### ISSUE TITLE
Response API 502 Bad Gateway with use:enhance

### ISSUE THREAD

**Issue by ubay1** [sveltejs/kit#10014]
### Describe the bug

I have a problem when my application is deployed to a VPS, I create a login form with use:enhance, if the username and password entered are appropriate then the response from the API is 502 bad gateway. but if what is entered is not appropriate then the response from the API is 200.

strangely this does not happen when I run it in docker.

**src/routes/(auth)/login/+page.server.ts**
```js
export const actions: Actions = {
	login: async ({ cookies, request }) => {
		const data = Object.fromEntries(await request.formData()) as {
			username: string;
			password: string;
			captcha: string;
			captchaId: string;
		};

		try {
			const dataSubmit = {
				username: data.username ?? null,
				password: data.password ?? null,
				captcha_code: data.captcha ?? null,
				captcha_id: data.captchaId ?? null
			};

			const res = await api().auth.login(dataSubmit);

			cookies.set('asik_token', res?.data.token.asik_token, { httpOnly: true });

			return {
				status: res?.status,
				data: res?.data.data
			};
		} catch (e: any) {
			return {
				status: e.status,
				data: null
			};
		}
	}
} satisfies Actions;
```

**src/routes/(auth)/login/+page@(auth).svelte**
```js
import { enhance, type SubmitFunction } from '$app/forms';

<script lang='ts'>
const submitFormLogin: SubmitFunction = ({ form, data, action, cancel }) => {
  isLoading = true;
  return async ({ result }: any) => {
     isLoading = false;
     if (result.data.status === 201) {
        const data = result.data.data.user;

        responseFetch = {
	   status: Number(result.data.status),
	   message: 'Berhasil masuk'
	};
         showToast = true;

          if (data.first_login) {
	    window.location.href = '/dashboard/bian';
	  } else {
	    window.location.href = '/change-password';
	  }
   } else {
       responseFetch = {
	  status: Number(result.data.status),
	  message: 'Username atau kata sandi Anda salah, silahkan coba lagi'
       };
	showToast = true;
    }
  };
};
</script>

<form method="POST" action="?/login" use:enhance={submitFormLogin} class="flex flex-col gap-4">
...
</form>
```

### Reproduction

on this project
[https://github.com/ubay1/asik-sveltekit](https://github.com/ubay1/asik-sveltekit)

you can check here https://ubay182.online/login

you can open the repository that I provided. then to reproduce you can try to open the web url that I provided. then try to input:
username: 1030073
password: e11abb83

from the code side there is nothing wrong, this is only wrong when the web has been deployed to the server. when I try to login the response obtained from use:enhance 502 Bad Gateway

### Logs

```Shell
Bad gateway Error code 502
Visit cloudflare.com for more information.
2023-05-23 03:42:42 UTC
You
Browser
Working
Singapore
Cloudflare
Working
ubay182.online
Host
Error
What happened?
The web server reported a bad gateway error.

What can I do?
Please try again in a few minutes.

Cloudflare Ray ID: 7cba4a58a99b3da7 • Your IP: Click to reveal 114.124.131.34 • Performance & security by Cloudflare
```

### System Info

```Shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 69.89 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
    Watchman: 2023.05.08.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 113.1.51.118
    Chrome: 113.0.5672.126
    Safari: 15.3
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
Please provide a proper reproduction for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by ubay1** [comment]
> Please provide a proper reproduction for the issue as instructed by the issue template:
> 
> > A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by ubay1** [comment]
> Please provide a proper reproduction for the issue as instructed by the issue template:
> 
> > A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by ubay1** [comment]
> Please provide a proper reproduction for the issue as instructed by the issue template:
> 
> > A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

Done

**Comment by gtm-nayan** [comment]
Please follow the instructions properly, especially the bolded part that says 

> must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**

**Comment by ubay1** [comment]
> Please follow the instructions properly, especially the bolded part that says
> 
> > must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**

from the code side there is nothing wrong, this is only wrong when the web has been deployed to the server. when I try to login the response obtained from use:enhance 502 Bad Gateway

**Comment by ubay1** [comment]
fix with add in nginx:
proxy_buffers 8 16k;
proxy_buffer_size 32k;

thanks for answer
