### ISSUE TITLE
Broken reactivity on `$page` store

### ISSUE THREAD

**Issue by moonmeister** [sveltejs/kit#10013]
### Describe the bug

I have a component that subscribes to $page.url. On that page, I change some app config that gets saved to the URL search params using `goto` from `$app/navigation` . This all works great. But I'm trying to render other components using that data from the url and they don't update on changes. It seems subscriptions (auto and manual) are broken with the `$page` store, or at least `$page.url`. 

### Reproduction

[Svelte Lab Repl](https://www.sveltelab.dev/#code=N4IgdADgTgpgLnAljKUDGIBcoBmiA2MWoaA9gHZwyUDOxIA1ouQCZYg0BuM%2BV%2BAhgCMAtAFdEADn4gANCEGicOFFgDaARgBMAZhnqADDICcM7QBY96gOyWArHv3qZEi0ZtGJd0xduftmywA2Swt1awcnM1DDE3MvA3swwwNdA08DJwknMJsw7PVgjO8ZX1MAsML1UPCiqIdjYoqQ41z9RP10tstk-V1A3LCHEwMTN2LS-0aDS3yepzi66djq8qqHROmmiVb25IKHCziJgLMTM09zmUWYqfKOy1bUrqSvI78Ao3mV5qKmv%2BfHM0zBs7ukar11t0rhsNp1svd-l9jLprg04mFQQ8HE8NoYJE8nGMwq5hvoLIFOhtqvY3mVjEizME4kYUdE0dV8nCfmsEg45q8fO96XodHT0fo7u0uWEaYKxRYzCdKrCIg4wYVAQtDgF0YMMUFIXkoTLxkKtLpJrqPgNqariab5fF1NKEfsinFJloaeVNPYWfUvQ4ALoAXzDcgg-DQDH4AHMYGAAFY0Cj0PCEehkSjUOB0bCMZhsTAcbi8HhCMSSaRyBRKFSYDSipZTGKtUlI463bnwjWE4b7LX1ZaWaU89TtDazB2WhUXYKXRlXYeo4f6%2B28sKeIluzVyz1usetSJs1duzT5O4doXi-vwvatLmD5u6v396Igg0m2meps3YceLENwRfRDG-HVqkpT9NQ%2BMEdjVPlihXdkEN%2BZ1p3AkdDR3eY7n5TdEJPZC1x5QF8KA-Jh07XVIMROliOiTlDVI9RVxuQMkPFPC0IpO0tF4nouJiUl2nyWUSjNX8GmHQJbTI0jXV7BxlSudxWlbSxVkU%2B1gRaQCDyvR0jB8QxFwXec-AVQjpNktDfgUu19GUsxWjgpowOKIylyuYJbBRcyCKHIi%2BPXZjKg1ETmnc5ljO8kp538p8-y7EL8jCpj8gVD80kAiEN2mHSTTk%2BF1VVKLXBixdbHirzEqkqYVTskr3T3DDPNsSIfN0WwlSuCyrisqYaOw9CPJ8HrTli7rGjY30A1mgxQ3DDh0HoFhEFgNA4FIKAAE96H4CAIDAAALOAAFt8DTAgiHzLMqFoegmFYdguB4PgK3EKRZHkRRlCgNRAlAvpPCsEx%2BmcCwJBMCRDECWI7mqDVSU8QI7hkQGDig5G6Pubcej6JFUNA8k0bBnoGN0gxYdJhoMZGXjgjGSYjFJVwbXiUL0cJmodxOewquKSZnPRmmyaGBndP3dT6aKQJuZo5j%2B1WDKDQ9D5b2NYaXiaOWpmElCd3JO9eMglnVQKlimL2DVDm1FSRcC2IBga%2BSmvk1z9kXAwKaJEDTFaWmTNaH21IdzYbgxgCjSpkUcIQ7dGZsC2XeKqD4Q9%2BcspI1OjV9kzdkp-Yxl18UOUw1DbbDpK6b9vKzXHT9z3g2XCdr54G7XXHcibzszejzYtYH5S4lR-2nRdN306w6qo71Wum%2B0GwMeFmO66rwP7dn42tCcUfpmX4Osfgvf9EWkM5HwRBBFW9aYE27a9vzABhUhRGzKAwFessrozW6KHu3Mj1CwvVLO9EQn1qw-TrP9BsdMG59xIlnYIJ8GjZVQkydWMw9LWzpCXE4nhbCkkCtoHyZoAQ6hOEJLBORNYYIdngryC447mkdpTYCKsmhmBiIzDWNDtYDklK8XChd8a8TLnwjuCIF4IyYk8Q4ugjDzicIQ1hCD8gDBwZMBhtgbAqObIGcOqCJTYOMP2cK1DpiejJCIlC7D0YPkhH3fQScTLMMkqMUxFiNGqxOATOkE09EzXaOjIOXgEHvg0gaFB%2B8YiwU-PpKE%2B4pylCcabUkS9si-jZsaNuXJwZoK6E47u9gUFgwcbyIpDlQI%2BgUbwnmOCDEzVqV42huDd7tP8fDdGFodRmKYu2UwXSqJ9KAgMr8wx5qw1CbPAYaV%2B7U2DGGJZcgoCvyoHmUAa0NpbV2vQAA1JGeMn8UDcA-smH%2BN0SD-xzBsgsz1ixfzAZWL6NZfr1g0KRTQexlbcjoWozWGw6FoMGHnNpdJtyJCbi8M2QtXFgtHj%2BJ4qDs7xPZi8RFrDoVtlVMM9GicOavjpC4BySt4IJ1KkQiZ-MiGBkCWfOQBy4wJkeZckA6ZWV3RuUA%2B5JY3rlnAVWb6tY-oAyBtCcVVixQUJkFYC0pIune0LkNURViYROiPEIyw%2Bt-h2x1aVHUlRrTYn1U6SoHDASLklZaaVsqfEc3hPCfs3pPEFIivwoFkiC7ulWOInmilmasxsSkXizrtwU3RX0q10r9yVAicG%2BNzE43hx6dPOiCSA1sM6GQwFmrCrhFnoSkKfpRy2i9j0KVdJbXaH7I%2BVYbqBF6WlUzOt-TIkFLjv8mWwU9ThynG5TSmNyUZt9lm3NuUe1mvqNatNk79wDGEeS71UEKaTAkPYCQAQrAeqnMzGw%2B5fWzJNU47J2tcoWo1FO6NARiWKrys6mWAJ9aVK-HcCZzCeYRWHc7E10djH7hzf3JNKrMHzIcII4NqrEkDtvdBZw67N3VUMdO1dGrq0ISsZk75qoEEeptiatdzgEMzqwRmxVeNjW1GqmWnNVi9gOtzT2no6RpEWOqcun9xi8o2T%2BdjCp6TYqmQvflewOkUFwMLYgtt%2BwUHIfA-oUlgG7UsP3EahNbj72cbHI6x0JDC6rBON%2Bv4Pbw0N3FBWyDXafnrgbcpu4qQJ0kZ9Bpn11D5M6fxcRAzUJtwKwUYevKO62SydbcRDhNnRT7jfKmsYUc7E-mc92cWM5x4OUnvbPNk6UrTSMe0BTxm7VodMo8ZuIKtwOMXAgtVaHAmXore2pTPNoieHxPE81ccGFhCi3lfFsWuRcJFPZtF9wqKGrYQSWKEimsihE-CczaNgv1f7S6nt3ilsMMuDVyxV6wMmJw1hHdMjyOrzsfk4ChbnH%2BP5GYNxSLgsLfPVJkzo4cE8Tsqp8EJV%2BvXZKEQu723O31LtWYPxQsTA1b%2BxWgHexJzNwe8C%2BEKJiYurO8jjVMdBykZW60774Ptt3dG77cbXtGvwWJxFMNyPIbSzWL7J1E3JGpSuEjgHq2ByWXBXU1nSjasQ8tJUIbzX7OZZRVom7aaBfiTFAT4rlG9JTdpb9vH2340OaNP13T%2BpCfm35z8e4OPFd1cmSE9L8CuvtwHdE8tNcFRg3m8rjuB5Wh3DRgfTGE1LfG%2B0CiETzqb3WLvWmup0Rv11AsweDTJmV3QcGBhwuE5m4scKvJDtgajtntEjjXExGYNxwIxumVdChY%2B-XtbkoCz8lY-dZL13irbALJiZE0eLPWmdhYc3qvgYa98Q9xjL34qdKTCsHRyKLbf0DP3dhwzjH%2BpS8iVr2Xk34KRYscHhjU4nHvrw%2BRmNmMl0ZZXz%2BgezDXR9vTyPxt8d-PMWdTpUTLvyZl4djDMb%2BGhcH9XVSY%2BoTa-16mY3mppg0uFGcOJOaCs0XeAQPeYqt%2BzqoMcuaa4a46DiFO-6rWuu76Lm-cl4uuzG76ke-EtiYW960%2BO%2BOeaaqmZ%2BRe4qYmD%2BdeT%2BQ2OaMWo6S6LWRmbWxuK81idBNB-%2BA2gB8B2UrBCSWWxOEune3%2B3eaMDeMy8SwubGoGKSvGhS-GusLCZGq2uSqop2aSDgxSVc9mjORoruMhRmchIs9KIAsY%2BApAgg-A%2BAYAaANAty7KmY1yD0%2BYT0RYvKZYAgAqLyUCIqDYpQ1m%2BQjOGKzYMBHMScxauklSBUXBQodBG2PglK-eaqBg0RxgZWqO4q7U4qt6kiBCiRqRkRSemRAEMW-Gt%2BYOZCskeuJkFwdslwi8M%2BoOvU7RLR%2BugUpRki5R2RcR-Mhgre-uhRTO7Roe%2BCY8ExjCFwfgScyiJRxeZR4qFR7gVR-MyitRHMFwQxDRJQ7OkwtgY0UxdsOicUUxCx3RSxvRKx-R6xJQAQwxdROxj%2ByRrRjxHxJxdIZxeRnRlxER1x7QfRsR9xvkkuVizxYxSRBCBxjxexnRpxCU8xP2Vx%2BRNxFsWkXyBo1R4JMiSeLxC4TRcx7xXkvxyJNWZwgJuhaJmJOCOkdBTx2xYxhJ-ixJ0xDJNI5JixaJQJNJdoWJnCGxuJu%2Box-WDJkx7JTIScpxnxfxKJAJPJ1JGJu%2B8kAyOJjJ%2BJzJYOrInS4xbJpxXUFoXJqJycSpAG-uqp5sgxwpBRUoUJQxEpiJXxhxspxpCpppGRfJZBD6kQQpGpopux7RU00xE0C4%2Bp3xPg8wbpNwPRvJ8RVmQ8wpaGcBRU3I72VWZwTRfo86badiHpUKDuWkbm0xgQGoyq1JVgqknirBBZ5p2mQ%2BrG2JdsaGrB8kBh%2BG9gVamZRKPyW8aB0xKZApUKZ%2BLw0xBGJhiZNCSEZSQaRcQ2OceuzZJgDZXGks16fmAKgyJJaGr2WmVsRKG5-CNI3Zloy52BwKo45iZszaMqo4qGJ5LaR2DcHpiaTEjx3JL5mRBgCZdJuWjZRouKK57c2Sg%2BAwfaMeD54soG-cH4lROKNKRuSwYI28ie7iWRIJ1JKuB6OS%2Bcy2Oc%2BWreaEFOX2VJnpOkqxOR9JkQ-xf4vCJ%2BzQhF2R2kuFn5Xpnyv5jCNFRiowQ2OIUInYZkJQ-M429MFJO20Fns7QFB2qUimxaaTFawJFipZFUl-5nsXFPFniG%2B2OEm%2BFKsjFhcCoLF6RF2yp3pbmtQImZwXFjS9QMkUF8kPQ2Zl2j2Dk55Y4xena9F2kaqx6JKOKZC1Oq%2B324RNwwRe5-cQKaFlJylplMRcFKlpJWxmpX2jRrJzpJwZwbJGlDQsZZp6FCVcVj%2B-pdpqVJJzR0pupAscpYlMVrF5Fdx%2BVeRJVpOexIZ4ZbRU0NVqRdVJlwJhVmRU0LV2UZV7VGVxVoE0ZdUeViVFFAxJQXUyVAZ4xRJ41wZ2V8pSUM1RVtEWgHFASS1pVbVq1CJ3xScG1tVaRURbFmG2J1pw19RK16Vp1hxSJVwOVvV11Zl7Fd1JQclEJTJo1J1lVhxPgRp71m1qCiFf4yFKEqFSKHiXlsNPlYSgadkAywxQV1JYltlzYN5ahSUSNB%2BBlxFxlX15piBapQpXR%2Bi0NUkuiYIQ08eu1fsoVdURNimD1LxDJPgImTRWVHRINjxwlFxkNVKc07QZ8Sy583hVADhFAeAsYSYzh10rh2Y7hoAnhICfKvhzykCwq7yoyUmYWfyoc240Gr5VimBc8XSO5NkE8acSkXgwsoK5tjtKN24-mEFkN%2BUScJw0q9lfwBZ2BoVf5oWvyYxdtKWjU7tjkztLkqahWHU9i-5nGAIqQs0QsXmSwdS0OdqUO4l6dYKbN-G3WNp0V9swsu6l%2BUmWkilzlEis6P5Ce76GwOZ4d1mw8o%2BNtHG4FQ0vqPQYyk5z5uqDOHGiM8SLapQwsnBGc9OKcJWikZaXEFwocucdOLtZt7dg8mUhcXtx%2BCZds%2BNKO%2B%2BZa01Sce6m6Tw0qO8LS9ose-C-dqdQ9mi4Gpmqww%2BS2ea29h9sd8h%2BWP4oRWIqB6CUELo-9B2a5To2BTiqlfGOMfdWEA9Dl4F84o9Gw2qRcgaSSekuGKpHaW9tdYiE2W1F9B5Dkx%2BE9RmU9q96WF2ZdZO5crsjty9JsdDw%2BlWm8hDxEddtoVt7%2Br6B%2Be%2B7cPQv99Mi67ckDTBd9Dart29vDztF6iN3D3aCjvcKjFtKsX2s24tmws0m2eEAp3aJtOMeExinti9HOqdcmXUpIFhnAiActWYitytFyatACtyWtDyoC-KetQqbyMCHyYdxjEdGKIDtkzDLNc98WOM1t2mp56M9tqWsdTkCdDDAwQ0-qYONKj6xtoTABtGblWE-IFep%2BNjdEmdzuiW9MCTckdZW5Bj-JWGimX9bc8I725SNmbThdWessYFOS5T-WBNyKmIfCZ6vTDcvcGeqZwKRZc92jyIEtENdK0tQAA)

### System Info

```Shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.17 GB / 15.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Firefox: 113.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.18.0 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.8
```

### Severity

serious, but I can work around it

### Additional Information

I think the workaround is basically manually managing another store, annoying but possible.

**Comment by moonmeister** [comment]
Possibly related to https://github.com/sveltejs/kit/issues/9374

**Comment by gtm-nayan** [comment]
@moonmeister Can you please recreate the repro as a plain git repro? SvelteLab neither has a download nor does it allow opening the output in a new window which makes it really difficult for us to debug.

**Comment by gtm-nayan** [comment]
It happens because you're mutating the searchParams on $page.url. That corrupts the internal state of the router so when you navigate it sees that the URL is unchanged and doesn't update the page store.

Create a new URL or URLSearchParams from $page.url instead of mutating it and use that in the goto.

**Comment by paoloricciuti** [comment]
> @moonmeister Can you please recreate the repro as a plain git repo? SvelteLab neither has a download nor does it allow opening the output in a new window which makes it really difficult for us to debug.

Just for info: you can both download the code and open the preview in a new window...to download the code press CMD+k and search for the download command. To open the preview in another window just click the little icon after the url bar over the preview.

**Comment by gtm-nayan** [comment]
> To open the preview in another window just click the little icon after the url bar over the preview.

That fails after clicking `Connect to project` but glad to know download works. Thanks. Is there anyway to download/clone it from the CLI directly?

**Comment by paoloricciuti** [comment]
> > To open the preview in another window just click the little icon after the url bar over the preview.
> 
> That fails after clicking `Connect to project` but glad to know download works. Thanks. Is there anyway to download/clone it from the CLI directly?

Oh that's an issue with StackBlitz and it only happens in certain browsers. I'll investigate btw.

Do you mean download/clone without accessing svelltelab? Or from the cli inside sveltelab?
