### ISSUE TITLE
Support Node Compat in Cloudflare Adaptor

### ISSUE THREAD

**Issue by arlair** [sveltejs/kit#10028]
### Describe the problem

Cloudflare announced Connect to PostgreSQL and it can provide database access from Cloudflare Workers, which combined with SvelteKit would be very powerful:
- https://developers.cloudflare.com/workers/databases/connect-to-postgres/

I'm not sure if it is meant to work as the documentation is for Cloudflare Workers and some old links suggest node_compat does not work in Pages. However, the documentation suggests otherwise, as I am using Cloudflare Pages with node_compat flags enabled via the Cloudflare Dashboard as found here:
- https://developers.cloudflare.com/workers/runtime-apis/nodejs/#enable-nodejs-with-pages-functions

I tried with a project and found a local vite build would fail due to `pg` being a node library when using the cloudflare-adaptor.

### Describe the proposed solution

I found this `build-worker` project, that includes the `@esbuild-plugins/node-modules-polyfill` with how to use it here:
- https://github.com/brillout/build-worker/blob/master/build-worker.mjs#LL8C8-L8C8

and it turns out Wrangler also uses this library:
- https://developers.cloudflare.com/workers/wrangler/configuration/#add-polyfills-using-wrangler

I made my own copy of `@sveltejs/adapter-cloudflare` to test and added this library. It builds locally and in Cloudflare Pages. While my code compiles and deploys, it does not seem to work as logging from Cloudflare Pages Functions gives the error: `ReferenceError: process is not defined` error, so I am not sure if I am missing something for the correct polyfill, or it is not possible at the moment due to a Cloudflare Pages limitation.

The [documentation states](https://developers.cloudflare.com/workers/runtime-apis/nodejs) `Node.js APIs are available under the node: prefix, and this prefix must be used when importing modules, both in your code and the npm packages you depend on`.  However, the [database connect documentation](https://developers.cloudflare.com/workers/databases/connect-to-postgres/) does not mention this when it tells you to add the `pg` package and `pg` would not be using the `node:` prefix internally. I also thought I found mention of another proposed option where the `node:` prefix was not required, but unfortunately I cannot find it.

### Alternatives considered

Wrangler 2 source code is a lot more complicated and seems to have a `nodejsCompat` option that can be passed that is used here:
 - https://github.com/cloudflare/workers-sdk/blob/4082cfcbdf08740d4a608d3d87df22e51ad0ce4a/packages/wrangler/src/bundle.ts#L107

[This announcement](https://blog.cloudflare.com/workers-node-js-asynclocalstorage/) mentions the Node.js `APIs are provided directly by the `[open-source Cloudflare Workers runtime](https://github.com/cloudflare/workerd)`, with no need to bundle polyfill implementations into your own code.`, so perhaps we only need to be able to compile it without the polyfill and then the `nodejs_compat` flag handles it?

### Importance

would make my life easier

**Comment by jadbox** [comment]
@arlair any luck on finding a workaround? The esbuild polyfill solution ideal since that is what Wrangler is using, but I'm also not sure why it's causing runtime errors for you. 😔

**Comment by eltigerchino** [comment]
Closed by https://github.com/sveltejs/kit/pull/10544
