### ISSUE TITLE
Support of GET methods prerendering

### ISSUE THREAD

**Issue by nosovk** [sveltejs/kit#10029]
### Describe the bug

after migration to new route format (rss.xml/+server.ts) I fount that if I use static-adapter, it seems that prerender of GET server methods broke.
Before update I added GET method for server endpoint and was able to render static rss feed and sitemap

It seems that before update static adapter was trying to prerender server response, but now - don't,

### Reproduction

- src\routes/rss.xml
```javascript
export const GET: RequestHandler = async () => {
  const body={};
  return new Response(body, {
    headers: {
      'Cache-Control': `max-age=0, s-maxage=${3600}`,
      'Content-Type': 'application/xml'
    }
  });
};
```

### Logs

```Shell
@sveltejs/adapter-static: all routes must be fully prerenderable, but found the following routes that are dynamic:
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 5.76 GB / 31.88 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.50
    @sveltejs/kit: next => 1.0.0-next.589
    svelte: ^3.59.1 => 3.59.1
    vite: ^4.3.8 => 4.3.8
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
To force a page/endpoint to prerender even if it looks like a dynamic route, you need to specify `export const prerender = true` - https://kit.svelte.dev/docs/page-options#prerender
