### ISSUE TITLE
documentation code cannot be selected and copy pasted

### ISSUE THREAD

**Issue by muka** [sveltejs/kit#10031]
### Describe the problem

documentation code cannot be selected and copy pasted

### Describe the proposed solution

allow copy paste!

### Importance

would make my life easier

### Additional Information

using chrome on ubuntu

**Comment by Rich-Harris** [comment]
what code? i can select and copy e.g. this just fine

<img width="872" alt="image" src="https://github.com/sveltejs/kit/assets/1162160/f494c05b-bb9c-4da2-a4c3-4215680c9b14">

**Comment by muka** [comment]
I tried recording a video, nothing selects on my side :(
https://github.com/sveltejs/kit/assets/1021269/f266eec0-54ac-49dd-bb77-09f8c532b576

Thank you!

**Comment by CaptainCodeman** [comment]
Maybe try it in an incognito window to see if it's caused by a browser plugin.

**Comment by muka** [comment]
No, same in incognito. In firefox just works well, anyway

**Comment by chinmaykh** [comment]
How a about a copy button to copy the code? (Usually present in docs)
The service-worker example is quite large and manually selecting that much text is a problem.

**Comment by s3812497** [comment]
closed by https://github.com/sveltejs/kit/pull/10187
