### ISSUE TITLE
`svelte-package` doesn't respect tsconfig options

### ISSUE THREAD

**Issue by WillsterJohnson** [sveltejs/kit#10035]
### Describe the bug

Say for example you want to provide some TS enums, but you don't want them to exist as runtime objects.
Instead, you want TypeScript to replace them at buildtime with the respective values.

The way to do this is to disable `preserveconstenums`, and ensure that the enums you want to remove at buildtime are declared as `const`. In a SvelteKit project, the generated tsconfig sets `isolatedmodules`, so you'll have to disable this also.

You cannot do this if you happen to be working in a package which is built by `svelte-package`, as it ignores your TSConfig. Or at least, it will ignore `isolatedmodules` and `preserveconstenums`.

### Reproduction

https://github.com/WillsterJohnson/svelte-package-ignores-tsconfig

### System Info

```Shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 4.75 GB / 15.34 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.8.1 - ~/.nvm/versions/node/v19.8.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.8.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v19.8.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Firefox: 112.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.0 => 2.1.0 
    @sveltejs/kit: ^1.18.0 => 1.18.0 
    @sveltejs/package: ^2.0.2 => 2.0.2 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.8 => 4.3.8
```

### Severity

annoyance

### Additional Information

The current workaround is to add another build-step, which uses TypeScript directly to compile any `.ts` files which create or use unpreserved constant enums.
This is a pain, so it's easier to just recompile all TypeScript files.
This causes any forwarding of Svelte components to error, so you must add `// @ts-expect-error`.
This causes tooling which is aware of how to handle Svelte imports to error, so you actually need to use the unsafe `// @ts-ignore`.
This can cause errors which ought to show up (eg, the Svelte file doesn't exist) to not show up at all.
Missing errors will allow unusable code to pass through your tooling and onto the registry if you aren't diligent.

**Comment by dummdidumm** [comment]
Svelte files are operated on file-by-file, and Vite does so, too, which is why `isolatedModules` is needed. Sadly, this means certain features like `const enum` are not usable, or rather, they can't be erased completely. This is a tradeoff we have to make, and there's no way around this, so I'm closing this as "works as expected".
