### ISSUE TITLE
Allow to manually override "Cannot prerender endpoints that have mutative methods" for pages

### ISSUE THREAD

**Issue by AndreasHald** [sveltejs/kit#10047]
### Describe the problem

We're using GraphQL quite heavily throughout our app, and since most graphql clients prefer to query using POST instead of GET, We can't prerender pages.

I understand why this error is thrown if you use POST within a load function, it makes sense to warn that this could be unintended. 

To resolve it we either have to
- Go around our graphql client and use GET for the query (with the disadvantages this entails)
- Query the graphql server from a +page.server function
- Discarding graphql

Neither of which we'd like to do

### Describe the proposed solution

If there are no technical problems with simply disabling the warning using some flag or config on the users on cognizance.

It could allow us to use POST in a prerendered load function fully knowing that if that post has side effects they will not work as expected.

### Importance

would make my life easier

**Comment by eltigerchino** [comment]
I think you can send a POST request in a load function. The error message you  mentioned in the title only comes from this block of code which is if you try to prerender a `+server.js` file.
https://github.com/sveltejs/kit/blob/65b81de97b35469008bdace105e32d3fbc15b8d1/packages/kit/src/runtime/server/endpoint.js#L27-L29
