### ISSUE TITLE
Too many HTTP redirects when throwing redirect from form action to the same page

### ISSUE THREAD

**Issue by ctiospl** [sveltejs/kit#10061]
### Describe the bug

Throwing a redirect from a form action causes too many HTTP redirects.
It seems the the formdata gets send along with the redirect causing an infinite redirect loop.

### Reproduction

https://github.com/ctiospl/svelte-kit-redirect-loop

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Max
    Memory: 113.38 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox Developer Edition: 114.0
    Safari: 16.5
  npmPackages:
    svelte: ^3.54.0 => 3.59.1
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
That is because of the status code you're using.

> The method and the body of the original request are reused to perform the redirected request. In the cases where you want the method used to be changed to [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET), use [303 See Other](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303) instead. This is useful when you want to give an answer to a [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT) method that is not the uploaded resources, but a confirmation message (like "You successfully uploaded XYZ").

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307
