### ISSUE TITLE
hooks.server : ReferenceError: __filename is not defined in ES module scope

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#10077]
### Describe the bug

Using @sveltejs/adapter-node and some function in hooks.server.ts, I get the following error:

```
file:///home/wighawag/dev/github.com/bug-reproduction/svelte-kit-hooks-server/build/server/chunks/hooks.server-8e68a0a6.js:335
                      if (fileName !== __filename) {
                                       ^

ReferenceError: __filename is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/wighawag/dev/github.com/bug-reproduction/svelte-kit-hooks-server/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.16.0
```

### Reproduction

Repo: https://github.com/bug-reproduction/svelte-kit-hooks-server

```bash
git clone  https://github.com/bug-reproduction/svelte-kit-hooks-server
cd svelte-kit-hooks-server
```

```bash
pnpm i
pnpm build
node build
```

### Logs

```Shell
file:///home/wighawag/dev/github.com/bug-reproduction/svelte-kit-hooks-server/build/server/chunks/hooks.server-8e68a0a6.js:335
                      if (fileName !== __filename) {
                                       ^

ReferenceError: __filename is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/wighawag/dev/github.com/bug-reproduction/svelte-kit-hooks-server/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.16.0
```

### System Info

```Shell
System:
    OS: Linux 5.19 KDE neon 5.27 5.27
    CPU: (16) x64 AMD Ryzen 7 PRO 6850U with Radeon Graphics
    Memory: 17.08 GB / 30.13 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 4.0.0-rc.44 - ~/.volta/tools/image/yarn/4.0.0-rc.44/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chromium: 113.0.5672.126
    Firefox: 112.0.1
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.5.0 => 1.20.0
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

**Comment by tcc-sejohnson** [comment]
I don't think this is a bug -- but you can probably replace `__filename` with `fileURLToPath(import.meta.url)` and it should work for you.

**Comment by wighawag** [comment]
I am reopening as I am currently not sure it is something to fix in vite or svelte-kit and there seems to be a strong opinion that __filename is correct in such dependencies (being cjs file), see : https://github.com/WiseLibs/better-sqlite3/issues/887#issuecomment-1322829223

**Comment by tcc-sejohnson** [comment]
I am... not an expert in this stuff. But if you find `node-bindings` in your `node_modules` folder and add `"type": "commonjs"` to the `package.json`, does it fix the issue?

**Comment by wighawag** [comment]
Thanks @tcc-sejohnson for helping

unfortunately adding `"type": "commonjs"` result in the same error

**Comment by biowaffeln** [comment]
I ran into the same issue today. For some reason what fixed the issue was moving better-sqlite3 from "devDependencies" to "dependencies".

**Comment by wighawag** [comment]
Ha, yes that works, thanks @biowaffeln !

I guess that's how vite detect whether it needs to do something

I close the issue then

**Comment by tmrsiteops** [comment]
> I ran into the same issue today. For some reason what fixed the issue was moving better-sqlite3 from "devDependencies" to "dependencies".

Unfortunately this does not fix the issue for me. I already have better-sqlite3 in my devDependencies and I'm still getting this error about `__filename` from the `bindings` dependency

**Comment by khromov** [comment]
>  For some reason what fixed the issue was moving better-sqlite3 from "devDependencies" to "dependencies".

It works because the root problem is that `devDependencies` are automatically bundled using Rollup, while normal dependencies are left as-is in the node_modules folder.

This is mentioned briefly in the adapter-node docs:

> Development dependencies will be bundled into your app using [Rollup](https://rollupjs.org/). To control whether a given package is bundled or externalised, place it in devDependencies or dependencies respectively in your package.json.

https://kit.svelte.dev/docs/adapter-node#deploying

**Comment by efstajas** [comment]
I just ran into a very similar issue after trying to build our app with `adapter-node` for the first time (previously `adapter-netlify`). Instead of __filename my problem was with __dirname.

To figure out which dependency was the culprit I `grep`-ed for `__dirname` on a local build of the app, found it, and then tried to guess which dependency it came from based on adjacent code. It turned out to be `jimp`. And indeed, moving it from `devDependencies` to `dependencies` fixed it. Thanks @biowaffeln!

It would really be amazing if this would already error during build time and reference the problematic dependency by name so you don't have to go on a hunt.

**Comment by shirecoding** [comment]
i get this as well, i traced it to a library i use called pngjs, but its already in devdependencies.

vite run works, but node doesnt i have no idea why as there is no logs at all.

**Comment by efstajas** [comment]
@shirecoding It should be a `dependency`, not `devDependency`.

**Comment by shirecoding** [comment]
> @shirecoding It should be a `dependency`, not `devDependency`.

yes i meant dependency, i still get the issue though. Not sure if its another library or svelte or the node adaptor itself

```
{
  "name": "app-svelte",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev",
    "build:static": "vite build",
    "build:server": "ADAPTER=node vite build",
    "build": "npm run build:static && npm run build:server",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
    "lint": "prettier --check . && eslint .",
    "format": "prettier --write .",
    "test": "vitest"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.2.5",
    "@sveltejs/adapter-static": "^3.0.5",
    "@sveltejs/adapter-node": "^5.2.5",
    "@sveltejs/kit": "^2.6.1",
    "@sveltejs/vite-plugin-svelte": "^3.1.2",
    "@tailwindcss/forms": "0.5.9",
    "@tailwindcss/typography": "0.5.15",
    "@types/eslint": "9.6.1",
    "@types/google.maps": "^3.58.1",
    "@types/js-cookie": "^3.0.6",
    "@types/jsonwebtoken": "^9.0.7",
    "@types/lodash-es": "^4.17.12",
    "@types/mime-types": "^2.1.4",
    "@types/ngeohash": "^0.6.8",
    "@types/node": "22.7.4",
    "@types/pixi.js": "^5.0.0",
    "@types/pngjs": "^6.0.5",
    "@typescript-eslint/eslint-plugin": "^8.8.0",
    "@typescript-eslint/parser": "^8.8.0",
    "@vitest/browser": "^2.1.2",
    "@vitest/ui": "^2.1.2",
    "autoprefixer": "10.4.20",
    "eslint": "^9.11.1",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.30.0",
    "eslint-plugin-svelte": "^2.44.1",
    "mime-types": "^2.1.35",
    "postcss": "8.4.47",
    "prettier": "^3.3.3",
    "prettier-plugin-svelte": "^3.2.7",
    "svelte": "^4.2.19",
    "svelte-check": "^4.0.4",
    "tailwindcss": "3.4.13",
    "tslib": "^2.7.0",
    "typescript": "^5.6.2",
    "vite": "^5.4.8",
    "vite-plugin-node-polyfills": "^0.22.0",
    "vite-plugin-static-copy": "^1.0.6",
    "vite-plugin-tailwind-purgecss": "0.3.3",
    "vitest": "^2.1.2"
  },
  "type": "module",
  "dependencies": {
    "@googlemaps/js-api-loader": "^1.16.8",
    "@internationalized/date": "^3.5.6",
    "@pixi/sound": "^6.0.1",
    "@solana/pay": "^0.2.5",
    "@solana/qr-code-styling": "^1.6.0",
    "@solana/wallet-standard-util": "^1.1.1",
    "@trpc/client": "^10.45.2",
    "@trpc/server": "^10.45.2",
    "bits-ui": "^0.21.16",
    "bs58": "^6.0.0",
    "clsx": "^2.1.1",
    "cmdk-sv": "^0.0.18",
    "countries-and-timezones": "^3.7.0",
    "encoding": "^0.1.13",
    "gsap": "^3.12.5",
    "html5-qrcode": "^2.3.8",
    "jsonwebtoken": "^9.0.2",
    "lodash-es": "^4.17.21",
    "lru-cache": "^11.0.1",
    "lucide": "^0.447.0",
    "lucide-svelte": "^0.447.0",
    "minio": "^8.0.1",
    "mode-watcher": "^0.4.1",
    "nft.storage": "^7.2.0",
    "ngeohash": "^0.6.3",
    "node-cron": "^3.0.3",
    "paneforge": "^0.0.6",
    "pixi.js": "^8.4.1",
    "pngjs": "^7.0.0",
    "redis-om": "^0.4.6",
    "simplex-noise": "^4.0.3",
    "svelte-sonner": "^0.3.28",
    "tailwind-merge": "^2.5.2",
    "tailwind-variants": "^0.2.1",
    "trpc-sveltekit": "^3.6.2",
    "tweetnacl": "^1.0.3",
    "vaul-svelte": "^0.3.2",
    "zod": "^3.23.8"
  }
}

```

**Comment by shirecoding** [comment]
i traced it down to a secondary dependency

```
npm ls bindings
app-svelte@0.0.1 /Users/benjaminhon/Developer/christmas/christmas/app
└─┬ @solana/pay@0.2.5
  └─┬ @solana/web3.js@1.95.3
    └─┬ bigint-buffer@1.1.5
      └── bindings@1.5.0
```

the issue is @solana/pay@0.2.5 is already in dependencies. This means that sveltekit doesnt process it if it is not a direrect dependency?

**Comment by shirecoding** [comment]
i solved it by manually adding "bindings" to my dependencies, and it seems it works. Seems secondary dependencies are an issue

**Comment by smash-llj** [comment]
(node:23896) UnhandledPromiseRejectionWarning: ReferenceError: __filename is not defined
If you have similar problems, please move better-sqlite3 from dependencies to devDependencies. The specific reason is explained by 👆.

**Comment by philmas** [comment]
> I ran into the same issue today. For some reason what fixed the issue was moving better-sqlite3 from "devDependencies" to "dependencies".

You're a hero @biowaffeln
