### ISSUE TITLE
Endpoint redirect support?

### ISSUE THREAD

**Issue by danawoodman** [sveltejs/kit#1008]
**Describe the solution you'd like**

I would love to be able to have endpoints support redirects just like `load` does, meaning returning something like `{ redirect: "/success", status: 302 }` from an endpoint would redirect the request.

I know a redirect won't make sense for API type requests, but if you want an HTML form submission without JS, you would need server redirecting as far as I'm aware.

**Describe alternatives you've considered**

Of course you can do client side requests using `fetch` but if you want your form to work (and behave) similar to client redirecting, you would need the endpoint to redirect the form submission request. 

**How important is this feature to you?**

Not a show-stopper, but something that I think a lot of users could leverage to make more accessible apps.

**Additional context**

Here is what I'm proposing:

`src/routes/Contact.svelte`:

```html
<script>
  let email
  let submit

  function handleSubmit() {
    submit = fetch('/contact', {
      method: 'POST',
      body: JSON.stringify({ email }),
      headers: { 'content-type': 'application/json' },
    })
      .then((resp) => resp.json())
      .finally(() => setTimeout(() => (submit = null), 5000))
  }
</script>

{#if submit}
  {#await submit}
    <p>Sending...</p>
  {:then resp}
    <p>🎉 Done!</p>
    <pre>RESPONSE: {JSON.stringify(resp, null, 2)}</pre>
  {/await}
{/if}

<form on:submit|preventDefault={handleSubmit} action="/contact" method="post">
  <input type="email" name="email" bind:value={email} />
  <button type="submit">Submit</button>
</form>
```

The `action` would be a fallback if JS isn't enabled.

`src/routes/contact.js`:

```js
export async function post(req) {
  const isFormSubmit =
    req.headers['content-type'] === 'application/x-www-form-urlencoded'

  const email = isFormSubmit ? req.body.get('email') : req.body.email

  // Simulating some magic here... 🧙
  await new Promise((resolve) => setTimeout(resolve, 300))

  return isFormSubmit
    ? { redirect: `/contact?success=true&email=${email}`, status: 302 }
    : { body: { success: true, email } }
}
```

This example works when JS is enabled but not otherwise

**Comment by Conduitry** [comment]
You can already do this by returning a `Location` header from the endpoint.

https://kit.svelte.dev/docs#routing-endpoints
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

There's no need for an extra abstraction here because this code is always run on the server. `load()` has `redirect` because it does different things when the page is being rendered on the server vs on the client.

**Comment by danawoodman** [comment]
Oh weird, @benmccann didn't even know this 😅, so maybe I'll add a PR to add a note to that effect?
