### ISSUE TITLE
Problem with CSR overwriting data already completed by SSR.

### ISSUE THREAD

**Issue by lzdetourer** [sveltejs/kit#10108]
### Describe the bug

I have data that takes a long time to look up. I'm trying to show a temporary value during that time. It seems to be working fine.

However, I discovered that SSR had already completed the data over a long period of time. The completed data was immediately overwritten by the CSR with temporary values. And after a long time it will be finished. (/)
I can see the real value very momentarily. If you view the HTML source, you can clearly see the real value created by SSR.

It's probably recognizing that you set it as a temporary value as a newer data change. In this case, is there a way to intentionally not render it?

I tried using toplevel-await when retrieving data that takes a long time with one attempt. (/toplevel-await) This solved the overwrite problem, but all events didn't work during that time.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-zokw5v?file=src%2Froutes%2F%2Bpage.svelte

path1 : /
path2 : /toplevel-await

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11600KF @ 3.90GHz
    Memory: 17.12 GB / 31.90 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.37)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.5.0 => 1.20.1
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
It sounds like what you want is #9160 so I'm closing this issue as a duplicate. As an alternative, if your returned data is serializable you can use a `+page.server.js` `load` function which will not have this problem.
