### ISSUE TITLE
Remove the "top level promises are awaited" feature

### ISSUE THREAD

**Issue by gtm-nayan** [sveltejs/kit#10106]
### Describe the problem

Why: it leads to confusing rules, requires streamed promises to be unnecessarily nested and gets in the way of some fixes sometimes.

### Describe the proposed solution

I don't think there are many people that know about the feature or are using it, but remove this only in v2 cause it would be a breaking change.

### Importance

nice to have

**Comment by thet0ast3r** [comment]
So will this mean in the future all promises will be streamed?

**Comment by adamshand** [comment]
> So will this mean in the future all promises will be streamed?

Just because I was wondering about this as well.  Yes, looks like all promises will be streamed.

https://twitter.com/Rich_Harris/status/1733598081839415331
