### ISSUE TITLE
Allow more flexible, simple and intuitive routing (beyond +page convention)

### ISSUE THREAD

**Issue by camiloux** [sveltejs/kit#10119]
### Describe the problem

I find it very confusing that everything is named "page", and that each page needs its' own folder. It doesn't follow common and intuitive route patterns like in static HTML.
<img width="926" alt="Screenshot 2023-06-08 at 8 24 01 AM" src="https://github.com/sveltejs/kit/assets/98063832/5ce9b459-bbab-4326-8621-abfa313f4e0f">

### Describe the proposed solution

Allow a more flexible and intuitive routing naming convention. Here's an idea: + for pages (or endpoints), - for layouts and errors
![Screenshot 2023-06-08 at 8 41 42 AM](https://github.com/sveltejs/kit/assets/98063832/49f3a8ae-aca4-4296-a935-fd5fa8660964)

### Alternatives considered

In an ideal world, use _ to differentiate pages from components in the routing system (similar to Astro).
![Screenshot 2023-06-08 at 8 50 00 AM](https://github.com/sveltejs/kit/assets/98063832/637615a8-f089-4069-9746-75dc47c40cfd)

### Importance

would make my life easier

### Additional Information

For me, this is the main drawbacks of Sveltekit currently. It makes things way more complicated than needed and **takes away the liberty** of naming things the way you want / need in your app. It also hinders productivity: you spend precious seconds figuring out which "+page" you are currently looking at. I makes you jump back and forth from the project structure to the editor. Constantly.

**Comment by ghostdevv** [comment]
Hey, we used to have the system you showed in your second screenshot (`about.svelte`, `index.svelte` etc) but switched from that before SvelteKit 1.0. The [discussion is a long read](https://github.com/sveltejs/kit/discussions/5748) but worth it if you want to fully understand why. Let me know if you have any questions

**Comment by camiloux** [comment]
I understand. I still believe there's a huge room for improvement here. Even after reading the discussion. I end up using Astro with Svelte constantly for simple content focused projects. Just because dealing with the Sveltekits' routing system is anything but intuitive.
