### ISSUE TITLE
depends() stops working as expected after form submission

### ISSUE THREAD

**Issue by themajashurka** [sveltejs/kit#10123]
### Describe the bug

Registering a custom dependency with `depends('load:child')` within a page's load function, and calling `invalidate('load:child')` with `setInterval` in the sibling `+page.svelte` in order to mimic a single polling behaviour, causes `+layout.server`'s load function to be called as well **after submitting form** on same page.

### Reproduction

https://github.com/themajashurka/depends-repro

Go to /child. You should see periodic logs on server about child load function being called.
Submit form. Now layout load function is called too.

### Logs

server-side

```
root load runs
layout load runs
child load runs
child load runs
child load runs
child load runs
child load runs
child load runs
layout load runs
child load runs
layout load runs
child load runs
layout load runs
child load runs
layout load runs
child load runs
layout load runs
```

### System Info

```Shell
System:
    OS: macOS 11.7.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
    Memory: 879.37 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.20.2 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by HanLap** [comment]
Hi,
this seems to happen because the enhance-action calls `invalidateAll`. 

 `invalidate_all` sets `force_invalidation` to true, which causes all following `invalidate` calls to invalidate everything. 

Similar behavior is described in https://github.com/sveltejs/kit/issues/10677.
