### ISSUE TITLE
Passing dereferenced data from PageServerData not updating content.

### ISSUE THREAD

**Issue by yan5** [sveltejs/kit#10127]
### Describe the bug

I have a left side navigation bar with two links for 'Active' and 'Verified' users that has the `href` set as below.

<a href="https://localhost/user?s=active">Active</a> --> /user?s=active
<a href="https://localhost/user?s=verified">Verified</a> --> /user?s=verified

The page get served from corresponding +page.server.ts (where user fetched from DB) and +page.svelte.

But I'm seeing a strange problem. The page content (user.id for eg) shows first time when I clicked on either of Active or Verified. But the content remains same if I click the other one, it doesn't get refreshed with correct content.

### Reproduction

Below code works:
```
<script lang="ts">
	import type { PageServerData } from './$types';
	export let data: PageServerData; //data from DB changes based on filter 'active' or 'verified'
</script>

{#each data.users as user, i}
	{user.uid}
{/each}
```

Below code throws that strange problem. The only difference is in the `#each` loop I used `users` (which I assigned from data.users) instead of `data.users`

```
<script lang="ts">
	import type { PageServerData } from './$types';
	export let data: PageServerData;
        const users = data.users;
</script>

{#each users as user, i}
	{user.uid}
{/each}
```

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 2.68 GB / 15.41 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 114.1.52.122
    Chrome: 114.0.5735.106
    Firefox: 113.0.2
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4 
    @sveltejs/kit: ^1.20.2 => 1.20.2 
    svelte: ^3.59.1 => 3.59.1 
    vite: ^4.3.9 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by ghostdevv** [comment]
I believe it's because you are doing `const users = ...` which isn't reactive, but `data.users` is in this case

**Comment by geoffrich** [comment]
Yes, if you want to use a separate variable you need to make the users assignment reactive - see [the docs](https://kit.svelte.dev/docs/state-management#component-state-is-preserved).

```
$: users = data.users;
```
