### ISSUE TITLE
Example of the state of the data in the documentation

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#10135]
### Describe the problem

Although I am familiar with SvelteKit, I often get lost as to what type of what it actually contains.
(You will say that in this case, I don't really know SvelteKit}.

### Describe the proposed solution

In the code in the documents, there should be a snapshot(state) of the stack from an example moment, with example code. Literally, as if someone made a breakpoint and displayed a panel with the contents of the stack, variables and objects that are at a given breakpoint.

Then, as if on the palm of your hand, you can see what type of data in what properties, in what object can be contained.
There would simply be a preview of variables and objects from a sample place in the code that corresponds to the place discussed in the documentation.

This is something I haven't seen in any documentation yet, it would be pioneering, something that would make it easier to understand SvelteKit on a level like if you "played with the code and DevTools and Debugger yourself."
I believe this is something amazing.

### Importance

nice to have

**Comment by ghostdevv** [comment]
I'm not sure exactly what you mean, could you provide an example?

**Comment by lukaszpolowczyk** [comment]
@ghostdevv That in the example about, for example, the `load` function, a side panel would appear on the right, in the code, and there would be the objects contained in that function, if you make a breakpoint inside the load function.

This panel would look like "Scopes" in the side panel, in the web browser Debugger.

![obraz](https://github.com/sveltejs/kit/assets/16800535/6d04b1aa-1be6-4f90-b422-c057292d9e6c)

He would have some example state, such as in the example in the given place in the documentation.

This way you have a "live" example, and there is nothing better than a live example, with a preview of what these values look like, not just signed links to data types as it is now. (Not to be confused with Learn Svelte dev, because it's different).

**Comment by ghostdevv** [comment]
I'm not sure whether it makes sense to have this in the docs since we already have the typing information available, and having a dev tools window wouldn't provide tons of value when you just want information about the structure of things :pray:

**Comment by lukaszpolowczyk** [comment]
@ghostdevv It would only look like this.
It would just be a list of objects/variables and nothing more. It could be expanded (tree structure) - nothing more.
This is not supposed to be a copy of devTools, just such a living example of data. Nothing more.
No editing, no next steps, just the view, the view itself, the preview.
Just that, and so much more.

What we have in the documentation causes me to get lost and I'm not sure what goes where, even though I'm the author of the "Range and Direction of Data Flow in SvelteKit" diagram (shared here in the discussions).

The problem is that a type is given, but that type is a reference, and in a reference, the structure sometimes also consists of links. 
This is so obfuscated. At the 1.0.next stage, the documentation had a moment that it was more readable, but then the types were moved and only linked.

What I'm proposing, this panel with a live example, will make you know what kind of data it is, because you just see it, as if you were seeing it in the debugger. (I stress, just the view, and just a simple list of objects/variables from the scope)

**Comment by FractalHQ** [comment]
@lukaszpolowczyk This seems pretty complex but you seem to have a clear vision of your idea.  Perhaps you could create a demo of this and if it winds up making sense for the docs, we can work on a PR for it.  If not, then it will still be useful to have it on a web page somewhere 👍

**Comment by lukaszpolowczyk** [comment]
@FractalHQ I'll try to do something, but I don't know when, at ease.

**Comment by ghostdevv** [comment]
I'll close this for now, but feel free to reopen when you have an example we can look at :pray:
