### ISSUE TITLE
`inlineStyleThreshold` units are not specified in doc website or JS Doc comments

### ISSUE THREAD

**Issue by Nick-Mazuk** [sveltejs/kit#10141]
### Describe the bug

What is the units for the `inlineStyleThreshold` config option? Characters? Bytes? Kilobytes?

This should be specified in the docs and JS Docs.

### Reproduction

https://kit.svelte.dev/docs/configuration#inlinestylethreshold

### System Info

```Shell
N/A
```

### Severity

annoyance

### Additional Information

Feel free to move this issue to a better location for docs issues.

**Comment by gtm-nayan** [comment]
It's length, as in what String.prototype.length on the file's contents would give you.
