### ISSUE TITLE
+layout.js/ts when ssr off and 404 error happens, then data in load function is null

### ISSUE THREAD

**Issue by ToP29** [sveltejs/kit#10157]
### Describe the bug

When i turn off ssr (in +layout.js) and 404 error happens, then data is always null in +layout.js in load function

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ck2eek?file=src%2Froutes%2F%2Blayout.js&terminal=dev

go to some non-existing page and try turning ssr on and off and observe log in console

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.20.2 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

**Comment by s3812497** [comment]
This happens because disabling SSR in `+layout.js` causes `+layout.server.js` to never run for any pages.

**Comment by brunobely** [comment]
Maybe this is the intended behavior, but I've been facing a similar bug and just did some testing by putting `console.log`s at the top of each of the `handle`, `load` (server), `load` (client), functions, and this is what I found:

Logs, in order:
- when SSR is **disabled** in `+layout.ts`:
  - visiting a page that exists (no error):
    - handle (server)
    - server load (server)
    - load (browser)
  - visiting a page that doesn't exist (404):
    - handle (server)
    - load (browser, error because server load didn't run)

- when SSR is **enabled** in `+layout.ts`:
  - visiting a page that exists (no error):
    - handle (server)
    - server load (server)
    - load (server)
    - load (browser)
  - visiting a page that doesn't exist (404):
    - handle (server)
    - server load (server)
    - load (server)
    - load (browser, *no error* because server load *did* run)
