### ISSUE TITLE
Interdependent params matching

### ISSUE THREAD

**Issue by iolyd** [sveltejs/kit#10167]
### Describe the problem

In an effort to create language-specific urls, some i18n app setups may require a way to use param matchers that depend on parent params present in a route. This can easily become necessary if we want to avoid linguistically incorrect param combinations that could otherwise mix languages. For example, say I have the following sveltekit routes folder structure:
```
> routes
  > [lang=lang]
    > [blog=blog]
    > [projects=projects]
...
```
Where `lang` is a simple matcher like so that checks against some expected langs/locales my app is configured for:
```ts
// /params/lang.ts

export const LANGS = {
  FRENCH: 'fr',
  ENGLISH: 'en'
} as const;

export type Lang = ValueOf<typeof LANGS>;

export const match: ParamMatcher = (param) => {
  return Object.values(LANGS).indexOf(param as any) > -1;
};
```
and `blog` could be a simple matcher like:
```ts
// /params/blog.ts

const BLOG_SEGMENT = {
  LANGS.FRENCH: 'blogue',
  LANGS.ENGLISH: 'blog'
} as const satisfies Record<Lang, string>;

export const match: ParamMatcher = (param) => {
  return Object.values(BLOG_SEGMENT).indexOf(param) > -1;
};
```
As it stands, we have no way to make it so the latter also matches by taking into consideration the `lang` param to exclude mixed languages like `/en/blogue`.

### Describe the proposed solution

Somehow pass parent params or the complete route url to `ParamsMatcher` functions.

### Alternatives considered

Reorganize my routing structure or manually repeat parallel route trees for every language (quite error-prone).

### Importance

nice to have

**Comment by iolyd** [comment]
The given use-case is highly related to https://github.com/sveltejs/kit/issues/1274 and https://github.com/sveltejs/kit/issues/553 but could also be relevant in non-i18n situations.

**Comment by Conduitry** [comment]
This sounds like a duplicate of #4500.

**Comment by iolyd** [comment]
> This sounds like a duplicate of #4500.

Ah! My bad, it definitely is.
