### ISSUE TITLE
precompress option not working since 1.20.3

### ISSUE THREAD

**Issue by wickning1** [sveltejs/kit#10184]
### Describe the bug

After npm upgrade took me from sveltekit 1.20.2 to 1.20.4, I noticed that the output of svelte-package no longer included .gz and .br files. Reverting to 1.20.2 solves the problem. Since 1.20.3 and 1.20.4 were related to tiny-glob, and builder uses `glob` to locate files for precompression, I'm sure the two are related.

### Reproduction

I believe any build with `precompress: true` is going to fail, but here is my repo: https://github.com/txstate-etc/dosgato-admin. 
- git clone
- Change package.json to un-pin the sveltekit version 
- `npm upgrade`
- `npm run build`
- inspect the `build` directory
- observe that there are no .br or .gz files.

### Logs

```Shell
The broken and non-broken build logs are identical. Neither mentions doing any compression.
```

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 192.86 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /opt/homebrew/bin/node
    npm: 9.6.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.4
```

### Severity

blocking an upgrade

**Comment by ghostdevv** [comment]
Tiny glob pr: #10166

**Comment by polyzen** [comment]
Here I was pleasantly surprised the built output was about half the size.
