### ISSUE TITLE
Node Adapter Returns a "Invalid request body" Error that can be Misleading and Hard to Debug

### ISSUE THREAD

**Issue by cedricvanrompay** [sveltejs/kit#10190]
### Describe the bug

SvelteKit has the following `catch` block at the very beginning of request handling:

```js
	} catch (err) {
		res.statusCode = err.status || 400;
		res.end('Invalid request body');
		return;
	}
```

One example of such a block is in the Node adapter: https://github.com/sveltejs/kit/blob/d4043863e5aa6b5fb003ebafef2a6e9098255b45/packages/adapter-node/src/handler.js#L88-L92

This code assumes that an error at this point necessarily comes from an invalid request body, which is wrong. For instance, as one can see in the minimal reproducible example, when using the NodeJS adapter a malformed `ORIGIN` environment variable will cause errors that will be caught by this block.

More info in the minimal reproducible example (see below).

This results in errors that are misleading because the error message is _"Invalid request body"_ when there is nothing wrong with the request body.

A second problem is that there is no mechanism to instrument errors at this level: a `handleError` function in `src/hooks.server.ts` will _not_ be triggered if an error happens there. This makes such errors even harder to debug.

### Reproduction

Minimal reproducible example is provided in https://github.com/cedricvanrompay/sveltekit-invalid-body. In a nutshell:

* `npm create svelte@latest`
* use NodeJS adapter
* `npm run build`
* `ORIGIN=localhost node run build` (note the invalid origin)
* go to http://localhost:3000

### Logs

```Shell
None, that's part of the problem.
```

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 7.32 GB / 15.49 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 114.0.5735.106
    Firefox: 113.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.5.0 => 1.20.4
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

### Severity

annoyance

### Additional Information

**I am happy to provide a Pull Request** when the maintainers agree on a solution.

Solutions I would suggest (most of them should be independent of the others):
* make the error message less precise: typically, a `HTTP 500` with a default "Internal server error" message
* only put "Invalid request body" in the HTTP response in the case we have stronger reasons to suspect an invalid body
* check the validity of the `ORIGIN` environment variable at program startup, typically soon after [we read it from the environment](https://github.com/sveltejs/kit/blob/d4043863e5aa6b5fb003ebafef2a6e9098255b45/packages/adapter-node/src/handler.js#L16)
* add a new error handler hook for errors that may not be caught by the `handleError` hook in `hooks.server.ts` (`handleDeepError`?)

**Comment by NormandoHall** [comment]
Even worse. It shows the **same error** when the size of an uploaded file exceeds `BODY_SIZE_LIMIT` environment variable of node adapter. This causes a lot of confusion.

**Comment by aMediocreDad** [comment]
Ran into this one. It required a few hours and several engineers.

**Comment by Dan1ve** [comment]
Just run into this, and it took me a while to figure this out despite having seen this issue.

Fix was to use the full url  `https://examle.com` instead of `example.com`  as `ORIGIN` env variable.

Would be great if there was some kind of warning for this.

**Comment by cedricvanrompay** [comment]
I just saw this update from changes in SvelteKit 2:

> Improved error handling
>
> Errors are handled inconsistently in SvelteKit 1. Some errors trigger the handleError hook but there is no good way to discern their status (for example, the only way to tell a 404 from a 500 is by seeing if event.route.id is null), while others (such as 405 errors for POST requests to pages without actions) don't trigger handleError at all, but should. In the latter case, the resulting $page.error will deviate from the [App.](https://kit.svelte.dev/docs/types#app-error)
[Error](https://kit.svelte.dev/docs/types#app-error)
type, if it is specified.
>
> SvelteKit 2 cleans this up by calling handleError hooks with two new properties: status and message. For errors thrown from your code (or library code called by your code) the status will be 500 and the message will be Internal 
[Error](https://kit.svelte.dev/docs/types#app-error)
. While error.message may contain sensitive information that should not be exposed to users, message is safe.
>
> source: https://kit.svelte.dev/docs/migrating-to-sveltekit-2#improved-error-handling

Maybe these changes fixed the problem this issue is about? We should have a look.

**Comment by NormandoHall** [comment]
> Maybe these changes fixed the problem this issue is about? We should have a look.

Yes, seems it is fixed now:

```
SvelteKitError: Content-length of 12634230 exceeds limit of 524288 bytes.
    at Object.start (file:///opt/minerva/devel/build/handler.js:975:19)
    at setupReadableStreamDefaultController (node:internal/webstreams/readablestream:2342:23)
    at setupReadableStreamDefaultControllerFromSource (node:internal/webstreams/readablestream:2375:3)
    at new ReadableStream (node:internal/webstreams/readablestream:286:7)
    at get_raw_body (file:///opt/minerva/devel/build/handler.js:972:9)
    at getRequest (file:///opt/minerva/devel/build/handler.js:1044:9)
    at Array.ssr (file:///opt/minerva/devel/build/handler.js:1194:24)
    at handle (file:///opt/minerva/devel/build/handler.js:1259:23)
    at file:///opt/minerva/devel/build/handler.js:1259:40
    at Array.<anonymous> (file:///opt/minerva/devel/build/handler.js:1187:4)
    at handle (file:///opt/minerva/devel/build/handler.js:1259:23)
    at file:///opt/minerva/devel/build/handler.js:1259:40
    at Array.<anonymous> (file:///opt/minerva/devel/build/handler.js:681:28)
    at handle (file:///opt/minerva/devel/build/handler.js:1259:23)
    at file:///opt/minerva/devel/build/handler.js:1265:10
    at Layer.handle [as handle_request] (/opt/minerva/devel/node_modules/express/lib/router/layer.js:95:5) {
  status: 413,
  text: 'Payload Too Large'
}
```
