### ISSUE TITLE
Add possibility to define server only data

### ISSUE THREAD

**Issue by enyo** [sveltejs/kit#10191]
### Describe the problem

Some data loaded by a `+layout.server.ts` load function, is not meant to reach the client, but should only live on the server.

```js
// +layout.server.js
export const load = ({ params }) => {
  const game = loadGame(params) // A class that holds server side game logic
  return { game }
}

// +page.server.js
export const load = async ({ parent }) => {
  const game = await parent()

  return { state: game.state }
```

Unfortunately that doesn’t work, because SvelteKit tries to serialize `game` which it can’t since it’s a class (or contains other sensitive information).

### Describe the proposed solution

Allow for some data to only be passed down to server load functions.

For example:

```js
// +layout.server.js
export const load = ({ params }) => {
  const game = loadGame(params)
  return { server: game } // Here `server` would be a “magic” field that makes sure it will not be serialized for the client
}
```

Since this would be a breaking change, maybe there are better options. I think however that the layout should be able to specify this, otherwise each `+page.server.js` load function would need to include some code to prevent serialization.

### Alternatives considered

The only alternative I found is to use `locals`. But the issue with locals is that in order to type them, you would need to type it for the whole app. So unrelated routes would have the `locals` polluted with an optional field that doesn’t concern them, while the subroutes of `/game` would need to do an `undefined` check every time before accessing it.

### Importance

nice to have

**Comment by ghostdevv** [comment]
As you mentioned `locals` is the best here - perhaps in the future locals could be dynamically typed, though not sure how we could achieve that to be honest

**Comment by enyo** [comment]
Yes I was thinking the same thing. `locals` is the place to put it. I created a separate issue #10194
