### ISSUE TITLE
[adapter-auto/adapter-node] POST request is denied in development

### ISSUE THREAD

**Issue by mateuszlewko** [sveltejs/kit#10193]
### Describe the bug

I'm running Svelte skeleton app (Sverdle) in development (`yarn dev`) exposed to internet (behind Cloudflare). On executing form POST request I'm getting the 403 error. I've tried setting env variables to my website's host address (https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocol-header-and-host-header), but that didn't help. Setting `kit.csrf.checkorigin: false` in svelte config resolves the problem, but I hope there is a better solution. 

Additionally, `request.url` printed from a server endpoint outputs `http://<host>` while the app is exposed on https.

### Reproduction

1. Create SvelteKit demo project using `npm create`.
2. Set vite host to `host: '0.0.0.0'` in vite.config.
3. Run `yarn install`, `yarn dev`.
4. Add a DNS rule, expose the app to Internet.
5. Visit publicly exposed URL. Go to Sverdle game, type some letters and press enter to invoke form POST request.

### System Info

```Shell
system:    OS: Linux 4.4 Debian GNU/Linux 12 (bookworm) 12 (bookworm)    CPU: (4) arm64 Neoverse-N1    Memory: 6.35 GB / 7.56 GB    Shell: 5.2.15 - /bin/bash  Binaries:    Node: 20.3.0 - /usr/local/bin/node    Yarn: 1.22.19 - /usr/local/bin/yarn    npm: 9.6.7 - /usr/local/bin/npm  npmPackages:    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0     @sveltejs/adapter-node: ^1.2.4 => 1.2.4     @sveltejs/kit: ^1.20.4 => 1.20.4     svelte: ^3.54.0 => 3.59.1     vite: ^4.3.0 => 4.3.9
```

### Severity

annoyance

### Additional Information

Form POST requests work fine in production (yarn build, node .)

**Comment by mateuszlewko** [comment]
I checked that ORIGIN header is `https:` on the server side, so the real question is why is Svelte reporting that request.origin is http:// and how to change that?

**Comment by Conduitry** [comment]
Duplicate of #8026.
