### ISSUE TITLE
Problem with hierarchy of +layout.svelte

### ISSUE THREAD

**Issue by maikerleon** [sveltejs/kit#10208]
### Describe the bug

At the moment of creating the project, and inside src in the root "/" I create a +layout.svelte and then I create a folder called "/panel" and inside there, I create another +layout.svelte and a +page@panel .svelte to create an advanced layout, then it doesn't work for me. I tried the same thing creating groups() and it didn't work for me either. I'm using the latest version of Sveltekit, and I'm just installing the project and using the advanced layouts at once. The main problem is that instead of showing me only the layout of "/panel" it shows me the two layouts

src/routes/
│
├ panel/
│ ├ +page@panel.svelte
│ └ +layout.svelte
└ +layout.svelte

If I use for example the following format if it works

src/routes/
│
├ panel/
│ ├ +page@.svelte
│ └ +layout.svelte
└ +layout.svelte

And it only shows me the main layout

### Reproduction

https://github.com/maikerleon/sveltekit/

### System Info

```Shell
"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"lint": "prettier --plugin-search-dir . --check .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.5.0",
		"autoprefixer": "^10.4.14",
		"daisyui": "^3.1.5",
		"postcss": "^8.4.24",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"svelte": "^3.54.0",
		"tailwindcss": "^3.3.2",
		"vite": "^4.3.0"
	},
	"type": "module",
	"dependencies": {
		"svelte-preprocess": "^5.0.4"
	}
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
You can only go upwards the layout chain, but you cannot skip or reset your layout. So you can't say "I only want the panel layout and skip the root layout". Furthermore, the root layout cannot be skipped because a stable/predefined layout is needed in case of errors etc.

What you can do is to use groups to achieve what you want:

```
src/routes/
├ (main)
│ ├ +layout.svelte
│ └ (everything that should extend the main layout goes here)
├ panel/
│ ├ +layout.svelte // does not extend the layout in (main)
│ └ +page.svelte
```
