### ISSUE TITLE
sveltekit:keepfocus

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#1022]
**Is your feature request related to a problem? Please describe.**

1. Refresh page
2. Press `Tab key` on the keyboard
3. The button are focused
4. Press `Right Arrow` on the keyboard
5. The button loses focus

GIF with this:
![lost-focus](https://user-images.githubusercontent.com/16800535/114312453-0534aa00-9af3-11eb-8127-fa5c146092fb.gif)

**Describe the solution you'd like**
Maybe similar to `sveltekit:noscroll` and `goto(href, { replaceState, noscroll })` , e.g. `sveltekit:keepfocus` and `goto(href, { replaceState, keepfocus })`?

It looks like something easy to do. [L245 of `router.js`](https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L245)  would have to give in a similar condition as  [L254 of `router.js`](https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L254).

**Describe alternatives you've considered**
Described by @ahtcx in https://github.com/sveltejs/kit/issues/968#issuecomment-817378602
> as a workaround I've been using [`patch-package`](https://www.npmjs.com/package/patch-package) on [L245 of `router.js`](https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L245) but this isn't ideal and I imagine `router.js` will change a lot so you'll have to update it at every change.

**How important is this feature to you?**
Using the keyboard and keeping the application focused is a matter of accessibility in general.

**Comment by c-bandy** [comment]
What's the normal browser behavior when navigating between pages without a router? Does it preserve the tab state?

**Comment by Conduitry** [comment]
If it's a regular old full-page load, then no. Preserving the tab state doesn't make sense, because it's generally a completely unrelated document.

**Comment by c-bandy** [comment]
OK. Given that, I'm not too sure how I feel about adding a helper like this into Kit. My gut feeling says this type of thing would better be solved using client JavaScript.

**Comment by lukaszpolowczyk** [comment]
@c-bandy Rather it's worth comparing to pure svelte behavior, with no routers.
Therefore, `sveltekit:keepfocus` is optional, as is `sveltekit:noscroll`.

I hope you're not looking for an excuse to reject the proposal?

**Comment by lukaszpolowczyk** [comment]
@c-bandy BTW - text selection is kept when switching between svelte routers. I don't know if this shouldn't be cleared by the router by default either?

**Comment by c-bandy** [comment]
I'm not opposed to your proposal but I don't see why something like this should be included as a helper. What is your use case here?

**Comment by lukaszpolowczyk** [comment]
@c-bandy It is directly related to the situation where using only the keyboard (`Tab key`), I slide to the button and press `Enter key`, then the page goes to the next subpage and I want to press `Enter key` again to continue. I can't because the focus is disappearing. I have to press Tab key again to get to the button and then press `Enter key`. Over and over again...

If you add to the `keepfocus` button, the focus does not disappear and you just need to press the` Enter key`.

**Comment by c-bandy** [comment]
Sorry for all the questions, I just want to understand if there's a better way to do this. What would this navigation system represent in the real world? Jumping between pages of some content?

**Comment by lukaszpolowczyk** [comment]
@c-bandy Consecutive pages of the same type of content, e.g. image jumping in an image gallery.

**Comment by c-bandy** [comment]
May I suggest you should not use the router for this? Pages work best when used for isolated content, where you'd want the tab focus to reset on each page load.

I think a better fit for your case is to utilize JavaScript to handle this state. If you want to preserve the state across page loads you can encode query params into the URL that resolve on page load.

**Comment by lukaszpolowczyk** [comment]
@c-bandy Actually, for view mode, this is what you can do (I didn't really think about it a bit when I wrote it).

But for the jumps in the following pages I don't know. You mean something like this:
I want this: `gallery.com/image/name1.jpg`
vs
You propose it: `gallery.com/?image=name1.jpg`
?

**Comment by c-bandy** [comment]
Well, how you implement it is up to you. I just propose from a philosophical standpoint that the HTML way is to not modify the URL for partial content, especially if you want to preserve the tab state. It feels anti-pattern-ish. 

For your specific example my 2¢ is that `gallery.com/image/name1.jpg` should point at a file and not a page to view the file on.

**Comment by lukaszpolowczyk** [comment]
I guess I'll do as you say.
I will give it as a parameter.

What about `keepfocus`?
Because it probably has the same meaning as the `noscroll`?

Although, as I will do in your case, as you wrote, I will not need `keepfocus`.

**Comment by c-bandy** [comment]
Personally I haven't found a need for `noscroll` either so I can't speak for it

**Comment by ahtcx** [comment]
My use case for this would be within the `goto` function. I have a search page `/search/[searchQuery]` which I would like to update on user input. (for an example, see Spotify's web client)

The issue is that on input change, focus is lost from the text input. There are possible workarounds but they're a pain and not very clean.

I think that it's a nice option to have, as it allows more flexibility with the router.

**Comment by c-bandy** [comment]
@ahtcx, What do you think of the solution discussed above? I think query parameters are a better fit for what you are trying to do. This pattern is very common for search results

**Comment by ahtcx** [comment]
I agree that query parameters are the more standard (and suitable) approach to this kind of pattern, but I'm saying that it's nice to have options as sometimes we have to follow a specific spec.

**Comment by babeard** [comment]
@c-bandy I don't think query parameters will help when you have a `<input type="color" />` dialog open and you want to listen for  `on:change` , [which is supposed to be triggered on dialog close](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color#tracking_color_changes) but it also weirdly triggers on route change and first `on:input` event even though the dialog box is still open. 

I discovered this just yesterday in Sapper and hadn't checked yet for Kit but it looks to be the same problem. I could be wrong though.

My use case for this is I want to be able to navigate to `/color/[hex]` route `on:input` and only close the search menu I have open when `on:change` happens (color dialog box closes).

_Hope this makes sense_

**Comment by MatthiasGrandl** [comment]
I have the same issue. I am implementing a search with query parameters and it's supposed to fetch filtered content live from the load function. So `goto` definitely makes sense here in my opinion...
