### ISSUE TITLE
SvelteKit (but not Svelte) creates css classes with no css props

### ISSUE THREAD

**Issue by jacobbogers** [sveltejs/kit#10238]
### Describe the bug

I illistrate this issue with an extremely simple sveltekit page and component isolating the problem

```html
<div class="me">
	<span>Hello world</span>
</div>
```

Svetlekit turns above into 

```html
<div class="me s-y_bCXRrkrYfP">
   <span class="s-y_bCXRrkrYfP" data-svelte-h="svelte-1ni7zwe">Hello world</span>
</div>

Svelte turns above into a span with no class attribute whatsoever (expected behavior)

```html
<div class="me svelte-2pluby">
   <span>Hello world</span>
</div>
```

Thank you for looking into this issue

### Reproduction

- Example in Sveltelabs: https://www.sveltelab.dev/4dvub3fe2i24fa5
- Example in REPL Svelte: https://svelte.dev/repl/5be2f3feafc04cd6bcf6af56cf5159c2?version=4.0.0

### Logs

```Shell
Not applicable, the issue is replicated in sveltlabs and svelte.dev REPL (see links)
```

### System Info

```Shell
Browser: Chrome

Version used in online REPL and SvelteLabs
```

### Severity

annoyance

### Additional Information

this will bloat my bundles if every tag in svelte kit ends up having undeeded class name attributes

**Comment by Conduitry** [comment]
Classes with names like `s-y_bCXRrkrYfP` exist only in development mode. The production build of your app will only have the classes like `svelte-2pluby` and they will only exist on the elements that need them.
