### ISSUE TITLE
$navigating store not updated when form submitted

### ISSUE THREAD

**Issue by liegeandlief** [sveltejs/kit#10237]
### Describe the bug

When submitting a form I would expect the `$navigating` store to be updated whilst the action is running.

The docs at https://kit.svelte.dev/docs/types#public-types-navigation say that `$navigating.type` can have the value `form` when a user has submitted a form.

But this never seems to be the case and `$navigating` remains as `null` whilst the action is running.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-kcmju7?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 602.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 3.3.0 - ~/.volta/tools/image/yarn/3.3.0/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/npm/9.5.1/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.5
  npmPackages:
    @sveltejs/adapter-vercel: ^3.0.0 => 3.0.1
    @sveltejs/kit: ^1.0.0 => 1.20.5
    svelte: ^3.44.0 => 4.0.0
    vite: ^4.0.0 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by geoffrich** [comment]
This is a docs issue - the `form` navigation type only applies when a `<form method="GET">` is submitted, e.g. https://kit.svelte.dev/docs/form-actions#get-vs-post. Regular `<form method="POST">` submissions do not trigger a navigation so the `$navigating` store won't be updated.

I've opened a PR to correct the docs.

You can track whether a form is submitting by customizing `use:enhance`

```html
<script>
	let submitting = false;
</script>

<form use:enhance={() => {
	submitting = true;

	return async ({update}) => {
		await update();
		submitting = false;
	}
}}></form>
