### ISSUE TITLE
Error: Not found: /src/main.ts

### ISSUE THREAD

**Issue by mwkldeveloper** [sveltejs/kit#10231]
### Describe the bug

The latest  `npm create svelte@latest` run fail.
Error: Not found: /src/main.ts

### Reproduction

npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 5.89 GB / 15.59 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.20.4
    svelte: ^4.0.0 => 4.0.0
    vite: ^4.3.6 => 4.3.9
```

### Severity

annoyance

**Comment by Basarus** [comment]
And where do you refer to main.ts? With a simple installation, it's not there, have you tried installing it from scratch into a new folder?

**Comment by mwkldeveloper** [comment]
I just follow below :
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open

both Skeleton project or demo project have the problem

**Comment by mwkldeveloper** [comment]
I found the problem. This is my problem. Some browser cache previous project.  No problem now.
