### ISSUE TITLE
Svelte updates the tab's title only if <title> is a direct child of <svelte:head>

### ISSUE THREAD

**Issue by ThomasGysemans** [sveltejs/kit#10247]
### Describe the bug

When you navigate a website, the tab's title should be replaced by the title of the new page. It is simple :

```html
<svelte:head>
  <title>Some page</title>
</svelte:head>

<h1>Some page</h1>
```

This works fine, if I navigate to other pages, the tab's title will be updated accordingly. However... let's put `<title>` in a component called `Head.svelte` : 

```html
<!-- components/Head.svelte -->
<script lang="ts">
  export let title: string;
</script>

<title>{title}</title>
```

And then use this component inside of `<svelte:head>` on all pages : 

```html
<!-- import component Head... -->

<svelte:head>
  <Head title="Some page" />
</svelte:head>

<!-- content of the page here... -->
```

This time, when you navigate the pages of the website, the tab's title doesn't get updated. It sticks with the first one. Reload the page to see the right title.

### Reproduction

Here a repo that reproduces the issue : https://github.com/ThomasGysemans/sveltekit-title-issue

The issue is very simple to describe. It took me 5 minutes to make this repo. Clone it and run `npm run dev`. You'll see that when you navigate through the site, the tab's title remains "Main Page". However, replace the `Head.svelte` component on all pages by `<title>` and try again. You'll see that the tab's title gets updated accordingly (which is the right behaviour).

### System Info

```Shell
System:
  OS: macOS 12.6
  CPU: (8) arm64 Apple M1
  Memory: 80.13 MB / 8.00 GB
  Shell: Unknown
Binaries:
  Node: 16.15.0 - /usr/local/bin/node
  npm: 8.5.5 - /usr/local/bin/npm
Browsers:
  Brave Browser: 113.1.51.110
  Chrome: 114.0.5735.133
  Safari: 16.0
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
  @sveltejs/kit: ^1.20.4 => 1.20.5 
  svelte: ^4.0.0 => 4.0.0 
  vite: ^4.3.6 => 4.3.9
```

### Severity

annoyance

### Additional Information

The simple work around is to just put `<title>` as a direct child of `<svelte:head>` but it is a little annoying and not really intuitive.

**Comment by Conduitry** [comment]
I don't think I'd consider this a bug. The `<title>` element is supposed to go in the `<head>` in regular HTML, so it's definitely intuitive that it needs to go in `<svelte:head>`. I'm not sure what browsers do if you try to put the `<title>` in the `<body>` - probably it tries to be helpful and move it to the `<head>` - but you shouldn't be trying to write apps that require that.

**Comment by ThomasGysemans** [comment]
> I don't think I'd consider this a bug. The `<title>` element is supposed to go in the `<head>` in regular HTML, so it's definitely intuitive that it needs to go in `<svelte:head>`

Even though `<title>` is in a component, the component itself is used in `<svelte:head>`. Why would there be a difference?
