### ISSUE TITLE
Unable to start a local server 

### ISSUE THREAD

**Issue by SolidFolio** [sveltejs/kit#10255]
### Describe the bug

So yesterday everything was working fine but today when i tried to start a sever by " npm run dev " i am getting these errors

![Screenshot 2023-06-26 161507](https://github.com/sveltejs/kit/assets/136412478/99aec6f2-627b-4a9a-b75f-15458d61ad57)

i also created a new svelte kit project same error showing. but if create a vue.js project the server does run and work just fine

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-8zp2zt?file=README.md&terminal=dev

existing or new project i does not work 

### System Info

```Shell
System:
    OS: Windows 11
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
    Memory: 10.91 GB / 15.89 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1778.0)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.5.0 => 1.20.4
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

### Severity

annoyance

### Additional Information

i really need to see what goin on with my code of course

**Comment by AntonPavlenkov** [comment]
https://github.com/sveltejs/kit/issues/10252

**Comment by Conduitry** [comment]
This suddenly started happening for someone else recently - #10252 - it's very peculiar. Their solution ended up being to upgrade Node. I really don't know what's happening here.

**Comment by SolidFolio** [comment]
Thank fixed by upgrading the node version
