### ISSUE TITLE
#fetch in await block: server prerendering

### ISSUE THREAD

**Issue by M5rian** [sveltejs/kit#10257]
### Describe the problem

Components with an await block, which include a fetch call currently print out a warning:
```
Avoid calling `fetch` eagerly during server side rendering — put your `fetch` calls inside `onMount` or a `load` function instead
```

This error actually confuses me a bit, because why does the await block run on the server at all?
Rendering anything of the await block on the server makes no sense, since its made for loading data while the web page is already loaded. Awaiting it on the server is basically awaiting the entire web page. I don't know the detailed implementation of it but the warning really confuses me.

I want to get rid of the warning, so I wrapped my code around an if statement to only run in the browser:
```
{#if browser}
	{#await doAsyncStuff()}
		<p>loading</p>
	{:then stuff}
		<p>received stuff</p>
	{/await}
{/if}
```
The issue with that code is that I get a small flickering when i (re)load the page. The component renders a few milliseconds after page load. It seems like that the javascript doesn't run immediately. This kinda destroys the aesthetics. 

### Describe the proposed solution

As mentioned, I don't know the implementation of the await feature but from the warning it seems like that the await block tries to get executed on server side?
It would be nice if it could pre-render the loading state of the await block on server side, so that when the javascript loads, no flickering exists. Instead there is an invisible transition from the pre-rendered await block and the one which takes over with javascript. With this the warning should disappear as well of course.

### Alternatives considered

There is a workaround for this, which is basically doing the pre-render manually like so:
```
{#if browser}
	{#await doAsyncStuff()}
		<p>loading</p>
	{:then stuff}
		<p>received stuff</p>
	{/await}
{:else}
	<p>loading</p>
{/if}
```
This gets pretty messy if the loading state is more complex than a simple text.

### Importance

would make my life easier

### Additional Information

As mentioned, I have no clue how its exactly implemented and if my assumptions are right. I hope that my problem still gets clear.
Thanks in advance!

**Comment by dummdidumm** [comment]
The await block is executed on the server side, yes. Svelte can't really swoop inbetween and swap it out with something else. Also if people call the function in the script tag and only reference the promise in the template, they would still run into this (and I think that's actually the more common case).

As the warning suggests, you can put your fetch call inside `onMount` and only execute it there. The pending state will be rendered. Another alternative would be to do `browser ? actualFetch() : Promise.resolve()` so that you don't call the fetch on the server.

Closing as this works as designed and workarounds exist. Hope this cleared things up 👍

**Comment by minmoong** [comment]
Hello, Just do this!

```js
{#if browser}
	{#await doAsyncStuff() then stuff}
		<p>received stuff</p>
	{/await}
{:else}
	<p>loading</p>
{/if}
```

**Comment by saadeghi** [comment]
This warning must mention the file path and the line number. How can we track the problem if the file is not addressed?
