### ISSUE TITLE
Minimize imported json files in output when using adapter-static

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#10262]
### Describe the problem

I have this json file in my lib folder which is 4mb in size.

When I build sveltekit, it turns that json file into a pretty formatted .js file inside `output/server/chunks`.

Due to the pretty formatting, it now is rougly 10mb in filesize.

### Describe the proposed solution

The option to minimize imported json files, or not pretty format the imported json files during build.

### Alternatives considered

-

### Importance

nice to have

**Comment by gtm-nayan** [comment]
The JSON transformation is done by vite, so please file an issue there. If it's not minified then their default plugins are likely out of order.
