### ISSUE TITLE
Missing "vite-manifest.json" file on build

### ISSUE THREAD

**Issue by stephenlrandall** [sveltejs/kit#10268]
### Describe the bug

Building a SvelteKit application on one of my GitLab runners breaks with:

`[vite-plugin-svelte-compile] ENOENT: no such file or directory, open '.../.svelte-kit/output/client/vite-manifest.json'`

On my local machine, the build is fine. I was curious about the `vite-manifest.json` file, and it looks like it's actually generated:

```
✓ 1268 modules transformed.
.svelte-kit/output/client/_app/version.json                           0.03 kB │ gzip:   0.05 kB
.svelte-kit/output/client/vite-manifest.json                         38.84 kB │ gzip:   2.79 kB
...
```

But if I go inspect that folder after the build is complete, that file isn't present. Does it get deleted at some point? Is there any chance of a race condition happening?

The exact line that spawns the error is:

https://github.com/sveltejs/kit/blob/e8d8587120cf3d27ff029f1f2113f8c3c1217b5b/packages/kit/src/exports/vite/index.js#L717

### Reproduction

I don't know how to reproduce this, it's only happening on a system I don't control.

### System Info

```Shell
System doesn't have external internet access, but it's using:

@sveltejs/adapter-static: 2.0.2
@sveltejs/kit: 1.15.7
svelte: 3.58.0
vite: 4.3.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Apologies for the lack of a good reproduction, more so just trying to understand where to continue debugging the issue.

**Comment by gtm-nayan** [comment]
Is the ... an absolute path replaced or was it actually there in the message?

**Comment by stephenlrandall** [comment]
> Is the ... an absolute path replaced or was it actually there in the message?

An absolute path replaced for privacy, apologies if that was confusing.

**Comment by gtm-nayan** [comment]
Check if the issue occurs in a new blank project deployed on GitLab.

**Comment by stephenlrandall** [comment]
> Check if the issue occurs in a new blank project deployed on GitLab.

Sorry for the long delay -- yes, the problem also occurs with the default starter SvelteKit app.

Again the Vite build log is saying that a `vite-manifest.json` file is being created, but it's not being found. Locally, where the build does work, I'm also not seeing a `vite-manifest.json` file in my build output. Do you know what's going on with that file?

**Comment by gtm-nayan** [comment]
> I'm also not seeing a vite-manifest.json file in my build output. Do you know what's going on with that file?

It's removed after the build is done so that's expected at least but I don't see why it'd behave differently on GitLab.

https://github.com/sveltejs/kit/blob/a7bffde62c3058db11c69f4c4250dda99674a1dc/packages/kit/src/exports/vite/index.js#L797

The plugin name from the error, `vite-plugin-svelte-compile` is odd, the name's not used in either SvelteKit or vite-plugin-svelte, are you using any others?

**Comment by stephenlrandall** [comment]
> The plugin name from the error, vite-plugin-svelte-compile is odd, the name's not used in either SvelteKit or vite-plugin-svelte, are you using any others?

Isn't this it?

https://github.com/sveltejs/kit/blob/a7bffde62c3058db11c69f4c4250dda99674a1dc/packages/kit/src/exports/vite/index.js#L477-L479

It's the same error on the skeleton project, with nothing extra added.

**Comment by stephenlrandall** [comment]
@gtm-nayan Is there any more information I can give to help with this? It looks like the “awaiting submitter” tag is still applied.

**Comment by gtm-nayan** [comment]
Ah sorry, I forgot to send the comment I had typed out.

The plugin name is missing `kit` in the error message in your original post, was that missed out when pasting or does the actual error report the plugin as `vite-plugin-svelte-compile`? There shouldn't be a race condition since the function that deletes the files is only called after everything has completed.

**Comment by gtm-nayan** [comment]
The double built in lines are for the two vite client and server builds I think which should be fine. Although the logs seem out of order, I'm confused why the adapter log would show up above the others when it should be at the end.

Could you please share the blank project that reproduced the issue on gitlab with the CI scripts configured?

**Comment by stephenlrandall** [comment]
Somewhat unsurprisingly, if I comment out the following lines:

https://github.com/sveltejs/kit/blob/a7bffde62c3058db11c69f4c4250dda99674a1dc/packages/kit/src/exports/vite/index.js#L796-L798

the build goes through just fine.

**Comment by fbele** [comment]
I have the same issue here. It's happening with Ionic Extension for VS Code when you want to run application in Android Emulator in combination with Capacitor.  And it happens **only** there and only if the application was already built once using the extension, the first run works just fine for me. If I just close VS Code and run the application is going to be built just fine. Also if I run application via `npx cap run android` it runs just fine.

**Comment by stephenlrandall** [comment]
That’s interesting, but my use case is entirely different since I’m seeing the issue in a GitLab runner, not within the VS Code terminal.

@gtm-nayan Do you have any idea why the server build might run twice under any circumstances?

**Comment by Miolus** [comment]
Same issue here on VSCode with internet access and node adapter.

**Comment by stephenlrandall** [comment]
> Same issue here on VSCode with internet access and node adapter.

If you rewind the kit/Vite packages a few versions, how far back do you have to go before the deployment works?

**Comment by kiddailey** [comment]
Just adding my comment as I have this issue as well.  (Windows 11, Svelte 3.59.2, Kit 1.22.3, Adapter-Static 2.0.3, Vite 4.4.7, currently using Node 16.18.1)

I have a very simple, default setup to build a non-SPA static site.  The build process does successfully complete and then the error pops up just as described in the original issue above.  For what it's worth, I don't see the issue when running the site with "vite dev"

I'm not sure, but I don't remember this being an issue when I first setup Svelte for my project, originally with Svelte 3.54.0, Kit 1.0.13, Adapter-Static 1.0.1 and Vite 4.0.0.  It only seems to have popped-up when I updated to 3.59.2 and Vite 4.4.7.  There are a few versions in between that I skipped, but perhaps that is some help?

If I can find some time, I'll downgrade back to the old versions of everything, see if the issue goes away and let you all know.

**Comment by kiddailey** [comment]
Okay, summary of results from testing:

* The issue appears to have been introduced with SvelteKit v1.4.0
* The issue does NOT occur with SvelteKit v1.3.0 regardless of Svelte or Vite versions.

If you want to test it out yourself, here's a snippet from package.json for an environment that works correctly (no error):

```
"@sveltejs/adapter-auto": "^2.1.0",
"@sveltejs/adapter-static": "^1.0.6",
"@sveltejs/kit": "^1.3.0",
"svelte": "^3.59.2",
"svelte-preprocess": "^5.0.4",
"vite": "^4.4.7"
```

And one that does NOT work, outputting the error originally reported:

```
"@sveltejs/adapter-auto": "^2.1.0",
"@sveltejs/adapter-static": "^1.0.6",
"@sveltejs/kit": "^1.4.0",
"svelte": "^3.59.2",
"svelte-preprocess": "^5.0.4",
"vite": "^4.4.7"
```

You'll see that the only difference is SvelteKit.  Note that adapter-static is capped at v1.0.6 for SvelteKit v1.3.0.  Hope this helps solve the mystery.

**Comment by emaktech** [comment]
Thanks @kiddailey 

Can confirm when running `npm install @sveltejs/kit@1.3.0` and then trying `npm run build` again it works fine!

**Comment by kiddailey** [comment]
> Thanks @kiddailey
> 
> Can confirm when running `npm install @sveltejs/kit@1.3.0` and then trying `npm run build` again it works fine!

Yes, everything works fine with `@sveltejs/kit@1.3.0` and running `npm run build` works fine.  No output errors reported.

In my tests with v1.3.1 and later, you still get the build, but the error is reported and would obviously break any automation checking for errors.

**Comment by stephenlrandall** [comment]
Same for me, locking kit at 1.3.0 and adapter-static at 1.0.6 fixes the issue.

@Rich-Harris Sorry for the ping, but as the author of #8636 do you have any ideas about why it might be causing the server build to run twice under certain circumstances?

**Comment by stephenlrandall** [comment]
@benmccann Since you reviewed #8636, do you have any ideas about why it might cause the server build to run twice? I'm seeing the issue on (one of) my GitLab runners, and it seems like other people are experiencing the same problem. The issue can be worked around by locking to SvelteKit 1.3.0 and adapter-static 1.0.6, but this is obviously non-ideal.

**Comment by opack** [comment]
I do have the same issue when trying to run the Playwright tests in VSCode. It fails with this error when executing from the "Playwright Test for VSCode" extension, but works like a charm when running `npm run test:integration` in the terminal.
