### ISSUE TITLE
Docs page for writing adapters refers to old polyfill package name

### ISSUE THREAD

**Issue by erxclau** [sveltejs/kit#10278]
### Describe the problem

The [page for writing adapters](https://kit.svelte.dev/docs/writing-adapters) refers to `@sveltejs/kit/install-fetch` but this package was [renamed](https://github.com/sveltejs/kit/pull/4934) to `@sveltejs/kit/node/polyfills`.

https://github.com/sveltejs/kit/blob/67c02148a9526d49a147b865c4742e8b7c48b3a8/documentation/docs/25-build-and-deploy/99-writing-adapters.md?plain=1#L40

### Describe the proposed solution

1. Change the package name to `@sveltejs/kit/node/polyfills`.
2. Update language to also say that `crypto` is shimmed as part of the package.

### Importance

nice to have

**Comment by gladimir777** [comment]
Hello, I am new to this world of contributing to open source project. And I would like give my firs contribution on solving this. Could you please asign this to me?
