### ISSUE TITLE
No Style/CSS on initial load with SvelteKit

### ISSUE THREAD

**Issue by shellking4** [sveltejs/kit#10277]
### Describe the bug

I have built a sveltekit app. And for some reason, the css won't load on initial load. I don't know how to solve this. Need your help please.

### Reproduction

Not provided

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 8.27 GB / 15.45 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Brave Browser: 114.1.52.126
    Chrome: 114.0.5735.133
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4 
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^1.5.0 => 1.18.0 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.8
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Please don't use GitHub issues for support requests, especially for ones where you don't link to any of your code. If you have a minimal reproduction of a bug where you think styles are missing that should be there, you can open an issue for that. There are other avenues - the Discord channel, StackOverflow, etc. - for support requests, but they're going to need to see some of your code as well.
