### ISSUE TITLE
`crypto.randomUUID is not a function` when vite preview is exposed over network

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#10288]
### Describe the bug

The error in the title gets thrown when:

- you use adapter-vercel
- ssr = false
- prerender = false
- build and then preview using `pnpm preview --host`
- open any link that is not `localhost`. 

### Reproduction

https://github.com/UltraCakeBakery/kit-crypto-host-bug

1. pnpm install
2. pnpm build
3. pnpm preview --host
4. open the second preview link using any browser

It should show you the same error

### Logs

```Shell
app.31df7b26.js:1  TypeError: crypto.randomUUID is not a function
    at 2.f13259e1.js:1:153
```

### System Info

```Shell
This command outputs just a linebreak...
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
> Crypto: randomUUID() method
Secure context: This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.

https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
