### ISSUE TITLE
An utility to auto-detect problems or upgrades in files and directories

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1029]
**Is your feature request related to a problem? Please describe.**
With the next versions of svelte-kit for sure some project files created with (maybe many) previous versions will change.

**Describe the solution you'd like**
How about creating an upgrade utility?

Ex: `npm init svelte@v1.0.0` on an existing project created with older versions can update or detect files and directories changed or deleted.

**Describe alternatives you've considered**
Do this manually.

**How important is this feature to you?**
Honestly, it is very important to have this handled automatically because it could prevent problems (new issues) and report discrepancies with respect to how the project files should be compared to the current version.

**Comment by Conduitry** [comment]
Once we reach 1.0.0 final, we'll respect semver, and the idea is that backwards-incompatible changes won't happen again until 2.0.0. It would be a huge burden to write code to check for these for every single breaking change during the prereleases. By using prereleases at all, people are taking responsibility for checking the changelog when upgrading and for the fact that any API could change at any time.
