### ISSUE TITLE
Docs search keybind missing compared to other docs/websites

### ISSUE THREAD

**Issue by emastho** [sveltejs/kit#10293]
### Describe the problem

Most websites have Ctrl+K search just like Svelte, but they also have / which works the same.

Websites that have it:
github, google, youtube, mdn docs, npm, dev.to, vercel, instagram, duckduckgo, react.dev, qwik, solidstart, gitlab, nuxt2 and nuxt3, nextjs, electron, bun, deno, material ui, vite, strapi cms, discourse forums and many more

### Describe the proposed solution

Add Ctrl+K behaviour (focus search bar) to / (slash) key

### Alternatives considered

Website open search bar focus is an alternative

### Importance

nice to have

### Additional Information

Raccoons are hella cute but probably hide (is unknown if didn't research) something that would make me dislike them once I found out

**Comment by ghostdevv** [comment]
cc: @PuruVJ

**Comment by eltigerchino** [comment]
This is now resolved in the new omnisite. https://svelte.dev/
