### ISSUE TITLE
adapter-node reports `https` as the protocol even when the request is `http`

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#10309]
### Describe the bug

adapter-node reports the protocol to be `https` even when it's actually `http`.

### Reproduction

Repo: https://github.com/aradalvand/sveltekit-adapter-node-https-repro

Clone, run `pnpm install`, then `pnpm run build`, and finally `node build`.

Then send a request to `http://localhost:3000/test`:

![image](https://github.com/sveltejs/kit/assets/26527405/77a3db1f-6ad8-40f3-97a8-f7d5d7e3f536)

Check the server logs (the related `console.log` is in `src/routes/test/+server.js`):

![image](https://github.com/sveltejs/kit/assets/26527405/3cf4659b-3ac5-4c7c-84b2-967d2c6e710f)

Notice it says `https`, even though the request was `http`.

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 15.30 GB / 18.67 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.3.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.5.0 => 1.20.4
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
Sounds like https://github.com/sveltejs/kit/issues/10078

**Comment by Conduitry** [comment]
It is. This is the intended behavior.
