### ISSUE TITLE
adapter-node over HTTP/2 `url.host` is `undefined`

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#10310]
### Describe the bug

May be related to #3566

Using a custom server with `adapter-node`'s `handler.js` to serve over HTTP/2 causes the reported `hostname` in URLs to be `undefined`.

### Reproduction

Repo: https://github.com/aradalvand/sveltekit-adapter-node-http2-repro

Clone, run `pnpm install`, then `pnpm run build`, and finally `node server.js` (remember to use the custom `server.js`, don't run `node build`).

Then send a request to `https://localhost:3000/test`:

![image](https://github.com/sveltejs/kit/assets/26527405/df64f6df-8d26-4709-a27c-52743fdd0013)

Check server logs (the related `console.log` is in `src/routes/test/+server.js`)::
![image](https://github.com/sveltejs/kit/assets/26527405/256fd2ac-cc1b-45d6-b2c0-cf0509670c99)

Notice that the `host`, `hostname` and so on are `undefined`; they should obviously be `localhost`.

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 17.05 GB / 18.67 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.3.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.5.0 => 1.20.4
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.9
```

### Severity

blocking an upgrade

**Comment by eltigerchino** [comment]
Closed by https://github.com/sveltejs/kit/pull/12989
