### ISSUE TITLE
Option for tailwindcss while creating project

### ISSUE THREAD

**Issue by bobbymannino** [sveltejs/kit#10325]
### Describe the problem

It would be a nice addition to have an option where there is for prettier but for tailwindcss. Making many projects and then having to go through the process is slow and annoying. Similar to having to change the @sveltejs/adapter-auto to one you like. having these options in the 'create svelte' script would be awesome

### Describe the proposed solution

As above

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
You should be able to do this today using the community package `svelte-add` running the command `npx svelte-add@latest tailwindcss`: https://github.com/svelte-add/tailwindcss

**Comment by Conduitry** [comment]
This has come up a few times before, in #9806, #3025, maybe other places. Is our position on this changing?

I'd strongly advise against adding CSS framework X to the create-svelte CLI, because we will then get people asking for CSS framework Y.

**Comment by bobbymannino** [comment]
This is true. but i mean having the convenience of it being an option when creating a svelte package. and @Conduitry you are totally right. if you think it would be unwise to ill close the issue

**Comment by ghostdevv** [comment]
Perhaps instead we can point to `svelte-add` in create svelte? That way it's easier for people who don't know/forget about svelte add to start quickly, and we don't run into people asking for X & Y

**Comment by bobbymannino** [comment]
That’s a good solution. What about having options in the create script for certain adapters. For me I always am using vercel so it would save me changing it each project?

**Comment by geoffrich** [comment]
> Perhaps instead we can point to svelte-add in create svelte? That way it's easier for people who don't know/forget about svelte add to start quickly, and we don't run into people asking for X & Y

We already do link to svelte-add after the wizard complete:

<img width="614" alt="Screenshot 2023-07-07 at 7 56 34 AM" src="https://github.com/sveltejs/kit/assets/4992896/aa322a5e-5aaf-43dd-8ecc-797e66f70dfd">

Having adapter options in the create script would be a separate request, but I don't think it's something we'd want to add -- whatever options we add to `create-svelte` is one more thing people will need to interact with/understand before setting up a new Svelte project, so we want to keep it minimal.

**Comment by bobbymannino** [comment]
i understand both points yes. shall i close this issue then?

**Comment by ghostdevv** [comment]
> We already do link to svelte-add after the wizard complete:

Oh amazing!

> I understand both points yes. shall i close this issue then?

Yea we can close this for now :pray:
