### ISSUE TITLE
Homepage hero image is noticeably blurry

### ISSUE THREAD

**Issue by thedenoff** [sveltejs/kit#10326]
### Describe the bug

In code it's imported in 1440px and 960px wide

https://github.com/sveltejs/kit/blob/a7bffde62c3058db11c69f4c4250dda99674a1dc/sites/kit.svelte.dev/src/routes/home/Hero.svelte#L4-L5

And in production HTML it resolved to 

```html
<picture>
    <source srcset="/_app/immutable/assets/svelte-kit-machine.3456a340.avif 960w" type="image/avif">
    <source srcset="/_app/immutable/assets/svelte-kit-machine.54d0c217.webp 960w" type="image/webp">
    <img src="https://kit.svelte.dev/_app/immutable/assets/svelte-kit-machine.b43eaaae.png" alt="SvelteKit illustration">
</picture>
```

Where all three pictures are 960x960

And are being drawn in a block 1080px wide which means that the smallest good resolution for retina screens here would be 2160px wide and half that for non-retina. 

Everything's perfect with similar hero image on svelte.dev tho

### Reproduction

Visit kit.svelte.dev

### System Info

```Shell
Safari 16.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
@benmccann is this a bug within `vite-imagetools` or why is it outputting `960` two times??

**Comment by benmccann** [comment]
@benmccann is this a bug within vite-imagetools?

Yes. Here's a PR to upgrade us to the latest version to fix it: https://github.com/sveltejs/kit/pull/10336

> why is it outputting 960 two times??

That part seems fine - it's outputting multiple image formats: avif, webp, png
