### ISSUE TITLE
We need to be able to get Raw body's request data from API

### ISSUE THREAD

**Issue by alanxp** [sveltejs/kit#10339]
### Describe the problem

When we get a request from our API, i can't seem to get the raw body request that stripe needs for the webhooks so i can't process payments lol. Been very frustrating, already searched for days, gpt + bard + forums and nothing. Stripe needs the body request untouched without any sveltekit's processing on it.

So using request.text() it wont help since it already has some processing.

### Describe the proposed solution

Be able to get request.rawData

### Alternatives considered

The only idea to make it work is to use a custom node server but that's just not the ideal

### Importance

i cannot use SvelteKit without it

**Comment by tcc-sejohnson** [comment]
Please provide an actual reproduction. What you're describing is possible, so we can't help without knowing what's going wrong.

**Comment by tcc-sejohnson** [comment]
I'm closing this as it has no reproduction. If you're still having this issue, please open a new one with a reproduction conforming to the requirements in the issue template.

**Comment by LamechIsrael** [comment]
I need help on this as well. All the packages I use return some sort of error, when trying to get the raw-body. The buffer from micro returns "Invalid body." And getRawBody returns "Argument stream must be a stream." Whatever that means.

```
import { NextApiRequest, NextApiResponse } from "next";
import Stripe from "stripe";
import { headers } from "next/headers";
import getRawBody from "raw-body";

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY as string, {
  apiVersion: "2023-10-16",
});

const endpointSecret = process.env.WEBHOOK_SECRET as string;

// Make sure to add this, otherwise you will get a stream.not.readable error
export const config = {
  api: {
    bodyParser: false,
  },
};

export async function POST(req: NextApiRequest, res: NextApiResponse) {
  try {
    const headersList = headers();
    const signature = headersList.get("stripe-signature") as string;


    const rawBody = await getRawBody(req);
  } catch (error) {
    console.error(error);
 
    return Response.json({
      key: "message",
      status: 500,
      message:
        "Internal Server Error. Check /api/payment/stripe-webhook-endpoint.ts",
    });
  }
}
```
