### ISSUE TITLE
[issue] hmr of vite is not working when we change in svelte file

### ISSUE THREAD

**Issue by ayush4345** [sveltejs/kit#10342]
### Describe the bug

i made the app with the help of Sveltekit yesterday. When I try to change +page.svelte in /src/routes. page is not get reloaded with new changes. I have to stop and restart the Vite server to see the difference which is annoying.

Here is the repo [gaming-review](https://github.com/ayush4345/gaming-review)

### Reproduction

if u want u can clone the repo and then npm i and then npm run dev. and try to make changes in the file in routes folder.

### System Info

```Shell
any bowser
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Cannot reproduce with the given instructions. Fill out the system info and preferably post a recording of what you're doing.

**Comment by ayush4345** [comment]
well, hmr of vite is not working when I working with wsl but now without wsl it is working. idk what was problem when working with wsl. so it is solve now
