### ISSUE TITLE
Vite v4.4.0+ restart dev server crashed by "@sveltejs/kit/vite" plugin.

### ISSUE THREAD

**Issue by hackape** [sveltejs/kit#10349]
### Describe the bug

See also https://github.com/vitejs/vite/issues/13735. 

This error can easily be triggered by hitting "r" key in vite CLI to restart the dev server.

### Reproduction

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-nvauxh?issueRepo=vitejs/vite&issueNumber=13735)

### Logs

```Shell
VITE v4.4.1  ready in 1272 ms

  ➜  Local:   http://localhost:5173/     
  ➜  Network: http://169.254.35.252:5173/
  ➜  Network: http://192.168.10.165:5173/
  ➜  Network: http://172.31.96.1:5173/   
  ➜  press h to show help
1:09:14 AM [vite] .env changed, restarting server...

const err = new Error('The server is being restarted or closed. Request is outdated');
                ^

Error: The server is being restarted or closed. Request is outdated
    at throwClosedServerError (node_modules/.pnpm/vite@4.4.1_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-439026c8.js:43694:17)
    at loadAndTransform (node_modules/.pnpm/vite@4.4.1_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-439026c8.js:54807:9)
    at async instantiateModule (node_modules/.pnpm/vite@4.4.1_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-439026c8.js:55738:10) {
  code: 'ERR_CLOSED_SERVER'
}

Node.js v18.16.0
```

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M2 Pro
    Memory: 155.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    pnpm: 8.6.3 - ~/.nvm/versions/node/v18.14.0/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.41
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.22.1 
    svelte: ^4.0.0 => 4.0.5 
    vite: 4.4.2 => 4.4.2
```

### Severity

annoyance

### Additional Information

It is introduced by this vite PR: https://github.com/vitejs/vite/issues/13262.

The error originates from [`align_exports`][1] function call in "@sveltejs/kit/vite", where it calls `await vite.ssrLoadModule(...);`. This happens in sveltekit plugin's "configureServer" hook, which is tapped when vite `restartServer`. 

And since [`server._restartPromise = restartServer(server)`][2], but `vite.ssrLoadModule` will eventually call `loadAndTransform` containing this line: [`if (server._restartPromise) throwClosedServerError()`][3], this error is always thrown.

[1]: https://github.com/sveltejs/kit/blob/6cb283e19a304bb6efe9971554a488cf77b9c41a/packages/kit/src/exports/vite/dev/index.js#L345-L357
[2]: https://github.com/vitejs/vite/blob/8f109a67bd54b0eb7679fe1fafc56e03a247b768/packages/vite/src/node/server/index.ts#L497
[3]: https://github.com/vitejs/vite/blob/8f109a67bd54b0eb7679fe1fafc56e03a247b768/packages/vite/src/node/server/transformRequest.ts#L259

**Comment by hackape** [comment]
I'm blind to background info, but what is with these comments 😅

https://github.com/sveltejs/kit/blob/6cb283e19a304bb6efe9971554a488cf77b9c41a/packages/kit/src/exports/vite/dev/index.js#L345-L348

**Comment by 231tr0n** [comment]
I am also facing the same issue suddenly with my sveltekit template initialised project. Hope this gets resolved quickly. I wanted to know if there are any workarounds for this bug which I can temporarily implement to get the restart part of vite working.

**Comment by 231tr0n** [comment]
I am also facing the same issue suddenly with my sveltekit template initialised project. Hope this gets resolved quickly. I wanted to know if there are any workarounds for this bug which I can temporarily implement to get the restart part of vite working.

**Comment by Rossvold** [comment]
After updating Vite from 4.2 this exact problem appears, this happens also everytime you restart the server in the terminal. Severely annoying.

**Comment by RBird111** [comment]
@231tr0n 
> I am also facing the same issue suddenly with my sveltekit template initialised project. Hope this gets resolved quickly. I wanted to know if there are any workarounds for this bug which I can temporarily implement to get the restart part of vite working.

Workaround is to downgrade to Vite version 4.3.9 for the time being.
![Screenshot 2023-07-08 094339](https://github.com/sveltejs/kit/assets/110942324/687b1a25-b07c-4deb-981d-0afac7fc02ca)
![Screenshot 2023-07-08 094231](https://github.com/sveltejs/kit/assets/110942324/c06666ed-18fc-406b-bda7-9a859ccc5f48)

**Comment by 231tr0n** [comment]
> @231tr0n
> 
> > I am also facing the same issue suddenly with my sveltekit template initialised project. Hope this gets resolved quickly. I wanted to know if there are any workarounds for this bug which I can temporarily implement to get the restart part of vite working.
> 
> Workaround is to downgrade to Vite version 4.3.9 for the time being. ![Screenshot 2023-07-08 094339](https://user-images.githubusercontent.com/110942324/252013454-687b1a25-b07c-4deb-981d-0afac7fc02ca.png) ![Screenshot 2023-07-08 094231](https://user-images.githubusercontent.com/110942324/252013528-c06666ed-18fc-406b-bda7-9a859ccc5f48.png)

Lol ok how did i miss this point XD thank you for reminding me. Will do that and check it out.

**Comment by bluwy** [comment]
I've made a fix upstream as it's a Vite bug. Closing in favour of https://github.com/vitejs/vite/issues/13735

**Comment by bluwy** [comment]
Re-opening as otherwise the Vite fix would actually corrupt the SvelteKit state 😬 Will send a following PR here.

**Comment by bluwy** [comment]
Nevermind, now it's really fixed in Vite 😅
