### ISSUE TITLE
compatible with @vercel/ncc

### ISSUE THREAD

**Issue by goldalworming** [sveltejs/kit#10357]
### Describe the problem

I need to integrate compiled sveltekit with express node that compiled into single (or multiple) file using @vercel/ncc

single executed files without node_modules is always awesome for deployment workflow

I have tried to compile to cjs and esm and it doesn't work

### Describe the proposed solution

compiled sveltekit integrate to express node that compiled into singlefile using @vercel/ncc

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Please provide more details on what you want to achieve - from the issue description I'm not sure what exactly you want to do. It would be helpful if you could provide a minimum reproducible to show how you are using `@vercel/ncc` to achieve your goal.

**Comment by goldalworming** [comment]
I want to build sveltekit server code and express code to merge into one file

    import express from 'express';
    import { handler } from './build/handler.js';
    import redis from 'redis'


    const app = express();
    import { createClient } from 'redis';

    const clientRedis = createClient();
    clientRedis.on('error', err => console.log('Redis client Error', err));
    clientRedis.connect({ url: 'redis://127.0.0.1:6379' });
    process.on("exit", function(){
        // clientRedis.disconnect();
        clientRedis.quit();
    });

    // add a route that lives separately from the SvelteKit app
    app.get('/healthcheck', (req, res) => {
        res.end('ok');
    });

    app.get('/redisdata', (req, res) => {
        const value = await client.get('test');
        res.status(200).json({success:true,value:value })
    });

    // let SvelteKit handle everything else, including serving prerendered pages and static assets
    app.use(handler);

    app.listen(3000, () => {
        console.log('listening on port 3000');
    });
    


I build system into onefile so it easier to deploy to production

**Comment by dummdidumm** [comment]
It's not possible to package the SvelteKit output into one file. The build output contains HTML, CSS and other static assets which you can't just bundle into one JavaScript file. You can bundle the server runtime, but you can't bundle the client.
You still did not provide a reproducible that shows how you actually are trying to use `@vercel/ncc` to achieve your goal. I'm confident it's possible to use a bundler to bundle the server runtime (but nothing else, as pointed out above), but it's not a concern of SvelteKit itself, therefore closing.
