### ISSUE TITLE
importing normalize in layout breaks the input bind

### ISSUE THREAD

**Issue by tombohub** [sveltejs/kit#10356]
### Describe the bug

Installing normalize via npm and importing in +layout.svelte breaks the input bind on +page.svelte. Typing into input doesn't update the state

### Reproduction

https://codesandbox.io/p/sandbox/autumn-shadow-x6km7y

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 101.72 MB / 2.01 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    pnpm: 7.1.0 - /usr/local/bin/pnpm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87 
    @sveltejs/kit: next => 1.0.0-next.541 
    svelte: ^3.46.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.3
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This is a library that only works on the server, not in the browser. You can see that by observing the error in the console where it says `ReferenceError: process is not defined` which stems from the `normalize` package. This means you can't use it within Svelte components that are used on the client.
