### ISSUE TITLE
Duplicate CSS rules after build

### ISSUE THREAD

**Issue by stefandevai** [sveltejs/kit#10379]
### Describe the bug

Hello everyone!

I'm building a personal blog and for for some reason the link tags containing css files are duplicated in production only. In dev mode everything looks fine. For this reason, every style is duplicated.

I've created a repo and added only @sveltejs/adapter-static and the issue remained.

Thanks in advance.

### Reproduction

https://github.com/stefandevai/duplicated-css

- Build the package
- Serve the static files generated on the build directory
- Open the example in a browser (tested with firefox and chrome) and inspect the orange title
- The CSS rule `background: orange;` is shown twice

![image](https://github.com/sveltejs/kit/assets/15495352/c5236122-f6fb-4331-8829-c3813e6ca18c)

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 565.56 MB / 4.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^1.20.4 => 1.22.3 
    svelte: 4.0.5 => 4.0.5 
    vite: ^4.4.2 => 4.4.3
```

### Severity

serious, but I can work around it

**Comment by performautodev** [comment]
Bump

**Comment by ghostdevv** [comment]
I believe this is because in the SSR output we have a link tag, and it's also being added by the hydration step. I don't think this would be considered a bug, or even fixed - I myself am not sure how to. At the very least I wouldn't worry about it since it's not causing duplicated network requests :pray:

**Comment by stefandevai** [comment]
It's a bit annoying regarding DX. When creating layouts, I usually iterate a lot of possibilities in the browser dev tools before writing the actual CSS. When the CSS is duplicated, I have to turn off CSS rules two times. I also don't think it's normal, I spent quite some time debugging believing it was an issue on my end.

**Comment by ghostdevv** [comment]
> It's a bit annoying regarding DX. When creating layouts, I usually iterate a lot of possibilities in the browser dev tools before writing the actual CSS. When the CSS is duplicated, I have to turn off CSS rules two times. I also don't think it's normal, I spent quite some time debugging believing it was an issue on my end.

Iirc the issue is only present after building with static adapter?

**Comment by s3812497** [comment]
@stefandevai A temporary workaround is to turn off SSR as well.
```ts
// routes/+layout.svelte
export const prerender = true;
export const ssr = false;
```

I tested and it seems to happen to the node adapter too. Currently only affects Chrome and Firefox (Safari on macOS doesn't parse the stylesheet twice). I'm not sure how to fix this but maybe Kit can always set SSR to false if prerender is true? It wouldn't make sense for `prerender` and `ssr` options to co-exist, right?

**Comment by s3812497** [comment]
Seems like [Vite](https://github.com/vitejs/vite/blob/1292ad08a06e2ae8c44307797ba533f64a602759/packages/vite/src/node/plugins/importAnalysisBuild.ts#L121-L128) is responsible for adding the `<link>` tags to the head in addition to what [SvelteKit](https://github.com/sveltejs/kit/blob/b251b235b321b9c75236429cc3a1ac2415475775/packages/kit/src/runtime/server/page/render.js#L240) is already adding. I'm not sure if this is intended behaviour? I can't seem to figure out how to prevent Vite from doing so (and what negative effects there may be if any).
