### ISSUE TITLE
Access to `nonce` in `<svelte:head>`? (Using Partytown with CSP enabled)

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#10377]
### Describe the problem

I'm trying to use Partytown in my SvelteKit app.

The [SvelteKit guide in Partytown's official documentation](https://partytown.builder.io/sveltekit) involves injecting the Partytown script in the root layout via a `<script>` tag in `<svelte:head>`.

This won't work if you have CSP with nonces enabled, because the `<script>` tag won't have the nonce. This means plugins like [partytown-sveltekit](https://github.com/romaindurand/partytown-sveltekit) also won't work.

### Describe the proposed solution

Somehow provide access to the generated `nonce` in `<svelte:head>`? Like so maybe:
```svelte
<svelte:head let:nonce>
    <script {nonce}>
        // Partytown script
    </script>
</svelte:head>
```
Or perhaps automatically add the nonce to every `<script>` tag including those rendered using `<svelte:head>` in the components?

### Alternatives considered

If there are any sane workarounds for getting Partytown to work with SvelteKit while using CSP, let me know.

### Importance

would make my life easier

**Comment by aradalvand** [comment]
**Update:**

After a bit of investigation, it seems like even if SvelteKit gave us the nonce in this context, Partytown would still not necessarily be fully functional because [it might add `<script>` tags itself](https://github.com/BuilderIO/partytown/blob/5ecb567f0103bcde473295bc7ae579abec922e6c/src/lib/main/snippet.ts#L107) as part of its setup; which would not work due to the same problem.

I think the "right" solution is actually using [`strict-dynamic`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#strict-dynamic), which allows "trusted" scripts to load other scripts by creating `<script>` elements. With `strict-dynamic` in place, our root layout could simply render a `<script>` element which it then populates with the Partytown snippet on mount:

```svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { partytownSnippet } from '@builder.io/partytown/integration';

	let scriptTag: HTMLScriptElement;
	onMount(() => {
		scriptTag.textContent = partytownSnippet();
	});
</script>

<svelte:head>
	<script bind:this={scriptTag}></script>
</svelte:head>
```

**Comment by aradalvand** [comment]
Closed as I don't think there's anything SvelteKIt should be doing here. `strict-dynamic` is tracked by #3558 of course.

**Comment by aradalvand** [comment]
I'm reopening this cause I think having access to `nonce` in `<svelte:head>` is generally something that you might need in many other scenarios, even if some of those can be worked around by using `strict-dynamic`.

**Comment by yuriyostapenko** [comment]
Wouldn't it be ideal if svelte automatically added `nonce` to such inline scripts from components?
In my case, I experience this problem with a third party dependency, and wondering how to fix it best.

**Comment by fnimick** [comment]
This is similarly a problem with https://github.com/svecosystem/mode-watcher

The library has been updated to have the component accept a `nonce` prop, but there's no good way to pass that through from the CSP without manually manipulating headers in hooks and attaching a generated nonce to the `locals`.

**Comment by dominikg** [comment]
You can use  a server hook with transformPageChunk to inject the partytown script  into a script block in app.html that you have prepared with the nonce

```html
<script nonce="%sveltekit.nonce%">
%partytown.snippet%
</script>
```

```js
export const handle = (async ({ event, resolve }) => {
	return resolve(event, {
		transformPageChunk: ({ html }) => {
			return html.replace(%partytown.snippet%', partytownSnippet());
		},
	});
}) satisfies Handle;
```

Access to the nonce itself has to be limited and must only be available to code provided by the sveltekit application itself. if we added it to svelte:head, a third party library could use it to render scripts with the nonce, bypassing the csp.

**Comment by dominikg** [comment]
As the og feature request asks for nonce access in svelte:head which would be inherently insecure, i'll close this. 
To improve support for partytown together with a csp, please start a discussion and/or join https://svelte.dev/chat and ask in `#help-svelte-and -kit`
