### ISSUE TITLE
Remove `kit.target`

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#1038]
**Is your feature request related to a problem? Please describe.**
I want to lower the amount of unnecessary elements in my DOM. Especially wrappers close to `<body>` that effect the majority of my application's structure.

Currently my slightly modified hello world app.html looks like this:
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="/favicon.ico" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		%svelte.head%
	</head>
	<body>
		<div id="svelte">%svelte.body%</div>
	</body>
</html>
```

My $layout HTML looks like this:
```html
<main>
  <nav></nav>
  <section>
    <aside></aside>
    <slot />
  </section>
</main>
```

Which together generates this HTML:
```html
<body>
	<div id="svelte">
		<main>
			<nav></nav>
			<section>
				<aside></aside>
				hello world
				</section>
			</section>
		</main>
	</div>
</body>
```

The `<div id="svelte">` element is now practically obsolete as it is only wrapping one element: `<main>`.  Because my css/structure is heavily state based I do all my primary styling inside of my $layout. The #svelte element is just there because it needs to be as there is no way to remove it automatically after hydration is completed.

**Describe the solution you'd like**
I want SvelteKit to fill the `<body>` with `%svelte.body%` by default. 

If I wrap all my elements in my layout in for example a `<main>` element SvelteKit should use that element to hydrate the application. If no wrapper is found it should generate the default `#svelte` wrapper element for me and use hydrate that one instead.

Maybe it would be good to promote the use of wrappers for $layout components by throwing a warning when a layout is sharded/does not have a single wrapper. But that may be a discussion for another day.

**Describe alternatives you've considered**
- Set the target to body and pray that the user does not have any extensions installed
- Migrate the main element to the app.html and somehow modify that element through vanilla JavaScript.

**How important is this feature to you?**
Important but not a deal breaker. The wrapper just makes the general structure of my application uglier, more complex and requires me to write extra CSS here and there to solve issues caused by this wrapper.

**Additional context**
None atm.

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs#configuration-target If you don't specify a `kit.target`, the app is mounted to `document.body`, and you should be able to edit `src/app.html` accordingly.

**Comment by dummdidumm** [comment]
What's stopping you from adjusting your `app.html` and removing `target` from the `svelte.config.cjs`? [According to the docs](https://kit.svelte.dev/docs#configuration-target), the fallback is the body.

**Comment by UltraCakeBakery** [comment]
> https://kit.svelte.dev/docs#configuration-target If you don't specify a `kit.target`, the app is mounted to `document.body`, and you should be able to edit `src/app.html` accordingly.

@Conduitry thank you for the information. 

@dummdidumm & @Conduitry
Coming from Vue/React/Sapper I've always heard that mounting to / hydrating `document.body` directly is not the best idea. The user might have browser extensions installed that add elements to `document.body` which would get removed or possibly break the framework. These issues are very difficult to trace back if you don't have full context of the users env.

**Comment by dummdidumm** [comment]
So you don't want to mount to `body`, but you also want to get rid of the `div` inside the `body` - those are conflicting requirements.

**Comment by UltraCakeBakery** [comment]
Explaining myself is something I'm not very good at. I'll try to clarify:

If my layout component has _all_ html wrapped in a wrapper element - that element can be whatever element you want - SvelteKit should use that element as the element that gets hydrated. Otherwise, if my component _does not_ have all html wrapped in a wrapper element, SvelteKit should create the wrapper for me (and hydrate that one).

I'm not entirely sure if SvelteKit should create the wrapper for me when I don't wrap my layout elements. That is something I happily discuss.

If people can confirm that targeting the body is never going to be an issue or leave room for instability / unreliability we wouldn't need to change anything. But as far as I know there are issues when targeting / hydrating the body directly. That's why I created this issue.

I just want to be able to have my layout take over the wrapper element after hydration and still have Svelte Kit work as expected. 
Maybe the title of this issue would need to be changed to reflect what I want better. If anyone knows how to word it better than I'm doing right now, be my guest.

**Comment by benmccann** [comment]
It doesn't seem to me like there's any pressing issue here, so I'm going to go ahead and close this. I don't think this is something we need to hyper optimize for given how many higher priority issues there are and there's also potential downsides such as complicating usage by making things work multiple ways or adding API surface
