### ISSUE TITLE
@sveltejs/adapter-vercel is not in the npm registry

### ISSUE THREAD

**Issue by CamiloAlmada** [sveltejs/kit#10384]
### Describe the bug

Hello I was trying to deploy on vercel and found this while trying to pnpm install the base project
```
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sveltejs%2Fadapter-vercel: Not Found - 404

@sveltejs/adapter-vercel is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
```

### Reproduction

pnpm install a project which have a @sveltejs/adapter-vercel dependency

### Logs

```Shell
pnpm install
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@sveltejs%2Fadapter-vercel: Not Found - 404

@sveltejs/adapter-vercel is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 4, reused 2, downloaded 0, added 0
```

### System Info

```Shell
System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (8) x64 Intel(R) Core(TM) i3-10105 CPU @ 3.70GHz
    Memory: 591.80 MB / 15.61 GB
    Container: Yes
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 9.7.2 - /usr/local/bin/npm
    pnpm: 7.5.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 105.0.5195.102
```

### Severity

annoyance

**Comment by rchrdnsh** [comment]
same issue for me as well.

**Comment by Conduitry** [comment]
https://www.npmjs.com/package/@sveltejs/adapter-vercel It definitely is published to the registry, so I'm not sure what this could be, other than some issue on their end,

**Comment by matthewyu01** [comment]
It's an [npm issue](https://status.npmjs.org/incidents/jglnklhspsnm). I have the same registry error with other packages

**Comment by Conduitry** [comment]
`curl https://registry.npmjs.org/@sveltejs%2Fadapter-vercel` is returning a 200, as expected, and not a 404.

**Comment by rchrdnsh** [comment]
working again for me as well :-)
