### ISSUE TITLE
Problem with local transition

### ISSUE THREAD

**Issue by georges-g** [sveltejs/kit#10417]
### Describe the bug

Hi,

Thanks for the open source work, great project!

I am in a situation where I cannot have my local transition working, and I don't want to have a global transition as it slows down page navigation.

This was already discussed [there](https://github.com/sveltejs/kit/issues/628#issuecomment-1342393920), but the issue as been closed, whereas the problem is still there.

### Reproduction

To understand the bug, you can check [this repo](https://github.com/georges-g/sveltekit-local-transition-bug) I made. There is also this [stackoverflow question](https://stackoverflow.com/questions/76730390/how-to-fix-a-local-transition-that-is-not-working).

Basically, I'm filling a form with error or success messages. I use a store and a `FormMsg` component. I need this component to be able to close the message from within. Functionally, it works well, but I cannot use a local transition on the `FormMsg`, it is simply not applied. I don't want to use it anyways, but global transition does not seem to work either.

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 11.79 GB / 15.56 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.1.0/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
    pnpm: 8.5.0 - ~/.nvm/versions/node/v18.1.0/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.22.3 
    svelte: ^4.0.5 => 4.1.1 
    vite: ^4.4.2 => 4.4.5
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
It sounds like you want more control over when the transition is applied, or how many levels deep it is applied. I'm closing this in favor of https://github.com/sveltejs/svelte/issues/8850

**Comment by georges-g** [comment]
It sounds like that could be a solution.

Another option would be to have a `|all-but-navigation` filter or something like that. It would specify that the transition is happening in any case, except if it is a page navigation.
