### ISSUE TITLE
Index page trailing slash 200

### ISSUE THREAD

**Issue by multipliedtwice** [sveltejs/kit#10414]
### Describe the bug

Index page returns 200 on homepage with trailing slash. 

### Reproduction

https://kit.svelte.dev/

![image](https://github.com/sveltejs/kit/assets/33694447/33bb26cb-99f9-450e-9657-bb3bc8f84772)

### System Info

```Shell
any
```

### Severity

annoyance

**Comment by ghostdevv** [comment]
I don't think this is an issue, since stripping the trailing slash

**Comment by ghostdevv** [comment]
I don't think this is an issue on `/` pages, you'll notice if you go to other pages such as [/docs/introduction/](https://kit.svelte.dev/docs/introduction/) you are getting a redirect. Let me know if I am wrong :pray:

**Comment by multipliedtwice** [comment]
@ghostdevv hello, Google expects the response code that explicitly indicates redirect.

https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash

Otherwise it counts it as duplicate content, as I understand from the article.  Correct me if I'm wrong.

And I guess it wouldn't be a problem for some/page/down/below/with-low-seo-weight. But index page has the highest amount of weight (importance). 

Or you can download sitechecher Google extension that will mark it as error and reduce your website overall tech audit score on each internal page because of index page.

**Comment by multipliedtwice** [comment]
@ghostdevv hello, Google expects the response code that explicitly indicates redirect.

https://developers.google.com/search/blog/2010/04/to-slash-or-not-to-slash

Otherwise it counts it as duplicate content, as I understand from the article.  Correct me if I'm wrong.

And I guess it wouldn't be a problem for some/page/down/below/with-low-seo-weight. But index page has the highest amount of weight (importance). 

Or you can download sitechecher Google extension that will mark it as error and reduce your website overall tech audit score on each internal page because of index page.

**Comment by fehnomenal** [comment]
From the same article:

> Rest assured that for your root URL specifically, https://example.com is equivalent to https://example.com/ and can't be redirected even if you're Chuck Norris.

**Comment by multipliedtwice** [comment]
> From the same article:
> 
> > Rest assured that for your root URL specifically, https://example.com is equivalent to https://example.com/ and can't be redirected even if you're Chuck Norris. 

Yes, the second grade doesn't mean defective lol

**Comment by multipliedtwice** [comment]
@fehnomenal as I understand, it doesn't mean it's the best behavior. Of course google will be able to catch it after some time for old domains. But it is still duplicated content on main page that can very well increase SEO budget for new sandboxed websites.
