### ISSUE TITLE
Returning Uint8Array / Buffer from `+page.server.ts load()`.

### ISSUE THREAD

**Issue by Palmik** [sveltejs/kit#10416]
### Describe the problem

Currently if you want to return binary data to the client you need to manually encode and decode the data using e.g. base64. This is cumbersome and error prone.

You run into this when using e.g. gRPC or when trying to return some file.

### Describe the proposed solution

It would be great to have native support for binary responses. This might also open doors for custom serialization formats -- I would love to have my load function return a protobuf, and transparently receive it on the client in `PageData`, in a type safe manner.

### Importance

would make my life easier

**Comment by ghostdevv** [comment]
The problem usually is if we start specifically going out of the way to support one framework/data type then we have to support others. Specifically for things like `Uint8Array` an issue would be better put in [devalue](https://github.com/Rich-Harris/devalue) as that's where the serialisation is coming from

**Comment by Palmik** [comment]
I agree that the support should not be framework specific. Uint8Array is a basic primitive.

**Comment by LorisSigrist** [comment]
I submitted a [Pull Request to devalue](https://github.com/Rich-Harris/devalue/pull/69) that would add support for Typed Arrays (like Uint8Array) and Arraybuffers. Let's see if it gets merged
