### ISSUE TITLE
Support i18n out of the box for SvelteKit

### ISSUE THREAD

**Issue by juniorforlife** [sveltejs/kit#10415]
### Describe the problem

I have checked these 2 issues ([1](https://github.com/sveltejs/kit/issues/553), [2](https://github.com/sveltejs/kit/issues/1274)) but seems like no progress has been made for i18n support out of the box in SvelteKit.
I believe i18n is crucial and should be built into SvelteKit

### Describe the proposed solution

Maybe take the existing library like [typesafe-i18n](https://github.com/ivanhofer/typesafe-i18n) and improve it?

### Alternatives considered

I'm aware of Ivan's `@inlang/sdk-js` but my first experience with this library is pretty buggy. Also this package tries to be framework agnostic which is cool but I think we should have something that is custom made for SvelteKit

### Importance

i cannot use SvelteKit without it

**Comment by ghostdevv** [comment]
Progress will be made towards it at some point, your best bet is to subscribe to those issues - going to close this as a duplicate :pray:
