### ISSUE TITLE
Couldn't deploy to Github pages

### ISSUE THREAD

**Issue by msanthoshofficial** [sveltejs/kit#10420]
### Describe the bug

I wanted to deploy a simple portfolio app in github pages, but got this error.
GET https://msanthoshofficial.github.io/portfolio/_app/immutable/chunks/index.cb53cde0.js net::ERR_ABORTED 404
Added base URL, used the right adapter but still same issue
![image](https://github.com/sveltejs/kit/assets/46109601/f76122d1-8498-45a9-b260-69f294e1ffae)

### Reproduction

https://github.com/msanthoshofficial/portfolio/tree/main

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 8.57 GB / 15.78 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.9 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (114.0.1823.82)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.0 => 2.1.0
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2
    @sveltejs/kit: ^1.22.3 => 1.22.3
    svelte: ^3.59.2 => 3.59.2
    vite: ^4.4.6 => 4.4.6
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
Please don't open issues for support requests, and please don't list your entire site as the reproduction.

I see that file is present at https://github.com/msanthoshofficial/portfolio/blob/gh-pages/_app/immutable/chunks/index.cb53cde0.js - if GitHub pages isn't serving it, then that's a GitHub pages configuration issue.

**Comment by ghostdevv** [comment]
See: https://kit.svelte.dev/docs/adapter-static#github-pages

**Comment by msanthoshofficial** [comment]
@Conduitry  Noted thanks!
@ghostdevv Thanks for the reference, I used `.github/workflows/deploy.yml` file to deploy instead of `gh-pages` which fixed the issue.

**Comment by Fasteroid** [comment]
Either the advice here is unclear or none of these solutions work.  Can someone here please explain exactly how I fix my site?
https://github.com/Fasteroid/svelte-portfolio

**Comment by Fasteroid** [comment]
> Please don't open issues for support requests, and please don't list your entire site as the reproduction.
> 
> I see that file is present at https://github.com/msanthoshofficial/portfolio/blob/gh-pages/_app/immutable/chunks/index.cb53cde0.js - if GitHub pages isn't serving it, then that's a GitHub pages configuration issue.

But *how* do I configure it correctly?  I get the exact same issue and I haven't done anything weird with my configuration.  It should either work out-of-the-box or be *clearly* documented at https://kit.svelte.dev/docs/adapter-static#github-pages (which I followed to the letter)

Reproduced at https://github.com/Fasteroid/svelte-portfolio and https://shinokada.github.io/sveltekit-githubpages/

Should be re-opened.
