### ISSUE TITLE
svelte-package doesn't resolve custom aliases

### ISSUE THREAD

**Issue by eakl** [sveltejs/kit#10425]
### Describe the bug

1. Open `src/lib/index.ts`
2. Run `npm run build`
3. Open `dist/index.js`

You can see that the custom alias is not resolved

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-scyeba?file=dist%2Findex.js

### System Info

```Shell
macOS
```

### Severity

annoyance

**Comment by ghostdevv** [comment]
Hey, it's because the syntax you used in the [alias](https://kit.svelte.dev/docs/configuration#alias) field is incorrect - you don't add `*`.

```diff
const config = {
  preprocess: vitePreprocess(),
  kit: {
    adapter: adapter(),
    alias: {
-      '$custom/*': './src/lib/custom/*',
+     $custom: './src/lib/custom',
    },
  },
};
```
