### ISSUE TITLE
sveltekit bundles production build in a way node can't start

### ISSUE THREAD

**Issue by Arikael** [sveltejs/kit#10432]
### Describe the bug

I have forked the starter project which you can see [here ](https://github.com/Arikael/svelte-test)

There is a[ `hooks.server.ts`](https://github.com/Arikael/sveltejs-test/blob/main/src/hooks.server.ts) with the following content
```
import type {Handle} from '@sveltejs/kit'
import {redirect} from '@sveltejs/kit'

export const handle: Handle = (async ({event, resolve}) => {
  
  if(event.url.pathname === '/test') {
    throw redirect(303, '/')
  }

  return resolve(event)
}) satisfies Handle
```

and under[ `routers/auth/login/+server.ts`](https://github.com/Arikael/sveltejs-test/blob/main/src/routes/auth/login/+server.ts)

```
import type {RequestHandler} from '@sveltejs/kit'
import {redirect} from '@sveltejs/kit'

export const POST: RequestHandler = (async ({ cookies }) => {
	throw redirect(303, '/about');

}) satisfies RequestHandler;
```
as you can see both import `redirect` from `@sveltejs/kit`

during development all is fine, but if you create the production build with `npm run build`  and then try to run this build via `node build` the process terminates immediatly.

The cause seems to be the following (generated code from `./build`)
in the file `server/chunks/handler-...` there is the function 
```
function get_hooks() {
  return import('./hooks.server-919689cf.js');
}
```

the file `hooks.server-919689cf.js` has the following line
```
import { r as redirect } from './handler-70d9707e.js';
```

this causes node to terminate immediatly (probably because of some circular dependency)
remove the redirect (and its import) and everything works.

I'm not sure if this is a svelte, vite or even a node problem.

### Reproduction

1. get https://github.com/Arikael/svelte-test
2. `npm i`
3. `npm run build`
2. `node build`
4. the process will terminate immediatly
5. remove all references to `redirect` from `hooks.server.ts`
6. `npm run build`
7. `node build`
8. server will start successfully

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 4.66 GB / 15.78 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.22621.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

It also happens on Linux (Oracle Linux 9 with NodeJs 18)

**Comment by gtm-nayan** [comment]
your reproduction repo is either private or deleted
