### ISSUE TITLE
link to correct source in error page

### ISSUE THREAD

**Issue by weepy** [sveltejs/kit#10440]
### Describe the problem

Currently the error pages do not link through to the correct page

<img width="698" alt="Screenshot 2023-07-27 at 11 40 22" src="https://github.com/sveltejs/kit/assets/820/bc829a6e-142b-42a6-8944-76f89241cb81">

the link is just relative to the project "/src/lib/components/ProjectMain.svelte:127:17" - but it needs the file:// prefix plus the location of the project.

It must be possible since with the svelte inspector it's possible to open the relevant component with a click.

### Describe the proposed solution

Clicking on the error opens the correct file and goes to the correct line in the user's editor.

### Importance

nice to have

**Comment by s3812497** [comment]
I think this issue should be moved to https://github.com/sveltejs/vite-plugin-svelte.

**Comment by weepy** [comment]
i did it

**Comment by s3812497** [comment]
> i did it

Thank you!
