### ISSUE TITLE
Docs: hamburger menu clickable area is too small

### ISSUE THREAD

**Issue by theetrain** [sveltejs/kit#10452]
### Describe the bug

The mobile navigation hamburger menu on https://kit.svelte.dev/ is too small to hit; and missed hits lead to 'home' anchor link instead.

<img width="556" alt="image" src="https://github.com/sveltejs/kit/assets/12798751/9307da07-dba0-4674-98a0-3570a8831994">

I recommend having the hamburger button's hit area be the full height of the nav bar as well as touch the right edge. This should result in a 60x60px touch target area (obviously use scalable units instead of pixels).

### Reproduction

1. Go to <https://kit.svelte.dev>
2. Try to open hamburger menu

<img width="559" alt="image" src="https://github.com/sveltejs/kit/assets/12798751/6b52e69b-7bdb-4bb9-b8a6-16c7e82ebd2c">

### System Info

```Shell
All browsers
```

### Severity

serious, but I can work around it

**Comment by PuruVJ** [comment]
Already fixed in sync to svelte.dev pr
