### ISSUE TITLE
`sveltekit:prefetch` should be conditioned on the presence of `href`

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1045]
**Is your feature request related to a problem? Please describe.**
`sveltekit:prefetch` should be conditioned on the presence of `href`.

**How important is this feature to you?**
I have many dynamics `a` tag, some with, some without `href`.

**Additional context**
> Yes, it is valid to use the anchor tag without a href attribute.

From https://stackoverflow.com/a/33046203.

**Comment by c-bandy** [comment]
How should this work? Watch the `href` attribute and activate prefetch behavior dynamically if a `href` appears?

**Comment by frederikhors** [comment]
I don't know. But now, as it is, there is an error even on mouse hover.

**Comment by Rich-Harris** [comment]
I cannot imagine why anyone would add a `sveltekit:prefetch` attribute to an href-less anchor, but this is easy enough to do: https://github.com/sveltejs/kit/pull/1060

It may be technically _valid_ to have an anchor without an href, but it's very rare that it's _appropriate_ :)

**Comment by dummdidumm** [comment]
Should this be closed now that the PR is merged?
