### ISSUE TITLE
Method overrides

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1046]
I could have sworn we'd already talked about this at some point, but I guess not.

**Is your feature request related to a problem? Please describe.**
Bewilderingly, the only valid `<form>` methods are GET and POST — in other words `<form method="put">` is invalid, and will result in `form.method === 'get'`.

A popular workaround is to use a method override query string parameter, like so:

```html
<form method="post" action="/todos/{id}?_method=put">
  <!-- form elements -->
</form>
```

(As evidence for the validity of this approach, there's an official Express middleware for it: https://www.npmjs.com/package/method-override).

It would be nice if such a thing existed in SvelteKit as well, since we want to encourage people to build apps that work with JavaScript disabled, and that's only really possible if you can use PUT and DELETE alongside GET and POST without having to resort to `fetch`.

**Describe the solution you'd like**
Since the `?_method=put` cowpath already exists, I propose that we bake it into SvelteKit, while making it configurable:

```js
// svelte.config.cjs
module.exports = {
  kit: {
    methodOverride: {
      key: '_method',
      allowed: ['post', 'put', 'delete']
    }
  }
};
```

Then, when any request that comes in where `query.has(override)`, we change the request method before passing it to `handle`.

**How important is this feature to you?**
It would be possible to do in userland...

```js
export function handle({ request, render }) {
  return render({
    ...request,
    method: request.query.get('_method') || request.method
  });
}
```

...but I think this is the sort of thing that belongs in the framework.

**Comment by Conduitry** [comment]
Looking at the readme of that middleware, are they actually blessing that particular query parameter name? The only thing I saw blessed was a particular HTTP header. Or are you saying this would be off by default and people would need to explicitly opt in and say what query parameter they want to use?

**Comment by Rich-Harris** [comment]
They're blessing it in the sense that it's in the README. I've seen it used in a couple of different places

![image](https://user-images.githubusercontent.com/1162160/115113709-a095a700-9f59-11eb-8aba-43400ad606d7.png)

I'm suggesting that `_method` would be the default, but you could change it to whatever:

```js
// svelte.config.cjs
module.exports = {
  kit: {
    methodOverride: {
      key: 'httpverb',
      allowed: ['patch']
    }
  }
};
```

**Comment by Conduitry** [comment]
I think not having this be opt-in would just bother me, no matter what name we used or what level of blessed this was in that middleware. It could be that I just wasn't looking, but I've certainly not gotten the impression that this has been at all an established de facto standard.

**Comment by Rich-Harris** [comment]
I don't know if I'd go as far as saying it's a de facto standard, just that it's a cowpath. Can you articulate why it bothers you? The framework is already doing other frameworky things like generating 304s and parsing bodies and serving static assets, is this so different?

**Comment by Conduitry** [comment]
That a 304 means a redirect and that a given `content-type` means that this is form data or that this is JSON data are all established real standards. That `?_method=put` means "pretend this is a PUT" is not a standard. It's ascribing some additional meaning to something that officially has no particular meaning.

If this is an appeal to "2.4 million downloads of this package per month can't be wrong" then I will remind you about other commonly done things that you have complained about vehemently in the past. And if you still think this is a good idea, I'm not going to keep arguing about it, because it doesn't seem _that_ awful as a default.

**Comment by Rich-Harris** [comment]
The only reason I'm keen on it is that without method overrides there's basically no way to build a CRUD app that doesn't rely on JS, AFAICT, and if 'you can build robust apps that don't make anti-SPA-fanatics froth at the mouth' is one of the selling points of SvelteKit (which I think it is!) then maybe it warrants being part of the framework.

At the same time, I've rarely regretted listening to you in the past. I think we need some more opinions!

**Comment by GrygrFlzr** [comment]
For consideration - prior art using the `_method` hack:
- [Twitter PowerTrack API](https://developer.twitter.com/en/docs/twitter-api/enterprise/powertrack-api/api-reference/powertrack-rules#GetRules)
- [Ruby on Rails](https://guides.rubyonrails.org/form_helpers.html#how-do-forms-with-patch-put-or-delete-methods-work-questionmark)
- [Laravel](https://laravel.com/docs/8.x/routing#form-method-spoofing)
- [Symfony](https://symfony.com/doc/current/forms.html#changing-the-action-and-http-method)
- [CodeIgniter](https://codeigniter.com/userguide4/incoming/methodspoofing.html)
- [Java Spring](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/filter/HiddenHttpMethodFilter.html)
- [Rust `hyper`](https://docs.rs/hyper-method-override-middleware/1.0.0/hyper_method_override_middleware/)
- [Rust `rocket`](https://api.rocket.rs/v0.4/rocket/request/trait.FromForm.html)
- [Elixir Phoenix.HTML](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#form_for/4-options)
- [HTTP Method Override for Go](https://github.com/kataras/methodoverride)
- [WeatherSource API](https://developer.weathersource.com/documentation/rest/)

**Comment by Rich-Harris** [comment]
Thanks, that's very useful context. I see a few of these:

```html
<input type="hidden" name="_method" value="PUT">
```

Perhaps we should support both? In which case it probably would need to be in the framework, since that would be more finicky to do in userland

**Comment by benmccann** [comment]
I'm in favor of this proposal. It's something I don't want to have to think about implementing as a user and would be happy to have the framework handle. The only danger I see is if I had a form with an input named `_method` but that seems quite unlikely and the benefits far outweigh the risks in my opinion

**Comment by Conduitry** [comment]
I'm not at all against this being included in the framework; what I'm concerned about is this being non-standard behavior that is being sent to folks as a default.

**Comment by lukeed** [comment]
Gross 😅

Better to scaffold a server-side `POST /items/:id/update` endpoint imo. It can even be an alias to the same handler for `PUT` route. 

Methods and status codes are fundamental building blocks. Paths can be reworked if need be. And there's a much deeper cow path for shuttling everything thru POSTs if needed.

**Comment by Rich-Harris** [comment]
Huh. I find it much grosser to update or delete a resource with a POST request. If HTTP methods mean anything at all, then `POST /items/xyz/update` means 'create a new resource of the type `/items/xyz/update`, which is incoherent.

**Comment by satyakresna** [comment]
> 
> 
> Thanks, that's very useful context. I see a few of these:
> 
> ```
> <input type="hidden" name="_method" value="PUT">
> ```
> 
> Perhaps we should support both? In which case it probably would need to be in the framework, since that would be more finicky to do in userland

I like this option supported in svelte kit. In [Laravel Framework - method spoofing](https://laravel.com/docs/8.x/routing#form-method-spoofing) as mention by @GrygrFlzr, when do something about update or delete data like `PUT` or `PATCH` or `DELETE`  they give two options:

 ```
<form action="{{ route('update-url') }}" method="POST">
<input type="hidden" name="_method" value="PUT">
<input type="hidden" name="_token" value="csrf_token()">
</form>
```

OR


 ```
<form action="{{ route('update-url') }}" method="POST">
@method('PUT')
@csrf
</form>
```

**Comment by am283721** [comment]
I'd be interested in tackling this.

I think there would be value in providing both of these approaches for overriding:

```html
<form method="post" action="/todos/{id}?_method=put">
```
AND
```html
<input type="hidden" name="_method" value="PUT">
```

The question of whether or not it should be enabled by default is interesting. Enabling by default could create some unexpected and confusing behavior for anyone unaware of the functionality. But I have to imagine the odds of someone submitting a form with a `_method` parameter has to be slim to none.

**Comment by 205g0** [comment]
FWIW, a user's perspective: Just stumbled over this `?_method...` override in Kit's demo app and was gonna write an angry issue about this confusing code until I found this issue and the conditional rewrite in hooks.ts.

First, I wanted to do the adapt your solution but I decided just to use POST for any mutation and GET for all queries, and nothing else. I use on the storage-side anyway kind of super-powered upsert for all mutations. This can create new objects, replace existing ones and/or patch existing ones (all paired with strict types if anyone cares, so it's not a mess, haha). None of the HTTP verbs matches this upsert behavior exactly (it's a blend of PUT and PATCH), so I thought, why all this fuzz, mental drain for nothing. Not sure how I gonna deal with DELETEs yet, maybe just POST an empty object or an extra flag, IDK yet, latter ideas feel also hacky, so I might opt for the method override just for DELETEs.

However and in general, if this method override is done in prior frameworks and learned by the users, why not.

**Comment by ignatiusmb** [comment]
Resolved by #2989

**Comment by aarondoet** [comment]
Has this feature been removed? I can no longer find it in the docs anymore, the type of the svelte config also doesn't seem to have the `config.kit.methodOverride` property anymore. Is there another way to easily achieve this?

**Comment by sillvva** [comment]
> Has this feature been removed? I can no longer find it in the docs anymore, the type of the svelte config also doesn't seem to have the `config.kit.methodOverride` property anymore. Is there another way to easily achieve this?

https://github.com/sveltejs/kit/pull/6469

Here's the full documentation for the replacements:
https://svelte.dev/docs/kit/form-actions
https://svelte.dev/docs/kit/routing#server

**Comment by aarondoet** [comment]
Oh yeah that makes sense. Knew about actions but somehow didn't think of this right now. Imma go sleep now, apparently I need it. Thanks!
