### ISSUE TITLE
+layout.js data don't include all parent layout.server.js data

### ISSUE THREAD

**Issue by jere2101** [sveltejs/kit#10476]
### Describe the bug

I don't know if the following is an understanding problem or if this is a bug. 
The problem is that I have a main layout.server.ts where I return data and my layout.ts in a subdirectory doesn't include this data. 

And yeah I know that the load Functions are not blocking each other but I thought all server load function have to be executed before the layout.js are executed. And the data from a layout.server.js that is in the same directory then the layout.js is included in the event.data. So my assumption was that all parent layout.server.js data are included in the layout.js as (event.data).

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-6qqepz?file=src%2Froutes%2Fsub%2F%2Blayout.js

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 18.81 GB / 22.91 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.20.1 - /usr/bin/node
    npm: 8.19.4 - /usr/bin/npm
    pnpm: 8.1.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.110
  npmPackages:
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4 
    @sveltejs/kit: ^1.20.4 => 1.20.4 
    svelte: ^4.0.5 => 4.0.5 
    vite: ^4.3.9 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
A `+layout.server.js` will get executed before its corresponding `+layout.js`. But no, each layer still gets executed in parallel.

Accessing data from higher-level `load` functions is discussed in https://kit.svelte.dev/docs/load#using-parent-data

**Comment by s3812497** [comment]
> And the data from a layout.server.js that is in the same directory then the layout.js is included in the event.data.

In a load function, you can access the parent data with `await parent()`. Only in the page itself (+page.svelte), all data is merged together.

```js
/** @type {import('./$types').LayoutLoad} */
export const load = async (event) => {
	const parentData = await event.parent();
	console.log(parentData);
	return { test: '123', ...parentData };
};
```

See https://kit.svelte.dev/docs/load#using-parent-data for more information.

**Comment by jere2101** [comment]
Ok thanks for the help. That all layout.server.js and layout.js pairs get executed in parallel was the missing peace for me. My understanding of the docs was that all layout.server.js get executed in parallel and merged together for the layout.js that get executed in parallel then.
