### ISSUE TITLE
Url/link component to get genereated page

### ISSUE THREAD

**Issue by StagnantIce** [sveltejs/kit#10485]
### Describe the problem

Now i need write my urls by myself, for use it in svelte files.

### Describe the proposed solution

Generate url component:

```
export const URL = {
    cookiePolicy: '/cookies-policy',
    user: (id: number) => `/user/${id}`,
    ....
}
```

### Importance

would make my life easier

**Comment by gtm-nayan** [comment]
Please provide a proper reproduction and description for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please **do NOT just paste a link to your project**. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by Conduitry** [comment]
@gtm-nayan This is a feature request, not a bug report - but it is a kind of open-ended one.

**Comment by gtm-nayan** [comment]
Oh, right, brain autopiloted cause of the lacking description. Updated the comment above.
