### ISSUE TITLE
Vite resolve.alias fails when given an array of { find, replacement } pairs

### ISSUE THREAD

**Issue by theurgi** [sveltejs/kit#1048]
vite 2.1.5
@sveltejs/vite-plugin-svelte 1.0.0-next.5
@sveltejs/kit 1.0.0-next.76

---

According to the [Vite spec](https://vitejs.dev/config/#resolve-alias), **resolve.alias**

>Can either be an object, or an array of `{ find, replacement }` pairs.

With a directory structure as follows...

```
.
├── bar
├── foo
└── svelte.config.cjs
```
this `svelte.config` will work ...

```
// ...
const path = require("path");

module.exports = {
  // ...
  kit: {
    // ...
    vite: () => ({
      // ...
      resolve: {
        alias: {
          "@foo": path.resolve(__dirname, "foo"),
          "@bar": path.resolve(__dirname, "bar"),
        },
      },
    }),
  },
};

```
but this one will not...

```
//...
const path = require("path");

module.exports = {
  // ...
  kit: {
    // ...
    vite: () => ({
      // ...
      resolve: {
        alias: [
          {
            find: "@foo",
            replacement: path.resolve(__dirname, "foo"),
          },
          {
            find: "@bar",
            replacement: path.resolve(__dirname, "bar"),
          },
        ],
      },
    }),
  },
};

```

It doesn't make a difference if `vite` is given a config object or a function returning one. 

The first `svelte.config` works fine, so it's not a big deal, but as of now the SvelteKit docs only provide this vague info regarding Vite configuration:

> `vite`
>A [Vite config object](https://vitejs.dev/config/), or a function that returns one. **Not all configuration options can be set, since SvelteKit depends on certain values being configured internally**.

So at the very least, if not handling an array of `{ find, replacement }` pairs, it would be helpful to update the docs by specifying exactly what `vite` configuration options can be set.

**Comment by rmunn** [comment]
What happens if you give it an array of `[ find, replacement ]` pairs? I.e. instead of this:

```js
        alias: [
          {
            find: "@foo",
            replacement: path.resolve(__dirname, "foo"),
          },
          {
            find: "@bar",
            replacement: path.resolve(__dirname, "bar"),
          },
        ],
```

What if you did this?

```js
        alias: [
          [ "@foo", path.resolve(__dirname, "foo") ],
          [ "@bar", path.resolve(__dirname, "bar") ],
        ],
```

I haven't tested this, that's just what occurred to me as what the documentation *might* mean. If this works, this is a documentation bug because the `{ }` characters in the docs make people misunderstand what format the Vite option is expecting.

**Comment by theurgi** [comment]
See [Vite's `AliasOptions` type definition](https://github.com/vitejs/vite/blob/41261c70e6d65ddf1dca52a6e94e5aa555539581/packages/vite/types/alias.d.ts) which is taken from @rollup/plugin-alias:

> This is passed to \@rollup/plugin-alias as the "entries" field

@rollup/plugin-alias also expects an `Object | Array[...Object]` as you can see [here](https://github.com/rollup/plugins/tree/master/packages/alias#arrayobject-format).

This could be an issue on Vite's end, I'm not sure. But just in case anyone runs into this via SvelteKit (as I did), hopefully this issue can save them some trouble until things are resolved.

**Comment by rmunn** [comment]
Yep, that's definitely supposed to be an array of `{ find: string, replacement: string }` objects. So my guess (which I dashed off without taking time to look up the docs since I only had five minutes) was wrong. Good to know.

Hmm, a quick search through the Vite issues yielded https://github.com/vitejs/vite/issues/3000, where the Vite config looks like this:

```js
export default defineConfig({
  plugins: [reactRefresh()],
  resolve: {
    alias: [
      {
        find: '@common',
        replacement: path.resolve('common'),
      },
    ]
  }
})
```

Which is the same `{ find, replacement }` config shape that you're using. I wonder if it's a Vite bug and you're hitting the same one?

**Comment by benmccann** [comment]
SvelteKit adds aliases, but I don't think it touches the ones you add at all:

https://github.com/sveltejs/kit/blob/1d76d66038647c8a67dbb011cf9c0e231fd086a6/packages/kit/src/core/dev/index.js#L88

So if there's a bug here it's probably in Vite. I see https://github.com/vitejs/vite/issues/3000 linked as one possibility. You can create a plain Vite project to test with `npm init @vitejs/app`
