### ISSUE TITLE
Adapter-static: Add an option to generate pretty HTML/CSS

### ISSUE THREAD

**Issue by georges-g** [sveltejs/kit#10482]
### Describe the problem

Hi,

To the best of my knowledge, there is no option to output "pretty" HTML or CSS.
It makes final code inspection a bit harder.

### Describe the proposed solution

There could a boolean `pretty` option on the adapter.

If it's on, the HTML/CSS is generated with proper linebreaks and indents.

### Alternatives considered

An alternative is to manually run a HTML or CSS prettifier on the output.

### Importance

nice to have

**Comment by dummdidumm** [comment]
Why do you need this? Not sending a terse version or having to format it will slow down response times. If you want to inspect the output manually, you can always copy-paste it into a CSS or HTML file and run Prettier on it.

**Comment by georges-g** [comment]
Yes, I can do it manually, but, if it is automatic, that's more convenient.

About response time, I would turn on the option for inspection, then turn it back off for the final production version. Default could be off of course.

**Comment by Conduitry** [comment]
You can add a `postbuild` script to your `package.json` that runs Prettier on everything - or just add it right to the `build` script, `vite build && prettier --write build`. This seems like a very niche use-case to me, and doesn't need to be its own option.

**Comment by georges-g** [comment]
Well, that's a pretty quick categorization and decision. I wish you would have left the issue opened a longer time to see if more people were interested/concerned. This might not be such a "very niche" use-case.

Using a tool like prettier has its downsides.

**Comment by dummdidumm** [comment]
Why? It does pretty-print the code. That's what it's really good at. We don't want to invent our own notion of what "formatted prettily" means

**Comment by georges-g** [comment]
IMO, when you build software, you are free to define your conventions. It is not about having an absolutely theoretically perfect definition of "prettiness", but about having an option that is understandable, practical, and useful. And I believe it would make sense for a tool whose job is basically to build html/css/js to have a such a kind of formatting option.

The downsides of a tool like prettier are:
- You need to learn the tool, let's say 50 pages of docs
- You need to install the tool, I just checked, that's 8.3M, makes the project a bit heavier

Overall, it is about reducing complexity for the svelte programmer.

That being said, I am not going to argue forever about this and, in the end, we can agree to disagree.
