### ISSUE TITLE
Routing - Rest parameters as breadcrumbs

### ISSUE THREAD

**Issue by annaghi** [sveltejs/kit#10490]
### Describe the bug

I'm experiencing a problem with links derived from rest parameters in my project. The issue is that clicking on the breadcrumb links does not actually navigate to the respective URLs.

I am unsure if this behavior is a limitation with the handling of rest parameters in SvelteKit, a bug, or a mistake in my adaptation of the example.

### Reproduction

The reproduction is a modified version of the official [Advanced routing / Rest parameters](https://learn.svelte.dev/tutorial/rest-params) example:

https://stackblitz.com/github/annaghi/sveltekit-rest-params-breadcrumbs

The original `/src/routes/[...path]/+page.svelte` has this snippet:

```svelte
{#each words.slice(0, depth) as word}
    <p>{word}</p>
{/each}
```

and my only modification is:

```svelte
{#each words.slice(0, depth) as word, index}
    <p><a href={words.slice(0, index + 1).join("/")}>{word}</a></p>
{/each}
```

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 20.76 GB / 31.29 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.1.0/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
  Browsers:
    Brave Browser: 115.1.56.14
    Chrome: 115.0.5790.110
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.0 => 2.1.0 
    @sveltejs/kit: ^1.22.4 => 1.22.4 
    svelte: ^4.1.2 => 4.1.2 
    vite: ^4.4.8 => 4.4.8
```

### Severity

annoyance

**Comment by Conduitry** [comment]
You're using relative paths for the breadcrumb links, so they're pointing at the wrong URLs.

**Comment by annaghi** [comment]
I am sorry for the false report, the annoyance is on me! I thought that I was able to make a minimal example around my issue, but instead I made a typo.

I am going to build up a more realistic reproduction, where the URL changes, but the HTML content does not refresh. I hope that I will find my mistake in the meantime.
