### ISSUE TITLE
Cookies not sent with server side fetch to same origin

### ISSUE THREAD

**Issue by leElvyn** [sveltejs/kit#10494]
### Describe the bug

Hi, i have a simple svelte kit app, and a backend with django. Both are behind the same origin, thanks to a Caddy reverse proxy, pointing `/api/` to django, and `/dash/` to caddy. I made a `handleFetch` function to point requests made to the backend directly to the local django url. However, this code in my `+layout.server.ts` : 
```ts
import type { LayoutServerLoad } from './$types';
import { redirect } from '@sveltejs/kit';

export const load = (async ({ fetch, url, cookies }) => {
    let user: any;
    let r = await fetch("/api/v1/home")
    console.log(cookies.getAll())
    
    // Do stuff with the result
}) satisfies LayoutServerLoad;
```
And here is my `+hooks.server.ts` : 
```ts
import type { HandleFetch } from '@sveltejs/kit';


export const handleFetch = (async ({ request, fetch }) => {
    if (request.url.startsWith(process.env.HOST)) {
        // clone the original request, but change the URL
        let cookies = request.headers.get("cookie")
        console.log("Cookies Are : ")
        console.log(request.headers)
        request = new Request(
            request.url.replace(process.env.HOST, 'http://web:8000/'),
            request,
        );

        request.headers.set('cookie', cookies!);
    }
    return fetch(request);
}) satisfies HandleFetch;
```
However, i do not understant why cookies are never passed during server fetch. Cookies are present on the server, since logging the `cookies.getAll()` : 
```ts
[
   { name: 'sessionid', value: 'stuff' },
   { name: 'csrftoken', value: 'other stuff' }
]
```
But the `console.log(request.headers)` : 
```ts
HeadersList {
   cookies: null,
   [Symbol(headers map)]: Map(0) {},
   [Symbol(headers map sorted)]: null
}
```
The backend also never receives the cookies from server requests. The cookie path is always "`/`"

### Reproduction

I think this is a minimal reproduction of my issue : https://stackblitz.com/edit/sveltejs-kit-template-default-cuzkon?file=src%2Froutes%2F%2Bpage.server.js

### System Info

```Shell
System:
    OS: Linux 6.2 Fedora Linux 38 (Workstation Edition)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.51 GB / 15.39 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    npm: 9.5.1 - /usr/bin/npm
  Browsers:
    Firefox: 113.0.1
```

### Severity

serious, but I can work around it

**Comment by david-plugge** [comment]
Have you checked how `request.url` looks like in `handleFetch`? I assume it doesn't come with the host included so the condition evaluates to false

**Comment by leElvyn** [comment]
It does, the URL looks like this : `http://127.0.0.1:7623/api/v1/home`, and the code is systematically ran when it needs to be

**Comment by david-plugge** [comment]
Ah i see the error. You need to get the cookie header from the _real_ request from the client. `request` in handleFetch is the request that you pass into `fetch` and therefore doesnt include the headers from the client.

```diff
import type { HandleFetch } from '@sveltejs/kit';

-export const handleFetch = (async ({ request, fetch }) => {
+export const handleFetch = (async ({ event, request, fetch }) => {
    if (request.url.startsWith(process.env.HOST)) {
        // clone the original request, but change the URL
-       let cookies = request.headers.get("cookie")
+       let cookies = event.request.headers.get("cookie")
        console.log("Cookies Are : ")
        console.log(request.headers)
        request = new Request(
            request.url.replace(process.env.HOST, 'http://web:8000/'),
            request,
        );

        request.headers.set('cookie', cookies!);
    }
    return fetch(request);
}) satisfies HandleFetch;
```

One thing to keep in mind is that the cookie headers does NOT include cookie set for the current requests. To achieve this you would need to stringify `event.cookies.getAll()` yourself. If you know what exact cookie you want to forward, you should only include those ones.

**Comment by leElvyn** [comment]
Thank you so much !
Works perfectly, this has been driving me crazy.

**Comment by david-plugge** [comment]
I'm glad it works! Feel free to close the issue
