### ISSUE TITLE
Missing documentation on getSession refactoring

### ISSUE THREAD

**Issue by Sciumo** [sveltejs/kit#10509]
### Describe the bug

The "current" documentation from sites ([like auth](https://authjs.dev/reference/sveltekit)) say to use getSession() but that does not work.
```javascript
import type { LayoutServerLoad } from "./$types";

export const load: LayoutServerLoad = async (event) => {
  return {
    session: await event.locals.getSession(),
  };
}
```
[Many people ](https://github.com/orgs/supabase/discussions/13835)are struggling with this issue.
Searching for getSession returns nothing of value.
I can't recommend using Sveltekit for any real business case in this current state of documentation.

### Reproduction

import type { LayoutServerLoad } from "./$types";

export const load: LayoutServerLoad = async (event) => {
  return {
    session: await event.locals.getSession(),
  };
};

### Logs

```Shell
Property 'getSession' does not exist on type 'Locals'.ts(2339)
```

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (128) x64 AMD Ryzen Threadripper PRO 3995WX 64-Cores
    Memory: 193.32 GB / 251.49 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.0.0/bin/yarn
    npm: 9.6.5 - ~/.nvm/versions/node/v20.0.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1 
    @sveltejs/kit: ^1.22.4 => 1.22.4 
    svelte: ^4.1.2 => 4.1.2 
    vite: ^4.4.9 => 4.4.9
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
There's nothing we can do about documentation from other sites that predates SvelteKit 1.0 and hasn't been updated since, nor do I think it warrants an official mention in our docs. Documentation about the removal of 'session' exists in #5883.

**Comment by Sciumo** [comment]
Bug reports is not really documentation. You changed it and you are responsible for assisting people who mistakenly put time into this.
All I asked was to add a note on this. This wasted a great deal of my time.
[Just add a note on the docs](https://kit.svelte.dev/docs/introduction).
I'm not far enough into this not to try htmx at this point.
