### ISSUE TITLE
Race condition in client side navigation

### ISSUE THREAD

**Issue by JakeBeaver** [sveltejs/kit#10512]
### Describe the bug

When quickly navigating "through" a page (using browser buttons), there can be a mismatch between the address bar and the rendered page.

In an edgecase (described in `Slug issue steps` below), quick back navigation causes `$page.params` to match the address, but not the rendered page.

## Critical effect is this: 
User is served a page with broken interactive elements, if these elements are using [slug] params

## Project: 
Create a skeleton project with the following, or clone this repo: https://github.com/JakeBeaver/sveltekit-quick-navigation-reproduction

### Content: 
1. `/+page.svelte`: empty
2. `/load/+page.svelte`: empty
3. `/load/+page.server.js`: `load()` that returns a promise
4.  `/layout.svelte`: navbar, `{$page.route.id}`, slot
5.  `/slug/[slug]/+page.svelte`: `{$page.params.slug}`
 
## Route issue steps:
Start on root route `/`
1. Use navbar to open /load
2. Use navbar to open home
3. Click the browser back button twice quickly

### Result
`/load` gets rendered while address bar shows `/`

![image](https://github.com/sveltejs/kit/assets/11947485/a43d77db-bddb-4ede-a34c-f5954c6d551a)

## Slug issue steps:

Start on root route `/`
1. Use navbar to open /slug/1
2. Use address bar to navigate outside of the sveltekit app, like https://github.com/sveltejs/kit
3. Click the browser back button twice quickly

### Result
`/slug/[slug]` gets rendered but `$page.params.slug` is missing

![image](https://github.com/sveltejs/kit/assets/11947485/799091cc-5575-4bad-9750-dd0a1d4536ed)

### Logs

```Shell
C:\repos\my-app> npm run dev                                                                         

> my-app@0.0.1 dev
> vite dev



  VITE v4.4.9  ready in 1311 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 12.55 GB / 31.74 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.22.4 
    svelte: ^4.0.5 => 4.1.2 
    vite: ^4.4.2 => 4.4.9
```

### Severity

serious, but I can work around it

### Additional Information

With a page refresh, which hopefully is intuitively done by all users, interactive elements come back to life, but it looks very bad.

**Comment by shivan-s** [comment]
Definitely, there are a race condition at play here.

https://github.com/sveltejs/kit/assets/51132467/b9650de1-6820-40e8-9ff2-1a386897db2c

Even tried getting the URL params from a load function and still has the same issue.

```js
// slug/[slug]/+page.js

/** @type {import('./$types').PageLoad} */
export function load({ params }) {
  return {
    slug: params.slug,
  };
}

```
```svelte
<script>
  import { page } from '$app/stores'
  
  /** @type {import('./$types').PageData} */
  export let data;

</script>

<p>slug from load function: {data.slug}</p>

<p>slug from store: {$page.params.slug}</p>

```

Would be very interested in what others will have to say.

Uploading Screen Recording 2023-08-12 at 10.01.14 AM.mov…

**Comment by nhunzaker** [comment]
I may be seeing a similar thing where the back button is pressed before the page fully hydrates:

1. Visit your app
2. Navigate to any secondary page
3. Reload the app
4. _before the app finishes loading, press the back button_

For me, this is happening when the `popstate` action runs before the `initialize` step executes, which is responsible for establishing the current history state:

https://github.com/sveltejs/kit/blob/68311d632eee69982ce02c39fcf4044a6158c1cd/packages/kit/src/runtime/client/client.js#L275-L280

Since `current.url.href` is `null`, calling `split` results in an exception:

https://github.com/sveltejs/kit/blob/68311d632eee69982ce02c39fcf4044a6158c1cd/packages/kit/src/runtime/client/client.js#L1646-L1652

When this happens, the navigation code following this scroll reset behavior never executes:

https://github.com/sveltejs/kit/blob/68311d632eee69982ce02c39fcf4044a6158c1cd/packages/kit/src/runtime/client/client.js#L1656-L1670

**Comment by JakeBeaver** [comment]
The bigger issue, of navigating from outside, is not influenced by the above PR

When quickly navigating back from a different site, the second navigation doesn't even trigger an http request, even before the scripts. 

I was able to correct this effect locally by adding a location.href check into the rendered html

https://github.com/JakeBeaver/kit/blob/c1477090331570414d4104788347470fee18a2a4/packages/kit/src/runtime/server/page/render.js#L359

While this is most definitelly not the fix, it proves that browser navigation during first hydration(?) is ignored completely. 

What could interfere with browser back button before `client/start.js` runs?
