### ISSUE TITLE
`Unfinished hook action(s) on exit: (vite-plugin-sveltekit-compile) writeBundle` while using `npm` and introducing classes in project

### ISSUE THREAD

**Issue by developer-ramen** [sveltejs/kit#10513]
### Describe the bug

This happened while debugging a commit that introduced JS classes to the project. The error only happened in build/production (`vite build`) and worked completely fine in local dev (`vite dev`). Some other issues like #3563 had the same-ish outputs and conditions but didn't help very much.
I have tried upgrading versions but the error remains unchanged.

### Reproduction

I couldn't figure out how to reproduce this issue on a barebones SvelteKit project.
Just cloning and then running `npm i` and `npm run build` should be fine.
[developer-ramen/just-games](https://github.com/developer-ramen/just-games)

### Logs

```Shell
transforming (12) node_modules/esm-env/prod-browser.jsUnexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
*loading and transforming svelte/internal files*
(vite:optimized-deps-build) load "/home/ramendev/projects/just-games/node_modules/.vite/deps_build-e2ef5bc8/svelte.js"
Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite-plugin-sveltekit-compile) writeBundle
✓ built in 2.73s
error during build:
Error: Unexpected early exit. This happens when Promises returned by plugins cannot resolve. Unfinished hook action(s) on exit:
(vite-plugin-sveltekit-compile) writeBundle
    at process.handleBeforeExit (file:///home/ramendev/projects/just-games/node_modules/rollup/dist/es/shared/node-entry.js:25777:28)
    at Object.onceWrapper (node:events:629:26)
    at process.emit (node:events:514:28)
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 4.84 GB / 7.67 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.17.0 - /usr/local/bin/node
    npm: 9.6.7 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-netlify: ^2.0.8 => 2.0.8 
    @sveltejs/kit: ^1.20.4 => 1.22.4 
    svelte: ^4.0.5 => 4.1.2 
    vite: ^4.4.2 => 4.4.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Cannot deploy to production, local dev works fine
Might also need to be posted to Vite as an issue

**Comment by benmccann** [comment]
There's also lots of issues in the logs like:
```
Unfinished hook action(s) on exit:
(commonjs--resolver) resolveId
(vite:build-import-analysis) transform
```

I doubt this is related to classes. I think it's more likely that you have a circular dependency somewhere or something. And in fact I see you even have had issues related to circular dependencies in the project already: https://github.com/developer-ramen/just-games/commit/4be0592f302b458d2bfcbe49dbe8ca5a875c455f.

This project's too complex to debug. We'd need a minimal reproduction. And I expect that this should really be filed in the Vite issue tracker rather than this project's: https://github.com/sveltejs/kit#bug-reporting

**Comment by developer-ramen** [comment]
Sorry for bothering you guys. The issue's been solved by removing the `optimizeDeps` configuration option.
