### ISSUE TITLE
Getting "Not Found" when wrapping styles in {#if} blocks

### ISSUE THREAD

**Issue by hAbuMustafa** [sveltejs/kit#10517]
### Describe the bug

I made a component in SvelteKit that will have different styles based on the data provided.
Part of the conditional styles are some background images that should be one of either two:

The `style` tag looks like this:

```svelte
{#if true}
  <style>
  ...
  .branch {
      background-image: url('$lib/assets/ezzeddin-logo-minified.png');
  }
  ...
  </style>
{/if}
```

### Reproduction

With this `{#if}` block I get the following error that the image doesn't exist, because somehow the compiler takes in the image url string *as is* and doesn't link to the actual image:
```console
Error: Not found: /$lib/assets/ezzeddin-logo-minified.png
    at resolve (C:/Users/hosam/Desktop/Work/Dev/recruitement-interface/node_modules/@sveltejs/kit/src/runtime/server/respond.js:430:13)
    at resolve (C:/Users/hosam/Desktop/Work/Dev/recruitement-interface/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at Object.#options.hooks.handle (C:/Users/hosam/Desktop/Work/Dev/recruitement-interface/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (C:/Users/hosam/Desktop/Work/Dev/recruitement-interface/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

When I remove the `{#if}` block everything works fine, but some styles get applied that I don't want to.
And I don't want to separate the logic into two components because otherwise I'll end up with so many duplicate code.

### Logs

```Shell
ezzeddin-logo-minified.png:1 
        
        
        GET http://192.168.1.8:5173/$lib/assets/ezzeddin-logo-minified.png 404 (Not Found)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 8.30 GB / 15.95 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.24.3 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
`<style>` blocks that aren't at the top level aren't processed by Svelte at all (meaning they won't be scoped). They're treated just as any other element would be, and don't have asset handling run on them either. Even if we ran asset handling and URL rewriting on this code, it would still result in global styles that affect every matching element on the whole page, not just this instance of this component.

One of the proper ways of dealing with this is to have a class conditionally added on a top-level element in the component, and then to style according to the presence of that class in a single top-level (scoped) `<style>` block.
