### ISSUE TITLE
Automatically added comments in JSON files cause errors in other tooling down the line.

### ISSUE THREAD

**Issue by mythril** [sveltejs/kit#10525]
### Describe the bug

The [JSON spec](https://www.json.org/json-en.html) does not include comments, and some other tooling breaks [because of these comments](https://github.com/sveltejs/kit/blob/118a3a62671d7bd60365b22ebd9dfbd746d91b4f/packages/create-svelte/shared/%2Bcheckjs/jsconfig.json#L13).

### Reproduction

Here's a tool that breaks parsing the default `jsconfig.json`:
```
$ npx apply --no-ssh rossyman/svelte-add-jest
```

### Logs

```Shell
[ info ]  Applying preset rossyman/svelte-add-jest.
[ question ]  Enable Jest DOM support? (Y/n) · true
[ question ]  Enable TypeScript support? (y/N) · true
[ question ]  Generate example test file? (Y/n) · true
[ question ]  Enable JSDOM environment by default? (Y/n) · false
[ info ]  Adding required dependencies
[ info ]  Initializing Jest config
[ info ]  Initializing Babel config
[ info ]  Enabling Jest DOM Support
[ info ]  Modifying TypeScript config for project
[ error ]  Could not read the JSON file.
SyntaxError: Unexpected token / in JSON at position 382
    at JSON.parse (<anonymous>)
    at EditJsonHandler.getContent (/home/user/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Handlers/EditJsonHandler.js:62:50)
    at EditJsonHandler.handle (/home/user/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Handlers/EditJsonHandler.js:28:42)
    at PresetApplier.performActions (/home/user/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Applier/PresetApplier.js:78:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PresetApplier.run (/home/user/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/Applier/PresetApplier.js:34:9)
    at async CommandLineInterface.apply (/home/user/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/IO/CommandLineInterface.js:57:16)
    at async CommandLineInterface.run (/home/user/.npm/_npx/1af5c665402bf7e1/node_modules/apply/dist/IO/CommandLineInterface.js:54:16)
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 49.77 GB / 62.44 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.0 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
  Browsers:
    Brave Browser: 115.1.56.20
    Chromium: 115.0.5790.110
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-static: ^2.0.2 => 2.0.3 
    @sveltejs/kit: ^1.20.4 => 1.22.4 
    svelte: ^4.0.0 => 4.1.2 
    vite: ^4.3.6 => 4.4.8
```

### Severity

annoyance

### Additional Information

Marked as annoyance, but it could be fairly opaque to someone who doesn't already know about JSON comments and what files are involved in the offense.

**Comment by mythril** [comment]
Only reason I didn't offer a pull request is that I have no idea what would be a good way to preserve the info in the comments in an accessible form for this project.

**Comment by gtm-nayan** [comment]
Typescript along with a few other tools don't completely follow the JSON spec and allow comments in their configuration files. Even their default tsconfig on init is filled with comments so the onus is on the tooling to support those.

FWIW those comments you point to are in the template so you can just remove them in your repo without needing any change here.

**Comment by Conduitry** [comment]
I agree with @gtm-nayan on this one. TypeScript and other big tools have already basically decided that their JSON files are actually JSON+comments, regardless of how polite of a thing that was to do. At this point, it's the responsibility tools like `rossyman/svelte-add-jest` to support comments in the JSON it's trying to parse. If you want to use tools that don't support comments, you'll just need to edit your JSON files before.

**Comment by Conduitry** [comment]
I see in https://github.com/rossyman/svelte-add-jest/issues/29 that that project has declared parsing JSON-C a won't-fix, and they explicitly mention it in their readme.

**Comment by ghostdevv** [comment]
`tsconfig.json` doesn't follow the JSON spec on more than just comments unfortunately, it also has stuff like trailing commas. You could try convincing their dependency to use something like [tsconfck](https://www.npmjs.com/package/tsconfck)

**Comment by ghostdevv** [comment]
I'll close this for now :pray:
