### ISSUE TITLE
Warn when reserved filenames exist but have neglected the + prefix

### ISSUE THREAD

**Issue by theetrain** [sveltejs/kit#10528]
### Describe the problem

Sometimes, users will encounter unexplainable behaviours (or lack thereof) when seemingly adding the correct files, but those files were misspelled or neglected the `+` prefix.

Common mistakes include:

- `hook.server.js`, `hook.server.ts`, `+hooks.server.js`, `+hooks.server.ts`
- `page.svelte`
- `page.js`, `page.ts`, `page.server.js`, `page.server.ts`
- `server.js`, `server.ts`

### Describe the proposed solution

During dev mode or project build, log a warning if any of the above misspellings are found in the codebase.

### Alternatives considered

Inform users to read the docs more closely. 

### Importance

nice to have

**Comment by 205g0** [comment]
Would love to have this for REST resources, e.g., my schema has users, posts and comments and i want to get a warning if a folder is not compliant to the schema's entities + a few other custom ones, e.g. `me` or `[lang]` I could set somewhere (as an array)

Could I add such a functionality myself or is too low level in the framework?

**Comment by theetrain** [comment]
@205g0 Assuming you have an API schema and you want your folder structure to comply via build-time validations, maybe an adaptation of https://github.com/SkeLLLa/fastify-oas for SvelteKit can be made.

**Comment by 205g0** [comment]
Maybe. I just want that my app breaks as much as possible if my SQL schema (=Drizzle TS schema) changes. And I want to know ofc where it broke. I achieved this already with almost everything which is entity- and/or route- related, e.g.. depends, goto, fetch, action, href, etc. This is the beauty with TS, you can easily change a table name with Drizzle, let TS refactor and where it can't, it will break at least.

If the routes/folder names break too (or emit an error on the console), you would have a complete "picture" where to refactor yourself and can do complex refactors in minutes you couldn't do with any other framework.

Atm, I just check against an enum type of all SQL entities, so no hierarchy or relations are checked but this is already a huge win. To get latter working, I guess you need a deeper integration with something like Drizzle which could expose the relations.

**Comment by 205g0** [comment]
With Drizzle you just need following to get all entities as enum type which you can use against all schema-related matters:

```ts
import type * as schema from '$lib/schema'

export type TableName = keyof typeof schema
// type TableName = "users" | "posts" | "comments" 
```
