### ISSUE TITLE
Migrate off purify-css

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#10536]
### Describe the bug

`purify-css` has not been updated in 6 years and is causing security warnings in the AMP example

### Reproduction

https://github.com/sveltejs/kit/blob/e133aba479fa9ba0e7f9e71512f5f937f0247e2c/packages/kit/test/apps/amp/src/hooks.server.js#L25

### System Info

```Shell
`master`
```

### Severity

annoyance

### Additional Information

Some alternatives:
- https://github.com/FullHuman/purgecss
- https://github.com/leeoniya/dropcss

**Comment by ghostdevv** [comment]
going to look into it now :pray:

**Comment by ghostdevv** [comment]
So looking into it, I'm not sure why it's included in the tests when it's not included in the docs. #4710 has a comment about why you might need it:

> One thing we lose is the ability to exclude CSS from components that are imported but not rendered for a given page. Given AMP's wholly arbitrary CSS size limit, that can be a problem. This can be solved (at least for prerendered pages, where it doesn't matter how expensive this sort of processing is) with something like [purifycss/purifycss](https://github.com/purifycss/purifycss):

What is the preferred solution here?
- Migrate off purify css
- Migrate off purify css and add a note about this to the docs
- Remove it altogether

Will raise a PR for whatever is decided - tagging @Rich-Harris here too as he originally added this :pray:

**Comment by ghostdevv** [comment]
> Some alternatives:

[leeoniya/dropcss](https://github.com/leeoniya/dropcss):
	- No types
	- CJS build only
	
[FullHuman/purgecss](https://github.com/FullHuman/purgecss):
	- Uses Node Libs
	- Big dependancies

**Comment by benmccann** [comment]
I think using dropcss might be the best solution then as I'd prefer not to pull in a lot of dependencies and it'd be nice to demonstrate usage for our users. I filed an issue there requesting some types, but in the meantime we can just do `// @ts-ignore` if needed

If that doesn't work for some reason then my second choice would be to remove it and add a comment like:
```
// you could invoke a library like purify-css/purgecss/dropcss here to exclude CSS from components that are imported, but not rendered
```

**Comment by ghostdevv** [comment]
> I filed an issue there requesting some types, but in the meantime we can just do // @ts-ignore if needed

Ty! I ended up writing types for the tests in #10546 so submitted a pr to dropcss to add those types in - hopefully they take a look at it soon :crossed_fingers:
