### ISSUE TITLE
Text selection is kept when switching between svelte routers - should be resetting?

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#1054]
Text selection is kept when switching between svelte routers(If it is in `$layout.svelte`). I don't know if this shouldn't be cleared by the router by default either?

The `router.js` file just executes `document.body.focus();` every time the router is rebooted:
https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L245
And for the scroll position (conditionally):
https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L254
Should text selection be treated the same?

`document.body.focus();` and `scrollTo(0, 0);` is to simulate a full website refresh.
Should `router.js` be run with a line that resets the text selection:
```javascript
window.getSelection().empty();
```

I emphasize: This is NOT needed directly by me, but I noticed this behavior during experiments with sveltekit.

**Comment by Rich-Harris** [comment]
This is intentional — the thinking is that it's better for accessibility if client-side navigation has the same behaviour as a full page refresh. We may make this behaviour customisable in future

**Comment by Rich-Harris** [comment]
Hang on, I totally misunderstood. Yes, we should be resetting the selection — good catch, thanks
