### ISSUE TITLE
Prettier works on the CLI but not using VSCode / Neovim

### ISSUE THREAD

**Issue by wojtekgalaj** [sveltejs/kit#10548]
### Describe the bug

On a project created with `npm create svelte` editor plugins for prettier do not work. The problem gets resolved when bumping prettier and prettier plugin svelte to version 3:

```
		"prettier": "^3.0.1",
		"prettier-plugin-svelte": "^3.0.3",
```

### Reproduction

```
npm create svelte
npm i
```

Open any of the svelte files, move code around, save.

Expected:
Prettier reformats the code on save.

Actual:
Code is not reformatted.

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.92 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    pnpm: 8.6.9 - ~/.local/npm-global/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 114.0.1823.67
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.5.0 => 1.22.5
    svelte: ^3.54.0 => 3.59.2
    vite: ^4.3.0 => 4.4.9
```

### Severity

serious, but I can work around it

### Additional Information

Again, bumping prettier and the svelte plugin to v3 fixes the problem.

**Comment by ghostdevv** [comment]
This belongs on [language tools](https://github.com/sveltejs/language-tools), can you reopen it there? I can't transfer it myself unfortunately
