### ISSUE TITLE
Pass an optional object to `redirect()` (flash messages)

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#10545]
### Describe the problem

For some actions, I want to redirect the user and show him additional messages, after he got redirected to the new page.

### Describe the proposed solution

```ts
throw redirect(303, '/dashboard', { message: '<custom message>' });
```

And then you can access it, for example with the $page store:

```svelte
<script>
    import { page } from '$app/stores';

    const { message } = $page.previous; // or $page.redirect
</script>

{#if message}
    <p class="success">{message}</p>
{/if}
```

### Alternatives considered

- GET params (which isn't a good DX imo)
- third party package like https://github.com/ciscoheat/sveltekit-flash-message

### Importance

would make my life easier

**Comment by s3812497** [comment]
I'm not really sure if this is something we want to implement. If CSR was disabled, the only way we could pass data from server to client would be as you have listed:

* URL Search Params
* https://github.com/ciscoheat/sveltekit-flash-message (which uses cookies)

Both of these can already be solved by the user, so you could create your own helper function to easily send and digest this data.
