### ISSUE TITLE
Rendering of yaml files is wrong in sveltekit doc

### ISSUE THREAD

**Issue by abbychau** [sveltejs/kit#10559]
### Describe the bug

rendering of yaml files is wrong in sveltekit doc:

example:
![image](https://github.com/sveltejs/kit/assets/350283/5a620eb9-43b5-493a-a06e-7a8951232408)

copying indentations are wrong too.

### Reproduction

go to 
https://kit.svelte.dev/docs/adapter-static

### System Info

```Shell
N/A
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Closing this since it's no longer an issue on the new Svelte site
- https://svelte.dev/docs/kit/adapter-static#GitHub-Pages
