### ISSUE TITLE
Anchor with #hash not showing :target CSS after history.back()

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#10550]
### Describe the bug

1. Goto `/#target`
2. Goto `/temp`
3. Return to the previous page
4. URL is `/#target` and the `#target:target` styles are not shown.

In this state, clicking `<a href="#target">` should show `#target:target` styles, but it does not.

### Reproduction

https://stackblitz.com/edit/github-ymws75?file=src%2Froutes%2F%2Bpage.svelte

### System Info

- Chrome 버전 115.0.5790.170(공식 빌드) (arm64)
- Firefox 116.0.2 (64-비트)

```Shell
System:
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 16.20.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.4.2 - /usr/local/bin/npm
  pnpm: 8.6.10 - /usr/local/bin/pnpm
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
  @sveltejs/kit: ^1.20.4 => 1.22.5 
  svelte: ^4.0.5 => 4.2.0 
  vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

### Additional Information

1. Using `<a href="#target" data-sveltekit-reload>` fixes the `:target` CSS issue.
2. Possibly related to https://github.com/sveltejs/kit/issues/3770

**Comment by whataboutpereira** [comment]
This is what I'm using to work around it without reloading the page.

```
const navigate = (navigation?: Navigation) => {
	if (navigation) {
		if (navigation.to?.url.hash && navigation.to.url.hash !== '#') {
			// history.replaceState() needed by Firefox to navigate back.
			const state = history.state;
			location.replace(navigation.to.url);
			history.replaceState(state, '', location.href);
		}
	}
};

afterNavigate(navigate);
```

**Comment by s3812497** [comment]
This seems to be a limitation of client-side routing / rendering. The browser navigates to the new URL but cannot find the element with the corresponding id as it has not been rendered through javascript yet. You can observe a similar behaviour when navigating from `/#one` to `/` as mentioned in https://github.com/sveltejs/kit/issues/10524 . The native browser behaviour would be a full page reload when navigating from a hash to a non-hash URL.

I'm not sure what the solution here is. `history.replaceState` and `history.pushState` have no effect. `location.replace(navigation.to.url)` mentioned in https://github.com/sveltejs/kit/issues/10550#issuecomment-1681789994 is a notable hack as it works without reloading, but we can't stop it from emitting a `popstate` event (which already occurs once when we hit the back button). I've looked at next.js and nuxt.js to see if they have a solution but the same issue occurs.

Adding `data-sveltekit-reload` to the `<body>` and enabling SSR ensures the most consistent behaviour when using `:target` styles.

**Comment by hyunbinseo** [comment]
- https://github.com/sveltejs/kit/issues/9374
- https://github.com/sveltejs/kit/pull/10202

Now that `$page.url.hash` is fixed and reactive, it might be best to toggle class-names.

```svelte
<script lang="ts">
  import { page } from '$app/stores';
</script>

<p id="secret-code" class:hidden={$page.url.hash !== '#secret-code'} class="hidden target:block">
  Hidden Message Block
</p>

<a href="#secret-code">Show Message</a>
```

Not that this REQUIRES JavaScript to work.

`:target` CSS could be provided as a fallback as shown above.

**Comment by hyunbinseo** [comment]
This workaround does not work. Use with caution:

- They do show the `:target` styling,
- But it breaks SvelteKit navigation.

```svelte
<script>
  import { page } from '$app/stores';
  import { tick } from 'svelte';

  $effect(() => {
    // Don't
    if ($page.url.hash) window.location.hash = $page.url.hash;

    // Don't
    if ($page.url.hash) {
      tick().then(() => {
        const anchor = document.createElement('a');
        anchor.href = $page.url.hash;
        anchor.setAttribute('data-sveltekit-reload', '');
        document.body.appendChild(anchor);
        anchor.click();
        document.body.removeChild(anchor);
      });
    }
  });
</script>
```

1. `/`
2. (click an anchor) → `/a#hash`
3. (press browser back) → `/`
4. (press browser forward)
   1. browser URL does change to `/a#hash` as expected
   2. but page stays the same (no client-side navigation)
