### ISSUE TITLE
404 and layout load fetch to prerendered endpoint returns internal server error

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#10556]
### Describe the bug

~Both kit.svelte.dev and svelte.dev are not showing the 404 page correctly.
e.g., https://kit.svelte.dev/abc CC: PuruVJ~

EDIT: See https://github.com/sveltejs/kit/issues/10556#issuecomment-1678593220

### Reproduction

https://github.com/gtm-nayan/kit-sandbox/tree/prerendered-endpoint-repro

1. Build the site.
2. Run `pnpm preview`
3. Navigate to a missing route e.g., `/abc`.

Expected: The `+error.svelte` page is rendered with a `404` status.

Actual: The fallback `error.html` page is used and the status is `500`.

### System Info

```Shell
n/a
```

### Severity

annoyance

**Comment by s3812497** [comment]
> However, I also found #8751, which was not the issue I was looking for. Is this different than that?

I think #8751 strictly occurs for client-side navigation while this one is happening during SSR.

**Comment by gtm-nayan** [comment]
Doesn't seem specific to the site, it's choking on the fetch('/nav.json') with an `Internal Server Error` when it should probably just be serving the prerendered file.

Minimal repro here:
https://github.com/gtm-nayan/kit-sandbox/tree/prerendered-endpoint-repro

**Comment by gtm-nayan** [comment]
I think there should be a check for prerendered routes somewhere around here

https://github.com/sveltejs/kit/blob/245cdc59ac9e1ffe7e14197889b18fcdbad93950/packages/kit/src/runtime/server/fetch.js#L81-L98

but that list of prerendered stuff is only generated at the adapter level and the internal server doesn't know about them currently.
