### ISSUE TITLE
site: inline code overflows on mobile

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#10566]
### Describe the bug

Lengthy inline code in different parts of the docs are cut-off on small screen sizes.
e.g., `transformPageChunk(opts: { html: string, done: boolean }): [MaybePromise](https://kit.svelte.dev/docs/types#private-types-maybepromise)<string | undefined>`

### Reproduction

https://kit.svelte.dev/docs/hooks#server-hooks-handle
![inline code cut off in kit docs site](https://github.com/sveltejs/kit/assets/54401897/ddd35071-4bdf-40b1-bebf-145324717a57)

### System Info

```Shell
n/a
```

### Severity

annoyance

**Comment by VKR981** [comment]
Can I fix this?

**Comment by s3812497** [comment]
> Can I fix this?

Absolutely! Feel free to open a PR for it.

**Comment by eltigerchino** [comment]
Seems that this was fixed (not sure when) and the code now wraps to the next line .
