### ISSUE TITLE
File path thrown in console.error() is not valid if load in a group crashes

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#10573]
### Describe the bug

The path of the file is incorrectly cut of in the console:
<img width="819" alt="Screenshot 2023-08-17 at 12 21 18" src="https://github.com/sveltejs/kit/assets/48158184/0665d23b-8bf3-4e42-b7bd-240b08357acc">

### Reproduction

Link to reproduction: https://stackblitz.com/edit/sveltejs-kit-template-default-upbgmq?file=src%2Froutes%2Fstyles.css

1. Click on "crash"
2. Open up the log in console

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 116.45 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    npm: 9.1.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 115.0.5790.170
    Firefox: 112.0.2
    Safari: 16.5.1
  npmPackages:
    @sveltejs/adapter-vercel: ^3.0.3 => 3.0.3 
    @sveltejs/kit: ^1.22.4 => 1.22.4 
    vite: ^4.4.9 => 4.4.9
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Upstream report: https://crbug.com/1473926

**Comment by dummdidumm** [comment]
Upstream issue was closed, so I assume this is fixed
