### ISSUE TITLE
Elements with a global transition in an {:else if} block are not being removed from the DOM on page URL change 

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/kit#10580]
### Describe the bug

We encountered a hard-to reproduce issue combining multiple factors that resulted in elements not being removed from the DOM after a transition ends:

 - The element needs to be the child of another element in an `{:else if}` (in the main branch of an `{#if}`, everything works correctly)
 - The element needs to have a global transition
 - Both the transition and the if need to be triggered on page change

See the reproduction below.

## Expected

After the transition ends, we end up on the new page and nothing from the old page remains in the DOM.

## Actual

After the transition ends, the element is not removed from the DOM, and hides the new page's contents.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-a4fqh3?file=package.json

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 631.11 MB / 15.36 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.20.2 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.4 - /usr/bin/npm
    pnpm: 8.6.3 - /usr/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.96
  npmPackages:
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1 
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^1.22.3 => 1.22.3 
    svelte: ^3.59.2 => 3.59.2 
    vite: ^4.4.4 => 4.4.4
```

### Severity

serious, but I can work around it

### Additional Information

Current workaround is to use two `{#if}` instead of an `{:else if}`

**Comment by lovasoa** [comment]
Here is a much smaller repro that works with svelte 4:

```svelte
<script lang="ts">
  import Parent from './Parent.svelte'
	import { page } from '$app/stores';
	import { fade } from 'svelte/transition';
</script>

<a href="?x">Click here</a>

{#if false}
	whatever
{:else if $page.url.searchParams.has('x')}
	<p transition:fade|global>
		<a href="/about">Go to /about</a>
	</p>
{/if}
```

**Comment by ghostdevv** [comment]
It's an unfortunate side effect of using `|global`, there isn't anything we can do here iirc so will close this for now :pray: I think this is the best issue to track for better transition controls: https://github.com/sveltejs/svelte/issues/8850

**Comment by lovasoa** [comment]
@ghostdevv Is there something that makes it impossible to compile 

```svelte
{#if x} a {:else if y} b {/if}
```

the same way as

```svelte
{#if x} a {/if}
{#if !x && y} b {/if}
``` 

which does work ?

**Comment by lovasoa** [comment]
https://github.com/sveltejs/svelte/issues/8850 seems to be about something else entirely; if the bug with global transitions is here to stay, maybe it should be documented very prominently in the documentation ?
