### ISSUE TITLE
+layout.server.ts is inconsistant host

### ISSUE THREAD

**Issue by ollyde** [sveltejs/kit#10586]
### Describe the bug

```
import type { LayoutServerLoad } from "./$types";

export const load: LayoutServerLoad = async ({ fetch, cookies, url }) => {
  return {
    host: url.href,
  };
};
```

---

```
<script lang="ts">
  import "../app.postcss";
  import "./styles.css";
  import ModalQueue from "$lib/components/ModalQueue.svelte";
  import { onMount } from "svelte";
  import { get } from "svelte/store";

  export let data: { host: string }

  onMount(() => {
    // Seems very broken, does not work on root :-/ 3 hours debugging
    console.log(`Client Hook Info: ${JSON.stringify(data)}`);
  });
</script>

<div class="app">
  <main>
    <slot />
  </main>
</div>
```

### Reproduction

Above

### Logs

```Shell
We need to load an environmental var for both server and client for server url address. This url needs to be interchangeably and user switchable/savable.

The issue is, we use the domain to determine the original url, and for all instances except development this domain is showing as "http://sveltekit-prerender/" for the root only domain.

Anything that is not root works as expected; showing the url.
```

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /opt/homebrew/bin/node
    npm: 9.6.7 - /opt/homebrew/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.5.1
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
If you need to control the origin used in prerendered pages, use [`kit.prerender.origin`](https://kit.svelte.dev/docs/configuration#prerender)

If you need this to be dynamic for different on a given route, you can't use prerendering for that route and need to disabled it - https://kit.svelte.dev/docs/page-options#prerender

**Comment by ollyde** [comment]
@Conduitry hey, thanks for closing so fast but this doesn't seem like expected behavior.

It should be consistent, if I visit a url it should show what that url is instead of hiding it and warping the result. I spent a few debugging for something that feels like a core platform issue.

To be honest I'm not too happy that SvelteKit is doing funky stuff like this; makes me want to leave the platform.

**Comment by ollyde** [comment]
@Conduitry for example, all these values for root say "http://sveltekit-prerender/" which is completely incorrect, they do not reflect real host values. This issue should be reopened..

When visiting 'mydomain.com'

```
export const load: LayoutServerLoad = async ({ cookies, url, fetch, request }) => {
  return {
    host: JSON.stringify(url), // Incorrect: http://sveltekit-prerender/
    fetch: JSON.stringify(fetch),  // Incorrect: http://sveltekit-prerender/
    request: request.url,  // Incorrect: http://sveltekit-prerender/
  };
};
```

When visiting 'mydomain.com/some-url'
```

export const load: LayoutServerLoad = async ({ cookies, url, fetch, request }) => {
  return {
    host: JSON.stringify(url), // Correct
    fetch: JSON.stringify(fetch) // Correct
    request: request.url // Correct
  };
};
```

**Comment by ollyde** [comment]
@Conduitry and based of the link you sent, which by the way is almost useless. It doesn't explain anything or how to fix this. This is a bug.

<img width="759" alt="Screenshot 2023-08-19 at 23 41 36" src="https://github.com/sveltejs/kit/assets/6940726/d4ea6081-8b3c-48f5-b887-071dcb936e73">

**Comment by ollyde** [comment]
@Conduitry also why does this 'request' work for other urls except root, that makes no sense? Since they are SSR, seems like a core platform bug

**Comment by dummdidumm** [comment]
Are you prerendering your root route? Because if yes, then there's no way how SvelteKit can magically know where you're deplying to, and you need to use said prerendering setting. If no, please provide a reproduction.

**Comment by ollyde** [comment]
@dummdidumm yes I'm per-rendering all roots. I've noticed that ```+layout.server.ts``` is not called for root but all other pre-rendered routes which is incorrect.

**Comment by dummdidumm** [comment]
Please provide a reproduction then.

**Comment by ollyde** [comment]
@dummdidumm if you create a base project and use +layout.server.ts with +layout.page.ts you can see the bug.

on "/" it's not called. On other roots it is.

With hooks it doesn't show the correct url. For other SSR routes it does.

I can create a whole project for you if yo want?

**Comment by dummdidumm** [comment]
Yes, please share a full repository of Stackblitz link. I think we're talking past each other and having a full code example where you say what you expect to work that doesn't it's easier

**Comment by ollyde** [comment]
@dummdidumm btw it seems to only bug when hosted (built and deployed) using the node-adaptor

Make a fresh project

```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev
```

then

add +layout.server.ts

```
/** @type {import('./$types').PageServerData} */
export async function load({url}) {

    console.log('load layout', url.host);

    return {
      empty: ''
    };
  }
```

**Comment by ollyde** [comment]
@dummdidumm this only fires for anything that isn't root.

**Comment by dummdidumm** [comment]
Again, please provide a reproduction linking to a Stackblitz or Github project. These scattered infos and manual steps that gloss over details are all prone to misunderstanding.

**Comment by ollyde** [comment]
Sure, here is a project that emulates the broken functionality, you will need to look at server logs to validate it, not sure how to do that on StackBlitz, I'm hosting with K8.

https://github.com/ollyde/example-sveltekit-root-page-load-broken

<img width="1681" alt="Screenshot 2023-08-21 at 12 12 49" src="https://github.com/sveltejs/kit/assets/6940726/f2f86d1b-4435-4b3c-87c6-c66c32f1cf6f">
