### ISSUE TITLE
Allow us to use folder name as root page file

### ISSUE THREAD

**Issue by ollyde** [sveltejs/kit#10598]
### Describe the problem

It's nice that we have a consistent way to load +page.layout but..

Sometimes it's just painful, for example, my +page is under login/+page.svelte

<img width="462" alt="Screenshot 2023-08-22 at 13 37 59" src="https://github.com/sveltejs/kit/assets/6940726/66eadac1-2862-45dd-9b16-d84d29f160d5">

### Describe the proposed solution

Allow us to use same name page files

login/+login.svelte

### Importance

would make my life easier

**Comment by ghostdevv** [comment]
We don't want to readd this behaviour in kit, if you wanna read more about why we changed to `+page`, `+layout` etc see [this discussion](https://github.com/sveltejs/kit/discussions/5748)

**Comment by ollyde** [comment]
@ghostdevv  there’s a huge update, can’t rely find anything about this subject; but can you explain why this isn’t a good idea? I mean other file based routers have been doing this for a long time 🥲

**Comment by ghostdevv** [comment]
@ollyde it's definitely great to discuss it, but this specifically has been discussed to it's limits. A lot of it took place in that thread but even since there has been a steady stream of issues/discord threads/gh discussions about it all saying the same - which is why I closed the issue 🙏

**Comment by ollyde** [comment]
@ghostdevv i understand and I reopened it; I literally can’t use SvelteKit and I see others complaining about the same issue.. what happened to this product; feels like it’s getting worse.
