### ISSUE TITLE
Only lint changed files

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1059]
The [pre-push hook](https://github.com/sveltejs/kit/blob/master/.githooks/pre-push) would be nicer if it somehow only linted changed files. I have no idea how to do that

(same goes for checking, though that seems much harder given you also need to typecheck importers of changed files)

**Comment by Conduitry** [comment]
https://www.git-scm.com/docs/githooks#_pre_push The pre-push hook is passed a few things on the command line, including the old and new hashes. Although presumably this would only be helpful on the second and later pushes for a branch. I'm not entirely sure what it makes the most sense to compare with on the first push. `git merge-base HEAD master`? We could then use `git diff --name-only xxx..yyy` to get the files that have changed in that range. We'd then be in the position of figuring out what to pass to what `lint` script, and that part I haven't thought about at all.

**Comment by n4bb12** [comment]
I'd recommend https://github.com/okonet/lint-staged.
It also has a convenient init command https://github.com/okonet/lint-staged#installation-and-setup that always worked for me.

**Comment by rubengmurray** [comment]
> The [pre-push hook](https://github.com/sveltejs/kit/blob/master/.githooks/pre-push) would be nicer if it somehow only linted changed files. I have no idea how to do that
> 
> (same goes for checking, though that seems much harder given you also need to typecheck importers of changed files)

I've only just written this (not heavily tested), but providing you have `husky`, `eslint` + other TS dependencies configured, putting this in .husky/pre-push has done the job for me over the last couple of days:

`npx eslint $(git diff --name-only origin/$(git rev-parse --abbrev-ref HEAD)..$(git rev-parse --abbrev-ref) HEAD | grep -E "(.ts$)")`

**Comment by Rich-Harris** [comment]
Going to close this, as it hasn't been a problem in practice, and simpler configs are better
