### ISSUE TITLE
`iframe` inserted into "dynamic" table header

### ISSUE THREAD

**Issue by hAbuMustafa** [sveltejs/kit#10597]
### Describe the bug

I made a dynamic table which columns are displayed upon user preference, using stores.
When the user choses to display the last column a weird `<iframe>` is inserted in the `<thead>` row elements before the newly displayed `<th>` element. And this, of course, breaks the table flow.

### Reproduction

Make a table like the following tree:
```svelte
<script>
  import {showColumnB} from '$lib/stores/preferences';
</script>

<table>
  <thead>
    <tr>
      <th>A</th>
      {#if $showColumnB}
        <th>B</th>
      {/if}
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>A</td>
        {#if $showColumnB}
          <td>B</td>
        {/if}
    </tr>
  </tbody>
</table>
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 436.07 MB / 7.84 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 115.0.5790.173
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1202
```

### Severity

serious, but I can work around it

### Additional Information

I get the following `iframe` inserted before the last column:
```html
<iframe style="display: block; position: absolute; top: 0; left: 0; width: 100%; height: 100%; overflow: hidden; border: 0; opacity: 0; pointer-events: none; z-index: -1;" aria-hidden="true" tabindex="-1" src="about:blank">
   <html><head></head><body></body></html>
</iframe>
```
I made sure all browser plugins are disabled but still got the same output.

**Comment by hAbuMustafa** [comment]
> Please provide a proper reproduction for the issue as instructed by the issue template:
> 
> > A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue.
> 
> A single code snippet with missing imports does not meet the above criteria. [Dimension bindings](https://svelte.dev/docs/element-directives#block-level-element-bindings) may be one possible reason for your issue.

Here's a [repo](https://github.com/hAbuMustafa/issue-example-sveltekit-dynamic-table) to reproduce the bug. Because I needed the `thead` height to stack several sticky rows, as shown in the repo.

It is TRUE that it is caused by the dimension binding. Because I needed the `thead` height to stack several sticky rows, as shown in the repo.

I originally had a temporary solution by using `display: none;` role on all `iframe` elements. and now I preferred shifting to controlling `colgroup`s with `visibility: collapse;` on the selected `col` for a more neat code.

**Comment by pawelblaszczyk5** [comment]
This should belong to Svelte repo, not SvelteKit specific. However, the reason are size bindings they use iframe trick to react to resize because they're created before ResizeObserver was introduced

You can use new ones that utilize ResizeObserver under the hood and don't need the iframe, check out here 

https://github.com/sveltejs/svelte/pull/8022

**Comment by gtm-nayan** [comment]
Yeah ResizeObserver bindings would be the way to do this now. If you absolutely need to use the old way for legacy reasons, you can maybe bind to dimension updates on a hidden element placed inside the table cell.

Likely not much we can do here otherwise.
