### ISSUE TITLE
vite-manifest.json missing

### ISSUE THREAD

**Issue by Spaceman2019** [sveltejs/kit#10608]
### Describe the bug

If I build a package I get the following error: 

[vite-plugin-sveltekit-compile] ENOENT: no such file or directory, open '... /dist/output/client/vite-manifest.json'

the screenshot of the output:
![Bug](https://github.com/sveltejs/kit/assets/53607207/8ea78a94-ba2c-42b2-ac0a-5e0377b566ee)

### Reproduction

Create a new project and build it.

### System Info

```Shell
Here is the part of my package.json:
	"peerDependencies": {
		"svelte": "^4.0.0"
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/adapter-node": "^1.3.1",
		"@sveltejs/kit": "^1.23.0",
		"@sveltejs/package": "^2.0.0",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.10.1",
		"publint": "^0.1.9",
		"svelte": "^4.0.5",
		"svelte-check": "^3.4.3",
		"tslib": "^2.4.1",
		"typescript": "^5.0.0",
		"vite": "^4.4.2"
	},
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
Works fine for me in a new project.

Please provide a proper reproduction for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue. Explaining how to reproduce is generally not enough. If no reproduction is provided, the issue will be closed.

**Comment by Spaceman2019** [comment]
Steps to recreate:
npm create svelte@latest test
cd test
npm install
