### ISSUE TITLE
A way to explicitly use svelte's fetch from load function on the server

### ISSUE THREAD

**Issue by HugeLetters** [sveltejs/kit#10609]
### Describe the problem

I have a `+page.ts` file
```ts
export const load: PageLoad = async ({ fetch }) => {
    const post = 20;
    const prefetched = await fetch(`https://jsonplaceholder.typicode.com/posts/${post}`).then(
        (response) => response.text()
    );
    return { post, prefetched };
};
```
and I have `+page.svelte`
```ts
let post = data.post;
let postData = data.prefetched;
$: fetch(`https://jsonplaceholder.typicode.com/posts/${post}`)
    .then((response) => response.text())
    .then((x) => (postData = x));
```

I have to duplicate fetching logic. If I extract it to a function - then Svelte's gonna warn me I'm using a native `fetch` in my `load` function instead of the one provided by `load`. 

### Describe the proposed solution

But forcing me to pass in fetch every time in each load function is kinda silly - in our project API is an external server so I'll have a lot of these fetch calls, some of those will need to be prefetched. 
This is an okay solution but nonetheless I wish there was an option to do something simpler.

The solutions I can think of which could be provided by SvelteKit are:
- allow to explicitly import your modified `fetch` so I can use it in my data querying functions and then reuse those.
- have a boolean config option which would """magically""" replace native fetch with a your modified one in server-side load calls. 

### Alternatives considered

The only sensible solution I could some up with is to create a function
```ts
export function _getPosts(post: number, _fetch = fetch) {
	if (!post) return null;
	return _fetch(`https://jsonplaceholder.typicode.com/posts/${post}`).then((x) => x.text());
}
```

### Importance

nice to have

**Comment by Conduitry** [comment]
`load`'s `fetch` on the server needs to be an argument to `load` rather than a global or a singleton you can import from somewhere because it contains logic specific to this request for things like resolving relative paths and handling cookies. JS does not (yet) have an asynchronous context propagation mechanism, so we'd have no idea which incoming request this given outgoing request corresponded to.

**Comment by HugeLetters** [comment]
> `load`'s `fetch` on the server needs to be an argument to `load` rather than a global or a singleton you can import from somewhere because it contains logic specific to this request for things like resolving relative paths and handling cookies. JS does not (yet) have an asynchronous context propagation mechanism, so we'd have no idea which incoming request this given outgoing request corresponded to.

So my function which accepts `fetch` is an argument is probably the best solution then?
