### ISSUE TITLE
+page.svelte is completely useless on many IDEs

### ISSUE THREAD

**Issue by ollyde** [sveltejs/kit#10606]
### Describe the problem

Before closing please read.

Some users cannot use VSC because of disability reasons or company policy. Also you shouldn’t be forcing everyone to use a narrow range of IDEs.

On a large project I cannot find any files with search since everything is called +page.layout

Many IDEs don’t support searching file via directory.

Also even on larger projects it won’t show the files on search, that is super annoying going back to clicking like I was a junior again, not good design guys.

I would be nice if you brought back the nice feature of same name file names; for example

login/+login.svelte (can still keep +page.svelte)..

What’s wrong with two options?

I read the discussions they don’t make sense from a real project point of view.

I know a design decision was made but it’s worth bringing this back up if it’s a common complaint I see people in my teams making and me. I also see online people are leaving SvelteKit because of this; but you guys ignored them here :/

Right now we are making symbolic links to get round this which has its own flaws.

Related

https://github.com/sveltejs/kit/issues/10598#issue-1861278719

### Describe the proposed solution

Mentioned

### Alternatives considered

+page.svelte is horrible to use on larger projects and alternatives IDEs

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment]
Please do not open another issue just because you don't like the outcome of the issue that was closed. We're not going to introduce another option of doing the same thing, because that will fragment projects. The decision stands.

Btw the bigger your project the better `+page.svelte` etc becomes, because you
- can colocate your components that are only relevant for that page right next to the `+page.svelte` file
- can easily find the page you are looking for by writing the folder name and a `+` in your editor's file search bar - that way it's filtered to special SvelteKit files only (I'm not aware of any IDEs that don't support file searching like that)

**Comment by ollyde** [comment]
No problem, didn't see their was an issue open.

Would be amazing to get this fixed, right now I have a person on my team who uses some special tools for accessibility and can't search via directory based results, I'll get the name of the tool.

A few small points also
- When you have a lot of +page.svelte open, it gets very confusing fast, even with the small reference text..
- Searching 'login.svelte' is much better than +page.svelte, which gets pushed to the bottom in VSC and IntelliJ.
- Ops guys, some of them are using find with basic text editors, this +page.svelte is hell for them.

There's no justified reason give for "+page.svelte", just seems like my way or the highway. "+{route-name}.svelte" is such much nicer for everything.

**Comment by ollyde** [comment]
@dummdidumm also regarding you're point for pressing "+" it doesn't work.

Searching for "/auth/enter-login/+page.svelte"

I though Svelte was about keeping it simple and things just working; I guess that's changed.

<img width="204" alt="Screenshot 2023-08-23 at 11 12 32" src="https://github.com/sveltejs/kit/assets/6940726/7c526863-2181-4139-85d9-044ad2c92d8d">

**Comment by dummdidumm** [comment]
Search for `+ en` (note the whitespace) or `en+`, that works in VS Code.

**Comment by ollyde** [comment]
@dummdidumm thanks  :-) 

I still think just keeping it simple with actual page root names is much better. 
Especially when I got like 10 of them open 🤷‍♂️

And for the other reasons I listed 👍

**Comment by ghostdevv** [comment]
> I still think just keeping it simple with actual page root names is much better.
Especially when I got like 10 of them open 🤷‍♂️

In VSC you can play around with the `workbench.editor.labelFormat` setting

**Comment by ollyde** [comment]
@ghostdevv I shouldn't have to play around with this to get a framework to work, Sveltekit just used to work out the box.
