### ISSUE TITLE
Support glob patterns in workspaces (postinstall script)

### ISSUE THREAD

**Issue by chill389cc** [sveltejs/kit#10610]
### Describe the bug

postinstall.js script doesn't successfuly create `.svelte-kit` directory in monorepositories that use glob patterns to enumerate their workspaces. Using [globby](https://www.npmjs.com/package/globby) allows us to support both fully enumerated workspace directories and glob patterns.

For example, our monorepositories top-level package.json contains the following for its workspaces:
```json
  "workspaces": [
    "packages/*",
    "examples/*",
    "clients/*"
  ],
  ```
  
The current postinstall script looks for a literal directory called `packages/*`, which obviously doesn't exist. [NPM package.json documentation](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#workspaces) has examples of using glob patterns, and the [JSON schema](https://github.com/SchemaStore/schemastore/blob/875dabd7c046bf36d20cdcfab06544c75eab5eec/src/schemas/json/package.json#L760) for package.json says it supports glob patterns.

### Reproduction

https://github.com/chill389cc/sveltekit-bug-mvr

### Logs

```Shell
The only relevant logs are those logs caused  when trying to `vite build` or  `vite dev` when the `.svelte-kit` directory is not generated by the postinstall script.
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 5.95 GB / 31.69 GB
  Binaries:
    Node: 18.16.1 - ~\nodejs\node.EXE
    Yarn: 1.22.19 - ~\nodejs\yarn.CMD
    npm: 9.5.1 - ~\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    svelte: ^3.59.1 => 3.59.2
```

### Severity

annoyance

**Comment by ghostdevv** [comment]
Can you provide a minimal reproduction? I don't fully understand the problem

**Comment by chill389cc** [comment]
Hmm, I'm wondering if this isn't the only place in sveltekit that needs to be updated to support glob patterns in the workspaces package.json property. While the PR I submitted here did successfully enable the postinstall script to create the `.svelte-kit` directory in a package in our monorepo, the `vite dev` script is still failing with this error:
```
> vite dev

Forced re-optimization of dependencies
error when starting dev server:
Error: Missing "./internal/disclose-version" specifier in "svelte" package
    at e (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:25)
    at n (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:627)
    at o (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:1297)
    at resolveExportsOrImports (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:28712:20)
    at resolveDeepImport (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:28731:31)
    at tryNodeResolve (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at async file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:65837:21
    at async file:///C:/Users/cah34/Code/Developer/javascript/node_modules/vite/dist/node/chunks/dep-df561101.js:44852:20
npm ERR! Lifecycle script `dev` failed with error: 
npm ERR! Error: command failed
npm ERR!   in workspace: ts-sveltekit@0.0.1
npm ERR!   at location: C:\Users\cah34\Code\Developer\javascript\examples\svelte2
```

Further, I'm not sure how the postinstall script works for monorepos with workspaces even when not using glob patterns. The script fails even if I change my workspaces to contain simply an array of folder names. [This line of code](https://github.com/sveltejs/kit/blob/45fd22322776bd6b140fe120303019a1c5c5654e/packages/kit/postinstall.js#L21) adds all of the files in the containing workspace folder to the `directories` array, and then [this line of code](https://github.com/sveltejs/kit/blob/45fd22322776bd6b140fe120303019a1c5c5654e/packages/kit/postinstall.js#L28) attempts to change the current working directory to a file, which throws an error and quits the script. Is there a minimal reproduction of this code (as it currently is) working? Seems like there hasn't been many people using sveltekit in a project that is using workspaces.
If I spend more time investigating this I'll put together a reproduction but its looking like a bigger issue than I initially reported.

**Comment by ghostdevv** [comment]
I can't see a README anywhere--? @chill389cc

**Comment by chill389cc** [comment]
@ghostdevv Sorry, forgot to push. That's embarrassing. It's there now.

**Comment by ghostdevv** [comment]
Ty! Looking into it more you're right - it seems like glob pattern support was removed here #10174 so I raised #10625 to revert that change. We can then look into [the other issue](https://github.com/sveltejs/kit/issues/10610#issuecomment-1692027658) you posted about
