### ISSUE TITLE
Documentation should have TypeScript options

### ISSUE THREAD

**Issue by ollyde** [sveltejs/kit#10612]
### Describe the problem

When I look at docs and see JavaScript examples, for example https://kit.svelte.dev/docs/routing

I don't know anyone who is writing vanilla JS and looking across the internet it doesn't seem common for new projects.
I myself have not worked a vanilla JS project for over a decade, strictly being TypeScript. 

This being a framework for new projects, why do we have JavaScript examples that don't work in TypeScript, extremely annoying.

### Describe the proposed solution

Have TypeScript examples, or at least a Tab for them

### Importance

would make my life easier

**Comment by gtm-nayan** [comment]
![image](https://github.com/sveltejs/kit/assets/50981692/c449b6c7-a3e0-46b4-8f09-d154b6fcb2f9)

**Comment by ollyde** [comment]
@gtm-nayan thanks perhaps it should be moved, very hidden
