### ISSUE TITLE
Issue with generated SvelteKit types in VS Code

### ISSUE THREAD

**Issue by michal-weglarz** [sveltejs/kit#10627]
### Describe the bug

I've been having this annoying issue in VS Code, where I open a SvelteKit file (page, layout, hooks etc.) and I can see that Typescript is not working properly as some parameters are not getting their types inferred correctly, and instead I get a bunch of anys. However, if I remove the parameter and then retype in again, without any other changes whatsoever, it magically starts working just fine.

I tried to capture the issue in the recording. Do you know what might be causing the issue?

https://github.com/sveltejs/kit/assets/37783495/5dd7314f-e86d-4750-a3e3-38ed357cd919

My app.d.ts file:
```ts
import { Session, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types/supabase';

declare global {
	namespace App {
		interface Locals {
			supabase: SupabaseClient<Database>;
			getSession(): Promise<Session | null>;
		}
		interface PageData {
			session: Session | null;
		}
		// interface Error {}
		// interface Platform {}
	}
}
```

I've also tried running `npx svelte-kit sync` but it didn't change anything.

### Reproduction

I've managed to reproduce it with the default SvelteKit demo:
1. Create a new SvelteKit project using CLI: `npm create svelte@latest my-app`
    - select "SvelteKit demo app" template
    - select Typescript syntax.
    
2. `cd my-app && npm install` and then open VS Code
3. Create a new `+page.server.ts` file in `src/routes/sverdle/how-to-play/` with the following content: 
    ```ts
        export const load = ({ cookies, depends, fetch }) => {
          return {
            message: "test",
          };
        };
    ```
4. Run the dev server: `npm run dev` => **TYPES ARE CORRECT**.
5. Open file `src/routes/sverdle/+page.server.ts` in a new editor tab.
6. Close the editor, shut down the dev server, and then reopen VS Code again. 
7. Switch to the `+page.server.ts` that we just added => **TYPES ARE BROKEN** 

Sometimes, to see the wrong types, it might take up to a couple of tries of closing and reopening the editor, but regardless of that it happens very consistently. 

The only way to get the appropriate types back is to remove the parameter, and then retype it again without any other modifications (I demonstrated that in the video recording above).

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 142.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.102
    Safari: 17.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.22.4
    svelte: ^4.0.5 => 4.1.2
    vite: ^4.4.2 => 4.4.7
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
There is a language tools problem and an issue about it already. 

https://github.com/sveltejs/language-tools/issues/2053

It probably is a race condition. But we haven't found out the reason yet.

**Comment by ghostdevv** [comment]
Will close this since it's a duplicate :pray:
