### ISSUE TITLE
Consider DocSearch for Svelte and SvelteKit sites

### ISSUE THREAD

**Issue by jasongitmail** [sveltejs/kit#10623]
### Describe the problem

Svelte and SvelteKit docs are not currently available via https://docsearch.algolia.com  

If they were, this would allow Svelte and SvelteKit docs to be consumed via tools that offer DocSearch integration, such as Raycast's ability to search docs, which is currently available for: Vite, Tailwind, Nuxt, Vue, Jest, React, etc.  

<img width="750" alt="raycast" src="https://github.com/sveltejs/kit/assets/50032291/f433758b-90fc-4ada-8f70-c0b9706e2a5a">

It also provides a good search UX on the docs website.

### Describe the proposed solution

Consider applying for Svelte and SvelteKit https://docsearch.algolia.com/apply/  

### Importance

nice to have

**Comment by ghostdevv** [comment]
I think it's pretty much decided about switching to `orama`, but you can leave a comment about using docsearch in this issue: #8712
