### ISSUE TITLE
Remove last slash

### ISSUE THREAD

**Issue by potatotomatobanana** [sveltejs/kit#10644]
### Describe the bug

Can we please remove the last slash from this URL?

![Screenshot 2023-08-28 121405](https://github.com/sveltejs/kit/assets/116115216/1302d134-290f-4cb6-9251-8e25baa59615)

### Reproduction

_

### System Info

```Shell
_
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is a more well-formed URL than one without the slash. When you request `http://whatever`, you're actually sending a path of `/`, not an empty string.

This message is actually coming from Vite, not SvelteKit itself, but I don't think they're going to want to change anything here either, nor do I think they should.
