### ISSUE TITLE
Why the CJS in svelte.config.cjs?

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#1064]
Why does `svelte.config.cjs` use CommonJS? Seems like a design that won't age well. It also prevents sharing logic between the dev and build steps. Can't every file in a project of `"type": "module"` use ES modules?

**Comment by GrygrFlzr** [comment]
This was a limitation of language tools and VS Code, not a deliberate decision. Work is already done to support ESM config files with sveltejs/language-tools#930 `(feat) support ESM configs`, but we're playing it safe for the moment and seeing if there are any bugs with the language tools update before we swap SvelteKit's config over to ESM.

**Comment by Conduitry** [comment]
It was a limitation of the language server used in editor tooling I believe. Part of this has been resolved, and I think the intention is to also accept ESM here before too long.

**Comment by dummdidumm** [comment]
#936 will add support for it
