### ISSUE TITLE
sveltekit crashes on startup using node.js 18.17.1 and latest pnpm/yarn

### ISSUE THREAD

**Issue by xxxhussein** [sveltejs/kit#10646]
### Describe the bug

![image](https://github.com/sveltejs/kit/assets/122984423/f6257644-b6e6-453d-970e-58e6ff30e03a)

### Reproduction

https://github.com/xxxhussein/sveltekit-reprod

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
    Memory: 3.81 GB / 7.89 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/kit: ^1.23.0 => 1.23.0
    svelte: ^4.2.0 => 4.2.0
    vite: ^4.4.9 => 4.4.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

installing packages using Bun package manager (on WSL) while using Node.js to run vite worked fine. It's when I moved to Windows and started using pnpm/yarn where the error above showed. Tried rm -rf .svelte-kit, node_modules, clearing pnpm and yarn cache, didn't work.

**Comment by xxxhussein** [comment]
related: same happened in https://github.com/oven-sh/bun/issues/4174 except that i'm not using workspaces and i'm using Windows

**Comment by gtm-nayan** [comment]
Works fine for me on Windows with pnpm, reminder that a minimal reproduction must be provided without any fluff from the rest of your project otherwise it'll be closed as invalid.

**Comment by xxxhussein** [comment]
> Works fine for me on Windows with pnpm, reminder that a minimal reproduction must be provided without any fluff from the rest of your project otherwise it'll be closed as invalid.

node_modules and yarn.lock are the only parts i didn't include. should i include them?

**Comment by xxxhussein** [comment]
update: issue gone after creating new project in C:\
