### ISSUE TITLE
Can't install adapter-node

### ISSUE THREAD

**Issue by engageintellect** [sveltejs/kit#10649]
### Describe the bug

I am trying to deploy my application using Ubuntu and PM2. To do this I would like to build my app, using the node adapter, to which I am getting an error.

### Reproduction

* clone repository
* cd into repository
* pnpm i && pnpm i -D @sveltejs/adapter-node@next

### Logs

```Shell
 WARN  GET https://registry.npmjs.org/@sveltejs%2Fadapter-node error (ERR_INVALID_THIS). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@sveltejs%2Fadapter-node error (ERR_INVALID_THIS). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npmjs.org/@sveltejs%2Fadapter-node: Value of "this" must be of type URLSearchParams
```

### System Info

```Shell
System:
    OS: macOS 13.5.1
    CPU: (10) x64 Apple M1 Pro
    Memory: 84.81 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.5.1 - /usr/local/bin/node
    npm: 9.8.0 - /usr/local/bin/npm
    pnpm: 7.25.1 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Edge: 116.0.1938.62
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.20.1 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I have built applications this way in the past without any issues, so I'm sure I am missing something trivial.

I also tried updating all sveltekit related packages to "latest", without any luck.

**Comment by Conduitry** [comment]
See https://github.com/pnpm/pnpm/issues/6424 - This is an issue in older versions of pnpm with Node 20.

**Comment by engageintellect** [comment]
> See [pnpm/pnpm#6424](https://github.com/pnpm/pnpm/issues/6424) - This is an issue in older versions of pnpm with Node 20.

You're a gentleman and a scholar. Deleting pnpm and reinstalling version 8.7.0 worked like a charm.

Thank you.
