### ISSUE TITLE
Callback in submit for progressively enhanced form returns wrong data type

### ISSUE THREAD

**Issue by ur5us** [sveltejs/kit#10658]
### Describe the bug

The `result` in the `({ result, update }) => {}` callback returned by the custom `submit` function carries the JSON response (`data`) itself instead of an `ActionResult` object with a combination of `type`, `status` and potentially `data` (which is the JSON response from the server) properties.

### Reproduction

Here’s an example app to reproduce the issue: https://github.com/ur5us/sveltekit-progressive-form-enhancement-type-issue

### Logs

```Shell
The app will log the `result`.
```

### System Info

```Shell
System:
    OS: Linux 6.4 Solus 4.4
    CPU: (8) x64 AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx
    Memory: 5.00 GB / 29.28 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.asdf/installs/nodejs/16.17.1/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 9.7.2 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.7.0 - ~/.asdf/installs/nodejs/16.17.1/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.24.0 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9
```

### Severity

blocking all usage of SvelteKit

**Comment by eltigerchino** [comment]
`use:enhance` is meant to be used with SvelteKit form actions https://svelte.dev/docs/kit/form-actions . If you're using a custom endpoint, it will not work. https://svelte.dev/docs/kit/form-actions#Alternatives
