### ISSUE TITLE
Vite build renaming functions causes code to fail.

### ISSUE THREAD

**Issue by dschalk** [sveltejs/kit#10663]
### Describe the bug

I was puzzled for a while. My code worked fine when loaded with "npm run dev," but after npm run build, the same code didn't work when loading with "npm run preview" or node build. Now I think I know why.

There's no need to show any definitions here. Suffice it to say, when I click "Reverse" a pointer reverts to "1" and increases by 2s (1,3,5,etc.) each time "Reverse" is clicked immediately thereafter. If any other effective key presses or clicks occur, the pointer stays where it is unless and until "Reverse" is clicked again. At least, that's what happens when I load the application with "npm run dev."

I verified that function names remain intact when "npm run dev" is used, and have different names when "node build" or "npm run preview" load the app in my browser.

All I need to do is compare the most recently run function "func" with the one that preceeded it "func === func" and "func.name === func.name" both work before Vite build renames them in some places, but not others. Is there a convenient way to disable the renaming feature? If not, maybe there should be. Otherwise, renamed functions should be renamed everywhere.

### Reproduction

There's no need here. This isn't a bug, just an annoying feature I have to deal with.

### System Info

```Shell
Linux, Firefox, and Chrome
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I don't really know what this is asking about or for. Is it just that minified code changes function names, which breaks things that depend on functions having specific names? Minifying code and changing variable and function names is standard across virtually all web applications.

If you want to have more specific control over minification options, you can do that with https://vitejs.dev/config/build-options.html#build-minify and https://vitejs.dev/config/build-options.html#build-minify

**Comment by dschalk** [comment]
I apologize for bothering you about this. All I needed to do was leave out the names. Here's the code that words with dev, preview, and node build:
   
if (arr.slice(-1)[0].name !== arr.slice(-2,-1)[0].name) index = 1;

**Comment by dschalk** [comment]
I apologize for bothering you about this. All I needed to do was leave out the names. Here's the code that works with npm run dev, npm run preview, and node build:

if (arr.slice(-1)[0].name !== arr.slice(-2,-1)[0].name) index = 1;

**Comment by msf-caesar** [comment]
Try with explicitly disabling the code renaming feature in Vite build configuration. This can ensure that function names remain intact and consistent across the entire application. Alternatively, you can consider using minification options that preserve function names during the build process.

**Comment by msf-caesar** [comment]
Try with configuring the Vite build process to disable the function renaming feature. If that is not possible, you may need to manually update the code to ensure consistent function names throughout the application.

**Comment by Conduitry** [comment]
I'm going to close this. You can pass specific minification options as mentioned above, if you need to. But code that relies on the names of certain functions is almost certainly a bad idea and an indication that you should be doing something else.

**Comment by spillz** [comment]
I echo the OPs concern. I think name mangling should be opt-in not opt-out by default in the vite build system. I'm happy enough with minification otherwise.

> I don't really know what this is asking about or for. Is it just that minified code changes function names, which breaks things that depend on functions having specific names? Minifying code and changing variable and function names is standard across virtually all web applications.

Name mangling may be standard but I think it's only standard because it's an old practice that made much more sense when browsers were creaky and slow and we did a lot more security-through-obscurity theater.

By far the biggest source of problems I run into when using vite comes from vite name mangling my sources. Sure it works if you don't use any of the introspective language features of JavaScript but I don't see how breaking language features and libraries that use them is a sensible choice for a bundler given the massive ecosystem we are working in.
