### ISSUE TITLE
Docs: GitHub Pages workflow sample has indentation issues

### ISSUE THREAD

**Issue by theetrain** [sveltejs/kit#10685]
### Describe the bug

On the docs site for "Static site generation", the `deploy.yml` workflow sample renders with incorrect indentation: https://kit.svelte.dev/docs/adapter-static#github-pages

Though its source file is correctly indented: https://github.com/sveltejs/kit/blob/a58f0491ecbd91cc3729836b6940066b1ee7317c/documentation/docs/25-build-and-deploy/50-adapter-static.md

![image](https://github.com/sveltejs/kit/assets/12798751/0920d59b-2c38-4366-831b-f15ff610e99a)

### Reproduction

1. Go to https://kit.svelte.dev/docs/adapter-static#github-pages
2. Observe incorrect yaml indentation

### System Info

```Shell
Tested on Chrome and Safari.
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Syntax highlighting seems broken too for that, although both should've been fixed in site-kit 6 next 32, kit.svelte.dev is currently on 6 next 36 🤔

**Comment by gtm-nayan** [comment]
Looks like some cache gone wrong, the originally described issue has been resolved, I'll keep this open as a reminder to look into the cache stuff.
