### ISSUE TITLE
Extra space in ORIGIN when setting it through package.json script

### ISSUE THREAD

**Issue by bfg-lazaro** [sveltejs/kit#10688]
### Describe the bug

The issue occurs when I attempt to do a custom deploy on my project and need to create the ORIGIN. It seems that the .env file is not being taken into account, so I set the ORIGIN using the package.json script:

"prodServer": "SET ORIGIN=https://test:3148 && tsm ./prodServer.ts"

I believe this script works on Linux.

While debugging the build, I noticed that the ORIGIN is being taken with an extra space at the end, like this: https://test:3148 /favicon.ico

I was able to fix this issue by removing the space at the end of the ORIGIN in the package.json script:

"prodServer": "SET ORIGIN=https://test:3148&& tsm ./prodServer.ts"

I’m not certain if this is an error with SvelteKit or Vite, but it could potentially be fixed by adding a simple trim function: const origin = env('ORIGIN', undefined).trim();

### Reproduction

 windows:

`"prodServer": "SET ORIGIN=https://test:3148 && tsm ./prodServer.ts"`

### System Info

```Shell
windows
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This appears to be just how Windows works. If I run `set FOO=bar && node -e "console.log(process.env)"` in a command shell, I see that the value of `FOO` has a trailing space. I don't think SvelteKit (or Vite) should try to account for this by trimming the environment variables that are passed to it.
