### ISSUE TITLE
Vite defineConfig.define crashes client-side logic

### ISSUE THREAD

**Issue by YoloClin** [sveltejs/kit#10681]
### Describe the bug

If I attempt to use vite `defineConfig.define`, the SSR works correctly but CSR crashes - it appears to treat the `define` value as raw JavaScript during client side rendering, rather than as a string (e.g., `console.log(foo)` instead of `console.log("foo");`)

### Reproduction

I created a basic SvelteKit project via `npm create svelte@latest my-app; cd my-app; npm install;`. I then modified `vite.config.js` to:

```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
        plugins: [sveltekit()],
        define: {
            World: 'space'
        }
});
```

And modified `src/routes/+page.svelte` to:

```
<script>
        function foo(){
          console.log("Hello World");
        }
        foo()
</script>

<button on:click={foo}>Hello World</button>
```

### Logs

On loading the application, vite console receives:

```

  VITE v4.4.9  ready in 458 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Hello space
```

To me this indicates the var has been replaced. The button text also renders as 'Hello space'. However, the Browser developer tools logs an error 'ReferenceError: space is not defined` on `env.ts:17`. I suspect that the browser is attempting to render `space` in a JavaScript context but not correctly wrapping the value as a string. If I attempt to double-wrap the string to `"'space'"` in vite.config.ts, the vite console treats the inner quotes as part of the value.

https://github.com/sveltejs/kit/issues/10275 indicates that svelte-package does not use vite. I'm a bit lost with the build chain of Svelte/kit, so please accept my apologies if it's something on my end.

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (2) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 5.91 GB / 7.75 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /snap/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chromium: 116.0.5845.140
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.24.0 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9
```

### Severity

serious, but I can work around it

**Comment by YoloClin** [comment]
![Browser with ReferenceError in console](https://github.com/sveltejs/kit/assets/20364970/b310fb53-5c20-471b-8a01-7cee65139070)

**Comment by brunnerh** [comment]
This is not SvelteKit-specific but just [how Vite behaves](https://vitejs.dev/config/shared-options.html#define) during in dev mode.

> Define global constant replacements. Entries will be defined as globals during dev and statically replaced during build.
> 
> - String values will be used as raw expressions, so if defining a string constant, it needs to be explicitly quoted (e.g. with `JSON.stringify`).

What fails here on the client, is the attempt to essentially execute `window['world'] = space`.

As noted by the docs, use `JSON.stringify` when setting these values, also, given that this just does a global replacement regardless of any context, it is a bad idea to use commonly appearing words as that may break existing code; personally, I use all-caps, sometimes even with an additional prefix to be certain, e.g. `VITE_WORLD` instead of `world`.

As the value will be JSON, if you want to replace something in Svelte markup, you can just use an interpolation with the identifier: `{VITE_WORLD}`

**Comment by YoloClin** [comment]
Thanks, that works but took a bit to unpack.

I'll document both the solution and bug for others - the tldr is 'stringify the property value and don't use `define` values within HTML'. The solution was:

```
        define: 
        {
            "World": JSON.stringify("space") // Evaluates to "\"world\""
        }
```

and 

```
<script>
        function foo(){
          console.log("Hello " + World);
        }
        foo()
</script>

<button on:click={foo}>Hello {World}</button>
```

Notably, The button HTML went from `Hello World` - this seems to compile via `npm run dev` fine, but `npm build` fails as something in the build chain attempts to stringify the value - this might be a bug (build output is inconsistent to run dev output) but it's clear now that define kvp's shouldn't be rendered raw within HTML context regardless.


Thanks for your help :)
