### ISSUE TITLE
[vite-plugin-svelte] invalid plugin options "disableTransformCache" in config

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1069]
**Describe the bug**
After a simple `rm -rf node_modules && npm i` I now get this warning in console:

```
[vite-plugin-svelte] invalid plugin options "disableTransformCache" in config
{ disableTransformCache: true, extensions: [ '.svelte' ] }
```

I can see in my package-lock.json an (involuntary) upgrade from `1.0.0-next.6` to `1.0.0-next.7` for `@sveltejs/vite-plugin-svelte`.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.65 => 1.0.0-next.65
    svelte: 3.37.0 => 3.37.0
    vite: 2.1.5 => 2.1.5

- Your adapter: static
</details>

**Comment by Conduitry** [comment]
The cache has been removed entirely in the latest Vite plugin version. Take a look at its changelog. Just remove it from your configuration.

**Comment by frederikhors** [comment]
I don't have any `disableTransformCache` in my config, @Conduitry. I'm using the default svelte init one. Please, re-open.
