### ISSUE TITLE
default export from commonjs dependency compiles differently in dev and prod builds

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/kit#10696]
### Describe the bug

```ts
import { json } from "@sveltejs/kit";
import foo from "somepackage/index.js"; 
 
export const GET = () => {
  console.log(foo);
  return json(foo); 
};
```
when running `vite dev` it prints `{a: 1}`. when running `vite build` it prints `{ default: { a: 1 } }`

### Reproduction

https://github.com/DetachHead/sveltekit-issue/tree/d724513ed294e55a237241fb371e815ab3c9f923

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 1.81 GB / 15.92 GB
  Binaries:
    Node: 20.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 7.27.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Chrome: 116.0.5845.180
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/kit: ^1.20.4 => 1.24.1
    svelte: ^4.0.5 => 4.2.0
    vite: ^4.4.2 => 4.4.9
```

### Severity

serious, but I can work around it

### Additional Information

- only happens if the dependency is specified in `dependencies` in `package.json`
- kinda related: https://github.com/microsoft/TypeScript/issues/54102

**Comment by benmccann** [comment]
I'm going to close this since it's an issue in Vite and there's nothing we can do about it in SvelteKit. I think it will be fixed in Vite 5 as this sounds like https://github.com/vitejs/vite/pull/14521
