### ISSUE TITLE
href inside +layout.svelte always relative to current url, not the file route

### ISSUE THREAD

**Issue by risalfajar** [sveltejs/kit#10708]
### Describe the bug

My routes structure is like this
```
/routes
  /dashboard
    /programs
      /inventory
      /investment
      +layout.svelte
```

Inside `+layout.svelte` I have a tabbed layout using anchors
```html
	<div class="tab-group">
		<a href="inventory">INVENTORY</a>
		<a href="investment">INVESTMENT</a>
	</div>
	<slot />
```

Clicking the tab works **for the first time**, it goes to `/dashboard/programs/inventory/`, but when I click the same tab again it will go to `/dashboard/programs/inventory/inventory/` which is 404.

`trailingSlashes` is set to “always”, other values won't work.

How to fix this without using absolute path?

### Reproduction

[Repo](https://github.com/risalfajar/svelte-relative-routes-problem)

### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M2
    Memory: 62.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Safari: 16.6
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.24.1 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

**Comment by Conduitry** [comment]
You need to construct the appropriate URLs yourself. There's no concept in HTML of a base URL just for a part of a page, and we don't want to take URL resolution out of the hands of the browser, or rewrite `href`s on the fly, etc. The current behavior is the intended behavior.

**Comment by risalfajar** [comment]
I believe this is related to [this](https://github.com/sveltejs/kit/issues/5), but I can't find the solution.

Is there no way to get the path of the file (not the current route, as in $page.route or $page.url)? So that we can prepend it in the href.

I think it'll be very useful for deep nested routes, especially if it has lots of slug.
This is an example from other project:
```svelte
<li class="crumb"><a href="/dashboard/projects/{$company.id}/{year}/{month}/{$project.id}/items">{$project.name}</a></li>
```

**Comment by risalfajar** [comment]
Maybe we can introduce `url()` like in [Routify](https://www.routify.dev/docs/helpers#url)?
