### ISSUE TITLE
404 requesting asset in prerendered page

### ISSUE THREAD

**Issue by navneetsharmaui** [sveltejs/kit#1070]
**Describe the bug**
When using adapter-static the application is not building properly when the route component contains the async load function to load the data from JSON file and when a page contains the nested layouts/routes.

1. When using the async load function to load the data from the JSON file
2. When the page contains the nested layouts/routes.
3. While building the nested layout it tries to refer to the favicon.ico in its folder and tries to create the favicon.ico folder.

**Logs**
1. This occurs when using SSR options is false in the configuration.
![adapter-static-three-nf-nssr](https://user-images.githubusercontent.com/11630812/115117884-4aa71a80-9fbe-11eb-8305-7940dc39f6b8.png)
2. This occurs when using SSR options is false in the configuration and force option is true in prender in configuration.
![adapter-static-four-f-nssr](https://user-images.githubusercontent.com/11630812/115117970-b5f0ec80-9fbe-11eb-9e90-32e98720857f.png)

3. This occurs when using SSR options is true in the configuration.
![adapter-static-two-no-f](https://user-images.githubusercontent.com/11630812/115117987-cb661680-9fbe-11eb-98aa-b414a7ea058a.png)

4. This occurs when using SSR options is true in the configuration and force option is true in prender in configuration.
![adapter-static-one](https://user-images.githubusercontent.com/11630812/115117997-d8830580-9fbe-11eb-846e-f14273b64dae.png)

![sveltekit-build-folder-structure](https://user-images.githubusercontent.com/11630812/115118242-dc635780-9fbf-11eb-9b90-d6ed0359237b.png)

Svelte Config
![svelte-config](https://user-images.githubusercontent.com/11630812/115119181-ae344680-9fc4-11eb-9a07-a70aced0b561.png)
 
**To Reproduce**
1. Create the application with the latest version of sveltekit and add adapter-static as a dev dependency.
2. Create the route with nested layouts, create a settings route with profile and notification as nested layouts.
3. Try to create an application with the following folder structure.
![svelte-kit-full-folder-structure](https://user-images.githubusercontent.com/11630812/115118289-16ccf480-9fc0-11eb-937f-c2390a29b223.png)

Repo you can refer to for the code.
https://github.com/navneetsharmaui/sveltekit-starter

**Comment by benmccann** [comment]
Better prerendering error messages were added in https://github.com/sveltejs/kit/pull/1062. Can you upgrade to the latest version of SvelteKit and see if you get a more informative error message?

**Comment by navneetsharmaui** [comment]
@benmccann The sveltekit version is 1.0.0-next.83
And the is the screenshot of the build error now
![updated-svektekit-1 0 0-next 83](https://user-images.githubusercontent.com/11630812/115233507-a0520300-a135-11eb-9ac5-823ab69d849d.png)

**Comment by benmccann** [comment]
Getting a 404 on an `.ico` file seems likely to be a usage issue and fairly unlikely to be a bug in SvelteKit.

I'd recommend you take a look at this FAQ: https://github.com/sveltejs/kit/blob/master/documentation/faq/45-assets.md

If that doesn't help, try asking on Discord

**Comment by Rich-Harris** [comment]
Looks like you have a relative `favicon.ico` link instead of an absolute one, like this: https://github.com/sveltejs/kit/blob/32b3fcde3c206347d0ca58ea2f8ecec649f5b7f5/packages/create-svelte/templates/default/src/app.html#L5
