### ISSUE TITLE
Purging unused css in stylesheet which is imported in sveltekit

### ISSUE THREAD

**Issue by 231tr0n** [sveltejs/kit#10704]
### Describe the bug

```js
import "$lib/css/main.css";
```
So i have a css file imported this way in one of my templates. But after building it using 'adapter-static' or 'adapter-auto', I see that some of the css which I did not use in any of svelte teamplate is getting bundled from the main.css file. I expected it to be purged since sveltekit purges unused css.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-qa6e5s

### System Info

```Shell
npmPackages:
    @sveltejs/adapter-auto: ^2.0.3 => 2.0.3 
    @sveltejs/kit: ^1.24.1 => 1.24.1 
    svelte: ^4.2.0 => 4.2.0 
    vite: ^4.4.9 => 4.4.9
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
I don't think we can reliably know which CSS to purge from a global stylesheet which is why we're not doing it currently. I think this only happens for styles in the Svelte template style block.
