### ISSUE TITLE
process is not defined in node library: util.js using xrpl library

### ISSUE THREAD

**Issue by Cainuriel** [sveltejs/kit#10705]
### Describe the bug

After removing process.env.VARIABLE as it is not the proper usage in sveltekit, it detected a node library using the process object giving me the error, as if I was suddenly using it in browser.

### Reproduction

When the server is up, this error appears. I have to say that it has appeared suddenly. The project has not had any problems until now. The only thing I did was to use process.env.VARIABLE in a script[ when it was not the valid way](https://joyofcode.xyz/sveltekit-environment-variables). When I removed this usage, this error appeared, which is already a node error. 
I cleared the cache node and it doesn't work either. 

### Logs

```Shell
eferenceError: process is not defined
    at node_modules/util/util.js (util.js:109:1)
    at __require (chunk-76J2PTFD.js?v=8f828950:3:50)
    at node_modules/assert/build/internal/assert/assertion_error.js (assertion_error.js:25:16)
    at __require (chunk-76J2PTFD.js?v=8f828950:3:50)
    at node_modules/assert/build/assert.js (assert.js:39:22)
    at __require (chunk-76J2PTFD.js?v=8f828950:3:50)
    at node_modules/xrpl/dist/npm/client/index.js (index.ts:4:1)
    at __require (chunk-76J2PTFD.js?v=8f828950:3:50)
    at node_modules/xrpl/dist/npm/client/BroadcastClient.js (BroadcastClient.ts:1:1)
    at __require (chunk-76J2PTFD.js?v=8f828950:3:50)
handleError @ app.js:22
```

### System Info

```Shell
"devDependencies": {
		"@playwright/test": "^1.30.0",
		"@sveltejs/adapter-auto": "^1.0.2",
		"@sveltejs/adapter-netlify": "^1.0.0-next.88",
		"@sveltejs/kit": "^1.3.10",
		"@typescript-eslint/eslint-plugin": "^5.50.0",
		"@typescript-eslint/parser": "^5.50.0",
		"eslint": "^8.33.0",
		"eslint-config-prettier": "^8.6.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"prettier": "^2.8.3",
		"prettier-plugin-svelte": "^2.9.0",
		"prisma": "^4.14.1",
		"rome": "^11.0.0",
		"svelte": "^3.55.1",
		"svelte-check": "^3.0.3",
		"tslib": "^2.5.0",
		"typescript": "^4.9.5",
		"vite": "^4.1.1",
		"vitest": "^0.25.8"
	},
	"type": "module",
	"dependencies": {
		"@lucia-auth/adapter-prisma": "^2.0.0",
		"@picocss/pico": "^1.5.7",
		"@prisma/client": "^4.9.0",
		"lucia-auth": "^1.7.0",
		"svelte-select": "^5.7.0",
		"xrpl": "^2.11.0"
	}
```
```


### Severity

annoyance

### Additional Information

_No response_

**Comment by Conduitry** [comment]
Please provide a proper minimal reproduction.

**Comment by Cainuriel** [comment]
The problem is the ``` "xrpl": "^2.11.0" ``` library.
This calls the assets dependency, and in turn, assets calls the utils.js dependency.

I can't use this library in browser contexts. 
We apologise for the inconvenience. I am correcting the title to make it clearer.
