### ISSUE TITLE
Explicit URL imports for images

### ISSUE THREAD

**Issue by Gerschtli** [sveltejs/kit#10725]
### Describe the bug

As per vite documentation (https://vitejs.dev/guide/assets.html#explicit-url-imports), importing an asset with the `?url` suffix should result in the url to the asset instead of inlining the content if the file is smaller than 4kB.

See my example repo: https://github.com/Gerschtli/sveltekit-image-inline-issue/blob/master/src/routes/%2Bpage.svelte

```svelte
<script lang="ts">
	import exampleImageDefault from '$lib/example.png';
	import exampleImageRaw from '$lib/example.png?raw';
	import exampleImageUrl from '$lib/example.png?url';
</script>

<pre>{JSON.stringify({ exampleImageDefault, exampleImageRaw, exampleImageUrl }, null, 2)}</pre>
```

When running `pnpm build && pnpm preview`, you get presented with

```json
{
  "exampleImageDefault": "data:image/png;base64,iVBORw0KGg...",
  "exampleImageRaw": "�PNG\r\n\u001a\n\u0000...",
  "exampleImageUrl": "data:image/png;base64,iVBORw0KGg..."
}
```

It seems `?raw` works, but `?url` is ignored.

To get the assets as URLs, I currently need to set `assetsInlineLimit: 0` in my `vite.config.ts`, which disables inlining for the whole app.
```ts
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	build: {
		assetsInlineLimit: 0
	}
});
```

### Reproduction

1. Checkout https://github.com/Gerschtli/sveltekit-image-inline-issue
2. Run `pnpm build && pnpm preview`
3. Open preview

### System Info

```Shell
System:
    OS: Linux 6.5 NixOS 23.05 (Stoat) 23.05 (Stoat)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 8.88 GB / 15.05 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 18.17.1 - /nix/store/1l03gdg4w3cvkygvbxsq9i19flnp1p3y-nodejs-18.17.1/bin/node
    npm: 9.6.7 - /nix/store/1l03gdg4w3cvkygvbxsq9i19flnp1p3y-nodejs-18.17.1/bin/npm
    pnpm: 8.5.1 - /nix/store/y0w8nm5p11530bvhfz3ba3kvb7wl7mfw-pnpm-8.5.1/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.25.0
    svelte: ^4.0.5 => 4.2.0
    vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

### Additional Information

I only found https://github.com/sveltejs/kit/issues/9924 but for images I still have this problem.

**Comment by gtm-nayan** [comment]
> importing an asset with the ?url suffix should result in the url to the asset instead of inlining the content if the file is smaller than 4kB.

you have it backwards, it's inlined if it's smaller than 4kB and this applies to any import that would be in the form of url.

You should file an issue with a vite only reproduction over at https://github.com/vitejs/vite if you want explicit `?url` imports to not be inlined.
