### ISSUE TITLE
Fallback URL is missing leading . in adapter-static

### ISSUE THREAD

**Issue by hybridherbst** [sveltejs/kit#10730]
### Describe the bug

When using 
```
adapter: adapter({
  fallback: '404.html',
}),
```
and adapter-static,

the resulting paths in build/index.html look like: `<link rel="modulepreload" href="./_app/immutable/chunks/index.8a112b5e.js">`
while the ones in build/404.html look like: `<link rel="modulepreload" href="/_app/immutable/chunks/index.8a112b5e.js">` which may be incorrect.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-jfbtrn?file=svelte.config.js

run `npm run build` and observe "build/index.html" and "build/404.html"

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 31.96 GB / 63.85 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.69)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3
    @sveltejs/kit: ^1.24.0 => 1.25.0
    svelte: ^4.2.0 => 4.2.0
    vite: ^4.3.9 => 4.4.9
```

### Severity

serious, but I can work around it

### Additional Information

The comment in https://github.com/sveltejs/kit/pull/9343#issuecomment-1490967570 leads me to believe this may be a documentation issue; maybe it just needs to be documented that the fallback page behaviour differs and it needs absolute URLs / correct base to work?

**Comment by Conduitry** [comment]
The fallback URL needs an absolute path to its assets, because it could be accessed from any URL of an arbitrary depth. The browser is going to be resolving relative to what it thinks the path is, not to where the `404.html` file exists on the disk.
