### ISSUE TITLE
A route called "/songs" does not work a search parameter called "page".

### ISSUE THREAD

**Issue by kenowi-dev** [sveltejs/kit#10743]
### Describe the bug

When calling the route `/songs?page=3` , the `page` url jumps back `/songs?page=1`.
When setting the `page` parameter to  `4`, `5` or `6`, the url jumps back to `/songs?page=2`.

The bug occurs in a freshly set up SvelteKit project.

The faulty search parameter already occurs in the `load` function of `+page.js` or `+page.server.js`.

This only happens, if:
- When the route is called `songs` (any other route that I tested works as expected)
- When the route is **not** nested. (`/nested/songs` works as expected) 
- The search parameter is called `page` (any other name works as expected)
- The app is run in `dev`. After `npm run build` the bug disappears

### Reproduction

[Repo for reproduction](https://github.com/kenowi-dev/sveltekit-songs-page-bug)

1. Create a new SvelteKit app `npm create svelte@latest my-app`
2. `mkdir src/routes/songs`
3. `echo "SONGS" > src/routes/songs/+page.svelte`
4. `npm install && npm run dev`
5. Goto `http://localhost:5173/songs?page=3`
6. See the url change to `http://localhost:5173/songs?page=1`

### System Info

```Shell
WSL Setup: 

System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 7700 8-Core Processor
    Memory: 9.44 GB / 15.20 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
Binaries:
    Node: 19.7.0 - ~/.asdf/installs/nodejs/19.7.0/bin/node
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
```

### Severity

annoyance

### Additional Information

The Bug also occurred on a freshly install WSL (Ubuntu-22.04) instance with npm and node installed via nvm.

**Comment by Conduitry** [comment]
I can't reproduce this. I'm guessing that you've previously sent some 301 Moved Permanently redirects with a previous version of the app that have been cached in your browser. If you don't want the browser to cache these redirects, you need to use a different status code for the redirects.

**Comment by Quendall** [comment]
I know this is old, but I just wanted to add that 308 (Permanent Redirect) will also be cached by the browser. Use something like 303 or 307 instead ([see more statuses](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status#redirection_messages)). You can also add the `Cache-Control` header set to `no-store` in the response.

I figure this is probably pretty basic stuff in the web development world, but for noobs like me it might not be so obvious. It was a headache trying to figure out why my redirect wasn't working, and I am _very_ glad I found this answer :)
