### ISSUE TITLE
[FR] `event.cookies.getAll()` return value should be object, not array of objects. (bcs of following standard, let's make helper function instead changing API)

### ISSUE THREAD

**Issue by GabrielGorta** [sveltejs/kit#10748]
### Describe the problem

Today we have weird returned value when it comes to cookies.

code: `event.cookies.getAll()` returns

```json
[
    {
        "name": "token",
        "value": "xxx"
    }, 
    {
        "name": "something",
        "value": "blabla"
    }
]
```

This is really weird output, because to get specific cookie, we need to call:

`const token = cookies.find(c => c.name === "token")?.value;`

or transform it to object with reduce function or with (if we have one value per cookie, this doesn't handle multiple values in one cookie):

```js
const cookies = Object.fromEntries(event.cookies.getAll().map(c => [c.name, c.value]));
```

that gives us more usefull output (shorter and easier to work with):

```json
{
    "token": "xxx",
    "something": "blabla"
}
```

### Describe the proposed solution

Change API of `event.cookies.getAll()`, this is breaking change and we would need to wait until SvelteKit@2

I propose to change returned type from:

```ts
{
    name: string;
    value: string;
}[]
```

to

```ts
{ [name: string]: string }
```

or respecrively to handle multiple values in one cookie, we will have:

```ts
{ [name: string]: string | string[] }
```

### E: **AFTER @GrygrFlzr sent [MDN docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) about getAll method in JS itself, I think it's not good to change semantic of function, but we still can provide helper function, and there is plus to it, we can do it right away (no breaking change)**

```js
const cookies = somehelperfunction(event.cookies);
```

it would internally call `.getAll()` and use transforming to our desired type.

### Alternatives considered

Let it be as is... but even array of arrays would be easier to work with `Object.fromEntries` like pair of touples, instead of weird array of objects... but why not object itself?

### Importance

would make my life easier

**Comment by s3812497** [comment]
> [MDN docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll) about getAll method in JS itself, I think it's not good to change semantic of function, but we still can provide helper function, and there is plus to it, we can do it right away (no breaking change)

I think it might be best to match the browser standard for now and leave users to implement the helper function themselves.

**Comment by GabrielGorta** [comment]
How does helper function break standards? I think it can be part of Kit, same as sequence for example.

**Comment by s3812497** [comment]
The sequence helper function does a lot more than converting an array of objects into an object of arrays. It's also very specific to the framework.
