### ISSUE TITLE
TypeError: Cannot read private member #context from an object whose class did not declare it

### ISSUE THREAD

**Issue by tarasowski** [sveltejs/kit#10740]
### Describe the bug

Getting this error while running the npm run build command.

### Reproduction

Unfortunately, I'm unable to provide links to the files for reproduction. I initially worked with Sveltekit during its beta phase, and now, as I attempt to update the website, it consistently fails during the build process.

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 467.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.5.0 - /opt/homebrew/bin/node
    npm: 9.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.34 => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.347 
    svelte: ^3.42.6 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
There's nothing we can do to fix this if we don't have a minimal reproduction. I'm not sure whether there was ever a class with a private `#context` member in the SvelteKit codebase, but there isn't now.
