### ISSUE TITLE
Form action with server streaming promise

### ISSUE THREAD

**Issue by vine1993** [sveltejs/kit#10750]
### Describe the bug

First of all, im not sure if it is a bug, but I didnt find any other place to post this, so I'm sorry about that.

If you are working with streaming every time you submit the form actions the route is invalidated.
Im wondering if it is a bug or is something that I don't understand about the form actions or the streaming with promise.

### Reproduction

Create a project using sveltekit, on the routes create a **+page.svelte** with the following content.

```
<script>
    import { enhance } from "$app/forms";
      /** @type {import('./$types').PageData} */
      export let data;

</script>

<h1>Testing promise</h1>
{#await data.streaming.promise}
    <p>Loading promise...</p>
{:then data}
    <h4>Promise loaded</h4>
    <form action="?/testAction" use:enhance method="POST">
        <input type="text" name="name" />
        <input type="text" name="email" />
        <button type="submit">Submit form</button>
    </form>
{/await}

```
then create a new file at the same folder called **+page.server.js** with the following content

```
export async function load() {
    const promise = new Promise(resolve => {
        setTimeout(()=>{
            resolve(true)
        },3000) //3 seconds
    })
    return {
        streaming: {
            promise
        },
      }
}

export const actions = {
    testAction: async (event) => {
      const data = Object.fromEntries(await event.request.formData());
  
      return {sucess:true, data };
    },
  }
```
  
when you submit the form you will see the route being invalidated at the Chrome network tab
<img width="1439" alt="image" src="https://github.com/sveltejs/kit/assets/2659288/c1d087ad-2de2-4c6e-88b8-f792e9dec537">

that causes the streaming to run again and my form disappears.

### Logs

```Shell
No errors or warning occurs
```

### System Info

```Shell
Im running inside a docker image, the following content its from the container.  

System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (4) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 4.87 GB / 7.68 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /app/node_modules/.bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.18.0 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.8
```

### Severity

serious, but I can work around it

**Comment by s3812497** [comment]
> Without an argument, use:enhance will emulate the browser-native behaviour, just without the full-page reloads. It will:
> - reset the <form> element and invalidate all data using invalidateAll on a successful response

> To customise the behaviour, you can provide a [SubmitFunction](https://kit.svelte.dev/docs/types#public-types-submitfunction)
 that runs immediately before the form is submitted, and (optionally) returns a callback that runs with the [ActionResult](https://kit.svelte.dev/docs/types#public-types-actionresult). Note that if you return a callback, the default behavior mentioned above is not triggered. To get it back, call update.

https://kit.svelte.dev/docs/form-actions#progressive-enhancement-use-enhance

**Comment by vine1993** [comment]
thank you @fehnomenal and @s3812497 , i'll do a test right now with a custom submit function and check this.

**Comment by vine1993** [comment]
so, even running with a custom submit function I need to use the update methods, and this method invalidates the routes.
There is another way to call the updates without invalidate anything? i don't see any params in the docs.


```
<script>
    import { enhance,applyAction } from "$app/forms";
      /** @type {import('./$types').PageData} */
      export let data, form;

      console.log('form',form?.name)

</script>

<h1>Testing promise</h1>
{#await data.streaming.promise}
    <p>Loading promise...</p>
{:then data}
    <h4>Promise loaded</h4>
    <form action="?/testAction" use:enhance={({ formElement, formData, action, cancel }) => {

		return async ({ result,update }) => {
			// `result` is an `ActionResult` object
			if (result.type === 'error') {
				await applyAction(result);
			}
            update() //this invalidates the routes
		};
	}} method="POST">
        <input type="text" name="name" />
        <input type="text" name="email" />
        <button type="submit">Submit form</button>
    </form>
{/await}
```

**Comment by fehnomenal** [comment]
I think calling `applyAction` instead of `update ` will be correct as that won't invalidate iirc.

**Comment by vine1993** [comment]
@fehnomenal you are absolute right, do docs give you a few infos only, it was hard to understand what applyActions and updates do.  any way, than you.
