### ISSUE TITLE
Navigating between same slug does not change page content

### ISSUE THREAD

**Issue by manuel3108** [sveltejs/kit#1075]
**Describe the bug**
I'm currently having a problem with routs in sveltekit:
Lets assume I am on the page `/test/1234`. Lets also assume that from this page (`/test/1234`) there is a link to `/test/5678`.
File structure:
```
routes/
  test/
    [id].svelte
```
If i then navigate from  `/test/1234` with the button to  `/test/5678` the url changes but the content does not.

This is the source code of `[id].svelte`:
```jsx
<script>
    import { page } from '$app/stores';

    const { id } = $page.params;
</script>

<a href="/test/5678">5678</a>
{id}
```
Searched on github for similar issues, bot could not find anything. Did I miss something? Thanks for your thoughts

**Logs**
No logs in either the browser or the server console written.

**To Reproduce**
https://github.com/manuel3108/svelte-router-bug
```
git clone https://github.com/manuel3108/svelte-router-bug
cd svelte-router-bug
npm i
npm run dev
```
* Visit the start page (propably http://localhost:3000)
* Follow the link on the main page to `/test/1234`
* From there follow the link to to `/test/5678`

You will see that the url changed, but the content did not. So its still displaying the content from the last page `1234`

**Expected behavior**
After clicking the link to `/test/5678` i would expect the content of the page to display `5678`

**Stacktraces**
None

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
System:
    OS: Linux 5.9 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 4.70 GB / 15.64 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh

Binaries:
    Node: 15.12.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.7.6 - /usr/bin/npm

 Browsers:
    Chrome: 90.0.4430.72
    Firefox: 87.0

npmPackages:
    @sveltejs/kit: next => 1.0.0-next.78 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 
```

- Your browser
Chrome, Firefox

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Happens in `build` and in `dev` mode.
Adapter: `static`

**Severity**
`annoying` - I could not found a workaround

**Comment by Rich-Harris** [comment]
This isn't a bug. When you do `const { id } = $page.params` inside `<script>`, you're setting `id` to whatever the value of `$page.params.id` was when the component first initialised. When you navigate to a new URL, it will call the `load` function again (if one exists), and the value of `$page.params.id` will update, but the component isn't created anew.

**Comment by manuel3108** [comment]
Thanks for the quick help and the hint into the correct direction.

For anyone (including future me) stumbling around this, this seems to work:
```jsx
<script context="module">
	export async function load({ page }) {
		return {
			props: {
				id: page.params.id
			}
		};
	}
</script>

<script>
	export let id;
</script>

<a href="/test/5678">bsd</a>
{id}

```
