### ISSUE TITLE
Disabling SSR and prerendering causes CSS network requests to start later

### ISSUE THREAD

**Issue by shynome** [sveltejs/kit#10764]
### Describe the bug

~+page ssr disabled make +layout ssr disabled too.~

See https://github.com/sveltejs/kit/issues/10764#issuecomment-1731958634

### Reproduction

```sh
npm create svelte@latest layout-css-delayed-too
cd layout-css-delayed-too/
npm i -D @sveltejs/adapter-auto@npm:@sveltejs/adapter-static
echo '<slot /><style>:global(h1) {color: red;}</style>' > src/routes/+layout.svelte
echo 'export const prerender = true' > src/routes/+layout.ts
echo 'export const ssr = true' > src/routes/+page.ts
npm run build && cat build/index.html
# you can see stylesheet css here
echo 'export const ssr = false' > src/routes/+page.ts
npm run build && cat build/index.html
# now stylesheet css is gone
```

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 14.04 GB / 30.64 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.6.7 - /usr/bin/npm
    pnpm: 7.18.0 - /usr/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.88
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3 
    @sveltejs/kit: ^1.20.4 => 1.24.1 
    svelte: ^4.0.5 => 4.2.0 
    vite: ^4.4.2 => 4.4.9
```

### Severity

serious, but I can work around it

**Comment by s3812497** [comment]
Any options in `+page.js` will override `+layout.js`. You cannot have both at the same time.

However, I do think that the SSR option shouldn't influence how CSS is imported for a prerendered page. Currently, disabling SSR and prerendering causes the CSS network request to start much later than when SSR is enabled. 

Reproduction: https://stackblitz.com/edit/sveltejs-kit-template-default-hbkpn9?file=src%2Froutes%2F%2Blayout.js

**Comment by eltigerchino** [comment]
seems to have been fixed by https://github.com/sveltejs/kit/pull/10988 in [v1.27.4](https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fkit%401.27.4)

**Comment by shynome** [comment]
Cool, it's be fixed!
