### ISSUE TITLE
Support loading WASM in adapter-node

### ISSUE THREAD

**Issue by inzanez** [sveltejs/kit#10765]
### Describe the problem

Building an application with WASM using @sveltejs/adapater-node currently results in an error:
RollupError: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)

### Describe the proposed solution

A way to build wasm projects using 'adapter-node'

### Importance

would make my life easier

**Comment by shynome** [comment]
hi you can see here https://vitejs.dev/guide/features.html#accessing-the-webassembly-module
use `xxx.wasm?url` get wasm url then fetch it and init wasm module

**Comment by inzanez** [comment]
@shynome Not sure if this is what I need? I do get an error message from rollup when using the "adapter-node". It does not seem to be an issue from vite.
On the other hand: not sure how I could try what you describe. I have installed a package ('wasm-test') that includes the JS and wasm, and currently import it like this:
 `import { test_function } from 'wasm-test';`

I am not sure how I should remap that to what you describe,...

**Comment by inzanez** [comment]
```Development dependencies will be bundled into your app using [Rollup](https://rollupjs.org/). To control whether a given package is bundled or externalised, place it in devDependencies or dependencies respectively in your package.json.```

I moved the package containing the wasm module into `dependencies` and it seems to build. Still having some runtime issues though.
