### ISSUE TITLE
Use of snapshot causes additional page render

### ISSUE THREAD

**Issue by mickvangelderen** [sveltejs/kit#10773]
### Describe the problem

I have a page which contains a lot of html and takes 500ms to load. This is fine because it only needs to load once and then I can CTRL-F search through everything. 

I've added some client side filtering that is persisted through the snapshot feature. Unfortunately this makes it so the page renders once with the default filters first and then again with the restored filter which is a bad user experience.

### Describe the proposed solution

Think with me about how I can restore the filter state before the first render. 

### Importance

nice to have

**Comment by s3812497** [comment]
Please provide a minimal reproduction in the form of a downloadable code repository.
