### ISSUE TITLE
I would like to have several <slot name="..."/> in the +layout.svelte

### ISSUE THREAD

**Issue by Gorbulev-Sergey** [sveltejs/kit#10778]
### Describe the problem

Sometimes there is a need for a complex layout, and if I could insert several `<slot name="..."/>`  into it, it would be very cool.

### Describe the proposed solution

Multiple `<slot name="..."/>` in the layout.

### Alternatives considered

Thanks guys!

### Importance

would make my life easier

**Comment by coryvirok** [comment]
In case you haven't seen this long thread yet - https://github.com/sveltejs/kit/issues/627#issuecomment-1458539744

**Comment by Gorbulev-Sergey** [comment]
@coryvirok, i looked at the branch, thank you!
