### ISSUE TITLE
Providing HTTP Link headers for preloading

### ISSUE THREAD

**Issue by ion1** [sveltejs/kit#1077]
**Is your feature request related to a problem? Please describe.**
It is not really a problem, but it might be worth considering to provide HTTP Link headers equivalent to the \<link\> elements for preloading. That would allow the preloading to start before the HTML is being parsed. That would also allow HTTP 2+ servers to push the resources to the client.

**Describe the solution you'd like**
Something like the following in [render.js](https://github.com/sveltejs/kit/blob/7931209749a4dc781dd90197d5cd44ba7b2a39e0/packages/kit/src/runtime/server/page/render.js#L161):

```js
	headers['link'] = [
		...Array.from(js).map((dep) => `<${encodeURI(dep)}>; rel=modulepreload`),
		...Array.from(css).map((dep) => `<${encodeURI(dep)}>; rel=stylesheet`)
	];
```

(Depends on `headers` supporting array values, see [helper.d.ts](https://github.com/sveltejs/kit/blob/7931209749a4dc781dd90197d5cd44ba7b2a39e0/packages/kit/types/helper.d.ts#L13).)

**Describe alternatives you've considered**
An alternative would be to keep using the \<link\> elements alone for preloading.

**How important is this feature to you?**
Not very important, just a nice thing to have.

**Additional context**
[The specification for the Link header](https://tools.ietf.org/html/rfc8288#section-3).

**Comment by Rich-Harris** [comment]
We looked into this previously and determined it wasn't worthwhile: https://github.com/sveltejs/kit/issues/47#issuecomment-804540117

It may have a marginal effect when combined with server push, but that's basically [dead in the water](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1) (will be removed from Chromium as soon as they're able), so I'll close this — thanks
