### ISSUE TITLE
Auto-generated types improvements for actions and forms (opposit way)

### ISSUE THREAD

**Issue by gabrielgortabns** [sveltejs/kit#10781]
### Describe the problem

Hello, today if I return data in load or action functions, the type appear in data and form props. That's really nice. But would it be possible to do opposit? E.g. type appearing in FormData, based on form on client-side?

E.g. let's say we have:

`+page.svelte`:
```html
<form method="POST">
    <input type="text" name="employee">
    <input type="number" name="salary">
    <button>Submit</button>
<form>
```

`+page.server.js`:
```js
export const actions: {
    default: async ({ request }) => {
        const data = Object.fromEntries(await request.formData());
        //   ^^^^^ type: `{[k: string]: FormDataEntryValue}`
    }
}
```

### Describe the proposed solution

And instead of `{[k: string]: FormDataEntryValue}`, I would like to have:

```js
{
    employee: string;
    salary: number;
}
```

### Importance

would make my life easier

### Additional Information

I know this may be more tricky and harder to do (if not impossible), because of main two reasons:

- We would need to know that there are no dynamic elements in form, or otherwise, we would need to fallback to "generic" `{[k: string]: FormDataEntryValue}`, this may be hardest part.
- We would need to be carefull about method and action property (including named actions stuff)

**Comment by david-plugge** [comment]
There are way too many edgecases to consider. Taking the html as source of truth isnt a thing here. Take a look at [superforms](https://superforms.rocks/) to add types and validation to your forms instead.

**Comment by LorisSigrist** [comment]
Even with all the edge cases covered, this still wouldn't work. Form Actions are HTTP endpoints like any other, so we don't actually know what data will be passed to them. 

The Type inference described would falsely tell developers that the input has been sanitized. It hasn't.

I would recommend taking a look at SvelteKit Superforms

**Comment by GabrielGorta** [comment]
I think this has nothing to do with validations, it's just about types. Also, it's possible to implement type like:

```
{
    employee?: string;
    salary?: number;
    [key: string]: FormDataEntryValue
}
```

**Comment by david-plugge** [comment]
I get the intention but it's way too hard to implement. You need to know all form inputs at build time, maybe you are using deeply nested components to render these inputs. You would have to recursively traverse through all child components to find them.

You are better of doing it the other way around. Define the types and build the inputs around those types. And
