### ISSUE TITLE
jsconfig.json and tsconfig.json created

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1078]
I just created a new project answering "yes" to all questions at the prompt including TypeScript and it created both a `jsconfig.json` and `tsconfig.json` file

**Comment by Rich-Harris** [comment]
using the currently released `create-svelte@next`, or #1014?

**Comment by benmccann** [comment]
Using the current release. I just ran `npm init svelte@next`

**Comment by Rich-Harris** [comment]
then i think we can close this, it shouldn't be an issue in #1014
