### ISSUE TITLE
Generated types for PageData do not include types for LayoutData

### ISSUE THREAD

**Issue by trunkyredstone** [sveltejs/kit#10806]
### Describe the bug

When using server data on a page, the layout server data is available, but the generated "./$types" do not reflect that the layout server data exists, and will only have properties from the page server data. 

Layout data is still accessible, but typescript & IDE warnings are generated.

Assume the layoutData consists of `{"layoutData": "foo"}`, and the pageData consists of `{"pageData": "bar"}`.
The generated type will be `{pageData: string}`, but the page will be able to access both `pageData` and `layoutData` still.

I'd expect it to generate `{pageData: string, layoutData: string}`.

### Reproduction

This is the minimal code required to reproduce.

https://github.com/trunkyredstone/svelte-data-bug

The data will be logged in the console on the root page. Run as normal

### Logs

```Shell
The log produced is { layoutData: 'foo', pageData: 'bar' }. This is what the page receives in terms of data, but the types do not reflect this
```

### System Info

```Shell
System:
  OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 4.16 GB / 13.31 GB
  Container: Yes
  Shell: 5.2.15 - /bin/bash
Binaries:
  Node: 18.13.0 - /usr/bin/node
  npm: 9.2.0 - /usr/bin/npm
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
  @sveltejs/kit: ^1.20.4 => 1.25.1 
  svelte: ^4.0.5 => 4.2.1 
  vite: ^4.4.2 => 4.4.9
```

### Severity

annoyance

**Comment by Rishab49** [comment]
@trunkyredstone  In vscode it is working fine
![type](https://github.com/sveltejs/kit/assets/25582966/252867de-3b36-4801-9020-50c2aff12266)

**Comment by trunkyredstone** [comment]
@Rishab49 thank you, but a few things to note - I'm using TypeScript. Secondly, the issue is with the generated types file containing incorrect types.

**Comment by Rishab49** [comment]
@trunkyredstone apologies but after going though your code I found out that you are using `PageServerData` instead of `PageData` as type inside `+page.svelte`. Also my `$types` file is showing right types.

https://github.com/trunkyredstone/svelte-data-bug/blob/a8a84ea6a6362f28aee5b49f7a009143c546f60b/src/routes/%2Bpage.svelte#L4 

![types](https://github.com/sveltejs/kit/assets/25582966/30e0ee93-f085-4d6e-82f9-f2ea1c0b33ed)
