### ISSUE TITLE
Sveltekit very regular local build blocked by EPERM errors

### ISSUE THREAD

**Issue by MarArMar** [sveltejs/kit#10807]
### Describe the bug

Very often my local build or dev is blocked by the same "EPERM: operation not permitted, stat $types.d.ts" errors on Sveltekit build and sometime dev too

Error is : 

> EPERM: operation not permitted, stat .../.svelte-kit/ ... /$types.d.ts

Makes dev experience really not optimal, I often have to run the same command 2 or 3 times or close / repopen VSCode

### Reproduction
```Shell
npx turbo run dev --filter=SvelteKitProject --no-daemon --no-update-notifier

npx turbo run build --filter=SvelteKitProject --no-daemon --no-update-notifier
```

### Workaround

Seems to work for build but NOT for dev : 
```Shell
Remove-Item -Recurse -Force 'apps\WingMan\.svelte-kit' ; npx turbo run build --filter=SvelteKitProject --no-daemon --no-update-notifier
```

### Logs

```Shell
SvelteKitProject:build: error during build:
SvelteKitProject:build: Error: EPERM: operation not permitted, stat '[path]\TurboRepo\apps\SvelteKitProject\.svelte-kit\types\src\routes\$types.d.ts'
SvelteKitProject:build:     at Object.statSync (node:fs:1690:3)
SvelteKitProject:build:     at file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:95:22
SvelteKitProject:build:     at Array.map (<anonymous>)
SvelteKitProject:build:     at write_all_types (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:94:27)
SvelteKitProject:build:     at create (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/sync.js:32:8)
SvelteKitProject:build:     at Module.all (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:15)
SvelteKitProject:build:     at config (file:///[path]/TurboRepo/node_modules/.pnpm/@sveltejs+kit@1.25.1_svelte@4.2.1_vite@4.4.9/node_modules/@sveltejs/kit/src/exports/vite/index.js:298:34)
SvelteKitProject:build:     at runConfigHook (file:///[path]/TurboRepo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-df561101.js:66272:31)
SvelteKitProject:build:     at async resolveConfig (file:///[path]/TurboRepo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-df561101.js:65715:14)
SvelteKitProject:build:     at async build (file:///[path]/TurboRepo/node_modules/.pnpm/vite@4.4.9_@types+node@18.17.1/node_modules/vite/dist/node/chunks/dep-df561101.js:47852:20)
SvelteKitProject:build:  ELIFECYCLE  Command failed with exit code 1.
SvelteKitProject:build: ERROR: command finished with error: command ([path]\TurboRepo\apps\SvelteKitProject) pnpm run build exited (1)
SvelteKitProject#build: command ([path]\TurboRepo\apps\WingMan) pnpm run build exited (1)
```

### System Info

```Shell
System:
OS: Windows 10 10.0.19043
CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Memory: 3.72 GB / 15.74 GB
Binaries:
Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
pnpm: 8.8.0 - ~\AppData\Local\pnpm\pnpm.EXE
Browsers:
Edge: Spartan (44.19041.1266.0)
Internet Explorer: 11.0.19041.1566
npmPackages:
@sveltejs/adapter-auto: ^2.1.0 => 2.1.0
@sveltejs/kit: ^1.25.1 => 1.25.1
svelte: ^4.2.1 => 4.2.1
vite: ^4.4.9 => 4.4.9
```

### Severity

annoyance

### Additional Information

tsconfig is
```
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "paths": {
      "$src/*": ["./src/*"],
      "$lib": ["./src/lib"],
      "$lib/*": ["./src/lib/*"],
      "$components": ["./src/lib/components/*"],
      "$components/*": ["./src/lib/components/*"]
    }
  },
  "exclude": [
    "./node_modules/**",
    "./.svelte-kit/**",
    "./dist/**",
    "./build/**",
    "./.svelte/**",
    "./.vercel_build_output/**",
    "./.vercel/**",
    "./coverage/**",
    "**/_/**"
  ]
}
```

**Comment by MarArMar** [comment]
I would be VERY grateful for a workaround as this REALLY makes development harder

**Comment by MarArMar** [comment]
Just had 12 builds blocked in a row by this

**Comment by benmccann** [comment]
This doesn't happen to most users. It's probably because of your use of Turbo or something else specific to your setup

**Comment by MarArMar** [comment]
> This doesn't happen to most users. It's probably because of your use of Turbo or something else specific to your setup

Why would turbo cause this ?

thanks, it might help with solving it.

**Comment by benmccann** [comment]
No idea. It could be something else in your setup. I'm just saying it doesn't happen in SvelteKit projects generally. It seems like it'd be very easy for you to test if it's turbo or not by running the build without turbo and seeing if that fixes it.

**Comment by MarArMar** [comment]
Confirmed it was not a Turbo issue, reproduced the problem without Turbo

**Comment by MarArMar** [comment]
Update : Replaced tsconfig exclude with

```
  "exclude": [
    "**/node_modules/**",
    "**/.svelte-kit/**",
    "**/dist/**",
    "**/build/**",
    "**/.svelte/**",
    "**/.vercel_build_output/**",
    "**/.vercel/**",
    "**/coverage/**",
    "**/_/**",
    "**/vite.config.js.timestamp-*",
    "**/vite.config.ts.timestamp-*"
  ]
  ```
  
  I did not see the problem in the last day, pretty unusual, will keep this updated
  
  Maybe a linter or code analyser of some sort that conflicted with the dev / build process

**Comment by DanChristos** [comment]
I've seen similar EPERM errors after I do an npm update, I don't think it's sveltekit related. Usually just clearing the npm cache does the trick: `npm cache clean --force`.

**Comment by frederikhors** [comment]
This should be re-open, please @benmccann.

This is a Windows issue I think. I'm having it too sometimes:

```
Error: EPERM: operation not permitted, stat 'C:\project\.svelte-kit\types\src\routes\$types.d.ts'
    at Object.statSync (node:fs:1658:25)
    at file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.7.3_@sveltejs+vite-plugin-svelte@4.0.0_svelte@5.1.6_vite@5.3.3_@types+node@20_rpqevhwe6a2uvdqwcg3j2pcwgm/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:96:22
    at Array.map (<anonymous>)
    at write_all_types (file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.7.3_@sveltejs+vite-plugin-svelte@4.0.0_svelte@5.1.6_vite@5.3.3_@types+node@20_rpqevhwe6a2uvdqwcg3j2pcwgm/node_modules/@sveltejs/kit/src/core/sync/write_types/index.js:95:27)
    at create (file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.7.3_@sveltejs+vite-plugin-svelte@4.0.0_svelte@5.1.6_vite@5.3.3_@types+node@20_rpqevhwe6a2uvdqwcg3j2pcwgm/node_modules/@sveltejs/kit/src/core/sync/sync.js:34:2)
    at Module.all (file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.7.3_@sveltejs+vite-plugin-svelte@4.0.0_svelte@5.1.6_vite@5.3.3_@types+node@20_rpqevhwe6a2uvdqwcg3j2pcwgm/node_modules/@sveltejs/kit/src/core/sync/sync.js:58:9)
    at config (file:///C:/project/node_modules/.pnpm/@sveltejs+kit@2.7.3_@sveltejs+vite-plugin-svelte@4.0.0_svelte@5.1.6_vite@5.3.3_@types+node@20_rpqevhwe6a2uvdqwcg3j2pcwgm/node_modules/@sveltejs/kit/src/exports/vite/index.js:325:27)
    at runConfigHook (file:///C:/project/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:67013:25)
    at async resolveConfig (file:///C:/project/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:66464:12)
    at async build (file:///C:/project/node_modules/.pnpm/vite@5.3.3_@types+node@20.14.10_terser@5.36.0/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:65530:18)
```

Windows 11 latest, nodejs latest.

This happens if I start with `npm run dev` or `npm run build` and have VSCode open.

**Comment by frederikhors** [comment]
@MarArMar do you have updates about?

**Comment by frederikhors** [comment]
We work on Windows unfortunately. This happens many many times.

**Comment by jasonlyu123** [comment]
I would guess the permission error is because some other process has "locked" the file so other processes can't read it. The reason might be a file stream isn't properly closed, either it outright doesn't close it or there was an exception that left the stream hanging. As it's possible it could be caused by another program, you'll have to figure out what it's the problem yourself. You can try disabling stuff that is running while the error happens or google if there is a way to tell if any program locks the file.

**Comment by oriolmontcreus** [comment]
@frederikhors @jasonlyu123 
Im a bit late but I found a manual fix (of course it would be better if the issue wasnt there in the first place):
Windows 11 user here.  
I ran into this same issue before in a Svelte project (though I’m not exactly sure what triggers it).  
Here’s what worked for me:  

> [!NOTE]  
> This seems to be caused by a **permission issue** with the `.svelte-kit` folder.  
> The fix is to remove that folder — it will regenerate automatically, and you won’t lose any project data.

### Steps I took:
1. **Close all processes using the `.svelte-kit` folder.**  
   In my case, I used the [Microsoft PowerToys File Locksmith](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith) utility to identify and stop them:  

   <img width="276" height="51" alt="Image" src="https://github.com/user-attachments/assets/eea070b6-eb1d-4ee3-b553-3b0a49f07448" />  

   <img width="819" height="192" alt="Microsoft " src="https://github.com/user-attachments/assets/f75af089-6cab-44e9-817f-93e7c5d57222" />  

2. **Delete the `.svelte-kit` folder.**  
   Once no processes were locking it, I was able to remove it without issues.  

3. **Delete `node_modules` and reinstall dependencies**:  
   ```sh
   rm -rf node_modules
   npm install

4. Finally, I was able to run commands like:

   ```sh
   npm run dev
   ```

**Comment by MarArMar** [comment]
NB : For some reason since switching to Linux I do not have this error anymore so it seemed to be Windows specific.
