### ISSUE TITLE
# Add `data` prop - quick-and-dirty migration

### ISSUE THREAD

**Issue by andreivreja** [sveltejs/kit#10800]
Suggesting a small change to your post here https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3292707_

```
export let data;
let { foo, bar } = data;
$: ({ foo, bar } = data); // so it stays in sync when `data` changes
```

This triggers every time one of the props changes. Expected behavior would be for it to trigger when `data` changes. Definitely appreciate the quick hack, saved me tons of time. Here's an alternative I'm proposing that fixes the issue I mentioned.

```
export let data;
let { foo, bar } = data;
const syncData = (d) => ({ foo, bar } = d);
$: syncData(data);
```

People should obviously just move to the new format, but in the meanwhile, this should prevent others from spending hours debugging incompatible setups.

**Comment by andreivreja** [comment]
CC @Rich-Harris in case it gets buried over time.

**Comment by s3812497** [comment]
> This triggers every time one of the props changes.

I'm not so sure this is the current behaviour. It only tracks when `data` is re-assigned and not the object properties.
