### ISSUE TITLE
Sveltekit always writes production env variables inside index.html 

### ISSUE THREAD

**Issue by fen89** [sveltejs/kit#10801]
### Describe the bug

I am really struggeling to get the `mode` flag to work for different builds for different environments (dev, staging, test, production). 
The build always ends up with using the variables from the `env.production` file.

### Reproduction

I have the following structure:

.env-file
```
PUBLIC_API=env
```

.env.staging
```
PUBLIC_API=staging
```

.env.production
```
PUBLIC_API=production
```

package.json

```
"build:staging": "vite build --mode staging",
```

### Logs

```Shell
No matter what if I run the command `npm run build:staging` vite is telling me that it is using the mode flag: `vite v4.3.9 building for staging...`
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 9.53 GB / 31.95 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-static: ^2.0.2 => 2.0.2
    @sveltejs/kit: ^1.20.0 => 1.20.0
    svelte: ^3.59.1 => 3.59.1
    vite: ^4.3.9 => 4.3.9
```

### Severity

annoyance

### Additional Information

 I always get the following output inside the generated index.html file:

```html
__sveltekit_1wnehg = {
    base: "",
    env: { "PUBLIC_API": "production" }
};
```

It is ignoring the mode flag completely inside the build. 

Any idea what I am missing here or is this indeed a bug? 

UPDATE:

**The build is using indeed after double checking the correct environment variables inside the SPA**. But why are there the env variables for the production environment always written to the index.html if the have no effect?

UPDATE 2:

**I checked the build files and found out about the `public.js` (inside the server folder)**, which is indeed using the correct env variables.

```
const PUBLIC_API="staging";
export {
  PUBLIC_API as P,
};
```

When I search through the generated js files I can indeed only find the env variables from the correct build mode!

**Comment by Rishab49** [comment]
hey @fen89 I think as doc explains [here](https://kit.svelte.dev/docs/modules#$env-dynamic-public:~:text=includes%20variables%20that-,begin%20with%20config.kit.env.publicPrefix%20(which%20defaults%20to,)%2C%20and%20can%20therefore%20safely%20be%20exposed%20to%20client%2Dside%20code.,-Note%20that%20public) that key starting with `publicPrefix` will get exposed to client side code hence you find it in built source code.

**Comment by s3812497** [comment]
Please provide a minimal reproduction in the form of a code repository.

**Comment by fen89** [comment]
> hey @fen89 I think as doc explains [here](https://kit.svelte.dev/docs/modules#$env-dynamic-public:~:text=includes%20variables%20that-,begin%20with%20config.kit.env.publicPrefix%20(which%20defaults%20to,)%2C%20and%20can%20therefore%20safely%20be%20exposed%20to%20client%2Dside%20code.,-Note%20that%20public) that key starting with publicPrefix will get exposed to client side code hence you find it in built source code.

@Rishab49 yes, but my point is that the exposed variables to the client are always in prod mode and only visible inside the index.html and not used at all in the project.

> Please provide a minimal reproduction in the form of a code repository.

 @s3812497  Sure, repo can be found here: https://github.com/fen89/svelte-env-demo (using SPA mode with prerender = false, ssr = false and adapter-static)

Steps to reproduce:

- npm run build:staging
- npm run preview

correct env variable is displayed:

![image](https://github.com/sveltejs/kit/assets/4036376/c644ef28-d13e-4b28-9d07-c16c1aaac1fd)

check the source code of the index.html:

![image](https://github.com/sveltejs/kit/assets/4036376/0a844447-d33a-4177-af21-df50ac361cc6)

Note: these values are NOT used as we saw above, but they are written to the index.html - and imho they shouldn't.

Please let me know if you need any additional information.

**Comment by MarkusWendorf** [comment]
@fen89 this issue seems to be related to this line: https://github.com/sveltejs/kit/blob/8b759b80f9f96f8c6f9bde7441e9b9ea67cf825f/packages/kit/src/core/adapt/builder.js#L147-L152

I do not know why this is hardcoded to be `production` though. And it wasn't immediately clear to me how I would access the VITE MODE inside the `generateFallback` method.

**Comment by MarkusWendorf** [comment]
This could fix the issue: https://github.com/sveltejs/kit/compare/master...MarkusWendorf:kit:master

I'm still not sure why it was hardcoded to `production` in the first place. Was this an oversight or intentional?

**Comment by eltigerchino** [comment]
> This could fix the issue: [master...MarkusWendorf:kit:master](https://github.com/sveltejs/kit/compare/master...MarkusWendorf:kit:master)
> 
> I'm still not sure why it was hardcoded to `production` in the first place. Was this an oversight or intentional?

I’m not sure but I would guess it’s an oversight. Would you like to submit a PR with a test for that?
