### ISSUE TITLE
Updating title from +layout.svelte fails after 404

### ISSUE THREAD

**Issue by Antonio-Bennett** [sveltejs/kit#10810]
### Describe the bug

If you have a dynamic title in your `+layout.svelte` file. Where you might have something like 
```svelte
<svelte:head>
	<title>{$page.data.title || "Default"}
</svelte:head>
```
where title is returned from the page load function.

After 404'ing unless you navigate to a page that explicitly sets it title via it's load function or `svelte:head`. The title will still stay as 404 when navigating to subsequent pages that do not return title. So it seems like `|| "Default"}` never gets hit after 404'ing. It works as expected before a 404.

### Reproduction

https://www.sveltelab.dev/g9belf05056nzaf

At `/` you see that the title is `Repro - Home` when you navigate to `en-CA` or `en-CA/category/1` you see that the title is `Default` however from the route `en-CA` when you click on `invalid Category` we get the expected `404` but when clicking back on `category 1` from the `404` page. We do not get the `Default` title. If you navigate back with arrow keys in browser and then click `home` which has an explicit title it updates title back to `Repro - Home`

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.44 GB / 15.50 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 20.6.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.7.6 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.132
  npmPackages:
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/kit: ^1.25.1 => 1.25.1
    svelte: ^4.2.1 => 4.2.1
    vite: ^4.4.9 => 4.4.9
```

### Severity

annoyance

### Additional Information

To my knowledge this has SEO implications for pages that are valid but have a 404 title

**Comment by s3812497** [comment]
This is more of an issue with Svelte than it is SvelteKit. In the 404 page, you've replaced the `<title>` element from the layout. It will remain as 404 until the layout `<title>` element is updated. When navigating from `/404` to `/category/1` there is no update because the evaluation inside the layout `<title>` element is `"Default"` for both pages. However, navigating to `/` updates the `<title>` element  because the value changes from `"Default"` to `$page.data.title`.

Closing this issue as it cannot be fixed from SvelteKit's side.

**Comment by Antonio-Bennett** [comment]
@s3812497 Ah okay it just clicked for me to use the `$page.error` object to check to see if there any errors and if so display the title as `$page.status` otherwise `$page.data.title` or `"Default"` if that is undefined. Is that the recommended approach so we don't have to manipulate `title` in `+error.svelte` ?
