### ISSUE TITLE
Deploying static site leads to MIME type errors where script fails to load and website does not render.

### ISSUE THREAD

**Issue by yoitsyoung** [sveltejs/kit#10814]
### Describe the bug

Hi there, 

I'm attempting to deploy a static website to github pages using 
`@sveltejs/adapter-static": "^2.0.3. `

I use the standard `static.yml` build process via Github actions, as detailed in vite's documentation. All source files and directories appear to be correctly configured (no more 404 errors, and I can access them on the webpage). 

However, I keep getting specifically this error which results in a blank page. I specifically get two of these errors, for app.css and App.svelte. The error can be reproduced by going to the website. My repository is 
https://github.com/beans-sprockets/beans-sprockets.github.io

### Reproduction

Website is at https://beans-sprockets.github.io/ 

### Logs

```Shell
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 60.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.2
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
It looks like what's been deployed is your original uncompiled source files. It also looks like you're simultaneously trying to write a SvelteKit app and trying to write a Vite+Svelte-only app. Your `vite.config.js` is not loading the required SvelteKit plugin.

Please direct support questions to our Discord server.
