### ISSUE TITLE
alias cause error, loading css file from svelte file  inside alias folders 

### ISSUE THREAD

**Issue by ravarage** [sveltejs/kit#10815]
### Describe the bug

I want to load css file from components  inside alias folder, when I ```run dev``` it work as it expected, but I build it and run on cloadflare pages I notice it wont load css file, so I build it on local using auto adapter and cloadflare adapter using ``` run build``` and ``` run preview``` and the issue I saw on cloadflare page appear on my local as well, it work well as expected in run dev but not on build 

### Reproduction

```js 
# svelte.config.js
...
	alias: {
			$components: 'src/components/*',

		}
...
```
```js
#  components/clinic/dashboard/mycard.svelte
    import 'flatpickr/dist/flatpickr.css';
```

### System Info

```Shell
System:
    OS: Linux 6.5 Garuda Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 15.29 GB / 31.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.1.0 - /usr/bin/npm
    pnpm: 8.8.0 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.0 => 2.1.0 
    @sveltejs/adapter-cloudflare: ^2.3.3 => 2.3.3 
    @sveltejs/adapter-cloudflare-workers: ^1.1.4 => 1.1.4 
    @sveltejs/kit: ^1.25.0 => 1.25.1 
    svelte: ^4.2.0 => 4.2.1 
    vite: ^4.4.9 => 4.4.9
```

### Severity

blocking an upgrade

**Comment by gtm-nayan** [comment]
Please provide a proper reproduction for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — do NOT just paste a link to your project. 

An incomplete description of the reproduction is not enough.

**Comment by ravarage** [comment]
I dont know what caused it, and what fixed it but damn cache didnt allow me to see its working fine my apologizes
