### ISSUE TITLE
Over-eager client-side redirect loop detection

### ISSUE THREAD

**Issue by moatra** [sveltejs/kit#10838]
### Describe the bug

Currently the client side navigation mechanism checks to see if the target pathname is already present in the redirect chain, and if so immediately throws an error that a redirect loop has been detected.  However, it's possible that navigating to that pathname will now succeed due to side effects of a previous navigation.

## Desired Behavior

I'm not sure the actual algorithm that browsers use to detect redirect loops, but I would imagine one of the following would be an improvement.

* If a pathname is already in the redirect chain, give it one last chance to return a non-redirect response before throwing a redirect loop error
* Track pairs of (from_pathname, to_pathname) to determine if a redirect loop is present.

### Reproduction

https://github.com/moatra/sveltekit_redirect

### Server Side Rendering
Works as expected
* Clear `my_cookie` if present
* Load `localhost:5173/foo`

Redirects work, navigating to `/set_my_cookie` and then back to `/foo` which can now use the cookie value.

### Client Side Rendering
Errors
* Clear `my_cookie` if present
* Load `localhost:5173/`
* Click the `/foo` link

Client errors

### System Info

```Shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 6.5 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 31.58 GB / 62.68 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.25.1 
    svelte: ^4.0.5 => 4.2.1 
    vite: ^4.4.2 => 4.4.11 
```

### Severity

serious, but I can work around it

**Comment by moatra** [comment]
I'm definitely not an expert in Gecko/Chromium, but best as I can tell:

### Gecko
Uses [`NS_ERROR_REDIRECT_LOOP`](https://github.com/search?q=repo%3Amozilla%2Fgecko-dev+NS_ERROR_REDIRECT_LOOP&type=code) to signal problematic redirects, which afaict is only returned in [`CheckRedirectLimit`](https://github.com/mozilla/gecko-dev/blob/59a514abdf5a675d33bfb5ce03dbbf8a2125d7f5/netwerk/protocol/http/HttpBaseChannel.cpp#L5871), which only checks the count against a constant of [`10`](https://github.com/mozilla/gecko-dev/blob/59a514abdf5a675d33bfb5ce03dbbf8a2125d7f5/netwerk/protocol/http/nsHttpHandler.h#L601)

### Chromium
Uses [`ERR_TOO_MANY_REDIRECTS`](https://github.com/chromium/chromium/blob/b245417f97f973f90db376322023ec8e4e338d00/net/base/net_error_list.h#L581)  to signal problematic redirects, which afaict is only returned in [`CanFollowRedirect`](https://github.com/chromium/chromium/blob/b245417f97f973f90db376322023ec8e4e338d00/net/url_request/url_request_job.cc#L710), which only checks if there's any "redirect budget" remaining.  The budget is initialized to [`20`](https://github.com/chromium/chromium/blob/15e7fdfb98b923efe27a2664faf62ab305c32b87/net/url_request/url_request.h#L93).

### Fetch Spec
The Chromium source included a helpful pointer to the [WhatWG Fetch Spec](https://fetch.spec.whatwg.org/#http-redirect-fetch):
> 7. If request’s [redirect count](https://fetch.spec.whatwg.org/#concept-request-redirect-count) is 20, then return a [network error](https://fetch.spec.whatwg.org/#concept-network-error).

### WebKit
Had a harder time grep-ing through the code base, but it looks like there are two [different](https://github.com/WebKit/WebKit/blob/bea72c4ddf242c392ba6e76d8294fc1a24f5efbc/Source/WebKit/NetworkProcess/NetworkLoadChecker.cpp#L153-L155) [checks](https://github.com/WebKit/WebKit/blob/bea72c4ddf242c392ba6e76d8294fc1a24f5efbc/Source/WebKit/NetworkProcess/curl/NetworkDataTaskCurl.cpp#L331-L336) for redirect loops, both of which use a constant of 20 maximum redirects.


## Conclusion
I didn't find any hint of "check if the new url or path is in a list of previous redirect targets" logic in the above codebases.  While hardly conclusive, I think it'd be safe to remove the "check for the pathname is navigation chain" logic from sveltekit's client.js, and just  rely on the count limit.

**Comment by thoughtspile** [comment]
I quite like @moatra approach here, fixes both our problems and simplifies the code! @benmccann what do you think?
