### ISSUE TITLE
prevent onDestroy

### ISSUE THREAD

**Issue by mkazar** [sveltejs/kit#10830]
### Describe the problem

if we search a word and get result list, if I click on a result a new page is opened, when I click on back button, the result list is disappeared and page is refreshed

### Describe the proposed solution

I want to prevent ondestroy when page changed. 

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment]
Could you clarify what you mean by that? Do you want to prevent the user to go back (use `beforeNavigate` for this)? If not, what exactly should be prevented from being destroyed (if you change pages, it's expected that the contents of the previous page are destroyed)?

**Comment by Rishab49** [comment]
I think this feature is work in progress https://github.com/sveltejs/kit/pull/9847
