### ISSUE TITLE
"locals" not getting passed

### ISSUE THREAD

**Issue by buhodev** [sveltejs/kit#10833]
### Describe the bug

Idk if I'm doing something wrong, but setting locals.user inside hooks and then retrieving it from +layout.server.js or +page.server.js doesn't work.

### Reproduction

https://github.com/buhodev/repro-locals-not-working

### System Info

```Shell
System:
  OS: Windows 10 10.0.22621
  CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
  Memory: 871.74 MB / 7.33 GB
Binaries:
  Node: 18.15.0 - ~\AppData\Local\Volta\tools\image\node\18.15.0\node.EXE
  npm: 9.5.0 - ~\AppData\Local\Volta\tools\image\node\18.15.0\npm.CMD
  pnpm: 8.6.5 - C:\Program Files\Volta\pnpm.EXE
Browsers:
  Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.47)
  Internet Explorer: 11.0.22621.1
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
  @sveltejs/kit: ^1.25.1 => 1.25.1
  svelte: ^4.2.1 => 4.2.1
  vite: ^4.4.11 => 4.4.11
```

### Severity

annoyance

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs/hooks Hooks go in `src`, not `src/routes`. Your `handle` hook isn't being run at all.
