### ISSUE TITLE
Disabling SSR prevents form actions from returning data

### ISSUE THREAD

**Issue by angrytongan** [sveltejs/kit#10846]
### Describe the bug

Disabling `ssr` prevents form actions from returning anything meaningful. I thought it might be possibly related to #10022, but this happens in a production build as well as dev.

To repoduce:
```shell
% git clone https://github.com/angrytongan/sveltekit-ssr-form-actions
% cd sveltekit-ssr-form-actions
% num install && npm run dev
# connect browser to localhost:5173
```

Type anything into the text field and submit; the client should receive the text you sent, but receives nothing. `form` is null.

Change `ssr` to `true` in `src/routes/+layout.server.ts`. Enter some text, submit the form; now you see a proper response.

Same behaviour witnessed with a production build using `npm run build` and `npm run preview` with the node adapter.

### Reproduction

https://github.com/angrytongan/sveltekit-ssr-form-actions

### System Info

```Shell
System:
    OS: macOS 12.7
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 519.36 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    pnpm: 8.8.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 17.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.20.4 => 1.25.1 
    svelte: ^4.0.5 => 4.2.1 
    vite: ^4.4.2 => 4.4.11
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Add `use:enhance` to the form and it should work.
The reason it doesn't work in your reproduction is because without `use:enhance` the form post results in a full page reload, but because SSR is disabled, this just results in in a blank page reload.
