### ISSUE TITLE
`use:enhance` does not emulate native browser behaviour of redirecting to the action

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#10847]
### Discussed in https://github.com/sveltejs/kit/discussions/10842

Native form submission always navigates to the route specified in the form `action` attribute. However, `use:enhance` doesn’t reflect this since it only navigates to another page if you explicitly throw a redirect in your action in `+page.server.js`.

We should document this in https://kit.svelte.dev/docs/form-actions#progressive-enhancement-use-enhance

Another thing we could document is how to emulate the navigation to the `action` route after a successful response with a `goto` call https://kit.svelte.dev/docs/modules#$app-navigation-goto
```svelte
<form
  action="/somewhere/else"
  method="post"
	use:enhance={({ formElement, formData, action, cancel }) => {

		return async ({ result }) => {
			// emulate native browser form redirect
			if (result.type === "success") {
				await goto(action);
			}
			await applyAction(result);
		};
	}}
>
  <button type="submit">
    Submit
  </button>
</form>
```

**Comment by krish-italiya** [comment]
Can I solve it ?

**Comment by geodask** [comment]
It’s been a while since this issue was last discussed. Would it be okay if I take this on and submit a PR?

**Comment by paoloricciuti** [comment]
This is a duplicate of #9999 and if you read in that thread there was a discussion about why this was implemented this way. I still agree that we should opt out rather than opt in to browser behavior.

**Comment by eltigerchino** [comment]
Thanks Pablo. Closing this as a duplicate of https://github.com/sveltejs/kit/issues/9999
