### ISSUE TITLE
Allow adapter-node to set extra response headers (e.g., X-Frame-Options)

### ISSUE THREAD

**Issue by rjwalters** [sveltejs/kit#10865]
### Describe the problem

In order to improve the security of websites built using SvelteKit and deployed using the adapter-node, I would like to have the ability to set specific security-related HTTP response headers, like `X-Frame-Options`. Setting this header helps mitigate clickjacking attacks by instructing the browser to not display the content in a `<frame>`, `<iframe>`, `<embed>`, or `<object>`.

While some other methods exist for setting this header at the route level within SvelteKit having a centralized way to set this header (and potentially others) directly within the adapter would provide a more consistent and straightforward approach for developers.

This would reduce the risk of developers forgetting to set this header on specific routes and ensure a uniform security policy across the entire application.

### Describe the proposed solution

I suggest enhancing the adapter configuration to include an option for setting custom response headers. This would allow developers to specify headers like `X-Frame-Options` once, ensuring they're added to every response the server sends.

Example configuration:

``` javascript
import adapter from '@sveltejs/adapter-node';

export default {
  kit: {
    adapter: adapter({
      responseHeaders: {
        'X-Frame-Options': 'DENY',
        // ... other headers
      }
    })
  }
};
```

### Alternatives considered

**Route-level Headers**: One could set the header at each route using SvelteKit's load function. However, this is error-prone as developers might forget to include the header in every route, leading to inconsistencies.

**Environment Variable Configuration**: Another approach would be to use environment variables, since the code already supports a few other headers this way (ADDRESS_HEADER/PROTOCOL_HEADER/HOST_HEADER)

We could introduce a new environment variable such as EXTRA_RESPONSE_HEADERS. Developers can then specify desired headers and their values in this variable. The adapter-node would then parse these headers and add them to every response it sends. For example:

``` javascript
const extra_response_headers = env('EXTRA_RESPONSE_HEADERS', '').toLowerCase();

/** @type {import('polka').Middleware} */
const ssr = async (req, res) => {
    // ... previous code ...

    // Set extra headers here based on parsed EXTRA_RESPONSE_HEADERS value
    // ...
}
```

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Another place for this would be https://kit.svelte.dev/docs/hooks#server-hooks-handle which is what I would recommend because it wouldn't be adapter-specific but it would still apply to every response from your application. Is there a reason this doesn't work for you?

**Comment by rjwalters** [comment]
that'll work - thanks.
