### ISSUE TITLE
run `git init` etc automatically when new project is created?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1087]
See discussion on #1036. Personally I think it's far better to print the instructions than to take any action on behalf of the user:

```diff
Next steps:
  1: cd foo
-  2: npm install (or pnpm install, or yarn)
-  3: npm run dev -- --open
+  2: git init && git add -A && git commit -m 'Initial commit'
+  3: npm install (or pnpm install, or yarn)
+  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat
```

I think it's probably ok to assume the developer has `git` installed if they've already used `npx`. If not, I don't know that this is the right place to teach them.

**Comment by GreenRobot777** [comment]
Yes, it is very important for many newers.
It is small thing, but even skilled users often forgot this step and first init changes was mixed with later app changes.

This is not mandatory step (skilled users will understand fast, if they will want skip this step), and this is promotes good practice.
That is well consistent with Svelte's general philosophy ;)

PR #1115 for apply this suggestion
