### ISSUE TITLE
Reassigning variables/reactive declarations breaks reactivity on other instances of the component

### ISSUE THREAD

**Issue by retr0cube** [sveltejs/kit#10903]
### Describe the bug

Hi,
I have a `PostMenu` component attached to  a list of posts (via for loop), and the component has a reactive like button that updates with on:click.
But the problem is that when there are multiple instances of the same component the reactivity breaks on all of them except the last one that stays reactive.

### Reproduction

Repo https://github.com/Msharfin/app precisely `src/routes/(app)/app/+page.svelte` and `src/lib/components/PostMenu.svelte`

- `npm run dev`
- go to the route where the component is initialized `/app`
- list more than 1 post element
(This should break reactivity on all instances of the component except the last one)

### System Info

```Shell
This happens locally and on production (vercel), so I don't really see if system info is important in this scenario.
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Please provide a minimal reproduction, as requested in the issue template, not just a link to your project.

**Comment by retr0cube** [comment]
> Please provide a minimal reproduction, as requested in the issue template, not just a link to your project.

Done. Please refer to the original issue

**Comment by retr0cube** [comment]
> Please provide a minimal reproduction, as requested in the issue template, not just a link to your project.

Any updates?

**Comment by s3812497** [comment]
This is not a minimal reproduction (it’s still a link to your project). It makes it difficult to find the code that causes the reproduces the issue. Also, the page mentioned in the reproduction steps does not use the component PostMenu

**Comment by retr0cube** [comment]
> This is not a minimal reproduction (it’s still a link to your project). It makes it difficult to find the code that reproduces the issue. Also, the page mentioned in the reproduction steps does not use the component PostMenu

So go to /app with the following conditions for the above bug to happen:
- Query more than 1 post

That's it and the last component should break other instances of it self

**Comment by s3812497** [comment]
> list more than 1 post element
(This should break reactivity on all instances of the component except the last one)

Please clarify this. How do I list more than 1 post element? What do you mean by reactivity breaking? What is the expected result and the actual result? (e.g., button should be green but is actually red.) Can you only reproduce this in SvelteKit or does it also break in a Svelte repl?

**Comment by retr0cube** [comment]
> > list more than 1 post element
> > (This should break reactivity on all instances of the component except the last one)
> 
> Please clarify this. How do I list more than 1 post element? What do you mean by reactivity breaking? What is the expected result and the actual result? (e.g., button should be green but is actually red.) Can you only reproduce this in SvelteKit or does it also break in a Svelte repl? (SvelteKit issue vs Svelte issue)

Hey! I think I know what's the issue (In my case, you'll see why later);

It looks like when you pass data into a component that is inside a loop, like the following:
```svelte
<script> 
  import SomeComponent from "/..."

  let i = [1,2,3]
</script>

{#each i as j}
  <SomeComponent {j}/>
{/each}
```
On rendering, the above process goes like this
```js
// first instance of the component
let j = 1
// second instance ...
let j = 2
let j = 2
// third instance ...
let j = 3
let j = 3
let j = 3
```
So the last component reassigns the value of all previous values to its own value (which is a big deal in some cases, when you want to add a component and pass data to it), But this [REPL ](https://svelte.dev/repl/1ca56287f57642658198598d8e83de43?version=4.2.2)doesn't confirm my suspicions! So is something wrong with my code?

**Comment by retr0cube** [comment]
> > > list more than 1 post element
> > > (This should break reactivity on all instances of the component except the last one)
> > 
> > 
> > Please clarify this. How do I list more than 1 post element? What do you mean by reactivity breaking? What is the expected result and the actual result? (e.g., button should be green but is actually red.) Can you only reproduce this in SvelteKit or does it also break in a Svelte repl? (SvelteKit issue vs Svelte issue)
> 
> Hey! I think I know what's the issue (In my case, you'll see why later);
> 
> It looks like when you pass data into a component that is inside a loop, like the following:
> 
> ```svelte
> <script> 
>   import SomeComponent from "/..."
> 
>   let i = [1,2,3]
> </script>
> 
> {#each i as j}
>   <SomeComponent {j}/>
> {/each}
> ```
> 
> On rendering, the above process goes like this
> 
> ```js
> // first instance of the component
> let j = 1
> // second instance ...
> let j = 2
> let j = 2
> // third instance ...
> let j = 3
> let j = 3
> let j = 3
> ```
> 
> How did I know this? `console.log()`'ing the ID of a post it when in `on:click` callback shows the last's one, but `console.log()`'ing the value on render prints the correct ID.
> 
> So the last component reassigns the value of all previous values to its own value (which is a big deal in some cases, when you want to add a component and pass data to it), But this [REPL ](https://svelte.dev/repl/1ca56287f57642658198598d8e83de43?version=4.2.2)doesn't confirm my suspicions! So is something wrong with my code or my sveltekit install broken?

This however doesn't break the functionality (it likes/dislikes correctly), but the UI's broken

**Comment by eltigerchino** [comment]
> is something wrong with my code or my sveltekit install broken?

You'll need to provide a minimal reproduction of this occurring in Svelte / SvelteKit.

> But this [REPL ](https://svelte.dev/repl/1ca56287f57642658198598d8e83de43?version=4.2.2)doesn't confirm my suspicions! So is something wrong with my code or my sveltekit install broken?

At a glance, I believe it has something to do with how `supadb` is being used to update the variables in your component. I'll close this issue for now as it can't be reproduced.
