### ISSUE TITLE
Cannot find module '@sveltejs/adapter-node'

### ISSUE THREAD

**Issue by bastinald** [sveltejs/kit#1093]
**Describe the bug**
clean install of the sveltekit demo produces an error when attempting to run

**Logs**
> bastinald@Kevins-MacBook-Pro llc-app % npm run dev
> 
> > ~TODO~@0.0.1 dev
> > svelte-kit dev
> 
> Cannot find module '@sveltejs/adapter-node'
> Require stack:
> - /Users/bastinald/Sites/llc-app/svelte.config.cjs
> Error: Cannot find module '@sveltejs/adapter-node'
> Require stack:
> - /Users/bastinald/Sites/llc-app/svelte.config.cjs
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:769:27)
>     at Module.require (node:internal/modules/cjs/loader:996:19)
>     at require (node:internal/modules/cjs/helpers:92:18)
>     at Object.<anonymous> (/Users/bastinald/Sites/llc-app/svelte.config.cjs:1:14)
>     at Module._compile (node:internal/modules/cjs/loader:1092:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
>     at Module.load (node:internal/modules/cjs/loader:972:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:201:29)

**To Reproduce**
```
npm init svelte@next my-app
cd my-app
npm install
npm run dev
```

select the `demo`, not the `skeleton` when installing

**Expected behavior**
the app to build and open in my browser

browser = chrome

**Comment by AndrewEQ** [comment]
Hi guys, just had a similar error from "vanilla building" today:

`Cannot find package '@sveltejs/adapter-node`

To reproduce (I have tried this with both skeleton and demo project):
```
npm init svelte@next web

My selected options were:
TypeScript: Yes
ESLint: Yes
Prettier: Yes
Playwright: No

cd web
npm install
npm run build
```

This produced: 
```
Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
```

So I replaced 
``` 
import adapter from '@sveltejs/adapter-auto';

adapter: adapter()
``` 
with: 
```
import adapter from '@sveltejs/adapter-node';
 
adapter: adapter({ out: 'production' }),
```

Reran:

`npm run build`

but still got the error:

`Cannot find package '@sveltejs/adapter-node`

then tried to run:

`npm install`

and got same error:

```
> web@0.0.1 prepare
> svelte-kit sync

> Cannot find package '@sveltejs/adapter-node' ...
```

Environment:
npm: 8.1.2
node: v16.13.1
macOS: 12.2.1 (21D62)
M1

**Comment by centratelemedia** [comment]
I have same problem, problem solve by install:

```
npm i -D @sveltejs/adapter-node@next
```

**Comment by ThomasMeli** [comment]
I would imagine that "auto" would solve this problem automatically, as its name suggests so that one could npm run build right out of the box without a problem.  Is there a reason why adapter-node isn't installed by default?

**Comment by rogadev** [comment]
I'm still having this problem today. 🤷‍♂️
It still runs and I can test locally, it's just an annoyance. Do I really have to switch back to `adapter-auto` if I want the error messages to go away?

**Comment by KyahWill** [comment]
I did a clean reinstall of the node packages and restarted VSCode and it worked for me.

**Comment by H3lel** [comment]
```
npm install -D @sveltejs/adapter-static 
````
this worked for me
