### ISSUE TITLE
Add GitHub Discussions

### ISSUE THREAD

**Issue by nico-bachner** [sveltejs/kit#1094]
GitHub Issues are a great way to track issues about SvelteKit itself, but are perhaps not the best tool for help about *using* SvelteKit.

Since GitHub now has a [built-in discussions tab](https://docs.github.com/en/discussions) for repositories, it would be amazing if we could turn those on. 
Having a clear distinction between community support about usage and issues about the project would be beneficial in two main ways:

1. The Issues tab will be less cluttered, and contributors will have an easier time finding issues they would like to solve.
2. The discussions section is more welcoming for people seeking help than posting help as an issue. Also, there's the benefit of gamification in discussions, which could further encourage community members to help each other out. 

Additionally, the discussions tab could have two (or more) main categories, 'help' and 'ideas/discussion', so that not only seeking help will be encouraged, but also discussing the evolution of SvelteKit in a slightly less formal setting. 

The [TailwindCSS discussions tab](https://github.com/tailwindlabs/tailwindcss/discussions) is a great example showcasing the possibilities of the GitHub discussions tab.

To me personally, this is more of a nice-to-have, but I think other people, especially newcomers to SvelteKit, will benefit a lot from this.

**Comment by dummdidumm** [comment]
[This came up in the core Svelte repository](https://github.com/sveltejs/svelte/issues/6035) already. We're not very convinced that GitHub discussions are the right place for things like these.
- Usage questions should be asked on StackOverflow, maybe also on the community Discord
- The line between a real feature request and some neboulus thoughts are blurry, so it might be confusing what to post where
- It needs some form of moderation which we don't have the capacity for

Closing this in favor of the issue in the core repo
