### ISSUE TITLE
Error: Handler should return a Response object

### ISSUE THREAD

**Issue by jamesbirtles** [sveltejs/kit#10940]
### Describe the bug

Using graphql-yoga in a +server.ts file the following error is returned:
```
Error: Invalid response from route /graphql: handler should return a Response object
```

This was working fine prior to sveltekit 1.27.1, but is now broken.

Looking into it, the yoga server is returning an object called `PonyfillResponse`, which I can see why sveltekit would not see this as a real Response object, but it was working before now so I am reporting it here in case this was unintentional.

### Reproduction

https://github.com/jamesbirtles/sveltekit-response-object-bug

This is just the sveltekit template with a graphql endpoint added (https://github.com/jamesbirtles/sveltekit-response-object-bug/blob/main/src/routes/graphql/%2Bserver.ts)

If you run this and visit /graphql you should trigger the error.

### Logs

```Shell
VITE v4.5.0  ready in 426 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: Invalid response from route /graphql: handler should return a Response object
    at Module.render_endpoint (/Users/james/Code/sveltekit-response-object-bug/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:48:10)
    at async resolve (/Users/james/Code/sveltekit-response-object-bug/node_modules/@sveltejs/kit/src/runtime/server/respond.js:404:17)
    at async Module.respond (/Users/james/Code/sveltekit-response-object-bug/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:20)
    at async file:///Users/james/Code/sveltekit-response-object-bug/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:510:22
```

### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M2
    Memory: 3.29 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.11 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Safari: 17.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: 1.27.1 => 1.27.1 
    svelte: ^4.0.5 => 4.2.2 
    vite: ^4.4.2 => 4.5.0
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
The only thing that changed between 1.27.0 and 1.27.1 is that we stopped polyfilling various global objects in Node versions above 18.11

**Comment by mustofa-id** [comment]
I've also encountered an issue that could be related to this, regarding the changes in version 1.27.1, where I'm getting a 'ReferenceError: File is not defined' even though I'm using Node 18.16.0. Prior to 1.27.1, everything was working just fine.

**Comment by eltigerchino** [comment]
the related change https://github.com/sveltejs/kit/pull/10920

**Comment by gtm-nayan** [comment]
The difference now is that without the polyfilling from SvelteKit, the fetch API classes are not enumerable. Yoga loops over the keys of the provided `fetchAPI` option to override its defaults from node-fetch, which breaks because these keys are skipped.

**Comment by jamesbirtles** [comment]
> The relevant difference now is that without the polyfilling from SvelteKit, the fetch API classes are not enumerable properties in the global object. Yoga loops over the keys of the provided `fetchAPI` option to override its defaults from node-fetch, which breaks because these keys are skipped.

Good spot, manually specifying each item does resolve this, e.g.:
```ts
const yoga = createYoga({
	schema,
	graphqlEndpoint: '/graphql',
	fetchAPI: {
		fetch,
		Request,
		Response,
		Headers,
		FormData,
		ReadableStream,
		WritableStream,
		TransformStream,
		Blob,
		crypto,
		btoa,
		TextEncoder,
		TextDecoder,
		URLPattern,
		URL,
		URLSearchParams
	}
});
```

I suppose its not really a bug in sveltekit then, just that the change highlighted it?

**Comment by jamesbirtles** [comment]
Does this suggest that making the polyfills enumerable previously (and still in <= 18.11) is actually a bug?

**Comment by dummdidumm** [comment]
Probably, yes. Either way, this is not something under our control / we can't do much here, therefore closing.
