### ISSUE TITLE
`static-adapter` expand dynamic routes according to paths set in `conig.kit.prerender.entries` generating same result as if they were wrote in static way

### ISSUE THREAD

**Issue by tqtifnypmb** [sveltejs/kit#10952]
### Describe the problem

Use case:

Imagine that you are writing an SEO-friendly website, where the website has the same structure, the same content, and the only difference is the language. Let's say expected structure of the website is:
`/index.html`
`/ja/index.html`
`/es/index.html`
`/blogs/a_blog.html`
`/ja/blogs/a_blog.html`
`/en/blogs/a_blog.html`
`/es/blogs/a_blog.html`

It would be nice if I can write once in Svelte with following routes:
`[slug]/index`
`[slug]/blogs`

And build with `conig.kit.prerender.entries` set to:
[
  `/index.html`
  `/ja/index.html`
  `/es/index.html`
  `/blogs/a_blog.html`
  `/ja/blogs/a_blog.html`
  `/en/blogs/a_blog.html`
  `/es/blogs/a_blog.html`
]

And `static-adapter` can expand the dynamic routes into expected structured website which can be hosted in S3 directly (doesn't have to be hosted behind server).

Note：I know `static-adapter` can works with dynamic routes as long as a `fallback` is given. But the generated site have to be hosted behind a `node-server`(?) or something like that, can't be hosted in S3 directly. Which, I think, is not `static`.

### Describe the proposed solution

It would be nice if `static-adapter` could expand dynamic routes according to paths set in `conig.kit.prerender.entries` and generate same result as if they were wrote in static way.

For example:

Given a Svelte project with dynamic routes:

`[slug]/index`
`[slug]/blogs`

and `conig.kit.prerender.entries` set to:
[
  `/index.html`
  `/ja/index.html`
  `/es/index.html`
  `/blogs/a_blog.html`
  `/ja/blogs/a_blog.html`
  `/en/blogs/a_blog.html`
  `/es/blogs/a_blog.html`
]

The result of this project generate by `static-adapter` should be equivalent to

a Svelte project with static routes:

routes/
--`/index`
--`/ja/index`
--`/es/index`
--`/blogs/a_blog`
--`/ja/blogs/a_blog`
--`/en/blogs/a_blog`
--`/es/blogs/a_blog`

### Importance

would make my life easier

**Comment by eltigerchino** [comment]
I'm confused. Does this not work currently work? You should be able to specify the value of slug to prerender dynamic routes with `config.kit.prerender.entries`. https://kit.svelte.dev/docs/configuration#prerender

**Comment by tqtifnypmb** [comment]
> I'm confused. Does this not work currently work? You should be able to specify the value of the slug to prerender dynamic routes with `config.kit.prerender.entries`. https://kit.svelte.dev/docs/configuration#prerender

I've tried, it works, but not `static`. The generated site can't be deployed to S3 directly. Dynamic routes with specified value are generated as some `js` file instead of a html page, so they can't be accessed directly(like: https://host/some_dynamic_route_here.html), they're only accessible through `index.html`.

As a comparison, static routes will be generated as corresponding HTML pages, and each route can be directly accessed without going through the index page. 

In this aspect, I believe there are differences between the two.

**Comment by eltigerchino** [comment]
You'll need to share a minimal reproduction of how you've setup your dynamic routes. It should produce a html page for each of your specified entries if you have marked your dynamic route to be prerendered.

**Comment by tqtifnypmb** [comment]
I guess know where the problem is now. I must place `export const prerender = true;` outside of the `[slug]/` in the `+layout.ts` file. If I put it inside the `[slug]/` in the `+page.ts` file, Svelte will require me to specify a fallback path, and in this case, dynamic routes will be generated as some JavaScript files

**Comment by eltigerchino** [comment]
It's mentioned in the docs that you should have `export const prerender = true;` in the root layout of your `routes` directory so that all pages are marked as prerendered. This is also mentioned in the error message when building your project.
https://kit.svelte.dev/docs/adapter-static#usage
