### ISSUE TITLE
Disabling SSR doesn't work

### ISSUE THREAD

**Issue by jgoyvaerts** [sveltejs/kit#10958]
### Describe the bug

Same bug as https://github.com/sveltejs/kit/issues/10168

It's just not possible to disable SSR in any way. What am I missing? The documentation is also confusing.

### Reproduction

```
npm create svelte@latest my-app
cd my-app
npm install
echo "export const ssr = false; console.log(document.cookie);" > src/routes/+layout.js
npm run dev
```

Expected: cookie is printed in console
Actual: document is not defined

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 9.99 GB / 31.94 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 118.0.5993.118
    Edge: Spartan (44.19041.3570.0), Chromium (118.0.2088.76)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.20.4 => 1.27.2
    svelte: ^4.0.5 => 4.2.2
    vite: ^4.4.2 => 4.5.0
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Top-level code in `+layout.js` gets executed by Node during the build process in order to see whether it exports `ssr = false`. You can't have any top-level code that won't run on the server. If you're exporting a `load` function, then that will run only in the browser:

```js
export const ssr = false;
export const load = () => {
        console.log(document.cookie);
};
```

**Comment by jgoyvaerts** [comment]
Thanks, that makes sense now!
