### ISSUE TITLE
Make imports of index.html absolute (enables better offline PWA)

### ISSUE THREAD

**Issue by domlen2003** [sveltejs/kit#10951]
### The issue
When building an "offline first" PWA you run into the issue of not being able to resolve dynamic routes or non pre-rendered routes in general when using the service worker in offline mode.
This means they have to be navigated to from a pre-rendered  page. 

### How it can be fixed
The VitePWA Plugin tries to resolve this by serving a fallback e.g. the `index.html` instead of a `404`. 
This is then used as the application entrance and the content of the dynamic route can now be loaded.

### How this fix fails
The `index.html` (if one is generated by `export const prerender = true;` or `adapter-static`) resolves its dependencies relative to its location e.g.: 
```js 
import("./_app/immutable/entry/start.f23c4643.js")
```
If this now is served as the entry point for e.g. `/dynamic/[number]` where `number` is a param on our current route, this would try to fetch the `start.f23c4643.js` from `/dynamic/_app/immutable/entry` instead of `_app/immutable/entry` which of course fails.

### Describe the proposed solution

I tried manually removing the `.` from the links in the generated `index.html` and it solved the problem.
In general I can't think of any problems arising making every link in `index.html` absolute. 
### Downside
The editor does notnot automatically recognise the linked files.In Webstorm for example you can simply click on the link and it opens the file which of course doesn’t work anymore after removing the `.`

### Alternatives considered

I started writing a custom "postprocessing" script for making the imports absolute an adding it to the build step, but it's tedious to write and brittle as im sure it could be broken by future sveltekit updates.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Have you seen the `paths.relative` configuration option (https://kit.svelte.dev/docs/configuration#paths)? Does it not do what you need?

**Comment by domlen2003** [comment]
Yeah i feel stupid now. Searched the whole docs for something like this... 
Thank you very much!
