### ISSUE TITLE
fetch failures with cloudflare-adapter

### ISSUE THREAD

**Issue by maemigh** [sveltejs/kit#10973]
### Describe the bug

I'm not sure if this is an issue specific to sveltekit's cloudflare adapter or not (but I'm specifically wondering about the special `fetch` used by FormActions and how that works with the adapter), and I've also opened an issue in the cloudflare/workers-sdk repo [here](https://github.com/cloudflare/workerd/issues/2589). The fetch works as expected with Vite.

Describe the Bug
Using fetch with wrangler dev results in errors. Attempted on both Mac and Linux.

```
const resp = await fetch(`https://stg.mul-bill.jp/`)
```

This results in internal server error.

### Reproduction

https://github.com/maemigh/cloudflare-test

This is just a build that has a submit button, which calls the `fetch` within the formaction where it produces the error.

Run the build and then
```
npx wrangler pages dev .svelte-kit/cloudflare
```
Navigate to http://localhost:8788/ja/apply and press the submit button. The fetch will cause the internal server error.

### Logs

```Shell
workerd/util/symbolizer.c++:98: warning: Not symbolizing stack traces because $LLVM_SYMBOLIZER is not set. To symbolize stack traces, set $LLVM_SYMBOLIZER to the location of the llvm-symbolizer binary. When running tests under bazel, use `--test_env=LLVM_SYMBOLIZER=<path>`.
workerd/jsg/util.c++:275: error: e = kj/compat/tls.c++:72: failed: OpenSSL error; message = error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO
stack: 10160890c 101610940 1027a0294 1027a06dc 10172893c 10172922c 10172a8f4 101707e30 10170e9f0 101724db4 100e6792c 1009b762c 100ed3ce4; sentryErrorContext = jsgInternalError
```

### System Info

```Shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1
    Memory: 97.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    npm: 10.2.0 - /opt/homebrew/bin/npm
    pnpm: 8.7.0 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 118.1.59.124
    Edge: 118.0.2088.76
    Firefox Nightly: 92.0a1
    Safari: 17.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/adapter-cloudflare: ^2.3.3 => 2.3.3
    @sveltejs/kit: ^1.20.4 => 1.27.2
    svelte: ^4.0.5 => 4.2.2
    vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

### Additional Information

Can't test a whole lot locally since `fetch` fails. Need to deploy to cloudflare to test the formaction.

**Comment by eltigerchino** [comment]
This seems like an issue with workerd rather than SvelteKit. The reproduction works fine when running outside workerd (npm run preview). There's nothing special about the fetch function when it comes to different adapters too. You can test this by not using fetch function provided by SvelteKit and you will get the same 500 internal server error result.
