### ISSUE TITLE
img on:error not fired

### ISSUE THREAD

**Issue by asv1** [sveltejs/kit#1097]
**Describe the bug**
If img cannot be loaded - on:error is not fired, refresh page is not helping. If modify code and let hmr update page contains img with on:error - error is fired.

**Logs**

**To Reproduce**
[https://github.com/asv1/svelte_bug_onerror](https://github.com/asv1/svelte_bug_onerror)

**Expected behavior**
on:error must be fired.

**Stacktraces**
**Information about your SvelteKit Installation:**
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 12.90 GB / 15.93 GB
  Binaries:
    Node: 14.16.0 - d:\portable\node\node.EXE
    npm: 6.14.11 - d:\portable\node\npm.CMD
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.78
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```
**Severity**
Looks like on:load not fired too. Other handlers maybe too, not tested.

**Additional context**

**Comment by Rich-Harris** [comment]
If the image is loaded (or fails to load) before JavaScript runs on the page, the events happen before listeners can be attached. This is expected — annoying, but not a problem specific to Svelte or SvelteKit

**Comment by asv1** [comment]
@Rich-Harris 
img on:error works on svelte repl.

**Comment by asv1** [comment]
@Rich-Harris 
I recreated example with sveltejs/template and it worked as expected. Something with sveltekit. It attaches handlers after img tag created?

**Comment by asv1** [comment]
I have update repo. If navigate to foo by clicking on link - works as expected. If press refresh - not working.

**Comment by saturnonearth** [comment]
Did you ever find a workaround for this? I am experiencing the same thing.

**Comment by maximedupre** [comment]
> I could fix this by using onerror="" instead of svelte's on:error={}.

@Rich-Harris This works. I suppose that event listeners that originate directly from HTML elements can be attached at the right moment?

<img width="1270" alt="Xnapper-2022-09-26-10 46 00" src="https://user-images.githubusercontent.com/5158181/192307771-617f2822-c530-4587-b415-1b81027247c0.png">

The language server seems to complain about that. Should I open a new ticket somewhere?

**Comment by raythurnevoid** [comment]
A better approach to this may be to insert a small script in your app.html file that attach the `error`/`load` events to all img in page and add a data-attribute to them when the events are fired (eg: `data-error` `data-success`)

**Comment by vaskulikov1983** [comment]
You have two ways to solve that problem:
1. Use native "onerror" listener right on the img element:
`<img src="/path/to/your/img" alt="Some alternative text" onerror="this.src='/path/to/your/substitute-img'">`

2. Use "onMount" and pass img source after img element was mount to DOM:
`<script>
    import {onMount} from "svelte";

    let src, alt;

    onMount(() => {
        src = '/path/to/your/img';
        alt = "Some alternative text";
    });
</script>

<img {src} {alt} on:error={errorHandler} on:load={loadHandler}/>`

Both ways has disadvantages, but i don't know another way.
