### ISSUE TITLE
Checking auth and redirect

### ISSUE THREAD

**Issue by zwelhtetyan** [sveltejs/kit#10989]
### Describe the bug

**I check auth for user and redirect if not.**

**In login**
```ts
// routes/login/+page.ts

import { envConfig } from '$lib/config/env.config';
import { redirect } from '@sveltejs/kit';
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ fetch }) => {
	const res = await fetch(`${envConfig.AUTH_DB_URL}/users/get-me`, { credentials: 'include' });
	const data = await res.json();

	if (data.me) throw redirect(302, '/');
};
```

**In register**
```ts
// routes/register/+page.ts

import { envConfig } from '$lib/config/env.config';
import { redirect } from '@sveltejs/kit';
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ fetch }) => {
	const res = await fetch(`${envConfig.AUTH_DB_URL}/users/get-me`, { credentials: 'include' });
	const data = await res.json();

	if (data.me) throw redirect(302, '/');
};
```

I have to write the same code in `routes/register/+page.ts` to perform this check-auth action. How to avoid repeating like this.

### Reproduction

https://github.com/zwelhtetyan/zfashion

### Logs

```Shell
---
```

### System Info

```Shell
---
```

### Severity

annoyance

### Additional Information

---

**Comment by hyunbinseo** [comment]
This is a question, not a bug.

>  [Discord Chat](https://svelte.dev/chat): Ask questions and discuss with other SvelteKit users in real time.

1. If authenticated, populate the `event.locals` in the [handle function](https://kit.svelte.dev/docs/hooks#server-hooks-handle).
2. Check if the authentication data exists in the [server load function](https://kit.svelte.dev/docs/load#universal-vs-server).


Example code from the documentation.

```ts
import type { Handle } from '@sveltejs/kit';

export const handle: Handle = async ({ event, resolve }) => {
  event.locals.user = await getUserInformation(event.cookies.get('sessionid'));

  const response = await resolve(event);
  response.headers.set('x-custom-header', 'potato');

  return response;
};
```
