### ISSUE TITLE
Anchor elements inside an anchor parent causes incorrect rendering during SSR

### ISSUE THREAD

**Issue by garvageart** [sveltejs/kit#10990]
### Describe the bug

Having an `a` element inside another `a` element causes the children of the parent `a` to render incorrectly during SSR. See the image below for an example.

![Screenshot 2023-11-06 174030](https://github.com/sveltejs/kit/assets/45718863/4db31f5f-fba9-4a43-8f4e-0be8444a8e6a)
In the example image, the large blocks are all anchor elements and the "Link" text is an anchor element which is a child of the large block. As you can see, blocks without the "Link" text render as intended while the rest break the tree of the parent element.

With the default of rendering server-side first and then the client hydrating, the DOM first elements rendered incorrectly and then the DOM flickers before the client renders the elements correctly. Disabling SSR or enabling only CSR is a workaround to fix the issue.

https://github.com/sveltejs/kit/assets/45718863/4e8682eb-1c86-4cc4-8f77-8d913bfb78c6

So instead of a block rendering as normal like this:

```svelte
<a id="parent-anchor">
	<div id="title-container">
		<h1 id="post-title">Some Test Data</h1>
		<div id="post-details">
			<h2 id="post-last_saved_at" class="post-container-subtitle">More Text</h2>
			<h2 id="post-status" class="post-container-subtitle">Even More Text</h2>
			<a id="child-anchor" href="link/to/somewhere"> Live </a>
		</div>
	</div>
</a>
```

You end up with a broken tree looking something like this:

```svelte
<a id="parent-anchor"></a>
<div id="title-container">
	<a id="parent-anchor">
		<h1 id="post-title">Some Test Data</h1>
	</a>
	<div id="post-details">
		<a id="parent-anchor">
			<h2 id="post-last_saved_at" class="post-container-subtitle">More Text</h2>
			<h2 id="post-status" class="post-container-subtitle">Even More Text</h2>
		</a>
		<a id="child-anchor" href="link/to/somewhere"> Live </a>
	</div>
</div>
```

### Reproduction

[Link to repository](https://github.com/garvageart/sveltekit-anchor-rendering) with similar styles which loads dummy data to show the issue in action. Instructions to reproduce issue are in the `+page.server.ts` file

### System Info

```Shell
System:
    OS: Windows 11 10.0.22635
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 141.10 MB / 7.82 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.0 => 2.1.1 
    @sveltejs/kit: ^1.24.1 => 1.27.3
    svelte: ^4.2.0 => 4.2.2
```

### Severity

annoyance

### Additional Information

This has only been tested during `dev` mode, I'm not sure if the same issue happens during preview and production.

**Comment by dummdidumm** [comment]
There's nothing that we can do about this. Having nested `a` tags is invalid HTML, and the browser "repairs" it, resulting in the HTML getting shuffled around, which then confuses Svelte's hydration algorithm. You need to adjust your code to not have nested `a` tags.

**Comment by garvageart** [comment]
Alright, noted. Thank you
