### ISSUE TITLE
SSE & unsubscribe

### ISSUE THREAD

**Issue by jycouet** [sveltejs/kit#11000]
### Describe the bug

In dev mode, when I connect to a SSE, I have 2 lines in the network console.
![image](https://github.com/sveltejs/kit/assets/5312607/dac6c121-759a-4dfe-bc8d-01aa286bbf82)

When I attempt to unsubscribe—either by clicking a button or through the onDestroy event—it does not unsubscribe both processes. Only the service worker process is unsubscribed, while the other remains open. Following five updates to the component in development mode, there are five open connections, which causes the browser (Chrome) to hang.

### Reproduction

I created a minimal repro, with only 1 `sse` route and an unsub button where you will see that one unsub is working but not the other one.

https://github.com/jycouet/kit-sse

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 6.52 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
    Yarn: 4.0.0-rc.50 - ~/.volta/tools/image/yarn/4.0.0-rc.50/bin/yarn
    npm: 9.6.7 - ~/.volta/tools/image/node/18.17.1/bin/npm
    pnpm: 8.6.5 - ~/.volta/bin/pnpm
    bun: 1.0.8 - ~/.bun/bin/bun
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.1 => 2.1.1 
    @sveltejs/kit: ^1.27.3 => 1.27.3 
    svelte: ^4.2.2 => 4.2.2 
    vite: ^4.5.0 => 4.5.0
```

### Severity

serious, but I can work around it

**Comment by noam-honig** [comment]
I ran into the same problem, did you find a solution yet?

**Comment by jycouet** [comment]
With [discord](https://discord.com/channels/457912077277855764/1174623818841600100) help, it seems to be related to another project that I had locally making use of service workers.
After cleaning all service workers, I don't have this anymore.

I will close the issue as I don't plan to use Service Worker now.
