### ISSUE TITLE
Allow route filenames to match the route folder

### ISSUE THREAD

**Issue by sdgoldstein** [sveltejs/kit#11011]
### Describe the problem

The current routing design fixes all filenames to well-known names - +page.svelte, +layout.svelte, etc.  As a result, it can lead to less than ideal productivity, as visually, when I look at the explorer or tabs in my IDE, there is little to distinguish them.  In addition, when I go to open a resource with a shortcut and start typing "+pa..", the search ahead finds all "+page.svelte" resources and I need to pick one versus being able to simply go directly to the file that I'm looking for. 

Although this isn't a major issue, when working with SvelteKit applications for several days in a row and running into the issue a number of times a day, it begins to get quite annoying and decreases my overall satisfaction with the framework

### Describe the proposed solution

Allow naming to follow the folder structure.  For example, a route in:

.../routers/login

could contain the files

+login.svelte
+login.layout.svelte
+login.layout.server.ts

The framework could then look for both patterns (e.g. in this case it could look for +page.svelte and if it doesn't find it, look for +login.svelte in the login folder).  This would add the enhancement without breaking backwards compatibility

### Alternatives considered

An alternative would be a declarative routing config file in which I could map a route to a filename.  But, I think that defeats the purpose of having a file system-based router

### Importance

would make my life easier

**Comment by eltigerchino** [comment]
> This was discussed at great length, and while there are some tradeoffs, we chose the API the way it is now to make the structure more consistent, easier to enhance and refactor, and more. Introducing another way to do the same thing would contradict that.
https://github.com/sveltejs/kit/issues/9418#issuecomment-1466260836

Here are a few workarounds in the meantime:

> when I look at the explorer or tabs in my IDE, there is little to distinguish them.

You can set this VS Code setting to display the folder name beside the file name.
```json
{
  "workbench.editor.labelFormat": "short"
}
```

There has also been progress for adding an API to VS Code which will allow us to rename the editor tab labels through th Svelte VS Code extension.
https://github.com/microsoft/vscode/pull/197205

> when I go to open a resource with a shortcut and start typing "+pa..", the search ahead finds all "+page.svelte" resources and I need to pick one versus being able to simply go directly to the file that I'm looking for.

You can type the name of the route first to find your file more easily. e.g., `login/+` would show all the route files for the `/login` route.

Hope that these help!
