### ISSUE TITLE
Svelte5 state signels and sveltekit page store don't work together 

### ISSUE THREAD

**Issue by JonathonRP** [sveltejs/kit#11021]
### Describe the bug

Page store attempting to interface store with svelte5 signels state doesn't work. Looking for how this could be done or if page store should be updated to signels state?

### Reproduction

Sveltekit project create .ts file for signels state and try to derive from store page data to access locals and notice type errors no matter what and subscribing with $ doesn't work either

https://stackblitz.com/edit/sveltejs-kit-template-default-jz7mqb?file=src%2Flib%2FuserLanguage.ts

### System Info

```Shell
Svelte5, sveltekit
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
Please provide a reproduction repository, I don't quite follow what the reproduction should look like.

**Comment by JonathonRP** [comment]
@dummdidumm please find reproduction at - https://stackblitz.com/edit/sveltejs-kit-template-default-jz7mqb?file=src%2Flib%2FuserLanguage.ts

**Comment by JonathonRP** [comment]
@dummdidumm I actually was able to figure out a way to get it them to work together just fine. this can be closed, if curious you can open repo link and see solution I came up with.
