### ISSUE TITLE
Library project tsconfig errors - module value, overwrite input file

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#11023]
### Describe the bug

Out-of-the box, two errors occur in the `tsconfig.json` file.

> Cannot write file '/src/lib/index.js' because it would overwrite input file. // ts
> 1. Provided `index.ts` instead of `index.js` if TypeScript is selected.
> 2. Related: https://github.com/sveltejs/kit/issues/9552

> Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'. // ts
> 1. The documentation does mention setting `"moduleResolution": "NodeNext"` in the [caveats](https://kit.svelte.dev/docs/packaging#caveats) section.

### Reproduction

```shell
pnpm create svelte@latest
```

```
create-svelte version 5.1.1

┌  Welcome to SvelteKit!
│
◇  Where should we create your project?
│  create-svelte@5.1.1
│
◇  Which Svelte app template?
│  Library project
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!
```

- Open the workspace in VS Code.

```shell
pnpm i
pnpm check
```

- Reload VS Code Window
- Open src/lib/index.js
- Open tsconfig.json -- 1st error message is shown
- Rename to src/lib/index.ts
- Open tsconfig.json -- 2nd error message is shown

### System Info

```Shell
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 60.42 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.8.1 - ~/Library/pnpm/node
  npm: 10.1.0 - ~/Library/pnpm/npm
  pnpm: 8.10.2 - ~/Library/pnpm/pnpm
Browsers:
  Chrome: 119.0.6045.123
  Edge: 119.0.2151.58
  Safari: 17.0
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
  @sveltejs/kit: ^1.20.4 => 1.27.5 
  @sveltejs/package: ^2.0.0 => 2.2.2 
  svelte: ^4.0.5 => 4.2.3 
  vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
I can't reproduce this issue given the reproduction steps. Can you provide a full reproducible?
