### ISSUE TITLE
Name Change - app.html to index.html

### ISSUE THREAD

**Issue by babakfp** [sveltejs/kit#1103]
### This issue isn't about a bug
So the language of the web is HTML right? [A video from Rich Harris](https://youtu.be/BzX4aTRPzno?t=735). Then why use `app.html` instead of `index.html`? The first file that beginner developer creates is `index.html` so because of those two reasons I think it's best to change `app.html` to `index.html`.
I know that SvelteKit isn't even the beta or alpha (or whatever) release but, in Sapper, the name of the main HTML file is `index.html` so I thought maybe in SvelteKit it's going to be `app.html`.
I hope I'm not being ridden by creating such a request.

**Comment by TheBeachMaster** [comment]
`app.html` is  a template file...

**Comment by TheBeachMaster** [comment]
It's also configurable , and you can name it whatever if you want... See docs https://kit.svelte.dev/docs#configuration

**Comment by Conduitry** [comment]
It is a template. It's used for serving all SSR'd pages. I don't see why we would want to call it index.html. That this is a filename people are already familiar with seems to be a counterargument, because it doesn't have the meaning they'd be familiar with.

**Comment by babakfp** [comment]
> It's also configurable , and you can name it whatever if you want... See docs https://kit.svelte.dev/docs#configuration

It doesn't matter that it's configurable or not, because It isn't the point. the point is that the user sees the `index.html` and says (Ok this is ower index file).

**Comment by babakfp** [comment]
> It is a template. It's used for serving all SSR'd pages. I don't see why we would want to call it index.html. That this is a filename people are already familiar with seems to be a counterargument, because it doesn't have the meaning they'd be familiar with.

It's the same because it doesn't matter that SvelteKit going to generate the code dynamically.
What does the beginner developer say at the first time that sees `app.html` and the second time that sees its content?
First time: "Ok we have a `.html` file with the name of `app`. What does it contain?"
Second time: "Ahah, It's the same as the `index.html` (or it's the index page or...)".

It's just one simple way to get the point. There is no reason to name it `app.html` and make it "not one way to the point".

**Comment by babichjacob** [comment]
People using Sapper saw the `index.html` file and thought they could just send the `src` file to their HTTP server and it start working, but it doesn't. Let's not have that happen again in SvelteKit.
