### ISSUE TITLE
U+FFFD (REPLACEMENT CHARACTER) in text

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/kit#11044]
### Describe the bug

Across multiple versions of svelte kit, multiple sites, and a period of over a year, I noticed that some characters in the text will be replaced with � (U+FFFD REPLACEMENT CHARACTER). I tried to inspect the response, but chrome dev tools says "No data found ..."

![image](https://github.com/sveltejs/kit/assets/1473102/3fa563bc-8a98-4e78-acae-92173e9c8c7b)

Reloading fixes

### Reproduction

tbd

### System Info

```Shell
tbd
```

### Severity

serious, but I can work around it

**Comment by eltigerchino** [comment]
Please provide a reproduction such a downloadable repository we can inspect. Otherwise, it’s impossible to tell where  the issue comes from

**Comment by mustafa0x** [comment]
1. Visit this page: https://svkit-bug.slk.is
2. click "go"

the bug should appear. if you refresh, there is no bug. i'll create a repo now.

**Comment by mustafa0x** [comment]
I'm pretty sure [client.js:1903](https://github.com/sveltejs/kit/blob/a7f8bdcfabce5cda85dd073a21d0afb6138a7a08/packages/kit/src/runtime/client/client.js#L1903) is the culprit, or near it. It seems to be splitting the body in the middle of a byte. If the demo was using ascii I don't think the bug would occur.

```js
		while (true) {
			// Format follows ndjson (each line is a JSON object) or regular JSON spec
			const { done, value } = await reader.read();
			if (done && !text) break;

			// ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
			text += !value && text ? '\n' : decoder.decode(value); // no value -> final chunk -> add a new line to trigger the last parse
			// ^^^^^^^^^^^^^^

			while (true) {
				const split = text.indexOf('\n');
				if (split === -1) {
					break;
				}

				const node = JSON.parse(text.slice(0, split));
				text = text.slice(split + 1);

				if (node.type === 'redirect') {
					return resolve(node);
				}
```

**Comment by mustafa0x** [comment]
I am unable to reproduce this bug locally, even when using `pnpm run preview`. I suspect the webserver (caddy in my case) may be affecting things, with how it passes/buffers bytes from svkit to the client.

# Reproduce
- `pnpm create svelte@latest my-app && cd my-app && pnpm install && pnpm run dev`
- create `routes/foo/`
  - +page.svelte: `<script>export let data</script><div>{data.text}</div>`
  - +page.server.js: `export async function load({ params }) { return { text: '««««««« '.repeat(1e4) } }`
- deploy, run on server (in my case: vps; pm2)
- caddy config: `https://svkit-bug.slk.is {reverse_proxy localhost:3001}`

**Comment by mustafa0x** [comment]
> I'm pretty sure [client.js:1903](https://github.com/sveltejs/kit/blob/a7f8bdcfabce5cda85dd073a21d0afb6138a7a08/packages/kit/src/runtime/client/client.js#L1903) is the culprit

Ok I think I confirmed this. Changing it to `decoder.decode(value, {stream: true})` seems to resolve the bug.
