### ISSUE TITLE
Not found error when navigating to an external content without route

### ISSUE THREAD

**Issue by janvotava** [sveltejs/kit#11069]
### Describe the bug

Upon clicking a link to navigate to an external page, an error is encountered, as shown below:

```
app.js:16 Error: Not found: /kitty.jpg
    at navigate (node_modules/@sveltejs/kit/src/runtime/client/client.js?v=268c8a72:1009:24)
    at HTMLHtmlElement.<anonymous> (node_modules/@sveltejs/kit/src/runtime/client/client.js?v=268c8a72:1591:5)
```

Simultaneously, the `willUnload` variable is set to `true` in the `beforeNavigate` callback.

### Reproduction

https://github.com/janvotava/navigation-bug

### System Info

```Shell
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 2.43 GB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.18.2 - ~/.nix-profile/bin/node
  npm: 9.8.1 - ~/.nix-profile/bin/npm
Browsers:
  Chrome: 119.0.6045.159
  Safari: 17.1
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
  @sveltejs/kit: ^1.27.4 => 1.27.6 
  svelte: ^4.0.5 => 4.2.5 
  vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior. The client-side javascript bundle only knows about the page routes, not other external files, and will treat other navigations as the destination not being found. You can use https://kit.svelte.dev/docs/link-options#data-sveltekit-reload to force the browser to handle this navigation normally.

**Comment by janvotava** [comment]
Why should Svelte Kit client side handle 404 when `willUnload` is already `true` and it knows that the navigation is not client side?
