### ISSUE TITLE
Consider removing `paths.relative: undefined`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#11073]
### Describe the problem

https://github.com/sveltejs/kit/pull/11059#issuecomment-1817405872

### Describe the proposed solution

Talk to Rich and figure out if we really need this or what exactly it does

### Importance

nice to have

**Comment by Rich-Harris** [comment]
The context here is that we wanted `paths.relative` to be a boolean (that starting in 2.0 would default to `true`) but it would have been a breaking change: https://github.com/sveltejs/kit/pull/9220#issuecomment-1447080890

We should indeed remove it in 2.0

**Comment by benmccann** [comment]
A note as to relative paths on the web archive

![Screenshot from 2023-11-20 13-23-48](https://github.com/sveltejs/kit/assets/322311/566a7111-689e-4667-8b46-edcf9226d4b3)
