### ISSUE TITLE
Cannot import that has same name props on the page file

### ISSUE THREAD

**Issue by ssssota** [sveltejs/kit#1108]
**Describe the bug**
Error has occured if you tried import that has same name props in the page file.

e.g.
*src/routes/index.svelte*
```svelte
<script context="module">
  import { hello } from '$lib/test'; // <- this import
</script>

<script>
  export let hello = '';
</script>

<h1>Hello {hello}</h1>
```
*src/lib/test.js*
```js
export const hello = 'svelte';
```

**Logs**
```
❯ pnpm dev

> ~TODO~@0.0.1 dev D:\Dev\trainings\sveltekit-test3
> svelte-kit dev

(node:18392) ExperimentalWarning: The ESM module loader is experimental.

  SvelteKit v1.0.0-next.80

  network: not exposed
  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


1:31:15 [vite] Error when evaluating SSR module /src/lib/components/Child.svelte:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (D:\Dev\trainings\sveltekit-test3\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:9)
Unexpected token '.'
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (D:\Dev\trainings\sveltekit-test3\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69030:9)

```

**To Reproduce**

1. Create new SvelteKit project.
2. Fix `src/routes/index.svelte` and create `src/lib/test.ts` like above.
3. `pnpm dev`

reproduction repo -> https://github.com/ssssota/sveltekit-module-import-issue

This repo includes some samples.

**Expected behavior**

We will be able to import like above.
And browser shows *Hello svelte*.

**Stacktraces**
No stacktraces.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 5.08 GB / 15.93 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.77)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.15
    @sveltejs/kit: next => 1.0.0-next.80
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5

</details>

**Severity**
1. Severe - I can't read the cause from the logs.
2. Normal - We should be able to import that.

**Comment by babichjacob** [comment]
> We should be able to import that.

No, this isn't allowed in regular JavaScript.

**Comment by ssssota** [comment]
oh, i see.
I'm sorry.

**Comment by babichjacob** [comment]
> Severe - I can't read the cause from the logs.

There is an error outside of the code sample given. I'll close this issue and you can open a new one that includes a reproduction repository for this. 

Since this might be a Vite issue, though, try reproducing with the Vite Svelte template (`npm init @vitejs/app`) and make the issue with them if it still happens there.

**Comment by ssssota** [comment]
@babichjacob 
I added some samples such as Vite, Svelte, and Sapper.

In my environment, this case is unique only to SvelteKit, and I consider it to be an Issue of SvelteKit.

My English is poor and may not be good enough to read.
And I understand that the collaborators are busy, but could you please check again?

If you think the sample is inadequate, please let me know what I can do.

Thank you.

**Comment by babichjacob** [comment]
I can't investigate right now, but I'll reopen this issue.

**Comment by mister-what** [comment]
I can't reproduce this issue with the current svelte-kit (`1.0.0-next.113`) and svelte (`3.38.2`).
Even when tricking Rollups _live code inclusion_ by using the import within the module context in a `console.log` does not provoke the error.

The output looks something like this:

```js
// ...generated code

const hello = "svelte";

// ...more generated code

console.log(hello);

// ...generated code

const Routes = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { hello: hello2 = "world" } = $$props;
  if ($$props.hello === void 0 && $$bindings.hello && hello2 !== void 0)
    $$bindings.hello(hello2);
  return `<h1>Hello ${escape(hello2)}</h1>`;
});

// ...more generated code

```

This is what I would expect in regards to svelte's semantics.

**Comment by ssssota** [comment]
I've confirmed that this issue has already been resolved.
