### ISSUE TITLE
App Initialization

### ISSUE THREAD

**Issue by mehdikhody** [sveltejs/kit#11088]
### Describe the problem

Currently, initializing services such as a database connection or a scheduler service in `hooks.server.js` poses an issue. 
https://github.com/sveltejs/kit/issues/927#issuecomment-917688430

Although this file allows for service initialization, it only runs after the first HTTP request is sent to the application. This causes problems for scenarios requiring script execution right at the application's startup.

This limitation is particularly problematic for implementing a scheduling system. In cases where the server reboots automatically, the scheduling system remains inactive until the first HTTP request arrives.

```js
// hooks.server.js

export const handler= async ({ event, resolve }) => {
    // other stuff
    return resolve(event);
};

async function init() {
    await initDatabase();
    await initScheduler();
}

init();
```

Currently, to mitigate this issue, I'm using Docker. After setting up my app container, a script is triggered to send an HTTP request to the application. This action results in the execution of `hooks.server.js`, effectively invoking the startup script as a side effect.

### Describe the proposed solution

I propose introducing a mechanism that enables the execution of `hooks.server.js` right at the initial startup of the application. Enabling this functionality would resolve the issue and allow for necessary scripts or services to initialize without depending on the arrival of the first HTTP request.

### Alternatives considered

In addition to addressing the startup initialization issue, it would be beneficial to consider enhancing the syntax within `hooks.server.js` to accommodate direct startup script declaration. For instance:

```js
// hooks.server.js

export const handler = async ({ event, resolve }) => {
    // other stuff
    return resolve(event);
};

export const startup = async () => {
    // Your startup script logic goes here
    await initDatabase();
    await initScheduler();
};
```

This alternative syntax addition would provide a clear and concise way to declare startup scripts within `hooks.server.js`, enhancing the customization and extensibility of the initialization process.

### Importance

would make my life easier

### Additional Information

This feature enhancement would greatly benefit applications requiring immediate startup initialization for crucial services, ensuring functionality consistency regardless of server reboots or the timing of the initial HTTP request.

**Comment by Conduitry** [comment]
You can use https://kit.svelte.dev/docs/adapter-node#custom-server for this. I'm not sure this feature makes sense in a more general case across adapters, because there's not in general a concept of your application "starting up" independent of it receiving its first request.

**Comment by mehdikhody** [comment]
Can I use this on development? What about the dev server?

**Comment by gersomvg** [comment]
@mehdikhody I want to achieve something similar. I've thought of a solution where instead of starting the server with `node build` (node build/index.js) you start it by running `node your-own-file.js`. You can have `your-own-file.js` import the `build.index.js` file thus copying all it's initialisation logic. It exports `listen` which you can use to wait for the server to be ready.

The only downside I see with this is that the `your-own-file.js` isn't included automatically by Vite, so you can't use typescript. Also, your linting will error locally if you haven't run a build yet, since `build/index.js` doesn't exist yet. All these issues are probably solvable.
