### ISSUE TITLE
create-svelte generates a CJS output

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#11086]
### Describe the bug

The default library template generates a CJS output.

```js
// dist/index.js

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Reexport your entry components here
```

This issue started from create-svelte version [5.3.0](https://github.com/sveltejs/kit/releases/tag/create-svelte%405.3.0).

### Reproduction

```shell
npm create svelte@latest
```

```
create-svelte version 5.3.1

┌  Welcome to SvelteKit!
│
◇  Where should we create your project?
│  create-svelte@5.3.1
│
◇  Which Svelte app template?
│  Library project
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◇  Select additional options (use arrow keys/space bar)
│  Add ESLint for code linting, Add Prettier for code formatting
│
└  Your project is ready!
```

```shell
npm i && npm run package
```

### Logs

```Shell
create-svelte-5.3.1 lint results:
Warnings:
1. pkg.exports["."].svelte is ./dist/index.js and is written in CJS, but is interpreted as ESM. Consider using the .cjs extension, e.g. ./dist/index.cjs

create-svelte-5.3.0 lint results:
Warnings:
1. pkg.exports["."].svelte is ./dist/index.js and is written in CJS, but is interpreted as ESM. Consider using the .cjs extension, e.g. ./dist/index.cjs

create-svelte-5.2.0 lint results:
All good!
```

### System Info

```Shell
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 155.33 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.9.0 - ~/Library/pnpm/node
  npm: 10.1.0 - ~/Library/pnpm/npm
  pnpm: 8.10.5 - ~/Library/pnpm/pnpm
Browsers:
  Chrome: 119.0.6045.123
  Edge: 119.0.2151.72
  Safari: 17.0
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
  @sveltejs/kit: ^1.27.4 => 1.27.6 
  @sveltejs/package: ^2.0.0 => 2.2.2 
  svelte: ^4.0.5 => 4.2.5 
  vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

**Comment by hyunbinseo** [comment]
Removing this line in `tsconfig.json` generates an ESM output.

```diff
- "module": "NodeNext",
```

However, removing the above line causes this TypeScript error.

> Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.

Reference https://github.com/sveltejs/kit/pull/11029

**Comment by benmccann** [comment]
> However, removing the above line causes this TypeScript error.
Option 'module' must be set to 'NodeNext' when option 'moduleResolution' is set to 'NodeNext'.

It doesn't cause the error for me. What command were you running to see that error message or is there anything else I might have to do to reproduce it?

**Comment by hyunbinseo** [comment]
The reproduction steps are same as before. https://github.com/sveltejs/kit/issues/11023

Try `pnpm check` and repeatedly close and open `tsconfig.json` file in VS Code.
