### ISSUE TITLE
Server payload added to page response for no reason

### ISSUE THREAD

**Issue by iTechTomekK** [sveltejs/kit#11100]
### Describe the bug

This is a massive thing, when you actually try to have whole content pulled from CMS, including dynamically generated components. Why oh why... when pulling content in `page.server.js` this payload that's purely used for generating page and nothing more after, is  included in page source as a data ?  
This is a huge problem, and cancels purpose of sveltekit with CMS. Now everyone shows some trivial examples and tells you to trim your payload, yes it's easy when  you have 2 lines of code and 2 links in your payload. But with a lot of content on the page plus multiple different components that needs to be described in CMS (style, theme, options etc etc), payload can be rather large and everything in it is needed. 
It got to the point in my app, generated html out of this payload is 215kb and the data carried in page source is 607kb and it's useless because html is already generated. Why does it have to be that way ? 
LCP is sky rocketing on mobile especially  because of that. 

As a workaround, I've created route with `server.js` that gets me my payload, and if I am using fetch in `page.js` it still generates page fine, and does not include that data in the response.

This basically means, using sveltekit with CMS driven sites, that have loads of content really unusable where web vitals are crucial. 

I really hope I've missed something and this can be easily fixed

### Reproduction

Run `npm run build` and observe, that in index.html that is prerendered there is a line that contains all server payload 
```js
const data = [null,{"type":"data","data":{server:"data"},"uses":{}}];
```

https://stackblitz.com/edit/sveltejs-kit-template-default-enggs5

### System Info

```Shell
not relevant
```

### Severity

blocking all usage of SvelteKit

**Comment by thet0ast3r** [comment]
How would you solve this issue? 
I don't think there is an easy way to hydrate and maybe afterwards modify the data ... if you dont have the DATA? 
You could turn off csr, then you don't need the data. 

Are your responses gzipped? Because that pretty much solves the issue with sending a big response, as e.g. links included in the data will be duplicates, etc.

**Comment by alexbudin** [comment]
@iTechTomekK we have the same issue, and its a lot of data. How exactly did you achieve the workaround?

I wish someone that knows Svelte very well or works on the core of it could address this.
