### ISSUE TITLE
url.searchParams removes second search param

### ISSUE THREAD

**Issue by juniorforlife** [sveltejs/kit#11124]
### Describe the bug

I have a query param like this `?keyword=https://www.youtube.com/watch?v=XqZsoesa55w`. Notice there are 2 query params (?keyword and ?v). The intention is to pass the whole youtube url as the keyword.

When I access `url`, the `?v=` part is completely removed

```
export async function GET({ url }: RequestEvent) {
  console.log(url.searchParams) // prints { 'keyword' => 'https://www.youtube.com/watch' }
}
```

### Reproduction

No link available

### System Info

```Shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 757.44 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v16.18.1/bin/pnpm
    bun: 1.0.10 - ~/.bun/bin/bun
    Watchman: 2023.05.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 117.0.5938.92
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/adapter-vercel: ^3.0.3 => 3.0.3 
    @sveltejs/kit: ^1.20.4 => 1.21.0 
    svelte: ^4.0.0 => 4.0.1 
    vite: ^4.3.6 => 4.3.9
```

### Severity

serious, but I can work around it

**Comment by brunnerh** [comment]
`?` is not allowed anywhere in the query string, so your URL is just invalid.
If you want to have an argument containing it (or `&` and other disallowed characters), make sure it's encoded.
Using the `URL`/`URLSearchParams` classes that happens automatically:

```js
const url = new URL('/some/path', document.location.href);
url.searchParams.set('keyword', 'https://www.youtube.com/watch?v=XqZsoesa55w');
console.log(url.toString())
// https://github.com/some/path?keyword=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DXqZsoesa55w
```

**Comment by tcc-sejohnson** [comment]
Closing, as @brunnerh  is correct! Feel free to open additional issues when necessary -- and check out our Discord for faster help on stuff like this!
