### ISSUE TITLE
`let {data} = $props()` is not type safe, and we cannot use `export let data` in rune mode

### ISSUE THREAD

**Issue by ryoppippi** [sveltejs/kit#11139]
### Describe the bug

```svelte:page.svelte
<script>
export let data; // type prediction works
</script>
```

```svelte:page.svelte
<script>
let {data} = $props() // data is predicted as `any`
</script>
```

Also, we cannot mix `export let data` and runes ......

### Reproduction

Create Sveltekit project and try using `props` instead of `export let data`

### Logs

```Shell
name: 'CompileError',
  id: '...app/src/routes/viewer/model/[modelId]/+page.svelte',
  message: '.../app/src/routes/viewer/model/[modelId]/+page.svelte:1:18 Cannot use `export let` in runes mode — use $props instead',
  frame: '1  |  <script lang="ts">\n' +
    '   |                    ^\n' +
    '2  |  \texport let data;\n' +
    '3  |  ',
```
```


### System Info

```Shell
System:
    OS: macOS 14.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.02 GB / 32.00 GB
    Shell: 3.6.1 - /usr/local/bin/fish
  Binaries:
    Node: 20.9.0 - ~/.volta/tools/image/node/20.9.0/bin/node
    Yarn: 1.22.21 - ~/.bun/bin/yarn
    npm: 10.1.0 - ~/.volta/tools/image/node/20.9.0/bin/npm
    pnpm: 8.11.0 - ~/.bun/bin/pnpm
    bun: 1.0.14 - ~/.local/share/aquaproj-aqua/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.1 => 2.1.1
    @sveltejs/kit: ^1.27.6 => 1.27.6
    svelte: 5.0.0-next.15 => 5.0.0-next.15
    vite: ^4.5.0 => 4.5.0
```
```


### Severity

annoyance

### Additional Information

_No response_

**Comment by MotionlessTrain** [comment]
`$props` supports generics to indicate types:

```ts
<script lang="ts">
  import type { PageData } from './$types'
  const { data } = $props<{ data: PageData }>()
</script>
```

**Comment by ryoppippi** [comment]
Yeah, currently I'm doing this ! Thanks

**Comment by dummdidumm** [comment]
I assume you mean "zero types", as in, `data` is automatically typed as `import('./$types').PageData`? Which version of the VS Code extension and svelte-check are you using? This should work in their latest versions. If not, please provide a more complete reproducible.

**Comment by ryoppippi** [comment]
@dummdidumm 
I'm using Neovim.
I updated to the svelte-language-server@0.16.1, and I found that the `zero types` works fine!
Thanks

**Comment by hanssonduck** [comment]
> @dummdidumm I'm using Neovim. I updated to the svelte-language-server@0.16.1, and I found that the `zero types` works fine! Thanks

Same issue in neovim, can you open this issue again?

**Comment by subhasish-smiles** [comment]
When doing this
`let { data } = $props<{ data: PageData }>();`

it stills hows the data as any.

$props() is typed like this
`declare function $props(): any;`

May be it could be 
`declare function $props<T>(): T;`
