### ISSUE TITLE
Vite transforms enhanced:img every build

### ISSUE THREAD

**Issue by DusterTheFirst** [sveltejs/kit#11135]
### Describe the problem

Building a site using `vite build` after making no changes to images referenced by `enhanced:img` or the image tags themselves will always result in vite re-optimizing those images. This causes build times to baloon upwards of 20 minutes in some cases. In projects with many, static images, this can be a large pain point.

### Describe the proposed solution

The processed images should be able to be cached, only rebuilding if there was a change to the source image data, or if the requested dimensions or other attributes changed.

This can be implemented using a cache that stores a hash of the source image contents to detect if the source changed, as well as a hash of the query parameters (ie. the directives found here: https://github.com/JonasKruckenberg/imagetools/blob/main/docs/directives.md)

It may be important for space reasons to not store more than one build worth of cache, so this cache might want to be cleared of any stale items after the build.

### Alternatives considered

To work around this large build time, users can pre-optimize their images, and simply reference them without `?enhanced`. This shifts the work onto the user to produce the optimized images, but will no longer take minutes to build every image.

It may be useful to allow the optimization step to be separate from the vite-build step as well. This would allow the image optimization to be done separately of the html generation.

### Importance

would make my life easier

### Additional Information

I am a recent adopter of SvelteKit, moving from Gatsby. From my experience, gatsby has implemented a system like this as subsequent build times are not as long as the initial build.

**Comment by MrGreenTea** [comment]
For me this would not only make life easier, but because we use `playwright` to test our website it actually breaks the workflow. When using `enhanced-img` the build takes easily more than 3 minutes every time and so often `playwright` will time out waiting for the webserver to start.

**Comment by danyelkoca** [comment]
This is fixed in the latest version of @sveltejs/enhanced-img (version 0.2.0)
![changelog](https://github.com/sveltejs/kit/assets/34621907/c76eda2c-fb57-43b3-bdd1-2c2852e07536)

Previously, caching was not done, hence the package would transform images at each build. And as you added more images, the build time would increase significantly. Now with the latest version, my build time on Netlify went down significantly:
![output](https://github.com/sveltejs/kit/assets/34621907/4112ac8f-da8b-4705-9026-03432e1a08fd)
