### ISSUE TITLE
Svelte 5: When I use the `children snippet` in `+layout.svelte`, I get two error messages.

### ISSUE THREAD

**Issue by mwc** [sveltejs/kit#11147]
### Describe the bug

When I use the `children snippet` in `+layout.svelte`, I get two error messages:

```js
<script>
    const { children } = $props()
</script>

{@render children()}
```

- Error message in vscode editor:
  <img width="630" alt="image" src="https://github.com/sveltejs/kit/assets/119984/b9ea4b09-a697-4c84-8139-de9a25bb3433">

- Error message in the browser's console:
![image](https://github.com/sveltejs/kit/assets/119984/7dcdaf96-04f0-4e57-aa6f-38ad310cd76b)

back to `<slot />`, everything is fine.

### Reproduction

...

### System Info

```Shell
Kit: 1.27.6
Svelte: 5.0.0-next.15
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Should both be fixed
