### ISSUE TITLE
vite does not await postcss.config.cjs 

### ISSUE THREAD

**Issue by basaran** [sveltejs/kit#11152]
### Describe the bug

I have been decoupling some of the logic I had in my postcss.config.cjs file. 

To do so, I created an ESM file, but since the postcss.config.cjs is, well cjs. I had to use the import() function.

I believe, It seems vite is not awaiting the postcss configuration. Although I am not quite sure.

![image](https://github.com/sveltejs/kit/assets/30809170/c0838271-f5c5-4c4c-a890-0cc1dd17d57a)

### Reproduction

To mimic the import behavior,  I added a sleeper.

```js
(async () => {
	await new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve(true);
		}, 1000);
	});
	console.log("here");
	const config = {
		plugins: [autoprefixer, purgeCssConfig()],
	};

	module.exports = config;
})();
```

### System Info

```Shell
System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (3) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 10.79 GB / 15.40 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 21.1.0 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.10.2 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3
    @sveltejs/kit: ^1.27.4 => 1.27.6
    svelte: ^4.2.7 => 4.2.7
    vite: ^4.4.2 => 4.5.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
CJS files are expected to synchronously set `module.exports` - and if they don't, there's no way for a consumer to know what to wait for.

In any case, it's not Vite that's not doing the awaiting, it's PostCSS's config loader, which is called via svelte-preprocess (https://github.com/sveltejs/svelte-preprocess/blob/main/src/transformers/postcss.ts) - but I don't think there's anything reasonable for svelte-preprocess to do either. If you synchronously set `module.exports` to a promise that resolved to the desired array, then svelte-preprocess could maybe theoretically await that promise (assuming the config loader doesn't try to validate these values and complain about getting a promise), but I don't think that's its responsibility if that's not how PostCSS's config loading normally works.

If you need to pull in outside data in your `postcss.config.cjs`, I would suggest putting it into CJS files that you can `require()`. Failing that, you might be able to synchronously return an array of plugin functions that perform their operations asynchronously by first awaiting the necessary promises.
