### ISSUE TITLE
Don't enforce prettier config by default in create-svelte

### ISSUE THREAD

**Issue by olehmisar** [sveltejs/kit#11166]
### Describe the problem

`npm create svelte` creates the following prettier file:
```json
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100,
	"plugins": ["prettier-plugin-svelte"],
	"overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

Why enforce `useTabs`, `singleQuote`, `trailingComma` and `printWidth`? Prettier is designed to be opinionated and be the same across all projects. Options are there because of history, not to abuse them.
> Prettier has a few options because of history. But we won’t add more of them.
> \- https://prettier.io/docs/en/option-philosophy

FYI, `"trailingComma": "none"` is a straight bad practice because it increases amount of diffs, so I would recommend removing at least that one.
![image](https://github.com/sveltejs/kit/assets/29802592/f9340255-33a2-418b-a0fa-4a7b2e675ac7)

### Describe the proposed solution

Replace prettier config with: 
```json
{
  "plugins": ["prettier-plugin-svelte"],
  "overrides": [{ "files": "*.svelte", "options": { "parser": "svelte" } }]
}
```

### Importance

nice to have

**Comment by benmccann** [comment]
You can have ugly code or ugly diffs. We chose ugly diffs :shrug: I don't think I setup this prettier config, but I do agree with it. Users can change it if desired. There's nothing that we can do there that will make everyone happy. These defaults align with Svelte's coding style
