### ISSUE TITLE
Kit: silenced error

### ISSUE THREAD

**Issue by zhihengGet** [sveltejs/kit#11170]
### Describe the bug

kit does not show error when we have bad imports

case1:  didnt even export 
case 2: didnt use  `import type` 

### Reproduction
in counter.svelte, if doesnt work, try restart the terminal
https://www.sveltelab.dev/?files=.%2Fsrc%2Flib%2Ftype.ts#code=N4IgdA5glgLlEDsD2AnApiAXKAZlANhtiAMZIIxoUDOWoA1lAgCZYjUBua%2Bl%2BAhgCMAtAFcoADj4gANCAEicONCiwBtACwA2aZvHTxAZmkBOAKz6jARkvbrl6dfUOADPcvOH7z2%2Bcf39sxdjbxc-SwB2Fz1-T3MvdUjjaIiXOOdo3xdpBOzbSzjLDJ9k21dstMj3AtLsyssAJhNE4PdEyucrMvjSty9rDNyXXrC9LWzGrwMjMZjrEcHZ%2Bo9jdpaGqKGs-tTPHsHjNeGXCec06dK88xmbHfcWrvzdpqDPRvUrk88M6s2xg5C5sdbh0FjdrFc8qU0vdej8Vi9rG8Pi4ALoAXwxsjAAAd0DA4MoUCQ6CA8IQSWQKFQYLRiIwWGxONxeIJRBIpLJ5IplGoGp0TNIDE5rHU0vZxE54UlYoKnKY9AYJmDLMKUjF1MLlrKZVVPH4Qe4ivpenVenshdJ5YKlXlVe17BqssELdZbc9dYbbn0QZpTQjnMF4RarYrtYC7HrNhbHV5naqlZqCmFtOJ2mlky4nMGFW9gupRqNNQKXetPSKXJ0kzLs9aTPYSwnNq6nh6Hk53q8NuX3JXIx3wV8m%2BkW2ULcZpkW452y2qDadI4ZNvDHCZ7k5dF7VeYa6HjPX29oxxOnWHrIPZirPInQk3HjvGnuHPUjKGXc4TmkjQP79r1G9LueXTDs2MTRlmjQlr0Npekc35yjmT4vhB8bupeA4Xlm8G1iWBRfsBYKjuBT7bhM9TmOOWxkaiGJorI2J8CQ9B8BAaBgAAVtQ5AkmSRCgJSlA0CS9KsJg7BcDw3CsmIkgyHIChKComCqHyJ4lssqxRlhr6Snoy6PLq-xgapqpfmh%2BnzhGgI-tGozaPmgzqFOMZag2V5erpdTmlp0Ert2ZTOcWW6rm5Hqlsq27eYhJ5Tu4%2Bq9AqkUlt8I71iccWDkZsaBSYyRpl2mTWSZXrmg%2BuXAhkHiZVqMVhZq8XAr0U4hshgE-KBSqNheyUXk5k7ZWWFl9DchXTmhDyQg1bmhh2-alvh7S9oCs1iqhkpruUN6hURYzTVc5HrTE-ytLWO3tn1MXvgCY2Bp52rNaenXjSOK0rrtG2Il2s6LfEBQrXpa2Zu9mRbSdh5Iu9lhrNeIGjv%2BYZag0Vx9W%2B6XbBuF4nLBwMPMs9wvXekUqVlU6aEF2yzPhezuABOTLpkek%2BW2G16bdEYjcYcoeGM9ncwl2TndqpM6oUQ4lEONPtHlzbs%2B2ebaKYXO2ZaLUBYGD0hU9MP45hloIWOnODKYdl2Xzqv9bVt4Ta2vTtgUJxlT2Xpc79gHFCld165KBvc3mSuOb%2BAs4a7n1ebr2Fe8rDlK6YL5ndFp7dQR%2B5h9pJhynDpgZ5VfWI-zxktvUUGaSnLV3ACwOzkaVX9djRcXvqqOxnjt4RSXUXE6euGi%2B7HZHc4dXBcdMuWg68sZzrWW530VHuOimLsESJLMFA6AkDAqAAJ4knw2LYmAAAWMAALb4NxBC8aQ5ACTSQlMCJYnMpJwjSRycncopqiaJVRgbuEwS%2BvoJw4hgjiA8JoZ0JxVSlHuHoTQnwv6AxhjA2sno9L6h-sneugtPj-31APOmYCcECgQWXC82ggwPnWv9HUT1NCYLVARcGRttTTUiHA%2BOJDgKDX1JEUMvkgKwMwfOI6Z4rJEXcKqAe7hGh0JYaKYOM4qbOCljcP48j0KazvJEHI0jULJREUca4Sp0EsLeGwohuD-RmmeHw2MGkYiyKSpNawawlQ2yeBaXchxIww1gjcRxqpm6xRHOuHwjd9EwghkEiupQdasJ0BYwU6iRYUzFhTFRxtEFlAIUkk8CCdH9yXO0QheTljJDCU%2BVKN49LkO0S7cmAj3bHVCnZO2Gs3YRhyf2emt14QBMQaIlJTMLTsI7pw-UXdbFtULvlew-TgmhTaagyoMz7oGJ8UnDZAERkQWSXhNJQEMn7HKZtGZBg2Fc2Ke5BJpTag5XLn4GZoywGXIGdAjYzy560RAPgKAAgl4rzQGvTeJIADCSARBUhQGAJkEkz7kmIPxaktIGB30ZOJFkz92SyS5ApNQJDHgiOhmFbQzzsIQTMXcqZAyTT5UqicB8UsuEClbK4q6UCUHPg8aREiQJfKiIDOHByrMZkfVAjnLh1ivFXTqBmUMji3h6FMPcclKCXLywQq2Cl2RcYyq2bWdhCrsi%2B2yFUom1V3SSpCqo5Y5DvHdiGmDL0vLgloIrLeVUtKNHRDOZA4EnQsxGGMHZewyr47rIdXKmRVTTCRDDZPGe%2BoWWXUjYPAiBQjh8MKW6hZVqAEDX2i4bRXMzVco7hGhhUbsgYJOsEeNCNE06FeQOIlXpoJkq8Ag6UDqraDPpVdDwVo%2B4RKLToNwZbs2ys2nm9oI7mlUTJf-WdOw%2B72hvHwrlFap0gUbS0Td9rK3crHceo1-t5VIUFGsKEVjL21nugYK9wJInfj3WkJtdzu0MN7UcT5NFZB3zQAAD3Yii0k58KRX2RbfBkolYWYrZDJTk8keRKRyDkWx9tnh9zNSmiyVrvykV6LS2xN19W2LyDh6Eo13HS0ZpIvVjsJEoIIgPXch5Sj6N0k6um%2Bj5FZqrORrJLss1uLpR6hYzgvmyBgBvbErEb7EB4hBqkgk6Rotgxip%2BCHX64pQ8pJNWU0O8MoahFa0062ashlGNKwIwhVodWZj8CIwo0eGj5UVc0HTaLXQ0MIon%2BVOp3XXWGR7%2Blnr6kZ2s-w9KOctIOyzkSs0TM2o6tV9UsFZvHX59lR7aNfPnigCFlBQPL1XuvFAW9iAAGp%2BAbyKzCzT8KL5ItU6imDD8JL8CxYht%2BeKlIEsLfwpZ-iiGsuo9ap1D7hXupnAEDyGw-hrGE3WlV%2BT5GttCu2z4nawifiuk6nIv755VfoixGFyguDQo4k15T19QPCXRY-Lr2mcXIY-osbLlkzLcYPbt3L%2BEAhXPlVUmLlTIyGTeCWg1cztXmpZWNaxDrVT9rh2rQEdNIn3v-rUmhhbQwSiHGy5Z7spsJvMPW4ilp7hSZACd5irE4MXyU4iyDrWQAPY009qS2KkPv3xX9jbg0tsnjG2KwZHL5V%2BlTb4qaDLrU%2BAgbegwHGV2jDYVLw9MuVzXC7qkknK2tgIy6EscbAW1WmUCz0p48IKdrZlIL4bpLtsvMBv7Rd0hwiY3yicjdnR1LW%2B0Xkf3pDjfbn5HbpjbvnfvvzYM7dmzXqUo7S7j67vwh7GoVZE4B7WOMvuV926gmKZE%2BHDUluUXWZai7cZgZUjLrzMKSBZUSpydq7uQss8IiITC32U00viQla5vqjohPgqxX96aQTZjOP%2BGdGsf0wI3aJ-hmUdgtVYQAhLdBLrxpWuJ-ShmLXQcI%2BlEl-m1ru8MjXl9Pgc29YR3vkQHwEgAQfB8BgBINQUDzO%2BKs4U21%2B%2BRnZ7F%2BV7PnJSK0flIjXLCdAUGaepVfXuebVdIGSKBWbIJVOUFVPMPaGhOpe5KUe4PA0wB0NIMmYce6CnbAiGCoZmJAwgjaf2e6Jjb1HVdAvOaaBUbRbaE1eyc5U1KnE8OA3A2grDegjsNApgxvcyUYRWdgxVXJR0czNg3g7RUNLAhg%2BAvA6UAg0dcQ0NTVKQvbdQQdWQ0wOOUMMwyOPgxQxoWNS0Q8VQgQwzHAjRLQug3Q8nWwgwsgmQuLNgywmwyOTOBQoiOw4ghQtQwQlw8yNw0Qjwy0IwSQnw1gtA%2ByAI0I2Q6w0Ik2CIpwrUIQ1wiGKmE3ZsGaCzNVZI4w5Q7aTguQ41EeXIygjQ4Q2aYojMcQ%2BLComhXwnmGokIu9QdbcRwpogomIoopsEo1RcnfQrolgqoiQ%2BQwI5hLIu9Ww3ZfgkY6Img1orJBXX4K4corNSormOtY8JQnmWopYxIl8YY9Q0Y7YtqRvICSJDotuZg6QlIwdRY7I-oiwtYxou4rY%2BImGOvF46Yt4wwhbEw-wt4bg5Qy40IuUesW4qI6g4ElNPtJ4LHD3NYUyFCUHF9Oo3uOoDqWZNEhoWEPvPMIiTQFXUKHhD3NoYKRcCk4WU-D3DffVQIqbFkoCKwAVKpcQcwcIF8ak2scQUTT9RHM8QIv%2BJ8R5HwOfPsIiIU-PTXZULgjhJk8MG4TPXfYcbk4IcIZLFcChCwVCP7KbQ0nQZIT1WzcUoNePbcMU18I0r3GcC3FdUjUMcIUyNdK08RQlJ08kpmLVPI2AoE46bpfzVLbpX7EIbE40zcGxRocIDXTkgMtVeMr7NpHQmICnKeJNIWEPCpAyGvKosXOvd0syHAiNAHNyZaQeJ4vY-Mgw4PMaRw33E8CAsyKA2jduC1e4%2BI7Q5oeIxg7w7o1g3ok6BE2tNg6wyIjuIcqM8idwlcvwpIycqo6cjg343MewgE%2BOZchA1cuI9c8IzcuY2QwIlQokutdY9QRcwcyMk8-A0c88rw2Yj47cwsGcvcjcyqFEpcl82IvM18mOCE446ov8lYv4%2BcoC58kMvArXSY1peoy87868vo2C2w7RS4p8gUKgxs9clC9o8nToo4rcrCmCzUiwnIhc8MtWY85ChPVCjaC8icq86C3cnCy0OUG4jY9Qws6KE5BZX1AcwitNDpcXNEvuUEzYSQ9szUONISxtYS2MUS4GcS1HN8pshaeXTwbdTIXue1eslcJgkWahbckCkQsCogh0AiwMUy0Sy8Cy8-S8aypC8Yj7J4MowSkXQVPU76CixY%2BWcnJUsuJo3RL7MioEDHcqMHNy1aKcmy6MgdXyxyuI7DLkwbAVFywmSyuodsZ2LynY5g54-Y%2Box88Mws-LP9dgGAPgOAYkYgUrIFcrSrXAPgDgKASkHEBACAG7FnFTf-dndTDreDEA3nPrVQZ8FoR8QoEBDwX0j3NwfkeoGoDwLahwIwEUj3GRPQCU6QbarmbQE638QUY6q6jwOahwBa4BfQcwW6yGNwB6hoSIc6qYfQZalMdcYIc656%2B6-%2BJwG60nIGnQEG6QQG164Gq66GhwB6oWUG%2BamGnQcwZGu61GpGqGsGrG9GnGlGhG-%2BfG%2BGxaiGuG3Gom8m7OQBAmzGqmlIc6wZFMVMw6owDGl6qm0mh67m2GnIXmpwkWAW4W1MqGyIcIewc6tlT3fQLfbay8AW%2BWpwAW%2BwAW9QKwZWj666umzmsmvajcTQcwAnXzHW8G4WymsmlWyINWn1U21Gx8YNO2rmi2nml2-6p2sm9Yc2wmy2t2homZb2%2Bmz2owQO3Wt6kOvQAW4Ivar63yeoCCV9D212n25OoO1OsOo04IUOs2yUUiUoEOv2gOv2kWJ6wuv2qwRoeoQ66uzwfkyun6pOtYLO4u%2BOxuj3NulSbOrGyuv2yw4wRoDms28nEmv28QOZQe1Gru52lOvMaYRI624ux4JwGWiC4W1WsumesW%2BUju0uzelW%2BoZWxe9sAuvejetOloQ%2BzeuU9WwUaEuU0BbelSNMtuqez24cV%2B9Os20sOUlIUwTw1ahwKGiyAwde0%2Bze9CBWs%2BjOnYAW8BS0Xe8%2Bu64UZ%2BlcNejWk%2BxB-exU49AcMNfe6YBB6Bj%2B7xFWs8Yh%2B5P%2BiGSIY2k3VU8hj6ful%2B4uwVLBtu6qjcKiehouzesYchtAqbQuSoPg8hxcNW0cqiZXfatugnAwF2FW1fHU2OHQDB6Bm%2B8h9R2RhwfseNMhqzfIWBEq8hzQFR8G865an%2BI02BSOv22kkwbQXmuq2QRnD-cgPACAEDIa3-Ea%2B7caoA7nHrXTd7PDInGS-snJBmSfcRDEu0suV08miB3vPfCWS1dsxmdxYkwylsM8KbAs15P8cYA1DlVk8fUtRaMfFzCbVgqbYs-SIZaSpRZJ5pQaQ8PMUeHQdMvlPDCu3lfJgpKSjZH4aVGKzps4aHTlfkeglpN4mApi7zCvapEkyJ5mOoVmbJmM-UH1M1WpxZsXVzbZFvcuRLas%2BYEGYZks-VAcQIjRHwHDIp5vGUK0SLJpn4HXBRSmX4UocJdvCuTfGUWmK5CJi-W2VCVZnDGMoiM0gtNkiTSSyLH0zoWHDzL1S8TLDZROGJ70Z9VLfjasYxfbZjAoHZips3CmFHGSjdPslIalMhEcPCMlzNPPalzzJstIJzCHW8E5waDF-ULF9owMgoIJXU9aWxZFwLFjazFJ1CNJhsmoWZqlRoXkm5r83tA5x5uZ553ygCBpepj56dYfK5TpLff5hZ0aKmGstVcFrMnLdqJ2PlUJwKyvDNSMXcAfBjNzSVwFhPc1w-SS8Jols1yKP1018TbcnwFlNSqiXJiYz7UJ91ofOKlZkOKLbM3DUZ%2BtGnHqygFxhANxjxxTcDYau7aDQAzTYAnnXrPTUXYl77cZglt5g5HwI5DdF1aJw57CWGhJ7uJJv5yWYqdvIZR4%2BsA3b0KjXZyprspLIcJzFfOZDp6KrpzlFtzqAVRXUnAd-XGq1GSYy1-s%2BN3RFmJNydimad70Wd9K%2Bd0ZismZ6ceaGbbhB5hCBa2pxJ0fI5UNkwfkXOaq9NmiNEIAA

### System Info

```Shell
windows
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
Catching type errors is Typescript's job, not SvelteKit's, and you didn't configure that when setting up the project.

**Comment by zhihengGet** [comment]
@gtm-nayan , hmm, im not sure what you mean, because import nonexistence variable also causes error and kit does not report it ?  im sure this is not an ts error  but compile time error ?

please check the reproduction

case 1:  importing an type without using "import type {} from "   -> this one could be ts but im not 100% sure
case 2: importing an nonexistent variables

**Comment by zhihengGet** [comment]
@gtm-nayan , hmm, im not sure what you mean, because import nonexistence variable also causes error and kit does not report it ?  im sure this is not an ts error  but compile time error ?

please check the reproduction

case 1:  importing an type without using "import type {} from "   -> this one could be ts but im not 100% sure
case 2: importing an nonexistent variables
