### ISSUE TITLE
Consider hooks naming

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#11180]
### Describe the problem

Our current hooks naming doesn't follow the naming convention of other files

### Describe the proposed solution

`src/hooks.server.js` or `src/routes/+hooks.server.js`

### Importance

nice to have

**Comment by Conduitry** [comment]
I'm against this. The other files beginning with a `+` all appear within `src/routes`, and their path is significant. `hooks.server.js` is neither in `src/routes` nor does its path signify anything. (It also aligns with `src/app.html`, `src/error.html`, and `src/service-worker.js`, all of which live at specific paths, and none of which have a `+`.)

If we get around to #6731, I think a `+` prefix makes sense for that file - but not for the single file that doesn't even live inside `src/routes`.

**Comment by benmccann** [comment]
Yeah, https://github.com/sveltejs/kit/issues/6731 is along the lines of what I was thinking. I'd forgotten there was an issue for it, so I'll go ahead and close this.

**Comment by benmccann** [comment]
It turns out we already renamed `hooks.js` to `hooks.server.js` and I'd forgotten that was a change we'd made...
