### ISSUE TITLE
Resurgence of invalid request body failure with +server.ts API endpoint

### ISSUE THREAD

**Issue by Octogonapus** [sveltejs/kit#11202]
### Describe the bug

I'm experiencing an issue which seems identical to #7409. I have a simple `+server.ts` file with a `GET` endpoint in a brand new skeleton project. Calling this API with a `Content-Type` header set results in `Invalid request body`. Calling it without that header results in an internal error `SyntaxError: Unexpected end of JSON input`.

This seems to just be a problem with `GET` bodies, so if sveltekit simply disallows this (totally reasonable imo) then this issue is really about the error message being unclear/unhelpful.

### Reproduction

My MWE repo is available here: https://github.com/Octogonapus/invalid-request-mwe

The steps I took to create this are:

1. `npm create svelte@latest invalid-request-mwe`
2. `cd invalid-request-mwe`
3. `npm i`
4. Create the `+server.ts` file
5. `npm run dev`
6. Hit the API `curl --location --request GET 'http://localhost:5173/foo' --header 'Content-Type: application/json' --data '{}'`
7. The response is `Invalid request body`

### Logs

```Shell
There are no logs
```

### System Info

```Shell
System:
    OS: Linux 6.6 Fedora Linux 38 (Workstation Edition)
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 48.85 GB / 62.54 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/kit: ^1.27.4 => 1.27.7 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^4.4.2 => 4.5.1
```

### Severity

serious, but i can work around it

**Comment by go-aegian** [comment]
in your vite.config.ts - add server: { proxy: {} } then you can upgrade all libs to latest version and should work
