### ISSUE TITLE
Form submission doesn't happen if formaction button is disabled after click in Chrome/Safari

### ISSUE THREAD

**Issue by sokyran** [sveltejs/kit#11204]
### Describe the bug

**WARNING**: Can Reproduced only using Chrome/Safari, works good in Firefox

Basically, you need two files: `+page.server.js` and `+page.svelte`.

In `+page.server.js` you can have any action you like:

```js
const checkout = () => {
	console.log('checkout successful')
	return { success: true }
};
export const actions = { checkout };
```

And in `+page.svelte` you have `<form>` and `<button>`. Button has `formaction` attribute and also logic to disable itself on submit:

```svelte
<script>
	import { enhance } from '$app/forms';
	let disabled = false;
</script>

<form method="POST" use:enhance>
	<button
		on:click={() => (disabled = true)}
		{disabled}
		formaction="?/checkout"
	>Send me</button>
</form>
```

**Expected behaviour:** form is submitted, "checkout successful" logged to console, button is disabled.

**Actual behaviour:** button is disabled, but no request to form sent.

### Reproduction

StackBlitz link: https://stackblitz.com/edit/form-submission-bug
Sveltelab link: https://www.sveltelab.dev/hoh6scx1j2wzqk5

### Logs

```Shell
No interesting logs.
See for yourself inside reproduction.
```

### System Info

```Shell
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 127.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/Library/Caches/fnm_multishells/51879_1673605975417/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/51879_1673605975417/bin/npm
    pnpm: 8.11.0 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 115.1.56.11
    Chrome: 119.0.6045.199
    Safari: 17.1.2
    Firefox: 120.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.1 => 2.1.1
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/kit: ^1.27.7 => 1.27.7
    svelte: ^4.2.8 => 4.2.8
    vite: ^4.5.1 => 4.5.1
```

### Severity

serious, but I can work around it

**Comment by brunnerh** [comment]
I would generally not recommend adding `click` events on buttons in a form, but instead just use the `submit` event.
When using `enhance`, you can just add a handler there:
```svelte
<form method="POST" use:enhance={() => { disabled = true }}>
```

This is [not a Svelte problem](https://stackoverflow.com/questions/5691054/disable-submit-button-on-form-submit) either and I looked at the spec and found it to be inconclusive. So again: Just don't do it.
