### ISSUE TITLE
Adding <script src=""> in Body Causes DOM Modification of that Script to Disappear

### ISSUE THREAD

**Issue by ghost** [sveltejs/kit#11206]
### Describe the bug

The code below is supposed to add it's own content into the page, but it doesn't work properly.
```
<div>
    <script src="https://nuthead.neocities.org/ring/ring.js"></script>
</div>
```

In `dev` mode:
The script will add some stuff to the page for like a second or two, but will then disappear. This is repeated if you try to refresh the page.

In production, using the static adapter:
When you first load the route containing the script, it will appear. However, if you click on a link and go to a different route, followed be heading back to the route you just went to, it disappears until you reload.

### Reproduction

Paste the code in any `+page.svetle` file or component, run `dev` mode, then head to the corresponding route or route that uses the component.

### Logs

```Shell
No errors or anything.
```

### System Info

```Shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 3.72 GB / 7.15 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 21.2.0 - /usr/bin/node
    npm: 10.2.4 - /usr/bin/npm
  Browsers:
    Chromium: 119.0.6045.123
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1 
    @sveltejs/adapter-static: ^2.0.3 => 2.0.3 
    @sveltejs/kit: ^1.20.4 => 1.27.7 
    svelte: ^4.0.5 => 4.2.8 
    vite: ^4.4.2 => 4.5.1
```

### Severity

annoyance

### Additional Information

I've confirmed this is not an issue with the script I want to paste or with Vite. The script works if you put in an HTML file and/or running Vite (but not SvelteKit).

I've attempted to workaround this, but the following does not work:
- Wrapping the script in `{@html}`
- Used `defer` in the tag.
- Used `async` in the tag.
- Make a component where only the script tag is used.
- Used `{#if true}` instead of `<div>`

Also note that `<svelte:head>` is not a solution here. The script HAS to modify the actual body.

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a repository.

**Comment by k-cottonears** [comment]
You can view this right issue right here: https://github.com/k-cottonears/svelte-bugged-issue

**Comment by eltigerchino** [comment]
Closing as this is no longer an issue with Svelte 5
