### ISSUE TITLE
Not work with Node.js v21.4.0 when using https in dev server

### ISSUE THREAD

**Issue by hronro** [sveltejs/kit#11213]
### Describe the bug

The dev server always responds "Invalid request body"

![CleanShot 2023-12-07 at 15 59 39@2x](https://github.com/sveltejs/kit/assets/15059605/48ecbd0d-26e7-4dc8-93b9-7d1d46718b90)

### Reproduction

Create a self-signed TLS certificate, and then copy the path of the certificate to vite.config.ts:

```typescript
export default defineConfig({
	server: {
		host: true,
		port: 8000,
		https: {
			key: '<key path>',
			cert: '<cert path>',
		},
	},
	// ...
})
```

Then run `pnpm dev`, and open the browser you will see the issue.

### System Info

```Shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (14) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 25.42 GB / 27.41 GB
    Container: Yes
    Shell: 3.6.2 - /usr/bin/fish
  Binaries:
    Node: 21.4.0 - /usr/bin/node
    npm: 10.2.5 - /usr/bin/npm
    pnpm: 8.10.5 - /usr/bin/pnpm
    bun: 1.0.0 - /usr/local/bin/bun
  npmPackages:
    @sveltejs/adapter-auto: ^2.1.1 => 2.1.1
    @sveltejs/adapter-node: ^1.3.1 => 1.3.1
    @sveltejs/kit: ^1.27.7 => 1.27.7
    svelte: ^4.2.8 => 4.2.8
    vite: ^4.5.1 => 4.5.1
```

### Severity

serious, but I can work around it

### Additional Information

It seems this only happens in the latest version of Node.js (v21.4.0). I tried to downgrade Node.js to v20.9.0, and everything works fine with Node.js v20.9.0.

Also, even with Node.js v21.4.0, if I force the client to use HTTP/1.1 to connect to the dev server (by default it will use HTTP2), everything works fine again. Here are my test using curl as the HTTP client:

![CleanShot 2023-12-07 at 16 13 22@2x](https://github.com/sveltejs/kit/assets/15059605/0fd63152-f789-439c-a455-e64589078762)

![CleanShot 2023-12-07 at 16 12 57@2x](https://github.com/sveltejs/kit/assets/15059605/f712c2d0-c51b-4d54-b851-5cfb8f2ca7c2)

Looks like something about HTTP2 has changed in the latest Node.js.

**Comment by benmccann** [comment]
You would need to file this issue in the Vite repository since we use the Vite dev server. However, I'm not sure if they'd support an unstable version of Node

**Comment by hronro** [comment]
The same issue has been confirmed on Node.js v22. Should we reopen this issue?
