### ISSUE TITLE
CloudFlare Workers Adapter can't serve prerendered pages

### ISSUE THREAD

**Issue by nosovk** [sveltejs/kit#11210]
### Describe the bug

We embed svelte kit blog inside existing site, using Cloudflare workers to intercept requests to `/blog*` route. Previously we had an issue that scenario https://github.com/sveltejs/kit/issues/10937 that was successfully fixed in recent upgrade. Now, pages are successfully served from subpath. But if we want to serve prerendered page content, attempt to open the page directly causes error. It means that if I go to `/blog` page, and then go over the link to `/blog/prerender` page - everything works as excepted. But if you try to open `blog/prerender` page directly - you will gate Cloudflare 1101 error.
As far I understand, prerendered page generated during build. And even more - it's contend stored inside corresponding KV. But when I try to open the page directly - there is some error in manifest, because of what matching KV entry isn't found.

<img width="762" alt="image" src="https://github.com/sveltejs/kit/assets/1398808/77e14bc0-7c93-4501-b49e-5b08ab55b7e1">
I can see that in KV resulting key is not `prerender.html`, but `blog/prerender.cfcc6a4220.html`
I think that hash is added by vite, but actually I didn't figure out how key name related to manifest inside build. I mean, that file  `/blog/prerender.cfcc6a4220.html` doesn't served by direct link.

### Reproduction

repository: https://github.com/nosovk/sveltekit-cloudflare-workers-repro

broken test link: https://sveltekit-cloudflare-workers-repro.nosovk.workers.dev/blog/prerender

it will fail if you will try to open it directly.

But you still can visit that page, by opening that link:

https://sveltekit-cloudflare-workers-repro.nosovk.workers.dev/blog/

and that pressing on a link to /prerender page

inside logs we can see error like that:
<img width="569" alt="image" src="https://github.com/sveltejs/kit/assets/1398808/b5b5778d-d4f6-4f4f-a4b7-c6d40cfe487d">

### Logs

```Shell
{
  "outcome": "exception",
  "scriptName": "sveltekit-cloudflare-workers-repro",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "name": "Error",
      "message": "_KVError: could not find prerender.html in your content namespace",
      "timestamp": 1701905948034
    }
  ],
  "logs": [],
....
}
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-1370P
    Memory: 35.48 GB / 63.67 GB
  Binaries:
    Node: 20.5.1 - ~\AppData\Local\fnm_multishells\23348_1701858361774\node.EXE
    npm: 10.2.1 - ~\AppData\Local\fnm_multishells\23348_1701858361774\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\fnm_multishells\23348_1701858361774\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.2.2 => 1.2.2
    @sveltejs/enhanced-img: ^0.1.5 => 0.1.5
    @sveltejs/kit: ^1.27.7 => 1.27.7
    svelte: ^4.2.0 => 4.2.2
    vite: ^4.0.0 => 4.5.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Unfortunately for a blog it's crucial to being indexed by Google, it means that without prerender it's not very usefull.

**Comment by eltigerchino** [comment]
can you share the deployment logs?

**Comment by nosovk** [comment]
wrangler deploy dev output:
[log.txt](https://github.com/sveltejs/kit/files/13621468/log.txt)

**Comment by eltigerchino** [comment]
Thank you. The log was very helpful. I now understand it was my mistake for copying the cloudflare adapter prerendered routing logic because there is an important distinction between the two.

Cloudflare workers store prerendered pages as `/about.html` so we can't request for the pathname `/about` that doesn't have the `.html` suffix like we do with cloudflare pages.

**Comment by nosovk** [comment]
https://sveltekit-cloudflare-workers-repro.nosovk.workers.dev/blog/prerender works now, thanks a lot for help!
