### ISSUE TITLE
ssr false with +layout.server file cause loop page refresh on 404 (#6854 recurred)

### ISSUE THREAD

**Issue by sinbino** [sveltejs/kit#11227]
### Describe the bug

Same issue as #6854 is happening with @sveltejs/kit 1.27.6 or later.
It does not happen in @sveltejs/kit 1.27.5 or earlier.

Create a +layout.server.js file when SSR is false cause loop refresh of the page.

### Reproduction

```
pnpm create svelte@latest my-app
cd my-app
pnpm install
pnpm upgrade
```

Create the following files:

```
/src/routes/+layout.js

export const ssr = false;
```

```
/src/routes/+layout.server.js (empty)
```

```
pnpm run dev
```

Now when navigating on a non-existent URL the page keeps refreshing indefinitely.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 9.40 GB / 15.42 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.8.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.1.0 - /usr/bin/npm
    pnpm: 8.6.10 - /usr/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: 1.27.5 => 1.27.5 
    svelte: ^4.2.7 => 4.2.7 
    vite: ^4.4.2 => 4.4.2
```

### Severity

annoyance

**Comment by sadfun** [comment]
+1, exactly same issue. Happening in @sveltejs/kit 1.27.4 and 1.27.6, but not 1.27.5.

**Comment by zommerberg** [comment]
+1

**Comment by sadfun** [comment]
Also happens in today's SvelteKit 2, can't upgrade :(
