### ISSUE TITLE
site: copy code button copies type errors

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#11247]
### Describe the problem

Using the copy code button for the code block at this docs page copies errors.
https://kit.svelte.dev/docs/adapter-cloudflare-workers#usage

Expected:
```js
import adapter from '@sveltejs/adapter-cloudflare-workers';

export default {
	kit: {
		adapter: adapter()
	}
};
```

Actual:
```js
import adapter from '@sveltejs/adapter-cloudflare-workers';Cannot find module '@sveltejs/adapter-cloudflare-workers' or its corresponding type declarations.2307Cannot find module '@sveltejs/adapter-cloudflare-workers' or its corresponding type declarations.
export default {	kit: {		adapter: adapter()	}};
```

### Describe the proposed solution

.

### Importance

nice to have

**Comment by krish-italiya** [comment]
I think I can resolve this issue you can assign it to me

**Comment by eltigerchino** [comment]
closed as completed since this no longer occurs in the new omnisite
