### ISSUE TITLE
How do I use a global property?

### ISSUE THREAD

**Issue by bastinald** [sveltejs/kit#1125]
Let's say I have a global property I want to be able to use in any component called websiteName.

Where do I put this global property and how do I use it in components?

Is there somewhere that explains how to use env variables with SvelteKit I missed?

Thank you.

**Comment by bastinald** [comment]
I think I figured it out via Vite.

Created a `.env` file in my root directory:

```env
VITE_MESSAGE="World"
```

Use `import.meta.env` to access it:

```html
<h1>Hello, {import.meta.env.VITE_MESSAGE}</h1>
```

**Comment by benmccann** [comment]
> Is there somewhere that explains how to use env variables with SvelteKit I missed?

https://kit.svelte.dev/faq

**Comment by pooledge** [comment]
@benmccann thank you for the updated reference!

I am getting this only while unit testing with testing-library and jest:
```
const url = import.meta.env.VITE_API_URL;
                       ^^^^
SyntaxError: Cannot use 'import.meta' outside a module
```
While this is most certainly a jest issue, I'm curious how did you overcome it?

**Comment by sebastianrothe** [comment]
You have to use a transformer, which understands this syntax. Like esbuild-jest (may come with some other problems though, if you use typescript)

**Comment by Crenshinibon** [comment]
@pooledge I'm struggling with this as well. Did you find a solution? @sebastianrothe I don't really understand how to approach what you suggest. An example would be really helpful. Thx.

**Comment by sebastianrothe** [comment]
> @pooledge I'm struggling with this as well. Did you find a solution? @sebastianrothe I don't really understand how to approach what you suggest. An example would be really helpful. Thx.

Can you post your jest.config file somewhere ?

**Comment by Crenshinibon** [comment]
It's embedded in package.json:

`  "jest": {
    "transform": {
      "^.+\\.svelte$": "svelte-jester",
      "^.+\\.js$": "babel-jest"
    },
    "moduleFileExtensions": [
      "js",
      "svelte"
    ],
    "moduleNameMapper": {
      "\\$lib/(.+)$": "<rootDir>/src/lib/$1",
      "\\$app/(.+)$": "<rootDir>/.svelte-kit/dev/runtime/app/$1"
    },
    "setupFilesAfterEnv": [
      "@testing-library/jest-dom/extend-expect"
    ],
    "testEnvironment": "jsdom"
  }`

**Comment by pooledge** [comment]
I recall the closest I got was there: https://github.com/javiertury/babel-plugin-transform-import-meta/issues/2

**Comment by sebastianrothe** [comment]
You need to change this part:
```
"transform": {
      "^.+\\.svelte$": "svelte-jester",
      "^.+\\.js$": "esbuild-jest"
    },
```

and then `npm install --save-dev esbuild esbuild-jest`

The problem is babel doesn't understand ES import.meta syntax. You could use some babel plugins, but using esbuid is easier and more modern.

**Comment by pooledge** [comment]
> The problem is babel doesn't understand ES import.meta syntax. You could use some babel plugins, but using esbuid is easier and more modern.

So if I am using
```
transform: {
		'^.+\\.svelte$': 'svelte-jester',
		'^.+\\.ts$': 'ts-jest'
	}
```
does this make it a `ts-jest`problem?

**Comment by sebastianrothe** [comment]
You can use ts-jest or esbuild-jest. Both should work.

**Comment by Crenshinibon** [comment]
Thank you @sebastianrothe. That solves it not completely though, or I'm missing something else. Now I get:

>  FAIL  src/lib/host/auth.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'SSR' of undefined

      36 | function prefetch_(href) {
      37 |      return router.prefetch(new URL(href, get_base_uri(document)));
    > 38 | }

**Comment by apu031** [comment]
Hi @Crenshinibon @sebastianrothe! I am getting the same error. Did you figure out how to solve it?

> Thank you @sebastianrothe. That solves it not completely though, or I'm missing something else. Now I get:
> 
> > FAIL  src/lib/host/auth.spec.js
> > ● Test suite failed to run
> 
> ```
> TypeError: Cannot read property 'SSR' of undefined
> 
>   36 | function prefetch_(href) {
>   37 |      return router.prefetch(new URL(href, get_base_uri(document)));
> > 38 | }
> ```

**Comment by sebastianrothe** [comment]
> Hi @Crenshinibon @sebastianrothe! I am getting the same error. Did you figure out how to solve it?
> 
> > Thank you @sebastianrothe. That solves it not completely though, or I'm missing something else. Now I get:
> > > FAIL  src/lib/host/auth.spec.js
> > > ● Test suite failed to run
> > 
> > 
> > ```
> > TypeError: Cannot read property 'SSR' of undefined
> > 
> >   36 | function prefetch_(href) {
> >   37 |      return router.prefetch(new URL(href, get_base_uri(document)));
> > > 38 | }
> > ```

I don't know, how your test file looks like. Where does this variable SSR come from ?

**Comment by apu031** [comment]
@sebastianrothe All good! I realized what the issue was. Because jest uses a dev server that does not have access to the browser, import.meta will always be undefined. I just had to mock svelte-kit's goto function and imported the module dynamically to solve the issue.

`type linkFunction = (
  href: string,
  opts?: { replaceState?: boolean; noscroll?: boolean; keepfocus?: boolean; state?: any },
) => Promise<any | string>;
type testLinkFunction = (href: string) => string;
let goto: linkFunction | testLinkFunction;

async function importModule(moduleName: string): Promise<any> {
  console.log('importing ', moduleName);
  const importedModule = await import(moduleName);
  console.log('\timported ...');
  return importedModule;
}

if (import.meta.env !== undefined) {
  console.log('inside');
  (async () => {
    let importedModule = await importModule('../../.svelte-kit/dev/runtime/app/navigation.js');
    goto = importedModule.goto;
  })();
} else {
  goto = (href: string): string => href;
}

export { goto };`

**Comment by sebastianrothe** [comment]
> @sebastianrothe All good! I realized what the issue was. Because jest uses a dev server that does not have access to the browser, import.meta will always be undefined. I just had to mock svelte-kit's goto function and imported the module dynamically to solve the issue.
> 
> `type linkFunction = (
> href: string,
> opts?: { replaceState?: boolean; noscroll?: boolean; keepfocus?: boolean; state?: any },
> ) => Promise<any | string>;
> type testLinkFunction = (href: string) => string;
> let goto: linkFunction | testLinkFunction;
> 
> async function importModule(moduleName: string): Promise {
> console.log('importing ', moduleName);
> const importedModule = await import(moduleName);
> console.log('\timported ...');
> return importedModule;
> }
> 
> if (import.meta.env !== undefined) {
> console.log('inside');
> (async () => {
> let importedModule = await importModule('../../.svelte-kit/dev/runtime/app/navigation.js');
> goto = importedModule.goto;
> })();
> } else {
> goto = (href: string): string => href;
> }
> 
> export { goto };`

Okay, but still. We have tests which use import.meta.env and they work. So it is possible with esbuild-jest/ts-jest.
