### ISSUE TITLE
Feature Request : minify generated Javascript

### ISSUE THREAD

**Issue by MarArMar** [sveltejs/kit#11250]
### Describe the problem

I deployed a Sveltekit website on Vercel

I tried a lighthouse test, it recommends that the JS should be minified, that it could help save close to 1 second for the user to load the entire page

Edit : I confirm the scripts loaded & not minified are from Sveltekit & not static or 3rd party loaded scripts

I also opend manually the files & saw they could indeed be minified because there were quite a bunch of whitespace

I think this should be a no brainer if the functionnality is the same and the user experience is better

### Describe the proposed solution

Probably an option to activate / deactivate this for builds

I would argue minified should be the default

### Alternatives considered

Maybe compress with a script after builds

### Importance

nice to have

**Comment by gtm-nayan** [comment]
It is the default. We need a minimal reproducible as the issue template asked you for if it's not.

(Hint: Look at the files in your network tab instead of the server files)
