### ISSUE TITLE
Redirecting HTML file pathnames to a file extensionless pathname

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#11252]
### Describe the problem

When a user navigates to `/example/index.html` and `/example.html`, I'd like it to redirect to `/example`. I'm not sure how useful or practical this is but it was just a thought I came across. I think we may already be doing for the vercel adapter? but not for the others.

### Describe the proposed solution

A default or configurable option to always redirect html file pathnames to their counterpart and vice versa. Similar to https://vercel.com/docs/projects/project-configuration#cleanurls

### Alternatives considered

Let the deployment platform or developer handle it through explicit redirect rules or rewrite rules etc.

### Importance

nice to have

**Comment by antony** [comment]
You could do this trivially in either hooks, or by creating a route which matches any path ending in .html, and doing the redirect there. I don't think we'd want to add an explicit feature for this, as it is easily achievable already.
