### ISSUE TITLE
Dependency Resolve

### ISSUE THREAD

**Issue by Nikhil-Software-Cartel** [sveltejs/kit#11264]
### Describe the bug

please resolve deps, things are working, and much faster with latest vite updates.
when is svelte 5 officially integrated?
# package
```json
{
  "name": "sewamo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
    "check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch",
    "test": "vitest",
    "lint": "prettier --check .",
    "format": "prettier --write ."
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^2.0.0",
    "@sveltejs/kit": "^1.27.4",
    "prettier": "^3.1.0",
    "prettier-plugin-svelte": "^3.0.0",
    "svelte": "^4.2.7",
    "svelte-check": "^3.6.0",
    "typescript": "^5.0.0",
    "vite": "^4.4.2",
    "vitest": "^0.34.0"
  },
  "type": "module",
  "dependencies": {
    "mongeasy": "^1.0.1",
    "mongoose": "^8.0.2"
  }
}
```
![image](https://github.com/sveltejs/kit/assets/54004431/b406000b-1bfa-43e2-bbb6-40f9d494f475)

dependencies:
- mongoose 8.0.2
+ mongoose 8.0.3

devDependencies:
- @sveltejs/kit 1.27.7
+ @sveltejs/kit 1.28.0
- prettier 3.1.0
+ prettier 3.1.1
- typescript 5.3.2
+ typescript 5.3.3
- vite 4.5.1
+ vite 5.0.7
- vitest 0.34.6
+ vitest 1.0.4

 WARN  Issues with peer dependencies found
.
└─┬ @sveltejs/kit 1.28.0
  ├── ✕ unmet peer vite@^4.0.0: found 5.0.7
  └─┬ @sveltejs/vite-plugin-svelte 2.5.3
    ├── ✕ unmet peer vite@^4.0.0: found 5.0.7
    └─┬ @sveltejs/vite-plugin-svelte-inspector 1.0.4
      └── ✕ unmet peer vite@^4.0.0: found 5.0.7

### Reproduction

# 12-dec-2023
pnpm up --latest

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   
    Memory: 7.20 GB / 15.94 GB
  Binaries:
    Node: 20.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.7.6 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.61)
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.1
    @sveltejs/kit: ^1.27.4 => 1.28.0
    svelte: ^4.2.7 => 4.2.8
    vite: ^4.4.2 => 5.0.7
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
SvelteKit v2 will support Vite v5. We can't update to Vite v5 in Svelte v1 because Vite v5 drops support for some of the versions of Node that SvelteKit v1 still supports.
