### ISSUE TITLE
Allow `handleMissingId` to remap missing to valid IDs

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#11280]
### Describe the problem

I have some readme-internal links

```md
For details, [see this section](#-this-section)
```

which receive different IDs on GitHub and when deploying SvelteKit. GitHub needs the above for the ID to resolve, while the deployed SvelteKit has a double hyphen (due to HTML spacing entity in the header title.

```md
For details, [see this section](#--this-section)
```

I'm currently doing some crazy slots business to replace the ID when deploying

```svelte
<Readme>
  <span slot="fix-id-diff">
    For details, <a href="#--this-section">see this section</a>.
  </span>
</Readme>
```

A different but only partial solution is to just ignore the missing ID at build time but that leaves a broken link on the site.

```ts
// svelte.config.js
export default {
 kit: {
    prerender: {
      handleMissingId: ({ id }) => {
        if ([`ok-to-be-missing IDs`].includes(id)) return
        throw `Missing ID: ${id}`
      },
    },
  },
}
```

### Describe the proposed solution

Maybe a nicer solution would be to allow the `handleMissingId` callback to return a string to use as the correct ID instead? I.e. the bad ID would be replaced by whatever string `handleMissingId` returns. Haven't thought through all the implications of this.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Extending the `handleMissingId` API to also start rewriting the HTML feels like the wrong solution here. Given that you can't influence how GitHub handles this and given that you want your links to work both in your source files and in your site, the correct solution would appear to be to figure out what rules GitHub uses and to adjust your Markdown renderer or whatever is producing the anchor elements these links are pointing at. We don't want to accommodate in the framework something that's happening incorrectly in userland.

**Comment by janosh** [comment]
I'm using @pngwn's excellent [MDsveX](https://github.com/pngwn/MDsveX) with [rehype-slug](https://github.com/rehypejs/rehype-slug) whose [only config option](https://github.com/rehypejs/rehype-slug?tab=readme-ov-file#parameters) is

> prefix (string, default: '') — prefix to add in front of ids

so I don't think there's an easy to get the right heading ID from it. Maybe a `rehype-slug` feature request waiting to be submitted? @wooorm would you be open to a new option to customize ID generation?


```ts
import link_headings from 'rehype-autolink-headings'
import heading_slugs from 'rehype-slug'

const rehypePlugins = [
  heading_slugs,
  [
    link_headings,
    {
      behavior: `append`,
      test: [`h2`, `h3`, `h4`, `h5`, `h6`], // don't auto-link <h1>
      content: s(
        `svg`,
        { width: 16, height: 16, viewBox: `0 0 16 16` },
        // symbol #octicon-link defined in app.html
        s(`use`, { 'xlink:href': `#octicon-link` }),
      ),
    },
  ],
]

mdsvex({
  rehypePlugins,
  extensions: [`.svx`, `.md`],
})
```

**Comment by wooorm** [comment]
> which receive different IDs on GitHub and when deploying SvelteKit.

The problem isn’t `rehype-slug`, it generates what GitHub does.

**Comment by janosh** [comment]
@wooorm you're right, apologies. actually the only case where the heading link doesn't work is when previewing the readme in VS Code which includes emojis in the heading so

```
## 🔣 &thinsp; Props
```

becomes

```
[link](#--props)
```

on GH and SvelteKit but needs to be 

```
[link](##-🔣-props)
```

to work in VS Code.
