### ISSUE TITLE
Upgrading to Kit 2 it throws with `Cannot find module 'graphql-request/build/esm/types' or its corresponding type declarations.ts (2307)`

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#11329]
### Describe the bug

Upgrading today from `"@sveltejs/kit": "1.30.0"` to `"@sveltejs/kit": "2.0.0"` and deleting `node_modules` and `package-lock.json`, if I run `npm install` on typescript check I get:

![image](https://github.com/jasonkuhrt/graphql-request/assets/41120635/676e1641-0088-4a39-a8a8-a212f85004bd)

`Cannot find module 'graphql-request/build/esm/types' or its corresponding type declarations.ts (2307)`

Why?

Maybe some issue with package.json `exports`?

```json
"exports": {
    ".": {
      "require": {
        "types": "./build/cjs/index.d.ts",
        "default": "./build/cjs/index.js"
      },
      "import": {
        "types": "./build/esm/index.d.ts",
        "default": "./build/esm/index.js"
      }
    }
  },
  "types": "./build/esm/index.d.ts",
```

### Severity

blocking an upgrade

**Comment by tcc-sejohnson** [comment]
Given that you've deleted your pnpm lockfile, it seems like you're probably installing a newer version of `graphql-request` that has a different structure -- indeed, if that exports you shared is correct, there is no `graphql-request/build/esm/types` anymore and you should be importing from `graphql-request/build/esm`, or pinning that library to the version you previously had installed.

**Comment by dummdidumm** [comment]
SvelteKit now uses `"moduleResolution": "bundler"` - with that, `tsconfig.json` reads the exports map now, so you need to adjust your imports to use just `graphql-request`

**Comment by frederikhors** [comment]
> Given that you've deleted your pnpm lockfile, it seems like you're probably installing a newer version of `graphql-request` that has a different structure -- indeed, if that exports you shared is correct, there is no `graphql-request/build/esm/types` anymore and you should be importing from `graphql-request/build/esm`, or pinning that library to the version you previously had installed.

Thank you for the answer.

I was already using the latest (6.0.1) version.

If I use `graphql-request/build/esm` as import path the error is the same, unfortunately.

**Comment by frederikhors** [comment]
> SvelteKit now uses `"moduleResolution": "bundler"` - with that, `tsconfig.json` reads the exports map now, so you need to adjust your imports to use just `graphql-request`

Thank you for the answer, @dummdidumm.

If I use just `graphql-request` the error is the same, unfortunately.

Can you please re-open the issue?

**Comment by dummdidumm** [comment]
You should probably do `import type { .. } from ..` instead. It looks like you only use this for the types, not actually as a runtime value.

**Comment by frederikhors** [comment]
> You should probably do `import type { .. } from ..` instead. It looks like you only use this for the types, not actually as a runtime value.

I'm already importing it as type, but it's the same error:

![image](https://github.com/sveltejs/kit/assets/41120635/e21ce520-c8df-4d7b-9710-0090d99197fb)

**Comment by frederikhors** [comment]
Maybe the issue is the `graphql-request` `package.json`:

```json
{
  "name": "graphql-request",
  "version": "6.1.0",
  "type": "module",
  "main": "./build/cjs/index.js",
  "exports": {
    ".": {
      "require": {
        "types": "./build/cjs/index.d.ts",
        "default": "./build/cjs/index.js"
      },
      "import": {
        "types": "./build/esm/index.d.ts",
        "default": "./build/esm/index.js"
      }
    }
  },
  "types": "./build/esm/index.d.ts",
  "packageManager": "pnpm@8.5.1",
  "files": [
    "build",
    "src"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/jasonkuhrt/graphql-request.git"
  },
  "keywords": [
    "graphql",
    "request",
    "fetch",
    "graphql-client"
  ],
  "author": {
    "name": "Jason Kuhrt",
    "email": "jasonkuhrt@me.com",
    "url": "https://kuhrt.me"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/jasonkuhrt/graphql-request/issues"
  },
  "homepage": "https://github.com/jasonkuhrt/graphql-request",
  "scripts": {
    "dev": "rm -rf dist && tsc --watch",
    "format": "pnpm build:docs && prettier --write .",
    "lint": "eslint . --ext .ts,.tsx --fix",
    "check": "pnpm check:types && pnpm check:format && pnpm check:lint",
    "check:types": "pnpm tsc --noEmit",
    "check:format": "prettier --check . && pnpm build:docs && git diff --exit-code README.md",
    "check:lint": "eslint . --ext .ts,.tsx --max-warnings 0",
    "prepublishOnly": "pnpm build",
    "build:docs": "doctoc README.md --notitle && prettier --write README.md",
    "build": "pnpm clean && pnpm build:cjs && pnpm build:esm",
    "build:cjs": "pnpm tsc --project tsconfig.cjs.json && echo '{\"type\":\"commonjs\"}' > build/cjs/package.json",
    "build:esm": "pnpm tsc --project tsconfig.esm.json",
    "clean": "tsc --build --clean && rm -rf build",
    "test": "vitest",
    "test:coverage": "pnpm test -- --coverage",
    "release:stable": "dripip stable",
    "release:preview": "dripip preview",
    "release:pr": "dripip pr"
  },
  "dependencies": {
    "@graphql-typed-document-node/core": "^3.2.0",
    "cross-fetch": "^3.1.5"
  },
  "peerDependencies": {
    "graphql": "14 - 16"
  },
  "devDependencies": {
    "@graphql-tools/schema": "^9.0.18",
    "@prisma-labs/prettier-config": "^0.1.0",
    "@tsconfig/node16": "^1.0.3",
    "@types/body-parser": "^1.19.2",
    "@types/express": "^4.17.17",
    "@types/json-bigint": "^1.0.1",
    "@types/node": "^20.0.0",
    "@types/ws": "^8.5.4",
    "@typescript-eslint/eslint-plugin": "^5.58.0",
    "@typescript-eslint/parser": "^5.58.0",
    "@vitest/coverage-c8": "^0.31.0",
    "apollo-server-express": "^3.12.0",
    "body-parser": "^1.20.2",
    "doctoc": "^2.2.1",
    "dripip": "^0.10.0",
    "eslint": "^8.38.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-config-prisma": "^0.1.0",
    "eslint-plugin-deprecation": "^1.4.1",
    "eslint-plugin-only-warn": "^1.1.0",
    "eslint-plugin-prefer-arrow": "^1.2.3",
    "eslint-plugin-simple-import-sort": "^10.0.0",
    "eslint-plugin-tsdoc": "^0.2.17",
    "express": "^4.18.2",
    "fetch-cookie": "^2.1.0",
    "get-port": "^6.1.2",
    "graphql": "^16.6.0",
    "graphql-tag": "^2.12.6",
    "graphql-ws": "^5.12.1",
    "happy-dom": "^9.7.1",
    "json-bigint": "^1.0.0",
    "prettier": "^2.8.7",
    "type-fest": "^3.8.0",
    "typescript": "^5.0.4",
    "vitest": "^0.31.0",
    "ws": "^8.13.0"
  },
  "prettier": "@prisma-labs/prettier-config"
}
```

Can you please re-open this @dummdidumm?

**Comment by dummdidumm** [comment]
This issue is unrelated to SvelteKit, and therefore stays closed. It's related to a type seemingly not existing in that library, or the types not being exposed correctly, or maybe you need to import a different type. It's appearing now because we changed the module resolution in the `tsconfig.json` to `bundler` which is the new recommended default by the TypeScript team for all application projects.
