### ISSUE TITLE
Sveltekit 2.0 breaks my quill editor

### ISSUE THREAD

**Issue by MuslemRahimi** [sveltejs/kit#11361]
### Describe the bug

For some reason after migrating to sveltekit 2.0 my quill editor looks completely chaotic. Don't know why

### Reproduction

![Screenshot from 2023-12-16 18-31-02](https://github.com/sveltejs/kit/assets/22890183/b3d895cd-a5fc-442f-80da-e579b029af46)

### System Info

```Shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 5.95 GB / 15.55 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    npm: 9.6.7 - /usr/bin/npm
    bun: 1.0.15 - /snap/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
  npmPackages:
    @sveltejs/adapter-vercel: ^4.0.2 => 4.0.2 
    @sveltejs/kit: ^2.0.0 => 2.0.0 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.0 => 4.2.8 
    vite: ^5.0.0 => 5.0.10
```

### Severity

blocking an upgrade

**Comment by MuslemRahimi** [comment]
Since I migrated to 2.0 I have only problems. Whoever reads this DO NOT MIGRATE!. It is still waayyy too early

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a code repository to will help us the diagnose the issue more easily.

**Comment by levinit** [comment]
maybe we should wait it some days， I upgrade my webapp to vite5+kit2， swSrc file is missing （not generated in .svelte-kit/output/clinet）. I have to downgrade kit and vite。

**Comment by eltigerchino** [comment]
If you can't provide a reproduction for the issue, there's no way to help troubleshoot or diagnose what the root cause is.

**Comment by eriknyk** [comment]
So sveltekit v2 is not ready to use it currently? I've migrated my projects that works prefectly in v1, in v2 stuck trying to fetch initial page, page loads never ends, what is awful situation, Rolling back to v1 and vite 4 for now. :-(
