### ISSUE TITLE
In `adapter-static`,  expand `<svlete:head>` statically into generated html files.

### ISSUE THREAD

**Issue by tqtifnypmb** [sveltejs/kit#11395]
### Describe the problem

In `adapter-static`, `<svlete:head>` is not expanded statically into generated html files, need executing the javascript to get final `<meta>` tags. In use cases where crawler won't run `js` code (twitter, for example), this behavior will make twitter card failed to show.

### Describe the proposed solution

Expand `<svlete:head>` that can be determined at compile time into generated html files.

### Importance

nice to have

**Comment by eltigerchino** [comment]
You need to enable SSR so that the page is rendered server-side during the prerendering process instead of returning an empty shell.
