### ISSUE TITLE
How can one get inlined web-workers?

### ISSUE THREAD

**Issue by FunMiles** [sveltejs/kit#1140]
I've tried examples of inlined web-workers from Vite 2. Unfortunately it does not work when trying to instantiate the worker.
Does Svelte-kit support web-workers? Here is what I tried:
```js
import MyWorker from '../workers/myworker?worker';
const worker = new MyWorker(); // This fails, giving a log that 'Worker is not defined'
```
`Worker` is a call from the source in Vite:
https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/worker.ts

**Comment by Conduitry** [comment]
It does work, just like that, but you need to make sure that you're only instantiating it on the browser. `Worker` doesn't exist on the server. Top-level code in a component gets run on both the server (as part of SSR) and on the browser.

**Comment by FunMiles** [comment]
@Conduitry thanks for the info. Could you however give an example how one can make sure it does not run on the server? That would be most helpful. Thanks.

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs#troubleshooting-server-side-rendering describes how to make sure code runs only on the browser.

**Comment by FunMiles** [comment]
A late addition to this for people who may find this thread. For an equivalent of `workerize-loader`'s convenient wrapping, I think [comlink](https://github.com/GoogleChromeLabs/comlink) is a convenient approach.
