### ISSUE TITLE
Relative link-path checking when building

### ISSUE THREAD

**Issue by iapyeh** [sveltejs/kit#1141]
In context of nested layout. Say, /routes/$layout.svelte and /routes/settings/$layout.svelte. Both $layout has menu. 

In /routes/$layout.svelte, it is
![image](https://user-images.githubusercontent.com/4695577/115332594-b78f0000-a1ca-11eb-9db0-da0bb2689e8e.png){:height="40px" width="100px"}

In /routes/settings/$layout.svelte. it is
![image](https://user-images.githubusercontent.com/4695577/115332650-cf668400-a1ca-11eb-941f-c2d913a73ab5.png)

This would not compile, because: compiler is looking for /settings/about.
![image](https://user-images.githubusercontent.com/4695577/115332669-de4d3680-a1ca-11eb-8dbc-1a00d37a065b.png)

One of the solutions I know is to use absolute path like this:
![image](https://user-images.githubusercontent.com/4695577/115332704-f02ed980-a1ca-11eb-8615-c7655d2a0b95.png)

But the absolute-path solution does not work if base-path is not empty string. For example in svelte.config.cjs:
![image](https://user-images.githubusercontent.com/4695577/115332764-13f21f80-a1cb-11eb-8c2f-4e03587cc4f2.png)

Because the resulting link should be "/foo/about", but not "/about" (now it is "/about").

The requesting feature is for compiler to looking for relative path. (not prefixing "about" to "/foo/about"). So that I can have 

/routes/$layout.svelte like this:
![image](https://user-images.githubusercontent.com/4695577/115334485-0c804580-a1ce-11eb-8144-d00a4533ef53.png)

/routes/settings/$layout.svelte like this:
![image](https://user-images.githubusercontent.com/4695577/115332890-4439be00-a1cb-11eb-80c8-5c9e38ae199c.png)

**Comment by Rich-Harris** [comment]
Yeah, links are always going to be relative to the current page. You should use absolute URLs for that reason. If you're using `paths` config, use the relevant imports:

```svelte
<script>
  import { base } from '$app/paths';
</script>

<nav>
  <a href="{base}">Home</a>
  <a href="{base}/about">About</a>
  <a href="{base}/settings">Settings</a>
</nav>
```

Please use code blocks rather than screenshots for sharing code samples in issues!
