### ISSUE TITLE
inlineStyleThreshold not working

### ISSUE THREAD

**Issue by StagnantIce** [sveltejs/kit#11444]
### Describe the bug

I m using post css modules, and write inlineStyleThreshold: 0, but i see what all my styles are inline, by the way in production mode all styles are in separated files.

### Reproduction

I m using post css modules, and write inlineStyleThreshold: 0, but i see what all my styles are inline, by the way in production mode all styles are in separated files.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 5.03 GB / 62.22 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.21.1 - /bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.17 - /bin/npm
  Browsers:
    Chrome: 116.0.5845.179
```

### Severity

serious, but I can work around it

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a code repository.

**Comment by gtm-nayan** [comment]
Styles are injected inline in dev mode to prevent FOUC

Closing as no reproduction was provided
