### ISSUE TITLE
v2 reproducibility issue with asset hash file names

### ISSUE THREAD

**Issue by peterpeterparker** [sveltejs/kit#11459]
### Describe the bug

When constructing a static bundle using SvelteKit version 2, the process results in the creation of assets with filenames that are not reproducible. Each build iteration leads to the generation of new filenames, distinguished by their unique hashes.

Additionally, attempts to define a custom file naming strategy through Rollup's [output-assetfilenames](https://rollupjs.org/configuration-options/#output-assetfilenames) configuration seem to be ineffective, as they do not produce the expected results.

### Reproduction

git clone https://github.com/peterpeterparker/my-app-hash
cd my-app-hash
npm ci
npm run build

// observe hash. e.g. build/_app/immutable/chunks/stores.GflRvHvF.js

npm run build

// observe new hash. e.g. build/_app/immutable/chunks/stores.nX1Zqub0.js

### Excpectation

Build should be reproducible and without any changes, should lead to always generate the same file names' hashes.

Furthermore, supporting Rollup option should allow developer to provide their own file name strategy.

### System Info

```Shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M2
    Memory: 2.08 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.1 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 120.0.6099.109
    Firefox: 121.0
    Safari: 17.1
  npmPackages:
    @sveltejs/adapter-static: ^3.0.1 => 3.0.1 
    @sveltejs/kit: ^2.0.6 => 2.0.6 
    @sveltejs/vite-plugin-svelte: ^3.0.1 => 3.0.1 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^5.0.10 => 5.0.10
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
This seems unlikely to be an issue in SvelteKit, but rather with Vite, so would probably be better reported there. See https://github.com/sveltejs/kit?tab=readme-ov-file#bug-reporting for more details

**Comment by peterpeterparker** [comment]
Vite 👉 https://github.com/vitejs/vite/issues/15555
