### ISSUE TITLE
Migrating to Sveltekit 2 cannot npm install after migration

### ISSUE THREAD

**Issue by JHethDev** [sveltejs/kit#11450]
### Describe the bug

Similar to https://github.com/sveltejs/kit/issues/11348#issue-2044509674 but deleting package-lock.json did not change the result.

### Reproduction

This is a private repo.

### Logs

```Shell
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: stakkz@0.0.1
npm ERR! Found: @sveltejs/adapter-auto@2.1.1
npm ERR! node_modules/@sveltejs/adapter-auto
npm ERR!   dev @sveltejs/adapter-auto@"^3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @sveltejs/adapter-auto@"^3.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @sveltejs/kit@2.0.6
npm ERR! node_modules/@sveltejs/kit
npm ERR!   peer @sveltejs/kit@"^2.0.0" from @sveltejs/adapter-auto@3.0.1
npm ERR!   node_modules/@sveltejs/adapter-auto
npm ERR!     dev @sveltejs/adapter-auto@"^3.0.0" from the root project
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 6.76 GB / 31.92 GB
  Binaries:
    Node: 21.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 120.0.6099.111
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.77)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 2.1.1
    @sveltejs/adapter-vercel: ^4.0.0 => 3.1.0
    @sveltejs/kit: ^2.0.0 => 1.27.6
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 2.5.3
    svelte: ^4.2.7 => 4.2.7
    vite: ^5.0.0 => 4.5.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This project was created on November 27th 2023 using `npm create svelte@latest`

**Comment by JHethDev** [comment]
Ran `npm upgrade` then `npm install` worked, all fixed.

**Comment by 205g0** [comment]
for others driving by, someting like `npm upgrade` won't work when you deploy, e.g. on Cloudflare, just `rm package-lock.json` and do `npm i` like mentioned in https://github.com/sveltejs/kit/issues/11348#issuecomment-1858634072

**Comment by Sk8rSeth** [comment]
> I am still having this issue. I get the same error when trying npm upgrade, I also removed package-lock.json and still no dice

+1 for the same situation.
seems like starting from scratch and bringing in the changed files for the site is perhaps the only option left

**Comment by gterras** [comment]
Just had the same error migrating after `npx svelte-migrate sveltekit-2`, got it working by removing `@sveltejs/kit` and `@sveltejs/vite-plugin-svelte` from package.json before `npm i`, then putting them back (then `npm i` again).
