### ISSUE TITLE
sveltekit 2 broke playwright tests

### ISSUE THREAD

**Issue by ivanafanasyeu** [sveltejs/kit#11454]
### Describe the bug

https://github.com/microsoft/playwright/issues/28781

### Reproduction

https://github.com/microsoft/playwright/issues/28781

### System Info

```shell
macOS
```

### Severity

blocking all usage of svelte

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a code repository.

**Comment by ivanafanasyeu** [comment]
https://github.com/microsoft/playwright/issues/28781 has to do this updated
