### ISSUE TITLE
Page hydration fails in Safari after SvelteKit v2 migration

### ISSUE THREAD

**Issue by MarkusThielker** [sveltejs/kit#11464]
### Describe the bug

After migrating to SvelteKit v2, the hydration of pages in the Safari browser fails.
The app continues to work properly in Chrome.

Ways to render the page:
- Removing the load function from the +layout.ts file causes the page to render, but in my case without texts as i18n was not loaded in the layout. It is not enough to just remove the content of the function, the function itself must also be removed.
- Moving the route content to a group fixes the problem of the page not being rendered. Thus /routes/(root)/+page.svelte is rendered, /routes/+page.svelte is not. Links and buttons don't work properly though. 

### Reproduction

The docker setup is not necessary for reproduction, but causes one extra error, which can be ignored.

1. Clone [MarkusThielker/ory-kit](https://github.com/markusthielker/ory-kit)
2. Navigate into the SvelteKit application directory: `cd ory-kit/authentication`
3. Copy the env file with `cp .env.example .env`
4. Run `npm install && npm run dev` to test the application before the migration. The app starts on http://localhost:4422.
5. Stop the development server and run `npx svelte-migrate@latest sveltekit-2`
6. Run `npm install && npm run dev` to test the application after migration (I had to remove 'node_modules' and 'package-lock.json' for `npm install` to run successfully)

Accessing the root page on http://localhost:4422 now fails in Safari, but works in Chrome.

#### Server
The server is not showing any errors.

#### Safari Logs:
```Shell
[Debug] [vite] connecting... (client, line 426)
[Debug] [vite] connected. (client, line 521)
[Warning] The next HMR update will cause the page to reload (client.js, line 2348)
[Error] ReferenceError: Cannot access uninitialized variable.
validate — exports.js:12
(anonymous function) — client.js:520

	handleError (app.js:35)
	handle_error (client.js:1488)
	(anonymous function) (client.js:2083)
[Warning] <Root> was created without expected prop 'form' (client.js, line 2348)
```

#### Chrome Logs: 
```Shell
client.ts:19 [vite] connecting...
client.ts:156 [vite] connected.
```

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 2.85 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    npm: 10.2.0 - /opt/homebrew/bin/npm
    bun: 1.0.10 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.2.1
```

### Severity

blocking an upgrade

**Comment by MarkusThielker** [comment]
The issue was cause by an unused import of an environment variable from "$env/dynamic/public", I had missed to remove.

**Comment by wbhob** [comment]
This seems like an issue that should stay open if the error message is incorrect. Others may face the same issue and not know what the heck is wrong!
