### ISSUE TITLE
error(404) in +server.ts doesn’t render +error.svelte

### ISSUE THREAD

**Issue by bfontaine** [sveltejs/kit#11474]
Hello,

### Describe the bug

```
$ npm list
my-app@0.0.1 /tmp/my-app
├── @sveltejs/adapter-auto@3.0.1
├── @sveltejs/kit@2.0.6
├── @sveltejs/vite-plugin-svelte@3.0.1
├── @types/eslint@8.56.0
├── @typescript-eslint/eslint-plugin@6.16.0
├── @typescript-eslint/parser@6.16.0
├── eslint-config-prettier@9.1.0
├── eslint-plugin-svelte@2.35.1
├── eslint@8.56.0
├── prettier-plugin-svelte@3.1.2
├── prettier@3.1.1
├── svelte-check@3.6.2
├── svelte@4.2.8
├── tslib@2.6.2
├── typescript@5.3.3
├── vite@5.0.10
└── vitest@1.1.0
```

I have a simple app with a form that `GET`s a `/?q=` page, which either redirects to the result or shows a 404. I have a `src/routes/+error.svelte` but it’s not rendered when I call `error(404)`; only when I go to a non-existing route like `/xxx`.

### Reproduction

Repository: https://github.com/bfontaine/svelte-app
This was created with `npm create svelte@latest` (skeleton app with TypeScript) where `src/routes` contains these two files:

`+error.svelte`:
```svelte
<h1>Oh oh!</h1>
```

`+server.ts`:
```typescript
import { error } from '@sveltejs/kit';

export async function GET() {
  console.log("in GET");
  error(404, { message: 'Not found' });
}
```

1. Clone the repository
2. `npm install`
3. `npm dev`
4. Open <http://localhost:5173/?q=aa>

Expected: you should see "Oh oh!"
Actual: you see the standard SvelteKit 404 page

### Logs

```
in GET
```

### System Info

```
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 5.25 GB / 15.31 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.8.0 - ~/.n/bin/node
    Yarn: 1.22.19 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 10.2.3 - ~/.n/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.1 
    @sveltejs/kit: ^2.0.0 => 2.0.6 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
See https://kit.svelte.dev/docs/routing#error - `+error` is only used for errors in `+page`s, not in `+server` routes.

**Comment by bfontaine** [comment]
@Conduitry thanks, then how can I work around this? I can’t migrate my app to Svelte because of this issue.
