### ISSUE TITLE
ContextAPI not working/updating context on a route with parameters 

### ISSUE THREAD

**Issue by carlosrafp** [sveltejs/kit#11481]
### Describe the bug

When you create a route with a dynamic parameter ('/my_route/[id]') and use ContextAPI to set a context on +page.svelte, if a child component calls goto ( from'$app/navigation') to the same route but different param the context is not updated on the child component.

The issue can be reproduced by:
https://stackblitz.com/edit/sveltejs-kit-template-default-7knglw

A workaround is to concatenate two goto calls to force new setContext

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-7knglw

### System Info

```Shell
sveltejs/kit: 2.0.0
svelte: 4.2.7
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior.

https://kit.svelte.dev/docs/load#rerunning-load-functions-when-do-load-functions-rerun The component is not re-created when you navigate to a new URL for the same route, and so `setContext` is not re-run.

https://svelte.dev/docs/svelte#setcontext Note also that context is not inherently reactive, and so just calling `setContext` will not be enough to cause that value to be picked up everywhere else.
