### ISSUE TITLE
cookies.set and cookies.get

### ISSUE THREAD

**Issue by jramiroz98** [sveltejs/kit#11484]
### Describe the bug

I'm trying to set a cookie the following way inside of my action aka +page.server.ts: 

`cookies.set('state', state, { path: '/', secure: false })`

Back in another route via a +server.ts i try the following:

`const expectedState = cookies.get('state');`

If i console.log(expectedState) i get `undefined`

### Reproduction

In my +page.server.ts
`OAuth2: async ({ locals, cookies, url }) => {
        const authMethods = await locals.pb.collection('users').listAuthMethods();
        if (!authMethods) {
            return { authMethods: '' }
        }
        const redirectURL = `${url.origin}/oauth`
        const googleAuthProvider = authMethods.authProviders[0]
        const authProviderRedirect = `${googleAuthProvider.authUrl}${redirectURL}`;
        const state = googleAuthProvider.state;
        const verifier = googleAuthProvider.codeVerifier;
        cookies.set('state', state, { path: '/', secure: false })
        cookies.set('verifier', verifier, { path: '/', secure: false })

        throw redirect(302, authProviderRedirect)`

in my +server.ts
```
export const GET = async ({ locals, url, cookies }) => {
	const redirectURL = `${url.origin}/oauth`;
	const expectedState = cookies.get('state');
	const expectedVerifier = cookies.get('verifier');
        console.log(expectedState)


```

Tried with a  +page.server.ts to fetch the cookies back and they where nowhere to be found.

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 326.43 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    pnpm: 8.6.0 - /usr/local/bin/pnpm
    bun: 1.0.7 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 120.0.6099.129
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.0 
    @sveltejs/kit: ^2.0.0 => 2.0.0 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^5.0.0-next.1 => 5.0.0-next.25 
    vite: ^5.0.3 => 5.0.10
```

### Severity

blocking an upgrade

### Additional Information

Thanks for your time!

**Comment by Conduitry** [comment]
Please provide a proper, minimal reproduction, in the form of a repo or a StackBlitz link, as directed in the issue template.

Have you checked whether the cookie appeared to be set in the browser and whether the issue seemed to be on the set side or the get side?

**Comment by jramiroz98** [comment]
Did tests and seems to work just fine. The problem with my code is the following line in my hooks file, which for some reason blocks my ability to set a cookie inside my actions.

`response.headers.set('set-cookie', event.locals.pb.authStore.exportToCookie({ secure: false }))`

**Comment by handsome-b-wonderful** [comment]
I had this problem because `response.headers.set` discards the cookie your trying to set in the form action, but you can have multiple `set-cookie` headers. Change your `+hooks.server.ts` to be
`response.headers.append('set-cookie', ...`
