### ISSUE TITLE
Unpin the Migration guide from the Discussions page

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#11486]
### Describe the problem

![image](https://github.com/sveltejs/kit/assets/47051820/156f3f7e-08a5-4879-9c29-14543b4a4f53)

The old migration guide prior to v1 is still pinned on top of the discussions page.

### Describe the proposed solution

Unpin the article. It is a locked article, so I cannot comment on it.

### Importance

nice to have

**Comment by benmccann** [comment]
done
