### ISSUE TITLE
Issue with running build for prod

### ISSUE THREAD

**Issue by paulGeoghegan** [sveltejs/kit#11491]
### Describe the bug

I was pushing a build to production and I got an error. After trying to run the production locally I found that when running the preview everything works fine but when trying to run the actual build I got:
Uh oh
This appeared on my browser and the dev build also works fine. I rolled back to a previous version of the app with older versions of sveltekit and vite so I know that it isn't my system.

### Reproduction

NA as it applies to any sveltekit project

### Logs

```Shell
> Using svelte-adapter-bun
  ✔ Start server with: bun ./build/index.js
  ✔ done
✓ built in 11.73s
vscode ➜ /workspaces/Envisionly-Website (main) $ bun ./build/index.js
Listening on 0.0.0.0:3000
709 |     }
710 |   });
711 | };
712 | var get_origin = function(headers) {
713 |   const protocol = protocol_header && headers.get(protocol_header) || "https";
714 |   const host = headers.get(host_header);
                     ^
TypeError: Invalid header name: ''
      at get_origin (/workspaces/Envisionly-Website/build/index.js:714:16)
      at ssr (/workspaces/Envisionly-Website/build/index.js:682:24)

709 |     }
710 |   });
711 | };
712 | var get_origin = function(headers) {
713 |   const protocol = protocol_header && headers.get(protocol_header) || "https";
714 |   const host = headers.get(host_header);
                     ^
TypeError: Invalid header name: ''
      at get_origin (/workspaces/Envisionly-Website/build/index.js:714:16)
      at ssr (/workspaces/Envisionly-Website/build/index.js:682:24)

^[[21;2~^[[21;2~^[[21;2~^[[B^[[B^[[21;2~^[[B^[[B
```

### System Info

```Shell
I am using bun so this didn't work but I am using the latest version of firefox with the following packages:
    "@sveltejs/kit": "^1.20.4",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-svelte": "^2.30.0",
    "prettier": "^2.8.0",
    "prettier-plugin-svelte": "^2.10.1",
    "svelte": "^4.0.5",
    "svelte-adapter-bun": "^0.5.0",
    "svelte-check": "^3.4.3",
    "tslib": "^2.4.1",
    "typescript": "^5.0.0",
    "vite": "^4.4.2"
    "cheerio": "^1.0.0-rc.12"
Here is my vite config:
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	server: {
		port: 8080
	}
});
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Thanks so much for any help!

**Comment by Conduitry** [comment]
Does this happen for you with Node or just with Bun? There have been several issues that people have reported where issues happened only in Bun, which is almost certainly going to be something Bun's end to address.

**Comment by paulGeoghegan** [comment]
I'm sorry I am only getting back to you now. I tried to use my Sveltekit project on Node but for whatever reason I couldn't install the Node adapter and all it said is that it couldn't resolve the dependancy. I'm following the command given on the official documentation and it installs every other package but it couldn't seem to install the Node adapter.
I had to use the --force flag just to get it to install.
Once I resolved this however I was able to build and run so this does seem like a BUN issue.
```
error during build:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'svelte-adapter-node' imported from /workspaces/Envisionly-Website-node/svelte.config.js
```

**Comment by ghostdevv** [comment]
> svelte-adapter-node

It's `@sveltejs/adapter-node` :pray:

**Comment by paulGeoghegan** [comment]
Yeh I didn't mean to include that. I was going to ask about it but I figured it out. I am still not sure why I can't install the Node adapter without using --force.
npm ERR! Could not resolve dependency:
5.601 npm ERR! peer @sveltejs/kit@"^2.0.0" from @sveltejs/adapter-node@2.0.2
5.601 npm ERR! node_modules/@sveltejs/adapter-node
5.601 npm ERR!   dev @sveltejs/adapter-node@"^2.0.2" from the root project
5.601 npm ERR!
5.601 npm ERR! Conflicting peer dependency: @sveltejs/kit@2.0.6
5.601 npm ERR! node_modules/@sveltejs/kit
5.601 npm ERR!   peer @sveltejs/kit@"^2.0.0" from @sveltejs/adapter-node@2.0.2
5.601 npm ERR!   node_modules/@sveltejs/adapter-node
5.601 npm ERR!     dev @sveltejs/adapter-node@"^2.0.2" from the root project
5.601 npm ERR!
5.601 npm ERR! Fix the upstream dependency conflict, or retry
5.601 
This has started causing problems with my docker builds now.

**Comment by ghostdevv** [comment]
@paulGeoghegan The version of adapter node you have installed requires SvelteKit version 2, either upgrade your SvelteKit or install an older version of adapter node with `npm install @sveltejs/adapter-node@1 -D`

**Comment by paulGeoghegan** [comment]
Ah okay perfect thanks!
