### ISSUE TITLE
Cloudflare adapter uses relative immutable asset paths

### ISSUE THREAD

**Issue by Caellian** [sveltejs/kit#11505]
### Describe the bug

I have a global style in `/+layout.svelte` file. All generated files work fine except for `404.html` on nested paths because immutable assets are imported using relative paths such as:
```html
<link href="./_app/immutable/assets/global_style_hash.css" rel="stylesheet">
```

So this works fine for routes like `domain.com/example` where `example` is substituted with the correct path to the asset, but routes like `domain.com/not/working` break because the resolved path of the asset ends up being `domain.com/example/_app/immutable/assets/global_style_hash.css` which doesn't exists.

### Reproduction

- Create an app with `404` route.
- Generate static content using Cloudflare (possibly other static adapters).
  - Host it.
- Navigate to `domain.com/some/non/existant/path`.
- Cry.

Example in the wild:
- Working: https://tinsvagelj.net/works
- Not working: https://tinsvagelj.net/works/not

The styles specified in `/+layout.svelte` don't apply:
```svelte
<style global lang="stylus">
  @import "../style/scheme";
  @import "../style/global";
</style>
```

### System Info

```Shell
System:
    OS: Linux 6.6 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750HF CPU @ 2.60GHz
    Memory: 8.50 GB / 15.53 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 21.5.0 - /usr/bin/node
    npm: 10.2.5 - /usr/bin/npm
  Browsers:
    Chromium: 120.0.6099.129
  npmPackages:
    @sveltejs/adapter-static: ~3.0 => 3.0.1 
    @sveltejs/kit: ~2.0 => 2.0.6 
    svelte: ~4.2 => 4.2.8 
    vite: ^5.0 => 5.0.10
```

### Severity

breaks applications in some cases

### Additional Information

Solution is probably adding a configuration option for specifying base path for immutable assets per bundle or `null` defaulting to current behavior as someone might host generated content on a nested route. Or use absolute paths but allow specifying base prefix.

**Comment by taikn** [comment]
I had exactly same issue with 404 page resources (.css, .js) not being loaded on nested paths. I was able to fix it by adding `kit.paths.relative: false` in `svelte.config.js` check the docs [here](https://kit.svelte.dev/docs/configuration#paths)

**Comment by Caellian** [comment]
The linked part of the docs basically describes exactly what I need/suggested. Thanks.
