### ISSUE TITLE
svelte/transition does not work on multi nested blocks

### ISSUE THREAD

**Issue by ptrtht** [sveltejs/kit#11518]
### Describe the bug

the transitions on elements do not work for doubly nested "svelte blocks".

Setup:
```
{#await promise}
   <!-- Redacted  -->
{:then value}
  {#if value}
    <button transition:slide={{ duration: 1000 }} />
  {/if}
{/await}
```

Expected:
Button animates with the slide effect for 1000s duration

Current:
Button does not animate at all.

See example repo.

### Reproduction

https://github.com/ptrtht/sveltekit-transitions-bug

### Logs

```Shell
There are no logs.
```

### System Info

```Shell
> npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 13.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 45.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 16.6
    Safari Technology Preview: 17.0
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.0 
    @sveltejs/kit: ^2.0.0 => 2.0.6 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10
```

### Severity

serious, but I can work around it

**Comment by brunnerh** [comment]
I think this is expected, you could use the `global` modifier here:
```svelte
<button in:fade|global={{ duration: 2000 }}>
```

> Transitions are `local` by default (in Svelte 3, they were `global` by default). Local transitions only play when the block they belong to is created or destroyed, not when parent blocks are created or destroyed.
