### ISSUE TITLE
Clarify invalidation behavior in universal load functions

### ISSUE THREAD

**Issue by realsuayip** [sveltejs/kit#11511]
### Describe the problem

Calling invalidation functions in load context seems to be undefined behavior since I could not find any documentation about it or any examples. I think it should not matter, since `load()` runs in client side, provided `browser` is `true`? Oddly, only the parent `load()` functions are run.

Also, for some reason, if you invalidate in `load()`, `navigating` is indefinitely set to `true`. 

### Describe the proposed solution

Clarify the behavior of invalidation calls in `load()` functions in documentation. 

### Importance

would make my life easier

### Additional Information

See related discussion for original context and the reasoning why I need to do this:

https://github.com/sveltejs/kit/discussions/11370

**Comment by eltigerchino** [comment]
I don't think you're suppose to run invalidate inside of a load function. Seems like that could cause an infinite loop with the load function invalidating itself, causing it to run again, and so on.
