### ISSUE TITLE
Customising use:enhance causes the action to run twice on the server.

### ISSUE THREAD

**Issue by Alii-isk** [sveltejs/kit#11520]
### Describe the bug

The form action should be called only once when submitting the form but its being called twice on the server whenever i Customize `use:enhance` .

**Additional Information:**
- I have tested this issue on multiple new SvelteKit projects, and the problem persists.
- The issue occurs consistently on both development and production builds.
- The issue do not occur when ` use:enhance ` used without any Customization .

### Reproduction

https://stackblitz.com/edit/node-nuzfoa

### System Info

```Shell
SvelteKit version: 2.0.0
Node.js version: v18.17.0
Operating System: windows 10.0.22621
```

### Severity

annoyance

**Comment by geoffrich** [comment]
This is happening because you're calling `formElement.submit()` inside your use:enhance callback. use:enhance already runs when the form is being submit; you don't need to submit the form again. This is causing the double-submit behavior you're seeing.

```svelte
<form
	method="post"
	use:enhance={({ formElement, formData, action, cancel, submitter }) => {
		// removing this makes the action only submit once
		//formElement.submit();
		return async ({ result, update }) => {
			// result
		};
	}}
>
```
