### ISSUE TITLE
Alternative to Worktop

### ISSUE THREAD

**Issue by barziahmed** [sveltejs/kit#11563]
### Describe the problem

It troubles me to see cloudflare-adapter relying on worktop as a dependency. Worktop is a one-man project that has not updated for one year and half! How can a production-grade enterprise web app be built on such package?

Sorry for my expression.

### Describe the proposed solution

Maybe we can use something like [Hono](https://hono.dev/) in place of Worktop

### Importance

would make my life easier

**Comment by benmccann** [comment]
The version we use was actually published 19 days ago: https://www.npmjs.com/package/worktop/v/0.8.0-next.16

No one's reported any problems with worktop that I recall, so I'm not sure why we should go through the code churn of changing libraries. If it's not broke don't fix it
