### ISSUE TITLE
@sveltejs/enhanced-img shows the same image if file name is the same

### ISSUE THREAD

**Issue by IAkumaI** [sveltejs/kit#11561]
### Describe the bug

If we place two images in two different routes and name the files the same, `<enhanced:img src="./image.png" />` on every page will show us the same image.

### Reproduction

Assume structure:
```
/routes/dir/one/+page.svelte
/routes/dir/one/image.png
/routes/dir/two/+page.svelte
/routes/dir/two/image.png
```

**one/image.png** and **two/image.png** are two different images, different files.
In every +page.svelte we place:
`<enhanced:img src="./image.png" />`

Of course, every enhanced:img has its own image file, but something goes wrong and both pages show the same image  The links are the same ( /@imagetools/080965fcd54cbb8c8fbb15c51a124bb77af1bad3 ). I suppose it generates hash from raw `src` and does not take into account real image path.

### System Info

```Shell
System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M1
    Memory: 33.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.3.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.199
    Safari: 17.1.2
  npmPackages:
    @sveltejs/adapter-node: ^2.0.2 => 2.0.2 
    @sveltejs/enhanced-img: ^0.1.7 => 0.1.7 
    @sveltejs/kit: ^2.1.0 => 2.1.0 
    @sveltejs/vite-plugin-svelte: ^3.0.1 => 3.0.1 
    svelte: ^4.2.8 => 4.2.8 
    vite: ^5.0.11 => 5.0.11
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
Hmm, I don't see anything that would cause that:
https://github.com/JonasKruckenberg/imagetools/blob/04613e4af6aa65f3c1087e38b30390b747d6ec43/packages/vite/src/utils.ts#L11C23-L11C38

Can you please share a repository that reproduces this issue? Per the issue template, we don't have time to look at issues where we have to go through the steps of creating a project to reproduce the issue as there's 600+ open issues and only a few of us

**Comment by IAkumaI** [comment]
Here the example: https://github.com/IAkumaI/enhanced-img-hash-example

As mentioned above we have two routes /one and /two
Each +page.svelte has `<enhanced:img src="./image.png" />` but src is relative, so image.png is different in every route.
And it shows "One" image at the Two page, as you can see.

Second image on each page shows the real one (src="./image.png?randomhash")

**Comment by benmccann** [comment]
Thank you! Very helpful

I'm guessing the issue is coming from here:

https://github.com/sveltejs/kit/blob/d93eb42bee7fd06d4d3f7e3dde7381ab032b076c/packages/enhanced-img/src/preprocessor.js#L27

**Comment by IAkumaI** [comment]
I found it:
https://github.com/sveltejs/kit/blob/d93eb42bee7fd06d4d3f7e3dde7381ab032b076c/packages/enhanced-img/src/preprocessor.js#L89

This cache uses just "url" as a key, which is just a relative path(and the same value). It should use full `id` from `resolve` or something.

**Comment by IAkumaI** [comment]
I made the PR. It works for me locally. Tests are fine. Hope this helps.

Btw, is there any way to make prettier do not touch your imports? My prettier wants to remove spaces around braces in imports and rearrange them.
