### ISSUE TITLE
Allow any numeric value for BODY_SIZE_LIMIT in adapter-node

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#11580]
### Describe the problem

From #11381 — it's unlikely but conceivable that someone would want to set a body size limit of zero. More to the point, it's arguably a bit weird that '0' actually means 'Infinity'.

It's also reasonable that someone would want to do something like `BODY_SIZE_LIMIT=1e6` to express 'a megabyte'.

### Describe the proposed solution

Allow any numeric JavaScript value, using `parseFloat`. Error if this results in `NaN`.

**Comment by codenoid** [comment]
ok let me take a look

**Comment by Rich-Harris** [comment]
closed via #11589
