### ISSUE TITLE
Include the return value of load in the HTML instead of everything that was fetched

### ISSUE THREAD

**Issue by ion1** [sveltejs/kit#1158]
**Is your feature request related to a problem? Please describe.**

I have a database of about 150 small items – in this case, data pertaining to events and abilities in a game, but you could also think of other databases like a family tree or the catalogue of books in a library.

I wish to generate a website with an individual page for each item.

The database is highly compressible, only taking up less than 10 kB in total with gzip or brotli (it's less than 100 kB uncompressed). I would prefer it if the website fetched the whole database once rather doing a round trip for a < 0.5 kB item on every navigation.

If I `fetch` the database in `load` and only return the part relevant to the current page, the entire database seems to be included in a `<script type="svelte-data" url="/data.json">` in the prerendered HTML, which means that every one of the ~150 HTML pages will be bloated by about 10 kB (when compressed). However, only the much smaller return value of `load` is needed to hydrate the page.

If the user is browsing without JavaScript support, it feels excessive to embed the whole database in every page they load.

**Describe the solution you'd like**

Embed the return value of `load` in the HTML for hydration rather than including the whole `/data.json`.

The frontend can then fetch `/data.json` upon a navigation to another page and cache it for further navigations.

**Describe alternatives you've considered**

One option is to keep the current behavior and let the database be embedded in every HTML page, resulting in a bloated HTML size.

Another option is to fetch `/data/[id].json` on every navigation, resulting in round trips when a one-time fetch of < 10 kB would have sufficed.

**How important is this feature to you?**

I can live without this, but it would be nice to have.

**Comment by Conduitry** [comment]
Serializing the return value from `load` was what was done in Sapper, and SvelteKit switched to serializing the response from the endpoint for the reasons given in https://github.com/sveltejs/kit/issues/3#issuecomment-738446901

The case of fetching a lot of data, only some of which is used comes up in https://github.com/sveltejs/kit/issues/3#issuecomment-738650921 and is addressed in the next comment. Granted, this doesn't specifically speak to your case where the data can be cached.

However, the benefits of serializing the response seem to outweigh those or serializing the return in general, and having some way to configure this would makes things more confusing for a lot of people, with only modest benefits in certain specific cases. So, thank you for the suggestion, but I am going to close this.

**Comment by ion1** [comment]
Thanks for your response! For now, I can pregenerate `data.json`, put it into `src` and `import` it, which is close enough.

Maybe I should look into writing a Vite plugin which produces the JSON in an importable form during the build.
