### ISSUE TITLE
Include .gitignore in blank template

### ISSUE THREAD

**Issue by makuzaverite** [sveltejs/kit#1159]
When starting out a new project using blank template it's really frustrations that the current version of cli doesn't come with a 
 .gitingore file which is really helpfully

**Comment by Conduitry** [comment]
This is the same as #1036 which was supposed to have been fixed in #1084. But I am still seeing this file missing on the latest version of create-svelte.

**Comment by Rich-Harris** [comment]
this is weird as hell — it seems to be writing the file, but renaming it to `.npmignore`. i have no idea how this could be happening

**Comment by Rich-Harris** [comment]
ugh. apparently this is [something that npm does when it packages things up](https://github.com/npm/npm/issues/1862), instead of, y'know, just interpreting the .gitignore as an .npmignore. how helpful.
