### ISSUE TITLE
Sveltekit internal paths import suggestions

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/kit#11607]
### Describe the bug

When using ctrl+space to auto import a variable, sveltekit internal paths are suggested.
e.g. `base` from `$app/paths` or `building` from `$app/environment`

### Reproduction

![grafik](https://github.com/sveltejs/language-tools/assets/196478/55c12110-a909-49d4-ba37-395bd7aa41a4)

### Expected behaviour

Hide paths starting with `__sveltekit/`

### System Info

- OS: Linux
- IDE: VSCode
- Svelte: 5.0.0-next.33
- Sveltekit: 2.3.0

### Which package is the issue about?

svelte-language-server

**Comment by dummdidumm** [comment]
I think the better solution is to fix this inside SvelteKit itself and change the imports/exports such that the internal module declarations don't end up in the bundled types.

**Comment by Rich-Harris** [comment]
Any thoughts on how we could do that? Would love to fix this, it's annoying
