### ISSUE TITLE
Get access to Vite mode in `svelte.config.js`

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#11603]
### Describe the problem

When setting the CSP config it is desired to know the current mode ("development", "staging", "production" etc). 

Real world example for needing this is setting `sentry_environment` in the [Security Police Reporting](https://docs.sentry.io/product/security-policy-reporting/#additional-configuration) from Sentry.

### Describe the proposed solution

Make it possible to get the current Vite mode in `svelte.config.js`. This would also help with getting access to the env-files with the [loadEnv](https://vitejs.dev/guide/api-javascript.html#loadenv) method

### Alternatives considered

It's possible to get access to the mode like this:

```ts
const mode = process.env.VITE_ENVIRONMENT ?? process.env.NODE_ENV;
```

But it feels kinda hacky

### Importance

would make my life easier

### Additional Information

It's possible to get access to the Vite mode in the `vite.config.js` file. Would it be possible to pass it down via the `sveltekit` Vite plugin and then make it accessible through the `load_config` method?

<img width="236" alt="image" src="https://github.com/sveltejs/kit/assets/48158184/a0d1a242-2a41-4c87-885c-e88b6770a42b">

**Comment by benmccann** [comment]
You can create your own `VITE_ENVIRONMENT` variable and then run `vite build --mode ${VITE_ENVIRONMENT}`, which is probably easier than us updating the Svelte config API

**Comment by kane81** [comment]
It would be good if we could pull the mode out....

there is a 
`export default ({ mode }) => {`
https://stackoverflow.com/questions/66389043/how-can-i-use-vite-env-variables-in-vite-config-js

but I am not sure how to use this in svelte.congif.js ....
