### ISSUE TITLE
load function does not respect returned error status codes

### ISSUE THREAD

**Issue by kamholz** [sveltejs/kit#1161]
According to the docs, a page's `load` function can return an error via `{ status: 4xx }`. However, the following test page component fails to work:

```js
<script context="module">
  export async function load({ session }) {
    if (!session.user) {
      return { status: 401 };
    }
    return {};
  }
</script>
```

Instead of returning status 401, the page returns status 200 and renders anyway. If I change it to something like `return { status: 302, redirect: 'https://google.com' }` then it does redirect, so this seems to just be an issue with error codes?

**Comment by danawoodman** [comment]
Can confirm this on `1.0.0-next.84`:

```html
<script context="module">
  export async function load() {
    return { status: 401 }
  }
</script>
```

Returns `200`

**Comment by lukasIO** [comment]
have you tried setting the `error` object additionally to the status code?

**Comment by kamholz** [comment]
> have you tried setting the `error` object additionally to the status code?
> 
> > If something goes wrong during load, return an Error object or a string describing the error alongside a 4xx or 5xx status code.

Yes. It doesn't make a difference.

**Comment by kamholz** [comment]
> Yes. It doesn't make a difference. Also, setting the `error` is not required in endpoints, so it should be consistent.

Correction, it does work now when I return `error` as well (not sure why it wasn't before). This should definitely be standardized between pages and endpoints if possible, because I'm sure other people will be confused by this at some point.

**Comment by Rich-Harris** [comment]
The place to append an error for `4xx`/`5xx` status codes is here, if anyone would like to open a PR that fixes this: https://github.com/sveltejs/kit/blob/32b3fcde3c206347d0ca58ea2f8ecec649f5b7f5/packages/kit/src/runtime/load.js#L5-L8

**Comment by bedewilson** [comment]
Failing test has been developed in #1355 but implementation of the fix is still pending. I closed the PR until this is done.

**Comment by damain** [comment]
Looking at taking up this issue, but what is the intended behavior?

Should you be able to able to send a 4xx status without an error?
Should a 4xx status without an error also trigger the appropriate error to be generated?

**Comment by kamholz** [comment]
Yes, you should be able to send a 4xx status without specifying the `error`. SvelteKit should set it to a default value in that case (whatever the standard message is for each error, I suppose).

**Comment by damain** [comment]
I did the following statuses are there any others that should be addressed

```
switch (status) {
				case 400:
					errorMessage = 'Bad Request';
					break;
				case 401:
					errorMessage = 'Unauthorized';
					break;
				case 403:
					errorMessage = 'Forbidden';
					break;
				case 404:
					errorMessage = 'Not Found';
					break;
				case 409:
					errorMessage = 'Conflict';
					break;
				default:
					errorMessage = 'Internal Server Error';
					break;
			}
```

**Comment by kamholz** [comment]
I would think we should do all of the 4xx codes in the HTTP standard?

**Comment by damain** [comment]
Added all http statuses from 400 to 599, if status within range but not valid it defaults to 500 Internal Server Error

**Comment by damain** [comment]
Just an update, it was decided that all the HTTP codes would not be generated automatically as the code to do this would add 3.7kb to the client library and would not be needed by every developer using the svelte kit. There are other libraries like http-status-codes that can be used to generate the error messages.

**Comment by kamholz** [comment]
I see. Does this mean that `load` will now require `error` to be set in the return value?

**Comment by damain** [comment]
No, we are setting it to generate the error. "Internal Server Error". But in order to present a proper error message, you should send an error or create your custom __error page

**Comment by damain** [comment]
This no longer generates an Internal Server Error. It passes on the status with an error object but no error message.

**Comment by delay** [comment]
So has this been fixed?  I noticed it seems to deal with status codes correctly if the function returns the value quickly without async.  But when you add in an async function like with a database call, it always returns a status of 200 even when setting the error message to a 4xx error.  It just seems to ignore the status that is set.

**Comment by seakrebel** [comment]
I have exactly the same issue as @delay

**Comment by DePasqualeOrg** [comment]
I'm also having this issue.
