### ISSUE TITLE
Preview Mode

### ISSUE THREAD

**Issue by rinti** [sveltejs/kit#1162]
**Is your feature request related to a problem? Please describe.**
CMS:es has preview functionality, and Svelte Kit should support it natively. [Here's an example of how Next does it](https://nextjs.org/docs/advanced-features/preview-mode).
As an example the CMS I use has previews on the url `/cms/pages/4/edit/preview/` and it's not clear (to me at least) how I would go about to make the preview work here. I don't think creating a `/cms/pages/[id]/edit/preview/` route is the correct solution.

**Describe the solution you'd like**
I'd like a clear way of handling previews in Svelte Kit

**Describe alternatives you've considered**
Various workarounds

**How important is this feature to you?**
I could live without it.

**Comment by babichjacob** [comment]
Is SvelteKit even affected by this problem that Next.js needed to engineer a specific solution for?

**Comment by rinti** [comment]
You're actually right. I managed to solved this pretty cleanly.
