### ISSUE TITLE
Svelte 5: $effect doesn't run on updates in sveltekit but works properly in svelte 5 REPL

### ISSUE THREAD

**Issue by amit13k** [sveltejs/kit#11628]
### Describe the bug

effect does not run when the object is modified using bind. This issue doesn't occur in svelte 5 repl and only happens in sveltekit.

Sample code
```svelte
<script lang="ts">
import NestedComponent from "./nested-component.svelte"
let values = $state({});

$effect(() => {
	// effect only runs once and not on updates in svelte kit
	// this issue doesn't occur in the svelte 5 repl
	console.log('running effect', values);
});

// inspect logs all the updates to the object
$inspect(values);
</script>

<NestedComponent bind:value={values['x']} />
```

### Reproduction

[Sveltelab SvelteKit with Svelte 5 with this problem](https://www.sveltelab.dev/wov8bvjwgabdp64)
[Svelte 5 REPL without this problem](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE42RwW7bMAyGX4UQAthFvXiXXbLYQLFTL32BqAdHphO1MilIVJHC8LsPst0OaC87kvz58wP_SQ3WYVSH06SoG1Ed1IP3qlLy7nMR39AJqkpFTsHkzjGaYL2A6-jSaCVRq1aTHT0HgSeMgv0fHj0TksAQeASt9jUtgx_mY7JfjbXS5FDgrXMJIzSwi9IJltN891uTph0OAxopyztoWpg0aalrWJvA5N4hJIrAZBA66oE4tyH5vhOMYAnWO69Wtl252gg2xoTQM0YqBNiYFLJWrrjp4RcE9C7vGKbIDveOL2UREpGly0ZQVBt4ht2I6xosRZ_5HF8idM4tvh9IwkvJ5xc0omm3ict_Rsd6_XCb7Y5fP3q21B8WcTOtO6fiVjzPULeaVKVG7u1gsVcHCQnn6jPWrwn8R8aZQPC2JPuZEjTw8xvlOYkw5RycNa_NtOa16O_v5_aRTMARSY71qmy_kz7PfwF99MzbjAIAAA==)

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M2 Pro
    Memory: 156.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.11.0 - ~/Library/pnpm/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.216
    Chrome Canary: 122.0.6241.5
    Safari: 17.3
```

### Severity

blocking an upgrade

**Comment by brunnerh** [comment]
That is expected (if you know why it happens) and unrelated to SvelteKit.

The REPL uses `JSON.stringify` for the console drawer, this means that every property of the `$state` is evaluated which each have their own signal. A regular `console.log` does not do this, so the effect would only run on an assignment to `values` itself.

If you want the same behavior locally, also use
```js
console.log('running effect', JSON.stringify(values))
```

**Comment by amit13k** [comment]
> That is expected (if you know why it happens) and unrelated to SvelteKit.
> 
> The REPL patches `console.log` and uses `JSON.stringify` for the console drawer, this means that every property of the `$state` is evaluated which each have their own signal. A regular `console.log` does not do this, so the effect would only run on an assignment to `values` itself.
> 
> If you want the same behavior locally, also use
> 
> ```js
> console.log('running effect', JSON.stringify(values))
> ```

Thanks for the details regarding this. I understand it now. Does this seem to be a proper way to execute some code whenever something changes in values or is there a better/clean way to do this (when conveniently using bind to modify the object properties)?

```svelte
$effect(() => {
	JSON.stringify(values);
	
	untrack(() => {
		// execute some code whenever values changes
	});
});
```

[Sveltelab](https://www.sveltelab.dev/mnv4v9aajhw5g49)

**Comment by brunnerh** [comment]
If you don't need to track deeply nested changes, I would use something like `Object.values(values)` instead; no need to generate JSON that is not being used.

**Comment by amit13k** [comment]
Thank you. Closing as unrelated to SvelteKit.

**Comment by danawoodman** [comment]
Is there a related issue for this in Svelte?

This seems to go completely against the documentation which state it should log if the value changes, which it clear does (bind updates the `$state` rune's value), confused why this isn't at least considered a bug in Svelte?

![Image](https://github.com/user-attachments/assets/e0e00bbe-8dbd-4a69-b664-2e47c130759b)

**Comment by brunnerh** [comment]
> I'm seeing an issue where $inspect does not log values updated by bind

If `$inspect` is not behaving according to the documentation, please open a new issue (in the Svelte repository) and provide the necessary reproduction. `$inspect` does not evaluate class instances deeply just plain objects/arrays, maybe you ran into that (though manually adding a `toJSON()` can help here - [example](https://svelte.dev/playground/untitled?version=5.18.0#H4sIAAAAAAAACm2PTWvDMAyG_4oQPSQQ0rubDnbdYTuMscOyg5tqzOAqxlK6jOD_PuwsFMZOgkfvh7Qg2wuhwRdWp57O2OCH8yRo3hbU75B3GWCzKe9DaOVKXjM7WaH_-DCyEqugwU6G6ILe9dzr4K0IvEYbAkVYMur1av1EcISdqFWq6p5XruPD89NjVW-6XiPpFBkWKBYD-umkXe1p1ZSRDqVrZFGYb8G_MY6ZogGmr-2Qqm6KrT6s1TvHEmjQas6k298e4M5xmBROjs-mFB-XuS2J6x0J9kX3h2KDSrOi0ThRek8_61Qx03cBAAA=)).

A related issue:
- https://github.com/sveltejs/svelte/issues/14988

It looks like there should at least be a caveat in the docs about classes (unless `$inspect` is changed to account for that).
