### ISSUE TITLE
docs: duplicate error, fail sections

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#11636]
### Describe the bug

For some reason, there are duplicate [error](https://kit.svelte.dev/docs/modules#sveltejs-kit-error) and [fail](https://kit.svelte.dev/docs/modules#sveltejs-kit-fail) documentations.

![image](https://github.com/sveltejs/kit/assets/47051820/985bba3b-31cc-48f3-bff1-e3308af645c7)

### Reproduction

- https://kit.svelte.dev/docs/modules#sveltejs-kit-error
- https://kit.svelte.dev/docs/modules#sveltejs-kit-fail

### System Info

```Shell
Not applicable
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Closing as duplicate of #7853
