### ISSUE TITLE
Svelte component type in a +page.ts file

### ISSUE THREAD

**Issue by emrergin** [sveltejs/kit#11634]
### Describe the bug

While I was following Rich's one of the examples here: https://stackblitz.com/edit/sveltejs-kit-template-default-c4ybjv?file=src%2Froutes%2Fblue%2F%2Bpage.svelte,src%2Froutes%2Fgreen%2F%2Bpage.svelte,src%2Froutes%2Fgreen%2FGreen.svelte,src%2Froutes%2Fgreen%2F%2Bpage.js,src%2Froutes%2Fblue%2F%2Bpage.js,src%2Froutes%2Fblue%2FBlue.svelte,src%2Froutes%2F%2Blayout.svelte&terminal=dev

I hit into a deadend. Specifically, even though my types work everywhere else, importing a Svelte file to a data loader does not work. This idea is explored more detail here: https://github.com/sveltejs/kit/issues/627#issuecomment-1458539744

I don't know what is missing currently that does not allow me this use.

Thanks in advance!

Attached is an image of my use, together with the related error.
![image](https://github.com/sveltejs/kit/assets/77497958/8f4c1111-063b-4bcf-9ae3-8a8d5d9bec8e)

I also asked for help from the discord before this report, and tried a lot of things before deciding to do a bug report.

It is important to note that, the code works as expected except this error message.

### Reproduction

1. Start a fresh sveltekit application using ```npm create svelte@latest my-app &&
cd my-app &&
npm install &&
npm run dev```
2. Open the project in VScode.
3. Import a svelte file at the beginning of a ts file.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.65 GB / 15.89 GB
  Binaries:
    Node: 20.9.0 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 4.0.2 - ~\scoop\apps\nodejs-lts\current\yarn.CMD
    npm: 10.1.0 - ~\scoop\apps\nodejs-lts\current\npm.CMD
    pnpm: 8.14.1 - ~\scoop\apps\nodejs-lts\current\pnpm.CMD
  Browsers:
    Chrome: 120.0.6099.217
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.0
    @sveltejs/adapter-vercel: ^4.0.4 => 4.0.4
    @sveltejs/kit: ^2.0.0 => 2.0.6
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1
    svelte: ^4.2.7 => 4.2.8
    vite: ^5.0.3 => 5.0.11
```

### Severity

annoyance

### Additional Information

It is important to note that, the code works as expected except this error message.

**Comment by eltigerchino** [comment]
Please include a minimal reproduction in the form of a stripped down code repository.
