### ISSUE TITLE
Feature Request: Dynamically load compiled Svelte components in SSR

### ISSUE THREAD

**Issue by kahverengi001** [sveltejs/kit#1164]
**Is your feature request related to a problem? Please describe.**
Yes for CMS software. When you create a CMS, you need to provide any of these: themes, customization, widgets, and more 3rd party integrations.
Currently, it is possible to dynamically import a component compiled with UMD format on the client side. But not the same on the server-side, it will throw an error like this, if you try to import it: `Cannot find module 'http://localhost:8088/assets/js/index.js' from '/home/kahverengi/Projeler/Pano/Pano Web Platform UI/vanilla-theme/src/routes'`

The SSR should have to be able to dynamically import compiled Svelte components. For the rendering content in the server.

**Describe the solution you'd like**
Just simply a possibility to dynamically import like this: 

```
import("http://localhost:8088/assets/js/index.js").then((w) => {
      Widget = w.default
    });
```

**Describe alternatives you've considered**
I don't see any other options.

**How important is this feature to you?**
Fairly severe, it is important for SSR rendering CMS software.

**Additional context**
I'm not sure is it correct to open for Kit repo, but the problem is kit uses the SSR component API.

**Comment by benmccann** [comment]
I would expect you can dynamically import a Svelte component. However, Svelte components should not be pre-compiled. Also, ESM should be preferred over UMD

This sounds like a usage issue to me. Please ask for help on Discord

If you still think there's a bug here after trying those tips and asking on Discord, please provide a repo to reproduce this
