### ISSUE TITLE
Unnecessary error during build

### ISSUE THREAD

**Issue by alkorlos** [sveltejs/kit#11659]
### Describe the bug

Hello

Have `fonts` in static folder, need use it in `.svelte` file.
```css
src: url("./fonts/OpenSans-Italic.woff2") format("woff2");
```

This style work in `dev` and `build` mode, but in `build` have error:
```
./fonts/OpenSans-Regular.woff2 referenced in path/src/routes/+page.svelte?svelte&type=style&lang.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
```

That is, everything works correctly, but with an error.

Absolute paths work without error.
Not sure this is problem SvelteKit or Vite and don`t now how check it, but don't see this error in SvelteKit or Vite repository.

If this is Vite error, tell me please how get it without SvelteKit, I open issue in Vite repository.

### Reproduction

https://github.com/alkorlos/svelte-issue-bug-relative-path

`npm create svelte@latest svelte-issue-bug-relative-path` Skeleton project
Put font in `static\fonts` and `@font-face` in `+page.svelte`
This is all.

### Logs

```Shell
./fonts/OpenSans-Regular.woff2 referenced in path/src/routes/+page.svelte?svelte&type=style&lang.css didn't resolve at build time, it will remain unchanged to be resolved at runtime
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 3.48 GB / 15.85 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.121)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.0
    @sveltejs/kit: ^2.0.0 => 2.3.3
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1
    svelte: ^4.2.7 => 4.2.9
    vite: ^5.0.3 => 5.0.11
```

### Severity

annoyance

**Comment by benmccann** [comment]
> Not sure this is problem SvelteKit or Vite and don`t now how check it, but don't see this error in SvelteKit or Vite repository.
If this is Vite error, tell me please how get it without SvelteKit, I open issue in Vite repository.

This sounds likely to be an issue in Vite. Please see https://github.com/sveltejs/kit?tab=readme-ov-file#bug-reporting

**Comment by alkorlos** [comment]
Yes, maybe it is Vite, maybe SvelteKit wrong use Vite cofig or Rollup config. I see [bug reporting](https://github.com/sveltejs/kit?tab=readme-ov-file#bug-reporting), but I still don’t understand exactly what’s going on. I'll try again soon.

I work with Vite and never see this. In SvelteKit this error in very simple case. Judging by mistake relative paths not work with static  folder, it took me a while to realize that the error was incorrect. SvelteKit great tool and even if the error is not in it, now error hurting him first, It would be nice to understand what's going on, and probably create other issue.

**Comment by benmccann** [comment]
I see. It's not a bug at all, but a usage issue. It works if you do `url("../../static/fonts/OpenSans-Regular.woff2")` and I'm guessing `url("/static/fonts/OpenSans-Regular.woff2")` would also be likely to work.

See https://vitejs.dev/guide/assets#importing-asset-as-url for more details:

> `url()` references in CSS are handled the same way.

**Comment by alkorlos** [comment]
`url("/static/fonts/OpenSans-Regular.woff2"` and `url("/fonts/OpenSans-Regular.woff2"` work, but after build we have absolute paths, not relative, it is different situation. I wrote about this in issue.

`url("../../static/fonts/OpenSans-Regular.woff2")` work with same error:
```
../../static/fonts/OpenSans-Italic.woff2 referenced in path/src/routes/styles/base.pcss didn't resolve at build time, it will remain unchanged to be resolved at runtime
```

Understand what's wrong. `static` is default `public` folder from vite:
> [public](https://vitejs.dev/guide/assets#the-public-directory) Vite
> You should always reference public assets using root absolute path.

It's strange that there is no way to access the file by relative path but it's a mechanism Vite. For that reason didn't use public.

Maybe change description `static` in documentation? Write that it only works with absolute paths and is `public` folder from Vite. I think this would be useful.
