### ISSUE TITLE
Can’t import $app/environment.js

### ISSUE THREAD

**Issue by Mark2M** [sveltejs/kit#11655]
### Describe the bug

I just ran “npm update” and now I can’t start my app. Something, possibly not svelte, has broken. All I get is an error stating environment.js couldn’t be found. Anyone know where I can look for a fix?

### Reproduction

NA

### Logs

```shell
NA
```

### System Info

```shell
MacOS (latest), NodeJs (latest)
```

### Severity

blocking all usage of svelte

**Comment by dummdidumm** [comment]
`environment.js` changed to `environment/index.js` recently, but that shouldn't have any user-noticeable effects AFAIK. What happens if you delete your `.svelte-kit` directory and try again? If that does work, please confirm, otherwise we need a proper reproduction.

**Comment by Mark2M** [comment]
Thank you again, you’re a star (not the first time you helped me out).  

I changed all the imports and it worked straight away. I’d a;ready tried deleting the .svelte-kit, node_modules and package lock but nothing else helped.

sidetracking though… for the last year (I’m on a fairly big project) every time we run an npm update (that actually updates), the app crashes on first load and then works if stopped and restarted. No biggie, but annoying.

anyway, thanks again

**Comment by dummdidumm** [comment]
> I changed all the imports and it worked straight away

What do you mean by that? You shouldn't have to update any `$app/environment` imports, if that's the case then we need a reproducible because that would be a bug

**Comment by Mark2M** [comment]
That's exactly it. I had to modify the import path to include "/index.js" in every component that uses it Cheers MarkOn 17 Jan 2024, at 21:56, Simon H ***@***.***> wrote:﻿

I changed all the imports and it worked straight away

What do you mean by that? You shouldn't have to update any $app/environment imports, if that's the case then we need a reproducible because that would be a bug

**Comment by dummdidumm** [comment]
Could you provide a reproducible then? Because that doesn't sound right. You should be able to leave your imports as `$app/environment`

**Comment by Mark2M** [comment]
Will do... sorry for being slow, I won't get time for another hour or two. CheersMarkOn 18 Jan 2024, at 09:50, Simon H ***@***.***> wrote:﻿
Could you provide a reproducible then? Because that doesn't sound right. You should be able to leave your imports as $app/environment

**Comment by Mark2M** [comment]
Ok... so I'm finally sat in front of a computer and have more info (and a repo below). 

1) I created a stripped down version of the app so there's just one page with the environment import and I still get the error.

2) I created a brand new app, added the import and it worked fine. Note that the both old and new import formats work on this version. Odd or just some cool code perhaps? I.e.: ```import { dev } from '$app/environment.js';``` and  ```import { dev } from '$app/environment/index.js';```

3) I deleted my node_modules in the stripped down version and the actual app, reran ```npm install;``` and both still have the problem.

So, here you go... **there's a repo, the stripped down app, that still has the problem, here: https://github.com/Mark2M/environment-import-test**

Bear in mind I got the error after running ```npm update```, i.e. the paths weren't updated (or mapped?) to ```$app/environment/index.js``` (if that's what's supposed to happen) so I got file not found etc.

Let me know if there's anything else I can do. The full error message is at the bottom.

Regarding the second issue, this only happens after an update. I can't guarantee the stripped down repo would suffer the same problem on the next update. The error message on crash relates to a mongoose model (not always the same one, and definitely not anything recently modified), the error message being something about changing the model after it's been initialized, it happens as soon as mongoose creates the connection and attempts a read (I'll copy it over next time it happens if that helps). 

I'm on a mac but tested it on Windows 10 and got the same problem. Other projects are fine.

Cheers

**This was the full error message for the import issue:**
[plugin:vite:import-analysis] Failed to resolve import "$app/environment.js" from "src/routes/control-center/+layout.svelte". Does the file exist?
56 |  const { console: console_1 } = globals;
57 |  import "svelte/internal/disclose-version";
58 |  import { dev } from '$app/environment.js';
   |                       ^
59 |  import { onMount, setContext, getContext } from 'svelte';
60 |  import { writable, derived } from 'svelte/store';
    at formatError (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63765:46)
    at TransformContext.error (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63759:19)
    at normalizeUrl (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62034:33)
    at async file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62188:47
    at async Promise.all (index 2)
    at async TransformContext.transform (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62109:13)
    at async Object.transform (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:30)
    at async loadAndTransform (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29)
    at async viteTransformMiddleware (file:///.../node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:59342:32

**Comment by dummdidumm** [comment]
I see, I think it's because of the explicit `.js` ending - you shouldn't need to do that, you can just write `import ... from "$app/environment";`

Why are you adding `.js` file extension endings to the imports? Does that happen automatically because of some vs code setting perhaps?

**Comment by Mark2M** [comment]
I'll have a play tomorrow without the extension and see what happens. To be honest I can't remember if I did it or the auto complete. It was a good year or so I wrote it. The new format has a .js format too by the way. CheersOn 18 Jan 2024, at 21:19, Simon H ***@***.***> wrote:﻿
I see, I think it's because of the explicit .js ending - you shouldn't need to do that, you can just write import ... from "$app/environment";
Why are you adding .js file extension endings to the imports? Does that happen automatically because of some vs code setting perhaps?

**Comment by Mark2M** [comment]
You were right... I dropped the file extension and the problem went away.

Thanks again...
