### ISSUE TITLE
Page load fetch file returns weird characters on first load, but returns correct text via router

### ISSUE THREAD

**Issue by kratos-digital** [sveltejs/kit#11650]
### Describe the bug

Fetching data from json or markdown file (inside load function) in croatian (probably any language with non-english characters) language renders text with weird characters. That happens only on first load (page refresh), but it is correctly displayed when visiting that page via router.

### Reproduction

src/routes/cookie-policy/+page.js 
```
import { error } from '@sveltejs/kit';

/** @type {import('./$types').PageLoad} */
export async function load({ fetch }) {
	try {
		const response = await fetch(`/data/test.json`);

		if (!response.ok) {
			throw error(response.status, response.statusText);
		}

		const content = await response.json();

                 // Output on first load: {cookies: 'KolaÄ\x8DiÄ‡i'}
                 // Output when coming from router: {cookies: 'Kolačići'}
		console.log(content);

		return { content: content };
	} catch (e) {
		console.log(e);
		throw e;
	}
}
```

test.json
```
{
    "cookies": "Kolačići"
}
```

### System Info

```Shell
System:
    OS: macOS 14.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.45 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    pnpm: 8.9.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.1 
    @sveltejs/adapter-static: ^3.0.1 => 3.0.1 
    @sveltejs/kit: ^2.0.0 => 2.0.4 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.10
```

### Severity

annoyance

**Comment by Conduitry** [comment]
What `content-type` is `/data/test.json` being returned with? You're not showing the code that does that. Does it indicate `charset=utf-8`?

**Comment by Conduitry** [comment]
What's important here is the `content-type` header in the _response_ for `/data/test.json`, not in the request.

Your reproduction is incomplete. It just shows the contents of `test.json` but not how that is getting served, and not what `content-type` header it has.

**Comment by kratos-digital** [comment]
It is served inside +page.svelte as simple html output. All code for fetching the data is inside page.js, I am not setting response headers manually anywhere. Output of `console.log(response.headers);` inside +page.js is always empty, both on first load (page refresh) and when navigating using anchor tags, but using anchor tags the text is rendered correctly. Only on first load the text is not rendered correctly.

**Comment by Conduitry** [comment]
`fetch('/data/test.json')` must be calling _something_, and you haven't shown the code that's serving that.

**Comment by kratos-digital** [comment]
I don't understand, it fetches json file located in /static/data/test.json.

It is basic sveltekit project structure.

**Comment by kratos-digital** [comment]
Problem was with html meta charset. This is the rule: "It needs to be inside the <head> element and [within the first 1024 bytes of the HTML](https://html.spec.whatwg.org/multipage/semantics.html#charset), as some browsers only look at those bytes before choosing an encoding."

Someone put those gtag scripts above it.
