### ISSUE TITLE
Sharp's dynamic import is not working

### ISSUE THREAD

**Issue by devcsrj** [sveltejs/kit#11656]
### Describe the bug

When building for production, dynamic imports are not included in the final build. The resulting chunk would have:

```
function commonjsRequire(path) {
	throw new Error('Could not dynamically require "' + path + '". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.');
}
```

I have many attempts to get this to work, such as:

```ts
export default defineConfig({
	plugins: [
		sveltekit()
	],
	build:{
		commonjsOptions: {
			dynamicRequireTargets: [`@img/sharp-darwin-arm64`],
		},
	},
	optimizeDeps: {
		include: [`@img/sharp-darwin-arm64`]
	},
	ssr: {
		external: ['@img/sharp-darwin-arm64']
	},
});
```

...but to no avail.

### Reproduction

Demo: https://github.com/devcsrj/sveltekit-sharp

Run the following:

```
npm install
npm run build
cd build
node .
```

Then, go to:

```
http://localhost:3000/api/demo.png
```

### Logs

```Shell
Error: Could not load the "sharp" module using the darwin-arm64 runtime
undefined: Could not dynamically require "../src/build/Release/sharp-darwin-arm64.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
undefined: Could not dynamically require "../src/build/Release/sharp-wasm32.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
undefined: Could not dynamically require "@img/sharp-darwin-arm64/sharp.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.
undefined: Could not dynamically require "@img/sharp-wasm32/sharp.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

```

### System Info

```Shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 87.97 MB / 16.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.3.0 - ~/.local/share/nvm/v20.3.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v20.3.0/bin/yarn
    npm: 9.6.7 - ~/.local/share/nvm/v20.3.0/bin/npm
    pnpm: 8.10.2 - ~/.local/share/nvm/v20.3.0/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
    Watchman: 2023.11.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2
```

### Severity

serious, but I can work around it

### Additional Information

sharpjs dynamically loads bindings through this snippet:

https://github.com/lovell/sharp/blob/a3b45ceccccf98c333b329a76b833c1af02ea15e/lib/sharp.js#L13-L30

**Comment by benmccann** [comment]
Out of curiosity, what are you trying to do? Executing sharp at request time is likely to be quite expensive and you could be better off using `@sveltejs/enhanced-img` or a CDN.

**Comment by devcsrj** [comment]
> what are you trying to do?

Hi @benmccann ! It's a bunch of steps:

* I have an SVG of a signature
* I have a `.docx` with templated variables rendered with [docx-templates](https://github.com/guigrpa/docx-templates)
* When injecting the signature, I convert it to PNG and render in the doc

**Comment by devcsrj** [comment]
Erm, I fixed it. Apparently moving `sharp` to `dependencies` prevents it from being bundled via Vite.

[Docs](https://kit.svelte.dev/docs/adapter-node#deploying)

> Development dependencies will be bundled into your app using Rollup. To control whether a given package is bundled or externalised, place it in devDependencies or dependencies respectively in your package.json.
