### ISSUE TITLE
Svelte-kit SPA with adapter static and globally disabled prerender and ssr stills executes app code on node.js

### ISSUE THREAD

**Issue by kran6a** [sveltejs/kit#11664]
### Describe the bug

According to this (taken from official docs) load functions defined on +page.ts when ssr = false and prerender = false would only run on the client.

This is not true, in the liked repo I used browser-only code carelessly within the load function and during the build I got
`ReferenceError [Error]: Worker is not defined`, meaning the load function is being executed on the server despite prerendering and ssr being disabled, contrary to what the docs state.

![image](https://github.com/sveltejs/kit/assets/15054534/bc4fde91-72a3-4871-a663-0507295e0afc)

### Reproduction

I made a minimal reproducible example based on the svelte-kit demo app.
The key files are `src/lib/worker.ts`, `src/lib/worker_handler.ts` and `src/routes/+page.ts`
https://github.com/kran6a/spa-bug

### Logs

```Shell
> spa-bug@0.0.1 build
> vite build

vite v5.0.11 building SSR bundle for production...
"confetti" is imported from external module "@neoconfetti/svelte" but never used in "src/routes/sverdle/+page.svelte".
✓ 108 modules transformed.

node:internal/event_target:1096
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: Worker is not defined
    at new WorkerWrapper (file://spa-bug/.svelte-kit/output/server/chunks/worker_handler.js:2:3)
    at file://spa-bug/.svelte-kit/output/server/chunks/worker_handler.js:9:16
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async Promise.all (index 0)
    at async analyse (file://spa-bug/node_modules/@sveltejs/kit/src/core/postbuild/analyse.js:58:16)
    at async MessagePort.<anonymous> (file://spa-bug/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)

Node.js v21.5.0
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 3600XT 6-Core Processor
    Memory: 22.43 GB / 63.93 GB
  Binaries:
    Node: 21.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.0
    @sveltejs/adapter-static: ^3.0.1 => 3.0.1
    @sveltejs/kit: ^2.0.0 => 2.3.5
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1
    svelte: ^4.2.7 => 4.2.9
    vite: ^5.0.3 => 5.0.11
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
The `load` function will only be _called_ on the client, but `+page.ts` still needs to be evaluated during the build to find out what it exports, and that imports code that refers to browser-only APIs at the top-level, and so fails to run on the server.

You will either need to import `worker_handler.js` lazily only while `load` is being called, or you will need to adjust `worker_handler.js` so importing it doesn't eagerly try to use browser APIs.

**Comment by kran6a** [comment]
> The `load` function will only be _called_ on the client, but `+page.ts` still needs to be evaluated during the build to find out what it exports, and that imports code that refers to browser-only APIs at the top-level, and so fails to run on the server.
> 
> You will either need to import `worker_handler.js` lazily only while `load` is being called, or you will need to adjust `worker_handler.js` so importing it doesn't eagerly try to use browser APIs.

But there is no need to import the whole file as is just to check some exports. Exports could be checked in the corresponding AST and code could be treeshaken so that anything not needed to compute those exports' values is never executed on node.

I get that it is way more complex than just importing the whole file but it is a pain for people developing client-side SPAs that do not need to prerender. Plus people won't be expecting their build tool to execute the code. At least I wasn't expecting that behavior with adapter-static despite having experience with svelte and svelte-kit (this was my first SPA that did not need prerendering).

If it is not planned I would at least state in the docs about adapter-static that code in `+page.ts` and `+layout.ts` files will be executed in node even if you are using adapter-static as it is a big point to consider for people developing no prerendering 100% client-side websites (eg: embedded devices, IoT config/monitoring, kiosks, ...).

**Comment by yegorius** [comment]
I have just hit the same problem. Our app is client-side only. It would be nice if adapter-static had an option to avoid running `+page.ts` during build-time.
