### ISSUE TITLE
`on:submit` can't prevent programmatic `form.requestSubmit()` with `use:enhance`

### ISSUE THREAD

**Issue by BMorearty** [sveltejs/kit#11692]
### Describe the bug

# Summary

The `on:submit` handler for a form cannot prevent submission when the form has `use:enhance`. 

# More detail

There are cases where I want to programmatically request submission of a form. E.g. if the user is in a `textarea` and hits Cmd+Enter / Ctrl+Enter.

I also have some client-side validation that prevents form submission under certain conditions. E.g., the `textarea` value is required to be at least 3 characters long.

When I don't have `use:enhance` enabled, I can prevent form submission with an `on:submit` handler that calls `event.preventDefault()`. But when `use:enhance` is on, this handler does not prevent form submission. 

Now I know I can always use the `cancel` function:

```svelte
  <script>
    let question;
    $: canAsk = question?.length > 3;
    function maybePreventSubmit(e) {
      if (!canAsk) {
        e.preventDefault();
      }
    }
  </script>

  <form
    on:submit={maybePreventSubmit}
    use:enhance={({ cancel }) => {
      if (!canAsk) {
        cancel();
      }
    }}>
    <textarea bind:value={question}></textarea>
  </form>
```

But that's duplicating cancellation logic in the progressive enhancement. The `maybePreventSubmit` is for the non-enhanced case and the `cancel()` is for the enhanced case.

I had a non-enhanced form and when I added `use:enhance` the previously-working behavior was broken, which is why I filed this as a bug rather than enhancement request. 😃 Thanks!

### Reproduction

Sveltelab demo: https://www.sveltelab.dev/34pmme5i59e2wim

Repository: https://github.com/BMorearty/cancel_form_submission

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 87.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1
    @sveltejs/kit: ^2.0.0 => 2.4.1
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1
    svelte: ^4.0.5 => 4.2.9
    vite: ^5.0.0 => 5.0.12
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
You need to use `event.stopImmediatePropogation()`

```diff
	function maybePrevent(event) {
		if (!canAsk) {
			event.preventDefault();
-			event.stopPropagation();
+			event.stopImmediatePropagation();
			return false;
		}
	}
```

> The stopImmediatePropagation() method of the [Event](https://developer.mozilla.org/en-US/docs/Web/API/Event) interface prevents other listeners of the same event from being called.
>
> If several listeners are attached to the same element for the same event type, they are called in the order in which they were added. If stopImmediatePropagation() is invoked during one such call, no remaining listeners will be called, either on that element or any other element.

More details at https://developer.mozilla.org/en-US/docs/Web/API/Event/stopImmediatePropagation
