### ISSUE TITLE
svelte-migrate downgrades adapters

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#11693]
### Describe the bug

I just ran `npx svelte-migrate sveltekit-2` in a project to which I had already upgraded `@sveltejs/adapter-vercel` to the latest version (5.1.0). It downgraded me to 4.0.0

**Comment by codenoid** [comment]
Hi @Rich-Harris could you check my solution

It's basically skip upgrade if user's library version are higher than the version that migrates offer

so far this solution are the most make sense to me

https://github.com/codenoid/kit/commit/f33ade0eadc79823da0fec1855c5375f1029f4c0
