### ISSUE TITLE
Errors in hooks.js are silently swallowed

### ISSUE THREAD

**Issue by pago** [sveltejs/kit#1170]
**Describe the bug**
Whenever there is any sort of issue with my `src/hooks.js` file it is silently swallowed and the hooks are no longer executed. But there is no notice of any sort of error.

**Logs**
None.

**To Reproduce**
Demo project: https://github.com/pago/bug-svelte-kit-hooks-silent-error

Without the last commit (https://github.com/pago/bug-svelte-kit-hooks-silent-error/commit/5b978684f824c654ba8ce613473f98b1af0a8241), which adds an import for `fs/promises` to the `src/hooks.js` file, the logging within `src/hooks.js` works. Once the import is added, the logging no longer happens and the hooks are just not executed anymore.
There is no warning and no information about why this happens.

**Expected behavior**
If executing the `hooks` fails for any reason, I would expect to get an error message in the console about it so that I know how to fix it and to be aware that is isn't working at the moment.

**Stacktraces**
None.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 32.47 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.volta/tools/image/node/14.16.1/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.12 - ~/.volta/tools/image/node/14.16.1/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Browsers:
    Edge: 90.0.818.42
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.85 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.2.1 
```

- Your browser
Safari 14.0.3 & Edge 90.0.818.42 (apparently)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
`npm run dev` (I assume Node)
</details>

**Severity**
My actual primary issue is not being able to figure out how to read a file in the hooks since importing `fs` fails for some unknown reason (I have a workaround for now). But I've been bitten by this issue a few times already while working on a very small app and it consumes a lot of time trying to figure out why a piece of the functionality no longer works.
Swallowing the errors in what I imagine being a very prominent feature isn't a deal breaker but it does make me nervous about svelte-kit and what other errors I might need to spent a lot of time to find.

I would _recommend_ to treat this as a _medium severity_ case. It's not a major thing but it will cause frustration with engineers when they play around with Svelte Kit and research its suitability for their projects and thus might influence their decision making in a negative way (in case they can't figure out why their hooks are not broken - i.e. I thought hooks were not working in general for a couple days before realizing it was the import).

**Additional context**
Should I open up another issue about not being able to import `fs` in the hooks file? According to the documentation those run only on the server so I was expecting to be able to use that API there. Alternatively I would like to use the `?raw` modifier on an import but that causes the same silent error since I would expect the server side code to also be bundled by rollup/vite.

**Comment by UltraCakeBakery** [comment]
I experienced the same issue with errors being swallowed in hooks. In my `hooks.js` I imported my custom database library from `$lib`. One of my database models had a missing package causing the entire hook to not do anything. It took me a couple hours to find the issue.

**Comment by Rich-Harris** [comment]
Ah, whoops 😬  This is happening because there's error handling here... https://github.com/sveltejs/kit/blob/9883c179720aeff37c9d6db4b5b37ed9e61e3c7c/packages/kit/src/core/dev/index.js#L139-L141 ...so that you can get away with not having a `hooks.js` file.

Since that (terrible) code was written, we added a `resolve_entry` helper here... https://github.com/sveltejs/kit/blob/9883c179720aeff37c9d6db4b5b37ed9e61e3c7c/packages/kit/src/core/utils.js#L44-L71 ...which would allow us to check if the file exists before attempting to load it, which would make the error 'handling' unnecessary. Should be a quick win if anyone wants to rustle up a PR (the only finicky part would be adding a test since we'd have to add a whole new 'app' to `packages/kit/test/apps` with a failing `hooks.js`; I think we can get away without adding one).
