### ISSUE TITLE
`PageLoad` type doesn't Work anymore

### ISSUE THREAD

**Issue by Soushi888** [sveltejs/kit#11715]
### Describe the bug

In the `documentation/docs/20-core-concepts/20-load.md` page, the `PageLoad` type seems outdated. It should be replaced by `PageServeLoad`.

### Reproduction

In my Svelekit project, the documentation code didn't work well.

``` ts
import type { PageLoad } from './$types' ;

export const load : PageLoad = ({ params }) => {
	return {
		post : {
			title : `The title of ${params.slug} goes here`,
			content : `The content of ${params.slug} goes here`,
		},
	} ;
} ;
```

When I looked in the `./$types` file, it seems that the `PageLoad` type has been replaced by `PageServerLoad`.
So I modified my code accordingly and everything works as expected.

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.3 (Virginia)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.83 GB / 15.45 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.10.0 - /nix/store/yc5bicc5zs5czjp5q5aygz79km84rmd4-nodejs-20.10.0/bin/node
    npm: 10.2.3 - /nix/store/yc5bicc5zs5czjp5q5aygz79km84rmd4-nodejs-20.10.0/bin/npm
    pnpm: 8.10.5 - /nix/store/y3mxy318cr8cl26saysfwqbxbcwb31lb-pnpm-8.10.5/bin/pnpm
  Browsers:
    Chromium: 120.0.6099.216
```

**Comment by Conduitry** [comment]
Is this a `+page.js` file or a `+page.server.js` file? `PageLoad` is for `+page.js` files, and `PageServerLoad` is for `+page.server.js` files, which is mentioned on that page.

**Comment by Soushi888** [comment]
Oh, I'm sorry. Yes, it was a +page.server.ts. I didn't read it right, I apologize. I'll close the ticket immediately.

**Comment by Antonio-Bennett** [comment]
@Soushi888 Sveltekit generated types are also automatically inferred for you. So you shouldn’t need to import from ./types :)
