### ISSUE TITLE
[Types] `DOM.Iterable` not used when service-worker file is present

### ISSUE THREAD

**Issue by f-elix** [sveltejs/kit#11721]
### Describe the bug

A weird typescript bug since v2.2.0 is that `DOM.Iterable` is not considered by TS if I have a `service-worker.ts` file in `src` with `/// <reference no-default-lib="true"/>` in it. As soon as I remove the reference line, no type error occurs anymore.

It only appears since v2.2.0 because the `service-worker` file is no longer excluded from the ts config.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-mj6fkf?description=The%20default%20SvelteKit%20template,%20generated%20with%20create-svelte&file=package.json,src%2Flib%2Fdom-iterable.ts,src%2Fservice-worker.ts&title=SvelteKit%20Default%20Template

There is some code inside `src/lib/test.ts` where type checking fails if `/// <reference no-default-lib="true"/>` is present in `src/service-worker.ts`. Remove the line and the type error goes away.

### System Info

```Shell
System:
    OS: macOS 12.7.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 39.68 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.6.0 - ~/.nvm/versions/node/v20.6.0/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.0/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.nvm/versions/node/v20.6.0/bin/bun
  Browsers:
    Brave Browser: 116.1.57.53
    Chrome: 120.0.6099.234
    Safari: 17.2.1
  npmPackages:
    @sveltejs/adapter-vercel: 5.1.0 => 5.1.0 
    @sveltejs/kit: 2.4.3 => 2.4.3 
    @sveltejs/vite-plugin-svelte: 3.0.1 => 3.0.1 
    svelte: 4.2.9 => 4.2.9
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This happened as part of #10994, IMO this shouldn't have been removed
