### ISSUE TITLE
Polyfill SSR and CSR separately

### ISSUE THREAD

**Issue by shirecoding** [sveltejs/kit#11722]
### Describe the problem

I am trying to polyfill buffer using vite.config.ts

```
import { purgeCss } from "vite-plugin-tailwind-purgecss";
import { sveltekit } from "@sveltejs/kit/vite";
import { defineConfig } from "vite";
import { nodePolyfills } from "vite-plugin-node-polyfills";

export default defineConfig({
    envDir: "../",
    plugins: [sveltekit(), purgeCss(), nodePolyfills()],
    define: {},
    resolve: {
        alias: {
            process: "process/browser",
        },
    },
    build: {
        rollupOptions: {
            external: [
                "vite-plugin-node-polyfills/shims/buffer",
                "vite-plugin-node-polyfills/shims/global",
                "vite-plugin-node-polyfills/shims/process",
            ],
        },
    },
});
```

However in SSR +server.js, it is also polyfilling node's buffer causing and error that it cant find the vite-plugin-node-polyfills/shims/buffer.

### Describe the proposed solution

Can we choose to polyfill on for CSR and exclude SSR?

### Importance

i cannot use SvelteKit without it

**Comment by Conduitry** [comment]
See also #9544, which may give you what you need via a `config` plugin that conditionally overrides your config. I haven't specifically tried it with options beyond `build.target`, however.

**Comment by benmccann** [comment]
Please see the Vite docs for details on how to do this: https://vitejs.dev/config/#conditional-config

**Comment by benmccann** [comment]
Ah, although I see in https://github.com/sveltejs/kit/issues/9544 that perhaps this isn't possible. I'm not sure if that's still the case or not. In any case I'll leave this as closed since it's a duplicate of https://github.com/sveltejs/kit/issues/9544 in that case

**Comment by shirecoding** [comment]
hmm not sure if this helps anyone but after i downgraded  vite-plugin-node-polyfills from 0.19.0 to 0.17.0 it solves the issue, this is my versions

```
"vite": "^5.0.3",
"vite-plugin-node-polyfills": "^0.17.0",
```

i suspect vite-plugin-node-polyfills 0.19.0 has a problem with when being also used in node

**Comment by kirbysayshi** [comment]
@shirecoding I spent hours on this today, and finally found your comment: it worked! Thank you!
