### ISSUE TITLE
svelte-package not generating `d.ts` files sometimes

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/kit#11729]
### Describe the bug

see title

### Reproduction

https://www.sveltelab.dev/1d4jbqqvu0s4fng

### System Info

```Shell
-
```

### Severity

serious, but I can work around it

**Comment by paoloricciuti** [comment]
@dummdidumm I think we can close this

**Comment by dummdidumm** [comment]
Closed via https://github.com/sveltejs/language-tools/pull/2269, will be resolved through a bump of svelte2tsx (release pending)
