### ISSUE TITLE
https://kit.svelte.dev/faq is borked

### ISSUE THREAD

**Issue by Zettexe** [sveltejs/kit#1173]
![Screenshot_4](https://user-images.githubusercontent.com/53223513/115691768-e08bce00-a34d-11eb-9bbd-8f82d41498da.png)

**Comment by Conduitry** [comment]
https://kit.svelte.dev/faq.json

```
Unknown language: "env"
Please report this to https://github.com/markedjs/marked.
```

https://github.com/sveltejs/kit/blob/721f2a54e7fcc82279d1a61aa8da2adb42ce8330/documentation/faq/60-env-vars.md#L9

`env` is an invalid triple backtick code block language value.

**Comment by benmccann** [comment]
fixed
