### ISSUE TITLE
Compiler unable to resolve $type file for universal layout load functions.

### ISSUE THREAD

**Issue by ethan-tqa** [sveltejs/kit#11736]
### Describe the bug

The compiler chokes when the following conditions are met:
- Typescript is enabled for the project.
- Both server-side layout load and universal layout load are used for the same layout.
- $types is explicitly imported on either `+layout.ts` or `+layout.server.ts` or both.

Happens on Windows and macOS.

Disabling SSR does not help.

### Reproduction

[https://github.com/ethan-tqa/sveltekit-layout-issue](https://github.com/ethan-tqa/sveltekit-layout-issue)

### Logs

```
Error when evaluating SSR module /src/routes/+layout.ts: failed to import "./$types"
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 7700X 8-Core Processor
    Memory: 10.05 GB / 31.14 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1
    @sveltejs/kit: ^2.0.0 => 2.4.3
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1
    svelte: ^4.2.7 => 4.2.9
    vite: ^5.0.3 => 5.0.12
```

### Severity

serious, but I can work around it

### Additional Information

The only work around is to remove explicit type definition from both the `+layout.ts` and `+layout.server.ts`. But then Eslint will give warnings for that, and some code editors may not be able to resolve types for example [Zed](https://zed.dev).

**Comment by dummdidumm** [comment]
It needs to be `import type { .. } from './$types';`, not `import { type .. } from './$types'`. The latter means that the resulting JS code will still contain an import to `$types`, but it's a type module only and should be removed completely - writing  `import type` ensures that.
