### ISSUE TITLE
Error swallowed in form action when page has SSR disabled

### ISSUE THREAD

**Issue by winstonewert** [sveltejs/kit#11757]
### Describe the bug

I've found that when an exception is thrown in a page action and ssr = false, then I don't see the exception anywhere. I do get the 500 error response.

### Reproduction

Minimal test case: https://github.com/winstonewert/sveltekit-bug-report

It's just a skeleton sveltekit project with the following +page.server.ts:

```
export const ssr = false;

export const actions = {
	default: async () => {
		throw new Error('Something bad!');
	}
};
```

And a button to trigger the post request

### Logs

```Shell
The absence of logs is the problem.
```

### System Info

```Shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 27.80 GB / 46.94 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.9.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.216
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2 
    svelte: ^4.2.7 => 4.2.9 
    vite: ^5.0.3 => 5.0.12
```

### Severity

annoyance

### Additional Information

1. The error gets returned to the call to `await handle_action_request` in render_page in src/runtime/server/page.js
2. Because ssr is disabled, `render_page` returns `await render_response` 
3. The code that checks and then rethrows the error later in render_page: `throw action_result.error` is never executed.

**Comment by mastermakrela** [comment]
Hi, I was investigating [something similar](https://github.com/mastermakrela/sveltekit-form-actions-inconsistency). I was confused why I can't see the data returned from the Form Actions.

And the solution was to use [`use:enhance`](https://kit.svelte.dev/docs/form-actions#progressive-enhancement-use-enhance) on the form, because without SSR, the returned HTML is always the same, so the data handling has to happen in the browser.

**Comment by eltigerchino** [comment]
Yeah, it doesn't look like the default form submit is suppose to work with SSR disabled (there's no code to return the page.form variable unless SSR is enabled).
