### ISSUE TITLE
"Unused CSS selector" for selectors prefixed with `img` while using @sveltejs/enhanced-img

### ISSUE THREAD

**Issue by fmaclen** [sveltejs/kit#11758]
### Describe the bug

There is a linting warning when adding a CSS selector that includes the `img.foo { ... }` prefix, but it doesn't have such warning when adding a selector that only has the class `.foo { ... }.

Here's a visual example:

![image](https://github.com/sveltejs/kit/assets/1434675/d53760ab-0c40-404a-b98b-2fcd634a2367)

### Reproduction

Here's a repro: https://github.com/fmaclen/enhancement-img-bug-unused-selector/blob/master/src/routes/%2Bpage.svelte

### System Info

```Shell
"devDependencies": {
		"@sveltejs/adapter-auto": "^3.0.0",
		"@sveltejs/enhanced-img": "^0.1.8",
		"@sveltejs/kit": "^2.0.0",
		"@sveltejs/vite-plugin-svelte": "^3.0.0",
		"svelte": "^4.2.7",
		"vite": "^5.0.3"
	}
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Please make the repo public.

I'm not sure whether this is going to be a gotcha we have to just document. I'm also not sure whether this is a compile-time warning (which results in removal of styles) or whether this is just the language tools letting you know. Having a clonable repo would help determine whether whether or not the non-matching styles are actually removed at build time.

**Comment by fmaclen** [comment]
> Please make the repo public.

Done

**Comment by fmaclen** [comment]
@benmccann understood. I was expecting the CSS styling to work like any other HTML element in the component, that being said this limitation is only a minor annoyance.

Feel free to close this issue if there is further work that can be done on this front.

**Comment by gterras** [comment]
> I'm not sure there's much that could be done here. I believe this warning is coming from the Svelte compiler, which isn't aware of the preprocessor. We had recommended avoiding `img.foo` in favor of `.foo` in the docs. See the last sentence here: https://kit.svelte.dev/docs/images#sveltejs-enhanced-img-basic-usage

Unearthing the thread because I'm not sure this deserves an issue but https://svelte.dev/docs/kit/images#sveltejs-enhanced-img-Intrinsic-Dimensions has the failing snippet: 

```css
<style>
.hero-image img {
	width: var(--size);
	height: auto;
}
</style>
```

This could be a good place to illustrate the `.foo .img {}` pattern.
