### ISSUE TITLE
vitePreprocess does not reload postcss.config after full vite restart

### ISSUE THREAD

**Issue by benjaminpreiss** [sveltejs/kit#11755]
### Describe the bug

vite-preprocess does not reevaluate the contents of postcss.config after a full vite server restart.

That means I am logging something in `postcss.config.js`.
When I trigger a full vite server restart via `vite-plugin-restart` this is not logged again, which tells me that the postcss config code is not reloaded.

### Reproduction

https://github.com/frontline-hq/tailwind-dynamic-safelist/tree/main

Then (requires node >= v18.13):

- `npm install -g pnpm`
- `pnpm i`
- `pnpm dev`

Then you will see a log in the console, after the server starts:

`loading postcss config...`

If you now edit any `.svelte` file in the `/routes` folder, you will see that the vite server is restarted in the console (I do this with the vite plugin `vite-plugin-restart`)

But this will not trigger the `loading postcss config...` console log (which you can find in `postcss.config.js`).

### System Info

```Shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 85.88 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    bun: 1.0.15 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 119.1.60.118
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/kit: ^2.0.0 => 2.4.3 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.9 
    vite: ^5.0.3 => 5.0.12
```

### Severity

annoyance

**Comment by ghostdevv** [comment]
The vitePreprocess code is located in the [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte) repo, so you might want to open an issue there
