### ISSUE TITLE
Getting a blank page with "Bad Request" after updating SvelteKit and adapter-node

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#11762]
### Describe the bug

I've updated a whole bunch of dependencies for my SvelteKit project, like SvelteKit itself, Vite, adapter-node, vite-plugin-svelte, etc. Everything is at the last version, and locally it all works just fine (running with `pnpm dev`).

But after I updated my staging server I am now only seeing a blank page with the words "Bad Request", and I don't know why. `pnpm build` seemed to build just fine, the Node server is running, locally everything is fine, so what is causing this Bad Request? Which request?

For reference: adapter-node was updated from 1.3.1 to 4.0.1, SvelteKit from 1.27.1 to 2.5.0, Vite from 4.5.0 to 5.0.12.

To rule out Nginx and its proxy to the node server I ran `curl http://localhost:2999` on my server and that also returns "Bad Request". (The Node server runs on port 2999 via a systemd script, and Nginx then proxies requests to localhost:2999.)

### Reproduction

I don't have a reproduction for this, but I do hope the issue won't simply be closed. I'll gladly supply any information necessary to help debug the issue. It's happening with even the most basic "hello world" `+page.svelte`, without any imports and no hooks in place. No `+layout.*` either. As such there is no reproduction I can supply.

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) x64 AMD EPYC Processor
    Memory: 27.23 GB / 30.62 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.16.1 - ~/.local/share/pnpm/node
    npm: 9.5.1 - ~/.local/share/pnpm/npm
    pnpm: 8.14.2 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @sveltejs/adapter-node: ^4.0.1 => 4.0.1
    @sveltejs/kit: ^2.5.0 => 2.5.0
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.0.2
    svelte: ^4.2.9 => 4.2.9
    vite: ^5.0.12 => 5.0.12
```

### Severity

blocking an upgrade

### Additional Information

At this moment my staging site is completely unusable. Luckily it's only the staging site and not production! 😅

**Comment by kevinrenskers** [comment]
`pnpm preview` and then `curl http://localhost:4173/` does work fine by the way. It's really the Node server that's causing the problem here.

**Comment by kevinrenskers** [comment]
Hmm when I manually run the build with `PORT=2999 node index.js` then `curl http://localhost:2999` works fine, and also the staging site (via Nginx) works fine. But running it via systemd as I always have no longer works? This is the script:

## /etc/systemd/system/www.example.rocks.service

```
[Unit]
Description=node daemon for www.example.rocks

[Service]
User=example
Group=www-data
WorkingDirectory=/home/example/www.example.rocks
Environment="HOST=127.0.0.1"
Environment="PORT=2999"
ExecStart=node deploy/index.js
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```

When the node server runs via this script, then I get the Bad Request.

**Comment by Conduitry** [comment]
This is presumably coming from https://github.com/sveltejs/kit/blob/a3607e5f577d45a6a8be52d5f6d3bda214877a6d/packages/adapter-node/src/handler.js#L104 - If you could manually edit the corresponding code in your built staging site to catch and log the error there, that would be helpful.

```diff
diff --git a/packages/adapter-node/src/handler.js b/packages/adapter-node/src/handler.js
index 5586e5169..f605465dc 100644
--- a/packages/adapter-node/src/handler.js
+++ b/packages/adapter-node/src/handler.js
@@ -99,7 +99,8 @@ const ssr = async (req, res) => {
 			request: req,
 			bodySizeLimit: body_size_limit
 		});
-	} catch {
+	} catch (error) {
+		console.log(error);
 		res.statusCode = 400;
 		res.end('Bad Request');
 		return;
```

**Comment by kevinrenskers** [comment]
Output of `journalctl -xef _COMM=node`:

```
Jan 30 21:31:03 example node[3260708]: Listening on 127.0.0.1:2999
Jan 30 21:31:14 example node[3260708]: ReferenceError: Request is not defined
Jan 30 21:31:14 example node[3260708]:     at getRequest (file:///home/example/www.example.rocks/deploy/handler.js:1044:2)
Jan 30 21:31:14 example node[3260708]:     at Array.ssr (file:///home/example/www.example.rocks/deploy/handler.js:1230:19)
Jan 30 21:31:14 example node[3260708]:     at handle (file:///home/example/www.example.rocks/deploy/handler.js:1301:23)
Jan 30 21:31:14 example node[3260708]:     at file:///home/example/www.example.rocks/deploy/handler.js:1301:40
Jan 30 21:31:14 example node[3260708]:     at Array.<anonymous> (file:///home/example/www.example.rocks/deploy/handler.js:1219:4)
Jan 30 21:31:14 example node[3260708]:     at handle (file:///home/example/www.example.rocks/deploy/handler.js:1301:23)
Jan 30 21:31:14 example node[3260708]:     at file:///home/example/www.example.rocks/deploy/handler.js:1301:40
Jan 30 21:31:14 example node[3260708]:     at Array.<anonymous> (file:///home/example/www.example.rocks/deploy/handler.js:682:28)
Jan 30 21:31:14 example node[3260708]:     at handle (file:///home/example/www.example.rocks/deploy/handler.js:1301:23)
Jan 30 21:31:14 example node[3260708]:     at Array.<anonymous> (file:///home/example/www.example.rocks/deploy/handler.js:1307:10
```

**Comment by Conduitry** [comment]
`Request not defined` sounds like you are using an unsupported version of Node. Is it possible that you have different versions of Node, and the one in the PATH of the user running the application via systemd is older?

**Comment by kevinrenskers** [comment]
Ah! You're absolutely right. The globally installed version is v16.19.1. I thought that the app was using Node 18, which is the default version for the user running the node server. But I guess the node server is run with the same node version as the root user has? Even though it's configured to run via a specific user.

When logged in via root, `node --version` returns v16.19.1.
When logged in as the user owning the code, `node --version` returns v18.16.1.

The app is actually configured to run on 18.17.1 though, via the `use-node-version` variable in `.npmrc`, which is used by pnpm. But yeah the systemd script is not going via pnpm.

For now I changed the systemd script to specifically run `/home/soundradix/.local/share/pnpm/nodejs/18.17.1/bin/node deploy/index.js`, and yeah the site runs.

I need to look into how to automatically use the correct node version as configured in the `.npmrc` file. pnpm picks it up just fine, but I don't know yet how to use the correct version via systemd.

**Comment by Conduitry** [comment]
If you're okay with the Node version living in `package.json` instead, then https://nodejs.org/api/corepack.html might be an option. I don't have a specific suggestion for reading it from `.npmrc` in a way that is suitable for running a production app (i.e., not via pnpm).

**Comment by kevinrenskers** [comment]
For those running into the same problem, I solved it by running the node server via pnpm, by adding an entry to package.json scripts: 

```
  "scripts": {
    "dev": "vite dev --port 3000",
    "build": "vite build",
    "preview": "vite preview",
    "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
    "systemd": "node deploy/index.js"
  },
```

And changed my systemd script to use this command:

```
[Unit]
Description=node daemon for www.example.rocks

[Service]
User=example
Group=www-data
WorkingDirectory=/home/example/www.example.rocks
Environment="HOST=127.0.0.1"
Environment="PORT=2999"
ExecStart=/home/example/.local/share/pnpm/pnpm systemd
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
```
