### ISSUE TITLE
'linked from null'

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1176]
**Describe the bug**
The parenthesized text should be omitted if `parent` is `null`: https://github.com/sveltejs/kit/blob/53521dbb7fa43789cb8c86ca5c4cd220d2d349ed/packages/kit/src/core/adapt/prerender.js#L75-L81

**To Reproduce**
Throw an error in `/` (in `load`), and prerender.

**Expected behavior**
> 500 /

rather than

> 500 / (linked from null)

**Severity**
low

**Comment by borntofrappe** [comment]
If you'll allow me, I'd like to contribute to the issue.

I'm considering a ternary operator for the message as well. Something similar to the following.

```js
log.error(`${status} ${path}${parent ? ` (${verb} from ${parent})` : ''}`);
throw new Error(`${status} ${path}${parent ? ` (${verb} from ${parent})` : ''}`)
```

Hopefully it's not too cumbersome.

**Comment by Rich-Harris** [comment]
yep, that would be perfect! thank you

**Comment by Rich-Harris** [comment]
oops, closed with a fat finger
