### ISSUE TITLE
ReferenceError: Request is not defined at getRequest (file:///../node_modules/@sveltejs/kit/src/exports/node/index.js:107:2) at file:///../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

### ISSUE THREAD

**Issue by squatchydev9000** [sveltejs/kit#11789]
### Describe the bug

ReferenceError: Request is not defined at getRequest (file:///../node_modules/@sveltejs/kit/src/exports/node/index.js:107:2) at file:///../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

After running npm run dev... this error persists in the localhost browser... site will not load.

ReferenceError: Request is not defined at getRequest (file:///../node_modules/@sveltejs/kit/src/exports/node/index.js:107:2) at file:///../node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:497:27

I've lost days...

Just wanted to move from svelte to sveltkit for the routes...

Tried:

Sveltekit cli install - tailwind, typescript, prettier, eslint
SkeltonUi cli install - same as above
Repeated attempts to change node version via NVM
Manually altering the different config files
Endless github, youtube, stackoverflow nonsense...
The Vite troubleshooting docs
The Sveltekit docs
A lot of back and forth with Chat-GPT and PerplexityAI...

Expected Behavior
Was expecting the localhost browser window to be filled with skeletonUi magic....

MacOS 14.2.1 (23C71)
ARC Browser
Node versions tried: 18, 19, 20

Tried removing config files and re-building them... etc.

### Reproduction

Steps To Reproduce
CLI install from SkeltonUI website... choose eslint, prettier, etc.. all of the options.

Npm run dev... annnnnnnd. boom. error.

### System Info

```Shell
MacOS 14.2.1 (23C71)
ARC Browser
Node versions tried: 18, 19, 20
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I cannot be the only one experiencing this right?

**Comment by Conduitry** [comment]
I don't know what to suggest, other than that I really don't think you're using the version of Node that you think you're using.

If you edit the file in question (`node_modules/@sveltejs/kit/src/exports/node/index.js`) and put a `console.log('node version', process.version);` right above the reference to `Request`, what happens?

**Comment by e0** [comment]
Not sure if you have the same problem/setup, but I just fixed the same error for my project.

I added the `console.log` as @Conduitry mentioned. It was outputting version 16 even after I installed a different default version using `volta`. Then I saw that apparently the `bun` I was using was installed using `volta` too. `volta ls bun` showed that `node` 16 is used for `bun`. I just uninstalled `bun` using `volta` and then reinstalled it using `curl`. Restarted the project in a new terminal session and I no longer get the error.

**Comment by Conduitry** [comment]
Closing due to lack of response.

**Comment by DomDumont** [comment]
Got this also, it was related to my nodejs version. i thought i was using a recent one but nvm default was a very old one. by doing a "nvm alias default" to a recent version, my problem disapeared

**Comment by sharukhi** [comment]
I also got the same error, it was related to my node-js version. Upgrading node worked for me.

**Comment by arnaudbesnier** [comment]
Moving from Node 16 to Node 18 also fixed the issue on my end (using `bun`).

**Comment by Avi-ADAM** [comment]
in my case it was because in my package.json i had old node version as dependency
