### ISSUE TITLE
[vite] ✨ optimized dependencies changed. reloading

### ISSUE THREAD

**Issue by mislam** [sveltejs/kit#11793]
### Describe the bug

We often face this issue due to a runtime reload caused by Vite optimization. For example, if there is a multi-page form submission wizard where user goes thru multiple routes to reach the end. This sudden reload causes a reload that jumps back to the very first page. This is very frustrating.

### Reproduction

I think, while running `npm dev` vite does not pre-optimize all components and modules for the future routes. This is causing the runtime optimization, thus the frustrating reload.

### Logs

```Shell
[vite] ✨ new dependencies optimized: svelte-transition
[vite] ✨ optimized dependencies changed. reloading
```

### System Info

```Shell
System:
    OS: macOS 12.7.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 1012.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.15.1 - ~/Library/pnpm/pnpm
    Watchman: 2023.03.06.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.0
    @sveltejs/kit: ^2.0.0 => 2.3.2
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1
    svelte: ^4.2.7 => 4.2.8
    vite: ^5.0.3 => 5.0.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Can you check if adding the `svelte-transition` dependency to the Vite config option `optimizeDeps.exclude` in the `vite.config.ts` file prevent the reload?
https://vitejs.dev/guide/dep-pre-bundling.html#customizing-the-behavior

**Comment by bluwy** [comment]
I think the fix should be adding it to `optimizeDeps.include` instead. The message comes out when during the initial Vite prebundling crawling it wasn't able to detect all dependencies that are used in the client. Without a repro though, it's hard to tell what directory structure makes the crawling not complete.

**Comment by JL102** [comment]
If it'd be possible for the SvelteKit adapter to somehow include all of the client dependencies into `optimizeDeps.include` automatically, I'd really appreciate it.

I'd rather not have to add every single client-side dependency to vite.config.ts by hand....

```ts
export default defineConfig({
	plugins: [sveltekit()],
	optimizeDeps: {
		include: ['@smui-extra/autocomplete', '@smui-extra/bottom-app-bar', '@smui/button', '@smui/card', '@smui/checkbox', '@smui/circular-progress', '@smui/common', '@smui/common/internal', '@smui/data-table', '@smui/dialog', '@smui/drawer', '@smui/fab', '@smui/form-field', '@smui/icon-button', '@smui/layout-grid', '@smui/linear-progress', '@smui/list', '@smui/paper', '@smui/ripple', '@smui/select', '@smui/slider', '@smui/snackbar', '@smui/switch', '@smui/tab', '@smui/tab-bar', '@smui/textfield', '@smui/textfield/helper-text', '@smui/tooltip', '@smui/top-app-bar', '@smui/touch-target', 'workbox-precaching', 'svelte-markdown', 'dexie', 'js-cookie', 'oslo/crypto'],
	},
	define: {
		'process.env.NODE_ENV': '"production"'
	}
});
```

**Comment by eltigerchino** [comment]
> If it'd be possible for the SvelteKit adapter to somehow include all of the client dependencies into `optimizeDeps.include` automatically, I'd really appreciate it.
> 
> I'd rather not have to add every single client-side dependency to vite.config.ts by hand, but at the moment it seems like I need to, because if I don't, every time I navigate to a new page with slightly different dependencies, it force reloads with "optimized dependencies changed. reloading"....
> 
> ```ts
> export default defineConfig({
> 	plugins: [sveltekit()],
> 	optimizeDeps: {
> 		include: ['@smui-extra/autocomplete', '@smui-extra/bottom-app-bar', '@smui/button', '@smui/card', '@smui/checkbox', '@smui/circular-progress', '@smui/common', '@smui/common/internal', '@smui/data-table', '@smui/dialog', '@smui/drawer', '@smui/fab', '@smui/form-field', '@smui/icon-button', '@smui/layout-grid', '@smui/linear-progress', '@smui/list', '@smui/paper', '@smui/ripple', '@smui/select', '@smui/slider', '@smui/snackbar', '@smui/switch', '@smui/tab', '@smui/tab-bar', '@smui/textfield', '@smui/textfield/helper-text', '@smui/tooltip', '@smui/top-app-bar', '@smui/touch-target', 'workbox-precaching', 'svelte-markdown', 'dexie', 'js-cookie', 'oslo/crypto', 'oslo/encoding', 'ua-parser-js', 'qrcode'],
> 	},
> 	define: {
> 		'process.env.NODE_ENV': '"production"'
> 	}
> });
> ```

Can you share a minimal reproduction so we can figure out what’s causing Vite to not find these dependencies during crawling?

**Comment by ARajgor** [comment]
I have the same issue. when I run `bun run dev` first time it take forever to load UI. I have to wait for like a minute to optimized and after that it shows the UI.

My config:
```
Windows 11
```
package.json
```
  "devDependencies": {
    "@sveltejs/adapter-auto": "^3.0.0",
    "@sveltejs/kit": "^2.0.0",
    "@sveltejs/vite-plugin-svelte": "^3.0.2",
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.32",
    "postcss-load-config": "^5.0.2",
    "svelte": "^4.2.7",
    "tailwindcss": "^3.3.6",
    "vite": "^5.0.3",
    "vite-plugin-wasm": "^3.3.0"
  },
  "type": "module",
  "dependencies": {
    "bits-ui": "^0.21.2",
    "lucide-svelte": "^0.365.0",
    "mode-watcher": "^0.3.0",
    "paneforge": "^0.0.3",
    "svelte-sonner": "^0.3.21",
    "tailwind-merge": "^2.2.2",
    "tailwind-variants": "^0.2.1",
    "clsx": "^2.1.0",
    "socket.io-client": "^4.7.5",
    "tiktoken": "^1.0.13",
    "xterm": "^5.3.0",
    "xterm-addon-fit": "^0.8.0"
  }
  ```

![Screenshot 2024-04-13 105648](https://github.com/sveltejs/kit/assets/76404080/af95353e-beaa-4ecd-babc-75df21b5cc8f)
![Screenshot 2024-04-13 111033](https://github.com/sveltejs/kit/assets/76404080/aa2aab34-0de7-47b5-b1f6-9c3a9ab2e707)
![Screenshot 2024-04-13 111224](https://github.com/sveltejs/kit/assets/76404080/fea8edb5-19c3-450d-be74-e7873a0497d5)

**Comment by Freeplayg** [comment]
If it helps here's a video of what happens for me:
[Screencast from 2024-04-23 23-35-132.webm](https://github.com/sveltejs/kit/assets/40742947/4a80d682-6a47-494c-b016-bcf2b6ebc669)

It is easier to notice when you have something like phosphor-svelte with different icons on each page.

**Comment by eltigerchino** [comment]
We really need a minimal repository that we can download that reproduces the issue. Reiterating on what Bjorn has said:

> I think the fix should be adding it to `optimizeDeps.include` instead. The message comes out when during the initial Vite prebundling crawling it wasn't able to detect all dependencies that are used in the client. Without a repro though, it's hard to tell what directory structure makes the crawling not complete.

**Comment by Martin-Carlsson** [comment]
Hey hey @eltigerchino 

I created a minimal repository that you can download and reproduce the issue ✨

https://github.com/Martin-Carlsson/minimal-repository-for-optimized-dependencies-changed-reloading

<img width="885" alt="image" src="https://github.com/sveltejs/kit/assets/7769335/842afa30-6b98-4d2a-a286-5ecac70c665b">

I included the `.devcontainer` folder so you can get the exact same dev setup as me. 
I'm on an M1.

**Comment by dominikg** [comment]
as mentioned earlier https://github.com/sveltejs/kit/issues/11793#issuecomment-1965850225
This can happen with dependencies that are not automatically detected at first and then optimized upon being processed.
To prevent this, you can add them to `optimizeDeps.include` by name. Note that for 3rd party svelte libraries optimizeDeps.include is recommended to so they don't get recompiled so often. Only if optimizing them causes a problem you should look into adding them to optimizeDeps.exclude.

This is not an issue with sveltekit, its the way vite works. If you believe there is a problem with how dependency optimization is handled with svelte libraries, please file an issue at vite-plugin-sveltes repo. 

The new issue must include a **minimal** reproduction and clearly describe the erroneous behavior out of line with what is described in the vite documentation already provided here.  (minimal reproductions do not include .devcontainer, tailwind, multiple unrelated dependencies, tons of routes and components etc, it means taking the barebones starter `pnpm create vite@latest --template svelte` or for sveltekit `pnpm create svelte@latest`  (all default options) and then adding the minimal amount of code/deps to it to reproduce the issue, including a step by step description of what to do to trigger it.

**Comment by dominikg** [comment]
after a chat with @eltigerchino  and @bluwy  :pray:  it looks like there is an issue in sveltekit. It sets `rollupOptions.build.input` in a way that prevents vite's scanner from finding the entry files it needs to do it's job.

as a workaround you can add `optimizeDeps.entries:['src/routes/**/+*.{js,ts,svelte}','src/hooks*.{ts,js}]`` to your vite.config.js  (in a future version, sveltekit will do this automatically.  (in case you are using custom options for your routesDir or hooks paths, adapt accordingly)

**Comment by shiftlabs1** [comment]
Fix still pending ?

**Comment by DDuran19** [comment]
![Image](https://github.com/user-attachments/assets/35638206-08fb-4166-b429-5bfcdf582c9f)

Just following up on this, cause the issue still exists.. at least on my end. it appeared when vite have updated to version 6

**Comment by eltigerchino** [comment]
> ![Image](https://github.com/user-attachments/assets/35638206-08fb-4166-b429-5bfcdf582c9f)
> 
> Just following up on this, cause the issue still exists.. at least on my end. it appeared when vite have updated to version 6

Please open a new issue with a minimal reproduction. Otherwise, it's difficult to troubleshoot.
