### ISSUE TITLE
Support other templating systems

### ISSUE THREAD

**Issue by chientrm** [sveltejs/kit#11815]
### Describe the problem

So we have `+page*.ts` and `+page.svelte`.

Why wouldn't we have like `+page.vue` for Vuejs, `+page.tsx` for ReactJS,...

And future languages or templating systems to come.

### Describe the proposed solution

I think SvelteKit has already been designed in a way that Svelte can be replaced by anything else.

### Alternatives considered

It would be nice to not spending a lot of time developing a new kit everytime a new programming language show up.

### Importance

nice to have

### Additional Information

I know Svelte itself is a framework with its own runtime but maybe we can somehow make that runtime exposed to other templating systems 🤔

**Comment by Conduitry** [comment]
Uh, what? No.
