### ISSUE TITLE
$page.form not updating if formaction triggered from another route

### ISSUE THREAD

**Issue by BlueFoxPrime** [sveltejs/kit#11812]
### Describe the bug

Hi!

according to the following part of the docs I assumed that $page.form is updated at all times a formaction is triggered (no matter from where):
"... the action can respond with data that will **be available through the form property on the corresponding page and through $page.form app-wide until the next update.**"

However, $page.form only updates, if the formaction belongs to the current route. Which could be explained by another part of the docs:
"use:enhance will ...update the form property, **$page.form and $page.status on a successful or invalid response, but only if the action is on the same page you're submitting from.** For example, if your form looks like <form action="/somewhere/else" ..>, form and $page will not be updated. This is because in the native form submission case you would be redirected to the page the action is on. If you want to have them updated either way, use applyAction"

I would expect the behaviour of the first statement. If thats not how it should or can be, the docs should be more clear (either its "available ... app-wide" or not).

### Reproduction

https://www.sveltelab.dev/0fshtniglq50776?files=.%2Fsrc%2Froutes%2Ftest%2F%2Bpage.server.js

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2 
    svelte: ^4.0.5 => 4.2.9 
    vite: ^5.0.0 => 5.0.12
```

### Severity

annoyance

### Additional Information

ActionResult callback can be used for each form action, but its feels unnecessary

**Comment by hyunbinseo** [comment]
The [Anatomy of an action] is placed before the [Progressive enhancement] section.

[Anatomy of an action]: https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action
[Progressive enhancement]: https://kit.svelte.dev/docs/form-actions#progressive-enhancement

This means that the `use:enhance` should not be used, and the form submit should be handled by the browser.

```diff
# /src/routes/+page.svelte
- <form method="POST" action="/test?/testAction" use:enhance>
+ <form method="POST" action="/test?/testAction" use:enhance>
```

In this case, the `form` is updated.

**Comment by dummdidumm** [comment]
As pointed out, that section refers to actions that are not progressively enhanced yet. I don't see a good way how we can make this clearer while keeping the docs somewhat succinct and not confuse readers who read this top to bottom, therefore closing.
