### ISSUE TITLE
Docs out of date for adapter-node `BODY_SIZE_LIMIT`

### ISSUE THREAD

**Issue by oscarhermoso** [sveltejs/kit#11817]
### Describe the problem

Since adapter-node v3, `BODY_SIZE_LIMIT=Infinity` is required (instead of `BODY_SIZE_LIMIT=0`) - but this is not mentioned in the docs

Breaking change was made here https://github.com/sveltejs/kit/pull/11589

### Describe the proposed solution

Docs updated to reflect that env var `BODY_SIZE_LIMIT=Infinity` is required to remove the limit

https://kit.svelte.dev/docs/adapter-node#environment-variables-bodysizelimit

### Alternatives considered

N/A

### Importance

nice to have

### Additional Information

Bonus points: Consider mentioning that this env var does not apply when running in DEV mode  https://github.com/sveltejs/kit/issues/10448

**Comment by manstie** [comment]
There's a PR for this already https://github.com/sveltejs/kit/pull/11804
