### ISSUE TITLE
Access to URL hash and/or full raw URL from endpoints and load()

### ISSUE THREAD

**Issue by Leftium** [sveltejs/kit#1182]
**Is your feature request related to a problem? Please describe.**
There is no way to access the URL hash (portion of URL after # character). Many 3rd parties pass useful information in the hash. Specifically: Google and Facebook during OAuth redirection. The OAuth redirect URL's are of the form:

    # Google OAuth redirect URL
    https://example.com/path/#state=value...&prompt=none

    # Facebook OAuth redirect URL
    https://example.com/path/?#access_token=TOKEN&...expires_in=5286

**Describe the solution you'd like**

- Additional properties `hash` and/or `rawUrl` to [SvelteKit endpoint API](https://kit.svelte.dev/docs#routing-endpoints)
- Additional properties `hash` and/or `rawUrl` to [`load({ page })`](https://kit.svelte.dev/docs#loading-input-page)

(Since the browser has access to the full URL, it is possible to work around the limitations of `load()`. Still cumbersome and not available server-side.)

**Describe alternatives you've considered**
- Using the client-side `load()` work-around. However, I need to set an http-only cookie which is much easier from an endpoint. Also redirects don't seem to work as well from client-side `load()`.
- Implementing OAuth redirect handling without SvelteKit.
- This hack that was suggested using static pages and messages:
    - https://github.com/JBusillo/cuencador-kit/blob/master/static/fbcallback.html
    - https://github.com/JBusillo/cuencador-kit/blob/master/src/routes/login.svelte
- What I'll probably do is create a Svelte page that can capture the information from the hash, then call an end endpoint that can set the `set-cookie` header. Redirects from client-side `load()` don't seem to work, but `goto` seems to work.

**How important is this feature to you?**
It will not keep me from using SvelteKit, but SvelteKit should be able handle URL hashes and OAuth redirects more elegantly.

**Additional context**
Simple repo to demonstrate and experiment with SvelteKit URL hash limitations:
https://github.com/Leftium/sk-cant-access-url-hashes

**Comment by Leftium** [comment]
I guess URI fragments are not sent to the server by design... perhaps OAuth redirect URLs intentionally use a hash to prevent information like tokens from getting past the client to the server.

I assumed SvelteKit was just not including data it already had. It would be wonderful if SvelteKit could offer access to the URI fragment on the server, too!

**Comment by Conduitry** [comment]
It's impossible to access the URL fragment on the server. And we don't want `load` to behave differently on the server and in the browser, so we can't provide it in there. If you know you're on the browser (either via `onMount` or `import { browser } from '$app/env'`) then you can just use the regular browser API `location.hash`.

**Comment by hdoro** [comment]
I understand the context, and thank you for getting back to this! 😄

However, I'm struggling to find a way to **access hashes for no-js users**. As I need client-side JS to access them, I don't see how I could ever work with access tokens without Javascript.

Super happy to learn from anybody who's managed to pull this off somehow :)

**Comment by Conduitry** [comment]
This isn't a SvelteKit limitation, it's a platform limitation. If you're trying to use the `#` portion of a URL in a no-JS context, you're going to have a bad time, because the browser doesn't send that to the server.
