### ISSUE TITLE
Avoid inline @const in Sverdle example, move to a separate component

### ISSUE THREAD

**Issue by snubydev** [sveltejs/kit#11820]
### Describe the problem

Some youtubers criticize Svelte approach to use inline @const in a component template section. For example, templates/default/src/routes/sverdle/+page.svelte
The point is to avoid of mixing javasript and html in component template section more than necessary, because it makes component code less readable. They say it looks "hybrid strange" mixing not type-safe javascript into html template directly.
 

### Describe the proposed solution

A solution might be to move dynamic part of template to a separate ```Cell.svelte``` component, using typed props (```export let```) for external context and ```$:``` dynamic variables instead of inline ```{@const ...}```

### Importance

nice to have

### Additional Information

I did try suggested improvement and could open PR if that makes sense.

**Comment by Conduitry** [comment]
I think creating another component just to avoid needing a `{@const}` isn't a good tradeoff. You always need to take things YouTubers say with a large grain of salt, but I've definitely heard more complaints about 'why do I have to make this a separate component for no good reason - I'm only ever going to be using it in exactly one other component' than I've heard complaints about `{@const}`.
