### ISSUE TITLE
Reactive block is executed first on the page and then on the layout

### ISSUE THREAD

**Issue by Thiagolino8** [sveltejs/kit#11849]
### Describe the bug

When distributing data using context from the layout and updating this data using a reactive block, the page is initialized with the outdated data, as the reactive block of the layout that updates the data is executed after the reactive block of the page that retrieves the data

### Reproduction

It is possible to see in the [repl](https://www.sveltelab.dev/ozma4b500uob0v9) that the tanstack query cache is only hydrated in the reactive block of the layout after the query has been started in the reactive block of the page

### System Info

```Shell
System:
    OS: Linux 5.15 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 10.50 GB / 12.67 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    Yarn: 4.0.2 - ~/.asdf/installs/nodejs/20.10.0/bin/yarn
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.11.0 - ~/.asdf/installs/nodejs/20.10.0/bin/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/kit: ^2.0.0 => 2.5.0 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2 
    svelte: ^4.2.7 => 4.2.9 
    vite: ^5.0.3 => 5.0.12
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
I don't think apps should depend on the particular order that reactive blocks are run in on different components. If that is causing problems in a particular app or with a particular library, there probably needs to be some adjustment there to how it's handling caching or to how the data is transported around the app.
