### ISSUE TITLE
Better error messages for incorrect form actions

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#11876]
### Discussed in https://github.com/sveltejs/kit/discussions/11865

<div type='discussions-op-text'>

<sup>Originally posted by **thebjorn** February 18, 2024</sup>
I just got this error:

    SvelteKitError: POST method not allowed. No actions exist for this page

I was trying to post from `/my/special/page` to `/logout?next=/goodbye`, so it's not exactly clear what "_this_ page" means in this context, especially if you're not experienced (e.g. does it mean a `+..page..` file, a path/url, or a route..?).

What can be improved:

1. give me all the information the error handler has - or can gather (it's already an error so there shouldn't be any concerns about using cycles to gather input).
2. give me an error number (`SvelteKitError[E042]: ...`) that I can look up to find more information (or even make the error number a link to the docs?)</div>

**Comment by mig-hub** [comment]
Not sure it helps at all but I experienced issues like this when using a `307` redirect. Then worked with a `302`.
