### ISSUE TITLE
Pages are rendered during build despite not setting `prerender = true`

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#1188]
I ran into a similar issue to https://github.com/sveltejs/kit/issues/763 earlier today. While digging into (and with some help of @benmccann) I fixed it by adding `prerender: { enabled: false }` to the svelte.config.js.

This because in https://github.com/sveltejs/kit/blob/92d33913e284e00fb20d882253ba5439eeafc407/packages/kit/src/core/load_config/options.js#L93 it seems the prerendering is by default turned _on_.

Instead of necro'ing the previous issue (which as it described there **is** solved, so no point in reopening it) I made this issue in case there can be some discussion about whether this is the correct default. I am not entirely clear on what the benefit of prerendering is over not doing it, so I suppose that would be part of this decision.

Regardless of this, the default values for the config should be (better) documented somewhere, especially in this case where the documentation on prerendering makes it look as if this is something you have to _explicitely turn on_.

**Comment by benmccann** [comment]
I think the thing that seems wrong to me here is that you said you did not have `prerender = true` on any page and `getSession` was still being called. This is similar to https://github.com/sveltejs/kit/issues/933#issuecomment-816820251, but you case is more extreme because that one was just about startup code being called whereas in your case `getSession` was being called, which doesn't make sense to me

Can you provide a repo that reproduces `getSession` being called during `build`?

**Comment by stephane-vanraes** [comment]
I will make a reproduction repo later today, but to be clear this is during the `adapter` (adapter-node) phase of the build.

**Comment by stephane-vanraes** [comment]
reproduction repositorty https://github.com/stephane-vanraes/sveltekit-prerender-issue

**Comment by benmccann** [comment]
Here's the stack trace from the reproduction:
```
Error: This shouldn't throw in prerender.
    at Object.getSession (.svelte/output/server/app.js:63:9)
    at render_page (node_modules/@sveltejs/kit/dist/ssr.js:1151:39)
    at render (node_modules/@sveltejs/kit/dist/ssr.js:1478:16)
    at Object.handle (.svelte/output/server/app.js:122:60)
    at respond (node_modules/@sveltejs/kit/dist/ssr.js:1453:30)
    at async visit (node_modules/@sveltejs/kit/dist/chunks/index5.js:113:20)
    at async prerender (node_modules/@sveltejs/kit/dist/chunks/index5.js:227:5)
    at async Object.prerender (node_modules/@sveltejs/kit/dist/chunks/index5.js:294:5)
    at async adapt (/home/bmccann/src/tmp/sveltekit-prerender-issue/node_modules/@sveltejs/adapter-node/index.cjs:26:4)
    at async adapt (node_modules/@sveltejs/kit/dist/chunks/index5.js:320:2)
```

**Comment by benmccann** [comment]
Prerendering crawls your site, which is why pages are being rendered. If you set `kit.prerender.enabled: false` that should stop it
