### ISSUE TITLE
Global styles directory and `$styles` alias

### ISSUE THREAD

**Issue by ixxie** [sveltejs/kit#11887]
### Describe the problem

There is currently no clear and standard to organized global styles in SvelteKit. While there are definitely _good_ options, I would argue that global styles are common enough to warrant a _standard_ solution.

### Describe the proposed solution

I propose a `src/styles` folder as a standard location for global styles, along with a `$styles` alias to facilitate exports. 

![image](https://github.com/sveltejs/kit/assets/20320695/ef7891cb-d5db-4804-95eb-1b72fa98dc7c)

### Alternatives considered

The obvious alternative is to do this in `$lib` instead; users can create `$lib/styles` and move on with their lives. However, this does not offer standardization this proposal hopes to address. Global styles get lost in a sea of functional code: `.js`, `.ts` and `.svelte` files which - to me at least - feel like a very different category of code.

### Importance

nice to have

**Comment by Conduitry** [comment]
You can also define your own aliases - https://kit.svelte.dev/docs/configuration#alias - I don't think we want to single out styles as having a blessed place to live.

There's also definitely an argument for putting code next to each other that's going to work as part of the same thing - and not separating it out by file extension. I don't think we want to wade into that fray with additional blessed places to put certain types of files.

**Comment by ixxie** [comment]
Fair enough, I was on the fence myself. Probably shouldn't have opened this. 

Thanks for the link @Conduitry, I was looking at Vite for aliasing and didn't realize that Kit had it too!
