### ISSUE TITLE
hooks.server.ts is running when you hover the <a href="">...<a/> tags

### ISSUE THREAD

**Issue by FCNealVillangca** [sveltejs/kit#11898]
### Describe the bug

according to what I read hooks run every time the SvelteKit server receives a request but it was login in the console whenever I hover a link even if not clicking it.

check this video:
https://drive.google.com/file/d/15nhajKfwJzFu38lAz9dcgrDFM_dcWAqE/view?usp=sharing

### Reproduction

clone and run git repo

```
git clone https://github.com/FCNealVillangca/svelte_testing.git
```

### System Info

```Shell
System:
    OS: windows 10 home 64bit 
    CPU: Intel(R) Pentium(R) CPU G4400 @ 3.30GHz   3.31 GHz
  Binaries:
    Node: 20.10.0
    Yarn: 1.22.21
    npm: 10.2.3
  npmPackages:
   "@sveltejs/adapter-auto": "^3.0.0",
   "@sveltejs/kit": "^2.0.0",
   "@sveltejs/vite-plugin-svelte": "^3.0.0",
   "svelte": "^4.2.7",
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
The load function runs on hover because of the preload data attribute that is set in the app.html. You can remove it or change it to a different setting https://kit.svelte.dev/docs/link-options#data-sveltekit-preload-data

**Comment by FCNealVillangca** [comment]
my bad thanks @eltigerchino
