### ISSUE TITLE
Error management with monorepo and sveltekit 2

### ISSUE THREAD

**Issue by piolet** [sveltejs/kit#11901]
### Describe the bug

I'm developing an application using sveltekit.
Up until now, I've been using version 1.30 and everything has worked without a hitch (except for the hiccups integrated by my own code ;) ).

Recently, I wanted to upgrade to version 2 of sveltekit, and then I noticed a problem with error handling (in +error.svelte, I didn't get the right status).

To try and give a framework, I've tried to reproduce my problem on this lab: https://www.sveltelab.dev/kvdbsalqt43c5v5

In this lab, I have a service (SlugService in $lib) that simulates a fetch and throws an error if it's not the right slug. Everything's fine here.

In my case, in my package.json, I use another repo from my monorepo a bit like this:

```
{
	"name": "front",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev --port 5178",
		"build": "vite build",
		"preview": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir --write ./src '!**/*.{json,html}'"
	},
	"prettier": "tools/prettier.config.js",
	"devDependencies": {
		"@sveltejs/adapter-auto": "^3.1.1",
		"@sveltejs/adapter-vercel": "^4.0.5",
		"@sveltejs/kit": "^2.5.1",
		"@sveltejs/vite-plugin-svelte": "^3.0.2",
		"svelte": "^4.2.12",
		...
		"tools": "workspace:*",
		"tslib": "^2.6.2",
		"typescript": "^5.3.3",
		"vite": "^5.1.4",
		"vitest": "^1.3.1",
		"zod": "^3.22.4"
	},
	"dependencies": {
		...
		"services": "workspace:*",
		...
	},
	"type": "module"
}
```
And, of course, in my services repo, the svelte and sveltekit dependencies are with the same versions.

If I move my service to this monorepo (without any modification other than importing it into /[...slug]/+page.server.ts), I see an server-side log: apps/front dev HttpError { status: 404, body: { message: 'Place not found' } } and the error displayed in +error.svelte is 500.

And this same code works perfectly with version 1.30. Do you have any ideas on how to fix this problem?

### Reproduction

Move my SlugService into a monorepo.
I created a repo : https://github.com/piolet/error-repo, everything is explained in the readme to reproduce

Expected behavior
catch a 404 error in +error.svelte in both cases

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 220.00 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    pnpm: 8.15.4 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 91.1.26.77
    Chrome: 122.0.6261.69
    Edge: 122.0.2365.52
    Safari: 16.5.2
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
closed as in favour of https://github.com/sveltejs/kit/issues/11749
