### ISSUE TITLE
adapter-static: infinite loop in the browser on inexistent page fallback

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1190]
**Describe the bug**
Now that https://github.com/sveltejs/kit/issues/754 is closed I found a problem: infinite loop in the browser.

**To Reproduce**
1. If you `npm run build` a simple app with two pages: `/` and `/players`

1. and `npx serve --single build`

1. it amazingly works good.

1. What doesn't work is if you open the browser pointing to `/inexistent` page.

1. Now the browser is in an infinite loop.

**Stacktraces**
![image](https://user-images.githubusercontent.com/41120635/115900197-f8537700-a45f-11eb-8bc0-81f215617b75.png)

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.87 => 1.0.0-next.87
    svelte: 3.37.0 => 3.37.0
    vite: 2.1.5 => 2.1.5

- Your browser: Chrome `90.0.4430.85 (64)

- Your adapter: static `1.0.0-next.5`
</details>

**Comment by frederikhors** [comment]
This is the code I get from `start-27062805.js`:

```js
async function st({paths: t, target: e, session: r, host: s, route: o, spa: a, hydrate: n}) {
    const i = o && new Z({
        base: t.base,
        routes: X
    })
      , l = new rt({
        Root: M,
        fallback: F,
        target: e,
        session: r,
        host: s
    });
    n && await l.start(n),
    o && i.init(l),
    a && i.goto(location.href, {
        replaceState: !0
    }, []),
    dispatchEvent(new CustomEvent("sveltekit:start"))
}
```

**Comment by mattiash** [comment]
The following patch redirects to '/' if the initial page does not exist for an SPA:

```diff
diff --git a/packages/adapter-static/test/test.js b/packages/adapter-static/test/test.js
index f313760..1456bac 100644
--- a/packages/adapter-static/test/test.js
+++ b/packages/adapter-static/test/test.js
@@ -30,4 +30,9 @@ run('spa', (test) => {
                await page.goto(base);
                assert.equal(await page.textContent('h1'), 'This page was not prerendered');
        });
+
+       test('renders index page when JS runs for missing page', async ({ base, page }) => {
+               await page.goto(`${base}/nosuchpage`);
+               assert.equal(await page.textContent('h1'), 'This page was not prerendered');
+       });
 });
diff --git a/packages/kit/src/runtime/client/router.js b/packages/kit/src/runtime/client/router.js
index 4539d33..ce06476 100644
--- a/packages/kit/src/runtime/client/router.js
+++ b/packages/kit/src/runtime/client/router.js
@@ -197,6 +197,12 @@ export class Router {
                                history[replaceState ? 'replaceState' : 'pushState']({}, '', href);
                                return this._navigate(info, noscroll ? scroll_state() : null, chain, url.hash);
                        }
+                       else {
+                               location.href = '/'
+                               return new Promise(() => {
+                                       /* never resolves */
+                               });
+                       }
                }

                location.href = href;
```

Ideally, we should render `$error.svelte` instead, but I haven't figured out how to do that.
