### ISSUE TITLE
I cannot CRUD cookies in sveltekit from another port

### ISSUE THREAD

**Issue by Tech-Gunner** [sveltejs/kit#11914]
### Describe the bug

I cannot CRUD cookies in sveltekit from another port

### Reproduction

1. Clone my repo: `git clone https://github.com/TechGunnerINC/TechGunner.git`
2. Run: `docker compose up`
3. Go to http://localhost:5173/sign-up
4. Fill in the form and click on the Sign up button
5. Open the inspect menu, Go to Application > Cookies > http://localhost:5173
6. And you won't see the auth cookie their

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 1.39 GB / 7.91 GB
  Binaries:
    Node: 21.6.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.19041.3636
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Please provide a minimal reproduction, with no extraneous parts that aren't needed to reproduce the issue, not a link to your actual project.

**Comment by Tech-Gunner** [comment]
@Conduitry I had this issue before I migrated to Bun and Elysia JS, My [backend](https://github.com/TechGunnerINC/TechGunner/tree/aff4dc52676376e22e6a4aa92d2864410738103d/Backend) was in Node and Express js before, and still had this issue

**Comment by Tech-Gunner** [comment]
@Conduitry I'm waiting for your response, reply ASAP!!

**Comment by Conduitry** [comment]
The response is that this isn't a minimal reproduction.

**Comment by Tech-Gunner** [comment]
@antony @arxpoetica @babichjacob @baseballyama @benmccann @bluwy @Conduitry @dominikg @dummdidumm @EmilTholin @FractalHQ @geoffrich @ghostdevv @GrygrFlzr @huntabyte @ignatiusmb @jasonlyu123 @kaisermann @lukeed @mindrones @mrkishi @ota-meshi @PaulBGD @pngwn @Rich-Harris @StrawHatHacker @SarcevicAntonio @spences10 @Swatinem @tanhauhau

**Pls fix this bug**

Here are quick start commands
```shel
git clone https://github.com/TechGunnerINC/TechGunner.git
cd TechGunner
docker compose -d up
code .
```
in one line:
```shel
git clone https://github.com/TechGunnerINC/TechGunner.git && cd TechGunner && docker compose -d up && code .
```

**You need to fix this bug it's breaking my app**

**Comment by StrawHatHacker** [comment]
You didn't just do that...

**Comment by Tech-Gunner** [comment]
Do what?

**Comment by Antonio-Bennett** [comment]
@Tech-Gunner  tagging a bunch of people that are not related at all to your issue. Also Quick Look at the sign up svelte file. You’re preventing the forms default submit and using your own where you don’t do any form of post request at all so I’m not sure exactly how you expected anything to work?

**Comment by Tech-Gunner** [comment]
@Antonio-Bennett nobody was helping me that's why i tagged that many people

**Comment by Antonio-Bennett** [comment]
@Tech-Gunner Have you tried asking for help in the discord? The issues tab is for identifying specific issues with svelte it therefore needs minimum reproductions. If at this moment you just don't know why something isn't working then the best thing to do is ask for help in the discord help channel

**Comment by Tech-Gunner** [comment]
@Antonio-Bennett  Discord is for asking for help and GitHub is for reporting bugs 
I'm not asking for help I'm reporting a bug

**Comment by Antonio-Bennett** [comment]
@Tech-Gunner then make a minimum reproduction as everyone has been saying. You can't post a whole repository and expect people to go through that setting up env variables, dbs and the like. Find the specific problem and make a very specific reproduction.

**Comment by Tech-Gunner** [comment]
@Antonio-Bennett so, should I provide an example DB link and also the env vars?
I'll delete the DB after 5 hours just don't do anything heavy.

**Comment by ghostdevv** [comment]
Feel free to ask your question in the Discord and if it's a bug someone there can advise you whether to make an issue.

**Comment by pngwn** [comment]
They are blocked from the org now so hopefully they won't come to discord after all.
