### ISSUE TITLE
url scheme should be made available on page object

### ISSUE THREAD

**Issue by kamholz** [sveltejs/kit#1193]
In my application, I automatically detect expired JWT access tokens and redirect to `/refresh_token?redirect=...`, where the redirect parameter is the page the user just tried to access. I wrote this function to generate the redirect URL:

```javascript
export function pageUrl(page) {
  let url = `http://${page.host}${page.path}`;
  if (page.query.values().next().done) { // no query params
    return url;
  } else {
    return url + '?' + page.query.toString();
  }
}
```

Unfortunately the URL scheme has to be hardcoded here, because it isn't available on `page`. It would be nice to include it -- is there some reason that wouldn't be practical?

**Comment by Conduitry** [comment]
We don't have access to this on the server, because even if the site is, say, running with the Node adapter and is being served over HTTPS, that's handled by a proxy living in front of the SvelteKit app, which is always serving HTTP.
