### ISSUE TITLE
forms with target="_blank" doesnt open new window

### ISSUE THREAD

**Issue by sacrosanctic** [sveltejs/kit#11931]
### Describe the bug

```html
<form target="_blank" action="/about">
  <button type="submit">navigate with a form</button>
</form>
```

## Expected
open `/about` in a new tab

## Actual
open `/about` in the same tab

### Reproduction

[repro](https://github.com/sacrosanctic/form_target_blank)

[live demo](https://form-target-blank.vercel.app/)

### System Info

```Shell
.
```

### Severity

annoyance

**Comment by ciscoheat** [comment]
Just want to add that it doesn't work with `use:enhance` added to the form as well. Tested with `_top` in an iframe, didn't work either.

**Comment by sacrosanctic** [comment]
> Just want to add that it doesn't work with `use:enhance` added to the form as well. Tested with `_top` in an iframe, didn't work either.

Use:enhance with POST method?

**Comment by ciscoheat** [comment]
Yes, it doesn't work without method="POST".
