### ISSUE TITLE
`data-sveltekit-replacestate` does not replace history entry

### ISSUE THREAD

**Issue by navtoj** [sveltejs/kit#11942]
### Describe the bug

After clicking on an anchor tag with the [data-sveltekit-replacestate](https://kit.svelte.dev/docs/link-options#data-sveltekit-replacestate) attribute and navigating to the second page, I can still navigate to the first page with the `back` button in the browser's navigation bar.

#### Expected Behavior

0. Start at `/login` page.
1. Click the `Go to /login/redirect` anchor element.
2. Press the `Back` button in the browser.
3. The browser should `NOT` be able to go back to the `/login` page.

#### Actual Behavior

3. The browser is able to go back to the `/login` page.

### Reproduction

https://github.com/navtoj/debug/tree/data-sveltekit-replacestate

```bash
# clone the project branch
git clone --single-branch --branch data-sveltekit-replacestate https://github.com/navtoj/debug.git data-sveltekit-replacestate

# change directory to the project
cd data-sveltekit-replacestate

# install the dependencies
npm install

# start the server (and open the app in a new browser tab)
npm run dev
# OR
npm run dev -- --open
```

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 220.62 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
    bun: 1.0.29 - /usr/local/bin/bun
  Browsers:
    Safari: 17.3.1
```

### Severity

serious, but I can work around it

### Additional Information

Direct Download: [https://github.com/navtoj/debug/archive/refs/heads/data-sveltekit-replacestate.zip](https://github.com/navtoj/debug/archive/refs/heads/data-sveltekit-replacestate.zip)

**Comment by eltigerchino** [comment]
I'm not sure there's anything SvelteKit can do here. Since the page doesn't exist, the router correctly defers it to a native navigation, resulting in the redirected page, but without it replacing the history entry. The router can only replace the history entry if the native navigation doesn't occur.
