### ISSUE TITLE
bind:files not updating on submit

### ISSUE THREAD

**Issue by valivia** [sveltejs/kit#11943]
### Describe the bug

using  `<input type="file" bind:files/>` and `use:enhance` does not update the state on form submission

### Reproduction

[recreation of the bug in sveltelab](https://www.sveltelab.dev/18ruvxdjlamgbr5?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte%2C.%2Fsrc%2Flib%2Findex.js%2C.%2Fsrc%2Froutes%2F%2Blayout.svelte%2C.%2Fsrc%2Froutes%2F%2Bpage.server.js)

when looking in the console there is no update when you press submit

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
    Memory: 20.58 GB / 23.38 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.1 - /usr/bin/node
    npm: 10.2.4 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^3.1.1 => 3.1.1 
    @sveltejs/adapter-node: ^2.1.2 => 2.1.2 
    @sveltejs/kit: ^2.5.2 => 2.5.2 
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.0.2 
    svelte: ^4.2.12 => 4.2.12 
    vite: ^5.1.5 => 5.1.5
```

### Severity

annoyance

**Comment by brunnerh** [comment]
The same is true for _any_ input.
`enhance` does a form `reset`, which does not trigger any change events that would update bindings.

**Comment by dummdidumm** [comment]
https://github.com/sveltejs/svelte/pull/10617 would tackle this
