### ISSUE TITLE
Typescript switch missing in docs' mobile menu

### ISSUE THREAD

**Issue by bennymi** [sveltejs/kit#11953]
### Describe the problem

Currently there's only the dark/light theme switch in the mobile menu on the docs page. It would be nice to also have the typescript switch in there.

### Describe the proposed solution

Add the switch below the theme switch in the mobile menu.

### Importance

nice to have

**Comment by eltigerchino** [comment]
The JS / TS switch is now inline with the code blocks. https://svelte.dev/docs/kit/load
