### ISSUE TITLE
Naming of Class with Condition

### ISSUE THREAD

**Issue by msf-caesar** [sveltejs/kit#11958]
### Describe the problem

The naming of class with condition is very verbose, the class name should be passed directly.

### Describe the proposed solution

![image](https://github.com/sveltejs/kit/assets/113716133/70c0fd17-f970-4729-b1b0-23c3963b7e0e)

### Importance

would make my life easier

**Comment by Conduitry** [comment]
`class:foo` is already a shorthand for `class:foo={foo}` - https://svelte.dev/examples/class-shorthand - we don't want to change it to mean something else.

Another thing that would work here for you is just having `class={kind}` to use the string as-is as a class name.
