### ISSUE TITLE
Cannot use browser Network throttling

### ISSUE THREAD

**Issue by eriknyk** [sveltejs/kit#11963]
Cannot use browser Network throttling
===

React developer moving to svelte recently, I've noticed that trying to use Chrome Network throtting is not possible because the sveltekit project in development when realoding the page is trying to fetch entirely all .svelte file components (hundreds) what takes a looooooot of time when trying to trottlin to a Slow 3G netwok, this feature I've used a lot in `nextjs` what surprises me that is not able to use it in sveltekit.

<img width="1452" alt="Screenshot 2024-03-09 at 14 14 54" src="https://github.com/sveltejs/kit/assets/205721/b9710720-e95d-46a3-a295-2af29e4a50d6">

Also even that many files are read from disk (cache) the reloading took 4.15 seconds

<img width="681" alt="image" src="https://github.com/sveltejs/kit/assets/205721/fee6b097-55ff-41d7-bfa6-c728b3715767">

And it is avery small project, recently started that has about 4 pages in routes folder, but using `shadcn-svelte` lib

Regards.

### Reproduction

Open Chrome Develeoper Tools -> Network tab -> Click in selectbox aside [Disable Cache] and select: Slow 3G, hit Cmd + R or Ctrl + R.

### System Info

```Shell
"@sveltejs/kit": "^2.5.0",
"typescript": "^5.2.2",
"vite": "^5.0.12",
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This seems like a won't-fix to me for apps in development mode. That shouldn't be what we are optimizing for. It's not a good test either since you aren't downloading minified versions of the various files anyway. If you want to get a sense of how your app behaves in these situations, run a production build.
