### ISSUE TITLE
Universal Load function fires twice with tRPC client using `event.fetch`

### ISSUE THREAD

**Issue by jgb-solutions** [sveltejs/kit#11962]
### Describe the bug

I'm using universal load function (+page.ts) instead of pager server load (+page.server.ts) because the app's data comes from an external tRPC API anyway and it's faster too for subsequent requests since the app is hosted on Vercel, API is on fly.io, and so the requests on the client directly to the API through tRPC should be and are faster. But I realized that though the docs say there shouldn't be a double fetch call when using `event.fetch`, I still get it. It'd be nice not to have it, even if it's not really a big deal in that case, but still annoying.

### Reproduction

I can't provide a repo for this issue but I'll provide some sample code that should be enough:

// tRPC client 
```ts
import { browser } from '$app/environment'
import { httpBatchLink, createTRPCProxyClient } from '@trpc/client'
import { PUBLIC_API_URL, PUBLIC_PRIVATE_API_URL } from '$env/static/public'

import type { TRPCRouter } from '../../../../elysia/src/trpc/router'


const API_URL = browser ? PUBLIC_API_URL : PUBLIC_PRIVATE_API_URL

// this function can be used to pass the fetch client on each request if needed.
export const getTrpcClient = (fetch?: typeof window.fetch) => createTRPCProxyClient<TRPCRouter>({
	links: [
		httpBatchLink({
			url: `${API_URL}/trpc`,
			fetch
		})
	]
})

export const trpcClient = getTrpcClient()
```

// src/routes/tracks/[trackId]/+page.ts
```ts
import { error } from '@sveltejs/kit'

import { getTrpcClient } from '$lib/trpc/client'

import type { PageLoad } from './$types'

export const load: PageLoad = async ({ params: { trackId }, fetch }) => {
  const track = await getTrpcClient(fetch).mp3pam.fetchTrackDetail.query({ trackId })

  if (!track) {
    error(404, {
      message: "Track not found!"
    })
  }

  return {
    track,
    // of course i am using streaming for less critical data
    relatedTracks: getTrpcClient(fetch).mp3pam.fetchRelatedTracks.query({ trackId }),
    relatedArtists: getTrpcClient(fetch).mp3pam.fetchRelatedArtists.query(),
  }
}
```

### System Info

```Shell
MacOS:  14.2.1 (23C71)
Bun:  1.0.30
Svelte: ^5.0.0-next.1 // using latest update
SvelteKit: ^2.0.0
```

### Severity

annoyance

### Additional Information

App is live at https://mp3pam.top.
This issue is encouraged by @Rich-Harris in this X thread: https://twitter.com/jgb_solutions/status/1766131161674199137

**Comment by amit13k** [comment]
The fetch uses different URLs on the server and the browser. The result of the fetch, when it runs on the server, is serialized in the server-rendered HTML along with the URL. On the browser, because the URL is different, SvelteKit cannot find the results in the serialized data and calls the fetch again.

**Comment by jgb-solutions** [comment]
hi @amit13k, thanks for replying! I'm almost sure it did the same thing when the URL was the same for both. But Il will try it with a single URL and report back later. Thanks!

**Comment by jgb-solutions** [comment]
@amit13k I just test using a single URL and it doesn't do double fetches anymore. But It still does it for the streams. I get since I'm using `page.ts` the streaming promises are resolved client side and instead of on the server. Is that right? If so I'll close this issue now.

**Comment by eltigerchino** [comment]
> @amit13k I just test using a single URL and it doesn't do double fetches anymore. But It still does it for the streams. I get since I'm using `page.ts` the streaming promises are resolved client side and instead of on the server. Is that right? If so I'll close this issue now.

Streaming only happens if you’re using a server load function in +page.server.ts. 
https://kit.svelte.dev/docs/load#streaming-with-promises

The last two fetches run twice because they are not awaited, so they run on both server and client.

**Comment by jgb-solutions** [comment]
get it, thanks @eltigerchino
