### ISSUE TITLE
Playwright types in fresh project are all "any"

### ISSUE THREAD

**Issue by ryanovas** [sveltejs/kit#11989]
### Describe the bug

I am new to sveltekit and booted up a fresh project for the first time. I got a few basic things working and went to try writing a couple tests and noticed my vscode intellisense wasn't showing me any autocompletions. Upon a little investigation, I noticed that for some reason everything is being typed as "any" even if I import the type directly. This doesn't seem right as in the playwright docs they show everything as typed?

### Reproduction

I started a new sveltekit project and went to adjust the default test just like this:

```
import { expect, test, Page } from '@playwright/test';

test('about page has expected h1', async ({ page: Page }) => {
	await page.goto('/');
	await expect(page).toBeVisible();
});
```

When I went to see what was in the autocomplete for `page` inside the `expect` there was nothing. I tried importing `Page` and typing it explicitly, but `Page` itself shows as any if I hover over it.

I tried updating to the latest playwright/test package and the same issue persists. Is there a dependency missing that contains the type definitions?

### System Info

```Shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (4) x64 Intel(R) N100
    Memory: 10.31 GB / 15.39 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 122.0.6261.94
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1 
    @sveltejs/adapter-node: ^4.0.1 => 4.0.1 
    @sveltejs/kit: ^2.0.0 => 2.5.1 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2 
    svelte: ^4.2.7 => 4.2.12 
    vite: ^5.0.3 => 5.1.4
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
You probably forgot to run install, no way to tell if there's any other problem since I can't reproduce it. And `{page: Page}` is the syntax for destructuring, not for writing the type for `Page`.
