### ISSUE TITLE
Is an isomorphic handle() hook a good idea?

### ISSUE THREAD

**Issue by hgl** [sveltejs/kit#1199]
**Is your feature request related to a problem? Please describe.**
Sometimes I'd like to take the db down and turn the site into maintenance mode where it shouldn't make any call to the db. In that mode, visiting any page that can hit the db should be preemptively redirected to a static page.

Currently, the `handle()` hook only takes us half way there, being only able to redirect full page load.

Another use case I can think of is where the site offers oauth login. Once the user logs in via a social network, she might be required to enter more info before she is considered a proper user. While she is in that "pending" state, visiting any user relate page should redirect her to that finish-info page.

We can of course redirect explicitly in every relevant page's `load()`, but that is probably very cumbersome. In both cases I mentioned, you probably want to redirect all but a very few pages.

**Describe the solution you'd like**
Provide an isomorphic `handle()` hook where it's at least possible to redirect both the server and the client requests.

**Describe alternatives you've considered**
Other than explicitly redirect in `load()` as I mentioned, I can't think of any. Maybe In the db case, we can put a load balancer before svelte kit, and redirect all requests to a static page? I'm not sure if client requests can be redirected this way, and it won't work for the oauth case.

**How important is this feature to you?**
Medium.

**Additional context**
None.

**Comment by Rich-Harris** [comment]
Your root `$layout.svelte` component's `load` function can contain that redirect logic, e.g. based on `session`

**Comment by hgl** [comment]
Good idea. It totally works for my case, but I wonder if it can fail if there is a layout reset?

**Comment by hgl** [comment]
My test case confirmed it fails to work if there is a layout reset.

Also it just occurs to me that the doc actually never mentioned that a layout can have a `load` function. It's wording

> A component that defines a page can export ...

And the fact that pages and layouts are explained in different sections seem to imply otherwise.

I'll send a PR soon to improve the doc.

**Comment by hgl** [comment]
Just realized that `__layout.svelte`'s `load` function doesn't work for endpoints. So to workaround you probably need to specify the redirection in both `hooks`'s `handle` and `__layout.svelte`'s `load`.

**Comment by Rich-Harris** [comment]
With the addition of [named layouts](https://kit.svelte.dev/docs/layouts#named-layouts) the layout reset problem no longer exists, since a blank layout and the default layout can both inherit a shared layout:

```bash
__layout@root.svelte          # default layout, extends __layout-root
__layout-blank@root.svelte    # blank ('reset') layout, also extends __layout-root
__layout-root.svelte          # implements the `load` logic
```

For endpoints, you can use `handle`. In combination, it's possible to solve this problem using existing primitives, so I'm going to close this issue.
