### ISSUE TITLE
Improve documentation: How do I setup a database?

### ISSUE THREAD

**Issue by danielniccoli** [sveltejs/kit#12018]
### Describe the problem

I'm trying to setup a database. I've come across https://kit.svelte.dev/docs/faq#how-do-i-use-x-with-sveltekit-how-do-i-setup-a-database which talks about things I don't understand. Specifically

> You can execute any one-time setup code in hooks.js and import your database helpers into any endpoint that needs them.

### Describe the proposed solution

Could you elaborate on that and provide some sample code for `hooks.js`? I'm also confused why hooks.js and not `hooks.server.js`, if you could elaborate on that, too.

### Importance

i cannot use SvelteKit without it

**Comment by CaptainCodeman** [comment]
Probably a mistake - things like that would typically be done `hooks.server.ts/.js`, not `hooks.ts/.js`
