### ISSUE TITLE
Option 'bundler' can only be used when 'module' is set to 'es2015' or later.

### ISSUE THREAD

**Issue by danielniccoli** [sveltejs/kit#12012]
### Describe the bug

VS Code is complaining about `moduleResolution`=`bundler` in `jsconfig.json`
![grafik](https://github.com/sveltejs/kit/assets/2971735/cfa8450a-c3ca-4241-b979-1a7e84c97ead)

### Reproduction

```sh
bun create svelte@latest
bun install
```

... with JSDoc, Prettier and ESLint configured.

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600K
    Memory: 11.22 GB / 31.75 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    bun: 1.0.26 - ~\AppData\Local\Programs\bun\bun.EXE
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1
    @sveltejs/kit: ^2.0.0 => 2.5.4
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: ^4.2.7 => 4.2.12
    vite: ^5.0.3 => 5.2.2
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
![CleanShot 2024-03-22 at 2  01 34@2x](https://github.com/sveltejs/kit/assets/54401897/3eea4423-a3b4-47e5-86c4-12cf73214605)
I can't reproduce this given the instructions. Can you provide a minimal reproduction as a repository?

**Comment by danielniccoli** [comment]
Seems like an issue with VS Code, as it disappeared suddenly.

**Comment by oluijks** [comment]
I get the same notification in Zed (0.161.2)

**Comment by levantocode** [comment]
I'm getting the same error in VSCode, if I run 'tsc' it shows the error as well:

![Image](https://github.com/user-attachments/assets/89358caf-e9a6-4339-a426-2d2f516cedf7)

**Comment by eltigerchino** [comment]
Please open a new issue with a minimal reproduction.

**Comment by Seblor** [comment]
For others stumbling onto this issue just after creating a project, it's because `tsconfig.json` cannot find the `./.svelte-kit/tsconfig.json` file.
Just run the `dev` script once so Svelte can create the necessary files.
Alternatively you can run `bun x svelte-kit sync` (or the equivalent with your preferred package manager) to create the files without running the dev server.
