### ISSUE TITLE
CSS is not loading for components if routes have name that begins similar

### ISSUE THREAD

**Issue by asv1** [sveltejs/kit#1202]
**Describe the bug**
CSS is not loading for component which referred in route if routes have similar names:
1. routes/**first**.svelte
2. routes/**first**_2.svelte

**Logs**

**To Reproduce**
[https://github.com/asv1/svelte_bug_css_not_load](https://github.com/asv1/svelte_bug_css_not_load)

Also video below.

**Expected behavior**
CSS is loaded properly.

**Stacktraces**

**Information about your SvelteKit Installation:**
```
 System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 11.29 GB / 15.93 GB
  Binaries:
    Node: 14.16.0 - d:\portable\node\node.EXE
    npm: 6.14.11 - d:\portable\node\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.1852
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.88
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.2.1
```

**Severity**
Bug is annoying. Hard to find it.

**Additional context**

https://user-images.githubusercontent.com/13184913/115953070-1669b780-a4f2-11eb-9011-4a21c5ba5b25.mp4

**Comment by yuanchuan** [comment]
Downgrade `vite` to version `2.1.5` should fix this issue

**Comment by asv1** [comment]
Looks like fixed now.
