### ISSUE TITLE
server.ts  can not stop rendering 

### ISSUE THREAD

**Issue by craigcosmo** [sveltejs/kit#12046]
### Describe the bug

server.ts  can not stop rendering, I put a redirect inside the +page.server.ts, but the redirect won't happen. and the +page went a head with the rendering, since there is no data from server, the rendering will cause the 500 internal error.

### Reproduction

+page.server.ts
```js
export const load: PageServerLoad = async (event: any) => {
    const token = event.locals.token
    try {
         const res = await getData(
            api.getProductByIdentifier + '/' + event.params.id,
            '',
            false,
         )
         if (res.data) {
            return res
         } else {
            redirect(302, '/contact')
         }
    } catch (error) {
        return { data: [] }
    }
}
```

+page.ts

```js
<script lang="ts">
    export let data: any
    let product = replaceNewline(data.detail)
</script>
<div class="bg-white">
    {product.detail}
</div>
```

### System Info

```Shell
mac os 13
```

### Severity

annoyance

**Comment by rmunn** [comment]
https://kit.svelte.dev/docs/load#redirects mentions that the `redirect()` function works by throwing an exception, and says "Don't use `redirect()` inside a `try {...}` block, as the redirect will immediately trigger the catch statement."

You should move the `if (res.data) { return res } else { redirect(...) }` block outside the `try {}` and then your redirect will work.

Closing issue as this is not a Svelte-Kit bug.
