### ISSUE TITLE
Error: Missing "./internal" specifier in "svelte" package

### ISSUE THREAD

**Issue by coolemur** [sveltejs/kit#12056]
### Describe the bug

Getting error when creating project:

error when starting dev server:
Error: Missing "./internal" specifier in "svelte" package

### Reproduction

```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```

And choosing Svelte 5:

◇  Which Svelte app template?
│  SvelteKit demo app
│
◇  Add type checking with TypeScript?
│  Yes, using TypeScript syntax
│
◆  Select additional options (use arrow keys/space bar)
│  ◼ Add ESLint for code linting
│  ◼ Add Prettier for code formatting
│  ◼ Add Playwright for browser testing
│  ◼ Add Vitest for unit testing
│  ◼ Try the Svelte 5 preview (unstable!)

Initially returns error.

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 778.14 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
    bun: 1.0.11 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.4
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0
    @sveltejs/kit: ^2.0.0 => 2.5.5
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: ^5.0.0-next.1 => 5.0.0-next.88
    vite: ^5.0.3 => 5.2.7
```

### Severity

serious, but I can work around it

**Comment by shanecmdexter** [comment]
Whats your workaround, not using svelte 5?

**Comment by ryangclark** [comment]
@shanecmdexter I just ran into this issue, too, and was able to install `next.87` instead of `next.88`, which is currently tagged with `next` in npm, and then able to run the dev server. You can install `next.87` with this command: `npm i -D svelte@5.0.0-next.87`, or update the specific version as desired.

**Comment by Rich-Harris** [comment]
fixed in the latest release
