### ISSUE TITLE
SSR dynamic imports not rendering

### ISSUE THREAD

**Issue by randyridge** [sveltejs/kit#1205]
Doing a dynamic import doesn't appear to be rendered as part of SSR.  I expect it to be rendered as part of the server response.

I've created a [minimal repro repo](https://github.com/randyridge/kit-ssr-dynamic-import-repro) with a brief overview in the readme.

Tested on latest SvelteKit v1.0.0-next.88.

Potentially related #1164 

# code

`src/routes/index.svelte`:

```svelte
<script context="module">
	import WidgetSelector from '$lib/WidgetSelector.svelte';
	import type { LoadOutput } from '@sveltejs/kit/types/page';
	export const load = (): LoadOutput => {
		return {
			props: {
				widgets: ['WidgetA', 'WidgetB', 'WidgetC']
			}
		};
	};
</script>

<script>
	export let widgets: string[];
</script>

<h1>Widgets</h1>
{#each widgets as widget, index}
	<div>{index}: <WidgetSelector {widget} /></div>
{/each}
```

`src/lib/WidgetSelector.svelte`:

```svelte
<script lang="ts">
	export let widget: string;
	const loadWidget = async (widget: string) => {
		switch (widget) {
			case 'WidgetA':
				return await import('$lib/WidgetA.svelte');
			case 'WidgetB':
				return await import('$lib/WidgetB.svelte');
			case 'WidgetC':
				return await import('$lib/WidgetC.svelte');
		}
	};
</script>

{#await loadWidget(widget) then c}
	<svelte:component this={c.default} />
{:catch error}
	error: {error}
{/await}
```

# server side result:

```html
<div>0:</div>
<div>1:</div>
<div>2:</div>
```

**Comment by Rich-Harris** [comment]
SSR is synchronous in Svelte. This may change one day but in the meantime the solution here is to `import()` the component in `load`

**Comment by Conduitry** [comment]
Closing, as there's a bit that needs to happen here, and most of it would be in Svelte itself, and there are already issues for it.
