### ISSUE TITLE
Static assets are not served if base path is set

### ISSUE THREAD

**Issue by eltigerchino** [sveltejs/kit#12060]
Currently, the cloudflare adapters do not serve the [static assets](https://kit.svelte.dev/docs/project-structure#project-files-static) correctly if a `base` path config is set. This is because the adapters look for the filename such that it is the base path + the filename but the SSR manifest only stores the filename without the base path prefix.

Example SSR manifest:
```js
export const manifest = (() => {
function __memo(fn) {
	let value;
	return () => value ??= (value = fn());
}

return {
	appDir: "_app",
	// app path correctly includes the base path
	appPath: "base/_app",
	// the static assets don't have the base path prefix
	assets: new Set(["favicon.png"]),
```

Currently the filename is the request URL pathname (which includes the base path). It will never match with the manifest assets if a base is configured. (e.g., `base/favicon.png` will never map to `favicon.png`)

https://github.com/sveltejs/kit/blob/335104713e89536cc3f9a1675d0cae622b9c86db/packages/adapter-cloudflare/src/worker.js#L31-L35

> This doesn't appear to be fixed. For example, if I set my base to /blog, and then upload to Cloudflare Pages, everything works except anything in the static folder. Everything in static folder is completely inaccessible. The structure of the contents in Cloudflare Pages appears to be correct, the files are there, they are under the subfolder blog, but when I attempt to navigate to them I get a 404.  In addition, if I attempt to navigate to them using root, it goes into an infinite refresh loop.
> 
> _Originally posted by @elucidsoft in https://github.com/sveltejs/kit/issues/11245#issuecomment-1966532275_

**Comment by Rishab49** [comment]
Making following changes to the `generate_manifest/index.js` file appears to solve the problem. I've tested these changes locally
```js
// passing base_path as argument to generate_manifest in exports/vite and core/adapt

// adding base_path as parameter here
// line 22
export function generate_manifest({ build_data, relative_path, routes, base_path }) {

...

// adding it to the assets path
// line 56
const assets = build_data.manifest_data.assets.map((asset) => base_path.slice(1,base_path.length)+"/"+asset.file);

```
