### ISSUE TITLE
Property 'data' does not exist on result type

### ISSUE THREAD

**Issue by jaycoolslm** [sveltejs/kit#12079]
### Describe the bug

I am using a progressively enhanced form.

The result object contains a data property (Even on errors as well) but there is a typescript error when I try to access it

### Reproduction

<form
	method="POST"
	action="/"
	class="card w-4/5 max-w-lg p-4 text-token space-y-4"
	use:focusTrap={isFocused}
	use:enhance={() => {
		loading = true;
		return async ({ result }) => {
			loading = false;
			const { type } = result;
			console.log(result);
			type === 'success'
				? toastStore.trigger({
						message: 'Your CV has been sent to your email.',
						background: 'variant-filled-success'
				  })
				: toastStore.trigger({
						message: result.data,
						background: 'variant-filled-error'
				  });
		};
	}}
>

### Logs

```shell
Property 'data' does not exist on type '{ type: "redirect"; status: number; location: string; } | { type: "error"; status?: number | undefined; error: any; } | { type: "failure"; status: number; data?: Record<string, unknown> | undefined; }'.
  Property 'data' does not exist on type '{ type: "redirect"; status: number; location: string; }'.ts(2339)
```

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a repository.
