### ISSUE TITLE
Hidden directories are ignored in `static/`

### ISSUE THREAD

**Issue by notramo** [sveltejs/kit#12070]
### Describe the bug

The build process does not copy over hidden directories from `static/`. This prevents adding a `.well-known/` directory in a simple way.

### Reproduction

Add a `static/.well-known/` directory with some files in it.

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i5
    Memory: 1.25 GB / 7.46 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    bun: 1.0.36 - /usr/local/bin/bun
  npmPackages:
    @sveltejs/adapter-static: ^3.0.1 => 3.0.1
    @sveltejs/enhanced-img: ^0.2.0 => 0.2.0
    @sveltejs/kit: ^2.5.0 => 2.5.5
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.0.2
    svelte: next => 5.0.0-next.90
    vite: ^5.0.12 => 5.2.7
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
I’ve had the opposite happen for me. Can you please provide a minimal reproduction?

**Comment by notramo** [comment]
Could this be an `@sveltejs/adapter-static` bug? Do the different adapters handle static assets differently?

**Comment by notramo** [comment]
I found the cause of the error. It was unrelated to SvelteKit. Sorry for the inconvenience.

**Comment by francesco-gaglione** [comment]
@notramo what was the issue? I have the same issue

**Comment by notramo** [comment]
@francesco-gaglione, unfortunately, I don't remember. Probably something Git-related.
