### ISSUE TITLE
Skeletal App too Skeletal

### ISSUE THREAD

**Issue by Crisfole** [sveltejs/kit#1208]
**Is your feature request related to a problem? Please describe.**

I don't get hot reloading on my `static/app.css`  when added from the skeletal app.

**Describe the solution you'd like**

The skeletal app should provide access to all usual features with actually skeletal contents. I don't mind deleting a _little_ but I don't feel like figuring out why I don't have hot reloading for global.css... Alternatively there should be clearer docs on how to manage the hot reloading of app.css (For example).

**Describe alternatives you've considered**

 * Starting from the fuller template and stripping back.
 * Looking for documentation on why hot reloading wasn't working. (Probably in Vite?)

**How important is this feature to you?**

_Personally_ I am sure I can work this out, I think this is more of an accessibility issue for new users. Insofar as I want everyone using Svelte and Svelte Kit it's very, very important to me. Insofar as my personal needs: not very.

**Comment by babichjacob** [comment]
> I don't get hot reloading on my `static/app.css` when added from the skeletal app.

You would if you `import`ed it in JS (aka in `script` block) instead of `link`ing it in HTML. (And at that point, put it in `src` instead of `static`). That's what the demo app does, so you should replicate it.

**Comment by babichjacob** [comment]
> _Personally_ I am sure I can work this out, I think this is more of an accessibility issue for new users.

Hopefully new users will look at the demo app to learn how SvelteKit works and what conventions in it are (like the `app.css` file) before switching to the skeleton template (that's intended for creating projects without having to delete a bunch of demo files).

What more can we do to make that clearer?

**Comment by Crisfole** [comment]
Oops. Confession time: I already re init-ed and must have just instinctively grabbed the skeleton a second time and then dove into a lockdown haze (local stay-at-home order here) without noticing that I screwed up. Some sapper transfer and I think it finished me off.
