### ISSUE TITLE
Zero-effort type safety not working in runes mode

### ISSUE THREAD

**Issue by kansson** [sveltejs/kit#12106]
### Describe the bug

Zero-effort type safety is not working with the next svelte preview.

### Reproduction

Clone https://github.com/hanssonduck/svelte-props and install dependencies and run dev server. Open the index page and see runes props are not typed but exported data is.

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M1
    Memory: 2.75 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.6 - /opt/homebrew/bin/pnpm
    bun: 1.1.3 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 123.1.64.116
    Safari: 17.4.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0
    @sveltejs/kit: ^2.0.0 => 2.5.5
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0
    svelte: ^5.0.0-next.1 => 5.0.0-next.100
    vite: ^5.0.3 => 5.2.8
```

### Severity

annoyance

**Comment by hyunbinseo** [comment]
Page data should be accessed like this:

```diff
- const { message } = $props();
+ let { data } = $props();
```

<img width="717" alt="image" src="https://github.com/user-attachments/assets/a7a7d750-b49e-404c-9523-40e1f30854f4">

It seemed to have worked from November, 2023. Try updating the VS Code extension if not.

- https://github.com/sveltejs/kit/issues/11139#issuecomment-1831816409

@benmccann I believe this issue can be closed?
