### ISSUE TITLE
+page.svelte switching erratically

### ISSUE THREAD

**Issue by unovil** [sveltejs/kit#12116]
### Describe the bug

I have three routes, `facility/add`, `equipment/add`, and `login`. The pages were working fine during development, until suddenly I click on `facility/add` and the +page.svelte switched to that of `login`, without the URL route actually switching to `login`. I don't know why this happened.

I stopped the npm site then ran it again. The problem was now suddenly gone, but now when I went to the `equipment/add` link and it did the same problem as before, only this time the +page.svelte switched to that of `facility/add`. I get confused, so I stopped the npm site then ran it again, but the problem persisted. I force cleared the npm cache, closed VS Code, reinstalled all packages and none solved the problem. I restarted my laptop and finally the problem was gone.

A few hours later, the first problem (`login` +page.svelte getting into `facility/add`) reappeared, and I don't know what to do. I really found no problem with the code, I didn't modify it prior to the problem nor did I modify it when the problem stopped. 

### Reproduction

[https://github.com/unovil/roamer](https://github.com/unovil/roamer)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 6.28 GB / 15.78 GB
  Binaries:
    Node: 18.18.0 - D:\Program Files\nodejs\node.EXE      
    npm: 10.4.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0
    @sveltejs/kit: ^2.5.0 => 2.5.5
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0
    svelte: ^4.2.7 => 4.2.13
    vite: ^5.0.3 => 5.2.8
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
This is not a minimal reproduction. Please provide one or this issue will be closed.

**Comment by unovil** [comment]
Hi, I've updated with a minimal reproduction.

**Comment by Conduitry** [comment]
The instructions being in the issue body rather than the repository readme wasn't the problem. The problem was that it's your actual project, with many dependencies, and reproducing the issue involves instructing the user to install a database.
