### ISSUE TITLE
Error when importing some modules: 'axios', 'cookie'

### ISSUE THREAD

**Issue by yussdev** [sveltejs/kit#1211]
SvelteKit is great and I love every part of it , I'm developing a new production app with SvelteKit and I can't use these two packages : 'axios', 'cookie'

vite config: 
                 `vite: {
			optimizeDeps: {
				include: ['axios']
			},
			ssr: {
				noExternal: Object.keys(pkg.dependencies || {})
			}
		}`
		
System Info: macOS 11, Node v12.20.0

Server Log:
[vite] Error when evaluating SSR module /node_modules/cookie/index.js:
ReferenceError: exports is not defined
    at /node_modules/cookie/index.js:15:1
    at instantiateModule (/Users/youssef/Desktop/my-app/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:69033:166)
[vite] Error when evaluating SSR module /node_modules/axios/index.js:
ReferenceError: module is not defined
    at /node_modules/axios/index.js:1:1
    at instantiateModule (/Users/youssef/Desktop/my-app/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:69033:166)
module is not defined

Client Log: 
GET http://localhost:3000/ 500 (Internal Server Error)

Code: 
```jsx
// index.svelte
<script context="module" lang="ts">
	export const prerender = true;
</script>
<script lang="ts">
	import axios from 'axios'
	import Counter from '$lib/Counter/index.svelte';
</script>
// hooks.ts
import cookie from 'cookie';
import { v4 as uuid } from '@lukeed/uuid';
import type { GetContext } from '@sveltejs/kit';
export const getContext: GetContext = (request) => {
	const cookies = cookie.parse(request.headers.cookie || '');
	return {
		is_new: !cookies.userid,
		userid: cookies.userid || uuid()
	};
};
```

**Comment by Mivinci** [comment]
I'm having the same problem here and the `noExternal` config did not work for me either. It seems like an unsolved bug of Vite, cuz I found a lot of discussion on this error especially this one https://github.com/vitejs/vite/issues/2579.

**Comment by Conduitry** [comment]
These are mentioned in the FAQ https://kit.svelte.dev/faq
