### ISSUE TITLE
Trailing slash on homepage

### ISSUE THREAD

**Issue by multipliedtwice** [sveltejs/kit#12133]
### Describe the bug

Homepage / and non-/URLs both returning 200.
![image](https://github.com/sveltejs/kit/assets/33694447/57d989b5-b7f7-425b-826b-905abe9462ab)

```
export const trailingSlash 
```
doesn't affect index page behavior.

### Reproduction

https://httpstatus.io/

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.45 GB / 15.87 GB
  Binaries:
    Node: 18.19.1 - ~\.nvm\versions\node\v18.19.1\bin\node.EXE
    Yarn: 3.6.3 - ~\.nvm\versions\node\v18.19.1\bin\yarn.CMD
    npm: 10.2.4 - ~\.nvm\versions\node\v18.19.1\bin\npm.CMD
    pnpm: 7.29.3 - ~\.nvm\versions\node\v18.19.1\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @sveltejs/adapter-cloudflare: ^4.1.0 => 4.1.0
    @sveltejs/adapter-node: 4.0.1 => 4.0.1
    @sveltejs/kit: 2.5.0 => 2.5.0
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: 4.2.11 => 4.2.11
    vite: 5.1.3 => 5.1.3
```

### Severity

annoyance

### Additional Information

Maybe there's a workaround with Cloudflare on how to enable homepage redirect?

**Comment by Conduitry** [comment]
There's no such URL as a host name followed by no path at all. There's always at least a `/`. When you request `https://example.com`, you're actually requesting `https://example.com/`.
