### ISSUE TITLE
sveltekit removes all styles from head

### ISSUE THREAD

**Issue by eye-wave** [sveltejs/kit#12142]
### Describe the bug

sveltekit removes all styles from head when elements such as h1 are added to <svelte:head>

### Reproduction

add h1 or div or any "visible" element to <svelte:head>

### System Info

```Shell
System:
    OS: Linux 6.8
    Memory: 6.28 GB / 14.99 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 21.7.3 - ~/.local/share/mise/installs/node/latest/bin/node
    bun: 1.1.3 - ~/.bun/bin/bun
```

### Severity

annoyance

**Comment by MotionlessTrain** [comment]
`<head>` elements aren't allowed to have visible elements in them (just things like a title, scripts, styles, and meta tags). Those all need to go in the `<body>` of an HTML-document. `<svelte:head>` allows you to add additional elements to the `<head>` of the document

**Comment by eye-wave** [comment]
i know that, but if you add those anyways, sveltekit just nukes all of your styles

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a repository, sveltelabs, or stackblitz project.

**Comment by gtm-nayan** [comment]
Closing as no reproduction was provided

**Comment by eye-wave** [comment]
here is a basic reproduction of this bug.
i made 2 routes `/a` and `/b` for demonstration purposes where one of them has a visible element inside of `<svelte:head>`

i saw the bug occur on the initial page load, so it can be seen only on
- initial page load
- going directly from page `/b` to `/a`
- refreshing the page after going into `/b`

https://github.com/eye-wave/sveltekit-bug-report-styles

**Comment by eye-wave** [comment]
@gtm-nayan can you reopen the issue? I've provided the repository as you asked. Sorry for such late response.

**Comment by gtm-nayan** [comment]
If you put a non-head element in the head, that'll cause the browser to not parse things correctly which moves elements and messes up hydration markers so you shouldn't expect it to work.
