### ISSUE TITLE
Svelte 5.0.0-next.123 fails to initialize on new project

### ISSUE THREAD

**Issue by Aurumaker72** [sveltejs/kit#12192]
### Describe the bug

When hosting the page locally via `npm run dev` and visiting, the following error appears in the console and the DOM doesn't load:

```ts
Uncaught TypeError: (anchor, props) => {
    let instance = {};
    let effect2;
    block(() => {
      const component2 = get(source2);
      if (effect2) {
        for (var k in instance)
          delete instance[k];
        destroy_effect(effect2);
      }
      effect2 = branch(() => {
        set_should_intro(false);
        Object.defineProperties(
          instance,
          Object.getOwnPropertyDescriptors(component2(anchor, props))
        );
        set_should_intro(true);
      });
    });
    return instance;
  } is not a constructor
    <anonymous> main.ts:19
```

### Reproduction

1. Create a Svelte Vite project using `npm create vite@latest`
2. Install packages using `npm i`
3. Launch the application using `npm run dev`, observe no error
4. Change the Svelte version in the package.json to ^5.0.0-next.123
5. Install packages using `npm i`
6. Launch the application using `npm run dev`, observe the error

For a quicker repro, see this [minimum repro project](https://github.com/Aurumaker72/svelte-5.0.0-next.123-startup-issue).

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 AMD Ryzen 3 PRO 3200G with Radeon Vega Graphics
    Memory: 23.52 GB / 31.95 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.1.0 
    svelte: ^5.0.0-next.123 => 5.0.0-next.123 
    vite: ^5.2.0 => 5.2.11
```

### Severity

blocking an upgrade

### Additional Information

I am aware that manually bumping package versions with disregard to other incompatibilities is probably not the intended way to upgrade to Svelte 5, but I haven't found any useful resources on the web regarding the upgrade process, so I went with my intuition.

**Comment by Conduitry** [comment]
You're not using SvelteKit. This is a project created from Vite's own Svelte template. They're maintaining that over in https://github.com/vitejs/vite/tree/main/packages/create-vite. It wouldn't surprise me if it hasn't been updated for Svelte 5 yet. From that error, it sounds like you're running into https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes.
