### ISSUE TITLE
Best practice: Where to import global css

### ISSUE THREAD

**Issue by manuel3108** [sveltejs/kit#12202]
### Describe the problem

I have been debating with myself multiple times, where global css imports (custom, tailwindcss, etc.) should be imported.

As they are global styles, they should be imported inside a `+layout.xx` file. But should we use `+layout.js` or `+layout.svelte`.

I was unable to find any relevant information for this inside the "Best practices" section inside the [docs](https://kit.svelte.dev/docs/performance). This issue was raised multiple times within the `svelte-add` project:
* https://github.com/svelte-add/svelte-add/issues/231
* https://github.com/svelte-add/svelte-add/pull/343
* And one more time, but I'm unable to find the appropriate issue

Additionally, a few months ago, I have seen this issue arise inside the discord server multiple times, partially with different conclusions.

### Describe the proposed solution

Determine the best practice and document it in the [docs](https://kit.svelte.dev/docs/performance) inside the "Best practices" section.

### Alternatives considered

---

### Importance

nice to have

### Additional Information

To be totally fair, I don't have a strong opinion on either of these options.

I think @AdrianGonz97 put it quite well in svelte-add/svelte-add#343
> Given that stylesheets directly affect the UI, and Svelte components are designed for building UIs, I think it'd make the most sense to keep the import in a svelte file.

On the other hand, you could argue that you are importing a CSS file inside a JS snippet no matter what, so does it make a difference at all?

**Comment by hyunbinseo** [comment]
The official Tailwind CSS [guide] suggests importing the CSS file in a root `+layout.svelte` file.

[guide]: https://tailwindcss.com/docs/guides/sveltekit

![image](https://github.com/sveltejs/kit/assets/47051820/546603e8-2542-4f6e-962a-fac0885b9e34)

Due to this, I was unaware that a CSS file was importable in a `+layout.js` file.

**Comment by gterras** [comment]
The answer you got in https://github.com/svelte-add/svelte-add/pull/343 is quite satisfying I don't understand why this was created as an issue and not a discussion.

**Comment by Conduitry** [comment]
I agree that `+layout.svelte` makes more sense than `+layout.js`. I disagree that this is something that warrants a note in the documentation. The other 'best practices' are focused on making your site better for end-users - but putting this import in one file or the other is going to result in sites that are pretty much indistinguishable to end-users.

**Comment by manuel3108** [comment]
Thanks a lot for all your responses!

Sorry for not making this a discussion, totally forgot about them!
