### ISSUE TITLE
Conflict between GET handler in +server.js and dynamic routes

### ISSUE THREAD

**Issue by anthonyivol** [sveltejs/kit#12218]
### Describe the bug

Not sure if it's a bug, but two independant routes handlers are called at the same time :
my routes are like so :
```yaml
- (admin)
    - admin
      - api
        - route
          - +server.js // <— GET handler that return json 
- (public)
  - [path]
    - +page.js
    - +page.svelte
  - ...
```
I have a `GET` handler in `(admin)/admin/api/route/+server.js` which return json data : 

In a browser if I go to `/admin/api/route` I get my json as expected, but also an error in the terminal console that comes from `(public)/[path]/+page.svelte`, as the `(public)/[path]/+page.js` load function is also called but it doesn't get it's params.

In the doc here : https://kit.svelte.dev/docs/routing#server-content-negotiation :

> GET/POST/HEAD requests are treated as page requests if the accept header prioritises text/html (in other words, it's a browser page request), else they are handled by +server.js

As json is returned by the API route, I am expecting that SvelteKit doesn't treat that route as a page request. 

And as there is no +page.svelte in my route API, it looks like sveltekit fallback to the dynamic route which match everything, which is weird as json is returned, and also both routes are in separate parenthesis folders.

However It seems that it only appears in the browser probably because of the accept "text/html", no problem with a fetch method. 

`(admin)/admin/api/+server.sj`
<img width="519" alt="image" src="https://github.com/sveltejs/kit/assets/19983700/6f9f3c0c-5e7f-414f-b3f3-92a19ab177cc">

`(public)/[path]/+page.js`
<img width="461" alt="image" src="https://github.com/sveltejs/kit/assets/19983700/7e4d1a47-91a0-4bd4-8224-ad70b583f11e">

<img width="798" alt="image" src="https://github.com/sveltejs/kit/assets/19983700/a8f3fc32-fb39-457c-adcc-345b85ff7d97">

### Reproduction

A minimal reproduction :
https://github.com/anthonyivol/sveltekit-routes-issue/tree/main

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 41.48 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.4.0 - ~/.nvm/versions/node/v21.4.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.4.0/bin/npm
    pnpm: 9.1.1 - /opt/homebrew/bin/pnpm
    bun: 1.1.8 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 124.1.65.133
    Chrome: 124.0.6367.208
    Safari: 17.4.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0 
    @sveltejs/kit: ^2.0.0 => 2.5.8 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0 
    svelte: ^4.2.7 => 4.2.17 
    vite: ^5.0.3 => 5.2.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
I can't seem to reproduce this by clicking on the api route link in the reproduction. Are there additional steps to reproduce the issue?
https://stackblitz.com/~/github.com/anthonyivol/sveltekit-routes-issue

**Comment by anthonyivol** [comment]
> I can't seem to reproduce this by clicking on the api route link in the reproduction. Are there additional steps to reproduce the issue? https://stackblitz.com/~/github.com/anthonyivol/sveltekit-routes-issue

I think it's probably because the stackblitz environment is emulating something, can you try on a local environment ?

https://github.com/sveltejs/kit/assets/19983700/9c567cfa-80ea-42f1-af46-3bcf0e870224

**Comment by eltigerchino** [comment]
Yeah, running it locally on MacOS reproduces the issue. I wonder if it's the same on other platforms or if it's MacOS specific.

**Comment by anthonyivol** [comment]
> Yeah, running it locally on MacOS reproduces the issue. I wonder if it's the same on other platforms or if it's MacOS specific.

Unfortunately I have no way to test it on other plateforms, but I can tell that the same issue appears with node 20

**Comment by eltigerchino** [comment]
So the issue is caused by the browser issuing a favicon request when visiting the endpoint in the browser. That favicon request then hits the dynamic parameter route since it matches `/favicon.ico`. You can test this by logging the request url in any server-side function. I guess this is intended behaviour...? (I have no clue what to think)

As an aside, thank you for the reproduction and issue. This was certainly an interesting one.

**Comment by anthonyivol** [comment]
Ahhhhh, I already had this `/favicon.ico` issue, with one in the static folder the error disappear, I think it's a defendable behaviour, like if you want to generate static assets (resized images,...) on the fly when requesting a static route, I don't know...
Thanks for your time anyway !
