### ISSUE TITLE
Navigation "flip back" bug on fresh install; pre-vite optimized dependencies

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/kit#12214]
### Describe the bug

SvelteKit "flips back" to prior pages after navigating to pages where Vite has not yet optimized dependencies.

This only happens on a fresh install and only in development, i.e. this sort of thing:

```
rm -rf node_modules
pnpm install
pnpm run dev
```

After Vite has optimized dependencies, SvelteKit`*` starts navigating correctly.

`*` slight chance this is a Vite bug, but since it's **_our navigation system_** going bananas, filing here. I also don't see any bugs filed over there.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-rz3oz5?file=README.md

Instructions in the README.md of the repro, and on startup (`pnpm run dev`).

### Logs

```Shell
4:11:30 PM [vite] ✨ new dependencies optimized: @tiptap/core, @tiptap/starter-kit
4:11:30 PM [vite] ✨ optimized dependencies changed. reloading
```
```


### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - ~/projects/sveltejs-kit-template-default-qeh3ub/node_modules/.bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: 3.2.0 => 3.2.0 
    @sveltejs/kit: 2.5.7 => 2.5.7 
    @sveltejs/vite-plugin-svelte: 3.1.0 => 3.1.0 
    svelte: 5.0.0-next.127 => 5.0.0-next.127 
    vite: 5.2.11 => 5.2.11
```

### Severity

annoyance

### Additional Information

For those of us neurotically updating dependencies... 😅

**Comment by eltigerchino** [comment]
This may have been fixed by https://github.com/sveltejs/kit/pull/12182 which configures Vite to correctly optimise dependencies before navigating to a page for the first time. The fix hasn’t been released yet despite being merged so you can test this first by adding the svelte route files to your Vite config optimizeDeps.entries option

**Comment by arxpoetica** [comment]
Gracias! Closing, and watching closely for the next Vite release.

**Comment by eltigerchino** [comment]
> Gracias! Closing, and watching closely for the next Vite release.

It's actually a fix on SvelteKit's side so we should probably cut a release soon (last one was 3 weeks ago).

**Comment by benmccann** [comment]
Okay, I just cut a release if you want to try to upgrade and see if it fixes this

**Comment by eltigerchino** [comment]
> Okay, I just cut a release if you want to try to upgrade and see if it fixes this

Aren't you suppose to be on vacation? 🤔

**Comment by benmccann** [comment]
Luckily doing a release is just the click of a button 😆

**Comment by arxpoetica** [comment]
HYPE it fixed it. (I updated the example which you can test over here: https://stackblitz.com/edit/sveltejs-kit-template-default-rz3oz5?file=README.md)
