### ISSUE TITLE
Aliasing in svelte.config.js doesn't include sources into the source map

### ISSUE THREAD

**Issue by tilkinsc** [sveltejs/kit#12219]
### Describe the bug

I wanted a `src/components` directory, to not pollute my `$lib`. However, when I went to run my code they would render correctly and mostly work, except for svelte specific features like `svelte::onMount`. So my navbar worked fine, while my cookie bar didn't since it hides and shows to prevent pop-in. It seems that `$lib` is also not working for me.

### Reproduction

Svelte base project initialization using npm with typescript, just smash enter all defaults except for typescript.
```
npm create svelte@latest myapp
```

Files involved:
./src/components/CookieBar.svelte
./src/+layout.svelte
./svelte.config.js
./tsconfig.json

```svelte
// +layout.svelte
<script>
	import CookieBar from '$comp/CookieBar.svelte';
</script>

<CookieBar />
```
```svelte
// CookieBar.svelte
<script>
	import { onMount } from "svelte";
	
	let cookieConsentHidden = true;
	
	onMount(() => {
		cookieConsentHidden = false;
	});
</script>

<div>
	{#if !cookieConsentHidden}
		<div>
			Cookie bar here
		</div>
	{/if}
</div>
```
```js
// svelte.config.js
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: vitePreprocess(),

	kit: {
		alias: { $comp: './src/components' },
		adapter: adapter()
	}
};

export default config;
```
tsconfig.json
```json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true,
		"moduleResolution": "bundler"
	}
}
```

```
npm run dev
```

You will not see `<CookieBar />`, setting `cookieConsentHidden = false;` in `onMount` will never show it either. However, `<style></style>` works and setting `let cookieConsentHidden = false;` will show it.

### Logs

![image](https://github.com/sveltejs/kit/assets/7494772/cc6b0db1-3f08-43a6-8c9c-59ec82d8f32d)

* no server logs

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 16.51 GB / 31.92 GB
  Binaries:
    Node: 21.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0
    @sveltejs/kit: ^2.0.0 => 2.5.7
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0
    svelte: ^4.2.7 => 4.2.16
    vite: ^5.0.3 => 5.2.11
```
```


### Severity

annoyance

### Additional Information

_No response_

**Comment by tilkinsc** [comment]
More information, it seems that sveltekit is very biased about the name 'Cookie' being in the file name. Removing it fixes everything. This is despite removing .svelte-kit

**Comment by gtm-nayan** [comment]
@tilkinsc do you have an adblocker active? See if it works in incognito mode.

**Comment by tilkinsc** [comment]
Oh. Thats a really good point. Yes. A really good point.
