### ISSUE TITLE
reroute not working in pages with server data.

### ISSUE THREAD

**Issue by angelvega93** [sveltejs/kit#12229]
### Describe the bug

In a page with a load function if you enter directly to the route with reroute it works, but if you go back history or navigate to it using a link, it does not work.

### Reproduction

Navigate and then go back history to the reroute url or navigate to it from a normal link.

https://stackblitz.com/edit/sveltejs-kit-template-default-d1dfkl

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0 
    @sveltejs/kit: ^2.0.0 => 2.5.9 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0 
    svelte: ^4.2.7 => 4.2.17 
    vite: ^5.0.3 => 5.2.11
```

### Severity

annoyance

**Comment by stephanedemotte** [comment]
any news on this ? I still have this issue :/
