### ISSUE TITLE
Please add `typescript-svelte-plugin` to the sveltekit template

### ISSUE THREAD

**Issue by ryoppippi** [sveltejs/kit#12228]
### Describe the problem

I install the `typescript-svelte-plugin` every time I create a Sveltekit project with `npm create svelte`. I've been doing that for the last year and a half and it's very time-consuming, so I'd like to see it added to the TEMPLATE.

### Describe the proposed solution

Add `typescript-svelte-plugin` to the svelte template(at least skeleton template) as a dependency

### Importance

would make my life easier

**Comment by eltigerchino** [comment]
After discussion with some other maintainers, I don't think we're in favour of adding the plugin to the default template. The reason being that the majority of users would be using the VS Code or IntelliJ Svelte plugin and would not need this configured in their projects.
