### ISSUE TITLE
Demo of tutorial page is not correct.

### ISSUE THREAD

**Issue by 2low** [sveltejs/kit#12241]
### Describe the problem

There is a problem with the tutorial on the official website.
I'm studying while watching the demo, but what I keep wanting isn't in the demo.
Please correct it.

### Describe the proposed solution

It is necessary to match the tutorial on the homepage with the demo page.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
You say it isn't correct. What exactly is not correct? What demo are you refering to?

Please provide more details/information/context or this issue will be closed.
