### ISSUE TITLE
Sveltekit build not rendering HTML properly

### ISSUE THREAD

**Issue by mellunar** [sveltejs/kit#12252]
### Describe the bug

When building the code to production, Sveltekit is not rendering the code as it's supposed to be.

This is how my code looks like in editor:
![sveltekit1](https://github.com/sveltejs/kit/assets/87154023/d9a8b271-6781-4fc2-96bf-0c9ad24a9f83)

When previewing it with 'npm run dev', it renders the code properly:
![sveltekit2](https://github.com/sveltejs/kit/assets/87154023/dd826160-c8d5-4b1d-abb5-adf44426231f)

But after building it to production, this is how it's rendered into view:
![sveltekit3](https://github.com/sveltejs/kit/assets/87154023/d8313131-8acf-47fa-8a82-b201ac5668b1)

In the last picture, the div is outside the anchor tag, causing the layout to be broken, and another anchor tag is created inside it.

### Reproduction

Create a project, add an anchor tag on a page, then insert content into a div inside it, and build/preview the project.

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 21.48 GB / 31.93 GB
  Binaries:
    Node: 20.13.0 - ~\.nvm\versions\node\v20.13.0\bin\node.EXE   
    npm: 10.5.2 - ~\.nvm\versions\node\v20.13.0\bin\npm.CMD      
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.0 => 3.2.0
    @sveltejs/kit: ^2.5.9 => 2.5.9
    @sveltejs/vite-plugin-svelte: ^3.1.0 => 3.1.0
    svelte: ^4.2.17 => 4.2.17
    vite: ^5.2.11 => 5.2.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Please provide a minimal reproduction in the form of a downloadable repository. Otherwise, I’m inclined to think this is an issue with how browsers handle anchor tags nested in other anchor tags. A similar issue to this is https://github.com/withastro/astro/issues/4864

**Comment by brunnerh** [comment]
It is not a browser issues, this is just invalid according to the spec.
> [Content model](https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model):
> [Transparent](https://html.spec.whatwg.org/multipage/dom.html#transparent), but there must be no [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) descendant, [a](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) element descendant, or descendant with the [tabindex](https://html.spec.whatwg.org/multipage/interaction.html#attr-tabindex) attribute specified.
