### ISSUE TITLE
enhanced:img should be considered a void element

### ISSUE THREAD

**Issue by mquandalle** [sveltejs/kit#12255]
### Describe the bug

Following https://github.com/sveltejs/svelte/issues/11052, svelte now warns on self closing tags for non void elements. This causes a warning when using `<enhanced:img />`, which is inconsistent with the usage of `<img />`

### Reproduction

<img width="650" alt="image" src="https://github.com/sveltejs/kit/assets/1730702/6319852f-daf0-43f2-9f23-6a677c6eb8f4">

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 83.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.14.1 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
    bun: 1.1.3 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 114.1.52.126
    Safari: 17.3.1
  npmPackages:
    @sveltejs/adapter-vercel: ^5.1.0 => 5.3.0 
    @sveltejs/enhanced-img: ^0.2.0 => 0.2.0 
    @sveltejs/kit: ^2.5.0 => 2.5.9 
    @sveltejs/pancake: ^0.0.18 => 0.0.18 
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.1.0 
    svelte: next => 5.0.0-next.137 
    vite: ^5.1.0 => 5.2.11
```

### Severity

annoyance

**Comment by mquandalle** [comment]
Probably an issue with https://github.com/sveltejs/language-tools/issues, not SvelteKit

**Comment by jasonlyu123** [comment]
Related to https://github.com/sveltejs/language-tools/issues/2321

**Comment by mquandalle** [comment]
This issue is fixed
