### ISSUE TITLE
Inflight Deprecation Warning

### ISSUE THREAD

**Issue by ananduremanan** [sveltejs/kit#12258]
### Describe the bug

On Installing dependencies after `npm create svelte@latest` I got `npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful`. Not sure if it is serious or not, saw `leaks memory` in it thus opened this issue.

### Reproduction

By Installing dependencies after `npm create svelte@latest`.

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 4.47 GB / 15.73 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers: {}
  npmPackages:
    @sveltejs/adapter-auto: latest => 3.2.1
    @sveltejs/kit: latest => 2.5.10
    @sveltejs/vite-plugin-svelte: latest => 3.1.0
    svelte: latest => 4.2.17
    vite: latest => 5.2.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
We should move this issue to svelte-preprocess https://github.com/sveltejs/svelte-preprocess
```sh
❯ npm why inflight
inflight@1.0.6 dev
node_modules/inflight
  inflight@"^1.0.4" from glob@7.2.3
  node_modules/glob
    glob@"^7.1.3" from rimraf@2.7.1
    node_modules/rimraf
      rimraf@"^2.5.2" from sander@0.5.1
      node_modules/sander
        sander@"^0.5.0" from sorcery@0.11.0
        node_modules/sorcery
          sorcery@"^0.11.0" from svelte-preprocess@5.1.4
          node_modules/svelte-preprocess
            svelte-preprocess@"^5.1.3" from svelte-check@3.7.1
            node_modules/svelte-check
              dev svelte-check@"^3.6.0" from the root project
```

**Comment by Conduitry** [comment]
Wouldn't the fix be to bump dependencies in https://github.com/rich-harris/sander, not svelte-preprocess? Or, perhaps, to just start using built-in filesystem APIs instead in https://github.com/Rich-Harris/sorcery?

**Comment by aymanin** [comment]
hello when i do the command to install nodered i have this error ,npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
what i can do?thank you

**Comment by ranaaboubakr** [comment]
I'm getting this error while trying to install Appium, any idea how it can be resolved?

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@7.0.1: This package is no longer supported.
npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
npm warn deprecated are-we-there-yet@4.0.2: This package is no longer supported.
npm warn deprecated gauge@5.0.2: This package is no longer supported.

**Comment by ananduremanan** [comment]
> I'm getting this error while trying to install Appium, any idea how it can be resolved?
> 
> npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm warn deprecated npmlog@7.0.1: This package is no longer supported. npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported npm warn deprecated are-we-there-yet@4.0.2: This package is no longer supported. npm warn deprecated gauge@5.0.2: This package is no longer supported.

The author of inflight deprecated the package on Mar 22. https://github.com/isaacs/inflight-DEPRECATED-DO-NOT-USE/issues/5#issuecomment-2126153820

**Comment by Srossiprieto** [comment]
@ananduremanan what should we do with the warnings that appear to us?

**Comment by ananduremanan** [comment]
> @ananduremanan what should we do with the warnings that appear to us?

If the package actually cause memory leak, then that would be a serious problem. The best we could do is find the package that uses inflight and replace it with ‘lru-cache’ as the author of inflight suggests and open a pull request or just wait for some cool people on open source community to fix it.

**Comment by ranaaboubakr** [comment]
is this issue on windows devices only or with mac users too?

**Comment by ananduremanan** [comment]
> is this issue on windows devices only or with mac users too?

I don't think so. When a package is deprecated it affects all users of that package, regardless of their operating system.

**Comment by BrunaMarjorie** [comment]
I am also having this problem when upgrading Capacitor from v.5 to v.6. I am a mac user.

**Comment by eltigerchino** [comment]
You can run `npm why inflight` or `pnpm why inflight` to figure out which package is depending on the deprecated package. In svelte-check’s case we will probably fix it by removing the dependency on inflight; replacing it with native APIs or a different package.

**Comment by Srossiprieto** [comment]
I have a problem when creating a project with Vite using the command `npm create vite@latest`. I go through all the configuration steps, but when I run the command npm install, I get warnings. This started happening after I followed a tutorial that used ESLint with the command `npx eslint --init`. After running that command, the warnings started appearing. Would you like me to run any command so you can see what might be going wrong?

**Comment by KikoB10** [comment]
I am also trying to install Appium and have gotten the same error message about inflight and a few other things. When I run `npm why inflight` terminal says  ' no dependencies found matching inflight' 

I am a bit lost as to what to do next? Do we just wait for a fix? I am fairly new to this and totally new to automated testing

**Comment by SugarD-x** [comment]
> I am also trying to install Appium and have gotten the same error message about inflight and a few other things. When I run `npm why inflight` terminal says ' no dependencies found matching inflight'
> 
> I am a bit lost as to what to do next? Do we just wait for a fix? I am fairly new to this and totally new to automated testing

I'm using a completely different project that depends on inflight as a sub-dependency, but I saw your post from a Google search and thought I'd pass along some information. I don't know anything about this project, but if it creates a package-lock.json after installation, you may be able to look in there to see what dependencies rely on it, and backtrack it to the parent one from there. That should give you your answer on which dependency is at fault.

**Comment by Chefkochcooking** [comment]
Hey guys!
I'm working on an web app rn and thus installed bun in VSCode. 
The installation was successfully but I am still concerned about those lines...

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

I am a newbie in the coding space. 
Any steps to solve this problem?

Thank you!
ChiefCook

**Comment by ananduremanan** [comment]
I think Updating [glob](https://github.com/isaacs/node-glob) in https://github.com/Rich-Harris/sander and https://github.com/Rich-Harris/sorcery may fix issues related to SvelteKit. Both of these packages use a lot of deprecated packages and haven't been updated for years.

**Comment by lorand-horvath** [comment]
This is caused by eslint@8 transient dependencies being deprecated, see report https://github.com/eslint/eslint/issues/18528

**Comment by kudo07** [comment]
> > I'm getting this error while trying to install Appium, any idea how it can be resolved?
> > npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm warn deprecated npmlog@7.0.1: This package is no longer supported. npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported npm warn deprecated are-we-there-yet@4.0.2: This package is no longer supported. npm warn deprecated gauge@5.0.2: This package is no longer supported.
> 
> The author of inflight deprecated the package on Mar 22. [isaacs/inflight-DEPRECATED-DO-NOT-USE#5 (comment)](https://github.com/isaacs/inflight-DEPRECATED-DO-NOT-USE/issues/5#issuecomment-2126153820)
> 
> This is common with JavaScript since anyone can came up with a package and when it got deprecated we get a bunch of errors or warnings.

 just downgrade the node into 18 may things works because ill do it in next js it works in 20 version but not in 22

**Comment by lorand-horvath** [comment]
Temporary solution: add `file-entry-cache` override to package.json, delete package-lock.json and `npm install`
```
  "overrides": {
    "eslint": {
      "file-entry-cache": "^8.0.0"
    }
  }
```

**Comment by rodneyazev** [comment]
In **_Select additional options_** mark the option **_Add ESLint for code linting_**

**Comment by benmccann** [comment]
`svelte-check` should remove its dependency on `svelte-preprocess`: https://github.com/sveltejs/language-tools/issues/2391. That would fix this issue for the majority of SvelteKit users and reduce the number of dependencies, which is always good. We should still fix `svelte-preprocess` for the users who are using it directly

**Comment by benmccann** [comment]
We should also probably remove `sorcery` from `svelte-preprocess`: https://github.com/sveltejs/svelte-preprocess/issues/637

**Comment by DevAloshe** [comment]
> is this issue on windows devices only or with mac users too?

with mac os too 

I got this error when installing whatsapp-wep.js package

npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated fstream@1.0.12: This package is no longer supported.
npm WARN deprecated puppeteer@18.2.1: < 22.6.4 is no longer supported

**Comment by benmccann** [comment]
All dependencies have now been removed from `svelte-preprocess`: https://x.com/BenjaminMcCann/status/1810698991820321028

Now we'll need to either update `svelte-check` to use this new version (https://github.com/sveltejs/language-tools/pull/2401) or see if the dependency on it can be removed (https://github.com/sveltejs/language-tools/issues/2391).

**Comment by iamjexcdevvv** [comment]
Hello I have the same error I am new to this so I have no idea what should I do, do you guys have a solution or just wait for an update or something?

**Comment by eltigerchino** [comment]
> Hello I have the same error I am new to this so I have no idea what should I do, do you guys have a solution or just wait for an update or something?

Hi jexc. Yes, see https://github.com/sveltejs/kit/issues/12258#issuecomment-2218052620 . We’ll have to wait to  a bit before updating to get rid of this warning

**Comment by atina867** [comment]
hello i getting this warning listed below while cloning Nest-js project , please help me with to get rid of this warning
 
 npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

**Comment by ankitbavne** [comment]
Hello, I am getting an npm deprecated warning in my NestJS project. Please help me get rid of this warning


npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

**Comment by lorand-horvath** [comment]
Add this to package.json, remove node_modules and package-lock.json, then execute `npm install`
```
  "overrides": {
    "eslint": {
      "@humanwhocodes/config-array": "npm:@eslint/config-array",
      "file-entry-cache": "^8.0.0"
    }
  }
```

**Comment by ankitbavne** [comment]
some warning gone but some is still there 

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated superagent@8.1.2: Please upgrade to v9.0.0+ as we have fixed a public vulnerability with formidable dependency. Note that v9.0.0+ requires Node.js v14.18.0+. See https://github.com/ladjs/superagent/pull/1800 for insight. This project is supported and maintained by the team at Forward Email @ https://forwardemail.net

**Comment by lorand-horvath** [comment]
You either did not do exactly what I suggested: `Add to package.json, remove node_modules and package-lock.json, then execute npm install`
or there is another package that is dependent on eslint and you would need to also add that to overrides.

**Comment by ankitbavne** [comment]
@lorand-horvath  
Yes, I did it and it works fine, but I have a doubt- is using overrides in package.json safe? I mean, will it not create problems in the future?

**Comment by benmccann** [comment]
You should not have to set overrides for eslint. Upgrade to eslint 9 instead. You can create a new SvelteKit project if you want to see an example of what it looks like to use eslint 9

**Comment by chris-avens** [comment]
@benmccann upgrading to eslint 9 causes npm error
 eslint@9.8.0 invalid: "^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0" from node_modules/eslint-plugin-react-hooks

**Comment by benmccann** [comment]
I wouldn't think you need `eslint-plugin-react-hooks` in a Svelte project. If you do, then you'll need to upgrade to the latest version and if the latest still doesn't support eslint 9 then that will need to be fixed in that plugin

**Comment by ankitbavne** [comment]
I’m getting a warning in my NestJS project. If I use override, there’s no warning. Are there any other options to remove the warning without using override?

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

**Comment by CJ-78** [comment]
can someone please help me with this? im trying to create a new project and this happens everytime:

> npm install
npm warn deprecated osenv@0.1.5: This package is no longer supported.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm warn deprecated rimraf@2.4.5: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@6.0.4: Glob versions prior to v9 are no longer supported
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead

added 1552 packages, and audited 1553 packages in 2m

146 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

✅ Your project is ready!

**Comment by benmccann** [comment]
We have started working on a new major version of svelte-check to fix this issue. The new version will drop these dependencies and many others. It will be probably a few weeks until it's ready due to vacation schedules and other commitments, but I'm excited about the improvements.

**Comment by ansAGujar** [comment]
I have created the new project with Angular 17 version. When i do npm install getting below warning.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated read-package-json@7.0.1: This package is no longer supported. Please use @npmcli/package-json instead.
npm warn deprecated backbone-undo@0.2.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info. 
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

Can someone please help me with this?

**Comment by dominikg** [comment]
it looks like this issue comes up high when searching for the warning. Please refrain from posting help requests or adding "me too" comments

**Comment by pracplayopen** [comment]
fwiw i tried both 'override' workarounds (including removing node_modules, package-lock.json and re-running npm install each time) and neither affected the inflight memory leak error at all.

i also find it strange that this has been happening FOR MONTHS in the default- "everybody should create a new project this way" method, and this is generating errors and memory leaks.   isn't svelte more polished that it has something that can be expected to work out of the box?  seems weird to be editing package.json for new project built from a template.  i appreciate the hard work and svelte does seem pretty interesting, but it's frustrating when the most basic things w/a new project need immediate maintenance... esp for a framework that's supposed to be EASIER.

**Comment by eltigerchino** [comment]
https://github.com/sveltejs/language-tools/releases/tag/svelte-check-4.0.0 just released a few days ago and removes the dependency on the old version of `svelte-preprocess` that depends on inflight.

**Comment by benmccann** [comment]
Yeah, I merged the fix on Monday, but hadn't cut a release yet. I just did that now, so new projects should no longer generate these warnings.

If you encounter this, please upgrade your project to `svelte-check` 4. If you have `svelte-preprocess` in your project make sure it's on version 6 or usually the better solution is to replace it with `vitePreprocess`: https://kit.svelte.dev/docs/integrations#vitepreprocess

This was difficult to fix because we had to fix so many different dependencies and cut major releases of multiple packages.

We've really reduced the number of dependencies by a lot during this process so that we're much less likely to hit these types of issues in the future. Compare https://npmgraph.js.org/?q=svelte-check@4 vs https://npmgraph.js.org/?q=svelte-check@3. There are plans to remove a majority of the remaining dependencies by upgrading to the upcoming chokidar v4 when it is released.

**Comment by ankitbavne** [comment]
I am getting the following warning in my NestJS backend project. Even after updating all the packages, I am still encountering this warning. Is there anyone who can help me get rid of it?

PS F:\Test_project\rescueworld-microservice-retteracademy> npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
![363954538-4cd1afdf-873f-436f-8276-f9f4cfeb41b0](https://github.com/user-attachments/assets/16afe87e-9bca-474f-a68b-737015746453)

**Comment by eltigerchino** [comment]
> it looks like this issue comes up high when searching for the warning. Please refrain from posting help requests or adding "me too" comments

**Comment by TunVunDerBunn** [comment]
Upgrading the eslint version resolves the issue. If someone else is still esperiencing the issue.

Run:
`npm i eslint@latest -D`

After that remove node_modules and package-lock.json and rerun:
`npm install`

The warnings disappeared for me.

**Comment by matzgans** [comment]
i have same error when i install "npm install whatsapp-web.js", how to solved the issue? please if you know about the problem please help me

**Comment by mgav** [comment]
> > @ananduremanan what should we do with the warnings that appear to us?
> 
> If the package actually causes a memory leak, it would be a serious problem. The best we can do is find the package that uses inflight (as @eltigerchino mentioned in his comment), replace it with `lru-cache` as the author of inflight suggests, and open a pull request. Alternatively, we could wait for some cool guy from the open-source community(like @Conduitry above) to fix it.

I'm getting the suggestion to use "lru-cache" (here's the whole message: "npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.")

**Comment by dickensas** [comment]
In pakage.json I put the below code, to solve this issue

```
"overrides": {
    "glob": "^11.0.1"
}
```

and the issue is resolved
