### ISSUE TITLE
Crawler does not crawl absolute URIs even if they are on `prerender.origin`

### ISSUE THREAD

**Issue by LorisSigrist** [sveltejs/kit#12271]
### Describe the bug

During Prerendering the Crawler is supposed to discover all internal links & follow them. However, if an internal link is on an absolute URI (`https://my-site.com`) or a Network-Path-refernece (`//my-site.com`) it will not be crawled, even if the origin is the same as `prerender.origin`.

I would expect these links to be crawled as well, assuming they are on the base path. 

Example: 
- `prerender.origin = "https://my-page.com"`
- `base = "/base"`
- `href = "https://my-page.com/base/some-page"` (should cause `/some-page` to be crawled)

### Reproduction

https://github.com/LorisSigrist/sveltekit-absolute-uri-crawling-repro (instructions in README)

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (14) arm64 Apple M3 Max
    Memory: 1.02 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 9.0.6 - /opt/homebrew/bin/pnpm
    bun: 1.1.8 - /opt/homebrew/bin/bun
  Browsers:
    Safari: 17.4.1
  npmPackages:
    @sveltejs/adapter-static: ^3.0.0 => 3.0.1 
    @sveltejs/kit: ^2.4.3 => 2.5.7 
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.1.0 
    svelte: ^4.2.7 => 4.2.15 
    vite: ^5.2.6 => 4.5.2
```

### Severity

serious, but I can work around it

### Additional Information

`<link rel="alternate"` links MUST be [absolute URIs](https://www.rfc-editor.org/rfc/rfc3986#page-27) according to [the spec](https://developers.google.com/search/docs/specialty/international/localized-versions#all-method-guidelines). 

This issue makes it impossible for the crawler to discover alternate language versions of pages if they are only linked via alternate tags.

**Comment by HannesScript** [comment]
Why did [LorisSigrist](https://github.com/LorisSigrist) down like [Static Side Generation](https://github.com/sveltejs/kit/issues/12272)? It's very *important* for me!!!
