### ISSUE TITLE
Source Code permission

### ISSUE THREAD

**Issue by HannesScript** [sveltejs/kit#12288]
### Describe the problem

Dear Svelte team,
I'm Hannes, a 10-year-old boy who has been programming since December 28, 2023.
My developer name is HannesScript and I **love** Svelte!
Now I want to create my own framework based on Svelte, so I want to ask you
**if I can get permission to use parts of Svelte and SveltKit source code** for my framework?
**I swear I will link to the Svelte.dev website!**

Best regards HannesScript

### Describe the proposed solution

I would like to read **yes** soon! 🤣

### Importance

would make my life easier

**Comment by HannesScript** [comment]
How can i start the Svelte/SvelteKits based code?

**Comment by dummdidumm** [comment]
You can find information about that here https://github.com/sveltejs/svelte/blob/main/CONTRIBUTING.md (same file exists in the kit repo)

**Comment by benmccann** [comment]
Creating your own framework is pretty advanced and usually done by experts with many years of experience. You might have a better experience learning an existing framework rather than trying to create a new one. For example, you might like https://learn.svelte.dev/tutorial/welcome-to-svelte

**Comment by HannesScript** [comment]
I code since 28 December 2023 but i'm already pretty experienced (i am 10 years old) look at my website (hannesscript.dev)[https://hannesscript.dev]
