### ISSUE TITLE
adapter-cloudflare-workers: platformProxy persist configuration example is wrong

### ISSUE THREAD

**Issue by tv42** [sveltejs/kit#12282]
### Describe the bug

https://kit.svelte.dev/docs/adapter-cloudflare-workers says

```js
svelte.config.js

import adapter from '@sveltejs/adapter-cloudflare-workers';

export default {
	kit: {
		adapter: adapter({
	  config: '<your-wrangler-name>.toml',
	  platformProxy: {
		persist: './your-custom-path'
	  }
	})
	}
};
```

https://developers.cloudflare.com/workers/wrangler/api/#syntax says

```
persist boolean | { path: string }

Indicates if and where to persist the bindings data. If not present or true, defaults to the same location used by Wrangler, so data can be shared between it and the caller. If false, no data is persisted to or read from the filesystem.
```

The doc example should be changed to `persist: { path: './your-custom-path' }`, or just `persist: true`.

### Reproduction

n/a to docs

### System Info

```Shell
n/a to docs
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Nite: we should fix this for adapter-cloudflare docs as well https://kit.svelte.dev/docs/adapter-cloudflare#usage
