### ISSUE TITLE
Page won't auto reload during development if CSR is disabled

### ISSUE THREAD

**Issue by LetrixZ** [sveltejs/kit#12286]
### Describe the bug

The page won't auto reload during development if a page has csr disabled.

### Reproduction

Add `export const csr = false` in `+page.ts` and make changes in the code.

https://github.com/sveltejs/kit/assets/25001812/5455f29e-cd22-467b-add6-3f16c4d5fe60

### System Info

```Shell
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M2
  Memory: 71.81 MB / 16.00 GB
  Shell: 3.7.1 - /opt/homebrew/bin/fish
Binaries:
  Node: 18.18.0 - ~/.local/share/nvm/v18.18.0/bin/node
  Yarn: 1.22.22 - ~/.local/share/nvm/v18.18.0/bin/yarn
  npm: 9.8.1 - ~/.local/share/nvm/v18.18.0/bin/npm
  pnpm: 9.1.2 - ~/Library/pnpm/pnpm
  bun: 1.1.7 - /opt/homebrew/bin/bun
Browsers:
  Chrome: 125.0.6422.141
  Safari: 17.5
npmPackages:
  @sveltejs/adapter-node: ^5.0.1 => 5.0.1 
  @sveltejs/kit: ^2.0.0 => 2.5.10 
  @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1 
  svelte: ^4.2.17 => 4.2.17 
  vite: ^5.0.3 => 5.2.12
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Setting csr to the value of the dev variable will enable js only during development so that the hot module reload still works.
https://github.com/sveltejs/kit/blob/25acb1d9fce998dccd8050b93cf4142c2b082611/packages/create-svelte/templates/default/src/routes/about/%2Bpage.ts#L5

**Comment by eltigerchino** [comment]
Reflecting on the current documentation, we could do with making a mention of it there and not just in the create svelte template https://kit.svelte.dev/docs/page-options#csr
