### ISSUE TITLE
SVGs which are imported and used as a `background-image` via a CSS variable get incorrectly encoded as a data URI during build

### ISSUE THREAD

**Issue by HopperElec** [sveltejs/kit#12283]
### Describe the bug

Importing an SVG, passing it as a CSS variable and using it as a background-image works in the dev server, where SvelteKit imports the SVG as a URL. However, when building the site, SvelteKit imports the SVG as a data URI. Data URIs are allowed in CSS, but SvelteKit is converting the SVG to a data URI incorrectly, resulting in "Invalid property value". SvelteKit actually seems to notice the invalid property value but, instead of reporting an error or sticking to just a URL, it just completely discards the property from the output.

Some context for why I am displaying the image in this unconventional way:
I am working on a component which resembles a fake IDE, with multiple files which can be viewed. Each file type has an icon associated with it, displayed alongside the file's name. These icons are displayed using a pseudo-element, hence why I am displaying the image via CSS instead of HTML. Because the icons are different depending on the file type, I pass the image as a CSS variable on the component.

I could of course just stop using a pseudo-element, but it took some time to figure out what was going wrong since SvelteKit was discarding the property altogether, and I don't want others to run into the same issue.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ntpuic?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.1 
    @sveltejs/kit: ^2.0.0 => 2.5.10 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1 
    svelte: ^4.2.7 => 4.2.17 
    vite: ^5.0.3 => 5.2.12
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
The conversion to a data uri is done by vite, not SvelteKit, it works in dev because the path in dev happens to not need to be quoted, but it is generally recommended that you wrap any urls you pass to CSS in quote marks like `url("${SvelteLogo}")`

And if you really wanted to, you can change the assetInlineLimit in the vite config
