### ISSUE TITLE
`$page.data` and `data` prop have different values

### ISSUE THREAD

**Issue by yuliankarapetkov** [sveltejs/kit#12295]
### Describe the bug

Sometimes `$page.data.myVar` and `data.myVar` have different values, which means one gets updated while the other doesn't. I can't provide a minimal reproducible example for a repository, but I can consistently reproduce the issue in the project I'm working on.

I'm not sure if it's related, but we are also using `depends()` and `invalidate()`

### Reproduction

I couldn't create a minimal reproducible repo.

### System Info

```Shell
System:
  OS: macOS 14.5
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 69.27 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.11.1 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.2.4 - /usr/local/bin/npm
  pnpm: 8.6.10 - /usr/local/bin/pnpm
Browsers:
  Brave Browser: 125.1.66.110
  Chrome: 125.0.6422.142
  Safari: 17.5
```

### Severity

serious, but I can work around it

**Comment by yuliankarapetkov** [comment]
This is still an issue, btw.

**Comment by eltigerchino** [comment]
There's nothing we can do without a minimal reproduction. If you can reproduce it, we can re-open the issue and investigate it.
