### ISSUE TITLE
Decrease server’s output file size by eliminating the need for static assets’ file data

### ISSUE THREAD

**Issue by tylerbrostrom** [sveltejs/kit#1233]
**Is your feature request related to a problem? Please describe.**

I’ve have project with many images in the `static` folder. Having all those files in `static` balloons the size of the output server module `.svelte-kit/output/server/app.js` and, more specifically, balloons the `SSRRenderingOptions` set by the server module’s `init` method.

All that file data from the `static` folder (`Asset[]`) is currently utilized by `Load` functions ran on the server in order lookup and handle fetch requests for assets from `static`. (e.g. prebaked data, etc.)

This _could_ eventually be problematic for a target environment like Cloudflare Workers where Worker scripts are limited to 1mb filesize.

**Describe the solution you'd like**

Speaking in terms of types, delete the `asset: Asset[]` property from `SSRManifest`.

So, how can we maintain support for fetching `static` files inside a `Load`?

Could that file list instead be generated at build time by introspecting each page and layout’s `Load` function? I’m not sure.

Or would a simpler option be to give Svelte Kit users some interface to explicitly pass in the relevant `Asset[]` data? And if that’s the case, what does that interface look like? Exposing this as a config option seems leaky. Maybe adding a new, optional parameter for `App['init']` would be appropriate? It’d at least give folks an ability to solve this issue in a custom adapter.

**Describe alternatives you've considered**

1. Look for opportunities to move files out `static`, and into the dependency graph (i.e. move file into and and reference it somewhere in`src`. This isn’t always possible.
2. Move static files that don’t need to be in the `SSRManifest` (i.e. aren’t fetched for inside a `Load`) into another folder. Write a post build script to copy those files into Svelte Kit’s output. This could be brittle (e.g. accidentally overwriting files).

**How important is this feature to you?**

Mildly important. It’s not a blocker now, but as the project grows, the more important conserving Worker file size will be.

**Comment by benmccann** [comment]
I didn't think service worker manifests would be used unless you're using the feature. Can you share a project where this is happening and explain where to look for the file?

**Comment by tylerbrostrom** [comment]
So admittedly, my initial explanation of this issue is completely naive; I filed it when I wasn’t very familiar with the codebase.

I’ve since updated both the initial comment and the title of the issue.

**Comment by benmccann** [comment]
This is one line of a 10,000 line file. I have no idea why static assets need to be in the manifest, but it doesn't seem particularly troublesome at the moment. I'm going to close it since it's low priority, but if someone ends up running into trouble we can consider PRs to improve it
