### ISSUE TITLE
`preloadData()` should be callable on the active route

### ISSUE THREAD

**Issue by kran6a** [sveltejs/kit#12386]
### Describe the problem

I have a route in which the user can view and update a resource.
When the user submits their changes the resource is modified server-side and the user wants to check the new version.
I could make the server return the updated resource on the PATCH request but that makes no sense from a back-end POV since the PATCH request won't be cached, will invalidate the GET request cache and the next GET request will hit the DB for the same information that was already returned on the PATCH request.

Ideally I would make a GET request for the updated resource, which would hit the DB a single time and populate the cache.

I tried the following and none of these work (they produce no network activity at all):

```typescript
goto(location.href); //Try navigating to the current page (expecting it to re-run the page load function)
```
 
```typescript
let {data}: {data: PageData} = $props();
const new_data = preloadData(location.href);
//Some error handling code
data = new_data.data;
```

I know about `invalidate()` but that re-runs all the parent layouts load functions as I use `await parent_data()` on the `+page.ts` file.
I would like to simulate navigating to the current page from another page sharing the same layout stack so only the deepest `+page.ts` load function is run.

### Describe the proposed solution

Calling `preloadData()` on the current route re-runs that route load function without re-running the whole layout stack load functions as it currently does when navigating between routes sharing the same layout stack.

### Alternatives considered

Copying or sharing the data fetching and transformation currently done on the `+page.ts` file into `+page.svelte` so I can update the `data` prop manually.

### Importance

would make my life easier

**Comment by kran6a** [comment]
Nevermind, found the culprit: the data was being fetched in `+layout.ts` and transformed in `+page.ts`. `+page.ts` in corretly re-run when using `preloadData()` but it keeps transforming stale data since `+layout.ts` is not re-run.

I still struggle to find a way to only re-run the innermost `+layout.ts` and `+page.data` files without rerunning the whole layout stack.

**Comment by eltigerchino** [comment]
Have you tried only invalidating the page load function by passing a custom identifier instead of the current URL?  https://kit.svelte.dev/docs/load#rerunning-load-functions-manual-invalidation

**Comment by carmas123** [comment]
Another proble occurs when you try to 
`preloadData(location.href);` using a custom `+layout.server.ts` that throw an `error(403)`.
For example when you try to preloadData for a custom page under a path like this:

details/user/[id]/+page.svelte
details/user/[id]/+page.server.ts

Having a +layout.server.ts under
details/+layout.server.ts

And into +layout.server.ts you try to puth a code like this

```
export const load: ServerLoad = async ({ request, parent, isDataRequest }) => {
        throw error(403, {
            message: 'No access!!!'
        });
}
```

the preloadData function does not handle the exception but return always the result.type === 'loaded' and status === 200.

In addition the preloadData function return the previous loaded data into the current page.

**Comment by eltigerchino** [comment]
closing this in favour of https://github.com/sveltejs/kit/issues/12399 since it has started a discussion for a potential solution. Really appreciate the additional thoughts in this issue though.
