### ISSUE TITLE
Make SSR's fetch send the referrer header when the destination is an endpoint

### ISSUE THREAD

**Issue by hgl** [sveltejs/kit#1240]
**Is your feature request related to a problem? Please describe.**
The referrer header can be really useful for some apps, but currently, when fetching an endpoint, only the client's fetch calls set the referrer header, not SSR's.

**Describe the solution you'd like**
Make SSR's fetch also set referrer header when the destination is an internal URL.

Svelte kit has almost everything it needs to construct the referrer url, lacking only the protocol.

The need for knowing the protocol also exists within svelte kit itself.
https://github.com/sveltejs/kit/blob/b4a851e4af1102de53ad6b09dee52438f2e7f330/packages/kit/src/runtime/server/page/load_node.js#L126-L130

**Describe alternatives you've considered**
Ask users to manually set this header themselves, but it's quite cumbersome once the header is needed in lots of places.

**How important is this feature to you?**
Not very, since there is a workaround, but I do have to pass the protocol in from an environment variable.

**Additional context**

**Comment by mrkishi** [comment]
As of #3631, `load()`'s `fetch` forwards most headers from the client.
