### ISSUE TITLE
[DOCS] Link to $service-worker module is not valid

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#1242]
Link to $service-worker module is not valid.
In section https://kit.svelte.dev/docs#service-workers there is link to https://kit.svelte.dev/docs#modules-service-worker instead https://kit.svelte.dev/docs#modules-$service-worker that doesn't exist, so it instead load (or scroll to) https://kit.svelte.dev/docs (top of docs)
the problem is "$" character in URL.

Also " expose the server to the network. This will allow people using the same coffee shop WiFi as you to see files on your computer; use it with care" in section https://kit.svelte.dev/docs#command-line-interface-svelte-kit-dev doesn't seems valid, it exposes file of your svelte project, but not whole filesystem, or does? If yes, I see security problem here.

**Comment by benmccann** [comment]
That security issue does exist unfortunately https://github.com/vitejs/vite/issues/2820. Maybe we should add a link to the issue so that if people read this section after the issue is closed we remember to update the docs

**Comment by Mlocik97** [comment]
I see this is fixed now.
