### ISSUE TITLE
Change the name of the special `fetch` function

### ISSUE THREAD

**Issue by felipesantoz** [sveltejs/kit#12435]
### Describe the problem

Since `fetch` from the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is a global variable, using the exact same name for the special context-specific SvelteKit `fetch` is error prone and unfriendly to beginners. For example, say we meant to write the following code in `routes/+page.server.ts`:
```ts
export const load: PageServerLoad = ({ fetch }) => {
 fetch('/example');
};
```
But instead, we accidentally wrote the code as such:
```ts
export const load: PageServerLoad = () => {
 fetch('/example');
};
```
The compiler will not complain, and we will be none the wiser about anything being wrong until encountering a run-time error. Then, when trying to debug the source of said error, it will likely take some time and/or previous experience with this type of error to find where the problem is. To make matters worse, there is a chance the error will be intermittent, making it even harder to catch.

The docs are also unclear about this. Take for example the documentation for [handleFetch](https://kit.svelte.dev/docs/hooks#server-hooks-handlefetch). It states:
> This function allows you to modify (or replace) a `fetch` request that happens inside a `load` or `action` function that runs on the server (or during pre-rendering).

There is no mention that this `fetch` request cannot come from the global `fetch`.

### Describe the proposed solution

There are a few ways to easily remedy the issue. My preferred is to simply rename the SvelteKit `fetch` to something else, for example `svetch`. Then the following will lead to a compiler error:

```ts
export const load: PageServerLoad = () => {
 svetch('/example');
};
```

And the docs will refer to `svetch` rather than `fetch`, removing all ambiguity from code and documentation alike.

### Alternatives considered

Some other form of compile-time error or warning could be used. For example, there could be an `eslint` rule to error/warn whenever the global `fetch` is referenced within a `load` or `action` function. With this solution, I'm not sure if it's possible to manage the cases where such a reference is made within a helper function, so perhaps a clear runtime error/warning in these cases might be more realistic. Perhaps instead eslint can complain whenever global `fetch` appears in any `server` file at all.

Alternatively, global `fetch` could be disabled by default within SvelteKit projects, requiring an explicit import to use. While this should be enough for more experienced users of SvelteKit to avoid the mistake, it does not necessarily discourage beginners from importing global `fetch` when learning from the docs. I'm also not sure if this is even possible to do on a browser.

### Importance

would make my life easier

**Comment by timothycohen** [comment]
ESLint has this pretty well covered.

```js
// eslint.config.js

/** @type {import('eslint').Linter.FlatConfig} */
const safeFetch = {
	files: ['**/+*'],
	ignores: ['**/+*.svelte'],
	rules: {
		'no-restricted-globals': [
			'error',
			{
				name: 'fetch',
				message: 'Use SvelteKit load fetch instead. Docs: https://kit.svelte.dev/docs/load#making-fetch-requests',
			},
		],
	},
};

export default config = [otherStuff, safeFetch]
```
<img width="706" alt="Screenshot 2024-07-07 at 14 50 21" src="https://github.com/sveltejs/kit/assets/83622086/dea5ef9b-816e-4b0c-89c8-f9e727a77d96">

But it would be nice as a default lint instead of relying on the browser console warnings.

**Comment by felipesantoz** [comment]
Thanks for the reply. This looks like a decent solution, but I think it comes with a couple of caveats:

- `load` is not the only place where you may want to use the special fetch request, other examples include form `actions` or using `event.fetch` in an API endpoint. So the error message might be misleading. This can probably be fixed by just changing the message however.
- There might be times where you _do_ want to use global `fetch`, for example if you want to explicitly bypass the logic in `handleFetch`. Disabling the error line by line is one solution, but it's ugly.

**Comment by dummdidumm** [comment]
Thanks for the suggestion, but we're not going to change the name of the fetch method, even if it may sometimes cause a bit of confusion - the dev time warnings will catch it quickly.

**Comment by felipesantoz** [comment]
@dummdidumm what do you mean by dev time warnings? I have never seen any warnings to do with this. I also don't quite understand the resistance to changing the name of `fetch`, given you failed to provide a compelling reason to keep it as is.

**Comment by timothycohen** [comment]
> * There might be times where you _do_ want to use global `fetch`, for example if you want to explicitly bypass the logic in `handleFetch`. Disabling the error line by line is one solution, but it's ugly.

You can write `globalThis.fetch`.

> * That rule will not catch the error in the following case:

Change `includes` to be all files and change your function to 
export const loadHelper = () => {
  fetch('/example');
};

export const load: PageServerLoad = () => {
 loadHelper();
};

**Comment by felipesantoz** [comment]
> You can write globalThis.fetch

> Change `includes` to be all files

Yep, this is the way to go about it, since it doesn't seem like they're keen on changing the name. It's a shame, because I've never seen another framework/library override a global variable name like this, and for good reason - it's so obviously an anti-pattern to do so.

**Comment by felipesantoz** [comment]
@dummdidumm I think I understand why I'm not seeing warnings, the warning only appears when using a relative URL, but the following will not yield any warning:

```ts
export const load: PageServerLoad = () => {
 fetch('example.com');
};
```

When, for example, using this as a proxy for an external API, you will run into cookie issues. Debugging the source of the cookie issues is often a pain.
