### ISSUE TITLE
The `base` path from `$app/paths` differs between SSR and client using the default config

### ISSUE THREAD

**Issue by ryanatkn** [sveltejs/kit#12441]
### Describe the bug

With no config added to a newly created skeleton project, the value of the `base` path from `$app/paths` is `'.'` during SSR and `''` on the client. This can cause bugs and hydration issues when the markup branches.

A workaround:

```ts
const actual_base = base === '.' ? '' : base;
```

The type of `base` is `"" | /${string}` causing the above to error in TypeScript:

```ts
const actual_base = (base as any) === '.' ? '' : base;
```

### Reproduction

https://github.com/ryanatkn/sveltekit-ssr-base-path-difference-repro

### System Info

```Shell
System:
    OS: Linux 6.9 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 6800U with Radeon Graphics
    Memory: 22.89 GB / 30.59 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 22.3.0 - /run/user/1000/fnm_multishells/28207_1720299464872/bin/node
    npm: 10.8.1 - /run/user/1000/fnm_multishells/28207_1720299464872/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.2 
    @sveltejs/kit: ^2.0.0 => 2.5.18 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1 
    svelte: ^4.2.7 => 4.2.18 
    vite: ^5.0.3 => 5.3.3
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
This is intended. See the kit.config.paths.relative option description for more details.

> If true, base and assets imported from $app/paths will be replaced with relative asset paths during server-side rendering, resulting in more portable HTML

https://kit.svelte.dev/docs/configuration#paths

It defaults to true, so you can set it to false if this behaviour is undesirable.

**Comment by ryanatkn** [comment]
Thank you, I read that but didn't understand. I should have tried the setting before opening this issue.

I don't think I benefit from the added portability of keeping the default `relative: true` unless I misunderstand, but I can see how that gives users more flexibility downstream of the build.

**Comment by ryanatkn** [comment]
I see the type referenced in 5 places in 4 files:

I think these need to be changed from:

```diff
- '' | `/${string}`
+ '' | `/${string}` | '.' | `./${string}`
```

- [src/runtime/app/paths/types.d.ts](https://github.com/sveltejs/kit/blob/144fb75c8280695d8aeb3228904bebb262e171a7/packages/kit/src/runtime/app/paths/types.d.ts#L6)
- [types/index.d.ts](https://github.com/sveltejs/kit/blob/144fb75c8280695d8aeb3228904bebb262e171a7/packages/kit/types/index.d.ts#L2141)

Probably this one?

- [src/types/ambient-private.d.ts](https://github.com/sveltejs/kit/blob/144fb75c8280695d8aeb3228904bebb262e171a7/packages/kit/src/types/ambient-private.d.ts#L12)

I don't know for sure but I'm guessing these do not change:

- [src/exports/public.d.ts](https://github.com/sveltejs/kit/blob/144fb75c8280695d8aeb3228904bebb262e171a7/packages/kit/src/exports/public.d.ts#L510)
- [types/index.d.ts](https://github.com/sveltejs/kit/blob/144fb75c8280695d8aeb3228904bebb262e171a7/packages/kit/types/index.d.ts#L492)

**Comment by eltigerchino** [comment]
I think the type is set up so that the user can leave it as an empty string or set a base path “/base”, etc.. The . and ./ are automatically prepended only during ssr. If csr is enabled, these are removed during hydration.

**Comment by eltigerchino** [comment]
I'll admit, I don't fully understand it myself. Maybe @Rich-Harris or @benmccann can chime in on the design behind this.

**Comment by mpost** [comment]
Just wanted to chim in that i stumbled upon the same issue. The docs and the relation to the `relative` property should be documented on the docs of the `base` property.

**Comment by Rich-Harris** [comment]
The idea is that `${base}/foo.jpg` resolves to `./foo.jpg` when you render the root, and `/foo.jpg` once the app starts in the browser — because it's a root-relative path, it will stay correct as you navigate around, whereas `./foo.jpg` could become something else if you were on a different page.

The reason we use relative paths during SSR is that the base path might be something other than `/`, either because you configured it that way, or because you're in an environment where you don't control the basepath (e.g. IPFS or the Wayback Machine).

It _does_ sound like the types are wrong
