### ISSUE TITLE
Update about page of examples/hn.svelte.dev

### ISSUE THREAD

**Issue by borntofrappe** [sveltejs/kit#1244]
This is an incredibly small issue, but [the about page for the demo of hn.svelte.dev](https://github.com/sveltejs/kit/blob/master/examples/hn.svelte.dev/src/routes/about.svelte#L12) refers to Sapper instead of SvelteKit.

```html
<p>This is a simple Hacker News clone, built with <a href="https://sapper.svelte.dev">Sapper</a>, an application framework for <a href="https://svelte.dev">Svelte</a>.</p>
```

If you'll allow me, I'd create a pull request to refer to SvelteKit instead.

**Comment by dummdidumm** [comment]
Sure, go ahead!

**Comment by benmccann** [comment]
Fixed. Thanks for raising the issue. Feel free to just St send a PR next time
