### ISSUE TITLE
Bun is not avaible in sveltekit

### ISSUE THREAD

**Issue by craigcosmo** [sveltejs/kit#12478]
### Describe the bug

Bun is not avaible in sveltekit

![CleanShot 2024-07-18 at 13 00 52](https://github.com/user-attachments/assets/c353c6b6-54e4-4f60-ba4d-2c9f0050e923)

### Reproduction

do this

```js
	Bun.write(pathname, new Uint8Array(await file.arrayBuffer()))
```

### Logs

```Shell
Cannot find name 'Bun'
```

### System Info

```Shell
macos sonoma
vscode Version: 1.77.3 (Universal)
```

### Severity

blocking all usage of SvelteKit

**Comment by Dudek-AMS** [comment]
This is not a svelte kit issue. As former bun discord team member and developer of one of the first bun sveltekit adapters i can tell you:

- 1) you need to tell vite to run in bun, not node --bun
- 2) install the bun types into your project for IDE 


default vite will run on node, so Bun is not available

**Comment by craigcosmo** [comment]
it was `bunx --bun ` in script already

**Comment by Dudek-AMS** [comment]
Maybe show some more how you call it. Anyway
'Cannot find name Bun' is a runtime error, therefor your program doesnt run on Bun. There's nothing sveltekit can do about it. Its like you are complaining not having google services on a apple phone iphone

**Comment by Dudek-AMS** [comment]
@craigcosmo  you dont want to declare bun yourself, take this one
https://www.npmjs.com/package/bun-types

**Comment by craigcosmo** [comment]
thanks
