### ISSUE TITLE
docs: use server load function in the `setHeaders` example

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#12473]
### Describe the bug

Current `setHeaders` [documentation](https://kit.svelte.dev/docs/load#headers) uses the universal load function in its example:

```js
// src/routes/products/+page.js

/** @type {import('./$types').PageLoad} */
export async function load({ fetch, setHeaders }) {
  const url = `https://cms.example.com/products.json`;
  const response = await fetch(url);

  // cache the page for the same length of time
  // as the underlying data
  setHeaders({
    age: response.headers.get('age'),
    'cache-control': response.headers.get('cache-control')
  });

  return response.json();
}
```

However, the page is cached only if both criteria are matched (or if CSR is disabled)

- SSR is enabled in the `/products` route
- The `/products` pages is directly accessed

### Reproduction

https://github.com/sveltejs/kit/issues/12473#issuecomment-2228582258

If the API does not respond with a `cache-control` header, it will be fetched every time the page is client-side rendered.

Also in a universal load function, the developer does not have control over the above API response caching.

The browser simply adheres to the API's HTTP response headers.

However, in a server load function, the developer can always have control using `setHeaders`.

### System Info

```Shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 37.39 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.15.1 - ~/.local/state/fnm_multishells/11115_1721012439034/bin/node
  npm: 10.7.0 - ~/.local/state/fnm_multishells/11115_1721012439034/bin/npm
  pnpm: 9.5.0 - ~/.local/state/fnm_multishells/11115_1721012439034/bin/pnpm
Browsers:
  Chrome: 126.0.6478.127
  Edge: 126.0.2592.102
  Safari: 17.5
npmPackages:
  @sveltejs/adapter-auto: ^3.0.0 => 3.2.2 
  @sveltejs/kit: ^2.0.0 => 2.5.18 
  @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.1 
  svelte: ^4.2.7 => 4.2.18 
  vite: ^5.0.3 => 5.3.3
```

### Severity

annoyance

### Additional Information

The universal load function's caveat is documented.

> When running in the browser, `setHeaders` has no effect.

**Comment by eltigerchino** [comment]
Isn’t the `data.json` that’s fetched during CSR being cached correctly?

**Comment by hyunbinseo** [comment]
This is the reproduction I've used:

Navigating between `/` and `/profile`, the [JSONPlaceholder](https://jsonplaceholder.typicode.com/) is continuously fetched in the browser.

```svelte
<!-- src/routes/+page.svelte -->
<a href="/profile">Profile</a>
```

```svelte
<!-- src/routes/profile/+page.svelte -->
<a href="/">Home</a>
```

```ts
// src/routes/profile/+page.ts
export const load = async ({ fetch, setHeaders }) => {
  await fetch('https://jsonplaceholder.typicode.com/users/1');
  setHeaders({ 'cache-control': 'public, max-age=604800' });
  return {};
};
```

When the `/profile` page is accessed directly, the HTML is properly cached.

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
cache-control: public, max-age=604800
content-length: 871
content-type: text/html
```

**Comment by hyunbinseo** [comment]
@eltigerchino in the documentation example, the CMS fetch request would have been cached in the client.

```js
/** @type {import('./$types').PageLoad} */
export async function load({ fetch, setHeaders }) {
  const url = `https://cms.example.com/products.json`;
  const response = await fetch(url); // has 'cache-control' header

  setHeaders({
    age: response.headers.get('age'),
    'cache-control': response.headers.get('cache-control')
  });
```

I have updated the above comment with a API response without a `cache-control` header.

**Comment by eltigerchino** [comment]
I'm not sure if we want to change it to a server load function in this case because that would incur an additional network request roundtrip instead of directly fetching from the CMS itself. It's also likely that the developer would have control over cache-control headers of that CMS.

**Comment by hyunbinseo** [comment]
I've personally written this issue after facing the following [Reddit question](https://www.reddit.com/r/sveltejs/comments/17mgt85/comment/ld8fwpr):

> My homepage makes about 15 API calls to an external API in the +page.server.ts file. The data does not change very often, and I don't want those API calls made every time the homepage is loaded or navigated to. Instead, I'd like the API to be called the first time a user navigates to the homepage, and then cached data to be used for that user for the next 24hr.

To my surprise, no one was mentioning the `setHeaders` API.

---

Would there be a better example other than a CMS fetch request?

e.g. change it to a `/` route which a user might directly revisit multiple times?

If a server-side rendered HTML must be cached in the client (which is not the default behavior), shouldn't it be because the SSR is slow or computationally heavy? (similar to the question above)

Please correct me if I am misunderstanding the example code from the documentation.

**Comment by eltigerchino** [comment]
> I've personally written this issue after facing the following [Reddit question](https://www.reddit.com/r/sveltejs/comments/17mgt85/comment/ld8fwpr):
> 
> > My homepage makes about 15 API calls to an external API in the +page.server.ts file. The data does not change very often, and I don't want those API calls made every time the homepage is loaded or navigated to. Instead, I'd like the API to be called the first time a user navigates to the homepage, and then cached data to be used for that user for the next 24hr.
> 
> To my surprise, no one was mentioning the `setHeaders` API.
> 
> Would there be a better example other than a CMS fetch request?
> 
> e.g. change it to a `/` route which a user might directly revisit multiple times?
> 
> If a server-side rendered HTML must be cached in the client (which is not the default behavior), shouldn't it be because the SSR is slow or computationally heavy? (similar to the question above)
> 
> Please correct me if I am misunderstanding the example code from the documentation.

I think the meaning in the example is conveyed well enough: if you want to cache the page, then set a cache control header. In the user's reddit question, they may be calling an external API with a secret key, so they can't use a universal load function without exposing the secret.

If no secrets or server-only APIs are needed, a universal load function is almost always preferred.
