### ISSUE TITLE
URL Search Params not correctly parsed when using ";" as divider

### ISSUE THREAD

**Issue by gemue-parndt** [sveltejs/kit#12489]
### Describe the bug

When parsing an URL like `http://localhost:5173/api/v1/generation?a=1&b=2&c=3` everything works fine.
But when chaning `&` to `;` it breaks and doesn't separate the params by the semicolon

### Reproduction

Simple GET endpoint in `src/routes/api/v1/generation/+server.ts`

```ts
import { json, type RequestHandler } from '@sveltejs/kit';

export const GET: RequestHandler = async ({ url, params }) => {
	console.log(params, url.searchParams);
	return json({ generation: 'generation' });
};
```

Called URL:  `http://localhost:5173/api/v1/generation?a=1;b=2;c=3`
Output of console log when using semicolon as divider:
```
[2024-07-23 13:30:36.101Z] [GET] /api/v1/generation - Status: 200 - OK
{} URLSearchParams { 'a' => '1;b=2;c=3' }
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (28) x64 13th Gen Intel(R) Core(TM) i7-13850HX
    Memory: 10.38 GB / 31.69 GB
  Binaries:
    Node: 22.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Roaming\npm\pnpm.CMD
    bun: 1.1.16 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (126.0.2592.113)
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.2 => 3.2.2
    @sveltejs/adapter-node: ^5.2.0 => 5.2.0
    @sveltejs/kit: ^2.5.18 => 2.5.18
    @sveltejs/vite-plugin-svelte: ^3.1.1 => 3.1.1
    svelte: ^5.0.0-next.193 => 5.0.0-next.195
    vite: ^5.3.4 => 5.3.4
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
Could you please point to the specification that says `;` can be used to separate search params and it should be parsed correctly

**Comment by gemue-parndt** [comment]
@gtm-nayan https://www.ietf.org/rfc/rfc3986.txt  - At section 3.3 Path

**Comment by Conduitry** [comment]
3.3 mentions semicolons being used in the _path_, not the query. https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams is the API being used here to parse the query parameters, which has certain (very standard) expectations, like them being separated by ampersands. If you need to parse query portions of your URLs yourself because they use a different format, do so from https://developer.mozilla.org/en-US/docs/Web/API/URL/search
