### ISSUE TITLE
SVELTEKIT WITH WASM - DEV WORKS BUT DURING BUILD WASM FILE IS LOST

### ISSUE THREAD

**Issue by pyenthu** [sveltejs/kit#12498]
### Describe the bug

I am working with a wasm library from Manifold-3d. I am able to import it during dev, but in the build directory this gets lost.
```

import init from "./built/manifold?init";

let newWasm = await init().then((instance) => {
  console.log("THIS IS IT INIT ", instance);
  instance.setup();
  return instance;
});
```
failed to asynchronously prepare wasm: Error: ENOENT: no such file or directory, open '/XXX/GitHub/YYYY/.svelte-kit/output/server/entries/pages/geo/manifold.wasm' Aborted(Error: ENOENT: no such file or directory, o '/Users/neerajsethi/Dropbox/GitHub/XXX/.svelte-kit/output/server/entries/pages/geo/manifold.wasm'). Build with -sASSERTIONS for more info.

Is there any way to ensure that this file is found in build as well?

### Reproduction

```
import init from "./built/manifold?init";

let newWasm = await init().then((instance) => {
  console.log("THIS IS IT INIT ", instance);
  instance.setup();
  return instance;
});
```
failed to asynchronously prepare wasm: Error: ENOENT: no such file or directory, open '/XXX/GitHub/YYYY/.svelte-kit/output/server/entries/pages/geo/manifold.wasm' Aborted(Error: ENOENT: no such file or directory, o '/Users/neerajsethi/Dropbox/GitHub/XXX/.svelte-kit/output/server/entries/pages/geo/manifold.wasm'). Build with -sASSERTIONS for more info.

### Logs

```Shell
failed to asynchronously prepare wasm: Error: ENOENT: no such file or directory, open '/XXX/GitHub/YYYY/.svelte-kit/output/server/entries/pages/geo/manifold.wasm' Aborted(Error: ENOENT: no such file or directory, o '/Users/neerajsethi/Dropbox/GitHub/XXX/.svelte-kit/output/server/entries/pages/geo/manifold.wasm'). Build with -sASSERTIONS for more info.
```

### System Info

```Shell
Sveltekit, Chrome, SSR
```

### Severity

blocking all usage of SvelteKit

### Additional Information

If I cannot use wasm reliably then it will not be possible to use sveltekit

**Comment by dominikg** [comment]
There is no need for all caps in the issue title.

Please provide a repository with a minimal reproduction as asked in the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by dominikg** [comment]
For questions about sveltekit and how to use wasm, please join https://svelte.dev/chat and ask in `#help-svelte-and-kit`

**Comment by pyenthu** [comment]
Sorry about the caps. Changed. I finally fixed this by taking advice from another forum.
Had to exclude the package in vote.

**Comment by pyenthu** [comment]
https://github.com/elalish/manifold/discussions/873
This describes the solution.
