### ISSUE TITLE
Support CSRF allow list

### ISSUE THREAD

**Issue by williamoverton** [sveltejs/kit#12505]
### Describe the problem

Our application needs to accept a webhook from Slack, the only format this comes in is via a form encoded POST request.

The problem is in production we get the following error:
```
Cross-site POST form submissions are forbidden
```

This is because we enable origin checking in production for improved security:
svelte.config.js:
```
kit: {
  csrf: { 
    checkOrigin: process.env.NODE_ENV === 'production',
  }
}
```

This is a great security measure to have out the box for the rest of our app, but we are going to be forced to turn it off in order to accept cross origin post requests on one single route.

### Describe the proposed solution

I would like to have an extra property in the kit.csrf config block to have an "bypass list" of routes which do not check origin.

Something along the lines of the following
```
{
    kit: {
        csrf: {
            checkOrigin: true,
            bypassList: [
                "/api/webhooks/slack"
            ]
        }
    }
}
```

This list could then be checked when handling the csrf check: https://github.com/sveltejs/kit/blob/main/packages/kit/src/runtime/server/respond.js#L63

### Alternatives considered

Disabling the built in csrf protection and writing our own. This could lead to errors during implementation.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Duplicate of #6784.
