### ISSUE TITLE
Modular svelte apps

### ISSUE THREAD

**Issue by jayk09** [sveltejs/kit#1251]
**Is your feature request related to a problem? Please describe.**
Sometimes you need to create modular apps. Basically stand-alone modules (with their own logic, stores, etc.) connectable to main module as a pieces of puzzle. Is something like that possible with SvelteKit?

![Untitled Diagram](https://user-images.githubusercontent.com/20700514/116318977-fd912880-a7b5-11eb-9a70-869044ee8966.jpg)

**Describe alternatives you've considered**
Some time ago I've tried to create something similar with Sapper https://github.com/jayk09/svelte-modular

**How important is this feature to you?**
Handy/Good to have

**Comment by Conduitry** [comment]
No. The parent app needs to be able to see all of the routes ahead of time, and it does this by traversing through the filesystem and creating a manifest. An API would need to be created for packages to expose what lives inside them, and an API would need to be created for wiring up a package of routes/components/etc. at a given subpath. If you have concrete ideas of how those would look, you're welcome to share them, but I don't think planning this is something that any core members would be spending time on in the foreseeable future.

**Comment by benmccann** [comment]
I wrote an RFC awhile back for Sapper that might provide pieces of this https://github.com/sveltejs/rfcs/pull/36. I semi-updated it for SvelteKit, but it's not really something I've been pursuing anymore. Happy to talk about it if you or anyone else would like to try implementing something. But today this is not possible with the current code and is not something that anyone's prioritizing, so I'm going to go ahead and close this to keep the issue tracker clean. Feel free to keep discussing here though

**Comment by jayk09** [comment]
I 100% agree and understand that this topic is not for 1.x. It needs solid concept (should be there some “route-link” files or some config overriding the file-based router? etc etc..) and probably many hours of development. This is just an idea because modular development is something I miss in Sapper and I think it could be possibly handy for bigger apps.. 
Awesome job with SvelteKit anyway! 🚀
