### ISSUE TITLE
Svelte 5: styles from segment remain loaded when navigating to another segment

### ISSUE THREAD

**Issue by iva2k** [sveltejs/kit#12518]
### Describe the bug

1. Setup:

a. File structure:
```
src/routes/(demo)/+layout.svelte
src/routes/(demo)/styles-demo.css
src/routes/(demo)/about/+page.svelte

src/routes/another/+layout.svelte
src/routes/another/styles-another.css
src/routes/another/+page.svelte
```

b. Each +layout.svelte has `import ./styles-*.css` for its local corresponding style file.

c. Run `pnpm dev`, open browser (same problem persists in `pnpm build` and deployed on Vercel)

2. Visit `/about/` route, see `styles-demo.css` and \<style> from `(demo)/about/+page.svelte` are both loaded in \<head>, as expected.

3. Navigate to `/another/` route, `styles-another.css` are added to \<head> as expected, but both `styles-demo.css` and \<style> from `(demo)/about/+page.svelte` remain in \<head>, which is UNEXPECTED.

4. Delete (demo) styles from \<head> in DevTools, when still in `/another/` route, then navigate to `/about/`, and none of the styles from (demo) segment are loaded, which is again UNEXPECTED (hinting that SvelteKit for some reason counts on the styles persisting in \<head>).

5. When loading `/another/` route directly (or full refresh), none of styles from (demo) segment are loaded (as expected).

### Reproduction

I'll work on that...

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 2.19 GB / 15.74 GB
  Binaries:
    Node: 20.10.0 - C:\nodejs\node.EXE
    npm: 10.2.3 - C:\nodejs\npm.CMD
    pnpm: 9.6.0 - C:\dev\svelte\total-app\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.2 => 3.2.2
    @sveltejs/adapter-netlify: ^4.3.1 => 4.3.1
    @sveltejs/adapter-static: ^3.0.2 => 3.0.2
    @sveltejs/adapter-vercel: ^5.4.1 => 5.4.1
    @sveltejs/kit: ^2.5.18 => 2.5.18
    @sveltejs/vite-plugin-svelte: ^3.1.1 => 3.1.1
    svelte: 5.0.0-next.190 => 5.0.0-next.190
    vite: ^5.3.5 => 5.3.5
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The nature of styles used in +layout.svelte require globals (like :root, to style \<html> and \<body>), and 2 different layout styles clash badly, making site appear broken in both segments.

**Comment by Conduitry** [comment]
This is by design. We don't want components to have to count how many instances of them currently exist so that they can unload their CSS when it gets back to zero. I'm also not entirely sure there is a way to do that with how we're delegating the on-demand loading of CSS to Vite.

Please feel free to open GitHub discussions and/or post questions on Discord or elsewhere if you have a particular concrete use case that you can demonstrate and that you're looking for another way to implement. There are several alternatives, but it's impossible to recommend one without additional details.
