### ISSUE TITLE
Allowing Usage of Wildcard Routes in Svelte-kit Adapter Static

### ISSUE THREAD

**Issue by CarsonGH** [sveltejs/kit#12520]
### Describe the problem

**Reasons I want to use svelte/sveltekit:**
- I like using svelte as it efficiently compiles javascript/css/html. 
- I like using svelte-kit (adapter-static) because it efficiently compiles the html layouts and subroutes into separate loaded files. 

**Usage:**
- I use no +page.server.js or +layout.server.js All my usecases are client-side only.

**Problem:**
 I can't compile a [slug] or Wildcard route that uses no loader or Slug and no +page.js. All my javascript usage will be done on the +page.svelte. I belive the problem problem is that the client-side router(of adapter-static) has no support for [slug] or wildcard routes, where all page manipulation would be done on the client-side. 

**To understand why I would want this:** 

I like svelte and javscript for the frontend, I like using Golang for my backend and rather than having 2 servers I would rather have static files for my frontend and a golang API server/file server and I want the advantages of layouts and a route split SPA.

Given the initial page build speed of svelte I would rather just use client-side data loading and loaders/spinners/skeletons. 

This is my prefered way of building apps (coming from react/react-router-dom, vite codesplit SPAs) and so it most likely differs from the standard svelte-kit dev, but I think that this format should be possible with svelte and svelte-kit (adapter-static).
 
 

### Describe the proposed solution

Allow for wildcard routes to be available to use. Where all the routes of a single wildcard point to 1 file. 

### Alternatives considered

Potentially there is another library that I can use with svelte to do efficient route compiling with layouts and efficient html code splitting/compiling that allows for wildcards?

Building a new adapter with support for wildcards

Building a minimized version of the sveltekit compiler that only does compilation of files and then using a custom client-side router on top of it.

### Importance

i cannot use SvelteKit without it

### Additional Information

I have seen this issue come up multiple times in the past 5 years of issues and forum posts, but people do not seem to understand why it is wanted. Hopefully this is a more clean and concise explanation about where a usecase for it would be and why it would be useful for someone over standard svelte-kit or standard adapter-static.

I am also not sure if this is a svelte-kit issue or just the adapter-static?

If someone deeply knows the adapter and sveltekit codebase, I would love to know where the client-side route handler generation code is in either svelte-kit or adapter static, as this issue seems niche enough that I will probably have to build something myself if I want to use this.

**Comment by Conduitry** [comment]
The client-side router of adapter-static does support wildcard routes, and you can create SPAs with SvelteKit. https://kit.svelte.dev/docs/single-page-apps If you have further specific questions, please ask in Discord, GitHub discussions, or StackOverflow.
