### ISSUE TITLE
Long load times with icon packages

### ISSUE THREAD

**Issue by RedCrafter07** [sveltejs/kit#12527]
### Describe the bug

Hello dear SvelteKit maintainers,
I've recently started migrating my codebase from a custom solution using React and Express using Vite to SvelteKit. However, I wanted to use icons from Tabler first and I've seen massive load times on the dev server (I've had load times of 3 seconds and above, multiple times more than 29 seconds, screenshot below; it comes from the reproduction I've linked)

![image](https://github.com/user-attachments/assets/fe4e2f2e-4b9c-44ef-9938-79f9c6af303a)

This happened for both Lucide Icons and Tabler Icons and I don't seem to be the only one with this issue. I haven't seen any issues like that with the React Version of Tabler Icons.

Thanks in advance!

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-bcxpkg?file=src%2Froutes%2F%2Bpage.svelte

I've included two links on the landing page for sites using icons from tabler and lucide. From my testing, the import was already enough to make the page load for a long time. 

### Logs

```Shell
[See screenshot found in the description]
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 15.09 GB / 31.85 GB
  Binaries:
    Node: 22.5.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 9.8.0 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.15.5 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.20 - ~\AppData\Local\pnpm\bun.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.2 => 3.2.2
    @sveltejs/kit: ^2.5.18 => 2.5.18
    @sveltejs/vite-plugin-svelte: ^3.1.1 => 3.1.1
    svelte: ^4.2.18 => 4.2.18
    vite: ^5.3.5 => 5.3.5
```

### Severity

annoyance

### Additional Information

Tried on both node (via pnpm) and bun

**Comment by AdrianGonz97** [comment]
With icon libraries, you should really be using deep imports instead of importing from the index. Here's the related [vite-plugin-svelte docs](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#what-is-going-on-with-vite-and-pre-bundling-dependencies) that covers this.

For `lucide-svelte`, importing the search icon directly will yield significantly faster load times in dev (and faster project builds):
```svelte
<script>
  import SearchIcon from "lucide-svelte/icons/search";
</script>

<SearchIcon />
```

**Comment by RedCrafter07** [comment]
Thanks a lot for that!
I've actually tried doing this, but I haven't seen any difference in load time and I thought it's the same. Seems like the changes didn't carry over or something. I've looked it up and seen someone talking about it being the same thing no matter which way you import it, that's why I opened this issue. 
Thanks again and sorry to bother!
