### ISSUE TITLE
Multilingual SEO Routing

### ISSUE THREAD

**Issue by wladislaw353** [sveltejs/kit#12542]
### Describe the problem

It's very painful to create correct SEO routing with lang prefixes

### Describe the proposed solution

Everything about it you can read in Next.js docs:
https://nextjs.org/docs/pages/building-your-application/routing/internationalization#sub-path-routing

/blog (defautl en lang)
/fr/blog  (fr lang)
/it/blog  (it lang)
The default locale does not have a prefix

Prefix should connect to locale and also prepare link navigation, <a> should generate prefixed automatically

### Importance

would make my life easier

**Comment by benmccann** [comment]
You might be interested in https://inlang.com/m/dxnzrydw/paraglide-sveltekit-i18n/localised-routing. https://github.com/svelte-add/svelte-add/pull/520 would help you set it up automatically for your project

I'm going to close this as it's not clear what part you're running into difficulty with or whether any changes to SvelteKit would be required, but hopefully the above resources help

**Comment by dominikg** [comment]
even without inlang, you can achieve this by using the `reroute` hook.  https://kit.svelte.dev/docs/hooks#universal-hooks-reroute

**Comment by tcurdt** [comment]
> even without inlang, you can achieve this by using the `reroute` hook. https://kit.svelte.dev/docs/hooks#universal-hooks-reroute

Sorry for resurrecting this old issue but - no, you cannot.

How do you get the browser language?

As `reroute` is isomorphic and does not have access to the request headers...
to me it does not seem like it is up to that task.
