### ISSUE TITLE
How to catch 404 Error

### ISSUE THREAD

**Issue by Kapsonfire-DE** [sveltejs/kit#1255]
To catch a 404 Error I created a Falltrough Route, since $error isnt called (at least in dev). This is needed, because 404 leads to a infinete reload till a route is created. But it failed to subfolders. Falltrough Routes does not affect subdirs.

routes/[404].svelte
works for all routes in root dir. When I call a subfolder like http://localhost:3000/Town/Shop I have to create  a routes/Town/[404.svelte] as well.

Now I'm at a point asking me some questions?

Should fallthrough Routes be catched by parent folders as well?
How can I catch the 404 Error and handle it by my own code?

Maybe we should be able to create a custom error 404 page, like $e404.svelte (similiar to $error.svelte)

**Comment by kosayoda** [comment]
> since $error isnt called (at least in dev)

I'm not sure what you mean, it should. The root error page should be `/src/routes/$error.svelte`. The [relevant documentation is here](https://kit.svelte.dev/docs#layouts-error-pages).

**Comment by Kapsonfire-DE** [comment]
$error.svelte isnt used for non existing routes

**Comment by Conduitry** [comment]
It's not clear what this issue is referring to.   First you were talking about behavior in dev mode, and then you were talking about which adapter you were using, which is relevant only in production.

**Comment by Kapsonfire-DE** [comment]
Its true for
npm run dev, 
adapter-static 
adapter-node

$error.svelte isnt used for a non existing route, leading to an infinte reload
![image](https://user-images.githubusercontent.com/67053124/116378968-e2a0d180-a812-11eb-8ce4-edec102a3d73.png)

**Comment by Conduitry** [comment]
Do you have a reproduction for dev or adapter-node?

**Comment by Kapsonfire-DE** [comment]
its fixed for  SvelteKit v1.0.0-next.92 now

best suggest had to with ssr: false in config
