### ISSUE TITLE
F-bombs in source comments

### ISSUE THREAD

**Issue by nathan-rogers** [sveltejs/kit#12557]
### Describe the problem

As the title suggests, f-bombs in comments in source. 

### Describe the proposed solution

Don't commit f-bombs in comments

https://github.com/sveltejs/kit/blob/65931f276ac2102032e3032c864a472eee19b7bb/packages/kit/src/runtime/server/respond.js#L538

https://github.com/sveltejs/kit/blob/65931f276ac2102032e3032c864a472eee19b7bb/packages/migrate/migrations/routes/utils.js#L41

**Comment by Rich-Harris** [comment]
this is my sincerest ever 'close as not planned'
