### ISSUE TITLE
Weird bug when using transitions and a $navigating spinner together

### ISSUE THREAD

**Issue by Nightloewe** [sveltejs/kit#12565]
### Describe the bug

When switching pages, there is a bug happening when the layout contains some code to show a loading spinner on `$navigating != null` and the page we are navigating from contains a transition. The transition then happens, but stops and the DOM is not updated to remove the old page and render the new page.

### Reproduction

https://github.com/Nightloewe/svelteKitBugTransition

### Logs

```Shell
src\routes\+layout.svelte
`<slot />` missing — inner content will not be rendered
```

### System Info

```Shell
Does not work
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
Closing this as I can't reproduce it on latest Svelte.
