### ISSUE TITLE
Export `ActionFailure` to allow `instanceof`

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#12611]
### Describe the problem

I have some shared logic for parsing user input, but it's not that convenient to deal with success/error types.

### Describe the proposed solution

`ActionFailure` is a class, but SvelteKit exposes it as an interface. It would be nice to simply `return fail()` and do `instanceof ActionFailure`:

```ts
function parse(value: T | null) {
	if (!value) {
		return fail(400, { message: 'Too high' })
	}
	// ...
	return value
}

// Action:
const result = parse('test')
if (result instanceof ActionFailure) {
	return result
}
```

### Alternatives considered

- Creating my own class
- Returning a result type like `{ value: T, error: null } | { value: null, error: string }`
- Use the `Error` class `message` as an intermediate, if I only need an error string

### Importance

nice to have

**Comment by eltigerchino** [comment]
Does adding a check such as below solve your issue?
```ts
if ('status' in result && typeof result.status === 'number' && result.status >= 400) {
  return result;
}
```
or simply throw the ActionFailure
```ts
function parse(value: T | null) {
	if (!value) {
		throw fail(400, { message: 'Too high' })
	}
	// ...
	return value
}

// Action:
try {
  const result = parse('test')
} catch (error) {
  if ('status' in error) {
    return result;
  }
}
```

**Comment by probablykasper** [comment]
No, I don't feel like those are any simpler than the workarounds I mentioned. The second is also not type safe so I would highly discourage using that

**Comment by dummdidumm** [comment]
We already have `isError` etc methods exposed from `@sveltejs/kit` - we should just add `isActionFailure` there

**Comment by probablykasper** [comment]
Isn't it just as convenient and more performant to call `instanceof` directly?

**Comment by eltigerchino** [comment]
> We already have `isError` etc methods exposed from `@sveltejs/kit` - we should just add `isActionFailure` there

I don't think we do 🤔 

![isError is not found](https://github.com/user-attachments/assets/caeb0b4b-6ee8-4be3-aa3b-f30ff327c92c)

**Comment by dummdidumm** [comment]
oops it's called `isHttpError`
