### ISSUE TITLE
Setting cookies within getContext?

### ISSUE THREAD

**Issue by leesus** [sveltejs/kit#1261]
Is there any way of setting cookies within `getContext`? I'm trying to `fetch` an internal endpoint to refresh a session, which adds `set-cookie` headers but they're getting dropped. Furthermore, in `load` functions, I can use the passed in `fetch` to call `/my/endpoint` but when `fetch`ing in `getContext` this results in an invalid url error, so I'm guessing in load functions fetch is bound to a different context. 

For now I'm using an ugly interval workaround in the `$layout` to accomplish the refresh but it'd be nicer if I could keep that out of the browser and only do it on demand.

**Comment by Conduitry** [comment]
If you need to adjust the headers that are being returned by SSR'd pages or by endpoints, the `handle` hook is the place to do that.

**Comment by leesus** [comment]
`handle` is called after `getContext` obviously, but I can work around that by attaching the `set-cookie` headers from the `getContext` internal `fetch` on the request as custom headers, and then setting them on the response in `handle`. A bit hacky, but it works.
