### ISSUE TITLE
Browser back button stops working on pages with router disabled

### ISSUE THREAD

**Issue by ghost** [sveltejs/kit#1262]
**Describe the bug**
Browser back button stops working on pages with router disabled.

**To Reproduce**
```javascript
<script context="module">
  export const router = false
</script>
```

**Severity**
Blocking.

**Comment by erwin-k** [comment]
If someone can point me to the code where this problem might come from I'd be happy to fix it.

More detail:
On a page with router disabled, when back button is clicked the url changes but rendering doesn't take place.

**Comment by ignatiusmb** [comment]
I can't reproduce with the latest version using the demo app, tested on both Chromium-based browser and Firefox
