### ISSUE TITLE
VSCode inline breakpoint debug is not working

### ISSUE THREAD

**Issue by ondrejrohon** [sveltejs/kit#12625]
### Describe the bug

breakpoints added using VSCode UI are unbound, execution doesn't stop at them. However inline debugger statement works, but stops in transpiled js instead of my original typescript file: 
![CleanShot 2024-08-28 at 18 41 41@2x](https://github.com/user-attachments/assets/2a218812-a02d-422f-a36e-2cd0557bbc01)
![CleanShot 2024-08-28 at 18 42 01@2x](https://github.com/user-attachments/assets/d9ee316d-84bf-4884-84a6-75832f7ac334)

### Reproduction

- scaffold base sveltekit repo, use typescript
- follow steps from oficial guide https://kit.svelte.dev/docs/debugging#visual-studio-code-launch-via-debug-pane
- in `+layout.server.ts` add an inline breakpoint to line 5, execution should stop there when page is requested

Sample repository: https://github.com/ondrejrohon/sveltekit-debug-vscode

### System Info

```Shell
Visual Studio Code

Version: 1.92.2
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin x64 23.6.0
```

### Severity

annoyance

**Comment by ondrejrohon** [comment]
![CleanShot 2024-08-28 at 21 51 44@2x](https://github.com/user-attachments/assets/a631167c-90ae-43e5-8ae3-0632df4fe1d1)
now I noticed, that there is a warning icon in breakpoints section in debug tab. Question is, why VSCode can't find +layout.server.ts?

**Comment by jasonlyu123** [comment]
It might be a problem with the space in your path. If tried in a directory with space in the path it stopped at the virtual file but when I removed the space it worked as expected. Can you confirm if this is the case? If so you should create an issue in vite. it might be the whitespace in the sourceURL needs to be escaped.

**Comment by ondrejrohon** [comment]
Yes, I confirm that removing the whitespace fixes the issue. Moving this issue to Vite: https://github.com/vitejs/vite/issues/17977

@jasonlyu123 thanks so much for help! :)
