### ISSUE TITLE
removed export from MaybePromise in downloaded package from NPM

### ISSUE THREAD

**Issue by ihr-it-projekt** [sveltejs/kit#12635]
### Describe the bug

If you download svelte kit in version 2.5.25 via NPM the export of MaybePromise in "kit/src/types/index.d.ts" was removed. In version 2.5.24 it is not the case and it is in another file "kit/src/types/private.d.ts" This is a breaking change and also break our application. 

### Reproduction

Upgrade to version 2.5.25 and check MaybePromise definition at "kit/src/types/index.d.ts", export is removed

### System Info

```Shell
The command does not work on my docker environment. 

We are using:

Docker: node:22.7.0-alpine3.20

npmPackages:
    @sveltejs/adapter-auto: ^3.2.4 => 3.2.4 
    @sveltejs/adapter-node: ^5.2.2 => 5.2.2 
    @sveltejs/kit: ^2.5.25 => 2.5.25 
    @sveltejs/vite-plugin-svelte: ^3.1.2 => 3.1.2 
    svelte: ^4.2.19 => 4.2.19 
    vite: ^5.4.2 => 5.4.2
```

### Severity

blocking an upgrade

**Comment by eltigerchino** [comment]
It’s been documented that these types [should not be imported directly](https://kit-svelte-1ihuyg57n-svelte.vercel.app/docs/types#private-types) so it was actually a bug if you could import them. I highly recommend that you copy the utility type into your own project.
```ts
type MaybePromise<T> = T | Promise<T>;
```

**Comment by ihr-it-projekt** [comment]
okay, thx

**Comment by ihr-it-projekt** [comment]
Only thing that i give you to think about, it is a breaking change... you should never do such a change to minor versions... .
