### ISSUE TITLE
CSP types are no longer exported from SvelteKit package from version 2.5.25

### ISSUE THREAD

**Issue by ivenuss** [sveltejs/kit#12636]
In SvelteKit **2.5.25** types `Csp` and `CspDirectives` exported from `packages/kit/src/types/private.d.ts` were no longer exported from `@sveltejs/kit` package.

In version 2.5.24 they can be imported from SvelteKit package and there are no mentions in [2.5.25 changelog](https://github.com/sveltejs/kit/blob/main/packages/kit/CHANGELOG.md#2525).

Just fyi, they're still mentioned in the docs:
- [`Csp`](https://kit.svelte.dev/docs/types#private-types-csp)
- [`CspDirectives`](https://kit.svelte.dev/docs/types#private-types-cspdirectives)

What's the current state? Should they be accessible to import from the package?

**Comment by dummdidumm** [comment]
They're part of the private types; the docs state:

> The following are referenced by the public types documented above, but cannot be imported directly

It was a bug that they were importable. What/where are you using these types for?

**Comment by ivenuss** [comment]
My bad, I missed the state in the docs.

I use it to type the rules object from which I generate CSP header string. I can use something like `Record<string, string[]>`, but I was just curious about this change.

```ts
const rules CspDirectives = {
	'script-src': ['https://example.com'],
	'img-src':  ['https://example.com'],
	...
};
```
