### ISSUE TITLE
Import universal `fetch` to use from `lib`

### ISSUE THREAD

**Issue by korywka** [sveltejs/kit#12644]
### Describe the problem

When we have universal `api.js` lib, that makes `fetch` requests from both: `+page.js` and components, we have notice:

```
`window.fetch`. For best results, use the `fetch` that is passed to your `load` function
```

The problem is that `fetch` is not patched while import from `+page.js`.

To avoid this, I see the only solution is to pass `fetch` from `load` function, something like:

```js
export function fetch_user(user_id, _fetch) {
  let f = _fetch || window.fetch;
  const user = await f(...);
}
```

This solution is looks bulky.

### Describe the proposed solution

Maybe one of:
1. Have ability to import `fetch` from kit, that is automatically patched if is called from `page.js` or `window.fetch` if called from components.
2. SvelteKit patches all `fetch` from imported files.

### Importance

nice to have

**Comment by Conduitry** [comment]
On the server, the behavior of SvelteKit's `fetch` function depends on the incoming request that you're in the process of serving. JavaScript, at the language level, does not yet have a feature that lets us track this context through asynchronous calls. Until such a feature exists, it is impossible to know what incoming request we're serving and thus it is impossible to know how `fetch` should behave.
