### ISSUE TITLE
Allow having client-only `load`

### ISSUE THREAD

**Issue by CNSeniorious000** [sveltejs/kit#12657]
### Describe the problem

I am building a production that have integration with GitHub. Because GitHub has rate limit for its API, I want to make use of our clients' IP to prevent reaching the rate limit.

So, my desired implementation is:

- If the user open a repo through client-side navigation, it will be fetched using the universal `load`.
- If a page is requested with SSR, it will be fetched on the server **with my secret credential**

The problem is, I can't import my credential in the universal load function, I can only use it in a `+page.server.ts`. Having both files will fetch twice, which I don't want.

### Describe the proposed solution

Maybe we can support client-only load function with `+page.client.ts`.

Or maybe we can manually specify it with `export const csr = false` in a `+page.ts`?

### Alternatives considered

For now, I can only implement this by making it a `+server.ts`, and in the universal `load`, fetch that API if during SSR.

The downside is, I lost the type safety when I use `+server.ts`. I can't import the type from `./$types`.

### Importance

nice to have

**Comment by Conduitry** [comment]
What credentials do you want the GitHub API called with if you're running a `load` function in the user's browser?

**Comment by CNSeniorious000** [comment]
If the user is not authorized, I will directly fetch with no credentials because GitHub REST API supports anonymous requests.

**Comment by Conduitry** [comment]
You can use the https://kit.svelte.dev/docs/hooks#server-hooks-handlefetch hook to adjust the requests and inject the authorization when they're made from the server as part of SSR. Does that work for you?

**Comment by CNSeniorious000** [comment]
Wow! Thank you, this really solves this problem. Now I’m not sure if what I mentioned earlier about `+page.client.ts` is still useful. But I noticed that `hooks` can be client-only; why does `load` only have universal and server-only options?

**Comment by david-plugge** [comment]
I do wonder though, dont you get a different result in that case? Could be very confusing for the user.

**Comment by dummdidumm** [comment]
Closing since this can be solved with `handleFetch`.

We don't have client-only load functions because you can pretty easily create them yourself using `import { browser } from '$app/environment'` and then do an if block inside your universal load function. Also, it would be harder to reason about what runs at what time.
