### ISSUE TITLE
Detect `svelte.config.mjs` for Deno

### ISSUE THREAD

**Issue by yetdragon** [sveltejs/kit#12678]
### Describe the problem

SvelteKit currently doesn't officially support `svelte.config.mjs`, and I understand why (as discussed in #12331). However, this becomes a problem when using SvelteKit with Deno because, unlike Node.js, Deno recognizes a file as a module only if it has an `.mjs` extension. Due to this, the Svelte IntelliSense incorrectly shows an error:

```plaintext
Error in svelte.config.js

SyntaxError: Cannot use import statement outside a module (svelte)
```

This issue is similar to one faced by Vite, which was resolved by using `vite.config.mjs`.

Although, Deno is a very niche development runtime for SvelteKit, it would be nice to have support for it in SvelteKit.

### Describe the proposed solution

Make SvelteKit detect `svelte.config.mjs` as a configuration file.

### Importance

nice to have

**Comment by marvinhagemeister** [comment]
An alternative solution would be to check for a `deno.json` or `deno.jsonc` file and treat the project as ESM by default. It's likely that there is some existing code that checks for `package.json` and for `type: "module"` that causes the problem in the first place. Extending that logic for Deno might be the best solution.

**Comment by dummdidumm** [comment]
What's speaking against adding `type: "module"` to the `package.json`? From what I understand it's irrelevant for Deno, but for local tooling it would then know that the file is ESM.

**Comment by yetdragon** [comment]
> What's speaking against adding `type: "module"` to the `package.json`? From what I understand it's irrelevant for Deno, but for local tooling it would then know that the file is ESM.

This fixed the issue. I mistakenly assumed this as Deno-related problem but it seems not. I will close the issue. Sorry for bothering.
