### ISSUE TITLE
Svelte 5 ecosystem CI is failing

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#12686]
### Describe the bug

![Screenshot from 2024-09-18 10-43-48](https://github.com/user-attachments/assets/42437388-0e3e-44db-9b7e-0d92ace1260b)

I don't understand why this is failing though

![Screenshot from 2024-09-18 10-43-18](https://github.com/user-attachments/assets/a234da42-e702-49a3-8b83-2cea5cfcf871)

I should also note that `TemplateNode` is declared in the types twice. Once in the root of the types as a non-exported type and once exported from `'svelte/types/compiler/interfaces'`

### Reproduction

Upgrade `enhanced-img` to the latest Svelte 5 and run `pnpm check`

### System Info

```Shell
`main`
```

### Severity

blocking an upgrade

### Additional Information

Should have been fixed with https://github.com/sveltejs/svelte/issues/12292, but for some reason it seems not to be working

**Comment by dummdidumm** [comment]
There's no real good to make this work other than to keep exposing the old AST types through that never-meant-to-be-public interface. And I'm not sure if that is the right solution. I'd rather switch to redeclaring those types within enhanced image for the time being, and once it has a peer dependency of Svelte 5 minimum you can switch to a) the modern parse output b) use the types exported along with it.

**Comment by benmccann** [comment]
Ah, we can switch to modern parse output. I didn't realize until just the other day that there's a flag for that and it can return two different AST.

It's probably a bit late in the game, but I would have made it `version: 5` so that we don't have `moreModern: true` if we switch to some other implementation in the future.

**Comment by dummdidumm** [comment]
The old AST will probably be gone in 6, and I sure don't hope we already have changes by then, so if we ever have another AST we can just use `modern` again

**Comment by benmccann** [comment]
Oh yeah, good call. Maybe we should deprecate the non-modern one now.

**Comment by dummdidumm** [comment]
I mean, it is deprecated. It's just for a seamless switch that we default to the old one

**Comment by benmccann** [comment]
It's not showing deprecated for me. I upgraded the project to Svelte 5, but don't see any indication in the IDE.

![Screenshot from 2024-10-15 13-13-02](https://github.com/user-attachments/assets/21036994-3088-4f89-837b-23bdf69fd402)
