### ISSUE TITLE
Add a configuration option to disable transforming fetch request into direct function calls

### ISSUE THREAD

**Issue by aloussase** [sveltejs/kit#12692]
### Describe the problem

As described [here](https://kit.svelte.dev/docs/web-standards#fetch-apis), fetch calls made during SSR can be replaced by function calls when the origin is the same as the application. This is good in many cases, but causes problems when the application is running behind a reverse-proxy and you are making an API call to another service proxied under a different path, but the same domain.

For example, I might have the following:

```
example.com/trivia-api -> backend api
example.com/trivia     -> svelte kit application
```

Requests in this case should go through the proxy in order to resolve correctly, instead of being transformed into function calls.

### Describe the proposed solution

A configuration option to turn off this behaviour.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
See #10163/#10170. It was for this precise use case - of being behind a proxy - that I implemented and am using this feature.

**Comment by aloussase** [comment]
But how would that help me? I need to prevent the subRequest in the first place.

**Comment by aloussase** [comment]
You mean something like this?

```javascript
	if (
		event.isSubRequest
	) {
		return event.fetch(new Request(event.request.url, event.request));
	}
```

**Comment by Conduitry** [comment]
Yes. You can even do `return fetch(event.request)` if you want to use the same URL - you don't need to create a new `Request` object.

**Comment by aloussase** [comment]
This doesn't seem to be working correctly. The application is still trying to invoke a function, which is causing my app to run out of memory.

**Comment by aloussase** [comment]
Ended up having to do it like this:

```javascript
if (event.isSubRequest) {
	console.log('subRequest detected, making manual call');
	return await fetch(event.request.url, {
		method: event.request.method,
		headers: event.request.headers,
		credentials: 'include',
		body: await event.request.text()
	});
}
```

Honestly, it doesn't make sense to me why this would be a default with no option to opt out. It's not expected functionality at all.
