### ISSUE TITLE
[Documentation] Clarification of using `load()` with `adapter-static` 

### ISSUE THREAD

**Issue by jmp-12** [sveltejs/kit#12704]
### Describe the problem

As per the [sveltekit docs](https://kit.svelte.dev/docs/load#streaming-with-promises), I have non-essential data that should be loaded after the page is rendered.

Given the following page load function:

> +page.ts
```typescript
export async function load({ fetch }) {
  async function fetchData() {
    const response = await fetch("https://dummyjson.com/quotes/random/?delay=3000");
    return await response.json();
  }

  return {
    quote: await fetchData()
  };
}
```

and the following page:

> +page.svelte
```svelte
<script lang="ts">
  let props = $props();
</script>

<h1 class="text-xl">
  { JSON.stringify(props.data) }
</h1>

<h2 class="text-xl">
  {#await props.data.quote}
    Loading quote...
  {:then quote}
    Quote: {JSON.stringify(quote)}
  {:catch error}
    <p>Error loading quote: {error.message}</p>
  {/await}
</h2>
```

waits for the promise to return before rendering the page using `npm run dev`, `npm run preview`, and `npx http-server ./build`.

Unrelated to my main concern, I'm not sure [why this is the case](https://khromov.se/the-missing-guide-to-understanding-adapter-static-in-sveltekit/#:~:text=you%20cannot%20test%20this%20behavior%20with%20npm%20run%20preview.) with `npx http-server`, I see the data serialized in `index.html` as expected but the page still waits until the fetch request completes before loading the page. I've set `export const prerender = true` in the root `+layout.ts` with no errors in the console during build.

Removing the `await` in the `+page.ts` return object provides the expected behavior. No data is serialized in `index.html` during build and the page loads instantaneously in all the above environments, replacing the "Loading..." text with the data when the fetch resolves.

The [docs ](https://kit.svelte.dev/docs/load#streaming-with-promises)and [blog post](https://svelte.dev/blog/streaming-snapshots-sveltekit#stream-non-essential-data-in-load-functions) seem to suggest this is part of promise streaming; however, those pages mention server load functions almost exclusively. Additionally, there's a note in the docs that says:
> Streaming data will only work when JavaScript is enabled. You should avoid returning promises from a universal load function if the page is server rendered, as these are not streamed — instead, the promise is recreated when the function reruns in the browser.

### Describe the proposed solution

I would like clarification in the docs for returning promises in `load()` function using `adapter-static`. It seems like the approach I'm using is more idiomatic than calling fetch in the the page itself. Plus, I _really_ like the preload on hover behavior.

### Alternatives considered

N/A

### Importance

nice to have

### Additional Information

Relevant package versions:
```
"@sveltejs/kit": "2.5.27"
"svelte": "5.0.0-next.246"
```

**Comment by eltigerchino** [comment]
The load function in `+page.ts` runs on the client, so the `fetch` only occurs when the page is navigated to. Only promises from **server load functions** are streamed to the client.
