### ISSUE TITLE
History, navigating around, streaming promises, data and scroll position issues

### ISSUE THREAD

**Issue by mattiasyoo** [sveltejs/kit#12711]
### Describe the bug

Apologies if this is not a bug, but i am sure i am not the only one experiencing this or having the same questions. I couldn't find a ticket specifically for this.

In the provided project there are 3 endpoints /, /test and /pre. The test and pre endpoints loads data from an API that returns a promise. I want all endpoints to be SSR and to have the choice of skeleton loading. Here are the common cases i would like to be able to do/handle.

Do these steps in order:
1. Go from / to /test, the page will SSR as expected but will be a little slow navigating due to not streaming the response. **Scroll down on the page before going to step 2**
2. Go to /pre, the page will do a "cheap" skeleton loading. This page checks if it's rendered in browser to decide if it should directly render all results or not, for optimal SEO. **Scroll down again before going to step 3**
3. After the items have loaded, click back in the browser. This will run the load function again, hence taking a bunch of time. The scroll position will be restored
4. Click forward/go forward in the history (back to the /pre page). This will do load the data again and displaying the cheap skeleton loading. Scroll position will be lost
5. Reload the current page (/pre). Looking at the network request it correctly renders the page SSR with all the items and then rehydrades on the client but also showing the skeleton loading.

From the above, the following is what i expect to happen. Correct me if i am wrong here, but this would be the default handling of any browser:
* On step 3, i would expect the load function to **NOT** run since i just came from that page. It should be able to instantaneously get me back to my previous state.
* On step 4, i would also expect to be taken right back to the page, no skeleton loading, no load function running. Just instantaneously showing me the previous state. Including scroll position, which is lost currently. The load function should only run again if run invalidate or invalidateAll (at least if going back/forward in the history). But a new entry can do the request again, and is expected from my side
* On step 5, it would be cool if i can somehow skip the rehydration since i already got the full state from the server. I only want the skeleton loading to be visible if navigating between pages on the client. Unless i run invalidate or invalidateAll

Maybe i am missing an essential piece of knowledge. But i think nextjs for example handles at least the "load" part exactly like this. Please let me know if i am handling this all wrong 🙏 

### Reproduction

https://github.com/mattiasyoo/svelte-navigation-load-test
https://stackblitz.com/edit/sveltejs-kit-template-default-fymxtk?file=src%2Froutes%2Fpre%2F%2Bpage.ts

### Logs

```Shell
No relevant logs
```

### System Info

```Shell
Running in WSL 2:
  System:
    OS: Linux 5.15 Ubuntu 24.04 LTS 24.04 LTS (Noble Numbat)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 9.76 GB / 15.46 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 22.8.0 - ~/.asdf/installs/nodejs/22.8.0/bin/node
    npm: 10.8.2 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.5 
    @sveltejs/kit: ^2.0.0 => 2.5.28 
    @sveltejs/vite-plugin-svelte: ^4.0.0-next.6 => 4.0.0-next.7 
    svelte: ^5.0.0-next.1 => 5.0.0-next.258 
    vite: ^5.0.3 => 5.4.7
```

### Severity

annoyance

**Comment by sacrosanctic** [comment]
Regarding step 3 and step 4
> SvelteKit always runs any `load` functions that have been invalidated when you navigate, regardless of the type of navigation.
> https://github.com/sveltejs/kit/issues/9822

**Comment by eltigerchino** [comment]
>On step 3, i would expect the load function to NOT run since i just came from that page. It should be able to instantaneously get me back to my previous state.

I believe the load result is cached but it will re-run with the cached result (which in this case is a promise that only resolves after 4 seconds?)

> On step 4, i would also expect to be taken right back to the page, no skeleton loading, no load function running. Just instantaneously showing me the previous state. Including scroll position, which is lost currently. The load function should only run again if run invalidate or invalidateAll (at least if going back/forward in the history). But a new entry can do the request again, and is expected from my side

If your load function is returning a promise, the load function will replay that promise each time, hence the loading screen and the waiting period. The scroll position is lost because the page is rendered with the loading screen instead of the list so SvelteKit can't restore the scroll position.
