### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by mgk-0** [sveltejs/kit#12756]
### Describe the bug

pnpm i
Your Node version is incompatible with "/@sveltejs/kit/2.6.1(@sveltejs/vite-plugin-svelte@3.1.2)(svelte@4.2.19)(vite@5.4.8)".

Expected version: >=18.13
Got: v18.5.0

npm audit fix --force
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*

### Reproduction

1   {
  1   "name": "web",
  2   "version": "0.0.1",
  3   "private": true,
  4   "scripts": {
  5     "dev": "vite dev",
  6     "build": "vite build",
  7     "preview": "vite preview"
  8   },
  9   "devDependencies": {
 10     "@sveltejs/adapter-auto": "^3.2.5",
 11     "@sveltejs/adapter-node": "^5.2.5",
 12     "@sveltejs/adapter-static": "^3.0.5",
 13     "@sveltejs/adapter-vercel": "^5.4.4",
 14     "@sveltejs/kit": "^2.6.1",
 15     "autoprefixer": "^10.4.20",
 16     "postcss": "^8.4.47",
 17     "postcss-import": "^16.1.0",
 18     "postcss-load-config": "^6.0.1",
 19     "postcss-nesting": "^13.0.0",
 20     "prettier": "^3.3.3",
 21     "prettier-plugin-svelte": "^3.2.7",
 22     "svelte-french-toast": "^1.2.0",
 23     "tailwindcss": "^3.4.13",
 24     "zod": "^3.23.8"
 25   },
 26   "type": "module",
 27   "dependencies": {
 28     "@tailwindcss/nesting": "^0.0.0-insiders.565cd3e",
 29     "animejs": "^3.2.2",
 30     "canvas-confetti": "^1.9.3",
 31     "dotenv": "^16.4.5",
 32     "express": "^4.21.0",
 33     "gsap": "^3.12.5",
 34     "object-to-formdata": "^4.5.1",
 35     "pocketbase": "^0.21.5",
 36     "svelte-hero-icons": "^5.2.0",
 37     "svelte-preprocess": "^6.0.3",
 38     "web": "^0.0.2"
 39   }
 40 }
~

### System Info

```Shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (1) x64 AMD EPYC 7713 64-Core Processor
    Memory: 570.78 MB / 960.70 MB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - /usr/bin/node
    npm: 10.8.3 - ~/.local/bin/npm
    pnpm: 8.11.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.2.5 => 3.2.5
    @sveltejs/adapter-node: ^5.2.5 => 5.2.5
    @sveltejs/adapter-static: ^3.0.5 => 3.0.5
    @sveltejs/adapter-vercel: ^5.4.4 => 5.4.4
    @sveltejs/kit: ^2.6.1 => 2.6.1
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
pnpm must be using a different copy of Node internally than the one you have in your PATH. There are different ways this can happen, depending on how you've installed Node, pnpm, etc.
