### ISSUE TITLE
node version prerequisite

### ISSUE THREAD

**Issue by tuggle24** [sveltejs/kit#1276]
### Problem
I am unable to execute the following command which was listed in the getting started section of documentation site without receiving an error:

`npm init svelte@next my-app`

The error I received is:

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`

I believe this error is _not_ a result from this library. I believe this error is a result from my version of node.js v12 not being able to load a file from this library. I think, and I may be wrong, the particular file for which node.js v12 is not able to load is:

`packages/create-svelte/bin.js`

### My resolution
After searching the issues and the discord, I read a particular [discord message](https://discord.com/channels/457912077277855764/502638785293713408/835210310390120488) which led me to a [github comment](https://github.com/sveltejs/kit/pull/1192#issuecomment-825818185) which was helpful.
And therefore the only way I was able to resolve this issue was to increase my version of node.js to v14.

### Question
My question is the following:
Is there a recommend method for executing the aforementioned command on node.js v12. Or in other words, is there a workaround besides upgrading my node version?

**Comment by babichjacob** [comment]
Yes, using Node 12.17 (maybe 18?) or higher is how you run the command on Node 12.

**Comment by tuggle24** [comment]
Thank you so much for your time and the very prompt reply. 
Great community!
I look forward to continuing my exploration of svelte
