### ISSUE TITLE
Uncaught error on startup: Cannot read env of undefined

### ISSUE THREAD

**Issue by HalfdanJ** [sveltejs/kit#12771]
### Describe the bug

After updating sveltekit from 2.6.2 to 2.6.3, the build version of the app is broken on startup with the following error

```
public.Dvbes-1E.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'env')
    at public.Dvbes-1E.js:1:376
```

The code that is running is 

```
const d = globalThis.__sveltekit_1n0gls.env;
```

I can see that `globalThis.__sveltekit_1n0gls` doesn't exist, but `globalThis.__sveltekit_aqr0w` does. So it seems like somehow the keys gets mixed up in the build. I suspect introduced in https://github.com/sveltejs/kit/pull/12700

### Reproduction

1. Create a new sveltekit project, and make a build
2. Take note of the variable name `globalThis.__sveltekit_*` in `client/_app/immutable/chunks/entry.*.js `
3. Make a change to package.json, for example add a new dependency
4. Make new build, notice that the `entry.*.js` file has not changed filename (same key), but that `globalThis.__sveltekit_*` has changed key, so the file has become mutable

The build is still valid by itself, but if application is served behind a cdn, the old file will be served since filename doesnt change.

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 2.38 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.1.1 - ~/.nvm/versions/node/v20.15.1/bin/pnpm
    bun: 1.1.5 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.90
    Safari: 17.6
  npmPackages:
    @sveltejs/adapter-node: 5.2.5 => 5.2.5 
    @sveltejs/enhanced-img: 0.3.8 => 0.3.8 
    @sveltejs/kit: 2.6.3 => 2.6.3 
    svelte: 4.2.19 => 4.2.19 
    vite: 5.4.8 => 5.4.8
```

### Severity

blocking an upgrade

**Comment by HalfdanJ** [comment]
After further looking into this, it seems like this might be a cache / cdn issue. The file `public.Dvbes-1E.js` is served with the wrong key `1n0gls`, but when i look at the artifact that has been deployed, it contains the right key `1lw3djs`. Is it possible the change in https://github.com/sveltejs/kit/pull/12700 resulted in the key changing, but the filename staying the same, and therefore resulting in a bad cdn file cache?

**Comment by sickl8** [comment]
Encountered the same problem recently, fixed by enabling "Disable Cache" in browser dev tools for each CI build of a commit

**Comment by gwest7** [comment]
For me the issue occurred (only in preview mode) when `kit.version.name` in svelte.config.js was set to `Date.now().toString()` manually.

**Comment by eltigerchino** [comment]
> For me the issue occurred when `kit.version.name` in svelte.config.js was set to `Date.now().toString()` manually.

Can you open a new issue with a minimal reproduction in the form of a repository?

**Comment by ohnv** [comment]
> For me the issue occurred when `kit.version.name` in svelte.config.js was set to `Date.now().toString()` manually.

Just encountered the exact problem as mentioned in the first comment, and this was the issue. I was generating kit.version.name by random GUID + date string at the end. Fixed it by referencing the git commit hash instead.

I also don't think it was related to a CDN, as it affected production builds running locally on my PC.

Interestingly, I deploy 2 apps with a shared codebase (essentially the same package.json, exactly the same same vite config, svelte config etc) and yet it only affected one of them.

🤷‍♂

**Comment by tehnrd** [comment]
This still seems to be an issue and I spent way too much time debugging this issue before searching Github Issues.

I was trying to use a hash but then fell back to `new Date().getTime().toString()` and this seemed to be the issue.

**Comment by teemingc** [comment]
> This still seems to be an issue and I spent way too much time debugging this issue before searching Github Issues.
> 
> I was trying to use a hash but then fell back to `new Date().getTime().toString()` and this seemed to be the issue.

Can you open a new issue with a minimal reproduction?

**Comment by tehnrd** [comment]
I will definitely try, but debugging this has been painfully slow. ~~The issue only happens when deployed to AWS ECS with Cloudflare in front. Doesn't repro with `npm run dev` or after `build` and `preview`~~

Edit: Finally reproduced with local build and preview, will start tearing down the app to create a minimal reproduction. The AWS issue still exists but that is a totally different issue, something with `<pre>` tags causing illegal invocation error.

**Comment by tehnrd** [comment]
This is one of the strangest bugs I have ever come across. Still working on trying to get a small reproducible example (my project is large)...but...

Throws env errror, nanoid() used directy.
```
import 'dotenv/config';
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { nanoid } from 'nanoid';

const config = {	
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter(),
		version: {
			name: process.env.GITHUB_SHA?.substring(0, 8) || 'rand=' + nanoid(8),
			pollInterval: 30000 // 30 seconds
		}
	}
};

export default config;
```

Throws env errror, nanoid() sets var that is passed in.
```
import 'dotenv/config';
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';
import { nanoid } from 'nanoid';

const randomId = nanoid(8);

const config = {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter(),
		version: {
			name: process.env.GITHUB_SHA?.substring(0, 8) || randomId,
			pollInterval: 30000 // 30 seconds
		}
	}
};

export default config;
```

Works fine when name is hardcoded:
```
import 'dotenv/config';
import adapter from '@sveltejs/adapter-node';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

const config = {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter(),
		version: {
			name: process.env.GITHUB_SHA?.substring(0, 8) || 'random',
			pollInterval: 30000 // 30 seconds
		}
	}
};

export default config;
```

**Comment by aviallon** [comment]
For those like me having a similar issue:
<h1>DO CHECK YOUR `NODE_ENV`'s VALUE !!!</h1>
If it is `development` while you do a `npm run build`, here is your mistake.

**Comment by gregg-cbs** [comment]
The problem I am having is I am deploying to my staging environment, so i have a staging env file.

I build the project by doing:
`vite build --mode staging`

This will read my: `.env.staging` file which has `NODE_ENV=production` in it.

When i run the project, i see the GlobalThis error. 

My production deployment works fine when i run: 
`vite build --mode produciton`

**Comment by gregg-cbs** [comment]
# 

> For those like me having a similar issue:
> # DO CHECK YOUR `NODE_ENV`'s VALUE !!!
> If it is `development` while you do a `npm run build`, here is your mistake.

You also need to set the NODE_ENV when running the build, otherwise you get the globalThis issue.

Easiest way to do this is to `npm install --save-dev cross-env` and then update your build command like so:
`cross-env NODE_ENV=production vite build --mode staging`

**Comment by alexangc** [comment]
> For those like me having a similar issue:
> DO CHECK YOUR `NODE_ENV`'s VALUE !!!
> If it is `development` while you do a `npm run build`, here is your mistake.

You saved my life @aviallon, thank you so much! Someone a while back had checked `NODE_ENV: 'test'` in our workflow and my e2e tests were failing on the same error after bumping SvelteKit ... Removing that line fixed the issue 🫡

**Comment by gregg-cbs** [comment]
We randomly started getting this issue today and cant seem to figure out why

**Comment by aviallon** [comment]
@gregg-cbs did you check for any place where you might accidentally be declaring NODE_ENV?

**Comment by gregg-cbs** [comment]
It comes down to how how the --mode and NODE_ENV works in sveltekit. I think on their next iteration they can look at improving it. It turns out I cant use staging as the ENV, some reason that breaks.

So i had to do this (notice that staging deployment uses NODE_ENV=production, because if we put staging there it wouldnt work:
```json
"build:staging": "cross-env NODE_ENV=production vite build --mode staging",
"build:production": "vite build --mode production",
```

**Comment by teemingc** [comment]
Please continue the discussion in https://github.com/sveltejs/kit/issues/15632 .
