### ISSUE TITLE
Previous user data stays on +error.svelte page

### ISSUE THREAD

**Issue by YVeselovskyi** [sveltejs/kit#12808]
### Describe the bug

If I create non existent link, which will lead me to +error.svelte page, visit it and send the link to another user, he will see my profile there.

```
<script>
	import { setContext } from 'svelte';
	import { writable } from 'svelte/store';

	/** @type {import('./$types').LayoutData} */
	export let data;

	// Create a store and update it when necessary...
	const user = writable();
	$: user.set(data.user);

	// ...and add it to the context for child components to access
	setContext('user', user);
</script>
```

that's how I'm setting user in context, but he is still able to see my info, when I visit that page.

```
  const response = await resolve(event);

  response.headers.set('Cache-Control', 'no-store');
  response.headers.set('Vary', 'Cookie');

  return response;
```

only this in hooks.server.js can fix it, maybe there is another way to handle this issue?
or it's cloudflare caching issue?

### Reproduction

It happens only in my production environment, so I can't post a link.

### System Info

```Shell
System:
  OS: macOS 15.0.1
CPU: (8) arm64 Apple M1 Pro
Memory: 97.36 MB / 16.00 GB
Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
Yarn: 1.22.19 - ~/.yarn/bin/yarn
npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
Browsers:
  Chrome: 129.0.6668.91
Safari: 18.0.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
This sounds like Cloudflare caching, yes. To confirm this, you could try clearing the cache in Cloudflare and seeing what happens, or you could add debug logging to your application and see whether the requests are getting through to it.
