### ISSUE TITLE
`<enhanced:img>` goes nutty when you duplicate images

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#12802]
### Describe the bug

If you do this...

```svelte
<enhanced:img src="./foo.png" />
<enhanced:img src="./foo.png" />
```

...stuff breaks, because it tries to import the same asset twice.

### Reproduction

later...

### System Info

```Shell
next
```

### Severity

annoyance

**Comment by benmccann** [comment]
this has been fixed
