### ISSUE TITLE
`bunx --bun vite preview` hangs on request

### ISSUE THREAD

**Issue by vjpr** [sveltejs/kit#12807]
### Describe the bug

I've traced the issue to here:

https://github.com/sveltejs/kit/blob/96642d234d1f5e961e919da725a1f6188e8aba2c/packages/kit/src/exports/node/index.js#L183-L200

In Bun, `done` never becomes `true`.

In Node, it does and everything works fine.

If I add the following logs:

```
for (;;) {
				let { done, value } = await reader.read();

				console.log({done})
				if (done) break;

				console.log(res.write(value))
				if (!res.write(value)) {
					res.once('drain', next);
					return;
				}

			}
			res.end();
```

_Node_

```
{ done: false }
true
{ done: true }
```

_Bun_

```
{ done: false }
true
```

### Reproduction

Bun

```
bunx --bun vite preview
```

Node

```
vite preview
```

### System Info

```Shell
System:
    OS: macOS 15.0.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 72.44 MB / 128.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.8.0 - ~/Library/pnpm/node
    npm: 10.8.2 - ~/Library/pnpm/npm
    pnpm: 9.12.1 - ~/Library/pnpm/pnpm
    bun: 1.1.30 - ~/.bun/bin/bun
    Watchman: 2024.08.19.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 18.0.1
```

### Severity

blocking all usage of SvelteKit

**Comment by vjpr** [comment]
Related: https://github.com/oven-sh/bun/issues/6638

**Comment by vjpr** [comment]
https://nodejs.org/api/http.html#requestwritechunk-encoding-callback

> The callback argument is optional and will be called when this chunk of data is flushed, but only if the chunk is non-empty.

> Returns true if the entire data was flushed successfully to the kernel buffer. Returns false if all or part of the data was queued in user memory. 'drain' will be emitted when the buffer is free again.

> When write function is called with empty string or buffer, it does nothing and waits for more input.

**Comment by eltigerchino** [comment]
Sorry, but I'll be closing this issue because there isn't anything we should do on Kit's side of things. I think it's a very well investigated issue but better belongs in the Bun issue tracker.
