### ISSUE TITLE
Form Validations not working when form is not in the page

### ISSUE THREAD

**Issue by helloalbin** [sveltejs/kit#12819]
### Describe the bug

I have a form which is defined inside a component. If I include the component in the page, the form validations from the form actions of +page.server.ts is not updating the form and hence not accessible in the page. This works fine if the <form> is directly inside the page.

### Reproduction

https://github.com/helloalbin/kit_form

Access http://localhost:5173/cat . Click on show contact form and submit the form. The errors from +page.server.ts is not accessible using form variable.

However if the page <form> is directly inside the page it works. http://localhost:5173/same_comp 

### System Info

```Shell
"svelte": "^5.0.0-next.1",
"@sveltejs/kit": "^2.0.0",
```

### Severity

blocking an upgrade

**Comment by eltigerchino** [comment]
You'll need to access the `form` variable either through the `$page` store or by passing it from the page props into the component. Currently, your form component is expecting the form variable through props, but no props are being passed to the component.

> the action can respond with data that will be available through the `form `property on the corresponding page and through `$page.form` app-wide until the next update.

https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action
