### ISSUE TITLE
weird behaviour with json imports

### ISSUE THREAD

**Issue by sukeshpabolu** [sveltejs/kit#12892]
### Describe the bug

If a json is imported with a name which is as same as a variable name used in a function and a proxy is created from the json, It is somehow being overwritten. If I use the structured clone of the json while creating the proxy the issue doesn't occur.

### Reproduction

[stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-ugyhvx?file=src%2Froutes%2F%2Bpage.svelte)

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.3.1 => 3.3.1 
    @sveltejs/kit: ^2.7.3 => 2.7.3 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.0 
    svelte: ^5.1.3 => 5.1.3 
    vite: ^5.4.10 => 5.4.10
```

### Severity

serious, but I can work around it

**Comment by eltigerchino** [comment]
I'll be closing this because I'm not sure what SvelteKit can do to help in this situation. It seems to be how JavaScript works.

**Comment by SukeshP1995** [comment]
How can you close this? Have you even looked at the code. If a file imported at 2 place and one file creates a proxy out of it and other doesn't, the data in the file is overwritten

**Comment by eltigerchino** [comment]
> How can you close this? Have you even looked at the code. If a file imported at 2 place and one file creates a proxy out of it and other doesn't, the data in the file is overwritten

Unfortunately, it's not something SvelteKit can fix because SvelteKit doesn't handle the JSON import. Either Vite or Node does this.

**Comment by sukeshpabolu** [comment]
Oh, sorry I thought vite or sveltekit should handle this during dev or bundle time
