### ISSUE TITLE
`TypeError: Failed to fetch` from `navigate`

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#12899]
### Describe the bug

Captured in Sentry. I'm not sure what the cause is - is this expected behaviour?

<img width="839" alt="image" src="https://github.com/user-attachments/assets/6265936a-4fd4-470d-9394-e494d41b7038">

### Reproduction

Not sure how to reproduce

### System Info

```Shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 73.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 9.7.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 130.1.71.114
    Chrome: 130.0.6723.70
    Edge: 130.0.2849.56
    Safari: 18.0.1
```

### Severity

annoyance

### Additional Information

We're using the latest `Svelte 5` and `SvelteKit 2` versions

**Comment by MathiasWP** [comment]
This one also just popped in:

<img width="1345" alt="image" src="https://github.com/user-attachments/assets/60716234-89d8-4555-b0f6-5a64279b3562">

**Comment by Conduitry** [comment]
We can't do anything without a reproduction, and screenshots of stacktraces in Sentry are not a reproduction. There are zillions of things that could cause network errors.

FWIW, at work I stopped using Sentry for capturing client-side errors because of the sheer amount of noise cause by network hiccups or god knows what that is completely beyond my control.

**Comment by MathiasWP** [comment]
> We can't do anything without a reproduction, and screenshots of stacktraces in Sentry are not a reproduction. There are zillions of things that could cause network errors.
> 
> FWIW, at work I stopped using Sentry for capturing client-side errors because of the sheer amount of noise cause by network hiccups or god knows what that is completely beyond my control.

Aight, so this is a network error - good to know! 

Also I'm, curious, what are you using at work for client-side errors?

**Comment by MathiasWP** [comment]
@Conduitry, just want to add this in case it should be open.

We have never received this error until 3 days ago:

<img width="343" alt="image" src="https://github.com/user-attachments/assets/5a1a759d-8b3f-4a30-8e05-b790181d6e94">

And the operating system is Linux, which may indicate that this is happening on a server?

<img width="940" alt="image" src="https://github.com/user-attachments/assets/2a3ffad8-07da-4dca-9325-cb26bc26c2ee">
