### ISSUE TITLE
empty context obj for load in $layout.svelte

### ISSUE THREAD

**Issue by Kapsonfire-DE** [sveltejs/kit#1289]
I'm exporting a load function in $layout.svelte
Somehow, context is always an empty object - but the getContext function inside hooks/index.ts is called fine
The session variable works as expected.

hooks/index.ts

```javascript
import languageParser from 'accept-language-parser';
export async function getContext({ headers }) {
    let lang = languageParser.parse(headers["accept-language"]);
    return {
        lang
    };
}

export function getSession({ context }) {
    return context
}
```

routes/$layout.svelte
```html
<script lang="ts" context="module">
 
    export async function load({page, fetch, session, context}) {
        console.log(context, session);
        return {
            status: 200
        }
    }
</script>
```

  SvelteKit v1.0.0-next.94

**Comment by GrygrFlzr** [comment]
The `context` object that is returned as a result of `getContext` is only available on server-side environments:
- endpoint handlers like `get`, `post`, etc.
- `getSession` inside `hooks.js`

The `context` object that is received by `load` is used to pass data down from a layout to subsequent `load` functions in pages. For example:

```svelte
<!-- src/routes/$layout.svelte -->
<script context="module">
  export async function load() {
    return {
      context: { name: 'hello' },
    };
  }
</script>
<slot />
```
```svelte
<!-- src/routes/index.svelte -->
<script context="module">
  export async function load({ context }) {
    console.log(context); // { name: 'hello' }
    return {};
  }
</script>
<slot />
```

**Comment by GrygrFlzr** [comment]
Closing, would recommend subscribing to #984 instead.
