### ISSUE TITLE
Can't install Kit with Node 21

### ISSUE THREAD

**Issue by khromov** [sveltejs/kit#12893]
### Describe the bug

We've had [several people in Discord](https://discord.com/channels/457912077277855764/1300197852756054026/1300197852756054026) pointing out that you can't create a SvelteKit project on Node 21, since `vite-plugin-svelte` only allows Node 20 and 21 as compatible engines (you get EBADENGINE).

### Reproduction

-

### Logs

```Shell
-
```

### System Info

```Shell
-
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Node 21 is EOL as of earlier this year. We shouldn't be encouraging people to use it.
