### ISSUE TITLE
enhanced-img not building <enhanced:img />

### ISSUE THREAD

**Issue by Lythium4848** [sveltejs/kit#12939]
### Describe the bug

The `@sveltejs/enhanced-img` package seems to not be building the `<enhanced:img />` tags into what they are supposed to be built into. Instead they are just staying as the `<enhanced:img />` tags after build resulting in the images not being shown. The package is working when using in a css url (like `url($lib/my-image.png?enhanced`).

### Reproduction

https://www.sveltelab.dev/2z7ull0kekwjx7z

Install latest `@sveltejs/enhanced-img`
Try and use the `<enhanced:img />` tag
No image shown, <enhanced:img /> not built into <picture> ... </picture>

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 14.89 GB / 31.91 GB
  Binaries:
    Node: 22.5.1 - ~\AppData\Local\fnm_multishells\15400_1730598094686\node.EXE
    npm: 10.8.2 - ~\AppData\Local\fnm_multishells\15400_1730598094686\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\fnm_multishells\15400_1730598094686\pnpm.CMD
    bun: 1.1.21 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @sveltejs/adapter-node: ^5.2.9 => 5.2.9 
    @sveltejs/enhanced-img: ^0.4.0 => 0.4.0 
    @sveltejs/kit: ^2.7.4 => 2.7.4 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.0 
    svelte: ^5.1.9 => 5.1.9 
    vite: ^5.4.10 => 5.4.10
```

### Severity

serious, but I can work around it

**Comment by Rishab49** [comment]
The culprit is the line below, as provided reproduction is using svelte5

https://github.com/sveltejs/kit/blob/c4b76d09c9f5982f024d5422aafea4135cc8ad15/packages/enhanced-img/src/preprocessor.js#L179

one solution could be changing the above line to something like this:
```js
`<script ${parseInt(VERSION) >= 4  ? 'context="module"' : 'module'}>${text}</script>\n`
```

**Comment by Kapsonfire-DE** [comment]
im not sure if you are correct here @Rishab49 

<script module> is totally correct for svelte5

**Comment by Lythium4848** [comment]
Downgrading to version 0.3.10 looks to be working correctly

**Comment by benmccann** [comment]
Please try with 0.4.1
