### ISSUE TITLE
derived store from `page.data` triggers unnecessary updates on navigation

### ISSUE THREAD

**Issue by TorstenDittmann** [sveltejs/kit#12948]
### Describe the bug

When having a derived store on the `$page.data` store, every navigation triggers an unnecessary update and therefore all `subscriptions`. This also only happens with objects, primitive values do not have this issue.

Also this issue is happening for us on Svelte 4 - but I was able to recreate it in Svelte 5 too.

### Reproduction

Having a `+layout.js` like this:
```js
export const load = async () => {
  return {
    name: { a: 1, b: 2 },
  };
};
```
and having a derived store like this:
```js
import { page } from '$app/stores';
import { derived } from 'svelte/store';

export const name = derived(page, ($page) => $page.data?.name);
```

triggers an update to any `name.subscribe` when navigating.

Here is a Stackblitz and you can see `console.log`s on every navigation => https://stackblitz.com/edit/sveltejs-kit-template-default-bse1so?file=src%2Froutes%2F%2Blayout.svelte 

### System Info

```Shell
System:
    OS: macOS 15.0.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 84.19 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
    bun: 1.1.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 130.0.6723.92
    Safari: 18.0.1
  npmPackages:
    @sveltejs/adapter-static: ^3.0.6 => 3.0.6
    @sveltejs/kit: ^2.7.4 => 2.7.4
    @sveltejs/vite-plugin-svelte: ^3.1.2 => 3.1.2
    svelte: ^4.2.19 => 4.2.19
    vite: ^5.4.10 => 5.4.10
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
This is expected, given how stores invalidate. The whole `$page` value is invalidated - it's not fine-grained.

Sometime in the near-ish future we will design and add fine-grained reactive Svelte 5 objects to expose the same information as is currently exposed in the stores in SvelteKit.

**Comment by TorstenDittmann** [comment]
> This is expected, given how stores invalidate. The whole `$page` value is invalidated - it's not fine-grained.
> 
> Sometime in the near-ish future we will design and add fine-grained reactive Svelte 5 objects to expose the same information as is currently exposed in the stores in SvelteKit.

Okay, but it has worked at some point for us 👍🏻 

I was expecting the whole page value to be invalidated too, however if in this case the value would be a primitive like a string, it would not be invalidated. That's why I was a bit confused seeing this.

```
export const name = derived(page, ($page) => $page.data?.name);
// ...
export const load = async () => {
  return {
    name: "Conduitry"
  };
};
```

It would work as expected. iirc wasn't there a protection function called something like `safe_not_equal` in place to prevent updates when the values equal?
