### ISSUE TITLE
Top level code only run in hooks.server.ts in "npm run preview" and not it "npm run dev"

### ISSUE THREAD

**Issue by yousufiqbal** [sveltejs/kit#12943]
### Describe the bug

I dont know if this is a feature of sveltekit or something else. In the given repo, inside hooks.server.ts file. The `console.log('I print only in npm run preview')` only runs in "npm run preview". It doesnt run in "npm run dev". Please clarfiy if this is some feature or a bug. Thanks

### Reproduction

https://github.com/yousufiqbal/sveltekit-hooks-issue

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i3-7100T 
CPU @ 3.40GHz
    Memory: 2.45 GB / 7.87 GB
  Binaries:
    Node: 20.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - ~\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355      
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/kit: ^2.0.0 => 2.7.4 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 
4.0.0 
    svelte: ^5.0.0 => 5.1.9
    vite: ^5.0.3 => 5.4.10
```

### Severity

annoyance

### Additional Information
Direct link to hooks file https://github.com/yousufiqbal/sveltekit-hooks-issue/blob/main/src/hooks.server.ts

_No response_

**Comment by Conduitry** [comment]
In dev, top-level code in the hooks file does run, but not until the first request comes in. This difference between dev and prod is known, but isn't something that it's particularly high priority to address, if at all. There's an old issue #927 with a lot of comments, which is about requesting a way to be more explicit about code to run on startup.
