### ISSUE TITLE
Empty comments in html 

### ISSUE THREAD

**Issue by hexahigh** [sveltejs/kit#12974]
### Describe the bug

When running the dev server or building, the output html contains empty comments.
![image](https://github.com/user-attachments/assets/4944511f-6e58-4c62-bc64-8a8399f6b5aa)
I remember that in previous versions (4 and earlier) there would be a comment showing the name of the component file.
I'm not entirely sure if this issue belongs in the svelte repo or the sveltekit repo but I'm putting it here as it seems to be related to the rendering. 

### Reproduction

https://github.com/hexahigh/sveltekit-empty-comments-reprod

### System Info

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 7 7800X3D 8-Core Processor
    Memory: 20.65 GB / 31.03 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 21.5.0 - ~/.local/share/pnpm/node
    npm: 10.2.4 - ~/.local/share/pnpm/npm
    pnpm: 9.1.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 130.0.6723.116
  npmPackages:
    @sveltejs/adapter-auto: ^3.3.1 => 3.3.1 
    @sveltejs/kit: ^2.7.3 => 2.7.3 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.0 
    svelte: ^5.1.3 => 5.1.3 
    vite: ^5.4.10 => 5.4.10
```

### Severity

annoyance

### Additional Information

1. I tested this on Chrome and Firefox.
2. This bug first occurred when I upgraded my site to Svelte 5.

**Comment by Conduitry** [comment]
This is expected. See https://github.com/sveltejs/svelte/issues/14099 for more information.

**Comment by JohnScience** [comment]
@Conduitry How to re-enable the comments showing the name of the component file.

**Comment by Conduitry** [comment]
There's an issue for that - https://github.com/sveltejs/svelte/issues/14952 - but I don't think anyone has spent the time to figure out what exactly broke about this in v5.
