### ISSUE TITLE
docs: Remove `lucia` (deprecated) from SvelteKit Auth guide

### ISSUE THREAD

**Issue by andrewschmidgit** [sveltejs/kit#12990]
### Describe the problem

Lucia is being [deprecated](https://github.com/lucia-auth/lucia/discussions/1714) March 2025, and probably shouldn't be recommended in the docs as anything other than a reference

### Describe the proposed solution

I realize this is still in preview, but I don't think [AuthJS](https://authjs.dev/reference/sveltekit) is going away anytime soon. 

### Importance

would make my life easier

**Comment by andrewschmidgit** [comment]
I did not read the docs close enough. I had just heard about lucia and saw it in the docs. Ignore my dumb

**Comment by idc77** [comment]
What does your comment mean? It's not going away? Why "dumb"?

**Comment by andrewschmidgit** [comment]
I opened the issue dumbly by not reading everything clearly

From [https://lucia-auth.com/](https://lucia-auth.com/):
> Lucia is now a learning resource on implementing auth from scratch. See the [announcement](https://github.com/lucia-auth/lucia/discussions/1714) for details and migration path.

From [https://svelte.dev/docs/kit/auth#Guides](https://svelte.dev/docs/kit/auth#Guides):
> [Lucia](https://lucia-next.pages.dev/) is a reference for session-based web app auth...

I skimmed the Auth page of the Svelte docs, saw `Lucia`, and had just heard that Lucia is no longer a library, but rather a reference

I hastily opened the issue

I then read the docs closer:
> [Lucia](https://lucia-next.pages.dev/) is a >**reference**< for session-based web app auth...

And closed the issue
