### ISSUE TITLE
superfluous build warning with transitions and easing

### ISSUE THREAD

**Issue by kamholz** [sveltejs/kit#1299]
**Describe the bug**
I have several components with code like:
```
<script>
  import { fly } from 'svelte/transition';
  import { sineIn, sineOut } from 'svelte/easing';
</script>

<tr in:fly|local={{ easing: sineIn }} out:fly|local={{ easing: sineOut }}>
...
</tr>
```

When I do `npm run build`, I get the following superfluous warning:
```
transforming...
✓ 126 modules transformed.
'fade', 'fly' and 'slide' are imported from external module 'svelte/transition' but never used
'sineIn' and 'sineOut' are imported from external module 'svelte/easing' but never used
```

I don't know if this is an issue with Vite, Svelte, or SvelteKit. I haven't seen it reported for Vite or Svelte, so I'm assuming it only happens with SvelteKit.

**Expected behavior**
No superfluous warnings.

**Severity**
Minor. Everything builds fine. It would just be nice to make the warnings accurate.

**Comment by mhatvan** [comment]
I can confirm this, experiencing the same.

**Comment by aaronkai** [comment]
Same thing for me.

**Comment by ignatiusmb** [comment]
I can't reproduce with the latest version, no superfluous warning are being logged in the console anymore. If this still occurs, please provide a complete and minimal reproducible example we can clone.

**Comment by kamholz** [comment]
Yes, I believe this was fixed in Vite at some point.
