### ISSUE TITLE
Page <title> Appears as the Last Element in <head> in Svelte 5

### ISSUE THREAD

**Issue by harshascode** [sveltejs/kit#13006]
### Describe the bug

After updating a SvelteKit project to Svelte 5, the page title appears last in the <head> section. The order of elements shows the title after the og tags, description, and other metadata. You can observe this by visiting any Svelte 5 project, such as [svelte.dev](https://svelte.dev/).
![Screenshot 2024-11-15 170514](https://github.com/user-attachments/assets/1675917e-6e53-4b79-9eba-73585b9eed01)

### Reproduction

Visit any Svelte 5 Deployed site. ex: svelte.dev and view the page source code.

### System Info

```Shell
noun
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Who is this annoying?

**Comment by harshascode** [comment]
👍
