### ISSUE TITLE
Components that require an external top level await during compilation fail in svelte 5

### ISSUE THREAD

**Issue by dsgallups** [sveltejs/kit#13015]
## Describe the bug

On import of any function binding from WebAssembly will return an error not found when running a vite development build, due to usage of `vite-plugin-top-level-await`. This is a Sveltekit issue that appears upon usage of Svelte 5 over Svelte 4.

Discovered behavior using the cloudflare adapter. `svelte-bug-wasm-2` reproduces the behavior with the auto adapter.

Uses: `wasm-pack: 0.13.1`, `vite-plugin-wasm: 3.3.0` for wasm bindings

## Reproduction

~~https://github.com/dsgallups/svelte-bug-wasm~~
https://github.com/dsgallups/svelte-bug-wasm-2

Branch with working compilation on svelte 4: https://github.com/dsgallups/svelte-bug-wasm-2/tree/svelte-4-working

## Logs

```Shell
TypeError: Pyramid_0 is not a function
    at Root (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/chunks/internal.js:510:5)
    at render (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/chunks/index3.js:812:3)
    at Function._render [as render] (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/chunks/internal.js:472:20)
    at render_response (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/index.js:1238:34)
    at async render_page (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/index.js:2066:12)
    at async resolve2 (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/index.js:2700:24)
    at async respond (file:///Users/danielgallups/repo/svelte-bug-wasm-2/.svelte-kit/output/server/index.js:2592:22)
    at async visit (file:///Users/danielgallups/repo/svelte-bug-wasm-2/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:208:20)

node:internal/event_target:1094
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /
To suppress or handle this error, implement `handleHttpError` in https://svelte.dev/docs/kit/configuration#prerender
    at file:///Users/danielgallups/repo/svelte-bug-wasm-2/node_modules/@sveltejs/kit/src/core/config/options.js:203:13
    at file:///Users/danielgallups/repo/svelte-bug-wasm-2/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:71:25
    at save (file:///Users/danielgallups/repo/svelte-bug-wasm-2/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:419:4)
    at visit (file:///Users/danielgallups/repo/svelte-bug-wasm-2/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:242:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)
    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)

Node.js v20.15.0
```

## System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 22.27 GB / 48.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
  Browsers:
    Chrome: 130.0.6723.117
    Chrome Canary: 133.0.6839.1
    Safari: 18.1
  npmPackages:
    svelte: 5.2 => 5.2.0
    vite: ^5.4.10 => 5.4.11
```

## Severity

blocking an upgrade

## Additional Information

In `.svelte-kit/output/server/entries/pages/_layout.svelte.js` the following code is generated in svelte 4:

```javascript
import { c as create_ssr_component } from "../../chunks/ssr.js";
import { e as escape } from "../../chunks/escape.js";
let Layout;
let __tla = (async () => {
   ...vite-plugin-wasm instantiation code...
 Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
    let mountState = "mounting";
    return `<div class="app"><main><div>${escape(mountState)}</div> <div>${slots.default ? slots.default({}) : ``}</div></main></div>`;
  });
})();
export {
  __tla,
  Layout as default
};
```

Now, svelte-5 will generate:

```javascript
import { e as escape_html } from "../../chunks/escaping.js";
import { S as pop, Q as push } from "../../chunks/index.js";
let _layout;
let __tla = (async () => {
   ...vite-plugin-wasm instantiation code...
  _layout = function($$payload, $$props) {
    push();
    let { children } = $$props;
    let mountState = "mounting";
    $$payload.out += `<div class="app"><main><div>${escape_html(mountState)}</div> <div>`;
    children($$payload);
    $$payload.out += `<!----></div></main></div>`;
    pop();
  };
})();
export {
  __tla,
  _layout as default
};
```

The issue is that `__tla` doesn't complete before `_layout` is called by `render`:

`_layout` is initially undefined. If called before `__tla` resolves, `component` (`_layout`) in `0.js` will return undefined leading all the way to `Pyramid[0]` being the component constructor for the layout page to be undefined. This is why it would *sometimes* work, because something would eventually process the topLevelAwait.

### Why does this work in Svelte 4?

in `internal.js` the Root function will validate that `constructors[0]` and `constructors[1]` have been properly instantiated using `validate_component` in `ssr.js`. Svelte 4 has a fallback for this, so things work:
```javascript
$$rendered = `  ${constructors[1] ? `${validate_component(constructors[0] || missing_component, "svelte:component").$$render(
      $$result,
      { data: data_0, this: components[0] },
      {
        this: ($$value) => {
          components[0] = $$value;
          $$settled = false;
        }
      },
      {
        default: () => {
          return `${validate_component(constructors[1] || missing_component, "svelte:component").$$render(
            $$result,
            { data: data_1, form, this: components[1] },
            {
              this: ($$value) => {
                components[1] = $$value;
                $$settled = false;
              }
            },
            {}
          )}`;
        }
      }
    )}` : `${validate_component(constructors[0] || missing_component, "svelte:component").$$render(
      $$result,
      { data: data_0, form, this: components[0] },
      {
        this: ($$value) => {
          components[0] = $$value;
          $$settled = false;
        }
      },
      {}
    )}`} ${``}`;
  } while (!$$settled);
```

Compared to the `Root` function from root.svelte in `.svelte-kit/output/server/chunks/internal.js:~516`:

```svelte
  const Pyramid_1 = constructors[1];
  if (constructors[1]) {
    $$payload.out += "<!--[-->";
    const Pyramid_0 = constructors[0];  // <-- There is no guarantee that constructors[0] exists.
    $$payload.out += `<!---->`;
    Pyramid_0($$payload, {
      data: data_0,
      form,
      children: ($$payload2) => {
        $$payload2.out += `<!---->`;
        Pyramid_1($$payload2, { data: data_1, form });
        $$payload2.out += `<!---->`;
      },
      $$slots: { default: true }
    });
    $$payload.out += `<!---->`;
  } else {
    $$payload.out += "<!--[!-->";
    const Pyramid_0 = constructors[0];
    $$payload.out += `<!---->`;
    Pyramid_0($$payload, { data: data_0, form });
    $$payload.out += `<!---->`;
  }
```

Since these constructors are not validated in Svelte 5, that leads to the error.

This is why I believe wasm won't work: Top level await does not set the component before the component's render() function is called.

### Why is this Important?

Because the [ES Module Integration proposal](https://github.com/WebAssembly/esm-integration) for WASM is not supported, the [vite docs](https://vite.dev/guide/features.html#webassembly) recommend usage of the `vite-plugin-wasm` dep. Since Svelte cannot properly compile components that utilize this plugin, the `wasm-pack` toolchain becomes ~~effectively useless~~ more difficult to use. ~~Examples of a workaround are not available~~ A half-workaround is to use a dynamic import. There are some cases, however, where wasm memory should be loaded alongside the constructor outside of an onMount callback.

### Idea for solution

I'd like to readd the `validate_component`/fallback functionality back to sveltekit in some form. However, I have no clue why it was removed. My hypothesis is that the simplest approach is to adjust `write_root` with an `if` check on `constructor[0]`, but not sure what a reasonable fallback would be. Some guidance on this would be super helpful!

**Comment by dsgallups** [comment]
It may be an underlying issue with `vite-plugin-wasm` not exposed in Svelte 4. Svelte 4 would, on occasion, emit a `installHooks.js was not found` error on the first instantiation in dev builds, yet was able to instantiate web assembly properly on proper builds.

**Comment by dsgallups** [comment]
This is quite an unusual bug. I noticed that in the output you will find

```
<!-- This file is generated by @sveltejs/kit — do not edit it! -->
<svelte:options runes={true} />
<script>
	import { setContext, onMount, tick } from 'svelte';
	import { browser } from '$app/environment';

	// stores
...
```

I have provided this output to the example.

On occasion, stripping the import entirely, leading to an error. I made some change that leads to the build failing on first page visit, and then fine afterwards. Really scratching my head on this one.

**Comment by eltigerchino** [comment]
I'm not able to reproduce the same error logs when running build on the reproduction. Can you provide another minimal reproduction and a set of steps to run?
These are the build logs I get:
```sh
x Build failed in 1.16s
error during build:
[vite:load-fallback] Could not load /home/chewteeming/github/svelte-bug-wasm-2/src/lib/wasm/pkg/frontend_wasm (imported by src/routes/+layout.svelte): ENOENT: no such file or directory, open '/home/chewteeming/github/svelte-bug-wasm-2/src/lib/wasm/pkg/frontend_wasm'
Error: Could not load /home/chewteeming/github/svelte-bug-wasm-2/src/lib/wasm/pkg/frontend_wasm (imported by src/routes/+layout.svelte): ENOENT: no such file or directory, open '/home/chewteeming/github/svelte-bug-wasm-2/src/lib/wasm/pkg/frontend_wasm'
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by dsgallups** [comment]
> I'm not able to reproduce the same error logs when running build on the reproduction. Can you provide another minimal reproduction and a set of steps to run?

Absolutely! Apologies, had not added the README.md from the first example. For compilation, you'll want to install rust, but what I'll do is upload the wasm pkg file for this

**Comment by dsgallups** [comment]
Alright, should be available now. Thank you!

**Comment by dsgallups** [comment]
FOUND IT!! Did a lot of digging.

In `.svelte-kit/output/server/entries/pages/_layout.svelte.js` the following code is generated in svelte 4:

```javascript
import { c as create_ssr_component } from "../../chunks/ssr.js";
import { e as escape } from "../../chunks/escape.js";
let Layout;
let __tla = (async () => {
   ...vite-plugin-wasm instantiation code...
 Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
    let mountState = "mounting";
    return `<div class="app"><main><div>${escape(mountState)}</div> <div>${slots.default ? slots.default({}) : ``}</div></main></div>`;
  });
})();
export {
  __tla,
  Layout as default
};
```


Now, svelte-5 will generate:

```javascript
import { e as escape_html } from "../../chunks/escaping.js";
import { S as pop, Q as push } from "../../chunks/index.js";
let _layout;
let __tla = (async () => {
   ...vite-plugin-wasm instantiation code...
  _layout = function($$payload, $$props) {
    push();
    let { children } = $$props;
    let mountState = "mounting";
    $$payload.out += `<div class="app"><main><div>${escape_html(mountState)}</div> <div>`;
    children($$payload);
    $$payload.out += `<!----></div></main></div>`;
    pop();
  };
})();
export {
  __tla,
  _layout as default
};
```

The issue is that `__tla` is never actioned on, even though it's a top level await function, so _layout (default export) will be undefined, so `component` in `0.js` will return undefined leading all the way to `Pyramid[0]` being the component constructor for the layout page to be undefined. I imagine `Pyramid[1]` is also undefined here. This is why it would *sometimes* work, because something would eventually process the topLevelAwait. Maybe it's a race condition. I had assumed this gets called anyway simply because it's instantiated.

Why does this work in Svelte 4?

in `internal.js` the Root function will validate that `constructors[0]` and `constructors[1]` have been properly instantiated using `validate_component` in `ssr.js`. Since these constructors are not validated, that leads to the error.

This is why I believe wasm won't work: Top level await does not set the component before it's been called by the compiler.

**Comment by dsgallups** [comment]
Last time I'm changing the title, wanted to make it more concise.

**Comment by benmccann** [comment]
Changing SvelteKit sort of feels like the wrong solution to this as it works fine with the code that is ordinarily generated. If a plugin is generating different code it seems like that plugin's responsibility to make the generated code work.

Perhaps you could use a different import method instead of using vite-plugin-wasm? https://github.com/vitejs/vite/issues/4551#issuecomment-983012078

Another option would be to write a preprocessor to change `root.svelte` to use your patch

Fixing the underlying Rollup issue could be another way to proceed and probably the best long-term solution: https://github.com/rollup/rollup/issues/4708

**Comment by dsgallups** [comment]
Thank you Ben and everyone else! That totally makes sense. Seems like this isn't an issue with Sveltekit at all then, just that this plugin unintentionally worked as a consequence of the svelte 4 implementation. I will proceed with your recommendations. Much appreciated!
