### ISSUE TITLE
No styling (including landing page) when the following command - bunx sv create xom -  executes successfully

### ISSUE THREAD

**Issue by st-clair-clarke** [sveltejs/kit#13021]
### Describe the bug

After successfully running the command -bunx sv create xom - the landing page that has links appears without any styling as shown below:

Welcome to your library project
Create your package using @sveltejs/package and preview/showcase your work with SvelteKit

Visit [svelte.dev/docs/kit](https://svelte.dev/docs/kit) to read the documentation

Compare the copy and paste above to the screenshot below:

![image](https://github.com/user-attachments/assets/5f3c54de-8383-49e0-b8e1-ba240b66a127)

Note the absence of styling in screenshot.

### Reproduction

The screenshot below shows the terminal command and the choices selected:

![image](https://github.com/user-attachments/assets/2019fbda-2e1e-4802-9d26-d9aa9d2aa548)

### Logs

```Shell
The app runs fine with no errors - only the absence of styling.
```

### System Info

```Shell
System:
    OS: Linux 6.1 LMDE 6 (faye) 6 (faye)
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 31.99 GB / 62.63 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.1.0 - ~/.volta/tools/image/node/22.1.0/bin/node
    Yarn: 1.22.22 - ~/workspace/svelte/nxt/medsoft-shell/node_modules/.bin/yarn
    npm: 10.7.0 - ~/.volta/tools/image/node/22.1.0/bin/npm
    pnpm: 9.12.3 - ~/.volta/bin/pnpm
    bun: 1.1.34 - ~/.volta/bin/bun
  Browsers:
    Chrome: 131.0.6778.69
    Chromium: 130.0.6723.116
  npmPackages:
    @sveltejs/adapter-auto: ^3.3.1 => 3.3.1 
    @sveltejs/kit: ^2.8.1 => 2.8.1 
    @sveltejs/package: ^2.3.7 => 2.3.7 
    @sveltejs/vite-plugin-svelte: ^4.0.1 => 4.0.1 
    svelte: ^5.2.2 => 5.2.2 
    vite: ^5.4.11 => 5.4.11
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
The absence of styling is intentional. In your project creation prompts, you have `Svelte library`, which does not come with any styling.
