### ISSUE TITLE
Tests fail with latest version of Svelte

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1306]
I noticed in https://github.com/sveltejs/kit/pull/1293 that one of the tests was failing. I tracked it down to being due to the Svelte upgrade

**Comment by Conduitry** [comment]
Presumably/hopefully this is because of more hydration regressions in 3.38. There are another couple issues on the Svelte repo about that.

**Comment by benmccann** [comment]
I just see one, but yeah, unfortunately it looks like it may not be completely working yet: https://github.com/sveltejs/svelte/issues/6279
