### ISSUE TITLE
SvelteKit depends on a "vulnerable" version of `cookie` lib

### ISSUE THREAD

**Issue by SkydiverTyler** [sveltejs/kit#13089]
### Describe the bug

Hi folks, hope y'all are doing alright today. Just want to talk about this very minor issue

SvelteKit `2.9.0` depends on `cookie ^0.6.0`.
Running `npm audit` results in this message:
```
cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
fix available via `npm audit fix --force`
Will install @sveltejs/kit@0.0.30, which is a breaking change
node_modules/cookie
  @sveltejs/kit  >=1.0.0-next.0
  Depends on vulnerable versions of cookie
```
This appears to only be an issue if users can set the cookie name (which should never be allowed). Nonetheless, it's a small annoyance when managing packages, and has been the case since 2024-10-04: https://github.com/advisories/GHSA-pxg6-pf52-xh8x

The fix seems to be to upgrade to `cookie ^0.7.0` (or better yet the 1.0 release), but obviously that may take some time for the team to do. Maybe this could be one of the December challenges the Svelte team does.

Cheers,
Tyler

### Reproduction

This can be reproduced when creating a new project.
In this case, with the `sv` CLI.

1. `npx sv new [name]`
2. Follow prompts (selected options do not matter)
3. `cd ./name`
4. `npm audit`

### Logs

```Shell
...
cookie  <0.7.0
cookie accepts cookie name, path, and domain with out of bounds characters - https://github.com/advisories/GHSA-pxg6-pf52-xh8x
fix available via `npm audit fix --force`
Will install @sveltejs/kit@0.0.30, which is a breaking change
node_modules/cookie
  @sveltejs/kit  >=1.0.0-next.0
  Depends on vulnerable versions of cookie
...
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (28) x64 Intel(R) Core(TM) i7-14700KF
    Memory: 19.47 GB / 31.86 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.51)
    Internet Explorer: 11.0.22621.3527
```

### Severity

annoyance

**Comment by dominikg** [comment]
duplicate of #12903 

Please use "resolutions" or "overrides" feature of your package manager to update cookie if you don't depend on its previous behavior
