### ISSUE TITLE
Contents within #if statement are not rendered with SSG

### ISSUE THREAD

**Issue by kota-yata** [sveltejs/kit#13084]
### Describe the bug

In the `src/routes/+page.svelte` of my blog repository, I have two arrays of posts filtered by category and a variable that determines which category to display. The issue arises when the initial state doesn't trigger a re-render for the non-default condition. here is the shortened version of my code:
```svelte
<script>
  export let data;
  let { posts } = data.props;
  let memoir = posts.filter(p => p.category === 'Memoir');
  let computer = posts.filter(p => p.category !== 'Memoir');
  let genre = 'computer';
</script>

<button on:click={() => genre = 'computer'}>Computer</button>
<button on:click={() => genre = 'memoir'}>Memoir</button>

{#if genre === 'computer'}
  {#each computer as post}
    <a href={post.url}>{post.title}</a>
  {/each}
{:else}
  {#each memoir as post}
    <a href={post.url}>{post.title}</a>
  {/each}
{/if}
```
`post.url` is the actual blog pages.

when I run `vite build`, it only generates pages for posts with 'computer' genres. when I change the default value of the `genre` variable to 'memoir', it only generates pages for posts with 'memoir' genres.

I suppose this is because of some optimization done during SSG build process, avoiding generation of pages that are 'never displayed', but in this case it does not work as expected.

### Reproduction

https://github.com/kota-yata/blog

here is the repository this problem was found on. run `yarn install`, `yarn build` and see the preview with `yarn preview`. in the preview page, go to 'Memoir' tab and click one of the blog posts, then you will see it's not rendered.

the snippet I wrote above was the shortened version of `src/routes/+page.svelte`. if you change `let genre = 'computer'` to `let genre = 'memoir'` you will see the opposite happening on the preview page.

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M2
    Memory: 647.83 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 131.0.6778.86
    Chrome Canary: 133.0.6870.0
    Safari: 17.6
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.16 => 1.0.6 
    @sveltejs/adapter-vercel: ^1.0.0-next.26 => 1.0.6 
    @sveltejs/kit: next => 1.0.0-next.589 
    svelte: ^3.34.0 => 3.55.1 
    vite: ^4.1.4 => 4.1.4
```

### Severity

annoyance

**Comment by paoloricciuti** [comment]
Nope it's because during ssg sveltekit crawls your website and pretender the pages it encounters. Since you are only rendering the computers pages by default it only crawl those. However you can fix this by specifying an entries function in the page of the post

**Comment by kota-yata** [comment]
thanks. I've added entries at svelte.config.js and it worked fine
