### ISSUE TITLE
Optional route [[lang]] followed by (group) breaks router

### ISSUE THREAD

**Issue by codeit-ninja** [sveltejs/kit#13095]
### Describe the bug

When I define a route like this

```
src/routes/
├ [[lang]]/
│ ├ (site)/
│ │ └ +page.svelte
│ │ ├ providers/
│ │ │ └ +page.svelte    // this does not work correctly
│ ├ (auth)/
│ │ └ // auth routes
```

When navigating to `https://example.com/providers` it loads `[[lang]]/(site)/+page.svelte`. When navigating to `https://example.com/en/providers` it now correctly loads `[[lang]]/(site)/providers/+page.svelte`

Navigating to  `https://example.com/providers` should load `[[lang]]/(site)/providers/+page.svelte`.

### Reproduction

https://github.com/codeit-ninja/sveltekit-route-issue-repro

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5800X3D 8-Core Processor
    Memory: 7.53 GB / 15.58 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.20.4 - ~/.volta/tools/image/node/18.20.4/bin/node
    npm: 10.7.0 - ~/.volta/tools/image/node/18.20.4/bin/npm
    pnpm: 9.7.1 - ~/.volta/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/kit: ^2.9.0 => 2.9.0 
    @sveltejs/vite-plugin-svelte: ^5.0.0 => 5.0.1 
    svelte: ^5.0.0 => 5.4.0 
    vite: ^6.0.0 => 6.0.2
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment]
possible workaround is to add a param matcher for "lang" that ensures "providers" can't match as a language

rename `[[lang]]` to [[lang=lang]]` and add /src/params/lang.ts with

```js
export function match(value) {
	return value.length <4; // allows for 3 char language tags, you might want to limit this to languages supported by your app
}
```
