### ISSUE TITLE
TailwindCSS not working with AMP

### ISSUE THREAD

**Issue by jerriclynsjohn** [sveltejs/kit#1310]
**Describe the bug**
When I turn on the amp option in the config, the tailwindcss stops working and I'm guessing that's because of the AMP requirement to have styles either inline or in the `head`.

**To Reproduce**
Here is a [sample repo](https://github.com/jerriclynsjohn/sveltekit-tailwind-amp) with the AMP option turned on and also with Tailwind JIT 

**Expected behavior**
Would absolutely love it if tailwind classes could be mentioned in `head`

**Severity**
Our entire project is built using tailwind and wanted to use AMP pages for our content and now literally all our pages have no styles because of this.

**Comment by babichjacob** [comment]
It seems like you've missed providing the repo link. Also, why exactly is Tailwind relevant? Isn't it just any external stylesheet will be ignored for AMP?

**Comment by jerriclynsjohn** [comment]
I was hoping there could be a way for the svelte kit to emit CSS of a page and then add that to the header like mentioned here https://www.storyblok.com/tp/tailwindcss-express-js-amp-sites

**Comment by jerriclynsjohn** [comment]
Any idea on how to get this working.

**Comment by mrkishi** [comment]
I just confirmed this is no longer an issue, at least since #4710.

Following the directions in [the docs](https://kit.svelte.dev/docs/seo#manual-setup-amp) and installing Tailwind normally yields in properly inlined CSS.
