### ISSUE TITLE
hooks files are "skipped" if a folder with the same name exists

### ISSUE THREAD

**Issue by paoloricciuti** [sveltejs/kit#13100]
### Describe the bug

If you have a `hooks.server.ts` or `hooks.ts` and you create a folder with the same name (`hooks.server` or more commonly `hooks`) the respective file will be "ignored" during the server generation.

This is because here

https://github.com/sveltejs/kit/blob/78404dfe1eb346723eefc183278b85f25485b419/packages/kit/src/core/sync/write_server.js#L85-L119

we call `resolve_entry` with `config.kit.files.hooks.server` and `config.kit.files.hooks.universal` which by default are `src/hooks.server` and `src/hooks`. However inside `resolve_entry` we check if it's a directory and if it's a directory we resolve index on that directory

https://github.com/sveltejs/kit/blob/78404dfe1eb346723eefc183278b85f25485b419/packages/kit/src/utils/filesystem.js#L169-L191

What we should do is probably check also for the file and if there's a file AND a directory give precedence to the file.

### Reproduction

1. go [here](https://www.sveltelab.dev/pia98ep9vdjyeyz)
2. check that only the `hooks.server.ts` handle function is logging to the terminal
3. delete the `hooks` folder
4. check that now also the `reroute` function is logging to the console
5. optionally create a folder named `hooks.server` (you need to refresh the page for it to take fully effect...bug in sveltelab sorry 😅)
6. check that now no hook is logged

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.3.1 
    @sveltejs/kit: ^2.5.27 => 2.9.0 
    @sveltejs/vite-plugin-svelte: ^4.0.0 => 4.0.2 
    svelte: ^5.0.0 => 5.4.0 
    vite: ^5.4.4 => 5.4.11
```

### Severity

serious, but I can work around it

### Additional Information

This can be very hard to debug.

**Comment by eltigerchino** [comment]
Wondering if the solution to this would solve https://github.com/sveltejs/kit/issues/12065 too
