### ISSUE TITLE
adapter-node bug? can't POST long text on deployed app

### ISSUE THREAD

**Issue by diramazioni** [sveltejs/kit#13111]
### Describe the bug

Hello, I've an unusual behavior/bug while posting a long text in a form, the server times out and never respond nor errors.
I've made a simple example to show the problem, however the app works as expected if I run it with `pnpm dev` and also in `pnpm preview` moreover it works deployed with `@sveltejs/adapter-vercel `but not with `@sveltejs/adapter-node`

working deployed adapter-vercel https://testone-jlvu6glw9-diramazionis-projects.vercel.app/
NOT working deployed adapter-node https://iot.digiteco.it/t

I've tried also to add BODY_SIZE_LIMIT, however changing to any value would not make the server start 
Error: Invalid BODY_SIZE_LIMIT: ''Infinity','. Please provide a numeric value. 
Error: Invalid BODY_SIZE_LIMIT: '1024000,'. Please provide a numeric value.

### Reproduction

https://github.com/diramazioni/testone/tree/adapter-node

### Logs

```Shell
on the server logs I see no errors and this console.log(updatedContent) is no reached

at the browser (Brave) after a while it times-out and see 
entry.C7jMES29.js:1 
       POST https://iot.digiteco.it/t?/save 504 (Gateway Time-out)
window.fetch @ entry.C7jMES29.js:1
x @ 9.BeinAz_K.js:1
(anonymous) @ utils.CLVpOP1V.js:1
m @ utils.CLVpOP1V.js:1
a @ utils.CLVpOP1V.js:1
VM101:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON

this last error in not present in firefox
```

### System Info

```Shell
on the adapter-node server $  node -v v18.19.0
**tried also with node v20.18.1**
```

### Severity

blocking all usage of SvelteKit

### Additional Information

my app is live and this is critical!

**Comment by Conduitry** [comment]
`BODY_SIZE_LIMIT` is the correct way to deal with this. From the error messages, it looks like you have additional quotes and/or commas in the value of the env var.

**Comment by diramazioni** [comment]
I've tried with and without quotes, and setting to `0` or `Infinity` can you check it works?
beside 50 paragraphs of text are less then 512k theoretical default

**Comment by coryvirok** [comment]
I've been using `BODY_SIZE_LIMIT=5000000` in my Dockerfile for a while and it works.

Looks like you have the Node version behind NGINX. You may want to check your NGINX logs for more info. I'm guessing there's a misconfiguration between NGINX and your SvelteKit app. How are you running your SvelteKit app? 1 Docker container running NGINX + Kit?

**Comment by diramazioni** [comment]
BODY_SIZE_LIMIT was indeed the problem, thanks, additional confusion came as pm2 was caching previous settings, I had to pm2 delete and then I was able to use the new settings.
Anyway I wish I had an error message of some sort instead of mysterious timeout, this  problem drove me crazy for a whole day
