### ISSUE TITLE
Give us the option to have root pages as same name as folder

### ISSUE THREAD

**Issue by ollyde** [sveltejs/kit#13135]
### Describe the problem

The +page stuff kinda sucks. It's annoying and is giving people headaches.

Why not give us the option below along with legacy support for +page names.

This is a far better pattern.
```
Home/home.svelte
Messages/messages.svelte
```

### Describe the proposed solution

This is a far better pattern.
```
Home/home.svelte
Messages/messages.svelte
```

### Importance

nice to have

**Comment by Conduitry** [comment]
This proposal sucks way more, is way more annoying, and would give way more people headaches.

**Comment by Conduitry** [comment]
I knew I recognized this name from somewhere. https://github.com/sveltejs/kit/issues?q=is%3Aissue+author%3Aollyde Apparently all the other times you opened this same issue and it got closed wasn't enough of a hint.
