### ISSUE TITLE
dynamic page templates

### ISSUE THREAD

**Issue by wysher** [sveltejs/kit#1315]
**Describe the bug**
Not possible to have dynamic page templates (or there's just no documentation for it).
I looked for help on svelte discord, but didn't find anything that will work.

**Details**
I'd like to have template system for each page, mainly to not repeat same code over and over. Plus adding next pages with template is easier than creating two files for each page.

I think this is pretty common for blog pages as well (you may have for instance simple blog entry, recipe, etc. based on category).

Each page data will have template name, which then needed to be imported dynamically by this name.

My attempt was to have two files `[slug].json.ts` and `[slug].svelte`:

```js
// routes/[slug].json.ts
export async function get({ params }) {
	const { slug } = params;
	const body = await readFile(`./content/${slug}.json`); // readFile with fs.promises

	if (body) return { body };
}
```

```js
// routes/[slug].svelte

<script context="module">
  export async function load({ page, fetch }) {
    const { params: { slug } } = page;

    try {
      const res = await fetch(`./${slug}.json`);
      const data = await res.json();

      return { props: { data, slug } };
    } catch (error) {
      console.error(error);
    }
  }
</script>

<script>
	import { onMount } from 'svelte';
    export let data, slug, component;

	onMount(async () => {
		component = (await import(`../_templates/${slug}.svelte`)).default;
	});
</script>

<svelte:component this={component} data={data} />
```

But navigating to another page not remounts page, so on client side page user was navigated to uses prev template.

Another attempt was to use beforeUpdate instead of onMount, but it falls into infinite loop, eventualy crashing the page.

In third attempt, instead of using svelte lifecycle methods I tried subsribe to page store, but it works only for few navigations and eventually crashes the page as well.

Another issue I find with this is that dynamic routes like [slug] not works with index page, so I need to have `index.json.js` and `index.svelte` files, which share same code with [slug].json.js and [slug].svelte.

Another attempts i tried:
- import component inside load function - works on client side, but not on ssr
- create $layout.svelte file, subscribe to page store, but fs is not accessible on client-side.

**To Reproduce**
Here's repo which shows this issue with three attempts I described above.
https://github.com/wysher/sveltekit-dynamic-templates-issue

**Expected behavior**
At least documentation of how to use template system with svelte kit.

**Comment by benmccann** [comment]
Documentation for specific use cases is best handled by the community in blog posts, tutorials, etc. We try to keep the documentation very general so that it is helpful for all users

**Comment by wysher** [comment]
@benmccann thanks for respond, but this looks more like bug than just lack of documentation. Also I pointed not one, but at least few possible bugs (like fall into infinite loop), so at least take a look.

I still don't know if this is even possible with sveltekit and it looks like pretty common use case which should be handled somehow. If it's not possible, please let me know or give some directions.

I use sapper for 2 and svelte for 3 years now, but even I tried for a few days I didn't came up with solution, so I will really appreciate it.

**Comment by babichjacob** [comment]
I don't understand how you're using a dynamic route (`/src/routes/[slug].svelte`) that looks up a `/src/_template/${slug}.svelte` instead of having your "templates" already in `/src/routes/whichever-template-here.svelte`.

**Comment by benmccann** [comment]
I can't understand the report. Part of this might be that it's discussing multiple different things that you tried. If there is a bug, please file a report discussing just that issue and showing how to reproduce it

**Comment by wysher** [comment]
@babichjacob 
First of all - I don't know which template will be used for specific route. I leave that choice to user (by CMS).
I just leave user options, like here's 3 different templates. Create how many pages you like and pick one for each page.

Second, much less important - I don't like to repeat same code, and for each template I need to have:
- /src/routes/whichever-template-here.svelte with load function (this may be imported)
- /src/routes/whichever-template-here.json.ts (or maybe just one json file, but I need to pass additional data, like slug to fetch method)

**Comment by wysher** [comment]
@babichjacob 
First of all - I don't know which template will be used for specific route. I leave that choice to user (by CMS).
I just leave user options, like here's 3 different templates. Create how many pages you like and pick one for each page.

Second, much less important - I don't like to repeat same code, and for each template I need to have:
- /src/routes/whichever-template-here.svelte with load function (this may be imported)
- /src/routes/whichever-template-here.json.ts (or maybe just one json file, but I need to pass additional data, like slug to fetch method)
