### ISSUE TITLE
Fatal error on importing svelte/reactivity/window in SSR

### ISSUE THREAD

**Issue by khromov** [sveltejs/kit#13150]
### Describe the bug

When importing `svelte/reactivity/window`, it seems like SvelteKit crashes:

```
130 | export const devicePixelRatio = /* @PURE */ new (class DevicePixelRatio {
131 |   #dpr = source(BROWSER ? window.devicePixelRatio : undefined);
132 |
133 |   #update() {
134 |           const off = on(
135 |                   window.matchMedia((resolution: ${window.devicePixelRatio}dppx)),
               ^
ReferenceError: Can't find variable: window
      at #update (C:\Users\user4\Documents\project\node_modules\svelte\src\reactivity\window\index.js:135:10)
```

As reported here https://discord.com/channels/457912077277855764/1316505763635789824/1316505763635789824

### Reproduction

https://www.sveltelab.dev/1hq6jy1ujicwck2

### System Info

```Shell
-
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Closing in favor of https://github.com/sveltejs/svelte/issues/14680
