### ISSUE TITLE
`SvelteKit 2.12.1` with `@sveltejs/vite-plugin-svelte 4.0.3` return weird server-side results

### ISSUE THREAD

**Issue by Serator** [sveltejs/kit#13179]
### Describe the bug

<img width="493" alt="image" src="https://github.com/user-attachments/assets/ef04f5c5-1af6-4256-94d3-813640c99411" />

At the moment I can't update `@sveltejs/vite-plugin-svelte` to version `5.x` in which everything works fine, but with version `4.0.3` I get output (only on the server side, in the browser everything is ok) as in the screenshot.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-jnng6k3p?file=src%2Froutes%2F%5Btest%5D%2F%2Bpage.svelte

### System Info

```Shell
-
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
When Vite 5 is installed, `$app/state` on the server seems to be resolving to the client module instead of the server module.
https://github.com/sveltejs/kit/blob/main/packages/kit/src/runtime/app/state/package.json
