### ISSUE TITLE
page.url not reactive on the new $app/state module.

### ISSUE THREAD

**Issue by Gonzalo9823** [sveltejs/kit#13187]
### Describe the bug

When you try to hear for changes on `page.url` using `$derived` it won't work. For example If ones has a `+page.svelte` that wants the value of a `searchParams` like this:
 
```typescript
const currentPage = $derived(page.url.searchParams.get("page") || "");
```

And then you update the `searchParams` using `goto`:

```typescript
const { url } = page;

url.searchParams.set('page', newPage);

goto(url, { replaceState: true, noScroll: true, keepFocus: true, invalidateAll: true })
```

The value of `currentPage` won't be updated it. I tried multiple combinations of this, and the only thing that works is listening to another value of `page`. For example something like this:

```typescript
const currentPage = $derived.by(() => {
  page.state;

  return page.url.searchParams.get('page') || '';
});
```

Now if I change the `searchParams` my `currentPage` will be updated to the correct value.

Also this used to work using the `$app/store` module:

```typescript
// This works.
const currentPage = $derived($page.url.searchParams.get('page') || '');
```

### Reproduction

https://replit.com/@GonzaloCaballe1/Reproduction

+page.svelte:

```svelte
<script>
  import { page } from "$app/state";
  import { goto } from "$app/navigation";

  const currentPage = $derived(page.url.searchParams.get("page") || "");

  const currentPageWorking = $derived.by(() => {
    page.state;
    return page.url.searchParams.get("page") || "";
  });
</script>

<div>
  <label for="current_page">Current Page:</label>
  <input
    id="current_page"
    bind:value={
      () => page.url.searchParams.get("page"),
      (newPage) => {
        const { url } = page;

        url.searchParams.set("page", newPage);

        goto(url, {
          replaceState: true,
          noScroll: true,
          keepFocus: true,
          invalidateAll: true,
        });
      }
    }
  />
</div>

<h1>Current Page Not Working: {currentPage}</h1>
<h1>Current Page Working: {currentPageWorking}</h1>
```

### System Info

```shell
System:
  OS: macOS 14.5
  CPU: (10) arm64 Apple M1 Pro
  Memory: 105.55 MB / 16.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
  npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
  pnpm: 9.14.2 - ~/Library/pnpm/pnpm
  bun: 1.1.9 - ~/.bun/bin/bun
npmPackages:
  svelte: 5.14.1 => 5.14.1
```

### Severity

annoyance

**Comment by Leonidaz** [comment]
according to the docs `goto` takes a string or URL.  However, this only currently works with a string.

[Working Reproduction SvelteLab](https://www.sveltelab.dev/j4gb3bc1xb2506w)

this works or `url.toString()`
```javascript
        goto(`?${url.searchParams.toString()}`, {
          replaceState: true,
          noScroll: true,
          keepFocus: true,
          invalidateAll: true,
        });
```

this doesn't:

```javascript
        goto(url, {
          replaceState: true,
          noScroll: true,
          keepFocus: true,
          invalidateAll: true,
        });
```

[Svelte Reactivity seems to be fine with `SvelteURL`](https://svelte.dev/playground/hello-world?version=5.14.2#H4sIAAAAAAAAE32QT2uEMBDFv8oQCiqIsldXhdJLDz0sLT3VUrI6uwZiDMno7iJ-9xLT_VO29JTJy_u9mcnEFO-QZewZpezh0BvZQIiNIGwiFrOdkGhZ9jExOmnncwKLz9Sj1okdUZLTttziX3rdK0JFlmUst7URmspKVSQ63RuCCd4W4_vrC8ywM30HgUdTg7wmMQo6BetKOabulSUYjIQCFB6uaBi0RNpmaYpH3mmJSd13qebUBtHCAni2HoxBRRu-RyjgoUEjRmzCwcjEIjd1u-GGdzbZI4UV03yPFYtcRJ5eZ1d5I8bSheaSb1HCrjdFxX6yvzxVPvkruF5Zni5ODwmlB3IVgGjuQP-wFarJRi4HLCavAIQRFCX8P2t8MSs8uNYLc4mAe9ze4DGcqfWZmH2xHGnpPsIvX6m8Xf1eEqab753ztF2VlWIxIzwSy8gMOH_O36MKFAJzAgAA)

**Comment by eltigerchino** [comment]
This snippet works because we're not mutating the $page/state URL object
```
<script>
  import { page } from "$app/state";
  import { goto } from "$app/navigation";

  const currentPage = $derived(page.url.searchParams.get("page"));
</script>

<div>
  <label for="current_page">Current Page:</label>
  <input
    id="current_page"
    bind:value={() => page.url.searchParams.get("page"),
    (value) => {
      const searchParams = new URLSearchParams(page.url.search);

      if (value) {
        searchParams.set("page", value);
      } else {
        searchParams.delete("page");
      }

      goto(`?${searchParams}`, {
        replaceState: true,
        noScroll: true,
        keepFocus: true,
        invalidateAll: true,
      });
    }}
  />
</div>

<h1>Current Page: {currentPage}</h1>
```
It's kind of a similar request to https://github.com/sveltejs/kit/issues/13178 where people want $page/state to be mutable whereas I think it wasn't intended to work this way? Thoughts? @dummdidumm @Rich-Harris

**Comment by dummdidumm** [comment]
This is probably because when the URL is not actually updating by reference, `$state.raw` says "nothing changed" and won't trigger an update.
Either we always wrap it in a `new URL(...)` or we implement a version counter under the hood for it.

**Comment by Leonidaz** [comment]
@dummdidumm @Rich-Harris  was the page.url created as `state.raw` on purpose so it's not deeply reactive with unwanted side-effects?

why not use `SvelteURL` for full reactivity? e.g. [playground SvelteURL with searchParams reactivity](https://svelte.dev/playground/hello-world?version=5.14.2#H4sIAAAAAAAAE32QT2uEMBDFv8oQCiqIsldXhdJLDz0sLT3VUrI6uwZiDMno7iJ-9xLT_VO29JTJy_u9mcnEFO-QZewZpezh0BvZQIiNIGwiFrOdkGhZ9jExOmnncwKLz9Sj1okdUZLTttziX3rdK0JFlmUst7URmspKVSQ63RuCCd4W4_vrC8ywM30HgUdTg7wmMQo6BetKOabulSUYjIQCFB6uaBi0RNpmaYpH3mmJSd13qebUBtHCAni2HoxBRRu-RyjgoUEjRmzCwcjEIjd1u-GGdzbZI4UV03yPFYtcRJ5eZ1d5I8bSheaSb1HCrjdFxX6yvzxVPvkruF5Zni5ODwmlB3IVgGjuQP-wFarJRi4HLCavAIQRFCX8P2t8MSs8uNYLc4mAe9ze4DGcqfWZmH2xHGnpPsIvX6m8Xf1eEqab753ztF2VlWIxIzwSy8gMOH_O36MKFAJzAgAA)

https://github.com/sveltejs/kit/blob/089159cc10a6d5a00cb693b48fc543785ca23e6b/packages/kit/src/runtime/client/state.svelte.js#L39

**Comment by dummdidumm** [comment]
while that's a nice idea, we can't do that at least in SvelteKit 2 while we still support Svelte 4, because we would need to import it from somewhere that does not exist in Svelte 4.

**Comment by Leonidaz** [comment]
> while that's a nice idea, we can't do that at least in SvelteKit 2 while we still support Svelte 4, because we would need to import it from somewhere that does not exist in Svelte 4.

but how are we using `$state.raw` then?  There is a flag above to check for legacy: https://github.com/sveltejs/kit/blob/089159cc10a6d5a00cb693b48fc543785ca23e6b/packages/kit/src/runtime/client/state.svelte.js#L17C5-L40

But if you mean that the behavior in SvelteKit 2 with Svelte v4 vs v5 will be different (reactive vs not), yeah.... I mean, it could be documented and people with Svelte 5 can start benefitting from this without having to wait for SvelteKit version 3.

**Comment by Rich-Harris** [comment]
That's not why. These values are readonly — if we use `SvelteURL` then any miscreant will be able to do things like `page.url.pathname = '/potato'`. It needs to be controlled by the framework

**Comment by Gonzalo9823** [comment]
@Rich-Harris Hey! Just to clarify, I don't expect variables using `$derived` to react whenever I change something in `page.url.searchParam`. I understand that the `page` state is readonly. However, I do expect my `$derived` values to update when navigating to a different page.

```typescript
// This should not work
const currentPage = $derived(page.url.searchParams.get('page') || '');
page.url.searchParams.set('page', newPage);
```

```typescript
// This should work
const currentPage = $derived(page.url.searchParams.get('page') || '');
page.url.searchParams.set('page', newPage);
goto(page.url, { replaceState: true, noScroll: true, keepFocus: true, invalidateAll: true })
```

Also, while currently `goto(page.url)` doesn't work, using a link does.

```svelte
<!-- This works -->
<a data-sveltekit-replacestate data-sveltekit-noscroll data-sveltekit-keepfocus href="/my-page?page=1">1</a>
```

**Comment by Leonidaz** [comment]
> That's not why. These values are readonly — if we use `SvelteURL` then any miscreant will be able to do things like `page.url.pathname = '/potato'`. It needs to be controlled by the framework

Not sure I understand because at least client-side, while `page.url` itself is read-only, the `pathname` is writable via URL.

**Comment by eltigerchino** [comment]
> > That's not why. These values are readonly — if we use `SvelteURL` then any miscreant will be able to do things like `page.url.pathname = '/potato'`. It needs to be controlled by the framework
> 
> Not sure I understand because at least client-side, while `page.url` itself is read-only, the `pathname` is writable via URL.

The intention is that these values are read-only. https://svelte.dev/docs/kit/$app-state

> SvelteKit makes three **readonly** state objects available via the $app/state module — page, navigating and updated.

For example, updating `url.pathname` doesn't actually navigate to that URL. It's a one way source of truth.

**Comment by Rich-Harris** [comment]
@Gonzalo9823 agree, it's a totally reasonable expectation. We can fix it just by ensuring that `page.url` is a new object following `goto` (I _think_ that's the only place where a mutation would go undetected) — #13196
