### ISSUE TITLE
404 Error for URLs with Uppercase Letters

### ISSUE THREAD

**Issue by ambigos1** [sveltejs/kit#13198]
### Describe the bug

Hi.
I am using the latest SvelteKit, Vite version.

I am getting a 404 error if one letter in the URL contains uppercase letters.
This error can be reproduced in the SvelteKit official blog

for example, The following URL throws a 404 error:
https://svelte.dev/blog/sv-The-svelte-cli

because the "The" word containing "T" uppercase letter

However, this URL works as expected:
https://svelte.dev/blog/sv-the-svelte-cli

### Reproduction

Another example:
Opening:
https://svelte.dev/tutorial/Svelte/welcome-to-svelte
 but opening:
 https://svelte.dev/tutorial/Svelte/welcome-To-svelte
Where the T in welcome-to-svelte is capitalized, it leads to a 404.

### System Info

```Shell
latest
```

### Severity

serious, but I can work around it

**Comment by eltigerchino** [comment]
It's intended that routing is case-sensitive. If you want it to be case-insensitive you can use the `reroute` hook to convert incoming request URLs to lowercase first so it matches a corresponding route.

```ts
export function reroute({ url }) {
  // this will convert /abouT to /about and match the /about/+page.svelte route
  return url.pathname.toLowerCase();
}
```

[Example](https://stackblitz.com/edit/sveltejs-kit-template-default-3myxqd1y?file=src%2Fhooks.js)
