### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by briteming** [sveltejs/kit#13248]
### Describe the bug

git clone failed

### Reproduction

$ git clone https://github.com/sveltejs/kit kit-by-sveltejs
Cloning into 'kit-by-sveltejs'...
remote: Enumerating objects: 86835, done.
remote: Counting objects: 100% (1243/1243), done.
remote: Compressing objects: 100% (669/669), done.
error: 80 bytes of body are still expected89 MiB | 903.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

### System Info

```Shell
it exports:

 System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 749.23 MB / 7.77 GB
  Binaries:
    Node: 23.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.9.0 - ~\node_modules\.bin\npm.CMD
    pnpm: 9.14.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (131.0.2903.70)
    Internet Explorer: 11.0.22621.3527
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Works fine for me. This isn't something we'd be able to do anything about, anyway. Try searching for `fetch-pack: unexpected disconnect while reading sideband packet` online. It's a connection stability or speed issue.
