### ISSUE TITLE
Adapter-Static readme file missing some info

### ISSUE THREAD

**Issue by mbtrs** [sveltejs/kit#1325]
> **Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: I'm always frustrated when [...]

When trying to `npm run build` without an adapter, you get a message that you need an adapter. I go to the adapter page and I choose the adapter-static option. I go to the README page and it appears to be missing information on how to set it up.

[@sveltejs/adapter-static README.md](https://github.com/sveltejs/kit/tree/master/packages/adapter-static)

> **Describe the solution you'd like**

I am proposing an addition to the README file:

```
## Configuration

Add `"@sveltejs/adapter-static": "next"` to the `devDependencies` in your `package.json` and run `npm install`.

Then add the adapter to your `svelte.config.cjs`:

...
```

> **Describe alternatives you've considered**

> **How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously.

This isn't high priority by any means.

> **Additional context**

I am not sure if there are other plans in place for adapters. I have been reading about the adapters in the issues section but I can't make out what exactly the plans are for them.

**Comment by benmccann** [comment]
PR welcomed if you'd like to make this change
