### ISSUE TITLE
Access to router 

### ISSUE THREAD

**Issue by makuzaverite** [sveltejs/kit#1328]
I'm working on an app where I need access to the current path, I would like to know if there is any way to do so?. I tried using the window object but it doesn't work. I also tried using this 
![image](https://user-images.githubusercontent.com/53856673/117002868-67449180-ace4-11eb-8ef2-edcb8ff80c23.png)

But it didn't work, if there is any way help me out.

**Comment by antony** [comment]
Hi @makuzaverite - we intend github issues to be the place for issues with Svelte Kit or feature requests, not for support.

Your question is covered by the docs, but if you need more help, please [chat to us](https://svelte.dev/chat).
