### ISSUE TITLE
[ERROR] svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/kit#1342]
**Describe the bug - Log**
svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module. See https://kit.svelte.dev/docs#configuration for an example

**To Reproduce**
This is the weirdest issue ever i got 
i installed this https://github.com/SharifClick/svelte-swipe
its giving me the error below 

i delete its it same , i remove all .svelte and node_modules , still same error 😭 

**Expected behavior**
its should not throw any error, after removeing all the node_modules + .svelte , and install package.json again

<details>
  <summary>Stack trace</summary>

```
> svelte-kit dev

svelte.config.cjs should be renamed to svelte.config.js and converted to an ES module. See https://kit.svelte.dev/docs#configuration for an example
No "exports" main defined in /study/spacefoot/xxxxxxxxxx/node_modules/@sveltejs/adapter-node/package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /study/spacefoot/xxxxxxxxxx/node_modules/@sveltejs/adapter-node/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:479:7)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/study/spacefoot/xxxxxxxxxx/svelte.config.cjs:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
``` 
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 2.62 GB / 7.71 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Browsers:
    Chromium: 90.0.4430.93
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.92 => 1.0.0-next.99 
    svelte: ^3.38.1 => 3.38.2 
    vite: ^2.2.3 => 2.2.4 

```

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
node
 
</details>

**Comment by mvolfik** [comment]
I was also hit by this, apparently some overnight update included a change that requires this. To fix it, do what it says – rename the file and replace `const someThing = require("some-thing")` with `import someThing from "some-thing";`

**Comment by Conduitry** [comment]
You need to rename your config file, rewrite it with ESM imports/exports, and update the version of the adapter you're using.

**Comment by Shaun-Regenbaum** [comment]
I still have an issue, when I do as you say, i get a module not found error:
: > hotflow-mvp@0.0.1 build /opt/build/repo
3:53:09 PM: > svelte-kit build
3:53:09 PM: (node:1356) ExperimentalWarning: The ESM module loader is experimental.
3:53:09 PM: module is not defined
3:53:09 PM: ReferenceError: module is not defined
3:53:09 PM:     at file:///opt/build/repo/svelte.config.js:5:1
3:53:09 PM:     at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
3:53:09 PM:     at async Loader.import (internal/modules/esm/loader.js:179:24)
3:53:09 PM:     at async load_config (file:///opt/build/repo/node_modules/@sveltejs/kit/dist/cli.js:440:17)
3:53:09 PM:     at async get_config (file:///opt/build/repo/node_modules/@sveltejs/kit/dist/cli.js:495:10)
3:53:09 PM:     at async file:///opt/build/repo/node_modules/@sveltejs/kit/dist/cli.js:580:18
3:53:09 PM: npm ERR! code ELIFECYCLE
3:53:09 PM: npm ERR! errno 1
3:53:09 PM: npm ERR! hotflow-mvp@0.0.1 build: `svelte-kit build`
3:53:09 PM: npm ERR! Exit status 1

**Comment by Shaun-Regenbaum** [comment]
Nevermind, I figured it out you have to change module.exports in your config file to config = ... and then after export default config.

**Comment by Egnus** [comment]
There is a side effect due to this. I cannot import _.json_ modules into the _svelte.config.js_
like this:
```javascript
import pkg from './package.json';
...
```
because I get this error `Unknown file extension ".json"`

I have tried to add to `jsconfig.json` and `tsconfig.json` this compilerOptions but they are not applied for svelte-kit when running the app:
```
"esModuleInterop": true,
"resolveJsonModule": true
```

**Comment by dummdidumm** [comment]
[The FAQ shows how to do this](https://kit.svelte.dev/faq#packages)

**Comment by autr** [comment]
Also try using:

```
pnpm view @sveltejs/kit versions
pnpm view @sveltejs/adapter-static versions
```

To view latest versions - I had to switch to `adapter-static@1.0.0-next.9` and `kit@1.0.0-next.107` to fix this issue.
