### ISSUE TITLE
OpenAPI 3

### ISSUE THREAD

**Issue by Type1J** [sveltejs/kit#1348]
**Is your feature request related to a problem? Please describe.**
I'd like to have OpenAPI 3 autogenerated for (some) endpoints.

**Describe the solution you'd like**
I'd like to be able to create an endpoint that serves JSON in the OpenAPI 3 format that describes (some of) the other endpoints.

**Describe alternatives you've considered**
I've tried doing this myself in other projects not using Svelte Kit, but I'm hoping that there's a way to generate it (or at least assist in generating it).

**How important is this feature to you?**
I can't make an API without an OpenAPI spec being served for some projects. It's a requirement that causes me lots of extra work; even though all of the type information is already available in the code, I have to restate it all in a servable subspec for each endpoint, then combine them in an endpoint that serves all of the registered subspecs as a complete OpenAPI spec.

**Additional context**
[It's a well known spec](https://swagger.io/specification/) that is usually paired with a test console web app called [Swagger UI](https://swagger.io/tools/swagger-ui/). [Here's an example of Swagger UI using the OpenAPI spec to create a test console for an API's endpoints](https://petstore.swagger.io/).

**Comment by benmccann** [comment]
This is probably best driven by the community for now. You could use something like https://github.com/lukeautry/tsoa
