### ISSUE TITLE
Invalid code is generated when using environment variables

### ISSUE THREAD

**Issue by mvolfik** [sveltejs/kit#1354]
**Describe the bug**
This bug is on an intersection of Svelte and Vite and I don't know how SvelteKit plays with all of this, but I'll report here.

When using environment variables, they are statically replaced in production builds by Vite. However, some intermediate files generated by Svelte contain these variable names also in CSS source map strings, and this replacement breaks it and produces invalid code like this:
(lines wrapped manually for readability - on the third line is the offending replacement)

```js
const css = {
	code: "h1.svelte-zynv6f{font-size:0.9em}",
	map: "{\"version\":3,\"file\":\"index.svelte\",\"sources\":[\"index.svelte\"],\"sourcesContent\":"
          + "[\"<script lang=\\\"ts\\\">function test() {\\n    console.log("8test");\\n}\\nexport"
          + " {};\\n</script>\\n\\n<h1>Welcome to SvelteKit</h1>\\n<button on:click="
          + "{test}>Test</button>\\n<p>Visit <a href=\\\"https://kit.svelte.dev\\\">kit.svelte.dev</a>"
          + " to read the documentation</p>\\n\\n<style>\\n  h1 {\\n    font-size: 0.9em;\\n  }\\n"
          + "</style>\"],\"names\":[],\"mappings\":\"AAWE,EAAE,cAAC,CAAC,AACF,SAAS,CAAE,KAAK,AAClB,CAAC\"}"
};
```

This doesn't happen during `yarn dev`, but with `yarn build` (probably?) independently of adapter - tested with static and node.

**To Reproduce**

Repo: https://github.com/mvolfik/sveltekit-bugreport

```sh
git clone https://github.com/mvolfik/sveltekit-bugreport.git
cd sveltekit-bugreport
yarn
env VITE_SOME_ENV_VAR=8test yarn build
```

As noted in the repo, to see the invalid intermediate file above, add the following line inside function at line 13256 in `node_modules/rollup/dist/shared/rollup.js` to see the broken generated source:

```js
if (input.startsWith("/* src/routes/index.svelte generated by Svelte v3.38.2 */\nimport { create_ssr_component")) console.log("\n\n", input, "\n\n");
```

The source file is this:
```html
<script lang="ts">
  function test() {
    console.log(import.meta.env.VITE_SOME_ENV_VAR);
  }
</script>

<h1>Welcome to SvelteKit</h1>
<button on:click={test}>Test</button>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<style>
  h1 {
    font-size: 0.9em;
  }
</style>
```

**Expected behavior**

It builds :)

**Stacktraces**

<details>
  <summary>Stack trace</summary>

```
[rollup-plugin-dynamic-import-variables] Identifier directly after number (6:163)
file: /tmp/sveltekit-bugreport/src/routes/index.svelte:6:163
> Identifier directly after number (6:163)
SyntaxError: Identifier directly after number (6:163)
    at Object.pp$4.raise (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:15686:13)
    at Object.pp$9.readNumber (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:17621:59)
    at Object.pp$9.getTokenFromCode (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:17440:17)
    at Object.getTokenFromCode (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:19550:20)
    at Object.pp$9.readToken (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:17180:15)
    at Object.pp$9.nextToken (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:17171:15)
    at Object.pp$9.next (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:17128:8)
    at Object.pp$3.parseLiteral (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:15148:8)
    at Object.pp$3.parseExprAtom (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:15035:17)
    at Object.pp$3.parseExprSubscripts (/tmp/sveltekit-bugreport/node_modules/rollup/dist/shared/rollup.js:14888:19)
error Command failed with exit code 1.
```

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 292.58 MB / 7.35 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 14.16.0 - ~/.local/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 7.6.3 - ~/.local/bin/npm
  Browsers:
    Chromium: 90.0.4430.93
    Firefox: 88.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.100 
    svelte: ^3.34.0 => 3.38.2 
    vite: ^2.2.3 => 2.2.4 
```

</details>

**Severity**

Blocker - basically means you can't use environment variables in svelte files which also include `<style>`s

**Additional context**

Relevant docs links:
- https://kit.svelte.dev/faq#env-vars
- https://vitejs.dev/guide/env-and-mode.html#production-replacement

**Comment by benmccann** [comment]
Thanks for the report. I think this issue resides withing Vite and would be better filed there

**Comment by mvolfik** [comment]
@benmccann I admire your work on Svelte and understand the load on open-source maintainers, but reading from [vite docs](https://vitejs.dev/guide/env-and-mode.html#production-replacement), I would say that this is intended behavior on their side, as they explicitly say that it will also be replaced in strings and should be escaped with zero-width space. So it seems to me that it really should be SvelteKit handling this

**Comment by benmccann** [comment]
Ah, I may not have read the report closely enough. I see that the line you referenced as being broken has `create_ssr_component` in it. Does this only happen on the server-side? If so, then I think our preferred solution would be to stop doing the replacement on the server side: https://github.com/vitejs/vite/issues/3176

If this is also an issue in client-side code then we can reopen this. Some more details about reproducing the issue for the client-side may help in that case as well

**Comment by mvolfik** [comment]
In my real use case of this, I build all of the code statically, with no server on the deployment. The env var is used to include an API key (which I expect to be rather static) which is used on the client side. So static replacement in the actual code is exactly what I want to do. The issue I'd like to get fixed is that somewhere during the build, it is replaced in the source map string, yielding syntax error and my code is currently unbuildable. And I'm not aware of any workaround.

**Comment by haishanh** [comment]
I think this is a [known issue of Svelte Kit](https://github.com/sveltejs/kit/issues/720#issuecomment-812728467).

You can workaround by putting the env vars into a non svelte component file, e.g. `src/lib/env.ts`

```typescript
// src/lib/env.ts
export const someEnvVar = import.meta.env.VITE_SOME_ENV_VAR;
```

Then in in your `src/routes/index.svelte`

```svelte
<script lang="ts">
  import {someEnvVar} from '$lib/env'
  function test() {
    console.log(someEnvVar);
  }
</script>
```
