### ISSUE TITLE
Error in handle() if Response.body is not string/Buffer

### ISSUE THREAD

**Issue by Leftium** [sveltejs/kit#1367]
**Describe the bug**
Error in [`handle()`](https://kit.svelte.dev/docs#hooks-handle) if `Response.body` is not string/Buffer.

This might be a simple documentation bug. However, I would like to suggest a related feature: allow `handle()` to return a response like [`load()`](https://kit.svelte.dev/docs#loading). This would make it easier to do redirects, error pages, and page caching from `handle()`.
- Ideally `handle()` could just return a Response that looks like `LoadOutput`.
- Perhaps `render()` could detect if the input is more like `{status, error, redirect, maxage}` and render that into an acceptable response.
- Or: just expose a utility function like `render()` that accepts such input. Either as another property passed to `handle()` or as an `import`

My app needs to:
1. Get a user JWT from HttpOnly cookie.
2. Create a guest user if no valid user cookie.
3. Set HttpOnly cookie if new guest created.
4. Redirect to error page if error creating guest user.

So `handle()` seems to be the best place to do this:
- Layout `load()` cannot set headers (for HttpOnly cookie), and only has indirect access to headers/cookies via `session`.
- `handle()` is better at keeping (API) secrets; has full access to `locals`

**Logs**
```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Object
    at ServerResponse.end (_http_outgoing.js:785:13)
```
**To Reproduce**
Return a response from `handle()` where Response.body is not a string/Buffer.

**Expected behavior**
1. Documentation for `handle()` updated to:

```
type Response = {
	status?: number;
	headers?: Headers;
	body?: string | Buffer;
};
```
2. OR: `handle()` can return any type of  `Response.body` without error.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
 System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 12.17 GB / 23.86 GB
  Binaries:
    Node: 14.16.0 - D:\DropBox\a\nodejs\64v14.16.0\node.EXE
    Yarn: 1.22.4 - D:\dropbox\home\.yarn\bin\yarn.CMD
    npm: 6.14.11 - D:\DropBox\a\nodejs\64v14.16.0\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.51)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.100
    svelte: ^3.34.0 => 3.38.2
    vite: ^2.2.3 => 2.2.4
```

</details>

**Severity**
Mostly annoying with one aesthetic limitation:
- It does not seem possible to use SvelteKit $error.svelte templates from `handle()`.
- I'd like to reuse code that is *already* in SvelteKit.
- Both `handle()` and `load()` return similar responses, but their interfaces are quite different.

**Comment by benmccann** [comment]
FYI, I added this to the 1.0 milestone to indicate that if we do it then it should be before 1.0 since it requires changing the API. This isn't an indication of whether I think we should do it, which I haven't really considered yet

**Comment by Conduitry** [comment]
I'm inclined to say this is a bad idea, because `handle` is lower level, and gives you precise control over, say, the incoming and outgoing headers, which `load` does not. It'd never have the same API anyway, and the separate purposes of the two return values should not be confused.

**Comment by Rich-Harris** [comment]
I'm in agreement with @Conduitry — the requirements listed above are easily met with the current API

**Comment by Leftium** [comment]
Thanks for considering the suggestion.

There's still a documentation bug: `body?` is not type `any` and the other two properties no longer seem optional (or at least they dropped the `?`)

[Type for handle() Response according to docs](https://kit.svelte.dev/docs#hooks-handle):
```
type Response = {
	status?: number;
	headers?: Headers;
	body?: any;
};
```

The actual type defined in hooks.d.ts:
https://github.com/sveltejs/kit/blob/11e7840c67c2cae17940b0d9664ca0fb3da91eb9/packages/kit/types/hooks.d.ts#L14-L18
