### ISSUE TITLE
Thoughts about SvelteKit pre-1.0

### ISSUE THREAD

**Issue by ttxtosca** [sveltejs/kit#1368]
**Is your feature request related to a problem? Please describe.**
I'm "frustrated" when I see current (and possible) future decisions about name charting. #1149 

**Describe the solution you'd like**
See below.

**How important is this feature to you?**
I think it's valuable for any serious future user and newcomer into the project.

**Additional context**
Hello,

First, I would like to congratulate you all, I think you are making a real good product right here.

I just wanted to give you some thoughts I have about SvelteKit after some tryout (despite it may not be the right place, but main topic coming).

Of course, we all 'expect bugs' from a beta project. By the way, except that projet is growing fast, I suggest to keep the demo as simple as possible for future newcomers. For example, messing with animations and extra styling is of course a nice thing to have/show, but a direct demo of what SvelteKit does (as a game-changer, in my opinion) is quite prefereable.

But anyway. In fact, I had some trouble testing the demo app (for issues already created, + some other, due to fast-growing codebase) ; By the way, at this day, a simple try/catch in the _api.js file should handle any issue that may happen.

But the real thing I have to say is this (in fact, the issue #1149 seams important to me) - don't take it personal, these are just observations :

- Original (+ proposed ones) name charting seams.. broken. I mean, '$', '[]', '{}' is quite.. not optimal at all.
- I think private files (actual '_') can, I think, easily live outside the ./router directory. For standard use case, only _api seams really useful ; for any advanced/custom usage, It feels natural to store this kind of file in appropriate directory.
- For layouts, a directory should be alright ; configurable (as path in config) and custom/nested layout configured locally in route/page template
  - If not acceptable, a double underscore '__' is Ok I think (as 'decided?')
- **Simple underscore '_' for params/slugged routes** < this is the point. (yeah like Nuxt or others but.. quite standard I guess)

This way, no longer issues and wierd behavior about filenames in terminals/editors. Really It's the only thing that bother me. This is not a "major" issue I suppose. But, AFAIK, to my knowledge, this is the first project I see adopting the kind of name charting, and this may break some users.

I'm taking this project very serioutly at the moment (and I'm sure many of us do too) - I may contribute (technically) or, anyway, would be happy to contribute for any french translation/promotion :)

Sorry for my rusted english! Good luck! I wish you the best.

**Comment by benmccann** [comment]
I'm not really sure what you mean by "name charting", but that issue was locked and limited conversation to collaborators for a reason and I hope you can see that simply filing a new issue to get around that might be considered frustrating or annoying

**Comment by ttxtosca** [comment]
Hello @benmccann,

By "name charting" I mean the filename style that is beeing applied (for layouts, dynamic endpoints, private files, etc). I noticed that the referenced issue is limited to collaborators, this is why the title (and content) of this issue is not referencing only this point.

Where do I have to suggest such things ? I ~~think~~ was thinking that some ideas/feedback from the community should be welcome, especially at this stage of the development.

Anyway, I hope you won't feel frustrated on annoyed if any future user tells you that using such characters is an issue (or don't really understand the demo, if they can run it).

As I said, good luck for this project! And I repeat I wish you the best.

**Comment by ttxtosca** [comment]
@Rich-Harris any thoughts ? After all, I writed this ticket mainly for you, since you are the main architect of this project. If none of these observations are acceptable just say it. If this is inapropriate, for any reason, just say it too. Otherwise, should I open a new issue for each idea / feature request? This would make sense.

Is @benmccann' behavior desirable ? I mean, does this seem normal to you ? Is this the new way to go in open source community ? If so, could be nice to know (I have surely grown old) ; but if not, thank you for any information about the way you prefer getting some feedback, if you do. I started the ticket by re-using ironically the (pre-filled) word "frustrated", but I have to say that such reaction is quite brutal and will, for sure, frustrate many future users. By the way I am myself a lot more frustrated by this than the way you want to name your routes files. How the hell any positive feedback can from now on be qualified as "_frustrating or annoying_" ? (serious question) ; even more given that this is the first time I'm posting something here ; besides offering my help. I did not want to spam but I rarely seen this.

I suppose that no answer at all will mean everything. I don't know you but I'm sure you're not this kind of person ; but if I'm wrong, I sincerely hope that only bug reports, general problems and such team members will help to maintain the future of the project in a healthy way... As I said, despite current stage, this project has great opportunities. Again, congratulations and good continuation!

**Comment by dummdidumm** [comment]
The referenced issue was locked and limited because of the bike shedding that occured, opening another ticket to continue the discussion is not the right solution, which is why Ben closed it. He certainly didn't want to come across as rude, but please understand that we get a lot of tickets each day and this issue is the second attempt to continue the discussion in a duplicate issue. Tagging other maintainers of the project because you are not satisfied with the response certainly isn't the solution.

Moreover, the referenced issue is now closed, the decision has been made. `$` was switched to `__` (double underscore), the `[brackets]` syntax stays the same.

**Comment by ttxtosca** [comment]
I understand. Thank you for the clarification, I noticed that decisions were made (or are in the process to) ; so I wanted to make sure that this is definitive and no other conversation about this topic is possible. As you may know, some important aspects sometimes need a bit of persistence (before it's too late?). My apologies for this (I must have really exaggerated). As I said, I hope this won't hurt any furure aspects of development or usage of this project.

By the way my issue did not raised that only topic (that has to be said). But nevermind. Plus, I did not tagged any maintainer (or you), but the main author of this project (I think?). And to conclude, the problem is not that the issue was closed, or even that I'm not satisfied with the answer ; the problem is that the given answer is not, in my opinion, the right way to go (even considering the growing amount of issues that are being created). This is a normal behavior for any similar project at this given stage. But you already must know that.
