### ISSUE TITLE
file based layout reset

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/kit#1376]
**Is your feature request related to a problem? Please describe.**
Here is my file structure
```
- folder
  - 0.svelte
  - 1.svelte
  - special.svelte
```

I want `0.svelte` and `1.svelte` to inherit the layout but not `special.svelte`.

**Describe the solution you'd like**
```html
<script context="module">
export let inheritLayout = false;
<script>
```

**Comment by TheComputerM** [comment]
Nice, but can you suggest any method by which I can do the same thing but with the root index.svelte.
```
- index.svelte
- section1
    - page1.svelte
- section2
    - page2.svelte
```

section 1 and 2 should have same layout but not index.svelte.

**Comment by didier** [comment]
@TheComputerM I'd suggest making a layout component (`SectionLayout.svelte`), defining your layout there, and importing it in the `$layout.svelte` of `section1` and `section2`:

```bash
src/
├── lib/
│   └── components/
│       └── SectionLayout.svelte
└── routes/
    ├── index.svelte
    ├── section-1/
    │   ├── index.svelte
    │   └── $layout.svelte
    └── section-2/
        ├── index.svelte
        └── $layout.svelte
```

I'll admit—it isn't ideal, but it definitely does the job.

**Comment by intrikate** [comment]
Given the structure above, layouts for `section-1` and `section-2` will always mutually reset. This may be a factor if you depend on layout preservation.

In a similar #1110, it was proposed to adjust one layout from different routes [using context](https://github.com/sveltejs/kit/issues/1110#issuecomment-822345891). That approach offers potentially unlimited control over what is done and how, and should, in theory, allow shared layouts to remain *actually shared*. Please not that in practice the concept of ‘shared’ is currently shaky (see #1214).
