### ISSUE TITLE
Change esbuild platform to browser for the cloudflare adapter

### ISSUE THREAD

**Issue by ElioStalteri** [sveltejs/kit#1377]
https://github.com/sveltejs/kit/blob/d31eb667115f3bd1058a24eac8410a41f2e69c6f/packages/adapter-cloudflare-workers/index.js#L37

the following is my current configuration
```javascript
await esbuild.build({
    entryPoints: ['.svelte/cloudflare-workers/entry.js'],
    outfile: `${entrypoint}/index.js`,
    bundle: true,
    target: 'es2020',
    platform: 'browser' // TODO would be great if we could generate ESM and use type = "javascript"
});
```
this solves most of my problem when using supabase as they use websocket and other various things
when the project is compiled for node wrangler fail to build it as there is some ```require(...)```

so my question is the following.
is there some reason on why we are using node instead of browser?
because from my understanding the cloudflare workers implements a browser like enviroment. so to me make sense to use a build that is compatible with the browser

**Comment by Rich-Harris** [comment]
The issue is that many people will include dependencies that require a Node-like environment; I forget the specifics but in some early tests is proved necessary to bundle the SvelteKit output with webpack (via wrangler) to get stuff to work. Not yet 100% sure what the universal solution is

**Comment by jwrunner** [comment]
> necessary to bundle the SvelteKit output with webpack (via wrangler)

If this is helpful as a reference, I'm using adapter-cloudflare-workers to deploy a production app using just `svelte-kit build` and `wrangler publish` - I don't need to run `wrangler build` and am able to use `type = "javascript"` in my wrangler.toml just fine  https://github.com/HVSBible/hvsb/blob/main/wrangler.toml#L2 with Wrangler v1.15.1

**Comment by ignatiusmb** [comment]
esbuild config for cloudflare adapter (and other serverless platforms) can now be configured, https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare-workers/README.md#esbuild.
