### ISSUE TITLE
Named export 'parse' not found. The requested module 'node-html-parser' is a CommonJS module, which may not support all module.exports as named exports.

### ISSUE THREAD

**Issue by IRediTOTO** [sveltejs/kit#1379]
**Describe the bug**
Hi, in my end point. I just import norman like this 
`import { parse } from 'node-html-parser';`
 Everything run well on dev mode `npm run dev`

Then I run `npm run build` no error too
but on `npm run preview` 

console fire this error

**Logs**
```
> Named export 'parse' not found. The requested module 'node-html-parser' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'node-html-parser';
const {parse} = pkg;
```

**To Reproduce**
I don't think need it, but tell me if you need

**Expected behavior**
Just need it run smooth :c

**Comment by babichjacob** [comment]
Closing for being a support question rather than a bug with SvelteKit. I'd also suggest upgrading to Node 14.16.1 if not 16.1.0 to solve this (because I've seen that be the reason for issues with a similar error message).
