### ISSUE TITLE
Loading does not finish when starting with Skeleton project.

### ISSUE THREAD

**Issue by shoNagai** [sveltejs/kit#1384]
**Describe the bug**
When I start the Svelte app, which is a project created using the template Skeleton project, the site does not stop loading.

**Logs**
<img src="https://i.gyazo.com/66021a688a55c1eda7c7f57fcf4a42f4.gif" width="320"/>
<img src="https://user-images.githubusercontent.com/22911189/117542812-1b337d00-b055-11eb-8fdb-4495e26cf8e5.png" width="320"/>

**Expected behavior**
The site should complete loading.

**Stacktraces**
I will post the log after installation.
<details>
  <summary>Stack trace</summary>
Sho:module nagaishou$ npm init svelte@next my-page
npx: 5個のパッケージを2.765秒でインストールしました。

create-svelte version 2.0.0-next.70

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

If you encounter a problem, open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › Skeleton project
✔ Use TypeScript? … No / Yes
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Copied project files
✔ Added TypeScript support. To use it inside Svelte components, add lang="ts" to the attributes of a script tag.
✔ Added ESLint.
Readme for ESLint and Svelte: https://github.com/sveltejs/eslint-plugin-svelte3
✔ Added Prettier.
General formatting options: https://prettier.io/docs/en/options.html
Svelte-specific formatting options: https://github.com/sveltejs/prettier-plugin-svelte#options

Want to add other parts to your code base? Visit https://github.com/svelte-add/svelte-adders, a community project of commands to add particular functionality to Svelte projects

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>
 System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 187.16 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - ~/.nodenv/versions/14.15.4/bin/node
    Yarn: 1.22.10 - ~/.nodenv/versions/14.15.4/bin/yarn
    npm: 6.14.10 - ~/.nodenv/versions/14.15.4/bin/npm
  Browsers:
    Brave Browser: 80.1.4.96
    Chrome: 90.0.4430.93
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.102
    svelte: ^3.34.0 => 3.38.2
</details>

**Severity**
It didn't happen with the other template, so I don't think it's that serious.

**Comment by raprocks** [comment]
Aren't the warning from your extensions not being loaded or something. Try doing a Shift + F5 or hard refresh. Maybe that can help?

**Comment by shoNagai** [comment]
> Aren't the warning from your extensions not being loaded or something. Try doing a Shift + F5 or hard refresh. Maybe that can help?

Thank you.
I also tried a hard refresh, but it didn't help.

**Comment by mattiash** [comment]
I tried reproducing this. I started with `npm init svelte@next svelte-kit-test`, made the following choices:

- Skeleton project
- Typescript Yes
- Eslint Yes
- Prettier Yes

I then did `npm install` and `npm run dev`. 

I tried both Firefox and Safari and both of them finish loading `http://localhost:3000` correctly. I cannot reproduce this issue.

@shoNagai can you try reproducing the problem again from a clean skeleton? Do you perhaps have any browser plugins that is causing issues? Maybe try with a browser in Private mode.


```
npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers
npx: installed 1 in 0.806s

  System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
    Memory: 129.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Firefox: 89.0
    Safari: 14.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.102
    svelte: ^3.34.0 => 3.38.2
```

**Comment by Conduitry** [comment]
This looks environmental. The first warning in the screenshot is from Svelte and is harmless, but the other ones are from browser extensions. A GitHub issue isn't the right place to try to be debugging something with your setup.
