### ISSUE TITLE
Duplicate <main> on navigation (in dev only)

### ISSUE THREAD

**Issue by maxime-pigeon** [sveltejs/kit#1392]
**Describe the bug**
The `<main>` element gets duplicated after navigating to another page. Then only the second `<main>` gets updated when I make a change to a file. This only happens in development. Everything is fine once I build and preview. And weirdly all seems to work fine for a while after I build and go back to dev. Probably a bug with vite? I get a bunch of `Failed to load resource: Could not connect to the server.` in the console.

**To Reproduce**
Repo: https://github.com/maxime-pigeon/vc-prototype2/tree/master/src/routes

In `__layout.svelte`:

```
<main>
	{#each labs as lab}
		<section
			class:selected={$page.path.includes(lab.id)}
			style="--labColor: {lab.color}"
		>
			<a href={`/${lab.id}`}>{lab.name}</a>
			{#if $page.path.includes(lab.id)}
				<div transition:fade={{ duration: 250 }}>
					<Header currentLab={lab.id} />
					<slot />
				</div>
			{/if}
		</section>
	{/each}
</main>
```

**Expected behavior**
`<main>` doesn't duplicate in dev.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>
System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 267.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
  Browsers:
    Brave Browser: 90.1.24.82
    Firefox: 88.0.1
    Safari: 14.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.102 
    svelte: ^3.38.2 => 3.38.2 
    vite: ^2.2.3 => 2.2.4 

The bug can be replicated regardless of the browser.
</details>

**Severity**
Annoying

**Comment by benmccann** [comment]
Please note that you can triple quote the whole code block rather than single quoting each line. I've updated your post for you

**Comment by maxime-pigeon** [comment]
Ah thank you, the template string was messing with the code block. I hope you were able to reproduce the bug. It's weird it takes a few modifications to the files before it starts happening. Let me know if I can be of any help.

**Comment by benmccann** [comment]
I would guess that your issue is coming from `<slot />` being located in an `{#each}` block. It should not generally be located in an `{#each}` or `{#if}`. Most of that code would generally be located in a child page like `index.svelte`. You might find Discord to be a better place for this type of issue

**Comment by maxime-pigeon** [comment]
Ok, sorry about that. I wasn't sure if it was something I was doing incorrectly or not, but since the issue doesn't appear once I build I thought it might be a bug. If not, we can close the issue.

**Comment by benmccann** [comment]
I would be surprised if it's a bug because probably other people would have hit it in that case
