### ISSUE TITLE
Nested error pages are not used

### ISSUE THREAD

**Issue by raprocks** [sveltejs/kit#1393]
**Describe the bug**
The Error page do not behave as written in the docs about them. They should render the one in the subdirectories but instead fallback to the root error page instead.

**Logs**
No Logs Encountered

**To Reproduce**
```powershell
git clone https://github.com/raprocks/error-repro.git
npm i
npm run dev -- --open
```

**Expected behavior**
the respective level error pages should be rendered but arent

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 1.67 GB / 7.84 GB
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (89.0.774.63)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.102
    svelte: ^3.34.0 => 3.38.2

Browser = Edge - Chromium Based
</details>

**Severity**
The Whole Error pages information from the docs is being proven wrong. Svelte feature being broken.

**Comment by damain** [comment]
I am guessing that the place where this should be implemented is [here](https://github.com/sveltejs/kit/blob/79b4fe2e50416c135b895f19b6faffd4eedf25a3/packages/kit/src/runtime/server/page/respond.js#L1610) line :161

Currently says: 					
```
// TODO backtrack until we find an __error.svelte component
// that we can use as the leaf node
// for now just return regular error page
```

**Comment by damain** [comment]
Created a failing test 7315619dcb7bc4eabf5f65fc2bb77e020457cc6e for this issue
