### ISSUE TITLE
Configure Gitpod as a single-click option to contribute

### ISSUE THREAD

**Issue by mikenikles** [sveltejs/kit#1394]
**Is your feature request related to a problem? Please describe.**
To contribute to SvelteKit, one needs to follow the instructions in the `README.md` file. This currently requires `pnpm` installed globally and a `build` & `test` step. This adds potential friction to the onboarding process.

**Describe the solution you'd like**
Automated, ephemeral development environments that run in the browser, allowing anyone to click a button in the `README.md` to open a new development environment in a browser tab. This solution is based on www.gitpod.io and will leverage [Prebuilds](https://www.gitpod.io/docs/prebuilds) which run the `build` and `test` scripts automatically for each new commit. By the time a user starts a new development environment, the system already executed the scripts and the user is ready to contribute, regardless of their operating system or device they use (Chromebook, iPad, Mac, Windows, etc.)

**Describe alternatives you've considered**
A script that automates the above tasks. This would have to be tweaked to make sure it runs on various operating systems.

**How important is this feature to you?**
I've worked with ephemeral development environments since 2019 and use it for all my work. Initially on a Chromebook, now on a MacBook and sometimes on an iPad. I truly believe ephemeral development environments lower the friction for contributors and make developers more productive.

**Additional context**
I work at Gitpod and recently talked on the Svelte Radio [episode 26](https://share.transistor.fm/s/507ad528) where I outlined the benefits of Gitpod and how we use it for the Gitpod website development.

This is an opt-in feature and the development setup instructions can still be executed locally should developers prefer that. Using Gitpod adds an option for people who prefer to work that way.

**Comment by Conduitry** [comment]
Closing, see comments on #1395.
