### ISSUE TITLE
Typescript error on custom events fired by sveltekit

### ISSUE THREAD

**Issue by TheComputerM** [sveltejs/kit#1399]
![image](https://user-images.githubusercontent.com/24741538/117614519-0b678600-b186-11eb-9238-18efd22260e6.png)

Everything works fine but errors are very annoying.

**Comment by dummdidumm** [comment]
Please fill out the issue template and provide a copy paste able snippet. Also make sure that this is really related to SvelteKit

**Comment by TheComputerM** [comment]
@dummdidumm updated the issue, but still not 100% sure if this is a problem with sveltekit or language-tools
