### ISSUE TITLE
[HELP 🔥] Navigating between pages (page/[slug].svelte)

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/kit#1401]
Hello ! 

i create a Dynamic page svelte 

```
page/[slug].svelte
page/[slug].json.js
```

The json is in the load function in the [slug].svelte
when i change page using a href , its change the link 
first link click its work fine , change the content,

but after that the next clicks are not changing the page content , 
its just change the link

I did try search and i didnt found any answer about this yet ! 

any help  
Thanls

**Comment by Kapsonfire-DE** [comment]
maybe you give us some code of your endpoint/component
