### ISSUE TITLE
The request url "/service-worker.js" is outside of vite dev server root

### ISSUE THREAD

**Issue by m4rch3n1ng** [sveltejs/kit#1414]
**Describe the bug**

when using svelte-kit vite throws an error.

**Logs**

```
09:42:39 [vite] Internal server error: The request url "/service-worker.js" is outside of vite dev server root "C:/Users/.../test".    
      For security concerns, accessing files outside of workspace root is restricted since Vite v2.3.x. 
      Refer to docs https://vitejs.dev/config/#server-fsserveroot for configurations and more details.
```

**To Reproduce**

run

`$ npm init svelte@next`

select the demo app, no extra features and run

`$ npm run dev`

**Expected behavior**

the error should not exist

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

-  System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 7.24 GB / 15.93 GB
  Binaries:
    Node: 16.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.56)
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.104
    svelte: ^3.34.0 => 3.38.2

- adapter-node

</details>

**Severity**

i needed to downgrade vite manually to use sveltekit again

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by m4rch3n1ng** [comment]
i used the official demo app and was able to reproduce

i have not added a service-worker.js file myself

**Comment by GrygrFlzr** [comment]
The official demo app does not come with a service worker, you may need to check if you have a service worker registered on your browser's localhost and unregister it.

- Chrome: `chrome://serviceworker-internals`
- Edge: `edge://serviceworker-internals`
- Firefox: `about:debugging#workers`

**Comment by m4rch3n1ng** [comment]
oh yeah that fixes it, thank you
