### ISSUE TITLE
NOENT: Tries to import .ts file from node_modules during dev

### ISSUE THREAD

**Issue by MarcusCemes** [sveltejs/kit#1415]
**Describe the bug**
Importing a subpath export from a package is trying to resolve a `.ts` file during development (`npm run dev`). The `exports` field in the `package.json` points to a `.js` file. See additional context for more information.

**Logs**
```text
ENOENT: no such file or directory, open '/sandbox/node_modules/true-myth/dist/es/maybe.ts'
```
That's the information given in the browser and the console, it also returns a 500 status code.

`true-myth`'s patched `package.json`:
```json
"exports": {
  "./maybe": {
    "default": "./dist/es/maybe.js",
    "node": "./dist/cjs/maybe.js"
  }
}
```

**To Reproduce**

[![Edit sveltekit-import-bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sveltekit-import-bug-8771q?fontsize=14&hidenavigation=1&theme=dark)

This is from a new skeleton project created with `npm init svelte@next`. The sandbox is a little glitchy. It may require a server restart to bind to the right port, and not the HMR WebSocket. It's recommended to download it as a ZIP. Reproducable on Windows and Linux.

 **You may have to manually patch the dependency in `node_modules` in the sandbox**, awaiting a PR I've submitted to `true-myth`. I've provided a handy Node.js script called `PATCH.js`.

**Expected behavior**
The import should be correctly resolved according to the `exports` field.

**Stacktraces**
No stack trace was provided by the error, I'll try digging around later with `DEBUG=*` and random `console.log` statements in Vite to see what's going on.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`

```text
  System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 4.63 GB / 62.73 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.104
    svelte: ^3.38.2 => 3.38.2
```

- Your browser
Latest version of Chrome.

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Static adapter, but no adapter is required for the development reproduction.

</details>

**Severity**
It's not major, I can get by with a manual implementation for now. I have had a lot of trouble anything into a SvelteKit application, this may get us one step closer to better library support 😁

**Additional context**
My apologies if this is related to another issue, I couldn't find anything. Furthermore, this doesn't seem to be a Vite issue as I have been able to create a new Vite/Vue application and import `true-myth/maybe` in development correctly.

The project builds correctly using the static adapter and can be served in production. Typescript is enabled for the SvelteKit project, but the import is from an ordinary `<script>` tag.

I have an ongoing PR with `true-myth` to add an `exports` field to their `package.json` (https://github.com/true-myth/true-myth/pull/126) to correctly resolve the subpath imports of `true-myth/maybe` and `true-myth/result`. There may be another misconfiguration in the `package.json` relating to ES that I'm not aware of. Is there anything else that should be added for optimal ES support? They have full ES builds, their package structure is a little unconventional (https://github.com/true-myth/true-myth/issues/102).

I have tried all sorts of combinations to try importing `true-myth/maybe`, setting `"type": "module"` in their `package.json`, manually importing from `dist`, importing ES and CJS, moving the files to the root of the package, exporting each file from a root `index.js`, importing the source `.ts` files, each time I get a different error, usually related to Rollup not being able to find the module. This is the only way I have managed to get the project to build at all, although why it's trying to import a `.ts` file is beyond me.

Thank you for the amazing work you have done already with SvelteKit!

**Comment by benmccann** [comment]
My guess is that it's because `true-myth`'s source map is broken. I've seen Vite crash when it encounters a broken source map. There's probably some other error as well. When you hit that issue Vite tries to use the source map to tell you where the error is located and then just crashes.

E.g. I see this in their `index.d.ts` file:
```
{"version":3,"file":"index.d.ts","sourceRoot":"./","sources":["index.ts"],"names":[],"mappings":"AAAA;;;GAGG;AAEH,OAAO,KAAK,cAAc,MAAM,SAAS,CAAC;AAC1C,oBAAY,KAAK,CAAC,CAAC,IAAI,OAAO,SAAS,EAAE,KAAK,CAAC,CAAC,CAAC,CAAC;AAClD,eAAO,MAAM,KAAK,uBAAiB,CAAC;AAEpC,OAAO,KAAK,eAAe,MAAM,UAAU,CAAC;AAC5C,oBAAY,MAAM,CAAC,CAAC,EAAE,CAAC,IAAI,OAAO,UAAU,EAAE,MAAM,CAAC,CAAC,EAAE,CAAC,CAAC,CAAC;AAC3D,eAAO,MAAM,MAAM,wBAAkB,CAAC;AAEtC,OAAO,KAAK,aAAa,MAAM,QAAQ,CAAC;AACxC,oBAAY,IAAI,GAAG,OAAO,QAAQ,EAAE,IAAI,CAAC;AACzC,eAAO,MAAM,IAAI,sBAAgB,CAAC"}
```

I think that's an invalid path in for `sources`. There's no `index.ts` in the package root. I see one in `src/index.ts` though
