### ISSUE TITLE
[vite] Internal server error: The request url "/api" is outside of vite dev server root

### ISSUE THREAD

**Issue by vfilatov** [sveltejs/kit#1420]
**Describe the bug**
After updating to Vite v2.3.0 I receive the following error:
`[vite] Internal server error: The request url "/api" is outside of vite dev server root "/tmp/bug". 
      For security concerns, accessing files outside of workspace root is restricted since Vite v2.3.x. 
      Refer to docs https://vitejs.dev/config/#server-fsserveroot for configurations and more details.`

**To Reproduce**
```
mkdir /tmp/bug && cd /tmp/bug
npm init svelte@next # all defaults
npm install
mkdir src/routes/api
cat <<EOF > src/routes/api/index.js
export async function get () {
  return {
    body: "World"
  }
}
EOF

cat <<EOF > src/routes/bug.svelte
<script>
import { onMount } from 'svelte';

let name;
onMount(async () => {
  const resp = await fetch("/api");
  name = await resp.text();
})
</script>

Hello, { name }
EOF
```
run server `npm run dev` navigate browser to http://localhost:3000/bug

observe error on the console
```3:07:54 PM [vite] Internal server error: The request url "/api" is outside of vite dev server root "/tmp/bug". 
      For security concerns, accessing files outside of workspace root is restricted since Vite v2.3.x. 
      Refer to docs https://vitejs.dev/config/#server-fsserveroot for configurations and more details.
      at ensureServingAccess (/tmp/bug/node_modules/vite/dist/node/chunks/dep-c9ea388d.js:57841:15)
      at transformRequest (/tmp/bug/node_modules/vite/dist/node/chunks/dep-c9ea388d.js:57883:17)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async viteTransformMiddleware (/tmp/bug/node_modules/vite/dist/node/chunks/dep-c9ea388d.js:58069:32) (x4)
```

**Expected behavior**
not having such error

**Comment by JustinVoitel** [comment]
I tried several cases and renaming the endpoint from index.ts to index.json.ts and calling fetch("/api.json") solved the issue for me.

**Comment by xferqr** [comment]
It works for me: 
try create **"static/service-worker.js"** file

**Comment by dominikg** [comment]
that check has been disabled by default in vite 2.3.1, so if you are seeing this issue, please update

**Comment by wiesson** [comment]
> that check has been disabled by default in vite 2.3.1, so if you are seeing this issue, please update

Btw, it looks like that `^1.0.0-next.105` does not include the pinning to Vite version 2.2.4 - could you release that as well?

**Comment by dominikg** [comment]
https://github.com/sveltejs/kit/pull/1429

**Comment by wiesson** [comment]
Hmm, maybe something is wrong with my setup, but I still see this error (in development). I also tried to add 

```
fsServe: {
  strict: false,
},
```

**Comment by ignatiusmb** [comment]
I can't reproduce with the latest version, no errors are being logged in the console anymore.
