### ISSUE TITLE
Request: forcing a component to persist in memory when navigating away

### ISSUE THREAD

**Issue by austlee** [sveltejs/kit#1424]
**Is your feature request related to a problem? Please describe.**
Mapping libraries such as mapbox take about a second to load during navigation, even when all files are cached and running in offline mode, which feels distinctly un-app-like.

**Describe the solution you'd like**
If there are use cases where a component is heavy to mount and it is preferred that the component live in memory, perhaps it could be flagged as such to the router to improve its load on return.

**Describe alternatives you've considered**
It seems like a store would be the right solution for simple data within a component, but with a map canvas I don't see an obvious way to put it in a store.

The best alternative I've found is to have that heavy component live in $router.svelte and make it invisible when necessary, which is an inelegant solution. 

**How important is this feature to you?**
Somewhat, my solution works fine but is hackish.

**Comment by lukasIO** [comment]
I see the same need, but would think that it  could be a svelte feature and not a svelte-kit feature.
It might be equally benefitial in some cases to keep components in memory that are part of a conditional statement in svelte.

Just for reference, vue calls this `keep-alive` and solves it with a wrapper component. https://v3.vuejs.org/api/built-in-components.html#keep-alive

**Comment by Rich-Harris** [comment]
Persisting _components_ in memory is a can of worms, and likely to lead to all sorts of bugs (and would need fundamental changes to how Svelte works). But you can do this sort of thing in userland:

```svelte
<script context="module">
  let cached_mapbox_instance;
</script>

<script context="module">
  let container;
</script>

<script>
  import { onDestroy } from 'svelte';
  import mapbox from 'mapbox-gl';

  export let lat;
  export let lon;
  export let zoom;

  let div;
  let map;

  function load() {
    if (!container) {
      container = document.createElement('div');
      map = new mapbox.Map({
        container,
        style: 'mapbox://styles/mapbox/streets-v9'
      });
    }

    map.setCenter([lon, lat]);
    map.setZoom(zoom);

    div.append(container);
  }
</script>

<div bind:this={div}></div>
```

**Comment by DeepDoge** [comment]
@austlee
One possible work around is handling the routing yourself and never really removing the page from the dom.
You check the `$page` on change, resolve the new URL yourself.
Then set `lastFoundPage` to the page your wanna view.
And set the `pageProps[YourPageComponent.name]` to props of the page, if it has any. if it doesnt set it to `{}`.
Handling routes yourself is better than handling it with sveltekit's router anyway. You can make routes for modals and stuff.

This way we mount the page when first go to that page and set it's props for the first time.
After that it just stays there and waits.

```html
<div style:display={lastFoundPage === A4 ? "block" : "none"}>
    {#if pageProps[A4.name]}
        <svelte:component this={A4} {...pageProps[A4.name]} />
    {/if}
</div>
<div style:display={lastFoundPage === Index ? "block" : "none"}>
    {#if pageProps[Index.name]}
        <svelte:component this={Index} {...pageProps[Index.name]} />
    {/if}
</div>
<div style:display={lastFoundPage === Post ? "block" : "none"}>
    {#if pageProps[Post.name]}
        <svelte:component this={Post} {...pageProps[Post.name]} />
    {/if}
</div>
<div style:display={lastFoundPage === Profile ? "block" : "none"}>
    {#if pageProps[Profile.name]}
        <svelte:component this={Profile} {...pageProps[Profile.name]} />
    {/if}
</div>
<div style:display={lastFoundPage === Topic ? "block" : "none"}>
    {#if pageProps[Topic.name]}
        <svelte:component this={Topic} {...pageProps[Topic.name]} />
    {/if}
</div>
```
Or you can come up with your own solution, maybe by using `#each` and stuff.
