### ISSUE TITLE
Typescript: Cannot find module '$app/env' or its corresponding type declarations

### ISSUE THREAD

**Issue by pikeas** [sveltejs/kit#1426]
**Describe the bug**
Typescript can't resolve anything in $app (env, stores, etc).

**To Reproduce**
Happening with latest create-svelte.

Looks like this can be fixed by editing global.d.ts to include:

```
// / <reference types="svelte" />
```

This was previously in the template and was removed without comment, so I'm not sure whether there are unintended consequences to adding it back.

**Comment by pikeas** [comment]
I was wrong about my fix, the error went away when I reloaded the Svelte language server in VS Code, but returned the next time TS was triggered.

**Comment by dummdidumm** [comment]
I can't reproduce this with the latest version on Windows 10. I created the starter template with the todo app and said "yes" to "add TypeScript?". I can import `$app/X` just fine in both Svelte and TS files.

**Comment by pikeas** [comment]
I figured it out, it's actually...a linter issue.

src/global.d.ts:

```
/// <reference types="@sveltejs/kit" />
```

My lint config includes https://eslint.org/docs/rules/spaced-comment, which replaces `///` with `// /`, which breaks the types reference. Is it worth adding a comment to this file in the template about keeping exactly `///`?

**Comment by pikeas** [comment]
I'm also not sure how to make ESLint aware of `$app`. When using import validation rules, this trips `import/no-unresolved`.

**Comment by ignatiusmb** [comment]
I can't figure out where the bug is, and I'm hoping that this is already resolved on your side. In any case, please close with the solution or make a small repro of the bug.

**Comment by ignatiusmb** [comment]
You shouldn't need to reference anything inside `node_modules` directly, I took a quick look of the repo and saw you have an invalid `global.d.ts` containing [these lines](https://github.com/sorenabedi/artist-svelte/blob/f4e25d6ce599a8fa059d44ac9f1addac07f56578/src/global.d.ts)

```ts
declare module '**/*.svelte';
/// <reference types="@sveltejs/kit" />
```

> Triple-slash directives are **only** valid at the top of their containing file.
> https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html

Please make sure to always test these bugs with the latest skeleton starter, we should only need this line for everything to work out-of-the-box

https://github.com/sveltejs/kit/blob/7fab7f67a4643715586693cf01fd4d43f54671d0/packages/create-svelte/templates/skeleton/src/global.d.ts#L1
