### ISSUE TITLE
How to serve static images, files, svgs with node-adapter

### ISSUE THREAD

**Issue by yassinrais** [sveltejs/kit#1427]
Hello Svelte Team!

i was wondering is there any one to serve a static folder with images, svg, etc ...

Using the node adapter ? 

Thanks.

**Comment by Kapsonfire-DE** [comment]
Create static folder right next to your src folder. Content inside this is copied over to the root on build

**Comment by babichjacob** [comment]
Closing this for being a support question and not following the issue template. 

As mentioned, use the `static` folder like the SvelteKit demo app (that can be chosen during the initialization process (`npm init svelte@next`)) shows. Further (albeit minimal) reading: https://kit.svelte.dev/docs#configuration-files

**Comment by yassinrais** [comment]
But the issue is that when im developing the src is static , but in generated build its assets

is there any way to rewrite that assets to static in dev mode ?

**Comment by babichjacob** [comment]
If you're writing your paths as `/static/image.png`, it's just `/image.png` for it to work correctly in both dev and prod.

**Comment by yassinrais** [comment]
Oh i see ! thanks ✨
