### ISSUE TITLE
SvelteKit cli overlapping parameter shortcut -h

### ISSUE THREAD

**Issue by Kage0x3B** [sveltejs/kit#1432]
**Describe the bug**
The "svelte-kit" cli commands dev, preview and start have overlapping parameter shortcuts for the host parameter and the help, both shortcuts are `-h`. When using the shortcut, the help is always displayed and the command exits.
(Using `--host` instead works)

**Logs**

```bash
$ npx svelte-kit dev -ho

  Description
    Deprecated — use svelte-kit preview instead

  Usage
    $ svelte-kit start [options]

  Options
    -p, --port     Port  (default 3000)
    -h, --host     Host (only use this on trusted networks)  (default localhost)
    -H, --https    Use self-signed HTTPS certificate  (default false)
    -o, --open     Open a browser tab  (default false)
    -h, --help     Displays this message

```

**To Reproduce**

- Execute the dev command `npx svelte-kit dev -ho` in any SvelteKit project.
- It should then only show the help message.

**Expected behavior**
The development server starts, binds to 0.0.0.0 because of the `-h` parameter and launches the browser `-o`

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 AMD FX(tm)-8350 Eight-Core Processor
    Memory: 790.58 MB / 11.68 GB
    Container: Yes
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107 
    svelte: ^3.34.0 => 3.38.2 
    vite: ^2.2.4 => 2.3.1
</details>

**Severity**
Low, `--host` parameter can be used instead, just a small annoyance which might confuse users.

**Comment by dberesford** [comment]
I had thought about simply removing the '-h' shortcut for '--help' as a proposed solution but when I look in to it, although the cmd line opts are set here: 

https://github.com/sveltejs/kit/blob/c6fde9932f81ddee09762eca8cd6530255ffec14/packages/kit/src/cli.js#L75

the `-h --help` is hard coded in the sade package:

https://github.com/lukeed/sade/blob/89f7377442a38fa90e51abf4f953e14af0f2f2cf/lib/utils.js#L44

**Comment by jthegedus** [comment]
This was introduced in https://github.com/sveltejs/kit/pull/834

The code sample in Sade's docs - https://github.com/lukeed/sade#single-command-mode - suggests `-H` for `--host`.

Given `--host` was implemented before `--https` my suggestion would be to change `--https` alias from `-H` to `-S`.

**Comment by benmccann** [comment]
I'm used to `-h` for host. E.g. that's what the `mysql` and `psql` command-line clients do. They use `-?` for help. I filed https://github.com/lukeed/sade/issues/47 over in the sade repo

**Comment by Rich-Harris** [comment]
I think `-h` for `--help` is pretty universal (see `node -h`, `npm -h`, etc). I like `-H, --host` and `-S, https`

**Comment by Rich-Harris** [comment]
Then again, it's a tricky breaking change (if someone was already using `-H` for `--https`, we'd have no way of knowing that they meant `-S` and not `--host`.) Am wondering if we shouldn't just remove those shortcuts and make it less ambiguous
