### ISSUE TITLE
[adapter api]: pass svelte.config.js config object to adapter

### ISSUE THREAD

**Issue by jthegedus** [sveltejs/kit#1435]
**Is your feature request related to a problem? Please describe.**

The [Firebase adapter](https://github.com/jthegedus/svelte-adapter-firebase) reads a provided `firebase.json` configuration to determine destination dirs for `utils.copy_{static/client}_files` etc.

If the destination dir defined in `firebase.json` is the same as the `svelte.config.js:kit.files.assets` dir then we end up with a mess of a dir similar to the issue I am experiencing from https://github.com/sveltejs/kit/issues/587

**Describe the solution you'd like**

Either:

- **preferred solution** `utils.copy_{static/client}_files` error when the destination dir is the same as the source dir (notably this misses `utils.prerender`, but calling prerender after the other copies would be enough)
- the adapter receives the SvelteKit config object so these types of checks can be made within the adapter without having to read in the config file itself

**Describe alternatives you've considered**

**How important is this feature to you?**

It will help reduce noise from known causes in the adapter workflow if I can nudge my users properly

**Additional context**

https://github.com/jthegedus/svelte-adapter-firebase/issues/56 is the tracking issue for identifying this conflict of a matching `source:dest` for static assets.

[update] I have temporarily worked around this by reading the `svelte.config.js` in the adapter, though obviously not ideal as it's the source config and not the computed final config.

**Comment by benmccann** [comment]
@jthegedus any chance you'd want to send a PR for this?

I think we could do something like:

```
return {
  adapt(utils, config) {
    ...
  }
};
```

**Comment by jthegedus** [comment]
Happy to create the PR 😁

Would an object be preferable?

```diff
-adapt(utils, config) {
+adapt({ utils, config }) {
```

Would break all adapters once, then never again should something like this come up

**Comment by benmccann** [comment]
Yes, that's a good idea. We've tried to follow that pattern generally, but I guess we missed doing it here
