### ISSUE TITLE
How to perform a client-side redirect after 401

### ISSUE THREAD

**Issue by Buraburaite** [sveltejs/kit#1437]
I currently have this in my `__layout.svelte`:

```js
<script context="module">
    export const load = async ({ page, session }) => {
	
    if (!session?.user && page?.path.slice(-7) !== '/public') {
        console.log('redirecting');
        // NOTE 'public' is just a temporary convention for a public page
        // NOTE the correct status code for this 401, but SvelteKit will not redirect
        // if the status code is not 3xx.
        return { status: 302, redirect: '/prepped/public' };
    }
    return {};
}
</script>
```

If I'm understanding status codes correctly, if the user is not logged in and tries to access a page that they have to be logged in to view, then they should get 401 and not 302. However, SvelteKit requires a 3xx status code, and will refuse to redirect otherwise (I tried).

Put another way, is there a recommended solution for a loggedIn route guard? Or at least a direction to go in? I have spent all day on this and still don't get it (only started using SvelteKit this week), but I did try out `handle` and `goto` as well, which I now know don't work for this.

I mean, 302 works, but I guess I'm being a bit of a perfectionist and wondering if I'm still missing something. The docs specifically mention this use case as well: https://kit.svelte.dev/docs#loading-output-redirect

**Comment by Conduitry** [comment]
If you want to show the user an error message, that would be a 4xx response. If you want to redirect the user to the login page, that would be a 3xx response.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
