### ISSUE TITLE
Infinite loop when accessing urls  directly

### ISSUE THREAD

**Issue by oratoran** [sveltejs/kit#1440]
Hi,

I have prepared the sveltekit site and deployed to netlify (with netlify adapter) and when I try to access certain urls directly it goes 301 loops.

I thought the problem cause of netlify settings and then removed the adapter and deployed to vercel (with vercel adapter) and nothing changed.

Here is the repo: https://github.com/oratoran/blkjeans
And the site at vercel: https://blkjeans.vercel.app/

But at 'npm run dev' works without any problem.

Any clue and suggesstion please?

Thanks

**Comment by Conduitry** [comment]
This is presumably the same as #1346 and can be resolved with the `trailingSlash` option.

**Comment by oratoran** [comment]
> This is presumably the same as #1346 and can be resolved with the `trailingSlash` option.

I have added vercel.json with trailingSlash: false but nothing changed.

I have tried to add trailingSlash: 'ignore' to svelte config file but when 'npm run dev' it gives error: 
Unexpected option config.kit.trailingSlash

What is expected options for it? Thanks

**Comment by Conduitry** [comment]
According to your lockfile, you're on Kit version next.103, and `trailingSlash` wasn't added until next.105 - https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next105

**Comment by oratoran** [comment]
deleting lockfile and npm install worked. Thanks
