### ISSUE TITLE
Ability to prerender to `about.html` instead of `about/index.html` like Sapper

### ISSUE THREAD

**Issue by bdadam** [sveltejs/kit#1443]
**Describe the bug**
When setting `tralilingSlash: 'ignore'` then the static adapter generates wrong files, e.g.

- `blog/hello-world.html.svelte` is generated as `blog/hello-world.html/index.html`
- `about.svelte` is generated as `about/index.html`

**To Reproduce**
Here is a repo with issue reproduction, generated files are also pushed to the main branch in `dist` directory: https://github.com/bdadam/svelte-kit-static-issue

The repo was freshly created with `npm init svelte@next .`.

**Expected behavior**

- `blog/hello-world.html.svelte` => `blog/hello-world.html.html`
- `about.svelte` is generated as `about.html`

**Information about your SvelteKit Installation:**

- The repo was freshly created with `npm init svelte@next .`
- `yarn add -D @sveltejs/adapter-node@next` to install the static adapter

**Severity**
For me this is a blocker in adopting Svelte Kit for one side project. I have a website which has 6+ years old URLs with .html extensions, e.g. `https://example.com/blog/hello-world.html`. I don't want to touch these URLs due to all the SEO rank and backlinks they received throughout the years. In all honesty this is a toy project - but I guess I'm not alone with this requirement.

**Comment by babichjacob** [comment]
>     * `about.svelte` is generated as `about/index.html`
> 

This is correct / intended: https://kit.svelte.dev/docs#ssr-and-javascript-prerender-route-conflicts


>     * `blog/hello-world.html.svelte` is generated as `blog/hello-world.html/index.html`
> 

This is (possibly?) not.

**Comment by bdadam** [comment]
Is there really no way to get about.html to be generated from about.svelte?

**Comment by Conduitry** [comment]
A recent-ish new feature in Sapper was to have `foo.html.svelte` render to `foo.html` when exporting a static site (rather than `foo.html/index.html`), but apparently that didn't make its way into SvelteKit. I think that would be a reasonable enhancement.

**Comment by honai** [comment]
Hi, I also want to create non-indexed HTML file and I found this issue.

It would be useful if we could use a route which ends with .html , especially for custom 404 page for some platforms (See [Additional Information of my comment](https://github.com/sveltejs/kit/issues/1937#issue-946887614) ).

I made PR for this: #1939

**Comment by benmccann** [comment]
Rich suggested he'd like to see this done in SvelteKit with a new option rather than by renaming the file extension. I've closed the associated PR given that, but if anyone would like to take a stab at it with the new direction I'd be happy to take a look

**Comment by bfanger** [comment]
I've rebased [PR 2632](https://github.com/sveltejs/kit/pull/2632), any feedback that prevents merging this PR would be appreciated.

**Comment by bfanger** [comment]
In `@sveltejs/kit` version 1.0.0-next.**250** and up you'll be able to use the **prerender.createIndexFiles** setting.

> `createIndexFiles` - Set to false to disable subfolders for routes: instead of about/index.html render about.html

```js
// svelte.config.js
export default {
  kit: {
    ...
    prerender: {
      createIndexFiles: false,
    }
  }
}
```

**Comment by archoda** [comment]
Is this fixed? I am using "@sveltejs/adapter-static": "^1.0.0-next.28" and with trailingSlash: true but still gettting 'example.html' instead of '/example/index.html'

```
kit: {
    adapter: adapter(),
    serviceWorker: {
      files: () => {
        return ['static/lib', 'src/lib']
      }
    }
  },
  prerender: {
    default: true
  },
  trailingSlash: 'always',
  ```

**Comment by babichjacob** [comment]
@archoda Upgrade your packages to their latest versions.

**Comment by archoda** [comment]
> @archoda Upgrade your packages to their latest versions.

@babichjacob, Yes. I have done this. Stood-up a stand-alone test project and still getting the same results. Have the prerender in the config and the context module per page also.

Page-level
```
<script context="module">
        export const prerender = true;
</script>
```

svelte.config.js
```
kit: {
		adapter: adapter(),
		serviceWorker: {
			files: () => {
			return ['static/lib', 'src/lib']
			}
		},
	},
	prerender: {
		default: true,
		enabled: true,
	},
	trailingSlash: 'always',
```

package.json
```
"devDependencies": {
    "@sveltejs/adapter-auto": "^1.0.0-next.33",
    "@sveltejs/adapter-static": "^1.0.0-next.29",
    "@sveltejs/kit": "next",
    "svelte": "^3.44.0",
    "svelte-preprocess": "^4.10.4"
  },
```
