### ISSUE TITLE
@sveltejs/adapter-static: build is accessing 2 dev dependencies

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#1450]
**Describe the bug**
I'm using the adapter *@sveltejs/adapter-static* and did a `npm run build` which produced a *build* folder.

For my deployment, I execute `npm install --production` and then start the server with `node build`.
Now I get errors about missing dependencies.

My solution is to move
- `"@sveltejs/kit": "next"`
- `"svelte": "^3.34.0"`

from devDependencies to dependencies (package.json).

**Expected behavior**
Server is starting without errors.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
 <summary>Cannot find package ... got this for @sveltejs/kit and svelte</summary>
  > node build

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'svelte' imported from /opt/app/build/app.js
    at packageResolve (internal/modules/esm/resolve.js:655:9)
    at moduleResolve (internal/modules/esm/resolve.js:696:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:88:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:241:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)
    at link (internal/modules/esm/module_job.js:55:36) {
  code: 'ERR_MODULE_NOT_FOUND'
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 9.02 GB / 15.96 GB
  Binaries:
    Node: 16.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.62)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): @sveltejs/adapter-static
</details>

**Comment by Conduitry** [comment]
Presumably related to and will have a similar solution at #1428, which is a similar report for the Node adapter.

**Comment by babichjacob** [comment]
I'm really confused: there is no server when using the static adapter.

**Comment by Conduitry** [comment]
Actually, yeah, that's true. Whoops.

If you're using adapter-static, you shouldn't be installing server dependencies at all. You should just deploy the HTML/JS/CSS files that end up in the build output directory.

If you do need some server-side stuff, you should be conditionally prerendering certain pages and using (say) the Node adapter.

**Comment by Zerotask** [comment]
I just messed it up with the adapters while testing them out.
Although the problem still exists with **@sveltejs/adapter-node**

I just verified it and changed the 2 deps back to dependencies and deployed again. This will result in the exact same error I reported initially.

For **@sveltejs/adapter-node**
- "@sveltejs/kit": "next"
- "svelte": "^3.34.0"

are needed as (production) dependencies.
