### ISSUE TITLE
Symlinking into routes folder not working

### ISSUE THREAD

**Issue by Madd0g** [sveltejs/kit#1460]
**Describe the bug**
I want to be able to develop some code that can be used by more than one website. So I want the contents of `/routes` to be populated with some real files but symlinked folders too.

I try to symlink a local folder into `/routes/p` and access a markdown file from that folder:

**Logs**
I get this error:
```Cannot find module 'svelte/internal' from '<my-project>/src/routes/p'```

**To Reproduce**
I'm using a symlink on mac to link a folder into `/routes/p`

```bash
ln -s ~/path/to/markdown/folder ./src/routes/p
```

I'm using a very simple mdsvex config

```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
	extensions: [".svelte", ...mdsvexConfig.extensions],
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess({
			postcss: true,
		}),
		mdsvex(mdsvexConfig),

	],
	kit: {
		vite: {
                     ......
```

**Expected behavior**
There should be a way to configure `preserveSymlinks`. I dug into the [vite code](https://github.com/vitejs/vite/blob/8b5a6a855091e6f744cc7b886cf927d14dc74d50/packages/vite/src/node/utils.ts#L36) and it looks like this is hardcoded to false unless running from pnp or something?

If I hardcode it to true instead of false, my code works.

https://github.com/vitejs/vite/blob/8b5a6a855091e6f744cc7b886cf927d14dc74d50/packages/vite/src/node/utils.ts#L36-L49

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 31.20 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  npmPackages:
    @sveltejs/kit: 1.0.0-next.102 => 1.0.0-next.102
    svelte: ^3.34.0 => 3.38.2
```
</details>

**Severity**
I really want a way of putting `.svelte/.css/.md` files outside of /src to develop the implementation of the website separately from the content.

**Additional context**
I commented on [mdsvex issues](https://github.com/pngwn/MDsveX/issues/122#issuecomment-836489378) looking for an alternative solution to my problem.

**Comment by benmccann** [comment]
Can you file this issue in the Vite repo instead? Since the code you're referring to lives there I think that's where the code change would be necessary and there's not much we can do in SvelteKit
