### ISSUE TITLE
Error: Cannot find module '@sveltejs/app-utils/renderer' while building with vercel adapter

### ISSUE THREAD

**Issue by borsemayur2** [sveltejs/kit#1461]
**Describe the bug**
Getting `Error: Cannot find module '@sveltejs/app-utils/renderer'` on `pnpm run build` command with `vercel adapter`
**Logs**
```
pnpm run build                                                                                                                                                     ─╯ 

> ~TODO~@0.0.1 build /home/mb/my/career/svelte/sveltekit/personal-portfolio
> svelte-kit build

Cannot find module '@sveltejs/app-utils/renderer'
Require stack:
- /home/mb/my/career/svelte/sveltekit/personal-portfolio/node_modules/.pnpm/@sveltejs+adapter-vercel@1.0.0-next.0/node_modules/@sveltejs/adapter-vercel/index.js
Error: Cannot find module '@sveltejs/app-utils/renderer'

 ERROR  Command failed with exit code 1.
```
**To Reproduce**
Run code from following branch:
https://github.com/borsemayur2/personal-portfolio/tree/1-add-vercel-adapter
**Expected behavior**
Should be able to make the build for production deploy on vercel

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>
Require stack:
- /home/mb/my/career/svelte/sveltekit/personal-portfolio/node_modules/.pnpm/@sveltejs+adapter-vercel@1.0.0-next.0/node_modules/@sveltejs/adapter-vercel/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/mb/my/career/svelte/sveltekit/personal-portfolio/node_modules/.pnpm/@sveltejs+adapter-vercel@1.0.0-next.0/node_modules/@sveltejs/adapter-vercel/index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (6) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 518.70 MB / 5.59 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.volta/tools/image/node/14.16.1/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.12 - ~/.volta/tools/image/node/14.16.1/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107
    svelte: ^3.34.0 => 3.38.2

- Your browser
Firefox 88.0.1 (64-bit) 

- Your adapter : Vercel
</details>

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

Minor

**Additional context**
![image](https://user-images.githubusercontent.com/47341981/118385383-f5e1d880-b62b-11eb-9680-db4bbfcbb07d.png)

**Comment by makuzaverite** [comment]
the output directory is `.svelte-kit` not `.svelte`

**Comment by madeleineostoja** [comment]
I'm also facing this issue, nothing to do with the output directory on vercel

**Comment by madeleineostoja** [comment]
Note this issue was fixed for me by installing the `@next` version of `adapter-vercel` rather than `latest`

**Comment by jthegedus** [comment]
Please ensure you are using the latest version of SvelteKit and Adapter before reporting an issue as they are constantly changing and your problem may have been resolved.

`@latest` will not be updated until a full `1.0` release. Please use `@next` to get the newest Beta releases. 

- kit: `npm i -D @sveltejs/kit@next`
- adapter: `npm i -D @sveltejs/adapter-vercel@next`

You can check via `npm show @sveltejs/kit versions` or via the Changelogs in GitHub https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

**Comment by vhscom** [comment]
You [can now use](https://www.youtube.com/watch?v=SUrFDhhsJNo) `adapter-auto` (the default adapter) to deploy to Vercel.

```sh
npm view @sveltejs/adapter-auto@next version # 1.0.0-next.14
pnpm un @sveltejs/adapter-vercel && pnpm i -D @sveltejs/adapter-auto@next
sed -r 's/vercel/auto/g' svelte.config.js
vercel
```

![Screenshot from 2022-01-24 17-55-29](https://user-images.githubusercontent.com/97140109/150761011-475e2331-68a6-470b-8670-5b8fc0e9a2fa.png)

Project setup and deployment can be done entirely from the command line. But I give Steph credit for making it look easy with a prompt running half-way across her screen. :smile:
