### ISSUE TITLE
In __error.svelte in HN example load function improperly has error as an ionput

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [sveltejs/kit#1462]
Where would the error (type string or Error) be passed for the __error.svelte's load function?
I know LoadOutput outputs an optional error, but there is no place for it in LoadInput. Is it passed through context? If so, the docs should specify this.

**Comment by Shaun-Regenbaum** [comment]
So on further analysis, it seems that there exists two independent types for both LoadInput and LoadOutput depending on context. For normal cases we have LoadInput and LoadOutput, but for the __error.svelte we have ErrorLoadInput and ErrorLoadOutput, should these not be merged into a single type? 

Why don't we modify LoadInput to be: LoadInput & {
    status: number;
    error: Error;
}, so that there is only ever one type for loading as to reduce confusion. We may never need the Error for normal pages, but having two types implies that load will act differently depending on the context which doesn't seem like an ideal design.

**Comment by dummdidumm** [comment]
The docs mention this at https://kit.svelte.dev/docs#layouts-error-pages . I don't think it's a good solution to merge the types, it would lead to more confusion.

**Comment by Shaun-Regenbaum** [comment]
Maybe mentioning that there is a separate type in the docs would be helpful.
