### ISSUE TITLE
can't npm init svelte@next my-app, getting: Unexpected identifier

### ISSUE THREAD

**Issue by j2l** [sveltejs/kit#1475]
**Describe the bug**
Can't init a svelte kit on my laptop, freshly installed node and npm for hackathon. I'd like to use sveltekit for it.
It was wokring on desktop though.

**Logs**
npx: installed 5 in 1.582s
/home/pm/.npm/_npx/108100/lib/node_modules/create-svelte/bin.js:2
import fs from 'fs';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**To Reproduce**
npm init svelte@next my-app

**Information about your SvelteKit Installation:**

npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers
npx: installed 1 in 1.607s

  System:
    OS: Linux 5.11 Pop!_OS 20.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 176.65 MB / 7.67 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.4 - /usr/bin/npm
  Browsers:
    Chromium: 83.0.4103.116
    Firefox: 88.0.1

**Severity**
blocking my usage of SvelteKit entirely

**Comment by dummdidumm** [comment]
Your node version is too old. I suggest to install the latest 14.x or 16.x .

**Comment by j2l** [comment]
You're right.
deb packages are not maintained :)
installing [nvm](https://github.com/nvm-sh/nvm) and updating node just fixed it right now.
Thank you!

**Comment by Conduitry** [comment]
You need to upgrade Node. Version 10 is end-of-life, so you should be upgrading anyway.

**Comment by j2l** [comment]
I can't close the ticket

**Comment by pashute** [comment]
which version had you updated to?  In 2023 its node 19 and even 16 says it can only be run only with versions up to 12. Versions 11 and 12 have the same fs problem!
