### ISSUE TITLE
navigate always discard base path

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#1476]
I am building an adapter for ipfs (see https://github.com/wighawag/sveltejs-adapter-ipfs)
and currently I have to inject and modify svelte generated code.

My plan is to continue documenting the process so that svelte kit can accomodate it without requiring such code injection, which is obviously very brittle

On recent version of svelte kit I noticed this line :
https://github.com/sveltejs/kit/blob/9a2cc0afd3433134045dec0550172ef194fc23d4/packages/kit/src/runtime/client/router.js#L232

It use the parsed path (which remove the base path) for the url to navigate. This is not intended as the bas path will always be ignored. It should use `url.pathname` or simply url

**Comment by wighawag** [comment]
this line 
https://github.com/sveltejs/kit/blob/9a2cc0afd3433134045dec0550172ef194fc23d4/packages/kit/src/runtime/client/router.js#L232

should be

```typescript
history.replaceState({}, '', `${this.base}${info.path}${location.search}`); 
```

**Comment by russellgoldenberg** [comment]
@wighawag is there a way to make this modification in the current version within a specific project? I see that a start.js is generated on each build which is where this piece lives.
