### ISSUE TITLE
font use absolute path assuming the font file will be hosted on the route.

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#1477]
**Describe the bug**
in the create svelte default template the following css : https://github.com/sveltejs/kit/blob/9a2cc0afd3433134045dec0550172ef194fc23d4/packages/create-svelte/templates/default/src/app.css#L1 get generated into font with url referencing font woff file with absolute path. This assume the website is hosted on the root path

**Expected behavior**
The css generated for font file should use relative path. This should work nicely has relative path in css are relative to the css file itself

**Comment by Rich-Harris** [comment]
This is a Vite issue that will hopefully be fixed by https://github.com/vitejs/vite/pull/7644

**Comment by locriacyber** [comment]
> This is a Vite issue that will hopefully be fixed by [vitejs/vite#7644](https://github.com/vitejs/vite/pull/7644)

It is not that simple. While [this simple site using vite](https://github.com/huibizhang/template-vite-vanilla-tailwind-v3) works fine, svelte tries to break this all.

Let's say I want to import a file with `import("./import-me.css")`.

With https://github.com/vitejs/vite/pull/7644 and `relative-assets` at git@github.com:locriacyber/kit.git

The website is generated at `/build/index.html` with `adapter-static`.

The browser tries to fetch `/_app/assets/import-me-2d113d6b.css`, which is wrong.

If I use `base: "./"` as vite config, then the browser fetches `/build/assets/import-me-2d113d6b.css`, which is wrong again.

The correct path should be `/build/_app/assets/import-me-2d113d6b.css`.

**Comment by locriacyber** [comment]
Here's the website I was talking about:
https://github.com/locriacyber/svelte-relative-assets-challenge
