### ISSUE TITLE
Deployed hello world demo missing base CSS

### ISSUE THREAD

**Issue by geoffrich** [sveltejs/kit#1479]
**Describe the bug**
The deployed "hello world" at https://netlify.demo.svelte.dev/ is missing the base CSS, making the page look broken. This is only an issue with the deployed demo; when running locally, everything looks as expected.

![image](https://user-images.githubusercontent.com/4992896/118517463-14a7a400-b6ec-11eb-9b6e-00a5e0c67ae6.png)

**Logs**
n/a

**To Reproduce**
Visit https://netlify.demo.svelte.dev/ and notice that styles are missing.

**Expected behavior**
The deployed page looks the same as running locally.

**Stacktraces**
Tested in Chrome and Firefox on Windows and iOS Safari.

**Severity**
This demo page has been used to show off SvelteKit on social media and elsewhere, so it should not look broken.

**Additional context**
I'm not sure if this is a problem with Kit, the demo page itself, or something else entirely.

**Comment by AsyncBanana** [comment]
It seems like this has been fixed. The page renders fine for me. 
![SvelteKit demo](https://user-images.githubusercontent.com/58297401/122695668-1bf02f00-d20f-11eb-8141-665c28a49bf3.png)
This was on the remote version of the demo. The result was the same for both Edge and Firefox.

**Comment by geoffrich** [comment]
You're right, looks fine to me as well. I'll go ahead and close the issue.
