### ISSUE TITLE
generated start file does not work with relative path

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#1480]
I could not find where in the source code the generated start file is coded, but in my ipfs app, I need to get rid of all absolute path 

The start file generated by sveltekit inject script tag at run time and is given a list of paths for that. Unfortunately these paths do not have access to the router base property currently,

Note that my ipfs adapter ensure the router base path is generated at runtime (See comment here: https://github.com/sveltejs/kit/issues/595#issuecomment-842278606 ) so the solution will also have to operate at runtime.

Could we make so that the start file have access to the router base property ?

in the generated start file I see  something like this :

```
        if (document.querySelector(`link[href="${t}"]${r}`))
            return;
        const s = document.createElement("link");
        ...
        s.href = t,
        document.head.appendChild(s),
  
```

by default `t` is an aboslute path. I hacked the output of static adapter via a postprocess and I make sure that the various `t` path are relative

Unfortunately depending on the context (the value of window.location), the relative path will be interpreted differently
The solution would be ensure the `t` paths are generated with the router.base in mind so that script tag are given only absolute path, making them independent of context

**Comment by Rich-Harris** [comment]
Closing in favour of #595
