### ISSUE TITLE
Invalid output and infinite redirect loop with `adapter-static` and `trailingSlash: "always"`

### ISSUE THREAD

**Issue by mvolfik** [sveltejs/kit#1486]
**Describe the bug**
Only `<meta http-equiv="refresh" content="0;url=/test/">` is written to `build/test/index.html` when using static adapter and always trailing slash.

**Logs**
None, build runs successfully, maybe just that `301 /test -> /test/` is printed during build.

**To Reproduce**

Use `npm init svelte@next test`, choose skeleton project.

Create a page `src/routes/test/index.svelte` with any content (`<p>hello</p>`). Have `svelte.config.js` like this:

```js
import adapter from "@sveltejs/adapter-static";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: "#svelte",
    adapter: adapter(),
    trailingSlash: "always",
  },
};

export default config;
```

Reproduction repo with individual setup steps in https://github.com/mvolfik/probable-disco

**Expected behavior**
No redirects should be needed at all. `build/test/index.html` should contain normal html page with `<p>hello</p>`.

**Stacktraces**
N/A

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite,@sveltejs/adapter-static --binaries --browsers

  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
    Memory: 292.40 MB / 7.35 GB
    Container: Yes
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 14.16.0 - ~/.local/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 7.6.3 - ~/.local/bin/npm
  Browsers:
    Chromium: 90.0.4430.212
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.9 
    @sveltejs/kit: next => 1.0.0-next.107
    svelte: ^3.34.0 => 3.38.2
```
</details>

**Severity**
Bad bad. Makes `adapter-static` unusable with `trailingSlash: "always"`.

**Additional context**
There is one similar issue #1346, but that is apparently caused by Netlify redirects, while this is only sveltekit.

**Comment by benmccann** [comment]
The value of `trailingSlash` shouldn't have much impact if you're using `adapter-static`, so I'd suggest just removing that option for now. `adapter-static` just outputs `.html` files which cannot control whether or not they are served with a trailing slash. You may be able to configure that with your hosting provider when generating static files. `trailingSlash` on the other hand will only be able to be utilized if you're using one of the other adapters which has a server-side component

**Comment by mvolfik** [comment]
I'm aware of that, though it does have some impact - SvelteKit rewrites the urls client-side upon navigation

**Comment by mvolfik** [comment]
Yayy, found a workaround - all my pages are interlinked, so I can rely on crawling and set `config.kit.prerender.pages = ["/"]`, and if all my links end with trailing slash, the issue doesn't happen.

**Comment by deepmouse** [comment]
Probably related to this: I am getting an infinite redirect loop even without `trailingSlash: "always"` on, all it needs is one link on my site that uses a trailing slash, and this "redirect loop page" is created.
