### ISSUE TITLE
Links to static assets do not work 

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/kit#1492]
**Describe the bug**

When creating a link to a static asset, clicking the link triggers a 404 instead of opening the asset. 

**Logs**

The issue doesn't log anything.

**To Reproduce**

In the default sveltekit app: 

 - Create a file in `static/hello.txt` with the contents `hello world`
 - In `src/index.svelte`, add the following link: `<a href="/hello.txt">xxx</a>`

run `npm run dev`, then, from your browser, click the link 

**Expected behavior**

The text file is loaded

**Actual behavior**
A 404 error

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```

  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 292.30 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 88.0.1
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107 
    svelte: ^3.34.0 => 3.38.2 
```

</details>

**Severity**
Caused a broken link in production for me in 
https://sanipasse.fr/french-health-pass

**Comment by lovasoa** [comment]
SvelteKit knows which static assets it has, so there is no reason that we can't make it work with a normal link, is there ?

**Comment by tobi-or-not-tobi** [comment]
I assume this is fixed by #1487

**Comment by mvolfik** [comment]
Yes, it is a duplicate. But let me just point out that this isn't solved by the patch (not)tobi mentions - that solves the case if you have app base `/foo/bar` and navigate to `/`

**Comment by lovasoa** [comment]
Oh, yes, I did not find that original issue. Sorry.
