### ISSUE TITLE
Change TOML parser to an active project that supports the latest TOML syntax

### ISSUE THREAD

**Issue by jwrunner** [sveltejs/kit#1493]
**Describe the bug**
I upgraded to the most recent wrangler version and expected adding upload.format = "service-worker" to the wrangler.toml (for adapter-cloudflare-workers) file to just work as described in https://developers.cloudflare.com/workers/cli-wrangler/configuration#service-workers but when the adapter (https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare-workers/index.js#L61) parses it with the toml package it throws:
`Error parsing wrangler.toml: Expected "=", [ \t] or [A-Za-z0-9_\-] but "." found.`

**To Reproduce**
- `npm init svelte@next` and `npm i`
- `npm i -D @sveltejs/adapter-cloudflare-workers@next` and add `import cloudflare from '@sveltejs/adapter-cloudflare-workers';
` and  `adapter: cloudflare(),` to svelte.config.js
- `wrangler init` (assumes you've installed wrangler globally)
- To the newly created wrangler.toml file add 
```
[build]
upload.format = "service-worker"
```
or any other wrangler instruction using the <word>.<word> syntax.
- `npm run build` <-- Bug throws here

**Expected behavior**
I expected the build to complete successfully and for me to be able to then publish the built site using `wrangler publish`.

**Information about your SvelteKit Installation:**

<details>
- @sveltejs/adapter-cloudflare-workers": "^1.0.0-next.8"
- @sveltejs/kit: "next"
</details>

**Severity**
Annoying but not a show-stopper presently because I can use an alternate syntax:
```
[build.upload]
format = "service-worker"
```

**Additional context**
The problem is caused by using the stale [toml](https://www.npmjs.com/package/toml) package which hasn't been updated in 2 years and is still back at the 0.4.0 TOML spec. I propose opening a PR to switch to using https://www.npmjs.com/package/@iarna/toml or some other Javascript package (see https://github.com/toml-lang/toml/wiki) which is up to date with the latest TOML spec as done by [others](https://github.com/renovatebot/renovate/pull/7559) to parse the wrangler.toml properly when using TOML syntax introduced after 0.4.0. **Can I open a PR?**

*Someone proposed support for TOML 0.5.0 to the stale toml package, but no dice as the package maintainer is no longer responding: https://github.com/BinaryMuse/toml-node/issues/50*

**Comment by benmccann** [comment]
Sounds reasonable to me. @halfnelson wrote the adapter originally so tagging him here in case he wants to weigh in

https://github.com/sveltejs/kit/pull/717/files#diff-43081842b4f8656d01e0b6705906f558acf5f309ea11076f4de04a01d5ecb39fR14

**Comment by halfnelson** [comment]
Good idea!

**Comment by halfnelson** [comment]
We should also bump/change the package used in the Netlify adapter too
