### ISSUE TITLE
Possible incorrect types

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1494]
I believe `Buffer` was replaced with `Uint8Array` in https://github.com/sveltejs/kit/pull/1382, so perhaps the type below is wrong

https://github.com/sveltejs/kit/blob/11e7840c67c2cae17940b0d9664ca0fb3da91eb9/packages/kit/types/helper.d.ts#L10

Also, `Incoming` is unused in `hooks`:

https://github.com/sveltejs/kit/blob/586785da75a3d0d6eb27a2ecd171208bbdb935a3/packages/kit/types/hooks.d.ts#L4

It's exported and used in [`index`](https://github.com/sveltejs/kit/blob/586785da75a3d0d6eb27a2ecd171208bbdb935a3/packages/kit/types/index.d.ts) and [`internal`](https://github.com/sveltejs/kit/blob/586785da75a3d0d6eb27a2ecd171208bbdb935a3/packages/kit/types/internal.d.ts), but I wonder if `ServerRequest` should be used instead

**Comment by benmccann** [comment]
@ignatiusmb @dummdidumm you guys might be interested in this one

**Comment by ignatiusmb** [comment]
I think you're right on replacing `Buffer` with `Uint8Array`, I've checked for other references and there seems to be none that's related. `Incoming` on the other hand, looks very similar to `ServerRequest`, but it seems to be correct and only used as the first parameter of render in `App`. I'm guessing we could remove it from the public types as well, seems to only be used internally.
