### ISSUE TITLE
`fetch` of URL with space fails during prerendering with `npm run build`

### ISSUE THREAD

**Issue by deepmouse** [sveltejs/kit#1501]
**Describe the bug**
When fetching an URL that contains spaces e.g. `/my static file.md` (escaped `/my%20static%20file.md`), the `fetch` tries to access a double escaped url `/my%20static%20file.md` (escaped `/my%2520static%2520file.md`) and generates a 404 html page in the file system under `/build/my%20static%20file.md/index.html`. On the browser side, the fetch works.

**Logs**
The build fails with:

```
> 404 /articles/recipe/Crushing%20bird%20nests%20at%20Nardah.md (fetched from /recipe/iiGzJN9IX0ILE81ECwNuIpJ6LUOsWbigIvMuTIkOxs9ISrFZQIMBb8pJybuBzdsZQQ)
```

**To Reproduce**

Make a route with a load function that fetches an URL with spaces in it. Use adapter static. The file will be fetched correctly in the browser but will fail during generation with `npm run build`.

I can make an example repo later if needed.

**Expected behavior**
Build passing and no `/build/my%20static%20file.md/index.html` file generated.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

> 404 /articles/recipe/Crushing%20bird%20nests%20at%20Nardah.md (fetched from /recipe/iiGzJN9IX0ILE81ECwNuIpJ6LUOsWbigIvMuTIkOxs9ISrFZQIMBb8pJybuBzdsZQQ)
Error: 404 /articles/recipe/Crushing%20bird%20nests%20at%20Nardah.md (fetched from /recipe/iiGzJN9IX0ILE81ECwNuIpJ6LUOsWbigIvMuTIkOxs9ISrFZQIMBb8pJybuBzdsZQQ)
    at error (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:93:11)
    at file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:181:6
    at Map.forEach (<anonymous>)
    at visit (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:163:17)
    at async visit (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:220:6)
    at async visit (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:220:6)
    at async prerender (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:229:5)
    at async Object.prerender (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
    at async adapt (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///C:/Users/a/src/greedy-goblin/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:2)

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

 System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
    Memory: 4.36 GB / 15.90 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.13.0 - ~\src\greedy-goblin\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.62)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.107
    svelte: ^3.29.0 => 3.38.2
    vite: ^2.1.0 => 2.3.2

using adapter-static
</details>

**Severity**

This can be circumvented with only using file names that don't need to be escaped. But, considering that this error stops the build, is quite subtle and can take some time to debug. Maybe it could be considered a medium-level priority.

**Additional context**
Discussion about the bug when it was discovered https://discord.com/channels/457912077277855764/819723698415599626/844895934257037392

**Comment by benmccann** [comment]
does this happen with the latest version of SvelteKit? we changed from `url.parse` to `new URL` and I wonder if it might have changed anything
