### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1503]
**Describe the bug**
After some time (from `1.0.0-next.87`) I am using SvelteKit again.

With 87 I can use `console.log(window.localStorage)` in `$layout.svelte`.

If I use the same code now (with 108) it throws with:

```
ReferenceError: window is not defined
  at __layout.svelte:5:43
```

**NOTE: the default SvelteKit init demo comes without adapters, should I add one? Is this the issue?**

**To Reproduce**
- npm init svelte@next my-app
- cd my-app
- npm install
- add `console.log(window.localStorage)` to `__layout.svelte` right before `</script>`
- npm run dev

**Expected behavior**
It prints in console.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.108 => 1.0.0-next.108
    svelte: 3.38.2 => 3.38.2
    vite: 2.3.3 => 2.3.3

- Your browser: Chrome 90

- Your adapter: none
</details>

**Severity**
I cannot work.

**Comment by dummdidumm** [comment]
According to your instruction steps you didn't turn off ssr. `window` is not defined in a server environment, so it's expected that this would throw.

**Comment by frederikhors** [comment]
It works! Thanks!

**Comment by sw-yx** [comment]
i know this is because of SSR, but also usually in React land we get around it with `if (typeof window === 'undefined') {`. however this appears not to work with the current version of sveltekit

**Comment by gustavneustadt** [comment]
How to turn off ssr? I just installed `sveltejs/adapter-static` and changed the `svelte.config.js` accordingly. But `window` is still `not defined`. 

In my case I try to use `window` in component context for `window.requestAnimationFrame(updateAnimation)`.
  
---
**svelte.config.js**

```js
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter({
			fallback: 'index.html'
		}),
		
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	}
};

export default config;
```

**Comment by ghostdevv** [comment]
@gustavneustadt prerendering is all done server side, theres no window variable defined.

**Comment by dummdidumm** [comment]
See https://github.com/sveltejs/kit/discussions/3365#discussioncomment-1976132

**Comment by gustavneustadt** [comment]
@dummdidumm Thanks – that's it.

**Comment by rdela** [comment]
Re: gustavneustadt [comment above](https://github.com/sveltejs/kit/issues/1503#issuecomment-1026864414) for people finding this issue in the future

[comment](https://github.com/sveltejs/kit/issues/4849#issuecomment-1121710739) on https://github.com/sveltejs/kit/issues/4849 by [mrkishi](https://github.com/mrkishi):
> If you have fallback: 'index.html' configured, that will clash with your actual routes/index.svelte route since they'd both be rendered into index.html. You should name your fallback differently and configure your server/platform to serve it for all requests that don't have a matching html file.

see also:

- https://github.com/sveltejs/kit/issues/5185
- https://github.com/sveltejs/kit/issues/4842
