### ISSUE TITLE
Invalid url in fetch when excluding domain

### ISSUE THREAD

**Issue by cupcakearmy** [sveltejs/kit#1520]
**Describe the bug**

The `load` function throws an `Invalid URL` if the url path does not have a hostname in the path.

`await fetch('/test.json')` does not work

`await fetch('http://localhost/test.json')` works

**Logs**
```
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:363:5)
    at onParseError (node:internal/url:537:9)
    at new URL (node:internal/url:613:5)
    ...
```

**To Reproduce**

```
npm init svelte@next test
```

```typescript
// src/routes/test.json.ts
import type { RequestHandler } from '@sveltejs/kit'

export const get: RequestHandler = async () => {
  return {
    body: {
      test: 'ok',
    },
  }
}

```

```svelte
<script lang="ts" context="module">
  // src/routes/index.svelte
  import type { Load } from '@sveltejs/kit'

  export const load: Load = async () => {
    return {
      props: {
        data: await fetch('/test.json').then((r) => r.json()),
      },
    }
  }
</script>

<script lang="ts">
  export let data

  $: console.log(data)
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

I've just pulled a skeleton project with the latest versions.

**Expected behavior**

Fetch should be aware of the domain

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

Quite blocking, data fetching does not work properly which is the backbone of the most apps.

**Comment by GrygrFlzr** [comment]
You need to use the fetch passed down to `load`, not the globally available fetch function.

```ts
export const load: Load = async ({ fetch }) => {
  return {
    props: {
      data: await fetch('/test.json').then((r) => r.json()),
    }
  };
}
```
