### ISSUE TITLE
@sveltejs/adapter-vercel: CLI deployment to Vercel is not working

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#1521]
**Describe the bug**
I changed my adapter to the official vercel adapter and tried a deployment to Vercel with their CLI tool.

**Logs**
```
<!--StartFragment-->
18:02:54.424 | Running "npm run build"
-- | --
18:02:54.629 | &gt; rust-jungle@0.1.0 build /vercel/path0
18:02:54.629 | &gt; svelte-kit build
18:02:54.724 | Cannot find module '@sveltejs/app-utils/renderer'
18:02:54.724 | Require stack:
18:02:54.724 | - /vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js
18:02:54.724 | Error: Cannot find module '@sveltejs/app-utils/renderer'
18:02:54.724 | Require stack:
18:02:54.724 | - /vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js
18:02:54.724 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
18:02:54.725 | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
18:02:54.725 | at Module.require (internal/modules/cjs/loader.js:952:19)
18:02:54.725 | at require (internal/modules/cjs/helpers.js:88:18)
18:02:54.725 | at Object.&lt;anonymous&gt; (/vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:7:16)
18:02:54.725 | at Module._compile (internal/modules/cjs/loader.js:1063:30)
18:02:54.725 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
18:02:54.725 | at Module.load (internal/modules/cjs/loader.js:928:32)
18:02:54.725 | at Function.Module._load (internal/modules/cjs/loader.js:769:14)
18:02:54.725 | at ModuleWrap.&lt;anonymous&gt; (internal/modules/esm/translators.js:199:29)

<!--EndFragment-->
```

After I added the package and re-run it, I got those errors:
```
<!--StartFragment-->
18:05:50.690 | Running "npm run build"
-- | --
18:05:50.889 | &gt; rust-jungle@0.1.0 build /vercel/path0
18:05:50.889 | &gt; svelte-kit build
18:05:50.984 | Package subpath './renderer' is not defined by "exports" in /vercel/path0/node_modules/@sveltejs/app-utils/package.json
18:05:50.985 | Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './renderer' is not defined by "exports" in /vercel/path0/node_modules/@sveltejs/app-utils/package.json
18:05:50.985 | at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
18:05:50.985 | at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
18:05:50.985 | at resolveExports (internal/modules/cjs/loader.js:432:36)
18:05:50.985 | at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
18:05:50.985 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
18:05:50.985 | at Function.Module._load (internal/modules/cjs/loader.js:725:27)
18:05:50.985 | at Module.require (internal/modules/cjs/loader.js:952:19)
18:05:50.985 | at require (internal/modules/cjs/helpers.js:88:18)
18:05:50.986 | at Object.&lt;anonymous&gt; (/vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:7:16)
18:05:50.986 | at Module._compile (internal/modules/cjs/loader.js:1063:30)

<!--EndFragment-->
```

**To Reproduce**
Create a basic SvelteKit project and use the @sveltejs/adapter-vercel adapter. Then try using the Vercel CLI tool to deploy your app.

**Expected behavior**
Deployment works without any errors.

**Stacktraces**
see logs above.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 6.90 GB / 15.96 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (90.0.818.66)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): @sveltejs/adapter-vercel
</details>

**Severity**
I'm currently using netlify without any problems. Vercel was just for testing. So this isn't important for me.

**Additional context**
The branch with the vercel adapter can be found here:
https://github.com/Zerotask/rust-jungle/tree/feat/vercel

**Comment by benmccann** [comment]
This is your issue:
```
		"@sveltejs/adapter-vercel": "^1.0.0-next.0",
		"@sveltejs/app-utils": "^1.0.0-next.0",
```

Please replace the version with `next`. Also you generally don't need to specify `app-utils` for most applications though I haven't looked if you're doing something uncommon where you might need it

**Comment by DougAnderson444** [comment]
@benmccann, I am still getting the `renderer` issue above, even with versions set to `next`. Suggest reopening if anyone else also still seeing this issue.

**Comment by benmccann** [comment]
You probably had the version locked with `package-lock.json`. If you put the version as `next`, delete `package-lock.json`, and then run `npm install` I expect it will work
