### ISSUE TITLE
Windows: import path in load function using incorrect slashes 

### ISSUE THREAD

**Issue by brittneypostma** [sveltejs/kit#1522]
**To Reproduce**
## Repo for site having issue.
[https://github.com/brittneypostma/sveltekit-tailwind-mdsvex](https://github.com/brittneypostma/sveltekit-tailwind-mdsvex)
1. Clone repo
2. run `pnpm i`
3. run `pnpm run dev`
4. navigate to [http://localhost:3000/blog/first-post](http://localhost:3000/blog/first-post)

**Describe the bug**
In `src/routes/blog/[slug].svelte` I am importing a markdown file. The path is getting resolved correctly, but windows is trying to mix it with a path using `\` forward instead of `/` backward slashes. This is causing the file to not load. If I navigate in the url bar to [http://localhost:3000/blog/posts/first-post](http://localhost:3000/blog/posts/first-post) the file loads correctly. I tried using `import('./posts/' + slug + '/index.md')` and `import(`./posts/${slug}/index.md`)`. Both get logged the same, but when the full path is stacked on, the slashes are a different way than windows is trying to use.

**Logs**
<details><summary>Browser Error</summary>500
failed to load module for ssr: /Users/Britt/Documents/Coding/Jamstack/Svelte/tailwind-blog/C:\Users\Britt\Documents\Coding\Jamstack\Svelte\tailwind-blog\src\routes\blog/posts/first-post/index.md
Error: failed to load module for ssr: /Users/Britt/Documents/Coding/Jamstack/Svelte/tailwind-blog/C:\Users\Britt\Documents\Coding\Jamstack\Svelte\tailwind-blog\src\routes\blog/posts/first-post/index.md
    at instantiateModule (C:\Users\Britt\Documents\Coding\Jamstack\Svelte\tailwind-blog\node_modules\.pnpm\vite@2.3.3\node_modules\vite\dist\node\chunks\dep-e9a16784.js:68148:15)

Console of browser:
Failed to load resource: the server responded with a status of 500 (Internal Server Error</details>
<details><summary>Terminal Error</summary>failed to load module for ssr: /Users/Britt/Documents/Coding/Jamstack/Svelte/tailwind-blog/C:\Users\Britt\Documents\Coding\Jamstack\Svelte\tailwind-blog\src\routes\blog/posts/first-post/index.md </details>

**Expected behavior**
I expect to be able to use the First Post link on the route `/blog` and it navigate to `/blog/first-post` and load the first post correctly without an error.

**Stacktraces**

<details>
  <summary>Stack trace</summary>

/Users/Britt/Documents/Coding/Jamstack/Svelte/tailwind-blog/C:\Users\Britt\Documents\Coding\Jamstack\Svelte\tailwind-blog\src\routes\blog/posts/first-post/index.md

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers` - 
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz
    Memory: 20.69 GB / 31.88 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE     
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD       
  Browsers:
    Edge: Spartan (44.1904), Chromium (90.0.81)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109
    svelte: ^3.34.0 => 3.38.2

- Your browser - Chrome & Firefox Dev Edition

- Your adapter (e.g. Node, static, Vercel, Begin, etc...) - no adapter added yet
</details>

**Severity**
Blocking my use of SvelteKit entirely and am unable to migrate from Sapper over with my blog sites.

**Additional context**
running in git bash on windows not in WSL

**Comment by ignatiusmb** [comment]
I can't seem to reproduce the issue, followed the steps and no errors appeared (also using windows without WSL). Can you try again and see if everything works as expected?

Also, your import glob line in `routes/blog/[slug].svelte` logs an empty object, seems like it should've been

```diff
-const modules = import.meta.glob(`./posts/*.{md,svx,svelte.md}`)
+const modules = import.meta.glob(`./posts/**/*.{md,svx,svelte.md}`)
```

**Comment by benmccann** [comment]
I expect this is generally working or we would have gotten more reports of it being broken. Can you clarify if there's still an issue?
