### ISSUE TITLE
Example app in SPA mode routing/reloading inconsistencies

### ISSUE THREAD

**Issue by brgrz** [sveltejs/kit#1529]
**Describe the bug**

I was playing around with different build modes in SvelteKit example app and this behaviour got me wandering.

If I build with static adapter with `fallback` set it will create almost empty `About/index.html`. 
Makes sense since the content will be provided by the app at runtime. Which upon hard reload with F5 will not load/empty page is displayed. **This is the expected behaviour.**

However, the same build will load the Todos page upon hard reload. How's that even possible? **I would't expect this to work.**

Both of these happen when `ssr` option is left unset. If I set `ssr:false` the About page will get prerendered and the hard reload will work.

**To Reproduce**

Just playing around with the default ootb SvelteKit example app

**Expected behavior**

The expected behaviour in SPA mode would be that Todos page does not work either.

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)

Static in SPA mode (`fallback` option set)

**Severity**

Not severe at all, just wanted to clarify some things

**Comment by benmccann** [comment]
Please ask questions on Discord
