### ISSUE TITLE
npm run build fails when using webcomponents using adapter-static

### ISSUE THREAD

**Issue by abnazhor** [sveltejs/kit#1531]
**Describe the bug**
When using web-components such as [shoelace](https://shoelace.style), `npm run build` crashes

**Logs**
```
> ~TODO~@0.0.1 build /home/jorge/Proyectos/svelte-kit
> svelte-kit build

vite v2.3.3 building for production...
✓ 28 modules transformed.
.svelte-kit/output/client/_app/manifest.json                            1.77kb
.svelte-kit/output/client/_app/layout.svelte-904f1151.js                0.49kb / brotli: 0.29kb
.svelte-kit/output/client/_app/pages/index.svelte-464950c5.js           0.53kb / brotli: 0.33kb
.svelte-kit/output/client/_app/error.svelte-ec464882.js                 1.19kb / brotli: 0.57kb
.svelte-kit/output/client/_app/chunks/preload-helper-9f12a5fd.js        0.61kb / brotli: 0.31kb
.svelte-kit/output/client/_app/assets/start-a8cd1609.css                0.16kb / brotli: 0.10kb
.svelte-kit/output/client/_app/chunks/vendor-43cd886a.js                5.05kb / brotli: 1.98kb
.svelte-kit/output/client/_app/assets/pages/index.svelte-a2c9796c.css   7.29kb / brotli: 1.43kb
.svelte-kit/output/client/_app/start-2c597637.js                        16.71kb / brotli: 5.32kb
.svelte-kit/output/client/_app/chunks/button-4ff57d8f.js                33.65kb / brotli: 8.11kb
vite v2.3.3 building SSR bundle for production...
✓ 23 modules transformed.
.svelte-kit/output/server/app.js   62.07kb

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> document is not defined
ReferenceError: document is not defined
    at file:///home/jorge/Proyectos/svelte-kit/.svelte-kit/output/server/app.js:249:9
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async prerender (file:///home/jorge/Proyectos/svelte-kit/node_modules/@sveltejs/kit/dist/chunks/index5.js:79:14)
    at async Object.prerender (file:///home/jorge/Proyectos/svelte-kit/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
    at async adapt (file:///home/jorge/Proyectos/svelte-kit/node_modules/@sveltejs/adapter-static/index.js:17:4)
    at async adapt (file:///home/jorge/Proyectos/svelte-kit/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:2)
    at async file:///home/jorge/Proyectos/svelte-kit/node_modules/@sveltejs/kit/dist/cli.js:616:5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ~TODO~@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ~TODO~@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jorge/.npm/_logs/2021-05-23T21_55_45_477Z-debug.log
```

**To Reproduce**
The following error is available in [this repository](https://github.com/abnazhor/svelte-shoelace-config)

**Expected behavior**
Build should be created and generate a folder with a static website using webcomponents.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Linux 5.11 Solus 4.2
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 7.82 GB / 15.64 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/bin/node
    npm: 6.14.13 - /usr/bin/npm
  Browsers:
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109 
    svelte: ^3.34.0 => 3.38.2 
</details>

**Severity**
This bug blocks the usage of Sveltekit completely as there is no other option to build to static webpage.

**Comment by Conduitry** [comment]
If any library makes use of browser APIs, you need to make sure it's only loaded in the browser build and not the server build.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by brgrz** [comment]
@Conduitry Obviously people are having a ton of issues as things with SvelteKit setup are rather confusing and the Docs don't make it any easier since they're lacking in many parts. Rather than closing everything and instructing "go to Discord" some of these closed questions could be marked as pointers on where to expand the Docs/FAQ. I'd bet even in Discord chat certain same questions pop up all the time.
