### ISSUE TITLE
Importing adapter-begin fails with "type": "module"

### ISSUE THREAD

**Issue by thislooksfun** [sveltejs/kit#1532]
**Describe the bug**
I'm trying to add `adapter-begin` to my freshly-created SvelteKit project, but now `svelte-kit build` fails with

```
Cannot find module '<snip>/node_modules/@sveltejs/adapter-begin/index.js' imported from <snip>/svelte.config.js
Did you mean to import @sveltejs/adapter-begin/index.cjs?
```

Changing it to importing `@sveltejs/adapter-begin/index.cjs` also fails with the message

```
Package subpath './index.cjs' is not defined by "exports" in <snip>/node_modules/@sveltejs/adapter-begin/package.json imported from <snip>/svelte.config.js
```

**Logs**
N/A

**To Reproduce**
1. Create a fresh SvelteKit project, making sure to enable TypeScript
2. Install [adapter-begin](https://github.com/sveltejs/kit/tree/master/packages/adapter-begin)
3. Run `npm run build`

**Expected behavior**
I expect to be able to import and use a first-party adapter after creating a project from the first-party scaffold.

**Stacktraces**
N/A

**Information about your SvelteKit Installation:**
N/A

**Severity**
It's blocking my intended use case entirely.

**Additional context**
n/A

**Comment by macdaddyaz** [comment]
I'm experiencing the same issue. Trying to set up a brand new app w/ SvelteKit & Begin. The app will not start locally, and will not deploy to Begin.

**Comment by benmccann** [comment]
There's a new version of the Begin adapter. Please take a look at https://github.com/architect/sveltekit-adapter
