### ISSUE TITLE
Manually mount slots

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#1535]
**Is your feature request related to a problem? Please describe.**
I have a virtual list component `VirtualList` where it takes a little time to load each item, so that this effect is quite prevalent when scrolling:

https://user-images.githubusercontent.com/11315492/119281916-e10ed180-bc37-11eb-8c94-b456c9b36e5e.mp4

I imagine the issue here is that whenever a new item becomes visible, all visible items are re-rendered.

**Describe the solution you'd like**
The fastest virtual list I've seen is VSCode's. It works by appending new elements to the view without being concerned about what order they're in, and positioning them using `position: absolute`:
<img width="444" alt="Screen Shot 2021-05-24 at 2 41 01 AM" src="https://user-images.githubusercontent.com/11315492/119282328-95f5be00-bc39-11eb-83b0-67a3457c9a1d.png">

The best way I can see to accomplish this is to be able to manually mount Svelte slots from JS.

Another possible solution would be to have an `#each` block where you could add or remove items without re-rendering any items.

**Describe alternatives you've considered**
1. Mounting the child components manually, instead of using slots. Should be possible, but I believe it would make it significantly more complicated to interact between the `Container` component and the `Item` components (keyboard events, drag-and-drop events, row selection), as well as sharing styles between them. Keeping slots would be great.
2. I could make a big soup of a Svelte component that includes both the container and the virtual list logic
3. Tried using `<svelte:options immutable/>`, but doesn't seem like something that would work here.

**How important is this feature to you?**
Quite important, but I understand it's an edge case.

**Comment by benmccann** [comment]
This doesn't seem related to SvelteKit

**Comment by probablykasper** [comment]
Thought I posted in the svelte repo, sorry
