### ISSUE TITLE
Build fails when client-side importing a module that uses window/self at the top-level

### ISSUE THREAD

**Issue by mattjennings** [sveltejs/kit#1537]
**Describe the bug**
When importing a module intended for the client in onMount (as instructed in https://kit.svelte.dev/faq), if that module uses window or self at a top level, SvelteKit will fail to build. However, it does work in dev.

If you don't use an adapter, the build will succeed but fail on preview. I have tried it with node, static, and vercel adapters and all of them fail with the same error.

**Logs**

build error:

```
> Using @sveltejs/adapter-node
> window is not defined
ReferenceError: window is not defined
    at file:///Users/mattjennings/Desktop/sk/.svelte-kit/output/server/app.js:190:1
    at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async prerender (file:///Users/mattjennings/Desktop/sk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index5.js:79:14)
    at async Object.prerender (file:///Users/mattjennings/Desktop/sk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index5.js:296:5)
    at async adapt (file:///Users/mattjennings/Desktop/sk/node_modules/.pnpm/@sveltejs+adapter-node@1.0.0-next.22_@sveltejs+kit@1.0.0-next.109/node_modules/@sveltejs/adapter-node/index.js:28:4)
    at async adapt (file:///Users/mattjennings/Desktop/sk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/chunks/index5.js:322:2)
    at async file:///Users/mattjennings/Desktop/sk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.109_svelte@3.38.2/node_modules/@sveltejs/kit/dist/cli.js:616:5
 ERROR  Command failed with exit code 1.
```

**To Reproduce**
https://github.com/mattjennings/sveltekit-client-import-bug

`src/routes/index.svelte` imports a script that sets up a click listener on window. Try running in dev, it'll work. Try building, it'll fail.

**Expected behavior**
I should be able to safely import a module client-side that uses window/self at a top-level.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 42.08 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Brave Browser: 90.1.24.82
    Chrome: 90.0.4430.212
    Safari: 14.1
    Safari Technology Preview: 14.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109 
    svelte: ^3.34.0 => 3.38.2 

- node / static adapters
</details>

**Severity**
Blocking - cannot use any module that works like this.

**Comment by benmccann** [comment]
It works if you simply follow the suggestion in [the FAQ](https://kit.svelte.dev/faq#integrations):
```
<script>
  import { onMount } from "svelte";
  import { browser } from '$app/env';

  if (browser) {
    onMount(async () => {
      await import("../client-script");
    });
  }
</script>
```

**Comment by benmccann** [comment]
It would be interesting to check if `client-script` is an external node module if the situation is different. I'm not quite sure why this example works and Monaco editor fails. I'm pretty sure I've seen other external node modules that work correctly though, so this really seems like Monaco is somehow triggering a weird Vite edge case

**Comment by mattjennings** [comment]
I might suggest that the FAQ be updated to include wrapping `onMount` in an `if (browser)` check. My understanding of it was that either-or would keep the import happening only in the browser, not that I might need both.
