### ISSUE TITLE
Convert values from exported (TS) variable automatically to correct type

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#1544]
In a component, I export a number variable

```
<script lang="ts">
    export let index: number;
</script>
```

and in another component, I import that component and pass a value to it (e.g. `index="4"`. I'd assume to have a number then, but it's actually a string.
I also get the TS error: Type 'string' is not assignable to type 'number.

The "workaround" which is working as expected is to define `const index: number = 4;` and then pass `{index}` to that component. Then it's correctly interpreted as a number.

**Comment by dummdidumm** [comment]
This is unrelated to Svelte kit. It's also the expected and intended behavior. Doing what you do or doing `index={4}` fixes the error.
