### ISSUE TITLE
sveltekit netlify build fails

### ISSUE THREAD

**Issue by katgolek** [sveltejs/kit#1552]
Netlify build fails. I am using  npm version 6.14.13 and LTS node version v14.16.0. 
I am not sure where node version 12.18.0 is coming from....

My svelte.config.js looks as below, locally I am able to build for production

@type {import('@sveltejs/kit').Config} */

import adapter from '@sveltejs/adapter-netlify';
const pkg = require('./package.json');

const config = {
	kit: {
		adapter: adapter(), // currently the adapter does not take any options
		target: '#svelte'
	}
};

export default config;

Netlify build logfile:

1:38:41 PM: Build ready to start
1:38:43 PM: build-image version: 0582042f4fc261adc7bd8333f34884959c577302
1:38:43 PM: build-image tag: v3.7.6
1:38:43 PM: buildbot version: cb3d235979bae64f617d34524cb2e8a9de68153f
1:38:43 PM: Fetching cached dependencies
1:38:43 PM: Failed to fetch cache, continuing with build
1:38:43 PM: Starting to prepare the repo for build
1:38:44 PM: No cached dependencies found. Cloning fresh repo
1:38:44 PM: git clone https://github.com/katgolek/netlify-test
1:38:45 PM: Preparing Git Reference refs/heads/main
1:38:45 PM: Parsing package.json dependencies
1:38:46 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'build/' in the Netlify UI
1:38:46 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'functions' versus 'functions/' in the Netlify UI
1:38:46 PM: Starting build script
1:38:46 PM: Installing dependencies
1:38:46 PM: Python version set to 2.7
1:38:47 PM: v12.18.0 is already installed.
1:38:48 PM: Now using node v12.18.0 (npm v6.14.4)
1:38:48 PM: Started restoring cached build plugins
1:38:48 PM: Finished restoring cached build plugins
1:38:48 PM: Attempting ruby version 2.7.1, read from environment
1:38:49 PM: Using ruby version 2.7.1
1:38:50 PM: Using PHP version 5.6
1:38:50 PM: Started restoring cached node modules
1:38:50 PM: Finished restoring cached node modules
1:38:50 PM: Installing NPM modules using NPM version 6.14.4
1:38:52 PM: npm ERR! code ENOTSUP
1:38:52 PM: npm ERR! notsup Unsupported engine for @sveltejs/kit@1.0.0-next.109: wanted: {"node":"^12.20 || ^14.13.1 || >= 16"} (current: {"node":"12.18.0","npm":"6.14.4"})
1:38:52 PM: npm ERR! notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.109
1:38:52 PM: npm ERR! notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.109
1:38:52 PM: npm ERR! notsup Required: {"node":"^12.20 || ^14.13.1 || >= 16"}
1:38:52 PM: npm ERR! notsup Actual:   {"npm":"6.14.4","node":"12.18.0"}
1:38:52 PM: npm ERR! A complete log of this run can be found in:
1:38:52 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-05-25T11_38_52_642Z-debug.log
1:38:52 PM: Error during NPM install
1:38:52 PM: Creating deploy upload records
1:38:52 PM: Build was terminated: Build script returned non-zero exit code: 1
1:38:52 PM: Failing build: Failed to build site
1:38:52 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
1:38:52 PM: Finished processing build request in 9.423917579s

**Comment by Conduitry** [comment]
As the error message says, you need to use a newer version of Node. Netlify lets you control what version you get instead of their default.

**Comment by katgolek** [comment]
Thanks, it helped, I wasn't aware I can change Netlify default version

**Comment by PotatoKilla** [comment]
> As the error message says, you need to use a newer version of Node. Netlify lets you control what version you get instead of their default.

could you walk me through how to do this? thanks

**Comment by BrentLabasan** [comment]
> > As the error message says, you need to use a newer version of Node. Netlify lets you control what version you get instead of their default.
> 
> could you walk me through how to do this? thanks

https://answers.netlify.com/t/specifying-a-node-version/9701

**Comment by katgolek** [comment]
Set a NODE_VERSION and NPM_VERSION as environment variables in build settings.
Add a  .nvmrc file to the site’s base directory in your repository and state your node version there for example 14.16.0. 

https://docs.netlify.com/configure-builds/manage-dependencies/

**Comment by JorisIvo** [comment]
> Add a .nvmrc file to the site’s base directory in your repository and state your node version there for example 14.16.0.
Can you give an example of this?

**Comment by mcurcija** [comment]
> > Add a .nvmrc file to the site’s base directory in your repository and state your node version there for example 14.16.0.
> > Can you give an example of this?

I had the same problem after upgrade: 

Installation section in README warns explains it:  
https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify#installation
