### ISSUE TITLE
Site generated with static adapter doesn't work with GitHub pages

### ISSUE THREAD

**Issue by amccausl** [sveltejs/kit#1553]
**Describe the bug**
Generated page throws errors when deployed to GitHub pages.  GitHub pages blocks access to any filename or directory that begins with an underscore, so requests to `_app/*` return an html 404 page and fail module load

**Logs**
Browser console error:
```
Loading module from “https://amccausl.github.io/sveltekit-pages-demo/_app/start-77f2cb3f.js” was blocked because of a disallowed MIME type (“text/html”).
```

**To Reproduce**
- `npm init svelte@next` (https://github.com/amccausl/sveltekit-pages-demo/commit/977f080b67cc92c615d4f14fadbfa2c731e38de9)
- add `static` adapter to output to `docs` folder, run build (https://github.com/amccausl/sveltekit-pages-demo/commit/c9909a4c23d7911fe6e8769bd897aa1852586c86)
- configure github pages to host the docs directory
- load the github pages url

Example:
- repo: https://github.com/amccausl/sveltekit-pages-demo
- page: https://amccausl.github.io/sveltekit-pages-demo/index.html

**Expected behavior**
Output from the static build should work with GitHub pages by default, or there should be a config option on static adapter to allow it to work (maybe replace filenames programmatically?).  Would also work with new static pages adapter.

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 46.69 GB / 50.01 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.1.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.11.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/kit: 1.0.0-next.109 => 1.0.0-next.109
    svelte: ^3.34.0 => 3.38.2
```

- Browser: all

- Adapter: static
</details>

**Severity**
- annoying
  - Can workaround with a post-build script to rename files and directories that start with an underscore prefix and replace all references in files

Example workaround script:
```sh
#!/usr/bin/env bash
mv docs/_app docs/app
find ./docs -type f -exec sed -i -e 's/\/_app/\/app/g' {} \;
```

**Comment by dominikg** [comment]
did you add `.nojekyll` file? see https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

**Comment by amccausl** [comment]
I haven't.  Didn't know about that, looks like it would do the trick.  Will give it a try tonight :)

**Comment by amccausl** [comment]
Adding `.nojekyll` file to `static` directory works as expected 👍

**Comment by eboatwright** [comment]
> Adding `.nojekyll` file to `static` directory works as expected 👍

This just saved me! Thanks so much for this thread
