### ISSUE TITLE
Initialize SvelteKit project with Yarn

### ISSUE THREAD

**Issue by AleCandido** [sveltejs/kit#1557]
**Describe the bug**
I was not able to initialize with `yarn`, i.e. the command `yarn create svelte@next foo` is failing.

**To Reproduce**
- `yarn`: 2.4.1
- `node`: v16.1.0

Then run `yarn create svelte@next foo`.

**Expected behavior**
Initialize the same way of `npm init svelte@next foo`

**Stacktraces**
<details><summary>yarn output</summary>
<pre><code>
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 638ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: Done in 1s 699ms

(node:66799) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/alessandro/.yarn/berry/cache/create-svelte-npm-2.0.0-next.71-3c988c4861-7.zip/node_modules/create-svelte/bin.js:2
import fs from 'fs';

^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.external_module_.Module._load (/tmp/xfs-14e6a52a/dlx-66788/.pnp.js:4968:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
</code></pre>
</details>

**Severity**
I have found a workaround and I can still use `npm`, so **low**.

**Additional context**
I found a workaround: searching on stackoverflow I found a [related question](https://stackoverflow.com/questions/58384179/syntaxerror-cannot-use-import-statement-outside-a-module) and somewhere else (I don't remember where, most likely in [yarn documentation](https://yarnpkg.com/getting-started/migration#step-by-step)) I get the second bit of the equation and the two things together made the command working:

1. add immediately a `package.json`
```json
{
   "type": "module"
}
```
2. add the following line in `.yarnrc.yml`
```yaml
nodeLinker: "node-modules"
```

I actually don't know how bad is what I'm doing, it looks to me that I'm able to revert the two tricks right after, and I hope the thing should not be incompatible overall. But I just know this way it's running, and doing what expected.

**Comment by benmccann** [comment]
We don't support Yarn and recommend against using it: https://kit.svelte.dev/faq#integrations

**Comment by AleCandido** [comment]
Sorry to have opened another PR, keep searching I even found an older issue #993, unfortunately I just found workarounds before the disclaimer...

I will follow the advice and drop yarn for svelte.
