### ISSUE TITLE
Ability to have ignored parameter in prerendered path

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1561]
https://github.com/sveltejs/kit/issues/1533 was requesting to have an ignored parameter in the path. The parameter is unused on the server-side so they'd like to be able to prerender the page without specifying the parameter, but they'd like to use the parameter on the client-side still in `onMount`

**Comment by johnnysprinkles** [comment]
Lol, my 1000 words in 20. I think the confusion is when I said "parameterized route" I meant actually parameterized, i.e. `/tshirt/[size]` when size is s, m, l, xl isn't actually parameterized, in my view, that's just 4 routes. I'm going to look into possibly making a new adapter, "adapter-static-dynamic" but a better name of course.

**Comment by benmccann** [comment]
I don't think you can really do this with the existing adapter API. You need support in prerendering which is in the core SvelteKit library

**Comment by johnnysprinkles** [comment]
That is true, `adapter-static` seems to just a lightweight wrapper around util/prerender.

**Comment by benmccann** [comment]
It seems the issue with having an ignored parameter though would be figuring out how it should show up in the URL. You'd want SvelteKit to be able to do that. I'm not quite sure what that'd look like, so I'm going to close this until there's a good proposal for it
