### ISSUE TITLE
Unable to install adapter-node

### ISSUE THREAD

**Issue by thislooksfun** [sveltejs/kit#1562]
**Describe the bug**
Running `npm i -D sveltejs/adapter-node@next` results in the error `Could not install from "sveltejs/adapter-node@next" as it does not contain a package.json file.`

**Logs**
N/A

**To Reproduce**
Run `npm i -D sveltejs/adapter-node@next`

**Expected behavior**
It should actually install

**Stacktraces**
N/A

**Information about your SvelteKit Installation:**
N/A

**Severity**
Fully blocking any build-related items, including previewing and deploy.

**Additional context**
N/A

**Comment by Conduitry** [comment]
It's `npm i -D @sveltejs/adapter-node@next`, not `npm i -D sveltejs/adapter-node@next`. The package name begins with an `@`.

**Comment by thislooksfun** [comment]
Yeah I just realized that. Feels dumb man.
