### ISSUE TITLE
CSS flickering when importing css using adapter-node 

### ISSUE THREAD

**Issue by diagraphic** [sveltejs/kit#1565]
Hey there hope all is well, and everyone is well.  There's an odd bug when importing css or writing css in components when using adapter-node.  Everything will flicker with nothing styled.  Things render fine when not using that specific adapter.   A run around is to import the css from the public directory in your app.html meta tags, that css will render right away if using adapter-node.  Just wondering if this is a bug or something I'm unfamiliar with.

**Comment by RNR1** [comment]
I also ran into this, but I noticed that it is only happening in the development environment, still pretty annoying.

**Comment by ignatiusmb** [comment]
Please provide a complete and minimal reproducible example. Also, can you check if #967 fits your problem?
