### ISSUE TITLE
Additional line is needed in `netlify.toml` for `adapter-netlify`

### ISSUE THREAD

**Issue by benaltair** [sveltejs/kit#1568]
**Describe the bug**
After updating to the latest Netlify CLI 3.31.14 it asked me what build command to run after running `netlify dev`. Among the options were Svelte and Vite commands. After selecting `run dev` from Svelte, it gave me this message:
```
Add `framework = "svelte"` to [dev] section of your netlify.toml to avoid this selection prompt next time
```
More is described here:
https://docs.netlify.com/configure-builds/file-based-configuration/#netlify-dev

**To Reproduce**
Using Kit 109 and Netlify CLI 3.31.14, you should see the prompt after running `netlify dev`. Keep in mind you'll need to following [these instructions](https://docs.netlify.com/cli/get-started/) to set up the Netlify CLI first.

In my repo, the following `netlify.toml` file was present:
```
[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"
```

I've since added the line to the end:
```
[build]
  command = "npm run build"
  publish = "build/"
  functions = "functions/"

[dev]
  framework = "svelte"
```

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 9.16 GB / 31.92 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.212
    Edge: Spartan (44.19041.964.0), Chromium (90.0.818.66)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.109 => 1.0.0-next.109
    svelte: ^3.38.2 => 3.38.2
    vite: ^2.3.4 => 2.3.4
```

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
**Netlify**
</details>

**Severity**
This is mild severity, quick fix in the readme I think? I'll submit a PR but leaving this here in case it needs to be updated in any setup scripts, etc.

**Comment by kvn-shn** [comment]
Not OP but sometimes I use `netlify dev` when I want to test locally if my site is behaving correctly inside the actual Netlify environment regarding Netlify redirect rules, environment variables etc.

**Comment by kvn-shn** [comment]
My PR in Netlify Dev got merged. So `svelte-kit` should now be detected automatically and `netlify.toml` doesn't have to be adjusted at all (regarding the framework).

**Comment by benmccann** [comment]
Thank you @kvn-shn
