### ISSUE TITLE
Config for "manualChunks" not making it to Vite

### ISSUE THREAD

**Issue by johnnysprinkles** [sveltejs/kit#1571]
**Describe the bug**
If you put something like this in your svelte config file, the manualChunks never make it to Vite because `rollupOptions.output` isn't spread in.

    kit: {
      vite: {
        build: {
          rollupOptions: {
            output: {
              manualChunks: {}

Why does that matter?

The vendor chunk logic comes from [Vite here](https://github.com/vitejs/vite/blob/4112c5d103673b83c50d446096086617dfaac5a3/packages/vite/src/node/build.ts#L564), and that might not always be what you want. That logic just takes the NPM dependencies for all your entry points and throws them into one vendor chunk. In my case I'm using D3 to make some graphs on my index route, but I'd like to not have all the other pages pay that JS download price on initial load.

There's an easy fix mentioned in https://github.com/vitejs/vite/issues/1683 but that doesn't work for SvelteKit at the moment because the output options are just overridden.

If we can set the `manualChunks` option we have a lot of flexibility. We can set to empty object to simply delete the vendor chunk concept, or if I had multiple pages using D3 and wanted shared cacheability I could make a manual D3 chunk like:

    manualChunks: {
      d3: [
        'd3-array',
        'd3-shape',
        'd3-scale',
      ]
    }

Pull request to come shortly on this, it's a simple one-liner.

**Comment by paul-schwendenman** [comment]
I've cloned the repo locally to try this out and I am getting an error on build. @johnnysprinkles do you have a working example somewhere that I could try?

To recreate, I added: 

```
		vite: {
			build: {
				rollupOptions: {
					output: {
						manualChunks: {
							lodash: ['lodash']
						}
					}
				}
			}
		}
```
to `svelte.config.js` in the hacker news example and I get the following error. 

```
The "output.manualChunks" option is not supported for "output.inlineDynamicImports".
> The "output.manualChunks" option is not supported for "output.inlineDynamicImports".
Error: The "output.manualChunks" option is not supported for "output.inlineDynamicImports".
```

Note, I get the same error with different `manualChunk` configs. I also got an error in my project after installing the local build. I tried disabling `inlineDynamicImports` but that config is protected by sveltekit.

Let me know if I should just make a new issue.

**Comment by johnnysprinkles** [comment]
I can repro. I have a SvelteKit project that was born on May 21st and I have it `npm link`ed to the latest @sveltejs/kit and the "manualChunks" work fine. I can set to undefined and bam, no vendor chunk. Assuming named chunks of specific npms work as well.

I created a brand new SvelteKit project via `npm init svelte@next` just now, similarly npm linked, and manualChunks appears to be ignored. I'm not seeing the error message you see though when doing an "npm run build".

I think a separate issue would be best.

**Comment by johnnysprinkles** [comment]
The delta between my two sveltekit projects above is vite 2.3.2 => 2.3.7 and vite-plugin-svelte 10 => 11. I imagine the regression is in there somewhere.

**Comment by johnnysprinkles** [comment]
**Edit**: I think I wasn't linking correctly, redid the "npm link" on both sides and I can repro your error message.

**Comment by johnnysprinkles** [comment]
OK this is weird. My prime use case is just disabling the vendor chunk, which I can do with `manualChunks: undefined` successfully. I will certainly want to make manual chunks as well at some point, as you want to right now, but if I pass an object, even an empty object, I get your

> The "output.manualChunks" option is not supported for "output.inlineDynamicImports".

I would create a new bug and paste this message in there.

**Comment by johnnysprinkles** [comment]
I hacked my @sveltejs/kit locally to comment out `// inlineDynamicImports: true` and everything works as expected with a lodash chunk on the Sveltekit demo app:

```
vite v2.3.7 building for production...
✓ 37 modules transformed.
.svelte-kit/output/client/_app/assets/svelte-logo.87df40b8.svg                           1.85kb
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-ext-400-normal.b3140dd3.woff2   16.11kb
.svelte-kit/output/client/_app/assets/fira-mono-cyrillic-400-normal.046b609f.woff2       9.08kb
.svelte-kit/output/client/_app/assets/fira-mono-greek-ext-400-normal.8659ae46.woff2      7.85kb
.svelte-kit/output/client/_app/assets/fira-mono-greek-400-normal.1f8b3a07.woff2          10.48kb
.svelte-kit/output/client/_app/assets/fira-mono-latin-ext-400-normal.b6331a25.woff2      11.84kb
.svelte-kit/output/client/_app/assets/fira-mono-latin-400-normal.a2f9dbe8.woff2          16.44kb
.svelte-kit/output/client/_app/assets/fira-mono-all-400-normal.0d19eb5d.woff             75.54kb
.svelte-kit/output/client/_app/manifest.json                                             2.69kb
.svelte-kit/output/client/_app/error.svelte-dff64c8c.js                                  1.19kb / brotli: 0.57kb
.svelte-kit/output/client/_app/pages/__layout.svelte-e3aa2c23.js                         4.62kb / brotli: 1.51kb
.svelte-kit/output/client/_app/pages/about.svelte-9a32fa08.js                            2.39kb / brotli: 0.90kb
.svelte-kit/output/client/_app/pages/index.svelte-a233ce63.js                            5.38kb / brotli: 2.07kb
.svelte-kit/output/client/_app/chunks/index-793954da.js                                  0.48kb / brotli: 0.28kb
.svelte-kit/output/client/_app/pages/todos/index.svelte-de105a7e.js                      6.14kb / brotli: 2.22kb
.svelte-kit/output/client/_app/assets/start-a8cd1609.css                                 0.16kb / brotli: 0.10kb
.svelte-kit/output/client/_app/chunks/index-72c96ff2.js                                  9.14kb / brotli: 3.70kb
.svelte-kit/output/client/_app/assets/pages/__layout.svelte-d4883a00.css                 5.04kb / brotli: 1.35kb
.svelte-kit/output/client/_app/assets/pages/about.svelte-4db5be0d.css                    0.11kb / brotli: 0.07kb
.svelte-kit/output/client/_app/assets/pages/index.svelte-078f1a0b.css                    1.35kb / brotli: 0.36kb
.svelte-kit/output/client/_app/start-79f0e79a.js                                         17.89kb / brotli: 5.67kb
.svelte-kit/output/client/_app/assets/pages/todos/index.svelte-ef0435f2.css              3.71kb / brotli: 0.86kb
.svelte-kit/output/client/_app/chunks/lodash-bb6d3078.js                                 69.41kb / brotli: 21.63kb
```

I think we just need a way to turn off inlineDynamicImports, to make it's value dynamic depending on whether there are manualChunks.

**Comment by paul-schwendenman** [comment]
@johnnysprinkles wow, thanks for looking into this. I'll make a new issue and link this one, thanks again!
