### ISSUE TITLE
kit@110: removed lines from .gitignore in demo project

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1581]
**Describe the bug**
From `1.0.0-next.110` in .gitignore of demo project are removed lines:

```
/build
/functions
```

and is added `/package`.

Is this a mistake?

WE still need `/build` in .gitignore, right?

**Comment by benmccann** [comment]
Yeah, I'd tend to agree. Though we may want to handle this on a per-adapter basis. See https://github.com/sveltejs/kit/pull/1436#issuecomment-841964176 for more discussion

**Comment by jthegedus** [comment]
Yes, I would like to voice again that **Adapter specific** ignore entries should be handled by the adapter or their instructions. `/functions` in the template may be useful for the Netlify users with default dirs, but disadvantages other adapter users by ignoring dirs they need.
