### ISSUE TITLE
Hash collision with fetch body in load

### ISSUE THREAD

**Issue by ion1** [sveltejs/kit#1582]
**Describe the bug**
When `fetch` is called with a body in `load`, the resulting `svelte-data` in the server-rendered HTML uses a 32-bit hash of the body to associate the responses with the requests.

Hash collisions might end up being a problem. They will not happen often, but that might just make it harder to debug once one eventually happens.

The result of the client-side `fetch` for the second request will be a copy of the result for the first one.

**Logs**
N/A

**To Reproduce**
Clone https://github.com/ion1/svelte-kit-fetch-body-hash-collision and run it. Observe the result:

![image](https://user-images.githubusercontent.com/39660/120068194-17a97980-c088-11eb-9521-82b781fdd76a.png)

**Expected behavior**
The "Expected" and "Actual" lists should be equal.

**Stacktraces**
N/A

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`

  System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 8.14 GB / 15.94 GB
  Binaries:
    Node: 16.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.37)
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.110
    svelte: ^3.34.0 => 3.38.2

- Your browser
Any browser which runs JavaScript will exhibit the problem.

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Any adapter will exhibit the problem.
</details>

**Severity**
This is only going to be a problem when doing multiple fetch requests with bodies to the same endpoint and when a hash collision occurs.

**Additional context**
N/A

**Comment by benmccann** [comment]
We're aware, but this seems quite rare. I'm going to close this since it doesn't have any suggested alternative

**Comment by ion1** [comment]
> I'm going to close this since it doesn't have any suggested alternative

One option would be to use a hash with many more bits, such as SHA-256. Another option would be to include the body verbatim and assume that it will be small in the first place or after compression.

**Comment by CounterPillow** [comment]
While SHA-256 can be hardware accelerated in modern systems, https://en.wikipedia.org/wiki/SipHash may be a more efficient alternative for a pure JS implementation as an alternate hashing algorithm.

**Comment by benmccann** [comment]
Hmm. I hadn't realized we implemented our own hash function:

https://github.com/sveltejs/kit/blob/eb96322f25b08af8e0f814a825a5db28c6794f50/packages/kit/src/runtime/hash.js

I'd have expected one of the off-the-shelf algorithms to be used. It might be worth a code comment explaining at least

**Comment by ion1** [comment]
One more option would be to discard the cached responses from the HTML if there are two with the same hash but different bodies.

**Comment by Rich-Harris** [comment]
Reopening for now.

> Hmm. I hadn't realized we implemented our own hash function:

We didn't, that would be an act of lunacy! It's `djb2`, which is commonly used because it's compact, performant, and is _pretty good_ at producing random hashes that don't collide. The question we need to answer is whether the chance of accidental collisions is infinitesimal (in which case there's no sense in using a chunkier hashing function) or merely 'small' in which case maybe we should. But we'd need to find something better: https://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed



> Another option would be to make sure the cached responses are listed in the order in which `load` calls `fetch` (rather than the order in which the responses trickle in)

I'd be hesitant for us to do this, since it's not unheard of to do this sort of thing:

```js
export async function load({ page, fetch }) {
  const { id } = page.params;

  const props = browser
    ? cache.get(page.params.id)
    : fetch(`/data/${id}.json`).then(r => r.json());

  return { props };
}
```

**Comment by dominikg** [comment]
more info about hashing algorithms https://github.com/rurban/smhasher

**Comment by benmccann** [comment]
I added some docs in https://github.com/sveltejs/kit/pull/2059. I'm not sure if there's more to do here? I'll close for now. We can reopen if there's something actionable we'd like to do
