### ISSUE TITLE
(adapter-netlify): _redirects file gets overwritten instead of changed

### ISSUE THREAD

**Issue by roschaefer** [sveltejs/kit#1585]
**Describe the bug**
The documentation clearly says:
> During compilation a required "catch all" redirect rule is automatically appended to your _redirects file. (If it doesn't exist yet, it will be created.)

See: https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify#using-netlify-redirect-rules

This is not quite true. When I put my own `_redirects` into either the root directory or `build/` folder, the file gets overwritten.

**To Reproduce**
1. Create a file `build/_redirects` and add some content:
```
/workshops    kategorie=:kategorie /.netlify/functions/render 200!
```
2. Run `svelte-kit build`
3. Content of `build/` is:
```

/* /.netlify/functions/render 200
```

> If possible, we recommend creating a small repo that illustrates the problem.

You can clone my repository and checkout my commit: https://github.com/roschaefer/tanzimpulse/pull/1/commits/984ba91e3f5464f51181d45f61e82a4497582ff7

**Expected behavior**

Expected content of `build/_redirects` should be:
```
/workshops    kategorie=:kategorie /.netlify/functions/render 200!

/* /.netlify/functions/render 200
```

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Linux 5.12 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 PRO 4650U with Radeon Graphics
    Memory: 18.48 GB / 30.65 GB
    Container: Yes
    Shell: 3.2.2 - /usr/bin/fish
  Binaries:
    Node: 14.15.4 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.10 - ~/.asdf/installs/nodejs/lts/.npm/bin/yarn
    npm: 6.14.10 - ~/.asdf/installs/nodejs/lts/bin/npm
  Browsers:
    Chromium: 91.0.4472.77
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109
    svelte: ^3.38.2 => 3.38.2
```

- Your browser
Irrelevant

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
It's `adapter-netlify`
</details>

**Severity**

A bit unfortunate but not a blocking issue. For my use case, this would allow to prerender sites (+performance) while catering noscript-browsers(+accessiblity).

**Additional context**
I asked at Discord: https://discord.com/channels/457912077277855764/819723698415599626/848204698808352788

> Hey everyone :wave: does anybody know if it's possible to configure netlify-adapter in a way that `/workhops` gets served by a pre-rendered page but `/workshops?filter=something` hits the serverless function?

> I figured it out myself! In build/_redirects:
```
/workshops    kategorie=:kategorie /.netlify/functions/render 200!

/* /.netlify/functions/render 200
```
> The relevant documentation is here: https://docs.netlify.com/routing/redirects/rewrites-proxies/#shadowing

**Suggestions to Fix**

I'm quite sure it's because the entire `build/` folder gets deleted here: https://github.com/sveltejs/kit/blob/028abd9cc6e1ab40434d0bbd71664ba0b2ea19d9/packages/adapter-netlify/index.js#L15
`appendFileSync` would never find an existing file: https://github.com/sveltejs/kit/blob/028abd9cc6e1ab40434d0bbd71664ba0b2ea19d9/packages/adapter-netlify/index.js#L42

Furthermore, I would suggest that users can put a `_redirects` file *into the project root folder* instead of the `build/` folder. This would allow users to `.gitignore` the `build/` folder.

**Comment by kvn-shn** [comment]
I believe there is a small misunderstanding. :) The `_redirects` file belongs into the project's `static` folder (not `build` nor your project's root).

**Comment by roschaefer** [comment]
@kvn-shn you're right! Should the documentation be updated to avoid further confusion? Or is it just me and we can assume that people understand that they have to put netlify configuration files into `/static`?

**Comment by roschaefer** [comment]
I'm going to close this non-issue. Feel free to ask me if I should send a PR to update docs.
