### ISSUE TITLE
Move `custom-extensions` test app into `options` test app

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1592]
**Is your feature request related to a problem? Please describe.**
There's no reason to have a dedicated app for testing the custom extension config, it slows things down unnecessarily (if only by a small amount).

**Describe the solution you'd like**
Move the `custom-extensions` tests into `options`

**How important is this feature to you?**
low hanging fruit but also low priority

**Comment by sidharthv96** [comment]
Plucked that low hanging fruit :)
