### ISSUE TITLE
302 undefined in adapter-node

### ISSUE THREAD

**Issue by efeerdogru** [sveltejs/kit#1597]
If redirection logic put in `hooks.ts` files `Handle` method, after building with `adapter-node` it displays, for example;

```bash
> Using @sveltejs/adapter-node
  302 /about -> undefined
  ✔ done
```

**To reproduce**

* With default install, (in my example with TypeScript), in `hooks.ts` file, add this code.
* Then add `adapter-node` package.
* Then run `npm run build`

```js
export const handle: Handle = async ({ request, render }) => {
  if (request.path.startsWith("/about")) {
    return {
      status: 302,
      headers: {
        Location: `/login?r=${encodeURIComponent(request.path)}`
      }
    };
  }
  // Rest of the code...
```

Note: It works fine with `npm run preview`

**Comment by edwindj** [comment]
Running into same issue...

**Comment by ignatiusmb** [comment]
All adapters will always prerender pages by default while building per [its contract](https://kit.svelte.dev/docs#writing-an-adapter), you'll need to guard the redirection with the `prerendering` flag from `$app/env`, or turn them off completely in the config.
