### ISSUE TITLE
Static-adapter build error: cannot read property 'copy_static_files' of undefined

### ISSUE THREAD

**Issue by stanf0rd** [sveltejs/kit#1602]
**Describe the bug**
On build try using `@sveltejs/adapter-static` error occured:
`Cannot read property 'copy_static_files' of undefined`

**Logs**
Please include browser console and server logs around the time this bug occurred.
![image](https://user-images.githubusercontent.com/28190898/120117747-f7181700-c18e-11eb-9cbe-a7013e5185ea.png)

**To Reproduce**
Start default SvelteKit app, and add static adapter to `svelte.config.js`:
```js
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-static';

const config = {
	preprocess: preprocess(),
	kit: {
		adapter: adapter(),
		target: '#svelte'
	}
};

export default config;
```

**Expected behavior**
Project built successfully.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

 System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.75 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.109 
    svelte: ^3.34.0 => 3.38.2 

- Your adapter: static
</details>

**Severity**
Blocking your usage of SvelteKit entirely

**Additional context**
I see Typescript type error here:
![image](https://user-images.githubusercontent.com/28190898/120117947-28ddad80-c190-11eb-83fb-c9628a6975ba.png)

If I fix type error:
`async adapt({ utils }) {` => `async adapt(utils) {`

the build goes much better (no favicon error seems much less tragically)
![image](https://user-images.githubusercontent.com/28190898/120118040-b6210200-c190-11eb-83a5-4836cb60b5ef.png)

**Comment by stanf0rd** [comment]
Sorry. Reinstalling node_modules fixed the problem!

**Comment by sinedie** [comment]
@stanf0rd got the same issue. I can solve the utils type error, but on a CI/CD enviroment it wont work cause I can't change it everytime... does it worked for you without fixing that utils typo?

**Comment by sinedie** [comment]
Nvm, just `npm upgrade` and it will solve

**Comment by ThatXliner** [comment]
I am having this issue and just found this...

**Comment by ThatXliner** [comment]
Nevermind, patched my node_modules with the latest version in this repo... Please make a new release or something
