### ISSUE TITLE
Prefetch broken — `Cannot read property 'load' of undefined`

### ISSUE THREAD

**Issue by madeleineostoja** [sveltejs/kit#1605]
**Describe the bug**
Trying to `prefetch` a route programatically errors when trying to call `load` on the prefetched route

**Logs**

<img width="719" alt="Screen Shot 2021-05-31 at 10 59 26 AM" src="https://user-images.githubusercontent.com/6374876/120122802-4bf37600-c1ff-11eb-94ed-9ae20baf8646.png">

**To Reproduce**

Call `prefetch` on a route if `browser` is true

```js
if (browser) {
  prefetch('/some-route')
}
```

**Expected behavior**
Prefetch should work...

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
System:
    OS: macOS 11.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 684.30 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 74.0
    Safari: 14.0.3
```

- Your browser: Chrome

- Your adapter: `adapter-static`, though occurs in dev and preview as well
</details>

**Severity**
Moderate — cannot use programatic prefetching to improve performance.

**Comment by benmccann** [comment]
Thanks for the report. If you have a repo that reproduces this it might help a bit

**Comment by madeleineostoja** [comment]
Sure thing, I'm playing with sveltekit on my [personal portfolio](https://madeleineostoja.com), I'll clean up a few private vars and open it up soon

**Comment by madeleineostoja** [comment]
Here's a repro: https://github.com/madeleineostoja/portfolio/tree/prefetch-bug

I added a simple prefetch in `/src/routes/index.svelte` to demonstrate.

Steps: 

- Pull down, install deps, run `dev`
- Open console to see error

Not exactly a minimal repro because it's a whole project, but I'm flat out atm so hopefully that's still helpful!

**Comment by moritzebeling** [comment]
`Cannot read property 'error' of undefined` is the most common error I run into. Unfortunately it provides no idea, in which component the error was caused or how it could be resolved. This makes debugging extremely hard.

**Comment by benmccann** [comment]
I think this might be fixed now. I just tried https://github.com/madeleineostoja/portfolio/tree/prefetch-bug with the latest version of SvelteKit and don't see the error originally reported. Can you check if you're still seeing this?

**Comment by mquandalle** [comment]
@benmccann I also had this bug and the latest version of SvelteKit fixes it.

**Comment by benmccann** [comment]
thank you for confirming!

**Comment by PedroBraude** [comment]
in the last version i have this bug again.
