### ISSUE TITLE
paths.base not considered for Service worker

### ISSUE THREAD

**Issue by sidharthv96** [sveltejs/kit#1612]
**Describe the bug**
When paths.base is set and service-worker.js is present in the root, the final build has `register("/service-worker.js")`, which throws 404

**Logs**
A bad HTTP response code (404) was received when fetching the script.
VM204 :1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://sidharthv96.github.io/') with script ('https://sidharthv96.github.io/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.

**To Reproduce**
Open https://sidharthv96.github.io/mermaid-live-editor

To help us help you, if you've found a bug please consider the following:

- If possible, we recommend creating a small repo that illustrates the problem.
- Reproductions should be small, self-contained, correct examples – http://sscce.org.

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that Svelte is run by unpaid volunteers in their free time, and issues that follow these instructions will get fixed faster.

**Expected behavior**
paths.base is prepended to service worker path.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

Stack trace goes here...

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`

- Your browser

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
</details>

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

Medium-Low. As it blocks users who need to use Service workers.

**Additional context**

**Comment by ignatiusmb** [comment]
Not necessarily a duplicate, but could be probably be solved in #922 as well. Closing in favor of the mentioned issue.
