### ISSUE TITLE
cannot update sveltekit to next.111 with latest adapters

### ISSUE THREAD

**Issue by kamholz** [sveltejs/kit#1618]
**Describe the bug**
The peer dependencies on the latest `adapter-node` (next.23) appear to make it impossible to update `kit` past next.110. If I try to do so with `npm install @sveltejs/kit@next`, I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving:
npm ERR! Found: @sveltejs/kit@1.0.0-next.111
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^1.0.0-next.111" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @sveltejs/kit@"1.0.0-next.110" from @sveltejs/adapter-node@1.0.0-next.23
npm ERR! node_modules/@sveltejs/adapter-node
npm ERR!   dev @sveltejs/adapter-node@"1.0.0-next.23" from the root project
```

**Expected behavior**
I don't expect `adapter-node`'s peer deps to need to be updated every time `kit` is updated in order to use them together. This hasn't been the case over the past two months and if it's the new norm it will be pretty annoying, since `kit` is updated much more often than `adapter-node`. I hope this is just a hiccup following the new peer dependencies in `adapter-node`.

**Severity**
High severity given how much SvelteKit is in flux and the need to keep up with the latest version.

**Comment by JBusillo** [comment]
This also affects adapter-vercel  (this was issue was raised on Discord).

**Comment by tonprince** [comment]
I had the same issue when using adapter-vercel, resulting in a 'resolve is undefined' error in the handle hook-function. I need to update to sveltekit next.111 but the peer dependency of adapter-vercel does not allow.

**Comment by tonprince** [comment]
Workaround for now:
- Install a new sveltekit starter template
- Manually replace kit-folder in node_modules of your project with the one from the starter template
```

npm init svelte@next my-app
cd my-app
npm install
```

**Comment by frederikhors** [comment]
This also affects `adapter-static`:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: project@0.0.0
npm ERR! Found: @sveltejs/kit@1.0.0-next.111
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"1.0.0-next.111" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @sveltejs/kit@"1.0.0-next.110" from @sveltejs/adapter-static@1.0.0-next.12
npm ERR! node_modules/@sveltejs/adapter-static
npm ERR!   dev @sveltejs/adapter-static@"1.0.0-next.12" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by jthegedus** [comment]
This will likely affect all adapters within the SvelteKit monorepo as they all have the same peer-dep requirement.

**Comment by ignatiusmb** [comment]
Kit monorepo uses pnpm which have no problem handling workspace dependencies. This is likely an issue with npm itself, which perhaps haven't support workspaces fully (yet) or even multiple version 1's, who knows.

Currently, `npm update` locks kit version to `next.110` but upgrades everything else no problem. In the meantime, follow the npm error commands to either force install the latest next version, or manually change the version and force install again.

```sh
npm install @sveltejs/kit@next --force

# or, change the version in package.json and run the following
npm install --force
```

You can also use the `--legacy-peer-deps` flag, but this will significantly increase your lockfile lines

**Comment by kamholz** [comment]
> Kit monorepo uses pnpm which have no problem handling workspace dependencies. This is likely an issue with npm itself, which perhaps haven't support workspaces fully (yet) or even multiple version 1's, who knows.

I'm not so sure this is an issue with workspace dependency support in npm. If I look at `adapter-node`'s package.json in `node_modules/`, I see this:

```
        "peerDependencies": {
                "@sveltejs/kit": "1.0.0-next.110"
        },
```

In other words, the package being published to npm (the repository) has this version number hard-coded. That can't be fixed by using a different local client.

**Comment by ignatiusmb** [comment]
You're right, I overlooked it. https://github.com/sveltejs/kit/pull/1590 should've updated it too like what happens in https://github.com/sveltejs/kit/pull/1543.

**Comment by kamholz** [comment]
> You're right, I overlooked it. #1590 should've updated it too like what happens in #1543.

Yeah, so this is related to my point that kit has typically been released quite a few times between adapter releases. Does this mean that now adapters are always supposed to be republished whenever kit is published, to keep the deps in sync? Or can peer deps be written more flexibly with semver?

**Comment by ClaytonFarr** [comment]
> This will likely affect all adapters within the SvelteKit monorepo as they all have the same peer-dep requirement.

Yep. Looks like same issue is happening with Netlify adapter as well.

**Comment by mylastore** [comment]
this worked for me
```
		adapter: {
			adapt: async () => await node()
		},
```
