### ISSUE TITLE
How to organize src files for the following structure

### ISSUE THREAD

**Issue by treeder** [sveltejs/kit#1629]
I'm probably missing something, but it doesn't seem to cover this in the docs. 

If i have a paths like this: 

/x/SOMEID/things -> returns a list of things belonging to SOMEID
/x/SOMEID/things/ANOTHERID -> returns the specific thing. 

How to I structure the files to represent that?

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
