### ISSUE TITLE
resolve is not a function - hooks.js - handle export

### ISSUE THREAD

**Issue by ryc76** [sveltejs/kit#1631]
**Describe the bug**
Using the example code shown on https://kit.svelte.dev/docs#hooks-handle the handle export is not passed the resolve function.
Further investigation shows that resolve is undefined.

**Logs**
TypeError: resolve is not a function is returned.

**To Reproduce**
Create src/hooks.js and add the following code

```
export async function handle({ request, resolve }) {
	
	const response = await resolve(request);

	return {
		...response,
		headers: {
			...response.headers,
			'x-custom-header': 'potato'
		}
	};
}
```

**Comment by Conduitry** [comment]
`render` was just renamed to `resolve` in next.111 - https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next111

It sounds like you're not on the latest version of `@sveltejs/kit`.

**Comment by akqira** [comment]
Hi,
Just to share, the file Hooks is case sensitive. I'm on last version but I received the same error until I changed hooks.ts to Hooks.ts
