### ISSUE TITLE
$service-worker files exclusion improvements. Make it automatic and Configurable.

### ISSUE THREAD

**Issue by hariombalhara** [sveltejs/kit#1636]
**Is your feature request related to a problem? Please describe.**
`.gitkeep` file available in `assets/some-dir` is available in `$service-worker.files` causing this file to be requested unnecessarily(and surprisingly).

**Describe the solution you'd like**
[Here](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/create_manifest_data/index.js#L389) I see that only one file `.DS_STORE` is excluded from `$service-worker.files`. I would suggest the following
*  All hidden files might be excluded from here by default. There might be other hidden files like vim swap and swo files 
*  An option to toggle the above flag using Svelte config file, just in case someone wants to have complete control.
* A list of files/glob patterns to specify the list of files that you would want to be excluded. This exclusion can also be helpful when you have certain files present which you are not using currently anywhere. Those files probably exist because you are experimenting with something or maybe someone just forgot to remove the file but he removed the actual usage. One more reason can be Open Graph meta tags using an image that isn't used on the website directly but is served from the website when requested.

**Describe alternatives you've considered**
For the time being, I have excluded `.gitkeep` in service-worker.ts which works for me but increases service-worker.js file size unnecessarily.

**How important is this feature to you?**
This is not super important. But I would love to contribute if you can provide the next step here.

**Additional context**
It shows a .gitkeep file being requested from service-worker
<img width="886" alt="Screenshot 2021-06-04 at 12 20 40 AM" src="https://user-images.githubusercontent.com/1780212/120696967-c9064000-c4ca-11eb-8e2e-30b822baaa13.png">

**Comment by benmccann** [comment]
Based off the discussion in https://github.com/sveltejs/sapper/pull/1095 I'm guessing that we might not want to ignore hidden files by default. But it sounds reasonable to provide an option that lets you filter which files are included / ignored

**Comment by hariombalhara** [comment]
@benmccann Thanks for pointing me to the sapper issue. I searched for a similar issue in Sveltekit but couldn't find it there. I didn't think about looking into sapper issues.

I have done the changes not sure if I am in the right direction.

**Comment by ignatiusmb** [comment]
This is now configurable through the [serviceWorker option](https://kit.svelte.dev/docs#configuration-serviceworker), thanks for the PR!

**Comment by julienchazal** [comment]
Hello, just a little improvement request : on my Mac it's `DS_Store` and not `DS_STORE ` as in default kit config
