### ISSUE TITLE
No 404 Error for missing favicon.ico

### ISSUE THREAD

**Issue by Kapsonfire-DE** [sveltejs/kit#1637]
If you don't have a favicon.ico, the dev server isn't giving E404 to the browser and leaves the connection pending.
due browser limit of open connection to a host, sveltekit stops working in browser  when the connection limit is reached
closing tab and reopen it works then again  till reaching connection limit

svelte@next 113

//edit:
to clarify, disable cache with developer console of browser. this will trigger the favicon.ico redownload every navigation

**Comment by Rich-Harris** [comment]
this was fixed at some point
