### ISSUE TITLE
Error when Vite not included in package.json for Netlify-Adapter

### ISSUE THREAD

**Issue by saturnonearth** [sveltejs/kit#1638]
Vite was recently bundled with SvelteKit and not required to be manually listed via package.json. If Vite is not included, Netlify seems to fail on build.

![image](https://user-images.githubusercontent.com/12503538/120533979-55234500-c3af-11eb-8078-631caf1538fa.png)

**Comment by benmccann** [comment]
I have the following in my project and it works just fine:
```
	"devDependencies": {
		"@sveltejs/adapter-netlify": "next",
		"@sveltejs/kit": "next",
		...
	},
```

I'm guessing you have an old version of one or both of the dependencies, but unfortunately I can't tell because you didn't run the command suggested in the issue template
