### ISSUE TITLE
HMR code is added to stringified JavaScript in markup

### ISSUE THREAD

**Issue by kwangure** [sveltejs/kit#1653]
**Describe the bug**
When JavaScript is in a string, HMR code is inserted into it.

```html
<code>
{`
const product = 1 * 1;

export default product;
`.trim()}
</code>
```

is displayed in the browser as 

```javascript
const product = 1 * 1; import * as ___SVELTE_HMR_HOT_API from '/sveltekit-javascript-repro/node_modules/svelte-hmr/runtime/hot-api-esm.js';import { adapter as ___SVELTE_HMR_HOT_API_PROXY_ADAPTER } from '/sveltekit-javascript-repro/node_modules/svelte-hmr/runtime/proxy-adapter-dom.js';if (import.meta && import.meta.hot) { if (false) import.meta.hot.accept(); product = ___SVELTE_HMR_HOT_API.applyHmr({ m: import.meta, id: "/sveltekit-javascript-repro/src/routes/index.svelte", hotOptions: {"preserveLocalState":false,"noPreserveStateKey":["@hmr:reset","@!hmr"],"preserveAllLocalStateKey":"@hmr:keep-all","preserveLocalStateKey":"@hmr:keep","noReload":false,"optimistic":true,"acceptNamedExports":true,"acceptAccessors":true,"injectCss":false,"cssEjectDelay":100,"native":false,"importAdapterName":"___SVELTE_HMR_HOT_API_PROXY_ADAPTER","noOverlay":true}, Component: product, ProxyAdapter: ___SVELTE_HMR_HOT_API_PROXY_ADAPTER, acceptable: true, preserveLocalState: false, emitCss: true, }); } export default product;
```

**Repro**
https://github.com/kwangure/sveltekit-javascript-repro

**Expected behavior**
HMR code should not be injected into strings.

<details>
  <summary>SvelteKit installation information</summary>

System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 1.56 GB / 3.05 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.2.0 - /usr/bin/node
    npm: 7.13.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: ^1.0.0-next.113 => 1.0.0-next.113 
    svelte: ^3.38.2 => 3.38.2 
- Chrome
</details>

**Severity**
It's not severe, but it it annoying. It's possible to work around it by escaping/HTML-encoding the JS text.

I'm not sure whether this is something to be solved at the `vite-plugin-svelte` or `svelte-hmr` level. I can move the issue to the appropriate repro as needed.

Somewhat related issue: https://github.com/sveltejs/kit/issues/1654

**Comment by Conduitry** [comment]
`svelte-hmr` is responsible for doing its own HMR injection, and so I think that would be the best repo for this issue.

**Comment by kwangure** [comment]
Noted. Issue filed. Thanks.
