### ISSUE TITLE
tsconfig generated with errors in the json

### ISSUE THREAD

**Issue by Vanderscycle** [sveltejs/kit#1655]
**Describe the bug**
When I generate a new svelte project using npm install svelte@next TS the tsconfig.json comes with errors.

**Logs**
```json
{
  "compilerOptions": {
  "moduleResolution": "node",
  "module": "es2020",
  "lib": ["es2020"],
  "target": "es2019",
  /**
	  svelte-preprocess cannot figure out whether you have a value or a type, so tell TypeScript
	  to enforce using \`import type\` instead of \`import\` for Types.
	  */
  "importsNotUsedAsValues": "error",
  "isolatedModules": true,
  "resolveJsonModule": true,
  /**
	  To have warnings/errors of the Svelte compiler at the correct position,
	  enable source maps by default.
	  */
  "sourceMap": true,
  "esModuleInterop": true,
  "skipLibCheck": true,
  "forceConsistentCasingInFileNames": true,
  "baseUrl": ".",
  "allowJs": true,
  "checkJs": true,
  "paths": {
	  "$lib/*": ["src/lib/*"]
  }
  },
  "include": ["src/**/*.d.ts", "src/**/*.js", "src/**/*.ts", "src/**/*.svelte"]
}
```

**To Reproduce**
npm install svelte@next, select ts, eslint, prettier 
npx svelte-add tailwindcss

**Expected behavior**
Produce tsconfig.json without errors

**Stacktraces**

**Information about your SvelteKit Installation:**

```bash
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 22.59 GB / 31.35 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.1.0 - /usr/bin/node
    npm: 7.15.0 - /usr/bin/npm
  Browsers:
    Brave Browser: unknown
    Firefox: 89.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.113
    svelte: ^3.34.0 => 3.38.2

```
- Your browse:r brave
- If using a community adapter, the adapter and version
</details>

**Severity**
Annoying, I am sure that I can create a bash file to check the content of the json file

**Additional context**
Any help is appreciated.

**Comment by dummdidumm** [comment]
What exactly is the error and where does it appear?

**Comment by Vanderscycle** [comment]
Sry no gifs
steps taken:
![new](https://user-images.githubusercontent.com/52706578/121243073-28a97600-c852-11eb-8903-c540174dd848.png)
results:
![tsconfig](https://user-images.githubusercontent.com/52706578/121243078-29420c80-c852-11eb-86a7-c447c587855e.png)

**Comment by dummdidumm** [comment]
I still don't understand what the problem with the tsconfig should be, and I don't see any error diagnostics in the pictures, either. If it's about the multiline comments: those are allowed inside tsconfig files, and if your editor shows errors, then that's the editors' problem.
