### ISSUE TITLE
Vite / Svelte isn't recompiling my css code 

### ISSUE THREAD

**Issue by Bradley-H** [sveltejs/kit#1656]
During certain times ( I suspect after X amount of reloads on a certain component ) it stops recompiling my css code. I don't get any error messages in the console or the integrated terminal. But I know when I make changes to my components it doesn't compile. 

here is the only example I can pull

https://i.imgur.com/47h8pCr.png

**Comment by bugbit-io** [comment]
@Bradley-H Have you tried:
1. Deleting node_modules folder and reinstalling
2. Does running a build work properly?
3. Making a new project and copying your files across?

**Comment by GrygrFlzr** [comment]
Without further information, we are unable to identify the issue. Closing for now.
