### ISSUE TITLE
Allow dynamic routes folders to contain several params

### ISSUE THREAD

**Issue by gterras** [sveltejs/kit#1663]
**Is your feature request related to a problem? Please describe.**

Dynamic routes folders are really nice.

They are the only way to get automatic param splitting (other syntaxes like `[...rest].svelte` and `[param1]-[param2].svelte` need extra work to get params to be fully usable) and play well with how sveltekit is supposed to be used (easy param passing from `load()` to endpoints for example). 

The problem is the actual file structure stops making sense as long as you need more than 1 dynamic param. Having something like : 

```
├── data
│   └── [name]
│       └── [date]
│           └── [type]
│               └── [mode]
│                   └── data.json.js
``` 
gets out of control very quickly. 

**Describe the solution you'd like**
Any kind of solution that would provide prepped params while maintaining a reasonable file structure : 

Of course it's tricky since you need to abstract slashes in file names somehow. Would it make sense to have a router option allowing to turn hyphens from multi-params files into slashes ? 

`[param1]-[param2].svelte` would be interpreted as `/param1/param2`.

**Describe alternatives you've considered**
- Having a unreasonable file structure
- Using others file syntaxes and parse params manually   

**How important is this feature to you?**
It's all about convinience in the end so not that important but it would be a nice addition (especially considering that it seems to play along sveltekit principles).

**Comment by benmccann** [comment]
Thanks for the idea, but judging by the initial reaction to this I don't think it's something we'd implement

**Comment by gterras** [comment]
Hi no worries but could you explain quickly why this is not a good idea (or not a good problem)?

**Comment by benmccann** [comment]
One reason is that it makes it harder to work on any SvelteKit project. If you see an open source SvelteKit project you can't understand how to convert between route and URL without first looking at what options are set and if you didn't know or forget to do that then it will cause a lot of confusion.

**Comment by gterras** [comment]
Thanks but if I may this is related to the suggested solution, not the root problem which is that the dynamic folders feature gets less usable the more you use it (somehow conflicts with the nature of the feature which gets more appealing the more you have params), which is exactly why dynamic folders are available in the first place.  

One of the solution would be to allow `[param1]_[param2]` syntax on folders to act like virtual routes, keeping the syntax on par with files and elegantly solving the problem. 

But anyway it seems I'm the only one finding file structure boilerplate annoying, so be it !

**Comment by sebastinez** [comment]
I'm with @gterras on this one, for simpler applications like blogs or landing pages, the current way seems great, but in apps  with URLs like the one showed above it gets really out of hand, and SvelteKit is a no-go, since any current Router is more appropriate than using the SvelteKit router.

Is there maybe the possibility to use a different router than the SvelteKit router, but keep the SSR and other features of SvelteKit?
From what I can see when disabling client-side routing every route is being fetched on the server instead of allowing another router implementation.

**Comment by stephane-vanraes** [comment]
While perhaps a bit cumbersome you can easily solve this with the rest parameters, eventually combined with a matcher.

```html
<!-- src/routes/products/[...slugs=product].svelte -->
<script context="module">
   export async function load({ params }) {
     const [category, id, colour] = params.slugs.split('/');
     // other code
  }
</script>
```
and the matcher could ensure you have three slugs
```js
// /src/params/product.js
export function match(params) {
   return params.split('/').length == 3
}
```

**Comment by gterras** [comment]
Thanks @stephane-vanraes matchers are indeed a great solution for this issue! Now that Sveltekit has a lot of obscure punctuation in router file naming maybe this proposal will be reevaluated some day (since it's admittedly not more confusing that the current state).
