### ISSUE TITLE
Jump links and :target pseudo-class don't work as expected

### ISSUE THREAD

**Issue by MXMLNDML** [sveltejs/kit#1670]
**Describe the bug**
![Safari](https://user-images.githubusercontent.com/42516330/121657554-ca260700-caa0-11eb-81bd-f3c37c844997.gif)
If you click a link with its `href` set to a section on the page (via the fragment of the URI) multiple times in a row the browser won't jump to the section anymore, even if you change the scroll position. This happens every time the fragment is already part of the URI. The only exception I found was if you set `window.location.hash` manually to the URI with the fragment. Then the jump-links work as expected but you have to press them twice to trigger the `:target`pseudo-class. `:target` is not triggered without the `window.location.hash` workaround. By sheer chance, I activated the experimental feature `CSSOM View Smooth Scrolling` and apparently that fixed the issue. But since this flag is non-standard a fix would be helpful.

**Logs**
Browser Console: [Warning] <Routes> received an unexpected slot "default". (index.mjs, line 1667)

**To Reproduce**
Example: https://mxmlndml.github.io/sveltekit-jump-links/
Code repo: https://github.com/MXMLNDML/sveltekit-jump-links

**Expected behavior**
![Firefox](https://user-images.githubusercontent.com/42516330/121657535-c5f9e980-caa0-11eb-8f44-bc530997e603.gif)
Jump links should work like in other browsers (Firefox, Chromium-based) or with vanilla html/css in Safari. Or just like the [SvelteKit docs](https://kit.svelte.dev/docs) in Safari (which claim to be build with SvelteKit). Additionally the `:target` pseudo-class should work the first time you click a link.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- Safari 14.0.2 (desktop), Safari iOS 14.6 (mobile) → won't jump a second time to the section + `:target` not working
- Firefox 89.0 → jump-links work as expected, but `:target` works only after the second time you press the link
</details>

**Severity**
It is just annoying, nothing severe.

**Comment by Rich-Harris** [comment]
Closing, as it looks like we fixed this at some point! My favourite kind of issue
