### ISSUE TITLE
Better error message for missing component

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1678]
I typed the path wrong when trying to import a component from `$lib`. It gave the error message:

>Error: failed to load module for ssr: /src/lib/ComponentIndex/Card.svelte

It sounded to me like it failed to load because there was an error in the component. I didn't realize from the error message that it was because it couldn't find the component

**Comment by andreivreja** [comment]
Anyone interested in tackling https://github.com/sveltejs/kit/issues/1861 ?

I just had to add yet another error message for Firefox + some extra string checks to detect if a module failed to load.

**Comment by Rich-Harris** [comment]
If this should be fixed anywhere, it's in Vite. Short of putting try-catch everywhere and detecting this case with something like `/failed to load module/.test(e.message)` in the catch block, there's nothing we could do regardless of whether we wanted to. I'll close this
