### ISSUE TITLE
Invalid Url on fetch in a store when first loading the page

### ISSUE THREAD

**Issue by iSirThijs** [sveltejs/kit#1680]
**Describe the bug**
Fetch in a custom store rejects with a `TypeError [ERR_INVALID_URL]: Invalid URL: /api/user.json` when first loading the page from the server. Once the svelte app is hydrated and navigating between pages, the error does not happen and the store works fine. 

**Logs**
The `console.error` from the rejection with stack. 
```
TypeError [ERR_INVALID_URL]: Invalid URL: /api/user.json
```

*The custom store:*
```ts
import { derived, writable } from 'svelte/store';
import { session } from '$app/stores';

function createUserStore() {
	// User
	const {subscribe} = derived(session, ($session, set) => {
		if ($session.authenticated) {
			fetch('/api/user.json').then(async (res) => {
				if (res.ok) {
					const user = await res.json();
					set(user);
				}
			}).catch(console.error)
		} else {
			set({});
		}
	});
	return {
		subscribe
	};
}

export const user = createUserStore();
```

The store is accessed in a page like so: 
```
<script lang="ts">
  import { user } from '$lib/Stores/user'
</script>

<header>
  <h2>Mijn Gymles</h2>
  {#if $user && $user.name}
	  Hello {$user.name}
  {/if}
</header>
```

**To Reproduce**
* Create a custom store that fetches from a svelte endpoint (see above for my custom store)
* Access the store on a page 
* Access the page directly with its route

**Expected behavior**
The fetch should not fail on this svelte endpoint url

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  ```
TypeError [ERR_INVALID_URL]: Invalid URL: /api/user.json
      at onParseError (internal/url.js:259:9)
      at new URL (internal/url.js:335:5)
      at new Request (file:///Users/thijsspijker/Repositories/jungle-gym/node_modules/@sveltejs/kit/dist/install-fetch.js:1239:16)
      at file:///Users/thijsspijker/Repositories/jungle-gym/node_modules/@sveltejs/kit/dist/install-fetch.js:1448:19
      at new Promise (<anonymous>)
      at fetch (file:///Users/thijsspijker/Repositories/jungle-gym/node_modules/@sveltejs/kit/dist/install-fetch.js:1446:9)
      at eval (/src/lib/Stores/user.ts:10:7)
      at sync (/Users/thijsspijker/Repositories/jungle-gym/node_modules/svelte/store/index.js:84:28)
      at /Users/thijsspijker/Repositories/jungle-gym/node_modules/svelte/store/index.js:102:9
      at Object.subscribe (/Users/thijsspijker/Repositories/jungle-gym/node_modules/svelte/store/index.js:52:20) {
    input: '/api/user.json',
    code: 'ERR_INVALID_URL'
  }
```
</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- System:
  - OS: macOS 11.4
  - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  - Memory: 176.29 MB / 16.00 GB
  - Shell: 5.8 - /bin/zsh
- Binaries:
  - Node: 14.15.5 - ~/.nvm/versions/node/v14.15.5/bin/node
  - npm: 6.14.11 - ~/.nvm/versions/node/v14.15.5/bin/npm
- Browsers:
  - Firefox: 88.0.1
  - Safari: 14.1.1
- npmPackages:
  - @sveltejs/adapter-netlify: ^1.0.0-next.17 => 1.0.0-next.17 
  - @sveltejs/kit: ^1.0.0-next.115 => 1.0.0-next.115
  - svelte: ^3.34.0 => 3.38.2 

Browser: Chromium Versie 91.0.4472.77 (Official Build, ungoogled-chromium) (x86_64)
Adapter: "@sveltejs/adapter-netlify": "^1.0.0-next.17"
</details>

**Severity**
Low, once the page is hydrated everything works as expected. Only on a page refresh the error returns, but again once hydrated, the store works as expected. 

**Additional context**
/

**Comment by nstuyvesant** [comment]
Check out #1644 to see if you think it may be related. My store also uses fetch and initially fails (if I delete my node_modules, package-lock.json, and .svelte-kit directory and do a fresh npm install before running the dev server).

**Comment by iSirThijs** [comment]
> Check out #1644 to see if you think it may be related. My store also uses fetch and initially fails (if I delete my node_modules, package-lock.json, and .svelte-kit directory and do a fresh npm install before running the dev server).

@nstuyvesant I have looked at your issue, but I think there is a subtle difference. Looking at your code the api call fails on `if(!response.ok)`, which means your fetch gets a response from the server that is not `2xx`. On my api call the fetch is rejected, which means there was a problem with fetch itself. Fetch doesn't reject on HTTP error codes. (correct me if I have interpreted you code wrong)

**Comment by iSirThijs** [comment]
I have tried adding a hardcoded `localhost:3000` before the URL, which seems to allow the request to get through.

**Comment by iSirThijs** [comment]
I have either found a workaround or a solution.

The custom store now exports a `fetchUser` method, which takes `fetch` as an argument. Passing the `fetch` from the `load` function, seems to work.

**Comment by istarkov** [comment]
See the issue, inside `load` function on server `fetch` is overwritten, so for all server side fetches protocol and host is added. In your case you are using globally defined `node-fetch` without protocol and host name. Server side have no idea what is your url and what to fetch then.

The best is just filling your user store initial value inside `load` module function.

Or create something like like this, or fill user store only clientside

```typescript
  import { derived } from 'svelte/store';
  import { page, session } from '$app/stores';

  function createUserStore() {
    // User
    return derived([page, session], ([$page, $session], set) => {
      const protolocol = 'http://';

      fetch(`${protolocol}{$page.host}/api/user.json`)
        .then(async res => {
          if (res.ok) {
            const user = await res.json();
            set(user);
          }
        })
        .catch(console.error);
    });
  }
```

**Comment by istarkov** [comment]
Thats why  load has `fetch` in input parameters.

**Comment by iSirThijs** [comment]
Thank you for the answer. It's not a bug then, but me not fully understanding how SvelteKit works. 

I think I have found a solution now by passing the `fetch` input paramater from `load` into the store.

**Comment by istarkov** [comment]
plz read getSession in sveltekit docs, seems like exactly your case
