### ISSUE TITLE
Build single (non ESM) bundle.js file in SPA-Mode

### ISSUE THREAD

**Issue by icalvin102** [sveltejs/kit#1682]
I am currently building a SPA with svelte and would like to migrate to sveltekit because of the builtin router. The serverside functions of sveltekit are not needed as all content is dynamically loaded from a REST API and SEO is not really a concern.

The `adapter-static` in SPA-Mode seems to be a good fit for hat and the app works as expected (in modern browsers). Sadly one of the project requirements is that it has to support some browsers that do not support import syntax.

**Describe the solution you'd like**
A build option in `adapter-static` that behaves similar to `format: 'iife'` in svelte with rollup.js that creates a single bundle.js file that is not dependant on ESM.

**Describe alternatives you've considered**
I tried [@vitejs/plugin-legacy](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) but I could not get it to work. 

**How important is this feature to you?**
Very important. The ability to build a legacy (non ESM) bundle determines if I use sveltekit or not.

**Comment by Conduitry** [comment]
There's already #12 for differential legacy builds. Whether or not this ends up being implemented as outputting a single .js file seems like an implementation detail to me, so I'm closing this in favor of that issue.
