### ISSUE TITLE
Netlify adapter: prerender field of `svelte.config.js` basically doesn't work - must prerender per page

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/kit#1683]
**Describe the bug**

I built a small blog and tried using this in `svelte.config.js`:

```js
	kit: {
		target: '#svelte',
		adapter: adapter(),
		prerender: {
			crawl: true,
			force: true,
			pages: [
				'/',
				'/blog'
			],
		}
	}
```

and ran a build - none of these pages were built.

i also tried 

```js
			pages: [
				'/',
				'/*',
			],
```

and it didnt work. (you can check by running a build locally and checking the `/build` folder)

the only thing that worked was adding `export const prerender = true;` on a per page basis.

**To Reproduce**

- run build on this: https://github.com/sw-yx/swyxkit/tree/d74a0af94bbec011f58f35b8e787981f005539a6 no HTML pages built
- run build on this: https://github.com/sw-yx/swyxkit/tree/d5ad85f368f02cbf31d36a70d8fceea29b05a382 HTML pages are built

**Severity**

if this field just doesnt work for the netlify adapter yet, we should document or warn.

if this is a fixable or known issue, let me know and i can look into how to fix or document.

**Comment by benmccann** [comment]
@sw-yx is this still happening with the latest versions of SvelteKit and the adapter? I did fix an issue with prerender recently that might have fixed this

**Comment by sw-yx** [comment]
@benmccann i think i updated versions and see no change:
![CleanShot 2021-07-27 at 23 03 42@2x](https://user-images.githubusercontent.com/6764957/127271972-68f29b31-9966-401a-89a1-63f2407b4441.png)

**Comment by benmccann** [comment]
https://kit.svelte.dev/docs#configuration-prerender

`pages` is where crawling starts. It's not a list of pages to prerender. I'd say this is working as expected

`prerender.pages` might not be the best name for the option. Maybe something like `prerender.crawlEntryPoints` would be better?

**Comment by sw-yx** [comment]
@benmccann crawlEntryPoints would be more explicit, yes

**Comment by benmccann** [comment]
filed a request to consider renaming
