### ISSUE TITLE
(re)trigger the load function

### ISSUE THREAD

**Issue by icalvin102** [sveltejs/kit#1684]
**Is your feature request related to a problem? Please describe.**
The new `invalidate(href)` feature in `$app/navigation` is a great way to trigger the execution of a `load` function that works in most cases. The problem is that this only works if one uses the `fetch` function that is provided as an argument to `load`. If a apiClientWrapper is used this does not work anymore. 

**Describe the solution you'd like**
One solution would be to pass a `invalidate` or `update` function to the `load` so that I can be passed as a prop or via context.
This solution would update a specific `load` function instead of a specific fetch url.

```svelte
<script context="module">
import { api } from '$lib/myapi';
export async function load({page, update}){
    const item = await api.getItem(page.params.id);
    return { 
        props: { item, update }
    }
}
</script>

<script>
import Item from '$lib/Item.svelte';
export let item;
export let update;
</script>

<Item {item} />
<button on:click={update}>Reload</button>
```

**Describe alternatives you've considered**
A alternative would be to write a second function in the (non module) script tags that replicates the load function to update data.

**How important is this feature to you?**
Somewhat important. It would make the code cleaner and more reusable but there are easy workarounds.

**Comment by lemmon** [comment]
Exactly what I'm after! Thank you @icalvin102 for describing this issue.

I would also welcome the ability to re-trigger the load fucntion manually. I have a page loading two separate resources using custom api wrapper. It would be great to re-run them manually when needed.

**Comment by etienneburdet** [comment]
`goto()` on the current location shall do the trick, no? Since components won't remount and state variables will be kept, what you have left is basically a run of the `load` function. Or does only work with dynamic routes 🤔 ?

**Comment by icalvin102** [comment]
@etienneburdet `goto()` will only run `load()` if `page.params`, `page.path`, `page.query`, `session` or `context` is used inside of `load` and one of those values has changed since the last run of the load function. This is the desired behavior of `goto` or any form of navigation as this prevents unnecessary loading of (sub)routes. 

What I want is function that is similar to `invalidate` but it should be bound to a `load` function instead of invalidating a URI.

The use case is similar to the one described in #1277 but with a more general solution.

**Comment by lemmon** [comment]
Perhaps something like?

```
goto(href, { replaceState: true, invalidate: true })
```

There are still many different use cases when you want invalidate page data only or invalidate both page and layout altogether. Anyway, the `invalidate` function seems to be no good when you use custom `fetch()` lib.

**Comment by lemmon** [comment]
Or another approach:

```
invalidate(href)
invalidate([ href, href... ])
invalidate({ some: 'options' })
```

**Comment by icalvin102** [comment]
I think the `goto` with `invalidate` option is not really a desired solution as this would cause a reload of all matching (sub)routes. 

Using the `invalidate` function is the better option in my opinion. 

One simple solution that should already work is to add a `uses` method to the
[`load_inputs` in renderer.js](https://github.com/sveltejs/kit/blob/aedec24cc0930186dd6be1d49d69dbf770b234ba/packages/kit/src/runtime/client/renderer.js#L483) that would look like this. 

```js
uses(identifier){
    const { href } = new URL(identifier, new URL(page.path, document.baseURI));					 
    node.uses.dependencies.push(href);
}
```
And change the [`invalidate_ in app/navigation`](https://github.com/sveltejs/kit/blob/aedec24cc0930186dd6be1d49d69dbf770b234ba/packages/kit/src/runtime/app/navigation.js#L28) like follows.

```diff
- async function invalidate_(resource) {
+ async function invalidate_(resource, isURI=true) {
+       if(!isURI) return router.renderer.invalidate(resource);
	const { href } = new URL(resource, location.href);
	return router.renderer.invalidate(href);
}
```

**Usage example:**
 
```svelte
<script context="module">
import { api } from '$lib/myapi';
export async function load({page, uses}){
    uses('item-resource');
    const item = await api.getItem(page.params.id);
    return { 
        props: { item }
    }
}
</script>

<script>
import Item from '$lib/Item.svelte';
import { invalidate } from '$app/navigation';
export let item;
</script>

<Item {item} />
<button on:click={()=> invalidate('item-resource', false) }>Reload</button>

```

**Comment by ajwinkworth** [comment]
Something like this is needed because not all data retrieval is from different endpoints. Sometimes it the same endpoint and the msg describes the data that you want. 

I came here because invalidate was not working and I worked out it was because I had a URL query string. When I invalidated the main endpoint if I did not put in the query string exactly it would no-op. This might not be a bug but it was surprising.

**Comment by noonien** [comment]
Any update on this by any chance?

**Comment by lemmon** [comment]
It doesn't seem to be on a horizon, in my opinion. I have found kind of a hack solution when using an external api library.

```js
// src/routes/void/[x].js
export async function get() {
  return {
    body: '',
  }
}
```

```js
// any page or layout
export async function load({ page, fetch, context }) {
  fetch('/void/document')
  const data = await api.get(`/documents/${page.params.site}/${page.params.id}`)
  return {
    props: {
      data,
      options: context.options,
    },
  }
}
```

Any time you call the `invalidate('/void/document')` function you will trigger reload. Not the most elegant solution and it requires one empty fetch for everty re-load but it's the simplest solution I was able to come up with.

**Comment by icalvin102** [comment]
I requested review on PR https://github.com/sveltejs/kit/pull/1709 but I'm not sure how long this usually takes as this is my first contribution.

**Comment by dummdidumm** [comment]
One possibly better alternative to solve this would be to provide a way to wrap `load`'s `fetch` (maybe inside a startup hook), so you can add your `api` wrapper there and then can use `fetch` inside `load`.

**Comment by noonien** [comment]
In my case, I want to trigger a full component reload. So, basically calling load again.

The load function can be more complex than just doing one fetch which can be invalidated. It can do multiple fetches, for example, and it would be great to be able to not have to keep track of what resources are loaded, and repeating an invalidate for each of them.

**Comment by icalvin102** [comment]
@noonien that is exactly what  PR https://github.com/sveltejs/kit/pull/1709 does. 
It provides a `uses(invalidationKey)` function that can be called to register a arbitrary invalidation key that can be used to reload the whole `load` function with a call to `invalidate(invalidationKey)`.

**Comment by hatemjaber** [comment]
Using "goto" only works the first time it's triggered. I've been having to use window.location to force a full reload in order to get the desired behavior. Could we do something like...
```javascript
goto("path/to/link", {replaceState:true, force:true}
```

**Comment by lazharichir** [comment]
We use codegen to generate an API Client from our backend's OpenAPI spec and therefore we aren't using the provided `fetch`. It makes re-`load`ing very cumbersome. Adding any item to a list requires a full reload using `window.location.href = window.location.href`...

**Comment by dslatkin** [comment]
> We use codegen to generate an API Client from our backend's OpenAPI spec and therefore we aren't using the provided `fetch`. It makes re-`load`ing very cumbersome. Adding any item to a list requires a full reload using `window.location.href = window.location.href`...

@lazharichir I've been looking into the best way to produce/consume OpenAPI specs myself. If you haven't considered it already, I might recommend SvelteKit docs' suggestion to [implement your endpoints programmatically](https://kit.svelte.dev/docs#hooks-handle) so you can use the fetch wrapper as normal.
