### ISSUE TITLE
CSS module generates empty style

### ISSUE THREAD

**Issue by JeromeDeLeon** [sveltejs/kit#1688]
**Describe the bug**
The issue is also appearing on `@svelte/kit` - https://github.com/sveltejs/svelte-preprocess/issues/372 @kaisermann 

**Stacktraces**
_n/a_

**Information about your SvelteKit Installation:**

System:
- OS: Windows 10 10.0.19042
- CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
- Memory: 6.88 GB / 15.87 GB

Binaries:
- Node: 14.17.0
- Yarn: 1.22.10
- npm: 6.14.13

Browsers:
- Chrome: 91.0.4472.101
- Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
- Internet Explorer: 11.0.19041.1

npmPackages:
- @sveltejs/kit: next => 1.0.0-next.115
- svelte: ^3.34.0 => 3.38.2

**Severity**
It's just annoying that it generates a class name for every element even though you're not declaring any style to it.

**Additional context**
_n/a_

**Comment by dummdidumm** [comment]
This sounds like an issue unrelated to SvelteKit itself, given the discussion in the linked issue. My guess it's either Vite or [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte).
