### ISSUE TITLE
prerendering tries to crawl data-ci-src attribute in addition to src and fails

### ISSUE THREAD

**Issue by Shackless** [sveltejs/kit#1697]
**Describe the bug**

I'm using a responsive image library where you set `<img data-ci-src="myimage.png"/>` which is then later translated to `src` in the client based on viewport size and other params. This work fine in dev mode but apparently, adapter-static is validating the `data-ci-src` attribute on build which always fails with a 404 because the src path is relative and will be something like `https://cloudprovider.com/_client_/myimage.png` after the translation. The files referenced in `data-ci-src` don't actually exist in my sveltekit project. 

If I comment out the `data-ci-src` attribute in the `<img>` tag, it works.

Sounds like a regex matching the image tag and an attribute ending in src instead of matching just "src" or something like that (wild guess). 

**Logs**

```bash
> Using @sveltejs/adapter-static
> 404 /myproj/myproj-screenshot-1.png (linked from /work/myproj)
```
**To Reproduce**
Create a new project, add `<img data-ci-src="xyz.png" />` where xyz.png doesn't exist. Build with adapter-static.

**Expected behavior**
Only `<img src="...">` should be validated but not `<img data-src="...">` or `<img data-ci-src="...">`.

**Stacktraces**
<details>
  <summary>Stack trace</summary>

```
Error: 404 /myproj/myproj-screenshot-1.png (linked from /work/myproj)
    at error (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:94:11)
    at visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:176:5)
    at async visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:236:6)
    at async visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:236:6)
    at async visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:236:6)
    at async visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:236:6)
    at async visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:236:6)
    at async visit (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:236:6)
    at async prerender (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:245:5)
    at async Object.prerender (file:///Users/[...]/node_modules/@sveltejs/kit/dist/chunks/index7.js:312:5)
```

</details>

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 350.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Brave Browser: 91.1.25.72
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.25 => 1.0.0-next.26 
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: ^1.0.0-next.115 => 1.0.0-next.115 
    svelte: ^3.38.2 => 3.38.2 
```

</details>

**Severity**
Blocking me from migrating from sapper, because I can't build my page.

**Additional context**
Losely related to #950 which is also about adapter-static image validation.

**Comment by Shackless** [comment]
Is there any way to disable adapter-static image validation altogether as a workaround?

**Comment by benmccann** [comment]
There's no validation done, but prerendering tries to crawl the images. Probably just need to add a space before `src` in the regex:

https://github.com/sveltejs/kit/blob/b1450961b642828a26ac2d1f481a358d3551ffa2/packages/kit/src/core/adapt/prerender.js#L25

**Comment by Shackless** [comment]
Thanks for fixing this so fast. Any idea when it will be released? This is the one and only showstopper preventing me from deploying my migrated site ;)

**Comment by benmccann** [comment]
I just kicked off a release since it had been awhile since we'd done one
