### ISSUE TITLE
Handler violations, browser freezes when using Web Components

### ISSUE THREAD

**Issue by brgrz** [sveltejs/kit#1699]
**Describe the bug**

I think this is a bug with Kit when using Shoelace web components but I am unsure where this stems from. 
The issue does not happen when using regular Svelte, even with Svelte REPL I'm unable to reproduce this issue.

I have thoroughly described the issue here https://github.com/shoelace-style/shoelace/issues/466 where the author of the Shoelace web components library replied with some notes.

I am unsure how to debug this. Maybe someone can help? But I can say the issue (handler violations) occur constantly.
The browser would freeze for up to 10 seconds with a Verbose console log message like `[Violation] 'focusin' handler took 6519ms`

**Logs**
No specific logs available, nothing comes up on dev server side

**To Reproduce**

1. Clone the repo at https://github.com/brgrz/sl-bugs
2. Run npm i
3. Run npm run dev, it will run the SvelteKit app at http://localhost:3000
4. Open Chrome + devtools, in Devtools->Console tab->select All issues (or Verbose)
5. Open the app, click the Open drawer button
6. Inside the drawer try clicking around on the whitespace, try clicking into the input and then onto the whitespace and so forth
7. You should be seeing instances of [Violation] 'focusin' handler took 6519ms in the Console (while this happens, the app will freeze preventing you to click on anything else)

**Expected behavior**
No freezes, no violations/timeouts

**Information about your SvelteKit Installation:**

<details>

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) ia32 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 5.00 GB / 15.78 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 7.11.2 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.106
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.113
    svelte: ^3.38.2 => 3.38.2

- Chrome
- 
</details>

**Severity**
Quite severe

**Comment by brgrz** [comment]
Update: There was a hint this could be dev server thing. So I built the sample using static adapter, deployed it to another server and the issue remains.

**Comment by geoffrich** [comment]
This seems really weird, so I tried to repro it. Some notes:

- As mentioned, this only happens in Kit. A regular Svelte app does not have the issue.
- It also does not happen in Firefox. I was only able to repro in Chrome and Edge. I'm on Windows, so I couldn't test Safari.
- If the drawer is open on initial render (i.e. `<sl-drawer label="Drawer" class="drawer-overview" open>`), the issue does not occur. Once you close and open the drawer, the freezes start happening again.

**Comment by geoffrich** [comment]
I was able to repro [outside of SvelteKit](https://github.com/shoelace-style/shoelace/issues/466#issuecomment-867779948), so I don't think this is a SvelteKit issue. See my linked comment for details, but this is really a perfect storm of an issue, requiring certain components to be present inside the drawer custom element.

The reason this didn't happen in vanilla Svelte is that vanilla Svelte doesn't include a router. SvelteKit has client-side routing and sets tabindex="-1" on the body so it can reset focus. This issue only manifests when the body is focusable.

**Comment by brgrz** [comment]
> but this is really a perfect storm of an issue

wow :) indeed

awesome work on finding the root cause of this 👍🏻

**Comment by geoffrich** [comment]
This was fixed in the Shoelace repo with https://github.com/shoelace-style/shoelace/commit/1c8a3ea7d245c5520567b09e48a6e50ff3315a7e so there isn't anything for SK to do here. I recommend closing when a maintainer gets around to this.

**Comment by brgrz** [comment]
@geoffrich The tabindex issue was reported to Chromium as [bug ](https://bugs.chromium.org/p/chromium/issues/detail?id=1263444) by @claviska but I'd still like more insight into why SvelteKit sets tabindex=-1 to body.

Not much is discussed in source and it is the only line of code in SK source that sets tabindex
https://github.com/sveltejs/kit/blob/9de809405f13a24268da167d3c50ad894ecd14a8/packages/kit/src/runtime/client/router.js

**Comment by geoffrich** [comment]
See my comment on another issue for why it's needed: https://github.com/sveltejs/kit/issues/3381#issuecomment-1014796558

If you remove the tabindex, SvelteKit won't be able to reset focus on navigation, which could impact keyboard-only and screen reader users.

However, I think we can improve this so that tabindex is only set when focus is being moved, and otherwise is not set: https://github.com/sveltejs/kit/issues/3501#issuecomment-1022380932

**Comment by geoffrich** [comment]
@brgrz SvelteKit now removes the tabindex after focusing the document root.
