### ISSUE TITLE
config.kit.adapter should be an object with an "adapt" method. See https://kit.svelte.dev/docs#adapters

### ISSUE THREAD

**Issue by derolf** [sveltejs/kit#1701]
Package.json:

```
    "@sveltejs/adapter-node": "next",
    "@sveltejs/adapter-static": "next",
    "@sveltejs/kit": "next",
```

svelte.config.js:

```
import staticAdapter from "@sveltejs/adapter-static";

...

kit: { 
  adapter: staticAdapter(),
  ...
}
```

Error:

`config.kit.adapter should be an object with an "adapt" method. See https://kit.svelte.dev/docs#adapters`

**Comment by Conduitry** [comment]
I can't reproduce this. What exact versions of `adapter-static` and `kit` are you using? Are they the latest ones?

**Comment by OliverHGray** [comment]
This happens if you install the adapter with `npm i -D @sveltejs/adapter-static` as the version marked at latest on npm is 1.0.0-next.0 which is 6 months old. If you run `npm i -D @sveltejs/adapter-static@next` instead it will install the most recently published version and work fine :)

**Comment by derolf** [comment]
Problem disappeared after running `npm upgrade @sveltejs/adapter-static`

Thanks!!!
