### ISSUE TITLE
Error running npm init

### ISSUE THREAD

**Issue by keithkelly31** [sveltejs/kit#1702]
I am attempting to run `npm init svelte@next my-app`, but I am getting the following error:

```
npx: installed 5 in 1.991s
internal/modules/cjs/loader.js:1174
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\kkelly\AppData\Roaming\npm-cache\_npx\72016\node_modules\create-svelte\bin.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1174:13)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by Conduitry** [comment]
Please use the provided issue template, which includes information about your Node version. I suspect you're using one that's too old and lacks the proper ESM support.

**Comment by keithkelly31** [comment]
You are correct.  Outdated Node.  Thanks.

**Comment by ianengelbrecht** [comment]
Please add a short little note about this on the homepage and/or the getting started section of the docs, just to save some of us from having to revert here to see the problem...
