### ISSUE TITLE
Cannot install the Cloudflare Worker package.

### ISSUE THREAD

**Issue by DrewRidley** [sveltejs/kit#1710]
**Describe the bug**
Unable to install ```@sveltejs/adapter-cloudflare-workers```. Receive errors with both ``npm`` and ``pnpm``

**Logs**
```
 ERROR  In : No matching version found for @sveltejs/kit@* inside the workspace
This error happened while installing the dependencies of @sveltejs/adapter-cloudflare-workers@0.0.1
Progress: resolved 1, reused 0, downloaded 0, added 0
```

**To Reproduce**
Create new directory, try to run ``npm i @sveltejs/adapter-cloudflare-workers`` and observe the error. Optionally try with ``pnpm``.

**Expected behavior**
The package is expected to install without any errors. The adapter should not have a dependency called ``@sveltejs/kit/@``. There is an extraneous ``@`` which is likely the culprit of the issue.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 1800X Eight-Core Processor
    Memory: 9.38 GB / 15.95 GB
  Binaries:
    Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.22 => 1.0.0-next.22
    @sveltejs/kit: ^1.0.0-next.115 => 1.0.0-next.115
    svelte: ^3.38.2 => 3.38.2

</details>

**Severity**
Severity is low to moderate, as its possible this bug has to do with my local configuration. Sveltekit can still be used and tested locally, but for users wishing to deploy to cloudflare this may present itself as a problem.

**Comment by Conduitry** [comment]
You should be installing `@sveltejs/adapter-cloudflare-workers@next`.
