### ISSUE TITLE
Recommended way to highlight current page link in navbar

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#1716]
From what I can tell, this is currently the ideal way to highlight the current page in a navbar:
```svelte
<a href="/" class:active={$page.path === '/'}>Home</a>
```

To me, this wasn't obvious, so I think it would be helpful to add an example to the documentation

**Comment by benmccann** [comment]
Seems straightforward enough to me. But if there's still a desire to document, the place to add examples would be https://sveltesociety.dev/recipes. I'll close this here since that site has its own repo
