### ISSUE TITLE
docs install command doesn't work

### ISSUE THREAD

**Issue by winstonDeGreef** [sveltejs/kit#1720]
**Describe the bug**
In the sveltekit docs, it says to use this command to install sveltekit:
`npm init svelte@next my-app`
However when running this command on Ubuntu 20.04.2 LTS, It errors out.
**Logs**
<details>`0 verbose cli [ '/usr/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'init',
0 verbose cli   'svelte@next',
0 verbose cli   'my-app' ]
1 info using npm@7.11.2
2 info using node@v10.19.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/USERNAME/Documents/nodejs/svelte/PROJECTFOLDER/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/USERNAME/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 2ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 3ms
22 timing npm:load:cleanupLog Completed in 3ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 22ms
26 timing config:load:flatten Completed in 3ms
27 http fetch GET 304 https://registry.npmjs.org/create-svelte 427ms (from cache)
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing command:init Completed in 1124ms
32 verbose stack Error: command failed
32 verbose stack     at ChildProcess.proc.on (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
32 verbose stack     at ChildProcess.emit (events.js:198:13)
32 verbose stack     at maybeClose (internal/child_process.js:982:16)
32 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
33 verbose cwd /home/USERNAME/Documents/nodejs/svelte/bukidipalabra
34 verbose Linux 5.8.0-55-generic
35 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "init" "svelte@next" "my-app"
36 verbose node v10.19.0
37 verbose npm  v7.11.2
38 error code 1
39 error path /home/USERNAME/Documents/nodejs/svelte/PROJECTNAME
40 error command failed
41 error command sh -c create-svelte "my-app"
42 verbose exit 1
`</details>
**To Reproduce**

Run this command mentioned in the docs: `npm init svelte@next my-app`

**Expected behavior**
Create files and folders.
**Stacktraces**
<details>
<summary>Stack trace of syntax error</summary>
/home/USERNAME/.npm/_npx/bbf9a9d70dc325b0/node_modules/create-svelte/bin.js:2
import fs from 'fs';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
</details>

**Information about your SvelteKit Installation:**
<details>
`
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
    Memory: 2.23 GB / 11.60 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 7.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 59.0.1
`
</details>

**Severity**
This is blocking my use of sveltekit entirely.

**Comment by ignatiusmb** [comment]
You'll need to update your Node to the latest version, v10 is EOL.

**Comment by winstonDeGreef** [comment]
worked, thanks

**Comment by babakfp** [comment]
> You'll need to update your Node to the latest version, v10 is EOL.

Why don't just check the node version before installation? So the program can tell you that you're using an old version and to order to use the Sveltekit, you need to install the newest version. it shows 2 options (yes update) (no cancel). if you click on the update, it's going to download and open the file for installation.
Or check the version after `yarn dev`. Sveltekit checks the version and the same above stuff. if the version was ok, it runs the app.

**Comment by dummdidumm** [comment]
That doesn't work because the setup fails before it runs, because it uses syntax node 10 doesn't understand

**Comment by babakfp** [comment]
Write a Nodejs program that works for all possible versions.
if the version was above, it will run a command to install the Sveltekit.
if the version was under, same as was I explained in the previous comment.

I checked the docs, there wasn't anything about the Nodejs version.

@dummdidumm
