### ISSUE TITLE
Server-side redirects doesn't work with the Fetch API

### ISSUE THREAD

**Issue by higoka** [sveltejs/kit#1721]
**Describe the bug**
I was trying to implement a login system when i noticed that server-side redirects doesn't work when i submit the form using the Fetch API. I then played around and noticed when i submit the form using the regular `<form>` element the redirects work as expected. I dont know if this is the intended behavior or a bug.

**Logs**
There a no logs but when i checked the network tab in the devtools, i see the request to the new location being made but it doesnt redirect, it stays on the same page.

**To Reproduce**
I created a small repo which can be found here: https://github.com/higoka/sveltekit-server-side-redirect
And a live version here: https://sveltekit-server-side-redirect.vercel.app

**Expected behavior**
The server-side redirects should work the same as a `<form>` element when submitting using the Fetch API.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 7.08 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh

  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    npm: 7.13.0 - /usr/local/bin/npm

  Browsers:
    Chrome: 91.0.4472.106
    Safari: 14.1.1

  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.22 => 1.0.0-next.22 
    @sveltejs/kit: next => 1.0.0-next.115 
    svelte: ^3.34.0 => 3.38.2
</details>

**Severity**
High

**Comment by Conduitry** [comment]
When you make a fetch (or an XmlHttpRequest) from the browser and the response is a redirect, the browser will attempt to fetch/request the target of that redirect, not navigate to the URL the endpoint is redirecting to. This is how browsers work. If you want to redirect from javascript, you'll need to do it manually.
