### ISSUE TITLE
Allow to change query parameters of current route on history

### ISSUE THREAD

**Issue by derolf** [sveltejs/kit#1728]
I am trying to encode some state (current search query) inside the query parameter with

```
    if (isClient) {
      history.replaceState(null, "", location.origin + "?q=" + query);
    }
```

and then I navigate to another page with `goto`.

However, navigating back doesn't properly work.

What's the proper approach to manipulate the current route's query in the history?

**Comment by benmccann** [comment]
When you say "navigating back doesn't properly work" - what do expect to have happen and what actually happens?

**Comment by ignatiusmb** [comment]
I also have the same questions, is this a bug that using `history` conflicts with kit's router, or requesting a feature for kit to support changing query params programmatically? Please also give a repro in a repo if possible.

In that case, does using `.pushState`, by any chance, works for your particular use case?

**Comment by derolf** [comment]
After debugging, I found the reason:

Since I passed `null` in `history.replaceState(null, "", location.origin + "?q=" + query);`,

`event.state` in

```TypeScript
		addEventListener('popstate', (event) => {
			if (event.state && this.enabled) {
				const url = new URL(location.href);
				this._navigate(url, event.state['sveltekit:scroll'], []);
			}
		});
```

is `null` and hence the hook isn't triggered.

So, I guess it would be the best if kit would offer a "safe" function to manipulate the URL.

**Comment by ignatiusmb** [comment]
Then you're looking for #969

**Comment by benmccann** [comment]
Closing as duplicate
