### ISSUE TITLE
Vite proxy urls not working in development with SSR=true

### ISSUE THREAD

**Issue by andreasnuesslein** [sveltejs/kit#1729]
- I have a django server running on port 8000 which is providing the api.
- in my `svelte.config.js` i have:
```js
vite: {
      server: {
        host: "0.0.0.0",
        proxy: {
          "/api": "http://localhost:8000",
          ...
```
which works nicely as long as I have 
```
<script lang="ts" context="module">
  export const ssr = false;
```
in my Pages.

However when I enable ssr, the ssr seems to ignore the proxy-logic and returns, for example:
```
500
Could not load /api/v2/pages/find/?html_path=/
```

I created a repo to illustrate the problem:

https://github.com/andreasnuesslein/svelte-ssr-issue

**Expected behavior**

I would like svelte also in SSR mode to honor the vite-proxy logic

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

-   System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 4.64 GB / 30.66 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.1 - /usr/bin/node
    npm: 6.14.13 - /usr/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Chromium: 88.0.4324.96
    Firefox: 89.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.115 
    svelte: ^3.34.0 => 3.38.2 

- Firefox, Chrome
</details>

**Severity**
annoying

**Thanks**
I thank you for this very slick piece of software :)  I really really enjoy svelte a lot.

**Comment by benmccann** [comment]
We're running SvelteKit in middleware mode. Not in server mode. So a lot of the `server` options probably aren't available. I'm not sure if this is something that could be added or if we just need to document the limitation

**Comment by j9108c** [comment]
i can't even get the `vite.server.proxy` to work when ssr is false.

<br/>

> We're running SvelteKit in middleware mode. Not in server mode. So a lot of the server options probably aren't available. I'm not sure if this is something that could be added or if we just need to document the limitation

so is there a workaround for this? how can we do something like [this](https://create-react-app.dev/docs/proxying-api-requests-in-development) for react CRA, but for sveltekit?

**Comment by quentincaffeino** [comment]
Also interested in this as most FE developers won't run their local instance of backend (what if there are many services). Setting up staging api hosted somewhere and pointing local FE to it is a norm

**Comment by benmccann** [comment]
We're no longer running Vite in middleware mode, so I'd expect this to work now though a user reported on Discord that it still doesn't, so we may need to test

**Comment by andreasnuesslein** [comment]
@benmccann  it works! :partying_face:   I ended up changing my setup, so I can't speak of any live situation anymore but I did update and retry my example repo (https://github.com/andreasnuesslein/svelte-ssr-issue) and you're right: it's solved so far.

Thanks again :)
