### ISSUE TITLE
svelte-kit package retain original casing in file names

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#1734]
**Is your feature request related to a problem? Please describe.**

`svelte-kit package` should not change case of copied files. In my case, I'm getting `readme.md -> package/README.md`.

**Describe the solution you'd like**

Project files should be treated as faithfully as possible.

**How important is this feature to you?**

Nice to have, not essential.

**Comment by dummdidumm** [comment]
Looking at the source code `README` is specifically handled and written all uppercase, so this should be the only file where this happens.

**Comment by ignatiusmb** [comment]
It seems there's other stuff that `svelte-kit package` isn't preserving as well. We could perhaps repurpose this to also track them, or I could open up a new issue for it as well. Here's some that I've found so far, I'll put it here for tracking purposes

1. only certain keys from `package.json` are copied and the rest are discarded
2. essential files from root folder (not in lib) such as `.npmignore`, `LICENSE`, `CHANGELOG.md`, etc. are not copied
3. package exports map starts with `./`, but subsequent separators will be changed to `\\` on windows
4. package exports map specifies path only, not `{ "import": ..., "require": ..., "browser": ... }`, this breaks vite for nested modules

There's probably other stuff that I missed, but it generally goes back to the `package.json`. Perhaps, we could copy the whole package file and only add or overwrite stuff that are missing, that way we can also preserve the `package.json` key ordering, which I know some would appreciate (there's even a prettier plugin for it).

**Comment by janosh** [comment]
@ignatiusmb The docs make it sound like 1. is intentional (though don't explain why):

https://github.com/sveltejs/kit/blob/d96c3c29a65f4ccae3225c125c69c533501d93b7/documentation/docs/12-packaging.md#L14

**Comment by ignatiusmb** [comment]
Yes, it was intentional from #1499, can't really say about it. I've just had the thought that other libraries will most likely use some keys specified in package that will be discarded. It's common as every library will certainly have a `package.json`, hence why I bring this up.
