### ISSUE TITLE
Web component support

### ISSUE THREAD

**Issue by sawden** [sveltejs/kit#1736]
**Describe the bug**
I would like to develop web components with Svelte. For this I have set "compilerOptions" to true.
svelte.config.js
```
...
const config = {
	...,
	compilerOptions: {
		// enable web component mode
		customElement: true
	}
};
...
```
After my changes the App is broken and nothing works anymore.

**Logs**
```
Uncaught TypeError: Cannot read property 'page' of undefined
Uncaught (in promise) TypeError: Illegal constructor
```

**To Reproduce**
1. Create n new SvelteKit Projekt and enable "customElement" mode.
2. Add `<svelte:options tag="component-NAME_HERE"/>` to all components.
3. Start the dev server.
4. The App is broken and the console is full of errors.

**Comment by dummdidumm** [comment]
Related #4502

**Comment by tncrazvan** [comment]
Any news on this?

**Comment by dummdidumm** [comment]
Closing in favor of #4502
