### ISSUE TITLE
Props derived from query parameters in static build are not updated on the client

### ISSUE THREAD

**Issue by derolf** [sveltejs/kit#1737]
I am having a page with a load function that extracts query parameter `q` into prop `q`:

```HTML
<script lang="ts" context="module">
  import type { LoadInput, LoadOutput } from "@sveltejs/kit";

  export async function load({ page, fetch }: LoadInput): Promise<LoadOutput> {
    const q = page.query.get("q") ?? "";

    return { props: { q } };
  }
</script>
```

This works fine with `adapter-node`, but breaks with `adapter-static` because `load` is statically evaluated on build and `props` are carved in stone in `index.html`:

```TypeScript
	hydrate: {
...
	          page: {
...		          query: new URLSearchParams(""),
		          params: {}
...
	          }
        }
```

How can I "update" the page-props on the client when running with `adapter-static`?

**Comment by ignatiusmb** [comment]
Duplicate of #669 and #1218

**Comment by derolf** [comment]
Ah, thanks, probably worth to note in the docs then...

**Comment by derolf** [comment]
Fix for me:
```TypeScript
  export async function load({ page, fetch }: LoadInput): Promise<LoadOutput> {
    const query = browser ? new URLSearchParams(location.search) : page.query;

    const q = query.get("q") ?? "";

    return { props: { q } };
  }
```

**Comment by johnnysprinkles** [comment]
If you're using adapter-static, and your query is dynamic, it makes no sense to look at it from the server-side, so you could simply change "load" to "onMount" and simplify that expression to just always do `location.search`.

**Comment by johnnysprinkles** [comment]
I've argued that we should have the page store work even in such cases, but I guess I wasn't convincing. Feel free to patch in my change here if you want to always be able to use the page store instead of directly inspecting `location.search`.

https://github.com/johnnysprinkles/kit/commit/963f0471184c245799744de7befa4ac85e82c56d
