### ISSUE TITLE
How to navigate between pages in Sveltkit programmatically like /home /contactus if any condition is true in home want to navigate to contact page , Any example will help

### ISSUE THREAD

**Issue by ajayyy123** [sveltejs/kit#1744]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by dummdidumm** [comment]
GitHub issues are reserved for feature request or bug reports. This does read like a usage question (which requires more details, btw), therefore I'm going to close this.
