### ISSUE TITLE
@sveltejs/kit 1.0.0-next.116 breaks CSS imports from node_modules

### ISSUE THREAD

**Issue by leroytromp** [sveltejs/kit#1748]
**Describe the bug**
After upgrading to @sveltejs/kit 1.0.0-next.116, CSS imports from node_modules no longer work as before. The styles are loaded, but any fonts, icons, etc. that are referenced in the imported CSS file, silently fail to load. Downgrading to @sveltejs/kit 1.0.0-next.115 solves the issue.

**Logs**
No errors are are shown in the browser console or server logs around the time this bug occurred.

**To Reproduce**
Tested with the latest versions of Svelte and SvelteKit. Here is a small repo that illustrates the problem:

[https://github.com/leroytromp/sveltekit-css-import-issue](https://github.com/leroytromp/sveltekit-css-import-issue)

**Expected behavior**
Working CSS imports from node_modules, as in @sveltejs/kit 1.0.0-next.115 and lower.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 2.30 GB / 7.84 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE      
    npm: 7.17.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.54)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.116
    svelte: ^3.34.0 => 3.38.3
</details>

**Severity**
This bug is in the annoying category. I suppose a workaround would be to copy the packages from node_modules to the static folder, and include the css files in the `<head>` of app.html. This manual copying approach does make a project harder to maintain, especially when importing a lot of CSS from node_modules. 

**Additional context**
This used to work in @sveltejs/kit 1.0.0-next.115 (and lower).

**Comment by benmccann** [comment]
Can users manually specify a Vite version? That would allow for testing whether that's the issue

**Comment by leroytromp** [comment]
@Conduitry , that was my suspicion as well, because vite 2.3.8 had a few CSS related bug fixes in it.

@benmccann It is definitely a vite 2.3.8 issue, as I have managed to reproduce it using only vite. Here is the repo:

[https://github.com/leroytromp/vite-css-import-issue](https://github.com/leroytromp/vite-css-import-issue)

Because of this, I have also opened an issue on the Vite Github: vitejs/vite#3945

**Comment by benmccann** [comment]
Thanks for the investigation! I'm going to go ahead and close this one since there's not much we can do about it on our side
