### ISSUE TITLE
Provide the "register" object returned by navigator.serviceWorker.register

### ISSUE THREAD

**Issue by Myrmod** [sveltejs/kit#1749]
**Is your feature request related to a problem? Please describe.**
I am currently trying to implement push notifications within my SvelteKit application.

Usually I would go with something like this:

```js
const registration = await navigator.serviceWorker.register('/service-worker.js')
if (!import.meta.env.VITE_VAPID_PUBLIC_KEY) {
      console.error('VITE_VAPID_PUBLIC_KEY is not defined.')

      return
}

// create subscribtion
const subscription = registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: `${import.meta.env.VITE_VAPID_PUBLIC_KEY}`,
})

// send push notification
await fetch('/subscribe', {
      method: 'POST',
      body: JSON.stringify(subscription),
      headers: {
        'content-type': 'application/json',
      },
})
```

**Describe the solution you'd like**
Currently we have `$service-worker` available. So I would suggest adding the `registration` to this object. Not sure if this is possible though.

**Describe alternatives you've considered**
I couldn't find a way to do add push notifications so far. So this is the only way I would suggest.

**How important is this feature to you?**
Some applications need a push notification. So if I cannot add one, the application is useless.

Best regards

**Comment by ignatiusmb** [comment]
The `$service-worker` module is only available inside a service worker file, would this be used outside of that too?

**Comment by benmccann** [comment]
@ignatiusmb the registration of a service worker is separate and doesn't rely directly on the `$service-worker` JS. It happens here:

https://github.com/sveltejs/kit/blob/a5c058a932bf9dbf2e67d0f07f0bc2d2ab2ca28f/packages/kit/src/runtime/server/page/render.js#L147

@Myrmod would https://github.com/sveltejs/kit/pull/2281 be enough to consider this issue solved? It lets you disable the registration. I'd hope that you could then register it on your own which would let you access the return value

**Comment by ignatiusmb** [comment]
Yes, so I think the proposed solution for having the `registration` in `$service-worker` wouldn't really work here.

**Comment by benmccann** [comment]
https://github.com/sveltejs/kit/pull/2988 has been merged which adds an option to disable the existing service worker registration, so I think you could now add your own to address this and I'll go ahead and close this. Let me know if there's something that would still be required

**Comment by alanxp** [comment]
is it possible to get the ServiceWorkerRegistration without manually registering our own file, since all i need is registration to get to pushmanager and work with push notifications

**Comment by milo-ft** [comment]
You can get it from await navigator.serviceWorker.ready;
