### ISSUE TITLE
Add something like getserversideprops in nextjs to sveltekit

### ISSUE THREAD

**Issue by VanshCodes** [sveltejs/kit#1750]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: I'm always frustrated when [...]

**Describe the solution you'd like**
A way to sending props to a component from the backend before rendering

**Describe alternatives you've considered**

**How important is this feature to you?**
Note: the more honest and specific you are here the more we will take you seriously.
Very Important for API's
**Additional context**

**Comment by Conduitry** [comment]
There's a previous discussion about `getServerSideProps` in #758.
