### ISSUE TITLE
SSR serialization of fetch() responses is triggered only if their body is read

### ISSUE THREAD

**Issue by io-levant** [sveltejs/kit#1761]
When SvelteKit-provided `fetch` runs on the server, the response is serialized inside `<script type="svelte-data" ...` tags only if `await response.text()` or `await response.json()` are invoked on the response object. Responses whose body is not read (e.g. responses with no content, errors, ...) won't be serialized and a duplicated network request will be triggered by the client.

Related code [here](https://github.com/sveltejs/kit/blob/f4c84408e6709e2d8780d6abb6805c71328c31f3/packages/kit/src/runtime/server/page/load_node.js#L189).

Related documentation [here](https://kit.svelte.dev/docs#loading-input-fetch) (not mentioning this behavior).

**Comment by benmccann** [comment]
Yeah, I'm not sure if there's any other way of implementing this. I know there was another issue about this somewhere in the tracker, but don't have time to look for it at the moment

**Comment by Conduitry** [comment]
#842 is the previous issue for this. Closing this one.
