### ISSUE TITLE
Page imported in another page as component does not accept props 

### ISSUE THREAD

**Issue by TheRealThor** [sveltejs/kit#1762]
Hello guys,
I created a page named index.html that features default props and  looks like this

_/src/routes/index.svelte_
```
<script>
	import SEO from '$lib/SEO/index.svelte';
	export let title = 'about us';
</script>

<SEO title={title} />
```

I created another page named index_german.svelte that imported index.svelte as component and passed a different title into the component 

_/src/routes/index_german.svelte_
```
<script>
       import SITE from '/src/routes/index.svelte'
       let newtitle = 'Über uns';
 </script>

<SITE title={newtitle}/>

```

Though the index_german.svelte page was rendered as the index.svelte, the title props variable was not "Über uns" as expected but stayed as the default value. 

I would assume that this is a bug, but maybe because the index.svelte is also used as a page object it maybe was somehow altered in behaviour?

<details>
  <summary>Diagnostics</summary>

SvelteKit Version: 1.0.0-next.117 
 System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 224.19 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
</details>

**Comment by Wolfr** [comment]
I don't think this is supported behavior. You would import components into a page (route), not another route.
