### ISSUE TITLE
Dynamic layout selection

### ISSUE THREAD

**Issue by unix-max** [sveltejs/kit#1766]
**Is your feature request related to a problem? Please describe.**
Now we have the option to either use the default layout _**"__layout.svelte"**_. Or use an alternative layout _**"__layout.reset.svelte."**_. But these are only 2 possible options. In my project, there is a need to implement several dozen themes, each of which significantly changes the appearance of the site.
   Now this can be solved by following the component for each theme and load them dynamically or via in-if. 
**_/lib/RedTheme.svelte';_**
```
<style>
:global(h1) {
color: red;
}
</style>

<slot></slot>
```
**_/lib/GreenTheme.svelte';_**
```
<style>
:global(h1) {
color: green;
}
</style>

<slot></slot>
```
**_/routes/__layout.svelte_**
```
<script>
import RedTheme from './RedTheme.svelte';
import GreenTheme from './GreenTheme.svelte';
let themeId = 1;
</script>
{#if themeId = 1}
   <RedTheme>
      <slot></slot>
   </RedTheme>
{:else themeId = 2}
   <GreenTheme>
      <slot></slot>
   </GreenTheme>
{:else}
	<slot></slot>
{/if}
```
It looks like an awkward crutch rather than a working tool

**Describe the solution you'd like**
Make the layout dynamically defined in the **_script context="module"_** just like other variables.
**_/routes/index.svelte_**
```
<script context="module">
     export const ssr = true;
     export const layaut = () => {
       switch (page.params.theme) {
          case red: return "RedThemeLayaot.svelte";
          break;
          case green: return "GreenThemeLayout.svelte
          break;
       }
    }
</script>
```
If the variable is not defined then the default layout **_"__layout.svelte"_** is used.

**How important is this feature to you?**
This is important to me and I am ready to start implementing this, but I will need help and documentation on the device of the router and the choice of a layout for it.

**Comment by moritzebeling** [comment]
I also often have the same situation, that I have several templates. I solve it like:
```js
<script>
    import Default from '$lib/Templates/Default';
    import Red from '$lib/Templates/Red.svelte';
    import Green from '$lib/Templates/Green.svelte';
    let templates = {
        default: Default,
        red: Red,
        green: Green
    };
    export let layout = 'default';
    export let data; // some page data
</script>

{#if templates.hasOwnProperty(layout)}
    <svelte:component this={templates[layout]} {data} />
{:else}
    <Default {data} />
{/if}
```

**Comment by fnicastri** [comment]
Any news about this?

**Comment by mrkishi** [comment]
This is now possible with [named layouts](https://kit.svelte.dev/docs/layouts#named-layouts):

```sh
/src/routes/
  /__layout-red.svelte
  /__layout-green.svelte
  /foo@red.svelte
  /bar@green.svelte
```
