### ISSUE TITLE
Not compatible with AMP syntax

### ISSUE THREAD

**Issue by cheluskin** [sveltejs/kit#1769]
example amp code 
`<input
	  autocomplete="off"
	  id="searchinput"
	  on="input-debounced:AMP.setState({query: event.value})"
	  inputmode="search"
	  placeholder="Search…"
	  type="search"
	/>`
Compiler will not skip curly braces and return ParseError

**Comment by Conduitry** [comment]
You need to escape the braces so they're not interpreted as Svelte template expressions.

**Comment by cheluskin** [comment]
Thank you. It may be worth declaring partial AMP compatibility if the code needs to be escaped this way.
