### ISSUE TITLE
Provide goto state in load (SSR)

### ISSUE THREAD

**Issue by mohe2015** [sveltejs/kit#1770]
**Is your feature request related to a problem? Please describe.**
You can provide `state` to the `goto` function but as far as I know this is not available for SSR. So when e.g. accessing it in the load function using `history.state` this only works with a client-side router.

**Describe the solution you'd like**
I think the `page` store could have a `state` object.

**Describe alternatives you've considered**
I'm not aware of any but would love to hear of them.

**How important is this feature to you?**
If there is no workaround (I don't know of one) I just need to hope that the client-side router has always loaded so my application works :)

**Comment by Rich-Harris** [comment]
`goto` is a client-side only function. There's no such thing as `history` in SSR, and therefore no `history.state`
