### ISSUE TITLE
HMR doesn't work when running multiple SvelteKit apps

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#1774]
**Describe the bug**
When running two SvelteKit apps in dev mode, only one of them will have functioning HMR. The problem is caused by the fact that both apps are trying to use the same port `24678` for HMR.

When using Vite directly, it is possible to override the port. SvelteKit doesn't allow it, providing the following explanation:

> The value for kit.vite.server.hmr specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.

**Expected behavior**
1. Multiple SvelteKit apps should work simultaneously and without interference
2. `vite.server.hmr` options should be configurable

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 236.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: 1.0.0-next.118 => 1.0.0-next.118 
    svelte: 3.38.3 => 3.38.3 
```
</details>

**Comment by Conduitry** [comment]
`vite: { server: { hmr: { port: some_port_number } } }` in `svelte.config.js` does work, but not, it looks like, when using `--https`, which I assume you are.

The code in question is: https://github.com/sveltejs/kit/blob/1b134165e6b6aa73f93a8c513adf79f4593aaef2/packages/kit/src/core/dev/index.js#L121

I don't think there's a reasonable way to get the browser to automatically accept the certificate if the websocket connection is on a different port (and therefore a different origin) than the main server. However, there shouldn't be a collision with the HMR ports across different `--https` apps unless there is also a collision with the apps themselves.

Do you have more details about your reproduction? Are you seeing something else?

**Comment by ebeloded** [comment]
I don't use https flag. 

My setup is pretty simple and reproduction is straightforward: start two SvelteKit apps. Both of them will try to use the same port for HMR (`24678`), which will result in only one app's HMR working.

In fact, the reproduction can be simplified further: you only need one app, but start it on different ports. Only one of the apps will get HMR (or none - in case you already have a SvelteKit app running).

**Comment by Conduitry** [comment]
I meant a reproduction for getting that error about overriding the Vite setting. When I do that, the setting is respected.

**Comment by ebeloded** [comment]
You are right, the HMR port can be set without issues. I must have been trying to set `vite.server.hmr`, not `vite.server.hmr.port`. 
I am sorry to waste your attention.

**Comment by ebeloded** [comment]
That being said - it would be better if we could run multiple SvelteKit apps with HMR without extra configuration.
