### ISSUE TITLE
Ignore node_modules when walking files configured in kit.files.{routes,etc}

### ISSUE THREAD

**Issue by xrd** [sveltejs/kit#1781]
## Description

If you use `{ kit: { files: { routes: '.' } } }` inside your `svelte.config.js`, kit processes files inside your node_modules directory. This means you cannot have your routes be inside the root directory.

For example, you will see this error if anything in the node_modules directory has a double underscore:

```
$ yarn dev
yarn run v1.22.10
warning package.json: No license field
$ svelte-kit dev
> Files and directories prefixed with __ are reserved (saw node_modules/postcss-selector-parser/dist/__tests__)
```

## envinfo

$ npx envinfo --system --npmPackages svelte,@sveltejs/kit,@sveltejs/adapter-node,@sveltejs/adapter-static,@sveltejs/adapter-begin,@sveltejs/adapter-netlify,@sveltejs/adapter-vercel vite --binaries --browsers
npx: installed 1 in 1.132s

  System:
    OS: Linux 5.11 Pop!_OS 20.10
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 11.39 GB / 62.66 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: next => 1.0.0-next.119 
    svelte: ^3.34.0 => 3.38.3 

## Browser

Firefox

## Severity

This does prevent me from using SvelteKit with my current repository where I want things all at the root.

**Comment by Conduitry** [comment]
I don't know why `node_modules` would be the only thing we'd want to exclude - but more importantly, I don't think this is something we want to support or enable people to do. If you're pointing `routes` at a directory, everything in that directory should be routes (unless it's already being excluded by the `_` rules explicitly specified in the docs).

**Comment by xrd** [comment]
@Conduitry Thanks for the response. Is there a workaround to ignore files? I can't figure out a way to use svelte kit with a "flat" file structure. for example, I want to make a blog using svelte kit that has this structure:

```
posts
pages
package.json
svelte.config.js
```

The problem is that npm/yarn install into node_modules and those files can have **any** filename format, and I don't have control over their names.

Would you consider adding something like `.kitignore` that you can use to ignore files specified in there?

**Comment by xrd** [comment]
Maybe I can just use `.yarnrc` for yarn, for example, and customize the node_modules directory. That is the only problem I face currently, I'll give that a go.

**Comment by xrd** [comment]
I'm really sad that this link is dead: `npm FAQ: "node_modules" is the name of my deity's arch-rival, and a Forbidden Word in my religion. Can I configure npm to use a different folder? ;-)`

**Comment by xrd** [comment]
@Conduitry: Would you consider an environment variable which is ignored if unset, like this:

```
.filter(f => {
                 return process.env.SVELTE_KIT_FILES_IGNORE_PREFIX ?
                     !process.env.SVELTE_KIT_FILES_IGNORE_PREFIX
                     .split(",")
                     .find(g => f.startsWith(g)) : true }));
```

For example, here is a script which demonstrates this:

```
const stuff = [
    "node_modules/FILTERME",
    "abc/node_modules/YESWANT",
    "random_prefix/FILTERME",
    "YESWANT",
    "YESWANT"
];

console.log( (process.env.SVELTE_KIT_FILES_IGNORE_PREFIX? "IS " :"UN")
             + "FILTERED: ",
            stuff
             .filter(f => {
                 return process.env.SVELTE_KIT_FILES_IGNORE_PREFIX ?
                     !process.env.SVELTE_KIT_FILES_IGNORE_PREFIX
                     .split(",")
                     .find(g => f.startsWith(g)) : true }));

```

It runs like this:

```
$ node test.js
UNFILTERED:  [
  'node_modules/FILTERME',
  'abc/node_modules/YESWANT',
  'random_prefix/FILTERME',
  'YESWANT',
  'YESWANT'
]
$ SVELTE_KIT_FILES_IGNORE_PREFIX=random_prefix,node_modules node test.js
IS FILTERED:  [ 'abc/node_modules/YESWANT', 'YESWANT', 'YESWANT' ]
```

**Comment by xrd** [comment]
@Conduitry Unfortunately, it does not look like there is a well supported way to install node_modules into another path, and this means I am unable to workaround this if I want my routes to be at the root of a JS project.

**Comment by benmccann** [comment]
Is there a compelling reason why you can't just make a `routes` directory and shove everything in there? Each configuration option we add is another thing we have to test, explain to users, etc. That's fine if there's a reason for it, but it's not clear to me that adding such an option would let you do anything you can't do today that has any practical difference

**Comment by Rich-Harris** [comment]
Echoing the previous comments — this doesn't feel like something we'd want to support. Unless there's a really strong reason for putting routes in the project root, we'll have to close this issue.

**Comment by xrd** [comment]
Just to restate what I noted in previous comments, I want to use kit to build a blog that mimics the structure of a jekyll blog, where there are directories like `_posts` at the root, directories that contain Markdown files as the blog posts (https://jekyllrb.com/docs/posts/). I don't see a way to configure kit if it automatically processes all directories in `.` and if node_modules includes filenames that are out of my control that kit does not like.

Would you consider a config file change like the follwoing? If not, I'll happily close this issue and live without this change. I appreciate the work on svelte and kit so far and will assume there are more pressing concerns. If so, I can work up another PR for that change.

```
const config = {
	kit: {
		files: {
			lib: 'lib',
			routes: '.',
                        ignoreRoutes: /$node_modules/,
                        ignore: '~'
		},
         }
}
```

What this would do:

1. Ignore anything in the routes directory that starts with node_modules (matching the regexp)
2. Ignore all files that have a tilde in the name (if the user happens to use emacs and temp files are created).

**Comment by benmccann** [comment]
I don't see why you have to mimic the structure of a jekyll blog
