### ISSUE TITLE
#svelte-announcer css included when building with router: false

### ISSUE THREAD

**Issue by JasonWoof** [sveltejs/kit#1794]
Thanks for Svelte and sveltekit! Seems very cool so far.

**Describe the bug**

sveltekit-build (with adapter-static and settings: prerender: true, hydrate: false, router: false) is slowing down my page load with this useless css:

`<link rel="stylesheet" href="/./_app/assets/start-a8cd1609.css">` with the contents: `#svelte-announcer.svelte-1j55zn5{position:absolute;left:0;top:0;clip:rect(0 0 0 0);clip-path:inset(50%);overflow:hidden;white-space:nowrap;width:1px;height:1px}`

**To Reproduce**

I started with the standard sveltekit example and added adapter-static.

I'm rendering to html at build time with svelte-kit build, prerender: true, hydrate: false, router: false

Everything works, I get no error messages or anything, I just don't want this extra http request.

**Severity**

minor

**Comment by acoyfellow** [comment]
My guess is that we'd want to do a check it `router` is set to true here:
https://github.com/sveltejs/kit/blob/52c0f99e57b993e9749e05a7c4567c4c9e25ad34/packages/kit/src/core/create_app/index.js#L179

And we need to update the test to accomodate:
https://github.com/sveltejs/kit/blob/ff35e8d50a344835480a0b79ad6b4fcfb2ebcace/packages/kit/test/apps/basics/src/routes/no-ssr/_tests.js

Can anyone who is more familiar with the internals of kit confirm or deny?

**Comment by mcmxcdev** [comment]
It seems that the CSS of `svelte-announcer` changed from being an additional request to inline `style` prop in the meantime:
https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/write_root.js#L78-L84

Is this an acceptable compromise for you to be able to close this issue @JasonWoof?

**Comment by Rich-Harris** [comment]
Closing now that the styles are inline
