### ISSUE TITLE
Alternative to using Vite for dev server?

### ISSUE THREAD

**Issue by davidcallanan** [sveltejs/kit#1795]
**Is your feature request related to a problem? Please describe.**
Yes. Whenever I run a dev server, Vite is used under the hood. Unfortunately, Vite actually runs not only a HTTP server on port 3000, but also a web socket server on port 24768 or something (I can't remember exactly). This is problematic in many situations.

Anyone using `ngrok` or `localtunnel` will be unable to use svelte-kit altogether since these services can only work with one port. If you are not aware of these services, they allow you to access your local web server from an SSL domain. They are commonly used to test a website on another device, or, in my case, to use certain APIs that are restricted to SSL domains (and can't be used on localhost), for example Google OAuth apis.

This means I have no way of integrating Google OAuth into my svelte-kit application. My only option is to rewrite my app with something else such as React, but I'd much prefer to keep using svelte-kit since it's the best framework I've ever used.

**Describe the solution you'd like**
There are a few options that could solve the above problem.

- An alternative dev server option that doesn't use Vite under the hood. For example it could be the same as the production server (however with some dev stuff enabled such as source maps), attached to a watcher to re-build and re-run when files change.
- A mechanism for hooking up a custom dev server (I'm not sure how something like this would be implemented).

**Describe alternatives you've considered**

 I was trying to do the following as a temporary hack, however for some reason it isn't working, and even if it does work it would be incredibly slow:

 - `nodemon --exec \"npm run build && npm run preview`

Another alternative could be to open an issue with Vite to add an option to run the websocket server on the same port.

**How important is this feature to you?**
Relatively important. It is only for a personal project, but I would really like to make progress on it.

**Comment by cayter** [comment]
Not sure why the insist to use custom domain for Google OAuth's local testing. I've personally done Google/Facebook/LinkedIn OAuth integrations, they do support localhost testing. For more details, please refer to https://developers.google.com/identity/protocols/oauth2/web-server on how to enable localhost whitelisting.

**Comment by dummdidumm** [comment]
Closing as there are ways as @cayter pointed out. I don't see a future where SvelteKit is decoupled from Vite.

**Comment by davidcallanan** [comment]
@cayter I just found that out myself not long before you left that comment. Thanks anyway. I wish I had tried that from the start instead of assuming I couldn't.

@dummdidumm Ok. There could be other reasons to use an alternative dev server than my specific scenario, but if decoupling from Vite is not feasible then that's fine. At least my own problem is solved :)
