### ISSUE TITLE
explicit config of adapter to null result to error `Cannot read property 'adapt' of null`

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#1816]
**Describe the bug**
Let say I use env variable to decide what adapter to use and as default value I want to use null (which is default value by documentation), when I set explicitly adapter to null in config, it throws error:

**Logs**
```
Cannot read property 'adapt' of null
TypeError: Cannot read property 'adapt' of null
    at Object.validate (file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:181:48)
    at validate (file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:583:28)
    at validate (file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:581:19)
    at validate_config (file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:670:20)
    at load_config (file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:647:20)
    at async get_config (file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:784:10)
    at async file:///mnt/sda1/Programovanie/test/node_modules/@sveltejs/kit/dist/cli.js:869:18
```

**To Reproduce**
Use config:

```js
kit: {
  adapter: null
}
```

**Expected behavior**
No error, and it should work same way as if there would be no adapter setting in config.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 2.91 GB / 15.46 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.30 => 1.0.0-next.30 
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.13 
    @sveltejs/kit: next => 1.0.0-next.119 
    svelte: ^3.34.0 => 3.38.3 

</details>

**Severity**
For me it's really big problem, because I can't use for example:

```js
kit: {
    adapter: process.env.SERVER == "node" ? adapter_node() : null;
}
```

in config. Or for example switch statement where default is null. like

```js
let adapter;

switch (process.env.ADAPT) {
	case "node":
		adapter = adapter_node()
		break;
	case "static":
		adapter = adapter_static()
		break;
	default:
		adapter = null;
}

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter,
        }
}
```

now I need to add it to config like this:

```js
if (adapter) {
	config.kit.adapter = adapter;
}
```

and it's unnecesary 3 lines of code.

**Comment by benmccann** [comment]
> I want to use null (which is default value by documentation)

Can you point to where the documentation says this? I don't see it. I expect the default value is `undefined` and not `null`

**Comment by Mlocik97** [comment]
https://kit.svelte.dev/docs#configuration

btw. undefined doesn't work too.

**Comment by ignatiusmb** [comment]
The default value of `null` in docs or optional `undefined` from the types are there to say that SvelteKit doesn't come pre-configured with an adapter and users need to configure one by themselves.

What are you trying to do in the first place? `config.kit.adapter` should only be used when `svelte-kit build` is called and it doesn't really make sense to build without an adapter in place.

Again, I'm not sure why you want to build without an adapter, but you can mock an empty one just by passing an object with adapt key as callback so it doesn't throw an error

```js
const config = {
  kit: {
    adapter: { adapt: () => {} }
  }
}
```

**Comment by Mlocik97** [comment]
Wait, so then why is null default value? I thought it generates build for testing/dev purpose. And that adapters are just for "adapting" for specific environment where my app will run (like node server, or server-less platform). Am I wrong?

**Comment by benmccann** [comment]
Adapters are for adapting to a specific environment in production only. They are not used in development

**Comment by Mlocik97** [comment]
@benmccann yes, I thought it's like that..

the problem is when I want adapt my app for more than one platform (like node, vercel and Netlify for example) and as default I want to fallback to null,... let say I set env variables specific for each platform, and when I don't get any value (it will be undefined/null), it throws error, even when I would like to let it work, because well I want to test it on my test server for example, that will not use env variable.

Yes, now I can cheat it with `adapter: { adapt: () => {} }` but at least I think, there should not be `null` as default value in documentation, when it's not really default value and default config (copied from documentation) throws error.

Still I think, it should be changed at least in documentation.

**Comment by benmccann** [comment]
> as default I want to fallback to null

but you're always running on some platform, so that's never a valid value. just make sure there's always at least `adapter-node` set. I'm not sure what you want `null` to do, but it sounds like you want it essentially to use `adapter-nodle`

**Comment by pngwn** [comment]
I'm starting a petition to create `adapter-noodle`.

**Comment by Mlocik97** [comment]
isn't null default value used for dev and test purposes? Maybe that's why I want to use it?

**Comment by benmccann** [comment]
As stated above https://github.com/sveltejs/kit/issues/1816#issuecomment-873465579, the adapters are not used in development. They are only used in production
