### ISSUE TITLE
[Issue template] Use form instead template.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#1820]
Like in svelte repo, we should in kit repo use issue forms, it would be much easier to create issues and PRs and it will also reduce of bad formated issues or even spam.

**Comment by johnnysprinkles** [comment]
Sounds like a good improvement. I wish I had more insight into who the core team is and how often they meet, and who the go-to person for such process improvements is.

**Comment by cayter** [comment]
Would suggest to also enable `Discussions` tab so that folks can:

- ask the questions
- get answers from the community
- if the community answer concludes that it's a bug, only then create an issue.

This would help to massively reduce the noise of random questions being asked in the `Issues` tab.

**Comment by jthegedus** [comment]
@cayter using GitHub Discussions has been discussed in a these (https://github.com/sveltejs/svelte/issues/5873 & https://github.com/sveltejs/svelte/issues/5857) Issues in the Svelte org with the maintainers set on Discord & StackOverflow instead.

**Comment by dominikg** [comment]
issue forms are now active, see #1882
