### ISSUE TITLE
serverFetch not getting called for relative urls

### ISSUE THREAD

**Issue by Alisaien** [sveltejs/kit#1823]
**Describe the bug**
The title basically.

**Expected behavior**
serverFetch get called for all server-side fetch calls.

**Severity**
The issue itself is just annoying, the problem is since this not documented (regardless if this behavior intended or not) this problem cost me like a day to find (at first I though the documentation was ahead of the npm package), so this might some people from using Kit at all.

**Fix**
Either call serverFetch for relative urls, or document that absolute urls are required for this to work.

**Comment by benmccann** [comment]
It says in bold "external resource", so I think it's clearly documented

**Comment by stalkerg** [comment]
@Alisaien 
> serverFetch get called for all server-side fetch calls.

it's exactly how it's working now but has nuance:
`serverFetch` working only for real network fetch, in SvelteKit terms it's external fetch, other fetches not actually work as `fetch` it's just routing inside code to your handler. 
It's also clearly documented:
> This function allows you to modify (or replace) a fetch request for an **external** resource that happens inside a load function that runs on the server (or during pre-rendering).

**Comment by Alisaien** [comment]
I think it depends on perspective, I was experimenting with SvelteKit by porting over an SPA which had no SSR. So all urls for fetch/xhr requests and anchors were relative, but the reverse proxy redirected everything beginning with "/api" to the api server.
From a client side/application (as a whole) standpoint this is an internal endpoint, for the router of SvelteKit this would be an external resource. It also is not documented (at least I think) how an server-side fetch call resolves relative urls, e.g. it could use the host header of the original request to build an absolute url (which would not be host-spoofing safe, so bad practice) but this would also trigger additional round trips.
So basically because my standpoint was different from yours and because I blindly copied urls for a quick start, I got stuck with this problem.
Also just because it is an absolute path does not mean it is external, since the host can actually be the SvelteKit router itself (or at least this is how I interpret external).

In my opinion, documenting clearly how server-side fetch calls are handled would also solve this issue and I hope above showed you that writing "absolute urls" in the documentation would be clearer and not perspective dependent.

**Comment by Alisaien** [comment]
I just want to add one more thing:
When I first read
> This function allows you to modify (or replace) a fetch request for an external resource that happens inside a load function that runs on the server (or during pre-rendering).

I interpreted it more like "you **can** (for example) use serverFetch for external resources", rather than "serverFetch is **exclusively** for fetching external resources" (even if it that is what I read from my current standpoint).
So I did not think much about what "external resources" are supposed to be.

Alright, I think I properly explained everything which lead me to misinterpret the usage/purpose of this function, the rest is you decision to make. If you want me to provide my own formulation/proofread yours, feel free to update me.

**Comment by Alisaien** [comment]
@stalkerg This is a question/feature request:
Why doesn't have serverFetch access to the original request (the one passed to handle/getSession) ? Since the use case seems to be hitting api/auth servers directly, what is the point if you can't pass the access token that you received as cookie on to the remote server ?

**Comment by stalkerg** [comment]
@Alisaien we thought about it but it will not a `fetch` anymore... currently it has the same signature as the original `fetch` method. 
Also, you still can put all auth things into the `fetch` in the component. 

> porting over an SPA which had no SSR

I suppose `serverFetch` has no sense without SSR.

**Comment by Alisaien** [comment]
@stalkerg 
> Also, you still can put all auth things into the fetch in the component.

But the problem is, the `load` method in the component has also no direct access to the request (which makes sense). I am currently circumventing this issue by using `getSession` to have access to the cookies/headers in the `load` method, but that is not ideal, since for example 'Cookie' is a forbidden header name, so I have to start worrying about env in `load`, which is kind of contra to its design.

Maybe you can make `serverFetch` a factory, which takes the client request, and then returns a `fetch`-like function, or instead of `options.hooks.serverFetch.call(null, request)` you can replace `null` and pass the client request as `this`. Both approaches would allow you to keep the signature.

>> porting over an SPA which had no SSR
>
> I suppose serverFetch has no sense without SSR.

Maybe you misunderstood me; I want to use SSR (and that reason for porting) but I coming from an app with none.

**Comment by stalkerg** [comment]
>  I am currently circumventing this issue by using getSession to have access to the cookies/headers in the load method,

As I understand it's a very common pattern:
```js
export function getSession(request) {
  return {
    user: request.locals.user,
    env: request.locals.env,
    cookie: request.headers.cookie,
  };
}
```
and you can easily access cookies without any limitations. Looks like you doing something wrong. 

> Maybe you misunderstood me; I want to use SSR (and that reason for porting) but I coming from an app with none.

Ahh I see, sorry.

**Comment by Alisaien** [comment]
Let me quote the doc:
```js
export function getSession(request) {
	return {
		user: {
			// only include properties needed client-side —
			// exclude anything else attached to the user
			// like access tokens etc
			name: request.locals.user?.name,
			email: request.locals.user?.email,
			avatar: request.locals.user?.avatar
		}
	};
}
```

So if I just forward the cookie header (which contains the access-token), wouldn't that be just what I am *not* supposed to do. I mean what's the point of using 'HttpOnly' flag if I return the token to the client-side js on every request.

**Comment by stalkerg** [comment]
Yep, you right and I agree with you, but `serverFetch` can't help here, it's just a different case.

**Comment by Alisaien** [comment]
Sorry I don't understand what you mean with
>and it's should work transparency for SSR case

Currently if SvelteKit resolves a path internally it basically cheats by passing the client credentials on to the fetch request.
```js
if (opts.credentials !== 'omit') {
    uses_credentials = true;

    headers.cookie = request.headers.cookie;
    if (!headers.authorization) {
        headers.authorization = request.headers.authorization;
    }
}
``` 

Also the problem becomes even worse if you multiple api/resource servers and have to decide in each `load` function which credentials should be exposed to which server.
A centralized way to modify requests seems the only right choice, you could change the hook to something like `requestSetup(clientReq: Request, serverReq: Request) => Request` because that's the actual purpose of this function and every `serverFetch` (probably) ends with `return fetch(modifiedRequest)`.
If the returned `request.url` is still relative, you skip HTTP and resolve internally and if not use `node-fetch` and send the request.
This approach seems to be better imo because modifying headers conditionally is also a pitfall.

**Comment by benmccann** [comment]
@Alisaien if you don't want to send credentials you can use the `credentials: omit` option on `fetch`. I've proposed renaming `serverFetch` to `externalFetch` because I think the current name is not clear: https://github.com/sveltejs/kit/issues/2101

**Comment by Alisaien** [comment]
1. I appreciate the renaming.
2. I do want to send credentials, my point was that SvelteKit internally passes the `cookie` and `authorization` headers unless you set `omit`, while with `server/externalFetch` there is no direct way to pass cookie headers from the original request to the external one. Sure you can abuse `session` but I don't like that since there is the risk of exposing credentials to client side code.
Right now I am working around this issue by having an internal `[...api].js`, then call `fetch` for that endpoint (which automatically passes on cookies) and from there hit the actual external endpoint. It works, there is no risk of leaking anything, but imo shouldn't be necessary.
Anyway I have a solution I am fine with, so feel free to close the issue.

**Comment by stalkerg** [comment]
@Alisaien as I understand right - you can't abuse `session` because all these cookies anyway on the client-side in the browser.

**Comment by Alisaien** [comment]
They are on client-side, but (usually) they are `HTTPOnly`. Now if they are part of `session`, any client-side script is able to access them, and I just don't like introducing vulnerabilities knowingly. As I said above, I found a workaround that works for me and you may have different opinion from me on how much this is a risk.

Regardless, currently an internal fetch treats credentials differently from an external one, which either requires some documentation or you could just make both behave the same (this is basically a new issue).

**Comment by stalkerg** [comment]
@Alisaien ok, got it, have sense. I do currently not use HTTPOnly cookies but hell yeah it sounds like an issue. 

@benmccann @Kapsonfire-DE what do you think?

**Comment by Kapsonfire-DE** [comment]
The moment you have injected JSCode on your site, able to reading the cookie you have other problems. It just becomes a problem, if you allow third party JS Code you dont control.
With httponly you only prevent to read the cookie with js, but its still possible to make requests in the name of the user.

**Comment by Alisaien** [comment]
I was thinking more along the lines of middleware or something like Google Analytics recording credentials in some log, which isn't as bad JS injection, but something you still don't want.

Honestly, I think the current discussion has nothing to do with my original issue anymore. I'll just summarize my two main concerns, which I tried to explain in earlier comments:
- Currently internal/external fetch handle credentials differently
- I think something along the lines of `requestSetup(clientReq: Request, serverReq: Request) => Request` which would allow users to modify the request before `fetch` logic is executed server side and make writing `load` functions easier, since you don't have to distinguish between envs.

As long as someone addresses these two thoughts I would be happy to close the issue.

**Comment by ignatiusmb** [comment]
You're right, this discussion is starting to go off on a tangent. Your second point is more of a feature request, which is not in the scope of this issue and is somewhat similar to #1473. Closing as the initial problem should be resolved, now that it's been renamed to `externalFetch`.
