### ISSUE TITLE
Custom hook to handle mime type interpretation

### ISSUE THREAD

**Issue by JeanJPNM** [sveltejs/kit#1829]
**Is your feature request related to a problem? Please describe.**
Possible solution for #1438, better thought of and more maintainable than #1687.

**Describe the solution you'd like**
A custom hook that lets the user determine how the body of a request/response should be parsed based on its mime type.
The hook receives the mime type or the request/response headers as input and returns a value from an enum, telling the framework how to interpret the body.

**Describe alternatives you've considered**
- Two fields in the `svelte.config.js` file (one for buffer and other for text) that contain a list of regexes that are tested against a mime type to determine how the body should be parsed.
- Hardcoded list of mime types for body parsing.

**How important is this feature to you?**
For me is a very important feature since it will enable users to send binary content from endpoints, and let them define specific handling for some mime types such as image/svg+xml.

**Additional context**
This feature requires svelte kit to make hooks accessible to adapters.
This feature was made considering that #1563 may become a part of the framework hence the use of an enum instead of a boolean.
This feature is also intended to replace #1687.

**Comment by JeanJPNM** [comment]
Here is a [quick and working implementation](https://github.com/JeanJPNM/kit/tree/hook-for-mime-type-interpretation)

**Comment by benmccann** [comment]
@JeanJPNM do you think we still need this after https://github.com/sveltejs/kit/pull/1890 and https://github.com/sveltejs/kit/pull/1900?

**Comment by JeanJPNM** [comment]
No I don't this is necessary anymore, since the the body will default to an instance of `Uint8Array` instead of a string it is pretty easy to parse it inside an endpoint.
