### ISSUE TITLE
Adapter build outputs are linted, formatted, and synced to Git

### ISSUE THREAD

**Issue by Nick-Mazuk** [sveltejs/kit#1832]
**Describe the bug**

Build outputs to the adapters are not in the `.eslintignore`, `.prettierignore`, and `.gitignore` by default. This means they are linted, formatted, and checked into version control by default. I suspect this is not desired behavior for most people.

**To Reproduce**

- Create any new Sveltekit project
- Add an adapter (e.g., `adapter-vercel`)
- `pnpm build`
- Running `pnpm lint`, `pnpm format`, or `git add .` will now also include these new build outputs

To fix, you can just add the build output to the relevant ignore files. I think they should be there by default.

I can provide a reproduction repo, stack traces, etc. if needed, but I think the issue is fairly self-explanatory.

**Expected behavior**

By default, these files should not be linted, formatted, or checked into version control.

**Severity**

Honestly, not that severe. It's a ~30 second fix for anyone creating a Svekte/kit project. But the bug fix would also be a ~30 second fix as well.

**Comment by benmccann** [comment]
Each adapter needs to ignore a different set of files. There was a standard set of files originally in the `.gitignore` but they ended up being removed to support the Firebase adapter. There's a ticket discussing it somewhere, but we were leaning towards having each adapter be responsible for adding the files it creates to `.gitignore`

**Comment by Mlocik97** [comment]
What if Adapter would internally generate/modify .gitignore ?

**Comment by benmccann** [comment]
Yes, what I just said in my previous comment was the the adapter could modify `.gitignore`

**Comment by JeanJPNM** [comment]
We could put something like this inside `adapter-utils.js` to let the adapters have a standart way to change `.gitignore`

```js
/** Adds glob patterns to the
 * @param {object} options
 * @param {string[]} options.patterns An array of glob patterns to be inserted into the project's `.gitignore` file
 * @param {boolean} [options.generate] Whether the `.gitignore` file should be created if it doesn't exist
 * @param {string} options.name The name of the adapter
 */
export async function addToGitIgnore({ patterns, generate = false, name }) {
	const path = '.gitignore';
	const { existsSync } = await import('fs');
	const { readFile, writeFile, appendFile } = await import('fs/promises');
	if (!existsSync(path)) {
		if (!generate) return;
		writeFile(path, '');
	}
	const file = await readFile(path, {
		encoding: 'utf-8'
	});
	if (file.includes(`# Generated by ${name}`)) return;
	const text = `\n# Generated by ${name}\n${patterns.join('\n')}`;
	await appendFile(path, text);
}
```
