### ISSUE TITLE
Is it possible to package sveltekit project into an executable

### ISSUE THREAD

**Issue by etclub** [sveltejs/kit#1844]
I developed a sveltekit app, which works as a server in a local area network.

Now I have to  package it into an executable, so that my client can run it easily on any computer in their LAN.

I tried https://www.npmjs.com/package/pkg, and set `.svelte-kit/output/server/app.js` as the entry file.
An executable is generated. But it fails to run, with error:
```
node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module '/snapshot/test-project/.svelte-kit/output/server/app.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1776:46)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I wonder if pkg is the right tool.

**Comment by ignatiusmb** [comment]
You need to use an adapter to build a production version first before packaging them, but I think what you want might be closer to #97

**Comment by dummdidumm** [comment]
Closing as duplicate of #97

**Comment by opensas** [comment]
you should have a look at https://github.com/Hugo-Dz/exe?tab=readme-ov-file

I gave it a try, and so far now it's the only way I could package a sveltekit app as an exe
