### ISSUE TITLE
Apply adapter-node as adapter 'npm run build' fail while 'docker-compose up' processing

### ISSUE THREAD

**Issue by Racinggavin** [sveltejs/kit#1849]
**Describe the bug**
I follow the sveltekit document [here](https://kit.svelte.dev/docs#adapters) to add adapter in the svelte.config.js. I can make the build folder successfully by `npm i -D @sveltejs/adapter-node@next` then `npm run build` on mac. But I cannot make it work with `docker-compose up`

**Logs**

    $ docker-compose up
    [+] Running 0/1
     ⠿ app-server Error                                                                                                                                4.6s
    [+] Building 14.2s (11/11) FINISHED                                                                                                                     
     => [internal] load build definition from Dockerfile                                                                                               0.0s
     => => transferring dockerfile: 267B                                                                                                               0.0s
     => [internal] load .dockerignore                                                                                                                  0.0s
     => => transferring context: 2B                                                                                                                    0.0s
     => [internal] load metadata for docker.io/library/node:16.4                                                                                       1.0s
     => [internal] load build context                                                                                                                  0.3s
     => => transferring context: 430.81kB                                                                                                              0.3s
     => [1/7] FROM  docker.io/library/node:16.4@sha256:372e674b6fed9b96badff974a334f8380b373149f0fc9cb9e60114ec0ee8b1e0                                 0.0s
     => CACHED [2/7] WORKDIR /usr/src/app                                                                                                              0.0s
     => [3/7] COPY ./app/package*.json ./                                                                                                              0.0s
     => [4/7] RUN npm ci                                                                                                                               8.4s
     => [5/7] COPY ./app ./                                                                                                                            0.7s
     => [6/7] RUN npm i -D @sveltejs/adapter-node@next                                                                                                 1.8s 
     => ERROR [7/7] RUN npm run build                                                                                                                  1.8s 
    ------                                                                                                                                                  
     > [7/7] RUN npm run build:                                                                                                                             
    #11 0.672                                                                                                                                               
    #11 0.672 > post-gql@0.0.1 build                                                                                                                        
    #11 0.672 > svelte-kit build                                                                                                                            
    #11 0.672 
    #11 1.112 vite v2.4.1 building for production...
    #11 1.205 transforming...
    #11 1.704 ✓ 14 modules transformed.
    #11 1.780 /usr/src/app/node_modules/esbuild/bin/esbuild: 1: /usr/src/app/node_modules/esbuild/bin/esbuild: Syntax error: "(" unexpected
    #11 1.791 node:events:371
    #11 1.791       throw er; // Unhandled 'error' event
    #11 1.791       ^
    #11 1.791 
    #11 1.791 Error: write EPIPE
    #11 1.791     at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    #11 1.791     at writeGeneric (node:internal/stream_base_commons:151:3)
    #11 1.791     at Socket._writeGeneric (node:net:770:11)
    #11 1.791     at Socket._write (node:net:782:8)
    #11 1.791     at writeOrBuffer (node:internal/streams/writable:389:12)
    #11 1.791     at _write (node:internal/streams/writable:330:10)
    #11 1.791     at Socket.Writable.write (node:internal/streams/writable:334:10)
    #11 1.791     at Object.writeToStdin (/usr/src/app/node_modules/esbuild/lib/main.js:1719:19)
    #11 1.791     at sendRequest (/usr/src/app/node_modules/esbuild/lib/main.js:617:14)
    #11 1.791     at start (/usr/src/app/node_modules/esbuild/lib/main.js:1252:9)
    #11 1.791 Emitted 'error' event on Socket instance at:
    #11 1.791     at emitErrorNT (node:internal/streams/destroy:193:8)
    #11 1.791     at emitErrorCloseNT (node:internal/streams/destroy:158:3)
    #11 1.791     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    #11 1.791   errno: -32,
    #11 1.791   code: 'EPIPE',
    #11 1.791   syscall: 'write'
    #11 1.791 }
    ------
    failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c npm run build]: exit code: 1

**To Reproduce**
My project tree as below

    app-server/app  <-- Just put skeleton project by 'npm init svelte@next app'
    app-server/Dockerfile
    docker-compose.yml

The docker-compose.yml

    version: "3.9"
    
    services:
      app-server:
        build: ./app-server
        image: app-server:1.0.0
        ports:
          - "3000:3000"
        container_name: app
 
The app-server/Dockerfile

    FROM node:16.4
    
    # Create app directory
    WORKDIR /usr/src/app
    
    COPY ./app/package*.json ./
    RUN npm ci
    
    COPY ./app ./
    RUN npm i -D @sveltejs/adapter-node@next
    RUN npm run build
    
    EXPOSE 3000
    CMD ["node", "build"]

**Expected behavior**
The `npm run build` is totally work fine on mac, I thought it should be successfully generate the build folder in container.

**Stacktraces**
no

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

      System:
        OS: macOS 11.4
        CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
        Memory: 170.53 MB / 32.00 GB
        Shell: 5.8 - /bin/zsh
      Binaries:
        Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
        Yarn: 1.22.4 - /usr/local/bin/yarn
        npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
      Browsers:
        Chrome: 91.0.4472.114
        Firefox: 46.0.1
        Safari: 14.1.1
      npmPackages:
        @sveltejs/adapter-node: ^1.0.0-next.32 => 1.0.0-next.32 
        @sveltejs/kit: next => 1.0.0-next.122 
        svelte: ^3.34.0 => 3.38.3

- The adapter and version:  **@sveltejs/adapter-node@1.0.0-next.32**
</details>

**Severity**
How severe an issue is this bug to you? 
Not so big deal at this moment.

**Additional context**
no

**Comment by benmccann** [comment]
There's no way we could debug this with the given information. I'd guess something must be different between your Docker environment and Mac environment. Try comparing your versions of Node, npm, etc.

**Comment by cayter** [comment]
@Racinggavin May I know why you didn't install `@sveltejs/adapter-node@next` as per normal but installing it separately during the docker build stage? This doesn't make sense 'cause:

- every time you run docker build, you'd probably be using different next version of the `adapter-node` to build the svelte app
- how does your `svelte.config.js` look like?
- are you able to run `npm run build` on your local machine, i.e. outside of the docker container?
- from the error logs, it seems esbuild is complaining you have a syntax error or a syntax that it can't transpile

In any case, all the open source maintainers here aren't magicians, no one would be able to tell exactly what is wrong without being able to reproduce the issue themselves. Imagine you're working in a tech company, and your manager walking to you asking you how did an issue happened without providing much context, how would you think about that?

With that said, it'd be really great if you could just provide the reproducible repo using something like codesandbox.io or github repo, this would have saved the SvelteKit maintainers from getting distracted on unclear issues like this and in return, we get to SvelteKit v1 released in a faster timeline. Thanks.

**Comment by Racinggavin** [comment]
I push the repository on my [github](https://github.com/Racinggavin/svltekit-docker-compose)
and eventually I can successfully create and run production docker image with copy the app-output folder, just push as the 'copy-app-output' branch.

**Comment by cayter** [comment]
This isn't even a SvelteKit issue, I tested it, you guys placed `.dockerignore` outside of the SvelteKit `app` folder which caused your local node_modules (esbuild is a golang binary that needs to be re-compiled on different OS) to also be copied into the docker container which cause your docker build to not re-install and re-build the esbuild binary for the docker container's OS. In short, move `Dockerfile` and `.dockerignore` into the `app` folder if you don't know well enough how to tweak the Docker file paths.

**Comment by cayter** [comment]
This isn't even a SvelteKit issue. I tested it, you guys placed `.dockerignore` outside of the SvelteKit `app` folder which caused your local node_modules (esbuild is a golang binary that needs to be re-compiled on different OS) to also be copied into the docker container which cause your docker build to not re-install and re-build the esbuild binary for the docker container's OS. In short, move `Dockerfile` and `.dockerignore` into the `app` folder if you don't know well enough how to tweak the Docker file paths.

**Comment by cayter** [comment]
This isn't even a SvelteKit issue. I tested it, you guys placed `.dockerignore` outside of the SvelteKit `app` folder which caused your local `app/node_modules` to also be copied into the docker container. In short, move `Dockerfile` and `.dockerignore` into the `app` folder if you don't know well enough how to tweak the Docker file paths.

@benmccann Please kindly close the issue as I've verified it's not SvelteKit issue. Thanks.

**Comment by benmccann** [comment]
Thanks for the investigation @cayter !

**Comment by Racinggavin** [comment]
Really thank @cayter
