### ISSUE TITLE
Place of the main component of the website - Svelte vs SvelteKit

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#1854]
I write in advance that this is really a small thing.

In base Svelte, the main component is `src/App.svelte`.
In SvelteKit, the main component is `src/routes/index.svelte`.

In the basic Svelte, the `routes` folder is not needed, because the page is single - one page anyway.

**Proposal**
I propose to handle an optional situation, WITHOUT the `routes` folder.

**How it is supposed to work**
Quite simply - when SvelteKit detects that the `routes` folder is missing, it looks for the files `index.svelte`, `__error.svelte`, and `__layout.svelte` in the `src` folder.

**Effect**
When you don't need to use many subpages, you can have one nesting less.
It's such a small thing. :)

**Comment by dummdidumm** [comment]
To me this would introduce a point of additional logic to maintain while also making things less consistent between apps, so I'm against this

**Comment by benmccann** [comment]
The location of the `routes` folder is configurable, so you could probably change it from `src/routes` to `src` if you wish

**Comment by lukaszpolowczyk** [comment]
@benmccann It is not it!
Then other `.svelte` files in the `src` directory will be read as subpages, which is not the point!

**Comment by benmccann** [comment]
Regardless I don't think it's something we'd implement for the reasons stated above

**Comment by lukaszpolowczyk** [comment]
@benmccann Well, I understand. It's a trifle anyway.

**Comment by lukaszpolowczyk** [comment]
Since **Fixing load, and tightening up SvelteKit's design before 1.0 #5748,** you are already free to use the advice from [benmccann](https://github.com/benmccann).

There is no longer the problem that files with the `.svelte` suffix will be revealed as page. :D

Basic configuration:

```javascript
import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
    files: {
      routes: "src"
    }
  },
};

export default config;
```

And you can delete the `src/routes` folder. :D

---


You cannot use `App.svelte` instead of `+page.svelte` (formerly `index.svelte`).

But when you create and use `App.svelte` in `+page.svelte`.

And in VSCode `settings.json` in `explorer.fileNesting.patterns` add a line ` "App.svelte": "+page.svelte",` like this:
```json
{
  "explorer.fileNesting.patterns": {
    "*.ts": "$(capture).js, $(capture).*.ts",
    "*.js": "$(capture).js.map, $(capture).min.js, $(capture).d.ts, $(capture).test.js",
    "*.jsx": "$(capture).js",
    "*.tsx": "$(capture).ts",
    "tsconfig.json": "tsconfig.*.json",
    "jsconfig.json": "jsconfig.*.json",
    "package.json": "jsconfig.json, package-lock.json, .npmrc, yarn.lock, .yarnrc, pnpm-lock.yaml, .gitignore, README.md",
    "svelte.config.js": "vite.config.js",
    "app.html": "app.css, app.d.ts, hooks.js, service-worker.js",
    "+page.svelte": "+page.js, +page.server.js, +layout.svelte, +layout.js, +layout.server.js",
    "App.svelte": "+page.svelte",
  },
}
```

Then you have quite a pleasant **effect**:

![obraz](https://user-images.githubusercontent.com/16800535/187561362-73b1daaa-1d0c-4b5d-8e26-e643a592de6a.png)

**:D**
