### ISSUE TITLE
Handle hook doesn’t run on prerendered pages or static content in production

### ISSUE THREAD

**Issue by malinowskip** [sveltejs/kit#1862]
**Describe the bug**
The `handle` hook is not called when the app is built using the `node` adapter and when the server is run directly via node: `node build/index.js`.

**To Reproduce**
1. Initialize the demo app with `npm init svelte@next my-app`.
2. Install the `node` adapter: `yarn add -D @sveltejs/adapter-node`.
3. Put `node()` in `./svelte.config.js` in `config.kit.adapter`.
4. Put a console log in the `handle` function in `src/hooks`.
5. `yarn build`

If you run the application using `node build/index.js`, the hook is triggered only when you navigate to the `/todos` route.

**Expected behavior**
Things work correctly if you run the app with `yarn preview`, i.e. the hook is called on every page and on every refresh. I assume that this is the expected behavior.

**Severity**
This seems to break hooks in production.

**Additional context**
I haven’t tested this with other adapters.

Also doesn't work with static pages: https://github.com/sveltejs/kit/issues/2060

**Comment by malinowskip** [comment]
I assume that when a page is rendered in the browser, then the Node server is not called and the `handle` hook isn’t executed. I found and removed `export const router = browser;` from the `/about` page. After rebuilding, the hook was called when I navigated to the page. I guess that’s how it’s intended to work.

However, I wasn’t able to call the `handle` hook from the `index` page, even after I set `router: false` and `ssr: true` in the config.

**Comment by tw1t611** [comment]
Hi, which other routes do you have? If you are using parameterized routes (e.g. [slug]), you need to add the paths to kit.prerender.pages in `svelte.config.js`

**Comment by malinowskip** [comment]
My issue doesn't relate to prerendering (at least not  directly). In fact, I don't want to pretender anything. The problem I ran into is that the `handle` hook, which should be called on each request, is ignored for some pages in the production (node) build. The app behaves differently in the adapter-agnostic `preview` mode vs. the final bundle compiled by the node adapter.

**Comment by malinowskip** [comment]
Ok, I’ve made some progress.

1. If a given page is prerendered, then it doesn’t trigger the `handle` hook in the node adapter bundle. I assume that’s not the expected behavior since it differs from what happens in preview mode.
2. Builds are not properly invalidated by the node adapter. If I set `prerender` to `false` on a page and rebuild, the page’s old prerendered assets still remain in the `build` directory and cause the original issue described above (the `handle` hook doesn’t get called).

**Comment by iOiurson** [comment]
I have a related question:
is it expected that `handle` runs when building with `svelte-kit build` (on CI for instance) ?

I found out that in my case it is run during CI, and i'm not sure why, since i'm just building the project, not requesting any prerender (i'm not using `prerender` by the way).

**Comment by benmccann** [comment]
@iOiurson you probably did not set `prerender.enabled = false` and so your site is being crawled, which is invoking `handle`

**Comment by malinowskip** [comment]
I spent some more time looking into this and I think I found the cause.

The node adapter uses [polka](https://github.com/lukeed/polka) to process requests, passing each through a series of middleware. The **final** middleware calls the `render` function, which calls the `respond` function, which in turn is responsible for calling hooks.

**Two preceding** middleware functions are `prerendered_handler` and `assets_handler`, which use [sirv](https://github.com/lukeed/sirv) to serve static assets. Sirv doesn’t call `next()` after it serves a static asset, so the middleware chain is halted before it reaches the final function.

**Comment by benmccann** [comment]
@malinowskip can you clarify what your use case is? I asked Rich about this and he suggested it was working as intended. After a page has been rendered, is it still useful to call `handle`? What for?

We would at least need to update the docs though. Right now the first sentence is "this function runs on every request", which isn't strictly true

**Comment by malinowskip** [comment]
Thanks, @benmccann. I was originally exploring SvelteKit’s client/server-side capabilities and tried to use the `handle` hook to log requests in a database. I thought that calling `handle` on each request might be useful for implementing server-side analytics. I imagine `handle` could be used to handle things like authorization.

> We would at least need to update the docs though. Right now the first sentence is "this function runs on every request", which isn't strictly true

Yes, I agree. After initially reading the docs, I assumed that `handle` would run every time the server processed a request.

**Comment by benmccann** [comment]
> I imagine handle could be used to handle things like authorization

You're almost certainly won't prerender a page that can be logged into. If you want to display the logged in user, or a logout button, or anything else that might differ between visits then you can't prerender it

> I thought that calling handle on each request might be useful for implementing server-side analytics

Hmm, yeah, that is a really good use case we should figure out how to support

**Comment by benmccann** [comment]
I think the best way to support that use case will be to use your adapter. E.g. for `adapter-node` we can expose a way to let you add middleware. I'll update the docs to clarify

**Comment by malinowskip** [comment]
Thanks, I think that clarifies everything. The ability to add middleware to each request would be a cool feature to have in the future.
