### ISSUE TITLE
XSS in href attribute, issue a warning

### ISSUE THREAD

**Issue by m1212e** [sveltejs/kit#1864]
As stated in [this ](https://github.com/sveltejs/svelte/issues/6423)issue, Sveltekit might be the right place to adress this.

**Comment by benmccann** [comment]
@pngwn can you clarify what you had in mind in terms of SvelteKit doing about it?

**Comment by pngwn** [comment]
No idea. But if we are going to solve this then we should be doing it in kit. I'll have a think.

**Comment by benmccann** [comment]
You can address this with a content security policy (CSP): https://github.com/sveltejs/kit/issues/93

I'm going to close this given that there's no concrete proposal for what we might do besides that
