### ISSUE TITLE
ESM module error in production, using adapter-node

### ISSUE THREAD

**Issue by yadoga** [sveltejs/kit#1865]
Tested with the standard SvelteKit demo app and addition of adapter-node in the config as per usual:

```
import adapter from '@sveltejs/adapter-node'

const config = {
    kit: {
        // hydrate the <div id="svelte"> element in src/app.html
        target: '#svelte',
        adapter: adapter()
    }
};

export default config;
```

`node build/` works locally, but is failing in production:

```
(node:16609) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/[...]/build/index.js:40
import { createRequire } from "module";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```
 
So far I have tried:

- renaming the build's index.js to index.mjs
- "type": "module" in package.json (as is the default now)
- importing via `require` in the config like so

```
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const adapter = require('@sveltejs/adapter-node'); 
```

Versions used _(all 'latest'):_
- Server running NodeJS 16.4.2
- SvelteKit 1.0.0-next.123
- adapter-node 1.0.0-next.32

**Comment by ignatiusmb** [comment]
The `build` folder should contain the production version, I don't understand how `node build/` can work locally but fails in production, and I don't think there's anything we can do if it's tied to the prod environment since we can't even reproduce the error that way.

It would helpful if you can make a small repo and reproduce it locally. Also, try synchronizing your production server to have all the same environment and settings as your local machine, or the other way around.

**Comment by rvrm** [comment]
Thanks, would you happen to have a particular environment setting in mind? 

Was going to prepare a small repo, but figured since this did not even work with the default SvelteKit Demo on my server it would probably be some discrepancy between local and live setup. Will see what I can sort out…

**Comment by yadoga** [comment]
Thanks, would you happen to have a particular environment setting in mind?

Was going to prepare a small repo, but figured since this did not even work with the default SvelteKit Demo on my server it would probably be some discrepancy between local and live setup. Will see what I can sort out…

**Comment by yadoga** [comment]
Solved this: My node_modules in production were not installed correctly. Thanks again for your time!

**Comment by Catsvilles** [comment]
I have the same problem when trying to deploy to DigitalOcean :(

@yadoga How did you manage to solve this?
