### ISSUE TITLE
adapter-static does not prerender

### ISSUE THREAD

**Issue by tw1t611** [sveltejs/kit#1868]
**Describe the bug**
`adapter-static` does not prerender `load()`.
I am using a headless cms and want to prerender pages using the data of the cms at build time.
There should be no request to the cms afterwards.

**To Reproduce**
1. create route `index.svelte`
```svelte
<script context="module">
  import Main from "$lib/main/Main.svelte";
  import _fetch from "$lib/utils/fetch.js";
  import getQueries from "$lib/main/queries.js";

  export async function load({ page, fetch }) {
    let pageData = await _fetch(getQueries("/").pageQuery, fetch);
    pageData = pageData?.pages?.find((page) => page.locale === "de");
    const trustImagesData = await _fetch(
      getQueries("/").trustImagesQuery,
      fetch
    );

    return {
      props: {
        pageData,
      },
    };
  }
</script>

<script>
  export let pageData;
</script>

<Main {pageData} />
```

Adding `if (browser) { ... }` to `load()` results in not loading the content

You can check the behavior here:
https://ari-motors-v2.vercel.app/

**Expected behavior**

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Linux 5.12 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 1.94 GB / 15.06 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.3/bin/yarn
    npm: 7.17.0 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.9 => 1.0.0-next.13 
    @sveltejs/kit: ^1.0.0-next.101 => 1.0.0-next.122 
    svelte: ^3.35.0 => 3.38.3 

browser independent
adapter-static
</details>

**Severity**
Normally not a big deal. In my case the performance makes the site hard to use.

**Comment by Conduitry** [comment]
You should either disable hydration and routing (so that you're always getting JS-free pages), or you should create local endpoints that proxy to your remote ones (or do the proxying in the `handle` hook) so that the responses to them can be saved out to local files when prerendering.

**Comment by tw1t611** [comment]
Thanks for your reply. The `handle` hook seems to be exactly what I need.

So far I got this, but I think I missed something.

src/hooks.js
```js
import _fetch from "$lib/utils/fetch.js";
import getQueries from "$lib/main/queries.js";

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ request, resolve }) {
  let pageData = await _fetch(getQueries(request.path).pageQuery, fetch); // got the right data
  request.body = pageData; // contains the data

  // what next?

  const response = await resolve(request);

  return {
    ...response,
    headers: {
      ...response.headers,
    },
  };
```

I can't see any new data sets, or chunks in `/build`. So how does the "save to local files" work?
