### ISSUE TITLE
Full page reload after clicking any link

### ISSUE THREAD

**Issue by emmarvpol** [sveltejs/kit#1881]
Hello!

I added some links on my svelte kit website (```<a href="/about">About</a>```) and it does a full page reload. 
Am I doing something wrong?

Updated: I think it may be related to this error:
[HMR][Svelte] Unrecoverable error in <Navbar>: next update will trigger a full reload
Im getting menu items in a store from my api.

Thanks!

**Comment by benmccann** [comment]
please follow the issue template
