### ISSUE TITLE
Endpoints as GraphQL APIs in Svelte kit.

### ISSUE THREAD

**Issue by NinekoTheCat** [sveltejs/kit#1883]
# GraphQL as an alternative to RESTful APIs in svelte kit endpoints.
---
## What's the issue with endpoints?

I'm unhappy with the current state of endpoints. Granted, they are amazing, however they have a few minor issues. For example, imagine you have an app that lets users post blog posts, you store these blog posts in a database making sure to keep it away from the user's hands. To accomplish this, you create a server side endpoint in JavaScript to handle the requests for the information about the blog pages. So, your site is gaining traction and your levels of users have skyrocketed. But you want to add a really cool feature to your blog posts, for example comments tied to words, now because you have a giant endpoint that has all post information in it. You didn't expect your site to grow so large, after all. So you go into the deep jungle of code to add your cool new feature, after you add it you feel content and start the many many many tests you have. The next day, you wake up and notice that your whole site code needs to be reworked to handle the new change, and your site is slower as users have to wait for this information. Since you had no way of splitting it up now you have a few solutions to your problem. You either split your post logic into smaller files, or add logic that lets you choose what information you get back. Both of those kinda suck as your client side code has to either request multiple endpoints and add onto the server's load, or request multiple times from one endpoint.

---
## How can we solve this issue?

Well thankfully this issue has been solved long ago by the wonderful people that created GraphQL, now we can just define what we want from our server, and we get it back in JSON format. And if you add more types to your schema, nothing will break! However, we run into a big issue. In svelte kit, there is no good support for it. Sure, you can implement your own custom logic, but it'll require loads of boilerplate code.

---
## What I'd love to see in svelte kit!

A special type of endpoint that accepts GraphQL queries. And you can define special get functions that handle these events emitted server side by the server, and we can have it all be nicely formatted into one neat JSON package afterwards. Or even better, we can put those functions into multiple JavaScript files and have the endpoint access point be the folder they are in! So if you want a new type of data to be added to your objects it'll be no problem, just add a function and if the client requests it, then it'll be used, and nothing else will break. This also allows better individual testing of the components, as you can just query all the types in the schema and know what breaks when it does.

---
## How important is this to ME?

This is important to me as I'd like svelte kit to offer even more cool features not found natively in other frameworks, and it would definitely be a good addition in my opinion.

---
### Relevant links

* [GraphQL homepage](https://graphql.org).
* [GraphQL vs rest](https://www.howtographql.com/basics/1-graphql-is-the-better-rest/).

**Comment by babichjacob** [comment]
Be aware there are existing solutions for hosting a GraphQL server through your SvelteKit app:
* https://github.com/kamalkech/sveltekit-graphql/blob/main/src/routes/graphql.ts
* https://github.com/svelte-add/graphql-server

**Comment by NinekoTheCat** [comment]
> Be aware there are existing solutions for hosting a GraphQL server through your SvelteKit app:
> 
>     * https://github.com/kamalkech/sveltekit-graphql/blob/main/src/routes/graphql.ts
> 
>     * https://github.com/svelte-add/graphql-server

Yeah, but wouldn't it be amazing if you didn't have to install these things just to make a GraphQL compliant endpoint?

**Comment by benmccann** [comment]
> wouldn't it be amazing if you didn't have to install these things just to make a GraphQL compliant endpoint?

The problem is that there are people who would say that we should also have support for firebase, postcss, sass, less, bulma, coffeescript, pug, etc. all built in as well. Pretty soon it becomes a huge unmaintainable and broken mess. I think GraphQL is great, but `svelte-add` makes it pretty easy to add and I think that's a better solution for this to keep the core slim and clean
