### ISSUE TITLE
FAQ: Does svelte-kit support native mobile apps?

### ISSUE THREAD

**Issue by chovy** [sveltejs/kit#1884]
### Describe the problem

Just want to know if svelte-kit supports native mobile apps.

### Describe the proposed solution

Answer in Faq

### Alternatives considered

No, use svelte-native

### Importance

i cannot use SvelteKit without it

**Comment by didier** [comment]
You might want to take a bit of extra effort to describe your issue.The team probably can’t help you with such little information. Also, for regular questions, you could ask in the Discord. This way, we keep the issues focused and organised. Kit is a different project than Svelte Native, and thus isn't compatible.

**Comment by Mlocik97** [comment]
Use svelte-native

**Comment by dominikg** [comment]
The sveltekit homepage mentions it's for the web in two prominent places already

on https://kit.svelte.dev/
> SvelteKit is a framework for building **web applications** of all sizes, with a beautiful development experience and flexible filesystem-based routing.

on https://kit.svelte.dev/docs
> SvelteKit is a framework for building extremely high-performance **web apps.** You're looking at one right now! There are two basic concepts:
(emphasis mine)

So no, it does not support building native apps out of the box. Please use discord for questions.
