### ISSUE TITLE
No types in the npm package

### ISSUE THREAD

**Issue by btakita** [sveltejs/kit#1887]
### Describe the bug

There are no Typescript types included in the npm package.

### Reproduction

`npm i @sveltejs/kit`

### System Info

```shell
System:
    OS: Linux 5.12 Arch Linux
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 26.27 GB / 62.78 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.4.2 - ~/.config/nvm/versions/node/v16.4.2/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.18.1 - ~/.config/nvm/versions/node/v16.4.2/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chromium: 91.0.4472.114
```

### Severity

annoyance

**Comment by Conduitry** [comment]
There are types in the `@next` version. If you're installing `@latest`, you're getting the very first version published, `@sveltejs/kit@1.0.0-next.1`, which doesn't have types (or a whole lot of other things).
