### ISSUE TITLE
Add directory imports when generating packages

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1891]
### Describe the problem

`npm run package` creates a default entry point for an `index.js` (or `index.svelte`) file directly inside `src/lib`, but not for other index files. In other words these files...

```
src/lib/index.js
src/lib/foo/index.js
src/lib/bar.svelte
```

...will result in the following `pkg.exports`:

```js
"exports": {
  "./package.json": "./package.json",
  "./index.js": "./index.js",
  "./foo/index.js": "./foo/index.js",
  "./bar.svelte": "./bar.svelte",
  ".": "./index.js"
}
```

### Describe the proposed solution

I think this would be preferable:

```diff
"exports": {
  "./package.json": "./package.json",
- "./index.js": "./index.js",
- "./foo/index.js": "./foo/index.js",
+ "./foo": "./foo/index.js",
  "./bar.svelte": "./bar.svelte",
  ".": "./index.js"
}
```

In other words, index files are never referenced directly, only by the containing folder. (A clashing `index.js` and `index.svelte` would presumably be an error in this scenario.)

### Alternatives considered

There are basically four options:

1. always be explicit (i.e. even `src/lib/index.js` doesn't get special treatment). Consistent, but ugly
2. the status quo (make an exception for the main entry point)
3. generate directory entry points in _addition_ to the existing file entry points. Consistent, but ugly, and probably a bit confusing (which do you document? both? ugh)
4. this proposal: only generate directory entry points for any `index.[whatever]` files. Slightly less consistent, but a definite aesthetic win. This sort of thing is encouraged by the design of `pkg.exports`, even though native ESM ordinarily requires you to be very explicit, and it will be familiar to Node users (i.e. basically all of us)

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Option 5: set the `exports` field yourself manually. This was changed recently; that field is not generated if it already exists on your `package.json`. Things like this sound like use cases for doing this and keep the config somewhat lean.

**Comment by Rich-Harris** [comment]
Sure, but we still need a sensible default. There's value in having predictable behaviour — if people are using the escape hatch of setting `exports` themselves it's because the framework itself is falling short
