### ISSUE TITLE
File '/**project root**/node_modules/source-map-js/source-map' not found.

### ISSUE THREAD

**Issue by digidub** [sveltejs/kit#1897]
### Describe the bug

The following error appears in VScode:

```
File '/**project root**/node_modules/source-map-js/source-map' not found.
  The file is in the program because:
    Root file specified for compilation
```

### Reproduction

Create a skeleton app using the following:

```
npm init svelte@next my-app
cd my-app
npm install
```

open `jsconfig.json`.

Error appears in error window.

### System Info

```shell
:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 243.95 MB / 7.68 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.14.0 - ~/.nvm/versions/node/v14.14.0/bin/node
    npm: 7.16.0 - ~/.nvm/versions/node/v14.14.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.20 => 1.0.0-next.20 
    @sveltejs/kit: next => 1.0.0-next.125 
    svelte: ^3.34.0 => 3.38.3
```

### Severity

annoyance

**Comment by benmccann** [comment]
I just tried following the steps suggested and was not able to reproduce any error. If you are still able to reproduce this on a new project, please provide additional details about where you are seeing the error.

![Screenshot from 2022-03-06 08-49-14](https://user-images.githubusercontent.com/322311/156933096-669f5983-3e50-434e-ae2c-12405632a6f9.png)
