### ISSUE TITLE
Favicon on showing in Demo app or Skeleton App when using Node Adapter

### ISSUE THREAD

**Issue by mharding7va** [sveltejs/kit#1902]
### Describe the bug

The favicon file, favicon.png does not load in the demo or skeleton app.  Notice the issue in my own dev app and tested the demo apps to see if the problem exists.

Issue exists in dev or build versions.

### Reproduction

```
npm init svelte@next my-app
cd my-app
npm install
npm run dev
```

Select Demo App.

You will see no favicon in the browser tab, yet the page graphic, WELCOME, text show fine.

npm run dev > same result

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.57 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.33 => 1.0.0-next.33 
    @sveltejs/kit: next => 1.0.0-next.127 
    svelte: ^3.34.0 => 3.38.3
```

### Severity

annoyance

**Comment by benmccann** [comment]
I can't reproduce this

Here's the favicon I see:
![Screenshot from 2021-07-14 08-07-28](https://user-images.githubusercontent.com/322311/125645881-1d863832-8882-4e7b-b32a-329bb5aa7410.png)

**Comment by mharding7va** [comment]
Seems to be a node version issue. Not sure why but upgrading node and npm to latest resolved issue.
