### ISSUE TITLE
Importing from d3-scale causes page load to hang forever

### ISSUE THREAD

**Issue by plmrry** [sveltejs/kit#1908]
### Describe the bug

When importing from `d3-scale@4`, the page never loads. No error is logged. 

This happens even when disabling ssr with `export const ssr = false`

### Reproduction

https://github.com/plmrry/svelte-kit-import-d3-bug/blob/main/src/routes/index.svelte

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.09 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 88.0.1
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.128 
    svelte: ^3.34.0 => 3.38.3
```

### Severity

blocking all usage of SvelteKit

**Comment by plmrry** [comment]
Note that this is fixed by downgrading from `d3@7` to `d3@6`, so this must have something to do with the recent d3 module switch

**Comment by benmccann** [comment]
Thanks for reporting Paul. I would expect that the bug most likely is in Vite. Perhaps https://github.com/vitejs/vite/issues/2491

A couple things you might try:
- Can you reproduce it on a Vite SSR project that isn't SvelteKit? You could try adding it to https://github.com/sveltejs/vite-plugin-svelte/tree/main/packages/e2e-tests/vite-ssr
- Does https://github.com/vitejs/vite/pull/3950 fix it for you?

**Comment by benmccann** [comment]
I expect that this is now fixed with the latest version of Vite
