### ISSUE TITLE
Cannot read property 'split' of undefined - Netlify adapter

### ISSUE THREAD

**Issue by Bradley-H** [sveltejs/kit#1911]
### Describe the bug

When I upload my project I keep getting cannot read property of "split".

I suspect this has something to do with the adapter and not of Svelte itself since I can run a dev server just fine. 

For whatever it might be worth, here is my project in question - https://github.com/Bradley-H/portfolio

### Reproduction

upload to netlify

### System Info

```shell
It uploads to netlify just fine, no problem
```

### Severity

blocking an upgrade

here is my website on netlify if you need it - https://bradley-portfolio.netlify.app/

**Comment by Bradley-H** [comment]
here is my website on netlify if you need it - https://bradley-portfolio.netlify.app/

**Comment by 0xPiyush** [comment]
Hello, I am facing the same issue, I tried deploying my Sveltekit app on netlify, on visiting the app, 
[https://sveltekit-pokedex.netlify.app/](https://sveltekit-pokedex.netlify.app/)
it shows:
`Cannot read property 'split' of undefined`

Here's the netlify function logs:

```
4:12:50 PM: a210dba2 ERROR  TypeError: Cannot read property 'split' of undefined
    at parse_body (/var/task/index.js:2082:57)
    at respond (/var/task/index.js:2171:15)
    at render (/var/task/index.js:2495:10)
    at Runtime.handler (/var/task/index.js:2722:26)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
```

The build succeeds and the website gets deployed but shows the above error, when testing locally using npm run build / npm run preview, the site works as intended, but shows the above error when deployed.
If you want to see the web app's code here it is:
[https://github.com/0xPiyush/sveltekit-pokedex](https://github.com/0xPiyush/sveltekit-pokedex)

using svelte netlify adapter. [https://www.npmjs.com/package/@sveltejs/adapter-netlify](https://www.npmjs.com/package/@sveltejs/adapter-netlify)

node: v14.17.2
Dev Dependencies: 
    
```
"@sveltejs/adapter-netlify": "^1.0.0-next.22",
"@sveltejs/kit": "next",
"autoprefixer": "^10.3.1",
"svelte": "^3.34.0",
"tailwindcss": "^2.2.4"
```

netlify.toml file:
```
[build]
    command = "npm run build"
    publish = "build/"
    functions = "functions/"
[build.environment]
    NODE_VERSION = "14.17.2"
```

**Comment by JeanJPNM** [comment]
By looking at the stacktraces it looks like the `content-type` header is `undefined` making it throw an error [here](https://github.com/sveltejs/kit/blob/53e9285df39a3feba3407a7541328de2960174e5/packages/kit/src/runtime/server/parse_body/index.js#L10)

**Comment by 0xPiyush** [comment]
@JeanJPNM but this only occurs on the deployed version and not when running/hosting locally.

**Comment by JeanJPNM** [comment]
Can you show me the request data (headers, uri, etc)?

**Comment by JeanJPNM** [comment]
And whether you were making a request to a page or endpoint

**Comment by JeanJPNM** [comment]
Ok, so the whole website doesn't work

**Comment by JeanJPNM** [comment]
Not only the main page responds with a 500 status, all the requests do

**Comment by 0xPiyush** [comment]
> Ok, so the whole website doesn't work

yes, none of the routes work on the deployed but if you clone the repo and run it locally, everything runs perfectly

**Comment by seenickcode** [comment]
@Bradley-H , @0xPiyush I'm getting the same issue as well (with Node v16.5.0). Have you both considered additionally posting the issue on one of Netlify's Github Issue trackers?

**Comment by 0xPiyush** [comment]
@seenickcode I created a post in the netlify support forum and they said that they've seen numerous issues on this forum with Sveltekit, though this is the first of this nature, and asked me to add to this issue. I haven't created an issue on Netlify's issue trackers yet.

**Comment by benmccann** [comment]
Don't post on Netlify's Github. This is our issue

https://github.com/sveltejs/kit/blob/53e9285df39a3feba3407a7541328de2960174e5/packages/kit/src/runtime/server/parse_body/index.js#L10

**Comment by benmccann** [comment]
I just moved that line of code: https://github.com/sveltejs/kit/pull/1916

Can y'all try @sveltejs/kit@1.0.0-next.131 and see if it works any better?

**Comment by 0xPiyush** [comment]
Thank you @benmccann #1916 fixed this issue.

**Comment by vish01** [comment]
@benmccann I'm still getting this error, but with adapter-node.

**Comment by rchrdnsh** [comment]
I’m getting this error as well. I did some sleuthing by publishing previous deploys until the problem went away and then comparing `netlify-adapter` releases…I went back to version 1.0.0-next-20 and the issue went away for me…so I’m assuming maybe something was broken in next-21? Dunno if this is helpful or not.

**Comment by JeanJPNM** [comment]
Are you using the most recent version of `@sveltejs/kit`?

**Comment by rchrdnsh** [comment]
kit: 131
netlify-adapter: 20

I just read Ben’s comment saying to try 131 with the latest adapter…I’ll try that next…

**Comment by rchrdnsh** [comment]
yes!

I updated to the latest of both kit and the netlify adaptor and the problem has indeed gone away for me...thank you @benmccann XD

**Comment by vojtechsedlak** [comment]
Running into this issue again with kit: 286 and netlify-adapter: 47. The build compiles and previews fine locally, but on Netlify results in the cannot read property 'split' of undefined error despite no errors getting thrown in the deployment. Any thoughts?
