### ISSUE TITLE
emit_dts in svelte-kit package should respect the file excludes config

### ISSUE THREAD

**Issue by truumahn** [sveltejs/kit#1923]
### Describe the problem

It's fantastic that automatic type generation is included with the `package` command, however it seems `svelte2tsx` [doesn't accept any other configuration besides the lib root directory](https://github.com/sveltejs/language-tools/blob/master/packages/svelte2tsx/src/emitDts.ts#L8) so when the [types are generated](https://github.com/sveltejs/kit/blob/1f8abd9aa3f244c1011f2b65a5d20d489989c319/packages/kit/src/core/make_package/index.js#L17) with `svelte-kit package`, all files get generated types.

This is not desired when `.stories.svelte`, `.test.ts` or `.test.svelte` files (files that [help test slots as a workaround](https://svelte-recipes.netlify.app/testing/#testing-slots)) are next to the `.svelte` files in the `lib` directory.

### Describe the proposed solution

It would be great to have the file excludes respected during type generation. I understand that it might be `svelte2tsx` that needs to be altered to make this work.

### Alternatives considered

For now I think I'll include a `post-package` script that cleans up files that match the glob in `excludes`. It's a hacky workaround, why generate files that need to be cleaned up, right?

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
`svelte2tsx` is basically a wrapper around `tsc` which then does all the heavy lifting of generating types. I don't think TypeScript has options regarding what to generate and what not to generate. What could work though if you add an `excludes` property to your `tsconfig.json`  where you exclude all these `.test.svelte` files. Unless `.test.svelte` files are not imported from some other file in the `includes` array, they should be ignored.

**Comment by truumahn** [comment]
But I do want these type checked, and the files you are referring to are one thing. I don't think it's uncommon to store component specific test files (in this case, `jest`) next to the components (e.g. `Component.test.ts`).

What you are saying is, if I want to keep type checking these files I should move them out of the `lib` directory so they don't get "packaged"?

**Comment by dummdidumm** [comment]
Telling tsc what to compile and what not to compile is exactly what `includes` and `excludes` is for in their `tsconfig.json` . If you still want that type-checked, you can create a `tsconfig.test.json` and refer to that config when running type checks for these files.

I guess what I'm saying is
- `tsc` is not very configurable in that regard
- working arond that with multiple tsconfigs is cumbersome but probably the most common way to do this

Adding additional logic to also remove the `d.ts` files that are matched by the `excludes` option of the `package` command might work, but may also be brittle since it's it could mean files are removed that some other not-removed files depend on. Then again, the same can be said about other files that are matched by the `excludes`.

**Comment by truumahn** [comment]
Is it not possible to emit the `d.ts` files based on the package contents? So `libRoot` is not `config.kit.files.lib` but `config.kit.package.dir`.

I can see how that might raise an issue with the handwritten `d.ts` files, but this way `excludes` and `emitTypes` would be in sync. I cannot propose a working solution right now, if others would find figuring this out useful as well then I can look into it further.

I cannot say how many people have similar project structures as I do, I also don't want to push this issue further if this is clearly an edge case but I can imagine that others will also see discrepancies when using `emitTypes` with a bunch of file `excludes`.

Maybe even a little documentation would help that says, `emitTypes` is based on the `tsconfig.json` file and the SvelteKit `package` config regarding file excludes doesn't affect it. I also understand if this is 100% clear for everyone except me. 🙂

**Comment by dummdidumm** [comment]
Yeah some more documentation definetly would help. I also get your discrepancy-concerns. Personally I also colocate my test files next to their implementation, and I guess many others do, too, so this isn't an edge case IMO.

**Comment by dummdidumm** [comment]
Ok I think you convinced me. Generated d.ts files for files that are excluded would make you assume that these files exist when really they don't. If this breaks you package then your `excludes` is wrong. So if you want you can go ahead and create a PR for this. I'll maybe look into this some time next week.

**Comment by ignatiusmb** [comment]
Emitted declarations should not get included when the source file is excluded in `.156` and above.
