### ISSUE TITLE
Add SvelteKit logo to pnpm "Who's Using This?" section

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/kit#1927]
### Describe the problem

It would be useful both for the further promotion of SvelteKit and pnpm to add the company logo to https://pnpm.io/users

### Describe the proposed solution

Add the company logo to https://pnpm.io/users, Zoltan from pnpm said in the Discord that he encourages new companies to do that.

### Alternatives considered

Just not care about it

### Importance

nice to have

**Comment by benmccann** [comment]
Sounds fine to me if you'd like to submit it

**Comment by mhatvan** [comment]
PR submitted to: https://github.com/pnpm/pnpm.github.io/pull/127

**Comment by benmccann** [comment]
Cool! I'll go ahead and close this then
