### ISSUE TITLE
Issue with 1.0.0-next.111 

### ISSUE THREAD

**Issue by pararell** [sveltejs/kit#1928]
### Describe the bug

I'm using @sveltejs/adapter-node and when I try to build application with svelte-kit build, I have this error -
**render2 is not a function**
It's happening since 1.0.0-next.111, so since this change
**eae1b1d: Rename handle's render parameter to resolve**
It wasn't event breaking change, but it prevents me to build app with version 1.0.0-next.111 and higher. 
I tried it with lts node and latest node version.

### Reproduction

https://github.com/pararell/svelte-blog

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 182.91 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.33 
    @sveltejs/kit: 1.0.0-next.131 => 1.0.0-next.131 
    svelte: ^3.38.2 => 3.38.2
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
According to your `package-lock.json`, you're not on the latest version of `@sveltejs/adapter-node` which is `1.0.0-next.33 ` . Did you try forcing an update of the adapter?

**Comment by pararell** [comment]
I added `@sveltejs/adapter-node 1.0.0-next.33`, but it didn't help, I pushed the changes to branch.

**Comment by pararell** [comment]
Ok I found the problem, I used in hooks.js `export const handle = async ({ request, render }) =>` according to older documentation, but now it is updated to `export const handle = async ({ request, resolve }) =>`, so it is working fine. Anyway thanks for checking the issue!
