### ISSUE TITLE
more detail doc (or how to set alias to router?)

### ISSUE THREAD

**Issue by y0zong** [sveltejs/kit#1929]
### Describe the bug

so as a url like `www.some.com/somebody/post/id` can use a file in `/routes/post/index.svelte` not `/routes/somebody/post/index.svelte`? I found doc says `/routes/[someone]/post/index.svelte` is support but it not work for me(404 forever), so is there more detail doc for this case or some way to set up alias?

### Reproduction

none

### System Info

```shell
none
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
You say you want an url like `/somebody/post/id` . This url is not expressed by `/routes/[someone]/post/index.svelte` , the correct path would be `/routes/[someone]/post/[slug].svelte`

**Comment by y0zong** [comment]
sorry for my poor english and it still not work, anyway, I give up for now

**Comment by y0zong** [comment]
> sorry for my poor english and it still not work, anyway, I give up for now

files-base route is too sparse to me, but finally it work. and how to route as modal? I found [this answer](https://stackoverflow.com/questions/61185073/route-as-modal-in-sapper) but a little hack, is there a better way?
