### ISSUE TITLE
How do I make a script run only the first time the `layout` is instantiated and not all subsequent pages (which inherit that `layout`)?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1930]
### Describe the bug

In a new Svelte Kit project I have a `<script context="module">` in `__layout.svelte`.

The `load` function in it is called on each page I change.

I thought instead it was only called when the `layout` is instantiated for the first time.

I'm doing it wrong?

**How do I make a script run only the first time the `layout` is instantiated and not all subsequent pages (which inherit that `layout`)?**

### Reproduction

https://github.com/frederikhors/issue-svelte-kit-layout-context-module-load-always-called

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.117 => 1.0.0-next.131
    svelte: 3.38.3 => 3.38.3
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Yes, that's the way it works, although that may need better documentation. What's the use case for running it only the first time?

**Comment by frederikhors** [comment]
To detect if the user is loggedIn otherwise it redirects to `/login`.

I prefer this way over `onMount` because I can avoid to load everything `import`ed in `__layout.svelte`.

But I just found that it repeats the actions on every page change and honestly it doesn't suit me, so I'll use `onMount` with an `isLoaded` boolean.

Do you have better ideas?

But when you think about it, why repeat the `load` operation on every page change?

**Comment by kevmodrome** [comment]
The way it works feels backwards to me. I wouldn't expect the layout to be re-mounted when I change pages - I guess that's the case?

**Comment by Kapsonfire-DE** [comment]
For me the layout is called only once using onMount ... it will just rerun on errors

**Comment by kevmodrome** [comment]
If onMount only runs once I would definitely not expect load to run more than once. Just my 2 cents though.

**Comment by frederikhors** [comment]
> For me the layout is called only once using onMount ... it will just rerun on errors

Yep. We're talking about `load` in `context="module"`.

**Comment by Kapsonfire-DE** [comment]
Your load is everytime called because you destructuring page
page is changed on navigation, so load is recalled everytime a destructuring variable changes

**Comment by frederikhors** [comment]
> Your load is everytime called because you destructuring page
> page is changed on navigation, so load is recalled everytime a destructuring variable changes

You're right! But this is the problem I think.

Is there a way to avoid this "reactivity"?

**Comment by frederikhors** [comment]
It's the same also without destructuring, the below code make it `load` re-run on each page change:

```ts
export function load(input: LoadInput): LoadOutput {}
```

**Comment by Kapsonfire-DE** [comment]
Of course, you make ist reactive to all properties. Using load({}) Should work

Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by frederikhors** [comment]
Yeah, but with `{}` we have the same problem: how to execute `load` the first time only?

**Comment by Kapsonfire-DE** [comment]
if you need the page, you can import the page store and use the get method inside load

**Comment by frederikhors** [comment]
> if you need the page, you can import the page store and use the get method inside load

I do not understand. Do you have a code example?

**Comment by Kapsonfire-DE** [comment]
```
import {page} from "$app/stores";
 import {get} from "svelte/store";

export async function load({}) {
    let pageVar = get(page);
   

}
```

**Comment by frederikhors** [comment]
> ```
> import {page} from "$app/stores";
> import {get} from "svelte/store";
> 
> export async function load({}) {
>   let pageVar = get(page);
>  
> 
> }
> ```

What a brute hack.

I think we deserve something better.

**Comment by Kapsonfire-DE** [comment]
this is neither a hack or something fiddly

the load function is reactive to the properties you destruct.. if the page isnt important for your load function, remove it.
if the page is important, of course rexecute the load... its very simple...

I still don't see a valid usecase, why it shouldnt be reactive...

**Comment by frederikhors** [comment]
Because it's a **layout** file. Not a **page** file.

**Comment by Kapsonfire-DE** [comment]
Then don't use the parameters and it works

**Comment by frederikhors** [comment]
And if I need parameters on the first load? Your "hackyish" way.

**Comment by Kapsonfire-DE** [comment]
and thats  what @dummdidumm and me asked for. show a usecase
and my way isnt hackyish, its the way svelte works

**Comment by kevmodrome** [comment]
Ah, so it does only run once as long as you don't use any of the inputs, that seems reasonable. I think a couple of sentences in the documentation might be good here.

**Comment by Kapsonfire-DE** [comment]
yes, its only reactive to the variables you define in the method header
if you use page in the method, it will run every time you navigate because page changes

**Comment by benmccann** [comment]
Closing given the improved documentation. Thanks for sending that PR!
