### ISSUE TITLE
CSS is imported incorrectly when transitive function is imported in layout

### ISSUE THREAD

**Issue by raiyni** [sveltejs/kit#1933]
### Describe the bug

I'm not sure if the CSS is being imported out of order or if there is rendering/race condition. But when I have a function named `get` being imported into a function that could be used in a layout component, the CSS is improperly applied. 

Assuming the following:

* __layout: apply css
* Route: index
* Route: features, override parent css

If you navigate from index to features, the css of features would be correctly applied. But child's imported CSS would not be rendered correctly if you came into the page on that route

### Reproduction

I have an example repo with this exact structure here https://github.com/raiyni/svelte-css-problem. If you comment `line 1` from `$lib/errorFile.js` and uncomment the other lines, the css is rendered correctly for `/features`.

So the structure would look like

```
routes
	__layout ->
		import app.css
		import Navbar -> 
			import { someFunc } from file ->
				import { get } from api
	index 
	features -> 
		import Feature -> 
			import feature.css
```

app.css could have
```css
.card { background-color: red; }
```

feature.css could have
```css
.card { background-color: green; }
```

and when navigating to /feature from index, the card background would be green (correctly) but if you refresh the page--or build and serve it--the background would be red (wrongly).

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 5.61 GB / 15.94 GB
  Binaries:
    Node: 16.3.0 - ~\AppData\Local\nvs\default\node.EXE
    Yarn: 1.22.5 - ~\.yarn\bin\yarn.CMD
    npm: 7.15.1 - ~\AppData\Local\nvs\default\npm.CMD
  Browsers:
    Chrome: 91.0.4472.124
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.70)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.13
    @sveltejs/kit: next => 1.0.0-next.131
    svelte: ^3.38.2 => 3.38.3
```

### Severity

This blocks upgrading react websites with componentized CSS imports

**Comment by raiyni** [comment]
This appears to be a possible issue with vite/SSR maybe? 

* When hydrate is set to false, the incorrect css is loaded 
* When ssr is set to false, the correct css is loaded

**Comment by benmccann** [comment]
Yes, it quite well could be an issue with Vite since Vite handles most of the asset building. A good way to test would be to see if you can reproduce on a Vite project without SvelteKit such as https://github.com/sveltejs/vite-plugin-svelte/tree/main/packages/e2e-tests/vite-ssr. I'd recommend trying that and then filing an issue with Vite assuming you can reproduce it without SvelteKit. You're a lot more likely to get help there since there'd be more people familiar with that part of the system
