### ISSUE TITLE
TypeScript: svelte-kit package does not copy custom event payload types

### ISSUE THREAD

**Issue by PuruVJ** [sveltejs/kit#1943]
### Describe the bug

I'm using `svelte-kit package` command(which is amazing BTW, kudos to you folks for it 😍). In the component, I have defined createEventDispatcher types as below 👇

```ts
const dispatch =
    createEventDispatcher<{
      start: Window;
      drag: any;
      stop: any;
      mousedown: any;
    }>();

  dispatch('start', {} as Window);
  dispatch('drag');
  dispatch('stop');
  dispatch('mousedown');
```

the `start` event has payload of type `Window` (just for a sample demo, final would be different). So when I run the `svelte-kit package` command, everything works perfectly, the svelte component is generated flaelessly, the `d.ts` is also perfect, with the issue that that the custom types provides for the events are stripped away, and final output has type as `any`

```js
events: {
        start: any;
        drag: any;
        stop: any;
        mousedown: any;
    } & {
        [evt: string]: any;
    };
```

`start` should've had the `Window` type

### Reproduction

Target source code: https://github.com/PuruVJ/svelte-drag/blob/e1e73f2b44abb76b3e730543a8a89b35141fa74f/src/lib/DraggableCore.svelte#L68-L74

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.30 GB / 7.86 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.1.0), Chromium (91.0.864.70)
    Internet Explorer: 11.0.22000.1
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.131 => 1.0.0-next.131
    svelte: ^3.38.3 => 3.38.3
```

### Severity

annoying

**Comment by dummdidumm** [comment]
Is this working when using simple types like `string` or `boolean`? If so, you likely need to add `DOM` to the `lib` list in your `tsconfig.json`

**Comment by PuruVJ** [comment]
@dummdidumm No, not working with string, number, boolean, undefined and null and even Symbol, so I guess the prblem is with any kind of type

**Comment by dummdidumm** [comment]
You need to add `DOM` to the `lib` list in order to get the correct typings, else TS doesn't know what `CustomEvent` is. I updated `create-svelte` accordingly in #1956

**Comment by PuruVJ** [comment]
Thank you!
