### ISSUE TITLE
A way append to `svelte-kit package`'s exports output.

### ISSUE THREAD

**Issue by kwangure** [sveltejs/kit#1944]
### Describe the problem

`svelte-kit package`'s current implementation does not export components [if I've included exports in my `package.json`](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/make_package/index.js#L84).

### Describe the proposed solution

I propose making appending exports to be the default behaviour, since if I don't want `svelte-kit package` to touch my exports I can just do `exports:{ exclude: ["**"] }`.

### Alternatives considered

Scripting to add a custom export after `svelte-kit package` is done running.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Why would you add exports to your package json when you don't want these to be the ones appearing in you package? The current logic is "if the user defined something there, they did that to manually specify it and don't want it changed"

**Comment by kwangure** [comment]
I want the exports I add to the package json *in addition* to the ones that `svelte-kit` generates. Unless I'm missing something, the current logic says "if the user defined some there, do not generate any other exports at all".

**Comment by dummdidumm** [comment]
Yes that's the case currently. What's the use case for additional exports the generated ones don't add?

**Comment by kwangure** [comment]
1) Convenience exports. 
For example, for a long path like `"./components/Input/Password": "./components/Input/Password/index.js"`, I might have a convenience export with `"./Password"`. This allows you to `import Password from "package/Password"` rather than `import Password from "package/components/Input/Password"`.
2) Maintain compatibility after refactor.
For example, if I moved `"./components/Input/Password"` to `"./components/Password"`, in order not to break downstream users, I would include a custom export `"./components/Input/Password"` pointing to the new location.

**Comment by kwangure** [comment]
I still think 'merge' should be the default. As @ًdummdidumm [hinted at above](https://github.com/sveltejs/kit/issues/1944#issuecomment-882070924), I wouldn't put anything in my `package.json` if I expected `svelte-kit package` to replace it.

Are the any use cases for the 'replace' behaviour?

I doubt switching to the 'merge' behaviour breaks any projects/setups.
Given that we're in beta, and that `svelte-kit package` is still pretty young, I think this "breakage" is acceptable. Others here may have other thoughts.

**Comment by ignatiusmb** [comment]
This would be thoroughly explained in the docs later, but the `replace` value there is referring to our current behavior

> "if the user defined something there, they did that to manually specify it and don't want it changed"

We could arguably come up with a better option name than `replace`, but I think it's clear enough (with some docs) that "existing config in package.json will `replace` svelte-kit generated exports"

Also, this shouldn't break anything as the old options are still there. I'll leave this open for some time before I open a PR, in case others have another approach, and in case no one beats me to the PR.
