### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by raulfdm** [sveltejs/kit#1961]
### Describe the bug

I'm not sure if this "bug" (or behavior) has Sveltekit as target since it seems some Vite config.

Anyways, I'm currently trying to bring [`unified`](https://github.com/unifiedjs/unified) to perform in some transformation (md string -> html) client-side, like [`next-mdx-remote`](https://github.com/hashicorp/next-mdx-remote), [`react-markdown`](https://github.com/remarkjs/react-markdown) and other libraries does.

However when I try to import like:

```svelte
<script>
import { unified } from 'unified'
</script>
```

I got the following error:

```
[vite] Error when evaluating SSR module /node_modules/is-buffer/index.js:
ReferenceError: module is not defined
    at /node_modules/is-buffer/index.js:8:1
    at instantiateModule (/Users/raul_personal/development/unified-sveltekit/node_modules/vite/dist/node/chunks/dep-11db14da.js:73323:166)
```

I'm not sure if I need to do some extra config or I'm missing something out.

### Reproduction

1. Access this repo: https://github.com/raulfdm/sveltekit-vite-ssr-error
2. Follow the instructions there

### Logs

```shell
[vite] Error when evaluating SSR module /node_modules/is-buffer/index.js:
ReferenceError: module is not defined
    at /node_modules/is-buffer/index.js:8:1
    at instantiateModule (/Users/raul_personal/development/unified-sveltekit/node_modules/vite/dist/node/chunks/dep-11db14da.js:73323:166)
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 42.99 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.asdf/installs/nodejs/14.16.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.asdf/installs/nodejs/14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 89.0.774.57
    Firefox Developer Edition: 90.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.131 
    svelte: ^3.34.0 => 3.38.3 
```

### Severity

blocking an upgrade

**Comment by raulfdm** [comment]
I've notice there's a specific [open issue](https://github.com/sveltejs/kit/issues/1895) to report this kind of problem to vite via Google forms. I've just done that.

I'm not sure if this issue should remain open but if not, feel free to close

**Comment by benmccann** [comment]
Thanks for reporting. We've been trying to reduce these errors. I added some detail in https://github.com/vitejs/vite/issues/4113 and will close this in favor of that issue
