### ISSUE TITLE
Stores don't work in service-worker.js

### ISSUE THREAD

**Issue by DanielBanobreDopico** [sveltejs/kit#1967]
### Describe the bug

I'm tring to use a Svelte store for share information between service-worker and Svelte modules.
There are not errors at compilation time, but Svelte app don't show service worker data updates.

### Reproduction

1. create src/lib/store.js exporting a writable store.
2. import it from src/service-worker.js and update in regular basis it by setInterval.
3. import it from a component and show {$store} content.

### Logs

```shell
If add a console.log in service-worker.js, it shows store updates.
No releant information.
```

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-2348M CPU @ 2.30GHz
    Memory: 213.19 MB / 3.44 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chromium: 91.0.4472.114
    Firefox: 89.0.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.132 
    svelte: ^3.34.0 => 3.38.3
```

### Severity

annoyance

**Comment by Kapsonfire-DE** [comment]
WebWorkers/ServiceWorkers are in different scopes and dont share data. You have to use postmessage and sync your data on your own.
