### ISSUE TITLE
Allow svelte pages with error statuses

### ISSUE THREAD

**Issue by JulienPradet** [sveltejs/kit#1973]
### Describe the problem

I'm currently trying to build an application with SvelteKit and my goal would be to allow forms to be submitted successfully if javascript is disabled for any reason. But currently it's kind of hard to display the same form with just an error message.

So I've got:

- `route/form-page.svelte` which renders the form.
- If I submit this form incorrectly, then `route/form-page.js` handles the form validation using the `post` method
- If there's an error, I set a key in `request.locals` and then make it available through the `getSession` hook. 
- It then renders back the `route/form-page.svelte` with the session containing the form error. So I do a check in the `load` method of my page, and return `{status: 400}` since the data submitted by the user is wrong. It then renders the `_error.svelte` associated to the page.

However I don't want to render an `_error.svelte`. I'd prefer to render the current svelte page since there's only a few more text messages that appear here and there on my page.

### Describe the proposed solution

Do you think it would make sense to only render the `_error.svelte` component when an actual `error` is thrown?
I feel like it makes sense to have the opportunity to render a page by simply adding an alert instead of rendering a full blown error page.

So when we only have `{status: XXX}` we rely on the `form-page.svelte` and when there's also an error, we fallback on the `_error.svelte`. If that's too much of an edge case, it could only render the `form-page-svelte` if there are `props` in the returned object.

### Alternatives considered

I've got a workaround by moving my `form-page.svelte` in `form-page/index.svelte` and creating a dedicated `__error.svelte` that imports and renders the `form-page/index.svelte`. But that's kind of a lot of boilerplate for an app that have many pages with forms.

### Importance

would make my life easier

### Additional Information

The current behavior seems to be a consequence of this code:

https://github.com/sveltejs/kit/blob/9701eb21b7698226ad287c7ce0f1893ffa6fb972/packages/kit/src/runtime/load.js#L11-L16

If I wasn't clear enough in my explanation I'll try to setup a reproduction repository. So feel free to ask.

**Comment by benmccann** [comment]
Just return 200 if you don't want to treat it like an error
