### ISSUE TITLE
Fetch crashes in SSR

### ISSUE THREAD

**Issue by manen** [sveltejs/kit#1981]
### Describe the bug

I have `/`, a page that automatically fetches the endpoint `/api/categories/2`.
This completely breaks SSR fetch.
Error included in logs

### Reproduction

1. Use @sveltejs/kit@next (1.0.0-next.131 and 1.0.0-next.133 tested)
2. Fetch an endpoint from a page from SSR
3. 'Enjoy'?

### Logs

```shell
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:363:5)
    at onParseError (node:internal/url:536:9)
    at new URL (node:internal/url:612:5)
    at new Request (file:///mnt/dev/hamza/node_modules/@sveltejs/kit/dist/install-fetch.js:1239:16)
    at file:///mnt/dev/hamza/node_modules/@sveltejs/kit/dist/install-fetch.js:1448:19
    at new Promise (<anonymous>)
    at fetch (file:///mnt/dev/hamza/node_modules/@sveltejs/kit/dist/install-fetch.js:1446:9)
```

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 6.33 GB / 15.63 GB
    Container: Yes
    Shell: 3.2.2 - /bin/fish
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 91.1.25.68
    Firefox: 88.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.133 
    svelte: ^3.34.0 => 3.38.3
```

### Severity

can work around it, it'll just be ugly

**Comment by babeard** [comment]
I've been bitten in the past by not using kit's built in fetch within the load function. Hopefully this solves your problem as well.

```diff
-   export async function load() {
+   export async function load({ fetch }) {
```

**Comment by benmccann** [comment]
If you can provide a repository to reproduce that would help a lot

**Comment by StephenGunn** [comment]
> I've been bitten in the past by not using kit's built in fetch within the load function. Hopefully this solves your problem as well.
> 
> ```diff
> -   export async function load() {
> +   export async function load({ fetch }) {
> ```

Can confirm that this fixed this problem for me.

**Comment by manen** [comment]
> I've been bitten in the past by not using kit's built in fetch within the load function. Hopefully this solves your problem as well.

It does, thanks, but isn't there an alternate method? It's pretty ugly to pass `fetch` as an argument to everything that needs to fetch something.

**Comment by benmccann** [comment]
SvelteKit's `fetch` is a special one that copies the response in order to hydrate the page. There's no way to make it globally available

**Comment by manen** [comment]
Okay :(
