### ISSUE TITLE
`$app/env`: "is" names for environment booleans

### ISSUE THREAD

**Issue by darrylyeo** [sveltejs/kit#1987]
Currently, the variables exposed from `$app/env` are as follows:

    import { amp, browser, dev, mode, prerendering } from '$app/env';

To avoid ambiguity, I think it would be clearer to prepend "is" to the boolean variables:

    import { isAmp, isBrowser, isDev, mode, isPrerendering } from '$app/env';

### Importance

nice to have

**Comment by benmccann** [comment]
VS Code should show you that they're booleans, so I'm not sure that this would be worth changing

**Comment by darrylyeo** [comment]
I personally think `if(isBrowser)` reads much better than `if(browser)`, and the less I have to mouse over things in an IDE to figure stuff out, the better.
