### ISSUE TITLE
TypeScript setup

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#200]
I'm leaving some notes here for when we eventually take a stab at adding back TypeScript.

**Issues we encountered**

We had originally tried getting `@rollup/plugin-typescript` working, but encountered a couple issues:
* https://github.com/rollup/plugins/issues/287 - this issue has the most votes of any Rollup bug in either the core repo or plugin repo
* https://github.com/rollup/plugins/issues/247 - this issue is closed because no one had agreed to work on it, but is still present

We instead setup `rollup-plugin-typescript2`, which was really easy to get setup. However, we eventually did hit one issue:
* https://github.com/ezolenko/rollup-plugin-typescript2/issues/254 - errors are swallowed and you need to run `tsc` manually to get the real error message. I suspect this has something to do with our usage of `pnpm` and corresponding directory structure (e.g. some libraries are present in `../../node_modules` if you're in a subpackage).

`@rollup/plugin-typescript` is super finicky and really hard to get working. `rollup-plugin-typescript2` was really easy to setup though it seems not to support `pnpm` yet and swallows error messages as a result. Normally I would think the best place to focus my efforts would be to fix the one issue in `rollup-plugin-typescript2` and then eventually re-enabled it. However, it turns out that `rollup-plugin-typescript2` does not have any tests! So in the long-run perhaps it's better to put more work into `@rollup/plugin-typescript` even though it might be further from working really well

The other issue we were hitting was that the project wasn't being compiled on the CI, so we had a few PRs that broke things. That seems easily avoidable and basically fixed at this point

**Suggested solution**

I wonder if a lot of our issues may be avoided by just calling `tsc` directly and removing Rollup from our build process given that the Rollup TypeScript plugins are so finicky. It certainly seems like it would avoid an extra layer of potential complication. TypeScript doesn't yet support npm's new `exports` map, which means we'll have to continue outputting files to the subpackage root directory instead of using something like a `dist/` directory (https://github.com/microsoft/TypeScript/issues/33079)

**Comment by Marr11317** [comment]
Out of curiosity, I just tried `@rollup/plugin-typescript` and it works fine. 

No configuration necessary. See [this branch](https://github.com/Marr11317/kit/tree/typescript-files) and particularly [the last commit](https://github.com/Marr11317/kit/tree/typescript-files). 

This commits only sets up typescript for the `kit` package.
