### ISSUE TITLE
regression: can't prerender unicode paths

### ISSUE THREAD

**Issue by datio** [sveltejs/kit#2000]
### Describe the bug

Greek character paths can't properly resolve.

There's a [regression](https://discord.com/channels/457912077277855764/819723698415599626/868119360793886720) from https://github.com/sveltejs/kit/pull/1062 when a unicode path is `visit`'ed because of the following change:

https://github.com/sveltejs/kit/blame/2a1e9795ad9773e04669a7b9d0234caa0b688ade/packages/kit/src/core/adapt/prerender.js#L227

If it's changed, say, to:
```javascript
await visit(decodeURI(path), parsed.pathname.replace(config.kit.paths.base, ''));
```
It builds correctly.

### Reproduction

Same as: https://github.com/sveltejs/sapper/issues/1174

### System Info

```shell
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 14.31 GB / 31.33 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Browsers:
    Firefox: 90.0
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.35 => 1.0.0-next.35 
    @sveltejs/kit: ^1.0.0-next.137 => 1.0.0-next.137 
    svelte: ^3.34.0 => 3.40.1 
```
```


### Severity

blocking all usage of SvelteKit

### Additional Information

_No response_

**Comment by benmccann** [comment]
@datio your solution didn't work for me. See here for a failing example: https://github.com/sveltejs/kit/commit/765527ac0cdd0033c56b04860f261341d29a6f46

If you're able to figure out what's wrong and send a fix, I'd be happy to merge it

**Comment by datio** [comment]
@benmccann yes, indeed.

Maybe a solution is to detect the 404 error and simply ignore it, which does the trick: https://github.com/datio/kit/commit/662309fb4ca06d4138e6302ef20e213fa4c570a1

The tests fail though so I haven't sent a pull request..

**Comment by datio** [comment]
A better approach might be to add: `request.path = decodeURI(request.path);` at the start of the resolve function [here](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/index.js#L46).

**Comment by benmccann** [comment]
That still fails for me
