### ISSUE TITLE
dynamic imports not working from cdn url

### ISSUE THREAD

**Issue by tsukhu** [sveltejs/kit#2002]
### Describe the bug

I am trying to use sveltekit for dynamic imports which are from a CDN

Please see the REPL (Svelte only version)
https://svelte.dev/repl/0bb24039df0e4a9abf35dd7b87f3976a?version=3.40.2 

This loads the qrcode component `svelte-qrcode` using `onMount` and works fine with the `await then syntax`

If I use the same code and implement it in sveltekit while the library loads but nothing is displayed

Is there something I need to do additionally in `sveltekit` to get this working ?

### Reproduction

- `git clone https://github.com/tsukhu/sveltekit-dynamic-import.git`
- `npm i`
- `npm run dev`
- Browse `http://localhost:3000/`

We see there is no output

- The same code works in Svelte REPL https://svelte.dev/repl/0bb24039df0e4a9abf35dd7b87f3976a?version=3.40.2  

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) ia32 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz 
    Memory: 5.82 GB / 11.92 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files (x86)\nodejs\node.EXE 
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.13 - C:\Program Files (x86)\nodejs\npm.CMD   
  Browsers:
    Chrome: 91.0.4472.164
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.71)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.137 
    svelte: ^3.34.0 => 3.40.2
```

### Severity

annoyance

**Comment by GrygrFlzr** [comment]
This is a usage question, not an issue with SvelteKit. You need a bundler plugin like [rollup-plugin-url-resolve](https://github.com/mjackson/rollup-plugin-url-resolve) to resolve URL imports like that. It works on the Svelte REPL because there is no package manager / resolution, everything is just URLs. I'd recommend using it as a node dependency normally though.

**Comment by tsukhu** [comment]
@GrygrFlzr Thank you for your time and quick response. I am trying to resolve this based on the solution you provided. Also taking this forward on discord . Is there a sample I can refer to that covers this use case
