### ISSUE TITLE
Multiple title tags in markup

### ISSUE THREAD

**Issue by disbelief** [sveltejs/kit#2009]
### Describe the bug

I've noticed that when using `<svelte:head>` to define a `<title>` for various pages in my site, the markup produced ends up with _two_ `<title>` tags in it.  Both tags contain the same text, so the `svelte:head` does appear to be updating them to the correct value, however I've been told that multiple title tags can confuse some search engines and social share link preview generators.

### Reproduction

1. Start with standard SvelteKit application
2. Include a default `<title>` tag in `app.html`
3. Use `<svelte:head>` to define custom title in each route svelte file.
4. Open any page of the app in a browser and view source.
5. There will be two `<title>` tags in the `<head>` of the document containing the custom title from the route

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 172.91 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Brave Browser: 92.1.27.108
    Chrome: 91.0.4472.164
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.15 => 1.0.0-next.15 
    @sveltejs/kit: ^1.0.0-next.115 => 1.0.0-next.115 
    svelte: ^3.34.0 => 3.38.2
```

### Severity

annoyance

### Additional Information

While it doesn't affect page behaviour (as far as I can tell), it is [unexpected and incorrect](https://html.spec.whatwg.org/#the-title-element) to have multiple `<title>` tags in a single HTML document. This may confuse some renderers, search engines, and social preview generators.

**Comment by disbelief** [comment]
This appears to actually happen to _any_ tags I put in the `<svelte:head>` section.

It's likely I'm expecting too much of `<svelte:head>` based on prior experience with React Helmet, in which case this could be more of a feature request. With React Helmet, the special head component can be rendered multiple times on a page and it will merge and de-dupe tags. Eg. a wrapper component may set the page title, and then a child component may override it.

**Comment by Conduitry** [comment]
`<title>` tags in multiple `<svelte:head>`s should already be de-duping - there's special handling for that in Svelte's SSR output. But anything in `app.html` is outside of this - so if you want a default title that can be overridden, put it in `<svelte:head>` in `__layout.svelte`, not in `app.html`.

There might be an issue open on the Svelte repo somewhere about merging other types of tags in `<svelte:head>`, but I don't think it's entirely clear for `<link>` and `<meta>` ought to be handled. So, for now, `<title>` is replaced by lower-level components, but other tags are all present.

**Comment by disbelief** [comment]
I'd argue it's incorrect behavior to both overwrite the text in the original `<title>` tag defined in `app.html` _and_ insert a separate `<title>` tag.

Regarding other tags, in my opinion `<link rel="canonical" />` and things like meta description and OG tags likely should be de-duped.

**Comment by disbelief** [comment]
Also, I just tried your suggestion of moving the default `<title>` tag into `routes/__layout.svelte` and it seems to override any `<title>` specified in a specific route.

```svelte
// routes/__layout.svelte
<svelte:head>
  <title>This is the default title</title>
</svelte:head>

<slot></slot>
```

```svelte
// routes/[slug].svelte
<svelte:head>
  <title>Custom route title</title>
</svelte:head>
```
Results in:
```html
<title>This is the default title</title>
```

**Comment by fuuuzz** [comment]
Better late than never 😅 

Just came across the same issue, I managed to get rid of it by moving `%sveltekit.head%` at the top of `<head>` tag in `app.html` file

In my case, i had default `meta` in `app.html`

**Before**
```
<!doctype html>
<html
  lang="fr"
  class="scroll-behavior-smooth">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta
      name="format-detection"
      content="telephone=no,date=no,address=no,email=no,url=no" />
    <meta
      name="theme-color"
      content="#3917B3" />

    %sveltekit.head%
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>

```

**After**
```
<!doctype html>
<html
  lang="fr"
  class="scroll-behavior-smooth">
  <head>
    %sveltekit.head%

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta
      name="format-detection"
      content="telephone=no,date=no,address=no,email=no,url=no" />
    <meta
      name="theme-color"
      content="#3917B3" />
  </head>
  <body data-sveltekit-preload-data="hover">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>

```

Cheers! 🤙
