### ISSUE TITLE
Wrong path resolution to components into `$lib` at dev server start

### ISSUE THREAD

**Issue by alexbruno** [sveltejs/kit#2015]
### Describe the bug

Wrong path resolution to components into `$lib` at dev server start, throwing an error 500.
While in development after server start it works, but at server start with `npm run dev` I have an error about path resolutions.
The error message shows that relative path to the component is duplicated.

### Reproduction

Check this:

![image](https://user-images.githubusercontent.com/2638399/126999199-0aa87ccb-21ff-4be0-9914-0cdd57687a9c.png)

![image](https://user-images.githubusercontent.com/2638399/126999467-6fcc7fc8-9eb8-4d7b-b173-52f6ff0154c1.png)

Page renders:

500
ENOENT: no such file or directory, open '/home/alxbr/github/media-centre-network/tempo-na-cidade/previsao-do-tempo/**src/lib/components/base/src/lib/components/base**/SiteMain.svelte'
Error: ENOENT: no such file or directory, open '/home/alxbr/github/media-centre-network/tempo-na-cidade/previsao-do-tempo/**src/lib/components/base/src/lib/components/base**/SiteMain.svelte'

### Logs

```shell
[vite] page reload src/routes/index.svelte (x2)
ENOENT: no such file or directory, open '/home/alxbr/github/media-centre-network/tempo-na-cidade/previsao-do-tempo/src/lib/components/base/src/lib/components/base/SiteMain.svelte'
Error: ENOENT: no such file or directory, open '/home/alxbr/github/media-centre-network/tempo-na-cidade/previsao-do-tempo/src/lib/components/base/src/lib/components/base/SiteMain.svelte'
ENOENT: no such file or directory, open '/home/alxbr/github/media-centre-network/tempo-na-cidade/previsao-do-tempo/src/lib/components/base/src/lib/components/base/SiteMain.svelte'
Error: ENOENT: no such file or directory, open '/home/alxbr/github/media-centre-network/tempo-na-cidade/previsao-do-tempo/src/lib/components/base/src/lib/components/base/SiteMain.svelte'
```

### System Info

```shell
npx: installed 1 in 0.891s

  System:
    OS: Linux 4.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 21.00 GB / 24.94 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.1 - ~/.nvm/versions/node/v14.17.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.1/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.1/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.0 => 1.0.0-next.0 
    @sveltejs/kit: next => 1.0.0-next.137 
    svelte: ^3.40.2 => 3.40.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I'm using it to develop a private project, so I can't share a link to a repo.
But, if needed, I can try to create a new repo just to reproduce this error.

**Comment by Conduitry** [comment]
This is presumably the same as #2001. Try downgrading to Svelte 3.40.1.

**Comment by Conduitry** [comment]
https://github.com/sveltejs/svelte/pull/6572 should fix it, but we're considering holding off on that until a new release of Vite which should be happening tomorrow and which may also fix the issue. This does seem to be Svelte surfacing a bug in Vite rather than a bug in Svelte.

In either case, closing this issue, as it is indeed the same as #2001.
