### ISSUE TITLE
docs: confusing "Fallthrough routes" means

### ISSUE THREAD

**Issue by dbwhddn10** [sveltejs/kit#2016]
### Describe the problem

I confused "Fallthrough routes" title In svelteKit docs.

### Describe the proposed solution

I think better title is "route priority"

### Alternatives considered

title include "priority" 

### Importance

nice to have

**Comment by benmccann** [comment]
Thanks for sharing. Unfortunately I think it would be hard to write the docs in a way that every non-native speaker from various countries will understand. It makes sense to me as written eventhough I was not the one to write it, so I'm not sure it needs to be changed
