### ISSUE TITLE
svelte-kit should choose new port on EADDRINUSE like sirv

### ISSUE THREAD

**Issue by elikoga** [sveltejs/kit#2020]
### Describe the problem

I was surprised when I tried to set up the skeleton project and it failed because port 3000 ist already bound.

When I went to check the webserver it was svelte-kit, not sirv, so I have to look up how to change the port.

This shouldn't be that complicated, so I think this should be changed.

```
❯ npm run dev

> ~TODO~@0.0.1 dev /home/coafin/Weidmueller/jws-toolkit
> svelte-kit dev


  SvelteKit v1.0.0-next.137

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network



events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ~TODO~@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ~TODO~@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coafin/.npm/_logs/2021-07-27T06_59_36_177Z-debug.log
```

### Describe the proposed solution

I would like to see the post chosen randomly if the default port is already bound.

### Alternatives considered

Change the port after looking up how :

- run `svelte-kit --help
- fail because PATH
- run `npx svelte-kit --help`
- read
- run `npx svelte-kit dev --help`
- read
- change `svelte-kit dev` to `svelte-kit dev --port <something>` in package.json

### Importance

nice to have

### Additional Information

Low priority and I hope to provide a pull request for a project that I like if I find the time

**Comment by elikoga** [comment]
This should at least be the case with `svelte-kit dev` without a specified port.

**Comment by Conduitry** [comment]
The current behavior is intended when this came up a few months ago in internal maintainer discussions. Picking a different port when the one you specified is occupied messes with one's muscle memory and browser history autocomplete. The error message could probably be improved, though, and tell people there about the `--port` option so they don't need to go looking for it.

**Comment by rmunn** [comment]
Or the default behavior could be to error out on EADDRINUSE as it does now, but if `--port=auto` is specified then it picks a port, starting at 3000 and counting up. Or if it's desired to be able to specify the starting port, perhaps a syntax like `port=3000+` could work. A trailing `+` means "start at this port and go up until an open port is found", perhaps limiting it to 100 attempts to it doesn't keep trying forever. With no trailing `+` then it would just try one port and quit, as with the current behavior.

Thoughts?

**Comment by elikoga** [comment]
I could probably implement https://github.com/sveltejs/kit/issues/2020#issuecomment-887324239 short term with https://github.com/sveltejs/kit/issues/2020#issuecomment-887470550 being a better solution that has to be worked out somewhere

**Comment by elikoga** [comment]
I think with https://github.com/sveltejs/kit/issues/2020#issuecomment-887470550 we should look at other projects and replicate the one people are most used to

**Comment by justingolden21** [comment]
Agree the error message and handling should be improved, if this behavior is to continue.

If you want the behavior or not is up to you, I simply think *if there is* an error, it should be caught and a nicer and obvious message should be shown to the end user to save potential hours of debugging.

Idea for an error message: "Unable to host to port 3000: port is currently in use elsewhere" something short, sweet, and obvious.

**Comment by Karlinator** [comment]
I generally like the error message proposed above, but with one addition: "Use `--port=XXXX` to host on a different port". The solution should be presented in the error.

Otherwise I'm also a fan of the behaviour in Create React App. It pauses, gives you a helpful message, and prompts you whether to abort or continue on another port, with 3001 as default. Minimal time spent by the user but doesn't just host on a different port without telling you.

**Comment by Karlinator** [comment]
@elikoga I'm slightly confused as to how you got this error message in the first place. I looked in the CLI file and found a function that checks if the port is occupied and prints a nice error message. Sure enough, when trying to replicate I get:
```
> npm run dev

> ~TODO~@0.0.1 dev
> svelte-kit dev

Port 3000 is occupied
Terminate process 7879 or specify a different port with --port
```
This check happens before printing the SvelteKit version. This appears to be either a bug causing the initial check to incorrectly state the port is open or a case where the port was bound by something else between the check and actually binding the port.

**Comment by elikoga** [comment]
I'm not sure if this helps but I'm on kit-1.0.0-next.137

**Comment by Karlinator** [comment]
The functionality itself was added all the way back in 1.0.0-next.68. I can't reproduce in 137 either.

Is the port actually used by some other program before `npm run dev`? And it works if you start it on a different port?

**Comment by elikoga** [comment]
I just checked that

- another process is bound to port 3000 by issuing `curl localhost:3000`
- running `npm run dev -- --port 3002` works

**Comment by Karlinator** [comment]
Huh, that implies the port checking fails somehow.

What platform are you on? Any other things about your environment?

**Comment by elikoga** [comment]
I'm using NixOS which has loads of implications but nothing major, it's just a Linux Distribution

**Comment by elikoga** [comment]
Accidentally closed

**Comment by Karlinator** [comment]
I looked up the source for the port check (https://github.com/Rich-Harris/port-authority) and it apparently does `lsof -i :${port} -sTCP:LISTEN -Fp`. I just tested on a Windows machine and it doesn't work there either. Does NixOS by any chance not have `lsof`?

I'll be opening a PR in a bit I think to use `ports.check()`, which should be cross platform.

**Comment by elikoga** [comment]
```
❯ lsof
The program 'lsof' is not in your PATH. It is provided by several packages.
You can make it available in an ephemeral shell by typing one of the following:
  nix-shell -p busybox
  nix-shell -p lsof
```

**Comment by elikoga** [comment]
https://www.npmjs.com/package/@ronomon/opened

This look like a better alternative to lsof?

**Comment by Karlinator** [comment]
So Kit is using a package called `port-authority` for this, and it uses lsof in order to get the process number that is using the port.

It also has a `check` method which simply tries to listen to a port and returns the result. I've tried to use that, but it's returning `true` for me every time for some reason. My proposal (if I can get it to work) is to use check to see if the port is in use and then try `blame` to get the process id. If `blame` doesn't work we print a more generic message.

**Comment by Karlinator** [comment]
Note: there is still the option of using `ports.find()`, which starts at the specified port and counts upwards until it finds a free one. I am personally in favour of incorporating this as the default in a "choose a different port" prompt (like in Create React App), but I figured I'd start with fixing the `lsof` dependency.

**Comment by dummdidumm** [comment]
In the next SvelteKit release you'll be able to use https://vitejs.dev/config/#server-strictport to automatically find another path.

```js
// svelte.config.js
export default {
  kit: {
    // ..
    vite: {
      server: { strictPort: false }
    }
}
```
