### ISSUE TITLE
Should allow apps that are in subdirectories

### ISSUE THREAD

**Issue by maximedupre** [sveltejs/kit#2022]
### Describe the problem

We should be able to run `svelte-kit dev` from the root level and have the app in a subdirectory. E.g. `/package.json` and `/my-app/src`

This assumes that at a minimum `package.json` is at the root level so that packages are installed in the root `node_modules` and that you can run npm scripts when the root dir is your cwd.

The [`kit.paths.base`](https://kit.svelte.dev/docs#configuration-paths) and the [`kit.vite.root`](https://vitejs.dev/config/#root) configurations do not accomplish this per my testing.

### Describe the proposed solution

There should be a cli option or `svelte.config.js` param that would allow apps in subdirectories.

### Alternatives considered

The alternative is: 

- `cd`ing in the subdirectory when you need to run commands
- having 2 `node_modules`/`package.json` in your project (1 at root level and 1 in the subdir)

### Importance

Would make my life easier

### Additional Information

The context of this request is when you just want to supplement your current project with a svelte component.

Let's say I have an electron app and would like a svelte component to reside in a subdir at the root of the project.

**Comment by benmccann** [comment]
you could do it with `pnpm`. that's how this repo is setup

**Comment by maximedupre** [comment]
> you could do it with `pnpm`. that's how this repo is setup

Thanks for the suggestion. If I get too annoyed with constantly doing the alternative steps I mentioned in my OP and if svelte kit has not implemented this feature, I'll definitely give it a try.

For now I'll just wait.

I do think it should be a built-in feature as it seems pretty basic to me.

**Comment by benmccann** [comment]
You could also set all the `files` options: https://kit.svelte.dev/docs#configuration-files
