### ISSUE TITLE
Why I need to specify the full path of node_modules

### ISSUE THREAD

**Issue by uc-anr** [sveltejs/kit#2032]
### Describe the bug

Import from node_modules needs to specify full path.

![image](https://user-images.githubusercontent.com/55784797/127453075-ead5b183-cb15-4d72-a44d-4be297ce0749.png)

![image](https://user-images.githubusercontent.com/55784797/127453173-6c361009-3c1a-4bbd-aea3-e6096770ae18.png)

### Reproduction

Coming error on local and not on server.

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 3.38 GB / 11.89 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.55)
    Internet Explorer: 11.0.19041.1
```

### Severity

blocking an upgrade

**Comment by JeanJPNM** [comment]
Your issue seems to be because you are making a default import of a commonjs module, but these don't work because they don't have an export named `default`, try using this:
```js
import * as QrCode from "svelte-qrcode"
```
