### ISSUE TITLE
[Docs] %svelte.body% and %svelte.head% are undocumented

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#2035]
### Describe the problem

I think `%svelte.body%` and `config.kit.target` is redundant.

### Describe the proposed solution

I suggest to automatically detect %svelte.body% placeholder in app.html (resp. in defined template html file) and remove this option from config. Also it should be fine to create docs about svelte html template placeholders.

### Alternatives considered

Removing placeholder, and let user set target in config.

### Importance

nice to have

**Comment by Conduitry** [comment]
I don't think we want SvelteKit to be responsible for parsing the template file and coming up with a selector that can be used to match where `%svelte.body%` was placed. That sounds like a nightmare.

**Comment by Mlocik97** [comment]
Than what does `%svelte.body%` does? Or why it even exist, when we anyway need target config.

**Comment by Mlocik97** [comment]
ok, I now see how it works... now I understand why we need both, (at least now, with actual way how kit use it), but still I think it would be nice at least document those placeholders.

**Comment by Mlocik97** [comment]
I just manually deleted that 

https://github.com/sveltejs/kit/blob/883d4b857ffd6d631ee1a0e1a63152b8ccb7ba3d/packages/kit/src/core/config/index.js#L99-L114
and
https://github.com/sveltejs/kit/blob/883d4b857ffd6d631ee1a0e1a63152b8ccb7ba3d/packages/kit/src/core/config/index.js#L122
 from node_modules/@sveltejs/kit/dist/cli.js and removed %svelte.body% from my app.html and it's work fine. So that placeholder seems really totally useless.

**Comment by Mlocik97** [comment]
And when I think about it, we would be able to totally remove app.html template file (resp. hide from user)... I know he would sometimes need to set some tags in head, but it's already possible with `<svelte:head>` resp. in `__layout.svelte` it would be same as in `app.html`... ?

**Comment by FractalHQ** [comment]
Interesting points about redundancy.  I personally appreciate the template tags being there, however. They make it very clear what to expect when building, and can be especially illuminating for newcomers.  I also like having the app.html and I use it often.  Removing it completely would make it feel even more black-boxy- I was already taken-aback by the removal of the App.svelte entry-point (although I don't particularly miss it).  Though admittedly, I haven't thought about it as long as you have, and I'm likely biased as a long-time Svelte user.

**Comment by UltraCakeBakery** [comment]
Removing the app.html will make it difficult for SPA mode users like me to have a page title, meta tags and some basic content shown before the page actually hydrates. On mobile phones this can easily take up more than 2 seconds for the svelte skeleton project depending on if you have power saving mode on, data transfer speeds and more. 

A possible workaround could be that svelte-kit takes all meta tags from `<svelte:head>` inside the root `__layout.svelte`, prefills the `index.html` with those tags and overwrites them once the client side hydrates.

**Comment by UltraCakeBakery** [comment]
> It would probably make possible to remove whole app.html (template html file) from svelte.

I would like this to be optional. I need the app.html too to work around svelte for some magical reason not having a the ability to add attributes to `<html>` through something like `<svelte:html>` "yet". 

In `hooks` I now replace `%html.language%` (`<html lang="%html.language%">`) with the correct language attribute.

**Comment by Mlocik97** [comment]
Oh, yes, I agree about html lang, well, there is RFC https://github.com/sveltejs/rfcs/pull/55 and I was already thinking about it a long time ago. But with:

```js
.replace('<html>', () => `<html lang="${lang}">`);
```

would solve that. , we would just need to pass content of `<svelte:html lang="en" />` (lang attribute) to lang variable. (As is proposed).

For SPA I agree, it would require some work to have ability to prerender `__layout.svelte` without components within it. But if this would be done, I think, it would be 100% possible to get rid of `app.html`, that would made some advantages, mainly because when You want to change some content of `app.html` dynamically, you now need to use raw js dom operations instead svelte way. But that's just one idea... This issue is not about it. It's more about those placeholders in `app.html`

**Comment by benmccann** [comment]
I believe `%svelte.body%` is for the server and `config.kit.target` is for the client. They're different because the server does a string replace and the client does a DOM navigation

**Comment by Mlocik97** [comment]
oh, thanks for explanation, I will test it and see what comes SSRed and what is changed on client-side by DOM manipulation.

**Comment by Mlocik97** [comment]
Oh I see, when I set hydratable to false, it's more visible how SSR use those placeholders. Now I understand why we need them. So practicaly target is for client-side, and those placeholders for server-side (SSR), and why it worked for me without those placeholers is because even when my content was unable to parse on server-side, on client-side it used target from config and put content to DOM, so I still was able to see content without those placeholders, but it was only client-side rendered. Practically without placeholders, SSR is impossible. Now I understand and agree we need them. But it would still be good to create documentation for them.

**Comment by Rich-Harris** [comment]
Closing this in favour of #4748. (Re `config.kit.target` — that option was removed, the markup is now self-hydrating)
