### ISSUE TITLE
adapter-node package is different than repository

### ISSUE THREAD

**Issue by smj-edison** [sveltejs/kit#2039]
### Describe the bug

When installing @sveltejs/adapter-node the package is not synchronized with what the repository contains.

### Reproduction

1. npm init -y
2. npm install @sveltejs/adapter-node
3. cat node_modules/@sveltejs/adapter-node/index.js

The contents of `node_modules/@sveltejs/adapter-node/index.js` do not match up with [kit/packages/adapter-node/index.js](https://github.com/sveltejs/kit/blob/master/packages/adapter-node/index.js).

### System Info

```shell
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 2.47 GB / 15.53 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.1 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Brave Browser: 92.1.27.108
    Chrome: 92.0.4515.107
    Firefox: 90.0
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.0 => 1.0.0-next.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
You need to install `@next`. If you're installing `@latest` (the default if you don't tell npm what to install), you are getting the very first version that was published.
