### ISSUE TITLE
Query params are not available within load function with adapter-vercel when prerendering

### ISSUE THREAD

**Issue by tionkje** [sveltejs/kit#2045]
### Describe the bug

Much like #631 the query params are not filled in when prerender is set to true in the module context.
It does work when using dev and preview. But does not work when deployed on vercel.

### Reproduction

I created a skeleton app and pushed to github
https://github.com/tionkje/svelte-kit-vercel-query-issue?ts=2
and also deployed on vercel
https://svelte-kit-vercel-query-issue-ie19yxpv0-tionkje.vercel.app/?name=value
Where null is on the page it should say `value`

### System Info

```shell
System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1.30 GB / 15.23 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Chromium: 92.0.4515.107
    Firefox: 90.0
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.139
    svelte: ^3.34.0 => 3.41.0
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
See https://github.com/sveltejs/kit/issues/669#issuecomment-848988844
