### ISSUE TITLE
Let automatically set name in package.json based on name of folder.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#2050]
### Describe the problem

When I use `npm init -y` it automatically set name in package.json to same as name of folder. It would be nice to have same thing with `npm init svelte@next`.

### Describe the proposed solution

Let say I'm in folder `foo`.

if I use command `npm init svelte@next` or resp. `npm init svelte@next .`, it should automatically set name to `foo`.
if I use command `npm init svelte@next bar`, it should automatically set name to `bar`,

it should also convert all capitals letter and remove invalid characters (or throw error like npm init -y), that doesn't use pattern:

```
"^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$"
```

### Alternatives considered

-

### Importance

nice to have

**Comment by supercoww** [comment]
Can I work on this?
