### ISSUE TITLE
Any RequestHandler runs twice

### ISSUE THREAD

**Issue by Webbmekanikern** [sveltejs/kit#2052]
### Describe the bug

Every RequestHandler in every route seems to run twice, regardless of the HTTP method (tested `GET`, `POST` and `PUT`). This causes a lot of problems especially for `POST` requests, as entries get inserted twice in our database.

### Reproduction

1. Set up a new route file (e.g. `./src/routes/test.js`).
2. Add a RequestHandler (example below).
3. Run `npm run dev`.
4. Request the route via e.g. Postman.

```JavaScript
/**
 * @type {import('@sveltejs/kit').RequestHandler}
 */
export async function get({ locals, query }) {
    console.log('Received request');
	
    return {
        body: {
            foo: 'bar'
        }
    };
}
	
```

### Logs

```shell
> svelte-kit dev


  SvelteKit v1.0.0-next.139

  local:   http://localhost:3000
  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network

Received request
Received request
```

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 196.66 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    npm: 7.16.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Safari: 14.0.3
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.26 => 1.0.0-next.35 
    @sveltejs/kit: next => 1.0.0-next.139 
    svelte: ^3.38.2 => 3.41.0
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment]
I just tested and can't reproduce this. Can you provide a repo that reproduces this?

Perhaps you have a hook that is calling `resolve` twice in `handle`?

**Comment by Webbmekanikern** [comment]
@benmccann - That did indeed seem to be the problem, which is weird as both calls to `resolve()` have a return statement.

Removing one of them did however solve the issue - thanks!
