### ISSUE TITLE
custom headers for static files - find and document best practice

### ISSUE THREAD

**Issue by helbling** [sveltejs/kit#2060]
### Describe the problem

The sapper migration guide and documentation in general is missing information on a best-practice for how to set custom headers for static files.

In sapper, I was setting `access-control-allow-origin: *` and a custom `content-type`. For that I configured `src/server.js` like this:
```
    sirv('static', {
        dev,
        setHeaders: (res, pathname, stats) => {
            if (pathname.match(/^\/images\//)) {
                res.setHeader('Access-Control-Allow-Origin', '*');
            }
           // ..
        }
    }),
```

As far as I know, there is currently no way to configure sirv in adapter-node. 
And `src/hooks.js` only works for pages and endpoints.

My solution/workaround is currently this:
Route the static requests you wish to override through an endpoint. The static files need to be moved somewhere (i.e. from /images to /_images). The endpoint has some method to get the file. The requests get their headers through src/hooks.js. (alternatively they could also be set inside the endpoint).
The following example demonstrates the concept:

`src/routes/images/[image].js`:

```
import { promises } from 'fs'; 
    
export async function get({ params }) {
    const { image } = params;
    const strippedImageName = image.replace(/[^a-zA-Z0-9._-]/, ''); // better be save to avoid data leaks
    try {
        return {
            body: await promises.readFile(`static/_images/${strippedImageName}`),
        };
    } catch {
        return {
            status: 404
        }; 
    }
}
```

`src/hooks.js`:
```
export async function handle({ request, resolve }) {
    const response = await resolve(request);
    if (request.path.match(/^\/images\//)) {
        const headers = {
            ...response.headers,
            'access-control-allow-origin': '*',
        };
        const match = request.path.match(/\.([^.]+)$/);
        const types = {
            png: 'image/png',
            svg: 'image/svg+xml',
            jpg: 'image/jpeg',
        };
        if (match) {
            const type = types[match[1]];
            if (type)
                headers['content-type'] = type;
        }
        return {
            ...response,
            headers
        };
    } 
    return response;
}
```

The content-type logic here is quite ugly especially as it is rebuilding something that works for direct static files out-of-the box. I hope there is a more elegant and general solution to this. Maybe that is possible with a subrequest to `/_images/..`.

### Describe the proposed solution

- agree on a best-practice for this
- document that solution in documentation and link to it from the migration guide

### Alternatives considered

Do nothing and let users find out for themselves what to do if they want custom headers for static files.

### Importance

nice to have

### Additional Information

Note 1:
I mentioned the issue in https://github.com/sveltejs/kit/issues/809 already, but that one got closed as it's main point got fixed.

Note 2:
`Access-Control-Allow-Origin: *` is set by default in development mode `npm run dev` but not in production builds.

**Comment by benmccann** [comment]
I suspect it might depend how you include your images. Can you check if `handle` is called if you `import` the image? https://kit.svelte.dev/faq#assets

**Comment by helbling** [comment]
Good idea, but sadly `handle` is not called this way either.

Here's a reproduction project with two images, one from static and one using `import` from assets. The `handle` functions logs all requests with `console.log` and sets `x-custom-header: potato` as an additional header.
https://github.com/helbling/sveltekit_static_headers

Handle is only called for the page itself, not for any of the images.

**Comment by Rich-Harris** [comment]
This could be achieved with a [custom server](https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server), with the caveat that static asset handling isn't separated from everything else, so the `Access-Control-Allow-Origin` header would apply to _all_ responses.

If that's not granular enough then we'd need to come up with a different API for `adapter-node` (whatever solution we came up with would be specific to that adapter — since in general we don't have control over how static assets are served by platforms, it can't be framework-level configuration).

**Comment by helbling** [comment]
Wow, this is a very nice and flexible solution, thank you very much!

I can actually do the exact same thing I did with sapper by calling 
```
app.use(express.static(
	'static',
	{
		setHeaders: (res, pathname, stats) => {
			// insert code here
		}
	}
));
```
before
```
app.use(handler);
```

See the following demo:
https://github.com/helbling/sveltekit_custom_server_test

```
npm i
npm run build
node my-server.js
```
`$ curl -sI http://localhost:3000/favicon.png` sets `Access-Control-Allow-Origin: *`
whereas
`$ curl -sI http://localhost:3000/robots.txt` doesn't


I think the only thing left to do is to set a link to the custom server documentation [1] in the migration guide [2]
[1] https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server
[2] https://kit.svelte.dev/docs/migrating#project-files-src-server-js
