### ISSUE TITLE
Large HTML still an issue - Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by DJBMASTER** [sveltejs/kit#2061]
### Describe the bug

When creating a large HTML in svelte components - past a certain point the error message **Maximum call stack size exceeded** appears. There is a workaround by using **{@html hugeHtml}** -  but it is far from ideal and impacts the development experience.

The issue is still open on the main svelte repo: https://github.com/sveltejs/svelte/issues/4694

Attempts to use the patch referenced in the above issue (https://gist.github.com/NetOperatorWibby/8515baa503ccc7b60189c6871c2c6096)
did not resolve the problem.

![image](https://user-images.githubusercontent.com/2739322/127775456-7b1cebfc-92e1-4cae-95b6-6c3538a7fbde.png)

### Reproduction

Remove the variable/script and use the HTML directly in this REPL: https://svelte.dev/repl/1ab32c5a3c2c426e973512cfc8da023c?version=3.20.1

![image](https://user-images.githubusercontent.com/2739322/127775552-7c912122-5e34-4de8-9789-d4c3270de363.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 14.04 GB / 31.94 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.107
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.62)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.139
    svelte: ^3.34.0 => 3.41.0
```

### Severity

annoyance / blocker

**Comment by benmccann** [comment]
Please do not file duplicate bugs when you already know an issue exists
