### ISSUE TITLE
app doesn't behave like a SSR app

### ISSUE THREAD

**Issue by shihjyun** [sveltejs/kit#2067]
### Describe the bug

Hi guys, here is the problem that bothers me few days, I have no idea why my sveltekit app doesn't behave like a SSR app.

When I run my app on dev mode or deploy it on vercel, there're not render anythings that I build (contents of `%svelte.head%` & `%svelte.body%`) in the **source page**, but those things just show normally on my page ... and I pretty sure all of my libraries are up to date. So I think it's a bit weird.

Because of this, crawlers on social networking sites or search engines may not be able to obtain the correct content from my website.

content from source page: 
![image](https://user-images.githubusercontent.com/51523128/127885649-38fa55ed-562c-4c22-9281-47ff3089793f.png)

some stuff in `src/routes/index.svelte`:
```
<section>
  ...
</section>
<section>
  ...
</section>
<section>
  ...
</section>
<section>
  ...
</section>
```

### Reproduction

reproducible repo: https://github.com/shihjyun/dd-story-hub
vercel app: https://www.ddstoryhub.com/

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 120.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 90.0.1
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.27 
    @sveltejs/kit: next => 1.0.0-next.140 
    svelte: ^3.38.0 => 3.41.0
```

### Severity

annoyance

### Additional Information

- I found that some meta tags that I add in `<svelte:head>` in `src/routes/index.svelte` show up within the `_app/pages/index.svelte-cd04194d.js`(the link I provided above), maybe those tags get render after this script is been run.
- there is the same problem with another adapter(adapter node)

**Comment by benmccann** [comment]
My guess would be that this line returns false on the server?
https://github.com/shihjyun/dd-story-hub/blob/edae0f00d553d8caf303acce3222d7def045eae8/src/routes/__layout.svelte#L39

**Comment by shihjyun** [comment]
thank you very much! That's the problem, I will find other ways to achieve the feature I want.
