### ISSUE TITLE
Allow 400 level status codes to be coupled with redirects

### ISSUE THREAD

**Issue by jwrunner** [sveltejs/kit#2068]
### Describe the problem

I have a dictionary which has individual entries that can be routed to. If someone shares a link to an entry, but then that entry is deleted, they will be trying to link to an entry which is not found (404 error code) at which point I would like to redirect them automatically in the load function to the dictionary homepage so they can browse other entries. SvelteKit tells me I'm only allowed to use 300 level errors (https://github.com/sveltejs/kit/blob/2a1e9795ad9773e04669a7b9d0234caa0b688ade/packages/kit/src/runtime/load.js#L42) none of which are proper for this use case.

### Describe the proposed solution

Allow 400 level error codes to be the explanation for a redirect.

### Alternatives considered

I know that one could argue it'd be better to show users a 404 page so they know the content their linking to is no longer available but in my use case that will just be bogging the user down. I'd like to get them straight to the dictionary.

### Importance

nice to have

### Additional Information

Would like this to be valid:
```
return { status: 404, redirect: `/${params.dictionaryId}` };
```

**Comment by benmccann** [comment]
Related https://github.com/sveltejs/kit/issues/1574

**Comment by benmccann** [comment]
The danger here is what if you redirect to a page with an error. You could enter an infinite loop

**Comment by Conduitry** [comment]
Does http even let you specify a location header with a 4xx response and will browsers respect it? I'm not sure what the request is for here. If you want a response that results in an immediate redirect, that should be a 3xx. If you want a timed redirect, you can render your own meta tag to do this.

**Comment by benmccann** [comment]
It would appear you're correct and this would not be a valid behavior

https://stackoverflow.com/questions/10466477/cant-seem-to-send-404-and-location-headers-together
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

**Comment by Conduitry** [comment]
I just gave this a try, and, no, browsers do not appear to respect `Location` headers for 4xx responses (which I'm a bit relieved to confirm!). My question, then, is still: what exactly is this asking for? A 4xx response containing a `<meta>` tag indicating a redirect? That would probably be possible, but probably not something we'd want to support or encourage. If you really want this, you could probably wrangle it yourself.

**Comment by jwrunner** [comment]
This is fine to be closed. I'm in over my head on understanding all the browser requirements surrounding different response codes. I merely want to give users the next best thing when their linked to entry is non-existent. I can do that with 3xx codes still even though it seems odd.
