### ISSUE TITLE
Tests are not running

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2069]
### Describe the bug

It looks like our browser tests are not running

This would explain recent regressions (e.g. https://github.com/sveltejs/kit/issues/2041)

I'm hesitant to merge any PRs until this gets fixed. I've added a note to the PR template informing PR submitters of this

Help looking into this issue would be appreciated

### Reproduction

If I make the first line `throw new Error('this should fail');` the test suite still passes

https://github.com/sveltejs/kit/blob/459efa27a8af5ad51d2a2c3aa8932f91344492cf/packages/kit/test/apps/basics/src/routes/routing/_tests.js#L205

### System Info

```shell
`master`
```

### Severity

blocking an upgrade

**Comment by harvey-k** [comment]
There seems to be a large number of tests being skipped.

This appears to be the last build of master where most tests were not skipped:
https://github.com/sveltejs/kit/runs/3057873558?check_suite_focus=true#step:11:276

And this looks like the first master build where many tests are skipped, and is still occurring:
https://github.com/sveltejs/kit/runs/3060779795?check_suite_focus=true#step:11:276

**Comment by harvey-k** [comment]
Test 'successfully' fails again when reverting packages/kit/tset/apps/basics/package.json back to the original code here:
https://github.com/sveltejs/kit/pull/1900/commits/c9f31dd6d20766ee55c23cc316658767c661dc1e#diff-cd5fb14d34909f44d04d296204d55dc16ccd7540c5a03f56106856bfcde2a0be

If I submit a pull request, should I attempt fixing the other tests?

**Comment by Mlocik97** [comment]
https://github.com/sveltejs/kit/blob/c9f31dd6d20766ee55c23cc316658767c661dc1e/packages/kit/test/apps/basics/package.json

**Comment by Mlocik97** [comment]
actually I can see `../` 3x = actual folder is test,.. you maybe want actual folder to be kit, so it means we need `../` 4x

**Comment by benmccann** [comment]
I just changed it locally back to:
```
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"preview": "svelte-kit preview"
```

It doesn't look like it changes anything. I changed a test so that it should fail and I'm still not seeing any test failures

The reason for changing was so that I could run the test projects myself with `pnpm run dev` and see what the tests were seeing. I added a line to the readme describing this:

>You can run the test server with cd packages/kit/test/apps/basics; pnpm run dev to hit it with your browser.

I think the path is correct as is since the following works:
```
cd packages/kit/test/apps/basics/
ls ../../../svelte-kit.js
```

**Comment by benmccann** [comment]
>This appears to be the last build of master where most tests were not skipped:
https://github.com/sveltejs/kit/runs/3057873558?check_suite_focus=true#step:11:276
>
>And this looks like the first master build where many tests are skipped, and is still occurring:
https://github.com/sveltejs/kit/runs/3060779795?check_suite_focus=true#step:11:276****

Aha!! Thank you! That helped me figure it out: https://github.com/sveltejs/kit/commit/e8b391bc32b07255e9b2b8dea166ec0e5e071bdb

**Comment by Mlocik97** [comment]
".only()" :laughing:

**Comment by Mlocik97** [comment]
now we see, there is tons of errors... yikes

**Comment by benmccann** [comment]
yeah :stuck_out_tongue_closed_eyes:   that was before I found `FILTER` in the code I guess. the custom test runner meant I couldn't figure out how to do even basic things since standard stuff like mocha's `--grep` didn't work and there were no docs. I tried to document some stuff, so hopefully it's a bit better now 

but yeah, now time to fix all the errors :cry:

**Comment by Mlocik97** [comment]
I also have idea, we should probably set in workflow, that skipped tests must be = 0.

**Comment by Mlocik97** [comment]
So test were not running from Jul 13, 2021... Yikes,... how a lot of code changes in half month?

**Comment by sebastianrothe** [comment]
> I also have idea, we should probably set in workflow, that skipped tests must be = 0.

It would be a good idea to use [eslint-plugin-jest](https://www.npmjs.com/package/eslint-plugin-jest) and enforce the linting in the CI. The plugin does not allow skipping or restricting tests.
