### ISSUE TITLE
Query params null on initial load with adapter-static

### ISSUE THREAD

**Issue by neurosnap** [sveltejs/kit#2081]
### Describe the bug

When using the `page` store from `$app/stores` in conjunction with `adapter-static` and uploading to GCP storage, the initial load of the page does not have the correct query parameters.

The query parameter works correctly both with `svelte-kit dev` and `svelte-kit build && svelte-kit preview`.

[This issue seems related](https://github.com/sveltejs/kit/issues/969#issuecomment-871122563) from #969 

### Reproduction

[index.svelte](https://github.com/neurosnap/kit/blob/b22fe9c600a85d17ff18bd4fc8ab7db2a0bd2a3a/examples/query/src/routes/index.svelte)

```
<script context="module">
import { page } from '$app/stores';
</script>

<h1>Query: {$page.query.get('search')}</h1>
```

URL: http://kit-query.storage.googleapis.com/index.html?search=test

[svelte.config.js](https://github.com/neurosnap/kit/blob/b22fe9c600a85d17ff18bd4fc8ab7db2a0bd2a3a/examples/query/svelte.config.js)

### System Info

```shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
npx: installed 1 in 0.676s

  System:
    OS: Linux 5.13 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 10.66 GB / 15.58 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.21.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  npmPackages:
    @sveltejs/eslint-config: github:sveltejs/eslint-config#v5.7.0 => 5.7.0
```

### Severity

annoyance

### Additional Information

I'd be happy to submit a PR to fix this issue but I need a little help knowing where to start.

**Comment by ignatiusmb** [comment]
Duplicate of #669

**Comment by neurosnap** [comment]
Ah, I didn't see this when searching, thanks!
