### ISSUE TITLE
dotenv and debugging

### ISSUE THREAD

**Issue by basaran** [sveltejs/kit#2091]
### Describe the problem

I have been trying to expose DEBUG flag to `debug` server side endpoints and hooks through `.env` using `dotenv` package but I couldn't succeed. 

### Describe the proposed solution

It seems vite has some configuration options that can be used, but I'm not sure how to place this to svelte.config.js

https://github.com/vitejs/vite/issues/2676

```
import { defineConfig, loadEnv } from 'vite';

export default defineConfig(({ mode }) => {
  Object.assign(process.env, loadEnv(mode, process.cwd()));

  return {
    // ...
    base: process.env.VITE_ASSET_URL
  }
});
```

### Alternatives considered

I was able to workaround this by using `dotenv-cli` and package.json

```
	"scripts": {
		"dev": "dotenv -e .env -- svelte-kit dev --port 4000 --host 0.0.0.0",
		"build": "svelte-kit build",
		"preview": "svelte-kit preview",
		"carbon": "gulp -f gulpfile.cjs"
	},
```

### Importance

nice to have

### Additional Information

If there is an official way, it would be nice to have this in the docs.

**Comment by benmccann** [comment]
We're working on making server-side environment variables easier to use. See https://github.com/vitejs/vite/pull/4192

In the meantime, I've documented everything I know at https://kit.svelte.dev/faq#env-vars
