### ISSUE TITLE
Consider renaming `serverFetch` to `externalFetch`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2101]
### Describe the problem

`serverFetch` name is unclear. That the docs need to say in bold that it's external is a bit of a code smell. Even still, we've had people get confused (https://github.com/sveltejs/kit/issues/1823)

### Describe the proposed solution

Rename to `externalFetch`. That it runs on the server is already implied by it being located in `hooks`

### Alternatives considered

status quo

### Importance

nice to have

**Comment by stalkerg** [comment]
As, author of the original idea and PR I agree with you, this name will be better. Sorry for what I didn't find this name.
