### ISSUE TITLE
Passing read option into init when using node-adapter

### ISSUE THREAD

**Issue by istarkov** [sveltejs/kit#2102]
### Describe the problem

When I `fetch` any file in `static` folder it fails serverside if I use https protocol.
The issue that `http` is hardcoded here

https://github.com/sveltejs/kit/blob/5911b1c7044f9db3cb44c670ce124039c9e00aa6/packages/kit/src/runtime/server/page/load_node.js#L109-L110

### Describe the proposed solution

Probably it's good idea to pass `read` function here at node-adapter init https://github.com/sveltejs/kit/blob/a12beb04a4075c8277b857f96860e7ccdb3daa86/packages/adapter-node/src/index.js#L6-L6

like  `read: (file) => readFileSync(join(config.kit.files.assets, file))` so that the server reads the assets directly?

### Alternatives considered

Add read to `default_settings` here https://github.com/sveltejs/kit/blob/e55bc44a703b60e693ffa27f704bcc4fea72c136/packages/kit/src/core/build/index.js#L310-L310

### Importance

would make my life easier

### Additional Information

Workaround is using `serverFetch` or read static files through api endpoint.

**Comment by benmccann** [comment]
It looks like `read` in production comes from `settings.read` in `build/index.js` which is populated by call to `init` (i.e. the proposed solution).

Yes, I think the proposed solution makes sense. I think we can't assume the ability to do `read` in serverless platforms, which is why it's passed in and isn't default

**Comment by Rich-Harris** [comment]
I opened #3850 without realising this was already here — will close this in favour of that
