### ISSUE TITLE
Prerender crawls URLs external to app on same domain

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2105]
### Describe the bug

I haven't tested this, but think I just noticed a bug in the code

We should use consistent logic for determining if a URL is external

This seems right:
https://github.com/sveltejs/kit/blob/be30a938c42619d0af61ba98d540c103ffade216/packages/kit/src/runtime/server/page/load_node.js#L113

This does not:
https://github.com/sveltejs/kit/blob/be30a938c42619d0af61ba98d540c103ffade216/packages/kit/src/core/adapt/prerender.js#L249

### Reproduction

todo

### System Info

```shell
`master`
```

### Severity

serious, but I can work around it

**Comment by si3nloong** [comment]
@benmccann I can work on this

**Comment by benmccann** [comment]
Sure!

Btw, no need to comment about taking an issue. If it's been open for awhile with no PRs, it's quite unlikely anyone is working on it. Thanks for the help!

**Comment by si3nloong** [comment]
@benmccann I think this issue can be close since Rich already solved it https://github.com/sveltejs/kit/commit/f12bbcc686829243f111db1b463d4a261fb67c23
