### ISSUE TITLE
kit.paths.base config setting seems like doesnt work

### ISSUE THREAD

**Issue by istarkov** [sveltejs/kit#2108]
### Describe the bug

I tried to set `kit.paths.base`  option at `svelte.config.js`, but seems like it has zero affect.

Documentation says that.
```markdown
base — a root-relative path that must start, but not end with / (e.g. /base-path). 
This specifies where your app is served from and allows the app to live on a non-root path
```

i.e. having svelte.config.js like
```javascript
{
  kit: {
    target: '#svelte',
    paths: {
      base: '/base',
      assets: '',
    },
  },
};
```

 I'm expecting to access all routes paths like `/base/about` etc
but getting __Not found: /base/about__ 

_but /about is working independent of kit.paths.base_

I thought it must be something like as https://nextjs.org/docs/api-reference/next.config.js/basepath but or its some other feature or its not working as expected

### Reproduction

https://github.com/realadvisor/kit-paths-base-issue

```bash
npm init svelte@next my-app
# use defaults
```

then change config on 

```javascript
/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    paths: {
      base: '/base',
      assets: '',
    },
  },
};
export default config;
```

```bash
npm install
npm run dev
```

open browser at http://localhost:3000/base/about and see 404

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC Processor
    Memory: 3.50 GB / 15.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.volta/tools/image/node/14.16.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 6.14.11 - ~/.volta/tools/image/node/14.16.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.142 
    svelte: ^3.34.0 => 3.42.1 
```
```


### Severity

serious, but I can work around it

### Additional Information

workaround is moving routes at build time into subdirectory but that is so so behaviour.

**Comment by benmccann** [comment]
Hmm. It looks like we might not have a test for this. We should probably set the `base` option in `packages/kit/test/apps/options` to test it. A PR to fix would be welcome if anyone wants to take a stab at it :smile:

**Comment by nhe23** [comment]
Isn't this the same as #2886? If so this can be closed as this works in the latest version of Sveltekit.

**Comment by bluwy** [comment]
I've verified this locally and it seems to work with the latest version as well. Closing this then.
