### ISSUE TITLE
hn.svelte.dev example breaks all other local sveltekit sites

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2118]
### Describe the bug

When you visit localhost:3000 for the HN example it redirects to localhost:3000/top/1. That gets cached by the browser and you can't visit the homepage of any other SvelteKit site you might be working on. It happens to me constantly and is maddening

### Reproduction

in git

### System Info

```shell
n/a
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment]
during dev, 301 redirects should be rewritten to 302

**Comment by Conduitry** [comment]
Hm. I can see why that'd be helpful, but it still makes me a bit uncomfortable. Where would this rewriting happen? Just for redirects generated by `load`? For redirects generated by other endpoint functions? If you have a `handle` hook that calls `resolve`, would `resolve` return the already rewritten 301->302? Or would SvelteKit intervene and rewrite 301->302 in the response returned by `handle`?

A much easier solution would be to update the HN example to use different HTTP codes in dev and prod - or even to just always use a 302.

**Comment by dominikg** [comment]
for this concrete example, yes. just using 302 instead of 301 works. 

But this is just one case of the general "redirects during dev" story. As the code responsible for the redirects might change the target any time during dev, and the devserver origin is very commonly shared (localhost:3000), we should avoid polluting the browser cache of that origin. (similar problem can happen with service-workers)

Not sure what the best way to implement this would be, most likely a dev-only middleware at the far end of the chain swapping out the response code from 301 to 302?

**Comment by Conduitry** [comment]
Would you also think that, after we get the response from the `handle` hook, we should rewrite any `cache-control` headers as well?

Protecting users from themselves isn't an inherently bad goal, but I'm just worried about doing so in a way that secretly rewrites their responses after the point they have the ability to do anything about it.

Do we want this to be configurable? Do we want to warn the users in any way when we've done something like this? These were the questions I was trying to avoid for now. We don't need any more scope creep on SvelteKit 1.0, and the simplest and least controversial way to address this specific issue is to change the HN project.

**Comment by dominikg** [comment]
You are right. This is a can of worms and opening it now isn't a good idea.
If it becomes a recurring issue with user projects, a FAQ entry + maybe some dev mode inspecting middleware that logs a warning might do enough to educate users about the risks involved in perma-caching during dev.

**Comment by dominikg** [comment]
see #2119 
`npm run build && npm run preview` would still result in a 301, but that scenario isn't easily detectable. 

Can't tell if always using 302 is desirable for the sake of the example.

**Comment by Conduitry** [comment]
@benmccann What are you seeing happen? Are you getting a 301 in dev mode (which would be unexpected to still be getting)? Were you seeing the (expected) 301 in prod or preview mode? Something else?

Should we just throw in the towel and return 302s all the time, and take the slight performance hit?

**Comment by benmccann** [comment]
Ah, yeah, it's quite likely that I had tested in production mode at some point. I use that example for testing changes in production mode fairly often. Changing it always to 302 sounds reasonable. Or maybe we could check if the request host is `localhost` instead of checking if it's production mode

**Comment by Conduitry** [comment]
I like the `localhost` idea.
