### ISSUE TITLE
Cannot read property 'handle_error' of null

### ISSUE THREAD

**Issue by traed** [sveltejs/kit#2120]
### Describe the bug

When running in a production environment I get an error 500 from and the output "Cannot read property 'handle_error' of null". No trace in the console, no error logs on the server, nothing. I don't have a function called handle_error in my code so I assume it is something internal in sveltekit?

Any idea what is this? How do I even troubleshoot this error?

### Reproduction

Cannot reproduce in a dev environment.

### Logs

```shell
No logs, just the output.
```

### System Info

```shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 DO-Premium-AMD
    Memory: 482.68 MB / 989.91 MB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/bin/node
    npm: 7.15.1 - /usr/bin/npm
  npmPackages:
    svelte: ^3.38.2 => 3.38.2
```

### Severity

blocking all usage of svelte

**Comment by benmccann** [comment]
We would need more information. E.g. a stacktrace and a copy of the file mentioned in the stack trace would be helpful

**Comment by Webbmekanikern** [comment]
My colleague @traed is currently on vacation, so I'm replying:

This issue was resolved by upgrading both Sveltekit as well as the Node adapter to the latest version (`1.0.0-next.151` and `1.0.0-next.42`). The bug was probably fixed in a recent version of the latter.

The updated system info:
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (1) x64 DO-Premium-AMD
    Memory: 314.56 MB / 989.91 MB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/bin/node
    npm: 7.15.1 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.42 => 1.0.0-next.42 
    @sveltejs/kit: ^1.0.0-next.151 => 1.0.0-next.151 
    svelte: ^3.38.2 => 3.42.1 
```
