### ISSUE TITLE
Conditional compilation/inclusion of Svelte components based on features

### ISSUE THREAD

**Issue by jquesada2016** [sveltejs/kit#2124]
### Describe the problem

Currently, Svelte has great conditional handling of components as such:
```html
{#if <condition>}
  <MountComponent />
{/if}
```

However, if the following where to happen:
```html
{#if false}
  <MountComponent />
{/if}
```

Then the above code would still make it into the final deployment artifact. This means it is currently not possible to perform conditional compilation/inclusion of code based on some static variable, or some other means.

I was originally inspired to propose such a feature after missing it a lot from the Rust programming language. In Rust, one can declare "features" for the app that can be easily enabled/disabled and the resulting executable would only contained enabled features. Such a feature would make a profound impact for projects that would like to conditionally include/exclude large portions of code from being deployed to specific environments, such as Desktop apps written with Electron or Tauri only including those relevant sections of code when those feature sets were enabled, where otherwise the rest of the code would be shared between platforms. In the context of SvelteKit, this would also open the door for providing conditionally compiled code targeting specifically SSR, or static, if one so desired, for whichever reason.

### Describe the proposed solution

My current proposed solution could be implemented in such a way:

Inside of `svelte.config.js`, one could include something like the following:
```js
const config = {
  /* config stuff */
  kit: {
    features: ["namedFeatures", /* more feature names */]
  }
}
```

And then used in a such manner:
```html
{#if $$featureName}
  <MountComponent />
{/if}
```

In the above example, the code would only get included if the named feature(s) were enabled. These features could also be able to be combined where multiple features are needed to enable compilation of that code.

For JavaScript/TypeScript side, one could do something like the following:
```javascript
import {feature} from "$app/features";

if ($feature.featureName) {
  /* everything inside this block would be conditionally included if the feature is present, or enabled */
}
```

This would also open a world of possibilities for including other components where you pay for the size you need, and nothing more. By this I mean something like the following:

Inside of an authored library, one could have the following in their `package.json`:
```json
{
  /* package stuff */
  "svelte": {
    "features": [/* list of documented features */]
  }
}
```

Then, inside of the dependee `package.json`, one could have:
```json
{
  /* package stuff */
  "svelte": {
    "features": {
      "package-name": [/* feature list one wishes to be included */]
    }
  }
}
```

### Importance

would make my life easier

### Additional Information

Please let me know what you all think of such a feature, and perhaps the implications and/or complexity of such a feature.

Perhaps the easy part would be the exclusion of components inside `#if` blocks, since those would just be parsed and removed before passing the rest of the file off to the svelte compiler, however, looking for the same tokens inside of JS might be more tricky. Regardless, I think this would be a pretty revolutionary feature for the web in general!

**Comment by benmccann** [comment]
I think this already works. If you were to literally do:

```
{#if false}
  <MountComponent />
{/if}
```

I expect that would work. If instead of `false` you were to put a condition dynamically calculated at runtime that would be impossible (halting problem amongst other difficulties). But if you'd like a boolean flag set at runtime you can use Vite's define: https://vitejs.dev/config/#define

**Comment by jquesada2016** [comment]
Although the dynamic condition would make sense to work (though haven't seen documentation on it), there's still the case of `#if <static> && ...`, which I don't believe works, and doesn't face any of the shortcomings you mentioned.

There's also the second half of the proposal, which would include defining feature sets that can be applied where needed for the current package and also for Svelte dep packages.

Regarding Vite's define, wouldn't this get injected _after_ Svelte processes the file, and therefore wouldn't be able to optimize that code away?

**Comment by benmccann** [comment]
> Regarding Vite's define, wouldn't this get injected after Svelte processes the file, and therefore wouldn't be able to optimize that code away?

It's not the Svelte compiler that optimizes it away. It's Vite/Rollup

**Comment by Rich-Harris** [comment]
Yeah, this basically already works for any expressions that can be statically evaluated by Rollup:

```svelte
{#if dev}
  <ThisComponentWillNotBeImportedInDevMode/>
{/if}
```

The one caveat is that the component will still be imported for its side-effects, which means that its CSS will get included. It's possible to disable that at an app-wide level by passing some config to Rollup:

```js
// svelte.config.js
export default {
  kit: {
    vite: {
      build: {
        rollupOptions: {
          treeshake: {
            moduleSideEffects: false
          }
        }
      }
    }
  }
};
```

That _does_ carry a small risk of introducing bugs if you have side-effecty imports elsewhere in your app, but the risk is small. Perhaps in future there'll be a way to tweak that configuration further, but for now I'm going to close this as 'close enough'.
