### ISSUE TITLE
Relative URLs in markup are broken

### ISSUE THREAD

**Issue by vwkd** [sveltejs/kit#2140]
### Describe the bug

This issue affects relative URLs in the markup, which are handled incorrectly. There are two issues here that are closely linked together hence reporting them here both.

### Issue 1

The client-side router treats relative URLs in the markup as absolute URLs.

### Issue 2

The integrated development static file server (Vite?) behaves similarly to the faulty client-side router in issue 1. This masks issue 1 when testing locally. You can only see issue 1 when using another static file server locally or if you deploy somewhere.

See Reproduction for an example that should make the two issues clearer.

I mark this as the most critical issue, since currently it appears to be impossible to make relative URLs work correctly.

### Reproduction

See https://github.com/vwkd/svelte-kit-relative-url-bug

This SvelteKit website has two pages, and index page at `/` and an about page at `/about`, as well as a Svelte logo as static file at `/svelte-logo.svg`. The layout contains the nav twice, once using relative URLs (incorrect on the about page!) and one using absolute URLs (always correct). The about page contains the logo twice, once using relative URLs (incorrect!) and one using absolute URLs (correct).

Starting from the index page (SSR) and navigating to the about page using the relative URL should work, because the index page is one level higher. It indeed works, but rather "by accident", because the absolute and relative URLs are in this case the same. Don't let that confuse you! Navigating anywhere from the about page using the relative URLs should break, since they should point to `about/` and `about/about`. But instead it works, because the client-side router incorrectly treats them as absolute URLs. We also expected the image using the relative URL to break, since it should point to `/about/svelte-logo.svg`, but instead it showed.

Starting from the about page (SSR), we now see how things should actually work. The about page is broken. The relative nav doesn't work, and the relative image doesn't show. If you navigate to the index page and back, now the about page isn't broken anymore. Breakage depends on if your page was rendered using SSR or CSR.

### Issue 1

Let's first see issue 1. I'm using a deployed version, because of Issue 2. The URLs are shown in the bottom left while I hover over the links.

https://user-images.githubusercontent.com/33468089/128707365-c2d164d7-70ba-4b72-ab97-b0e158be7ac8.mov

### Issue 2

If instead we had tested it locally, we wouldn't have seen issue 1 at all. While the deployed version above breaks on the about page, the local version does not. We can clearly see that the local dev server masks issue 1, because it behaves like the faulty client-side router. 

https://user-images.githubusercontent.com/33468089/128707311-a0150cbb-bfcc-4b85-8362-5e4609abf755.mov

### System Info

```shell
System:
    OS: macOS 11.5
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.11 => 1.0.0-next.16 
    @sveltejs/kit: next => 1.0.0-next.142 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Not sure if issue 2 is due to SvelteKit or Vite.

I didn't test if relative URLs are also broken in JavaScript. Further testing would be appreciated.

**Comment by Middlerun** [comment]
Isn't this just due to the trailing slash in the URL, which is present when the page is loaded directly vs and absent after client-side navigation? A URL with a trailing slash is treated by the browser as one level deeper, so the relative URLs are behaving as expected.

Maybe you just need to set the `trailingSlash` option in your config.

**Comment by vwkd** [comment]
Thanks @Middlerun. I tested it locally and setting `trailingSlash = "always"` fixed both issues making relative URLs again behave as expected.

I've read up about relative URL behaviour with trailing slashes as I was indeed confused having expected a trailing slash to not matter. But it does indeed for this special case of relative URLs to child resources. See [StackOverflow](https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url/16445016#16445016), or more rigorously [blog.cdivilly.com](https://blog.cdivilly.com/2019/02/28/uri-trailing-slashes)

> [..] the implication of the significance of the right-most `/` character in the URI resolution algorithm is that **if a [parent] resource has child resources [..], then the parent resource must have a trailing slash.**

Contrary to popular belief, trailing slashes don't distinguish between "file" and "directory" in URLs, because there are only resources. It's a remnant of the notation in the Unix file systems. Also SEO isn't compromised.

There seems to be no good reason (other than aesthetics) to not use trailing slashes. But there is a very good reason to put in trailing slashes, namely relative URL resolution.

So the question then becomes shouldn't `trailingSlash = "always"` be the default?

**Comment by iOiurson** [comment]
I need to investigate a little more, but while playing with `load`'s `redirect`, i found out that `__layout` and `index` pages (and `__error` [once we can redirect from `error` pages](https://github.com/sveltejs/kit/pull/2127)) have this relative path issue, but not other pages.

**Comment by vwkd** [comment]
@iOiurson 🤔Not sure what bug you found, but they seem to be different from what I described. In https://github.com/sveltejs/kit/issues/2140#issuecomment-895952107 I learned that there is no bug. The issue arises because of the the default config value for trailingSlash.

**Comment by iOiurson** [comment]
This might be a different bug indeed, i filed a new issue here: #2235

**Comment by vwkd** [comment]
Sad to see this issue being closed without giving a reason when there are still open question to be resolved (read above).

Seems there is high pressure to get the issue count down. Ugh.

**Comment by benmccann** [comment]
This was closed because there's no bug here. I understand you'd like the default to be different, but different people will have different opinions about what the default should be, and so unfortunately we can't make everyone happy there
