### ISSUE TITLE
Default appDir "_app" incompatible with some file managers

### ISSUE THREAD

**Issue by Marr11317** [sveltejs/kit#2143]
### Describe the bug

Jekyll ignores files starting with an underscore.
This means that trying to publish to, for example, Github Pages will result in the whole "_app" directory not being served.

The PR's actually ready on my fork, tell me when I should open and continue the discussion there.

### Reproduction

Coming in a few minutes.

### System Info

```shell
Github Pages
```

### Severity

annoyance

**Comment by Marr11317** [comment]
Reproduction: https://github.com/Marr11317/sveltekit-issue-2143

**Comment by Marr11317** [comment]
Workaround: better documentation.
https://github.com/sveltejs/kit/pull/2135/files#diff-686a8887792be1010ca671d32a7cfb517fe5ad28cfe2a84dce332ab4b07dc1bd

Ideally it should work out of the box though.
I suggest the name "app_" instead.

**Comment by Marr11317** [comment]
Note that #861 will have to be closed before changing the name for 1.0.

It is breaking changes.

**Comment by manuel3108** [comment]
I don't think this is necessary. You can create a `.nojekyll` file in your `gh-pages` branch and after that the files should be served.

Also you could use this action https://github.com/marketplace/actions/github-pages-action. According to this https://github.com/marketplace/actions/github-pages-action it should even be the default.

**Comment by Marr11317** [comment]
Ok so better documentation only.
