### ISSUE TITLE
Server Crash at endpoint

### ISSUE THREAD

**Issue by vfilatov** [sveltejs/kit#2153]
### Describe the bug

I discovered a bug causing the server crash while using `nunjucks` template containing error.

### Reproduction

```
cd /tmp
npm init svelte@next crash
# respond defaults
cd crash
```

setup code

```
# create template folder
mkdir views

# create views/template.njk
cat << EOF > views/template.njk
{# next line missing '%' before '}' #}
{% block body }
Hi from Template
{% endblock %}
EOF

# delete default code
rm src/routes/*

# create endpoint
cat << EOF > src/routes/index.js
import nunjucks from 'nunjucks';

const _base = typeof process !== 'undefined' && 'PWD' in process.env
       ? process.env['PWD']
       : '';

nunjucks.configure(_base + '/views', {
  autoescape: false,
  watch: false,
  noCache: true,
});

const template = '{% include "template.njk" %}';

export async function get () {
  try {
    const body = nunjucks.renderString(template);
    return { body }
  }
  catch (error) {
    return {
      body: error.toString()
    }
  }
}
EOF
```
`npm install nunjucks`
`npm run dev`
navigate browser to `http://localhost:3000`

Observe the server crash

### Logs

```shell
> ~TODO~@0.0.1 dev
> svelte-kit dev


  SvelteKit v1.0.0-next.144

  local:   http://localhost:3000
  network: not exposed

  Use --host to expose server to other devices on this network


/tmp/crash/node_modules/nunjucks/src/environment.js:575
          throw err;
          ^

Template render error: (unknown path)
  Template render error: (/tmp/crash/views/template.njk) [Line 3, Column 1]
  expected block end in block statement
    at Object._prettifyError (/tmp/crash/node_modules/nunjucks/src/lib.js:36:11)
    at /tmp/crash/node_modules/nunjucks/src/environment.js:563:19
    at eval (eval at _compile (/tmp/crash/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:19:11)
    at /tmp/crash/node_modules/nunjucks/src/environment.js:41:5
    at RawTask.call (/tmp/crash/node_modules/asap/asap.js:40:19)
    at flush (/tmp/crash/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

### System Info

```shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel Core Processor (Haswell, no TSX, IBRS)
    Memory: 23.07 GB / 31.42 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.17.4 - /usr/bin/node
    npm: 7.20.5 - /usr/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.144 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
This doesn't look like a SvelteKit issue

Also, take a second look at your template: `{% block body }`. I've never used nunjucks, but that doesn't look right

**Comment by vfilatov** [comment]
> This doesn't look like a SvelteKit issue
> 
> Also, take a second look at your template: `{% block body }`. I've never used nunjucks, but that doesn't look right

`{% block body }` done on purpose to cause the exception which leads to the server crash.

I believe it **_is_** a SvelteKit issue as I would not expect the server crash within try {} catch () {} block

**Comment by benmccann** [comment]
Maybe it's coming from your call to `nunjucks.configure` which is outside the try / catch

**Comment by vfilatov** [comment]
> Maybe it's coming from your call to `nunjucks.configure` which is outside the try / catch

I doubt that.

```
at flush (/tmp/crash/node_modules/asap/raw.js:50:29)
```
if I replace
```javascript
queue[currentIndex].call();
```
as
```javascript
try { queue[currentIndex].call(); } catch (e) { console.log('RAW:', queue[currentIndex], e) }
```
I can see
```
RAW: RawTask { task: null, domain: null } Template render error: (unknown path)
  Template render error: (/tmp/crash/views/template.njk) [Line 3, Column 1]
  expected block end in block statement
    at Object._prettifyError (/tmp/crash/node_modules/nunjucks/src/lib.js:36:11)
    at /tmp/crash/node_modules/nunjucks/src/environment.js:563:19
    at eval (eval at _compile (/tmp/crash/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:19:11)
    at /tmp/crash/node_modules/nunjucks/src/environment.js:41:5
    at RawTask.call (/tmp/crash/node_modules/asap/asap.js:40:19)
    at flush (/tmp/crash/node_modules/asap/raw.js:50:35)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
^C
```
and the server does _not_ crash

**Comment by benmccann** [comment]
I don't know what `queue[currentIndex].call();` is but it's not from SvelteKit. The only stuff in the stack trace in from nunjucks. Can you more clearly tie this to SvelteKit somehow? E.g. can you reproduce without nunjucks involved? If it's simply a matter of SvelteKit not handling errors correctly you shouldn't need nunjucks for a reproduction

**Comment by vfilatov** [comment]
> I don't know what `queue[currentIndex].call();` is but it's not from SvelteKit. The only stuff in the stack trace in from nunjucks. Can you more clearly tie this to SvelteKit somehow? E.g. can you reproduce without nunjucks involved? If it's simply a matter of SvelteKit not handling errors correctly you shouldn't need nunjucks for a reproduction

You seem to be right.
I cannot reproduce that without `nunjucks` module.

Meanwhile there is still a question: how can I prevent the SvelteKit from crashing in case of 3rd party module fails?

**Comment by vfilatov** [comment]
Created an issue with `Nunjucks` https://github.com/mozilla/nunjucks/issues/1368
