### ISSUE TITLE
ESLint not working from terminal in typescript skeleton starter

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#2156]
### Describe the bug

The skeleton starter doesn't appear to setup ESLint correctly for use with TypeScript. Getting `Unexpected token  ParseError`.

### Reproduction

Run `npm init svelte@next test-eslint` and answer yes to the Typescript, ESLint and Prettier prompts.

```sh
$: npm init svelte@next test-eslint

Welcome to SvelteKit!

This is beta software; expect bugs and missing features.

If you encounter a problem, open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › Skeleton project
✔ Use TypeScript? … Yes
✔ Add ESLint for code linting? … Yes
✔ Add Prettier for code formatting? … Yes
✔ Copied project files
✔ Added TypeScript support. To use it inside Svelte components, add lang="ts" to the attributes of a script tag.
✔ Added ESLint.
Readme for ESLint and Svelte: https://github.com/sveltejs/eslint-plugin-svelte3
✔ Added Prettier.
```

Add a `<script>` tag to `src/routes/index.svelte`:

```svelte
<script lang="ts">
  let foo: string;
</script>
```

Then run `eslint` on the `src` directory:

```sh
eslint src

test-eslint/src/routes/index.svelte
  2:12  error  Unexpected token  ParseError

✖ 1 problem (1 error, 0 warnings)
```

### System Info

```shell
System:
    OS: macOS 11.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 202.33 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 92.1.27.111
    Firefox: 88.0
    Safari: 14.1.2
```

### Severity

annoyance

### Additional Information

Not sure if this issue belongs here or with https://github.com/sveltejs/eslint-plugin-svelte3.

**Comment by Conduitry** [comment]
If you're running literally `eslint src`, then you're running some globally installed copy of ESLint, which likely isn't going to handle things that need plugins correctly. When I use `npx eslint src` (so that I'm using the local copy of ESLint installed in the project), I can't reproduce this.
