### ISSUE TITLE
Consider renaming `prerender.pages` option

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2185]
### Describe the problem

`prerender.pages` config name is confusing. E.g. https://github.com/sveltejs/kit/issues/1683

### Describe the proposed solution

rename to something like:
- `prerender.entry`
- `prerender.entryPoints`
- `prerender.start`
- `prerender.startPages`

### Importance

nice to have

**Comment by Mlocik97** [comment]
prerender.start is really dumb name... I think prerender.entry sound good.

**Comment by MarioDena** [comment]
+1 on prerender.entry
