### ISSUE TITLE
`1.0.0-next.147` breaks conditional `[slug]` routes

### ISSUE THREAD

**Issue by Accelyte** [sveltejs/kit#2186]
### Describe the bug

On `@sveltejs/kit` version `1.0.0-next.147`, trying to access routes such as `[id].svelte` results in
```
error loading dynamically imported module
```
This did not happen on version `1.0.0-next.146`.

### Reproduction

1. `npm update` to the latest version (`1.0.0-next.147`)
2. try to access a relative route such as `[id].svelte`
3. Status code 500: `error loading dynamically imported module`

### System Info

```shell
Need to install the following packages:
  envinfo
Ok to proceed? (y) 
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
    Memory: 2.91 GB / 7.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.33 => 1.0.0-next.40 
    @sveltejs/kit: next => 1.0.0-next.147 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

blocking _some_ usage of SvelteKit

### Additional Information

If it helps, here is the (working) system info prior to `npm update`

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
    Memory: 2.92 GB / 7.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.33 => 1.0.0-next.39 
    @sveltejs/kit: next => 1.0.0-next.146 
    svelte: ^3.34.0 => 3.42.1 
```

**Comment by benmccann** [comment]
`vite-plugin-svelte` was upgraded from `1.0.0-next.14` to `1.0.0-next.16`. I wonder if that's it. If you have a repo that reproduces this, that would help

**Comment by Accelyte** [comment]
After a bit of testing, I realised the issue actually has to do with how SvelteKit handles the `paths` config in `svelte.config.js`:
```
/** @type {import('@sveltejs/kit').Config} */
import node from "@sveltejs/adapter-node";
import preprocess from "svelte-preprocess";

const config = {
    preprocess: preprocess({
        scss: {
            renderSync: true,
        },
    }),
    kit: {
        target: "#svelte",
        adapter: node({
            env: {
                port: "PORT",
            },
        }),
        paths: {
            base: "/somebasepath",
        },
    },
};

export default config;
```

A bit of context: the app is currently deployed at `mywebsite.com/somebasepath`. In my `src` folder, I have the following:

```
src/
  routes/
    list/
      [id].svelte
      index.svelte
```

I also have a convenience script: `npm run serve`, which is defined as:

```
"serve": "npm run build && PORT=8000 node build/index.js",
```

After running `npm run serve`, the app is deployed at `localhost:8000`, which is then forwarded to `mywebsite.com/somebasepath`. Here is what I found:
- `localhost:8000/somebasepath/list`: 404
- `localhost:8000/list`: OK
- `localhost:8000/list/1`: OK
- `mywebsite.com/somebasepath/list`: OK
- `mywebsite.com/somebasepath/list/1`: 500: Failed to fetch dynamically imported module

**Comment by noahsalvi** [comment]
> `vite-plugin-svelte` was upgraded from `1.0.0-next.14` to `1.0.0-next.16`. I wonder if that's it. If you have a repo that reproduces this, that would help

I made a repro for this issue
https://github.com/noahsalvi/kit-path-broken-repro

**Comment by benmccann** [comment]
A repo is always helpful. Otherwise we have to setup an app with those routes ourselves to see what is happening, which takes up a lot of time when we have to do it across hundreds of issues
