### ISSUE TITLE
Static adapter fails on startup

### ISSUE THREAD

**Issue by pfesenmeier** [sveltejs/kit#2187]
### Describe the bug

attemping to run a project with a the static adapter returns error on startup

### Reproduction

```bash
clone https://github.com/svelteland/svelte-kit-blog-demo/commit/f8b7ac29d2c193d548e4fa01888b4ee4ac78511e
cd svelte-kit-blog-demo
npm i
npm run dev
```

### Logs

```shell
config.kit.adapter should be an object with an "adapt" method. See https://kit.svelte.dev/docs#adapters
Error: config.kit.adapter should be an object with an "adapt" method. See https://kit.svelte.dev/docs#adapters
    at Object.validate (file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:332:13)
    at validate (file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:627:28)
    at validate (file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:625:19)
    at validate_config (file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:714:20)
    at load_config (file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:691:20)
    at async get_config (file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:834:10)
    at async file:///home/pfes/svelte-kit-blog-demo/node_modules/@sveltejs/kit/dist/cli.js:894:18
```

### System Info

```shell
Ubuntu 20
```

### Severity

blocking all usage of SvelteKit

**Comment by ignatiusmb** [comment]
This is an issue for that repo itself, it is [using outdated version of the adapter](https://github.com/svelteland/svelte-kit-blog-demo/blob/f8b7ac29d2c193d548e4fa01888b4ee4ac78511e/package.json#L12)

**Comment by pfesenmeier** [comment]
Sorry, @ignatiusmb , I meant to mention that pinning the adapter to version `next` does not fix or change the problem

**Comment by ignatiusmb** [comment]
You need to reinstall it with
```
npm i @sveltejs/adapter-static@next
```

**Comment by pfesenmeier** [comment]
Awesome, thank you!

**Comment by chris-aeviator** [comment]
this should be added to readme - everyone runs into this at first

**Comment by ignatiusmb** [comment]
> this should be added to readme - everyone runs into this at first

Is there anything else you find unclear from the readme, which one should be added there? The installation command is literally the first thing in the usage section

https://github.com/sveltejs/kit/blob/c32218b7dd41e41d695c0eb1bda1a2542e7d763b/packages/adapter-static/README.md#L5-L7

**Comment by chris-aeviator** [comment]
actually revisiting I have to agree having been blind to it

I think I just literally skipped from [headline announcing package name] to [npm install -D] translating it in my head to `yarn add --dev` back to [headline]

My bad but that's how long coding days might look like :-)
![grafik](https://user-images.githubusercontent.com/11522213/133737398-b64c936b-420f-4ecc-b099-edad449b69e6.png)
