### ISSUE TITLE
Svelte fails to open new page in browser using url

### ISSUE THREAD

**Issue by tonborzenko** [sveltejs/kit#2214]
### Describe the bug

When creating new page and open it through address bar it fails without any error in console. I see only 404 error in browser. If reload terminal, page appears.

### Reproduction

1. npm init svelte@next
2. create any page in routes (ex. page.svelte)
3. navigate to this page through address bar
4. sveltekit throws error 404 and page is not refresh / reloading.

I am using windows, but I checked it on WSL with ubuntu 20, the same story. 
Also I check older version of svelte.kit, so that error not happend in v1.0.0-next.135, but since v1.0.0-next.136 it happend for each version.
I check that bug for node v14 and v16, it happened both.

### Logs

```shell
404
Not found: /info
Error: Not found: /info
    at render_page (file:///C:/Users/anstak/job/projects/linkphone/node_modules/@sveltejs/kit/dist/ssr.js:1289:11)
    at async resolve (file:///C:/Users/anstak/job/projects/linkphone/node_modules/@sveltejs/kit/dist/ssr.js:1626:12)
    at async Object.handle (/C:\Users\anstak\job\projects\linkphone\src\hooks:19:20)
    at async respond (file:///C:/Users/anstak/job/projects/linkphone/node_modules/@sveltejs/kit/dist/ssr.js:1575:10)
    at async Immediate.<anonymous> (file:///C:/Users/anstak/job/projects/linkphone/node_modules/@sveltejs/kit/dist/chunks/index.js:3454:22)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 4600U with Radeon Graphics
    Memory: 2.88 GB / 14.92 GB
  Binaries:
    Node: 16.6.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.73)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/kit: 1.0.0-next.136 => 1.0.0-next.136
    svelte: ^3.34.0 => 3.42.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I working on earlier version svelte-kit, everything worked well, but today I tried upgrade it, and I can not developing as well. So I think it is serious bug.

P.S. Sorry for bad English

**Comment by Mlocik97** [comment]
can't reproduce, it works fine for me.

**Comment by tonborzenko** [comment]
> can't reproduce, it works fine for me.

From windows?

**Comment by Mlocik97** [comment]
Linux... maybe your problem is related to https://github.com/sveltejs/kit/issues/2046 that is already fixed

**Comment by benmccann** [comment]
try again with 1.0.0-next.151. I expect it will work now

**Comment by tonborzenko** [comment]
> try again with 1.0.0-next.151. I expect it will work now

Yes, it is working. Thank you!
