### ISSUE TITLE
Addding config.kit.paths.base breaks `npm run build`

### ISSUE THREAD

**Issue by marcel0ll** [sveltejs/kit#2230]
### Describe the bug

On versions >1.0.0-next.147 adding a 'base' path to the project makes it no longer build.
This happens while using adapter-static

### Reproduction

1. Create new project

npm init svelte@next my-app
cd my-app
npm install
npm run dev -- --open

2. Install and config adapter-static 

Install with npm i -D @sveltejs/adapter-static@next, then add the adapter to your svelte.config.js:

```
// svelte.config.js
import adapter from '@sveltejs/adapter-static';

export default {
	kit: {
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null
		})
	}
};
```

3.  Config 'base' path
 
```
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		paths: {
			base: '/something'
		},
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null
		})
	}
};

export default config;
```

4.  `npm run build`

### Logs

```shell
vite v2.5.0 building SSR bundle for production...
✓ 34 modules transformed.
.svelte-kit/output/server/app.js   68.93 KiB

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
> 404 /_app/start-518edf61.js (linked from /)
Error: 404 /_app/start-518edf61.js (linked from /)
...
```

### System Info

```shell
System:
    OS: Linux 4.15 Linux Mint 19.2 (Tina)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
    Memory: 7.40 GB / 15.59 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 91.0.4472.114
    Firefox: 90.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.16 => 1.0.0-next.16
    @sveltejs/kit: next => 1.0.0-next.153
    svelte: ^3.34.0 => 3.42.1
```

### Severity

blocking an upgrade

### Additional Information

Changing back to version 1.0.0-next.147 stops the error on my personal repo, but it does not seem to work on the example project.

**Comment by sidharthv96** [comment]
Facing the issue in https://github.com/mermaid-js/mermaid-live-editor

**Comment by sidharthv96** [comment]
Trying to figure out which change is causing the issue. https://github.com/sveltejs/kit/pull/2189/ seems to be related.

**Comment by Xananax** [comment]
I confirm that
```sh
pnpm remove @sveltejs/kit 
pnpm add -D @sveltejs/kit@1.0.0-next.147 
```

Allows my site to build statically.

It seems 

```sh
pnpm add -D @sveltejs/kit@next  
```

works too

**Comment by Xananax** [comment]
Actually no, the older version doesn't work either. Things break in novel and spectacular ways, `path` is empty during some part of the build, so hrefs are wrong (but not always!). The build fails with `Error: 500 (linked from /)`. Different configurations of hrefs (depending on where I compose them, template/data give me different errors, but nothing works.

I'm dropping the idea of using static for the moment, I can't make it work.

**Comment by sidharthv96** [comment]
I'm using github pages and static adapter, with base path to deploy mermaid live editor and it works without any issue on 147.

**Comment by Xananax** [comment]
Yes, you're right! After reading your comment, I re-examined my code, and I had a single hard-coded href to the homepage that wasn't using `base`. Thanks!

**Comment by gavinr** [comment]
I am having this issue too, and just to follow-up on @derolf's comment, for a workaround, if you run:

```
npm install @sveltejs/kit@1.0.0-next.147 --save-dev
npm run build
```

If seems to work.

**Comment by SarcevicAntonio** [comment]
Just wanted to note im facing the same issue. setting `kit.paths.base` gives me the error message `> 404 /_app/start-333b5ef8.js (linked from /)`.

I was using `adapter-static@1.0.0-next.19` and `@sveltejs/kit@1.0.0-next.169`, but `@sveltejs/kit@1.0.0-next.147` seems to work.

**Comment by terwer** [comment]
> https://mermaid-js.github.io/mermaid-live-editor/beta/

Thanks very much, helps me a lot❤
