### ISSUE TITLE
client-side navigation doesn't work if endpoint has the same name as a route component

### ISSUE THREAD

**Issue by GCastilho** [sveltejs/kit#2234]
### Describe the bug

The client-side navigation ~sveltekit:prefetch directive~ appears to not ~fire the prefetch~ work if there is an endpoint with the exact name of the page

### Reproduction

- Initialize template
- Add route `test.svelte`
- Add endpoint `test.ts` with a post function
- Add `/test` to the `Header` component with `sveltekit:prefetch`, as the others

When hovering the "about" page, prefetch is fired, but when hovering the "test" rout it is not, and when clicking the link the site will do a full page reload to navigate there

### System Info

```shell
System:
    OS: Linux 5.4 Linux Mint 20.2 (Uma)
    CPU: (2) x64 Pentium(R) Dual-Core  CPU      E5400  @ 2.70GHz
    Memory: 319.32 MB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.5 - /usr/bin/node
    npm: 6.14.14 - /usr/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 90.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.153 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

serious, but I can work around it

**Comment by anudeepreddy** [comment]
I suppose that is the intended behavior. If you see the documentation for [Fall through routes](https://kit.svelte.dev/docs#routing-advanced-fallthrough-routes), it clearly says the endpoints are tried first for a match. Since we find a match with the endpoint prefetch is not performed.

**Comment by GCastilho** [comment]
@anudeepreddy But the endpoint does not export a GET route, just a POST one

**Comment by anudeepreddy** [comment]
@GCastilho, Currently we obtain an array of routes then perform a check if it's an incredible endpoint. The current logic doesn't check what http methods are exposed in that route.

**Comment by GCastilho** [comment]
Ok, got it. But is there any plans to change this or it's considered the correct behavior?

**Comment by GCastilho** [comment]
I've just noticed that it's not just prefetch that isn't working, it's the whole client-side navigation that is

The site does a full page reload if there is an endpoint with the same name as a route component even if there are no get methods on the endpoint

**Comment by yn5** [comment]
I seem to be running into this too. Not sure but this I'm observing the following: Going to from route A to B works, but going back to route B doesn't update the view. The page endpoint is called consistently, and  it does seem to update the data, but only the root fields, deeper nested fields don't update.

So if the data has the following type:
```ts
type data  = {
  id: string,
  something: {
    nested: string[]
  }
}
```

then `data.id` does update on very client side navigation, but `data.something.nested[0]` doesn't.

Adding the following "works" but seems to be a hack to me:
```svelte
<script lang="ts" context="module">
    export const router = false;
</script>
```

**Comment by yn5** [comment]
It seems a production build doesn't update the view the first time either, so going from A to B never renders B.

**Comment by yn5** [comment]
I found out if I flatten the data coming from the page endpoint I can get around the issue.

So from the original data:
```ts
type data  = {
  id: string,
  something: {
    nested: string[]
  }
}
```

i needed: `data.something.nested[0]`. If I return this value and thus the following type from the endpoint the component updates as I would expect:
```ts
type data  = {
  id: string,
  something:string // which is data.something.nested[0] mapped in the endpoint
}
```

Also returning the array directly works as well:
```ts
type data  = {
  id: string,
  something:string[] // which is data.something.nested mapped in the endpoint
}
```

Sorry for "spamming" this issue. I'm very new to Svelte / SvelteKit so probably this is just my misunderstanding Svelte components and maybe has not much to do with this issue, but maybe it's useful to others reading this.

**Comment by geoffrich** [comment]
I can no longer reproduce the original issue. See this demo on [StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-vpy3k4?file=src/routes/test.svelte) -- the `/test` route is prefetched and uses client-side navigation. Since this issue was filed, things are notably different, since an endpoint with the same name as a route component is treated as a [page endpoint](https://kit.svelte.dev/docs/routing#endpoints-page-endpoints).

@yn5 your issue sounds different from the original issue. Can you open a separate issue, preferably with a full reproduction on [StackBlitz](https://sveltekit.new)?
