### ISSUE TITLE
Can we generate a default docs website like the Svelte and SvelteKit website?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#2245]
### Describe the problem

I would like to have a docs skeleton project (like Vue has) for documentation of packages and libraries created with Svelte Kit.

Is already there one?

### Describe the proposed solution

Can we generate a default one like the Svelte and SvelteKit docs website?

### Importance

would make my life easier

**Comment by Mlocik97** [comment]
Now it's not possible, but You can extract a lot of code from https://github.com/sveltejs/sites

**Comment by dummdidumm** [comment]
This is a question better asked on Discord or Reddit. A google search might bring up a lot of starter templates, maybe one is for you.

**Comment by Mlocik97** [comment]
btw. there is: https://alexxnb.github.io/svelte-docs

**Comment by Valexr** [comment]
https://github.com/GeopJr/SveltePress

https://github.com/crinklesio/dockit

**Comment by frederikhors** [comment]
> btw. there is: https://alexxnb.github.io/svelte-docs/introduction

Is deprecated, see Readme.
