### ISSUE TITLE
What's the point of rerunning the `load` function on `session` change?

### ISSUE THREAD

**Issue by csangonzo** [sveltejs/kit#2252]
### Describe the problem

It's more like a genuine question about a new feature in sveltekit. I just noticed this in the docs:
```
The load function is reactive, and will re-run when its parameters change, but only if they are used in the function.
```
After login when I set `$session.user = response.user;` like in the realworld demo (https://github.com/sveltejs/realworld/blob/master/src/routes/login/index.svelte) I see that the login page's `load` function runs again.
I use access and refresh tokens in my app and I implemented a silent refresh method, something like the one mentioned here: https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/ .
When I do a silent refresh I reset the session, but this causes a rerun of the load function now.
The problem with this is I have a lot of components that use data returned by the load function (like an editor that gets it's content first from the load function, or a form that has it's model from the load function) and if it runs again the data changes on the page, so if I had unsaved changes in my editor for example and my silent refresh runs, it loads the data again from the server so my changes will be lost.

### Describe the proposed solution

If someone could explain the benefits we get from this feature I'd be really glad, because right now this is the first thing that doesn't make any sense about sveltekit for me.

### Importance

i cannot use SvelteKit without it

### Additional Information

I follow the changes of sveltekit from day to day, last year I decided to ditch angular in favour of svelte and migrated almost every app to it that we had and I'm having problems with the authentication part because of this change. I'm open to alternative solutions as well.

**Comment by dummdidumm** [comment]
This is beneficial because you are then able to refresh your page based on changed parameters. I can see that this behavior is sometimes not beneficial, not sure for the best way to handle this. 

Random things I just came up with:
- make the `load` function return a parameter like (`noFurtherUpdates: true`) to signal SvelteKit to not refresh again
- another option similar to `srr`, like `rerunLoad`, which can be configured globally and be overwritten on a page level (`export const rerunLoad = true`

Random thoughts on how to work around it right now:
- don't update the session store / keep the token somewhere else
- don't reference `session` in the pages, if possible (load won't rerun then)
- restructure how page props overwrite unsafed stuff

**Comment by csangonzo** [comment]
Thanks for the response!
The real problem comes when I validate every page with session's user property, so I check `$session.user`, if it exists the user can stay on the page, if not then redirect.
I also use my access token in the load function (on the server and on the client as well) and it's in the session's user property. Since load can run on the client and on the server side, it was my only solution to store the token in.
So right now I don't think I can store it anywhere else, and since I check it on every page that requires a logged in user I have to reference it in `load`.
Restructuring how I handle the page props would be a solution, but there'd still be the exported data that would change to the newly fetched data from the load function, and needless to say it would make an unnecessary request to the server for data that would never be used.

**Comment by csangonzo** [comment]
Okay, so as I see the `load` function, it's main functionality is to do/check things before navigating to a specific page. Basically I use it for checking whether the user authenticated or not and if they are load some data associated with the user and the current page.

```js
export async function load({ page, fetch, session }) {
		if (!session?.user) {
			return { status: 302, redirect: '/'};
		}
		const { data } = await api.get(...);
		return { props: { data } };}
```
This means that the page needs to have an exported value named `data`.
```js
...
export let data;
...
```
We want to use this `data` for something, let's say display it's properties in a form so the user can edit it.
Now I have input fields bound to this `data`.
If my global store or any other function changes the `session`, it would be reloaded, the fields the user already edited would be filled with the data from the server, so all unsaved progress would be lost.

This means that I can't change the `session`'s value when the user is using a page.

**Comment by csangonzo** [comment]
To reproduce it see: https://github.com/csangonzo/sveltekit-refresh-test
Run `npm i`, then `npm run dev` and navigate to `about`.

**Comment by mdynnl** [comment]
probably?

```
export let server_state

// not reactive
let local_state = server_state

// so no cyclic dep
// changes along with local_state
$: server_state = local_state

// and server_state reverts back on load
// while local_state doesn't
```

**Comment by benmccann** [comment]
This has always been a controversial feature. I wonder if we could turn it off, but let people re-enable it with `invalidate` https://github.com/sveltejs/kit/pull/1709 ?

**Comment by dummdidumm** [comment]
I'd say a flag with the `invalidate` logic you mentioned makes sense.

**Comment by csangonzo** [comment]
> Question is whether the default behavior should be on or off ...

I can only speak for myself, but I've been using sveltekit since day one and I always looked at `load` kind of like the part of the page's 'lifecycle', and if I think about it like that, I don't see the benefit of 'rerunning a lifecycle event' by default on a parameter change. But maybe that's just me.

**Comment by seanlail** [comment]
I vote for opt in. It's only in very rare cases I think I would need load to be reactive.

**Comment by seanlail** [comment]
Slightly related: Is the Sapper "preload" reactive? 

I'm not actually sure now but would this require an update to the migration doc too?

**Comment by csangonzo** [comment]
>  Is the Sapper "preload" reactive?

I don't think so, at least the sapper doc doesn't mention anything like that.

**Comment by benmccann** [comment]
Sapper's `preload` was also rerun when `session` changed and I remember people complaining about it there too

**Comment by Mlocik97** [comment]
I would go for part of return (as it affects load function itself),... and maybe also instead return whole page and session object instead strings, to tell which objects to invalidate, (not just name of object, but it's reference instead).

**Comment by rmunn** [comment]
I have a design proposal for session persistence and refreshing sketched out in https://github.com/sveltejs/kit/issues/1726#issuecomment-913295755. Part of that design includes the idea that `load()` would not re-run whenever you set the session value, e.g. `$session.user = loggedInUser` would not trigger a re-run of `load()`. But if you explicitly call `$session.refresh()`, and your page's `load()` function uses the value of its `session` parameter, then it would be re-run with the value that `$session.refresh()` returns if (and only if) that value was different from what the session store contained before calling `$session.refresh()`. (If you refresh the session on the client, and the server returns the exact same session data that the client already knew about, then you almost certainly wouldn't want the page reloading).

As far as I can tell from reading the discussion here, most people are surprised by `$session.user = loggedInUser` causing a page reload, but would be generally okay with the page reloading if its other params change (e.g., `/preview?itemID=123` and `/preview?itemId=456` are different pages and should cause the `load()` function to re-run). If so, then I think having `session` only trigger a reload after an explicit `$session.refresh()` call would fit your use cases.

For anyone who wants session assignment not to cause `load()` to re-run, would you be okay with it rerunning after an explicit call to `$session.refresh()`? Or would that still surprise you?

**Comment by csangonzo** [comment]
Sounds good!

**Comment by seanlail** [comment]
I just got burnt by this reactive session again and it's made me even more resolute that `load` should not run when the session changes.

Just had an idea, what if we use the `$`?

### No reactivity
```svelte
<script context="module">
  export function load({ page, session }) {
    return {
      status: 200,
      props: { id: page.params.id },
    };
  }
</script>
```

### Session reactive
```svelte
<script context="module">
  export function load({ page, $session }) {
    return {
      status: 200,
      props: { id: page.params.id },
    };
  }
</script>
```

### Page reactive
```svelte
<script context="module">
  export function load({ $page, session }) {
    return {
      status: 200,
      props: { id: $page.params.id },
    };
  }
</script>
```

### Session and Page reactive
```svelte
<script context="module">
  export function load({ $page, $session }) {
    return {
      status: 200,
      props: { id: $page.params.id },
    };
  }
</script>
```

Pros | Cons
--- | ---
Familiarity with current Sveltisms | The inverse is now confusing. `session` !== Writeable store.
Cleaner API | Implementing this is difficult (I assume?)
Easy on the eyes | Tooling would not support this (I assume?)
Nothing is reactive by default | Page should be reactive by default

**Comment by Mlocik97** [comment]
`$` prefix seems like short and simple to write, but I think it can be confusing, at because it can contain both prefixed and unprefixed, it can lead to bugs as someone will forget to add prefix in code, when changing existing code... I would not recommend this. `$` symbol is already used in two cases in Svelte, so it would not be good to add anothers, as it would be harder to beginners to understand what it means there, and what there.

**Comment by ramiroaisen** [comment]
Vote up to make it opt-in with `export const invalidate: InvalidateOpts = { session: boolean, page: boolean }` or something like that

**Comment by LucianVoju** [comment]
Hello,

Why not leaving the functionality as it is and use a derived  or custom store around session?

REPL ideas: https://svelte.dev/repl/fdbf426e0bd84855b8f88bc6c3b7f488?version=3.45.0

**Comment by tcc-sejohnson** [comment]
Just a quick note that the approach here that seems to be most accepted, `export const invalidate: InvalidateOpts`, has great precedent in the React world -- it's basically `useEffect`'s dependency array -- and `load` is already a lot like a page-level version of `useState` and `useEffect` combined. I personally think it's a great and easy-to-understand solution, and it'd make for a lot cleaner implementations of a couple of things for me.

**Comment by Mlocik97** [comment]
We are not React here.... I'm against `export const invalidate`

**Comment by tcc-sejohnson** [comment]
@Mlocik97 

I absolutely agree we're not React here, but I also think it'd be fallacious to say "It's like React, therefore it's bad and we don't want to do it." React does a lot of things well.

Can you clarify what abilities we would lose?

**Comment by Mlocik97** [comment]
I already explained how invalidate would give better control in load... in case of load, you can do something like:

```js
export async function load({ session, page, fetch }) {
    // some logic
   const shouldSessionInvalidate /* @type boolean */ = ...
    return {
        invalidate: shouldSessionInvalidate? { session } : {}
    }
}
```

that's impossible to do with `export const invalidate` case...

**Comment by tcc-sejohnson** [comment]
Absolutely agreed that it goes better in `load` than as an export. As a sidenote, that's actually _more_ similar to React's `useEffect` dependency array than the export. My intent behind the original comment was to voice support for "the ability to expose a dependency object to control rerun behavior" than "the specific implementation of exporting that object from the script block", but I didn't make that clear -- my bad on that! 🥲

**Comment by pooledge** [comment]
If using `session` precisely as described [here](https://github.com/sveltejs/kit/issues/2252#issuecomment-902713201) for 2 pages, let's say a login and account index page, bound by redirect to their counterpart, I am observeing both of them in DOM for a short amount of time after `session` has been updated.

I feel like rerun `load()` on load input change is a good idea overall, it's just that some edge cases like this occur, and suddenly an old good `goto()` would be way more comfortable. Opting in for an opt-in.

**Comment by dummdidumm** [comment]
The "`$session` causes props to be reset"-issue is tracked in #3732, more general discussion about load timing is discussed in  #2301. Closing as duplicates of those.
