### ISSUE TITLE
How can the server be notified of a hot module reload; import.meta.hot only works on client?

### ISSUE THREAD

**Issue by alexbjorlig** [sveltejs/kit#2255]
### Describe the bug

In my project we have a change event listener on a Mongodb change-stream. It works serverside, but when the module that registres the event listeners is hot reloaded, there is nothing in place to remove the old listeners.

To fix that it would be awesome to be able to do something like `import.meta.hot` - but on the server (so we can gracefully cleanup when hot reloading).

### Reproduction

Clone and npm install this repo [here](https://github.com/alexbjorlig/sveltekit-hot-reload-on-server).

You will never see the log statements from the `Header.svelte` `import.meta.hot` section.

### Logs

```shell
N/A
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
    Memory: 698.63 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.17.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Edge: 92.0.902.78
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.154 
    svelte: ^3.34.0 => 3.42.2
```

### Severity

serious, but I can work around it

### Additional Information

I currently workaround be NOT attaching the event listeners, if a certain env variable was configured.
It's not a nice work-around, but...

**Comment by Rich-Harris** [comment]
Agree that this could be a useful addition, but unfortunately it's out of scope for SvelteKit — this is something that would need to happen in Vite
