### ISSUE TITLE
Anchor hrefs inside SVG elements not getting handled properly by router

### ISSUE THREAD

**Issue by ptizzy** [sveltejs/kit#2256]
### Describe the bug

Anchor tags inside SVG elements cause a TypeError in the router, and fall through to browser navigation.  This results in a full page load.  The issue seems to be that SVG elements are SVGAnimatedStrings, and the href attribute is returned as an object.  I have resolved this issue locally by checking if the element is an SVG, and if so, accessing a.href.baseVal, and including document.baseURI in the URL constructor.  This has to be done inside the "click" event handler and the trigger_prefetch function.

I'm happy to submit a PR if this solution is acceptable.

### Reproduction

- Initialize Demo App
- Add SVG inline with anchor tag to index.svelte
- Click on SVG element

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
    Memory: 2.08 GB / 15.82 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.73)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.154
    svelte: ^3.34.0 => 3.42.1
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
Hey, thanks for digging into this. I'm not super familiar with this part of the code or how SVGs might be handled differently. I do see a few references to SVGs in [the router code](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/router.js) already, but I wouldn't be terribly surprised if there's a case that got missed somehow.

I'd say go ahead and send a PR so I can better see what exactly the issue is you're talking about and what you're proposing to change.

**Comment by stephane-vanraes** [comment]
I ran into the same problem, a 'decent' workaround is to hijack the clickevent and use `goto` to navigate the correct page, this will keep you inside the SvelteKit 'context', while still allowing navigating if javascript is disabled.

```svg
<a {href} on:click|preventDefault={() => goto(href)>
  <p d="...." />
</a>
```

**Comment by bluwy** [comment]
@ptizzy Will you be sending a pr to fix this? I can take a look at it _soon_ and make a fix as well (or anyone else).

To clarify the reason for this ambiguity, given:

```html
<a id="a" href="/foo" />
<svg>
  <a id="b" href="/foo" />
</svg>
```

```js
document.getElementById('a').href         // logs "http://localhost:3000/foo"
document.getElementById('b').href.baseVal // logs "/foo" <--- not full url
```

Because `b` isn't giving us the full url path, `new URL(href)` fails.

**Comment by ptizzy** [comment]
I gave it a shot.  In my testing, it handled absolute and relative paths correctly.  Let me know if you notice any issues, or feel I should take a different approach.
