### ISSUE TITLE
idea of having adapters like "Class" that can be overriden

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#2257]
### Describe the problem

let say, I don't want to write my own adapter, but just "override" small part of actual existing adapter. Now I need to copy manually all code and change one small simple thing. But wouldn't it be nice, to have ability to override implementation of adapter before passing it do config?

### Describe the proposed solution

give ability to override implementation of existing adapters (at least official ones).

### Importance

nice to have

**Comment by Conduitry** [comment]
This is a very open-ended and ill-defined feature. If there are specific things in particular adapters that people think should be configurable (not overridable) those should be their own issues. Making everything pluggable in every adapter sound like a lot of unnecessary work, resulting in confusing codebases and a lot of things to document.

**Comment by Mlocik97** [comment]
ok, I understand.
