### ISSUE TITLE
sveltekit npm publish error

### ISSUE THREAD

**Issue by shaozi** [sveltejs/kit#2263]
### Describe the bug

I use `npm run package` to generate the package folder, but when used the generated package, vite reports error:

```
[vite] Internal server error: Missing "." export in "svelte-steps" package
```

### Reproduction

Install my package:

```
npm install svelte-steps
```

Then in `index.svelte`:

```javascript
<script type="ts">
	import { Steps } from 'svelte-steps';
	let steps = [{ text: 'step 1' }, { text: 'step 2' }, { text: 'step 3' }];
</script>

<Steps {steps} />
```

and run `npm run dev -- --open`

You will see the error.

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 162.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.1 - /usr/local/bin/node
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.139 
    svelte: ^3.34.0 => 3.41.0
```

### Severity

annoyance

**Comment by ignatiusmb** [comment]
You'll need to have an `index.js` that re-export the components if you want to use named imports, please read https://kit.svelte.dev/docs#packaging again.

I see your package only has 2 svelte files in `src/lib`, you can also import them as usual using default imports, e.g., `import Steps from 'svelte-steps/Steps.svelte';`

**Comment by shaozi** [comment]
Nice. Thank you. it works. I added this `index.js`

```javascript
export { default as Steps } from './Steps.svelte'
```
