### ISSUE TITLE
Service worker breaks AMP validation

### ISSUE THREAD

**Issue by asendia** [sveltejs/kit#2264]
### Describe the bug

Issue: Creating `src/service-worker.ts` breaks AMP validation in Google Webmaster because svelte-kit injects custom `<script>` tag to install the service-worker.
<img src="https://user-images.githubusercontent.com/9080782/130347319-3434b5df-6301-408e-89f0-17c9542ab115.png" alt="webmaster error" width="400" />

Expected: svelte-kit should inject [amp-install-serviceworker](https://amp.dev/documentation/components/amp-install-serviceworker/) if `config.kit.amp` is `true` or let users to customize it.

PR: https://github.com/sveltejs/kit/pull/2265

### Reproduction

1. Create `src/service-worker.ts`
2. Set `config.kit.amp = true` in `svelte.config.js`
3. There will be no AMP validation error during development, but it will result on AMP entries being removed from google with the following error in Google webmaster dashboard: `Custom JavaScript is not allowed.`
Example: https://github.com/asendia/salmonfit/tree/f5aea01869760c83d57403a8cad3e1bfdee8e7aa

### System Info

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) arm64 Apple M1
    Memory: 228.31 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.1.0/bin/yarn
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.1
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.154 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

serious, but I can work around it

### Additional Information

Workaround that I did: ugly postinstall script to modify `ssr.js`: https://github.com/asendia/salmonfit/blob/3d9b0316a85c6164db01946529bc8b15d0ec31b8/scripts/replace-sw-amp.js

**Comment by benmccann** [comment]
@asendia what do you think about https://github.com/sveltejs/kit/pull/2281 as a fix for this? It allows you to turn off automatic service worker registration so that you can handle it yourself

I'm not terribly familiar with either AMP no service workers, so I don't fully understand the issue you're facing
