### ISSUE TITLE
`files` in `$service-worker` should contain prerendered files

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#2271]
Using `adapter-static` and the code:

```ts
import { files } from '$service-worker';
```

I expect to find also the `<NAME>.html` fallback file listed in `files`.

Am I wrong?

**Comment by ignatiusmb** [comment]
Please provide a complete and minimal reproducible example of what happen and should've happen.

**Comment by Mlocik97** [comment]
this is specific for adapter, so it's not good if it's provided by `$service-worker`, why You don't simply add manually that file to it? It's just one line of code.

**Comment by benmccann** [comment]
For fallback we can add just the one. For prerendered files there might be too many to do this. We'd have to have the adapter generate the manifest after prerendering I guess?

**Comment by benmccann** [comment]
SvelteKit's own service worker should contain prerendered files now. Unfortunately, it still doesn't happen early enough in the build process that plugins like `vite-plugin-pwa` could pick them up
