### ISSUE TITLE
Webcomponents from CDN do not show 

### ISSUE THREAD

**Issue by Tommertom** [sveltejs/kit#2272]
### Describe the bug

Hi
I tried adding UI components from CDN (Ionic library) and they do not show on the page, although they are loaded in the DOM. They briefly pop-up and then disappear. These are webcomponents - not sure if that makes a difference for sveltekit?

This behaviour I earlier saw with SAPPER but does not appear when using a plain SVELTE project. So maybe related to router or other goodies added to the svelte sweetness?

### Reproduction

See git repo:

https://github.com/Tommertom/svionic

The CDN is added in app.html:

```
<script type="module" src="https://cdn.jsdelivr.net/npm/@ionic/core@5.4.0/dist/ionic/ionic.esm.js"></script>
<script nomodule src="https://cdn.jsdelivr.net/npm/@ionic/core@5.4.0/dist/ionic/ionic.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ionic/core@5.4.0/css/ionic.bundle.css" />

```

The UI components are in index.svelte
```
<ion-chip>sadasds</ion-chip>
<ion-button on:click={() => console.log('asdsadsads')}>sadsasd</ion-button>

```

The behaviour can be see in this clip: https://www.youtube.com/watch?v=cjzYMQpZMd8
I am refreshing the page and after the refresh, the components do no longer show

(ran using `npm run dev -- --open`)

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 6.69 GB / 13.88 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.14 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.155
    svelte: ^3.34.0 => 3.42.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The CDN can work with Svelte...
https://ionicsvelte.firebaseapp.com/ionic/Slides

**Comment by benmccann** [comment]
Hydration is removing them because they're not rendered by Svelte. Svelte expects to control the DOM. This isn't really a bug, but a usage issue, so would probably be a better question for Discord. I haven't tried to do something like what you're attempting before, so you'd be more likely to find someone with ideas on Discord

**Comment by Tommertom** [comment]
Hi @benmccann . Thx for the reply. So, just out of curiosity, why does it work in a svelte project not using sveltekit? So the svelte starter template?

**Comment by benmccann** [comment]
svelte starter template doesn't do SSR or hydration. you can turn SSR off in SvelteKit if you want behavior more similar to svelte starter template

**Comment by Tommertom** [comment]
Ok thx for the explanation.

**Comment by Rich-Harris** [comment]
For posterity, updating this thread with more detail: the reason this fails is because Ionic adds classnames to custom elements when they are upgraded; the classnames are removed during hydration: https://github.com/sveltejs/kit/issues/5143#issuecomment-1190843804

**Comment by Tommertom** [comment]
Cross link to issue @ Ionic Framework  https://github.com/ionic-team/ionic-framework/issues/22345

**Comment by dummdidumm** [comment]
A possible workaround (haven't tested this): register the custom elements after a small timeout. By then, Svelte should have done the hydration, and upgrading the components is no longer reverted.

**Comment by dominikg** [comment]
other options to wait until after hydration:

- the `sveltekit:start` event: https://kit.svelte.dev/docs/events
- `onMount` hook: https://kit.svelte.dev/faq#integrations-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

**Comment by Tommertom** [comment]
Thx @dominikg  and @dummdidumm for the suggestions.

So trying to reinitialise Ionic webcomponents in onMount (__layout) does not yield results...

`<script lang="ts">
	import Header from '$lib/header/Header.svelte';
	import { onMount } from 'svelte';
	import '../app.css';

	onMount(async () => {
		//	const { initialize } = await import('@ionic/core/components'); // this is from the Ionic lib itself
		//	initialize();
		const { setupIonicSvelte } = await import('$lib/ionic/svelte'); // this is from a lib I made myself that reregisters the customer components  https://github.com/Tommertom/svelte-ionic-app/blob/main/src/lib/ionic/svelte/index.ts
		setupIonicSvelte();
	});
</script>

<slot />`

The dom is filled with elements, made invisible, and the styling gone.

Something I am not doing right?
