### ISSUE TITLE
CSS not initially loading when pushed to Netlify (mobile)

### ISSUE THREAD

**Issue by billpliske** [sveltejs/kit#2273]
### Describe the bug

Using the Netlify adapter.  When I view my Sveltekit site  live on Netlify, **_on initial load, there's no styling._** 
If I refresh my phone browser, the style then loads.

After some digging, I noticed folks complaining about similar issues, but with stuff like Hugo or Gatsby.

Their solution also worked for Sveltekit.
In your `jsconfig.json` file, update your baseUrl from `"baseUrl": "."` ... to `"baseUrl": "/"`

**_Just mentioning this in case you thought it was worth adding to the docs._**

### Reproduction

1.  Build simple Sveltekit static app.
2. Deploy to Netlify.
3. Open on mobile device (I had a PIxel 4a)

### System Info

```shell
System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 22.26 GB / 24.88 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.4 - ~/.nvm/versions/node/v14.17.4/bin/node
    Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v14.17.4/bin/npm
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.154 
    svelte: ^3.34.0 => 3.42.2
```

### Severity

annoyance

**Comment by ignatiusmb** [comment]
Can you share the link where updating `baseUrl` fixed the issue?

**Comment by billpliske** [comment]
Apologies. This was where I discovered the link:
https://answers.netlify.com/t/css-not-loading/17773

And sure enough, I tried it out on my own static site repo, and the initial
css has now loaded every time.

**Comment by benmccann** [comment]
That forum post looks totally unrelated. It's about setting a Hugo option: https://gohugo.io/getting-started/configuration/#baseurl

The option you found is about setting how VS Code handles the files: https://www.typescriptlang.org/tsconfig#baseUrl

They don't have anything to do with one another, so I closed the PR because I don't think it's the right solution

**Comment by billpliske** [comment]
Appreciate you at least looking into it.
