### ISSUE TITLE
Dynamic import of JS fails if other dynamic import of CSS is present

### ISSUE THREAD

**Issue by vwkd** [sveltejs/kit#2275]
### Describe the bug

When building a page that dynamically imports JavaScript *and* CSS, the dynamic JavaScript import will fails. Dynamically importing only JavaScript works fine. But when *also* dynamically importing CSS, the dynamic JS import fails.

This issue occurs only when building for production (`npm run build`), and not when running the development server (`npm run dev`).

I tracked it down to the JS script being imported twice in the built file. The second import has a wrong hash pointing to a file that doesn't exist. The server then correctly responds with a 404 HTML which makes the import throw because it expected JS.

For example, a page has dynamic imports like this

```
await import("mod.js");
await import("some.css");
```

Building it will generate a `[page].svelte-[hash].js` with a piece of code similar to the following

```
async function p() { 
    await s((() => import("../chunks/mod-50221c7b.js")), []),
    await s((() => import("../chunks/mod-b7268ec5.js")), []),
}
```

The second file doesn't exist and hence fails the import because it throws on the received 404 HTML file from the server.

Deleting this second import manually fixes it.

### Reproduction

See https://github.com/vwkd/sveltekit-bugs/tree/dynamic-import

1. Run `npm run build && npm run preview`
2. Click "Load modules" button
3. Observe no text color change console error (modules not loaded)

You see the second erroneous import failing in the network tab

<img width="613" alt="network" src="https://user-images.githubusercontent.com/33468089/130519458-2d7e5ec7-0907-439e-9e65-bb18d5ffd8a1.png">

Note, this issue occurs only when building for production.

1. Run `npm run dev`
2. Click "Load modules" button
3. Observe text color green and successful console log (modules loaded)

### System Info

```shell
System:
    OS: macOS 11.5
  Binaries:
    Node: 16.6.0 - ~/.nvm/versions/node/v16.6.0/bin/node
    npm: 7.19.1 - ~/.nvm/versions/node/v16.6.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.11 => 1.0.0-next.16 
    @sveltejs/kit: next => 1.0.0-next.144 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
This is probably caused by Vite. Can you file it in their issue tracker instead? We're unlikely to be able to do anything about it directly in Kit

For more details, see https://github.com/sveltejs/kit#bug-reporting
