### ISSUE TITLE
[Static Adapter] Absolute file paths in generated HTML files

### ISSUE THREAD

**Issue by Uni2K** [sveltejs/kit#2278]
### Describe the bug

When building the sveltekit app with the static adapter, the generated index.html inside /build/ contains only absolute links.  However, trying to run index.html leads to tons of errors because the absolute file paths cannot be resolved.

	<link rel="modulepreload" href="/_app/start-47ad7042.js">
	<link rel="modulepreload" href="/_app/chunks/vendor-986c0c4e.js">
	<link rel="modulepreload" href="/_app/pages/__layout.svelte-76e90a6f.js">
	<link rel="modulepreload" href="/_app/pages/index.svelte-3ba9ed59.js">
	<link rel="modulepreload" href="/_app/chunks/Footer-4274319b.js">
	<link rel="stylesheet" href="/_app/assets/start-61d1577b.css">
	<link rel="stylesheet" href="/_app/assets/vendor-a0137619.css">
	<link rel="stylesheet" href="/_app/assets/pages/__layout.svelte-9da8ffa3.css">
	<link rel="stylesheet" href="/_app/assets/pages/index.svelte-1280cda4.css">
	<link rel="stylesheet" href="/_app/assets/Footer-5bd6e039.css">

The solution would be to just insert the a dot before the starting / :
`<link rel="modulepreload" href="./_app/start-47ad7042.js">`

The given errors are related to CORS, since the path is pointing to the current drive ("D") in this case:
![errors](https://user-images.githubusercontent.com/20185223/130598442-53f2db84-09b1-470f-bf52-157d5909ce15.PNG)

I am using the default configuration for the adapter. I wonder if this is intended or if there is a solution other than manually fixing all the paths.

### Reproduction

The adapter: `adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null
		})`

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 5.80 GB / 15.88 GB
  Binaries:
    Node: 14.16.1 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.2 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.17 => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.156
    svelte: ^3.34.0 => 3.42.2
```

### Severity

serious, but I can work around it

**Comment by ignatiusmb** [comment]
Build output are meant to be served through a live server and not with the file protocol. Either run a http server or use something like `npx serve`

**Comment by icanotc** [comment]
is there an option to use the file protocol? it seems like it's also broken with Github pages.
