### ISSUE TITLE
Adapter for `express-session` `connect-redis` support

### ISSUE THREAD

**Issue by tunailgaz** [sveltejs/kit#2279]
### Describe the problem

I am using stelve-kit with typescript.
I really love the framework, however couldnt find how to save session at server side with using existing libraries.
Like express.js I just want to use `express-session` and `connect-redis` libs so I can provide server side data to user with hooks.

I tried to edit adapter-node but kinda failed.

### Describe the proposed solution

I am not sure what is the best way to do that but probably with a custom adapter which runs express server with those middlewares.

### Alternatives considered

Writing a new library? I dont think so

### Importance

i cannot use SvelteKit without it

**Comment by ShahrukhAhmed89** [comment]
Did you happen to find a solution for this? Stuck in a similar issue.
