### ISSUE TITLE
Code breaks when using curly braces for single import

### ISSUE THREAD

**Issue by justingolden21** [sveltejs/kit#2287]
### Describe the bug

this broke my entire app:
`import { Modal } from '../components/Modal.svelte';`
removing the braces fixed it:
 `import Modal from '../components/Modal.svelte';`
but for some reason it works with `npm run preview` but not `npm run build`

the component is literally just `<slot></slot>` and not currently used in the page

The error I get when I have the curly braces is: `__layout.svelte:7 Uncaught (in promise) SyntaxError: The requested module '/src/components/Modal.svelte' does not provide an export named 'Modal'`

### Reproduction

Basic svelte kit boilerplate plus an empty component

### System Info

```shell
C:\Users\Justin>npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 7.09 GB / 15.95 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)


C:\Users\Justin>
```

### Severity

annoyance

### Additional Information

When using the component (again, even if it's entirely empty) the entire app refuses to load and I get the error that it's not a valid SSR component. I have other components that work perfectly fine. Took a few hours to debug this lol. I tried clearing cache and hard refreshing, incognito, stopping and starting `npm run dev`, the works...

Thanks for looking into this

**Comment by dummdidumm** [comment]
This works as designed, and the error is right. The Svelte component itself is the default export, named exports are exports from the module script.

**Comment by justingolden21** [comment]
> This works as designed, and the error is right. The Svelte component itself is the default export, named exports are exports from the module script.

But the errors given are completely unrelated. I get anything from it's not a valid SSR component (and led down the path that I need to make it work with SSR) and that it can't find a modal component. I went on the svelte discord and spent hours debugging this with several experienced svelte devs. If the error message made any sense at all then maybe this would be a thirty second fix.

I understand why it broke after the fact now, but the error message should be changed imo.

**Comment by dummdidumm** [comment]
You only posted the error message `__layout.svelte:7 Uncaught (in promise) SyntaxError: The requested module '/src/components/Modal.svelte' does not provide an export named 'Modal'` which is very descriptive in my opinion.

**Comment by justingolden21** [comment]
My mistake for not mentioning, the first error I came across was:

```cmd
Error: <Modal> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
    at Proxy.validate_component (C:\Users\Justin\Documents\GitHub\desktopclock\node_modules\svelte\internal\index.js:1654:15)
    at eval (C:\Users\Justin\Documents\GitHub\desktopclock\src\routes\__layout.svelte:49:29)
    at Object.$$render (C:\Users\Justin\Documents\GitHub\desktopclock\node_modules\svelte\internal\index.js:1677:22)
    at root.svelte:36:44
    at $$render (C:\Users\Justin\Documents\GitHub\desktopclock\node_modules\svelte\internal\index.js:1677:22)
    at Object.render (C:\Users\Justin\Documents\GitHub\desktopclock\node_modules\svelte\internal\index.js:1685:26)
    at render_response (file:///C:/Users/Justin/Documents/GitHub/desktopclock/node_modules/@sveltejs/kit/dist/ssr.js:472:28)
    at async respond_with_error (file:///C:/Users/Justin/Documents/GitHub/desktopclock/node_modules/@sveltejs/kit/dist/ssr.js:1108:10)
    at async respond$1 (file:///C:/Users/Justin/Documents/GitHub/desktopclock/node_modules/@sveltejs/kit/dist/ssr.js:1336:10)
    at async render_page (file:///C:/Users/Justin/Documents/GitHub/desktopclock/node_modules/@sveltejs/kit/dist/ssr.js:1386:19)
    ```

Which is what I was stuck on for several hours.

**Comment by bluwy** [comment]
@justingolden21 as mentioned in discord, that's because the library did not properly export the svelte component. If any, you should open an issue in the library's repo instead of here.
