### ISSUE TITLE
Allow some script output without router + hydration

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#2303]
### Describe the problem

For a simple blog where each page is SSR'd and there's no need for the router or hydration, turning both off also disables any per-component scripts - extra effects that toggle menus for instance.

Right now I have to enable hydration, which then repeats all the serialized JSON of the content even though it isn't used OR I have to switch to using some other JS lib such as alpine or custom JS to add menu toggles, which feels wrong when I'm already using the best JS framework there is.

### Describe the proposed solution

I would like the `hydrate: false` option to just turn off the JSON serialization and re-hydration parts, without also removing the regular svelte scripts. I understand the onus is then on me not to use something

### Alternatives considered

Writing JS manually as static content

### Importance

nice to have

**Comment by Rich-Harris** [comment]
Hydration in SvelteKit is currently all-or-nothing — there's no way to attach event handlers that toggle menus without hydrating the app, and you can't hydrate the app without the page's data. In the longer term we'd like to improve the story around hydration (making it faster, non-blocking, and _maybe_ partial) but for now I'm afraid this isn't possible.
