### ISSUE TITLE
[cloudflare adapter] Can't set multiple cookies

### ISSUE THREAD

**Issue by half2me** [sveltejs/kit#2305]
### Describe the bug

When setting multiple cookies from `hooks` in the `handle` function, I have the following code:
```js
return {
  // rest of response
  headers: {
    'set-cookie': ['cookie1', 'cookie2'],
  },
}
```

When using the node adapter, it correctly uses separate entries in the returned headers for each cookie.
```
set-cookie: cookie1
set-cookie: cookie2
```

However when running on cloudflare workers, with the cloudflare adapter, the cookies are merged into a single entry:
```
set-cookie: cookie1,cookie2
```

This results in only one cookie being set.

### Reproduction

Return multiple cookies and use the `@sveltejs/adapter-cloudflare-workers` adapter

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 407.40 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - /usr/local/bin/node
    npm: 7.21.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.0.0-next.19 => 1.0.0-next.19 
    @sveltejs/adapter-node: ^1.0.0-next.43 => 1.0.0-next.43 
    @sveltejs/kit: next => 1.0.0-next.158 
    svelte: ^3.34.0 => 3.42.3
```

### Severity

blocking all usage of SvelteKit

**Comment by half2me** [comment]
Thanks @JeanJPNM this works perfectly. I'll be using this as a workaround for now. Reckon this behaviour could be made default?

**Comment by JeanJPNM** [comment]
Ok, I will make a pull request

**Comment by benmccann** [comment]
Won't `result.append(header, sub);` make it so that there's just a single header for `Set-Cookie`? I thought that's what @half2me was complaining about in the issue description

**Comment by JeanJPNM** [comment]
Yes, it technically does the same thing, but for some reason it works

**Comment by benmccann** [comment]
I guess it's because headers takes a bytestring and not a `string[]`: https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers#parameters
