### ISSUE TITLE
Disable SSR (and CSR!)

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#231]
People often ask for SPA mode. We could do the following:

```js
// svelte.config.js
module.exports = {
  adapter: '@sveltejs/adapter-node',
  serverSideRendering: false
};
```

(`serverSideRendering: false` might seem nonsensical in the context of adapter-node — why not just use adapter-static? — but we might still have dynamic endpoints, so it's something that should probably work with all adapters.)

Less commonly, people ask to disable client-side rendering (i.e. they just want SSR'd HTML, no interactivity) or at least client-side routing.

So we could have three new options that all default to `true`:

* `serverSideRendering`
* `clientSideRendering`
* `clientSideRouting`

At least one of `serverSideRendering` or `clientSideRendering` would have to be true, and `clientSideRouting` couldn't be false if `serverSideRendering` was false.

**Comment by isgj** [comment]
Is it reasonable that the first steps for this feature will be
1. make https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/router.js able to start on the browser depending on the path
2. add to https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/adapt/Builder.js a method that will output (copy) a `.html` file without rendering the part of the target of `app.html`, and that in the script part will use the router as in point 1

?

**Comment by benmccann** [comment]
To do only client-side rendering , I was thinking you'd want to skip running the `load` functions, etc. and just render the template (to replace `%svelte.head%`, etc.), which starts about here:

https://github.com/sveltejs/kit/blob/13f23e116b750d00f7cee6642b5f75138907d8ff/packages/kit/src/runtime/server/page.js#L334

**Comment by lukasIO** [comment]
> 
> To do only client-side rendering , I was thinking you'd want to skip running the `load` functions, etc. and just render the template (to replace `%svelte.head%`, etc.), which starts about here:

For this proposal I was expecting the `load` function to still run on the client in order to fetch dynamic content from any endpoint, while still being able to deploy the site to let's say a shared web hoster that does not support nodejs.

**Comment by benmccann** [comment]
Yes, I was referring only to server-side `load`

**Comment by regnaio** [comment]
> > To do only client-side rendering , I was thinking you'd want to skip running the `load` functions, etc. and just render the template (to replace `%svelte.head%`, etc.), which starts about here:
> 
> For this proposal I was expecting the `load` function to still run on the client in order to fetch dynamic content from any endpoint, while still being able to deploy the site to let's say a shared web hoster that does not support nodejs.

Since this has been closed, is this now possible?

How can we go about doing this?
