### ISSUE TITLE
moment.js locale not working

### ISSUE THREAD

**Issue by efeerdogru** [sveltejs/kit#2314]
### Describe the bug

While using moment.js, locale is not working on client side.

### Reproduction

Create demo app.

```shell
npm init svelte@next my-app
```

Install moment.js

```shell
npm i -D moment
```

Add these to `index.svelte` file

```js
import moment from "moment";
import "moment/locale/tr";
console.log(moment(Date.now()).locale("tr").format("L LT"));
```

Run and see logs:

```shell
npm run dev -- --open
```

### Logs

```shell
Server log:

28.08.2021 15:48


Client (browser) log:

08/28/2021 3:48 PM
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 18.03 GB / 31.85 GB
  Binaries:
    Node: 16.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.78)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.158
    svelte: ^3.34.0 => 3.42.4
```

### Severity

annoyance

**Comment by benmccann** [comment]
You really shouldn't use Moment.js: https://momentjs.com/docs/#/-project-status/

This isn't something we'd really investigate because it's not clear there's any issue in SvelteKit and it's related to a deprecated library that no one should be using anyway
