### ISSUE TITLE
Turning off router does not turn off link checking

### ISSUE THREAD

**Issue by danawoodman** [sveltejs/kit#2329]
### Describe the bug

From my understanding, setting `router: false` should stop client side navigation and thus link checking. Doing this however, still checks links and fails the build if you have a link that SvelteKit is not aware of. 

I would hope that Kit will just ignore links from link checking if `router: false` is set since it is possible for the these links to be perfectly valid. 

Setting `rel="external"` for all of them is onerous and not always possible. 

### Reproduction

Set `router: false` and use adapter-static, then setup a link that is a potential 404 (say `/foo`). Running `npm run build` throws an error.

Repro: https://github.com/danawoodman/sveltekit-link-checking-bug

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 135.39 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/fnm_multishells/42995_1630345044758/bin/node
    npm: 7.15.1 - /var/folders/j4/3_1h9_mn6w5g4p438nym2vl40000gn/T/fnm_multishells/42995_1630345044758/bin/npm
  Browsers:
    Brave Browser: 92.1.28.106
    Chrome: 92.0.4515.159
    Firefox: 91.0.1
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.17 => 1.0.0-next.17 
    @sveltejs/kit: 1.0.0-next.159 => 1.0.0-next.159 
    svelte: 3.42.4 => 3.42.4
```

### Severity

annoyance

**Comment by benmccann** [comment]
I'm not sure what you mean by link checking. I guess pre-rendering? But pre-rendering and client-side routing are different features. Pre-rendering shouldn't be disabled by disabling client-side routing, so this sounds like it's working as intended

**Comment by danawoodman** [comment]
I mean that Kit seems to want to check whether a given relative URL points to a valid page and if it thinks the page is not valid because it doesn't know the route, the build fails. Eg if I have a link going to /foo but there is no foo.svelte, the build fails. I want to disable this "link checking" behavior

**Comment by benmccann** [comment]
It's not clear to me what the usecase is. At least in the example it seems helpful to let you know there's a dead link

But if you want to change the behavior you should be able to do so with the `onError` option: https://kit.svelte.dev/docs#configuration-prerender

**Comment by danawoodman** [comment]
@benmccann thanks for the link, I will check this out. 

It is a strange use case, I will admit that, but I have other relative routes that are controlled by a system that Kit is running within and thus I want to turn off the router and this link checking. If I can accomplish this with the `onError` handler, I will just use that 😄

**Comment by danawoodman** [comment]
Ok, this worked for me I believe! For anyone needing similar, I did the following:

```js
const config = {
  kit: {
    // ...
    prerender: {
      onError: (error) => {
        if (error.status === 404) return;
        throw error;
      },
    },
  },
}
```

Thanks again @benmccann 🙇
