### ISSUE TITLE
Unicode characters in routes don't work in dev mode

### ISSUE THREAD

**Issue by noahsalvi** [sveltejs/kit#2331]
### Describe the bug

Unicode characters in routes don't work in dev mode. To be precise they work in ssr but not when hydrated.

### Reproduction

https://github.com/noahsalvi/kit-umlaut-repro-v2

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 103.33 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.18.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Edge: 91.0.864.71
    Firefox: 91.0.2
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.159 
    svelte: ^3.34.0 => 3.42.4
```

### Severity

blocking an upgrade

**Comment by rmunn** [comment]
Try with version 1.0.0-next.160 of svelte-kit. There's a fix related to URL decoding in the changelog, and when I ran your repro repo in 159 it failed, but in 160 the `/ü` route loaded just fine. So this may already be fixed.

**Comment by noahsalvi** [comment]
> Try with version 1.0.0-next.160 of svelte-kit. There's a fix related to URL decoding in the changelog, and when I ran your repro repo in 159 it failed, but in 160 the `/ü` route loaded just fine. So this may already be fixed.

When I posted this issue, there was no version 160, I guess the problem got fixed but they forgot to update this issue.

Either way it works now, thanks for telling me :)
