### ISSUE TITLE
Watch mode for package command

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/kit#2333]
### Describe the problem

Some people use SvelteKit to create a package but use/test this package in a different environment than the `routes` folder in the same project. For them to get updates, they have to run the package command over and over again or write a custom script for that, which might not work for windows users. Details: https://github.com/sveltejs/component-template/issues/29#issuecomment-908589456

### Describe the proposed solution

Add a `--watch` option to the package command which rebuilds the package without deleting its top level folder

### Alternatives considered

Don't add it, but at least don't delete the top level folder (only empty its content) so that the changes are properly picked up by watchers.

### Importance

nice to have

**Comment by mechadragon01** [comment]
I have tried using the `svelte-package --watch` command and it works to detect changes.
- Successfully get `dist` directory from my file changes in `src/lib`.
 
But it crashes on any changes with syntax issues which renders it kind of useless for dev purposes. Can the` --watch` flag be more robust in the sense it doesn't crash on any non-perfect change or you don't need to fix the syntax immediately.
