### ISSUE TITLE
Adding <body> CSS classes and <html> attributes

### ISSUE THREAD

**Issue by miohtama** [sveltejs/kit#2336]
### Describe the problem

Some CSS styling techniques and external JavaScript integrations require one to add classes on `<body>`.

I do not know if this is possible because the current`%svelte.body%` is wrapped within the `<div>` (at least on the starter template):

```html
	<body>
		<div id="svelte">%svelte.body%</div>
	</body>
```

Another common feature is add attributes on `<html>` itself, like `<html lang="fi">`. This is especially important for SSR pages, as locale specific SEO optimisations are somewhat important.

I see this otpic been discussed in Svelte issue tracker before:

* https://github.com/sveltejs/svelte/issues/3105
* https://github.com/sveltejs/svelte/issues/1133
* https://github.com/sveltejs/svelte/issues/6620

 

### Describe the proposed solution

Because the SvelteKit has the concept of a [page](https://kit.svelte.dev/docs#routing-pages) the issue could be solved on a page level, making the solution more straightforward than a generic Svelte solution.

[Output](https://kit.svelte.dev/docs#loading-output) could contain hooks allowing modifying both `<html>` and `<body>`. 

I do not, however, know if Svelte internals has enough flexibility to allow this.

### Alternatives considered

Solve this issue on Svelte level. However, it seems like there hasn't been any progress on this over two years.

### Importance

nice to have

**Comment by Mlocik97** [comment]
> I do not know if this is possible because

so You create issue about "BUG/feature" that You don't even know if exist in Svelte? Well, You know, this issue is already solved, because it works. The problem is only HTML attributes that are already covered by other issues and also RFC: https://github.com/sveltejs/rfcs/pull/55

so this issue is totally useless.

**Comment by benbender** [comment]
Just as a quicktip (apart from svelte): You have javascript on your hand. You have access to the `document`. Nothing in the world hinders you from just do something like ```document.getElementsByTagName("body")[0].classList.add("foo")``` or similar...

**Comment by PaulMaly** [comment]
@benbender actually, SSR has hindered you from just use DOM API, because SvelteKit is also about isomorphic/universal applications, so we need to have the ways to do some things on both - client and server - sides universally.

**Comment by miohtama** [comment]
FYI there now exists (svelte-body)[https://www.npmjs.com/package/svelte-body] package.

I consider this issue closed with this addon package.
