### ISSUE TITLE
[create-svelte] provide command line params to run `npm init svelte` non-interactively

### ISSUE THREAD

**Issue by opensas** [sveltejs/kit#2348]
### Describe the problem

I want to create a new SvelteKit app programatically, but I have to interact with the script to choose options

### Describe the proposed solution

svelte-create should allow to specify options using command line parameters, like this:

```
-y || --no-interaction
-d || --demo-app
-s || --skeleton
-t || --ts || --no-ts
-e || --eslint || --no-eslint
-p || --prettier || --no-prettier
```

### Alternatives considered

can't think of any

### Importance

would make my life easier

### Additional Information

inspiration take from https://github.com/rossyman/svelte-add-jest#%EF%B8%8F-options

**Comment by Conduitry** [comment]
This has come up before but I can't find the issue right now.

My comment before was that I'm worried about committing to what is effectively a public API for this, with the potential for breaking changes. If we want to add other options, would it mean that previously non-interactive invocations of the command (with certain CLI options) would suddenly become interactive? That doesn't sound desirable, but neither does bumping a major version whenever we do something that might disrupt people attempting to use this in a non-interactive way.

We have a lot more freedom to adjust and improve the CLI if we make sure that it's only humans interacting with it, who can respond to prompts that change over time. If you have a need for non-interactive and reproducible starter projects, you should probably just run the CLI once yourself and save that somewhere and use that going forward.

**Comment by opensas** [comment]
Thanks a lot for pointing this out, I haven't though about it as a public API, but it really is.
I think one way to prevent, or at least attenuate, the effect of adding options would be to make all optiond default to NO when running non-interactively. That is, unless specified otherwise, `npm init svelte@next -y` command would create a completely barebone sveltekit app, and you would have to pass parameters to add features.
That way, when eventually new feature are added, the default behaviour would be the same.
Right now, all the interactive settings have a "no" default, and you have to opt in. (except the "which app template to use" that defaults to SvelteKit demo app, but could default to a barebones SvelteKit project. Anyway, the defaults for the interactive mode could differ from the non-interactive one, of course.
I think it's a nice feature to automatize the creation of apps, building scrtips, reporting errors, writing tutorials, etc.

**Comment by babichjacob** [comment]
> This has come up before but I can't find the issue right now.

https://github.com/sveltejs/kit/pull/1231


@opensas what you want currently exists with `svelte-add`'s app initializer:
```js
npm init @svelte-add/kit@latest my-new-app -- --with typescript+eslint
```
for example.

**Comment by opensas** [comment]
Thanks a lot @babichjacob , that's exactly what I was looking for.

Could you tel me where are all available options documented?

BTW, I thinks svelte adders are one of sveltekit's killer features, GREAT JOB! I hope it gets properly documented (and promoted) once the stable version is released. It's really great to have all this common tasks already solved and supported by the community.

**Comment by ppo** [comment]
> Could you tel me where are all available options documented?

`--demos true|false` => template default|skeleton ([source](https://github.com/svelte-add/svelte-add/blob/062154a5f6e723987a4d8b69b3894965b7869436/projects/svelte-add/index.js#L223))
`--with typescript+eslint+prettier+playwright+vitest` (source: trace the use of `passedFeatures` [here](https://github.com/svelte-add/svelte-add/blob/062154a5f6e723987a4d8b69b3894965b7869436/projects/svelte-add/index.js#L84)). _Note: `vitest` is not handled, see [here](https://github.com/svelte-add/svelte-add/blob/main/projects/create-kit/__init.js#L14))_

You can see the parameters here: [svelte-add/projects/create-kit/__init.js](https://github.com/svelte-add/svelte-add/blob/main/projects/create-kit/__init.js)  
That are coming from [here](https://github.com/svelte-add/svelte-add/blob/062154a5f6e723987a4d8b69b3894965b7869436/projects/app-initializer-tools/index.js#L60) (to see the real CLI names)

  The actual parameters in `create-svelte`: [`kit/packages/create-svelte/bin.js`](https://github.com/sveltejs/kit/blob/%40sveltejs/package%401.0.1/packages/create-svelte/bin.js) at lines [51-125](https://github.com/sveltejs/kit/blob/%40sveltejs/package%401.0.1/packages/create-svelte/bin.js#L51-L125) and/or [133-160](https://github.com/sveltejs/kit/blob/%40sveltejs/package%401.0.1/packages/create-svelte/bin.js#L133-L160).

**Comment by gurjeet** [comment]
One can automate the interactions with `sv` command using the unix command `expect`. Below is a sample session that I used to automate the interaction with current version (0.9.2) of SvelteKit.

```
frontend_dir="$PWD/del"

expect <<EOF
spawn npx sv create --template minimal --types ts --install npm --no-add-ons "$frontend_dir"
#expect "Ok to proceed?"
send "\\r"
set timeout -1
expect "You're all set"
expect eof
EOF

expect <<EOF
spawn npx sv add --cwd "$frontend_dir" --install npm --no-git-check prettier eslint vitest playwright tailwindcss sveltekit-adapter
expect "What do you want to use vitest for"
send "\\r"
send " "
expect "tailwindcss: Which plugins would you like to add"
send "j"
send " "
send "\\r"
expect "sveltekit-adapter: Which SvelteKit adapter would you like to use"
send "j"
send "\\r"
set timeout -1
expect "You're all set"
expect eof
EOF

```
