### ISSUE TITLE
`query` accessible from page store during prerendering, but shouldn't be

### ISSUE THREAD

**Issue by ssssota** [sveltejs/kit#2361]
### Describe the bug

Building with `sveltejs/adapter-static` does not give me the correct query.

`svelte-kit dev` and `svelte-kit preview` work fine.

However, if I build with `@sveltejs/adapter-static`, I don't get the correct query parameters.
Especially after a reload.

### Reproduction

https://github.com/ssssota/sveltekit-static-query

### System Info

```shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 8.18 GB / 15.93 GB
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 92.0.4515.159
    Edge: Spartan (44.19041.1023.0), Chromium (92.0.902.84)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18
    @sveltejs/kit: next => 1.0.0-next.162
    svelte: ^3.42.4 => 3.42.4
```

### Severity

serious, but I can work around it

### Additional Information

I think the hydrate part of the initialization is suspicious.

*[/build/index.html](https://github.com/ssssota/sveltekit-static-query/blob/gh-pages/index.html#L18-L41)*
```js
import { start } from "/_app/start-19affe50.js";
start({
	target: document.querySelector("#svelte"),
	paths: {"base":"","assets":""},
	session: {},
	host: location.host,
	route: true,
	spa: false,
	trailing_slash: "never",
	hydrate: {
		status: 200,
		error: null,
		nodes: [
			import("/_app/pages/__layout.svelte-e8a46f20.js"),
			import("/_app/pages/index.svelte-9233398d.js")
		],
		page: {
			host: location.host, // TODO this is redundant
			path: "/",
			query: new URLSearchParams(""), /* 🤔 */
			params: {}
		}
	}
});
```

**Comment by ssssota** [comment]
#2316 may have the same problem.

**Comment by ssssota** [comment]
#669 may be the same problem.
But we can reproduce it, so we don't know why this is closing.

**Comment by ssssota** [comment]
https://github.com/sveltejs/kit/issues/669#issuecomment-848988844

I read this comment and understand.

But isn't this specification unfriendly?
I can't find any documentation that mentions it, even though there are several similar issues (#1218 #1737 #2045 #2316 ).

**Comment by benmccann** [comment]
Ah, https://github.com/sveltejs/kit/pull/2104 only stopped you from doing it in `load`, but you're accessing it from the page store, which wasn't updated

> But isn't this specification unfriendly?

It doesn't really make sense any other way. I'm not really sure what you're trying to do, but I'm not sure how it'd work any other way than to disallow it

**Comment by ssssota** [comment]
@benmccann 
Thank you for the reply and quick response.
Please forgive me for making this Issue before I found #669, and for not understanding the exact problem.

**Comment by benmccann** [comment]
No problem. I appreciate that you made this. There was an issue on our end that we didn't alert you to the fact that it's not possible

**Comment by benmccann** [comment]
No problem. I appreciate that you made this. There was an issue on our end that we didn't alert you to the fact that it's not possible.

I sent https://github.com/sveltejs/kit/pull/2363 to fix that
