### ISSUE TITLE
Export DefaultBody for typing callback function

### ISSUE THREAD

**Issue by winston0410** [sveltejs/kit#2368]
### Describe the problem

I cannot type a callback like this correctly, as `DefaultBody` is not exported

```typescript
import type { EndpointOutput } from "@sveltejs/kit"

export type Callback<Output> = () => Promise<EndpointOutput<Output>>

// DefaultBody is not exported
export const catched = async <Output = DefaultBody>(cb: Callback<Output>): Promise<EndpointOutput<Output>> => {
    try {
      return await cb()
    } catch (e) {
      const body = await e.json()
      return {
          status: e.status,
          body
      }
    }
}
```

### Describe the proposed solution

Export DefaultBody. This type should not be kept as internal.

### Alternatives considered

Passing null as the default value, but the compiler still complains for this.

### Importance

would make my life easier

**Comment by benbender** [comment]
Simply use the `RequestHandler`-Interface. See https://kit.svelte.dev/docs#routing-endpoints

**Comment by winston0410** [comment]
@benbender Thanks for the reply. My callback there is part of the request handler, therefore it won't work. This is a snippet of how that function can be used:

```typescript
const getTournament = async (token: string): Promise<ITournaments> => {
	return fetch(endpoints.meTournament, {
		method: 'GET',
		headers: { authorization: `Bearer ${token}` }
	})
		.then(handleFetchError)
		.then((res) => res.json());
};

export const get: RequestHandler = async (req) => {
	return await catched(async () => {
		const data = await getTournament(req.locals.accessToken);
		return {
			body: data
		};
	});
};
```

**Comment by Rich-Harris** [comment]
Since this issue was opened, [`RequestHandlerOutput`](https://kit.svelte.dev/docs/types#sveltejs-kit-requesthandleroutput) was added to the public types
