### ISSUE TITLE
Using vite-plugin-iso-import after updating to latest version of SvelteKit results in an error

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#2371]
### Describe the bug

I was using [vite-plugin-iso-import](https://github.com/bluwy/vite-plugin-iso-import) successfully just fine for a few weeks. Today I updated SvelteKit from .144 to .162 and now I am getting this error when trying to start the server:

```
> The following dependencies are imported but could not be resolved:

  text-field-edit?client (imported by /Users/kevin/Workspace/cn-sveltekit/src/lib/components/Textarea.svelte)
  fit-textarea?client (imported by /Users/kevin/Workspace/cn-sveltekit/src/lib/components/Textarea.svelte)

Are they installed?
```

Why is this no longer working after the SvelteKit update, and how do I fix it?

### Reproduction

My (simplified) `Textarea.svelte` component:

```
<script>
  import { onMount } from "svelte";
  import { insert, wrapSelection, getSelection } from "text-field-edit?client";
  import fitTextarea from "fit-textarea?client";

  export let value = "";
  let textarea;

  onMount(() => {
    fitTextarea.watch(textarea);
  });
</script>

<textarea rows="3" bind:value bind:this={textarea} />
```

My `svelte.config.js` file:

```
import md from "vite-plugin-markdown";
import { isoImport } from "vite-plugin-iso-import";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    vite: {
      plugins: [md.plugin({ mode: md.Mode.HTML }), isoImport()],
    },
  },
};

export default config;
```

### System Info

```shell
System:
    OS: macOS 12.0
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 28.36 MB / 32.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Safari: 15.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.162 
    svelte: ^3.34.0 => 3.42.4
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
Could you narrow down which version bump introduced the error?

**Comment by kevinrenskers** [comment]
It seems that it still worked in 145 but broke in 146.

**Comment by bluwy** [comment]
I think we should transfer the issue to https://github.com/bluwy/vite-plugin-iso-import, the change in 146 can't be reverted. I may have some ideas to fix this on the vite plugin's end

**Comment by kevinrenskers** [comment]
> I think we should transfer the issue to https://github.com/bluwy/vite-plugin-iso-import, the change in 146 can't be reverted. I may have some ideas to fix this on the vite plugin's end

Do you need me to create a new issue over at vite-plugin-iso-import?

**Comment by bluwy** [comment]
Yes please
