### ISSUE TITLE
Adding an __error.svelte components breaks pages because context is missing

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#2379]
### Describe the bug

I am seeing weird behavior where adding an `__error.svelte` component results in my page's `load` function no longer receiving the `context` it expects.

### Reproduction

My file structure, you can see that I have a toplevel `__error.svelte` and one inside of the `characters` route:

![Screen Shot 2021-09-06 at 19 05 52](https://user-images.githubusercontent.com/229384/132247626-b793f1df-1736-43b8-bb98-4105f1f34697.png)

Now, when I directly open http://localhost:4000/campaigns/1/characters/1, I see the page just fine, as expected:

![Screen Shot 2021-09-06 at 19 07 01](https://user-images.githubusercontent.com/229384/132247719-5342e32a-4522-42dc-a7a8-fd8f71f25330.png)

But if I go to that exact same page using the list on the left, I get the error page:

![Screen Shot 2021-09-06 at 19 24 52](https://user-images.githubusercontent.com/229384/132248833-6e0cac4d-95f4-4dbd-a0af-ed82522ec36b.png)

In my `characters/[characterId].svelte` page I have this `load` function:

```
<script context="module">
  export async function load({ page, context }) {
    const character = context.fetchedCharacters[page.params.characterId];
    if (!character) {
      return {
        status: 404,
        error: "Character not found"
      }
    }

    return { props: context };
  }
</script>
```

This works fine, it's using the context which is given by `characters/__layout.svelte`'s `load` function.

However, as soon as I introduced that `characters/__error.svelte` component, `context` is empty on client side route changes. And since it's empty, the character isn't found and the error is returned. Removing `characters/__error.svelte` makes it work again.

### System Info

```shell
System:
    OS: macOS 12.0
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 25.98 MB / 32.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Safari: 15.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.164 
    svelte: ^3.34.0 => 3.42.4
```

### Severity

Serious, but I can work around it (by not using any error pages other than the top level one..)

### Additional Information

This doesn't seem to be a brand new problem, it's been broken since at least .144.

**Comment by rmunn** [comment]
I'm having trouble reproducing the error. All the attempts I've made, placing an `__error.svelte` next to a `__layout.svelte`, have worked fine and passed `context` down correctly as far as I can tell. Could you create a minimal reproduction in a repo so I can clone it and see the error happening?

**Comment by kevinrenskers** [comment]
I'll try to create an example repo tonight.

**Comment by kevinrenskers** [comment]
It was a logic error on my part. I am caching the result of the server request to fetch the characters into a writable store, and only returning the context in SSR - relying on the store on the client side. So it's logical that the context was empty on client side route changes. I was seeing weird behavior where everything seemed to work fine until I added that `__error.svelte` page, but I can no longer reproduce that, so 🤷‍♂️
