### ISSUE TITLE
Error: Function called outside component initialization

### ISSUE THREAD

**Issue by n00pper** [sveltejs/kit#2381]
### Describe the bug

Kinda the same problem as [#460](https://github.com/sveltejs/kit/issues/460) which got resolved, but I'm still getting this error on `"@sveltejs/kit": "^1.0.0-next.164"` version.

In `onMount` of my `__layout.svelte` I create a class which subscribes to the `page` params imported from `'$app/stores'`. This is where the error is thrown.

### Reproduction

[https://github.com/n00pper/svelte-kit-error-reproduction](https://github.com/n00pper/svelte-kit-error-reproduction)

### Logs

```shell
Error: Function called outside component initialization
    at get_current_component (index.mjs:938)
    at getContext (index.mjs:971)
    at getStores (stores.js:21)
    at Object.subscribe (stores.js:46)
    at new Translator (translator.ts:24)
    at initTranslator (translator.ts:14)
    at __layout.svelte? [sm]:10
    at run (index.mjs:18)
    at Array.map (<anonymous>)
    at index.mjs:1731
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 20.29 GB / 31.89 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chromium (93.0.961.38)
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18
    @sveltejs/kit: ^1.0.0-next.164 => 1.0.0-next.164
    svelte: ^3.34.0 => 3.42.4
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
As indicated in https://kit.svelte.dev/docs#modules-$app-stores you need to subscribe to the stores synchronously during component initialization. If there's code inside `onMount` that's attempting to subscribe to a store (asynchronously), that's not going to work. You can use `getStores` to obtain already-bound instances of the stores and pass them into asynchronous code.

**Comment by discreet-google-maps-api** [comment]
> As indicated in https://kit.svelte.dev/docs#modules-$app-stores you need to subscribe to the stores synchronously during component initialization. If there's code inside `onMount` that's attempting to subscribe to a store (asynchronously), that's not going to work. You can use `getStores` to obtain already-bound instances of the stores and pass them into asynchronous code.





https://resolver761.github.io/oa2d3if-XKA-ItIVDPir6L6T_f_LRhqvP1ivRw/
