### ISSUE TITLE
Prerender adds trailing slash even for json/webmanifest files

### ISSUE THREAD

**Issue by Konakona-chan** [sveltejs/kit#2390]
### Describe the bug

Hi, for my project I need to generate webmanifest during build. With `trailingSlash: 'always'` build fails, because prerender.js extracts link from `<link rel="manifest" href="/manifest.webmanifest" />` and fails with:
```
Attempt to 404 /manifest.webmanifest/ (linked from /)
```

### Reproduction

svelte.config.js
```
import preprocess from 'svelte-preprocess';
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),
		target: '#svelte',
		trailingSlash: 'always'
	}
};

export default config;
```

index.svelte
```
<svelte:head>
    <link rel="manifest" href="/manifest.webmanifest" />
</svelte:head>
```

manifest.webmanifest.ts
```
import type { RequestHandler } from "@sveltejs/kit";


export const get: RequestHandler = () => {
    return { body: {/* code skipped */} };
};
```

`npm run build` fails with:
```
> Using @sveltejs/adapter-static
> 404 /manifest.webmanifest/ (linked from /)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 3.17 GB / 15.88 GB
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 93.0.4577.63
    Edge: Spartan (44.17763.1911.0)
    Internet Explorer: 11.0.17763.1852
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18
    @sveltejs/kit: next => 1.0.0-next.164
    svelte: ^3.34.0 => 3.42.4
```

### Severity

serious, but I can work around it

### Additional Information

Renaming `manifest.webmanifest.ts` to `manifest.json.ts` does not help.

The only workaround I know is to use .kit.trailingSlash="ignore" option (I can not use "never" for compatibility reasons).

**Comment by rmunn** [comment]
What happens if you change `<link rel="manifest" href="/manifest.webmanifest" />` to `<link rel="manifest" href="/manifest.webmanifest/" />`? Does that work, or is there a requirement that the manifest URL must **not** have a trailing slash?

**Comment by Konakona-chan** [comment]
> What happens if you change `<link rel="manifest" href="/manifest.webmanifest" />` to `<link rel="manifest" href="/manifest.webmanifest/" />`? Does that work, or is there a requirement that the manifest URL must **not** have a trailing slash?

No, it still fails with the same error (`404 /manifest.webmanifest/ (linked from /)`). And even if I manage to turn `/manifest.webmanifest/` to a directory, my static website host won't be able to serve it (webmanifest should have a specific mimetype).

I also found another dirty hack solution:
```
<script context="module" lang="ts" >
import type { Load } from "@sveltejs/kit";

export const load: Load = async ({ page, fetch }) => {
    const { lang, project } = page.params;
    await fetch(`/${lang}/${project}/manifest.webmanifest`);
    return {};
};
</script>

<script lang="ts" >
    import {page} from "$app/stores"
</script>

<svelte:head>
    <!-- full domain here to prevent crawler from extracting this url -->
    <link rel="manifest" href="https://app.dev/{$page.params.lang}/{$page.params.project}/manifest.webmanifest" />
</svelte:head>
```
Then it is also possible to [embed webmanifed directly into html](https://stackoverflow.com/a/62439564/337979) in a similar way. But for now I would prefer `trailingSlash: 'ignore'`.

This also affects other non-html types like:
```
<link rel="alternate" type="application/rss+xml" title="RSS" href="/data/rss.xml">
<link rel="alternate" type="application/atom+xml" title="Atom" href="/data/atom.xml">

<link rel="alternate" href="/data/item.json" type="application/json"/>
<link rel="alternate" href="/data/item.n3" type="text/n3"/>
<link rel="alternate" href="/data/item.ttl" type="text/turtle"/>
<link rel="alternate" href="/data/item.nt" type="application/n-triples"/>
<link rel="alternate" href="/data/item.rdf" type="application/rdf+xml"/>
<link rel="alternate" href="/data/item.jsonld" type="application/ld+json"/>

<a href="/data/item.json">Download generated specification in JSON format</a>
```

The only common thing in all these cases is a custom extension (which is a requirement to serve statically generated files with a correct mimetype).

**Comment by Konakona-chan** [comment]
How about doing [url normalization in prerender visitor](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/adapt/prerender.js#L146) after rendering (based on output content-type header, a. k. a. `is_html` in this file)? Looks like a good zero-configuration alternative to proposal in #1405.

**Comment by benmccann** [comment]
I would think that trailing slashes should also be added for endpoints if you set a value of `'always'`. In that case, you can't decide based just on `content-type`. I think you'd have to have a list of all routes and check if it's a route that exists in the application?

**Comment by benmccann** [comment]
Is your `manifest.webmanifest` file located in the static directory? Perhaps we should skip adding trailing slashes for files in that directory

**Comment by Konakona-chan** [comment]
> Is your `manifest.webmanifest` file located in the static directory? Perhaps we should skip adding trailing slashes for files in that directory

Not exactly, my full path webmanifest is [/src/routes/listen/[album]/[language]/manifest.webmanifest.ts](https://gitlab.com/Kona-chan/kona-chan.gitlab.io/-/blob/master/src/routes/listen/%5Balbum%5D/%5Blanguage%5D/manifest.webmanifest.ts).

As I said in bug description, I use `adapter-static`, which of course builds all .svelte/.ts files into static files. However all static files are served by a generic static files hosting (Gitlab pages in my case). It is not possible to configure any popular static files hosts (like Github pages, Netlify, Cloudflare Pages, etc.) to serve webmanifest/json/xml and other non-html files under paths with trailing slashes.

**Comment by kdheepak** [comment]
I'm having the same issue with `/rss.xml`

```
> 404 /rss.xml/ (linked from /)
    at file:///$HOME/gitrepos/blog/node_modules/@sveltejs/kit/dist/chunks/index5.js:409:11
    at visit (file:///$HOME/gitrepos/blog/node_modules/@sveltejs/kit/dist/chunks/index5.js:583:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Is there a recommended fix for this?

**Comment by kdheepak** [comment]
I believe this issue is fixed by https://github.com/sveltejs/kit/pull/3858.
