### ISSUE TITLE
Freeze livereload in node_modules folder

### ISSUE THREAD

**Issue by Valexr** [sveltejs/kit#2406]
### Describe the bug

If sveltekit root folder inside `./src/node_modules/svelte-kit` live reload in dev mode don't working...

### Reproduction

Create sveltekit project inside node_modules folder & run `svelte-kit dev`

### System Info

```shell
System:
    OS: macOS 12.0
    CPU: (8) arm64 Apple M1
    Memory: 116.34 MB / 8.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.9.0 - /opt/homebrew/bin/node
    npm: 7.21.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Firefox: 92.0
    Firefox Developer Edition: 93.0
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.18 
    @sveltejs/kit: next => 1.0.0-next.165 
    svelte: ^3.34.0 => 3.42.5
```

### Severity

annoyance

**Comment by bluwy** [comment]
Anything under `node_modules` isn't watched by Vite [by default](https://github.com/vitejs/vite/blob/fbd143a937f48254f20d568040c9d295438c71fd/packages/vite/src/node/server/index.ts#L320-L325), and there doesn't seem to be a way to configure that. Plus a lot of Vite's internal have assumptions on whether a path contains `node_modules` and work accordingly, so I'd guess it's not a simple feature.

At the meantime you can use something like https://github.com/ElMassimo/vite-plugin-full-reload to watch that path, but it'll do a full reload everytime the files there change. Another untested idea, is to only force Vite to watch those files [like so](https://github.com/ElMassimo/vite-plugin-full-reload/blob/1a4bf3338676524a3a7235e34c1e621ad76510df/src/index.ts#L60) so HMR could still work (not sure).

**Comment by Mlocik97** [comment]
> Create sveltekit project inside node_modules folder

I don't see one reason to do this. What is use case of this?

**Comment by Valexr** [comment]
Old school monorepo 😁`src/node_modules/package` for using in app like `import pack from 'package'`
Now it resolved by workspaces or lerna… but I’m find this case🤷🏻‍♂️

**Comment by bluwy** [comment]
That's a very unique usecase. I don't think there's anything SvelteKit can do at the moment to fix this, it would be an upstream issue in Vite, so we should send an issue up there instead and close this.

Though to be honest, I don't think it's worth the effort fixing in Vite either. Might be worth refactoring the old monorepo style to use workspaces, as Vite also has extra support for developing in workspaces.

**Comment by Valexr** [comment]
Yep, that’s it
