### ISSUE TITLE
Cannot find package 'stream' 

### ISSUE THREAD

**Issue by winston0410** [sveltejs/kit#2412]
### Describe the bug

This happens after the latest update for kit. I got the following error with `npm run build`:

19:39:57.691 | > Cannot find package 'stream' imported from /vercel/path0/web/.svelte-kit/output/server/app.js
-- | --
19:39:57.691 | Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /vercel/path0/web/.svelte-kit/output/server/app.js
19:39:57.691 | at packageResolve (internal/modules/esm/resolve.js:664:9)
19:39:57.691 | at moduleResolve (internal/modules/esm/resolve.js:705:18)
19:39:57.691 | at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
19:39:57.691 | at Loader.resolve (internal/modules/esm/loader.js:89:40)
19:39:57.691 | at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
19:39:57.691 | at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
19:39:57.691 | at link (internal/modules/esm/module_job.js:72:36)

### Reproduction

Clone my repo here: https://github.com/winston0410/portfolio-2021

`cd ./web`
`npm install`
`npm run build`

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 27.66 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.1 - /nix/store/i0sl2paxrjshqn5ps24pdhdkql07x6ra-nodejs-16.4.1/bin/node
    npm: 7.18.1 - /nix/store/i0sl2paxrjshqn5ps24pdhdkql07x6ra-nodejs-16.4.1/bin/npm
  Browsers:
    Brave Browser: 93.1.29.76
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.18
    @sveltejs/adapter-vercel: next => 1.0.0-next.28
    @sveltejs/app-utils: next => 1.0.0-next.3
    @sveltejs/kit: next => 1.0.0-next.162
    svelte: ^3.34.0 => 3.42.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I got the same error on both local and vercel.

**Comment by benmccann** [comment]
I think [that import statement is coming from `node-fetch`](https://github.com/node-fetch/node-fetch/blob/2603c67f1840fb4a43e0837099a3b2725e8f615e/src/index.js#L12). We haven't changed the `node-fetch` version in many months though

>This happens after the latest update for kit.

This doesn't seem to have broken because of a kit upgrade, but because of https://github.com/winston0410/portfolio-2021/commit/859ead8c0a970ec6ac91f410795736af7763e161#diff-4b5e57f6eb2f42b9039b3d1e13929295f231749c510cbe341cd68036d9af97e2

**Comment by benmccann** [comment]
It's because you added a dependency on `node-fetch` 3.0 final. I get the same error if I try to upgrade SvelteKit to use that version: https://github.com/sveltejs/kit/pull/2422

**Comment by winston0410** [comment]
@benmccann Yes I have added in `node-fetch`, because I got an `ERR_MODULE_NOT_FOUND` for `fetch` in my server side code.

And I think I got that error after I have added in a wrapped fetch to my code, but it looks alright to me? It should pick up `fetch` from either `global` or `window`?

```javascript
// index.ts
var createWrapped = (f) => {
  f = f ? f : fetch;
  return async (url, opts) => {
    const res = await f(url, opts);
    return {
      ok: res.ok,
      status: res.status,
      body: await res.json()
    };
  };
};
var git_clone_aa4ce5db_default = createWrapped;
export {
  git_clone_aa4ce5db_default as default
};
```

**Comment by winston0410** [comment]
> #2422

I hope this will solve the issue. Thank you for your time for helping me out.

**Comment by benmccann** [comment]
You must set `ignoreTryCatch: true` for `@rollup/plugin-commonjs`: https://github.com/rollup/plugins/issues/1004

**Comment by asdfdelta** [comment]
I found a decent work-around since updating Kit wasn't working for me. Downgrading to version 2.6.5 of `node-fetch` solved all errors.

`npm I node-fetch@2.6.5`

**Comment by benmccann** [comment]
I got fixes into `@rollup/plugin-commonjs`, `@sveltejs/kit`, and `vite` for this issue. Can you try upgrading to `1.0.0-next.180` which I just released?

**Comment by DavidM42** [comment]
I can support @jckr's advice. Was using node version 14 when I got this error.
Updating to the current node version 18.6.0 solved it :+1:

**Comment by hperrin** [comment]
I ran into this too. Upgrading to 16 worked, but unfortunately, that really complicates my setup, as I have other things that require Node 14.

**Comment by dominikg** [comment]
> I ran into this too. Upgrading to 16 worked, but unfortunately, that really complicates my setup, as I have other things that require Node 14.

kit requires node 16 https://github.com/sveltejs/kit/blob/21d97256f8320fa7a8e3ccf859894e1bc28046d2/packages/kit/package.json#L97

**Comment by benmccann** [comment]
Using multiple node versions is easy with nvm: https://github.com/nvm-sh/nvm

**Comment by rainrisa** [comment]
i had the same issue, my node version is 16.13.0

**Comment by rainrisa** [comment]
solved by this https://github.com/octokit/octokit.js/issues/2126#issuecomment-1186210471
