### ISSUE TITLE
[Version 1.0.0-next.165] Error when evaluating SSR module in dev

### ISSUE THREAD

**Issue by f-elix** [sveltejs/kit#2418]
### Describe the bug

With version 1.0.0-next.165 of Sveltekit installed, I get several Vite SSR errors (`[vite] Error when evaluating SSR module`). The package that seems to be problematic is `@xstate/svelte`. Here is the error log I get:

```
9:47:17 AM [vite] Error when evaluating SSR module /node_modules/@xstate/svelte/lib/index.js:
ReferenceError: exports is not defined
    at /node_modules/@xstate/svelte/lib/index.js:2:23
    at instantiateModule (C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75119:15)
Line must be greater than or equal to 1, got 0
TypeError: Line must be greater than or equal to 1, got 0
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:73983:13) 
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:74052:22)
    at C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:74991:34
    at String.replace (<anonymous>)
    at C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:74981:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:74980:10)
    at instantiateModule (C:\Work\sveltekit-dev-ssr-bug\node_modules\vite\dist\node\chunks\dep-63d4bd14.js:75122:28)
```

This package does not cause any problems with previous Sveltekit versions, that's why I'm assuming there is something wrong with Sveltekit (or Vite) and not the package itself. 

I only get this error when running `npm run dev`. Builds and previews are fine. 

EDIT: I noticed in `package-lock.json` that `@sveltejs/kit` requires `"@sveltejs/vite-plugin-svelte": "^1.0.0-next.22"` but `"@sveltejs/vite-plugin-svelte"` is at version `1.0.0-next.23`. Would that be a possible cause?

### Reproduction

https://github.com/f-elix/sveltekit-dev-ssr-bug

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 21.56 GB / 39.76 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.165
    svelte: ^3.42.5 => 3.42.5
```

### Severity

serious, but I can work around it

**Comment by f-elix** [comment]
Ok I found the problem and the solution. Somewhere along the way `vite-plugin-svelte` was updated with this change: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md.

Therefore, I added `@xstate/svelte` in the `ssr.external` property of the vite config:

In `svelte.config.js`:

```js
```

**Comment by bluwy** [comment]
Thanks for digging into this. The change in `vite-plugin-svelte` was needed to support `svelte/ssr` so `onMount` gets treeshaken out in the server. Your workaround is fine for now since `@xstate/svelte` isn't using any of Svelte's lifecycle methods.

The `ReferenceError: exports is not defined` error is likely because `@xstate/svelte` only exports CJS and we try to bundle (noExternal) it together in an ESM node environment. You can contact the library to export an ESM variant for it. It's weird that a package mainly used in the browser only exports CJS.

**Comment by f-elix** [comment]
It is weird indeed, especially since the source code is written in ES modules. I'll open an issue on the package.

**Comment by bluwy** [comment]
From the mentioned issue, I've sent a PR that should fix this too: https://github.com/sveltejs/vite-plugin-svelte/pull/169. The `ssr.external` workaround would not be needed after that gets updated into kit. Nonetheless, having ESM for `@xstate/svelte` is still great to have.

**Comment by jdgamble555** [comment]
In my case I had to do this:

```typescript
ssr: {
  external: ['whatwg-url']
}
```

**Comment by deandex** [comment]
> In my case I had to do this:
> 
> ```ts
> ssr: {
>   external: ['whatwg-url']
> }
> ```

This is work for me

**Comment by Millionaiyer** [comment]
Error when evaluating SSR module /node_modules/@sveltejs/kit/src/runtime/server/index.js: Cannot read properties of undefined (reading 'wrapDynamicImport') 

I'm having this issue while running svelte kit. It is a fresh app with appwrite, vitest,tailwind , line , typscript.
This error pops up everytime npm run test runs

 If there's anyone that could help me it would be really nice. Thanks

**Comment by khromov** [comment]
@Millionaiyer Please create a new issue or ask on Discord (and provide more information such as link to repo)
