### ISSUE TITLE
browser-only redirect during load not working

### ISSUE THREAD

**Issue by WHenderson** [sveltejs/kit#2424]
### Describe the bug

Browser-only redirects during the load function are being ignored.

### Reproduction

https://github.com/WHenderson/sveltekit-bug-browser-redirect

Code such as the following fails to redirect:
```html
<script context="module">
    import {browser} from "$app/env";

    export async function load() {
        if (browser) {
            // Note there would normally be some condition logic here
            return {
                status: 303,
                redirect: '/redirected',
            };
        }

        return {};
    }
</script>
```

I've been looking at the sveltekit code that should be responding to the redirect and I can't see how it can be hit. Perhaps it has become a dead code branch?

`/runtime/internal/start.js:564`
```javascript
if (result.redirect) {
	// this is a real edge case — `load` would need to return
	// a redirect but only in the browser
	location.href = new URL(result.redirect, location.href).href;
	return;
}
```

### Logs

```shell
N/A. No errors or logs are generated.
```

### System Info

```shell
Chrome
```

### Severity

serious, but I can work around it

### Additional Information

Browser-only redirects make sense when using things such as client-side authentication. In my current example, I wish to navigate away from the sign-in page once the user is authenticated and the authentication check will _always_ fail on the server since the authentication information isn't sent to the server.

**Comment by dummdidumm** [comment]
Fixing the issue will maybe also solve (part of?) #1575
