### ISSUE TITLE
No loader is configured for ".svelte"

### ISSUE THREAD

**Issue by murunwas** [sveltejs/kit#2433]
### Describe the bug

I'm getting the error shown below on the image when I run command `npm run dev` after creating project with `npm init svelte@next` on windows 10 

![image](https://user-images.githubusercontent.com/8838943/133461763-5b9207ef-c79f-4895-b845-7035915d4ebf.png)

### Reproduction

1. run `npm init svelte@next`
2. Run `npm install`
3. run `npm run dev`
4. get this error
![image](https://user-images.githubusercontent.com/8838943/133462785-eae9bfe0-3686-4e54-b078-0cf6ac9126c4.png)

### System Info

```shell
windows 10
```

### Severity

blocking all usage of SvelteKit

**Comment by baseballyama** [comment]
Did you execute `npm install` command before `npm run dev`?

ref: https://kit.svelte.dev/

**Comment by murunwas** [comment]
Yes I did

**Comment by baseballyama** [comment]
Thank you for the answer.

Then the `Reproduction` part you wrote is not accurate.
So could you please update it?
I need to know what did you do perfectly for analysis.
And I recommend you all logs also paste on the issue report.

And regarding `System Info` part,
You should paste result of `npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"` command.

Otherwise, contributors can't analyze what is going on.

**Comment by Conduitry** [comment]
I can't reproduce this on fresh VM of Windows 10 with Node 14.

**Comment by dominikg** [comment]
vite has issues with # in directory names ,please try again with a path without #

eg https://github.com/vitejs/vite/issues/2346

**Comment by baseballyama** [comment]
I can reproduce it after add `c#` folder.

**Reproduce Steps**
```
mkdir d#
cd c#
npm init svelte@next
npm install
npm run dev
```

Then below error comes.


```
> Build failed with 1 error:
.svelte-kit/dev/runtime/internal/start.js:1:17: error: No loader is configured for ".svelte" files: .svelte-kit/dev/generated/root.svelte
Error: Build failed with 1 error:
.svelte-kit/dev/runtime/internal/start.js:1:17: error: No loader is configured for ".svelte" files: .svelte-kit/dev/generated/root.svelte
    at failureErrorWithLog (C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:1478:15)
    at C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:1136:28
    at runOnEndCallbacks (C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:926:63)
    at buildResponseToResult (C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:1134:7)
    at C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:1243:14
    at C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:614:9
    at handleIncomingPacket (C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:711:9)
    at Socket.readFromStdout (C:\Users\baseballyama\Desktop\temp\c#\node_modules\esbuild\lib\main.js:581:7)
    at Socket.emit (events.js:376:20)
    at Socket.emit (domain.js:470:12)
```

Thank you @dominikg

**Comment by Conduitry** [comment]
Interesting, okay. IMO we don't need to keep an issue open on our side to track this, but I'll defer if other folks want to.

**Comment by murunwas** [comment]
Thank you so much, it's working fine now 👏
