### ISSUE TITLE
Add hero images to kit.svelte.dev

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#244]
Includes #33, #34, #168, but I mostly wanted to raise this catch-all issue so we have a convenient place for @vedam's gorgeous work: https://www.figma.com/file/f87psJnCeqMbUPAQABmCrN/svelte

![svelte-cutter-06](https://user-images.githubusercontent.com/1162160/101544134-2fbefc80-3973-11eb-85c7-61b23f7ecab3.png)
![svelte-kit-04](https://user-images.githubusercontent.com/1162160/101544135-30579300-3973-11eb-9ab9-e9ca5812e562.png)
![svelte-kit-grey-05-small](https://user-images.githubusercontent.com/1162160/101544137-30579300-3973-11eb-88ac-32cd7562147a.png)
![svelte-liquid-08](https://user-images.githubusercontent.com/1162160/101544138-30579300-3973-11eb-8aeb-2fedc43cfd1d.png)
![svelte-main-10](https://user-images.githubusercontent.com/1162160/101544140-30f02980-3973-11eb-8acd-781203261e0c.png)

**Comment by benmccann** [comment]
I'm wondering where to integrate these. One idea would be in the three boxes on the SvelteKit homepage. "Powered by Svelte" could be the power plant looking thing, "Best of both worlds" could be the two streams colliding, "Build fast" could be the factory pumping out machines from boxes. Maybe the background of those three sections would change to the image when hovered over

**Comment by vedam** [comment]
Yes, when I made them I didn't know that SvelteKit would get its own site. IMO the illus are rather meant as a replacement for the relatively simple outline-S. Large background images as eyecandy (see figma-layout). One for Svelte itself and one for SvelteKit. As a result, the SvelteKit site is then also visually more distinct from the Svelte site. I think degrading them into the three boxes would make them very small-scale and petty after all.

**Comment by Rich-Harris** [comment]
100%, definitely hero images. I absolutely love these mockups and can't wait for us to start implementing them

**Comment by benmccann** [comment]
Oh, nice! Yeah, much better usage to have them more prominent! I just sort of thought it was funny how well the images matched the captions for the boxes and wasn't sure how to blend the backgrounds, but the Figma mockups look much better than what I suggested :smile:

**Comment by zamkevich** [comment]
> Maybe someone can tell me if you're able to comment on the figma-file?
> First figma-experience, so I don't know if it's setup correctly.
> I don't want to risk something going public until we're ready.

**Actually is already public** 
1. You need to select all team members from the share menu, and give them 'can view' option 
2. And then make the file a private

![image](https://user-images.githubusercontent.com/13717428/112308983-7e0fc580-8cee-11eb-9821-518a3e6fa8dc.png)

**Comment by zamkevich** [comment]
> Maybe someone can tell me if you're able to comment on the figma-file?
> First figma-experience, so I don't know if it's setup correctly.
> I don't want to risk something going public until we're ready.

**Actually is already public**
To make it private:
1. First you need to make the file a private
![Screen Shot 2021-03-24 at 10 21 00 PM](https://user-images.githubusercontent.com/13717428/112310273-19ee0100-8cf0-11eb-8f8e-e46276f108fd.png)

2. Then remove access from all non-team members
![Screen Shot 2021-03-24 at 10 23 38 PM](https://user-images.githubusercontent.com/13717428/112309996-c8de0d00-8cef-11eb-8b4f-4fc2efd30188.png)

**Comment by vedam** [comment]
@zamkevich Thx for enlightening me. 
I have now made the figma file accessible only to maintainers. If I have removed one of you from the viewlist accidentally (most likely because i can't assign the shown username), please let me know.
If you don't mind that the file is public, let me know too, and I'll reopen it again to everyone.

**Comment by MTyson** [comment]
I'd like to be able to see the files.

**Comment by benmccann** [comment]
I have no issues with the files being public. It's up to @vedam whether he wants to be getting comments on them or not :grin: 

Anyway, the most interesting ones are already included in the description of this issue

**Comment by MTyson** [comment]
What is the license for these? Can we use them when pimping Svelte to the general public?

**Comment by benmccann** [comment]
See https://github.com/sveltejs/branding

**Comment by vedam** [comment]
OK then, if public viewing isn't a concern: reopened to view for everyone.  ;-)

**Comment by simonlayfield** [comment]
Just seen these - really awesome work.

**Comment by benmccann** [comment]
Making a note here for anyone that would want to work on this. The code lives in https://github.com/sveltejs/sites/tree/master/sites/kit.svelte.dev

**Comment by rafaelcamaram** [comment]
I just created the first PR related to it: https://github.com/sveltejs/sites/pull/17. 

It's updating the existing components to match with the new design -- I'll create a new PR in order to add the new sections soon :)
