### ISSUE TITLE
Layout fallthrough

### ISSUE THREAD

**Issue by lemmon** [sveltejs/kit#2440]
### Describe the bug

I am trying to throw an error:

```js
export async function load({ page }) {
  if (page.params.foo !== 'okay') {
    return
  }
  return {}
}
```

This example works as expected within a page component. However when I put this logic inside `__layout.svelte` it behaves rather oddly.

In first case when nothing is returned then application proceeds to the page component. It renders the page contents, however ignores the __layout content. When the page is refreshed and reloaded completelly it thows an error 500 saying "load must return a value except for page fall through"

I want to check path validity for all the child pages within one directory and putting this logic inside every single page is not ideal. Better solution would to be able to check only once, inside the layout component.

I understand this is probably outside of the scope of intended functionality but it might be a mice addition, in my opinion.

### Reproduction

https://github.com/lemmon/svelte-kit-layout-error

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 49.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    npm: 7.22.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 88.1.19.86
    Chrome: 93.0.4577.82
    Firefox: 92.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.168 
    svelte: ^3.34.0 => 3.42.6
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
What do you want to achieve / what is your expected behavior when you return nothing from a load function in __layout? AFAIK, fall-through routes exist for pages only, not for layouts.

**Comment by lemmon** [comment]
I want it to behave the same as the page endpoints. If the __layout returns nothing it should fall-through. I understand this issue is part bug and part feature request.

I have this routes structure:
`routes/[foo]/` .. and many pages here.

I don't want to check validity of `foo` inside every single page but only once in the layout.

**Comment by dummdidumm** [comment]
> 
> 
> I want it to behave the same as the page endpoints. If the __layout returns nothing it should fall-through. I understand this issue is part bug and part feature request.

So you have 
```
routes/[foo]/..
routes/[bar]/..
```
and you want to fall through to `bar` by returning nothing from the `__layout` in `foo`?

**Comment by lemmon** [comment]
Yeah. Fall through either to `[bar]` or an `__error` page. I don't have `bar` in my case. The very thing is possible when you return nothing form either a page or an endpoint. But it's quite anoying and ugly when you have a lot of pages under the `foo` (or `bar`). Seems like __layout is the best place to validate such scenario but the functionality is not there.

**Comment by nhe23** [comment]
I'd like to work on this issue and will create a PR as soon as I'm done.

**Comment by nhe23** [comment]
Turns out the solution to this issue is pretty easy. All I had to do was to remove a is_leaf check in the load_node function in the server runtime
```js
// if leaf node (i.e. page component) has a load function
// that returns nothing, we fall through to the next one
if (!loaded && is_leaf && !is_error) return;
```
and in the client-side renderer:
```js
else if (is_leaf && module.load) {
// if the leaf node has a `load` function
// that returns nothing, fall through
return;
```

However it seems like this behaviour was actively prevented in the past. Was there a reason for that?
