### ISSUE TITLE
`$page.query` not available in production mode

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2444]
### Describe the bug

It appears that, at least for `adapter-static`, `$page.query` is not available in production mode

Originally reported by @ABarnob in https://github.com/svelte-society/sveltesociety.dev/pull/108

### Reproduction

```
git clone git@github.com:svelte-society/sveltesociety.dev.git
cd sveltesociety.dev
git checkout staging
npm install
npm run build
cd build
python -m http.server 3000
```

If you navigate to http://localhost:3000/help/submitting?type=tool then the query parameter is ignored and the dropdown in not correctly populated. It works in dev mode

### System Info

```shell
npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.18 
    @sveltejs/kit: next => 1.0.0-next.162 
    svelte: ^3.38.2 => 3.42.4
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Is this the essentially the same as #1825/#2262, which were working-as-designed?

**Comment by benmccann** [comment]
Ah, yes, you're right. It's really not obvious :smile: #2363 would solve this so that users can't make that mistake

**Comment by scorsi** [comment]
Here is a potential workaround client-side only : 
```js
// import { page } from '$app/stores';
import { browser } from '$app/env';

export let param /* = $page.query.get('param') */;

$: {
	if (browser) {
		const urlParams = new URLSearchParams(window.location.search);
		param = urlParams.get('param');
	}
}
```

**Comment by Conduitry** [comment]
@benmccann Can we close this in favor of #2361? It doesn't sound to me like there's anything else going on here.
