### ISSUE TITLE
Next Gen Image Optimization

### ISSUE THREAD

**Issue by navneetsharmaui** [sveltejs/kit#2448]
### Describe the problem

As Sveltekit is growing. We could add the in-house support for the next-gen image optimization support like the one in NextJS with `next/image`.

Image optimization is one of the important parts of web vitals and web performance. Right now there is no proper way to integrate the image optimization logic into the sveltekit other than to pre-optimize all the images then including them in the sveltekit build process.

### Describe the proposed solution

We could add the in-house support for the next-gen image optimization support like the one in NextJS with `next/image`.

### Importance

would make my life easier

**Comment by bluwy** [comment]
Thanks! But this is already tracked in #241. Closing in favor of that.
