### ISSUE TITLE
Move packaging support into a separate package?

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2452]
### Describe the problem

As we get closer to 1.0, we should start thinking about how to stabilize APIs and versioning. I wonder if having the `package` command in the same package as the rest of SvelteKit will cause us any difficulties in having the versioning of the two functionalities be tied to one another. The two functionalities seem fairly different and I'm not sure if makes sense to block major version upgrades of one on the other

### Describe the proposed solution

We could perhaps create a separate `svelte-package` command? Open to other ideas as well

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
I'm not sure about this. It's separated in the sense that they only share the config. But it _feels_ tightly connected to each other.
Regarding whether or not this blocks an upgrade: I don't remember a breaking change being made to the package command and don't foresee one.

**Comment by benmccann** [comment]
Ok, good to know it's fairly stable. I thought perhaps since it was a bit newer that it might still need some time to marinate. But if there's not much need then I can go ahead and close this
