### ISSUE TITLE
Include a default adapter for the demo project

### ISSUE THREAD

**Issue by penalosa** [sveltejs/kit#2459]
### Describe the problem

I installed the demo project and tried to build, but got an error mentioning that no adapter was specified, which seems somewhat confusing as a default experience.

### Describe the proposed solution

Default the demo project to the static adapter/node adapter (not sure which is more appropriate), or add a question to the setup (along with whether to enable Typescript etc...) that defaults to including an adapter.

### Importance

nice to have

**Comment by Conduitry** [comment]
I'm against adding a default. I'm ambivalent about adding an option to `create-svelte`. See #62 for the original discussion where we decided to not have a default adapter.

**Comment by penalosa** [comment]
Sure, I get the reasoning behind not adding a default, but I think adding an option to `create-svelte` would really help first time users get started (or a bit more explanation to the "No adapter specified" warning message, something like "Adapters are how SvelteKit knows how to prepare your app for the specific platform you want to deploy to. See https://kit.svelte.dev/docs#adapters for a list of which adapters are available, and to learn how to configure your app to run on the platform of your choosing")

**Comment by benmccann** [comment]
Adding it to `create-svelte` sounds fine to me if anyone wants to work on it

**Comment by Mlocik97** [comment]
related to: https://github.com/sveltejs/kit/issues/2246

I mean it would be good to have option to add adapter in initializing project, but default should still be "I don't know yet / a different adapter". As benmccann wrote.

**Comment by supercoww** [comment]
I'm interested in working on this.

**Comment by benmccann** [comment]
Sounds fine to me. The default should probably be something like "Not now. I'll add it later or will use a community-provided adapter (https://bit.ly/3kvqIRy)"

Right now the list of community adapters at sveltesociety.dev is pre-rendered at build-time for that site. But we could probably send a PR to add an API endpoint to that site exposing the list of adapters. Then we could also allow you to choose from them as well

**Comment by Rich-Harris** [comment]
This can be closed, both demo apps include `adapter-auto`
