### ISSUE TITLE
Client redirect (goto, return redirect) not working if load function exist

### ISSUE THREAD

**Issue by codeinforest** [sveltejs/kit#2460]
### Describe the bug

It's seem goto / return functions not working if I have load function together.

### Reproduction

I have this code in `index.svelte`
```
<script context="module">
  export async function load({ session }) {
    if (!session.user) { // Update here, ! was be added
      return {
        status: 302,
        redirect: "/login", // Update here, redirect to login route
      };
    }
    return {};
  }
</script>
```

Then in `login.svelte`, I have this code:
```
<script context="module">
  export async function load({ session }) {
    if (session.user) {
      return {
        status: 302,
        redirect: "/",
      };
    }
    return {};
  }
</script>
... API Logic ...

if (res.status > 300) {
    statusCode = res.status;
}

$session.user = json.data;
goto("/");
```

But when I login successfully, the function goto not working. I try to change to return function and still not work.
```
...
$session.user = json.data;
return {
    status: 302,
    redirect: "/",
};
```

Anyone has solutions for this case? Please help me!

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 182.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.159
    svelte: ^3.34.0 => 3.42.4
```

### Severity

annoyance

**Comment by benmccann** [comment]
@codeinforest can you please provide a repository with an example of this issue?

**Comment by benmccann** [comment]
I can't create an application to reproduce every issue that's filed because we have over 200 issues. It's just not scalable for me to do it all myself. Even with instructions provided, I still need the issue reporter to put it in a repo on GitHub because there's no way I'd have time to do it for all the issues

**Comment by codeinforest** [comment]
> I can't create an application to reproduce every issue that's filed because we have over 200 issues. It's just not scalable for me to do it all myself. Even with instructions provided, I still need the issue reporter to put it in a repo on GitHub because there's no way I'd have time to do it for all the issues

I see, I know you and development team work hard to make this awesome product. So I will try to fix this issue and help another got same issue. I also see some pull request has same issue and I will try to find some way to fix it soon. Thank you and development team!

**Comment by rmunn** [comment]
> I have this code in `index.svelte`
> 
> ```
> <script context="module">
>   export async function load({ session }) {
>     if (session.user) {
>       return {
>         status: 302,
>         redirect: "/",
>       };
>     }
>     return {};
>   }
> </script>
> ```

That looks wrong to me. What are you trying to do here? Because what that will do is, if there is a user in the session, redirect to `/` again, which will load `index.svelte` again, and redirect to `/`, and so on in an infinite loop. I suspect that this is your problem: when you call `goto('/')` after a successful login nothing seems to happen, because your browser has entered an infinite redirect loop.

If you encounter other problems in the future, I suggest asking a question in https://svelte.dev/chat first before opening a bug report, just to make sure that the cause of the problem isn't a misunderstanding or a bug in your code.

**Comment by codeinforest** [comment]
> > I have this code in `index.svelte`
> > ```
> > <script context="module">
> >   export async function load({ session }) {
> >     if (session.user) {
> >       return {
> >         status: 302,
> >         redirect: "/",
> >       };
> >     }
> >     return {};
> >   }
> > </script>
> > ```
> 
> That looks wrong to me. What are you trying to do here? Because what that will do is, if there is a user in the session, redirect to `/` again, which will load `index.svelte` again, and redirect to `/`, and so on in an infinite loop. I suspect that this is your problem: when you call `goto('/')` after a successful login nothing seems to happen, because your browser has entered an infinite redirect loop.
> 
> If you encounter other problems in the future, I suggest asking a question in https://svelte.dev/chat first before opening a bug report, just to make sure that the cause of the problem isn't a misunderstanding or a bug in your code.

It's not wrong. The load() function only run while the browsers loading. If no condition matched, it return empty object.
My issue is when I press Login button, the page is not redirect. When I press this button, load() function not be run so it can not redirect loop. goto() function just go to target page without refresh.
You can see in Real World project, it's does the same and it's work.

**Comment by codeinforest** [comment]
> If your application is open-source, can you provide a link to the repository so that we can see the issue happening for ourselves? If it's not open-source, can you boil it down to a small example that reproduces the problem? Because right now I don't have enough information to solve the problem. I'd like to see console logs, what the browser displays when you click the Login button, what's in the Network tab of the browser dev tools, all sorts of things. If you can provide a link to a GitHub repo that reproduces the problem, then I won't have to ask you for all that information a bit at a time and your problem will be solved much sooner.

I can't provide a repo but I can tell you something to make sense.
1. API return status 200.
2. Network has no error. Get 200 http status.
3. After press login, it doesn't redirect but if I refresh the browser, the load() function work => It's mean my credentials valid and has a valid token.
4. If I remove load() function. Then goto() function works.
5. It's only happen if request has no cookie. Because after login success, any functions works exclude logout(). My logout function just set cookie to "". When I click logout button, the cookie set to "" but not redirect. Use trick as I mention above make it work.

===> It's happen when auth token not exist, that's mean I cannot use SSR to navigate. May be this issue happen because I set the cookie from server.

My temp solutions:
- Remove hooks/index.js
- Use goto() function
or
- Refresh page when login / logout

**Comment by rmunn** [comment]
I'm sorry, but without some actual code that I can run on my machine, I'm not going to be able to reproduce the problem with just your description. If you can manage to produce a small example repository — not your main repo, just a small repo that demonstrates the problem with some example code — then I'll be able to help you. But without a repo that reproduces the problem, I'm sorry, but I don't think I'll be able to figure out the problem.

**Comment by codeinforest** [comment]
@rmunn  @benmccann 
Good news: I fixed this issue, it's not about load() function, you can untag this topic, sorry because I created it quite soon.
_Beginning, I follow `real world` project but I don't pay attention to logic. Realworld project don't require login to view the content but my project require logged in user. This is important information._
Below is my issue and solutions, hope it's helpful for someone build dashboard (like me) or anything else with validation.

**Problem:**
In `hooks/index.js` at `handle()` function, I has logic to extract payload then send it to `request.locals`, it require a token. So when I login, I don't have any token at the moment, that why `handle()` always return a invalid value but when I refresh browser, token was set in cookie, that why `load()` function work.

**My solution:**
1. In the `index.svelte` (where you redirect after login), you should **not** validate token or cookie on `load()` function. Use `onMount()` function alternative for validate a $session.
2. In the `login.svelte`, when you logged in, you should set a session (For me: `$session.user = true;`). This session will be send to `index.svelte()` to allow user access to homepage/index.
3. In every routes after login, you can use `load()` function as real world project does.

**Note:**
I use validation by set a cookie with httpOnly flag. If you use other validation method, you should custom `hooks/index.js` to make it work.

**Comment by rmunn** [comment]
@codeinforest -
If you fixed the issue, then you should close it. The Svelte-Kit maintainers can also close it, but it's generally polite to close the issue you opened if you fixed it and the bug report isn't needed any more.

**Comment by codeinforest** [comment]
> @codeinforest -
> If you fixed the issue, then you should close it. The Svelte-Kit maintainers can also close it, but it's generally polite to close the issue you opened if you fixed it and the bug report isn't needed any more.

Okey. If you can untag after I close this thread, I will close it now.
