### ISSUE TITLE
client only components

### ISSUE THREAD

**Issue by happy-little-one** [sveltejs/kit#2468]
### Describe the problem

many components needn't run on the server ,such as dialog, note... , perhaps sveltekit should provide a way to write client-only component.

### Describe the proposed solution

what a about `foo.client.svelte` ?

### Importance

nice to have

**Comment by benmccann** [comment]
See here for tips on how to use a component only on the client-side: https://kit.svelte.dev/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

**Comment by happy-little-one** [comment]
@benmccann  is there any suggested structure for a sveltekit project ?  I read the docs a lot, but still wonder what a regular project look like

**Comment by bluwy** [comment]
Perhaps https://github.com/sveltejs/realworld and the demo app (during `npm init svelte@next`) would help. SvelteKit doesn't really enforce a structure pattern, except for the `lib`, `routes`, etc folders.

**Comment by transbitch** [comment]
> See here for tips on how to use a component only on the client-side: https://kit.svelte.dev/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

Doing that is very annoying. From the docs, the way to do this is:
```
<script>
	import { browser } from '$app/environment';

	const ComponentConstructor = browser ?
		import('some-browser-only-library').then((module) => module.Component) :
		new Promise(() => {});
</script>

{#await ComponentConstructor}
	<p>Loading...</p>
{:then component}
	<svelte:component this={component} />
{:catch error}
	<p>Something went wrong: {error.message}</p>
{/await}
```
...which is a lot of code. Forcing the developer to do this is bad design IMO.

On the other hand,  `foo.client.svelte` is simple and ergonomic. For anyone else reading this, there is a plugin for this, https://github.com/paoloricciuti/svelte-client-components. But based on the fact that the author of that plugin can't even get the naming convention right, I can't vouch for its quality.

**Comment by paoloricciuti** [comment]
> On the other hand, `foo.client.svelte` is simple and ergonomic. For anyone else reading this, there is a plugin for this, https://github.com/paoloricciuti/svelte-client-components. But based on the fact that the author of that plugin can't even get the naming convention right, I can't vouch for its quality.

Hey, author of the plugin who can't even get the naming convention right (silly me). What kind of convention are we talking about?

**Comment by paoloricciuti** [comment]
Btw if you don't care about importing a component even on the server you can use this `NoSSR` component i wrote

```svelte
{#await Promise.resolve() then _}
    <slot />
{/await}
```
and just wrap the part you don't want on the server like this
```svelte
<NoSSR>
    <YourClientComponent />
</NoSSR>
```

**Comment by transbitch** [comment]
> > On the other hand, `foo.client.svelte` is simple and ergonomic. For anyone else reading this, there is a plugin for this, https://github.com/paoloricciuti/svelte-client-components. But based on the fact that the author of that plugin can't even get the naming convention right, I can't vouch for its quality.
> 
> Hey, author of the plugin who can't even get the naming convention right (silly me). What kind of convention are we talking about?

JS doesn't use `snake_case` names. This:
>import { svelte_client_components } from 'svelte-client-components';
should be:
>import { svelteClientComponents } from 'svelte-client-components';

See some other examples [here](https://github.com/vbenjs/vite-plugin-html) and [here](https://github.com/hemengke1997/vite-plugin-public-typescript).

**Comment by paoloricciuti** [comment]
> > > On the other hand, `foo.client.svelte` is simple and ergonomic. For anyone else reading this, there is a plugin for this, https://github.com/paoloricciuti/svelte-client-components. But based on the fact that the author of that plugin can't even get the naming convention right, I can't vouch for its quality.
> > 
> > 
> > Hey, author of the plugin who can't even get the naming convention right (silly me). What kind of convention are we talking about?
> 
> JS doesn't use `snake_case` names. This:
> 
> > import { svelte_client_components } from 'svelte-client-components';
> 
> should be:
> 
> > import { svelteClientComponents } from 'svelte-client-components';
> 
> See some other examples [here](https://github.com/vbenjs/vite-plugin-html) and [here](https://github.com/hemengke1997/vite-plugin-public-typescript).

Well that's really strange because I just did it and JS didn't complain 😏

It's a preference, I feel it makes the code more readable AAAAAND you just need to setup the preprocessor in one file so it's not littering your code if you don't like it.

Next time try to be less rude especially around stuff that is so unimportant.

Peace out ✌🏻

**Comment by transbitch** [comment]
> Well that's really strange because I just did it and JS didn't complain 😏

Doesn't matter.

> It's a preference, I feel it makes the code more readable AAAAAND you just need to setup the preprocessor in one file so it's not littering your code if you don't like it.

You're right, it is a preference. But my personal judgment of the quality of your code is based on those preferences. I see that code in your README and I think "this guy is green behind the ears and doesn't know how to name things", which on a cursory glance doesn't bode well for code quality. I was right, too, as your preprocessor can't handle typescript and causes my build to fail.

> Next time try to be less rude especially around stuff that is so unimportant.

All I said is that I can't recommend your preprocessor. You asked for me to elaborate and I provided a response.

**Comment by paoloricciuti** [comment]
> I was right, too, as your preprocessor can't handle typescript and causes my build to fail.

You just need to put this preprocessor after vitePreprocess, not substitute to it. If you still have issues feel free to open an issue and if my `snake_case` mind will be able to fix it i will do it.

> All I said is that I can't recommend your preprocessor. You asked for me to elaborate and I provided a response.

How i would've said that: "I don't know if the preprocessor is mature enough to be recommended"

How you said it: "But based on the fact that the author of that plugin can't even get the naming convention right, I can't vouch for its quality."

I'd say there's a big difference.

**Comment by FeldrinH** [comment]
> See here for tips on how to use a component only on the client-side: https://kit.svelte.dev/faq#how-do-i-use-x-with-sveltekit-how-do-i-use-a-client-side-only-library-that-depends-on-document-or-window

It is worth noting that as far as I know dynamic imports break tree shaking, so you can end up bloating your bundle size with this workaround.

A more recently added alternative, `export const ssr = false`, is usable in some contexts, but then you lose the ability to do any server-side rendering on the page. For example, if you have one small dynamic component and a bunch of static HTML then you will be forced to render the whole page on the client, which makes the page load feel slower.

 Some kind of client-only components or client-only static imports would be really useful.

**Comment by phocks** [comment]
```svelte
<script>
  import { browser } from '$app/environment';
</script>

{#if browser}
  <div>Hello world!</div>
{/if}
```

Seems to work for me.

**Comment by crowne** [comment]
I had a similar issue recently, and managed to work around it by moving the initialisation code into an onMount function.
