### ISSUE TITLE
TypeScript CommonJS issue

### ISSUE THREAD

**Issue by ISDEdtech** [sveltejs/kit#2469]
### Describe the bug

Hi,
I am getting this after updating to the latest today

.svelte-kit/output/server/app.js:23:7: error: No matching export in "node_modules/tslib/modules/index.js" for import "default"

I have tried a few things to try and replace it with a es6 module (vite alias etc) , but as it is a dependency difficult to change?
Any help out there?

### Reproduction

Have not tried with the latest sample sveltekit repo

### Logs

```shell
Error: Build failed with 1 error:
.svelte-kit/output/server/app.js:23:7: error: No matching export in "node_modules/tslib/modules/index.js" for import "default"
    at failureErrorWithLog (/Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:1478:15)
    at /Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:1136:28
    at runOnEndCallbacks (/Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:1054:65)
    at buildResponseToResult (/Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:1134:7)
    at /Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:1243:14
    at /Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:614:9
    at handleIncomingPacket (/Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:711:9)
    at Socket.readFromStdout (/Users/mike/Documents/workspace/isd-coaching/node_modules/esbuild/lib/main.js:581:7)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:470:12)
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3330S CPU @ 2.70GHz
    Memory: 282.44 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 7.23.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Safari: 14.1.2
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.170 
    svelte: ^3.34.0 => 3.42.6
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
Could you check if it happens with the example app from `npm init svelte@next`? If not, please provide a minimum reproducible.

**Comment by rmunn** [comment]
Another thing you could try is deleting the `.svelte-kit` folder and re-running the build. This should be safe since everything in `.svelte-kit` is temporary stuff created by the build process, but if you're feeling extra cautious, rename `.svelte-kit` to `previous.svetel-kit` or something. Then re-run `build` or `dev` or whatever you're doing, and see if the error goes away.

**Comment by mdeborde** [comment]
It is me (from my account) not ISDEdtech. 
Seemed to be an issue with Firebase, this led to a solution (for now)
https://github.com/firebase/firebase-js-sdk/issues/5499.
Will be more detailed if I post again.
