### ISSUE TITLE
Cannot run npm init svelte@next

### ISSUE THREAD

**Issue by FelixChanCh** [sveltejs/kit#2471]
### Describe the bug

The error I got when I was going to create a new project:

```
> npx: installed 5 in 0.88s
> /home/felix/.npm/_npx/11479/lib/node_modules/create-svelte/bin.js:2
> import fs from 'fs';
```
Should it be `import {fs} from 'fs'` instead? Thanks

### Reproduction

npm init svelte@next

### System Info

```shell
N/A
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
No, it shouldn't be `import {fs} from 'fs'`. It sounds like you're running Node 10 or earlier, which isn't supported, but you didn't fill out the "System Info" section where you should have listed that.

**Comment by Mlocik97** [comment]
He/She use v10.2.2 (/.npm/_npx/**11479**/ - that number inside `_npx` indicate it)
