### ISSUE TITLE
deno svelte kit

### ISSUE THREAD

**Issue by elycheikhsmail** [sveltejs/kit#2472]
### Describe the problem

svelte kit is great project, but building it using node runtime make it difficule to maintain: security pb and modularity system ( node module)

### Describe the proposed solution

svelte kit is great project, but why not use deno instead of node ? this may be a new project but it will not be from scrach.
existing adapter can be updated or rewriting to work.
there are many benefit of using deno :
- good dev experience ( no node_module)
- easy debug, most of deno module are ts
- no loosing all existing work in deno svelte since we use the kanguage
- using existing hosting plus deno deploy
-  and more

### Importance

would make my life easier

**Comment by adebisi-fa** [comment]
This looks something like a deno adapter like this `[adapter-deno](https://github.com/pluvial/svelte-adapter-deno)` can fix.  Can you try this out?

**Comment by Conduitry** [comment]
SvelteKit depends on a number of other projects (notably Vite) that only work in Node. You can use an adapter to produce a build that can run on Deno in production. but it's not even remotely practical for the development experience to also use Deno.

**Comment by DefinitelyMaybe** [comment]
hey could we re-visit this now that deno supports npm and vite?

I've been playing around trying to get deno to run my svelte-kit starter template but coming up with errors atm.

```sh
$ deno task dev
Task dev deno run -A --node-modules-dir npm:vite


  VITE v3.2.4  ready in 1057 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
TypeError: types.isProxy is not a function
    at Object.record<ByteString, ByteString> (file:///home/aaron/Documents/threlte-BVH/node_modules/.deno/undici@5.12.0/node_modules/undici/lib/fetch/webidl.js:267:16)
    at Object.webidl.converters.HeadersInit (file:///home/aaron/Documents/threlte-BVH/node_modules/.deno/undici@5.12.0/node_modules/undici/lib/fetch/headers.js:493:63)
    at new Headers (file:///home/aaron/Documents/threlte-BVH/node_modules/.deno/undici@5.12.0/node_modules/undici/lib/fetch/headers.js:169:32)
    at ServerResponse.<instance_members_initializer> (https://deno.land/std@0.165.0/node/http.ts:244:14)
    at new ServerResponse (https://deno.land/std@0.165.0/node/http.ts:267:5)
    at https://deno.land/std@0.165.0/node/http.ts:579:23
    at new Promise (<anonymous>)
    at handler (https://deno.land/std@0.165.0/node/http.ts:578:16)
    at Object.serve (deno:ext/flash/01_http.js:559:24)
    at async Promise.all (index 0)

```

or maybe someone can point me in the right direction?

**Comment by elycheikhsmail** [comment]
> hey could we re-visit this now that deno supports npm and vite?
> 
> I've been playing around trying to get deno to run my svelte-kit starter template but coming up with errors atm.
> 
> ```shell
> $ deno task dev
> Task dev deno run -A --node-modules-dir npm:vite
> 
> 
>   VITE v3.2.4  ready in 1057 ms
> 
>   ➜  Local:   http://localhost:5173/
>   ➜  Network: use --host to expose
> TypeError: types.isProxy is not a function
>     at Object.record<ByteString, ByteString> (file:///home/aaron/Documents/threlte-BVH/node_modules/.deno/undici@5.12.0/node_modules/undici/lib/fetch/webidl.js:267:16)
>     at Object.webidl.converters.HeadersInit (file:///home/aaron/Documents/threlte-BVH/node_modules/.deno/undici@5.12.0/node_modules/undici/lib/fetch/headers.js:493:63)
>     at new Headers (file:///home/aaron/Documents/threlte-BVH/node_modules/.deno/undici@5.12.0/node_modules/undici/lib/fetch/headers.js:169:32)
>     at ServerResponse.<instance_members_initializer> (https://deno.land/std@0.165.0/node/http.ts:244:14)
>     at new ServerResponse (https://deno.land/std@0.165.0/node/http.ts:267:5)
>     at https://deno.land/std@0.165.0/node/http.ts:579:23
>     at new Promise (<anonymous>)
>     at handler (https://deno.land/std@0.165.0/node/http.ts:578:16)
>     at Object.serve (deno:ext/flash/01_http.js:559:24)
>     at async Promise.all (index 0)
> ```
> 
> or maybe someone can point me in the right direction?

you can discus about this in deno discor,  you can get help there

**Comment by DefinitelyMaybe** [comment]
cheers
