### ISSUE TITLE
router ignore certain paths in configuration

### ISSUE THREAD

**Issue by josvanos** [sveltejs/kit#2487]
### Describe the problem

When a page gets complex and very long, I choose to split the page in multiple components. So i am still able oversee the whole structure of a page.

My current way of splitting looks like this:

I save all the components in a folder outside the routes folder **together**  
-Header.order.svelte
-Table.order.svelte
-Footer.order.svelte
-Table.packing.svelte
ect.

With many page components it gets a mess and sometimes you first search in the routes directory, finding out that you need to be at the page components directory.

 

### Describe the proposed solution

This solution might not only solve my unorganised mess but can also be helpful in other use cases: 

I would like to see a svelte kit configuration property called "ignore ..."  which makes the router ignore paths like: /order/components/  or /clients/components. With this feature i can make a directory "components" in subdirectories of the routes directory that is **not accessible from the web**. 

` {
ignore: "components",
ignore: ['components','bar']
}`

  

### Importance

would make my life easier

**Comment by Conduitry** [comment]
You can already do this just by having a folder name beginning with an underscore. https://kit.svelte.dev/docs#routing-private-modules There's no need to add a configuration option to add further names to ignore.
