### ISSUE TITLE
Setting Session value to `undefined` is ignored in page `load`

### ISSUE THREAD

**Issue by CC-DennisMarkgraf** [sveltejs/kit#2501]
### Describe the bug

I can't pin point exactly since when, but if I change a session store property to `undefined`, `null`, `false` etc. The corresponding page `load` will "ignore" this change and provides the previous value.

### Reproduction

```html
<script lang="ts">
  import type { Session } from "$lib/@types/session";
  import { getStores } from "$app/stores";

  const { session } = getStores<Session>();

  async function logout() {
    try {
      const response = await fetch("/auth/logout");
      if (response.ok) {
        $session.user = undefined; // <-- this worked before
      }
    } catch (error) {
      console.error(error);
    }
  }
</script>

{#if $session.user}
  <div on:click="{logout}">Logout</Button>
{/if}
```

```html
<script lang="ts" context="module">
  import type { Load, LoadOutput } from "@sveltejs/kit";

  import type { PageLoadInput } from "$lib/@types/page";

  export const load: Load<
    PageLoadInput,
    LoadOutput & { user?: UserInfo; }
  > = async ({
    fetch,
    session: {
      user,
    },
  }) => {
    console.log(user); // <-- will never be `undefined`
    return { props: { user } }; 
  };
</script>

…
```

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 507.15 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.5 - ~/.nvm/versions/node/v16.6.1/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Safari: 14.1.2
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Please provide a complete clonable repository as a reproduction.

**Comment by nhe23** [comment]
I also tried to reproduce this issue but couldn't. Setting ```$session.user = undefined;``` updates the user values everywhere and is also properly logged in the load function. Maybe the issue is that the new session value is not persisted on the server. However this works as designed and documented in the SveltKit Docs: '_It can be written to, but this will not cause changes to persist on the server — this is something you must implement yourself._'

**Comment by bluwy** [comment]
Closing due to lack of response from OP.
