### ISSUE TITLE
Unable to use own certificates in dev mode

### ISSUE THREAD

**Issue by taylorzane** [sveltejs/kit#2510]
### Describe the bug

When using SvelteKit in HTTPS mode, it is no longer possible (as of #2232) to specify a collection of HTTPS certificates in the `svelte.config.js` file.

### Reproduction

MVP Repository to cause the error (doesn't actually have certificates, but they're not important at this point)

https://github.com/taylorzane/svelte-kit-https-repro

```
git clone https://github.com/taylorzane/svelte-kit-https-repro
cd svelte-kit-https-repro
npm install
npm run dev # throws a warning, doesn't try to use empty certs object
```

`svelte.config.js`
```js
import fs from 'fs'
import path from 'path'

const keys = []
const certs = []
const cas = []

keys.push(fs.readFileSync(path.join('/path/to/certs', 'key.pem')))
certs.push(fs.readFileSync(path.join('/path/to/certs', 'cert.pem')))
cas.push(fs.readFileSync(path.join('/path/to/certs', 'ca.pem')))

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    target: '#app',
    vite: {
      server: {
        https: {
          key: keys,
          cert: certs,
          ca: cas
        }
      }
    }
  }
}

export default config
```

### Logs

```shell
(full logs are sensitive, but this is the relevant snippet)

$ pnpm run dev
The value for kit.vite.server.https specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.

$ pnpm run dev -- --https
The value for kit.vite.server.https specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 1.93 GB / 32.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nodenv/versions/16.2.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - ~/.nodenv/versions/16.2.0/bin/npm
  Browsers:
    Chrome: 93.0.4577.82
    Firefox: 91.0.1
    Firefox Developer Edition: 79.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.173 
    svelte: ^3.41.0 => 3.42.5
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
Please provide a repository that reproduces this. I can't recreate the steps for all 200+ issues like researching how to generate `.pem` files, etc. It's not scalable and we need issue reporters to help with this work

**Comment by benmccann** [comment]
You wrote this:
```
    vite: {
      server: {
        key: keys,
        cert: certs,
        ca: cas
      }
    }
```

Did you mean to write this?
```
    vite: {
      server: {
        https: {
          key: keys,
          cert: certs,
          ca: cas
        }
      }
    }
```

**Comment by taylorzane** [comment]
Yes, I've edited my original reproduction snippet. I'm working on a repository for this issue, although the actual PEM files don't even need to be generated in order to reproduce the issue. They can be empty arrays and will still be flagged by the `deep_merge` function in [kit/src/core/dev/index.js](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/dev/index.js#L122)

**Comment by taylorzane** [comment]
I've updated my original post to include a link to this repository: https://github.com/taylorzane/svelte-kit-https-repro

**Comment by benmccann** [comment]
Thanks! I was having trouble reproducing. It turns out that I actually was, but there's another bug that was hiding the error message from me: https://github.com/sveltejs/kit/issues/2511 :stuck_out_tongue_closed_eyes:

**Comment by robots4life** [comment]
```js
const config = {
    kit: {
        // hydrate the <div id="svelte"> element in src/app.html
        target: '#svelte',
        vite: () => ({
            server: {
                host: '0.0.0.0',
                port: 3000,
                https: {
                    key: readFileSync('/app.loc.key'),

                    cert: readFileSync('/app.loc.crt')
                },
                hmr: {
                    host: 'app.loc',
                    protocol: 'wss',
                    port: 24678
                }
            }
        })
    }
};
```
I develop under singed certificates locally but unfortunately above config does not work any more.

> The value for kit.vite.server.**host** specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.
> The value for kit.vite.server.**https** specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.

A fix is highly appreciated. :+1: 
Hopefully HMR will continue to work properly, without constant reloading of the page. :crossed_fingers: 
Thank you. :heart: 

Ref: [https://github.com/vitejs/vite/pull/1992](https://github.com/vitejs/vite/pull/1992).

**Comment by EirikFA** [comment]
I am still unable to use custom a HTTPS certificate, it seems SvelteKit is ignoring `kit.vite.server.https`. It works in `next.168`, but not in any newer versions (not even in `next.176` when #2512 was merged..

**Comment by talgolan** [comment]
Absolutely.
