### ISSUE TITLE
HMR indefinitely reloads on startup after upgrading to `1.0.0-next.169`

### ISSUE THREAD

**Issue by techniq** [sveltejs/kit#2519]
### Describe the bug

Upgrading from `1.0.0-next.168` to `1.0.0-next.169` onward causes an infinite reload cycle on startup.

I believe the issue is from the Vite HMR [config](https://vitejs.dev/config/#server-hmr) no longer working / being passed after this [PR](https://github.com/sveltejs/kit/pull/2232).  Might also be a similar issue as what was resolved in https://github.com/sveltejs/kit/commit/0f06e3554bbc354ae47a7d40a8742925bf58e626

I run a dotnet backend with SSL on `https://localhost:5443` and [needed](https://github.com/sveltejs/kit/issues/581#issuecomment-805398830) this configuration to allow the proxy to `http://localhost:3000` to work.

```js
const config = {
  kit: {
    vite: {
      server: {
        hmr: {
          protocol: 'ws',
          port: 3001,
        },
      },
    },
  },
};
```

What's interesting is if I remove the hmr config above, accessing the Vite server directly at `http://localhost:3000` does not reload indefinitely, but if I leave the config in place, `http://localhost:3000` also indefinitely reloads on startup.

### Reproduction

https://github.com/techniq/sveltekit-hmr-reload-issue

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 146.43 MB / 16.00 GB
    Shell: 5.6.2 - /usr/local/bin/zsh
  Binaries:
    Node: 14.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.4.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 94.0.4606.61
    Chrome Canary: 96.0.4656.0
    Firefox: 80.0
    Safari: 15.0
    Safari Technology Preview: 14.2
```

### Severity

blocking an upgrade

**Comment by moisesbites** [comment]
Please, use port 443 and `wss` protocol.
https://github.com/sveltejs/kit/issues/1134#issuecomment-928098710

**Comment by techniq** [comment]
@moisesbites - Thanks.  In my case the port should be `5443` since that is what I have running locally.  I'm not even sure how it ran with port `3001` on version 168.  Maybe SvelteKit was launching another server on that port... anyways, this is the config that now works and allows me to upgrade.

```
const config = {
  kit: {
    vite: {
      server: {
        hmr: {
          protocol: 'wss',
          port: 5443,
        },
      },
    },
  },
};
```

**Comment by moisesbites** [comment]
For version "@sveltejs/kit": "^1.0.0-next.178", maybe you will need to put '--host 0.0.0.0' in the `scripts` in package.json:

```JS
  "scripts": {
    "dev": "svelte-kit dev --host 0.0.0.0",
    "start": "svelte-kit start --host 0.0.0.0",
    "preview": "svelte-kit preview --host 0.0.0.0",
    ....
   }
```

https://github.com/sveltejs/kit/issues/1134#issuecomment-932334309

**Comment by gyurielf** [comment]
I tried the ``--host 0.0.0.0`` everywhere, but didn't help.

I'm on a "true" SPA mode. All of the packages are the latest.

```
client.ts:28 WebSocket connection to 'ws://local.mydev.tld:24679/' failed: 
[vite] server connection lost. polling for restart...
```

I have found that it happens from this ``"@sveltejs/kit": "^1.0.0-next.169"``,
``168`` working fine.

I'm run it in a docker container and use an nginx container as a reverse proxy and pass to the specified ports from the port 80.
(It works on version 168)

My config:
```
kit: {
        target: '#svelte',
        vite: {
            server: {
                hmr: {
                    protocolo: 'ws',
                    port: 24679
                }
            }
        },
        adapter: staticAdapter({
            fallback: '404.html'
        }),
        ssr: false,
        amp: false,
        trailingSlash: 'never'
    }
   
  ```
