### ISSUE TITLE
`sveltekit:invalidate-start` and `sveltekit:invalidate-end` events

### ISSUE THREAD

**Issue by ambrt** [sveltejs/kit#2528]
### Describe the problem

My use case for firing `invalidate-start` is to reload data on same path link and show loading indicator.
(And also to show loading indicator on navigation to different path).

I also think that it would be consistent to have both `start` and `end` events.

### Describe the proposed solution

Dispatch `sveltekit:invalidate-start` on invalidate()

### Importance

would make my life easier

**Comment by benmccann** [comment]
The bug portion of this (firing `navigation-end` without `navigation-start` has been fixed). I've updated the title and description of this issue to reflect the remaining request

**Comment by Rich-Harris** [comment]
This can be solved with the [`navigating`](https://kit.svelte.dev/docs/modules#$app-stores-navigating) store or the [`beforeNavigate`](https://kit.svelte.dev/docs/modules#$app-navigation-beforenavigate) and [`afterNavigate`](https://kit.svelte.dev/docs/modules#$app-navigation-afternavigate) lifecycle functions
