### ISSUE TITLE
[create-svelte] Add the ability to pass in options via the command

### ISSUE THREAD

**Issue by chanced** [sveltejs/kit#2542]
### Describe the problem

It would be nice if `create-svelte` allowed for options to be passed in. For example:

```bash
pnpm init myPackage -- --template skeleton --typescript=true --eslint=true --prettier=true
# the -- is required to inform npm / pnpm to stop parsing
```

### Describe the proposed solution

I have a [pull request ready to go](https://github.com/chanced/kit/blob/add-options-to-create-svelte/packages/create-svelte/bin.js) using [Optionator](https://www.npmjs.com/package/optionator). I'm creating an issue first for discussion.

### Importance

nice to have

**Comment by Conduitry** [comment]
This has come up before in #1231 and #2348, and I explain there why we don't want this.

**Comment by chanced** [comment]
I understand your reasonings. One thing I'd offer is that in the future, once kit is released, it shouldn't be as big of an issue because you can fix the version of the generator which should solve the trouble of breaking APIs relying upon it.

I was in the middle of creating my own template and just figured I'd offer it up. Sorry I created yet another duplicate issue.
