### ISSUE TITLE
Support Dockerfile/Kubernetes spec generation on project bootstrap

### ISSUE THREAD

**Issue by c16a** [sveltejs/kit#2545]
### Describe the problem

Svelte developers need to go through the extra effort of writing Dockerfiles or Kubernetes specifications to deploy the assets.

### Describe the proposed solution

It would be a better developer experience if the project starter also generates a `Dockerfile` and/or a Kubernetes `Deployment` YAML.

This can be an opt-in feature in the interactive prompt.

### Importance

would make my life easier

**Comment by c16a** [comment]
@dominikg This merely adds two optional files during `npm init svelte@next my-app` by prompting the user if they want to enable support for Docker and Kubernetes.

This doesn't imply the devserver via k8s, but offers a template for `Deployment` and `Service`. Ideally, you'd need to add the `sveltjs-static` adapter and have the Docker image expose the static files via httpd or nginx. But doing this would need us to add the adapter which seemed restrictive. Would be open to doing that, if it makes more sense.

**Comment by dominikg** [comment]
What exactly are you looking for?

I don't think create-svelte is the right place to add docker support. Ideally this could be offered via community supported packages, eg a svelte-add or an adapter

**Comment by c16a** [comment]
Alright, will close it.

**Comment by dominikg** [comment]
I do think supporting docker/k8s in some form is worth talking about and implementing. 
But there are different ways to get there and asking users first thing in create svelte and offering suboptimal images that use npm run dev isn't helpful. Novice users would end up with a dangerous setup and experienced users don't save time either as the have to edit it.
