### ISSUE TITLE
Post processors (process prerendered pages)

### ISSUE THREAD

**Issue by MyIsaak** [sveltejs/kit#2549]
### Describe the problem

Preprocessors have a limitation where the processed content happens before data is fetched. SvelteKit added adapters, for example, `adapter-static` which pre-renders all pages from the compiled _and processed_ Svelte web app. Unfortunately, any post-processor might have changes that get removed by hydration. So how can I process the content _after_ SvelteKit's adapter has pre-rendered the page with the fetched data?

### Describe the proposed solution

Post-processors! They process your code after prerendering. With Svelte alone, this won't make much sense, because data is fetched from the browser, where we cannot process the HTML, CSS, and JS inside the browser. However, with SvelteKit we have the luxury (performance) to fully modify the content from the server-side.

### Alternatives considered

I've considered processing via the component level, but unfortunately, it doesn't give me as much control over manipulating the HTML, CSS and JS as strings. 

An external build script is a workaround considered by @dummdidumm. The hydration issue still remains.

Using the `handle` hook suggested by @Conduitry works even better because we have control over pre-rendered data. This still doesn't fix the hydration issue. Another disadvantage is the lack of dynamic execution of script tags. In a preprocessor, I can dynamically insert imports to be resolved by Vite/Rollup plugins. 

### Importance

i cannot use SvelteKit without it

### Additional Information

Considering this feature, it could be the next step forward post `1.0` for image optimization. Meaning that we can optimize not only local images but ones that come from a CMS for example.

**Comment by dummdidumm** [comment]
I don't get the use cases yet. Could you give a pseudo code example? If you talk about prerendered pages, where we talk about plain html/css/js, couldn't you solve this in userland as a postbuild step?

**Comment by MyIsaak** [comment]
Hi @dummdidumm, writing a post-build script is a workaround of the problem: a preprocessor is not able to process fetched data after prerendering.

For example, say we want to process a component that renders from a fetched data
```html
<script context="module">
  export async function load({ page, fetch }) {
    const resArticle = await fetch("/article.json");
    return { props: { article: await resArticle.json() } };
  }
</script>
<script>
  export let article;
</script>
<section>
  <img src={article.mainImgSrc} alt="dynamic image a preprocessor don't see yet" />
  <img src="/images/ok.png" alt="static image visible to a preprocessor" />
</section>
```

A preprocessor that optimizes images would look like:
```js
function imageProcessor() {
  return {
    markup: async function ({ content, filename }) {
      // Problem: the prop hasn't been rendered yet: <img src={article.mainImgSrc} ... 
      // We can only work with static data.. <img src="/images/ok.png"... 
      const [ code, dependencies ] = optimizeImgTags(content);
      return { code, dependencies };
    }
  }
}
```

What if we can use our preprocessor as a post-processor? Hook into the prerendering step? I call it postprocessor because we're processing AFTER the code is rendered.

```js
const config = {
  prerender: {
    entries: "*",
    postprocess: [imageProcessor] // a possible config solution
  }
}
``` 

Allowing preprocessors to work as postprocessors would extend its functionality and allow for more robust compile-time processing. If Svelte can pre-process why not post-process too?

**Comment by Conduitry** [comment]
[The handle hook](https://kit.svelte.dev/docs#hooks-handle) is how I would suggest to do any post-processing on any responses (whether from an endpoint or a page). Is there anything you don't think would be possible with that?

**Comment by MyIsaak** [comment]
Hooks! Yes, how could I miss that? It solves the problem to have access to the data after being fetched right. What's missing is the compile step that works with Vite/Rollup plugins. Perhaps `svelte.preprocess` solves this. I'm going to check.

**Comment by MyIsaak** [comment]
Update: So `svelte.preprocess` doesn't fix the missing compile step issue with Vite/Rollup plugins. It fails with a parsing error, because the input contains the full HTML (header, metas, body). Even if the parsing error is fixed, and the code is recompiled with `svelte.compile`, it can't be pre-rendered again so easily (whilst inside a pre-render loop).

**Comment by Rich-Harris** [comment]
What you describe really isn't possible. You can't apply an arbitrary transformation to rendered HTML and make an equivalent transformation happen to the code that renders the same content in the browser. This isn't a limitation of Svelte, or SvelteKit, it's a more fundamental issue: you have these two processes...

```bash
# SSR
(app, state) -> HTML

# CSR
(app, state) -> DOM
```

...and you're trying to affect the second output by transforming the first output. Instead, you have to transform the _inputs_ — either you have to somehow change the code (`app`), or you have to pass in optimized image URLs (`state`).

For image optimisation specifically there's an issue which we'll get round to addressing one day: #241
