### ISSUE TITLE
page does not rerender when param change

### ISSUE THREAD

**Issue by happy-little-one** [sveltejs/kit#2553]
### Describe the bug

routes/news/[id]/index.svelte

```
<script context="module">
export async function load() {
  return {
    props: {
      text: Math.random(),
    },
  }
}
</script>

<script>
import { goto } from '$app/navigation'
export let text

function on_next() {
  goto(`/news/${Math.floor(Math.random() * 100)}`)
}
</script>

<h1>{text}</h1>

<button on:click={on_next}>next</button>

```

after the first click, click again, the page param id changed, but the `text` keep as it is.

### Reproduction

https://github.com/happy-little-one/sveltekit

### System Info

```shell
none
```

### Severity

blocking an upgrade

**Comment by ignatiusmb** [comment]
Also described in the docs, please read https://kit.svelte.dev/docs#loading-input
