### ISSUE TITLE
Allow for .css?inline to be excluded from head in SSR

### ISSUE THREAD

**Issue by ambrt** [sveltejs/kit#2556]
### Describe the problem

Basically, SSR version of page that imports CSS has all imported CSS dumped into header.
They are collected here
https://github.com/sveltejs/kit/blob/5e14ce9298e6b4c818c21009d7306c92bea108c8/packages/kit/src/runtime/server/page/render.js#L50
and inserted here
https://github.com/sveltejs/kit/blob/5e14ce9298e6b4c818c21009d7306c92bea108c8/packages/kit/src/runtime/server/page/render.js#L156-L160

The problem is that what is  added in  `svelte:head` is _followed_ by  insert so css that goes into  `svelte:head` is overwritten by css that's imported.
Vite allows for `?inline` css import to be read into variable.
So to be consistent with Vite, Kit should exclude `?inline`  imports from the head.

### Describe the proposed solution

Filter ?inline css imports from header insert.

#### Change order
Change order in array:
https://github.com/sveltejs/kit/blob/5e14ce9298e6b4c818c21009d7306c92bea108c8/packages/kit/src/runtime/server/page/render.js#L156-L163
to
```
const head = [
		styles.size && !options.amp
			? `<style data-svelte>${Array.from(styles).join('\n')}</style>`
			: '',
		rendered.head,
		links,
		init
	].join('\n\n\t\t');
```
Although this solution will allow for overwriting of imports by svelte:head it will leave all css that is imported and not overwritten 
in DOM.
So its not a solution for switching css'es dynamically without having to have each selector explicitly overwritten, for example.

#### node.styles
I'm not sure where `node.styles` are collected. Maybe it would be better to exclude it on import instead
of when using in template.

### Importance

I cannot use SvelteKit without it

**Comment by Rich-Harris** [comment]
Late to this (sorry), but can you create a repro? It's not clear from the description what the expected vs actual behaviour is

**Comment by Rich-Harris** [comment]
Going to close this as there's no repro and I don't understand the problem — feel free to open a new issue with a repro
