### ISSUE TITLE
Deployed HN clone at `hn.svelte.dev` is old version using Sapper

### ISSUE THREAD

**Issue by flbn** [sveltejs/kit#2558]
### Describe the problem

It looks like [hn.svelte.dev](https://hn.svelte.dev) might still be using Sapper, or at least the build is not up to date with the current repositories build. I noticed this due to the about page saying it's using Sapper, and the latest version of the Svelte Kit HN Clone repository having replaced that part with SvelteKit. After looking into it a bit more, all of the about page information point to Sapper docs. Obviously not a major issue, just felt like it was pertinent enough to point out! 

### Describe the proposed solution

Easiest solution would be to build and deploy the current version of Svelte Kit's HN Clone source code.

### Alternatives considered

The process could be automated with some CI/CD deployment but that sounds like a lot of work, lol.

### Importance

nice to have

**Comment by Addeuz** [comment]
Hello, I think this would be an issue I could try to take on.
However I saw that https://github.com/sveltejs/hn.svelte.dev is archived, so how would one go about doing pull requests etc for migrating to Kit?

Also I would have no idea on how the deployment is done..

**Comment by benmccann** [comment]
As the readme for that project states, the new version lives in this repo: https://github.com/sveltejs/kit/tree/master/examples/hn.svelte.dev

**Comment by flbn** [comment]
i suppose this can just be deployed when Kit hits 1.0. It's not a minor issue.

**Comment by dreitzner** [comment]
@benmccann should this not also be moved to https://github.com/sveltejs/sites?

**Comment by benmccann** [comment]
No, I don't think it should be. It's helpful when developing SvelteKit to have example apps in the repo

**Comment by dreitzner** [comment]
> No, I don't think it should be. It's helpful when developing SvelteKit to have example apps in the repo

Right! I didn't think of that.

**Comment by benmccann** [comment]
This is fixed now. See https://hn.svelte.dev/about
