### ISSUE TITLE
ESI (Edge Side Includes) hydration

### ISSUE THREAD

**Issue by mmarchois** [sveltejs/kit#2561]
### Describe the bug

I have created an ESI (Edge Side Includes) component that adds the `esi:include` tag to the DOM. This one calls a fragment middleware that returns a component with the `Component.render()` method.

Here is my esi component :
``` 
<script lang="ts">
  import { session } from '$app/stores';

  const urlObj = new URL('/_fragment', $session.siteUrl);

  const url = urlObj.pathname + urlObj.search;
</script>

<esi:include src={url} />
```

Here is my middleware called in hooks.ts: 
```
import 'svelte/register';

export async function esiMiddleware(request) {
  const component = (await import('../../components/Test.svelte')).default);
  const { html, css: { code: cssCode } } = component.render();

  return {
    body: `<style>${cssCode}</style>${html}`,
  };
}
```

Then i call the esi component where i need it from `<Esi />`

I've set up a varnish that takes the esi:include into account and gives it back to me on the server side.
The problem I have is that the ESI rendered component disappears due to client side hydration.

Shouldn't hydration be deactivated when an esi is present?

### Reproduction

I can't share any repository because it is private, but it's just an ESI implementation.

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 283.77 MB / 15.34 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
    npm: 7.20.1 - ~/.nvm/versions/node/v14.17.2/bin/npm
  Browsers:
    Brave Browser: 94.1.30.87
    Chrome: 93.0.4577.82
    Firefox: 92.0
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
This isn't something we're ever likely to support natively, and for the forseeable future it wouldn't be possible anyway since Svelte doesn't yet have any concept of partial hydration.

But you can approximate it by simply querying the DOM and reusing the HTML:

```svelte
<script>
  import { browser } from '$app/env';

  export let src;
</script>

<div data-esi={src}>
  {#if browser}
    {@html document.querySelector(`[data-esi="${src}"]`)?.innerHTML ?? '&lt;esi:include&gt only works with SSR'}
  {:else}
    <esi:include {src}/>
  {/if}
</div>
```

A more sophisticated version could work with client-side navigation as well, if you don't mind a little flash of missing content in cases where the include wasn't cached:

```svelte
<script context="module">
  const cache = new Map();
</script>

<script>
  import { browser } from '$app/env';

  export let src;

  let content = '';

  if (browser) {
    if (cache.get(src)) {
      content = cache.get(src);
    } else {
      const element = document.querySelector(`[data-esi="${src}"]`);
      if (element) {
        cache.set(src, content = element.innerHTML);
      } else {
        onMount(async () => {
          const res = await fetch(src);
          cache.set(src, content = await res.text())
        });
      }
    }
  }
</script>

<div data-esi={src}>
  {#if browser}
    {@html content}
  {:else}
    <esi:include {src}/>
  {/if}
</div>
```

[Here's a demo](https://stackblitz.com/edit/sveltejs-kit-template-default-4cnezk?file=src%2Flib%2FEsi.svelte&terminal=dev), using `hooks.js` to simulate the replacement.
