### ISSUE TITLE
cannot specify build target

### ISSUE THREAD

**Issue by m4rch3n1ng** [sveltejs/kit#2565]
### Describe the bug

while running `svelte-kit build` i cannot set the build target, it says
`"build_server: The value for kit.vite.build.target specified in svelte.config.js has been ignored. This option is controlled by SvelteKit."`
and when i then try to build a project where i use BigInt it says
`"> Transform failed with 1 error:
app.js:2052:9: error: Big integer literals are not available in the configured target environment ("es2018")"`

### Reproduction

1. create an empty ("skeleton") sveltekit project (with the node-adapter)
2. create an `index.js` file in `src/routes` and fill it with
```js
export function get () {
	let n = 10n

	return {
		status: 200,
		body: n.toString()
	}
}
```
3. overwrite your svelte.config.js to
```js
import node from "@sveltejs/adapter-node"

export default {
	kit: {
		adapter: node(),
		vite: {
			build: {
				target: "esnext"
			}
		}
	}
}
```

### Logs

```
$ npm run build

> test@0.1.0 build
> svelte-kit build --verbose

vite v2.6.3 building for production...
✓ 13 modules transformed.
.svelte-kit/output/client/_app/manifest.json               0.96 KiB
.svelte-kit/output/client/_app/layout.svelte-65943d9d.js   0.53 KiB / gzip: 0.35 KiB 
.svelte-kit/output/client/_app/error.svelte-1cfc6a4a.js    1.56 KiB / gzip: 0.74 KiB 
.svelte-kit/output/client/_app/assets/start-61d1577b.css   0.16 KiB / gzip: 0.15 KiB 
.svelte-kit/output/client/_app/start-6f07df61.js           15.17 KiB / gzip: 5.91 KiB
.svelte-kit/output/client/_app/chunks/vendor-af0f2ef7.js   7.08 KiB / gzip: 2.89 KiB 
  build_server: The value for kit.vite.build.target specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.
vite v2.6.3 building SSR bundle for production...
✓ 14 modules transformed.
[vite:esbuild-transpile] Transform failed with 1 error:
app.js:2052:9: error: Big integer literals are not available in the configured target environment ("es2018")

Big integer literals are not available in the configured target environment ("es2018")
2050|  
2051|  function get () {
2052|   let n = 10n;
   |           ^
2053|  
2054|   return {

> Transform failed with 1 error:
app.js:2052:9: error: Big integer literals are not available in the configured target environment ("es2018")
Error: Transform failed with 1 error:
app.js:2052:9: error: Big integer literals are not available in the configured target environment ("es2018")
    at failureErrorWithLog (C:\Users\User\OneDrive\Programming\small_projects\javascript\testing\sveltekit\nft\test\node_modules\esbuild\lib\main.js:1493:15)
    at C:\Users\User\OneDrive\Programming\small_projects\javascript\testing\sveltekit\nft\test\node_modules\esbuild\lib\main.js:1282:29
    at C:\Users\User\OneDrive\Programming\small_projects\javascript\testing\sveltekit\nft\test\node_modules\esbuild\lib\main.js:629:9
    at handleIncomingPacket (C:\Users\User\OneDrive\Programming\small_projects\javascript\testing\sveltekit\nft\test\node_modules\esbuild\lib\main.js:726:9) 
    at Socket.readFromStdout (C:\Users\User\OneDrive\Programming\small_projects\javascript\testing\sveltekit\nft\test\node_modules\esbuild\lib\main.js:596:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

### System Info

```shell
  System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 8.02 GB / 15.93 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.24.1 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.53
    @sveltejs/kit: next => 1.0.0-next.180
    svelte: ^3.43.0 => 3.43.1
```

### Severity

serious, but I can work around it

### Additional Information

_no additional information_

**Comment by gunggmee** [comment]
This PR by @GrygrFlzr is the one introduced `target: 'es2018'` and there're explanation for the reason behind it: https://github.com/sveltejs/kit/pull/486#issuecomment-797194660

As I see it, es2018+ is there to support async/await syntax. Does it mean that we can simply change the value to `es2020`? Or at least can we allow users to override the target with any value satisfying `es2018+`?

**Comment by gunggmee** [comment]
Just found that one of yesterday's PRs (#2604) partially solved the issue. Now the target is `es2020` so it is okay to use big integer literals, but it still shows a warning if `svelte.config.js` tries to override the target.

**Comment by bluwy** [comment]
I think we should allow `build.target` to be changed, and have `es2020` as the default. I don't think it would be easy to validate the value to be higher than `es2020` though, esbuild's `target` option is magnificently flexible, e.g. `chrome80`, `firefox90`. If one sets a lower value, then Vite should (hopefully) provide a nice message for what to do. Feel free to send a PR to apply my first sentence :)

**Comment by gunggmee** [comment]
@bluwy Thanks for helpful comment. Just made a draft PR. Could you please take a look at it, and let me know if this is a good way to go?
