### ISSUE TITLE
Remove relative path references in adapters

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2569]
### Describe the bug

The best idea I have so far is that instead of writing the server output to `.svelte-kit/output/server`, we could try writing it to something like `node_modules/@sveltejs/user-app` (or maybe `src/node_modules` like Sapper does) with a `package.json` file:

```
		{
			"name": "@sveltejs/user-app",
			"version": "0.0.1",
			"private": true,
			"type": "module",
			"main": "app.js"
		}
```

The relative path is stopping adapter authors from using the types

I also think that after this is fixed that we can use Vite to do a single build pass instead of doing a second build step with `esbuild` in the adapters 

### Reproduction

For example: https://github.com/sveltejs/kit/blob/ff35e8d50a344835480a0b79ad6b4fcfb2ebcace/packages/adapter-node/src/middlewares.js#L1

We should make sure @jthegedus can consume the types in the firebase adapter after this is fixed

### System Info

```shell
`master`
```

### Severity

annoyance

**Comment by Mlocik97** [comment]
I don't think it's good idea to write this to node_modules (it caused problems in Sapper).

**Comment by Mlocik97** [comment]
what about putting `node_modules` to `.svelte-kit` ?

**Comment by benmccann** [comment]
No longer an issue: 

https://github.com/sveltejs/kit/blob/7b79522e0e22cbed61c196558fd5607a860bdbc3/packages/adapter-node/src/handler.js#L7
