### ISSUE TITLE
Service Worker Fallback Page Not Working

### ISSUE THREAD

**Issue by lubiah** [sveltejs/kit#2570]
### Describe the bug

So am using sveltekit for my website and I have implemented a service-worker.
Everything works fine but the problem am having is that, the fallback page which is an `offline.html` file, doesn't work onless the page is being refreshed. 
Here is the service worker file.
```svelte
self.addEventListener("fetch", event =>{
	if (event.request.method !== 'GET' || event.request.headers.has('range')) return;

	event.respondWith(
		
		caches.match(event.request)
		.then(response => {
			if (response)
				return response
			return fetch(event.request, {mode:"no-cors"})
			.then(fetch_res=>{
				if (!fetch_res || fetch_res.status !== 200)
					return fetch_res;
				return caches.open(dynamic_cache)
				.then(cache =>{
					cache.put(event.request.url, fetch_res.clone());
					limitCacheSize(dynamic_cache,80);
					return fetch_res;
				})
			})
			.catch(err=>{
		
			if (event.request.mode === "navigate"){
				return caches.match("/offline.html");	
				}
			});
		})
		)
})
```
If I try to log to the console, the service worker sends the fallback page but on my website, it turns to a 500 status error. 
Then when I refresh the page, the fallback page will then work

### Reproduction

Okay, to reproduce;
 * `git clone https://github.com/biah/www.kudadam.com.git`
 * npm install
 * npm run build

### System Info

```shell
System:
    OS: Windows 8.1 6.3.9600
    CPU: (2) x64 Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz
    Memory: 252.85 MB / 1.93 GB
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.9600.17037
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.46 => 1.0.0-next.46
    @sveltejs/kit: next => 1.0.0-next.174
    svelte: ^3.34.0 => 3.42.4
```

### Severity

annoyance

**Comment by abdo643-HULK** [comment]
If you are using the sveltekit router it doesn't trigger a real navigation and that is why you will never see the offline page. A reload counts as a navigation from the browser and that's why you see the page. You could use the online/offline event to show a status information or hook into the svelte router events and check if your offline and reroute.

**Comment by abdo643-HULK** [comment]
> > If you are using the sveltekit router it doesn't trigger a real navigation and that is why you will never see the offline page. A reload counts as a navigation from the browser and that's why you see the page. You could use the online/offline event to show a status information or hook into the svelte router events and check if your offline and reroute.
> 
> Do you know any code which I can use to do this???

https://github.com/La-Mediterranee/Web-App this is a Project I am working on. I am showing a statusbar. You can find it in the __layout component.
