### ISSUE TITLE
Packaging won't include TS files that include word 'types'

### ISSUE THREAD

**Issue by TeemuKoivisto** [sveltejs/kit#2573]
### Describe the bug

I was really puzzled why I received type errors about non-existent files having ran `svelte-kit package` for my library. Yet the cause was even puzzling because apparently the command just didn't package types that included word `types` in their name.

### Reproduction

https://github.com/TeemuKoivisto/svelte-kit-packaging-types-bug

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 97.85 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v16.7.0/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.71
    Firefox: 92.0.1
    Safari: 13.1.3
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.180 => 1.0.0-next.180 
    svelte: ^3.43.1 => 3.43.1
```

### Severity

serious, but I can work around it

**Comment by ignatiusmb** [comment]
It's because you're excluding them in your `package.files` config with this code in line 20 of your `svelte.config.js`

```js
if (['__tests__', 'types.ts'].some(s => filepath.includes(s))) return false
```
