### ISSUE TITLE
Ability to run a single test app

### ISSUE THREAD

**Issue by JeanJPNM** [sveltejs/kit#2585]
### Describe the problem

Testing created or edited integration tests is currently a very slow process, since all the test apps have to run their own tests.

### Describe the proposed solution

Add an option to the `pnpm test` command to select a particullar app to test

### Alternatives considered

Create test subcommands (`pnpm test:<app-name>`) to select the test app

### Importance

nice to have

**Comment by Rich-Harris** [comment]
This is now much simpler — just `cd` into a test app (like `test/apps/basics`) and run `pnpm test`. It's effectively self-documenting via npm run scripts, so I'll close this

**Comment by benmccann** [comment]
Documented in the contributing guide: https://github.com/sveltejs/kit/blob/master/CONTRIBUTING.md#testing
