### ISSUE TITLE
Goto vs <a href>

### ISSUE THREAD

**Issue by x4080** [sveltejs/kit#2593]
### Describe the problem

I have navigation links using a href that svelte will prefetch the link automatically so that if the link in a href is clicked
the page is instantly show up (good)

Then I tried same thing using button (programmatically) -> using goto and the result is that the link that clicked is NOT loading instantly

### Describe the proposed solution

Maybe there's option to use the prefetch links like using a href for goto function ?

### Importance

nice to have

### Additional Information

Thanks, and sorry if it already implemented

**Comment by ignatiusmb** [comment]
Anchor tags needs and detects if there's the [`sveltekit:prefetch`](https://kit.svelte.dev/docs#anchor-options-sveltekit-prefetch) attribute for it to have that "instant" feeling, and the last part mentions that you can invoke `prefetch` programmatically from `$app/navigation`, which I think is what you're looking for here
