### ISSUE TITLE
Component discovery

### ISSUE THREAD

**Issue by dreitzner** [sveltejs/kit#2594]
### Describe the problem

Let's assume there is a CMS that feeds into a svelte-kit website.

A content editor in the CMS should have the ability to use different modules inside the CMS which would translate into Svelte components, like Headline, Image, Paragraph, etc.

Currently there is no way to generically Render components driven by an outside source (to my knowledge).

it would be great to be able to use something like this:
```
{#each cmsEntity as {id, name, data}(id)}
  <svelte:component {name} {data} />
{/each}
```

### Describe the proposed solution

Something similar to Nuxt.js' component discovery.

https://nuxtjs.org/docs/features/component-discovery/

```
Folder structure:
/lib/components
|- Header.svelte
|- /base
  |- Button.svelte
```
```
// use it in index.svelte route without import
<Header />
<BaseButton>Click Me</BaseButton>
```

The base component directory could also be something that is exposed through the config, but I think having it only one way would be preferable.

### Importance

nice to have

**Comment by Prinzhorn** [comment]
> Something similar to Nuxt.js' component discovery.

I think the difference here is that you want that _at runtime_. What you've linked happens _at compile time_

The common solution to your problem is to keep a `Map<String, Component>` (or similar) in a js file and then lookup the component by it's name/key/id at runtime. This also has the benefit that you need to be explicit about what components are "blessed" and can be used by your CMS. You don't want someone to inject arbitrary components (with arbitrary props), which can lead to XSS or other isses.

```
{#each cmsEntity as {id, name, data}(id)}
  <!-- TODO: handle lookup errors (unknown name), bless/validate certain props -->
  <svelte:component this={cmsComponents.get(name)} {data} />
{/each}
```

**Comment by yuanchuan** [comment]
I've used this plugin I wrote and it works pretty well. I post it here in case of it'll meets your need.

https://github.com/yuanchuan/vite-plugin-autoimport

**Comment by dreitzner** [comment]
@yuanchuan that is really awesome 🥳

I'll close this issue and will use that if I ever need it.

Thank you for your awesome contribution.... Maybe we can add it to the recipes on svelte society :)

**Comment by dominikg** [comment]
Note that using auto-import and thud not adding explicit imports to a .svelte file prevents static analysis like vite optimizer from scanning them correctly.

I don't recommend it and suggest to use IDEs auto-generating imports for you as you type up your template.
