### ISSUE TITLE
Unobtrusive JavaScript

### ISSUE THREAD

**Issue by bojanv55** [sveltejs/kit#2601]
### Describe the problem

Is there a way to write unobtrusive JavaScript in svelte?

Let's say I have following HTML:

    <select name="cars" id="cars">
      <option value="volvo">Volvo</option>
      <option value="saab">Saab</option>
    </select>

Now, since I want to style this, I would have to transform this internally to something that would not be accessible anymore as a `select` element, for example:

    <button name="cars" id="cars>Select...</button>
    <ul>
      <li>Volvo</li>
      <li>Saab</li>
    </ul>

In the context of classic Svelte - I guess this question is actually meaningless (since everything is generated by JS - I guess I would here just create standard svelte component that would render ul's and li's as needed.

But if using SSR in svelte-kit - this question is valid I guess?

### Describe the proposed solution

Unobtrusive JavaScript

### Importance

nice to have

**Comment by Conduitry** [comment]
I'm really not sure what this is asking for. Magically transforming a select into an unordered list so you can style it more easily?

**Comment by bojanv55** [comment]
Yes. Basically rendering accessible elements that have semantic meaning (like that select box), and then replace it by JS with different elements on load - elements that would be easier to style and present to end user.

@dummdidumm  - yes, aria-roles is one solution for this.

@Conduitry not auto-magically - but you would have to write the code to transform and replace all <select> elements on js render.
