### ISSUE TITLE
Prebundling of libraries with Svelte components

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2612]
### Describe the bug

See https://github.com/illright/attractions/issues/311#issuecomment-944701061 for the original report

It was loading all of `svelte-feather-icons` when you use just a few icons. Vite is supposed to do dependency pre-bundling to avoid this: https://vitejs.dev/guide/dep-pre-bundling.html#the-why. However, Vite's pre-bundling uses esbuild, so we disabled it on Svelte components because it doesn't know what to do with `.svelte` files.

[Evan has proposed changing this](https://github.com/vitejs/vite/discussions/4921). I'm finally a convert to the idea.

### Reproduction

Try to use `svelte-feather-icons`

### Logs

```shell
https://github.com/illright/attractions/ was making 485 requests for each page in dev mode taking 10s to load
```

### System Info

```shell
Vite 2.6.7
```

### Severity

serious, but I can work around it

### Additional Information

You can work around it by doing deep imports

**Comment by antony** [comment]
This was the same in Sapper. Reloads were taking 60 seconds. I made a reduced version of the library including only the icons we required, and reloads started taking 20 seconds. Game changer.

I suppose what this means is that, the library isn't properly tree-shakeable.

**Comment by dominikg** [comment]
Until vite can pre-bundle svelte libraries it's best to use deep imports to avoid paying the tax of loading all exported svelte components. 

Icon libraries are usually the worst in this context, luckily https://github.com/antfu/unplugin-icons does not suffer from this.

**Comment by benmccann** [comment]
Wow, that's a great solution! Yeah, I wonder if we could tweak that library and use it generally. I've asked the author in https://github.com/carbon-design-system/carbon-preprocess-svelte/issues/20

**Comment by bluwy** [comment]
I think we discussed something similar too about transforming the entrypoint with only the named imports, so it works more generically. The preprocessor technique is interesting though, I suppose it can be worked around by checking the `exports` field and naively work with that.

Anywho, I've been working today on actually prebundling Svelte libraries. It seems to be working on [this branch](https://github.com/sveltejs/vite-plugin-svelte/tree/prebundle-svelte-libraries). Wish I thought about it sooner :smile:  The caveats now are that:

1. Prebundling would take a while (6s for `carbon-components-svelte`), but that's negligible in the long run.
2. Deeply importing Svelte components is not compatible, it could cause multiple instance of `carbon-components-svelte` running. Unless we force prebundle that nested import too. Could be a bug in Vite

In that branch, I have a [big-component-library](https://github.com/sveltejs/vite-plugin-svelte/tree/prebundle-svelte-libraries/packages/playground/big-component-library) playground to test out. I'd appreciate if anyone likes to test this in their project as well.

**Comment by benmccann** [comment]
Vite 2.9 will add better support for prebundling Svelte libraries: https://github.com/vitejs/vite/pull/6801

**Comment by bluwy** [comment]
I haven't got any negative feedback so I hope all's good with `prebundleSvelteLibraries` 😄 I'll try to get this stabilized once Vite 3 lands. There's a lot of moving parts with the optimizer in Vite 3, so there's a chance `prebundleSvelteLibraries` needs tweaks for it to work later.

**Comment by benmccann** [comment]
Since `vite-plugin-svelte` 1.0 this option can now be set with the following in `svelte.config.js`:
```
  vitePlugin: {
    experimental: {
      prebundleSvelteLibraries: true
    }
  }
```

**Comment by benmccann** [comment]
The main thing to do before graduating from experimental is probably https://github.com/sveltejs/vite-plugin-svelte/issues/419

**Comment by ZetiMente** [comment]
Been using vitePlugin: { experimental: { useVitePreprocess: true }} for a fairly large web app & it has been great ! Except the annoying messages in the build, there has been no issues. It also handles the css background image url and a few other things better. And it allows you to remove Svelte preprocess from your package !

**Comment by dominikg** [comment]
SvelteKit currently has prebundleSvelteLibraries forcefully enabled via inline config to vite-plugin-svelte.

We are still working on enabling it by default in vite-plugin-svelte, which should happen in it's next feature release. See https://github.com/sveltejs/vite-plugin-svelte/pull/494

After that SvelteKit can remove that setting from it's own code and users will be able to disable it completely if they so desire. 
See https://github.com/sveltejs/vite-plugin-svelte/pull/494#issuecomment-1318620849 for a preliminary explaination of prebundling svelte libraries, index imports vs deep imports and large component libraries and why it isn't always the best to prebundle. vite-plugin-svelte docs are going to explain it in more detail.
