### ISSUE TITLE
Remove globals

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2631]
### Describe the problem

Globals mean you can have only a single router, which means we don't support microfrontends

It also makes testing harder

### Describe the proposed solution

Router / application instances vs globals

### Importance

nice to have

**Comment by AlbertMarashi** [comment]
Ah I see, that's what I was thinking.

**Comment by benmccann** [comment]
Yeah, I put this here as a thing to think about for myself, but after doing so for a bit, I'm not entirely sure what it would mean to do so. Having a single global router sort of makes sense - there's only one URL bar. But what we're missing is a way to define new routes in other modules and register additional routes. Maybe that's a better / more concrete goal
