### ISSUE TITLE
adapter-static data:image URL error 404

### ISSUE THREAD

**Issue by leighwilliams** [sveltejs/kit#2645]
### Describe the bug

Hi,

I'm trying to use an emoji favicon as described here: https://css-tricks.com/emojis-as-favicons/

``` html
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💥</text></svg>">
```

When building this with adapter-static it fails to handle the data:image/svg URL:

```
Error: 404 /%22data:image/svg+xml,%3Csvg (linked from /)
```

### Reproduction

https://github.com/leighwilliams/svelte-kit-repro

1. npm run build

### Logs

```shell
...
> Using @sveltejs/adapter-static
> 404 /%22data:image/svg+xml,%3Csvg (linked from /)
Error: 404 /%22data:image/svg+xml,%3Csvg (linked from /)
    at file:///project/node_modules/@sveltejs/kit/dist/chunks/index4.js:86:11
    at visit (file:///project/node_modules/@sveltejs/kit/dist/chunks/index4.js:213:5)
    at async visit (file:///project/node_modules/@sveltejs/kit/dist/chunks/index4.js:281:6)
    at async prerender (file:///project/node_modules/@sveltejs/kit/dist/chunks/index4.js:291:6)
    at async Object.prerender (file:///project/node_modules/@sveltejs/kit/dist/chunks/index4.js:353:4)
    at async adapt (file:///project/node_modules/@sveltejs/adapter-static/index.js:13:4)
    at async adapt (file:///project/node_modules/@sveltejs/kit/dist/chunks/index4.js:378:2)
    at async file:///project/node_modules/@sveltejs/kit/dist/cli.js:878:5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 142.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.volta/tools/image/node/14.17.0/6.14.13/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 6.14.13 - ~/.volta/tools/image/node/14.17.0/6.14.13/bin/npm
  Browsers:
    Brave Browser: 93.1.29.79
    Chrome: 94.0.4606.81
    Firefox: 93.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21
    @sveltejs/kit: next => 1.0.0-next.184
    svelte: ^3.34.0 => 3.43.2
```

### Severity

annoyance

**Comment by gg187on** [comment]
hello, I would like to work on this issue.

**Comment by Mlocik97** [comment]
OK, I was searching about solution, but what I can see is that regex is not correct way, as it can't do recursion and is only  Chomsky Type 3 grammar, while HTML itself is XML based means Chomsky Type 2 grammar, and as Type 2 is more complex, it would make sense to use parser instead regex.

**Comment by gg187on** [comment]
OK, I was searching about solution, but what I can see is that regex is not correct way, as it can't do recursion and is only  Chomsky Type 3 grammar, while HTML itself is XML based means Chomsky Type 2 grammar, and as Type 2 is more complex, it would make sense to use parser (AcornJS?) instead regex.

The problem is mainly nested tags inside attribute of link tag. That makes impossible for regex to parse correctly. Even tho, I got nearly good result with regex:

```js
const pattern = /<(a|img|link|source)(?:\s+\w+\s*=\s*"([^"]+?)")*>/gm;
```
