### ISSUE TITLE
CSS psuedo selector ':target' issue

### ISSUE THREAD

**Issue by Kainkainkain** [sveltejs/kit#2667]
### Describe the bug

CSS 3 pseudo selector :target fails to work when it should. When the target of an anchor fragment link e.g. `<a href="#p1">` is clicked, the url shows the #p1 but 
CSS target electors fail until it is clicked a second time.

Works fine in svelte, so must be something to do with routing in sveltekit? 

### Reproduction

Paste this into any .svelte in sveltekit project:
```svelte
<h3>Target test</h3>
<ol>
 <li><a href="#p1">Jump to the first paragraph!</a></li>
 <li><a href="#p2">Jump to the second paragraph!</a></li>
 <li><a href="#nowhere">This link goes nowhere,
   because the target doesn't exist.</a></li>
</ol>

<h3>My Fun Article</h3>
<p id="p1">You can target <i>this paragraph</i> using a
  URL fragment. Click on the link above to try out!</p>
<p id="p2">This is <i>another paragraph</i>, also accessible
  from the links above. Isn't that delightful?</p>


<style>
p:target {
  background-color: gold;
}
</style>
```

### System Info

```shell
Package.json
{
  "name": "sveltekit_ssg_tw",
  "version": "0.0.1",
  "scripts": {
    "dev:only": "svelte-kit dev",
    "build:only": "svelte-kit build",
    "preview": "svelte-kit preview",
    "tailwind:watch": "cross-env TAILWIND_MODE=watch cross-env NODE_ENV=development postcss src/styles/tailwind.css -o src/styles/tailwind-output.css -w",
    "tailwind:build": "cross-env TAILWIND_MODE=build cross-env NODE_ENV=production postcss src/styles/tailwind.css -o src/styles/tailwind-output.css",
    "dev": "concurrently \"npm run dev:only\" \"npm run tailwind:watch\"",
    "build": "npm run tailwind:build && npm run build:only"
  },
  "devDependencies": {
    "@sveltejs/adapter-netlify": "^1.0.0-next.32",
    "@sveltejs/adapter-static": "^1.0.0-next.20",
    "@sveltejs/kit": "next",
    "autoprefixer": "^10.3.6",
    "concurrently": "^6.2.2",
    "cross-env": "^7.0.3",
    "postcss-cli": "^9.0.1",
    "svelte": "^3.43.1",
    "svelte-fa": "^2.3.3",
    "tailwindcss": "^2.2.16"
  },
  "type": "module",
  "dependencies": {
    "@fortawesome/free-brands-svg-icons": "^5.15.4",
    "@fortawesome/free-solid-svg-icons": "^5.15.4",
    "@tailwindcss/forms": "^0.3.4"
  }
}
```

### Severity

annoyance

**Comment by johnknoop** [comment]
Any update on this?

**Comment by bluwy** [comment]
I didn't have time to tackle this unfortunately. IIRC an easy fix can be implemented, but it'll be hacky and possibly cause unwanted side effects. Ideally a proper solution for how we handle hashes in general is needed, but I haven't got there yet. Feel free to take a stab and make a PR if you're interested!

**Comment by hyeonseok** [comment]
Reproducible on @sveltejs/kit 2.5.0

**Comment by ckiee** [comment]
Could this please be reopened? #3177 [only fixed](https://github.com/sveltejs/kit/pull/3177/files#diff-35da857c87de7945a1a14898efa59865955ced32f6ede60e298a3386be524dd6R1486) `:target` for intra-page links with hash, but inter-page navigation with hash is still broken, as per the upstream spec issue: https://github.com/whatwg/html/issues/639 ({push,replace}State don't recompute `:target`)

Here's the workaround proposed there translated to SvelteKit... It seems to be good on Firefox but [not Chrome](https://gist.github.com/ckiee/1c565e2df2014403708f0a52d16dfc3d)
```js
afterNavigate(navigation => {
    if (!navigation.to?.url.hash) return;

    // go back and then come forward again immediately, to force :target to update.
    history.back();
    window.addEventListener(
        "popstate",
        (e) => {
            history.forward();
            e.stopImmediatePropagation()
        },
        { once: true, capture: true }
    );
})
```

Making a new issue would also be ok but the template takes too long to fill out TBH.

cc @bluwy
