### ISSUE TITLE
Passthrough User-Agent header in server side fetch inside load along with cookies for same origin requests

### ISSUE THREAD

**Issue by ramiroaisen** [sveltejs/kit#2688]
### Describe the problem

server side `fetch` inside `load` should passthrough `User-Agent` header as some apps use this header to avoid session id hijacking.

For example `express-session` use the `User-Agent` header for this, so you will get two different session ids in server side and in client side fetch.

I can think of other headers that the browser set by default and should also de passed through to mimic the behaviour of a client side fetch like `Accept-Language`. 

what else should be passed through appart from these two?
 
### Describe the proposed solution

Pass through the `User-Agent` and other headers in server side `fetch` inside `load` functions along with cookies for same-origin domains 

The user can then override the headers by setting other value for the same header in callings to fetch, like `node-fetch` does with the `User-Agent` header

### Alternatives considered

The user can mimic this by setting a `userAgent` property inside `session` and adding it manually to server side `fetch` requests headers but I think the solution described avobe should be the default.

(mis)using the `session` object like this is a really bad practice as `load` functions will have to destructure the `session` prop with the consecuences it have with the current logic of when the load functions will be called, Eg: when session change.  

### Importance

would make my life easier

**Comment by mrkishi** [comment]
The behavior of the server-side `fetch` was changed by #3631. It now forwards most headers, and cookies and authorization can also be passed along (guarded by `credentials`).
