### ISSUE TITLE
Support __error.reset.svelte

### ISSUE THREAD

**Issue by drobati** [sveltejs/kit#2694]
### Describe the problem

I want the error page at /routes to not contain the __layout.svelte code.

I would like my error page to be a fullscreen background image without the navbar that exists across the site.

### Describe the proposed solution

Allow error pages to be reset with .reset like __layout.reset.svelte

### Importance

would make my life easier

**Comment by yousufiqbal** [comment]
I second this. This is a need

**Comment by m-haritonov** [comment]
I need it too. Without it I don't see a way to create a root error page with its own layout.

**Comment by lukaszpolowczyk** [comment]
I am pasting my [proposal](https://github.com/sveltejs/kit/issues/3949) - `__error` folder z `__layout.reset.svelte`:
> 



> A `__error` directory that can have its own `__layout.reset.svelte`. This can be multi-level. For the first level: `routes/__error/index.svelte` - error page `routes/__error/__layout.reset.svelte` - layout reset page
> 
> The file `/routes/__error/index.svelte`, is equivalent to `/routes/__error.svelte` - so it works on all subpages e.g. on `routes/about` also this error works.
> 
> Of course this should also work: `routes/todos/__error/index.svelte` - error page `routes/todos/__error/__layout.reset.svelte` - layout reset page
> 
> Then the `/routes/todos/__error/index.svelte` file is equivalent to `/routes/todos/__error.svelte`.

**Comment by vhscom** [comment]
If you only want to hide the nav in `__error.svelte` for a full-screen error page, you can hide the nav:

```svelte
<style>
  :global(nav) {
    display: none;
  }
</style>
```

Then if you have a user logged in, you'll be able to customize the error accordingly.

**Comment by vhscom** [comment]
If you only want to hide the nav in `__error.svelte` for a full-screen error page, you can hide the nav:

```svelte
<style>
  :global(nav) {
    display: none;
  }
</style>
```

Then if you have a user logged in, you'll be able to customize the error message accordingly.

**Comment by Rich-Harris** [comment]
closing in favour of #4582
