### ISSUE TITLE
Generated URLs are inconsistent to the basepath with `adapter-static`

### ISSUE THREAD

**Issue by illright** [sveltejs/kit#2697]
### Describe the bug

Sapper was gracefully handling non-root basepaths by injecting a `<base>` tag into `<head>` in place of `%sapper.base%`. SvelteKit doesn't have that, but it does have `kit.paths.base`. By changing it, the auto-generated URLs of SvelteKit are rebased, but if there were any previous static URLs, for example, a favicon in `app.html`, these URLs will be broken.

Due to the fact that there are now both rebased and non-rebased URLs on a page, this can no longer be remedied by injecting a `<base>` tag with a hook, as @benmccann suggested in https://github.com/illright/attractions/issues/311#issuecomment-950333419.

### Reproduction

https://github.com/illright/sveltekit-repro-basepath

### System Info

```shell
System:
    OS: Linux 5.14 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.16 GB / 7.62 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.11.0 - /usr/bin/node
    npm: 8.0.0 - /usr/bin/npm
  Browsers:
    Firefox: 93.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/kit: next => 1.0.0-next.191 
    svelte: ^3.42.6 => 3.44.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This blocks reliable deployment of SvelteKit-generated websites to GitHub Pages.

**Comment by mgrubinger** [comment]
Can reproduce this in a similar setup (building for github-pages). I worked around it for now is to move the <link>s in app.html to my __layout.svelte file and wrap them in <svelte:head>. 
Would be great to see the paths in app.html respect kit.paths.base though 👍

**Comment by Rich-Harris** [comment]
As of the most recent version you can do e.g. `%svelte.assets%/favicon.png` in your `src/app.html`

**Comment by nstuyvesant** [comment]
Seeing `%svelte.head%`, `%svelte.body%` and `%svelte.assets%`, are these tokens for the template documented anywhere? Are there others that can be used?
