### ISSUE TITLE
A way to delay current route unmount until new one finishes the in transition.(will have 2 route mounted together, and the first I will keep at a lower index, so they will seem stacked) ) 

### ISSUE THREAD

**Issue by development-vargamarcel** [sveltejs/kit#2710]
### Describe the problem

I tried to fly in the new route all while the old one stays visible beneath it using a lower z-index. The problem is the the new route mounts only after the old one is destroyed.

### Describe the proposed solution

A way to mount a new route after clicking a link without destroying the current one and a way from the new route to destroy the old one (maybe by providing a path to a function or simply providing a detroyPreviousRoute function)

### Importance

would make my life easier

**Comment by Mlocik97** [comment]
Put transition to `__layout` on <slot> element, and execute it at path change.

**Comment by development-vargamarcel** [comment]
@Mlocik97 , 
Could you provide a simple working example please? 
 In the docs I do not see a way to control transition execution time.

Thanks for the response

**Comment by development-vargamarcel** [comment]
For anyone trying to achieve native-like page transitions,the way i did it,finaly, was to use the __layout.svelte as: itself + index.svelte (index.svelte will be left empty).

 Imagine having a blog section on your website:
 in the routes directory in your sveltekit project,you will have a directory called blog with 3 files inside (index.svelte,__layout.svelte,[id].svelte)

- index.svelte will be left empty.
- [id].svelte will contain whatever you want
**- __layout.svelte will have the contents you would usualy put in index.svelte.At the bottom add the usual <slot />.**

Keep in mind that in order for this to work as intended,the [id].svelte will have to display above what is in __layout.svelte ,maybe displaying it in a position fixed container. (otherwise it will simply be displayed just below the contents in __layout.svelte)
At this point use for example the fly x transition ,and observe how the content of layout is visible beneath the flying page,just like in a native app.


I think this is the best approach because you do not need to destroy and re-create al those DOM elements.
**Please correct me if i am making a mistake by using this aproach.**

**Comment by development-vargamarcel** [comment]
@Mlocik97 thank you for your reply! could you check my solution to this and give me some feedback?I am just starting out with frontend dev.
