### ISSUE TITLE
configuration for an even more static site

### ISSUE THREAD

**Issue by tycobbb** [sveltejs/kit#2711]
### describe the problem

afaict, `svelte-kit` with `adapter-static` prerenders every page, but it also adds a bunch of fancy js for providing an app-like experience after the initial page load.

while surely useful in many cases, it adds weight not necessary for every project. some users, like myself, prefer to limit bandwidth consumption and only fetch data when the user requests it (by clicking a link). some users, such as those w/ low-end devices, might prefer their browser do as little work as possible.

it would be nice to be able to discard it and generate sites that are just prerendered html, assets, styles, per-page javascript. to use svelte-kit to build a site but provide a wholly traditional browsing experience.

### describe the proposed solution

add a configuration option(s) to disable the generation of app-like js, remove links to it from pages, &c. maybe this should be project-wide, maybe per-page (if you want an app-like experience in some subtree). i don't know.

### importance

would make my life easier

**Comment by babichjacob** [comment]
What is different about this from the existing ability to disable [`hydrate`](https://kit.svelte.dev/docs#configuration-hydrate) and [`router`](https://kit.svelte.dev/docs#configuration-router) by default and [enable them on the pages that need them](https://kit.svelte.dev/docs#ssr-and-javascript-hydrate)?

**Comment by tycobbb** [comment]
maybe nothing! i will give that a shot thank you.
