### ISSUE TITLE
TypeScript load function example

### ISSUE THREAD

**Issue by benblazak** [sveltejs/kit#2712]
### Describe the problem

It took me a long time to figure out how to write a TypeScript `load` function for `__error.svelte`

### Describe the proposed solution

Include an example :)

``` typescript
import type { ErrorLoadInput, LoadOutput } from "@sveltejs/kit";
export async function load({
  error,
  status,
}: ErrorLoadInput): Promise<LoadOutput> {
  return {
    props: {
      title: `${status}: ${error.message}`,
      stack: error.stack,
    },
  };
}
```

### Alternatives considered

Don't include an example :(

### Importance

nice to have

**Comment by JeanJPNM** [comment]
You can import the `Load` type:

```ts
import type { Load } from "@sveltejs/kit"

export const load: Load = ({ error, status }) => ({
  props: {
    title: `${status}: ${error.message}`,
    stack: error.stack,
  }
})
```

But I agree that there should be an example for this.

**Comment by benblazak** [comment]
that's much nicer -- thanks :)

tried it just now. using `Load` compiled and ran fine, but failed svelte-check.  had to use `ErrorLoad`.

``` typescript
import type { ErrorLoad } from "@sveltejs/kit";
export const load: ErrorLoad = ({ error, status }) => ({
  props: {
    title: `${status}: ${error.message}`,
    stack: error.stack,
  },
});
```

@benmccann do you guys like pull requests for things this small?

if so, is there support for code tabs in the sveltekit docs, or should i just write it after the javascript version in https://kit.svelte.dev/docs#layouts-error-pages?

**Comment by bluwy** [comment]
> if so, is there support for code tabs in the sveltekit docs, or should i just write it after the javascript version in https://kit.svelte.dev/docs#layouts-error-pages?

Feel free to open a PR for the javascript version on that section! Seems to be lacking the jsdoc typings in the code block example. I'm not sure if we'd want a typescript version soon (not my call), but a javascript version is a good start.

**Comment by benblazak** [comment]
So just adding this on top?

``` javascript
/**
 * @type {import('@sveltejs/kit').ErrorLoad}
 */
```

I can add that if it's helpful :)

In that case, should we also add `ErrorLoadInput` to the list of types in the "Loading" section just below?

``` typescript
export interface ErrorLoadInput<
	PageParams extends Rec<string> = Rec<string>,
	Stuff extends Rec = Rec,
	Session = any
> extends LoadInput<PageParams, Stuff, Session> {
	status?: number;
	error?: Error;
}
```

Perhaps with a link to the code https://github.com/sveltejs/kit/blob/master/packages/kit/types/page.d.ts#L21

Though, from the perspective of someone new to both Svelte and Typescript, I still wouldn't have known how to translate the jsdoc typing into a typescript type import + function, and testing just now it appears to pass svelte-check even when it's wrong.

**Comment by bluwy** [comment]
This got lost in my notifications :sweat_smile: 



> So just adding this on top?

Yep!



> In that case, should we also add `ErrorLoadInput` to the list of types in the "Loading" section just below?

I think having them in the "Error pages" may be easier to follow. Don't think a link to the code is needed though, to keep it consistent with the "Loading" section.

> Though, from the perspective of someone new to both Svelte and Typescript, I still wouldn't have known how to translate the jsdoc typing into a typescript type import + function, and testing just now it appears to pass svelte-check even when it's wrong.

For now SvelteKit is going full on jsdoc so a typescript version would clutter up the docs. Maybe in the future though if we implement a sort of language toggle.

**Comment by sebastianrothe** [comment]
> 

Works fine, even with the latest change #4160

**Comment by frederikhors** [comment]
Yeah. It works but I think weh should add some docs for Typescript. Not only for javascript.

**Comment by bewards** [comment]
I am trying to use the _generated-types_ from documentation, but I'm still getting _any_ type for everything, including the parameters:

My route svelte file:
![image](https://user-images.githubusercontent.com/3927169/158229472-6338cce3-2b41-4a92-8767-cfaaa1c8dba1.png)

The generated route type file:
![image](https://user-images.githubusercontent.com/3927169/158229644-c3b9c831-f4a3-44d1-ac7c-6e76698c82f1.png)

I am using the default latest sveltekit + typescript application.

**tsconfig.json**
```
{
	"extends": "./.svelte-kit/tsconfig.json"
}
```

**svelte.config.js**
```
import adapter from '@sveltejs/adapter-auto';
import preprocess from 'svelte-preprocess';
import path from 'path';

/** @type {import('@sveltejs/kit').Config} */
const config = {

	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess({
		postcss: true,
	}),

	kit: {
		adapter: adapter(),
		vite: {
			resolve: {
				alias: {
					$components: path.resolve('./src/lib/components'),
					$stores: path.resolve('./src/lib/stores'),
					// $lib: path.resolve('./src/lib'),
				},
			},
		},
	},

	babel: {
		presets: [
			[
				'@babel/preset-env',
				{
					loose: true,
					modules: false, // No need for babel to resolve modules
					targets: {
						esmodules: true, // ! Very important. Target es6+
					},
				},
			],
		],
	},
};

export default config;
```

**Comment by Rich-Harris** [comment]
closing in favour of #4452

**Comment by fokoenecke** [comment]
I am completely new to svelte and it just took me a while to get `load` running in typescript.
So here is a snippet that worked for me. Maybe it will help someone.

``` svelte
<script lang="ts" context="module">
	import type { LoadInput } from '@sveltejs/kit';
	export async function load({ fetch }: LoadInput) {
		const url = `https://example.com/data.json`;
		const response = await fetch(url);

		return {
			status: response.status,
			props: {
				// this needs to be an exported field in your component
				// https://svelte.dev/tutorial/declaring-props
				data: response.ok && (await response.json())
			}
		};
	}
</script>
```

**Comment by GaryB432** [comment]
hi @fokoenecke (or anyone 😀)is this still the way?  I have `Module '"@sveltejs/kit"' has no exported member 'LoadInput'.`

**Comment by plckr** [comment]
@GaryB432 
```

**Comment by plckr** [comment]
@GaryB432 this works for me

```
<script context="module" lang="ts">
  import type { Load } from '@sveltejs/kit'

  export const load: Load = async (ctx) => {
    return { ... }
  }
</script>
```

**Comment by fokoenecke** [comment]
@GaryB432 
[Changelog](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next340) says it has been renamed from `LoadInput` to `LoadEvent`. Worked for me.

**Comment by GaryB432** [comment]
The [docs](https://kit.svelte.dev/docs/loading) say how to enable type-safety for `params` with the jsdoc comment.  Is there a better way?

**Comment by fokoenecke** [comment]
> The [docs](https://kit.svelte.dev/docs/loading) say how to enable type-safety for `params` with the jsdoc comment. Is there a better way?

If you are using typescript, the individual input params for load should be typed automatically:

```typescript
<script lang="ts" context="module">
  import type { LoadEvent } from '@sveltejs/kit';
  export async function load({ fetch, params }: LoadEvent) {
  ...
```

fetch for example is this `fetch(info: RequestInfo, init?: RequestInit): Promise<Response>;` then.

**Comment by jankalfus** [comment]
> > The [docs](https://kit.svelte.dev/docs/loading) say how to enable type-safety for `params` with the jsdoc comment. Is there a better way?
> 
> If you are using typescript, the individual input params for load should be typed automatically:
> 
> ```ts
> <script lang="ts" context="module">
>   import type { LoadEvent } from '@sveltejs/kit';
>   export async function load({ fetch, params }: LoadEvent) {
>   ...
> ```
> 
> fetch for example is this `fetch(info: RequestInfo, init?: RequestInit): Promise<Response>;` then.

If you type it like this, then all the type information about params is `lost`, because a generic `Record<string, string>` type is used. You can use the generated type and get proper typing instead:

```
<script lang="ts" context="module">
	import type { Load } from './__types/[slug]';

	export const load: Load = async ({ params, fetch, session, stuff }) => {
		const url = `https://cms.example.com/article/${params.slug}.json`; // slug will be properly typed

		return {
			status: response.status,
			props: {
				article: response.ok && (await response.json()),
			},
		};
	};
</script>
```

If you attempt to you use a param that doesn’t exist, you’ll get an error:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/12714276/180638588-0c168e20-ea37-45a2-9d0a-774cb57df123.png">

**Comment by GaryB432** [comment]
Thanks @jankalfus is there a similar way for the `RequestHandler` in an endpoint?  my `get` function (@sveltejs/kit@1.0.0-next.376) still has the `Record<string, string>` typing for `params` after importing `RequestHandler` from `@sveltejs/kit`. I'm likely doing something wrong while I'm learning this amazing platform.

**Comment by csjh** [comment]
> Thanks @jankalfus is there a similar way for the `RequestHandler` in an endpoint? my `get` function (@sveltejs/kit@1.0.0-next.376) still has the `Record<string, string>` typing for `params` after importing `RequestHandler` from `@sveltejs/kit`. I'm likely doing something wrong while I'm learning this amazing platform.

same as importing the load type
`import type { RequestHandler } from './__types/[slug]'`
