### ISSUE TITLE
Add or document a method for retrieving location information within a non-page/non-layout component

### ISSUE THREAD

**Issue by rsheasby** [sveltejs/kit#2717]
### Describe the problem

As it is now, I don't see any way that a component can retrieve the path when it's SSR'ed and not a page or layout. A page or layout component can do it using the load() function, and a non-SSR component can do it using the window object, but there doesn't seem to be a method that works for an imported SSR component.

In this case, I'm attempting to create a component for a navigation button that is highlighted when you're currently on that page. I can do this if I disable SSR, but I see no reason this couldn't be SSR'ed.

### Describe the proposed solution

Add a global path variable, or enable the load() function to be called on all components, not just page/layout components.

If I'm missing an existing method for doing this, please add documentation explaining that method.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
It is possible, and it is documented. https://kit.svelte.dev/docs#modules-$app-stores

We can't use a global for this because that would be shared between different requests to the server.

**Comment by rsheasby** [comment]
Oh awesome, thanks. I spent ages but wasn't able to find that solution.
