### ISSUE TITLE
Add .env to .gitignore file generated by starter

### ISSUE THREAD

**Issue by brittneypostma** [sveltejs/kit#2718]
### Describe the problem

Currently when running `npm init svelte@next` and starting either a demo or skeleton app, then doing a `git init`, the generated `.gitignore` file does not include `.env`. This is a pretty common file extension and typically should not be added to a repository. I wanted to conversation around it and get a consensus if this is something that should be added to the starters.

### Describe the proposed solution

Add `.env`  or variation of that to the `.gitignore` file generated by the starter app.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
It does seem reasonable to assume that people are generally not going to want to commit `.env` files to their Git repo for a SvelteKit project, but I'm not sure where the line is here. There's no dotenv stuff that comes included in the starter projects - which other third party things (that are not currently used in the project) would it make sense to add `.gitignore` entries for? There are a ton of other things that people might add to their apps (videos recorded by Cypress, reports from Codecov), but that I don't think it's SvelteKit's place to add here.

**Comment by brittneypostma** [comment]
I agree with that as well that there are lots of things that could be in there, but`.env` specifically is a pretty popularly used file. It's easy to forget to check the `.gitignore` if it's included and accidentally commit private keys and cause huge issues.

**Comment by benmccann** [comment]
We have some built-in support for `.env` via Vite, so it seems reasonable to me: https://kit.svelte.dev/faq#env-vars

**Comment by Conduitry** [comment]
:+1: That seems like a good enough reason for me.
