### ISSUE TITLE
Links to server-routes broken

### ISSUE THREAD

**Issue by neoel** [sveltejs/kit#2719]
### Describe the bug

Before I was able to have a link to a server-route, which could redirect the user f.i. Now it assumes it's a clientside page and renders a 404. Refreshing the page makes the route hit the server.

### Reproduction

https://github.com/neoel/sveltekit-bugs/tree/nav-server-route

### System Info

```shell
System:
    OS: Linux 5.11 KDE neon 5.23
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 32.32 GB / 46.73 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Brave Browser: 95.1.31.87
    Chrome: 95.0.4638.54
    Firefox: 93.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.192 
    svelte: ^3.42.6 => 3.44.1
```

### Severity

blocking an upgrade

### Additional Information

Will dive into checking which version of svelte-kit introduced it. -> It was introduced in @next.190 (was functional in 189)

**Comment by Conduitry** [comment]
This was an intentional change in #2656 so that less code could be sent to the browser. You can still manually mark links as external so that they receive regular browser navigation.
