### ISSUE TITLE
App deployed with adapter-netlify doesn't have access to request headers/cookies

### ISSUE THREAD

**Issue by cibernox** [sveltejs/kit#2721]
### Describe the bug

I'm not 100% sure the netlify adapter is to blame here, but I'm not sure how to figure it out who is really.

I've created an sveltekit app that defines a `getSession` hook. In there I read the `request.headers.cookie` (regular cookie set using `document.cookie`, not HTTP-only cookies in case it matters) to read the user's preferred language if they've set one and fallback to `request.headers["accept-language"]` if it was never set.

The reason is that I want SSR to already render on the right language and avoid the text to show on the wrong language for a split second.

It works like a charm locally but when I deploy to netlify it doesn't. I've tried a few things and after sending some debug information back to the client I reached the conclusion that the `request` object received by the hooks doesn't have ANY headers. None.

I'm not sure if netlify itself could be blocking the headers, but it seems unlikely. Cookies are a keystore of the web, I don't see how they could be in business without allowing them.
I also deployed the app using the vercel adapter with identical result.

### Reproduction

The repo is open source: svelte-intl-precompile-docs
The app has been deployed in https://svelte-intl-precompile.com

I also tried the vercel adapter with the sa

### System Info

```shell
Not applicable I think, but:

  System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 146.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.volta/tools/image/node/14.18.1/bin/node
    Yarn: 1.22.15 - ~/.volta/tools/image/yarn/1.22.15/bin/yarn
    npm: 6.14.15 - ~/.volta/tools/image/node/14.18.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 92.0
  npmPackages:
    @sveltejs/adapter-netlify: next => 1.0.0-next.35
    @sveltejs/kit: next => 1.0.0-next.191
    svelte: ^3.34.0 => 3.44.0
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
The Netlify headers are set here:

https://github.com/sveltejs/kit/blob/a07ed46ff575f59b548c5aae688a22cc9264c513/packages/adapter-netlify/files/entry.js#L31

You could insert some debug statements and check the function logs: https://docs.netlify.com/functions/logs/

Perhaps you could build the site locally and then try the Netlify CLI to run it locally

Alternatively, you could update the version of `@sveltejs/adapter-netlify` to point at a git repo with your fork of that package with the `console.log` statements

**Comment by adamjkb** [comment]
I have not been able to reproduce this bug, all works as expected. Both `handle` and `getSession` receives the same headers object from the Netlify Function event. I created a repo to test this out:
https://github.com/adamjkb/adapter-netlify-cookie-2721/

Page example:
https://adapter-netlify-cookie-2721.netlify.app/ (`kit_username` cookie set here if not already set)
Endpoint example:
https://adapter-netlify-cookie-2721.netlify.app/locals.json

See how cookie data is passed onto the application:
https://github.com/adamjkb/adapter-netlify-cookie-2721/blob/main/src/hooks/index.js#L12-L28

System info:
```
  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
    Memory: 6.23 GB / 24.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nvm/versions/node/v16.8.0/bin/node
    npm: 7.21.0 - ~/.nvm/versions/node/v16.8.0/bin/npm
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 95.0.4638.54
    Edge: 95.0.1020.44
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.194
    svelte: ^3.42.6 => 3.44.1
```

**Comment by nhe23** [comment]
With the current sveltekit and adapter-netlify version (v1.0.0-next.212 & 1.0.0-next.37) everything works as expected as @adamjkb pointed out. 
I also created a minimal repo to test this: [https://github.com/nhe23/sveltekit-headers-cookies](https://github.com/nhe23/sveltekit-headers-cookies)
In my example I just display the cookie (initially undefined; after refresh there should be a cookie) that was sent and all request headers available in the handle hook. The cookie and the header are exposed to the app via the getSession hook.

The deployed version on netlify can be found here: [https://gracious-rosalind-02eca5.netlify.app](https://gracious-rosalind-02eca5.netlify.app)

So either there is no more issue or something completely different is causing the strange behavior which I can not reproduce.

**Comment by bluwy** [comment]
Thanks for the confirmation @nhe23 @adamjkb. I'll close this with the comments above. @cibernox If you still hit this error, feel free to re-open the issue and have a minimal repro to check out.
