### ISSUE TITLE
Generated SvelteKit app doesn't start on a subst drive

### ISSUE THREAD

**Issue by jemhuntr** [sveltejs/kit#2734]
### Describe the bug

This may be a bit tangential to SvelteKit (and frankly more of a Windows issue that SvelteKit), but I figured it might be worth reporting anyway, since I believe it relates to how paths are handled by SvelteKit.

Basically, `npm run dev` fails when run from a [subst drive](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst), complaining about modules it can't resolve:

```
> greenova.b2bmall.backoffice.web.client.sveltekit@0.0.1 dev
> svelte-kit dev "--open"

Pre-bundling dependencies:
  svelte/store
  svelte
  svelte/animate
  svelte/easing
  svelte/internal
  (...and 2 more)
(this will be run only when your dependencies or config have changed)
 > dep:svelte:2:14: error: Could not resolve "./C:/project/path/on/source/drive/.../node_modules/svelte/index.mjs"
    2 │ export * from "./C:/project/path/on/source/drive/..."

 > ...
```

The path seems correct, it just looks like it's trying to resolve the module relatively even if it's already got the correct absolute path to the .mjs file.

### Reproduction

1. [create a subst drive](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst) of an existing path: `subst X: C:\...\path\to\project\root`
2. navigate to just-created subst drive: `cd X:`
3. scaffold a new sveltekit app from this drive: `npm init svelte@next my-app`
4. `cd my-app`
5. `npm install`
6. `npm run dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 15.99 GB / 31.94 GB
  Binaries:
    Node: 14.17.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.40)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.193
    svelte: ^3.42.6 => 3.44.1
```

### Severity

annoyance

**Comment by bluwy** [comment]
Currently the core issue is within Vite and is tracked at https://github.com/vitejs/vite/issues/4635, so there's not much we can do. Closing in favour of the linked issue instead.

**Comment by jemhuntr** [comment]
Thanks! Will track the linked issue.
