### ISSUE TITLE
'404 Not found: /index' when visiting localhost:3000/index ( or localhost:3000/$NESTED_ROUTE/index )

### ISSUE THREAD

**Issue by 1776smithadam** [sveltejs/kit#2750]
### Describe the bug

SvelteKit treats `routes/index.svelte` differently than `routes/*`. The router specifically only loads the page with the '/index' value omitted from the URL which is inconsistent with other paths. This has a pernicious implication for relative paths linked from index.svelte when they are in a nested route / directory. 

### Reproduction

1) Add routes/index.svelte 
2) `npm run dev`
3) As expected, `localhost:3000/` shows the index.svelte component
4) Expect `localhost:3000/index` to show same results as `localhost:3000/`. Actual: 404.

Similarly for nested routes:

1) Add routes/foobar/index.svelte 
2) `npm run dev`
3) As expected,`localhost:3000/foobar` shows the index.svelte component
4) Expect `localhost:3000/foobar/index` to show same results as `localhost:3000/foobar`. Actual: 404.

### Logs

```shell
404
Not found: /index
Error: Not found: /index
    at resolve (file:///Users/louis/workspace/kanjo/frontend/node_modules/@sveltejs/kit/dist/ssr.js:1776:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async respond (file:///Users/louis/workspace/kanjo/frontend/node_modules/@sveltejs/kit/dist/ssr.js:1723:10)
    at async svelteKitMiddleware (file:///Users/louis/workspace/kanjo/frontend/node_modules/@sveltejs/kit/dist/chunks/index.js:4542:22)
```

### System Info

```shell
└─ ▶ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

npx: installed 1 in 0.844s

  System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 57.56 MB / 16.00 GB
    Shell: 5.1.8 - /opt/homebrew/bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Edge: 95.0.1020.44
    Firefox: 94.0
    Safari: 14.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.190
    svelte: ^3.44.1 => 3.44.1
```

### Severity

annoyance

### Additional Information

This is annoying for relative links in nested routes.

Suppose this is the directory structure:
```
/routes/foobar/index.svelte
/routes/foobar/about.svelte
```

index.svelte:
`
  <a href="about">Click me</a>
`

I can visit: 
```
localhost:3000/foobar
localhost:3000/foobar/about
```

Since index.svelte's path is localhost:3000/foobar, the relative link will instead go to localhost:3000/about which does not exist. If instead we can access Index.svelte via  localhost:3000/foobar/index than the relative link will go to  localhost:3000/foobar/about

**Comment by Conduitry** [comment]
This is all working as intended and as documented as far as I can tell.

**Comment by benmccann** [comment]
Yes, I don't think there's any bug here. You certainly wouldn't want the same page to be loadable by two different URLs in the general case because you'd be punished by the search engines for duplicate content.

If you want a page named `index`, you can create `[placeholder].svelte` and then check if the route is `index` in `load` and fall-through otherwise
