### ISSUE TITLE
Ensure js as server only

### ISSUE THREAD

**Issue by jesperordrup** [sveltejs/kit#2758]
### Describe the problem

My worst fear is that some code that was only ment to be serverside suddenly is referenced by a client side script and thereby is included in the clientside code.

At some point I typically Import some stuff only to find that this wasnt such a great idea. 

yes - api endpoints are made for this
no - they dont prevent you from making that sweet /utils/mysecrets/businessrules.js only ment for serverside, but accidently added to clientside ...

### Describe the proposed solution

I suggest that any js file can be defined as being server side only and that sveltekit should prevent it from being compiled to client side code.

A few ideas

The folder: Any file in /server can only be accessed from serverside code
The filename: Any file with *.server.js (or *.server.ts) can only be accessed from serverside code

Or reusing from "private modules": Any file or folder prefixed with a "_" such as can only be accessed from serverside code

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
How would one know what a server side only component is where you are only allowed to import these files?
Also: This sounds like it could also be solved with a custom ESLint rule.

**Comment by benmccann** [comment]
I agree an eslint rule or something along those lines is a better fit for this. You could also do this today by creating two projects - a backend project and frontend project.

I'm going to go ahead and close this because I've never seen anyone actually hit this issue and it seems relatively low priority compared to all the other issues we have.

We have special handling of environment variables between client and server already, which handles the most crucial aspect of this.

**Comment by jesperordrup** [comment]
Have to respectfully disagree. It's one of those things that will help ppl not to share code that wasnt intented for any reason. 

> I agree an eslint rule or something along those lines is a better fit for this. 

Some (many) wouldnt know how to eslint this (me included)

> You could also do this today by creating two projects - a backend project and frontend project.

That might be true but not really a solution. It seems complicated and require two instances. 

> We have special handling of environment variables between client and server already, which handles the most crucial aspect of this.

True. But not code.
