### ISSUE TITLE
Client-side router should check `event.composedPath()` to intercept link clicks

### ISSUE THREAD

**Issue by andreavaccari** [sveltejs/kit#2768]
### Describe the problem

We use SvelteKit in combination with Ionic Framework, which makes heavy use of web components and Shadow DOMs. Some of these components take an `href` attribute and render an anchor element inside a shadow dom. This is a simplified view of the resulting document structure:

```
...
└─ <ion-button>
   ├─ #shadow-root
   │  └─ <a href="...">
   │     └─ <slot>
   └─ <div>              <-- This goes in the anchor slot
```

Currently, [packages/kit/src/runtime/client/router.js](https://github.com/sveltejs/kit/blob/e79cf049ab36d42d6db0d0bb0092ea4e36dc937f/packages/kit/src/runtime/client/router.js#L14-L17) uses the following function to find anchor tags in the page:

```
function find_anchor(node) {
  while (node && node.nodeName.toUpperCase() !== 'A') node = node.parentNode; // SVG <a> elements have a lowercase name
  return /** @type {HTMLAnchorElement | SVGAElement} */ (node);
}
```

This implementation will not find the anchor tag, because a click event will have the `div` element has the event's `target`, but the `ion-button` as its parent node.

### Describe the proposed solution

The `find_anchor` function takes the `target` of an event and is used inside various listeners to either 1) intercept a click and perform router-based navigation, or 2) detect a mouse hover or touch and possibly trigger a prefetch. In both cases, the following function that takes the `composedPath()` of an event can be used.

```
function find_anchor(path) {
  return path.find((e) => e.nodeName.toUpperCase() === 'A');
}
```

### Alternatives considered

To the best of my knowledge there are no alternative solution because it is not possible to traverse the flattened document tree. 

### Importance

i cannot use SvelteKit without it

### Additional Information

If the proposed solution is acceptable, I'll be happy to submit a PR. Thank you!

**Comment by bluwy** [comment]
That sounds like a good solution to me. I'd say feel free to submit a PR.
