### ISSUE TITLE
POST endpoints should work with a request with missing `content-type` headers

### ISSUE THREAD

**Issue by lukasIO** [sveltejs/kit#2779]
### Describe the bug

When receiving third party webhooks I came across some implementation that didn't set any content-type headers when POSTing the webhook payload.
In SvelteKit the `getRawBody` function sets the body to `null` if the content-type header is missing: https://github.com/sveltejs/kit/blob/93726c38d2118b1dc136f3ef659c5ae6bb039138/packages/kit/src/core/node/index.js#L6-L8

I got curious to know what's the right approach here and it seems, while POST requests **should** set it, it is not required by the  http spec:

   > Any HTTP/1.1 message containing an entity-body SHOULD include a
   Content-Type header field defining the media type of that body. If
   and only if the media type is not given by a Content-Type field, the
   recipient MAY attempt to guess the media type via inspection of its
   content and/or the name extension(s) of the URI used to identify the
   resource. If the media type remains unknown, the recipient SHOULD
   treat it as type "application/octet-stream".

- https://www.ietf.org/rfc/rfc2616.txt

The only useful scenario I can see (and that's what I'm trying to do) is to get the `rawBody` of the request, even if the content-type headers are missing

### Reproduction

1. Create an endpoint in any SK app:
```ts
export async function post(request: ServerRequest) {
	console.log('receiving webhook request');
	console.log(request.rawBody);
}
```

2. Post a request to that endpoint with a valid body but without `content-type` headers

-> rawBody is always null

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 20.39 GB / 24.83 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.31 
    @sveltejs/kit: next => 1.0.0-next.195 
    svelte: ^3.44.0 => 3.44.0
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
In newer versions, the request body is retrieved in the endpoint (`await request.json()` etc) rather than parsed eagerly, so we can close this
