### ISSUE TITLE
CSS Imports not deloading after navigation away

### ISSUE THREAD

**Issue by matteopaz** [sveltejs/kit#2783]
### Describe the bug

When importing a stylesheet from a .css file into a route, then navigating away, the styles imported do not unload. Initially, styles are correct and reloading fixes.

### Reproduction

[Reproduction](https://github.com/matteopaz/css-issue-sk-reproduction)

`npm install` and `npm run dev` for obvious reasons.
There are two root stylesheets, one for global styles and one that we are importing in our non-index route.
Notice how the global.css is being loaded with the red color style for h1s. This is being imported in __layout, so it should and does function always. This is a sanity check for global loading. Starting or reloading on the root page gives a red h1, and a black unstyled h2. When navigating to the subfolder, you recieve a red h1 and blue h2 as expected. When navigating back to index, the h2 has remained blue, loading the external stylesheet that is not being loaded on the current route.

### Logs

```shell
[vite] connecting...
[vite] connected.
<Routes> received an unexpected slot "default".
GET http://localhost:3000/favicon.ico 404
<Sub> received an unexpected slot "default".
<Routes> received an unexpected slot "default".

(No logs of any kind out of the ordinary)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
    Memory: 7.57 GB / 15.95 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: github:matteopaz/adapter-cloudflare-workers => 1.0.0-next.23
    @sveltejs/kit: next => 1.0.0-next.180
    svelte: ^3.42.6 => 3.43.1
```

### Severity

serious, but I can work around it

### Additional Information

In my specific use case, this is impeding me from styling markdown. Due to the fact that the markdown is being loaded and is not immediately present in the markdown of the svelte file, if I attempt to inline the css file, the rules are removed because the compiler thinks that the selectors are unused.

**Comment by antony** [comment]
Styles are cumulative, and don't get removed.
If you redefine an existing style, it overrides it and will become the default style for that selector.

If you want to style markdown, I suggest placing a class on the container where it is rendered, and using `:global(.container-class h1) { ... }` to style it.

**Comment by steve-taylor** [comment]
> Styles are cumulative, and don't get removed. If you redefine an existing style, it overrides it and will become the default style for that selector.

@antony Why is that the it works, though? How can the SvelteKit devs be OK with such a resource leak and all the CSS side-effects that go with it (i.e. the style of a page depends on the navigation that led to it)?

> If you want to style markdown, I suggest placing a class on the container where it is rendered, and using `:global(.container-class h1) { ... }` to style it.

Other SvelteKit devs have specifically said not to use `:global` in this way because of the "intended behavior" (i.e. styles accumulating and user experience going to hell the more the user navigates).

As much as I hate Tailwind, it's looking like the lesser of two evils right now.
