### ISSUE TITLE
[Question] npm run dev error from demo app

### ISSUE THREAD

**Issue by scheung38** [sveltejs/kit#2795]
### Describe the bug

[> npm init svelte@next svelte-kit-app 

Selected demo app

npm install                                             
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

➜  svelte-kit-app git:(master) npm run dev 

> svelte-kit-app@0.0.1 dev $HOME/Documents/svelte-kit-app
> svelte-kit dev

file://$HOME/Documents/svelte-kit-app/node_modules/@sveltejs/kit/dist/cli.js:856
			https = https || !!vite_config.server?.https;
			                                      ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-kit-app@0.0.1 dev: `svelte-kit dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-kit-app@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     $HOME/.npm/_logs/2021-11-13T13_24_55_028Z-debug.log
➜  svelte-kit-app git:(master) 

which npm
/usr/local/opt/node@12/bin/npm

which node
/usr/local/opt/node@12/bin/node

Mac OS: Monterey](https://discord.com/invite/yy75DKs)

### Reproduction

➜  svelte-kit-app git:(master) npm run dev 

### System Info

```shell
Mac OS Monterey
```

### Severity

annoyance

**Comment by babichjacob** [comment]
Upgrade to a recent version of Node, such as `16.13.0`
