### ISSUE TITLE
Error handling is broken

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#280]
I get this when I try to load the `hn.svelte.dev` example:

![Screenshot from 2020-12-15 21-49-56](https://user-images.githubusercontent.com/322311/102310338-a9308f00-3f1f-11eb-81f3-efbc39a4703a.png)

And then if I use the web inspector to delete the broken error overlay I see this:

![Screenshot from 2020-12-15 21-52-10](https://user-images.githubusercontent.com/322311/102310485-e8f77680-3f1f-11eb-8730-85678d182635.png)

**Comment by GrygrFlzr** [comment]
Is this still an issue on the latest main branch? the `hn.svelte.dev` example seems to work for me, aside from pages with 0 comments showing `undefined` in place of the comments.
