### ISSUE TITLE
Modifying src/routes/*.svelte at dev mode cause non reactive variables to change

### ISSUE THREAD

**Issue by istarkov** [sveltejs/kit#2816]
### Describe the bug

Create following page in routes

```svelte
<!-- src/routes/[slug].svelte -->
<script>
  import { page } from '$app/stores';
  let p_slug = $page.params.slug;
</script>

<h1>{p_slug}</h1>
<a href={`${p_slug}_x`}>Click me - {p_slug}</a>
```

In production build or in dev build without code edits
p_slug is constant since I visit any page like http://localhost:3000/test

Even if I click on link "Click me - test", p_slug will not change. 

This is good expected behaviour.

## Now the issue.

In dev mode visit http://localhost:3000/test then click on "Click me - test" link.  _(url will be changed to /test_x)_

Edit `src/routes/[slug].svelte` like add something to h1.

Visit page again at http://localhost:3000/test

Click on link and see that "Click me - test" become "Click me - test_x" so  p_slug is equal to `test_x` what is different behaviour from prod or non edited dev build.

_(Its because click now cause full render from scratch and not updating)_

### Reproduction

https://github.com/realadvisor/sveltekit-dev-reactivity-issue

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC Processor
    Memory: 4.33 GB / 15.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.10.0 - ~/.volta/tools/image/node/16.10.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 7.24.0 - ~/.volta/tools/image/node/16.10.0/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196 
    svelte: ^3.42.6 => 3.44.1
```

### Severity

annoyance

### Additional Information

This is not about $page params, and affects any non reactive vars _(because link click cause page render from scratch after modifying)_. What sometimes cause hard to find bugs during development or unexpected behaviour. Had it multiple times now just reduced to minimal reproducible example

**Comment by si3nloong** [comment]
@istarkov I don't think this is an issue, you can solve it using 


<script>
  import { page } from '$app/stores';
  $: p_slug = $page.params.slug;
</script>

<h1>{p_slug}</h1>
<a href={`${p_slug}_x`}>Click me - {p_slug}</a>

**Comment by istarkov** [comment]
The issue that some code works differently at dev and prod mode. This is the issue. There is no need to show how to fix minimal reproducible example of the bug ;-)

**Comment by si3nloong** [comment]
@istarkov I can't reproduce the problem you mentioned. (dev and production are work the same)

**Comment by istarkov** [comment]
Just do steps described carefully

1. In dev mode visit http://localhost:3000/test then click on "Click me - test" link. (url will be changed to /test_x)

2. Edit src/routes/[slug].svelte like add something to h1.

3. Visit page again at http://localhost:3000/test

4. Click on link and see that "Click me - test" become "Click me - test_x" so p_slug is equal to test_x what is different behaviour from prod or non edited dev build.

**Comment by istarkov** [comment]
Fixed
