### ISSUE TITLE
svelte parser errors when hitting a template string with a close script tag in it. close style tags are even weirder

### ISSUE THREAD

**Issue by blairn** [sveltejs/kit#2825]
### Describe the bug

```
let c = `</script>`
```
is legit javascript, but svelte's parser shits itself when it sees it. note, you can close any other tag in a string temple, except for script.

```
let c = `<p>
hi, I'm a P tag
</p>`
```
works... 

what is even weirder yet, close style tags gives a even stranger result, *but only in sveltekit*  (which may help you track it down.)
```
<script>
  let c = `<style>
    hi I am a p tag
    </style>`
</script>
{c}
```

gives

```
<style> hi I am a p tag *{}</style>
```

where it puts in a *{} before the end of the style tag, always.

it isn't a vite problem, since old svelte has the issue with </script> in template strings.

### Reproduction

https://svelte.dev/repl/3789e31e9baa4a37b1da7d7939a94ccb?version=3.44.1

### System Info

```shell
System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 9.33 GB / 31.17 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 90.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196
    svelte: ^3.42.6 => 3.44.1
```

### Severity

annoyance

### Additional Information

You can always split the string up. slightly annoying but, not really an issue.

**Comment by gtm-nayan** [comment]
The issue with the script tag is related to parsing it belongs in the Svelte repo, not SvelteKit. If you'd searched there you'd have found multiple issues about it posted about it. It's a wontfix, see https://github.com/sveltejs/svelte/issues/5024#issuecomment-644667794

Can't say the same about the style tag, so please remove mentions of the script tag problem, and make the issue more descriptive about the style tag problem if you want it to get more exposure.

**Comment by blairn** [comment]
ok, I'll close this, and open a new one for the style one directly.

**Comment by bluwy** [comment]
@gtm-nayan is right. This is a known limitation and has been raised in the issue linked. Regarding the style issue, it's because `vite-plugin-svelte` adds a CSS preprocessor which prepends `* {}` for HMR, but due to the core issue it's incorrectly replaced as well. Closing this as this is similar to the issue linked.
