### ISSUE TITLE
closing style tags in string templates get a *{} added to them.

### ISSUE THREAD

**Issue by blairn** [sveltejs/kit#2826]
### Describe the bug

```
<script>
  let c = `<style>hi</style>`
</script>
{c}
```
gives you 
```
<style>hi*{}</style>
```
### Reproduction

can't use the repl because it is only sveltekit which has the issue, not svelte. but... like, the code above is tiny.

### System Info

```shell
System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 9.33 GB / 31.17 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 90.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196
    svelte: ^3.42.6 => 3.44.1
```

### Severity

annoyance

### Additional Information

you can split the string as a way to get around it, so, it isn't the end of the world, just annoying.
I suspect it is that svelte adds the *{} rule to styles so that there is always a rule for the parser to parse.

**Comment by blairn** [comment]
ok, apparently a vite issue (someone comments on a combined bug issue thing on another report.... closing)

**Comment by bluwy** [comment]
For future readers: https://github.com/sveltejs/kit/issues/2825#issuecomment-972483365
