### ISSUE TITLE
Cloudflare Pages adapter

### ISSUE THREAD

**Issue by Zizico2** [sveltejs/kit#2828]
### Describe the problem

Cloudflare Workers are now supported inside Cloudflare Pages as [Functions](https://developers.cloudflare.com/pages/platform/functions).

### Describe the proposed solution

Is it worth making an adapter for? Would there be any advantage over the Cloudflare Workers adapter?

### Importance

nice to have

**Comment by pngwn** [comment]
This already exists and was merged yesterday.

**Comment by pngwn** [comment]
More information can be found here: https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare
