### ISSUE TITLE
Installation script not working

### ISSUE THREAD

**Issue by Zahara-Nour** [sveltejs/kit#2839]
### Describe the bug

The installation script exits at the early begining, whithout being able to make a choice.
<img width="761" alt="Capture d’écran 2021-11-19 à 07 20 47" src="https://user-images.githubusercontent.com/32236491/142564610-d00853f8-acde-4baf-bbf6-5d7e69f282e7.png">

### Reproduction

Just use `npm init svelte@next my-app`

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 75.25 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    npm: 8.1.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 94.0.1
    Safari: 15.0
```

### Severity

blocking all usage of SvelteKit

**Comment by rmunn** [comment]
Can't reproduce on my system:

```
  System:
    OS: Linux 5.4 Linux Mint 19.1 (Tessa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 32.62 GB / 62.58 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 7.23.0 - ~/.local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 93.0
```

Only difference I see there is you have NPM 8 while I'm using NPM 7. I also tried with [pnpm](https://pnpm.io/) 6 and it worked fine. Does the problem still happen if you run `pnpm init svelte@next`, or if you try with NPM 7?

**Comment by Zahara-Nour** [comment]
Very Strange. It works now after just restarting my terminal.
