### ISSUE TITLE
Why check anchors for download & svg not in docs ?

### ISSUE THREAD

**Issue by Valexr** [sveltejs/kit#2846]
### Describe the problem

https://github.com/sveltejs/kit/blob/e79cf049ab36d42d6db0d0bb0092ea4e36dc937f/packages/kit/src/runtime/client/router.js#L144

### Describe the proposed solution

add explanation of this behavior in docs anchors attributes

### Importance

would make my life easier

**Comment by bluwy** [comment]
I don't quite understand what's there to document. `download` is checked and skipped because routing `download`s doesn't make sense as a browser behaviour. And we're also not doing different behaviours for SVG, we're handling it that way because anchors in SVG has a different API.

**Comment by Valexr** [comment]
Not explicit behaviour for users. I’m understood - it’s default & native but in sveltekit scope… I think it’s maybe usefull

**Comment by rmunn** [comment]
Also, the `rel=external` behavior is documented [here](https://kit.svelte.dev/docs#anchor-options-rel-external).

**Comment by bluwy** [comment]
> Not explicit behaviour for users. I’m understood - it’s default & native but in sveltekit scope… I think it’s maybe usefull

Having `download` anchors to download stuff sounds like an expected behaviour, I don't think this needs to be documented. As rmunn pointed out, we have special handling for `rel=external` and that's already documented. Unless you have something else in mind to document?
