### ISSUE TITLE
goto keepfocus not working in `v1.0.0-next.196`

### ISSUE THREAD

**Issue by m4rch3n1ng** [sveltejs/kit#2853]
### Describe the bug

the focus is not kept on the input when binding input value to a URLSearchParams object and using `goto` with `{ keepfocus: true }` to navigate

bug started when switching from version `1.0.0-next.195` to `1.0.0-next.196`

### Reproduction

**1.** initialise new svelte-kit skeleton project via `$ npm init svelte@next`

**2.** update `package.json` so it reads `"@sveltejs/kit": "1.0.0-next.195"`

**3.** install dependencies using `$ npm install`

**4.** go to `src/routes/index.svelte` and replace code with

```sv
<script>
  import { goto } from "$app/navigation";
  import { page } from "$app/stores";

  function toObject(params) {
    const obj = {};
    for (const key of params.keys()) {
      obj[key] = params.get(key);
    }
    return obj;
  }

  function queryStore(prop) {
    let query = {};
    return {
      subscribe(callback) {
        return page.subscribe((page) => {
          query = toObject(page.query);
          callback(query[prop]);
        })
      },
      set(value) {
        if (value) {
          query[prop] = value;
        } else {
          delete query[prop];
        }

        const searchParams = new URLSearchParams(query);
        const to = [ ...searchParams.keys() ].length ? `?${searchParams.toString()}` : "./";
        goto(to, { keepfocus: true, replaceState: true, noscroll: true });
      }
    }
  }

  const query = queryStore("name");
</script>


<input bind:value={$query} type="text" />
```

**5.** start development server using `$ npm run dev`

**6.** navigate to `http://localhost:3000` and input a value into the `<input />` field and observe how the url changes, while the focus is kept on the input

**7.** stop the development server

**8.** update the "@sveltejs/kit" version to `1.0.0-next.196` and run `$ npm install` again

**9.** repeat steps **(5.)** and **(6.)** and observe how the input is not kept in focus

_(i could provide a video or repository on this particular bug if you preferred)_

### Logs

_no response_

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.59 GB / 15.93 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\.yarn\bin\yarn.CMD
    npm: 8.1.2 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.29)
  npmPackages:
    @sveltejs/kit: 1.0.0-next.196 => 1.0.0-next.196
    svelte: ^3.42.6 => 3.44.2
```

### Severity

blocking an upgrade

### Additional Information

_no additional information_

**Comment by bluwy** [comment]
This is likely caused by #2755. Perhaps we should only not unselect text selection when `keepfocus` is true too
