### ISSUE TITLE
Colors blinking on page load (Windicss)

### ISSUE THREAD

**Issue by JuanRaymundo** [sveltejs/kit#2856]
### Describe the bug

Colors blinking on page load only on production, I make some custom colors with Windicss (to css vars)

![image](https://user-images.githubusercontent.com/18089878/142804754-9bbd533c-00a0-4b95-86c3-fac73b3d255b.png)

The blinking time increase in a UI library that I'm developing :(

- Live demo: https://sveltekit-example-934hwsilh-jrcj52-gmailcom.vercel.app/
- Repo: https://github.com/JuanRaymundo/sveltekit-example

### Reproduction

- Create a new sveltekit project
- Install Windicss
- Add some custom colors to css vars (https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo)
- Fill css vars programmatically (from style attribute)
- Build and run as production

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 4.56 GB / 15.38 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.31 
    @sveltejs/kit: next => 1.0.0-next.196 
    svelte: ^3.38.3 => 3.44.2
```

### Severity

annoyance

### Additional Information

Works fine on development mode

**Comment by zakaria-chahboun** [comment]
That's happens to me also! Just because of the `Vite` Development Mode, When i changed the adapter to `node-adapter` for SSR! everything is good.

**Comment by Rich-Harris** [comment]
For some reason, the CSS hashes differ between SSR and CSR. In the linked repro, the SSR'd `<button>` has the classname `svelte-1p0ff7b`, but when it hydrates the classname becomes `svelte-hpusq4`. That's why there's a flash of unstyled content.

These hashes are based on the contents of `<style>`. I'm not sure how they can differ — the preprocessor is outputting the same result in both SSR and CSR modes. Will investigate further, just wanted to leave some breadcrumbs for my future self.

**Comment by bluwy** [comment]
While this seems like a bug, when integrating windicss it's [recommended](https://windicss.org/integrations/vite.html#sveltekit-as-of-1-0-0-next-102) to use the [Vite plugin](https://windicss.org/integrations/vite.html) instead of the Svelte preprocessor as that handles CSS more reliably.

**Comment by dominikg** [comment]
addendum: under the hood vite-plugin-windicss also provides a [svelte preprocessor](https://github.com/windicss/vite-plugin-windicss/blob/03b27ab6d5fa53a32171ea5bdeaccecd0ad0a3ba/packages/vite-plugin-windicss/src/index.ts#L205 ) that is being picked up by [vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte/blob/98671039942c6a3cb475c5056db6bf932926380e/packages/vite-plugin-svelte/src/utils/preprocess.ts#L140)

**Comment by gtm-nayan** [comment]
Just checked with kit@next.350 and adapter-vercel@next.58 and it looks like this doesn't happen anymore. The hash is hpusq4 on both the SSR'ed response and after hydration. 

At least I think so because the render function has this but no mention of the `1p0ff7b` hash.
```js
<button style="${"--primary: " + escape(primary) + "; --primary-contrast: " + escape(primaryContrast) + ";"}" class="${"p-2 rounded bg-primary text-primary-contrast svelte-hpusq4"}">${slots.default ? slots.default({}) : ``}
</button>
```

@JuanRaymundo can you update your repro and check on a deploy if it's fixed or not?

**Comment by JuanRaymundo** [comment]
it work's fine, thanks for help me and make svelte great :)

**Comment by mquandalle** [comment]
I have the same issue of blinking style due to a different CSS hashes between SSR and CSR when using windiCSS in a sveltekit app. I have the latest version of all packages:

```
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.66 => 1.0.0-next.76 
    @sveltejs/kit: ^1.0.0-next.409 => 1.0.0-next.491 
    @sveltejs/pancake: ^0.0.18 => 0.0.18 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.0.4 => 3.1.3 
    vite-plugin-windicss: ^1.8.8 => 1.8.8 
    windicss: ^3.5.6 => 3.5.6 
```

**Comment by mquandalle** [comment]
I have a really hard time trying to create a minimal reproduction for this issue. Spend a few hours trying various things without success. But it seems related to how the CSS files are splited, in my minimal reproduction all the CSS is bundled in a single file but in original app there are multiple files, not sure what's the logic for splitting CSS files and how I could reproduce it without the full app.
