### ISSUE TITLE
Router changes the URL prematurely

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#2870]
### Describe the bug

When using links within the SvelteKit app, the URL gets updated immediately, even though the underlying page is still loading. In this simple demonstration the second-page loads for 1s, but the URL is updated a immediately:

![CleanShot 2021-11-23 at 14 09 45](https://user-images.githubusercontent.com/5859177/142983691-54a6d6ce-9274-4860-a64f-7555625a04f4.gif)

This is unconventional and results in asynchrony between the URL and the page content.

For contrast, here is what happens when clicking on the second link with rel="external", which triggers normal browser behavior: 

![CleanShot 2021-11-23 at 14 10 35](https://user-images.githubusercontent.com/5859177/142984018-569e3747-4127-427d-96d1-9a41b58f9224.gif)

Here you can see that both the URL and the page change at the same time. The page represents the URL at every moment. This behavior and universal across browsers.

SvelteKit mimicks browser behavior with History API. To do it correctly, the URL needs to be changed after the page is loaded.

### Reproduction

[Stackblitz](https://stackblitz.com/edit/sveltekit-aajlpj?file=src/routes/index.svelte)
[Source Code](https://github.com/ebeloded/sveltekit-issue-2870/tree/master)

### System Info

```shell
-
```

### Severity

annoyance

**Comment by harshmandan** [comment]
Can confirm it happens with me as well.

**Comment by Rich-Harris** [comment]
Explanation of why the current behaviour is intentional: https://github.com/sveltejs/kit/pull/2917#issuecomment-979419299

**Comment by ebeloded** [comment]
Given the split in opinions regarding the URL change behavior, could this be added as a configuration option?

**Comment by rmunn** [comment]
> Explanation of why the current behaviour is intentional: [#2917 (comment)](https://github.com/sveltejs/kit/pull/2917#issuecomment-979419299)

But since the browser's built-in behavior is the opposite (see second GIF in https://github.com/sveltejs/kit/issues/2870#issue-1060911996), IMHO it should be the other way around, with the URL not updating until after `load()` completes. There's also the fact that the current behavior is causing #2945, and may be causing other issues as well.

**Comment by benmccann** [comment]
I wonder, if we did want to mirror the browser behavior, if the most analogous place to update the url would be in between the network fetch and dom rendering, which I think would be here:

https://github.com/sveltejs/kit/blob/943835f883eb41c811708a6deebcb31c674bd1fe/packages/kit/src/runtime/client/renderer.js#L442

**Comment by Rich-Harris** [comment]
Did a reverse ferret on this — `pushState` is now deferred until navigation completes: https://github.com/sveltejs/kit/pull/4070
