### ISSUE TITLE
With paths.base configured, index page is inaccessible without a trailing slash

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#2886]
### Describe the bug

When `kit.paths.base` is configured, the index page cannot be accessed without a trailing slash. Adjacent pages work.

Config:
```js
const config = {
  kit: {
    paths: {
      base: '/admin',
    }
}
```

files:
```
src/routes/index.svelte
src/routes/not-index.svelte
```

With the above setup, here's how it works:

`/admin` - 404 (but expected index)
`/admin/` - index
`/admin/not-index` - not-index

### Reproduction

The issue reproduced on Stackblitz: https://stackblitz.com/edit/sveltekit-44rsrt?file=svelte.config.js

When the app is running, try navigating to `/admin` to see the 404.

Repo: https://github.com/ebeloded/sveltekit-base-path-index-issue

### System Info

```shell
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.196 
    svelte: ^3.42.6 => 3.44.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

We need to be able to use the app from a non-root path and having a working index page is critical

**Comment by j9108c** [comment]
+1 i am also experiencing the same issue

**Comment by nhe23** [comment]
On the current version the trailing slash is removed from the url automatically and also results in a 404. I'll have a look and try to come up with a fix.

**Comment by nhe23** [comment]
With the current version of Sveltekit (v1.0.0-next.232) I cannot reproduce this issue. Here is my repo: [https://github.com/nhe23/test-2886](https://github.com/nhe23/test-2886).

**Comment by ebeloded** [comment]
Yay!
