### ISSUE TITLE
`ReferenceError: Cannot access uninitialized variable` on Safari

### ISSUE THREAD

**Issue by pheuter** [sveltejs/kit#2889]
### Describe the bug

Running Svelte Kit app using `> svelte-kit dev --port 3001` works in Chrome but throws the following error only in Safari:

```
ReferenceError: Cannot access uninitialized variable.
```

Issue is in `async _load_node({ status, error, module, page, stuff }) {}` in _.svelte-kit/dev/runtime/internal/start.js_

![image](https://user-images.githubusercontent.com/92698/143264245-e554ba13-a417-42da-9056-e64df3f0e59a.png)

For some reason, Safari doesn't like the fact that the variable is named `module` and further thinks it's undefined?

### Reproduction

Any svelte-kit boilerplate.

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.38 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.1.0 - ~/.nvm/versions/node/v17.1.0/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v17.1.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.55 => 1.0.0-next.55 
    @sveltejs/kit: 1.0.0-next.199 => 1.0.0-next.199 
    svelte: 3.44.2 => 3.44.2 
```

### Severity

blocking all usage of SvelteKit

### Additional Information

<img width="1389" alt="Screen Shot 2021-11-24 at 10 26 48 AM" src="https://user-images.githubusercontent.com/92698/143266814-9eab47f0-8c50-42f0-9cc3-21a8b09ff562.png">

**Comment by Rich-Harris** [comment]
I can't reproduce this in Safari 15.1. Is it still occurring?

**Comment by pheuter** [comment]
@Rich-Harris Thanks for checking in, I haven't been able to reproduce it anytime recently, likely due to some third-party library that interfered with SSR.

**Comment by brittianwarner** [comment]
This is occurring for me in Safari when trying to access dynamic routes.  Let me know if you need more information about my project.  

<img width="2489" alt="image" src="https://user-images.githubusercontent.com/18333842/205845322-d9470b9a-1568-4161-ab43-dd880372e26a.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/18333842/205845429-02e7e4ac-c530-42b2-b7eb-fd0fe2d2e002.png">

**Comment by segovo** [comment]
+1 I'm also having this issue (Safari 16.1), it only happens while running in dev and not in any builds.

No issues on chrome, no idea what's causing it yet.

**Comment by geoffrich** [comment]
@segovo @brittianwarner if you are still experiencing this issue, please open a new issue with a reproduction

**Comment by pheuter** [comment]
@geoffrich No problem, #8529

**Comment by brittianwarner** [comment]
@Rich-Harris @pheuter We finally resolved this issue. We fixed it by removing the esnext build target in our vite config, which was there for a couple of top-level awaits. [This](https://bugs.webkit.org/show_bug.cgi?id=242740) bug in webkit is what ultimately made us try this update. Hoping this helps someone that is currently telling everyone, "Safari is the new IE" :). 

@TuffDev

**Comment by Smilefounder** [comment]
@brittianwarner could you help to explain more on the action? Please.
"We finally resolved this issue by removing the esnext build target in our vite config"

**Comment by braden-w** [comment]
Just in case anybody else is stumbling upon this issue and is working with Tauri—opening the Tauri app in Chrome under port 5173 (or whatever port you have configured) enabled me to solve the issue. It turns out that I had variables that were accessed before declaration, and the details in Chrome were far more detailed (for some reason Safari gives cryptic errors). Had this issue many times and this has always been the fix.

**Comment by thesiti92** [comment]
we just started experiencing this bug when upgrading to SvelteKit 2. worked fine before, now its breaking only in safari (16.5 for me) on line 12 in exports.js:
```js
function validate(module, file) {
		if (!module) return;

		for (const key in module) {
			if (key[0] === '_' || expected.has(key)) continue; // key is valid in this module

			const values = [.
```

im trying to repro in a standalone environment, but currently having trouble. Would appreciate any help you guys may have!

**Comment by brittianwarner** [comment]
@thesiti92 Are you using any top level awaits? I don't think v2 supports top level awaits but this was my issue a while ago. Try spinning up a clean v2 project and see if it is still happening and you can at least narrow it down to something unique about your project. I worked through this a while ago and the best thing to do is try to follow best practices.

**Comment by jamestinman** [comment]
Also having this issue with Safari 
<img width="870" alt="image" src="https://github.com/sveltejs/kit/assets/1458976/ed718301-d60c-4e3a-b5f1-603a41ddb0c0">

Debugging the old-school way by cutting out code, it is triggered (for me) by inclusion of public env
```js
  import { env } from '$env/dynamic/public';
```
