### ISSUE TITLE
licenses are missing from individual packages

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#2893]
### Describe the bug

SvelteKit and all its associated packages are MIT licensed, per the LICENSE file at the root of the repo and the `"license": "MIT"` at the root package.json. We need to add that field to the individual packages (and possibly add some automated way to ensure new packages also have it?)

### Reproduction

N/A

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by benmccann** [comment]
To clarify, I think they have the `LICENSE` file, but the license field not included in `package.json` (I only checked `adapter-netlify`)

**Comment by si3nloong** [comment]
I think we can write a js script to check and create `LICENSE` file if it's not exists, it can be executed on lifecycle of `prepublish`

**Comment by bluwy** [comment]
Instead of automation, maybe we can have some sort of checklist for publishing new packages. Recently, adapter-cloudflare-workers and adapter-auto had some small issues publishing, we could document that in the checklist as well.
