### ISSUE TITLE
Build error starting with version 171

### ISSUE THREAD

**Issue by raduab** [sveltejs/kit#2912]
### Describe the bug

I am getting the following error when building, starting with version 171:

```
> Using @sveltejs/adapter-node
 > .svelte-kit/output/server/chunks/app-0d4ff97d.js:1703:25: error: Could not resolve "./global-61357231.js"
    1703 │       load: () => import("./global-61357231.js")
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~

 > .svelte-kit/output/server/chunks/__layout-048eba31.js:377:7: error: Could not resolve "./global-61357231.js"
    377 │ import("./global-61357231.js");
        ╵        ~~~~~~~~~~~~~~~~~~~~~~

> Build failed with 2 errors:
.svelte-kit/output/server/chunks/__layout-048eba31.js:377:7: error: Could not resolve "./global-61357231.js"
.svelte-kit/output/server/chunks/app-0d4ff97d.js:1703:25: error: Could not resolve "./global-61357231.js"
Error: Build failed with 2 errors:
.svelte-kit/output/server/chunks/__layout-048eba31.js:377:7: error: Could not resolve "./global-61357231.js"
.svelte-kit/output/server/chunks/app-0d4ff97d.js:1703:25: error: Could not resolve "./global-61357231.js"
```

### Reproduction

The build is working well for these versions of SvelteKit and adapter-node:

```
    "@sveltejs/adapter-node": "^1.0.0-next.55",
    "@sveltejs/kit": "^1.0.0-next.170",
```

After upgrading SvelteKit to version 171, it stops building.

Please see #2409 and #2453

### System Info

```shell
System:
    OS: Linux 5.15 Arch Linux
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 2.30 GB / 62.49 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 14.18.1 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.1.3 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.45
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.55 => 1.0.0-next.55 
    @sveltejs/kit: ^1.0.0-next.171 => 1.0.0-next.200 
    svelte: ^3.44.2 => 3.44.2
```

### Severity

blocking an upgrade

**Comment by antony** [comment]
Hi, can you provide a reproduction?

**Comment by raduab** [comment]
What do you mean @antony by reproducing the issue? You just have to run `svelte-kit build` (or `npx svelte-kit build` if you don't have svelte-kit installed) with the npm packages from the above system info.

**Comment by raduab** [comment]
Hi, you are right, I checked if the problem occurs on a fresh svelte-kit project, and it doesn't. It seems that indeed it is something related to my code. As far as I can see, it has something to do with the `global.css` file, which is imported by `__layout.svelte` like this:

```
<script>
  import('../global.css')
</script>
```

This works in development, but not on production &mdash I've tried with `adapter-node` and `adapter-static`. I'll try to find which is the problem and maybe reproduce it on a fresh install, otherwise, I'll close this soon.

**Comment by bluwy** [comment]
Is there a reason you're not importing the CSS as `import '../global.css'`?

**Comment by dummdidumm** [comment]
My guess is that it has to do with the config switch to not eagerly load/resolve dynamic imports. As Blu says, I suggest to switch this to a regular import.

**Comment by raduab** [comment]
Oh crap, I don't know when it was changed to dynamic import and why. Thank you @bluwy it works now. Closing this.
