### ISSUE TITLE
Async imports not being found

### ISSUE THREAD

**Issue by webdev03** [sveltejs/kit#2919]
### Describe the bug

I have a JSON file in src/lib/widgets with a directory name in it. It looks like this:
```json
[
  "project-embed"
]
```
In `src/lib/widgets` I have a directory named `project-embed` like the name in the JSON file.
When I use a file to loop over it and read the `widget.json` file in the directory (which would make it `src/lib/widgets/project-embed/widget.json`) it doesn't work, and instead gives this error:
`Cannot find module '$lib/widgets/project-embed/widget.json' from '/Users/(my user)/(my project)/src/lib'`
My line of code that gives the error is:
```js
const componentJSON = (await import("$lib/widgets/" + componentName + "/widget.json")) // error
```
componentName is "project-embed" and when I replace componentName with `"project-embed"` the import works as normal.

### Reproduction

https://github.com/webdev03/scratchinfo/tree/widgets You can use this branch and then start the development server, then go to [localhost:3000/leaderboards/loves](http://localhost:3000/leaderboards/loves) and watch your development logs for the error.

### Logs

```shell
Cannot find module '$lib/widgets/project-embed/widget.json' from '/Users/(my user)/(my project)/src/lib'
Error: Cannot find module '$lib/widgets/project-embed/widget.json' from '/Users/(my user)/(my project)/src/lib'
    at Function.resolveSync [as sync] (/Users/(my user)/(my project)/node_modules/.pnpm/resolve@1.20.0/node_modules/resolve/lib/sync.js:102:15)
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 72.40 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Firefox: 94.0.2
    Firefox Developer Edition: 95.0
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.31 => 1.0.0-next.31 
    @sveltejs/kit: next => 1.0.0-next.199 
    svelte: ^3.44.1 => 3.44.1
```

### Severity

blocking an upgrade

### Additional Information

I installed dependencies with pnpm.

**Comment by Rich-Harris** [comment]
Vite transforms modules as they're loaded/served, so that their dependencies can be found. This comes with a caveat — it must be possible to statically analyse their imports. An import like

```js
await import("$lib/widgets/" + componentName + "/widget.json")
```

is not statically analysable. The solution is to use [`import.meta.glob`](https://vitejs.dev/guide/features.html#glob-import):

```js
const components = import.meta.glob('./widgets/*/widget.json');

// later
const componentJSON = await components['./widgets/' + componentName + '/widget.json']();
```
