### ISSUE TITLE
.env.example is gitignored in starter templates 

### ISSUE THREAD

**Issue by gtm-nayan** [sveltejs/kit#2925]
### Describe the problem

#2905 made it so that `.gitignore` in the starter templates ignores all files starting with `.env.`. This also includes `.env.example` files. They are often used for other contributors/users to get a quick overview of the enviroment variables used within the project. These don't contain any secrets so they are safe to be tracked by git. 

### Describe the proposed solution

Include `.env.example` using the exclamation point pattern in .gitignore.

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again. It is not possible to re-include a file if a parent directory of that file is excluded. Git doesn’t list excluded directories for performance reasons, so any patterns on contained files have no effect, no matter where they are defined. Put a backslash ("\\") in front of the first "!" for patterns that begin with a literal "!", for example, "\\!important\\!.txt".
[Source](https://git-scm.com/docs/gitignore#_pattern_format)

### Importance

nice to have

**Comment by coyotte508** [comment]
From the way SvelteKit handles environment, it would make sens to change this:

- ignore `.env.local` and `.env.*.local`
- do not ignore `.env` or `.env.{production,development,test}`

SvelteKit [refers](https://kit.svelte.dev/docs/adapter-node#environment-variables) to [how Vite handles env](https://vitejs.dev/guide/env-and-mode.html#env-files)

The `.env.*.local` files override the `.env` files, and Vite recommend ignoring the local files but not the other. 

It's helpful if we want to make cloning a project friendly - there is no need to recreate a `.env` file locally each clone, the developer can directly start their project, and if they want to tune their config further they can create a `.env.local` file
