### ISSUE TITLE
page reset after goto.

### ISSUE THREAD

**Issue by kenchan97** [sveltejs/kit#2967]
### Describe the problem

Page A is a article list. have 10 articles in beginning
after infinite scroll , it will fetch more articles from backend. like 20 articles.

when user click one of the article and then "goto" Page B, its for detail content.
when user finish reading. And back to page A.
page A is "reset".  articles array is 10.
and DOM is reload

how can make it do not reload when goto another Page ?
the DOM do not change

### Describe the proposed solution

an option to make after goto do not change previous page

### Importance

nice to have

**Comment by Conduitry** [comment]
When you navigate off page A, its data is gone. We don't want SvelteKit to have to preserve the props or other state of each page you navigate from just in case you might want to return to it later.

You'll need to persist the state somewhere and make sure page A's `load` function returns the props corresponding to the state you want to see when you arrive there a second time.
