### ISSUE TITLE
Ability to intercept a navigation request

### ISSUE THREAD

**Issue by zommerberg** [sveltejs/kit#2974]
### Describe the problem

I was trying to build a confirmation dialog feature that appears before the user tries to leave the page.
![Screenshot_20211203_001741](https://user-images.githubusercontent.com/43446836/144512206-5c8b3c45-9bb9-46d5-badc-dcfced3779f4.png)

The problem that occurred is that normally in this case we would use `beforeunload` listener and prevent the navigation event from firing before leaving the page. However, in sveltekit we have client-side routing so this event is not fired. 

Currently, there is no good way of handling that.

### Describe the proposed solution

My proposed solution is to create a listener that exposes the navigation intent. 
Within this intent, we should be able to cancel the navigation and get the required information about the page we are trying to navigate to.

The idea is to create a `onBeforeNavigate` interceptor that is triggered when we use the following events:
- goto()
- popstate events
- anchor tags clicks

The interceptor could be used in the following way:
```
<script>
  import { browser } from '$app/env';
  import { onBeforeNavigate } from '$app/navigation';

     if (browser) {
       onBeforeNavigate((navigationIntent) => {

          //the url we are going to navigate to
	  console.log(navigationIntent.url);

          //optionally cancel the navigation
	  navigationIntent.cancel();

        });
      }
	
</script>
```

### Alternatives considered

An alternative is just to disable the client-side router

### Importance

i cannot use SvelteKit without it

**Comment by zommerberg** [comment]
Closing this since there is an issue for that already #560

**Comment by zommerberg** [comment]
Reopening this since it is a different request from the `onNavigate` function proposed by Rich. I think we can move the discussion about the `onBeforeNavigate` function in this request.

**Comment by zommerberg** [comment]
I was looking at the current route implementation and new `onBeforeNavigate` would need to be triggered by a  synthetic event. Currently we have "navigation-start" and "navigation-end" event, we should add something like "navigation-intent" event
and add it to all of the palces that handle click, goto and browser navigations like so:
```
                        //by default the navigation is allowed
	                let startNavigation = true;

                        //once we verified that the route is valid we emit a navigation-intent event
                        //we pass in the information about the current route as well as a function that 
                        //can prevent us from executing the navigation
			dispatchEvent(
				new CustomEvent('sveltekit:navigation-intent', {
					detail: {
						url: url.href,
						cancelNavigation: () => {
							startNavigation = false;
						}
					}
				})
			);

                        //prevent futher execution of navigation if the user has cancelled the navigation
			if (!startNavigation) return;

                        ...execute the navigation 
```

**Comment by IsaacHub** [comment]
Will this work for you? https://github.com/sw-yx/svelte-actions#preventtabclose

**Comment by zommerberg** [comment]
> Will this work for you? https://github.com/sw-yx/svelte-actions#preventtabclose

@IsaacHub  No, I also need to handle browser buttons, hrefs, and programmatically navigation without a button.

I've already made a pull request for that here: #2982
