### ISSUE TITLE
@html and export const hydrate = false; issue

### ISSUE THREAD

**Issue by dwsmart** [sveltejs/kit#2977]
### Describe the bug

Navigating from a page populated by `{@html ...}` with
```
<script context="module">
	export const hydrate = false;
</script>
```
To a different page doesn't remove this content, and doesn't load the content of the new page.

### Reproduction

[Example Repository at https://github.com/dwsmart/sveltekit-hydration-issue](https://github.com/dwsmart/sveltekit-hydration-issue)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 6.36 GB / 15.92 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: yarn install v0.24.6
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.14s. - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.41)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3
    @sveltejs/kit: next => 1.0.0-next.201
    svelte: ^3.44.0 => 3.44.2
```

### Severity

serious, but I can work around it

### Additional Information

The workaround is sadly to not use `hydrate = false` which seems a shame

**Comment by bluwy** [comment]
Note: reproducible in both dev and build

**Comment by Rich-Harris** [comment]
Brought the repro up to date and confirmed it works with current SvelteKit, replacing `hydrate` with `csr` — closing
