### ISSUE TITLE
Provide block-level global styles

### ISSUE THREAD

**Issue by mzenz** [sveltejs/kit#2981]
### Describe the problem

I think Svelte's local-first style policy is brilliant. That said, when it comes to global styles (think reset.css or styles that apply to an entire component library) I find it extremely clunky having to wrap every single style declaration with a `global()` statement.

### Describe the proposed solution

I would much prefer having some sort of block-level attribute as follows:

```html
<style scope="global">
body {
    color: red;
}

a {
    text-decoration: none;
}
</style>
```

### Alternatives considered

The main way to achieve this currently is by linking a global stylesheet inside `src/app.html`.

### Importance

nice to have

**Comment by Conduitry** [comment]
https://github.com/sveltejs/svelte-preprocess#global-style svelte-preprocess already lets you do this
