### ISSUE TITLE
Snyk reports code vulnerability in default startup project

### ISSUE THREAD

**Issue by dnotes** [sveltejs/kit#2987]
### Describe the bug

When starting up a new project with `npm init svelte@next`, the new [Snyk Vulnerability Scanner extension](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner) for VS Code reports a code vulnerability on lines 7 and 15 of `[uid].json.ts`: "Unsanitized input from an HTTP parameter [:7] flows [:7, :7, :7, :19, :27, :27] into fetch [:27], where it is used as an URL to perform a request. This may result in a Server-Side Request Forgery vulnerability."

This obviously doesn't represent a security vulnerability in either Svelte or Sveltekit, and in truth I don't completely understand whether this is an actual vulnerability or just a potential one in the startup project code. However, I think we should encourage people to use security tools like Snyk, and part of that encouragement should be ensuring that the startup code either pass all the security tests or else include an ignore comment and explain why they don't apply.

### Reproduction

[The kit repository](https://github.com/sveltejs/kit) contains the issue in `/packages/create-svelte/templates/default`.

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
    Memory: 491.80 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Firefox: 94.0.1
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/kit: next => 1.0.0-next.201 
    svelte: ^3.44.0 => 3.44.2
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
A lot of time has passed since this was opened and the startup project looks completely different now. If something similar persists, please open a new issue - thank you.
