### ISSUE TITLE
`ERR_REQUIRE_ESM` error when importing `ky-universal` in a server context

### ISSUE THREAD

**Issue by illright** [sveltejs/kit#2993]
### Describe the bug

I'm pretty sure this issue is caused by Vite, but the reproduction involves SvelteKit-specific details (`hooks.ts`), so I'm a little bit lost as to how to reproduce this issue outside of SvelteKit. If this issue is indeed off-topic here, I would appreciate guidance on how to check if this issue persists outside of SvelteKit in order to file a proper issue to Vite.

Certain libraries, namely, `ky-universal`, fail to be imported in the server context, such as the `src/hooks` module. This only happens in dev mode.

In the linked reproduction, the first request to http://localhost:3000 fails with an error message provided below in **Logs**. The subsequent requests proceed just fine.

### Reproduction

https://github.com/illright/sveltekit-repro-ky-esm

### Logs

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/illright/work/sveltekit-repro-ky-esm/node_modules/.pnpm/ky-universal@0.9.1_ky@0.28.7/node_modules/ky-universal/index.js from /home/illright/work/sveltekit-repro-ky-esm/node_modules/.pnpm/vite@2.6.14/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js not supported.
Instead change the require of index.js in /home/illright/work/sveltekit-repro-ky-esm/node_modules/.pnpm/vite@2.6.14/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js to a dynamic import() which is available in all CommonJS modules.
    at nodeRequire (/home/illright/work/sveltekit-repro-ky-esm/node_modules/.pnpm/vite@2.6.14/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66559:17)
    at ssrImport (/home/illright/work/sveltekit-repro-ky-esm/node_modules/.pnpm/vite@2.6.14/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66501:20)
    at eval (//home/illright/work/sveltekit-repro-ky-esm/src/hooks.ts:3:37)
    at instantiateModule (/home/illright/work/sveltekit-repro-ky-esm/node_modules/.pnpm/vite@2.6.14/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66544:15)
```

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.17 GB / 3.76 GB
    Container: Yes
    Shell: 3.3.1 - /bin/fish
  Binaries:
    Node: 17.1.0 - /usr/sbin/node
    npm: 8.1.3 - /usr/sbin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/kit: next => 1.0.0-next.201 
    svelte: ^3.44.0 => 3.44.2
```

### Severity

serious, but I can work around it

### Additional Information

Not directly related to the issue, but would like to draw attention to this nonetheless: `ky-universal` isn't meant to be used with projects that already ship `fetch` for Node, as is the case with SvelteKit. However, SvelteKit's polyfilling seems to fail in certain cases involving `globalThis.Headers`. Regular `ky` sometimes just cannot get the reference to this object.

Please excuse the relatively low quality of this issue's description, I'm just feeling very lost and frustrated at not understanding what's going on. I'm happy to follow up with more information and cooperate, but I will need some guidance from those who understand the internals.

**Comment by DaveKeehl** [comment]
I'm also facing the same issue with a recent library I created. You can see [this issue](https://github.com/DaveKeehl/svelte-reveal/issues/62) for more info. I also have no idea of what's happening and would like to get some clarification if possible.

**Comment by benmccann** [comment]
delete the lock file and try again. it works with Vite 2.7.1 released this morning
