### ISSUE TITLE
Importing from an absolute path `src/routes/_*.ts` or `$routes/_*.ts`  fails.

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/kit#3000]
### Describe the bug
According to the [documentation](https://kit.svelte.dev/docs#routing-private-modules) a private module is a file prefixed with an underscore `_`. But when referencing a file prefixed with `_` in routes using 

- the absolute path: `import {hello} from "src/routes/_hello.ts"`
- a "$routes"-prefixed path: `import {hello} from "$routes/_hello.ts"`

...  the build or `npm run dev` fails. It is slightly cumbersome to use relative paths, so the expected behaviour is for the file to be found in this way.

I have made a MWE repository to reproduce this issue.

### Reproduction

https://github.com/wvhulle/sveltekit-bug-report

- Start with the SvelteKit demo.
- Write a file to `src/routes/_hello.ts`.
- Import the file with a non-relative path.
- Run `npm run build` or `dev`

### Logs

```shell
~/Documents/my-app on  main [✘!+?⇡] is 📦 v0.0.1 via  v16.13.0 
❯ npm run build

> my-app@0.0.1 build
> svelte-kit build

vite v2.7.1 building for production...
✓ 7 modules transformed.
[vite]: Rollup failed to resolve import "src/routes/_hello" from "src/routes/test.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

### System Info

```shell
System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 519.37 MB / 15.36 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 8.2.0 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.45
    Firefox: 94.0.2
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Does it work with paths without underscores in them? If so, that's the part that would surprise me here.

`$lib` meaning `.../src/lib` is special pre-defined alias. It doesn't automatically apply to other folders in `.../src`. You would need to define additional aliases with Vite's https://vitejs.dev/config/#resolve-alias config and in your `tsconfig.json`.

**Comment by wvhulle** [comment]
Yes i have defined another alias in `tsconfig.json` for the `src/routes` folder as you can see in the `tsconfig.json` of the MWE repo. Without underscore it still doesn't work.

**Comment by supercoww** [comment]
@wvhulle yes you need to configure vite as well. Here is an example from sveltesociety.dev config.

https://github.com/svelte-society/sveltesociety.dev/blob/2aacc273453e32adc610e8c6a36e2eb240b527b8/svelte.config.js#L40-L44

In your case alias for routes could be:
```
'$routes': path.resolve('./src/routes') // import {hello} from "$routes/_hello.ts"
```
or something like this if you want to use an absolute path
```
'$': path.resolve('./') // import {hello} from "$/src/routes/_hello.ts"
```

**Comment by wvhulle** [comment]
Ah, thanks @supercoww !
