### ISSUE TITLE
Env variables are not accessed by vite in PROD 

### ISSUE THREAD

**Issue by narender2031** [sveltejs/kit#3004]
### Describe the bug

I am using the docker image for the production build. I have set my environment variables in docker and they are accessible by using `env`. But when I build the app these are not accessed by Vite. 

Please help me here!

### Reproduction

Create Svelte kit app by started. 
- create the docker image
- Create the env variables in the docker system. 
- use the VITE_ as a prefix. 

### System Info

```shell
Undefined
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
`VITE_` variables are bundled during build, not looked at at runtime in prod mode. If your Dockerfile is setting them at app runtime with `ENV`, this is expected. If that's not what's happening, we need a proper reproduction.

**Comment by narender2031** [comment]
> `VITE_` variables are bundled during the build, not looked at runtime in prod mode. If your Dockerfile is setting them at app runtime with `ENV`, this is expected. If that's not what's happening, we need proper reproduction.

@Conduitry Yes, Dockerfile is setting them at app runtime with `ENV`. 
Do you know any workaround for this.

**Comment by narender2031** [comment]
@Conduitry 

.env
```
VITE_SOME_ENV=hello
```

variable.ts
```
console.log(import.meta.env) // {VITE_SVELTEKIT_AMP: '', BASE_URL: '/_app/', MODE: 'production', DEV: false, PROD: true}
export const variables = {
	SOME_ENV: <string>import.meta.env.VITE_SOME_ENV,
};
```
NOTE: import.meta.env don't have `VITE_SOME_ENV` after the build

api.ts

```
import { variable } from './variable.ts'

const data = variable.SOME_ENV // const data = "undefined "
```
after the build `const data = "undefined "`  it replaced by `undefined`.


My docker image already has all the env variable inside the system `env`. When I build the file my env data is replaced by undefined.

**Comment by rmunn** [comment]
What happens if you change `import.meta.env.SOME_ENV` to `import.meta.env['SOME_ENV']`? I remember a while ago Vite was doing text replacement specifically looking for the text `import.meta.env.` (with a trailing period), but I haven't looked at it in months and don't know if that's still current Vite behavior. But if `import.meta.env['SOME_ENV']` works for you then that could be an easy workaround.

**Comment by benmccann** [comment]
@rmunn there should be some improvement on that front with Vite 2.7: https://github.com/vitejs/vite/pull/5404

@narender2031 can you try upgrading and see if it fixes your issue?

**Comment by bluwy** [comment]
I don't think `import.meta.env.SOME_ENV` or `import.meta.env['SOME_ENV']` would work, even with Vite 2.7. `import.meta.env` is a per-file variable and replacements must be done during build-time. `.env` files wouldn't work as well so we'd need a different strategy for this, here's two options:

1. Have a separate build script in docker that generates a static JS file, which would be imported by `app.html`.

```js
// env.js
window.__MY_ENV__ = "something"
```

```js
// your-code.js
console.log(__MY_ENV__)
```

Keep in mind that you need to shim it in dev and SSR if needed, possible with `kit.vite.define`.

2. Or have a separate build script that does a find+replace on the final build assets.

**Comment by IsaacHub** [comment]
vite looks like a horrible absurd bundler considering the number of issues and how childish and absurd those issues are. This vite nonsense is ruining the reputation of sveltekit. It's the only thing preventing the release of sveltekit. What a shame!

svelte team made a terrible mistake by choosing an incompetent bundler.

**Comment by bluwy** [comment]
@IsaacHub This issue has nothing to do with Vite, it's a common problem across any other bundlers like webpack, rollup, snowpack, so it's misleading to belittle Vite here. Plus, Vite 2.7 has solved many SSR issues, the majority of issues left are within SvelteKit itself. Vite is here to stay.

**Comment by bartosjiri** [comment]
@benmccann Tried upgrading to `1.0.0-next.202`, variables are still undefined with `import.meta.env.VAR_KEY` and `import.meta.env['VAR_KEY']` when provided through Docker. 

Reproduction repo available [here](https://github.com/bartosjiri/sveltekit-prod-env).

**Comment by korywka** [comment]
Sort of duplicate: https://github.com/sveltejs/kit/issues/3030

**Comment by benmccann** [comment]
Please see the environment variable FAQ: https://kit.svelte.dev/faq#env-vars

To use at runtime you'll need to instantiate yourself (see svelte.dev's hooks.js for an example). You can then pass to your templates using `session`

**Comment by SwatDoge** [comment]
This problem is still here and quite infuriating.

**Comment by SwatDoge** [comment]
This is an incredibly ugly hack to get this working, it converts process.env variables prefixed with VITE_ to an .env file before before runtime.

docker build file
```docker
...

COPY . .

CMD ["pnpm", "run", "preview"]
```

package.json
```json
"scripts": {
    "build": "node ./.patch/env_bind.js && vite build && rm .env",
    "preview": "node ./.patch/env_bind.js && vite build && rm .env && vite preview --host"
},
```

.patch/env_bind.js
```js
// Vite imports environment variables through import.meta.env. import.meta.env does not import docker variables like process.env does. This file patches this.
import fs from "fs";

const vite_env_variables = Object.entries(process.env).filter(variable => variable[0].startsWith("VITE_"));
const vite_env_variable_string = vite_env_variables.map(variable => variable[0] + "=" + variable[1]).join("\n");
fs.writeFileSync(".env", vite_env_variable_string, {encoding: "utf-8"});
```

I don't recommend using this, but in my case I dont have another choice until import.meta.env gets all the env variables

**Comment by AgusVelez5** [comment]
Hey, any update on this?

**Comment by cpres** [comment]
I solved this by building the .env from a shell script, using a pre-populated .env with `=null` for each variable.

docker-entry.sh:
```
#!/bin/sh

SRC=.env
OUTPUT="// generated"

while IFS="" read -r line || [ -n "$line" ]; do
    use_line=$line

    if expr "$line" : "VITE" > /dev/null; then
        ENVIRONMENT_VARIABLE_NAME=$(echo "$line" | sed -re 's/=.*//g')
        value=$(printenv "$ENVIRONMENT_VARIABLE_NAME")

        if [ "${value}" ] && [ "${value-x}" ]; then
            use_line="$ENVIRONMENT_VARIABLE_NAME = '$value';"
        fi
    fi

    OUTPUT="$OUTPUT\n$use_line"
done <$SRC

echo "$OUTPUT" > $SRC

http-server dist
```

**Comment by zebra-f** [comment]
https://stackoverflow.com/a/77490465/17756110 If anyone is still looking for the solution to this problem.

**Comment by BraveVN** [comment]
> https://stackoverflow.com/a/77490465/17756110 If anyone is still looking for the solution to this problem.

this is not the best practice when it forces me to store ENV production in the Dockerfile.
