### ISSUE TITLE
Static adapter doesn't create page for nested route under [...rest]

### ISSUE THREAD

**Issue by duncanwerner** [sveltejs/kit#3020]
### Describe the bug

I want to create a page that takes arbitrary parameters, so following the docs I create the route
```
src/routes/target/[...rest]/index.svelte
```
Which works as expected (very nice). However when building with the static adapter, no page is created for `/target`. It turns out this is because there is no link in my app directly to `/target` (I was routing using `goto`).

More concretely, in my example repo I create three routes:
```
src/routes/page-A.svelte
src/routes/page-B/index.svelte
src/routes/page-C/[...rest]/index.svelte
```

The static adapter automatically builds routes for `/page-A` and `/page-B` but not `/page-C`. If I add a page like `/routes/index.svelte`  that includes a link,

```html
...
<a href='/page-C'>page-C</a>
...
```
then the static adapter _will_ build the link to `/page-C`.

I can't tell if this is intended behavior and there is a config option that I am missing, but it seems to me that if the adapter creates a route for `Page-B` in the above example, it should create a route for `Page-C` as well. I get that you might not want to recurse infinite directories, but since `[...rest]` is magic that seems like it should work.

### Reproduction

repo:

https://github.com/duncanwerner/sk-1221

```
> npm run build && ls build
_app  favicon.png  index.html  page-A  page-B
```

uncomment links in `/src/routes/index.svelte`

```
> npm run build && ls build
_app  favicon.png  index.html  page-A  page-B  page-C
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 2.35 GB / 7.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.0.0 - ~/.nvm/versions/node/v17.0.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21
    @sveltejs/kit: next => 1.0.0-next.201
    svelte: ^3.44.0 => 3.44.2
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is intended. By default, prerendering (and the static adapter) crawls your app starting from each non-dynamic route. You can specify additional starting points with the `prerender.entries` config. https://kit.svelte.dev/docs#configuration-prerender

**Comment by duncanwerner** [comment]
Got it. Thanks, clearly I didn't parse the docs well enough.
