### ISSUE TITLE
_clock_gettime on El Capitan

### ISSUE THREAD

**Issue by Justiniscoding** [sveltejs/kit#3028]
### Describe the bug

Cannot build or preview a project

### Reproduction

Try building the example app with `npm run dev`

### Logs

```shell
dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/user/Documents/VSCode/Websites/sveltekit/node_modules/esbuild-darwin-64/bin/esbuild
  Expected in: flat namespace

> The service was stopped
Error: The service was stopped
    at /Users/user/Documents/VSCode/Websites/sveltekit/node_modules/esbuild/lib/main.js:1237:25
    at /Users/user/Documents/VSCode/Websites/sveltekit/node_modules/esbuild/lib/main.js:629:9
    at Socket.afterClose (/Users/user/Documents/VSCode/Websites/sveltekit/node_modules/esbuild/lib/main.js:607:7)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### System Info

```shell
System:
    OS: OS X El Capitan 10.11.6
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     E8235  @ 2.80GHz
    Memory: 32.50 MB / 2.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.19.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 96.1.32.115
    Safari: 11.1.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

After trying to follow the guide from https://github.com/evanw/esbuild/issues/1278 the error continued happening

**Comment by dominikg** [comment]
vite and sveltekit use esbuild. You should use an OS that is supported by esbuild. El Capitan had it's last release over 3 years ago and it is no longer maintained.

I strongly recommend you upgrade your OS.

An alternative solution may be using a combination of pnpm overrides and npm aliases to enforce using esbuild-wasm in place of esbuild.
package.json
```json
"devDependencies":{
  "esbuild-wasm":"latest"
},
"pnpm":{
  "overrides":{
    "esbuild":"npm:esbuild-wasm@latest"
  }
}
```

**Comment by fergardi** [comment]
I have Mac OSX El Capitan so upgrading my OS is not an option. But I switched from NPM to PNPM and the override worked fine.

Thanks @dominikg, your suggestion worked for me!

**Comment by Justiniscoding** [comment]
I forgot to say, I have the same case as @dominikg where I cannot upgrade my OS. The PNPM override did work perfectly for me too!

**Comment by dominikg** [comment]
Fortunately i'm not in that boat and again i'd like to emphasize that you should focus on not using El Capitan anymore. It is severely out of date and using it is a high risk.
