### ISSUE TITLE
@html issue on SSR hydration

### ISSUE THREAD

**Issue by half2me** [sveltejs/kit#3033]
### Describe the bug

When you put this code anywhere in a SvelteKit page that has SSR and hydration enabled:
```svelte
<p>
  {#if true}
    {@html '<p>Hey!</p>'}
  {/if}
</p>
```
It results in the following error when hydrating the server rendered page on the browser.
`Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'node.parentNode.removeChild')`

The error is only displayed on the browser console, and only when it is rendered on the server. If navigating to the page from another page (no ssr involved) then it works just fine.

### Reproduction

Reproduction is pretty easy, just initialise a new Sveltekit demo app:
`npm init svelte@next my-app`
And insert the code snippet somewhere on the index page:
```svelte
<p>
  {#if true}
    {@html '<p>Hey!</p>'}
  {/if}
</p>
```
Reload the page, so it gets rendered on the server.

### Logs

```shell
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'node.parentNode.removeChild')
	(anonymous function) (start.js:1210)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 438.47 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3
    @sveltejs/kit: next => 1.0.0-next.201
    svelte: ^3.44.0 => 3.44.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

In my case, this completely breaks my page. My styles are not rendered properly, and the page is unusable.
For a temporary workaround I'm disabling SSR for that page.

**Comment by dominikg** [comment]
does it happen only on dev or also on build?

cc @rixo for possibility of svelte-hmr issue

**Comment by half2me** [comment]
> does it happen only on dev or also on build?
> 
> cc @rixo for possibility of svelte-hmr issue

It happens on my production build too

**Comment by rixo** [comment]
AFAIK it is invalid HTML to nest `<p>` in `<p>`.

This:

```svelte
<p>
  {#if true}
    {@html '<p>Hey!</p>'}
  {/if}
</p>
```

renders to this:

```html
<p>
  <p>Hey!</p>
</p>
```

which, in the browsers unfolds to this (because the second `<p>` triggers auto close of the first one):

```html
<p></p>
<p>Hey</p>
</p> <!-- unexpected closing tag -->
```

The autoclose rule actually makes it the same as if you had written something like this:

```svelte
<p>{@html "text </p>"}
```

... which is not (and probably cannot) be supported by Svelte.

**Comment by half2me** [comment]
@rixo Thanks for pointing that out!
Putting it inside a div instead of a p fixed the issue.

Do you reckon it would be useful/possible for sveltekit to notify of invalid html when in dev mode?
I would have never guessed the cause of the issue from the error message.

**Comment by rixo** [comment]
> Do you reckon it would be useful/possible for sveltekit to notify of invalid html when in dev mode?

It doesn't seem really doable for Svelte to parse what's in a `@html` directive and make assumptions as to what makes it correct. Moreover, in real life scenario it will probably be some dynamic content (e.g. `{@html post.text}`) that's totally invisible to the compiler / IDE's static analysis.
