### ISSUE TITLE
`goto('./foo')` doesn't work correctly

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3039]
### Describe the bug

`goto(href)` wraps the internal `router.goto(href)`, which resolves `href` against the document base URI instead of the current location, which is probably more correct

### Reproduction

will add later

### System Info

```shell
latest kit
```

### Severity

annoyance

**Comment by benmccann** [comment]
> which is probably more correct

I want to make sure I understand - which way are you saying is more correct?

**Comment by bluwy** [comment]
I think Rich meant to always resolve relative links by the current location when the user calls `goto()` programatically. I think it makes sense from the user's point of view though.

**Comment by Rich-Harris** [comment]
this actually works just fine, not sure what i was thinking
