### ISSUE TITLE
`svelte-kit preview` doesn't pick up env vars declared in `.env`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3040]
### Describe the problem

During development, Vite loads `.env` files [according to this logic](https://vitejs.dev/guide/env-and-mode.html#env-files). `svelte-kit preview` doesn't read `.env` files; as such, env vars are missing.

### Describe the proposed solution

Load `.env` files with the same logic Vite uses (this is handwavy — Vite allows arbitrary 'modes', so it's unclear which file(s) we'd load in `preview` beyond `.env` and `.env.local`. `.env.prod` and `.env.prod.local`?)

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Hmm I have mixed feelings about whether this would be the desired behavior. Production builds don't automatically look at `.env` (I admit I haven't specifically checked, but I hope they do not!) so why should `preview`s?

`preview` loading `.env` might be convenient, but it sounds unwise to me. As in production, you should be responsible for making sure the environment variables in question are actually present in your environment.

**Comment by matmoxam** [comment]
I think this is in relation to using tools like dotenv and env-cmd. The intended purpose is to load env variables at runtime. Is there a better way to load env variables at runtime?

**Comment by Rich-Harris** [comment]
closing in favour of #4296
