### ISSUE TITLE
Top-level await in script and / or nuxt-like server data fetching

### ISSUE THREAD

**Issue by Gin-Quin** [sveltejs/kit#3043]
### Describe the problem

The actual way SvelteKit loads data from server before loading the page has two defaults:

1. it's very verbose 🗣️    
2. it's not type-safe ☠️   

This is a typical example of server-side rendering with SvelteKit:

```svelte
<script context="module" lang="ts">
  export async function load() {
    return {
      props: {
        foo: await fetch("api/foo") as string
      }
    }
  }
</script>

<script lang="ts">
export let foo: string
</script> 
```

So we've written a lot of code just to return a string, and it is absolutely not safe. You have to indicate the type first in the load function and then in the main script section.

Linters won't complain if we write something like this:

```svelte
<script context="module" lang="ts">
  export async function load() {
    return {
      props: {
        foo: await fetch("api/foo") as number // changed my mind, now it's a number
      }
    }
  }
</script>

<script lang="ts">
export let foo: string // ouch, forgot to change the type here
</script> 
```

### Describe the proposed solution

I won't describe a full proposed solution as I don't know about Svelte and SvelteKit internals, but instead I will share raw ideas that need refinement and further thinking.

With Vue and the `script setup` syntax, it is actually possible to use `await` in the main script section.

This wonderful feature brings that kind of syntax:

```svelte
<script lang="ts">
  const foo = await fetch("api/foo") as number
</script>
```

Which is extremely concise and type-safe.

I know for sure this is not a small feature, it would need changes even in the Svelte internal parts, not just SvelteKit.

Just making `await` working will not be a magical solution ; there should be a way to prevent data-fetching first from server and then from client after hydration. To achieve this in a clean way, **Nuxt 3** uses the `useFetch` composable:

```vue
<script setup lang="ts">
  const foo = useFetch("api/foo")
</script>
```

Which is not exactly the same approach as the `await` but quite close. Maybe SvelteKit should define its own `useFetch` / `useServerLoader` - or whatever it is named - utility function to deal with asynchronous server-side loading?

To deal with page parameters and similar stuff, I would use the same syntax as in client-side, ie with `$page` store. That simplifies things as you share one syntax for server and client.

I think this feature should be thought taking in consideration other issues about SvelteKit loading, as it might resolve them in an elegant way as well:

- [A function for getting the current load arguments #2979](https://github.com/sveltejs/kit/issues/2979)
- [RFC: svelte-urql: enable to query in SvelteKit load() function #1819](https://github.com/FormidableLabs/urql/issues/1819)
- [Multiple load functions #3042](https://github.com/sveltejs/kit/issues/3042)

### Importance

would make my life easier

**Comment by rogueyoshi** [comment]
Top level await would at least be consistent with the newer versions of node but there might be design choices at play here

**Comment by Gin-Quin** [comment]
Top-level await does not need newer versions of node since the code inside '<script>' is put inside a function.

**Comment by benmccann** [comment]
Related: https://github.com/sveltejs/kit/issues/2301

**Comment by Rich-Harris** [comment]
Using `await` in components for... something is a nice idea, but it's a change that would need to happen in Svelte itself, and would require a detailed RFC. It would at minimum need to be a Svelte 4 feature. Since we now have page endpoints (i.e. `foo.js` supplies props to `foo.svelte`, without a `load` function) the boilerplate issue is solved, and type safety is something that could be improved with #647 (we already have per-route types for `params`, we just need to do props as well), so I'll close this

**Comment by junaga** [comment]
@Rich-Harris 

Hi, total Noob here

This is a critically underestimated feature. Javascript Modules are the new default, used by every modern tool. (One of my personal favorites [Firebase](https://firebase.google.com/docs/web/setup#add-sdks-initialize)).

top-level `await`, together with the `export` and `import` statements are the defining characteristics of it.
_please add it to your svelte 4 todo <3_

cya
