### ISSUE TITLE
Long delay when importing a 5MB file

### ISSUE THREAD

**Issue by mquandalle** [sveltejs/kit#3046]
### Describe the bug

I experience a longer delay than expected when loading a file using a JavaScript `import` :

```js
const start = performance.now()

import data from "5mb-file.json"

const end = performance.now()
console.log(`Delay : ${end-start}ms`) // about 5s
```

The ~5s delay seems unreasonnable considering the size of the file.

For comparaison using `JSON.parse` and `fs.readFileSync` on the exact same file, I'm able to retreive the data in about ~0.1s.

### Reproduction

https://github.com/mquandalle/large-import-delay-vitejs-repro

The reproduction contains 2 server-side endpoints showcasing the two import methods (ES module or `JSON.parse`/`fs.readFileSync`), and a minimal UI to explain the issue a bit more.

### System Info

```shell
System:
    OS: Linux 5.13 Pop!_OS 21.04
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.63 GB / 15.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.11.0/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.0/bin/npm
  Browsers:
    Brave Browser: 96.1.32.113
    Firefox: 94.0
```

### Severity

serious, but I can work around it

### Additional Information

This issue occurs both on development mode and when the app is deployed and the import called for the first time (example: cold starts on Vercel lambdas)

**Comment by bluwy** [comment]
This is expected because you're transferring a 5MB file over the network. Both in the local server and prod server. Using `fs` is faster because everything stays locally and there's no intermediate step, so it's a caveat of web dev in general. Closing with the above explanation.

**Comment by mquandalle** [comment]
Unless I miss something, I don't see why the `import` would involve a netwok transfer, as the following lines are executed only on the server:

```js
import data from "data-5mb.json";
console.log(data.length)
```

and are taking ~5s in the context of ViteJS / SvelteKit. The same script executed with `node` (with `--experimental-json-modules`) is nearly instant.

**Comment by bluwy** [comment]
I see. I'll re-open this at the meantime, until we've figured out why the imports are slower on the server side.

**Comment by mquandalle** [comment]
The issue seems to only happen in dev mode, not in production or preview.

So it's probably related to Vite processing the import in dev mode.They may be way to opt-out from that behaviour, but I was unlucky with `vite.optimizeDeps.exclude`.

**Comment by bluwy** [comment]
I've checked the repro out today, filed an issue with Vite at https://github.com/vitejs/vite/issues/6154. It's because Vite has special transforms for JS files during dev mode for HMR, which impacted the loading time for this. However, I don't think JSON files should be impacted by this, since it's just JSON (perhaps I'm wrong but we'll see). Thanks for making a comprehensive repro btw! I'll close this and track the progress over at Vite.
