### ISSUE TITLE
Nested layout are re-initilized even if i navigate to a deeper router if i don't come from root route

### ISSUE THREAD

**Issue by neckaros** [sveltejs/kit#3052]
### Describe the bug

i have a server with a possible route of /server/[serverid]/library/[libraryid]
under /server/[serverid] i have a nested layout (initializing a store that depends on the serverid)

if i navigate from / to /server/[serverid]/ then to /server/[serverid/library/[libraryid]
my store in nested layout is only initialized once

now if i start navigaton from /server/[serverid]/
my nested layout is initialized a second time when i navigate to /server/[serverid/library/[libraryid]

### Reproduction

checkout repo:
git@github.com:neckaros/svelte-nestedlayouts-issue.git
( https://github.com/neckaros/svelte-nestedlayouts-issue )
npm install
npm run dev

First what works:
go to: http://localhost:3000/
click go to server
then click go to library
==> in the console you only see "INIT LAYOUT SERVER toto" once

now start your navigation at 'http://localhost:3000/server/toto' (refresh once at this url to make sure you are starting here
click go to library
you can now see in the console that 'INIT LAYOUT SERVER toto' is printed twice

### System Info

```shell
Chrome / windows / sveletekit@next
```

### Severity

blocking all usage of SvelteKit

### Additional Information

blocking my usage of sveltekit because it reinitialize store on each page navigation

**Comment by rmunn** [comment]
Probably related to SSR, where the first page you load is being server-side rendered. I followed your instructions and can't reproduce the error you're describing where you see "INIT LAYOUT SERVER toto" twice in the console logs. But I *do* see it once in the server logs and once in the browser console logs. Generally you don't want to run store initialization code in the server, as every client would then see the same store. So you might want to wrap your store initialization in `if (browser) { ... }` (see https://kit.svelte.dev/docs#modules-$app-env for details) to make sure it won't run during SSR.

**Comment by neckaros** [comment]
@rmunn thanks for taking the time of testing it out.
You are right about the SSR part. Weird that you cannot reproduce. I will close the issue an reopen if i'am able to reproduce on another PC.
