### ISSUE TITLE
Cloudflare adapter produces errors and warnings that fail the build

### ISSUE THREAD

**Issue by theurgi** [sveltejs/kit#3057]
### Describe the bug

`@sveltejs/adapter-cloudflare` fails to build in two cases:

1) When configured as follows:

```js
// svelte.config.js
import adapter from '@sveltejs/adapter-cloudflare'

const config = {
  // etc. 
  kit: {
    adapter: adapter(),
}

export default config
```

This produces many errors such as follows:

```
> Using @sveltejs/adapter-cloudflare
 > node_modules/eth-lattice-keyring/index.js:1:23: error: Could not resolve "crypto" (use "platform: 'node'" when building for node)
    1 │ const crypto = require('crypto');
      ╵                        ~~~~~~~~
```

I heed the error and change my configuration to use `"platform: 'node'"`, which brings us to the second case:

2) `"platform: 'node'"` configuration

```js
// svelte.config.js
import adapter from '@sveltejs/adapter-cloudflare'

const config = {
  // etc. 
  kit: {
    adapter: adapter({ platform: 'node' }),
}

export default config
```

Now on build all of the `Could not resolve` errors are gone, but I now get:

```
> Using @sveltejs/adapter-cloudflare
 > .svelte-kit/output/server/chunks/__layout-75c5dd94.js:4:7: warning: Ignoring this import because "node_modules/ethers/lib/index.js" was marked as having no side effects
     4 │ import "ethers";
       ╵        ~~~~~~~~
   node_modules/ethers/package.json:65:2: note: "sideEffects" is false in the enclosing "package.json" file
    65 │   "sideEffects": false,
       ╵   ~~~~~~~~~~~~~
```

and the build fails.

I have no problems building with `adapter-static` or `adapter-auto`. 

### Reproduction

1. Use `@sveltejs/adapter-cloudflare` in SvelteKit as described in [packages/adapter-cloudflare](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare)

2. Install `ethers` as a dependency and import it in a Svelte component

3. Run `svelte-kit build`

### Logs

```shell
Included in description.
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 1.59 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.asdf/installs/nodejs/16.11.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.0.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Firefox: 95.0
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4 
    @sveltejs/adapter-cloudflare: ^1.0.0-next.3 => 1.0.0-next.3 
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.22 
    @sveltejs/kit: next => 1.0.0-next.202 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

blocking all usage of SvelteKit

**Comment by theurgi** [comment]
Update:

The esbuild warnings for `"sideEffects": false` don't fail the build after all. The warnings persist but I was able to build after removing `node_modules` and `yarn.lock` and reinstalling.

**Comment by gustavopch** [comment]
Those `Ignoring this import because "path/to/file.js" was marked as having no side effects` warnings are very annoying though. It seems that whenever you import something, SvelteKit adds a side-effect import to the top of the output. It would be better if it could skip doing that for packages that are marked as side-effect free in their `package.json`s.

**Comment by fredguest** [comment]
Agreed, these warnings add a ton of noise, basically makes the Cloudflare logs unreadable for any actual issues.
