### ISSUE TITLE
CSS and JS as a string gets prepocessed, CSS in HTML doesn't appear

### ISSUE THREAD

**Issue by mhkeller** [sveltejs/kit#3080]
### Describe the bug

Svelte-kit likes to treat code examples in strings as actual code.

If I do something like this:

```html
<script>
  const css = `<style>
  h1 { 
    color: red; 
  }
</style>
`

</script>

<pre>
  <code>
    {css}
  </code>
</pre>
```

The resulting out put in the DOM gets appended with `*{}` like so:

```
<style>
 h1 { 
   color: red; 
 }
 *{}</style>
```

If I try to write the `<style>` tag directly into the HTML within `<pre>` and `<code>` blocks, it doesn't appear at all.

In the JS example below, if I try to include a script tag, nothing works. In my local app, I see a different behavior: the compiler complains that the linked components don't exist.

### Reproduction

CSS example: https://stackblitz.com/edit/sveltekit-dcxy4c?file=src%2Froutes%2Findex.svelte

JS example: https://stackblitz.com/edit/sveltekit-yfuyi7?file=src%2Froutes%2Findex.svelte

### System Info

```shell
REPL
```

### Severity

annoyance

**Comment by dominikg** [comment]
svelte uses regex to find script and style blocks to preprocess. It should work if you "hide" them by concatenation `const style = "<sty"+"le>...</sty"+"le>"` or any other way to prevent the tag literals from being matched.

**Comment by mhkeller** [comment]
Thanks, that solved it.
