### ISSUE TITLE
Make vite a peer dependency?

### ISSUE THREAD

**Issue by applemonkey496** [sveltejs/kit#3081]
### Describe the problem

As it stands right now, installing any `vite` plugins to use with SvelteKit triggers a bunch of `unmet peer dependency vite>2.x` warnings. Presumably, this is because most plugins list `vite` as a peer dependency and not a regular dependency. 

Because SvelteKit has `vite` as a *regular* dependency, it's quite annoying to configure `vite` in any way without running into these warning messages. 

### Describe the proposed solution

Moving `vite` from the `dependencies` to the `peerDependencies` section in [`packages/kit/package.json`](https://github.com/sveltejs/kit/blob/master/packages/kit/package.json#L16) should resolve the issue. 

### Alternatives considered

It's possible to install `vite` with a wildcard version `*` just to suppress the warning, but this creates an unnecessary copy of the entire library and possibly some of its dependencies.

It's also possible to just ignore the warnings. The problem here is pretty much just an aesthetic one.

### Importance

would make my life easier

### Additional Information

If this change is made, `vite` should be added to the dependency lists in the `create-svelte` templates ([`skeleton`](https://github.com/sveltejs/kit/tree/master/packages/create-svelte/templates/skeleton), [`default`](https://github.com/sveltejs/kit/tree/master/packages/create-svelte/templates/default)) to avoid running into errors there.

This *would* be a breaking change so it might not be practical to introduce it at this point, but at the same time SvelteKit is still in development so it could be possible. This decision is obviously up to the developers.

**Comment by Conduitry** [comment]
For context, it used to be a peerdep and that was changed in #1239.

**Comment by applemonkey496** [comment]
Yeah, I suppose your previous issue is the exact opposite of mine...

If the motivation for that was to allow SvelteKit to use features from new versions of vite it would be possible to put vite as a peer dep and bump the minimum version whenever needed.

**Comment by dummdidumm** [comment]
Bumping the minimum peer dep is a breaking change (strictly speaking), so that would put us in a position where we can't bump the Vite version often which would be bad.

**Comment by applemonkey496** [comment]
Fair enough, yes. I seems like it makes the most sense to leave things how they are. Technically semver requirements (if sveltekit intends to comply with them) only allow breaking changes every major version, so even when sveltekit is fully stable you would only be able to bump the vite version every **major** sveltekit version (which is indeed bad). 

With that I think it's safe to close for now.
