### ISSUE TITLE
Add ability to return headers (set cookies) from load function

### ISSUE THREAD

**Issue by korywka** [sveltejs/kit#3082]
### Describe the problem

For now the only way to set cookie is to use `fetch` inside `load` function.

### Describe the proposed solution

Add ability to return headers without `fetch` something:

```
type ResponseHeaders = Record<string, string | string[]>;

export interface LoadOutput<
	Props extends Record<string, any> = Record<string, any>,
	Stuff extends Record<string, any> = Record<string, any>
> {
	status?: number;
	error?: string | Error;
	redirect?: string;
	props?: Props;
	stuff?: Stuff;
	maxage?: number;
        headers?: ResponseHeaders <--- this one
}
```

### Importance

nice to have

**Comment by Rich-Harris** [comment]
This wouldn't work with client-side navigation or with prerendering, so it would create confusion. In the case of `set-cookie` we _could_ set `document.cookie`, but this doesn't work with `HttpOnly` and we don't want to promote insecure practices in the framework.
