### ISSUE TITLE
"X" is null

### ISSUE THREAD

**Issue by akhefale** [sveltejs/kit#3084]
### Describe the bug

My team is building a platform that consists of users, each user being able to create projects and invite other users. We've been working on our platform for several months without issue, and have been making rapid progress thanks to the nature of Svelte and Sveltekit. We recently moved into closed beta. 

After deploying a minor update, older projects have broken. All modifications on the project (promise-based) result in the same error, with some seemingly random variation. I have no idea where to start debugging, as it seems like a Sveltekit bug. 

`Uncaught (in promise) TypeError: ce is null`
`Uncaught (in promise) TypeError: S is null`
`Uncaught (in promise) TypeError: P is null`

...and so on. These random variables seems to stem from sveltekit, as we haven't defined them anywhere. 

Wizards of the web, what do?

### Reproduction

Unable to provide reproduction code, as I'm unable to diagnose the project. The entire project is private. 

### Logs

```shell
 (in promise) TypeError: P is null
    y https://reaktor.rabotnik.coop/_app/pages/project/_id_.svelte-623ad825.js:11
    nt https://reaktor.rabotnik.coop/_app/pages/project/_id_.svelte-623ad825.js:11
    z https://reaktor.rabotnik.coop/_app/pages/project/_id_.svelte-623ad825.js:9
    Bo https://reaktor.rabotnik.coop/_app/chunks/vendor-b6c3eef8.js:1
```

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (1) x64 AMD EPYC 7601 32-Core Processor
    Memory: 106.19 MB / 1.94 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/bin/node
    npm: 6.14.15 - /usr/bin/npm
  Browsers:
    Firefox: 95.0
```
```


### Severity

blocking an upgrade

### Additional Information

_No response_

**Comment by dominikg** [comment]
We need a reproduction. 
To start understanding the issue better and then provide a repo with a minimal reproduction for us you could turn off minification in vite, hoping that the unminified names tell you sth about the location of issue
