### ISSUE TITLE
Slow prefetched load

### ISSUE THREAD

**Issue by PH4NTOMiki** [sveltejs/kit#3089]
### Describe the bug

I noticed that `load` request that has `fetch` request that has been already prefetched (either using `sveltekit:prefetch` or `prefetch` function) takes much more time(around 30-60ms difference, not that much but still) than when I just hardcoded values that are returned as props, and I don't understand why would that happen, cause when I check in the network monitor, it shows that those requests are indeed prefetched, and only requested once.

Thanks

### Reproduction

No need, literally any repo.

### System Info

```shell
System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 2.79 GB / 7.65 GB
    Container: Yes
    Shell: 5.1.12 - /bin/bash
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    npm: 8.1.4 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.93
    Firefox: 95.0.1
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.55 
    @sveltejs/kit: ^1.0.0-next.202 => 1.0.0-next.202 
    svelte: ^3.44.3 => 3.44.3
```

### Severity

annoyance

**Comment by bluwy** [comment]
Is this related to #2929? (Fix unreleased yet) `sveltekit:prefetch` hasn't been working recently on desktop. Otherwise I don't really see any call-to action here and it may be working as intended. I'd suggest providing a repro to make a comparison and potentially provide an analysis on what you think makes it slow.

**Comment by ww9** [comment]
@PH4NTOMiki out of curiosity, does this approach improve latency on your end?

```html
<script>
import { prefetch } from '$app/navigation';
export const prefetchUrl = function (e) {
   const link = e.target;
   if (link.getAttribute('fetched')) return;
   const url = link.getAttribute('href');
   prefetch(url);
   link.setAttribute('fetched', 'yep');
};
</script>

<a href="/link" on:mouseover={prefetchUrl} on:focus={prefetchUrl} on:touchstart={prefetchUrl}>Link</a>
```

**Comment by bluwy** [comment]
Closing this as #2929 has been released, and there was no response from OP.

> out of curiosity, does this approach improve latency on your end?

This should already be done by SvelteKit out-of-the-box. I don't think it'll improve the prefetch performance.
