### ISSUE TITLE
Templating app.html

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#3091]
### Describe the problem

Currently SvelteKit templating is fairly simple: it replaces `%svelte.head%` and `%svelte.body%` entries in `app.html`.

However, sometimes it is necessary to augment some parts of `app.html` that are outside of Svelte's control. 

For example, for i18n one needs to be able to change the `lang` attribute on `<html>` or set a class on `<body>` tag.

### Describe the proposed solution

It would be useful if SvelteKit provided some built-in templating solution for `app.html` that extends beyond replacing `%svelte.head%` and `%svelte.body%` and provides access other request parameters.

### Alternatives considered

It is possible to do such templating in `handle` hook. For example, we can define some logic in `app.html` in EJS format and then run the templating engine on `response.body` before returning it from the hook.

### Importance

would make my life easier

**Comment by miohtama** [comment]
As a workaround please checl [svelte-body](https://www.npmjs.com/package/svelte-body) package. Though not sure if it can do `<HTML lang>`.

**Comment by abdo643-HULK** [comment]
it can be done with <svelte:body> but with a lot of limitations right now, but there is an open issue for that: https://github.com/sveltejs/svelte/issues/3105. For the <html> you can't but any attributes that need to change in the app.html file for this to work. I use it like this in my project : 
```
<svelte:head>
	<html {lang} {dir} />
</svelte:head>
```

**Comment by arichard-info** [comment]
> it can be done with svelte:body but with a lot of limitations right now, but there is an open issue for that: [sveltejs/svelte#3105](https://github.com/sveltejs/svelte/issues/3105). For the `<html>` you can't but any attributes beforehand in the app.html file that need to change for this to work. I use it like this in my project :
> 
> ```
> <svelte:head>
> 	<html {lang} {dir} />
> </svelte:head>
> ```

Wow thanks for the `<svelte:head>` trick. Didn't know that `<html>` was a valid tag. Is is documented somewhere ?

**Comment by abdo643-HULK** [comment]
> > it can be done with svelte:body but with a lot of limitations right now, but there is an open issue for that: [sveltejs/svelte#3105](https://github.com/sveltejs/svelte/issues/3105). For the `<html>` you can't but any attributes beforehand in the app.html file that need to change for this to work. I use it like this in my project :
> > ```
> > <svelte:head>
> > 	<html {lang} {dir} />
> > </svelte:head>
> > ```
> 
> Wow thanks for the `<svelte:head>` trick. Didn't know that `<html>` was a valid tag. Is is documented somewhere ?

not really, got it from some example/project. This works because a page can only have one html tag and this trick puts a second one in the head and the browser automatically takes the tags and puts them into the top tag. It's not the cleanest solution and I haven't tested if there are any a11y issues.

**Comment by itssumitrai** [comment]
Just stumbled upon this, I would like this functionality because we have plenty of assets which we get from npm packages. And these npm packages are supposed to be only server side usage.

Something like

```
import { getUrl } from 'my-internal-pkg';
```
Then we need to be able to slot this url asset into the template during build time or run time. But like the description said, the `app.html` is not flexible.

`vite` has a hook for this purpose though:

https://vitejs.dev/guide/api-plugin.html#transformindexhtml

But its not working with sveltekit probably because the `html` is named `app.html` ?

**Comment by abdo643-HULK** [comment]
> Just stumbled upon this, I would like this functionality because we have plenty of assets which we get from npm packages. And these npm packages are supposed to be only server side usage.
> 
> Something like
> 
> ```
> import { getUrl } from 'my-internal-pkg';
> ```
> 
> Then we need to be able to slot this url asset into the template during build time or run time. But like the description said, the `app.html` is not flexible.
> 
> `vite` has a hook for this purpose though:
> 
> https://vitejs.dev/guide/api-plugin.html#transformindexhtml
> 
> But its not working with sveltekit probably because the `html` is named `app.html` ?

I am working on a script to do that. I also creates favicons and all apple images

**Comment by Rich-Harris** [comment]
`transformPage` is the recommended way to inject values into HTML outside Svelte's control — e.g.:

```html
<html lang="%lang%">
```

```js
export function handle({ event, resolve }) {
  return resolve(event, {
    transformPage: ({ html }) => html.replace('%lang%', get_lang(event))
  });
}
```

Closing this as I don't think there's a way to make this more convenient without cluttering the API with something less flexible

**Comment by Korayem** [comment]
> `transformPage` is the recommended way to inject values into HTML outside Svelte's control — e.g.:
> 
> ```
> <html lang="%lang%">
> ```
> 
> ```js
> export function handle({ event, resolve }) {
>   return resolve(event, {
>     transformPage: ({ html }) => html.replace('%lang%', get_lang(event))
>   });
> }
> ```
> 
> Closing this as I don't think there's a way to make this more convenient without cluttering the API with something less flexible

For those searching for this fix, note that the method has changed.  Just replace `transformPage` with `transformPageChunk` based on #4910

**Comment by tontonsb** [comment]
> For the `<html>` you can't but any attributes beforehand in the app.html file that need to change for this to work. I use it like this in my project :
> 
> ```
> <svelte:head>
> 	<html {lang} {dir} />
> </svelte:head>
> ```

The reason why this works is explained in the HTML [parsing](https://html.spec.whatwg.org/multipage/parsing.html) spec. It says that for HTML start tags encountered anywhere within the HTML itself it will add new attributes (but not overwrite existing values):

> for each attribute on the token, check to see if the attribute is already present on the top element of the stack of open element. If it is not, add the attribute and its corresponding value to that element.

Btw the same behaviour is implemented for repeated BODY start tags.

**Comment by trusktr** [comment]
We need a way to inject entry points into app.html.

**Comment by coyotte508** [comment]
There `%sveltekit.env.XXX%` available now

**Comment by 0gust1** [comment]
Hi, I'll add a use case I'm currently confronted with:

- I generate a static website using Sveltekit
- Content/posts are expressed as markdown files (mdsvex FTW!)
- Content/posts can be in different languages. This lang is expressed as a `lang` metadata in the frontmatter of the posts.

I quickly looked into the `transformPageChunk` solution, but right now I don't see how I can _easily_ pass the info (which come from the post metadata/frontmatter) to the `transformPageChunk` function (i.e. how to attach/express this info on the `event` object). 

I guess I could/should use in my `hooks.server.ts` the "data module" that executes `import.meta.glob(`/src/posts/**/*.{md,svx,svelte.md}`)` at build time and try to make a match between the url of `event` and the post's slug to get the eventual `lang` metadata in the frontmatter. But it feels a bit complicated and clunky.

Right now (easy/short-term), I let the `<html>` tag have its `lang='en'` attribute and I set `lang='<LANG>'` on the `<article>` or `<section>` below (not optimal, but semantically correct as far I know).

**Comment by figurae** [comment]
ATM, I use this solution. I have a store containing the current locale and in its subscribe method I do this:

```typescript
localeStore.subscribe((localeValue: string) => {
	if (browser) {
		window.localStorage.setItem('website-locale', localeValue);
		locale.set(localeValue);

		document.documentElement.setAttribute('lang', localeValue);
	}
});
```
Works quite well for what it is.

**Comment by mindplay-dk** [comment]
I couldn't find this in the docs or anywhere, but why do the app and error templates need to be written in a different template syntax in the first place? 

I was expecting these would just be Svelte templates - is there any obvious reason why they aren't?
