### ISSUE TITLE
Allow paths that have segments starting with underscore

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#3092]
### Describe the problem

SvelteKit router has "private modules" feature that hides folders and files that start with an underscore from the router. ([docs](https://kit.svelte.dev/docs#routing-private-modules))

Sometimes it is necessary to have a path that starts with underscore though. For example, AppEngine [warmup request](https://cloud.google.com/appengine/docs/standard/nodejs/configuring-warmup-requests) is a fixed path `/_ah/warmup`. Implementing a normal endpoint for such path is currently impossible. 

### Describe the proposed solution

Not quite sure if the private modules in routes are necessary - private things can be put elsewhere. But if they are going to stay, then maybe the underscore convention should be reconsidered. Maybe use a symbol that can't be in a URL path - like a `#`, for example.

### Alternatives considered

Implementing a handler for a path with underscore, such as`/_ah/warmup`, can be done in `handle` hook or in a middleware.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
You could also use the handle hook to change the current path (to not have a leading underscore) and then leave all the actual code for it in a regular endpoint route file.

Files in the routes directory that aren't routes are very useful to have and we won't be getting rid of that feature.

This issue feels like #2930 and the same solution could presumably resolve both.

**Comment by Rich-Harris** [comment]
Indeed, this can be closed now that we have https://kit.svelte.dev/docs/configuration#routes
