### ISSUE TITLE
build fails when using vercel adapter (no not the same as the other ticket)

### ISSUE THREAD

**Issue by jmsunseri** [sveltejs/kit#3104]
### Describe the bug

I'm creating a state machine use xstate and my someMachine.ts file does

import { useMachine } from '@xstate/svelte';

works fine locally using adapter-auto but switching to adapter-vercel causes the build to fail saying 

'lib.useMachine is not a function'

changing import statement to 

import { useMachine } from '@xstate/svelte/lib/useMachine';

resolves the issue;

### Reproduction

none at this time

### System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
    Memory: 201.83 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Chrome: 96.0.4664.110
    Safari: 15.2
```

### Severity

annoyance

### Additional Information

thank you for your time

**Comment by Figments** [comment]
i'm having a similar issue with a shared models library, everything in it seems to be imported correctly except a single enum, which SvelteKit thinks is not exported. this isn't a problem in my backend API project, which uses the same shared library and imports the same things.

**Comment by jmsunseri** [comment]
I import the same library in different components in the same project and
no issues with the import.  The only two files where this import breaks is
the stateMachine.ts files

Sincerely,
Justin Sunseri

**Comment by benmccann** [comment]
>Reproduction
none at this time

I'm sorry, but the reproduction isn't optional. I'm happy to take a look at this if there's a way to reproduce on my machine

**Comment by jmsunseri** [comment]
You don't have to close a legitimate issue without at least asking me and giving me a day to come up with a reproduction.  What the best way to provide a repro for a build issue that only pops up on a specific adapter?  is there a REPL that will support this case?

**Comment by jmsunseri** [comment]
@benmccann I tried to reproduce on a project from scratch but was unable to.  I just granted you access to my private repo.  You should be able to pull down the 'build-issue' branch and run yarn build to see the issue.

**Comment by benmccann** [comment]
I can't build your project because it's saying `supabaseUrl is required`. But anyway, I'm guessing there might not be a lot we can do because the entire xstate packaging situation seems like a mess:
- https://github.com/statelyai/xstate/issues/2893
- https://github.com/statelyai/xstate/issues/2642
- https://github.com/statelyai/xstate/issues/2458

Hopefully that library will fix its packaging at some point. There seems to be a PR pending that says it fixes some things to allow it to work on SvelteKit: https://github.com/statelyai/xstate/pull/2474. Perhaps you can ping that PR and see if it can be merged

**Comment by jmsunseri** [comment]
Why does it work locally using the auto adapter but fails with vercel
adapter?  Keep in mind this isn't only an xstate issue.  I've seen other
similar reports with different libraries.  Let me fix the supabase url
issue for you.

**Comment by benmccann** [comment]
The auto adapter isn't actually running the whole build process. If you tried to build using the auto adapter on Vercel it would detect that platform and fail in the same way. But if you try to build locally with the auto adapter then it doesn't know you want to build for Vercel and so it doesn't complete the build and gives you the warning:
> Could not detect a supported production environment. See https://kit.svelte.dev/docs#adapters to learn how to configure your app to run on the platform of your choosing

**Comment by jmsunseri** [comment]
I have fixed the repo so that it should have some dummy information for the supabase config so you should get past that.  I would also like to note that the library that is actually being complained about was '@xstate/svelte' not 'xstate'

**Comment by benmccann** [comment]
I still think the best solution is to try to get https://github.com/statelyai/xstate/pull/2474 merged
