### ISSUE TITLE
page.params value changes if url used in a 'style' doesn't exist... (weird one)

### ISSUE THREAD

**Issue by neiled** [sveltejs/kit#3106]
### Describe the bug

When an invalid URL is used in a background-image: style the page params value changes to that URL... 

I've created a repo that reproduces this here:
https://github.com/neiled/imgurl

Run the app and goto` /profile/<something>`
Check the logging of the page.params
First load of the page (SSR?) you see the params as `id=<something>`
Second load of the page (the client?) you see the params value for id is now whatever is used as the url in the 'style'.
Blew my mind.

In the example app it's shown as 'nothing that exists' (see the log below)

`<div class="" style="background-image: url('nothing that exists');" />`

### Reproduction

https://github.com/neiled/imgurl

### Logs

```shell
Logs of the page.params:

loading profile/[id]
{ id: 'hello' }
loading profile/[id]
{ id: 'nothing that exists' }
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 104.03 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.n/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.3 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4 
    @sveltejs/kit: next => 1.0.0-next.202 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

serious, but I can work around it

**Comment by zyxd** [comment]
The browser tries to load the background image of the div block by the url `nothing that exists` relative to `/profile/[id]`, so there is an additional page request `/profile/nothing that exists`.

If you try to request page with `curl` (raw output) or just fix the style to `background-image: url('/nothing that exists')`, there is only one log entry.

**Comment by neiled** [comment]
Ugh of course that makes so much sense. Thank you!!
