### ISSUE TITLE
Modulepreload generated html head link tags aren't closed and as such trip XHTML validator end tag omitted errors

### ISSUE THREAD

**Issue by david-smejkal** [sveltejs/kit#3107]
### Describe the bug

SvelteKit generates html head link tags that aren't closed.
```
<link rel="modulepreload" href="/_app/start-3fb567c5.js">
<link rel="modulepreload" href="/_app/chunks/vendor-89cc92cc.js">
<link rel="modulepreload" href="/_app/layout.svelte-eaee886a.js">
<link rel="modulepreload" href="/_app/pages/index.svelte-fd279b0c.js">
<link rel="stylesheet" href="/_app/assets/start-61d1577b.css">
```

It should generate closed and thus XHTML valid link tags instead.
```
<link rel="modulepreload" href="/_app/start-3fb567c5.js" />
<link rel="modulepreload" href="/_app/chunks/vendor-89cc92cc.js" />
<link rel="modulepreload" href="/_app/layout.svelte-eaee886a.js" />
<link rel="modulepreload" href="/_app/pages/index.svelte-fd279b0c.js" />
<link rel="stylesheet" href="/_app/assets/start-61d1577b.css" />
```

### Reproduction

- npm init svelte@next . # Skeleton project
- npm install
- edit src/app.html to use XHTML Doctype as per https://www.w3.org/2010/04/xhtml10-strict.html
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
```
- npm run build && npm run preview
- validate the source code using https://validator.w3.org/#validate_by_input

### Logs

```shell
Line 12, Column 60: end tag for "link" omitted, but OMITTAG NO was specified
<link rel="modulepreload" href="/_app/start-3fb567c5.js">
You may have neglected to close an element, or perhaps you meant to "self-close" an element, that is, ending it with "/>" instead of ">".
```

### System Info

```shell
Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    npm: 8.1.1 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chromium: 96.0.4664.93
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4 
    @sveltejs/kit: next => 1.0.0-next.202 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
Svelte itself doesn't support XHTML — if you have a [self-closing `<img/>` tag](https://svelte.dev/repl/9c19c5f3135b44c7a7b6652a78ebc7fc?version=3.44.3), for example, it will render as a void tag:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/1162160/147416739-b03cb79d-0506-4540-a617-95dbd6fc6e84.png">

Because of that, I'm not totally sure this is a worthwhile change by itself. Can you elaborate as to why you need this? Obviously it's a fairly small change by itself, but I'm uneasy about committing us to an ongoing need to ensure XHTML compliance.

**Comment by david-smejkal** [comment]
No real reason other than a desire to use a stricter standard to produce cleaner markup code.

I was convinced that `XHTML 1.0 Strict` would ensure wider browser compatibility but after reading a bit more about [potential downsides](http://www.webdevout.net/articles/beware-of-xhtml) and current trends I've changed my perspective. It seems that using HTML standard for `text/html` content-type is the more widespread and more browser compatible way to go.

Even W3C have adopted views of [WHATWG](https://www.w3.org/TR/html/) in the end as per their latest [HTML 5.2 specification](https://www.w3.org/TR/2021/SPSD-html52-20210128/).

**Comment by Rich-Harris** [comment]
Yep, XHTML was a cul-de-sac :) There's really no reason to use it in this day and age. I'll close this and the associated PR — thanks
