### ISSUE TITLE
possible memory leak, in an certain length in a each block

### ISSUE THREAD

**Issue by Bradley-H** [sveltejs/kit#3113]
### Describe the bug

In my current project, I'm looping through each block x amount of time that is determined by how many items are in my globalStore. I noticed my memory usage through this went from around 460mb up to over 1000.

### Reproduction

https://github.com/Bradley-H/Invoice-App

npm run dev

go to any invoice on your screen, and click on the edit button (desktop view) and should bring out a modal, thats when the memory usages go up.

I deduced it has something to do in my invoiceModal.svelte in the each block at the Array(length) when I remove it, there is no memory leak

![image](https://user-images.githubusercontent.com/37282160/147446551-5e36b313-bca7-453e-a676-063bc304529c.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz
    Memory: 8.48 GB / 15.78 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4
    @sveltejs/adapter-netlify: ^1.0.0-next.36 => 1.0.0-next.36
    @sveltejs/kit: ^1.0.0-next.201 => 1.0.0-next.202
    node-sass: ^7.0.0 => 7.0.0
    sass: ^1.45.0 => 1.45.1
    svelte: ^3.44.0 => 3.44.3
    svelte-check: ^2.2.6 => 2.2.11
    svelte-preprocess: ^4.9.4 => 4.10.1
    tslib: ^2.3.1 => 2.3.1
    typescript: ^4.4.3 => 4.5.4
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment]
We would need some additional information indicating a bug in SvelteKit before we could look at this. If there is a bug here, it seems more likely to be a bug in Svelte rather than SvelteKit. But even still, there's no clear indication there's a bug here rather than just some sort of user error
