### ISSUE TITLE
Svelte-kit & FullCalendar

### ISSUE THREAD

**Issue by IvanCastroR** [sveltejs/kit#3116]
### Describe the bug

I am trying to implement sveltekit and fullcallendar but it throws an import error with the FullCalendar plugin and even though I install and add a different plugin the error comes back.

### Reproduction

https://github.com/IvanCastroR/fullCalendar-sveltekit

### Logs

```shell
Please import the top-level fullcalendar lib before attempting to import a plugin.
@http://localhost:3000/node_modules/.vite/chunk-2WFLGF5O.js?v=1937cd08:3:9
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 
Graphics
    Memory: 2.10 GB / 10.96 GB
  Binaries:
    Node: 14.18.2 - C:\Program Files\nodejs\node.EXE    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD  
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.4    
    @sveltejs/kit: next => 1.0.0-next.202
    svelte: ^3.44.0 => 3.44.2
```

### Severity

serious, but I can work around it

### Additional Information

https://sveltekit-fullcalendar.netlify.app/

**Comment by abdo643-HULK** [comment]
There's an issue about that: https://github.com/YogliB/svelte-fullcalendar/issues/800 and another one that is currently open for cjs: https://github.com/YogliB/svelte-fullcalendar/issues/804

**Comment by IvanCastroR** [comment]
> There's an issue about that and how to work around it: https://github.com/YogliB/svelte-fullcalendar/issues/800 and another one that is currently open for cjs but for a custom svelte version: https://github.com/YogliB/svelte-fullcalendar/issues/804

I had already seen YogliB / svelte-fullcalendar # 800 and he contacted him, but he commented that the problem persists, even in his post they comment that the solution was only temporary because when adding new components the error returns

**Comment by benmccann** [comment]
Reading through the linked issues this would appear to be a bug in `svelte-fullcalendar` or Vite or both. There's nothing to indicate that there's any bug in SvelteKit though

**Comment by devShamim** [comment]
Just import @fullcalendar/core/vdom before you import svelte-fullcalendar and other fullcalendar plugins. Like this: 
`import '@fullcalendar/core/vdom';`
`import FullCalendar from 'svelte-fullcalendar';`
`import daygridPlugin from '@fullcalendar/daygrid';`

I am using this version (^2.0.0-beta.0) of svelte-fullcalendar along with **vite-4.0.1**

**Comment by chanmathew** [comment]
> Just import @fullcalendar/core/vdom before you import svelte-fullcalendar and other fullcalendar plugins. Like this: 
> 
> `import '@fullcalendar/core/vdom';`
> 
> `import FullCalendar from 'svelte-fullcalendar';`
> 
> `import daygridPlugin from '@fullcalendar/daygrid';`
> 
> 
> 
> I am using this version (^2.0.0-beta.0) of svelte-fullcalendar along with **vite-4.0.1**

I tried this and still running into the vdom issue as well...
