### ISSUE TITLE
Unknown word when creating a "<style>x</style>" element to inline through @html

### ISSUE THREAD

**Issue by pepicrft** [sveltejs/kit#3128]
### Describe the bug

I'm trying to add [Typography.js](https://kyleamathews.github.io/typography.js/) to a SvelteKit project by using the `@html` directive and including a `<style>..</style>` element inside `<svelte:head>...</svelte:head>`. However, when I create the HTML string, SvelteKit yields a `Unknown word` error that's very hard to debug because I have no idea where the error comes from. I tried passing `--verbose` to see if I could obtain additional logs but it didn't help.

### Reproduction

In a SvelteKit project, add the following to a `__layout.svelte` layout:

```svelte
<script>
	import Typography from 'typography';
	import funstonTheme from 'typography-theme-funston';
	const typography = new Typography(funstonTheme);
	const styleElement = `<style>${typography.toString()}</style>`
</script>

<svelte:head>
	<title>tweet2toot - Toots and Tweets in sync</title>
	{@html styleElement}
</svelte:head>

<slot />
```
SvelteKit will yield the following error: `Unknown word`

### Logs

```shell
[vite-plugin-svelte]  /test/project/src/routes/__layout.svelte:1:3: Unknown word
file: /test/project/src/routes/__layout.svelte
>  /test/project/src/routes/__layout.svelte:1:3: Unknown word
 ELIFECYCLE  Command failed with exit code 1.
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 35.51 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 96.1.32.115
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.5 
    @sveltejs/adapter-netlify: next => 1.0.0-next.36 
    @sveltejs/kit: next => 1.0.0-next.206 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
You need to escape the `<style>` string. See, for example, #3080.
