### ISSUE TITLE
Disabling prerendering breaks runtime on 1.0.0-next.208 using latest adapter-node

### ISSUE THREAD

**Issue by pheuter** [sveltejs/kit#3141]
### Describe the bug

Setting `prerender: { enabled: false }` in svelte.config.js causes `svelte-kit build` to no longer generate a `build/prerendered` directory, which throws this error during runtime:

```
Error: ENOENT: no such file or directory, scandir 'apps/v2/build/prerendered'
@careswitch/v2-app:preview:     at readdirSync (node:fs:1392:3)
@careswitch/v2-app:preview:     at list (file://apps/v2/build/handler-2aa2c439.js:57:12)
```

### Reproduction

Any Svelte Kit app on 1.0.0-next.208 with `@sveltejs/adapter-node: 1.0.0-next.57` and `prerender: { enabled: false },` set in svelte.config.js.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.05 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v17.3.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.57 => 1.0.0-next.57 
    @sveltejs/kit: 1.0.0-next.208 => 1.0.0-next.208 
    svelte: 3.44.3 => 3.44.3 
```

### Severity

serious, but I can work around it

### Additional Information

The workaround I'm currently doing is a manual `mkdir -p build/prerendered` after `sveltekit build`.

**Comment by benmccann** [comment]
https://github.com/sveltejs/kit/blob/6221e6a5758cd1e6cc0f99ccd2ae0e260b97ce3b/packages/adapter-node/src/middlewares.js#L23

changed to

https://github.com/sveltejs/kit/blob/a1e980fad27d9c8cd5b32aa183eb96e39f438ec2/packages/adapter-node/src/handler.js#L33
