### ISSUE TITLE
404 Error when deploying to Vercel

### ISSUE THREAD

**Issue by HeritagePalms** [sveltejs/kit#3142]
### Describe the bug

With the new API changes that were done ([https://github.com/sveltejs/kit/pull/3133](https://github.com/sveltejs/kit/pull/3133)), the new output folder is '.output' instead of '.vercel_build_output' and Vercel doesn't seem to know what to do with that.

I have the preset set to Sveltekit and had to do a manual override on the output folder to '.vercel_build_output' for it to work. Now, I followed the Vercel guide for the file system api ([https://vercel.com/docs/file-system-api](https://vercel.com/docs/file-system-api)), and my deployments just go to a 404 page. I also added the manual output override to '.output' but the deployments fail if I do that.

I understand that this might be a Vercel thing instead of SvelteKit. If so, then let me know and I will head over there.

Thanks.

### Reproduction

I don't have a public repo available, sorry.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 100.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    npm: 7.17.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: 96.0.1054.62
    Firefox Developer Edition: 96.0
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.33 
    @sveltejs/kit: ^1.0.0-next.114 => 1.0.0-next.208 
    svelte: ^3.34.0 => 3.44.3
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
same issue as #3143, closing (even though this was first :)

**Comment by Rich-Harris** [comment]
actually this might not be a dupe, reopening

**Comment by HeritagePalms** [comment]
I don't know if this helps but overriding the output folder in Vercel deployment settings allows the build to complete but the root folder structure in Vercel is just a 'server' and 'static' folder & 'routes-manifest.json' file.

**Comment by Rich-Harris** [comment]
Can you try with `@sveltejs/adapter-vercel@1.0.0-next.34`?

**Comment by HeritagePalms** [comment]
@sveltejs/adapter-vercel@1.0.0-next.34

This indeed solve my problem. Thanks!

**Comment by hemanthvalsaraj** [comment]
This ain't working for me either. Am I missing something here?

**package.js**
`{
    "name": "demo",
    "version": "0.0.1",
    "scripts": {
        "dev": "svelte-kit dev",
        "build": "svelte-kit build",
        "package": "svelte-kit package",
        "preview": "svelte-kit preview",
        "lint": "prettier --ignore-path .gitignore --check --plugin-search-dir=. .",
        "format": "prettier --ignore-path .gitignore --write --plugin-search-dir=. ."
    },
    "devDependencies": {
        "@sveltejs/adapter-vercel": "next",
        "@sveltejs/kit": "next",
        "autoprefixer": "^10.4.0",
        "prettier": "^2.4.1",
        "prettier-plugin-svelte": "^2.4.0",
        "svelte": "^3.44.0",
        "svelte-preprocess": "^4.10.1",
        "tailwindcss": "^3.0.7"
    },
    "type": "module",
    "dependencies": {
        "@fontsource/fira-mono": "^4.5.0",
        "@lukeed/uuid": "^2.0.0",
        "cookie": "^0.4.1",
        "cookie-universal": "^2.1.5",
        "svelte-loading-spinners": "^0.1.7"
    }
}`

**Error Log on Vercel**
`
> Using @sveltejs/adapter-vercel
> Cannot read property 'location' of undefined
    at get_single_valued_header (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/url.js:8:23)
    at visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:436:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
`
