### ISSUE TITLE
@sveltejs/adapter-vercel build error

### ISSUE THREAD

**Issue by xxtereshko** [sveltejs/kit#3153]
### Describe the bug

<img width="868" alt="Screenshot 2021-12-30 at 23 41 56" src="https://user-images.githubusercontent.com/19520678/147789907-3e31dc71-bc44-41fb-bd1b-62679a564d01.png">

the same on vercel

<img width="1110" alt="Screenshot 2021-12-30 at 23 43 50" src="https://user-images.githubusercontent.com/19520678/147789939-e28e8f3c-3ddc-4086-a808-28c16777cb4d.png">

### Reproduction

Error while building. (npm run build)

### Logs

```
> Using @sveltejs/adapter-vercel
> builder.getBuildDirectory is not a function
TypeError: builder.getBuildDirectory is not a function
    at adapt (file:///Users/xxtereshko/dev/tereshkonet/node_modules/@sveltejs/adapter-vercel/index.js:14:24)
    at adapt (file:///Users/xxtereshko/dev/tereshkonet/node_modules/@sveltejs/kit/dist/chunks/index4.js:485:8)
    at file:///Users/xxtereshko/dev/tereshkonet/node_modules/@sveltejs/kit/dist/cli.js:910:11
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.26 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/Cellar/node@16/16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/Cellar/node@16/16.13.1/bin/npm
    Watchman: 2021.12.20.00 - /usr/local/bin/watchman
  Browsers:
    Firefox Developer Edition: 96.0
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.206 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
You're using a more current `adapter-vercel` than `kit`. try `npm install @sveltejs/kit@next`

**Comment by xxtereshko** [comment]
> You're using a more current `adapter-vercel` than `kit`. try `npm install @sveltejs/kit@next`

Thanks. The problem was in lock file. 😉
