### ISSUE TITLE
From `1.0.0-next.211` errors and pages reloads

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#3158]
### Describe the bug

From `1.0.0-next.211` on each navigation click there are errors in the console and automatic reload of the page and then that page works and the same happens for subsequent pages.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
```

### Severity

blocking all usage of SvelteKit

**Comment by HeritagePalms** [comment]
I know I was getting "New Dependencies Found" and then I get a reload while on 'Dev' but after visiting the various locations on the website this goes away. After a build and npm run preview, I don't get those messages. I don't consider those errors so, what error messages are you getting?

**Comment by frederikhors** [comment]
@HeritagePalms if I restart the dev server it's all the same again.

**Comment by HeritagePalms** [comment]
> @HeritagePalms if I restart the dev server it's all the same again.

Is it only in dev? How about preview after a build?

**Comment by frederikhors** [comment]
Dev only.

**Comment by frederikhors** [comment]
Dev only. Or better, I don' event tried to publish or build. I reverted to 210.

**Comment by HeritagePalms** [comment]
211 patch notes state: "Use Vite's filewatcher in dev mode instead of creating a new one". What errors were you getting though?

**Comment by kevinrenskers** [comment]
Same here. The initial page load doesn't work at all, it shows as an error 500 for me. When I native to another link and back to that first page, it all works.. until I reload the page.

**Comment by bluwy** [comment]
Please provide a reproduction.
