### ISSUE TITLE
Getting error 404 for `/service-worker.js` since 1.0.0-next.207

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#3159]
### Describe the bug

When I updated from 203 to 210 I noticed that I was getting the following errors:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (service-worker.js, line 0)
[Error] Unhandled Promise Rejection: TypeError: Script http://localhost:3000/service-worker.js load failed
```

This happens with `npm run preview` and on the actual production site, so I've downgraded back to 206 for now.

### Reproduction

https://github.com/kevinrenskers/sw-repro

Basically it's just the standard demo app, with adapter-node. Run `npm run build` and `npm run preview`, open the website, and look at the console.

### Logs

```shell
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (service-worker.js, line 0)
[Error] Unhandled Promise Rejection: TypeError: Script http://localhost:3000/service-worker.js load failed
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.07 GB / 32.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    npm: 8.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Edge: 96.0.1054.62
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.58
    @sveltejs/kit: next => 1.0.0-next.211
    svelte: ^3.34.0 => 3.44.3
```

### Severity

blocking an upgrade

**Comment by asmajlovicmars** [comment]
As mentioned in Discord, I started getting the same error related to service-worker.js not existing, immediately after upgrading to SvelteKit v1.0.0-next.211:

`
...
TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/%27) with script ('http://localhost:3000/service-worker.js%27): A bad HTTP response code (404) was received when fetching the script.
`

Seems, my error was related to aws-amplify. 

Prior to upgrade, calling Amplify.configure worked fine on the server side, but after the upgrade I had to change the call to Amplify.default.configure, and all seems to be working fine again. 

Not sure if this is of any help to your case, but leaving it here. 

`
routes/api/xyz.js:

import Amplify, { graphqlOperation, withSSRContext } from 'aws-amplify';
import { awsmobile } from '$lib/utils/awsmobile';

export async function post(req) {
  // changed Amplify.configure (which worked properly before), to Amplify.default.configure, and it seems to be good now:
  Amplify.default.configure({ ...awsmobile, ssr: true });
...

caller-fn.svelte:
    ...
    const res = await fetch('/api/xyz', {
      method: 'POST',
      body: JSON.stringify({ ...}),
     })
`

**Comment by angrytongan** [comment]
Workaround: `rm -rf build .sveltekit && touch src/service-worker.js && npm run build && npm run preview`

**Comment by yuanchuan** [comment]
Try to update `svelte.config.js`

```js
kit: {
  /* ... */

  serviceWorker: {
    register: false,
  }

}
```

**Comment by kevinrenskers** [comment]
That doesn't seem to help, I get the same errors in the console when I preview the built app.

**Comment by smithliam** [comment]
@Rich-Harris 
Why do we need to do this all the time!😐

**Comment by smithliam** [comment]
> Try to update `svelte.config.js`
> 
> ```js
> kit: {
>   /* ... */
> 
>   serviceWorker: {
>     register: false,
>   }
> 
> }
> ```

Doesn't work

**Comment by smithliam** [comment]
I see, the error that I'm getting is deferent than this one, and this issue created at 2021, not 2022 :)

This is my error message:
```
Not found: /service-worker.js
Error: Not found: /service-worker.js
    at resolve (file:///C:/Users/babak/Desktop/nostroid/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.511_svelte@3.50.1+vite@3.1.7/node_modules/@sveltejs/kit/src/runtime/server/index.js:260:13)
    at resolve (file:///C:/Users/babak/Desktop/nostroid/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.511_svelte@3.50.1+vite@3.1.7/node_modules/@sveltejs/kit/src/runtime/server/index.js:291:5)
    at Object.handle (file:///C:/Users/babak/Desktop/nostroid/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.511_svelte@3.50.1+vite@3.1.7/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:336:66)  
    at respond (file:///C:/Users/babak/Desktop/nostroid/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.511_svelte@3.50.1+vite@3.1.7/node_modules/@sveltejs/kit/src/runtime/server/index.js:288:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/babak/Desktop/nostroid/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.511_svelte@3.50.1+vite@3.1.7/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

**Comment by oneezy** [comment]
@smithliam i'm getting the same error on this end. anyone @here have some ideas?

**Comment by sourcegr** [comment]
@smithliam @oneezy 

go to `chrome://serviceworker-internals/`

and click `unregister` at the service worker that is bound to the port you are running node (mine was 3000)

**Comment by Todaricli** [comment]
Do you guys know why this happened? I fix it by using @sourcegr 's solution, but would like to know the cause.
