### ISSUE TITLE
Credentialed fetch server side still not working?

### ISSUE THREAD

**Issue by tohodakilla** [sveltejs/kit#3160]
### Describe the bug

According to documentation for load fetch function:
"Cookies will only be passed through if the target host is the same as the SvelteKit application or a more specific subdomain of it." 

load function:
```
    export async function load({ fetch, session }) {
        const { apiURL } = session // apiURL = 'http://api.app.drasha.tld'

        try {
            const req = await fetch(`${apiURL}/products`, { credentials: 'include' })
            const res = await req.json()
            
            return { props: res }
         } catch(error) { return { status: 500, error }}
     })
```

host that svelteKit is served: _app.drasha.tld_
api server from: _api.app.drasha.tld_ - which i understand is a more specific subdomain of svelteKit application host
cookie is httpOnly and its domain is: .app.drasha.tld

both api and app are behind simplest nginx proxy (config below):
```
server {
    listen 80;
    server_name api.app.drasha.tld;

    location / {
            proxy_pass http://localhost:6969;
            proxy_http_version 1.1;
    }
}

server {
    listen 80;
    server_name app.drasha.tld;

    location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
    }
}
```

svelte.config.js
```js
export default {
    kit: {
        adapter: adapter({
            out: 'build',
            precompress: false,
            env: {
                host: 'HOST',
                port: 'PORT'
            }
        }),
        target: '#svelte',
        vite: {
            plugins: [ initSession, loadUserFromSession ]
        }
    }
}
```

no externalFetch inside hooks.js

load function client side passes cookie correctly, when i refresh page it doesnt.
the only way to fix this i found is to create a /api/[...routes].js proxy within svelteKit

my understanding is that this is supposed to be fixed, yet cookies are not passed server side, what am i missing?

### Reproduction

https://stackblitz.com/edit/sveltekit-msbv6h

### System Info

```shell
System:
    OS: Linux 5.15 Artix Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 347.30 MB / 15.48 GB
    Container: Yes
    Shell: 5.1.12 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    npm: 8.3.0 - /usr/bin/npm
  Browsers:
    Chromium: 96.0.4664.110
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.58 => 1.0.0-next.58 
    @sveltejs/kit: next => 1.0.0-next.209 
    svelte: ^3.44.0 => 3.44.3
```

### Severity

serious, but I can work around it

### Additional Information

I am aware those isses were heavili discusses, mine is of same nauture.

session authentication using a HttpOnly cookie isues for .domain.tld api living at api.domain.tld and app living at app.domain.tld
whole authentication method relies on server providing HttpOnly cookie which i could read and verify inside hooks.js and then its passed back to API with all the calls, so server api verify it as well, both sharing same secret, removing need for any auth tokens and a lot of attack vectors.

I am positing here, because after several attempts in vain at discord chat.

**Comment by Rich-Harris** [comment]
The repro is unusable — for starters the config file is invalid. We can't investigate issues with broken repros!

That said, it _sounds_ like what you need to do is forward the `cookie` header from the request in `externalFetch`. Cookies aren't attached when you call `fetch` on the server, because there's no way to know _whose_ cookies to send.
