### ISSUE TITLE
[adapter-vercel] Can't visit dynamic routes due to page/o being undefined (and a bonus of builds sometimes failing)

### ISSUE THREAD

**Issue by murl-digital** [sveltejs/kit#3167]
### Describe the bug

When using the latest version of SvelteKit and the Vercel adapter, pages with dynamic routes (e.g example.com/blog/[post] return an error. The message varies between page is undefined and o is undefined. Builds also fail inconsistency with the error of `rimraf is undefined`. I'm unsure if this issue is just affecting me and my setup or is just a problem in general.

### Reproduction

[Here's](https://github.com/murl-digital/draconium.productions/tree/sv-kit) the repo I'm using, simply clone and deploy to a fresh vercel project. You may also need to set the `DRC_SANITY_PRJ_ID` and `DRC_SANITY_DATASET` environment variables. Then, if you navigate to a page such as ``rls/test``, You should observe that the error it gives you is either page or o is undefined, whereas if the page is working you'll probably get an error complaining about your sanity client.

### Logs

```shell
Build Logs:
TypeError: Cannot read property 'rimraf' of undefined
    at adapt (file:///vercel/path0/node_modules/@sveltejs/adapter-vercel/index.js:17:10)
    at adapt (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:623:8)
    at file:///vercel/path0/node_modules/@sveltejs/kit/dist/cli.js:948:11

Error:
500

o is undefined

ze@https://draconium-productions-murl-digital.vercel.app/_app/pages/rls/_slug_.svelte-1f6f7184.js:1:12591
_load_node@https://draconium-productions-murl-digital.vercel.app/_app/start-c1e17c54.js:1:18350
_load@https://draconium-productions-murl-digital.vercel.app/_app/start-c1e17c54.js:1:19128


500

Cannot read property 'params' of undefined

TypeError: Cannot read property 'params' of undefined
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 34.31 GB / 63.92 GB
  Binaries:
    Node: 17.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0)
    Internet Explorer: 11.0.22000.120
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
Did you take care of the breaking changes made in version next.208? The `{page, ...}` in the load function has been split into `{url, params, ...}`.

If you have and the issue still persists, provide a more minimal reproduction so that the maintainers don't have to go through the hassle of setting env vars.

**Comment by bluwy** [comment]
As mentioned by @gtm-nayan, there was a breaking change for `page` which likely explains the `Cannot read property 'params' of undefined` error. For the other errors, it should be resolved with the latest version of SvelteKit and the vercel adapter. You've mentioned that you've upgraded them to latest, but might want to double check that again.

**Comment by murl-digital** [comment]
@gtm-nayan was entirely correct, replacing `page` with `params` in my load function fixed the issue, my bad! Also regarding @bluwy's comment, yes you're correct. The code on that repo is slightly out of date and I'm using the latest version locally.
