### ISSUE TITLE
Package export component + SSR function from index.js

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#3172]
### Describe the bug

I have a package that exports both a Svelte component as well as a function to be run at build time in `svelte.config.js`:

```js
// my-package/index.js
export { someSSRFunction } from './main'
export { default } from './SomeComponent.svelte'
```

### Reproduction

In my app's component tree, I import the component

```svelte
// App.svelte
import SomeComponent from 'my-package'
```

and in `svelte.config.js`, I import the function

```js
import { someSSRFunction } from 'my-package'

if (NODE_ENV === `production`) {
  someSSRFunction()
}
```

### Logs

Trying to run the app, I then get the error

```sh
$ svelte-kit dev
Unknown file extension ".svelte" for node_modules/my-package/SomeComponent.svelte
```
cause of course `node` executing `svelte.config.js` doesn't know how to handle Svelte files. What's the recommended approach here besides nested imports like

```js
import { someSSRFunction } from 'my-package/some-ssr-function'
```

I would like to import everything from `my-package/index.js`.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 113.31 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
    @sveltejs/kit: ^1.0.0-next.201 => 1.0.0-next.201 
    svelte: ^3.44.2 => 3.44.2 
    vite: ^2.7.1 => 2.7.1
```

### Severity

annoyance

**Comment by sea-grass** [comment]
You'd be able to fix this by providing different exports from your package by specifying them in your package.json, similar to how the Svelte repo structures [its exports](https://github.com/sveltejs/svelte/blob/master/package.json#L22-L80). Then again, you already said this is not the solution you want.

**Comment by bluwy** [comment]
The only solution if you want to stick with importing everything from `index.js`, is to utilize [Nodejs loader hooks](https://nodejs.org/dist/latest/docs/api/esm.html#loaders) to handle Svelte files. This is experimental though and you have to specify it through `node --loader your-loader`, which isn't very nice IMO.

But that aside, I think the better and correct way is to use `exports` as mentioned, and export the specific code that runs in `svelte.config.js` separately. Not needing to load Svelte files is also a perf improvement.

**Comment by janosh** [comment]
> I think the better and correct way is to use `exports` as mentioned

@bluwy Thanks. That's what I'm doing atm so I guess I'll stick to it.
