### ISSUE TITLE
CF Adapter breaks URL.searchParams

### ISSUE THREAD

**Issue by cheesycod** [sveltejs/kit#3173]
### Describe the bug

Method searchParams called on incompatible receiver [object Object]
TypeError: Method searchParams called on incompatible receiver [object Object]

### Reproduction

```<script context="module" lang="ts">
	import { fetchFates } from "$lib/request"
	export const prerender = false;
	/** @type {import('@sveltejs/kit@next').Load} */
	export async function load({ url }) {
		//console.log("url is:", url)
		let tag = url.searchParams.get("tag")
		let targetType = url.searchParams.get("target_type")
        console.log(tag)
		const searchUrl = `/api/v2/search/tags?target_type=${targetType}&tag=${tag}`;
		const res = await fetchFates(searchUrl);

		if (res.ok) {
            let data = await res.json()
			return {
				props: {
					data: data,
                    targetType: targetType,
                    tag: tag
				}
			};
		}

		return {
			status: res.status,
			error: new Error(`Tag Search Error`)
		};
	}
</script>
<script lang="ts">
    import CardContainer from "$lib/cards/CardContainer.svelte"
    import BotCard from "$lib/cards/BotCard.svelte"
    import SearchBar from "$lib/base/SearchBar.svelte"
    import Tag from "$lib/base/Tag.svelte";
import { session } from "$app/stores";
    export let data: any;
    export let targetType: string;
</script>
<section>
	<h1>Fates List</h1>
	<h2 class="best-bots">Find the best bots for your servers!</h2>
</section>
<SearchBar type={targetType} query=""></SearchBar>
<Tag targetType={targetType} tags={data.tags_fixed}></Tag>
<CardContainer>
	{#each data.search_res as bot}
		<BotCard data={bot} type={targetType} rand={false}/>
	{/each}
</CardContainer>

<style>
	h1 {
		font-size: 50px;
		margin: 0px;
	}

	h2 {
		font-size: 40px;
		margin: 0px;
	}

	.best-bots {
		opacity: 0.6;
	}
	section {
		display: flex;
		flex-direction: column;
		justify-content: center;
		align-items: center;
		flex: 1;
		overflow: hidden;
	}
</style>
```

This code will give:

Method searchParams called on incompatible receiver [object Object]
TypeError: Method searchParams called on incompatible receiver [object Object]

### Logs

```shell
No logs are reported
```

### System Info

```shell
System:
    OS: Linux 5.15 Fedora Linux 35 (Cloud Edition)
    CPU: (2) x64 DO-Regular
    Memory: 688.41 MB / 3.82 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    npm: 8.1.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.7 
    @sveltejs/adapter-cloudflare: ^1.0.0-next.4 => 1.0.0-next.5 
    @sveltejs/adapter-node: ^1.0.0-next.57 => 1.0.0-next.58 
    @sveltejs/kit: next => 1.0.0-next.212 
    svelte: ^3.44.0 => 3.44.3 

issue itself is with cf pages
```

### Severity

blocking all usage of SvelteKit

**Comment by jahir9991** [comment]
same problem

**Comment by cheesycod** [comment]
I found a workaround for this:

In hooks, create a getSession, and then set all the stuff you need from url in session, then use the session in load:

```export function getSession(request) {
console.log("getSession called")

// Bypass dumb cloudflare bug
let query = {}
request.url.searchParams.forEach((v, k) => {
query[k] = v
})

return {
"url": request.url.toJSON(), // CF adpter workaround, hopefully works?
"query": query
}
}```

**Comment by jahir9991** [comment]
> I found a workaround for this:
> 
> In hooks, create a getSession, and then set all the stuff you need from url in session, then use the session in load:
> 
> ```
> export function getSession(request) {
>     console.log("getSession called")
> 
>    // Bypass dumb cloudflare bug
>    let query = {}
>    request.url.searchParams.forEach((v, k) => {
>         query[k] = v
>    })
> 
>    return {
>       "url": request.url.toJSON(), // CF adpter workaround, hopefully works?
>      "query": query
>    }
> }
> ```

it make some more complexity on another change in frontend

**Comment by jahir9991** [comment]
any update?

**Comment by Giggiux** [comment]
+1 on this. 
In my experience the site is breaking when loading from "direct access" to the page using searchParams, so when doing server side rendering, but if you load a page that doesn't use searchParams and then use a link with prefetch, using client side hydration, it works flawlessly. 

This bug is absolutely non spottable/reproducible neither in `dev` command or `build`+ `preview`, plus I personally didn't find any logs on Cloudflare Pages.

**Comment by cheesycod** [comment]
I think this issue actually has to do with binding of url. The url object itself is sent but doesn’t appear to be properly bound.

**Comment by b3ngg** [comment]
Same with accessing pathname on the url object. Cloudflare shows a 500 with: `Method pathname called on incompatible receiver [object Object]`. 

Using hooks works, but this still really sucks.

**Comment by MDALIMULALRAZY** [comment]
any update?

**Comment by stephane** [comment]
Another workaround a bit less intrusive:

In hooks, handle():

```js
request.locals.fixedUrl = request.url.toJSON();
```

In hooks, getSession():
```js
return {
    fixedUrl: locals.fixedUrl
};
```

In the `load` functions:

```js
export async function load({ session }) {
    const url = new URL(session.fixedUrl);
}
```

**Comment by b3ngg** [comment]
With the latest version of `adapter-auto` and `kit` it works for me now! Thanks!

**Comment by Giggiux** [comment]
It now works for me on SvelteKit version `1.0.0-next.241` and adapter-cloudflare version `1.0.0-next.8`.

Thanks a lot!

**Comment by cheesycod** [comment]
One second, let me test
