### ISSUE TITLE
Request: Add ability to set a charset on the Content-Type MIME type

### ISSUE THREAD

**Issue by johnnysprinkles** [sveltejs/kit#3184]
### Describe the problem

I think browsers still default to Latin-1, while nearly everybody wants to use utf-8. Out of the box SvelteKit includes `<meta charset="utf-8" />` in the app.html but that has a couple issues:

1. It's just sort of hacky, to tell the parser how to parse while it's parsing.
2. There is a pitfall I ran into where if you re-arrange things so that meta tags is below the `%svelte.head%`, it might not be in the first 1024 bytes of the response, which causes Firefox at least to reload the page on each request, making for a double fetch.

Much better to put it in the HTTP response headers.

That line of code is here:
https://github.com/sveltejs/kit/blob/b0fa96b756d810127391d4b376c2d0aad4a0e1c8/packages/kit/src/runtime/server/page/render.js#L205

What do you think about an option in svelte.config.js to set this? Happy to submit a PR.

### Describe the proposed solution

See above.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Wanting an HTTP header instead of the meta tag feels niche to me. You should already be able to alter the header in the `handle` hook.

**Comment by johnnysprinkles** [comment]
That works, doing this conditionally on responses that are HTML looks like this, for reference.

// hooks.js

```javascript
export async function handle({ request, resolve }) {
  let response = await resolve(request)
  if (response.headers['content-type'] == 'text/html') {
    return {
      ...response,
      headers: {
        ...response.headers,
        'Content-Type': 'text/html; charset=utf-8'
      },
    }
  } else {
    return response
  }
}
```

**Comment by johnnysprinkles** [comment]
Side note: I recently started not using semicolons and I'm never going back. I think it makes sense for the same reason always using trailing commas makes sense -- you can duplicate lines and not worry about the last line being different.

**Comment by johnnysprinkles** [comment]
This quite a bit nicer now with #3384 merged, now it's dealing with UrlSearchParam objects:

```
export async function handle({ resolve, event }) {
  let response = await resolve(event)

  if (response.headers.get('content-type') == 'text/html') {
    response.headers.set('content-type', 'text/html; charset=utf-8')
  }

  return response
}
```

**Comment by rohanrajpal** [comment]
> This got quite a bit nicer now with #3384 merged, now it's dealing with UrlSearchParam objects:
> 
> ```js
> export async function handle({ resolve, event }) {
>   let response = await resolve(event)
> 
>   if (response.headers.get('content-type') == 'text/html') {
>     response.headers.set('content-type', 'text/html; charset=utf-8')
>   }
> 
>   return response
> }
> ```

You're a lifesaver, thanks a ton!

**Comment by Rican7** [comment]
👋 Here in 2025, I tried to use [this workaround](https://github.com/sveltejs/kit/issues/3184#issuecomment-1019024692), but it caused issues at build time during the prerender step. Issue filed here: https://github.com/sveltejs/kit/issues/13612

It can be worked around by adding a conditional to check for `building` state:

```javascript
import { building } from '$app/environment';

export const handle = async ({ event, resolve }) => {
	const response = await resolve(event);

	// TODO: Remove `building` conditional... It's currently needed for some
	// reason, as prerendering breaks otherwise...
	//
	// See https://github.com/sveltejs/kit/issues/13612
	if (!building && response.headers.get('content-type') == 'text/html') {
		response.headers.set('content-type', 'text/html; charset=utf-8');
	}

	return response;
};
```

**Comment by VityaSchel** [comment]
Keep in mind this won't work for static resources.

> Requests for static assets — which includes pages that were already prerendered — are not handled by SvelteKit.

Source: https://svelte.dev/docs/kit/hooks#Server-hooks-handle
