### ISSUE TITLE
Anchor tag attribute to disable client side routing

### ISSUE THREAD

**Issue by qdozaq** [sveltejs/kit#3188]
### Describe the problem

There doesn't seem to be a concise way of disabling the client side route navigation for just a single link.
The [current method](https://kit.svelte.dev/docs#ssr-and-javascript-router) affects **all** navigations from the specific page.

One use case this is needed for is if hosting several different apps under the same domain. (Like hosting multiple apps in a [vercel monorepo](https://vercel.com/blog/monorepos) for example)

If I want to host a separately built app on say `/blog` then I need to disable client side navigation when navigating to `/blog` other wise svelte kit will try to look for it locally and get a 404

### Describe the proposed solution

I would like to see a new anchor tag attribute along the lines of:
`sveltekit:disableRouter`
`sveltekit:defaultBehavior`
`sveltekit:default`
`sveltekit:refresh`
`sveltekit:reload`
ect...

Which would disable the client side navigation for that one link.

I believe this should be fairly straight forward and can take on the work if this is something you think should be pursued.
Required change would involve also returning at [this line](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/router.js#L126) if the `sveltkit:<chosen_name>` attribute is present
and updating the types in the language server.

### Alternatives considered

This problem can currently be worked around by doing the following:

```html
  <a
      href="/blog"
      on:click={(e) => {
          e.preventDefault();
          window.location.href = '/dashboard';
  }}>Blog</a>
```

which isn't _terrible_ or that tedious, but it's not very obvious and doesn't feel like thats the cleanest this solution could be.

### Importance

nice to have

**Comment by babichjacob** [comment]
If you give the link [the `rel="external"` attribute](https://kit.svelte.dev/docs#anchor-options-rel-external), it will be navigated to using the browser (i.e. SSRed) rather than using the client side router.

An example with the link you gave:

```svelte
  <a
      href="/blog"
      rel="external"
  }}>Blog</a>
  ```
  
(assuming that the `window.location.href = '/dashboard';` was a mistranscription and it was supposed to be `/blog` rather than `/dashboard`)

**Comment by qdozaq** [comment]
@babichjacob 🤦 
thank you!
that appears to be exactly what I needed
