### ISSUE TITLE
Packaging feature, unwanted dependencies in `package.json` and more

### ISSUE THREAD

**Issue by BlueFirePro** [sveltejs/kit#3204]
### Describe the bug

Hi
I didn't know that this packaging feature is experimental, I just jumped into it😂. Let me start from the beginning to explain what is needed and etc.

I have a very simple and small package. It's a 1 `.svelte` file, a Svelte component. It doesn't need any dependencies. [This is the package](https://github.com/babakfp/svelte-outclick).

My first issue was that I needed to create an `index.js` file. I thought that I can just link to the component file from alias config in `svelte.config.js` or from `jsconfig.json`. In the community, I find out that someone had the same issue and someone else said that she need an `index.js` file to export the component as default... I was able to fix it.

After doing some changes to my package, I realized that all of my `package.json` dependencies are added to the package's `package.json` file too!. My package doesn't even need a single dependency.

What if I want to have a separate LICENSE or README or... for the package and the demo? There is nothing to do that.

---

Wasn't it better to just add an absolute path to the dependency value in `package.json` without creating something that does something and doesn't do so much stuff?

```json
"devDependencies" : {
  "my-package": "C/some-folder/package-folder"
}
```

What if someone has a CSS file that can't be placed in the `lib` folder? Like [this](https://github.com/sveltejs/kit/issues/3109).

[This description](https://kit.svelte.dev/docs#packaging-caveats) must be placed at the start, so everyone before starting to use the Kit packaging feature know about all the negative things about it.

That's all❤️

### Reproduction

_

### System Info

```shell
_
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
From what I understand, you want to 
- place the caveat description at the top -> I'm against this
- get better docs around the `package.json` contents. I'll create a PR where the dependencies/devDependencies thing is explained
- you want more flexibility ("what if..") but there's no compelling reasons given why. Many of SvelteKit's features are opinionated, which is great to prevent decision fatigue and provide a consistent developer experience, but it also means it may not suit all needs.

From the the three things only one is actionable, so I'll close this issue through that docs PR.

Please open one issue per feature request or bug report in the future. It's hard for us to track issues when there are multiple in one.

**Comment by BlueFirePro** [comment]
Can I create a post in Discussions to talk about this feature? And I'll also check out the current issues related to this feature and talk about them too...
