### ISSUE TITLE
SvelteKit Global Styles and TailwindCSS Bug

### ISSUE THREAD

**Issue by BlueFirePro** [sveltejs/kit#3216]
### Describe the bug

Hi
I'm not sure that this is related to SvelteKit or Svelte or Tailwind. I only test this white SvelteKit.
The problem is in `index.svelte` global `border-2` style. The first box border colors must be `emerald-500`, not `gray-200`. this `gray-200` added with the `border-2` class.

![Screenshot 2022-01-05 014557](https://user-images.githubusercontent.com/80850817/148196740-f6078997-db0a-48e9-9844-ba42c1019435.png)

### Reproduction

https://github.com/babakfp/sveltekit-tailwind-bug

### System Info

```shell
_
```

### Severity

annoyance

**Comment by TakenHiduk** [comment]
I think you forgot to add your component in the first **COMPONENT**

your code is like so:

```html
// index.svelte
<div class="content">CONTENT</div>

<div>
  <Comp class="my-content">MY CONTENT</Comp>
</div>
```

I simply did this:
```html
// index.svelte

<!-- <Comp/> was missing -->
<div>
  <Comp class="content">MY CONTENT</Comp>
</div>

<div>
  <Comp class="my-content">MY CONTENT</Comp>
</div>
```

## Result
![imagen](https://user-images.githubusercontent.com/47125485/148216558-263f8361-0170-497d-a6fc-f25c44dac538.png)

**Comment by dominikg** [comment]
This is not an issue with sveltekit itself. Please use discord or github discussions for questions.

To find out if something is caused by sveltekit you can try to reproduce the it in a regular vite+svelte project `npm init vite -t svelte`.

**Comment by BlueFirePro** [comment]
> I think you forgot to add your component in the first **COMPONENT**
> 
> your code is like so:
> 
> ```
> // index.svelte
> <div class="content">CONTENT</div>
> 
> <div>
>   <Comp class="my-content">MY CONTENT</Comp>
> </div>
> ```
> 
> I simply did this:
> 
> ```
> // index.svelte
> 
> 
> <div>
>   <Comp class="content">MY CONTENT</Comp>
> </div>
> 
> <div>
>   <Comp class="my-content">MY CONTENT</Comp>
> </div>
> ```
> 
> ## Result
> ![imagen](https://user-images.githubusercontent.com/47125485/148216558-263f8361-0170-497d-a6fc-f25c44dac538.png)
> 
> Also, Happy Code 😁

Thank you, but no, that isn't the reason🤦‍♂️ I'm not blind😐😂
