### ISSUE TITLE
Type error not detected - Typescript

### ISSUE THREAD

**Issue by esoteloferry** [sveltejs/kit#3225]
### Describe the bug

Not sure if this issue corresponds here (or in svelte-preprocess, etc).

Using sveltekit + typescript:

I have a function that returns `number | undefined` . I use it in Svelte,  if I type assigned a variable `let val: number = ...` it does not show any warning about that val should be `number | undefined`. 
The problem for me is that even `npm run build` runs fine which is an issue that nothing really catched the mistype. Also `npx svelte-check` does not throw an error.

Then for experimenting, I replace the return values of function by `number | string` and it actually works fine. Lsp finds the mistype when trying to assign to only number and `npm run build` throws an error. 

Is it something related to `undefined` in Svelte?, I am confused. 

I also tried with the function inside the same Svelte file but it is the same.

### Reproduction

Just start with a new sveltejs project (skeleton type) and enable typescript.
Add a ts file with the function that returns number | undefined and use it in index.svelte

I wrap it here: 
https://github.com/esoteloferry/typed_error_not_detected

@sveltejs/kit : 1.0.0-next.216
typescript: 4.5.4

### Logs

```shell
When doing a mistype in variable assignment , npx svelte-check and npm run build works fine (everything green)
```

### System Info

```shell
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GH
z
    Memory: 34.06 MB / 8.00 GB
    Shell: 5.1.4 - /usr/local/bin/bash
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 13.1.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.9
    @sveltejs/kit: next => 1.0.0-next.216
    svelte: ^3.44.0 => 3.45.0
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
This isn't related to the svelte or svelte kit. You have to enable strict mode or `strictNullChecks` in your tsconfig for the nullable type check to work.

**Comment by Conduitry** [comment]
Yup, this is how TypeScript behaves when strict null checks aren't enabled.

**Comment by esoteloferry** [comment]
Uau, yes, I forgot to check that.  Great , thank you!
