### ISSUE TITLE
external module not found when using static or node adaptor

### ISSUE THREAD

**Issue by ksgolding** [sveltejs/kit#3233]
### Describe the bug

I hit an issue when using sveltekit trying to use either the node or, preferable the static adapter. 
The Vite development environment seem to work fine, as well as the auto adaptor, however, the other adaptors are failing with the following error:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/projects/ksgolding/playground/my-app/node_modules/ol/layer/Tile' imported from /projects/ksgolding/playground/my-app/.svelte-kit/output/server/entries/pages/index.svelte.js
Did you mean to import sgolding/playground/my-app/node_modules/ol/layer/Tile.js? # !!! MIGHT BE NOTHING, BUT NOTE sgolding/ instead of ksgolding !!!
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)

### Reproduction

I did create a repository that recreates the issue:

https://github.com/ksgolding/svelte-kit-MFN

### Logs

```shell
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/projects/ksgolding/playground/my-app/node_modules/ol/layer/Tile' imported from /projects/ksgolding/playground/my-app/.svelte-kit/output/server/entries/pages/index.svelte.js
Did you mean to import sgolding/playground/my-app/node_modules/ol/layer/Tile.js? # !!! MIGHT BE NOTHING, BUT NOTE sgolding/ instead of ksgolding !!!
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
```

### System Info

```shell
node v14.17.0
yarn 1.22.17
Redhat Linux 8
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I set the Severity to high, as using node or, preferably a static deployment are my only options and would prefer to use the sveltekit tooling.

**Comment by Conduitry** [comment]
See #3210. This is a bug in that library.

**Comment by ksgolding** [comment]
WOW, this was helpful!  However, the behavior is confusing .. 
For example
import { Map, View } from 'ol';
works, as this in the index.js file.. but
import {TileLayer} from 'ol/layer'; does not.. despite the inclusion of
export { default as Image } from './layer/Image.js';
export { default as Layer } from './layer/Layer.js';
In the layer.js file.. 
But, your right .. this works
import TileLayer from 'ol/layer/Tile.js';

Not totally obvious when to use one over the other .. :(
