### ISSUE TITLE
Split vite config for Server and Client

### ISSUE THREAD

**Issue by und3fined** [sveltejs/kit#3242]
### Describe the problem

I make a site with Golang server and frontend is Svelte Kit complied. After research, problem with compile script to ES5.

Vite navtive support `@vitejs/plugin-legacy` for legacy browser

But, I don't want to use it on the server

### Describe the proposed solution

My soulution is split vite config with server and client

It here

```
	/** @type {import('vite').UserConfig} */
	const vite_config = config.kit.vite();
```

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
I think the better solution would be to have a plugin which does not compile the server code to legacy JS, only the Frontend. Not sure how that would look like.

**Comment by und3fined** [comment]
> 

It can is a options for Kit. eg `legacy` 
With `legacy` is `Object`, builder will include plugin `@vitejs/plugin-legacy` with option is value of `legacy`

In source of client config (https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/build/build_client.js#L88)

It maybe is:

```
import legacy from '@vitejs/plugin-legacy';

// other config

plugins: [
	svelte({
		extensions: config.extensions,
		emitCss: !config.kit.amp,
		compilerOptions: {
			hydratable: !!config.kit.hydrate
		}
	}),
        config.kit.legacy &&  legacy(config.kit.legacy)
]

// ...

```

**Comment by bluwy** [comment]
Is there a legacy output for the server build when used today? I just checked `@vitejs/plugin-legacy` and it is all guarded with `if (config.build.ssr)` (checks whether is an SSR build), which means it skips SSR build entirely. If the issue indeeds persists, it should be fix upstream instead. Vite plugins are meant to be interoperable in different builds.
