### ISSUE TITLE
process.env["PORT"] builds as process.env["3001"]

### ISSUE THREAD

**Issue by adam-cyclones** [sveltejs/kit#3265]
### Describe the bug

process.env["PORT"] builds as process.env["3001"]

overriding the port here as seen below does not do anything: 
``` js
{
kit: {
		adapter: adapter({
			out: 'build',
			env: {
				host: 'configuregator.dev',
				port: '3001',
			}
		}),
		target: '#svelte'
}
}
```
 I then tried setting a node ENV variable when running my built sveltkit project
 PORT=3001 node index.js
 
 The result is a built output with the lines
 
 ```js
 const port = process.env["3001"] || (!path && '3000');
 ```
 
 which is undefined and the value is the name of the property

### Reproduction

See the steps above

### Logs

```shell
N/A
```

### System Info

```shell
npx: installed 1 in 1.366s

  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.49 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0.2
    Safari: 15.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I cannot specify ports which blocks deployment

**Comment by Conduitry** [comment]
See #2300.

**Comment by adam-cyclones** [comment]
Okay that's an unexpected way of doing things, tripped me up for sure. Nonetheless, how then do you change the port and host name?

**Comment by bluwy** [comment]
See https://github.com/sveltejs/kit/tree/master/packages/adapter-node#env
