### ISSUE TITLE
Seeing dev-friendly, readable JS output

### ISSUE THREAD

**Issue by eden-omb** [sveltejs/kit#3268]
### Describe the problem

Transparency is important. Svelte has readable and informative JS output, seen e.g. in the REPL (`JS output` tab, next the to `Result` tab); however, there's currently no way I'm aware of to read this output when build with SvelteKit. There's an unreabable minimized version you get in `.svelte-kit/output` when using `svelte-kit build`, but the dev version seems to only ever exist on the fly.

### Describe the proposed solution

I'd like a way to read and explore the dev-friendly, compiled JS output as run when using `svelte-kit dev`. I don't understand enough of how `svelte-kit dev` works to know whether the best way of implementing this is just writing it to the FS as part of `svelte-kit dev`, a special flag on `svelte-kit build`, or whatever else.

In any case, this is a significant step down in transparency and clarity of what's happening under the hood from plain Svelte.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
SvelteKit components are just regular Svelte components, so you can
- past them into the Repl and look at the output (doesn't always work if you have more components set up)
- use the "show compiled code" command from the vs code extension

I'm not sure if this is something that SvelteKit can/should offer.

**Comment by benmccann** [comment]
Are you familiar with how to view them in Chrome? I'm not sure what the benefit is of viewing them on the filesystem instead of in the browser

**Comment by eden-omb** [comment]
@dummdidumm This works on a per-component basis, but even then completely misses out on e.g. routing stuff and `<script context=module>`. However,
@benmccann This completely skipped my mind and (of course) works perfectly and contains everything. Thanks a bunch!
