### ISSUE TITLE
Ability to override load or use before/after hooks

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#327]
One of the most common requests in Sapper is a way to alter `fetch` or otherwise affect the `load` calls

**Is your feature request related to a problem? Please describe.**

* Distributed tracing - add a header to every request to trace requests from frontend all the way to datastore (requested by @adamb on Discord. difficulty setting up honeycomb.io also mentioned in https://github.com/sveltejs/sapper/issues/751)
* Using an internal hostname on the server-side (that's what I want this for. my api server is written in another language)
* Using `fetch` in setup - e.g. to setup Apollo client (https://github.com/sveltejs/sapper/issues/1243 https://github.com/sveltejs/sapper/issues/751)
* Specifying a base URL (https://github.com/sveltejs/sapper/issues/489)
* Using a UNIX socket for AWS Lambda (https://github.com/sveltejs/sapper/issues/356)
* Ability to wrap `fetch` (https://github.com/sveltejs/sapper/issues/908)
* It currently requests only over HTTP. A user on Discord reported this wouldn't work with his server than listens only on port 443
* Accessing Polka request on server (https://github.com/sveltejs/sapper/issues/1436)

**Describe the solution you'd like**

I originally sent https://github.com/sveltejs/sapper/pull/1336 though it might not solve all requests. E.g. there was a request to time how long `load` takes and I don't think my solution would have made that easy to do, so it should probably be updated a bit to account for that.

**How important is this feature to you?**

This enables a large number of use cases for advanced users, so is fairly important.

**Comment by benmccann** [comment]
Reopening this as @ajbouh is reporting a gap in the APIs:

You can't wrap `fetch` (or otherwise augment the preload state) without SvelteKit platform support because (on the server-side) the information you need to use while wrapping is hidden in the *request headers*. 

So the minimum needed to "get around this" is to have in the same place:
- access to request headers and
- access to the values passed to load/prefetch

**Comment by Rich-Harris** [comment]
The request headers are available in setup. Is that insufficient?

**Comment by benmccann** [comment]
@ajbouh I'll leave that question to you (just FYI, if we don't hear anything after awhile we'll probably go ahead and close this)

**Comment by ajbouh** [comment]
I don't fully understand the data flow between setup and load, but maybe?

Are there values that the server-side invocation of `setup` can return that go to *every* server-side `load`, but *never* to the client-side one?

We can't use `session` to pass through a custom fetch, since `session` gets serialized automatically for the client. Maybe we can use `context` for that? I'm not really sure what the rules for `context` are or how brittle using that instead would be.

**Comment by Rich-Harris** [comment]
Fair warning: some of the nomenclature [will probably change](https://github.com/sveltejs/kit/issues/647#issuecomment-808170023), because we have too many things called 'context'.

You can derive a *request context* in `getContext`, and derive a session from that in `getSession`. Then, in your root `$layout.svelte` you can create a wrapped `fetch` using the contents of `session` and make it available to every `load` function via the *load context*. IOW request context -> session -> load context.

```js
// src/hooks.js
export function getContext({ headers }) {
  return {...};
}

export function getSession({ context }} {
  return {...};
}
```

```js
// src/routes/$layout.svelte
export async function load({ fetch, session }) {
  const context = {
    fetch: wrap(fetch, session)
  };

  return { context };
}
```

**Comment by ajbouh** [comment]
I see. This flow seems to make a few assumptions about non-global state used by the `load` function:

1. it must be serializable
2. it is either the same value for the client and the server or the server value must be something we are willing to disclose to clients

In my experience there are a variety of scenarios where we want to use non-serializable state that differs between server-side and client-side code.

Simple counter examples:
1. a specific or cache or logger instance
2. where to submit request events: a publicly accessible endpoint, a private log ingestion service, or just stdout?

**Comment by Rich-Harris** [comment]
Still not really sure I understand the problem. The `wrap(fetch, session)` example above could return a different value based on whether it's running in the browser. On the server it could e.g. use environment variables that aren't available in the client. Can you give a concrete example of a problem you can't solve with the current tools?

**Comment by ajbouh** [comment]
My server-side code primarily runs within Lambda@Edge, where environment variables are not available.

Instead on boot up my server-side pulls its configuration from AWS SSM Parameter Store. (I believe Cloudflare workers are similarly expected to store their configuration in the Cloudflare Worker KV store.) Unlike environment variables, values pulled from these places are subject to expiration and may need to be periodically updated.

In my sapper fork, I initialize a `telemetry` object from these values and call `setContext('telemetry', telemetry)` before any route processing happens.

I need this `telemetry` object for a number of things:
- for direct use in both `<script>` and `<script context="module">`
- to properly wrap `fetch`

Not only is the configuration of this `telemetry` object completely different between client and server, but the server-side implementation uses an entirely different set of imported dependencies from the client-side.

It is very straightforward to handle both the lack of environment variables and the differing imports when the server-side "context" and client-side "context" have different initialization code paths.

**Comment by Rich-Harris** [comment]
> It is very straightforward to handle both the lack of environment variables and the differing imports when the server-side "context" and client-side "context" have different initialization code paths.

this is where the overuse of "context" gets confusing — do you mean component context (as in `getContext` and `setContext`), request context, or `load` context?

I'm guessing the latter since component context isn't available in `<script context="module">` and `request.context` doesn't exist client-side. Given that, can't you use different initialization code paths like so?

```js
// src/routes/$layout.svelte
import { browser } from '$app/env';

export async function load() {
  const context = browser
    ? await import('$lib/client/context.js')
    : await import('$lib/server/context.js');

  return { context };
}
```

**Comment by benmccann** [comment]
I'm going to close this since it's a long thread and no response has been received. If there's a further need it might be best to file a new issue discussing the specific problem that needs to be solved
