### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ridwancc** [sveltejs/kit#3279]
### Describe the bug

When running npm run build getting below error:

![image](https://user-images.githubusercontent.com/47181926/148859065-89d6e49f-7b03-48b5-a772-7c04f0ceecc1.png)

### Reproduction

Ubuntu: 20.04
Node: 14.18.3

### System Info

```shell
na
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
Please provide a reproduction.

**Comment by sabars** [comment]
Adding routes\error.svelte page results in a build error

**Comment by ridwancc** [comment]
adding /routes/__error.svelte seemed to fix the build error

**Comment by sabars** [comment]
> adding /routes/__error.svelte seemed to fix the build error

The root cause is some sort of the interference between routes\error.svelte and .svelte-kit\build\components\error.svelte

**Comment by sabars** [comment]
Issue is in this line:
https://github.com/sveltejs/kit/blob/3523d38845d4eb2dc7e6eeb2861fddb366df4f63/packages/kit/src/core/build/build_server.js#L169
Instead 'entries/pages' must be 'entries' I guess
