### ISSUE TITLE
Package should obey .gitignore settings

### ISSUE THREAD

**Issue by seanlail** [sveltejs/kit#3283]
### Describe the problem

`svelte-kit package` currently exports _all_ files in the $lib folder.
There is a way to amend this in `svelte.config.js` as explained here: https://kit.svelte.dev/docs#configuration-package

While this is a good solution, I think an additional feature to this should be to obey the settings in .gitignore.

# Example:
### `.gitignore`
```
.DS_Store
/src/lib/ignore
```

When I run `svelte-kit package`:

## Expected package.json exports:
```
"exports": {
    "./package.json": "./package.json",
    ".": "./index.js"
  }
```

## Actual export:
```
"exports": {
    "./package.json": "./package.json",
    "./.DS_Store": "./.DS_Store",
    ".": "./index.js",
    "./ignore": "./ignore/index.js",
  }
```

### Describe the proposed solution

Load the `.gitignore` file (if available) and automatically ignore those files when packaging.

### Alternatives considered

1. ignore the `.DS_Store` and other files (I think Windows has a Thumbs.db or something?) when packaging.
2. add an example in the docs to show how to ignore these types of files.

### Importance

nice to have

**Comment by Conduitry** [comment]
In most npm packages, you specifically do not want to exclude everything in .gitignore from being in the package, because there are some generated files you want in the package but not in the repo. That doesn't directly apply here necessarily, but this still feels like it would be a weird feature.

**Comment by dummdidumm** [comment]
I agree with Conduitry. For example the `dist` folder is `.gitignore`'d most of the time but it's what should end up in the package.

**Comment by jchanes04** [comment]
I agree that excluding `.gitignore`'d files would probably not be very useful and could cause a lot of confusion. The docs already describe the `files` function in svelte.config.js, which could be used to exclude files from the outputted package.

**Comment by seanlail** [comment]
Fair point.

It would only be a slight improvement then to ignore the system files (.DS_Store, etc) when packaging... but as I mentioned in the description I'm able to control this in the svelte config with `if (filepath.endsWith(".DS_Store")) return false;`

**Comment by seanlail** [comment]
Will close this as it's not really worth the change. Feel free to reopen if not.

**Comment by lafkpages** [comment]
> The docs already describe the `files` function in svelte.config.js, which could be used to exclude files from the outputted package

I don't see that anywhere in [the docs](https://kit.svelte.dev/docs/configuration#files).
