### ISSUE TITLE
Vercel Deployment - Cannot read property 'location' of undefined at get_single_valued_header  

### ISSUE THREAD

**Issue by hemanthvalsaraj** [sveltejs/kit#3298]
This ain't working for me either. Am I missing something here?

**package.json**
`
{
"@sveltejs/adapter-vercel": "next",
"@sveltejs/kit": "next",
"svelte": "^3.44.0",
"svelte-preprocess": "^4.10.1",
 }
 `

**Error Log on Vercel**
`
> Using @sveltejs/adapter-vercel
> Cannot read property 'location' of undefined
    at get_single_valued_header (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/url.js:8:23)
    at visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index5.js:436:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 1
`

_Originally posted by @hemanthvalsaraj in https://github.com/sveltejs/kit/issues/3142#issuecomment-1010662879_

**Comment by benmccann** [comment]
please follow the bug reporting template. there's not enough information here to do anything meaningful with your report
