### ISSUE TITLE
Regression: adapter-static build fails if url contains comma in srcset attribute on image tag

### ISSUE THREAD

**Issue by Theo-Steiner** [sveltejs/kit#3299]
### Describe the bug

When building with adapter-static, if the srcset attribute on an image tag contains a comma, the build fails trying to fetch not the external url pointing to the image but whatever follows the comma as an internal url.
This results in a 404 and the build failing.
Example: 
not ``https://res.cloudinary.com/demo/image/upload/q_auto:best,w_864/sample.jpg`` is fetched but ``/w_864/sample.jpg``

I am pretty sure this bug was introduced by #3288 , since it doesn't occur on 1.0.0-next.223 or lower and also seems to fit the changes.

### Reproduction

Super simple reproduction of the problem: https://github.com/Theo-Steiner/crawling-external-srcset

### Logs

```shell
https://app.warp.dev/block/kmoZl6fbECWcw8hKUKyzIp
```

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 97.00 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Firefox Developer Edition: 91.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.225
    svelte: ^3.44.0 => 3.46.0
```

### Severity

blocking upgrade

### Additional Information

Many image hosts use a comma in their URLs as an api for enumerating multiple transformations. Since commas are legal in URLs, we should fix this.

**Comment by Theo-Steiner** [comment]
This could be fixed relatively easily by reverting (just) the logic for separating image candidates of a srcset back to how it was before #3288 . (https://github.com/sveltejs/kit/blob/984746649170f6619dff3751727464e16b918ee3/packages/kit/src/core/adapt/prerender/crawl.js)
```javascript
...
} else if (name === 'srcset') {
  const candidates = value.split(',');
  for (const candidate of candidates) {
    const src = candidate.trim().split(WHITESPACE)[0];
    hrefs.push(src);
  }
}
...
```
^ this approach is sadly doesn't fit to the specifications of the srcset attribute:

> If present, its value must consist of one or more image candidate strings, each separated from the next by a U+002C COMMA character (,). If an image candidate string contains no descriptors and no ASCII whitespace after the URL, the following image candidate string, if there is one, must begin with one or more ASCII whitespace.

```javascript
} else if (name === 'srcset') {
const candidates = [];
  // Parse the content of the srcset attribute.
  // The regexp is modelled after the srcset specs (https://html.spec.whatwg.org/multipage/images.html#srcset-attribute)
  // and should cover most reasonable cases.
  const regex = /\s*([^\s,]\S+[^\s,])\s*((?:\d+w)|(?:-?\d+(?:\.\d+)?(?:[eE]-?\d+)?x))?/gm;
  let sub_matches;
  while ((sub_matches = regex.exec(value))) {
    candidates.push(sub_matches[1]);
  }
  for (const candidate of candidates) {
    hrefs.push(candidate);
  }
}
```
I am not sure if this should be how we proceed though, since @Rich-Harris explicitly named the issue "Crawl prerendered pages **without regex hackery**" and this would reintroduce a bunch of regex witchcraft.
Moreover, since according to the specification the meaning of a comma changes based on the preceding symbols, Regexes might be the wrong tool for this job altogether anyways, since this would render it an irregular language. (? I have no clue what I'm talking about here, if this is wrong please correct me) Maybe a State Machine would be the better tool for this?

**Comment by johnknoop** [comment]
@Rich-Harris is this really fixed?

I'm not sure if this is truly solved. Since upgrading from a beta version of SvelteKit, this code:

```svelte
<img
    srcset="/order_thumbnail_400px.png,
            /order_thumbnail_800px.png 1.5x"
    src="/order_thumbnail_400px.png"
    alt={title} />
```

...will generate this error when building:

> Error: Not found: /order_thumbnail_400px.png,/order_thumbnail_800px.png
>     at resolve (file:///C:/work/hublinwebsite/.svelte-kit/output/server/index.js:2711:18)
>     at resolve (file:///C:/work/hublinwebsite/.svelte-kit/output/server/index.js:2586:34)
>     at #options.hooks.handle (file:///C:/work/hublinwebsite/.svelte-kit/output/server/index.js:2755:59)
>     at respond (file:///C:/work/hublinwebsite/.svelte-kit/output/server/index.js:2584:43)
> file:///C:/work/hublinwebsite/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53
>                                         throw new Error(format(details));
>                                               ^
> 
> Error: 404 /order_thumbnail_400px.png,/order_thumbnail_800px.png (linked from /)
>     at file:///C:/work/hublinwebsite/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:53:12
>     at save (file:///C:/work/hublinwebsite/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:355:4)
>     at visit (file:///C:/work/hublinwebsite/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:204:3)

Whereas if I leave out the `srcset` attribute:

```svelte
<img src="/order_thumbnail_400px.png"
alt={title} />
```

...then it builds successfully.
