### ISSUE TITLE
modifying routes/*.svelte results in a full page reload not a HMR

### ISSUE THREAD

**Issue by samccone** [sveltejs/kit#330]
Steps:

* Edit a svelte file inside of the routes folder. 
*  Observe that the entire page reloads vs a HMR. 

Expectation:

* I recall this working prior to the snowpack 3 upgrade but it seems to have regressed over the past week resulting in a less polished developer experience.

**Comment by borsemayur2** [comment]
I'm facing the same issue in WSL2. The demo app state does not persist (count resets to 0) after code change.

**Comment by borsemayur2** [comment]
Same issue occurs in vite setup (svelte-ts template)
