### ISSUE TITLE
Ability to use another port when 3000 is arleady in use 

### ISSUE THREAD

**Issue by veritem** [sveltejs/kit#3311]
### Describe the problem

Have an option to automatically use a different port when the default one (3000) is already in use. 

### Describe the proposed solution

Just like how nextjs does it. There should be a way to automatically use another port when the default one is already taken.  
![image](https://user-images.githubusercontent.com/53856673/149208838-c52a81d1-4e29-4ee4-b90d-eeea39446840.png)

### Importance

would make my life easier

**Comment by Conduitry** [comment]
You should be able to set https://vitejs.dev/config/#server-strictport to `false` to enable automatically trying another port.

**Comment by veritem** [comment]
It's working with this 
![image](https://user-images.githubusercontent.com/53856673/149211392-2ea1780c-9fdd-433f-bdbc-36fc037dd73f.png)

is there any plan to make this a default option?

**Comment by Conduitry** [comment]
There is not: https://github.com/sveltejs/kit/issues/2020#issuecomment-887324239
