### ISSUE TITLE
Unable to crawl non-soft nav links

### ISSUE THREAD

**Issue by john-michael-murphy** [sveltejs/kit#3331]
### Describe the problem

The NYT has run into a scenario where we need svelte kit to crawl links that have soft nav disabled. AFAIK the only way to disable soft nav is to set `rel=‘external’`, which disables crawling. 

https://github.com/sveltejs/kit/blob/2097f00f131aef42ffe4e8fd16da6e302ce22901/packages/kit/src/core/adapt/prerender/crawl.js#L171

### Describe the proposed solution

It would be great if there were a way to selectively bypass sveltekit's link interception, without disabling crawling. 

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
External links are now crawled, so I'll close this: https://github.com/sveltejs/kit/pull/3826
