### ISSUE TITLE
Endpoints /.well-known/* are not included

### ISSUE THREAD

**Issue by trecloux** [sveltejs/kit#3340]
### Describe the bug

We are hosting some endpoints under the `/.well-known/` path prefix, this prefix is quite standard and enforced by Android et iOS domain checks.
During the "adapt" phase, endpoint files are not copied by the builder `writeServer()` funnction. Paths starting with a dot are explicitly [filtered out](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/adapt/builder.js#L138-L142).

### Reproduction

I created a reproduction app there https://github.com/trecloux/svelte-kit-dot-path-filtered-out

### System Info

```shell
System:
    OS: Linux 5.16 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 373.44 MB / 31.20 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.2.0 - ~/.nvm/versions/node/v17.2.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.2.0/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v17.2.0/bin/npm
  Browsers:
    Chromium: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.61
    @sveltejs/kit: next => 1.0.0-next.229
    svelte: ^3.44.0 => 3.46.1
```

### Severity

blocking an upgrade

**Comment by Mlocik97** [comment]
dot prefixed files are often hidden files in a lot of filesystems, and I think hidden files shouldn't be used by Svelte at all. You typically have other dot prefixed files in project You would never want to include, and because it's complicated to decide which dot files should or shouldn't be included, I think better solution than including every dot file should be having config in svelte.config.js where we would be able to tell, which files to include, that are prefixed with dot.

**Comment by mishrasatyam** [comment]
Serve `.well-know/file` from static folder. I am using the same in production in a project

**Comment by trecloux** [comment]
> Serve `.well-known/file` from static folder. I am using the same in production in a project

Unfortunately, I'm using dynamic content there

**Comment by accuser** [comment]
I'm automatically rotating keys in a JWKS served from `.well-known/jwks.json`, and so dynamically generating the content. I could change this to serve the key set from `static`, but would need to re-build/re-deploy each time I rotated the keys. Being able to 'map' the path in `svelte.config.js` would be useful if the use of dot prefixed files should be avoided.

**Comment by accuser** [comment]
https://www.rfc-editor.org/rfc/rfc8615 defines the use of well-known URIs. I wonder if adding  `__well-known` as a root route could be a place-holder for the `.well-known` path, be mapped automatically by SvelteKit?

**Comment by sidvishnoi** [comment]
Figured out a workaround. Rename `.well-known` directory to `well-known` and rewrite request via hooks. Tested with adapter-node. 
I had some problems with content-encoding though, so I manually cleared some headers.

```js
// src/hooks.js
export const handle = ({ event, resolve }) => {
  if (event.url.pathname.startsWith('/.well-known')) {
    const url = new URL(event.url);
    url.pathname = url.pathname.replace('/.well-known', '/well-known');
    const res = await fetch(url.href, {
      method: event.request.method,
      headers: event.request.headers,
    });
    // Some content-encoding related headers cause invalid response. So, we pick
    // the desired ones. There might be a better way to do this.
    const headers = new Headers();
    headers.set('content-type', res.headers.get('content-type'));
    headers.set('cache-control', res.headers.get('cache-control'));
    return new Response(res.body, { headers });
  }

  return resolve(event);
};
```

I think adapters should respect `config.kit.routes` and/or include `.well-known` as an exception.

**Comment by mankins** [comment]
> I think adapters should respect config.kit.routes and/or include .well-known as an exception.

I agree. I think the blanket filter is a bug, but besides @sidvishnoi 's workaround you can work around it this way as well:

Rename `.well-known` to `[...wellKnown=wellKnown]`

```
src/routes/.well-known => src/routes/[...wellKnown=wellKnown]/
```

and then: `src/params/wellKnown.ts` is

```
import type { ParamMatcher } from '@sveltejs/kit';

export const match: ParamMatcher = (param) => {
  const isWellKnownPath = /^\.well-known$/i.test(param);
  return isWellKnownPath;
};
```

That way the file doesn't start with a `.` and isn't filtered by the adapter.

**Comment by coryvirok** [comment]
In case anyone else finds this and is trying to use the `[...wellKnown=wellKnown]/` rest params route. The param matcher's regex needs to be less strict to allow for rest params. 

```ts
import type { ParamMatcher } from '@sveltejs/kit'

export const match: ParamMatcher = (param) => {
  const isWellKnownPath = /^\.well-known\/.*$/i.test(param)
  return isWellKnownPath
}
```
