### ISSUE TITLE
[bug] `params` value incorrectly shows static asset

### ISSUE THREAD

**Issue by thousandsofraccoons** [sveltejs/kit#3352]
### Describe the bug

Hello, I have a route structure like this `/[lang]/[offline_id]`

When I log contents of `load({params})` I get `favicon.png` as a value during link navigation between `/[lang]` and  `/[lang]/[offline_id]`.

![image](https://user-images.githubusercontent.com/33694447/149618106-6f38c11d-3db5-4f1c-8c12-1613e33f1586.png)

### Reproduction

https://github.com/thousandsofraccoons/sveltekit-ssr-route-param-bug

start project, click link, see result in terminal

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 5.24 GB / 15.87 GB
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10
    @sveltejs/kit: next => 1.0.0-next.230
    svelte: ^3.44.0 => 3.46.2
```

### Severity

blocking an upgrade

**Comment by thousandsofraccoons** [comment]
Solved.
```
  <link rel="stylesheet" href="/global.css" />
    <link rel="manifest" href="/manifest.json" crossorigin="use-credentials" />
    <link rel="icon" type="image/png" href="/favicon.png" />
    <link rel="apple-touch-icon" href="/logo-192.png" />
```

Slashes in front of filenames resolved the issue.

**Comment by thousandsofraccoons** [comment]
Although problem still persists with `params: { lang: 'service-worker.js' },

![image](https://user-images.githubusercontent.com/33694447/149661669-beeeeb3b-02db-4bd7-aa65-0aeae9108534.png)

**Comment by benmccann** [comment]
It's hard to understand your bug report because you've cut off the top of the screenshot, so I can't see the field names.

Is this still an issue? All I see in the terminal is:

![Screenshot from 2022-01-16 09-06-50](https://user-images.githubusercontent.com/322311/149670156-add15899-5057-4ce7-b767-74be8228b44f.png)

**Comment by thousandsofraccoons** [comment]
@benmccann this one was solved. Default values in app.html make it happen. 

Regarding `service-worker.js` in params - I will update the repo in a few hours, sorry.

**Comment by thousandsofraccoons** [comment]
@benmccann I've updated the repo, same steps to reproduce, thank you

![image](https://user-images.githubusercontent.com/33694447/149768659-2f536991-677d-4512-ab2e-a83410299b01.png)

**Comment by thousandsofraccoons** [comment]
Also, it causes awkward side effect that breaks cypress tests related to i18n. Cypress sets header "accept-language", this service-worker request inside of `handle()` hook always has the following headers:
```
ctx :>>  {
  connection: 'keep-alive',
  host: 'localhost:3000',
  'proxy-connection': 'keep-alive',
  'cache-control': 'max-age=0',
  accept: '*/*',
  'service-worker': 'script',
  'sec-fetch-site': 'same-origin',
  'sec-fetch-mode': 'same-origin',
  'sec-fetch-dest': 'serviceworker',
  referer: 'http://localhost:3000/service-worker.js',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',       
  'accept-encoding': 'gzip',
  'accept-language': 'en-US,en;q=0.9',
  'if-none-match': '"e47ttb"'
}
```

it breaks language detection and redirects

**Comment by benmccann** [comment]
I'm not seeing any issue with the `ctx.params` your app is logging. It shows `lang: 'en'` for me. I wonder if there's some Windows issue here?

**Comment by thousandsofraccoons** [comment]
@benmccann I got same issue on Mac

```
 System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 8.99 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 91.1.26.74
    Chrome: 97.0.4692.71
    Firefox: 95.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.11 
    @sveltejs/kit: next => 1.0.0-next.232 
    svelte: ^3.44.0 => 3.46.2
```

**Comment by benmccann** [comment]
The only way I get this to happen is if I visit the URL http://localhost:3000/service-worker.js which is not what the reproduction instruction above say to do.

That happens because the file `service-worker.js` does not exist, so the static handler doesn't handle it and you hit the SvelteKit handler

This is an issue in your application and doesn't appear to be a SvelteKit bug
