### ISSUE TITLE
Non-JS/TS server with SvelteKit

### ISSUE THREAD

**Issue by cabreraalex** [sveltejs/kit#3360]
### Describe the problem

I was curious if some support for non-JS servers + SvelteKit is either in the works or could be implemented in the future, e.g. Flask, FastAPI, etc. I'm guessing one challenge would be doing SSR from a language like Python.

### Describe the proposed solution

It would be great to have at least one example adapter or template that uses a non-JS/TS server.

### Importance

nice to have

**Comment by Conduitry** [comment]
This isn't practical because JS can appear anywhere in the template or in the script tag, and this would essentially involve transpiling JS to other languages.
