### ISSUE TITLE
The npmjs repo link for create-svelte is wrong

### ISSUE THREAD

**Issue by olivercoad** [sveltejs/kit#3368]
### Describe the bug

While trying to find the repo that is used when you do `npm init svelte@next`, I found https://www.npmjs.com/package/create-svelte. But the repository and homepage and readme on that are for https://github.com/Axelen123/create-svelte-site instead of https://github.com/sveltejs/kit/tree/master/packages/create-svelte

### Reproduction

Visit https://www.npmjs.com/package/create-svelte and click on the homepage link.  
Expected: goes to this repo
Actual result: goes to an old archived repo

### System Info

```shell
.
```

### Severity

annoyance

### Additional Information

I'm not even 100% sure that `create-svelte` is the right npm package, so maybe it's an unrelated 3rd party package, but looking at this https://docs.npmjs.com/cli/v8/commands/npm-init#description and looking at the versions tab, I think it's the one.

**Comment by dummdidumm** [comment]
This happens because we took other that package with the kind permission of the original author. The new versions are under the `next` tag while SvelteKit is in beta. Once it reacher 1.0, `create-svelte` will be bumped to version 2.0 and then the correct readme should appear.

**Comment by Conduitry** [comment]
`create-svelte` is now also being published as `create-svelte@latest` and https://www.npmjs.com/package/create-svelte now displays the correct package - _however_, that package does not have a readme. I'm going to leave this issue open until we write one.
