### ISSUE TITLE
Credentialed `fetch` for hooks

### ISSUE THREAD

**Issue by AradAlvand** [sveltejs/kit#3380]
### Describe the problem

I'm a bit confused about how authentication is done in SvelteKit as I couldn't find sufficient information in the docs, so I think I need some guidance.

I have an ASP.NET Core back-end application, which acts as my API and will be served on a subdomain in production (e.g. `api.my-domain.com`), and a SvelteKit front-end application which would be the main site (e.g. `my-domain.com`).

Authentication is already implemented in the back-end project, once a user logs in, a cookie is generated that contains a token (sort of like JWT). Any subsequent requests that carry that cookie will be authenticated. Pretty straightforward stuff.

Now, in the docs, in the section about the `load` function's `fetch`, it's mentioned that:
> Cookies will only be passed through if the target host is the same as the SvelteKit application or a more specific subdomain of it. [(Here)](https://kit.svelte.dev/docs#:~:text=additional%20network%20request.-,Cookies%20will%20only%20be%20passed%20through%20if%20the%20target%20host%20is%20the%20same%20as%20the%20SvelteKit%20application%20or%20a%20more%20specific%20subdomain%20of%20it.,-session)

And this works beautifully. When a load function sends a fetch request to the same target host, the client's credentials are properly passed through. As a result, when, for example, in a layout's `load` function I send a fetch request to my back-end API to retrieve, say, the current user's authentication state and information, it works as expected during SSR, that is, the auth cookie is passed through and the right information is retrieved. The fetch request that takes place on the server, in a sense, **emulates** a fetch request that's sent directly from the user's browser (in terms of credentials).

But I also noticed that SvelteKit has something called the [`getSession` hook](https://kit.svelte.dev/docs#hooks-getsession) which is simply a function that's run on every request and can be used to retrieve information about the current request, including the current user's authentication status, and that information is then put in a `session` store that is going to be available to use in pages and components.
In the `getSession` hook, however, I tried to send a fetch request to my back-end API to retrieve some information about the current user, but the problem is I need the client's credentials to be passed through, just like what happens in `load` functions (provided that you used the special `fetch` that's received as an argument, of course). But there's no such special `fetch` in hooks, and by using the global, plain `fetch` there, it's as though the server is sending the request and therefore the client's credentials aren't passed through.

### Describe the proposed solution
Couldn't hook functions also receive a special `fetch` that passes the client's credentials through and effectively emulates the client? Just like how the load function's `fetch` works. This would enable scenarios like this.

If there is already a straightforward workaround for this, or I'm missing something obvious, let me know.

Thank you.

**Comment by Conduitry** [comment]
In hooks, you have access to all of the request's headers (unlike in load) so you can construct the fetch request using whichever headers you want however you want.

It might make sense to expose the cookie handling from load in hooks if we can find a sensible way for that to behave, but you do already have all of the information available to you.

**Comment by AradAral** [comment]
@Conduitry Thanks for the pointer. Then I guess I can just manually pass the client's headers through to the fetch request that's being sent in the hook.

> It might make sense to expose the cookie handling from load in hooks if we can find a sensible way for that to behave

Yeah I think that would be a good idea. So, if you don't mind we can keep this issue open for that.

**Comment by Rich-Harris** [comment]
I think this is a documentation issue rather than something that justifies a new feature — opened #4726
