### ISSUE TITLE
Typing `props` and `stuff` in `LoadOutput` and `Load`

### ISSUE THREAD

**Issue by AradAral** [sveltejs/kit#3392]
### Describe the bug

I'm using TypeScript, and trying to specify the type of the `props` property in the return type of my load function. But I don't seem to be able to get it working:

```svelte
<script lang="ts" context="module">
    import type { Load, LoadInput, LoadOutput } from "@sveltejs/kit";

    type Props = {
        foo: number;
    }

    const output: LoadOutput<Props> = {
        props: { // type is 'Props', as expected.

        }
    }

    export const load: Load<LoadInput, LoadOutput<Props>> = async () => {
        return {
            props: { // type is 'Rec<any>', it should be 'Props'.

            }
        }
    };
</script>
```

Also, when I do:
```typescript
type Test = ReturnType<Load<LoadInput, LoadOutput<Props>>>>;
// 'Test' is:
// MaybePromise<Either<LoadOutput<Rec<any>, Rec<any>>, Fallthrough>>
// But it should be:
// MaybePromise<Either<LoadOutput<Props, Rec<any>>, Fallthrough>>
```

There seems to me to be something wrong with SvelteKit's `Load` type here.

### System Info

```shell
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.02 GB / 7.89 GB
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.232 => 1.0.0-next.232
    svelte: ^3.42.6 => 3.44.2
```

### Severity

annoyance

**Comment by AradAral** [comment]
**Update:** After playing with this for hours, I just found out that the way you're supposed to type the properties of input and output of `load` function (like `props` for the output type, or even `session` of the input type) is something like this:
```typescipt
export const load: Load<{ session: Sessio }, { props: PropsType }> = async () => {
    return {
        props: {

        }
    }
};
```
But to me this wasn't clear at all. So I'll keep this issue open as a suggestion to write about this in the docs.

**Comment by 7nik** [comment]
The interface `LoadOutput<>` defines `props` as optional, but the inner type `InferValue<>` expects `props` to be a required property, so it fallbacks to `Rec<any>` instead of `Props`.

You can see why it happens here:
```ts
import type { InferValue, Rec } from "@sveltejs/kit/types/helper";
// the InferValue returns either type of the named property in the first type or the third type
type Test1 = InferValue<LoadOutput<Props>, 'props', Rec>; // type Test1 = { [x: string]: any; }
// the same but with just unfolded and simplified, for this case, `LoadOutput`.
type Test2 = InferValue<{props?: Props}, 'props', Rec>; // type Test2 = { [x: string]: any; }
type Test3 = InferValue<{props: Props}, 'props', Rec>; // type Test3 = { foo: number; }
```

But `LoadInput` doesn't have this problem as all its fields are defined as required.

**Comment by AradAral** [comment]
@7nik Thanks for the explanation. I was confused about that too, now it makes sense.
Am I still right in thinking that [this](https://github.com/sveltejs/kit/issues/3392#issuecomment-1015210339) is the way these property types are supposed to specified? I'm assuming that's the reason why `InferValue` is used and why `Load` is defined like this:
```typescript
export interface Load<
	Input extends LoadInputExtends = Required<LoadInputExtends>,
	Output extends LoadOutputExtends = Required<LoadOutputExtends>
> {
	(
		input: LoadInput<
			InferValue<Input, 'pageParams', Rec<string>>,
			InferValue<Input, 'stuff', Rec>,
			InferValue<Input, 'session', any>
		>
	): MaybePromise<
		Either<
			LoadOutput<InferValue<Output, 'props', Rec>, InferValue<Output, 'stuff', Rec>>,
			Fallthrough
		>
	>;
}
```

If so, I think it would be nice if this was mentioned somewhere perhaps, as it's likely to confuse people.

**Comment by 7nik** [comment]
I doubt that the PR fixed the problem. As far as I can see, the types passed to `LoadOutput<>` still get ignored and replaced with `Record<string, any>`.
I think the solution can be to return the following type by `Load`:
```ts
MaybePromise<
    Either<
	    Fallthrough,
	    LoadOutput<
		    InferValue<Required<Output>, 'props', Record<string, any>>,
		    InferValue<Required<Output>, 'stuff', Record<string, any>>
	    >
    >
>
```
It's should be okay to requirefy `Output` as `LoadOutput` anyway defines `props` and `stuff` as optional.

**Comment by AradAral** [comment]
@ignatiusmb Sorry I don't understand how your PR resolved this issue?!

**Comment by ignatiusmb** [comment]
What seems to be the problem here? The original issue points that you don't understand how to use the `Load` type from the lack of documentation, hence the PR including the definitions in the docs.

**Comment by AradAral** [comment]
@ignatiusmb Well, I was expecting an example (the usage if you will), as opposed to just the types themselves.
Similar to the code snippet in [this comment](https://github.com/sveltejs/kit/issues/3392#issuecomment-1015210339) of mine.

**Comment by ignatiusmb** [comment]
We don't have any usage examples for using types in the docs, so it doesn't make sense to add one for this.

**Comment by AradAral** [comment]
Okay then I think it would be a good idea to add type usage examples to the docs in general, although I understand that that's beyond the scope of this issue.
Is there an already-existing issue for this or not?
