### ISSUE TITLE
Store discrepancy from packages in dev

### ISSUE THREAD

**Issue by MathiasFrost** [sveltejs/kit#3401]
### Describe the bug

When using `svelte-kit package` on a lib that has stores in it, installing said package in another Svelte-Kit app and changing the store value in the main app will have no effect on the store in the package and vice versa.   

This means that this code:
```html
<script lang="ts">
    import {get} from "svelte/store";
    import {someStore} from "sveltepack/someStore";
    import TestComponent from "sveltepack/TestComponent.svelte";

    let count = 0;

    function click() {
        count++;
        someStore.set(`new value: ${count}`);
        console.log(`Value set to ${get(someStore)}`);
    }
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<p>{$someStore}</p>
<button on:click={click}>
    Change store value
</button>

<hr/>
<h1>Component from package:</h1>
<TestComponent/>
```
_(TestComponent's code is exactly the same)_

Will result in this result in dev:
![image](https://user-images.githubusercontent.com/77194821/149993786-83f85b7f-e306-46e4-adc0-99485d4ae6f4.png)  

While the same code after build will act as it is supposed to:
![image](https://user-images.githubusercontent.com/77194821/149993932-1a0dac6d-722f-4a7d-85fc-89c2755a2cfb.png)

### Reproduction

First
```shell
npm init svelte@next SveltePack
```
And
```shell
npm init svelte@next SvelteMain
```
Make a `TestComponent.svelte` and `someStore.ts` or `someStore.js` in SveltePack.  
Write this code in `TestComponent.svelte`:
```html
<script lang="ts">
    import {someStore} from "$lib/someStore";
    import {get} from "svelte/store";

    let count = 0;

    function click() {
        count++;
        someStore.set(`new value: ${count}`);
        console.log(`Value set to ${get(someStore)}`);
    }
</script>

<p>{$someStore}</p>
<button on:click={click}>
    Change store value
</button>
```

Adn this code in `someStore.ts`:
```ts
import {writable} from "svelte/store";

export const someStore = writable<string>("Initial value");
```

Then
```shell
npm run package
cd package
npm pack
cd ../..
cd SvelteMain
npm install -D ../SveltePack/package/sveltepack-0.0.1.tgz 
```

And write this in ìndex.svelte` in SvelteMain:
```html
<script lang="ts">
    import {get} from "svelte/store";
    import {someStore} from "sveltepack/someStore";
    import TestComponent from "sveltepack/TestComponent.svelte";

    let count = 0;

    function click() {
        count++;
        someStore.set(`new value: ${count}`);
        console.log(`Value set to ${get(someStore)}`);
    }
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<p>{$someStore}</p>
<button on:click={click}>
    Change store value
</button>

<hr/>
<h1>Component from package:</h1>
<TestComponent/>
```

### Logs

```shell
[vite] connecting...
client.ts:52 [vite] connected.
index.svelte? [sm]:11 Value set to new value: 1
TestComponent.svelte? [sm]:7 Value set to new value: 1
index.svelte? [sm]:11 Value set to new value: 2
TestComponent.svelte? [sm]:7 Value set to new value: 2
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 19.25 GB / 31.93 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.11
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.232
    svelte: ^3.44.0 => 3.46.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The reason I set to "blocking all usage of SvelteKit" is because developing component libraries is an important part of building apps for a company.  
The way I see it, right now the only way I can do that consistently with Svelte is to use Rollup.  
Would be amazing if this issue was resolved without using advanced configuration.  
_(That being said, I appreciate advice on working around this issue with fancy config ^^)_

**Comment by Conduitry** [comment]
With SSR, stores that don't have some way to make sure they're scoped to the current request are a bad idea anyway, because their value will be shared across all users on the server.

If you're certain that these are only being used client-side, I would recommend either a) making it the consumer's responsibility to instantiate stores and pass them in to your components, or b) having the store instance live inside the package and export it from the `<script context=module>` so that consumers of the component can also have access to that same instance of the store. If the stores are being imported from some external package, there are always going to be duplication issues with somebody's setup, and I wouldn't suggest packaging your components that way.

I don't know what "fixing" this for SvelteKit would mean. Assuming we can rule out the issues with shared server-side state being the cause of this behavior, I'm guessing this would be a feature request for Vite for how they resolve modules in dev mode.

**Comment by MathiasFrost** [comment]
> With SSR, stores that don't have some way to make sure they're scoped to the current request are a bad idea anyway, because their value will be shared across all users on the server.
> 
> If you're certain that these are only being used client-side, I would recommend either a) making it the consumer's responsibility to instantiate stores and pass them in to your components, or b) having the store instance live inside the package and export it from the `<script context=module>` so that consumers of the component can also have access to that same instance of the store. If the stores are being imported from some external package, there are always going to be duplication issues with somebody's setup, and I wouldn't suggest packaging your components that way.
> 
> I don't know what "fixing" this for SvelteKit would mean. Assuming we can rule out the issues with shared server-side state being the cause of this behavior, I'm guessing this would be a feature request for Vite for how they resolve modules in dev mode.

So, I am 100% sure that I did explore the `<script context="module">` before, but when I tried it now, that did do what I wanted it to do:
```html
<script context="module" lang="ts">
    import {writable} from "svelte/store";

    export const anotherStore = writable<string>("Another value");
</script>

<script lang="ts">
    import {get} from "svelte/store";

    let count = 0;

    function click() {
        count++;
        anotherStore.set(`new value: ${count}`);
        console.log(`Value set to ${get(anotherStore)}`);
    }
</script>

<p>{$anotherStore}</p>
<button on:click={click}>
    Change store value
</button>
```

I have to try it on my component library to make sure it works _(as mentioned I did explore this option before and for some reason I can't remember, I decided it did not work optimally)_  

If it does though, there is no point in this issue's existence, even less if it is a Vite issue ^^. 

_(My use case is indeed an SPA, so I am sure it is only client-side)_

**Comment by MathiasFrost** [comment]
I see. I think the reason why I thought it was not optimal was because we use JetBrains IDE's and it does not recognize exports from `<script context="module">` from within the same project _(not an npm package)_:
![image](https://user-images.githubusercontent.com/77194821/150076478-10d55fa8-ecc0-47b1-a81e-fb3655269f79.png)

But if I ignore the error it does work as it should, and VSCode does not have this problem. _(both using ther respective Svelte plugin of course)_
This is an issue for YouTrack then, thanks ^^
