### ISSUE TITLE
sveltekit:prefetch multiple prefetches

### ISSUE THREAD

**Issue by pavelloz** [sveltejs/kit#3416]
### Describe the bug

Im using `sveltekit:prefetch` and it seems to me that if i cycle between two links, Svelte will fetch the same link over and over, without any consideration of cache. Im not sure if its a bug or feature.

Log from network tab as visualization:
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/546845/150212720-b68befdd-233d-440a-9496-f03528e2a606.png">

### Reproduction

1. Create two (or more) links with sveltekit:prefetch
2. Hover over first, then second, then first again

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 703.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v14.18.1/bin/npm
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.26 
    @sveltejs/kit: next => 1.0.0-next.229 
    svelte: ^3.46.2 => 3.46.2 
    vite: ^2.7.12 => 2.7.12
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
When I'm opening Dev Tools "disable network cache" is enabled by default, there's a checkbox for that in that tab. Is it checked? I'm guessing that's what triggers this behavior for you, it wouldn't have anything to do with SvelteKit.

**Comment by bluwy** [comment]
This is expected by default because the data could be stale when you hover over it again. To prevent this, you can set a [maxage](https://kit.svelte.dev/docs#loading-output-maxage) to tell how long to consider the data as stale and to be refetched again.

**Comment by pavelloz** [comment]
Thank you. You are both right. I had `disable cache` checked and i need to dive into `maxage`. :)
