### ISSUE TITLE
Could not find request resource

### ISSUE THREAD

**Issue by deshartman** [sveltejs/kit#3417]
### Describe the bug

Create a brand new Sveltkit project and launch with error: Could not find request resource

![image](https://user-images.githubusercontent.com/47675451/150215579-cae2904a-29f4-4090-8502-e07481e0f83a.png)
 
Reload the page and then get this error:

![image](https://user-images.githubusercontent.com/47675451/150215867-e8b36b89-031c-4702-a298-aeae6431340b.png)

### Reproduction

Create a brand new Sveltkit project:

`npm init svelte@next test`

Select demo project with defaults:
✔ Which Svelte app template? › SvelteKit demo app
✔ Use TypeScript? … **No** / Yes
✔ Add ESLint for code linting? … **No** / Yes
✔ Add Prettier for code formatting? … **No** / Yes

`cd test`

`npm Install`
`npm run dev -- --open`

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 425.43 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.14 - /usr/local/bin/yarn
    npm: 8.1.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 91.1.26.67
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.13 
    @sveltejs/kit: next => 1.0.0-next.234 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
It looks like #3415 was missing a changeset for create-svelte and the necessary changes to the starter apps there weren't published.
