### ISSUE TITLE
Maintain a template repo

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3422]
### Describe the problem

If you go to https://node.new/sveltekit, it will create an out of date project. That's because we haven't supplied a template repo, so it's using a snapshot.

### Describe the proposed solution

If we had a programmatic interface to `create-svelte` (#3421), then we could create a GitHub action that kept such a template repo up to date. This action would run on every commit to `master` (and dryrun on all other commits?)

### Importance

would make my life easier

**Comment by Mlocik97** [comment]
Wouldn't it make more sense, if it would be run every time, new version of kit or create-svelte is deployed to npm? So there is not "unreleased" version of it in node.new / stackblitz ?

**Comment by Rich-Harris** [comment]
Good point, it probably belongs in the release workflow (https://github.com/sveltejs/kit/blob/master/.github/workflows/release.yml), or the `pnpm release` command

**Comment by benmccann** [comment]
Should this be closed now that https://github.com/sveltejs/kit-template-default exists or is there more to do?

**Comment by Conduitry** [comment]
Well, it's still private. We'd probably want to make it public, maybe mark it as a template repo in GitHub (although people should probably just use the CLI), and disable issues or otherwise limit contributions and update the repo description there so that stuff gets opened over here instead.

**Comment by Rich-Harris** [comment]
we can close this now — https://github.com/sveltejs/kit-template-default is public, and powers https://sveltekit.new
