### ISSUE TITLE
Distributing multiple copies of same file

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#3428]
### Describe the bug

`node_modules/@sveltejs/kit/dist/chunks/index.js` and `node_modules/@sveltejs/kit/dist/assets/index.js` seem to have quite a lot of duplicated content in them. It makes debugging a pain because I don't know which line of code is actually being run and it makes installing the package take longer than necessary

### Reproduction

Run `npm init svelte @next` and look in `node_modules/@sveltejs/kit`

### System Info

```shell
any
```

### Severity

annoyance

**Comment by JEbertPrime** [comment]
I might be making a mistake setting up, but the second path you provided (`node_modules/@sveltejs/kit/dist/assets/index.js`) seems to not be present in a normal install. Wondering if you mean `node_module/@sveltejs/kit/assets/server/index.js` which seems to have quit a bit of replicated code

**Comment by benmccann** [comment]
The paths seem to have changed a bit though there's still some duplication present. E.g. if I do `grep -r "ignore W/ prefix"` I see that line in both of the following files:
```
./dist/chunks/index.js
./assets/server/index.js
```

**Comment by JEbertPrime** [comment]
The duplicated code is a result of the `src/runtime/server/index.js` module not being properly externalized during the build process. When the rollup config is updated to externalize that import, there's no duplication. Tests are passing for this change. #3628

**Comment by JEbertPrime** [comment]
Windows test `url-supplied anchor is ignored with onMount() scrolling on navigation to page ` fails. Unsure about why, but it appears(?) that this test fails regularly. 
Some thoughts about this solution:
- It muddies up the rollup config, which probably won't make maintenance easier
- My solution works but is kinda gross. Having a regex match in the config is probably less than ideal
- There is probably a reason why there aren't any imports between dist and assets folders. FWIW this import (from `src/core/dev/plugin.js`) seems to be the only one that references a module in the `runtime` folder (as evidenced by `grep -r '^import.*runtime'`) so this probably doesn't need to be a generalizable solution

_Originally posted by @JEbertPrime in https://github.com/sveltejs/kit/issues/3628#issuecomment-1025802097_
