### ISSUE TITLE
Netlify: Request with GET/HEAD method cannot have body

### ISSUE THREAD

**Issue by mattpilott** [sveltejs/kit#3438]
### Describe the bug

Hello,

I updated to kit 234 & auto adapter 13 this morning and upon deploying to netlify I ran into the attached issue.

After asking in discord and trying a few things i have been unable to resolve it.

I then created a reproduction using the skeleton starter and managed to confirm the issue again. This may very well be down to a breaking change in https://github.com/sveltejs/kit/pull/3384

Happy to give more info if need be!

### Reproduction

https://github.com/mattpilott/kit

https://kittest.netlify.app

### Logs

```shell
{
  "errorType": "TypeError",
  "errorMessage": "Request with GET/HEAD method cannot have body",
  "trace": [
    "TypeError: Request with GET/HEAD method cannot have body",
    "    at new Request2 (/var/task/.netlify/functions-internal/render.js:5262:17)",
    "    at Runtime.handler (/var/task/.netlify/functions-internal/render.js:7048:39)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 76.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.3.1 - /opt/homebrew/bin/node
    npm: 8.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0.1
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.13 
    @sveltejs/kit: next => 1.0.0-next.234 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

blocking an upgrade

**Comment by thisisthejay** [comment]
I'm getting the same issue on my deploy [https://confident-perlman-901dcd.netlify.app](https://confident-perlman-901dcd.netlify.app)

**Comment by dimavolo** [comment]
I got the same issue after following the resolution steps in #2687

**Comment by mattpilott** [comment]
@dimavolo You can downgrade to kit 233 and auto-adapter 12 (netlify adapter 40)

**Comment by dimavolo** [comment]
> @dimavolo You can downgrade to kit 233 and auto-adapter 12 (netlify adapter 40)

Thanks for the suggestion. I gave that a go, but that now reverts to my original error: `SyntaxError: Unexpected token '.'`

https://61e987875ecd5f0007e9b0aa--excel-demo-012.netlify.app

Are these two issues (i.e. optional chaining vs. "Request with GET/HEAD method cannot have body")  connected or quite separate?

**Comment by dimavolo** [comment]
```
"devDependencies": {
		"@babel/core": "^7.16.10",
		"@babel/preset-env": "^7.16.10",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/adapter-netlify": "^1.0.0-next.40",
		"@sveltejs/kit": "^1.0.0-next.235",
		"@tailwindcss/forms": "^0.4.0",
		"@tailwindcss/typography": "^0.5.0",
```

**Comment by mattpilott** [comment]
Im not sure, cant see how they would be. Have you tried setting a NODE_VERSION env variable in netlify?

`NODE_VERSION` = `node`

**Comment by dimavolo** [comment]
I've tried all these variations:

1. Setting NODE_VERSION env variable in Netlify Dashboard UI

2. Setting NODE_VERSION in netlify.toml

3. Setting netlify.toml:

```
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"
```
  
4. Setting netlify.toml:

```
[functions]
  node_bundler = "esbuild"
```

Currently my package.json has:

```

"devDependencies": {
		"@babel/core": "^7.16.10",
		"@babel/preset-env": "^7.16.10",
		"@sveltejs/adapter-auto": "1.0.0-next.12",
		"@sveltejs/adapter-netlify": "^1.0.0-next.40",
		"@sveltejs/kit": "^1.0.0-next.233",
		"@tailwindcss/forms": "^0.4.0",
```

Currently Netlify env in the UI has only:

`AWS_LAMBDA_JS_RUNTIME = nodejs14.x`

My deploy is here: https://61e989e221b6fd00070a45cd--excel-demo-012.netlify.app

**Comment by mattpilott** [comment]
<img width="733" alt="Screenshot 2022-01-20 at 4 10 44 pm" src="https://user-images.githubusercontent.com/2401925/150395366-80c22447-2712-491c-8a7f-1908d017b080.png">
Try this one
