### ISSUE TITLE
[bug] undefined path error on vercel

### ISSUE THREAD

**Issue by rcapdepaula** [sveltejs/kit#3442]
### Describe the bug

In localhost, I don't have any problems, but when I deploy the project on Vercel, I get this error:

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined`

I access the URL https://svelte-house-marketplace.vercel.app/ and get the error, but when I refresh the page, works normally.

### Reproduction

[https://github.com/rcapdepaula/svelte-house-marketplace](https://github.com/rcapdepaula/svelte-house-marketplace)

### System Info

```shell
Windows
```

### Severity

serious, but I can work around it

### Additional Information

I can't find identify where is the error. I have no idea.

**Comment by rcapdepaula** [comment]
Any solution for this?

**Comment by benmccann** [comment]
Can you provide a stack trace?

**Comment by rcapdepaula** [comment]
> Can you provide a stack trace?

Sorry, how do i do it?

**Comment by benmccann** [comment]
https://vercel.com/docs/concepts/deployments/logs#function-logs

**Comment by rcapdepaula** [comment]
> https://vercel.com/docs/concepts/deployments/logs#function-logs

My Build log:

Cloning github.com/rcapdepaula/svelte-house-marketplace (Branch: master, Commit: 95d97bc)
--
```
11:26:43.097 | Cloning completed: 963.92ms
11:26:43.129 | Analyzing source code...
11:26:43.378 | Installing build runtime...
11:26:45.784 | Build runtime installed: 2.405s
11:26:46.111 | Looking up build cache...
11:26:48.199 | Build cache downloaded [27.18 MB]: 1840.468ms
11:26:48.378 | Detected package.json
11:26:48.378 | Installing dependencies...
11:26:48.380 | Detected `package-lock.json` generated by npm 7...
11:26:49.340 |  
11:26:49.341 | up to date in 674ms
11:26:49.341 |  
11:26:49.341 | 9 packages are looking for funding
11:26:49.342 | run `npm fund` for details
11:26:49.613 | Running "npm run build"
11:26:50.010 |  
11:26:50.011 | > house-marketplace@0.0.1 build
11:26:50.011 | > svelte-kit build
11:26:50.011 |  
11:26:50.415 | vite v2.7.4 building for production...
11:26:50.528 | transforming...
11:26:52.953 | 2:26:52 PM [vite-plugin-svelte] /vercel/path0/node_modules/svelte-slidy/src/Slidy.svelte:4:4 A11y: Redundant role 'region'
11:26:52.954 | 2:
11:26:52.954 | 3: <section
11:26:52.955 | 4:     role="region"
11:26:52.955 | ^
11:26:52.955 | 5:     tabindex="0"
11:26:52.956 | 6:     aria-label="Slidy"
11:26:56.078 | ✓ 86 modules transformed.
11:26:56.398 | rendering chunks...
11:26:56.754 | .svelte-kit/output/client/_app/manifest.json                                                7.49 KiB
11:26:56.758 | .svelte-kit/output/client/_app/pages/__layout.svelte-e8b23226.js                            5.35 KiB / gzip: 2.25 KiB
11:26:56.759 | .svelte-kit/output/client/_app/pages/index.svelte-98dcf1c6.js                               3.81 KiB / gzip: 1.81 KiB
11:26:56.759 | .svelte-kit/output/client/_app/pages/forgot-password.svelte-c35a4588.js                     1.99 KiB / gzip: 1.06 KiB
11:26:56.760 | .svelte-kit/output/client/_app/start-475ce09b.js                                            22.14 KiB / gzip: 7.29 KiB
11:26:56.760 | .svelte-kit/output/client/_app/pages/category/_catName_.svelte-a6e0295f.js                  3.69 KiB / gzip: 1.66 KiB
11:26:56.760 | .svelte-kit/output/client/_app/pages/category/_id_/_listingId_.svelte-55d12197.js           9.50 KiB / gzip: 3.86 KiB
11:26:56.761 | .svelte-kit/output/client/_app/pages/contact/_landLordId_.svelte-f1cc8ab5.js                2.84 KiB / gzip: 1.42 KiB
11:26:56.761 | .svelte-kit/output/client/_app/pages/createlistings.svelte-dafddd5d.js                      13.00 KiB / gzip: 4.74 KiB
11:26:56.762 | .svelte-kit/output/client/_app/pages/profile.svelte-d1420ff8.js                             6.29 KiB / gzip: 2.83 KiB
11:26:56.762 | .svelte-kit/output/client/_app/pages/offers.svelte-0a37f362.js                              3.85 KiB / gzip: 1.73 KiB
11:26:56.762 | .svelte-kit/output/client/_app/pages/signin.svelte-92fb0a5e.js                              3.23 KiB / gzip: 1.51 KiB
11:26:56.763 | .svelte-kit/output/client/_app/pages/signup.svelte-5bb50249.js                              3.54 KiB / gzip: 1.62 KiB
11:26:56.763 | .svelte-kit/output/client/_app/pages/_editListing_/_listingId_.svelte-daa98cd0.js           13.12 KiB / gzip: 4.79 KiB
11:26:56.763 | .svelte-kit/output/client/_app/chunks/singletons-12a22614.js                                0.05 KiB / gzip: 0.06 KiB
11:26:56.763 | .svelte-kit/output/client/_app/chunks/preload-helper-ec9aa979.js                            0.51 KiB / gzip: 0.36 KiB
11:26:56.763 | .svelte-kit/output/client/_app/chunks/firebase.config-0035150b.js                           0.37 KiB / gzip: 0.27 KiB
11:26:56.764 | .svelte-kit/output/client/_app/chunks/notifications-86bae1f2.js                             0.57 KiB / gzip: 0.35 KiB
11:26:56.764 | .svelte-kit/output/client/_app/chunks/stores-cd0eaa18.js                                    0.38 KiB / gzip: 0.23 KiB
11:26:56.764 | .svelte-kit/output/client/_app/chunks/ListingItem-58cec434.js                               4.23 KiB / gzip: 1.70 KiB
11:26:56.764 | .svelte-kit/output/client/_app/chunks/navigation-51f4a605.js                                0.11 KiB / gzip: 0.12 KiB
11:26:56.764 | .svelte-kit/output/client/_app/chunks/OAuth-6b168417.js                                     1.61 KiB / gzip: 0.87 KiB
11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/__layout.svelte-8926c4e3.css                    0.35 KiB / gzip: 0.24 KiB
11:26:56.765 | .svelte-kit/output/client/_app/assets/start-61d1577b.css                                    0.16 KiB / gzip: 0.15 KiB
11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/category/_catName_.svelte-c2348a6d.css          0.04 KiB / gzip: 0.06 KiB
11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/forgot-password.svelte-2470cbe0.css             0.20 KiB / gzip: 0.15 KiB
11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/createlistings.svelte-57eb0c3e.css              0.08 KiB / gzip: 0.09 KiB
11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/index.svelte-be82b0ef.css                       0.76 KiB / gzip: 0.34 KiB
11:26:56.766 | .svelte-kit/output/client/_app/assets/vendor-5b2b3803.css                                   3.52 KiB / gzip: 0.79 KiB
11:26:56.766 | .svelte-kit/output/client/_app/assets/OAuth-b2f14544.css                                    0.41 KiB / gzip: 0.20 KiB
11:26:56.766 | .svelte-kit/output/client/_app/assets/pages/offers.svelte-ed65610e.css                      0.12 KiB / gzip: 0.12 KiB
11:26:56.766 | .svelte-kit/output/client/_app/assets/pages/category/_id_/_listingId_.svelte-9a790867.css   0.12 KiB / gzip: 0.12 KiB
11:26:56.766 | .svelte-kit/output/client/_app/assets/pages/signup.svelte-30e18588.css                      0.55 KiB / gzip: 0.29 KiB
11:26:56.767 | .svelte-kit/output/client/_app/error.svelte-bcee5e53.js                                     1.56 KiB / gzip: 0.75 KiB
11:26:56.770 | .svelte-kit/output/client/_app/chunks/leaflet-src-9525ae07.js                               140.07 KiB / gzip: 40.61 KiB
11:26:56.779 | .svelte-kit/output/client/_app/chunks/vendor-ec885d3a.js                                    455.41 KiB / gzip: 108.33 KiB
11:26:56.787 | vite v2.7.4 building SSR bundle for production...
11:26:56.887 | transforming...
11:26:57.398 | 2:26:57 PM [vite-plugin-svelte] /vercel/path0/node_modules/svelte-slidy/src/Slidy.svelte:4:4 A11y: Redundant role 'region'
11:26:57.398 | 2:
11:26:57.398 | 3: <section
11:26:57.399 | 4:     role="region"
11:26:57.399 | ^
11:26:57.399 | 5:     tabindex="0"
11:26:57.399 | 6:     aria-label="Slidy"
11:26:57.546 | ✓ 53 modules transformed.
11:26:57.589 | rendering chunks...
11:26:57.609 | .svelte-kit/output/server/app.js                               0.09 KiB
11:26:57.609 | .svelte-kit/output/server/chunks/app-18f56d88.js               21.48 KiB
11:26:57.611 | .svelte-kit/output/server/chunks/__layout-2a587688.js          2.72 KiB
11:26:57.612 | .svelte-kit/output/server/chunks/notifications-8770e658.js     3.40 KiB
11:26:57.612 | .svelte-kit/output/server/chunks/error-d6835b02.js             0.74 KiB
11:26:57.612 | .svelte-kit/output/server/chunks/index-8ac9f8a7.js             2.26 KiB
11:26:57.612 | .svelte-kit/output/server/chunks/firebase.config-8dbe1004.js   0.50 KiB
11:26:57.612 | .svelte-kit/output/server/chunks/forgot-password-8ae1f33f.js   1.16 KiB
11:26:57.613 | .svelte-kit/output/server/chunks/createlistings-e5b56213.js    5.14 KiB
11:26:57.613 | .svelte-kit/output/server/chunks/_listingId_-edc17f25.js       17.46 KiB
11:26:57.613 | .svelte-kit/output/server/chunks/stores-b1c3cbc1.js            0.60 KiB
11:26:57.613 | .svelte-kit/output/server/chunks/_catName_-3fb45bc7.js         2.13 KiB
11:26:57.613 | .svelte-kit/output/server/chunks/ListingItem-631be943.js       2.14 KiB
11:26:57.614 | .svelte-kit/output/server/chunks/_landLordId_-6b759adb.js      1.76 KiB
11:26:57.615 | .svelte-kit/output/server/chunks/profile-377f15ab.js           3.43 KiB
11:26:57.615 | .svelte-kit/output/server/chunks/offers-d0783453.js            2.05 KiB
11:26:57.615 | .svelte-kit/output/server/chunks/signin-92982ac5.js            2.15 KiB
11:26:57.616 | .svelte-kit/output/server/chunks/OAuth-3653b5dc.js             1.20 KiB
11:26:57.622 | .svelte-kit/output/server/chunks/signup-4db56528.js            2.25 KiB
11:26:57.622 | .svelte-kit/output/server/chunks/_listingId_-3cb178df.js       5.45 KiB
11:26:57.623 |  
11:26:57.623 | Run npm run preview to preview your production build locally.
11:26:57.637 |  
11:26:57.637 | > Using @sveltejs/adapter-auto
11:26:57.773 | > .svelte-kit/output/server/chunks/createlistings-e5b56213.js:6:7: warning: Ignoring this import because "node_modules/uuid/wrapper.mjs" was marked as having no side effects
11:26:57.774 | 6 │ import "uuid";
11:26:57.774 | ╵        ~~~~~~
11:26:57.774 | node_modules/uuid/package.json:19:2: note: "sideEffects" is false in the enclosing "package.json" file
11:26:57.774 | 19 │   "sideEffects": false,
11:26:57.775 | ╵   ~~~~~~~~~~~~~
11:26:57.775 |  
11:26:57.781 | > .svelte-kit/output/server/chunks/_listingId_-3cb178df.js:7:7: warning: Ignoring this import because "node_modules/uuid/wrapper.mjs" was marked as having no side effects
11:26:57.782 | 7 │ import "uuid";
11:26:57.782 | ╵        ~~~~~~
11:26:57.782 | node_modules/uuid/package.json:19:2: note: "sideEffects" is false in the enclosing "package.json" file
11:26:57.782 | 19 │   "sideEffects": false,
11:26:57.783 | ╵   ~~~~~~~~~~~~~
11:26:57.783 |  
11:26:58.075 | ✔ done
11:26:58.244 | Detected Serverless Functions in ".vercel_build_output"
11:26:58.244 | Detected Static Assets in ".vercel_build_output"
11:26:58.244 | Detected Routes Configuration in ".vercel_build_output"
11:26:58.280 | Uploading build outputs...
11:26:59.061 | Deploying build outputs...
11:27:00.611 | Build completed. Populating build cache...
11:27:08.889 | Uploading build cache [27.18 MB]...
11:27:09.954 | Build cache uploaded: 1.066s
11:27:09.999 | Done with "package.json"
```

**Comment by rcapdepaula** [comment]
> > https://vercel.com/docs/concepts/deployments/logs#function-logs
> 
> My Build log:
> 
> ## Cloning github.com/rcapdepaula/svelte-house-marketplace (Branch: master, Commit: 95d97bc)
> ```
> 11:26:43.097 | Cloning completed: 963.92ms
> 11:26:43.129 | Analyzing source code...
> 11:26:43.378 | Installing build runtime...
> 11:26:45.784 | Build runtime installed: 2.405s
> 11:26:46.111 | Looking up build cache...
> 11:26:48.199 | Build cache downloaded [27.18 MB]: 1840.468ms
> 11:26:48.378 | Detected package.json
> 11:26:48.378 | Installing dependencies...
> 11:26:48.380 | Detected `package-lock.json` generated by npm 7...
> 11:26:49.340 |  
> 11:26:49.341 | up to date in 674ms
> 11:26:49.341 |  
> 11:26:49.341 | 9 packages are looking for funding
> 11:26:49.342 | run `npm fund` for details
> 11:26:49.613 | Running "npm run build"
> 11:26:50.010 |  
> 11:26:50.011 | > house-marketplace@0.0.1 build
> 11:26:50.011 | > svelte-kit build
> 11:26:50.011 |  
> 11:26:50.415 | vite v2.7.4 building for production...
> 11:26:50.528 | transforming...
> 11:26:52.953 | 2:26:52 PM [vite-plugin-svelte] /vercel/path0/node_modules/svelte-slidy/src/Slidy.svelte:4:4 A11y: Redundant role 'region'
> 11:26:52.954 | 2:
> 11:26:52.954 | 3: <section
> 11:26:52.955 | 4:     role="region"
> 11:26:52.955 | ^
> 11:26:52.955 | 5:     tabindex="0"
> 11:26:52.956 | 6:     aria-label="Slidy"
> 11:26:56.078 | ✓ 86 modules transformed.
> 11:26:56.398 | rendering chunks...
> 11:26:56.754 | .svelte-kit/output/client/_app/manifest.json                                                7.49 KiB
> 11:26:56.758 | .svelte-kit/output/client/_app/pages/__layout.svelte-e8b23226.js                            5.35 KiB / gzip: 2.25 KiB
> 11:26:56.759 | .svelte-kit/output/client/_app/pages/index.svelte-98dcf1c6.js                               3.81 KiB / gzip: 1.81 KiB
> 11:26:56.759 | .svelte-kit/output/client/_app/pages/forgot-password.svelte-c35a4588.js                     1.99 KiB / gzip: 1.06 KiB
> 11:26:56.760 | .svelte-kit/output/client/_app/start-475ce09b.js                                            22.14 KiB / gzip: 7.29 KiB
> 11:26:56.760 | .svelte-kit/output/client/_app/pages/category/_catName_.svelte-a6e0295f.js                  3.69 KiB / gzip: 1.66 KiB
> 11:26:56.760 | .svelte-kit/output/client/_app/pages/category/_id_/_listingId_.svelte-55d12197.js           9.50 KiB / gzip: 3.86 KiB
> 11:26:56.761 | .svelte-kit/output/client/_app/pages/contact/_landLordId_.svelte-f1cc8ab5.js                2.84 KiB / gzip: 1.42 KiB
> 11:26:56.761 | .svelte-kit/output/client/_app/pages/createlistings.svelte-dafddd5d.js                      13.00 KiB / gzip: 4.74 KiB
> 11:26:56.762 | .svelte-kit/output/client/_app/pages/profile.svelte-d1420ff8.js                             6.29 KiB / gzip: 2.83 KiB
> 11:26:56.762 | .svelte-kit/output/client/_app/pages/offers.svelte-0a37f362.js                              3.85 KiB / gzip: 1.73 KiB
> 11:26:56.762 | .svelte-kit/output/client/_app/pages/signin.svelte-92fb0a5e.js                              3.23 KiB / gzip: 1.51 KiB
> 11:26:56.763 | .svelte-kit/output/client/_app/pages/signup.svelte-5bb50249.js                              3.54 KiB / gzip: 1.62 KiB
> 11:26:56.763 | .svelte-kit/output/client/_app/pages/_editListing_/_listingId_.svelte-daa98cd0.js           13.12 KiB / gzip: 4.79 KiB
> 11:26:56.763 | .svelte-kit/output/client/_app/chunks/singletons-12a22614.js                                0.05 KiB / gzip: 0.06 KiB
> 11:26:56.763 | .svelte-kit/output/client/_app/chunks/preload-helper-ec9aa979.js                            0.51 KiB / gzip: 0.36 KiB
> 11:26:56.763 | .svelte-kit/output/client/_app/chunks/firebase.config-0035150b.js                           0.37 KiB / gzip: 0.27 KiB
> 11:26:56.764 | .svelte-kit/output/client/_app/chunks/notifications-86bae1f2.js                             0.57 KiB / gzip: 0.35 KiB
> 11:26:56.764 | .svelte-kit/output/client/_app/chunks/stores-cd0eaa18.js                                    0.38 KiB / gzip: 0.23 KiB
> 11:26:56.764 | .svelte-kit/output/client/_app/chunks/ListingItem-58cec434.js                               4.23 KiB / gzip: 1.70 KiB
> 11:26:56.764 | .svelte-kit/output/client/_app/chunks/navigation-51f4a605.js                                0.11 KiB / gzip: 0.12 KiB
> 11:26:56.764 | .svelte-kit/output/client/_app/chunks/OAuth-6b168417.js                                     1.61 KiB / gzip: 0.87 KiB
> 11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/__layout.svelte-8926c4e3.css                    0.35 KiB / gzip: 0.24 KiB
> 11:26:56.765 | .svelte-kit/output/client/_app/assets/start-61d1577b.css                                    0.16 KiB / gzip: 0.15 KiB
> 11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/category/_catName_.svelte-c2348a6d.css          0.04 KiB / gzip: 0.06 KiB
> 11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/forgot-password.svelte-2470cbe0.css             0.20 KiB / gzip: 0.15 KiB
> 11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/createlistings.svelte-57eb0c3e.css              0.08 KiB / gzip: 0.09 KiB
> 11:26:56.765 | .svelte-kit/output/client/_app/assets/pages/index.svelte-be82b0ef.css                       0.76 KiB / gzip: 0.34 KiB
> 11:26:56.766 | .svelte-kit/output/client/_app/assets/vendor-5b2b3803.css                                   3.52 KiB / gzip: 0.79 KiB
> 11:26:56.766 | .svelte-kit/output/client/_app/assets/OAuth-b2f14544.css                                    0.41 KiB / gzip: 0.20 KiB
> 11:26:56.766 | .svelte-kit/output/client/_app/assets/pages/offers.svelte-ed65610e.css                      0.12 KiB / gzip: 0.12 KiB
> 11:26:56.766 | .svelte-kit/output/client/_app/assets/pages/category/_id_/_listingId_.svelte-9a790867.css   0.12 KiB / gzip: 0.12 KiB
> 11:26:56.766 | .svelte-kit/output/client/_app/assets/pages/signup.svelte-30e18588.css                      0.55 KiB / gzip: 0.29 KiB
> 11:26:56.767 | .svelte-kit/output/client/_app/error.svelte-bcee5e53.js                                     1.56 KiB / gzip: 0.75 KiB
> 11:26:56.770 | .svelte-kit/output/client/_app/chunks/leaflet-src-9525ae07.js                               140.07 KiB / gzip: 40.61 KiB
> 11:26:56.779 | .svelte-kit/output/client/_app/chunks/vendor-ec885d3a.js                                    455.41 KiB / gzip: 108.33 KiB
> 11:26:56.787 | vite v2.7.4 building SSR bundle for production...
> 11:26:56.887 | transforming...
> 11:26:57.398 | 2:26:57 PM [vite-plugin-svelte] /vercel/path0/node_modules/svelte-slidy/src/Slidy.svelte:4:4 A11y: Redundant role 'region'
> 11:26:57.398 | 2:
> 11:26:57.398 | 3: <section
> 11:26:57.399 | 4:     role="region"
> 11:26:57.399 | ^
> 11:26:57.399 | 5:     tabindex="0"
> 11:26:57.399 | 6:     aria-label="Slidy"
> 11:26:57.546 | ✓ 53 modules transformed.
> 11:26:57.589 | rendering chunks...
> 11:26:57.609 | .svelte-kit/output/server/app.js                               0.09 KiB
> 11:26:57.609 | .svelte-kit/output/server/chunks/app-18f56d88.js               21.48 KiB
> 11:26:57.611 | .svelte-kit/output/server/chunks/__layout-2a587688.js          2.72 KiB
> 11:26:57.612 | .svelte-kit/output/server/chunks/notifications-8770e658.js     3.40 KiB
> 11:26:57.612 | .svelte-kit/output/server/chunks/error-d6835b02.js             0.74 KiB
> 11:26:57.612 | .svelte-kit/output/server/chunks/index-8ac9f8a7.js             2.26 KiB
> 11:26:57.612 | .svelte-kit/output/server/chunks/firebase.config-8dbe1004.js   0.50 KiB
> 11:26:57.612 | .svelte-kit/output/server/chunks/forgot-password-8ae1f33f.js   1.16 KiB
> 11:26:57.613 | .svelte-kit/output/server/chunks/createlistings-e5b56213.js    5.14 KiB
> 11:26:57.613 | .svelte-kit/output/server/chunks/_listingId_-edc17f25.js       17.46 KiB
> 11:26:57.613 | .svelte-kit/output/server/chunks/stores-b1c3cbc1.js            0.60 KiB
> 11:26:57.613 | .svelte-kit/output/server/chunks/_catName_-3fb45bc7.js         2.13 KiB
> 11:26:57.613 | .svelte-kit/output/server/chunks/ListingItem-631be943.js       2.14 KiB
> 11:26:57.614 | .svelte-kit/output/server/chunks/_landLordId_-6b759adb.js      1.76 KiB
> 11:26:57.615 | .svelte-kit/output/server/chunks/profile-377f15ab.js           3.43 KiB
> 11:26:57.615 | .svelte-kit/output/server/chunks/offers-d0783453.js            2.05 KiB
> 11:26:57.615 | .svelte-kit/output/server/chunks/signin-92982ac5.js            2.15 KiB
> 11:26:57.616 | .svelte-kit/output/server/chunks/OAuth-3653b5dc.js             1.20 KiB
> 11:26:57.622 | .svelte-kit/output/server/chunks/signup-4db56528.js            2.25 KiB
> 11:26:57.622 | .svelte-kit/output/server/chunks/_listingId_-3cb178df.js       5.45 KiB
> 11:26:57.623 |  
> 11:26:57.623 | Run npm run preview to preview your production build locally.
> 11:26:57.637 |  
> 11:26:57.637 | > Using @sveltejs/adapter-auto
> 11:26:57.773 | > .svelte-kit/output/server/chunks/createlistings-e5b56213.js:6:7: warning: Ignoring this import because "node_modules/uuid/wrapper.mjs" was marked as having no side effects
> 11:26:57.774 | 6 │ import "uuid";
> 11:26:57.774 | ╵        ~~~~~~
> 11:26:57.774 | node_modules/uuid/package.json:19:2: note: "sideEffects" is false in the enclosing "package.json" file
> 11:26:57.774 | 19 │   "sideEffects": false,
> 11:26:57.775 | ╵   ~~~~~~~~~~~~~
> 11:26:57.775 |  
> 11:26:57.781 | > .svelte-kit/output/server/chunks/_listingId_-3cb178df.js:7:7: warning: Ignoring this import because "node_modules/uuid/wrapper.mjs" was marked as having no side effects
> 11:26:57.782 | 7 │ import "uuid";
> 11:26:57.782 | ╵        ~~~~~~
> 11:26:57.782 | node_modules/uuid/package.json:19:2: note: "sideEffects" is false in the enclosing "package.json" file
> 11:26:57.782 | 19 │   "sideEffects": false,
> 11:26:57.783 | ╵   ~~~~~~~~~~~~~
> 11:26:57.783 |  
> 11:26:58.075 | ✔ done
> 11:26:58.244 | Detected Serverless Functions in ".vercel_build_output"
> 11:26:58.244 | Detected Static Assets in ".vercel_build_output"
> 11:26:58.244 | Detected Routes Configuration in ".vercel_build_output"
> 11:26:58.280 | Uploading build outputs...
> 11:26:59.061 | Deploying build outputs...
> 11:27:00.611 | Build completed. Populating build cache...
> 11:27:08.889 | Uploading build cache [27.18 MB]...
> 11:27:09.954 | Build cache uploaded: 1.066s
> 11:27:09.999 | Done with "package.json"
> ```

```
Function Details
Failed Requests

None

Runtime

Node.js 14.x

Region

Washington, D.C., USA

Memory Size

1024 MB

Size

0.33 MB

Maximum Execution Duration

10 seconds
```

**Comment by bluwy** [comment]
@rcapdepaula Is there a way to get the stack trace for `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined` error specifically, so we know where in code the error happened.

**Comment by benmccann** [comment]
I'm guessing not since the function logs he posted in the last comment say "Failed Requests None"

**Comment by rcapdepaula** [comment]
> stack trace

The log of the function error:

```
2022-01-23T15:02:49.263Z	a4471017-756f-4d2e-8b64-a8b224690806	ERROR	TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at new NodeError (internal/errors.js:322:7)
    at fileURLToPath (internal/url.js:1370:11)
    at node_modules/@firebase/firestore/dist/index.node.mjs (/var/task/index.js:29721:53)
    at __init (/var/task/index.js:9:50)
    at node_modules/firebase/firestore/dist/index.mjs (/var/task/index.js:31634:5)
    at __init (/var/task/index.js:9:50)
    at .svelte-kit/output/server/chunks/index-8ac9f8a7.js (/var/task/index.js:31681:5)
    at __init (/var/task/index.js:9:50)
    at /var/task/index.js:38941:70
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by benmccann** [comment]
Thanks for providing that. Given that the stack trace is coming from Firestore, it's pretty unclear that there would be any bug in SvelteKit. It's more likely to be either a usage issue or a bug in Firestore. Perhaps it can't find your `firebase.config.js` in production?

I'm going to go ahead and close this since it doesn't look like a bug in SvelteKit. If you can provide more info showing SvelteKit is at fault I'll take a look

**Comment by rcapdepaula** [comment]
> Thanks for providing that. Given that the stack trace is coming from Firestore, it's pretty unclear that there would be any bug in SvelteKit. It's more likely to be either a usage issue or a bug in Firestore. Perhaps it can't find your `firebase.config.js` in production?
> 
> I'm going to go ahead and close this since it doesn't look like a bug in SvelteKit. If you can provide more info showing SvelteKit is at fault I'll take a look

I will never use firestone again. Thanks so much for the attention!

**Comment by monarchwadia** [comment]
So glad I found this. 

I have the same issue described in the first comment on this thread.... when I refresh, the error disappears for me, too. 

Here's my stack trace

```
[GET] /__data.json
13:14:32:19
Function Status:500
Edge Status:500
Duration:12.87 ms
Init Duration: N/A
Memory Used:74 MB
ID:cle1::iad1::d85qc-1652980472188-588c23b13d80
User Agent:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0

2022-05-19T17:14:32.223Z	274bc6a8-e7b3-47d6-8804-0b1ca866e35b	ERROR	TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
  at new NodeError (internal/errors.js:322:7)
  at fileURLToPath (internal/url.js:1370:11)
  at .svelte-kit/output/server/entries/endpoints/index.ts.js (/var/task/index.js:10062:47)
  at __init (/var/task/index.js:8:56)
  at /var/task/index.js:12595:53
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async resolve (/var/task/index.js:12406:55)
  at async respond (/var/task/index.js:12378:22)
  at async Server.serverless_default (/var/task/index.js:12655:20)
```

Repro deployment: https://monarchwadia-518v3wi7g-monarchwadia.vercel.app

Repro codebase: https://github.com/monarchwadia/monarchwadia.com/tree/328c30187f38c2a6de0a4274fc6134ded6ed3354

Do you have any insights into what might be causing this?

**Comment by rcapdepaula** [comment]
Hello @monarchwadia! Put your project on Vercel. And install the package.json again or create a new project from zero and put your code in it. For me, I created a new project from zero and put my code in it. The most important thing is to use Vercel, which embraced the svelte project.

**Comment by monarchwadia** [comment]
Hi @rcapdepaula , thanks! My project is already deployed on Vercel; am I missing something? Are you recommending that I somehow use [this package](https://www.npmjs.com/package/vercel) ?

**Comment by rcapdepaula** [comment]
No, I just install svelte, I'm my case sveltekit again in another project and I make a new version of my project that isn't working

**Comment by monarchwadia** [comment]
Okay I have some more info. 
Inside svelte.config.js, I was configuring Vite with aliases

```js
const config = {
  // ...
	kit: {
		adapter: adapter(),
		vite: {
			resolve: {
				alias: {
					'src': path.resolve(__dirname, './src')
				}
			}
		}
	},
 // ..
}
```

But since SvelteKit uses modules, `__dirname` is undefined. In order to get it, I'm doing the following near the top of my file, right below my imports...

```js
const __filename = fileURLToPath(import.meta.url); // this errors out
const __dirname = dirname(__filename);
```

The function `fileURLToPath` does not like undefineds. I tested it in the repl, and it spat out the following error..

```js
> const { fileURLToPath } = require("url")
undefined
> fileURLToPath(undefined)
Uncaught:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of URL. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at fileURLToPath (node:internal/url:1417:11) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

This might not be a sveltekit issue exactly, but I'll report back on what I did to solve it.

**Comment by rcapdepaula** [comment]
My svelte.config:

```
import adapter from '@sveltejs/adapter-auto'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		vite: {
			server: {
				fs: true
			}
		},
		adapter: adapter()
	}
}

export default config
```
