### ISSUE TITLE
Svelte/TailwindCSS/Rollup template dependencies broken

### ISSUE THREAD

**Issue by nikokozak** [sveltejs/kit#3444]
### Describe the bug

After a fresh installation following the docs, using the following settings:
`application type: Svelte`
`template: TailwindCSS`
`bundler: Rollup`
and upon running `npm run dev`, the server crashes throwing an error. 

This is because the dependencies listed in the template pulled by the installer (`Axelen123/svelte-tailwind-template#rollup`) lists incompatible dependencies.

To newer users wishing to use the template, this issue prevents all usage of SvelteKit.

### Reproduction

`npm init svelte@next app`

`Select application type: Svelte`
`Select template: TailwindCSS`
`Select bundler: Rollup`

`npm run dev`

### Logs

```shell
[!] Error: Package subpath './compiler.js' is not defined by "exports" in /Users/niko/Documents/Code/JS/logros/node_modules/svelte/package.json
Error: Package subpath './compiler.js' is not defined by "exports" in /Users/niko/Documents/Code/JS/logros/node_modules/svelte/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:703:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/niko/Documents/Code/JS/logros/node_modules/rollup-plugin-svelte/index.js:11:4)

ERROR: "autobuild" exited with 1.
```

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 1.88 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Safari: 14.1.1
  npmPackages:
    svelte: ^3.0.0 => 3.46.2
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Some system should be implemented for ensuring that templates pulled for certain SvelteKit configurations have compatible (or the latest versions of) dependencies.

I'm not entirely sure what dependency version is causing this, but found the following [SO question](https://stackoverflow.com/questions/66965954/build-error-after-updating-svelte-package-subpath-compiler-js-is-not-define) that puts the blame on the `rollup-plugin-svelte` version being incompatible with the `svelte` version.

In the template pulled by the installer, the versions are as follows:
```json
"rollup-plugin-svelte": "^5.0.3",
"svelte": "^3.0.0"
```

**Comment by pixelmund** [comment]
I tried to reproduce this, but it seems like you're running `npm init svelte` instead of `npm init svelte@next`, because the options you get are not from the `next` version.

**Comment by Conduitry** [comment]
Yes, this is https://github.com/Axelen123/create-svelte-site and not `create-svelte@next`.

**Comment by nikokozak** [comment]
I'm sorry, but this isn't in fact the case.

I've gone back through the output and found this: 
```
found matching commit hash: ed3ede9048aa523b641b834f0355080fde3e5e34
/Users/niko/.degit/github/Axelen123/svelte-tailwind-template/ed3ede9048aa523b641b834f0355080fde3e5e34.tar.gz already exists locally
extracting /Users/niko/.degit/github/Axelen123/svelte-tailwind-template/ed3ede9048aa523b641b834f0355080fde3e5e34.tar.gz to logros
cloned Axelen123/svelte-tailwind-template#rollup to logros
```

Which I guess means the installer isn't pulling fresh templates because it found one locally that I must've used quite a while ago. 

Is there any way to get around this? How do we clear this cache so that users don't have to do so manually?

**Comment by nikokozak** [comment]
Even after clearing out the `./degit` hash the problem persists. So evidently there's some value cached somewhere as part of the install that keeps pulling an old version.

**Comment by nikokozak** [comment]
Solved: `create-svelte` globally was the wrong version, updating it fixed the template pulled.
