### ISSUE TITLE
Error rendering route: Adapters should call app.render({ url, method, headers, rawBody })

### ISSUE THREAD

**Issue by 7Hazard** [sveltejs/kit#3476]
### Describe the bug

Locally dev and preview works fine, it even build fine for Cloudlfare Pages.
However, when attempting to access the page, the following error is displayed, with status code 500:
`Error rendering route: Adapters should call app.render({ url, method, headers, rawBody })`

Im not sure if I was able to pinpoint where the issue lies, but when going back from `next (1.0.0-next.8)` to `1.0.0-next.7` would make accessing properly again.

### Reproduction

I had the following `svelte.config.js`
```
import cloudflare from '@sveltejs/adapter-cloudflare';
import preprocess from 'svelte-preprocess';

export default {
	preprocess: preprocess(),
	kit: {
		target: '#svelte',
		adapter: cloudflare({
			// any esbuild options
		})
	}
};
```
Building for version `next (1.0.0-next.8)` on Cloudflare Pages and deploying it, would result in the non-functional site.

### Logs

```shell
`Error rendering route: Adapters should call app.render({ url, method, headers, rawBody })`
```

### System Info

```shell
npx: installed 1 in 2.476s

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 12.00 GB / 31.94 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-cloudflare: 1.0.0-next.7 => 1.0.0-next.7
    @sveltejs/kit: next => 1.0.0-next.232
    svelte: ^3.44.0 => 3.46.2
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
We need a complete reproduction. Please also make sure that you are on the latest version of Kit and the Cloudflare adapter - according to your system info section, neither of those are the latest version in your app.

**Comment by CrzyMan** [comment]
I was also experiencing this error. I was able to resolve it by updating "@sveltejs/kit" to "^1.0.0-next.239", "@sveltejs/adapter-cloudflare" to "^1.0.0-next.8", and Node to v16.13.2

**Comment by jordanful** [comment]
I ran into the same issue deploying to Netlify and downgrading to Sveltekit to `"^1.0.0-next.239"` fixed the issue. Thank you.

**Comment by lennartvanlaake** [comment]
Had a quick look in the compiled code to see if I could figure it out, but it seems like the error is caused by a check for a 'request' parameter to have a certain format:
In my app.js:
`
  class App {                                                                                                                               
       ...                                                                                                             
                                                                                                                       
      render(request, {                                                                                                                       
              prerender                                                                                                                             
      } = {}) {           
      if (Object.keys(request).sort().join() !== "headers,method,rawBody,url") {                                                            
              debugger;                                                                                                                     
              throw new Error("Adapters should call app.render({ url, method, headers, rawBody })");                                        
      }     
....
 } 
}       
`


This is being called in this bit in the handler-[some hash].js


`

 /** @type {import('polka').Middleware} */                                                                                                 
  const ssr = async (req, res) => {                                                                                                         
          let request;                                                                                                                      
                                                                                                                                            
          try {                                                                                                                             
                  request = await getRequest(origin || get_origin(req.headers), req);                                                       
          } catch (err) {                                                                                                                   
                  res.statusCode = err.status || 400;                                                                                       
                  return res.end(err.reason || 'Invalid request body');                                                                     
          }                                                                                                                                 
            // this is an instance of Appv                                                                                                                   
          setResponse(res, await app.render(request));                                                                                      
  };      


`

**Comment by 7Hazard** [comment]
It appears that upgrading to a later sveltekit version fixes it
