### ISSUE TITLE
adapter-node assuming https eventhough url is http://localhost:3000

### ISSUE THREAD

**Issue by andreasnuesslein** [sveltejs/kit#3481]
### Describe the bug

Hey all :wave: ,

since `adapter-node ~1.0.0-next.64` or `adapter-node ~1.0.0-next.65` the internal fetch assumes I'm on https, even though my base url is http://localhost:3000.

In adapter-node ~1.0.0-next.63 it still worked, and I think the following change is responsible for my problem:

https://github.com/sveltejs/kit/commit/ee906a3b2b103e4523eb1b6bb13f04d03eb35238#diff-216dce32a326b5829e531e0315d25a9e5feaab9175dc9a489d3a7d498afe63d4R72

This is what I get:
```
$ node build/index.js 
Listening on 0.0.0.0:3000
FetchError: request to https://localhost:3000/api/pprofiles.php?method=getFamily failed, reason: write EPROTO 140431486900160:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```

When I DO set the ORIGIN, it works
```
$ ORIGIN="http://localhost:3000" node build/index.js 
Listening on 0.0.0.0:3000
```

But it seems like the educated guess (`protocol_header && headers[protocol_header]`) is not working properly.

### Reproduction

I understand the point of this.

Please forgive me, but I don't have the time right now :(

If that means you'll just close the issue, so be it. I still thought it might help to at least mention the situation. Maybe it'll help.

### System Info

```shell
09:23:14 [0] nuts@t14.t14 ~/code/airi/airi.radio main( u=)*+
$ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 1022.44 MB / 30.59 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 8.1.2 - /usr/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Chromium: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    @sveltejs/adapter-node: ~1.0.0-next.66 => 1.0.0-next.66 
    @sveltejs/kit: ^1.0.0-next.235 => 1.0.0-next.235 
    svelte: ^3.46.2 => 3.46.2
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior. In production, your apps are generally served with an HTTPS proxy sitting in front of them. `ORIGIN` and the other runtime environment variables for the Node adapter are intended for the situations where this assumption is not correct.

**Comment by andreasnuesslein** [comment]
okay :+1:  thanks for getting back to me on that.
