### ISSUE TITLE
Endpoint Response breaks with "content-type: application/json" 

### ISSUE THREAD

**Issue by nikosgpet** [sveltejs/kit#3505]
### Describe the bug

Using the new api described in #3384, when I create an API endpoint returning a Response, it breaks in Cloudflare Workers if I set `content-type: application/json` as a Response header.

I believe the reason is because it applies JSON.stringify to the body of the response. However the body of the response being a ReadableStream, it breaks returning an object `{ locked: false }`.

### Reproduction

I believe the culprit is found here: https://github.com/sveltejs/kit/blob/ee906a3b2b103e4523eb1b6bb13f04d03eb35238/packages/kit/src/runtime/server/endpoint.js#L86

Normally the control `is_pojo(body)` shouldn't allow the code to reach here, however the control doesn't work correctly in Cloudflare Workers. More specifically it fails here:
https://github.com/sveltejs/kit/blob/ee906a3b2b103e4523eb1b6bb13f04d03eb35238/packages/kit/src/runtime/server/endpoint.js#L119

In Cloudflare `body[Symbol.toStringTag]` returns `undefined`. Replacing the control with `body instanceof ReadableStream` works in Cloudflare Workers.

### System Info

```shell
Binaries:
    Node: 16.10.0 - ~/.volta/tools/image/node/16.10.0/bin/node
    Yarn: 3.1.0 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.3.1 - ~/.volta/tools/image/npm/8.3.1/bin/npm
  npmPackages:
    @sveltejs/adapter-cloudflare: ^1.0.0-next.8 => 1.0.0-next.8 
    @sveltejs/kit: ^1.0.0-next.239 => 1.0.0-next.239 
    svelte: ^3.46.2 => 3.46.2 
    vite: ^2.7.12 => 2.7.12
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
by all means, thank you! note that `body instanceof ReadableStream` won't work in environments that don't implement `ReadableStream`, so it probably needs to be `typeof ReadableStream !== undefined && body instanceof ReadableStream` (and if you can cache the `typeof` check, even better)

**Comment by vicky1999** [comment]
okay sure.  is there any example to test the issue?

**Comment by Rich-Harris** [comment]
the test would go in this section https://github.com/sveltejs/kit/blob/27239fa1f3f502bd7cc5e51d3593beb302ce487f/packages/kit/test/apps/basics/test/test.js#L349

**Comment by vicky1999** [comment]
Thanks.

**Comment by vicky1999** [comment]
I have made the code changes.  but, to check whether the code change is working,  I need to reproduce the issue.  so, can I get the steps to reproduce the issue?

**Comment by bluwy** [comment]
@vicky1999  Not sure how easy it is to reproduce this, since it happens on cloudflare specifically, but as long as the test pass with your changes. I think that's good enough.

**Comment by vicky1999** [comment]
okay.  Thanks.  I tried to run the test cases.  all of them were passing.
