### ISSUE TITLE
Svelte is reusing component with its state on different pages using the same route

### ISSUE THREAD

**Issue by plrenaudin** [sveltejs/kit#3506]
### Describe the bug

Svelte routing reuses the component with its local state.
I have a route (/counter/[id]) That is using the sveltekit demo counter component.
Navigating from one counter/[id] page to another keep the state of the counter component
The only way to make it work as I want is to use the `target="_self"` attribute on the link which is forcing a full page reload (not ideal)

Sorry if this is expected behavior, it looks like a bug to me.

### Reproduction

Demo: https://routing-issue-theta.vercel.app/
Repo: https://github.com/plrenaudin/svelte-routing-issue

### System Info

```shell
System:
    OS: Linux 5.14 Solus 4.3
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 1.73 GB / 15.46 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 7.24.2 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Brave Browser: unknown
    Firefox: 96.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.14 
    @sveltejs/kit: next => 1.0.0-next.239 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
This is expected behaviour - it allows you more control over the navigation (for example, animating changes). You can use `afterNavigate` if you need to reset state etc https://kit.svelte.dev/docs#modules-$app-navigation

**Comment by plrenaudin** [comment]
Thanks a lot for the quick response! So there is no generic way to force component remount on a page change or do I have to implement a reset on `afterNavigate` for every single component used in the page?

**Comment by Rich-Harris** [comment]
Only the ones that need their state to be reset, but yes, currently you can't force a remount

**Comment by plrenaudin** [comment]
Thanks a mil @Rich-Harris I'll find a way. 

Thanks a lot for Svelte, it keeps getting better and better :+1:

**Comment by johnnysprinkles** [comment]
Is there any chance we can reconsider this issue? Resetting the state in `afterNavigate` is more error prone than simply tearing the whole component down and remounting it. It just strikes me as a little weird that what happens when you "arrive at "/id/4" is different depending on if you came from "/foo" or "/id/3". I do get the point about performance and animating between, so any change would need to be opt in of course.

**Comment by johnnysprinkles** [comment]
Here's the workaround I'm using now, not so bad but would be cool to have something built-in. I'm just making my route component be a thin shell that displays the real component in a key block, so like this (I renamed my real thing as if it's a Todo app, but otherwise my use is identical).

```svelte
<script>
  import { afterNavigate } from '$app/navigation'
  import { base } from '$app/paths'

  import TodoPage from '$components/routes/TodoPage.svelte'

  let todoId

  afterNavigate(({from, to}) => {
    let path = to.pathname
    if (base) {
      path = path.substring(base.length)
    }
    let m = path.match(/^\/todo\/(\d+)$/)
    todoId = m[1]
  })
</script>

{#if todoId}
  {#key todoId}
    <TodoPage {todoId} />
  {/key}
{/if}

```

**Comment by Rich-Harris** [comment]
Opened a discussion about this here: https://github.com/sveltejs/kit/discussions/5007
