### ISSUE TITLE
EndpointOutput is no longer typed. Maybe add the optional typing back in.

### ISSUE THREAD

**Issue by cdcarson** [sveltejs/kit#3512]
### Describe the problem

[This commit](https://github.com/sveltejs/kit/pull/3455) removed the generic typing for `EndpointOutput`. It used to be:
```ts
export interface EndpointOutput<Body extends DefaultBody = DefaultBody> {
	status?: number;
	headers?: Headers | Partial<ResponseHeaders>;
	body?: Body;
}
```
It now is:
```ts
export interface EndpointOutput {
	status?: number;
	headers?: Headers | Partial<ResponseHeaders>;
	body?: Body;
}
```
I had been using the typing of `EndpointOutput` to enforce  the endpoint's contract. For example...
```ts
// foo.json.ts
import type { MyFoo } from './types';
export const get = (): Promise<EndpointOutput<MyFoo>> => {/** return a MyFoo or else! **/}
```
Not only would I get good type-hinting while writing the endpoint code, but, later on, I could also easily look up what the endpoint was supposed to return.

Without the typing I lose both benefits.

I realize this change is part of a larger effort to move the endpoint API away from the bespoke SvelteKit types toward vanilla `Request`/`Response`. But unless the idea is to eventually do away with `EndpointOutput` entirely, I think adding the typing back in would be good idea. Once a project goes beyond a few pages and a few endpoints, this kind of typing is really handy.

### Describe the proposed solution

The (naive, untested) solution could be as simple as this:

```ts
// packages/kit/types/endpoint.d.ts
export interface EndpointOutput<T = Body> { //++ <T = Body>
  status?: number;
  headers?: Headers | Partial<ResponseHeaders>;
  body?: T;
}
```
I believe this would allow both untyped and typed code...
```ts
// untyped...
export const get = (): Promise<EndpointOutput> => {}
// typed...
export const post = (): Promise<EndpointOutput<MyFoo>> => {}
```

### Alternatives considered

1. Relax, and go with untyped endpoints.
2. Write a typed wrapper around `EndpointOutput` for my own purposes. 

### Importance

nice to have

**Comment by konstantinov90** [comment]
I had to use a `patch-package` package so that not to lose our typed endpoints, kinda like that

```
diff --git a/node_modules/@sveltejs/kit/types/endpoint.d.ts b/node_modules/@sveltejs/kit/types/endpoint.d.ts
index ace4fd1..a6305bf 100644
--- a/node_modules/@sveltejs/kit/types/endpoint.d.ts
+++ b/node_modules/@sveltejs/kit/types/endpoint.d.ts
@@ -1,18 +1,20 @@
 import { RequestEvent } from './hooks';
 import { Either, JSONString, MaybePromise, ResponseHeaders } from './helper';
 
-type Body = JSONString | Uint8Array | ReadableStream | import('stream').Readable;
+type Body<T = undefined> = T extends object ? T : (JSONString | Uint8Array | ReadableStream | import('stream').Readable);
 
-export interface EndpointOutput {
+type B = Body<boolean>;
+
+export interface EndpointOutput<T> {
 	status?: number;
 	headers?: Headers | Partial<ResponseHeaders>;
-	body?: Body;
+	body?: Body<T>;
 }
 
 export interface Fallthrough {
 	fallthrough: true;
 }
 
-export interface RequestHandler<Locals = Record<string, any>> {
-	(event: RequestEvent<Locals>): MaybePromise<Either<Response | EndpointOutput, Fallthrough>>;
+export interface RequestHandler<Locals = Record<string, any>, T> {
+	(event: RequestEvent<Locals>): MaybePromise<Either<EndpointOutput<T>, Fallthrough>>;
 }
```
