### ISSUE TITLE
Attempt to use unknown over any for public APIs

### ISSUE THREAD

**Issue by fezproof** [sveltejs/kit#3513]
### Describe the problem

I noticed when exploring the types for SvelteKit, that any tends to be used for most of the generics exposed to the user. Wouldn't it better to use `unknown` for these, as it is more type safe and robust to user error.

### Describe the proposed solution

`unknown` is described [here](https://www.typescriptlang.org/docs/handbook/2/functions.html#unknown).

The gist is that it is a more safe version of `any` as it requires users to verify what they are accessing. I may be unreasonable to change all the `any`s to `unknown`s, but changing the public APIs to use unknown would make them much safer to use.

### Importance

would make my life easier

**Comment by benmccann** [comment]
makes sense to me, but I'm not a TypeScript export. what do you think @dummdidumm @ignatiusmb ?

**Comment by dummdidumm** [comment]
This should be decided on a case by case basis, and we should strive for a good balance of strictness and pragmatism. I wouldn't want TS users to have the burden of needing to set all generics. If some people are fine with `any` they should be allowed to not pass generics.

**Comment by ignatiusmb** [comment]
Agreed. I know we've discussed this some time ago, but can't remember where exactly. I expect those that uses strict mode would just pass in their types to get the type safety. Using `unknown` would force everyone that doesn't use the generics to specify them. We are already making these generic arguments optional by specifying the default values, changing these (to `unknown`) would kind of defeats the purpose.

If we were to change this, we definitely want to make the decision before 1.0, but I don't think it's likely to happen.

**Comment by benmccann** [comment]
Thanks for taking a look guys. I'll go ahead and close this since the current state sounds intentional
