### ISSUE TITLE
[bug] `typescript-eslint` warnings show up in `svelte.config.js`

### ISSUE THREAD

**Issue by kelvindecosta** [sveltejs/kit#3514]
### Describe the bug

The skeleton project when configured with `typescript` and `eslint` run `@typescript-eslint` rules on the main configuration file, `svelte.config.js`. Although no warnings show up in the default skeleton configuration, when they do, they cannot be resolved since type annotations can only be used in TypeScript files.

### Reproduction

Example change: 

```diff
@@ -7,6 +7,10 @@ const config = {
        // for more information about preprocessors
        preprocess: preprocess(),
 
+       compilerOptions: {
+               cssHash: ({ hash, css }) => `svelte-${hash(css)}`
+       },
+
        kit: {
                adapter: adapter(),

```

[Reproduction on CodeSandbox](https://codesandbox.io/s/54dse?file=/svelte.config.js)

### Logs

The output of `npm run lint`:

```shell
/path/to/project/svelte.config.js
  11:12  warning  Missing return type on function          @typescript-eslint/explicit-module-boundary-types
  11:13  warning  Object pattern argument should be typed  @typescript-eslint/explicit-module-boundary-types

✖ 2 problems (0 errors, 2 warnings)

```

### System Info

```shell
npx: installed 1 in 1.332s

  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Memory: 873.68 MB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Brave Browser: 96.1.32.115
    Firefox: 95.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.14 
    @sveltejs/kit: next => 1.0.0-next.240 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

annoyance

### Additional Information

This is a mild annoyance.
Still, I think it could use a workaround/modification to the default `eslint` configuration in the skeleton project.

Any help is appreciated!
Thank you for your time!

**Comment by benmccann** [comment]
> type annotations can only be used in TypeScript files

I don't think that's true. You can specify types via JSDocs. Look at the code of SvelteKit itself in this repo as that's how it handles typing in all files

**Comment by kelvindecosta** [comment]
@benmccann Thank you for the response!

I understand it better now.
With JSDoc comments type annotations can be added to `svelte.config.js` even though it isn't a TypeScript file.

Although the `config` object is annotated with  `/** @type {import('@sveltejs/kit').Config} */` , the warnings still appear for some expressions within its definition.

In the example above, `config.compilerOptions.cssHash`  is appropriately typed as a `CssHashGetter` but the linter still complains about a missing return type.
