### ISSUE TITLE
Error when evaluating SSR module in dev mode

### ISSUE THREAD

**Issue by matheussouza9** [sveltejs/kit#3520]
### Describe the bug

Using sveltekit at `1.0.0-next.240` version, I get the following error with  `youtube-player` package when the page loads for the first time in dev server. In production preview server it's working.

![image](https://user-images.githubusercontent.com/6036320/150706514-df51badd-ce09-44f2-bafc-c8160e1e6358.png)

```
[vite] Error when evaluating SSR module /node_modules/.pnpm/youtube-player@5.5.2/node_modules/youtube-player/dist/index.js?v=70c987a9:
ReferenceError: exports is not defined
    at /node_modules/.pnpm/youtube-player@5.5.2/node_modules/youtube-player/dist/index.js?v=70c987a9:3:23
    at instantiateModule (/home/matheus/meetacity/node_modules/.pnpm/vite@2.7.13/node_modules/vite/dist/node/chunks/dep-f5552faa.js:60105:15)
```

But, when I refresh the page, it works.

![image](https://user-images.githubusercontent.com/6036320/150706551-b2f6e9d4-e62b-41e4-b832-e6195d2a20bf.png)

### Reproduction

- Install `svelte-youtube` package
- Create a simple page like this one below
```
<script>
    import YouTube from 'svelte-youtube'
</script>

<YouTube videoId='uQntFkK8Z54'/>
```
- Run `npm run dev -- --open`
- Go to that page and see the error
- Refresh the page and it works

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 3.37 GB / 5.79 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
Binaries:
    Node: 16.13.2 - /tmp/fnm_multishells/1514_1642986568258/bin/node
    Yarn: 1.22.17 - /tmp/fnm_multishells/128_1642985412126/bin/yarn
    npm: 8.1.2 - /tmp/fnm_multishells/1514_1642986568258/bin/npm
npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.14 
    @sveltejs/kit: next => 1.0.0-next.240 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

annoyance

**Comment by bluwy** [comment]
Sounds like https://github.com/vitejs/vite/issues/2579. Unfortunately there isn't much SvelteKit can do, other than having this fixed in Vite, so I'll close this in favour of that.

**Comment by matheussouza9** [comment]
I found the solution right here https://github.com/sveltejs/kit/issues/655#issuecomment-809714987.
I moved svelte-youtube dep from `dependencies` to `devDependencies`.
