### ISSUE TITLE
Favicon.ico Not Found

### ISSUE THREAD

**Issue by lemmon** [sveltejs/kit#3525]
### Describe the bug

Starting version 231 svelte-kit is no longer able to display static asset favicon.ico. I have previously described the issue here: https://github.com/sveltejs/kit/issues/3393#issuecomment-1017608444:

> I have [probably] the same issue, starting v 231. However, I haven't applied any special settings for kit.paths nor the adapter. Everything is set to default.
> 
> The only affected file is `favicon.ico`.
> 
> ```
> HTTP/1.1 404 Not Found
> Content-Length: 9
> ```
> 
> But the very same file renamed to `favicon2.ico` works just fine:
> 
> ```
> HTTP/1.1 200 OK
> Content-Length: 61
> ```
> 
> Every other file seems to be working just fine.

### Reproduction

https://github.com/lemmon/svelte-kit-favicon-issue

Try to load http://localhost:3000/favicon.ico -> 404 Not Found

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 407.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 88.1.19.86
    Chrome: 97.0.4692.99
    Firefox: 96.0.1
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.14 
    @sveltejs/kit: next => 1.0.0-next.240 
    svelte: ^3.44.0 => 3.46.2
```

### Severity

annoyance

**Comment by tfpgh** [comment]
> Not sure if that [line](https://github.com/sveltejs/kit/blob/8a5f5de72c7b55a3ce230c50ac904b291096da77/packages/kit/src/core/dev/plugin.js#L144) is needed.
> 
> The workaround:
> 
> ```js
> diff --git a/packages/kit/src/core/dev/plugin.js b/packages/kit/src/core/dev/plugin.js
> index f8116132..90ec560c 100644
> --- a/packages/kit/src/core/dev/plugin.js
> +++ b/packages/kit/src/core/dev/plugin.js
> @@ -141,7 +141,7 @@ export async function create_plugin(config, cwd) {
>                                 vite.middlewares.use(async (req, res) => {
>                                         try {
>                                                 if (!req.url || !req.method) throw new Error('Incomplete request');
> -                                               if (req.url === '/favicon.ico') return not_found(res);
> +                                               //if (req.url === '/favicon.ico') return not_found(res);
>  
>                                                 const base = `${vite.config.server.https ? 'https' : 'http'}://${req.headers.host}`;
> ```

[Commit](https://github.com/sveltejs/kit/commit/42fac849d856c01003b97c11cb63b3366a7d3233) that added it. Looks like a refactor though, so might have been introduced earlier.

**Comment by nhe23** [comment]
It seems like this line has always been there ... I checked the git logs all the way back to march of last year. I can't think of a good reason of why this line is needed. I don't see why SvelteKit should not support .ico files for the favicon as they are broadly used. Also the current behaviour is inconsistent as 404 is only returned in dev mode. I'll remove it and create a PR.
