### ISSUE TITLE
Examples link in Migration docs is broken

### ISSUE THREAD

**Issue by wardou2** [sveltejs/kit#3542]
### Describe the bug

In the first document in the Migration folder, kit/documentation/migrating/01-migrating.md, the link to view examples leads to a github 404 page.

### Reproduction

- Go to https://github.com/sveltejs/kit/blob/master/documentation/migrating/01-migrating.md
- Click link labeled "examples"

### System Info

```shell
n/a
```

### Severity

annoyance

### Additional Information

thanks for all your good work :) love the framework

**Comment by ignatiusmb** [comment]
Thanks for the report, I think we've moved all of them to the sites monorepo, so I've updated the link to point there instead.
