### ISSUE TITLE
SvelteKit not always triggering animations on scroll when using svelte-reveal package

### ISSUE THREAD

**Issue by DaveKeehl** [sveltejs/kit#3550]
### Describe the bug

Hi, I’m the maintainer of a small Svelte action called [svelte-reveal](https://github.com/DaveKeehl/svelte-reveal) that allows users to easily create and trigger animations on scroll. I’ve tested my package over and over with vanilla Svelte (you can also take a look at [this REPL](https://svelte.dev/repl/1cf37b0947ac46b8ae9cc791abda7159?version=3.44.1)) and it works fine. However, with SvelteKit for some reason it does not. 

By testing the action I created on SvelteKit, I've noticed that the animations do not get triggered at a hard page reload, but rather only when the project files are saved with new content. I assume this behavior might have something to do with the way SvelteKit deals with rendering (?). I've decided to create this issue with the highest severity, because at the current state it's almost impossible to preview and test scroll animations without keeping creating dummy content.

Is there anything I can do on my end? If yes, do you have an idea of what might be the root cause? 

I did some inspections and all my assets (CSS stylesheet inside the head tag, CSS classes on elements, JS bundle) seem to be correctly placed within the page.

### Reproduction

I’ve created reproduction repositories for Svelte and SvelteKit and I deployed them on Netlify and Vercel by using the same source code.

Svelte:
- [Repository](https://github.com/DaveKeehl/svelte-reveal-issue-81-svelte)
- [Deployed website](https://svelte-reveal-with-svelte.netlify.app/)

SvelteKit:
- [Repository](https://github.com/DaveKeehl/svelte-reveal-issue-81-sveltekit)
- [Deployed website (Netlify -> broken)](https://svelte-reveal-with-sveltekit.netlify.app/)
- [Deployed website (Vercel -> working fine)](https://svelte-reveal-issue-81-sveltekit-davekeehl.vercel.app/)

### System Info

```shell
System:
  OS: macOS 12.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 195.90 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
  Yarn: 1.22.17 - /usr/local/bin/yarn
  npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
Browsers:
  Chrome: 97.0.4692.99
  Edge: 97.0.1072.69
  Firefox: 93.0
  Safari: 15.2
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
Are the repros private? I'm not able to access either https://github.com/DaveKeehl/svelte-reveal-issue-81-svelte or https://github.com/DaveKeehl/svelte-reveal-issue-81-sveltekit

**Comment by DaveKeehl** [comment]
Hi Rich, thank for replying!

Sorry for the repros not being accessible, they are now back. I've also updated some links in my previous comment, because the SvelteKit project builds fine on Netlify but then returns 500 when visiting it (not sure why...). On Vercel it works fine though.

Since I opened this issue at the end of January, I was able to find a workaround [that I've also added to the documentation](https://github.com/DaveKeehl/svelte-reveal#sveltekit). It basically looks this:

```html
<script>
  import { afterUpdate } from 'svelte';

  let show = false;

  afterUpdate(() => {
    show = true;
  });
</script>

{#if show}
  <your-element-or-component />
{/if}
```

By doing this, I'm able to trigger the animations at every manual page reload, as it happens with the vanilla Svelte.
[I've also commented out this workaround in the SvelteKit repro, so you can try it out.](https://github.com/DaveKeehl/svelte-reveal-issue-81-sveltekit/blob/main/src/routes/index.svelte#L20-L29)

Do you think there's a better workaround/solution that doesn't need the users to solve this problem on their end?

**Comment by souravjamwal77** [comment]
Thanks, @DaveKeehl for your workaround. I was able to implement the transitions.

**Comment by socketopp** [comment]
Is this is related to #2759 ?

**Comment by eltigerchino** [comment]
Closing this as it is no longer reproducible
