### ISSUE TITLE
fix the flaky tests

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3552]
### Describe the bug

The tests that routinely fail on Windows — 'prefetches programmatically' and 'url-supplied anchor is ignored with onMount()' spring to mind — are a real nuisance. Getting these to pass reliably is probably the single biggest contribution someone could make relative to the development effort involved (though having said that, I've tried and failed)

### Reproduction

Open a random PR and look at the checks

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by PH4NTOMiki** [comment]
@Rich-Harris I tried experimenting with this on my Windows machine and the only way I succeeded to reliably get no errors in the tests was to lower the workers count (in the playwright config), and I guess the reason for it is that Windows is worse at dealing with CPU and RAM than the Linux/MacOS are. 
Recommended and the default amount of workers for playwright test is the half of the amount of CPU cores on the machine (source: https://github.com/microsoft/playwright/blob/512a245f135e7c2430aebc698b65a299fe07dac6/packages/playwright-test/types/test.d.ts#L628 ) and the number of the CPU cores on the Github Actions Windows machines is 2 (source: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources ) 
I have a laptop with i5 processor with 4 CPU cores and 8GB of RAM (not bad, not great obviously) and still when I run the test with 8 workers I get error and the machine slows down a bit, so no wonder the Windows VM fails.

**Comment by bluwy** [comment]
That's great info @PH4NTOMiki!  Would you like to send a PR to lower the workers count for Windows specifically?

**Comment by PH4NTOMiki** [comment]
@bluwy No problem, but I'm still not sure how much we have to lower it to make it reliable, as I said I have 4cpu cores, and the `8 workers`(which is in the config now) **always fails for me**, 
when I lowered it to 6 workers, sometimes it worked without an error, and sometimes not, so that's not viable either, 
so I guess we have to try with 4 cause that worked for me, but it's still possible for it to fail on the Github Actions VM.

Is that okay?

**Comment by PH4NTOMiki** [comment]
And I'm guessing we also have to increase timeout time for the test in the Github Action config (in the `.github/workflows/ci.yml`) because lowering the workers will slow down the tests obviously

**Comment by bluwy** [comment]
Yeah I think for 4 sounds fine, otherwise we can lower it to 2. The timeout could be adjusted later once we observe the usual time it takes perhaps.

**Comment by PH4NTOMiki** [comment]
@bluwy It passed but it detected that some tests are `flaky` which is interesting, what do you think, is this okay enough, or should we try to lower to 2?

**Comment by bluwy** [comment]
If having 2 workers reduce the flakiness, I think it's worth going there. You could also push some empty commits to verify if it's passing reliably too.

**Comment by PH4NTOMiki** [comment]
@bluwy It's pretty much the same situation for 2 and 4, I'll also check the tests, maybe there are some other error in them.

**Comment by PH4NTOMiki** [comment]
@bluwy @benmccann I see that other platforms (macos, linix)return flanky tests too, so I don't think it's that much of an issue.
