### ISSUE TITLE
App-level types

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3569]
### Describe the problem

Various types in a Kit app are app-level, by which I mean they're the same wherever they're used — `event.locals`, [`event.platform`](#3429), `session`, and arguably `stuff` (which, even though it's scoped to `load`, can be used globally as `$page.stuff` and is therefore probably best thought of and used as a consistently-shaped object, where input `stuff` and output `stuff` in `load` are both `Partial<Stuff>`).

It's wasteful, therefore, that to take full advantage of type safety it's necessary to use generic arguments everywhere:

```html
<script context="module">
  /**
   * @type {import('@sveltejs/kit').Load<{
   *   pageParams: PageParams;
   *   session: { foo: number };
   *   stuff: Stuff;
   * }, {
   *   props: Props;
   *   stuff: Stuff
   * }>} */
  export function load({...}) {...}
</script>
```

```js
/**
 * @type {import('@sveltejs/kit').RequestHandler<
 *   Locals,
 *   Platform,
 *   Output
 * >}
 */
export function get({...}) {...}
```

```js
/**
 * @type {import('@sveltejs/kit').Handle<
 *   Locals,
 *   Platform
 * >}
 */
export async function handle(...) {...}
```

> Aside: why is it `pageParams` rather than `params`?

It's also a problem that `RequestHandler` and `Handle` take positional generic arguments — it meant that the addition of `Platform` was a breaking change, for example. And why doesn't `RequestHandler` accept `params`? If we fixed that, it would be another breaking change.

With app-level types (and assuming we _were_ to treat `stuff` as app-level), the examples above could be rewritten thusly:

```html
<script context="module">
  /**
   * @type {import('@sveltejs/kit').Load<{
   *   pageParams: PageParams;
   *   props: Props;
   * }>} */
  export function load({...}) {...}
</script>
```

```js
/** @type {import('@sveltejs/kit').RequestHandler<Output>} */
export function get({...}) {...}
```

```js
/** @type {import('@sveltejs/kit').Handle} */
export async function handle(...) {...}
```

### Stretch goal — no manual typing at all

A priori, it's silly that you have to type `params` — SvelteKit already has that information. It should make it available... [somehow](https://github.com/sveltejs/kit/issues/647).

In an ideal world, it wouldn't be necessary to type `props` either — that would be inferred from the props in the `<script>` block.

In an even idealer world, TypeScript would support [implicit module typing](https://github.com/microsoft/TypeScript/issues/38511#issuecomment-983034156) and you wouldn't even have to _declare_ types.

I've no idea how feasible any of this is in the real world (maybe there's something sneaky/clever we could do with `preprocess`?) but this is the development experience we should be aiming for, even if we fall short.

### Describe the proposed solution

I'm not much of a TypeScript expert, so I don't really know _how_ we would do this. @dummdidumm had a suggestion:

```ts
// src/app.d.ts
declare namespace SvelteKit {
  export interface Session { .. }
}
```

```ts
// inside SvelteKit
declare module "$app/stores" {
  export let session: Writable<SvelteKit.Session>
}
```

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
I found a working solution which might be even more idiomatic than the namespace approach:

1. Create the following helper type
```ts
type WithAnyFallback<T> = T extends never ? any : T;
```
2. Add the following to for example `$app/stores`:
```ts
declare module '$app/stores' {
  // ..
  // @ts-ignore
  export let session: Writable<WithAnyFallback<Session>>;
}
```
`Session` is not defined anywhere so this is a type error (which is why we add `@ts-ignore` above), but thanks to the helper type it will fall back to any
3. Add the following to the user's `global.d.ts`:
```
declare module '$app/stores' {
  export interface Session {
     whatever: 'i want';
   }
}
```
TypeScript will merge the module declarations, which means `Session` is now defined, which means intellisense will now use that type instead of `any`.

So the way forward would be to
- define that helper type
- enhance `global.d.ts` in `create-svelte` with initially empty module declarations for every declaration we support to type that way with some additional comments on how to take advantage of this

**Comment by Rich-Harris** [comment]
I'd argue that the namespace is more idiomatic. It so happens that `Session` is used by `$app/stores`, but the `session` argument in `load` functions also needs to be typed, as do `locals` and `stuff` and `platform` which aren't available via a store.

Separately, I think `app.d.ts` might be a better name than `global.d.ts`, since it's the language we use elsewhere, though I don't feel strongly on that point.

**Comment by Rich-Harris** [comment]
App-level stuff is implemented in #3670, and I've updated #647 to reflect the current state of things, so I'll close this

**Comment by biltongza** [comment]
I'm having trouble with this change. The moment there is an import in my app.d.ts file, the App namespace stops getting picked up.

You can see in this screenshot (of the default skeleton app made by svelte-init) that with the import commented out, there are 3 references to `Stuff`, 4 references to `Session`, and 1 reference to `Locals` and `Platform`:
<img width="430" alt="image" src="https://user-images.githubusercontent.com/2845704/152661956-871c7e42-47e5-4db9-92f0-2e77ea98132c.png">

Yet when I uncomment it, those references go away, and it's like Typescript pretends the namespace doesn't exist:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/2845704/152661991-a19f221a-5ff2-4da8-bfd5-4442603c2d9a.png">

You get the same behaviour simply by exporting an interface in the same file:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/2845704/152662010-146cbd61-8ab6-491d-8583-5416447a3a3a.png">

However, not exporting it brings it back to life:
<img width="429" alt="image" src="https://user-images.githubusercontent.com/2845704/152662022-69c040c5-9f56-4eb2-a156-44e0176043fb.png">

**Comment by dummdidumm** [comment]
This is how typescript works. The d.ts file stops being an ambient module file as soon as you add a top level export or import, so they stop adding these types to the global types. So you should avoid doing that. Maybe we should add a comment in the starter template making this more clear. This also was why I preferred "global" as a file name.

**Comment by biltongza** [comment]
So then how do I reference a type that isn't in the same file?

**Comment by dummdidumm** [comment]
For reusable types you want to import, create a separate d.ts file.

**Comment by biltongza** [comment]
I have exactly that, but the app.d.ts doesn't know about the types in the other file, unless I am missing something.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/2845704/152676457-b761b6dc-da59-4e52-8044-d91702814bbd.png">

<img width="488" alt="image" src="https://user-images.githubusercontent.com/2845704/152676465-cdb56f0f-7485-4be0-8fd3-a179e6cb3f35.png">

**Comment by jasonlyu123** [comment]
you can import inside the namespace block. Or use `import('./thing').Manifest` as type

**Comment by biltongza** [comment]
Importing inside the namespace works! Thank you.

**Comment by jasonlyu123** [comment]
Ah. Import inside a namespace isn't right. That only works inside the `declare module`.

**Comment by AradAral** [comment]
I'm having issues with the namespacing importing as well.
This is my `app.d.ts`:
```typescript
/// <reference types="@sveltejs/kit" />
/// <reference types="$graphql/generated" />

declare namespace App {
    interface Session extends import('ts-essentials').DeepWritable<import('./someFile').SessionInfoFragment> {
        isAuthenticated: boolean;
    }
}

```
But it's not working, do generics fail to work when using dynamic imports like this?! Or I'm doing something wrong?
