### ISSUE TITLE
%svelte.assets% not being substituted correctly 

### ISSUE THREAD

**Issue by deklanw** [sveltejs/kit#3582]
### Describe the bug

Noticed my favicon was 404ing. On my `/about/` route it was requesting `/about/favicon.png` on a blogpost like `/blog/post1` it was requesting `/blog/favicon.png`.

### Reproduction

Navigate to https://kit-demo.netlify.app/about/ and observe that the favicon is missing. The request is 502ing

### System Info

```shell
n/a
```

### Severity

annoyance

### Additional Information

Probably related to recent changes https://github.com/sveltejs/kit/pull/3234

**Comment by Rich-Harris** [comment]
If your platform is adding trailing slashes to URLs, then you'll need to set `trailingSlash: 'always'` in your `svelte.config.js`

**Comment by deklanw** [comment]
@Rich-Harris thanks, that solved it. I was baited by the demo into thinking it wasn't just me being an idiot. Since you're using Netlify to host the demo for testing, maybe it should have that setting on?

**Comment by nltesown** [comment]
For a site built with adapter-static and hosted on Google Pages, setting `trailingSlash: 'always'` solves the problem. Thanks, Rich.
