### ISSUE TITLE
Svelte API 404's when hooks and SSR is used together

### ISSUE THREAD

**Issue by natefabian18** [sveltejs/kit#3616]
### Describe the bug

Using hooks.ts at all will any API endpoints to return a 404 error
The strangest part is this error only occurs when ran on a windows environment when tested on a linux environment the error does not occur

### Reproduction

https://github.com/ok-hackers/Production/tree/user_settings_page

the issue seems to have to do with hooks.ts as deleting it stops the problem from appearing
```
import { sequence } from '@sveltejs/kit/hooks';

async function SSRAll({ event, resolve }) {
	const response = await resolve(event, {
		ssr: false
	});

	return response;
}

export const handle = sequence(SSRAll);
```

### Logs

```shell
Browser Logs

404

Not found: /LearnYourNumbers/1

_get_navigation_result@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:940:11
update@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:766:38
handle_navigation@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:755:14
_navigate@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:413:23
goto@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:282:16
start@http://localhost:3000/.svelte-kit/dev/runtime/internal/start.js:1377:19
@http://localhost:3000/LearnYourNumbers/1:11:10
```

Server Console
```
Cannot read property 'url' of undefined
TypeError: Cannot read property 'url' of undefined
    at resolve (file:///S:/Desktop/New%20folder/node_modules/@sveltejs/kit/dist/ssr.js:1829:39)
    at SSRAll (s:/Desktop/New%20folder/src/hooks.ts:4:32)
    at apply_handle (file:///S:/Desktop/New%20folder/node_modules/@sveltejs/kit/dist/hooks.js:20:11)
    at Object.handle (file:///S:/Desktop/New%20folder/node_modules/@sveltejs/kit/dist/hooks.js:10:10)
    at respond (file:///S:/Desktop/New%20folder/node_modules/@sveltejs/kit/dist/ssr.js:1809:30)
    at file:///S:/Desktop/New%20folder/node_modules/@sveltejs/kit/dist/chunks/index.js:205:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```


### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 AMD Ryzen 5 2600X Six-Core Processor
    Memory: 21.29 GB / 31.93 GB
  Binaries:
    Node: 16.7.0 - S:\Utility\nodejs\node.EXE
    npm: 7.7.5 - S:\Utility\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.69)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.10
    @sveltejs/kit: next => 1.0.0-next.229
    svelte: ^3.44.0 => 3.46.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

PS. This is my teams senior project for our college so the blocking of 3 out of 4 of our developers is a major issue for us.

Any advice would be appreciated.

**Comment by geoffrich** [comment]
Your system info has you on SvelteKit next.229, but you're using `event` in your hook, which was not introduced until [next.234](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next234). Try updating to the latest SvelteKit and see if that fixes it.

I suspect that the reason it works on Linux is that you have a different SvelteKit version installed in that environment.

**Comment by natefabian18** [comment]
> Your system info has you on SvelteKit next.229, but you're using `event` in your hook, which was not introduced until [next.234](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next234). Try updating to the latest SvelteKit and see if that fixes it.
> 
> I suspect that the reason it works on Linux is that you have a different SvelteKit version installed in that environment.

This seems to have resolved the issue. Thank you so much. lesson learned to always check for updates before banging my head against it for a few hours.
