### ISSUE TITLE
Incorrect build path for prerendered endpoints when setting a basepath (kit.paths.base)

### ISSUE THREAD

**Issue by yannp00** [sveltejs/kit#3620]
### Describe the bug

When setting a basepath with kit.paths.base, the prerenderer does not store the prerendered pages and endpoints in the same path, resulting in error when trying to access them.
If basepath is set to /mybasepath, pages will end up in the build/ folder, whereas endpoints will be in build/mybasepath/ folder.

### Reproduction

Clone `https://github.com/aryga/sveltekit-basepath.git`  (a minimal project created with create-svelte)

`npm install`
`npm run build`

**svelte.config.js** contains:
```import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter(),
		paths: { base: '/myapp' },
		target: '#svelte'
	}
};

export default config;
```

**Site structure:**
```app.html
routes
--index.svelte
--mypage
----index.svelte
----mypage.json.js
```

**As a result, the prerenderer generates files like this:**
```build
--_app
--index.html
--mypage
----index.html
--myapp
----mypage
------mypage.json
```

The endpoint and page that are in the same route "mypage" are not prerendered to the same folder.

When you deploy the build folder onto a flat-file server in a folder "myapp", then navigate to the index (is /myapp), then to the myapp/mypage page, it will open with error - it looks for /myapp/mypage/mypage.json when that file is in /myapp/myapp/mypage/mypage.json

**Note that dev or preview will work**, it somehow finds its way to the file in these modes.

```404
Could not load text from endpoint
Error: Could not load text from endpoint
    at H (https://[mysite.com]/myapp/_app/pages/mypage/index.svelte-2a470229.js:1:747)
    at async qe._load_node (https://[mysite.com]/myapp/_app/start-e76574a6.js:1:19806)
    at async qe._load (https://[mysite.com]/myapp/_app/start-e76574a6.js:1:20635)
    at async qe._get_navigation_result (https://[mysite.com]/myapp/_app/start-e76574a6.js:1:18038)
    at async qe.update (https://[mysite.com]/myapp/_app/start-e76574a6.js:1:16039)
    at async qe.handle_navigation (https://[mysite.com]/myapp/_app/start-e76574a6.js:1:15956)
    at async Ce._navigate (https://[mysite.com]/myapp/_app/start-e76574a6.js:1:12353)
```

Moving build/myapp/mypage/mypage.json to build/mypage/mypage.json fixes the problem.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 4.93 GB / 15.92 GB
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    npm: 7.23.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.76)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/adapter-static: ^1.0.0-next.26 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.250
    svelte: ^3.44.0 => 3.46.3
```

### Severity

serious, but I can work around it

### Additional Information

Workaround: move the files from build/myapp to build/ when deploying

FYI, I could not get it to work at all with adapter-netlify, myapp/mypage would not load at all but I did not try to check if it was related.

**Comment by lkostrowski** [comment]
Do you know if any previous version works, so we can rollback? Indeed this is a serious problem - is it a regression?

**Comment by Rich-Harris** [comment]
This is fixed in newer versions — closing
