### ISSUE TITLE
Browser "back" button doesn't scroll back from anchors in current page

### ISSUE THREAD

**Issue by Glench** [sveltejs/kit#3621]
### Describe the bug

It's a little easier to describe this bug with the reproduction, but the gist is that when you click a link with an anchor (e.g. `<a href="#foo">`), then click the browser's back button, the page doesn't scroll back to where you were before you clicked the anchor. Instead it just stays at the same scroll position as the target, although it does properly change the url hash.

Testing the behavior on other sites (e.g. [any wikipedia page with a table of contents](https://en.wikipedia.org/wiki/Barack_Obama)) confirms that the browser does normally remember your scroll position when navigating between anchor elements on the same page.

### Reproduction

1. Go here as an example: https://sveltesaas.com/articles/sveltekit-github-pages-guide/
2. Scroll down and click the "Install SvelteKit" link in the Getting Started section. The page will properly scroll down to the correct section.
3. Click your browser's "back" button. The URL will correctly change but the page will not scroll back to where you were before, as it usually does when navigating between anchors on the same page.

### System Info

```shell
Firefox 96.0.2 on Mac 12.1
```

### Severity

annoyance

**Comment by geoffrich** [comment]
I can repro this on the [Kit docs](https://kit.svelte.dev/docs). Interestingly, it only happens on the first hash link you click. So after clicking one hash link, the back button will not return you to the top of the page. But if you click two hash links in a row, the back button works -- it will first take you back to the first hash link, and then to the top of the page.

**Comment by Glench** [comment]
> I can repro this on the [Kit docs](https://kit.svelte.dev/docs). Interestingly, it only happens on the first hash link you click. So after clicking one hash link, the back button will not return you to the top of the page. But if you click two hash links in a row, the back button works -- it will first take you back to the first hash link, and then to the top of the page.

Ohh interesting — you're right! Weird.

**Comment by vicky1999** [comment]
Can I work on this issue?

**Comment by benmccann** [comment]
I believe this is fixed now. @Glench can you upgrade to the latest version and test it out? Let me know if it's still present or if it has resolved for you

**Comment by charbelnicolas** [comment]
I think this is still broken :(

**Comment by Glench** [comment]
I just tried on the SvelteKit docs and the scrolling seems to work fine.

**Comment by charbelnicolas** [comment]
> I just tried on the SvelteKit docs and the scrolling seems to work fine.

But the browser history will not work, at least on my computer. If I first click on #section1 link and then click on #section2 link and then hit the back button, the URL changes but it doesn't go back to #section1...

**Comment by Glench** [comment]
That exact sequence works fine for me on Firefox 108.0.2.

**Comment by zqianem** [comment]
> > I just tried on the SvelteKit docs and the scrolling seems to work fine.
> 
> But the browser history will not work, at least on my computer. If I first click on #section1 link and then click on #section2 link and then hit the back button, the URL changes but it doesn't go back to #section1...

Just ran into this with the SvelteKit docs, Firefox 117.0 on Linux. The URL is changed but the page does not scroll.
