### ISSUE TITLE
Viewport prefetching

### ISSUE THREAD

**Issue by bluwy** [sveltejs/kit#3633]
### Describe the problem

Currently `sveltekit:prefetch` works by requesting data on hover or before click only. In some cases, it may be desirable to prefetch immediately when the link enters the viewport, similar to how nextjs works today.

https://github.com/sveltejs/kit/discussions/3041 also highlighted some points there.

### Describe the proposed solution

Provide a way to define the prefetching strategy, either by viewport or hover. This can be achieved by passing a value to the attribute, e.g. `sveltekit:prefetch="<strategy>"`. By default with no value, it would fallback to the hover strategy.

For viewport prefetching, `IntersectionObservers` can't be used as anchor tags change often and to detect that `MutationObservers` are needed, but that imposes a lot of potential overhead. An alternative is to query select anchor tags and prefetch them in short intervals. (Ideas welcomed)

To detect when to invalidate the data, `maxage` can be used. To avoid discouraging short `maxage` (which indirectly cause repeated prefetching), a syntax like `sveltekit:prefetch="viewport:1000"` could be supported to denote "invalidate after 1s". Or a config option can be used to set a minimum prefetch interval (similar https://github.com/sveltejs/kit/issues/790)

### Alternatives considered

Refer users to implement their own viewport prefetch logic using actions. Caveat is that links in contents from CDN can't take advantage of the declarative prefetching syntax.

### Importance

nice to have

### Additional Information

1. Rich noted that prefetch invalidation may not always be wasteful as the modules requested are usually reusable, only the data is stale.
2. Adding viewport prefetch implementation may require some infrastructure refactoring.
3. I might've forgotten some points from the last maintainer's meeting.

**Comment by madeleineostoja** [comment]
Just wanted to chime in again that adding that kind of config to every single anchor element in an app is a lot of user overhead in terms of DX that's also prone to user-error, and imo if this was implemented that's an even stronger argument for adding support to prefetch all relative links by default at the same time, with this stuff configured globally in the same place. A `prefetch` option under kit in `svete.config.js` feels like a no-brainer, with per-link overrides possible.

**Comment by NagabhushanS** [comment]
.

**Comment by Rich-Harris** [comment]
Another strategy might be 'focus'. If I navigate to a link with the tab key, maybe that link should start prefetching? Then again, doing so would typically mean prefetching all the links you tab through until you get to the one you want, so maybe not. Unclear. At the very least we should prefetch on keydown for focused links.

**Comment by Rich-Harris** [comment]
this can be closed now that we have `data-sveltekit-preload-code="viewport"`

https://kit.svelte.dev/docs/link-options#data-sveltekit-preload-code
