### ISSUE TITLE
Rename `params` to `slugs` in load

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#3634]
### Describe the problem

in load function we have instead of page now parameters url and params... params is derived from url.pathname, but url has also property url.searchParams... because of that it's kind of confusing as "params" can now refer to both parameters like `?x=value` or to params like `/[slug]/` ... I even twice was burned on that I did "const params = url.searchParams" in load function and rewrited params object from params of load function. (see, a lot of params word in this sentence)....

### Describe the proposed solution

let url be url, and params be named slugs

### Importance

nice to have

**Comment by Mlocik97** [comment]
![Snímka obrazovky z 2022-01-30 17-57-34](https://user-images.githubusercontent.com/34808350/151709218-7745cb91-e641-4239-b73a-17969690095f.png)

as You can see, I'm not the only one confused about this. The name "params" for load "parameter" named "params", when it refer to slugs, while actuall "params" are avaiable in url.searchParams, is really bad...

**Comment by Conduitry** [comment]
I had suggested `slugs` a month ago when we were reorganizing things to use the `URL` API, and Rich's reaction at the time was

> eesh
> i think we initially went with `params` because it has lineage (`req.params` in express and everything that copied it, for example)
> i think `slugs` could be tricky because it's often the case that you have a paramater _called_ `slug`
> `slugs.slug` is an unpleasant thing to type

**Comment by Mlocik97** [comment]
interesting, and I agree with Rich that "slugs.slug" seems weird, but params seems as bad name as well... just today I found at least 4 people at Discord that were confused about this.

**Comment by didier** [comment]
`request.values`? `request.entries`? Just my two cents. I for some reason feel strongly for a single word variable name. Also, `slugs` sounds kinda gross. 😆

**Comment by Mlocik97** [comment]
actually we don't want to change request object as it's instance of Request, so it would be fine to have same... better to change params, not sure if entries would be good name for it... "values" is like, what is it? Not self-descripted...

**Comment by didier** [comment]
@Mlocik97 Oops, I meant `url` instead of `request`. You’re right about it being less descriptive. What about `parts`, `slices` or `sections`?

**Comment by Mlocik97** [comment]
`sections` seems interesting suggestion, also `parts` but it's little less descriptive,... about `slices` I think this is not good suggestion as there is `slice` function in JS, and if You would use both slice and slices in load it would be maybe confusing in some situations. Also it would be less readable to read similiar words, would need to make extra attention to last letter.

**Comment by didier** [comment]
Yeah, my thought process behind `sections` was that they are literal sections of the url. `example.com/<section>/<section>`, etc.

**Comment by Rich-Harris** [comment]
Unless we can find a name that's unambiguously better than `params`, I think we probably need to keep it as-is. It was chosen because it matches `req.params` in Express apps, and is also used by Nuxt...

![image](https://user-images.githubusercontent.com/1162160/152067469-5250d1b0-c168-4eb1-ac85-2166474551d0.png)

...and Remix:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/1162160/152067530-a5106379-ce86-4721-b537-dd46149570e9.png">

It shouldn't be the overriding consideration, but there's value in using the same terminology as the wider ecosystem.
