### ISSUE TITLE
SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#365]
We've been seeing this in production, via Sentry — almost exclusively on iPhones. I assume it's related to this: https://github.com/sveltejs/kit/blob/ad9551c47727b74fcc7c31614962e7bc37792633/packages/kit/src/runtime/internal/router/index.js#L49-L63

**Comment by zackify** [comment]
What if you changed it to only run every 500ms? Then it would only run a max of 60 times in 30 seconds. I feel like that is still pretty frequent for restoring the scroll position later.

**Comment by benmccann** [comment]
It should not be running when continuously moving the mouse or when not moving the mouse, but only when the mouse was moving and then stops. Changing it to 500s sounds like a copout instead of really understanding the issue as to why debouncing isn't working here.

**Comment by zackify** [comment]
I see what you mean!

**Comment by pago** [comment]
Not entirely sure if it should go here or in a separate issue. Happy to move it to a separate issue if needed.

I'm observing the same issue mentioned here but I also have some (iOS only) errors about `pushState` in my Sentry log.

```
SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds
```

Might be related somehow.

**Comment by philippdormann** [comment]
seeing these issues in production on iOS 14.7.1 devices (iPhone 12 mini - "iPhone13,1")
```
SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
```

```
SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds
```

**Comment by acoyfellow** [comment]
Can confirm I'm picking this up via Sentry too:
```
SecurityError: Attempt to use history.replaceState() more than 100 times per 30 seconds
```

Mobile Safari
Version:14.1.2

iOS
Version:14.7.1

iPhone

**Comment by si3nloong** [comment]
May be we can refer to this solution.

https://github.com/ampproject/amphtml/pull/23938/files

**Comment by MyIsaak** [comment]
Check out my PR on this issue: https://github.com/sveltejs/kit/pull/2738

**Comment by bluwy** [comment]
I tested this on my iphone today and I discovered that ios emits the scroll event later than other browsers. Intervals between scroll events rapidly fluctuate between 30 - 150ms. And an easy way to aggressively trigger this bug is to quickly scroll up and down, that would consistently give 200-300ms.

With these said, our debounce function runs at a 50ms interval, which explains how the security error was caused, because we essentially had no debouncing at all. I'll submit a PR to increase it to 200ms as that gives the least false positives.

**Comment by sundarrajendran** [comment]
What is the fix for this issue. I am also getting the same error. can anyone please help?
`Attempt to use history.pushState() more than 100 times per 30 seconds`

**Comment by TheBlckbird** [comment]
This is safari specific

**Comment by mprync** [comment]
This is still happening on Safari and potentially iOS but it is specific to Safari.
