### ISSUE TITLE
Page, url and params. 

### ISSUE THREAD

**Issue by R0N1n-dev** [sveltejs/kit#3655]
### Describe the bug in

"page in load functions has been replaced by url params."
The code below gives me the above error 

### Reproduction

<script context="module">  
    export async function load({page}){
        const id = page.params.id;
        const url = `https://pokea.pi.co/api/v2/pokemon/${id}`;
        const res = await fetch(url);
        const pokeman = await res.json();
        return {props: {pokeman}};}
</script>

<script>  
    export let pokeman;
</script>

<h1>{pokeman.name}</h1>

### System Info

```shell
Zorin lite 16
```

### Severity

annoyance

### Additional Information

Can we please get A CLEAR CALRIFICATION on this issue. Reading a lot of other discussions and they seem not useful if just looking for a solution.
Lots of words but no clear solution.

Yes a m kind of new to svelte

**Comment by Conduitry** [comment]
The error message says exactly what is happening. The arguments to `load` have changed. See https://kit.svelte.dev/docs#loading-input
