### ISSUE TITLE
adapter-static: parameterized pages not crawled if link has "sveltekit:prefetch"

### ISSUE THREAD

**Issue by geoffrich** [sveltejs/kit#3660]
### Describe the bug

When prerendering an entire site with adapter-static, links to parameterized pages with `sveltekit:prefetch` are not crawled properly. Only one parameterized page is prerendered.

If I have the following routes....
```
[idx].svelte
index.svelte
__layout.svelte
```
...and the layout looks like this...
```
<a href="/1" sveltekit:prefetch>1</a>
<a href="/2" sveltekit:prefetch>2</a>
<a href="/" sveltekit:prefetch>Home</a>

<slot />
```

Only `/index.html` and `/1/index.html` are prerendered when building the site with adapter-static. `/2/index.html` is not.

If I remove `sveltekit:prefetch` from the links, `/index.html`, `/1/index.html`, and `/2/index.html` are all prerendered.

### Reproduction

[Stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-yueq65?file=src/routes/__layout.svelte)

Run `npm run build` in the terminal and check the `build` directory to see that `/2/index.html` was not prerendered, despite being linked in the layout.

### System Info

```shell
I'm unable to run this on StackBlitz. Package versions:

@sveltejs/kit: 1.0.0-next.252
@sveltejs/adapter-static: 1.0.0-next.26
```

### Severity

serious, but I can work around it

**Comment by iham** [comment]
i guess i have a pretty similar issue here: #3665

**Comment by Conduitry** [comment]
It looks like the issue is that when the crawler's HTML parser runs into an attribute containing a `:`, the _next_ attribute loses its first character - meaning the crawler only sees `ref` instead of `href` and doesn't follow the link. This appears to be happening even when the affected (next) attribute is in a later tag.

**Comment by Conduitry** [comment]
Or rather, actually, it looks like an attribute with no value will cause the first character of the next attribute to be lost (regardless of whether that is in the same element or not), which makes a lot more sense as a bug, because I wasn't seeing anything special about `:` in the parsing code.

**Comment by Conduitry** [comment]
```diff
diff --git a/packages/kit/src/core/adapt/prerender/crawl.js b/packages/kit/src/core/adapt/prerender/crawl.js
index 9a19a8aa..8cf584cf 100644
--- a/packages/kit/src/core/adapt/prerender/crawl.js
+++ b/packages/kit/src/core/adapt/prerender/crawl.js
@@ -175,6 +175,8 @@ export function crawl(html) {
 									hrefs.push(src);
 								}
 							}
+						} else {
+							i -= 1;
 						}
 					}
```

would appear to fix this. We need to un-eat the character that wasn't an `=`. I don't know whether there's a more graceful way of accomplishing this.
