### ISSUE TITLE
Overhaul docs

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3696]
### Describe the problem

https://kit.svelte.dev/docs needs some love. The API was a nice idea but we decided it's ultimately more trouble than it's worth — previewing changes is much harder, and it prohibits us from experimenting with things like mdsvex (which is very useful in the [Svelte Cubed documentation](https://svelte-cubed.vercel.app/docs/getting-started), for example)

### Describe the proposed solution

The maintainers recently settled on the outline of a plan:

1. [x] #3704 
2. [x] Deploy the site from this repo, rather than `sveltejs/sites`
3. [x] Remove kit.svelte.dev from `sveltejs/sites`
4. [x] Prerender docs using markdown in this repo, rather than api.svelte.dev
5. [x] Remove Kit docs from api.svelte.dev
6. [x] Multiple pages and full text search
7. [x] #3324 so that the docs are typechecked

Other thoughts:

* We should move most of the type declarations to the `TypeScript` section — there's a lot of duplicative clutter that helps no-one
* It's important that we're able to accommodate internationalisation work in future, though we don't yet know exactly what form that will take in SvelteKit. I do like the idea of having translations be visible in the repo, where it's easy to (for example) see if a given piece of the primary documentation is more recent than its translations.

### Importance

would make my life easier

**Comment by benmccann** [comment]
In case it helps with the next step, here's the old code for generating docs locally. It's possible there might need to be some changes copied over from the API if this docs generation code has changed at all:

https://github.com/sveltejs/sites/blob/a043d3fdf6c3fbfd8f5dc84979eb03a50657b7d4/sites/kit.svelte.dev/src/routes/docs/index.json.js
https://github.com/sveltejs/sites/blob/a043d3fdf6c3fbfd8f5dc84979eb03a50657b7d4/sites/kit.svelte.dev/src/utils/generate_docs.js

**Comment by lukaszpolowczyk** [comment]
**Collapsing elements in the side panel**

While we're on the subject of shortening documentation page scrolling, why not add element collapsing in the side panel? Because the list in the side panel is pretty long too, and often whole sections I skip anyway.
(Even the collapsing can be maintained between sessions)
