### ISSUE TITLE
Notify of any breaking changes to make it easier for folks to update their apps

### ISSUE THREAD

**Issue by kevmodrome** [sveltejs/kit#3710]
### Describe the problem

There have been some requests for a way to get notified of breaking changes in kit. I'd argue we wouldn't need to care about it until 1.0 but I'm forwarding the request anyway. 

### Describe the proposed solution

A quick way to solve this would be to add some kind of `(breaking change)` message in the changeset. Using #3670 as an example: `Add App namespace for app-level types (breaking change)`. 

### Alternatives considered

- Do nothing

### Importance

nice to have

### Additional Information

- None

**Comment by dominikg** [comment]
there is https://github.com/sveltejs/kit/labels/breaking%20change which highlights at least some

**Comment by Conduitry** [comment]
We've been inconsistent about including "breaking change" next to changelog entries. It would probably be a polite thing to do,

**Comment by bluwy** [comment]
We do have the `Breaking:` text in the changeset to note it's a breaking change. But yes it seems like some breaking changes are not prefixed with it, e.g. https://github.com/sveltejs/kit/pull/3674 too

**Comment by Rich-Harris** [comment]
We're getting better about adding `[breaking]` to changesets. I think that's probably the best we can do until we hit stable, so I'll close this
