### ISSUE TITLE
`getSession()` does not get called on page load. should warn user

### ISSUE THREAD

**Issue by luhagel** [sveltejs/kit#3722]
### Describe the bug

Unfortunately, I haven't been able to get our sveltekit app to work in production past kt@next.206 and adapter-node@next.56.

Since the ssr was always somewhat flunky with our - aside from the login page- completely private app we previously disabled it via the config and on all update attempts in the handle hook.

Now, the issue is always the same, everything runs fine locally, until it gets deployed, where you can't get past the login screen anymore, since the session never gets populated. I recently found out that the issue seems to lie somewhere within adapter-node, since running `dev` and `preview` works flawlessly, but running the build output directly via `node _build` presents the same issue our staging environment showed locally.

Any help/pointers would be appreciated, ready to replace our auth code if necessary/it's just us working against sveltekit.

If you have any further questions, feel free to ask !

### Reproduction

https://github.com/luhagel/sveltekit-node-session-repro

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 AMD Ryzen 5 3600X 6-Core Processor             
    Memory: 9.02 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.2
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/adapter-node: ^1.0.0-next.67 => 1.0.0-next.67 
    @sveltejs/kit: next => 1.0.0-next.260 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking an upgrade

**Comment by PH4NTOMiki** [comment]
If I remove `{ssr: false}` from your hooks file, it works for me, both in dev and prod (build)

**Comment by zommerberg** [comment]
I had the same issue and had to remove the `handle` function together with the `ssr:false` (sveltekit v.260), It appears that having ssr disabled prevents getSession from passing data or being run with adapter node on prod.

**Comment by eriknyk** [comment]
same here

**Comment by PH4NTOMiki** [comment]
@benmccann I'm not sure this is a bug, I just tried to debug it, and what I found out was that that page was prerendered (`/protected`) and that's why it was not working, because it was a static page, so the solution to the @luhagel issue is use this config:

```javascript
import node from '@sveltejs/adapter-node';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: node({
			out: '_build',
			precompress: true
		}),
		prerender: {
			enabled: false
		}
	}
};

export default config;

```

**Comment by PH4NTOMiki** [comment]
@benmccann but there should be at least a warning that session is being used on prerendered page, something like that.

**Comment by luhagel** [comment]
@PH4NTOMiki Thanks for looking into this ! Gonna give it a try with the full scale non-repro project and keep you posted :+1:

**Comment by luhagel** [comment]
@PH4NTOMiki That did indeed do the trick, thanks a lot ! And yes, a warning would be helpfull, especially it was a somewhat undocumented change post `.206` and ist somewhat difficult to figure out without.

**Comment by PH4NTOMiki** [comment]
@zommerberg @eriknyk what about you, does that solve the issue?

**Comment by zommerberg** [comment]
@PH4NTOMiki Yes, it solves it.

**Comment by tcc-sejohnson** [comment]
@benmccann 

Happy to tackle this one. Just give the a-ok.

**Comment by JJCLane** [comment]
Not sure if you'd like me to add another issue for this, but I just ran into a related issue where I was accessing the session through `import { session } from '$app/stores';` in `__layout.svelte` (think user menu), and it took me a while to realise I had a stray `prerender = true` causing the page not to update.

**Comment by tcc-sejohnson** [comment]
> Not sure if you'd like me to add another issue for this, but I just ran into a related issue where I was accessing the session through `import { session } from '$app/stores';` in `__layout.svelte` (think user menu), and it took me a while to realise I had a stray `prerender = true` causing the page not to update. 

Weird. I'm 95% sure that I added some error log for this before this issue got closed.

**Comment by tcc-sejohnson** [comment]
Yeah, #4811 should've fixed this.

**Comment by tcc-sejohnson** [comment]
Oh, pff, I'm stupid -- this is the session store. Yeah, I would open a new issue and reference this one. Be sure to include a small repro with StackBlitz or a GitHub repo.

**Comment by Lirben** [comment]
Hi,

I don't know if this is related, but i get an error:

"Attempted to access session from a prerendered page. Session would never be populated."

By having 	enabled: false. This indeed dissapears. But i want to enable prerendering.

This code triggers the error: It strange, because i don't really read the session variable. If i delete the parameter, i can run my dev server, but when building with static adapter, it throws the error again.

```
<script context="module">
	/**
	 * @type {import('@sveltejs/kit').Load}
	 */
	export async function load({ params, fetch, session, context })
    {
        const response = await fetch('/api_routes/coursesAPI/byID/zu9knmlb80.json');
		let course = await response.json();
        
		if (response.ok) {
			return {
				props: {
                    course: course
				}
			};
		}	
	}
</script>

thanks for any help
```

**Comment by tcc-sejohnson** [comment]
> Hi,
> 
> I don't know if this is related, but i get an error:
> 
> "Attempted to access session from a prerendered page. Session would never be populated."
> 
> By having 	enabled: false. This indeed dissapears. But i want to enable prerendering.
> 
> This code triggers the error: It strange, because i don't really read the session variable. If i delete the parameter, i can run my dev server, but when building with static adapter, it throws the error again.
> 
> ```
> <script context="module">
> 	/**
> 	 * @type {import('@sveltejs/kit').Load}
> 	 */
> 	export async function load({ params, fetch, session, context })
>     {
>         const response = await fetch('/api_routes/coursesAPI/byID/zu9knmlb80.json');
> 		let course = await response.json();
>         
> 		if (response.ok) {
> 			return {
> 				props: {
>                     course: course
> 				}
> 			};
> 		}	
> 	}
> </script>
> 
> thanks for any help
> ```

Intended behavior. Also, you're using an old version of Kit.
