### ISSUE TITLE
Adder ability, to add Hooks handle in sequence 

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#3723]
### Describe the problem

I would like an Adder able to add Hooks handle, but so that it does not interfere with other handles.

The adder I have in mind adds fast login support itself, so
* creating a handler,
* adding ready-made routes login.svelte, register.svelte etc,
* also components (a login/status button that can be added to other routes) that you just embed and that's all you need to do initially.
* Plus under that a ready-made test database, like db.json.

One command - and you have it all ready.

The obstacle is:
* the difficulty(impossibility) of adding a handler using Adder.
---

Ultimately, I'd like to be able to hide some routes and just "register" them, and the same handler to be hidden in the package that the adder adds. Just like a regular package installed with npm, it is "hidden" but can be used in the project.

Perhaps this is a topic for another issue.

### Describe the proposed solution

I have no idea.

Probably using the sequence function, should be replaced with some easy to edit file format, so that Adder can easily modify it.

### Alternatives considered

Doing it by hand... :( (Because making an Adder where you have to add one of the big elements manually anyway, kinda misses the point in this case.)

### Importance

would make my life easier

**Comment by babichjacob** [comment]
Did you mean to make this issue at https://github.com/svelte-add/svelte-add?

**Comment by lukaszpolowczyk** [comment]
@babichjacob No, because it requires a change with SvelteKit Hooks.
Adder would only modify the file responsible for the handler sequence in SvelteKit Hooks.

If you modify the SvelteKit Hooks syntax, Adder will be able to do this by, for example, simply editing the file, without an additional API inside Adder.

**Comment by dummdidumm** [comment]
The requirements sound unclear to me. We will not add some specific format so that `svelte-add` has it slightly easier to create an adder that modifies the hooks - closing.
