### ISSUE TITLE
update hrefs to match with createIndexFiles set to false

### ISSUE THREAD

**Issue by iham** [sveltejs/kit#3725]
### Describe the problem

i try to build a completely static site - as a result - from a sveltekit project.
idea is to not host the app, but its output - SSG so to speak
in general it works but adding `createIndexFiles: false` to prerender, creates hickups.

a website with two pages
/routes/index.svelte
/routes/about/index.svelte

in my __layout.svelte a nav with a tags which hrefs point to / and /about
```
<nav>
  <a href="/">HOME</a>
  <a href="/about">ABOUT</a>
</nav>
```

npm run build creates 
/build/index.html
/build/about.html

but the navigation does not respect the "changes"
```
<nav>
  <a href="/" class="svelte-1rhg2al">HOME</a>
  <a href="/about" class="svelte-1rhg2al"> ABOUT </a>
</nav>
```

i have searched the docs, examples and tried several ideas on my own, but sadly didn't find a solution.

### Describe the proposed solution

hrefs should be updated correctly when createIndexFiles is set to false and the routing changes from /about/index.html to /about.html

### Alternatives considered

if this works - the docs should be showing an example on that use case

### Importance

i cannot use SvelteKit without it

**Comment by Rich-Harris** [comment]
If you're using `createIndexFiles: false`, the assumption is that you're using a static file host that responds to `/` with `index.html` and `/about` with `about.html`. If that's not the case, you shouldn't use that option.

**Comment by Rich-Harris** [comment]
we no longer have `createIndexFiles` — everything is driven by `trailingSlash` — so I'll close this
