### ISSUE TITLE
Shadow endpoints navigation within same route

### ISSUE THREAD

**Issue by livehtml** [sveltejs/kit#3727]
### Describe the bug

How can we navigate if route component and endpoint won't change?
Currently its not work as expected.
If we have say:
/example/[...rest].js
/example/[...rest].svelte

And try to use links on page like:
href="/example", href="/example/1", href="example/2" — navigation between them won't work (page not updates, only address bar changes)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-x92deg?devtoolsheight=33&file=src/routes/example/[...rest].js

### System Info

```shell
kit next 260
```

### Severity

serious, but I can work around it

**Comment by ambiguous48** [comment]
> but I can work around it

@livehtml I've run into the same issue. Would you mind sharing your workaround?

**Comment by livehtml** [comment]
@ambiguous48 sure:
```
export const load = async ({ params, props }) => {
    if (params.rest) '';
    return { props }
};
```

Just highlight needed params to watch it in the load function and it works as expected.
But I think it's more like a 'hack' other than right way.

**Comment by ambiguous48** [comment]
I've tried your workaround and it doesn't work for searchParams as far as I can tell.

In my case I'm using url.searchParams (not params) and I can't seem to get the endpoint to pick up changes in the url.searchParams after navigating with `goto`. 

After a manual refresh, the first time calling `goto` works as expected. Then, the url continues to change as expected, the load function is able to pick up the changes, but not the endpoint.

**Comment by tmarnet** [comment]
Noticed the same issue with both:
- search params, e.g. navigating from `/movies` to `/movies?q=foo` using `goto()`
- dynamic params, e.g. navigating from `/movies/1` to `/movies/2` using a regular link

**Comment by PH4NTOMiki** [comment]
I was testing this and as it turns out prefetching works for those routes without any issue, but the actual navigation doesn't, @benmccann @bluwy  as far as I can see, it looks like the code that checks is the route the same as previous is causing this, I'm trying to fix it, but I didn't succeeded yet. if I do, I'll push PR
