### ISSUE TITLE
Make it clearer when client-side load is re-fetching data because the server-side load didn't use its wrapped fetch function

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#3731]
### Describe the problem

When using an external SDK in a `load` function without telling it what `fetch` to use (or if it doesn't have the ability to be told what `fetch` to use), the network response is not serialized into the server-rendered DOM, and on the client-side, the browser's native `fetch` doesn't know to first look for these serialized responses before making a network call. This results in degraded performance, because the same request is then performed again in the browser.

The solution here is for people to call the SDK on the server in an endpoint (preferably a shadow endpoint for this page, which will make this very easy), or to make sure they only call it client-side in `onMount`, say. However, there's no currently obvious way for people to know that this undesirable thing is even happening.

### Describe the proposed solution

In dev mode, we could override the browser's `window.fetch` with our own version that we can configure to complain when it is called (and then call the underlying native `fetch`). We could enable this during the `load` for the initial hydration of the page.

For bonus points, the `load`'s `fetch` could call this patched `window.fetch` function in such a way as to tell it that it _shouldn't_ complain during this request. This would reduce false positives where there is (for whatever reason) a genuine reason to request additional data in the client's `load` that wasn't requested in the server's `load`, as long as it is done via the appropriate `fetch` function.

### Alternatives considered

We could just document this, but that doesn't seem very discoverable. If someone's doing something that's probably wrong, we would like to tell them about it, rather than assuming that they've read the documentation and are keeping this in the back of their mind all the time.

### Importance

nice to have

### Additional Information

This proposal arose from a conversation in the maintainers' chat about #3729.

**Comment by synthXR** [comment]
Could the maintainers kindly comment on this?

**Comment by Rich-Harris** [comment]
I like this idea, we should do it

**Comment by newlegendmedia** [comment]
To clarify, this issue seems to be saying that a fetch in the load function could/would be called in the browser if it's not the load special fetch? If so, I guess I've managed to write a fairly extensive svelte-kit app without realizing that code in the load function could have been (selectively) run in the browser. I always treated the load function  as running on the server.

**Comment by geoffrich** [comment]
@newlegendmedia see the [docs](https://kit.svelte.dev/docs/loading) - load runs on the client and the server.

> A component that defines a page or a layout can export a load function that runs before the component is created. This function runs both during server-side rendering and in the client, and allows you to fetch and manipulate data before the page is rendered, thus preventing loading spinners.

**Comment by newlegendmedia** [comment]
@geoffrich Thanks for the reference, I probably had no idea what that meant when I was first learning. Is there any general guide as to what parts of the load run on both sides? Is it all run on both places except the special fetch has some split logic in it? If thats difficult to answer, I can go explore that in other contexts. Thanks

**Comment by pyronaur** [comment]
Personally, I would prefer to rename the server-side fetch to something that helps the developer distinguish between what happens on front-end and back-end, but since #4193 is closed I guess I can live with whatever happens next. I don't mind - now I know. But it seems that I'm not the only one who was confused by this.
