### ISSUE TITLE
hash handling in the client-side router

### ISSUE THREAD

**Issue by PH4NTOMiki** [sveltejs/kit#3746]
### Describe the bug

When the page is visited with a hash segment(`/page1#bottom`) and for ex. there is navigation link to `/page1` (that same page just without the hash part) and the browser would do a full page reload instead of just removing the hash part (by calling `history.pushState`) and scroll to top.

### Reproduction

Visit https://kit.svelte.dev/docs#loading
Click Docs link in the top middle in navbar
The browser would do a full page reload

### System Info

```shell
latest sveltekit
```

### Severity

annoyance

**Comment by PH4NTOMiki** [comment]
It looks like somewhere here is the issue: https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/router.js#L188-L197

I'll try to fix it myself and push PR if I can

**Comment by PH4NTOMiki** [comment]
Looks like related to https://github.com/sveltejs/kit/pull/3177

**Comment by bluwy** [comment]
Good catch @PH4NTOMiki. Yes we should only call the if block if the target URL contains a hash, feel free to send a PR.

**Comment by PH4NTOMiki** [comment]
@bluwy I pushed PR #3757 but I think that only fixes a really specific case, but the problem is wider, for example, go to https://kit.svelte.dev/docs#loading then scroll up/down and click any other item in the menu on the left(other than Loading)   (for example ), and the router will take to you to that element id, but it will be recorded twice in the history, because you are calling pushState in that setTimeout callback, #3663 (@benmccann I think this is the reason that @vicky1999 pushed it) tried to solve it as far as I can see, and also the navigation back won't work, and I don't know why yet, possible because that Hash change event gets intercepted somewhere, I'm not sure.
What do you think?

**Comment by bluwy** [comment]
Yeah, I haven't got to looking into the double history issue, but I think your PR is great as well to tackle this specific case, as the reload isn't a desirable thing at the moment. Thanks for getting your hand into this!
