### ISSUE TITLE
[vite] Error when evaluating SSR module 

### ISSUE THREAD

**Issue by uc-anr** [sveltejs/kit#3749]
### Describe the bug

I am getting below error in my project.

code: "ERR_MODULE_NOT_FOUND"
id: "E:/uCertify/App/ucertify_root/node_modules/tippy.js/dist/tippy.css"
message: "Cannot find module 'E:\\uCertify\\App\\ucertify_root\\package.json' imported from 'E:\\uCertify\\App\\ucertify_root\\node_modules\\vite\\dist\\node\\chunks\\dep-f5552faa.js'"
name: "Error"
plugin: "vite:css"

### Reproduction

On running app npm run dev.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 795.86 MB / 7.77 GB
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    npm: 7.11.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.33 => 1.0.0-next.67
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.26
    @sveltejs/kit: next => 1.0.0-next.260
    svelte: ^3.41.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
"Reproduction: By running sveltekit app" is not a proper reproduction and doesn't help anyone else reproduce your error.

This also sounds like the same issue as #3742, which I see you just commented on.

**Comment by uc-anr** [comment]
Yes this is the same issue.

**Comment by Conduitry** [comment]
Then please don't open another issue.
