### ISSUE TITLE
[Docs] Clarify optionality of hooks.handle in the context of SSR behavior

### ISSUE THREAD

**Issue by netaisllc** [sveltejs/kit#3750]
### Describe the bug

- `handle` is documented as being optional.
- `ssr` property has been added as an optional parameter to `resolve`.
- no mention of the behavior of `resolve` with regard to SSR if `ssr` is omitted.

Docs could be more explicit here. Namely, 

- if the SSR behavior is desired, `handle` _and_ `ssr` property are required.
- if `handle` is implemented, but `ssr` is omitted from `resolve`, what is the default behavior re SSR

Note: this is docs related; it's not a comment on relocating the SSR configuration.

### Reproduction

n/a

### Logs

```shell
n/a
```

### System Info

```shell
n/a
```

### Severity

annoyance

**Comment by benmccann** [comment]
> if the SSR behavior is desired, handle and ssr property are required.

That's not correct. If you don't define a `handle` method your pages will be server-side rendered
