### ISSUE TITLE
Use `kit.config.paths.base` in local development

### ISSUE THREAD

**Issue by metonym** [sveltejs/kit#3752]
### Describe the problem

Consider the use case of deploying to GitHub Pages, where a `base` URL must be specified (e.g., the name of the repo).

However, when developing a SvelteKit app locally, the base URL cannot be specified. A "not found" error is shown when attempting to navigate to `http://localhost/<base-url>/`.

As a result, `base` must be conditionally applied only when building the app for production.

```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
    paths: {
       base: process.env.NODE_ENV === "production" ? "/repo-name" : "",
    },
  },
};
```

**Prior Art**

`vite` uses the `base` URL when developing locally:

```js
// vite.config.js
import { defineConfig } from "vite";

export default defineConfig({
  base: "/repo-name/",
});
```

Run `vite dev`:

```sh
vite v2.7.13 dev server running at:

> Local: http://localhost:3000/repo-name/
> Network: use `--host` to expose

ready in 342ms.
```

### Describe the proposed solution

The desired UX would be to avoid conditionally applying a base path:

```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
    paths: {
       base: "/repo-name"
    },
  },
};
```

This would also make it easier to preview the app locally (i.e. `svelte-kit preview`).

### Importance

nice to have

**Comment by Conduitry** [comment]
Sounds like a duplicate of #2958.

**Comment by metonym** [comment]
Oof. Yeah, this is a dupe.
