### ISSUE TITLE
First visited page never unmounts when combining transition directive with page store

### ISSUE THREAD

**Issue by nonphoto** [sveltejs/kit#3753]
### Describe the bug

I have two pages with the same component on them: `<h2 transition:fade>Test</h2>`. If I access the page store anywhere in the layout shared by both pages: `console.log($page.url.pathname)` the first page will fail to unmount and will get stuck in a mounted state.

There is also some odd behavior for `onMount` in the layout. The layout component will mount twice—once for each page—but after both pages have been visited it will not continue to call `onMount`. This is unexpected because I would expect the layout to only mount once as it is shared by both page components.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-cfnjv7?file=src/routes/__layout.svelte

### System Info

```shell
See reproduction link
```

### Severity

serious, but I can work around it

**Comment by Robak08** [comment]
Seems ok to me, You're using transition directive which means both in: and out: transition. Component will unmount when all transitions are completed - hence the moment when old page is still visible, You can either use crossfade or just try in: directive.

**Comment by nonphoto** [comment]
Odd, I can't reproduce the issue anymore either. To be clear, this was not the default behavior of `out`: the element would never be removed from the DOM even after the duration ended. I will close this out for now unless it pops up again.
