### ISSUE TITLE
Shadow Endpoints: slight problems with set-cookie and other headers

### ISSUE THREAD

**Issue by georgecrawford** [sveltejs/kit#3758]
### Describe the bug

Firstly, thank you for shadow endpoints! They are a lovely simplification, and make perfect sense when implementing straightforward pages.

I've noticed two things which aren't quite right with the processing of the shadow endpoint's Response:

### Reproduction

**1. `set-cookie` is assumed to be an array**
See https://github.com/sveltejs/kit/commit/647131e00149cb5299042eedeb880efcd855a2df#diff-7266c49c71803f38dda70345d857f13a7a2494cc649b70af6b689627199f5b79R404-R406

<details>
 <summary>Reproduction: string is exploded</summary>

**endpoint.js**

```js
export async function post() {
    return {
        headers: {
            'set-cookie': 'a=b',
        },
    };
}
```
**test**
```sh
bash-5.1$ curl -X POST -I http://localhost:5001/endpoint

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
content-type: text/html
etag: "l9x8dd"
permissions-policy: interest-cohort=()
set-cookie: a
set-cookie: =
set-cookie: b
Date: Mon, 07 Feb 2022 10:16:38 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```
</details>

<details>
 <summary>Reproduction: array is handled correctly</summary>

**endpoint.js**
```js
export async function post() {
    return {
        headers: {
            'set-cookie': ['a=b'],
        },
    };
}
```

**test**
```sh
bash-5.1$ curl -X POST -I http://localhost:5001/endpoint

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
content-type: text/html
etag: "l9x8dd"
permissions-policy: interest-cohort=()
set-cookie: a=b
Date: Mon, 07 Feb 2022 10:16:38 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```
</details>

<details>
 <summary>Expected: string is treated as a singular header</summary>

**endpoint.js**
```js
export async function post() {
    return {
        headers: {
            'set-cookie': 'a=b',
        },
    };
}
```

**test**
```sh
bash-5.1$ curl -X POST -I http://localhost:5001/endpoint

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
content-type: text/html
etag: "l9x8dd"
permissions-policy: interest-cohort=()
set-cookie: a=b
Date: Mon, 07 Feb 2022 10:16:38 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```
</details>

**2. `set-cookie` and other headers aren't preserved for 3xx redirects**
See https://github.com/sveltejs/kit/commit/647131e00149cb5299042eedeb880efcd855a2df#diff-7266c49c71803f38dda70345d857f13a7a2494cc649b70af6b689627199f5b79R408-R416

Note that only `headers.location` is copied across in the case of a 3xx redirect.

<details>
 <summary>Reproduction: `set-cookie` is ignored for 307 redirect</summary>

**endpoint.js**
```js
export async function post() {
    return {
        status: 307,
        headers: {
            location: '/',
            'set-cookie': ['a=b'],
        },
    };
}

```

**test**
```sh
bash-5.1$ curl -X POST -I http://localhost:5001/endpoint

HTTP/1.1 307 Temporary Redirect
Access-Control-Allow-Origin: *
location: /
Date: Mon, 07 Feb 2022 10:25:09 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```
</details>

<details>
 <summary>Expected: `set-cookie` is preserved for 307 redirect</summary>

**endpoint.js**
```js
export async function post() {
    return {
        status: 307,
        headers: {
            location: '/',
            'set-cookie': ['a=b'],
        },
    };
}

```

**test**
```sh
bash-5.1$ curl -X POST -I http://localhost:5001/endpoint

HTTP/1.1 307 Temporary Redirect
Access-Control-Allow-Origin: *
location: /
set-cookie: a=b
Date: Mon, 07 Feb 2022 10:25:09 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Transfer-Encoding: chunked
```
</details>

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (6) arm64 unknown
    Memory: 10.94 GB / 15.60 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.67 => 1.0.0-next.67
    @sveltejs/kit: ^1.0.0-next.260 => 1.0.0-next.260
    svelte: ^3.46.2 => 3.46.2
```

### Severity

serious, but I can work around it

**Comment by georgecrawford** [comment]
FWIW, this conversation between @Rich-Harris and @Conduitry - https://github.com/sveltejs/kit/pull/3679#discussion_r798723647 - seems related, but I don't think we're dealing with a `Headers` object here, as I'm returning a `pojo` for `headers` instead. But I could be wrong.

**Comment by georgecrawford** [comment]
And the spec seems super annoying when using Request/Response on the server! https://fetch.spec.whatwg.org/#headers-class

**Comment by georgecrawford** [comment]
See related discussion, which GitHub didn't auto-link: https://github.com/sveltejs/kit/discussions/3739

**Comment by georgecrawford** [comment]
@benmccann I know that triage takes huge amounts of time, but I could probably have a stab at fixing these issues if you can confirm the bugs are valid. Would you agree with my presumptions that, in shadow endpoints:
- `'set-cookie': 'a=b'` should work as a singular header, and it should not be exploded as if it were an array?
- `'set-cookie'` headers should always be passed to the client, even in 3xx, 4xx or 5xx responses?

Thanks!

**Comment by ivanhofer** [comment]
I got the same issue. My auth-flow is currently broken because I can't set the auth-cookies and at the same time redirect the user to the page he was visiting before clicking on "login"
