### ISSUE TITLE
Shadow endpoint -- issue rendering with no get endpoint

### ISSUE THREAD

**Issue by florianlouvet** [sveltejs/kit#3759]
### Describe the bug

When using the new shadow endpoints, it seems it is required to define a `get` endpoint so that sveltekit renders the page (even if no data needs to be loaded and passed down to the page).
Not providing any `get` endpoints returns a 405 error.

<img width="1054" alt="Screenshot 2022-02-07 at 16 03 25" src="https://user-images.githubusercontent.com/21657360/152813743-75fffc4c-c005-48c8-9631-4a28ec17fc29.png">

Providing an empty `get` function solves this problem.
```javascript
export async function get() {
    return {
        body: { }
    };
}
```
It would be interesting not to have to provide an empty `get` function.

### Reproduction

Minimal reproduction can be found here: https://github.com/florianlouvet/shadow-endpoint-svelte-bug

When navigating to the `/login` page the 405 is raised. In the `login.js` endpoint file there is the empty get endpoints necessary to render the page (solving this issue in the meantime).

### Logs

```shell
405

get method not allowed

Error: get method not allowed
    at load_shadow_data (file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/.svelte-kit/runtime/server/index.js:1841:12)
    at async load_node (file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/.svelte-kit/runtime/server/index.js:1523:5)
    at async respond$1 (file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/.svelte-kit/runtime/server/index.js:2120:15)
    at async render_page (file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/.svelte-kit/runtime/server/index.js:2321:19)
    at async resolve (file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/.svelte-kit/runtime/server/index.js:2564:11)
    at async respond (file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/.svelte-kit/runtime/server/index.js:2497:20)
    at async file:///Users/florianlouvet/own/shadow-endpoint-svelte-bug/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 163.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.260 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

**Comment by ShubhankarKG** [comment]
Came here to support this, would be great to have this fixed!

**Comment by baseballyama** [comment]
What are the remaining point of this issue?
When I tried it on my local, the client-side navigation was also processed correctly.

**Comment by sw-yx** [comment]
@benmccann think this issue is now solved

**Comment by benmccann** [comment]
Yes, if I upgrade the reproduction to the latest version it appears to work. Thank you so much for letting me know!
