### ISSUE TITLE
Prerendering fails with 404 since introduction of shadow endpoints

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#3760]
### Describe the bug

Prerendering fails with 404 since introduction of shadow endpoints

### Reproduction

https://github.com/benmccann/interactive-blogs-benchmark/tree/shadow-endpoint-404

### System Info

```shell
reproduction provided
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
I can't reproduce this using the linked repo with the most recent version of Kit

**Comment by benmccann** [comment]
I just upgraded the repo to the latest. It looks like it's successfully building, but still printing a 404 error:

>  404 /posts/post4.json (fetched from /posts/post4/)
  Wrote site to "build"
  ✔ done

**Comment by Rich-Harris** [comment]
Do you have unstaged changes to the repro? It's not attempting to render `post4` when I run it

**Comment by benmccann** [comment]
I checked it out fresh and am still getting it. Are you on the branch `shadow-endpoint-404`?

**Comment by mrkishi** [comment]
That's a legit 404 due to this line: https://github.com/benmccann/interactive-blogs-benchmark/blob/f667db20a594b3c67ddce0204be82bab2673910c/sveltekit_mdsvex/src/routes/posts/%5Bslug%5D.json.ts#L7.

**Comment by Conduitry** [comment]
That explains why `/posts/post4.json` is a 404, but I'm not sure why that's being requested. The error message says `fetched from /posts/post4/` but why is that fetching that?

**Comment by mrkishi** [comment]
It's being fetched from the layout of `post4.svelte`: https://github.com/benmccann/interactive-blogs-benchmark/blob/f667db20a594b3c67ddce0204be82bab2673910c/sveltekit_mdsvex/src/routes/posts/__layout.svelte#L5-L25.

**Comment by Conduitry** [comment]
Ah, the layout, right. Yup. I think this is all behaving as expected, then. And the build still finishes successfully because of the `onError: 'continue'`.

**Comment by benmccann** [comment]
Ah, thanks for taking a look. This was a user reported issue and I missed that they had defined a `load` in the layout
