### ISSUE TITLE
Use `DeepPartial<App.Stuff>` for `LoadOutput.stuff`

### ISSUE THREAD

**Issue by AradAral** [sveltejs/kit#3781]
### Describe the problem

It's not unthinkable to want your `stuff` to have more than one level of depth, for example:
`app.d.ts`:
```typescript
/// <reference types="@sveltejs/kit" />

// See https://kit.svelte.dev/docs#typescript
// for information about these interfaces
declare namespace App {
    interface Session {}

    interface Locals {}

    interface Platform {}

    interface Stuff {
        footer: {
            show: boolean;
            bottomMargin: boolean;
        }
        header: {
            layoutType: string;
            highlightedButton: string;
        }
    }
}
```

The type of the `stuff` property on `LoadOutput` is `Partial<App.Stuff>`, and that makes sense, since you shouldn't have to specify every single stuff property in every load function. However, this fails to cover cases like above where the `stuff` object is more than one level deep.

### Describe the proposed solution

I think it would be better if you used `DeepPartial<App.Stuff>` instead. There's no `DeepPartial` type in the TypeScript standard library, but it exists in most popular TypeScript libraries such as [type-fest](https://github.com/sindresorhus/type-fest/blob/main/source/partial-deep.d.ts) or [ts-essentials](https://github.com/ts-essentials/ts-essentials#deep-wrapper-types).

### Importance

nice to have

**Comment by ignatiusmb** [comment]
The same way as discussed in #3788, I believe this should be handled in the user-defined interfaces itself as well. We can opt-in to have properties be optional, but having it be `Partial` recursively would make it really hard to opt out of the optionality.

You can always mark individual properties as optional, say `foo` may or may not be defined, but when it is, it will certainly have the `certainly_defined` property, so right now we can do an approach like the example below, but it would not be possible as is if we were to have `Partial` recursively

```ts
declare namespace App {
    interface Stuff {
        foo: {
            maybe?: boolean;
            certainly_defined: string;
            not_really?: number;
        }
    }
}
```

**Comment by Rich-Harris** [comment]
Agree, this needs to belong in userland. I'll close this as there's no action for SvelteKit to take
