### ISSUE TITLE
Prerender dependencies are written multiple times

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3784]
### Describe the bug

If two pages are prerendered, and both pages request the same file, that file will be written to the output directory twice. If building with `svelte-kit build --verbose`, it will be logged twice.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ypvoq7

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 78.02 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: workspace:* => 1.0.0-next.18 
    @sveltejs/kit: workspace:* => 1.0.0-next.260 
    @sveltejs/site-kit: ^2.0.2 => 2.0.2 
    svelte: ^3.43.0 => 3.44.2
```

### Severity

annoyance

**Comment by MangioneAndrea** [comment]
Isn't this to be closed as now the build is managed by vite?
