### ISSUE TITLE
Deep `stuff` merge 

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#3788]
### Describe the problem

In the section about [`stuff` returned by `load`](https://kit.svelte.dev/docs#loading-output-stuff) in the docs, it is stated that:
> This will be merged with any existing stuff and passed to the load functions of subsequent layout and page components.

This "merging" behavior means that if you, for example, do the following in `routes/__layout.svelte`:
```typescript
export function load() {
    return {
        stuff: {
            prop1: 'foo',
            prop2: 'bar',
        }
    };
}
```
and this in `route/someRoute.svelte`:
```typescript
export function load() {
    return {
        stuff: {
            prop2: 'something entirely different',
        }
    };
}
```
The resulting `stuff` would be:
```
{
    prop1: 'foo',
    prop2: 'something entirely different',
}
```
However, I noticed that SvelteKit only performs a "shallow" merge as opposed to a "deep" merge on `stuff`. This means that if your `stuff` has multiple levels of depth, the merging wouldn't take place for the deeper objects. For example:
`routes/__layout.svelte`:
```typescript
export function load() {
    return {
        stuff: {
            footer: {
                show: true,
                layout: 'normal',
            }
        },
    };
}
```
`route/someRoute.svelte`:
```typescript
export function load() {
    return {
        stuff: {
            footer: {
                layout: 'wide',
            }
        },
    };
}
```
The resulting `stuff` would be:
```javascript
{
    footer: {
        layout: 'wide',
    }
}
```
What I expected was:
```javascript
{
    footer: {
        show: true,
        layout: 'wide',
    }
}
```

### Describe the proposed solution

Do a deep merge on `stuff` instead.

### Alternatives considered

Currently, you have no choice but to keep the `stuff` object completely flat if you want to take advantage of the merging behavior.

### Importance

would make my life easier

### Additional Information

If you decide against this, I think it should at least be noted in the docs that the merging on `stuff` is shallow and is only performed on the first level of depth, so that users won't assume otherwise.

**Comment by Conduitry** [comment]
I'm +1 for documenting it, -1 for making it a deep merge.

**Comment by AradAral** [comment]
> I'm +1 for documenting it, -1 for making it a deep merge.

Okay, could you elaborate a bit on why you're against making it a deep merge? Would that be problematic?
Thanks.

**Comment by 7nik** [comment]
Thus you can get an object with an "impossible state" (e.g., an object has both mutually exclusive props). Or you alter the "type" of an object and old props can accidentally match with some optional props in the new object.
And, in case of the deep merge, you cannot fix these problems: you can set a property to `undefined`/`null`/smth else, but it still will be in the object and the operator `in` will see the property.

And I think I don't need to remind you that the `load` function receives the `stuff` object and you can deeply merge props you need.

**Comment by Rich-Harris** [comment]
Agree with @Conduitry — this absolutely belongs in userland, not in the framework:

```js
export function load({ stuff }) {
    return {
        stuff: {
            footer: {
                ...stuff.footer,
                layout: 'wide',
            }
        },
    };
}
```

**Comment by AradAral** [comment]
Okay, then I guess just documenting this would suffice.
Thanks.

**Comment by UltraCakeBakery** [comment]
> Agree with @Conduitry — this absolutely belongs in userland, not in the framework:
> 
> ```js
> export function load({ stuff }) {
>     return {
>         stuff: {
>             footer: {
>                 ...stuff.footer,
>                 layout: 'wide',
>             }
>         },
>     };
> }
> ```

The people of User Land could also do `delete stuff.footer` before merging.

**Comment by Rich-Harris** [comment]
closing this as `stuff` no longer exists
