### ISSUE TITLE
Can not parse json when using django restful framework backend 

### ISSUE THREAD

**Issue by xiayulu** [sveltejs/kit#3810]
### Describe the bug

I update SveltKit from next.196 to next.263 today, The following code: 

```html
<script context="module">
	export const load = async ({ fetch }) => {
		const res = await fetch(`http://127.0.0.1:8000/courses/`);
		return {
			props: {
				courses: res.ok && (await res.json())
			}
		};
	};
</script>

<script>
	export let courses;
</script>

{JSON.stringify(courses)}
```

Raised:

```shell
Unexpected token < in JSON at position 4
SyntaxError: Unexpected token < in JSON at position 4
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1781:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (index.svelte:6:30)
    at async load_node (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1810:12)
    at async respond$1 (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2165:15)
    at async render_page (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2366:19)
    at async resolve (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2609:11)
    at async respond (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2542:20)
    at async file:///C:/Users/24147/Desktop/test/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```

But, it works fine when using the previous version.

### Reproduction

I won't give a repo for this reasons:
- This issue is a little complex, because you have to build an django restful framework api
- I have solve this problem, see __Additional Information__
- I write down this for some one facing the same problem.
- May improve SveltKit

### Logs

```shell
Unexpected token < in JSON at position 4
SyntaxError: Unexpected token < in JSON at position 4
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1781:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (index.svelte:6:30)
    at async load_node (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1810:12)
    at async respond$1 (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2165:15)
    at async render_page (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2366:19)
    at async resolve (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2609:11)
    at async respond (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2542:20)
    at async file:///C:/Users/24147/Desktop/test/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
```

### System Info

```shell
Need to install the following packages:
  envinfo
Ok to proceed? (y) y

  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 8.73 GB / 15.83 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE      
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.17 => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.263
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

Finally, I sovle this problem.

The reason is: https://www.django-rest-framework.org/topics/browsable-api/

Django restful framework backend api is using  **browsable-api**. 
- If we open http://127.0.0.1:8000/courses/ in browser, we will get:

![image](https://user-images.githubusercontent.com/41274826/153342841-e30d03f1-dc91-4364-89e2-78f07d4140b7.png)

- If we use Postman, we will get:
![image](https://user-images.githubusercontent.com/41274826/153343021-1d96c137-7fc8-4b37-a1c9-41502d1d4867.png)

# Conclusion
The newer version of SveltKit fetch the `browsable-api` but not the json like Postman or older version。To solve this problem we have to force django restful framework return json data: http://127.0.0.1:8000/courses/?format=json

So, dose SveltKit rewrite `await respones.json()` ? If so, I hope improve this case.

**Comment by jasonlyu123** [comment]
Doesn't seem like a svelte kit problem. Possible you don't set the required header for your backend to return JSON.

**Comment by Tal500** [comment]
> ### Describe the bug
> 
> I update SveltKit from next.196 to next.263 today, The following code:
> 
> ```
> <script context="module">
> 	export const load = async ({ fetch }) => {
> 		const res = await fetch(`http://127.0.0.1:8000/courses/`);
> 		return {
> 			props: {
> 				courses: res.ok && (await res.json())
> 			}
> 		};
> 	};
> </script>
> 
> <script>
> 	export let courses;
> </script>
> 
> {JSON.stringify(courses)}
> ```
> 
> Raised:
> 
> ```shell
> Unexpected token < in JSON at position 4
> SyntaxError: Unexpected token < in JSON at position 4
>     at JSON.parse (<anonymous>)
>     at Proxy.<anonymous> (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1781:21)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async load (index.svelte:6:30)
>     at async load_node (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1810:12)
>     at async respond$1 (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2165:15)
>     at async render_page (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2366:19)
>     at async resolve (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2609:11)
>     at async respond (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2542:20)
>     at async file:///C:/Users/24147/Desktop/test/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
> ```
> 
> But, it works fine when using the previous version.
> ### Reproduction
> 
> I won't give a repo for this reasons:
> 
>     * This issue is a little complex, because you have to build an django restful framework api
> 
>     * I have solve this problem, see **Additional Information**
> 
>     * I write down this for some one facing the same problem.
> 
>     * May improve SveltKit
> 
> 
> ### Logs
> 
> ```shell
> Unexpected token < in JSON at position 4
> SyntaxError: Unexpected token < in JSON at position 4
>     at JSON.parse (<anonymous>)
>     at Proxy.<anonymous> (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1781:21)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async load (index.svelte:6:30)
>     at async load_node (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:1810:12)
>     at async respond$1 (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2165:15)
>     at async render_page (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2366:19)
>     at async resolve (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2609:11)
>     at async respond (file:///C:/Users/24147/Desktop/test/.svelte-kit/runtime/server/index.js:2542:20)
>     at async file:///C:/Users/24147/Desktop/test/node_modules/@sveltejs/kit/dist/chunks/index.js:244:24
> ```
> 
> ### System Info
> 
> ```shell
> Need to install the following packages:
>   envinfo
> Ok to proceed? (y) y
> 
>   System:
>     OS: Windows 10 10.0.19044
>     CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
>     Memory: 8.73 GB / 15.83 GB
>   Binaries:
>     Node: 16.13.1 - C:\Program Files\nodejs\node.EXE      
>     npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.43)
>     Internet Explorer: 11.0.19041.1202
>   npmPackages:
>     @sveltejs/adapter-auto: ^1.0.0-next.17 => 1.0.0-next.17
>     @sveltejs/kit: next => 1.0.0-next.263
>     svelte: ^3.44.0 => 3.46.4
> ```
> 
> ### Severity
> 
> serious, but I can work around it
> ### Additional Information
> 
> Finally, I sovle this problem.
> 
> The reason is: https://www.django-rest-framework.org/topics/browsable-api/
> 
> Django restful framework backend api is using **browsable-api**.
> 
>     * If we open http://127.0.0.1:8000/courses/ in browser, we will get:
> 
> 
> ![image](https://user-images.githubusercontent.com/41274826/153342841-e30d03f1-dc91-4364-89e2-78f07d4140b7.png)
> 
>     * If we use Postman, we will get:
>       ![image](https://user-images.githubusercontent.com/41274826/153343021-1d96c137-7fc8-4b37-a1c9-41502d1d4867.png)
> 
> 
> # Conclusion
> 
> The newer version of SveltKit fetch the `browsable-api` but not the json like Postman or older version。To solve this problem we have to force django restful framework return json data: http://127.0.0.1:8000/courses/?format=json
> 
> So, dose SveltKit rewrite `await respones.json()` ? If so, I hope improve this case.

As a Django user by myself, I agree with @jasonlyu123 that it's probably not an issue with SvelteKit, but issue in your code, and I will give the appropriate solution here. However, it is weird that you had a different behavior on different SvelteKit version. I think it will be usefull if you could reproduce the different effects in both version of SvelteKit. Either it is a different behavior due to your setup, or a different behavior due to SvelteKit change of code (which might lead to find a serious problem).

The "correct" solution is not to add query prams `?format=json`, it is intended only for the developer to force JSON result if the way I'll say now isn't available/convenient somehow.

The "correct" solution is to add the following HTTP headers to your fetch call:
```
headers: {
	'Accept': 'application/json',
	'Content-Type': 'application/json',
}
```

In HTTP protocol standards:
* The `Accept` says what format(s) the client expects to get the response from the server. (Which Django REST Frameword added additional way with`format` query)
* The `Content-Type` says what format(s) the current HTTP body is formatted. You rather keep it on `application/json` because somehow in your requests you add JSON data to the REST request.

**Comment by antony** [comment]
> This issue is a little complex, because you have to build an django restful framework api

This issue doesn't relate to SvelteKit, but in fact fetch. A reproduction would have shown that there are no issues with SvelteKit or fetch parsing JSON, the `<` character is indicative of you having received HTML, not JSON from your Django endpoint.

I'm happy that you've solved your problem, but next time please provide a reproduction of the issue as it will help you diagnose the issue faster.

**Comment by xiayulu** [comment]
Thanks for your advise.

I rewrite my code to:

```js
    const res = await fetch(`http://127.0.0.1:8000/courses/`, {
      headers: {
        Accept: 'application/json',
      },
    });
    return {
      props: {
        courses: res.ok && (await res.json()),
      },
    };
```

It works. This method is better 👍 .
