### ISSUE TITLE
Pathless layout routes

### ISSUE THREAD

**Issue by mekto** [sveltejs/kit#3832]
### Describe the problem

Found this in Remix documentation - https://remix.run/docs/en/v1/api/conventions#pathless-layout-routes.
This seems to be pretty usesful. It allows wrapping routes with different layouts but without adding unnecessery segments to the URL or using reset layouts.

```
routes/
  ├── __app/
  |   ├── __layout.svelte
  │   ├── dashboard.svelte
  │   └── [userId]/
  │   │   └── profile.svelte
  ├── __auth/
  |   ├── __layout.svelte
  │   ├── signin.svelte
  │   ├── signup.svelte
  │   ├── reset-password.svelte
  └── __marketing/
  |   ├── __layout.svelte
  │   ├── index.svelte
  │   └── product.svelte
```

So `/dashboard`, `/signin`, `/product` will be at root level, but with different layouts. Directories `__app`, `__auth`, `__marketing` won't apper in the URLs.

### Describe the proposed solution

Any `__directory` starting with two underscores would create a group which could have it's one layout. The directory itself won't be added to the URL.

### Alternatives considered

It is not easily doable with current implementation. It will require some `__layout.reset.svelte` files or adding segments to the URL.
E.g. just to use different layout for `/signin`, `/signup` you need to create subfolders with index files:

```
routes/
  ├── signin/
  |   ├── __layout.reset.svelte
  │   ├── index.svelte
  ├── signout/
  |   ├── __layout.reset.svelte
  │   ├── index.svelte
  ...
  ├── __layout.svelte
  ├── dashboard.svelte
```

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
The idea we were playing around with was using a special character like `!` to denote these, since the double underscore prefix is reserved for future SvelteKit-specific stuff (we can't allow things like `__app` and `__auth` because then adding something like `__middleware` would be a breaking change). In other words:

```
routes/
  ├── !app/
  |   ├── __layout.svelte
  │   ├── dashboard.svelte
  │   └── [userId]/
  │   │   └── profile.svelte
  ├── !auth/
  |   ├── __layout.svelte
  │   ├── signin.svelte
  │   ├── signup.svelte
  │   ├── reset-password.svelte
  └── !marketing/
  |   ├── __layout.svelte
  │   ├── index.svelte
  │   └── product.svelte
```

**Comment by Rich-Harris** [comment]
This is now solved with [named layouts](https://kit.svelte.dev/docs/layouts#named-layouts):

```
src/routes/
├ __layout.svelte
├ __layout-app.svelte
├ __layout-auth.svelte
├ [userId]/
│ └ profile@app.svelte
├ dashboard@app.svelte
├ index.svelte
├ product.svelte
├ reset-password@auth.svelte
├ signin@auth.svelte
└ signup@auth.svelte
```

In our view it's quite a lot better than the pathless layout route solution — it keeps the route structure and the file structure in sync (without which conflicts between `__x/foo` and `__y/foo` are all but guaranteed on a long enough timescale), and gives you more flexibility.

**Comment by mekto** [comment]
Thank you @Rich-Harris and the team. The named layouts seem to be a better approach, great work!
