### ISSUE TITLE
Links to documentation pages make problems

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#3836]
### Describe the bug

I noticed two bugs:

1. link to e.g. https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete doesn't work because it moves the page to the absolute top. Every opening in a new tab has this bug.
2. At one point the page title was Hooks, even though I was in the Anchor options section. I was skipping with the PREVIOUS button. But I can't reproduce it.

### Reproduction

1. Open https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete and see.
2. Nie umiem.

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 2.73 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.17.0 - /usr/bin/npm
  Browsers:
    Firefox: 87.0
```

### Severity

annoyance

**Comment by bootsa** [comment]
>1. link to e.g. https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete doesn't work because it moves the page to the absolute top. Every opening in a new tab has this bug.

"Not on my machine" - the example works as expected.

```
  System:
    OS: Linux 5.13 Linux Mint 20.3 (Una)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 601.65 MB / 15.38 GB
  Browsers:
    Brave Browser: 98.1.35.101
    Chromium: 98.0.4758.80
    Firefox: 97.0
```

Base docs [url](https://kit.svelte.dev/docs) and old links are broken though, see #3859

**Comment by lukaszpolowczyk** [comment]
@bootsa It's working for me now too. Apparently they have fixed it now.
