### ISSUE TITLE
Search results in new docs search engine are blurry to my eyes - accessibility

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#3837]
### Describe the bug

Just the fonts are not clear enough, they should be more contrasting.
![obraz](https://user-images.githubusercontent.com/16800535/153540863-fa921b9e-c26f-4fcd-9f0b-157e7b2444f7.png)

(The same problem is in the selected REPLs in https://svelte.dev/apps - they are also very blurry when selected)
![obraz](https://user-images.githubusercontent.com/16800535/153540841-186d2917-c79a-43f6-bba6-447224d2827d.png)

### Reproduction

Go to https://kit.svelte.dev/, type something in the search engine and see.

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 2.73 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.17.0 - /usr/bin/npm
  Browsers:
    Firefox: 87.0
```

### Severity

annoyance

**Comment by geoffrich** [comment]
Additional context from search PR: https://github.com/sveltejs/kit/pull/3717#discussion_r800106735

**Comment by dummdidumm** [comment]
Contrast in the search is a little better now - is it sufficient for you now?

**Comment by lukaszpolowczyk** [comment]
@dummdidumm It's still bad.
See, even Firefox DevTools hints that the contrast is too low: `#999999`
![obraz](https://user-images.githubusercontent.com/16800535/179735740-54156037-0c04-404d-81ba-c5ee381f4bc7.png)

In Firefox DevTools more or less this value is AA: `#737373`
![obraz](https://user-images.githubusercontent.com/16800535/179735906-02611c4a-3b54-46ab-8216-75c27ad3e95e.png)

Or even the AAA value: `#4d4d4d`
![obraz](https://user-images.githubusercontent.com/16800535/179735214-9f1fcbad-f302-4e04-a9a7-eeb0e97fdea2.png)
