### ISSUE TITLE
Prerendered dependencies are SSR'd in production

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3849]
### Describe the bug

The second half of #3848 — https://kit.svelte.dev/docs is failing at the moment because (AFAICT) it's attempting to server-render `/docs.json` which was (necessarily, because it uses the filesystem) prerendered during build.

SvelteKit has logic for loading e.g. `static/docs.json` via `fetch` rather than attempting to server-render it here... https://github.com/sveltejs/kit/blob/d788cf27e0f6014bd0773c70e6200f2bfe6d96ef/packages/kit/src/runtime/server/page/load_node.js#L162-L176 ...but it's not applying that same logic to files that were generated during prerendering.

### Reproduction

go to https://kit.svelte.dev/docs

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 89.55 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.1
  npmPackages:
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.32 => 1.0.0-next.32 
    svelte: ^3.44.2 => 3.44.2 
    vite: ^2.8.0 => 2.8.0
```

### Severity

serious, but I can work around it

**Comment by tcc-sejohnson** [comment]
Hey @Rich-Harris,

I was looking at this one as an issue I might try to take off of your plate, but I can't replicate. Visiting `https://kit.svelte.dev/docs` correctly redirects to `/docs/introduction` on both Chrome and Firefox (I tried in incognito/private windows as well). Was this fixed at some point?

**Comment by Rich-Harris** [comment]
It was, yeah. I think this can probably be closed
