### ISSUE TITLE
Using a import type statement in app.d.ts breaks

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/kit#3853]
### Describe the bug

Currently when I use a import type statement in app.d.ts (where my app types are) it will no longer work. I know it's just this statement as when I use an alternative like `import('magic-sdk').MagicUserMetadata` in the typedef it works fine

### Reproduction

In this example I am using MagicUserMetadata, when I add the import the user and test fields no longer work

```ts
import type { MagicUserMetadata } from 'magic-sdk';

/// <reference types="@sveltejs/kit" />

// See https://kit.svelte.dev/docs#typescript
// for information about these interfaces
declare namespace App {
    interface Locals {
        test: boolean;
        user: MagicUserMetadata;
    }

    interface Platform {}

    interface Session {}

    interface Stuff {}
}
```

### System Info

```shell
System:
    OS: Linux 5.16 undefined
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.9.1/bin/yarn
    npm: 7.24.2 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Chromium: 98.0.4758.80
    Firefox: 96.0.3
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.43 
    @sveltejs/kit: next => 1.0.0-next.266 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
This is how typescript works, it stops treating a d.ts file as ambient as soon as there's an import or export statement. Since this came up twice already I think we should document that a little in the file and in the docs

**Comment by jchanes04** [comment]
Neither of the solutions proposed there are working for me, currently using next.267. It seems like it is always referencing the ambient-modules.d.ts file inside of node_modules no matter what I put inside of app.d.ts.

**Comment by ghostdevv** [comment]
Could you share your app.d.ts @jchanes04

**Comment by StephenGrider** [comment]
Use an `import()`.

```
/// <reference types="@sveltejs/kit" />

declare namespace App {
	type _Session = import('$services/types').Session;

	interface Locals {
		session: _Session;
	}

	interface Platform {}

	interface Session extends _Session {}

	interface Stuff {}
}
```
