### ISSUE TITLE
An empty style-tag is appended to head every time an element with a transition-directive is mounted

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#3854]
### Describe the bug

Look at title

### Reproduction

Skeleton sveltekit project with minimum svelte-code to reproduce bug: https://github.com/MathiasWP/sveltekit-transition-stylesheet-bug

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 27.01 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.100
    Chrome: 98.0.4758.80
    Edge: 98.0.1108.43
    Firefox: 95.0.2
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.266 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

**Comment by MathiasWP** [comment]
This bug is also reproducable on a pure svelte project, so i am closing the issue here and moving it over to the svelte project instead.

**Comment by rmunn** [comment]
Svelte bug report link, in case anyone is looking for it: https://github.com/sveltejs/svelte/issues/7255
