### ISSUE TITLE
only require page components, not layout components, to export `prerender`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#386]
I had a hard time prerendering. It turns out I needed to set `prerender = true` in my `$layout.svelte` or else nothing would prerender. This wasn't clear to me. At the very least we should make sure to document this

**Comment by Rich-Harris** [comment]
Probably makes more sense to disregard `prerender` for layout components, the same as we do for `maxage`. No real reason to have to mark the entire component chain
