### ISSUE TITLE
Search results from Migrating from Sapper litter the search engine.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#3865]
### Describe the problem

A search in the docs turns up results with Migrating from Sapper.
What are the chances that you're looking for this? Practically none.
This is annoying, results from Migrating from Sapper litter the search engine.

### Describe the proposed solution

Move all results with Migrating from Sapper to the bottom of the search engine.
Or maybe even separate, specially marked.

### Alternatives considered

Remove from search results and separate Migrating from Sapper from the rest of the documentation.

### Importance

would make my life easier

**Comment by lukaszpolowczyk** [comment]
Can be closed because resolved here - https://github.com/sveltejs/kit/pull/4541

**Comment by mrkishi** [comment]
Thanks for the heads-up!
