### ISSUE TITLE
Expose the Vite dev server

### ISSUE THREAD

**Issue by brillout** [sveltejs/kit#3869]
### Describe the problem

[Telefunc](https://telefunc.com/) cannot be used with SvelteKit because Telefunc needs a reference to the Vite dev server which SvelteKit creates at:https://github.com/sveltejs/kit/blob/cf5d4aa54c3824a93967abe8508931854cd30524/packages/kit/src/core/dev/index.js#L92.

(Telefunc needs the Vite dev server to be able to run `vite.ssrLoadModule()` in order to `import.meta.glob('**/*.telefunc.*')`.)

### Describe the proposed solution

Expose the vite dev server.

For reference this is how Telefunc integrates with vite-plugin-ssr: https://github.com/vikejs/telefunc/blob/ff196287342b4ea3addbc0e0a559eef680f73796/examples/vite-plugin-ssr/server/index.js

Note how the Vite dev server is set to `telefuncConfig.viteDevServer` here: https://github.com/vikejs/telefunc/blob/ff196287342b4ea3addbc0e0a559eef680f73796/examples/vite-plugin-ssr/server/index.js#L23

@benmccann mentioned that there is PR to make the Vite dev server accessible, any chance to get it merged?

CC @phiberber who is working on a SvelteKit + Telefunc example.

### Importance

i cannot use SvelteKit without it

**Comment by bluwy** [comment]
Related #2921

**Comment by benmccann** [comment]
Here's the PR for reference: https://github.com/sveltejs/kit/pull/2663. But we didn't want to expose the dev server or component loading unless absolutely necessary

I'm not entirely sure you'd need it for what you're attempting. The `hooks` are loaded via `ssrLoadModule`: https://github.com/sveltejs/kit/blob/2fefa5e9cf01510dd03c1a9cc0b62c9686621faa/packages/kit/src/core/dev/plugin.js#L177

As a result, anything loaded in the hooks should generally be transitively loaded by Vite's `ssrLoadModule`. Is there some way that telefunc's API could be changed to simply do a standard `import` and not require access to the `ViteDevServer`? I believe it should just work in that case

**Comment by dougmoscrop** [comment]
I would like to run the dev server in-process; I don't need access to the internals, an opaque function that takes (req, res, next) or Web Fetch versions would be fine.  I guess this actually also asks for a programmatic interface to SvelteKit.

**Comment by phiberber** [comment]
> @phiberber also said he was able to grab it from a Vite plugin as another solution:
> 
> ```
> {
>   name: "telefunc-config",
>   configureServer(viteDevServer) {
>     telefuncConfig.viteDevServer = viteDevServer;
>   }
> }
> ```

This is now implemented in the Telefunc vite plugin.

> I would like to run the dev server in-process; I don't need access to the internals, an opaque function that takes (req, res, next) or Web Fetch versions would be fine. I guess this actually also asks for a programmatic interface to SvelteKit.

I think that you can use of Svelte Kit [Endpoints](https://kit.svelte.dev/docs/routing#endpoints) to that, if not maybe an express-like middleware system written with Svelte Kit [hooks](https://kit.svelte.dev/docs/hooks) fullfills your needs, not sure how recommended is it though.

**Comment by Rich-Harris** [comment]
If this relies on the dev server, how does it work in prod?

**Comment by Rich-Harris** [comment]
Going to close this now that we just use a regular Vite config
