### ISSUE TITLE
The builded .html files doesnt visualize correctly because href slashing

### ISSUE THREAD

**Issue by JTorresConsulta** [sveltejs/kit#3887]
### Describe the bug

When the build is runned to make an static site, it make links in html files with a previous slash /

For example:
<link rel="modulepreload" href="/_app/start-d800466a.js">

href="/ <-----

Then, navigators can`t visualize the html builded correctly because the relative route is not correct ...

### Reproduction

`npm run build`

See the code of the html in build folder

### System Info

```shell
npm run build
```

### Severity

annoyance

**Comment by NaincyKumariKnoldus** [comment]
Hey @JTorresConsulta Can I solve this please?

**Comment by JTorresConsulta** [comment]
clear reproduction:

1. npm install
2. npm build
3. Open the source code of the index.html builded
4. Note that the css and js links href has a slash in the init URL

href="/ <-----

Navigators can`t visualize correctly because the .css or .js route is bad

**Comment by antony** [comment]
I understand that there is a slash at the start of the url, that's because the link is designed to be relative to the root of the app.

You have options for modifying where the assets are hosted: https://kit.svelte.dev/docs/configuration#appdir

In future, it's helpful if you provide a use-case for **why** you think something is wrong - rather than just "is bad" which doesn't help us understand your expectation.

**Comment by JTorresConsulta** [comment]
Excuse my bad english.
I work on windows, VSC and Node.js 16.

I already know what a relative path is. Obvious

All the browsers that I have installed on my computer (chrome, firefox, brave...) do not correctly interpret the bar at the beginning.
For browsers to display correctly the beginning of the path must be, or without init slash, or with ./  (dot slash)

`<link rel='stylesheet' href='/build/bundle.css'>`  -- not working

`<link rel='stylesheet' href='build/bundle.css'>`  -- works
`<link rel='stylesheet' href='./build/bundle.css'>`  -- works

**Comment by AndreReynosoPeru** [comment]
> Excuse my bad english. I work on windows, VSC and Node.js 16.
> 
> I already know what a relative path is. Obvious
> 
> All the browsers that I have installed on my computer (chrome, firefox, brave...) do not correctly interpret the bar at the beginning. For browsers to display correctly the beginning of the path must be, or without init slash, or with ./ (dot slash)
> 
> `<link rel='stylesheet' href='/build/bundle.css'>` -- not working
> 
> `<link rel='stylesheet' href='build/bundle.css'>` -- works `<link rel='stylesheet' href='./build/bundle.css'>` -- works

Hi bro, can you solve this problem in svelte, no sveltekit, in the docs page from svelte I cannot see anything for config the "./" I have the same issue and I thought svelte does not work with php apache server in windows, I hope you can tell me an answer. PD. Sorry for my english
