### ISSUE TITLE
Can't set `browser.hydrate` to `false`

### ISSUE THREAD

**Issue by nosovk** [sveltejs/kit#3896]
### Describe the bug

Switching to SPA mode fails.
Goal is to completely disable svelte kit router and server side rendering to create simple one page application, which still uses `$page.url.searchParams` to read state from url (like https://gist.github.com/nosovk/c1c7d43071bf2b10bd6b50dd80e2eabc).

Steps to switch Kit app to SAP mode.

1. modify hooks.js to set ssr to false - https://github.com/nosovk/spa-mode-fails/commit/5c9a9f4ae78947fffe8f56c723e1ca268a439884
2. modify svelte.config to add `kit.browser.hydrate=false` - https://github.com/nosovk/spa-mode-fails/commit/242ea161026adb9f4dfa9feb8e69dddc1c40c8f5
3. build application and observe error: ```Error: options.hydrate only works if the component was compiled with the `hydratable: true` option` ```

actually hydrate explicitly disabled in config, but Kit expects to see it in enabled state.

Expected behavior: disabling hydrate should disable hydrate without broking application.

### Reproduction

repo vs reproduction: https://github.com/nosovk/spa-mode-fails
deployed url: https://spa-mode-fails.vercel.app/

### Logs

```shell
proxy.js:15 [HMR][Svelte] Unrecoverable error in <Root>: next update will trigger a full reload
logError @ proxy.js:15
await in logError (async)
handle_navigation @ start.js:832
_navigate @ start.js:425
goto @ start.js:301
start @ start.js:1497
(anonymous) @ (index):14
root.svelte? [sm]:50 Uncaught (in promise) Error: options.hydrate only works if the component was compiled with the `hydratable: true` option
    at Object.claim [as l] (root.svelte? [sm]:50:13)
    at init (index.mjs:1883:40)
    at new Root (root.svelte? [sm]:16:25)
    at createProxiedComponent (svelte-hooks.js:266:9)
    at new ProxyComponent (proxy.js:239:20)
    at new Proxy<Root> (proxy.js:346:11)
    at Renderer._init (start.js:968:15)
    at Renderer.update (start.js:886:9)
    at async Renderer.handle_navigation (start.js:832:3)
    at async Router._navigate (start.js:425:3)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 3.83 GB / 31.88 GB
  Binaries:
    Node: 16.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.22.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.28 => 1.0.0-next.28
    @sveltejs/kit: next => 1.0.0-next.267
    svelte: ^3.46.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

for my current project switching to `kit.browser.hydrate=true` is acceptable, but if somebody needs SPA only mode it could be troublesome.

**Comment by dummdidumm** [comment]
This condradicts each other. You want an SPA, but you disable hydration and the router, which means no JavaScript should be sent to the browser, which means an SPA is impossible. This is also mentioned in the docs: https://kit.svelte.dev/docs/page-options#hydrate

**Comment by dummdidumm** [comment]
If you want to use Vite without using any of Kit's feature, you may be better served with using a barebones Vite starter template like this one: https://github.com/vitejs/vite/tree/main/packages/create-vite/template-svelte

Closing as this works as designed, you can't disable SSR and hydration/router at the same time.
