### ISSUE TITLE
Redirect in shadow endpoint `post()` function results in attempt to POST to new location

### ISSUE THREAD

**Issue by georgecrawford** [sveltejs/kit#3909]
### Describe the bug

I honestly don't know what's desired here, but I've observed that a `307 Redirect` in a `post()` shadow endpoint results in the browser attempting a second, unexpected _`POST`_ to the `Location` URL.

### Reproduction

**clearCookie.svelte**
```
<form method="post" action="/clearCookie">
    <button>Clear your cookie</button>
</form>
```

**clearCookie.js**
```
export async function post() {
    return {
        status: 307,
        headers: {
            location: '/',
            'set-cookie': [
                'my-cookie-name=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT',
            ],
        },
    };
}
```

Clicking the button results in the following:

1. browser issues `POST` to `https://domain.com/clearCookie`, with response:
```
location: /
set-cookie: my-cookie-name=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT
```
2. browser issues unexpected `POST` to `https://domain.com` with response `Status Code: 405 Method Not Allowed` and error:
```
Error: post method not allowed
    at load_shadow_data (file:///app/server/.svelte-kit/runtime/server/index.js:1878:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load_node (file:///app/server/.svelte-kit/runtime/server/index.js:1550:5)
    at async respond$1 (file:///app/server/.svelte-kit/runtime/server/index.js:2169:15)
    at async render_page (file:///app/server/.svelte-kit/runtime/server/index.js:2370:19)
    at async resolve (file:///app/server/.svelte-kit/runtime/server/index.js:2602:11)
    at async handle (//app/server/src/hooks:299:22)
```

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (6) arm64 unknown
    Memory: 9.57 GB / 15.60 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.67 => 1.0.0-next.67
    @sveltejs/kit: ^1.0.0-next.269 => 1.0.0-next.269
    svelte: ^3.46.2 => 3.46.2
```

### Severity

serious, but I can work around it

### Additional Information

I've seen discussion elsewhere (sorry, I'm not able to find it now) that this is a misuse of shadow endpoints, and that the client should perform a redirect with `goto()` or similar. But it seems OK to me. I'd love to get some guidance about whether we consider this a bug or can improve the documentation to explain a better approach.

Thanks!

**Comment by georgecrawford** [comment]
@babichjacob Sorry to ping you, but I dimly remember the comment about this being a misuse of shadow endpoints coming from you. I may be mistaken! If it was, could you link the issues and let me know your thoughts about this specific case? Thanks so much.

**Comment by Conduitry** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307 This is what a 307 means. The browser should redirect and reuse the method and body from the original request.

**Comment by georgecrawford** [comment]
Well damn. Thanks @Conduitry. I've always been a bit hazy on some of the 3xx codes, but 307 is precisely _not_ what I needed here. A `303` (`The server sent this response to direct the client to get the requested resource at another URI with a GET request`) gives me exactly the behaviour I was after. Thanks so much.
