### ISSUE TITLE
Clarify meaning of `shadow endpoint`.

### ISSUE THREAD

**Issue by baseballyama** [sveltejs/kit#3917]
### Describe the problem

I got the below error but I took time to understand the meaning of "shadow endpoint"

> Body returned from shadow endpoint request handler must be a plain object

This is because the document doesn't appear "shadow endpoint".

### Describe the proposed solution

Write the meaning of `Sahdow Endpoint` to the Document.

https://kit.svelte.dev/docs/routing#endpoints

> If an endpoint has the same filename as a page (except for the extension), the page will get its props from the endpoint. So a page like src/routes/items/[id].svelte could get its props from src/routes/items/[id].js:
> (Such an endpoint that fires without a `load` function is called `Shadow Endpoint`.)

(I added 2nd line but please correct the sentence if necessary....)

### Alternatives considered

Remove `Sahdow Endpoint` from the error message and use another sentence.

### Importance

nice to have

### Additional Information

If other users don't actually have this issue, please close it.

**Comment by Rich-Harris** [comment]
We should fix the error message rather than the documentation — 'shadow endpoints' are intended to be the default (i.e. just 'endpoints'), with 'standalone endpoints' being the exception

**Comment by baseballyama** [comment]
Thank you for answering!
Right. I created PR.

I have 1 question.
The word "Shadow" is used in Code also.
Should we refactor it?
I mean should we remove "Shadow" and add "Standalone"?

**Comment by netaisllc** [comment]
Consider more effective docs around this pattern.  Leaving the effectiveness of the pattern aside for the moment, I find the the docs are too quiet on the following points:
* what is the behavior of Kit when a route exists with both a `load` function and an endpoint of the same name?
* if both are executed in what order does that happen and what are the consequences?
* is the pattern of using both a really lame idea (which I assume it is)

**Comment by baseballyama** [comment]
> what is the behavior of Kit when a route exists with both a load function and an endpoint of the same name?
> if both are executed in what order does that happen and what are the consequences?

Right. I think we should add some sentences to the document.

> is the pattern of using both a really lame idea (which I assume it is)

Personally, I think it is better to avoid using endpoints and standalone endpoints at the same time from the point of view of code readability. (So IMO kit doesn't need to support it.)
