### ISSUE TITLE
Endpoints unable to return JSON response for POST request

### ISSUE THREAD

**Issue by serchavalos** [sveltejs/kit#3923]
### Describe the bug

I've started learning SvelteKit, and unless I'm missing something, I'm not able to create an endpoint to handle POST requests that return JSON

## Steps
1. Create a new project using `npm init svelte@next` with TypeScript support
2. Create a new endpoint as as `src/routes/index.ts` with a `post` handler that returns: `{ status: 201, body: { message: "submitted"}}`

## What I expected
To receive a `{ message: "submitted" }` after sending a request `POST /`

## What actually happened
Responded with the same HTML payload used for the SvelteKit Welcome page

You can see it in here
https://github.com/serchavalos/routing-debugging/commit/844587b082a0c019ca5e230bf40d6370496181b8

### System Info

```shell
System:
  OS: macOS 12.2
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 327.48 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
  Yarn: 1.22.17 - ~/.yvm/.yarn/shim/yarn
  npm: 8.4.1 - ~/.nvm/versions/node/v14.17.5/bin/npm
Browsers:
  Brave Browser: 89.1.21.74
  Chrome: 98.0.4758.80
  Edge: 98.0.1108.43
  Firefox: 88.0.1
  Safari: 15.3
  Safari Technology Preview: 15.4
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.17
  @sveltejs/kit: next => 1.0.0-next.269
  svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

### Additional Information

Like I said, I'm still learning, so I probably just missing something

**Comment by Conduitry** [comment]
If an endpoint and a page have the same URL, requests for that URL will go to the page unless you specify `Accept: application/json`, as f-elix noted.

**Comment by serchavalos** [comment]
@f-elix @Conduitry thanks!
