### ISSUE TITLE
Validate hash links when prerendering

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3955]
### Describe the problem

This is a relatively small thing, but it would be nice if the crawler could warn you if you prerender a page with a link like this...

```html
<a href="/docs/routing#advanced">advanced routing</a>
```

...and the `/docs/routing` page was updated:

```html
<h2 id="advanced-routing">Advanced routing</h2>
```

### Describe the proposed solution

When prerendering, keep track of which hash links have been requested, and whether they match `id` attributes on the destination page.

### Importance

nice to have

**Comment by mquandalle** [comment]
Would it be possible to generalize this hash link validation beyond pre-rendered pages?

**Comment by Rich-Harris** [comment]
In terms of runtime checking, no — the only way to see if a link is valid is to actually (attempt to) render the target. If we had a way of generating a typed route manifest, it might be possible to surface broken links, but that's a different problem and a very big can of worms.
