### ISSUE TITLE
service-worker.ts does not have the necessary TS types

### ISSUE THREAD

**Issue by maximedupre** [sveltejs/kit#3956]
### Describe the bug

`service-worker.ts` does not seem to have the necessary TS types. Not sure if you intended to support it. Not sure if there should be documentation addressing this potential issue. 

**Edit** It might just be an error with the IDEs (VSC, Stackblitz, etc), since there is no error at compilation 🤷🏻‍♂️

### Reproduction

Just added the `service-worker.ts` file with a small amount of code in it.

https://stackblitz.com/edit/sveltejs-kit-template-default-bmwfwd?file=service-worker.ts

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
    Memory: 1.75 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    npm: 8.1.3 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 98.0.4758.102
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.272 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

**Comment by maximedupre** [comment]
I added 

``` json
"lib": ["es2020", "DOM", **"webworker"**]
```

to `tsconfig.json` and

``` typescript
declare var self: ServiceWorkerGlobalScope;
```

at the top of my `service-worker.ts`.

Perhaps this should be the default `tsconfig.json` for new projects? Or is there a better way to handle typings in service workers?

🙏

**Comment by bluwy** [comment]
We could also use `tsconfig` [references](https://www.typescriptlang.org/tsconfig#references), to isolate the webworker typings for `service-worker.ts` only. Something like [this](https://github.com/vitejs/vite/blob/main/packages/create-vite/template-preact-ts/tsconfig.json) which reference another tsconfig for node only. This would make the configuration a bit complex though, and I'm not sure what's the right call here.

**Comment by Rich-Harris** [comment]
@bluwy would this be simpler now that we have `.svelte-kit/tsconfig.json`?

**Comment by bluwy** [comment]
Yes! I think with that we can abstract away the configuration now.

**Comment by dummdidumm** [comment]
addressed in https://kit.svelte.dev/docs/service-workers#type-safety
