### ISSUE TITLE
If pollInterval detects a new version and I click on a not existent link it redirects sine fine

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#3957]
### Describe the bug

After https://github.com/sveltejs/kit/pull/3412 if I have an app with `adapter-static` with this config:

```ts
version: {
  name: Date.now().toString(),
  pollInterval: 5 * 1000,
}
```

if the polling detects the update and I click on a link for a page which doesn't exists instead of rendering the `__error.svelte` page it keeps in an infinite redirect.

### Reproduction

https://github.com/frederikhors/iss-poll-404

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.50)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.28 => 1.0.0-next.28
    @sveltejs/kit: 1.0.0-next.269 => 1.0.0-next.269
    svelte: 3.46.4 => 3.46.4
```

### Severity

blocking an upgrade

**Comment by baseballyama** [comment]
@frederikhors 

Could you please publish https://github.com/frederikhors/iss-poll-404 ?
I can not access to this repo.

**Comment by frederikhors** [comment]
The repro is [here](https://github.com/frederikhors/iss-kit-polling-404) but I cannot reproduce it right now. I think this has something to do with my project which uses a custom sw.

I'll close for now. Thank you @baseballyama.

**Comment by jycouet** [comment]
@frederikhors you might be able to help me?
I have something wrong with `pollInterval` I think.

This: https://github.com/sveltejs/kit/pull/3412 seems out of date, no?
How do you reload onError? (MP everywhere ;) )

**Comment by frederikhors** [comment]
`pollInterval` works for me. What is your problem?

**Comment by frederikhors** [comment]
```ts
import { updated } from '$app/stores';

updated.subscribe(async (value) => {
  if (value) {
    if (sw) {
      // handle sw update
    } else {
      window.location.reload();
    }
  }
});
```

**Comment by jycouet** [comment]
Isn't it too "**hard**" for your users a reload directly?
What if he was typing something?

How do you test the behavior? 
because in `dev`, value never goes to true
same in `preview`, value never goes to true

Thx for your help :)

**Comment by jycouet** [comment]
Thx, I'll do the same 😅

**Comment by MAYANK-M31** [comment]
> ```ts
> import { updated } from '$app/stores';
> 
> updated.subscribe(async (value) => {
>   if (value) {
>     if (sw) {
>       // handle sw update
>     } else {
>       window.location.reload();
>     }
>   }
> });
> ```

How to test this in Development Mode ?
