### ISSUE TITLE
adapter-static 1.0.0-next.28 ignores svelte.config.js kit.paths.base for static assets

### ISSUE THREAD

**Issue by nstuyvesant** [sveltejs/kit#3959]
### Describe the bug

Images for a website generated by adapter-static are not loading because the site does not run off of the website root.

Relevant part of svelte.config.js...
```javascript
	kit: {
		adapter: adapter({
			pages: 'public',
			assets: 'public'
		}),
		paths: {
			base: '/front-end/example-svelte'
		}
	}
```

Did an `npm run build` and deployed the content to GitLab Pages. The site was generally functional but gave 404s for every image in my assets folder. The browser tried to load these from the root website instead of /front-end/example-svelte.

This is what was created in /public/index.html (public is my build folder per the svelte.config.js setting above). Note that the paths property for the start() method looks correct...
```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Salesforce Svelte</title>
		<meta charset="utf-8" />
		<meta name="description" content="" />
		<link rel="icon" href="/front-end/example-svelte/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="icon" href="/front-end/example-svelte/images/logo-light.svg" type="image/svg+xml"/>
		<meta http-equiv="content-security-policy" content="">
	<link rel="modulepreload" href="/front-end/example-svelte/_app/start-4c099fc5.js">
	<link rel="modulepreload" href="/front-end/example-svelte/_app/chunks/vendor-fbfd3ada.js">
	<link rel="modulepreload" href="/front-end/example-svelte/_app/chunks/preload-helper-f2490223.js">
	</head>
	<body>
		<div>
		<script type="module" data-hydrate="45h">
		import { start } from "/front-end/example-svelte/_app/start-4c099fc5.js";
		start({
			target: document.querySelector('[data-hydrate="45h"]').parentNode,
			paths: {"base":"/front-end/example-svelte","assets":"/front-end/example-svelte"},
			session: {},
			route: true,
			spa: true,
			trailing_slash: "never",
			hydrate: null
		});
	</script></div>
	</body>
</html>
```

The index.html loaded images correctly in the head because app.html uses `%svelte.assets%` for image URLs. Svelte components do not. They use relative URLs to load.

For example
```html
    <img class="check-circle" src="/images/icons/check-circle.svg" alt="check circle">
```

While I can manually add `import { base} from '$app/paths'` and pass this to each URL, I can't imagine this is the intended approach as it's extremely time-consuming.

### Reproduction

1. Create SvelteKit project
```bash
npm init svelte@next my-app
cd my-app
npm install @sveltejs/adapter-static@next
```

2. Modify **svelte.config.js**
```javascript
import adapter from '@sveltejs/adapter-static'
import preprocess from 'svelte-preprocess'

const production = process.env.NODE_ENV === 'production'
const base = production ? '/front-end/example-svelte': ''

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),

	kit: {
		adapter: adapter({
			pages: 'public',
			assets: 'public'
		}),
		paths: {
			base
		}
	}
}

export default config
```

3. Build the site
```bash
npm run build
```

4. Examine the generated /public/index.html file and verify paths passed to start() method are correct.
5. Set the contents of /public to load from your favorite web server at /front-end/example-svelte.
6. Access the site at http://yourserver/front-end/example-svelte and note the images do not load. Check the 404 errors in the console and you'll see they are trying to load from the website root.

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 703.45 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 97.0
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.28 
    @sveltejs/kit: next => 1.0.0-next.272 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I am trying to convince a team of **Angular** developers to switch to **SvelteKit** so I created a simple example in Angular 13.2.2 and SvelteKit 1.0.0-next.272.

I cannot show it to them with the workaround using `import { base } from '$app/paths'` or I'll miss the opportunity to win them over.

**Comment by nstuyvesant** [comment]
Possibly related to https://github.com/sveltejs/kit/issues/3726

**Comment by babichjacob** [comment]
> While I can manually add `import { base} from '$app/paths'` and pass this to each URL, I can't imagine this is the intended approach as it's extremely time-consuming.

It is the intended approach, I think, besides switching to [importing assets](https://kit.svelte.dev/faq#assets) which have base path following done for you.

**Comment by nstuyvesant** [comment]
As there is a capability to establish a base path, wondering what the rationale would be for having static assets ignore it. Why not have it apply to everything? I see I can provide an absolute path for kit.paths.assets but not one that is root-relative like base.

So I guess this is either:
1. A bug if it's not intended behavior, or...
2. Something needed to make SvelteKit simpler. SvelteKit strikes me as a great way to get away from all the boilerplate in Angular but all I had to do to make the Angular project ready for use on /front-end/example-angular was a single line in angular.json `"baseHref": "/front-end/example-angular/"`. With SvelteKit, I had to modify 15 Svelte components to add `import { base } from '$app/paths'` and then modify each and every reference to an image. PAINFUL.

**Comment by babichjacob** [comment]
It isn't just static assets, because links in your app would behave the same way. If SvelteKit didn't behave this way, it wouldn't be possible to reference assets that are external to SvelteKit (i.e. supplied by wherever you're hosting the app).

Consider looking into importing images and other assets (from anywhere in `src`) to use them without dealing with `base` path stuff. That would also set you on the right track for image optimization, like Vite's built-in inlining support for sufficiently small images, or something more advanced like [`vite-imagetools`](https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite).

**Comment by vekunz** [comment]
If you add the `base` tag to the head section of the HTML:

```html
<head>
    <base href="/front-end/example-angular/" />
</head>
```

and remove the slash from the image URL

```html
 <img class="check-circle" src="images/icons/check-circle.svg" alt="check circle">
```

then the browser should automatically use the base path as root for the image path.

**Comment by nstuyvesant** [comment]
Thanks @vekunz. Stepping back from this a bit, wondering why svelte.config.js's kit.paths.assets doesn't allow a relative URL.

Wouldn't that also solve the problem in perhaps a more elegant way?

**Comment by Rich-Harris** [comment]
`paths.assets` is intended for cases where your static assets are deployed to a CDN separately from your server, which is why it isn't relative.

All Angular's `baseHref` is doing, as far as I can tell, is injecting a `<base>` element. In my experience that's a bad idea with all sorts of unintended consequences (like breaking `url(#foo)` references inside SVG elements), and it's much better to be explicit about it. That can take two forms — prefixing the `src` with the imported `base` value, or adding the `<base>` element to `src/app.html` yourself (while accepting responsibility for the results of doing so!).

Another option is to take advantage of Vite's [static asset handling](https://vitejs.dev/guide/assets.html).

Did you try the `<base>` suggestion, and did it work? If so I think we can close this.

**Comment by nstuyvesant** [comment]
Yeah, angular's baseHref is just injecting the <base> element. But the workaround is effective... thanks for checking.
