### ISSUE TITLE
Non-SSR'd pages should be prerendered by default

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#3966]
### Describe the problem

While we recommend that people use SSR as widely as possible, some apps don't. In these cases, there's no obvious reason not to prerender the shell page.

### Describe the proposed solution

If a page is rendered with `ssr: false`, don't bail out during prerendering here, unless `export const prerender` is explicitly `false` (to provide an escape hatch when the app is doing something funky in `handle`): https://github.com/sveltejs/kit/blob/b5cf676d30515b2168238064169d754276a7d5bc/packages/kit/src/runtime/server/page/respond.js#L70-L76

### Alternatives considered

The alternative is to continue dynamically server-rendering empty pages. Totally fine, since rendering an empty page is cheap, but wasteful nonetheless.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
occurs to me that this is technically a breaking change, so added to 1.0

**Comment by Tal500** [comment]
Though this feature sounds awesome, this amplifies the problems with removing the option of disabling prerendering, as I said:

> Today, you can disable that with `config.kit.prerender.enabled = false`. But if we're leaning more in this direction, we would probably need to get rid of that option.
> 
> For my testing, I like to build some projects locally with prerendering disabled (for debugging prerendering issues and also for faster build time). Therefore, removing the options to (temporary) disable prerendering is not preferable for me, and I believe also for other people.
> 
> I do agree that this configuration in `svelte.config.js` is problematic. **As a compromise, maybe except some environment variable to disable prerendering or such?**
> 
_Originally posted by @Tal500 in https://github.com/sveltejs/kit/discussions/7716#discussioncomment-4371528_

Though this problem was amplified, the solution seems to be more clear now - perhaps add a configuration of `prerendering`, to be one of these three states:
1. `'disabled'`: No prerendering, ignoring each page settings.
2. `'strict'`: Prerender each page if and only if in the page settings `prerender === true`.
3. `'lax'`: Prerender each page if and only if in the page settings `prerender !== false`.

**Comment by Rich-Harris** [comment]
I'm not totally sure I see the problem — you could prevent the prerendering from happening just by passing `entries: []` (which you're probably already doing if you can't run `handle` inside `build`) or adding `prerender = false` alongside `ssr = false`.

**Comment by Tal500** [comment]
> I'm not totally sure I see the problem — you could prevent the prerendering from happening just by passing `entries: []` (which you're probably already doing if you can't run `handle` inside `build`) or adding `prerender = false` alongside `ssr = false`.

OK, missed that option. Tnx

**Comment by dummdidumm** [comment]
Mhhm I think it's not as easy as we thought. We also have to bail if any `+page/layout.server.js` file is present, because the data could be dynamic and prerendering in this case when you didn't explicitly opt in feels wrong. This shrinks the use case quite a bit - still worth it?
