### ISSUE TITLE
Unable to use `index.svelte` with a shadow endpoint `index.ts`

### ISSUE THREAD

**Issue by kdheepak** [sveltejs/kit#3974]
### Describe the bug

I get the following error on internal routing to the root url:

```
404

Failed to load data

_load@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:22348
async*_get_navigation_result@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:19338
update@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:17196
handle_navigation@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:17109
_navigate@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:12898
init_listeners/<@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:10324
EventListener.handleEvent*init_listeners@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:9696
it@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:24041
async*@https://svelte-kit-test.kdheepak.com/:28:8
```

And I get the following in the console:

```
https://svelte-kit-test.kdheepak.com/__data.json
```

<img width="1440" alt="Screen Shot 2022-02-17 at 1 20 44 AM" src="https://user-images.githubusercontent.com/1813121/154434446-ebca3894-0cc3-4d1f-bda3-e809ce6ed8fa.png">

### Reproduction

Reproducible using https://github.com/kdheepak/svelte-kit-test and adapter-static, on github pages.

1) Go to <https://svelte-kit-test.kdheepak.com/>
2) Click on link that takes you to <https://svelte-kit-test.kdheepak.com/link>
3) Click on link that takes you to <https://svelte-kit-test.kdheepak.com/>

### Logs

```shell
_load@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:22348
async*_get_navigation_result@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:19338
update@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:17196
handle_navigation@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:17109
_navigate@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:12898
init_listeners/<@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:10324
EventListener.handleEvent*init_listeners@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:9696
it@https://svelte-kit-test.kdheepak.com/_app/start-f0f2a705.js:1:24041
async*@https://svelte-kit-test.kdheepak.com/:28:8
```

### System Info

```shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"                                       ─╯

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 4.47 GB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 17.1.0 - ~/miniconda3/bin/node
    npm: 8.1.2 - ~/miniconda3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.28
    @sveltejs/kit: next => 1.0.0-next.276
    svelte: ^3.46.4 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I believe the error has something to do with this:

https://github.com/sveltejs/kit/blob/905457befb1e558848b0f032031019b62ad08bef/packages/kit/src/runtime/client/renderer.js#L757-L764

This is the same issue that was occurring in https://github.com/sveltejs/kit/issues/3718. When I tested it, I thought I remember it not doing this any more and assumed it was fixed. I could be misremembering or it is possible that something else has caused a regression since then. Possibly related to https://github.com/sveltejs/kit/issues/3532.

**Comment by kdheepak** [comment]
fwiw I think I'm getting the same error when using `goto('/')` as well.

**Comment by madeleineostoja** [comment]
Yep I ran into this as well, had to move my `index.ts` shadow endpoint to a `home.json.ts` manual endpoint. It was fixed temporarily but seems to have regressed again — initial load works, but navigating back to index results in a faulty data fetch
