### ISSUE TITLE
Failed to fetch dynamically imported module

### ISSUE THREAD

**Issue by knajjars** [sveltejs/kit#3978]
### Describe the bug

Hi, we are using SvelteKit on production for a while now and recently added Sentry to monitor errors.

Some of our settings:
* SSR: `off`
* Pre-render: `disabled`
* adapter: `static`
* hosting: `netlify`
* it's a SPA (we have `fallback` to `index.html`)

The error log looks something like this:
`Failed to fetch dynamically imported module: https://<our_page.com>/_app/pages/index.svelte-91a57275.js`

And the odd thing is that it does not happen on any particular route and not always, but often enough.

### Reproduction

It is not reproducible on development and it happens randomly. Probably something to do with SPA?

### Logs

```shell
TypeError: 'text/html' is not a valid JavaScript MIME type.
Failed to fetch dynamically imported module: https://<our_page.com>/_app/pages/index.svelte-91a57275.js
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 31.21 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.2 - ~/.nvm/versions/node/v14.17.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 7.23.0 - ~/.nvm/versions/node/v14.17.2/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 98.0.4758.102
    Firefox: 97.0
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.28 => 1.0.0-next.28
    @sveltejs/kit: ^1.0.0-next.266 => 1.0.0-next.266
    svelte: ^3.45.0 => 3.45.0
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Does that JS file that's failing to load exist or not?

This is presumably a result of filenames changing when your site is redeployed. The experience there to users should be improved by #3412, but I don't know that you're going to be able to avoid Sentry complaining about it.

I'm also increasingly of the opinion that using something like Sentry to report all uncaught browser exceptions is basically useless as a way to find out when things are going wrong, because of the number of badly behaved browser extensions and network issues and so on that will report tons of errors that don't actually indicate that anything is wrong and that you can't do anything about.

**Comment by knajjars** [comment]
> Does that JS file that's failing to load exist or not?
> 
> This is presumably a result of filenames changing when your site is redeployed. The experience there to users should be improved by #3412, but I don't know that you're going to be able to avoid Sentry complaining about it.
> 
> I'm also increasingly of the opinion that using something like Sentry to report all uncaught browser exceptions is basically useless as a way to find out when things are going wrong, because of the number of badly behaved browser extensions and network issues and so on that will report tons of errors that don't actually indicate that anything is wrong and that you can't do anything about.

~90% of the time the file exists, but when it fails it's not there of course. When it fails and the page is reloaded the missing index suddenly appears. I agree with not relying on Sentry to capture all uncaught errors, but this particular error has been quite high relative to the amount of traffic we are getting.

**Comment by knajjars** [comment]
> try to put a` .` before the slash` /` . It was working for me but the problem is how to perform this programmatically!

where should I do this?

**Comment by el-schneider** [comment]
I'm also suddenly getting very similar errors and while my build is not failing the deployed website isn't working.

**Comment by goynang** [comment]
I'm also now hitting something very similar as well on Netlify. Occurred for me when I upgraded Kit from 272 to 278. Rolling back to previous deploy **has** got my site back up so not quite the same experience as @el-schneider but this all sounds very similar.

The error at runtime in my case is...

```JSON
{
    "errorType": "Error",
    "errorMessage": "Dynamic require of \"buffer\" is not supported",
    "trace": [
        "Error: Dynamic require of \"buffer\" is not supported",
        "    at __require (file:///var/task/.netlify/functions-internal/render.js:28:9)",
        "    at node_modules/safe-buffer/index.js (file:///var/task/.netlify/functions-internal/render.js:5730:18)",
        "    at __require2 (file:///var/task/.netlify/functions-internal/render.js:34:44)",
        "    at node_modules/jws/lib/sign-stream.js (file:///var/task/.netlify/functions-internal/render.js:6261:19)",
        "    at __require2 (file:///var/task/.netlify/functions-internal/render.js:34:44)",
        "    at node_modules/jws/index.js (file:///var/task/.netlify/functions-internal/render.js:6441:22)",
        "    at __require2 (file:///var/task/.netlify/functions-internal/render.js:34:44)",
        "    at node_modules/jsonwebtoken/decode.js (file:///var/task/.netlify/functions-internal/render.js:6474:15)",
        "    at __require2 (file:///var/task/.netlify/functions-internal/render.js:34:44)",
        "    at node_modules/jsonwebtoken/index.js (file:///var/task/.netlify/functions-internal/render.js:8531:15)"
    ]
}
```

**Comment by goynang** [comment]
To follow up on how I solved my problem, in case it helps…

I removed…

```toml 
[functions]
    node_bundler = "esbuild"
```

…which I had added a while back to resolve some other problem building on Netlify. With that gone everything builds fine for me again now (including with latest version of kit). Until next time I guess.

**Comment by el-schneider** [comment]
> To follow up on how I solved my problem, in case it helps…
> 
> I removed…
> 
> ```toml
> [functions]
>     node_bundler = "esbuild"
> ```
> 
> …which I had added a while back to resolve some other problem building on Netlify. With that gone everything builds fine for me again now (including with latest version of kit). Until next time I guess.

NIce one! I had done the same and removing it fixed it for me too!

**Comment by code-masala** [comment]
@knajjars How did you solve this problem?

**Comment by jNaimXIII** [comment]
I see that you are not alone facing this issue months after this issue being closed. :)

[This component](https://github.com/jNaimXIII/jannatinnaim.com/blob/main/src/routes/_Socials.svelte) renders dynamically imported components. I have this deployed on Vercel. Hopefully can get it fixed.

**Comment by kevinrenskers** [comment]
I am also constantly seeing this error in Sentry, for both of my SvelteKit projects. It's quite annoying, and I am not sure what to do about this.

**Comment by disbullief** [comment]
In my case, I managed to fix the issue by doing 2 things:

```
// svelte.config.js
const config = {
	kit: {
		...
		version: {
			pollInterval: 15_000 // Set a pollInterval, in my case check for code updates every 15 seconds
		}
	}
```

and in my 'highest' layout:

```
// +layout.svelte
	import { beforeNavigate } from '$app/navigation';

	// Should fix white screen due to errors on try to import missing module by forcing a hard page reload if the version changed
	beforeNavigate(({ to, willUnload }) => {
		if ($updated && willUnload && to?.url) {
			location.href = to.url.href;
		}
	});
```
