### ISSUE TITLE
[docs] Inline code blocks are not rendered properly in the sidebar

### ISSUE THREAD

**Issue by malinowskip** [sveltejs/kit#3987]
### Describe the problem

Inline code blocks are rendered as `<code>Some heading in the docs</code>` in the sidebar nav.
<img width="266" alt="Zrzut ekranu 2022-02-17 o 23 02 37" src="https://user-images.githubusercontent.com/47485431/154578376-eea1e125-ccb6-42ae-806e-b93c0f629b28.png">

### Describe the proposed solution

Remove backticks from [section headings](https://github.com/sveltejs/kit/blob/ec62766ac115ba02ed60b717ae9ba0ca9bafab6f/documentation/docs/15-seo.md?plain=1#L25).

### Alternatives considered

Using `{@html ...}` to render section headings in the sidebar causes problems (code block contents are also rendered as HTML, even if escaped), so making it work would require other rewrites.

### Importance

nice to have

### Additional Information

I also noticed that backticks are not rendered as code blocks in the new search utility.

<img width="541" alt="Zrzut ekranu 2022-02-17 o 23 23 21" src="https://user-images.githubusercontent.com/47485431/154581015-3d6aeb01-1582-4382-8a0b-2993b8c8c4ea.png">

**Comment by bluwy** [comment]
Fixed in #4011
