### ISSUE TITLE
Collapse docs table of contents

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4003]
### Describe the problem

The docs would be easier to navigate if instead of this...

<img width="285" alt="image" src="https://user-images.githubusercontent.com/1162160/154773099-2970c08f-168d-4b4b-a049-dc75263d05e1.png">

...we had something like this:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/1162160/154773162-258d0d44-1f37-4b9a-8b76-26e5d29c0290.png">

The sub-sub-sections could become visible when you're on the page in question.

### Importance

nice to have

**Comment by bhaskar2840** [comment]
# We could use this type of collapsible doc structure?
 

<details>
 <summary>LOADING</summary>
  
### Output
### Input

</details>

**Comment by Rich-Harris** [comment]
fixed in #4011
