### ISSUE TITLE
Add option to only run fetch on server in <script module="context">

### ISSUE THREAD

**Issue by naptestdev** [sveltejs/kit#4006]
## This is my app of getting random english word
![trim](https://user-images.githubusercontent.com/88878684/154790416-7c3bf550-94c8-42d7-9ca2-78b67de54e94.gif)

### This is the code
<img width="552" alt="image" src="https://user-images.githubusercontent.com/88878684/154790456-70073d3c-b05e-4c1e-9f88-53f4d956d5ea.png">

## I have read from the documentation that
![image](https://user-images.githubusercontent.com/88878684/154790482-e2d4f75e-a5cc-4af4-8f44-930b1a759b74.png)

### Importance

i cannot use SvelteKit without it

**Comment by bluwy** [comment]
Use `browser` from `$app/env` to run things conditionally in the browser or server

**Comment by babichjacob** [comment]
If you use the `fetch` argument passed to `load`, that random word fetching will be deduplicated because the browser will reuse the response the server got instead of making another one.
