### ISSUE TITLE
Issue in navigating through pages.

### ISSUE THREAD

**Issue by bhaskar2840** [sveltejs/kit#4012]
## Navigation bug 
- When we open the documention (docs) in svelteKit and Svelte docs as well and open different components in the same doc.
- After pressing the back option for multiple times the page remains stagnant and doesnot move .

https://user-images.githubusercontent.com/47430433/154818241-4a94e441-93bc-4b1f-a3d7-c5cb0a66358b.mp4

- The navigation bar shows change in address but the page remained same.
- (no internet issue in my computer 😂)

### Describe the proposed solution

1. Can fix this issue.
2. Have a side button to navigate to the home page that is sticky like in the main svelte doc page but is absent in sveltekit doc.
3. This will reduce the time for beginners to navigate through the docs.

### Importance

would make my life easier

**Comment by bhaskar2840** [comment]
![svelte](https://user-images.githubusercontent.com/47430433/154818761-a3476eba-c8a8-449f-a8f8-cf5caf683815.jpg)

- This is a great sticky navigation on the top page of docs page in sveltejs but no such navigation is there sveltekit docs

**Comment by mustofa-id** [comment]
I found no navigation issue in Kit docs 🤷‍♂️

**Comment by bhaskar2840** [comment]
- provided the video in the issue.  
-  While doing back after selecting different sections nothing happens in the main doc page and doing back is tedious
- Should have a navigation tab that can make going to the main page easy .
