### ISSUE TITLE
Gracefully handle occupied ports

### ISSUE THREAD

**Issue by jonahsnider** [sveltejs/kit#4018]
### Describe the problem

When running lots of services locally you may end up having a collision when one app is using port `3000` and SvelteKit tries to use it as well. The current behavior is to check if the port is free and if not, provide some info for tracking down the app which is using it.
You can also provide a 

### Describe the proposed solution

Commands that use a port should gracefully handle cases where it's occupied.

For example, if a user runs the `dev` command with no arguments the default port of `3000` is selected. Using a library like `get-port` SvelteKit can check if port `3000` is available. If it's not available then it can try `3001`, `3002` and so on. If none of those ports are free after 10 or so attempts it can fall back to just picking a random port.

This change would then allow the `check_port()` function to be unnecessary since there will never be a case where every port on the system is occupied.

### Alternatives considered

I think the general idea for implementing this will stay the same, although there are a number of ways you could tweak the implementation. For example, erroring if a port can't be found in 10 tries, printing a warning if the desired port was occupied, etc.

### Importance

would make my life easier

### Additional Information

I'd be happy to implement this change if you maintainers think it would be helpful for DX.

**Comment by bluwy** [comment]
If you prefer the incrementing port feature, you can set the [strictPort](https://vitejs.dev/config/#server-strictport) Vite config as `false`. SvelteKit has it `true` by default.

**Comment by Conduitry** [comment]
This has come up a few times. We should perhaps document it on our end. I don't know where a good place to document useful Vite config is though, nor where the line is where we should just direct people to Vite's own documentation.
