### ISSUE TITLE
Move mention of `accept` header in shadow endpoint docs

### ISSUE THREAD

**Issue by lkj4** [sveltejs/kit#4027]
### Describe the problem

You could now just rename the shadow endpoint file from `[someId].ts` to `[someId].json.ts` and the problem is solved. This could be even better bc it's even easier to distinguish endpoint file from svelte file. However, `.ts` and `.svelte` are good enogh.

PS if endpoints are not fetched with `.json` the requestor gets the html.

### Describe the proposed solution

Either we fix this or we adjust the docs and stress that the filenames need to have `.json` in the name. Otherwise users need to get deep into Inspector's network tab/response/etc to understand what is going on...

Problem is also that you get this typical error message that a `<` is at the beginning of your JSON without giving a file or line number. If you are a crack you know what is going on but most will need their time to get the problem.

So, the current state is kind of unintuitive.

### Importance

nice to have

**Comment by Conduitry** [comment]
As mentioned in https://kit.svelte.dev/docs/routing, the way to access the underlying endpoint is to use an `Accept` header, not to append `.json` to the URL. This also applies to GETs, so maybe it should be moved in the docs.

**Comment by benmccann** [comment]
I agree we should move the location in the docs. I missed it the other day as well because I wasn't looking there
