### ISSUE TITLE
AMP hybrid mode just like next.js

### ISSUE THREAD

**Issue by souhailmerroun** [sveltejs/kit#4029]
### Describe the problem

We have a big website that is built using Svelte, everything is fine and works perfect so thank you svelte <3

But, now, we have a business need where we need some pages to be "Google AMP".

We've tried `amp:true` so far but it forces the entire website to become an AMP. 

Is there a way you are adding this feature soon? Otherwise we are thinking about using the endpoints and serving custom AMP but could we get some general guidelines or recommendations if possible?

### Describe the proposed solution

We would love to have a hybrid mode to activate AMP only on some routes. 

### Alternatives considered

Using endpoints to serve our own AMP code but meh. 

### Importance

would make my life easier

**Comment by souhailmerroun** [comment]
For info, 

[https://nextjs.org/docs/api-reference/next/amp](https://nextjs.org/docs/api-reference/next/amp)

![image](https://user-images.githubusercontent.com/8895242/154943551-5a7b445a-fb11-497d-a2b3-828a17938290.png)

**Comment by Rich-Harris** [comment]
will be fixed by #4710
