### ISSUE TITLE
Clashing endpoint-powered pages break route sorting

### ISSUE THREAD

**Issue by mrkishi** [sveltejs/kit#4038]
### Describe the bug

When multiple endpoint-powered pages have a clashing route path, both client- and server-side routers break, not following sorting rules.

Given:

```
/[id].js
/[id].svelte
/[slug].js
/[slug].svelte
```

A client-side navigation to any matching route renders `[id].svelte` with undefined props, without hitting the endpoint.

A full-page navigation _does_ hit the endpoints and falls through them, but you get back their JSON payload instead of the rendered page.

### Reproduction

[Minimal reproduction available here.](https://github.com/mrkishi/mrkishi-repro-sveltekit-clashing/commit/ca1c21dd2ad2a35b6d0a62db4044d5bda9fe3d9c)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
    Memory: 1.44 GB / 7.88 GB
  Binaries:
    Node: 17.5.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 8.4.0 - ~\scoop\apps\nodejs\current\bin\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.279
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by isaacfranco** [comment]
I saw that the strategy to associate a page route with it's shadow endpoint requires that they are just after the other after route sorting.

The problem is that when we have multiple endpoint-powered pages on the same folder, all it's endpoints stay before all the pages, and the association strategy doesn't work.

On the later part of packages/kit/src/core/create_manifest_data/index.js there is a comparator function that to the rout sorting, and there is a code that put pages after endpoints:
```javascript
	if (a.is_page !== b.is_page) {
		return a.is_page ? 1 : -1;
	}
```

if we remove that, the bug is gone, but I'm feeling that it will not respect the priorities especified on the documentation anymore.

Someone with any thoughts?

**Comment by isaacfranco** [comment]
I can try to keep the sort comparator intact, but change this:
```javascript
while (i--) {
		const route = routes[i];
		const prev = routes[i - 1];

		if (prev && prev.key === route.key) {
			if (prev.type !== 'endpoint' || route.type !== 'page') {
				const relative = path.relative(cwd, path.resolve(config.kit.files.routes, prev.key));
				throw new Error(`Duplicate route files: ${relative}`);
			}

			route.shadow = prev.file;
			routes.splice(--i, 1);
		}
	}
```
... to someting that doesn't require page routes and its shadow-endpoints to be together after sorting.

**Comment by ITwrx** [comment]
is 
```
index.svelte
index.js
[root_page].svelte
[root_page].js
```

a clash? If so, how are we supposed to specify both `index only` and `anything else at same level` without it being a clash? My app is serving the endpoint's json response instead of the page right now. 

described more in depth here: https://github.com/sveltejs/kit/discussions/4162

**Comment by kvetoslavnovak** [comment]
I van confirm to encounter the very same problem using endpoints. In here above described case the endpoints seem not to follow the sorting rules.
