### ISSUE TITLE
adapter-vercel build fail - app.js missing

### ISSUE THREAD

**Issue by vlntsolo** [sveltejs/kit#4063]
### Describe the bug

After upgrading packages project no longer builds with vercel adapter. Also tried with skeleton Sveltekit project, got the same output.

svelte.config.js

```
// import adapter from '@sveltejs/adapter-auto';
import vercel from '@sveltejs/adapter-vercel';
/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: vercel(),

		// Override http methods in the Todo forms
		methodOverride: {
			allowed: ['PATCH', 'DELETE']
		}
	}
};

export default config;
```

app.js file doesn't appear in the output folder.

 
![Screenshot from 2022-02-23 00-56-52](https://user-images.githubusercontent.com/25847225/155233616-02294fe8-a80e-4368-a219-3e5641430e5d.png)

 

### Reproduction

https://github.com/vlntsolo/adapter-vercel-issue

### Logs

```shell
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-vercel
 > .svelte-kit/vercel-tmp/entry.js:3:20: error: Could not resolve "../output/server/app.js"
    3 │ import { App } from '../output/server/app.js';
      ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~

> Build failed with 1 error:
.svelte-kit/vercel-tmp/entry.js:3:20: error: Could not resolve "../output/server/app.js"
.svelte-kit/vercel-tmp/entry.js:3:20: error: Could not resolve "../output/server/app.js"
    at failureErrorWithLog (/home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:1493:15)
    at /home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:1069:65)
    at buildResponseToResult (/home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:1149:7)
    at /home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:1258:14
    at /home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/home/valentine/dev/nous-test/node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
```

### System Info

```shell
ubuntu 21.10
node v14.19.0
```

### Severity

blocking an upgrade

**Comment by mdynnl** [comment]
You have an outdated adapter-vercel https://github.com/vlntsolo/adapter-vercel-issue/blob/219bf0695ba4f1422a4c4493091d0e7e360e6b40/package-lock.json#L73

**Comment by nrabulinski** [comment]
I am also encountering this issue on the latest sveltekit version. My temporary fix is to pin package versions in `package.json`
```json
"@sveltejs/adapter-auto": "=1.0.0-next.17",
"@sveltejs/adapter-vercel": "=1.0.0-next.43",
"@sveltejs/kit": "=1.0.0-next.278",
```
like so, as those are the latest versions which I can see worked for me

**Comment by Swarleys** [comment]
I had this problem deploying to Vercel with the adapter-auto, I fixed updating the adapter-auto to the last package instead of the next one, there is an issue open about this problem with the versions.

**Comment by vlntsolo** [comment]
> ```json
> =1.0.0-next.278
> ```

These versions worked for me too. Thanks. 

> I had this problem deploying to Vercel with the adapter-auto, I fixed updating the adapter-auto to the last package instead of the next one, there is an issue open about this problem with the versions.

I couldn't find one somehow.

**Comment by Rich-Harris** [comment]
It's this issue: https://github.com/sveltejs/kit/issues/4008. I tried forcing a bump just now but no dice. Other packages are affected too

**Comment by Rich-Harris** [comment]
this should be fixed now, if you `npm i -D @sveltejs/adapter-auto@next`
