### ISSUE TITLE
AMP 'http-equiv' may not appear in tag 'meta'

### ISSUE THREAD

**Issue by asendia** [sveltejs/kit#4074]
### Describe the bug

Using this configuration:
- [amp](https://kit.svelte.dev/docs/configuration#amp) enabled (`amp: true`)
- `@sveltejs/adapter-static`

Will make the amp document invalid since sveltekit injected `http-equiv`

Impact: Google removes the web page from its AMP CDN

### Reproduction

https://github.com/asendia/salmonfit/tree/3a0062f875f0d3a41700d16e293fbf378e29b4c1

Building the repo will result in this error when checked using https://validator.ampproject.org/
<img width="510" alt="image" src="https://user-images.githubusercontent.com/9080782/155302204-68a392d5-b642-4c3a-b8c2-184adfba2530.png">

### Logs

```shell
The attribute 'http-equiv' may not appear in tag 'meta'.
```

### System Info

```shell
System:
  OS: macOS 12.2.1
  CPU: (8) arm64 Apple M1
  Memory: 151.58 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
  npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
Browsers:
  Chrome: 98.0.4758.102
  Firefox: 92.0.1
  Safari: 15.3
npmPackages:
  @sveltejs/eslint-config: github:sveltejs/eslint-config#v5.8.0 => 5.8.0
```

### Severity

serious, but I can work around it

### Additional Information

I need to remove the http-equiv element in the postbuild in order to make the amp docs valid https://github.com/asendia/salmonfit/blob/main/scripts/remove-empty-csp.js#L8

**Comment by geoffrich** [comment]
Closed by #4073.
