### ISSUE TITLE
Upgrading from SvelteKit v260 to v261+ starts returning 500 errors "Dynamic require of "X"" for every serverless rendered page

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/kit#4079]
### Describe the bug

as part of regular maintenance for swyxkit i [upgraded the deps](https://github.com/sw-yx/swyxkit/commit/98dd9f41af1a5d1b8652dfd62641e4ee644dd4fc) as per the title

and now [everything is throwing a 500 error](https://621638d27781070008fb992c--swyxkit.netlify.app/blog) with this `Dynamic require of "fs"` error, even though i'm pretty darn sure I don't actually write that code. EDIT: Possible related error: https://github.com/sveltejs/kit/issues/2400

this error only happens in prod build, not in local dev. is this something broken in the netlify adapter?

```
Feb 23, 07:43:09 PM: 24d25a60 ERROR  Error: Dynamic require of "fs" is not supported
Feb 23, 07:43:09 PM: 24d25a60     at __require (file:///var/task/.netlify/functions-internal/render.js:28:9)
Feb 23, 07:43:09 PM: 24d25a60     at node_modules/gray-matter/index.js (file:///var/task/.netlify/functions-internal/render.js:10725:14)
Feb 23, 07:43:09 PM: 24d25a60     at __require2 (file:///var/task/.netlify/functions-internal/render.js:34:44)
Feb 23, 07:43:09 PM: 24d25a60     at .netlify/server/chunks/content-4d53413a.js (file:///var/task/.netlify/functions-internal/render.js:17141:37)
Feb 23, 07:43:09 PM: 24d25a60     at __init (file:///var/task/.netlify/functions-internal/render.js:31:50)
Feb 23, 07:43:09 PM: 24d25a60     at .netlify/server/entries/endpoints/api/listContent.json.js (file:///var/task/.netlify/functions-internal/render.js:17185:5)
Feb 23, 07:43:09 PM: 24d25a60     at __init (file:///var/task/.netlify/functions-internal/render.js:31:50)
Feb 23, 07:43:09 PM: 24d25a60     at file:///var/task/.netlify/functions-internal/render.js:26540:51
Feb 23, 07:43:09 PM: 24d25a60     at async resolve (file:///var/task/.netlify/functions-internal/render.js:26295:83)
Feb 23, 07:43:09 PM: 24d25a60     at async respond (file:///var/task/.netlify/functions-internal/render.js:26246:22)
```

![image](https://user-images.githubusercontent.com/6764957/155331234-fa543590-301d-4e0b-b1e4-23a01d5fa081.png)

### Reproduction

this is the netlify build logs https://app.netlify.com/sites/swyxkit/deploys/621638d27781070008fb992c

and this is the commit https://github.com/sw-yx/swyxkit/tree/c452df95219f73c4c3cd199490752656f0ab89ec

### System Info

```shell
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Apple M1
    Memory: 38.87 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.1 - /var/folders/h_/1lq46tdj7jdbs0j1m5l6rlb00000gn/T/fnm_multishell_23513_1645623105494/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.0.0 - /var/folders/h_/1lq46tdj7jdbs0j1m5l6rlb00000gn/T/fnm_multishell_23513_1645623105494/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 94.0.2
    Safari: 14.1
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/kit: ^1.0.0-next.283 => 1.0.0-next.283 
    svelte: ^3.44.3 => 3.46.4
```

### Severity

blocking an upgrade

### Additional Information

still trying to narrow down the precise version where this broke

**Comment by sw-yx** [comment]
currently suspect this issue is related to SvelteKit 279->280  where there was an important breaking change

https://github.com/sveltejs/kit/pull/4034

**Comment by sw-yx** [comment]
i realized that my last working build on [Feb 16](https://github.com/sw-yx/swyxkit/commit/c682a7ee6be40561242532786571f1e1bf8b9732) had Netlify adapter 45 and Kit 269 so i am trying to repro with that.

**Comment by sw-yx** [comment]
i have put my failed attempts at debugging into a different branch, so as not to break current users https://github.com/sw-yx/swyxkit/commits/debuggingVersions

**Comment by geoffrich** [comment]
Possibly related: https://github.com/sveltejs/kit/issues/3978#issuecomment-1046307164 and https://github.com/sveltejs/kit/pull/4058. Does removing [node_bundler](https://github.com/sw-yx/swyxkit/blob/c2f30eb4886cfa31cabb5893022f46b727211edb/netlify.toml#L8) help?

**Comment by PH4NTOMiki** [comment]
> Possibly related: [#3978 (comment)](https://github.com/sveltejs/kit/issues/3978#issuecomment-1046307164) and #4058. Does removing [node_bundler](https://github.com/sw-yx/swyxkit/blob/c2f30eb4886cfa31cabb5893022f46b727211edb/netlify.toml#L8) help?

I just tried with removing node_bundler, still the same

**Comment by sw-yx** [comment]
confirmed that removing node bundler did not help :( any other options?

**Comment by PH4NTOMiki** [comment]
I think it's Netlify handling of node_modules

**Comment by PH4NTOMiki** [comment]
created issue https://github.com/netlify/zip-it-and-ship-it/issues/1036

**Comment by PH4NTOMiki** [comment]
Netlify reverted to working version of ZISI

**Comment by sw-yx** [comment]
WOW so it was not my/our fault?!? amazing. thank you so much, will retry.

**Comment by PH4NTOMiki** [comment]
@sw-yx no problem man, yeah, I was pretty sure it wasn't your/our problem, and I checked all the recent SvelteKit changes and there wasn't anything breaking, and when I tried to deploy it to Vercel, and it was working no issue, and the dev was working, so I figured the issue has to be something with Netlify, something with their build/packaging process.
Glad it works now.

**Comment by PH4NTOMiki** [comment]
Esbuild source issue: https://github.com/evanw/esbuild/issues/1921
