### ISSUE TITLE
SvelteKit & AMP

### ISSUE THREAD

**Issue by souhailmerroun** [sveltejs/kit#4086]
### Describe the bug

Hello, I have a 500 error on the documentation.

[https://kit.svelte.dev/docs/amp](https://kit.svelte.dev/docs/amp)

### Reproduction

1. https://www.google.com/search?q=sveltekit+amp
2. 
![image](https://user-images.githubusercontent.com/8895242/154933855-3c6f9708-22d6-4cce-b1b6-12f4147df515.png)

3. 
![image](https://user-images.githubusercontent.com/8895242/154933891-3a083f36-bbcf-4760-a6d6-3d8b2a18e1e8.png)

### System Info

```shell
nada.
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
added a redirect
