### ISSUE TITLE
env variable for process.title in adapter-node

### ISSUE THREAD

**Issue by ITwrx** [sveltejs/kit#4097]
### Describe the problem

Right now, when you build your application with `node-adapter`, the node process title is set to "node" (IIRC). This causes problems when trying to write init scripts and hosting multiple apps on the same server. In alpine linux using `openrc`, you can start the process with your custom name but `rc-status` shows the process as "crashed" because `sveltekit/node` has started the process with "node" process title. The current state of using "node" as the process title would also likely cause problems trying to run multiple sveltekit apps on the same server, in general.

### Describe the proposed solution

Add a env variable to node-adapter like `ORIGIN` and `HOST` that can be set in the terminal when building the project, like: `HOST=127.0.0.1 PORT=3000 ORIGIN=http://itwrx.org PROCESS_TITLE=itwrxorg-node npm run build` (these seem to be ignored for me right now, but maybe i'm not doing something right).

### Alternatives considered

My current workaround is hard coding the process.title in /build/index.js after building the application. 

```
13900 /* global "SOCKET_PATH", "HOST", "PORT" */
13901 process.title = 'itwrxorg-node';
13902 const path = process.env["SOCKET_PATH"] || false;
13903 const host = process.env["HOST"] || '127.0.0.1';
13904 const port = process.env["PORT"] || (!path && '3000');
```

The process.title doesn't get changed with a rebuild, but if sveltekit gets updated and process.title is not re-hard-coded it will revert to using "node". This is not good DX and prone to be forgotten.

 

### Importance

would make my life easier

### Additional Information

I'm new to sveltekit and node, so maybe i'm missing something. :)

thanks

**Comment by Conduitry** [comment]
Does just manually setting `process.title` in your hooks file in prod mode work?

**Comment by ITwrx** [comment]
yes, that works. thanks!
