### ISSUE TITLE
rename `__fetch_polyfill` to `installFetch`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4098]
### Describe the problem

I have no idea why it's called that.

### Describe the proposed solution

```js
import { installFetch } from '@sveltejs/kit/install-fetch';
```

### Importance

nice to have

**Comment by Conduitry** [comment]
I think that name came from before we were bundling things the same way we are now, and we wanted a name that was unlikely to collide with user code.

**Comment by Rich-Harris** [comment]
Also, I don't think there's a good reason for that module to re-export `fetch`, `Headers`, `Request` and `Response`
