### ISSUE TITLE
Do the token and current_token variables serve a purpose in the create-svelte default template (todo app)? 

### ISSUE THREAD

**Issue by SylvainGarrigues** [sveltejs/kit#4100]
### Describe the bug

I can't see the reasoning behind the token dance below. Is that necessary in this template? What is the purpose?

[const token = (current_token = {});](https://github.com/sveltejs/kit/blob/93d22b784afb7ff0c69936e9843b4fb6a57adca0/packages/create-svelte/templates/default/src/lib/form.ts#L38)

and 

[if (token !== current_token) return;](https://github.com/sveltejs/kit/blob/93d22b784afb7ff0c69936e9843b4fb6a57adca0/packages/create-svelte/templates/default/src/lib/form.ts#L55)

### Reproduction

Source code of the file is here:
https://github.com/sveltejs/kit/blob/93d22b784afb7ff0c69936e9843b4fb6a57adca0/packages/create-svelte/templates/default/src/lib/form.ts

### System Info

```shell
Any system
```

### Severity

annoyance

**Comment by Conduitry** [comment]
It's to deal with multiple submissions to the form before the first one completes.

**Comment by lidlanca** [comment]
`if (token !== current_token) return;` 

is after the actual fetch, which will allow multiple fetch calls.
and only the last request will set the response.
