### ISSUE TITLE
Add query to SvelteKit Routing docs

### ISSUE THREAD

**Issue by bluepuma77** [sveltejs/kit#4129]
### Describe the problem

I'm always frustrated when I try to rebuild my NodeJS Express project in SvelteKit. Like most developers I use `params`, `query` and `body` to pass data to the server. I can find `params` and `body` in the [docs](https://kit.svelte.dev/docs/routing), but not `query`. 

### Describe the proposed solution

Please add a sentence about query parameters in [Routing](https://kit.svelte.dev/docs/routing).

### Importance

i cannot use SvelteKit without it

**Comment by dansvel** [comment]
they replace request.origin/path/query with request.url , youbmaybwant check it here #3126

**Comment by dimfeld** [comment]
On a URL object the `searchParams` field exposts the parsed querystring, or `search` is the fully-expanded querystring. See https://developer.mozilla.org/en-US/docs/Web/API/URL
