### ISSUE TITLE
The site https://kit.svelte.dev/ : Docs: Single Page Suggestion

### ISSUE THREAD

**Issue by dmitrykurmanov** [sveltejs/kit#4134]
### Describe the problem

Now the documentation is not one huge single page. We have many small pages with the  site's Search bar.

### Describe the proposed solution

For me, it would be much better to have one huge doc page (like for https://svelte.dev/docs) with the browser search. It helps me a lot many times when I don't know which exactly article I need. In that case, I just search some words and found something in the doc. 

For now, it looks less helpful and convenient for me. Or it could be some "switch to single page presentation mode" button :)

### Importance

would make my life easier

**Comment by Acmion** [comment]
Both approaches have their merits. 

For example, Plotly.js (https://plotly.com/javascript/) has implemented a separate "Single Page Reference" view (https://plotly.com/javascript/reference/).

**Comment by dmitrykurmanov** [comment]
I agree it would be great to have both but  this can make support difficult

**Comment by Acmion** [comment]
Would it not be possible to just create a route or page where all current pages are rendered inline and in sequence?
