### ISSUE TITLE
svelte-kit sync

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4165]
### Describe the problem

In #4120, we introduce _generated types_, which give you type safety when using `params` inside pages and endpoints. (In future, we want to extend that to props as well.)

One minor wrinkle is that the types aren't generated until you run `svelte-kit dev` or `svelte-kit build`, which means that if you were to (for example) typecheck in CI _before_ building the app, it would fail. 

### Describe the proposed solution

It would be good to collate all the work that takes the filesystem as input (i.e. generating `manifest.js`, `Root.svelte` and now the route-level types) into a new function — let's call it `sync` — and expose it via the CLI as `svelte-kit sync`. (Open to alternative names but this one seems good enough to me.)

We could then add this to the default template as a postinstall script:

```js
// package.json
"scripts": {
  // ...
  "postinstall": "svelte-kit sync"
}
```

### Importance

would make my life easier

**Comment by xpat** [comment]
Is my error related to this issue?  I installed the skeleton version of kit.  I have a svelte.config.js, adapted for node as usual (I've gotten this deployment to work for at least six other domains, the last one a little over a week ago).  The only thing that immediately jumps out at me is that my package.json didn't have this:

```
// package.json
"scripts": {
  // ...
  "postinstall": "svelte-kit sync"
}
```
(But even if I manually add that package, I get the same error.)

> ~/sveltekitprod$ npm install

> 01-dev-cleva@0.0.1 postinstall
> svelte-kit sync

> You need to create a svelte.config.js file. See https://kit.svelte.dev/docs/configuration
    at load_config (file:///home/patrouch/sveltekitprod/node_modules/@sveltejs/kit/dist/cli.js:779:9)
    at file:///home/patrouch/sveltekitprod/node_modules/@sveltejs/kit/dist/cli.js:1001:25
    at o.parse (/home/patrouch/sveltekitprod/node_modules/sade/lib/index.js:1:3402)
    at file:///home/patrouch/sveltekitprod/node_modules/@sveltejs/kit/dist/cli.js:1009:6
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
npm ERR! code 1
npm ERR! path /home/patrouch/sveltekitprod
npm ERR! command failed
npm ERR! command sh -c svelte-kit sync

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/patrouch/.npm/_logs/2022-03-12T16_02_47_502Z-debug-0.log

**Comment by rmontgomery429** [comment]
A side effect of this change is that you used to be able to run something like this in a Dockerfile:

```
COPY package.json package-lock.json ./
RUN npm ci
```

And it would work.

Now with this prepare script you get this:

```
=> ERROR [4/6] RUN npm ci                                                                                                                                                  7.8s
------                                                                                                                                                                           
 > [4/6] RUN npm ci:                                                                                                                                                             
7.504                                                                                                                                                                         
7.504 > example@0.0.1 prepare                                                                                                                                                 
7.504 > svelte-kit sync                                                                                                                                                       
7.504                                                                                                                                                                         
7.550 > You need to create a svelte.config.js file. See https://kit.svelte.dev/docs/configuration
7.550     at load_config (file:///app/node_modules/@sveltejs/kit/dist/cli.js:779:9)
7.550     at file:///app/node_modules/@sveltejs/kit/dist/cli.js:1001:25
7.550     at o.parse (/app/node_modules/sade/lib/index.js:1:3402)
7.550     at file:///app/node_modules/@sveltejs/kit/dist/cli.js:1009:6
7.550     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
7.550     at async Promise.all (index 0)
7.550     at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
7.550     at async loadESM (node:internal/process/esm_loader:88:5)
7.550     at async handleMainPromise (node:internal/modules/run_main:61:12)
7.558 npm ERR! code 1
7.558 npm ERR! path /app
7.559 npm ERR! command failed
7.559 npm ERR! command sh -c svelte-kit sync
```

If I remove the prepare script it works again. 😬

I'll share anything I learn as I play with this and search for a solution but I thought I'd share this here in case I'm not the only one.

**Comment by Conduitry** [comment]
That's a good catch @rmontgomery429 - I've opened #4366.
