### ISSUE TITLE
Typescript page not functioning on website

### ISSUE THREAD

**Issue by darpots** [sveltejs/kit#4175]
### Describe the bug

Error 500: Unexpected token < in JSON at position 0

### Reproduction

Just by going to https://kit.svelte.dev/docs/typescript 

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by PH4NTOMiki** [comment]
Typescript page was renamed to Types, that should be 404 but currently there are issues with it so you saw 500.

**Comment by geoffrich** [comment]
The underlying cause is being tracked in https://github.com/sveltejs/kit/issues/4093
