### ISSUE TITLE
Focus outline after navigating to new page on Firefox

### ISSUE THREAD

**Issue by bgdev89** [sveltejs/kit#4180]
### Describe the bug

After navigating to a different page in Firefox, the browser will show a focus outline surrounding the entire viewport.

### Reproduction

- Latest version of Sveltekit, since 1.0.0-next.288
- Latest version of Firefox

### System Info

```shell
Firefox, Windows 10
```

### Severity

annoyance

**Comment by pieterdd** [comment]
Was just about to report this myself! For completeness, [here](https://user-images.githubusercontent.com/1407980/156452839-f09c4767-e712-4535-8aca-eeba3d4f9837.png) is a reproduction screenshot.

Reproduction:
- Make a new starter with `npm init svelte@next test`. I chose the SvelteKit demo app.
- `yarn dev`

**Comment by geoffrich** [comment]
Likely introduced by https://github.com/sveltejs/kit/pull/4140
