### ISSUE TITLE
Rename fetch

### ISSUE THREAD

**Issue by pyronaur** [sveltejs/kit#4193]
### Describe the problem

I've been using SvelteKit for a while now and only today I learned that depending on whether I pass `fetch` as a param in the load function, I get a "special fetch" or "normal fetch". And the "special fetch" is more optimized and doesn't load requests twice, as the "normal fetch" does.

I consider the current implementation something similar to monkey patching. It looks really good, almost magical.....a little too magical. Unless you read the documentation very thoroughly before you begin (or you learn the hard way as I did) it's easy to miss that the fetch is special.

I don't care what the special fetch is called, be it `specialFetch`, `svelteFetch`, `magicLoad` or whatever else - but calling it `fetch` is too confusing, imho.

### Describe the proposed solution

Rename `fetch` passed to the `load` function to something more distinct. 

### Alternatives considered

Alternatively - overwrite all fetch calls to be special fetch calls, at least that'll be consistent monkey patching.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Renaming it just sounds like it would be more typing for everyone and more things to worry about.

I think the confusion about what's going on would be sufficiently addressed by #3731.

**Comment by Conduitry** [comment]
Besides it being more typing, I think people would be less likely to do the right thing if we renamed the parameter. I'm going to close this in favor of the improved warnings suggested in #3731.
