### ISSUE TITLE
Use `.ts` extension when creating Playwright config for TypeScript projects

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#4194]
### Describe the bug

I've seen a few reports of this. It appears to have been a known issue when the feature was added: https://github.com/sveltejs/kit/pull/4056#discussion_r813166060

I saw that someone fixed it by prefixing with some environment variable. Unforunately, I can't find what that was at the moment

### Reproduction

Create TypeScript + Playwright project from wizard

### System Info

```shell
latest
```

### Severity

serious, but I can work around it

**Comment by vhscom** [comment]
```json
"test": "PW_EXPERIMENTAL_TS_ESM=1 playwright test"
```

example implementation: https://codeberg.org/vhs/svelte-headlessui-starter

**Comment by vhscom** [comment]
I believe you're looking for:

```json
"test": "PW_EXPERIMENTAL_TS_ESM=1 playwright test"
```

example implementation: https://github.com/vhscom/svelte-headlessui-starter

**Comment by vhscom** [comment]
Last update I saw for ESM in TS for Playwrite dated Jan 11: https://github.com/microsoft/playwright/issues/7121#issuecomment-1009140849. I'd expect the ENV var to simply become optional later, but since this flag was recently introduced I haven't dug in deeper yet.

**Comment by frederikhors** [comment]
I opened this some time ago and I'm waiting for the next version. After this TS code is usable. https://github.com/microsoft/playwright/issues/12307

**Comment by EdricChan03** [comment]
> I believe you're looking for:
> 
> ```json
> "test": "PW_EXPERIMENTAL_TS_ESM=1 playwright test"
> ```
> 
> example implementation: https://github.com/vhscom/svelte-headlessui-starter

Testing this on the latest versions appears to result in the following issue:

```
Cannot find package 'url.js' imported from /path/to/node_modules/@sveltejs/kit/dist/chunks/index2.js
```
([Full build logs for context](https://github.com/EdricChan03/playwright-ts-repro/runs/5529113293?check_suite_focus=true#step:5:20))

(And a [reproduction of the issue](https://github.com/EdricChan03/playwright-ts-repro/tree/repro/cant-find-package-urljs))

**Comment by vhscom** [comment]
@EdricChan03 the `url.js` appears to have started with https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next292

**Comment by vhscom** [comment]
The `url.js` appears to have started with [1.0.0-next.292](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next292) when using `PW_EXPERIMENTAL_TS_ESM` flag for tests.

**Comment by vhscom** [comment]
> Testing this on the latest versions appears to result in the following issue:
> ```
> Cannot find package 'url.js' imported from /path/to/node_modules/@sveltejs/kit/dist/chunks/index2.js`
> ```

Appears to have started with [1.0.0-next.292](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next292) when using `PW_EXPERIMENTAL_TS_ESM` flag for tests with TypeScript. Backing down to `@sveltejs/kit@1.0.0-next.291` and tests are functional again. So something in the [291-292 changeset](https://github.com/sveltejs/kit/compare/%40sveltejs/kit%401.0.0-next.291...@sveltejs/kit@1.0.0-next.292) is likely conflicting with the experimental TS ESM flag for Playwright.

**Comment by vhscom** [comment]
> Testing this on the latest versions appears to result in the following issue:
> ```
> Cannot find package 'url.js' imported from /path/to/node_modules/@sveltejs/kit/dist/chunks/index2.js`
> ```

Appears to have started with [1.0.0-next.292](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next292) when using `PW_EXPERIMENTAL_TS_ESM` flag for tests with TypeScript. Backing down to `@sveltejs/kit@1.0.0-next.291` and tests are functional again. So something in the [291-292 changeset](https://github.com/sveltejs/kit/compare/%40sveltejs/kit%401.0.0-next.291...@sveltejs/kit@1.0.0-next.292) is conflicting with the experimental TS ESM flag for Playwright in the current stable release of playwright. As a result, if using `@sveltejs/kit@1.0.0-next.292` or above, consider installing playwright version `1.20.0` (currently tagged `beta`) or above, or try the latest nightly release with `@playwright/test@next`.

You're using experimental features, so I'll assume you know how to upgrade and downgrade your version of Node.
If the browser window stops opening and tests fail as a result, reinstall playwright with `npx playwright install`.

**Comment by sebastianrothe** [comment]
Works  again with the latest version of Playwright (1.20), which has been released just now.

**Comment by benmccann** [comment]
`PW_EXPERIMENTAL_TS_ESM` had no effect for me. I had to rename the `.js` file to `.ts` as suggested in https://github.com/sveltejs/kit/issues/4341

**Comment by vhscom** [comment]
`PW_EXPERIMENTAL_TS_ESM=1` is required for the Playwright config to be written in TypeScript as of v1.20.

**Comment by vhscom** [comment]
`PW_EXPERIMENTAL_TS_ESM=1` is required for the Playwright config to be written in TypeScript as of v1.20. [Reference implementation](https://github.com/sveltejs/kit/issues/4194#issuecomment-1058242614). OP asked about an environment variable. Were you looking for something else?

**Comment by benmccann** [comment]
With the latest release of SvelteKit, when you setup a new Playwright+TypeScript project it is now working without needing any further changes

However, if I rename `playwright.config.js` to `playwright.config.ts` it does not work even when adding `PW_EXPERIMENTAL_TS_ESM=1`. Newly created projects are using Playwright 1.20.0

**Comment by aliak00** [comment]
I just now ran a completely new installation of sveltekit, did an `npm install` and then `npm test` and got this error. Adding `"test": "PW_EXPERIMENTAL_TS_ESM=1 playwright test"` did not work. (on mac m1).

**Comment by frederikhors** [comment]
Use 1.20.0, they are fixing bugs with 1.20.1.

**Comment by frederikhors** [comment]
Unfortunately:

I'm having this issue using both `1.20.1` and `next`:

![image](https://user-images.githubusercontent.com/41120635/160815400-1ff794fd-a4d7-4e07-acc5-e49de13b9754.png)

Only a VSCode issue. The tests are working.

If I use `./constants` (without `.ts`) I get error in pw at runtime: `[ERR_MODULE_NOT_FOUND]` using `PW_EXPERIMENTAL_TS_ESM=1 playwright test`.

**Comment by Rich-Harris** [comment]
I think this can be closed now? https://github.com/sveltejs/kit/pull/4479

**Comment by frederikhors** [comment]
I'm using SvelteKit with PW 1.20.2 with no problem and Typescript. I think we can close.
