### ISSUE TITLE
Scrolling to hash links is broken on Chrome

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4216]
### Describe the bug

Clicking a link like https://kit.svelte.dev/docs/configuration#version should take you to that part of the page. It works in Firefox...

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1162160/156806587-7f0ae30e-ae0e-4764-85b9-cb0ed65b892a.png">

...but not Chrome:

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/1162160/156806624-e851382f-c9f6-473f-b9b8-4b2db4bed51b.png">

### Reproduction

Go to https://kit.svelte.dev/docs/configuration#version in Chrome

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 69.61 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.30 
    @sveltejs/adapter-static: next => 1.0.0-next.28 
    @sveltejs/kit: next => 1.0.0-next.291 
    svelte: ^3.46.0 => 3.46.4
```

### Severity

annoyance

**Comment by PH4NTOMiki** [comment]
Testing fix now

**Comment by mrkishi** [comment]
You're never going to believe it, but it was introduced in #4155 _somehow_.

**Comment by PH4NTOMiki** [comment]
Makes sense, because it scrolls to the correct position temporary and then returns to 0

**Comment by PH4NTOMiki** [comment]
It's probably something to do with that clientHeight/Width bind, some Chrome edge-case/bug, but no idea how to fix it, maybe there is some other way to do that banner without that bind

**Comment by Conduitry** [comment]
Most of the more complicated stuff with the banner is no longer necessary with the shorter message on mobile that doesn't need to wrap. The whole thing should be able to be replaced with an HTML- and CSS-only banner that swaps out messages with media queries.

**Comment by PH4NTOMiki** [comment]
#4219 it looks like it works.

**Comment by PH4NTOMiki** [comment]
https://kit-svelte-dev-aigplkaoi-svelte.vercel.app/docs/configuration#version

**Comment by PH4NTOMiki** [comment]
Actually now it works on some loads and not on others, hmmm, looks like some racing condition

**Comment by PH4NTOMiki** [comment]
I think I actually figured the root cause of the issue

**Comment by PH4NTOMiki** [comment]
Closed #4219 it was just hiding the issue, need to investigate deeper.

**Comment by Rich-Harris** [comment]
Before this block of code, the page is correctly scrolled: https://github.com/sveltejs/kit/blob/cdc32a9f4f17d69be6ca1cae58bf3961155545a2/packages/kit/src/runtime/client/client.js#L330-L334

After, it's reset. So it's something to do with the hydration. Trying to create a minimal repro.

**Comment by PH4NTOMiki** [comment]
I think the browser tries to scroll, but the max scroll(full page height) changes slightly when hydrated(maybe just 1 pixel) and that causes it, but how to solve it is beyond me.

**Comment by Rich-Harris** [comment]
Ok I've managed to at least make a simpler repro: https://stackblitz.com/edit/sveltejs-kit-template-default-pm2sdq?file=src%2Froutes%2Ffails.svelte&terminal=dev

Visit https://sveltejs-kit-template-default-pm2sdq--3000.local.webcontainer.io/ and try going to `works` and `fails`. There's something about the combination of `{@html ...}` and `bind:clientHeight` that causes the scroll to be reset on hydration.

**Comment by benzara-tahar** [comment]
Just wanted to tell you guys, you are doing great job, I recently tried svelte (kit) and felt like am home 🚀 ( no  jsx, simplicity, chrome lighthouse is very happy ..etc)
I want to help with this but am still a noob,  am learning a lot reading what you're doing guys. Keep it up. 

And good luck with this scrolling bug 😊

**Comment by Rich-Harris** [comment]
Ok, so the bug isn't visible in the [Svelte REPL](https://svelte.dev/repl/d28fe0d4900d4a88b297c0f806d12067?version=3.46.4) for obvious reasons, but I think I have a basic understanding of why it's happening:

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/1162160/156846400-53cc35d8-402a-4242-b8dc-0345ffa75add.png">

On line 32, in the `l` (cLaim) method, the children of the `<main>` are being detached. The HTML isn't put back until line 42 in the `m` (Mount) method. Between claim and mount, the addition of the resize listener is somehow causing Chrome to reset the scroll (presumably Firefox waits until work is complete before assessing whether it needs to). I'm not sure why `innerHTML = html` doesn't happen during claim. Will raise an issue on the Svelte repo.

So we have lots of fixes to choose from:

* move the banner with the `bind:clientHeight` to below the HTML block
* reimplement it so it doesn't need `bind:clientHeight`
* add resize observer bindings to Svelte so it doesn't need to use the resize listener hack
* populate `{@html ...}` tags during claim instead of mount

**Comment by PH4NTOMiki** [comment]
@Rich-Harris I'm on my phone now, but one solution I can think of is to save scroll position to const before calling new Root
and after it just do 
scrollTo(pos.x, pos.y)

I don't it's good to just for it for the docs site because that bug could be happening on some other sites we don't know about.
That's just one of the most simplest solutions but your solutions are definitely better.

**Comment by Rich-Harris** [comment]
Opened https://github.com/sveltejs/svelte/issues/7341

**Comment by PH4NTOMiki** [comment]
@Rich-Harris It's happening again for me on the docs site, for ex. link https://kit.svelte.dev/docs/routing#advanced-routing-fallthrough-routes you posted in https://github.com/sveltejs/kit/issues/4291#issue-1165916525 
Interestingly enough, it happens most of the loads, but not always.

**Comment by frederikhors** [comment]
> Interestingly enough, it happens most of the loads, but not always.

Same here! Crazy! 😄

**Comment by PH4NTOMiki** [comment]
@Rich-Harris any idea why this could be happening? because I have none, one workaround I can think of is to check if hash is present and scrollTop is 0, If both are true then we do `document.getElementById(location.hash.slice(1)).scrollIntoView()` or something like that in `client.js` but I understand it's bad design.

**Comment by cliftonlabrum** [comment]
Hash links are working fine for me in Chrome Version 99.0.4844.84 on a Mac. Am I supposed to do something in particular to reproduce the issue?
```
https://kit.svelte.dev/docs/configuration#version
```
<img width="871" alt="HashLink" src="https://user-images.githubusercontent.com/2513753/161690720-682be9d1-418a-424a-8be7-6756bb7f9950.png">

**Comment by Morzaram** [comment]
> Hash links are working fine for me in Chrome Version 99.0.4844.84 on a Mac. Am I supposed to do something in particular to reproduce the issue?
> 
> ```
> https://kit.svelte.dev/docs/configuration#version
> ```
> 
> <img alt="HashLink" width="871" src="https://user-images.githubusercontent.com/2513753/161690720-682be9d1-418a-424a-8be7-6756bb7f9950.png">

This one is failing for me on the same version of chrome (M1 as well) as you @cliftonlabrum 
https://kit.svelte.dev/docs/routing#advanced-routing-fallthrough-routes

**Comment by p-lau** [comment]
It is working fine for me...

[Version 1.37.109 Chromium: 100.0.4896.60 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by winston0410** [comment]
Didn't work for me(Will attach the right version tomorrow)

**Comment by fjdumont** [comment]
Can not reproduce the behavior when clicking a link from another page (external or internal), i.e. the links in the Github comments above.

However, when middle-mouse-clicking, ctrl-clicking, or pasting the URL into a new tab, the scroll offset doesn't apply just as described in the issue. The same happens when I modify a link in this issue by adding `target="_blank"`.

I'm not sure if that's supposed to work like that, due to some browser limitations or something, so I'm not sure that helps.

[Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by moritzebeling** [comment]
Used to be broken in Safari as well. But seems to work from version `324`

**Comment by nubpro** [comment]
Faced this bug while I was learning sveltekit.

Click on this link (https://kit.svelte.dev/docs/types#generated-types), it doesnt scroll to that position on Chrome. But sometimes it does, very finicky.

**Comment by whataboutpereira** [comment]
I might have happened on a related issue - I'm finding that Chrome 102.0.5005.63 doesn't scroll to hash when the page is doing an inertial scroll from scrolling with a mouse. Hash links work only when the page has completely stopped moving from inertial scrolling.

**Comment by dummdidumm** [comment]
Can't reproduce this anymore, therefore closing this. The PR that would fix the underlying issue is https://github.com/sveltejs/svelte/pull/7426

**Comment by nilslindemann** [comment]
Please reopen, middleclicking the link does not scroll to the hash in recen chromium based browsers.

**Comment by kvetoslavnovak** [comment]
Having the same problem as well when I paste the hask link in Chrome (Chromium).
On the other hand hash links scroll works programaticaly (when generating  table of content links in navigation of my SvelteKit application).

**Comment by nilslindemann** [comment]
This works now! Thank you :-)

**Comment by gregg-cbs** [comment]
Hash links in an anchor tag are not working on firefox for me. But in a goto it does work.

If i have an anchor tag like so:
```html
<a  href="/terms-and-conditions#refund">See our refund policy here</a>
```

This goes to the page but does not scroll to the element with the id of "refund". If i refresh the page it goes to the refund elements position.

If i use goto function it goes to the page and scrolls to the section on the page:
```
<button  onclick={()=> goto("/terms-and-conditions#refund")>See our refund policy here</button>
```

**Comment by teemingc** [comment]
> Hash links in an anchor tag are not working on firefox for me. But in a goto it does work.
> 
> If i have an anchor tag like so:
> 
> <a  href="/terms-and-conditions#refund">See our refund policy here</a>
> 
> This goes to the page but does not scroll to the element with the id of "refund". If i refresh the page it goes to the refund elements position.
> 
> If i use goto function it goes to the page and scrolls to the section on the page:
> 
> ```
> <button  onclick={()=> goto("/terms-and-conditions#refund")>See our refund policy here</button>
> ```

Hi Gregg. Can you please open a new issue with a minimal reproduction and environment details such as OS and browser version so that we can try to reproduce it?

**Comment by gregg-cbs** [comment]
@teemingc - I did some testing on this. Creating a reproduction was hard to do and gave me varying results.

So i stripped back my page from any parent layouts, nothing fancy, just html content.

I made a video of this behviour to show the svelte behaviour. I also used chrome performance to show when the issue happens.

**Video of behaviour**: refreshing the page using ctrl+r or the browser reload button does not scroll to the hash element but pressing enter in the url bar does:
https://github.com/user-attachments/assets/2fcdfefa-6d07-44b0-bbcc-c25bda662e52

**Video of chrome performance**: timeline showing the browser goes to the hash section but then svelte goes back to the top:
https://github.com/user-attachments/assets/ed7286d7-019b-42da-9c79-ff2480d3fc37

I dont know how to see exactly what is restoring the scroll position in the chrome perf tab, i tried but was unsuccessful, any pointers would be great.

**Comment by gregg-cbs** [comment]
@teemingc - Here is a full on reproduction video of the issue happening along with a link to the codesandbox. This took me 6 hours of debugging today, i hope it is useful.

Video of the exact issue (excuse the distortion in my mic, turn down the volume to 50%):
https://www.youtube.com/watch?v=MIN5jCe3CF4

Codesandbox:
https://codesandbox.io/p/devbox/inspiring-orla-4zwlq3
