### ISSUE TITLE
Export `vite-plugin-sveltekit` for usage without Sveltekit CLI.

### ISSUE THREAD

**Issue by kwangure** [sveltejs/kit#4223]
### Describe the problem

It's currently not straight forward to build on top of Sveltekit since the CLI manages all our interactions with Sveltekit core. Since the refactor of [Sveltkit core into a plugin](https://github.com/sveltejs/kit/blob/4c5322aa4936b2c0e29d902a698932d0a69e53d9/packages/kit/src/core/dev/plugin.js), the path to making Sveltekit usable as a Vite plugin seems more tenable with a few modifactions. With the exception of the CLI, Sveltekit-package and adapters much of the framework's functionality lives in the internal plugins already. 

Reasons to export the plugin publicly:
- It's necessary for to build a meta-framework on top of Sveltekit
- Sveltekit would be easier to incorporate/migrate into a project already using Vite
- Tooling (e.g IDE or CI) can initiate Svelte kit programmatically without needing CLI
- Chrome extensions
	- In an extension, HTML files are the routes, so every page is essentially a Sveltekit instance. Coordinating this in a meta-framework setup is only possible if Sveltekit lends itself to easy programmatic control. Otherwise it's a mess -- [I speak from experience](https://www.npmjs.com/package/patootie).
- It's in the spirit of embracing Vite e.g. https://github.com/sveltejs/kit/issues/3659.
- Other tooling such as Vitest can use Sveltekit resolve alias etc.

### Describe the proposed solution

I imagine having the packages `@sveltejs/vite-plugin-sveltekit` and `@sveltejs/vite-plugin-sveltekit/core`.

`@sveltejs/vite-plugin-sveltekit` would be targeted at userland, and would be something like: 
```js
import kit from `@sveltejs/vite-plugin-sveltekit/core`;
import svelte from '@sveltejs/vite-plugin-svelte';

export default function vitePluginSveltekit(options) {
	const { kitOptions, svelteOptions } = options;

	// Vite flattens arrays of plugins
	return [
		svelte(svelteOptions),
		kit(kitOptions),
	];
}
```

and `@sveltejs/vite-plugin-sveltekit/core` would look like: 
```js
export default function sveltekitCore(options) {
	return {
		config(_config) {
			// Add internal Sveltekit config e.g $lib and $app aliases
		}
		configResolved(_config) {
			// Vite config validation now goes here...
		}
		// ... rest of core hooks
	}
}
```

and integrated into other setups like:
```js
import kit from `@sveltejs/vite-plugin-sveltekit/core`;
import svelte from '@sveltejs/vite-plugin-svelte';

export default function vitePluginSuperDuperSveltekit(options) {
	const { kitOptions, svelteOptions } = options;

	// Vite flattens arrays of plugins
	return [
		svelte(svelteOptions),
		kit(kitOptions),
		{
			name: "super-duper-sveltekit",
			// ...
		}
	];
}
```

I admittedly haven't thought too much how adapters fit into the picture since I'm not yet intimate with how they actually work.

### Alternatives considered

Add Sveltekit hooks. I haven't thought deeply about how this would look like but adding a plugin system on top of Svelkit might achieve something similar but it's additional overhead/maintenance for a less universally useful (read worse) outcome.

### Importance

would make my life easier

**Comment by benmccann** [comment]
Done in https://github.com/sveltejs/kit/pull/5094
