### ISSUE TITLE
adapter-vercel seems to be broken at @sveltejs/kit@1.0.0-next.292

### ISSUE THREAD

**Issue by brunobely** [sveltejs/kit#4224]
### Describe the bug

Vercel builds seem to be broken by #4192 since adapter-vercel [still uses `builder.prerender`](https://github.com/sveltejs/kit/blob/d028c7d27832cc5430a8a952fa9945a8edddf760/packages/adapter-vercel/index.js#L28-L30).

### Reproduction

[StackBlitz link](https://stackblitz.com/edit/sveltejs-kit-template-default-ansvrj?devtoolsheight=33&file=svelte.config.js)

Run `npm run build` to see error.

### Logs

```shell
At the end of build...

> Using @sveltejs/adapter-vercel
> builder.prerender() has been removed. Prerendering now takes place in the build phase — see builder.prerender and builder.writePrerendered
    at Object.prerender (file:///home/projects/sveltejs-kit-template-default-ansvrj/node_modules/@sveltejs/kit/dist/chunks/index4.js:183:10)
    at adapt (file:///home/projects/sveltejs-kit-template-default-ansvrj/node_modules/@sveltejs/adapter-vercel/index.js:116:38)
    at adapt (file:///home/projects/sveltejs-kit-template-default-ansvrj/node_modules/@sveltejs/kit/dist/chunks/index4.js:202:8)
    at eval (file:///home/projects/sveltejs-kit-template-default-ansvrj/node_modules/@sveltejs/kit/dist/cli.js:956:11)
```

### System Info

```shell
Default node.new/sveltekit env. Left the command above running for ~5min and got no response.
```

### Severity

blocking an upgrade

### Additional Information

Blocks upgrade to @sveltejs/kit@1.0.0-next.292

**Comment by Conduitry** [comment]
It looks like #4192 didn't include the appropriate changesets for any of the adapters, and so they weren't actually released.

**Comment by Travja** [comment]
Just going to note that this appears to impact more than just vercel. I'm attempting to build with the static-adapter and running into the same error message.

**Comment by evdama** [comment]
yes, same for `adapter-node`
```
Using @sveltejs/adapter-node
> builder.prerender() has been removed. Prerendering now takes place in the build phase — see builder.prerender and builder.writePrerendered
    at Object.prerender (file:///Users/sa/0/svk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.292_svelte@3.46.4/node_modules/@sveltejs/kit/dist/chunks/index4.js:172:10)
    at adapt (file:///Users/sa/0/svk/node_modules/.pnpm/@sveltejs+adapter-node@1.0.0-next.70/node_modules/@sveltejs/adapter-node/index.js:39:18)
    at adapt (file:///Users/sa/0/svk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.292_svelte@3.46.4/node_modules/@sveltejs/kit/dist/chunks/index4.js:191:8)
    at file:///Users/sa/0/svk/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.292_svelte@3.46.4/node_modules/@sveltejs/kit/dist/cli.js:936:11
 ELIFECYCLE  Command failed with exit code 1.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/sa/0/svk/build/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v17.6.0
```

**Comment by faisalramdan17** [comment]
The solution from me turns back or use the previous version that `1.0.0-next.288`.
you can try :

1) Change `"@sveltejs/kit": "next",` to be `"@sveltejs/kit": "1.0.0-next.288",` at `package.json`.
2) remove `"prepare": "svelte-kit sync"` at at `package.json`.
3) Run `npm install` 
4) After that *commit* & *push* your repo
5) Enjoy guys!

Thanks

**Comment by Sunyuzu** [comment]
`@sveltejs/kit@1.0.0-next.291` was also okay.
Thank you @faisalramdan17 for information.

**Comment by HalCodes** [comment]
Confirmed that this issue also affects `@sveltejs/adapter-netlify`.  Rolling back to @sveltejs/kit@1.0.0-next.291 is a working workaround.

**Comment by nstuyvesant** [comment]
See this issue is closed but I'm still experiencing the problem with adapter-node. Just reverted to SvelteKit 1.0.0-next.291 as a temporary fix.

**Comment by frederikhors** [comment]
The build is broken. The release of adapter-static 29 is coming.

**Comment by K-Sato1995** [comment]
> The solution from me turns back or use the previous version that 1.0.0-next.288.
> @sveltejs/kit@1.0.0-next.291

so any version that doesn't include the changes made by https://github.com/sveltejs/kit/pull/4192 currently works? (which seems to be `@sveltejs/kit@1.0.0-next.291`.

**Comment by baseballyama** [comment]
> so any version that doesn't include the changes made by https://github.com/sveltejs/kit/pull/4192 currently works?

Now we can install `@sveltejs/adapter-static@1.0.0-next.29` and other latest adapters!

**Comment by phiberber** [comment]
> > so any version that doesn't include the changes made by #4192 currently works?
> 
> Now we can install `@sveltejs/adapter-static@1.0.0-next.29` and other latest adapters!

I'm still having the same issue even with adapter-static 1.0.0-next.29.

**Comment by amarhasic** [comment]
> 

Same here, issue persists even with rolling back the adapter version.

**Comment by benmccann** [comment]
It would be much more useful to open a new issue rather than comment on a closed issue. The comments here have none of the information that would be required to debug an issue and the issue template will guide you to providing that information

**Comment by saturnonearth** [comment]
> > 
> 
> Same here, issue persists even with rolling back the adapter version.

I managed to fix mine by manually installing/updating both sveltekit and the adapter even though they were set to install the latest version when building in Netlify.

**Comment by benmccann** [comment]
You probably needed to update your npm lock file

**Comment by qudo-code** [comment]
![Screen Shot 2022-03-25 at 11 23 00 AM](https://user-images.githubusercontent.com/59782726/160188527-7b5ea0eb-91e1-4a7a-9526-7bb0d62ce2b1.png)
![Screen Shot 2022-03-25 at 12 28 59 PM](https://user-images.githubusercontent.com/59782726/160188619-4ba77969-0bae-4b4f-b423-4ae1dbd53207.png)
![Screen Shot 2022-03-25 at 12 29 25 PM](https://user-images.githubusercontent.com/59782726/160188664-79700a89-37d7-4433-862d-6e5af938118c.png)
![Screen Shot 2022-03-25 at 12 30 34 PM](https://user-images.githubusercontent.com/59782726/160188812-ddbd4077-eaaa-4cfa-bbd0-e31d3f1bc25b.png)

A fresh project and build with the latest versions or rolled back versions result in the following for me. Here are my configs and the error from adapter-static and adapter-node. I also tried Node 17.

**Comment by johnkegd** [comment]
Thanks dude. @faisalramdan17

**Comment by mhenrichsen** [comment]
After much trial and error here are some settings that work:
```
"@sveltejs/adapter-netlify": "1.0.0-next.49",
"@sveltejs/kit": "1.0.0-next.291",

```

**Comment by slier81** [comment]
why is this closed? has it being fixed?

**Comment by baseballyama** [comment]
Sometimes destructive change occur because kit is under beta.
And adapters may be updated at the same time accordingly.
This means that the kit and adapters is only work with certain version combinations.
So when you update kit version, I recommend that adapter version also should update as well.

This problem was opened when release timing between kit and adapters was off by several hours.
And it was fixed few hours later and this issue is now closed.

If you have a problem now, you need to open a new issue.

**Comment by justingolden21** [comment]
Has this issue been fixed? What version of the netlify adapter is necessary to fix?

Had no idea why my code was failing until this thread, and I didn't even update or install or remove any packages...

**Comment by lukas-h** [comment]
Ran into the same problem yesterday with adapter-node and had to downgrade to 288.

**Comment by qudo-code** [comment]
> Ran into the same problem yesterday with adapter-node and had to downgrade to 288.

Yeah, for me I only got around it with some magical combination of downgraded versions. Eventually something worked, not ideal by any means. 🤷

**Comment by tallestlegacy** [comment]
I did a `pnpm update` and it just worked
good things do happen when you update after all
