### ISSUE TITLE
devDependencies are included when running `pnpm run package`

### ISSUE THREAD

**Issue by CarlosIvanchuk** [sveltejs/kit#4226]
### Describe the bug

When I run `pnpm run package`, the generated package.json file inside the package folder contains all the devDependencies from the project root's package.json. Is this the correct behavior? Why should the end user install the devDependencies (which are only needed for the component library's documentation or demo site) when installing the package? This is a quote from the docs:

> A package.json copied from the project root with all fields but the "scripts" field. The "dependencies" field is included, which means you should add packages that you only need for your documentation or demo site to "devDependencies".

### Reproduction

Run `npm run package` and see that all devDependencies are copied in the generated package.json inside the package folder. https://stackblitz.com/edit/sveltejs-kit-template-default-uwyz79

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
    Memory: 401.75 MB / 3.75 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
Binaries:
    Node: 16.13.2 - /tmp/fnm_multishells/24095_1646447930303/bin/node
    npm: 8.4.0 - /tmp/fnm_multishells/24095_1646447930303/bin/npm
Browsers:
    Chrome: 99.0.4844.51
npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.30 
    @sveltejs/kit: next => 1.0.0-next.292 
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.36 => 1.0.0-next.39 
    svelte: ^3.44.0 => 3.46.4 
    vite: ^2.7.0 => 2.8.6
```

### Severity

annoyance

**Comment by bluwy** [comment]
When installing a package, the user doesn't download the `devDependencies`, only `dependencies`, so it's safe for it to be there.

**Comment by CarlosIvanchuk** [comment]
Oh, didn't know that. Thanks for the response. I think I should close this issue then
