### ISSUE TITLE
Ukraine support?

### ISSUE THREAD

**Issue by MarcGodard** [sveltejs/kit#4233]
### Describe the bug

Continuing this as free speech is important.

Have you guys not seen wag the dog (great movie). I speak 7 languages, traveled the world before having a family. I have read 100s of history books and think you guys need to remove your support for Ukraine.

Lock this thread and I will start another.

If you want to make a political message, I will keep making an issues with political content.

Because you have locked the last thread with history:  https://github.com/sveltejs/kit/issues/4222

If you do not want political threads, you shouldn't do political messages.

I bet you guys fell for BLM too. Sure, I support all life, but funny how the BLM leaders ran away with the millions collected from site supporting them. Funny how there is like 80 million of missing money.

I am sure you all fell for covid too, got double experimental injections, and this new war has nothing to do with all the data showing the experimental injections was gene therapy and welcome to being a GMO...

I am sure you guys fall for each "Current Thing" that is pushed by the media and government... you probably know nothing about how all the companies are owned by the same group of companies that all own each other and your government (yahoo finance has this really nice "holders" section).

But all the fact checkers say I am wrong... sure cause those same billionaires don't fund all those. They don't have an agenda........

Stop being retarded (yes that is the correct word), and use your brain a little. Be curious of the big scary world you live in.

I am no bible thumper but wow... the four horseman, 1st is white (like a doctors coat) holding a crown (corona = crown for anyone that knows langauges)... 2nd horseman is red (like communism) and tricks people to fight each others... 3rd is black (like black monday / thursday -- how we name market craches) and holds a scale to measure food.... famine... it is coming... 80% of the wolds money was created in the last 2 years... hyperinflation... but you guys wouldn't know anything about what is actually going on in the world. Because you are retarded.

### Reproduction

.

### System Info

```shell
.
```

### Severity

serious, but I can work around it

### Additional Information

.

**Comment by Conduitry** [comment]
> Lock this thread and I will start another.

You won't, because you will be blocked.
