### ISSUE TITLE
From 1.0.0-next.292: adapter-static: builder.prerender() has been removed. Prerendering now takes place in the build phase — see builder.prerender and builder.writePrerendered

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#4237]
### Describe the bug

Using:

```json
"@sveltejs/adapter-static": "1.0.0-next.28",
"@sveltejs/kit": "1.0.0-next.292",
```

during `npm run build`:

> Using @sveltejs/adapter-static
> builder.prerender() has been removed. Prerendering now takes place in the build phase — see builder.prerender and builder.writePrerendered

I'm in SPA only mode.

### Severity

blocking an upgrade

**Comment by PH4NTOMiki** [comment]
same as #4224
will be fixed

**Comment by frederikhors** [comment]
Close as duplicate of https://github.com/sveltejs/kit/issues/4224.
