### ISSUE TITLE
Cannot import from $app/navigation in latest SvelteKit

### ISSUE THREAD

**Issue by faulander** [sveltejs/kit#4241]
### Describe the bug

Cannot import from $app/navigation in latest version, eg:
import { goto } from '$app/navigation';

Completely deleted nodes_modules and package-lock.js didn't fix the issue.
I have another project with     
_@sveltejs/kit: next => 1.0.0-next.290_ 
works like expected there.

### Reproduction

https://svelte.dev/repl/fa848922791e40f7be794022a414a335?version=3.46.4

### Logs

```shell
Cannot find module '$app/navigation' or its corresponding type declarations.js(2307)
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 27.17 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 97.0.1
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.30 
    @sveltejs/kit: next => 1.0.0-next.292 
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by PH4NTOMiki** [comment]
That's not valid repro, can you do one on sveltekit.new
