### ISSUE TITLE
Servside code somehow runs on the client side (Svelte Kit + Prisma)

### ISSUE THREAD

**Issue by umgefahren** [sveltejs/kit#4258]
### Describe the bug

in the load function of my landing page i call (with svelte kits fetch) another api that fetches data from my database with prisma and then displays it.
This actually once worked, but now it is somehow suddenly broken and i get an error 500 that origins in Prisma, which critizes, that it can't run in the browser (very understandable).

I think that this is caused by the fetch method, that calls code on client not on the server ( as i interpreted it from reading the docs), it's also very possible that i missinterpreted something.

![image](https://user-images.githubusercontent.com/55623006/156942078-0201d3c9-f4ad-4728-9e30-959af5d59975.png)

### Reproduction

I can't really describe how to reproduce **exactly** however this is the repository in question: https://github.com/umgefahren/online-bank

### Logs

```shell
Client Side Logs:
500
PrismaClient is unable to be run in the browser.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
PrismaClient@http://localhost:3000/node_modules/.vite/@prisma_client.js?v=0f35e043:2555:24
module code@http://localhost:3000/src/lib/database.ts:2:32
evaluate@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
moduleEvaluation@[native code]
@[native code]
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
Server Side Logs:
 -- None --
```

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 433.74 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.30
    @sveltejs/kit: next => 1.0.0-next.292
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This seems like a very severe error and i had to stop working on the project, beacause of it. Maybe i just misread something

**Comment by Conduitry** [comment]
In your `index.svelte`, you are importing `$lib/user`, which imports `$lib/authentification`, which imports `$lib/database`, which instantiates `PrismaClient` from `@prisma/client`. You need to make sure you are not running code that might instantiate server-only components from code that is run on the browser.
