### ISSUE TITLE
builder.writePrerendered is not a function

### ISSUE THREAD

**Issue by necmettin** [sveltejs/kit#4259]
### Describe the bug

I am trying to create a self-contained node app with `npm run build`, as described in https://kit.svelte.dev/docs/adapters#supported-environments-node-js, but after vite v2.8.6 builds SSR bundle for production, I get this:

```
Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-node
> builder.writePrerendered is not a function
    at adapt (file:///home/t4/website/client/panel/node_modules/@sveltejs/adapter-node/index.js:37:12)
    at adapt (file:///home/t4/website/client/panel/node_modules/@sveltejs/kit/dist/chunks/index4.js:887:8)
    at file:///home/t4/website/client/panel/node_modules/@sveltejs/kit/dist/cli.js:1060:11
```

I have not modified the build command or the node adapter in any way.

### Reproduction

I am unable to share code. I will try with an empty SvelteKit repository but after seeing #4224, I thought this might be related/known.

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
    Memory: 349.17 MB / 908.55 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    npm: 8.3.1 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.30
    @sveltejs/adapter-node: ^1.0.0-next.71 => 1.0.0-next.71
    @sveltejs/kit: next => 1.0.0-next.291
    svelte: ^3.44.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I am unable to proceed and couldn't find any reference to this issue anywhere.

**Comment by Rich-Harris** [comment]
Your `@sveltejs/kit` is out of date:

```bash
npm i -D @sveltejs/kit@next
```
