### ISSUE TITLE
Docs: Dark mode not working in firefox developer edition

### ISSUE THREAD

**Issue by danielkellyio** [sveltejs/kit#4263]
### Describe the bug

When using Firefox Developer Edition with my systems Dark mode preference, the documentation site is illegible. The text seems to get the color for the dark mode but the background is still white. 
<img width="1440" alt="Screen Shot 2022-03-07 at 6 46 13 AM" src="https://user-images.githubusercontent.com/7635209/157037553-08e4a414-d945-4fc7-b9aa-484a39f87028.png">

### Reproduction

open up the production docs site in Firefox Developer Edition

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 180.48 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.npm-packages/bin/yarn
    npm: 7.19.1 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 94.0.2
    Firefox Developer Edition: 98.0
    Safari: 15.0
```

### Severity

annoyance

**Comment by kelvindecosta** [comment]
The documentation styles are derived from `@sveltejs/site-kit`.
The text color is computed from the `--text` CSS custom property (this [line](https://github.com/sveltejs/sites/blob/58dde6c5e243996a30da4d42408845e968682110/packages/site-kit/src/lib/base.css#L47)).
Perhaps this `--text` property is affected somehow?

**Comment by Rich-Harris** [comment]
Is this specific to developer edition? Is it still happening? I've never been able to reproduce it

**Comment by danielkellyio** [comment]
Just checked in Firefox developer edition and (with system preferences set to dark mode) I get a working light mode with legible text, so I guess this has been solved. :)
