### ISSUE TITLE
Remove network calls from demo app

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#4264]
### Describe the bug

I have seen so many people complaining that SvelteKit is slow. No one realizes that a locally created demo app would be making network calls.

E.g. https://discord.com/channels/457912077277855764/939868205869072444/950313663850508328

This would also solve our issues around eventual consistency: https://github.com/sveltejs/kit/issues/1564

### Reproduction

I don't know if these people have particularly slow network connections or the app or host is sometimes being quite slow

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Even without the speed concerns, I'd be in favor of a tiny ad-hoc in-memory data store thing for the todo app rather than calling out to the Cloudflare KV API.

**Comment by am283721** [comment]
I'm wondering if it's an issue with the API being served from somewhere in North America and certain users on other continents experiencing unusually slow network performance?

I also think some sort of in-memory data store would provide a better/more consistent user experience as long as it's still able to demonstrate the same functionality that is shown with the current setup. Specifically things like utilizing fetch, handling redirects, method overrides, etc... Having a demo that interacts with an external API is very useful as most people will need to do the same, and showing some best practices helps them get started on the right foot.

An update here could also be an opportunity to add functionality demonstrating shadow endpoints (unless that would create too much confusion for new users).

**Comment by baseballyama** [comment]
IMO...

By default, the Demo app will use an in-memory object.
And as default, commenting out files that connect to the API,
If users want to try to use API also, then users can use the commented-out files.
Then users don't need to feel bad experience.
And even users can try persistence and dynamic SSR if necessary.

**Comment by am283721** [comment]
I was thinking using something like [json-server](https://github.com/typicode/json-server) could provide a good middle-ground, where a full rest api could be utilized but the backend is running in the same environment as the frontend.

To me, persisting data between a local dev environment and a deployed environment isn't that important, considering in most real-world scenarios you wouldn't want that either.

The main downside I can see of using something like `json-server` is introducing a 3rd party dependency to the demo app that might require future maintenance. Secondarily, it adds a little more code and complexity to the demo app.

**Comment by aolose** [comment]
I prefer the app to send these requests, it is closer to reality. We need a more friendly interactive experience.
For example, you could add a status display to each new todo item instead of waiting for the request to complete before adding it to the list.

**Comment by Rich-Harris** [comment]
To be clear, the issue isn't persisting data between local and deployed, it's having a backend that works both locally and deployed

**Comment by baseballyama** [comment]
> it's having a backend that works both locally and deployed

I may not be getting it correctly, but https://github.com/sveltejs/kit/pull/4266 stores data for each user, so there is no data conflict even if multiple people connect to the deployed app. The only issue is losing all data when the app is deployed.
(But personally, I think this is a smaller issue than a bad experience.)

**Comment by alexiglesias93** [comment]
Perhaps a simpler solution would be to just add some `Loading` states in the UI that explicitly show that the app is performing some requests in the background?
- Show a [Preloading Indicator](https://github.com/sveltejs/sites/blob/master/sites/svelte.dev/src/lib/components/PreloadingIndicator.svelte) when navigating through pages.
- Show a loading spinner when creating/updating/deleting a TODO.

**Comment by jycouet** [comment]
Could we imagine providing both experiences with an environment variable switch?
_(Defaulting to `false`)_
```ts
const base = localDev ? 'http://localhost:3000/api/local_api_svelte_dev' : 'https://api.svelte.dev';
```
And implement `get` `post` `patch` `del` in `api/local_api_svelte_dev`?

After, the question is: Is it a realistic demo?

**Comment by Rich-Harris** [comment]
Something else I've just realised: for whatever reason, the todos page doesn't work on StackBlitz (https://sveltekit.new). Unclear whether it's a fixable bug or an inherent limitation, but could turn out to be another good reason to change the demo

**Comment by jycouet** [comment]
Yes, `userid` is set in cookies and it seems that StackBlitz can't support this without customizing some browser settings.

In a demo remote fetch is nice to showcase imo. But maybe only reading data is sufficient?
And a second part with some local things?

I'll be happy to help, let me know how.

**Comment by samal-rasmussen** [comment]
Here's a little demo of the janky behavior you get when clicking on the `todos` tab now:

https://user-images.githubusercontent.com/1503031/176706300-e7711381-8fa9-4337-b68d-f151f0657af3.mov

**Comment by samal-rasmussen** [comment]
OK, so I've tried investigating this a bit further to see if I can find a path forward here.

Rich's comment [here](https://github.com/sveltejs/kit/issues/4264#issuecomment-1060924682) gives me the understanding that the point of the todos page is to demonstrate `persistence and dynamic SSR`. I take it that `persistence` here means that there has to be a network request to a remote server that persists the data. And `dynamic SSR` means the ui should be able to render on the server using data that is not statically stored with the source code, but rather fetched from somewhere else at render time.

Neither of these two requirements make the ui freeze when clicking todos necessary as far as I can tell. When clicking todos we are doing client side rendering and not SSR, right? So waiting for SSR should not be a limitation. I see no reason why the ui couldn't do the page transition even if the server is doing some async fetching of persisted data before returning a response. After the page transition we could just use the `await` block to show some loading state while waiting for this data in the todos component.

In theory this makes sense to me. But as far as I can tell Sveltekit endpoints are based on load functions which are implemented such that they always block rendering when they are async.

**Comment by UltraCakeBakery** [comment]
How about just displaying the latency / response time after each submit below the submit form? Or some status updates about what the request is doing?
