### ISSUE TITLE
Allow vite plugins to be run before compilation

### ISSUE THREAD

**Issue by Marr11317** [sveltejs/kit#4280]
### Describe the problem

So from what I understand, preprocessors (for svelte kit) are basically vite plugins running before vite-plugin-svelte. They also have an easier access to the content of scripts and style tags, but let's consider the case where only the `markup` preprocessor is used.

Now, for the sake of portability, I'm using [unplugin](https://github.com/unjs/unplugin) to create plugins for vite and other similar frameworks.

Unfortunately, these plugins run **after the svelte to js transpilation**. This means it is not easy to modify .svelte files, because it's the resulting js that will be modified.

So, I'd love a way to run these plugins *before* transpilation.

### Describe the proposed solution

Add a `beforeKitPlugins` options:

```js
// svelte.config.js
/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		preprocess(),
		// MyPlugin.transform // This is doable, but prevents using more vite features.
	],

	kit: {
		adapter: adapter(),
		vite: {
			plugins: [
				// MyPlugin(), // I would like this one to run **before** transpilation
			],
		}
	},

	// Best option:
	pluginsBeforeKit: [
		MyPlugin()
        ]
};

export default config;
```

### Alternatives considered

Create a preprocesssor. But that defeats the purpose of  [unplugin](https://github.com/unjs/unplugin).

### Importance

nice to have

**Comment by bluwy** [comment]
Unplugin can set `enforce: "pre"`, which should run before `vite-plugin-svelte`. But I think the correct way is to use preprocessors? Its purpose is to be bundler agnostic too.

**Comment by Marr11317** [comment]
`enforce: "pre"` does [not work with rollup and esbuild](https://github.com/unjs/unplugin#hooks). Which means it may work at dev time, but not at dev time, and will prevent sapper from being supported.

**Comment by bluwy** [comment]
> `enforce: "pre"` does [not work with rollup and esbuild](https://github.com/unjs/unplugin#hooks). Which means it may work at dev time, but not at dev time, and will prevent sapper from being supported.

It doesn't matter. For rollup and esbuild, there's no sense of `enforce` since plugins are ordered the way they are defined. Not having support for them doesn't mean is should be avoided. You can still use it in rollup by placing your unplugin before `rollup-plugin-svelte`.

**Comment by Marr11317** [comment]
You are right. As long as the sveltekit plugin itself doesn't use `enforce`, using enforce is fine.

I'll mark this as resolved, with the solution being to 

1) Use `enforce: "pre"`
2) Tell users of rollup and esbuild to place the plugin before any svelte transpilation is done.
