### ISSUE TITLE
Page with `load()` still calls shadow endpoint, and SSR returns endpoint data.

### ISSUE THREAD

**Issue by georgecrawford** [sveltejs/kit#4283]
### Describe the bug

When a shadow endpoint exists, but the page implements a `load()` function, the shadow endpoint is still called during SSR. The endpoint response is available in the page source HTML, but isn't exposed to the `load()` function in a useful way, so can't be used.

I'd say this is either a bug (the endpoint shouldn't be called) or an undocumented and inaccessible feature (my preference - I'd _love_ to have access to this endpoint data in a page which implements `load()` for other reasons - e.g. to occasionally return `fallthrough: true` - see [discussion](https://github.com/sveltejs/kit/discussions/4282)).

### Reproduction

See [Stackblitz example project](https://stackblitz.com/edit/sveltejs-kit-template-default-ycrecf?file=src%2Froutes%2Findex.svelte&terminal=dev).

**index.svelte**
```
<script context="module">
  export async function load() {
    return {props: {data: 'from load function'}}
  }
</script>

<script>
export let data;
</script>

data: {data}
```

**index.js**
```
export async function get() {
	console.log('endpoint running now!');
	return {
		body: { data: 'from endpoint' }
	};
}
```

### Logs

When the page is loaded, the server logs `endpoint running now!`. The HTML response from SSR contains the endpoint response:
```
<script type="application/json" sveltekit:data-type="props">{"data":"from endpoint"}</script>
```

### System Info

Stackblitz couldn't provide this info. SvelteKit 1.0.0-next.294.

### Severity

annoyance

**Comment by geoffrich** [comment]
The response from the endpoint is available in load via [props](https://stackblitz.com/edit/sveltejs-kit-template-default-ycrecf?file=src%2Froutes%2Findex.svelte&terminal=dev)

```html
<script context="module">
  export async function load({ props }) {
    return {props: {data: props.data + ' from load function'}}
  }
</script>

<!-- Renders "data: from endpoint from load function" -->
```

Is this what you're looking for?

**Comment by georgecrawford** [comment]
Amazing. Thanks @geoffrich - I'd missed that part of the docs.
