### ISSUE TITLE
Copy url to clipboard on server start : dev mode

### ISSUE THREAD

**Issue by foochris** [sveltejs/kit#4286]
### Describe the problem

As a developer, I'd like to have the URL of the development server copied to the clipboard upon start of the server.

e.x.:
```
npx svelte-kit dev --copy
```

### Describe the proposed solution

Similar to Vue's `vue-cli-service serve` [[link](https://cli.vuejs.org/guide/cli-service.html#using-the-binary)] an option `--copy` would made be available:

```
Usage: vue-cli-service serve [options] [entry]

Options:

  --open         open browser on server start
  --copy         copy url to clipboard on server start
  --mode         specify env mode (default: development)
  --host         specify host (default: 0.0.0.0)
  --port         specify port (default: 8080)
  --https        use https (default: false)
  --public       specify the public network URL for the HMR client
  --skip-plugins comma-separated list of plugin names to skip for this run
```

### Importance

nice to have

**Comment by rmunn** [comment]
That would require something like https://github.com/sindresorhus/clipboardy, which seems a bit much to pull in as a Svelte-Kit dependency just to save a few mouse clicks. I don't think the benefit outweighs the cost in this case: most terminals will let you right-click the URL printed to the terminal and copy it to the clipboard.

**Comment by dominikg** [comment]
There is `--open` already which is more useful and less invasive than overriding clipboard. 
See https://kit.svelte.dev/docs/cli#svelte-kit-dev

If you really need copy, you can add it with a vite plugin. See https://github.com/svitejs/vite-plugin-qrcode/blob/main/packages/vite-plugin-qrcode/src/index.ts
for inspiration.
