### ISSUE TITLE
Throw an error (or warn?) if using adapter-static with invalid routes

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4287]
### Describe the problem

`adapter-static` is a source of confusion for people who believe that it allows you to _somehow_ publish an app with dynamic server rendering and/or endpoints with POST/PATCH/DELETE/etc handlers to GitHub pages.

### Describe the proposed solution

I haven't thought deeply about the implementation, beyond this:

* If pages are left unprerendered, `adapter-static` should throw an error unless `fallback` was specified.
* If an endpoint has non-GET handlers, `adapter-static` should throw an error regardless of whether `fallback` was specified.

### Alternatives considered

More complete documentation, and spending more time dealing with issues

### Importance

would make my life easier

**Comment by Mlocik97** [comment]
I'm for warn, but not error... Sometimes I want to have implemented endpoints with post/patch/delete or hooks and other dynamic server stuff, and use `adapter-static` for example if you want to implement website (using node resp. `adapter-node` or some server-less one), but at the same time use same source codes to generate static assets for for example electron/neutralino app, or nativescript mobile app. Then I have two adapters in config, and two build commands that build for website or app based on for example `process.env`. So error would "break" this. But there should be warn definitelly.

**Comment by Rich-Harris** [comment]
Prerendering happens automatically, regardless of what adapter you're using. In the rare case that an adapter doesn't specify where the prerendered output should be copied to, it's accessible at `.svelte-kit/output/prerendered`, so I'm not sure there's I understand why there's a reason to run `adapter-static` alongside a separate adapter.

**Comment by Spenhouet** [comment]
I'm a bit confused about what's supposed to work and what not.

I'm using the **page routing (via slugs in file names), matchers and page endpoints (only GET)**. It's working when starting the dev environment but not when building it with adapter-static and deploying it to gh-pages.
**Which of these three features should generally work with adapter-static?** Are there any caveats? 

_Not going into any specifics here. If you say all three features generally should work, I will dig deeper and eventually open an issue to sort it out._

**Comment by Mlocik97** [comment]
> Prerendering happens automatically, regardless of what adapter you're using. In the rare case that an adapter doesn't specify where the prerendered output should be copied to, it's accessible at `.svelte-kit/output/prerendered`, so I'm not sure there's I understand why there's a reason to run `adapter-static` alongside a separate adapter.

sometimes I have reason to not prerender (for adapter-node).
