### ISSUE TITLE
The inlineStyleThreshold option doesn't work

### ISSUE THREAD

**Issue by ciricc** [sveltejs/kit#4288]
### Describe the bug

I want to minify my website css requests count because i have only 7 kb page size with all js css stylesheets code. But for now, SvelteKit build creates many splitted css files. I've tried setup the `kit.inlineStyleThreshold` = 1 bytes but builder ignoring this option and continue creating css chunks without putting them all into <style> tag.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-yyekv4?file=svelte.config.js

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 686.20 MB / 6.94 GB
  Binaries:
    Node: 14.18.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - D:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.36)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.31
    @sveltejs/adapter-node: ^1.0.0-next.71 => 1.0.0-next.71
    @sveltejs/kit: next => 1.0.0-next.295
    svelte: ^3.46.0 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
As described in https://kit.svelte.dev/docs/configuration#inlinestylethreshold, this setting is the _maximum_ length of CSS files to be inlined, not the minimum.
