### ISSUE TITLE
sveltekit - deliberately crash

### ISSUE THREAD

**Issue by pjebs** [sveltejs/kit#4317]
### Describe the problem

Is there a way to deliberately crash a sveltekit app (on the client) in PROD without displaying a stack trace or other potentially sensitive data?

### Describe the proposed solution

a simply labelled function that can be called from anywhere in sveltekit application that will cause a runtime crash.

### Importance

nice to have

### Additional Information

Other languages and frameworks have this feature.

**Comment by Rich-Harris** [comment]
What do you mean 'crash on the client'? There's nothing sensitive in a client-side stack trace, and server-side stack traces are already removed in prod (unless you have a reproduction of this not happening?)

**Comment by pjebs** [comment]
Make the app unusable until a reload.

**Comment by pjebs** [comment]
How could it be done via userland?

My use case it's:
1. I'm building a progressive webapp using svelte kit and adapter-static.
2. I'm releasing it as a beta to people.
3. I want to 'invalidate' the app after a certain date.
4. I'm concerned people will keep a copy of the source (as it's a static site)

Hence, my solution is to 'crash' the application.

**Comment by Rich-Harris** [comment]
Right, but what does 'crash' mean? Be super-specific!

**Comment by pjebs** [comment]
Updated comment

**Comment by pjebs** [comment]
It's not the same but Many server side frameworks such as PHP/laravel has a function to provide that functionality. eg. `abort()`

**Comment by Rich-Harris** [comment]
Again, please explain what 'crash' means. In what _specific_ ways does the app become 'unusable'? Does the page immediately vanish, replaced with an error page? Does the router stop working? Do components become non-interactive? How is all this communicated to the user? We can't discuss a feature request without knowing what the feature is.

**Comment by pjebs** [comment]
Yes I misunderstood what you wanted because for my particular use case I don't care what happens or gets displayed to the user, as long as the site just stops working (until at least a reload, in which case I will call the `abort` function again).

But for a more generally applicable feature request, I *guess* the ability to display a custom static page and make javascript interpretation stop working. 

I've tried throwing an uncaught exception, but it just displays a message in console, but everything still works as best as it meaningfully could. 

Maybe sveltekit can produce output with `Content-Type: text/plain`.

**Comment by Rich-Harris** [comment]
> I don't care what happens or gets displayed to the user, as long as the site just stops working

This is user-hostile design and I hope you reconsider. But this can be done in userland — just redirect someone to a page that uses [`beforeNavigate`](https://kit.svelte.dev/docs/modules#$app-navigation-beforenavigate) to prevent the user from navigating onwards or backwards. There's no reason to add stuff to SvelteKit to achieve this.

**Comment by pjebs** [comment]
Is there a way for sveltekit to return `Content-Type: text/plain`?
