### ISSUE TITLE
Load fetch resolver address

### ISSUE THREAD

**Issue by MushiX** [sveltejs/kit#4320]
### Describe the bug

If application started at this url: http://application.lh application default cut prefiks and change url.
from: http://api.application.lh/endpoint
to: /endpoint

if http://api.application.lh is other application this process been failed.

### Reproduction

On external application on url: `http://api.application.lh` you can have something like that:

```js
import Fastify from 'fastify'
const fastify = Fastify({
  logger: true
})
// CommonJs
const fastify = require('fastify')({
  logger: true
})

// Declare a route
fastify.get('/endpoint', function (request, reply) {
  //reply.send({ hello: 'world' })
  return JSON.stringify({result: "Hello World"});
})

// Run the server!
fastify.listen(3000, function (err, address) {
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  // Server is now listening on ${address}
})
```

Everything work if you use `curl http://api.application.lh/endpoint` you get a message: "Hello World".

On file: __layout.svelte
```js
<script context="module">
  export async function load({session, fetch}) {
    let url = 'http://api.application.lh/endpoint';
    
    const result = await fetch(url, {
	    method: 'GET',
	    headers: {
		    'Content-type': `application/json`
	    }
    });
  }
</script>
```
But if you use fetch in svelte you get a error.

PORTS IN URL's IS DON'T NEED I USE DOCKER AND HAVE PORT 80 / 8080 IN ALL APPS!

Normal JS fetch working correctly!

### Logs

`etshops-wholesalers-1  | <pre>Not found: /authentication/token</pre>`

### System Info

```shell
System: Alpine on docker (node:alpine)
Binaries: Vanilla SvelteKit installation
Browsers: All browser the same result
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
I'm sorry, that's not a reproduction. I have no idea what issue you're describing!

**Comment by emil-1996** [comment]
I have the same problem. SvelteKIT fetch is broken. 

example: 

`export async function load({session, fetch}) {
  let url = 'http://api.application.localhost/endpoint';
  
  const result = await fetch(url, {
	  method: 'GET',
	  headers: {
		  'Content-type': `application/json`
	  }
  });
}`


Svelte kit try fetch /enpoint NOT  full url http://api.application.localhost/endpoint

**Comment by Rich-Harris** [comment]
@emil-1996 that's also not a reproduction, I'm hiding your comment

**Comment by emil-1996** [comment]
VERSION FOR @[Rich-Harris] (low IQ) 

IF your application have domain example: https://etdeal.pl/
AND YOU try fetch http://api.etdeal.pl/endpoint'; 

Sveltekit fetch try fetching /endpoint  not fetching full url

**Comment by MushiX** [comment]
@emill-1996 Yeah I saw the same problem im my app. One think to can resolve this problem is a use node-fetch and change config on svelte. But this is problematic and wrong way in my opinion! I want use one svelte fetch but this wrong behavior in my opinion.

**Comment by Rich-Harris** [comment]
@MushiX Please familiarize yourself with the instructions for providing a reproduction: https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml

If no reproduction is provided, this issue will be closed.

**Comment by MushiX** [comment]
@Rich-Harris How to run second application on this reproduction tool ? On a subdomain address ?
How to install docker, because I can't find this possibility.

**Comment by Rich-Harris** [comment]
just create a `server.js` file and launch it from an `npm run dev` script or something

**Comment by itemodahl** [comment]
We might have the same problem in our project. We need to fetch data from an endpoint with a different domain. After we upgraded svelte-kit from @sveltejs/kit@1.0.0-next.229 -> 297, the fetch function stopped working. We are using @sveltejs/adapter-node as well, so it could be an issue with some configurations there.

**Comment by MushiX** [comment]
We resolve this problem using `links` on docker-compose.yml. Second resolve this problem is add <IP contener> api.application.lh to /etc/hosts.

I close this issue, this is not wrong working SvelteKit but my setup.
