### ISSUE TITLE
Prerender, cache buffor - dependent on URLsearchParams,, cookies, other header and mayby something else

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#4321]
### Describe the problem

Prerender, cache buffor - dependent on URLsearchParams,, cookies, other header and mayby something else

I'm wondering if `prerender` should be available for different variations of a page?

### Describe the proposed solution

Currently it is possible to make a `prerender` for `page.com/path1`.

But it is not possible to do `prerender` (cache?) for e.g. `page.com/path?param1=a`?

Is that correct?

Likewise, it is not possible to do a `prerender` for a variant of a page, with a specific preference in the cookie.

Is it a good idea to introduce `prerender` support for various more specific page variants?

Second thing - is there a standard way to do a cache, based on requests to the server?
That is, if a user enters, for example, `page.com/path?param2=ha`, a variant of that page is created that is returned instead of re-rendering when another user enters the same url.
I know that in `Hooks.handle` you can save and later read the `request` and `response` for a given urls, but you have to prepare it manually.

Such a question/proposal. What do you guys think about it?

### Importance

nice to have

**Comment by Rich-Harris** [comment]
Prerendering literally means writing files to the filesystem, so that an arbitrary static webserver can serve them. A webserver isn't going to know what to do with a query string. It's not possible.

**Comment by lukaszpolowczyk** [comment]
@Rich-Harris  And what about server content cache for pages?
Instructions to the server content cache could be declared in the svelte file in `<script context="module">`, and the adapter would simply get this information.
The adapter would prepare a server cache for each page variant.
