### ISSUE TITLE
Option to extend which files svelte-kit dev restarts with. Ex: *.lua, *.ts, *.js..etc

### ISSUE THREAD

**Issue by careerlister** [sveltejs/kit#4350]
### Describe the problem

It would be a great convenience if the option in the svelte-kit dev command could include file types it would restart with.  I am working with lua scripts in a current project that get read into ioredis commands so that they can be used in REDIS.  >> https://redis.io/commands/eval.     I am having to restart the server manually every time I make a change to a lua file.   Mean while the *.ts & *.js files restart on change?

### Describe the proposed solution

Allow the svelte-kit dev cli command to have the option to extend which files the process is watching and restart on chnage.  

Ex solution:  svelte-kit dev --watch *.lua *.ts *.js    

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
I'm not sure what you mean by 'restart on change'? The dev server _doesn't_ restart on change, it simply (hot) reloads the page. This feels like something that needs to exist outside the SvelteKit CLI (i.e. you invoke `svelte-kit dev` inside a command that watches `.lua` files and restarts the process when they change)

**Comment by careerlister** [comment]
Thank you for responding so quickly.  I can see how that statement is confusing.  I am learning so I may have some miss understandings of how svelte-kit command works.  Thank you in advance for your patience.   

Here is the "would make my life better"  :  when a change to a .ts or .js occurs the code reloads.  I would like the ability for the command to also recognize lua files (or any file extension) to reload so that the change in the lua file is recognized.   Currently manually stoping the process (control c) and running npm run dev again ensure the server recognizes the change.

I apologize if I am assuming this is how the command would/could work and it doesn't.   Any help would be appreciated.

BTW:  Excellent work on Sveltekit.  Sveltekit & Svelte feel more intuitive than the other similar solutions out there to me.  Happy programmer here!  Thank you.

**Comment by bluwy** [comment]
You can configure the extra files with https://github.com/antfu/vite-plugin-restart, which can be passed to `config.kit.vite.plugins`. Restarts (or HMR) only happens currently for files you import, if they are not, you'd have to reload it yourself, or with a Vite plugin.

**Comment by Rich-Harris** [comment]
Going to go ahead and optimistically assume that vite-plugin-restart solves this problem, and close the issue
