### ISSUE TITLE
Endpoint Redirect Issue

### ISSUE THREAD

**Issue by lemmon** [sveltejs/kit#4369]
### Describe the bug

When performing redirect from within the `load()` function everything seems to be working as expected:

```html
<!-- hello/index.svelte -->
<script context="module">
export async function load() {
  return {
    status: 302,
    redirect: `/`,
  }
}
</script>
```

However when I drop the .svelte file and replace it with just .js endpoint the redirect gets broken and empty json object is returned instead.

```js
// hello/index.js
export async function get() {
	return {
		status: 302,
		redirect: '/'
	};
}
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-zzqmwt?file=src%2Froutes%2Fhello%2Findex.js&terminal=dev

### System Info

```shell
.
```

### Severity

serious, but I can work around it

**Comment by halindraprakoso** [comment]
`redirect` only exists on the load function though. To redirect from an endpoints you need to return location header https://kit.svelte.dev/docs/routing#endpoints

**Comment by lemmon** [comment]
Oh I see. Thanks! It's somewhat confusing, one would expect that the endpoints and pages have similar api.

**Comment by Conduitry** [comment]
The types for [`load` output](https://kit.svelte.dev/docs/types#additional-types-loadoutput) and [endpoint output](https://kit.svelte.dev/docs/types#sveltejs-kit-requesthandleroutput) are documented. They differ because there are rather different sorts of things one can do in them.
