### ISSUE TITLE
(adapter-static) fallback: '404.html' => index.html disappears

### ISSUE THREAD

**Issue by pjebs** [sveltejs/kit#4376]
### Describe the bug
**ADAPTER-STATIC**
When I set `fallback: '404.html'`, the `index.html` file is not generated.
So the site no longer works.

### Reproduction

```
    adapter: adapter({
      fallback: '404.html'
    }),

```

### System Info

```shell
Mac
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
From the issue template: 

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
