### ISSUE TITLE
adapter-static: prevent generated files and directories from beginning with underscore (for github pages)

### ISSUE THREAD

**Issue by pjebs** [sveltejs/kit#4378]
### Describe the bug

I have a public repo: `https://github.com/rocketlaunchr/petersir`
It has **github pages** setup with a custom domain: `petersir.com`

My svelte config file looks like this:

```
import { optimizeImports } from 'carbon-preprocess-svelte';
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: [optimizeImports()],
  kit: {
    adapter: adapter({
      fallback: '404.html'
    }),
    files: {
      assets: 'src/static'. /// <--------- used to copy favicon files to root directory after running build command. 
    },
    trailingSlash: 'always'
  }
};
```

When I go to the site: `https://petersir.com`, the page is blank.
When I look in the console it shows 404 errors for the crucial JS files (despite definitely existing):

<img width="477" alt="image" src="https://user-images.githubusercontent.com/5377970/158935862-408e9099-1691-460a-bfba-db2866c7d4bc.png">

However, the browser fetches the favicon file which is located in the root directory

### Reproduction

See above:

The repo is public: https://github.com/rocketlaunchr/petersir

### Logs

```shell
GET https://petersir.com/ 404
petersir.com/:11          GET https://petersir.com/_app/assets/vendor-8149caf7.css net::ERR_ABORTED 404
petersir.com/:1          GET https://petersir.com/_app/start-2f6645ce.js net::ERR_ABORTED 404
petersir.com/:1          GET https://petersir.com/_app/chunks/vendor-92f0db20.js net::ERR_ABORTED 404
petersir.com/:1          GET https://petersir.com/_app/chunks/preload-helper-e4860ae8.js net::ERR_ABORTED 404
petersir.com/:1          GET https://petersir.com/_app/chunks/singletons-d1fb5791.js net::ERR_ABORTED 404
```
```


### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 156.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.4.1 - /usr/local/bin/node
    npm: 8.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Safari: 15.2
```
```


### Severity

blocking all usage of SvelteKit

### Additional Information

github pages seems to be set up correctly: for example, the favicon is being pulled properly.

**Comment by pjebs** [comment]
Okay, I discovered the **primary issue**.

Github Pages produces 404 for directories starting with underscore. Therefore `appDir` should be set:

```
const config = {
  preprocess: [optimizeImports()],
  kit: {
    adapter: adapter({
      fallback: '404.html'
    }),
    files: {
      assets: 'src/static'
    },
    trailingSlash: 'always',
    appDir: 'app'  // <------------ Very important to change from _app to app.
  }
};
```
It would be good to add this to the `adapter-static` documentation too.


....


<img width="740" alt="image" src="https://user-images.githubusercontent.com/5377970/158939043-d9698b3d-b036-4e68-b460-9ccbd4153def.png">


BUT how can I prevent sveltekit from generating files with `_` eg `__layout.svelte-a94bc638.js`?

**Comment by pjebs** [comment]
Problem fixed: You need to add a blank file called `.nojekyll` to configure github pages to not produce 404 files for `_` files/folders.

**Comment by xpluscal** [comment]
@pjebs I added the .nojekyll and have the same issue still. Any other ideas?

**Comment by pjebs** [comment]
@xpluscal What else did you do?

**Comment by stephen-digicert** [comment]
I am facing a similar issue. Folders and files prepended with an underscore are ignored. Currently i can't get my layout assets to output with a different filename, has anyone found a more permanent solution to this?

**Comment by ozzythecoder** [comment]
Having this issue as well. Adding the .nojekyll file hasn't changed anything for me.

**Comment by ashley-cai** [comment]
Had this issue -- fixed after making the .nojekyll file **manually** on the gh-pages branch on Github.
