### ISSUE TITLE
`browser.hydrate: false` breaks client-side router

### ISSUE THREAD

**Issue by martinszar** [sveltejs/kit#4382]
### Describe the bug

Setting `browser.hydrate` to `false` renders the client-side router unusable whilst not disabling it. This results in the following behaviour:

1. Link gets clicked
2. URL in address bar changes
3. Content of page stays unchanged

Setting `export const hydrate = false` on a page does interestingly not break the router.

### Reproduction

[🚩 Link to a demo](https://stackblitz.com/edit/sveltejs-kit-template-default-q36fqu?file=svelte.config.js)

1. Start the dev server and click on the links to observe the broken router
2. Comment the `browser: { hydrate: false },` line in `svelte.config.js` and restart the dev server to see the router working again.

### Logs

When clicking on link (browser console):
```
[HMR][Svelte] Unrecoverable HMR error in <Root>: next update will trigger a full reload
Uncaught (in promise) Error: options.hydrate only works if the component was compiled with the `hydratable: true` option
    at Object.claim [as l] (root.svelte? [sm]:50:13)
    at init (index.mjs:1883:40)
    at new Root (root.svelte? [sm]:16:25)
    at createProxiedComponent (svelte-hooks.js:341:9)
    at new ProxyComponent (proxy.js:242:7)
    at new Proxy<Root> (proxy.js:349:11)
    at initialize (start.js:702:10)
    at update (start.js:631:4)
    at async navigate (start.js:1241:3)
```
![image](https://user-images.githubusercontent.com/79395582/158990748-6225bfe9-563e-4e79-a6a6-9ce04d743802.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 10.11 GB / 15.93 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.36)
  npmPackages:
    @sveltejs/adapter-netlify: ^1.0.0-next.51 => 1.0.0-next.51
    @sveltejs/kit: next => 1.0.0-next.299
    svelte: ^3.46.4 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
The first problem is that `hydrate: true` is unconditionally set in the code (where `root.svelte` is generated). Setting this to `false` for testing purposes reveals a different problem then: If a link is followed, the page is duplicated below the original page and the original page is "frozen" (no links are followed, that happens in the duplicated page below). If then the router is also disabled through `router: false` it works as expected. But users could enable the router or the hydration on a page-by-page basis (like the about page in the example app during dev) which makes this buggy behavior reoccur.

**Comment by benmccann** [comment]
Yeah, I think I'd make `hydrate: false` and `router: true` throw an error or make `hydrate: false` disable the router or something along those lines.

**Comment by FarhanAliRaza** [comment]
Uncaught (in promise) Error: options.hydrate only works if the component was compiled with the `hydratable: true` option
My app was working fine. Then I updated sveltekit to the latest version now it is giving this error

**Comment by VirgileD** [comment]
@FarhanAliRaza I'm really stuck at this point, did you find something relevant about this error?

**Comment by jessmartin** [comment]
I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:

```js
import preprocess from "svelte-preprocess";

const config = {
  preprocess: [
    preprocess({
      postcss: true,
    }),
  ],
}
```

The correct configuration is as so:
```js
import adapter from "@sveltejs/adapter-auto";
import preprocess from "svelte-preprocess";

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter()
	},
	preprocess: [
		preprocess({
			postcss: true,
		}),
	],
};

export default config;
```

**Comment by weirdwir3d** [comment]
> I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> 
> ```js
> import preprocess from "svelte-preprocess";
> 
> const config = {
>   preprocess: [
>     preprocess({
>       postcss: true,
>     }),
>   ],
> }
> ```
> 
> The correct configuration is as so:
> 
> ```js
> import adapter from "@sveltejs/adapter-auto";
> import preprocess from "svelte-preprocess";
> 
> /** @type {import('@sveltejs/kit').Config} */
> const config = {
> 	kit: {
> 		adapter: adapter()
> 	},
> 	preprocess: [
> 		preprocess({
> 			postcss: true,
> 		}),
> 	],
> };
> 
> export default config;
> ```

still unable to fix the issue, ano other ideas?
Additionally, I get this error as well:

<img width="499" alt="Screenshot 2023-01-18 at 11 57 16" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">

Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

I can help, suck dick then you dont have to fix the issue

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

you dont need help you need 🍆 then your all set

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

I am everywhere in places where you dont expect

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

I will always be in places where you dont expect

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

why should we help you? are you retarded?

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

bring them back

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

you know you did something wrong

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

Haarlem

**Comment by Zigarettenbrenner** [comment]
> > I ran into this by following the TailwindCSS docs, which instruct you to configure `svelte.config.js` thusly:
> > ```js
> > import preprocess from "svelte-preprocess";
> > 
> > const config = {
> >   preprocess: [
> >     preprocess({
> >       postcss: true,
> >     }),
> >   ],
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The correct configuration is as so:
> > ```js
> > import adapter from "@sveltejs/adapter-auto";
> > import preprocess from "svelte-preprocess";
> > 
> > /** @type {import('@sveltejs/kit').Config} */
> > const config = {
> > 	kit: {
> > 		adapter: adapter()
> > 	},
> > 	preprocess: [
> > 		preprocess({
> > 			postcss: true,
> > 		}),
> > 	],
> > };
> > 
> > export default config;
> > ```
> 
> still unable to fix the issue, ano other ideas? Additionally, I get this error as well:
> 
> <img alt="Screenshot 2023-01-18 at 11 57 16" width="499" src="https://user-images.githubusercontent.com/63656528/213154117-ddce30fc-e8fd-486d-8c2f-a038773a1886.png">
> 
> Can someone please help? I edited the song file in the ways suggested above but it did not fix the issue

Haarlem Amstelveen
