### ISSUE TITLE
adapter-auto fails to deploy to Cloudflare Pages

### ISSUE THREAD

**Issue by thinkloop** [sveltejs/kit#4389]
### Describe the bug

Similar to #4107 I am unable to build on Cloudflare with error `Output directory "build" not found`:

> 01:14:49.521	> Using @sveltejs/adapter-cloudflare
> 01:14:49.552	  ✔ done
> 01:14:49.578	Finished
> 01:14:49.578	Note: No functions dir at /functions found. Skipping.
> 01:14:49.578	Validating asset output directory
> 01:14:49.578	Error: Output directory "build" not found.

### Reproduction

**package.json:**

```
devDependencies": {
   "@sveltejs/adapter-auto": "^1.0.0-next.33",
   "@sveltejs/kit": "next",
   "eslint": "^8.11.0",
   "eslint-config-prettier": "^8.5.0",
   "eslint-plugin-svelte3": "^3.4.1",
   "less": "^4.1.2",
   "prettier": "~2.6.0",
   "prettier-plugin-svelte": "^2.6.0",
   "svelte": "^3.46.4",
   "svelte-preprocess": "^4.10.4",
   "svelte2tsx": "^0.5.6",
   "typescript": "^4.6.2"
 }
```

**svelte.config.js**

```
/** @type {import('@sveltejs/kit').Config} */

import adapterAuto from '@sveltejs/adapter-auto';
import sveltePreprocess from 'svelte-preprocess';

const config = {
	preprocess: sveltePreprocess(),
	kit: {
		adapter: adapterAuto()
	}
};

export default config;
```

**Cloudflare build settings:**

> Build command: npm run build
> Build output directory: /build
> Root directory: /
> Environment variables:
>      NODE_VERSION | 14.17.3

![image](https://user-images.githubusercontent.com/118814/159111959-b3e18efd-5154-47f9-b418-d832c32804e1.png)

### System Info

```shell
Cloudflare
```

### Severity

blocking all usage of SvelteKit

**Comment by babichjacob** [comment]
What happens when you use the correct Deployment settings? https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare#deployment (specifically the differing `Build output directory`)

**Comment by thinkloop** [comment]
It works 🥲 thank you very much @babichjacob
