### ISSUE TITLE
__error generated types should use `ErrorLoad` instead of `Load`.

### ISSUE THREAD

**Issue by f-elix** [sveltejs/kit#4398]
### Describe the bug

The types generated at `./.sveltekit/types/src/routes/__error.d.ts` by Sveltekit use the generic `Load` function type instead of the `ErrorLoad` type, which causes errors to show up when using the `error` and `status` parameters in the function.

### Reproduction

https://github.com/f-elix/sveltekit-generated-types-error

You can open this repo in vscode to see the errors in `__error.svelte`. `npm run check` will also display the errors in the terminal.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 26.30 GB / 39.76 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33
    @sveltejs/kit: next => 1.0.0-next.301
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

### Additional Information

I can use the `ErrorLoad` type provided by Sveltekit to work around that.

**Comment by Rich-Harris** [comment]
Relatedly, I sort of wonder if we shouldn't just have a single `Load` type where `status` and `error` are both `null` in the default case. (This thinking also prompted by the addition of page endpoints, which mean that a non-error `load` can be called even if the status code is a 4xx/5xx, even though we're not currently using it — #4328)

**Comment by Rich-Harris** [comment]
Going to close this in favour of #4461, where we're plotting the removal of `ErrorLoad` altogether
