### ISSUE TITLE
manifest.json find_deps fails to load the file when symlinks are involved

### ISSUE THREAD

**Issue by awderh** [sveltejs/kit#4400]
### Describe the bug

Since client-side `find_deps` does a string based get on the manifest file, `symlinks` may not be properly handled if the working directory is different. Since this utility is within Svelte's codebase, this should be fixed here. 

### Reproduction

If I had the project in: `C:\projects\awd-portfolio` where `C:\projects` links to `C:\some\other\path\projects`, then the client-side `manifest.json` would have `../../some/other/path/projects/awd-portfolio` instead of `../../projects/awd-portfolio`

This will cause [`find_deps`](https://github.com/sveltejs/kit/blame/fac284475decb1531ee9c2413f58020256f719d2/packages/kit/src/core/build/utils.js#L31) to not find the correct file if my current directory uses the symlink path, since `manifest` uses a different path
```js
/**
 * @param {string} file
 * @param {import('vite').Manifest} manifest
 * @param {Set<string>} css
 * @param {Set<string>} js
 */
export function find_deps(file, manifest, js, css) {
	const chunk = manifest[file];

	if (js.has(chunk.file)) return;
	js.add(chunk.file);

	if (chunk.css) {
		chunk.css.forEach((file) => css.add(file));
	}

	if (chunk.imports) {
		chunk.imports.forEach((file) => find_deps(file, manifest, js, css));
	}
}
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz  
    Memory: 29.96 GB / 47.94 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE        
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.74
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.46)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33
    @sveltejs/kit: next => 1.0.0-next.301
    svelte: ^3.44.0 => 3.46.4
```

### Severity

annoyance

### Additional Information

Easy fix if using absolute path comparisons (with fully resolved symlinks) instead of a string comparison. Also, adding an error-handler for `chunk` being null/undefined would be good. I can try to submit a patch for this if you'd like

**Comment by Rich-Harris** [comment]
A patch (with tests! :) would be great, thank you

**Comment by eltigerchino** [comment]
closing this as not planned since the method has since been refactored, causing this issue to be stale
https://github.com/sveltejs/kit/blob/d94a854f9f5e8ed474c97cf7d51f2e0db3fe16ac/packages/kit/src/exports/vite/dev/index.js#L578-L614
