### ISSUE TITLE
For a svelte package index.js group imports don't work anymore

### ISSUE THREAD

**Issue by 24jr** [sveltejs/kit#4401]
### Describe the bug

https://kit.svelte.dev/docs/packaging#publishing

This used to work before update a few weeks ago and stopped and still doesnt work
```
import { Foo } from 'your-library';
```
but this does
```
import Foo from 'your-library/Foo.svelte';
```
but easier to use first syntax for multiple imports

Don't believe much of anything changed except updating so I think the issue has to do with something in an update

### Reproduction

make svelte package
```
npm run package
publish ./package --access public
```
import into another sveltekit project

### System Info

```shell
Latest svelte
```

### Severity

annoyance

### Additional Information

Alternative is fine but at some point would be nice

**Comment by 24jr** [comment]
this may have to do with other issue I am having https://github.com/sveltejs/kit/issues/3473

**Comment by ignatiusmb** [comment]
Please see https://github.com/sveltejs/kit/issues/2263#issuecomment-903216564 or follow the issue template and provide a proper reproduction.

**Comment by 24jr** [comment]
@ignatiusmb That link just shows u telling someone the basic usage of this which I had already done and as I said worked fine until updating to newer version but sure just close the issue that solves the problem right...

**Comment by ignatiusmb** [comment]
From the issue template: 

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by 24jr** [comment]
@ignatiusmb Ok well you are right that I am not setting up all that for someone and it would require whoever fixes these things to make an nmp package and idk how I make that easy for them and also don't desire to spend that much time doing all that as I am busy so if simply bringing up the valid issue without all that isnt good enough then I understand and will wait until one day someone else finds the problem and desires to create issue to your standard. I guess its a tradeoff of work to issue fixer or issue creator and you are right I am putting more on the fixer but thats just where I'm at
