### ISSUE TITLE
Static adapter build --> I can't refresh pages without adding ".html" to the URL.

### ISSUE THREAD

**Issue by dschalk** [sveltejs/kit#4404]
### Describe the bug

I uploaded my SveltKit build to my DigitalOcean droplet.
https://schalk.net loads fine. I can click links to get to https://schalk.net/Functions/monads but I get a "file not found" message when I try to refresh the page. After appending ".html" to the URL, the page refreshes normally. Again, I can refresh https://schalk.net/Functions/monads.html but without the ".html", I get the "file not found" message.

When I enter "yarn run preview" on the same build I uploaded to schalk.net, this does not occur. localhost:3000/Functions/monads refreshes without the ".html".  In Build on my desktop, I opened Functions and saw monads.html. "Functions/monad.html" is also in my DigitalOcean droplet. All would be well If only the ".html" would stay on the files.  

I work in Debian 11.2 on my desktop and in the server. A Debian adapter would be nice, but I like the static adapter idea. It almost works.

### Reproduction

https://github.com/dschalk/site5

### System Info

```shell
Debian 11.2 on the desktop and in the DigitalOcean droplet
Chrome and Firefox
SvelteKit
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I can't publicize my work without abandoning my beloved SvelteKit. I love what you are doing

**Comment by Conduitry** [comment]
See https://github.com/sveltejs/kit/tree/master/packages/adapter-static#usage - in particular the part about the `trailingSlash` setting.

Running "preview" serves your app without any adapters, so you're not actually testing the same build as you are deploying.
