### ISSUE TITLE
Fix manifest not being JSON.parse-able (missing "")

### ISSUE THREAD

**Issue by isaac-mcfadyen** [sveltejs/kit#4405]
### Describe the problem

In most adapters, the builder generates a list of assets, entry files, and routes using `builder.generateManifest`.

However, the generated dictionary (it's a string type, but in dictionary format) is not JSON spec-compliant; it can't be `JSON.parse`d or otherwise read without exec because the dictionary keys are missing double quotation marks (`"`).

This is a problem because this manifest can be used for other things, such as generating a `_headers` file for Cloudflare to use Server Push or parsing entry files for further bundling in adapters.

### Describe the proposed solution

The most clear solution, in my mind, is to add double quotes (`"`) around each dictionary key.

This is still valid Javascript so it won't break scripts that inject it as-is into JS files. This solution would allow parsing using standard functions such as `JSON.parse`

### Alternatives considered

An alternative could be to not change this and parse using `exec` etc. However, this is much easier to break than spec-compliant `JSON.parse` and doesn't function in some environments.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
The manifest isn't JSON-serializable _period_ — it contains dynamic imports, among other things. Can you elaborate on exactly what you're trying to do?

**Comment by isaac-mcfadyen** [comment]
Mostly to generate Link headers for using with technologies such as Cloudflare's Early Hints (generated automatically from Link headers). Because the assets are dynamically named there's no easy way to predict filenames ahead of time.

**Comment by Rich-Harris** [comment]
At what stage are you generating these headers — in a custom adapter, or in `handle`, or elsewhere? The asset list is already available to adapters (from the generated manifest at runtime, and from the filesystem at build time, albeit hackily); if it needs to be available elsewhere then it can probably be arranged. Though I'm curious about which assets you're including in those headers, specifically?

**Comment by isaac-mcfadyen** [comment]
I was planning to add them via the adapter itself (that's why I was running into this issue with being unable to parse the manifest inside the adapter). I was unaware that there was another way to refer to those assets; are you referring to using the manifest itself somehow or via another method?

As for which assets I was planning on using Early Hints for, plugins such as `vite-imagetools` bundle the images (dynamically generated, random filenames so I can't predict) themselves into the `assets` key inside the manifest. I'm totally open to handling these inside the `handle` hook or elsewhere somehow, just thought the adapter would be the easiest. 🙂

**Comment by Rich-Harris** [comment]
Actually, I misspoke — I don't think the generated assets are currently exposed via the manifest that's available to adapter code. I was thinking of stuff like this: https://github.com/sveltejs/kit/blob/2ce93d6f4bba58011aee63c6702848945c40b7c5/packages/adapter-cloudflare/src/worker.js#L43-L49

How are you deciding which assets get `Link` headers for a given page?

**Comment by isaac-mcfadyen** [comment]
I was planning to based on extension (so .jpeg, .jpg, .png, etc) but I guess that wouldn't ensure that it's scoped to the current page (even if I tried directly in the adapter it would grab all the assets, not just the current page's assets).

In my mind one solution would be returning Link headers in the GET inside a Shadow Endpoint, but that's again running into the issue of filenames being dynamically generated... except that `vite-imagetools` converts the imports to the URLs at build-time so it might allow returning inside a `load` function, which I didn't think of before.

Might not be possible for all tools, but this does seem like a niche use-case. In that case, free to close this issue 🙂

**Comment by Rich-Harris** [comment]
Yeah, it sounds like this is probably best solved in userland, so I'll close this. Generally speaking you can't know which assets to push until you've actually rendered the page, and I doubt SvelteKit could generate that list in a way that improved performance universally (I haven't used server push, but my understanding was that it [didn't work very well in the wild](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1) because it's easy to misuse bandwidth; Early Hints seems more promising but only has so much value when the HTML is already generated).

You could probably do something grotesque like this, if it improves performance:

```js
export async function handle({ event, resolve }) {
  const links = [];
  const response = await resolve(event, {
    transformPage: ({ html }) => {
      find_images(html).forEach(src => {
        links.push(src);
      });
    }
  });

  links.forEach(link => {
    response.headers.append('link', ...);
  });

  return response;
}
```
