### ISSUE TITLE
adapter-static doesn't generate nested routes

### ISSUE THREAD

**Issue by aklajnert** [sveltejs/kit#4407]
### Describe the bug

I want to serve Svelte app via `nginx`. To do that, I'm using `adapter-static` to generate all the JS files.  
I'm on a framework research stage before I pick one for an upcoming project.

I've generated the SvelteKit demo app, changed the adapter and built the app. When I ran `nginx` with it I've noticed that `HOME` and `ABOUT` pages work fine, but `TODO` doesn't. I've used `trailingSlash: 'always'` as it works better on clean `nginx`, and the `TODO` page wasn't even generated.

Note, that I'm not sure if "nested routes" is a valid name for this case. By nested I mean that `todos` is not a `.svelte` file, but a directory with `index.svelte` and `index.ts`.

The `src` directory content:
```
src
├── app.css
├── app.d.ts
├── app.html
├── hooks.ts
├── lib
│   ├── Counter.svelte
│   ├── form.ts
│   └── header
│       ├── Header.svelte
│       └── svelte-logo.svg
└── routes
    ├── __layout.svelte
    ├── about.svelte
    ├── index.svelte
    └── todos
        ├── _api.ts
        ├── index.svelte
        └── index.ts
```

Here's the generated build directory structure:
```
build
├── _app
│   ├── assets
│   │   ├── fira-mono-all-400-normal-1e3b098c.woff
│   │   ├── fira-mono-cyrillic-400-normal-c7d433fd.woff2
│   │   ├── fira-mono-cyrillic-ext-400-normal-3df7909e.woff2
│   │   ├── fira-mono-greek-400-normal-a8be01ce.woff2
│   │   ├── fira-mono-greek-ext-400-normal-9e2fe623.woff2
│   │   ├── fira-mono-latin-400-normal-e43b3538.woff2
│   │   ├── fira-mono-latin-ext-400-normal-6bfabd30.woff2
│   │   ├── pages
│   │   │   ├── __layout.svelte-15681802.css
│   │   │   ├── about.svelte-bf4528fa.css
│   │   │   ├── index.svelte-1d45bd0c.css
│   │   │   └── todos
│   │   │       └── index.svelte-a910a02d.css
│   │   └── svelte-logo-87df40b8.svg
│   ├── chunks
│   │   ├── singletons-d1fb5791.js
│   │   └── vendor-ee294e9e.js
│   ├── error.svelte-6f6d00da.js
│   ├── manifest.json
│   ├── pages
│   │   ├── __layout.svelte-1fdcf5b9.js
│   │   ├── about.svelte-64b29582.js
│   │   ├── index.svelte-92dd2217.js
│   │   └── todos
│   │       └── index.svelte-88591dd1.js
│   ├── start-a7acf4f2.js
│   └── version.json
├── about
│   └── index.html
├── favicon.png
├── index.html
├── robots.txt
├── svelte-welcome.png
└── svelte-welcome.webp
```

Without `trailingSlash: 'always'` the structure is very similar, except `about` being a file instead of directory.

### Reproduction

Generate a fresh `SvelteKit demo app` with the following settings:

```
✔ Which Svelte app template? › SvelteKit demo app
✔ Use TypeScript? … Yes
✔ Add ESLint for code linting? … Yes
✔ Add Prettier for code formatting? … Yes
✔ Add Playwright for browser testing? … No
```

Install `adapter-static`:
```shell
npm i -D @sveltejs/adapter-static@next
```

Change `svelte.config.js`:
```diff
- import adapter from '@sveltejs/adapter-auto';
+ import adapter from '@sveltejs/adapter-static';
```

At this point, you can run `npm run build` to see that the generated files are insufficient to handle this application.

To see that in `nginx`, you can use the following `docker-compose.yml` file:
```yml
version: '3.3'

services:
  nginx:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - 8080:80
```

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 273.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.7.1 - /usr/local/bin/node
    npm: 8.5.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Firefox: 98.0
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33 
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.301 
    svelte: ^3.46.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Same thing happens when I use `SPA` mode.

**Comment by Conduitry** [comment]
`/todos` not being rendered is not related to it being a `/todos/index.svelte` file. As mentioned in [the adapter-static readme](https://github.com/sveltejs/kit/tree/master/packages/adapter-static) and in the warning message you see while building the app, you need to set `kit.prerender.default` to `true` to tell the adapter to prerender (and save) all pages. SvelteKit isn't prerendering the todos page by default because it can see that it's dynamic. But the todos page will also not work properly when using the static adapter anyway, because it involves dynamically rendered server-side content.

**Comment by aklajnert** [comment]
Oh, that makes perfect sense. Thank you.
