### ISSUE TITLE
Commented code (string interpolation) seems to be evaluated

### ISSUE THREAD

**Issue by einarpersson** [sveltejs/kit#4411]
### Describe the bug

For reason that is not really relevant, I was experimenting with injecting CSS via javascript in a somewhat unconventional way :) 

However, when doing so I stumbled upon a situation that surely seems to be a breach of some kind of contract. **I was able to crash my app by writing things in comments!**

````html
<script>
	// <style>`${foo}`</style>
</script>

<h1>Hello. Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<style>
</style>
````

Result:
![image](https://user-images.githubusercontent.com/6043691/159264516-123bf25e-0b83-4d4b-b801-aa2bf196b401.png)

If I remove the string interpolation the error goes away!

**Note:**

I understand that it seems very weird, why would I even have style-tag in the script-section? Well, I was trying to programmatically create some css to be added to the file, which couldn't be done using custom CSS properties or styling the elements directly (using polyfill [pagedjs](https://pagedjs.org/). I was able to accomplish what I wanted, but I had to put it in another typescript file and import it. If I created a string interpolation with `<style>` somewhere in the `<script>` tag (even if it's just a string) it seems to crash.

### Reproduction

[repo](https://github.com/einarpersson/sveltekit-bug-reproduction)

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 22.56 GB / 24.59 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33
    @sveltejs/kit: next => 1.0.0-next.301
    svelte: ^3.44.0 => 3.46.4
```
```


### Severity

annoyance

### Additional Information

_No response_

**Comment by Conduitry** [comment]
Preprocessors work by simple string replacements before the components are parsed. The `svelte-preprocess` library sees the `<style>...</style>` in the component and attempts to process its contents, which PostCSS rightfully balks at. You'll need to escape characters or split strings (`'<sty' + 'le>'` etc.) to prevent the preprocessor from trying to process the `<style>` tag.
