### ISSUE TITLE
OPEN REDIRECT BUG 

### ISSUE THREAD

**Issue by Amanzv** [sveltejs/kit#4416]
### Describe the bug

Hey team,
I reported an open redirect bug to kenshi project & they said the bug resides in your application because they just cloned yours the vulnerable url of kenshi is https://kenshi.io//example.com/ which will be redirected to example.com so the case here is the 2 slashes can be used to bypass the protection & can make manipulative redirection to any application which can be controlled by an attacker so kindly see the code of your application & make sure you fix this because every project who cloned your will be vulnerable to this 

Thanks
Best,
Amannoobda

### Reproduction

.

### Logs

```shell
.
```

### System Info

```shell
.
```

### Severity

serious, but I can work around it

### Additional Information

.

**Comment by Conduitry** [comment]
This is a duplicate of #2515 which was just minutes ago fixed via #4414, but hasn't been released yet.
