### ISSUE TITLE
`load` runs before `beforeNavigate` finishes

### ISSUE THREAD

**Issue by Addeuz** [sveltejs/kit#4421]
### Describe the problem

I'm not sure if this is a bug or feature request. But since I think the way these two functions are implemented I assume it is more of a feature request.

The way we use `beforeNavigate` and `load` is that we save our data to our back end when `beforeNavigate` runs. And then (usually) load the data from the back end in `load`. Sometime we want to load data that depends on what was saved in `beforeNavigate`.

So lets say we navigate to a place with a normal `a` tag. And then `beforeNavigate` runs and save our data. But the issue then becomes that `load` runs before `beforeNavigate` is "complete" (i.e. the fetch request is resolved in `beforeNavigate`). So we get the old data in `load` instead of the fresh and saved date in `beforeNavigate`.

### Describe the proposed solution

What we would like is to somehow. Either in `load` or `beforeNavigate` say that we want to wait to load our data until the request is resolved in `beforeNavigate`.

### Alternatives considered

We have came up with a solution that we think might work.
Basically have a store that is sort of like a dependency tree. So lets say that we make our PUT request in `beforeNavigate`. Then we say to all fetches that gets the data that the data is now "invalid". When the PUT request resolves we say that there is "fresh" data to get and we fetch.

With this solution we would have to move all of our GET requests that depend on some data in `onMount` or even `afterUpdate`. So we can listen on the dependency tree store if the GET request could be done (the PUT request has resolved). And that would be quite a lot of extra work. Putting skeletons and stuff when the data can't be fetched 

### Importance

would make my life easier

### Additional Information

I have made this repo where I fetch in both `beforeNavigate` and `load` where we can see that the `load` fetch runs before the `beforeNavigate` fetch finishes:
https://github.com/Addeuz/load-issues

Picture from network tab:
![image](https://user-images.githubusercontent.com/12641358/159531329-1841f893-be76-4817-8714-b224362d7081.png)

**Comment by Rich-Harris** [comment]
This is expected behaviour — `beforeNavigate` is synchronous by design, as it's important to eliminate opportunities for navigation to be delayed. It also needs to be synchronous for `cancel` to work when unloading a page.

You _could_ get the desired behaviour like so...

```js
beforeNavigate(async ({ to, cancel }) => {
  if (has_unsaved_changes) {
    cancel();
    await save();
    goto(to.href);
  }
});
```

...though it would be a little unconventional, and users might be unclear on what's happening — I'd generally recommend having an explicit `save` button, perhaps with background auto-save.

**Comment by Addeuz** [comment]
Thanks for the answer Rich, we figured that it was working as intended.

We do have some auto saving in different routes. And the reason for saving in `beforeNavigate` is mainly done to make sure that we save the latest state.

We have thought about adding save buttons but our client doesn't want them.. But it certainly would make a developers life easier.

We think we can make your suggestion work, basically almost have like a dependency tree. So we only cancel the request if we are going to a route that depends on the data we are saving.. And hopefully it won't feel super intrusive..

**Comment by johnnysprinkles** [comment]
I'm making an "are you sure you want to abandon" changes confirmation, using the above approach, but the problem is the `goto` triggers another `beforeNavigate` so the confirmation keeps appearing. Anyone have any clever ideas of how to include some "force" boolean?

```
beforeNavigate(async ({ to, from, cancel }) => {
  if (to.routeId != 'foo' && from.routeId == 'foo' && dirty) {
    cancel();
    let ok = await confirmationService('Are you sure you want to abandon these changes?');
    if (ok) {
      go(to.href):
    }
  }
});
```

**Comment by johnnysprinkles** [comment]
Well I guess this works:

```js
let left = false;
beforeNavigate(async ({ to, from, cancel }) => {
  if (to.routeId != 'foo' && from.routeId == 'foo' && dirty && !left) {
    cancel();
    let ok = await confirmationService('Are you sure you want to abandon these changes?');
    if (ok) {
      left = true;
      goto(to.url):
    }
  }
});
```

**Comment by sj-adpro** [comment]
> Well I guess this works:
> 
> ```js
> let left = false;
> beforeNavigate(async ({ to, from, cancel }) => {
>   if (to.routeId != 'foo' && from.routeId == 'foo' && dirty && !left) {
>     cancel();
>     let ok = await confirmationService('Are you sure you want to abandon these changes?');
>     if (ok) {
>       left = true;
>       goto(to.url):
>     }
>   }
> });
> ```



Imo, this begs the question as to why `onNavigate` doesn't also pass a `cancel` option since, unlike `beforeNavigate`, it *will* hold for promises.

The following (if possible) would be a much cleaner implementation with less workaround.
```
onNavigate(async ({cancel}) => {
    if (formDirty) {
        let doNavigate = await Modal.confirm({
            ...
        });
        
        if (!doNavigate) cancel();
    }
}

<form on:change={() => formDirty = false} > ... </form>
```
