### ISSUE TITLE
adapter-node: Ability to disable compression of html response

### ISSUE THREAD

**Issue by randyridge** [sveltejs/kit#4422]
### Describe the problem

I'd like to offload gzipping html responses to something upstream, my ingress or maybe my cdn, but maintain serving up pre-compressed gz/br files.  

I believe this is the line responsible: [compression enabled](https://github.com/sveltejs/kit/blob/e338edcede1c63a880970b1f9b661c9b91c247ac/packages/adapter-node/src/index.js#L13)

### Describe the proposed solution

Allow me to configure disabling or giving further control.  Pre-compressed assets are seemingly [handled elsewhere in sirv](https://github.com/sveltejs/kit/blob/e338edcede1c63a880970b1f9b661c9b91c247ac/packages/adapter-node/src/handler.js#L35)

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
The easiest fix here would be to use a custom server: https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server

**Comment by Rich-Harris** [comment]
am open to changing the default behaviour here, but in the meantime I'll close this issue as it's easily solved with custom servers
