### ISSUE TITLE
Add Vitest to `create-svelte`

### ISSUE THREAD

**Issue by jtlapp** [sveltejs/kit#4423]
### Describe the problem

I have spent many hours trying to figure out the best way to do unit testing with playwright. Sometimes I make progress, sometimes I get stuck. Right now I've got basic tests working but I'm stuck on mocking dependent modules.

At one point I tried to install jest but could not get it working with SvelteKit's configuration files. I'm thinking that the problem was supporting TypeScript. (That was two weeks ago, so I don't remember the details.)

Apparently, [playwright is not really designed for unit testing](https://github.com/microsoft/playwright/issues/8076), which probably explains Google's inability to pull up anything helpful.

So I'm here feeling displeased with SvelteKit. Something about the default installation is incompatible with jest or with jest + TypeScript. If some solutions are incompatible, what does SvelteKit recommend?

### Describe the proposed solution

I'd like to see something in the docs on doing unit testing -- running purely in node.js -- and maybe even an example unit test. I need a solution that supports mocking dependencies.

I'm not sure whether it's SvelteKit's support for unit testing that's incomplete or SvelteKit's support for TypeScript, but it looks like one of these to me.

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment]
This may help: https://github.com/rossyman/svelte-add-jest

**Comment by jtlapp** [comment]
Wow! That did it! I'm surprised I hadn't come across this before. Thank you so much!

There is one oddity: it completely bumped the playwright `test` script:

![Screen Shot 2022-03-22 at 13 43 16](https://user-images.githubusercontent.com/138133/159553411-a06c16f9-2021-45a8-87e6-343e4240c1fa.png)

But I am still able to run playwright tests from the command line, so I'll be able to add playwright back in.

**Comment by jtlapp** [comment]
Except now I'm off trying to figure out why vite is pulling in `.spec.ts` files, despite `tsconfig.json` containing `"exclude": ["src/**/*.spec.ts"]`:

```
1:59:06 PM [vite] Error when evaluating SSR module /Users/joe/repos/cavesite/src/routes/index.spec.ts:
ReferenceError: describe is not defined
```

**Comment by jtlapp** [comment]
But I'm having import problems. It's not pulling in postgres. These are unit tests I had working under playwright, converted to jest.

![capture1](https://user-images.githubusercontent.com/138133/159572135-f9d0c289-8baf-4a11-bf5d-2309d674a9ad.png)

At this point, I've probably spent a cumulative total of 8 hours trying to get unit tests working under SvelteKit. I can't keep wasting so much time. I have two things left to try:

- Try to get unit testing working under Mocha or Jasmine.
- Put all modules requiring unit tests in a separate package, and pull that package into my SvelteKit repo.

**Comment by jtlapp** [comment]
I've thought of a way to make my dependent module test-configurable so I don't have to stub it and can stick with playwright. Figuring out unit testing under SvelteKit has been such a bear.

**Comment by jtlapp** [comment]
I've finally got unit tests working with [vitest](https://vitest.dev/). It was as simple as installing the package and adding `vitest.config.js`. Nothing more to do. Everything works, including playwright tests.

**Comment by jtlapp** [comment]
Maybe the thing to do in the docs is to list the known efforts to provide svelte-kit with unit testing? Here are two:

- [svelte-add-jest](https://github.com/rossyman/svelte-add-jest) (though it installed a demo test in routes/ and wouldn't let my tests import some packages)
- [vitest-svelte-kit](https://github.com/nickbreaton/vitest-svelte-kit) (worked seamlessly with my test suite)

**Comment by jtlapp** [comment]
Another approach would be to use a monorepo and put the backend code into its own repo with its own unit testing. Unfortunately, I spent a day trying to do this, trying to resolve all the problems that arose, and ultimately decided that maybe I should ditch SvelteKit and do an SPA. I'll start a discussion about this.

**Comment by jtlapp** [comment]
I've broached a more general docs issue in discussion #4586.

**Comment by jtlapp** [comment]
The [playwright unit test runner](https://pkerschbaum.com/blog/using-playwright-to-run-unit-tests) could potentially resolve one of my problems with using svelte-kit. I would like to be able to choose my runner for unit tests, but I could live with being forced to use this one.

**Comment by benmccann** [comment]
I think we will be recommending Vitest as the preferred unit testing solution using `@sveltejs/kit/experimental/vite` (https://github.com/sveltejs/kit/issues/5184)
