### ISSUE TITLE
[create-svelte] Non TS demo app has type errors for the enhance action

### ISSUE THREAD

**Issue by gtm-nayan** [sveltejs/kit#4427]
### Describe the bug

Without Typescript declarations marking them as optional, the type of the parameters to the action is inferred as `{ pending: any; error: any; result: any; }` with all three fields required causing errors everywhere `enhance` is used in todos/index.svelte.

### Reproduction

Default create-svelte template without Typescript

### System Info

```shell
.
```

### Severity

annoyance

### Additional Information

https://discord.com/channels/457912077277855764/956030069229359154

**Comment by Rich-Harris** [comment]
closing in favour of #4428
