### ISSUE TITLE
__tests__ directories break the build

### ISSUE THREAD

**Issue by cmcculloh-kr** [sveltejs/kit#4435]
### Describe the problem

https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/create_manifest_data/index.js#L85

Keeps me from placing `__tests__` directories alongside my source files:

```
src/index.svelte
src/__tests_/index.svelte
```

### Describe the proposed solution

I have no idea why this is blocked, so I don't know the ramifications of what I'm asking for. The most brute-force method would be to just hard-code the allowance of `__tests__` directories.

Edit [line 28](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/create_manifest_data/index.js#L28) to be:

`const specials = new Set(['__layout', '__layout.reset', '__error', '__tests__']);`

### Alternatives considered

Structuring my code like this:

```
src/index.svelte
src/index.test.svelte
```

or:

```
src/index.svelte
src/_tests_/index.svelte
```

The former gets very cluttered, and the latter just doesn't match the conventions used by my team on other projects so will be another tiny little speed-bump in adoption.

### Importance

would make my life easier

### Additional Information

I'm happy to submit a PR, but didn't want to bother if it was just going to be closed.

**Comment by benmccann** [comment]
`__` prefix is disallowed because we want to have SvelteKit-specific files like `__layout.svelte` (https://kit.svelte.dev/docs/layouts)

Adding a special check to allow `__tests__` seems reasonable to me

**Comment by cormacmccarthy** [comment]
@benmccann I'm just as happy to close the PR I just issued and make another one that just changes line 28 in https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/create_manifest_data/index.js#L28 by hard-coding `__tests__` as an additional allowed special.

I just got a little carried away ;)

**Comment by benmccann** [comment]
I'll wait for the other maintainers to see what their opinions are. I tend to think we wouldn't want to allow it to be configurable as that would defeat the purpose of disallowing it

**Comment by Conduitry** [comment]
Yeah, I don't think we want this to be configurable, because otherwise people could set up things that we eventually want to ascribe some special meaning to.

I'm fine with hardcoding an exclusion for `__tests__` for now and then seeing what makes sense later if we want to expand that exclusion (which could be done as a non-breaking change).

**Comment by cormacmccarthy** [comment]
Makes sense! Feel free to accept/close whichever PR you'd like. 

#4437 
#4438

**Comment by rmunn** [comment]
As I mentioned in https://github.com/sveltejs/kit/pull/4438#issuecomment-1080403531, I'd suggest allowing `__test__` as well as `__tests__`. Rationale in that comment.
