### ISSUE TITLE
Incorrect path for dynamic routes: Server & Client mismatch

### ISSUE THREAD

**Issue by AlessioGr** [sveltejs/kit#4439]
### Describe the bug

I'm using a dynamic route, but its params are incorrect on the server (and correct on the client). Best to explain it with an example.

Relevant Code:
![image](https://user-images.githubusercontent.com/70709113/159810542-c7697ef7-acbc-4cfd-92cf-be3ab63dc981.png)

Now when opening `http://localhost:3000/sg/tests/hello` I'm getting following message on the client:
![image](https://user-images.githubusercontent.com/70709113/159810639-e453f031-e68d-4ff1-a4fa-ffc46b20b503.png)
which is correct! But on the server it's looking different:
![image](https://user-images.githubusercontent.com/70709113/159810716-c12d49e6-2d7f-4de1-9280-c15855237052.png)
As you can see, it prints out the log twice. The first one is correct, the second one is incorrect. On the client, it prints it out only once - the correct one.

### Reproduction

GitHub repo: https://github.com/AlessioGr/sveltekit-bug-report/blob/master/src/routes/%5Blocale%5D/tests/%5Bslugname%5D.svelte

Stackblitz: https://stackblitz.com/github/AlessioGr/sveltekit-bug-report?file=src%2Froutes%2F[locale]%2Ftests%2F[slugname].svelte

You can very easily reproduce it there. The relevant files are [slugname].svelte and Header.svelte.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 17.24 GB / 31.92 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.46)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33
    @sveltejs/kit: next => 1.0.0-next.303
    svelte: ^3.46.0 => 3.46.4
```

### Severity

blocking all usage of SvelteKit (I don't know how to work around it for what I'm trying to do)

**Comment by mrkishi** [comment]
This seems to be "working" as intended: the first request is for the page while the second is for the header's image.

`Header.svelte` renders an `<img src="svelte-welcome.png" />`. Note that it has a relative path which resolves to `/sg/tests/svelte-welcome.png` when loaded from `/sg/tests/anything`.

In this case you can easily solve this by using an absolute url for the image or by importing the image instead so that you get a processed url from vite.

**Comment by AlessioGr** [comment]
> This seems to be "working" as intended: the first request is for the page while the second is for the header's image.
> 
> `Header.svelte` renders an `<img src="svelte-welcome.png" />`. Note that it has a relative path which resolves to `/sg/tests/svelte-welcome.png` when loaded from `/sg/tests/anything`.
> 
> In this case you can easily solve this by using an absolute url for the image or by importing the image instead so that you get a processed url from vite.

Ah I see, thank you! Why does that request only exist on the server and not on the client, though? And isn't the load function only supposed to run once for that component - not for other requests?
Because if I do get two "legit" requests there (assuming I didn't mess up with the image imports), and I load in the post from my CMS there (via the slugname), it would try to load in data twice, which it shouldn't. Should I be doing that a different way?

**Comment by mrkishi** [comment]
The second request is only visible from the server because it doesn't happen from SvelteKit's router.

When the browser sees `<img src="/sg/tests/svelte-welcome.png"/>`, it'll try to load the image by making an http request the server by itself. This request isn't initiated by the client, so the route's `load()` is never called. Once you fix the image URL you will see only one request from both the server and the client, so you won't need to worry about loading things twice.

**Comment by AlessioGr** [comment]
> The second request is only visible from the server because it doesn't happen from SvelteKit's router.
> 
> When the browser sees `<img src="/sg/tests/svelte-welcome.png"/>`, it'll try to load the image by making an http request the server by itself. This request isn't initiated by the client, so the route's `load()` is never called. Once you fix the image URL you will see only one request from both the server and the client, so you won't need to worry about loading things twice.

Alright, thank you! Still, shouldn't that request have appeared in the `Header.svelte` instead of the `[slugname].svelte` there? Also are there any "legit" cases where the `load()` function is called twice?

**Comment by mrkishi** [comment]
`Header.svelte` is a standalone component that has no idea about SvelteKit, `load()`, client-side or server-side routing. It's simply rendering an image tag that the browser handles natively. Therefore, SvelteKit isn't responsible for the second request—it's a native image loading request and there would be no way for us to control it.

`load()` is ordinarily not called twice, but if you manually (or indirectly as in this case with an image) make a request to a route, the server _will_ handle it, regardless of origin. Even though it _looks_ like `load()` was called twice, they are two independent requests to the route.

Feel free to reach for further help on Discord, StackOverflow, or even Github Discussions. Those are better channels for questions.
