### ISSUE TITLE
Changing the value of a store in a load function results in unexpected behaviour

### ISSUE THREAD

**Issue by robertcoopercode** [sveltejs/kit#4449]
### Describe the bug

I have two pages that reference the same store (e.g. `todosStore`). Both pages will update the value in the store in their respective `load` functions. When navigating from one page to another, e.g. Home -> About, the Home page will briefly display values from that store that are meant for the About page. This can be noticeably shown when waiting 2 seconds in the About page's load function after we've update the values in the `todosStore`.

### lib/store.js
```js
import { writable } from 'svelte/store';

export const todosStore = writable([]);
```

### routes/index.svelte
```js
<script context="module">
  import { todosStore } from "$lib/store";

  export const load = () => {
    todosStore.set(["one", "two", "three"]);

    return {
      props: {},
    };
  };
</script>

<section>
  <h1>Home</h1>

  {#each $todosStore as todo}
    <p>{todo}</p>
  {/each}
</section>
```

### routes/about.svelte
```
<script context="module">
  import { todosStore } from "$lib/store";

  export const load = async () => {
    const waitTwoSeconds = async () => {
      return new Promise((resolve) => {
        setTimeout(() => {
          resolve();
        }, 2000);
      });
    };

    todosStore.set(["four", "five", "six"]);

    await waitTwoSeconds();

    return {
      props: {},
    };
  };
</script>

<section>
  <h1>About</h1>

  {#each $todosStore as todo}
    <p>{todo}</p>
  {/each}
</section>
```

Here's how this looks:

![CleanShot 2022-03-24 at 23 55 43](https://user-images.githubusercontent.com/16786990/160051353-acdee482-6375-4480-90d1-dc95eef8cb28.gif)

Now you could argue that waiting 2 seconds is not a realistic scenario in an app. However, if you're navigating from one page to another and you might need to call multiple `load` functions (e.g. `__layout.reset.svelte` load function and `about.svelte` load function) and make multiple `fetch` calls to your endpoints to gather the right data for a page. If that's the case, then it's possible for the current page to flash the content from the page you want to navigate to while waiting for all the asynchronous stuff to happen in the `load` functions.

### Reproduction

https://github.com/robertcoopercode/svelte-load-bug

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.89 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox Developer Edition: 97.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33 
    @sveltejs/kit: next => 1.0.0-next.303 
    svelte: ^3.46.0 => 3.46.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
`load` is called before the new page is displayed, and if you're updating state that the old page uses, it's going to update.

Updating a shared store like this is not the recommended way to pass state around, and it's especially dangerous on the server where all users will share a single copy of the store.

**Comment by robertcoopercode** [comment]
Ok, I guess i'm confused as to the proper usage of stores. I'm using my store as a normalized cache of my server data that i'm setting/updating in my `load` functions.

- Should I not be updating the stores in my `load` functions?
- Should I instead be updating the stores on a pages `onMount` lifecycle to avoid previous pages flashing content that is meant for the new page?
- Should I even being using stores as a normalized cache of my server data?

Apologies for not using the discord server. I haven't had any luck in getting answers on the discord server in the past, so I opted for the GitHub issue route.

Thanks a lot for your quick responses above @mdynnl and @Conduitry!
