### ISSUE TITLE
Site not properly being redirected from HTTP to HTTPS using Netlify Adapter

### ISSUE THREAD

**Issue by saturnonearth** [sveltejs/kit#4450]
### Describe the bug

On first load, and a fresh cache, which is sometimes hard to replicate as only some browsers allow this, my site is not properly being redirected from HTTP to HTTPS.

I was told by Netlify:

> It's a known limitation of Proxying (that SvelteKit uses under-the-hood) that responses by functions are not automatically redirected to HTTPS. This is browser-independent, so if you don't specify HTTPS explicitly, it would not load over HTTPS. Since those pages are rendered over functions, you can't redirect them using Netlify redirects too.

### Reproduction

Try visiting a website on iOS safari and omit the HTTPS or HTTP. It will fail the first time if the safari was closed, cache cleared.

### System Info

```shell
I've seen it happen on edge, but appears on iOS Safari mainly.
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Why aren't requests that are handled by functions redirected from HTTP to HTTPS like those that are served from a static file?

Is there anything that the handler in the Netlify adapter can look at to determine whether the incoming request is over HTTP or HTTPS?

**Comment by saturnonearth** [comment]
> Why aren't requests that are handled by functions redirected from HTTP to HTTPS like those that are served from a static file?

After another message with them, they replied, 

> Unfortunately, there's nothing for you to do here and it's a bug with Netlify. So, it can be solved from our end, but the issue has not been prioritized yet, so it's waiting to be fixed. Till then, there's no good solution unfortunately.

**Comment by Rich-Harris** [comment]
Using `_redirects` sounds like the appropriate workaround. Given that this is a problem on Netlify's end and not ours, can we close this issue?
