### ISSUE TITLE
Build fails to resolve "exports" field

### ISSUE THREAD

**Issue by gtm-nayan** [sveltejs/kit#4454]
### Describe the bug

The dependency in question is [`@fortawesome/free-solid-svg-icons`](https://unpkg.com/browse/@fortawesome/free-solid-svg-icons@6.1.1/package.json) although it might apply to others as well. It provides both CJS and ESM files and it has a exports field in the package.json linking to each. The dev mode works fine so does a [`vite build` by itself](https://stackblitz.com/edit/vitejs-vite-kjehbf).

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-4vct5r

Run `npm run build` in the terminal

### Logs

```shell
vite v2.8.6 building for production...
✓ 14 modules transformed.
.svelte-kit/output/client/_app/manifest.json                    1.15 KiB
.svelte-kit/output/client/_app/start-0bcdba7f.js                22.21 KiB / gzip: 8.36 KiB
.svelte-kit/output/client/_app/layout.svelte-a5e06bcf.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/error.svelte-27a532b4.js         1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/pages/index.svelte-a9233dfa.js   0.30 KiB / gzip: 0.23 KiB
.svelte-kit/output/client/_app/chunks/vendor-8dd2e701.js        7.84 KiB / gzip: 3.35 KiB
vite v2.8.6 building SSR bundle for production...
✓ 11 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                        1.09 KiB
.svelte-kit/output/server/index.js                             65.45 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js   0.24 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js    0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js        0.29 KiB
.svelte-kit/output/server/chunks/index-2dc61825.js             2.29 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js             0.00 KiB
file:///home/projects/sveltejs-kit-template-default-4vct5r/.svelte-kit/output/server/entries/pages/index.svelte.js:2
import { faBold } from "@fortawesome/free-solid-svg-icons";
         ^^^^^^
SyntaxError: Named export 'faBold' not found. The requested module '@fortawesome/free-solid-svg-icons' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@fortawesome/free-solid-svg-icons';
const { faBold } = pkg;

    at async respond$1 (file:///home/projects/sveltejs-kit-template-default-4vct5r/.svelte-kit/output/server/index.js:1490:13)
    at async resolve (file:///home/projects/sveltejs-kit-template-default-4vct5r/.svelte-kit/output/server/index.js:1868:105)
    at async respond (file:///home/projects/sveltejs-kit-template-default-4vct5r/.svelte-kit/output/server/index.js:1824:22)
    at async visit (file:///home/projects/sveltejs-kit-template-default-4vct5r/node_modules/@sveltejs/kit/dist/chunks/index2.js:1091:20)
> 500 /
    at eval (file:///home/projects/sveltejs-kit-template-default-4vct5r/node_modules/@sveltejs/kit/dist/chunks/index2.js:990:11)
    at save (file:///home/projects/sveltejs-kit-template-default-4vct5r/node_modules/@sveltejs/kit/dist/chunks/index2.js:1210:4)
    at visit (file:///home/projects/sveltejs-kit-template-default-4vct5r/node_modules/@sveltejs/kit/dist/chunks/index2.js:1101:3)
```

### System Info

```shell
-
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment]
I don't think that Vite is failing to resolve the `exports` field. Rather it's that you need to reference it in another manner as indicated by the error message. The tricky thing is that Vite will use ESM in the browser, but may use CJS on the server and these need to be referenced different ways.

I'm not entirely sure there's any bug here or what we could change. I use `svelte-awesome` in my own project which works just fine, so you might want to try giving that a go.

You may also find it helpful to put `experimental: { prebundleSvelteLibraries: true }` at the root of your Svelte config when using icon libraries for better performance: https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md#prebundlesveltelibraries

**Comment by bluwy** [comment]
The error seems to be coming in the adapter stage which runs node over it, and it looks like `@fortawesome/free-solid-svg-icons` [isn't properly exporting](https://cdn.jsdelivr.net/npm/@fortawesome/free-solid-svg-icons@6.1.1/package.json) ESM files as `.mjs`. So I think this is a packaging issue in general.

**Comment by gtm-nayan** [comment]
@bluwy Shouldn't the conditional exports in the package.json eliminate the need for the `.mjs` extension?
I'm more surprised by the discrepancy between build mode and dev mode tho.

**Comment by bluwy** [comment]
Perhaps Vite was handling well in dev mode for cases like this, but Node is more stricter and would requite the `.mjs` extension. The reason is due to how Node determine what is an ESM file, which is only:

1. `.mjs` extension for ESM explicitly.
2. `.js` with `type: "module"` in the nearest `package.json`.

**Comment by gtm-nayan** [comment]
[v5.15.4](https://cdn.jsdelivr.net/npm/@fortawesome/free-solid-svg-icons@5/package.json) of the package which was lacking the exports field and instead used `"main"/"module"` [seems to be working fine](https://stackblitz.com/edit/sveltejs-kit-template-default-wcetkm). That version doesn't use the `.mjs` extension either so it working is also surprising.

I'll workaround it by downgrading for now, but it might not be applicable for all packages.

**Comment by Rich-Harris** [comment]
As noted, this is a bug in `@fortawesome/free-solid-svg-icons` — the `index.es.js` should become `index.mjs` and the `pkg.exports` should be updated accordingly.

Ideally, each of the modules inside the package would also get ESM versions, i.e. a `faBold.mjs` alongside `faBold.js` with the corresponding update to `pkg.exports`...

```diff
-"./*": "./*.js"
+"./*": {
+  "import": "./*.mjs",
+  "require": "./*.js",
+  "default": "./*.js"
+}
```

...or better yet, add `"type": "module"` and use `.js` as the default and `.cjs` as the exception. But that's not my business. (I _do_ recommend opening an issue or PR on the repo though!)

Happily, due to the basic static analysis Node performs on CommonJS modules when you import them, you _can_ used named imports with the individual modules:

```diff
-import { faBold } from '@fortawesome/free-solid-svg-icons';
+import { faBold } from '@fortawesome/free-solid-svg-icons/faBold';
```

The other workaround is to ensure that the imports are inlined into the build created by Vite:

```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // ...

    vite: {
      ssr: {
        noExternal: ['@fortawesome/free-solid-svg-icons']
      }
    }
  }
};
```

**Comment by benmccann** [comment]
I sent a fix for the FontAwesome issue earlier this week: https://github.com/FortAwesome/Font-Awesome/pull/19041

**Comment by adam-coster** [comment]
I ran into this same issue. I've solved it in the interim by:

- Editing the local `package.json` for each `@fortawesome/whatever` package to have `"type": "module"` so that it is always treated as ESM
- Using [patch-package](https://www.npmjs.com/package/patch-package) to ensure that my local change gets applied after installing those modules

For example, I updated `node_modules/@fortawesome/free-brands-svg-icons/package.json` and then ran `npx patch-package @fortawesome/free-brands-svg-icons  --exclude 'none'`

**Comment by michaelusantiago** [comment]
> As noted, this is a bug in `@fortawesome/free-solid-svg-icons` — the `index.es.js` should become `index.mjs` and the `pkg.exports` should be updated accordingly.
> 
> Ideally, each of the modules inside the package would also get ESM versions, i.e. a `faBold.mjs` alongside `faBold.js` with the corresponding update to `pkg.exports`...
> 
> ```diff
> -"./*": "./*.js"
> +"./*": {
> +  "import": "./*.mjs",
> +  "require": "./*.js",
> +  "default": "./*.js"
> +}
> ```
> 
> ...or better yet, add `"type": "module"` and use `.js` as the default and `.cjs` as the exception. But that's not my business. (I _do_ recommend opening an issue or PR on the repo though!)
> 
> Happily, due to the basic static analysis Node performs on CommonJS modules when you import them, you _can_ used named imports with the individual modules:
> 
> ```diff
> -import { faBold } from '@fortawesome/free-solid-svg-icons';
> +import { faBold } from '@fortawesome/free-solid-svg-icons/faBold';
> ```
> 
> The other workaround is to ensure that the imports are inlined into the build created by Vite:
> 
> ```js
> /** @type {import('@sveltejs/kit').Config} */
> const config = {
>   kit: {
>     // ...
> 
>     vite: {
>       ssr: {
>         noExternal: ['@fortawesome/free-solid-svg-icons']
>       }
>     }
>   }
> };
> ```

this workaround works at the moment. Though on previous vite version I don't get this breaking build error. Vite 2.9.x. The later solution solved my issue, I'm at vite@latest. It can now successfully build. However I didn't put the code on `svelte.config.js` but rather on `vite.config.js.` like this
```js
/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()],
	server: { port: 3000 },
	ssr: {
		noExternal: ['@fortawesome/free-solid-svg-icons']
	}
};
```
