### ISSUE TITLE
Lighthouse performance test fails

### ISSUE THREAD

**Issue by raccodee** [sveltejs/kit#4457]
### Describe the bug

Hi, I have been noticing that on the pages I build with Sveltekit the Lighthouse performance test is not working. It always shows the error NO_FCP (First Content Paint).

At first I thought it could be my fault for using lazy loading in some sections of the page (https://raccode.dev) but in others I don't do it and it keeps happening (https://mmabogada.com).

In both I create a small delay in the rendering to show the page with a fade in but that has never given me problems using other frameworks or creating static web pages in a vanilla way. Both use prerender.

Is this a known problem?
Thanks in advance.

### Reproduction

Go to pagespeed insights: https://pagespeed.web.dev/report?url=https%3A%2F%2Fmmabogada.com%2F
Run analyze.
The page shows that couldn't found any data.

Also happens when running Lighthouse locally with the links provided at the description.

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 234.63 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Safari: 15.3
```

### Severity

annoyance

**Comment by Mlocik97** [comment]
can't reproduce with any of my Svelte projects.

**Comment by benmccann** [comment]
I cannot reproduce on my SvelteKit projects either. This seems likely to be an issue particular to your specific project. We would need more info showing that there's actually a bug caused by SvelteKit here

**Comment by sam-the-programmer** [comment]
I have this same problem
