### ISSUE TITLE
window bind:scrollY not working

### ISSUE THREAD

**Issue by jaads** [sveltejs/kit#4465]
### Describe the bug

I'm trying to bind the scrollY value like shown in the tutorials solution: https://svelte.dev/tutorial/svelte-window-bindings

But the variable to which I bind the scrollY value, does not change on scroll. The code I used is shown below.

### Reproduction

Make a svelte route component with the following code:

```
<script>
  let y;
  $: console.log(y);
</script>

<svelte:window bind:scrollY={y}/>

<div style="height: 300rem;" class="mt-64">{y}</div>
``` 

The displayed `y`does not change as expected.

### System Info

```shell
  System:
    OS: Linux 5.16 undefined
    CPU: (4) x64 Intel(R) Core(TM) i3-6100T CPU @ 3.20GHz
    Memory: 21.62 GB / 31.24 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chromium: 99.0.4844.84
    Firefox: 98.0.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/kit: ^1.0.0-next.303 => 1.0.0-next.303 
    svelte: ^3.46.4 => 3.46.4 
```

### Severity

annoyance

**Comment by geoffrich** [comment]
I cannot reproduce this in [StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-g6wwpi?file=src/routes/index.svelte) or the Svelte REPL. Please provide a [reproduction in StackBlitz](https://sveltekit.new/) or in a GitHub repo, or the issue will be closed.

**Comment by jaads** [comment]
I figured it out. 'm using a CSS framework and this causes the problem.

**Comment by N00nDay** [comment]
> I figured it out. 'm using a CSS framework and this causes the problem.

Can you elaborate on this? I am running into an issue where this is randomly working and not working and I am curious if it is the same issue.

**Comment by jaads** [comment]
I was using the [Drawer component](https://daisyui.com/components/drawer/) from DaisyUI. This caused the problem. To solve this, I had to bind the div with the `drawer-content` to get the information I was looking for. 

```javascript
  let drawercontent;
```
```html
<div
      class="drawer-content"
      bind:this={drawercontent}
      on:scroll={parseContentScroll}
>
```

**Comment by a-r-i-e-l** [comment]
I was having the same issue than @jaads
thanks for the tip :)

I'll add here a bit more info about how to get the scorll position then

either

```.ts
<div class="drawer-content flex flex-col"
  on:scroll={(event) => {
    console.log(event.currentTarget.scrollTop) // 👈
  }}
>
  <slot />
</div>
```

or

```.ts
<script lang="ts">
  let drawerContent: HTMLDivElement

  const scrollY = () => {
    console.log(drawerContent.scrollTop)
  }
</script>

<div class="drawer-content flex flex-col" bind:this={drawerContent} on:scroll={scrollY}>
  <slot />
</div>
```

**Comment by sinbino** [comment]
Anyway, <svelte:window bind:scrollY={y}/> doesn't seem to work if body has height: 100% set

**Comment by w3rafu** [comment]
> Anyway, <svelte:window bind:scrollY={y}/> doesn't seem to work if body has height: 100% set

Was breaking my head with this, thank you.
