### ISSUE TITLE
CSS discarded when <svelte:head> contains <html> tag

### ISSUE THREAD

**Issue by 7Hazard** [sveltejs/kit#4471]
### Describe the bug

This issue is not occurring while running on the dev server, only when building then previewing. Also tested when deployed to Cloudflare Pages.
The CSS is downloaded by looking at the DevTools networking tab, even seemingly loaded for a split second, but is discarded when the page finishes loading.

The global CSS resides in __layout.svelte.

When <html> tag is defined in <svelte:head>, CSS is not properly loaded.
If it's put in by accident, there is no indication whether it should not be there.

### Reproduction

https://github.com/7Hazard/svelte-issue-4471

### System Info

```shell
npx: installed 1 in 1.701s

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 11.70 GB / 31.94 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.60
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.55)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.33
    @sveltejs/adapter-static: next => 1.0.0-next.29
    @sveltejs/kit: next => 1.0.0-next.303
    svelte: ^3.44.0 => 3.46.4
```

### Severity

can get around it

**Comment by rcastellotti** [comment]
Is there any reason to not just put the css in `static/app.css` and then use `<link rel="stylesheet" href="app.css">`?
Tried it and works as expected.

**Comment by 7Hazard** [comment]
> Is there any reason to not just put the css in `static/app.css` and then use `<link rel="stylesheet" href="app.css">`?
> Tried it and works as expected.

Does that mean that you tried it as is and it did not work?

I will give what you suggested a try and see if it works.

**Comment by 7Hazard** [comment]
I found the issue, apparently having the following in `__layout.svelte` breaks it:
```html
<svelte:head>
	<meta name="robots" content="noindex nofollow" />
	<html lang="en" />
</svelte:head>
```

So it's a bad idea to specify <svelte:head> in `__layout.svelte`, but there was absolutely no indication of it. It worked fine under `npm run dev` but not when built and previewed.

**Comment by rcastellotti** [comment]
this is somehow interesting, now I am curious

**Comment by dominikg** [comment]
> I found the issue, apparently having the following in `__layout.svelte` breaks it:
> 
> ```
> <svelte:head>
> 	<meta name="robots" content="noindex nofollow" />
> 	<html lang="en" />
> </svelte:head>
> ```
> 
> So it's a bad idea to specify svelte:head in `__layout.svelte`, but there was absolutely no indication of it. It worked fine under `npm run dev` but not when built and previewed.

`<html>` inside `svelte:head` does not work.

Please provide a separate repository with a minimal reproduction. The history of the one you linked shows you've been changing it and it does not contain the head you posted above.

for the record: You should not use `<style global>` in __layout.svelte. Just add your css to the generated app.css.

**Comment by antony** [comment]
We had a quick discussion about this as @dominikg raised it, and there are two things which we don't really expect to work here, which might be causing your issue:

* the presence of a self closing html tag - if you close the html tag with no content, then you wouldn't expect any content to render
* html tags aren't valid inside `head` tags, and `svelte:head` is ultimately deisgned to act like a `head` tag.

**Comment by 7Hazard** [comment]
> We had a quick discussion about this as @dominikg raised it, and there are two things which we don't really expect to work here, which might be causing your issue:
> 
> * the presence of a self closing `html` tag - if you close the `html` tag without content, then you wouldn't expect any content to render
> * html tags aren't valid inside `head` tags, and `svelte:head` is ultimately deisgned to act like a `head` tag.

Indeed, it was cause <html> was put in <svelte:head>. Not sure how it got there.

> > I found the issue, apparently having the following in `__layout.svelte` breaks it:
> > ```
> > <svelte:head>
> > 	<meta name="robots" content="noindex nofollow" />
> > 	<html lang="en" />
> > </svelte:head>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So it's a bad idea to specify svelte:head in `__layout.svelte`, but there was absolutely no indication of it. It worked fine under `npm run dev` but not when built and previewed.
> 
> `<html>` inside `svelte:head` does not work.
> 
> Please provide a separate repository with a minimal reproduction. The history of the one you linked shows you've been changing it and it does not contain the head you posted above.
> 
> for the record: You should not use `<style global>` in __layout.svelte. Just add your css to the generated app.css.

I have edited the issue and provided a new link to the reproduction.

**Comment by dominikg** [comment]
> There was no generated app.css when i created the project.

https://sveltekit.new (opens a fresh instance of the default starter template)

there is `/src/app.css` imported by `/src/routes/__layout.svelte`

**Comment by dominikg** [comment]
I'm going to close this issue as adding `<html/>` into `<head>` would break regular html documents too and svelte:head wasn't designed to work for that. If you have questions about how to set the language for your page in sveltekit, open a discussion in this repo or find us on discord: https://svelte.dev/chat
