### ISSUE TITLE
Content negotiation for unexpected errors

### ISSUE THREAD

**Issue by akkie** [sveltejs/kit#4477]
### Describe the problem

Currently there is an error page which I can define for unexpected errors in the frontend. It seems that there is no such thing for APIs? Because if an API will throw an error, I get the error page as HTML back. It would be great if we can use something like content negotiation for errors. With this an API could respond with an error in the same format as it was send in the request. If I send a JSON request to an API, then the API should respond with an error in JSON format.

### Describe the proposed solution

If a JSON request was fired agains an API, the response in case of an error should also be returned as JSON.

### Importance

i cannot use SvelteKit without it

**Comment by Rich-Harris** [comment]
This was implemented in https://github.com/sveltejs/kit/pull/5314
