### ISSUE TITLE
create-svelte installs an older version of the package

### ISSUE THREAD

**Issue by FraWolf** [sveltejs/kit#4481]
### Describe the bug

When I try to use `npm init svelte@next my-app` it installs an older version of that (I can confirm because on my macbook it installs a completely different version, it has the library for test, on Windows nope, I still have the target under svelte.config.js file)

### Reproduction

npm init svelte@next my-app

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 7.48 GB / 15.96 GB
  Binaries:
    Node: 16.13.2 - D:\NodeJS\node.EXE
    Yarn: 1.22.4 - D:\Yarn\bin\yarn.CMD
    npm: 7.20.3 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 99.0.4844.84
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.52)
    Internet Explorer: 11.0.19041.1566
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
There's not anything we can do to resolve this or debug this. The package is published. Whatever's happening is something between your system, your local npm cache, and the npm registry. You could try cleaning your npm cache.

**Comment by FraWolf** [comment]
I fixed that, just a solution for future users, check if the package is installed globally, because I had it installed under the yarn global package
