### ISSUE TITLE
Remove `@playwright/test@next`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4488]
### Describe the problem

Ref #4479. In order to run Playwright in TypeScript projects with a `playwright.config.ts` file, we need to use `@playwright/test@next`, hence this file: https://github.com/sveltejs/kit/blob/master/packages/create-svelte/shared/%2Bplaywright%2Btypescript/package.json

Ideally we'd be using a stable version instead.

### Describe the proposed solution

Remove the file once 1.21 is released

### Importance

nice to have

**Comment by JackDra** [comment]
Ref to keep track of playwright 1.21 release: https://github.com/microsoft/playwright/releases
