### ISSUE TITLE
I killed svelte-kit, don't know how to recover: ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by jtlapp** [sveltejs/kit#4489]
### Describe the bug

([I posted to discord](https://discord.com/channels/457912077277855764/959535708769505320), but no responses. Don't know if this is a bug.)

I'm getting the following error trying to import TypeScript types from `@sveltejs/kit`:

`Cannot find module '@sveltejs/kit' or its corresponding type declarations`

I tried updating to `@sveltejs/kit@next` and `@sveltejs/kit@adapter-node@next`, but this didn't help.

And I get the following error trying to run svelte-kit:

```
$ svelte-kit dev --open
Malformed svelte.config.js
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/joe/repos/cavesite/svelte.config.js from /Users/joe/repos/cavesite/@root not supported.
Instead change the require of svelte.config.js in /Users/joe/repos/cavesite/@root to a dynamic import() which is available in all CommonJS modules.
    at requireRelative (/Users/joe/repos/cavesite/node_modules/@sveltejs/kit/dist/package.js:135:15)
    at Object.load_config (/Users/joe/repos/cavesite/node_modules/@sveltejs/kit/dist/package.js:157:17)
    at Object.<anonymous> (/Users/joe/repos/cavesite/node_modules/@sveltejs/kit/dist/cli.js:35:20)
    at Object.<anonymous> (/Users/joe/repos/cavesite/node_modules/@sveltejs/kit/svelte-kit:3:1)
error Command failed with exit code 1.
```

`svelte.config.js` hasn't changed:

```js
import adapter from '@sveltejs/adapter-node';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter()
	}
};

export default config;
```

When I rename `svelte.config.js` to `svelte.config.cjs`, it complains about not finding `svelte.config.js`.

### Reproduction

Try doing any of the above in [this repo](https://github.com/ut-entomology/cavesite).

### Logs

```shell
n/a
```

### System Info

```shell
System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 342.25 MB / 32.00 GB
    Shell: 5.0.11 - /usr/local/bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Safari: 13.1.1
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/kit: ^1.0.0-next.1 => 1.0.0-next.1 
    svelte: ^3.46.6 => 3.46.6
```

### Severity

blocking all usage of SvelteKit

**Comment by jtlapp** [comment]
Oddly, no matter how far I back out commits, the problem still persists. But when I start a fresh svelte-kit repo, there is no problem. So I'm now attempting to rebuild the project from a fresh svelte-kit repo...

**Comment by jtlapp** [comment]
I copied all the files over to a new installation, and things are working again. I suspect there were inconsistencies between svelte-kit dependencies.

**Comment by Conduitry** [comment]
https://github.com/ut-entomology/cavesite/blob/0ab5c98f1822ecc60b05a486b5e9173ce6d1d7c0/yarn.lock#L679 You're using `@sveltejs/kit@1.0.0-next.1`, which is also mentioned in your "system info" section.

**Comment by jtlapp** [comment]
Thanks! I'm not sure how that happened, but all is well now.
