### ISSUE TITLE
PWA Can't build non-index subdirectory routes while prerender is true.

### ISSUE THREAD

**Issue by HenrijsS** [sveltejs/kit#4490]
### Describe the bug

I have a static website and wanted to add PWA functionality to it. 
Hosting on Cloudflare pages, I wanted to `prerender: true` it.

The problem with PWA is that it somehow tries to grab a manifest.json in every directory for non-index pages.

For example: 
There's a sub route `test` which has an `index.svelte` and `testing.svelte`.
It compiles perfectly when removing `testing.svelte`, but when it's present, it shows that: 
```
> 404 /test/manifest.json (linked from /test/testing)
    at eval (file:///home/projects/sveltejs-kit-template-default-sb13we/node_modules/@sveltejs/kit/dist/chunks/index2.js:990:11)
    at save (file:///home/projects/sveltejs-kit-template-default-sb13we/node_modules/@sveltejs/kit/dist/chunks/index2.js:1223:4)
    at visit (file:///home/projects/sveltejs-kit-template-default-sb13we/node_modules/@sveltejs/kit/dist/chunks/index2.js:1114:3)
```

I'm confused as to why the index works and these don't.
It also builds when 

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-sb13we?file=src%2Froutes%2Ftest%2Ftesting.svelte&terminal=dev

Just run `npm run build` and you'll see the error.
Remove `testing.svelte` from `src/routes/test/` and the issue dissapears.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.09 GB / 15.86 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.4 => 1.0.0-next.34 
    @sveltejs/adapter-cloudflare: ^1.0.0-next.16 => 1.0.0-next.17 
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.29 
    @sveltejs/kit: ^1.0.0-next.202 => 1.0.0-next.304 
    svelte: ^3.44.0 => 3.46.6
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
Your `app.html` has a (relative) `<link rel="manifest" href="manifest.json" />` in it. This results in a reference to `/test/manifest.json` from `/test/`. By default, prerendering aborts when it sees references to files that aren't found, but this is configurable. In your case, however, the solution is likely to be to refer to the manifest with `/manifest.json` instead of `manifest.json`.
