### ISSUE TITLE
routing docs should say what to put in the html to link to another page

### ISSUE THREAD

**Issue by JasonWoof** [sveltejs/kit#4497]
### Describe the bug

This page about routing doesn't say how to use routes:
https://kit.svelte.dev/docs/routing

How do I link to pages/routes so svelte will handle the routing? Do I just use normal `<a href="/foo">`? Is there a special svelte tag for links that svelte handles like in React?

There's lots of example code on that page, but none of them seem to have any links to other pages/routes in them.

Please add some links to the examples, and maybe put in a sentence or two about it.

### Reproduction

https://kit.svelte.dev/docs/routing

### System Info

```shell
https://kit.svelte.dev/docs/routing
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
yes, it's just a normal link like `<a href="/foo">`

**Comment by PH4NTOMiki** [comment]
We could use something similar like Sapper has: 
Links are just <a> elements, rather than framework-specific <Link> components. That means, for example, that [this link right here](https://sapper.svelte.dev/), despite being inside a blob of markdown, works with the router as you'd expect
