### ISSUE TITLE
Error when using `Vite`'s native WebAssebmly imports

### ISSUE THREAD

**Issue by jquesada2016** [sveltejs/kit#4512]
### Describe the bug

According to [vite's docs](https://vitejs.dev/guide/features.html#webassembly), one should be able to import a "*.wasm" file directly, and call an init function, as such:

```js
import init from "./path/to/wasm.wasm";

await init();
```

If one call's `.toString()` on the init function, we can see the expected function declaration and body:
```
opts => __vite_ssr_import_0__.default(opts, "/path/to/wasm.wasm")
```

However, when run in SSR as follows:
```js
if (!browser) {
  await init();
}
```

I get a runtime error from node which is down below in the `logs` section.

I am trying to find a way of running WASM in both SSR and client side. I am able to run on client side no problem, but not in SSR.

### Reproduction

[Repro link here](https://github.com/jquesada2016/svelte-ssr-wasm-repro)

A few things of note. I am using `wasm-pack` with `Rust`. I am not using any plugins, as none that I've been able to find work well when the code is updated.

Within `src/lib/wasm` is the browser build and within `src/lib/wasm-node` is the node build. On their own, I can get the client to use the browser build, and node to use the node build, but I cannot get SSR to work with either of these.

When `wasm` is loaded, it will simply log to the console `"hello"`.

### Logs

```shell
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at onParseError (node:internal/url:563:9)
    at parse (<anonymous>)
    at new URL (node:internal/url:643:5)
    at new Request (file:///C:/Dev/Commercial/Importadora%20Queara/online-sales-v2/node_modules/@sveltejs/kit/dist/install-fetch.js:5907:16)
    at file:///C:/Dev/Commercial/Importadora%20Queara/online-sales-v2/node_modules/@sveltejs/kit/dist/install-fetch.js:6189:19
    at new Promise (<anonymous>)
    at fetch (file:///C:/Dev/Commercial/Importadora%20Queara/online-sales-v2/node_modules/@sveltejs/kit/dist/install-fetch.js:6187:9)
    at Module.__vite_ssr_exports__.default (/__vite-wasm-helper:20:32)
    at Module.__vite_ssr_exports__.default (/src/lib/wasm/index_bg.wasm:3:32)
```
```


### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 4.08 GB / 15.75 GB
  Binaries:
    Node: 17.7.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
    Internet Explorer: 11.0.22000.120
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
Is this unique to SvelteKit, or is this an issue with Vite? If the latter then there's probably nothing we can do, and the issue should be opened on [Vite's issue tracker](https://github.com/vitejs/vite/issues) instead

**Comment by jquesada2016** [comment]
No, this works in Vite

**Comment by jquesada2016** [comment]
@Rich-Harris I just pulled up a React project using [vite-plugin-ssr](https://[vite-plugin-ssr](https://vite-plugin-ssr.com/).com/) and was able to get it working there.

Here's the gist of what's going on here.

In order for the native `vite wasm` behavior to work, we need to look at what's going wrong.
The vite generated init function `opts => __vite_ssr_import_0__.default(opts, "/path/to/wasm.wasm")
` relies on `fetch` to work. However, the SvelteKit server is refusing the file, and therefore cannot proceed.

The error above is `invalid URL`. This is because in `SSR`, `import.meta.url` is generating something of the form "file:///blah/path/to/file.wasm`, which is being passed into the SvelteKit defined `fetch`, which is causing the URL request to fail.

All that needs to happen for this to work, is for the server to successfully respond with queried `*.wasm` file...perhaps by transforming the "file://" into the actual "http://"schema. and, of course, returning the actual `*.wasm` file itself.

I believe that it would not work, if for example, `fetch` tried to read the file directly from disk and return it directly, but I might be wrong.

**Comment by Rich-Harris** [comment]
Are you sure the WASM module is being instantiated server-side in the React project you mention? If I create a simple test like this...

```js
import vite from 'vite';

const server = await vite.createServer();

const { default: init } = await server.ssrLoadModule('/src/whatever.wasm');
const mod = await init();

console.log(mod);
```

...I get this error:

```js
ReferenceError: fetch is not defined
    at Module.__vite_ssr_exports__.default (/__vite-wasm-helper:22:26)
    at __vite_ssr_exports__.default (/src/whatever.wasm:6:69)
```

It seems to me that this is a Vite issue, and you'll need to raise it over there.

Side-note: when creating repros, please remove all the extraneous junk (custom aliases, Tailwind config, etc). It might feel harmless but maintainers have to look at a large number of repros, and it takes longer to figure out what's pertinent and what's irrelevant when the repo is full of unnecessary files.

**Comment by benmccann** [comment]
Please read this regarding Vite, SSR, and bug reporting: https://github.com/sveltejs/kit#bug-reporting

**Comment by Rich-Harris** [comment]
Closing as no response, and this seems very likely to be a Vite issue rather than a SvelteKit one

**Comment by AbstractFruitFactory** [comment]
@jquesada2016 did you find a solution? I'm having the same issue and I'm lost scouring the deepest corners of the web trying to find an answer...

**Comment by jquesada2016** [comment]
> @jquesada2016 did you find a solution? I'm having the same issue and I'm lost scouring the deepest corners of the web trying to find an answer...

I did! What I am doing is to check if I'm in the server and passing `init` the module from disk. The trick is to find out where SvelteKit is going to place your final `.wasm` file,, because I did not find an easy solution for this one besides checking with the specific integration you're using.
