### ISSUE TITLE
External Named Layout - from package

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#4518]
### Describe the problem

The new `__layout@name.svelte` syntax looks cool.

I have a thought to expand or refute:
Support for a layout, loaded externally, from a package.

### Describe the proposed solution

You install the `npm i packagename` package that contains the layout file.
You use this layout via the package name, for example: `__layout@packagename.svelte`.
That's it. :)

You could also add a built-in, external layout in SvelteKit, e.g. to reset `__layout-reset.svelte`:
Then use for reset `__layout@reset.svelte`, so you won't need to create an empty `__layout-root.svelte`, containing the `<slot/>` itself (as recommended in the SvelteKit documentation).

### Alternatives considered

1. adder containing the layout.

2. wrapper in `__layout.svelte` with imported component:
```svelte
<script>.
Import packagename from "packagename";
</script>
<Packagename><slot/></Packagename>
```
...Such a thing doesn't work, because in Packagename you can't, for example, provide a `load` function.

### Importance

would make my life easier

### Additional Information

Such a thing would be part of a broader thinking about external modules, as related - https://github.com/sveltejs/kit/issues/3723

**Comment by Rich-Harris** [comment]
Beyond resets (which are better done without an external package, which would only make things harder to follow) is this a real use case or a hypothetical one?

**Comment by lukaszpolowczyk** [comment]
@Rich-Harris Just using an external layout - more hypothetical.


But in my head I have kind of a complete initial login support that would also require external delivery of hooks code.
(For that you would also need - https://github.com/sveltejs/kit/issues/3723, maybe also with externally loaded routes?)

Such a thing, that you install the package, turn it on and you have the whole login system (under the selected database, etc.).
This could be done with adders, but adders would be less flexible.

Along with that, using an External layout would add a login bar, maybe provide some pre-processed, typical data in `stuff` or something similar.

**Comment by Rich-Harris** [comment]
This doesn't sound like something we'd want to support. It doesn't add any new expressive power, it just adds a very small amount of convenience when solving a very specific problem

**Comment by lukaszpolowczyk** [comment]
@Rich-Harris Well tough, at least I got the idea out of my head.
I don't have any better arguments to convince you of this idea.

**Comment by dummdidumm** [comment]
Closing as it sounds we agree that this is too specific to be worth the additional maintenance, and the "workaround" is to just import the package's component, together with a library-provided load function and do something like this:

```svelte
<script>
  import Layout, { libraryLoad } from 'package';
  export const load = libraryLoad;
</script>

<Layout>
  <slot />
<Layout>
```
