### ISSUE TITLE
Seems like the new way of using layouts doesn't work with index svelte files

### ISSUE THREAD

**Issue by GeForcez** [sveltejs/kit#4521]
### Describe the bug

Hi,
It seems like if you create an index.svelte with a named layout doesn't recognise it as the root 'page' of that folder or subfolder.
eg:
```
├ x/
│ ├ __layout-foo.svelte
│ ├ index@foo.svelte
│ └ someotherpage@foo.svelte
├ __layout-global.svelte
└ index@global.svelte
```

here all index[@.....].svelte files give 404's
(unless i'm not getting the concept of the new layouts)

### Reproduction

create the following in your routes folder:
src/routes/
```
├ x/
│ ├ __layout-foo.svelte
│ ├ index@foo.svelte
│ └ someotherpage@foo.svelte
├ __layout-global.svelte
└ index@global.svelte
```
start dev server and go to the root page

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 570.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.7.2 - /opt/homebrew/bin/node
    npm: 8.5.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 97.0.1
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/kit: next => 1.0.0-next.306 
    svelte: ^3.46.6 => 3.46.6
```

### Severity

serious, but I can work around it

**Comment by tsukhu** [comment]
Same here ..
For example I have a folder under routes /login
with /__layout-login.svelte and a route file index@login.svelte (renamed the existing __layout.reset.svelte to __layout-login

I get a 404 for /login not found when I use goto 

The logic is simple - On the root layout , if the user has not logged in redirect to the login page 
Can't figure out how to get this working now
Is there a sample we can refer to?

**Comment by GeForcez** [comment]
Well i was doing some testing, on first sight it looks like it works with the other way of creating that 'index' page for a folder/subfolder.
eg: 
```
├ login/
│ └ register@login.svelte
├ __layout-login.svelte
├ login@login.svelte
├ __layout-global.svelte
└ index@global.svelte
```
This seems to work just fine, it is way less visible what an index page is for a certain path though (imo).

**Comment by t3hmrman** [comment]
Also for anyone using the [above workaround](https://github.com/sveltejs/kit/issues/4521#issuecomment-1088355392), note that you must also rename endpoints (ex. `login@login.svelte`'s endpoint file would be named `login@login.ts`)

**Comment by GeForcez** [comment]
actually maybe a bit unrelated but still quite useful to know, the routeId that is provided in for example the load function of a svelte component (docs [here](https://kit.svelte.dev/docs/types#sveltejs-kit-load)) also returns the full svelte component name so in previous example this would be `login@login` instead of just `login`. 
Just an fyi for the people that use the routeId in their code to do something.
Although i only tested it in the load function could be the case for other parts where the routeId also is passed.

**Comment by stephane-vanraes** [comment]
You can name your file `@foo.svelte` (without the `index` part) and it will work as expected, 
To a degree this does make sense if you consider the following mappings
`prodcuts/about.svelte` => `products/about`
`products/about@foo.svelte` => `products/about`

As you see the `a@b` will map to `a` from which follows that

`products/@foo.svelte` => `products/`

(the part before the `@` is an empty string)

Which is the same as
`products/index.svelte`  => `products/`

If this is the intended behaviour though it should be documented

**Comment by tsukhu** [comment]
Thanks @GeForcez - your recommendation worked for me
Any recommendation on a slug

Previously 
```
/dash/_layout.reset.svelte
/dash/[slug].svelte
```

**Comment by tsukhu** [comment]
Ok this worked for the slug

```
/__layout-dash.svelte
/dash/[slug]@dash.svelte
```
```
