### ISSUE TITLE
Multiple monkeys in layout title

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#4531]
### Describe the problem

It's cool to create [layout chains](https://kit.svelte.dev/docs/layouts#named-layouts-inheritance-chains), it gives you nice flexibility.

But there is a limitation - you can't in one layout title, immediately select several elements of the layout chain.

For example, with:
`__layout@one.svelte`
`__layout-one@two.svelte`
`__layout-two.svelte`

You cannot use `__layout-one` WITHOUT `__layout-two`.
Then he will have to duplicate `__layout-one`, with the same code, but without `@two`.

### Describe the proposed solution

Introduce the syntax:
`__layout@one@two.svelte`

Then you can leave `__layout-one` unconnected in the forced string:
`__layout@one@two.svelte`
`__layout-one.svelte`
`__layout-two.svelte`

And that way you can use `__layout-one.svelte` somewhere and it will be a standalone layout, without `__layout-two.svelte` automatically attached to it.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
I disagree. Please don't waste maintainers' time by raising issues for features just in case they might be useful to someone someday; that's not how progress works.
