### ISSUE TITLE
Allow for matchers inside route code

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#4539]
### Describe the problem

The new `route matching` feature is very nice 👍, but I think it is a touch cumbersome to have to define the matching function in an _external_ javascript file.  When I first read about them I thought I could do: 
```html
<script context="module">
   export function match(params) {
     return something.with(params)
  }
</script>
``` 
which obviously doesn't work 🙄 

### Describe the proposed solution

Allow the above ?
I guess this would require the compiler to inspect the route and add the matcher if it has a matcher.

### Importance

nice to have

**Comment by Conduitry** [comment]
Having this in external files was a conscious decision to avoid issues with treeshaking. We want to download all matchers as part of the route manifest with the initial page load from the server, but we don't want to download other code from any of the pages until the user actually visits them. If the matcher lived in the component, there would always be the risk of the bundler not seeing something as treeshakable, resulting in a lot of code from various pages ending up in the JS for the initial page load.
