### ISSUE TITLE
Shadow endpoint doesn't support for ReadableStream

### ISSUE THREAD

**Issue by gunggmee** [sveltejs/kit#4556]
### Describe the bug

`RequestHandlerOutput`'s `body` accepts `ReadableStream` instance in general, yet it throws an error when the endpoint is a shadow endpoint.

### Reproduction

The code works well if it's called as standalone endpoints, but it throws an error if it's called as shadow endpoints:

```
export const get: RequestHandler = async () => {
  const res = await fetch('some url')
  return { body: res.body }
}
```

The following code is direct cause of the error:

https://github.com/sveltejs/kit/blob/2d6f0d2d49d4505112bdc6f2f0ef1b8ce1d1fb40/packages/kit/src/runtime/server/page/load_node.js#L508-L510

If I comment-out the above code, everything works fine.

### Logs

```shell
Body returned from endpoint request handler must be a plain object
Error: Body returned from endpoint request handler must be a plain object
    at validate_shadow_output (file:///Users/ak/prjs/pxd-cr/services/crapp/.svelte-kit/runtime/server/index.js:2052:9)
    at load_shadow_data (file:///Users/ak/prjs/pxd-cr/services/crapp/.svelte-kit/runtime/server/index.js:1988:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load_node (file:///Users/ak/prjs/pxd-cr/services/crapp/.svelte-kit/runtime/server/index.js:1597:5)
    at async respond$1 (file:///Users/ak/prjs/pxd-cr/services/crapp/.svelte-kit/runtime/server/index.js:2243:15)
    at async resolve (file:///Users/ak/prjs/pxd-cr/services/crapp/.svelte-kit/runtime/server/index.js:2744:11)
    at async respond (file:///Users/ak/prjs/pxd-cr/services/crapp/.svelte-kit/runtime/server/index.js:2688:20)
    at async file:///Users/ak/prjs/pxd-cr/services/crapp/node_modules/@sveltejs/kit/dist/chunks/index.js:298:24
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (20) x64 Intel(R) Xeon(R) W-2150B CPU @ 3.00GHz
    Memory: 501.01 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 96.0.3
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.33 => 1.0.0-next.33 
    @sveltejs/adapter-node: ^1.0.0-next.72 => 1.0.0-next.72 
    @sveltejs/kit: ^1.0.0-next.299 => 1.0.0-next.299 
    svelte: ^3.46.4 => 3.46.4
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
This is deliberate - during SSR, the object is passed directly from the endpoint to the component, without any kind of buffering or deserialization. It's only when you access the endpoint via client-side navigation that the data is turned into a `Response`. Use `res.json()` in your handler

**Comment by gunggmee** [comment]
@Rich-Harris, Thank you for the explanation.

But my current application need to invoke shadow endpoint during SSR and also from browser via `setInterval()`, since the endpoint calls a remote API which returns varying data from call to call.

Does it look like a valid use case for streaming support for shadow endpoint?

For now, I made standalone endpoint like `[blah].svelte` and `[blah]-stream.ts` and let `[blah].svelte` call the standalone endpoint using old method - `Load` from `<script context="module">`. Could you recommend a better way to handle this situation?

Thank you.
