### ISSUE TITLE
Change App.Locals in ambient.d.ts to a type

### ISSUE THREAD

**Issue by pedeEli** [sveltejs/kit#4557]
### Describe the problem

```ts
// src/global.d.ts
declare namespace App {
    type Locals = LoggedIn | LoggedOut

    interface LoggedOut {
        authenticated: false
    }

    interface LoggedIn {
        authenticated: true,
        user: User,
        isAdmin: boolean
    }
}
```

is not possible, because App.Locals is an interface in ambient.d.ts and it will not be overwritten by my own Definition.

### Describe the proposed solution

```ts
// kit/types/ambient.d.ts

// change this
declare namespace App {
    export interface Locals {}

    ...
}

// to this
declare namespace App {
    export type Locals {}

    ...
}
```

### Importance

would make my life easier

**Comment by jasonlyu123** [comment]
It's intended to be [merged](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces) with the user's interface definition. And `type` can't merge with another type. Maybe you can just put your locale one level deeper? For example: 

```ts
// src/global.d.ts
declare namespace App {
    type UserInfo = LoggedIn | LoggedOut

    interface LoggedOut {
        authenticated: false
    }

    interface LoggedIn {
        authenticated: true,
        user: User,
        isAdmin: boolean
    }

    interface Locals {
      info: UserInfo
    }
}
```

**Comment by dummdidumm** [comment]
I tend to agree that this is a "won't fix". AFAIK we could use namespace merging by not providing empty Interfaces/types in kit's library Code but that could become tricky to handle during kit development (you do need to know that there are errors which would be gone because of the app.d.ts later on)

**Comment by pedeEli** [comment]
Oh yeah, i forgot a type alias cannot be merged, I thought it would be overwritten. I guess the only way is your solution then, @jasonlyu123

**Comment by dummdidumm** [comment]
Closing as we now all seem to agree that keeping the interfaces at the cost of not being able to use union types at the top level is ok.
