### ISSUE TITLE
The `base` from `$app/paths` doesn't contain a slash

### ISSUE THREAD

**Issue by illright** [sveltejs/kit#4561]
### Describe the bug

For some reason, with default settings, the `base` variable from `$app/paths` contains an empty string, even though the TypeScript typings and the docs both very explicitly mention that it will and should always contain a slash. 

### Reproduction

https://stackblitz.com/edit/sveltekit-empty-basepath-repro?file=src/routes/__layout.svelte

All I changed from a fresh project was to add some text before the slot in the layout that outputs the basepath onto the page.

### Logs

```shell
N/A
```

### System Info

envinfo doesn't seem to play well with StackBlitz, but believe me when I say I created the project no sooner than 15 minutes before posting this issue, everything is fresh as a daisy

### Severity

annoyance

**Comment by jhubbardsf** [comment]
So I checked out the documentation and this is what it says for for the base variable.

> base — a root-relative path that must start, but not end with / (e.g. /base-path), unless it is the empty string. This specifies where your app is served from and allows the app to live on a non-root path

Seems that it does say it should be an empty string. If it was allowed to be '/' then that's ending with a slash as well.

**Comment by Conduitry** [comment]
Yup it sounds like we just need to update https://kit.svelte.dev/docs/modules#$app-paths-base to reflect the empty-string case mentioned in https://kit.svelte.dev/docs/configuration#paths
