### ISSUE TITLE
SCSS class renaming does not work for nested classes

### ISSUE THREAD

**Issue by infusion** [sveltejs/kit#4566]
### Describe the bug

SCSS class names like `.open` within the nested structure

```
<style lang="scss">
  .select {
    &.open {
      display: block;
    }
  }
</style>
```

should work when selected individually, such as addressing `open`.

### Reproduction

Having a CSS class `open` inside a component that is applied conditionally to a div like

```
<div class="select" class:open={isOpen}>
```

with the SCSS rule

```
<style lang="scss">
  .select {
    &.open {
      display: block;
    }
  }
</style>
```

does not work as expected. Adding global like 

```
<style lang="scss" global>
```

solves the problem, which suggests that the class `.select.open` is not handled properly.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 22.43 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Safari: 15.4
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
What CSS is this getting preprocessed to?

**Comment by infusion** [comment]
With global option on, it is compiled to 

```
.select.open {
  display: block;
}
```

**Comment by RawMajkel** [comment]
> does not work as expected

What do you mean "as expected"?
Do you expect other output than `.select.open { display: block; }` ?

I'm using latest SvelteKit version (next.320) and it's working fine.

**Comment by Rich-Harris** [comment]
Please provide a reproduction, or I'll have to close this issue. See https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml
