### ISSUE TITLE
Named layouts no longer work

### ISSUE THREAD

**Issue by ZaDarkSide** [sveltejs/kit#4570]
### Describe the bug

The documentation describes Named Layouts here: https://kit.svelte.dev/docs/layouts#named-layouts
They no longer work and the following error is reported when you try to create a new file named `__layout-foo.svelte` : `Files and directories prefixed with __ are reserved (saw /src/routes/__layout-foo.svelte)`

### Reproduction

1. Create a new file named `__layout-foo.svelte`
2. Observe error in console: `Files and directories prefixed with __ are reserved (saw /src/routes/__layout-foo.svelte)`

### System Info

```shell
    @sveltejs/adapter-node: 1.0.0-next.73 => 1.0.0-next.73
    @sveltejs/adapter-static: 1.0.0-next.29 => 1.0.0-next.29
    @sveltejs/kit: 1.0.0-next.301 => 1.0.0-next.301
    svelte: ^3.46.6 => 3.46.6
```

### Severity

serious, but I can work around it

**Comment by mrkishi** [comment]
Named layouts were introduced in `next.306`, you're on `next.301`.
