### ISSUE TITLE
Color adjustment asap please - Docs

### ISSUE THREAD

**Issue by savannahx** [sveltejs/kit#4594]
### Describe the problem

Hello ladies and gents.

I am fairly new to Svelte/Sveltekit but I would like to make a suggestion please.

It is regarding documentation...

Can somebody change the background color of the sidebar from this difficult color #676778; to something darker?
Literally every time you want to focus on a link on the sidebar your eyes hurt and you lose at least 1 to 2 seconds until you focus on what you want to find and all that because poor contrast.

Also the "highlighted" link (the active one) is, honestly, almost indistinguishable from the inactive links below and above, why is this? 

Why not make it something like almost black background with white inactive links and the active link like the orange color from the logo? Perhaps put a divider line in between links or something?

By the way, I do these things every time  I use the docs, this is how bad it is, no offense to anyone, but 1-2 seconds of faster focus per person per time they visit the docs, well, we want to be talking about performance when we are talking about Svelte right? 

Please do the right thing, the nice svelte logo orange color matches great with a darker blackish background color, why put that ugly blueish/purplish (which is not dark enough for a bg color)?

To whoever can make this happen, PLEASE we need docs that can be scanned quickly. 

Here is the contrast score https://coolors.co/contrast-checker/ffffff-676778
It's almost poor... if you have any sort of sight issues... I mean come on, how come no one addressed this before, docs is a huge part of the process.

### Describe the proposed solution

Color for the "active" link => #ff3e00

Color for the sidebar background => #242426

Any dark enough background (with no colors, either blackish or grayish/blackish will do) 

### Alternatives considered

Please adjust this so visually impaired or people with sight difficulties (even the ones with glasses) can focus easier on the links and traverse faster. 

### Importance

i cannot use SvelteKit without it

### Additional Information

Every time I browse the docs I literally go to inspect and change these myself....!

Thanks for your understanding!

**Comment by benmccann** [comment]
I tend to agree that we could add more contrast to the sidebar. I'm not sure I like the proposed changes though. Here's a screenshot of what they look like

![Screenshot from 2022-04-12 09-40-44](https://user-images.githubusercontent.com/322311/163012323-601a03cb-4502-4501-bf3b-79f284653f93.png)

Alternatively, here's the sideback background set to `#363636` with no change to the active link

![Screenshot from 2022-04-12 09-43-56](https://user-images.githubusercontent.com/322311/163012757-73360b3d-d8df-42dd-bcd8-56c396ba3133.png)

**Comment by benmccann** [comment]
Another idea, here's using bold rather than color to indicate the active item

![Screenshot from 2022-04-12 09-48-01](https://user-images.githubusercontent.com/322311/163013432-21c71ad2-0dc6-4bea-aeba-fa71bda869a0.png)

**Comment by savannahx** [comment]
Hey @benmccann  thanks for the response here.

On the first slide the accent color looks kinda red and not the actual orange brand color, are you sure you used the right code? 
If it is the right color code then perhaps on that particular background we could lighten the orange just a bit.

Listen I very much appreciate your feedback here but I have to mention that as a person that has poor sight, I would argue that it's imperative the background to be kept at least a bit darker than your proposed hex above and the active link to be of an accent color (instead of a base like white) so it easily distinguishable and not on the same hue as the inactive links (truly important).

Check this =>
https://vuejs.org/guide/introduction.html
(They also have dark and light theme...)

We want to grow as a framework and as a user base but Vue.js is killing us with those Docs comparing to Svelte/kit's.

Please choose a slight darker background color, just a tiny touch and keep a punchy accent color close to the logo for the active links, I am positive this will help grow the framework, it sounds crazy but it is in my experience an important detail really.

Between choosing competing stuff online I personally have chosen then ones with the more accessible documentation.

@benmccann  thanks again for your consideration!

**Comment by UltraCakeBakery** [comment]
If only there was something like https://caniuse.com/mdn-css_at-rules_media_forced-colors

**Comment by savannahx** [comment]
Hey @UltraCakeBakery, thanks for your reply here.

I am not sure what you are suggesting and if there is sarcasm involved on your reply.
To be honest it feels there is sarcasm involved in your message because of the way you started your sentence and you didn't expand on what you are trying to say, you didn't take the time, you pasted a link and asked of us to figure everything else out.
 
You provided no basis for all other people to work with. Is this link a universal and time-efficient solution to the current problem? 
Do you mind telling us a little bit more please? 

This is a serious matter that affects thousands of people (in different degrees). 
Are you suggesting we all take the above action instead of adjusting 2 colors in the actual docs?

This is a genuine problem that needs solving, please provide constructive feedback/solutions.
No negativity is needed, thank you.

**Comment by UltraCakeBakery** [comment]
> Hey @UltraCakeBakery, thanks for your reply here.
> 
> I am not sure what you are suggesting and if there is sarcasm involved on your reply. To be honest it feels there is sarcasm involved in your message because of the way you started your sentence and you didn't expand on what you are trying to say, you didn't take the time, you pasted a link and asked of us to figure everything else out.
> 
> You provided no basis for all other people to work with. Is this link a universal and time-efficient solution to the current problem? Do you mind telling us a little bit more please?
> 
> This is a serious matter that affects thousands of people (in different degrees). Are you suggesting we all take the above action instead of adjusting 2 colors in the actual docs?
> 
> This is a genuine problem that needs solving, please provide constructive feedback/solutions. No negativity is needed, thank you.



> This is a serious matter that affects thousands of people (in different degrees).
> Are you suggesting we all take the above action instead of adjusting 2 colors in the actual docs?

Hey @savannahx, thanks for your reply here.

I am not sure if there is unawareness or selfishness involved on your reply.
To be honest it feels there was unawareness and selfishness involved in your message because of the way you formulated yourself and did not think about us, the other 99% of svelte-kit users, who also have to deal with this change and asked of us to actually do all the work of implementing this new color.

You provided no way for us to reach a middle ground where both you and others can be happy. It seems like you really just want us to change the color to what you want. Did you even read the link that I posted in the one minute before you started writing this reply you posted 3 minutes after me making my original comment? Do you mind telling us why you get a bad vibe from my comment (saying it is sarcastic) even though I was trying to be helpful?

Suggestions like these affects billions of people (in different degrees). Are you suggesting we completely change the documentation instead of asking you and "the others" to start using the build-in tools provided to you by your operating system and browser?

This is a genuine problem that needs solving, please consider changing your mindset. We do not need more any people in the world that are like:

"THE WORLD NEEDS TO CHANGE, N̵̠̲͛̿͘O̵̞̙̒̇͘T̴̼͓̮̈́͂ ME" 

"I AM **N̵̠̲͛̿͘O̵̞̙̒̇͘T̴̼͓̮̈́͂** GONNA WEAR GLASSES OR CHANGE MY SETTINGS! ALL LIGHTS AND COLOURS S̷͈̫̮͙̑̔͌̓̐H̸̨̨̨͎̱̫͊̉̂͌Ó̸͓͓͖̽̏Ǘ̴̹͙͕̝͈ͅĻ̴̛̭͇̭̗̤̈́̽͐D̴̻̈̅̀̕ JUST GET BRIGHTER AND DARKER Ẁ̵̞̻̤̗̩̎̅H̴̨̤̮̼͉͆́̚͜͝É̴̛̠̃̌Ǹ̷͚͔̮͙̬͖̉̄̈̆͌͠ ̵͖̩̰͗̿͝Í̵̜͈͂̋ ̵̟͓̱̤͖̯͙͗̏̍̒́̈̚W̴̩̹̖̭͂̿ͅÂ̷̳̬̱͕̐̄̓̔̚N̴̙̳͔̏͒̇̿ͅT̷͉͚̳̈͂̈́̈͐̌ͅ ̶͍̦͂̓́T̸͍̭̤̲̲͕̔͜H̸̳̣̑͌̓̌̆͛Ḛ̴̢̛̱͋̇́M̶̳̀̀̂̄́͊ ̵͕̣̲̼́͗̈́̎̊̊͑Ţ̸̭͕̪͔̼͑͛̆ͅŐ̷̧̗̫͈̄͑͌͛͆̅O̷͖͈̱̳͓̠̎̋́͘!̵͓̩̙̦̍̂̾ͅ!̴̡̱͇̝͔̻̭̊̀͠!̴̛̠͔̩͚͂̋̕͠!̵̛̟̼̘̼͍͝!!!!"

**Comment by UltraCakeBakery** [comment]
I am impaired too, and get sick of suggestions like these. 
WE are the ones with disabilities, not the rest of the world. WE need to adapt ourselves to the world, NOT the other way around.

The documentation could offer better support for high contrast mode, dark mode, screen readers.. But I don't think it should.
It is fine as is. 

If you are still unable to read the documentation (which is also available on Github, which has a very great accessibility).

you might want to buy a new monitor, open or close your blinds, change your color profile, tweak the brightness, gamma, contrast and other settings, increase the scale of your UI or install a extension which can do automatic contrast for you. 

Again, this is a problem only we deal with. We are an edge case.

**Comment by savannahx** [comment]
Dude's raging, for young people it's mostly preferable to fortify behind a false sense of reality and stand their ground. They are young and cocky (at least on the internet :P)
I am too old for this. it's okay, I am not perfect either, nobody is.  

Anyway I really hope this gets addressed if anyone has access and time to implement this color edit (removing the washed out blueish background and using an accent color for the active link).
I would create a pull request but I barely know Svelte so apologies for not taking the initiative in that regard.

@benmccann  feel free to let me know if and when I should close this Issue and thanks again for your consideration.

**Comment by Rich-Harris** [comment]
alright, time out. i locked the conversation.

accessibility matters to us and we want to get this right. people shouldn't have to fiddle with browser settings just to read documentation. at the same time, there's a balance to be struck between maximising contrast and making the site pleasant to look at for people without visual impairments and/or shitty screens (we could just use pure black on pure white or vice versa everywhere, but that would be very tiring for most people to look at for any length of time).

so we will address this, though i make no guarantees about where it sits in the priority queue, and putting 'asap' in the issue title or declaring that the current contrast ratio means 'i cannot use SvelteKit without it' (unlikely) won't affect that decision (though there is now a pull request for it pending review — https://github.com/sveltejs/sites/pull/327)
