### ISSUE TITLE
Support for subdomains in SvelteKit

### ISSUE THREAD

**Issue by cowboycodr** [sveltejs/kit#4598]
### Describe the problem

I do want to start this off with the acknowledgment that subdomains with SvelteKit is possible. However, there is no clear documentation nor have I found any clear and concise examples on how to do so. The only reason I even assume it is possible  is because of [kit.svelte.dev](https://kit.svelte.dev). 

If I am wrong, and there is a clear and documented way of adding support for subdomains to SvelteKit websites then please do let me know and I will close this issue.

### Describe the proposed solution

The proposed solution is that of the title.

### Alternatives considered

Subdirectories are fine, just not ideal.

### Importance

nice to have

**Comment by Conduitry** [comment]
I don't know what this is asking for. You have access to the hostname via the `event` that's sent to endpoints and the `$page` store that's available to pages.

`kit.svelte.dev` is its own app/site that is completely separate from the app/site at `svelte.dev`.

Is the request to be able to have one app serve multiple hostnames, and have the hostname be part of what distinguishes routes, instead of just the path?

**Comment by cowboycodr** [comment]
I understand I have access to the site's hostname. Even then there is still no clear documentation. 

I am using cloudflare pages and see no clear way of using multiple subdomains with one or even multiple SvelteKit projects.

**Comment by benmccann** [comment]
subdomains are something that you configure with DNS (not with your frontend framework), so there's nothing that SvelteKit would do here

If you'd like help or are confused about something, please ask on Discord

**Comment by rocketinventor** [comment]
Hi!

I think that the question being asked is if someone wants to use dynamic subdomain routing can they do that in Svelte Kit as part of their routing scheme:

I.e.
```
http://mysubdomain.example.com => '/subdomain/mysubdomain/'
http://myexcellentsubdom.example.com/homepage => '/subdomain/myexcellentsubdom/homepage'
http://first.second.example.com => '/subdomain/first/second/'
http://first.second.example.com/another/page => '/subdomain/first/second/another/page'
```

In express this is possible using `express-subdomain-handler`

In other words: Just like you can use `src/routes/about/+page.svelte` and `src/routes/blog/[slug]/+page.svelte` to make `/blog/foo` and `about` pages on mysite.com, so too you should be able to create a route for a subdomain such as `/src/routes/[subdomains]/login/+page.svelte` or `/routes/search.site/+page.svelte` to make a `login.mysite.com` or `search.mysite.com` subdomain.

This seems like a reasonable and understandable request, so I think that this issue should maybe be reopened.

**Comment by PaperPrototype** [comment]
I can also confirm this would be invaluable

**Comment by PaperPrototype** [comment]
Op and it looks like this is complete solved with rerouting.

https://ramonmalcolm.com/articles/dynamic-domain-subdomain-routing-sveltekit-guide/
https://svelte.dev/docs/kit/hooks#Universal-hooks-reroute

I am now able to put all my +page.svelte files into any folder I want and render it with the subdomains actings as a path

```ts
// src/hooks.ts
import type { Reroute } from "@sveltejs/kit";

export const reroute: Reroute = ({ url }) => {
    const host = url.host; // e.g., "mysubdomain.project.example.com"

    const parts = host.split('.')

    console.log("host", host)
    console.log("subdomain", parts)

    if (parts.includes("project") && parts.length > 2) {
        console.log("/isolated/" + parts[0])
		return `/isolated/${parts[0]}`;
    }

	if (parts.length > 1) {
        console.log("/isolated")
		return `/isolated`;
	}

	// Add more domain or subdomain checks as needed
};
```
