### ISSUE TITLE
sessions

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#46]
Something people seem to trip over a bit is the fact that `session`, despite being a writable store, doesn't get persisted. I wonder if we can address that:

```svelte
<script>
  import { stores } from '$tbd';
  const { session } = stores();

  let name;

  async function update_username(name) {
    // optimistic — update the client-side store, then persist
    // (rolls back in case of failure)
    session.update($session => ({
      ...$session,
      user: { ...$session.user, name }
    }));

    session.persist();

    // pessimistic — wait until success before updating
    // client-side store
    session.persist($session => {
      ...$session,
      user: { ...$session.user, name }
    });
  }
</script>

<!-- pretend i did this properly, with a progressively enhanced <form> -->
<input bind:value={name}>
<button on:click={() => update_username(name)}>
  Update
</button>
```

This requires that the developer add some persistence logic. Perhaps in the same file where we define logic for getting a session (#9), we have a place to put logic for persistence:

```js
// src/session/index.js
import { parse } from 'cookie';
import * as db from './db.js';

export async function get(headers) {
  const cookies = parse(headers.cookie);
  const user = await db.get(cookies.session_id);
  return { user };
}

export async function persist(headers, data) {
  const cookies = parse(headers.cookie);
  const user = await db.set(cookies.session_id, data); // validate and store
  return { user };
}
```

Glossing over some details but what do folks think?

**Comment by rmunn** [comment]
I have a design for `persistSession` (rather than `setSession`), and for `$session.refresh()`, sketched out in https://github.com/sveltejs/kit/issues/1726#issuecomment-913295755. Rather than reproduce that comment here, I'd suggest making comments on #1726 so that the discussion on session persistence and refreshing can be in one place instead of spread between multiple issues.

**Comment by Rich-Harris** [comment]
Going to close this in favour of #1726 as much of the thread is rather out of date
