### ISSUE TITLE
Could we get more magical with code splitting? (yes, but...)

### ISSUE THREAD

**Issue by willster277** [sveltejs/kit#4606]
### Describe the problem

> Before we begin, I want to say that if this has been proposed here before, or in similar projects, or as a feature for the JS programming language, then I've used the complete wrong search terms as I haven't been able to find anything that even mentions that ESM does this. My bad.

To start off let's go through setting up a project that illustrates the issue ([here's one I made earlier](https://github.com/willster277/magical-codesplitting-maybe));
1. `npm init svelte@next issue-4606` & `cd issue-4606` & `npm i` etc
2. make the `src/lib` folder and `src/lib/index.[jt]s`
3. make some files in `src/lib` which match;
```js
// a.js
const a = "a";
console.log(a);
export default a; 
```
4. in `src/lib/index.[jt]s`, add `export { default as NAME } from "./NAME"` for each file
5. in `src/routes/index.svelte`, import one (and only one) of these items
6. run `dev` or `build` & `preview` and observe all of the console logs from the code you have not used

Now, this is completely expected behavior from ESM, we import `a` from `$lib/index`, which in turn needs to satisfy all of it's imports in order to execute and export, so all the other files come in with it. Fair enough.

But, it would be faster to not have to import all of that.
The obvious solution is for developers to stop being lazy and to import things directly from the file they're exported from.
The issue with this is that your options are;
```js
import { a, b, c } from "a-to-z"; // may load unused files
````
```js
import { a } from "a-to-z/vowels";
import b from "a-to-z/consonants/b";
import c from "a-to-z/consonants/c"; // nothing unused, but this scales horribly
```

### Describe the proposed solution

Something in the compiler that would analyse import statements in js/ts/svelte files under `src/` and trace them to the file the imported object originates from.

I'll admit it sounds like a lot of work and problem solving just to get rid of a minor problem, but depending on what you're importing and where from, it could make a real impact to both the client device and the server runtime.

### Alternatives considered

This does sound like something that a preprocessor could do, although I would argue it's more likely compiler territory as it requires knowledge of the project as a whole rather than an individual file (I've also proposed that it should apply to js/ts files in the project, which preprocessors can't yet modify).

Ultimately this is something I came up with about an hour ago when I was poking around the network tab in firefox. The idea certainly needs fleshing out, and a lot more input from someone who knows how all this works behind the scenes.
I'm just a guy on the internet building websites.

### Importance

nice to have

**Comment by dummdidumm** [comment]
This sounds like the job of a bundler/minifier to treeshake away unused code. AFAIK that's not done in dev mode because that would take longer than just keeping the code as-is, and in dev mode you want rapid iteration, not optimized code. Not sure about the output of `build`. Either way, this isn't SvelteKit's (or Svelte's) territory. If this isn't done already on production builds, we could at least document how to set up proper treeshaking.

**Comment by Conduitry** [comment]
Yup. We don't want to worry about this in development builds - and in production builds, this is already getting done by bundlers. Bundlers are already pretty good at this, and any improvements to this sort of thing should happen there, and not in SvelteKit.
