### ISSUE TITLE
async route matchers

### ISSUE THREAD

**Issue by eikster-dk** [sveltejs/kit#4609]
### Describe the problem

I got an usecase where I wanted to make slug based routing where I need to be able to ask an backend if the slug exists before showing a page, the page could either be a CMS based page or an ecommerce product.

I was hoping that the matchers for routing was able to perform this action for me but as soon as I return a promise it's not working. 

what I want is to be able to route like
```
[category=categorymatching]/index.svelte
[category=categorymatching]/[product].svelte
[cms=cmsmatching]
```

### Describe the proposed solution

Allow the match function to return a promise

### Importance

would make my life easier

**Comment by Conduitry** [comment]
This is against the design goals of matchers. Even if async matchers were allowed, you'd still need to make sure your code worked on the server and in the browser, which would be non trivial.

If you have a situation like this, you can do the appropriate checks in a single `load` function and then render the relevant other components from that page.

**Comment by eikster-dk** [comment]
@Conduitry correct me if I'm wrong I'm still pretty new to Svelte/kit, but before the matchers it looked like I could perform a `fallthrough` in a load function on a given page to keep pages nicely seperated while having slug based routing. 

Now I'm required to combine all components into one page, it seems to me that it could become messy. 

Isn't there a way to make something like the above possible, so you can have cleanly seperated pages with a single purpose?
