### ISSUE TITLE
Application code shouldn't be executed during build even when prerendering is not explicitly disabled

### ISSUE THREAD

**Issue by AradAlvand** [sveltejs/kit#4619]
### Describe the bug

This bug was explained in #4492, and #4604 was supposed to solve the issue, but it only does so if you explicitly disable prerendering in the configuration.
But it still makes no sense to me why SvelteKit would execute application code during build by default for adapter-node.

### Reproduction

Described in #4492

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 983.98 MB / 7.89 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73
    @sveltejs/kit: ^1.0.0-next.312 => 1.0.0-next.312
    svelte: ^3.46.4 => 3.47.0
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
This is not a bug, nor is it a recent change. If prerendering is enabled, SvelteKit needs to run your app. If you don't want to run your app during build, disable prerendering.

**Comment by AradAlvand** [comment]
But should prerendering be disabled by default?! Then why do you need to explicitly set `config.kit.prerender.enabled` to `false` for this to take effect?!
