### ISSUE TITLE
[docs] Wrong element is highlighted in the sidebar menu

### ISSUE THREAD

**Issue by malinowskip** [sveltejs/kit#4620]
### Describe the problem

Currently, if you directly navigate to a section in the docs, the _preceding_ item is marked as active.

https://user-images.githubusercontent.com/47485431/163463849-4c5e825c-9504-45b4-ad9c-4b73073fe912.mov

This is happening because the active element in the sidebar menu is determined by the page position (i.e. the respective heading’s position in the viewport); if you navigate to a section directly, its heading is not high enough in the viewport to trigger a change.

### Describe the proposed solution

Change the value from 40 to 102 or greater:
https://github.com/sveltejs/kit/blob/c46e08738199af8054c6496b921e118413046aa2/sites/kit.svelte.dev/src/lib/docs/Contents.svelte#L49

I guess the value should be tied to this CSS rule: https://github.com/sveltejs/kit/blob/c46e08738199af8054c6496b921e118413046aa2/sites/kit.svelte.dev/src/lib/docs/client/docs.css#L117

### Importance

would make my life easier

**Comment by pto1026** [comment]
I'd like to resolve this issue, can you please assign it to me
