### ISSUE TITLE
URI Encoding inconsistent between SSR and Browser routers

### ISSUE THREAD

**Issue by Bluebie** [sveltejs/kit#4629]
### Describe the bug

A reasonable user would expect the SvelteKit router to behave the same way in the ssr and browser contexts, regarding uri encoding in route params. This currently isn't the case.

Sample below demonstrates main issue, but also note this inconsistency appears in load functions too, depending if they are run in ssr or browser side

### Reproduction

```
git clone https://github.com/Bluebie/sveltekit-url-params-encoding-issue.git
cd sveltekit-url-params-encoding-issue
npm i
npm run dev
```

Open browser to `http://localhost:3000/test/foo` and click the demo links in the list on the bottom of the page to see some examples of how decoding is inconsistent.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 80.17 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    npm: 8.5.5 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Edge: 100.0.1185.39
    Firefox: 97.0.1
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.312 
    svelte: ^3.46.0 => 3.47.0
```

### Severity

serious, but I can work around it

### Additional Information

Example output of `src/routes/test/[param].svelte` when navigating to `http://localhost:3000/test/why%3Ais%3Acolon`

<img width="1044" alt="Screen Shot 2022-04-15 at 5 51 31 pm" src="https://user-images.githubusercontent.com/12768/163542055-39cb7674-1d29-4a9a-a516-8d60ff2d1d67.png">

**Comment by YazanDuelLinks** [comment]
the current behavior is of decodeURI instead of decodeURIComponent

**Comment by rdela** [comment]
see #5029 / #5056

**Comment by benmccann** [comment]
I added a browser test with a page like this in the Kit repo and it's passing. However, I upgraded the test project and it's still failing ([PR here](https://github.com/Bluebie/sveltekit-url-params-encoding-issue/pull/1)). Not quite sure what I'm missing...

**Comment by benmccann** [comment]
Ah, so `why:is:colon` is a perfectly valid URL parameter and doesn't need to be encoded. The sample app is encoding it anyway and I guess we're doing a decoding on the server, but not the client

**Comment by benmccann** [comment]
We have a `decode_params` method only on the server: https://github.com/sveltejs/kit/blob/bde443dad85868defb9bdfdc8f0a2347a2451582/packages/kit/src/runtime/server/utils.js#L24

**Comment by benmccann** [comment]
fixed here: https://github.com/sveltejs/kit/commit/d02f1f25ac8acb29e21a06b94418c333928fb9bb
