### ISSUE TITLE
index@layout.svelte does not handle the default GET request if index.ts is present

### ISSUE THREAD

**Issue by angryziber** [sveltejs/kit#4647]
### Describe the bug

If `index.svelte` uses a non-default layout, then it is not called if `index.ts` is present with it's own get() implementation.

### Reproduction

Just create both files - the index.ts will be called to handle GET request by default.

### System Info

```shell
1.0.0-next.314
```

### Severity

serious, but I can work around it

**Comment by mrkishi** [comment]
Could you provide a reproduction?

It's not clear what you really meant, but `index@layout.svelte` requires an `index@layout.ts` file as a page endpoint (_not_ `index.ts`).

**Comment by angryziber** [comment]
Repoduction:

* Create __layout-hello.svelte
* Create index@hello.svelte
* See that you see html content produced by index@hello.svelte
* Create index.ts with get function inside
* See that you no longer able to see content produced by index@hello.svelte, but only json returned by index.ts's get function
* Rename index@hello.svelte to index.svelte
* See that you can see it's content again in the browser

**Comment by dummdidumm** [comment]
Closing as this works as expected. As @mrkishi pointed out, `index@layout.svelte` requires an `index@layout.ts` file as a page endpoint, _not_ `index.ts`.
