### ISSUE TITLE
hooks.js handle not called in in run preview, only run dev

### ISSUE THREAD

**Issue by christopherreay** [sveltejs/kit#4648]
### Describe the bug

in the documentation it states the the `handle` hook will be called before each call to an end point.

when running an app usiing `npm run dev`, the handle function is called as expected. Once the same app is `npm run build` and then `npm run preview`, the site that is generated does not call the handle hook when loading a page with a page endpoint. 

Sometimes the site doesnt appear to make any network calls at all, when calling a page with a page endpoint. Sometimes it does.

So to be clear, I have made a repo that shows that pageEndpoint is not being called when site served with `npm run preview`. If this is desired behaviour, then I will continue to work on the repo to try and produce the behaviour where `__data.json` is being called without `hooks/handle` being called first (ive put a screenshot of this in the section at the bottom of this issue). It also sometimes is the case in my main app that a page with a pageEndpoint is loaded without any network communications. But then sometimes `__data.json` is called over the network, which is getting a result without `hooks/handle` being called at all. which I do not understand, having looked at the source. This never happens in `npm run dev`

### Reproduction

https://gitlab.com/christopherreay/sveltekit_testHookPageEndpoint/-/commit/6a99222100825eb0080639b75ae55332ee90997a

#### `npm run dev`
```bash
HOOKS: handle:  Request {
  size: 0,
  ... AS EXPECTED
}
ENDPOINT /index.js, get: {
  request: Request {
    size: 0,
    ... AS EXPECTED
  } 
} 
```

#### `npm run preview`
```bash
> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
lancaster_app_user@mcsSustenance:~/context/lancasterApp/sveltekit_testHookPreview$ npm run preview

> sveltekit-testhookpreview@0.0.1 preview
> svelte-kit preview --port=60000

  SvelteKit v1.0.0-next.314

  local:   http://localhost:60000
  network: not exposed
  network: not exposed
  network: not exposed

  Use --host to expose server to other devices on this network

> THERE IS NO OUTPUT AT ALL ON THE SERVER CONSOLE WHEN THE INDEX PAGE IS LOADED IN THE BROWSER When localhost:60000/ is loaded in the browser window (which is indeed very very fast :) ), there is no output in the console. Either in the browser console, or on the server side console. I would expect there to be output on the server console. In fact the front end does not make any network calls at all. Sometimes my app does make calls to __data.json, but it *does not* make calls to hooks/handle
```

### System Info

```bash
System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
    Memory: 147.52 MB / 981.37 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.8.0 - ~/.nvm/versions/node/v17.8.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v17.8.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.314 
    svelte: ^3.46.0 => 3.47.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Sorry for the high priority, but I am unable to deploy my app, and I have tried speaking to people in the discord. No one has heard of anything like it.

having reviewed the code here: https://github.com/sveltejs/kit/blob/32a700a204e108a1fdceeffc7727bdb340335a3e/packages/kit/src/runtime/server/index.js#L168, I dont see how it is possible for __data.json to be called without calling hooks/handle. I have got screenshots of this clearly happening on my main app repo.

I have tried using the -node adapter and building and running as production, same results.

When `npm run build` is called, the end points and the handle hook are called for each page, during SSR... however... given the documentation, there seems to be no reason why an endpoint wouldnt be called during page load of an already built site. In fact, I dont understand why the SSR pages are built during `npm build`

I *can* understand that, but it doesnt it at all into what I think that sveltekit is supposed to be doing.

I have read the source code, and I do not see how it is possible for __data.json to be called for a page endpoint without hooks/handle being called as well, which is what is happening on my full app.

If all this behaviour in this repo is doing what you expect it to (which will be very interesting to me), then I will work in more detail on what is happening in my full app, where __data.json is being called without hooks/handle being called before it

screenshot of `__data.json` being called, wihlst there is no console log from `hooks/handle`
![image](https://user-images.githubusercontent.com/239550/163810372-f81d233d-ca9c-4200-800a-2970500ff700.png)

**Comment by Conduitry** [comment]
It sounds like you're hitting pre-rendered versions of those pages/endpoints, which will not result in `handle` being called at runtime, as described in https://kit.svelte.dev/docs/hooks#handle

**Comment by christopherreay** [comment]
So that would make sense if:

`pageendpoints` are a special kind of endpoint that are only called during SSR - PreRender

unless, the pageEndpoint is dynamic? in which case they must be called and memoised for each specific URL?

**Comment by christopherreay** [comment]
in the documentation you linked to it says: 
> It receives an event object representing the request and a function called resolve, which invokes SvelteKit's router and generates a response (rendering a page, or invoking an endpoint) accordingly.

**Comment by christopherreay** [comment]
In fact, in the pageEndpoints documentation, it is stated clearly that fetch is called on the endpoint:

> https://kit.svelte.dev/docs/routing#endpoints-page-endpoints
> If an endpoint has the same filename as a page (except for the extension), the page gets its props from the endpoint — via fetch during client-side navigation, or via direct function call during SSR.

**Comment by christopherreay** [comment]
Ok, yes, that is the case. Thank you very much.

I would suggest that the documentation on pageendpoints points to this documentation here: https://kit.svelte.dev/docs/page-options#prerender

would make things very clear

tytyty

Also, where do we donate to this project?

**Comment by christopherreay** [comment]
And one last question. Would it be reasonable to pre-render a page, and then have it collect information using a standalone enpoint, and update the contents of the page?

This would affect the SEO of the page, but would it be faster?

I very much thought that SvelteKit was rending pages on the server side before sending them to the browser, and then hydrating them with data.

Are there two kinds of SSR then? one is SSR-Prerender, and the other is SSR every page load?

**Comment by christopherreay** [comment]
Also, what is the meaning of this: https://kit.svelte.dev/docs/loading
within this context?

**Comment by christopherreay** [comment]
So aye, in the documentation the phrase "Server Side Rendering" and "Pre-Rendering" have been difficult for me to grasp. I was working from a page that was prerender true, from the skeleton.

It all makes sense, but may I suggest a PR to make it clear to people when pre-rendering affects SSR

**Comment by Rich-Harris** [comment]
Closing this as the prerendering documentation has since been updated, and includes details on how `+server.js` routes are handled https://kit.svelte.dev/docs/page-options#prerender-prerendering-server-routes
