### ISSUE TITLE
CSS for root layout is loaded even after reset

### ISSUE THREAD

**Issue by ricardobeat** [sveltejs/kit#4670]
### Describe the bug

CSS imported from the root `__layout.svelte` file is unexpectedly loaded in routes where the layout has been reset.

### Reproduction

I have a CSS import in the main `__layout.svelte`:

```js
import "../global.css";
```

And then a layout reset in a nested route:

```
order/
  __layout.reset.svelte
  index.svelte
```

where `__layout.reset.svelte` is a file with a single `<slot />`

When visiting the `/order` route, the generated root styles at `__layout.svelte-a576ae6a.css` are still loaded, introducing undesired rules.

To make matters worse, this _only happens in the production build_, so could not be spotted in dev, and the base CSS takes precedence over any styles defined in the reset file.

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 102.80 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0.1
    Safari: 15.4
```

### Severity

serious, but I can work around it

**Comment by rmunn** [comment]
`__layout.reset` was removed in release `next.306`; see https://github.com/sveltejs/kit/pull/4388 and https://kit.svelte.dev/docs/layouts#named-layouts for the new way to do it.
