### ISSUE TITLE
kit start mounting wrong node

### ISSUE THREAD

**Issue by john-michael-murphy** [sveltejs/kit#4685]
### Describe the bug

For a number of reasons related to platform integration, nytimes wraps sveltekit html output in a template that will occasionally hoist script tags into the `body` tag:

src/hooks.js
```javascript
/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
	return resolve(event, {
		transformPage: ({ html }) => {
                          // wraps the output in the nytimes renderer, which sometimes 
                          // hoists script tags contained in html out of the generated component html and into the <body> tag.
			return render_page_in_template(html);
		},
	});
}
```

Since [kit now assumes that the mount script is always an immediate child of the root mount node](https://github.com/sveltejs/kit/blob/28139749c4bf056d1e04f55e7f955da33770750d/packages/kit/src/runtime/server/page/render.js#L161), this means that kit will mount the `body` node instead of the parentNode defined in app.html template. 

In practice this means that if we wanted to embed a component generated by kit into the NYTs homepage (which hoists scripts), we're at risk of that component blowing out the entire DOM. 

I really like the ergonomics introduced in https://github.com/sveltejs/kit/pull/3674, but I wonder if instead setting `data-hydrate` on `<script  data-hydrate="foo" />` we set it on a tag that's not vulnerable to hoisting `<div  data-hydrate="foo" />`

Thanks so much for all the amazing work y'all have done so far. And thanks in advance for your wisdom on this. 

### Reproduction

In src/hooks.js write a small script that hoists kit script tags out of their default parent node. 

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) x64 Apple M1 Max
    Memory: 2.44 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/bin/nvm/versions/node/v14.18.3/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/bin/nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: 1.0.0-next.305 => 1.0.0-next.305 
    @sveltejs/vite-plugin-svelte: 1.0.0-next.41 => 1.0.0-next.41 
    svelte: ^3.44.0 => 3.46.4 
    vite: ^2.6.10 => 2.8.4
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
I've opened #4698, which solves this, but at the cost of an additional element in all server-rendered HTML. While working on it, it occurred to me that you could probably achieve the same outcome using `transformPage`, I think?

```js
const pattern = /data-hydrate="(.+)"/;

const response = await resolve(event, {
  transformPage: ({ html }) => html
    .replace(/<script[^]+?<\/script>/g, (script) => {
      const match = pattern.exec(script);
      return match ? `<span ${match[1]}/>${script.replace(pattern, '')}` : script;
    })
});
```

**Comment by john-michael-murphy** [comment]
@Rich-Harris you're so fast! Thank you! 

We're already doing the string manipulation you suggest in the comment. The concern with that approach is that it's modifying an internal sveltekit implementation detail that could change without warning. If y'all are aware of this edge case and don't think anything about the current implementation will change in the future, I'm super happy keeping that string replacing as our final solution! Otherwise, #4698 looks great!

**Comment by john-michael-murphy** [comment]
@Rich-Harris it looks like this may have regressed. Would you recommend we manage the html script ourselves?
