### ISSUE TITLE
Rejected documentation edit pull request

### ISSUE THREAD

**Issue by clarkebishop** [sveltejs/kit#4689]
### Describe the bug

I tried to submit a very small pull request to improve the documentation. But got a very long CI/CD error mentioning a circular dependency. That does not seem reasonable given the small change I made.

The original commit changing the documentation
https://github.com/sveltejs/kit/commit/015b12fd83edc68178251db95d24f34449702d47

The Pull Request workflow
https://github.com/sveltejs/kit/actions/runs/2198644618

I can't see where I might have done something wrong, but if so, please let me know and forgive me for creating an issue.

### Reproduction

See the above links. 

### System Info

```shell
Not relevant
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
You just ran into a flaky test. There's an issue already for the specific test that failed for you at #4681 - the logs linked to in that issue are in fact the very run where you ran into this.
