### ISSUE TITLE
preload header support

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#47]
I tried `npm run dev` as well as `node build; node build/index.js` and didn't see the `link` preload header in the hn.svelte.dev sample app that's available on https://hn.svelte.dev/top/1 today

**Comment by Rich-Harris** [comment]
I looked around for definitive information about whether the HTTP header is better than including the tags on the page. The best I could find was [Addy](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf):

> Preloading via headers _may_ offer a very negligible improvement, but require the document to be committed before processing happens.

In other words it probably isn't worth the additional complexity, so I'll close this
