### ISSUE TITLE
Cannot find module '$lib/...' or '$app/...' from language server for .svelte files in default configuration of sveltekit

### ISSUE THREAD

**Issue by groovy9** [sveltejs/kit#4706]
### Describe the bug

In a fresh install of sveltekit with demo app and typescript, LSP works fine out of the box except for imports from the $ aliases in .svelte files.

These throw a diagnostic such as `Cannot find module '$lib/Counter.svelte' or its corresponding type declarations` and jump to definition does not work for those imported symbols.

These diagnostics disappear if I replace $lib or $app with absolute paths and jump to definition starts working.

These diagnostics DO NOT happen in .ts files, where jump to definition works fine for symbols imported from $app, for example (see src/lib/form.ts in the demo app).

### Reproduction

I'm using a fresh install of Node 16.14.2 LTS straight from the node main page tarball. Fresh global installs of svelte-language-server, typescript-language-server and typescript. Using the Helix editor which has a native LSP client, using the default config that automatically finds svelteserver for .svelte files and typescript-language-server for .js and .ts files.

I set up a new sveltekit project as per instructions on sveltekit main page answering yes for typescript and demo app and no for everything else. Cd to app dir, `npm install`, `npm run dev -- --open`. No changes made to anything.

Edit a .svelte file from the app root dir: `hx src/routes/index.svelte`

As soon as the language server loads, LSP features start working fine but it throws a diagnostic for the line `import Counter from '$lib/Counter.svelte';` that reads: `Cannot find module '$lib/Counter.svelte' or its corresponding type declarations` and jump to definition does not work for that symbol (works fine otherwise for everything else in the same file).

The about.svelte page does the same thing for `import { browser, dev } from '$app/env'; `

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 1.38 GB / 1.94 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/node/bin/node
    npm: 8.5.0 - ~/node/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.37 
    @sveltejs/kit: next => 1.0.0-next.320 
    svelte: ^3.46.0 => 3.47.0
```

### Severity

annoyance

**Comment by bluwy** [comment]
This sounds like an issue with the Helix editor as it's working fine in VS Code. Perhaps it should be reported there?

**Comment by gtm-nayan** [comment]
@bluwy I can recreate this in VSCode as well.

You'd have to open a svelte file before running `npm i`, more specifically before `.svelte-kit` is created. TS files will no longer have the errors after the folder is populated but the Svelte language server doesn't pick up the new files I guess.

**Comment by bluwy** [comment]
👍 perhaps the ts language server wasn't watching references to the generated tsconfig. It looks like OP also cross-posted https://github.com/sveltejs/language-tools/issues/1459 without mentioning it. I'll close this in favour of that then as the fix is likely within language tools.

**Comment by groovy9** [comment]
I'd created the demo app just to test the editor LSP integration.  Since then, I restarted with a blank app and if I add an import from LSP there, it's fine.  Maybe it's something in the demo app specifically, or maybe I lost my mind and never actually did npm install or something.  Regardless, I'm good to go and thanks for your time.

**Comment by fcrozatier** [comment]
Sometimes `npm run check` can help with this error

**Comment by emastho** [comment]
> @bluwy I can recreate this in VSCode as well.
> 
> You'd have to open a svelte file before running `npm i`, more specifically before `.svelte-kit` is created. TS files will no longer have the errors after the folder is populated but the Svelte language server doesn't pick up the new files I guess.

*You'd have to open a svelte file before running `npm i`*

Thank you, this should be in the docs
