### ISSUE TITLE
Adapter that produces separate client and server code

### ISSUE THREAD

**Issue by trenta3** [sveltejs/kit#4708]
### Describe the problem

I would like to develop a simple mobile application with SK and I would like to package client code inside the application the user downloads, and keep the server code just serving endpoints requests.

### Describe the proposed solution

The node adapter should have an option that splits client and server code in two different folders, allowing to configure in the client code the origin to which to request pages.

It should be possible to serve client code locally / directly and it should connect to server only for the pages that effectively have an endpoint.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
I'm afraid I don't really understand what you're asking for. The `build` folder (or whatever you decide to call it) generated by `adapter-node` contains the client code in `client` (and your static assets in `static` and prerendered pages in `prerendered`). Can you be more specific?

**Comment by trenta3** [comment]
Oops I'm sorry, I must have not understood something about which things were inside the `.svelte-kit` folders.

For others looking for this,
```bash
mv .svelte-kit/output/prerendered/pages/* .svelte-kit/output/client/
```
produces for me a working client part.
