### ISSUE TITLE
Expose `paths` to `$service-worker` module

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4714]
### Describe the problem

An aside in #2571:

> `src/service-worker.js` can't import `$app/paths` with build errors

That's expected — `$app` modules aren't available in service workers, because in general they don't make any sense in that context. But it might be useful to expose `paths`.

I don't know what the concrete use cases are, but it seems worth having a ticket distinct from #2571. And it's all tree-shakeable and therefore free anyway

### Describe the proposed solution

One of these:

```js
import { paths } from '$service-worker';
```

```js
import { base, assets } from '$service-worker';
```

```js
import { base, assets } from '$service-worker/paths';
```

### Importance

nice to have

**Comment by benmccann** [comment]
I'm not that familiar with service workers. Why do you say `paths.assets` is incompatible with service workers? You can't have a site that loads assets from a CDN and uses a service worker?
