### ISSUE TITLE
Trying to use named layouts in directory names should be a compile-time error

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#4717]
### Describe the problem

Having a path like `src/routes/foo/bar@blah/index.svelte` is accepted, but it is treated the same as `src/routes/foo/bar/index.svelte`. (To get the intended behavior, you need to use `src/routes/foo/bar/index@blah.svelte`.)

### Describe the proposed solution

Having a route like `src/routes/foo/bar@blah/index.svelte` should be a compile-time error. The `@blah` doesn't do anything useful, so we should stop people early rather than letting their app compile and behave in an unexpected way.

Bonus points if the error message tells users what path(s) they should instead be using for their desired layout behavior.

### Alternatives considered

None, really. In an earlier version of named layouts, `src/routes/foo/bar@blah/index.svelte` was supported, but it was removed due to the risk of confusion and the difficulty in documenting what is already a pretty tricky feature to get your head around the first time. That sounds like a good enough argument to me to not solve this another way by instead supporting this syntax.

### Importance

nice to have

**Comment by Mlocik97** [comment]
I see a few problems here too, so I would really really remove it, and throw error... not add support as alternative consider...

imagine having two folders:

bar@blah/
bar/

both have index.svelte file in it...

what will happen?
