### ISSUE TITLE
Can't install svelte-preprocess using node-17.9.0 in Debian 11

### ISSUE THREAD

**Issue by dschalk** [sveltejs/kit#4719]
### Describe the bug

I'll use nvm to revert to node-16 because I get an error message when installing svelte-preprocess. It says, "npm ERR! notarget No matching version found for node@17.9.0." Here's the whole message:

host:~/site5$ 
u@localhost:~/site5$ npm install -D svelte-preprocess
npm WARN idealTree Removing dependencies.svelte-preprocess in favor of devDependencies.svelte-preprocess
npm ERR! code ETARGET
npm ERR! notarget No matching version found for node@17.9.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/u/.npm/_logs/2022-04-24T16_36_41_784Z-debug-0.log
u@localhost:~/site5$ 
u@localhost:~/site5$ 
u@localho

### Reproduction

u@localhost:~/site5$ npm run dev

> site7@0.0.1 dev
> svelte-kit dev -p 3005

> Cannot find package 'svelte-preprocess' imported from /home/u/site5/svelte.config.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:910:9)
    at moduleResolve (node:internal/modules/esm/resolve:959:20)
    at defaultResolve (node:internal/modules/esm/resolve:1176:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)

@localhost:~/site5$ 
u@localhost:~/site5$ npm install -D svelte-preprocess
npm WARN idealTree Removing dependencies.svelte-preprocess in favor of devDependencies.svelte-preprocess
npm ERR! code ETARGET
npm ERR! notarget No matching version found for node@17.9.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/u/.npm/_logs/2022-04-24T16_36_41_784Z-debug-0.log
u@localhost:~/site5$ 

### System Info

```shell
Running on Debian 11.
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Works on my machine with Node 17.9.0.

But also, odd-numbered versions go EOL shortly after the next even-numbered version comes out. Node 17 is EOL starting June 1, so you're going to want to stop using it soon anyway, because it won't be getting any bug or security fixes.

**Comment by Rich-Harris** [comment]
Please open an issue on the svelte-preprocess issue tracker - thanks

**Comment by dschalk** [comment]
Thanks. svelte-preprocess installed flawlessly with node-8.6.0.

**Comment by dschalk** [comment]
PS I'm mostly using node-18.0.0 now.
