### ISSUE TITLE
Can't server side render components with props

### ISSUE THREAD

**Issue by Explosion-Scratch** [sveltejs/kit#4736]
### Describe the problem

Currently in Sveltekit there is no way to server side render a component with props. Here's an example of a (hypothetical) component:

```svelte
<! -- Component.svelte -->
<script context="module">
  import {onMount} from "svelte";
  export let slug = "";
  let someFetchedData = {};
  onMount(() => {
      someFetchedData = await fetch(`api/route/${slug}.json`).then(r => r.json())
  })
</script>
{someFetchedData.title}
{someFetchedData.body}

<!-- index.svelte -->
<Component slug="test"></Component>
```

### Describe the proposed solution

Here's an example of the **proposed syntax:**

```svelte
<! -- Component.svelte -->
<script context="module">
  export async function load({fetch, props}){
      return {
          props: {
            someFetchedData: await fetch(`api/route/${props.slug}.json`)
          }  
      }
  }
</script>
{someFetchedData.title}
{someFetchedData.body}

<!-- index.svelte -->
<Component slug="test"></Component>
```

### Importance

would make my life easier

**Comment by andrei0x309** [comment]
Server-side components would be nice. 

Passing through props will be very messy if the component where you want the data is xx layers beneath the page/layout load function...

Also, another pattern without a load function is to have something like `+[component-name].server.ts` where you would be able to run some server-side stuff.
