### ISSUE TITLE
Remove wrapper div tag

### ISSUE THREAD

**Issue by chientrm** [sveltejs/kit#4743]
### Describe the problem

Svelte kit auto wrap the dom tree with a `div` tag which make semantic tags meaningless.
![](https://cdn.discordapp.com/attachments/968165821450973256/968165958072012830/Screen_Shot_2022-04-25_at_10.05.38_PM.png)

### Describe the proposed solution

Add an option to ignore wrapping dom tree with `div` tag

### Alternatives considered

Completely remove the wrapping step.

### Importance

nice to have

**Comment by Conduitry** [comment]
You have control over this by editing `src/app.html`.

**Comment by chientrm** [comment]
> You have control over this by editing `src/app.html`.

Right solution!
