### ISSUE TITLE
bug(dev host binding @next.321): Unable to bind to 0.0.0.0

### ISSUE THREAD

**Issue by ryanrussell** [sveltejs/kit#4745]
### Describe the bug

I am running SvelteKit in a docker container. 

After upgrading to @next.321, I am unable to bind to 0.0.0.0 using `npm run dev` , which prevents access to SvelteKit inside the container

There appears to be a breaking change around `npm run preview` and host #4729 on 321. Perhaps there are some side effects to dev mode binding to '0.0.0.0' or the best practices have changed?

https://github.com/sveltejs/kit/pull/4729

SvelteKit  has been working with `npm run dev --host` to bind to `0.0.0.0` since version ~100. 

## Attempt 1: 
package.json
```json
"scripts": {
    "dev": "svelte-kit dev"
    ...
}
```

```bash
npm run dev -- --host 0.0.0.0

> fs-svelte@0.1.1 dev
> svelte-kit dev "--host" "0.0.0.0"


  SvelteKit v1.0.0-next.321

  local:   http://localhost:3000
  network: http://192.168.1.159:3000

  Note that all files in the following directories will be accessible to anyone on your network: src/lib, src/routes, .svelte-kit, src, node_modules
  network: http://172.17.0.1:3000

  Note that all files in the following directories will be accessible to anyone on your network: src/lib, src/routes, .svelte-kit, src, node_modules
  network: http://172.22.0.1:3000

  Note that all files in the following directories will be accessible to anyone on your network: src/lib, src/routes, .svelte-kit, src, node_modules

```

## Attempt 2: 
package.json
```json
"scripts": {
    "dev": "svelte-kit dev --host 0.0.0.0",
    ...
}
```

```bash
npm run dev

> fs-svelte@0.1.1 dev
> svelte-kit dev --host 0.0.0.0


  SvelteKit v1.0.0-next.321

  local:   http://localhost:3000
  network: http://192.168.1.159:3000

  Note that all files in the following directories will be accessible to anyone on your network: src/lib, src/routes, .svelte-kit, src, node_modules
  network: http://172.17.0.1:3000

  Note that all files in the following directories will be accessible to anyone on your network: src/lib, src/routes, .svelte-kit, src, node_modules
  network: http://172.22.0.1:3000

  Note that all files in the following directories will be accessible to anyone on your network: src/lib, src/routes, .svelte-kit, src, node_modules
  ```
  
  
  Notice the slightly different rendering of 
  ```bash
  # Attempt 1 stdout
  > svelte-kit dev "--host" "0.0.0.0"
  ...
  
  # Attempt 2 stdout
  > svelte-kit dev --host 0.0.0.0

```

### Logs

```shell
In Reproduction.
```

### System Info

```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

node --version
v14.17.0

npm --version
8.3.2
```

### Severity

serious, but I can work around it

### Additional Information

This may be isolated to the `dev` mode

```bash
node build/index.js
```

Still seems to work and bind to 0.0.0.0 from within docker.

**Comment by mrkishi** [comment]
As discussed in Discord, this is likely an issue with their Docker network configuration since the bindings appeared to be correct when passing `--host`, `--host 0.0.0.0`, and a missing `--host` (as seen [on the screenshots on the Discord thread](https://discord.com/channels/457912077277855764/939868205869072444/968360515611033620)).

@ryanrussell will attempt to get to the bottom of it and provide a minimal reproduction if an issue is found in SvelteKit.

**Comment by moritzebeling** [comment]
For me `npm run dev --host` doesn't work,
but when I add this new command to `package.json` it does:
`"dev-host": "svelte-kit dev --host 0.0.0.0",`
