### ISSUE TITLE
Clearly State ENV exposure

### ISSUE THREAD

**Issue by MentalGear** [sveltejs/kit#4746]
### Describe the problem
https://kit.svelte.dev/faq#env-vars
Update docs to clearly state where VITE_ envs are exposed in sveltekit. Being unsure about this may lead to poor security design.

### Describe the proposed solution

A highlighted info that says: VITE_ Envs are exposed to the client ! You might want to use VITE_PUBLIC_KEY to indicate this.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Closing as outdated (environment variables should now be accessed via the [`$env`](https://kit.svelte.dev/docs/modules#$env-dynamic-private) modules, not through `import.meta.env`)
