### ISSUE TITLE
Orientation

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4748]
### Describe the problem

We don't have anywhere in the docs that describes the structure of a SvelteKit app. For example, `app.html` isn't explained anywhere, and `%svelte.head%` and `%svelte.body%` (which should really be `%sveltekit.head%` and `%sveltekit.body%`) aren't documented.

### Describe the proposed solution

An 'Orientation' section near the top of the docs that gives a brief overview of the contents of a project freshly created with `npm init svelte`.

**Comment by Mlocik97** [comment]
"Orientation" as name of section sounds weird/ugly for me, it's like talking about sex orientation... maybe "Structure" for describing structure of whole project folder, and resp. "HTML template" for `app.html` file docs?

**Comment by jchanes04** [comment]
Seconding the choice of "Structure" for the name of this section. I'd recommend including information the common usage of a global.css file inside of `static` + `app.html` `head`. Some of the other parts of the docs could be moved here as well, such as explaining `routes` and `lib`.

**Comment by AleCandido** [comment]
Actually, maybe a more general "Templates" or "Templates structure" sections might be appropriate: not only the basic SvelteKit structure is worth to be documented, but also all the other amenities provided by `create-svelte`, including:
1. the basic difference of the two templates (even a single sentence is fine)
2. references to the documentation for other tools (Prettier, TypeScript, ...) and possible relevant cross-projects ([`prettier-plugin-svelte`](https://github.com/sveltejs/prettier-plugin-svelte), [TypeScript integration](https://svelte.dev/blog/svelte-and-typescript), ...)

Point 2. has somehow interactions with ["Integrations"](https://kit.svelte.dev/docs/additional-resources#integrations), that might be expanded with the references above. Still, I'd mention explicitly everything that is referred and produced by the user facing `create-svelte` bootstrapping package.
At the moment, the easiest way to get an idea about is to have a look at the code (that is clean and templates are well separated, but not the best).

**Comment by carusog** [comment]
I like @AleCandido idea of an overview section. Probably before anything else, optimally between "Introduction" and "Web Standards" to explore the "Project Structure" that has been generated by the command listed in "[Introduction > Getting Started](https://kit.svelte.dev/docs/introduction#getting-started)".

That "Project Structure" would be a great walk through that I was missing the first time I've read docs. 
Anecdotally, to better understanding Svelte Kit, I've created myself locally both JS and TS versions of the same starters code just to compare and to learn differences between their folder structures.

@Mlocik97 (or anybody else) if you start working on it, I'd love to join you. Anytime.

**Comment by Mlocik97** [comment]
I started writing it, but didn't had much of free time over weekend... now I have some work to do, so I will continue writing it maybe at friday or saturday.

**Comment by carusog** [comment]
> I started writing it, but didn't had much of free time over weekend... now I have some work to do, so I will continue writing it maybe at friday or saturday.

Happy to join you if you will. Just drop me a message. 👍

**Comment by Mlocik97** [comment]
https://github.com/Mlocik97/kit/blob/master/documentation/docs/01-project-structure.md

Here it is. If you want, you can create PR or point on some changes... I'm actually not really good in writing docs.
