### ISSUE TITLE
Package now compiles Typescript files to CJS instead of ESM

### ISSUE THREAD

**Issue by jacob-8** [sveltejs/kit#4764]
### Describe the bug

Upgrading from @sveltejs/kit@1.0.0-next.314 to @sveltejs/kit@1.0.0-next.315 will change the output of svelte-kit package as follows:
 
![image](https://user-images.githubusercontent.com/7559478/165654223-72f2ebdc-6b3c-45e1-98ed-3d48f29d7a4f.png)

![image](https://user-images.githubusercontent.com/7559478/165654318-67ad98d3-21e9-410a-b835-b45fdd67629a.png)

My package is now broken when trying to install in another app (`ReferenceError: exports is not defined` in reference to an action defined in a .js file) if I upgrade SvelteKit and I'm forced to stay .314. 

### Reproduction

- Clone https://github.com/jacob-8/svelte-pieces/
- `pnpm i`
- `pnpm package` - look at any compiled .js filed inside /package
- update to @sveltejs/kit@1.0.0-next.315 or higher
- `pnpm i`
- `pnpm package` and inspect different results in compiled .js files in /package

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 1.14 GB / 11.77 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.50)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.40 => 1.0.0-next.40
    @sveltejs/kit: 1.0.0-next.314 => 1.0.0-next.315
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.41 => 1.0.0-next.41
    svelte: ^3.47.0 => 3.47.0
```

### Severity

blocking an upgrade

**Comment by tcc-sejohnson** [comment]
Weird... I just checked the changelog for 314 => 315, and [this is the only line I could possibly see that might cause this issue](https://github.com/sveltejs/kit/blob/c8f71e3191015d74a5ac446e064b5d21aa408500/packages/kit/rollup.config.js#L57), but it shouldn't be the problem. I'll try to look further into this when I get home to at least triage.

**Comment by dummdidumm** [comment]
Possibly related #4460

**Comment by gtm-nayan** [comment]
This commit seems like the culprit, changelog didn't pick up on it https://github.com/sveltejs/kit/commit/2bb2ab094e18a4554b367252aea7c25ae4a75803

**Comment by gtm-nayan** [comment]
Oh, it's a create-svelte change, that's why

**Comment by dummdidumm** [comment]
Thanks @gtm-nayan that might be indeed the culprit. If you set target and lib to what was generated before, does the error go away?

**Comment by jacob-8** [comment]
Thank you, all! I create a new svelte-kit app and copied in the default compilerOptions from the j/tsconfig.json file and all is working as expected using this tsconfig:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/7559478/165690456-3d746524-bde1-4b77-a97e-7fa217baf25b.png">

I know it's not 1.0, but it'd be nice for that to be documented somewhere as breaking change. I had already scoured the docs and changelogs ahead of posting my bug but it wasn't there of course.
