### ISSUE TITLE
Ability to conditionally set sveltekit:noscroll

### ISSUE THREAD

**Issue by thegrumpysnail** [sveltejs/kit#4793]
### Describe the problem

I have a component that renders an anchor with other elements inside. I originally needed the sveltekit:noscroll attribute set in all cases, but I recently ran into a scenario where I didn't want sveltekit:noscroll to be defined on the anchor element. I discovered that there is no way (that I could tell) to conditionally disable the sveltekit:noscroll attribute in that one case. Looking at the code, it seems to check for the existence of the attribute only, instead of optionally checking its value.

### Describe the proposed solution

I would like to be able to use sveltekit:noscroll with an optional value -

This would still work:

```js
<a { href } sveltekit:noscroll></a>
```

This would also work:

```js
<script>
  export let noscroll = true;
</script>

<a { href } sveltekit:noscroll={ noscroll }></a>
```

### Alternatives considered

The alternative is that I have to either make an exact copy of the component except without the sveltekit:noscroll, or remove the anchor and create two new parent components, one with and one without noscroll. These aren't deal breakers, but it is unnecessarily chatty for just wanting to make an attribute conditional.

### Importance

nice to have

**Comment by Conduitry** [comment]
You can do this like you'd conditionally set any attribute on an element in Svelte (that the browser doesn't recognize as a known boolean attribute) - `sveltekit:noscroll={noscroll || null}`.

**Comment by thegrumpysnail** [comment]
Oh geesh, I feel like an idiot, @Conduitry. I assumed `false` would behave the same way. It never occurred to me to use `null` or `undefined`. Thanks a bunch for the help!
