### ISSUE TITLE
GA4 property breaks navigation

### ISSUE THREAD

**Issue by Renkas** [sveltejs/kit#4796]
### Describe the bug

Using GA4 property on SvelteKit project forces every navigation to reload page from server.

### Reproduction

Just add GA4 property to your project. Either put the code snippet to app.html directly or use some other way to include it, behaviour is the same.

Same problem when you are in dev mode or run built code in production.

This was working fine about a week ago. But something has changed.
It's probably not an issue in SvelteKit and is caused by some change in Googles code. But I have no idea on how to debug this further and/or how to get Google to look into this. Hopefully someone here can investigate this further.

### System Info

```shell
not applicable
```

### Severity

blocking all usage of SvelteKit

**Comment by babichjacob** [comment]
Please provide a reproduction per the instructions in the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. **Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable.** If no reproduction is provided, the issue will be closed.

**Comment by Renkas** [comment]
Repro: https://stackblitz.com/edit/sveltejs-kit-template-default-yvpfdc?file=src%2Fapp.html&terminal=dev

**Comment by babichjacob** [comment]
The issue doesn't seem to be present in the reproduction for me. All navigation is client side (where expected).

**Comment by np-nam** [comment]
Confirmed to have the same issue. I didn't have time to debug so I just opted out and using umami instead.

**Comment by antony** [comment]
I'm not seeing this in the reproduction. We have been using GA4 on our sites for a while and haven't noticed the issue either.

Can you provide a loom (or equivalent) of you navigating your repro and seeing page reloads?

**Comment by Renkas** [comment]
odd thing is that in reproduction  I first had this issue. And later it dissapeared ...

In my own local dev and prepreoduction (it's not live yet) environments I also still have this issue.

@np-nam maybe you have better luck on creating a reproduction?

**Comment by np-nam** [comment]
@Renkas I've just added GA4 code back and the issue is gone.

**Comment by Renkas** [comment]
It seems to have been fixed by itself. Probably Google changed things on their end?

Anyway I'll close the issue right now.
