### ISSUE TITLE
Allow externalFetch to also proxy endpoint routes

### ISSUE THREAD

**Issue by maraisr** [sveltejs/kit#4800]
### Describe the problem

When dealing with endpoint routes `routes/things.ts` and a `export const post = () => {..}` — it would be nice to also allow externalFetch to have a part there.

eg

```js
export const post = async ({params, fetch}) => {
   await fetch('https://example.com/do-work')
   return {status: 200}
}
```

### Describe the proposed solution

allow externalFetch to also be plumbed into endpoint routes. Why? Much like https://github.com/sveltejs/kit/pull/4792 is doing, allow Cloudflare service bindings to be called in there.

### Alternatives considered

hooks.ts is just a module, maybe;

```ts
// hooks.ts

export let env;

export const handle = ({event}) => {
 // other defaults
 env = event.platform.env;
}

// routes/things.ts

import {env} from '../hooks';

export const post = async ({params}) => {
   await env.API.fetch('https://example.com/do-work')
   return {status: 200}
}
```

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
I'm confused.

```ts
import type { RequestHandler } from '@sveltejs/kit';

export const get: RequestHandler = async () => {
	const resp = await fetch('https://jsonplaceholder.typicode.com/posts/1');
	const json = await resp.json();
	return {
		body: {
			post: json
		}
	};
};
```

This will work. What are you saying is missing?

**Comment by maraisr** [comment]
that fetch is `globalThis.fetch` right. Which isn't the same as `env.MY_SERVICE.fetch` that Cloudflare Workers Service Bindings gives you. And the only place to access this is with `event.platform.env`. Which isn't available to endpoint routes.

Hence the suggestion to allow endpoint routes get access to externalFetch to allow that to happen all in one place.

eg.

```diff
import type { RequestHandler } from '@sveltejs/kit';

- export const get: RequestHandler = async () => {
+ export const get: RequestHandler = async ({ fetch }) => {
	const resp = await fetch('https://jsonplaceholder.typicode.com/posts/1');
	const json = await resp.json();
	return {
		body: {
			post: json
		}
	};
};
```

**Comment by tcc-sejohnson** [comment]
You can't [use this documented approach](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare#environment-variables)? Looks like it should be available on `platform.env.BLAH.fetch` or `platform.context.BLAH.fetch` (sounds like probably `env`. Is it not there? If so, that's probably the feature request. (I don't use Cloudflare, so I'm not an expert here. Just reading the adapter docs. 😃)

```
export async function post({ platform }) {
  const counter = platform.env.BLAH.fetch('https://blargh.what.com');
}
```
