### ISSUE TITLE
Do page endpoint need to sit in separate files?

### ISSUE THREAD

**Issue by Beiri22** [sveltejs/kit#4813]
### Describe the problem

Imaging the page ```testpage[id=integer]-[code=letter]@somelayout.svelte``` and its page endpoint ```testpage[id=integer]-[code=letter]@somelayout.js``` -- for me this seems redundant and error prone. Both are linked together; the page endpoint is not called from other pages.

### Describe the proposed solution

So why not putting all into one file? Couldn't we just have an ```<endpoint>``` - tag inside a svelte page? (Or further - when the page endpoint contains e.g. a get and post handler -> this could be simplyfied by ```<endpoint get>``` and ```<endpoint post>```. Too naive?

### Importance

would make my life easier

**Comment by gtm-nayan** [comment]
See: alternatives considered section of https://github.com/sveltejs/kit/issues/3532

**Comment by dummdidumm** [comment]
Closing as this has been considered and decided against, see the issue link above
