### ISSUE TITLE
Allow encode request handler body to base64

### ISSUE THREAD

**Issue by chientrm** [sveltejs/kit#4817]
### Describe the problem

Imagine I have this `index.ts`:
```js
export const get: RequestHandler = async () => {
	const data = { name: 'bob', age: 24 };
	return { body: { data } };
};
```
and `index.svelte`
```svelte
<script>
export let data;
</script>
```
Now when I browse `index` and inspect source, there will be an ugly `const data = { name: 'bob', age: 24 };` in a `<script>` tag.

### Describe the proposed solution

I suggest an option to allow auto encode request handler body to base64 and decode on the svelte template so when we inspect html, we would see
```html
<script>const data = 'eyBuYW1lOiAnYm9iJywgYWdlOiAyNCB9';</script>
```
Which is a lot more friendly for inspector.

### Alternatives considered

Keep the data object raw in `development` environment and auto encode in`production` build.

### Importance

nice to have

**Comment by benmccann** [comment]
encoding and decoding would likely be less performant. it's also less human readable so I'm not sure why you'd call it less "ugly"...

**Comment by chientrm** [comment]
> encoding and decoding would likely be less performant. it's also less human readable so I'm not sure why you'd call it less "ugly"...
In my case, the data object can be around 100 KB 😄. The amount of `{` and `[` will make the overall codeblock hard to read while a right hand side of base64 string will make the total codeblock very nice to read.
I'm not sure about performance since I don't really understand it 😶‍🌫️

**Comment by benmccann** [comment]
This isn't something we'd implement for the requested reason
