### ISSUE TITLE
Make `adapter-static` zero-config by detecting platform

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4818]
### Describe the problem

We've encountered Vercel users using `adapter-static` instead of `adapter-vercel` (or `adapter-auto`) to deploy their fully-prerendered sites, the result being that they have to mess around with config (changing `public` to `build`, and fiddling with `cleanUrls`). It's likely that some users of other zero-config platforms (currently Netlify and Cloudflare Pages) are in a similar situation.

Using `adapter-static` is basically unnecessary given that the same pages will be prerendered whatever adapter you use (the only difference being that `adapter-static` lets you specify a fallback page, which is unnecessary in these cases). It would be helpful therefore if we steered people back towards `adapter-auto`, making configuration unnecessary.

### Describe the proposed solution

In `adapter-static`, we could use the same platform detection logic in `adapter-auto`...

https://github.com/sveltejs/kit/blob/b2c37078ae109f63c6646e1e1e5752fb54582aa5/packages/adapter-auto/adapters.js#L1-L17

...to detect that someone should just use `adapter-auto` or the adapter specific to their platform.

### Alternatives considered

Make `adapter-static` somehow work in a zero-config way on the platforms in question.

### Importance

nice to have

### Additional Information

Couple of caveats: functions will still be created for endpoints and for pages with dynamic parameters. Those functions will never be invoked (unless someone requests something that wasn't prerendered), but there may be costs associated just with creating them. We can mitigate this by declaring endpoints `prerenderOnly` or something, but not eliminate it.

On Netlify (when using Edge Functions) and Cloudflare Pages, the main handler will still be invoked (since it sits in front of requests for static assets), and there _is_ a cost to that.

As I write this, I'm starting to wonder what universally zero-config `adapter-static` would look like.

**Comment by stephane-vanraes** [comment]
While I do understand the problem, this solution might bring some other problems, namely in debugging.  If a build fails (for whatever reason) and a user checks the build logs, they might be confused to see something like

> 7:21:37 PM: > Using @sveltejs/adapter-cloudflare

even if they are using `adapter-static`.  This could lead them to look for a problem in their configuration, possibly setting them on the wrong path. (This could of course be mitigated if the logging would include a line stating that it picks another adapter)

**Comment by jrmoynihan** [comment]
Definitely agree. It wasn't clear that `adapter-auto` can deploy really easily to Vercel and that the platform adapters are for more custom config. Once I saw how smooth that process can be, it was an easy switch.

In general, the Kit 1.0 might need some a) more detailed docs and/or b) examples that break into more specific (but common) use cases. Finding the Svelte/Kit "blessed" way to do [X] should be a little easier.

**Comment by gbibeaul** [comment]
Hello! I'm looking for a good first issue and this pops out. Makes sens to pick it up as a first time contributor?

**Comment by Rich-Harris** [comment]
@gbibeaul definitely, thanks — though I actually think the initial idea of telling people to use `adapter-vercel` etc is the wrong one, since there _are_ reasons you might want to use `adapter-static` (i.e. you don't want to create functions, and you don't want a Cloudflare Worker/Netlify Edge Function to sit in front of your static assets).

So I think we probably want to do something like [this](https://github.com/sveltejs/kit/blob/369ce25ddaafc5075c144edf4bec53637f0fed54/packages/adapter-static/index.js#L10)...

```diff
-export default function ({ pages = 'build', assets = pages, fallback, precompress = false } = {}) {
+export default function ({ pages = 'build', assets = pages, fallback, precompress = false } = get_defaults()) {
```

...where `get_defaults` selects from a bunch of platform presets like

```js
const defaults = [
  {
    name: 'Vercel',
    test: () => !!process.env.VERCEL,
    options: () => ({
      pages: 'public',
      assets: 'public'
    })
  },
  // ...
];
```

(and communicates to the user that that's what's happening). What do you reckon?

**Comment by gbibeaul** [comment]
@Rich-Harris Yes I feel this is a better option!

It also helps document suggested best practises for some platforms that people won't have to think about. I'll grab the issue! I'll probably reach out for some guidance on what the defaults should be like.

**Comment by Rich-Harris** [comment]
Another dimension on which adapter-static isn't currently zero-config: https://twitter.com/bartveneman/status/1530285724402176001

<img width="586" alt="image" src="https://user-images.githubusercontent.com/1162160/170785921-005e2c71-b2d3-4db3-add5-8b206a1acc31.png">

Ideally we'd emit the relevant configuration where possible. Not sure exactly what that looks like but it would save some head-scratching.

**Comment by Rich-Harris** [comment]
I guess one solution in the Vercel case would be targeting Build Output API directories rather than `public` in the Vercel case, and also writing a `config.json`. Seems like a bit of a scenario-solve though
