### ISSUE TITLE
`getStaticPaths()` for dynamic route?

### ISSUE THREAD

**Issue by Amber-Bird** [sveltejs/kit#4820]
### Describe the problem

I'm using dynamic routing to create pages that gets all its props from a database where the values doesn't change much. So almost all routes can be known at build time. Creating each path by hand would be a hassle so I opted for dynamic routing instead. Currently I'm using the load function to fetch data on request but I think it might be faster with SSG. But as far as I know, there's no way of prerendering dynamic route with static paths.

### Describe the proposed solution

Something like Next.js `getStaticPaths()` where static paths can be specified to preform SSG during the build phase.

### Importance

nice to have

**Comment by Conduitry** [comment]
If there is a link in the SSR'd HTML to a given page, it will be rendered during static site generation even if it has a dynamic route. `kit.prerender.entries` (https://kit.svelte.dev/docs/configuration#prerender) also lets you specify additional crawling entry points.
