### ISSUE TITLE
Supporting streaming SSR in the future

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4830]
### Describe the problem

Currently, SvelteKit renders HTML in one go, which I tend to think is the better choice despite that being a minority opinion (you can't set the response status code once you've started sending the body, and you generally don't know for sure what the status code is _until_ you've rendered the body, so AFAICT streaming implies 200-everything-and-hope-for-the-best).

It might be worth preparing for a world in which a) we want to give people the option to stream, and b) it's possible to set status codes late (which I understand is under active discussion), in which case streaming HTML makes more sense to me.

There are currently three obstacles that I'm aware of:

## Svelte

Svelte itself doesn't have a streaming render mode, and without it there's not much benefit to streaming the non-Svelte parts of a page (other than optimising TTFB, I guess, which isn't a particularly meaningful achievement). That could change — we could introduce APIs that allowed us to (for example) resolve `{#await}` blocks rather than rendering the pending state:

```js
Component.stream(
  (error, chunk) => {
    if (error) {
      // literally no idea what to do here tbh
    } else {
      controller.enqueue(chunk);
    }
  },
  {
    timeout: 1000
  }
);
```

In SvelteKit, we could wrap nested routes in `{#await}` blocks that wait for `load` functions to resolve, allowing us to render the nav bar before the main content is ready, etc.

> Returning a `ReadableStream` directly from `Component.stream` feels more standards-flavoured, but I'm not sure it would actually be an ergonomic improvement. I reserve the right to change my opinion in future, but for now it's an immaterial detail

## `<svelte:head>`

If we stream everything in order, [`<svelte:head>`](https://svelte.dev/docs#template-syntax-svelte-head) puts us back to square one — we can't render the `%svelte.head%` in `src/app.html` until we've finished rendering the body and know that we won't encounter any more `<svelte:head>` elements.

Two options spring to mind: we somehow gather head content prior to rendering, or we stream out of order. The first option makes sense in some cases, but not all (e.g. a document title often depends on the same data as the body content), and would involve some fairly substantial design changes.

The second option would be easier (render a placeholder element to the head, and write a small `<script>` that inserts HTML adjacent to the placeholder as `<svelte:head>` elements are rendered), though out-of-order streaming makes me a little nervous — it relies on JavaScript (albeit not in the inherently brittle way that 'relies on JavaScript' usually implies), and I would expect it to be significantly worse for SEO, unless we did something tricksy like defaulting to in-order streaming if the UA is a known search engine bot.

## `transformPage`

People use `transformPage` for making arbitrary tweaks to the HTML (like replacing a `<html lang="%lang%">` placeholder), and the API assumes the whole page is rendered.

In a streaming world this API makes no sense. We need to transform the stream instead, which in the general case is [rather more complicated](https://github.com/jakearchibald/isserviceworkerready/blob/master/src/demos/transform-stream/edge-cases.md) than something like a naive `transformPageChunk`.

---

This is all fairly vague, because I don't have a lot of answers or strong opinions. I'm mostly putting this here so we have a place for people who _do_ have answers and strong opinions (including about how important streaming is).

### Describe the proposed solution

N/A

### Importance

nice to have

**Comment by Mlocik97** [comment]
You know you can move issues to discussion and vice versa.

**Comment by Cinci7** [comment]
What you think you know what you doing cause your nit supposed  it be on here at at all im reporting you good day.
