### ISSUE TITLE
How should types be provided to stuff?

### ISSUE THREAD

**Issue by plmrry** [sveltejs/kit#4839]
### Describe the problem

I'm not sure how we are supposed to provide a type definition for the `stuff` argument of a page's `load` function.

I'm passing data into `stuff` within my `__layout.svelte`. 

When using that `stuff` object within non-layout pages, Typescript thinks it should be an empty object. 

<img width="502" alt="Screen Shot 2022-05-06 at 10 51 49 AM" src="https://user-images.githubusercontent.com/688617/167158730-92aad22e-8d7c-44d9-831e-690408ab4d6c.png">
 

### Describe the proposed solution

I'm not sure if this is a bug, or needs to be documented somewhere.

### Importance

nice to have

**Comment by Conduitry** [comment]
It's documented at https://kit.svelte.dev/docs/types#app

**Comment by plmrry** [comment]
🤦‍♂️ sorry! thanks
