### ISSUE TITLE
Handling scheduled events with adapter-cloudflare-workers

### ISSUE THREAD

**Issue by tgle** [sveltejs/kit#4841]
### Describe the problem

I notice the CF Workers adapter now uses the module worker format for output. That's great! But now I'm wondering, how can I have sveltekit output the default export needed to handle scheduled events on CF? I need it for sending scheduled emails. https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/#syntax-module-worker

### Describe the proposed solution

Documentation on how to use the Cloudflare Workers scheduling feature with a SvelteKit project

### Alternatives considered

In the version before the adapter used module workers, it was possible to just put this in `hooks.ts`:

```ts
if (typeof addEventListener !== 'undefined') {
  addEventListener('scheduled', (event: ScheduledEvent) => {
    event.waitUntil(...)
  })
}
```

However this is no longer the syntax for the module format.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
Is there a reason sending emails needs to be the responsibility of your SvelteKit app, rather than a separate dedicated worker?

**Comment by tgle** [comment]
It uses a bunch of code and environment from the svelte-kit app to send the emails, since it needs to iterate over the users in the database and determine if they're ready to receive a reminder email.

But you're right-- the Cloudflare Discord helped me work out a solution using a second worker for the Cron Trigger part that calls a `/heartbeat` endpoint on the svelte-kit app through Service Bindings. It's a little janky because Service Bindings were just released the other day, but it works!

**Comment by Rich-Harris** [comment]
Excellent — will close this as it's not expected that `addEventListener('scheduled', ...)` will work, and if we wanted it to then we'd need to explicitly design support for it

**Comment by robertaboukhalil** [comment]
This is a bit hacky, but here's what I did to get a cron working within the same Svelte Kit + [Cloudflare Workers adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare-workers) app. (mostly because it's really convenient to keep everything as a single worker 🙂)


#### wrangler.toml

```toml
[...]
main = "./.cloudflare/worker.mjs"
[...]
```

#### package.json

```js
[...]
    "scripts": {
        [...]
        "postbuild": "cat src/lib/cron.js >> .cloudflare/worker.mjs"
    }
[...]
```

#### src/lib/cron.js

```js
entry_default.scheduled = async (event, env, ctx) => {
    ctx.waitUntil(cron(env));
};

// Cron logic
async function cron(env) {
    console.log("Starting cron");
    // ...
}
```

(of course this only works if `cron.js` doesn't need to import anything, otherwise it would need its own build step)

**Comment by colecrouter** [comment]
Here's my revised solution based on @robertaboukhalil's

```js
// $lib/cron.js
/**
 * @param {import("@cloudflare/workers-types").ScheduledEvent} event 
 * @param {Env} env 
 * @param {import('@cloudflare/workers-types').EventContext<Env, "", {}>} ctx 
 */
entry_default.scheduled = async (event, env, ctx) => {
    // ... do stuff here
};
```

```js
// append.js
import { appendFile, readFile } from 'fs/promises';

const file = await readFile('src/lib/cron.js', 'utf8');
await appendFile('.cloudflare/worker.js', file, 'utf8')
```

```json
    "build": "vite build && node append.js",
```

Note that if you're planning on fetch-ing existing endpoints in your app, you don't have SvelteKit's fetch function, so you'll get a 1042 error. You can get around this by adding a service binding that points to itself:

```toml
# wrangler.toml
[[services]]
binding = "SELF"
service = "worker_name_here"
```

```js
entry_default.scheduled = async (event, env, ctx) => {
    await env.SELF.fetch('...');
};
```

**Comment by e3ndr** [comment]
Hate to necro, but here's my solution for anyone who's coming from Google:

```javascript
// cron/append.js

// https://github.com/sveltejs/kit/issues/4841#issuecomment-3290611044
import { appendFile, readFile } from 'fs/promises';

const file = await readFile('cron/job.js', 'utf8');
await appendFile('.svelte-kit/cloudflare/_worker.js', file, 'utf8');
```
```javascript
// cron/job.js

// https://github.com/sveltejs/kit/issues/4841#issuecomment-3290611044
/**
 * @param {import("@cloudflare/workers-types").ScheduledEvent} event
 * @param {Env} env
 * @param {import('@cloudflare/workers-types').EventContext<Env, "", {}>} ctx
 */
worker_default.scheduled = async (event, env, ctx) => {
	// You can use example.com or any other origin as long as it's a fully-qualified URL.
	// Replace /_cron with any path of your choosing, preferably one with some secret key so outsiders cannot trigger your cron jobs arbitrarily.
	const req = new Request('https://example.com/_cron', { method: 'GET' });
	await worker_default.fetch(req, env, ctx);
};
```
```javascript
// wrangler.jsonc

{
	"name": "example-api",
	"main": ".svelte-kit/cloudflare/_worker.js",
	"compatibility_date": "2025-01-01",
	"assets": {
		"binding": "ASSETS",
		"directory": ".svelte-kit/cloudflare"
	},
	"triggers": {
		"crons": ["0 * * * *"]
	}
}
```


And then my `npm run build` script looks like: `vite build && node cron/append.js`


This avoids needing to use a service binding, though you WILL need to deploy the site on [Workers](https://svelte.dev/docs/kit/adapter-cloudflare-workers) instead of Pages.

**Comment by dev-itzarun** [comment]
@Rich-Harris Please Update Cloudflare adapter to support injecting CRON Triggers to this main file".svelte-kit/cloudflare/_worker.js" by default on build

Must support [Multiple Cron Triggers](
https://developers.cloudflare.com/workers/examples/multiple-cron-triggers/)
