### ISSUE TITLE
adapter-static not rendering index.html by default

### ISSUE THREAD

**Issue by Myrmod** [sveltejs/kit#4842]
### Describe the bug

I created a skeleton project via `npm init svelte`. Switched to `adapter-static` to build it.

The output didn't contain an html file. I expected the `index.html` to be created, since there was nothing else. Without HTML, as far as I know, a website is no website. So I would expect an error to be thrown during build.

### Reproduction

```sh
git clone git@github.com:Myrmod/example-3d.git adapter-static-not-rendering-html
cd adapter-static-not-rendering-html
npm ci
npm run build
```

==> there is no html in the `build directory`

### Logs

```shell
> Using @sveltejs/adapter-static
  You should set `config.kit.prerender.default` to `true` if no fallback is specified
  Wrote site to "build"
  ✔ done
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (5) x64 Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
    Memory: 1.55 GB / 3.84 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.5 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.326 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

The solution would be to set eg `config.kit.prerender.default` to true by default or thrown an error if there is no html file being rendered.

**Comment by NikosEfthias** [comment]
I have the same problem it creates a bunch of node files instead of actually static rendering

**Comment by NikosEfthias** [comment]
waste of the entire day. I need to write with vanilla svelte now everything and perhaps use something that works such as parcel

**Comment by Rich-Harris** [comment]
The answer is in the logs you pasted in:

> You should set `config.kit.prerender.default` to `true` if no fallback is specified

**Comment by Myrmod** [comment]
The reason for this issue was actually not a request for a solution, but to set a better default. Since the default settings can create a bundle without any HTML files and I don't know of a reason for such a bundle to exist.

**Comment by MentalGear** [comment]
> The solution would be to set eg `config.kit.prerender.default` to true by default or thrown an error if there is no html file being rendered.

I strongly concur! Searched for over >1 hours as the sveltekit build folder didn't contain any html files, and became quite frustrated. The official [adapter guide](https://kit.svelte.dev/docs/adapters) does not mention prerender has to be true for static adpater, and the logged hint also just refers on how to set it for fallback to work, not that it must be true for static-adapter to work. Thanks @Myrmod  for the solution!

**Comment by 24jr** [comment]
So is something like this supposed to get me the index.html on npm run package because this is not...Very confused.
```
import adapter from "@sveltejs/adapter-static";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    prerender: {
      default: true
    },
    adapter: adapter(
      {
        pages: 'build',
        assets: 'build',
        fallback: 'index.html'
      }
    ),
    package: {
      dir: 'package',
      emitTypes: true
    }
  }
};

export default config;
```

**Comment by ranzucker** [comment]
currently the default config is described here https://github.com/sveltejs/kit/tree/master/packages/adapter-static
you'd need to change 
` fallback: null,`
to
` fallback: index.html,`
to generate the file

**Comment by NikosEfthias** [comment]
> currently the default config is described here https://github.com/sveltejs/kit/tree/master/packages/adapter-static you'd need to change ` fallback: null,` to ` fallback: index.html,` to generate the file

this is somewhat confusing and unintuitive tho. Am i the only one who thinks so ? I believe if adapter is static the default file should be index.html if then user wants to change it to something else should go for this update. Again this is my personal opinion everybody does a great job designing and maintaining the project and i mean no offence to anyone :)

**Comment by francoisschwarzentruber** [comment]
I finally succeeded to use adapter-static with github pages!
I wrote https://github.com/francoisschwarzentruber/howto-deploy-a-sveltekit-application in order to explain how to do that. Hope it helps.

**Comment by phil-w** [comment]
For me `fallback: index.html,`  still errors out - you have to quote the name of the missing page:
`fallback: 'index.html'` does work. The documented "default" config doesn't work without this thread.

The name seems confusing too; I don't want a "fall back".

**Comment by MentalGear** [comment]
Guys, We need to open up a new issue for this, since it's all bit fixed, but none of the maintainers see it as it's marked as a closed.On 3 May 2024, at 14:05, phil-w ***@***.***> wrote:﻿
For me fallback: index.html,  still errors out - you have to quote the name of the missing page:
fallback: 'index.html' does work. The documented "default" config doesn't work without this thread.
The name seems confusing too; I don't want a "fall back".
