### ISSUE TITLE
HMR 'reload on save' breaks on import but build does not

### ISSUE THREAD

**Issue by mallsoft** [sveltejs/kit#4844]
### Describe the bug

HMR reload on save breaks when importing with "wrong" case. 

`import Xyz from 'Xyz.svelte'`✅
vs
`import Xyz from 'xyz.svelte'` ❌ no reload

### Reproduction

1. Import component `import X from "x.svelte"` (notice the lower case)
2. Modify X and the expected update does not happen.

Example:
2 iframes showing two routes where one imports `Component.svelte` and another `component.svelte`

https://github.com/mallsoft/hmr-bug-reprod

### System Info

```shell
Windows 10
Firefox 100.0 64
VSCode
Terminal - bash
```

### Severity

annoyance

### Additional Information

Relevant [discord thread](https://discord.com/channels/457912077277855764/970337730712186921)

**Comment by mallsoft** [comment]
Relevant discord thread https://discord.com/channels/457912077277855764/970337730712186921

**Comment by dominikg** [comment]
You must always use the exact case of the filename on disk when importing, even on case insensitive file systems.

To be honest i am surprised building works without errors in your case, your reproduction produces errors on both `pnpm dev` and `pnpm build` in a case sensitive file system (ext4)

I suggest you turn on case sensitivity in your file system (options exist for windows and mac) to get immediate feedback when using the "wrong" case.

There is also an enhancement pending in vite to warn you about case inconsistencies: https://github.com/vitejs/vite/issues/964

closing here as an upstream issue exists
