### ISSUE TITLE
Server fetch vs browser fetch

### ISSUE THREAD

**Issue by codeyash** [sveltejs/kit#4853]
### Describe the bug

Browser fetch is working fine but server fetch is not working and reporting Invalid URL error.

### Reproduction

```
//REST.js file
export const get = async (url) => {

	const response = await fetch('/api', {
		method: 'GET',
                credentials: 'include',
                mode: 'same-origin',

		headers: {
			'Content-Type': 'application/json',
			'Accept': 'application/json',
			'url': url
		}
	})

	return {
		status: response.status,
		body: await response.json()
	}
}


//Index.svelte
import { get } from '$lib/rest.js'
export const load = async () => {
    // Not working
    const organisations = await get(`organization/`) 

}

```

```
import { get } from '$lib/rest.js'
onMount( async () => {
   // Works perfectly
    const organisations = await get(`organization/`) 

  })


```

### Logs

```shell
Invalid URL
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:372:5)
    at URL.onParseError (node:internal/url:563:9)
    at new URL (node:internal/url:643:5)
    at new Request (file:///Users/y/Projects/era/ui/node_modules/@sveltejs/kit/dist/install-fetch.js:5907:16)
    at file:///Users/y/Projects/era/ui/node_modules/@sveltejs/kit/dist/install-fetch.js:6189:19
    at new Promise (<anonymous>)
    at fetch (file:///Users/y/Projects/era/ui/node_modules/@sveltejs/kit/dist/install-fetch.js:6187:9)
    at Module.get (/src/lib/Common/Util/rest.js:3:25)
    at load (index.svelte:13:26)
    at load_node (file:///Users/y/Projects/era/ui/.svelte-kit/runtime/server/index.js:2421:30)
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 75.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.4
  npmPackages:
    svelte: ^3.48.0 => 3.48.0
```

### Severity

blocking all usage of svelte

**Comment by Conduitry** [comment]
On the server, when not using the copy of `fetch` passed into a `load` function, you need to pass a complete URL, not a relative one.

**Comment by codeyash** [comment]
https://stackoverflow.com/a/36369553 - If I am using / in front of URL then it should work. It's not working

With full URL it's not working. Creating below error: 

`500
Load failed
fetch@[native code]
@http://localhost:3000/src/lib/Common/Util/rest.js?t=1652058188322:3:30
asyncFunctionResume@[native code]
@http://localhost:3000/src/routes/index.svelte:53:27
asyncFunctionResume@[native code]
@http://localhost:3000/@fs/Users/yash/Projects/era/ui/.svelte-kit/runtime/client/start.js:946:41
asyncFunctionResume@[native code]
@http://localhost:3000/@fs/Users/yash/Projects/era/ui/.svelte-kit/runtime/client/start.js:1575:34
asyncFunctionResume@[native code]
@[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]`


 Let's discuss it first before aggressively closing it.
