### ISSUE TITLE
Auto import

### ISSUE THREAD

**Issue by codeyash** [sveltejs/kit#4854]
### Describe the problem

Auto imports without needing import manually.  It will nice to support by default. 

### Describe the proposed solution

https://github.com/yuanchuan/sveltekit-autoimport
https://v3.nuxtjs.org/guide/concepts/auto-imports/

### Importance

would make my life easier

### Additional Information

It will remove lots of extra code and it will make code look clean.

**Comment by benmccann** [comment]
several maintainers discussed this and there's widespread agreement that the reduction in clarity is not worth the conciseness benefits

**Comment by dummdidumm** [comment]
If you really want this , the community already has you covered with a plugin which does just that: https://www.npmjs.com/package/sveltekit-autoimport

**Comment by codeyash** [comment]
@Rich-Harris can you please review this? I have no idea what @benmccann is referring "widespread agreement" or "reduction in clarity". It will remove unnecessary import statements.

I have watched many of your videos on YouTube, and it seems you respect community vision.

NuxtJs-v3 is bringing similar features. I love svelte-kit so much that I am beta version on many of my production applications without any issues.

Closing any request like it is a very bad community experience. The bad community experience is the number reason for any product failure as per my research and knowledge.

I hope you will consider many new features which are similar to NuxtJS-V3.

Good luck!
