### ISSUE TITLE
Update @sveltejs/vite-plugin-svelte to 1.0.0-next.43

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#4855]
### Describe the problem

@sveltejs/vite-plugin-svelte added an experimental code-inspector with [its latest update](https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/CHANGELOG.md#100-next43). This feature is super interesting, and i would love to have this in SvelteKit and test it out.

### Describe the proposed solution

Updating `@sveltejs/vite-plugin-svelte` to `1.0.0-next.43`

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
You are free to bump this yourself. SvelteKit has a dependency on the plugin in the form of `^1.0.0-next.32`, so `next.43` should work, too. You could do that by running the package update command of the package manager you use, or delete the node_modules folder and the lock file and reinstall again.
