### ISSUE TITLE
Provide AbortController implementation for `load({ fetch })`

### ISSUE THREAD

**Issue by furudean** [sveltejs/kit#4866]
### Describe the problem

The preferred way to set up timeouts with `fetch` is to use [`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController). This is a browser API that does not exist in most supported node versions (or other environments) and requires a user provided polyfill to work correctly. [`abort-controller`](https://www.npmjs.com/package/abort-controller) is what `node-fetch` [suggests as a solution](https://github.com/node-fetch/node-fetch#request-cancellation-with-abortsignal).

The user has to handle both the browser and ssr rendering cases with something like:
```js
const AbortController = globalThis.AbortController || await import('abort-controller')
```

This is awkward, and I think it's in the spirit of Svelte Kit to help out with this.

### Describe the proposed solution

Expose a polyfilled `AbortController` implementation as a parameter like we did with `fetch`, i.e. `load({ fetch, AbortController })`, or as a global.

### Alternatives considered

Bring your own polyfill and set up logic yourself.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Yeah, agree with this. Now that [WinterCG](https://wintercg.org/) exists, we could look to [this document](https://common-min-api.proposal.wintercg.org/) for guidance on which APIs should be available. `install-fetch` probably needs to become something like `install-runtime` (and maybe we need to have different versions of it for different Node versions, since future versions of Node will include more of this stuff).

**Comment by Rich-Harris** [comment]
Actually, looking at https://developer.mozilla.org/en-US/docs/Web/API/AbortController#browser_compatibility, `AbortController` is supported in Node in versions 15 and above. As of #4922, SvelteKit only supports Node 16 and above, which means we can guarantee that `AbortController` is present - no polyfills needed.

**Comment by furudean** [comment]
What about other environments?

**Comment by abdo643-HULK** [comment]
> What about other environments?

Deno and cloudflare have out of the box support and all other environments officially supported by the sveltekit team run on aws lambda which gets defaulted into using Node 16.
