### ISSUE TITLE
Error: Cannot read clientAddress during prerendering

### ISSUE THREAD

**Issue by JLAcostaEC** [sveltejs/kit#4873]
### Describe the bug

Trying to do a deployment in vercel I have found the following, will I have to deactivate the SSR?

I'm using the handle hook to get the user IP.

### Reproduction

Just do a console.log of `event.clientAddress` on handle() hook.

### Logs

```shell
at Object.getClientAddress (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1240:8)
    at Object.get clientAddress [as clientAddress] (file:///vercel/path0/.svelte-kit/output/server/index.js:2110:22)
    at Object.handle (file:///vercel/path0/.svelte-kit/output/server/chunks/hooks-4198ddf8.js:29:109)
    at async visit (file:///vercel/path0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1085:20)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
    Memory: 4.61 GB / 15.83 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40
    @sveltejs/adapter-vercel: ^1.0.0-next.50 => 1.0.0-next.50
    @sveltejs/kit: next => 1.0.0-next.324
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is expected behaviour — you can't include someone's IP address in a prerendered HTML file. Can you elaborate on what you're trying to do and why this is a bug?

**Comment by JLAcostaEC** [comment]
Yes thats true, but request the clientAddres on Dev work perfect (Would I need a warning?).

After all, There is only talk of disabling Prerendering on Discord, But I was able to fix it using:

```
import { prerendering } from '$app/env';
export async function handle({ event, resolve }) {
const clientAddress = !prerendering ? await event.clientAddress : '';
}
```
// src/hooks.ts

**Comment by Rich-Harris** [comment]
Prerendering only happens at build time. A given page or endpoint _could_ be both prerendered and dynamically rendered (e.g. `/blog/[slug]` could power both a prerendered `/blog/recent-article` and `/blog/long-tail-article`), so it's not possible to disallow it at dev time. 

The `prerendering` import from `$app/env` is designed to enable exactly the sort of thing you're doing. Closing as I don't think there's anything that needs to change here
