### ISSUE TITLE
When using netlify-adapter with Edge functions enabled, _redirect is not being created, resulting in 404

### ISSUE THREAD

**Issue by saturnonearth** [sveltejs/kit#4881]
### Describe the bug

When using the netlify-adapter with Edge functions enabled in the config, the _redirect file is not being created at all, resulting in a 404, "Page Not found" as this file is required to redirect all requests to the **Render** function.

### Reproduction

use netlify-adapter, set Edge functions to "true"

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 94.73 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    npm: 8.5.3 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 88.0.1
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @sveltejs/adapter-netlify: next => 1.0.0-next.56 
    @sveltejs/kit: next => 1.0.0-next.326 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking an upgrade

### Additional Information

Similar and probably related to other issue I created,[ #4722](https://github.com/sveltejs/kit/issues/4722)

**Comment by Rich-Harris** [comment]
As far as I can tell, Netlify edge functions don't use `_redirects`; they use `.netlify/edge-functions/manifest.json`. It's working fine for me. Perhaps the error is caused by something else?

**Comment by saturnonearth** [comment]
Looks like it was the password I had set through Netlify to make the website `private` only.
