### ISSUE TITLE
Dynamic route not possible when using adapter-static

### ISSUE THREAD

**Issue by superseby2** [sveltejs/kit#4886]
### Describe the bug

Not sure this is a bug or a misundestanding from my part. 

When building my project using adapter-static. Dynamic route does not seem to be built at all. 

### Reproduction

the route is as follow

/offer/test-[offerId]

When built with the node-adapter I can browse http://.../offer/test-19090
but doing the same thing on a static build will display the /index.svelte content. (not even a 404)
The page itself does nothing but a console.log.

Is dynamic routing possible when going static ? I thought it would  as load function are working in this mode. :thinking: 

Thx!

### System Info

```shell
"@sveltejs/adapter-static": "^1.0.0-next.29", 
"@sveltejs/kit": "^1.0.0-next.326"
"svelte": "^3.46.6",
"svelte-preprocess": "^4.10.6"
```

### Severity

annoyance

### Additional Information

Adaptater config

      adapter: adapter(
 23      {
 24          precompress: false,
 25          fallback: null
 26      }
 27 
 28     ),
 29 
 30     prerender: {
 31         default: true
 32

**Comment by Rich-Harris** [comment]
Prerendering will generate .html files for any pages that are a) explicitly listed in `config.kit.prerender.entries` or b) discoverable via links.

I'm going to close this issue though, as you didn't follow the reproduction instructions in the issue template.

**Comment by superseby2** [comment]
Thx @Rich-Harris for the quick reply. 

And sorry for not following the reproduction instructions. (I guess it is a good practice, even if at fist it hurts :smiley:  that you closed issues like mine, as it made me actually *read*  the instructions.. which might be a little too "blocky" though ... .)

Regarding the issue, I my understanding is that static is not the way to go when you have dynamic pages, hence not discoverable. (Adding in config.kit.prerender.entries would thoough a 404 in that case).

Thx.

**Comment by mrkishi** [comment]
You can still have dynamic pages with `adapter-static`, but you must serve the fallback page for URLs that weren't prerendered.

Please, direct questions to [Github Discussions](https://github.com/sveltejs/kit/discussions), [Discord](https://svelte.dev/chat), or [StackOverflow](https://stackoverflow.com/questions/tagged/sveltekit).

**Comment by superseby2** [comment]
Thanks @mrkishi
