### ISSUE TITLE
Endpoint code is built for / accessible to the client

### ISSUE THREAD

**Issue by babichjacob** [sveltejs/kit#489]
**Describe the bug**
Endpoint code is included in the files built for the client:
https://github.com/sveltejs/kit/blob/943a11fea064841b3291599043761c3bd62acc8b/packages/kit/src/core/build/index.js#L112-L116

This was added in 710126d9264b41aa65686dd381027e6e438faedb as part of the service workers pull request.

**Logs**
There are no errors or warnings in the logs, unless you use a library that can't be built for browsers such as `firebase-admin`, in which case you get a Vite / Rollup build failed error: *See the Stacktraces section*

**To Reproduce**
* Use `examples/sandbox` as a starting point
* Put `console.log("sensitive info");` at the top of `src/routes/doubler.js`
* Switch to the static adapter (I don't know if the Node or any other adapter will show the problem so easily) in `svelte.config.cjs`
* Build and adapt with the `build` package script
* Recall the generated `build` folder is meant to be publicly served with e.x. `pnpx serve build`. Notice in the `build` folder that the `_assets` folder has an `endpoints` folder with the `doubler.js` code and `sensitive info`. 
* You could navigate to `site.com/_assets/endpoints/` and the HTTP server show you the files available—yikes!

**Expected behavior**
Endpoint code shouldn't be included in the files built for the client because it's intended for the server only (they're formerly known as server routes after all).

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

    > svelte-kit build
    
    vite v2.0.4 building for production...
    transforming (315) ../../node_modules/.pnpm/tslib@2.1.0/node'fast-crc32c' is imported by fast-crc32c?commonjs-external, but could not be resolved – treating it as an external dependency
    'request' is imported by request?commonjs-external, but could not be resolved – treating it as an external dependency
    transforming (853) ../../node_modules/.pnpm/uuid@8.3.2/node_Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
    ✓ 862 modules transformed.
    rendering chunks (4)...[vite:esbuild-transpile] Transform failed with 2 errors:
    endpoints/doubler.js-cbebd688.js:167765:4: error: Transforming async generator functions to the configured target environment is not supported yet
    endpoints/doubler.js-cbebd688.js:167783:16: error: Transforming for-await loops to the configured target environment is not supported yet
    
    Transforming async generator functions to the configured target environment is not supported yet
    167763|       * `QueryPartition`s.
    167764|       */
    167765|      async *getPartitions(desiredPartitionCount) {
       |      ^
    167766|          var _a;
    167767|          validate.validateInteger('desiredPartitionCount', desiredPartitionCount, {
    
    Transforming for-await loops to the configured target environment is not supported yet
    167781|              const stream = await this.firestore.requestStream('partitionQueryStream', request, tag);
    167782|              stream.resume();
    167783|              for await (const currentCursor of stream) {
       |                  ^
    167784|                  ++partitionCount;
    167785|                  const currentValues = (_a = currentCursor.values) !== null && _a !== void 0 ? _a : [];
    
    > Transform failed with 2 errors:
    endpoints/doubler.js-cbebd688.js:167765:4: error: Transforming async generator functions to the configured target environment is not supported yet
    endpoints/doubler.js-cbebd688.js:167783:16: error: Transforming for-await loops to the configured target environment is not supported yet
    Error: Transform failed with 2 errors:
    endpoints/doubler.js-cbebd688.js:167765:4: error: Transforming async generator functions to the configured target environment is not supported yet
    endpoints/doubler.js-cbebd688.js:167783:16: error: Transforming for-await loops to the configured target environment is not supported yet
        at failureErrorWithLog (/Users/babichjacob/Repositories/svelte-kit/node_modules/.pnpm/esbuild@0.8.52/node_modules/esbuild/lib/main.js:1171:15)
        at /Users/babichjacob/Repositories/svelte-kit/node_modules/.pnpm/esbuild@0.8.52/node_modules/esbuild/lib/main.js:1037:33
        at /Users/babichjacob/Repositories/svelte-kit/node_modules/.pnpm/esbuild@0.8.52/node_modules/esbuild/lib/main.js:553:9
        at handleIncomingPacket (/Users/babichjacob/Repositories/svelte-kit/node_modules/.pnpm/esbuild@0.8.52/node_modules/esbuild/lib/main.js:642:9)
        at Socket.readFromStdout (/Users/babichjacob/Repositories/svelte-kit/node_modules/.pnpm/esbuild@0.8.52/node_modules/esbuild/lib/main.js:520:7)
        at Socket.emit (events.js:315:20)
        at addChunk (internal/streams/readable.js:309:12)
        at readableAddChunk (internal/streams/readable.js:284:9)
        at Socket.Readable.push (internal/streams/readable.js:223:10)
        at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

       ERROR  Command failed with exit code 1.
</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
➜ npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers
npx: installed 1 in 1.165s

  System:
    OS: macOS 11.1
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor [Hackintosh]           
    Memory: 75.76 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.2 - ~/.nvm/versions/node/v14.15.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.2/bin/npm
  Browsers:
    Chrome: 89.0.4389.82
    Firefox: 86.0
    Safari: 14.0.2

- Your browser: Browser independent

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): Static. No other adapters tested.

**Severity**
Security issue. Blocks some usage of server-side libraries like the aforementioned `firebase-admin`.

**Additional context**
Removing the highlighted code block above solves the issue and doesn't cause any tests to fail. I don't know if there are any features or behaviors that depend on this but don't have tests, though.

**Comment by alteredorange** [comment]
I'm struggling with firebase-admin, it' always fails on build with a because it can't `read length of undefined`
```
import * as firebaseAdmin from 'firebase-admin';
if (typeof window === 'undefined' && !firebaseAdmin.apps.length) {
    firebaseAdmin.initializeApp({
        credential: firebaseAdmin.credential.cert(serviceAccount),
        databaseURL: "https://oranges-testing.firebaseio.com"
    });
}
```
because firebaseAdmin is undefined...  It works fine in dev, but not when I `npm run build`....
