### ISSUE TITLE
Improve the routing docs for getting page params

### ISSUE THREAD

**Issue by aklajnert** [sveltejs/kit#4894]
### Describe the problem

This is not really a feature request, nor a bug report but a suggestion to update the docs.

I was trying to access the query parameters from the route. The [Endpoints chapter in the documentation](https://kit.svelte.dev/docs/routing#endpoints) presents rather a clunky way to do that. Besides being not very elegant, I had quite a problem with it, that such code was causing error 500 for me in some cases. I've prepared a repository demonstrating it if you'd like to see it [here](https://github.com/aklajnert/svelte-issue-demo).

The solution was much, much simpler than the one described in the docs:
```html
<script lang="ts">
  import {page} from '$app/stores';

  export let name = $page.params.name;
</script>
```

I've spent quite some time figuring it out when it could be simply put in the docs. I know that this way it's not reactive, but making it reactive is also quite simple:
```html
<script lang="ts">
  import {page} from '$app/stores';

  export let name: string;
  $: tab = $page.params.name;
</script>
```

### Describe the proposed solution

The docs should be updated showing the simpler solution at least as an alternative.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
Closing this as I'm not sure it's specific enough to act on. The endpoints documentation isn't showing how to access parameters, it's showing how to load data _based_ on parameters, which isn't equivalent to accessing `$page.params.whatever`. Documentation on how to access parameters in a page is in https://kit.svelte.dev/docs/routing#pages
