### ISSUE TITLE
Automatically rerouted to `http://sveltekit-prerender` in production

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#4900]
### Describe the bug

I'm automatically redirected to `http://sveltekit-prerender/<my-path>` when trying to enter my application that is hosted on Vercel.

### Reproduction

I'm not sure how to reproduce this, it just suddenly happened without any code changes.

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 120.23 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.39
    Firefox: 100.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-vercel: ^1.0.0-next.50 => 1.0.0-next.50 
    @sveltejs/kit: 1.0.0-next.326 => 1.0.0-next.328 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by jordigagomerino** [comment]
Hi
How you solved this problem? I have the same issue.
Thanks

**Comment by MathiasWP** [comment]
Hi @jordigagomerino! I found that the bug was caused by a redirect in my `handle` hook. I changed from redirecting in the `handle`-hook to using the load-function in my root `__layout.svelte` instead!
