### ISSUE TITLE
SVG file and version hashing (any reason not to hash them?)

### ISSUE THREAD

**Issue by jaymakes11** [sveltejs/kit#4914]
### Describe the problem

Currently it seems that SVG files do not get their filenames appended with their hash for versioning purposes, unlike other files. 

Is this intentional or can we fix it?

### Describe the proposed solution

Add a version hash to SVG file names (and update their references) for production builds.

### Importance

nice to have

**Comment by Conduitry** [comment]
Where are the SVG files and how are you referring to them? If they're in `static` and you're just referring to them with `<img src='/static/whatever.svg'>`, then yes, this is intentional.

**Comment by jaymakes11** [comment]
Yes, they're in `static/` and yes I'm using them via `img` tags. 

Any insight on the reason this is intentional?

Is there any way to force them to be hashed?

**Comment by Rich-Harris** [comment]
Yes, import them using [Vite's asset handling logic](https://vitejs.dev/guide/assets.html):

```svelte
<script>
  import whatever from './whatever.svg';
</script>

<img src={whatever} alt="whatever">
```

It wouldn't make any sense to hash files in `static`, as you'd have no way to get the hashed filename (it's not like you can reliably replace every occurence of a URL that corresponds to a static asset whether it appears in HTML, CSS, JS or a blob of JSON or whatever), and in general you don't _want_ them to be hashed — you wouldn't hash `static/robots.txt` or `static/favicon.png` for example.
