### ISSUE TITLE
Asset extension matching not consistent between DEV and PREVIEW

### ISSUE THREAD

**Issue by Laavenx** [sveltejs/kit#4931]
### Describe the bug

Preview build of sveltekit doesn't match asset paths the same way as dev build.

### Reproduction

Put let's say image.PNG inside of static then in index.svelte `<img src="/image.png" />` and let's run npm run dev, then run build and preview and the image won't be displayed anymore.

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 6.21 GB / 15.94 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (97.0.1072.76)
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40
    @sveltejs/kit: next => 1.0.0-next.328
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I can't reproduce this. It's working fine for me. Please provide a complete clonable repo that reproduces the issue.

**Comment by Laavenx** [comment]
All you have to do is rename svelte-welcome.png and webp to svelte-welcome.PNG AND WEBP in demo template (build should also throw 404 error). If that doesn't work then its interesting why it works this way on my system.
![Screenshot_2](https://user-images.githubusercontent.com/57064828/168480776-8047748c-3c29-4a53-b405-e5d01f04594f.png)

**Comment by Conduitry** [comment]
This sounds like a case sensitivity thing. I see you're on Windows and you're requesting the file with a lower case extension and it looks like the file is named with an upper case extension.

**Comment by Rich-Harris** [comment]
We should probably enforce correct case at dev time

**Comment by Conduitry** [comment]
Do we have the access/control necessary for that? Isn't Vite solely responsible for serving those assets, and we just give it the directory to use?

**Comment by Rich-Harris** [comment]
No, we use `sirv` so that we have more control:

https://github.com/sveltejs/kit/blob/ae416be399340a86f8191b6a80c4dee59bf1d541/packages/kit/src/core/dev/plugin.js#L200-L204

https://github.com/sveltejs/kit/blob/ae416be399340a86f8191b6a80c4dee59bf1d541/packages/kit/src/core/dev/plugin.js#L176-L181

I don't recall if `sirv` can enforce the correct case, but we could do it easily enough before handing off to `sirv`.
