### ISSUE TITLE
Adding --host to script is not exposing server on network

### ISSUE THREAD

**Issue by yousufiqbal** [sveltejs/kit#4947]
### Describe the bug

I'm on Windows 10. On starting fresh repo using `npm init svelte` and then adding `--host` to `dev` in scripts is not exposing server to other devices on network.

```json
{
  "name": "abcd",
  "version": "0.0.1",
  "scripts": {
    "dev": "svelte-kit dev --host",
    "build": "svelte-kit build",
    "package": "svelte-kit package",
    "preview": "svelte-kit preview",
    "prepare": "svelte-kit sync",
    "check": "svelte-check --tsconfig ./jsconfig.json",
    "check:watch": "svelte-check --tsconfig ./jsconfig.json --watch",
    "lint": "eslint --ignore-path .gitignore ."
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "eslint": "^8.12.0",
    "eslint-plugin-svelte3": "^4.0.0",
    "svelte": "^3.44.0",
    "svelte-check": "^2.2.6",
    "typescript": "~4.6.2"
  },
  "type": "module"
}
```

Terminal output

```
> abcd@0.0.1 dev
> svelte-kit dev --host


  SvelteKit v1.0.0-next.331

  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network
```

The issue seems to be tied with **next.331**. I cannot reproduce this on **next.330**

### Reproduction

https://github.com/yousufiqbal/host-issue-repo.git

### Logs

```shell
> abcd@0.0.1 dev
> svelte-kit dev --host


  SvelteKit v1.0.0-next.331

  network: not exposed
  local:   http://localhost:3000

  Use --host to expose server to other devices on this network
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz
    Memory: 383.09 MB / 3.90 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.47)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.43
    @sveltejs/kit: next => 1.0.0-next.331
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by yousufiqbal** [comment]
I found that using `svelte-kit dev --host 0.0.0.0` makes it work. But that wasn't the case before. Only adding `--host` to scripts worked previous. If it is intended, maybe it should be documented.

**Comment by Conduitry** [comment]
With the new default for `host` specified in https://github.com/sveltejs/kit/pull/4932/files#diff-3d3392afaae8a848f5862f73d4cfa9e50f984b68ecd1d91f6c414ece0de4f23bR52, when `--host` is specified without an argument, the `host` variable is now an empty string, rather than `true`.

@bluwy Is there a particular reason to have `'localhost'` be the default for this option? Should we revert that part of the change, or should we make the rest of the codebase treat `host` equal to an empty string as exposing the server on all interfaces? The `preview` command, so we could presumably borrow the logic for correctly handling the empty string from there.

**Comment by bluwy** [comment]
Yeah I'm checking this out too and it seems to be the case. I've set it to `localhost` mostly so that it's consistent with `preview`. I think "`host` equal empty string => expose" makes sense.
