### ISSUE TITLE
Document that route matchers are run client-side

### ISSUE THREAD

**Issue by i-am-gizm0** [sveltejs/kit#4981]
### Describe the problem

I ran into a problem on a site that I'm building where the client was throwing an error because it was importing a file it shouldn't have, which was failing because it was trying to import `path` since it is intended to only run on the server.
Tracking it down took a while, but eventually I realized that I was importing that server-only file from a route matcher.
**I had assumed that route matching only happened on the server, not on the client**

### Describe the proposed solution

I would like the [documentation about matching](https://kit.svelte.dev/docs/routing#advanced-routing-matching) to include that the modules are packaged and run on the client.

### Alternatives considered

I am not familiar with the inner workings of routing on SvelteKit between the client and server, but I'm not sure if route matching needs to or should happen on the client; if it is just making requests to the server, does it need to know what endpoint will answer it?

### Importance

would make my life easier

### Additional Information

The client-side error in question: 
![`Uncaught SyntaxError: The requested module '/@id/__vite-browser-external:path' does not provide an export named 'join' (at gallerieshelper.ts:5:1)`](https://user-images.githubusercontent.com/20424374/169087920-abd1256c-091a-4cd9-b273-d37e294459b7.png)
No errors are displayed on the server console

**Comment by Conduitry** [comment]
Route matching needs to happen on the client so that client-side navigation in the app knows what page is going to get rendered. If the page has a `load` function that fetches standalone endpoints (rather than just defaulting to fetching the corresponding page endpoint), the browser needs to know about it.
