### ISSUE TITLE
Standalone POST endpoint request sometimes throws cryptic errors.

### ISSUE THREAD

**Issue by AlexVasiluta** [sveltejs/kit#4989]
### Describe the bug

I was playing around with standalone endpoints that call `request.formData()` and wanted to recreate the requests in curl to see what happens.

I tested `curl -x POST http://localhost:3000/<path>` (which i assume provides an empty body to the request), and my `yarn dev` terminal showed that the request threw `Cannot read properties of null (reading 'startsWith')`. 

After a bit more testing, I found out that `request.json()` also behaves inappropriately (`Unexpected end of JSON input`).

In my view, the expected behaviour for both of the functions should be to return the default output values (empty `FormData` and `{}`, respectively).

### Reproduction

I created a small repository from the skeleton, located here: [https://github.com/AlexVasiluta/sveltekit-bug-report](https://github.com/AlexVasiluta/sveltekit-bug-report).

Steps to reproduce:
1. Start the webserver with `yarn dev`;
2. Run `./curl_commands.sh`, I redirected curl's outputs and added `-s` for clarity in the output;
3. Look at the webserver logs.

### Logs

```shell
Server output from the reproduction above (after running ./curl_commands.sh):

2:20:27 PM [vite] page reload formdata_output.html
Cannot read properties of null (reading 'startsWith')
TypeError: Cannot read properties of null (reading 'startsWith')
at Request.formData (file:///home/alexv/src/bug-report/node_modules/@sveltejs/kit/dist/install-fetch.js:4832:10)
at post (/home/alexv/src/bug-report/src/routes/formData.js:3:28)
at render_endpoint (file:///home/alexv/src/bug-report/.svelte-kit/runtime/server/index.js:171:25)
at resolve (file:///home/alexv/src/bug-report/.svelte-kit/runtime/server/index.js:3305:17)
at async respond (file:///home/alexv/src/bug-report/.svelte-kit/runtime/server/index.js:3250:20)
at async file:///home/alexv/src/bug-report/node_modules/@sveltejs/kit/dist/chunks/index.js:294:24
2:20:27 PM [vite] page reload json_output.html
Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at Request.json (file:///home/alexv/src/bug-report/node_modules/@sveltejs/kit/dist/install-fetch.js:4868:15)
at async post (/home/alexv/src/bug-report/src/routes/json.js:3:14)
at async render_endpoint (file:///home/alexv/src/bug-report/.svelte-kit/runtime/server/index.js:171:19)
at async resolve (file:///home/alexv/src/bug-report/.svelte-kit/runtime/server/index.js:3305:11)
at async respond (file:///home/alexv/src/bug-report/.svelte-kit/runtime/server/index.js:3250:20)
at async file:///home/alexv/src/bug-report/node_modules/@sveltejs/kit/dist/chunks/index.js:294:24
```

### System Info

```shell
System:
OS: Linux 5.17 Fedora Linux 35 (Workstation Edition)
CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
Memory: 7.60 GB / 15.54 GB
Container: Yes
Shell: 5.1.8 - /bin/bash
Binaries:
Node: 17.9.0 - /usr/bin/node
Yarn: 1.22.19 - /usr/bin/yarn
npm: 8.5.5 - /usr/bin/npm
Browsers:
Firefox: 100.0
npmPackages:
@sveltejs/adapter-auto: next => 1.0.0-next.43
@sveltejs/kit: next => 1.0.0-next.335
svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
I don't believe this is incorrect behavior. SvelteKit tries to stick as closely as possible to spec behavior where it can -- and in this case, you're receiving a standard `Request` object. The default behavior for `request.json()` and `request.formData()` is _not_ to return `{}` when there is no body. The default behavior is to throw the errors you're seeing. In the case of JSON, if you set the body to `"{}"`, you'll get `{}` back, but if you set _no_ body, you're never going to get an empty JSON object -- you're going to get an error. Same for `formData`, but I'm not sure what an empty `formData` object looks like as a body.

Try this in your browser console (comment out either await line to see the behavior you want):

```js
const request = new Request('/myEndpoint', {
  method: 'POST'
});

await request.formData();
await request.json();
```

**Comment by tcc-sejohnson** [comment]
[Here's a repro to show you what's going on.](https://github.com/tcc-sejohnson/test-standalone-post). Run it like a normal SvelteKit app and click the buttons on the root page. It'll show you what's happening in the endpoint.

**Comment by mrkishi** [comment]
@tcc-sejohnson is right, this is expected behavior even with the browser's `Request` and `Response` object.

It's possible to provide better errors during dev, but the priority on that is likely to be pretty low.
