### ISSUE TITLE
Endpoints can not handle '=' in cookies

### ISSUE THREAD

**Issue by nhe23** [sveltejs/kit#4991]
### Describe the bug

If you set a cookie that contains a '=' inside the handle hook and then hit an endpoint a second (broken) cookie is written. For example setting `testCookie={"key1":"value1,"key2":"value=2","key3":"value3"}; Path=/; HttpOnly; SameSite=Lax` and then hitting an endpoint will make your cookies look like this: 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/19340684/169399799-62bd6969-fa91-4cde-bb3d-30ba488e32e0.png">

If you then got to page thats not the root page and reload the page the original cookie is set two times (one correct and one broken version): 
<img width="516" alt="image" src="https://user-images.githubusercontent.com/19340684/169401008-a25db661-fe67-40e1-973f-4b006665e929.png">

These broken cookies can potentially crash the whole app and cause a lot of harm.

### Reproduction

https://github.com/nhe23/sveltekit-endpoint-cookie-bug

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 258.66 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.9.0 - ~/.volta/tools/image/node/17.9.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.5 - ~/.volta/tools/image/node/17.9.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.64
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.43 
    @sveltejs/kit: next => 1.0.0-next.335 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by nhe23** [comment]
After some further investigation I found out that this line ist responsible for this bug:https://github.com/sveltejs/kit/blob/4a2b7d98f8de755ea3c7e61134f582e6773b9dc7/packages/kit/src/runtime/server/page/load_node.js#L257
[set-cookie-parser](https://github.com/nfriedly/set-cookie-parser) splits the cookies wrong if there is an equal sign somewhere in the cookies value.

**Comment by d3vhound** [comment]
Hey @nhe23,

I don't think this is an issue with Svelte. I was able to get it to work by adding the `cookie` npm packagae and using the serialize and parse methods from it. Ex:

_hooks.js_
```js
import { serialize } from 'cookie';

export const handle = async ({ event, resolve }) => {
  const response = await resolve(event);
  const body = JSON.stringify({ key1: 'value1', key2: 'value=2', key3: 'value3' })

  response.headers.append(
    'Set-Cookie',
    serialize('testCookie', body, {
      path: '/',
      httpOnly: true,
      sameSite: 'lax',
    })
  )

  return response;
};
```
_endpoint.js_
```js
import { parse, serialize } from 'cookie';

export const get = async (event) => {
  const cookies = parse(event.request.headers.get('cookie') || '');

  return {
    body: {
      key: JSON.parse(cookies.testCookie),
    },
  };
};
```
___layout.svelte_
```svelte
<script context="module">
  export const load = async ({ fetch }) => {
    const testData = await (await fetch(`/endpoint`)).json();

    return {
      props: {
        testData,
      },
    };
  };
</script>

<script>
  export let testData;
</script>

<slot />
<pre>{JSON.stringify(testData.key, null, 2)}</pre>

```

**Comment by tcc-sejohnson** [comment]
I'm pretty sure this isn't a SvelteKit bug, but I could be wrong... @nhe23, as written, your `Set-Cookie` header just plain breaks the spec rules for cookie values ([from MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)):

> A `<cookie-value>` can optionally be wrapped in double quotes and include any US-ASCII character excluding a control character, [Whitespace](https://developer.mozilla.org/en-US/docs/Glossary/Whitespace), double quotes, comma, semicolon, and backslash.

Your cookie value quite clearly contains double quotes _and_ commas -- lots of 'em. If you're trying to pass JSON data (or really anything that's not a simple word-character string) as a cookie value, you should do as @d3vhound suggested and encode your cookie value on the sending side and decode it on the reading side.

**Comment by nhe23** [comment]
In my case I simply forgot to serialize and desirialize my cookie. But my app worked fine until I hit an endpoint. That was very hard to debug and I think that this behaviour can be optimised. If the cookie I'm setting in my handle hooks is not spec compliant it should break immediately rather than kind of work until my app hits an endpoint.

**Comment by mrkishi** [comment]
As a framework, I think it'd make sense for us to support these cookies. While they're not spec-compliant, in practice most servers and browsers support the Netscape-era rules.

If we don't, SvelteKit apps would break merely by running on the same domain as another app that uses them.

**Comment by dummdidumm** [comment]
Since this was opened the `cookies` API was added, which handles proper serialization automatically, so this no longer applies - closing.
