### ISSUE TITLE
Relative paths considered relative to the current url (differs from Sapper behaviour)

### ISSUE THREAD

**Issue by antony** [sveltejs/kit#5]
Porting the hackernews app I have found that:

From the `ask` page, hitting the `ask` navigation link:
```
<li><a rel="prefetch" class='{segment === "ask" ? "selected" : ""}' href='ask/1'>ask</a></li>
```

in Sapper - visits the `/ask/1` page
In Svelte App - visits `/ask/ask/1` page (which 404s)

I'm assuming this has something to do with baseUrl.

Note that in line with the thinking in sveltejs/kit#16 - we recently made this change to baseUrl which should be considered https://github.com/sveltejs/sapper/pull/1562

This also isn't specific to hrefs since I've noticed that from the `ask` page, all references to static assets are attempting to be loaded under the `/ask/` path.

**Comment by Rich-Harris** [comment]
This is really two separate issues — #192, which we decided to close for now, and #595 which I'll close this in favour of
