### ISSUE TITLE
`svelte-kit sync` fails without `./src/routes` directory

### ISSUE THREAD

**Issue by furudean** [sveltejs/kit#5008]
### Describe the bug

When `svelte-kit sync` runs during the `prepare` hook you're met with this ugly error if you don't have a `routes` directory in `src`
```
> ENOENT: no such file or directory, scandir '/path/to/my/project/src/routes'
```

If your project primarily uses `svelte-kit package` then you don't need a `routes` directory. Since git doesn't clone empty directories the issue is a bit more serious than it seems.

### Reproduction

```
npm init svelte my-app
cd my-app
rm -rf src/routes
npm install
```

### System Info

N/A

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
@Rich-Harris I've been wanting to dig into sync. Want me to take a look?

**Comment by Rich-Harris** [comment]
that would be super helpful, thanks! i'd wager we just need to wrap https://github.com/sveltejs/kit/blob/01d9d30c1a7f71524e3fcc552bcb1f7de109f6db/packages/kit/src/core/sync/create_manifest_data/index.js#L87 in an if block, but i haven't tested that hypothesis

**Comment by tcc-sejohnson** [comment]
@Rich-Harris

Your hunch was correct! #5008. Looks like there's an issue with the Vercel deployments _and_ it was attacked by the "renders error page for missing page" test monster, but everything tests successfully when run locally on Ubuntu and Windows.
