### ISSUE TITLE
"Made With Svelte/SvelteKit" badge / logo with usage guidelines

### ISSUE THREAD

**Issue by edwinludik** [sveltejs/kit#5010]
### Describe the problem

I could not find any resources that I can add on my website to boast that I am using svelte/sveltekit. The inspiration comes from here: https://bulma.io/made-with-bulma/

### Describe the proposed solution

Provide a page with approved badges and usage instructions, similar to this: https://bulma.io/made-with-bulma/

### Alternatives considered

- Provide one badge
- A community member can create a badge
- Dont do it :-P 

### Importance

nice to have

**Comment by Mlocik97** [comment]
You can just write `made with <img src="/svelte-logos.png" />` btw, Svelte logos are available already under MIT license.

**Comment by dominikg** [comment]
https://github.com/sveltejs/branding#conditions-of-usage

**Comment by edwinludik** [comment]
Awesome thanks!
