### ISSUE TITLE
adapter-vercel — ERROR: Top-level await is currently not supported with the "cjs" output format

### ISSUE THREAD

**Issue by acarl005** [sveltejs/kit#5017]
### Describe the bug

When building the app with `@sveltejs/adapter-vercel`, and when I use top-level `await` in my server routes, I get this error:

```
.svelte-kit/output/server/entries/endpoints/helloworld.js:1:0: ERROR: Top-level await is currently not supported with the "cjs" output format
```

However, my `package.json` specifies `"type": "module"`, but it still thinks I'm using cjs when I'm not.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-qgneqz?file=src/routes/helloworld.js

Then, run `npm run build`

### Logs

```shell
npm run build
```

```
.svelte-kit/output/server/entries/endpoints/helloworld.js:1:0: ERROR: Top-level await is currently not supported with the "cjs" output format
```

### System Info

See my StackBlitz link

https://stackblitz.com/edit/sveltejs-kit-template-default-qgneqz?file=svelte.config.js,src%2Froutes%2Fhelloworld.js&terminal=dev

### Severity

serious, but I can work around it

### Additional Information

I'm using the recommended setup for a new sveltekit app, for which ECMA modules are encourages. That being the case, I believe the module features which are now built into node.js, like top-level `await`, should be usable.

**Comment by Rich-Harris** [comment]
Ah, I forgot there was a reason for holding off on merging https://github.com/sveltejs/kit/pull/4967. https://github.com/sveltejs/kit/pull/4969 would fix this, but it causes certain builds to hang in a way that I don't currently understand.

For the time being, I'd recommend pinning to [1.0.0-next.52](https://github.com/sveltejs/kit/blob/master/packages/adapter-vercel/CHANGELOG.md#100-next52) or 51.

**Comment by acarl005** [comment]
Thanks for the response, Rich! Pinning to 1.0.0-next.52 worked.

**Comment by furudean** [comment]
@Rich-Harris This seems to still happen with `1.0.0-next.56`

**Comment by furudean** [comment]
Could this issue be reopened? @Rich-Harris
