### ISSUE TITLE
Imported CSS file in layout gets "leaked" to other named layouts

### ISSUE THREAD

**Issue by yekta** [sveltejs/kit#5022]
### Describe the bug

If I import a `main.css` file in `__layout.svelte`, it also gets imported in pages that don't use that layout but instead uses another named layout such as `__layout-secondary`. This doesn't happen for component imports in layout and named layouts. Feels like it shouldn't happen for CSS either unless opted in somehow like the `global` on style tags.

This is needed to be able to share CSS files between different pages that use the same layout without them effecting other pages that don't use that layout. I tried style tags inside layouts but that throws the usual unused CSS error. So I'm not sure how I can access body, :root or other general selectors for a sets of pages that should have the same CSS without potentially importing not needed CSS from other pages.

Here is the link to see the problem:
https://stackblitz.com/edit/sveltejs-kit-template-default-f4rsjz?file=src/routes/__layout.svelte

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-f4rsjz?file=src/routes/__layout.svelte

### System Info

```shell
Using StackBlitz
```

### Severity

serious, but I can work around it

**Comment by gkatsanos** [comment]
> To create a layout that applies to every page, make a file called src/routes/__layout.svelte. 

The [documentation](https://kit.svelte.dev/docs/layouts) on Layouts is pretty clear, IMO. 
I have a strong feeling that this is the expected behaviour. CSS that you put in the `routes/__layout.svelte` is used everywhere should/would automatically be `global` implicitely - otherwise, why use the global layout?

If you want to have shared CSS across only a certain number of pages (and not all), you can nest/group these pages in a subdirectory under `/routes` so they inherit from that same sub-layout.

**Comment by Conduitry** [comment]
This is working as designed. See Rich's comment here for a similar issue: https://github.com/sveltejs/kit/issues/3622#issuecomment-1107998628

Importing a component automatically applies its styles, whether or not that component is used - and the root layout is always imported eagerly for performance - and styles in `import './file.css'` in JS are always global and not scoped to the component importing them.

**Comment by yekta** [comment]
> > To create a layout that applies to every page, make a file called src/routes/__layout.svelte.
> 
> The [documentation](https://kit.svelte.dev/docs/layouts) on Layouts is pretty clear, IMO. I have a strong feeling that this is the expected behaviour. CSS that you put in the `routes/__layout.svelte` is used everywhere should/would automatically be `global` implicitely - otherwise, why use the global layout?
> 
> If you want to have shared CSS across only a certain number of pages (and not all), you can nest/group these pages in a subdirectory under `/routes` so they inherit from that same sub-layout

> > To create a layout that applies to every page, make a file called src/routes/__layout.svelte.
> 
> The [documentation](https://kit.svelte.dev/docs/layouts) on Layouts is pretty clear, IMO. I have a strong feeling that this is the expected behaviour. CSS that you put in the `routes/__layout.svelte` is used everywhere should/would automatically be `global` implicitely - otherwise, why use the global layout?
> 
> If you want to have shared CSS across only a certain number of pages (and not all), you can nest/group these pages in a subdirectory under `/routes` so they inherit from that same sub-layout.

I’m not using the global layout for those pages, that’s the point. 

> > To create a layout that applies to every page, make a file called src/routes/__layout.svelte.
> 
> The [documentation](https://kit.svelte.dev/docs/layouts) on Layouts is pretty clear, IMO. I have a strong feeling that this is the expected behaviour. CSS that you put in the `routes/__layout.svelte` is used everywhere should/would automatically be `global` implicitely - otherwise, why use the global layout?
> 
> If you want to have shared CSS across only a certain number of pages (and not all), you can nest/group these pages in a subdirectory under `/routes` so they inherit from that same sub-layout.

When you apply a named layout, my understanding is that the things should reset. They do for component imports. Not for the CSS import. Why use the “__layout.svelte”? It’s simple really, it’s the “base” unless I reset it with a named layout. So it is to have this structure, to not use unnecessary `@s` with a “__layout-main.svelte” and to have access to selectors like body, :root etc.

`index.svelte`
`about.svelte`
`contact.svelte`
`test@secondary.svelte`
`__layout.svelte`
`__layout-secondary`

So it’s not __layout is not “global” for component imports because I can reset it. It is “global” for styles though.

After seeing the replies here and Rich’s reply in the linked issue, I do understand it’s expected behaviour. But like Rich indicated how one could consider this a bug, I’m in that camp as well.
