### ISSUE TITLE
routes with `%40` not working

### ISSUE THREAD

**Issue by half2me** [sveltejs/kit#5029]
### Describe the bug

I have a route like this: `/@[username]`.
Up until recently, I just used the `@` character as the name of the folder.
With the introduction of named layouts, I've had to get rid of the `@` character as it was failing to build, and as someone on Discord suggested, I changed it to `%40`. This worked fine locally, and all my tests passed so I made the change.

However, when actually deployed to cloudflare pages with the cloudflare adapter, it fails to fetch any `.js` files under that path. It returns an http 200, but empty content. The page usually fails either due to mimetype checks, or some other error depending on the browser.

`Failed to fetch dynamically imported module: https://<mysite>/_app/pages/%40_username_/index.svelte-71303df9.js`

### Reproduction

Using the cloudflare adapter, use a route with `%40` somewhere in the path.

### Logs

```shell
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "null". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 626.66 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.1.0 - /opt/homebrew/bin/node
    npm: 8.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-cloudflare: next => 1.0.0-next.19 
    @sveltejs/kit: next => 1.0.0-next.338 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by np-nam** [comment]
This also happens with node adapter, not only cloudflare adapter. 
Related issue: https://github.com/sveltejs/kit/issues/4403

**Comment by Rich-Harris** [comment]
Would love to see a repro of this, because I can't get a route with `%40` in the filename to work at all — not in dev, not in preview.

A workaround in the meantime would be to do something like `src/routes/[username=prefixed]` where `prefixed` is a [matcher](https://kit.svelte.dev/docs/routing#advanced-routing-matching) that verifies the username begins with `@`. It _would_ then be part of the parameter, but that should be easy to accommodate.

**Comment by half2me** [comment]
Thanks for the suggestion @Rich-Harris . The `%40` is not in the file's name, but the directory.
My file structure was `/@[username]/index.svelte` and that worked fine for me in dev locally.
