### ISSUE TITLE
Sveltekit throws developer warning when using correct fetch from load-function

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#5031]
### Describe the bug

In #4958 a helper warning was introduced if the `window.fetch` method is used instead of the `fetch` method provided by the load function. However, this warning is logged even though the correct fetch method is used.

### Reproduction

https://github.com/MathiasWP/sveltekit-window-fetch-warning-bug

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 21.08 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.64
    Edge: 101.0.1210.53
    Firefox: 100.0
    Safari: 14.1.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.44 
    @sveltejs/kit: next => 1.0.0-next.338 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
Not sure why this is happening, but I can confirm that commit d7cb8b8124320c9a5e4799923905c7cfabf4f85c (warn if load uses `window.fetch`) is where this was introduced, i.e. this is not a regression caused by a later commit.

**Comment by mrkishi** [comment]
Note: this is about `initial_fetch` using the patched `window.fetch` instead of the original.

**Comment by tcc-sejohnson** [comment]
@mrkishi

You're totally correct -- I just nailed it down. The easy fix is this: https://github.com/tcc-sejohnson/kit/tree/sejohnson-fix-fetch-warning-on-initial-fetch

The slightly-harder fix is to pass `fetch` to `initial_fetch` (adjust the `initial_fetch` signature to accept `fetch`).

Given that this is a dev-mode thing for ergonomics, I don't see much of an issue just checking the stack trace for `initial_fetch` as seen in the linked branch. If we want to do that, I'll open a PR. If not, happy to make the adjustments necessary to not use the patched `window.fetch`.

**Comment by Rich-Harris** [comment]
I have a fix in a branch, one sec...
