### ISSUE TITLE
syntax error in cli.js

### ISSUE THREAD

**Issue by susanmonnelly** [sveltejs/kit#5032]
### Describe the bug

https://github.com/sveltejs/kit/blob/29ef2e2ecf8ee1a1d57b667fbb933b929d9b0801/packages/kit/src/cli.js#L289

unexpected token error

				} else if (allow?.length && cwd) {

should be 

				} else if (allow.length && cwd) {

### Reproduction

This error occurred while attempting to set up svelte kit in a colima/docker/ddev container environment

### Logs

```shell
Output from the ddev startup up using a docker file 

#23 [ddev-readex_svelte-kit-app deps 6/6] RUN npm run build
#23 sha256:0a4ba19945111a69aa6f548924f350046852031aa8a19a644cc786ecc2db4e66
#23 0.837 
#23 0.837 > svelte-kit@0.0.1 build /app
#23 0.837 > svelte-kit build
#23 0.837 
#23 0.907 file:///app/node_modules/@sveltejs/kit/dist/cli.js:1121
#23 0.907                                       } else if (allow?.length && cwd) {
#23 0.907                                                        ^
#23 0.907 
#23 0.907 SyntaxError: Unexpected token '.'
#23 0.907     at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
#23 0.916 npm ERR! code ELIFECYCLE
#23 0.916 npm ERR! errno 1
#23 0.921 npm ERR! svelte-kit@0.0.1 build: `svelte-kit build`
#23 0.923 npm ERR! Exit status 1
#
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 19.53 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    npm: 8.6.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.2
    Safari: 15.4
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment]
This is called optional chaining and supported in node14 and above, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility

Please verify that you are running node16 or node18 inside the container, the system info you posted seems to be from your host os.

**Comment by susanmonnelly** [comment]
ahh thank you!  I upgraded to Node 16 and it works fine - sorry about that!
