### ISSUE TITLE
CI: Failed to publish create-svelte

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#504]
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/create-svelte - You do not have permission to publish "create-svelte". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

Not sure why but `2.0.0-next.31` wasn't published alongside the other packages.

https://github.com/sveltejs/kit/runs/2095960157

**Comment by Rich-Harris** [comment]
well that's odd. i just ran `pnpm release` locally and it succeeded, so maybe it was just an npm glitch? will close this for now and see what happens

**Comment by Conduitry** [comment]
Which users owned the token that you were publishing with when you did it locally and when it was attempted by CI? Was it your personal npm account locally, and the svelte-admin user in CI? That could be a difference. Although that wouldn't explain why it succeeded all the other times.
