### ISSUE TITLE
Don't include tsconfig.json in non-TypeScript projects

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#506]
If you create a standard JS project with `npm init svelte@next` then there's a [`tsconfig.json` file](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/template/tsconfig.json). It doesn't seem like it should be there and it was reported on Discord to have been creating problems in VS Code (which I'm fixing in https://github.com/sveltejs/kit/pull/507)

**Comment by dummdidumm** [comment]
It should be nothing, or a jsconfig which I think will help editor intellisense.

**Comment by benmccann** [comment]
If we rename to `jsconfig.json` we should remove `allowJS` which isn't supported in that file
