### ISSUE TITLE
Start from version `1.0.0-next.337` to current `1.0.0-next.343` , use `[...path].svelte` will overwrite assets import urls

### ISSUE THREAD

**Issue by TrungRueta** [sveltejs/kit#5066]
### Describe the bug

start from version `1.0.0-next.337` to current `1.0.0-next.343`. when define a route file to catch error 404 (file named `[...path].svelte`) , it will catch asset urls imported in source too. This issue not happend until ver `1.0.0-next.336` . 

[Change log 337](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next337)

i guess that the change in v*.337 regards to 
`Only run viteServeStaticMiddleware after server has attempted response (https://github.com/sveltejs/kit/pull/4974)` will be cause. But dont know how to help fix.

### Reproduction

- create new fresh svelte-kit project use `npm init svelte <folder project name>`
- add image into `/src/lib/assets/a.jpg`
- from file `/src/routes/index.svelte` import image to `<script>` block, then create `<img>` tag in template.
- in `/src/routes` create new file name `[...path].svelte`, define some html like a 404 catcher page.
- run `npm run dev`. see image url in chrome devtool will redirect to `[...path].svelte` page .
- rename file `[...path].svelte` to `[path].svelte`. run dev serer again, see img show correctly.
- try add file `[...path].svelte again, then run build `npm run build` and then `npm run preview`, the built version work ok so issue only happend with dev mode.

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 81.88 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.3
  npmPackages:
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
closed via #5070
