### ISSUE TITLE
Ability to execute fetching in a dedicated server

### ISSUE THREAD

**Issue by Tal500** [sveltejs/kit#5080]
### Describe the problem

Possibly duplicate, since Rich always talks about serverless, but didn't find any serious place it is being discussed.
Right now, especially because of Cloudflare Workers and Amazon Edge, people are thinking(and doing!) about running the frontend/SSR server in many locations wordwide by the mechanisms I mentioned before.
That gives the user the ability to SSR the initial result to the HTTP page from the nearest server, while reducing the computation efforts needed from the centeral backend server(s). It also might yield faster responses.

Since developer care about persistency and consistency, there is still a main backend server in a single(or sometimes in many) specific data centers.
That means, for fetching a page in SSR, the frontend server, running sveltekit instancey(e.g. with the adapter of cloudflare workers), is sending REST requests to the backend, while processing the sveltekit `load` function.

The problem is that in the `load` function, the SSR server might invoke many remote IO calls, or even need to wait for a return of an HTTP response for sending another HTTP request(for example, the first might be an auth request since the second need to use the credentials from the first).
Usually, because of a geographic gap, it is much easier and faster to compute the `load` function only in the backend.

### Describe the proposed solution

Have the ability to execute a server that only answer the result of the `load` function, and also execute an SSR server calling for the former server for the response of `load`, instead of computing it by itself.
This way, in the centeral backend(s) the former will be executed, and the goe-spread SSR servers will enjoy easy and fast networking, and their job is only to precompute the HTML output, the same as what the user client should do.

### Alternatives considered

Two obvious alternative:
* Just give up on the geo-spreading concept and compute SSR in the main server(s).
* Manually code the `load` function to send only a one HTTP big request designed specifically for every route. This isn't convenient for the backend developers. Additionally, this doesn't cover the separation of `__layout.svelte` which have additional `load` function.

### Importance

nice to have

**Comment by Conduitry** [comment]
A lot of this sounds exactly like https://kit.svelte.dev/docs/routing#endpoints-page-endpoints - combine all of the requests for a page in one page endpoint that backs the page, and (automatically) make only that one request from the browser. Are you talking about something that wouldn't be covered by that?

**Comment by Tal500** [comment]
> A lot of this sounds exactly like https://kit.svelte.dev/docs/routing#endpoints-page-endpoints - combine all of the requests for a page in one page endpoint that backs the page, and (automatically) make only that one request from the browser. Are you talking about something that wouldn't be covered by that?

Hi!
Page Endpoints are just (good) alternative to the page/layout `load` function.

I'm seeking for the ability to compute the `load` or the page endpoint in a different server than the server instance which computes the initial SSR HTML response for the client.

**Comment by benmccann** [comment]
This all sounds like userland concerns to me. E.g. you can create one app for the endpoints and deploy it separately from your frontend app

**Comment by Tal500** [comment]
> This all sounds like userland concerns to me. E.g. you can create one app for the endpoints and deploy it separately from your frontend app

Didn't fully understand you.
You're suggesting to do exactly what I wish: the user may already run one server instance delivering only endpoints/load function result, and another server instance (in an endpoint) for the user server, which the latter sends exactly one(or zero perhaps) HTTP request per page for the former server.

Do you mean you can already do it automatically in SvelteKit right now? For me, it seems you need to add an ability in the adapter API, allowing the adapter to build one instance of "preloading" server, and another instance of "SSR only" server.

Or you might suggest by the "user land" that the user should write the code yielding the page data in a project separated from SvelteKit? I think it goes against what the project designed for.

**Comment by benmccann** [comment]
If you want your SSR server to make a single request to an API endpoint then you can write your application that way today. E.g. that's why GraphQL has become popular - you can write one query that joins together the different pieces of data into a single request

**Comment by Tal500** [comment]
> If you want your SSR server to make a single request to an API endpoint then you can write your application that way today. E.g. that's why GraphQL has become popular - you can write one query that joins together the different pieces of data into a single request

You right about it, but since SvelteKit is a flexible toolkit, can't we allow this out of the box?

I want to clarify again what I said since I see it's confusing, and also give a simple real life example.
Right now, the server node that SvelteKit generates(with the help of the adapters) works as follows (as far as I'm aware of):
**Currently Frontend Server:**
* For every HTTP request:
  * For every layout component (sequentially), and also for the page component of the requested page (at the end):
    1. Process `load` or page endpoint (if any).
    2. Substitute the data from 1 in the component props.
    3. Calculate the SSR result of the component(page/layout).
  * Combine them all together to an HTML output, and send this as an HTTP response.

The thing that seems so natural for me, is to decouple step 1 from this process, and getting the following two servers:
**New Frontend Server:**
* For every HTTP request:
  * Call the intermediate server(see next) and ask the JSON-formatted props data for the specific page.
  * For every layout component (sequentially), and also for the page component of the requested page (at the end):
    1. Substitute the data of the relevant component, given by the intermediate server, in the component props.
    2. Calculate the SSR result of the component(page/layout).
  * Combine them all together to an HTML output, and send this as an HTTP response.

**Intermediate Server:**
* For every data request:
  * For every layout component (sequentially), and also for the page component of the requested page (at the end):
    1. Process `load` or page endpoint (if any).
  * Combine them all together to a JSON-formatted props data, and send this as a response.

I shall mark the generation and the communication between the new frontend server and the intermmediate server should be implemented in the adapter implementation by itself, this is my "user land".

In modern real life the user might put the new frontend server in the endpoint, and the intermediate server and the main backend(usually needed for logical decoupling) in its data center(s).
The advantages of this system, is that we'd have an automatic, simple and fast way to geo-spread the endpoints for efficiency, and yet avoid too much networking latency issues.

I'll mention two main examples, usually happen together, which demonstrate why my suggestion is useful, and it is hard to fix these issues in "user land":
1. A layout inside layout for a page: You will need to perform loading for the first layout and wait for response, and then perform loading for the second layout and wait for response, and then to the same for the page itself. -> Three rounds of communication
2. Call fetch A, and wait for the result. Sometimes you'd need to process the data of A in order to know what another request B you need to perform. (You can view here maybe some auth mechanism e.g.) -> Two rounds of communication

The solution I proposed doesn't decrees the number of rounds, but make the latency in between possible much shorter, since both the intermediate and the backend server can be in the same data center or even in the same machine.

**Comment by Rich-Harris** [comment]
By design, it's not possible to separate SSR from `load` — you can return non-serializable things from it, like (for example) components. This is an important use case that can't be handled with JSON, so I'm afraid this is a non-starter.

As mentioned, page endpoints (and soon, layout endpoints) are designed to make it possible to fetch all the data for a page that _doesn't_ use `load` in a single go. But for pages with those endpoints, there's nothing to be gained by separating the data from the SSR — no matter how geographically distributed and instant-to-start-up your 'SSR nodes' are, browser -> SSR node -> data node will _never_ be faster than if the browser makes a request direct to a server that computes the HTML response in the same place as the data lives.

**Comment by Tal500** [comment]
> By design, it's not possible to separate SSR from `load` — you can return non-serializable things from it, like (for example) components. This is an important use case that can't be handled with JSON, so I'm afraid this is a non-starter.
> 
> As mentioned, page endpoints (and soon, layout endpoints) are designed to make it possible to fetch all the data for a page that _doesn't_ use `load` in a single go. But for pages with those endpoints, there's nothing to be gained by separating the data from the SSR — no matter how geographically distributed and instant-to-start-up your 'SSR nodes' are, browser -> SSR node -> data node will _never_ be faster than if the browser makes a request direct to a server that computes the HTML response in the same place as the data lives.

You're totally right but you forgot one thing - load balancing.
Serverless is not only about geo-minimal-latency, but also good for balancing work load.

If a non-state-critical task can be on specific backend(s), and the rest of the work can be done in every edge location, you gain a much more robust system (both for DDoS and for global load balancing).

**Comment by Tal500** [comment]
> By design, it's not possible to separate SSR from `load` — you can return non-serializable things from it, like (for example) components. This is an important use case that can't be handled with JSON, so I'm afraid this is a non-starter.
> 
> As mentioned, page endpoints (and soon, layout endpoints) are designed to make it possible to fetch all the data for a page that _doesn't_ use `load` in a single go. But for pages with those endpoints, there's nothing to be gained by separating the data from the SSR — no matter how geographically distributed and instant-to-start-up your 'SSR nodes' are, browser -> SSR node -> data node will _never_ be faster than if the browser makes a request direct to a server that computes the HTML response in the same place as the data lives.

For potential future reference - The latency problem of the layout loading before page can be fixed by #5748 .
