### ISSUE TITLE
Can't `location.assign(url)` in `load()` function: throws `Illegal invocation`

### ISSUE THREAD

**Issue by georgecrawford** [sveltejs/kit#5083]
### Describe the bug

I have a fallthrough route, which I want to _always be server-rendered_. The use-case is that we're migrating from Angular to SvelteKit, and any pages which SvelteKit doesn't recognise should:
- if invoked client-side, reload the URL to force a SSR
- return a page which boots AngularJS, with no hydration or SvelteKit router
- this ensures that only AngularJS is running in the browser, as SvelteKit will not send any of its own JS with the SSR response

The fix for [this issue](https://github.com/sveltejs/kit/issues/4788) (PR [here](https://github.com/sveltejs/kit/pull/4983)) introduced a `Proxy` wrapper for the `url` input parameter to the `load()` function. This now causes my browser-side interceptor code to throw a `TypeError: Illegal invocation`.

### Reproduction

Click the link to the fallthrough page in this repro: https://stackblitz.com/edit/sveltejs-kit-template-default-cn2bpx?file=src%2Froutes%2F[...fallthrough].svelte&terminal=dev, and you'll see:

```
500
Illegal invocation
TypeError: Illegal invocation
    at load (https://sveltejs-kit-template-default-cn2bpx--3000.local.webcontainer.io/src/routes/[...fallthrough].svelte?t=1653555167052:81:12)
    at load_node (https://sveltejs-kit-template-default-cn2bpx--3000.local.webcontainer.io/@fs/home/projects/sveltejs-kit-template-default-cn2bpx/.svelte-kit/runtime/client/start.js:1029:33)
    at load_route (https://sveltejs-kit-template-default-cn2bpx--3000.local.webcontainer.io/@fs/home/projects/sveltejs-kit-template-default-cn2bpx/.svelte-kit/runtime/client/start.js:1147:20)
    at async update (https://sveltejs-kit-template-default-cn2bpx--3000.local.webcontainer.io/@fs/home/projects/sveltejs-kit-template-default-cn2bpx/.svelte-kit/runtime/client/start.js:626:38)
    at async navigate (https://sveltejs-kit-template-default-cn2bpx--3000.local.webcontainer.io/@fs/home/projects/sveltejs-kit-template-default-cn2bpx/.svelte-kit/runtime/client/start.js:1372:3)
```

Change the `location.assign(url)` to `location.assign(url.href)` and it works fine.

### System Info

```shell
`@sveltejs/kit@1.0.0-next.345`
```

### Severity

serious, but I can work around it

### Additional Information

This may purely be a documentation/education thing. The [docs say](https://kit.svelte.dev/docs/loading#input-url) **`url` is an instance of [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL)**, but that's not entirely true, as the implicit casting to string with `location.assign(url)` is broken by the Proxy wrapper. Either we should document that limitation, or, if possible, improve the Proxy with a `toString()` method or whatever is required.

**Comment by georgecrawford** [comment]
This works, but I have to admit I don't know enough about Proxies or whether this is a good idea!

**Before**:
```
return new Proxy(url, {
    get: (target, property) => {
        if (property === 'hash') {
            throw new Error(
                'url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.'
            );
        }

        return Reflect.get(target, property, target);
    }
});
```

**After**:
```
return new Proxy(url, {
    get: (target, property) => {
        if (property === 'hash') {
            throw new Error(
                'url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.'
            );
        }

        if (property === 'toString') {
            return target[property].bind(target);
        }

        return Reflect.get(target, property, target);
    }
});
```

**Comment by Rich-Harris** [comment]
That's very strange — the proxy should be completely transparent, unless you're accessing `hash`. What happens if you make this change instead?

```diff
return new Proxy(url, {
-    get: (target, property) => {
+    get: (target, property, receiver) => {
        if (property === 'hash') {
            throw new Error(
                'url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.'
            );
        }

-        return Reflect.get(target, property, target);
+        return Reflect.get(target, property, receiver);
    }
});
```

I think that's the more _correct_ way to do it, though we got into the habit of passing `target` instead of `receiver` because of a weird bug we stumbled upon in Cloudflare Workers (though the details completely escape me).

**Comment by georgecrawford** [comment]
No dice, sadly.

```
const url = new URL(location.href);
const proxy = new Proxy(url, {
    get: (target, property, receiver) => {
        if (property === 'hash') {
            throw new Error(
                'url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.'
            );
        }

        return Reflect.get(target, property, receiver);
    }
});

console.log(String(proxy));
```

```
Uncaught TypeError: Illegal invocation
    at String (<anonymous>)
    at Script snippet #1:18:13
```

**Comment by georgecrawford** [comment]
if you add `console.log(property);`, you'll see that it throws on trying to run the `toString` method.

**Comment by tcc-sejohnson** [comment]
Ouch, sorry @georgecrawford -- I hate that my PR bit you in the bum (though I _will_ say, it was Rich's idea to use a `Proxy`)... 😉 

@Rich-Harris / @georgecrawford 

This will fix the issue (I tested in the browser with basically every method on the `url` instance). Can you guys test and let me know if I'm missing anything?

```ts
new Proxy(url, {
    get: (target, property, receiver) => {
        if (property === 'hash') {
            throw new Error(
                'url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.'
            );
        }

        if (!(property in target)) {
          return undefined;
        }
        const value = target[property];
        return typeof value === "function"
          ? (...args) => value.apply(target, args)
          : value;
    }
});
```

This is a little more invasive than I like. I adapted it from [a StackOverflow issue](https://stackoverflow.com/questions/48535551/is-it-possible-to-use-proxy-with-native-browser-objects-htmlelement-canvas2dre), where the author says: 

> As pointed out in the comments below, I completely neglected to test for the method calls on the host object, which, it turns out, are all protected. This comes down to weirdness in the host objects, which get to play by their own rules.

> ...

> Here, I am still "getting" the method off of the original object, to call it. It just so happens that in the case of the value being a function, I call bind to return a function that maintains the this relationship to the original context. Proxies usually handle this common JS issue.

**Comment by tcc-sejohnson** [comment]
@Rich-Harris 

An altogether less-invasive solution:

```ts
const loadUrl = new URL(url);
Object.defineProperty(loadUrl, 'hash', {
  get: () => { throw new Error('url.hash is inaccessible from load. Consider accessing hash from the page store within the script tag of your component.') }
});
```

We keep all of the benefits of a native URL instance, but replace the 'hash' property with our own error-throwing getter.

Happy to open a PR to fix if you like either of these.
