### ISSUE TITLE
SvelteKit keeps repeating redirect behaviour

### ISSUE THREAD

**Issue by EmilePW** [sveltejs/kit#5084]
### Describe the bug

About 30 minutes ago I added the following code for my personal website on `index.svelte`:
```
<script context="module">
	export async function load({}) {
		return {
			status: 301,
			redirect: '/about'
		};
	}
</script>
```

I've just now created and opened an entirely separate project using SvelteKit. After installing and doing `npm run dev`, SvelteKit is still redirecting to `/about` in this new project on the default port 3000. I went back to the previous project, commented out the above code and tried `npm run dev` again - it's still redirecting to `/about`.

Tried restarting my Macbook and still the same problem. Also tried deleting the `.svelte-kit` directory and still the same problem.

I've gotten around by running it on a different port but not sure how to properly resolve this - any ideas?

### Reproduction

I've made my personal website repo public here: https://github.com/EmilePW/personal-website.git

It can be run locally with `npm install` and `npm run dev` but I assume this isn't actually going to actually help that much. I'm not sure how to inspect the SvelteKit internals to really look at the problem.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 73.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 102.0.5005.61
    Firefox: 89.0.2
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.48 
    @sveltejs/kit: next => 1.0.0-next.345 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301 301 is moved permanently. The redirect will be cached in your browser, and your app won't even be hit. Clear your cache, and then use a different redirect response if you don't want this behavior.
