### ISSUE TITLE
trailingSlash: "always" changes external URLs

### ISSUE THREAD

**Issue by Renkas** [sveltejs/kit#5087]
### Describe the bug

When using configuration: `trailingSlash: "always"` then external URLs will also get a trailing slash.

There is a workaround if you set some kind of taget to the anchor element. For example `target="_self"` but it's still a bug that shoud be fixed.

### Reproduction

You can see repro: https://sveltejs-kit-template-default-tq3lbk--3000.local.webcontainer.io/

"Click me" should link to the URL: https://example.com/foo.php?bar=baz&more=params
But it actually navigates to: https://example.com/foo.php/?bar=baz&more=params

Notice the extra slash before the question mark.

You can see source of this example: https://stackblitz.com/edit/sveltejs-kit-template-default-tq3lbk?file=src/lib/header/Header.svelte

### System Info

```shell
not applicable
```

### Severity

annoyance

**Comment by babichjacob** [comment]
A workaround right now is adding `rel="external"` to the `a` tag to mark the link as external.

(To other maintainers: I hope I got the labels right.)

**Comment by zmre** [comment]
I'm seeing similar problems, but it is even worse. I have a statically generated site and the HTML has the links right (no trailing slash), but on click, something adds the slash before navigating.  This happens for external links, but also to internal links to static assets like PDFs. So `<a href="/pdfs/xyz.pdf">Download PDF</a>` is generated correctly, but if someone clicks it, they get a 404.  The `rel="external"` trick doesn't make sense for the static asset use case. Finding and modifying all of the links to add extra attributes isn't ideal, so I'm hoping someone picks this up.  The broken links on our site are not a good look.

**Comment by zmre** [comment]
Update: the `target="_self"` trick does not seem to work for me as a workaround -- at least not when the link is to a local asset. The problem also happens when referencing things like images.

**Comment by PatrickG** [comment]
> [...] The `rel="external"` trick doesn't make sense for the static asset use case. Finding and modifying all of the links to add extra attributes isn't ideal, so I'm hoping someone picks this up. The broken links on our site are not a good look.

You can use `rel="external"`, the `download` attribute or the `sveltekit:reload`, see https://github.com/sveltejs/kit/blob/373ff63433cfca3ac7119a5d6da7956dfb5f4740/packages/kit/src/runtime/client/client.js#L1158
I think, in your case I would use the `download` attribute.

**Comment by zmre** [comment]
Nice, the [sveltekit-reload](https://kit.svelte.dev/docs/a-options#sveltekit-reload) option looks like the "right" way to bypass the javascript navigation when that's needed and that will workaround. Appreciate the code reference.

The function that adds the slash is here: https://github.com/sveltejs/kit/blob/373ff63433cfca3ac7119a5d6da7956dfb5f4740/packages/kit/src/utils/url.js#L49

Seems like it could detect non-relative links easy enough, but unfortunately, I'm not sure how that function (or the navigate function that calls it) might be able to discern static assets from routes before adding the slash.  For now I guess I'll go annotate all the links I can find that are broken, but hopefully someone with more experience in Svelte Kit can craft a fix.
