### ISSUE TITLE
An error can run in develop mode, but this error is reported in production mode

### ISSUE THREAD

**Issue by ddy-ddy** [sveltejs/kit#5102]
### Describe the bug

- When i run in develop mode, all of my code and web pages work fine. but when i used production mode, one of my svelte files didn't run(load function include in this files)
- when i click on the category page(the corresponding svelte file is `category-[id].svelte` and `category-[id].json.js`)
- it works in `num run develop` , but not work in `npm run preview`
![category-[id].svelte](https://tva1.sinaimg.cn/large/e6c9d24egy1h2olblu8d4j214o0m6jv8.jpg)
![category-[id].json.js](https://tva1.sinaimg.cn/large/e6c9d24egy1h2olery76pj21jm0u047f.jpg)
- #### I got a error like this.
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2oldm733yj21jd0u0k0q.jpg)
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2olhf7osij220k0byjuy.jpg)
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2olhh0yyoj21d30u00xz.jpg)

### Reproduction
- repository: [https://github.com/ddy-ddy/ddy-website](https://github.com/ddy-ddy/ddy-website)
- `npm install`
- `npm run build`,
- if `npm run dev`, all pages are working.
- if `npm run preview`, clink `摄影`->`分类`->`景物`, it doesn't work!
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2ozvpf3cdj22640u00vc.jpg)
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h2ozwaubq5j21qs0u0wfl.jpg)

### Logs

```shell
(base) zhengyan@duanyudeMacBook-Pro ddy-website % npm run preview

> ddy-website@0.0.1 preview
> svelte-kit preview

  SvelteKit v1.0.0-next.326

  local:   http://localhost:3000
  network: not exposed
  network: not exposed
  network: not exposed

  Use --host to expose server to other devices on this network

ReferenceError: i is not defined
    at get (file:///Users/zhengyan/Desktop/ddy-website/.svelte-kit/output/server/entries/endpoints/api/photography/category-_id_.json.js:9:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async render_endpoint (file:///Users/zhengyan/Desktop/ddy-website/.svelte-kit/output/server/index.js:186:20)
    at async resolve (file:///Users/zhengyan/Desktop/ddy-website/.svelte-kit/output/server/index.js:2189:53)
    at async respond (file:///Users/zhengyan/Desktop/ddy-website/.svelte-kit/output/server/index.js:2146:22)
    at async file:///Users/zhengyan/Desktop/ddy-website/node_modules/@sveltejs/kit/dist/chunks/index5.js:139:5
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 21.69 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.64
    Safari: 15.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.40
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73
    @sveltejs/kit: next => 1.0.0-next.326
    autoprefixer: ^10.4.7 => 10.4.7
    daisyui: ^2.14.3 => 2.14.3
    nprogress: ^0.2.0 => 0.2.0
    postcss: ^8.4.13 => 8.4.13
    svelte: ^3.44.0 => 3.48.0
    svelte-typewriter: ^3.0.0-alpha.11 => 3.0.0-alpha.11
    sveltekit-embed: ^0.0.5 => 0.0.5
    tailwindcss: ^3.0.24 => 3.0.24
```

### Severity

serious, but I can work around it

### Additional Information
- this is the first time for me to submit issue in svelte-kit community, there are a lot of irregularities please point out and criticize. ♪(･ω･)ﾉ
- hope there's a great man who can help me (๑′ᴗ‵๑)
_No response_

**Comment by Conduitry** [comment]
We need a clonable repository with a minimal reproduction.

**Comment by ddy-ddy** [comment]
> 

I have modified it according to your requirements. (#^.^#)

**Comment by tcc-sejohnson** [comment]
I'm more curious how this would work in dev, as it shouldn't work in either environment:

```diff
- for (i = 0; i < number, i++) {
+ for (let i = 0; i < number, i++) {
```

The error is telling you what's wrong. `i` isn't declared (you need to use `let` or `var`).

**Comment by ddy-ddy** [comment]
> 
- Oh my god. I made a such stupid mistake. Thank you so much. I solved this problem. 
- I'm just as curious as you as to why this stupid code work in dev. It is possible that dev mode is less stringent about code review?

**Comment by gtm-nayan** [comment]
Probably this?
![image](https://user-images.githubusercontent.com/50981692/170870354-8055a27f-2264-4ac5-9205-7d758241423d.png)

**Comment by ddy-ddy** [comment]
> Probably this?
> 
> ![image](https://user-images.githubusercontent.com/50981692/170870354-8055a27f-2264-4ac5-9205-7d758241423d.png)
> 
> 

yes. The i is not declared. Thank you so much (•̀ᴗ•́)و

**Comment by tcc-sejohnson** [comment]
@ddy-ddy 

Happens to all of us! 😉
