### ISSUE TITLE
Swap out `node-fetch` for `undici`

### ISSUE THREAD

**Issue by rmunn** [sveltejs/kit#5113]
### Describe the problem

https://github.com/sveltejs/kit/pull/4934 had a checklist step "swap out `node-fetch` for `undici`, which is more standards compliant (though I think we're blocked on https://github.com/nodejs/undici/issues/1262)". https://github.com/nodejs/undici/issues/1262 has just been closed via https://github.com/nodejs/undici/pull/1469, so it may be time to look again at swapping out `node-fetch`, at least once https://github.com/nodejs/undici/pull/1469 makes its way into an actual Node release.

### Describe the proposed solution

Swap out `node-fetch` for `undici` as described in https://github.com/sveltejs/kit/pull/4934#issue-1236378590

### Importance

would make my life easier

### Additional Information

This should allow us to make progress on https://github.com/sveltejs/kit/issues/3419 as well (see https://github.com/sveltejs/kit/pull/4934#issuecomment-1127679552).

**Comment by OttoHatt** [comment]
I believe this'll be blocked by sveltejs/kit#5109 (cloudflare wrangler also uses Undici for requests).

**Comment by rmunn** [comment]
> I believe this'll be blocked by #5109 (cloudflare wrangler also uses Undici for requests).

#5109 is marked as fixed by #5116, which has been [released in `next.346`](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next346). I can't confirm that the fix works on Cloudflare as I don't have any Cloudflare sites set up at the moment; @OttoHatt, can you confirm that it works?

**Comment by OttoHatt** [comment]
yes! on the newest version, #5109 is fixed.
