### ISSUE TITLE
404 when going to a url directly

### ISSUE THREAD

**Issue by mbakker96** [sveltejs/kit#5126]
### Describe the bug

I've compiled my sveltekit website with adapter-static. But when I compile the page and set it live I get an error when I go to a page directly. for example .nl/contact. Then I receive a 404. 

I tried to fix this with a .htaccess file, but that caused problems like a page load when navigating. 

When adding contact.html it works fine, but navigating to .nl/contact gives a 404

uses case:
-> *.nl -> contact button -> .nl/contact works fine
-> *.nl/contact.html works fine
-> *.nl/contact gives a 404.

### Reproduction

-> *.nl -> contact button -> .nl/contact works fine
-> *.nl/contact.html works fine
-> *.nl/contact gives a 404.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 163.46 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 96.0.3
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.34 
    @sveltejs/kit: 1.0.0-next.326 => 1.0.0-next.326 
    svelte: 3.48.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

svelte.config.js
```
import preprocess from 'svelte-preprocess';
// import node from '@sveltejs/adapter-node';
import adapter from '@sveltejs/adapter-static';

/** @type {import('@sveltejs/kit').config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false,

		}),

		prerender: {
			// This can be false if you're using a fallback (i.e. SPA mode)

			default: true
		}
	}
};

export default config;
```

![image](https://user-images.githubusercontent.com/10044261/171269017-e93b8ebf-b316-4bd5-b880-106b1dfd5c05.png)

my .htaccess is empty.

**Comment by Conduitry** [comment]
See #4404.
