### ISSUE TITLE
Support forwarding more options to vite in config file

### ISSUE THREAD

**Issue by andy0130tw** [sveltejs/kit#5127]
### Describe the problem

When spinning up a Vite server, SvelteKit only passes some entries to Vite. This is expected from [the documentation](https://kit.svelte.dev/docs/configuration#vite):

> [...] SvelteKit will prevent you from setting certain build-related options since it depends on certain configuration values.

This is, however, somehow misleading because only `plugins` and `server.https` are read from this object, and all other options are ignored ([source code](https://github.com/sveltejs/kit/blob/a344dcafaa36447c6b64fa13239b3b78be813349/packages/kit/src/cli.js#L68)). For example, given the following config file `svelte.config.js`:

```
import adapter from '@sveltejs/adapter-auto'

const config = {
  kit: {
    adapter: adapter(),
    vite: {
      clearScreen: false,
    },
  },
};

export default config
```

The entry `kit.vite.clearScreen` will not be passed to the Vite dev server.

### Describe the proposed solution

I hope that I can pass more options to Vite, or at least forbid it clearing my screen :)

### Importance

nice to have

**Comment by benmccann** [comment]
I believe this should be fixed in @sveltejs/kit@1.0.0-next.349
