### ISSUE TITLE
SvelteKit doesn't support older browsers in development mode due to nullish coalescing operator usage in @sveltejs/kit/assets/client/start.js

### ISSUE THREAD

**Issue by josetr** [sveltejs/kit#5130]
### Describe the bug

See https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/client.js where these two features are used:

* Nullish coalescing operator - https://caniuse.com/mdn-javascript_operators_nullish_coalescing
* Optional chaining  - https://caniuse.com/?search=Optional%20chaining

This is very problematic because browsers for mobile added support very late:

* Chrome for Android supports it since April 27, 2022.
* Firefox for Android support it since May 3, 2022.

### Reproduction

-

### System Info

```shell
-
```

### Severity

annoyance

**Comment by PatrickG** [comment]
The supported mobile browser on caniuse.com seem to only show the current browser version.
[According to MDN the nullish coalescing operator is supported since april 2020 on chrome and july 2020 on firefox](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#browser_compatibility).

**Comment by Conduitry** [comment]
@josetr Are you actually seeing browsers where this isn't supported, or is this report just based on what caniuse is showing? I'm almost positive that Android Firefox and Chrome supported this prior to their most recent versions - but that information just isn't available on caniuse for whatever reason, as @PatrickG noted.

**Comment by josetr** [comment]
@PatrickG @Conduitry 

I had an old iPad which I wanted to use to connect to my local SvelteKit website but they all wouldn't support both operators at the same time.

Browsers: 

Chrome version 92.0.4515.90 which was released 10 months ago according to the App Store.
Opera version 3.2.17 which was released 10 days ago according to the App Store.
Safari 12,5,2

**Comment by Rich-Harris** [comment]
I'm going to close this, as it's simply not practical to support ancient browsers in `dev`. `svelte-kit preview` exists to make it possible to check the production build against those browsers.

**Comment by josetr** [comment]
@Rich-Harris

* Doesn't seem too fair to call Safari IOS 13.3 that was released in 2020 an "ancient browser".
* Claiming it's not practical to support older browsers even tho we have been transpiling / converting code for so long isn't that fair either.
* Using `svelte-kit preview` every day isn't practical either.

Libraries that are supposed to be used widely are not supposed to break often. I guess this is why some people hate the npm ecosystem.

**Comment by dominikg** [comment]
These legacy browsers are supported in preview and production builds.

For dev, a modern browser is required. 

safari ios < 13.4 has less than 1% market share. 
https://browserslist.dev/?q=aW9zX3NhZiA8MTMuNA%3D%3D

And this will even be less for developers wanting to use it for dev mode. 

It would not be fair to spend time writing less idiomatic/optimal code and serve it to >99% of users just so that the other <1% can use a legacy browser instead of updating.

To reiterate: You can test on older devices with preview just fine. Only dev mode isn't supported.

**Comment by josetr** [comment]
> These legacy browsers are supported in preview and production builds.
For dev, a modern browser is required.

Why should it be different when you have the tools to avoid that?

Is it not the goal to make dev / production builds as similar as possible?

> safari ios < 13.4 has less than 1% market share.

It has a 1.2% percent market share which is translated to 8% of Safari users.

> It would not be fair to spend time writing less idiomatic/optimal code

None writes less idiomatic / optimal code to support old browsers. You just convert the code as needed. If you provide the config `kit.vite.build.target` and the developer sets it to `ES2015`, why shouldn't the developer expect SvelteKit to honor it in every build type?

>  and serve it to >99% of users just so that the other <1% can use a legacy browser instead of updating.

The 99% of users are already getting served non-optimal code because the default `kit.vite.build.target` isn't `ES2020`. I'm just saying developers should get served the same non-optimal code as the normal users do if they are explicitly requesting it.

**Comment by jaider** [comment]
Using the latest Mac and still seems this error, so I cannot run learn module https://learn.svelte.dev/tutorial/classes

**Comment by dominikg** [comment]
@jaider  learn.svelte.dev uses webcontainers under the hood which is only supported in very recent versions of safari https://blog.stackblitz.com/posts/webcontainers-are-now-supported-on-safari/   Please update your browser or use firefox/chrome to access it.
