### ISSUE TITLE
sveltekit d3 problems / shows unexpected behavior for  bind:clientWidth and bind:clientHeight compared to a normal svelte project

### ISSUE THREAD

**Issue by delight** [sveltejs/kit#5134]
### Describe the bug

Trying to use d3 with sveltekit I stumbled upon unexpected behavior.

For demo purposes I took the svelte project [`simple-svelt-chart`](https://github.com/higsch/simple-svelte-chart) and migrated it into a simple sveltekit project  [`simple-svelt-chart-kit`](https://github.com/delight/simple-svelte-chart-kit).

Doing so it shows strange behaviors regarding the calculated **_width_** and **_height_**.

Contrary to a simple svelte project it won't get calculated at render time but later. 

I created 2 branches with partly solutions that are still faulty / defective. 

In the branch "solution/unconditionalRendering" it renders the graph (unconditionally if width and height are available yet) including some NaN errors in the browser console (SVG translate)

In the branch "solution/presetingWidthAndHeight" I simply did preset a value for the width and height property, resulting in a rendered and secondly adjusted graph.

What is really weird with both "solutions" is the behavior when changing the window size. It results in an graph enlarging itself in height endlessly.

### Reproduction

Try the sveltekit demo project I created for this purpose  [`simple-svelt-chart-kit`](https://github.com/delight/simple-svelte-chart-kit) ... I used the svelte project [`simple-svelt-chart`](https://github.com/higsch/simple-svelte-chart) as a simple comparable base.

Don't forget to switch into the solution ( attempt ) branches to see the weird behaviors described previously

### System Info

```shell
System:
    OS: Linux 5.13 KDE neon 5.24
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 2.11 GB / 15.44 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 102.0.5005.61
    Chromium: 102.0.5005.61
    Firefox: 100.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50 
    @sveltejs/kit: next => 1.0.0-next.347 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit with d3

### Additional Information

I'm still rather new to sveltekit - hopefully I didn't overlook anything obvious. Researching it didn't pop up any solutions.

**Comment by tcc-sejohnson** [comment]
@delight I didn't have time to fully look into your issue, but could this be a SSR issue? When the component is created on the server, obviously there's no applicable `clientWidth` or `clientHeight`. You could test this by temporarily disabling SSR using `handle`: https://kit.svelte.dev/docs/hooks#handle. I'll see if I can look into it further later in the day. 😄

**Comment by delight** [comment]
I just added the global.css file of the original project into the master branch - doesn't make a difference ... I can rebase the "solution" branches on top of that ... but a quick try out of one of them resulted in the same behavior

**Comment by delight** [comment]
crated a [stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-n2kxqz?file=README.md) from the project

**Comment by delight** [comment]
created also a [stackblitz](https://stackblitz.com/edit/simple-svelte-chart?file=package.json) to the working svelte (not-sveltekit) project

**Comment by gtm-nayan** [comment]
Pretty sure the difference has to do with where you're mounting your app. In the Svelte-only stackblitz it's getting mounted to the body which is occupying the full height of the viewport (from the global css). In the SvelteKit one it is getting mounted to a div inside which is only as big as its contents need to be i.e. big enough for the selectors.

I added `style="height: 100%;"` to the div in app.html and the chart is rendering properly. Haven't checked on other browsers but pretty sure that's what's happening, @delight I'd be delighted (lol) if you could confirm.

**Comment by delight** [comment]
@gtm-nayan to your delight ;-) I can confirm that the problem indeed was the additional div (I guess the outer div limiting the space of the inner div.wrapper - css some(often)times behavior confuses me. `style="height: 100%;"` wasn't needed as it was set already in the global.css

Thnx so much for point this out ... closing the ticket
