### ISSUE TITLE
Endpoints / pages being called in Chrome that shouldn't be called while loading page

### ISSUE THREAD

**Issue by ReindDooyeweerd** [sveltejs/kit#5136]
### Describe the bug

Not 100% sure if i'm doing something wrong but i expect this to be a bug since i can only reproduce it in Chrome and not on any other browser (didn't try Edge).

**What is going wrong?**
While navigating through my project and loading some pages i see endpoints being called that shouldn't be called. This only happens in Chrome and doesn't happen in Firefox or Safari. Easiest way to explain it is via a screen recording that can be found here, https://share.cleanshot.com/CT23BF8lyeiQ1gIJeu7L

I added a console.log in each endpoint that is called when the endpoint is triggered, while clicking through the site with Chrome you will notice that multiple console.logs are logged to the terminal after a click while clicking through the exact same website with Firefox only 1 console.log is logged to the console.

### Reproduction

The exact same code as used in the video can be found here, https://github.com/ReindDooyeweerd/sveltekit-bug

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 984.67 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Chrome Canary: 104.0.5096.0
    Edge: 102.0.1245.30
    Firefox: 100.0.1
    Safari: 15.5
```

### Severity

annoyance

**Comment by ReindDooyeweerd** [comment]
@dominikg here's the content of the .env file, `GRAPHQL_ENDPOINT=https://cms.sim-racer.nl/graphql`. I opened up that API so it's publicly available.

The prefetch, preload and so on is one i haven't thought about that but after checking i don't find any on those pages, only modulepreloads. Strange thing is, in the network tab of Chrome i don't see those endpoints being called multiple times also. 

I made another video, network tab of Chrome and the Node process in the terminal, https://share.cleanshot.com/U8cahLrIDNmXupmw8qfQ

So i only see those multiple endpoints being called in the Node process and not in the inspector tab of Chrome itself, also checked in Edge, same behaviour (obvious ;) ).

**Comment by dominikg** [comment]
you also have to add `graphql` as a devDependency for it to work.
Once you do and add logging of params.slug to your endpoints you can see that the requests stem from `favicon.ico` requests.

This feels similar to https://github.com/sveltejs/kit/issues/3748

And there is also https://github.com/sveltejs/kit/issues/4968

So you should probably fix your favicon setup (there is no favicon.ico and also no `<link rel="icon">` in head of your app.html) and do not call fetch if the slug is a static asset.

**Comment by ReindDooyeweerd** [comment]
@dominikg i think you are right, tested it and that seems to be the solution so i'll close this one. Thanks for the help!
