### ISSUE TITLE
Shadowing API endpoint takes precendence over page endpoints when using named layout

### ISSUE THREAD

**Issue by lxy-yz** [sveltejs/kit#5139]
### Describe the bug

Given below file structure, it has a named layout `__layout-named.svelte`, api endpoint `foo.js` and a page endpoint `foo@named.svelte`.

```
├── __layout-named.svelte
├── __layout.svelte
├── foo.js
├── foo@named.svelte
└── index.svelte
```

When starting the dev server and visiting http://localhost:3000/foo, json response rather than html was served. While changing `foo@named.svelte` to `foo.svelte` html response will be served as expected.

### Reproduction

https://github.com/lxy-yz/sveltekit-named-layout-issue/tree/main/src/routes. 
Simply `npm install && npm run dev`.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 106.95 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.15.0 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50 
    @sveltejs/kit: next => 1.0.0-next.347 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by PatrickG** [comment]
AFAIK the filename of the endpoint must be `foo@named.js`.

**Comment by lxy-yz** [comment]
@PatrickG thanks, it works. Imho, it makes sense to have the page/api endpoint filename the same, but not intuitive to have layout(ui) tight to endpoint as well. 
Might worth mentioning it as a caveat on https://kit.svelte.dev/docs/layouts#named-layouts. I can help with that. Leave the issue open for more feedback.
