### ISSUE TITLE
TypeScript not being checked on latest SvelteKit

### ISSUE THREAD

**Issue by regnaio** [sveltejs/kit#5140]
### Describe the bug

The latest SvelteKit @sveltejs/kit@1.0.0-next.347 with TypeScript is not doing any TypeScript checks. I'm intentionally typing nonsense variable names, and it's compiling fine. Only when running in the browser do ReferenceErrors come up...

### Reproduction

Create a Skeleton project using ESLint, TypeScript, Prettier with `npm init svelte myfolder`

`myfolder/src/routes/index.svelte`
```svelte
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<script lang="ts">
  x = 43sdag

  sdafsdgarh

  ds
</script>
```

`npm run build` **Compiles fine?!**

### System Info

```shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 15.25 GB / 24.92 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50
    @sveltejs/adapter-static: ^1.0.0-next.34 => 1.0.0-next.34
    @sveltejs/kit: next => 1.0.0-next.347
    svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by jasonlyu123** [comment]
You can use svelte-check and your editor for type-check. It's separated from the build. 

If you want to have a type-check during dev. You can use the `check:watch` command. And If you prefer it to be in the same terminal you can write your vite plugin to fork a process for the svelte-check watch. 

If you want to check before building you can modify the build script to `npm run check && svelte-kit build`
