### ISSUE TITLE
adapter-node should automatically generate package.json for esm

### ISSUE THREAD

**Issue by mwc** [sveltejs/kit#5144]
### Describe the problem

adapter-node should automatically generate `package.json` for ESM, otherwise it will be created in the output directory each time the project is created:

dist /build is set as the output directory.
dist/package.json

``` js
{
  "type": "module"
}
```

Seems to be more complicated.

### Describe the proposed solution

adapter-node will automatically generate `package.json` for ESM.

### Importance

nice to have

**Comment by Conduitry** [comment]
The intention is that you'd use your regular `package.json` (which already has `"type": "module"`) but only install its prod dependencies. I think it would be confusing to have two `package.json` files (it might even mess up production dependency module resolution, I'm not sure), and we don't want to be responsible for copying in all of the prod dependencies along with the lockfile from the parent directory. You should just use your existing `package.json`.
