### ISSUE TITLE
Buffer is not defined in an external module in development

### ISSUE THREAD

**Issue by tyvdh** [sveltejs/kit#5151]
### Describe the bug

I've spent nearly a full day trying to debug this. It feels really simple but I just can't quite figure it out.

I'm using `@sveltejs/adapter-cloudflare-workers` adapter and trying to import the `stellar-base` package and make a call with the `Keypair` method which subsequently calls `Buffer`. I know workers don't bundle `Buffer` so it'll need to be polyfilled. This error is specific to running in development mode with miniflare but I can't imagine there would be much difference running in production.

This error surfaces on the endpoint/server side not the browser side.

What I think is happening is that `stellar-base` is [prebundled](https://kit.svelte.dev/faq#packages) by esbuild with no `Buffer` and thus I can successfully get Buffer polyfilled in the `kit.plugins.inject` but that `Buffer` is then available _after_ `stellar-base` has already been prebundled. What I need is to polyfill `Buffer` _before_ the prebundling. I don't know how to pull that off however and specifically for packages being bundled for the server as esbuild configuration options seem to be aimed primarily at the client side bundle.

There's a lot going on between vite, esbuild, and rollup making it really tricky to sus out what's going on.
I've created an example repo here you can test with: https://github.com/tyvdh/buffer-woes

Just install deps and run the project with `npm run mf`

### Reproduction

https://github.com/tyvdh/buffer-woes

### Logs

```shell
Buffer is real! aGVsbG8gd29ybGQ=
Buffer is fake :(
ReferenceError: Buffer is not defined
    at new Keypair3 (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:17397:28)
    at Function.fromRawEd25519Seed (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:17520:18)
    at Function.random (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:17543:23)
    at get (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:23245:47)
    at load_shadow_data (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:25261:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at load_node (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:25009:28)
    at respond$1 (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:25430:20)
    at resolve (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:25769:105)
    at respond (/Users/tylervanderhoeven/Desktop/buffer-woes/worker-site/worker.mjs:25725:22)
GET / 500 Internal Server Error (58.60ms)
```

### System Info

```shell
  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 85.36 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: 1.0.0-next.44 => 1.0.0-next.44 
    @sveltejs/kit: ^1.0.0-next.347 => 1.0.0-next.347 
    svelte: ^3.48.0 => 3.48.0 
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
I made the following changes to your repro — I removed the `inject` plugin, added this file...

```js
// src/lib/shims.js
import { Buffer } from 'buffer-es6';
globalThis.Buffer = Buffer;
```

...then imported it before `stellar-base` in `src/routes/index.js`...

```diff
+import '$lib/shims.js';
import { Keypair } from 'stellar-base'

export async function get() {
  console.log('Buffer is real!', Buffer.from('hello world').toString('base64'))

  console.log('Buffer is fake :(')
  const keypair = Keypair.random()

  console.log(keypair)

	return {
		body: {
			keypair: {
        publicKey: keypair.publicKey(),
        secret: keypair.secret()
      }
		}
	}
}
```

...and the error message went from

> Buffer is not defined

to

> "size" argument must be a number

which feels like progress? I don't know how to diagnose that latter error, but it seems like `stellar-base` is using the polyfill.

**Comment by tyvdh** [comment]
Thanks for the explorations here. I've since solved this issue with vite configurations.

e.g.
https://github.com/tyvdh/boilerkit/blob/main/svelte.config.js
https://github.com/tyvdh/starlite-sveltekit/blob/main/vite.config.js
