### ISSUE TITLE
Can anyone tell me where is the issue?

### ISSUE THREAD

**Issue by skaaiya** [sveltejs/kit#5156]
### Describe the bug

So I've been building a movie wiki app and got this error on the site: `500
request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
Error: request in handle has been replaced with event. See https://github.com/sveltejs/kit/pull/3384 for details
    at Object.get request [as request] (file:///home/runner/movie-site/.svelte-kit/runtime/server/index.js:3332:11)
    at Object.handle (/home/runner/movie-site/src/hooks.ts:5:39)
    at respond (file:///home/runner/movie-site/.svelte-kit/runtime/server/index.js:3208:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/chunks/plugin.js:361:24`

What do I need to do to fix it, I know there is a pull request link on the error but I can't seem to find the issue.

### Reproduction

https://github.com/skaaiya/Movie-Wiki

### System Info

```shell
System:
OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal
Fossa)
CPU: (8) x64 AMD EPYC 7B12
Memory: 4.82 GB / 62.80 GB
Container: Yes
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 16.7.0- /nix/store/bwxril521b35zl
f4x2g32hl164rzfhck-nodejs-16.7.0/bin/node
npm: 7.20.3 - /nix/store/bwxril521b35zlf
4x2g32h1l64rzfhck-nodejs-16.7.0/bin/npm
npmPackages:
@sveltejs/adapter-auto: next => 1.0.0-ne
xt.3
@sveltejs/kit: ^1.0.0-next.348 => 1.0.0-
next.348
svelte: ^3.44.0 => 3.44.2
```

### Severity

blocking all usage of SvelteKit

**Comment by PatrickG** [comment]
The property `request` in the `handle` function in `src/hooks.js` has been replaced by the `event` property.
You can read more about the handle hook in [the docs](https://kit.svelte.dev/docs/hooks#handle).
Please ask such questions in the [discord chat](https://svelte.dev/chat) in the future..
