### ISSUE TITLE
How can I fix this problem?

### ISSUE THREAD

**Issue by skaaiya** [sveltejs/kit#5158]
### Describe the bug

I'm getting this issue with the code I put in reproduction, can anyone help me fix it?

error: 500

Cannot read property 'id' of undefinedTypeError: Cannot read property 'id' of undefined at load ([id].svelte:3:75) at load_node (file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/ssr.js:1058:30) at respond$1 (file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/ssr.js:1264:21) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async render_page (file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/ssr.js:1454:19) at async resolve (file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/ssr.js:1717:10) at async Object.handle (/home/runner/movie-site/src/hooks.ts:14:24) at async respond (file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/ssr.js:1696:10) at async svelteKitMiddleware (file:///home/runner/movie-site/node_modules/@sveltejs/kit/dist/chunks/index.js:4557:22)

### Reproduction

https://github.com/skaaiya/Movie-Wiki/blob/main/src/routes/movie/%5Bid%5D.svelte

### System Info

```shell
System:
OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal
Fossa)
CPU: (8) x64 AMD EPYC 7B12
Memory: 4.82 GB / 62.80 GB
Container: Yes
Shell: 5.0.17 - /bin/bash
Binaries:
Node: 16.7.0- /nix/store/bwxril521b35zl
f4x2g32hl164rzfhck-nodejs-16.7.0/bin/node
npm: 7.20.3 - /nix/store/bwxril521b35zlf
4x2g32h1l64rzfhck-nodejs-16.7.0/bin/npm
npmPackages:
@sveltejs/adapter-auto: next => 1.0.0-ne
xt.3
@sveltejs/kit: ^1.0.0-next.348 => 1.0.0-
next.348
svelte: ^3.44.0 => 3.44.2
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
As someone else already told you in your previous issue (https://github.com/sveltejs/kit/issues/5156#issuecomment-1146549948)

Use other channels such as the [discord chat](https://discord.gg/svelte), [github discussions](https://github.com/sveltejs/kit/discussions), [the Svelte subreddit](https://reddit.com/r/sveltejs) or [StackOverflow](https://stackoverflow.com) when asking for help. **The issue tracker is for bug reports and feature requests, not for support questions.**
