### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by geniuskrul** [sveltejs/kit#5159]
### Describe the bug

When the text transform in the import path is wrong, the website slows down and it doesn't show any errors.

### Reproduction

1. Install SvelteKit
2. In the `lib` folder create a folder called (no typo) `header` and inside it, create a file called `Header.svelte`
3. In your layout file, import it exactly like this `import Header from '$lib/Header/Header.svelte'`
4. You will see the website slows down 100x but there is no error!

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 6.68 GB / 15.84 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.50 => 1.0.0-next.50
    @sveltejs/kit: 1.0.0-next.348 => 1.0.0-next.348
    svelte: ^3.48.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by tcc-sejohnson** [comment]
In the bug template you filled out, above the reproduction box, there's this text:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. [...] Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

It is _much_ more likely someone will pick this up quickly and look into it if you provide a real reproduction.

**Comment by geniuskrul** [comment]
I was too tired at the time. Later I removed the project and now I can't replicate the problem. Maybe something else in that project caused the problem.
