### ISSUE TITLE
Add warning for use of session store outside of a component

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/kit#5176]
### Describe the problem

You are unable to use the `session` store outside of a component and currently you just get an error message along the lines of `Function called outside component initialisation`

### Describe the proposed solution

Talked in the discord about potentially adding something to svelte core to allow you to check whether you are in component initialisation or not and then libs can use that to throw more helpful error messages

### Importance

nice to have

**Comment by rmunn** [comment]
This is probably moot now that https://github.com/sveltejs/kit/pull/5946 has removed the special `$session` store. (It can now be implemented quite easily by anyone who needs it, using `event.locals` and a `+layout.server.ts` file). So I'm closing the issue; if the decision to remove the session store gets reversed, we can reopen the issue if/when that happens.
