### ISSUE TITLE
Netlify adapter builds cjs by default

### ISSUE THREAD

**Issue by ghostdevv** [sveltejs/kit#5177]
### Describe the bug

Currently the netlify adapter builds cjs by default, this is configurable with `functions.node_bundler` in the netlify.toml. The code for that is below:

https://github.com/sveltejs/kit/blob/master/packages/adapter-netlify/index.js#L72
```js
// for esbuild, use ESM
// for zip-it-and-ship-it, use CJS until https://github.com/netlify/zip-it-and-ship-it/issues/750
const esm = netlify_config?.functions?.node_bundler === 'esbuild';
```

What I am trying to understand is why, and if it's still required to be this way. It's causing issues for esm only packages (for example any package made with svelte-kit package) because the cjs bundle that uses `require` is of course unable to import esm.

The `esm` variable there is used in the netlify adapter, if it's false then esbuild is used to transpile the generated esm by sveltekit into cjs. I am unsure why it needs to be set to esbuild in the `netlify.toml` because it's a sveltekit adapter doing the transpiling.

What I don't fully understand is where `zip-it-and-ship-it` comes in or why we are transpiling at all. I also don't understand what parts of netlify do and don't support esm. Hopefully the netlify guys or anyone here will know! I asked @brittneypostma and she is going to get some help from some of the netlify team if possible

### Reproduction

I created this repo to show what I mean. It uses a package I made that is esm only. If you remove the netlify.toml OR set the `node_bundler` to `zisi` then it will generate CJS and when you visit the site on netlify it breaks

https://github.com/ghostdevv/netlify-sveltekit-esm-only-broke

### System Info

```shell
@sveltejs/adapter-netlify: next => 1.0.0-next.64 
@sveltejs/kit: next => 1.0.0-next.348
```
### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
We're blocked by https://github.com/netlify/zip-it-and-ship-it/issues/749

**Comment by brittneypostma** [comment]
This may be fixed now @ghostdevv with pr https://github.com/sveltejs/kit/pull/6666

Other possibly relevant issue with zip-it-and-ship-it: https://github.com/netlify/zip-it-and-ship-it/issues/750

**Comment by benmccann** [comment]
yeah, this should be fixed. let me know if that's wrong and we can reopen

**Comment by ghostdevv** [comment]
awesome!!
