### ISSUE TITLE
People are confused by `adapter-static` 

### ISSUE THREAD

**Issue by tcc-sejohnson** [sveltejs/kit#5185]
### Describe the problem

I've lost count of the number of times people have asked "why is my `adapter-static` build output missing `index.html`" (and other similar questions) in Discord. It's always fixed by either adding `config.kit.adapter.fallback = 'foo.html'` or `config.kit.prerender.default = true`. To be clear, this _is_ in the documentation, and not having one of these settings _does_ produce a yellow (?) warning during build, but I've found that people tend to lose the yellow warning in the output from `build`.

### Describe the proposed solution

When trying to run `svelte-kit dev` or `svelte-kit build`, throw a full-on, red, crash-the-process error stating:

```
It looks like you're using adapter-static, but `config.kit.prerender.default` is `false` and `config.kit.adapter.fallback` is missing. Either set `config.kit.prerender.default` to true (to statically generate your entire site) or set `config.kit.adapter.fallback` to your desired fallback page (to operate in SPA mode). For more information, check out <link to FAQ in adapter-static docs about this issue>
```

Maybe I'm missing some context here, but I don't think there's any case where `adapter-static` should be run without one of those options set, and the fact that it "works" in dev confuses a lot of people.

### Importance

would make my life easier

### Additional Information

Happy to work on this one if it's a feature we'd actually like to add.

**Comment by Mlocik97** [comment]
There are use cases when you want to use adapter-static without prerendering or fallback, anyway it's good to warn about this... not throw error.

**Comment by Mlocik97** [comment]
There are use cases when you want to use adapter-static without prerendering or fallback, anyway it's good to warn about this... not throw error.

**Comment by furudean** [comment]
> There are use cases when you want to use adapter-static without prerendering or fallback
 
When?

**Comment by bothness** [comment]
I can second that this has been causing confusion for me. In earlier versions of Adapter Static, it was clear that you can render as a SPA by including **config.kit.adapter.fallback**, or pre-render all routes by including **config.kit.prerender.enabled**, but now I get messages suggesting that I need to use "hooks" to render as a SPA, but there isn't any documentation on how to do this.

**Comment by Rich-Harris** [comment]
Judging by the emoji reactions, this is something we should do. I also can't think of a situation where you'd want to use `adapter-static` without either prerendering by default or having a fallback.

**Comment by tcc-sejohnson** [comment]
@Rich-Harris Consider it done
