### ISSUE TITLE
Nested error components

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#519]
We have nested `$layout` components, but only a top-level `$error`. It might be useful to support nested error components as well:

![image](https://user-images.githubusercontent.com/1162160/111069414-5c6b3e80-84a3-11eb-81a4-e4218bca13e2.png)

In this example, if `routes/settings/notifications/$error.svelte` errored in load, we'd _then_ try rendering `routes/settings/$error.svelte`, etc.

**Comment by arxpoetica** [comment]
Crazy thought -- should error pages belong in layout pages?
