### ISSUE TITLE
Add "beforeLeave" support in navigation hooks

### ISSUE THREAD

**Issue by MathiasWP** [sveltejs/kit#5190]
## This is a made up example, but i feel it illustrates a somewhat valid use-case

Let's say you have a component that shows a video based on the route you're on; `/video/:id`.

This component does not remount when you go to a new video, because that's often unnecessary when working with Svelte.

When the user goes from `/video/1` to `/video/2` you can easily fetch a new video using the `afterNavigate` hook. However, before the user left, you wanted to save the timestamp of the video the user was just watching.  You could use `beforeNavigate`, but it quickly becomes awkward.

How could we easily run some code in a "beforeLeave" scenario?

### Describe the proposed solution

We could return a function from the `beforeNavigate` and `afterNavigate` hook which would be called before the user left the page. You can compare it to the way `onMount` works:

```svelte
<script>
	import { afterNavigate } from '$app/navigation';
	
	afterNavigate(({ to }) => {
		console.log(`Hi! welcome to: ${to.href}`!)

		return () => {
			console.log(`Bye! We'll wait for you here at ${to.href}!`)
		}
	})
</script>
```

### Alternatives considered

You can use the current implementation of `beforeNavigate` and `afterNavigate` to get this behaviour, but it quickly requires awkward juggling of values.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
I can imagine use cases for this, but I'm going to close it because it's very easy to implement in userland:

```js
import { afterNavigate, beforeNavigate } from '$app/navigation';

export function onNavigate(fn) {
  let pending;

  beforeNavigate((navigation) => {
    pending?.(navigation);
    pending = null;
  });

  afterNavigate((navigation) => {
    pending = fn(navigation);
  });
}
```

```svelte
<script>
  import { onNavigate } from '$lib/lifecycle';

  onNavigate(({ from, to }) => {
    console.log(`1. navigated from ${from.pathname} to ${to.pathname}`);

    return ({ from, to }) => {
      console.log(`2. navigated from ${from.pathname} to ${to.pathname}`);
    };
  });
</script>
```

In general, we want to keep the built-in APIs as lean and extensible (and maintainable!) as possible. We could conceivably add this in future as a non-breaking change, but we might equally decide to do the opposite (where you return a callback that runs after the current navigation completes)...

```js
import { afterNavigate, beforeNavigate } from '$app/navigation';

export function onNavigate(fn) {
  let pending;

  beforeNavigate((navigation) => {
    pending = fn(navigation);
  });

  afterNavigate((navigation) => {
    pending?.(navigation);
    pending = null;
  });
}
```

...and leaving the possibility open saves us from potentially making a breaking change.
