### ISSUE TITLE
create-svelte CI deploy failed again

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#520]
Part 2 electric boogaloo - cc @Rich-Harris

I think there's probably an actual problem with the credentials set for it.

**Comment by Conduitry** [comment]
Is `svelte-admin` the user whose token CI has, and does that not (any longer?) have permission to publish `create-svelte`, which is outside the `@sveltejs` org?

**Comment by Conduitry** [comment]
@Rich-Harris On https://www.npmjs.com/~svelte-admin I don't see `create-svelte` listed as one of the packages. Since your personal `rich_harris` npm user is the only one listed as a maintainer on that project (I think), you'll need to add `svelte-admin`.

**Comment by Rich-Harris** [comment]
ah, interesting. i just ran `npm owner add svelte-admin` inside `create-svelte`, hopefully that will fix it for next time. released manually with `pnpm release` in the meantime

**Comment by Conduitry** [comment]
`npm show create-svelte@next` now lists both you and `svelte-admin` as maintainers, so I _think_ we're good? Let's see what happens next release.

**Comment by Conduitry** [comment]
The last automated publish appears to have worked. I think we're good for real now.
