### ISSUE TITLE
[Feature Request] Add a default .node-version file to starters

### ISSUE THREAD

**Issue by isaac-mcfadyen** [sveltejs/kit#5205]
### Describe the problem

On services such as Cloudflare Pages, they use `nvm` to install Node. `nvm` chooses which version of Node.JS to install via looking at either the `NODE_VERSION` environment variable or a file in the root directory named `.node-version`.

Because neither of these are included in the SvelteKit starter, we commonly have to tell people to add these when their build mysteriously breaks.

### Describe the proposed solution

The first solution (adding an environment variable of NODE_VERSION) is very platform-specific to set and would likely not be possible.

However, we could consider adding a file `.node-version` to the starters by default (perhaps with a sane default version of Node, for example the LTS version 16). This would ensure that any CI tools that respect this, such as Cloudflare Pages and other CI that uses `nvm`, would have SvelteKit "just work".

### Alternatives considered

An alternative would be to make this clearer in the documentation. However, it's already fairly prominent and not everyone reads over the docs when first deploying.

### Importance

nice to have

**Comment by shadowspawn** [comment]
To clarify, Cloudflare Pages supports a `.node-version` file. nvm itself does not.

For interest, I have been collecting `.node-version` file usage: https://github.com/shadowspawn/node-version-usage

**Comment by isaac-mcfadyen** [comment]
The Pages team is working on a new build image for Cloudflare Pages builds (which should have a sane LTS version of Node by default). No idea when it'll be ready though.

**Comment by indatawetrust** [comment]
i don't know if it's related to this issue, but why do you make 16.9 and above node versions mandatory for installation? i guess the [most widely used version is 14](https://nodejs.org/metrics/). i think it would be good to support slightly older versions for more people to use. i would like to know if there is an extra special reason. thanks

**Comment by isaac-mcfadyen** [comment]
> i don't know if it's related to this issue, but why do you make 16.9 and above node versions mandatory for installation? i guess the [most widely used version is 14](https://nodejs.org/metrics/). i think it would be good to support slightly older versions for more people to use. i would like to know if there is an extra special reason. thanks

I'm guessing:
1. According to the official NodeJS lifetime schedule, [Node 14 is now End-Of-Life](https://nodejs.org/en/about/releases/) and is maintainance-only, no feature additions.
2. SvelteKit uses Node features only available in Node 16.

Also just an FYI, those metrics you cited are now out-of-date, according to the warning across the top of the page.

**Comment by benmccann** [comment]
I'm going to close this. It really seems like Cloudflare's problem that they're chronically terribly outdated

**Comment by isaac-mcfadyen** [comment]
> It really seems like Cloudflare's problem that they're chronically terribly outdated

Apologies, I forgot about this Issue!

They've since updated the build container to use a more modern Node version, so this can definitely be closed.
