### ISSUE TITLE
adapter-vercel shouldn't wipe `.vercel/output`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#5207]
### Describe the bug

This line is problematic... https://github.com/sveltejs/kit/blob/c9567444ea59172756671eb96474b0283c298f58/packages/adapter-vercel/index.js#L213 ...because it wipes files that `vc build` places in that directory. `vc build` _also_ empties the directory, which is enough. 

### Reproduction

Going to break my own rule and skip a repro for this one, since it's best demonstrated with a canary version of the Vercel CLI

### System Info

```shell
latest everything
```

### Severity

annoyance

**Comment by mrkldshv** [comment]
Hey! I'm thinking to take this issue. As mentioned in the issue, `vercel build` removes potentially existing output directory, so I guess we can just remove this line from the adapter code, because it does the same.
