### ISSUE TITLE
Mobile iOS Safari Errors - 500: Importing a module script failed.

### ISSUE THREAD

**Issue by kristjanmar** [sveltejs/kit#5208]
### Describe the bug

I recently migrated my website from NextJS to SvelteKit.

Everything has worked smoothly except for mysterious errors that seem to happen mostly on mobile iOS Safari, but also on desktop Firefox.

On Safari, the error is: "500: Importing a module script failed."
On Firefox, the error is: "500: error loading dynamically imported module"

![Screenshot 2022-06-15 at 16 26 18](https://user-images.githubusercontent.com/22234692/173794139-65cb1ca4-4a4c-4d3b-b307-5d9c3ad35f69.png)

As you can see, this is so common that a total of 0.6% of visitors are getting a critical error that is severe enough to replace the entire page's content with an error message.

On Safari, the error happens mostly on the home page. On Firefox there is no noticeable pattern. It appears to be a client-side error because my Vercel server logs are not picking up the errors.

I track the error by sending a custom event to Plausible Analytics in the __error.svelte file.

The error appears to be coming from up-to-date browser versions. As in, Safari 15 and Firefox 101.

Here's the spike in errors after switching to SvelteKit:

![Screenshot 2022-06-15 at 16 34 13](https://user-images.githubusercontent.com/22234692/173795569-62fb19db-4972-4120-ac85-2c9c5f495cc5.png)

Unfortunately, I am totally unable to replicate the error myself. It does not show up on my iPhone or the versions I tested with Browserstack. And there doesn't appear to be any stack trace provided to help me debug the issue.

This is my site: https://stockanalysis.com/
This is the repo: https://github.com/stockanalysisdev/stock-analysis-sveltekit

Has anyone dealt with this issue before? Or have an idea about the best way to debug the issue without being able to reproduce it myself?

Also, if anyone could try visiting my home page on mobile iOS Safari and see whether they get an error and a stack trace then that would be incredibly helpful.

### Reproduction

Unable to reproduce testing on my own iPhone or via Browserstack.

### System Info

```shell
All packages have been updated to their latest versions.

System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Memory: 333.49 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.9.0 - /usr/local/bin/node
    npm: 8.8.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.50 => 1.0.0-next.50 
    @sveltejs/kit: 1.0.0-next.350 => 1.0.0-next.350 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by tcc-sejohnson** [comment]
@kristjanmar

I see you're running `adapter-auto` -- out of curiosity, what platform are you deploying your app to?

**Comment by Conduitry** [comment]
Vercel, it looks like, behind Cloudflare.

That said, I'm not sure that there's anything we can or should do here about this. In my experience, client-side error reporting services report a _ton_ of truly bonkers errors, and these don't seem to correlate at all with getting complaints from real people that the app is not working properly. If this isn't something that can be consistently reproduced, and isn't something that can be traced to SvelteKit rather than "iunno browsers freak out sometimes, especially Safari", then I'd be in favor of closing this.

**Comment by kristjanmar** [comment]
Yes, it's hosted on Vercel, behind Cloudflare.

The errors are sent from the __error.svelte file when a user gets an error page. I was using the exact same approach for error reporting in NextJS and critical errors have gone up 4X since then.

If these are real errors then 0.5-0.6% of visitors getting a critical error is pretty severe IMO, so I definitely want to get to the bottom of it.

Is there a proper error reporting service that works well with SvelteKit that I could try?

**Comment by kristjanmar** [comment]
I tried visiting the site in mobile iOS safari, changing something and redeploying and then clicking around afterwards and I didn't get any errors.

I also don't see any increase in the error reports after a fresh deploy, they come throughout the day.

**Comment by kristjanmar** [comment]
I guess it's a long shot that this could be related, but I noticed that __error.svelte is loaded on every single pageview by looking at the network tab in Chrome dev tools. It is initiated by the preload-helper.js file.

Is __error.svelte supposed to be loading on every single visit?

![CleanShot 2022-06-24 at 21 23 20 2](https://user-images.githubusercontent.com/22234692/175556181-1af433e5-0885-440f-a38f-5aefb78088a0.png)

**Comment by MathiasWP** [comment]
Could the errors be caused by older browsers that don't support `type="module"`?

I would recommend this library for increased browser support, https://github.com/guybedford/es-module-shims/, and see if it helps.

**Comment by enyo** [comment]
Maybe this is unrelated, but I had the same issue with Svelte Kit apps, specifically on iOS, where it was caused by the "Crystal" content/ad blocker extension.

**Comment by kristjanmar** [comment]
> Could the errors be caused by older browsers that don't support `type="module"`? You say that the errors are supposedly thrown by up to date browsers, but there may be a chance that the report-tool is a little funky. Not saying that it is, I'm just thinking out loud.
> 
> I would recommend https://github.com/guybedford/es-module-shims/ for increased browser support. Maybe it helps.

Thank you, I will look into this.

> Maybe this is unrelated, but I had the same issue with Svelte Kit apps, specifically on iOS, where it was caused by the "Crystal" content/ad blocker extension.

Thanks for the suggestion. Unfortunately I tried installing this on my iPhone and tested Safari and it didn't trigger any errrors.

**Comment by kristjanmar** [comment]
I'm going to close this since the error rate has gone down significantly. It's down to about 0.3% of visits, which is significant but not much higher than it was with NextJS.

I haven't done anything specific that I belive can explain the drop in errors. They increased with Vite 3.0.0 but have gone down as of Vite 3.0.2. Not sure if that's even related to the errors.

**Comment by petermakeswebsites** [comment]
I don't mean to beat a dead horse here, but my application is a PWA Svelte (but not SvelteKit) and getting these errors reported. I would imagine this may be still present in SvelteKit, but the reason I'm posting here is because a lot of my users are experiencing this error and I have no strings to pull on except in this thread. Does anyone understand why this is happening? Has anybody found a solution?

**Comment by kyle-villeneuve** [comment]
> I don't mean to beat a dead horse here, but my application is a PWA Svelte (but not SvelteKit) and getting these errors reported. I would imagine this may be still present in SvelteKit, but the reason I'm posting here is because a lot of my users are experiencing this error and I have no strings to pull on except in this thread. Does anyone understand why this is happening? Has anybody found a solution?

1. you have code splitting in your app.
2. the user visits your website and loads only part of your code split app.
3. you deploy a new version
4. the user does not reload the page, so it is running an old script with references to code split bundles that no longer exist on your server.
5. the browser makes a request for code split modules that no longer exist.

**Comment by newsve** [comment]
FWIW, my site polls version.json
1. I got _cannot load version.json due to access control checks_
2. next to a handful of _[Error] TypeError: Importing a module script failed._

Somehow 1 disappeared at some point and 2 as well after 2 deploys (to CF Pages). And it is only on Safari, both IOS and macOS. I got this two times the last days.

Super weird, does it make sense to report this to CF and if yes, how so they know where to look at?

**Comment by MuslemRahimi** [comment]
I still have this issue on my side for older safari browser where suddenly they get a 5xx errors

**Comment by thlintw** [comment]
Ran into this, and it seemed to have something to do with unused imports. I removed an unused firebase analytics import which solved the problem.

**Comment by MuslemRahimi** [comment]
> Ran into this, and it seemed to have something to do with unused imports. I removed an unused firebase analytics import which solved the problem.

In my case I don't use firebase analytics but still have this issue.

**Comment by norman784** [comment]
It happened to me now in localhost, and it seems to be related to ad-blockers. After disabling the ad-blocker, the error went await.

**Comment by newsve** [comment]
I got the error without using any ad blocker (since I always use a ded. clean Chrome profile without any plugins for dev).

**Comment by JadedBlueEyes** [comment]
I'm seeing sentry reporting this issue persistently for safari users:
![image](https://github.com/user-attachments/assets/66a886df-5e37-4b70-816b-5f574b4e2c13)
(LINE being a mobile safari based browser) 
There are no additional stack trace details for some reason.

**Comment by JorensM** [comment]
I'm also getting similar reports on Safari browsers.

**Comment by flowluap** [comment]
We have the same problem on osx and ios with safari.

![Bildschirmfoto 2025-01-03 um 20 02 37](https://github.com/user-attachments/assets/d38aec93-c464-4762-bfb1-a29c4a71e68a)
![Bildschirmfoto 2025-01-03 um 20 02 57](https://github.com/user-attachments/assets/a68fdd2f-999a-4d81-8b9e-5e2919d4b86e)

**Comment by Aarbel** [comment]
Same error here, who found a fix ?

**Comment by Aarbel** [comment]
This fixed the error: https://github.com/facebook/create-react-app/issues/11779#issuecomment-1954240251

**Comment by davidwessman** [comment]
We are seeing similar issue with Vue, Vite and Inertia. Started after we started using Code Splitting

**Comment by ehrencrona** [comment]
I suspect a lot of these errors are from bots. Presumably they stay on the page for an extremely short time and then leave, aborting the fetches that are in progress. I got rid of a lot of these errors by not letting suspected bots report anything.
