### ISSUE TITLE
%svelte.assets% in src/app.html should be replaced with %sveltekit.assets%

### ISSUE THREAD

**Issue by tvardy** [sveltejs/kit#5223]
### Describe the bug

After recently updating from `-next.326` to `-next.350` I'm being shown a message:

`%svelte.assets% in src/app.html should be replaced with %sveltekit.assets%`

1. I have no `%svelte.assets%` in my `app.html` file... only `%svelte.head%` and `#svelte.body%`
2. I checked in the new [template](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/app.html), that those values should be changed into `%sveltekit.head%` and `%sveltekit.body%` respectively... so I did it... but no change :(

### Reproduction

Hard to reproduce the package upgrade process on old template... :(

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 93.78 MB / 16.00 GB
    Shell: 3.4.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/8482_1655557523896/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - ~/Library/Caches/fnm_multishells/8482_1655557523896/bin/npm
  Browsers:
    Brave Browser: 99.1.36.109
    Chrome: 102.0.5005.115
    Firefox: 101.0.1
    Firefox Developer Edition: 102.0
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.34 => 1.0.0-next.34 
    @sveltejs/kit: 1.0.0-next.350 => 1.0.0-next.350 
    svelte: 3.48.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by bluwy** [comment]
We're correctly checking for `%svelte.assets%` and reporting it [here](https://github.com/sveltejs/kit/blob/70f8a4400270ff53620b5a4ca870f30496be13cd/packages/kit/src/core/config/index.js#L21-L26). Perhaps a global find might uncover it? It's used within links so it may not be easy to spot. Closing as there's no repro for us to verify.

**Comment by tvardy** [comment]
yep! found it... thanks for your time... ;)
