### ISSUE TITLE
Can I haz an helpful error message?

### ISSUE THREAD

**Issue by MichaelBailly** [sveltejs/kit#5227]
### Describe the bug

Hello SvelteKit developers! I got a lot of respect for this software, so please do not take this bug report badly. I recently reinstalled my computer and development environment, and the current SvelteKit project I'm working on now brings an error when going to a specific route.

There is no doubt that the error is on my hand. However, given the current debug messages, I'm unable to find it.

I'd like, if you accept, you to help me find the bug, and doing so, we may be able to enrich the error messages together, then I can provide a pull request... What do you think? Here is the current error stack that I'm having:

### Reproduction

As stated in the description, I have no way to provide a simple reproduction code

![sveltekit-error](https://user-images.githubusercontent.com/1465817/174495184-a0ef8dbe-451b-46f0-8945-86324274c4e7.png)

### Logs

```shell
index.svelte? [sm]:21 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parentNode')
    at index.svelte? [sm]:21:22
    at run (index.mjs:18:12)
    at Array.map (<anonymous>)
    at index.mjs:1816:45
    at flush (index.mjs:1075:17)
(anonymous) @ index.svelte? [sm]:21
run @ index.mjs:18
(anonymous) @ index.mjs:1816
flush @ index.mjs:1075
Promise.then (async)
schedule_update @ index.mjs:1018
make_dirty @ index.mjs:1844
(anonymous) @ index.mjs:1882
$$self.$$set @ root.svelte? [sm]:34
(anonymous) @ proxy.js:83
$set @ index.mjs:1977
dest.<computed> @ proxy.js:46
update @ start.js:699
await in update (async)
navigate @ start.js:1372
(anonymous) @ start.js:1598
```

### System Info

```shell
System:
    OS: Linux 5.18 Fedora Linux 36 (KDE Plasma)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.31 GB / 15.28 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.12.2 - ~/dev/git/tradlogger/node_modules/.bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Firefox: 101.0.1
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.66 => 1.0.0-next.78 
    @sveltejs/kit: ^1.0.0-next.240 => 1.0.0-next.350 
    svelte: ^3.44.3 => 3.48.0 

Using TypeScript (4.7.4)
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
If you have no way to give a reproducible, then there's no way we can find out what's the source of the error

**Comment by Conduitry** [comment]
There's nothing actionable for us to do here. Please don't use issues for (extremely) thinly veiled support requests.

**Comment by MichaelBailly** [comment]
OK I'm sorry if you took it like a support request, please look a little bit my profile and you'll see I've done Open Source development for more than 9 years... So I tell you I have no way to find the problem because the error message is helpless, you tell me there is nothing actionable because I cannot give a reproduction scenario, which I can not because the error message is helpless... 

Well, ok pals, I get it, but sincerely, developers would benefit from useful error messages from SvelteKit.

**Comment by acoyfellow** [comment]
@MichaelBailly I'm assuming everyone here agrees with that concept.. but, without a way to reproduce this error, how can any contributor fix it?
