### ISSUE TITLE
`<meta property="og:image" content="..."`  is not being picked up by crawl

### ISSUE THREAD

**Issue by gbkwiatt** [sveltejs/kit#5228]
### Describe the problem

Came up to issue where  `<meta property="og:image" content="https://link-to-image.jpg"/>` 
Is not being picked up by crawl and image is not added to `assets`. 
It is because Open Graph specification requires full scheme url, but full scheme url is no picked up by crawl due to url looking "external".
It's also not being picked up, because it's in meta tags, so even if I try no scheme url, it's still not picked up.

That forces me to hack it and create hidden image elements that can be crawled. 

### Describe the proposed solution

Not entirely sure, what could be the best solution. 
Either always crawl og:image/twitter:image, or have property in config to force crawl those tags. 

### Importance

would make my life easier

**Comment by rishi-raj-jain** [comment]
Do you have it deployed somewhere?

**Comment by gbkwiatt** [comment]
> Do you have it deployed somewhere?

Not to live preview I am afraid. However in the production it looks alright, URL looks valid but when opening it - it's 404 due to image not existing in assets.

**Comment by rishi-raj-jain** [comment]
Does that mean, the error is no anymore?

**Comment by gbkwiatt** [comment]
There is no error. It's just that it's not being picked up by crawler and image does not exists in `assets` directory. Therefore it causes 404 error when trying to open image from link in `<meta property="og:image" content="https://link-to-image.jpg"/>`

**Comment by s3812497** [comment]
closed by https://github.com/sveltejs/kit/pull/9900

**Comment by JempUnkn** [comment]
Why doesn't it work with */assets/image/logo.png*? I'm trying to use this and it doesn't want to work.

**Comment by eltigerchino** [comment]
> Why doesn't it work with _/assets/image/logo.png_? I'm trying to use this and it doesn't want to work.

Please open a new issue with a minimal reproduction in the form of a repository.
