### ISSUE TITLE
Pre-rendering all pages at once with Adapter Static can exceed node memory limit

### ISSUE THREAD

**Issue by bothness** [sveltejs/kit#5233]
### Describe the bug

Note: I'm describing this as a "bug" rather than a "feature request" as it seems to not have been an issue in earlier versions of Adapter Static.

When pre-rendering my Svelte Kit app with ~300 fairly data-heavy pages, I am hitting the default 2GB memory limit in Node.

The reason for hitting this limit seems to be that the pre-rendered pages are getting stored in memory until ALL of them have been generated, and then are getting written to disk. Previous versions of Adapter Static seemed to write the pages to disk one-by-one, thus not causing this issue. I tend to believe that this previous "streaming" approach is more robust as it doesn't limit the size of sites that can be statically generated with Svelte Kit.

### Reproduction

Build a Svelte Kit app with a lot of pages.

### Logs

```shell
<--- Last few GCs --->

[18376:0000021C00E58240]   114602 ms: Scavenge (reduce) 2042.8 (2083.6) -> 2042.3 (2083.6) MB, 18.1 / 0.0 ms  (average mu = 0.128, current mu = 0.097) allocation failure
[18376:0000021C00E58240]   114620 ms: Scavenge (reduce) 2043.0 (2083.6) -> 2042.6 (2084.1) MB, 7.6 / 0.0 ms  (average mu = 0.128, current mu = 0.097) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF68DA2013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF68D9AF396 DSA_meth_get_flags+65526
 3: 00007FF68D9B024D node::OnFatalError+301
 4: 00007FF68E2E19EE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF68E2CBECD v8::SharedArrayBuffer::Externalize+781
 7: 00007FF68E17C2C9 v8::internal::Heap::PublishPendingAllocations+1129
 8: 00007FF68E17929A v8::internal::Heap::PageFlagsAreConsistent+2842
 9: 00007FF68E16BF19 v8::internal::Heap::CollectGarbage+2137
10: 00007FF68E16A0D0 v8::internal::Heap::AllocateExternalBackingStore+2000
11: 00007FF68E18EA06 v8::internal::Factory::NewFillerObject+214
12: 00007FF68DEC1CD5 v8::internal::DateCache::Weekday+1797
13: 00007FF68E36F3E1 v8::internal::SetupIsolateDelegate::SetupHeap+494417
14: 00007FF68E3015A1 v8::internal::SetupIsolateDelegate::SetupHeap+44305
15: 0000021C0359EF49
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 2.02 GB / 7.72 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.34
    @sveltejs/kit: next => 1.0.0-next.350
    svelte: ^3.34.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

I can work around this for my present project by setting a higher memory limit in Node, but can imagine that it will fail entirely for very large projects (eg. 1,000s, 10,000s or 100,000s of pages).

**Comment by Rich-Harris** [comment]
I'm afraid we're going to need a repro for this. Pages aren't stored in memory, they're written to disk as they're ready, and the default `config.kit.prerender.concurrency` (which dictates how many pages can be prerendered at once) is `1`. Perhaps there's something else going on here?

**Comment by tcc-sejohnson** [comment]
I think two weeks is long enough to wait for a repro. OP, if you are still experiencing a bug, please create a repro and open a new issue. Thanks!

**Comment by SKalt** [comment]
I've got unintentional repro:
```sh
git clone https://github.com/i-s-compat-table/i.s.compat.table.git repro &&
  git checkout 12fdd14 &&
  cd repro/website &&
  pnpm i &&
  pnpm build
```

When I run the failing build, I see memory usage creep up while ~11 of processes like
```
node ./node_modules/@sveltejs/kit/prerender.js \
  ./svelte-kit/output/client/ \
  ./.svelte-kit/generated/prerender.json \
  ./.svelte-kit/output/server/manifest.js \
  true
```
run. I double-checked that setting `config.kit.prerender.concurrency` did not affect the memory consumption.

<details open><summary>system info</summary>

```

  System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 29.00 GB / 31.29 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.n/bin/node
    Yarn: 1.22.11 - ~/.n/bin/yarn
    npm: 8.11.0 - ~/.n/bin/npm
  Browsers:
    Firefox: 103.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-static: 1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: next => 1.0.0-next.405 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.0 

```

</details>
