### ISSUE TITLE
adapter-node redirect to http://sveltekit-prerender/ for simple routing

### ISSUE THREAD

**Issue by Diamssword** [sveltejs/kit#5234]
### Describe the bug

Hello,
I compiled a project with the adapter-node but I have an issue:
When I access a simple route like http://my.domain/main , I get redirected to  http://sveltekit-prerender/main
But it does work fine when going to a advanced route like "src/user/[id].svelte" , everything work fine.
Same for client-side navigation: using my website menu to go to http://my.domain/main works fine.

Any idea what could be causing this?

### Reproduction

I created a basic project with similar configuration:
https://github.com/Diamssword/svelte-adapter-bug

the 'dev' version work well, but once built and the "build/index.js" launched with basic node, you will be redirected to  "http://sveltekit-prerender/parcours" when going to "http://localhost:3000/parcours".
But everything work ok when going to  "http://localhost:3000/formation/anyStringAsParam".

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics
    Memory: 19.34 GB / 31.95 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50
    @sveltejs/adapter-node: ^1.0.0-next.78 => 1.0.0-next.78
    @sveltejs/kit: next => 1.0.0-next.350
    svelte: ^3.46.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by kbsali** [comment]
hi @Diamssword ,

I'm facing the exact same issue trying to "protect" some private routes in my `hooks.ts` file.
Could you share exactly how you solve this in your `__layout` file? :pray:

**Comment by kbsali** [comment]
To me this is a real bug which should be addressed and the issue should therefore be re-opened.

**Comment by Diamssword** [comment]
> hi @Diamssword ,
> 
> I'm facing the exact same issue trying to "protect" some private routes in my `hooks.ts` file. Could you share exactly how you solve this in your `__layout` file? 🙏

for now, my systeme is not perfect but functional enough for me, what I did was passing the routeId in my session (via hook.js)

And made the verification on my _layout, redirecting to /login if needed

       if (!session.isAuth) {
            if (session.routeId != null) {
                if (!publicPages.includes(session.routeId)) {
                    return { redirect: "/login", status: 302 }; //redirection on login if not auth
                }
            }
        }

**Comment by xmlking** [comment]
I faced the same problem. I also have a guard lin my hooks 
https://github.com/xmlking/svelte-starter-kit/blob/main/src/lib/server/middleware/guard.ts#L20

my node build `ADAPTER=node AUTH_TRUST_HOST=http://sveltekit-prerender vite build` prerendered `dashboard.html` which should not be  prerendered

<img width="493" alt="image" src="https://user-images.githubusercontent.com/627951/209491507-329aae4e-a50a-45c6-bcb2-766a8e4638ee.png">

the content of `dashboard.html`  is 
```html 
<meta http-equiv="refresh" content="0;url=http://sveltekit-prerender/auth/signin?callbackUrl=/dashboard">
```

My Repo: https://github.com/xmlking/svelte-starter-kit
