### ISSUE TITLE
Assets are not included for the server (adapter-node)

### ISSUE THREAD

**Issue by maximedupre** [sveltejs/kit#5240]
### Describe the bug

# Bug

If you import an image on the server (e.g. in an endpoint), the file path will point to a non-existent file.

``` js
import Image from '$lib/svelte-welcome.webp';

console.log(Image); // /_app/immutable/assets/svelte-welcome-c18bcf5a.webp
```

When looking in `/build/client/_app/immutable/assets` folder, the file is not included.

# Use case

1. I am using `node-canvas` on the server and in this case, I need to place an image on the canvas, so I need the image path
2. This is not an asset that I want to share publically, which is why I don't want to have it in the `static` folder

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-eromzr?file=src/routes/todos/_api.js

1. Run `npm run build`
2. Run `node build`
3. Click on the "Todos" link
4. See image path in the console

### System Info

```shell
This command doesn't seem to work on StackBlitz 😄
```

### Severity

serious, but I can work around it

### Additional Information

I guess I can work around it by having all assets in the `static` folder, which is included in the build correctly.

But then all the assets are public. So then I guess I can have some sort of logic in `hooks.ts` that would prevent access to those files.

**Comment by 7antra** [comment]
This is a serious issue ! Because assets are now considered as route by the layout... so it throws a 404 and event could erase $page.stuff if you use it for metadata in your __error.svelte

**Comment by 7antra** [comment]
https://github.com/sveltejs/kit/pull/4974

**Comment by Rich-Harris** [comment]
possible related: #1567

**Comment by nmfrankel** [comment]
I just got this issue using @sveltejs/adapter-static@1.0.0-next.39 and my auto deploys (using adapter-auto) on vercel started throwing 404 for missing static files.

**Comment by nmfrankel** [comment]
Everything is now working after doing ``npm update``.

I got the following message with directions to change config
> svelte-kit build is no longer available — use vite build instead

All good 😊

**Comment by Rich-Harris** [comment]
Opened https://github.com/vitejs/vite/issues/11429

**Comment by LukaHarambasic** [comment]
Does a workaround exist?

**Comment by Rich-Harris** [comment]
Yes, import the assets somewhere in your client code. As long as you don't _use_ them in client code, the paths will be treeshaken away so they won't impact your client-side bundle size.

**Comment by thechubbypanda** [comment]
I just tried vite 4.1.0-beta.1 which should have the fix from https://github.com/vitejs/vite/issues/11429 and my similar error still occurs, are others still seeing the same thing?

**Comment by matfantinel** [comment]
@thechubbypanda I'm also still facing the error with vite 4.1.0-beta.1, but I don't think it includes the fix, since it's not on [the changelog document](https://github.com/vitejs/vite/blob/v4.1.0-beta.1/packages/vite/CHANGELOG.md#410-beta1-2023-01-26) yet.

**Comment by mahi160** [comment]
I had a similar issue with production. I used as `background-image: url('images/hexagon.svg')` in the `<style></style>`, but was not getting the image in the production. It was searching in _app/immutable.

But when i put the url as variable in the script, and did an inline styling lin `style="background-image: url({src})"` it worked just fine!
[This](https://svelte.dev/repl/2594c50ed8f94798898e11416951babc?version=3.44.2) example helped me.

![image](https://user-images.githubusercontent.com/50174250/219099388-3e28376a-e0d7-4b1d-8945-8749aa557e58.png)
![image](https://user-images.githubusercontent.com/50174250/219099625-b98aec94-326c-4cbe-98b1-ec956170e558.png)
