### ISSUE TITLE
__layout props update on every route change

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#5247]
### Describe the bug

Not sure if this is a bug or should just be a discussion, but it was a surprise. When loading some data _once_ in a parent __layout I expected that data to then remain static. But the props appear to be re-assigned on every navigation, even for querystring parameter changes. This plays havoc with any `use:actions` which think things have been updated when they haven't (which may contain image gallery layout code, canvas setup etc... that I only want to re-run when the data actually changes)

### Reproduction

Simplified example to show the behavior:
https://github.com/CaptainCodeman/sveltekit-layout-props-example

Run the project and navigate around. Note the prop changes and action update console logs, even though the `load` function has only executed once:

<img width="484" alt="Screen Shot 2022-06-22 at 12 38 08 PM" src="https://user-images.githubusercontent.com/304910/175111993-c175289f-cdb8-4146-ad68-cc045420c05a.png">

I wouldn't expect the `data` prop to keep changing or for the `use:action` to keep being updated, but they are in both the __layout and an imported component.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 335.20 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 102.0.5005.115
    Chrome Canary: 105.0.5134.0
    Edge: 102.0.1245.41
    Firefox: 101.0.1
    Safari: 15.5
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.34 
    @sveltejs/kit: next => 1.0.0-next.352 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

**Comment by CaptainCodeman** [comment]
NOTE: the `data` is the same object reference each time, so I'm actually kind of surprised that it updates as it does but I guess it's doing it on the assignment operation and ignoring any reference check (which I thought Svelte did to avoid unnecessary updates).

I can get it to give the expected behavior by checking for the reference change myself. i.e. return dataraw from the load function and check for it differing from a local variable:

``` js
export let dataraw

let data

$: if (data !== dataraw) data = dataraw
```

**Comment by jacob-8** [comment]
> should just be a discussion

I appreciate that the load function runs every time queryparams change. This is important as it gives a lot of flexibility for pages where one might want to show multiple panels side by side based on queryparams. For example:

.../read?pane1=doc1234&pane2=doc34&pane3=doc55

**Comment by Co1eCas3** [comment]
I believe this issue I've run into is related to this discussion, and I do believe it to be an issue.

I've discovered that when altering the state of props that are import from a load function in a layout, those state changes are not retained when navigating. The load function does not re-run at all, nor do any function that may be responsible for altering said state. The props simply are reverted back to their initial state on first load for no apparent reason. This is irregardless of any load input that may or may not be used.

Please refer to [this example](https://github.com/Co1eCas3/sveltekit-layout-load-issue) repo I've created for a clearer picture.

While @CaptainCodeman calls it a mere 'annoyance', I feel this could be particularly detrimental in some scenarios, especially if/when layout endpoints are finally introduced.
