### ISSUE TITLE
`src/params/*.js` files with a `-` in their name cause svelte-kit to throw an error

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#5261]
### Describe the bug

If you add `src/params/foo-bar.js` and use it on a directory like `src/routes/foo/[category=foo-bar]` dev/build runtimes crash due to a thrown error (see logs). 

### Reproduction

https://github.com/UltraCakeBakery/svelte-kit-param-matcher-dash-name-bug

### Logs

```shell
file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:241
                                                                                                const [, rest, name, type] = /** @type {RegExpMatchArray} */ (
                                                                                                                                                             ^

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:241:74
    at Array.map (<anonymous>)
    at file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:239:12
    at Array.map (<anonymous>)
    at parse_route_id (file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:223:8)
    at file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:432:15
    at Array.forEach (<anonymous>)
    at create_manifest_data (file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:358:39)
    at update (file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/sync.js:1001:24)
    at update_manifest (file:///P:/named-layouts-bug/svelte-kit-param-matcher-dash-name-bug/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.354_svelte@3.48.0/node_modules/@sveltejs/kit/dist/vite.js:1961:29)
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.33 GB / 15.75 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.52
    @sveltejs/kit: next => 1.0.0-next.354
    svelte: ^3.46.0 => 3.48.0
```

### Severity

serious, but I can work around it

### Additional Information

My project heavily relies on fall through routes. I expect to have quite a lot of files in `src/params` by the end of my refactor here. I need the `-` to represent a `/`, to simulate what it would be like if param matchers lived inside the `routes` folder.

**Comment by rmunn** [comment]
Since the route names get turned into Javascript property names (off of the `params` object), it's unlikely that `-` will ever be supported; the design intent is for only valid Javascript *identifier* characters to be supported (as you can tell from that regex), so that you can do this:

```js
const { foo, bar } = params;
console.log(`Got params ${foo} and $[bar}`);
```

If `-` or other characters were allowed, that would be harder to write:

```js
const { foo, bar } = params;
const other = params['baz-quux'];
```

Not impossible, but significantly harder. So it's rather unlikely that Rich will decide to allow non-identifier-legal characters as param names.

Any chance you could use `_` instead of `-` to represent a slash in your use case? Or, if `_` is impractical because you're already using underscores in your route names, you could work around that by representing a slash by a combination of characters highly unlikely to appear elsewhere in your names, like `_SLASH_` or something. That would at least let you proceed now, without waiting for an enchanceent request that's unlikely to be implemented.

**Comment by furudean** [comment]
@rmunn This is valid js
```js
const { foo, bar, 'baz-quux': baz_quux } = params
```

**Comment by UltraCakeBakery** [comment]
> Since the route names get turned into Javascript property names (off of the `params` object), it's unlikely that `-` will ever be supported; the design intent is for only valid Javascript _identifier_ characters to be supported (as you can tell from that regex), so that you can do this:
> 
> ```js
> const { foo, bar } = params;
> console.log(`Got params ${foo} and ${bar}`);
> ```
> 
> If `-` or other characters were allowed, that would be harder to write:
> 
> ```js
> const { foo, bar } = params;
> const other = params['baz-quux'];
> ```
> 
> Not impossible, but significantly harder. So it's rather unlikely that Rich will decide to allow non-identifier-legal characters as param names.
> 
> Any chance you could use `_` instead of `-` to represent a slash in your use case? Or, if `_` is impractical because you're already using underscores in your route names, you could work around that by representing a slash by a combination of characters highly unlikely to appear elsewhere in your names, like `_SLASH_` or something. That would at least let you proceed now, without waiting for an enchanceent request that's unlikely to be implemented.

Is there also a more technical reason for this to be supported? I find it an uncommon convention and somewhat random limitation in sveltekit. I understand that it is harder to write, but that can't be the only reason right? If so, why is it not forced on properties added to the `$session` store or `$page.stuff`?

**Comment by gtm-nayan** [comment]
> why isn't the same regex forced on properties added to $session or $page.stuff

Those come from users and get passed to users without any intervention from SvelteKit, param/matcher names have to be parsed to extract information.

It's not impossible but does add some complexity to route parsing which imo isn't all that worth it considering underscores serve the purpose of separators just as well. There's also the question of at what characters do we stop.

> I find it an uncommon convention and somewhat random limitation

FWIW, path-to-regexp does so too https://github.com/pillarjs/path-to-regexp#named-parameters
