### ISSUE TITLE
Nested Error Page Behavior Inconsistent with SvelteKit Docs

### ISSUE THREAD

**Issue by cliftonlabrum** [sveltejs/kit#5267]
### Describe the bug

I'm using **SvelteKit v1.0.0-next.354**

The [SvelteKit documentation here](https://kit.svelte.dev/docs/layouts#error-pages) states:

> For example, if `src/routes/settings/notifications/index.svelte` failed to load, SvelteKit would render `src/routes/settings/notifications/__error.svelte` in the same layout, if it existed. If not, it would render `src/routes/settings/__error.svelte` in the parent layout, or `src/routes/__error.svelte` in the root layout.

It seems that it will always use the top-level `__error.svelte` page for a folder with a fixed value. It seems to work correctly if your folder name is a parameter like `[id]`. 

See the reproduction for an example.

### Reproduction

1. Create a new SvelteKit skeleton project.
2. Inside the `routes` folder, create `__error.svelte` in `/routes`
3. Inside `/routes` create `index.svelte`.
4. Inside the `routes` folder, create a `test` folder.
5. Inside `/routes/test` create `index.svelte`.
6. Inside `/routes/test` create `__error.svelte`.
 
<img width="181" alt="Folder Structure" src="https://user-images.githubusercontent.com/2513753/175645262-11b8b9ae-5d71-43de-aa98-5f52db168169.png">

Then visit the following URLs and observe the following results:

✅ Correct: `http://localhost:3000/` ➡️ `/routes/index.svelte` content

✅ Correct: `http://localhost:3000/asdf` ➡️ `/routes/__error.svelte` content

✅ Correct: `http://localhost:3000/test` ➡️ `/routes/test/index.svelte` content

⛔️Incorrect: `http://localhost:3000/test/asdf` ➡️ `/routes/__error.svelte` content, but should be `/routes/test/__error.svelte` content

**Reproduction Project:** 
https://github.com/cliftonlabrum/SvelteKitErrorPageTest

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.08 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
Browsers:
    Chrome: 103.0.5060.53
    Safari: 15.5
npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.52 
    @sveltejs/kit: next => 1.0.0-next.354 
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

**Comment by philip-weber** [comment]
I'd say it is working as documented. Please have a look into the docs in the [Error pages - 404s](https://kit.svelte.dev/docs/layouts#error-pages-404s) section.

> Nested error pages are only rendered when an error occurs while rendering a specific page. In the case of a request that doesn't match any existing route, SvelteKit will render a generic 404 instead. or example, given these routes...

> src/routes/
├ __error.svelte
├ marx-brothers/
│ ├ __error.svelte
│ ├ chico.svelte
│ ├ harpo.svelte
│ └ groucho.svelte

> ...the `marx-brothers/__error.svelte` file will not be rendered if you visit `/marx-brothers/karl`. If you want to render the nested error page, you should create a route that matches any `/marx-brothers/*` request, and return a 404 from it

This would mean in your example that you need to create a route that matches any `/test/*` request, and return a 404 from it. For example `src/routes/test/[...path].svelte`
