### ISSUE TITLE
Move enhance action for forms to module `@sveltejs/kit/enhance`

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#5281]
Can we for now expose existing enhance action, so instead of having it in `$lib/` we could be able to import it from `@sveltejs/kit/enhance` or something like that?

_Originally posted by @Mlocik97 in https://github.com/sveltejs/kit/issues/3533#issuecomment-1166571303_

**Comment by benmccann** [comment]
Duplicate of https://github.com/sveltejs/kit/issues/3533
