### ISSUE TITLE
Production build does not work

### ISSUE THREAD

**Issue by ollydixon** [sveltejs/kit#5297]
### Describe the bug

Trying to run a simple Svelte-kit app for production, cannot get it working :-/

### Reproduction

Trying to run a simple Svelte-kit app for production, cannot get it working :-/

Running with 

```npm run build (svelte-kit build)```

Then ```node ./svelte-kit/build/index.js```

Get the following error

```Cannot find package '__GENERATED__'```

Running the following docker I get the same result.

```
FROM node:16.15.1-alpine

WORKDIR /app
COPY . .

RUN npm ci
RUN npm run build

COPY ./svelte-kit/build ./build

EXPOSE 3000
CMD ["node", "build"]
```

### Logs

```shell
Error: Cannot find module '/Users/oliverdixon/Projects/app-name/app-name-website/svelte-kit/build/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.52 
    @sveltejs/kit: next => 1.0.0-next.354 
    svelte: ^3.46.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
That's not the production build you're trying to run, it's the intermediate output that should be passed to an adapter.

Assuming you want to use a node server, follow the instructions [here](https://github.com/sveltejs/kit/tree/master/packages/adapter-node) to set it up, after which the server will be created inside the `build` directory.

**Comment by ollydixon** [comment]
For anyone else who wasted hours on this, here is a complete setup.

Make sure to change the ```svelte.config.js```
So that the import is 
`import adapter from '@sveltejs/adapter-node';`

then, change the adapter line to: `adapter: adapter({ out: './build' }),`

And here is the docker file I used in the end

```
# First stage to build and copy all files.
FROM node:16.15.1-alpine3.14 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build && npm prune --production

# Second stage removes src files and reduces the size.
FROM node:16.15.1-alpine3.14
USER node:node
WORKDIR /app
COPY --from=builder --chown=node:node /app/build ./build
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node package.json .
ENV PORT 3000
EXPOSE 3000
CMD ["node","build"]
```
