### ISSUE TITLE
goto doesn't preserve hash

### ISSUE THREAD

**Issue by markfswe** [sveltejs/kit#5300]
### Describe the bug

goto does not take into account hash in url at all.

`goto("/profile/settings#kyc")` will do the same as `goto("/profile/settings")` except some buggy scrollTo animations.

### Reproduction

https://stackblitz.com/edit/sveltekit-tatdzc?devtoolsheight=33&file=src%2Froutes%2Findex.svelte

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 76.67 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.5.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome Canary: 105.0.5147.0
    Firefox Developer Edition: 102.0
    Safari: 15.3
    Safari Technology Preview: 15.4
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.34 => 1.0.0-next.34 
    @sveltejs/kit: 1.0.0-next.355 => 1.0.0-next.355 
    @sveltejs/vite-plugin-svelte: 1.0.0-next.49 => 1.0.0-next.49 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Is this different from the several other issues that appear when you search for "scroll"? https://github.com/sveltejs/kit/issues?q=is%3Aissue+is%3Aopen+scroll

**Comment by ZerdoX-x** [comment]
> Is this different from the several other issues that appear when you search for "scroll"?

Can't see any similar issues. This is not really related to scroll as even URL in browser doesn't changes and hashchange event is not fired.

**Comment by PatrickG** [comment]
> > Is this different from the several other issues that appear when you search for "scroll"?
> 
> Can't see any similar issues. This is not really related to scroll as even URL in browser doesn't changes and hashchange event is not fired.

You should check error in the console. You need to import the `goto` function from `$app/navigation`.

**Comment by ZerdoX-x** [comment]
@PatrickG @Conduitry Sorry. My bad. I updated the REPL

**Comment by PatrickG** [comment]
The hash do change.
The hashchange event does not fire when doing a history.pushstate.
I think everything works like it should.
