### ISSUE TITLE
Abort Stale Invalidation Request

### ISSUE THREAD

**Issue by john-michael-murphy** [sveltejs/kit#5305]
### Describe the problem

Consider the scenario where several [invalidate requests](https://kit.svelte.dev/docs/modules#$app-navigation-invalidate) to the same dependency are triggered in rapid succession (say because of an updating query parameter, e.g. `?search=foo`). 

The order in which these requests return from the server is not guaranteed, which means it's possible that the last resolving revalidation will be stale.

### Describe the proposed solution

I wonder if we allow an optional abort signal, where `AbortSignal` implements the canonical [Abort API](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal). 

```typescript
function invalidate(
  dependency: string | ((href: string) => boolean)
  options?: { signal?: AbortSignal } 
): Promise<void>;
```

### Alternatives considered

Sveltekit's invalidate function could manage this automatically, but I worry there are scenarios where one might need multiple inflight invalidation requests. 

### Importance

would make my life easier

### Additional Information

As always, thanks so much for all the great work! Sveltekit is such a gamechanger for NYTs!

**Comment by dummdidumm** [comment]
I think the problem is not a race condition, but that `invalidate` blocks all other invalidation requests while one invalidation is running, which in this case means getting outdated results. It would probably be better to remove this logic and let invalidates run as they come.

**Comment by Carlos-err406** [comment]
hello, im facing this issue, where i have to run several invalidations with `invalidate(resource)` that can overlap, but im only interested on the last one and i can't find any way to abort the staled invalidations.

any help or workarounds on how to do so, would be very appreciated
