### ISSUE TITLE
`handle()` redirects should work with browser router

### ISSUE THREAD

**Issue by furudean** [sveltejs/kit#5309]
### Describe the problem

Currently, if you set up a redirect using hooks.js `handle()` like so:

```js
/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
  if (event.url.pathname === "/from") {
    return new Response(null, { status: 302, headers: { location: "/to" } });
  }
 
  const response = await resolve(event);
  return response;
}
```

and then navigate with a link `<a href="/from">Link</a>` you should expect it to redirect to `/to` when activated. 

In reality Svelte Kit tries, and fails to navigate to the non-existent page `/from`. This is unintuitive.

### Describe the proposed solution

Svelte Kit is smart and can pick up on `302` responses from the server.

### Alternatives considered

The workaround is to handle this with JavaScript code, which means duplicating code across both server and client.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
I don't know how this would work. We don't want to make a request to `/from` whenever the user clicks a link to `/from` because that would defeat a lot of the purpose of hydrating to a client-rendered app.

**Comment by furudean** [comment]
Does Svelte Kit not contact the server to request new pages? In this suggested implementation, the server would say "hey, this is a redirect!", and then deliver the page it's redirecting to. The router would update the url as well. 

Did I overlook some part of this process?

**Comment by justingolden21** [comment]
It seems like hydrating this way fails to mimic "real" behavior where `handle` doesn't run redirects when changing links in a navbar or footer for example, so you have an inconsistent experience between typing the URL in browser initially and then clicking around the website. This example of course is only for people putting links they want to redirect inside their nav which is dumb, but it's just one of many cases when you'd want to mimic non hydrated behavior.

**Comment by Conduitry** [comment]
The browser SvelteKit code does routing on the client, loads the JS necessary to run the `load()` function for that page, and runs that (or, if appropriate, it first calls the corresponding shadow endpoint for that page). When navigating to `/from` via client-side navigation, `/from` is not one of the requests made by the browser.

**Comment by justingolden21** [comment]
So with the current setup it would be impossible, difficult, or unperformant?

**Comment by Conduitry** [comment]
Yes. If you want to have this sort of redirection happen during client-side rendering, it should happen in the response from a `load()` function. We don't want to make and wait for requests to `/from` for every navigation just in case there's a redirect happening in the `handle` function.

**Comment by furudean** [comment]
Point taken. Thanks for clarifying that.

This again makes me question if Svelte Kit should have some sort of built in redirect-from-a-list manifest. Putting a load on every page seems undesirable. This is more important with a large CMS compared to a small app, but I wonder what can be done for this use case beyond just "custom code". It's not exactly an uncommon use case.

**Comment by furudean** [comment]
[Next has this built in](https://nextjs.org/docs/api-reference/next.config.js/redirects).

**Comment by Conduitry** [comment]
Closing, as this feature isn't going to be implemented as described. If you have a proposal for configuring redirects that happen in both the server and on the client, you're free to open another issue for that. Or if doing this redirect check in a `__layout` works for you, great.

**Comment by MentalGear** [comment]
Using the proposed workaround using a layout.(server).ts file also won't work and will still result in the above mentioned error.

Even using sveltekit's `redirect` won't work.
```ts
    if (userOnPrivateRoute && !userAuthentication) {
            // redirect
            throw redirect(303, '/no-auth') // still HTML instead of JSON returned client-side
            // return Response.redirect('[...]/no-auth', 303)
    }
```
Sveltekit's redirect states:
```ts
/**
 * Creates a `Redirect` object. If thrown during request handling, SvelteKit will
 * return a redirect response.
 */
export function redirect(status: number, location: string): Redirect;
```

Maybe we could extend sveltekit's `redirect` to execute:
- client-side:
`window.location.replace('/${redirectionPath}')`
-  serverside:
as it is now (returning a Response)

Would be really great to have an client/server idiomatic method for this. @Rich-Harris 
Happy to give this a PR if you concur this'd be the way to go.
