### ISSUE TITLE
Redesign layouts (again) to make it less chaotic and more programatically

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#5316]
### Describe the problem

I think from all features that Svelte and SvelteKit offer, layouts are actually the most confusing and complicated feature. So I agree with @furudean . I use it really carefully and a lot of more complicated stuff that someone would typically use layouts for, I do with dynamic content... like:

`./src/routes/__layout.svelte`:
```html
<script>
    import SomeContainer from '$lib/SomeContainer.svelte';
    import { page } from '$app/stores';
 </script>
 
 {#if $page.url.pathname.startWith('/something')}
     <SomeContainer>
         <slot />
     </SomeContainer>
 {:else}
     <slot />
 {/if}
 ````
 
 even tho, doing it with named layouts would make more sense.... and it's just because I find this less chaotic, mainly in more complicated layout structures.

### Describe the proposed solution

I think, we need to redesign layouts (again),... and I got idea of having `./src/layouts/` folder, where we would be able to create all layouts, use them for pages programatically. In pages, we would have:

```html
<script context="module">
   export const layouts = {
		a: {
			b: {
				c: {}
			}
		}
	};
</script>
```

and it would render content of that page in layout c that would be in layout b that would be in layout a. Or something like this. (actually that export const layouts is just first idea, it would probably look different, but somehow we would define all layouts like this)

### Alternatives considered

Same thing, but would define names how pages are nested via `@c@b@a` sequence, that will tell it's inside layout c, that is inside layout b that is inside layout a. And we will break inheritence (resp. move it from layout structure to page name). This would allow us to reset layout by simply not using `@` in page name at all.

### Importance

nice to have

### Additional Information

_Originally posted by @Mlocik97 in https://github.com/sveltejs/kit/issues/5311#issuecomment-1170395513_

**Comment by UltraCakeBakery** [comment]
It might be better to close this ticket and continue the discussion in the [thread made by Rich Harris](https://github.com/sveltejs/kit/discussions/5037)

People there made suggestions about adding a `/layouts` folder already. 
I [made a suggestion](https://github.com/sveltejs/kit/discussions/5037#discussioncomment-3031389) there that includes a `/layouts` folder, but also comes with some bigger changes.

I recommend upvoting the ideas / comments that you like there.
