### ISSUE TITLE
getSession didn't get called in production. development and preview runs ok.

### ISSUE THREAD

**Issue by taganchua** [sveltejs/kit#5323]
### Describe the bug

Before I update npms,

my project is old and use Sveltekit v1.0.0-next.326. vite 2.9.8.

svelte.config.js
```
import adapter from '@sveltejs/adapter-node';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess({}),
	kit: {
		adapter: adapter({
			out: 'build'
		})
	}
};

export default config;
```

hooks.ts
```
import { parse } from 'cookie';
import { UAParser } from 'ua-parser-js'; 

export const handle = async ({ event, resolve }) => {
	const parser = new UAParser(event.request.headers.get('user-agent') || '');
	const cookies = parse(event.request.headers.get('cookie') || '');
	if (cookies) {
		...
               event.locals.user = { .... };
	}

	return await resolve(event);
};

export function getSession({ locals }) {
	return {
		user: locals.user
	};
}
```

It runs fine in all enivornments.

Some npm modules are outdated and after I updated some npm modules (Sveltekit v1.0.0-next.357. vite 2.9.13), development and preview run OK. But production cannot work. getSession didn't get called.

I tried this https://github.com/sveltejs/kit/issues/3722#issuecomment-1036526539. Still cannot work.

Anyone knows? How to solve this issue?

### Reproduction

https://github.com/taganchua/TestApp

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 3.73 GB / 15.81 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.12.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.66
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.40 => 1.0.0-next.53
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.78
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.34
    @sveltejs/kit: ^1.0.0-next.326 => 1.0.0-next.357
    svelte: ^3.48.0 => 3.48.0
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
FWIW, I added a getSession to the demo app with the node adapter and it's running fine in all modes.

Please provide a proper reproduction for the issue.

**Comment by taganchua** [comment]
Updated first post in reproduction.

https://github.com/taganchua/TestApp

Login button is in first page. And the cookie is UserID: undefined

After click login, UserID would be "TesterName".

Development works fine. Preview cannot work. I put console.log() in getSession(). It didn't get called in my side.

**Comment by quasarchimaere** [comment]
i had the same issue, and it turned out that `getSession()` was called for all pages but the ones that had the `prerender = true` constant in the component code... not sure if that helps you

**Comment by quasarchimaere** [comment]
https://github.com/taganchua/TestApp/blob/73bc6d16bae6dc43033095b8dd4b16208f944996/src/routes/index.svelte#L2

this line is the reason why getSession() is not called in production, since this flag is setting the whole page (and its children) to be precompiled (in production) and thus accessing this route will only return a static html page to the client disregarding the hooks logic

**Comment by taganchua** [comment]
> i had the same issue, and it turned out that `getSession()` was called for all pages but the ones that had the `prerender = true` constant in the component code... not sure if that helps you

Forgot to remove that in this project. But my old project has set prerender = false already. I'll double check.

**Comment by taganchua** [comment]
Weird, my old project now ok. It couldn't work yesterday and I didn't even change any code in my old project today.

Thanks anyway!
