### ISSUE TITLE
Bug: `vm2` can't be imported and used in Endpoints with Vercel only

### ISSUE THREAD

**Issue by kaleabmelkie** [sveltejs/kit#5339]
### Describe the bug

The following Endpoint produces an error when deployed in Vercel.

```ts
// src/routes/test.ts

import vm2 from "vm2";

export async function get() {
  const nodeVm = new vm2.NodeVM();
  nodeVm.run('console.log("hi from the vm")');

  return {status: 200, body: {message: "Hi!"}};
}
```

The error is:

```
500
Cannot read properties of undefined (reading 'default')
TypeError: Cannot read properties of undefined (reading 'default')
```

I've done `console.log({vm2})` and it removes the library's functions, and logs an empty brace inside Vercel (the functions `NodeVM`, `VM`, etc. are stripped off):
```
{vm2: {default: {}}}
```

Everything works inside local SvelteKit (no adaptors), in pure/vanilla Vercel Serverless Functions, and in Vercel Serverless Functions with a Vite project. This happens when a SvelteKit repo with Endpoints is deployed to Vercel.

### Reproduction

Repo: https://github.com/kaleabmelkie/sk-vm2-bug
Link: https://sk-vm2-bug.vercel.app/test

Or, follow these steps:

```
pnpm create svelte@next

pnpm add vm2 -D

# add an Endpoint that uses vm2

vercel --prod

# navigate to that endpoint, and it crashes because the functions (NodeVM, etc...) aren't found.
```

### Logs

```shell
TypeError: Cannot read properties of undefined (reading 'default')
```

### System Info

```shell
System:
  OS: macOS 12.4
  CPU: (8) arm64 Apple M1 Pro
  Memory: 200.42 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
  Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
  npm: 8.12.1 - ~/.nvm/versions/node/v16.15.1/bin/npm
Browsers:
  Chrome: 103.0.5060.53
  Firefox: 101.0.1
  Safari: 15.5
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.53 
  @sveltejs/kit: next => 1.0.0-next.357 
  svelte: ^3.44.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
The Vercel endpoints get bundled with esbuild. You could try bundling a Vercel Serverless Function with esbuild and see if that breaks things as another thing to test. I expect there's a high likelihood this is where that's coming from and would need to be filed as an esbuild bug

**Comment by gtm-nayan** [comment]
Closing since serverless functions aren't bundled anymore so it's unlikely to be a problem now.
