### ISSUE TITLE
Passing shadow endpoint response error to __error.svelte page

### ISSUE THREAD

**Issue by KarolusD** [sveltejs/kit#5341]
### Key points:
1. I noticed that custom error could be easily passed when the get request is implemented in the load fn of the *.svelte files.
```
  export const load: Load = async () => {
    // fetch happens here and in case of an error we return i.e
    return {
      status: 404,
      error: new Error('Something went wrong') // <-- passing error
    }
  }
```

2. If the same get request is implemented as shadow endpoint in *.ts file, the error is NOT received in the __error.svelte page
```
export const get: RequestHandler = async () => {
  return {
    status: 404,
    error: new Error('Custom error message') // custom error is not received in __error.svelte
  }
}
```

3. In both cases status code is passed to __error.svelte page

I would like to know if that's somehow indented by sveltekit or is it a potential area for improvement.

### Describe the proposed solution

I would like to see a possibility to pass the custom error object from shadow endpoint to the __error.svelte page
just like it works in other requests made in load fn on svelte pages. 

shadow endpoint:
```
export const get: RequestHandler = async () => {
  return {
    status: 404,
    error: new Error('Custom error message')
  }
}
```

__error.svelte page
```
export const load: Load = ({ error, status }) => {
  return {
    props: {
      status,
      error: `${error?.message}` // returns "Custom error message"
    }
  }
}

```

### Alternatives considered

We could also consider passing other values to __error.svelte page like response body for example.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
You can do this today — you just need to pass an `Error` instance as the `body`:

```diff
export const get: RequestHandler = async () => {
  return {
    status: 404,
-    error: new Error('Custom error message')
+    body: new Error('Custom error message')
  }
}
```

**Comment by KarolusD** [comment]
Thanks for the clarification @Rich-Harris! I guess I was confused and tried to return in this way because it's the way of returning error in load function (https://kit.svelte.dev/docs/layouts#error-pages-404s)
```
 export function load({ params }) {
    return {
      status: 404,
      error: new Error(`Not found: /marx-brothers/${params.path}`)
    };
  }
```

I also tried to return errors in this way, as this is usually how I pass errors inside POST requests and this is the way how it's currently documented (https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete)
```
body: {
    errors
}
```

But as I can see error object has to go straight to the body to then be able to grab it in __error.svelte page.
Maybe it's just me, but It would be great to have a bit clearer docs on it somewhere here (https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete)
