### ISSUE TITLE
Cannot find package 'stream'

### ISSUE THREAD

**Issue by IvanCastroR** [sveltejs/kit#5342]
### Describe the bug

I am trying to create a new sveltekit project but I get the error when I run: npm run dev, 

I have seen this error mentioned before and tried the solutions they gave but nothing, I find it quite strange that this error occurs even when creating a new project.

NPM: 8.1
NODE: 16.13

### Reproduction

npm create svelte my-app
cd my-app
npm install
npm run dev -- --open or npm run dev

### Logs

> Cannot find package 'stream' imported from C:\****\node_modules\@sveltejs\kit\dist\vite.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:687:9)
    at moduleResolve (internal/modules/esm/resolve.js:728:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)

### System Info

 System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 Graphics
    Memory: 4.62 GB / 10.96 GB
  Binaries:
    Node: 14.18.2 - ~\node_modules\.bin\node.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.66
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.68 => 1.0.0-next.68
    @sveltejs/kit: 1.0.0-next.357 => 1.0.0-next.357
    svelte: ^3.44.0 => 3.47.0

### Severity

blocking all usage of SvelteKit

### Additional Information

NPM: 8.1
NODE: 16.13
sveltejs/kit: 1.0.0-next.357

**Comment by gtm-nayan** [comment]
Can't repro on either windows or linux with next.357, closest thing I got was a experimental feature warning for "stream/web".

Fill in the system info field properly please

**Comment by IvanCastroR** [comment]
> Can't repro on either windows or linux with next.357, closest thing I got was a experimental feature warning for "stream/web".
> 
> Fill in the system info field properly please

sorry, Windows 10 x64 with sveltejs/kit: 1.0.0-next.357

**Comment by PH4NTOMiki** [comment]
@IvanCastroR do `npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"` in the `my-app` folder

**Comment by IvanCastroR** [comment]
sorry again, done post update:
 System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 Graphics
    Memory: 4.62 GB / 10.96 GB
  Binaries:
    Node: 14.18.2 - ~\node_modules\.bin\node.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.66
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.68 => 1.0.0-next.68
    @sveltejs/kit: 1.0.0-next.357 => 1.0.0-next.357
    svelte: ^3.44.0 => 3.47.0

**Comment by IvanCastroR** [comment]
> @IvanCastroR do `npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"` in the `my-app` folder

sorry again, updated post:
System:
OS: Windows 10 10.0.19044
CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 Graphics
Memory: 4.62 GB / 10.96 GB
Binaries:
Node: 14.18.2 - ~\node_modules.bin\node.CMD
npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: 103.0.5060.66
Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
Internet Explorer: 11.0.19041.1566
npmPackages:
@sveltejs/adapter-node: 1.0.0-next.68 => 1.0.0-next.68
@sveltejs/kit: 1.0.0-next.357 => 1.0.0-next.357
svelte: ^3.44.0 => 3.47.0

**Comment by IvanCastroR** [comment]
@PH4NTOMiki  
sorry again, updated post:
System:
OS: Windows 10 10.0.19044
CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 Graphics
Memory: 4.62 GB / 10.96 GB
Binaries:
Node: 14.18.2 - ~\node_modules.bin\node.CMD
npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: 103.0.5060.66
Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.44)
Internet Explorer: 11.0.19041.1566
npmPackages:
@sveltejs/adapter-node: 1.0.0-next.68 => 1.0.0-next.68
@sveltejs/kit: 1.0.0-next.357 => 1.0.0-next.357
svelte: ^3.44.0 => 3.47.0

**Comment by gtm-nayan** [comment]
Can recreate it with v14, but SvelteKit doesn't intend to support v14 anymore, so you have to upgrade your Node to v16 or higher

see #4916

**Comment by IvanCastroR** [comment]
> Can recreate it with v14, but SvelteKit doesn't intend to support v14 anymore, so you have to upgrade your Node to v16 or higher
> 
> see #4916
what is the difference?
I am supposed to have node [16.13.0]
![imagen](https://user-images.githubusercontent.com/95248750/177004164-53cb6c4e-fa3a-40c2-bd34-be23696162af.png)

**Comment by gtm-nayan** [comment]
You might have some other tool that's setting a different Node environment for your project than your CLI or npm could be linked to the wrong version. A fresh install could help.

Don't think there's anything else SvelteKit can do here.

**Comment by IvanCastroR** [comment]
> You might have some other tool that's setting a different Node environment for your project than your CLI or npm could be linked to the wrong version. A fresh install could help.
> 
> I don't think there's anything else SvelteKit can do here.

ok, thanks

**Comment by FWORDIE** [comment]
I am having the same issue on a fresh Sveltekit creation. 

However, I am on Node 16 I believe.

```
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 12.83 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/node_modules/.bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.79
    Firefox: 103.0
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.405 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.7 
```

VSCODE About

```
Version: 1.70.1 (Universal)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:09:06.916Z (3 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.4.0
```

**Comment by FWORDIE** [comment]
Yarn run dev works tho
