### ISSUE TITLE
`afterLoad` lifecycle function like `afterNavigate`

### ISSUE THREAD

**Issue by vpanyushenko** [sveltejs/kit#5368]
### Describe the problem

`beforeNavigate` and `afterNavigate` are really convenient to manage some state in other components like a loading indicator. However, when using a query param in the url, `afterNavigate` does not fire. I think this is intended? 

It's pretty common to have something like a select input that will update the query param which will trigger the svelte kit `load` function to rerun and get the new data from the server. Since `afterNavigate` does not fire here, it's a little tricky to stop the loading state inside of a component directly. Instead the way to do it is to wait for the value from the load function to change, then pass that into your component yourself. It ends up being a little verbose. 

### Describe the proposed solution

I would be convenient to have something like:

```js
import {afterLoad} from "$app/navigation"

afterLoad(() => {
  console.log("Runs after svelte kit load finishes")
})
```

It seems like it makes sense to pair this with `beforeLoad`, although that is already taken care of by just listening to the svelte kit `page` store since that will update if a query param is changed.   

### Alternatives considered

At the moment, this can be done by manually waiting for the value from `load` to change and doing it yourself. It's fine and works.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
I think this is a bug — `afterNavigate` should run when the query parameter changes, unless I've misunderstood. Do you have a repro handy?

**Comment by vpanyushenko** [comment]
Here's a repo for the issue: https://github.com/vpanyushenko/after-navigate-test

**Comment by Rich-Harris** [comment]
This is happening because you're not actually navigating, you're just doing `history.replaceState` and then tricking SvelteKit into rerunning `load` by setting the timestamp.

Do this instead:

```diff
  function addQueryParam(event) {
    const value = event.target.value;
    console.log("Adding search param:", value);

+   // if (browser) is unnecessary, this function will never run outside the browser.
+   // but i left it here because it would mess up the diff otherwise
    if (browser) {
-      const searchParams = new URLSearchParams(window.location.search);
+      const url = new URL(location.href);

      if (value === "" || value === null || value === undefined) {
-        searchParams.delete("search");
+        url.searchParams.delete("search");
      } else {
-        searchParams.set("search", value);
+        url.searchParams.set("search", value);
      }

+     goto(url);

      //I suspect this might be while the afterNavigate is happening.

      //The reason the state is being replaced instead of pushed is because this is common for applying filters
      //and it's really annoying to use the back button to go through the history of filters rather than just going
      //back to the previous page.

      //Should this be triggering load to rerun since the URL changed?
-      history.replaceState(null, "", "?" + searchParams.toString());

      //Update the session to trigger load to rerun
-      $session.timestamp = Date.now();

      //Can also use invalidate to trigger load to rerun but that used to be glitchy so i tend to use the session timestamp hacky way.
      //invalidate("https://pokeapi.co/api/v2/pokemon");
    }
  }
```
