### ISSUE TITLE
Support for root scrolling element other than document.scrollingElement

### ISSUE THREAD

**Issue by ramiroaisen** [sveltejs/kit#5371]
### Describe the problem

Provide a way to support scroll restoration in other element than the root element.

Sometimes you have the main scrolling element deeper in your layout than the `document.scrollingElement` 

### Describe the proposed solution

Add a config entry to `svelte.config.js` named "scrollingElementSelector" that, if specified, will be used by sveltekit to restore scroll position to and from this element.

The change won't be a breaking one because it can use the current behaviuor if left unspecified.

### Alternatives considered

I'm currently using `patch-package` to achieve this behaviour

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Closing in favour of https://github.com/sveltejs/kit/issues/5478 — the solution to this will be to read and write the scroll position in navigation lifecycle functions
