### ISSUE TITLE
Run Task `npm: dev` in VSCode - Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream'

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#5381]
### Describe the bug

When I run the dev server SvelteKit in VSCode, it returns an error with some package and the server does not start.

SvelteKit v next.359

Typing the `npm run dev` command manually in the Terminal in VSCode starts the development server without any problems.

I assume that this is not a problem with VSCode, but with SvelteKit, however, because older versions did not have this problem.

### Reproduction

VSCode -> Terminal -> Run Task... -> npm: dev

### Logs

```shell
> Executing task: npm run dev <


> svelte-triangle@0.0.1 dev
> vite dev

failed to load config from /media/x/svelte-triangle/vite.config.js
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'stream' imported from /media/x/svelte-triangle/node_modules/@sveltejs/kit/dist/vite.js
    at new NodeError (node:internal/errors:363:5)
    at packageResolve (node:internal/modules/esm/resolve:698:9)
    at moduleResolve (node:internal/modules/esm/resolve:739:18)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:853:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:73:40)
    at link (node:internal/modules/esm/module_job:72:36)
The terminal process "/usr/bin/bash '-c', 'npm run dev'" terminated with exit code: 1.
```

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 8.03 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.109
    Firefox: 102.0esr
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.53 
    @sveltejs/kit: next => 1.0.0-next.359 
    svelte: ^3.44.0 => 3.48.0 
    vite: ^2.9.13 => 2.9.13 
```

### Severity

serious, but I can work around it

### Additional Information
I use `nvm`, with the result that:
```
$ node -v
v18.4.0
$ nodejs -v
v16.3.0
```
...If it matters.

**Comment by Conduitry** [comment]
When this happened before (#5342) it was because an older version of Node was being used. Do you know what version of Node is used when you start using the VS Code UI? I'm guessing it might be some version of Node baked into VS Code and not what you have installed on your system.

**Comment by lukaszpolowczyk** [comment]
That's right:
```
Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:49:57.055Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.10.7-arch1-1
```

**Comment by lukaszpolowczyk** [comment]
When I run VSCode this way, it all works:
`nvm use node & /usr/bin/code --unity-launch`.

From this it appears that VSCode in Tasks does not use the version set in `nvm`, while in Terminal it does.

Is this the fault of the difference between `node` and `nodejs`? Or is it some completely different reason.

At the moment I would like to make a desktop launcher that fires this command:
`nvm use node & /usr/bin/code --unity-launch`.

BUT I would prefer the main node and nodejs to be version 18 due to nvm, and that is not happening for some reason.
This is a real problem to solve.

I wish I could just update the system....
