### ISSUE TITLE
All adapters seem broken with the new Vite plugin system

### ISSUE THREAD

**Issue by isaac-mcfadyen** [sveltejs/kit#5382]
### Describe the bug

After upgrading to the new Vite plugin style of SvelteKit (where a `vite.config.js` is used and `sveltekit()` is a plugin inside the `vite.config.js`) my adapters seem broken.

I've tried using both `adapter-auto` and `adapter-cloudflare`, and neither seem to work. Vite builds the bundle successfully but then exits with a "done in x seconds" message before entering the phase where the adapter takes over. No files are output.

My vite.config.js:
```js
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()]
};

export default config;
```

My svelte.config.js:
```js
import adapter from '@sveltejs/adapter-cloudflare';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: preprocess(),
	kit: {
		adapter: adapter()
	}
};

export default config;
```

### Reproduction

Upgrade to the newest versions of dependencies (`sveltekit@next`, `vite@2.9.13`) and try running a normal `vite build`.

Notice that no files are output to the directory where they are supposed to be for an adapter (in this case, `.svelte-kit/cloudflare`).

### Logs

```shell
Vite build seems to complete successfully but then doesn't ever enter the adapter stage.

$ vite build
vite v2.9.13 building for production...
✓ 845 modules transformed.
✨  Done in 2.86s.
```

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 562.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox Developer Edition: 102.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-cloudflare: ^1.0.0-next.24 => 1.0.0-next.24
    @sveltejs/kit: next => 1.0.0-next.359
    svelte: ^3.44.0 => 3.48.0
    vite: ^2.9.13 => 2.9.13
```

### Severity

non-urgent but definitely an issue

**Comment by isaac-mcfadyen** [comment]
Partially resolved. This has something to do with adding `monaco-editor` to dev dependencies. As soon as it's imported, Vite seems to give up building any adapters.

**Comment by isaac-mcfadyen** [comment]
Reopening this. This error seems to occur with *any* invalid imports (whether external libraries or `.svelte` components) and Vite should really be giving an error instead of silently failing.

**Comment by benmccann** [comment]
Please file an issue in the Vite repository instead: https://github.com/sveltejs/kit/#bug-reporting
