### ISSUE TITLE
Storybook support

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#5397]
### Describe the problem

Storybook mostly works now, but there's still some things that can be cleaned up. Opening this as a tracking issue for the various pending PRs

### Describe the proposed solution

- https://github.com/intuit/design-systems-cli/pull/701
- https://github.com/storybookjs/addon-svelte-csf/pull/61
- https://github.com/storybookjs/addon-svelte-csf/pull/62
- https://github.com/storybookjs/addon-svelte-csf/pull/63
- https://github.com/storybookjs/addon-svelte-csf/pull/66
- https://github.com/storybookjs/builder-vite/pull/427
- https://github.com/storybookjs/builder-vite/pull/428
- https://github.com/storybookjs/builder-vite/pull/444
- https://github.com/storybookjs/builder-vite/pull/445
- https://github.com/storybookjs/storybook/pull/18645
- https://github.com/storybookjs/storybook/pull/18651
- https://github.com/svelte-add/svelte-add/pull/220
- https://github.com/storybookjs/storybook/pull/19338
- https://github.com/storybookjs/storybook/issues/19409
- fix `npx sb init`
  - https://github.com/storybookjs/storybook/pull/18648
  - https://github.com/storybookjs/storybook/pull/18705
  - update `viteFinal` to match [michaelwooley/storybook-experimental-vite](https://github.com/michaelwooley/storybook-experimental-vite) when SvelteKit is present
  - reference:
    - [svelte generator](https://github.com/storybookjs/storybook/blob/next/lib/cli/src/generators/SVELTE/index.ts)
    - [base generator](https://github.com/storybookjs/storybook/blob/next/lib/cli/src/generators/baseGenerator.ts)
    - [example files](https://github.com/storybookjs/storybook/tree/next/lib/cli/src/frameworks/svelte)
- check potential alias issues on [michaelwooley/storybook-experimental-vite](https://github.com/michaelwooley/storybook-experimental-vite#readme) and public env vars issue https://github.com/sveltejs/kit/issues/6225#issuecomment-1226055441
 

### Importance

nice to have

**Comment by GauBen** [comment]
I ran into this very issue this morning, and after a bit of trial and error, I managed to have a working configuration: https://github.com/windicss/windicss/issues/267#issuecomment-1175919481

I'll try to contribute to svelte-add.

**Comment by benmccann** [comment]
I think rather than creating a new Svelte adder it may make more sense to fix `npx sb init`, which does the same thing

**Comment by IanVS** [comment]
For sb init, you have `remove need for yarn`.  There is some logic to detect the package manager in use based on the lockfile, but I've seen it fail sometimes and try to use yarn in npm projects.  It can be forced using `--use-npm`, but there's no `--use-pnpm`.

**Comment by benmccann** [comment]
I somehow had an empty `yarn.lock` file in my home directory that the generator was picking up on. I removed that and it's working now

**Comment by benbender** [comment]
Thanks for this combined effort! 🎉 

The last missing piece, after all those changes have landed, will be some kind of docgen-extraction for ts-types inside of svelte-components, right? 

The different storybook-svelte-packages (and more) are using https://github.com/alexprey/sveltedoc-parser which seems quite dead atm and, sadly, never finished support of doc-extraction of ts-components. Last time I checked there wasn't any complete/working solution for this problem. 

That's not really specific for storybook, but more a lack in the svelte-ecosystem.
Any plans to tackle that too?

**Comment by IanVS** [comment]
I wonder if some of https://github.com/styleguidist/react-docgen-typescript could be used as a starting point / reference to add sveltedoc-parser typescript support.  There was already some work in https://github.com/alexprey/sveltedoc-parser/compare/dev...typescript-support, I wonder if anyone would be willing to fork the project and continue working on adding support.  It seems like it would benefit much of the ecosystem.

**Comment by GauBen** [comment]
The [svelte language tools](https://github.com/sveltejs/language-tools) probably contain all that's needed to extract the documentation, given that it works in vscode: 

<img width="189" alt="image" src="https://user-images.githubusercontent.com/48261497/180227323-166b47bc-855d-44ff-bfe6-4d2be6a09e96.png">
<img width="431" alt="image" src="https://user-images.githubusercontent.com/48261497/180227433-32da5f2c-63f7-4630-850f-0eb6d6a367e2.png">

**Comment by dummdidumm** [comment]
Yes and no - we rely on typescript to show all of this, not sure how we could intercept this cleverly to get what we want. However, we indeed have some kind of extraction going on, which could be reused to achieve this. svelte2tsx is the package where it would be implemented

**Comment by IanVS** [comment]
I [mentioned](https://github.com/alexprey/sveltedoc-parser/issues/34#issuecomment-1145150500) svelte2tsx in the sveltedoc-parser typescript issue a while back, with no response.  @dummdidumm what do you envision would need to be done to achieve docgen from svelte typescript?

**Comment by benmccann** [comment]
Storybook 7 will have SvelteKit support: https://github.com/storybookjs/storybook/blob/next/code/frameworks/sveltekit/README.md

Pending PR in the Sotrybook repo: https://github.com/storybookjs/storybook/pull/20239

**Comment by ciscorn** [comment]
I just submitted a PR to introduce an approach using svelte2tsx and TypeScript.
https://github.com/storybookjs/storybook/pull/28492
