### ISSUE TITLE
List minimum node engine version in package.json

### ISSUE THREAD

**Issue by DougAnderson444** [sveltejs/kit#5405]
### Describe the problem

I just made the upgrade to `@svelte/kit 1.0.0-next.360` via `npm create svelte my-app` and it wouldn't run the server unless I upgraded Nodejs and npm.

### Describe the proposed solution

Listing the minimum node engine in the package.json for the code that is built with `npm create svelte my-app` 

### Alternatives considered

Blog post? A note in the create instructions? But listing it in the package.json is more fool proof.

### Importance

i cannot use SvelteKit without it

### Additional Information

If you have an older version of Nodejs, Sveltekit won't work out of the box.

**Comment by dominikg** [comment]
The package `@sveltejs/kit` already declares the minimum required node version here

https://github.com/sveltejs/kit/blob/885d0a8e6e75555918a2655dd4735244213d4e0f/packages/kit/package.json#L100

this leads to an error when installing wih node 14:

```
develop/reproductions/n14 ❯ node -v
v14.20.0
is 📦 v0.0.1 via  v14.20.0 
develop/reproductions/n14 ❯ npm i
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for @sveltejs/kit@1.0.0-next.360: wanted: {"node":">=16.7"} (current: {"node":"14.20.0","npm":"6.14.17"})
npm ERR! notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.360
npm ERR! notsup Not compatible with your version of node/npm: @sveltejs/kit@1.0.0-next.360
npm ERR! notsup Required: {"node":">=16.7"}
npm ERR! notsup Actual:   {"npm":"6.14.17","node":"14.20.0"}
```

**Comment by DougAnderson444** [comment]
Interesting, ok. I didn't get any errors when trying to build with node 16.6. 

What I meant in this issue was to transfer over the `"node": ">=16.7"` to the generated package, which also didn't happen with my scaffolding. 

I upgraded personally but hoping to save anyone else the headache if they try to use `svelte create` with <16.7
