### ISSUE TITLE
is Streaming Supported or publish yet?

### ISSUE THREAD

**Issue by AliBasicCoder** [sveltejs/kit#5406]
### Describe the problem

i treid to send a `ReadableStream` but i got this message `Invalid response from route /api/images/62c742cefb7c36c7c11bd9e8: body must be an instance of string or Uint8Array if content-type is not a supported textual content-type`

using
```
"@sveltejs/adapter-node": "^1.0.0-next.78",
"@sveltejs/kit": "^1.0.0-next.357"
```

my code was something like this
```js
const stream = /* get stream */
console.log(stream instanceof ReadableStream); // => true
```

### Describe the proposed solution

IDK?

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
whoops! The guard is a holdover from when we _didn't_ support streaming. Should be fixed by #5407

**Comment by AliBasicCoder** [comment]
> whoops! The guard is a holdover from when we _didn't_ support streaming. Should be fixed by #5407 

maybe this question is too early
But will this by fixed next release?

**Comment by Rich-Harris** [comment]
as soon as #5407 is merged (pending review by another maintainer) it will trigger a changesets PR; merging that will create a new release

**Comment by AliBasicCoder** [comment]
> as soon as #5407 is merged (pending review by another maintainer) it will trigger a changesets PR; merging that will create a new release

awesome
