### ISSUE TITLE
vite.define with typescript didn't work as expected

### ISSUE THREAD

**Issue by kamontat** [sveltejs/kit#5432]
### Describe the bug

When we define `vite.define` custon environment configuration and add global constants along with it.
Vscode works as expected, however on `eslint` cli it always return `'__VERSION__' is not defined  no-undef`.

### Reproduction

1. Create new sveltekit repository: `yarn create svelte my-app`
2. Answer question as following
    - Which Svelte app template? › Skeleton project
    - Add type checking with TypeScript? › Yes, using TypeScript syntax
    - Add ESLint for code linting? … Yes
    - Add Prettier for code formatting? … Yes
    - Add Playwright for browser testing? … Yes
4. Add below configuration to **vite.config.js**

```js
{
	"define": {
		"__VERSION__": JSON.stringify('v1.0.0')
	}
}
```

5. Add below code to **index.svelte**

```svelte
<script lang="ts">
	const version = __VERSION__ ?? 'version';
</script>
<h1>Welcome to SvelteKit ({version})</h1>
```

6. Create **env.d.ts** near **app.d.ts** on **src** directory
7. Add below code to **env.d.ts**

```typescript
declare const __VERSION__: string;
```

8. Run `yarn lint` or `npm run lint` and error will throw as below
```text
/my-app/src/routes/index.svelte
  2:18  error  '__VERSION__' is not defined  no-undef
```

I create example repository [here][repository] and also create Github Action usecase the result as well [here][github-action]

[repository]: https://github.com/kamontat/sveltekit-bug-5432
[github-action]: https://github.com/kamontat/sveltekit-bug-5432/actions/runs/2638055245

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 135.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.55
    @sveltejs/kit: next => 1.0.0-next.366
    svelte: ^3.44.0 => 3.49.0
    vite: ^2.9.13 => 2.9.14
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
eslint doesn't know about your vite config or your .d.ts files. you will have to fix that by adding `/*global __VERSION__*/` to the file that references that global, or add `"globals": { "__VERSION__": true }` to your eslint config
