### ISSUE TITLE
Add `vite.config.ts` to generated tsconfig `include`

### ISSUE THREAD

**Issue by tedbyron** [sveltejs/kit#5443]
### Describe the problem

vite supports using typescript for its config: <https://vitejs.dev/config/#config-intellisense>, but eslint + typescript will complain that `vite.config.ts` is not included in the current project

### Describe the proposed solution

if it exists, add `../vite.config.ts` to the `include` section of generated tsconfigs

### Alternatives considered

manually specify `"include": ["vite.config.ts", "src/**/*", "src/**/*.svelte"]` in tsconfig

### Importance

nice to have

### Additional Information

<img width="706" alt="image" src="https://user-images.githubusercontent.com/39110425/178093077-eedfbe40-e5df-42cc-8a20-fb52519c1e31.png">

**Comment by dummdidumm** [comment]
We do not generate a vite.config.ts, we generate a vite.config.js in the scaffolding script. So if you want to use a .ts file instead it's on you to adjust other files accordingly. It would be confusing for people to see a non existent file added to configs.

**Comment by dummdidumm** [comment]
Oh wait you mean the generated tsconfig

**Comment by gtm-nayan** [comment]
@tedbyron can you describe the steps you took to get to the screenshot?

For me,
`pnpm create svelte` (Pick typescript and eslint)

and then
```sh
pnpm i
pnpm run prepare
pnpm run format
pnpm run lint

```

the lint passes without any errors and I don't see any errors in the `vite.config.ts` files either.

**Comment by tedbyron** [comment]
@gtm-nayan default setup does not use type-aware linting, see <https://typescript-eslint.io/docs/linting/type-linting>

you have to specify `parserOptions.project` for `@typescript-eslint/parser` to use your tsconfig
