### ISSUE TITLE
mailto is broken with `goto` !

### ISSUE THREAD

**Issue by 416d72** [sveltejs/kit#5448]
### Describe the bug

`goto` doesn't work with `mailto://` protocol!!
I have this simple code:
```svelte
<script>
import {goto} from '$app/navigation';
</script>

<div on:click={() => goto('mailto://contact@example.com')}>Contact us</div>
```
But when I click on the div, I see this error in the console:
```js
Uncaught (in promise) TypeError: URL constructor: null//contact@example.com is not a valid URL.
```
For some reason `mailto:` gets replaced with `null` !

### Reproduction

I made a [stackblitz demo](https://stackblitz.com/edit/sveltejs-kit-template-default-gjosfe)

### Logs

```shell
Uncaught (in promise) TypeError: URL constructor: null//contact@example.com is not a valid URL.
```

### System Info

```shell
System:
OS: Linux 5.18 Manjaro Linux
CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
Memory: 1.02 GB / 7.71 GB
Container: Yes
Shell: 5.9 - /usr/bin/zsh
Binaries:
Node: 18.3.0 - /usr/bin/node
npm: 8.6.0 - /usr/bin/npm
Browsers:
Chromium: 103.0.5060.114
npmPackages:
@sveltejs/adapter-auto: 1.0.0-next.54 => 1.0.0-next.54
@sveltejs/kit: 1.0.0-next.361 => 1.0.0-next.361
svelte: ^3.49.0 => 3.49.0
vite: ^2.9.13 => 2.9.13
```

### Severity

serious, but I can work around it

### Additional Information

I need to use `goto` for a WebGL project where I can't use regular anchor links

**Comment by Conduitry** [comment]
You shouldn't use `//` in `mailto:` links, as I believe this will become part of the email address.

You can also just manually set `window.location` - I don't think there's a real benefit `goto` needs to handle things like this that aren't true URLs.

**Comment by 416d72** [comment]
>You can also just manually set window.location - I don't think there's a real benefit goto needs to handle things like this that aren't true URLs.

Thanks, I used `window.location.href` and it works well
