### ISSUE TITLE
`NODE_ENV` environment variable is `undefined` in `svelte.config.js` during during development (`npm run dev`)

### ISSUE THREAD

**Issue by kelvindecosta** [sveltejs/kit#5456]
### Describe the bug

When used in `svelte.config.js`, `process.env.NODE_ENV` is `undefined` during development (`npm run dev`).
It is expected to be `development`.

> This bug doesn't appear during production builds.
> In other words, `process.env.NODE_ENV` is `production`, which is the expected value.

### Reproduction

Reproduction on [StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-8grzce?file=svelte.config.js).

Please find the simple `console` statement that outputs the `process.env.NODE_ENV` value.

### System Info

```shell
System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
    Memory: 9.81 GB / 15.52 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Firefox: 100.0
  npmPackages:
    @sveltejs/adapter-vercel: next => 1.0.0-next.60 
    @sveltejs/kit: next => 1.0.0-next.367 
    svelte: ^3.48.0 => 3.48.0 
    vite: ^2.9.13 => 2.9.13
```

### Severity

annoyance

### Additional Information

AFAIK, this bug appeared after the addition of the `vite.config.js` file.

**Comment by Conduitry** [comment]
Per @bluwy, this looks like a bug in Vite. Checking for `'production'` vs `undefined` instead of `'production'` vs `'development'` sounds like a reasonable workaround for the time being.

**Comment by kelvindecosta** [comment]
@Conduitry, yes that makes perfect sense!

In that case do I close the issue?
