### ISSUE TITLE
Add ability to disable type module in package.json

### ISSUE THREAD

**Issue by NikolayMakhonin** [sveltejs/kit#5463]
### Describe the problem

I have a lot of problems using this function `"type": "module"`. I think this is still an experimental feature. For example, ts-node still [doesn't fully support esm](https://github.com/TypeStrong/ts-node/pull/1585), but I can't run it without esm as long as there is a `"type": "module"` in `package.json`.

I need the ts-node to run mocha tests inside the same project. And I do not think that this is the only problem that I will have to face in the development of my project.

If I disable the `"type": "module"` then I got this error:
```
C:\Users\Mika\AppData\Roaming\npm\pnpm.cmd run build

> svelte-kit@0.0.1 build D:\projects\-temp\svelte-kit\svelte-kit-template
> vite build

vite v2.9.13 building for production...
✓ 13 modules transformed.
.svelte-kit/output/client/_app/immutable/manifest.json                    1.14 KiB
.svelte-kit/output/client/_app/immutable/layout.svelte-c20868e3.js        0.53 KiB / gzip: 0.35 KiB 
.svelte-kit/output/client/_app/immutable/error.svelte-dab28125.js         1.56 KiB / gzip: 0.75 KiB 
.svelte-kit/output/client/_app/immutable/start-1ae51c64.js                23.04 KiB / gzip: 8.73 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-c3890ae1.js   0.80 KiB / gzip: 0.47 KiB 
.svelte-kit/output/client/_app/immutable/chunks/index-dd64db13.js         6.84 KiB / gzip: 2.79 KiB 
vite v2.9.13 building SSR bundle for production...
✓ 11 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                        1.09 KiB
.svelte-kit/output/server/index.js                             73.08 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js   0.24 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js    0.72 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js        0.32 KiB
.svelte-kit/output/server/chunks/index-9f6ceea8.js             2.31 KiB
.svelte-kit/output/server/chunks/hooks-1c45ba0b.js             0.00 KiB
(node:1912) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[vite-plugin-svelte-kit] Cannot use import statement outside a module

Process finished with exit code 0
```

`.svelte-kit/output/prerendered` is not generated
`.svelte-kit/output/client/_app/immutable/**/*.js` is not generated

But `Process finished with exit code 0` - this is fine

[see my repo to reproduce it](https://github.com/NikolayMakhonin/svelte-kit-template/tree/disable-type-module)

### Describe the proposed solution

I think the solution to this problem is simple - use the `.mjs` extension instead of `.js` where it necessary.

### Alternatives considered

The alternative is to wait indefinitely for a lot of popular modules to fully support esm so that I don't regularly stumble over unsolvable problems.

### Importance

i cannot use SvelteKit without it

**Comment by Conduitry** [comment]
`"type": "module"` only affects your code or the code that SvelteKit generates as part of your app. Anything in a dependency will be treated according to the value in its `package.json` (which defaults to CJS).

I don't know what the "a lot of popular modules" that don't support ESM that you're talking about are. It would just be modules that _act_ on your code (like ts-node), and not modules that are imported by your code.

**Comment by NikolayMakhonin** [comment]
OK, I understand, if imported modules are not affected, then only the problem with ts-node remains (for now).
The alternative is to fix the problem with ts-node or find a replacement for it.

**Comment by benmccann** [comment]
I would recommend Vitest over Mocha + `ts-node`. It will utilize your `vite.config.js` to support things like Vite aliases, is faster, nicer, etc.

**Comment by dominikg** [comment]
also you can use https://www.npmjs.com/package/tsx instead of ts-node

**Comment by benmccann** [comment]
Yeah, it should replace the need for Karma as well

I'm going to go ahead and close this given that it sounds like things are working for you at the moment
