### ISSUE TITLE
Dynamic Lazily imported component doesn't work in preview

### ISSUE THREAD

**Issue by PlopTheReal** [sveltejs/kit#5492]
### Describe the bug

I'm adding components dynamically based on IntersectionObserver ie when the component is in the browser view. 
`Lazy` component will load when necessary the component: 
```javascript
<Lazy
  componentName="./Thing"
  let:intersecting
  let:component
  >
  {#if intersecting}
	  <svelte:component this={component} />
  {/if}
</Lazy>
```
```javascript
// the interesting part from <Lazy>
...
 export let componentPath = "";
 const initialize = () => {
      observer = new IntersectionObserver(
          (entries) => {
              entries.forEach(async (_entry) => {
                  entry = _entry;

                  if (_entry.isIntersecting) {
                      component = (await import(`${componentPath}.svelte`)).default; 
                  }
                  intersecting = _entry.isIntersecting;
              });
          },
          { root, rootMargin, threshold }
      );
  };
...
```

In dev mode all is fine and components loads but not in preview (it loads an HTML instead of the component js).
I'm suspecting the path to the component isn't correct in preview mode.
Perhaps it's a matter of specifying a static path that will work in both dev and preview?
Unfortunatly `$lib` doesn't work.

### Reproduction

import a component via a function that takes the component path as a parameter such as 
```javascript 
export async function loadComp(path) {
    return  (await import(`${path}.svelte`)).default;
}
```
and run it in preview mode.

### System Info

```shell
@sveltejs/kit 1.0.0-next.370
@sveltejs/vite-plugin-svelte 1.0.0-next.49
vite 2.9.13
node v18.4.0
```

### Severity

blocking prod usage of SvelteKit

**Comment by f-elix** [comment]
This is probably due to the dynamic path you are using. 

Vite statically analyzes dynamic imports with these restrictions: https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations

This essentially means you only get to have one dynamic segment in your import path, and the path should be relative.

**Comment by PlopTheReal** [comment]
Thanks! I didn't knew that.
The problem I can see is if I specify a path like `./components/${name}.svelte` it works in `dev` but not in `preview`
Anything I'm missing there?

**Comment by Conduitry** [comment]
It works in dev because all of the files are there and are compiled on demand - while in your production build, everything's compiled ahead of time. I'm going to close this as working-as-intended.

**Comment by PlopTheReal** [comment]
Thanks for the quick feedback. My problem is that I haven't found a way to make this work in preview.
Any recommendation would be greatly appreciated.

**Comment by PlopTheReal** [comment]
Ok thanks @f-elix, I had more than `one dynamic segment` in the path.
