### ISSUE TITLE
Change html lang with adapter-static

### ISSUE THREAD

**Issue by YeungKC** [sveltejs/kit#5508]
### Describe the problem

I have make a [Blog](https://github.com/YeungKC/Hakuba/) using Svelte kit, it is data driven through Github discussions.

Case all data is via environment or Github discussion, you can set a default lang with env or config, and specific post set lang with post frontmatter.

I found a solution, but it is not compatible with adapter-static.
https://github.com/sveltejs/kit/issues/3091#issuecomment-1112589090

### Describe the proposed solution

Maybe provid like `<svelte:head>` a `<svelte:html>`?

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
I don't understand, is the language known at prerender time? If so, https://github.com/sveltejs/kit/issues/3091#issuecomment-1112589090 will indeed work. If not, and the content is being injected with JavaScript (not recommended!) then you can set the `lang` attribute at the same time:

```js
document.documentElement.lang = lang
```

**Comment by YeungKC** [comment]
> I don't understand, is the language known at prerender time? If so, https://github.com/sveltejs/kit/issues/3091#issuecomment-1112589090 will indeed work. If not, and the content is being injected with JavaScript (not recommended!) then you can set the `lang` attribute at the same time:
> 
> 
> 
> ```js
> 
> document.documentElement.lang = lang
> 
> ```

I think I know why, because I miswrite hooks into hooks…
