### ISSUE TITLE
'The following Vite config options will be overridden by SvelteKit' message is hidden

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#5540]
### Describe the bug

If you set a value in `vite.config.js` that SvelteKit needs to control, like `base`, a message is printed:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1162160/179115563-57ca11ab-6318-4263-bf40-1b2fb8427283.png">

I had to add `clearScreen: false` to the Vite config to take that screenshot, because normally the message is immediately hidden by Vite's welcome message. Not sure if there's a way to either preserve the message or print it immediately after the welcome message?

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-pmx9s3?file=vite.config.js&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.60 
    @sveltejs/kit: next => 1.0.0-next.373 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.0
```

### Severity

annoyance

**Comment by bluwy** [comment]
It can be printed after the welcome message by listening for Vite's http server start, and log after a `setTimeout`. Me and dominik did [this](https://github.com/svitejs/vite-plugin-qrcode/blob/9ecb49cfc5cbaa80432bdd85886e41f901abe5ef/packages/vite-plugin-qrcode/src/index.ts#L10-L25) for printing qrcode's after the welcome message.
