### ISSUE TITLE
Stream file does not seem to work.

### ISSUE THREAD

**Issue by half-metal** [sveltejs/kit#5561]
### Describe the bug

Unable to return a fs.createReadStream from an endpoint. There are plenty of examples for fetching a file from URL, and sending as stream, but sometimes a log file or file located on machine needs to be sent.

### Reproduction

When attempting to return a fs.createReadStream via endpoint like so:
```
readStream = await fs.createReadStream(file) 
                     return {
                         
                         body:readStream,
                         headers: responseHeaders
                         };
```

an error results:
```
Node streams are no longer supported — use a ReadableStream instead
Error: Node streams are no longer supported — use a ReadableStream instead
```

These issues below relate in they attempt to stream or talk about documentation for examples missing, but do not talk about an opened file and how to actually send the file via a stream, for example a giant 1GB file:
https://github.com/sveltejs/kit/issues/5344
https://github.com/sveltejs/kit/issues/5412
https://stackoverflow.com/questions/72894078/sveltekit-node-streams-are-no-longer-supported

### Logs

```shell
Postman call to endpoint results in error above.
```

### System Info

```shell
Chrome
Node v18.2.0
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"autoprefixer": "^10.4.7",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.14",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.1.6",
		"vite": "^3.0.0"
	},
```

### Severity

annoyance

### Additional Information

Maybe there is an alternative way to do this. But I don't see any examples how to natively pipe this to a response in Sveltekit like you would in Express
I returned a readableStream but the response is essentially the stream and not the contents
![image](https://user-images.githubusercontent.com/58837299/179317877-a302f9cb-40dc-439b-a782-cd5988dd8e2e.png)

**Comment by repsac-by** [comment]
```js
import { Readable } from 'node:stream';
...
return {
    body: Readable.toWeb(readStream),
};
```

**Comment by AliBasicCoder** [comment]
you just have to use web stream not node's

here is code that will help you (remove type antotions if you aren't using TS)

```ts
// converts web stream to node
export function readStreamToReadable(readStream: ReadableStream) {
  const result = new Readable({ read() {} });
  const reader = readStream.getReader();
  function push() {
    reader.read().then(({ done, value }) => {
      if (done) {
        return result.push(null);
      }
      result.push(value);
      push();
    });
  }
  push();
  return result;
}

// converts node stream to web
export function readableToReadStream(
  readable: Readable
): ReadableStream<Uint8Array> {
  return new ReadableStream({
    start(controller) {
      readable.addListener("data", (chunk: Buffer) => {
        controller.enqueue(new Uint8Array(chunk));
      });
      readable.addListener("end", () => {
        controller.close();
      });
      readable.addListener("error", (err) => {
        controller.error(err);
      });
    },
  });
}
```

**Comment by Conduitry** [comment]
As noted above, Node's streams are different from the newer web stream standard. https://nodejs.org/dist/latest-v18.x/docs/api/stream.html#streamreadabletowebstreamreadable is how to convert them if you're on a new enough version of Node (which by your system info it looks like you are), otherwise you will need to do it manually.

**Comment by half-metal** [comment]
Yes! @repsac-by  that works, thanks for showing how to do the return with `Readable.toWeb`
Looking through the web stream standard @Conduitry, I'm not sure how anyone is to figure out that toWeb would ever solve anything
<img width="789" alt="Screen Shot 2022-07-16 at 11 45 47 AM" src="https://user-images.githubusercontent.com/58837299/179368203-0706336a-2efe-46cb-8a1a-1c28d8e5fd38.png">

Many parts of the Node documentation on streams is confusing. Would be nice if they did a section on "modern" way to use streams and for the various common use cases. Their examples are limited, and a bit all over the place.

@AliBasicCoder  yes that looks like it would work too, and that is what I was doing, except I was confused how you open a file that is stored locally, and then send that without more code. I'm still not sure where on the readableToReadStream you pull in that fs opened file, but I'll play around with that eventually. For now, the solution from @repsac-by will work for what I need.

**Comment by half-metal** [comment]
Adding some info after migration ended up breaking the solution above and migration suggestion (which I left in the code snippet below) didn't work as expected. Now with Sveltekit, we do not need to use Readable.toWeb(readStream) and can merely pass the readStream like so

```
                     const file = `${filePath}/${fileName}`
                     //const readStream = fsb(file, {block:chunkSize, start:readEnd, end:readStart})
                     const fd = await fsp.open(file)
                     const readStream = fd.createReadStream()
                     console.log('Size of file:',stats.size,'totalChunkCount:',chunkCount,'readStart:',readStart,'chunksReturned:',chunksReturned, 'pageNumber:', pageNumber)
                           let cnt = 0 //value to track chunks
                           const reverseLineStream = new Transform({
                               transform (chunk, encoding, next) {
                                   const reversedChunk = (chunk.toString().split('\n').filter((logContents) => logContents.includes(searchFilter))).reverse().join('\n');
                                   cnt++
                                       this.push(reversedChunk);
                                   next();
                               }
                           });
                          readStream.pipe(reverseLineStream).on('finish', () => {
                            console.log(`Finished reversing the contents of ${file} and piping the output to the response. ${cnt} chunks.`);
                        });
                 
                     //throw new Error("@migration task: Migrate this return statement (https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3292701)");
                     // Suggestion (check for correctness before using):
                     // return new Response(Readable.toWeb(readStream), { headers: responseHeaders });
                    //  return {
                    //      body:Readable.toWeb(readStream),
                    //      headers: responseHeaders
                    //      };
                    return new Response(readStream, { headers: responseHeaders });

                 }
```
