### ISSUE TITLE
Double inserting the same css

### ISSUE THREAD

**Issue by polRk** [sveltejs/kit#5580]
### Describe the bug

I result page I can see 2 style tags tie the same content

### Reproduction

1. Create a project form template. 
2. Add postcss and tailwinds.
3. import in src/__layout.svelte any .css files

<img width="246" alt="Снимок экрана 2022-07-17 в 14 21 25" src="https://user-images.githubusercontent.com/39828645/179395784-179c9885-b699-45fe-8a35-dfaee5c1f1d7.png">

### System Info

```shell
System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 144.28 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.3.0 - ~/.nvm/versions/node/v18.3.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v18.3.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 14.1
  npmPackages:
    vite: 3.0.0 => 3.0.0
```

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
From the bug template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be short, self-contained and correct and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

It is _much_ more likely we will look at this if you provide a repro.

**Comment by tcc-sejohnson** [comment]
@polRk 

Can you provide a repro, or have you solved the issue on your end? If you have solved the issue on your end, please respond with the solution in case future users encounter it and Google it. 🙂

**Comment by tcc-sejohnson** [comment]
Given that we haven't seen any activity for five days, I'm going to assume you've fixed this on your end or moved on. If not, feel free to open a new issue with a repro. Thanks!
