### ISSUE TITLE
Docker Environment Variables not fetched by Svelte

### ISSUE THREAD

**Issue by thinkrapido** [sveltejs/kit#5589]
### Describe the bug

svelte build works fine when starting from command line with environment variable, but when placed in a docker container it can't fetch the environment variable

### Reproduction

const region = import.meta.env.VITE_REGION || process.env['REGION'] || 'None'

gets the appropriate REGION variable

In docker container it's always None

File is index.svelte of demo counter

### System Info

```shell
System:
    OS: Linux 5.15 NixOS 22.11 (Raccoon) 22.11 (Raccoon)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 23.01 GB / 31.32 GB
    Container: Yes
    Shell: 5.1.16 - /nix/store/pxfxgmas6iyqb6dq7d7d7kvv1vld4r89-bash-interactive-5.1-p16/bin/bash
  Binaries:
    Node: 18.3.0 - /nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/bin/node
    Yarn: 1.22.18 - /nix/store/8lajm4glg9v9f7lzpz4r4gm02rqwgnkl-yarn-1.22.18/bin/yarn
    npm: 8.11.0 - /nix/store/njq5flksyp6aplbp1r1gqpvajch7fyrb-nodejs-18.3.0/bin/npm
  Browsers:
    Firefox: 101.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.57 
    @sveltejs/adapter-node: ^1.0.0-next.81 => 1.0.0-next.81 
    @sveltejs/kit: next => 1.0.0-next.371 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^2.9.13 => 2.9.14
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
Environment variables aren't automatically carried from the host system into Docker containers.

If that's not all that's happening, please provide a proper (complete, minimal) reproduction.

**Comment by thinkrapido** [comment]
When I'm using following code snippet instead of sveltekit, it works fine.

```js
const Koa = require('koa');
const app = new Koa();

app.use(async ctx => {
  ctx.body = 'Hello World, from ' + (process.env['REGION'] || 'the world') + '!';
});

app.listen(3000);
```

But when I use this here:

```js
const region = import.meta.env.VITE_REGION || process.env['REGION'] || 'None'
```
the environment variable is not getting picked up inside the container.

When I don't use docker and run sveltekit on, the env variable gets picked up.
