### ISSUE TITLE
Build fails after upgrading to vite > 2.9.0

### ISSUE THREAD

**Issue by lmtr0** [sveltejs/kit#5600]
### Describe the bug

It's expect to build the project when, in  a dependency, I export a svelte component, and then import that component. However the build fails with this error: 
```
500

Unknown file extension ".svelte" for /home/projects/vitejs-vite-14hxgx/node_modules/@higenku/theme/src/footer/Footer.svelte

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /home/projects/vitejs-vite-14hxgx/node_modules/@higenku/theme/src/footer/Footer.svelte
    at get (https://vitejs-vite-14hxgx.w-corp.staticblitz.com/blitz.9dc2007b053e3e7ca4daf0ec1a74b5c3910935fe.js:6:292488)
    at instantiateModule (file:///home/projects/vitejs-vite-14hxgx/node_modules/vite/dist/node/chunks/dep-1513d487.js:50382:13)
    at <anonymous> (<anonymous>)
```
You can check it yourself [here](https://stackblitz.com/edit/sveltekiterror)

[this should have fixed the problem](https://github.com/sveltejs/kit/issues/5549), however It hasn't

### Reproduction

Open https://stackblitz.com/edit/sveltekiterror and see the error yourself

1. install the next version of my theme `@higenku/theme@0.6.6-next` other versions work because you have to import the components yourself.
2. Import a component (I only exported the footer ones to test the vite 3 update) 
```js
<script lang="ts">
import {Footer} from "@higenku/theme"
</script>
```

### Logs

```shell
Unknown file extension ".svelte" for /home/projects/sveltekiterror/node_modules/@higenku/theme/src/footer/Footer.svelte
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /home/projects/sveltekiterror/node_modules/@higenku/theme/src/footer/Footer.svelte
    at get (https://sveltekiterror.w-corp.staticblitz.com/blitz.9dc2007b053e3e7ca4daf0ec1a74b5c3910935fe.js:6:292488)
    at instantiateModule (file:///home/projects/sveltekiterror/node_modules/vite/dist/node/chunks/dep-1513d487.js:50382:13)
```

### System Info

```shell
System:
    OS: Linux 5.15 undefined
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.41 GB / 15.36 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Chromium: 103.0.5060.114
    Firefox: 102.0.1
```

### Severity

blocking an upgrade

**Comment by dominikg** [comment]
This appears to be a packaging issue with the library you mention `@higenku/theme`  

Looking at the content of node_modules/@higenku/theme/package.json it seems like there is no "svelte" field that helps to resolve imports of svelte sources.

Adding `"svelte":"src/index.js"` to that and restarting the dev server fixes the problem for me.

I highly recommend you check out `svelte-kit package`  https://kit.svelte.dev/docs/packaging  . Even though it is still in beta, it makes it a lot easier to release svelte libraries.

**Comment by lmtr0** [comment]
I'm Investigating, but it seems to work better

**Comment by dominikg** [comment]
Thi tracker is not used for support/setup questions. It looks like this isn't a bug in kit.

Please open a [discussion](https://github.com/sveltejs/kit/discussions) or ask for help in [discord](https://svelte.dev/chat) (#svelte-kit) to get this resolved.

**Comment by lmtr0** [comment]
I don't know how or why, but I started the project all over again and it worked
