### ISSUE TITLE
kit: page store does not update when navigating to the same page with a query parameter

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#562]
**Describe the bug**
When navigating to the same page with a query parameter (e.g. from `/` to `/?lang=jp`) the page store from `$app/stores` does not update. Navigating either by `<a>` tag or by `goto()` has the same result.

**To Reproduce**
```bash
npm init svelte@next
# js-only and css
npm install
npm run dev
```
Replace `index.svelte` with the following:
```svelte
<script>
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
</script>

<h3>Key-Values:</h3>
{#each Array.from($page.query) as [key, value]}
	<p>{key}: {value}</p>
{/each}
<pre>Query: {$page.query.toString()}</pre>

{#if $page.query.get('lang') === 'jp'}
	<h1>こんにちは</h1>
{:else}
	<h1>Hello World!</h1>
{/if}

<button on:click={() => goto('/?lang=jp')}>Goto</button>

<a href="/?lang=jp">Anchor Tag</a>
```
Click either the button or the anchor tag to see a lack of update. Refresh the page to see the actual update.

**Expected behavior**
That the page store is updated without refreshing the page. e.g. Hello World to change to こんにちは.

**Information about your SvelteKit Installation:**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 18.32 GB / 31.95 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.50)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.49
    svelte: ^3.29.0 => 3.35.0
```

**Severity**
You could use `rel=external` to force the page load, but that's janky and not necessarily appropriate for all use cases.

**Comment by Conduitry** [comment]
I think the problem is at https://github.com/sveltejs/kit/blob/0512fd1c7e27ef7452197d8fc044068e064b63a5/packages/kit/src/runtime/client/renderer.js#L433 and that we also need to be checking whether the query changed. I'm not sure why we're not using the `changed.*` values that we're computed above.

**Comment by Conduitry** [comment]
Oh, there _is_ no `changed.path`. But adding ` || changed.query` to that `if` does seem to fix this in my brief manual tests, and it doesn't break any of our other automated tests.

**Comment by Conduitry** [comment]
I was looking to add a new test for this, and I'm not sure why the tests in https://github.com/sveltejs/kit/blob/c895e4377872fc5f465116bdbce3c730e984a62c/packages/kit/test/apps/basics/src/routes/query/__tests__.js aren't already catching this.

**Comment by Rich-Harris** [comment]
they're not testing client-side navigation, only full reloads
