### ISSUE TITLE
Add documentation to config types

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#5626]
### Describe the problem

The configuration is documented at https://kit.svelte.dev/docs/configuration. It would be nice if the descriptions of each option lived with the types themselves... https://github.com/sveltejs/kit/blob/850528dd80d89640916764177445e7b5efd06403/packages/kit/types/index.d.ts#L85-L149 ...so that they were exposed inside editors, etc

### Describe the proposed solution

Move the descriptions to `types`, and ('draw the rest of the owl') generate the documentation from them. It might be tricky to get things appropriately grouped, but I have faith in our ingenuity.

### Alternatives considered

Leaving things as they are

### Importance

nice to have

**Comment by dummdidumm** [comment]
We did this
