### ISSUE TITLE
[bug] assets are not being prerendered

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#5630]
### Describe the bug

Rich said pages go to `.svelte-kit/output/prerendered/pages` and assets should go to `.svelte-kit/output/prerendered/assets`. However, I have no `.svelte-kit/output/prerendered/assets` directory

It looks to me like assets are being crawled and enqueued, but not visited. I think this is because `files` is passed in, if something is in `files` it is skipped, but we never write `files`

### Reproduction

I'm assuming this happens to all apps, but if that's not true I can put together a reproduction

### System Info

```shell
npmPackages:
    @sveltejs/adapter-netlify: next => 1.0.0-next.70 
    @sveltejs/kit: next => 1.0.0-next.382 
    svelte: ^3.48.0 => 3.49.0 
    vite: ^3.0.2 => 3.0.2
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
I misspoke earlier when I said `prerendered/assets`. Assets that are dynamically generated are placed in `prerendered/pages`, and dependencies (think `__data.json`) go in `prerendered/dependencies`, but files that already live in `static` are just left there. There's no reason to copy them somewhere else (until the adapt phase happens).

Are you sure this is a bug? Seems like the desired behaviour to me
