### ISSUE TITLE
`adapter-cloudflare`: SVGs from `static` folder stopped working

### ISSUE THREAD

**Issue by allozaur** [sveltejs/kit#5652]
### Describe the bug

After updating to `1.0.0-next.63` Cloudflare stopped loading SVGs from `static` folder and started displaying some XML error.

![Zrzut ekranu 2022-07-21 o 13 52 41](https://user-images.githubusercontent.com/37627284/180207498-237cdbce-627b-453a-ba78-e55d1e9344d9.png)

### Reproduction

Update package to `/@sveltejs/adapter-auto/1.0.0-next.63` which has `'@sveltejs/adapter-cloudflare': 1.0.0-next.29` and deploy app to Cloudflare Pages using `adapter-auto`.

### System Info

```shell
Cloudflare Pages Environment
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
This...

> Update package to `/@sveltejs/adapter-auto/1.0.0-next.63` which has `'@sveltejs/adapter-cloudflare': 1.0.0-next.29` and deploy app to Cloudflare Pages using `adapter-auto`.

...is not a reproduction

**Comment by benmccann** [comment]
Did you also update `@sveltejs/kit` at the same time? Because I'm guessing that's more likely to be where the issue is

**Comment by nosovk** [comment]
Actually I have the same issue: any static assets are not copied to the resulting Cloudflare bundle from `"@sveltejs/adapter-cloudflare": "1.0.0-next.30"`
All was okay at "1.0.0-next.29", currently just pinned it in deps

**Comment by benmccann** [comment]
Did you also update SvelteKit to the latest version?

A reproduction would help

**Comment by nosovk** [comment]
https://github.com/nosovk/cf-broken-assets-repro
here is a reproduction
<img width="227" alt="image" src="https://user-images.githubusercontent.com/1398808/180312084-b6d02d6c-c158-4101-bfb4-ef906afc4c1d.png">

**Comment by benmccann** [comment]
@nosovk in your project you updated only adapter-cloudflare and not SvelteKit itself, which is why it's not working for you. You need to update them at the same time

Change the Vite version to `^3.0.0` in `package.json` and run `rm -rf node_modules/ package-lock.json && npm install`
