### ISSUE TITLE
Static Adapter not generating index.html with proper script links for GH-pages deploy

### ISSUE THREAD

**Issue by tmallz** [sveltejs/kit#5668]
### Describe the bug

I have been trying to get a portfolio using svelte to deploy to GH-pages and no matter what configuration I use in the adapter I can't get it to load the .js files on the deployed site post build. The index.html generated in the build has /_app/immutable/{generatedfile}.js as failing to load. 

### Reproduction

I was able to reproduce the bug with a skeleton svelte app that I added two dummy pages and only the dependencies needed to use the static adapter. I am seeing the same results. See screenshots below:

index.html generated from build
![image](https://user-images.githubusercontent.com/61262154/180364194-d07fb885-4a9f-44b1-aac3-39073db52b15.png)

svelte.config.js
![image](https://user-images.githubusercontent.com/61262154/180364119-687b8963-47f7-4cd8-90ce-ccb7da5c9347.png)

console on github pages with  js files failing to load
![image](https://user-images.githubusercontent.com/61262154/180364074-d2f72287-25e9-4140-b5eb-9796014b5b53.png)

### Logs

```shell
Logs from the build and deploy

$ npm run deploy

> gh-pages-issue-recreation@0.0.1 deploy
> npm run build && npx gh-pages -d ./build -t true


> gh-pages-issue-recreation@0.0.1 build
> rm -rf build && vite build && touch ./build/.nojekyll

(node:16408) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
vite v3.0.2 building for production...
transforming...
✓ 15 modules transformed.
rendering chunks...
.svelte-kit/output/client/manifest.json                                     1.74 KiB
.svelte-kit/output/client/_app/immutable/layout.svelte-9147df0b.js          0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-7d1ddec6.js           1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-ba0114b5.js     0.80 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/lib/nav.svelte-ad49efb2.js   0.81 KiB / gzip: 0.44 KiB
.svelte-kit/output/client/_app/immutable/start-cd7304e7.js                  24.22 KiB / gzip: 9.04 KiB
.svelte-kit/output/client/_app/immutable/pages/page.svelte-f5bdb174.js      0.62 KiB / gzip: 0.40 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-03969575.js           6.85 KiB / gzip: 2.80 KiB
vite v3.0.2 building SSR bundle for production...
transforming...
✓ 13 modules transformed.
Generated an empty chunk: "hooks"
rendering chunks...
.svelte-kit/output/server/manifest.json                             1.50 KiB
.svelte-kit/output/server/index.js                                  76.23 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js        0.25 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js         0.74 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js             0.34 KiB
.svelte-kit/output/server/entries/pages/lib/nav.svelte.js           0.32 KiB
.svelte-kit/output/server/entries/pages/page.svelte.js              0.26 KiB
.svelte-kit/output/server/_app/immutable/chunks/index-3e01a4ca.js   2.61 KiB
.svelte-kit/output/server/_app/immutable/chunks/hooks-bced8853.js   0.00 KiB
(node:16408) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
Published
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.62 GB / 7.81 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.114
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.63
    @sveltejs/adapter-static: ^1.0.0-next.38 => 1.0.0-next.38
    @sveltejs/kit: next => 1.0.0-next.390
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.2
```

### Severity

blocking all usage of SvelteKit

**Comment by dominikg** [comment]
Hi, please post a link to the repo with your reproduction. Also make sure that the .nojekyll file is added correctly. It has to be present in the gh-pages branch root iirc

**Comment by tmallz** [comment]
Yes everything I read says you need a .nojekylll, I believe I have it being added in the build step. Can't believe I forgot to link the repo. Here is the link to the reproduction: [https://github.com/tmallz/SPA-build-not-adding-repo-name](url)

**Comment by dominikg** [comment]
The deployed site is here https://tmallz.github.io/SPA-build-not-adding-repo-name/

initial html response:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="./favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta http-equiv="content-security-policy" content="">
	<link rel="modulepreload" href="/_app/immutable/start-cd7304e7.js">
	<link rel="modulepreload" href="/_app/immutable/chunks/index-03969575.js">
	</head>
	<body>
		<div>
		<script type="module" data-sveltekit-hydrate="45h">
		import { start } from "/_app/immutable/start-cd7304e7.js";
		start({
			target: document.querySelector('[data-sveltekit-hydrate="45h"]').parentNode,
			paths: {"base":"","assets":""},
			session: {},
			route: true,
			spa: true,
			trailing_slash: "never",
			hydrate: null
		});
	</script></div>
	</body>
</html>
```

it looks like base is not configured correctly, it requests https://tmallz.github.io/_app/immutable/start-cd7304e7.js but the file is at https://tmallz.github.io/SPA-build-not-adding-repo-name/_app/immutable/start-cd7304e7.js

have you validated that `process.env.NODE_ENV` is set to production ? 
There's also https://vitejs.dev/config/shared-options.html#base (should be correctly configured by sveltekit but if not that may play a role)

**Comment by frederikhors** [comment]
`process.env.NODE_ENV` is not set I think. I'm having the same issue with `workbox` and `service-worker.ts`.

And I upgraded Kit and Vite from 2.9 to 3 today.

**Comment by tmallz** [comment]
So it's always building and deploying as if process.env.NODE_ENV is development and not production? I took out the dev part from the paths line and still had the issue. See screenshot below. Do I need to manually set it to prod at this point?

![image](https://user-images.githubusercontent.com/61262154/180567187-4d82f15d-dcfd-4f05-b1fd-1fc25d982082.png)

**Comment by frederikhors** [comment]
Sincerely I don't know. I think we should avoid to put that replacements in config files since it is so common to replace NODE_ENV...

**Comment by frederikhors** [comment]
I opened https://github.com/sveltejs/kit/issues/5682.

**Comment by tmallz** [comment]
I added a console log to verify that the build is indeed running in production mode, and it is. (See logs below) I am still seeing the reference errors in my Index.html. Is the response in the issue opened above addressing this issue? That is my understanding.

$ npm run deploy

> gh-pages-issue-recreation@0.0.1 deploy
> npm run build && npx gh-pages -d ./build -t true


> gh-pages-issue-recreation@0.0.1 build
> rm -rf build && vite build && touch ./build/.nojekyll

(node:9112) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
NODE_ENV:  production
NODE_ENV:  production
vite v3.0.2 building for production...
transforming...
✓ 15 modules transformed.
rendering chunks...
.svelte-kit/output/client/manifest.json                                     1.74 KiB
.svelte-kit/output/client/_app/immutable/layout.svelte-9147df0b.js          0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-7d1ddec6.js           1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-ba0114b5.js     0.80 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/pages/lib/nav.svelte-ad49efb2.js   0.81 KiB / gzip: 0.44 KiB
.svelte-kit/output/client/_app/immutable/start-4928de1a.js                  24.22 KiB / gzip: 9.04 KiB
.svelte-kit/output/client/_app/immutable/pages/page.svelte-f5bdb174.js      0.62 KiB / gzip: 0.40 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-03969575.js           6.85 KiB / gzip: 2.80 KiB
vite v3.0.2 building SSR bundle for production...
transforming...
✓ 13 modules transformed.
Generated an empty chunk: "hooks"
rendering chunks...
.svelte-kit/output/server/manifest.json                             1.50 KiB
.svelte-kit/output/server/index.js                                  76.23 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js        0.25 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js         0.74 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js             0.34 KiB
.svelte-kit/output/server/entries/pages/lib/nav.svelte.js           0.32 KiB
.svelte-kit/output/server/entries/pages/page.svelte.js              0.26 KiB
.svelte-kit/output/server/_app/immutable/chunks/index-3e01a4ca.js   2.61 KiB
.svelte-kit/output/server/_app/immutable/chunks/hooks-bced8853.js   0.00 KiB
(node:9112) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time

Run npm run preview to preview your production build locally.

> Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
Published

**Comment by p-jeff** [comment]
Hey, I ran into the same issue, until I noticed that `paths` is a property of `kit`, not `config`.

So instead of 
```
config={
kit{},
paths{}
}
```

it has to be 
```
config={
kit{ paths{} }
};
```

in your exact case it would be 
```
const config = {
  kit: {
    adapter: adapter({
      pages: 'build',
      assets: 'build',
      fallback: 'index.html',
      trailingSlash: 'always',
      precompress: true,
    }),
    paths: {
      base: dev ? '' : '/SPA-build-not-adding-repo-name',
    },
  }
};
```


Check out [my fork ](https://github.com/p-jeff/SPA-build-not-adding-repo-name)of your repo, as you can see files in /build have the correct paths and the [working hosted site](https://p-jeff.github.io/SPA-build-not-adding-repo-name)

**Comment by tmallz** [comment]
> Hey, I ran into the same issue, until I noticed that `paths` is a property of `kit`, not `config`.
> 
> So instead of
> 
> ```
> config={
> kit{},
> paths{}
> }
> ```
> 
> it has to be
> 
> ```
> config={
> kit{ paths{} }
> };
> ```
> 
> in your exact case it would be
> 
> ```
> const config = {
>   kit: {
>     adapter: adapter({
>       pages: 'build',
>       assets: 'build',
>       fallback: 'index.html',
>       trailingSlash: 'always',
>       precompress: true,
>     }),
>     paths: {
>       base: dev ? '' : '/SPA-build-not-adding-repo-name',
>     },
>   }
> };
> ```
> 
> Check out [my fork ](https://github.com/p-jeff/SPA-build-not-adding-repo-name)of your repo, as you can see files in /build have the correct paths and the [working hosted site](https://p-jeff.github.io/SPA-build-not-adding-repo-name)

This sovled the issue for me. Thank you @p-jeff! I will close this issue now
