### ISSUE TITLE
sourcing `js` file from static folder breaks on `1.0.0-next.390`

### ISSUE THREAD

**Issue by bhvngt** [sveltejs/kit#5672]
### Describe the bug

After upgrading to the latest sveltekit version (1.0.0-next.390), I am not able to source `js` file from the static folder. Infact, it breaks for even css files. I believe this is due to #5648. Not sure, if there is any configuration that needs to be changed to make it work.

I am sourcing it by adding following code inside `app.html` head tag.

```
<script src="%sveltekit.assets%/sample.js"></script>
```

### Reproduction

[Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-5jzsnx?file=static%2Fsample.js,package.json,src%2Fapp.html&terminal=dev)

### Logs

```shell
Failed to load url /sample.js (resolved id: /sample.js). This file is in /public and will be copied as-is during build without going through the plugin transforms, and therefore should not be imported from source code. It can only be referenced via HTML tags.
    at loadAndTransform (file:///home/projects/sveltejs-kit-template-default-5jzsnx/node_modules/vite/dist/node/chunks/dep-1513d487.js:39810:19
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.63 
    @sveltejs/kit: 1.0.0-next.390 => 1.0.0-next.390 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.2
```

### Severity

blocking an upgrade

**Comment by wickning1** [comment]
I'm getting this same error message with the global.css file after upgrading sveltekit and creating my vite.config.js for the first time. I'm not referencing it anywhere except the app.html.

**Comment by homerjam** [comment]
I'm also experiencing this...
```html
<!-- app.html -->
...
<link rel="stylesheet" href="/fonts/fonts.css" />
...
```

<img width="921" alt="Screenshot 2022-07-22 at 16 54 23" src="https://user-images.githubusercontent.com/1055769/180478029-d3d87920-d6f3-4d0d-a45f-a6f9bfaa250e.png">

**Comment by kuchaguangjie** [comment]
vite 3 use `/public` for static asset by default, is that relevant? It also break my code, my temp solution is:
https://github.com/hperrin/svelte-material-ui/issues/489#issuecomment-1192305792

**Comment by Ncookiez** [comment]
Also breaking on my end (css file in static folder).

**Comment by hperrin** [comment]
I can confirm that this also happens when you use `<link href="{assets}/somefile.css" />` in a `<svelte:head>`.

**Comment by TerranceLuke** [comment]
Having the exact same issue and it's blocking an upgrade.

**Comment by Arstman** [comment]
same issue happened here, i upload to s3 and use outlink to get rid of this annoying message, hope this can be fixed soon.

**Comment by ball6847** [comment]
From my testing, this bug starts happening since `1.0.0-next.387`, we need to pin `@sveltejs/kit` version to `1.0.0-next.386` to keep the project running.

**Comment by Rich-Harris** [comment]
Sorry about this everyone. I've undone the bad PR, and this should now be fixed.

**Comment by michal-kapala** [comment]
I still have had this issue with `1.0.0-next.391`, updating sveltekit to 392 resolved it.
