### ISSUE TITLE
Service-Worker messages

### ISSUE THREAD

**Issue by mawoka-myblock** [sveltejs/kit#5676]
### Describe the problem

I want to send messages from my svelte-code to the service-worker, but for that, I would need access to the service-worker object. I asked on reddit and searched in the docs, but found no way to access the service-worker object.

In short: I want to communicate with the service-worker from my svelte-pages.

### Describe the proposed solution

I've got 2 ideas:

- Import the service-worker object
- Make a store to communicate with the service worker

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
Does this help?

https://kit.svelte.dev/docs/service-workers

Can you just import it from `src/service-worker.{js|ts}`?

**Comment by mawoka-myblock** [comment]
I could try that, but I've got the following line in `src/service-worker.ts`

```ts
export const worker = self as unknown as ServiceWorkerGlobalScope;
```
but I can't build it, because it complains that `self` is not defined, if I import it (eg. in `index.svelte`)

---
If I import it onMount asynchronously, `const worker = import("../service-worker")`, in the build, it loads the file from `_app/chunks/xxx_service-worker.ts`, not from `/service-worker.js`.

no the other hand, if I import it with `const worker = import("/service-worker.js")`, it won't build, because it can't find the file.

**Comment by tcc-sejohnson** [comment]
You should import it from whatever the path is at build time (so I'd imagine `../service-worker.js` is correct). What is `self`? Do you mean `this`?

**Comment by mawoka-myblock** [comment]
My service-worker now looks like this:
```js
this.onMessage((message) => {
	console.log(message, "from service-worker")
})
```
And `this.onMessage` is not a function.

**Comment by Rich-Harris** [comment]
You can't import the service worker as a module; it's running in a different process. Even if it was importable, the imported module _wouldn't be your service worker_, it would just be a module with the same contents.

You have to get hold of the service worker registration via `navigator.serviceWorker.controller` then communicate with it via `postMessage`. This article covers it well: https://felixgerschau.com/how-to-communicate-with-service-workers/

Closing as this isn't a SvelteKit issue.
