### ISSUE TITLE
Localhost page is not found and Sveltekit hot reloading doesn't work

### ISSUE THREAD

**Issue by nelson-111** [sveltejs/kit#5679]
## Localhost page is not found (Svelte)
When I was creating a simple project for my portafolio (with the Vite Svelte template), I tried to go to page, but it appears me with the "page not found" error, I checked the localhost numbers if they were correct, and yes, they were. 
## Sveltekit hot reloading don't work
After the before error, I decided to create the project in Sveltekit, all worked well, until I notice the hot reloading didn't work, but it wasn't a problem to the project. 

Tell me if these errors happen to you or only to me.

### Reproduction

The project is the following: https://github.com/nelson-111/magic-navbar-clone-with-tailwind

### System Info

```shell
System:
OS: Windows 10 10.0.19044
CPU: (4) x64 AMD A10-9620P RADEON R5, 10 COMPUTE CORES 4C+6G
Memory: 3.54 GB / 6.95 GB

Binaries:
Node: 18.3.0 - C:\ Program Files\nodejs\node.EXE
npm: 8.12.1 - C:\ Program Files\nodejs\node.CMD

Browsers:
Chrome: 103.0.5060.134
Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.43)

npmPackages:
svelte: ^3.44.0 => 3.49.0
```

### Severity

annoyance

**Comment by bluwy** [comment]
> When I was creating a simple project for my portafolio (with the Vite Svelte template), I tried to go to page, but it appears me with the "page not found" error

If this is already happening for a non-SvelteKit project, then it's likely something up with Vite or your machine. Maybe it's serving under http://127.0.0.1:5173/ or http://[::1]:5173/ instead of http://localhost:5173/ ?

The repro is working fine for me.

**Comment by nelson-111** [comment]
> > When I was creating a simple project for my portafolio (with the Vite Svelte template), I tried to go to page, but it appears me with the "page not found" error
> 
> If this is already happening for a non-SvelteKit project, then it's likely something up with Vite or your machine. Maybe it's serving under http://127.0.0.1:5173/ or http://[::1]:5173/ instead of http://localhost:5173/ ?
> 
> The repro is working fine for me.

In fact, I was thinking that the problem is because of Vite. The thing is, I'm mentioning two problems and I just put the project where the hot reloading problem happened to me. I mean, the repro doesn't show the "page not found" problem.
So, maybe there's a bug in Vite, and the repro is only for the hot reloading problem, sorry for the mistake, but the first project (non Sveltekit) was deleted because I couldn't do anything.

**Comment by maximedupre** [comment]
I confirm that this is an issue. I updated my existing project to the latest version and now when I try to access localhost:3000... nothing 

```
  VITE v3.0.2  ready in 367 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: http://192.168.0.160:3000/
```

**Comment by benmccann** [comment]
It doesn't look like there's any bug here. Better places to ask for help would be Discord or StackOverflow

**Comment by nelson-111** [comment]
> It doesn't look like there's any bug here. Better places to ask for help would be Discord or StackOverflow

That's right, I updated an old sveltekit project and all is well.
