### ISSUE TITLE
support fetching with non-string bodies

### ISSUE THREAD

**Issue by sourcecaster** [sveltejs/kit#5680]
### Describe the bug

Calling fetch function from async export load({fetch} with Uint8Array body results in exception: Request body must be a string.
A little bit of investigating the problem gave me this:

```javascript
if (opts.body && typeof opts.body !== 'string') {
    // per https://developer.mozilla.org/en-US/docs/Web/API/Request/Request, this can be a
    // Blob, BufferSource, FormData, URLSearchParams, USVString, or ReadableStream object.
    // non-string bodies are irksome to deal with, but luckily aren't particularly useful
    // in this context anyway, so we take the easy route and ban them
    throw new Error('Request body must be a string');
}
```

### Reproduction

1. Create a route with load function.
```javascript
export async function load({fetch}) {
    fetch('api/endpoint', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/octet-stream'
        },
        body: new Uint8Array([1,2,3,4]);
    });
    return {};
}
```
2. Run it.

### Logs

```shell
500
Request body must be a string
Error: Request body must be a string
    at fetch (file:///Users/*******/projects/web/*******/.svelte-kit/runtime/server/index.js:2241:13)
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /opt/homebrew/bin/node
    npm: 8.7.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Chrome Canary: 105.0.5195.2
    Firefox: 100.0.2
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.52 => 1.0.0-next.52 
    @sveltejs/adapter-node: ^1.0.0-next.78 => 1.0.0-next.78 
    @sveltejs/kit: ^1.0.0-next.355 => 1.0.0-next.355 
    svelte: ^3.48.0 => 3.48.0
```

### Severity

serious, but I can work around it

### Additional Information

The simplest solution is of course "use JSON or base64" and yet it's not a solution at all because I'm using high-performance PackMe binary protocol (I mean, really high performance, like hundreds of thousands pack/unpack operations per second, you can't do that with JSON or base64). Would be nice to keep it that way (obviously, not possible for now).

And it all worked perfectly until I realized that I need to make a few api calls inside load function :( It turned out that fetch from load function is not the same as browser fetch. Can we do something about it? It looks like implementing Blob, BufferSource and ReadableStream support isn't something too complicated.

**Comment by benmccann** [comment]
Please update to the latest version (`1.0.0-next.392`) and provide a GitHub repository with a reproduction or this issue will be closed

**Comment by sourcecaster** [comment]
It's the same with 1.0.0-next.392

**Comment by tcc-sejohnson** [comment]
From the bug template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be short, self-contained and correct and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

There are 300 open issues. If it takes 5 minutes to create a reproduction project, that's 25 hours _just to reproduce bugs_. We all have full-time jobs.

**Comment by benmccann** [comment]
Here's the line in question:

https://github.com/sveltejs/kit/blob/66e0ede13451918ced85255e2b87dc90fd61a446/packages/kit/src/runtime/server/page/load_node.js#L206

The code comment is a bit incomplete as it does not mention `TypedArray`: https://developer.mozilla.org/en-US/docs/Web/API/Request/Request

**Comment by vicky1999** [comment]
Hi, can I work on this issue
