### ISSUE TITLE
Dev mode page SSR ignores updates to file until it's restarted

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#572]
**Describe the bug**
`svelte-kit dev` only SSRs a page once and then never refers to the file's contents again. The only thing it will notice is deleting the file (renders a 404 instead), but even then, creating a new file with the same name loads the cached SSR page again.

**To Reproduce**
```bash
npm init svelte@next
# no typescript, css
npm install
```
Comment out `%svelte.head%` as `<!-- %svelte.head% -->` in `src/app.html` to better see the effect.
```bash
npm run dev
```
You should see `Hello world!` on http://localhost:3000
Update `index.svelte` to say `Another message` and refresh the page, it will still be `Hello world!`.
Restart the dev server to see the changes take effect.

**Expected behavior**
At the very least, SSR should update on a manual refresh.
Ideally, live reload would trigger on file update if HMR is not possible (without commenting out `%svelte.head%` of course).

**Information about your SvelteKit Installation:**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 12.61 GB / 31.95 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.6.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.50)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.51
    svelte: ^3.29.0 => 3.35.0
```

**Severity**
This really sucks for developing on certain workflows, since it requires you to restart the dev server over every change.

**Comment by Rich-Harris** [comment]
This appears to be caused by vite-plugin-svelte's caching (cc @dominikg). If I comment out the following in `node_modules/@svitejs/vite-plugin-svelte/dist/index.js`...

```js
if (cachedCompileData && !options.disableTransformCache) {
  log.debug(`transform returns cached js for ${filename}`);
  return cachedCompileData.compiled.js;
}
```

...everything works as expected. Tested with 0.11.1 (the latest version). The same code exists in the `@sveltejs` version, but I haven't yet verified whether the issue is still present: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/vite-plugin-svelte/src/index.ts#L174-L177

**Comment by Rich-Harris** [comment]
Confirmed still happening with `@sveltejs/vite-plugin-svelte` `main` branch.

**Comment by benmccann** [comment]
I filed an issue in the `vite-plugin-svelte` repo to track: https://github.com/sveltejs/vite-plugin-svelte/issues/3
