### ISSUE TITLE
 GET request query params in SSR

### ISSUE THREAD

**Issue by codeyash** [sveltejs/kit#5722]
### Describe the bug

It should return query parameters but it return nothing and won't provide any method to access GET parameters in SSR or server side.

### Reproduction

Always

### System Info

```shell
Any System
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
I have no idea what this means. And "Always" is not a valid reproduction.

**Comment by mustofa-id** [comment]
I guess op is using `RequestEvent#params` instead of `RequestEvent#url.searchParams`. I often find complaints like this and they miss the docs.

**Comment by benmccann** [comment]
This issue is not understandable. If you're not going to respect us and our time by following the template, there's no reason to leave this open
