### ISSUE TITLE
Add `DOM.Iterable` to base `tsconfig.json` `lib`

### ISSUE THREAD

**Issue by jquesada2016** [sveltejs/kit#5733]
### Describe the problem

Currently, with the default base `tsconfig.json`, DOM objects, such as `FileList` are not iterable. Perhaps it would be a good idea to add the afore mentioned `lib` by default?

### Describe the proposed solution

I would like `DOM.Iterable` be added to the default `tsconfig.json` generated by SvelteKit.

### Alternatives considered

Leaving as is and using `tsconfig.json` in project directory.

### Importance

nice to have

**Comment by Mlocik97** [comment]
I always added it first thing after initializing project, but it never bothered me so much I would create issue or PR.
