### ISSUE TITLE
Can't use `fs` with relative paths in `svelte.config.js` since the `postinstall` lifecycle hook has a different `$PWD`

### ISSUE THREAD

**Issue by martinszar** [sveltejs/kit#5769]
### Describe the bug

The most recent update of SvelteKit can not be installed on my project because of my use of `fs.readFileSync` and relative paths inside of `svelte.config.js`.
It seems like the added lifecycle hook executes the code of `svelte.config.js` inside of `node_modules/@sveltejs/kit` (according to `process.cwd()`), which of course breaks any relative paths and finally makes `fs.readFileSync` throw, which in turn makes `npm update` or `npm install` fail and not change anything.
I use a JSON file to populate the content of `config.kit.prerender.entries`, so accessing a file using Nodes `fs` is crucial. 

### Reproduction

[🎩 Repository for reproduction](https://github.com/martinszar/sveltekit-lifecycle-pwd-reproduction)
I quickly made a skeleton project using `npm create svelte@latest` and added the following four lines to the top of `svelte.config.js`:
https://github.com/martinszar/sveltekit-lifecycle-pwd-reproduction/blob/main/svelte.config.js#L1-L4

To observe the bug just clone the repo and run `npm install`. I additionally added a `console.log` marked with the 🚨 emoji, which will log `process.cwd()`.

### System Info

```shell
System:
    OS: Linux 5.18 Fedora Linux 36 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 10.09 GB / 15.49 GB
    Container: Yes
    Shell: 3.5.0 - /usr/bin/fish
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    npm: 8.13.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 102.0
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Here https://github.com/sveltejs/kit/blob/ef6d42b65c58bf5d9ec74298048c012707ffaf38/packages/kit/src/cli.js#L58 we've got some logic for looking for the `svelte.config.js` file in a different place depending on whether we're in a `postinstall` event or not. Presumably we could `process.chdir()` here rather than simply loading the config file from the appropriate directory.

**Comment by Conduitry** [comment]
That doesn't appear to quite work. I'm guessing the CWD needs to be changed _back_ afterwards.

Also, for the record, you repro is trying to load `"./.svelte.config.js"` rather than `"./svelte.config.js"`.

**Comment by Conduitry** [comment]
Looks like the fix worked. Should be good now with `next.401`.
