### ISSUE TITLE
[vite-plugin-svelte-kit] Prerendering failed with code 1        error during build:

### ISSUE THREAD

**Issue by tomaz-on** [sveltejs/kit#5776]
### Describe the bug

[vite-plugin-svelte-kit] Prerendering failed with code 1       
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///C:/Users/y1981/OneDrive/Desktop/Coding/sveltekit/lista-anapu/anapu-app/node_modules/@sveltejs/kit/dist/vite.js:2447:14)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

vite.config.js
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()]
};

export default config;

vite.js (where the error is pointed in child by vscode) : 

child.on('exit', (code) => {
					if (code) {
						_**reject(new Error(`Prerendering failed with code ${code}`));**_    // the line pointed by vscode error
					} else {
						prerendered = JSON.parse(fs$1.readFileSync(results_path, 'utf8'), (key, value) => {
							if (key === 'pages' || key === 'assets' || key === 'redirects') {
								return new Map(value);
							}
							return value;
						});
						fulfil(undefined);
					}
				});

### Reproduction

Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///C:/Users/y1981/OneDrive/Desktop/Coding/sveltekit/lista-anapu/anapu-app/node_modules/@sveltejs/kit/dist/vite.js:2447:14)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)

### System Info

```shell
windows 10 updated, node and npm updated last version, node LTS last version, windows and vscode updated last version
```

### Severity

annoyance

### Additional Information

I am testing the sveltekit , my clients begun call me because another week offline, I need help, is my first time with a js framework, but I'm trying searching alone for answers but now is vite issues , my lib folder seems not to work using $ and I have to point the folders in the old ways ... 
![childIssueVscode](https://user-images.githubusercontent.com/59876880/182052058-b83e53e3-c15b-40be-85c6-35f5959480e0.png)

**Comment by Conduitry** [comment]
As indicated in the issue template, you need to provide a minimal reproduction - either as a link to a repo or a link to a StackBlitz project - or this issue will closed.

**Comment by tomaz-on** [comment]
The first time I asked for help here, if I messed up, please forgive me and show me the right way to do it, my clients is getting angry because the app is offline and I really loved sveltekit but I need to put at least the test working, is my first time with a framework, I almost tried vue but only sveltekit I enjoyed, because I work with vanilla html vanilla css and vanilla js ... Sorry If I ask for help in the wrong way I am here to learn and do it in the right way next time :)

**Comment by tomaz-on** [comment]
The first time I asked for help here, if I messed up, please forgive me and show me the right way to do it, my clients is getting angry because the app is offline and

**Comment by tomaz-on** [comment]
I understand ... Seems to be happening with a lot of people but in different ways

**Comment by tomaz-on** [comment]
I'll try to get help with the guys from sveltekit in discord , or I'll have to back to normal way to make the app and forget about sveltekit for a while until 1.0 get ready
