### ISSUE TITLE
Posting Form sends both a POST and GET request

### ISSUE THREAD

**Issue by alex-way** [sveltejs/kit#5781]
### Describe the bug

When using a form with the `POST` method, sveltekit seemingly sends both a POST request and a GET request?

Effectively what I'm attempting to do is to protect an endpoint by only allowing the POST http method. However, a genuine POST request to the endpoint is causing a redirect.

My expectation is that the reproduction should redirect on a GET request to the `/post` endpoint and will render the page on a POST request.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ptfleq

### Logs

```shell
N/A
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.62 
    @sveltejs/kit: next => 1.0.0-next.379 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.2
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior. https://kit.svelte.dev/docs/routing#endpoints-post-put-patch-delete `GET` is also called afterwards for full-page form submits to get the other props. You can check for `event.request.method` in `GET` and do nothing if the request is not actually a GET.

However, be aware that a lot of this stuff is going to be changing in #5748.
