### ISSUE TITLE
Request: ability to throw error() in `+server.js` endpoints just like in load functions

### ISSUE THREAD

**Issue by rmunn** [sveltejs/kit#5783]
### Describe the problem

One thing I like about #5748's upcoming changes is the ability to throw errors in `load` with the `error()` helper function. Currently, that doesn't apply to endpoint handlers in `+server.js`, which must return a Response object with a suitable HTTP error code. I'd like to request that an `error()` helper function be made available to `+server.js` handlers as well.

My use case is an API project that I implemented using Svelte-Kit. I have a lot of auth code that's the same across multiple API endpoints, which I've extracted into helper functions: for example, the `allowSameUserOrAdmin` function checks the JWT found in the Authorization header, and ensures that: 1) it's valid, correctly signed, and not expired, and 2) it belongs to either the username whose settings are being updated, or to a site admin who has access rights to change anything.

Currently, all my auth functions return an object of the same "shape" that endpoint handlers currently return: `{ status: 401, body: "Unauthorized" }` (or 403, or ...) for failures, or `{ status: 200, body: '' }` if the user is authorized to perform the operation. Then the rest of the code in the "edit user account" endpoint looks something like this:

```js
const authResult = await allowSameUserOrAdmin(db, { params: { username }, headers });
if (authResult.status === 200) {
    const result = await updateUser(db, user.id, userDetails));
    return { status: 200, body: result };
} else {
    return authResult;
}
```

I have boilerplate like this all over my endpoint handlers. But if my auth helper functions could **throw** errors (that had HTTP statuses and messages attached to them, just like the `error()` helper for load functions), I could simplify that boilerplate down to just two lines:

```js
await allowSameUserOrAdmin(db, { params: { username }, headers });
return updateUser(db, user.id, userDetails));
```

### Describe the proposed solution

An `error()` function would be made available to `+server.js` code, and would work similarly to how `load()` functions work: if the handler function throws a SvelteKitError (or whatever specific exception the `error()` function constructs) instead of returning a `Response` object, then the Svelte-Kit server code will catch that exception and turn it into a `Response` with appropriate status and body (taken from the values passed into `error()`). Any exceptions that did not come from the `error()` function would be handled the same way they currently are, by producing a 500 Internal Server Error response.

### Alternatives considered

Once #5748 goes through, I can change my auth functions to return a Response with appropriate status codes, but then the `if (authResult.status === 200)` boilerplate would remain essentially unchanged. Or I could create my own AuthException exceptions and throw them, and reduce the boilerplate down to a throw-catch:

```js
try {
    await allowSameUserOrAdmin(db, { params: { username }, headers });
    return updateUser(db, user.id, userDetails));
} catch (e) {
    if (e instanceof AuthException) return makeResponseFrom(e);
    else throw e;
}
```

But that's the same number of lines as my original boilerplate, so doing it myself isn't a huge gain. To really be able to simplify my boilerplate, I would need Svelte-Kit to handle the "catch and `makeResponseFrom`" logic.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
What I like about the current(future) API is that it's very simple: Return any form of `Response` object, that's it. I'm not sure muddying the waters helps here. Your code could be rewritten as follows to make it less repetitive:

```js
return allowSameUserOrAdmin(db, { params: { username }, headers }, () => { /* code that should run when allowed */ });
```

where `allowSameUserOrAdmin` is something like

```js
function allowSameUserOrAdmin(db, params, cb) {
   if (notAuthed(db, params) {
      return Response('Nope', { status: 400 });
   } else {
      return cb();
   }
}
```

**Comment by Rich-Harris** [comment]
I was envisaging that we _would_ support the same helpers, since a) as you say, it provides consistency (e.g. reusing auth logic between `+page.server.js` and `+server.js`), and b) it would actually be _more_ to _not_ support them.

The same goes for `setHeaders` — even though it's redundant (you can return a `Response` with whatever headers you want) it would be weird to prevent its usage on that basis.

In fact this is described in #5748, in the '`+server.js` API' section of the OP:

> As conveniences (and to keep things consistent), the `error` and `redirect` imports and the `setHeaders` helper can be used, though strictly speaking they're not necessary since you could construct your own error/redirect `Response` objects with whatever `headers` you like.

**Comment by rmunn** [comment]
Great! I missed that, but that's exactly what I was wanting to have. Shall I close this issue as redundant? Or would you prefer for me to leave it open for some reason?

**Comment by tcc-sejohnson** [comment]
I'm just going to go ahead and close it for now since it's part of the design doc. If, for some reason, we change that design before release and this feature doesn't get implemented, we can reopen it or create a new one. Or Rich can reopen it if he thinks it should stick around. :)
