### ISSUE TITLE
No way to silence warning "Omitting environment variable"

### ISSUE THREAD

**Issue by wtesler** [sveltejs/kit#5801]
### Describe the bug

When I call `vite dev`, I get a few warnings which state `Omitting environment variable "ProgramFiles(x86)" from $env/static/private as it is not a valid identifier` .

More generally `Omitting environment variable "<X>" from $env/static/private as it is not a valid identifier`

I can see it is due to the fact that some of the env variables on my machine have spaces etc...

I don't mind that they are omitted, but I don't want to see the warning every time I call vite. How can I ignore the warning?

### Reproduction

Set an env variable on your machine to to have a key with a space in it like "TEST A" -> "TEST".

Then when calling `vite dev` you will get this warning.

### System Info

```shell
svelte 3.49.0
@sveltejs/kit 1.0.0-next.401
vite 3.0.4
```

### Severity

annoyance

**Comment by NormandoHall** [comment]
Same here
