### ISSUE TITLE
Invoking methods directly on components

### ISSUE THREAD

**Issue by infusion** [sveltejs/kit#5812]
### Describe the problem

To invoke an exported method of a component, one has to bind it like 

```
<Component bind:this={foo} />
```

and can then use the proxy `foo` like

```
foo.Bar()
```

This gets a mess when the components are generated dynamically within a loop. Currently I do

```
{#each x as y}
<Component bind:this={xxx[y.id]} />
{/each}
```
with an invoke in the `onMount()` function.

### Describe the proposed solution

I would like to propose an inline reference to access exported attributes and methods right within the definition:

```
{#each x as y}
  <Component call:Bar={y} />
{/each}
```

For what is this good? I have a uniform `setValue()` function for all input-field components, such as dropdowns, file uploads, ... and setting values inline with an attribute is typical. However as with more complex components it's not possible to just set the DOM attribute, but invoke further actions, which requires the ability to call methods.

### Alternatives considered

Using only attributes for this use-case would be possible if there were an attribute-watcher that is called whenever the attribute is changed from outside the component.

### Importance

would make my life easier

**Comment by chvanam** [comment]
I think this case would be better discussed on Svelte's GitHub, not here on SvelteKit.

Although I feel like your case could be solved with existing Svelte logic for example with a component prop holding the argument and another holding an internal function's name that gets called with some matching logic in your component.

**Comment by dominikg** [comment]
This isn't related to sveltekit and like suggested you can ask for help on svelte discord on how to solve the presented case with current features of svelte
