### ISSUE TITLE
Storybook ReferenceError: __SVELTEKIT_DEV__ is not defined

### ISSUE THREAD

**Issue by gbkwiatt** [sveltejs/kit#5827]
### Describe the bug

After some update - can't remember which one since I didn't test storybook for a while ( but it was working month ago). 
When building static storybook and trying to run it I get `Uncaught ReferenceError: __SVELTEKIT_DEV__ is not defined at env.js:11:13`  in the console when serving storybook. 

I've updated all storybook and sveltekit deps to latest but it's still the same. 

here is my main.js from storybook 
```javasript
const path = require('path');
const preprocess = require('svelte-preprocess');
const { viteCommonjs } = require('@originjs/vite-plugin-commonjs');

module.exports = {
    core: {
        builder: '@storybook/builder-vite',
    },
    stories: ['../src/**/**/*.stories.mdx', '../src/**/**/*.stories.@(js|jsx|ts|tsx|svelte)'],
    addons: ['@storybook/addon-essentials', '@storybook/addon-links', '@storybook/addon-svelte-csf'],
    staticDirs: ['./static'],
    svelteOptions: {
        preprocess: preprocess({
            postcss: true,
        }),
    },
    async viteFinal(config) {
        config.plugins = [viteCommonjs(), ...config.plugins];
        config.resolve.alias = {
            $app: path.resolve('./.svelte-kit/runtime/app'),
            $tailwindConfig: path.resolve('./src/lib/tailwind.config.cjs'),
        };

        // Allow files outside root for any aliased modules
        if (config?.server?.fsServe) {
            config.server.fsServe.strict = false;
        }

        return config;
    },
};
```

### Reproduction

run:

- vite build
- build-storybook
serve `stsorybook-static` and open it in the browser

Then you get 

![image](https://user-images.githubusercontent.com/62710468/183056039-2a98ab52-de0a-44ea-9628-a564f28d03d8.png)

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 5.19 GB / 9.72 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 7.24.2 - /sveltekit/node_modules/.bin/npm
  npmPackages:
    @sveltejs/kit: 1.0.0-next.403 => 1.0.0-next.403 
    svelte: 3.48.0 => 3.48.0 
    vite: ^3.0.4 => 3.0.4
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
I'd suggest looking at https://github.com/michaelwooley/storybook-experimental-vite for an example. Does it work if you update your `viteFinal` to be closer to the example there?

**Comment by gbkwiatt** [comment]
I've tried that config, but config there does nit create correct build, it's missing assets and 'iframe.html'. Basically it's not creating correct storybook build.

But I've compared output config that's returned and they are identical except plugin orders, so that config there gave me hard times and couldn't make it work.

**Comment by benmccann** [comment]
It's not clear that there's a bug in SvelteKit here. It looks more likely to be a usage issue since the example project https://github.com/michaelwooley/storybook-experimental-vite works just fine. I recommend you ask for help on Discord instead. If there's a bug, you should follow the template and provide a minimal reproducible example. You should also have minimal changes from the working project https://github.com/michaelwooley/storybook-experimental-vite and indicate why exactly you think there's a SvelteKit bug. You also need to provide clearer instructions (what is "build-storybook" and why is there a `-` in it? How do you "serve stsorybook-static"? etc.)
