### ISSUE TITLE
node build failed ,server.init is not a function

### ISSUE THREAD

**Issue by 1610474496** [sveltejs/kit#5837]
### Describe the bug

TypeError: server.init is not a function
    at file:///mnt/d/source/official-website/build/handler-393b2283.js:1047:8
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

### Reproduction

None

### System Info

```shell
{svelte,@sveltejs/*,vite} adapter-node
```

### Severity

annoyance

**Comment by Conduitry** [comment]
We can't diagnose anything without a reproduction and without the versions of dependencies you're using. This sounds like you need to make sure that both the adapter and Kit itself are on the latest versions.

**Comment by pdaddyo** [comment]
I can confirm I had this issue with latest adapter but slightly out of date kit, and bumping to these latest versions fixed it:

 ```
   "@sveltejs/adapter-node": "^1.0.0-next.86",
   "@sveltejs/kit": "1.0.0-next.405",
```

**Comment by 1610474496** [comment]
Upgraded the kit version and then resolve this problem

**Comment by jinxmcg** [comment]
`TypeError: server.init is not a function` bug was present on Vercel too, the update to "1.0.0-next.405" fixed it.
