### ISSUE TITLE
Self-Signed Certificate error on load function's fetch

### ISSUE THREAD

**Issue by amunim** [sveltejs/kit#5852]
### Describe the bug

For SSR Load function we have to use Svelte's implementation of fetch but their isn't a way for custom agent(nor `rejectUnauthorized` property like axios), how I am I supposed to work with my locally hosted ASP.Net API?

### Reproduction

Create a new ASP.Net API with HTTPS enabled.
Create a new Svelte project, use fetch in Load function to query the result and it should throw an error.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.34 GB / 15.84 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    svelte: ^3.44.0 => 3.49.0
```

### Severity

blocking all usage of svelte

**Comment by benmccann** [comment]
This is bug report is totally unactionable. You didn't provide a reproduction or show what the error is. You probably need to install the certificate in your local store. Please ask for help on GitHub or StackOverflow. It's not clear there's any bug in SvelteKit here

**Comment by amunim** [comment]
Oh my bad, I forgot to paste in the log, here is the error:
```
TypeError: fetch failed
    at Object.processResponse (file:///D:/projects/AptRevision%20front-end/book-relation/node_modules/@sveltejs/kit/dist/node/polyfills.js:10520:24)
    at file:///D:/projects/AptRevision%20front-end/book-relation/node_modules/@sveltejs/kit/dist/node/polyfills.js:11238:39
    at node:internal/process/task_queues:141:7
    at AsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:138:8)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: Error: self signed certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
      at TLSSocket.emit (node:events:390:28)
      at TLSSocket._finishInit (node:_tls_wrap:944:8)
      at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT'
  }
}
```
Isn't there any way to include a custom agent or a `rejectUnauthorized: false` property on svelte's implementation so I can use it? The certificate is installed and browser shows connection is secure, however here is my code(but you should be able to reproduce by only creating a new project)
```typescript
export const load: Load = async ({ fetch }) => {
        const baseUrl = "https://localhost:44377/api";
        const loginUrl = `${baseUrl}/Authentication/Login`;
        const book1Url = `${baseUrl}/Book/1/Topics`;
        const book2Url = `${baseUrl}/Book/5/Topics`;

        try {
            const login = await fetch(loginUrl, {
                method: "GET",
                body: JSON.stringify({
                    username: "111",
                    password: "111",
                }),
                headers: {
                    "Content-Type": "application/json",
                },
                
                return {
                    status: login.status,
                    props: {
                            jwt: JSON.parse(await login.text())['value']
                    },
                };
            });
         } catch (err) {
            console.log(err);

                return {
                    status: login.status,
                    error: err
                };
        }
    };
```

**Comment by jasonlyu123** [comment]
This is not an issue on the svelte-kit side. The error is thrown by node.js. Nodejs only trust some preconfigured certificate. You can provide your own with https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

There is plenty of stackoverflow question about this. I am sure you can find something useful there.

**Comment by buzzy** [comment]
Why not make life easier for people instead of disregarding their question?
Simply use this to ignore self-signed certs:
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`
