### ISSUE TITLE
setInterval uses Node.js typings

### ISSUE THREAD

**Issue by cloudlena** [sveltejs/kit#5859]
### Describe the bug

I'm creating a statically rendered site using `@sveltejs/adapter-static` and TypeScript. One of my components uses `setInterval`. This function returns a `NodeJS.Timer` on Node.js and a `number` in the browser. Since I'm using it in the browser, I would need the typings to reflect that and have it return a `number`. However, if I use it, TypeScript assumes it to return a `NodeJS.Timer`.
I would expect the typings to expect a `number` instead.

The workaround of typing it as a `NodeJS.Timer` results in `eslint` reporting an error:

```txt
/home/me/project/src/lib/Component.svelte
  11:13  error  'NodeJS' is not defined  no-undef
```

### Reproduction

https://github.com/elatella/bernpride.ch/blob/0df3087ae6df72f2ff4b3666f2dfb23a9379d938/src/lib/Countdown.svelte#L37

### System Info

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 9.45 GB / 15.33 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    npm: 8.16.0 - /usr/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Chromium: 104.0.5112.79
    Firefox: 103.0.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.39
    @sveltejs/kit: next => 1.0.0-next.405
    svelte: ^3.46.0 => 3.49.0
    vite: ^3.0.0 => 3.0.5
```

### Severity

annoyance

**Comment by CaptainCodeman** [comment]
It's because the global object could be either node or window in the browser.

The easiest fix might be to be more explicit by referring to it as `window.setTimeout`

**Comment by tcc-sejohnson** [comment]
Hmm. @dummdidumm, any ideas? I can see where the TS confusion would come from, because depending on SSR/browser, the timer function could be in either environment.

**Comment by benmccann** [comment]
If you want it to work on the server as well, you could use `ReturnType` as suggested above: https://stackoverflow.com/a/69301944

Anyway, this seems like a TypeScript usage thing and not related to SvelteKit at all
