### ISSUE TITLE
Relative route to endpoint not behaving as expected

### ISSUE THREAD

**Issue by jwsinner** [sveltejs/kit#5860]
### Describe the bug

Suppose I have the following route structure:
```
└───monitor
    └───[server]
        └───status
            │   api-[pin].ts
            │   index.svelte
            │
            └───[id]
                    api-[pin].ts
                    index.svelte
                    index.ts
```
In `[id]/index.svelte` I have a form `<action="./api-{pin}" method="post">`. I would assume by using `./` that my form would `POST` to the endpoint in the `[id]` directory based on the relative location to `index.svelte`. However, it is posting to the endpoint in the `status` directory.

If I want access to `id` in my api endpoint, I have to pass that along in the form in a hidden input with value bound to `$page.params.id`.

I'm either doing something very wrong here (most likely), or the routing isn't quite where it needs to be.

### Reproduction

[Here](https://github.com/jwsinner/sveltekit-routing-issue-demo) is a link to a basic repo to demonstrate the issue.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-3350P CPU @ 3.10GHz
    Memory: 3.09 GB / 15.93 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.81
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
    Internet Explorer: 11.0.19041.1202
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
That's how HTTP and web browsers work

If you're on http://example.com/3 and link to `./api-hello` it will take you to http://example.com/api-hello

**Comment by jwsinner** [comment]
This is still counter-intuitive. If I'm on `http://example.com/3`, SvelteKit code is really putting me at `http://example.com/3/index.svelte`. If we were doing this with only html, then I could put `<a href="./about.html">about</a>` or `<a href="about.html">about</a>`  in `http://example.com/3/index.html` and that would send me to `http://example.com/3/about.html`. 
If my structure was this:
```
└───monitor
    └───[server]
        └───status
            └───[id]
                    index.svelte
                    index.ts
                    about.svelte
```
It should be reasonable to assume I could create this link `<a href="./about">about</a>` in `monitor/[server]/status/[id]/index.svelte` and have it link to `monitor/[server]/status/[id]/about.svelte` because they are both in the same sub-directory. This `<a href="$page.params.id/about">about</a>` seems unnecessarily redundant.
