### ISSUE TITLE
content length mismatch when use load.fetch

### ISSUE THREAD

**Issue by jasonlyu123** [sveltejs/kit#5870]
### Describe the bug

When using `load.fetch` to load external resources. The `content-length` header of the page would be piped to the fetch call. This usually won't be a problem. But there's some edge case where you would send a post request to the page. Maybe accidentally forgot to preventDefault on a form. This would cause a fetch failed error thrown by node undici, which is kind of hard to debug if you don't know what `load.fetch` does behind the scene. 

The case of why I found the issue is also an edge case. For some reason the reverse proxy I am using appends a `'content-length': 0` header to the proxied request which causes the same problem. 

### Reproduction

https://github.com/jasonlyu123/kit-load-content-length-issue

submit the search form on the index page. A fetch-failed error would be thrown but It won't happen when you refresh the page because then it's a get request which in theory doesn't have a `content-length` header. 

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 3.18 GB / 15.42 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.47)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64
    @sveltejs/kit: next => 1.0.0-next.405
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.5
```

### Severity

annoyance

### Additional Information

Probably can be fixed by adding `content-length` to the blacklist here. Can't find a drawback for removing `content-length` header here. Can anyone think of one? 

https://github.com/sveltejs/kit/blob/87552ef7efd2f6b38dd7e3f7a90bc9fd5ceb12f3/packages/kit/src/runtime/server/page/load_node.js#L128-L135

Since this file is being split in the big update and it's an edge case. Guess it would be easier to handle it after that.

**Comment by benmccann** [comment]
Related: https://github.com/sveltejs/kit/pull/5195

Perhaps we should consider reversing the check and doing a whitelist given how many issues the current approach has been causing

**Comment by Conduitry** [comment]
I'm still very much against #5195. Adding `content-length` to the blacklist sounds reasonable. Regarding switching from blacklisting to whitelisting: I'm sure that would take us a while to converge on a good list, as well, and it would throw away whatever progress we've been making from the blacklist side.

**Comment by benmccann** [comment]
Ok, the blacklisting approach makes more sense to me after having read through the original ticket: https://github.com/sveltejs/kit/issues/696
