### ISSUE TITLE
[Adapter Vercel] Returning a json Response object from an edge function returns an empty object

### ISSUE THREAD

**Issue by f-elix** [sveltejs/kit#5873]
### Describe the bug

I'm trying to fetch some json from an endpoint which is deployed as an edge function. 

The endpoint returns a `Response` object, like this:

```ts
export const GET: RequestHandler = () => {
	const body = {
		some: {
			data: 'from my endpoint'
		},
		here: {
			isSome: 'more'
		}
	};
	return new Response(JSON.stringify(body), {
		status: 200,
		headers: {
			'content-type': 'application/json'
		}
	});
};
```

Everything works perfectly in local dev and preview, but once deployed to Vercel the response is an empty object.

If I return a POJO instead of a `Response`

```ts
export const GET: RequestHandler = () => {
	const body = {
		some: {
			data: 'from my endpoint'
		},
		here: {
			isSome: 'more'
		}
	};
	return {
            body
        );
};
```

or if I deploy the endpoint as a serverless function instead of edge, I get the data.

Maybe I'm missing something in my code, but I don't see what could be wrong with it.

### Reproduction

Here is a minimal reproduction:

Repo - https://github.com/f-elix/vercel-edge-response-bug
Deploy - https://vercel-edge-response-bug.vercel.app/ 

Click fetch data to get the data from the endpoint. It should work in local dev but not in the Vercel deployment.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 741.42 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 79.0
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-vercel: next => 1.0.0-next.66 
    @sveltejs/kit: next => 1.0.0-next.405 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.5
```

### Severity

serious, but I can work around it

**Comment by tcc-sejohnson** [comment]
Is there some edge-function-endpoint behavior I'm not aware of? Returning a `Response` is not supported for endpoints. https://kit.svelte.dev/docs/types#sveltejs-kit-requesthandleroutput

**Comment by tcc-sejohnson** [comment]
Ahhh, hold on. The other maintainers pointed out that `Request` implicitly fulfills the return type interface, so this _should_ work.

**Comment by Rich-Harris** [comment]
Does it work with `edge: false`? (Would try it myself but not currently in a position to)

**Comment by f-elix** [comment]
@Rich-Harris Yes `edge: false` makes it work. That's what I meant by 'deploying as a serverless function', sorry if that was confusing.

**Comment by dummdidumm** [comment]
No longer reproducible with the latest versions
