### ISSUE TITLE
Way to specify props for layout component

### ISSUE THREAD

**Issue by winstonDeGreef** [sveltejs/kit#5881]
### Describe the problem

On the site I am currently working on. Most pages have a main with width `60em`. On one page I want `<main>` to have a width of `30em`.

### Describe the proposed solution

A special element, like `<sveltekit:layout>` wherein props can can be passed to the layout components. When having nested layouts, all layouts would get the prop. Props only for a specific layout could be passed by specifying the route of the layout instead of just layout. (`<sveltekit:layout/settings>`, `<sveltekit:layout/settings@foo.svelte>`

### Alternatives considered

In this case, I could add another element in `<main>` to decrease the width. A more general solution is to have a store with these props.

### Importance

nice to have

**Comment by PatrickG** [comment]
You can use [stuff](https://kit.svelte.dev/docs/loading#output-stuff) (soon `$page.data`) for that.

**Comment by tcc-sejohnson** [comment]
Patrick is correct. You can reference `$page.stuff` store in your `layout`, and you can set that `stuff` by using `load`. I'll come back and close this in a day or two when you've had time to see the responses. 🙂
