### ISSUE TITLE
svelte.config.js does not allow vitePlugin section

### ISSUE THREAD

**Issue by tv42** [sveltejs/kit#5888]
### Describe the bug

```
/** @type {import('@sveltejs/kit').Config} */
const config = {
...
  vitePlugin: {
    experimental: {
      useVitePreprocess: true,
    },
  },
};
```

leads to Typescript complaining `Object literal may only specify known properties, and 'vitePlugin' does not exist in type 'Config'`. This change hides the error:

```
/** @type {import('@sveltejs/kit').Config & {vitePlugin: unknown}} */
```

Related, the documentation at https://github.com/sveltejs/kit/blob/e297259a8c357f2083c2ca77e8beffa009fc919d/documentation/docs/18-assets.md?plain=1#L21-L28 is wrong and is missing the `vitePlugin` level in the config.

### Reproduction

sorry

### System Info

```shell
System:
    OS: Linux 5.18 NixOS 22.05 (Quokka) 22.05 (Quokka)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 6.65 GB / 62.60 GB
    Container: Yes
    Shell: 5.1.8 - /nix/store/00z6kxv40m8aq9rpf1g1sfgn9mfjvhzd-bash-5.1-p8/bin/bash
  Binaries:
    Node: 16.14.2 - /nix/store/5f0bcmbylg2zizwp96z3976mxnb24jk1-nodejs-16.14.2/bin/node
    npm: 8.5.0 - /nix/store/5f0bcmbylg2zizwp96z3976mxnb24jk1-nodejs-16.14.2/bin/npm
  Browsers:
    Firefox: 103.0.1
  npmPackages:
    @sveltejs/adapter-cloudflare: ^1.0.0-next.31 => 1.0.0-next.31
    @sveltejs/kit: ^1.0.0-next.405 => 1.0.0-next.405
    @sveltejs/vite-plugin-svelte: ^1.0.1 => 1.0.1
    svelte: ^3.49.0 => 3.49.0
    vite: ^3.0.5 => 3.0.5
```

### Severity

annoyance

**Comment by evankford** [comment]
@tv42 

Since a few months back, the `vitePlugin` settings are moved into their own `vite.config.js` file in the root of the project directory. See the [up-to-date docs here.](https://kit.svelte.dev/docs/project-structure#project-files-vite-config-js) It looks like you were referring to a past version of the documentation.

**Comment by Conduitry** [comment]
Indeed, `vitePlugin` has been moved to `vite.config.js`.

The reference in https://kit.svelte.dev/docs/assets should have been updated, but wasn't. I'm marking this as a documentation issue and we can leave this open until that's fixed.

**Comment by benmccann** [comment]
I've sent a PR to update the docs: https://github.com/sveltejs/kit/pull/5889

It seems there's also a bug that's been introduced though if you're not able to pass the `vitePlugin` options

**Comment by Conduitry** [comment]
Okay, so what's described in https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/config.md is the intended way for this to work - you pass it directly to the plugin if you're using Vite alone, or you pass it in `viteConfig` in `svelte.config.js` if you're using SvelteKit - but the latter of these is broken (or at least has bad types)?

**Comment by dominikg** [comment]
Passing it in vite config doesn't work as the kit plugin includes vite-plugin-svelte without a way to forward them.

It svelte.config.js it works as documented, the config type in kit might need to be updated to include `vitePlugin`

**Comment by dominikg** [comment]
See https://github.com/sveltejs/kit/issues/5485 about inline options in vite config
