### ISSUE TITLE
Migration guide references non-existent type "Load" on "$types"

### ISSUE THREAD

**Issue by JeremyMoeglich** [sveltejs/kit#5914]
### Describe the bug

https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3292693 in #5774 references Load on ./$types but this type doesn't exist, PageLoad exists on ./$types should it be that instead?

### Reproduction

https://stackblitz.com/edit/node-fvjfyj?file=src/routes/+page.ts

Go to /src/routes/page.ts
You will see the error on the import
Module '"./$types"' has no exported member 'Load'.

### Logs

```shell
Module '"./$types"' has no exported member 'Load'.
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22622
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 554.71 MB / 5.95 GB
  Binaries:
    Node: 17.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.450.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22621.1
```

### Severity

annoyance

**Comment by Addeuz** [comment]
Yes it should be `PageLoad` instead.
https://kit.svelte.dev/docs/types#generated-types

**Comment by dummdidumm** [comment]
Thank you for noticing, @Addeuz is right, it should be `PageLoad` (or `LayoutLoad`) instead - updated the migration guide.

**Comment by rudolfbyker** [comment]
I just started a new SvelteKit project today, and it seems that the `PageLoad` type is not generated. This is all I get:

```
import type * as Kit from '@sveltejs/kit';

interface RouteParams extends Partial<Record<string, string>> { nid: string }

export type Errors = undefined;
export type PageData = null;
export type PageServerData = null;
```

Is this a regression?

**Comment by dummdidumm** [comment]
Can't tell without a proper reproduction
