### ISSUE TITLE
Sveltekit 1.0.0-next.406+ (or whichever version uses vite3) seems to have issues with wasm-files in the static/ folder

### ISSUE THREAD

**Issue by quasarchimaere** [sveltejs/kit#5923]
### Describe the bug

Before vite 3 it was possible to load an `wasm` file via a worker (both stored in the static directory)
however, since the upgrade to newer sveltekit versions, the wasm file seems to get corrupted upon loading in the browser (probably happens during the build process already, since dev environment works)

### Reproduction

.

### Logs

```shell
(in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): unknown section code #0x61 @+428023). Build with -s ASSERTIONS=1 for more info.
    at abort (IFCWorker.js:48977:19)
    at IFCWorker.js:49053:15
```

### System Info

```shell
sveltekit
adapter-node
web-ifc-three -> using IFCWorker.js within static/ directory and wasm files which are also in that directory
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
Can you test whether this happens when using Vite directly? https://github.com/sveltejs/kit#bug-reporting

I'm guessing this issue should be filed in the Vite repository instead. We won't look at this and will close it unless there's confirmation this doesn't happen in vanilla Vite

**Comment by quasarchimaere** [comment]
found out what the issue was -> since there is still a base_path issue i need to do some workaround scripting prior to the node server execution (ie: moving some folders/files) sveltekit with vite3 does not have the `build/static` any longer and puts the resources directly into `build` directory, thus i was copying files into a wrong folder
