### ISSUE TITLE
+page.svelte data does not respect setting a default value

### ISSUE THREAD

**Issue by cdcarson** [sveltejs/kit#5939]
### Describe the bug

If one has a `+page.svelte` component it appears to be impossible to set a default value for the `data` property, like this:

```html
<script lang="ts">
  import type { MyPageData } from 'src/lib/types';
  export let data: MyPageData = {
    foo: 'bar'
  };
</script>
```
There are three cases that I've tested:

- A. without a `+page.server.ts` file
- B. with a `+page.server.ts` file that does not include a `load` function (it has a `POST` action.)
- C. with a `+page.server.ts` including a `load` function 

Cases A and B render with `data` being `null`.  C renders, as expected, with whatever one returns from `load`.

I can think of several examples where I'd want to be able to set a default value for `data` in this _simple_ way, rather than having to write a separate function in a potentially additional file.

### Reproduction

https://github.com/cdcarson/sk-load-issue

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 97.16 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.411 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

serious, but I can work around it

**Comment by rmunn** [comment]
This bug only triggers when the prop is named `data`. Rename it to any other name, say `foo` or `quux` or `incomingData`, and the bug does not trigger. Only a prop specifically named `data` appears to trigger the buggy behavior.

**Comment by Conduitry** [comment]
`data` is the only prop that is getting passed in at all now, unless I'm completely misunderstanding the context of this issue. Any other props would always get their defaults, because the framework isn't passing any value into the page component for them.

The solution here, presumably, if this were something we decided to support, would be to make sure we're not instantiating the page component with `data={null}` in these cases, so that the default can be used.

**Comment by cdcarson** [comment]
> Only a prop specifically named data appears to trigger the buggy behavior.

My limited understanding is that +page.svelte will only ever be passed the props `data` and `error`.

> The solution here, presumably, if this were something we decided to support, would be to make sure we're not instantiating the page component with data={null} in these cases, so that the default can be used.

I ran into this trying to port a page to the new router conventions (i.e. trying to analogize my way from existing code rather than starting from scratch or rethinking.) So maybe there's a case to be made for _not_ fixing it. One can just set a default if `data` is `null`.

The case for fixing it would be that it's an anomaly. No other svelte components have this behavior. But then again, no other components are like `+page.svelte`, and `+page.svelte` is a new thing, so I'm fine either way.

@Conduitry you can close this if you want.  Thanks
