### ISSUE TITLE
Structure of /endpoint/__data.json returned from +page.server.js has changed

### ISSUE THREAD

**Issue by infovore** [sveltejs/kit#5950]
### Describe the bug

Data served from an endpoint was also available from `/endpoint/__data.json`. Following the routing overhaul, the structure of this data has changed; it's unclear if this is deliberate or not or if it needs documenting. For instance, in the SvelteKit demo app, available via `create-svelte`, the URL `/todos/__data.json` returns:

```
{
  "type": "data",
  "nodes": [
    {
      "data": null
    },
    {
      "data": {
        "todos": []
      }
    }
  ]
}
```

Previously, it would return:

```
{
  todos:[]
}
```

### Reproduction

Install sample svelte-kit app:

```
yes "" | "$(npm init svelte@next test_app)"
```

run sample app:

```
cd test_app && npm run dev
```

visit `/todos/__data.json` on the appropriate port.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.28 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.12.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
    Safari: 15.6
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
It is deliberate. `__data.json` is no longer a public API - and it was never _really_ public or intended for general use, although the docs didn't really make that clear.

There are no longer references to `__data.json` in the documentation. This is something that can change at any time, or replaced with another mechanism entirely to support serializing more types of data. It's not something we want people to rely on or that we want to document.

**Comment by infovore** [comment]
Yep, that all makes sense - I noticed it had been removed from the documentation, but hadn't read any commentary to that effect so wanted to check in. Thanks.

**Comment by mattpilott** [comment]
@Conduitry whats the right way to refetch load data? For example if i have a +page.svelte and +page.server.js delivering SSR data but then in onMount i want to refetch that data every few seconds how would i do that now that __data.json is unavailable? Really struggling to come up with a solution that doesnt mean duplicating code

**Comment by dummdidumm** [comment]
Sounds like `invalidateAll` could help you

**Comment by mattpilott** [comment]
That does work, i tried the normal invalidate but couldnt get that to work.

```svelte
<script>
   import { onMount } from 'svelte'
   import { invalidateAll } from '$app/navigation'

   export let data

   onMount(async () => setInterval(invalidateAll, 5000))
</script>

<h1>£{data.buy.ounce.toFixed(2)}</h1>
```
