### ISSUE TITLE
Delete todos in example app broken

### ISSUE THREAD

**Issue by HalfdanJ** [sveltejs/kit#5953]
### Describe the bug

In sveltekit 413, the delete method for todos is broken. 

### Reproduction

When clicking delete on a todo, the rest call returns status 400 with body `_method=DELETE is not enabled. See https://kit.svelte.dev/docs/configuration#methodoverride` 

The url requested is http://localhost:5174/todos?_method=DELETE (post request) 

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 119.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.413 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
I can't reproduce this in a fresh project

**Comment by HalfdanJ** [comment]
Weird, me neither now. Must have been some caching teasing me.
