### ISSUE TITLE
Property 'locals' does not exist on type 'LoadEvent' 

### ISSUE THREAD

**Issue by Hycord** [sveltejs/kit#5975]
### Describe the bug

I can access `event.locals` within my `+layout.server.ts` file, and pass down data from it. However I get an error that the properties do not exist? 
If I ignore the error, then it works fine, so just a typescript error but still

```ts

return {
  theme: event.locals.theme
}

```

### Reproduction

Paste the following code into `+layout.server.ts`

```ts

import type { LoadEvent } from "@sveltejs/kit";


export async function load(event: LoadEvent) {
	// const res = await fetch('/api/appeals', {
	//     headers: { Authorization: configurations.devHeader, beta: dev },
	// })
	// const data = await res.json();
	return {
		theme: event.locals.theme
    }
}

```

### Logs

```shell

(parameter) event: LoadEvent<Record<string, string>, JSONObject | null, Record<string, any> | null>
Property 'locals' does not exist on type 'LoadEvent<Record<string, string>, JSONObject | null, Record<string, any> | null>'.ts(2339)

```

### System Info

```shell

System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 23.85 GB / 30.71 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - /snap/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Firefox: 103.0.2

```

### Severity

annoyance

### Additional Information

![image](https://user-images.githubusercontent.com/40705478/185120531-df7888e6-a8c8-4064-90c8-9f45b53d2482.png)

**Comment by sandstromdev** [comment]
The correct type for this is be `ServerLoadEvent`, `Load`. You should probably also be using the generated types in `./$types` (see https://kit.svelte.dev/docs/routing#$types).

`+layout.server.ts`
```ts
import { LayoutServerLoad } from './$types'
export const load: LayoutServerLoad = async (event) => {
  return {
    theme: event.locals.theme
  }
}
```

**Comment by Conduitry** [comment]
Yup, that's not the right type to be using. The previous comment is correct, you should be using `ServerLoadEvent` or, better yet, the generated `./$types`.
