### ISSUE TITLE
Returning location from POST does not set 3xx status code

### ISSUE THREAD

**Issue by sandstromdev** [sveltejs/kit#5976]
### Describe the bug

When returning a `location` path from a `+page.server.ts` sveltekit set status as 200, and does not perform a redirect.

The problem is located in `packages/kit/src/runtime/server/page/index.js` at 81:38

```ts
return redirect_response(status, result.location);
```

where status is not changed from 200 (at 57:5)

```ts
let status = 200;
```

I'd be willing to submit a PR to fix this issue.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-t26lrz?file=src/routes/+page.svelte

The page contains two buttons:
- Submit form with `throw redirect()`
- Submit form with `location`

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 69.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Firefox Developer Edition: 104.0
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-node: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: 1.0.0-next.415 => 1.0.0-next.415 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.8
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Feel free to open a PR! This should probably be a 302

**Comment by Conduitry** [comment]
Especially since it's in response to a POST, we should probably take a stand here and make a conscious decision between 303 and 307, rather than just a 302. A 302 is, in practice, treated as a 303, so I'd be in favor of using a 303.

**Comment by benmccann** [comment]
Looks like this was merged 2 minutes ago, but I do wonder if 307 might be nicer at least in dev mode. When developing multiple apps it's really annoying to have redirects cached

**Comment by Conduitry** [comment]
303 vs 307 is whether the POSTs turn into GETs upon redirection, or whether the new URL is also POSTed to. Neither of them is 301 Moved Permanently.
