### ISSUE TITLE
Spurious prop warnings with `+page.svelte` files

### ISSUE THREAD

**Issue by stephenlrandall** [sveltejs/kit#5980]
### Describe the bug

On each route not using a `load` function, the console has

```
[Warning] <Page> was created with unknown prop 'data' (+page.svelte, line ...)
[Warning] <Page> was created with unknown prop 'errors' (+page.svelte, line ...)
```

These can be removed with the boilerplate

```
export let data;
export let errors;
```

in the `+page.svelte` files for those routes, but ideally the warnings would not be present unless the route has an associated `load` function.

### Reproduction

Launch a SvelteKit app that includes routes which do not explicitly accept `data` or `errors` and check the console.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 25.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/Library/pnpm/node
    npm: 8.12.1 - ~/Library/pnpm/npm
  Browsers:
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.38 => 1.0.0-next.38 
    @sveltejs/kit: next => 1.0.0-next.411 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.8
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This comes down to a warning in Svelte core, which we IMHO could just remove. I also believe there is some (closed?) issue in this repo already noticing the same thing in a different context.

**Comment by sserdyuk** [comment]
The warning is helpful if you accidentally use the wrong binding on a component.

**Comment by benmccann** [comment]
https://github.com/sveltejs/svelte/issues/4652 looks to be the issue in the Svelte repo. If we're going to be removing annoying warnings then I'd also nominate https://github.com/sveltejs/svelte/issues/6325

**Comment by stephenlrandall** [comment]
I agree that the warning is useful in many cases (I've definitely caught a lot of issues thanks to those warnings), but only when I'm intentionally passing props around. If I don't have a `+page.js` in a route, I wouldn't expect `data` or `errors` to be passed in to the route and I wouldn't want to be warned that I'm missing some boilerplate `export let data` line.

**Comment by Rich-Harris** [comment]
Agree, the warning should only appear if we're passing `data` or `errors` and they're not being received

**Comment by charbelnicolas** [comment]
I just upgraded to the new directory based routing and immediately noticed these annoying warnings!

+1 for removing the warnings

**Comment by dummdidumm** [comment]
The problem is - how do we leave the warning in place while silencing it for this use case? There would have to be some kind of runtime code involved. Two possibilities I can think of:
- Svelte exposes some kind of method that says "surpress the warnings of type X" and another one that says "stop surpressing warnings of type X", which we call before and after setting the props
- Svelte exposes some kind of info on its components in dev mode: "these are the props I expect", and SvelteKit's component uses that info to not pass `data`/`errors` in this case

**Comment by Zamiell** [comment]
Hello,

I am trying out Svelte Kit for the first time. Upon running the provided "hello world" application, I am greeted with the spurious warnings on the console as described in the OP, which lead me to wading through this thread & https://github.com/sveltejs/svelte/issues/4652 to try and get a handle on the situation.

This is not a great DX experience for new users. In the first minutes of using Svelte, I want to be building my app, not spending 15 minutes troubleshooting warnings. I'm posting here not to complain about the product, but rather to emphasize the importance of fixing this issue if Svelte is to gain more popularity.

**Comment by aradalvand** [comment]
> Agree, the warning should only appear if we're passing data or errors and they're not being received

@Rich-Harris Perhaps not even in those cases, sometimes you're just populating the data for the layouts to consume, and you don't need it in the page itself. This is actually common, I think.

**Comment by kevinrenskers** [comment]
This got closed a while back but I am still seeing frequent `<Page> was created with unknown prop 'errors'` warnings for pages without a load function.

**Comment by charbelnicolas** [comment]
Yeah, I still get them sometimes when hot reloading too

**Comment by dummdidumm** [comment]
Reopening as they can appear as a result of Vite hot module reload. Not sure how we can silence these except turning on the warning-silence-hack all the time.

**Comment by kevinrenskers** [comment]
> Yeah, I still get them sometimes when hot reloading too

True, it seems limited to HMR.

**Comment by TeamDman** [comment]
Also getting this with the Error page it seems
```
<Error> was created with unknown prop 'data'
<Error> was created with unknown prop 'form'
```

![image](https://user-images.githubusercontent.com/9356891/206651416-a476c3d9-2e31-4d7d-9ed5-395721ab0844.png)

**Comment by sonylomo** [comment]
@TeamDman I'm getting the same error message. Did you find a possible solution?

**Comment by TeamDman** [comment]
Just ignored it for now
