### ISSUE TITLE
Redirects to error pages occur when an expected error is thrown

### ISSUE THREAD

**Issue by theetrain** [sveltejs/kit#5988]
### Describe the bug

Utilizing the `error` helper documented here: https://kit.svelte.dev/docs/load#errors
When I use `throw error(400)` in a server file, its respective page redirects to an error page instead of passing the response successfully.

I expect to be able to handle the response in my `+page.svelte` file, but I cannot. It could be my misunderstanding of the docs, or unintended behaviour of `throw error()`.

### Reproduction

Reproduction demo: https://stackblitz.com/edit/sveltekit-load-errors?file=src%2Froutes%2F%2Bpage.server.js,src%2Froutes%2F%2Bpage.svelte&terminal=dev

Utilizing `error` like so:

**+page.server.js**
```js
import { error } from '@sveltejs/kit';

export function load() {
  throw error(400, 'missing something');

  return;
}
```

**+page.svelte**
```html
<script>
// export let data
import { onMount } from 'svelte'

export let data

let response
onMount(async ()=>{
  try {
    response = await fetch('/')
  } catch (error) {
    console.log('some error')
  }
})
</script>

<p>Returned response is: {JSON.stringify(data)}</p>

<p>Fetched response is: {JSON.stringify(response)}</p>
```

1. Run project and navigate to the root page
2. Observe error page being shown instead of the contents of `+page.svelte`

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.416 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
This is the intended behavior. If you throw an error from a `load` function, an error page gets displayed. You aren't returning any data to pass into the corresponding `+page.svelte`. If you want to display that page but in some sort of error state, that needs to be part of the data returned by `load` and needs to be handled accordingly in `+page.svelte`.
