### ISSUE TITLE
Clarify response vs request headers for the setup.js `getContext` function

### ISSUE THREAD

**Issue by didier** [sveltejs/kit#599]
**Describe the bug**
Whenever the `prepare` function of `src/setup.js` returns anything (headers, etc.), the HTTP endpoint causes an `Error: Transferred a partial file.` This does not happen if the `prepare` function is not present or does not return anything.

**Logs**

There is not much to see here. I've only tested the endpoints using Insomnia, so no browser logs. (Though, I suspect there wouldn't be any aside from the aforementioned partial fire error.)

```bash
yarn run v1.22.5
warning package.json: No license field
$ svelte-kit dev
(node:83958) ExperimentalWarning: The ESM module loader is experimental.
> Listening on http://localhost:3000
```

**To Reproduce**
The issue happens after a fresh install of Kit. My setup options were to disable TS in components, and to use SCSS for preprocessing.

I've made a repo to show exactly where the issue occurs: [@didier/svelte-kit-broken-endpoints](https://github.com/didier/svelte-kit-broken-endpoints). See [`src/setup.js`](https://github.com/didier/svelte-kit-broken-endpoints/blob/main/src/setup.js) for an example.

**Expected behavior**
I would expect the endpoint to send a respond, irregardless of whatever the `prepare` function does and returns.

**Stacktraces**
None, no visible errors occur besides the HTTP client warning me of the `Error: Transferred a partial file`.

**Information about your SvelteKit Installation:**

```bash
System:
  OS: macOS 11.2.3
  CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Memory: 156.12 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh

Binaries:
  Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
  Yarn: 1.22.5 - /usr/local/bin/yarn
  npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Watchman: 4.9.0 - /usr/local/bin/watchman

Browsers:
  Brave Browser: 89.1.21.77
  Firefox: 83.0
  Firefox Developer Edition: 85.0
  Firefox Nightly: 74.0a1
  Safari: 14.0.3

npmPackages:
  @sveltejs/kit: ^1.0.0-next.55 => 1.0.0-next.55 
  svelte: ^3.29.0 => 3.35.0
```

**Severity**
This issue is blocking usage of SvelteKit entirely, as HTTP Endpoints are part of the core functionality.

**Additional context**
I've had contact with @antony about this. Raising the issue here so other contributors can take a look.

**Comment by GrygrFlzr** [comment]
The `prepare` example in the repo *overwrites* the response headers with the request headers, which also includes stuff like `content-length` headers, which I suspect is what is happening considering the `Error: Transferred a partial file.`

Are you able to replicate this *without* overwriting the response headers with the request headers?

**Comment by didier** [comment]
Ah, that is an interesting angle I hadn't yet looked at. That would make sense. I'll try to recreate it as soon as I get the chance. Having said that: if what you mentioned is indeed the reason for this error, I think this could be a useful tip in the docs. Because I would expect returning the arguments to not break the response.

**Comment by didier** [comment]
I've done some more testing. I'm not entirely sure what is going on. 

The following function causes the error, presumably because of content length not matching.
```js
export async function prepare({ headers }) {
  return {
    headers,
  };
}
```

So I tried each incoming header individually. Turns out, when you still return everything like this, nothing breaks.

## Example 1: Return all headers
This was my first approach. Quickly found out this doesn't really matter as its the `header` key of the response that's causing the error.
```js
export async function prepare({ headers }) {

  // Destructure every part of the headers
  const { host, cookie, accept } = headers
  const userAgent = headers['user-agent']
  const contentType = headers['content-type']
  const contentLength = headers['content-length']

  return {
    host,
    cookie,
    userAgent,
    contentType,
    contentLength,
    accept,
  }
}

```

## Example 2: 'Rebuild' header object and return
This example returns the header key in the response just as if you would return it directly. However, this example *does not* break the response. Am I missing something?
```js
export async function prepare({ headers }) {
  // Destructure every part of the headers
  const { host, cookie, accept } = headers
  const userAgent = headers['user-agent']
  const contentType = headers['content-type']
  const contentLength = headers['content-length']

  return {
    headers: {
      host,
      cookie,
      userAgent,
      contentType,
      contentLength,
      accept,
    },
  }
}
```

**Comment by GrygrFlzr** [comment]
In example 2 you are setting the header `contentLength`, not `content-length`, so there is no issue. Change it to `'content-length': contentLength` and you should see the same behavior as the original code.

**Comment by didier** [comment]
Oh, you're totally right. Been a long day 😅. That does indeed replicate the issue. I don't think this is a bug then—though I still think this could be mentioned in the docs, as this can be confusing for new users. Especially when coming from Sapper. Do you agree?

**Comment by GrygrFlzr** [comment]
I've certainly seen this specific mistake crop up a number of times, so it can definitely be a documentation exercise.

**Comment by Rich-Harris** [comment]
Note that `prepare` has been replaced by `getContext`: https://kit.svelte.dev/docs#hooks

**Comment by GrygrFlzr** [comment]
Closing since `getContext` no longer returns a response header, and `handle` takes in a `request` object instead, so there's no longer a header -> header function signature.
