### ISSUE TITLE
Take into account `vite.config.envDir` or provide a `kit.env.dir` option

### ISSUE THREAD

**Issue by iolyd** [sveltejs/kit#5995]
### Describe the problem

It appears that in its current state, the `kit.config` does not allow us to specify a `.env` checkup directory other than the project's root. This can be a bit annoying when working with monorepos where `.env` files can often be defined in a parent folder. Vite's config already provides an `envDir` option covering such cases, yet it is my understanding that it doesn't work with kit. As is, none of the `$env/...` imports seem to include env vars defined in a parent folder pointed to by vite's config.

### Describe the proposed solution

I see two avenues:

1- take into account `vite.config.envDir`, or;
2- provide a `kit.env.dir` option to stay more in line with kit's own handling of `kit.env.publicPrefix`.

### Alternatives considered

Make developpers copy the necessary `.env` files when they reside outside the kit project's root.

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
@Rich-Harris 

Happy to tackle this one, since it's part of my "pet project"... I'd probably vote that we have our own config for it (`config.kit.env.dir` seems fine).
