### ISSUE TITLE
Sync latest code from Sapper

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#6]
E.g. compare https://github.com/sveltejs/kit/tree/master/packages/kit/src/client vs https://github.com/sveltejs/sapper/tree/master/runtime/src/app

We'll have to come up with a strategy for this because there have been a lot of fixes and improvements recently. I can slow down on merging Sapper stuff if it makes it easier to manage

**Comment by Rich-Harris** [comment]
pretty sure we can close this now, i'm sure we'll find out in due course if not

**Comment by benmccann** [comment]
I think we almost have all of this done. The one I think we haven't yet is https://github.com/sveltejs/sapper/pull/1498 - store the current error in the page store to allow the layout to know whether the current page is an error page

**Comment by Rich-Harris** [comment]
Given that it only applies to the root layout I think I'd prefer that we pass the error (and possibly status) as a prop. It doesn't belong on the page store

**Comment by benmccann** [comment]
Ok. Created a separate issue for that (https://github.com/sveltejs/kit/issues/598) and will close this
