### ISSUE TITLE
Respect existing deploy config

### ISSUE THREAD

**Issue by lukeed** [sveltejs/kit#60]
The `adapter-vercel` package completely obliterates the existing `vercel.json` file.

Instead it should be write the necessary values into the JSON object, only after checking that the necessary keys/values don't already exist.

Option B is to add some kind of `adapter-vercel` config or CLI flag that effectively acts like `--skip-config`

**Comment by Rich-Harris** [comment]
Is this still an issue with the current `adapter-vercel`?

**Comment by benmccann** [comment]
I would guess so. I haven't used it, but don't remember anything being committed that would change it

**Comment by antony** [comment]
Yeah - I don't think we do any config merging as I remember it being a bit difficult. I do remember talking to @leo about having a sort of internal config which we could build and then the user's `vercel.json` would just be overrides. I don't know if this is implemented yet, but if not, we could do some config merging.

**Comment by Rich-Harris** [comment]
i think we can close this now, since we don't write a `vercel.json`. reopen if i'm mistaken

**Comment by kvn-shn** [comment]
@Rich-Harris Still relevant for e.g. Netlify Adapter I guess. Because there the adapter overrides the potentially already existing `_redirects` file. The `_redirects` has a higher priority than `netlify.toml`, so custom redirects currently don't work (see discussion at #930).
