### ISSUE TITLE
Private `.env` variables are accessible in client-side code

### ISSUE THREAD

**Issue by iolyd** [sveltejs/kit#6000]
### Describe the bug

Variables defined in a `.env` under a name that is not prefixed with `kit.env.publicPrefix` are still available in client-side code.

### Reproduction

```html
<!-- Some page.svelte or layout.svelte file -->
<script>
  import { A_PRIVATE_VAR } from '$env/static/private';
  
  console.log(A_PRIVATE_VAR);
</script>

...
```

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 227.32 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.17.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.1
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: 1.0.0-next.416 => 1.0.0-next.416 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.8
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
Is this in dev mode only, or also in production builds? I recall some discussion when this feature was being implemented something about not being able to properly traverse the module graph in dev mode, but that this would still be enforced in prod builds.

**Comment by iolyd** [comment]
Ah, I've only tested it in dev mode for now as I'm still in the process of migrating things and can't do successful builds at the moment. I can try with doing a prod build of a small reproduction project if you would prefer.

**Comment by Rich-Harris** [comment]
It's supposed to happen in dev mode too, for direct imports. The case we have to give up on is if you dynamically import a module that dynamically imports a module that's supposed to be inaccessible, which isn't the case here. It looks like we (or I, probably) just broke it

**Comment by iolyd** [comment]
Just tested with @ssbm-oro 's [quick repro](https://github.com/sveltejs/kit/issues/6001) and it's broken in prod builds too.

**Comment by jr-trinium** [comment]
In SK 1.0.0-next.430, importing `$env/dynamic/private` and `$env/static/private` in +page.js|ts and +layout.js|ts now trigger dev mode errors, but you can still import and use them in +page.svelte and +layout.svelte files.  Only when you do a prod build does it then show errors when importing `$env/*/private` in page and layout svelte files.  Is that intentional, or should that also be caught in dev mode?

**Comment by jr-trinium** [comment]
As of SK 1.0.0-next.440, all imports of `$env/dynamic/private` and `$env/static/private` in client-side code, `+page.js|ts|svelte` and `+layout.js|ts|svelte`, seem to be caught in dev mode.  Perhaps it worked before and my .svelte-kit folder needed to be resynced?
