### ISSUE TITLE
`+layout.server.ts` doesn't run if a route doesn't match

### ISSUE THREAD

**Issue by juanvillacortac** [sveltejs/kit#6010]
### Describe the bug

I just just notice that if I navigate to a non-existent route, like `/asdasdasd` and I have a `+layout.server.ts` and a `+layout.ts`, `+layout.server.ts` is not executed and `data` prop on `LoadEvent` of the `load` function of `layout.ts` is not populated. This does not happen if I manually throw an `error(404)` on any of the layout files, only happen when a 404 is thrown because the route does not match with the filesystem router.

### Reproduction

If for example I have a `+layout.server.ts` like:

```ts
import { fetchLayoutData } from '$lib/utils/layout.server'
import type { LayoutServerLoad } from './$types'

export const load: LayoutServerLoad = async ({ locals, url }) => {
  const { notFound, layoutData } = await fetchLayoutData(
    { url, fetch },
    locals.layoutType
  )

  return {
    userAgent: locals.userAgent,
    host: locals.host,
    fullHost: locals.fullHost,
    userId: locals.userId,
    layoutData,
    notFound,
  }
}
```

And a `+layout.ts` file like:

```ts
import { error } from '@sveltejs/kit'
import type { LayoutLoad } from './$types'

export const load: LayoutLoad = async ({ data }) => {
  // `data` doesn't get populated when this issue happen, is `null` in this case
  const { layoutData, notFound } = data
  let layoutComponent: any

  if (notFound) {
    // this 404 doesn't trigger this issue, so everything is fine in this case
    throw error(404)
  }

  switch (layoutData?.layout || 'app') {
    case 'app':
      layoutComponent = (await import('$lib/__layouts/AppLayout.svelte'))
        .default
      break
    case 'store':
      if (!data.layoutData?.store) {
        layoutComponent = (await import('$lib/__layouts/AppLayout.svelte'))
          .default
      } else {
        layoutComponent = (
          await import('$lib/__layouts/DecalshutLayout.svelte')
        ).default
      }
      break
  }

  return {
    ...data,
    layoutComponent,
  }
}
```

And If I navigate to a non-existent route, I found that `+layout.server.ts` doesn't run, including the fact than a simple `console.log` in that file does not work.

### System Info

```shell
System:
    OS: Linux 5.17 undefined
    CPU: (4) x64 AMD A10-7300 Radeon R6, 10 Compute Cores 4C+6G
    Memory: 1016.16 MB / 6.76 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Firefox: 99.0
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.63 => 1.0.0-next.63 
    @sveltejs/adapter-cloudflare: ^1.0.0-next.18 => 1.0.0-next.19 
    @sveltejs/adapter-netlify: ^1.0.0-next.55 => 1.0.0-next.56 
    @sveltejs/adapter-node: 1.0.0-next.82 => 1.0.0-next.82 
    @sveltejs/adapter-static: ^1.0.0-next.29 => 1.0.0-next.30 
    @sveltejs/adapter-vercel: 1.0.0-next.66 => 1.0.0-next.66 
    @sveltejs/kit: 1.0.0-next.419 => 1.0.0-next.419 
    @sveltejs/svelte-virtual-list: ^3.0.1 => 3.0.1 
    svelte: ^3.49.0 => 3.49.0 
    vite: 3.0.2 => 3.0.2
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
@juanvillacortac Create a simpler repro and put it up as a public git repo please. It's hard to create a usable context from your description and two verbose snippets.

**Comment by benmccann** [comment]
Why would you expect `+layout.server.ts` to be run? What are you trying to do inside it? Can you not use `handle`?

**Comment by PatrickG** [comment]
> Why would you expect `+layout.server.ts` to be run? What are you trying to do inside it? Can you not use `handle`?

I expect it to run as well. When the `load` function in  `+layout.js` runs, it makes sense that the corresponding `load` function in `+layout.server.js` to run as well.
`+layout.js` may depend on data from `+layout.server.js`

**Comment by dummdidumm** [comment]
I can't reproduce this, please provide a proper minimum reproduction (on stackblitz for example).

**Comment by juanvillacortac** [comment]
Right now I'm on mobile, so I'm gonna sumbit a repro repo in the course of the day. My project is a multitenant marketplace like shopify, with custom domains and subdomains. On the `+layout.server.ts` `load` function I fetch the corresponding shop and respective layout data, and I send that data to `+layout.ts` `load` function, where I dinamically import the correct Svelte layout component file for render in `+layout.svelte` with a `svelte:component`. Everything is working in this workflow, but when I navigate to a route that should throw a 404, I notice that `+layout.server.ts` does nothing, but `+layout.ts` and `+layout.svelte` doesn't have this issue. I think that this bug occurs on simple projects too.

**Comment by juanvillacortac** [comment]
`data` on the `+layout.ts` `load` function is `null` when the bug happens, `data` should be populated by the `+layout.server.ts` counterpart.

**Comment by CaptainCodeman** [comment]
I also need this for the same multi-tenancy reason - even if the page is an error it needs to load the contextual data and even though a sub-route might not have matched if a layout route _did_ then it's a surprise and problematic if it doesn't trigger.

**Comment by juanvillacortac** [comment]
I'm making a reproduction here: [sveltekit-issue-6010](https://stackblitz.com/edit/sveltekit-issue-6010), but doesn't happens in any way, only happens on my repo, so I'm gonna to temporary close this issue. Thanks.

**Comment by nitroboy720** [comment]
Did you figure out what caused the problem? I am running into the same issue
