### ISSUE TITLE
load parent function doesn't infer LayoutData from named layout

### ISSUE THREAD

**Issue by raythurnevoid** [sveltejs/kit#6013]
### Describe the bug

LayoutLoad interface doesn't include named layout's LayoutData in `parent()` function

### Reproduction

With this files structure
![image](https://user-images.githubusercontent.com/53383860/185288017-0c93e3fb-00fe-456d-b1be-61be36fa01dc.png)

and this named layout `layout-customer.ts`
![image](https://user-images.githubusercontent.com/53383860/185288465-00f64e5f-b8be-4ede-830b-1c47677d32c2.png)

I expect `layout.ts` to get LayoutData from layout-customer but it doesn't
![image](https://user-images.githubusercontent.com/53383860/185288257-95844267-30ee-408e-871e-95bee4f5f8d9.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 7.55 GB / 31.42 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: 1.0.0-next.418 => 1.0.0-next.418
    svelte: ^3.49.0 => 3.49.0
```

### Severity

annoyance

### Additional Information

To fix the value `Record<never, never>` in the related `./$types`
![image](https://user-images.githubusercontent.com/53383860/185289162-c5a8dddb-2574-496b-bbc4-87e8a19b98a2.png)

should become `LayoutData.customer`
![image](https://user-images.githubusercontent.com/53383860/185289099-9114e8c2-6336-4e37-9ec4-ee801367cda0.png)

**Comment by z7f010** [comment]
Dhl
