### ISSUE TITLE
new svelte-package command doesn't generate .svelte-kit folder

### ISSUE THREAD

**Issue by agufagit** [sveltejs/kit#6024]
### Describe the problem

For a pure package project, new svelte-package command doesn't generate .svelte-kit folder, which causes typescript build error:

Cannot read file "/svelte/.svelte-kit/tsconfig.json'

### Describe the proposed solution

svelte-package command generate .svelte-kit folder or at least tsconfig.json file

### Alternatives considered

Now I have to add a dummy app.html to src folder, run vite build first before svelte-package.  It wasn't development problem, but CI build problem.

### Importance

nice to have

**Comment by dummdidumm** [comment]
Please provide a reproduction. It sounds like you reference the generated SvelteKit tsconfig from your own tsconfig. If you declare a dependency on the generated config in there, that's on you to ensure SvelteKit is present. You are free to omit this if you use svelte-package on its own.

**Comment by agufagit** [comment]
yeah, i copied fields over to local tsconfig.json, and it works, now for a typescript lib with only .ts and .svelte files, package.json only needs:

```
"devDependencies": {
  "@sveltejs/package": "1.0.0-next.1",
  "svelte": "^3.44.0",
  "svelte-preprocess": "^4.10.6",
  "svelte2tsx": "^0.5.13",
  "typescript": "^4.7.4",
  "vite": "^3.0.0"
},
```

Thank you
