### ISSUE TITLE
Having a + (plus) sign in assets’ paths potentially breaks SvelteKit in some server environments (PHP)

### ISSUE THREAD

**Issue by malinowskip** [sveltejs/kit#6029]
### Describe the bug

I have encountered a scenario in which assets generated by SvelteKit can’t be imported by the app due to the `+` (plus) sign being in the generated paths (after the routing update).

I have a setup in which a few pages of my Laravel app are generated by `adapter-static`. In production, assets would be served by Nginx, but the development environment relies on the built-in PHP server. After upgrading SvelteKit, I started getting weird redirects for all assets whose paths contained the `+` (plus) sign, e.g. `+page-3508b0bd.css`. It turns out that the PHP server treats the `+` (plus) character as a space ([source](https://stackoverflow.com/a/2671854/13414081))

I know it’s technically fine to use an unescaped `+` sign in a path, but it seems there might be edge cases where this causes problems.

### Reproduction

Serve a statically-generated SvelteKit app (post-routing update) using the built-in PHP server.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 91.08 MB / 16.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Edge: 104.0.1293.54
    Firefox: 104.0
    Firefox Developer Edition: 104.0
    Safari: 15.6
  npmPackages:
    @sveltejs/vite-plugin-svelte: 1.0.0-next.41 => 1.0.0-next.41
    svelte: ^3.49.0 => 3.49.0
    vite: 2.9.5 => 2.9.5
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
This is essentially the same issue as https://github.com/sveltejs/kit/issues/5843

**Comment by Conduitry** [comment]
Yup I think we can close this in favor of #5843. The solution will presumably be the same.
