### ISSUE TITLE
Cannot set set-cookie response headers multiple times

### ISSUE THREAD

**Issue by SylvainGarrigues** [sveltejs/kit#6032]
### Describe the bug

Since the `setHeaders` takes a POJO and also checks that a response header as not been already set, one cannot set multiple cookies with multiple `set-cookie` headers. 

### Reproduction

Source code for `setHeaders` checks whether an header is already been set, so can’t even call it multiple times.

### System Info

```shell
Any system
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
`set-cookie` is a special case because it's the only header that allows an array input through the `setHeaders` method. I'd say it's sensible to support that use case and merge the arrays and check no entry appears twice.

**Comment by Conduitry** [comment]
If this is referring to the `load` argument `setHeaders`, the docs do already call that out as a specially handled case https://kit.svelte.dev/docs/load#input-methods-setheaders - I guess it's not actually working that way?

**Comment by dummdidumm** [comment]
You are right, then it's a bug 😄

**Comment by SylvainGarrigues** [comment]
My bad, set-cookie is indeed handled as a special case correctly, leading in multiple set-cookie being set. Sorry for the annoyance.

**Comment by Conduitry** [comment]
It's good that the array version is working, but the docs do say that you should be able to call it multiple times as well. Reopening.

**Comment by SylvainGarrigues** [comment]
As far as I am concerned, not being able to call it multiple times is not an issue (I prefer the array version), and we could just fix the doc :) But it's not my call to decide. Thanks anyway for your very prompt feedback.
