### ISSUE TITLE
Can't navigate away after hitting error page

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/kit#604]
**Describe the bug**

1. setup an error page
2. navigate to localhost:3000/foobar and see the error page
3. try to click any links to navigate to a different page,
4. see the error page persist

see 40 second bug report: https://loom.com/share/1c2706a6904b4b4fb506d8510b97826f

**To Reproduce**

repo: https://github.com/sw-yx/sveltekit-errornavigation-bugreport

40 second bug report: https://loom.com/share/1c2706a6904b4b4fb506d8510b97826f

**Expected behavior**

it should navigate away nicely to the new page

**Stacktraces**

when i navigate to the new page i get this error in the browser console

<details>
  <summary>Stack trace</summary>

```
start.js:429 Uncaught (in promise) TypeError: Cannot read property 'path' of null
    at Renderer.notify (start.js:429)
    at Router._navigate (start.js:191)
    at start.js:117
```

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

```

  System:
    OS: macOS 11.0.1
    CPU: (8) x64 VirtualApple @ 2.50GHz processor
    Memory: 28.27 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 84.0.2
    Safari: 14.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.55 
    svelte: ^3.29.0 => 3.35.0 

```

- Your browser: chrome

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): N/A

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

minor

**Comment by mcdba** [comment]
confirm.
After $error page all real page link return error in console + continue show $error page

**Comment by legowhales** [comment]
I confirm, I have the same error. 
And for me, the issue seems to be within the navigator store : `this.current.page` does not exist anymore, after navigating to an error page.

**Comment by benaltair** [comment]
Confirmed. The path in the address bar changes, but no navigation occurs https://github.com/bahaistudies/conference/issues/34

Must be an issue with the local router?

**Comment by Rich-Harris** [comment]
Unclear when this was fixed, but apparently it was!

**Comment by janosh** [comment]
Not fixed for me. Still experiencing this issue with `@sveltejs/kit@1.0.0-next.120` and `svelte@3.38.2`.

**Comment by janosh** [comment]
Maybe there are cache issues involved? In any case, combing back to it now, the problem seems to have disappeared.
