### ISSUE TITLE
Support relative base path in prerendered files

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#6053]
### Describe the problem

I need to inject asset like ` <link rel="icon" type="image/png" sizes="16x16" href="/pwa/favicon-16x16.png">` in my app.html template

Unfortunately the website will be hosted in different configuration (in a sub folder or at root, see https://github.com/sveltejs/kit/issues/595 for a similar idea

I would like to be able to have that URL relative and so would need this generated index.html in sub folder to correctly prepend sufficient  number of `../` to get to the correct resource

### Describe the proposed solution

Solution :

allow app.html template to use `%sveltekit.base%` that get transformed into `"../../"` in  `demo/test/index.html` but `"../"` in `test2/index.html` and `""` in the root index.html

### Importance

i cannot use SvelteKit without it

**Comment by Rich-Harris** [comment]
It sounds like you want to use `%sveltekit.assets%`?

**Comment by Rich-Harris** [comment]
https://github.com/sveltejs/kit/blob/4ef2f050f1711462d9962d2f1725c9d4b38fe948/packages/create-svelte/templates/skeleton/src/app.html#L3-L8

**Comment by wighawag** [comment]
From the doc:

```
assets — an absolute path that your app's files are served from. This is useful if your files are served from a storage bucket of some kind
```

It seems to require it to be an absolute path. For my use case, all assets live under the sub folder (which is not predictable) the website lives on

**Comment by Rich-Harris** [comment]
If `paths.assets` is provided then %sveltekit.assets% will be equal to it, yes. If not, then `%sveltekit.assets%` is a relative path to `paths.base`. I've opened a PR to clarify the docs: https://github.com/sveltejs/kit/pull/6074
