### ISSUE TITLE
Migration tool feedback

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#6059]
### Describe the bug

Three issues I noticed that may be able to be automatically migrated:
- typo `+page.server.js` vs `+page.js` https://discord.com/channels/457912077277855764/571775594002513921/1009951261279387781
- it could probably migrate `/** @type {import('@sveltejs/kit').PageLoad} */` to `/** @type {import('./$types').PageLoad} */`
- `fetch` wasn't added in `load` so I ended up using global fetch accidentally. not the worst though because I got a console warning about that

### Reproduction

noticed when working on https://github.com/sveltejs/sites/pull/371

### System Info

```shell
n/a
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
> fetch wasn't added in load so I ended up using global fetch accidentally. not the worst though because I got a console warning about that

Where did that happen specifically? AFAIK nothing is removed/added to the `load` function, so this was likely an existing bug

> it could probably migrate /** @type {import('@sveltejs/kit').PageLoad} */ to /** @type {import('./$types').PageLoad} */

I'm hesitant to do this, because people could have a reason for this. We don't know if they use TypeScript at all (or rather, have TypeScript in their package.json) in this case; if they don't the `$types` aren't generated.

**Comment by benmccann** [comment]
The `fetch` thing happened several places. It looks like you're right about it being an existing bug: https://github.com/sveltejs/sites/blob/1c83a81d3957812a2986c6c50667d3cfca790980/sites/svelte.dev/src/routes/examples/__layout.svelte#L5

I'm not sure I understand what you were suggesting about the types migration. I assumed if they already had a type declaration then they were using type checking, but it sounds like they could have that comment without TypeScript installed which would cause issues if we were to automatically migrate?

Thanks for fixing the typo and reviewing this issue!
