### ISSUE TITLE
Windows: css not loaded on navigation

### ISSUE THREAD

**Issue by aloker** [sveltejs/kit#606]
**Describe the bug**
When navigating from one page to another, the css of the second page is not loaded. This only happens when building the app on Windows, on Linux (WSL2 on Windows), the css file is correctly loaded.

I've created a simple repo for reproduction: https://github.com/aloker/svelte-kit-issue-load-on-nav

First page:
![image](https://user-images.githubusercontent.com/140714/112210270-c52c8680-8c1a-11eb-95aa-d95136467437.png)

A click on "To page 2" shows this on WSL2:
![image](https://user-images.githubusercontent.com/140714/112210480-06249b00-8c1b-11eb-8497-705b4c880a3f.png)
Network requests (notice the css for page2 at the enc):
![image](https://user-images.githubusercontent.com/140714/112210581-2c4a3b00-8c1b-11eb-929c-a175c2f80390.png)

And this on Windows (missing the styling):
![image](https://user-images.githubusercontent.com/140714/112210417-f442f800-8c1a-11eb-999e-e52145e15f34.png)
Network requests (no css for page2):
![image](https://user-images.githubusercontent.com/140714/112210645-3d934780-8c1b-11eb-8e98-fc10960ec97f.png)

**Logs**
There are no errors in the console

**To Reproduce**
- Checkout https://github.com/aloker/svelte-kit-issue-load-on-nav
- npm install && npm run build && npm start
- Open http://localhost:3000 in browser, then navigate to page2 by clicking on the link
- Compare different output on Linux and Windows

**Expected behavior**
CSS files should be loaded for pages 

**Information about your SvelteKit Installation:**

Windows:
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 18.54 GB / 31.81 GB
  Binaries:
    Node: 14.16.0 - c:\tools\node\node.EXE
    Yarn: 1.22.10 - c:\tools\node\yarn.CMD
    npm: 7.6.3 - c:\tools\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.57)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.55
    svelte: ^3.29.0 => 3.35.0

Linux:
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 23.83 GB / 24.91 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.10 - /mnt/c/tools/node/yarn
    npm: 7.7.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.55
    svelte: ^3.29.0 => 3.35.0

Tested on latest Firefox, Chrome and Vivaldi browsers

Tested with node and static adapters with same result.

**Severity**
Show stopper for pure Windows development, although when using WSL2 it works fine.

**Comment by stephane-vanraes** [comment]
I am running into a similar issue after build on a dockerized linux instance

**Comment by Kapsonfire-DE** [comment]
In fact, the SSR version works. The CSS is injected on SSR request. (navigate to page2 and reload browser)
But on the client module code, the CSS is never mentioned/injected.

**Comment by stephane-vanraes** [comment]
As a potential workaround for this you can extract all the css, bundle it up and serve it statically:

in `svelte.config.js`

```js
const css = require('rollup-plugin-css-only');

module.exports = {
   kit: {
     vite: {
        plugins: [
           css({ output: 'bundle.css' })
	]
     }
  }
}
```

and to serve it, in `app.html` add a reference to the header

```html
<link rel="stylesheet" href="/./_app/bundle.css">
```

**Comment by frederikhors** [comment]
It works with v1.0.0-next.65. From v66 it doesn't.

**Comment by frederikhors** [comment]
This is the only commit between 65 and 66: https://github.com/sveltejs/kit/commit/d9ce2a2dd46370442288cb43667d2694c8150fe9

**Comment by frederikhors** [comment]
It works until v70.

These are the commits between 69 and 70:

- https://github.com/sveltejs/kit/commit/6ecfa2c3a6f8c1fe612759ac9baf5faf8887b5a0
- https://github.com/sveltejs/kit/commit/6d9f7b1856dd1979934cf09aa8cef223a456bb0b

Perhaps the fault of the latter.

**Comment by frederikhors** [comment]
It works today with 79.

I think we can close this, @aloker.
