### ISSUE TITLE
Local fetch from index.svelte's load function fails on server

### ISSUE THREAD

**Issue by alecglassford** [sveltejs/kit#607]
**Describe the bug**

In my project's root-level `index.svelte`, `fetch` to a local resource (endpoint) within the load function returns 404 even though the resource exists. This only occurs when the server is trying to render the page; if I navigate to my project's homepage from another page, the client-side fetch works fine and the page loads as expected.

Excerpt:

```
<script lang="ts" context="module">
  import type { Load } from "@sveltejs/kit";

  export const load: Load = async function load({ fetch }) {
    const res = await fetch("/post-list.json");
    console.log(res.status);
    ...
  }
</script>
```

--> logs 404, even though `/post-list.json` (from `post-list.json.ts` endpoint) renders just fine when you navigate to it directly (or load it from other pages).

This issue occurs with `@sveltejs/kit@1.0.0-next.55` but not when I downgraded to `@sveltejs/kit@1.0.0-next.54`; I think the root cause was introduced in #583 and specifically I think it's coming from https://github.com/sveltejs/kit/blob/8a88fad3118a7ddec3ef6728cc1b5a74fc18e0f7/packages/kit/src/runtime/server/index.js#L30-L38

`options.initiator` in this case seems to correspond to the `index.svelte` route, which is the first route that gets checked, so we get 404 immediately (before other routes are checked); this problem seems like it could occur with fetches from other routes, but I guess I've noticed it here because `index.svelte` is the first route listed in the manifest.

**To Reproduce**

Use `@sveltejs/kit@1.0.0-next.55` (issue does not occur with `@sveltejs/kit@1.0.0-next.54`).

1. Create a new project (with TypeScript) using `npm init svelte@next`
2. Replace the contents of `src/routes` with these 3 minimal files: https://gist.github.com/alecglassford/f1498cc6af3d2eb90ed5eb0940ff3024
3. Run `npm run dev` and navigate to `localhost:3000`. You'll see `404`.
4. Navigate to `localhost:3000/other` and then click the link to go to the homepage. You'll now see 200.

**Expected behavior**
Fetch does not 404 when endpoint exists.

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

    ```
      System:
        OS: macOS 11.2.3
        [omitted]
      Binaries:
        Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
        npm: 7.6.3 - ~/.nvm/versions/node/v14.16.0/bin/npm
      Browsers:
        [omitted]
      npmPackages:
        @sveltejs/kit: ^1.0.0-next.55 => 1.0.0-next.55 
        svelte: ^3.29.0 => 3.35.0 
    ```

- Your browser: Firefox

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): static (but the reproduction example uses node)

**Severity**

Can't build the site, and things aren't loading properly on the dev server Somewhat severe.

**Comment by Rich-Harris** [comment]
Thanks — your diagnosis was spot on. Fixed in #615
