### ISSUE TITLE
Load function called twice when using sveltekit:prefetch (by design?)

### ISSUE THREAD

**Issue by aloker** [sveltejs/kit#609]
**Describe the bug**

I'm not sure whether this is by design or a bug.

I have a page that load data in its load function and a link to this page with sveltekit:prefetch. The load function calls some API using fetch. As soon as I hover over the sveltekit:prefetch, the load function of the target page is called, invoking fetch. Then, when I click on the link and the actual navigation takes place, the load function is called again including the fetch calls. 

To me this seems to defeat the purpose of prefetching in the first place (at least partially - the page script is of course prefetched, which is beneficial for sure).

**Logs**
![loading-twice](https://user-images.githubusercontent.com/140714/112222040-7d146080-8c28-11eb-9064-4fdd7b8aab07.gif)

**To Reproduce**

- Pull https://github.com/aloker/svelte-kit-issue-duplicate-data-load
- npm install && npm dev
- Open browser and watch the network/console tap
- Hover over "Sunrise API" => sunrise page is loaded and load function is called
- Click on "Sunrise API" => load function is called again

**Expected behavior**
Load should only be called once.

**Information about your SvelteKit Installation:**

```
System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 22.28 GB / 24.91 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.10 - /mnt/c/tools/node/yarn
    npm: 7.7.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.55
    svelte: ^3.29.0 => 3.35.0
```
Tested in Chrome and Firefox (latest)

**Severity**
Medium, mostly a performance issue - or by design.

**Comment by Rich-Harris** [comment]
yep, this is a bug, and one we should prioritise a fix for. tracked at #545, so I'll close this as a duplicate

**Comment by rawasaditya** [comment]
I still see this issue
