### ISSUE TITLE
static private and static public env variables are both undefined

### ISSUE THREAD

**Issue by pbvahlst** [sveltejs/kit#6094]
### Describe the bug

When importing `$env/static/private` `$env/static/public` both are `undefined` further more there seem to be a problem with `$env/dynamic/private` on windows (related to #5941 ?) where it always is an empty object.

### Reproduction

https://stackblitz.com/edit/svelte-kit-i2grct?file=src%2Fhooks.js

### System Info

```shell
stackblitz...
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs/modules#$env-static-private For static private and public env vars, the export is the name of the variable, not `env`.

**Comment by bmccorm2** [comment]
@Conduitry - i get a typescript error when i import variables like this.  Any way around this?

`Module '"$env/static/public"' has no exported member 'PUBLIC_BASE_URL'.`
