### ISSUE TITLE
relationship to svelte-hmr

### ISSUE THREAD

**Issue by dominikg** [sveltejs/kit#61]
Properbly not the right repo to raise this but I thought you should be aware of some delicate dependency setup right now

- kit depends on snowpack plugin svelte which depends on svelte-hmr
- kit and svelte-hmr depend on svelte
- svelte-hmr needs to use svelte internals to work correctly

Changes to svelte can break svelte-hmr (https://github.com/rixo/svelte-hmr/issues/17), which in turn breaks the snowpack plugin and then kit. 

Thoughts:
At least there should be a testsuite covering hmr working correctly.
At best svelte-hmr moves closer to svelte domain or in the long run have it integrated in the compiler?

cc @rixo

**Comment by benmccann** [comment]
I think the original issues raised here have been somewhat ironed out or are no longer relevant since switching to Vite, so I'll go ahead and close this, but of course feel free to let us know if you have more questions
