### ISSUE TITLE
Use current history state for initial route

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/kit#610]
**Is your feature request related to a problem? Please describe.**
When using `history.state` in your app, the current state is overwritten when doing a page refresh (F5).
The `sveltekit:scroll` property is also overwritten.

**Describe the solution you'd like**
Change [this line](https://github.com/sveltejs/kit/blob/a1a6937c33bdff68c898567d8675d75114acf958/packages/kit/src/runtime/client/router.js#L129)
```diff
-		this.history.replaceState({}, '', location.href);
+		this.history.replaceState(history.state || {}, '', location.href);
```

Maybe it would be good [here](https://github.com/sveltejs/kit/blob/a1a6937c33bdff68c898567d8675d75114acf958/packages/kit/src/runtime/client/router.js#L188) too.

**Describe alternatives you've considered**
None.

**How important is this feature to you?**
Not unimportant

**Comment by benmccann** [comment]
Sounds reasonable to me

**Comment by babichjacob** [comment]
So that someone tackling this knows what to look out for, can you clarify exactly what issues arise or what features (so to speak) are missing from the current state of things?

**Comment by PatrickG** [comment]
> So that someone tackling this knows what to look out for, can you clarify exactly what issues arise or what features (so to speak) are missing from the current state of things?

If you have a route that has enough content, so that the page can be scrolled:
1) scroll a down a bit (`history.state` should have a `sveltekit:scroll` property now)
2) hit F5 (`history.state` is undefined now)
3) navigate to a different page and back with the browser back button
4) the page does not scroll to the previous scroll position anymore
