### ISSUE TITLE
Simplify client/server communication by transparently calling backend endpoints as functions

### ISSUE THREAD

**Issue by epavanello** [sveltejs/kit#611]
As a full stack developer I often come across the redundancy of define an API and call it from the frontend, always with the same steps:
- write the api inside a function
- Map that function with an endpoint name under expressjs
- call it from the client with a fetch call
- parse the json response
- grab errors
- consume the response with another function on the client side

Recently I developed a library that manage this problem by a generator and a proxy that allow you to write only the first and the last step. Here the package [no-more-rest](https://github.com/epavanello/no-more-rest) to understand how it works.

The philosophy behind svelte-kit seems to meet with this need to simplification, and I'd like to know if one pull request to this repo for to try to manage this case can be well accepted.

The idea for that feature is to detect when you import an exported API (a file that match with endpoint pattern *.json.{js|ts}) into a svelte component and proxy that function that behind the scene call the remote endpoint and simplifies all redundancies.

In this way you can define your APIs as exported functions, then you can import it in a svelte component and consume it like simple functions that returns promises of json responses.

**Comment by antony** [comment]
This is a nice idea, thought it does somewhat remind me of Enterprise Java Beans. I think it'd be a nice thing for the integrations project / on the community site, however I don't believe that it's something we would want to implement into core at this time, since it's quite a deviation from 99.9% of use-cases.

**Comment by saikatdas0790** [comment]
Can we please reconsider this? As a later feature? 
Right now, i'm feeling this same pain more and more as i'm choosing to write rest endpoints that provide the data for my pages and all the endpoints and fetch calls on the pages have the same boilerplate-y structure.
- create the verbose fetch request with the same headers
- on the endpoint, verify the user's auth token
- verify if parameter/body present else return 4xx code
- execute db/api logic
- return data in a verbose response object
- client side, parse the fetch response after the .json() call and have error checking logic

It would be so much easier if this were all abstracted away and all we needed to do was make a call and get JSON back

**Comment by antony** [comment]
I've not unconsidered it, it just isn't a common enough use-case that we would push people into using it.

Svelte tries to allow the user to do things in the way they would prefer, by being flexible and unopinionated.

Blessing and baking in a specific way of handling crud that only one user has ever requested goes against that principle.

It would make a great community supported module. Feel free to author it, and if we find that 95% of users want it, then we can consider it for inclusion in core.
