### ISSUE TITLE
Seeing a lot of this error: "TODO render fallback error page"

### ISSUE THREAD

**Issue by kristjanmar** [sveltejs/kit#6112]
### Describe the bug

I'm running SvelteKit in production on a site that gets over 100K pageviews per day, so I am catching a lot of errors that might be hard to spot otherwise.

One error that is showing up constantly after upgrading to the new routing system is "TODO render fallback error page".

According to my logs, over 0.1% of all users are getting this error. Most of them are using Chrome 102-104 or a Chromium browser like Edge.

It appears to come from runtime/client/client.js and the "load_route" function.

Almost all of my pages use +page.server.ts to return data to the user, so I'm assuming that there is something failing when users are client-side navigating attempting to fetch the __data.json for the page.

### Reproduction

Unable to reproduce but it's occurring for over 0.1% of users.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 49.86 GB / 63.91 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.64 => 1.0.0-next.64
    @sveltejs/kit: 1.0.0-next.427 => 1.0.0-next.427
    svelte: ^3.49.0 => 3.49.0
    vite: ^3.0.9 => 3.0.9
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
Ah yep, this code can be reached if there's a network error when requesting data for a client-side navigation. That code is currently being overhauled in #6056, so the fix should be rolled into that PR
