### ISSUE TITLE
Actions redirect using location is not working on +page.server

### ISSUE THREAD

**Issue by stausmar** [sveltejs/kit#6114]
### Describe the bug

When returning a location in a `+page.server.js` action, no redirect happens.

Not sure if I'm doing something wrong, but that's what the docs say: https://kit.svelte.dev/docs/routing#page-actions

```
export const POST = async ({ request, locals }) => {
    if (true) {
        console.log('Executed');
	return {
	    location: '/'
	};
    }
}
```

### Reproduction

Here's a link to a minimal reproduction:
https://stackblitz.com/edit/sveltekit-actions-location-redirect-not-working?file=src/routes/todos/+page.server.js

- Open the link
- run `npm install`
- run `npm run dev`
- Navigate to the ToDo page
- Create a new ToDo

You will find the issue in file `src/routes/todos/+page.server.js` in line `43`.

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.91 GB / 7.65 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.17.0 - /usr/bin/npm
  Browsers:
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.424 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.2 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by tobylewis** [comment]
I think this may be to do with the progressive enhancement in the demo app.  If you remove the use:enhance property from the form, this seems to work.

**Comment by stausmar** [comment]
Does the location redirect only work with forms? If I call that function using fetch, then it does not work.

Please see the following file `src/routes/product/+page.server.js`
https://stackblitz.com/edit/sveltekit-actions-location-redirect-not-working?file=src/routes/product/+page.server.js

**Comment by david-plugge** [comment]
You can manually use the `goto` method to redirect the user on the client side

**Comment by tobylewis** [comment]
I'm still trying to get a handle on the new routing myself and have only been using svelte for about three months.  I've been looking at form validation errors so have also been playing around with the demo app.

However my understanding is that if the browser is handling the form and page loading then it will behave as expected.  Once you are in your own fetch call you are going to have to handle all the scenarios yourself.

**Comment by david-plugge** [comment]
@tobylewis there is a discussion about actions so that will probably change

**Comment by tobylewis** [comment]
@david-plugge thanks yes I was reading https://github.com/sveltejs/kit/discussions/5875 yesterday

**Comment by stausmar** [comment]
@david-plugge - Sure, I could use `goto` on the client side. But the redirect should depend on the result of the fetch call. Since the `POST` function in `src/routes/product/+page.server.js` can't return any data, I can't tell if the fetch call was successful or not.

**Comment by tobylewis** [comment]
@stausmar - do your redirect in psge.server.js with `return {location:'/whatever'}`
and then inside your fetch handler in page.svelte do
`if (response.redirected){ goto(response.headers.location)}`

**Comment by david-plugge** [comment]
`response.redirected` is false if you pass the header `Accept: 'application/json'` as the handler only returns the errors.
One way to solve this problem could be sending `{ location: '/whatever' }` to the client if he asks for json, just like the errors

**Comment by stausmar** [comment]
Checking for `response.redirected` and then redirecting to `response.url`on the client side actually works, but doesn't seem to be a good solution. 

But I guess I would rather prefer to have a separate `+server.ts` because then I can return whatever I need and do the redirect based on that on the client side.

**Comment by tcc-sejohnson** [comment]
> Checking for `response.redirected` and then redirecting to `response.url`on the client side actually works, but doesn't seem to be a good solution. 
> 
> But I guess I would rather prefer to have a separate `+server.ts` because then I can return whatever I need and do the redirect based on that on the client side.

This is the correct solution. `fetch` will not redirect your page under any circumstances that I'm aware of. If a response contains a 3xx code, `fetch` will _sometimes_ follow the redirect (depends on what options you've passed to fetch), but it still won't trigger a page navigation. That's just how it works -- it's not even a Kit thing. 🤷

If you do need custom redirection after `fetch` requests, it's your job to implement, and `+server.ts` is the way to go, IMO.

**Comment by Rich-Harris** [comment]
What's _supposed_ to happen is this: the `fetch('/todos', { method: 'POST', ... })` should return a response like this:

```js
const { location } = await response.json();
```

The `enhance` action (which won't survive much longer, once we get some consensus on #5875) should just be returning that object.

(I'm realising now that this all got overlooked in the big #5748 overhaul — we need to get `errors` and `fields` back as well. Not sure how best to handle `fields` since it starts out as a `FormData` object.)

At that point, it's up to the app developer to redirect if that's appropriate, or update the UI in situ. Right now the framework isn't making that possible.

**Comment by Rich-Harris** [comment]
Closing, as form actions have been completely overhauled: https://github.com/sveltejs/kit/pull/6469
