### ISSUE TITLE
[vite] error while updating dependencies: 

### ISSUE THREAD

**Issue by olaitan6201** [sveltejs/kit#6115]
### Describe the bug

Error: The service is no longer running
at
\node_modules\esbuild\lib\main.js

### Reproduction

https://github.com/olaitan6201/sveltekit-recipe-app.git

### System Info

```shell
npm run dev
```

```shell
npm run build
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Similar issue with Svelte as well. Unable to run dev and build.

It says a package service is no longer working.

I think this issue is only related to the new integration of vite, npx degit is working fine.

**Comment by Conduitry** [comment]
We're going to need more logs, and for you to actually fill out the "System Info" section. It sounds like the esbuild binary stopped working, which is very likely to be environmental.

**Comment by benmccann** [comment]
When does this happen for you? When running `npm run dev`, `npm run build`, `npm run preview` or other?

**Comment by olaitan6201** [comment]
It happens on both npm run dev and npm run build

**Comment by olaitan6201** [comment]
Thanks everyone. It's now working fine.

**Comment by olaitan6201** [comment]
It happens on

npm run dev and npm run build

I didn't try npm run preview
