### ISSUE TITLE
No adapter specified in my SvelteKit Project

### ISSUE THREAD

**Issue by rcapdepaula** [sveltejs/kit#6127]
### Describe the bug

My project runs perfectly when I run it in dev mode "npm run dev".

But when I build it, it gets this error:

`No adapter specified`

I run "npm run preview" and run the build mode in my localhost:3000 and everything happens perfectly, I can access my app normally, with no errors in the console.

There are no errors, just `No adapter specified` that's the strange thing.

### Reproduction

Attempting this in another project, can't reproduce this currently,

Attempted to reproduce this however was unable.

### Logs

```shell
There are no errors in the consoles, only: 

`No adapter specified
See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing`
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 8.44 GB / 15.86 GB
  Binaries:
    Node: 17.2.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.18.9
    @sveltejs/adapter-auto: next => 1.0.0-next.17
    @sveltejs/kit: next => 1.0.0-next.267
    @tinymce/tinymce-svelte: ^1.0.0 => 1.0.0
    firebase: ^9.8.1 => 9.8.1
    instantsearch.js: ^4.44.0 => 4.44.0
    leaflet: ^1.7.1 => 1.7.1
    prettier: ^2.5.1 => 2.5.1
    prettier-plugin-svelte: ^2.5.0 => 2.6.0
    svelte: ^3.44.0 => 3.48.0
    svelte-loading-spinners: ^0.1.7 => 0.1.7
    svelte-slidy: ^2.8.7 => 2.8.7
    typesense-instantsearch-adapter: ^2.4.1 => 2.4.1
    uuid: ^8.3.2 => 8.3.2
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
The error almost certainly is that you don't have an adapter specified in `svelte.config.js`. Not having an adapter won't stop `dev` from working. It won't even actually stop `build` from working - it's just that the build will then only work with `preview` and not as a proper standalone app.

**Comment by Conduitry** [comment]
I surmise the "you can close this" comments on #2598 were referring to this issue.

**Comment by rcapdepaula** [comment]
yes, sorry.
