### ISSUE TITLE
Please document markdown SSR

### ISSUE THREAD

**Issue by bionicles** [sveltejs/kit#613]
**Is your feature request related to a problem? Please describe.**
It's unclear from the docs currently how to make a folder of markdown files and set a CSS module for it (blog, blog style / layout)

**Describe the solution you'd like**
Please document how to integrate markdown and how to style the markdown separately from the main app (for a blog)

**Describe alternatives you've considered**
Perhaps this could work with pure vite but I'm wary of getting sucked into workarounds and want to do it the idiomatic sveltekit way

**How important is this feature to you?**
Having a markdown blog is really important to me because it's much more readable than HTML

**Additional context**
One super cool thing would be to integrate roam research style [[wiki links]] -- with backlinks. This could make sveltekit a legit platform for Zettelkasten

Also, perhaps a svelte version of "MDX" To embed svelte components in markdown, would be epic, since we could make interactive data viz in our blogs

Just one man's opinion, I like the idea of markdown files "just working"

**Comment by Conduitry** [comment]
Perhaps this could go in a community-maintained recipe somewhere, but I don't think this belongs in Kit itself or in its official documentation.

**Comment by benmccann** [comment]
https://github.com/sveltejs/sites uses Markdown as does https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev, so there are some examples you can follow
