### ISSUE TITLE
Navigating to/from dynamic routes fails

### ISSUE THREAD

**Issue by bradleyg** [sveltejs/kit#6138]
### Describe the bug

When navigating to/from dynamic routes (/post/[slug]/page.svelte/) the content of the page isn't updated (although the URL is updated).

### Reproduction

1. Navigate to https://179cd29f.sveltekit-1-0-0-next-428-bug.pages.dev/post/foo
2. Click "bar" and see the content remains "foo" although the URL shows "bar"
3. Refresh the page, content now shows "bar".

Full project code:  
https://github.com/bradleyg/sveltekit-1.0.0-next.428-bug

Sample code:
```javascript
// src/routes/post/[slug]/page.server.js

export function load({ url }) {
  return { pathname: url.pathname };
}
```

```svelte
<!-- src/routes/post/[slug]/page.svelte -->

<script>
  export let data;
  export let { pathname } = data;
</script>

<a href={`/post/foo`}>Foo</a>
<a href={`/post/bar`}>Bar</a>
<h1>{pathname}</h1>
```

### System Info

```shell
Safari, Chrome
```

### Severity

serious, but I can work around it

### Additional Information

Strangely similar to #3929

**Comment by babichjacob** [comment]
Write `$: ({ pathname } = data);` instead of `export let { pathname } = data;`

**Comment by bradleyg** [comment]
Got it, reread the [migration guide](https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3292707). Thank you :)
