### ISSUE TITLE
Uncaught TypeError on start

### ISSUE THREAD

**Issue by DoomDuck** [sveltejs/kit#6139]
### Describe the bug

I get an uncaught exception in the `console`
And then I get weird bugs that I don't understand (sorry to be so vague)

### Reproduction

I created a repo at to repoduce the bug
https://github.com/DoomDuck/svletekit-bug-report

steps:
- git clone
- npm i
- npm run dev
- open in *firefox*

### Logs

```shell
<Layout> was created with unknown prop 'data' layout.svelte:84:92
<Page> was created with unknown prop 'data' +page.svelte:41:92
<Page> was created with unknown prop 'errors' +page.svelte:41:92
Uncaught (in promise) TypeError: navigation_result.state.branch.at is not a function
    update http://127.0.0.1:5174/node_modules/@sveltejs/kit/src/runtime/client/client.js:352
    navigate http://127.0.0.1:5174/node_modules/@sveltejs/kit/src/runtime/client/client.js:907
    goto http://127.0.0.1:5174/node_modules/@sveltejs/kit/src/runtime/client/client.js:171
    goto http://127.0.0.1:5174/node_modules/@sveltejs/kit/src/runtime/client/client.js:974
    start http://127.0.0.1:5174/@fs/tmp/tmp.dOl1SqvHSC/svletekit-bug-report/node_modules/@sveltejs/kit/src/runtime/client/start.js:43
    <anonymous> http://127.0.0.1:5174/:16
client.js:352:52
```

### System Info

```shell
System:
    OS: Linux 5.10 NixOS 21.05 (Okapi) 21.05.740.aa576357673 (Okapi)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 4.90 GB / 11.55 GB
    Container: Yes
    Shell: 3.2.2 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 16.14.0 - ~/.nix-profile/bin/node
    npm: 8.3.1 - ~/.nix-profile/bin/npm
  Browsers:
    Chromium: 98.0.4758.102
    Firefox: 89.0
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.411
    svelte: ^3.46.0 => 3.49.0
    vite: ^3.0.0 => 3.0.8
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Removing the `hooks.js` file seemed to be a temporary fix but but later on the problem came back.
This is seems like a hard bug..
I tried to go around it without success

**Comment by DoomDuck** [comment]
I just realized I do not get the error with chromium :shrug:

**Comment by MajorBreakfast** [comment]
Hey @DoomDuck. The critical error is the `.at` function. I've seen a recent commit related to this. You can try updating to the latest `1.0.0-next.428`. It will likely resolve your issue

**Comment by MajorBreakfast** [comment]
https://github.com/sveltejs/kit/pull/6082

**Comment by Conduitry** [comment]
Please make sure you're using the latest version when you report an issue.

**Comment by DoomDuck** [comment]
Sorry @Conduitry, I thought I had done it..
Thank you @MajorBreakfast  !
