### ISSUE TITLE
Sveltekit + Urql + SSR

### ISSUE THREAD

**Issue by kamalkech** [sveltejs/kit#614]
I can get data just in client side,
but for SSR data empty and still in step : fetching

any idea how solve this probleme ?

Tnx

**Comment by Conduitry** [comment]
Please use one of the issue templates and please provide a reproduction.

**Comment by benmccann** [comment]
This type of question is probably better asked on Discord or StackOverflow

**Comment by kamalkech** [comment]
@benmccann already asked in discord by no result, so why you close it hhh

**Comment by babichjacob** [comment]
We couldn't help you in the Discord server, or here, because we haven't been provided any of your code to look at. The best I was able to do was point you to solving the only urql + SvelteKit error I knew of:

> put
> ```js
>   optimizeDeps: {
>        exclude: ["@urql/svelte"]
>    }
>```
> in your `vite` config and move `@urql/svelte` from `devDependency` to `dependency`

**Comment by kamalkech** [comment]
@babichjacob i already do that, and i get data and no in SSR mode

**Comment by babichjacob** [comment]
> 
> 
> @babichjacob i already do that, and i get data and no in SSR mode

We still don't know what code you wrote.

**Comment by kamalkech** [comment]
yesterday i already send to you capture of my code, any way plz check this captures :

![1](https://user-images.githubusercontent.com/1313428/112380034-2cb10780-8ce9-11eb-956c-af7f1f0e4c5e.png)
![2](https://user-images.githubusercontent.com/1313428/112380037-2de23480-8ce9-11eb-94b1-f0960a583362.png)
![3](https://user-images.githubusercontent.com/1313428/112380039-2de23480-8ce9-11eb-9c82-ad3b20e31f6f.png)
![4](https://user-images.githubusercontent.com/1313428/112380041-2e7acb00-8ce9-11eb-8233-3e87e8537295.png)

**Comment by babichjacob** [comment]
There is nothing in your code that would make server side page rendering wait until the query is resolved. Do work like this in `load` per SvelteKit's docs.

**Comment by benmccann** [comment]
This is a hard way for us to reproduce because we would need to type the code from the screenshot and their may be other code that's important elsewhere in the application that's not included. A repo that reproduces this would be a lot more helpful

**Comment by kamalkech** [comment]
@babichjacob  with this i get error: 
500
Function called outside component initialization

Error: Function called outside component initialization


```typescript
<script context="module">
  import { initClient, operationStore, query } from '@urql/svelte';

  export async function load({ page, fetch, session, context }) {
    initClient({
      url: 'http://localhost:4000/graphql',
    });

    const articles = operationStore(`
      query {
        articles {
          _id
          title
          article_categories {
            _id
            name
          }
        }
      }
    `);

    query(articles);

    articles.subscribe((d) => console.log(`d`, d));

    return {
      props: {
        articles,
      },
    };
  }
</script>

<script lang="ts">
  export let articles;
</script>

<h2>Graphql</h2>

{#if $articles.fetching}
  <p>Loading...</p>
{:else if $articles.error}
  <p>Oh no... {$articles.error.message}</p>
{:else}
  <ul>
    {#each $articles.data.articles as article}
      <li>
        {article.title}
        <br />
        Categories:
        {#each article.article_categories as category}
          {category.name},
        {/each}
      </li>
      <hr />
    {/each}
  </ul>
{/if}
```

**Comment by kamalkech** [comment]
@benmccann ok understood

**Comment by babichjacob** [comment]
> @babichjacob  with this i get error: 
> 500
> Function called outside component initialization
> 
> Error: Function called outside component initialization
> 
> 
> ```typescript
> <script context="module">
>   import { initClient, operationStore, query } from '@urql/svelte';
> 
>   export async function load({ page, fetch, session, context }) {
>     initClient({
>       url: 'http://localhost:4000/graphql',
>     });
> 
>     const articles = operationStore(`
>       query {
>         articles {
>           _id
>           title
>           article_categories {
>             _id
>             name
>           }
>         }
>       }
>     `);
> 
>     query(articles);
> 
>     articles.subscribe((d) => console.log(`d`, d));
> 
>     return {
>       props: {
>         articles,
>       },
>     };
>   }
> </script>
> 
> <script lang="ts">
>   export let articles;
> </script>
> 
> <h2>Graphql</h2>
> 
> {#if $articles.fetching}
>   <p>Loading...</p>
> {:else if $articles.error}
>   <p>Oh no... {$articles.error.message}</p>
> {:else}
>   <ul>
>     {#each $articles.data.articles as article}
>       <li>
>         {article.title}
>         <br />
>         Categories:
>         {#each article.article_categories as category}
>           {category.name},
>         {/each}
>       </li>
>       <hr />
>     {/each}
>   </ul>
> {/if}
> ```

Use `createClient` and store the value of client instead. You can't use `initClient` because it implicitly makes a `setContext` call.

**Comment by kamalkech** [comment]
@babichjacob still get empty data in SSR using createClient, can you plz share link or same documentation about this topic, cuz i won't to broth u, tnx bro

**Comment by babichjacob** [comment]
> 
> 
> @babichjacob still get empty data in SSR using createClient, can you plz share link or same documentation about this topic, cuz i won't to broth u, tnx bro

I don't know whether or not there is any, nor do I know how to use urql. I only picked this up from previous troubleshooting. (Non-sarcastically) good luck!

**Comment by kamalkech** [comment]
@babichjacob tnx good luck u too

**Comment by kamalkech** [comment]
I found solution, it s simple for SSR mode must to add fetch to createClient function:

```typescript
export async function load({ page, fetch, session, context }) {
    const client = createClient({
      url: 'http://localhost:4000/graphql',
      fetch,
      exchanges: [
        fetchExchange
      ]
    });
    const articles = await client.query(QUERY).toPromise();

    return {
      props: {
        articles: articles,
      },
    };
  }
  ```

**Comment by frederikhors** [comment]
@babichjacob why cannot I use `initClient`?

Reproduction here: https://github.com/FormidableLabs/urql/issues/1660
