### ISSUE TITLE
A way to validate things on server initialization

### ISSUE THREAD

**Issue by Zamiell** [sveltejs/kit#6147]
### Describe the problem

Related to #1538.

In other server solutions, a common pattern is check for the presence of necessary environment variables on startup, for the purposes of showing a friendly error message.

For example:

```ts
const { DATABASE_URI } = process.env;

if (DATABASE_URI === undefined || DATABASE_URI === "") {
  console.error(
    'The "DATABASE_URI" environment variable is not set. This is necessary in order for the server to function.',
  );
  console.error(
    'If you are deploying to Node, did you forget to copy the ".env.example" file to ".env" and fill in the values?',
  );
  console.error(
    "If you are deploying to Vercel, did you forget to add this environment variable to your project settings page?",
  );
  process.exit(1);
}
```

Doing this kind of thing prevents end-users from having to troubleshoot more-complicated run-time errors. ("Why is the database logic failing? Is the app that I just downloaded bugged?")

In #1538, [Rich-Harris recommends using "hooks.js"](https://github.com/sveltejs/kit/issues/1538#issuecomment-1002106271), but this doesn't solve the problem, as the logic in that file will only be executed when a user actually surfs to the page, rather than on server initialization.

### Describe the proposed solution

SvelteKit should expose an idiomatic way to perform server-start validation of this manner.

This would also an appropriate place to e.g. initiate necessary database connections, so that the app can e.g. fail early if the database password is wrong (rather than when the first user actually tries to use your product).

### Importance

nice to have

**Comment by Conduitry** [comment]
You can use https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server for this.

**Comment by Zamiell** [comment]
That's helpful, but what about users who are using other adapters, such as `adapter-vercel`?

In my example error message in the OP, I included:
"If you are using Vercel to deploy your app, remember to add this environment variable in your project settings page."
The idea here is to make it so that this friendly error message would appear in the "Deployment Status" box, pictured here:

![image](https://user-images.githubusercontent.com/5511220/185811419-16f1ab8b-60ce-47ff-8c7b-c9ee37da6542.png)

In general, I think there is a use-case for providing an adapter-agnostic error message, regardless of the deployment platform that the end-user chooses.

**Comment by tcc-sejohnson** [comment]
I've argued several times for a "startup" hook that's guaranteed to run right when you start your built app. I think there are many reasons to provide one, this being one of them, but it's also not super straightforward when it should run, especially in environments with the concept of instances, such as serverless platforms.

**Comment by tcc-sejohnson** [comment]
I'm with Rich -- simply having `hooks.js` initialized on startup is plenty good. It allows for optimistic connections to databases, running startup validation, etc. without increasing the API footprint.

**Comment by siddhsql** [comment]
I created a `src/hooks.js` and put following in it:

```
const CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID;
if (!CLIENT_ID) {
    throw Error("FATAL: CLIENT_ID is not set");
}
```

but when I run the application using `npm rundev` it still runs when `CLIENT_ID` is not set. am i doing anything wrong?
