### ISSUE TITLE
adapter-vercel build fails with TypeError: builder.copy is not a function

### ISSUE THREAD

**Issue by heyharold** [sveltejs/kit#617]
**Describe the bug**
adapter-vercel build fails with with TypeError: builder.copy is not a function

"@sveltejs/adapter-vercel": "^1.0.0-next.8",
"@sveltejs/kit": "^1.0.0-next.56",
"svelte": "^3.35.0",

**Logs**
```
> Using @sveltejs/adapter-vercel
> builder.copy is not a function
TypeError: builder.copy is not a function
    at adapt (/Users/harold/code/translate-image/node_modules/@sveltejs/adapter-vercel/index.js:24:12)
    at adapt (file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/chunks/index5.js:757:8)
    at file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/cli.js:512:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! translate-image@0.0.1 build: `svelte-kit build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the translate-image@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**To Reproduce**
1. Brand new SvelteKit repo
2. Replace node adapter with vercel adapter
3. Update dependencies
   "@sveltejs/adapter-vercel": "^1.0.0-next.8",
   "@sveltejs/kit": "^1.0.0-next.56",
   "svelte": "^3.35.0",
4. npm run build

**Expected behavior**
Successfull build

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

TypeError: builder.copy is not a function
    at adapt (/Users/harold/code/translate-image/node_modules/@sveltejs/adapter-vercel/index.js:24:12)
    at adapt (file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/chunks/index5.js:757:8)
    at file:///Users/harold/code/translate-image/node_modules/@sveltejs/kit/dist/cli.js:512:11

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
```
$ npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers
npx: installed 1 in 1.361s

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 196.52 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.56 => 1.0.0-next.56
    svelte: ^3.35.0 => 3.35.0
```
- Your browser
N/A

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Vercel

**Severity**
Blocking Entirely

Note: the more honest and specific you are here the more we will take you seriously.

**Comment by leerob** [comment]
Once this is working, I'm happy to contribute back and add docs 😄 We'd also like to have zero-config support for SvelteKit on Vercel!

**Comment by benmccann** [comment]
@antony looks like this broke in https://github.com/sveltejs/kit/pull/600/files#r600142752

**Comment by wiesson** [comment]
> @antony looks like this broke in https://github.com/sveltejs/kit/pull/600/files#r600142752

Yes - but the copy function is still required in the code? What is the strategy here? I'm happy to do a hotfix PR to make it work. 

https://sveltekit-vercel.vercel.app
https://github.com/wiesson/sveltekit-vercel
https://github.com/wiesson/sveltekit-adapter-vercel (I just inlined the required functions)
