### ISSUE TITLE
`fetch` in endpoints

### ISSUE THREAD

**Issue by c-bandy** [sveltejs/kit#618]
**Is your feature request related to a problem? Please describe.**

I'm hosting a blog post on `/blog/[slug].svelte`. This blog post is powered by `/blog/[slug].json`, generated by an endpoint. In the endpoint we want to include some html which serves as the body of the blog post. This html is composed by markdown, and its location is defined by an `articleUrl` parameter.

The final output for `/blog/[slug].json` might look something like this:

```json
{
  "slug": "my-article",
  "articleUrl": "/articles/my-article.md",
  "articleHtml": "<h1>My article</h1>\n<p>This is my article</p>"
}
```

Making relative requests to fetch additional content, let's say `/articles/my-article.md`, is awkward if you use something like `node-fetch`. You have to make assumptions about the hosted environment, ergo:

```js
import fetch from "node-fetch";

export async function get(request) {

  (...)

  const url = new URL(project.articleUrl, "http://localhost:3000");
  const res = await fetch(url);
  const markdown = await res.text();

  project.articleHtml = renderMarkdown(markdown);

  return {
    headers: {
      'Content-Type': 'application/json'
    },
    body: project
  }
}
```

**Describe the solution you'd like**

If `fetch` was available in endpoints, similar to how they are implemented in `load()` for pages, this could easily be solved like:

```js
export async function get(request, fetch) {

  (...)

  const res = await fetch(project.articleUrl);
  const markdown = await res.text();

  project.articleHtml = renderMarkdown(markdown);

  return {
    headers: {
      'Content-Type': 'application/json'
    },
    body: project
  }
}
```

**Describe alternatives you've considered**
`node-fetch` would normally be an option, but since we are dealing a relative path to a locally hosted file there are the shortcomings elaborated on above.

**How important is this feature to you?**
It's not really obvious how to solve this particular issue without this feature, so it could help prevent some headaches in the future if there was parity with `load()`.

**Comment by PatrickG** [comment]
Why are you fetching the content of a local file via fetch?
You could simply read the content of the file with nodes `fs` module.

**Comment by babichjacob** [comment]
> 
> 
> Why are you fetching the content of a local file via fetch?
> You could simply read the content of the file with nodes `fs` module.

That would only work during `dev`, since those files won't be available on e.x. a serverless platform.

**Comment by alteredorange** [comment]
All api endpoints would always run on the server, so if you were fetching something server side, then yes you'd have to use something like node-fetch.

 But what you're describing could just be done in the load function, and that way you don't have to call your own api endpoint, which then calls the actual endpoint where the data is stored. Just call the data endpoint directly from the [loading function](https://github.com/sveltejs/kit/blob/master/documentation/docs/03-loading.md).

**Comment by c-bandy** [comment]
> All api endpoints would always run on the server, so if you were fetching something server side, then yes you'd have to use something like node-fetch.
> 
> But what you're describing could just be done in the load function, and that way you don't have to call your own api endpoint, which then calls the actual endpoint where the data is stored. Just call the data endpoint directly from the [loading function](https://github.com/sveltejs/kit/blob/master/documentation/docs/03-loading.md).

I'm aware this can be done in `load()`, but this is not what I'm asking for. I want to be able to do a relative fetch inside of endpoints.

**Comment by antony** [comment]
Yeah - I think the overarching thing here is that we provide fetch in `load` but we don't provide it in endpoints, which is somewhat odd. I felt the same when using server routes in Sapper.

I sort-of know the reasons, but my gut feel is that although it would be convenient, it also seems odd to just pass one thing into the endpoints. What if you were using graphql? Or a database of some sort? Why would we bless `fetch` in this way where it isn't strictly required (it's a special case in `load`)

**Comment by benmccann** [comment]
`fetch` seems a bit different to me than the other use cases you mentioned because we already provide a `fetch` implementation. If we don't make `fetch` available then users need to know the implementation detail that we use `node-fetch` or they might end up with two fetching implementations. Also if you want to share code between a page and endpoint you'd hope the fetching works the same in both places

**Comment by antony** [comment]
Agreed, and this is why I felt it odd in Sapper. I'm definitely ok with adding it to handlers.

**Comment by benmccann** [comment]
Hmm. Counterpoint to this is that someone just asked about using `fetch` in hooks. I'm not sure we'd want to provide `fetch` to every hook. Maybe it's better to just document that you should use `node-fetch` in that case

**Comment by c-bandy** [comment]
> I'm not sure we'd want to provide `fetch` to every hook.

Why is that a bad idea?

**Comment by jwrunner** [comment]
I'm about to set up an endpoint for my app and would also appreciate being provided `fetch` in endpoints for the context of Cloudflare Workers. Due to fetch being available there, I would find it annoying to have to write the code to provide node-fetch just for the dev server, done in some fashion related to:

https://github.com/sveltejs/kit/blob/5554accd7677e5e5caeb45c6c4e0230c218cbd48/examples/realworld.svelte.dev/src/lib/api.js#L15-L17

Glad to see Cloudflare being taken into consideration in #1034 and think this request would round things out nicely.

**Comment by Rich-Harris** [comment]
As of recent versions, `fetch` is available globally. In environments where it already exists, like Cloudflare Workers and Deno, we can just use the global; in other environments like Lambda the adapter is expected to make it available, which it can do thusly:

```js
import '@sveltejs/kit/install-fetch';
```

That solves the problem of external fetches.

I don't think it makes sense to provide a special custom `fetch` to endpoints for relative fetches. I can't think of a situation where you'd use it that wouldn't be better solved with whatever tool you're using inside the fetched endpoint (`fs`, a database, an external fetch, whatever). All it creates is overhead, and confusion about what's actually happening under the hood.

Even in the case where you're fetching something from `static`, as far as the endpoint is concerned it _is_ an external fetch (endpoints have no privileged access to static assets), so it's appropriate that you'd do something like this:

```js
fetch(`https://${host}${assets}/${file}`)
```

**Comment by benmccann** [comment]
I'd closed this as solved, but am going to reopen to track adding something to the documentation
