### ISSUE TITLE
Reuse default +layout.js and +layout.server.js in named layout. 

### ISSUE THREAD

**Issue by stalkerg** [sveltejs/kit#6196]
### Describe the problem

If I want to have a second root layout, just a different "layout" (`+layout.svelte`) I should copy-paste `+layout.js` and `+layout.server.js`. 
In old routing, schema duplicate was only inside `__layout.js` `load` function. Even if I move `load` function to a separate file, I will duplicate two extra files for each named layout. 

### Describe the proposed solution

To reduce boilerplate, the named layout should have a way to reuse the default layout client and server functions. 

### Importance

nice to have

**Comment by dummdidumm** [comment]
The layout API will very likely change ([see discussion](https://github.com/sveltejs/kit/discussions/6124)), depending on your use case this will be possible introducing groups. If not, you can create a resuable layout UI component and a reusable load function and use that in both your layouts.

**Comment by stalkerg** [comment]
As I can see, only a few people mention about `+layout.js` and `+layout.server.js` this proposal is mostly about `+layout.svelte` and named layouts.
