### ISSUE TITLE
Changes to searchParams no longer trigger updates (+page.server.js load)

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#6199]
### Describe the bug

Anchor links that stay on the same route path, but change the URL searchParams stopped triggering data reloads with 1.0.0-next.431.

it's the +page.server.js load that doesn't re-execute.

Example, using querystring for filter / pagination links (?page=2 etc...)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-pyg1xs

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 207.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5256.0
    Firefox: 103.0.2
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65 
    @sveltejs/kit: next => 1.0.0-next.431 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Works OK when downgraded to 1.0.0-next.430

**Comment by stalkerg** [comment]
I didn't see your example, but it working now on my project.

**Comment by stalkerg** [comment]
Inside the iframe just changing the `searchParams` not working, if you will check the iframe URL it is static.

**Comment by CaptainCodeman** [comment]
If you do a full page refresh, the +page.server.js load function runs.
If you navigate from a different route, the +page.server.js load function runs.
But if you navigate to a page that changes the searchParam without changing the route, the load function is not called.

**Comment by chbert** [comment]
Having similar issues with changing params acting in a similar way.
