### ISSUE TITLE
Requests for __data.json should be skipped entirely when possible

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#6201]
### Describe the bug

Re-running server-side `load` on each navigation is supposed to be skipped now (unless the `load` function depends on `url` etc.), but this does not appear to be fully working. Even if a given page has no `+page.server.js` file, the browser is still making requests to `__data.json` on each navigation, which return things like `{"type":"data","nodes":[{"type":"skip"},null]}` - the root (layout) node is skipped, and the leaf (page) node has no data. Requests that would tell the server to skip all of the nodes for which there are no `.server.js` files should be skipped entirely.

### Reproduction

https://github.com/Conduitry-Repros/kit-6201

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 8.34 GB / 12.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Yarn: 1.22.19
    npm: 8.15.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65 
    @sveltejs/kit: next => 1.0.0-next.431 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

serious, but I can work around it

### Additional Information

This is the situation I referred to in https://github.com/sveltejs/kit/pull/6056#issuecomment-1220125221 - it seems like it was not correctly (or fully?) handled.

**Comment by Conduitry** [comment]
An intriguing wrinkle with this is that, by calling `__data.json` on every navigation whether it needs to be or not, any logging of requests in `handle` will also reflect any client-side navigation through the app, and (since `/__data.json` is stripped off from the URL in the `event`), these logs will look pretty much exactly the same as if each request were being server-rendered. This might be good or it might be bad.

**Comment by bjon** [comment]
`__data.json` been stripped off is really bad for us. We have to use `event.request.url`, cause there you can see it.

**Comment by dummdidumm** [comment]
What's your use case for knowing that it's the `__data.json` call?

**Comment by bjon** [comment]
@dummdidumm We don't want to know. Its the effect of removing `__data.json`, that's the problem.

Here's how our URLs works (predated sveltekit):
`/[language]/ ` is our "root". `/en/path1` and `/en/path2/path3` are valid, cause we only use trailing slash for language path.
If we detect `/en`, we redirect to `/en/ `, and this is the problem.
When `/en/__data.json` is requested, `event.url` becomes `/en`, and we do a redirect, that breaks the app.
We have solved this by never using `event.url`, but using `event.request.url` instead.

Is there a good reason why `event.request.url` and `event.url` should differ?

**Comment by dummdidumm** [comment]
One problem with calling the backend too much is that we don't know that the new page doesn't have a load function. We only know "this route uses server data somewhere along the way", but we don't know "this leaf doesn't use a load function and everything leading up to it is unchanged so you can skip requesting the data".

**Comment by stalkerg** [comment]
@Conduitry @dummdidumm after the latest changes, this issue occurs again.

**Comment by dummdidumm** [comment]
Discussed in Discord, it's working as expected, but is undesired - there are open feature requests related to this.
