### ISSUE TITLE
calling "local" api endpoints from within a `+page.ts` causes `hooks.handle` to be executed twice

### ISSUE THREAD

**Issue by demetrius-mp** [sveltejs/kit#6209]
### Describe the bug

I actually detected this behaviour because i use [trpc-sveltekit](https://github.com/icflorescu/trpc-sveltekit) in my project.

trpc creates a route under the app (`/trpc`), which is responsible to handle every procedure call.

when running a procedure from inside any `+page.ts`, the hooks.handle gets executed twice (one for the actual `+page.svelte`, and other to the `/trpc/{procedureName}`.

this becomes a problem because in my `hooks.handle`, i make a db call to get the current user based on cookies. hence, every "user navigation" causes 2 db calls to get the user.

this started happening only after this major update (the one that added the `+` prefix to everything.

### Reproduction

start a new sveltekit project and create the following files:
```ts
// src/routes/api/+server.ts
import type { RequestHandler } from './$types';

export const GET: RequestHandler = async () => {
	return new Response(
		JSON.stringify({
			hello: 'world'
		})
	);
};
```

```ts
// src/routes/+page.ts
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ fetch }) => {
	const r = await fetch('/api');

	return await r.json();
};
```

```ts
// src/hooks.ts
import type { Handle } from '@sveltejs/kit';

export const handle: Handle = async ({ event, resolve }) => {
	console.log(event.url.pathname);

	const response = await resolve(event);
	return response;
};
```

```ts
// routes/+layout.server.ts
import type { LayoutServerLoad } from './$types';

export const load: LayoutServerLoad = async () => {
	return {
		layoutLoad: 'layoutLoad'
	};
};
```
```svelte
// src/routes/+layout.svelte
<slot />
```

```svelte
// src/routes/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';

	export let data: PageData;

	console.log(data);
</script>
```

then, access `http://127.0.0.1:5173/some-page
your editor console should log the following:
```
/some-page
/api
```

here is a [repro for reproduction](https://github.com/demetrius-mp/twice-handle-execution-repro)

### System Info

```shell
System:
    OS: Linux 5.18 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 10.38 GB / 15.54 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65 
    @sveltejs/kit: next => 1.0.0-next.431 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
I don't think there's any bug here. `handle` runs on every request to the server; you're making two requests to the server.

**Comment by Conduitry** [comment]
This is the intended behavior. And it definitely is not new with the routing rework.

Calls to internal endpoints made from the browser are real, requests coming into your server, and so `handle` is called for them. Calls to internal endpoints made from the server during SSR also call `handle` again (although this time with a constructed `event` object without there being an actual new HTTP request) for consistency with the browser behavior.
