### ISSUE TITLE
FormData is empty

### ISSUE THREAD

**Issue by fcrozatier** [sveltejs/kit#6223]
### Describe the bug

When using a form action to handle form submission, the formData received by the action is empty.

If I use the `enhance` action from the todo [demo app](https://github.com/sveltejs/kit/blob/89ef569c8f07640d7e42ca08945ed0fc6a536de3/packages/create-svelte/templates/default/src/lib/form.ts#L31) the fetch fails, otherwise the formData is just empty

### Reproduction

[repo](https://github.com/fcrozatier/kit_form_action)

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 507.42 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Firefox Developer Edition: 105.0
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65 
    @sveltejs/kit: next => 1.0.0-next.432 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
When you say it's empty, do you just mean that this is what you see in the terminal?

```
form FormData {}
```

The way Node prints it is admittedly confusing, but that's not an empty form data object. In your repro if I change the code to log a specific value...

```diff
-console.log('form', form);
+console.log('number', form.get('number');
```

...everything works as expected:

```
number 0
```

Or you can do `console.log('form', ...form)` or `console.log('form', Object.createEntries(form))`.

**Comment by fcrozatier** [comment]
Yes that's what I meant, but indeed I was just getting confused by the way Node prints. XD
Silly mistake !
