### ISSUE TITLE
FOUC while loading javascript style library that needs to be loaded before DOM loading

### ISSUE THREAD

**Issue by bhvngt** [sveltejs/kit#6227]
### Describe the bug

As per this comment from @Rich-Harris, after #6174 FOUC should not be possible when we are importing global css within root layout.

I have been using a style javascript library that needs to be loaded before any DOM content gets loaded. I could see FOUC happening. This is different than the scenario where styles are imported which, as per the comment, gets imported as `style` tag.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-7xrgjy?file=src%2Froutes%2F%2Blayout.svelte,package.json,package-lock.json&terminal=dev

In the following reproduction one can see a flicker of `FOUC TEST` happening on the right hand side of the band. It's best to see the preview in a separate tab.

### System Info

```shell
@sveltejs/kit: 1.0.0-next.431
vite: 3.0.9
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This isn't a bug in SvelteKit. It's because of how `@master/css` works — it's a big bag of JavaScript that injects styles into the DOM, rather than an actual CSS file that tooling can reason about. Unfortunately I don't have any better advice than 'don't use it'.

**Comment by bhvngt** [comment]
Fair enough. Leaving aside the pros/cons of `@master/css`, there are use cases which falls outside the purview of what framework is expected to handle. Maybe this is one of those cases.

**Comment by 1aron** [comment]
I didn't find this thread until just now. 👀

@Rich-Harris Master CSS provides **three rendering modes**, including **pre-rendering**, **runtime rendering**, and **static extraction** same as UnoCSS and TailwindCSS.

![image](https://github.com/sveltejs/kit/assets/33840671/9b9b74d7-80db-4132-86ae-15fa9aabf31b)

It's recommended to use **Master CSS Progressive Rendering** with Svelte. It only generates the required CSS rules based on the page, rather than bundling the entire application.
```ts
// src/hooks.server.ts
import { render } from '@master/css-server'
import { config } from '../master.css'
 
/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
    return await resolve(event, {
        transformPageChunk: ({ html }) => render(html, config).html
    })
}
```
See the full guide for Svelte integration: https://rc.css.master.co/docs/installation/svelte

**Comment by 1aron** [comment]
@bhvngt If you are using a pure SPA, you only need to set `html` to `display: none` in advance to avoid FOUC. The Master CSS Runtime will immediately inject styles into the running stylesheet after initialization and remove `display: none`.
```html
<!DOCTYPE html>
<html lang="en" style="display:none">
```
https://rc.css.master.co/docs/installation/svelte/runtime-rendering#prevent-flash-of-unstyled-content

**Comment by cookies-sharpener** [comment]
@bhvngt https://extra-emil.github.io/8y8Mg8TXzlV/
