### ISSUE TITLE
Document why the wrapping `div` is necessary in `app.html`

### ISSUE THREAD

**Issue by ponderingexistence** [sveltejs/kit#6244]
### Describe the problem

The default SvelteKit template includes an `app.html` file — the purpose of which was explained in [this part of the docs](https://kit.svelte.dev/docs/project-structure#project-files) — in which the `%sveltekit.body%` so-called placeholder, is put within a `<div>` element that acts as a wrapper. However, at least on the surface, the div seems redundant and unnecessary, and the app continues to work even if you remove it and make `%sveltekit.body%` a direct child of `<body>`, yet it feels like it must been been put there for a reason.

### Describe the proposed solution

The first question of course, is why this `div` even exists and what purpose it exactly serves; and also whether or not it's safe to remove it. I think it would be helpful if these questions were answered in the documentation. Although this may sound like a small detail, it could cause confusion for some people as it has for me (I've seen it being asked about a few times in the Discord server). Especially if the `div` is in fact necessary for the proper functioning of the app, some people may remove it without realizing that. So either way, this could benefit from some documentation, I feel.

### Alternatives considered

At the very least, I'd appreciate it if some explanation were provided in this issue, so that in the future if somebody else has this question mark in their head, and they search for it, they can hopefully find this issue and read the explanation here.

### Importance

nice to have

**Comment by CaptainCodeman** [comment]
I can't remember if it was todo with a plugin or mounting multiple apps, it used to have an ID for the app to target.

Things are so much more _symmetrical_ and aesthetically pleasing when you remove it - it's usually the first thing I do with a new project:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %sveltekit.head%
  </head>
  <body>
    %sveltekit.body%
  </body>
</html>
```

**Comment by Rich-Harris** [comment]
This is because if you don't have it, browser extensions are liable to inject elements in the `<body>` that the hydration process removes. I've seen it cause cryptic and noisy bugs that you really don't want spamming your Sentry account or whatever.

As far as SvelteKit is concerned, it's optional, but given the fact that you have no control over what browser extensions your users have installed, I would strongly recommend leaving it where it is.

Opened #6245

**Comment by CaptainCodeman** [comment]
Couldn't `%sveltekit.body%` also write the div it needs?

**Comment by Rich-Harris** [comment]
We considered it, but ultimately concluded it took too much control out of people's hands
