### ISSUE TITLE
Option for file-based routing

### ISSUE THREAD

**Issue by gavin-noktes** [sveltejs/kit#6256]
### Describe the problem

I used Sveltekit a couple months ago to create a simple application that I posted and forgot about. A bit ago I decided to open up a new project similar to the other application and found out that file-based routing doesn't work now? Although I can see why you would choose folder-based routing over the alternative, for smaller projects it is very annoying to have 7-10 folders that just contain a `+page.svelte` file. My file explorer has gotten so long I have to scroll each time I want to open a file on my code editor.

### Describe the proposed solution

Have you all decided that only folder-based routing will be used for the future, or is there a possibility that smaller projects could maybe opt-in to file-based routing instead. I know it is merely personal preference, but it annoys me to my core that, each time I open a file, I have to open a folder just to access the one file in it when there is an easier alternative.

### Alternatives considered

I have tried to just work with the folder-based routing, but each time I open a folder to open a `+page.svelte` file I lose so much motivation for working.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
This was discussed on the discussion leading up to the change, we don't want to bring back two ways of doing the same.

If you don't want to scroll, I suggest to use the file search feature of your code editor, `<foldername>+` will bring consistently fast results.
