### ISSUE TITLE
LayoutServerLoad not re-fetched when page without PageServerLoad is invalidated

### ISSUE THREAD

**Issue by HalfdanJ** [sveltejs/kit#6258]
### Describe the bug

In a simple project where theres a `+layout.server.ts` file and a `+page.svelte`, calling `invalidate()` doesn't re-trigger fetching the page data from `+layout.server.ts` again. 

If an "empty" `+page.server.ts` file is added, then the data does get re-fetched when invalidated, including the data from `+layout.server.ts`. 

I was able to determine that this was a regression in sveltekit 432 (https://github.com/sveltejs/kit/pull/6174) 

### Reproduction

Reproduction example: https://stackblitz.com/edit/sveltejs-kit-template-default-voqrk9?file=src/routes/+page.svelte 

The date shown in the example comes from `+layout.server.ts`. Every time invalidate button is clicked, it should show a new date, and re-fetch `__data.json`, but data is never fetched and the date doesn't update.

If a `+page.server.ts` file is added returning an empty object, then it does fetch new data when invalidated.

Changing the version of sveltekit to 431 in the example above solves the issues.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 79.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: next => 1.0.0-next.435 
    @sveltejs/package: next => 1.0.0-next.1 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by HalfdanJ** [comment]
Looks very similar as the issue in https://github.com/sveltejs/kit/issues/6257 that was posted around same time

**Comment by DePasqualeOrg** [comment]
I'm also having problems with `invalidate()` not updating the data from `LayoutServerLoad`, which started appearing sometime after the migration away from `session`. It looks like the layout's `load` function is running after calling `invalidate`, but the values in `$page.data` aren't always being updated.

**Comment by CaptainCodeman** [comment]
I think this may be the same https://github.com/sveltejs/kit/issues/6269

For me, it works if I'm on a different page, not the same route as the +layout.server file. And the +page loaded data updates, just not the root layout stuff (e.g. session)
