### ISSUE TITLE
Feature request: Reset layout inheritance in nested routes

### ISSUE THREAD

**Issue by sto3psl** [sveltejs/kit#626]
**Is your feature request related to a problem? Please describe.**

When building a website I want pages to share a specific layout with common UI elements like a navigation, sidebar, footer, etc. Other pages might want to use different layouts like a custom landing page. This works fine as long as my landing page is not a sub page of an existing page with layout.

```
** MY SHOP **
src/routes
├── bikes
│   ├── _layout.svelte
│   ├── category
│   │   └── index.svelte
│   └── [slug]
│       ├── index.svelte
│       └── _layout.svelte
```

In this example `/bikes` has a custom layout. Individual bike routes like `/bikes/fancy-bike-3000` add their own layout and inherit the one from `/bikes`.

The problem appears when I want to make a super fancy landing page to promote all my mountain bikes. This page is completely individual and uses its own layout.

```diff
  ** MY SHOP **
  src/routes
  ├── bikes
  │   ├── _layout.svelte
  │   ├── category
  │   │   ├── index.svelte
+ │   │   └── mountain-bikes-promo
+ │   │       └── index.svelte
  │   └── [slug]
  │       ├── index.svelte
  │       └── _layout.svelte
```

`/bikes/category/mountain-bike-promo` will always inherit the layout from `/bikes`, but in this case it's not wanted. 

Sapper needs a feature to bail out of the layout inheritance and let sub pages define their own layouts.

**Describe the solution you'd like**
I would like an API that allows me as developer to get more flexibility when needed but has the layout inheritance by default. 

Ideas: 
* Use a special prop in layout components, that tell Sapper to not include layouts up in the file tree. Maybe something like this:
```html
<!-- _layout.svelte -->
<script>
  export let inherit = false;
</script>
```

* Nuxt.js has a `layout/` folder with custom layouts that you can specify in your page (https://nuxtjs.org/api/pages-layout). This probably doesn't work well with the current inheritance model but I like it.
```js
/* vue code */
export default {
  layout: 'blog',
  // OR
  layout (context) {
    return 'blog'
  }
}
```

**Describe alternatives you've considered**

In the end it's always possible to import layout components like any other component on every page. This provides full flexibility but can be a bit cumbersome if something like the inheritance model already exists.

A different solution could be to structure routes differently but a site structure should ideally not be constrained by the framework of choice.

**How important is this feature to you?**

I think this is a use case every application of a particular size will eventually run into. May it be custom landing pages or interactive stories with data visualizations.

**Additional context**

There was a former discussion in this issue https://github.com/sveltejs/sapper/issues/809.  
The idea to hide elements in a root layout based on `segment` doesn't really work since not the full route is available.
Looking at my example `bikes/_layout.svelte` has `segment === "category"` but `mountain-bike-promos` is needed to know if layout components need to be hidden.

---

I look forward to any API discussion and can maybe come up with an implementation if this is a feature you want to integrate into Sapper.

**Comment by tbremer** [comment]
For those, like myself, coming across this issue with newer release of SvelteKit, this seems to be working well for me:

```html
<script lang="ts">
	import { page } from '$app/stores';
	import Default from '$lib/layouts/Default.svelte';
	import Alternative from '$lib/layouts/Resume.svelte';

	export let layout = Default;

	const layouts = {
		'/': Default,
		'/other': Alternative
	};

	page.subscribe(({ path }) => {
		layout = layouts[path] ?? Default;
	});
</script>

<svelte:component this={layout}>
	<slot />
</svelte:component>
```

**Comment by Rich-Harris** [comment]
I'm not fully up to date on this thread, because it's loooooong, but my current thinking is that we just turn `$layout.svelte` into `$layout.reset.svelte` any time we want a reset

**Comment by GrygrFlzr** [comment]
What about another const export in `$layout.svelte`'s `<script context="module">` instead? That would avoid having to deal with the situation where both `$layout.svelte` and `$layout.reset.svelte` are in the directory at the same time.

```svelte
<script context="module">
  export const reset = true;
</script>
```

This could also extend to pages where you can opt out of the layout on a per-page basis without needing a separate API. E.g. opting out for the `/login` route but using the layout for everything else.

**Comment by Rich-Harris** [comment]
The route manifest is generated purely based on the files inside `src/routes`. If you had files like this...

```
src/routes/$layout.svelte
src/routes/foo/$layout.svelte
src/routes/foo/bar/$layout.svelte
src/routes/foo/bar/baz/$layout.svelte
src/routes/foo/bar/baz/index.svelte
```

then your route manifest would look like this:

```js
import * as layout from "../../../src/routes/$layout.svelte";

const components = [
  () => import("../../../src/routes/foo/$layout.svelte"),
  () => import("../../../src/routes/foo/bar/$layout.svelte"),
  () => import("../../../src/routes/foo/bar/baz/$layout.svelte"),
  () => import("../../../src/routes/foo/bar/baz/index.svelte")
];

export const routes = [
  // src/routes/foo/bar/baz/index.svelte
  [/^\/foo\/bar\/baz$/, [components[0], components[1], components[2], components[3]]]
];

export { layout };
```

In other words you need to import all those components. That's true regardless of whether one of those layouts has the `reset` export, meaning the earlier imports are wasted. By contrast, if you use the filename, you can trivially do this:

```diff
src/routes/$layout.svelte
src/routes/foo/$layout.svelte
src/routes/foo/bar/$layout.svelte
-src/routes/foo/bar/baz/$layout.svelte
+src/routes/foo/bar/baz/$layout.reset.svelte
src/routes/foo/bar/baz/index.svelte
```

```diff
import * as layout from "../../../src/routes/$layout.svelte";

const components = [
-  () => import("../../../src/routes/foo/$layout.svelte"),
-  () => import("../../../src/routes/foo/bar/$layout.svelte"),
-  () => import("../../../src/routes/foo/bar/baz/$layout.svelte"),
+  () => import("../../../src/routes/foo/bar/baz/$layout.reset.svelte"),
  () => import("../../../src/routes/foo/bar/baz/index.svelte")
];

export const routes = [
  // src/routes/foo/bar/baz/index.svelte
-  [/^\/foo\/bar\/baz$/, [components[0], components[1], components[2], components[3]]]
+  [/^\/foo\/bar\/baz$/, [components[0], components[1]]]
];

export { layout };
```

(I'm glossing over the fact that right now the root layout is _always_ included; we'd need to start explicitly including it in route definitions if we started having resets. Which is totally fine as it would actually simplify some stuff.)

**Comment by GrygrFlzr** [comment]
Interesting! You can also use `$layout.reset.svelte` with the /login use case anyway, so this seems like a good way to handle it.

**Comment by dummdidumm** [comment]
Would it be possible then to have one layout in-between have it reset, but everything below will be able to opt in to all parent's layouts again? Like a `$layout.restore.svelte`?

**Comment by Florian-Schoenherr** [comment]
@dummdidumm what's the usecase? (I already asked this somewhere in this thread)
I genuinely want to know, because I can't think of any route layout where you go down the resource-tree, a layout gets removed and deeper it gets restored.
You could also do
```
<MyLayout>
  <slot/>
</MyLayout>
```
on root `$layout.svelte` and on the deeper nested `$layout.reset.svelte`.

If it's no implementation overhead, of course it would be cool.

**Comment by seanlail** [comment]
@Florian-Schoenherr A use case I have found is a kind of "summary" page in a long journey. 

You would want the layout all the way down but somehow exclude it for that page and then be included afterwards.

At the moment I just toggle components in my layout page based on the page path, but that requires anyone updating my "summary" page to be aware that they need to go up the tree and update the layout if they want to make changes.

**Comment by Florian-Schoenherr** [comment]
@seanlail 😕 
In `$layout.reset.svelte` you would have the advantage of just putting some kind of wrapper there again, without toggling.

**Comment by seanlail** [comment]
@Florian-Schoenherr very true. That does make it simpler. I guess then the restore part is left? Would the reset only work in that specific route and not cascade?

**Comment by babakfp** [comment]
> For those, like myself, coming across this issue with newer release of SvelteKit, this seems to be working well for me:
> 
> ```
> <script lang="ts">
> 	import { page } from '$app/stores';
> 	import Default from '$lib/layouts/Default.svelte';
> 	import Alternative from '$lib/layouts/Alternative.svelte';
> 
> 	export let layout = Default;
> 
> 	const layouts = {
> 		'/': Default,
> 		'/other': Alternative
> 	};
> 
> 	page.subscribe(({ path }) => {
> 		layout = layouts[path] ?? Default;
> 	});
> </script>
> 
> <svelte:component this={layout}>
> 	<slot />
> </svelte:component>
> ```
> 
> _Note, I made use of the `$lib` prefix and stored my layouts there (`./src/lib/layouts`)_

What about `/shop/`?

**Comment by babakfp** [comment]
Hi

@Rich-Harris 
Can't we just create the layout system like [how it is in the NuxtJS](https://nuxtjs.org/docs/2.x/directory-structure/layouts)? What if I want to change the layout if the `x` was greater than the `y`? This is not possible with the current layout system. So it means that SvelteKit isn't 100% reactive because the app can't react in some circumstances, right? (hmm emoji).

---

@SillyFreak 
[Your solution](https://github.com/sveltejs/kit/issues/626#issuecomment-791901376) was great at the time but now I'm facing an issue. [Check out this repo please](https://github.com/babakfp/sapper-layouts-and-error-page-issue)

**Comment by Florian-Schoenherr** [comment]
@babakfp `layouts[path] ??  layouts[path+"/"] ?? Default;` don't know how ts works but something like that

**Comment by hitrust** [comment]
I’m just a newbie.
Maybe SvelteKit can use jinja2's template pattern.  Then no need to reset layout. just import the right layout using the right layout‘s path and then import it. It's more flexibility and explicit.

src/routes/$layout.svelte
src/routes/index.svelte
src/routes/foo/$layout.svelte
src/routes/foo/index.svelte
src/routes/foo/bar/index.svelte

<---src/routes/index.svelte---->
import ‘$layout.svelte’

<---src/routes/foo/index.svelte---->
import ‘foo/$layout.svelte’

<---src/routes/foo/bar/index.svelte---->
import ‘$layout.svelte’

**Comment by Florian-Schoenherr** [comment]
A Huge thanks! @Rich-Harris 🎉 🎉
