### ISSUE TITLE
 `Typescript` doesn't show an error when trying to return an array in `load` function

### ISSUE THREAD

**Issue by ivanhofer** [sveltejs/kit#6261]
The return type of the `load` function has to be a `Record`.
`Typescript` doesn't show an error when you trying to return an array.

_I opened this issue because I first thought `SvelteKit` incorrectly converts arrays to an object. I have updated the issue_

# original issue

### Describe the bug

When returning an `Array` from a `load` function, the `+page.svelte`'s `data` prop receives it as an array like object instead of a real object.

_input_
```ts
['some', 'items']
```

_output_

```ts
{
   0: 'some',
   1: 'items'
}
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-q6unzn?file=src/routes/+page.svelte

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: next => 1.0.0-next.437 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by ivanhofer** [comment]
Ah, I just realised that this now must be a `Record`. But `TypeScript` also allowes to return an `Array`...

**Comment by ivanhofer** [comment]
Interesting.. when using `Record<string, any>` returning an `Array` is valid and by changing `any` to `unknown` it correctly shows an error:

```ts
const load = (): Record<string, any> => {
	return [] // this is valid
}

const load2 = (): Record<string, unknown> => {
	return [] // this is an error
}
```

https://www.typescriptlang.org/play?#code/MYewdgzgLgBANiAhgExgXhgCgJQC4YBKApqAE7IA80pAlmAOYA0MiYAngHzpcDeAUAEhSRKAFdSYGAG0AunwC+fPqEiwEKAEzoseQiRDkqUWg2aiwAazAgA7mC5peg4WInS5ioA

**Comment by ivanhofer** [comment]
I have submitted an issue https://github.com/microsoft/TypeScript/issues/50439.

Meanwhile: does anything speak against using `Record<string, unknown>` to type `OutputData`?

**Comment by dummdidumm** [comment]
My hesitancy is that people would be forced type-cast all their data accesses, `Record<string, any>` is already pretty loosey-goosey which is ok if people opt in to not worrying about type checks. Making it `Record<string, unknown>` would be an awkward middle ground.

**Comment by ivanhofer** [comment]
Ok, I now have tried out a three different use cases with the current implementation.

[link to playground examples](https://www.typescriptlang.org/play?#code/PTAEFsHsGMGtUgM1AcwKYDs0CcCGAXNAE1AAMAFXdAGUlyNNHwE8AHNAKBfdEprqIAeAPIBXfK3EARArlBoAHoQxEAzqABKaaJGxDV+bAEsMKADShcGZgD5QAH1AA3SEZIBeTdt37DJ85bWdo4ubnaeABQAlKDudmIS0rIcHCCgAIwAdKBEkBgA5PigoqpoZHxotPSM+JBMbGWkADYCpBwA3hwAkGkARvQAXKAAkqDQVqDYaPii2BjyTjjM+AAW-t1powDukKJNJBiQRehFVsygaxj46nlMK41VRACii1eMrLh44Ex1uNDQaFU6lIHy+qkY02gmW6OgwBlALXosVA0Vidk6XS6Uxmc1AAG0ALrdAC+KR6YBQkEgRCGFCoaBk+FwjFghy26i2KwIZERDEm01mcO63DKFUZck8AEEtrgjIQhFocRgACoNQQipAIgQ2GwbMCgA2Gw0APQA-BxSakwAAmbIlfyTXBbcr0x5tDGw+G8oYVR7I1FxUAYrEC3GE0BpIxA0RoIajcbzbGCwKWbB4ZgksmR6Oxl3ocWMXKA0CHIpTXBNJrnVmQZ2c7nNVr8pWqPVjXb7UC9MqqSBNRYkXrnFb4CSqAYgFBylaiXqZHTgYDgIzQbCQXuIfDAVXsADKq6MrC3UdUMdUwAALAB2ACc1oADMKGrx6eLkdLZfLBIrBTu0OqGk1XkdTbI0wLNC0UjSABmbJCErPNKibesim2KwilqZtBQ6NtKWpONUGmeQ010Dl7nmUYk1xXtwGmS4UFALY11MNt+hpEYLlwRYfggKxRArKt6h4OUYTyL0BB9V0BEEdpQDcIYDGMUxQGJcIURiQNgyo+ZZPk0B8nSfIVMzXCqXYul81kFk2TIhteUYbTWy6EUX0spl3xlOViG-UMVTVDVkGA3VyTA8DzVYwYOJ0PYSG0lNPnTUS4SKXlrUk-h6EERT-EJNSA3RboQyVfEiS6UlSSAA)

To be as safest as possible only use case 3 can be really used right now.

When choosing `unknown` for the record `OutputData extends Record<string, unknown> | void = Record<string, unknown> | void` we would get the following:

[link to playground examples](https://www.typescriptlang.org/play?#code/PTAEFsHsGMGtUgM1AcwKYDs0CcCGAXNAE1AAMAFXdAGUlyNNHwE8AHNAKBfdEprqIAeAPIBXfK3EARArlBoAHoQxEAzqABKaaJGxDV+bAEsMKADShRGWBkgB3DAD5QAH1AA3SEZIBeTdt19QxNzS2tbB2c3T29nPwAKAEpQH2cxCWlZDg4QUABGADpQIkgMAHJ8S1U0Mj40WnpGfEgmNhrSABsBUg4Abw4ASFyAI3oALlAASVBoXAxQbDR8UWx5tHccZnwACxDBkfGp0DtIUQ6SW0r0SrnmUF2MfHVSpm32hqIAUQ3HxlZcPDgJgtXDQaBoVTqUj-QGqRhLaAFQY6DAGUBdegpUBJFLOfoDAaLZarUAAbTyFgATBYAMwAXUGAF9skMwChIJAiBMKFQ0DJ8LhGDZ7Oo7NsCGQMQwFksVqjBtwanV+XI-ABBOy4IyEIRaYkYAAqbUEiqQ6IEjkc+zAoFtdrtAD0APwcZk5MCUoqiVQhBa4Oy1XkfHr43KIIwKCETaazeZEuWgOaJ7B4ZjI0poqUTOofLE41KgfGE2Uk0kMgZu1mgUZcwPoFWMEoQ0CXGW4DodO7CgNiiWdboy-Wqa0zU7nas1VSQDobEjDO7bfASVRjEAobXbUTDAo6cDAcBGaDYSBTxD4YBG9gAZSPRlY56MkNEEOAABYAOwATkpAAYR0QIUMSBmBXXheRVApvRwY4xwuewJzIKxuwwRgTAMNBMTNUhbkYBU2jA+tZCxDUtR1QQ9TlS80BNNozSlS0R3tJjnVdbJchpIpCA7Ot6gHXtKmmTVHmBQc5T6Ed2U5aNUCWeQU10UU3nmaZ4xJKdwCWB4UGOY9TBHGtpPFDYRPAOZRHbTtWh4bV01RSoswI3j6EEXpQG8CYDGMUxQEZOJsWSAsi1U+ZXPc0AyjyMofKZFlckk2seUIgUhQiRS+ylRhguHAZFUclViM1bViHIktDWNU1kHoq0qyY+0WJHcNI1AmNYNEkkkwBVNbMzARKWzIMBEETyQjLPz8zxQZi31Mly2ZZkgA)

(_look for `'fixes'` and `'destroys'` comments_)

This would solve the issue of but as you correctly noted, this would mean that in use case 2 the `data` object each property would be `unknown` and would need to be checked in order to get rid of TypeScript errors. So this isn't really an option.

There is also a middle ground when typing just the `extends` clause with `unknown` like this `OutputData extends Record<string, unknown> | void = Record<string, any> | void`:

[link to playground examples](https://www.typescriptlang.org/play?#code/PTAEFsHsGMGtUgM1AcwKYDs0CcCGAXNAE1AAMAFXdAGUlyNNHwE8AHNAKBfdEprqIAeAPIBXfK3EARArlBoAHoQxEAzqABKaaJGxDV+bAEsMKADShRGWBkgB3DAD5QAH1AA3SEZIBeTdt19QxNzUFwMZmc3T29nPwAKAEpQH2cxCWlZDg4QUABGADpQIkgMAHJ8S1U0Mj40WnpGfEgmNhrSABsBUg4Abw4ASFyAI3oALlAASVBocNBsNHxRbAx5dxxmfAALEMHc6btIUQ6SW0r0SvDmUB2MfHVSpi32hqIAUXW7xlZcPHAmFq4aDQNCqdSkH5-VSMRbQAqDHQYAygLr0FKgJIpZz9AYDBZLFagADaAF1BgBfbJDMAoSCQIgTChUNAyfC4Rg2ezqOxbAhkVEMeaLZZIwbcGp1VlyPwAQTsuCMhCEWgJGAAKm1BOKkCiBI5HHswKBjSaTQA9AD8HEpOTAACYiqJVCF5rg7LVma8ejjEciBRM6q90ZjUqAcXjhYTSaBckYwaI0BNprNVviRWFVr88MwKVTY-HEx70FLGCVQaAzkLcB0OtdOe6eXzOt0harVIaZkcTqBhjVVJAOusSMNrlt8BJVGMQChFVtRMMCjpwMBwEZoNhIP3EPhgBr2ABlddGVg7uOqBOqYAAFgA7ABOO0ABjFbV4zKl6LlCqVghVIr3aBam0OoCvqHamhBlrWtkuQAMxFIQNZFvULaNpUBzhJUzStiKfQdrS9JJqgizyNgG7YNyzyrNMaaEv24CLLcKCgHYG6mB2owMlMNy4OsAIQOEojVrWrQ8IqCKlH6AgBp6AiCL0oDeBMBjGKYoDknEGLJKG4a0asClKaAZR5GU6m5vhdJcUyxayByth2JRTYCowentgM4pvjZbKfvKirEL+kbqpq2rIKBBrUhBkFWh2iBGAooJEToxwkHpGZhGRuA5gMvqVAKdoyfw9CCCpISkppIbYoMEaqsSZIDJSlJAA)

(_look for the single `'fixes'` comment_)

This then would make use case 3 more typesafe and would not affect the other usecases.

**Comment by dummdidumm** [comment]
This is a good middle ground 👍 I'll incorporate this into another change I'm planning to make.

**Comment by ivanhofer** [comment]
Maybe you could also check other appearences of `Record<string, any>` in the repo?

**Comment by leumasme** [comment]
I can't fully follow the discussion, but have found this issue and am experiencing the original problem.
```ts
// +page.ts
import type { PageLoad } from "./$types";

export const load = (() => {
    return [1, 2, 3];
}) satisfies PageLoad;
```
(Written explicitly with export const & satisfies for demonstration - same result when just exporting a function)  
Does not throw a type error, but errors at runtime.
I am using
```
+-- @sveltejs/adapter-auto@2.1.0
+-- @sveltejs/kit@1.22.3
+-- svelte-check@3.4.6
+-- svelte@4.1.1
```
(as installed by the create-svelte package just today)  
Since this issue is closed for nearly a year now and I am, I'd expect this to be solved.  
Was there a regression or am I missing something?
