### ISSUE TITLE
`+page.svelte` in deepest route is not getting `errors` prop 

### ISSUE THREAD

**Issue by pilcrowOnPaper** [sveltejs/kit#6264]
### Describe the bug

I tried to open a new PR but I even can't get a fresh fork to pass tests so I'm opening a new issue

For a very simple project like so:

```
/+page.svelte
```

the "route pyramid" in root.svelte looks like this:

```html
{#if components[1]}
	<svelte:component this={components[0]} data={data_0}>
		<svelte:component this={components[1]} data={data_1}/>
	</svelte:component>
{:else}
	<svelte:component this={components[0]} data={data_0} {errors} />
{/if}
```

and the deepest page component is missing the `errors` prop. The problem is in `/src/core/sync/write_root.js`:

```js
let pyramid = `<svelte:component this={components[${l}]} data={data_${l}}/>`;
```

should be fixed to

```js
let pyramid = `<svelte:component this={components[${l}]} data={data_${l}} {errors}/>`;
```

### Reproduction

.

### System Info

```shell
.
```

### Severity

serious, but I can work around it

**Comment by mustofa-id** [comment]
I'm sorry @Rich-Harris but looks like the issue is still there. Here's a [repro](https://stackblitz.com/edit/sveltekit-errors-props-repro).
