### ISSUE TITLE
The new data prop not useful with binding

### ISSUE THREAD

**Issue by stalkerg** [sveltejs/kit#6268]
### Describe the bug

Before changes, we have just props:
```js
export let tags = [];
```
And it perfectly works with binding, but now we are using reactive assignment:
```js
export data;
$: ({ tags = [] } = data);
```
(from https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3292707)

And this combination (reactive assignment from export props) it's not working with bindings. 
As I understand, it's primarily a Svelte feature than a bug, and it's why we should probably have a workaround in SveltKit. 

A bit of context: I can't use `invalidation` because my load function returns ten different heavy props, and I want to change only a few of them without touching the `load` function again; it's why I am using `bind`.

### Reproduction

https://svelte.dev/repl/3aefe1af8d0546bab15c187e1be9a332?version=3.49.0

### System Info

```shell
System:
    OS: Linux 5.18 Gentoo Linux
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 6.23 GB / 31.26 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    npm: 8.15.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.87 => 1.0.0-next.87 
    @sveltejs/adapter-static: 1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: 1.0.0-next.437 => 1.0.0-next.437 
    @sveltejs/svelte-virtual-list: github:sveltejs/svelte-virtual-list => 3.0.1 
    @sveltejs/vite-plugin-svelte: ^1.0.2 => 1.0.2 
    svelte: 3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

blocking all usage of SvelteKit

**Comment by M4rk3tt0** [comment]
In your App.svelte you don't need to export data, just declare the variable. Like this

```
<script>
	import Tags from './TagsManipulation.svelte';
	let data = { tags: [1, 2] };
	$: ( {tags = []}  = data);
</script>

<Tags bind:tags />
{tags}
```

And it will work.

**Comment by Rich-Harris** [comment]
Can't you do

```js
export let data;
let { tags } = data;

afterNavigate(() => {
  tags = data.tags;
});
```

?

**Comment by stalkerg** [comment]
Thanks, it's working fine! But:
1. Looks like hacky. 
2. Because I have many props it's looks very heavy:
```js
 let {
    post,
    tags = [],
    user,
    moderator,
    fileUrl,
    position,
    similarPictures = [],
    tiedPictures,
    isStarIt,
    favoritesUsers = [],
    env,
    sessionUser,
    loading = false,
  } = data;

  afterNavigate(() => {
    ({
      post,
      tags = [],
      user,
      moderator,
      fileUrl,
      position,
      similarPictures = [],
      tiedPictures,
      isStarIt,
      favoritesUsers = [],
      env,
      sessionUser,
      loading = false,
    } = data);
  });
```
I really don't like such a boilerplate, also update pipeline now has different timings (update everything in afterNavigate).

**Comment by stalkerg** [comment]
In Svelte1 and Svelte2, we had a `data` state, Svelte3 made a much more clean solution with `export` specific props, and now in SvelteKit we are back to the old ages. Yes, the component can still export many props, but what is different if the page component doesn't support it? 
Anyway, if we can fix it in Svelte, it will not be an issue.

**Comment by M4rk3tt0** [comment]
What about this? 
If you bind tags to data.tags you can see in the console log that both data and tags are in sync.

```
<script>
	import Tags from './TagsManipulation.svelte';

	export let data = { tags: [1, 2] };
	$: ({ tags = [] } = data);

	$: console.log('tags', tags);
        $: console.log('data', data);
</script>

<Tags bind:tags={data.tags} />
{tags}
```

**Comment by Rich-Harris** [comment]
Good point! https://svelte.dev/repl/4c340722ed8a4cfd860763c779683412?version=3.49.0 seems like exactly what you want

**Comment by f-elix** [comment]
Or just don't use the `data` prop and bind it with the page store?

```ts
$: ({ tags = [] } = $page.data);
```

**Comment by Rich-Harris** [comment]
I suppose the issue with `bind:tags={data.tags}` is that invalidating `data.tags` has to invalidate all of `data`.

That said, I'm going to close this issue as `export let data` isn't going anywhere — it has too many benefits relative to this one downside. There's a variety of ways to get the behaviour you want, such as returning a writable store from `load`, or using the `afterNavigate` hook (you don't need to reset _every_ property, just the ones you're plucking out of `data` in order to mutate them locally).

**Comment by stalkerg** [comment]
Okay, thanks. It will be good to add something like this to the documentation.

**Comment by AlexRMU** [comment]
You can also use the key for the entire page:
```svelte
<!-- +page.svelte -->
<script lang="ts">
    import Page from "$lib/Page.svelte";
    import type { PageData } from "./$types";
    export let data: PageData;
</script>

{#key data}
    <Page prop={data.prop} />
{/key}
```
<sub>(yes, it's not very good for rendering, but it's easier than writing destructurizations, afterNavigate and onMount in a bunch of components)</sub>
