### ISSUE TITLE
App.PageData type only appears within routes

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#6283]
### Describe the bug

(or maybe "doesn't appear outside of routes")

Using the same import from `$app/stores` in a route (or layout) and a.n.other file (e.g. a custom store in $lib) one includes the `App.PageData` types and one doesn't.

<img width="671" alt="Screen Shot 2022-08-25 at 12 10 04 PM" src="https://user-images.githubusercontent.com/304910/186738792-98f55aad-5490-4cad-aa34-e866534e05ee.png">

<img width="707" alt="Screen Shot 2022-08-25 at 12 09 48 PM" src="https://user-images.githubusercontent.com/304910/186738809-ef7a83f9-9aea-47a2-816b-66906f05c4b9.png">

### Reproduction

.

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 445.23 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5260.0
    Firefox: 103.0.2
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/adapter-node: next => 1.0.0-next.87 
    @sveltejs/kit: next => 1.0.0-next.440 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

annoyance

### Additional Information

Minor, but may confuse some people (and the typing is lost for the derived store in this case unless added back manually)

**Comment by dummdidumm** [comment]
I can't reproduce this. Please provide a proper reproduction. Maybe you need to restart the Svelte and TypeScript language servers (or just restart VS Code) - if you have updated to the latest version and didn't do that, it may be stuck on old typings.

**Comment by CaptainCodeman** [comment]
Yes, I just needed a restart. It threw me seeing it correctly updated in once place.
