### ISSUE TITLE
svelte-kit demo app not working correctly with typescript option

### ISSUE THREAD

**Issue by kuehlc** [sveltejs/kit#6289]
### Describe the bug

I ran the commands for making a new app on https://kit.svelte.dev/. I chose typescript for the option and when I go to the 'todos' page of the app after running it, any action I do requires a refresh of the page to show the change. I ran the same commands but chose javascript with the type docs and it works fine for that option. Is this an issue with how the demo-app is auto built when typescript is chosen as the option, or is there a deeper typescript compatibility issue to where I should avoid using it for now? I'm new to svelte and svelte-kit by the way..

### Reproduction

The reproduction is following the instructions to build a demo app with svelte-kit on this page: https://kit.svelte.dev/. Then, choose typescript and say yes to all of the options.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 1.48 GB / 15.89 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.19041.1566
```

### Severity

serious, but I can work around it

### Additional Information

By 'work around it' I mean I have to use the javascript option instead.

**Comment by Rich-Harris** [comment]
I'm afraid I can't reproduce this in a freshly created TypeScript app with `npm create svelte@latest`

**Comment by kuehlc** [comment]
After rebuilding for a 3rd time, it works now for some reason. I do get an issue occasionally where it throws an error for me deleting an item, but I'm not sure how to reproduce it, since it seems random. Closing for now I suppose.
