### ISSUE TITLE
🐛 Symlink routes no longer work (1.0.0-next.432 — PR #6174)

### ISSUE THREAD

**Issue by oneezy** [sveltejs/kit#6303]
### Describe the bug

Symlink routes / Symbolic link routes are no longer working since Sveltekit version `1.0.0-next.432` [(PR #6174)](https://github.com/sveltejs/kit/pull/6174)

### Reproduction

**1.0.0-next.431** (working)
✅ https://github.com/oneezy/sveltekit-symlink-repro-next-431

**1.0.0-next.432** (broke)
❌ https://github.com/oneezy/sveltekit-symlink-repro-next-432

![image](https://user-images.githubusercontent.com/7369575/187002410-3f58ccb9-8b14-419e-b5e8-15b0a606c708.png)

### Logs

```shell
Error: Not found: /symlink
    at resolve (file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/runtime/server/index.js:430:14)
    at Object.handle (file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/vite/dev/index.js:318:66)
    at respond (file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/runtime/server/index.js:213:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/oneezy/Desktop/www/10.Repros/sveltekit-symlink-repro-next-442/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.442_svelte@3.49.0+vite@3.0.9/node_modules/@sveltejs/kit/src/vite/dev/index.js:375:22
```

### System Info

```shell
System:
    OS: Windows 11
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 15.50 GB / 31.75 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: 1.0.0-next.406 => 1.0.0-next.406 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking all usage of SvelteKit

### Additional Information

We use a [monorepo](https://github.com/oneezy/monorepo) with multiple separate apps that we link together via symlink routes so this one's a showstopper for us.

**Comment by oneezy** [comment]
I believe the issue is somewhere around here:
[kit/src/core/sync/create_manifest_data/index.js](
https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/create_manifest_data/index.js#L159-L161)

Doing a little research I found the symlink issue was fixed by @mikenikles in PR [#4957](https://github.com/sveltejs/kit/pull/4957)

### The Fix [(commit eb2ab91)](https://github.com/sveltejs/kit/commit/eb2ab91338e10d081191f493e3e75abd6ad760d2?diff=split)
> As per @Conduitry's comment, this would error on symlinks to files, as `readdirSync` throws when not called on a directory.
>
> There seems to be a problem with Node's `fs.readdirSync(dir, { withFileTypes: true })` returning `false` for `isDirectory()` on symlinks (open issue at https://github.com/nodejs/node/issues/30646). It doesn't seem likely to get fixed upstream in a timely manner, so reverting to `fs.statSync` instead of `withFileTypes` seems like a better solution.
>
_Originally posted by @mrkishi in https://github.com/sveltejs/kit/pull/4957#pullrequestreview-974512804_

---
With the recent rewrite from @Rich-Harris  I believe this was accidentally written back to the old `withFileTypes: true` way on [create_manifest_data/index.js : lines 159-161](https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/create_manifest_data/index.js#L159-L161)
```javascript=
const files = fs.readdirSync(dir, {
    withFileTypes: true
});
```

**Comment by oneezy** [comment]
# `#HelpWanted`

I hacked away on this a bit but didn't have any luck.
PR #6174 refactored quite a bit of the code from it's previous state.

![image](https://user-images.githubusercontent.com/7369575/187565304-179ff827-6511-4b5d-9455-b081ca5d3697.png)


PR #4957 before and after fix for symlinks 

![image](https://user-images.githubusercontent.com/7369575/187564512-e3592741-e672-44b2-bf22-d4918b61a4f2.png)

**Comment by myhrmans** [comment]
Same issue applies on Linux.
