### ISSUE TITLE
Arrays returned by endpoints (page or layout) are transformed into objects

### ISSUE THREAD

**Issue by SiegfriedEhret** [sveltejs/kit#6305]
### Describe the bug

I have this `+page.svelte`:

```svelte
<script lang="ts">
	import type { PageData } from './$types';
	export let data: PageData;
</script>

<pre>{JSON.stringify(data, null, 2)}</pre>
```

And this `+page.ts`:

```ts
/** @type {import('./$types').PageLoad} */
export function load() {
	return ['42', '9000'];
}
```

In my page, I get this:

<img width="144" alt="image" src="https://user-images.githubusercontent.com/537567/186864314-de6c1780-4f13-46b5-906a-079a8c3272b6.png">

Since layout data are merged into children pages data, I understand that we must work with objects, but I would love to see a note in the docs about this.

### Reproduction

https://github.com/SiegfriedEhret/svelte-request/tree/main/src/routes/test

### System Info

```shell
❯ npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1
    Memory: 216.27 MB / 16.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.17.0 - ~/.local/share/nvm/v16.17.0/bin/node
    npm: 8.18.0 - ~/.local/share/nvm/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox Developer Edition: 105.0
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66
    @sveltejs/kit: next => 1.0.0-next.442
    svelte: ^3.46.0 => 3.49.0
    vite: ^3.0.8 => 3.0.9
```

### Severity

annoyance

**Comment by IvankoB** [comment]
Me confirm it too. The array object returned by endpoint looses its 'length' property on client side thus considered as non-iterable Affecting to Svelte's #each is very nasty. 
The workaround as iteration over Object.keys() causes convinient index functionality of #each be unavailable.

**Comment by dummdidumm** [comment]
This is the expected behavior. The data of parent layouts and the data of the whole page need to be collected into one object, which is why arrays won't work. I think the serialization checker should take this into account.

**Comment by SiegfriedEhret** [comment]
Yes, the [docs](https://kit.svelte.dev/docs/load) mention that `load` "can only return data that can be serialized as JSON". And arrays (or values) are valid JSON: https://www.json.org/json-en.html, so I think a note in the docs on that contraint would be useful.

**Comment by IvankoB** [comment]
data of the whole page need to be collected into one object
 ====================
At a glance array is one object.
 
Client iteration over Object.values(data) may break 2-way bindings to 'data'

And another approach :
```
{#each` Object.keys(data) as key }
   <div>data[parseInt(key)/*to cope with non-integer array index complain*/].some_field</dib>
{/each}
```
is ugly

**Comment by IvankoB** [comment]
From a tutorial :
==============
```
const tweets = tweetsOfUsers/*array findMany-ed from prizma's DB*/.map((tweet) => {
		return {
			id: tweet.id,
			content: tweet.content,
			likes: tweet.likes,
			posted: timePosted(tweet.posted),
			url: tweet.url,
			avatar: tweet.user.avatar,
			handle: tweet.user.handle,
			name: tweet.user.name,
			liked: likedTweets.includes(tweet.id)
		}
	})
return tweents	
```

**Comment by M4rk3tt0** [comment]
Change it to this:

`+page.svelte`:
```
<script lang="ts">
	import type { PageData } from './$types';
	export let data: PageData;
</script>

<pre>{JSON.stringify(data.result, null, 2)}</pre>
```

`+page.ts`:
```
/** @type {import('./$types').PageLoad} */
export function load() {
	return {result: ['42', '9000']};
}
```
and you will get the array back.
![image](https://user-images.githubusercontent.com/7859305/186896695-828e3464-a80d-4c9b-b1a7-1f05683a5a89.png)

**Comment by SiegfriedEhret** [comment]
Thanks @M4rk3tt0, this is exactly what I did to solve the initial issue.

Also, thanks @dummdidumm for https://github.com/sveltejs/kit/pull/6313 !

**Comment by IvankoB** [comment]
A bit hacky, needs to be documented with the 'result' example ))

**Comment by Rich-Harris** [comment]
I think the docs are clear enough now that we don't need to keep this issue open

**Comment by SiegfriedEhret** [comment]
Awesome! Thanks a lot folks! 😘
