### ISSUE TITLE
Vercel edge functions producing a null error from @sveltejs/kit next.433

### ISSUE THREAD

**Issue by SG60** [sveltejs/kit#6308]
### Describe the bug

@sveltejs/kit next.433 (this PR: https://github.com/sveltejs/kit/pull/6179) seems to have introduced a bug with Vercel edge functions. The edge functions consistently crash

### Reproduction

1. kit 433 with Vercel edge functions: https://github.com/SG60/kit-433-error/tree/36670af2556b9b832b4b7fc47be807a7bc120e0d
_this has an error_
3. kit 433 without edge functions: https://github.com/SG60/kit-433-error/tree/b2e212d73dd297ac54fece7ec8e834657b9967dc
_this works_
5. kit downgraded to 432 with Vercel edge functions: https://github.com/SG60/kit-433-error/tree/c02648f00e9d9812b4dfdaa74a00cab0f93c930e
_this works_

### Logs
(These are from Vercel's function logs)
```shell
TypeError: Cannot read properties of null (reading 'handleError')
    at ../../../../.svelte-kit/output/server/index.js:2455:27
    at ../../../../.svelte-kit/output/server/index.js:2404:12

[GET] / reason=EDGE_FUNCTION_INVOCATION_FAILED, status=500, user_error=true
```

### System Info

```shell
Vercel
```

### Severity

blocking an upgrade

**Comment by mquandalle** [comment]
I had a similar issue and had to update the `@sveltejs/vercel-adapter` to fix it.

**Comment by SG60** [comment]
Annoyingly I'm already using the newest version of `vercel-adapter` (next.68), so I don't think it's that.

**Comment by dennisregalado** [comment]
Using the newest version of the `vercel-adapter` & experiencing the same issue on Edge functions.

**Comment by ZetiMente** [comment]
Have you looked at https://github.com/sveltejs/kit/issues/5873 ?
