### ISSUE TITLE
Layout/page data typescript bugs

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6316]
### Describe the bug

I've found a couple of weird things related to the data returned by layout or page.

```
// /src/routes/+layout.ts

import type { LayoutLoad } from "./$types";

export const load: LayoutLoad = async ({ parent }) => {
  const data = await parent();

  return {
    ...data,
    foo: "bar"
  };
};
```

```
// /src/routes/+layout.svelte

<script lang="ts">
  import type { PageData } from "./$types";
  export let data: PageData;

  console.log("/+layout.svelte", data.foo);
</script>

<slot />
```

So far so good, everything has the correct type.

But if I add a new route, things get weird:

```
// src/routes/route/+page.ts

import type { PageLoad } from "./$types";

export const load: PageLoad = async ({ parent }) => {
  const data = await parent();

  console.log("/route/+page.ts", data.foo);

  return {
    ...data,
    xyz: 123
  };
};
```

Here `data.foo` is still `string`, no problem, but here it's not:

```
// src/routes/route/+page.svelte

<script lang="ts">
  import type { PageData } from "./$types";
  export let data: PageData;

  console.log("/route/+page.svelte", data.foo);
  console.log("/route/+page.svelte", data.xyz);
</script>

Hello to the item
```

The problem is that `data` itself is an `any` type here for some reason.

And if I add yet another subroute, `data` becomes `{}`:

```
// src/routes/route/subroute/+layout.ts

import type { LayoutLoad } from "./$types";

export const load: LayoutLoad = async ({ parent }) => {
  const data = await parent();

  console.log("/route/subrout/+layout.ts", data.foo);
  console.log("/route/subrout/+layout.ts", data.xyz);

  return {
    ...data,
  };
};
```

This generates an actual TS error: `Property 'foo' does not exist on type '{}'.ts(2339)`.

### Reproduction

https://github.com/kevinrenskers/sveltekit-data-repro

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 616.89 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66
    @sveltejs/kit: next => 1.0.0-next.443
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by CaptainCodeman** [comment]
I have the same thing, types seem to get "stuck" on an old version. I sometimes just have to restart vs.code to make it sync up and get back in step.

**Comment by kevinrenskers** [comment]
This is not just an VSCode problem, `npm run check` gives errors as well.

**Comment by david-plugge** [comment]
Restarting the ts server works for me but it's really annoying having to do that so often

**Comment by dummdidumm** [comment]
The problem is that the project is in a temporary invalid state. A layout without a page underneath doesn't make sense, so the manifest does not generate the correct parent/child relationships for this.

The "type not updated until restart" sounds like a different problem. For those encountering it: Does it only happen in Svelte files or inside TypeScript files, too?

**Comment by kevinrenskers** [comment]
I've updated my repro repo to add some more files, and now I get the problem that inside of `routes/route/subroute/+page.svelte` and `routes/route/subroute/+layout.ts` `data.xyz` can't be found, even though it was declared on the level above. I also hit this problem in my actual big project.

`Property 'xyz' does not exist on type 'LayoutData'`

**Comment by kevinrenskers** [comment]
I guess parent only loads data from the layout load files, not page load files? 🤔

**Comment by kevinrenskers** [comment]
Ok so it does indeed seem that the data is only loaded within the layout tree. So it seems I have to create a bunch of empty `+layout.svelte` files (just containing a `<slot />`), to move the data tree to a `+layout.ts` file instead of a `+page.ts` file. This is rather cumbersome, but not impossible. But before I go make this changed; am I correct in what I think? And if so, is this something that could be improved or is this as designed?

**Comment by dummdidumm** [comment]
That is correct, parent data only comes from the layouts above .
There's an open feature request to not require a `+layout.svelte` if app you want to do is load data, so this would become easier then.

**Comment by kevinrenskers** [comment]
Ok cool, in that case I can close this issue.
