### ISSUE TITLE
service-worker builder does not provide constant replacement from vite.config

### ISSUE THREAD

**Issue by pfz** [sveltejs/kit#6329]
### Describe the bug

When using [vite/define](https://vitejs.dev/config/shared-options.html#define), constant replacement works as expected for the main app, but the define configuration is not reproduced to the service-worker builder [`@sveltejs/kit/src/vite/build/build_service_worker.js`](https://github.com/sveltejs/kit/blob/1e28edb90a3c501e843e0bc2ac0e4b1f42b078e0/packages/kit/src/exports/vite/build/build_service_worker.js), so no replacement.

### Reproduction

example of configuration for `vite.config` : 
```js
export default defineConfig(({ command, mode }) => {
	/** @type {import('vite').UserConfig} */
	const config = {
		plugins: [sveltekit()],
		define: {
			__MYVAR__: 'foobar'
		}
	};
}
```

and my `service-worker.ts` :
```ts
import { build, files, version } from '$service-worker';

const ASSETS = `cache${version}`;
const SW_VERSION = __MYVAR__;

//...
```

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 5.85 GB / 15.33 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    Yarn: 3.1.0 - ~/.npm-global/bin/yarn
    npm: 8.17.0 - ~/.npm-global/bin/npm
  Browsers:
    Chromium: 104.0.5112.101
    Firefox: 91.13.0esr
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: ^1.0.0-next.443 => 1.0.0-next.443 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
This one is tricky as Vite doesn't have a concept of a 'service worker build', just SSR or not-SSR. Options:

1. pass through certain properties from the main config (e.g. `define`)
2. add an option to the plugin like `sveltekit({ serviceWorkerConfig: vite.UserConfig })` 

Option 1 would be a breaking change. Option 2 is probably the better choice, and could be done in a non-breaking way, but I'm going to mark this as 'breaking' in case we decide the other way

**Comment by Tal500** [comment]
> This one is tricky as Vite doesn't have a concept of a 'service worker build', just SSR or not-SSR. Options:
> 
>     1. pass through certain properties from the main config (e.g. `define`)
> 
>     2. add an option to the plugin like `sveltekit({ serviceWorkerConfig: vite.UserConfig })`
> 
> 
> Option 1 would be a breaking change. Option 2 is probably the better choice, and could be done in a non-breaking way, but I'm going to mark this as 'breaking' in case we decide the other way

I'm not sure about what kit do to web workers, but I know that vite inject the environment (including the definitions at 'define'), by injecting an import statement:
https://github.com/vitejs/vite/blob/e7712ffb68b24fc6eafb9359548cf92c15a156c1/packages/vite/src/node/plugins/worker.ts#L223-L242

**Comment by Rich-Harris** [comment]
We discussed this offline and decided that the best move for now is to copy over `define` from the main config. If needs arise we can look into option 2 later. Both courses of action are non-breaking, so I'm removing the label

**Comment by pfz** [comment]
I think option 2 is the cleanest.
Though option ~1, ie copying define, might be breaking in peculiar situations where people knowing this bug/feature, added their own replacement mechanism, AND would have same constants name. Highly improbable, but still ?

Any way, thanks a lot !
