### ISSUE TITLE
Disconnect page from router

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#6331]
### Describe the problem

Let's say I have the routes `/main` and `/[profile]`. `/main` has a Google Analytics script set up, but this script shouldn't be running when the user navigates to `/[profile]`

Each `/[profile]` page may or may not have it's own Google Analytics script set up. This script shouldn't be running when the user navigates to any other page.

### Describe the proposed solution

A way to completely disconnect a page from client side routing, so no state moves from/to a page.

### Alternatives considered

The page option `router = false` can be set, but that only disables client side routing when navigating _away_ from a page

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
If I understand correctly, you want to do a full page reload instead of a client side navigation. Can't you use [sveltekit:reload](https://kit.svelte.dev/docs/a-options#sveltekit-reload) on all related links?

**Comment by probablykasper** [comment]
Ah I didn't think of that. Now that I looked further, it seeme like `beforeNavigate` would be a great fit, if I could somehow figure out if a URL is `/[page]`.

Using `sveltekit:reload` would be a bit challenging because there are many links that are used both in `/main` and in `/[page]`. I'd have to create my own link component that conditionally applies `sveltekit:reload`, and would need to somehow check if a route matches `/[page]`. Would also lose out on `class:` attributes on the elements which is unfortunate. There's also the concern that it could accidentally not be used.

**Comment by david-plugge** [comment]
Not sure if you already know this but it may help you https://kit.svelte.dev/docs/load#input-properties-routeid

**Comment by probablykasper** [comment]
Thanks, though I don't think that would work as I need to know of a URL that's being navigated to is `/[profile]`, before it's loaded

**Comment by dummdidumm** [comment]
Sounds related to the other navigation hooks enhancements we plan to implement.

**Comment by Rich-Harris** [comment]
This is possible now following https://github.com/sveltejs/kit/pull/6552 — you can inspect `from.routeId` and `to.routeId` in `beforeNavigate` and `afterNavigate`
