### ISSUE TITLE
Navigating back to last page doesn't work with `router = false`

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#6332]
### Describe the bug

If a page has specified the page option `router = false`, you cannot navigate back to a previous page using the browser's back button.

### Reproduction

https://github.com/probablykasper/sveltekit-router-false-bug

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 712.65 MB / 32.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.0 - ~/Library/Caches/fnm_multishells/41321_1661559717152/bin/node
    npm: 8.12.1 - ~/Library/Caches/fnm_multishells/41321_1661559717152/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: 1.0.0-next.443 => 1.0.0-next.443 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
The `router` option is no longer supported (replaced with `csr` https://kit.svelte.dev/docs/page-options#csr) so I'll close this issue
