### ISSUE TITLE
Trailing $ after domain name and before img/asset path causing 404 errors

### ISSUE THREAD

**Issue by namangor04** [sveltejs/kit#6338]
### Describe the bug

Hello Team SvelteKit!
First of all, Thank you so much for doing an amazing job with Svelte and SvelteKit!

I am facing some issues with how the `img` tag's `src` attribute's value gets changed automatically. When I put images in the `static` directory, then I should be able to access them using `/images/some-image.png`, but when I use this as the `src` url, the actual url which SvelteKit (or Svelte) uses becomes `localhost:port/$/images/some-image.png`, which is causing `404 not-found` errors.
I have confirmed that the image is available at `localhost:port/images/some-image.png`.

Can someone point out something that I might be doing wrong? Or as I think, this is a bug?

Thank you for your help in advance!

### Reproduction

1. Create a `Skeleton` project with `npm create svelte@latest` using TypeScript Syntax without ESLint, Prettier, Playwright support.
2.  Run `npm install`
3.  Run `npx svelte-add@latest tailwindcss`
4. Run `npm i daisyui`
5. Paste this into `tailwind.config.cjs`:
```js
const config = {
content: ["./src/**/*.{html,js,svelte,ts}"],

theme: {
extend: {},
},

plugins: [
require("daisyui"),
],
};

module.exports = config;
```

6. Make a copy of `favicon.png` in `static/images` directory.
7.  Add `<img src="/images/favicon.png"/>` to `src/routes/+page.svelte`.
8. Run `npm run dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.25188
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.76 GB / 7.88 GB
  Binaries:
    Node: 18.4.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 8.18.0 - ~\scoop\apps\nodejs\current\bin\npm.CMD
  Browsers:
    Edge: Spartan (44.25188.1000.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.25188.1000
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: next => 1.0.0-next.437 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by dominikg** [comment]
Your issue description mentions a deployment, but your incomplete reproduction mentions `npm run dev`? 

Please follow our bug template and provide a repository with a reproduction and include information about your deployment env. (which adapter etc)

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

Note: with our default template, there is no `$` prepended to static assets, see here https://stackblitz.com/edit/sveltejs-kit-template-default-upe7mn?file=src%2Froutes%2F%2Bpage.svelte,.svelte-kit%2Foutput%2Fprerendered%2Fpages%2Findex.html&terminal=dev  ( run `npm run build` in the terminal and check the output html for the image src)

**Comment by namangor04** [comment]
Thank you so much for your prompt reply! And yes, I know that no `$` is prepended to static assets when they are served, but when they are being loaded, the `src` automatically changes to have `$` after `localhost:port` like this: `localhost:5553/$/images/some-image.png`. Sorry for the incomplete reproduction, I have updated the original issue to clarify details.

**Comment by namangor04** [comment]
I'm very sorry! It was my mistake in code which led to this issue. I was writing this code:
```svelte
<img src="${imgPath}" alt="Image {i}" />
```

While what I should have been writing is:
```svelte
<img src={imgPath} alt="Image {i}" />
```

Thank you very much for your help!🙏🏻
