### ISSUE TITLE
Inherit data not only from layout.js load functions

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6342]
### Describe the problem

Currently parent data only comes from the layouts above, not from the pages above, which I find rather confusing. If I have a route that returns data in its `+page.js` load function, then it's accessible in `+page.svelte` - but not in a subroute of that route. For that I have to move the data loading to a brand new `+layout.js` file (which also means having to create a `+layout.svelte` file with just a `<slot />`). 

See also https://github.com/sveltejs/kit/issues/6316.

### Describe the proposed solution

Have parent data not only use the layout load tree, but also the page load tree. 

### Alternatives considered

Keep it as it is, with a bunch of extra files as a result, plus the confusion of why data is available in `+page.svelte`, but not in a subroute's `+page.svelte` when using parent data.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Pages are leaves, they inherit from layouts. It would be super weird if leaves inherited from other leaves. The fact that you currently have to add a `+layout.svelte` if you have a `+layout.js` is a bug, it'll be fixed soon. 

Closing as works-as-intended

**Comment by kevinrenskers** [comment]
I think the way it works now is a bit strange. Like, let's say in a certain route you don't need a custom layout so you load some data in +page.js, together with the parent data from the parent load function. So far so good. Then you add a subroute and you want to access that same parent (page) data. But that's not possible - now you need to move the data loading to a new layout.js file, because of what's happening in a child route. It's not very logical to me. The fact that both layout and page load functions can return data, the page.svelte can use both of them, but child pages can't, is weird.

But ok, not impossible to work with it either so it is what it is.

**Comment by dummdidumm** [comment]
These are distinct pages which could do very different things. Just because one is further below the file tree doesn't mean they are related. The layout is what is shown for both, so it makes sense to inherit from that and not the page.

**Comment by kevinrenskers** [comment]
That makes sense. Thanks!
