### ISSUE TITLE
Types not being generated

### ISSUE THREAD

**Issue by PH4NTOMiki** [sveltejs/kit#6344]
### Describe the bug

`.svelte-kit` folder doesn't have `types` folder even if I manually run `npx svelte-kit sync` on an old project I just migrated.

### Reproduction

I can't provide it, so sorry, please help me without it if possible, if not I'l try to provide one

### System Info

```shell
System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.60 GB / 7.65 GB
    Container: Yes
    Shell: 5.1.12 - /bin/bash
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    npm: 8.13.1 - /usr/bin/npm
  Browsers:
    Firefox: 102.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.39 => 1.0.0-next.39 
    @sveltejs/kit: ^1.0.0-next.444 => 1.0.0-next.444 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
Is typescript installed according to your package.json? It's needed to generate types
