### ISSUE TITLE
`App.PageData` proper typing isn't enforced in layouts

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#6346]
### Describe the bug

Given the following `app.d.ts`:
```ts
declare namespace App {
  interface PageData {
    foo: number;
  }
}
```

If you do the following in a `+page.ts` load function:
```ts
import type { PageLoad } from './$types';
export const load: PageLoad = () => {
  return {
    foo: 'not a number'
  };
};
```
You'll get an error (and rightly so) stating that the type of the property `foo` isn't correct.

However, if you do the same thing in a `+layout.ts` load function:
```ts
import type { LayoutLoad } from './$types';
export const load: LayoutLoad = () => {
  return {
    foo: 'not a number'
  };
};
```
Now you don't get any errors; you should, obviously, `foo` has to be a number.

I actually just spent a relatively long time beating my head against the wall trying to figure out what was wrong with some part of my app and eventually found out it came down to me setting the wrong value for a certain property in my `+layout.ts`, which I wasn't noticing due to there not being any type errors or anything.

### Reproduction

Explained above.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 953.19 MB / 3.77 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    npm: 8.11.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-node: ^1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.445 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.8
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Can't reproduce this, if I paste the code into a `+layout.ts` and generate the types I get 
```
Type '() => { foo: string; }' is not assignable to type 'LayoutLoad<void | (Partial<PageData> & Record<string, any>)>'.
  Type '{ foo: string; }' is not assignable to type 'MaybePromise<void | (Partial<PageData> & Record<string, any>)>'.
    Type '{ foo: string; }' is not assignable to type 'Partial<PageData> & Record<string, any>'.
      Type '{ foo: string; }' is not assignable to type 'Partial<PageData>'.
        Types of property 'foo' are incompatible.
          Type 'string' is not assignable to type 'number'.ts(2322)
```

**Comment by aradalvand** [comment]
@dummdidumm I just noticed that this problem only exists when there's also a `+page.ts`, here you go, a repro: https://github.com/aradalvand/sveltekit-load-typing-problem

![image](https://user-images.githubusercontent.com/26527405/187076883-270b254b-da19-45eb-bfd0-483854210a93.png)
![image](https://user-images.githubusercontent.com/26527405/187076892-2f3bb006-c61d-4dc2-84b1-d928a97eb3a2.png)

**Comment by dummdidumm** [comment]
Still can't reproduce it, I get the expected error in `+layout.ts`

**Comment by aradalvand** [comment]
Wow, that's pretty weird... 🤔
I don't know, maybe you can close this issue and wait to see if this is reported again, if not, then it's probably a glitch on my side. Thanks.

**Comment by dummdidumm** [comment]
Does that mean it's consistently reproducible on your end with your repo, or can't you reproduce it either reliably?

**Comment by aradalvand** [comment]
I can reproduce it like 50% of the time, which is strange.
Sometimes it works as expected and there's an error, sometimes there isn't — for what it's worth, in my actual project I couldn't get it to produce an error no matter how many times I cleared the `.svelte-kit` directory or restarted the TS server, but in the repro I linked above, it fluctuates. Strange.

**Comment by alialaa** [comment]
I think this used to work before but after some update to sveltekit I am currently not getting ts errors in neither pages not layout. Anybody having the same issue?

**Comment by alialaa** [comment]
@aradalvand I think the problem happens if the load function is async. Can you confirm?

**Comment by aradalvand** [comment]
@alialaa It seems like you're right:

![Untitled Project](https://user-images.githubusercontent.com/26527405/187973633-a444e09c-c06e-4943-8523-064d2a15ea00.gif)

Let's see if @dummdidumm can reproduce this now.

**Comment by dummdidumm** [comment]
I think I understand the problem better now.
1. Right now the logic is "if there's a page(.server) file, assume that it has a load function". This isn't always correct. We may need to statically analyze each of those files to see if that's really true
2. (possible bug uncovered while playing around) when I delete a `+page.js` file next to a `layout.js` file the types don't get updated
3. Even with 1 and 2 getting resolved, there's still the "problem" that the type of `LayoutLoad` assumes that it's the `PageLoad`'s job to fill out the required fields. `LayoutLoad` will only get more strict typings if not all children have load functions. I don't see a way to make this work so that it works as wanted here, since this is a cyclic relationship: In order to know what type `LayoutLoad` is, it would need to know what return type `PageLoad` has. To know what type `PageLoad` to restrict to, it needs to know the return type of `LayoutLoad` (properties already set in `LayoutLoad` are no longer required in `PageLoad`).
