### ISSUE TITLE
Bug: components still use the old props design

### ISSUE THREAD

**Issue by Oren-Lindsey** [sveltejs/kit#6347]
### Describe the bug

In https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3292707 the old way of making props:
```
export let prop1
export let prop2
```
was replaced with this:
```
export let data
let {prop1,prop2} = data
```
But this has not been changed for components imported from `$lib`

### Reproduction

[Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-q8wqh1?file=src%2Flib%2FTest.svelte)

### Logs

```shell
n/a
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 4.14 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.66 
    @sveltejs/kit: next => 1.0.0-next.443 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.0.4 => 3.0.9
```

### Severity

annoyance

### Additional Information

If this is kept the same, it should be specified in the docs. Right now it's not, and it took me an hour to figure out why my website was broken

**Comment by Conduitry** [comment]
It's only `+page.svelte` and `+layout.svelte` that had their props replaced with a single `data` prop. For any other component, you can pass whatever props in that you want. I don't think there's anything here that should be documented differently. The existing Svelte tutorial https://svelte.dev/tutorial makes it clear how props work. And the SvelteKit routing migration script will only touch page and layout components, and will leave the other ones alone.

**Comment by Oren-Lindsey** [comment]
Why would you have 2 different kinds of props though? To me it seems like they should be the same

**Comment by dummdidumm** [comment]
`+page.svelte` and `+layout.svelte` are special components to SvelteKit, and they adhere to a contract which says "all data is passed into the data prop". You other components can define the props interface however they want. Closing since this works as expected.

**Comment by Oren-Lindsey** [comment]
This should at least be clarified in the docs. It's incredibly confusing to have 2 different ways of doing it
