### ISSUE TITLE
Navigate to url before GETting shadow endpoint 

### ISSUE THREAD

**Issue by Maxson52** [sveltejs/kit#6348]
### Describe the problem

When navigating to another page one the client-side navigation has taken over, any shadow endpoints will be loaded before updating the URL in the browser. This makes for a less than amazing UX as it can seem like link clicks didn't register or the site is broken, especially when a shadow endpoint takes a while to load.

### Describe the proposed solution

A solution could be to update the URL in the browser before executing the GET of the shadow endpoint. One (possible) downside would be the page title from `<svelte:head>` wouldn't update until the shadow endpoint finishes which could cause some confusion.

### Alternatives considered

Just use the navigation store to show the end user that there is content being loaded.

### Importance

nice to have

**Comment by kristjanmar** [comment]
Are you using sveltekit:prefetch on your links? That makes the endpoints run as soon as the user hovers over the link.

I use prefetching and then the nprogress library to show a visual indicator of page loading, so a blue progress bar shows at the top of the screen as soon as the person starts navigating.

**Comment by Maxson52** [comment]
Using prefetch definitely helps in many situations. But there are still times when data takes longer to load (or there's less time to prefetch for one reason or another) and it would make the experience better to have the URL change and then show the loading indicators.

**Comment by Conduitry** [comment]
This current behavior is intentional. See the discussion in #4070 where this was changed.
