### ISSUE TITLE
+layout.server.ts load doesn't run after invalidate()

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#6349]
### Describe the bug

The `invalidate()` function no longer triggers a reload of the root layout (which has changed data). It works on v443, but stopped working on v444+

### Reproduction

https://github.com/CaptainCodeman/sveltekit-example/tree/ssr

The `invalidate()` call happens after client-side auth state changes and `/session` is called to set or clear server-side cookie. `LayoutData` should reflect the `user` from that cookie.

Needs firebase emulator running to execute locally. I can make a simpler cutdown repro if needed, was just working on this example which made me notice it:

No data reloads with v444:

https://user-images.githubusercontent.com/304910/187050362-e0a2204c-d334-43dd-8f83-f4e6f4286728.mov

Same code with v443 showing layout data updates:

https://user-images.githubusercontent.com/304910/187050370-5d9d9692-2a9e-4e77-8089-4e9d33092d91.mov

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.97 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.111
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5265.0
    Firefox: 103.0.2
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.87 
    @sveltejs/kit: 1.0.0-next.444 => 1.0.0-next.444 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by bjon** [comment]
There is another broken thing with v444. `data` in `+layout.ts` is now sometimes null, even though `+layout.server.ts` returns an object.

**Comment by CaptainCodeman** [comment]
Do you mean something that's part of the data prop when it's inside the svelte component, or in the http response from the `/__data.json` request?

**Comment by bjon** [comment]
I mean the `load({data})` in `layout.ts`, that should hold the data from `layout.server.ts`.

**Comment by luhagel** [comment]
> I mean the `load({data})` in `layout.ts`, that should hold the data from `layout.server.ts`.

This still seems to be an issue, even if there is no need to rerun the server load, I'd still expect the data object to stay the same instead of becoming `null` after navigating

// +layout.server.ts
```ts
export const load: LayoutServerLoad = async ({ locals, url }) => {
	if (!locals.token) {
		throw redirect(302, `/login?${new URLSearchParams({ callBackUrl: url?.pathname ?? '/' }).toString()}`)
	}

	const jwt = decode<JWTPayload>(locals.token)
	const session = {
		user: {
			id: jwt['sub'],
			email: jwt['email']
		},
		permissions: jwt['pem'],
		org: {
			name: jwt['org_name']
		},
		locale: locals.locale
	}
	return {
		token: locals.token,
		settings: locals.appSettings,
		session: session
	}
}
```

//+layout.ts
```ts
export const load: LayoutLoad = async ({ data, url }) => {
	await loadTranslations(getDefaultLocale(), url.pathname) // keep this just before the `return`
	return {
		token: data.token,
		settings: data.settings,
		session: data.session
	}
}
```
Will error out after page change
<img width="1694" alt="Screenshot 2022-08-30 at 07 20 56" src="https://user-images.githubusercontent.com/7240688/187355831-a9775d0c-94e5-4a1b-88a1-a4ed1ce9aac6.png">

**Comment by arackaf** [comment]
@dummdidumm @Rich-Harris fyi I'm seeing this again. After a successful login (with @auth/sveltekit), a call to invalidate("root-data") does not reload a root +layout.server.ts loader.

Oddly, after manually refreshing the page, it works as expected.
