### ISSUE TITLE
Server functions called from the browser

### ISSUE THREAD

**Issue by malgor** [sveltejs/kit#6351]
### Describe the problem

Client code and server code (or endpoints) are like two separate programs with the fetch interface between them.  Like all interfaces they take a lot of time to design and code and they are a big source of bugs.  Client code that pre-renders on the server doesn't change this.  

There is a lot of repetitive (boilerplate) code to be written for every fetch call and endpoint.  On the client side there is the fetch promise, then extracting the JSON and finally returning the resulting object.  On the server side, there is a request event to decode and a response with status and statusText to generate.  On both sides there is the extra headache of how to convey and understand that a request has failed in some way, providing an error message in some out-of-band manner.

### Describe the proposed solution

I am proposing that it be possible to write client code that calls functions available on the server with exactly the same syntax as calling a function exported by a module.  The called server function can accept arbitrary parameters and return an arbitrary result just like a normal function.  The server function can throw an exception and it can be caught by the client code just like a normal function.  And the server function can be called reactively in the way normal functions are.

SvelteKit would need to become a compiler in the same manner that Svelte is (if it isn't already).  SvelteKit would compile your server function call into all of the fetch code and exception handling to make it look like you are passing parameters back and forth to an ordinary function.  SvelteKit would generate the exception logic so that throwing one in the server function causes one to be thrown on the client.  SvelteKit would need to know which functions are server functions and for that I propose putting them in modules under `src/server`.  That is, replace this

```javascript
// Client side code
import { session } from '$lib/stores';

const response = await POST('auth/login', {
	username: username.value,
	password: password.value
});

if (response.error) {
	error = response.error;
} else {
	// Set the session with the response from the login endpoint.
	session.set(response);
	await goto('/');
}

// Server side code
export async function POST ({ request }) {
	// Authenticate the user's credentials
	try {
		await authenticate(request.params.username, request.params.password);
	} catch (e) {
		// Authentication failed, tell the user.
		return json(401, { error: e.message });
	}

	// Return data to the client
	const data = await getSessionData(username);
	return json(200, { data });
};
```

with this

```javascript
// Client side code
import { login } from '$server/authnz';
import { session } from '$lib/stores';
try {
	const response = await login(username.value, password.value);
	session.set(response);
	await goto('/');
} catch(e) {
	error = e.message;
}

// Server side code, /src/server/authnz.js
export async function login (username, password) {
	// Authenticate the user's credentials
	await authenticate(username, password);

	// Return data to the client
	return await getSessionData(username);
};
```

I believe that most people would not care how the server function interface was actually implemented by SvelteKit.  That includes which request methods, how the data is structured, how exceptions are conveyed and the routes used.  Because it would now be just be an internal interface that the developers do not have to maintain.  However, there might be a use case where a developer wants to expose a REST API to users.  I think this would be an edge case, infrequently needed, for which I have three options.

1. Don't provide the ability to have a defined REST API.  Developers would have to create it in some way outside of SvelteKit using, for example, Express.
2. Developers could duplicate the functionality of the server functions using the GET, POST, PUT, PATCH and DELETE functions in `src/routes/*/+server.js` files.  
3. Define a syntax that extends JavaScript so that a developer can define the details of the internal interface. 

You might object to all three of those options but remember they are on the assumption that they won't be used very much.  

### Alternatives considered

The alternative to this is the extant `+server.js` (endpoint) design.

### Importance

would make my life easier

### Additional Information

This idea could go further by seamlessly making module variables accessible on both server and client.  I haven't described how this might work because it would obfuscate the feature request.  But it would open up possibilities like reactive assignments and reactive statements on the server.

With all of this in place the concept of server and client would become abstracted away.  To developers it would feel like they are writing a simple native program with no division between server and client at all.

**Comment by david-plugge** [comment]
So basically like grcp? I like the idea and I think that actions are somewhat related to this as it's pretty much the same thing but the functions are called by a form submission.

**Comment by Rich-Harris** [comment]
This isn't going to happen. It would discourage progressive enhancement, create multiple ways to do things (HTTP handlers aren't going anywhere) and cause developers to be confused about what was actually happening under the hood (which I assure you many developers very much care about!).

[A Critique of the Remote Procedure Call Paradigm](https://medium.com/@ilegacy/a-critique-of-the-remote-procedure-call-paradigm-41a9dd5d3ed9) is 34 years old, but still contains a lot of relevant truth. Some arguments can't be serialized correctly. If your server function mutates arguments, that mutation won't be respected on the client. Network errors become indistinguishable from logic errors. All these things are easy to deal with _if you're not hiding the implementation details_ with compiler magic that makes server functions look like local functions.
