### ISSUE TITLE
"Cannot find base config file ./.svelte-kit/tsconfig.json" after running `bun install`

### ISSUE THREAD

**Issue by vinliao** [sveltejs/kit#6359]
### Describe the bug

The warning "Cannot find base config file ./.svelte-kit/tsconfig.json" only appears when `bun install` is used instead of `yarn` or `npm install`. Not a big problem, though, because `yarn dev` still runs, and after the initial warning message, a `tsconfig.json` seems to be added automatically by SvelteKit.

### Reproduction

1. `npm create svelte@latest my-app`
2. `cd my-app`
3. `bun install`
4. `yarn dev` (or `npm run dev`)

![Screenshot from 2022-08-29 09-20-05](https://user-images.githubusercontent.com/34117807/187110265-3df70a9b-ed65-421a-b28b-172192947991.png)

(Can't use StackBlitz because it bun isn't installed.)

### System Info

```shell
System:
    OS: Linux 5.17 Fedora 34 (Workstation Edition) 34 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 1.23 GB / 7.63 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.67 
    @sveltejs/kit: next => 1.0.0-next.445 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.9
```

### Severity

annoyance

**Comment by benmccann** [comment]
It looks like it currently only runs postinstall on your own project, but not your project's dependencies, so that seems like the issue: https://twitter.com/jarredsumner/status/1555008750120865792. This is an issue in bun and not in SvelteKit, so I'm going to go ahead and close this
