### ISSUE TITLE
adapter-node custom server code example does not work with Polka

### ISSUE THREAD

**Issue by miohtama** [sveltejs/kit#6363]
### Describe the bug

`polka` is the default web server implementation for adapter-node. 

However, the default example for custom server script on adapter-node README does not work with Polka. It works with Express only.

If using Polka,m SvelteKit handler takes completely over and the health check endpoint is not available (gives 404). 

I do not know why is this as I am not an expert on the Polka server, but I would like to use it if possible.

### Reproduction

Here is an example script on how to reproduce when running with any SvelteKit application.

You can run the same script with Polka and Express

- With Express everything works
- With Polka `/healthcheck` gives 404

```javascript
// my-server.js
import { handler } from '../build/handler.js';
import express from 'express';
import polka from 'polka';

// Works
//const app = express();

// Does not work
const app = polka();

// add a route that lives separately from the SvelteKit app
app.get('/healthcheck', (req, res) => {
  res.end('ok');
});

// let SvelteKit handle everything else, including serving prerendered pages and static assets
app.use(handler);

app.listen(3000, () => {
  console.log('listening on port 3000');
});

```

### System Info

```shell
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 24.04 GB / 64.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Chrome: 104.0.5112.101
    Firefox: 104.0
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.73 => 1.0.0-next.73 
    @sveltejs/adapter-static: ^1.0.0-next.13 => 1.0.0-next.18 
    @sveltejs/kit: 1.0.0-next.308 => 1.0.0-next.308 
    svelte: ^3.49.0 => 3.49.0 

```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is a Polka issue, not a SvelteKit one — I honestly don't know how to make Polka respect the `app.get` in this situation. cc'ing @lukeed for visibility, but I'll close this issue as there's nothing for SvelteKit to do here
