### ISSUE TITLE
Standard process to handle reload of web client after backend deployment

### ISSUE THREAD

**Issue by bluepuma77** [sveltejs/kit#6365]
### Describe the problem

We have clients that use our SvelteKit app 24/7 on a single PC, so we need to a solution to trigger a client reload after we have deployed a new app version to our backend. 

Complication is that we can't just trigger a reload on a (git) version mismatch as our staged deployments take about 90 seconds and clients will be bounced by load balancers back and forth between new an old versions. They should only reload once.

Would like to see a best practice solution for SvelteKit.

### Describe the proposed solution

Is it possible to access the JS filename tag that is generated during the building of a SvelteKit app? 
Is that somehow ordered so a compare (">") on client side is possible?

### Importance

would make my life easier

### Additional Information

The WhatsApp web client shows a small windows stating "Software was updated, click here to reload".

**Comment by Rich-Harris** [comment]
You should be able to use the [`updated` store](https://kit.svelte.dev/docs/modules#$app-stores-updated) alongside [`version.pollInterval`](https://kit.svelte.dev/docs/configuration#version) for this

**Comment by benmccann** [comment]
Closing this since the ability to do it already exists to large degree. Further improvements are tracked in https://github.com/sveltejs/kit/issues/3666

**Comment by kristjanmar** [comment]
A question regarding the version.pollInterval option.

From the [docs](https://kit.svelte.dev/docs/configuration#version): 

> SvelteKit solves this problem by falling back to traditional full-page navigation if it detects that a new version has been deployed, using the name specified here (which defaults to a timestamp of the build).

Does this mean that if I set the version.name and version.pollInterval, that SvelteKit will automatically disable the client side router and trigger a full reload on the next link click?

Is it not necessary for me to add my own subscription to the updated store to trigger a refresh?

**Comment by kevinrenskers** [comment]
If I read that correctly, then you don't even have to set a `pollInterval`; that is only to populate the `updated` store. All the logic about "falling back to traditional full-page navigation if it detects that a new version has been deployed" is purely based on the `name` parameter, which has a sensible default value.

And yet, the most common error in Sentry for my SvelteKit app is "Failed to fetch dynamically imported module".

**Comment by kristjanmar** [comment]
If that's the case then it's definitely not working at the moment. I am also getting a lot of these and other errors that indicate that people are trying to navigate with an old version of the app.
