### ISSUE TITLE
Can't have VsCode breakpoints to work in SSR endpoints

### ISSUE THREAD

**Issue by IvankoB** [sveltejs/kit#6369]
### Describe the bug

Me failed to get stepped debugging SSR code of the default (vite-based, created in the way recommended on the SvelteKit site) project in VsCode. Many settings in 'vite.config.js' & 'launch.js' were tried.

### Reproduction

Any project with SSR endpoints

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 1.27 GB / 11.90 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.17.0 - D:\MyProjects\JS\SVELTEKIT\pokemon-tutorial\node_modules\.bin\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.70)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64
    @sveltejs/kit: next => 1.0.0-next.445
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.9
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
I don't think this is something we can "fix", this sounds more like a usage question, therefore turning this into a discussion.
