### ISSUE TITLE
adapter-static does not behave properly when served from IPFS

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#638]
**Describe the bug**
The bug is best exemplified with this sample app : https://github.com/wighawag/svelte-kit-ipfs-example

It is the basic sveltekit app modified to use static-adapter and it comes bundled with a static server that behave like ipfs gateways
In such case, the base path cannot be known at build time as the base path is composed of the ipfs hash of the content

if you load the page with an url like http://localhost:8080/ipfs/ffff/ the css is not taken in consideration

**To Reproduce**
See repo : https://github.com/wighawag/svelte-kit-ipfs-example

**Expected behavior**
Svelte Kit adapter-static should work well on host where the basepath cannot be predicted. The resulting build should remain independent of the path where it is served

**Severity**
As I build website solely on ipfs, this is a blocking feature.

Example of svelte based website (which use snowpack) that works on IPFS with root base path and hashed base path 
root: https://bafybeiailrpnrx5qaeegtpeysazfsvutwatwcsvkyx54u3fxvedv34mhru.ipfs.cf-ipfs.com/
path with hash: https://dweb.link/ipfs/bafybeiailrpnrx5qaeegtpeysazfsvutwatwcsvkyx54u3fxvedv34mhru or https://ipfs.io/ipfs/bafybeiailrpnrx5qaeegtpeysazfsvutwatwcsvkyx54u3fxvedv34mhru/
It also available on ENS via :  https://mandalas.eth.link/

**Comment by antony** [comment]
There's an open issue for making the base path dynamic, https://github.com/sveltejs/kit/issues/595 which would probably resolve this.

**Comment by Rich-Harris** [comment]
closing this as it's covered by #595
