### ISSUE TITLE
More "dynamic" option for trailingSlash

### ISSUE THREAD

**Issue by garyrutland** [sveltejs/kit#6429]
### Describe the problem

Currently the only options for `trailingSlash` are `never`, `always` or `ignore` which on the most part is fine but there is at least one other use case that doesn't quite fall into these three.

The use case I'm currently having is when the path has an extension on the end, for example: `http://localhost/my/catchall/route/file1.md`

This catch all is pulling in markdown files in from where ever they need to, parsing them and then rendering.
Some of these contain relative links like `./file2.md` which shouldn't be a problem.

However, I run into these two situations:

`always` - `http://localhost/my/catchall/route/file1.md/` = `/my/catchall/route/file1.md/file2.md`
`never` - `http://localhost/my/catchall/route` = `/my/catchall/file2.md`

If I'm on `http://localhost/my/catchall/route/file1.md` and there is a link for `./file2.md` it should result in `http://localhost/my/catchall/route/file2.md`

I've currently had to compensate for this by setting it to `ignore` and adding something into a layout like so:
```node
// ./src/routes/+layout.js

import {redirect} from '@sveltejs/kit'

/** @type {import('./$types').LayoutLoad} */
export function load({url}) {
    if (url.pathname.indexOf('.') === -1 && url.pathname.slice(-1) !== '/') {
        throw redirect(301, url.pathname + '/' + url.search)
    }
}
```
I did try and use `handle` but it wouldn't quite do what I wanted it to do.

### Describe the proposed solution

It would be nice if the `trailingSlash` config had an additional option to handle paths that have extensions at the end, possibly using the logic I put into my solution above but in a better location?

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
This can be closed now that `trailingSlash` is a [page option](https://kit.svelte.dev/docs/page-options#trailingslash)
