### ISSUE TITLE
Can't update npm packages after recent changes (vite dependency)

### ISSUE THREAD

**Issue by stausmar** [sveltejs/kit#6437]
### Describe the bug

I get error messages while trying to update my npm packages. The command `npm outdated` shows the following packages to be updated.

```
Package                        Current          Wanted          Latest  Location
@sveltejs/adapter-auto   1.0.0-next.65   1.0.0-next.69   1.0.0-next.69  node_modules/@sveltejs/adapter-auto
@sveltejs/kit           1.0.0-next.431  1.0.0-next.454  1.0.0-next.454  node_modules/@sveltejs/kit
@types/node                    18.7.11         18.7.14         18.7.14  node_modules/@types/node
sass                            1.54.5          1.54.6          1.54.6  node_modules/sass
svelte-check                     2.8.1           2.9.0           2.9.0  node_modules/svelte-check
typescript                       4.7.4           4.8.2           4.8.2  node_modules/typescript
vite                      3.1.0-beta.1           3.0.9           3.0.9  node_modules/vite
```

When running `npm update` I get the following error messages.

```npm ERR! While resolving: marcs-depot-svelte@0.0.1
npm ERR! Found: vite@3.0.9
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.1.0-beta.1" from @sveltejs/kit@1.0.0-next.454
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"next" from the root project
```

How can I update to the latest version of SvelteKit? Unfortunately, the solution suggest in https://github.com/sveltejs/kit/issues/6427 does not work for me and brings up other dependency issues.

Thanks a lot!

### Reproduction

There's no minimal reproduction available.

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 2.10 GB / 7.65 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.17.0 - /usr/bin/npm
  Browsers:
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65 
    @sveltejs/kit: next => 1.0.0-next.431 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

This blocks me from updating to the latest SvelteKit version.

**Comment by benmccann** [comment]
If you want to update to the latest SvelteKit, specify the version `^1.0.0-next.454` in your `package.json`

**Comment by stausmar** [comment]
I changed the version in my `package.json` to `^1.0.0-next.454`.

```
"devDependencies": {
	"@sveltejs/adapter-auto": "next",
	"@sveltejs/kit": "^1.0.0-next.454",
	"svelte": "^3.44.0",
	"svelte-check": "^2.7.1",
	"svelte-preprocess": "^4.10.6",
	"tslib": "^2.3.1",
	"typescript": "^4.7.4",
	"vite": "^3.1.0-beta.1"
},
```
Afterwards, running `npm install` unfortunately still does not work. This brings up:

```
npm ERR! Found: @sveltejs/kit@1.0.0-next.431
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^1.0.0-next.454" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @sveltejs/kit@"^1.0.0-next.454" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vite@3.1.0-beta.1
npm ERR! node_modules/vite
npm ERR!   peer vite@"^3.1.0-beta.1" from @sveltejs/kit@1.0.0-next.454
npm ERR!   node_modules/@sveltejs/kit
npm ERR!     dev @sveltejs/kit@"^1.0.0-next.454" from the root project
```

**Comment by benmccann** [comment]
Do you have https://docs.npmjs.com/cli/v8/using-npm/config#strict-peer-deps enabled globally?

Is the installation _actually_ failing, or are those just warnings?

We really need reproductions for issues

**Comment by ryans-usafacts** [comment]
If I do a clean re-install of my sveltekit application (delete the `.svelte-kit` folder, `node_modules`, `package.json`) I get the same error.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend-explorations@0.0.1
npm ERR! Found: vite@3.0.9
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^3.1.0-beta.1" from @sveltejs/kit@1.0.0-next.454
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^1.0.0-next.454" from the root project
```

with these dependencies:
```
	"devDependencies": {
		"@sveltejs/adapter-node": "next",
		"@sveltejs/kit": "next",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"fs-extra": "^10.1.0",
		"node-fetch": "^3.2.10",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-check": "^2.7.1",
		"typescript": "^4.7.4",
		"vite": "^3.0.0",
		"vite-plugin-plain-text": "^1.2.1",
		"vite-plugin-svgstring": "^1.0.0"
	},
```

I didn't install anything new, and I don't have anything other than whatever is the default for `strict-peer-deps` enabled.

**Comment by benmccann** [comment]
@ryans-usafacts You need to change `"vite": "^3.0.0",` to `"vite": "^3.1.0-beta.1",`

**Comment by ryans-usafacts** [comment]
Thanks @benmccann. It still throws the error message, but overrides and installs.

**Comment by stausmar** [comment]
@benmccann - Chaning `"vite": "^3.0.2"` to `"vite": "^3.1.0-beta.1"` and `"@sveltejs/kit": "next"` to `"@sveltejs/kit": "^1.0.0-next.454"` does not work either. `npm install` shows:

```
npm ERR! Found: @sveltejs/kit@1.0.0-next.431
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^1.0.0-next.454" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @sveltejs/kit@"^1.0.0-next.454" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: vite@3.1.0-beta.1
npm ERR! node_modules/vite
npm ERR!   peer vite@"^3.1.0-beta.1" from @sveltejs/kit@1.0.0-next.454
npm ERR!   node_modules/@sveltejs/kit
npm ERR!     dev @sveltejs/kit@"^1.0.0-next.454" from the root project
```
Any other idea?

**Comment by benmccann** [comment]
@stausmar it's very hard for me to debug your project with just this information. I really would need a reproduction

**Comment by benmccann** [comment]
Btw, Vite 3.1.0 final will be out on Friday and this should resolve itself then

**Comment by asmajlovicmars** [comment]
@benmccann - after installing the vite@3.1.0-beta.1 and SK 1.0.0-next.454, npm run preview works fine, but the node build/index.js fails with following errors:

`➜  app git:(adnan) ✗ node build/index.js
file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-BHN6OJC3.js:12
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "http" is not supported
    at file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-BHN6OJC3.js:12:9
    at Object.http (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:7033:27)
    at __webpack_require__ (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:21:27)
    at Object.../node_modules/axios/lib/adapters/http.js (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:242:20)
    at __webpack_require__ (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:21:27)
    at getDefaultAdapter (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:1263:23)
    at Object.../node_modules/axios/lib/defaults/index.js (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:1282:20)
    at __webpack_require__ (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:21:27)
    at Object.../node_modules/axios/lib/core/transformData.js (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:1231:24)
    at __webpack_require__ (file:///Users/asmajlovic/code/dexp-fe-ssr/app/build/server/chunk-2EV6LM4I.js:21:27)`

**Comment by benmccann** [comment]
@asmajlovicmars your issue looks more like https://github.com/sveltejs/kit/issues/6440

**Comment by asmajlovicmars** [comment]
Thank you @benmccann.
