### ISSUE TITLE
Types - JSON Endpoint function, only allow valid JSON types

### ISSUE THREAD

**Issue by JeremyMoeglich** [sveltejs/kit#6438]
### Describe the problem

Currently, the JSON endpoint function takes `any` as a type
![image](https://user-images.githubusercontent.com/60170474/187494878-595af41f-fa97-486d-8644-92b0dfddc289.png)

The `any` type includes types such as Date, Map and functions which can't be represented in JSON.

For example, let's say you had this
```js
return json({
    test: new Date()
})
```
after serialization, this would for example be
```json
{
    "test": "2022-08-30T16:55:12.151Z"
}
```

Meaning the JSON type and the JavaScript type don't match

### Describe the proposed solution

The json function could use JsonValue as a type for data.
This would lead to an error for types such as dates and force the developer to manually convert the type if desired

### Alternatives considered

1. Continue using `any`.
This would make it easier to use dates and so on as these are automatically serialized
2. Automatically convert JSON back to original types when using fetch or some alternative. I like this idea, but there should be an alternate function for this

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
I'm not sure I like preventing users passing arbitrary data -- sometimes I'm totally OK with my dates being serialized just how they are, and I want the `toJSON` functions on my classes to be able to handle their serialization for me. I think a better solution would be just to change the function to accept the standard `JSON.stringify` `replacer` argument. Users who need that kind of custom serialization can then just:

```ts
const resp = await fetch('foo.com');
const text = await resp.text();
const json = await JSON.parse(text, reviver);
```

This seems more in-line with the standard JavaScript API.

**Comment by Rich-Harris** [comment]
If you need that level of control over the serialization, I think it's reasonable to do this...

```js
return new Response(JSON.stringify(data, replacer), {
  headers: {
    'content-type': 'application/json'
  }
});
```

...rather than adding a third argument to the `json` helper.

**Comment by Rich-Harris** [comment]
We used to have a `JSONValue` type that was useful for this sort of thing, but it couldn't tolerate interfaces, only types. It caused more trouble than it was worth so we removed it.

**Comment by Rich-Harris** [comment]
going to close this as i don't think there's anything it makes sense for the framework to do differently
