### ISSUE TITLE
Issue with `history.back()` not working as intended

### ISSUE THREAD

**Issue by rogadev** [sveltejs/kit#6439]
### Describe the bug

On my landing page, users make 2 selections before they are taken to a new route, `/outlook/1234`. Before updating and migrating, I used a floating back button which used `history.back()` to navigate back to the root route. After updating/migrating, I get a 500 error when I attempt to navigate back using `history.back()` or even when using an anchor tag that takes me to `/` from the outlook page.

### Reproduction

https://github.com/rogadev/viu-eo

On the `main` branch you'll find the previous, working functionality. From `/`, choose a program. Choose a career. Hit the back button to reproduce.
Alternatively, you can find this version running [here](https://viu-career-outlook.vercel.app/)

On the `mono` branch you'll find essentially the same app, but updated/migrated. Do the same steps. From `/`, choose a program. Choose a career. Hit the back button to reproduce.

### Logs

Terminal logs are empty.

Dev tools:

```shell
+page.svelte? [sm]:20 <Page> was created with unknown prop 'errors'
(anonymous) @ +page.svelte? [sm]:20
:5174/__data.js?__invalid=ny&__id=2:1          Failed to load resource: the server responded with a status of 404 (Not Found)
error.svelte? [sm]:14 <Error> was created with unknown prop 'data'
(anonymous) @ error.svelte? [sm]:14
error.svelte? [sm]:14 <Error> was created with unknown prop 'errors'
(anonymous) @ error.svelte? [sm]:14
DevTools failed to load source map: Could not load content for chrome-extension://lggdbpblkekjjbobadliahffoaobaknh/static/js/content.js.map: System error: net::ERR_FILE_NOT_FOUND
```

On-Screen Message
```
500
Failed to fetch dynamically imported module: http://localhost:5174/__data.js?__invalid=ny&__id=2
TypeError: Failed to fetch dynamically imported module: http://localhost:5174/__data.js?__invalid=ny&__id=2
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 68.16 GB / 79.94 GB
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70)        
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.69
    @sveltejs/kit: next => 1.0.0-next.447
    svelte: ^3.44.0 => 3.49.0
    vite: ^3.0.0 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by CaptainCodeman** [comment]
Check for `@migration` tasks that throw errors.

**Comment by rogadev** [comment]
I solved it.

It was a migration error, but not an `@migration` task. Migration created an empty `+page.server.js` file. Once removed, I get the proper functionality as before. I overlooked this file forever, thinking that the migration wouldn't have created it if it didn't need it. Turns out, it definitely did not need it and it was causing problems.

**Comment by dummdidumm** [comment]
Mhm interesting - do you know why it could have created it? Did you have an empty `<script context="module"></script>` tag in that old page file by any chance?

**Comment by rogadev** [comment]
No context=module. I had a `programs.js` helper file that I think was the root of the problem. I emptied this file into the +page.svelte after migration but I didn't give the empty +page.server.js a second thought. It might not have known what to do with the programs.js file, left it, and created the +pagee.server.js for me to put things into as a to-do. 🤷‍♂️ I'm just happy to have it solved. I'll know what to look for next time.
