### ISSUE TITLE
Remove `sveltekit:start` event

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#6448]
### Describe the problem

The only real reason we have [this](https://kit.svelte.dev/docs/events) is so that we can do some setup work in our test suite. It's a bit of a weird appendage — you can't really use it to do useful setup work, and it would probably be better to just use root layouts, even if it would add a tiny bit of repeated code to our tests.

### Describe the proposed solution

Remove the event

### Alternatives considered

Leave the event

### Importance

nice to have

**Comment by dummdidumm** [comment]
It may be that others rely on this to know "ok SvelteKit is setup", maybe KitQL (cc @jycouet), in general all people who came across #4447

**Comment by Conduitry** [comment]
I actually didn't know about this event. What I ended up doing in an app (something going back to when it was using Sapper) in e2e tests when I wanted to make sure the app was running and hydrated before proceeding was to have `onMount(() => document.body.setAttribute('hydrated', ''))` in my root layout and then just wait for that attribute to be present in the tests. That's working fine enough for me, and it's presumably less susceptible to race conditions if you happen to be too later in attaching your event listener.
