### ISSUE TITLE
Route params is empty if page not found (404)

### ISSUE THREAD

**Issue by bjon** [sveltejs/kit#6453]
### Describe the bug

We have a setup like this: `/[lang]/path1`, `/[lang]/path2`, etc...

In `layout.ts` we get the `lang` from `params`, so we can fetch other stuff.
But when a page is not found, `params` is now an empty object.
This broke in v432 ([#6174](https://github.com/sveltejs/kit/pull/6174))

### Reproduction

* `npm create svelte@latest repro-6453`
* create route `src/routes/[test]`
* move `+page` into `src/routes/[test]`
* add `+layout.ts` to `src/routes`
```js
/** @type {import('./$types').LayoutLoad} */
export function load({ params }) {
  console.info("params", params);
}
```
* `npm run dev`
* test http://localhost:5173/repro (console should print params)
* test http://localhost:5173/repro/not-found (now params is empty)

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 12.22 GB / 15.59 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/bin/node
    npm: 8.15.0 - /usr/bin/npm
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
This is expected behaviour — if no route matched, there's no route to extract params from. You'll need to use a rest route as described here: https://kit.svelte.dev/docs/advanced-routing#rest-parameters

```js
// src/routes/[test]/[...catchall]/+page.js
import { error } from '@sveltejs/kit';

export function load() {
  throw error(404);
}
```
