### ISSUE TITLE
Data from +layout.server.ts is null after navigating

### ISSUE THREAD

**Issue by luhagel** [sveltejs/kit#6459]
> I mean the `load({data})` in `layout.ts`, that should hold the data from `layout.server.ts`.

This still seems to be an issue, even if there is no need to rerun the server load, I'd still expect the data object to stay the same instead of becoming `null` after navigating

// +layout.server.ts
```ts
export const load: LayoutServerLoad = async ({ locals, url }) => {
	if (!locals.token) {
		throw redirect(302, `/login?${new URLSearchParams({ callBackUrl: url?.pathname ?? '/' }).toString()}`)
	}

	const jwt = decode<JWTPayload>(locals.token)
	const session = {
		user: {
			id: jwt['sub'],
			email: jwt['email']
		},
	}
	return {
		token: locals.token,
		settings: locals.appSettings,
		session: session
	}
}
```

//+layout.ts
```ts
export const load: LayoutLoad = async ({ data, url }) => {
	await loadTranslations(getDefaultLocale(), url.pathname) // keep this just before the `return`
	return {
		token: data.token,
		settings: data.settings,
		session: data.session
	}
}
```
Will error out after page change
<img width="1694" alt="Screenshot 2022-08-30 at 07 20 56" src="https://user-images.githubusercontent.com/7240688/187355831-a9775d0c-94e5-4a1b-88a1-a4ed1ce9aac6.png">

EDIT: Running on next.454

_Originally posted by @luhagel in https://github.com/sveltejs/kit/issues/6349#issuecomment-1231155148_

**Comment by alialaa** [comment]
I also opened a similar issue in #6336 and it was supposedly fixed but I am still having the same problem.

**Comment by laxadev** [comment]
I have the same issue too. From time to time when I navigate on the site it returns `null` but if I hard refresh the site all is good.

**Comment by AlexRMU** [comment]
The same with using depends and invalidate

**Comment by mquandalle** [comment]
Minimal reproduction of the issue: https://stackblitz.com/edit/sveltejs-kit-template-default-qvjxq7?file=src/routes/+page.svelte

**Comment by AlexRMU** [comment]
About `invalidate` and `invalidateAll`:
https://stackblitz.com/edit/sveltejs-kit-template-default-9yng4c?file=src/routes/+page.svelte

**Comment by mquandalle** [comment]
I opened up a discussion on a API change that is related to this issue: #6570

**Comment by ni-max** [comment]
> Minimal reproduction of the issue: https://stackblitz.com/edit/sveltejs-kit-template-default-qvjxq7?file=src/routes/+page.svelte

I encountered this bug today,
accessing `url.pathname` seems to be a workaround as of `1.0.0-next.480`

```diff
--- page.server.js	2022-09-12
+++ page.server.js	2022-09-12
@@ -1,4 +1,5 @@
-export function load() {
+export function load({url}) {
+	url.pathname;
 	return {
 		textFromTheServer: `This text comes from the server \`load\` function.
       It should remain on screen when we stay on page (even if the client \`load\` is rerun when clicking ABC and DEF links below).`
```
