### ISSUE TITLE
Layout Load Function, Data Inheritance, Order

### ISSUE THREAD

**Issue by lemmon** [sveltejs/kit#6460]
### Describe the bug

I am not sure if this is a bug or I am missing something. I have rather comlicated routes structure:

```
src/routes/+layout.js
src/routes/+layout.svelte
src/routes/(app)/+layout.js
src/routes/(app)/+layout.svelte
src/routes/(app)/[site]/+layout.js
src/routes/(app)/[site]/+layout.svelte
src/routes/(app)/[site]/+page.js
src/routes/(app)/[site]/+page.svelte
src/routes/(app)/[site]/looking-glass/+layout.js
src/routes/(app)/[site]/looking-glass/+layout.svelte
src/routes/(app)/[site]/looking-glass/+page.js
src/routes/(app)/[site]/looking-glass/+page.svelte
```

When navigating to `/siteid/looking-glass` my understanding is that the `load()` functions would be triggered in order such as:

```
src/routes/+layout.js
src/routes/(app)/+layout.js
src/routes/(app)/[site]/+layout.js
src/routes/(app)/[site]/looking-glass/+layout.js
src/routes/(app)/[site]/looking-glass/+page.js
```

It seems that on server side this order is honored. However when running in client it is not the case.

<img width="211" alt="Screenshot 2022-08-31 at 10 21 27" src="https://user-images.githubusercontent.com/251591/187635395-35ddaf8e-31c7-4c1e-803d-cec128b2eb67.png">
<img width="264" alt="Screenshot 2022-08-31 at 10 21 05" src="https://user-images.githubusercontent.com/251591/187635405-90220e2f-5876-4ead-9bed-c4ffd8dc138a.png">
<img width="228" alt="Screenshot 2022-08-31 at 10 19 38" src="https://user-images.githubusercontent.com/251591/187635412-1878f49f-3da3-46a6-9db8-eef1ec234087.png">

As you can see the order gets messed up every refresh.

Another thing is sharing data between those functions. In previous versions with the `stuff` property this worked just fine. This thime, however I am getting always `null` when acessing the `data` object.

```js
// src/routes/+layout.js

export async function load({ data }) {
  console.log('👋 ROOT +layout', data)
  return {
    user: 'User'
  }
}
```

My guess was that I cas access the `data.user` property in subsequent layout `load` functions in same fashion as `stuff` worked before.

I am wrong here or this is in fact a bug?

### Reproduction

https://github.com/lemmon/sveltekit-layout-data-load

### System Info

```shell
System:
    OS: macOS 11.6.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 55.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 100.1.37.109
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.70 
    @sveltejs/kit: next => 1.0.0-next.456 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.1.0-beta.1 => 3.1.0-beta.1
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
This is the intended behavior. Multiple `load` functions are by default run in parallel rather than in series in order to make things faster. The `data` argument in `+layout.js`/`+page.js` is not the parent `load`'s return value - it is the return value for the corresponding `+layout.server.js`/`+page.server.js` (of which you apparently have none). https://kit.svelte.dev/docs/load#input-methods-parent retrieves that parent `load`'s data, and forces those two to run in series.

**Comment by lemmon** [comment]
@Conduitry Okay I get it. When I use `*.server.js` the inheritance works as expected.

However there's no way, in this case, to build a SPA. When trying to build with `adapter-static` and trying to run on a static server I get infinite redirects.

I understand that `*.server.js` are intended to run on server but with this behaviour it becomes impossible to build SPA hosted on a static server with no SSR.
