### ISSUE TITLE
silence errors coming from `data-sveltekit-prefetch`

### ISSUE THREAD

**Issue by ivanhofer** [sveltejs/kit#6463]
### Describe the problem

Now that we have [the option to prefetch all links inside a certain region of the DOM](https://kit.svelte.dev/docs/link-options#data-sveltekit-prefetch), I want to enable for all links instead of passing it to each link individually. I have added `data-sveltekit-prefetch` to the `body` tag.

But now I get a lot of errors:
```
Error: Attempted to prefetch a URL that does not belong to this app
````
some of my links will open to an external ressource.

### Describe the proposed solution

It would be great if `data-sveltekit-prefetch` would not throw errors and instead could silently fail.

Maybe a second optional param could be added to the `prefetch` function to allow to control if an error should be thrown or if the function should just returns.

This would also make it possible to have the same feature when calling `prefetch` programmatically.

### Importance

would make my life easier

**Comment by flayks** [comment]
Just my opinion but I'm not certain that putting `data-sveltekit-prefetch` on the `<body>` would be the best idea as it obviously would catch external links and then throw this error?  
Since this should only be applied to internal links/existing routes, maybe specifying it to certains blocks where you know you'll have some might be a better option, like the default example site has been updated to.

On another hand, `data-sveltekit-prefetch` could maybe check to not prefetch external links? That's another thing tho 😄

```svelte
<nav data-sveltekit-prefetch>
  <ul>
    <li><a href="/">Homepage</a></li>
    <li><a href="/route">Another route</a></li>
  </ul>
</nav>
```

**Comment by ivanhofer** [comment]
The example in the docs applies it on the `main` section, so it is set on a rather big scope.

And the second approach you mention is what I did propose in the issue 😅

**Comment by flayks** [comment]
> The example in the docs applies it on the `main` section, so it is set on a rather big scope.

True! I see the attribute on the in the nav in the default example though, so mixed examples here and there I suppose.
https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/lib/header/Header.svelte#L13

> And the second approach you mention is what I did propose in the issue 😅

I agree 👌

**Comment by Greenheart** [comment]
Next.js has a [`prefetch()`](https://github.com/vercel/next.js/blob/57fdff135dbdc5c40f4b6063d2c21dbd1faed34b/packages/next/client/link.tsx#L70-L77) function that stops external URLs by returning early after checking with [`isLocalURL()`](https://github.com/vercel/next.js/blob/57fdff135dbdc5c40f4b6063d2c21dbd1faed34b/packages/next/shared/lib/router/router.ts#L137-L151). This happens silently, without any warning.

SvelteKit already has a [similar solution](https://github.com/sveltejs/kit/blob/41d3cb617dedd3e44cf5934630bb04f45d829661/packages/kit/src/runtime/client/client.js#L944-L946) that warns about external URLs, and easily could be modified into an early return instead.

Perhaps the easiest solution to close this issue would be to just do an early return and remove the warning. The warning does make sense to make you aware - but in practice there wouldn't be any need for developers to take action, if SvelteKit would ignore external links automatically just like Next.js does.

What do you think? 🙂
