### ISSUE TITLE
[ci] cache playwright browser binaries according to their version, to avoid conflict on caching

### ISSUE THREAD

**Issue by Tal500** [sveltejs/kit#6464]
### Describe the problem

While I was working on some PR here, I had accidentally upgraded Playwright version from 1.25.0 to 1.25.1.
Turns out, there is a different browser binaries for that version, and the caching in the CI force Playwright to use the browser binaries of 1.25.0., although I used 1.25.1. This is the part of the CI workflow causing it:
https://github.com/sveltejs/kit/blob/db506894463cd846ac9e8ddc7fa542630ed5ba27/.github/workflows/ci.yml#L53-L57

This can be problematic not only to me, but also for the main project CI, when you'll decide to upgrade playwright, unless you'll decide to clean cache every time.

### Describe the proposed solution

Instead of caching to `node_modules`, use a different caching directory for the binaries, and use current playwright version (+ the runner OS details) as the caching key.

### Importance

would make my life easier

**Comment by benmccann** [comment]
That seems like a good idea. Care to send a PR for it @Tal500 ?

**Comment by Tal500** [comment]
> That seems like a good idea. Care to send a PR for it @Tal500 ?

Yes, I'll work on it, test the idea in my repos, and send a PR.

Wonder how no popular GitHub action exists with this idea, this repo did already the most of it.

**Comment by dominikg** [comment]
do you have a link to where it happens? The pnpm cache is keyed to pnpm-lock, so updating playwright would lead to it not being used?

**Comment by Tal500** [comment]
> do you have a link to where it happens? The pnpm cache is keyed to pnpm-lock, so updating playwright would lead to it not being used?

https://github.com/sveltejs/kit/runs/8110860816?check_suite_focus=true

**Comment by Rich-Harris** [comment]
Closed via #6502
