### ISSUE TITLE
Polyfill Buffer API

### ISSUE THREAD

**Issue by chientrm** [sveltejs/kit#6465]
### Describe the problem

Cloudflare Workers doesn't have `Buffer` API.

### Describe the proposed solution

Polyfill `Buffer` API with this package [buffer](https://www.npmjs.com/package/buffer)

### Importance

would make my life easier

**Comment by benmccann** [comment]
I guess that's because `Buffer` is a Node thing. Perhaps alternatively we could switch to `ArrayBuffer`? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

**Comment by benmccann** [comment]
@chientrm can you clarify which is the case? If you're hitting the error in SvelteKit code, could you provide a repository and steps to reproduce?

**Comment by chientrm** [comment]
> @chientrm can you clarify which is the case? If you're hitting the error in SvelteKit code, could you provide a repository and steps to reproduce?

Here's the example repository: [test-sveltekit-cloudflare-worker-buffer-api](https://github.com/chientrm/test-sveltekit-cloudflare-worker-buffer-api).

The project is deployed successfully to Cloudflare Pages. However, here's the result page: [Pages](https://test-sveltekit-cloudflare-worker-buffer-api.pages.dev/)

My use case is to use `Buffer.from(base64_secret, "base64")` to convert `base64` string to`Uint8Array`.

**Comment by Conduitry** [comment]
We don't want to be in the business of shipping everyone every possible polyfill for helpful APIs not available on their particular platform. And if we're not doing that, there's no compelling reason to specifically add `Buffer` to this environment. If you need this, you can bring your own `Buffer` polyfill. Or if all you really need is to be able to decode base64 strings into arraybuffers, you can get a library to do that.

Eventually we want to be able to prevent you during dev or build from being able to use APIs that we know aren't available in that environment. But that has its own issue. Our solution for this will be to make it fail earlier, not to make all APIs work in all environments.

**Comment by chientrm** [comment]
> We don't want to be in the business of shipping everyone every possible polyfill for helpful APIs not available on their particular platform. And if we're not doing that, there's no compelling reason to specifically add `Buffer` to this environment. If you need this, you can bring your own `Buffer` polyfill. Or if all you really need is to be able to decode base64 strings into arraybuffers, you can get a library to do that.
> 
> Eventually we want to be able to prevent you during dev or build from being able to use APIs that we know aren't available in that environment. But that has its own issue. Our solution for this will be to make it fail earlier, not to make all APIs work in all environments.

Yah this's what I mean. SvelteKit doesn't throw an error when building project using `Buffer` API to Cloudflare Workers 🤦 .
