### ISSUE TITLE
adapter-static documentation issue

### ISSUE THREAD

**Issue by johnknoop** [sveltejs/kit#648]
According to [this page](https://github.com/sveltejs/kit/tree/master/packages/adapter-static), the `adapter-static` adapter builds a Node server. I thought this adapter would produce files that can be used in a S3 bucket (or Azure blob storage)?. And that means we can't run any server-side processing - it all has to take place in the browser.

If this is not a typo but indeed the intention with `adapter-static`, then which adapter can we use instead?

**Comment by benmccann** [comment]
I think that documentation is wrong

**Comment by joe-azps** [comment]
To clarify, running "npm run build" will use whichever adapter is set in your svelte.config.js. Make sure you have the right adapter set.
