### ISSUE TITLE
has a popState

### ISSUE THREAD

**Issue by maxguzenski** [sveltejs/kit#6498]
### Describe the problem

I'm porting a react webapp to svelte, and I have a need to know when a page was loaded by push/replace or because the user pressed the browser's back button or if window.history.go(-1) method was called.

For this, I'm using my own code (below), but I would like to know if sveltekit could officially inform that.

### Describe the proposed solution

This is working for my use case, 
but I'm sure it doesn't work for all cases

```js
import { browser } from '$app/environment'
import { afterNavigate } from '$app/navigation'

let idx = 0

export function listenPopState() {
	afterNavigate(() => {
		idx = window.history.state['sveltekit:index']
	})
}

export function isPopState() {
	return browser && idx > window.history.state['sveltekit:index']
}
```

### Importance

nice to have

**Comment by dummdidumm** [comment]
Closed via #6537
