### ISSUE TITLE
Clicking on a link before JS finishes loading breaks navigation

### ISSUE THREAD

**Issue by pablo-abc** [sveltejs/kit#652]
**Describe the bug**
If the user clicks on an internal link before the JS of the page finishes loading, the route changes but Svelte never navigates to the page. An `Uncaught Promise` is thrown in the logs with the message: `TypeError: can't access property "path", this.current.page is null`. This only happens consistently in production. I didn't manage to reproduce it in https://kit.svelte.dev at all, but I did manage to reproduce it consistently in [my site](https://felte.dev) which uses `adapter-static`.

**Logs**

```
Uncaught (in promise) TypeError: can't access property "path", this.current.page is null
    notify https://felte.dev/_app/start-66c1f370.js:1
    _navigate https://felte.dev/_app/start-66c1f370.js:1
    init https://felte.dev/_app/start-66c1f370.js:1
    init https://felte.dev/_app/start-66c1f370.js:1
    bt https://felte.dev/_app/start-66c1f370.js:1
    <anonymous> https://felte.dev/:32
```

**To Reproduce**
In the browser (e.g. Firefox) set throttling to Regular 2G (or something slow enough for you to click an internal link before JS finishes loading) and click the link. The URL should change to the appropriate value but the page never changes. An error is thrown in the console. I haven't managed to reproduce it consistently on a local environment, just on the production site. Using `svelte-kit build && svelte-kit start` does make the bug appear but rarely.

https://user-images.githubusercontent.com/40573613/112403833-74e32080-8d0f-11eb-94c4-3a6c0a47b49c.mov

**Expected behavior**
Clicking a link before JS loads should work as clicking a link in a page without JS at all.

**Stacktraces**
No stack trace.

**Information about your SvelteKit Installation:**

```
 System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 98.43 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.volta/tools/image/node/14.16.0/bin/node
    Yarn: 1.22.10 - ~/.volta/tools/image/yarn/1.22.10/bin/yarn
    npm: 7.5.4 - ~/.volta/tools/image/npm/7.5.4/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox Developer Edition: 87.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: 1.0.0-next.58 => 1.0.0-next.58
    svelte: ^3.0.0 => 3.35.0
 ```

- Tested in Firefox Developer Edition 87.0

- Adapter: static

**Severity**
Might block users with slow connections since the site will feel broken to them.

**Additional context**
I had a similar issue with sites built using `sapper export` as well.

**Comment by Rich-Harris** [comment]
Thanks — opened https://github.com/sveltejs/kit/pull/654
