### ISSUE TITLE
Loading module from “https://svelte-spectre.surge.sh/__data.js?__invalid=y&__id=2” was blocked because of a disallowed MIME type (“text/html”).

### ISSUE THREAD

**Issue by Valexr** [sveltejs/kit#6524]
### Describe the bug

Loading module from “https://svelte-spectre.surge.sh/__data.js?__invalid=y&__id=2” was blocked because of a disallowed MIME type (“text/html”).

### Reproduction

open devtools on https://svelte-spectre.surge.sh
code: https://github.com/Valexr/svelte-spectre

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 64.70 MB / 8.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.8.0 - /opt/homebrew/bin/node
    npm: 8.18.0 - /opt/homebrew/bin/npm
  Browsers:
    Firefox Developer Edition: 105.0
    Safari: 16.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
As described in the issue template: "Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project."

**Comment by Valexr** [comment]
I don’t know where error 🤷🏻‍♂️

**Comment by Valexr** [comment]
IIRC surge omits files beginning with underscore by default. If you create a .surgeignore file you should be whitelist that file.

**Comment by Valexr** [comment]
Why in file name used underscore?🤷🏻‍♂️

**Comment by Rich-Harris** [comment]
This looks like a bug — when I build your project, no `build/__data.js` file is generated

**Comment by Rich-Harris** [comment]
Ah wait, no it isn't a bug. You have a `+layout.server.ts` file (which means you need a server — in your case to read `.md` files from the filesystem), but you also have a `fallback` file (which means you don't have a server). They're incompatible. You need to prerender your site.

`adapter-static` should probably warn if you're using a fallback alongside a `+layout|page.server.js` file.

**Comment by Valexr** [comment]
I have exported `prerender = true` constant in root layout, but without fallback it’s not building… I don’t remember which version get this bug in surge, but previously it’s building & hosted 👌🏻

**Comment by Valexr** [comment]
[This fixed](https://github.com/Valexr/svelte-spectre/blob/b4db4d093e320b53748dc68e6a644c11dfce8671/src/www/%2Blayout.server.ts#L1) + remove fallback 👍🏻
Tx 🤓 @Rich-Harris  for explanation ✌🏻

**Comment by Valexr** [comment]
> I have exported `prerender = true` constant in root layout, but without fallback it’s not building… I don’t remember which version get this bug in surge, but previously it’s building & hosted 👌🏻

& build with this ☝🏻config working locally 🤷🏻‍♂️

**Comment by Valexr** [comment]
May be this info from @sintaxi will be useful:

`The default underscore omission was derived from conventions that some SSGs (mainly harp) and other publishing platforms have. In many situation sensitive or configuration information is stored in files that begin with underscore. Harp uses this convention heavily.`
