### ISSUE TITLE
Using +page.server.ts generated types in components when accessing $page.data

### ISSUE THREAD

**Issue by Lootwig** [sveltejs/kit#6528]
### Describe the problem

Accessing the parent page's `load()` through `$page.data` is great, but importing `PageData from './$types.d.ts'` is not possible, which I currently can only resolve through `$page.data as { propertyUsedForComponent: propertyValue }`. This obviously does not scale well.

### Describe the proposed solution

Allow importing `PageData` types in components.

### Alternatives considered

Passing all data in through `export const propertyUsed: KnownType`, which takes away the convenience of using the page store.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Could you clarify what the feature request is? You are talking about parent page's `load`, which you get through `await parent()`, not `$page.data`. Furthermore, it _is_ possible to import `PageData`, you do `import type { PageData } from './$types'`

**Comment by Lootwig** [comment]
The import doesn't seem to work from a component, at least neither VS Code nor IntelliJ pick up the file - is there something else required to configure to make it work?

**Comment by dummdidumm** [comment]
Where is you component located? The `./$types` import only works if you are inside the folder where the `+page.(server.)js` where that load function is coming from lives. Else you have to do something like `import type { PageData } from '.svelte-kit/types/...(path to your page)/$types`. If this is too confusing to type, you could reexport the type from the folder where that page is like `export type { PageData } from './$types'` and do `import type { PageData } from '..(path to that file)'`

**Comment by Lootwig** [comment]
Yeah it's a shared component under "lib".

As of now, the intellij svelte plugin (my preferred ide) doesn't support the context="module" script parts, nor the imports from ".svelte-kit/types", so both suboptimal but usable in VS Code.

Is it common to keep (single-use) components under "routes" next to their pages? I'm not sure yet whether I find it more structured if they're all under the same directory..

**Comment by dummdidumm** [comment]
I'd say yes - if you only use them on that page, put it inside the same route as that page. You have `+page.svelte` now, so you can easily distinguish that from regular components, and do not have to fear accidentally creating another route like with the old design.

Under the hood the `./$types` thing works because in the generated tsconfig we tell TypeScript that there's a "type root" which means "if you look for the type of an import, do not only look into the files that are next to it on the file system, also look at this other location".

**Comment by Lootwig** [comment]
> Under the hood the `./$types` thing works because in the generated tsconfig we tell TypeScript that there's a "type root" which means "if you look for the type of an import, do not only look into the files that are next to it on the file system, also look at this other location".

This only works in .ts files with the IntelliJ plugin; in .svelte files I have to specify the full relative path from the project root for the type to be usable.

But since that's not related to the issue, I'm good with closing this. Thanks for the superb responsiveness!

**Comment by Lootwig** [comment]
Yeah it's a shared component under "lib". I might go with the re-export
method for now.

Is it common to keep (single-use) components under "routes" next to their
pages? I'm not sure yet whether I find it more structured if they're all
under the same directory..
