### ISSUE TITLE
Dynamic route serving as index route when index.svelte is not present

### ISSUE THREAD

**Issue by erwin-k** [sveltejs/kit#653]
**Is your feature request related to a problem? Please describe.**
In my project I have configured the routes `/complexes/:id` and `/complexes` to render the same component.

However when doing it the traditional way (`/complexes/index.svelte` & `/complexes/[id].svelte`), the component gets remounted when navigating from `/complexes` to `/complexes/example` which is unfortunately not what I'm looking for (data fetching, transitions etc. all happens again).

To get around this I have `[...slug].svelte` at the root of my project which conditionally renders on wether the first param is `complexes`. This works but is not ideal.

**Describe the solution you'd like**
Ideally when there is no index route present the dynamic route page would be rendered with undefined (or null?) params.
Or maybe an additional naming scheme for routes like `index[slug].svelte` to indicate this behaviour.

**How important is this feature to you?**
It's not stopping me from getting further in my project, so I can't honestly say it should take high priority.

**Comment by Rich-Harris** [comment]
Can you have a `complexes/$layout.svelte` component that contains whatever logic needs to be shared between `complexes/index.svelte` and `complexes/[id].svelte`?

**Comment by erwin-k** [comment]
Doing it this way introduces some very random behaviour. 
My file structure:
![unknown](https://user-images.githubusercontent.com/67192919/112413289-3a35b400-8d20-11eb-991e-e7d74ef661ab.png)
`index.svelte` and `[complexId].svelte` are both empty

**$layout.svelte**
![unknown](https://user-images.githubusercontent.com/67192919/112417685-635a4280-8d28-11eb-9649-b8884d88a76c.png)


- Navigating from `/complexes/complex1` to `/complexes` won't trigger load.

- Landing on either `/complexes` or `/complexes/complex1` and navigating from there will remount layout but only after the first navigation, from then on it won't. However this only occurs sometimes and stops after restarting the dev server.

- Landing on `/complexes` will only fire the load function once and never again upon navigation.

- Landing on `/complexes/complex1` and from there navigating to `/complexes/complex2` works correctly, but navigating back to `/complexes` won't trigger the load function, however going back again to `/complexes/compex1` does fire load now.

- The dev server stops working randomly even after restarting it.

Editing any of the files and wether or not there is a slot component in layout randomizes all the behaviour described above, sometimes it happens, sometimes it won't, in some cases layout was remounting upon every navigation.

**Comment by erwin-k** [comment]
**update**
(2) seems to happen for any dynamic routes and related layouts regardless of anything.
(2) only occurs after editing a file, simply writing a comment and saving will cause this issue and disappears after restarting the dev server.

(1), (3), (4) and (5) are very random issues and I can't always 100% reproduce them but it seems related to having a load function and wether it returns props or not. Sometimes load will never run.

**Comment by erwin-k** [comment]
Closing this since this feature won't be needed when these bugs are fixed.
