### ISSUE TITLE
Update docs: `data-sveltekit-reload` can't be disabled by values other than `""`.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [sveltejs/kit#6532]
### Describe the problem

In https://kit.svelte.dev/docs/link-options#data-sveltekit-reload, there is no mention of how to conditionally turn on/off. It took me a while of trial and error to find out that all the following values have the same behaviour...
```svelte
<a  href="/"  data-sveltekit-reload={null}> ... </a>
<a  href="/"  data-sveltekit-reload={undefined}> ... </a>
<a  href="/"  data-sveltekit-reload={true}> ... </a>
<a  href="/"  data-sveltekit-reload={false}> ... </a>
<a  href="/"  data-sveltekit-reload="true"> ... </a>
<a  href="/"  data-sveltekit-reload="false"> ... </a>
<a  href="/"  data-sveltekit-reload="on"> ... </a>
<a  href="/"  data-sveltekit-reload="off"> ... </a>
<a  href="/"  data-sveltekit-reload="abcd"> ... </a>
```
... and only an empty string changes the behaviour:
```svelte
<a  href="/"  data-sveltekit-reload=""> ... </a>
```

### Describe the proposed solution

It would be great if the docs could be updated.

### Importance

nice to have

**Comment by ak4zh** [comment]
It not possible yet.
It’s planned to be added in future. Options like `data-sveltekit-prefetch=“viewport”` etc are not yet implemented, but will come in future.

**Comment by Glitchy-Tozier** [comment]
I know that `data-sveltekit-reload` works perfectly fine, but I was trying to conditionally evoke this functionality.

**Comment by dangelomedinag** [comment]
removing it using `undefined` is the default behavior of string attributes, as [Rich replied](https://twitter.com/Rich_Harris/status/1481232821201125383?t=QTRLwpNRfLa7DfZZdPFPWA&s=19) to a question I asked on twitter
