### ISSUE TITLE
prerendering with static-adapter doesn't work with next.455 changes

### ISSUE THREAD

**Issue by mprather** [sveltejs/kit#6538]
### Describe the bug

Prior to the release of https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next455, static prerendering was working with what I would consider an ordinary site. With the changes, the build step will not complete. 

Existing config:

- in svelte.config, 
  - prerender.default=true.
  - use @sveltejs/adapter-static with no parameters when initializing
  - specify set of prerender.entries to 2 values ('*', '/sitemap.xml')
- set of non-dynamic pages and 2 +server endpoints
  - 1 endpoint aggregates pages into a list to be consumed by a page that renders the list
  - 1 endpoint produced a sitemap
- leverage mdsvex plugin to create pages from markdown
- only 2 layouts
  - 1 layout at root
  - 1 layout in folder used by md files 

Instructions to accommodate breaking changes were implemented but no luck. 

Related side note: docs still mention the prerender.default option as valid.

Related note to design change: I understand the intent to make it easier to tweak what goes through prerender and what does not. however, the inability to set a global value and forcing a decision into each file and layout is not ideal.

### Reproduction

To accommodate breaking changes the following changes were made:
- removed config prerender.default setting
- added export of prerender to all layouts
- added export to +server files

Build results in the following error:

``
 @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root layout — see https://kit.svelte.dev/docs/page-options#prerender for more details
    - src\routes
error during build:
``

No additional information is provided. I've gone through the breaking change docs several times and confirmed expected changes exist in layouts and server pages. The error message is unfortunately not great. 

Note: I took at quick look at the code for the static adapter and I'm not sure that I understand the logic in index.js, lines 17 and 27 (https://github.com/sveltejs/kit/blob/e365633c29e3c94a37f7e11fc344d480b842887d/packages/adapter-static/index.js#L17).  Doesn't the call to builder.createEntries always push a value into the string array on line 17, then the check in line 27 will always be true. Am I reading that right? 

Or have I missed something in the upgrade?

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 15.99 GB / 31.59 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.70), ChromiumDev (106.0.1363.0)
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.41
    @sveltejs/kit: next => 1.0.0-next.464
    svelte: ^3.48.0 => 3.50.0
    vite: ^3.1.0-beta.1 => 3.1.0-beta.2
```

### Severity

blocking an upgrade

### Additional Information

Not sure if this is a user error (misunderstanding documentation or lack of documentation) or a product bug. Will need to stay on release 420 in the meantime.

**Comment by mcmxcdev** [comment]
I was also not able to make this work, using `@sveltejs/adapter-static` as well.

**Comment by Rich-Harris** [comment]
Please provide a repro

**Comment by mprather** [comment]
Simple repo with 2 files -> https://stackblitz.com/edit/sveltejs-kit-template-default-vzfod8

**Comment by janosh** [comment]
Seeing the same error in a lot of my SvelteKit repos. Switching to `adapter-netlify` is a [temporary workaround](https://github.com/janosh/svelte-multiselect/pull/103/commits/be2f81715cd23f1dc6965d6cf1ceccfa4d62c351).

> @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root layout — see https://kit.svelte.dev/docs/page-options#prerender for more details

**Comment by charbelnicolas** [comment]
Did you try adding `export const prerender = true` to layout.js instead of layout.svelte?

**Comment by janosh** [comment]
@charbelnicolas Oops my bad, I thought I should be exported from `+layout.svelte`. All is working when exporting from `+layout.ts` instead.

**Comment by charbelnicolas** [comment]
> @charbelnicolas Oops my bad, I thought `prerender` should be exported from `+layout.svelte`. All is working when exporting from `+layout.ts` instead. Thanks! 👍

You're welcome @janosh! The same thing happened to me a few days ago hehehe

**Comment by mprather** [comment]
I also added a `+layout.ts` and everything lit up.  Thanks for the lead, @charbelnicolas.

The takeaways from this issue:
1) the docs need to be updated in 2 places.
2) in the error case, the resulting error message needs improvement

### Document update suggestions
Location: https://kit.svelte.dev/docs/page-options#prerender
> Alternatively, you can set export const prerender = true in your root +layout and prerender everything except pages that are explicitly marked as not prerenderable:

I read that multiple times and it never dawned on me that it was the script file instead of the .svelte file.  Simple fix is adding the extension to +layout`.js`


Location: https://kit.svelte.dev/docs/configuration#prerender
> default — set to true to prerender encountered pages not containing export const prerender = false

This is no longer true and should be removed.

Of all the breaking changes in the past few weeks, this change really doesn't sit well with me because instead of allowing me to globally specify a behavior and then selectively modifying the behavior, I'm forced to micro-manage the behavior. With large sites that may use a large number of N layouts, this change forces the creation N extra files -- all of which say the same thing (and there is just more clutter to +server.js files). Please consider allowing a global default to exist.

### Error message suggestion
> Try adding `export const prerender = true` to your root layout

It would be a good idea to add the .js extension to the error message.


Considering our sites didn't previously require +layout.ts files, the documentation and error message's generalized references to `+layout` and `root layout` led me to believe the fix was updating the `+layout.svelte`.

**Comment by charbelnicolas** [comment]
Yep, they really need to update the docs and I agree with you that having an extra one liner layout.js file is cumbersome.

**Comment by Rich-Harris** [comment]
> Of all the breaking changes in the past few weeks, this change really doesn't sit well with me because instead of allowing me to globally specify a behavior and then selectively modifying the behavior, I'm forced to micro-manage the behavior. With large sites that may use a large number of N layouts, this change forces the creation N extra files -- all of which say the same thing (and there is just more clutter to +server.js files). Please consider allowing a global default to exist.

We replaced one way of specifying a global default (`config.kit.prerender.default`) with another (setting `prerender` in your root layout). This is much more flexible since you can also set it in individual layouts to control entire subtrees. So no, this doesn't force the creation of N extra files, it forces the creation of _one_ extra file (or zero, if you already have a root `+layout.js`) and allows you to _delete_ per-page overrides in favour of per-layout overrides, which are likely to be vastly fewer in number.

**Comment by mprather** [comment]
The assumption that all sites will have a root layout doesn't hold for everyone.  Even with the 2 sites we have under development, we've had to go through and add multiple files and update quite a few +server files.  

I don't consider our projects to be complex or elaborate; deciding to save for more complex sites after we learned how to better use svelte (my team decided to start using svelte-kit back in June).  I fully expect on some of the more elaborate sites, we would have a large number of layouts all requiring this bit of customization (i.e. add another file), but none really relying on a root level layout.

A global setting was very nice. It was simple.  This change moved away from simple. 

Prerender should be settable in the config file with the opportunity to override as needed.  Why can't we have both a global setting and improved per-layout mechanism? 

If you want simple, use the config setting. Why in the world do I want to *repeatedly* state that I want to prerender when I know the entire project is supposed to have the same characteristic?  In the small site (< 15 total pages) where we first ran into this issue, we've had to state this fact no less than 4 times (2 layouts, 2 server files). This is not efficient or simple. Before the change, the fact was stated once. I could look at the config file, see that the project is set to use the static adapter and prerender was set to true. Simple. 

If you want to be more granular, then use +layout.js and +server.js files. 

For the foreseeable future (for our current and anticipated projects), this change adds clutter. A global setting + the new per-layout/per-server format would be a win for everyone.


Also, shouldn't this issue be used to track the documentation bugs if fact they lead to users going down the wrong path?

**Comment by janosh** [comment]
@mprather Like @Rich-Harris said, in applies to subtrees. Not sure, why you would have to set `prerender` to `true` repeatedly? If you just export it from `src/routes/+layout.ts`, it should apply to the whole app.

**Comment by mprather** [comment]
@janosh For every +server.ts file, the setting must be declared. I was hoping that +layout.ts or +layout.server.ts would serve as the global declaration but it does not. Or am I missing something else?  

Again, the big assumption with the above statements is that you have a root layout.ts file. We didn't need it previously and quite frankly didn't think to create one because we like to keep functionality together (i.e. if no +layout.svelte exists, why create a corresponding +layout.ts?); hence, we need to update 2 layouts in addition to 2 server files.

If my site is heavy with server endpoints and even though a root-level +layout.ts (or +layout.server.ts) exists, all I can see is that we moved away from a clean solution to one that requires duplicated code and extra files.
