### ISSUE TITLE
Conditional request handling makes output caching difficult

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#6558]
### Describe the problem

SvelteKit has built-in [support for conditional request handling](https://github.com/sveltejs/kit/blob/164cddb9577335ef08a0fe1ed2d492f6b60db0f4/packages/kit/src/runtime/server/index.js#L278), to provide a "304 Not Modified" response if the client already has the resource requested. This is great, and can save bandwidth and reduce TTLB.

However, if you want to use output caching (either in-memory or via Redis or Memcached) in order to avoid the complete render + data-access part and improve TTFB, it is a little awkward to work around.

Unless you remove the `if-none-match` header and re-create how it is handled _after_ the `resolve(event)` call the response you get may have already been turned into a "304 Not Modified" response, denying the ability to cache it. On a site with mostly static content and lots of repeat visitors, this might negatively affect cache-hit ratios.

Also, because the handling of it is done inside of `resolve(event)`, if you _have_ a cached response to return, you now miss out on sending the "304 Not Modified" response (unless you have re-created the code, in your own `handle` method).

### Describe the proposed solution

If the conditional handling was _after_ the hooks handle call it would be more straight-forward to return a cached response and also have _that_ response be evaluated.

### Alternatives considered

Using a custom server with the node-adapter and some caching middleware, but it may be something that non-node deploys would benefit from too.

### Importance

nice to have

### Additional Information

Removing the http header and re-implementing the conditional handling works, but feels kludgy.

**Comment by Rich-Harris** [comment]
> If the conditional handling was _after_ the hooks handle call it would be more straight-forward to return a cached response and also have _that_ response be evaluated.

To be clear, you're saying that you want to add some caching logic in your `handle` hook, so you want `resolve(event)` to return a non-304 response but then turn the return value from `handle` into a 304 if appropriate? That makes sense, yeah

**Comment by benmccann** [comment]
I didn't closely read the part about memcached, etc. but in general it would make sense to me that etag handling should happen after `handle` since `handle` may change the response. While I suppose this would be a change in behavior, I would classify it as a bug fix more than a breaking change.

**Comment by Rich-Harris** [comment]
Yeah it's borderline. I figured I'd include it anyway since it should be a nice quick fix
