### ISSUE TITLE
Service worker reference is absolute, should be relative

### ISSUE THREAD

**Issue by bassjoe** [sveltejs/kit#6561]
### Describe the bug

The service worker reference in `build/index.html` is `/service-worker.js`, i.e. still absolute, while the other references are (finally :partying_face:) relative.

### Reproduction

https://github.com/bassjoe/pwa3
- created sveltekit app
- changed from `auto` adapter to `static` adapter, creating `src/routes/+layout.js`
- created `src/service-worker.js`

To reproduce:
- run `npm install` and `npm run build`
- see `build/index.html`
 
The resulting `index.html` looks like this: https://github.com/bassjoe/pwa3/blob/gh-pages/index.html
And the service worker obviously can't be loaded: https://bassjoe.github.io/pwa3/

### System Info

```shell
System:
    OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 11.72 GB / 15.51 GB
    Container: Yes
    Shell: 3.5.0 - /usr/bin/fish
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Firefox: 104.0.1
  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.41 
    @sveltejs/kit: next => 1.0.0-next.468 
    svelte: ^3.44.0 => 3.50.0 
    vite: ^3.1.0-beta.1 => 3.1.0-beta.2
```

### Severity

serious, but I can work around it

### Additional Information

This is similar to https://github.com/sveltejs/kit/issues/3290

**Comment by julien-vu** [comment]
to my app, still an error 404 with non root url. event with the serviceWorker in config

**Comment by julien-vu** [comment]
Not exactly the same issue:

using adapter-node, svelte kit 322, and baseUrl

still got 404 on service-worker.js when the assets and everything else works fine
