### ISSUE TITLE
beforeNavigation doesn't understand link with `data-sveltekit-reload`

### ISSUE THREAD

**Issue by TranscendentalRide** [sveltejs/kit#6575]
### Describe the bug

If a link has `data-sveltekit-reload` on it, you should still be able to have `to` data in the `beforeNavigate` function. And it should be cancellable. 

Currently the value for `to` is `undefined` and `cancel` does something worse than nothing. It ask if you are sure you want to leave the page. Something it doesn't do if you don't cancel. Though there should likely be a simple way to prompt this in the browser, `cancel` isn't the intention here.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-svvcbr?file=src%2Flib%2Fheader%2FHeader.svelte,src%2Froutes%2F%2Blayout.svelte&terminal=dev

Step 1: Click HOME
Step 2: Click TODO

Observation 1: Prompted by browser despite cancel
Observation 2: Look for console.log output

### System Info

```shell
MacOS 12.5, Chrome 104, SvelteKit 1.0.0-next.465
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
This is just how browsers work. If you click on a link that isn't handled by the client-side router (which is the case when `data-sveltekit-reload` is set) then SvelteKit has no power to cancel the navigation other than by running the `beforeNavigate` hook in `beforeunload` and triggering the browser prompt. There are many things that can trigger `beforeunload` (link click, history traversal, programmatic `location.reload()`, `location = blah`) which means it's not possible for the framework to attribute it to a specific navigation intent, hence `to === null`.
