### ISSUE TITLE
Combine param matcher

### ISSUE THREAD

**Issue by KekOnTheWorld** [sveltejs/kit#6579]
## The problem

I have considered writing a social platform using svelte kit where users can either be identified by their unique id or their username. 
I now made param matchers for both types (name: [a-z]{2,16}, id: [0-9]{8}) and wanted to create a route where you can view individual users (/users/[user]).

I'd now have to create 2 routes:

> /users/[id=id]
> /users/[name=name]

and write a +page.ts and page.svelte for both even if the content that will be displayed there is **exactly the same**.

That's a pain in the arse, so i wondered if we could combine param matchers somehow.

## Merging param matchers

> /users/[id=id|name=name]

 *(The actual syntax definition here is not final and may change)*

This will now either match type id or name (Left to right. If none matched, try the other routes or 404)

#### Using 2 files

 > /users/[id=id|name=name]/+page|name.ts

```ts
import { session } from "$lib/store";
import { get_store_value } from "svelte/internal";
import type { PageLoad } from "./$types";

export const load = async function({ params }) {
    // Fetch the user by its name
    return { 
        user: await get_store_value(session)
                ?.users.fetchByName(params.name)
    };
} as PageLoad;
```

 > /users/[id=id|name=name]/+page|id.ts

```ts
import { session } from "$lib/store";
import { get_store_value } from "svelte/internal";
import type { PageLoad } from "./$types";

export const load = async function({ params }) {
    // Fetch the user by its id
    return { 
        user: await get_store_value(session)
                ?.users.fetchById(params.id)
    }
} as PageLoad;
```

#### Using 1 file

<br>

 > /users/[id=id|name=name]/+page.ts

```ts
import { error } from "@sveltejs/kit";
import { session } from "$lib/store";
import { get_store_value } from "svelte/internal";
import type { PageLoad } from "./$types";

export const load = async function({ params }) {
    if(params.id) {
        // Fetch the user by its id
        return { 
            user: await get_store_value(session)
                    ?.users.fetchById(params.id)
        }
    } else if(params.name) {
        // Fetch the user by its name
        return { 
            user: await get_store_value(session)
                    ?.users.fetchByName(params.name)
        };
    } else throw error(500, "Not implemented"); // This should not happen since we wouldn't execute the load function if none matched.
} as PageLoad;
```

<br>

So this will now either load the user by its id or by its name. The layout of +page.svelte would stay the same for id and name since both will be resolved into an User object.

 > /users/[id=id|name=name]/+page.svelte

```html
<script lang="ts">
    import type { User } from "$lib/api";
    import type { PageData } from "./$types";

    export let data: PageData;
    const user: User = data.user;
</script>

<div class="profile">
    <img src={user.avatar} alt="">
    <h1>{user.username}</h1>
    <p>{user.id}</p>
</div>
```

<br>

### Do it the other way around (obscure)

Here the data processing itself stays the same for both types, so we don't wanna split them into different folders, but we want to display the 2 differently.

<br>

> /show/[data=integer|data=string]/+page.ts

```ts
import type { PageLoad } from "./$types";

export const load = function({ params }) {
    // Forward the parameters
    return params;
} as PageLoad;
```

> /show/[data=integer|data=string]/+page|integer.ts
```html
<script lang="ts">
    import type { PageData } from "./$types";

    export let data: PageData;
</script>

<p>You entered an integer: {data.data}</p>
```

> /show/[data=integer|data=string]/+page|string.ts

```html
<script lang="ts">
    import type { PageData } from "./$types";

    export let data: PageData;
</script>

<p>You entered a string: {data.data}</p>
```

### Using a component

- Duplicate code:
  We'd need to create 2 +page.svelte which contain basically the same code.

### Importance

would make my life easier

**Comment by s3812497** [comment]
One workaround is to evaluate the `params` inside the load function, and ditch the SvelteKit params matching (to avoid evaluating the `params` twice).
Example:
```ts
export const load = async function({ params }) {
   const store_value = await get_store_value(session);
   
   const id = params.match(/^[0-9]{8}$/);
   if (isId) {
        // Fetch the user by its id
        return { 
            user: store_value?.users.fetchById(params)
        };
   };
   
   const isName = params.match(/^[a-z]{2,16}$/);
   if (isName) {
        // Fetch the user by its name
        return { 
            user: store_value?.users.fetchByName(params)
        };
   }
   
   throw error(404, "Invalid user name / id");
} as PageLoad;
```

Param matching combinations could be nice though (although the filename would get really long).

**Comment by Rich-Harris** [comment]
Just create a param matcher that handles both cases:

```
/users/[id=user]
```

```js
// src/params/user.js
import { id, name } from '$lib/match';

export const match = param => id(param) || name(param);
```

```js
// src/routes/users/[id=user]/+load.js
import { id, name } from '$lib/match';

/** @type {import('./$types').PageLoad} */
export async function load({ params }) {
  const user = id(params.user)
    ? await fetchById(params.user)
    ? await fetchByName(params.user);

  return { user };
}
```

This is a very niche requirement (it's not good SEO practice to have two different URLs pointing to the same resource, and so this pattern is best avoided) and it's easily solved in userland, so it wouldn't be appropriate to add complexity to the framework.
