### ISSUE TITLE
Erroneous 'Missing svelte.config.cjs' error

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#659]
**Describe the bug**
If your svelte.config.cjs file requires a non-existent module, you get a 'Missing svelte.config.cjs' error, because of this line... https://github.com/sveltejs/kit/blob/8805c6daa6b11a46d2d373c3db890227b27e660d/packages/kit/src/cli.js#L30 ...which doesn't care which MODULE is NOT_FOUND.

**Expected behavior**
For MODULE_NOT_FOUND where it's a different module that's missing, just throw the error as-is instead of trying to make it nice

**Severity**
Minor

**Comment by kazerlelutin** [comment]
same issue : 

```bash
Error: Cannot find module '@sveltejs/app-utils/renderer'
```

**Comment by Rich-Harris** [comment]
@kazerlelutin that suggests some of your dependencies are out of date, we recently got rid of the `app-utils` package altogether
