### ISSUE TITLE
Can you explain the difference between theses 2 differents ways to call the 'load' function ?

### ISSUE THREAD

**Issue by regnou** [sveltejs/kit#6590]
### Describe the problem

Hi, 
you can have a load function, in a +page.js like this (note the context=module):
case 1)
```
<script context="module">
  export function load({ error, status }) {
```
case 2)
or in a file +pagE.server.js
```
/** @type {import('./$types').PageServerLoad} */
export function load() {
```

I did not understood if theses 2 functions are the same at the end ? because both load will execute server side if I am right... So Is there a difference, and if not, is that a good idea this kind of 'duplication' ?

Thanks you,

### Describe the proposed solution

-

### Alternatives considered

-

### Importance

nice to have

### Additional Information

-

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

That said, there's no such thing anymore as `load` in `<script context='module'>`. See https://kit.svelte.dev/docs/load which explains the difference between `+page.js` and `+page.server.js`.
