### ISSUE TITLE
New `use:enhance` is good thing, but we need exported type for it's handler.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#6605]
### Describe the problem

If you don't like to use inline functions, and define handler in script tag, you get error bcs of incorrect types. You need to define types youtself, as SvelteKit doesn't expose types for `use:enhance` action handler.

### Describe the proposed solution

Export types for action handler.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Could you describe in more detail what you mean? Do you mean that you want the type of the submit callback function exposed? Could you give a code example of what you want to achieve?

**Comment by Mlocik97** [comment]
```html
<script>
/** @type {???} */
function add({ form }) {
    return (result) => {
        if (result.type === 'success') {
            form.reset();
            invalidateAll();
        }
    }
}
</script>

<form use:enhance={add} >
    <!-- some inputs -->
</form>
```

**Comment by repsac-by** [comment]
As a workaround
```js
/** @type {NonNullable<Parameters<typeof enhance>[1]>} */
```
