### ISSUE TITLE
New `use:enhance` is good thing, but boilerplatish... can we reduce boilerplate and redesign it?

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#6606]
### Describe the bug

Old `use:enhance`'s handler:

```js
const result = ({ form }) => form.reset();
```

New `use:enhance`'s handler... same logic (reseting form after successful submit):

```js
function add({ form }) {
    return (result) => {
        if (result.type === 'success') {
            form.reset();
            invalidateAll();
        }
    }
}
```

This is really big increase of LOCs (from 1 to 8). Yes, new `use:enhance` is more powerfull, but still I think we can do it much better without making it powerless.

### Reproduction

1. `npm create svelte && npm i`
2. in `./src/routes/todos/+page.svelte` try to extract `use:enhance`'s handler to function in script tag for `/todos?/add` form (or see it even inline, that doesn't matter).

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 2.06 GB / 15.45 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Browsers:
    Chrome: 105.0.5195.52
    Firefox: 104.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/kit: next => 1.0.0-next.472 
    svelte: ^3.46.0 => 3.50.0 
    vite: ^3.1.0 => 3.1.0
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
The `enhance` action surely won't fit everyone's need, but the beauty of it is that you can recreate all of this writing your own enhance function, or wrapping the enhance action with something more opinionated you want:

```js
import { enhance, invalidateAll, updateForm } from '$app/forms';

export function myEnhance({result}) {
  return enhance(({form}) => {
    return (response) => {
       updateForm(response);
       if (response.type === 'success') {
         invalidateAll();
         result();
       }
    }
  }
```
You can even copy-paste/keep the old version of `enhance` and create your own function from scratch. If you look at the source code, it really isn't much: https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/app/forms.js#L19-L65

**Comment by Rich-Harris** [comment]
> This is really big increase of LOCs (from 1 to 8)

I don't follow. Before:

```svelte
<form
  method="POST"
  use:enhance={{
    result: ({ form }) => form.reset()
  }}
>
```

After:

```svelte
<form
  method="POST"
  use:enhance={({ form }) => {
    return ({ type }) => {
      if (type === 'success') {
        invalidateAll();
        form.reset();
      }
    };
  }}
>
```

It _is_ an increase in this particular case (though not from 1 to 8 LOC, not sure where you got that from), because we wanted a design that scales better — the old `enhance` doesn't cleanly differentiate between redirect and success responses, and makes it unnecessarily difficult to handle complex pending UI states. On balance, the new design is better.

**Comment by Mlocik97** [comment]
```html
<script>
    const result = ({ form }) => form.reset();         // 1
</script>

<form use:enhance={{ result }} >
    <!-- some inputs -->
</form>
```

vs

```html
<script>
function add({ form }) {                               // 1
    return (result) => {                               // 2
        if (result.type === 'success') {               // 3
            form.reset();                              // 4
            invalidateAll();                           // 5
        }                                              // 6
    }                                                  // 7
}                                                      // 8
</script>

<form use:enhance={add} >
    <!-- some inputs -->
</form>
```

**Comment by Mlocik97** [comment]
> The `enhance` action surely won't fit everyone's need, but the beauty of it is that you can recreate all of this writing your own enhance function, or wrapping the enhance action with something more opinionated you want:
> 
> ```js
> ```
> 
> You can even copy-paste/keep the old version of `enhance` and create your own function from scratch. If you look at the source code, it really isn't much: https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/app/forms.js#L19-L65

Yeah, I know, that's fine... but if we need to write this to our scripts, I find like framework didn't somehow done work well.

**Comment by Mlocik97** [comment]
> ...because we wanted a design that scales better — the old enhance doesn't cleanly differentiate between redirect and success responses, and makes it unnecessarily difficult to handle complex pending UI states. On balance, the new design is better.

I agree, that's fine part of new `use:enhance`, but is it really impossible to make it scale better and have easy handling of pending UI states without adding so much "boilerplate"?

**Comment by Mlocik97** [comment]
For example instead:

```js
function add({ form }) {
    return (result) => {
        if (result.type === 'success') {
            form.reset();
            invalidateAll();
        }
    }
}
```

we can have:

```js
function add({ form, result }) {
        if (result?.type === 'success') {
            form.reset();
            invalidateAll();
        }
}
```

is already some reduction of boilerplate. That function would be called like:

```html
<form use:enhance={{ result: add })>
    <!-- some inputs -->
</form>
```

while enhance could have pending for part of JS, that you actually have 

```js
function add({ form }) {
   // ---------- HERE -------
    return (result) => {
        if (result.type === 'success') {
            form.reset();
            invalidateAll();
        }
    }
}
```

means in result:

```js
<script>
    function add_pending({ form }) {
        // same code as the code that would be in part of script above marked `// ---------- HERE -------`
    }

    function add_result({ form, result }) {
        if (result.type === 'success') {
            form.reset();
            invalidateAll();
        }
    }
</script>

<form use:enhance={{ pending: add_pending, result: add_result }}>
    <!-- some inputs -->
</form>

**Comment by Mlocik97** [comment]
<table>
<tr>
	<th>Type</th>
	<th>Old enhance</th>
	<th>Today's enhance</th>
	<th>Proposal</th>
</tr>

<tr>
<td>Simple result - script</td>
<td>

```html
<script>
	const result = ({ form }) => form.reset();
</script>

<form use:enhance={{ result }}></form>
```

</td>
<td>

```html
<script>
	function add({ form }) {
		return (result) => {
			if (result.type === 'success') {
				form.reset();
				invalidateAll();
			}
		};
	}
</script>

<form use:enhance={add}></form>
```

</td>
<td>

```html
<script>
	function result({ form, result }) {
		if (result.type === 'success') {
			form.reset();
			invalidateAll();
		}
	}
</script>

<form use:enhance={{ result }}></form>
```

</td>
</tr>



<tr>
<td>Simple result - inline</td>
<td>

```html
<form use:enhance={{
    result: ({ form }) => form.reset()
}}>

</form>
```

</td>
<td>

```html
<form use:enhance={({ form }) => {
	return ({ type }) => {
      	if (type === 'success') {
			invalidateAll();
			form.reset();
		}
	};
}}>

</form>
```

</td>
<td>

```html
<form use:enhance={{
	result: ({ form, result }) => {
		if (result.type === 'success') {
			form.reset();
			invalidateAll();
		}
	}
}}>

</form>
```

</td>
</tr>

<tr>
<td>Simple pending - script</td>
<td>

```html
<script>
	const pending = ({ form }) => {};
</script>

<form use:enhance={{ pending }}></form>
```

</td>
<td>

```html
<script>
	const pending = ({ form }) => {};
</script>

<form use:enhance={pending}></form>
```

</td>
<td>

```html
<script>
	const pending = ({ form }) => {};
</script>

<form use:enhance={{ pending }}></form>
```

</td>
</tr>


<tr>
<td>Simple result - inline</td>
<td>

```html
<form use:enhance={{
    pending: ({ form }) => {

	}
}}>

</form>
```

</td>
<td>

```html
<form use:enhance={({ form }) => {
	
}}>

</form>
```

</td>
<td>

```html
<form use:enhance={{
	pending: ({ form }) => {

	}
}}>

</form>
```

</td>
</tr>


<tr>
<td>Pending, Result combined - script</td>
<td>

```html
<script>
	const result = ({ form }) => form.reset();
	const pending = ({ form }) => {};
</script>

<form use:enhance={{ result, pending }}></form>
```

</td>
<td>

```html
<script>
	function add({ form }) {
		// pending code on this line
		return (result) => {
			if (result.type === 'success') {
				form.reset();
				invalidateAll();
			}
		};
	}
</script>

<form use:enhance={add}></form>
```

</td>
<td>

```html
<script>
	const result = ({ form }) => form.reset();
	const pending = ({ form }) => {};
</script>

<form use:enhance={{ result, pending }}></form>
```

</td>
</tr>

<tr>
<td>Pending, Result combined - inline</td>
<td>

```html
<form use:enhance={{
    result: ({ form }) => form.reset(),
	pending: ({ form }) => {}
}}>

</form>
```

</td>
<td>

```html
<form use:enhance={({ form }) => {
	// pending code on this line
	return ({ type }) => {
      	if (type === 'success') {
			invalidateAll();
			form.reset();
		}
	};
}}>

</form>
```

</td>
<td>

```html
<form use:enhance={{
	result: ({ form, result }) => {
		if (result.type === 'success') {
			form.reset();
			invalidateAll();
		}
	},
	pending: ({ form }) => {}
}}>

</form>
```

</td>
</tr>
</table>

**Comment by Mlocik97** [comment]
Another idea... can SvelteKit somehow detect if data in handler were already invalidated and if not, call invalidate? Like with old code:

```js
function add({ form }) {
    return (result) => {
        if (result.type === 'success') {
            form.reset();
            invalidateAll();
           // some more code
        }
    }
}
```

would invalidate on line `invalidateAll()` before `// some more code`, but

```js
function add({ form }) {
    return (result) => {
        if (result.type === 'success') {
            form.reset();
           // some more code
        }
    }
}
```

as there is no `invalidate` at all, it would automatically invalidate at end of function (and that's actually it should do, so `use:enhance`'s behavior is closer to standard form submits without JS, because they always invalidates (as whole page refresh in that case), so it should always need to invalidate. This would also reduce boilerplate.

**Comment by UltraCakeBakery** [comment]
> ```
> <script>
>     const result = ({ form }) => form.reset();         // 1
> </script>
> 
> <form use:enhance={{ result }} >
>     
> </form>
> ```
> 
> vs
> 
> ```
> <script>
> function add({ form }) {                               // 1
>     return (result) => {                               // 2
>         if (result.type === 'success') {               // 3
>             form.reset();                              // 4
>             invalidateAll();                           // 5
>         }                                              // 6
>     }                                                  // 7
> }                                                      // 8
> </script>
> 
> <form use:enhance={add} >
>     
> </form>
> ```
> 
> I counted just JS part and when is extracted to script tag. Not if it's inline.


```html
<script>
const add = ({form}) => (({type})=> {if(type === 'success'){form.reset(); invalidateAll();}}) // 1
</script>
```

**Comment by Mlocik97** [comment]
@UltraCakeBakery do you find that readable? Ofc, you can write even 1000 LOCs of JS code to one line....

**Comment by UltraCakeBakery** [comment]
> 


> @UltraCakeBakery do you find that readable? Ofc, you can write even 1000 LOCs of JS code to one line.... but it doesn't solve anything.
> 
> Also after using prettier, it breaks to multiple lines.
> 
> ```js
> const add =
> 		({ form }) =>
> 		({ type }) => {
> 			if (type === 'success') {
> 				form.reset();
> 				invalidateAll();
> 			}
> 		}; // 1
> ```
> 
> that's not one line... it's 8 LOCs.

Just giving you a one liner that - if you are not slightly more than a beginner to javascript, I think... - is, in my opinion, relatively simple and works as a replacement for what you had before. I edited the code to make it more "readable".

**Comment by Mlocik97** [comment]
giving :+1: to yourself, while it's still not one-liner.... you are weird person, please don't write here anymore.

**Comment by Conduitry** [comment]
We're not optimizing for one-liners. It's not a bug if certain situations require more lines of code than they used to. If you don't like it, it's straightforward to write your own version of the action that behaves exactly how you want.
