### ISSUE TITLE
Add `Origin` request header for the server-side fetch

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#6608]
### Describe the bug

Related #6550
Basically what @kevinrenskers said [here](https://github.com/sveltejs/kit/pull/6550#issuecomment-1236366109).

The behavior isn't currently sound and can cause unexpected errors — my server is configured to return the right CORS headers, but I'm getting CORS errors using the server-side fetch that I wouldn't get using the browser's fetch — the server-side fetch must automatically send an `Origin` header along with the request in order for the CORS stuff to work properly, this is how the native browser `fetch` works.

### Reproduction

Explained above.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.01 GB / 3.77 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    Yarn: 1.22.15 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/adapter-node: ^1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.472 
    svelte: ^3.44.0 => 3.49.0 
    vite: ^3.1.0-beta.1 => 3.1.0
```

### Severity

blocking an upgrade

**Comment by itssumitrai** [comment]
Facing the same issue, `Origin` header is not being forwarded which creates issues with CORS

**Comment by ponderingexistence** [comment]
Same here

**Comment by andreasnuesslein** [comment]
same here; problem was introduced in https://github.com/sveltejs/kit/tree/%40sveltejs/kit%401.0.0-next.468

**Comment by randyridge** [comment]
also hit this, can workaround by manually setting the origin header, but it's a little bit of a hassle as we have to configure it per-environment and we use fetch indirectly via urql...

**Comment by rohanrajpal** [comment]
One thing to note is that (after this issue is fixed) it'd be great to still allow customizing the origin.

It would be useful for the folks who run sveltekit behind an nginx proxy, typically in a proxy the URL would be `http://local.dev` but request would be coming from `https://local.dev`

**Comment by itssumitrai** [comment]
Any timelines to fix this issue, this is a major bug the workaround of adding Origin to every request is also a very unsafe option, you shouldn't be doing that and accidentally opening up yourself to further attacks.

**Comment by Christopher2K** [comment]
This is how I did it in `hooks.server.ts`

```typescript
export const handleFetch: HandleFetch = async ({ request, fetch }) => {
  if (request.url.startsWith(apiUrl)) {
    // Workaround: https://github.com/sveltejs/kit/issues/6608
    request.headers.set('origin', appUrl)
  }

  return fetch(request)
}
```

I'm not sure if this is the right thing to do atm

I'm

**Comment by smblee** [comment]
> This is how I did it in `hooks.server.ts`
> 
> ```ts
> export const handleFetch: HandleFetch = async ({ request, fetch }) => {
>   if (request.url.startsWith(apiUrl)) {
>     // Workaround: https://github.com/sveltejs/kit/issues/6608
>     request.headers.set('origin', appUrl)
>   }
> 
>   return fetch(request)
> }
> ```
> 
> I'm not sure if this is the right thing to do atm
> 

Good work around!

I think you could replace appUrl with `event.url.origin` for now

**Comment by Christopher2K** [comment]
> > This is how I did it in `hooks.server.ts`
> 
> > 
> 
> > ```ts
> 
> > export const handleFetch: HandleFetch = async ({ request, fetch }) => {
> 
> >   if (request.url.startsWith(apiUrl)) {
> 
> >     // Workaround: https://github.com/sveltejs/kit/issues/6608
> 
> >     request.headers.set('origin', appUrl)
> 
> >   }
> 
> > 
> 
> >   return fetch(request)
> 
> > }
> 
> > ```
> 
> > 
> 
> > I'm not sure if this is the right thing to do atm
> 
> > 
> 
> 
> 
> Good work around!
> 
> 
> 
> I think you could replace appUrl with `event.url.origin` for now

Good catch, I totally forgot va bout this one 🙏🏿
