### ISSUE TITLE
The postinstall script for a SvelteKit project runs in the root of a monorepo resulting in failure to generate the .svelte-kit folder

### ISSUE THREAD

**Issue by seantimm** [sveltejs/kit#6617]
### Describe the bug

My .svelte-kit folder wasn't getting generated on initial npm install from the root of my monorepo, so I dug in and saw that when the @sveltejs/kit postinstall script was running, it's trying to access the svelte.config.js from the root rather than the project that has the dependency.

### Reproduction

Run "npm install --foreground-scripts" from the root of the following repo to see the errors about a missing svelte.config.js:

https://github.com/seantimm/sveltekit-postinstall-problem

### Logs

```shell
> @sveltejs/kit@1.0.0-next.474 postinstall
> node svelte-kit.js sync

Missing /projects/postinstall-problem/svelte.config.js - skipping
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.74 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.15.0 - ~/.volta/tools/image/npm/8.15.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.102
    Firefox Developer Edition: 99.0
    Safari: 15.6.1
```

### Severity

annoyance

**Comment by seantimm** [comment]
Also, I think this *may* have worked fine in the past when it required a prepare script (probably because it was running in the correct folder and found the config file).

**Comment by pyronaur** [comment]
Did you manage to figure this out? I'm seeing a similar issue when building in Cloudflare:

```


23:34:51.013 |  
-- | --
23:34:51.026 | npm ERR! code ELIFECYCLE
23:34:51.027 | npm ERR! errno 1
23:34:51.027 | npm ERR! @sveltejs/kit@1.0.0-next.484 postinstall: `node svelte-kit.js sync`
23:34:51.027 | npm ERR! Exit status 1
23:34:51.027 | npm ERR!
23:34:51.027 | npm ERR! Failed at the @sveltejs/kit@1.0.0-next.484 postinstall script.
23:34:51.027 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
23:34:51.052 |  
23:34:51.052 | npm ERR! A complete log of this run can be found in:
23:34:51.052 | npm ERR!     /opt/buildhome/.npm/_logs/2022-09-17T20_34_51_042Z-debug.log
23:34:51.063 | Error during NPM install
23:34:51.066 | Failed: build command exited with code: 1
23:34:51.874 | Failed: an internal error occurred
```

This doesn't happen locally for me  - only on cloudflare.

**Comment by gbkwiatt** [comment]
Just found that - but having issue again with mono repo - if app/package does not hav sveltekit in package json, but only in root mono repo package.json - it still does not run sync in workspace directories. 
I've had to add it to each package.json for each package and app

**Comment by parkernilson** [comment]
I believe this is happening again with Deno 2 in a monorepo setting. This may be a Deno 2 problem and not relevant to SvelteKit, but I figured I would bring it up. May be a difference between how Deno 2 and NPM resolve INIT_CWD.

**Comment by wsoule** [comment]
> I believe this is happening again with Deno 2 in a monorepo setting. This may be a Deno 2 problem and not relevant to SvelteKit, but I figured I would bring it up. May be a difference between how Deno 2 and NPM resolve INIT_CWD.

also getting this with Deno 2
