### ISSUE TITLE
`svelte-kit dev --open` doesn't work on Linux

### ISSUE THREAD

**Issue by bjon** [sveltejs/kit#662]
**Describe the bug**
When running `svelte-kit dev --open`, the server starts, but `localhost:3000` isn't opened.

**To Reproduce**
Run `svelte-kit dev --open`, on Linux.

**Expected behavior**
Should open `localhost:3000` in the default browser

**Information about your SvelteKit Installation:**
```
  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 12.65 GB / 31.35 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.21.0 - /usr/bin/node
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.59 
    svelte: ^3.29.0 => 3.35.0 
```

**Severity**
Low

**Possible solution**
In
[https://github.com/sveltejs/kit/blob/957613747ba48cb9ccb9d339d4c6e61e539ca709/packages/kit/src/cli.js#L50](https://github.com/sveltejs/kit/blob/957613747ba48cb9ccb9d339d4c6e61e539ca709/packages/kit/src/cli.js#L50)
replace
```javascript
  exec(`${process.platform == 'win32' ? 'start' : 'open'} http://localhost:${port}`);
```
with
```javascript
  let cmd = 'open';
  if (process.platform == 'win32') {
    cmd = 'start';
  } else if (process.platform == 'linux') {
    cmd = 'xdg-open';
  }
  exec(`${cmd} http://localhost:${port}`);
```

**Comment by icyrockcom** [comment]
@bjon I hope you don't mind me packaging this as a pull-request https://github.com/sveltejs/kit/pull/667.

**Comment by bjon** [comment]
@icyrockcom 👍🏻 👍🏻
