### ISSUE TITLE
Navigation and `use:enhance` should apply `autofocus`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#6629]
### Describe the problem

This is arguably a bug, insofar as client-side navigation and `enhance` are supposed to simulate a full page reload as far as possible, but I'm on my phone so no repro will be forthcoming.

In a navigation, we (IIRC) focus the body. In an enhanced form submit, the submit button stays focused.

### Describe the proposed solution

In both cases, we should focus the first element with `autofocus` if such there be. If such there not be, `enhance` should focus the body by default.

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
@Rich-Harris Did you intend for #fda8eb3 to close this issue?
