### ISSUE TITLE
`use:enhance` should work with `<button formaction>`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#6630]
### Describe the problem

This should work...

```html
<form method="POST">
  <button formaction="?/hello" use:enhance>click me</button>
</form>
```

...but it doesn't, because `enhance` assumes its first argument is a `<form>`. The same goes for `<input>` elements with `type="submit"` and `type="image"`.

### Describe the proposed solution

![image](https://user-images.githubusercontent.com/1162160/188821200-652db6aa-10d2-456f-bb8c-60ee6bbee4ef.png)

### Importance

would make my life easier

**Comment by danawoodman** [comment]
Wondering if some documentation around this could be created? Eg:

- Do you need to add `use:enhance` on all `<button formaction="...">`?
- Can you have a default form action set like `<form action="?/foo">` or will you have to only use `formaction` or `action` and not both?
