### ISSUE TITLE
Generated ActionData type from './$types' is always unknown

### ISSUE THREAD

**Issue by harrylaulau** [sveltejs/kit#6631]
### Describe the bug

I tried to migrate my project to the newest sveltekit version but the ActionData type imported from './$types' is always unknown.

I then tried to reproduce the issue by creating a new project from scratch and the result is the same. I edited +page.svelte and added a +page.server.ts as follows.

`+page.svelte`
![CleanShot 2022-09-07 at 09 33 03](https://user-images.githubusercontent.com/32997810/188830921-0f5e116d-ac18-4a0c-9562-1c43b6bcf869.png)

`+page.server.ts`
![CleanShot 2022-09-07 at 09 29 51](https://user-images.githubusercontent.com/32997810/188830198-846ef95f-c360-4372-bee2-972e7ae95851.png)

The error at the script tag complains another error, still I am not sure if that is related.
![CleanShot 2022-09-07 at 09 32 03](https://user-images.githubusercontent.com/32997810/188830723-e81c4163-ea00-4b9e-95aa-f1991c642cd2.png)

### Git Repository
https://github.com/harrylaulau/sveltekittest

### Steps
1. created with:
`npm create svelte@latest test`
Options: skeleton project, typescript, eslint, prttier enabled.
![CleanShot 2022-09-07 at 09 46 21](https://user-images.githubusercontent.com/32997810/188833951-926c3cd4-8ab4-44e8-9bb7-bd33d7af1367.png)

3. Edited Files:
`src/routes/+page.svelte`
```html
<script lang="ts">
	import type { ActionData } from './$types';
	export let form: ActionData;
	$: console.log(form?.success);
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
<form method="POST">
	<button>Log in</button>
</form>
```

`src/routes/+page.server.ts`
```ts
import type { Actions } from './$types';
export const actions: Actions = {
	default: async () => {
		return { success: true };
	}
};

```

### Logs

```shell
console.log successfully output true when the form button is pressed
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.19 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/kit: next => 1.0.0-next.475 
    svelte: ^3.44.0 => 3.50.0 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

### Additional Information

This is from the generated `$types.d.ts` file. Not sure if this screen shot is helpful. 
![CleanShot 2022-09-07 at 09 43 24](https://user-images.githubusercontent.com/32997810/188833213-feeee130-3c0b-4cdd-b534-cb0e690188c7.png)

**Comment by harrylaulau** [comment]
Further testing by adding a if branch in actions.default returning a `invalid()`changes the return type of `actions.default` in generated `$types.d.ts` to `Promise<any>`

`+page.server.ts`
![CleanShot 2022-09-07 at 10 01 51](https://user-images.githubusercontent.com/32997810/188837567-c2ba4aa8-a3ef-47d2-99ce-e3fc79e10a89.png)

Generated `$types.d.ts`
![CleanShot 2022-09-07 at 10 01 30](https://user-images.githubusercontent.com/32997810/188837522-d1860c58-cf25-429f-99e3-b69ebeaee10a.png)

**Comment by mattcroat** [comment]
Yeah, it's not working! 😔

I opened a discussion recently for https://github.com/sveltejs/kit/discussions/6597 which is interesting because it seems it's the same problem but now moved to `ActionData`.

**Comment by jeppech** [comment]
I think it's worth noting, that doing the same thing in a JS project, will work as expected. I've included both TS and a JS sample in #6668.

**Comment by aloker** [comment]
It's there any update on this? Do you need more input or better repos?

**Comment by williamviktorsson** [comment]
Thanks for the fix! The development experience when the types work is amazing 😍
