### ISSUE TITLE
Global Layout on server side, Page on client side. Global layout as shell

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#6636]
### Describe the problem

The beginning is here - https://github.com/sveltejs/kit/discussions/6564

**Story:**

I had an application with SSR, and in it I had a dark mode available through `prefers-color-scheme`.
I tested how it worked, and it worked perfectly.
Later I created another application, and it required SSR to be disabled.
In this application, I also had dark mode available.
At one point, I was testing an item in dark mode, and I saw that the page flashed when I reloaded it in the browser. This surprised me. I wasn't aware of it (or if I was a little, I had forgotten it and didn't associate it).

---

**The reason:**

The imported CSS file `import '../app.css';` works when the whole page is in SSR, but blinks when it is without SSR. (preloads shell - "it renders an empty 'shell' page instead." from the documentation)

This is an inconsistency.
That is, if you want to avoid blinking, you have to use `<link rel="stylesheet" href="%sveltekit.assets%/app.css">` in `app.html`, which is (in e.g. the SvelteKit template) deprecated and replaced with `import '../app.css'`.

### Describe the proposed solution

Global `layout` (and the whole SvelteKit in general), by default works **with** SSR. It would be nice if, when having to apply without SSR, not to disable SSR completely, just in the `page` itself, when the `layout` could still be with SSR.

It is worth flipping, on the SSR as much as possible, if possible.

What if it could be set that the layout is prepared on the server side, and only the page would be rendered on the client side?

The issue is the global `src/router/+layout.svelte`. He is global, attached to each page, just as `app.html` is attached to each page as a fixed base for the page. (Since `(group)`, and I hope it stays that way)

The global `src/router/+layout.svelte` should also be as such a base, ready already on the server side, enabled/disabled under the control of the setting.

---

**Syntax**

The setting could look like this:

```javascript
// src/routes/+layout.js
export const ssrShell = true;
```

Or:

```javascript
// src/routes/+layout.js
export const ssr = "shell"; // layout with SSR, page without SSR
```

Or crazy - when:

```javascript
// src/routes/+layout.js
export const ssr = false;
```

Then **anyway**, it loads the global layout with SSR, and the rest of the layouts and pages without SSR.

---

**How it should work**

Thanks to which the styles, imports, etc., from `src/routes/+layout.js`, would be ready already on the server side, and `+page` would load according without SSR.

It seems to me that only the global layout (`src/routes/+layout.svelte`) should have this option.

The rest of the layouts should work as before, that is, it should not be possible to set `ssr = "shell"` in `src/routes/about/+layout.js` etc.

### Alternatives considered

a. Always only use `<link rel="stylesheet" href="%sveltekit.assets%/app.css">` in `app.html`.
Also in the examples attached from SvelteKit. Whether it is using SSR or not using SSR.

b. "Shell"([described](https://kit.svelte.dev/docs/page-options#ssr) in the documentation), by default matched to dark mode when you turn off SSR. The easiest way - adding style `prefers-color-scheme` with `background-color: black`, to shell SvelteKit. This is supposed to simulate `about:blank` in dark mode.
Because the new tab in the browser, and when loading, is matched to the dark color in the system/browser.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
If you're creating a purely client-rendered application, rendering an empty shell page is exactly what is intended to happen. If you want some styles that don't need JS to run for them to be loaded, you should just put them in `app.html`, because that's what it's there for.

**Comment by lukaszpolowczyk** [comment]
@Conduitry :((
I would like to have all the benefits that SvelteKit has, and not have to use `app.html`.
Putting this code into `app.html`, it's like hacking SvelteKit, not using it normally. :(

This is sad.

For me, the problem is not solved. Definitely.

All these arguments that this is different behavior, unexpected. That there are bound to be sites that will be flashed just because someone would not expect this behavior.
All this you ignore.  :((

**Comment by lukaszpolowczyk** [comment]
@Conduitry Of course that this behavior IS NOT expected. I described it in the Story!

We already had a situation where you thought the user was smarter than he actually could be - https://github.com/sveltejs/svelte/issues/5797#issuecomment-1162544060
And later you went to your senses and did something better.
Why do we have to repeat this?!

I ASSUME that adding this code to `app.html` is not something ok, just like hacking SvelteKit, because SvelteKit has some shortcomings!!!

**Comment by lukaszpolowczyk** [comment]
The simplest solution to the problem (although I haven't tested it much):

```svelte
<!-- src/routes/+layout.svelte -->
<script>
  import '../app.css';
  import { browser } from "$app/environment";
</script>

{#if browser}
  <slot />
{/if}
```

It hadn't occurred to me before.... :D
