### ISSUE TITLE
Export endpoint request type

### ISSUE THREAD

**Issue by arnemolland** [sveltejs/kit#664]
**Is your feature request related to a problem? Please describe.**
I'd like for an endpoint request object to be typed equal to `RequestHandlerResponse`.

**Describe the solution you'd like**
It's pretty straightforward, though I'm not sure about naming. For reference, Next.js has named their equivalent types `NextApiRequest` and `NextApiResponse`.

**Describe alternatives you've considered**
As of now, I'm declaring the type myself.

**How important is this feature to you?**
For direct usage of the `RequestHandler` function, you inherit typings from the function type, but constructing a standalone request object requires custom type declaration which is a pain in comparison with how small of a change it is to export the type.

**Additional context**
An alternative declaration (following current naming):
```typescript
export interface RequestHandlerResponse {
	status?: number;
	headers?: Record<string, string>;
	body?: any;
}

export interface RequestHandlerRequest {
	host: string;
	headers: Headers;
	path: string;
	params: Record<string, string>;
	query: URLSearchParams;
	body: string | Buffer | ReadOnlyFormData;
}

export type RequestHandler = (
	request?: RequestHandlerRequest,
	context?: any
) => RequestHandlerResponse | Promise<RequestHandlerResponse>;
```

**Comment by Rich-Harris** [comment]
Yeah, this makes sense. I'd suggest we keep it simple and just have `Request`, `Response` and `RequestHandler`. These types will likely change if we implement https://github.com/sveltejs/kit/issues/334#issuecomment-806289525 — `context` will become a property of `Request`, and `RequestHandler` will have a single argument — but not in a way that changes the crux of this issue

**Comment by ignatiusmb** [comment]
`RequestHandler` now only have a single argument and its own response type

https://github.com/sveltejs/kit/blob/aed1bd0765852ad573030bda789ec054d68f5073/packages/kit/types/endpoint.d.ts#L21-L27

Which is exposed publicly as `Request` and `EndpointOutput` respectively

https://github.com/sveltejs/kit/blob/aed1bd0765852ad573030bda789ec054d68f5073/packages/kit/types/index.d.ts#L7-L15
