### ISSUE TITLE
Document `*.server.*` and `$lib/server` functionality

### ISSUE THREAD

**Issue by tcc-sejohnson** [sveltejs/kit#6640]
### Describe the problem

I wrote #6422 and the more recent #6623. I suggested some documentation in the first PR, but we weren't sure where to put it. We need to add the latest feature to that documentation and actually add it to the docs.

### Describe the proposed solution

Do the thing.

### Alternatives considered

Scrap SvelteKit and start over

### Importance

i cannot use SvelteKit without it

**Comment by accuser** [comment]
Some documentation for the `$lib/server` functionality should probably be included with [Project Files / src](https://kit.svelte.dev/docs/project-structure#project-files-src) and [Modules / $lib](https://kit.svelte.dev/docs/modules#$lib).

Looking at the current documentation I don't think I'd be sure where the `*.server.*` functionality should sit either.
