### ISSUE TITLE
replace `%sveltekit.message%` with `%sveltekit.error.message%`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#6645]
### Describe the problem

As of https://github.com/sveltejs/kit/pull/6586 we have a standard way of dealing with errors in a SvelteKit app. It would make sense if we respected the `App.PageError` shape in `src/error.html`.

### Describe the proposed solution

Change `%sveltekit.message%` to `%sveltekit.error.message%`. We _could_ include other properties on the `error` object, but there are some caveats here (we can't allow any way for `src/error.html` to blow up during rendering) so for now we should probably just make that change, and worry about surfacing `%sveltekit.error.code%` or whatever as a post-1.0 thing

### Importance

would make my life easier

**Comment by msigwart** [comment]
> worry about surfacing %sveltekit.error.code% or whatever as a post-1.0 thing

Are there plans for this already? Would be great to be able to show some other error props in the `error.html`.
