### ISSUE TITLE
VITEST included

### ISSUE THREAD

**Issue by TranscendentalRide** [sveltejs/kit#6647]
### Describe the problem

Support test-driven development patterns at the unit-test level.

### Describe the proposed solution

It would be great to have VITEST + JSDOM + Svelte-Testing-Library included.

### Importance

would make my life easier

### Additional Information

Every time a new Sveltekit project is started, extra work needs to be done to install some UNIT testing library. Would be nice to have something included.

**Comment by benmccann** [comment]
Closing this in favor of the existing discussion

Also, there's a PR out for this: https://github.com/sveltejs/kit/pull/5708
