### ISSUE TITLE
incomplete build with no error message

### ISSUE THREAD

**Issue by Anyass3** [sveltejs/kit#6653]
### Describe the bug

A strange and interesting bug: an Incomplete build with no error message
The app starts building and it always stops/terminates once it reaches this point in the attachment and it doesn't state any reason.
<img src='https://cdn.discordapp.com/attachments/939868205869072444/1017129847920803850/unknown.png'/>

### Reproduction

.

### System Info

```shell
System:
    OS: Linux 5.18 Fedora Linux 36 (Workstation Edition)
    CPU: (4) x64 AMD PRO A12-8830B R7, 10 COMPUTE CORES 4C+6G
    Memory: 6.14 GB / 15.06 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    npm: 8.3.1 - /usr/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.88 => 1.0.0-next.88 
    @sveltejs/adapter-static: 1.0.0-next.42 => 1.0.0-next.42 
    @sveltejs/kit: 1.0.0-next.476 => 1.0.0-next.476 
    @sveltejs/svelte-scroller: ^2.0.7 => 2.0.7 
    @sveltejs/vite-plugin-svelte: ^1.0.0-next.44 => 1.0.1 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
We need a minimal reproduction.

**Comment by Anyass3** [comment]
Sorry, I could not reproduce it but it was related to the vite config importing from a custom global config. After removing that implementation, it works. I am working on a monorepo with various svelte-kit apps.
