### ISSUE TITLE
Incorrect version in package.template.json

### ISSUE THREAD

**Issue by idleberg** [sveltejs/kit#6657]
### Describe the bug

All `package.template.json` files included in this mono repo currently use version `0.0.1` as an initial value. In my opinion, this is incorrect usage of SemVer. The specification *recommends* starting at `0.1.0`, but doesn't rule out `0.0.0` as being a valid version. However, `0.0.1` would be a patch for `0.0.0`, so it shouldn't be valid as an *initial* version.

I understand everyone rolling eyes over this and let me assure you I don't live to be called nitpicky. Frankly, I don't care too much how people version *their* software. However, in the case of a template file, I think recommendations or best practices should be followed. Don't encourage people to use the wrong versioning in their own projects, even if you don't agree. Use something that doesn't cause conflicts. Ideally, people have this on their radar, but why make it more difficult if it doesn't have to be?

### Reproduction

Take a look at the following template files to find `v0.0.1` in use.

```
packages/create-svelte/templates/default/package.template.json
packages/create-svelte/templates/skeleton/package.template.json
packages/create-svelte/templates/skeletonlib/package.template.json
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 47.71 MB / 32.00 GB
    Shell: 3.5.0 - /usr/local/bin/fish
  Binaries:
    Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox Developer Edition: 104.0
    Safari: 15.6.1
  npmPackages:
    svelte: ^3.48.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

- [SemVer FAQ](https://semver.org/#faq)
- [Is 0.0.1 valid semver?](https://stackoverflow.com/questions/38252708/is-0-0-1-valid-semver)

**Comment by benmccann** [comment]
I didn't put `0.0.1` there, but agree with whoever did and the next answer on the stackoverflow you linked to of:
> There are no rules here and conventions are loose.

This really doesn't matter and anyone who wants to change it can. `0.0.1` seems totally correct and fine to me
