### ISSUE TITLE
`use:enhance` does not properly handle `<button formaction="...">`

### ISSUE THREAD

**Issue by danawoodman** [sveltejs/kit#6660]
### Describe the bug

Adding `use:enhance` to a form like:

```html
<script lang="ts">
	import { enhance } from '$app/forms';
</script>


<form method="POST" action="?/a" use:enhance>
	<button>Submit A</button>
	<button formaction="?/b">Submit B</button>
</form>
```

Always calls `?/a` action. Removing it calls `?/b` when clicking "Submit B".

### Reproduction

https://github.com/danawoodman/sveltekit-formaction-use-enhance-bug

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Apple M2
    Memory: 23.95 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.asdf/installs/nodejs/18.4.0/bin/node
    npm: 8.12.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 105.1.43.89
    Chrome: 105.0.5195.102
    Firefox: 103.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/kit: next => 1.0.0-next.476 
    svelte: ^3.44.0 => 3.50.0 
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking an upgrade

**Comment by PatrickG** [comment]
You need to use the action on the button.

**Comment by danawoodman** [comment]
Yes, I'm aware, but the `use:enhance` isn't handling this as (I think it) should. Instead, perhaps it needs to be changed to add event handlers to any `button` with a `formaction` value. I've gotten around it by doing something like this:

```ts
	async function handle_submit(
		this: HTMLFormElement,
		event: Event
	) {
		const data = new FormData(this);

		const actionType = data.get("actionType");
		const action = !actionType
			? "?/upload"
			: actionType === "publish"
			? "?/publish"
			: "?/approve";

		const response = await fetch(action, {
			method: "POST",
			body: data,
		});
		const result = await response.json();

		await applyAction(result);

		if (result.type === "error") {
			// Handle error...
		}

		if (result.type === "success") {
			// Handle success...
		}
	}
```

And then adding a hidden field for the action type depending on the button I'm showing: `<input type="hidden" name="actionType" value="approve" />`

That said, it feels hacky and I'm wondering if the built in `use:enhance` can do something smarter?

**Comment by danawoodman** [comment]
Weird, I thought I searched for issues. Glad to see https://github.com/sveltejs/kit/issues/6630

**Comment by Rich-Harris** [comment]
@PatrickG aw man, I wish I'd known about `submitter` yesterday! Had no idea it existed 🙈. That's way cleaner (and also handles the unlikely edge case where `<button form={dynamic}>`)

**Comment by danawoodman** [comment]
Thanks @PatrickG for the `submitter` suggestion. I've updated my DIY handler to something like this which is working great:

```ts
async function handle_submit(
  this: HTMLFormElement,
  event: SubmitEvent
): Promise<void> {
  const data = new FormData(this);

  const submitter = event?.submitter as HTMLButtonElement | HTMLFormElement;
  const action = submitter?.formAction ?? this?.action;

  loading = true;

  const response = await fetch(action, { method: "POST", body: data });

  loading = false;

  const result = await response.json();

  if (result.type === "error") {
    // Handle error...
  }

  if (result.type === "success") {
    // Handle success...
  }
}

```
