### ISSUE TITLE
Changeset missing from #6586. Change not in changelog

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6664]
### Describe the problem

The changelog is missing entries about recent changes to error handling and hooks.

### Describe the proposed solution

It would be a good idea to add this to the changelog because they're breaking changes.

### Importance

would make my life easier

**Comment by benmccann** [comment]
Can you link to exactly which changes you're talking about?

**Comment by kevinrenskers** [comment]
For example the new split client and server hooks (https://kit.svelte.dev/docs/hooks) and the new typed PageError stuff (https://kit.svelte.dev/docs/types#app-pageerror).

**Comment by kevinrenskers** [comment]
I guess ultimately it's https://github.com/sveltejs/kit/pull/6586 that is missing from the changelog?
