### ISSUE TITLE
Inconsistent error handling: internal endpoints stringify their error objects

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6671]
### Describe the bug

When throwing an error inside of an internal endpoint, this error object gets stringified as the new error message, which makes it basically impossible to handle errors in a consistent way. See also https://github.com/sveltejs/kit/discussions/6603.

Basically when doing a request to an external endpoint and throwing an error, I can easily handle those errors in my pages, I can just display `err.body.message`. But when wrapping this external request inside an internal endpoint (to set a cookie on success), errors that are thrown are unusable, can't be shown to the user.

### Reproduction

https://github.com/kevinrenskers/sk-error-handling

When pressing the "Make external request" button, you'll see the error `This is not a valid login link. Has it already been used?` appear, as expected. When pressing the button "Make request via internal endpoint", the error `message: This is not a valid login link. Has it already been used? errors: [object Object]` instead appears. The entire error object with all properties is stringified and used as the message.

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 534.30 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71
    @sveltejs/kit: next => 1.0.0-next.477
    svelte: ^3.44.0 => 3.50.0
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking an upgrade

### Additional Information

This is causing serious issues in my website - my login function which calls an external endpoint via an internal one now has horrible error messages shown to the user when something goes wrong.

**Comment by dummdidumm** [comment]
This works as expected. When you make the external API call, there's no SvelteKit involved so the error you throw in api.ts appears as-is in your +page.svelte file. When you make the external API call through a SvelteKit endpoint, the HttpError is handled by the server catch behavior, given out, and then you throw the error a second time. It's because you use `send` two times:
- external: send -> error thrown in send -> done
- internal send -> +server.ts -> send -> error thrown in send -> error catched and thrown in send -> done
-

**Comment by kevinrenskers** [comment]
But how can this work as expected when the behavior to stringify the error object instead of simply rethrowing it is simply weird? How am I supposed to work around this behavior? Yeah send gets used twice. The external call throws the error, the internal call should just pass it on. Instead it modifies the error so it becomes completely unusable.

I'm really not sure how to deal with this behavior and my users are seeing crazy errors that don't make sense and are not usable at all.

**Comment by dummdidumm** [comment]
Again, you are catching your own `throw error` and throwing it again, because you call `postApi` 2 times, once from `postLocal` and once from inside `+server.ts`, which results in this nesting.

**Comment by kevinrenskers** [comment]
Right but why does rethrowing an error result in the entire error object becoming the new message, stringified? That's not me doing that.

I should also add that this used to work just fine in an older version of SvelteKit. Some time after 1.0.0-next.406 this got changed (sorry, can't pinpoint it better than that).

**Comment by kevinrenskers** [comment]
I've simplified the example repro. The server endpoint no longer does a request, all it does it throw:

```
import { error } from "@sveltejs/kit";
import type { RequestHandler } from "@sveltejs/kit";

export const POST: RequestHandler = async ({ request, cookies }) => {
  throw error(400, {
    message: "This is not a valid login link. Has it already been used?",
    errors: { foo: ["Just some dummy data"] },
  });
};
```

And even then, I can't catch the error in a usable format, the error message is still `message: This is not a valid login link. Has it already been used? errors: [object Object]`.

**Comment by kevinrenskers** [comment]
Found the cause of the weird error message format, that was definitely in my code.
