### ISSUE TITLE
Slide Transition not behaving as expected

### ISSUE THREAD

**Issue by bdanoit** [sveltejs/kit#6674]
### Describe the bug

In the example repro, when a new section is opened, the animation for the section that was previously open is delayed until after the initial animation ends. I would expect both items to animate at the same time, but please correct me if I am wrong.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-fpv3ld?file=src%2Froutes%2F%2Bpage.svelte&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/kit: next => 1.0.0-next.476 
    svelte: ^3.46.0 => 3.50.0 
    vite: ^3.1.0 => 3.1.0
```

### Severity

annoyance

**Comment by PatrickG** [comment]
I didn't look into it, but might be related to [this bug](https://github.com/sveltejs/svelte/issues/7828) which has crept in with Svelte 3.50.0.

**Comment by bdanoit** [comment]
> I didn't look into it, but might be related to [this bug](https://github.com/sveltejs/svelte/issues/7828) which has crept in with Svelte 3.50.0.

Yup, this is it.
