### ISSUE TITLE
Dark mode docs

### ISSUE THREAD

**Issue by elliottetzkorn** [sveltejs/kit#6677]
### Describe the problem

The documentation website only offers docs in light mode. This is blinding when you are working late at night.

### Describe the proposed solution

Please implement a dark mode toggle for the svelte kit doc website.

### Importance

would make my life easier

**Comment by Mlocik97** [comment]
I think all pages should have dark mode. Not just docs.

**Comment by Shiinoya** [comment]
@elliottetzkorn , not the solution but a patch meanwhile: I use [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh) and it works wonders for me. It'll automatically have every website in the best dark mode possible, but you can turn it off per site if needed (for those websites that have their own dark mode).

**Comment by STR1234** [comment]
@elliottetzkorn I always use OperaGX when reading the svelte docs or other blinding docs or information pieces that offer only the blinding lightray mode of doom - this browser has a nice dark mode feature for all websites (of course not perfect though :'D)- it works very well for the Svelte Docs in my experience. Just as long as the docs are in blinding mode, this might be a nice workaround - did not try any dark mode extensions though for any preferred browser...might offer the same benefits.

**Comment by delight** [comment]
In OperaGX you still have to activate opera://settings/content/forceDarkMode the result is afaict exactly the same as using any other chrome based browser with chrome://flags/ (which redirects in some browsers e.g. edge://flags/) and set "Auto Dark Mode for Web Contents" : enabled.

**Comment by gg187on** [comment]
Hello, even tho this issue is closed, website shows me in light mode, there is no darkmode "button/switch" or anything, and it doesn't show in dark mode, even tho my system is in dark mode (Ubuntu 20.04., Chrome with GTK4+ theme).

**Comment by dummdidumm** [comment]
We will add a dark mode toggle soon

**Comment by delight** [comment]
> Hello, even tho this issue is closed, website shows me in light mode, there is no darkmode "button/switch" or anything, and it doesn't show in dark mode, even tho my system is in dark mode (Ubuntu 20.04., Chrome with GTK+ theme).

This is no issue of this project ... It's an configuration issue of chrome not picking up the system settings on Ubuntu. You'll have the same problem on other pages not picking up your system dark mode settings automatically. I remember I had to do give chrome some starting parameters to start in dark mode.

Quick Google came up with:  --enable-feautures=WebUIDarkMode --force-dark-mode

**Comment by andylib93** [comment]
Hello, I wanted to report a little bug - I'm not sure if anyone has noticed yet:

When I open the docs on mobile and click the burger menu button, the navigation appears in light mode. At least on my phone and laptop. Perhaps there are some CSS variables not set correctly? I haven't looked into the source code yet.

**Comment by delight** [comment]
> Hello, even tho this issue is closed, website shows me in light mode, there is no darkmode "button/switch" or anything, and it doesn't show in dark mode, even tho my system is in dark mode (Ubuntu 20.04., Chrome with GTK+ theme).

I finally remembered to check on my start parameters of chrome and chromium on my Linux Machine (using latest kde neon as a distro).  

Both have the starting parameters set to:
`--incognito --force-dark-mode %U`
where the first parameter obviously is just my preference.

It works perfectly fine. Like it does when I for example switch into dark mode on my mac.
Firefox seems to work correctly out of the box on my distro, reflecting the desktop settings about the global design seetings (dark mode).

Hopefully that helps. Let me know if that fixed your problem. Would be nice to hear you confirm it. 

If it does not work right away - you might need to scrape the browser setting / config from disk. But that is just a guess.
Good luck with it !
