### ISSUE TITLE
Document available types

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#668]
**Is your feature request related to a problem? Please describe.**
The types are illustrated in the docs inline, but it might be nice to have a central place where they're all visible.

**Describe the solution you'd like**
A new `/docs#types` section.

**How important is this feature to you?**
Nice to have

**Additional context**
Needs to consider https://github.com/sveltejs/kit/issues/647, if we do that

**Comment by benmccann** [comment]
We could probably auto-generate with https://typedoc.org/

**Comment by Rich-Harris** [comment]
please no 🤮 typedoc pages are some of the ugliest, least usable things i encounter as a web developer
