### ISSUE TITLE
Hosting a SPA (adapter-static) in IIS requires a security workaround to allow css files

### ISSUE THREAD

**Issue by gatapia** [sveltejs/kit#6680]
### Describe the bug

The new generated css file names, such as `+layout-7623f1e9.css` causes IIS to block the request with the following error:
```
HTTP Error 404.11 - Not Found
The request filtering module is configured to deny a request that contains a double escape sequence.
```
This can be disabled by setting `allowDoubleEscaping=true` as per this [StackOverflow](https://stackoverflow.com/questions/7739233/double-escape-sequence-inside-a-url-the-request-filtering-module-is-configured).  However, as mentioned in that link, this is opening a security hole.

Could the generated filename omit the `+` prefix? 

### Reproduction

This [repo reproduces the issue](https://github.com/gatapia/svelte_dotnet)

### Logs

```shell
The only relevant error from IIS is:

HTTP Error 404.11 - Not Found
The request filtering module is configured to deny a request that contains a double escape sequence.
```
```


### System Info

```shell
Windows 10, IIS 7
```

### Severity

serious, but I can work around it

**Comment by PatrickG** [comment]
Which SvelteKit version are you using?
There should be no `+` signs in the filenames anymore since @sveltejs/kit@1.0.0-next.450

**Comment by Conduitry** [comment]
There are still `+` signs in the _filenames_, but with the upgrade to Vite 3.1.0, these should now be properly percent encoded when they are referred to in HTML.

However, I can see this project still uses Vite 3.0.9. Does this still happen on the latest version?

**Comment by gatapia** [comment]
Can confirm that upgrading to vite 3.1.0 resolves the issue
