### ISSUE TITLE
Question: Why are actions restricted to form-encoded data only?

### ISSUE THREAD

**Issue by lemmon** [sveltejs/kit#6685]
### Describe the problem

First of all I welcome new Actions structure. I think it is a great idea. I understand using `FormData` (as default) for POST-ing data to the server. However, what bugs me, is restriction that you can ONLY use `FormData`; no `JSON` allowed.

Is there any particular reason that this is so restrictive? Again, I understand why this should be encouraged, but I don't think this should be forced.

I can think of milion instances when POST-ing JSON objects. When you want to quickly hack something; or your app's UI is dependent on JavaScript then you can expect all users having JS enabled; building APIs, and so on. FormData is quite dificult to work with compared to a JSON Object.

### Describe the proposed solution

Quit restricting Actions to FormData only.

### Alternatives considered

Way around it is to submit a FormData object with your JSON serialized as form value:

```js
const formData = new FormData()
formData.append('data', JSON.stringify(data))
```

...then parse the value back on the server side. I don't see any value in this unnecessary step. If someone want's to post JSONs they shouldn't be restricted. If theren's no technical reason to do so.

### Importance

would make my life easier

**Comment by benmccann** [comment]
The forms feature only works with forms. If you want to write a json endpoint use the server files: https://kit.svelte.dev/docs/routing#server
