### ISSUE TITLE
Form `enhance` does not work when `action` points to a different route

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#6695]
### Describe the bug

`enhance` without a callback will not apply its action if the form action references a different route. However, it works when manually calling `applyAction(result)` in the callback.
For example:

```html
// routes/+page.svelte
<form use:enhance method="POST" action="/login"> // this doesn't work
<form use:enhance method="POST"> // this works
```

### Reproduction

https://github.com/s3812497/sveltekit-enhance-bug-2

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 8.07 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 104.0.1
    Firefox Developer Edition: 105.0
    Safari: 16.1
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/kit: next => 1.0.0-next.479 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
It's there by design. The reason is that the progressive enhancement case would work differently to the native case. In the native case you are redirected to that page and the info would be available there. When JS is available this is different, so it might create subtle differences between the modes. It's only the default behavior though, you can modify this yourself by passing your own callback function.

**Comment by s3812497** [comment]
> It's there by design. The reason is that the progressive enhancement case would work differently to the native case. In the native case you are redirected to that page and the info would be available there. When JS is available this is different, so it might create subtle differences between the modes. It's only the default behavior though, you can modify this yourself by passing your own callback function.

Thanks for the clarification! Appreciate it.

Do you think it would be better if it followed the native form behaviour by default? Or maybe just a side note in the docs?
Otherwise, I think this issue can be closed, since it's not a bug.

**Comment by dummdidumm** [comment]
Let's give it the documentation label to signal we can improve on making this clearer

**Comment by Mlocik97** [comment]
Can we somewhat read `redirect` header in response, if is present, and in that case apply `goto(redirect_url)` and in case of it's not present call `goto(form.action)` ? This would make sense doing by default, so it's as close to native forms as possible.

**Comment by danawoodman** [comment]
Does `use:enhance` not work at all if action is different than the current path? I'm trying to do a simple action that throws a `redirect` but it doesn't do anything. 

Is that expected or is it a bug? If it is expected, the documentation doesn't make it clear.
