### ISSUE TITLE
Unable to run generated index.js using node command

### ISSUE THREAD

**Issue by harrisonBarnett** [sveltejs/kit#6698]
### Describe the bug

After building my SvelteKit project, I am unable to run the generated `index.js` using the `node` command. I have tried this on 3 separate projects, one of which was the SvelteKit demo application with zero modifications (linked in reproduction below). The error thrown:

```
node:internal/errors:465
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '__GENERATED__' imported from C:\N\path\to\project\.svelte-kit\build\index.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

I'm aware that this may be a Vite issue, but searching out solutions for Vite with regard to SvelteKit has proven to be a recursive endeavor. To be clear, the applications run fine running `npm run dev` and `npm run preview`. But I would like to be able to simply run the generated application with the `node` command if at all possible. Apologies if this isn't a proper bug, but I have seen zero results for the exact error `Error [ERR_MODULE_NOT_FOUND]: Cannot find package '__GENERATED__' `.

### Reproduction

https://github.com/harrisonBarnett/sveltekit-bug-demo

This is simply the SvelteKit demo application created with `npm create svelte@latest`. After running `npm install`, `npm run build` and `node .svelte-kit/build/index.js`, I receive the previously mentioned errors. 

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 8.48 GB / 15.92 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72
    @sveltejs/kit: next => 1.0.0-next.480
    svelte: ^3.46.0 => 3.50.1
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

### Additional Information

I consider this issue serious, though I could technically run this in development or preview as a stop-gap until I figure out a proper solution.

**Comment by benmccann** [comment]
That file isn't meant to be run. If you want to run with the `node` command you need to use `adapter-node`

**Comment by harrisonBarnett** [comment]
> That file isn't meant to be run. If you want to run with the `node` command you need to use `adapter-node`

Ah! Apologies, I got serious tunnel vision banging up against this over the last day or so. Thank you!
