### ISSUE TITLE
SyntaxError: Unexpected token '=' on > iOS 15 in-app browsers UI/WKWebView

### ISSUE THREAD

**Issue by fejiroofficial** [sveltejs/kit#6705]
### Describe the bug

Running the Svelte Kit project on an iPhone running >iOS 15, we noticed this syntax error on Sentry when the project is visited from an in-app browser on Facebook or TikTok.

`[Error] SyntaxError: Unexpected token '='`

### Reproduction

Unfortunately, I cannot replicate it, but should anyone be aware of this or how best to tackle this, I would appreciate it.

### Logs

```shell
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <style>
      html {
```

### System Info

```shell
System:
    iOS: 15.6.1
  Binaries:
    Node: v16.17.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  npm Packages:
    @sveltejs/adapter-netlify: 1.0.0-next.44,
    @sveltejs/kit: npm:@tal500/kit@1.0.0-next.445-legacy-builds-3 
    svelte: npm:@tal500/svelte@3.49.0-repo-advanced-1
    @vitejs/plugin-legacy: 2.0.1,

Browser: Mobile Safari UI/WKWebView
```

### Severity

annoyance

### Additional Information

I am currently using vite legacy plugin with an ongoing fix found here [PR](https://github.com/sveltejs/kit/pull/6265). This doesn’t seem to solve the above issue for me.

**Comment by Tal500** [comment]
Few questions that may be helpful for tracing:
1. Does it happen when the page immediately loaded, or only after some time/interactions?
2. Can you share us a simple code repository which reproduces the issue on these devices? Or even better - does it happen on the simple demo of SvelteKit, created by `npm create svelte@latest my-app`?
3. Can you try to "click" or something else, on the message you see `[Error] SyntaxError: Unexpected token '='`, ususally when clicking or opening it, the browser gives more information (like stack trace).

**Comment by benmccann** [comment]
Closing as this can't be replicated and there was no response to any of the questions
