### ISSUE TITLE
Github Project Website

### ISSUE THREAD

**Issue by techniq** [sveltejs/kit#671]
The github project url currently points to https://kit-sveltejs1.vercel.app/ (an example site)

![image](https://user-images.githubusercontent.com/177476/112477580-8b0dd280-8d49-11eb-9ed3-7ce9d997b55b.png)

It seems like it should point to 
- https://kit.svelte.dev/

**Comment by benmccann** [comment]
Fixed. Thanks!

**Comment by techniq** [comment]
Thank you :).  Appreciate all you do.
