### ISSUE TITLE
KIT changelog

### ISSUE THREAD

**Issue by Renkas** [sveltejs/kit#6717]
### Describe the problem

It seems Github UI is not able to render CHANGELOG anymore: https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

I'm getting a message: `This blob took too long to generate.`

### Describe the proposed solution

Maybe this changelog should be split up so it would still be easy to keep track of the changes?

Or maybe render this in the Kit documentation?

### Importance

nice to have

**Comment by Mlocik97** [comment]
You can still see changelog in releases https://github.com/sveltejs/kit/releases

**Comment by Renkas** [comment]
> You can still see changelog in releases https://github.com/sveltejs/kit/releases

thanks - forgot about that. I was used to see the CHANGELOG directly

**Comment by frederikhors** [comment]
![image](https://user-images.githubusercontent.com/41120635/189487584-5a5246d6-8251-4d0d-aab2-efeb9b83e4d0.png)

**Comment by frederikhors** [comment]
> You can still see changelog in releases https://github.com/sveltejs/kit/releases

I would like to read the Kit one only.

**Comment by Mlocik97** [comment]
https://github.com/sveltejs/kit/releases?q=%40sveltejs%2Fkit%40&expanded=true

kit only...

**Comment by frederikhors** [comment]
> https://github.com/sveltejs/kit/releases?q=%40sveltejs%2Fkit%40&expanded=true
> 
> kit only...

Thanks! I didn't see the search input! 😄

**Comment by Mlocik97** [comment]
You have 4 eyes, and don't see? :eyeglasses:

**Comment by Conduitry** [comment]
This appears to be a recent change in GitHub where some threshold was suddenly lowered. We should wait a few days to see whether enough people yell at them for them to revert it before we spend any time figuring out how we want to split the changelog into smaller files.

**Comment by GrygrFlzr** [comment]
Closing for now - seems like GitHub has reverted the change and the changelog markdown renders again.
