### ISSUE TITLE
named props from load

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/kit#6721]
### Describe the problem

Today we have that weird stuff:

```js
/** @type {import('./$types').PageData} */
export let data;
```

Sometimes my data holds something that are not data... (like stringified regex, or even more specific things that in some sense is weird to call "data")... and I find it weird to have it in data.

There is also issue that `data` is object and not primitive type, and so sometimes if you need to do some rare-case specific things, like flushing variable, mutating stuff, etc, you want only specific part react to change of variable, but as whole data change, it can affect other parts. Or sometimes you want modify that object to hold some accessors and callable functions.

### Describe the proposed solution

Inspired by form actions, what about having default prop (data) and named props (like in old SvelteKit)?

In `+page.server.js` we could either return default Response:

```js
return {
    default: () => new Response();
}
```

or just:

```js
return new Response()
```

as it is now... but we could do also:

```js
return {
    a: () => new Response(),
    b: () => new Response();
}
```

and then in page have:

```js
export let a;
export let b;
```

### Alternatives considered

let it be as is. Or find at least better name for that variable.

### Importance

nice to have

**Comment by david-plugge** [comment]
You can always return an object:
```ts
return {
  myRegex: ... 
} 

// +page.svelte
export let data;
$: myRegex = data.regex;
// or if you have more named props
$: ({ a, b} = data);
```

**Comment by Conduitry** [comment]
This was discussed at length in the routing / data loading issue. The syntax proposed in this issue provides no additional expressive power for its additional complications. We want a single `data` value that is an object so that it can be merged across multiple `load` functions in the chain of layouts and the current page.
