### ISSUE TITLE
Page/layout load functions running twice on initial page load

### ISSUE THREAD

**Issue by pilcrowOnPaper** [sveltejs/kit#6728]
### Describe the bug

This is either a "feature" request or an issue with the docs.

On initial page load (server-side navigation), page and layout load functions run once during SSR (server) and once before hydration. I'm sure this is intended behavior but I don't see why it is. This blocks the hydration process, and if load functions can return different results, the page will look/act different before and after hydration. Initial page load are part of server side navigation and not client side navigation, so one would think that load functions will only run once in the server and reuse that the hydration process in the client. The result of server load functions are sent to the browser inside `hydrate.data` so I don't see why we can't do the same for normal load functions as well.

If there's a reason to keep this behavior, it would be great if the docs explained this more clearly. Right now it states *where* each load functions run but not *when*.

### Reproduction

none.

### Logs

```shell
none.
```

### System Info

```shell
none.
```

### Severity

serious, but I can work around it

### Additional Information

none.

**Comment by pooledge** [comment]
I am sorry, _now_ this is a bit confusing.

Current documentation states:
> during hydration, the response will be read from the HTML, guaranteeing consistency and preventing an additional network request

So, how do I debug a post-405 app to actually prevent this network request?

> This is intended behaviour

Or does this mean it is a lost battle anyway? Isn't it primarily a developer's task to ensure this consistency instead of SK kinda handicapping everyone with another hundreds ms.

What do I miss? Thanks.

**Comment by pooledge** [comment]
Thank you for clarification, Simon!

Regarding debugging, I came here solely because, despite using `fetch` provided by `load`, I cannot get rid of a browser request and I surely don't want to have a `+page.server.js`

**Comment by pooledge** [comment]
Now, that I _know_ I can prevent the duplicate request, I was able to narrow it down to the fact, that it occurs if endpoint URL is absolute, e.g. `http://localhost:3000/api/v1/somedata` instead of `/api/v1/somedata`

Since the only mention is that
> it can make relative requests on the server

Maybe worth mentioning in docs or did I miss it?

**Comment by llui85** [comment]
What would be the best way to ensure that the load function only runs on the server once, _if_ it can be guaranteed that the data can be safely serialized? I'm struggling to find a way to check if the page has been hydrated - is there a lifecycle function I can hook into?

To be clear, I'm trying to make one request on the server **only** if a route is being initially loaded, but on the client-side if that route is navigated to.

**Comment by niaher** [comment]
I am facing the exactly same problem. The following code results in 2 HTTP requests - one from the server and one from the browser. Based on the docs I understood that the browser request shouldn't happen?

```ts
/** @type {import('@sveltejs/kit').Load} */
export async function load({ fetch }) {
    var x = await fetch('http://localhost:3000/api');
    console.log(x);
}
```

**Comment by dummdidumm** [comment]
Closing as the docs address this now
