### ISSUE TITLE
Provide the ability to defer the execution of parent in a page load function

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#6729]
### Describe the problem

Imagine a very ordinary scenario in which you're retrieving user information in your root layout's `load` function (previously done with `getSession`):

`routes/+layout.ts`:
```ts
export const load: PageLoad = async ({ fetch }) => {
  const user = await fetch('/getUserInfo');
  return { user };
});
```
In the load function of some page, you might need to do something that affects the user state, which means it would _then_ require updating the user info. Another way of thinking about this would be that you want to first do something and only THEN retrieve the user info. This is currently not possible:

`routes/sign-out/+page.ts`:
```ts
export const load: PageLoad = async ({ fetch }) => {
  const success = fetch('signOut');
  return { success }; // In the corresponding `+page.svelte`, now `$page.data.user` would likely be out-of-date, we need to refresh it somehow because we did something that affected it.
});
```
(Now, a sign out page may not be the best example because you could have an endpoint that does the same thing but it was the simplest example, there are other more realistic instances such as a page that a user gets redirected to after a payment transcation, etc.)

### Describe the proposed solution

Introduce some sort of a construct that allows page load functions to instruct SvelteKit that the execution of the parent load function(s) should be initiated after the execution of the current one.
Perhaps something like:
```ts
export const load: PageLoad = async ({ fetch, parent }) => {
  parent.defer();
  const success = fetch('signOut');
  return { success };
});
```
Or:
```ts
export const parentDefer: boolean = true;
export const load: PageLoad = async ({ fetch }) => { // no `parent` here as part of the input
  const success = fetch('signOut');
  return { success };
});
```
The API doesn't have to look like this and is open to discussion, the underlying idea here is what matters: The ability to reverse the execution flow of a page load function and its parent. This would be very, very useful in scenarios where the page load does something that causes the data that the parent retrieves to become out-of-date.

### Importance

would make my life easier

**Comment by PatrickG** [comment]
AFAIK the intended approach is:
```js
// routes/+layout.js
export const load = () => {
  return {
    user: { someData: 1 }
  };
};
```

```js
// routes/whatever/+page.js
export const load = async ({ parent }) => {
  const { user } = await parent();
  return {
    user: { ...user, changedData: 2 }
  }
};
```

**Comment by Conduitry** [comment]
If the child page/layout requires that it do something before some other data is fetched, it should just do both of them, in the required order. Or, if there's only a part of the data that would otherwise be coming from a parent that should be overridden, the `load` function can override just that part.

This doesn't seem like something that needs a special syntax. The logout example doesn't feel like how you would want to implement logout anyway. Logging out should probably either be a form action, or - if for some reason if needs to be a GET to a page - that page should redirect to some post-logout page.

**Comment by aradalvand** [comment]
@Conduitry Would've made more sense to give me the opportunity to respond before closing the issue.

> If the child page/layout requires that it do something before some other data is fetched, it should just do both of them, in the required order. Or, if there's only a part of the data that would otherwise be coming from a parent that should be overridden, the load function can override just that part.

That's not possible, because then the overridden data property will revert back to the parent value once the user navigates to another page, that's not what's intended here.

> The logout example doesn't feel like how you would want to implement logout anyway. Logging out should probably either be a form action, or - if for some reason if needs to be a GET to a page - that page should redirect to some post-logout page.

I explicitly pointed out that the sign out example wasn't the best but the simplest, and also hinted at a better example, namely the page that the user gets redirected to after a payment transaction is complete.

**Comment by aradalvand** [comment]
Can you please reconsider this?
