### ISSUE TITLE
Supabase works with Vite but not SvelteKit dev mode

### ISSUE THREAD

**Issue by nathanlindsay** [sveltejs/kit#673]
**Describe the bug**

Importing [Supabases's client](https://supabase.io/docs/reference/javascript/supabase-client) and refreshing the page shows an error that always looks something like...
```
500
ENOENT: no such file or directory, open '[project_folder]/node_modules/@supabase/supabase-js/src/index.ts'

Error: ENOENT: no such file or directory, open '[project_folder]/node_modules/@supabase/supabase-js/src/index.ts'
```

Building and running (`npm run build` `npm run start`) works fine, and the client can be used.

Have tested with a normal Vite Svelte app (`npm init @vitejs/app`) and that works fine.

**To Reproduce**

```bash
npm init svelte@next
npm install
npm install --save @supabase/supabase-js
```

```javascript
// index.svelte
import { createClient } from '@supabase/supabase-js'
```

[Reproducible repo](https://github.com/nathanlindsay/sveltekit-supabase-bug)

**Information about your SvelteKit Installation:**

```bash
npx: installed 1 in 1.117s

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 939.37 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.59 
    svelte: ^3.29.0 => 3.35.0
```

Chrome

static

**Severity**

I'm probably doing something stupid here, so sorry if this is a waste of your time. But we want to build a simple-ish web app using SvelteKit and Supabase and this is stopping us.

**Comment by extraordinaire** [comment]
This happens when the source map for supabase-js is loaded, not sure how to fix it, but it's from here

```
node_modules/@supabase/supabase-js/dist/module/index.js.map
```

**Comment by benmccann** [comment]
Does it work if you install it as a `devDependency`? https://github.com/supabase/supabase-js/issues/89#issuecomment-809385143

**Comment by nathanlindsay** [comment]
I've just tested and yes it does work...

Though I'm so certain that I tried this before when trying to figure out the problem and it didn't... Maybe Supabase or SvelteKit was updated between my messing about and creating this issue. Either that or I'm losing my mind. Or both.

Thanks for looking into this!

**Comment by benmccann** [comment]
I think the `devDependency` trick will only work with `adapter-node` and `adapter-static`

If you're using another adapter you will need the source map issue to be fixed https://github.com/supabase/supabase-js/issues/153

**Comment by ixxie** [comment]
https://github.com/supabase/supabase-js/issues/153 was resolved but now there is also https://github.com/supabase/supabase-js/issues/155
