### ISSUE TITLE
Throwing an Error inside hooks / handle()

### ISSUE THREAD

**Issue by Beiri22** [sveltejs/kit#6738]
### Describe the bug

Throwing an error() inside the handle hook does not trigger the +error page. I would expect to see the same behaviour as throwing an expected error from a load function.

### Reproduction

```
import { error, type Handle } from  "@sveltejs/kit";

export const handle: Handle = async function ({ event, resolve })
{
    // Check auth and may throw error.
    throw error(400, "TEST");
    // otherwise continue normally
}
```

### Logs

results in error message 

```shell
Error: {"status":400,"body":{"message":"TEST"}}
    at coalesce_to_error (file:///xxx/.svelte-kit/output/server/index.js:226:73)
    at respond (file:///xxx/.svelte-kit/output/server/index.js:1964:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///xxx/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:145:5
```

but does not trigger the +error-page.

### System Info

```shell
System:
    OS: Linux 5.19 Manjaro Linux
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 25.74 GB / 31.27 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.8.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.1 - /usr/bin/npm
  Browsers:
    Chromium: 105.0.5195.102
    Firefox: 104.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/adapter-node: ^1.0.0-next.79 => 1.0.0-next.89 
    @sveltejs/kit: next => 1.0.0-next.480 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3 => 3.1.0
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
I'd say this is the intended behavior, but it should probably be made explicit in the docs.

**Comment by Beiri22** [comment]
So, then. How would i trigger an +error page programmatically within the handler?

**Comment by Rich-Harris** [comment]
You can't. Can you describe why you want to?

**Comment by Beiri22** [comment]
@Rich-Harris The Applikation is behind a reverse proxy that does some shibboleth authentication. As only authenticated users shall access the application, I wanted to use the handler as global location for checking the auth. I thought that throwing an expected error() would work the same way as on pages - but it does not. I just wanted my default error page for  unauthenticated users.

**Comment by izznatsir** [comment]
Maybe you could use a root +layout.server.js

**Comment by Rich-Harris** [comment]
Yes, a `+layout.server.js` is the way to go here. Though in order for the `+error` page to render, the layout 'above' it can't throw the error, so you would need to use this pattern, using a [layout group](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group):

```bash
src/routes/
├ (authed)/
│ ├ [your app]
│ ├ +layout.js         # do the auth check in `load` here
│ └ +layout.svelte
├ +layout.svelte       # don't throw an error in this layout
└ +error.svelte
```

**Comment by Beiri22** [comment]
I will try that, thanks @izznatsir @Rich-Harris
