### ISSUE TITLE
Can't set cookies for Response.redirect()

### ISSUE THREAD

**Issue by infusion** [sveltejs/kit#6749]
### Describe the bug

When trying to set cookies in a +server.js file, I get a "immutable" error when the cookie is set for a redirect

### Reproduction

Does not work:

```js
export async function GET({ cookies }) {

    cookies.set("foo", "bar")

    return Response.redirect("http://localhost:3000/", 302);
}
```

Does work:

```js
export async function GET({ cookies }) {

    cookies.set("foo", "bar")

    return new Response("test");
}
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 791.16 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.4
```

### Severity

blocking an upgrade

**Comment by cdcarson** [comment]
`Response` is a [built-in javascript interface](https://developer.mozilla.org/en-US/docs/Web/API/Response).  It doesn't have a static `redirect` method as you have in your first example. Your second example works, but to redirect, try this...

```js
export async function GET({ cookies }) {
  cookies.set("foo", "bar");
  return new Response(null, {
     status: 302,
     headers: new Headers({ Location: `/'})
  })
}
```

Above uses pure javascript. I believe you can shorten it using the SvelteKit `redirect` helper...
```js
export async function GET({ cookies }) {
  cookies.set("foo", "bar");
  throw redirect(302, '/');
}
```

**Comment by Conduitry** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect There is a static `Response.redirect`. It does sound like there's a bug here, but it's a low priority one, as there are other ways of doing this.

**Comment by cdcarson** [comment]
Wow, didn't know that. Sorry about that.

**Comment by Rich-Harris** [comment]
This isn't a SvelteKit bug — in fact it's not a bug at all, it's how `Response.redirect(...)` is specced. Try it in your browser:

```js
res = Response.redirect('https://example.com', 301)
res.headers.set('x-foo', 'bar')
```

The solution is to construct the response yourself and not use `Response.redirect(...)`.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1162160/189767586-dd0885ed-fb14-42ac-b53a-149c3fbe4078.png">

**Comment by homerjam** [comment]
I'm having a similar issue. It's difficult to reproduce as it seems to happen on Vercel only, usually after the site has been deployed/visited a few times - something to do with keeping the function warm?

Here's the log:

```
2022-10-03T13:36:03.691Z	de73af4e-b112-4c1f-b13c-f495164cd037	ERROR	TypeError: immutable
    at Headers.append (/var/task/node_modules/.pnpm/undici@5.10.0/node_modules/undici/lib/fetch/headers.js:227:13)
    at add_cookies_to_headers (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/index.js:440:13)
    at file:///var/task/packages/continua-frontend/.svelte-kit/output/server/index.js:2436:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handle (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/chunks/hooks.server.js:9:20)
    at async respond (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/index.js:2427:22)
    at async fetch (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/index.js:1010:21)
    at async fetcher (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/index.js:943:22)
    at async fetchMetadata (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/chunks/metadata.js:11:27)
    at async load (file:///var/task/packages/continua-frontend/.svelte-kit/output/server/entries/pages/_layout.js:4:3)
```

Here's `hooks.server.js`:

```js
import { nanoid } from 'nanoid';
import dayjs from 'dayjs';

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
	const sessionId = event.cookies.get('sessionId') || nanoid();

	event.cookies.set('sessionId', sessionId, {
		maxAge: dayjs().diff(dayjs().subtract(1, 'year'), 'seconds'),
	});

	event.locals.sessionId = sessionId;

	const response = await resolve(event);

	return response;
}

```

**Comment by ximus** [comment]
@homerjam pretty sure you get that error because `event.cookies` is request cookies, which should be immutable as they are defined by the request that was received and nothing should change that.

If what you are trying to do is set response headers, then I think you want to move your `set` to after the `resolve()` and use `response.headers.set`.

**Comment by homerjam** [comment]
@ximus if I understand correctly `event.cookies` is actually a get/set interface https://kit.svelte.dev/docs/types#sveltejs-kit-requestevent
