### ISSUE TITLE
External api called twice on SSR when app is served behind reverse proxy

### ISSUE THREAD

**Issue by ambiguous48** [sveltejs/kit#6752]
### Describe the bug

I have an app served behind a reverse proxy. Any request where the pathname starts with `/api` is routed to a nestjs server. Everything else is routed to a sveltekit app.

After upgrading from `1.0.0-next.467` to `1.0.0-next.480`, requests to external api's are executed twice on SSR, failing to take advantage of the included serialized response in the html.

### Reproduction

Example:
- `mysite.com/api` - nestjs server
- `mysite.com` - sveltekit app

```ts
// src/routes/random-dog/+page.ts
export const load({ fetch }) {
    const res = await fetch(`https://mysite.com/api/dogs/1`)
    const dog = await res.json()
    return { dog }
}
```

On a visit to `https://mysite.com/random-dog`:

First, the response will be serialized into the server rendered html using a _relative_ url like so: 
`script[data-sveltekit-fetched][data-url="/api/dogs/1"]`

Afterwards however, [`initial_fetch`]( https://github.com/sveltejs/kit/blob/b68f242806047a3430f79375926c88c3abda7ba1/packages/kit/src/runtime/client/fetcher.js#L78 ) function, which determines whether or not to refetch the resource on the browser, looks for the serialized response using an _absolute_ url:
`script[data-sveltekit-fetched][data-url="https://mysite.com/api/dogs/1"]`

Since this yields no results, the resource is refeteched again client-side.

### System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 10.26 GB / 31.13 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.9.0 - ~/.local/share/pnpm/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 8.19.1 - ~/.local/share/pnpm/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 103.0
```

### Severity

serious, but I can work around it

### Additional Information

Possible workarounds:

1. Proxy all calls through a sveltekit endpoint. This does sound enticing, but I haven't tried it yet. Are there any reasons not to take this approach in a production app? Performance, security, etc?

2. I could use `transformPageChunk` to manually convert the url back to an absolute one, but I haven't tried it yet and I'm not familiar with the codebase enough to know whether or not this will introduce any bugs, etc.

3. Serve the api on a different origin. I'd love nothing more. But doing so causes introduces a significant performance hit caused by preflight requests.

**Comment by ambiguous48** [comment]
> make relative fetch('/api/whatever') calls in my load functions

This has fixed the issue for me. For server-side calls, I used `handleFetch` to replace `https://mysite.com/api` with `http://local-url:8080`, using the supplied `fetch` parameter. Now, `initial_fetch` searches for the correct script url `script[data-sveltekit-fetched][data-url="/api/dogs/1"]`, allowing the serialized response to be reused in the browser.

Thank you!

**Comment by squelix** [comment]
I think this would be great without writing `handleFetch`. It should redirect automatically  to the host on the browser and on the server. Don't you think ?
