### ISSUE TITLE
A way to break out of the default layout without using: (main)

### ISSUE THREAD

**Issue by yekta** [sveltejs/kit#6753]
### Describe the problem

I've looked at the docs but I couldn't find a way to break out of the default layout without having an extra `(main)` layout. This seems weird to me since especially with smaller projects I very regularly come by this problem.

Most routes follow the default layout, there is a couple that needs to break out of it. Even if there is one that needs to break out, I need to create a `(main)` for all the others that follow the default, which not only introduces 1 extra depth in my folder structure but also makes `+error.svelte` not follow the default layout (since my default is now `(main)` and I can't put `+error.svelte` in that folder.

### Describe the proposed solution

To be able to break out of the default layout without the need to create an extra `(main)` layout to then break out of it.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
The current layout model was discussed and litigated at length, with the goal of making just about anything possible without too much complexity in the mental model for how layouts work. If you don't like `(main)`, another thing you can do is look at `$page.routeId` in your layout and render different content depending on that value. We're not going to add a third way of dealing with this specific case. The lack of a single root layout that was used for all pages was also the source of a number of bugs and a good deal of confusion.
