### ISSUE TITLE
Integrate AMP Optimizer into AMP mode

### ISSUE THREAD

**Issue by sebastianbenz** [sveltejs/kit#676]
Thanks for adding AMP support to Svelte Kit (...and I'm sorry for any pain that might've caused). 

**Is your feature request related to a problem? Please describe.**

Un-cached AMP performance is only good if using [AMP Optimizer](https://amp.dev/documentation/guides-and-tutorials/optimize-and-measure/amp-optimizer-guide/node-amp-optimizer/?format=websites) due to boilerplate css and render-blocking JS. AMP Optimizer also enables more advanced features such as shipping AMP Runtime scripts using a module/nomodule approach.

**Describe the solution you'd like**
After rendering the AMP HTML document we should pass it through AMP Optimizer. This should also make the rest of the implementation easier as AMP Optimizer will automatically add any missing AMP specific tags. There's also the possibility to inject CSS as part of the optimization step (not sure if that's of any help).

I'm happy to help with the integration.

**Describe alternatives you've considered**
There's not really an alternative.

**How important is this feature to you?**
This is super important for the AMP team, as we want to make sure that AMP pages perform good on origin.

**Comment by Rich-Harris** [comment]
I've looked into this a bit and to be honest I'm not sure it's something that we should put inside SvelteKit itself. The optimizer is a very large package  - literally ten times larger on disk than SvelteKit itself — which is something we want to be conscious of (as it affects things like CI install time). 

Beyond that, it adds some very significant overhead to SSR. Excluding time spent waiting for data to load over the network, it increases render time by orders of magnitude. While that might be acceptable for cases where pages are prerendered and/or cached, I don't feel comfortable making that choice on behalf of users.

I think the right approach is for people who want to use the AMP optimizer to add it themselves by intercepting the request in [`handle`](https://kit.svelte.dev/docs#hooks-handle):

```js
import AmpOptimizer from '@ampproject/toolbox-optimizer';

const amp = AmpOptimizer.create();

export async function handle(request, render) {
  const response = await render(request);

  if (response.headers['content-type'] === 'text/html') {
    const body = await amp.transformHtml(response.body);

    return {
      ...response,
      body
    };
  }

  return response;
}
```

**Comment by sebastianbenz** [comment]
Thanks a lot for the feedback - super helpful! Few comments:

**re: bundle size** 

Yup, totally understand this. Problem is that terser, css-nano, etc blow up the bundle size. You wouldn't want to run these in your critical path anyway. More about this in the next comment.

**re: execution time** 

There are two problems here: 

1) network requests in critical path
2) execution time

The network requests are hard to avoid as they are needed to fetch the latest runtime CSS and runtime version. I've considered shipping these with optimizer, but this would mean that the AMP Optimizer dependency needs to be updated every two weeks with every AMP release, which is not ideal either. However, the responses are cached, so they should only be fetched once. I wouldn't consider this a critical problem. 

The execution time varies greatly based on the optimizer configuration, e.g. a minimal configuration takes only ~6ms on my machine for the amp.dev homepage vs ~150ms using the default configuration (see [here](https://github.com/ampproject/amp-toolbox/pull/1180)). The problem here are again terser, css-nano and postcss. If using the minimal config, the additional execution time is a good trade off considering that LCP improves significantly for optimised AMP documents (up to several seconds on slow connections).

**Proposal**

My proposal would be:

1. I'll provide a runtime config for optimizer otimzing

**Comment by Rich-Harris** [comment]
closing this, as it should be solved in userland, not the framework
