### ISSUE TITLE
flags for npm create svelte@latest

### ISSUE THREAD

**Issue by pjebs** [sveltejs/kit#6765]
### Describe the problem

Documentation: `npm create svelte@latest` asks 5 questions:'

1. Template type
2. TS support
3. ESLint
4. Prettier
5. Playwright

I am trying to run the command from an application.
The documentation doesn't mention if there are CLI flags I can use to bypass human intervention questions.
`-f and -y` has been disabled.

### Describe the proposed solution

Add flags to the create command.

### Importance

i cannot use SvelteKit without it

**Comment by pjebs** [comment]
If it's not possible to add flags to `npm create svelte@latest`, is there someother way I can obtain the template project (automated)? Perhaps a git repo somewhere for:

```
Template=skeleton
TS=yes
ESLint=yes
Prettier=yes
Playwrite=yes
```

?

**Comment by GrygrFlzr** [comment]
Previous relevant issues: #1231, #2348, #2542

> If we make this more programmatic, I'm concerned about that implying an API that we won't want to stick with. E.g., if we add a new question that someone hasn't yet added an option for in their script, is this a breaking change because running `create-svelte` now expects user input and won't just run automatically. (The alternative would be to make it explicitly fail if some but not all options were specified on the command line, which would also be a breaking change.) If this tool always requires human interaction, we don't need to worry about having an API because we can always assume a human is reading the interactive prompts.

**Comment by pjebs** [comment]
Where is the project files located? Perhaps I can just clone it?

**Comment by pjebs** [comment]
I guess this is what I was looking for: https://github.com/sveltejs/kit/issues/2348#issuecomment-913047793
