### ISSUE TITLE
Nonce cannot be obtained in the component

### ISSUE THREAD

**Issue by rizusss912** [sveltejs/kit#6768]
### Describe the problem

есть случаи, когда нужно инлайнить код в теге <script>. (отправка статистики, логгирование ошибок). Хочется это делать в компоненте рядом с инициализацией. Но, с CSP нужно получить nonce для этого.

### Describe the proposed solution

get nonce in events or event.request

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
there are cases when you need to inline the code in the <script> tag. (sending statistics, error logging). It would be desirable to do it in a component near to initialization. But, with CSP you need to get a nonce for this.

(translated)

**Comment by tcc-sejohnson** [comment]
OP, please provide a complete description of what functionality is missing, preferably with a repository illustrating what you're trying to do. SvelteKit currently supports CSP through `config.kit` -- check the docs and search for CSP. 

Also, if you don't know English well enough to feel confident posting in it, please just run your comments through Google Translate. Almost everyone here speaks English; very few (none?) speak Russian.

**Comment by tcc-sejohnson** [comment]
Closing for no response for now. OP, if you still need help, please check out the Discord -- and if you have a feature request, please fill out the full Feature Request template.

Thanks!
