### ISSUE TITLE
Custom error page isn't shown

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6781]
### Describe the bug

On the root route I have a custom `+error.svelte` page, and a `+layout.ts` file in which I throw an error. Since I have a custom error page on the same level, I would expect this page to be rendered. Instead I get SvelteKit's built-in error page.

The docs say this:

> If an error occurs during load, SvelteKit will render a default error page. You can customise this error page on a per-route basis by adding an +error.svelte file

I think that is exactly what I am doing? An error is thrown during `load`, and I have a `+error.svelte` file. 

### Reproduction

https://github.com/kevinrenskers/sk-error-page

``` typescript
// /src/routes/+layout.ts
import { error } from "@sveltejs/kit";
import type { LayoutLoad } from "./$types";

export const load: LayoutLoad = async () => {
  throw error(401, "Invalid token.");
};
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 490.47 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.73
    @sveltejs/kit: next => 1.0.0-next.481
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.0
```

**Comment by Conduitry** [comment]
Your error is being thrown by your root layout, so SvelteKit can't even render that in this case. We should make the docs more precise here, which I see Rich is doing in a PR that appeared while I typed this comment.

**Comment by Rich-Harris** [comment]
Indeed, was just about to post the following

----

This is expected behaviour. In this scenario...

```svelte
<RootLayout>
  <RootError>
</RootLayout>
```

...if `src/routes/+layout.ts` throws an error during `load`, we can't render `<RootLayout>`. 

Opened #6782 to spell this out a bit more

**Comment by kevinrenskers** [comment]
Ok, that makes sense.
