### ISSUE TITLE
Unexpected errors are always rendered in the default error page as 500 Internal Error

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6783]
### Describe the bug

If I throw an "expected" error from my root `+layout.ts` file, it is rendered with the default error page, showing the status code and the message:

```
import { error } from "@sveltejs/kit";
import type { LayoutLoad } from "./$types";

export const load: LayoutLoad = async () => {
  throw error(401, "Invalid token.");
};
```

But this error won't make it into the `handleError` hook, since it's an expected error. But if I turn it into an "unexpected" error like so:

```
import type { LayoutLoad } from "./$types";

export const load: LayoutLoad = async () => {
  throw { status: 401, message: "Invalid token!" };
};
```

Then while the error does make it into the `handleError` hook, the error page now shows status 500 and the message is "Internal Error".

Can I throw an error of a certain "shape" so that it's "unexpected" but still rendered with the proper code and message?

### Reproduction

https://github.com/kevinrenskers/sk-error-page

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 434.91 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.73
    @sveltejs/kit: next => 1.0.0-next.481
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.0
```

### Severity

annoyance

**Comment by kevinrenskers** [comment]
Related: is there any information on how to create the custom static error.html page, so that it can render the error instead of just being a literal static html page?

**Comment by Conduitry** [comment]
As described in https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror you can use the return value of that to control what's exposed to the user for an expected error.

The replacements available to you in `error.html` are described in https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror

**Comment by kevinrenskers** [comment]
> The replacements available to you in `error.html` are described in https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror

Is that link correct? I don't see anything about `error.html` there.

**Comment by Conduitry** [comment]
Sorry, I pasted the same link twice. `error.html` is described at https://kit.svelte.dev/docs/project-structure#project-files-src

**Comment by kevinrenskers** [comment]
I can return a different message, but it always show the code 500:

```
import type { HandleServerError } from "@sveltejs/kit";

export const handleError: HandleServerError = ({ error }) => {
  console.log(error);

  return {
    code: 401,
    message: "My custom message",
  };
};
```

I tried "code" and "status", as strings and ints, with and without adding this to `interface PageError`. The default error page doesn't seem to pick up any custom status code?

**Comment by Conduitry** [comment]
That's the intended behavior. If you really need to override the status code for certain responses, you can do so manually in your `handle` hook.

But if you're returning something other than a 500, I'd argue that this is not really an unknown/unhandled error, and you should use the `throw error()` helper, and then just log (or do whatever you need to) from within `+error.svelte` itself. `handleError` really is intended for errors that you didn't foresee.

**Comment by kevinrenskers** [comment]
Hm I see, thanks.

I'm just in a pickle because in my real world app I am trying to handle 401 errors coming from the server, from a request I am doing in the root layout's load function. That means the `+error.svelte` page is not involved at all. Handling it in `handleError` is possible by throwing an unexpected error, except that I can't redirect back to safety of the homepage (after deleting the token cookie) from `handleError`. And also the user sees a big fat error 500 which is not so nice.

But that is rather off-topic for this issue, I understand why it's closed. If someone has ideas on how to solve global 401 error handling, please chime in on https://github.com/sveltejs/kit/discussions/6779 😅
