### ISSUE TITLE
Bug with prerendering based on anchor tags (during build)

### ISSUE THREAD

**Issue by smblee** [sveltejs/kit#6787]
### Describe the bug

Say you have a page that cannot prerender (`+server.ts` file with only `GET` export, for example, `/logout` page).

No matter what you do, if you have the file linked somewhere in other pages (like `header` component that lives at root layout that has a `logout` button), it seems like the build process will try to prerender the path and fail with the following error.

```
.svelte-kit/output/server/chunks/hooks.server.js                                       0.09 KiB
--
21:53:55.077 | Error: logout is not prerenderable
21:53:55.078 | at render_endpoint (file:///vercel/path0/.svelte-kit/output/server/index.js:208:11)
21:53:55.078 | at resolve (file:///vercel/path0/.svelte-kit/output/server/index.js:1947:28)
21:53:55.078 | at async respond (file:///vercel/path0/.svelte-kit/output/server/index.js:1997:22)
21:53:55.078 | at async visit (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:223:20)
21:53:55.080 | file:///vercel/path0/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50
21:53:55.081 | throw new Error(format_error(details, config));
21:53:55.081 | ^
21:53:55.081 |  
21:53:55.081 | Error: 500 /logout (linked from /)
21:53:55.081 | at file:///vercel/path0/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:50:11
21:53:55.082 | at save (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:361:4)
21:53:55.082 | at visit (file:///vercel/path0/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:232:3)
```

I've tried `data-sveltekit-prefetch="off"` in the anchor tag, and also `export const prerender = false;` from the `logout/+server.ts` file itself.

The only way for build to pass is getting rid of the anchor tag at the moment.

### Reproduction

The logout file: https://github.com/smblee/sveltekit-1.0-exploration/blob/main/src/routes/logout/%2Bserver.ts

without:

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/9781750/190042788-e2408dd2-79db-425f-85fb-e8ab98e4e80e.png">

Removing anchor (vercel build passes):
https://github.com/smblee/sveltekit-1.0-exploration/pull/1/files

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.34 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.6
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72
    @sveltejs/kit: next => 1.0.0-next.480
    svelte: ^3.46.0 => 3.50.1
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

**Comment by s3812497** [comment]
You can configure the `prerender` options in `svelte.config.js` as a workaround in the meantime:

1. Allow build to continue despite encountering prerender failures.
```js
const config = {
  kit: {
    adapter: adapter(),
    prerender: {
      onError: 'continue'
    }
  }
};
```

2. Disable crawling links during prerender.
```js
const config = {
  kit: {
    adapter: adapter(),
    prerender: {
      crawl: false
    }
  }
};
```
https://kit.svelte.dev/docs/configuration#prerender

**Comment by benmccann** [comment]
> I've tried data-sveltekit-prefetch="off" in the anchor tag

That's the wrong one. You need: https://kit.svelte.dev/docs/link-options#data-sveltekit-reload
