### ISSUE TITLE
https://kit.svelte.dev ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by amenayach** [sveltejs/kit#6791]
### Describe the bug

Just trying to explore [https://kit.svelte.dev](https://kit.svelte.dev) but I got `ERR_SSL_PROTOCOL_ERROR`

### Reproduction

Just open any modern web browser and try to head to: [https://kit.svelte.dev](https://kit.svelte.dev)

### System Info

```shell
chrome, edge
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment]
works fine here, site loads, cert is issued by let's encrypt and valid

```
Common Name (CN)	kit.svelte.dev
Organization (O)	<Not Part Of Certificate>
Organizational Unit (OU)	<Not Part Of Certificate>
Common Name (CN)	R3
Organization (O)	Let's Encrypt
Organizational Unit (OU)	<Not Part Of Certificate>
Issued On	Friday, August 19, 2022 at 9:43:01 PM
Expires On	Thursday, November 17, 2022 at 8:43:00 PM
SHA-256 Fingerprint	AF 78 CD 06 AE C1 FC 05 13 35 AE 5C 6A 4A 6F 3B
C8 29 85 97 D9 F5 03 03 A4 1A 4C 2E 5A BB AC BC
SHA-1 Fingerprint	6B 45 62 B6 78 E6 D4 BB B2 00 BA 8B D6 D2 23 23
9A DB CC F6
```

**Comment by dominikg** [comment]
confirmed from multiple people that the site is working fine, this is likely a problem on your end.

**Comment by amenayach** [comment]
Seems a country/region related thing, I am try from Lebanon:
![image](https://user-images.githubusercontent.com/13263277/190105790-4b11a30b-a39d-4d9a-9b0a-b0618f342933.png)

When I tried using a VPN through Germany it works!
![image](https://user-images.githubusercontent.com/13263277/190106125-59a8970e-b8aa-488e-9d14-c440ffa17881.png)
