### ISSUE TITLE
Thrown expected errors get a different status code on non-existing routes

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6799]
### Describe the bug

If you throw an error from `+layout.ts`, this gets rendered with the correct status code and message using the default error page.

```
import { error } from "@sveltejs/kit";
import type { LayoutLoad } from "./$types";

export const load: LayoutLoad = async () => {
  throw error(401, "Invalid token.");
};
```

However, if you go to a non-existing page, that error code now becomes 500.

### Reproduction

https://github.com/kevinrenskers/sk-error-page

Open http://127.0.0.1:5173 or http://127.0.0.1:5173/page, and you will see a 401 "Invalid token" error. But if you open http://127.0.0.1:5173/foo (which doesn't exist) you will see instead the same message but now with the status code 500.

I would expect to still see the same 401 code there, as I have not modified it anywhere. Or I would expect to see a 404? But definitely not a 500.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 717.94 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.73
    @sveltejs/kit: next => 1.0.0-next.481
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.0
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
The root layout is always loaded and its load function is always run. Upon first navigation the page is not found, so a 404 happens which means loading the root layout and the root error page. Then the root layout throws the error, probably resulting in this behavior.
