### ISSUE TITLE
Vercel notification noise

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#680]
Right now Vercel is commenting on every commit which is pretty noisy. E.g. https://github.com/sveltejs/kit/commit/c998143bc5059a8536142f021b83ce902af6e441#commitcomment-48707780 

I wonder if it could comment only when https://github.com/sveltejs/kit/tree/master/examples/svelte-kit-demo is changed?

Or maybe only when a deploy fails?

**Comment by iltimasd** [comment]
Not sure if this is related but Vercel makes a deployment per push

https://vercel.com/changelog/every-push-now-receives-a-unique-url

**Comment by iltimasd** [comment]
Vercel makes deployment per push, and the integration will comment for each one. So if there's a push per commit it will comment on the most recent commit on the push.

there is a way to silence it with the Vercel config: [https://vercel.com/docs/configuration#git/github-enabled](https://vercel.com/docs/configuration#git/github-enabled)

but im not sure if there's a more granular way to control the integration

**Comment by Rich-Harris** [comment]
There's this 'Ignored Build Step' section of the settings:

![image](https://user-images.githubusercontent.com/1162160/112533003-de9b1300-8d7f-11eb-9bd5-c076809a2800.png)

I've changed it to 

```
git diff -- packages/adapter-vercel/CHANGELOG.md packages/kit/CHANGELOG.md examples/svelte-kit-demo
```

so it should only run when the demo app changes, or when there's a release of `kit` or `adapter-vercel`. Suggestions for improvements welcome

**Comment by antony** [comment]
I'm going to work on an actions based deployment strategy for all of the adapters. This way we can have a more consistent and readable build output for our adapter tests.

**Comment by benmccann** [comment]
Nice! Thanks Rich!

**Comment by benmccann** [comment]
Hmm, unfortunately I'm not sure it worked. I just got an email about https://github.com/sveltejs/kit/pull/695. It says "Preview: Canceled"

**Comment by benmccann** [comment]
I haven't seen this in a bit. Hoping it's fixed now
