### ISSUE TITLE
GET in +server.ts gets called twice

### ISSUE THREAD

**Issue by NagabhushanS** [sveltejs/kit#6800]
### Describe the bug

The method GET gets called twice. Following is a sample code:

```
let counter = 0;

export const GET = async () => {
  counter++;
  return new Response(`count: ${counter}`);
};
```

The responses on consecutive page visits on browser are:
```
count: 1
count: 3
count: 5
count: 7
```

Interestingly the same is not the case, when I call the APIs using Postman, fetch (which give the correct output i.e., GET gets called only once).

### Reproduction

Reproduce by creating a file route/+server.ts with the following contents:
```
let counter = 0;

export const GET = async () => {
  counter++;
  return new Response(`count: ${counter}`);
};
```
Visit localhost:5173/ on browser.

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.55 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 105.1.43.89
    Chrome: 105.0.5195.102
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/kit: next => 1.0.0-next.480 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

### Additional Information

The GET method needs to be called only once.

**Comment by dummdidumm** [comment]
Can't reproduce this given the instructions. Please provide a minimum reproducible.

**Comment by dummdidumm** [comment]
Tried this, but it increases the count by 1 as expected for me

**Comment by dummdidumm** [comment]
Can't reproduce it that way, either

**Comment by Conduitry** [comment]
You know, there actually is a reason the instructions when opening a new bug issue say that reproductions need to be a link to a repository or to a StackBlitz project.

**Comment by dummdidumm** [comment]
chrome

**Comment by bfovez** [comment]
Hello everyone,
I just tried the thing, and I reproduce the bug on Chrome (v105) and Edge (v105). 
And indeed, works as expected with Firefox (v104).

**Comment by dummdidumm** [comment]
I'm on 105, too (Windows), can't reproduce this. Could you try this in an incognito tab to make sure it's not some browser extension causing this?

**Comment by dangelomedinag** [comment]
I have the same problem

routes/[id]/+server.ts
```js
let counter = 0;

export const GET = () => {
	counter++;
	return new Response(`count: ${counter}`);
};
```
visit 'localhost:5173/whatever' repeatedly
```bash
count: 1
count: 3
count: 5
count: 7
```
windows 10 Verison 21h2
Chrome Versión 105.0.5195.125
node v16.17.0

output `console.trace()`
```bash
Trace
    at GET (C:\Users\produ\Documents\interno\dev\sveltekit\src\routes\[id]\+server.ts:6:11)
    at render_endpoint (file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:38:26)
    at resolve (file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:233:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:301:20)
    at async file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
Trace
    at GET (C:\Users\produ\Documents\interno\dev\sveltekit\src\routes\[id]\+server.ts:6:11)
    at render_endpoint (file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:38:26)
    at resolve (file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:233:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async respond (file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:301:20)
    at async file:///C:/Users/produ/Documents/interno/dev/sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

**Comment by bfovez** [comment]
> I'm on 105, too (Windows), can't reproduce this. Could you try this in an incognito tab to make sure it's not some browser extension causing this? Could you place a `console.trace()` in the `GET` function and paste the call stack of it in here (for the first and the duplicated request, to see if they differ)?

Just tested in an incognito tab, same outcome.

**Comment by dominikg** [comment]
Please check out https://github.com/sveltejs/kit/issues/5136  it is possible that your parameterized route is picking up requests to `favicon.ico` 
Please provide a link to a repository which reproduces this issue and include logging of the actual param value in the endpoint as well.

The reproduction is required so that we have a common ground to work with. Right now all of us are speculating, this is frustrating and error prone.

**Comment by dangelomedinag** [comment]
[reproduction](https://github.com/dangelomedinag/server-endpoints-gets-called-twice) - it might just be chrome

as this https://github.com/sveltejs/kit/issues/6800#issuecomment-1248064392 suggests, favicon.ico is the cause of repeated requests.

**Comment by maximedupre** [comment]
I'm not sure if this is related or not, but since updating to 

```
"@sveltejs/adapter-node": "^1.0.0-next.92",
"@sveltejs/kit": "^1.0.0-next.484",
```

from

```
"@sveltejs/adapter-node": "^1.0.0-next.87",
"@sveltejs/kit": "^1.0.0-next.474",
```

Sentry started reporting

> Error Not found: /favicon.ico

**Comment by Rich-Harris** [comment]
This happens because browsers are making a real (if pointless) request for `/favicon.ico`. It's not SvelteKit's place to intercept those requests in a way that interferes with app developers' ability to handle them as they see fit, so there's really nothing to do here.

Workarounds:

* create a `static/favicon.ico` file
* create a `src/routes/favicon.ico/+server.js` file with a `load` that contains `throw error(404)`
* validate the `[whatever]` param

**Comment by ShriPunta** [comment]
Hi I am having the same issue with postman as well.

<img width="490" alt="image" src="https://github.com/sveltejs/kit/assets/22234496/fd80e732-ce3c-42f5-8720-190e7cc8c0ca">

**Comment by ShriPunta** [comment]
Hi @Rich-Harris , Sorry again for the tag. I created a random simple route `routes/a/+server.ts` and it still invoked it twice while doing a separate call for `favicon.ico`.
I have tried to reach out everywhere to get help (Stackoverflow, Discord community, GitHub issues) but I am stumped. 
Please do let me know if this is a potential bug.
I am almost on the verge of giving up SvelteKit for my project.

![image](https://github.com/sveltejs/kit/assets/22234496/70515c78-d6f0-4242-9162-c009ebaa5a50)

Here is my `hooks.server.ts`

```

import { validateSessionHook } from '$lib/hooks/validateSessAndPopulateUserHook';
import { type Handle } from '@sveltejs/kit';
import type { MaybePromise, RequestEvent, ResolveOptions } from '@sveltejs/kit';

const PUBLIC_ROUTES = ['/login', '/api/signin', '/api/sf/auth/callback', '/connections/close']
// Handling requests
export const handle = (async ({ event, resolve }) => {
  if (PUBLIC_ROUTES.some(publicPrefix => event.url.pathname.startsWith(publicPrefix)
    || event.url.pathname == '/')) {
    console.log('PUBLIC route call -->', event.url.pathname);
    return await resolve(event);
  } else {
    console.log('Private route call -->', event.url.pathname);
    return await authorizedRouteHandle(event, resolve);
  }

}) satisfies Handle;


const authorizedRouteHandle = async (event: RequestEvent<Partial<Record<string, string>>, string | null>, resolve: (event: RequestEvent<Partial<Record<string, string>>, string | null>, opts?: ResolveOptions | undefined) => MaybePromise<Response>) => {
  // User object is not set for the request, then continue
  if (!event.locals.user) {
    event.locals.user = {
      userId: null,
      sid: null
    }
    await validateSessionHook({ event, resolve });
  }
  return await resolve(event)
}
```

Here is the `validateSessionHook` code:

```
import { retrieveSessionWithSFConnBySessionId } from "$lib/services/DBService/DBSessionService";
import { verifySessionIdAndSetLocals } from "$lib/services/SessionService";
import { error, type Handle } from "@sveltejs/kit";
import { sequence } from "@sveltejs/kit/hooks";

const routeDataValidateSession = (async ({ event, resolve }) => {
  const sessionCookie = event.cookies.get("__session");
  if (!sessionCookie) {
    return error(400, {
      message: "Missing Sesssion cookie"
    })
  }
  try {
    await verifySessionIdAndSetLocals(event.locals, sessionCookie);
    // If unverified, the above method call throws an exception.
  } catch (e) {
    event.locals.user.userId = null;
    return error(401, {
      message: "Invalid session."
    })
  }
  // resolve will move onto whatever logic is next. Similar to next() in express
  return await resolve(event);
}) satisfies Handle;


const dbFetchAndPopulateLocalsUserObj = (async ({ event, resolve }) => {

  // If it has reached here in sequence, it should definitely have a userId populated with a session.
  const dbSessionWithSFConn = await retrieveSessionWithSFConnBySessionId(event.locals.user.sid!);
  if (!dbSessionWithSFConn) {
    return error(401, {
      message: "No active session found."
    })
  }

  if (dbSessionWithSFConn.sfConn) {
    // populate locals with sfConnection details
    event.locals.sf = {
      ...dbSessionWithSFConn.sfConn,
      refreshToken: dbSessionWithSFConn.sfConn.refreshToken ?? '',
    }
  }
  console.log('sequence2 called?-->', Date.now())
  return await resolve(event);
}) satisfies Handle;

export const validateSessionHook = sequence(routeDataValidateSession, dbFetchAndPopulateLocalsUserObj);
```

**Comment by fehnomenal** [comment]
I guess you have to return the result of `validateSessionHook`. Otherwise you resolve the event a second time and thus call the endpoint handler.

**Comment by ShriPunta** [comment]
Wow! Thank you so much! You are awesome and rightly named @fehnomenal !!
It worked! I have been stuck on this for a week 🙏 👏 🎉 

<img width="1390" alt="image" src="https://github.com/sveltejs/kit/assets/22234496/cc686ff4-da53-43b3-b6e8-d547e697572c">

Thank you again!
