### ISSUE TITLE
Failed to load module script, if the `URL` ends with `/` - `adapter-static`

### ISSUE THREAD

**Issue by gyurielf** [sveltejs/kit#6803]
### Describe the bug

Hello there!

I try to migrate to the RC version of sveltekit. It's went quite well until this point.

First of all, it's hard to wrap into a self-contained reproduction, but I tried my best.
It can't reproducible on StaclBlitz, because it runs `npm run preview` to serve built app.

The app running on a CDN therefore it uses the following config:

```javascript
// svelte.config.js 
kit: {
    adapter: staticAdapter({
        fallback: '404.html'
    }),
    trailingSlash: 'always'
}
```
and to make `index.html` files as entry points, it uses:
```typescript
// /routes/+layout.ts
export const prerender = true;
export const ssr = false;
```
Then, files created as it should, but if I deploy or serve via nginx, if I hit `domain/about/` URL, it will be a blank page and throw an error into the console.
But if I hit `domain/about` it will load the site and redirect to `domain/about/`. If I try to refresh, it will be a blank page and throw error into the console.

Minimal reproduction is attached below. (Reproduction steps in the README.md)

### Reproduction

[Reproduction link](https://github.com/gyurielf/sveltekit-trailing-slash-issue)

### Logs

```shell
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.30 GB / 15.48 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.local/share/pnpm/node
    npm: 8.17.0 - ~/.local/share/pnpm/npm
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 104.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.43 => 1.0.0-next.43 
    @sveltejs/kit: next => 1.0.0-next.481 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

blocking an upgrade

### Additional Information

Without I set `trailingSlash: 'never'`, it works, but if I put slash to the end of the URL, it will broken.

**Comment by Rich-Harris** [comment]
Looks like a bad nginx config. Whatever URL I go to — `/`, `/about/`, `/this/path/does/not/exist` — it serves `build/index.html`, which contains relative links that are broken unless you happen to be visiting `/`.

No idea how to fix it I'm afraid as I'm not an nginx expert, but it isn't a SvelteKit bug so I'll close this issue.
