### ISSUE TITLE
Prettier is ignoring svelte files

### ISSUE THREAD

**Issue by kyuuaria** [sveltejs/kit#6804]
### Describe the bug

I created a new sveltekit app but when running the lint or format script prettier is ignoring all svelte files. It only works when explicitly telling prettier to check for svelte files with for example `src/**/*.{ts,svelte}` instead of `.`.

### Reproduction

- create a new sveltekit app with `pnpm create svelte@latest` and make sure to add prettier for code formatting
- install the packages with `pnpm install`
- run `pnpm format`

> You won't see any svelte files getting formatted

### System Info

```shell
System:
  OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
  CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
  Memory: 23.82 GB / 24.99 GB
  Container: Yes
  Shell: 5.8.1 - /usr/bin/zsh
Binaries:
  Node: 16.17.0 - ~/.local/share/pnpm/node
  npm: 8.15.0 - ~/.local/share/pnpm/npm
npmPackages:
  @sveltejs/adapter-node: next => 1.0.0-next.90
  @sveltejs/kit: next => 1.0.0-next.481
  svelte: ^3.50.1 => 3.50.1
  vite: ^3.1.0 => 3.1.0
```

### Severity

annoyance

**Comment by dominikg** [comment]
can confirm, adding `--plugin-search-dir .` to the script in package.json works, wonder why `	"pluginSearchDirs": ["."],` in the prettierrc doesn't do the same.

**Comment by ZizhengTai** [comment]
Possibly caused by https://github.com/sveltejs/prettier-plugin-svelte/issues/155

**Comment by mvllow** [comment]
A previous version of the sveltekit template included `"plugins": ["prettier-plugin-svelte"]`. Adding this to the prettier config in a new project works as expected. When using editors aside from VSCode and the Svelte extension, this has always been needed for me.

**Comment by oscard0m** [comment]
With Prettier v3, `--plugin-search-dir` (and `pluginSearchDirs` in config file) has been removed. 

Prettier's documentation [suggests using `--plugin` instead (or `plugins` in config file](https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker). Even though my `.prettierrc` has a `plugins` entry, I have to pass the `--plugin='prettier-plugin-svelte'` to keep it working. Very similar to what @dominikg suggested [here](https://github.com/sveltejs/kit/issues/6804#issuecomment-1246753782).

Does it happen to you as well?

**Comment by dummdidumm** [comment]
This is a bug within Prettier, see the migration guide for more info: https://github.com/sveltejs/prettier-plugin-svelte#how-to-migrate-from-version-2-to-3
