### ISSUE TITLE
`npm create svelte@latest my-app` and then `cd my-app` - you have to type the same name twice - this is annoying

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#6805]
### Describe the problem

Typical SvelteKit installation code:

```shell
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```

It is annoying for me, typing the same name in two places every time I create a new project in SvelteKit.

### Describe the proposed solution

I would like, for example, such a:

```shell
npm create svelte@latest my-app --cd
npm install
npm run dev -- --open
```

In the `npm create svelte@latest my-app --cd` line there is an added attribute `--cd`, which replaces the `cd my-app` line, with the project name repeated.

This would make me less annoyed, when creating a new SvelteKit project.

### Importance

would make my life easier

**Comment by deric4** [comment]
You can append ` && cd $_` to your command if you're using bash/zsh/etc

> `$_` interpolates to last argument of the previous command.

```console
$ npm create svelte@latest my-app && cd $_

create-svelte version 2.0.0-next.176

Welcome to SvelteKit!

This is release candidate software; expect bugs and missing features.

Problems? Open an issue on https://github.com/sveltejs/kit/issues if none exists already.

✔ Which Svelte app template? › Skeleton project
✔ Add type checking with TypeScript? › No
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Add Playwright for browser testing? … No / Yes

Your project is ready!

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-adders

Next steps:
  1: cd my-app
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat

$ pwd
/inside/your/new/proj/called/my-app
```

**Comment by lukaszpolowczyk** [comment]
It works. I just have to remember it. And I always copy the installation code from https://kit.svelte.dev/ anyway. xD

How would you add this code of yours to https://kit.svelte.dev/ and guide?

**Comment by dominikg** [comment]
Adding flags to the cli has been suggested before see https://github.com/sveltejs/kit/issues/6765 (that has more links to previous requests of similar nature)

You could also call `create-svelte` as part of a script and run `npm install` after `cd app-dir`, saving even more keystrokes.

**Comment by Conduitry** [comment]
Yes, something universal, like something that is literally impossible in Bash.
