### ISSUE TITLE
HMR and loading from node_modules in `app.html` does not work at all

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#6806]
### Describe the bug

In this thread - https://github.com/sveltejs/kit/issues/6636, Mr. @Conduitry recommends using `app.html` for various things.

However, `app.html` has various shortcomings.

E.g. HMR does not work for `app.html`.
HMR does not respond. (when I load `<script type="module" src="src/s.js"></script>`, it responds, but that's not the point of breaking everything into separate files, right?)

 In `app.html` it does not even support loading a module from node_modules:
![testapphtml](https://user-images.githubusercontent.com/16800535/190141435-9712054c-61b3-4a8e-a3b4-a43de8728703.png)

Besides, I suspect that in `app.html` it is impossible to get many other advantages of svelte files.

### Reproduction

Change something in `app.html` and see that HMR does not work.

Use the code as in the image, and see that node_modules is not loading.

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 12.90 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.8 - /bin/bash
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.109
    Firefox: 102.2.0esr
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.73 
    @sveltejs/kit: next => 1.0.0-next.481 
    svelte: ^3.46.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

**Comment by dominikg** [comment]
Hi, even if it may be simple, we ask everyone to provide a link to a repository with a reproduction in our issue template for a reason.

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by lukaszpolowczyk** [comment]
Error node_modules:

https://github.com/lukaszpolowczyk/apphtmltest

Does not support jquery with node_modules. The error can be seen in the browser console.

---

To check that HMR in `app.html` doesn't work either, you can comment out the line `import $ from "jquery";` in `app.html` - the page in the web browser doesn't refresh in any way.

**Comment by lukaszpolowczyk** [comment]
@david-plugge I have some quick scripts that I'm loading and testing, and it doesn't necessarily match the layout in mode with SSR disabled. Sometimes I want to test something quickly, some local module. jquery was only given as an example, it's not about it.

But that may not be the most important thing.

Loading CSS from `<link rel="stylesheet" href="src/s.css">` also has this problem.
Commenting out a line with such a `link` is not supported by HMR either.

Tag styles are not supported either, changes to these styles do nothing:
```html

		<style>
			html {
			background-color: rgb(255, 6, 6);
		}
		</style>
```

And I can't use it in +layout, for the reason described in this thread - https://github.com/sveltejs/kit/issues/6636
(SSR and blink issue)

And that thread was rejected, as you can see.

So all that is left is the `app.html` file.

In general, you can see that `app.html` is not fully supported by SvelteKit.
But the SvelteKit member refers to the `app.html` file.

**Comment by dominikg** [comment]
hmr won't work when editing app.html as there is no way to preserve the current page. Only a full reload is able to ensure that the changes actually do what is expected. So the best we could do in this case is trigger a full reload.

Not sure exactly why you chose jquery as an example but the way you are loading it would not work either way. You'd have to wrap it in onMount to prevent it from getting loaded during ssr.

something like 

```js
import {onMount} from 'svelte';
import * as jq from 'jquery';
onMount(()=>{
  // maybe this works? 
  if(!window.$) window.$=jq;
})
```

or 
```js
import {onMount} from 'svelte';
onMount(()=>{
  import('jquery').then(jq =>{
    // do something
  })
})
```
in your root layout could work.

either way, please join our discord on https://svelte.dev/chat and try to ask for help. This bug seems to mix two different problems you are having with using app.html for something it isn't designed for.

**Comment by lukaszpolowczyk** [comment]
There is no need to wrap `onMount` to make `jquery` work from `app.html`.
The script from `app.html` only loads on the browser side. He never loads on the server side.
Check `console.log` in `app.html`.
```html
<script>
console.log("dee")
</script>
```
...Works without any problem, only on the browser side.

I figured that these are similar topics, generally "lack of app.html support by SvelteKit".
You can limit this issue to just the styles topic, if that's more convenient. Without the node_modules subject.

There's the problem that @Conduitry's recommended way to CSS without SSR, doesn't even have basic support like HMR.

**Comment by david-plugge** [comment]
> Sometimes I want to test something quickly, some local module

That can also be done in the layout.

> Loading CSS from `<link rel="stylesheet" href="src/s.css">` also has this problem.
> Commenting out a line with such a `link` is not supported by HMR either

Yeah that´s an issue for me aswell. I think adding the linked resources to the vite file watcher and reloading the page on changes could be a valid way to solve that.

> Tag styles are not supported either, changes to these styles do nothing

That works for me in a new sveltekit project

**Comment by lukaszpolowczyk** [comment]
Well, but that is when you need `onMount` etc. :D
And also I had a case where I couldn't load it from the import level, I had to add it to the `<script src="script-url">` tag. A script that has no equivalent in the form of a module.
In fact, I am currently using something like this. In order to make it work in `+layout`, I had to create a function that does `document.createElement("script")`, and loads that into the `head` using `append(script)`.
Let me emphasize: It was about doing it fast, and the whole thing was not fast. :|

> Yeah that´s an issue for me aswell. I think adding the linked resources to the vite file watcher and reloading the page on changes could be a valid way to solve that.

@david-plugge Wait. Once you load the page with `<link rel="stylesheet" href="src/s.css">` in `app.html`, then modifying the content in the `src/s.css` file works with HMR. I have already written this in the issue.
What does not work with HMR is the very moment of adding the `<link rel="stylesheet" href="src/s.css">` tag to the `app.html` file.

It's complicated, I see. But now you understand?

> That works for me in a new sveltekit project

@david-plugge I am using SvelteKit 1.0.0-next.481, this is the latest version. You can see in my logs in the issue.

HMR does not work for the styles in the `style` tag in `app.html`.
When I manually refresh the page in the web browser, this style from the `style` tag in `app.html` loads.
The problem is with HMR.

Such code, and I just change the `color` in `background-color`, and nothing refreshes on its own:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<style>
			html {
			background-color: rgb(50, 37, 170);
		}
		</style>
		%sveltekit.head%
	</head>
	<body>
		<div>%sveltekit.body%</div>
	</body>
</html>

```

Summary: Simply whatever is directly placed in `app.html` is not supported by SvelteKit.

**Comment by david-plugge** [comment]
You are right, `<link rel="stylesheet" href="src/s.css">` works but `src/s.css` is not included in the bundle if you build the app. I linked to `/global.css`, css file in the asset folder but changing the contents does not trigger a page reload.

I copied your code into a project with tailwind installed, that must have triggered a refresh.

**Comment by Rich-Harris** [comment]
This is expected behaviour, and not something it would make any sense to try and change

**Comment by lukaszpolowczyk** [comment]
> This is expected behaviour, and not something it would make any sense to try and change

@Rich-Harris I don't know how to reconcile this with @Conduitry's words that `app.html` is the recommended way to load styles when you have an app with SSR disabled.
(The topic of blinking black background in dark mode, with the app with SSR disabled, which is in the link in the topic)
