### ISSUE TITLE
Preloading critical style-sheets for improved performance 🚤  

### ISSUE THREAD

**Issue by sanjaiyan-dev** [sveltejs/kit#6812]
### Describe the problem

This is inspired from `Next.js`.
[Preload critical stylesheets to improve loading speed](https://web.dev/preload-critical-assets/).

I think headers won't work in SSG mode :(.

### Describe the proposed solution

Using `link:rel=preload`

### Importance

nice to have

**Comment by sanjaiyan-dev** [comment]
Related PR-: https://github.com/sveltejs/kit/pull/6712

**Comment by Rich-Harris** [comment]
Unless I'm mistaken, this already happens. Can you please clarify?

**Comment by benmccann** [comment]
To add to what Rich said, if this isn't already happening, please provide a sample repository and describe what URL you want to be preloaded that is not

**Comment by bradleyg** [comment]
I'm seeing the same thing. When visiting a pre-rendered page, the preload headers aren't sent (and it doesn't fallback to using `rel="preload"` on the `<link>` element).

[Sample code](https://stackblitz.com/edit/node-3s5o8j?file=README.md&view=editor)

**Comment by sanjaiyan-dev** [comment]
> Unless I'm mistaken, this already happens. Can you please clarify?



> To add to what Rich said, if this isn't already happening, please provide a sample repository and describe what URL you want to be preloaded that is not

I thought this would benefits for SSG generated pages :) and this doesn't have any drawback for SSR pages too 😄 

_Sorry if I told anything incorrect :(_

**Comment by Rich-Harris** [comment]
There's no reason to duplicate `<link rel="stylesheet">` as `<link rel="preload">`. It won't speed anything up — in fact it will slow things down because you're sending extra markup unnecessarily.

**Comment by bradleyg** [comment]
The problem isn't with duplication, the issue is that for any page that has `export const prerender = true;` neither the preload headers (`Link`) or markup `<link rel="preload" href="style.css" as="style" />` exists at all.

<img width="1115" alt="Screen Shot 2022-09-20 at 09 38 56" src="https://user-images.githubusercontent.com/275270/191212189-904944fd-f071-4d1d-b752-dcf3a322ea0f.png">

<img width="1115" alt="Screen Shot 2022-09-20 at 09 39 01" src="https://user-images.githubusercontent.com/275270/191212268-7696ee17-94ea-4ae9-bbd1-8728240c1256.png">

See [sample code](https://stackblitz.com/edit/node-3s5o8j?file=README.md&view=editor).

**Comment by sanjaiyan-dev** [comment]
> There's no reason to duplicate `<link rel="stylesheet">` as `<link rel="preload">`. It won't speed anything up — in fact it will slow things down because you're sending extra markup unnecessarily.

https://web.dev/preload-critical-assets/#preloading-css-files

**Comment by geoffrich** [comment]
There is no need to preload the stylesheets on the SvelteKit homepage. The point of preload is to tell the browser about stylesheets that are being lazy-loaded with JS so it can start fetching them before they're needed. The web.dev article you linked only talks about preloading CSS in the context of loading it with JS:

> If you are using the [critical CSS approach](https://web.dev/extract-critical-css), you split your CSS into two parts. The critical CSS required for rendering the above-the-fold content is inlined in the <head> of the document and _non-critical CSS is usually lazy-loaded with JavaScript._ Waiting for JavaScript to execute before loading non-critical CSS can cause delays in rendering when users scroll, so it's a good idea to use <link rel="preload"> to initiate the download sooner.
>
> https://web.dev/preload-critical-assets/#preloading-css-files

For the SvelteKit homepage, the stylesheets are _already being loaded via the head_, not with JS, so adding extra link tags with "preload" won't speed anything up. And as Rich mentioned, it increases the sent markup unnecessarily, so it actually slows things down.

```
<link href="./_app/immutable/assets/_layout-4d3fe515.css" rel="stylesheet">
<link href="./_app/immutable/assets/SkipLink-278549ba.css" rel="stylesheet">
<link href="./_app/immutable/assets/SearchResults-1df3fdcb.css" rel="stylesheet">
<link href="./_app/immutable/assets/_page-134b8b92.css" rel="stylesheet">
```

If you inspect the network trace, you'll see that the stylesheets are loaded immediately after the HTML document is parsed. Adding `rel="preload"` won't speed this up.

![screenshot of network trace showing stylesheets being loaded immediately after the document](https://user-images.githubusercontent.com/4992896/192841562-67465edc-27d1-443e-870b-db991df69b1f.png)
