### ISSUE TITLE
I have several development proposals and feature requests for svelte and svelte-kit

### ISSUE THREAD

**Issue by InfernalAzazel** [sveltejs/kit#6819]
### Describe the problem

svelet and kit are very popular and excellent projects, we still use vue react the most in China

We focus on stable documentation and ecology

Maybe svelet and kit can replace the position of vue, no matter what the technology is, vue is the most used here

What gives me a headache is that there are some invalid instructions in the official documentation

bad ecological environment

Very few development examples

### Describe the proposed solution

1. Hope the docs are up to date and the descriptions clear
2. I hope the official homepage can be designed more professionally and better. Reference vue
3. Write more examples
4. vite create sveletkit Library skeleton project want to integrate docs similar VuePress (In this regard, it is hoped that the convenience provided can stimulate the enthusiasm for building an ecology regardless of the level of technology.)

### Importance

i cannot use SvelteKit without it

**Comment by benmccann** [comment]
We are working on a new homepage and tutorials. Thank you for the ideas
