### ISSUE TITLE
exporting async function from matcher doesn't work

### ISSUE THREAD

**Issue by Mr-M1M3** [sveltejs/kit#6827]
### Describe the bug

Hello, I'm trying to export an async function from matchers inside `/src/params`. It didn't work even if I return `false` explicitely.

### Reproduction

Say, I have a route `routes/book/[page]`. To make sure `[page]`  is a number, I wrote a param matcher called `int.js` inside `src/params` and renamed my route dir to [routes/book/[page=int]]. Now, inside `src/params/int.js`,

```javascript
// src/params/int.js
export async function match(v){
// other things that I can do only inside an async function

// for now, lets return `false` explicitely
return false;
}
```
Though we returned `false` explicitly, it will match any route instead of matching no route.

### System Info

```shell
System:
    OS: Linux 5.18 Manjaro Linux
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 11.07 GB / 15.40 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.93
    Chromium: 104.0.5112.79
    Firefox: 103.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/kit: next => 1.0.0-next.480 
    svelte: ^3.46.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
This is the intended behavior. We want matchers to be able to be small and to run quickly and synchronously. Any async stuff will have to happen inside `load`.
