### ISSUE TITLE
Duplicated tags from component inside svelte:head after hydration

### ISSUE THREAD

**Issue by tdislay** [sveltejs/kit#6858]
### Describe the bug

When you create a new svelte component, with some tags (title, meta, etc.) then use this component in `svelte:head` (in a `layout.svelte`), the tags inside the component get duplicated in the head section after hydration.

What I've tested:
- Disable csr / ssr : it works fine, my tags didn't get duplicated
- Extracting the tags from the component, and inserting them directly into `layout.svelte` : it works fine
- Testing from firefox / chromium

I've found a weird workaround:
Surround with the `svelte:head` tag your tags inside the components, then you can put your component either inside or outside the `svelte:head` tag in the `layout.svelte` 

### Reproduction

routes>layout.ts
```js
<script>
  import Title from '$lib/Title.svelte';
</script>
<svelte:head>
    <Title></Title>
</svelte:head>
<slot />
```

lib>Title.svelte
```js
<title>Welcome</title>
```

-> Add a `route>+page.svelte` file to create a working route
-> `npm run dev -- --open` (same result with `npm run build && npm run preview`)
-> Open the webpage, check source => The tags got duplicated

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 15.91 GB / 23.42 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chromium: 105.0.5195.102
    Firefox: 104.0.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.75 => 1.0.0-next.75 
    @sveltejs/kit: next => 1.0.0-next.484 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.1
```

### Severity

annoyance

**Comment by benmccann** [comment]
I'm guessing this is a duplicate of https://github.com/sveltejs/svelte/issues/4533, https://github.com/sveltejs/svelte/issues/6463, https://github.com/sveltejs/svelte/issues/7444. The issue will be fixed in the next release of Svelte

**Comment by tdislay** [comment]
Yes, it is. Thank you :)
