### ISSUE TITLE
Feature Request: something along the lines of `await serverLoad()`

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#6859]
### Describe the problem

Consider this example pseudo code which represents one of many different yet similar situations I ran into today...

```js
// `+layout.server.js`
import ModalCreateNewGroup from './ModalCreateNewGroup.svelte'

export async function load({ locals })
{
	const groups = await locals.company.getGroups() // database query
	
	return { 
		groups,
		modals: [
			{
				id: 'create-new-group',
				component: ModalCreateNewGroup // component reference
			}
		]
	}
}
```

`devalue` chokes while trying to serialize the component. Renaming `+layout.server.js` to `+layout.js` is not going to do the trick due to the database query requiring a database connection which is only available on the server side. 

### Describe the proposed solution

It basically boils down to this:

```js
/** @type {import('@sveltejs/kit').LayoutServerLoad} */
export async function load({ locals })
{
	const groups = await locals.company.getGroups() // database query
	
	return { 
		groups
	}
}


import ModalCreateNewGroup from './ModalCreateNewGroup.svelte'

/** @type {import('@sveltejs/kit').LayoutLoad} */
export async function load({ serverLoad })
{	
	const data = await serverLoad() // does a fetch or something like that under the hood
	return {
		...data,
		modals: [
			{
				id: 'create-new-group',
				component: ModalCreateNewGroup
			}
		]
	}
}
```

### Alternatives considered

My current workaround involves creating a standalone `+server.js` endpoint that returns the database query results and then fetching those results from the endpoint in my `+layout.js`'s load function. I can tell from experience that this is not fun and can lead to confusion in bigger teams.

### Importance

would make my life easier

### Additional Information

1. I really need a reference to the component inside `$page.data`. This so it can be accessed by a managing component, for example: the  "`<ModalManager />`", in my root `+layout.svelte`.

2. this is probably a breaking change.

3. I have not thought this through to an interstellar extend.

**Comment by geoffrich** [comment]
I think you can do what you want with the `data` property on RequestEvent. See [the docs](https://kit.svelte.dev/docs/load#input-properties).

```js
/** @type {import('@sveltejs/kit').LayoutServerLoad} */
export async function load({ locals })
{
	const groups = await locals.company.getGroups() // database query
	
	return { 
		groups
	}
}


import ModalCreateNewGroup from './ModalCreateNewGroup.svelte'

/** @type {import('@sveltejs/kit').LayoutLoad} */
export async function load({ data })
{	
	return {
		...data, // data from the server load
		modals: [
			{
				id: 'create-new-group',
				component: ModalCreateNewGroup
			}
		]
	}
}
```

**Comment by UltraCakeBakery** [comment]
@geoffrich I can't believe I looked over that entire section. Thanks!
