### ISSUE TITLE
Remove 'Update latest tag on published packages' step

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#686]
https://www.npmjs.com/package/@sveltejs/kit shows an old version of the README and people continually run into issues installing the `latest` instead of `next` package

**Comment by Rich-Harris** [comment]
is that just a matter of removing `--tag=next` from https://github.com/sveltejs/kit/blob/d1925cfa7a469841c78302b49b3a6d11fc6f4954/package.json#L12 ? we can still stay in `pre` mode as far as `changesets` is concerned, and publish packages with a `-next.n` version suffix?

if so then 👍 this probably makes sense, though presumably we'd need to do some deprecated `@next` releases so that people are pointed towards `latest`? otherwise this would be equally confusing for the people currently using `@next` packages.

**Comment by benmccann** [comment]
@pngwn do you know if we can just remove `--tag=next` or if more is needed?

**Comment by pngwn** [comment]
We need to call changeset publish to get other tags and releases in the repo rather than recursively publishing manually.

**Comment by Rich-Harris** [comment]
but `changeset publish` would publish `next` tags because we're in prerelease mode, no? Will `changeset publish` respect the `"private": true` package.json fields?

**Comment by pngwn** [comment]
> But changeset publish would publish next tags because we're in prerelease mode, no?

You're right, i'm not sure how we add additional tags for specific releases, I'll look into that.

> Will changeset publish respect the "private": true package.json fields?

It will, yes.

**Comment by benmccann** [comment]
`pnpm publish` might not let us add two tags, but we should be able to add a second tag after the package is published

**Comment by dominikg** [comment]
we are using `changeset publish` and it is run by `@changeset/action'` here:  https://github.com/sveltejs/kit/blob/32a7ccfbd1ab5e1928da27149fe67d88d3308f7f/.github/workflows/release.yml#L32
 
This action [emits outputs](https://github.com/changesets/action#outputs) that could be used to generate
`npm dist-tag add package@version latest` calls in a conditional step  

```
- name: Tag published packages as latest too
        if: steps.changesets.outputs.published == 'true'
        # somehow take that json output of steps.changesets.outputs.publishedPackages and turn it into dist-tag commands
        run: # execute commands
```
problems:
1) github actions expressions syntax is not a joy to work with  
2) running `dist-tag` shortly after publishing a version for the first time may fail if the registry hasn't propagated the new version.

**Comment by Rich-Harris** [comment]
Rather than close this and create another issue, I've renamed the title to remind us to remove this stuff once we exit `pre`: https://github.com/sveltejs/kit/blob/f0df78265c393f0dc4730500f405ee10a94bf2e6/.github/workflows/release.yml#L43-L54

**Comment by didier** [comment]
@Rich-Harris Can we close this?

**Comment by dummdidumm** [comment]
Yes we can :)
