### ISSUE TITLE
extending a tsconfig in .svelte-kit/tsconfig.json

### ISSUE THREAD

**Issue by Alexandre-Fernandez** [sveltejs/kit#6868]
### Describe the bug

I have a monorepo which shares a base tsconfig and I want sveltekit to extend it.
However the root sveltekit tsconfig extends `.svelte-kit/tsconfig.json` and I cannot modify `.svelte-kit/tsconfig.json` to extend my  base tsconfig because it gets overridden by the auto-generation.
So from what I understand my only choice if I want to extend my base tsconfig is to lose the autogenerated one ?

### Reproduction

Create a turborepo app and create a sveltekit app inside the app folder.

### System Info

```shell
Linux
```

### Severity

annoyance

### Additional Information

I created this package to be able to extend multiple tsconfigs: 
https://github.com/Alexandre-Fernandez/tsconfig-multiple-extends

**Comment by bluwy** [comment]
Looks like there has been some work for array support for `extends`: https://github.com/microsoft/TypeScript/pull/50403
