### ISSUE TITLE
AWS Amplify with Svelte-Sapper and Svelte-Kit

### ISSUE THREAD

**Issue by EdwinFdoGarcia** [sveltejs/kit#687]
We are very excited with svelte-kit
We started some academic exercises to deploy applications with Svelte-Kit in aws amplify, playing with Appi, storage ... etc.

`Installation method:
mkdir my-app
cd my-app
npm init svelte @ next
npm install
npm run dev - --open`

when starting the cloud environment it shows an error: (Error [ERR_REQUIRE_ESM])

<img width="1912" alt="Captura de Pantalla 2021-03-25 a la(s) 2 35 42 p  m" src="https://user-images.githubusercontent.com/35706123/112533069-8f50e480-8d77-11eb-826b-8ea5fa1cab28.png">

<img width="1920" alt="Captura de Pantalla 2021-03-25 a la(s) 3 34 11 p  m" src="https://user-images.githubusercontent.com/35706123/112540154-d6db6e80-8d7f-11eb-88e2-cd6804dc5531.png">

We understand that it could be an Amplify error so we created the same academic exercise with Svelte-Sapper but now it works! we can deploy our academic project with Svelte-Sapper!

<img width="1918" alt="Captura de Pantalla 2021-03-25 a la(s) 2 40 09 p  m" src="https://user-images.githubusercontent.com/35706123/112533701-3cc3f800-8d78-11eb-96d0-8a538a949230.png">

**We appreciate the time you take to read these academic concerns!**

**Comment by benmccann** [comment]
This issue would probably be best asked on Discord. Also, it'd be helpful if you could share the repository with the code example

**Comment by sw-yx** [comment]
suspect it is amplify's ESM support https://github.com/aws-amplify/amplify-cli/issues/5691

**Comment by EdwinFdoGarcia** [comment]
## He publicado este issues en AWS Amplify [aws-amplify/amplify-cli#5691](https://github.com/aws-amplify/amplify-cli/issues/5691)
