### ISSUE TITLE
Cannot set cookies in the hooks.server.js for redirects

### ISSUE THREAD

**Issue by lemnisk8** [sveltejs/kit#6878]
### Describe the bug

I am unable to set the cookie. The cookie is always undefined. I believe that this is because the event is not returned, but a new response is sent instead. I wanted to to get rid of the extra cookie package. :)

```
 event.cookies.set("foo", "bar");
  return new Response(null, {
     status: 302,
     headers: new Headers({ Location: `/'})
  })
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-frzqi9?file=src/hooks.server.js

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 791.16 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.3.0 - /opt/homebrew/bin/node
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.4
```

### Severity

annoyance

**Comment by s3812497** [comment]
Hi leminsk8, you have to set the cookies directly in the `set-cookies` header.

If I'm not mistaken, you need to call `resolve(event)` for any effects of event to apply.

**Comment by lemnisk8** [comment]
Thanks @s3812497... I thought so too...
