### ISSUE TITLE
Add --host option

### ISSUE THREAD

**Issue by srid** [sveltejs/kit#688]
**Is your feature request related to a problem? Please describe.**
I'd like to expose my dev server to other machines, so wish to bind to 0.0.0.0 and not localhost.

**Describe the solution you'd like**
Add a `--host` option (along side existing `--port` option).

**Describe alternatives you've considered**
Port forwarding is butchered on WSL; don't want to deal with it now.

**How important is this feature to you?**
Somewhat.

**Additional context**

```
node_modules/.bin/svelte-kit dev --help

  Description
    Start a development server

  Usage
    $ svelte-kit dev [options]

  Options
    -p, --port    Port  (default 3000)
    -o, --open    Open a browser tab  (default false)
    -h, --help    Displays this message
```

**Comment by extraordinaire** [comment]
you can get it bound on `0.0.0.0` by editing `svelte.config.cjs` and configuring vite, like so:

```
// svelte.config.cjs

module.exports = {
  kit: {
    vite: {
      server: {
        host: '0.0.0.0'
      }
    }
  }
}
```

All available options are documented here https://vitejs.dev/config/#server-host

**Comment by bjon** [comment]
I think `svelte-kit dev --host fake.domain.com --open` should replace `http://localhost:3000` with `http://fake.domain.com:3000`.

Its good to have, when developing with third party libs, that require a "real" host.

**Comment by babichjacob** [comment]
> 
> 
> you can get it bound on `0.0.0.0` by editing `svelte.config.cjs` and configuring vite, like so:
> 
> ```
> // svelte.config.cjs
> 
> module.exports = {
>   kit: {
>     vite: {
>       server: {
>         host: '0.0.0.0'
>       }
>     }
>   }
> }
> ```
> 
> All available options are documented here https://vitejs.dev/config/#server-host

@srid Can you confirm this helps you achieve your goal?

**Comment by srid** [comment]
Yea, that syntax will work for me too. I don't use svelte at the moment, so can't confirm if that actually works though. If it works, feel free to close this issue.

**Comment by johnyvelho** [comment]
> > you can get it bound on `0.0.0.0` by editing `svelte.config.cjs` and configuring vite, like so:
> > ```
> > // svelte.config.cjs
> > 
> > module.exports = {
> >   kit: {
> >     vite: {
> >       server: {
> >         host: '0.0.0.0'
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > All available options are documented here https://vitejs.dev/config/#server-host
> 
> @srid Can you confirm this helps you achieve your goal?

I tried it and didn't help :/
