### ISSUE TITLE
`App.PageError` should probably be renamed `App.Error`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#6905]
### Describe the bug

...because it also applies to non-page requests (e.g. if you throw an error in `handle` or a `+server.js` file, it will go through `handleError`, and if it's a non-page request it will be turned into a JSON response).

Annoyingly, this _would_ be a breaking change

### Reproduction

N/A

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
If we do this, we could try minimize impact by checking if there's an `src/app.d.ts` and if that contains `PageError` rename that to `Error` during sync.

**Comment by N-NeelPatel** [comment]
@Rich-Harris - I am getting this issue. And there are no instance of PageError in my system. What do you think the issue may be?

**Comment by dummdidumm** [comment]
Does a full-text-search of `PageError` bring something up? If yes, is it inside `app.d.ts`? If yes, rename it there even if it's commented out. That should happen automatically in more recent versions of SvelteKit btw.

**Comment by N-NeelPatel** [comment]
@dummdidumm - It worked. Thanks. BTW why was it causing issue even though it was commented?
