### ISSUE TITLE
`apply_action` should update `page.status`

### ISSUE THREAD

**Issue by dmkret** [sveltejs/kit#6907]
### Describe the bug

https://github.com/sveltejs/kit/blob/a404e63cafc4cac13aa2b4b8bf51574352e8982e/packages/kit/src/runtime/client/client.js#L1205-L1210

`page.status` not updated, so `$page.data` contains irrelevant values.

Example case:
1. return `invalid(400)` from action (status 400) => `$page.status === 400`
2. return `{}` from action (status 200) => `$page.status === 400`

### Reproduction

https://github.com/dmkret/sveltekit-page-status-form-action
https://stackblitz.com/edit/sveltejs-kit-template-default-uahxzt?file=src/routes/+page.svelte

1. Press `Produce 400`. This calls `return invalid(400)`
2. `$page.status` = 400, expected = 400 ✅
3. Press `Produce 200`. This calls `return {}`
4. `$page.status` = 400, **expected = 200** ❌

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 342.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.76 
    @sveltejs/kit: next => 1.0.0-next.488 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.3
```

### Severity

annoyance

### Additional Information

my current workaround without patching sources is to return `invalid` in valid case

```js
export const actions = {
    default: () => {
        // return {}
        return invalid(201, {})
    }
}
```

**Comment by dummdidumm** [comment]
I can't reproduce this given the reproducible, it correctly updates the status for me

**Comment by dmkret** [comment]
@dummdidumm I've also created a fork of [https://node.new/sveltekit](https://node.new/sveltekit):

[https://stackblitz.com/edit/sveltejs-kit-template-default-uahxzt?file=src/routes/+page.svelte](https://stackblitz.com/edit/sveltejs-kit-template-default-uahxzt?file=src/routes/+page.svelte)

The issue is reproducible there.

**Comment by dummdidumm** [comment]
Not sure why I wan't able to reproduce it locally, from looking at the code it probably should be this:
```js

				if (result.status !== page.status) {
					page.status = result.status; // <- page object needs to be updated else subsequent checks are wrong
					props.page = {
						...page
					};
				}
```

**Comment by Conduitry** [comment]
@dummdidumm Could you reproduce this in stackblitz? I could in the provided link, in Firefox.

**Comment by dummdidumm** [comment]
Yes. sry. wasn't clear on that, wasn't able to reproduce it locally earlier, was abel to reproduce it in stackblitz, which made me look at the code one more time and having found the bug (probably).
