### ISSUE TITLE
Respond with status code 413 if request body is too large

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/kit#6920]
### Describe the bug

Yesterday a few people in the discord tried to help someone who got an error 400 upon requesting an endpoint.
We needed almost an hour to find the problem because he only saw "400 Bad request" and not the message of the thrown `Error` (idk why).

If the response status code had been 413, we would have found the issue much earlier.

### Reproduction

Can not reproduce on stackblitz
https://replit.com/@PehGeh/GreenMutedComma
- click on "Upload a large file"

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC 7B12
    Memory: 37.87 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.2.0 - /nix/store/q3hh5viyhr3gvfrn6yakbd59gyna0v05-nodejs-18.2.0/bin/node
    Yarn: 1.22.18 - /nix/store/n7d0ibna8751b6kfj6i4fkanbdix8h7a-yarn-1.22.18/bin/yarn
    npm: 8.9.0 - /nix/store/q3hh5viyhr3gvfrn6yakbd59gyna0v05-nodejs-18.2.0/bin/npm
```

### Severity

annoyance

### Additional Information

https://github.com/sveltejs/kit/blob/ba168b0ff57caeb45a7b3185a97892ce745abec4/packages/adapter-node/src/handler.js#L51-L61

It seems like it would be enough to set the `status` property on the thrown errors to 413.

**Comment by theswerd** [comment]
Can this be disabled/edited on specific routes?
