### ISSUE TITLE
Allow the `routes` folder to be empty 

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#6921]
### Describe the problem

When there are no routes present in the `routes` folder, the following error is thrown: 
```
error when starting dev server:
Error: The filesystem router API has changed, see https://github.com/sveltejs/kit/discussions/5774 for details
    at create_routes_and_nodes (file:///P:/weather-apps-api/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.490_svelte@3.50.1+vite@3.1.3/node_modules/@sveltejs/kit/src/core/sync/create_manifest_data/index.js:229:11)
```

### Describe the proposed solution

Allowing the `routes` folder to be empty (when the `static` folder has content in it?)

### Alternatives considered

 To work around this annoyance, I created an empty `+page.svelte` component in the routes folder.

### Importance

nice to have

**Comment by dummdidumm** [comment]
The solution is probably to check if the folder contains any files at all before throwing the migration error

**Comment by dummdidumm** [comment]
I think the right fix is to not throw the error when the routes folder doesn't exist - if it's empty, why keep it. This should also solve your problem. If there's something in the routes folder, it should be related to routing.

**Comment by UltraCakeBakery** [comment]
@dummdidumm thank you for the quick fix!
