### ISSUE TITLE
getSession not executed on hooks.server.js after page load

### ISSUE THREAD

**Issue by 3daddict** [sveltejs/kit#6957]
### Describe the bug

getSession is not running on page load from the `src/hooks.server.js` file.

### Reproduction

Stackblitz: [https://stackblitz.com/edit/sveltejs-kit-template-default-pmhwgv?file=src/hooks.server.js](https://stackblitz.com/edit/sveltejs-kit-template-default-pmhwgv?file=src/hooks.server.js)

`src/hooks.server.js`
```js
export const getSession = ({ locals }) => {
  console.log("getSession running");
  if (locals.userid) {
    console.log("getSession: user data");
    return { user: locals.userid };
  } else {
    console.log("getSession: return null values");
    return { user: null, token: null };
  }
};
```

### Logs

```shell
10:03:41 PM [vite] page reload src/hooks.server.js (x3)
handle running
handle running
handle running
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 68.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.95
    Chrome: 105.0.5195.125
    Firefox: 104.0.1
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: workspace:* => 1.0.0-next.80 
    @sveltejs/adapter-static: workspace:* => 1.0.0-next.43 
    @sveltejs/amp: workspace:* => 1.0.0-next.1 
    @sveltejs/kit: workspace:* => 1.0.0-next.493 
    @sveltejs/site-kit: ^2.1.2 => 2.1.2 
    svelte: ^3.48.0 => 3.48.0 
    vite: ^3.1.1 => 3.1.1
```

### Severity

blocking an upgrade

### Additional Information

This could just be I am implementing this wrong but I cannot find a way to get this to execute and persist logins for the app I am trying to upgrade to the new version with breaking changes.

**Comment by aloker** [comment]
The concept of sessions does not exist anymore in SvelteKit

https://github.com/sveltejs/kit/pull/5946

Use +layout.server.ts to implement a similar concept
