### ISSUE TITLE
`use:enhance` always targeting `+server.{js|ts}` instead of `+page.server.{js|ts}`

### ISSUE THREAD

**Issue by mustofa-id** [sveltejs/kit#6983]
### Describe the bug

When `+server.{js|ts}` file in the same directory  as `+page.server.{js|ts}` file, the `use:enhance` form action cannot hit form `actions` methods. This is does not following content negotiation [rules](https://kit.svelte.dev/docs/routing#server-content-negotiation) as `use:enhance` always using `accept: 'application/json'` request header.

### Reproduction

https://github.com/mustofa-id/sveltekit-form-enhance-issue

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz     
    Memory: 2.21 GB / 7.90 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.95 => 1.0.0-next.95   
    @sveltejs/kit: 1.0.0-next.499 => 1.0.0-next.499 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.1.1 => 3.1.1
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
It does follow the stated rules, because the `fetch` request does not priority `text/html`, but yeah it still is not ideal in this case.
Question: Does you `+server.js` have a `POST` request or not?

**Comment by Rich-Harris** [comment]
Yeah, I guess we need to add a `x-sveltekit-action: true` header or something for this case to work
