### ISSUE TITLE
Postinstall breaks when `package.json` is missing (for instance on a `pnpm fetch`)

### ISSUE THREAD

**Issue by allezxandre** [sveltejs/kit#6987]
### Describe the bug

It appears #6949 broke `pnpm fetch` when no `package.json` is present.

In the context of a Docker build like the following:

```Dockerfile
FROM node:18 as builder
RUN corepack enable
WORKDIR /workspace
# Step 1
COPY pnpm-lock.yaml ./
RUN pnpm fetch
# Step 2
COPY package.json ./
RUN pnpm install --frozen-lockfile --offline
# [...]
```

where Step 1 can be cached as long as `pnpm-lock.yaml` stays the same, even if `package.json` changes (for instance on a config or script change that does not require package re-install).

But from what I understand it means when `postinstall` is run in `pnpm fetch`, it doesn't have access to a `package.json` file.

### Reproduction

In any SvelteKit repo, create the lock file by running install:

```bash
pnpm install
```

Remove the installed packages and the `package.json` file:

```bash
rm -r node_modules/ package.json
```

Now, running `pnpm fetch` will fail on versions `1.0.0-next.495` onward (Logs provided below).

### Logs

```shell
.../esbuild@0.15.8/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.15.8/node_modules/esbuild postinstall: Done
.../node_modules/@sveltejs/kit postinstall$ node postinstall.js
.../node_modules/@sveltejs/kit postinstall: node:fs:599
.../node_modules/@sveltejs/kit postinstall:   handleErrorFromBinding(ctx);
.../node_modules/@sveltejs/kit postinstall:   ^
.../node_modules/@sveltejs/kit postinstall: Error: ENOENT: no such file or directory, open 'package.json'
.../node_modules/@sveltejs/kit postinstall:     at Object.openSync (node:fs:599:3)
.../node_modules/@sveltejs/kit postinstall:     at Object.readFileSync (node:fs:467:35)
.../node_modules/@sveltejs/kit postinstall:     at file:///workspace/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.499_svelte@3.50.1+vite@3.1.3/node_modules/@sveltejs/kit/postinstall.js:10:27 {
.../node_modules/@sveltejs/kit postinstall:   errno: -2,
.../node_modules/@sveltejs/kit postinstall:   syscall: 'open',
.../node_modules/@sveltejs/kit postinstall:   code: 'ENOENT',
.../node_modules/@sveltejs/kit postinstall:   path: 'package.json'
.../node_modules/@sveltejs/kit postinstall: }
.../node_modules/@sveltejs/kit postinstall: Node.js v18.9.0
.../node_modules/@sveltejs/kit postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
The command '/bin/sh -c pnpm fetch' returned a non-zero code: 1
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 26.52 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.95 => 1.0.0-next.95 
    @sveltejs/kit: 1.0.0-next.499 => 1.0.0-next.499 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.3 => 3.1.3
```

### Severity

annoyance

**Comment by dominikg** [comment]
This is confusing behavior on pnpm's part. 

from https://pnpm.io/cli/fetch
> Fetch packages from a lockfile into virtual store, package manifest is ignored.

That description does not read like it would be calling postinstall hooks.
Maybe it is to populate the "side effects cache", so as a workaround disabling that via npmrc might help https://pnpm.io/npmrc#side-effects-cache

One possible fix for us would be to wrap the postinstall code in a try/catch to ensure it always exits with 0.

**Comment by Conduitry** [comment]
> One possible fix for us would be to wrap the postinstall code in a try/catch to ensure it always exits with 0.

That might be a good idea in general. Since it's just to generate types that would get generated the first time the user ran `dev` or `build` anyway, having the types be missing (perhaps with a quiet warning message) sounds pretty much always better than making the install fail.

**Comment by gaarf** [comment]
install fails for me since #6969 in a monorepo using `turbo` and `yarn`. Here's the error I get:

```
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/2] ⠈ @sveltejs/kit
error /home/user/src/monorepo/node_modules/@sveltejs/kit: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments: 
Directory: /home/user/src/monorepo/node_modules/@sveltejs/kit
Output:
file:///home/user/src/monorepo/node_modules/@sveltejs/kit/postinstall.js:15
	for (const directory of pkg.workspaces) {
	                            ^

TypeError: pkg.workspaces is not iterable
    at file:///home/user/src/monorepo/node_modules/@sveltejs/kit/postinstall.js:15:30
```

my root `package.json` is configured like follows:
```
	"workspaces": {
		"packages": [
			"packages/*"
		]
	},
```

`@sveltejs/kit` is a devDependency in one of the packages.

**Comment by Rich-Harris** [comment]
@gaarf When is `workspaces` not an array of strings? I can't find any examples of that anywhere. This is [Yarn's documentation](https://classic.yarnpkg.com/lang/en/docs/workspaces/)...

<img width="796" alt="image" src="https://user-images.githubusercontent.com/1162160/192029361-49602f01-8a0f-426e-8901-07d2259402a7.png">

...and this is [Turborepo's](https://turborepo.org/docs/getting-started/existing-monorepo):

<img width="865" alt="image" src="https://user-images.githubusercontent.com/1162160/192029388-b823adbc-75d1-4b47-8603-0909cc7bb863.png">

**Comment by Rich-Harris** [comment]
On second thoughts @gaarf can you create a new issue for this please? It doesn't belong in this one, which is about not running postinstall when `package.json` is missing

**Comment by gaarf** [comment]
@Rich-Harris will do. I changed our `workspaces` to an array in my project to solve the install failure issue, did not seem to matter in this project. Others may be affected tho, here's a reference to the pattern: https://classic.yarnpkg.com/blog/2018/02/15/nohoist/

**Comment by Rich-Harris** [comment]
Ah, gotcha. I added handling for that case in #6998
