### ISSUE TITLE
Handle file uploads

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#70]
Currently, the body parser bails on multipart forms that include files

**Comment by benmccann** [comment]
It looks like the way you'd do this in Sapper is to add something like [Multer](https://www.npmjs.com/package/multer) or [Formidable](https://www.npmjs.com/package/formidable) as a middleware which would parse the incoming request and stick the files on the request object. Probably the way to do this would be to expose a way to add middleware, so that users can utilize these packages, so I wonder if this is essentially a duplicate of https://github.com/sveltejs/kit/issues/334. (side note, I wonder if we should have `adapter-polka` and `adapter-express` instead of `adapter-node`)

I was trying to figure out how Netlify, Lambda, etc. handle this. All the examples I see directly upload to S3 from the browser. I couldn't find how you'd handle a form upload inside a Lambda, so I guess that's something that's generally not supported

**Comment by thgh** [comment]
Here is an example of file uploads to lambda: https://github.com/mpxr/lambda-file-upload/blob/master/handler.js

I may be biased, but I think serverless APIs typically don't use global middleware and instead have several awaits (one per middleware) at the start of the function. See https://nextjs.org/docs/api-routes/api-middlewares#connectexpress-middleware-support

**Comment by asos-tomp** [comment]
For what it's worth, confirmed that this was working fine with sapper + [Formidable](https://www.npmjs.com/package/formidable) but not working with sveltekit.

**Comment by axmad386** [comment]
I think hooks is enough for handling Middleware, except the request (ServerRequest) is little bit different from polka or express. Multer require request.pipe and unpipe to handle File Upload. Formidable require request.on which is missing from request object on handle hooks. Cmiiw

**Comment by benmccann** [comment]
You'd have to convert from SvelteKit request to Express request first before calling the middleware

**Comment by axmad386** [comment]
> You'd have to convert from SvelteKit request to Express request first before calling the middleware

That's exactly I want, but how. Any references?

**Comment by vonadz** [comment]
Would it be possible to comment out this section in kit/src/runtime/server/parse_body/index.js:1413
`
if (directives.filename) {
  //TODO we probably don't want to do this automatically
  throw new Error('File upload is not yet implemented');
}`
for now? This will give users the chance to implement their own solutions in the handle hook.

**Comment by MTyson** [comment]
I just did this in Sapper, and I'll throw out my thoughts in case it might help.

I used [formidable ](https://www.npmjs.com/package/formidable )and [filepond](https://pqina.nl/filepond/).  Filepond sends the chunks, and I used formidable to write a temp file to disk (via node fs).  Upon submitting the form, a unique id is used to retrieve the file and write it to its permanent home (mongodb in this case).

In a pure serverless environment, you could override formidable and handle the chunks yourself, writing them to memory, and do the same process. (This assumes we can import formidable into sveltekit).

In the end, there should be a simple way to interact with the filesystem if there is one at hand.

**Comment by vonadz** [comment]
> I just did this in Sapper, and I'll throw out my thoughts in case it might help.
> 
> I used [formidable ](https://www.npmjs.com/package/formidable)and [filepond](https://pqina.nl/filepond/). Filepond sends the chunks, and I used formidable to write a temp file to disk (via node fs). Upon submitting the form, a unique id is used to retrieve the file and write it to its permanent home (mongodb in this case).
> 
> In a pure serverless environment, you could override formidable and handle the chunks yourself, writing them to memory, and do the same process. (This assumes we can import formidable into sveltekit).
> 
> In the end, there should be a simple way to interact with the filesystem if there is one at hand.

Yeah I played around with using formidable, but I don't think it's a very nice solution. From my understanding, the handle hook would be the natural place for handling fileupload. The issue is that the request in the handle hook isn't a stream of chunks, like is normally expected for something like formidable or express-fileupload, but an object with a rawBody that is the complete stream in string format. The reason I was using busboy is because it can parse out form data out of a string, both fields and files.

**Comment by juanmait** [comment]
> > handle hook isn't a stream of chunks
> 
> Interesting. So something in sveltekit itself is handling the chunks and marshalling them into a string of bits?
> 
> I wonder if that could pose a limitation in cases where one wanted to stream the chunks directly to a datastore...?

I'm just looking for that. I'm working with streaming in the browser side and now reached the point of wanting to stream the result of the client pipeline to the server. Seems like there is no way to access the raw request in sveltekit endpoints. I was planning to use cloudflare workers but first giving it a try using nodejs. 

I would vote for having a way to access the plain raw request object on whatever the platform you use. I guess this would be the job of every adapter.

**Comment by avhust** [comment]
plain/text Content-Type allows to send data (e.g base64 coded image).
I use this code with SvelteKit to upload images:
```javascript
// <input type="file" bind:files>
const getBase64 = (image) => {
	const reader = new FileReader();
	reader.onload = (e) => {
		uploadImage(e.target.result);
	};
	reader.readAsDataURL(image);
};
const uploadFunction = async (imgBase64) => {
	const imgData = imgBase64.split(',');
	await fetch(`/api/upload`, {
		method: 'POST',
		headers: {
			'Content-Type': 'text/plain',
			Accept: 'application/json'
		},
		body: imgData[1]
	});
};
getBase64(file[0]);
```

and in hook.ts to capture the image and process with sharp:

```typescript
export const handle: Handle = async ({ request, render }) => {
	//...
	// Upload Image
	if (request.path === '/api/upload' && request.method === 'POST') {
		const imageName = 'some.webp';
		try {
			await sharp(Buffer.from(request.rawBody, 'base64'))
				.rotate()
				.resize({ width: 200, height: 200 })
				.webp()
				.toFile(`./${imageName}`);
		} catch (err) {
			console.log(err);
		}
		return {
			status: 201,
			body: JSON.stringify({
				src: imageName
			}),
			headers: {
				'Content-Type': 'application/json'
			}
		};
	}
	// ...
};

```

**Comment by juanmait** [comment]
@avhust It's a good solution for relatively small uploads. But if you're dealing with sizes in the range of the gigabytes its like you cannot afford to fill the whole `rawBody` especially in an environment like vercel or cloudflare. Streaming allows you to start processing the data as soon as it start coming in and you can kind of control the memory usage and also even pause the stream to also control the CPU usage.
I guess I could use some sort of proxy to redirect uploads to something outside sveltekit, or use CORS. But is an inconvenience :sweat_smile:

**Comment by MTyson** [comment]
It would seem strange to have the client-side content type dictated by the framework.  Feels like a workaround right out the box.

**Comment by geoidesic** [comment]
https://github.com/mscdex/busboy ftw! @vonadz any luck with this yet?

**Comment by vonadz** [comment]
> https://github.com/mscdex/busboy ftw! @vonadz any luck with this yet?

Nope. I just decided to use an external service (transloadit) to handle my file uploads for me. It made more sense for my use case anyway.

**Comment by geoidesic** [comment]
@avhust I tried your work-around but I still get the dreaded `Error: File upload is not yet implemented
` response. Doesn't seem to trigger any `console.log`s in the `hooks.ts` file, so I'm not convinced it's even getting that far.

**Comment by avhust** [comment]
@geoidesic Looks like you doesn't use 'Content-Type': 'text/plain' in your POST request.

**Comment by UltraCakeBakery** [comment]
As I am writing this I'm filling up my production svelte-kit server's error log budget... Svelte kit throws / logs an error, even after build. It is also annoying to work around the endpoint forcing a 500 error. Can't instead a developer warning be thrown instead with the formdata entry being set to a value of null? I have some security concerns and shitty developer experience because of this lol

**Comment by joelhickok** [comment]
I'm using the solution provided by @avhust for now.  Can't wait until sveltejs/kit supports better server-side customizations and middleware.  It's kind of a handicapped tool at this point, powerful as it is.  Yes, I understand it's still under development.

My example uses .xlsx instead of an image.  This works fine without using the `text/plain` Content-Type.

```js
// client side code
const reader = new FileReader()

reader.onload = async (e) => {
    const file = e.target.result.split(',')

    const response = await request.post('/upload.json', file[1], {
        params: {
            filename: encodeURIComponent('file.xlsx'), // just to pass in the actual filename to use
        },
    }).catch(err => err)
}

reader.readAsDataURL(fileInput.files[0])

// hooks.js or .ts
export async function handle({ request, resolve }) {
    if (request.path === '/upload.json' && request.method === 'POST') {
        const filename = request.query.get('filename')
        try {
            // this example show use for a file such as .xlsx instead of the previous example
            // using sharp for an image
            fs.writeFileSync(`static/uploads/${filename}`, request.rawBody, { encoding: 'base64' })
            // file now available for use in local upload path, so create additional logic elsewhere
        } catch (err) {
            console.log(err)
        }
    }

    const response = await resolve(request)

    return {
        ...response,
        headers: {
            ...response.headers,
        }
    }

}

// upload.json.js
export async function post(req) {
    console.log(`HANDLER: ${req.path}`)
    try {
        // do something else, or just return a response letting
        // the client know the upload went okay

        return {
            body: {
                success: true,
                filename: req.query.get('filename'),
            },
        }
    } catch (err) {
        return {
            body: err.message
        }
    }
}
```

**Comment by benmccann** [comment]
We're soon going to have the ability to add middleware in `adapter-node` (https://github.com/sveltejs/kit/pull/2051). Users can also do file uploads to S3, etc. on the serverless platforms. That seems like it should basically solve this

**Comment by benbender** [comment]
@benmccann I'm sorry, but I tend to disagree. Uploads are an essential part of the web - and of HTML-Spec. If we consider this issue closed, I'm basically forced to do either one of two things - in even mild usecases - where the endpoint-concept of sveltekit might by totally fine otherwise:

- replicate my db-setup, form-handling, etc outside of sveltekit in a middleware as I normally need to handle/save the resulting filename, path, etc somewhere
- pay a service to do it externally for me with possibly attached concerns about cost, privacy, gdpr etc (yaeh I know, most of them start for free, but you get the point...) 

Tbh, I don't get the notion transported in handling this issue. If I argue that external, specialized services do things better and I, as a dev, shouldn't do them therefor myself, we could skip many of the features of sveltekit and basically provide a linklist to 3rd-party, paid, specialized services in many cases...

**Comment by benmccann** [comment]
> I don't get why I have to sacrifice on adapter-node, where the apis are right in front of me but I'm not allowed to grab them
> To me, it should expose as much of http.ClientRequest/http.ServerResponse as the platform, sveltekit runs on, offers - at least as an optIn (in cost of interoperability - but if I need it, I am able to leverage the power which is given to me by the platform) in addition to a guaranteed subset of interoperable apis.

I'm not sure what you mean by this. We will be exposing `adapter-node` so that you can customize it 100% including any middleware to do things like handle file uploads (https://github.com/sveltejs/kit/pull/2051). That sounds to me like exactly what you're asking for. Or is there something else you mean?

Though I did realize that multer will stick the uploaded files on `request.files`, so we'll need to make sure there's a way to get at that before 1.0

**Comment by joelhickok** [comment]
Is the middleware in adapter-node only going to work in builds, or will it work in dev mode?

**Comment by benbender** [comment]
> I'm not sure what you mean by this. We will be exposing `adapter-node` so that you can customize it 100% including any middleware to do things like handle file uploads (#2051). That sounds to me like exactly what you're asking for. Or is there something else you mean?
> 
> Though I did realize that multer will stick the uploaded files on `request.files`, so we'll need to make sure there's a way to get at that before 1.0

Your example pinpoints my direct problem quite exactly. As of now I expected that those middlewares will be basically living in there own silo and I won't have access to the (modified) "real" request/response-objects within hooks/endpoints. So even if I have full access to request/response in the middleware, there is no proprietary "communication-channel" into my app. Or am I missing something?

But even if there is such a concept to deliver possible changes from a middleware into my app the "cutback of possibilities" because of the missing access to clientRequst/serverResponse still exists and cripples the power of adapter-node quite a bit...

**Comment by benmccann** [comment]
> Is the middleware in adapter-node only going to work in builds, or will it work in dev mode?

That's a very good point. Thank you for raising it. The current open PR does not address that, but there is an open issue on the 1.0 milestone to do that, which we will also need to address: https://github.com/sveltejs/kit/issues/1779. I will take it into consideration when reviewing the open PR as well to make sure we have a plan to address it

> I won't have access to the (modified) "real" request/response-objects within hooks/endpoints

Assuming that by "real" you mean the Express versions, I was basically agreeing that we will need a way to handle that in my last comment

**Comment by benbender** [comment]
> Assuming that by "real" you mean the Express versions, I was basically agreeing that we will need a way to handle that in my last comment

More like the ones from https://nodejs.org/api/http.html - but  🥳 😄

**Comment by adam314315** [comment]
@vonadz @geoidesic Hello,

Finally succeeded to implement your method with the help of this post https://stackoverflow.com/questions/66807052/utf-8-encoded-string-to-buffer-node-js on issue generated with UTF-8 encoding. You need to cancel utf8 encoding in adapter-node as below. Then it will fix the corrupt file issue.

in @sveltejs/adapter-node/files/index.js

```
 if (isContentTypeTextual(type)) {
         const encoding = h['content-encoding'] || 'utf-8';
         return fulfil(data);
         //return fulfil(new TextDecoder(encoding).decode(data));
   }
```

**Comment by meticoeus** [comment]
@benmccann Chiming in with a serverless use case. I'm currently building a specialized app that will be running on Vercel (serverless) but I would still like to handle file uploads directly. This app will have only a small user base and has a strict allowed file uploads policy and I don't want to add the complexity of using S3 for this (Files are stored in a service that isn't very upload-from-client friendly). Uploads are limited to less than 1MB on the client so I don't expect any problems for the lambda runtime. Direct to S3 makes plenty of sense if you need to support large files. It just adds a lot of hassle if you don't really need it.

It would be great if sveltekit considered providing a well documented mechanism for gaining access to the raw request/response of whatever platform it is running on or some other way to handle raw requests at least for those of us with non-standard use cases.

For now I'm going to be uploading base64 strings but this bloats processing time and bandwidth transfer.

Also, really loving Svelte development compared to React so far. It is so much easier to deal with most things so far without a ton of annoying performance workarounds.

**Comment by benmccann** [comment]
@meticoeus I have a PR pending to allow access to the raw request of whatever platform is being used. See https://github.com/sveltejs/kit/pull/2359

**Comment by meticoeus** [comment]
@benmccann With the recent close of #2359 and the new discussion #2426 to add props to `locals` is support for getting access to  the raw request body in anything other that adapter-node still be considered?

**Comment by benmccann** [comment]
Whatever we do will work for all platforms and not just Node. I still need to sync up with Rich about design of https://github.com/sveltejs/kit/issues/2426

**Comment by mithlesh425** [comment]
Community, any update on this issue / any working workaround as of now? Please let us know!

**Comment by jack-y** [comment]
My solution, for those who use `adapter-node`. 

First, adds an upload plugin in the vite options of the `svelte.config.js` file:
```
// vite options
vite: {
    plugins: [{
        name: 'upload-middleware',
        configureServer (server) {
            server.middlewares.use(((req, res, next) => {
                if (req.url.startsWith('/upload')) {
                    /* Uploads the files here.
                     In this example, the "uploadFiles" function returns a Promise.
                     To retrieve the separate parts of the FormData,
                     the "uploadFiles" function uses the "busboy" package.
                     If you need, I can give you a full example.
                     */
                    uploadFiles(req)
                    .then(() => {
                        res.writeHead(200, {
                            'Content-Type': 'text/plain'
                        });
                        return res.end('ok');
                    })
                    .catch(err => {
                        res.writeHead(500, {
                            'Content-Type': 'text/plain'
                        });
                        return res.end('upload plugin error: ' + err);
                    });
                } else {
                    next();
                }
            }));
    }],
    ...
},
```

Then, in the application:
```
/* Assuming the "fileToUpload" variable is the File object of the multipart form */
const filepath = "your-file-path-and-name-on-disk";
/* Creates the form data */
let formData = new FormData();
/* Size must be the first part */
formData.append('size', fileToUpload.size);
/* Others parts */
formData.append('file', fileToUpload);
formData.append('filepath', filepath);
formData.append('mimeType', fileToUpload.mimeType); // could be used in a type control server side
/* Calls the process on the server */
fetch('upload', {
    method: 'POST',
    body: formData
    /* Don't set the Content-Type header.
     See: https://muffinman.io/blog/uploading-files-using-fetch-multipart-form-data/ 
     */
})
/* Handles the response */
.then(res => {
    if (!res.ok) { // the response has a bad status (500..)
        throw new Error('upload error status ' + res.status + ', status text: ' + res.statusText);
    } else {
        /* Do something when the file is uploaded */
    }
})
.catch(err => {
    /* Do something with the error */
});
```
Hope it helps.

**Comment by sebamon** [comment]
jack-y  can u show the upload.js or ts file? i cant upload file to the server side.
Thanks u!

**Comment by jack-y** [comment]
OK, here is a full example repository: [svelte-kit-file-upload](https://github.com/jack-y/svelte-kit-file-upload).  
Have fun!

**Comment by yanick** [comment]
> OK, here is a full example repository: [svelte-kit-file-upload](https://github.com/jack-y/svelte-kit-file-upload). Have fun!

Awesome! For giggles I cloned the repo and made a variation that uses multer and Uppy. So far, it works pretty darn good -- https://github.com/yanick/svelte-kit-file-upload

**Comment by sebamon** [comment]
Thank both! we can upload files now!

**Comment by vonadz** [comment]
Do the above solutions actually work when you export the project though? I vaguely remember when trying to solve this issue, I ran into the problem that the adapter-node and/or other adapters actually had to be adjusted as well.

**Comment by yanick** [comment]
> Do the above solutions actually work when you export the project for production though?

Darn it, it doesn't. :-( dev mode is all peachy, but in the build mode I still get the 'File Upload is not yet implemented'. Bummer.

**Comment by vonadz** [comment]
> 

Yeah, I figured. You'll have to make appropriate adjustments in the adapter-node package as well, which isn't that bad. The reason I stopped pursuing this though is because you'd also have to make adjustments in the other adapters, and I wasn't comfortable with serverless envs at the time.

**Comment by jack-y** [comment]
Arghhh !    
@vonadz Please, what adjustments are necessary in the adapter-node package?

**Comment by yanick** [comment]
The secret lies in the docs of https://github.com/sveltejs/kit/tree/master/packages/adapter-node  

I've updated my example. The key is the file `src/server.mjs`, which is the entry point for the prod server.

**Comment by vonadz** [comment]
> The secret lies in the docs of https://github.com/sveltejs/kit/tree/master/packages/adapter-node
> 
> I've updated [my example](https://github.com/yanick/svelte-kit-file-upload). The key is the file `src/server.mjs`, which is the entry point for the prod server.

Oh yeah the whole middleware section is a new update since I last tried implementing this, which substantially simplifies things.

**Comment by jack-y** [comment]
@yanick Great job! Thank you so much. I've updated [my repo](https://github.com/jack-y/svelte-kit-file-upload) too.    
    
FYI, I tried with fastify instead of polka, but without success.    
As the doc says: "The adapter exports a middleware (req, res, next) => {} that's compatible with Express / Connect / Polka."

**Comment by m4tr1k** [comment]
Hi everyone!

So I came across this problem as well, since I needed a way to have access to the file on sveltekit endpoint, but I didn't want to use the above solutions using `adapter-node` because of my backend implementation.
So I decided to rewrite the `get-multipart` function to support file uploading. I used a dependency ([parse-multipart-data](https://github.com/nachomazzara/parse-multipart-data) to parse the multipart form data request, and then I just had to present that information in a different way.

That's my implementation:

```javascript
import multipart from 'parse-multipart-data';

(...)

function parse_body(raw, headers) {
	         (...)
		case 'multipart/form-data': {
			const boundary = directives.find((directive) => directive.startsWith('boundary='));
			if (!boundary) throw new Error('Missing boundary');
                         // I added the raw body request to use it in parse-multipart-data
			return get_multipart(text(), boundary.slice('boundary='.length), raw);
		}
}

(...)

function get_multipart(text, boundary, raw) {
	let data = {};
	const parts = text.split(`--${boundary}`);

	if (parts[0] !== '' || parts[parts.length - 1].trim() !== '--') {
		throw new Error('Malformed form data');
	}


	let names = [];
	parts.slice(1, -1).forEach((part) => {
		const match = /\s*([\s\S]+?)\r\n\r\n([\s\S]*)\s*/.exec(part);
		if (!match) {
			throw new Error('Malformed form data');
		}
		const raw_headers = match[1];
		raw_headers.split('\r\n').forEach((str) => {
			const [raw_header, ...raw_directives] = str.split('; ');
			let [name, value] = raw_header.split(': ');

			name = name.toLowerCase();

			/** @type {Record<string, string>} */
			const directives = {};
			raw_directives.forEach((raw_directive) => {
				const [name, value] = raw_directive.split('=');
				directives[name] = JSON.parse(value);
			});

			if (name === 'content-disposition') {
				if (value !== 'form-data') throw new Error('Malformed form data');

				if (directives.name) {
					names = [...names, directives.name];
				}
			}
		});
	});

	const bodyParts = multipart.parse(raw, boundary);

	for(let i = 0; i < bodyParts.length; i++) {
		const bodyPart = bodyParts[i];
		if(!bodyPart.type){
			data[names[i]] = bodyPart.data.toString();
		} else {
			data[names[i]] = {
				data: bodyPart.data,
				type: bodyPart.type
			};
		}
	}

	return data;
}
```
Please keep in mind that I'm aware that this may not be the smartest and most effective way to do this (because you can see that I did not erase a part of the code and probably there are more elegant ways to do this), but as a small fix until the full implementation is fully done I think it is a pretty good solution. I would like to know your opinion on this as well. 

Thanks 😄

**Comment by KrustyC** [comment]
I am running into the same issue and I am just wondering what's the latest on this? Is this going to be part of release 1.0? If not, is there any estimate about when this will be made available? I think it's an important feature and a very common use case (as proven from all the comments above). I would be happy to help if possible, although I have never worked with the svelte-kit codebase before

**Comment by m4tr1k** [comment]
@KrustyC hey, check out my solution right above your comment. I developed a way to be able to access the files on Svelte endpoints. Hope it helps!

**Comment by simonjcarr** [comment]
I have been playing around with sveltekit for about 3 weeks and have fallen in love with it. The thing that just blew me away was being able to integrate the API and GUI in one codebase. Then today I found that it does not support middleware or file uploads. I suppose I could just accept this and set up a dedicated API in Adonis etc, but then I am not sure that the other features I love in svelte are enough for me to make the move away from VueJS. I already tried Svelte a year ago and thought I would give it another year to mature and come back to it. I think I will have to do the same again and see if the middleware/file uploads gap ("gap" is my opinion only) has been filled.

**Comment by Rich-Harris** [comment]
# RFC

Prompted by #3086 (thanks @pixelmund), I've spent some time thinking about how we should rethink request body handling to enable both file uploads and other large bodies. I'd be grateful for feedback on the following:

* if the request's `content-type` is `text/*` or `application/json`, keep the existing behaviour (i.e. `request.body` contains text or a parsed JSON object)
* if the request's `content-type` is `application/x-www-form-urlencoded` or `multipart/form-data`, `request.body` is an async iterable, each of whose values represents one of the form values and is _also_ an async iterable, whose values correspond to the actual data:

    ```js
    export async function post({ body }) {
      for await (const entry of body) {
        console.log(`receiving ${entry.name}`);
        for (const chunk of entry) {
          console.log(`received ${chunk.length} bytes of data`);
        }
      }

      return {
        status: 201
      };
    }
    ```

    It would be great if we could keep the existing behaviour for `application/x-www-form-urlencoded`, but we can't, because in their infinite wisdom the web's architects decided that a regular form submission should have that content type, but a `fetch` with the exact same data (i.e. `body: new FormData(event.target)`) will have a `multipart/form-data` content type. In order for endpoints to behave the same way with JS-triggered form submissions as JS-less ones, we need to have consistent behaviour.

    We could recover some of the lost convenience by exposing a `body.toFormData()` method:

    ```diff
    // src/routes/multiply.js
    export async function post({ body }) {
    - const a = +body.get('a');
    - const b = +body.get('b');
    + const data = await body.toFormData();
    + const a = +data.get('a');
    + const b = +data.get('b');

      return {
        status: 200,
        body: a * b
      };
    }
    ```

    (In the Lambda case, where the body is already buffered, this might seem like more work than is necessary, but there's a lot of value in having a consistent interface.)
* Finally, for all other cases (`application/octet-stream`, `image/*` and so on) we can expose the raw data as an async iterable:
    ```js
    // src/routes/upload-image.js
    import { appendFileSync } from 'fs'; // purely for demo purposes
    import { v4 as uuid } from '@lukeed/uuid';

    export async function post({ headers, body }) {
      if (headers['content-type'] !== 'image/jpeg') {
        return {
          status: 400,
          body: 'expected a JPEG'
        };
      }

      const id = uuid();
      const file = `static/__images/${id}.jpg`;

      for await (const chunk of body) {
        appendFileSync(file, chunk);
      }

      return {
        status: 307,
        location: `/view/${id}`
      };
    }
    ```

**This would, of course, be a breaking change.** We'd also need to figure out what to do about `rawBody`, which we currently expose for use cases like #831. I think the logical choice here would be to make it available for text/JSON bodies, but otherwise have it be `null`.

**Comment by thgh** [comment]
How about using the standard [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) object?

```diff
// src/routes/multiply.js
- export async function post({ body }) {
- const data = await body.toFormData();
+ export async function post(req: Request) {
+ const data = await req.formData();
const a = +data.get('a');
const b = +data.get('b');

  return {
    status: 200,
    body: a * b
  };
}
```

**Comment by maxicarlos08** [comment]
That doesn't exist in Nodejs as far as I know...

**Comment by thgh** [comment]
> That doesn't exist in Nodejs as far as I know...

The node adapter depends on [node-fetch](https://github.com/sveltejs/kit/blob/43b0f5ab3157ce9fdfc5daadc893403513229f7e/packages/adapter-node/package.json#L42).
And node-fetch seems to have the [formData](https://github.com/node-fetch/node-fetch/blob/3944f24770b442e519eaff758adffc9ca0092bdb/%40types/index.d.ts#L121) method.

So this should work:

```ts
import { Request } from 'node-fetch'

const data: FormData = await new Request(url, { headers, body }).formData();
const file: File = data.get('file-input')
console.log(file.name)
console.log(file.size)
console.log(file.type)
```

**Comment by Rich-Harris** [comment]
@thgh I've thought about it. There _is_ something nice about aligning with the platform. But it risks being a straitjacket, and I think we can provide better ergonomics when it comes to streaming. Glossing over the fact that `params` and `locals` need to be present in the argument signature, this is how you'd process an octet stream using `Request`...

```js
export async function post(req) {
  const reader = req.body.getReader();

  let chunk;
  while (chunk = await reader.read()) {
    if (chunk.done) {
      return {
        status: 204
      };
    }

    await do_something_with(chunk.value);
  }
}
```

...versus the proposal:

```js
export async function post({ body }) {
  for await (const chunk of body) {
    await do_something_with(chunk.value);
  }

  return {
    status: 204
  };
}
```

For forms with files (where we want to handle things in streaming fashion, i.e. `formData()` is a non-starter), it gets much more complicated; we'd need to provide a helper of some kind that would turn `Request` into an iterable-of-iterables as above (or a stream-of-streams, if we wanted to do things that way, but I think this is a case where language > platform).

Even for trivial cases, it's an extra hoop to jump through — if the content-type is `application/json` then calling `await req.json()` feels like busywork.

> That doesn't exist in Nodejs as far as I know...

That's not a problem, it's provided in SvelteKit (either by the environment, if you're using Deno etc, or the adapter if you're using Node). But it is true that we'd be creating a `Request` object ourselves, which feels like unnecessary overhead.

**Comment by Rich-Harris** [comment]
> So this should work:
> 
> ```ts
> import { Request } from 'node-fetch'
> 
> const data: FormData = await new Request(url, { headers, body }).formData();
> const file: File = data.get('file-input')
> console.log(file.name)
> console.log(file.size)
> console.log(file.type)
> ```

Unfortunately this assumes that the body is already buffered

**Comment by darbymanning** [comment]
Sorry if a tad off-topic - but whilst processing files in requests for endpoints isn’t available yet, is it possible to add a platform specific serverless function, that’s handled by the provider? eg. A platform specific endpoint not managed through SvelteKit (in my case a Vercel Serverless function). I haven’t checked but I assume they can support formdata being provided. I love the platform agnostic approach SK has, but as a temporary solution perhaps that could work until we have support in SK endpoints.

Alternative to this I guess is making a whole separate app/site in Vercel which is ‘vanilla’, purely to create the serverless function. None are great solutions, but I do kinda need the functionality!

**Comment by yanick** [comment]
Just to drop info to prevent some teeth-gnashing: the latest node-adapter versions renamed the produced `middleware.js` to `handler.js`. I'll try to update my example repo to reflect that soon. (@jack-y, that might be of interest to you too)

:heart:

**Comment by jack-y** [comment]
@yanick, thank you so much for letting me know! My example repo is also updated.

**Comment by jack-y** [comment]
I just created an [example repo using FileReader](https://github.com/jack-y/svelte-kit-file-upload-reader) and an endpoint. No FormData.     
Beware: this IS NOT a solution for the [initial issue](https://github.com/sveltejs/kit/issues/70#issue-730922116). It's just a workaround that might help.

**Comment by benmccann** [comment]
@Rich-Harris your suggestions look pretty reasonable to me. The only question in my mind would be making sure we nail down the streaming API, which this seems to build on top of. There were some interesting use cases in that thread, so we might want to check if we can [handle cancellation](https://github.com/sveltejs/kit/issues/1563#issuecomment-906536251) or [jump around a video stream](https://github.com/sveltejs/kit/issues/1563#issuecomment-921225044). The streaming portion is not my area of expertise, but the changes to the form API here look good to me.

**Comment by quentincaffeino** [comment]
@Rich-Harris 

> if the request's content-type is text/* or application/json, keep the existing behaviour (i.e. request.body contains text or a parsed JSON object)
> if the request's content-type is application/x-www-form-urlencoded or multipart/form-data, request.body is an async iterable, each of whose values represents one of the form values and is also an async iterable, whose values correspond to the actual data:

I don't really like having it hard-coded like that.

For example from personal experience with JSON I see two reasons why streaming might be useful:

1. Processing large JSON inputs, this just isn't possible with regular JSON.parse or res.json. Yes having big jsons is very niche, but asynchronous parsing could speedup some apps.
2. Semantic Web and JsonLD. This one is even more niche. One can parse JsonLD string into JS object with proxies of linked data. Problem is not every client sets the correct header. Since it's still a json many just use regular `application/json` instead of `application/ld+json`.

There most definitely other cases that I am missing. But generally speaking my point is that streaming any of the types of data could be useful.

My proposal would be and I believe I haven't seen this yet: is to leave it as is by default and export config object (or separate properties) from the endpoint, similar to how it's done on `.svelte` files (eg.: `<svelte:options accessors={true}/>`).

I imagine it looking something like this:

```js
export const postConfig = {
	body: "default" | "raw" | "stream"
};
```

Reason I believe it is better to use an object is because this would allow other extensions to the config in the future (middlewares?).

Hope my idea isn't to crazy.

**Comment by Rich-Harris** [comment]
@benmccann 

> There were some interesting use cases in that thread, so we might want to check if we can [handle cancellation](https://github.com/sveltejs/kit/issues/1563#issuecomment-906536251) or [jump around a video stream](https://github.com/sveltejs/kit/issues/1563#issuecomment-921225044).

#1563 is about responses rather than requests, so the issues are related but different. Reading through it, I _am_ warming to the idea of supporting `ReadableStream` responses directly. Firstly, as the issue points out, it gives us an avenue for cancellation:

```js
return {
  status: 200,
  body: new ReadableStream({
    start(controller) {
      // streaming logic goes here
    },
    cancel() {
      // cleanup goes here
    }
  })
};
```

Achieving the same thing with async iterables would involve some contortions.

Secondly, with a minor change — allowing `headers` to be a `Headers` object rather than a POJO — we would get support for this for free, which would make it incredibly easy to proxy to external sites and APIs:

```js
export const get = ({ url }) => fetch('https://en.wikipedia.org' + url.pathname);
```

I _think_ this fetch would be cancellable by the underlying platform (`res.body.cancel()`) even if we don't pass in an `AbortSignal`? (I'm not particularly well versed on this.)

Thirdly, it means less work, since we wouldn't need to convert the iterable to a `ReadableStream` in order to pass the response to platforms that expect `Response` objects, like Cloudflare Workers and Deno. ([This might even save SvelteKit users money, in some cases.](https://blog.cloudflare.com/workers-optimization-reduces-your-bill/))

Of course, this involves a change to the contract between adapters and Kit. If `app.render` returns a `Response`, we can delete some code from `adapter-cloudflare`, but Node- and lambda-shaped adapters would need to do some more work to pipe a `ReadableStream` to a Node `res` or buffer it for a lambda return value (Kit can expose helpers for doing that), and `adapter-node` would need to listen for `req.on('close')` to cancel the body.

Given all the above it might seem odd to still favour async iterables for _request_ bodies, but I do — I think the ergonomics for consuming versus producing streams are sufficiently different, and cancellation is easier to model (if the requester cancels `for await (const chunk of body)` can throw; the endpoint could proactively cancel the request by returning). 

---

Re video streams — the endpoint will always need to handle `Range` headers, Kit can't do that for you.

---

@quentincaffeino 

> My proposal would be and I believe I haven't seen this yet: is to leave it as is by default and export config object (or separate properties) from the endpoint

I like this. I think that's probably a separate conversation as the configuration could take many forms, and it's something that could be implemented after we've nailed the basics of streamed requests/responses.

**Comment by Rich-Harris** [comment]
It's now possible to upload files, as long as they're not large: #3384.

Handling streams is still a TODO, but there's an issue for it. Closing this in favour of #3419

**Comment by Aide-nuts** [comment]
Answer unearthed https://stackdev.space/questions/tips-on-extracting-image-data-from-filepond
