### ISSUE TITLE
Let app on Vercel preview URLs access external API server

### ISSUE THREAD

**Issue by mikenikles** [sveltejs/kit#7005]
### Describe the problem

I've got the following architecture:

**Production**
* API server: https://api.mydomain.com
* SvelteKit app: https://app.mydomain.com

**PR previews**
* API server: https://staging.mydomain.com 
* SvelteKit app: https://webapp-xyz-mydomain.vercel.app

I can send cookies in the production setup just fine (see _Credentials_ in the [docs](https://kit.svelte.dev/docs/hooks#server-hooks-handlefetch)).

However, due to [this code](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/page/fetch.js#L84), the SvelteKit app that runs on Vercel preview URLs can't send (authentication) cookies to the API server.

I've given this quite a bit of thought, but can't think of a workaround to make this work. Does anyone have ideas on how to let a SvelteKit app on Vercel preview URLs access an external API server?

### Describe the proposed solution

I would like to see a configuration option to whitelist domains so they receive cookies even if it violates the same-origin policy.

### Alternatives considered

I haven't tried yet because it feels hacky, but a possible alternative is to have a SvelteKit endpoint (`+server.js`) and use that as a pass-through for all requests in Vercel PR preview environments.

I'd abstract all `fetch()` calls and route to either https://api.mydomain.com in prod or https://webapp-xyz-mydomain.vercel.app/api-passthrough in Vercel PR preview environments. The `/api-passthrough` endpoint would receive all cookies (default SvelteKit behaviour) and could forward the request to https://staging.mydomain.com.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
If the cookies exist only on `.mydomain.com` and aren't even being sent to your staging server at all, then no, your staging server can't be configured to forward them along because there's nothing for it to forward. You can't just tell browsers to please send cookies to domains they don't belong to. The SSR SvelteKit server needs to at least know about the cookies, and then at that point you can use `handleFetch` if you need to tweak which cookies are passed along.

**Comment by mikenikles** [comment]
Let me illustrate the flow in a bit more detail:
1. SvelteKit app on https://webapp-xyz-mydomain.vercel.app/ makes a POST request to https://staging.mydomain.com/
2. Node.js API server on https://staging.mydomain.com/ sends a response back to the SvelteKit app
    * This response contains a cookie with `domain=.mydomain.com`
3. SvelteKit app on https://webapp-xyz-mydomain.vercel.app/ makes a GET (or any request for that matter) to https://staging.mydomain.com/ as part of SSR.
    * If the request was client-side, the browser would find the cookie on the .mydomain.com domain and send it along to the Node.js API server if the `credentials: "include"` option is set.
    * However, SvelteKit SSR doesn't send the cookie

SvelteKit SSR doesn't know about the `domain=.mydomain.com` part of the cookie since that info is only available client-side. Hence I think we need a configuration option to whitelist domains.

**Comment by Conduitry** [comment]
Again, SvelteKit SSR doesn't forward along the cookie because the browser isn't sending the SvelteKIt app server the cookie. You can't whitelist domains and tell browsers to send cookies to domains they're not intended for.

**Comment by mikenikles** [comment]
Oooh, that took me too long to understand, but I get it now 😄. Thanks for the explanations!

I've just found the "[Preview Deployment Suffix](https://vercel.com/docs/concepts/deployments/generated-urls#preview-deployment-suffix)" docs where you can configure a custom domain name for preview deployments, although with the caveat that Vercel's nameservers have to be used.

Thanks again 🙏
