### ISSUE TITLE
Add `App.PageForm` interface

### ISSUE THREAD

**Issue by f-elix** [sveltejs/kit#7017]
### Describe the problem

Firsr,  thank you so much for adding the form property on the page store! It's a huge feature for me. 

I was wondering if the property could be better typed than `any`. I understand that we can't use the auto-generated type `ActionData` for this, but could users have the freedom to type it as they see fit, the same as with `App.PageData`? Is this something that can be done?

### Describe the proposed solution

Add the `App.PageForm` interface.

### Importance

nice to have

**Comment by david-plugge** [comment]
You can import the generated types in any file:

_src/routes/+page.server.ts_
```ts
import type { Actions } from './$types';

export const actions: Actions = {
	default: async () => {
		return { test: 1, value: '' };
	}
};
```

_src/lib/MyForm.svelte_
![image](https://user-images.githubusercontent.com/59972093/192145657-1e7cede8-79ac-4e98-94b8-be53822de095.png)

**Comment by dummdidumm** [comment]
I also lean towards keeping it as `any`, for the reasons outlined above. Even if you decide on a common denominator, it's not checked that what you type actually is correct (on contrast to `App.PageData`).

**Comment by f-elix** [comment]
Oh I ser! I hadn't realized how it differed from `App.PageData`. Still, the proposed solution is a bit cumbersome, especially if you have deeply nested routes with complex names, which isn't uncommon in Sveltekit. I wonder if this could be made easier?

**Comment by david-plugge** [comment]
Not sure if this works correct but the idea is using a global namespace you can extend with the actions you want to use elsewhere

```ts
// src/routes/some/[deep]/route/+page.server.ts
import type { ActionData, Actions } from './$types'

declare global {
  namespace Forms {
    MySigninForm: ActionData
  } 
}

export actions: Actions = {
 ... 
} 
```

```ts
// src/lib/MySigninForm.svelte

$: form = $page.form as Forms.MySigninForm
```

**Comment by david-plugge** [comment]
It would be possible to extend that namespace in the generated types so you only have to do:

```ts
$: Form = $page.form as Forms["some/[deep]/route"] 
```

**Comment by f-elix** [comment]
@david-plugge Hey the global `Forms` namespace is actually a really nice solution! Thanks a lot for that.

@dummdidumm I didn't mean for this to turn into a support discussion, so feel free to close it if you don't think this will be added to the framework.

**Comment by dummdidumm** [comment]
Closing as implementing this similarly to `App.PageData` would be too limiting, since all your (probably very diverse) forms will have to have a common denominator, and if we allow defining an interface without checking it is adhered to it's not of much use.
