### ISSUE TITLE
Static adapter complains about non-existant dynamic routes 

### ISSUE THREAD

**Issue by brgrz** [sveltejs/kit#7029]
### Describe the bug

This is related to https://github.com/sveltejs/kit/issues/4157 but that issue is marked post-1.0 and I believe this should hopefully be resolved before that.

With the default (new) setup of a SvelteKit app a static adapter fails when doing `npm run build` **even when there are no dynamic routes present at all, with the following error:**

```
 @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root layout.js — see https://kit.svelte.dev/docs/page-options#prerender for more details
Error: Encountered dynamic routes
```

I have no dynamic routes set up, there is only the default `page.svelte` file.

Also why does it mention layout.js, what file would that be? seems to me this hasn't been updated since the latest routing changes

I went and added both `prerender` and `ssr` options to the page (not both at the same time) but the issue remains

```
<script lang="ts">
	export const prerender = true;
	// export const ssr = false;
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

this is my svelte.config.js

```
import adapter from '@sveltejs/adapter-static';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter({
			// default options are shown. On some platforms
			// these options are set automatically — see below
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false
		  })
	}
};

export default config;
```

### Reproduction

Create a new SvelteKit app, add the static adapter into the mix, use it in svelte.config.js then try to build the app.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 5.11 GB / 15.78 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 105.0.5195.127
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.50)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/adapter-static: ^1.0.0-next.43 => 1.0.0-next.43 
    @sveltejs/kit: next => 1.0.0-next.503 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.3
```

### Severity

blocking an upgrade

### Additional Information

Impossible to make a static build which could be deployed anywhere.

**Comment by benmccann** [comment]
Closing per the above comment as you've set the option in the wrong place. Please let us know if there are any outdated docs that show the option being set in the `.svelte` file

**Comment by brgrz** [comment]
@benmccann Wrong place? Is it the static adapter that requires it in layout.js(ts)? Bc docs clearly define page options being set in [pages](https://kit.svelte.dev/docs/page-options).

**Comment by dummdidumm** [comment]
As the error suggests, you need to add `export const prerender = true` to your `+layout.ts`, not `+layout.svelte`.

The default app isn't completly prerenderable by default, for example the TODO list example needs a server who can respond to POST requests.

In general, the static adapter can be used when you can prerender everything (just a bunch of HTML files in the end) and/or you have an SPA (which the fallback option is for). The static adapter can NOT be used when you have anything dynamic on the server, like endpoints, SSR, etc.
