### ISSUE TITLE
Move realworld app out to standalone repo

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#703]
We should at some point move the realworld app out to https://github.com/sveltejs/realworld

It's a requirement that it be in a separate repo to be listed on https://github.com/gothinkster/realworld. Probably because they sort by stars

It's probably easier to wait on that for now though. It's helpful to have it in this repo while the API is still changing

**Comment by antony** [comment]
Can't we just set up a github action to clone it to that repo + force push each time?
