### ISSUE TITLE
Better and more optimized structure regarding loops and conditions

### ISSUE THREAD

**Issue by paladio** [sveltejs/kit#7037]
### Describe the problem

I deeply love and enjoy working with Svelte kit, but one thing diminishes this good feeling. It is also the syntax related to the loops and conditions, which I feel needs to be modified and changed in this field. The current syntax has several major problems that I will state below and I will also make a suggestion:

In terms of readability and simplicity, it does not have suitable readability in the subsequent reviews
It makes understanding the structure of the code difficult and a bit unconventional and unfamiliar
Development experience is not pleasant for everyone
It destroys the beauty of the code structure and does not create a good feeling
The amount of code in writing the HTML section increases and causes additional codes to be written

### Describe the proposed solution

Using a structure similar to HTML attributes is very optimal, readable, practical, simple and familiar to the developer mentality.

We can learn and inspire from other frameworks to simplify and improve Svelte js to get closer to a more optimal and efficient structure, for example in the new structure, conditions can be used s-if and loops s-for Just like Vue js

### Alternatives considered

Among the current frameworks, the best structure in these two fields (loops structure and conditions) belongs to the Vue JS , which has both high readability and makes the codes much more understandable.

In fact, the structure of Vue JS is very creative and optimal in terms of conditions and loops, and the final structure is much more understandable. In View, some kind of HTML attributes are used, which are very familiar with the main structure of HTML.

And in the end, my question is whether the Svelte development team has any plans to add this changes in the near future or not?

### Importance

would make my life easier

**Comment by david-plugge** [comment]
First of, this is an issue about svelte not sveltekit.

How are s-if or s-for more readable? I completely disagree with that. Like how is an element with just an attribute more descriptive than an each block? 

But as always it's all about personal preference

**Comment by Conduitry** [comment]
This has come up a number of times. We're not interested in using fake props/attributes to indicate loops and ifs, and we're interested in having two syntaxes for the same thing.

**Comment by paladio** [comment]
> First of, this is an issue about svelte not sveltekit.
> 
> How are s-if or s-for more readable? I completely disagree with that. Like how is an element with just an attribute more descriptive than an each block?
> 
> But as always it's all about personal preference

In the end, it's all a matter of personal preference. But this issue that was raised above has been raised by many developers, and yes, the use of attribute has a more regular, simpler and understandable structure. Many developers have also raised this issue.
I completely disagree with your opinion and as always, your opinion is just your opinion
The text above is just a suggestion and nothing more
