### ISSUE TITLE
Routing between different paths to the same route with parameters doesn't remount

### ISSUE THREAD

**Issue by roelvanhintum** [sveltejs/kit#7049]
### Describe the bug

When using a route with parameters, and fetching all data from a cms, the page doesn't mount for each path visited. When navigating between two pages, which are both handled by the same route, only the first mounts. The second reuses the already mounted page.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-hh9xes?file=src/routes/[...slug]/+page.svelte

About and todos both point to the same route with parameters. Console.log on mount only fires when switching from home, but not between about and todos.

### Logs

```shell
onMount about
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/kit: next => 1.0.0-next.504 
    svelte: ^3.46.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.3
```

### Severity

serious, but I can work around it

### Additional Information

I found a workaround for now by using key blocks in the layout.svelte:
```svelte
<script>
  // Url passed from +layout.js load function.
  /** @type {import('./$types').LayoutData} */
  export let data;
</script>

{#key data.url}
  <slot />
{/key}
```

**Comment by Conduitry** [comment]
This is the intended behavior. See e.g. #3884.
