### ISSUE TITLE
`vite dev --https` command results in the browser error ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by jymma** [sveltejs/kit#7056]
### Describe the bug

In a freshly installed SvelteKit project (skeleton project ; Javascript with JSDoc comments ; no ESLint ; no Prettier ; no Playwright), the command `vite dev --https` results in the error `ERR_SSL_VERSION_OR_CIPHER_MISMATCH` in the browser.

### Reproduction

Just enter the `npm run dev -- --https` command.

### Logs

```shell
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 21.96 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/kit: next => 1.0.0-next.504 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.3
```

### Severity

serious, but I can work around it

**Comment by bluwy** [comment]
You need the [@vitejs/plugin-basic-ssl](https://github.com/vitejs/vite-plugin-basic-ssl) plugin. https://vitejs.dev/config/server-options.html#server-https
