### ISSUE TITLE
Add flags to control options in create-svelte

### ISSUE THREAD

**Issue by IanVS** [sveltejs/kit#7064]
### Describe the problem

I would like to add a reproduction generator in storybook for sveltekit + storybook projects, which requires me to provide a command to run that will bootstrap a sveltekit project.  Currently, it seems there's no way to run `create svelte` without following all of the prompts interactively. 

### Describe the proposed solution

I'd like to add command-line flags like `--template`, `--types=none`, and `--eslint=false` which, if provided, skip the prompts for those questions and allow an "unattended" bootstrap of a sveltekit project.

This could be done with commander, or optionator, or whatever other tool y'all prefer.  

### Importance

i cannot use SvelteKit without it

**Comment by Conduitry** [comment]
This has come up a number of times and isn't something we're interested in adding for the reasons outlined in https://github.com/sveltejs/kit/pull/6117#issuecomment-1221323822

**Comment by IanVS** [comment]
OK, thanks for the quick response, even though it's disappointing.
