### ISSUE TITLE
Invalidate just the page load function

### ISSUE THREAD

**Issue by jhwz** [sveltejs/kit#7073]
### Describe the problem

I find myself quite often doing something like:

```ts
// +page.ts
const invalidateKey = "some-key";

export const load = async ({depends}) => {

depends(invalidateKey);
return { ... }
}
```

and then in the markup doing something like
```svelte
// +page.svelte

<button on:click={() => invalidate(invalidateKey)}>reload page data</button>
```

It seems that it's a pretty common use case to just reload the current pages data, but I'm not sure if this is the case for everyone!

I don't always want to use `invalidateAll()` because in my case that will make a bunch of global API requests for things that don't need to be reloaded.

### Describe the proposed solution

Some other way of reloading the current page load function, `invalidatePage()`? Although you probably don't want yet another `invalidate` function.

### Alternatives considered

I can just keep declaring string dependencies for each page and invalidating that.

### Importance

nice to have

**Comment by david-plugge** [comment]
What about `invalidate($page.url)`?

**Comment by jhwz** [comment]
> What about `invalidate($page.url)`?

That used to work (I'm pretty sure), but not in the latest versions!

**Comment by jhwz** [comment]
> By definition only one page can be active at the same time. Therefore you can create such a function yourself with minimal additional boilerplate:
> 
> ```js
> export function updatePage(depends) {
>   depends('some:key');
> }
> export function invalidatePage() {
>   invalidate('some:key');
> }
> ```
> 
> ```js
> export function load({ depends }) {
>   updatePage(depends);
>   // ..
> }
> ```
> 
> ```
> <button on:click={invalidatePage}>Invalidate</button>
> ```
> 
> I therefore think this can stay in user-land.

All good, I had resorted to something similar!
