### ISSUE TITLE
Prerender fails when the route contains Non-ASCII Characters

### ISSUE THREAD

**Issue by kwchang0831** [sveltejs/kit#7074]
### Describe the bug

Prerendering process fails during setting the response header of `x-sveltekit-routeid` when routeId contains Non-ASCII Characters. https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/index.js#L301

```sh
TypeError: Cannot convert argument to a ByteString because the character atindex 0 has a value of 21021 which is greater than 255.
```

### Reproduction

https://github.com/kwchang0831/issue-sveltekit-prerender-unicode-path

To Reproduce:
1. Create a route with Non-ASCII Characters. eg: `src/routes/初めまして/+page.svelte`.
2. Set `export const prerender = true;` in `+layout.ts`.
3. Run `pnpm build`

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Xeon(R) CPU D-1541 @ 2.10GHz
    Memory: 21.55 GB / 31.35 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.7.0 - ~/.asdf/installs/nodejs/18.7.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Firefox: 105.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/kit: next => 1.0.0-next.505 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.4
```

### Severity

serious, but I can work around it

### Additional Information

What I have tried to work around the issue:

Encode the routeId

https://github.com/sveltejs/kit/blob/720735d59b8bca3ba7fcd37e07cc9e5ae004ae2d/packages/kit/src/runtime/server/index.js#L300-L302

```js
  response.headers.set('x-sveltekit-routeid', encodeURI(event.routeId));
```

https://github.com/sveltejs/kit/blob/720735d59b8bca3ba7fcd37e07cc9e5ae004ae2d/packages/kit/src/core/prerender/prerender.js#L422-L426

```js
  if (prerender === true && !prerendered_routes.has(encodeURI(route_id))) {
```

I am not sure if this is the correct way to do, and this assumes that the routeID was not previously encoded with `encodeURI`.

Also, while I was trying to figure out the issue, I found that the routing will fail if the route is already encoded. eg: `src/routes/%E5%88%9D%E3%82%81/+page.svelte`. ~~I guess I should probably sumbit another issue for that.~~ The issue has submitted at #7075.

**Comment by benmccann** [comment]
We had to do `encodeURI` for the `link` header: https://github.com/sveltejs/kit/blob/a4e5814d2f6cd7e6700076df9ea1f99d4161a873/packages/kit/src/runtime/server/page/render.js#L248

I'm guessing we need to do the same here
