### ISSUE TITLE
Adding custom resolve.alias causes SSR loading to file in vite

### ISSUE THREAD

**Issue by mithusingh32** [sveltejs/kit#710]
**Describe the bug**
Adding custom resolve.alias in svelte.config.cjs causes SSR loading to file in vite

**Logs**
```
yarn run v1.22.10
warning package.json: No license field
$ svelte-kit dev
> Listening on http://localhost:3000
Error: failed to load module for ssr: /@fs/src/components/Header.svelte
    at instantiateModule (/home/removed_username/git/MusicalKeyWeb/node_modules/vite/dist/node/chunks/dep-0776dd57.js:68875:15)
```

**To Reproduce**

1. Create directory `component` in src
2. Create svelte component in `src/component`
3. create alias for component directory in `svelte.config.ts` as shown below
```js
const sveltePreprocess = require('svelte-preprocess');
const node = require('@sveltejs/adapter-node');
const pkg = require('./package.json');

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: [
		sveltePreprocess({
			defaults: {
				style: "postcss",
			},
			postcss: true
		}),
	],
	kit: {
		// By default, `npm run build` will create a standard Node app.
		// You can create optimized builds for different platforms by
		// specifying a different adapter
		adapter: node(),

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',

		vite: {
			resolve: {
				alias: {
					$components: 'src/components'
				}
			},
			ssr: {
				noExternal: Object.keys(pkg.dependencies || {})
			},
		}
	},

};
```
4. import component using alias `import TestComponent from '$component/TestComponent'`
5. `yarn dev`

I can create a repo, but I think this is super simple to recreate

**Expected behavior**
Web page renders w/out error

**Information about your SvelteKit Installation:**

**System:**

- OS: Linux 5.11 Fedora 33 (Workstation Edition) 33 (Workstation Edition)
- CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
- Memory: 19.51 GB / 25.41 GB
- Container: Yes
- Shell: 5.0.17 - /bin/bash

**Binaries:**
- Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
- Yarn: 1.22.10 - /usr/bin/yarn
- npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm

**Browsers:**
- Chrome: 89.0.4389.90
- Firefox: 86.0.1
**Adapter**
- node

**Severity**
Technically its an annoyance but I consider it severe because it indicatres all aliases other than $lib and $app will be broken. 

**Additional context**
Doesn't look like its a svelte issue but a Vite. But not 100% sure.

**Comment by Rich-Harris** [comment]
try `$components: path.resolve('src/components')`

**Comment by mithusingh32** [comment]
Thanks! I keep forgetting that path.resolve() exists.
