### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by fancyplants** [sveltejs/kit#712]
**Describe the bug**
When working with SvelteKit and attempting to import the `mediasoup-client` library into one of my main components as such:

`import mediasoup from 'mediasoup-client'`

The app doesn't compile and complains that there is no `exports` variable defined in the `index.js` of the compiled-to-js part of `mediasoup-client`. When attempting to add a `var exports = {}` at the top of said file in `node_modules` in hopes it would work, I also got an error related to the function `require` not being available.

**Logs**
Server logs:
![image](https://user-images.githubusercontent.com/26033574/112689482-9b03e000-8e37-11eb-8cde-5719349d1391.png)

Browser logs (less info, but I can delve deeper into the error if needed):
![image](https://user-images.githubusercontent.com/26033574/112689559-b53dbe00-8e37-11eb-9a2e-36a3abc74a16.png)

**To Reproduce**
This occurs directly in the repository I am working on, and is a relatively self-contained error without much setup needed to reproduce. If this is not small enough, I can definitely create a separate repo to reproduce with as little code as possible!

1. Clone https://github.com/fancyplants/svelte-lather
2. Run `npm install` or equivalent to install dependencies
2. Run `npm run dev`
3. Navigate to `http://localhost:3000/video`
4. Error should occur.

**Expected behavior**
I expected the page to compile as normal and allow me to utilize both types (like `mediasoup.types.Producer`) as well as actual classes (`mediasoup.Device`, as used on line 94 of `video.svelte`).

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>
1:31:57 PM [vite] Error when evaluating SSR module /node_modules/mediasoup-client/lib/index.js:
ReferenceError: exports is not defined
    at /node_modules/mediasoup-client/lib/index.js:21:23
    at instantiateModule (/home/josh/code/js/lather/svelte-lather/node_modules/vite/dist/node/chunks/dep-0776dd57.js:68919:166)
</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
```
System:
    OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 9.35 GB / 12.36 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.11.0 - ~/.nvm/versions/node/v14.11.0/bin/node
    npm: 7.7.5 - ~/.nvm/versions/node/v14.11.0/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.60
    svelte: ^3.29.0 => 3.35.0
```
- Your browser
![image](https://user-images.githubusercontent.com/26033574/112690077-6e03fd00-8e38-11eb-94fd-74cb8405283f.png)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
The default, `node`.

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or **blocking your usage of SvelteKit entirely**?

This is entirely blocking my next usage of SvelteKit. I'm super excited to use this and have been trying to adapt this project from using React/Next.js to Svelte/SvelteKit. This app is going to use video conferencing through the `mediasoup` library, and so it is crucial that my app is able to compile while using said library.

Otherwise, I love developing with Svelte and want to see this project succeed so bad. If there's *any* more information I can give or any other way I can help with getting this figured out, please do let me know! Thanks.

**Additional context**
Screenshot of the error in browser:
![image](https://user-images.githubusercontent.com/26033574/112689398-74de4000-8e37-11eb-817c-0fe9c85f07c6.png)

**Comment by lukasIO** [comment]
try loading it only client-side only

```js
onMount(async () => {
		let module = await import('mediasoup-client');
		const mediasoup = module.default;
		let device = new mediasoup.Device();
		console.log(device);
	});
```

it's documented in the docs here https://kit.svelte.dev/docs#troubleshooting-server-side-rendering

**Comment by fancyplants** [comment]
@lukasIO Works great! Thank you so much, can't believe I missed that bit in the docs. Gonna close this now.
