### ISSUE TITLE
Add `submitting` state to `page` store 

### ISSUE THREAD

**Issue by KoichiKiyokawa** [sveltejs/kit#7120]
### Describe the problem

First, thank you for all of your work in SvelteKit.
It's common to disable the submit button during form submission to prevent users from submitting multiple times.
But now, we need some boilerplate code to do it. cf) https://github.com/sveltejs/kit/discussions/7041
It would be nice if SvelteKit provides the submitting state by `page` store.

### Describe the proposed solution

- `$page.formSubmitting` ?
- `$page.form.submitting` ?
- and so on
```sv
<script>
import { page } from '$app/store'
</script>

<button disable={$page.formSubmitting}>submit</button>
```

### Importance

nice to have

### Additional Information

FYI: Remix can handle it by the followings,
```ts
function SubmitButton() {
  const transition = useTransition();

  return <button type="submit" disable={transition.state === "submitting"}>submit</button>;
}
```
https://remix.run/docs/en/v1/api/remix#transitionstate

**Comment by KoichiKiyokawa** [comment]
> but what if there is multiple forms in a page?

Good point of view. I had missed it. Thank you!
How about `$page.forms[0].submitting` ? (Like [Document.forms](https://developer.mozilla.org/en-US/docs/Web/API/Document/forms))

Current SvelteKit already has `$page.form` (https://kit.svelte.dev/docs/types#sveltejs-kit-page), but maybe it is only for a single form. Does it also has to consider multiple forms in a page?

**Comment by dummdidumm** [comment]
`export let form` and `$page.form` are designed to work with the latest submitted form. It is not designed to work with multiple in-flight forms at the same time. Adding your own submission state using the `use:enhance` action is done quick:

```svelte
<script>
  import { enhance } from '$app/forms';

  let submitting = false;
</script>

<form method="POST" use:enhance={() => {
  submitting = true;
  return ({ update }) => {
    submitting = false;
    update();
  }
}}>
  ...
</form>
```

I think the bigger desire here is to have more info and/or a provided function to make these more advanced uses cases (multiple in-flight submissions, submission state) easy to implement. I opened #7175 for this, closing in favor of that.
