### ISSUE TITLE
The Generated javascript file from flowbite-svelte is bigger than the generated js file from flowbite

### ISSUE THREAD

**Issue by Abdulrhman311** [sveltejs/kit#7123]
### Describe the bug

The Generated javascript file from flowbite-svelte ( Navbar component ) is 67kb
in the other hand the generated file from flowbite  ( Navbar component )  is almost 5kb
so why the output from flowbite-svelte is very bigger than flowbite

### Reproduction

![Screenshot from 2022-10-02 21-31-02](https://user-images.githubusercontent.com/114878289/193472799-3e5c84eb-177c-48bc-bcb9-317a16062b6f.png)

![Screenshot from 2022-10-02 21-30-38](https://user-images.githubusercontent.com/114878289/193472801-0f9c7ff0-22fd-45de-874a-a0264e8fda76.png)

**Vite.config.js**

![Screenshot from 2022-10-02 21-30-19](https://user-images.githubusercontent.com/114878289/193472803-23ea47e6-9cf7-4bc1-bf00-33bd5c77f749.png)

**Flowbite-svelte (Navbar)**
![Screenshot from 2022-10-02 21-29-56](https://user-images.githubusercontent.com/114878289/193472806-803deb72-9709-437a-8f32-702af4d72abb.png)

![Screenshot from 2022-10-02 21-29-10](https://user-images.githubusercontent.com/114878289/193472808-34bf61f1-a19f-42ec-a2b4-72d526c72836.png)

### System Info

```shell
System:
    OS: Linux 5.19 Fedora Linux 36 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 1.87 GB / 7.64 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.71 
    @sveltejs/adapter-static: ^1.0.0-next.41 => 1.0.0-next.41 
    @sveltejs/kit: next => 1.0.0-next.469 
    svelte: ^3.44.0 => 3.50.0 
    vite: ^3.1.0-beta.1 => 3.1.0-beta.2
```

### Severity

annoyance

### Additional Information

**With Flowbite Output size is 5.5KB**

![Screenshot from 2022-10-02 21-15-55](https://user-images.githubusercontent.com/114878289/193472996-90f27e4c-f1b8-43da-94f3-ad52814e9c1a.png)

**Comment by Conduitry** [comment]
You'll have to ask the creators of flowbite-svelte. Please only open issues for reproducible bugs or concrete feature requests.

**Comment by dominikg** [comment]
Please don't crosspost issues. 
https://github.com/themesberg/flowbite-svelte/issues/355

If you believe this to be an issue with SvelteKit, please provide a repository with a minimal reproduction. Also check that it does not happen without using kit, eg in a vite+svelte project.
