### ISSUE TITLE
Allow the removal of the `src` directory

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#7127]
### Describe the problem

This is a followup on #6944 

I only serve static assets now. I no longer have a `routes` folder, need for the `app.html` and no need for the type declarations. I simply only need the `static` directory. 

### Describe the proposed solution

Allow me to remove the `app.html` and/or the `./src` directory

### Alternatives considered

Not care about these practically useless yet mandatory files in my codebase

### Importance

nice to have

### Additional Information

I would not have opened this issue if it wasn't for me being in a boring meeting right now. I have nothing better to do with these 5 minutes. If this issue is too much refactor work, don't bother please.

**Comment by MaoMaoCake** [comment]
Why would you use Svelte instead of a webserver then? Use either nginx or apache or whatever thats meant to serve static file

**Comment by Conduitry** [comment]
Indeed. At that point, just use nginx, or S3, or whatever else you want to serve static files.

**Comment by UltraCakeBakery** [comment]
@MaoMaoCake I can't setup nginx or S3 on my serverless/edge hosting

@Conduitry I would recommend rolling back the changes from #6944 in that case. If my use case falls outside the scope of svelte kit, then I don't know why #6944 got fixed in the first place.

**Comment by aloker** [comment]
> @Conduitry I would recommend rolling back the changes from #6944 in that case. If my use case falls outside the scope of svelte kit, then I don't know why #6944 got fixed in the first place.

For a Svelte Kit library package, having no routes makes sense (only the lib folder is used)

**Comment by UltraCakeBakery** [comment]
> > @Conduitry I would recommend rolling back the changes from #6944 in that case. If my use case falls outside the scope of svelte kit, then I don't know why #6944 got fixed in the first place.
> 
> For a Svelte Kit library package, having no routes makes sense (only the lib folder is used)

Ahh fair point. I forgot about that lib folder.

But in that case, the `app.html` doesn't need to be mandatory.. unless I'm again missing something here.. right?
