### ISSUE TITLE
App.PageError transition error does not respect comments

### ISSUE THREAD

**Issue by MaoMaoCake** [sveltejs/kit#7128]
### Describe the bug

The test written as part of #6905 does not respect comments. The commented `// interface PageError {}` of older app.d.ts will trigger the error. Not critical but its pretty confusing. Especially if you were not expecting it.

### Reproduction

Update from an older version of svelte and try to run dev.

### System Info

```shell
N/A
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
This is intended. If you don't update it now and only eventually uncomment it to add types post-1.0 (at which point we will have removed all of these deprecation/upgrade checks), it won't work. We're erring on the side of being annoying now rather than being surprising later.
