### ISSUE TITLE
Using inlineStyleThreshold causes duplicate CSS

### ISSUE THREAD

**Issue by The-Noah** [sveltejs/kit#7130]
### Describe the bug

When I add `inlineStyleThreshold` to my `svelte.config.js` file it duplicates the CSS; it is both inline and imported via `link` tags. The link tags have both the `disabled` property and `media="(max-width: 0)"` which would make me think they shouldn't be loaded (and if that's the case I don't know why it's included at all) but when I go to the network tab in devtools it shows the styles being loaded

## No `inlineStyleThreshold`
![image](https://user-images.githubusercontent.com/35819660/193636182-1a5d30cf-97c0-4079-89dd-19a2b43d7e67.png)

## `inlineStyleThreshold`
![image](https://user-images.githubusercontent.com/35819660/193636240-23d125dd-664c-4176-8a21-f5fba6fd1f7f.png)
![image](https://user-images.githubusercontent.com/35819660/193636256-662e4b64-a989-4b20-a539-7ace83283fa0.png)

### Reproduction

Repo: https://github.com/The-Noah/sveltekit-inline-css

## Steps to reproduce

1. Download and build application
```bash
git clone https://github.com/The-Noah/sveltekit-inline-css.git
cd sveltekit-inline-css
pnpm i
pnpm build
```

2. Open `build/index.html` to find the inline CSS and CSS import.

### System Info

```shell
System:
  OS: Windows 10 10.0.25211
  CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
  Memory: 15.29 GB / 31.92 GB
Binaries:
  Node: 17.4.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.25211.1001.0), Chromium (104.0.1293.47)
  Internet Explorer: 11.0.25211.1001
npmPackages:
  @sveltejs/adapter-static: 1.0.0-next.44 => 1.0.0-next.44
  @sveltejs/kit: next => 1.0.0-next.507
  svelte: ^3.44.0 => 3.50.1
  vite: ^3.1.0 => 3.1.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This seems to have been a bug in Vite. It fails with 3.1.x, but works with 3.2.x. Updating to the latest version of Vite fixes the bug.

**Comment by Rican7** [comment]
Hmm, I'm running into this same issue now, with Vite 6.2.2.

**Comment by The-Noah** [comment]
I've just noticed the same issue again as well. SvelteKit v2.19.2 and Vite v6.2.2.
