### ISSUE TITLE
Update sveltekit Request new event. hooks

### ISSUE THREAD

**Issue by Upsetmania** [sveltejs/kit#7134]
### Describe the bug

hello, since the new version of sveletekit I can no longer make the code work that I present to you the hook the application crashes with an error TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))

Thank you for your help

### Reproduction
https://github.com/Upsetmania/client-v507.git
import cookie from 'cookie';

export const getSession = async (event) => {
	const cookies = cookie.parse(event.request.headers.get('cookie') || '');
	const theme = cookies.theme || 'light';

	return {
		theme
	};
};

export const handle = async ({ event, resolve }) => {
	
	const response = await resolve({...event});
	const cookies = cookie.parse(event.request.headers.get('cookie') || '');

	let headers = response.headers
	
	
	//console.log(headers)
	const cookiesArray = [];

	if (!cookies.theme) {
		const theme = event.request.headers.get('theme') || 'light';
		cookiesArray.push(`theme=${theme};path=/;expires=Fri, 31 Dec 9999 23:59:59 GMT`);
	}
	if (cookiesArray.length > 0) {
		headers = {
			...response.headers,
			'set-cookie': cookiesArray	
		};
	}
	
	return {
		...response,
		headers
	};
};

### Logs

```shell
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
```

### System Info

```shell
sveltekit
```

### Severity

annoyance

### Additional Information
https://github.com/Upsetmania/client-v507.git
_No response_

**Comment by Conduitry** [comment]
Please provide a minimal reproduction as a StackBlitz link or a clonable repo.

**Comment by Upsetmania** [comment]
hello, thank you for your answer I added the link of the ghiub clone thank you cordilamenet

**Comment by david-plugge** [comment]
getSession was removed and I think using the spread operator on a request isn't a good idea. And take a look at the new cookie api, it should fit your use case

**Comment by Upsetmania** [comment]
thanks for the information but since deleting session and getsession I can't find a solution to modify the code

**Comment by Upsetmania** [comment]
thank you very much i solved my problem.

https://github.com/sveltejs/kit/discussions/5883
