### ISSUE TITLE
Query string is lost when using named actions

### ISSUE THREAD

**Issue by oganexon** [sveltejs/kit#7137]
### Describe the bug

When using named actions, the query string is removed from the url, causing issues when returning validation errors with the `invalid` function.

Let's say we have a `challenge` query parameter in the query URL. This parameter was used to process things server side in the `load` function. When submitting a default action, if something goes wrong (eg. wrong password), we can `invalid` the form and tel the user something isn't valid. Since the `challenge` parameter is still here, we can regenerate the page as before.

But with named actions (eg. `?/login` and `?/deny` to deny access to an account), query parameters get lost and there's no way to feed back the `challenge` parameter in the `load` function. Data in the `invalid` function won't be reachable from there so the page is broken.

### Reproduction

**Reproduction :**
https://stackblitz.com/edit/sveltejs-kit-template-default-8tnzt3?file=src/routes/named-actions-login/+page.server.ts

1. Go to `/login?login_challenge=1234`
2. Enter `a` and `a` for user login and password
3. `Invalid credentials` message is displayed
---
4. Go to `/named-actions-login?login_challenge=1234`
5. Enter `a` and `a` for user login and password
6. 400 Error : challenge is missing

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/kit: next => 1.0.0-next.507 
    svelte: ^3.46.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.4
```

### Severity

serious, but I can work around it

### Additional Information

My intent was to split my code thanks to this new “named actions” feature. Looks like it isn't compatible with some workflows.

**Comment by repsac-by** [comment]
You need to explicitly specify the query parameters because `action=` is a new URL

```diff
<script>
  export let data;
  export let form;

  const challenge = form?.challenge ?? data.challenge;

+  $: query = new URLSearchParams({
+   login_challenge: challenge
+  })
  
</script>

{#if form?.invalidCredentials}
  <p>Invalid credentials</p>
{/if}

-<form method="POST" action="?/login">
+<form method="POST" action="?/login&{query}">
```

**Comment by oganexon** [comment]
Thanks a lot, it works now.

I wasn't sure how the query parameters were handled in `action=` but it makes perfect sense !
