### ISSUE TITLE
Converting an undefined kit.version.name in to a Date.now(), a hardcoded timestamp gets added and generates unique static files for each build

### ISSUE THREAD

**Issue by grumpyoldman-io** [sveltejs/kit#7144]
### Describe the bug

When you do not include a version.name, Svelte uses a Date.now().toString() (https://kit.svelte.dev/docs/configuration). This has the added benefit of always rendering a unique version. The downside of this is that this gets passed on and hardcoded in the singletons.js during a build. Consequently making the singletons.hash.js unique to each build. If your hosting does not "share" build assets while scaling horizontally this creates a problem in that you get 404's (each container has a unique set of files).

### Reproduction

1. install sveltekit
2. run a build
3. rename output folder (to prevent overwriting it)
4. run a second build (without any code changes)
5. observe that build/_app/immutable/chunks/singletons-[hash].js is now different from the previous build

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 106.39 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 105.1.43.93
    Chrome: 105.0.5195.125
    Firefox Developer Edition: 106.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.42 => 1.0.0-next.43
    @sveltejs/kit: next => 1.0.0-next.491
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.3 => 3.1.3
```

### Severity

annoyance

### Additional Information

Perhaps the singletons could uses a pointer to the version, and not a hardcoded version?

the original code can be found here:
https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/utils.js#L140
which gets its contents from here:
https://github.com/sveltejs/kit/blob/master/packages/kit/src/exports/vite/build/utils.js#L136

CC @s-rd

**Comment by Conduitry** [comment]
What would the "pointer" to the version be? If each thing tried to load the `/_app/version.json` file instead, presumably that would be different across different builds of the app as well, no?

The current behavior doesn't feel like a bug to me. If your hosting platform (for whatever reason) rebuilds the app when scaling horizontally, that sounds like a great reason to manually specify a version based on, say, the current Git SHA1.

**Comment by grumpyoldman-io** [comment]
I think my main gripe with it is that is so implicit that not setting a version leads to uniquely generated files. I completely agree with you on the solution, it is simply quite a challenge to come to that conclusion without doing quite a lot of digging.

**Comment by Rich-Harris** [comment]
Perhaps if we didn't embed the version in the generated files, but instead included it in the rendered HTML...

```diff
<script type="module" data-sveltekit-hydrate="1vcz4c4">
  import { start } from "./_app/immutable/start-425c5ea9.js";

  start({
    env: {},
    hydrate: {
      status: 200,
      error: null,
      node_ids: [0, 3],
      params: {},
      routeId: "",
      data: (function(a){return [a,a]}(null)),
      form: null
    },
    paths: {"base":"","assets":""},
    target: document.querySelector('[data-sveltekit-hydrate="1vcz4c4"]').parentNode,
    trailing_slash: "never",
+   version: 'xyz123'	
  });
</script>
```

...then it wouldn't matter so much, since the assets themselves would retain the same hashes.

**Comment by Rich-Harris** [comment]
(Though I will say that creating separate builds when scaling horizontally seems like... an interesting design choice?)

**Comment by Conduitry** [comment]
I do think it would still be helpful to continue to have a URL that could easily be queried to find out the deployed version. I know `/_app/version.json` isn't part of the public API, but I've definitely used it on sites in production.

**Comment by grumpyoldman-io** [comment]
@Rich-Harris more of an oversight and limitation in human resources at the time, and I fully agree its uhum "less than desirable", but I do think it helps to persist file names when file contents do not change, and in theory this is an undesired and implicit change in the file. I think not embedding it is the way to go here even in interestingly designed environments.

**Comment by grumpyoldman-io** [comment]
+1 on pulling the version out of the logic (js files). Having a query-able endpoint I can totally see the value of, but I also worry about an extra request if that's the only place to get it from.
