### ISSUE TITLE
no css on error page after building

### ISSUE THREAD

**Issue by elianiva** [sveltejs/kit#715]
**Describe the bug**

The error page doesn't seem to load any CSS or even request it.

**Logs**

There is no log, it just says route is not found which is expected, though I have a screencast for it.

This first screencast is when running sveltekit on development. The CSS doesn't seem to load initially but it comes back after maybe several ms. It's like vite put the css back (there's a message in the console, though I don't really understand how Vite works)

https://user-images.githubusercontent.com/51877647/112703266-d8fd1480-8ec8-11eb-92df-4fa68dcd477a.mp4

This second one is after running `svelte-kit build`. The CSS doesn't seem to load at all and there's no network request either.

https://user-images.githubusercontent.com/51877647/112703267-dac6d800-8ec8-11eb-81b8-5c5857d00ccd.mp4

![2021-03-27T06:46:54,198945491+07:00](https://user-images.githubusercontent.com/51877647/112703368-49a43100-8ec9-11eb-9e88-d52558527bd3.png)

**To Reproduce**

I've made a repo to reproduce this issue. https://github.com/elianiva/repro

1. install deps
2. run `npm run build`
3. go to a non-existent route
4. the CSS isn't there

or 

1. install deps
2. run `npm run dev`
3. go to a non-existent route
4. the CSS is there

**Expected behavior**

The CSS should be there even if it's a production build

**Stacktraces**

none

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

```
  System:
    OS: Linux 5.11 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    Memory: 4.22 GB / 7.65 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /tmp/fnm_multishell_2179_1616801221879/bin/node
    Yarn: 1.22.10 - /tmp/fnm_multishell_2179_1616801221879/bin/yarn
    npm: 7.6.3 - /tmp/fnm_multishell_2179_1616801221879/bin/npm
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.61 
    svelte: ^3.29.0 => 3.35.0 
```

- Your browser

Mozilla Firefox 88.0b2

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)

adapter-static, but also happen on adapter-vercel

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

This is quite annoying because I'd like to have some styling on my error page. I could just redirect to `/` whenever a user hits an invalid route but that doesn't seem right.

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

maybe related? https://github.com/sveltejs/kit/issues/606
Thanks in advance :)

**Comment by jfranciscosousa** [comment]
Can confirm that this is still happening. Just after creating an empty `svelte-kit` project. Seems that the entirety of `%svelte.head%` is missing on error pages.

**Comment by benaltair** [comment]
For those who aren't seeing the fixes (this will be obvious to some) make sure to run `npm update` to get the latest Kit code.

**Comment by jfranciscosousa** [comment]
Can confirm that the new release works great
