### ISSUE TITLE
Improve error message for route not found

### ISSUE THREAD

**Issue by peterpeterparker** [sveltejs/kit#7155]
### Describe the problem

Today I spend 30min debugging an error I met in my terminal:  `Not found: /components/modal` 

I tried, tried, tried to fix until I finally figured out that my browser, which was hidden behind my editor and terminal, was trying to access an url `http://localhost:5173/components/modal` which does not exist in my project.

Dumb me, I was always switching between terminal and editor but never opened the browser. Since I am migrating a project I assumed the error was in my build setup or code.

### Describe the proposed solution

Improve terminal error message when route are not found.

e.g. instead of 

```
Not found: /components/modal
```

parse

```
Route not found: /components/modal
```

### Importance

nice to have

**Comment by jrmoynihan** [comment]
Would be curious to see the code that gave you this error.  When using anchor tags with the data-sveltekit-prefetch attribute (or placing it on the body of the app), I get this kind of error message in the console when the route is not found (e.g. when I hover the link and the prefetch begins):

`Uncaught (in promise) Error: Attempted to prefetch a URL that does not belong to this app.`

Having said that, even with the stack trace, the error would be more helpful if it told me which route url it was trying to prefetch.

**Comment by peterpeterparker** [comment]
@jrmoynihan you can reproduce it with just a blank new app using the `adapter-static`

```
git clone https://github.com/peterpeterparker/my-app
cd my-app
npm ci
npm run dev
```

open `http://localhost:5173/whatever` url

<img width="1470" alt="Capture d’écran 2022-10-06 à 08 48 03" src="https://user-images.githubusercontent.com/16886711/194233299-d5eed9bf-26fb-4ccc-968c-cd70546c5f7d.png">

**Comment by dummdidumm** [comment]
We debated this internally and think that the current error message is enough, especially in combination with the info in the browser. If this comes up more times, we'll revisit this decision.
