### ISSUE TITLE
Types for enhance function callback

### ISSUE THREAD

**Issue by ftognetto** [sveltejs/kit#7161]
### Describe the problem

I would like to have the result object parameter of enhance function to be typed.

Example:

*+page.server.ts*
```
import { invalid, type Actions } from '@sveltejs/kit';

export const actions: Actions = {
	default: async (event) => {
                // get data from form
		const data = await event.request.formData();
		const name = data.get('name');
		const surname = data.get('surname');

		// validation
		const errors = validate({name, surname});
		if (errors) {
			return invalid(400, {
				name,
				surname,
				errors
			});
		}
		// call external be or db
		const result = await fetch('<url>', { body: JSON.stringify({name, surname}) });
		if (!result.ok) {
			return invalid(500, {
				name, 
				surname,
				beError: await result.text()
			})
		}
		return {
			name,
			surname,
			result: await result.json()
		}
	}
};
```

*+page.svelte*
```
<script lang="ts">
	import { applyAction, enhance } from '$app/forms';
	import type { ActionData } from './$types';
	export let form: ActionData;
</script>

<form
	method="POST"
	use:enhance={(event) => {
		return async ({ result }) => {
			if (result.type === 'success') {
				alert('hello ' + result.data?.name);
			}
			applyAction(result);
		};
	}}
>
	<input type="text" name="name" placeholder="Name" value={form?.name || ''} />
	<input type="text" name="surname" placeholder="Surname" value={form?.surname || ''} />

	<button type="submit" class="btn btn-primary ">Salva</button>
</form>
```

So in +page.svelte i have the correct types on form object so that in input value `<input type="text" name="name" placeholder="Name" value={form?.name || ''} />` the editor suggest me that form object has a name property.
<img width="966" alt="Schermata 2022-10-06 alle 07 00 22" src="https://user-images.githubusercontent.com/47910896/194218685-ad2d7887-de7d-4b58-a106-dfc6b482cdb2.png">

Insted in enhance callback the result.data is a `Record<string, any> | undefined` and I don't know what kind of data the `+page.server.ts` sent.
<img width="870" alt="Schermata 2022-10-06 alle 07 04 08" src="https://user-images.githubusercontent.com/47910896/194218706-75e8e904-5c16-4044-abb9-ce9151f49da8.png">

### Describe the proposed solution

I'm trying to find a solution but for now the only workaround that is working for me is to not use enhance but instead use a custom listener like the docs says (https://kit.svelte.dev/docs/form-actions#progressive-enhancement-custom-event-listener) but I'm afraid that without the use of the enhance function I lose the ability to make the form work in the absence of javascript.

### Importance

would make my life easier

**Comment by ftognetto** [comment]
hi @david-plugge thank you! I was working on a similar solution, declaring a new SubmitFunction passing the correct types.
But I think it would be nice that enhance function infer types returned from the *+page.server.ts* action.

So for example if I write an action that

```
export const actions: Actions = {
	default: async (event): Promise<FormResult<User>> => {
            ....
        }
}
```

with, in my case, FormResult from

```
export type FormErrors = { [key: string]: string | undefined; generic?: string | undefined };
export type FormValues = { [key: string]: string | undefined };

export type FormSuccessResult<T extends RecordOrUndefined> = {
	values: FormValues;
	output?: T;
};
export type FormInvalidResult = {
	values: FormValues;
	errors: FormErrors;
};
export type FormResult<T extends RecordOrUndefined = undefined> = FormSuccessResult<T> | ValidationError<FormInvalidResult>;
```

Then the submit function would infer Success and Invalid types, passing type `User` to `result.data.output` in case of success.

**Comment by ZerdoX-x** [comment]
Could someone clarify how can I type enhance function now? I saw commit on March 30 but I am not sure how to get benefits from it and how to type it correctly now.

```
const enhanceTagSuggestionForm =
	() => {
		return (event) => {
			const result = event.result;
			if (result.type === "failure") {
				alert("something went wrong");
			} else if (result.type === "success") {
				if (typeof result?.data?.data?.competency_name !== "string")
					return alert("something went wrong");
				pushCompetencyTag(result.data.data.competency_name);
			}
		};
	};
```

```
  112:10  error  Unsafe assignment of an `any` value                                     @typescript-eslint/no-unsafe-assignment
  112:19  error  Unsafe member access .result on an `any` value                          @typescript-eslint/no-unsafe-member-access
  113:8   error  Unsafe member access .type on an `any` value                            @typescript-eslint/no-unsafe-member-access
  115:15  error  Unsafe member access .type on an `any` value                            @typescript-eslint/no-unsafe-member-access
  117:16  error  Unsafe member access .data on an `any` value                            @typescript-eslint/no-unsafe-member-access
  120:23  error  Unsafe argument of type `any` assigned to a parameter of type `string`  @typescript-eslint/no-unsafe-argument
  120:23  error  Unsafe member access .data on an `any` value                            @typescript-eslint/no-unsafe-member-access
```

**Comment by hyunbinseo** [comment]
@ZerdoX-x As of now, the generated `SubmitFunction` type has to be manually imported and applied.

```svelte
<script lang="ts">
  import type { SubmitFunction } from './$types';

  const submitFunction: SubmitFunction = () => {
    return async ({ result }) => {
      if (result.type === 'success' && result.data) {
        result.data; // typed
      }
      if (result.type === 'failure' && result.data) {
        result.data; // typed
      }
    };
  };
</script>
```

Hope this was part of the [zero-effort type safety].

[zero-effort type safety]: https://svelte.dev/blog/zero-config-type-safety

**Comment by ftognetto** [comment]
Yes @hyunbinseo you are right, I think we can close this now :)

**Comment by hyunbinseo** [comment]
> partially implements https://github.com/sveltejs/kit/issues/7161

Note that this issue is not completely resolved.

Maybe it should stay open in the whenever (non-urgent) milestone?

**Comment by divmgl** [comment]
Do we have a solution for this now?
