### ISSUE TITLE
trailingSlash: 'always' not building file structure

### ISSUE THREAD

**Issue by coffeepostal** [sveltejs/kit#7167]
### Describe the bug

I'm trying to generate a static site to be hosted on DreamHost shared server. I spun up a blank skeleton project and added this adapter, but changed nothing else, just to make sure it wasn't some other code of mine messing with it. It's still not working in production.

This is my `svelte.config.js` file:
```
import adapter from '@sveltejs/adapter-static';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter({
			out: 'build',
			trailingSlash: 'always'
		})
	}
};

export default config;
```

This is my `+layout.svelte` file:
```
<h1>Layout</h1>
<nav>
    <a class="nav-item" href="/">Home</a>
    <a class="nav-item" href="about">About</a>
</nav>
<main>
    <slot />
</main>
```

This is my `+layout.js` file:
```
export const prerender = true;
```

And my `+page.svelte' files are:
```
<h1>Index</h1>
```
and
```
<h1>About</h1>
```

It generates this files structure:
```
root
  - _app
  - about.html
  - faviceon.png
  - index.html
```

Everything works fine on dev; and, in the build, as long as you only use the navigation, the secondary pages load fine, but as soon as you refresh or try to navigate to a secondary page by URL, it returns not found.

Additionally, if you add `.html` to the secondary page URL, it will load, but if you add that to the navigation, it won't build. Any help would be greatly appreciated!

### Reproduction

https://github.com/coffeepostal/sveltekit-static-test

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Xeon(R) CPU           W3680  @ 3.33GHz
    Memory: 22.54 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    npm: 8.18.0 - /usr/local/bin/npm
  Browsers:
    Firefox Developer Edition: 71.0
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.96 => 1.0.0-next.96 
    @sveltejs/adapter-static: ^1.0.0-next.44 => 1.0.0-next.44 
    @sveltejs/kit: next => 1.0.0-next.511 
    svelte: ^3.44.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.6
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
`trailingSlash` isn't an adapter-specific option. Your `svelte.config.js` should look like this:

```diff
import adapter from '@sveltejs/adapter-static';
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter({
			out: 'build',
-			trailingSlash: 'always'
		}),

+		trailingSlash: 'always'
	}
};

export default config;
```

**Comment by coffeepostal** [comment]
OH MY GOD! That's it! Thank you @Rich-Harris!
