### ISSUE TITLE
sveltekit - adapter-node: string_decoder is not supported resolving ES modules

### ISSUE THREAD

**Issue by kpopovic** [sveltejs/kit#7173]
### Describe the bug

when I try to run the build (npm run build --> vite build) the following error is shown:

string_decoder/' is not supported resolving ES modules imported from /home/kpopovic/Development/web-apps/zimmerfrei-web-app-sveltekit-bootstrap/.svelte-kit/standalone-node-build/server/chunks/hooks.server-257a44cd.js
Did you mean to import string_decoder/lib/string_decoder.js?

### Reproduction

**svelte.config.js**

//import adapter from '@sveltejs/adapter-auto';
import adapter from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		adapter: adapter({ out: '.svelte-kit/standalone-node-build' })
	}
};

export default config;

**vite.config.js**
import { sveltekit } from '@sveltejs/kit/vite';

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit()]
};

export default config;

### Logs

```shell
Starting the app
#### start with node: node .svelte-kit/standalone-node-build/index.js // dev local notebook
#### start with pm2:  HOST=127.0.0.1 pm2 start standalone-node-build/index.js --name app // production

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                            ^
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/kpopovic/Development/web-apps/zimmerfrei-web-app-sveltekit-bootstrap/node_modules/string_decoder/' is not supported resolving ES modules imported from /home/kpopovic/Development/web-apps/zimmerfrei-web-app-sveltekit-bootstrap/.svelte-kit/standalone-node-build/server/chunks/hooks.server-257a44cd.js
Did you mean to import string_decoder/lib/string_decoder.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:425:17)
    at moduleResolve (node:internal/modules/esm/resolve:1006:10)
    at defaultResolve (node:internal/modules/esm/resolve:1214:11)
    at nextResolve (node:internal/modules/esm/loader:165:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:844:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:431:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///home/kpopovic/Development/web-apps/zimmerfrei-web-app-sveltekit-bootstrap/node_modules/string_decoder/'
}
```

### System Info

```shell
# npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 25.50 GB / 31.26 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/adapter-node: ^1.0.0-next.96 => 1.0.0-next.96 
    @sveltejs/kit: next => 1.0.0-next.507 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.6 => 3.1.6
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Please provide a minimal reproduction as a clonable repo or an project on StackBlitz, as requested in the issue template.

**Comment by georgykarpenko** [comment]
Same problem here after updating from "~1.0.0-next.46" to  "^1.0.0-next.96". 
One of the build/server/chunks/ has 
`import 'string_decoder/';` in it.

Chunk is build from '+page.server.js' with only two imports: 
`import {error}           from "@sveltejs/kit";
import {firestore} from "$lib/firebase.js";`

**Comment by kpopovic** [comment]
> Please provide a minimal reproduction as a clonable repo or an project on StackBlitz, as requested in the issue template.

Hello,
it seams that problem is with winston logging.

[https://stackblitz.com/edit/sveltejs-kit-template-default-uoasnv?file=src/hooks.server.js](url)

1. npm run build

> Using @sveltejs/adapter-node
Circular dependency: node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_readable.js -> node_modules/readable-stream/lib/_stream_duplex.js
Circular dependency: node_modules/readable-stream/lib/_stream_writable.js -> node_modules/readable-stream/lib/_stream_duplex.js -> node_modules/readable-stream/lib/_stream_writable.js
Circular dependency: node_modules/winston-transport/index.js -> node_modules/winston-transport/legacy.js -> node_modules/winston-transport/index.js
Circular dependency: node_modules/async/internal/wrapAsync.js -> node_modules/async/asyncify.js -> node_modules/async/internal/wrapAsync.js
  ✔ done

2. node build/index.js

> Error: Directory import '/home/projects/sveltejs-kit-template-default-uoasnv/node_modules/string_decoder/' is not supported resolving ES modules imported from /home/projects/sveltejs-kit-template-default-uoasnv/build/server/chunks/hooks.server-cf1810b5.js
Did you mean to import string_decoder/lib/string_decoder.js?
    at async ESMLoader.import (https://sveltejs-kit-template-default-uoasnv.w.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:6:1209286)
    at async i.loadESM (https://sveltejs-kit-template-default-uoasnv.w.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:6:246622)
    at async handleMainPromise (https://sveltejs-kit-template-default-uoasnv.w.staticblitz.com/blitz.c3f3eab0760382367e86f2a862c18516376c36f4.js:6:989295) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///home/projects/sveltejs-kit-template-default-uoasnv/node_modules/string_decoder/'

**see hooks.server.js as starting point.**

**Comment by dominikg** [comment]
continued in #7190
