### ISSUE TITLE
Unable to use adapter-static in newer SvelteKit versions

### ISSUE THREAD

**Issue by johnnysprinkles** [sveltejs/kit#7179]
### Describe the bug

Hello, I'm trying to upgrade my very old SvelteKit 350 app to the latest SvelteKit 511 with all the new goodness. I'm using adapter-static to spit out out a bunch of html files that I serve statically. After upgrading I had it complain about "Encountered dynamic routes" so I started making a repro case. But now in my repro case which is just the skeleton app and has no dynamic routes, I'm getting the same issue. Let's address one thing at a time then.

### Reproduction

Repro case is here:

https://github.com/johnnysprinkles/sveltekit_static_dynamic/commits/main

Commit 1 is just the bone stock skeleton app.
Commit 2 switches over the "adapter-static"

Then I do "npm run build" and I get:

```
> Using @sveltejs/adapter-static
  @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root +layout.js/.ts file — see https://kit.svelte.dev/docs/page-options#prerender for more details
    - src/routes
error during build:
Error: Encountered dynamic routes
    at adapt (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/@sveltejs/adapter-static/index.js:35:12)
    at adapt (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/@sveltejs/kit/src/core/adapt/index.js:28:8)
    at Object.handler (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/@sveltejs/kit/src/exports/vite/index.js:488:12)
    at async PluginDriver.hookParallel (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/rollup/dist/es/shared/rollup.js:22632:17)
    at async Object.close (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/rollup/dist/es/shared/rollup.js:23709:13)
    at async Promise.all (index 0)
    at async build (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/vite/dist/node/chunks/dep-db16f19c.js:45667:13)
    at async CAC.<anonymous> (file:///Users/jpsimons/dev/sveltekit_static_dynamic/node_modules/vite/dist/node/cli.js:748:9)
```

Looking into the source code, it's checking for any dynamic routes here:
https://github.com/sveltejs/kit/blob/9a941a13f4b40b903a2e676d92152c75f06290a0/packages/adapter-static/index.js#L27

And there is some logic to see if the route is dynamic here:
https://github.com/sveltejs/kit/blob/9a941a13f4b40b903a2e676d92152c75f06290a0/packages/kit/src/core/adapt/builder.js#L50

But it doesn't appear that anything is being filtered according to that value, so it looks like all routes are considered "dynamic".

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 76.33 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Firefox: 105.0.1
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80
    @sveltejs/adapter-static: ^1.0.0-next.44 => 1.0.0-next.44
    @sveltejs/kit: next => 1.0.0-next.511
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.6
```

### Severity

blocking an upgrade

**Comment by johnnysprinkles** [comment]
Note that I also tried adding `export const prerender = true` to no avail.

**Comment by dominikg** [comment]
Your reproduction does not contain this file:

```js
// /src/routes/+layout.js
export const prerender = true;
```

once you add that to the skeleton project created by `npm create svelte@latest` it'll work with adapter-static. Another option is to define a fallback.

Both of which are mentiond in the error message, including links to the relevant documentation

```
> Using @sveltejs/adapter-static
  @sveltejs/adapter-static: all routes must be fully prerenderable (unless using the 'fallback' option — see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode). Try adding `export const prerender = true` to your root +layout.js/.ts file — see https://kit.svelte.dev/docs/page-options#prerender for more details
    - src/routes
```

**Comment by johnnysprinkles** [comment]
Ah got it now, yeah I was thinking layout is optional and I was trying to do it from `<script context=module>` in the +page.svelte, but the new way I believe is to use +page.js. It works either there or in +layout.js. All good now, thanks for the free tech support.
