### ISSUE TITLE
Redirect in +layout.server.ts still leads to execution of load method in current +page.server.ts

### ISSUE THREAD

**Issue by Cluster2a** [sveltejs/kit#7185]
### Describe the bug

After login, the user is redirected to a specific route (in my case 'dashboard').

In the **+layout.server.ts** I am checking for specific conditions (user has a team) and redirecting the user to another page if no team is assigned.
```JavaScript
/** @type {import('./$types').LayoutServerLoad} */
export async function load({ locals }) {

	let redirectPath = null;

	const user: VerifyUser | null = locals.auth;

	if (!user) {
		redirectPath = '/auth/login';
	} else {
		if (!user.team) {
			redirectPath = '/wizard';
		}
	}

	if (redirectPath !== null) {
		throw redirect(302, redirectPath);
	}

	return {
		user
	};
}
```

Even though the user is being redirected the load method within **+page.server.ts** of the original URL ('dashboard') is being called.

I would expect that the redirect is happening without the load method of the page is being called.

### Reproduction

- create route test/+page.server.ts
- Add load method to the test/+page.server.ts
- create +layout.server.ts
- add redirect within +layout.server.ts
- call test within the browser
- user gets redirected, but the load method of test/+page.server.ts is being executed

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
    Memory: 2.41 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.4.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.96 => 1.0.0-next.96 
    @sveltejs/kit: 1.0.0-next.511 => 1.0.0-next.511 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.6 => 3.1.6
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is intended. For speed, all `load`s (for the layouts and for the page) are run in parallel. You can use `await parent()` in a child `load` if you want it to wait for its parent before proceeding. I believe there are other issues in this repo discussing potential features to provide another way to deal with this.
