### ISSUE TITLE
FormData works differently on Cloudflare Pages

### ISSUE THREAD

**Issue by m4tr1k** [sveltejs/kit#7186]
### Describe the bug

I'm hosting a project on Cloudflare Pages, and in some endpoints, I'm using multipart requests to send files to the server. Behaviour is not the same locally and in production, so I decided to simulate Cloudflare environment with wrangler.

What I found was that the file sent is processed differently in both environments. Locally it is a normal File, however, in production, it is a string. Below I'll attach both outputs from `console.log`

Local:
```
{
  ...
  profilePic: File {},
}
```

Production:

```
{
  ...
  profilePic: '�PNG\r\n' +
    '\x1A\n' +
    '\x00\x00\x00\rIHDR\x00\x00\x00�\x00\x00\x00�\b\x06\x00\x00\x00$`\x0F�\x00\x00\x00\x19tEXtSoftware\x00Adobe ImageReadyq�e<\x00\x00\x1E�IDATx��]\tx\x14E�drN\x12\x12B\x12��\b\x04�p]\x0E�C��\x14\br�? ����!\x1E("*����*,\b\b\x02�\n' + ...
}
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-blmugs?file=package.json

Some problems when requesting the endpoint but the point is there.
The best way to reproduce this is to run this project twice, one with `npm run dev` and other with `wrangler` (after running `npm run build` with `@sveltejs/adapter-cloudflare`) with this command: `wrangler pages dev --port 3002 .svelte-kit/cloudflare/`

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 326.18 MB / 16.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.80 
    @sveltejs/adapter-cloudflare: ^1.0.0-next.38 => 1.0.0-next.38 
    @sveltejs/kit: 1.0.0-next.450 => 1.0.0-next.450 
    svelte: ^3.50.1 => 3.50.1 
    vite: ^3.1.6 => 3.1.6
```

### Severity

serious, but I can work around it

### Additional Information

I'm using version 450 because of #6739 which makes it impossible for me to use the latest version of SvelteKit. It would be interesting to test this with the latest version of SvelteKit to see if it is still a current problem or was already fixed.

**Comment by The-Noah** [comment]
This is not an issue with SvelteKit but rather a limitation of Cloudflare Workers (which Pages runs on). Workers has a compatability flag you can enable to receive a `File` instead of a `string`, however it is not possible to enable this for Pages *yet*.

Two solutions:

### Use a Worker for file uploads
Here is a great tutorial: https://walshy.dev/blog/21_09_10-handling-file-uploads-with-cloudflare-workers

### Always use a string
In my own project, I've decided to go the route of base64 encoding the File on the client then decoding it on the backend.

**Comment by m4tr1k** [comment]
> This is not an issue with SvelteKit but rather a limitation of Cloudflare Workers (which Pages runs on). Workers has a compatability flag you can enable to receive a `File` instead of a `string`, however it is not possible to enable this for Pages _yet_.
> 
> Two solutions:
> 
> ### Use a Worker for file uploads
> Here is a great tutorial: https://walshy.dev/blog/21_09_10-handling-file-uploads-with-cloudflare-workers
> 
> ### Always use a string
> In my own project, I've decided to go the route of base64 encoding the File on the client then decoding it on the backend.

Thank you so much for your input. I'll probably go towards the second option, but I'll explore both and will let you know if I was able to fix it

**Comment by dummdidumm** [comment]
Closing as there's nothing we can do about it, and a workaround seems to be present.
