### ISSUE TITLE
Failed to load resource when I implemented in Google Cloud Run with custom domain

### ISSUE THREAD

**Issue by angelserranoperez** [sveltejs/kit#719]
**Describe the bug**
I use Google Cloud Run to run my svelte kit app.
Default version:
https://youernes-22w6ta6irq-ew.a.run.app/planes/UEVytEBG6rfcLrdqflD8TsjmCRn2_1611080173358
Custom domain version:
https://youernes.com/planes/UEVytEBG6rfcLrdqflD8TsjmCRn2_1602059251917

**In the custom domain version I can not access to information though It can fetch data from script module.** 

I use the node adapter and this is my following configuration:
```
const sveltePreprocess = require("svelte-preprocess");
	const node = require('@sveltejs/adapter-node');
	const pkg = require('./package.json');

	/** @type {import('@sveltejs/kit').Config} */
	module.exports = {
		preprocess: [
			sveltePreprocess({
				defaults: {
					style: "postcss",
				},
				postcss: true
			}),
		],
		kit: {
			hostHeader: 'X-Forwarded-Host',
			// By default, `npm run build` will create a standard Node app.
			// You can create optimized builds for different platforms by
			// specifying a different adapter
			adapter: node(),

			// hydrate the <div id="svelte"> element in src/app.html
			target: '#svelte',

			vite: {
				ssr: {
					noExternal: Object.keys(pkg.dependencies || {})
				}
			}
		}
	};
```

1st I run 
npm run build

and 
2nd I use docker 
```
FROM node:12

WORKDIR /youernes

ENV PORT=8080

ENV HOST=0.0.0.0

COPY . .

CMD [ "node" , "build/" ]
```

We can choose the plans from:
https://youernes-22w6ta6irq-ew.a.run.app/yhoyquetoca
https://youernes.com/yhoyquetoca

**Comment by Conduitry** [comment]
GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

There's also no way for anyone to try to reproduce this with what you've provided.
