### ISSUE TITLE
XSS during server side rendering

### ISSUE THREAD

**Issue by valterkraemer** [sveltejs/kit#721]
**Describe the bug**

It is possible to inject a script tag into the HTML during server side rendering. The content of `svelte-data`-scripts aren't escaped.

Also tested it on Sapper and there it is escaped.

**Logs**

--

**To Reproduce**

##### user.json.js
```js
export async function get() {
  const user = {
    name: "</script><script>alert('xss')</script>"
  };

  return {
    body: user
  };
}

```

##### index.svelte
```html
<script context="module">
  export async function load({ fetch }) {
    const res = await fetch('/user.json');

    return {
      props: {
        user: await res.json()
      }
    };
  }
</script>

<h1>My heading</h1>
```

##### On the rendered page
```html
<script type="svelte-data" url="/user.json">{"status":200,"statusText":"","headers":{"content-type":"application/json"},"body":"{\"name\":\"</script><script>alert('xss')</script>\"}"}</script>
```

##### Sapper does something like this (shortened):

```html
<script>__SAPPER__={preloaded:[void 0,{user:{name:"\u003C\u002Fscript\u003E\u003Cscript\u003Ealert('xss')\u003C\u002Fscript\u003E"}}]};</script>
```

**Expected behavior**

The content inside `svelte-data` would be escaped.

**Stacktraces**

--

**Information about your SvelteKit Installation:**

```
System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 328.02 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.5 - ~/.nvm/versions/node/v14.5.0/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Browsers:
    Brave Browser: 89.1.21.77
    Firefox: 86.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.61 
    svelte: ^3.29.0 => 3.35.0
```

- Your browser

Tested in all three

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)

adapter-node

**Severity**

High, possible to work around, but everybody would have to be aware of it, and mistakes can easily happen.

**Additional context**

--

**Comment by Conduitry** [comment]
Hm. Yeah. @Rich-Harris I know you liked the  `<script type>` thing because it sped up parsing, but is there a reasonable way to deal with this?

**Comment by valterkraemer** [comment]
> Hm. Yeah. @Rich-Harris I know you liked the `<script type>` thing because it sped up parsing, but is there a reasonable way to deal with this?

Don't think that's the issue here. If `<script>` wouldn't be escaped in Sapper (`\u003C\u002Fscript\u003E...`), it would have the same problem. Or did I misunderstand something @Conduitry?

**Comment by Rich-Harris** [comment]
Thanks for flagging this. I'm pretty sure we can use the [escaping logic from `devalue`](https://github.com/Rich-Harris/devalue/blob/master/src/index.ts#L240-L268), which is what Sapper uses:

```ts
const escaped: Record<string, string> = {
	'<': '\\u003C',
	'>' : '\\u003E',
	'/': '\\u002F',
	'\\': '\\\\',
	'\b': '\\b',
	'\f': '\\f',
	'\n': '\\n',
	'\r': '\\r',
	'\t': '\\t',
	'\0': '\\0',
	'\u2028': '\\u2028',
	'\u2029': '\\u2029'
};

// ...

function stringifyString(str: string) {
	let result = '"';

	for (let i = 0; i < str.length; i += 1) {
		const char = str.charAt(i);
		const code = char.charCodeAt(0);

		if (char === '"') {
			result += '\\"';
		} else if (char in escaped) {
			result += escaped[char];
		} else if (code >= 0xd800 && code <= 0xdfff) {
			const next = str.charCodeAt(i + 1);

			// If this is the beginning of a [high, low] surrogate pair,
			// add the next two characters, otherwise escape
			if (code <= 0xdbff && (next >= 0xdc00 && next <= 0xdfff)) {
				result += char + str[++i];
			} else {
				result += `\\u${code.toString(16).toUpperCase()}`;
			}
		} else {
			result += char;
		}
	}

	result += '"';
	return result;
}

**Comment by Conduitry** [comment]
What sort of escaping is supported in unknown `<script type>` tags? I'm not sure how browsers parse those. Is your intention to still be able to use the contents of the element as directly as we're already doing?

**Comment by Conduitry** [comment]
Oh. Disregard that, I think. I see we're already doing `JSON.parse(script.textContent)` which means yeah, we should just be escaping the strings as mentioned above. I was working from a misremembered version of this feature and/or early plans for it before it was implemented.
