### ISSUE TITLE
Unable to set custom headers in hooks.server.js

### ISSUE THREAD

**Issue by jasongitmail** [sveltejs/kit#7219]
### Describe the bug

I'm attempting to set a site-wide custom header using `hooks.server.js`.

However the custom header isn't appear in the HTTP response when viewed in a browser dev console.

![Screen Shot 2022-10-11 at 10 02 56 AM](https://user-images.githubusercontent.com/50032291/195128048-6f724249-0a47-44c7-a29f-9c9f02d01e4f.png)

### Reproduction

1. `npm create svelte@latest proj` (choose Skeleton project)
2. Add `src/hooks.server.js` containing:

```js
/** @type {import('@sveltejs/kit').Handle} */
export async function handle({ event, resolve }) {
  const response = await resolve(event);
  response.headers.set('x-custom-header', 'potato');
  console.log('response.headers:', response.headers);
  return response;
}
```
3. `npm run dev`
4. Visit the URL in a web browser.
5. The HeadersList will be console logged and will contain all expected heades--default & custom. However, with the browser dev console open and viewing network request response headers, only default headers are listed and _no_ custom headers appear.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: 105.0.2

	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"svelte": "^3.44.0",
		"vite": "^3.1.0"
	},
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The use case I'm working on requires custom headers or the code won't work.

**Comment by Conduitry** [comment]
I can't reproduce this. `x-custom-header: potato` is present for me in HTML responses in the browser dev tools.

**Comment by jasongitmail** [comment]
Another datapoint: A colleague tested via the repro steps on on this issue, using his laptop and Chrome and FireFox, and observed the same behavior with no custom headers on the response that is show in the web browser.

**Comment by Conduitry** [comment]
Have you tried `curl -I http://localhost:5173` to directly see what response is coming back without any potential browser interference?

**Comment by jasongitmail** [comment]
Whoa! The headers are being set, as confirmed via CURL. Not sure why they don't appear in Chrome or FireFox dev console, but that might be an artifact of the `npm run dev`, as opposed to a production build.

Thank you!

**Comment by jasongitmail** [comment]
To add a note for others: Although headers do not show up when using `npm run dev`, they do show up for production builds. Using the node adapter, I ran: `npm run build && npm run preview` and the headers are present.
