### ISSUE TITLE
Unhelpful error message for `throw invalid()`

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#7224]
### Describe the bug

Using `throw invalid()` instead of `return invalid()` in an action displays an unhelpful error message in the server console: `[object Object]`

My silly brain decided to spend over an hour trying to debug this without realising I was using `throw` where I needed to use `return` (despite using form actions since it came out).

It may be helpful to return a more useful error message so someone else doesn't fall into the same trap.

### Reproduction

Press the submit button.

Expected: action returns form values to page.

Actual: error message in console: [object Object]

https://stackblitz.com/edit/sveltejs-kit-template-default-q9n9ns?file=src/routes/+page.server.js

### Logs

```shell
[object Object]
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.81 
    @sveltejs/kit: next => 1.0.0-next.512 
    svelte: ^3.46.0 => 3.51.0 
    vite: ^3.1.0 => 3.1.7
```

### Severity

annoyance

**Comment by alphaelf** [comment]
why we can't throw invalid like redirect?

i have use case for  adding validation functionality to request object via `hooks.server.ts` :
```typescript
import type { Schema } from 'zod'
import { invalid, type Handle } from '@sveltejs/kit'

export const handle: Handle = async ({ event, resolve }) => {
  event.request.validate = async (schema: Schema) => {
    const data = Object.fromEntries((await event.request.formData()))
    const validation = await schema.safeParseAsync(data)
    if (!validation.success)
      throw invalid(422, {errors: validation.error.flatten().fieldErrors})
    return validation.data
  }
  return resolve(event)
}
```
and in `+page.server.ts` i can use it as:
```typescript
import type { Actions } from "./$types"
import { z as Schema } from 'zod'

export const actions:Actions = {
  default: async ({ request }) => {
    const schema = Schema.object({
      username: Schema.string().min(3),
      password: Schema.string().min(3)
    })
    const payload:Schema.infer<typeof schema> = await request.validate(schema)
    // payload is my validated data
  }
}
```
but i get your helpful error in terminal 😔 
```terminal
Cannot "throw invalid()". Use "return invalid()"
```

**Comment by s3812497** [comment]
> why we can't throw invalid like redirect?

I don't think you can throw redirect in `hooks.server.ts`. You need to return a `Response` object from the `handle` function.

I believe that these helpers can only be used for:
* `invalid` - actions
* `redirect` - actions, load functions

Also, the framework requires you to use `return invalid()` because of it expects to return to the same page (and return the invalid data) while only catching redirects and unexpected errors ([see how it works here](https://github.com/sveltejs/kit/blob/dcb9d3dc494422dce1996ffe56630fd52090d0ba/packages/kit/src/runtime/server/page/actions.js#L127)).

**Comment by alphaelf** [comment]
> I don't think you can throw redirect in hooks.server.ts. You need to return a Response object from the handle function.

if you look at my code in `hook.server.ts` i put `throw invalid` in `validate` method that's part of `request` object and it run at actions 
but guess what i add [same code for redirect](https://github.com/sveltejs/kit/blob/dcb9d3dc494422dce1996ffe56630fd52090d0ba/packages/kit/src/runtime/server/page/actions.js#L141-L147) to sveltekit `actions.js` and it works as i expected

`runtime/server/page/actions.js`
```typescript
...
if(error instanceof ValidationError){
  return action_json({
    type: 'invalid',
    status: error.status,
    data: error.data
  });
}
...
```
`runtime/server/utils/error.js`
```typescript
import { HttpError, Redirect, ValidationError } from '../runtime/control.js';
...
export function normalize_error(error) {
  return /** @type {Redirect | HttpError | Error | ValidationError} */ (error);
}
```

**Comment by s3812497** [comment]
> if you look at my code in `hook.server.ts` i put `throw invalid` in `validate` method that's part of `request` object and it run at actions 

Oops, you're right! Forgive me. I did not notice that it was setting a method and thought it was running immediately 😅
