### ISSUE TITLE
Returning invalid with 4xx status code from an action results in 200 HTTP status

### ISSUE THREAD

**Issue by SylvainGarrigues** [sveltejs/kit#7233]
### Describe the bug

```
export const actions = {
	default: async ({ request }) => {
			return invalid(400, {foo: true})
         }
}
```

returns a HTTP 200 status response to the browser while I would expect a 400 HTTP status (from what I understand in the doc).

Should I throw invalid instead?

### Reproduction

Have a +page.server.js with above code or check:
https://github.com/SylvainGarrigues/sveltekit-action-codes

### System Info

```shell
any
```

### Severity

annoyance

**Comment by Conduitry** [comment]
`return invalid` is correct. This is working fine in my own app. Please provide a complete reproduction.

**Comment by SylvainGarrigues** [comment]
+page.svelte

```
<script>
	import { enhance } from '$app/forms'
</script>

<form method="POST" use:enhance>
	<input name="email" type="email" />
	<input name="password" type="password" />
	<button>Log in</button>
</form>
```

+page.server.js
```
import { invalid } from "@sveltejs/kit";

/** @type {import('./$types').Actions} */
export const actions = {
  default: async () => {
    return invalid(400, { error: "something is wrong" });
  },
};
```

With `use:enhance`, server replies with **200** HTTP status code (not talking about the status field of the JSON payload), while it replies with **400** without it. Is that intended?

**Comment by dominikg** [comment]
@SylvainGarrigues 

This is the description directly below the required field "Reproduction" in our issue form. Please reread and provide the information we asked for.
> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by SylvainGarrigues** [comment]
Please check https://github.com/SylvainGarrigues/sveltekit-action-codes.
It's merely the skeleton app created by create-svelte, with action code from SvelteKit doc.

2 pages there, one with use:enhance, one without. POST response is 400 in one case, 200 in the other.

**Comment by dominikg** [comment]
This is by design. To be able to render validation errors on the same page in case of 400, or an error page in case of other errors, the response code is 200, but if you check the response body* you'll see the 400 code contained in there and the enhanced form should act accordingly.

*
```
{"type":"invalid","status":400,"data":{"error":"something is wrong"}}
```

**Comment by Conduitry** [comment]
To add on to that, when using a JS-enhanced form, [`$page.status`](https://kit.svelte.dev/docs/types#sveltejs-kit-page) _will_ be updated with the 400 status code, if you have anything that's looking at that.

**Comment by SylvainGarrigues** [comment]
@dominikg  @Conduitry I know the `status` field of the JSON payload in the response body matches the provided status in the call to invalid`, but I just find it strange that (by design) the same SvelteKit endpoint code produces inconsistent HTTP status code response whether called from JS or from other mean.

Couldn't the server reply with the same consistent HTTP (not in the body) status code from `ìnvalid` (), and the JS code of enhance still be able to populate $page.form or $page.status on the same page?

**Comment by SylvainGarrigues** [comment]
I'm questioning the design of HTTP response statuses, that's all - not the content of the JSON payload which is in turn correct.

**Comment by dummdidumm** [comment]
It's like this to distinguish `return invalid` from `throw error` or other unexpected errors. `throw error` could have any status code, so you could distinguish it on the client only by carefully inspecting the payload, which would be bad.

**Comment by Strutyk** [comment]
I think it would be correct, by web standards, for `fail(400, {...})` to return an HTTP status of 400 with `use:enhance` on the form.
