### ISSUE TITLE
Support for local storage stores

### ISSUE THREAD

**Issue by luke-hagar-sp** [sveltejs/kit#7235]
### Describe the problem

Local Storage can be a headache with values not populating until the component mounts, which can cause delays in things like style preferences or themes

The below solution helps but there are inherent delays in how quickly the items can be retrieved due to how Svelte loads components.

Can a solution be implemented that similarly populates stores with local storage data as early as possible in browser/page load?

### Describe the proposed solution

The best implementation I have seen for this is: https://github.com/babichjacob/svelte-localstorage

but this solution still works inside of the standard Svelte loads, can a faster solution be implemented?

### Alternatives considered

https://github.com/babichjacob/svelte-localstorage

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
You can access the localStorage inside `load` in the browser, so the data is already present then.

```js
// +page.js
import { browser } from '$app/environment';

export function load() {
  if (browser) {
    return { someValue: localStorage.get('someValue');
  }
}
```

Closing as these things are possible to solve in user-land. Also watch #7105 for a more generic/related solution to this.
