### ISSUE TITLE
SvelteKit app slows down browser

### ISSUE THREAD

**Issue by IRod22** [sveltejs/kit#7250]
### Describe the bug

Whenever I load my app with `npx vite dev`, and open it in the browser, the browser freezes up or gets slowed down; that is what my Chrome and FireFox browsers indicate (I did not test MS Edge because of its Promise issues, which I think Svelte, SvelteKit and/or Vite relies on when in the browser).

### Reproduction

https://github.com/IRod22/svelte-math

### Logs

I could not see any browser logs in FireFox or Chrome, and there were no error logs emitted by Vite except for an unused style rule. There were no logs other than that.

### System Info

*(edited to show relevant browsers)*
```diff
   System:
     OS: Windows 10 10.0.19043
     CPU: (2) x64 Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
     Memory: 376.29 MB / 3.91 GB
   Binaries:
     Node: 17.8.0 - C:\Program Files\nodejs\node.EXE
     npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
   Browsers:
+    Chrome: 106.0.1370.42
+    Firefox: 105.0.3
-    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
-    Internet Explorer: 11.0.19041.1566
   npmPackages:
     @sveltejs/adapter-auto: next => 1.0.0-next.75
     @sveltejs/kit: next => 1.0.0-next.483
     svelte: ^3.46.0 => 3.50.1
     vite: ^3.1.0 => 3.1.1
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
You created an endless loop somewhere in side your `Expr` component, it keeps firing `onchange` indefinetly, which is why the browser freezes.

**Comment by IRod22** [comment]
:man_facepalming: Thank you.
