### ISSUE TITLE
Cannot read properties of undefined (reading 'disable_scroll_handling')

### ISSUE THREAD

**Issue by secretgspot** [sveltejs/kit#7257]
### Describe the bug

Just appeared out of nowhere and bricked the whole app, won't go away no matter what.  Tried deleting node_modules + .svelte-kit then reinstall and still there.

```txt
navigation.js?v=92264f1c:16 
Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling') at navigation.js?v=92264f1c:16:11


Fails on:
export const disableScrollHandling = ssr
	? guard('disableScrollHandling')
	: client.disable_scroll_handling;  <---

with message: Uncaught TypeError: Cannot read properties of undefined (reading 'disable_scroll_handling')
```

### Reproduction

<https://github.com/secretgspot/sveltekit-auth-helper-bug>

installed sveltekit latest,
installed supabase-js v2,
installed auth-helpers-sveltekit

### System Info

```shell
{
	"name": "myapp",
	"version": "0.0.1",
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview"
	},
	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"svelte": "^3.46.0",
		"vite": "^3.1.0"
	},
	"type": "module",
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.0",
		"@supabase/auth-helpers-sveltekit": "^0.8.2",
		"@supabase/supabase-js": "^2.0.0-rc.10"
	}
}
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
You need to provide a provide reproduction as instructed by the issue template.

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by secretgspot** [comment]
After trying every combination I found that if I delete hooks.client.js which only contains 

```js
import '$lib/db';
```

it first yells at me with 
```txt
Failed to resolve import "../../src/hooks.client.js" from ".svelte-kit\generated\client-manifest.js". Does the file exist?
Failed to resolve import "../../src/hooks.client.js" from ".svelte-kit\generated\client-manifest.js". Does the file exist? (x2)
3:00:00 AM [vite] Internal server error: Failed to resolve import "../../src/hooks.client.js" from ".svelte-kit\generated\client-manifest.js". Does the file exist?
  Plugin: vite:import-analysis
  File: V:/xxx/.svelte-kit/generated/client-manifest.js
  1  |  import * as client_hooks from '../../src/hooks.client.js';
     |                                 ^
  2  |  
  3  |  export { matchers } from './client-matchers.js';
```
then when I restart the server, error goes away. 
I returned the hooks.client.js and sure enough error returned after restarting the server

**Comment by dummdidumm** [comment]
I can't reproduce this given the instructions. Please provide a repository with the minimum reproducible.

**Comment by dummdidumm** [comment]
Remove `import { goto } from '$app/navigation';` from `lib/db/index.js` and it works.

The problem is that `hooks.client.js` is called before the client with its methods is initialized, so if you import `$app/navigation` in there, which uses the not-initialized client, it breaks. I'm not sure how we best deal with this. We could 
- try to do some import analysis on `hooks.client.js` similar to the env/server analysis and throw a more meaningful error if we encounter an invalid import
- initialize the client right away with some placeholder so accessing its values doesn't throw
- wrap using the client's values with functions so access is lazy

I feel like the first option is the one that makes the most sense, the others just hide misuse and wouldn't prevent that nebolous error if someone would access the client's methods.

**Comment by yasserlens** [comment]
I also had this issue, and it refused to go, until I removed $app/navigation from a component in $lib. Then once it was resolved, I got $app/navigation back into the same component and I never saw this issue again. Not sure how it was is now magically gone but that makes me nervous about production.

I'll aim to move the goto function out of components by propagating events up to be handled by pages under routes instead just to be on the safe side.

**Comment by justingolden21** [comment]
Encountered this too but on refresh it works. Hoping it doesn't appear in prod, as something similar happened in prod (!!!) somewhat recently and idk what caused it.

**Comment by tony19** [comment]
This can be reproduced without `hooks.client.js` (see [repro](https://github.com/tony19-sandbox/sveltekit-storybook-bug)). If you use SvelteKit with Storybook, the bug appears if any of your storied components import `$app/navigation`.

**Comment by roprice** [comment]
FYI, I can reproduce this in the UI by creating any table then attempting to edit it. Even when I successfully CRUD, I still get it, weird
![Screenshot 2023-04-05 at 4 22 32 PM](https://user-images.githubusercontent.com/19863/230110490-27258e38-b999-455e-8338-b6df01ad2cb6.png)

**Comment by aidvai-sp** [comment]
I also get this error but when trying to `beforeNavigate` from `$app/navigation`. Commenting out this import and the code snippet that uses it fixes the problem

**Comment by MelodicCrypter** [comment]
I'm also experiencing the "disable_scroll_handling" issue

![Screenshot 2023-04-14 at 1 58 30 PM](https://user-images.githubusercontent.com/18341500/231954122-cf8f1c43-3bad-46d6-a14e-8f52bda05fdf.png)

Using: `"@sveltejs/kit": "^1.15.5"`

**Comment by Bandit** [comment]
I'm also suddenly getting this after a package (`@skeletonlabs/skeleton@1.2.5`) bumped my Svelte version to `3.5.8`. Literally nothing else changed and now my webserver won't start...

**Comment by davecalleja-casumo** [comment]
I can reproduce this when adding this to my vite config

```
build: {
    rollupOptions: {
      output: {
        manualChunks: (id) => {
          // Magic happens here
          if (id.includes('sentry')) {
            return 'vendor_sentry'
          }
          // Set this as undefined if you want to split your entire bundle.
          return 'vendor'
        }
      }
    }
  }
  ```
  
Follows previous comment that vite is doing something while building / optimising.
