### ISSUE TITLE
Allow package.json customisation when using svelte-package

### ISSUE THREAD

**Issue by tkvw** [sveltejs/kit#7258]
### Describe the problem

I'm always frustrated when `svelte-package` creates a `package.json` not to my liking. 
In a monorepo I have specified the following two entries in the original `package.json` to allow a component library to work with the `svelte-kit` generated website: 
```
  "svelte": "src/lib/index.ts",
  "types": "src/lib/index.ts",
```
This is shamefully copied by the `svelte-package` library. 

### Describe the proposed solution

Allow `packageJson` generation to be overwritten in the `package` config section of `svelte.config.js`. 

``` 
/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: preprocess(),
  kit: {
    adapter: adapter()	
  },
  package: {
	mergePackageJson: (original,proposed) => proposed // default = proposed, false = skip 
  }
};

```

### Alternatives considered

Post edit the generated package.json

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Somewhat related to #6824

**Comment by tkvw** [comment]
FWIW I create a  `svelte-package-unpack` [gist](https://gist.github.com/tkvw/ade8c42068fab1610bcad241649fd745) which will copy the package content to the root folder and creates appropriate `package.json` files in subfolders. This allows typescript to find the correct typings and use the package in place (for use in a monorepo). 

Make sure to add the generated folders to the `.gitignore`
The gist can simply be run by npx after build: 
```
// package.json
"scripts": {
   "build": "svelte-kit sync && svelte-package && npx --yes https://gist.github.com/tkvw/ade8c42068fab1610bcad241649fd745/dfb552d06cea7ae9821456d9ac0678bc428f1e9b",
}
```

I think having the transpiled javascript in the root package with an appropriate `.gitignore` is best solution.
