### ISSUE TITLE
More informative error if someone returns a `Response` from `load`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#7262]
### Describe the problem

Per https://github.com/sveltejs/kit/discussions/7259 — if someone does this...

```js
import { json } from '@sveltejs/kit';

export function load() {
  return json({ answer: 42 });
}
```

...they will get a cryptic error:

> DevalueError: Cannot stringify arbitrary non-POJOs

### Describe the proposed solution

It would be easy to catch this case and provide a more specific error:

> `load` must return a plain object rather than a `Response`

For bonus points, it should identify the `load` function in question.

### Importance

nice to have

**Comment by ShaswatPrabhat** [comment]
Can I give this a shot if open @Rich-Harris ?

**Comment by dummdidumm** [comment]
Go for it!
