### ISSUE TITLE
@sveltejs/adapter-static causes vite build --watch to fail

### ISSUE THREAD

**Issue by louisabraham** [sveltejs/kit#7274]
### Describe the bug

@sveltejs/adapter-static causes vite build --watch to fail

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-4skw3p?file=svelte.config.js

`vite build` works

`vite build --watch` returns `Error: Not found: /favicon.png`

### System Info

```shell
https://stackblitz.com/edit/sveltejs-kit-template-default-4skw3p?file=svelte.config.js
```

### Severity

annoyance

**Comment by benmccann** [comment]
This was probably fixed by https://github.com/sveltejs/kit/pull/7516. Let me know if that's wrong and it's still happening
