### ISSUE TITLE
Load not called for child components

### ISSUE THREAD

**Issue by icyrockcom** [sveltejs/kit#728]
**Describe the bug**
Child components' `load` not called.

**Logs**
No errors, just nothing happens.

**To Reproduce**

**index.svelte**

```html
<script lang='ts'>
  import Child from './_Child.svelte';
</script>

<Child />
```

**_Child.svelte**

```html
<script lang='ts' context='module'>
  export async function load({}) {
    const val = 33;

    return {
      props: {
        val
      }
    };
  };
</script>

<script lang='ts'>
  export let val;
</script>

{val}
```

The output is `undefined` instead of the expected `33`.

Let me know if making a sscce repo would be useful.

**Expected behavior**
Child components' `load` should be called.

**Stacktraces**
None.

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1230 V2 @ 3.30GHz
    Memory: 2.76 GB / 7.73 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Firefox: 86.0.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.61 
    svelte: ^3.35.0 => 3.35.0 
```

- Your browser

Firefox.

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)

Node.

**Severity**
Low.

**Additional context**
The same code works if put inside `index.svelte` instead of `_Child.svelte`. `load` in `_Child` is not called at all, though the `<script context='module'>` is entered.

**Comment by babichjacob** [comment]
This is expected behavior.

**Comment by Conduitry** [comment]
As described in https://kit.svelte.dev/docs#loading in the red box, `load` only runs on page components, just like `preload` did in Sapper.

**Comment by babichjacob** [comment]
https://github.com/sveltejs/kit/blob/7166c5760615a94dd2b61613f8224f871f74e96c/documentation/docs/03-loading.md#L23
> `load ` only applies to components that define pages, not the components that they import.

**Comment by icyrockcom** [comment]
@babichjacob @Conduitry Thanks!
