### ISSUE TITLE
Import aliases do not work for generated `$types`, must use relative path instead.

### ISSUE THREAD

**Issue by brev** [sveltejs/kit#7283]
### Describe the bug

When importing generated `$types` files from other directories, it seems that relative paths must be used (`../../../`). If you try to use a path `$alias` instead, you will get a type error.

### Reproduction

https://github.com/brev/sveltekit-issue-import-alias-generated-types

```
git clone https://github.com/brev/sveltekit-issue-import-alias-generated-types
cd sveltekit-issue-import-alias-generated-types
npm install
npm run check
```

Next, edit file: `src/lib/Signup.svelte`, and change this line from a relative path:

```ts
  import type { ActionData } from '../routes/$types'
```

to an aliased path:

```ts
  import type { ActionData } from '$routes/$types'
```

and re-run check:

```bash
npm run check
```

We now get a type error because the import alias is not working:

```
Error: Cannot find module '$routes/$types' or its corresponding type declarations. (ts)
  import type { ActionData } from '$routes/$types'
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz
    Memory: 91.68 MB / 8.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.83
    @sveltejs/kit: next => 1.0.0-next.516
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.1.8
```

### Severity

annoyance

**Comment by s3812497** [comment]
Hi brev,
You'll have to import from './$types' instead. Using the alias `$routes` for `src/routes` is technically incorrect because each route has its own folder for its generated types (you can find this in the `.svelte-kit/types/src/routes` folder)

**Comment by dummdidumm** [comment]
Try setting the alias to `.svelte-kit/types/src/routes` - this is where they are located

**Comment by dummdidumm** [comment]
Just tested this out. Adding 
```js
	kit: {
		// ...
		alias: {
			$routes: '.svelte-kit/types/src/routes'
		}
	},
```

to the `svelte.config.js` and then using `import type { .. } from '$routes/../$types` works as expected.
