### ISSUE TITLE
Edge adapter-netlify not providing platform or context object

### ISSUE THREAD

**Issue by brittneypostma** [sveltejs/kit#7297]
### Describe the bug

Digging into the code for [`adapter-netlify`](https://github.com/sveltejs/kit/blob/master/packages/adapter-netlify/src/edge.js#L17-L31), it looks like platform and context should be provided on the event from the load function. 

There is no such object on the event in my [edge functions log](https://app.netlify.com/sites/demo-sveltekit-edge/edge-functions) and the [client](https://demo-sveltekit-edge.netlify.app/edge) console.
<img width="211" alt="image" src="https://user-images.githubusercontent.com/45889730/196293985-8093b782-8bcd-47fc-8820-17299145da64.png">

Originally I had `adapter-auto` installed and that was causing functions to run in regular the serverless setting and not on the edge network also. I explicitly installed `adapter-netlify` and was able to get it at least running on the edge, but still no platform or context object. I've been looking at it all day and can't see what's wrong. 

### Reproduction

Repo: https://github.com/brittneypostma/demo-sveltekit-edge/blob/main/src/routes/edge/%2Bpage.ts
Endpoint: https://demo-sveltekit-edge.netlify.app/edge

### Logs

```shell
6:04:10 PM: {
  url: URL {
    href: "https://demo-sveltekit-edge.netlify.app/edge",
    origin: "https://demo-sveltekit-edge.netlify.app",
    protocol: "https:",
    username: "",
    password: "",
    host: "demo-sveltekit-edge.netlify.app",
    hostname: "demo-sveltekit-edge.netlify.app",
    port: "",
    pathname: "/edge",
    hash: "",
    search: ""
  },
  params: {},
  data: null,
  routeId: "edge",
  fetch: [AsyncFunction: fetch],
  setHeaders: [Function: setHeaders],
  depends: [Function: depends],
  parent: [AsyncFunction: parent]
}
6:04:10 PM: [render] undefined
6:04:10 PM: [render] undefined
6:09:44 PM: {
  url: URL {
    href: "https://demo-sveltekit-edge.netlify.app/edge",
    origin: "https://demo-sveltekit-edge.netlify.app",
    protocol: "https:",
    username: "",
    password: "",
    host: "demo-sveltekit-edge.netlify.app",
    hostname: "demo-sveltekit-edge.netlify.app",
    port: "",
    pathname: "/edge",
    hash: "",
    search: ""
  },
  params: {},
  data: null,
  routeId: "edge",
  fetch: [AsyncFunction: fetch],
  setHeaders: [Function: setHeaders],
  depends: [Function: depends],
  parent: [AsyncFunction: parent]
}
6:09:44 PM: [render] undefined
6:09:44 PM: [render] undefined
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox Developer Edition: 103.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.83 
    @sveltejs/adapter-netlify: ^1.0.0-next.81 => 1.0.0-next.81 
    @sveltejs/kit: next => 1.0.0-next.516 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
`platform` is only available in `+page.server/layout.js`, not inside `+page/layout.js`

**Comment by brittneypostma** [comment]
@dummdidumm if I change it to `+page.server.js` I get a 500 error on the [route](https://demo-sveltekit-edge.netlify.app/edge).

**Comment by dummdidumm** [comment]
My guess is that the `platform` object contains non-serializable code, so it fails when returning the data from `load`

**Comment by brittneypostma** [comment]
I get these errors in the edge-functions log:

```
6:47:30 AM: Error: Cannot access event.url.hash. Consider using `$page.url.hash` inside a component instead
    at URL.get (file:///root/.netlify/edge-functions/render.js:15240:13)
    at URL.[Deno.privateCustomInspect] (deno:ext/url/00_url.js:386:20)
    at inspectObject (deno:ext/console/02_console.js:1311:36)
    at _inspectValue (deno:ext/console/02_console.js:704:16)
    at inspectValue (deno:ext/console/02_console.js:722:11)
    at inspectValueWithQuotes (deno:ext/console/02_console.js:830:16)
    at inspectRawObject (deno:ext/console/02_console.js:1201:15)
    at inspectObject (deno:ext/console/02_console.js:1359:30)
    at _inspectValue (deno:ext/console/02_console.js:704:16)
    at inspectValue (deno:ext/console/02_console.js:722:11)
```

**Comment by brittneypostma** [comment]
This is on Netlify's end, but it's wanted to use the Svelte store in that generated file. I debated if this was an `adapter-netlify` thing, or something not working well with the edge functions specifically. If it's an issue on our end, I just need to know where to point it to.

**Comment by dummdidumm** [comment]
The problem is the `console.dir (?)` of `event` which also tries to log `url.hash`, and then SvelteKit tries to be helpful telling you that access to it on the server is forbidden because that would never work as expected. There's some code SvelteKit to make this case work for Node environments, but the edge isn't such an environment so my guess it doesn't work there. Not sure if there's any way to detect that. @Rich-Harris should we have another look at this "log url" problem?

**Comment by brittneypostma** [comment]
I removed the console logs and still nothing comes through and I get a 500 error. Nothing shows in the Edge Functions log either.

**Comment by dummdidumm** [comment]
If you pass something from the server-only load function to the client when client-side rendering is enabled, it needs to be serializable. You can't transport the context or event object over the network, it has functions etc in it. It works with `platform` destructured in dev because that object is only set through the adapter after building, not at dev (this is a limitation currently). Through `export const csr = false` in `+page.server.js` you can turn client-side rendering off.

What's the use case for passing the event or context object to the Svelte file?

**Comment by brittneypostma** [comment]
I was just trying to see what was in it, I didn't realize it couldn't be passed, but that does make sense. The end use case is to use the `{platform}` object on the site, but I can't see what's in it. I believe it should be `platform.context` to access the edge features from Netlify, but I can't get it that far.

**Comment by dummdidumm** [comment]
I think if you do `console.log(event.platform)` that should work (and hopefully shows up in your log), AFAIK SvelteKit doesn't touch things in there so there's no url hash error when logging it.

**Comment by brittneypostma** [comment]
You are correct, this logs out in the Edge Functions log.
```js
export const load: PageServerLoad = async (event) => {
	console.log(event.platform);
	return {
		event: ''
	};
```
this is the log
```
5:32:48 AM: [render] {
	  context: {
	    cookies: {
	      delete: [Function: bound delete],
	      get: [Function: bound get],
	      set: [Function: bound set]
	    },
	    geo: {
	      city: "Holland",
	      country: { code: "US", name: "United States" },
	      subdivision: { code: "MI", name: "Michigan" }
	    },
	    ip: "2600:6c4a:747f:a7c4:507c:6160:872d:7f77",
	    json: [Function: bound json],
	    log: [Function],
	    next: [Function: next],
	    requestId: "01GFTBSXMXDWNSGJF0QTH0CRHZ",
	    rewrite: [Function: bound rewrite],
	    site: {
	      id: "846ed0e0-067a-474a-b074-56ad712b2272",
	      name: "demo-sveltekit-edge",
	      url: "http://demo-sveltekit-edge.netlify.app"
	    },
	    account: { id: "5d260577f54c73a4f797c5e1" }
	  }
	}
```

The problem is as soon as I try to use any of that and return it from the server, I get a 500 error and the other error logs.

**Comment by brittneypostma** [comment]
Actually, I just got it to work with `event.platform.context.geo.city`. That returned Holland for me, which is correct. So there must be certain things in the object that you can't return from the server and see on the client. I wonder if a better error message here could be helpful for folks.

**Comment by dummdidumm** [comment]
Through #7303 that message should be more descriptive now

**Comment by brittneypostma** [comment]
Thanks, I also noticed that `adapter-auto` doesn't detect the edge network. I have to explicitly install `adapter-netlify` also to get this to work.

**Comment by dummdidumm** [comment]
Yeah, `edge` is `false` by default and `adapter-auto` doesn't accept any configuration, it's more of a "I want to get up and running as quickly as possible without worrying about any environment config and adapter stuff"-entry solution. The moment you know where you deploy to and want to configure that, you need to switch to the specific adapter.

**Comment by brittneypostma** [comment]
Thank you for the explanations and looking into this for me!
