### ISSUE TITLE
docs: Making TS/JS Switch more obvious

### ISSUE THREAD

**Issue by MentalGear** [sveltejs/kit#7299]
### Describe the problem

I just found out that there's a JS/TS switch on the bottom of the sidebar, after using the sveltekit docs for several months now (off and on). 

I'm sure there are many more who miss this as well, since it's hidden away at the bottom and has the same color as the rest of the linked items.

Could we make it a bit easier to spot?

### Describe the proposed solution

Maybe:
- placing it at the top of the sidebar ?
- make it a different background color, for example the brand svelte color ?
- placing it in the navbar itself ?

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
It was added only a few days ago, so you didn't overlook it previously. It's unobstrusive since this is probably something you set once and then forget about it. Having it in-your-face-style would get annoying quickly. Not sure how to best balance this.

**Comment by MentalGear** [comment]
Ah, I was thinking it might have been a recent additions. Maybe a subtle hint of color, like having the active label (or just the switch know) in brand color?

**Comment by benmccann** [comment]
I haven't heard of people missing this since it was added, so I think I'll go ahead and close this for now, but we'll continue to watch for feedback on the docs

**Comment by MentalGear** [comment]
Just wanted to add, in case this becomes relevant again: Why not have a switch in the upper corner within code snippets, like almost every other guide generator.

**Comment by benmccann** [comment]
That was my first thought as well, but there was a feeling that it might be too redundant to have it on every code block vs having it appear just once
