### ISSUE TITLE
New adapter for Cloudflare Pages & Workers

### ISSUE THREAD

**Issue by lgs** [sveltejs/kit#731]
**Cloudflare Pages is cheaper & better technology that its competitors**
Cloudflare Pages is a JAMstack platform for frontend developers to collaborate and deploy websites, this is going to be very competitive compared to Netlify and other players. It is growing quickly. 

**Describe the solution you'd like**
A new adapter able to deploy on Cloudflare Pages as a JAMstack (see: [https://pages.cloudflare.com/](https://pages.cloudflare.com/)) and expand SSR on Cloudflare Workers (see: [https://workers.cloudflare.com/](https://workers.cloudflare.com/))

**How important is this feature to you?**
Cloudflare Workers have not "cold start" like AWS Lambda and all the other FaaS, lower latency, and it is an order of magnitude cheaper that all its competitors. In one words, a better function as a service.

**Additional context**
Just google and see how the landscape is promizing.

**Comment by fergusonB** [comment]
Hafnelson has a pull request in right now if you want to take a look [#717](https://github.com/sveltejs/kit/pull/717)

**Comment by GrygrFlzr** [comment]
Released just now.

**Comment by lgs** [comment]
Really ?!? That's Amazing !!!

**Comment by gnimmelf** [comment]
So basically it *is* the static adapter (and I can stick w/ that one) apart from the semantic that it is designated for Cloudflare Pages? 

cheers!
