### ISSUE TITLE
I can't use auth + fingerprints

### ISSUE THREAD

**Issue by Ohyenno** [sveltejs/kit#7316]
### Describe the bug

It's very sad. I have done a lot of work to transfer the project to the latest version (before that, the project was running on version 449) and got a problem.

As I understand it, sessions were deleted in the project. Now, along with the fetch request, I can't send browser data if the request is executed on the ssr side. Without this, my token confirmation is not valid. An authorized user cannot work (The user can only use tools created after hydration)

Tell me how to solve the problem. How can I pass browser data in headers, as it was possible to do before?

It's very important!

### Reproduction

No data headers in SSR
All of headers after hydration

### System Info

```shell
Latest svelte kit version
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Please don't use bug reports for support requests.

It sounds like you want https://kit.svelte.dev/docs/hooks#server-hooks-handlefetch but if not, please ask in a GitHub discussion or in Discord.
