### ISSUE TITLE
Remove global `fetch` prerendering override

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#7317]
### Describe the problem

This code... https://github.com/sveltejs/kit/blob/779d57524e0734765c2399929c3b38397c3fdcf6/packages/kit/src/core/prerender/prerender.js#L105-L156 ...was added in https://github.com/sveltejs/kit/pull/5627 to make it possible for apps to fetch from themselves during prerendering.

Now that `fetch` is part of `RequestEvent` and can therefore be used in `+server.js` handlers and server-only `load` functions, I'm pretty sure we can get rid of it.

### Describe the proposed solution

Delete the code

### Alternatives considered

If we want to be really nice we could try and detect cases where people are doing `fetch(event.url.origin + '/...')` and tell them to use `event.fetch('/...')` instead

### Importance

nice to have

**Comment by Conduitry** [comment]
This _would_ be a breaking change, right? (The global `fetch` wouldn't mark dependencies like this one would.) I do think we should do this, so we should get it in before 1.0. I think we should put in a warning about using `event.fetch` instead, but I think it can probably be removed for 1.0.

**Comment by dummdidumm** [comment]
Playing devil's advocate here: What are the advantages of removing this from a user perspective? I can only think of "doesn't have to prepend the URL origin", so they trade one load argument for another. Are there others? Want to make sure we're not only doing that for our own good, but also the user's good.
