### ISSUE TITLE
SvelteKit won't start due to "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by zicho** [sveltejs/kit#732]
I am trying to start up a new SvelteKit project using the tutorial found on https://svelte.dev/blog/sveltekit-beta

After install, it gives the following message after running "npm run dev -- --open"

```
path\to\project\node_modules\@sveltejs\kit\svelte-kit.js:2
import './dist/cli.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

I have tried with different settings, such as turning TypeScript, ESLint and prettier off and on, but it doesnt seem to change anything, I still get the same issue.

**Comment by dummdidumm** [comment]
Which node version are you using? You need at least 12.

**Comment by zicho** [comment]
Confirmed working after node update

**Comment by kinxiel** [comment]
Had the same issue using node 12.14.1, updated to 15.12.0 and confirmed working.
