### ISSUE TITLE
Call `toJSON()` instead of `toString()` when serializing JS Date

### ISSUE THREAD

**Issue by CalebBassham** [sveltejs/kit#7323]
### Describe the problem

Currently, if I give back a date object from a `+page.server.js` I will get something formatted like this `Sun Oct 02 2022 03:55:20 GMT-0500 (Central Daylight Time)`. However Date has a `toJSON()` that will give me something like this `2022-10-02T08:55:20.563Z` which is much more useful since it is in the ISO standard.

This is a pretty common problem because a lot of database drivers will can give JS Date for date columns. So, as it is currently, I find myself doing this a lot:

```js
export const load: ServerLoad = async () => {
    const users = await sql`SELECT name, email, role, created_at FROM users`

    const mappedUsers = users.map(user => {
        user.createdAt = user.created_at.toJSON()
        delete user.created_at
        return user
    })

    return {
        users: mappedUsers
    }
}
```

Quite ugly. With this change it would be:

```js
export const load: ServerLoad = async () => {
    const users = await sql`SELECT name, email, role, created_at FROM users`

    return {
        users
    }
}
```

Side note, this was already a thing, as in I got the ISO string on the front-end, before the SK routing/form updates.

### Describe the proposed solution

Call `toJSON()` instead of `toString()` when serializing a JS Date object. Perhaps, even do it more generally if a `toJSON()` is available at all on an object and use `toString()` as secondary.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
The returned object is of type `Date`, we use `devalue` to (de)serialize it, so the object is preserved as `Date` when you access it in your Svelte component. This therefore works as designed.

**Comment by CalebBassham** [comment]
Interesting. I didn't realize SK was preserving Date.

**Comment by CalebBassham** [comment]
Is the same not true for actions? When I try to return a Date from an action I get `cannot be serialized as JSON without losing its original type (Date objects are serialized as strings)`.

If not, this is quite unintuitive. I know it is not the only place where there is some different behavior between `load()` and Actions, but since they are in the same file and work *almost* the same, most people are going to think of them working the same way. 

That is why I think it should be one or the other. Either always preserve Date (and others with devalue), or require that the object returned from these functions all be valid json or have a `toJSON()` method.

**Comment by CalebBassham** [comment]
Also, I haven't tested what the current behavior is, but client->server in the form of Actions should probably be in the conversation to.
