### ISSUE TITLE
Cannot host static build (built used `adapter-static`) on nginx docker container,  while `run preview` works as expected

### ISSUE THREAD

**Issue by d-adamkiewicz** [sveltejs/kit#7329]
### Describe the bug

This (see Reproduction) work as expected atfer `npm run build && pnpm run preview --host $MYIP --port 3000`, while when I copy `build` folder and then run `docker run --rm -it -d --name nginx -v /path/to/build:/usr/share/nginx/html -p 80:80 nginx` browser displays `500
Internal Error` and I got on Chrome console: `SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
...`

### Reproduction

```js
// svelte.config.js
import adapter from "@sveltejs/adapter-static";

export default {
        kit: {
                adapter: adapter({
                        fallback: "index.html",
                }),
                prerender: { entries: [] },
        },
};
```

```svelte
// +page.svelte
<script>
  import { enhance } from '$app/forms';
  export let form;
</script>

<form action="/" method="POST" use:enhance>
  <input type="number" name="number" />
  <button type="submit">Submit</button>
</form>

{#if form?.userId}
  {form.title}
{/if}
```
```svelte
//+page.server.js
export const actions = {
  default: async ({ request }) => {
    const form = await request.formData();
    const number = form.get('number');
    const response = await fetch(`https://jsonplaceholder.typicode.com/todos/${number}`);
    return await response.json();
  }
};
```

### Logs

```Shell
SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at He (start-2f33cc72.js:1:24423)
    at async Pe (start-2f33cc72.js:1:16831)
    at async je (start-2f33cc72.js:1:11701)
    at async ye (start-2f33cc72.js:1:19721)
handleError @ start-2f33cc72.js:1
```

### System Info

```Shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-6100T CPU @ 3.20GHz
    Memory: 5.49 GB / 6.11 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 18.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.10.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.45 => 1.0.0-next.45
    @sveltejs/kit: next => 1.0.0-next.520
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.1.8
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
This issue report could use a lot of work:
- can you reproduce this issue outside of docker?
- you did not provide a repository that reproduces the issue per the issue guideline
- please try to figure out what the rest of the response is. I'm guessing it will tell you what the issue is. E.g. open up `start-2f33cc72.js` and add a `console.log` statement right before `JSON.parse` and then run the app again or hit the app directly in your browser and look in the developer debug console

I'm inclined to close this issue if you don't do a bit more work showing what bug might be present because right now it's hard to tell that you didn't just make some mistake in the way you're deploying the app

**Comment by d-adamkiewicz** [comment]
Tried to debug ...
It seems no `__data.json` is generated in `build` folder but it crucial to have it (created empty "{}" `__data.json` file and in this case it resulted in another subsequent error) 
```js
// excerpt from _app/immutable/<entry-file-js>
// code above
async function He(r, e) {
	const t = new URL(r);
	t.pathname = r.pathname.replace(/\/$/, "") + Ut;
// t.ref:
// `http://localhost/__data.json`
	const o = await de(t.href, {
			headers: {
				"x-sveltekit-invalidated": e.map((l) => (l ? "1" : "")).join(","),
			},
		}),
		s = await o.text();
	if (!o.ok) throw new Error(JSON.parse(s));
	return Jt(s);
}
// code below
```

**Comment by d-adamkiewicz** [comment]
I simply copied content to `__data.json` file from `run preview`  server in Chrome/DevTools/Network 
`http://localhost/__data.json` Response ie
```json
[{"type":1,"nodes":2},"data",[3,5],{"type":4},"skip",{"type":1,"data":6,"uses":7},null,{"dependencies":-1,"params":-1,"parent":-1,"url":-1}]
```
now  page is displayed, but request to `https://jsonplaceholder.typicode.com/todo/${number}` URL is not fullfiled,
the more - string `jsonplaceholder.typicode.com` is not present in any file of `build` folder. So it seems present `npm run build` doesn't produce viable static build.

**Comment by d-adamkiewicz** [comment]
According to https://github.com/sveltejs/kit/issues/7200 "SvelteKit SSR mode supports defining actions in +page.server.js that can be accessed via form action attribute but not in SPA mode." So I can't use `+page.sever.js` in static build (all because I was "deceived" by `run preview` server.)
