### ISSUE TITLE
Route priority surprise

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#7344]
### Describe the bug

Given the routes:
```
/blog
├── [...slug]
│   └── +page.svelte // article
└── [taxonomy=type]
    └── [[page=integer]]
        └── +page.svelte // listing
```

where the type matcher = (category|series|tag), and integer = \d+

The request `/category/2` goes to the listing page, but `/category`, _without_ the optional page, matches the `[...slug]` route and goes to article.

That was a surprise ... 'cause adding a page directly under `[taxonomy=type]` conflicts with the optional `[[page=integer]]` route, but removing that optional param then makes `/category` match the listing route as expected.

This seems unexpected and inconsistent.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-4sff7t?file=src/routes/[taxonomy=type]/[[page=int]]/+page.svelte

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 87.88 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/Library/pnpm/node
    npm: 8.19.2 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 106.0.5249.119
    Chrome Canary: 109.0.5372.0
    Firefox: 106.0
    Safari: 16.0
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.99 
    @sveltejs/kit: next => 1.0.0-next.522 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.1.8 => 3.1.8
```

### Severity

serious, but I can work around it

### Additional Information

Maybe related to recent changes https://github.com/sveltejs/kit/pull/7304 ?

**Comment by dummdidumm** [comment]
Ok this is interesting. It happens because the `int` matcher is invoked with `undefined` and the matcher says "nope, not correct". Question is - should the matcher be invoked with `undefined` in case of a missing segment or not? I think it's expected that it isn't invoked, so we should change this.

**Comment by CaptainCodeman** [comment]
It's giving me an empty string in my app, which is mostly identical to that example ... that gives me an easy-way to make it work (but probably only because the last param is the optional one).

I would expect it _not_ to be called with undefined, only if there was a value it was considering as a candidate to work out the route match. If the candidate value was undefined, it should take the optionality to mean it matched.
