### ISSUE TITLE
Minor improvement: allow passing an array of urls (strings, `URL`s or functions) to `invalidate`

### ISSUE THREAD

**Issue by cdcarson** [sveltejs/kit#7349]
### Describe the problem

I'm finding myself doing this often in my `enhance` "result" functions:

```ts
await Promise.all([
  invalidate('page:plans'),
  invalidate('layout:plans'),
  invalidate('layout:dashboard')
]);
```

This is fine, as long as I remember to wrap the `invalidate` calls in `Promise.all` rather than `await`ing each one, thus allowing the `__data.json` requests to run concurrently. 

I'm pretty sure there wouldn't be a huge performance hit in most cases, but still it's a point of uncertainty. I'd much rather be able to do this:

```ts
await invalidate([
  'page:plans',
  'layout:plans',
  'layout:dashboard'
]);
```

### Describe the proposed solution

Currently:
```ts
export function invalidate(url: string | URL | ((url: URL) => boolean)): Promise<void>;
```

Improved:
```ts
// InvalidateArg for clarity...
type InvalidateArg = string | URL | ((url: URL) => boolean);
export function invalidate(url: InvalidateArg | InvalidateArg[]): Promise<void>;
```

I'm pretty sure this is doable here:

https://github.com/sveltejs/kit/blob/87b3037bb6fcf574d5d50c91f42cc91d3b97286c/packages/kit/src/runtime/client/client.js#L1145-L1161

### Alternatives considered

1. Write a wrapper:

```ts
type InvalidateArg = string | URL | ((url: URL) => boolean);
export const wrapInvalidate = async (arg: InvalidateArg | InvalidateArg[]): Promise<void> => {
  const args: InvalidateArg[] = Array.isArray(arg) ? arg : [arg];
  await Promise.all(args.map((a) => invalidate(a)));
};
```

2. Express the cache dependencies somehow in the page load function, therefore, on the client, only having to invalidate the page data rather than the page plus whatever layout data may have been affected. I have no idea whether this is possible, and it seems like it could be a mess/inefficient:

  - only `invalidate('page:plans')` on the client
  - `load` in `+page.server.ts` somehow knows to load & merge the parent layout data?

### Importance

would make my life easier

**Comment by mustofa-id** [comment]
I like this, but prefer rest parameters: `invalidate(...args: InvalidateArg[])` just like `depends(...deps: string[])`

**Comment by Rich-Harris** [comment]
We decided against implementing `invalidate(...resources)` in #7703 because we might want to add an options object in future. `invalidate([...resources])` avoids that problem, but it's a less nice API for the common case where you're invalidating a single resource. We might revisit this issue in future if we're confident that we won't end up needing an options object.

In the meantime, note that multiple `invalidate(...)` calls will return the _same_ promise if they happen in the same tick:

```js
const p1 = invalidate(url1);
const p2 = invalidate(url2);

console.log(p1 === p2); // true
```

For that reason, you can always do this sort of thing, though it's not as nice as putting all the resources in a single call:

```js
invalidate('page:plans');
invalidate('layout:plans');
await invalidate('layout:dashboard');
```

**Comment by cdcarson** [comment]
Ok, good to know. Thanks.
