### ISSUE TITLE
Initial setup adds Sass 1.0.0 whereas there are newer versions

### ISSUE THREAD

**Issue by Wolfr** [sveltejs/kit#739]
**Describe the bug/To Reproduce**
If you choose Sass (SCSS) in the initial setup wizard, `sass: "^1.0.0" is added to devDependencies.

**Expected behavior**
A more recent version of `sass` is added (1.32.8 is the latest on npm)

**Comment by benmccann** [comment]
The `^` means get the latest 1.x.x version so you should still get the latest in your `package-lock.json` and this way we don't have to update the template everytime there's a new release

**Comment by Wolfr** [comment]
Sorry, my bad!
