### ISSUE TITLE
Static files with spaces or underscores in the file name don't work with adapter-node

### ISSUE THREAD

**Issue by PaulHobbs** [sveltejs/kit#740]
**Describe the bug**
Static files with a space or underscores don't get served by adapter-node.

**Logs**
No logs available, just a 404 from the node server.

**To Reproduce**
Add a static file with a space in it, like so: https://github.com/PaulHobbs/kit/commit/28ce49c41069d71ca34eb91e3b289e5008e22874

The file will be served correctly from the dev server, but return a 404 from the built node server (when run with `npm run build && cd build && node .`).

**Expected behavior**
Static with spaces should be served by the built node server correctly.

**Stacktraces**
N/A

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
```
  System:
    OS: macOS 11.0.1
    CPU: (8) arm64 Apple processor
    Memory: 117.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - /opt/homebrew/bin/node
    npm: 7.3.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.1
```

- Your browser
Tested with Chrome and curl.

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Node

**Severity**
Blocking an upgrade from Sapper to SvelteKit. I have a site with extensive use of static files with spaces, and the file names are used semantically (to determine the titles of the images), so removing the spaces is not an option.

**Additional context**

**Comment by samccone** [comment]
Reducing the problem a bit I can confirm that sivr is not correctly handling the decoding of URL paths
https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L163

Example request:
http://localhost:3000/a%20space.png

If I change the above line to 

```
		let pathname = decodeURI(req.path || parser(req, true).pathname);
```

Things begin to work.

plussing in @lukeed for visibility. That said I am 99% sure this is a issue upstream that we should patch
https://github.com/lukeed/sirv

**Comment by samccone** [comment]
Interestingly I added a new test case upstream for sirv and can confirm it is handling this case correctly
https://github.com/lukeed/sirv/pull/102

**Comment by samccone** [comment]
The reason why sivr is working is that req.path is unset, and thus it falls into the parser code which handles the decoding of the URL.

```
let pathname = req.path || parser(req, true).pathname;
```

```
// req.path
`undefined` 

// parser(req, true).pathname
/with space.txt
```

**Comment by lukeed** [comment]
Kit fails because `req.path` is set, coming from Polka (stable) which doesn't decode upfront. Either add an inline middleware to manually decode before the `assets` middleware is run, or override `app.parse`, or use polka@next which decodes by default.

**Comment by samccone** [comment]
Thanks @lukeed looks like I was on the right path :) 
https://github.com/sveltejs/kit/pull/743

**Comment by lukeed** [comment]
Indeed!
