### ISSUE TITLE
separate layout for +error.svelte

### ISSUE THREAD

**Issue by Cluster2a** [sveltejs/kit#7402]
### Describe the problem

Hey, 

my svelte app uses a layout `<Header /><Slot><Footer />`.

If the App renders an error (+error.svelte), I would like to use a separate Layout for the error page without the Header / Footer from the +layout.svelte.

### Describe the proposed solution

We should be able to define a separate layout for the error page.

### Alternatives considered

Currently, I am checking in my current +layout.svelte for $page?.error.
If an error is found, I render the layout without the header and footer.

### Importance

nice to have

**Comment by Conduitry** [comment]
Having a single root layout is a conscious decision, as it makes a lot of things easier to reason about and eliminates whole classes of potential bugs. What you're doing now is a fine way of handling this.
