### ISSUE TITLE
C++ addon support for adapter-node

### ISSUE THREAD

**Issue by MilesWellsSVT** [sveltejs/kit#7413]
### Describe the problem

I need to be able to bundle `.node` files ([C++ Addons](https://nodejs.org/api/addons.html)). 

I'm fine if this is immediately closed because of #3733, but because adapter-node no longer uses esbuild I'm not sure if [my comment](https://github.com/sveltejs/kit/issues/3733#issuecomment-1291248198) on that issue is relevant.

### Describe the proposed solution

My knowledge in rollup and esbuild are quite lacking, but here is an [esbuild plugin](https://nodejs.org/api/addons.html) that would theoretically solve the problem. Since adapter-node switched to rollup from esbuild this isn't exactly a solution, but I've included it for reference since I don't know what else to do.

### Alternatives considered

I've gotten the C++ addon I'm using to work by putting it in `dependencies` so it gets skipped for bundling. Then you can simply run `node build` to run and it works just fine on my local machine. So theoretically, for deployment, one could produce the build (with C++ addons in `dependencies` so they aren't bundled) and then install the non-bundled `dependencies` wherever the build gets deployed.

### Importance

would make my life easier

### Additional Information

Specifically I'm using [Azure's MSAL Node extensions](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/dev/extensions/msal-node-extensions) for account caching.

The `node-resolve` [rollup plugin docs state the default for the extensions configuration](https://github.com/rollup/plugins/tree/master/packages/node-resolve#extensions) includes `.node` files. I don't know why `.node` files don't work out of the box since [adapter-node uses this plugin](https://github.com/sveltejs/kit/blob/master/packages/adapter-node/rollup.config.js).

[Here is a reproduction repo](https://github.com/MilesWellsSVT/adapter-node-reproduction). All I did was install `adapter-node` and `@azure/msal-node-extensions` as well as using it in `src/routes/+page.server.js`.

![image](https://user-images.githubusercontent.com/80766315/198392682-5c6e3460-71f6-439b-92f2-c4097aed1d78.png)

For the "Alternatives considered" here's what I did:

- `pnpm run build` and copy the `build` directory out somewhere else on my local machine
- In the directory `build` was copied to, also copy `package.json` (I deleted all the `devDependencies` but I doubt that's necessary)
- `pnpm i` in the same directory to install `dependencies`
- `node build` to run the application

Here's some example output:

![image](https://user-images.githubusercontent.com/80766315/198395089-e9d14337-fc82-4af9-82b1-62f7e5faafda.png)

The `false` coming through the console when I navigate to `localhost:3000` is from [this line](https://github.com/MilesWellsSVT/adapter-node-reproduction/blob/main/src/routes/%2Bpage.server.js#L3) and it is `false`, as expected, since I ran this on a mac.

**Comment by Rich-Harris** [comment]
The packages in question _should_ go in `dependencies` — these will be ignored by esbuild. I'm not sure there's anything we need to do beyond that? Packages in `dependencies` (as opposed to `devDependencies`) are supposed to be installed wherever you run the deployment

**Comment by MilesWellsSVT** [comment]
I believe my error was in thinking C++ addons were somehow portable in a way they could be bundled in any node application to be deployed anywhere so I was searching for a way to make bundling work with them. But that's not the case since the addons are compiled for specific architecture which happens on installation with tools such as node-gyp. Due to my ignorance this is a best guess, anyway.

So to conclude - my "alternative" is the correct way of handling C++ addons and I just figured it out through roundabout trial and error 😆

Thanks for your time!
