### ISSUE TITLE
applyAction does not update form variable when form action is pointed at a different page

### ISSUE THREAD

**Issue by N00nDay** [sveltejs/kit#7420]
### Describe the bug

I have a `<form />` on a layout that has action `action="/registration"`. When using `enhance` I am trying to update `export let form: ActionData;` using `await applyAction(result);` but the form variable is not updated.

### Reproduction

Reproduction can be found [here](https://github.com/N00nDay/kit-reproduction). The README provides instructions along with my current work around.

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 577.82 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 106.0.5249.119
    Edge: 107.0.1418.24
    Firefox: 100.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.84 
    @sveltejs/kit: next => 1.0.0-next.525 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.0
```

### Severity

serious, but I can work around it

**Comment by mustofa-id** [comment]
You can use `$page.form` in layout. According to the [documentation](https://kit.svelte.dev/docs/form-actions#progressive-enhancement-applyaction:~:text=updates%20form%20and%20%24page.form%20to%20result.data%20(regardless%20of%20where%20you%20are%20submitting%20from ), it will update both the `form` and `$page.form`, but there's no mention that layout has `form` prop.

**Comment by N00nDay** [comment]
> You can use `$page.form` in layout. According to the [documentation](https://kit.svelte.dev/docs/form-actions#progressive-enhancement-applyaction:~:text=updates%20form%20and%20%24page.form%20to%20result.data%20(regardless%20of%20where%20you%20are%20submitting%20from), it will update both the `form` and `$page.form`, but there's no mention that layout has `form` prop.

This did the trick! I did the following and it works perfectly:

1. Removed the import for `ActionData` type from `.svelte-kit/types/src/routes/registration/$types`
2. Removed `export let form: ActionData;`
3. Added `$: form = $page.form;`
4. Removed `form = result.data;` as `applyAction` is now working!
