### ISSUE TITLE
`prefetch` module shouldn't return a void promise

### ISSUE THREAD

**Issue by Mr-M1M3** [sveltejs/kit#7428]
## Describe the problem

Let's say,I have a blog page which has a `next blog` button. Clicking  the button should take user to the next blog. But I want to show the title of the next blog as a tooltip.

In that case, if I prefetch the next blog page and also fetch it's title separately that means, I have to request the same resource (kind of ) twice. It would be nice, If i could access the return value of the next blog page's load function via prefetching that resource programaticallly.

## Describe the proposed solution

`prefetch` module should return a promise that contains the return value of the next blog page's load function.

#### Next page's load function
```javascript
// blog-02/+page.js
...
return {
...
title: "Why sveltekit is awesome"
}
```

#### Current page's +page.svelte
```javascript
// blog-01/+page.svelte
...
import {prefetch} from "$app/navigation";

async function prefetch_next_page(){
const next_page_data = await prefetch("/blog-02"); // this should return the returned value of the load function of blog-02/+page.js
const next_page_title = next_page_data.title; // now we can access the title of next blog
}
...
```

## Importance

would make my life easier

**Comment by Rich-Harris** [comment]
If you need to know the title of the next page, then return the title of the next page from your `load` function. Getting it via `prefetch` is a very elaborate workaround that adds all sorts of complexity but adds limited value (for example, loading the data lazily might be good enough for a tooltip, but what if you want to include it in a 'next' link instead?)

SvelteKit's docs have next/previous links at the bottom of each page. The list of pages is available from the layout...

https://github.com/sveltejs/kit/blob/4022c74680ce4f3cbbd3fa367000696bcc6764e4/sites/kit.svelte.dev/src/routes/docs/%2Blayout.server.js#L35-L37

...so we can easily retrieve the next/previous pages:

https://github.com/sveltejs/kit/blob/4022c74680ce4f3cbbd3fa367000696bcc6764e4/sites/kit.svelte.dev/src/routes/docs/%5Bslug%5D/%2Bpage.svelte#L13-L16
