### ISSUE TITLE
`Not found: /__data.json` when use form actions with `use:enhance`

### ISSUE THREAD

**Issue by dangelomedinag** [sveltejs/kit#7434]
### Describe the bug

I have this code:
```svelte
<!-- routes/+page.svelte -->

<script>
	import { enhance } from '$app/forms';
</script>

<form method="POST" use:enhance>
	<input type="text" name="text" id="textid" />
	<button type="submit">submit</button>
</form>
```

```js
// routes/+page.server.js

export const actions = {
	default: () => {
		return {
			success: true
		};
	}
};
```

when I submit the form, the following error occurs:

```bash
Not found: /__data.json
Error: Not found: /__data.json
    at resolve (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:264:13)
    at resolve (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:5)
    at Object.handle (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:343:66)
    at respond (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:292:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:413:22
```

exactly the same happens if they are named actions, when using `use:enhance` I get the same error.
I thought it was related to [#7410](https://github.com/sveltejs/kit/issues/7410), but I updated to the latest version and the error described still occurs

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-kbaf32?file=src/routes/+page.svelte 

other option (local)
```bash
npm create svelte@latest 
// zero configuration
add files /+page.svelte and /+page.server.js
```

### Logs

```Shell
Not found: /__data.json
Error: Not found: /__data.json
    at resolve (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:264:13)
    at resolve (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:295:5)
    at Object.handle (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:343:66)
    at respond (file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/runtime/server/index.js:292:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///C:/Users/dange/Documents/dev/sveltekit/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:413:22
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 8.55 GB / 15.41 GB
  Binaries:
    Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.755.0), Chromium (107.0.1418.24), ChromiumDev ((@(&"C:/Users/dange/AppData/Local/Programs/oh-my-posh/bin/oh-my-posh.exe" init pwsh --config="C:\Users\dange\AppData\Local\Programs\oh-my-posh\themes\jandedobbeleer.omp.json" --print) -join "`n") | Invoke-Expression)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.85
    @sveltejs/kit: next => 1.0.0-next.528
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.2.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I can do a minimal reproduction, but I literally just start a new project and try to use form actions with `use:enhance`

**Comment by boian-ivanov** [comment]
I've just about wanted to report this issue. I've been getting it on the root route `+page.server.ts` file, but I've been able to also replicate it with the default create-svelte app. Stackblitz link [here](https://stackblitz.com/edit/sveltejs-kit-template-default-tctov7?file=src/routes/+page.server.js).
In my experience if you have a `+page.server.js` in the root of the routes, the `/__data.json` won't exist so it can't fetch any of the data that you are trying to pass at prerender. On full page load it works, but on prerender it doesn't. Seems like quite the braking issue

**Comment by JouanDeag** [comment]
Can confirm, getting this error as well.

**Comment by KarolusD** [comment]
Same here, reverting back to: "@sveltejs/kit": "1.0.0-next.527" helps.

**Comment by NormandoHall** [comment]
Same here

**Comment by chrskerr** [comment]
This appears to also impact `invalidateAll()`. We are receiving 404 errors on `/__data.json` after running it, causing a full page refresh.

**Comment by AIS-Brandon** [comment]
Have the same issue, but was caused by having `export const ssr = false` in root `+layout.server.ts` file. 

I could fix the problem by commenting out that line, or reverting to 527 as above.

**Comment by pheuter** [comment]
I'm seeing an issue now where the first request to `__data.json` fails and I have to click the link twice and the second request succeeds:

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/92698/199021500-6a7b20bb-226b-4e07-a4f4-023b3e055de2.png">

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/92698/199021537-baa9f868-5520-4640-924a-5219e9487316.png">

/cc @dummdidumm

**Comment by dummdidumm** [comment]
Please open a new issue with a reproduction

**Comment by beeb** [comment]
> Please open a new issue with a reproduction

There is a repro linked in the second post https://github.com/sveltejs/kit/issues/7434#issuecomment-1295879722
