### ISSUE TITLE
Make "version" available from $app/environment

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#7436]
### Describe the problem

Caching is great, it makes things fast. But using a cached page after an app deploy means all the script references are wrong and "bad things". So some form of "app version" needs to be part of any cache key.

There is a generated version string, used for the update checks. That could be read from `build/client/_app/version.json`except ... it won't be there during the build if pre-rendering.

So you have to check if running in `dev` or `prerendering` mode before reading the file.

### Describe the proposed solution

I would like to be able to access the version string from `$app/environment`

### Alternatives considered

Maybe it's already exposed from '$service-worker'?

But I don't know if that only works if using a service-worker, and it feels odd importing it from there when it isn't _really_ anything todo with a service-worker.

### Importance

nice to have

**Comment by iolyd** [comment]
Somewhat related to #7144 (see comments).

In the meantime, I also needed some form of app versioning for quick and easy client-side version checks (to automatically clear some outdated localStorage objects, both for dev and prod, and without additional requests), and while kit's `appVersion` isn't exposed as proposed, we can resort to defining a basic version key using a vite global var:

```ts
// vite.config.ts
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
  plugins: [sveltekit()],
  define: {
    __VITE_DEV_APP_VERSION__: JSON.stringify(Date.now().toString()),
  },
};

export default config;
```

```ts
// lib/utils/version.ts
import { dev } from '$app/environment';

export const version = dev ? __VITE_DEV_APP_VERSION__ : __SVELTEKIT_APP_VERSION__;
```
