### ISSUE TITLE
add export const reloadonout = true;

### ISSUE THREAD

**Issue by Ohyenno** [sveltejs/kit#7439]
### Describe the problem

Hello. 
I need a solution for this case:

I have an admin page where the user works with the content editor.
I don't use prefetch on this page, also I use `data-sveltekit-reload` with a link in this route.
This is good.

When working with content, the user could click on the menu (this is a layout) and its links do not have `data-sveltekit-reload`. After exiting, I need to kill all scripts, but without a reboot, this is not possible. Also, i can't catch `window.onbeforeunload`

### Describe the proposed solution

I think it will be a good solution to add a parameter like
`export const reloadonout = true;`

if the user follows this route, then a reload parameter will be added to all links.

### Importance

nice to have

**Comment by dummdidumm** [comment]
Not fully understanding the problem yet, more precisely I don't understand when exactly you want to reload.
That said, this sounds like something you can solve in user land. You know at what point you want to reload, so you could 
- create a global click handler which reacts to clicks on `a` tags
- or use `beforeNavigate` to intercept all starting navigations, turning them into a full page reload under certain conditions using browser APIs like `location`

**Comment by Ohyenno** [comment]
Thanks, I solved with `beforeNavigate`

But caught strange behavior with onbeforeunload
When I clicked "Cancel" on the prompt window, the user didn't stay on the page (followed the link).

I cannot prevent the action.

**Comment by mustofa-id** [comment]
I think setting the data-sveltekit-reload attribute to the [container](https://kit.svelte.dev/docs/link-options#disabling-options:~:text=%3Cdiv%20data%2Dsveltekit%2Dreload) will help.

**Comment by dummdidumm** [comment]
> But caught strange behavior with onbeforeunload When I clicked "Cancel" on the prompt window, the user didn't stay on the page (followed the link without reload).

Doing this 
```js
window.addEventListener('beforeunload', (event) => {
			event.preventDefault();
			event.returnValue = '';
		});
```
(note the returnValue thing, necessary for many browsers)

works for me.
Closing as this can be solved in userland.
