### ISSUE TITLE
Adapter static talks about brotli compression, but no brotli files are generated

### ISSUE THREAD

**Issue by happysalada** [sveltejs/kit#744]
First of all, a great thanks for making sveltekit!

**Describe the bug**
Upon generating assets with the static adapter, the console talks about brotli.
```
vite v2.1.3 building for production...
✓ 36 modules transformed.
.svelte/output/client/_app/manifest.json                                        2.27kb
.svelte/output/client/_app/pages/blog/$layout.svelte-bc46c501.js                0.88kb / brotli: 0.48kb
.svelte/output/client/_app/pages/index.svelte-9c14b94a.js                       2.77kb / brotli: 1.01kb
.svelte/output/client/_app/pages/about.svelte-0054d702.js                       6.17kb / brotli: 2.04kb
.svelte/output/client/_app/pages/blog/about_this_site.svx-9894ea34.js           4.04kb / brotli: 1.53kb
.svelte/output/client/_app/pages/blog/index.svelte-1d0d2ad6.js                  3.80kb / brotli: 1.49kb
.svelte/output/client/_app/chunks/Tag-3f8ec96c.js                               0.85kb / brotli: 0.47kb
.svelte/output/client/_app/chunks/index-e2fe1118.js                             5.14kb / brotli: 1.98kb
.svelte/output/client/_app/assets/start-e9853c00.css                            5.76kb / brotli: 1.46kb
.svelte/output/client/_app/assets/pages/index.svelte-ece06296.css               3.89kb / brotli: 1.17kb
.svelte/output/client/_app/assets/pages/blog/$layout.svelte-7ee25cc0.css        0.39kb / brotli: 0.19kb
.svelte/output/client/_app/assets/Tag-84bd08b3.css                              0.75kb / brotli: 0.26kb
.svelte/output/client/_app/assets/pages/blog/about_this_site.svx-f7025d3f.css   0.87kb / brotli: 0.38kb
.svelte/output/client/_app/assets/pages/blog/index.svelte-cdb6cb2c.css          0.94kb / brotli: 0.37kb
.svelte/output/client/_app/assets/pages/about.svelte-f9a365f3.css               1.79kb / brotli: 0.60kb
.svelte/output/client/_app/start-5fbc547e.js                                    25.28kb / brotli: 7.69kb
vite v2.1.3 building SSR bundle for production...
✓ 36 modules transformed.
.svelte/output/server/app.js      150.74kb
.svelte/output/server/style.css   13.23kb
```

I checked in both the build directory and the .svelte output directory and can't find any .br files. 
Could it be that it's just an indication of possible compression and not actually doing the compression? 

**To Reproduce**
`svelte-kit build` with a static adapter

To help us help you, if you've found a bug please consider the following:

- If possible, we recommend creating a small repo that illustrates the problem.
- Reproductions should be small, self-contained, correct examples – http://sscce.org.

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that Svelte is run by unpaid volunteers in their free time, and issues that follow these instructions will get fixed faster.

**Expected behavior**
generated .br files next to the corresponding css and js files.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

Stack trace goes here...

</details>

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`

- Your browser
firefox 87

- Your adapter 
Static

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

compression can be enabled by other ways, but if would be nice to have it done with svelte-kit. So not critical in my opinion.

**Comment by Rich-Harris** [comment]
That's just Vite telling you what the file _will_ compress to, so that you have a sense of what assets will cost in over-the-wire terms (as well as in parse-and-evaluate terms). The actual compression is usually handled by your fileserver/CDN, and isn't something you need to think about.

**Comment by happysalada** [comment]
Thanks!
