### ISSUE TITLE
Static adapter issues with Verbal

### ISSUE THREAD

**Issue by Mark2M** [sveltejs/kit#7440]
### Describe the bug

Just a heads up...

I migrated some old php to svelte/sveltekit and opted to prerender everything as none of the routes are dynamic etc.

I set my svelte config to use 'adapter-static' and set the prerender flag in the root layout. When I tried deploying to Vercel it kept failing, one error being no 'public' output folder found, another 'command not found'.

Switching the svelte config back to 'adapter-auto' resolved the issue.

Cheers

### Reproduction

NA (see above)

### System Info

```Shell
NA
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
For deployment to Vercel you need to use adapter-vercel, as that sets up the necessary steps to deploy on that platform. This is why adapter-auto works because that detects Vercel and uses its adapter

**Comment by Mark2M** [comment]
Thanks dummdidumm...
