### ISSUE TITLE
Web Workers Support?

### ISSUE THREAD

**Issue by JAD3N** [sveltejs/kit#746]
**Is your feature request related to a problem? Please describe.**
I'm trying to use web workers, but I can't seem to find a nice way to integrate into the build chain similar to the hardcoded service worker.

**Describe the solution you'd like**
I ideally would like to be able to have multiple web workers build (using TypeScript) from a directory (e.g. src/workers/example.ts) or some other configurable method that can be used inside an onMount call client-side.

**Describe alternatives you've considered**
I have considered modifying my project to have additional scripts to build the web workers, but I was hoping there might be a nice way to get this done without having to do that, maybe some method that could be derived from modifying the svelte config file.

**Comment by lukasIO** [comment]
using vite you can specify to import an asset as a worker, maybe this helps:
https://vitejs.dev/guide/assets.html#importing-script-as-a-worker

**Comment by JAD3N** [comment]
@lukasIO That's perfect, I've tested it using TypeScript as well and everything appears to be working as expected.
