### ISSUE TITLE
Breaking change occurred between "@sveltejs/adapter-auto" .84 and .85 - Missing references

### ISSUE THREAD

**Issue by ZaxyxaZ** [sveltejs/kit#7464]
### Describe the bug

Error during build occurs: node_modules/ajv-dist/dist/ajv7.min.js" points to missing source files
When you fall back to .84 the problem is resolved.
Looks as if there is invalid JSON parse package error in module ajv.

### Reproduction
"devDependencies": {
		"@sveltejs/adapter-auto": "1.0.0-next.84",
		"@sveltejs/kit": "1.0.0-next.526",
		"@tailwindcss/typography": "0.5.7",
		"autoprefixer": "10.4.13",
		"daisyui": "2.36.0",
		"date-picker-svelte": "2.2.1",
		"eslint": "8.24.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.18",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.8.0",
		"svelte": "3.50.1",
		"svelte-preprocess": "4.10.7",
		"tailwindcss": "3.2.1",
		"vite": "3.2.2"
	}

Causes Error Message: Sourcemap for "E:/dev/src/sveltekit/common-utility-app/node_modules/ajv-dist/dist/ajv7.min.js" points to missing source files. As a result - the application never starts. 

"devDependencies": {
		"@sveltejs/adapter-auto": "1.0.0-next.84",
		"@sveltejs/kit": "1.0.0-next.525",
		"@tailwindcss/typography": "0.5.7",
		"autoprefixer": "10.4.13",
		"daisyui": "2.36.0",
		"date-picker-svelte": "2.2.1",
		"eslint": "8.24.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.18",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.8.0",
		"svelte": "3.50.1",
		"svelte-preprocess": "4.10.7",
		"tailwindcss": "3.2.1",
		"vite": "3.2.2"
	},

Runs nominally without any reported errors. 

### Logs

```Shell
Sourcemap for "E:/dev/src/sveltekit/common-utility-app/node_modules/ajv-dist/dist/ajv7.min.js" points to missing source files
```

### System Info

```Shell
These dependencies cause the invalid reference. If you change the adapter to .84 the issue is resolved. 

"devDependencies": {
		"@sveltejs/adapter-auto": "1.0.0-next.85",
		"@sveltejs/kit": "1.0.0-next.524",
		"@tailwindcss/typography": "0.5.7",
		"autoprefixer": "10.4.13",
		"daisyui": "2.36.0",
		"date-picker-svelte": "2.2.1",
		"eslint": "8.24.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.18",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.8.0",
		"svelte": "3.50.1",
		"svelte-preprocess": "4.10.7",
		"tailwindcss": "3.2.1",
		"vite": "3.2.2"
```

### Severity

serious, but I can work around it

### Additional Information

none

**Comment by Conduitry** [comment]
Please provide a minimal reproduction of the bug, not a link to our changelog.

**Comment by Rich-Harris** [comment]
Again, you need to provide a reproduction, otherwise we have no choice but to close this issue.

**Comment by ZaxyxaZ** [comment]
> Again, you need to provide a reproduction, otherwise we have no choice but to close this issue.

Under normal circumstances I would provide the code. But in this case it's pure dependencies. If the application does not execute when invoked what will satisfy this requirement? I provided the difference between the package.json files.

**Comment by ZaxyxaZ** [comment]
@Rich-Harris Have been working with https://github.com/josdejong (Svelte JSON-Editor) and we have found others who have confirmed this issue.

We nailed down the issue to some sort of Vite compilation / dependency issue. The problem can be resolved after toggling SSR. First, you have to wait for the failure. Then go into the source (+layout.js) and reset to the opposite value (in our case true) and then when the application error resolves then restart the server and it works. Here is terminal output from Vite.

[vite] ✨ new dependencies optimized: immutable-json-patch, lodash-es, @fortawesome/free-regular-svg-icons, ajv-dist, jmespath, ...and 16 more
2:44:54 PM [vite] ✨ optimized dependencies changed. reloading

Clearly this "optimization" needs to occur by Vite prior evidently it's not seeing the dependencies on initial compilation. 

See https://github.com/josdejong/svelte-jsoneditor/issues/185

**Comment by ZaxyxaZ** [comment]
@dummdidumm You are correct it's a dev mode issue - production build works fine.  For some reason, Vite is not resolving dependencies currently in dev mode.
