### ISSUE TITLE
Cannot set property duplex of #<Request> which has only a getter

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#7468]
### Describe the bug

As of SvelteKit 1.0.0-next.406, I started getting this issue in server endpoints that used ky for making web reqeusts:
```
Cannot set property duplex of #<Request> which has only a getter
```

The issue stems from it setting `request.duplex` like this:
```ts
    const request = new Request('https://example.com')
    if (supportsRequestStreams) {
        // @ts-expect-error - Types are outdated.
        request.duplex = 'half';
    }
```

In SvelteKit 1.0.0-next.406, `supportsRequestStreams` started evaluating to true. It's defined as this:
```ts
const supportsRequestStreams = (() => {
    let duplexAccessed = false;
    let hasContentType = false;
    const supportsReadableStream = typeof globalThis.ReadableStream === 'function';
    if (supportsReadableStream) {
        hasContentType = new globalThis.Request('https://a.com', {
            body: new globalThis.ReadableStream(),
            method: 'POST',
            // @ts-expect-error - Types are outdated.
            get duplex() {
                duplexAccessed = true;
                return 'half';
            },
        }).headers.has('Content-Type');
    }
    return duplexAccessed && !hasContentType;
})();
```

For context, setting `request.duplex` seems to be needed for compatibility with Chrome 105: https://github.com/sindresorhus/ky/commit/316fffe5ad9a1a1329816b6d82d02e7da05b6f35

I'm not sure entirely sure if this is an incorrect implementation in SvelteKit, or if the issue is with ky.

Ky issue: https://github.com/sindresorhus/ky/issues/467

### Reproduction

https://github.com/probablykasper/sveltekit-fetch-duplex-bug

### System Info

```Shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 820.51 MB / 32.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.0 - ~/Library/Caches/fnm_multishells/70304_1667344002694/bin/node
    Yarn: 1.22.15 - ~/Library/Caches/fnm_multishells/70304_1667344002694/bin/yarn
    npm: 8.12.1 - ~/Library/Caches/fnm_multishells/70304_1667344002694/bin/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 107.0.5304.87
    Firefox: 106.0.1
    Firefox Developer Edition: 107.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/kit: 1.0.0-next.531 => 1.0.0-next.531 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.2.2 => 3.2.2
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
This is probably a result of #7412 where we had to add the `duplex` property to prevent `undici` from erroring. From looking at the referenced Ky-code I don't see how this could have an impact on this though.

**Comment by repsac-by** [comment]
This behavior of `undici@5.12.0` is fully consistent with the [specification](https://fetch.spec.whatwg.org/#request-class).

>  **readonly** attribute RequestDuplex duplex;

Note that the `duplex` attribute is marked readonly.
This attribute can only be set by passing `RequestInit`.

**Comment by dummdidumm** [comment]
Then this is on Ky's end, because in the code you linked they modify that property _after_ initialising the request.

**Comment by vhscom** [comment]
I'm seeing OP described behavior in SvelteKit and I'm not using Ky. Kit 529 + Node Adapter 100. Occurs on POST requests only.

**Comment by repsac-by** [comment]
@vhscom please provide a minimal reproducible repo.

**Comment by vhscom** [comment]
For those who see this issue, ensure you're passing `duplex: 'half'` into any calls which are not using a `load` function or `RequestHandler` like. Oddly, I also had to pin `undici` using overrides to the same version kit pinned to (5.11.0).

```ts
const res = await fetch('/api/listing', {
  method: 'POST',
  // @ts-ignore-next-line - Types outdated
  duplex: 'half',
  body: JSON.stringify(theBody)
});
```
