### ISSUE TITLE
Feature Request: add actual link to "Not found (did you mean... ?)" page

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/kit#7474]
### Describe the problem

This is related to the 404 "did you mean...?" page added to fix [#2838](https://github.com/sveltejs/kit/issues/2838) which displays when you have a base path and run the dev server without the base path after the address.

That page is very helpful but it still requires you to actually copy and paste the base path after the address.

### Describe the proposed solution

I would like to see the /base-path/? part just turn into a clickable link which would take you to the correct place (not sure if this is actually possible though)

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
this was added at some point — closing
