### ISSUE TITLE
Sitemap Error

### ISSUE THREAD

**Issue by taishi55** [sveltejs/kit#7477]
### Describe the bug

By following [the instruction](https://kit.svelte.dev/docs/seo#manual-setup-sitemaps), I made `routes/[sitemap.xml]/+server.ts` but this generates a following error. 
`Error: Invalid param: sitemap.xml. Params and matcher names can only have underscores and alphanumeric characters.`

### Reproduction

Follow https://kit.svelte.dev/docs/seo#manual-setup-sitemaps

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 108.36 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 103.1.40.113
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.83 
    @sveltejs/kit: next => 1.0.0-next.517 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

### Severity

annoyance

**Comment by s3812497** [comment]
> ### Describe the bug
> By following [the instruction](https://kit.svelte.dev/docs/seo#manual-setup-sitemaps), I made `routes/[sitemap.xml]/+server.ts` but this generates a following error. `Error: Invalid param: sitemap.xml. Params and matcher names can only have underscores and alphanumeric characters.`

You need to remove the brackets `[ ]` around sitemap.xml. The brackets are used for parameterised routes.
