### ISSUE TITLE
template syntax - #if... as... for svelte stores

### ISSUE THREAD

**Issue by jdgamble555** [sveltejs/kit#7479]
### Describe the problem

Since Stores work just like Observables, it would be nice to have an **#if as** for the template syntax.

Angular has this ability like so:

```html
<div class="course-detail" *ngIf="post | async as _post; else loading">
```
This gets the posts value once, and allows you to use it many times after without calling the observable event again.  We don't need to re-subscribe.

### Describe the proposed solution

```jsx
{#if $post as _post}
  {_post.createdAt}
  <a href="..">{_post.title}
{/if}
```
This would allow us to only get the reactive value once ($posts), and not subscribe / unsubscribe to the observable everytime.

### Alternatives considered

Subscribe to the posts in the script tag, then unsubscribe:

```html
<script lang="ts">
  let post: Post;
  const unsub = postStore.subscribe(_post => post = _post);
  onDestroy(unsub);
</script>

{#if post}
...
{/if}
```

However, this is not reactive, and requires manually managing the subscription.

### Importance

would make my life easier

### Additional Information

Just adding a simple `as` for declaring the variable.

**Comment by Rich-Harris** [comment]
I don't understand — the subscription _is_ set up once and then torn down when the component is destroyed? What is the difference between this...

```svelte
{#if $post as _post}
  {_post.createdAt}
  <a href="..">{_post.title}
{/if}
```

...and this?

```svelte
{$post.createdAt}
<a href="..">{$post.title}
```

**Comment by Conduitry** [comment]
Having multiple `$post` references in your template doesn't create multiple subscriptions to the store. There's still just one for the whole component, no matter how many times it is used. This is part of what autosubscriptions in the framework takes care of for you.

**Comment by jdgamble555** [comment]
@Conduitry - Okay, if that is the case than consider this feature request a dud.  Thanks for the explanation!

J
