### ISSUE TITLE
Rest parameters unintuitive/inconsistent?

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/kit#748]
The way rest parameters in routes are written makes them look like the JS construct, but they are resolved to a string rather than a string array.

Is there a reason for that?

Turning the string into an array is fairly easy (`.split`), but so is turning an array back into a string (`.join`).

**Comment by Rich-Harris** [comment]
It's a lot easier to provide useful type information for TypeScript users if the `params` signature is `Record<string, string>` rather than `Record<string, string | string[]>`. As you say, it's trivial to convert the string to an array, so the typing benefits are sufficient reason
