### ISSUE TITLE
Not sure if issue but Tailwind not working latest SvelteKit -- "no utility classes were detected..."

### ISSUE THREAD

**Issue by MelodicCrypter** [sveltejs/kit#7481]
### Describe the bug

I think this bug is not closely related to SvelteKit, I can't say that yet. Coz previously, I also created and SvelteKit and Tailwind - working perfectly. Here are the versions in that previous app:

```
"@sveltejs/kit": "1.0.0-next.396",
"tailwindcss": "^3.1.3",
```

Right now, was planning to create a scaffolding for latest SvelteKit with Tailwind. But can't seem to make it work. I followed again Tailwind's doc for installing it with SvelteKit. I am already using latest SvelteKit with latest changes, structure, +page, +server, +layout, etc. Versions used are:

```
"@sveltejs/kit": "1.0.0-next.531",
"tailwindcss": "^3.2.1",
```

Overall situation:
- I think Tailwind seems integrated in the codebase
- but Tailwind's classes aren't loaded even I already imported the CSS in the +layout.svelte component (root of routes directory)

### Reproduction

_Simple Steps:_
1. Please create a new fresh latest SvelteKit with Typescript enabled: `pnpm create svelte@latest my-app`
2. Install Tailwind following official guides at: https://tailwindcss.com/docs/guides/sveltekit
3. Run dev

_Please take note:_
I'm using **PNPM**

### Logs

```Shell
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
```

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 540.50 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh

  Binaries:
    Node: 18.2.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.9.0 - /usr/local/bin/npm

  Browsers:
    Brave Browser: 100.1.37.116
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 15.5

  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.86 => 1.0.0-next.86 
    @sveltejs/adapter-node: 1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/kit: 1.0.0-next.531 => 1.0.0-next.531 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.2.2 => 3.2.2
```

### Severity

blocking an upgrade

**Comment by dominikg** [comment]
you can try to use `npx svelte-add@latest tailwindcss` , see https://github.com/svelte-add/tailwindcss

It creates a working setup that is very similar to what tailwind docs describe and you didn't share a reproduction repository so we can't tell what may be wrong. 

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

Please provide the information we asked for or we are going to close this issue.

**Comment by CaptainCodeman** [comment]
The extra config you posted in discord was incorrect. There is no problem with SvelteKit or TailwindCSS, and having them work together. As suggested, the easiest way to get a working setup is to use the svelte-add system.

**Comment by dummdidumm** [comment]
Closing as it sounds this is not an issue with SvelteKit itself.
