### ISSUE TITLE
Run `handle` between action and `load`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#7482]
### Describe the problem

If a form action sets a cookie with `cookies.set('blah')`, any `load` functions that read the cookie with `cookies.get('blah')` will get the updated value.

If, on the other hand, the cookie is read in `handle`, for example like this...

```js
export async function handle({ event, resolve }) {
  event.locals.user = await get_user(event.cookies.get('sessionid'));
  return resolve(event);
}
```

...`locals.user` is not updated by the time the page is rendered in response to the form submission.

### Describe the proposed solution

Honestly I'm not sure what the correct solution is here. Conceptually, it's a single request, so it's correct that `handle` isn't called between the action and the load. But it does result in surprising behaviour.

Of course, if we _did_ run `handle` again with a fresh `RequestEvent` object, it would prevent you from adding data to `locals` inside the action that your `load` functions then depended on. (Perhaps we re-run `handle` with the same `RequestEvent`, or at least the same `locals`?)

### Alternatives considered

The alternative is just to document the current behaviour.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
After trying various different approaches to this problem, I think the most natural solution is to update `event.locals` at the point at which the cookie is set. In most cases this won't be many places in the app. Still a tiny bit of a footgun though.

**Comment by dummdidumm** [comment]
What would that mean exactly in this context? Where would one update `event.locals` to get the desired behavior?

**Comment by Rich-Harris** [comment]
```js
// src/hooks.server.js
export async function handle({ event, resolve }) {
  event.locals.user = await getUser(event.cookies.get('sessionid'));
  return resolve(event);
}
```

```js
// src/routes/login/+page.server.js
export function load({ locals }) {
  // `locals.user` is populated by `handle` when we first come to `/login`, but
  // is populated by the action following a form submission...
  console.log('user', locals.user);
}

export const actions = {
  login: async ({ cookies, locals, request }) => {
    const data = await request.formData();
    const username = data.get('username');
    const password = data.get('password');

    const { user, sessionid } = await login(username, password);

    cookies.set('sessionid', sessionid, { path: '/' });
    locals.user = user; // <-- ...here
  }
}
```
