### ISSUE TITLE
polyfillModulePreload is deprecated. Use modulePreload.polyfill instead.

### ISSUE THREAD

**Issue by talgolan** [sveltejs/kit#7485]
### Describe the bug

When executing...

`npm run build`

I have started seeing the following at the very beginning of the process...

`polyfillModulePreload is deprecated. Use modulePreload.polyfill instead.`

This DOES NOT appear to be producing any negative side effects, however, I would like to know how to resolve this warning.

Please advise.

### Reproduction

npm run build

### Logs

```Shell
npm run build

> svelteKitProject@4.20221103.0019 build
> vite build

polyfillModulePreload is deprecated. Use modulePreload.polyfill instead.
vite v3.2.2 building for production...
transforming (16) src/routes/magic/publish/+page.svelteModule level directives cause errors when bundled, 'use strict;' was ignored.
✓ 460 modules transformed.
Generated an empty chunk: "modules/pages/tests/gridTastic/_page.js"
polyfillModulePreload is deprecated. Use modulePreload.polyfill instead.
vite v3.2.2 building SSR bundle for production...
```

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 35.62 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 106.0.3
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/kit: 1.0.0-next.532 => 1.0.0-next.532 
    svelte: 3.52.0 => 3.52.0 
    vite: 3.2.2 => 3.2.2
```

### Severity

annoyance

**Comment by otaux** [comment]
This warning has begun after the update of vite - not sveltekit. In their docs they state it's deprecated: https://vitejs.dev/config/build-options.html#build-polyfillmodulepreload

Don't want to piggyback this issue, but there is also another warning after vite update.

Example CSS:
`background-image: url("/img/icon.svg");`

Throws this warning during build:
`/img/icon.svg referenced in /webapp/src/routes/+layout.svelte?svelte&type=style&lang.css didn't resolve at build time, it will remain unchanged to be resolved at runtime`

The warning is thrown for anything what is referenced via url(), may it be an image or font file.
