### ISSUE TITLE
inlineStyleThreshold does not create a style tag with adapter-static

### ISSUE THREAD

**Issue by newsroomdev** [sveltejs/kit#7492]
### Describe the bug

<img width="1624" alt="Screen Shot 2022-11-03 at 9 40 47 PM" src="https://user-images.githubusercontent.com/1578563/199872050-ae8857ef-5577-4e69-9995-601063269bc1.png">

While #2620 created an option to inline CSS, the config does not currently add `style` tags when using `adapter-static`. I've created a [minimum reproducible repo](https://github.com/newsroomdev/sveltekit-static-no-inline-styles) and added some [initial exploration notes](https://github.com/sveltejs/kit/issues/962#issuecomment-1297128914) to #962. Although the value for `inlineStyleThreshold` gets read, it gets overwritten by the [`options` function in kit/src/core/config/index.js](https://github.com/sveltejs/kit/blob/177a5a9f8219f3f9633d8f8dc879f8472f74d6a2/packages/kit/src/core/config/index.js#L109).

### Reproduction

https://github.com/newsroomdev/sveltekit-static-no-inline-styles contains two commits:

* [First](https://github.com/newsroomdev/sveltekit-static-no-inline-styles/commit/7adc85e4d70154c90d3e46860f2dedb6cdf5854e): Initial commit generated by `npm create svelte@latest`
* [Second](https://github.com/newsroomdev/sveltekit-static-no-inline-styles/commit/60a0807d111e0ff4b4309a664cf3f21a19f2872a): Removes Sverdle and adds `adapter-static`

### System Info

```Shell
System:
  OS: macOS 12.6.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 2.88 GB / 32.00 GB
  Shell: 3.5.1 - /opt/homebrew/bin/fish
Binaries:
  Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
  npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
Browsers:
  Brave Browser: 106.1.44.101
  Chrome: 107.0.5304.87
  Firefox: 105.0.1
  Safari: 16.1
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.86
  @sveltejs/adapter-static: next => 1.0.0-next.47
  @sveltejs/kit: next => 1.0.0-next.532
  svelte: ^3.46.0 => 3.52.0
  vite: ^3.1.0 => 3.2.2
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
The inlineStyleThreshold is a SvelteKit specific option, so it shouldn't be at the top level, but inside `config.kit`. @newsroomdev can you check again with that?

**Comment by newsroomdev** [comment]
Good catch; user error on my part. Thank you @gtm-nayan
