### ISSUE TITLE
Resolve path aliases for service worker imports

### ISSUE THREAD

**Issue by egargan** [sveltejs/kit#7496]
### Describe the problem

I have some code that I'd like to share between some SvelteKit endpoints and my service worker.

When I try to import these modules in my service worker using a custom path alias (e.g. `import addOne from '$utils/addOne';`), then build the service worker with `vite build`, I get the following error --

```
[vite]: Rollup failed to resolve import "$utils/addOne" from "src/service-worker.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

I've tried doing as this error asked, but no luck!

I've created this repo as a minimal reproduction: https://github.com/egargan/sveltekit-service-worker-alias-issue. 
Clone it, install deps, then run `npx vite build` to see the error mentioned above.

Interestingly, the default `$lib` alias works!

### Describe the proposed solution

I'd like custom aliases defined in `svelte.config.js` to be respected when building a service worker. `vite build` should output a service worker with the alias-imported modules bundled into it.

### Importance

would make my life easier

**Comment by egargan** [comment]
I've managed a fix in this branch, probably needs a bit of work, e.g. I imagine the `$app` and `__GENERATED__` aliases aren't relevant to the service worker, but am I on the right lines? Happy to continue with this with some guidance.

https://github.com/egargan/kit/commit/2a5049e05734a83e689a3fff8ff3d69242889953

**Comment by dummdidumm** [comment]
This looks about right, my suggestion is to split up the alias generation utility in two, where one just cares about `$lib` and the user-defined aliases, and the other adds `$app` etc on top.
