### ISSUE TITLE
Re-exporting components always loads all components and all their dependencies

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#7509]
### Describe the bug

In my SvelteKit project I have a whole bunch of reusable components in my `/src/lib/components` folder. To make it easier to import them, I added a `/src/lib/components/index.ts` file like this:

```
import Modal from "./Modal.svelte";
import LoadingOverlay from "./LoadingOverlay.svelte";
import FileUpload from "./FileUpload.svelte";
import Avatar from "./Avatar.svelte";
import Markdown from "./Markdown.svelte";
// and a whole lot more

export {
  Modal,
  LoadingOverlay,
  FileUpload,
  Avatar,
  Markdown,
  // and a whole lot more
};
```

This allows me to do to this:

```
import { Button, Textarea } from "$lib/components"
```

instead of this:

```
import Button from "$lib/components/Button.svelte"
import Textarea from "$lib/components/Textarea.svelte"
```

It works. However, this causes all the components and their dependencies to be loaded every time I import *any* component. For example I have a rather complex Editor component which loads a wysiwyg editor dependency, my Markdown component imports the marked dependency, etc. And now even if I only import a Button on a page, all those other things get loaded too. This is causing way way too much JS to be loaded when you visit my website, the initial page loads hundreds of JS files when it's not even using all that stuff on that page.

Besides getting rid of this index file and changing all my imports (hundreds of them), is there another solution to this problem?

This doesn't help, by the way:

```
export { default as Modal } from "./Modal.svelte";
// and all the others...
```

### Reproduction

https://github.com/kevinrenskers/sk-components

Load the website, and open the network inspector. You can see that Avatar.svelte is loaded, even though it's never used anywhere. And if this component would import a big NPM dependency, that is loaded as well.

![Screenshot 2022-11-04 at 23 55 18](https://user-images.githubusercontent.com/229384/200086324-4deee7f8-014c-454b-a404-521f3e9c5b65.png)

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 329.59 MB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Firefox: 106.0.1
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87
    @sveltejs/kit: next => 1.0.0-next.535
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.2.2
```

### Severity

serious, but I can work around it

**Comment by CaptainCodeman** [comment]
You're comparing dev mode, it's focusing on speed not optimizing bundles.

For comparing performance and build output it _has_ to be a proper build.

The component is correctly excluded.

**Comment by PatrickG** [comment]
I had this problem in production builds as well.
There were chunks loaded that had components with big 3rd-party libs that were never used on the current route.
But that was about 6 months ago. I haven't tested it since then.

**Comment by kevinrenskers** [comment]
I am indeed not seeing it in production builds. That is a huge relief! I think this issue can be closed, thanks @CaptainCodeman.
