### ISSUE TITLE
`cookies.get` incorrectly logs a warning when a cookie was removed from the browser instead of `cookies.delete`

### ISSUE THREAD

**Issue by ptlthg** [sveltejs/kit#7510]
### Describe the bug

Context provided by @dummdidumm in Discord:
> Some context about this warning and how the logic is to surface it:
Why this warning: Cookies have a path. This means they are only available at this path and below. So a path of /foo means your cookie is available at /foo, /foo/bar etc, but not / or /sthelse. Not setting the path value means the cookie's path is set to where the cookie is set on. This is a source of confusion ("why is my cookie not deleted/set/available?") so we added that warning. That said, that warning could probably use some love, at least a link to some more in-depth explanation what this is about.
> 
> Logic to surface it: Whenever you call cookies.set in dev mode, that cookie's name and its path are stored in a map, and whenever you call cookies.get and it turns up nothing, it prints a warning if a cookie with that name exists in that map. False positives could occur if you remove a cookie through another method - and writing this I just realized that session cookies are probably also false positives: If you set a cookie, close the browser tab and open it again, a session cookie is removed from the browser, but not from the map. Maybe that's something that happens here?

It seems that these proposed false positives are correct, when a cookie is removed via exterior means but still expected to be there via `cookies.get` this warning is thrown. However, the warning says "`did you mean to set its 'path' to '/'?`" even when the path is set correctly. 

I propose that this warning is only logged when the path isn't `/`, and print the path(s) associated with the cookie. If it is already set to `/`, then these cookies should be removed from the map to align with the lack of them in the browser. I'll attempt to submit a PR to fix this myself shortly, but I'm not super familiar with the inner workings of the project, so it might not be perfect.

### Reproduction

A simple reproduction can be found in [CookiesGetWarningRepro](https://github.com/ptlthg/CookiesGetWarningRepro), but it's a simple thing to check. Just remove a cookie from your browser in dev tools, then refresh or try to access it via `cookies.get` afterwards. The warning should then be logged.

### Logs

```Shell
Cookie with name 'session-cookie' was not found, but a cookie with that name exists at a sub path. Did you mean to set its 'path' to '/'?
Cookie with name 'normal-cookie' was not found, but a cookie with that name exists at a sub path. Did you mean to set its 'path' to '/'? 
Cookie with name 'expires-cookie' was not found, but a cookie with that name exists at a sub path. Did you mean to set its 'path' to '/'?
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 45.67 GB / 59.86 GB
  Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87
    @sveltejs/kit: next => 1.0.0-next.535
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.2.2
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Haven't checked yet, but does the browser send all cookies to the server it currently has for this site? If yes, it should be solveable by checking the initially parsed headers and remove/add anything that comes from that.

**Comment by cdcarson** [comment]
> Whenever you call cookies.set in dev mode, that cookie's name and its path are stored in a map, and whenever you call cookies.get and it turns up nothing, it prints a warning if a cookie with that name exists in that map.

The presence of the cookie in the request should be the only source of truth. Previously set cookies can and do expire, and therefore are not sent. (For example,  setting a short-lived "flash message" or "permission" cookie on  a certain path.) This does not warrant a warning, even in dev. It's the expected behavior. 

> This is a source of confusion ("why is my cookie not deleted/set/available?") so we added that warning.

My reading (could be wrong) of those issues was that folks were setting/deleting cookies without the path, thus inadvertently setting the path to `/__data.json` rather than `/`. This could be avoided by requiring the developer to set the path -- in fact, I'd say it'd make the API more straightforward.

**Comment by ptlthg** [comment]
> The presence of the cookie in the request should be the only source of truth.

I agree with all of this, but I was wondering if this level of robustness was necessary, as it's just dev mode exclusive functionality. Looking at the new PR, though, I agree this a much better solution. Thanks everyone for looking into this.
