### ISSUE TITLE
authorization header not present in getContext()

### ISSUE THREAD

**Issue by higoka** [sveltejs/kit#753]
Okay so i dont know if im doing something wrong or if this is a bug but what im trying to do is implement a login system using JWT. In my `index.svelte` i have a simple form which posts the username and password to the `/login` endpoint which i then check if username and password are correct. If they are i create a (dummy) token and set a `authorization` header. Now finally inside `getContext()` i want to check if the `authorization` header is a valid JWT token and set the user session but when i do a `console.log()`on the request headers, no `authorization` header is present even though i set it when the user enters the correct login credentials.

**Here are some snippets:**

`src/routes/index.svelte`
```svelte
<script>
  let username
  let password

  async function handleSubmit () {
    const res = await fetch('/login', {
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify({ username, password })
    })
    
    console.log(await res.json())
  }
</script>

<h1>Login</h1>
<form on:submit|preventDefault={handleSubmit}>
  <p>
    <label for="username">Username</label>
    <input type="text" id="username" bind:value={username} />
  </p>
  <p>
    <label for="password">Password</label>
    <input type="password" id="password" bind:value={password} />
  </p>
  <p>
    <button>Login</button>
  </p>
</form>
````

`src/routes/login.js`
```js
export async function post ({ body }) {
  const { username, password } = body

  // only for testing purposes
  if (username === 'a' && password === 'b') {
    const token = 'foo' // dummy token
    return {
      headers: {
        authorization: `Bearer ${token}`
      },
      body: {
        msg: 'success'
      }
    }
  }

  return {
    status: 401,
    body: {
      msg: 'incorrect username or password'
    }
  }
}
```

`src/hooks/index.js`
```js
export async function getContext ({ headers }) {
  console.log(headers) // no authorization header ?

  // fake user for testing purposes
  const user = {
    username: 'foo',
    email: 'foo@example.com'
  }

  return { user }
}
```

**Expected behavior**
I was expecting an `authorization` header to be there so that i can verify the token and set the user session.

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.65 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.10.0 - /usr/local/bin/node
    npm: 7.5.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.62 
    svelte: ^3.29.0 => 3.35.0

- Your browser
Google Chrome

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Node

**Comment by Rich-Harris** [comment]
It's a bug, tracked at https://github.com/sveltejs/kit/issues/672. Closing this in favour of that one.
