### ISSUE TITLE
Provide "routeId" as prop to top level route component

### ISSUE THREAD

**Issue by johnnysprinkles** [sveltejs/kit#7542]
### Describe the problem

Sometimes when you're using `beforeNavigation` and `afterNavigation` you want to know if you're arriving at or leaving the current page. Let's make a hypothetical app with two routes, where A route has some changes you can make you'd want to confirm before abandoning.

/routes/a/+page.svelte
/routes/b/+page.svelte

In the former we could have something like this:

```
<script>
  import { beforeNavigate } from '$app/navigation';

  beforeNavigate(({from, to, cancel}) => {
    if (to.routeId != 'a' && dirty) {
      cancel();
      alert('Save changes before leaving');
    }
  });
```

It's unfortunate to have to hard code the routeId. There is `$page.route` but that's not the "lexically" current route, i.e. it will update as soon as you've navigated.

Would it make sense to pass a prop for routeId into the component for comparison? Then the code would look like:

```
<script>
  import { beforeNavigate } from '$app/navigation';

  export let routeId;

  beforeNavigate(({from, to, cancel}) => {
    if (to.routeId != routeId && dirty) {
      cancel();
      alert('Save changes before leaving');
    }
  });
```

### Describe the proposed solution

See above.

### Alternatives considered

Maybe checking if the routeIds are the same on to/from is good enough, like to check for leaving the page it could be something like:

```
beforeNavigate(({from, to, cancel}) => {
  if (from.routeId != to.routeId) {
    // leaving page
  }
});
```

Because when arriving at the page the "beforeNavigate" won't have been registered yet.

I think this logic would run afoul of the non-local transitions extending the page lifecycle though.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
You're right that `from.route.id !== to.route.id` is sufficient (side-note: `routeId` was replaced with `route.id` in #7450), for both `beforeNavigate` and `afterNavigate`. Given that, I don't think there's all that much value in adding a prop, when it would only apply to pages (not layouts) and you'd have to manually pass it down to components below the route component. 

> I think this logic would run afoul of the non-local transitions extending the page lifecycle though.

Not sure I follow?

**Comment by Rich-Harris** [comment]
Ah, I see. Oof. The fact that `afterNavigate` can be called on the page we just left is a bigger bug than any potential confusion around route IDs, albeit not one I'm sure that we can solve. I think we probably want to discourage non-local `out` transitions altogether, as they're somewhat problematic. That whole area is due for a rethink when Svelte 4 comes along.

So I don't think it changes the equation — you always have the option of hardcoding the route ID, and if we get round to making the type of `route.id` an enum that only includes the routes in your app then I reckon we're covered.

**Comment by johnnysprinkles** [comment]
Sounds good. Let me close.
