### ISSUE TITLE
Using named slots in +layout and +page

### ISSUE THREAD

**Issue by mscofield0** [sveltejs/kit#7553]
### Describe the problem

Currently the following syntax isn't allowed in SvelteKit:
```html
<!-- +layout.svelte -->
<slot name="test-slot" />
```
```html
<!-- +page.svelte -->
<div slot="test-slot"> <!-- Element with a slot='...' attribute must be a child of a component or a 
                            descendant of a custom elementsvelte(invalid-slotted-content) -->
</div>
```

Which is weird because +layout components *are* custom-Svelte-element parents of the +page component. 

### Describe the proposed solution

I would like to see it become a "syntax" (not sure of a better word) feature of SvelteKit where the above syntax becomes valid.

### Alternatives considered

Alternatively, don't do anything and just enforce a custom Svelte element to be created and used instead. (not very ergonomic imo)

### Importance

would make my life easier

**Comment by PatrickG** [comment]
Duplicate #627

**Comment by mscofield0** [comment]
Ah damn, 2019 and still not implemented :( I'll close this one
