### ISSUE TITLE
Don't generate CSS twice

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#7555]
### Describe the problem

Both the client and server bundles generate CSS

### Describe the proposed solution

Merge https://github.com/sveltejs/svelte/pull/7914. Bump peer dep to latest Svelte. Then I think we can set `'none'` for one of the builds?

### Importance

nice to have

**Comment by Rich-Harris** [comment]
closing per https://github.com/sveltejs/kit/pull/7590#issuecomment-1310606660
