### ISSUE TITLE
automatically replace $env variables with process.env in edge functions

### ISSUE THREAD

**Issue by jdgamble555** [sveltejs/kit#7556]
### Describe the problem

Edge functions in Vercel do not work as expected. You have to specify the variable EXACTLY in `process.env` for it to work, while $env seem to get translated automatically in regular lambdas.

It would be nice if all $env variables were replaced with `process.env` so that I would not have to configure it manually with something like:

```js
import { env } from '$env/dynamic/public';
import { createClient } from '@supabase/supabase-js';

const isLocal = Object.keys(env).length;

export const supabase = createClient(
    (isLocal ? env.PUBLIC_SUPABASE_URL : process.env.PUBLIC_SUPABASE_URL) as string,
    (isLocal ? env.PUBLIC_SUPABASE_ANON_KEY : process.env.PUBLIC_SUPABASE_ANON_KEY) as string
);
```

### Describe the proposed solution

The vercel adapter does this if the `edge: true` is set.

### Alternatives considered

My workaround code above.

### Importance

would make my life easier

### Additional Information

Obviously this would not be necessary if SvelteKit handled this internally, or if Vercel Edge functions handled env variables the same way as regular functions.

**Comment by jdgamble555** [comment]
Ok, thanks for the update. In my case, this was okay (with Supabase):

```js
import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';
```

J

Good to know Vercel is working on getting everything working the same across environments.

**Comment by leerobert** [comment]
Can confirm this is how I set up my `supabaseClient.ts` for vercel deployment:

```
import { createClient } from '@supabase/auth-helpers-sveltekit';
// import { env } from '$env/dynamic/public';
import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';

//export const supabase = createClient(env.PUBLIC_SUPABASE_URL, env.PUBLIC_SUPABASE_ANON_KEY);
export const supabase = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);
```

**Comment by MiraiSubject** [comment]
I also ran into this issue recently, however even when following the documentation and setting `envVarsInUse` with my array of environment variables I want to be accessible to the edge function they are still not available. 

From the sveltekit docs: 

![CleanShot 2023-05-02 at 20 33 03](https://user-images.githubusercontent.com/803255/235754553-31ff9773-3219-48e6-a5c6-fad45bc47bb6.png)

From the vercel docs: 

![CleanShot 2023-05-02 at 20 33 30](https://user-images.githubusercontent.com/803255/235754705-3003ae40-d2d8-46a6-a916-26de65d9cb19.png)

My `svelte.config.js`: https://github.com/MiraiSubject/sveltekit-env-vars-repro/blob/1be777331b3b34d0744f76f980a82c818757f311/svelte.config.js#L16-L24

However this simple [repro](https://github.com/MiraiSubject/sveltekit-env-vars-repro) shows that even that is non-functional. 

On vercel before building the project I have specified the environment variables like this: 

![CleanShot 2023-05-02 at 20 29 09](https://user-images.githubusercontent.com/803255/235755348-da750e8b-734e-4d0f-a783-48e02f971c7e.png)

But in the deployment: https://sveltekit-env-vars-repro.vercel.app/ only the `VERCEL_REGION` gets printed.

I noticed that both of the documentations mention `edge: true` which has been changed to `runtime: 'edge', so maybe something might have been changed in the behaviour of this as well? 

Am I potentially missing something here or does `envVarsInUse` just not work at all anymore for Vercel? 

Either way if the dynamic option really doesn't work, it's going to be difficult for us to maintain both a Vercel and self-hosted docker image, where in the latter case consumer should supply their own keys.

**Comment by MiraiSubject** [comment]
As of `@sveltejs/adapter-vercel@3.0.0` https://github.com/sveltejs/kit/releases/tag/%40sveltejs%2Fadapter-vercel%403.0.0 Environment variables in `$env/dynamic/private` and `$env/dynamic/public` now work as expected. 

This can be closed now because https://github.com/sveltejs/kit/pull/9942 fixes the issue.
