### ISSUE TITLE
dev server crashes with message 'Invalid state: ReadableStream is locked'

### ISSUE THREAD

**Issue by ivanhofer** [sveltejs/kit#7560]
### Describe the bug

Whenever I run code for my routes and an error occurs, the dev server crashes with the message `'Invalid state: ReadableStream is locked'`.

Here is the line that produces this error: https://github.com/sveltejs/kit/blob/11950e00ac57919b09e6148b78004bbeb002a446/packages/kit/src/exports/node/index.js#L125

This is really annoying and stops me from beeing productive when I have to restart the server multiple times per hour or even per minute while experimenting with some concepts.

I can workaround the issue for now by replacing the line with
```ts
	let reader
	try {
		reader = response.body.getReader();
	} catch (e) {
		res.end();
		return;
	}
```

I would expect the dev server just to output an error e.g. "Not found: /foo" and not to chrash the whole server

### Reproduction

1. Start up a SvelteKit project.
2. Visit a route that does not exist (404 error).
3. You should see the dev server crash.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 699.55 MB / 7.65 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.18.0 - ~/.volta/tools/image/npm/8.18.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.68
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/kit: 1.0.0-next.532 => 1.0.0-next.532 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.2.2 => 3.2.2
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Can't reproduce this given the instructions, so there's probably more that's needed for this to crash -> please provide a reproduction repo.

**Comment by ivanhofer** [comment]
Sorry, I forgot to comment out our logging middleware before submitting this issue.. and that was producing the error 🙈

Whenever an error happens, the middleware logs the content of the `Response` object. 
Cloning the response with `response.clone()` before passing it to the middleware solves the issue.

Here is a reproduction of the issue: https://stackblitz.com/edit/sveltejs-kit-template-default-d3y1jy?file=src/hooks.server.js

In this case it's clearly a 3rd party that produces this issue (the same code was working the last 6+ months, it did just break recently).

But I'm thinking if SvelteKit could
1. display a more clear error message
2. catch the error so the server doesn't crash

What do you think?

**Comment by ivanhofer** [comment]
Not just the dev server is affected. Also the production build can crash when using the `node` adapter.
