### ISSUE TITLE
It's not possible to define a lower TS lib in tsconfig

### ISSUE THREAD

**Issue by i-rme** [sveltejs/kit#7561]
### Describe the bug

Hi,
We are trying to set a lower TypeScript lib version of ECMAScript but we are unable to do so when using Svelte / Svelte-kit.

Our intention is the following:
We want to avoid using newer methods like `String.prototype.replaceAll()` inside our `<script lang="ts">` snippets or in any .ts file of the project, as this breaks compatibility with older browsers, as this method was introduced in ES2021.

In other frameworks like Angular, you can just set a lower TS lib version on the `tsconfig.json` file like this:
```
"lib": [
	"ES2018",
	"DOM"
],
```

This way, if you try to use `String.prototype.replaceAll()` in your project, the build process fails with the following error:
`Error: [...].ts:24:28 - error TS2550: Property 'replaceAll' does not exist on type String. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.`

This avoids breaking older browsers.

### Reproduction

Create a demo project selecting all the default options:

```
npm create svelte@latest my-app
cd my-app
npm install
```

Add the following code to app.html

```
<script lang="ts">
	console.log("test".replaceAll("t", "r"));
</script>
```

Add the following code to tsconfig.json / jsconfig.json
`
"lib": [
	"ES2018",
	"DOM",
	"DOM.Iterable"
],
`

Build or run the project:

`npm run dev -- --open`

Expected output:
_an error as we are using non compatible methods_

Actual output:
_no errors_

### Logs

```Shell
_not relevant in this issue_
```

### System Info

```Shell
_not relevant in this issue_
```

### Severity

annoyance

### Additional Information

As we are new to Svelte / Sveltekit, we might be doing something wrong or missing something, please be kind.

**Comment by dummdidumm** [comment]
`npm run dev` doesn't do type checking, use `svelte-check` for that. There should be scripts for a one-time run (`check`) and one for ongoing checks (`check:watch`) in there. Also your IDE should show an error (VS Code at least).

**Comment by i-rme** [comment]
Thanks for your answer, but svelte-check returns no errors.

```
> my-app@0.0.1 check
> svelte-kit sync && svelte-check --tsconfig ./jsconfig.json


====================================
Loading svelte-check in workspace: c:\Users\rmartinez\Downloads\sveltekit-demo-project\my-app
Getting Svelte diagnostics...

====================================
svelte-check found 0 errors, 0 warnings, and 0 hints
```

**Comment by dummdidumm** [comment]
You're saying you added the code to `app.html ` - was that by mistake? `app.html` shouldn't be touched normaly, you do most if not all your work inside Svelte/JS/TS files - and it also isn't checked.
