### ISSUE TITLE
URI decoding of routes does not work except for select few characters

### ISSUE THREAD

**Issue by dmkret** [sveltejs/kit#7567]
### Describe the bug

When there is %-encoded character in pathname decodable by `decodeURI`, server sends 200 response for pages and 404 for static files (+page.js, +page.svelte etc.)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-s8cge5

1. Click on `goto /%5b`
2. Expected: `this is %5b`. Received: glitch, `this is %5b` changes to `500 internal error`.

Inside network inspector you can see that `GET /%5b/+page.svelte` fails with 404.

### Logs

```Shell
Not found: /src/routes/%5b/+page.svelte
Error: Not found: /src/routes/%5b/+page.svelte
    at resolve (file:///home/projects/sveltejs-kit-template-default-s8cge5/node_modules/@sveltejs/kit/src/runtime/server/index.js:281:13)
    at resolve (file:///home/projects/sveltejs-kit-template-default-s8cge5/node_modules/@sveltejs/kit/src/runtime/server/index.js:312:5)
    at Object.handle (file:///home/projects/sveltejs-kit-template-default-s8cge5/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:360:66)
    at respond (file:///home/projects/sveltejs-kit-template-default-s8cge5/node_modules/@sveltejs/kit/src/runtime/server/index.js:309:40)
    at async eval (file:///home/projects/sveltejs-kit-template-default-s8cge5/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:430:22)
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87 
    @sveltejs/kit: next => 1.0.0-next.538 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.3
```

### Severity

annoyance

**Comment by dmkret** [comment]
Should %-encoded characters, decodable by `decodeURI` be completely rejected in folder names?

**Comment by benmccann** [comment]
> When there is %-encoded character in pathname decodable by decodeURI, server sends 200 response for pages and 404 for static files (+page.js, +page.svelte etc.)

I don't understand the terminology here. Static files generally refer to files that live in `static`. Pages generally mean `+page.svelte`. Is it all directories with a %-encoded character that are failing? Can you clarify what cases are working? (i.e. sending a 200)

**Comment by dmkret** [comment]
@benmccann I mean

If directory segment contains uri-decodable character:
When `html` requested, server returns `200`.
When `.js`/`.svelte` requested, server returns `404`.

I updated project on stackblitz.

There are 2 folders with encoded characters and one [slug].
1. Folder with `%5b`. Request to `/%5b` returns `200` for html and `404` for .js/.svelte. Correct candidate used.
2. Folder with `%40`. Request to `/%40` returns `200` for all. Incorrect `[slug]` candidate used.
Request to `/@` returns `200` for all, Correct candidate is used.
3. Folder with `[slug]`. Requests `/%5d` returns `200` for all. Correct candidate used.

**Comment by benmccann** [comment]
This is a regression. You used to be able to have a directory named something like `%5b`. It was broken in https://github.com/sveltejs/kit/commit/b30d2b64e4843a309f1033100a5d9d1e774c5140. Unfortunately that PR is 900 files large, so not exactly easy to pin down...

**Comment by benmccann** [comment]
My guess is this is some kind of bug in `write_client_manifest`? I'm a bit stumped and would love if you could figure this out

**Comment by dmkret** [comment]
@benmccann I am wonder to check this, but in next week

**Comment by benmccann** [comment]
Actually, I lied. It was broken before that commit. I forgot to update my test to the old routing system and another page started loading making it look like it was working. It's been broken for at least a year. I don't know if it ever worked. We do seem to have some docs for it, but I guess we just tested the very few characters that worked and assumed they all did...
