### ISSUE TITLE
Percent-encoded underscore in route throws 500 error

### ISSUE THREAD

**Issue by georgecrawford** [sveltejs/kit#7570]
### Describe the bug

https://github.com/sveltejs/kit/pull/5056 introduced %-encoded filenames. There are test which assert that, for example, the route at `/encoded/@svelte` will be matched by a file at `routes/encoded/%40svelte/+page.svelte`.

However, I've found that when an underscore is %-encoded in the same way, the SvelteKit server throws a 500 error.

### Reproduction

- In the SvelteKit **basics** test app, create a file at `/src/routes/encoded/%5Funderscore-prefix/+page.svelte`
- Run `pnpm run dev`
- Visit `http://127.0.0.1:5173/encoded/_underscore-prefix`
- Observe that the server-side rendering works fine
- Observe that Vite requests the source file at `http://127.0.0.1:5173/src/routes/encoded/_underscore-prefix/+page.svelte`, and receives the response `dynamically rendered file` (from the generic fallthrough server at `/src/routes/src/[...anything]/+server.js`.
- Observe the console error `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.` thrown in `+page.svelte:1 `
- Observe the error page is shown, with the error `This is your custom error page saying: "Failed to fetch dynamically imported module: http://127.0.0.1:5173/.svelte-kit/generated/nodes/83.js"`

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 216.06 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.08.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Chrome Canary: 109.0.5410.0
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    svelte: ^3.52.0 => 3.52.0
```

### Severity

annoyance

**Comment by dmkret** [comment]
Relates to #7567

**Comment by georgecrawford** [comment]
I think this probably relates to https://github.com/sveltejs/kit/issues/7554 too.

**Comment by benmccann** [comment]
Did you just try this for the first time and find it was broken? Or was it working previously and then broken upon an upgrade?

**Comment by benmccann** [comment]
if you want to use an underscore prefix then just use an underscore. there's no need to encode it

**Comment by georgecrawford** [comment]
Woah. Sorry for the noise. Back a few months ago (and I appreciate that lots has changed since then), `__` was a reserved prefix for 'blessed' files. But now I can create `__health/+page.svelte` and it all just works. I was trying to fix a problem which doesn't exist. Thanks for your time @benmccann and sorry for wasting it. :/
