### ISSUE TITLE
"plugins": ["prettier-plugin-svelte"] in .prettierrc is preventing VSCode for auto-formatting *.svelte files

### ISSUE THREAD

**Issue by regnaio** [sveltejs/kit#7582]
### Describe the bug

`"plugins": ["prettier-plugin-svelte"]` in `.prettierrc` is preventing VSCode from auto-formatting `*.svelte` files

After removing this line, Alt+Shift+F is now able to successfully auto-format `*.svelte` files

A Skeleton project was created 2 days ago using `@sveltejs/kit@1.0.0-next.538` reproducing this

### Reproduction

A Skeleton project was created 2 days ago using `@sveltejs/kit@1.0.0-next.538` reproducing this

### System Info

```Shell
Windows WSL 2

System:
    OS: Linux 4.19 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 18.65 GB / 24.92 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.3.1 - /usr/bin/node
    Yarn: 1.22.10 - /mnt/c/Program Files/nodejs/yarn
    npm: 8.3.0 - /usr/bin/npm

But using Docker container with `node:16.16.0-slim`
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
@dummdidumm maybe you'd have some ideas about this one?

**Comment by manninobobby** [comment]
I’m having a similar issue when I remove svelte plugin and swap for prettier-plugin-tailwindcss

**Comment by bobbymannino** [comment]
![](https://cdn.discordapp.com/attachments/1053551133160914956/1053552256974344192/image.png)

Found this in the discord chat, seems to fix the problem with svelte and tailwind plugin

**Comment by eltigerchino** [comment]
Closing as resolved by https://github.com/sveltejs/language-tools/pull/1829
