### ISSUE TITLE
`beforeNavigate` runs twice if redirecting in the navigation targets `load`

### ISSUE THREAD

**Issue by Addeuz** [sveltejs/kit#7584]
### Describe the bug

Don't know if this is a bug or a feature... But if I have a before navigate in a route. And then I redirect in the load function on the route we are navigating to. The beforeNavigate runs twice in the original route.

### Reproduction

It's reproduced here:
https://stackblitz.com/edit/sveltejs-kit-template-default-5ed6za?file=src/app.html

I've made this example of the bug occuring.
If we are at the `/` route (Home) and then go to `/about` (About) "BEFORE" is only logged once.
But if we go back to `/` and then go to `/test` (Test) we are correctly redirected to `/about` but "BEFORE" is logged twice.
The console looks like this for the latter case:
```
BEFORE
LOAD IN TEST
BEFORE
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87 
    @sveltejs/kit: next => 1.0.0-next.539 
    svelte: ^3.46.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.3
```

### Severity

serious, but I can work around it

### Additional Information

This is quite a serious bug for how we use `beforeNavigate` in our application. But can be worked around

**Comment by dummdidumm** [comment]
If we deem this behavior working as expected, we should at least introduce a `type: 'redirect'` so these events can easily be ignored.

**Comment by Addeuz** [comment]
I was talking to Kevin in the Swedish Svelte discord. And he made me think that it was not a bug if you think about it. So I tested some more and printed out `to.route` as well. And that gave me this:
![image](https://user-images.githubusercontent.com/12641358/201112385-abd957d4-1942-4274-ae92-d0400397bc5f.png)

But a type that allows us to ignore it as you said would be nice.

<details>
  <summary>Summary of our discussion</summary>
  
  My argument for why it should be a bug and not a "feature" was that when I navigate to a route that checks in its load if a user is authenticated. And the user isn't authenticated, I might want to throw a redirect to another route. Then it would be weird if we would run the beforeNavigate in the original route.

His argument for why it was working as intended was that I never navigate from the original route because the load threw and "blocked" the target route from rendering. And therefore I'm still on the original route when the redirect is ran. We try to navigate again (to the redirect destination)

I understand his argument and why it happens now. But I don't know if it makes sense to run the beforeNavigate again.. Because the user/client has already said that it want to navigate away from the original route if that makes sense..
</details>
