### ISSUE TITLE
Cannot prerender pages with actions

### ISSUE THREAD

**Issue by LowArmour** [sveltejs/kit#7586]
### Describe the bug

I have a simple form that once it submits, the default action consoles log the data and returns {success: true}. In production, it will take the data, send an e-mail and return success: true.

According to the docs: "When not to prerender", "The basic rule is this: for a page to be prerenderable, any two users hitting it directly must get the same content from the server." and "Not all pages are suitable for prerendering. Any content that is prerendered will be seen by all users."

In my case, both requirements are true, the submitted form data does not change the content of the page.

If I create a +page.server.ts, and include the default action, then when I hit the page in dev or production, it errors out with "Cannot prerender pages with actions".

Alternatively, I can try the API route with +server.ts, but docs recommend against it, in the section "Receiving data": "In general, form actions are a better way to submit data from the browser to the server."

Something has to give, either this error is unintended behavior, or the docs have to be changed, to include the pages with actions as not prerenderable and that the API route with +server.ts can be the only way to prerender pages with form elements.

Also an explanation in the docs regarding why the pages with actions cannot be prerendered, even if they do not change the content of the page, would be ideal.

Thanks in advance.

### Reproduction

+page.svelte
```
<form
			class="contact"
			method="POST"
			autocomplete="off"
			use:enhance={({ form, data, action, cancel }) => {
				contactFormStore.validateAll()
				if ($contactFormStore.fields.some((x) => x.errors[$langStore])) cancel()
				console.log('form', form)
				console.log('data', data)
				console.log('action', action)
			}}
		>
			<TextInput label={f.name.label} name="name" placeholder={f.name.placeholder} store={contactFormStore} />
			<ActionButton type="submit">{f.submission.send}</ActionButton>
</form>
```

+page.server.ts
```
import type { Actions } from '@sveltejs/kit'

export const actions: Actions = {
	default: async ({ request }) => {
		const data = await request.formData()
		console.log(data)
		return { success: true `}`
	},
}
```

svelte.config.js
```
import adapter from '@sveltejs/adapter-node'
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess({
		scss: {
			prependData: "@import './src/styles/variables.scss';",
		},
	}),

	kit: {
		adapter: adapter({
			out: 'build',
			precompress: true,
			envPrefix: '',
		}),
		alias: {
			$components: 'src/lib/components',
			'$components/*': 'src/lib/components/*',
			$stores: 'src/lib/stores',
			'$stores/*': 'src/lib/stores/*',
			$types: 'src/lib/types',
			'$types/*': 'src/lib/types/*',
			$utils: 'src/lib/utils',
			'$utils/*': 'src/lib/utils/*',
			$icons: 'src/lib/icons',
			'$icons/*': 'src/lib/icons/*',
		},
	},
}

export default config
```

### Logs

```Shell
Cannot prerender pages with actions
Error: Cannot prerender pages with actions
    at render_page (file:///home/bt/counselor-website-2/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:88:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///home/bt/counselor-website-2/node_modules/@sveltejs/kit/src/runtime/server/index.js:235:17)
    at async respond (file:///home/bt/counselor-website-2/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:20)
    at async file:///home/bt/counselor-website-2/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:410:22
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 27.27 GB / 30.99 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.84 
    @sveltejs/adapter-node: ^1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/adapter-static: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/kit: next => 1.0.0-next.525 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.1.8
```

### Severity

annoyance

### Additional Information

I have used both adapter-static and adapter-node, same error.

**Comment by Rich-Harris** [comment]
Will add some docs but the tl;dr is that you can't `POST` data to a static file. Most webservers will respond to requests for `/YOUR_ROUTE` with the static file before even letting SvelteKit see the request, which means you need a server to handle that route.
