### ISSUE TITLE
`@sveltejs/package` `next` behind `latest`

### ISSUE THREAD

**Issue by mrienstra** [sveltejs/kit#7603]
Seems like `latest` and `next` are generally pointing to the same release in `@sveltejs` packages that haven't hit a stable v1, e.g. in [`@sveltejs/kit`](https://www.npmjs.com/package/@sveltejs/kit?activeTab=versions) & [`@sveltejs/adapter-auto`](https://www.npmjs.com/package/@sveltejs/adapter-auto?activeTab=versions), but they aren't in [`@sveltejs/package`](https://www.npmjs.com/package/@sveltejs/package?activeTab=versions). If anything, I'd expect `next` to be ahead of `latest`, but in this case it's behind:

- `next`: [1.0.0-next.1](https://www.npmjs.com/package/@sveltejs/package/v/1.0.0-next.1)
- `latest`: [1.0.0-next.5](https://www.npmjs.com/package/@sveltejs/package/v/1.0.0-next.5)

`next` also lags `latest` in these packages:
- [`@sveltejs/site-kit`](https://www.npmjs.com/package/@sveltejs/site-kit?activeTab=versions)
- [`@sveltejs/amp`](https://www.npmjs.com/package/@sveltejs/amp?activeTab=versions)

**Comment by Rich-Harris** [comment]
Not quite sure why this is. But everything new release is getting tagged with `latest`, so whether or not we're able to fix this it's probably best to just avoid `next`
