### ISSUE TITLE
failed to fetch dynamically imported module in vercel deployment

### ISSUE THREAD

**Issue by jNaimXIII** [sveltejs/kit#7605]
### Describe the bug

I'm trying to dynamically import components in my SvelteKit app. It works fine in development mode but when I deploy to Vercel, it breaks.

The paths for the loaded files is [here](https://github.com/jNaimXIII/jannatinnaim.com/blob/db46d71cbe62687668a3568ad288d1ec95a4bc67/src/lib/data/content/socials.ts#L36). I then import the data in [this component](https://github.com/jNaimXIII/jannatinnaim.com/blob/main/src/routes/_Socials.svelte) where I map over them [here](https://github.com/jNaimXIII/jannatinnaim.com/blob/db46d71cbe62687668a3568ad288d1ec95a4bc67/src/routes/_Socials.svelte#L34).

I'm not sure why this is happening but I have no issues doing this on local dev. Only in prod does it break.

### Reproduction

I don't have any particular set of steps other than the files I linked above and the methods I used there.

### Logs

```Shell
GET https://www.jannatinnaim.com/_app/immutable/components/pages/_SocialSectionGitHub.svelte net::ERR_ABORTED 404

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://www.jannatinnaim.com/_app/immutable/components/pages/_SocialSectionGitHub.svelte
```

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 128.95 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.asdf/installs/nodejs/16.17.1/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.17.1/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 107.0.5304.87
    Edge: 107.0.1418.35
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87 
    @sveltejs/kit: next => 1.0.0-next.539 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.1.0 => 3.2.2
```

### Severity

serious, but I can work around it

**Comment by benmccann** [comment]
This issue will be closed without a repository that reproduces the issue per the issue guidelines

**Comment by jNaimXIII** [comment]
Ow, it has a repository. I've linked to the files directly.

https://github.com/jNaimXIII/jannatinnaim.com

**Comment by dummdidumm** [comment]
This isn't related to `adapter-vercel`. The problem is that the request is made relative to the current file, and those files live somewhere else to each other on prod. You can observe the same behavior when running `preview` after `build` locally. Instead, you should make the dynamic import so that Vite can determine the correct path from it. In `_Social.svelte`, so this:

```js
  const getSectionComponent = () => {
    const componentPath = components.get(selectedSection);
    if (componentPath)
      return import(`./_SocialSection${selectedSection}.svelte`).then((component) => component.default);
  };
```

More info about dynamic imports in the context of Vite: https://vitejs.dev/guide/features.html#dynamic-import

**Comment by jNaimXIII** [comment]
> This isn't related to `adapter-vercel`. The problem is that the request is made relative to the current file, and those files live somewhere else to each other on prod. You can observe the same behavior when running `preview` after `build` locally. Instead, you should make the dynamic import so that Vite can determine the correct path from it. In `_Social.svelte`, do this:
> 
> ```js
>   const getSectionComponent = () => {
>       return import(`./_SocialSection${selectedSection}.svelte`).then((component) => component.default);
>   };
> ```
> 
> More info about dynamic imports in the context of Vite: https://vitejs.dev/guide/features.html#dynamic-import

@dummdidumm Thanks for the solution but, I've basically done what you're suggesting me to do here.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/115424698/201875519-a9fd55a8-9b50-46f9-9403-224d9a4eff75.png">
<img width="631" alt="image" src="https://user-images.githubusercontent.com/115424698/201875586-cc82fbb4-54cc-45d2-802d-aeb07e6915ff.png">

`components` is a map with the component name and it's "relative path" from the `_Socials.svelte` file. Your one liner and my function produce the exact same result.

Then why didn't my original implementation work?

**Comment by dummdidumm** [comment]
Because Vite needs to statically analyze the import in order to resolve the file path correctly at both dev and build time. The way you've written it is not statically analyzable by Vite, you need to have part of the string in the dynamic import.  You can read more about those gotchas in the Vite documentation I linked.

**Comment by jNaimXIII** [comment]
I see. Thanks for the help.
