### ISSUE TITLE
Not possible to use relative path on fetch

### ISSUE THREAD

**Issue by johnyvelho** [sveltejs/kit#762]
I am using Vite proxy to forward the request to the backend API. the config on svelte.config.cjs looks like:
```

...
vite: {
	ssr: {
		noExternal: Object.keys(pkg.dependencies || {})
	},
	server: {
		proxy: {
			'^/api': {
				target: `http://localhost`,
				changeOrigin: true,
				rewrite: (path) => {
					return path.replace(/^\/api/, '/api/storefront')
				}
			}
		}
	}
}
```

Using relative path on fetch, it will fail:
```
export async function load({fetch}) {
    const response = await fetch(`/api/cms?host=${page.host}`);
    .....
}
```

However, though, using the absolute path works fine.

**Severity**
annoying

**Additional context**
I know I can easily bypass this issue just using the absolute path, but it's kind of annoying and I would like to let you guys know about it. Maybe is not even possible to do it with Vite, since they use https://github.com/http-party/node-http-proxy to make the proxy

**Comment by Rich-Harris** [comment]
`server` options won't work here, because `fetch` doesn't make an HTTP request when it's for an internal endpoint, it just calls the function. And it wouldn't work in production anyway as it's a dev-server-only option. I think you'll need to find another solution.

**Comment by johnyvelho** [comment]
yeahh, I confused it with https://vitejs.dev/guide/ssr.html#setting-up-the-dev-server (which I believe is not possible to customize as nextjs yet). So I end up creating a middleware in the backend.
Thanks a lot for your time and for all the greats tools you have been creating!

Closing it
