### ISSUE TITLE
Provide comprehensive migration tool

### ISSUE THREAD

**Issue by Explosion-Scratch** [sveltejs/kit#7620]
### Describe the problem

I lot of svelte's early supporters have bailed on this project due to the new routing system and recent breaking changes. While the reasoning behind these changes has already been decided, and the changes are permanent, a comprehensive migration tool should be provided.  

### Describe the proposed solution

`npx svelte-migrate` only has the `routes` subsection, but it also does a lot more. I think that this tool should try to be as comprehensive as possible, allowing anyone using any beta version of svelte to update to the current version. Where these updates need clear human intervention, a `throw new Error("@migrate ...")` might work, but otherwise this tool should just do it. 

### Alternatives considered

Long hours of work migrating from a cool framework to a slightly less cool newer version of said framework

### Importance

i cannot use SvelteKit without it

**Comment by benmccann** [comment]
Migrating from any version would be far more difficult to implement than migrating from a single version. This would take an incredible amount of time to implement and probably have a fair number of bugs. I don't think the migration tool will change in any significant way as a result

**Comment by Explosion-Scratch** [comment]
Ah, is there already an issue about incremental adoption of new features? I'm sure that's also a frequently requested thing. Thanks for your response! 

also:
![image](https://user-images.githubusercontent.com/61319150/201454698-91b6ab8f-8984-455e-a452-b3ffb92c51f8.png)

_That took like 14 hours no joke_

**Comment by benmccann** [comment]
> Ah, is there already an issue about incremental adoption of new features?

Not sure what you mean by this, but there's a migration guide here: https://github.com/sveltejs/kit/discussions/5774

**Comment by Explosion-Scratch** [comment]
> > Ah, is there already an issue about incremental adoption of new features?
> 
> Not sure what you mean by this, but there's a migration guide here: #5774

Like options in `svelte.config.js` where you can turn on and off various new features, like:
```
{kit: {legacy: {disableNewRouting: true, disablePageActions: true, disableOtherNewFeature: true}}}
```

**Comment by benmccann** [comment]
Generally the way to do an incremental migration with Kit is just to migrate a few versions at a time instead of doing a big jump all at once. The version that introduced the routing change does take effort though
