### ISSUE TITLE
why vscode shortened div tag on save

### ISSUE THREAD

**Issue by craigcosmo** [sveltejs/kit#7632]
### Describe the bug

When I write this `<div></div>` and press save, vscode turn it to `<div/>` is there option to stop this behavior. I don't have this problem when developing react and nextjs app. This must be Svelte setting about eslint or prettier.

### Reproduction

just make a file and write  `<div></div>` then press save

### System Info

```Shell
mac os 13.0
vscode

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z (11 mos ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 22.1.0
```

### Severity

annoyance

### Additional Information

`<div></div>` is turned into this`<div/>` on save. Can we change this behavior?

**Comment by Conduitry** [comment]
You presumably have VS Code configured to automatically format on save, and you are presumably using https://github.com/sveltejs/prettier-plugin-svelte to do so. There's an option listed in that readme to control this. Please don't open GitHub issues for support requests.

**Comment by craigcosmo** [comment]
it's a bug, I don't even use prettier-plugin-svelte in my projfect. I specifically chose `no` at the projection initiation. Sveltekit still implement it behind the scene. It's a bug.

**Comment by jasonlyu123** [comment]
It's not. The Svelte for VSCode extension also uses prettier-plugin-svelte.

**Comment by craigcosmo** [comment]
ok, it's the Svelte for VSCode extension problem
