### ISSUE TITLE
adapter-cloudflare: only including `_app` content in `_routes.json`

### ISSUE THREAD

**Issue by userquin** [sveltejs/kit#7640]
### Describe the bug

The adapter should include any assets inside the `client` output folder instead `_app` only (`kit.appDir`).

Latest changes in kit allow plugins to emit/generate assets in the client folder: `@vite-pwa/sveltekit`, `sitemap`...

The problem is here: https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare/index.js#L42 (should include the client folder)

### Reproduction

~~no, sorry, just reported from Discord here: https://discord.com/channels/937808017016119440/937973377883336704/1041084393239891988~~

https://github.com/hazre/neosvr-mod-manager/tree/fix/pwa

### System Info

```Shell
NA
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The app is using the new `@vite-pwa/sveltekit` plugin to add the PWA, cloudflare returns 404 for the service worker and webmanifest assets.

**Comment by userquin** [comment]
Related kit changes:
- https://github.com/sveltejs/kit/pull/5620
- https://github.com/sveltejs/kit/pull/5601#issuecomment-1188391404

**Comment by hazre** [comment]
Here's a list of the cloudflare folder. Assets are definitely there and they work fine locally with `pnpm run preview` but when I deploy it to cloudflare pages, I get a 404s, which is weird.

https://gist.github.com/hazre/1ebf72e8f43f0252822076aa6c33b3c6

**Comment by benmccann** [comment]
@jrf0110 tagging you in case you or anyone else from Cloudflare might be interested in giving this one a look. We no longer have any Svelte maintainers employed at Cloudflare and I don't have a Cloudflare account so couldn't be very confident in any attempt I made

**Comment by tedsteen** [comment]
When deploying to Cloudflare with kit `1.0.0-next.544` I don't get any functions deployed. do I understand correctly that this issue related to that?

**Comment by jrf0110** [comment]
@benmccann I'll get some 👀 on this today! Thanks for the ping

**Comment by Rich-Harris** [comment]
@tedsteen that sounds like a separate issue

**Comment by Rich-Harris** [comment]
started looking at this, wrote up notes in https://github.com/sveltejs/kit/pull/7667

**Comment by jrf0110** [comment]
Just to clarify, the `_routes.json` file is an optimization.  Missing entries _should not_ cause any assets to 404

**Comment by userquin** [comment]
> Just to clarify, the `_routes.json` file is an optimization. Missing entries _should not_ cause any assets to 404

Yeah, sorry for that, maybe we can change the title and the content: I just check the code, I never use CloudFlare, I assume he routes files used for routing.

**Comment by userquin** [comment]
Generated `_routes.json` sent by `@hazre` after I created this issue:
```json
{
  "version": 1,
  "description": "Generated by @sveltejs/adapter-cloudflare",
  "include": [
    "/*"
  ],
  "exclude": [
    "/_app/immutable/*",
    "/favicon-16x16.png",
    "/favicon-32x32.png",
    "/favicon.ico"
  ]
}
```

**Comment by jrf0110** [comment]
Is there a bug to report here? Is the listed severity correct?

> blocking all usage of SvelteKit

**Comment by Neicul123** [comment]
Am I correct in assuming this would also fix the version.json calls from counting towards the quota on CF? Because I seem to be running into the problem where if one (or a few) users leave open their tab, it will do thousands of function requests, quickly ramping up costs.

**Comment by Rich-Harris** [comment]
Yes. Alternative this line... https://github.com/sveltejs/kit/blob/284b20bb543890e7d5a6ca99581d6eba72d9deae/packages/adapter-cloudflare/index.js#L81 ...would need to lose the `immutable` part.

@jrf0110 is there any likelihood that we could just exclude all static assets (perhaps behind an option in the adapter), without adding them individually to the `exclude` array (and exceeding the 100 limit, in many cases)?

**Comment by 0xMihir** [comment]
I'm unsure if this is related, but any generated items are not added to the manifest.

I'm running into a similar issue to the one mentioned here (https://github.com/xiphux/svimg/issues/16#issuecomment-1201612762). This package outputs transformed images to a subfolder inside the `cloudflare` directory, like so:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/93171064/203847162-cdc9506a-ee82-4983-8f74-071e703e5c2c.png">

All of the images in the generated folder return 404 when trying to access them, but the two untransformed images in the `images/` folder are accessible. 

However, none of the generated images are in the manifest, which seems to be the reason why they aren't served.
<img width="955" alt="image" src="https://user-images.githubusercontent.com/93171064/203847454-e4485d78-285d-4635-9860-617bb6640179.png">
 
If I made the build run twice, it will output these files to the manifest, which allows Cloudflare to recognize and serve the files. I feel the solution to this could be adding generated files to the manifest after running other preprocess steps.

**Comment by ajgeiss0702** [comment]
> Is there a bug to report here? Is the listed severity correct?
> 
> > blocking all usage of SvelteKit

Only a slight exaggeration. Currently, almost any request that goes through would count as a function invocation. My site is mostly static except for a few (4) endpoints that must have server-side code. According to Cloudflare analytics, my site gets 1-1.5 million (uncached) requests on an average day (and is growing). The endpoints only get ~10,000 requests per day. 

This issue is the difference between my side-project being free and it being yet another subscription I have to pay for (seemingly unnecessarily, since the sections that actually need functions take up <1% of the total requests).

Currently, I'm using svelte-multi-adapter to use both the static adapter and the nodejs adapter. I'm then deploying the static site to cloudflare pages, (for most of the content on the website) then the nodejs generated server to a vps I have to host somewhere else. Obviously, this setup is not ideal.
