### ISSUE TITLE
Adapter-node creates double slash in manifest.js file paths when building

### ISSUE THREAD

**Issue by xpertekShaun** [sveltejs/kit#7641]
### Describe the bug

https://github.com/sveltejs/kit/blob/master/packages/adapter-node/index.js#L50 sets the relative path to `'./'` which is then prepended to the list of manifest.js files

![image](https://user-images.githubusercontent.com/78720069/201675358-3d4ce04d-5223-4699-9e23-5fc7b06c4afc.png)

This leads to errors during building like the following

![image](https://user-images.githubusercontent.com/78720069/201675569-518a9461-c85d-4a19-8829-74cfa3def332.png)

I have seen weird behaviour, as building on windows appears to be ok, but linux and github CI both crash 

### Reproduction

1. `npm create svelte@latest my-app`
2. choose all defaults
3. `cd my-app`
4. `npm i -D @sveltejs/adapter-node`
5. `npm install`
6. Then change svelte.config.js from `adapter-auto` to `adapter-node`
7. `npm run build`
8. inspect `.svelte-kit/adapter-node/manifest.js`

### Logs

```Shell
> Using @sveltejs/adapter-node
error during build:
Error: Could not resolve './/entries/matchers/Actor.js' from .svelte-kit/adapter-node/manifest.js
    at error (file:///SolutionFolder/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///SolutionFolder/node_modules/rollup/dist/es/shared/rollup.js:22156:24)
    at ModuleLoader.resolveDynamicImport (file:///SolutionFolder/node_modules/rollup/dist/es/shared/rollup.js:22210:120)
    at async file:///SolutionFolder/node_modules/rollup/dist/es/shared/rollup.js:22105:32
The command '/bin/sh -c npm run build' returned a non-zero code: 1

Error: Process completed with exit code 1.
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 5600U with Radeon Graphics
    Memory: 3.14 GB / 15.31 GB
  Binaries:
    Node: 16.15.1 - ~\.nvm\versions\node\v16.15.1\bin\node.EXE
    npm: 8.11.0 - ~\.nvm\versions\node\v16.15.1\bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87
    @sveltejs/adapter-node: ^1.0.0-next.100 => 1.0.0-next.100
    @sveltejs/kit: next => 1.0.0-next.544
    svelte: ^3.46.0 => 3.53.1
    vite: ^3.1.0 => 3.2.3
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
Here's the file to update:

https://github.com/sveltejs/kit/blob/e617b75fe72684d9d42626b0deda4e9e35023e17/packages/kit/src/core/generate_manifest/index.js
