### ISSUE TITLE
Outdated error on having defined `config.kit.router`?

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/kit#7645]
### Describe the bug

I had not updated SvelteKit for a project in a very long time and on start it gave me this error after the update:

> error when starting dev server:  
> Error: config.kit.router has been moved to config.kit.browser.router

This looks outdated, as I could no longer find a reference to `config.kit.browser`, at the very least it is not defined [in the types](https://kit.svelte.dev/docs/types#sveltejs-kit-kitconfig).

### Reproduction

- Create new skeleton SvelteKit project via `npm init`
- Change config to:
  ```js
  const config = {
	  preprocess: preprocess(),
	  kit: {
		  adapter: adapter(),
		  router: false,
	  }
  };
  ```
- Try `vite build`

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 8.06 GB / 31.92 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.87
    @sveltejs/kit: next => 1.0.0-next.545
    svelte: ^3.44.0 => 3.53.1
    vite: ^3.1.0 => 3.2.3
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
The code for this is inside `options.js`, the easiest solution is to replace the error with the one that is thrown for the new path.
