### ISSUE TITLE
Router picks up .d.ts files

### ISSUE THREAD

**Issue by knpwrs** [sveltejs/kit#7662]
### Describe the bug

When using tooling such as graphql-code-generator 

### Reproduction

Create a file anywhere under `routes` called `+layout.server.d.ts`.

### System Info

```Shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 171.77 MB / 32.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 18.10.0 - /nix/store/m3za3mblwg9az7vpkkvlfm04z66mcr6y-nodejs-18.10.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /nix/store/m3za3mblwg9az7vpkkvlfm04z66mcr6y-nodejs-18.10.0/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 106.1.44.101
    Chrome: 107.0.5304.110
    Chrome Canary: 99.0.4828.0
    Firefox: 106.0.5
    Safari: 15.2
```

### Severity

annoyance

### Additional Information

I can think of four solutions:

1. The router should ignore `.d.ts` files by default. As long as TypeScript is considered a first-class citizen in SvelteKit this doesn't seem like an unreasonable solution to me.
  a. Another consideration: only allow specific extensions to be picked up by the router, maybe configured some way in Vite.
3. Configurable ignore for the router. This is more complex, but opens up end users to be able to exclude any generated files of various extensions.
4. Don't generate files with `+` at the start of their name. Unfortunately, I couldn't find a way to configure graphql code generator to do this, but I could either place all generated code in its own `.d.ts` file outside of `routes`, or, as suggested on Discord, I can place all queries in `queries.ts` files which would result in files such as `__generated__/queries.d.ts`, which should not be picked up by the router.

I'd be willing to put up a PR for the first solution if the SvelteKit team would be open to that solution.

**Comment by dummdidumm** [comment]
What's the use case for this? You mention something about a graphql code generator - could you expand on that?

**Comment by knpwrs** [comment]
[GraphQL Code Generator](https://the-guild.dev/graphql/codegen) is a tool which can generate code for various usecases in GraphQL projects. In my case, given the following query in `+layout.server.ts`:

```graphql
me {
  id
  username
  email
}
```

It will generate the following in `+layout.server.d.ts`:

```ts
export type MeQuery = {
  __typename?: 'Query',
  me?: {
    __typename?: 'AppUser',
    id: string
  } | null
};
```

This type can be imported into the original `+layout.server.ts` file and used to type the response that comes back from a GraphQL request. Notice that it properly handles nulls and nesting and whatnot so you get full type safety.

There are other tools that generate `.d.ts` files as well. One I've used before (which admittedly doesn't apply to Svelte as far as I'm aware) is https://github.com/skovy/typed-scss-modules, which generates `.d.ts` files to allow you to safely import CSS modules.

I have not personally used any other tools but I know there are other tools that exist that generate various `.d.ts` files for type-safely importing things that the TypeScript compiler doesn't understand on its own.

`.d.ts` files can only contain type exports, not executable code, so thinking about my first proposed solution, if TypeScript is a first-class citizen of SvelteKit then I think it makes sense to just ignore them.
