### ISSUE TITLE
`<form on:submit|preventDefault={...}>` does not call `event.preventDefault()`

### ISSUE THREAD

**Issue by c-bandy** [sveltejs/kit#767]
**Describe the bug**
The `preventDefault` event modifier seems to be broken in `svelte-kit`, at least when used on a `<form>` with `on:submit`.

**To Reproduce**
```svelte
<form on:submit|preventDefault={(event) => {
  console.log("Default was prevented: ", event.defaultPrevented)}
}>
  <button type="submit">Submit</button>
</form>
```

Press the submit button. The page should reload (default behavior of form submit), thus demonstrating that default was not correctly prevented.

**Expected behavior**
`event.preventDefault()` gets called as defined in the Svelte API reference.

**Information about your SvelteKit Installation:**

```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 2.35 GB / 32.00 GB
    Shell: 3.2.1 - /usr/local/bin/fish
Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
Browsers:
    Chrome: 89.0.4389.90
    Firefox Developer Edition: 88.0
    Safari: 14.0.3
npmPackages:
    @sveltejs/kit: next => 1.0.0-next.64
    svelte: ^3.24.1 => 3.35.0
```

- Using `@sveltejs/adapter-vercel`
- Firefox browser

**Severity**
Admittedly not that big of a problem since you can manually call `event.preventDefault()` in your handler as a workaround, but its confusing as you don't quite understand what's going on at first when your browser is refreshing the window on submit.

**Comment by Rich-Harris** [comment]
Does the text get logged? It sounds more like the client-side JS isn't running at all. I can't think of any other scenario in which an event modifier would fail to work

**Comment by c-bandy** [comment]
Looks like there was something vite that caused the whole js execution to crash. The error wasn't exactly what it seemed like. When I solved that issue this also went away.
