### ISSUE TITLE
Do we need a per-platform `atob` implementation?

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#7698]
### Describe the problem

Node's is deprecated and the other platforms don't support `Buffer`, so there's not a cross-platform way of doing this which makes me wonder if we need it to be implemented in the adapters?

### Describe the proposed solution

Maybe we could use `atob` by default, but let adapters provide an override so we only need to update `adapter-node`?

https://github.com/sveltejs/realworld/commit/e35cef936e66de3cc6b7043e0ae3506e5d49448e#commitcomment-88922201

### Importance

nice to have

**Comment by Conduitry** [comment]
Is it deprecated? The Node docs say that it's _legacy_, which doesn't sound like the same thing.

> Although this feature is unlikely to be removed and is still covered by semantic versioning guarantees, it is no longer actively maintained, and other alternatives are available.

I'd tend to not worry about this until the docs say it's deprecated (if that ever happens) or until it starts emitting warnings on use.

**Comment by Conduitry** [comment]
https://nodejs.org/dist/latest/docs/api/globals.html#atobdata It has "stability 3 legacy", not "stability 0 deprecated".

**Comment by benmccann** [comment]
ah, I didn't realize those are different. ignoring for now sounds good
