### ISSUE TITLE
Google tries to index hydrate.route data

### ISSUE THREAD

**Issue by Ohyenno** [sveltejs/kit#7714]
### Describe the bug

See what problem I found. While I read the google search console logs, I saw a very large number of 404 errors (several thousand) that blocked the operation of the crawler.

Problem number one. There are a small number of them, but still. The Google crawler is trying to read data from the script tag. And in all the ways that are used on the site - trying to index them. Block such pages individually in robots.txt is not a good idea.

For example (it from https://kit.svelte.dev/docs/introduction):
```
<script type="module" data-sveltekit-hydrate="1mqkmp1">
hydrate: {
route: {"id":"/docs/[slug]"},
});
</script>
```

It will create task to read path https://yourdomain.com/docs/[slug] and get 404 error

The second problem. And it's like a very big one. I collect a bunch of data in the api, which come as parameters. For optimization, these come not by links, but by parameters that are already collected by links in the project. The parameters may, for one reason or another, contain / at the beginning. Google automatically catches it and tries to find such pages.
{
"domain": "https://someexternaldomain.com",
"image": "/images/one.png",
"item_url": "/catalog1/item1",
}

In SSR html it looks like:

```<script type="application/json" data-sveltekit-fetched data-url="https://some/api/path">{"status":200,"headers":{},"body":"{\"id\":1,\"domain\":\"https://someexternaldomain.com\",\"image\":\"/images/one.png\".... ```

Questions about the case
1. Is it possible to remove json pure json from js?
2. Is it possible to encode this data in some way so that search engines do not read it? 
3. What can be the solution to the problem? It is clear that slashes can be replaced with other characters in the api, but this in any case will not solve the problem with displaying paths in the index.

### Reproduction

You could look at your google search console, then 404 error list

### System Info

```Shell
lastest
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is... very weird behaviour on Google's part. I've never heard of it doing something like that. Regardless, does it cause any issues beyond cluttering the search console?

**Comment by benmccann** [comment]
We just setup Search Console on svelte.dev and subdomains. I'm not seeing any issues like this anywhere. Perhaps you accidentally are creating links to these pages? I'm not sure what to do about this, but am tempted to close the issue without a way to reproduce this
