### ISSUE TITLE
Prerendered pages with trailing slash 404 when directly loaded

### ISSUE THREAD

**Issue by drzax** [sveltejs/kit#7725]
### Describe the bug

This only appears to happen when deployed (I've tested Vercel, but not other deployment options) and works as expected with a local `npm run build && npm run preview`.

With `export const prerender = true;` in `src/routes/+layout.ts` and `trailingSlash: "always"` in the config, rendered pages 404 when directly loaded.

The page loads as expected when navigating from another page (i.e. client-side navigation), but when loaded directly (or when the link is clicked before code implementing client-side navigation is loaded), the URL returns a 404. This isn't a problem with `trailingSlash: "never"`.

### `trailingSlash: "always"`
- [Demo](https://repro-prerender-404-k64onxso1-drzax.vercel.app/)
- [Code](https://github.com/drzax/repro-prerender-404)

There's a PR in that repo where the only change is to set `trailingSlash: "never"`:
- [Demo](https://repro-prerender-404-6hgfib8uc-drzax.vercel.app/)
- [Code](https://github.com/drzax/repro-prerender-404/pull/1/files)

This doesn't appear to affect the root path (presumably because it always has a trailing slash), but all other paths appear to be affected. 

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 51.70 MB / 32.00 GB
    Shell: 5.1.8 - /usr/local/bin/bash
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.10
    Edge: 107.0.1418.52
    Firefox: 106.0.5
    Firefox Developer Edition: 107.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.88
    @sveltejs/adapter-vercel: ^1.0.0-next.81 => 1.0.0-next.81
    @sveltejs/kit: next => 1.0.0-next.551
    svelte: ^3.44.0 => 3.53.1
    vite: ^3.1.0 => 3.2.4
```

### Severity

serious, but I can work around it

### Additional Information

In my use case I can set trailingSlash to 'never', but can easily imagine a scenario where that might not be possible or desirable. 

Vercel build output where trailing slash is 'always'
<img width="647" alt="image" src="https://user-images.githubusercontent.com/596563/202841798-0c897766-4e9a-44c6-950d-7d2227b4adb1.png">

Vercel build output where trailing slash is 'never'
<img width="647" alt="image" src="https://user-images.githubusercontent.com/596563/202841765-05f80e2f-b363-4c14-a607-8929eb9e74f2.png">

This may be related to (or even the same bug as) #6236, but I couldn't tell for sure so thought I'd submit this anyway — apologies if it's a duplicate.

**Comment by Rich-Harris** [comment]
This may be fixed by https://github.com/sveltejs/kit/pull/7719, which removes redirect handling from the Vercel routes config and delegates to SvelteKit itself
