### ISSUE TITLE
Alias documentation

### ISSUE THREAD

**Issue by Randagio13** [sveltejs/kit#7732]
### Describe the bug

Coming from the kit docs, I thought I could use `svelte.config.ts` as the configuration. If I do, that alias doesn't work.

Let's add an annotation for that to avoid any misunderstanding.

### Reproduction

Changing `svelte.config.js` to `svelte.config.ts` with an alias configuration

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Memory: 163.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Edge: 107.0.1418.52
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.88 
    @sveltejs/kit: next => 1.0.0-next.551 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I don't think there's anything particularly about aliases that's relevant here. There's #2576 for supporting `svelte.config.ts`. There shouldn't be anything in the docs that points towards this already being supported.

**Comment by Randagio13** [comment]
Thanks @Conduitry

**Comment by MentalGear** [comment]
Also ran into this and took a lot of debugging to find out it was the culprit since errors were only displaying that the <style> tag in .svelte files were not correct.
