### ISSUE TITLE
Add config option to make all links relative to `base`

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#7733]
### Describe the problem

I have several static sites I'd like to publish GitHub pages (prev. on Netlify). 2 examples

- https://janosh.github.io/svelte-multiselect
- https://janosh.github.io/svelte-toc

Internal links like `/` or `/foo` on all those sites go to non-existant `https://janosh.github.io` instead of `https://janosh.github.io/{repo-name}`

### Describe the proposed solution

[Docs](https://kit.svelte.dev/docs/configuration#paths) state `base` currently needs to be manually added to all internal links:

> You can use [base from $app/paths](https://kit.svelte.dev/docs/modules#$app-paths-base) for that: `<a href="{base}/your-page">Link</a>.`

Would be very convenient if there was a setting, say `autoPrefixBase` to make all internal links relative to `base` to avoid having to refactor internal links across half a dozen sites.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
URLs appear in many contexts — `href` attributes, `src` attributes, `fetch(...)` calls, `goto(...)` calls... the list is endless. Even if we could catalog all the places where we might expect a base to be automatically prefixed, in only some of those cases would it even be possible. The distinction between places where it happens and places where it doesn't would, from the app author's perspective, be arbitrary. And then you have to consider the places where you _don't_ want URLs to be prefixed.

You could try using a `<base>` element (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base), but as an addition to SvelteKit itself I'm afraid it's a non-starter.

**Comment by janosh** [comment]
Great suggestion! Should have remembered `<base>` myself!

What worked for me in https://github.com/janosh/svelte-multiselect/pull/172 is adding `<base>` to `+layout.svelte` conditional on running in CI so local `dev` and builds remain unaffected (`import.meta.env.CI` is set by most CI providers):


```svelte
<script>
  // +layout.svelte
  import { name } from '../../package.json'
</script>

<svelte:head>
  <base href={import.meta.env.CI ? `/${name}/` : ``} />
</svelte:head>
```

where name is the repo name in `https://github.com/{user}/{repo_name}`. Note the slash before _and_ after `/${name}/`.

I then had to remove all leading slashes from `href`, `src` (incl. stuff like `<link rel="icon" href="favicon.svg" />` in `app.html`) and turn links to the landing page from `href="/"` to `href="."` since the `<base>` href will only be prefixed if the link is relative (i.e. no leading slash). Not sure if `href="."` is the most semantic solution here?

Not sure how discoverable this is. Given GitHub pages popularity, we should maybe add a paragraph to the static adapter docs showing how to deploy there.
