### ISSUE TITLE
RequestHandler Input Body Type for application/json requests - Typescript

### ISSUE THREAD

**Issue by DhyeyMoliya** [sveltejs/kit#775]
**Describe the bug**
In Endpoints RequestHandler type has body prop as `string | Buffer | ReadOnlyFormData` but in case of `application/json` reqests, these types give TypeError if we try to access `body._____` props.

**Logs**
<img width="1054" alt="Screenshot 2021-03-30 at 5 51 45 PM" src="https://user-images.githubusercontent.com/6321840/112987690-a1b88d00-9180-11eb-8442-782f96918fc2.png">

**To Reproduce**
```
In a typescript enabled kit project, Create a `post` Endpoint and try to access `body.email` prop.
```

**Expected behavior**
It should allow to access json props directly from the `body` object as `body._____`.

**Stacktraces**
None

**Information about your SvelteKit Installation:**
- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 73.41 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 89.0.4389.90
    Edge: 89.0.774.54
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.64 
    svelte: ^3.36.0 => 3.36.0 
```
- Your browser
```
Microsoft Edge
```

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
```
Node
```

**Severity**
`Many of the times, APIs are using "Content-Type : application/json" for requests. I use it in my 90% APIs.`. 

**Additional context**
None

**Comment by dummdidumm** [comment]
I don't think we can infer this, so this sounds like an optional generic type to pass so that `body` is properly specified, like `RequestHandler<Context = any, BodyType extends string | Buffer | ReadOnlyFormData = string | Buffer | ReadOnlyFormData>`
