### ISSUE TITLE
Broken LayoutParentData types in +page.ts

### ISSUE THREAD

**Issue by iOiurson** [sveltejs/kit#7757]
### Describe the bug

With nested routes `/a/b/c` and their respective `+layout.ts`, each`+page.ts` is not able to understand correctly the types of the `await parent()`.

The types of the returned data from the immediate `load` parent of `+page.ts` are ignored.

Ex:
- `/a/+page.ts` can't see types from `/a/+layout.ts`
- `/a/b/+page.ts` can't see types from `/a/b/+layout.ts`
- `/a/b/c/+page.ts` can't see types from `/a/b/c/+layout.ts`

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-pn8meq?file=src%2Froutes%2Fa%2Fb%2Fc%2F%2Bpage.ts

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.89 
    @sveltejs/kit: ^1.0.0-next.556 => 1.0.0-next.556 
    svelte: ^3.46.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.4
```

### Severity

annoyance

**Comment by s3812497** [comment]
It works if you change the type of the load function for `+page.ts` from `LayoutLoad` to `PageLoad`.
```diff
// src/routes/a/b/c/+page.ts
- import type { LayoutLoad } from './$types';
+ import type { PageLoad } from './$types';

- export const load: LayoutLoad = async ({ parent }) => {
+ export const load: PageLoad = async ({ parent }) => {
	const { a, b, c } = await parent();

	console.log('in /a/b/c +page.ts: a', a, 'b', b, 'c', c);

	return {
		someOtherData: 3
	};
};
```

**Comment by iOiurson** [comment]
Oh right, i had missed that. Thanks !
