### ISSUE TITLE
ssr : false - Should dev server not try to server render

### ISSUE THREAD

**Issue by printfhere** [sveltejs/kit#776]
Hi,

I tested the new spa mode with ssr : false and it seems that the dev server still try to evaluate my components on the server (can't import/use libraries which manipulate the DOM outside of onMount).

I can't build the app aswell.

Is it expected ? Even with ssr : false, do I need to code the app as isomorphic ?

In addition, I don't understand well when to add my depencies as dev or prod, if you could explain to me why for example when using Quill it works as dev dep but not as prod dep ?

Thanks for your time and your work on SvelteKit, it is great <3

**Comment by printfhere** [comment]
Sorry I didn't see the advertisement about seeking help here, I am closing the issue.

**Comment by benmccann** [comment]
well if `ssr: false` and it's rendering on the server that sounds like a bug

the devDep vs regular dep is a Vite thing https://github.com/sveltejs/kit/issues/655#issuecomment-809714987

**Comment by bleca** [comment]
@benmccann Thanks for your help ! I may recreate the issue then
