### ISSUE TITLE
$lib is no longer built in or docs are wrong

### ISSUE THREAD

**Issue by niktek** [sveltejs/kit#7774]
### Describe the bug

The docs say https://kit.svelte.dev/docs/configuration#alias that $lib is built in - it no longer is. 
It says that it will generate it in (t/j)sconfig.json on npm run dev - it does not (not even in the included .svelte-kit generated files).
It will work if i manually create $lib in svelte.config.js in kit.alias and THEN it will generate it in .svelte-kit/tsconfig.json.
I just can't find the GH issue that discusses this change to know whether this is the new expected behaviour or not.

Either way, $lib needs to be back in there by default or the docs page needs to be changed to describe adding $lib to aliases and that it is not enabled by default.

### Reproduction

`pnpm create svelte mytest`
`cd mytest`
`ppm I`
`pnpm dev`

Observe no creation of compilerOptions.paths.$lib in .svelte-kit/tsconfig.json 

Add $lib in manually
```
kit: {
  adapter: adapter(),
  alias: {
    '$lib': 'src/lib/*',
  }
}
```
Observe correct compilerOptions.paths.$lib being generated in .svelte-kit/tsconfig.json

This is true for both Typescript and Javascript with JSDoc comments projects.

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 68.58 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Chrome: 107.0.5304.110
    Firefox Developer Edition: 108.0
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.89
    @sveltejs/kit: next => 1.0.0-next.557
    svelte: ^3.44.0 => 3.53.1
    vite: ^3.1.0 => 3.2.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Which option do you choose when running `create svelte`?

**Comment by niktek** [comment]
```
✔ Which Svelte app template? › Skeleton project
✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Add Playwright for browser testing? … No / Yes
```

And also Javascript with JSDocs
