### ISSUE TITLE
Cache headers in server load function seem to be ignored again

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#7778]
### Describe the bug

This issue

https://github.com/sveltejs/kit/issues/6477#issuecomment-1256601175 

described a bug with server load functions not being appropriately cacheable. Rich closed it as fixed, describing behavior I'm exactly looking for: that cache headers sent down would control ttl for that url alone, and would be overridable with SvelteKit's standard invalidate functions.

Unfortunately I'm having trouble getting this to work. 

My +page.server.ts looks like this

```ts
let i = 0;

import type { PageServerLoad } from './$types';

// @ts-ignore
export async function load(params) {
	console.log('LOADING');

	// const val = params.url.searchParams.get('val');
	const val = params.url.search;

	const result = {
		searchProps: 'Value ' + val + ' ' + i++
	};

	params.setHeaders({
		'cache-control': 'max-age: 20000'
	});

	return result;
}
```

and then I navigate to different querystrings for that page with 

```html
<a href="/?val=1">1</a>
<a href="/?val=2">2</a>
<a href="/?val=3">3</a>
```

### Reproduction

The minimal repro is here: https://github.com/arackaf/booklist/tree/special/bug-repro/svelte-kit 

the directory above that has a huge project around it, but that directory I've linked to contains a minimal SvelteKit app that reproduces this (ostensible) bug. 

It's currently deployed here: https://booklist-svelte-kit.vercel.app/

As you navigate, you'll see fresh calls to fetch __data.json, even though it should be cached 

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 149.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 8.18.0 - ~/Documents/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 107.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.89 
    @sveltejs/kit: next => 1.0.0-next.557 
    svelte: ^3.44.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.4
```

### Severity

blocking all usage of SvelteKit

**Comment by dummdidumm** [comment]
You cache header is wrong. It should be `max-age=20000` instead of `max-age: 20000` (note the `=` instead of the `:`). If I change that, it works for me.

**Comment by arackaf** [comment]
@dummdidumm - sorry, I did try it with the more standard `=`, and it also did not work. I've updated my repo, and deployment with that syntax, but the results (for me) are the same.

**Comment by dummdidumm** [comment]
I don't see fresh calls to `__data.json`, in the chrome network tab they appear but it says "disk cache" in the size tab, which indicates to me the cache is working.

**Comment by arackaf** [comment]
@dummdidumm hmm - I did also (previously) add some local state to each call’s result to make it clear whether the loader was being called, as well as adding console.logs.

Let me get back to a keyboard and see if I can re-update that here.

**Comment by Rich-Harris** [comment]
I haven't dug into the repro yet but I did grep for `no-store` and realised we still have this when we generate `__data.json` files: https://github.com/sveltejs/kit/blob/53e034b2ee49866c6f19ec8707c3837fbe08cd7a/packages/kit/src/runtime/server/data/index.js#L133-L145

IIRC we initially added that so that if you were navigating from `/x/y/z` to `/a/b/c` you'd get all the data, instead of a cached partial response that was generated for a navigation from `/a/b/d` to `/a/b/c`, but that we'd replaced it with a `Vary` request header that allowed cache headers to be respected

**Comment by Rich-Harris** [comment]
Also, for non-prerendered pages we could be using the `ttl` trick to fake-cache the initial data payload, as described in https://github.com/sveltejs/kit/issues/3803#issuecomment-1310947888

**Comment by arackaf** [comment]
@dummdidumm @Rich-Harris 

Gentlemen please accept my sincere apologies. I’m mortified to admit this, but the problem was that I had my dev tools open, with the “prevent caching” box ticked.

My repro already has that local state in the response (the trailing number you see displayed). And it works perfectly.

Years of SPA development have ruined my already minimal brain

**Comment by Rich-Harris** [comment]
lmao

**Comment by Rich-Harris** [comment]
> don't we already have fake-cache for the initial data payload for shared `load` functions?

For anything loaded with `event.fetch` yes, we slap a `data-ttl` on the inline script that contains the body and reuse it for as long as the data is fresh. But not for server data. In theory we could extract a `ttl` value and reuse that data for any requests for `/a/b/c/__data.json` until it expired (in some cases it'll contain data that hasn't been invalidated but that's totally harmless). We can only do that for non-prerendered pages, of course
