### ISSUE TITLE
Inability to send multiple cookies in a single endpoint

### ISSUE THREAD

**Issue by BiscuiTech** [sveltejs/kit#778]
**Describe the bug**
Because the return statement from endpoints is in JSON, multiple set-cookie is not permissible. 

**To Reproduce**
return multiple 'Set-Cookie', like so 
```
return {
      status: 200,
      headers: {
        'Set-Cookie': supaToken,
        'Set-Cookie': supaRefresh,
        'Set-Cookie': supaRemember,
      },
      body: { success: true },
    }
```

To help us help you, if you've found a bug please consider the following:
https://github.com/BiscuiTech/finance-dashboard

**Expected behavior**
I understand this is a limitation of JSON and not Svelte per-say, but setting multiple cookies should definitely be in its capacity. 

**Information about your SvelteKit Installation:**

System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 3.22 GB / 7.74 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 7.5.4 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.61
    svelte: ^3.36.0 => 3.36.0

- Your browser
Edge Chromium

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Node

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?
Blocking upgrade

**Comment by Conduitry** [comment]
I think you should be able to specify `'Set-Cookie': [supaToken, supaRefresh, supaRemember]`

**Comment by BiscuiTech** [comment]
I can't believe I tried every other trick (string templating, JSON parsing, concatenation) but didn't think to try making an array.

Anyway, of course this works. Thanks!
