### ISSUE TITLE
Documentation on how to debug frontend and backend code with source maps 

### ISSUE THREAD

**Issue by TimoWilhelm** [sveltejs/kit#7781]
### Describe the problem

I'm trying to setup a full stack debugging environment for SvelteKit.

I'm using the following `launch.json`  and I'm starting the server with `NODE_OPTIONS='--inspect' vite dev` but I'm unable to hit any breakpoints.

<details>
<summary>See Code</summary>

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "chrome",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:3000",
      "sourceMaps": true,
      "webRoot": "${workspaceFolder}/src",
    },
    {
      "name": "node:attach",
      "type": "node",
      "request": "attach",
      "sourceMaps": true,
      "skipFiles": [
        "<node_internals>/**"
      ],
    },
  ]
}
```

</details>

If I manually insert some `debugger` statements, I end up in the generated chunk js and the source maps do not seem to apply properly

There also seem to be many different options to enable source map generation.  I'm having a hard time understanding which option will affect what files.

`svelte.config.js`
```js
/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: sveltePreprocess({
    sourceMap: true,
    ...
  }),
  compilerOptions: {
    enableSourcemap: true,
  },

  kit: {
    ...
  },
};
```

`vite.config.ts`
```ts
const config: UserConfig = {
  plugins: [...],
  build: {
    sourcemap: true,
  },
};
```

`tsconfig.json`
```json
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "sourceMap": true,
  }
}

```

### Describe the proposed solution

Something like https://nextjs.org/docs/advanced-features/debugging that explains how you can debug your SvelteKit frontend and backend code with full source maps support using either the [VS Code debugger](https://code.visualstudio.com/docs/editor/debugging) or [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools).

### Alternatives considered

I've found a few different sources for how to set up debugging:

- https://stackoverflow.com/questions/67276886/how-to-get-sourcemaps-working-with-svelte-preprocess-typescript-sourced-ts-fi
- https://github.com/sveltejs/kit/discussions/6374
- https://github.com/vitejs/vite/issues/3288 (Is this issue blocking SSR debugging?) 
- https://github.com/sveltejs/kit/issues/1144

### Importance

would make my life easier

**Comment by jayfresh** [comment]
Agree this would be a big plus. Looks like the vite change that was supposed to unblock #1144 hasn't gone through - https://github.com/vitejs/vite/pull/3928

**Comment by gigitalz** [comment]
Upvoting this, truly essential.

**Comment by jerriclynsjohn** [comment]
Oh yes this is a big need for SvelteKit

**Comment by Leftium** [comment]
Someone [posted this workaround on Reddit](https://www.reddit.com/r/sveltejs/comments/11hsz5o/enable_vs_code_breakpointsdebugging_for_sveltekit/?utm_source=share&utm_medium=web2x&context=3) (but I haven't been able to get it to work. Maybe a Windows+git bash issue?).

**Comment by theetrain** [comment]
This is currently possible in VSCode with the following `.vscode/launch.json` config:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch server",
			"request": "launch",
			"runtimeArgs": ["dev"],
			"runtimeExecutable": "pnpm",
			"skipFiles": ["<node_internals>/**"],
			"type": "node",
			"console": "integratedTerminal"
		},

		{
			"type": "chrome",
			"request": "launch",
			"name": "Launch browser",
			"url": "http://127.0.0.1:5173",
			"webRoot": "${workspaceFolder}"
		}
	],
	"compounds": [
		{
			"name": "Both",
			"configurations": ["Launch server", "Launch browser"]
		}
	]
}
```

Replace `runtimeArgs` and `runtimeExecutable` with your respective dev script and package manager.

Running 'Both' will open Chrome and run your Node.js/Vite server in debug mode, allowing you to add breakpoints for all client and server code, including JS code within `<script>` in `.svelte` files. It's important to use the provided browser that launches with Vite sine it attaches source maps and your Node.js server. And here's my video walkthrough: https://youtu.be/OG70PKD0hEU?t=211

**Comment by ranjan-purbey** [comment]
@theetrain  that only works for client-side debugging, but not for server-side code, for example inside a `+page.server.ts` file

**Comment by ftognetto** [comment]
It works on server side if you put `debugger;`
on the contrary, with vavite-loader breakpoints work on the server but on the client you have to use debuggers;

😭😭😭

**Comment by hugotox** [comment]
Not sure if this is still relevant, but on VSCode you can debug server side code with the built-in JS Debug Terminal, no config needed. Just run your dev command from that terminal and it just works:
<img width="442" alt="Screenshot 2024-04-30 at 10 06 56 PM" src="https://github.com/sveltejs/kit/assets/1758062/ada3c1e5-8cbf-4b7c-b20d-c41ed6c73695">
<img width="771" alt="Screenshot 2024-04-30 at 10 07 57 PM" src="https://github.com/sveltejs/kit/assets/1758062/5a9e4e25-a110-41a3-a823-8b33f4a9a46d">
