### ISSUE TITLE
Layout to route

### ISSUE THREAD

**Issue by ugurkorkmaz** [sveltejs/kit#7789]
### Describe the problem

![image](https://user-images.githubusercontent.com/40540244/203652253-282f6295-0068-418d-990d-8367f0395240.png)
Let's imagine that we have a route structure like this. Normally, Sveltekit gives an error and shuts itself down. This is a normal situation. 
We solve the problem by adding a new folder, as shown below. But folder hell; not a big problem; but it doesn't feel right to me.
![image](https://user-images.githubusercontent.com/40540244/203653270-c710f764-30e8-4b2b-8ee9-4f6bbe8b03c8.png)

### Describe the proposed solution

It would be nice to include an identifier for the parenthesis, such as (.dash), so that sveltekit understands it is also a route. 
![image](https://user-images.githubusercontent.com/40540244/203653848-d43c46ca-8999-4858-a133-4ef41b3a3cf5.png)
And now the route :)

### Alternatives considered

![image](https://user-images.githubusercontent.com/40540244/203654250-58be6178-149d-4d53-af03-b30b364bfd46.png)
It can be like this; actually, the identifier is not very important.)

### Importance

would make my life easier

**Comment by Conduitry** [comment]
You can already use `@foo` to break out to a real route - it doesn't have to be to a `()` folder. https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-breaking-out-of-layouts Is this what you're asking about?

**Comment by ugurkorkmaz** [comment]
Thanks @Conduitry , this is not exactly the solution I was looking for or I did not understand the example and explanation in the document.
I want (group) to be a route at the same time. I use different layouts and routes for Dashboard, Homepage or Auth. Creating a folder again doesn't feel right to me. It is a bit strange to navigate between folders, I know the problem I mentioned is a bit ridiculous, but maybe such a feature can be added in the future. Thanks for the svelte <3

**Comment by dummdidumm** [comment]
If you want a group to be a route at the same time, then don't use a group, just use a route. There's no value in having groups for this case. A group is useful for grouping more than one route.

**Comment by ugurkorkmaz** [comment]
I should do as you suggest. Thank you @dummdidumm
