### ISSUE TITLE
ssr : false - server still tries to render components

### ISSUE THREAD

**Issue by printfhere** [sveltejs/kit#779]
**Describe the bug**
I can't use libraries like Quill which manipulates the DOM outside of onMount function when ssr : false

**Logs**
18:53:37 [vite] Error when evaluating SSR module C:\Users\Bastien\Desktop\svelte-spa\src\routes\index.svelte:
ReferenceError: document is not defined
    at Object.<anonymous> (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:7661:12)
    at __webpack_require__ (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:36:30)
    at Object.<anonymous> (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:1030:1)
    at __webpack_require__ (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:36:30)
    at Object.<anonymous> (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:5655:14)
    at __webpack_require__ (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:36:30)
    at Object.<anonymous> (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:10045:13)
    at __webpack_require__ (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:36:30)
    at Object.<anonymous> (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:11557:18)
    at __webpack_require__ (C:\Users\Bastien\Desktop\svelte-spa\node_modules\quill\dist\quill.js:36:30)

**To Reproduce**
- Fresh install of sveltekit.
- ssr : false in config
- npm install Quill for exemple
- import Quill as top level of component
- npm run dev -> broken
- npm run build -> broken

**Expected behavior**
I understood I would not need to code my app as isomorphic when using ssr : false

**Information about your SvelteKit Installation:**

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit --binaries --browsers`
 System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 2.36 GB / 7.73 GB
  Binaries:
    Node: 14.4.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 6.14.5 - ~\scoop\apps\nodejs\current\npm.CMD
  Browsers:
    Chrome: 89.0.4389.90
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.64
    svelte: ^3.29.0 => 3.36.0
- Your browser
Brave
- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
tested on node and static , both not working

**Severity**
I still can use classic onMount and if browser conditions.

**Comment by Rich-Harris** [comment]
SvelteKit needs to import the page to determine whether or not it should be server-rendered. (I'd like to add a build step that figures that out earlier on, so that the component doesn't need to be imported at runtime if it's not being SSR'd, but it won't solve the problem.)

For that reason, you have two options:

1. Raise this as a bug with Quill, because it _is_ a bug — it should be possible to import a DOM-centric library in a non-DOM environment, even if it doesn't _do_ anything
2. use `await import('quill')` in `onMount`

**Comment by benmccann** [comment]
SvelteKit has both app-wide configuration and page-level configuration for SSR. I wonder if there's a way we can avoid importing the page is the app-level config option is set?

**Comment by printfhere** [comment]
Hey thanks for your answers ! 

If I understand correctly, the issue comes from librairies that manipulates the DOM as soon as imported. 

In that case I should import these kind of dependencies in onMount to prevent sveltekit from evaluating them in a non DOM env.

I'll try to raise an issue on Quill side then !

**Comment by aberndtiteratec** [comment]
In case someone faces a similar issue:  the browser variable coming from svelte-kits $app/env might also help to solve it. 
https://kit.svelte.dev/docs#modules-$app-env

**Comment by ranjanified** [comment]
Today even I ran into this... I am trying to use `svelte-quill` library. When I tried `import(...)` at the top-level, it balked with `document not defined`. I am going to try to use `import(...)` inside `onMount` now. 

When I looked-up here, [svelte-quill](https://www.npmjs.com/package/svelte-quill), there is no mention of repository, sadly.
