### ISSUE TITLE
Dynamic Routes

### ISSUE THREAD

**Issue by AltCEO** [sveltejs/kit#7799]
### Describe the problem

It would be useful to be able to control which svelte file is returned, e.g. based on a domain. In our case, we have two index.svelte files (e.g. index-domain1.svelte and index-domain2.svelte) and want to return a homepage dynamically, based on the request.url.host).

Example (in our case, two domains point to our svelte kit installation)
domain1.com -> index-domain1.svelte
domain2.com -> index-domain2.svelte

### Describe the proposed solution

A hook for routing logic. It seems current hook methods don't support this use-case yet.

### Importance

would make my life easier

**Comment by PatrickG** [comment]
You already can dynamically load the component you want to render in the `load` function of a `+page.js` or `+layout.js` file.
I don't know how a hook could make this easier.

```js
// +page.js
export const load = ({ url }) => ({
  component: import(`./components/${url.hostname === 'domain2.com ' ? 'domain2' : 'domain1'}.svelte`).then(mod => mod.default);
})
```

```html
<!-- +page.svelte -->
<script>
  export let data;
</script>

<svelte:component this={data.component} />
```

**Comment by dummdidumm** [comment]
Thanks  @PatrickG , this is the blessed solution for these kinds of use cases - therefore closing.
