### ISSUE TITLE
Issues with some modules ?

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#780]
**Describe the bug**
When I import `@ethersproject/bignumber` in a page I get the following error when loading the page : 

```
500
Cannot read property 'BN' of undefined

TypeError: Cannot read property 'BN' of undefined
    at ../src.ts/bignumber.ts:12:18
    at instantiateModule (C:\dev\wighawag\test-svelte-kit\node_modules\vite\dist\node\chunks\dep-6e02b235.js:69027:166)
```

**Logs**

browser : 
```
GET http://localhost:3000/ 500 (Internal Server Error)
```

cli:
```
[vite] Error when evaluating SSR module /node_modules/@ethersproject/bignumber/lib.esm/bignumber.js:
TypeError: Cannot read property 'BN' of undefined
    at ../src.ts/bignumber.ts:12:18
    at instantiateModule (C:\dev\wighawag\test-svelte-kit\node_modules\vite\dist\node\chunks\dep-6e02b235.js:69027:166) (x3)
```

**To Reproduce**
A repo created out of `npm init svelte@next` here : https://github.com/wighawag/test-svelte-kit

`yarn && yarn dev` 

**Expected behavior**
can import es module

**Severity**
This is a blocker as I rely on @ethersproject packages

**Comment by wighawag** [comment]
Note that I tested on a pure vite vanilla project and the `@ethersproject/bignumber` import works fine there

**Comment by JBusillo** [comment]
You need to install  @ethersproject/bignumber as a dev dependency:
`npm i @ethersproject/bignumber -D@ethersproject/bignumber`
I tested your repo, and it works after doing this.

**Comment by wighawag** [comment]
Interesting.  Do you know why ?

I ll leave the issue open as it should work as is. (without @ethersproject/bignumber being a dev dependenccy).

**Comment by wighawag** [comment]
hmm, actually I tried it with `yarn add -D @ethersproject/bignumber` and same issue.

the repo use yarn, @JBusillo  did you use npm ?

**Comment by GrygrFlzr** [comment]
This is a bug with Vite when bundling certain SSR dependencies and does not appear in a Vite template project because it does not perform SSR nor bundling.

You are correct that it should be in production dependencies, not dev dependencies, so that it can be bundled into the application. It looks like Vite is failing to see that `@ethersproject/bignumber` is referencing `bn.js`.

For a proper workaround that bundles the dependency into the application, do the following in `svelte.config.cjs`:
```js
module.exports = {
  // ...
  kit: {
    // ...
    vite: {
      // ...
      optimizeDeps: {
        include: ['bn.js'],
      }
    }
  }
};```

**Comment by wighawag** [comment]
for the app I am working on I use pnpm
interestingly the optimizeDeps config fails with pnpm but succeed with yarn

I guess vite is failing to find the deps with pnpm folder structure. 

See branch : https://github.com/wighawag/test-svelte-kit/tree/pnpm

The error is 

```
> Failed to resolve force included dependency: bn.js
Error: Failed to resolve force included dependency: bn.js
    at optimizeDeps (C:\dev\wighawag\test-svelte-kit\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:65584:27)
    at async runOptimize (C:\dev\wighawag\test-svelte-kit\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69322:48)
    at async Object.createServer (C:\dev\wighawag\test-svelte-kit\node_modules\.pnpm\vite@2.1.5\node_modules\vite\dist\node\chunks\dep-66eb515d.js:69350:9)
    at async Watcher.init_server (file:///C:/dev/wighawag/test-svelte-kit/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.66_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index2.js:3229:24)
    at async Watcher.init (file:///C:/dev/wighawag/test-svelte-kit/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.66_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/chunks/index2.js:3196:3)
    at async file:///C:/dev/wighawag/test-svelte-kit/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.66_svelte@3.37.0+vite@2.1.5/node_modules/@sveltejs/kit/dist/cli.js:571:20
```

Maybe I should create a new issue for it ?

**Comment by GrygrFlzr** [comment]
@wighawag Technically speaking, only direct application dependencies should be added to Vite's `optimizeDeps.include`, pnpm is just exposing this incorrect model.

Really what should be happening is that Vite should be following the `@ethersproject/bignumber` -> `bn.js` dependency and including it. I might file a Vite issue for it later.

**Comment by wighawag** [comment]
@GrygrFlzr any other potential workaround to make it work with pnpm in the meantime ?

**Comment by johnyvelho** [comment]
same error here. I had errors with the following libs: axios and yup.

For yup, I tried to include on optimizeDeps:
include: ['lodash', 'property-expr', 'toposort', 'yup/es/Reference.js']

But no success and I still got: Error when evaluating SSR module /node_modules/yup/es/Reference.js

**Comment by benmccann** [comment]
Here's an FAQ with tips for the standard solutions to loading packages in Vite: https://github.com/sveltejs/kit/blob/master/documentation/faq/70-packages.md

I'm not sure whether this is the same issue though

**Comment by benmccann** [comment]
There have been tons of improvements to Vite and I don't think this issue exists anymore. The reproduction was quite old, so I just created a new project using `@ethersproject/bignumber` in a similar fashion and didn't experience this error. If you're still seeing it, please provide an updated reproduction and I'll take a look
