### ISSUE TITLE
$page.error (and load ({ error })) not give information about stacktrace

### ISSUE THREAD

**Issue by DeuneB07** [sveltejs/kit#7803]
### Describe the bug

In previous versions of sveltekit, I have a `+error.page` where I print an image but also the `stackTrace `for better comprehension during the development process. When the project was updated to recent versions, stackTrace is always undefined and I cannot get it with $page store or load module function (as documentation explains).

### Reproduction

```
<script lang="ts">
  import { page } from '$app/stores';

  const error = $page.error;
  const status = $page.status;

</script>

  <div class="d-flex justify-content-center">
    <div class="p-3 m-3 w-100 w-lg-75 stacktrace">
      <span class="text-left">Stack: {error.stack ?? 'Stacktrace not available' }</span>
    </div>
  </div>
```

but stackTrace is always undefined

### System Info

```Shell
none
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
You need to implement the `handleError` hook and return the stack trace from there in order to make it appear. By default, it's not shown because it could be a security risk. It should be logged to your terminal though already. More info: https://kit.svelte.dev/docs/errors#unexpected-errors
