### ISSUE TITLE
Add ability to disable svelte-package publishing instructions

### ISSUE THREAD

**Issue by silverbucket** [sveltejs/kit#7804]
### Describe the problem

I'm working on a shared component library to use with a number of different projects. The release process of this library needs to be different than a simple `npm publish` of the package directory. So the message displayed is incorrect and causes confusion among developers.

### Describe the proposed solution

Add ability to remove the publishing instructions, (i.e. `-s` silent mode)

Though it's nice to have the basic text:
```
$ npx svelte-package
src/lib -> package
Successfully built 'shared-svelte-components' package.
```

It's this part after, that can go against any custom workflow:
```
To publish it to npm:
  cd package
  npm publish
```

In my case we need to actually commit and tag the release in git and install via a git URL so this instruction is entirely incorrect for us (and potentially dangerous).

Ideally it would be even better have the option to have the `package.json` that is generated set to `private` by default.

### Importance

would make my life easier

**Comment by gtm-nayan** [comment]
Publish instructions are no longer logged with @sveltejs/package v2. (#8922)
