### ISSUE TITLE
goto with invalidateAll navigates then returns to previous page

### ISSUE THREAD

**Issue by kennethklee** [sveltejs/kit#7810]
### Describe the bug

when calling `goto(url, { invalidateAll: true })`, sveltekit navigates to the url, then returns back to the previous page.

this also happens in form actions with `<form ... use:enhance>` when you throw a redirect, for the same reason -- https://github.com/sveltejs/kit/blob/cfaca3fec5f0c6a9480333b508d5996b2762b0a6/packages/kit/src/runtime/client/client.js#L1298

### Reproduction

create a page with `<button on:click={() => goto('next', {invalidateAll: true})}>Go To Next</button>`

click the button
page will navigate to `next`, then return back to original page.

### System Info

```Shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (28) x64 Intel(R) Xeon(R) CPU E5-2650L v4 @ 1.70GHz
    Memory: 56.91 GB / 62.69 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  Browsers:
    Firefox: 105.0.3
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.87 => 1.0.0-next.101 
    @sveltejs/kit: ^1.0.0-next.454 => 1.0.0-next.561 
    svelte: ^3.52.0 => 3.53.1
```

### Severity

annoyance

### Additional Information

work around is to manually handle the redirect and call `if (result.type === 'redirect') goto(result.location)`

**Comment by dummdidumm** [comment]
Please provide a complete reproduction, I can't reproduce this given the description.

**Comment by kennethklee** [comment]
Sorry, side effect from our side. closing.
