### ISSUE TITLE
Scoped style import using <style src="./style.scss"> does not work in SvelteKit

### ISSUE THREAD

**Issue by jacob-8** [sveltejs/kit#7814]
### Describe the bug

Using the `<style src="./style.scss"></style>` syntax to import a stylesheet and scope its styles as if they were included inside the component's `<style>` block works in vanilla Svelte but not SvelteKit. To be clear, it's not the scoping that is broken in SvelteKit but the entire import. Importing styles in the `<script>` block is not an option as those are not scoped.

Documented in https://github.com/sveltejs/svelte-preprocess#external-files and referenced in https://github.com/sveltejs/svelte/issues/7125

### Reproduction

Compare these two Stackblitz examples: [style src import example - broken in SvelteKit](https://stackblitz.com/edit/sveltejs-kit-template-default-ye5xhi?file=src/routes/+page.svelte) with [style src import example - working in Svelte TS](https://stackblitz.com/edit/vitejs-vite-zgkht6?file=src/App.svelte)

### System Info

```Shell
From Stackblitz console:

System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.89 
    @sveltejs/kit: next => 1.0.0-next.561 
    svelte: ^3.46.0 => 3.53.1 
    vite: ^3.1.0 => 3.2.4
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
You don't have `svelte-preprocess` in the SvelteKit repro. 

After adding it: 
![image](https://user-images.githubusercontent.com/50981692/204069796-e4903ced-8f63-4dd0-8f09-28a2c522ab1b.png)

**Comment by jacob-8** [comment]
> You don't have `svelte-preprocess` in the SvelteKit repro.

Thank you for pointing out my eggregiously silly oversight. You've helped me identify that the problem exists only when adding my UnoCss Vite plugin (svelte-scoped) which makes changes to the style block and inadvertently replaces my `src="./foo.css"></style>` block with `<stlye>*/...computed styles*/</style>. I'll have to fix that.

**Comment by RNovaCoder** [comment]
Brother, I apologize for my lack of knowledge, but in my case, there are issues with svelte-preprocess in SvelteKit. The classes I import only work for tags that have the class immediately applied. However, if the component with the class is within a conditional statement or is a toggle class that will be added at runtime using JavaScript, the class is not imported.
