### ISSUE TITLE
"TypeError: Request3 is not a constructor" upgrading `adapter-netlify` from 76 to 77 - possibly incompatible with node fetch?

### ISSUE THREAD

**Issue by sw-yx** [sveltejs/kit#7839]
### Describe the bug

I upgraded my SK version from 510 to 561 and adapter from 
 72 to 89 (https://github.com/sw-yx/swyxkit/commit/ffdd14921ed058961d1b638735077fb26bbf8385) and it started reporting a `TypeError: Request3 is not a constructor` error:

![image](https://user-images.githubusercontent.com/6764957/204195325-bade6d2b-0512-4c6d-8307-88825bec1eff.png)

(you can see the preview here https://app.netlify.com/sites/swyxkit/functions/render?scope=deploypreview:136) causing all renders to 500. 

this **doesnt happen in dev, only prod.**

### Reproduction

https://github.com/sw-yx/swyxkit/commit/ffdd14921ed058961d1b638735077fb26bbf8385

i am debugging in https://github.com/sw-yx/swyxkit/pull/136

### Logs

```Shell
Nov 28, 12:38:24 PM: b5dfe38e ERROR  TypeError: Request3 is not a constructor
    at file:///var/task/.netlify/functions-internal/render.mjs:24273:22
    at new Promise (<anonymous>)
    at fetch3 (file:///var/task/.netlify/functions-internal/render.mjs:24272:10)
    at listContent (file:///var/task/.netlify/functions-internal/render.mjs:36534:23)
    at GET2 (file:///var/task/.netlify/functions-internal/render.mjs:36737:23)
    at render_endpoint (file:///var/task/.netlify/functions-internal/render.mjs:44730:29)
    at resolve (file:///var/task/.netlify/functions-internal/render.mjs:46610:29)
    at async respond (file:///var/task/.netlify/functions-internal/render.mjs:46520:23)
    at async fetch (file:///var/task/.netlify/functions-internal/render.mjs:46370:21)
    at async Object.fetch (file:///var/task/.netlify/functions-internal/render.mjs:46302:12)
```

### System Info

```Shell
"@histoire/plugin-svelte": "^0.11.7",
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "1.0.0-next.89",
		"@sveltejs/kit": "^1.0.0-next.561",
		"@tailwindcss/typography": "^0.5.8",
		"@typescript-eslint/eslint-plugin": "^5.44.0",
		"@typescript-eslint/parser": "^5.44.0",
		"autoprefixer": "^10.4.13",
		"concurrently": "^7.6.0",
		"eslint": "^8.28.0",
```

### Severity

annoyance

### Additional Information

filing for others to find in future as i try to isolate the problem.

i am debugging in https://github.com/sw-yx/swyxkit/pull/136

**Comment by sw-yx** [comment]
at SK version 521 i am getting this issue `Dynamic require of "fs" is not supported` again https://github.com/sveltejs/kit/issues/4079

https://app.netlify.com/sites/swyxkit/functions/render?scope=branch:bisectdeps

cc @PH4NTOMiki 

![image](https://user-images.githubusercontent.com/6764957/204196033-5f8cf73c-221c-4583-9b6b-0f07502bf63e.png)

**Comment by sw-yx** [comment]
ok as far as i know this is the status

Latest version: SK 561, Adapter Auto 89

- SK 541, Adapter Auto 75: broken
- SK 541, Adapter Auto 73: working

**Comment by sw-yx** [comment]
ok current theory is that there are at least two bugs. the earliest bug i can find is 

- Going from adapter netlify 76 to 77 https://github.com/sveltejs/kit/blob/master/packages/adapter-netlify/CHANGELOG.md#100-next77

**Comment by sw-yx** [comment]
ok turns out this is still a known bug - have to pin adapter netlify to 72 until this gets addressed https://github.com/sveltejs/kit/issues/6440 cc @brittneypostma

**Comment by benmccann** [comment]
The reason it's using `esbuild` is this line:

https://github.com/sw-yx/swyxkit/blob/ffdd14921ed058961d1b638735077fb26bbf8385/netlify.toml#L8

I recommend you remove that if you're having difficulty with `esbuild`. `adatper-netlify` will only use `esbuild` if you either set that option in `netlify.toml` or set `edge: true` in the adapter options

**Comment by sw-yx** [comment]
ahh thanks. its not yet 100% working for me (https://deploy-preview-138--swyxkit.netlify.app/welcome is mysteriously 404ing) but still pretty good! thank you!

**Comment by filipwiniarski** [comment]
This one seems related: https://github.com/sveltejs/kit/issues/12057

Having the same issue with edge functions enabled. Dynamic requires not working. I tried to write a polyfill `onBuild` plugin but couldn't make it work without breaking the the netlify edge function bundler 🤔
