### ISSUE TITLE
Static Adapter: Render dynamic routes

### ISSUE THREAD

**Issue by ShadiestGoat** [sveltejs/kit#7842]
### Describe the problem

Dynamic routing doesn't really work with a static adapter. While client side routing is great, static hosting is what I am using. I rely completely on client side rendering for this project. 
My host is my own go code. 

With a dynamic route, such as `/posts/[post=id]/` it is impossible to statically host a page that is under `post=id`. 

### Describe the proposed solution

A way to generate a `[post=id]` folder in build. This will contain an `index.html`, which csr. Please see the following difference:

```js
start({
			target: document.querySelector('[data-sveltekit-hydrate="dtem5y"]').parentNode,
			paths: {"base":"","assets":""},
			route: true,
			spa: false,
			trailing_slash: "always",
			hydrate: {
				status: 200,
				error: null,
				node_ids: [0, 6],
				params: {
					post: "123"
				},
				routeId: "posts/[post=id]"
			}
		});
```
```js
start({
			target: document.querySelector('[data-sveltekit-hydrate="dtem5y"]').parentNode,
			paths: {"base":"","assets":""},
			route: true,
			spa: false,
			trailing_slash: "always",
			hydrate: {
				status: 200,
				error: null,
				node_ids: [0, 6],
				params: {
					post: location.pathname.split("/")[2]
				},
				routeId: "posts/[post=id]"
			}
		});
```

The first one is a prerendered result with current svelte static adapter, with the following options:

```js
entries: ["*", "/posts/123"],
```

The second is what the desired output is.

With this solution, it would be up to the host to figure out routing, but that is preferable to having no dynamic router.

### Importance

i cannot use SvelteKit without it

### Additional Information

Just wanted to mention that I set importance to be the highest since in my opinion it is a core requirement of a static adapter.

**Comment by s3812497** [comment]
This is currently possible by [turning part of the app into an SPA](https://github.com/sveltejs/kit/tree/master/packages/adapter-static#spa-mode).

You'll need to specify a `fallback` option in `svelte.config.js`.

See the project below for an example:
https://stackblitz.com/edit/sveltejs-kit-template-default-5knbww?file=svelte.config.js

**Comment by ShadiestGoat** [comment]
Thank you
