### ISSUE TITLE
Better handling of function overloads in docs

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#7853]
### Describe the problem

![image](https://user-images.githubusercontent.com/1162160/204373005-e57cca3f-e6f9-4dbf-b5e7-8772de0c51bd.png)

### Describe the proposed solution

Does this need to be an overload? Is there a sneaky way we can adjust the type rather than adding doc generation logic?

### Importance

nice to have

**Comment by eltigerchino** [comment]
Closing this since the function overload now results in one document section instead of two https://svelte.dev/docs/kit/@sveltejs-kit#error
