### ISSUE TITLE
Fix `handleError` example

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#7867]
### Describe the bug

Described in this comment: https://github.com/sveltejs/kit/pull/7862/files#r1034134599

I'm putting this on the 1.0 milestone because depending on the fix we decide on we may update either the docs or types. Changing the types may be a breaking change. I *think* it'd be preferred just to change the docs, but am not a TypeScript expert

### Reproduction

`npm create svelte@latest myapp`. Create `src/hooks.server.js` containing the example code from the docs

### System Info

```Shell
latest
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
We should adjust the documentation, the types are conservative but sound
