### ISSUE TITLE
css not loading/loading too late (SASS)

### ISSUE THREAD

**Issue by offeex** [sveltejs/kit#7873]
### Describe the bug

Repro: https://github.com/OffeeX/sindrom-svelt-kita
you will fiind out css being not loaded until CTRL + F5, or loaded incompletely
Have this issue only ini PRODUCTION or preview mode
Tested on chrome and firefox

### Reproduction

I don't know i'm only one experiencing this.
Similar issue: https://github.com/sveltejs/kit/issues/967

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 2.95 GB / 15.48 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Firefox: 107.0
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.100 => 1.0.0-next.100 
    @sveltejs/kit: next => 1.0.0-next.551 
    svelte: ^3.44.0 => 3.52.0 
    vite: ^3.2.4 => 3.2.4
```

### Severity

blocking all usage of SvelteKit

**Comment by OffeeX** [comment]
found out that this line breaks everything (SASS) 
![image](https://user-images.githubusercontent.com/64991049/204483768-25b629c7-355a-4571-97b3-edc710a7d48c.png)

I need to use in css animations like this
![image](https://user-images.githubusercontent.com/64991049/204483857-73368662-3b1d-4acd-a556-65e7da23cafb.png)

**Comment by adealmeida-aa** [comment]
I'm experiencing a similar issue but I'm not using the random function, I'm using random to generate the stars for the background of my application.
![image](https://user-images.githubusercontent.com/89392376/206177113-9001a7d8-d605-43eb-80b4-9d26888c40d3.png)

My dependencies aren't even super complicated:
![image](https://user-images.githubusercontent.com/89392376/206177275-9e13d67b-ab8d-466d-999b-9a7326726b65.png)

**Comment by jakobbouchard** [comment]
I seem to be experiencing a similar issue with PostCSS. Since my project is relatively new, I'll try removing PostCSS to see if the issue disappears.

**Comment by jakobbouchard** [comment]
I can confirm that removing PostCSS and using plain CSS fixes the issue.

**Comment by steinoy** [comment]
Same issue here with PostCSS. Fixed it by adding the PostCSS configuration directly in vite.config.js:

```
const config = {
	plugins: [sveltekit()],
	css: {
		postcss: {
			plugins: [
				...
			]
		}
	}
};
```

Still have to configure the preprocess option in svelte.config.js or Svelte will complain.

The resulting CSS with or without configuring PostCSS in vite.config.js is the same, but the server side rendered element class names differ from the names in the CSS files. The client side JS has correct class names, so everything looks right when it's hydrated.

**Comment by Visual-Dawg** [comment]
I am using PostCss and Sass (separate components) and I have this problem too

**Comment by eltigerchino** [comment]
Closing this issue as it's stale and the reproduction is no longer accessible
