### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by developedbyant** [sveltejs/kit#7888]
### Describe the problem

It will be nice to have something like express.js `express.static`, a way to delivery files after you run `npm run build`.
Right now if you have to rebuild your app everything you add new assets to your project in order to use it, if you have a project where you generate, create or upload new static files from server side you can't use it without running `npm run build` again, you will get a `404 file not founded` because asset was uploaded after app built.
### Example 
File `image-1.png` exists in your `static` path, you run `npm run build` and uploaded `image-2.png` after the build now you can't access `image-2.png` without rebuilding your app.
### express
``` JavaScript
// Set static files path
app.use(express.static("static"))
```

### Describe the proposed solution

A way to set a static folder, where you can have access to new files after build.

### Importance

would make my life easier

**Comment by ayuancool** [comment]
I don't understand why it's not supported to return files with the same name from an additional static resource directory when the route misses. At least give us an option to choose when to enable it. Please consider, thank you
