### ISSUE TITLE
Documentation for creating an adapter

### ISSUE THREAD

**Issue by Crisfole** [sveltejs/kit#789]
Adapters pretty simple, but they definitely need better documentation. Even exposing Typescript interfaces and types would help.

**Comment by benmccann** [comment]
Can you explain more? Is there something you were trying to accomplish that you had difficulty with?

I believe that the types are exposed at least for some adapters: https://github.com/sveltejs/kit/blob/96cbda341e4139bd944ac01f9fe8753e8a25a171/packages/adapter-node/index.js#L5

**Comment by dummdidumm** [comment]
You said "create your own". So what documentation do you expect specifically?
- documentation about how to create a new adapter?
- documentation on certain existing adapters (how to use them)?

**Comment by jthegedus** [comment]
Related: documentation/guidance for how community created adapters are going to be listed (if at all) in the SvelteKit docs.

@Crisfole I've taken care of the Firebase adapted - https://github.com/jthegedus/svelte-adapter-firebase

**Comment by ignatiusmb** [comment]
This is now documented under https://kit.svelte.dev/docs#writing-an-adapter
