### ISSUE TITLE
use:enhance breaks forms that are not method=POST

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#7896]
### Describe the bug

A form with no method (or method=get) cannot have a use:enhance directive. The presence of such a directive causes the form to attempt to submit with a POST, and errors out. 

### Reproduction

https://github.com/arackaf/form-enhance-repro

repro should be self-explanatory - type in the box and hit enter. 

### Logs

```Shell
500
Unexpected token '<', "<!DOCTYPE "... is not valid JSON
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at deserialize (http://localhost:5173/node_modules/@sveltejs/kit/src/runtime/app/forms.js?v=857c15ff:21:22)
    at HTMLFormElement.handle_submit (http://localhost:5173/node_modules/@sveltejs/kit/src/runtime/app/forms.js?v=857c15ff:106:13)
```

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 69.51 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.11.1 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 8.18.0 - ~/Documents/node_modules/.bin/npm
  Browsers:
    Chrome: 107.0.5304.121
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.570 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.4
```

### Severity

Serious but not the end of the world

**Comment by tcc-sejohnson** [comment]
This is intended behavior, I believe. The default method for a form is GET, and using `use:enhance` on a GET form doesn't make sense. SvelteKit automatically provides enhanced behavior for GET forms: https://kit.svelte.dev/docs/form-actions#get-vs-post

To fix this:
- Specify `method="POST"` and provide a handler in `+page.server.ts`
- Remove `use:enhance` and handle the client-side navigation's query parameter in your `+page.ts` `load` function using `event.url`

**Comment by arackaf** [comment]
@tcc-sejohnson thanks for replying! That actually makes sense. Really I was only using use:enhance to do some preprocessing on the formData object prior to submission. 

Is there some other way of doing that? I did look in the on:submit handler, but did not see anything in that event object.

**Comment by PatrickG** [comment]
Maybe it's not a bad idea to check if the form would send a POST request, and stop the enhancement (dont preventDefault) if it doesn't.
I can't think of any use case for this, but there might be a `button` with [`formmethod="GET"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-formmethod).

**Comment by Rich-Harris** [comment]
Yeah, we should bail and print an error from `enhance` if `method !== 'post'`

**Comment by arackaf** [comment]
@Rich-Harris is there some other way to get direct access to the formData object (ie, to remove empty entries and prevent annoying search=&nextItem= from showing up in your url?

**Comment by geoffrich** [comment]
@arackaf I believe you can use the browser-native [`formdata` event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/formdata_event) for that. e.g.

```html
<script>
  import { page } from "$app/stores";

  function handleFormData(e) {
    const { formData } = e;
    // add a new entry
    formData.append("test", "var");
    // remove a value
    formData.delete("idontwant");
    // edit a value
    const hello = formData.get("hello");
    formData.set("hello", hello + " from formdata");
  }
</script>

<p>
  Submitted: {JSON.stringify(Object.fromEntries($page.url.searchParams))}
</p>
<form on:formdata={handleFormData}>
  <input name="hello" />
  <input name="idontwant" value="no" />
  <button>Submit</button>
</form>
```

**Comment by arackaf** [comment]
@geoffrich you're my hero - I swear I tried that, or thought I did. 

That ... appears to work perfectly. Thank you SO much.

**Comment by arackaf** [comment]
I do still think it would be useful for the same use:enhance to work with GET forms, but if that's by design, a maintainer can feel free to just close this. Clearly there's decent workarounds.

**Comment by AleksandrHovhannisyan** [comment]
Apologies for necroing this very old thread, but I also think it would be useful to support `use:enhance` for `GET` requests on forms. There are valid use cases for this that don't involve side effects.

For context, I'm using [Superforms](https://superforms.rocks/) to create a progressively enhanced HTML form that uses a schema validation library (like zod) for both client-side and server-side validation. To do this, I need to use that library's own `enhance` function:

```svelte
<script>
    const { form, enhance } = superForm(form, {
	validators: zod(schema),
	validationMethod: 'onblur',
    });
</script>

<form method="GET" use:enhance></form>
```

Unfortunately, because Svelte does not support `use:enhance` on `GET` forms, the library doesn't support it either. But I have a legitimate use case for this: My GET form needs to redirect the user to another route on submit (if JS is disabled) and serialize the data in the URL for easy link sharing. A POST request doesn't really make sense in my app and loses out on this native form-serializing behavior.

Am I perhaps missing an obvious workaround to this?
