### ISSUE TITLE
Prettier doesn't work with pnpm

### ISSUE THREAD

**Issue by matiaguilera** [sveltejs/kit#7916]
### Describe the bug

Prettier doesn't format svelte files when using pnpm.

### Reproduction

Skeleton project created today using `pnpm create svelte@latest my-app`

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (2) x64 Intel(R) Celeron(R) CPU  N2830  @ 2.16GHz
    Memory: 548.25 MB / 3.89 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90
    @sveltejs/kit: next => 1.0.0-next.570
    svelte: ^3.53.1 => 3.53.1
    vite: ^3.2.4 => 3.2.4
```

### Severity

annoyance

**Comment by matiaguilera** [comment]
That works! Is there a way to format the files automatically after saving?

**Comment by The-Noah** [comment]
It depends on your editor. If you're using VSCode you can create `.vscode/settings.json` and add
```json
{
  "editor.formatOnSave": true
}
```

**Comment by matiaguilera** [comment]
Apparently it was just a configuration error on my part. VSCode notified me about a problem with the formatter, then when I clicked on it the problem got solved. 

When I am on a svelte file though, in the status bar Prettier still has a circle slash symbol next to it. But it works nevertheless.
