### ISSUE TITLE
Wrong styles applied when using multiple layouts

### ISSUE THREAD

**Issue by DaveKeehl** [sveltejs/kit#7918]
### Describe the bug

I noticed that when a SvelteKit project has the following folder/routes structure:

```bash
src
├── ...
└── routes
    ├── (post)
    │   ├── article/[slug]/...
    │   ├── project/[slug]/...
    │   └── +layout.svelte
    ├── +layout.svelte
    ├── +page.svelte
    └── ...
```

If both `src/routes/+layout.svelte` and `src/routes/(post)/+layout.svelte` use the global css selector in the `<style>` tag on the same element, then styles are not updated accordingly when navigating between the routes involved.

For example, in my case I wanted to have `scroll-behavior:scroll` on the homepage, and `scroll-behavior:auto` on all the pages inside the `(post)` group. So I did the following:

```html
/routes/+layout.svelte
<script lang="ts">
  import '../styles/global.css';
</script>

<slot />

<style global>
  html {
    scroll-behavior: smooth;
  }
</style>
```
```html
/routes/(post)/+layout.svelte
<script lang="ts">
  import '../styles/global.css';
</script>

<slot />

<style global>
  html {
    scroll-behavior: auto;
  }
</style>
```

What happens is the following. I navigate on the homepage and the smooth scroll behavior works fine (which is good). Then, I navigate to `/project/<whatever>` and the smooth scroll behavior is overridden with `auto` (which is good). However, if at this point I navigate back to the homepage, the `scroll-behavior:smooth` rule is not applied again (which is incorrect).

This is what the html element has after going back to the homepage, when in reality it should be the other way around.
![image](https://user-images.githubusercontent.com/34663397/205329884-4cf5c825-0a25-4563-9b97-2206f9269806.png)

### Reproduction

I have 2 repros: my own work-in-progress portfolio website where I first noticed this issue, and a small StackBlitz sandbox that shows the same problem in a minimal environment.

- [My portfolio](https://github.com/DaveKeehl/portfolio/tree/2022/src/routes)
- [StackBlitz sandbox](https://stackblitz.com/edit/sveltejs-kit-template-default-6o13rn?file=src%2Froutes%2F(post)%2F%2Blayout.svelte,src%2Froutes%2F(post)%2Fpost%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte)

If you checkout my portfolio you need to:
1. Clone it
2. Run `npm i`
3. Run `npm run dev` (or you can also build it and preview it)
4. Go to `localhost:5173`
5. Click on `projects` in the navbar
6. Go to `/project/svelte-reveal`
7. Go back to `/`
8. Click on `projects` in the navbar

As you'll see, the smooth scroll behavior is now lost.

---

If you checkout the StackBlitz sandbox you can see this behavior by navigating between the page at the root (`/`) and `/post`.

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.65 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Edge: 107.0.1418.62
    Firefox: 97.0.1
    Safari: 16.1
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Is this the same as #7751? The order that global styles are applied is not guaranteed, which is a limitation it would be too onerous to do anything about, and which we intend to document.

**Comment by DaveKeehl** [comment]
Looks like it, yeah. Though in my case there is no behavior difference between `vite dev` and `vite build+preview`
