### ISSUE TITLE
Upload image/file and save it to filesystem no longer works same way, what is method to do this now?

### ISSUE THREAD

**Issue by half-metal** [sveltejs/kit#7924]
### Describe the bug

This repo is fine for updating an image in filesystem using a previous version of Sveltekit:

https://github.com/Programonaut-Blog/sveltekit-image-upload

Something changed in Sveltekit, and a very common use case "write a file to filesystem" has what seems like no documentation for Sveltekit in its current form.  What's the recommended way to do this now? I want to upload an image and save on filesystem. This worked fine before, but all the examples online are using old Sveltekit and error out.

This explains using request.json() that I am used to https://stackoverflow.com/questions/70990443/unable-to-access-request-body-from-the-endpoint-js-in-sveltekit-skeleton-project, but I get an error with "Unexpected token o in JSON at position 1"

### Reproduction

Use this same code with latest version of Sveltekit, no longer works.
https://github.com/Programonaut-Blog/sveltekit-image-upload

### Logs
When attempting to use .json() with code above I get this
```Shell
Unexpected token o in JSON at position 1
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
```

### System Info

```Shell
Mac, svelte latest 1.0.0-next.571
```

### Severity

serious, but I can work around it

### Additional Information

Still boggled Sveltekit doesn't have core common use cases which would be updated with major changes, would help with adoption and probably cut down on defects.

**Comment by Conduitry** [comment]
Please don't use issues for support requests. That repo and SO answer are both rather old, and there have been a lot of changes since then. You can ask in Discord or in GitHub Discussions for sample code for uploading a file.

**Comment by half-metal** [comment]
ok, let me try ask for sample code for how to do it with latest Sveltekit since it no longer works since Sveltekit changes. I will try Discord first, then Github discussions @Conduitry
