### ISSUE TITLE
hide `/__data.json` from the `url` object inside `handle`

### ISSUE THREAD

**Issue by ivanhofer** [sveltejs/kit#7926]
### Describe the problem

I find it weird that the `url` object inside `handle` in `hooks.server.ts` differs from the `url` object passed to the route files.

In the end, the `/__data.json` information from the route is just for the `resolve` function to distinguish what it should return.

Use-cases I see problematic with the current approach:
 - redirecting in case of an unauthenticated request and saving the current information as a "redirectTo" parameter
   This works fine as long as you directly access `/dashboard/project1` in the browser, but if you would get redirected via a client-side navigation, the "redirectTo" parameter will be `/dashboard/project1/__data.json`
 - logging: when I want to track how many requests were made to `/dashboard/project1` I would also need to look for `/dashboard/project1/__data.json` entries (assuming I log all accesses with its url from within `hooks.server.ts`)

It is easy to make a workaround for those usecases and manually remove the `/data.json` at the end of the url, but you first have to discover that this "issue" exists. I see this as a hurdle for new or inexperienced users.

And I also see it problematic if e.g. for some reasons `__data.json` gets renamed to `__data.json5` or `__data.xml`  in the future to support other content formats. Then the workarounds will no longer work.

> Here is a small project demonstrating a problematic logging issue: https://stackblitz.com/edit/sveltejs-kit-template-default-sllc4q?file=src/hooks.server.ts
> 1. Click on the "page 1" link
> 2. Reload the page
> 3. See that both requests resulted in different log outputs

### Describe the proposed solution

Use the same `url` object within `hooks.server.ts` (without `/data.json` at the end) and add a new attribute to the `event` object to distinguish between regular requests and data requests.

This would mean a breaking change, but the migration process should be fairly simple.

### Alternatives considered

Leave it as it is

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
We used to do exactly this (strip the `__data.json` suffix) but it proved problematic, though I can't recall the exact reasons and I can't seem to find the issue where it was discussed.

**Comment by ivanhofer** [comment]
Do you mean back in the days where the server distinguished between html and data requests via a header the client sent? Or was this in `sapper`?

Maybe to make it more clear: the client should not change it's behaviour. Just the server.
I have hacked together an example that should demonstrate it:
```ts
const patchHandle = (handle) =>
	async ({ event: originalEvent, resolve: originalResolve }) => {
		let event = originalEvent;
		let resolve = originalResolve;
		if (originalEvent.url.pathname.endsWith('/__data.json')) {
			event = {
				...event,
				url: new URL(originalEvent.url.toString().replace('/__data.json', '')),
				isLoadRequest: true,
			};
			resolve = (event) => {
				if (event.isLoadRequest) {
					event = {
						...event,
						url: new URL(originalEvent.url.toString() + '/__data.json')
					};
				}
				return originalResolve(event);
			}
		}

		return handle({ event, resolve });
	};

export const handle = patchHandle(async ({ event, resolve }) => {
	// custom handle function
});
```

**Comment by Rich-Harris** [comment]
No, I mean that an older version of SvelteKit did exactly what `patchHandle` does (minus the `isLoadRequest` property, plus `trailingSlash` handling). I suspect part of the problem was that it made it impossible to know if you were serving an HTML or data request, which `isLoadRequest` solves.

Marking as a 1.0 milestone issue since if we change this it needs to happen before then.

**Comment by dummdidumm** [comment]
I also vaguely remember some issue where someone expressed concerns about not being able to distinguish `__data.json` requests, but can't find it either. IIRC it even requested to not remove `__data.json` in some other place. So if we decide to remove it, there probably needs to be some other way to know that it's a data request (through a boolean or something like that).

**Comment by bjon** [comment]
@Rich-Harris @dummdidumm We had problems with that, see https://github.com/sveltejs/kit/issues/6201#issuecomment-1225833655

But `isLoadRequest` would solve that, for us.

**Comment by dummdidumm** [comment]
Aaaah thank you, that's exactly the comment I remembered. Glad to hear the boolean would solve that for you!
