### ISSUE TITLE
Don't enforce url-encoding of cookies

### ISSUE THREAD

**Issue by jb297686** [sveltejs/kit#7929]
### Describe the problem

With #7736 we moved from being opinionated that cookies should _not_ be url-encoded to being opinionated that they _should_ be url-encoded.  This means that authentication will now fail if we forward a cookie to a backend service that requires that cookies are _not_ url-encoded.  Url-encoding cookies may be very common but it is not universal so it makes sense to allow for either case.

We currently respect the `encode` option passed when calling `cookies.set()` so it's possible to set a cookie that is not url-encoded, but if that cookie later comes back from the client and we 'forward' it to a backend service using `fetch` it will get url-encoded.

Example flow, with a backend service that insists on non-url-encoded cookies:
```
backend service
     |
(response with non-url-encoded cookie) (cookie=foo+bar)
     |
     v
sveltekit node app
     |
(cookie set using cookies.set() with { encode: (value) => value }, i.e. no encoding) (cookie=foo+bar)
     |
     v
browser
     |
(request, returning cookie just as it was when the browser received it) (cookie=foo+bar)
     |
     v
sveltekit node app
     |
(external fetch request, url-encoding of cookie is enforced) (cookie=foo%2Bbar)
     |
     v
backend service declines authentication as it expects non-url-encoded cookie
```

### Describe the proposed solution

Be unopinionated about whether cookies should be url-encoded.  For cookies sent by the browser don't decode them when we parse them and don't encode them later - just leave them as they are.  For explicit header cookies let people specify their own encoder function if they want to, just as they can when adding to `new_cookies` by calling `cookies.set()`.

```diff
// kit/packages/kit/src/runtime/server/cookie.js
export function get_cookies(request, url, dev, trailing_slash) {
	const header = request.headers.get('cookie') ?? '';
-	const initial_cookies = parse(header, { decode });
+	const initial_cookies = parse(header, { decode: (value) => value });  // i.e. don't decode
```
and

```diff
// kit/packages/kit/src/runtime/server/cookie.js
	/**
	 * @param {URL} destination
	 * @param {string | null} header
+	 * @param {function} header_encode
	 */
-	function get_cookie_header(destination, header) {
+	function get_cookie_header(destination, header, header_encode) {
		/** @type {Record<string, string>} */
		const combined_cookies = {};

		// cookies sent by the user agent have lowest precedence
		for (const name in initial_cookies) {
-			combined_cookies[name] = encode(initial_cookies[name]);
+			combined_cookies[name] = initial_cookies[name]; 
		}

		// cookies previous set during this event with cookies.set have higher precedence
		for (const key in new_cookies) {
			const cookie = new_cookies[key];
			if (!domain_matches(destination.hostname, cookie.options.domain)) continue;
			if (!path_matches(destination.pathname, cookie.options.path)) continue;

			const encoder = cookie.options.encode || encode;
			combined_cookies[cookie.name] = encoder(cookie.value);
		}

		// explicit header has highest precedence
		if (header) {
			const parsed = parse(header, { decode });
+			const encoder = header_encode || encode;
			for (const name in parsed) {
-				combined_cookies[name] = encode(parsed[name]);
+				combined_cookies[name] = encoder(parsed[name]);
			}
		}

		return Object.entries(combined_cookies)
			.map(([name, value]) => `${name}=${value}`)
			.join('; ');
	}

```
The `'serialized cookie header should be url-encoded'` test in kit/packages/kit/src/runtime/server/cookie.spec.js would need to be removed.

### Alternatives considered

Not doing any decoding/encoding of cookies by default, but if url-encoding cookies is very common it probably makes sense to leave that as the default behavior for `cookies.set()` and for explicit header cookies.

### Importance

would make my life easier

### Additional Information

If this change makes sense I'm willing to work on a PR.

**Comment by dummdidumm** [comment]
I'm not sure this would work, because AFAIK there's no way to know if the cookie coming from the browser was previously set through `cookies.set` and therefore encoded - in which case we need to decode it. Could you solve this through some logic in the externalFetch hook?

**Comment by jb297686** [comment]
I don't think it's possible to workaround this with a handleFetch hook. It's `get_cookie_header` that adds the url-encoding, and that gets called after handleFetch.

In any case, you can't access the browser cookies in handleFetch, for two reasons:
1. In handleFetch the `request` parameter does not yet include the cookies received from the browser - they get added later.
2. `cookies` is not available as a parameter in handleFetch, so the browser cookies can't be accessed that way.

```js
export async function handleFetch({ request, fetch }) {
    // here the request object only contains the cookies added when the
    // request was created i.e. when fetch was called from somewhere
    // else in the app
  }
 
  return fetch(request);
  // when you call fetch here it will call get_cookie_header, which adds
  // the cookies that came from the browser (and also those added using
  // cookies.set) and adds the url-encoding to the cookies
```
Does cookie.js need to url-decode cookies that arrive from the browser? It needs to parse the cookie string, but I can't see the reason for decoding the cookie tokens, but perhaps I'm missing something.  If someone needs the decoded cookie token it can be accessed using `cookies.get()` which url-decodes by default.

#7736 highlighted the issue that "forwarded input cookies are different on the way out than on the way in". Previously we were forcibly removing url-encoding before forwarding a cookie but now we are forcibly adding url-encoding before forwarding. I think it makes sense that forwarded cookies should be the same on the way out as on the way in.

`cookies.set()` and `cookies.get()` have `encode`/`decode` options and cookie.js respects those options, so it's inconsistent for cookie.js to force encoding on forwarded cookies.

**Comment by dummdidumm** [comment]
(adding this to 1.0 to have it on our radar to decide whether a breaking change is lurking here, and to reach a conclusion how to proceed, not necessarily implement it)
