### ISSUE TITLE
Error related to Sveltekit's new link prefetch options

### ISSUE THREAD

**Issue by kristjanmar** [sveltejs/kit#7946]
### Describe the bug

I updated to the latest SvelteKit in prod about 3 hours ago and already have 60 errors in Sentry thrown from line 50 of this file:
https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/utils.js

```
function link_option(element, name) {
	const value = /** @type {ValidLinkOptions<T> | null} */ (
		element.getAttribute(`data-sveltekit-${name}`)
	);

	if (__SVELTEKIT_DEV__) validate_link_option(element, name, value);

	return value;
}
```

So the element.getAttribute throws an error because element is null.

![33aaaa9c35f207e5d2435b6336c74797](https://user-images.githubusercontent.com/22234692/205644160-1b37bd55-bd58-47df-8b77-e8be71bd2330.png)

### Reproduction

Not sure how to reproduce, just seeing this in Sentry but not on my own machine.

### System Info

```Shell
Latest versions of everything.
```

### Severity

blocking an upgrade

**Comment by PatrickG** [comment]
Duplicate and already fixed #7913
