### ISSUE TITLE
Docs clarification for form action errors 

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#7949]
### Describe the problem

The docs around form actions, in particular errors therein, might be incomplete or incorrect.

The bullets in [this section](https://kit.svelte.dev/docs/form-actions#progressive-enhancement) imply that an error in a form action, with or without progressive enhancement, will trigger the nearest error boundary. 

This seems like extremely questionable design, since it would cause existing UI to unmount, and show an error screen if a form failed to post, rather than just showing the existing UI, along with an error message of some sort. 

Fortunately I've been unable to actually cause this to happen, which makes me hope perhaps the docs are just unclear? 

I have this as my first line in my form action

```js
throw new Error("Bad");
```

but fortunately the progressively enhanced form does not unload my UI for an error boundary (instead provides the appropriate error properties in my use:enhance callback, or $page store)

After the comment below, I tried this 

```js
return invalid(500);
```

instead of the throw new Error, but that behaved the same, except (when progressively enhanced) the fetch to the form action no longer errors out, but instead returns a 200 status. 

[This comment](https://github.com/sveltejs/kit/issues/7233#issuecomment-1279779888) makes me especially suspicious that the docs are intended to mean something else? Does the error boundary only show if the page re-rendering throws an error? Ie, the load function throws an error, after the form is done?

### Describe the proposed solution

Clearify docs.

### Alternatives considered

n/a

### Importance

would make my life easier

**Comment by s3812497** [comment]
I believe the error boundary always shows after any `throw error()` (expected error), uncaught errors in the load function or form action, and non-existent routes.

**Comment by arackaf** [comment]
@s3812497 - I updated my original post - throw new Error is exactly what I'm doing in my form action

**Comment by arackaf** [comment]
@s3812497 - I updated my original post - throw new Error is exactly what I'm doing in my form action

**Comment by arackaf** [comment]
@s3812497 thanks! throw new Error is what I have, and return invalid() doesn't really change the behavior. The error boundary continues to NOT show, no matter how the form action returns an error

**Comment by s3812497** [comment]
> @s3812497 thanks! throw new Error is what I have, and return invalid() doesn't really change the behavior. The error boundary continues to NOT show, no matter how the form action returns an error 

If you implemented a custom callback for the enhance function, you have to use `applyAction` or `update` to show the error oafe

**Comment by arackaf** [comment]
@s3812497 thanks again! I've tried this progressively enhanced, with and without a custom callback, and with and without calling update with the custom callback. None unmounts my existing UI, to show an error boundary.

Again though ... that seems right. It seems positively insane to unmount existing UI, to render an entire error page if a form action fails. I'm increasingly thinking this is correct, and the docs just need a tweak.

**Comment by s3812497** [comment]
> @s3812497 thanks again! I've tried this progressively enhanced, with and without a custom callback, and with and without calling update with the custom callback. None unmounts my existing UI, to show an error boundary.
> 
> Again though ... that seems right. It seems positively insane to unmount existing UI, to render an entire error page if a form action fails. I'm increasingly thinking this is correct, and the docs just need a tweak.

Could you provide a reproduction? I'm genuinely curious as to what's causing this.

**Comment by arackaf** [comment]
I can do that a bit later. I'm hoping Rich might chime and and confirm whether this is expected behavior.

**Comment by dummdidumm** [comment]
It would go up to the nearest error boundary, matching the behavior of an error thrown during load. As @s3812497 points out a reproducible would be good to understand what behavior is triggered for you and whether that's expected or not.

**Comment by arackaf** [comment]
@dummdidumm your word is as good as Rich's so I'll get on that.

Pending that ... Tee mentioned that, even with expected behavior, simply not calling update() is enough to *not* jump over to the error boundary, which I was happy to see.

**Comment by dummdidumm** [comment]
Correct, not calling update or applyAction in the progressive enhancement case would prevent this from happening, so you could create your own error handling logic instead

**Comment by arackaf** [comment]
@dummdidumm got it - it still seems to be a bug though (however much I might disagree with the correct behavior) - will put together a repro

**Comment by arackaf** [comment]
@dummdidumm found the problem. Your docs say that actions always use post, since get's should never have side effects. But Kit let's me omit the method altogether, and happily fires off a GET to my form action, which works just fine (incorrect error behavior notwithstanding).

Is *that* by design, or a bug?
