### ISSUE TITLE
possibility to throw invalid function (for implement better server-side validation)

### ISSUE THREAD

**Issue by alphaelf** [sveltejs/kit#7951]
### Describe the problem

so for server side validation, current approach according to [docs](https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action-validation-errors) is do validation in form action function in `page.server.ts` and `return invalid` function with proper status code and message but what if we want use validation libraries like `zod`, `yup`, `joi` or ... ?

for implementing those libs, zod for example we need to add `validate` function to `request` object through `hooks.server.ts`:
```typescript
import type { Schema } from 'zod'
import { invalid, type Handle } from '@sveltejs/kit'

export const handle: Handle = async ({ event, resolve }) => {
  event.request.validate = async (schema: Schema) => {
    const data = Object.fromEntries((await event.request.formData()))
    const validation = await schema.safeParseAsync(data)
    if (!validation.success)
      throw invalid(422, {errors: validation.error.flatten().fieldErrors})
    return validation.data
  }
  return resolve(event)
}
```
and simply use it in any action we need.
e.g. in `+page.server.ts`:
```typescript
import type { Actions } from "./$types"
import { z as Schema } from 'zod'

export const actions:Actions = {
  default: async ({ request }) => {
    const schema = Schema.object({
      username: Schema.string().min(3),
      password: Schema.string().min(3)
    })
    const payload:Schema.infer<typeof schema> = await request.validate(schema)
    // payload is the validated data
  }
}
```
and if data not being validate it will throw 422 error, but we can't throw invalid function 😔 

### Describe the proposed solution

just do as same as [redirect](https://github.com/sveltejs/kit/blob/dcb9d3dc494422dce1996ffe56630fd52090d0ba/packages/kit/src/runtime/server/page/actions.js#L141-L147) code in sveltekit `actions.js` file and it works as I expected
in `runtime/server/page/actions.js`:
```javascript
...
if(error instanceof ValidationError){
  return action_json({
    type: 'invalid',
    status: error.status,
    data: error.data
  });
}
...
```
and for types in `runtime/server/utils/error.js`:
```javascript
import { HttpError, Redirect, ValidationError } from '../runtime/control.js';
...
export function normalize_error(error) {
  return /** @type {Redirect | HttpError | Error | ValidationError} */ (error);
}
```

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment]
As @tcc-sejohnson points out, you can try-catch this at your usage locations - and if you don't want to write this every time, you can abstract it away into a helper function which you use for your actions:

```js
import type { Actions } from "./$types"
import { z as Schema } from 'zod'

async function catchInvalid(async (fn) => {
  return async (input) => {
    try {
       await fn(input);
    } catch (invalid) {
       return invalid;
    }
  };
}); 

export const actions:Actions = {
  default: catchInvalid(async ({ request }) => {
    const schema = Schema.object({
      username: Schema.string().min(3),
      password: Schema.string().min(3)
    })
    const payload:Schema.infer<typeof schema> = await request.validate(schema)
    // payload is the validated data
  }
}
```

You could enhance that higher-order-function pattern to get rid of your `handle` function, too, and even add the schema as one of the arguments, reducing the code further:

```js
// ...
const schema = Schema.object({
      username: Schema.string().min(3),
      password: Schema.string().min(3)
});

export const actions:Actions = {
  default: withSchemaValidation(schema, async (paylout) => {
    // payload is the validated data, if there's something invalid, withSchema will take care of it and return early
  }
}
```
