### ISSUE TITLE
Rename 'shared load functions' to 'universal load functions'

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#7952]
### Describe the problem

I'm working on some tutorial content, and finding the 'server-only `load` functions' and 'shared `load` functions' terminology a bit ugly and confusing.

### Describe the proposed solution

* Server `load` function — `+page.server.js`, `+layout.server.js`
* Universal `load` function — `+page.js`, `+layout.js`

### Alternatives considered

'Isomorphic' 🤮 

### Importance

nice to have

**Comment by benmccann** [comment]
Shared always made sense to me. Universal seems a bit weird to me because it's like they can run on anything anywhere, but there's really only two places they're running - the client and the server - so it doesn't seem like it needs such an all encompassing name

**Comment by tcc-sejohnson** [comment]
Not to be utterly controversial, but what if we just named them like we do environment variables? Public load and private load. They both follow the same semantics -- public x can be used both server-side and client-side, while private x can only be used server-side.

**Comment by avarun42** [comment]
Isomorphic seems like it has a clear definition that matches the intent of usage here, so why 🤮?

**Comment by Rich-Harris** [comment]
It's a pretentious word that means the opposite of what people in the JavaScript world want it to mean. Isomorphism describes different things that have the same form, rather than one thing adapting to multiple surfaces. It's backwards.

**Comment by Jerboas86** [comment]
what do you think about omni-side load function ?

**Comment by lukaszpolowczyk** [comment]
@Jerboas86 In this case, another one in this style: both-side. :)
