### ISSUE TITLE
shrink test matrix?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#796]
We test node 12, 14 and 15 on linux, mac and windows — 9 separate runs. It would be quicker if we had fewer. Unless we're trying to identify e.g. a windows bug that only happens on node 12, would it be sufficient to test 12 and 14 on linux, and 15 on linux, mac and windows?

**Comment by dummdidumm** [comment]
I'd switch it up and test 14 on mac/windows and 15 on linux only, since far more people will use 14 than 15 (the "inbetween LTS" version)

**Comment by Rich-Harris** [comment]
We also don't need to build the examples on every possible combination
