### ISSUE TITLE
Respect cache options in subsequent_fetch

### ISSUE THREAD

**Issue by cristovao-trevisan** [sveltejs/kit#7971]
### Describe the bug

Found two bugs in cache implementation at client-side [fetcher.js](https://github.com/sveltejs/kit/blob/1dfa20e7d8e27fbdca99067619b16e1ca125f4a2/packages/kit/src/runtime/client/fetcher.js):

- Current implementation of subsequent_fetch considers only max-age and ignores the cache option
- Cache `delete` and `get` are using different keys

About the cache option (RequestCache from RequestInit), I think it should redo the request if it's set to 'no-store', 'no-cache' or 'reload'.
Another option is to let the browser handle the cache entirely, but I assume there's a reason to be a cache object (and that's why I didn't create a PR). 

### Reproduction
I've created a very simple example to explain the issue that I have in my private app. To better explain the issue here a few facts of my application (which should be a very common case):
- I have a separate backend (not running in kit) that provides user data (among other stuff), but the example uses +server.ts to simulate the backend
- Authentication is done using http-only cookies
- To check auth, kit calls an API that returns user data (name, image, etc). In the example only name is used
- I want to load this user data in the layout and cache it (don't need to request at every navigation)
- I use max-age in the API to cache this data
- There's a profile page in which the user can update it's own info, e.g. it's name
- The profile update form sends a POST/PUT request to the backend, then it reloads user data (layout load through invalidation)

Here the problem arises: If max-age is set, the user data is not being reloaded by invalidateAll even if I set `{ cache: 'reload' }` in fetch options.

### Example
The example bellow does 3 things to demonstrate this:
- Calls invalidateAll on form submit (use:enhance)
- Calls invalidateAll on page load (just to make sure)
- Calls fetch directly on page load, using `cache: 'reload'`, to show that the response is different from what's on the screen (thus returned by +page.js)

> https://github.com/cristovao-trevisan/kit-issue-report

Submitting the form with a different name does not update the page data. By navigating back and forward and looking at the console you can see that the invalidateAll function does not take effect (because the resource is cached), even after reloading the HTTP cache.
Reloading the page does update the data. 

![image](https://user-images.githubusercontent.com/4981855/205979384-41d454c9-ae0d-49a9-9d4f-3c2b5cf72353.png)

![image](https://user-images.githubusercontent.com/4981855/205979491-50cf88c5-77dc-4f68-979a-5349825aac49.png)

### System Info

```Shell
System:
    OS: Linux 6.0 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
    Memory: 1.19 GB / 7.68 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.134
    Firefox: 107.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.572 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.4 => 3.2.5
```

### Severity

serious, but I can work around it

> The current work around is to remove the max-age header and request user info at every navigation

**Comment by dummdidumm** [comment]
I don't fully understand the issue. To clarify: In your reproduction, you set the cache control header inside `+server.js` and you expect `invalidateAll()` to bust the cache - am I understanding this correctly? If so: `invalidateAll` only relates to `load? functions in `+page(.server).js`. If not: Could you clarify the issue?

**Comment by cristovao-trevisan** [comment]
Thanks for que quick answer!!

I've updated the **Reproduction** section the better explain my issue

**Comment by dummdidumm** [comment]
Thanks, I understood the problem now. About your second point: "Cache delete and get are using different keys" - what do you mean exactly? `cache.get` and `cache.delete` both use `selector`.

**Comment by cristovao-trevisan** [comment]
Just saw your PR and it's exactly what I meant. Thanks a lot!
