### ISSUE TITLE
Accessing environment variables in `svelte.config.js`?

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#7981]
### Describe the bug

Currently, it seems like it's not possible to access environment variables (i.e. import from `$env/static/*` or `$env/dynamic/*`) from within the `svelte.config.js` file, which I was surprised to find out. Here's what happens if you try to do that:

![image](https://user-images.githubusercontent.com/26527405/206247306-0fb32e07-8434-44a2-a379-479640ece2d1.png)

This is however, necessary in some situations. For example, you might want to configure [CSP](https://kit.svelte.dev/docs/configuration#csp) based on certain environment variables, or at least you might want to configure it differently based on whether the app is in prod or dev mode. Consider the following example:

```js
import adapter from '@sveltejs/adapter-node';
import preprocess from 'svelte-preprocess';
import { ALLOW_CSP } from '$env/static/private'

/** @type {import('@sveltejs/kit').Config} */
const config = {
    preprocess: preprocess(),

    kit: {
        adapter: adapter(),
        csp: {
            mode: 'nonce',
            directives: {
                'default-src': ['self', ALLOW_CSP],
            },
        }
    }
};

export default config;
```

`ALLOW_CSP` might be `localhost:*` in dev mode and `*.yourdomain.com` in production. You could have a backend API that listens on another port on `localhost` during development, and becomes a subdomain (e.g. `api.yourdomain.com`) in production.

### Reproduction

Described above.

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 4.65 GB / 6.10 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.101 => 1.0.0-next.101
    @sveltejs/kit: next => 1.0.0-next.570
    svelte: ^3.53.1 => 3.53.1
    vite: ^3.2.4 => 3.2.4
```

### Severity

blocking all usage of SvelteKit

**Comment by aradalvand** [comment]
@bluwy But `process.env` doesn't actually include environment variables defined in `.env` files.

**Comment by bluwy** [comment]
Yeah you could install `dotenv`, or use Vite's exported `loadEnv` function to load the env file. It's not done by default because other tooling like svelte vscode and vite-plugin-svelte only reads `svelte.config.js`, they don't preload the env, hence it's better done yourself if required.
