### ISSUE TITLE
Fail to resolve the path in the project (includes Reproduction concerned with bugs)

### ISSUE THREAD

**Issue by tanaka-naoki-heavisidelab** [sveltejs/kit#7991]
### Describe the bug

According to the vite document, it is possible to import JSON files directly. 
https://ja.vitejs.dev/guide/features.html#json
However, the warning "Cannot find module './data/example.json' or its corresponding type declarations." is displayed. During development it is possible to start the server with this warning, but it is impossible to compile with "npm run build".

### Reproduction

https://stackblitz.com/edit/node-ejx71g

This project is built as followings;
1.Node new
2.delete files to make sveltekit-TS project.
3. $ npm create @svelte-add/kit@latest . -- --with typescript+eslint+prettier
4. $ pnpm i @sveltejs/adapter-node@next -D
5. Update svelte.config.js as "node-adapter"

According to "npm run dev" it is possible to start the server, but a warning "Can not find module..." is displayed.
The page "jsondata" is acceptable of hot-reloaded by change and save the contents in ./data/example.json.
![json_path_missing](https://user-images.githubusercontent.com/93065464/206360158-281968c8-5b90-4392-a8fd-25a533a3c9eb.png)

Then I try "npm run build" and "node bulid/", but fail to compile due to "Could not resolve.."
![fail_to_compile](https://user-images.githubusercontent.com/93065464/206361285-72f203e1-a2a1-4c6f-a581-214ea193f167.png)

### Logs

```Shell
heavisidelab@Heavisidelab-00:~/Documents/VSCode/sveltekit_wasm/wasmapp$ npm run build

> wasmapp@0.0.1 build
> vite build


vite v3.2.5 building for production...
✓ 38 modules transformed.
11:18:32 [vite-plugin-svelte] dom compile done.
package         files     time     avg
wasmapp             3    0.11s  36.7ms
@sveltejs/kit       2   70.0ms  35.0ms

vite v3.2.5 building SSR bundle for production...
✓ 49 modules transformed.
11:18:33 [vite-plugin-svelte] ssr compile done.
package         files     time    avg
wasmapp             3   16.1ms  5.4ms
@sveltejs/kit       2   10.8ms  5.4ms
Could not resolve './data/example.json' from src/routes/jsondata/+page.server.ts
[vite-plugin-svelte-kit] Could not resolve './data/example.json' from src/routes/jsondata/+page.server.ts
error during build:
Error: Could not resolve './data/example.json' from src/routes/jsondata/+page.server.ts
    at error (file:///home/heavisidelab/Documents/VSCode/sveltekit_wasm/wasmapp/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at ModuleLoader.handleResolveId (file:///home/heavisidelab/Documents/VSCode/sveltekit_wasm/wasmapp/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22156:24)
    at file:///home/heavisidelab/Documents/VSCode/sveltekit_wasm/wasmapp/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22119:26
heavisidelab@Heavisidelab-00:~/Documents/VSCode/sveltekit_wasm/wasmapp$
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 7.72 GB / 15.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 107.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/adapter-node: 1.0.0-next.102 => 1.0.0-next.102 
    @sveltejs/kit: next => 1.0.0-next.572 
    svelte: ^3.44.0 => 3.54.0 
    vite: ^3.1.0 => 3.2.5
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
Your path is wrong in the repro that you provided. Any import starting with "./" is relative to the directory your js/ts file is in. 

The build succeeds after I fix that, I don't know why the dev mode loads the page successfully but that sounds like a bug in vite so please report it upstream with the vanilla-js vite template if you can reproduce it with that.
