### ISSUE TITLE
adapter-vercel should not use x-forwarded-proto

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#800]
adapter-vercel is only using x-forwarded-proto so it can construct a valid URL in order to get pathname and searchParams. which seems wholly unnecessary

**Comment by wiesson** [comment]
I think that is going to be fixed in https://github.com/sveltejs/kit/issues/801

**Comment by Conduitry** [comment]
Oh, I didn't realize there was an issue for this. Yeah this is also fixed in #802 along with #801.
