### ISSUE TITLE
Docs code example sidescroll on mobile

### ISSUE THREAD

**Issue by joeldrake** [sveltejs/kit#8032]
### Describe the bug

When browsing the sveltekit docs on mobile I can not sidescroll the code example blocks.

### Reproduction

Go to https://kit.svelte.dev/docs/accessibility#focus-management on an iphone. Try to sidescroll a code example.

### System Info

```Shell
Ios 16.1.1
```

### Severity

annoyance

**Comment by benmccann** [comment]
Even https://kit.svelte.dev/docs/modules#$app-navigation-goto on desktop overflows and can't be read
