### ISSUE TITLE
HTML minifier docs still reference `import { prerendering } from '$app/environment'`

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#8050]
### Describe the bug

https://kit.svelte.dev/docs/migrating#integrations-html-minifier

This needs to be updated to `building`. But more troubling is that this didn't fail the docs build, which is why I opened an issue at all rather than just a PR.

### Reproduction

https://kit.svelte.dev/docs/migrating#integrations-html-minifier

### System Info

```Shell
n/a
```

### Severity

annoyance

**Comment by Conduitry** [comment]
If I import `building`, I do get better mouseover types - it knows that it's a boolean, whereas for `prerendering` all the tooltip says is `import prerendering`. But the build still succeeds with `prerendering`.

Is it possible to make the `declare module '$app/environment'` in `packages/kit/types/ambient.d.ts` treated more strictly?

**Comment by Rich-Harris** [comment]
Found the culprit:

https://github.com/sveltejs/kit/blob/5dc7f9f6a39ee6df0b2fe056eb70086df9218c9b/sites/kit.svelte.dev/src/lib/docs/server/index.js#L145-L149

This seems bad. Gonna try removing it to see what happens

**Comment by jsnimda** [comment]
The updated document, https://kit.svelte.dev/docs/migrating#integrations-html-minifier
It should be `page += html`, right? Otherwise it gives you a blank page.
