### ISSUE TITLE
[docs] clarify that unit tests live in `src` and browser tests in `tests`

### ISSUE THREAD

**Issue by delight** [sveltejs/kit#8052]
### Describe the bug

In the SvelteKit Docs, specifically the [Project structure](https://kit.svelte.dev/docs/project-structure) it states that the tests are supposed to be in `/tests`

```
├ tests/
│ └ [your tests]
```
but the config `vite.config.js` points to src 

```
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}']
	}
```

1 of both should be changed ... easy fix but needs a decission on which path too take. Personally I prefer changing vite.config.js to promote a separation of tests from the app source code.

### Reproduction

create a project with 

pnpm create svelte@next 

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 595.02 MB / 32.00 GB
    Shell: 5.2.12 - /opt/homebrew/bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0.1
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90
    @sveltejs/kit: next => 1.0.0-next.581
    svelte: ^3.54.0 => 3.54.0
    vite: ^4.0.0 => 4.0.0
```

### Severity

annoyance
serious, but I can work around it

### Additional Information

does not give a good impression if something is not working as described in the docs

**Comment by gtm-nayan** [comment]
The test files covered by the glob in vite.config.js are unit tests that are added if you choose the vitest option when creating the project whereas the files inside the top level `tests` directory are for integration tests.

The project structure docs should change to reflect the possibility of both depending on what options chose.
