### ISSUE TITLE
`vite dev` should include `paths.base` in the "Local" url, or `paths.base` shouldn't be used by `vite.dev`

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/kit#8086]
### Describe the problem

if i have `paths.base` specified, the url that `vite dev` outputs is incorrect:
```js
// svelte.config.js
import adapter from '@sveltejs/adapter-node'

const config = {
    kit: {
        adapter: adapter(),
        paths: { base: '/foo' },
    },
}

export default config
```
```
3:08:37 pm [vite] server restarted.

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose 
```
when navigating to `http://localhost:5173/` the following error is displayed:
```
Not found (did you mean /foo/?)
```

### Describe the proposed solution

two possible solutions:

1. include `paths.base` in the url outputted by `vite dev` (assuming it's possible to change)
2. from my understanding, `paths.base` is only relevant on the deployment target, meaning there's no reason for `vite dev` to use it. if this is true, it would probably be better for `vite dev` to just ignore `paths.base` entirely

### Importance

would make my life easier

**Comment by benmccann** [comment]
This has been fixed
