### ISSUE TITLE
Make cache headers configurable for contents of `static`

### ISSUE THREAD

**Issue by Maggi64** [sveltejs/kit#809]
**Describe the bug**
Cache Headers for images in the static folder are set to `public,max-age=0,must-revalidate`. 
This happens even in production builds (`svelte-kit build, svelte-kit start`).

**Logs**
![image](https://user-images.githubusercontent.com/20517052/113208418-128ba200-9272-11eb-9101-cb50454a07b6.png)

**To Reproduce**
Prepared a example repo.
https://github.com/Maggi64/svelte-kit-cache-header-issue

**Expected behavior**
As far as i understand the code, cache headers should be set to immutable.
Am i missing something here?

**Thanks for the great work guys. Keep it up!**
![PixelPepeFedora](https://user-images.githubusercontent.com/20517052/113209073-e0c70b00-9272-11eb-8ba2-51ad63b1da3b.gif)

**Comment by Rich-Harris** [comment]
But the `/wow.jpg` URL _isn't_ immutable; you could change the file. Only the files generated by Vite (the contents of `_app`, with hashes in the filenames) are immutable.

**Comment by Maggi64** [comment]
Makes sense, in sapper you could configure sirv yourself and we treated those images as unchangeable.
Might be a good idea to add a setting to change this behavior.

We have icons that will never change and if we would alter the path.

Thanks for the quick response.

**Comment by samccone** [comment]
> Might be a good idea to add a setting to change this behavior.

Seems like a reasonable dial to expose from the adapter! +1 to this idea.

**Comment by benmccann** [comment]
In Sapper, we accomplished this with `@rollup/plugin-url`: https://github.com/sveltejs/sapper-template/blob/4ddc022fe064d34be9c76653cccb839d3633f9f0/rollup.config.js#L39

I haven't checked how this works in SvelteKit yet, but would you be able to do the same here? I'd hope so since you can include Rollup plugins

**Comment by Rich-Harris** [comment]
You don't need the plugin, Vite already has static asset handling. Importing assets just works. But it doesn't help if you want a stable URL, which is the ask here

**Comment by benmccann** [comment]
Isn't that what the plugin does though is provide you a stable filename / URL?

**Comment by Rich-Harris** [comment]
It gives you a hashed URL, which has stable _contents_. The OP needs the opposite — stable URL, changeable contents.

**Comment by benmccann** [comment]
They said "We have icons that will never change and if we would alter the path" and were also asking for the cache header to be set to `immutable`, so I think they do have stable contents

**Comment by Rich-Harris** [comment]
Apologies, crossed wires (was responding to Sam's suggestion that it be exposed to the adapter). In that case yes the existing behaviour would suffice, but I think it probably _does_ make sense to be able to configure caching on `static` (probably using globs or something)

**Comment by benmccann** [comment]
Yeah, it might. Though I never really needed it with Sapper because when I included `@rollup/plugin-url` it got copied to another directory that had long-lived caching. Also with `adapter-static` it's tricky because it's just building the project. It really seems like you'd need to set it during the deploy process to your CDN which wouldn't really be covered by `adapter-static`

**Comment by helbling** [comment]
I changed the `sirv` call in sappers `src/server.js` as well, like this:
```
    sirv('static', {
        dev,
        setHeaders: (res, pathname, stats) => {
            if (pathname.match(/^\/images\//)) {
                res.setHeader('Access-Control-Allow-Origin', '*');
            }
        }
    }),
```
In my case it was not about caching. There can be all sorts of reasons for wanting some custom header. Another one is setting the MIME type. I suggest deleting the word `cache` in the issue title.

As a user I first tried to use src/hooks.js and was surprised it didn't work (without much thought about the implementation).
Note that the documentaion of the handle function [1] currently starts out with: `This function runs on every request, [..]`.

I'm not sure if it would be feasible to use handle function in adapter-node (and possibly other adapters) for static requests. The adapter would need to make the decision whether to serve a static or dynamic resource inside the handlers render function. Sirv probably takes its requests much earlier.
Besides, different behaviour for different adapters can be confusing.

The straightforward solution for adapter-node itself would be to let users configure their sirv options in svelte.config.js. Would be an easy migration path from sapper. Drawback is that an implementation detail of adapter-node would be exposed in its api. Not sure how important that is.


I thought about a solution for all adapters: route the static requests you wish to override through an endpoint. The static files need to be moved somewhere (i.e. from /images to /_images). The endpoint has some method to get the file. The requests get their header ordinarily through src/hooks.js. Alternatively they can also be set inside the endpoint.
The following to examples demonstrate the concept (`src/routes/images/[image].js`). However, I didn't get the encoding right in both of them..


```
import { promises } from 'fs';

export async function get({ params }) {
    const { image } = params;
    return {
        body: (await promises.readFile(`static/_images/${image}`)).toString('binary') // TODO: fix binary encoding of images!
    }
}
```

```
export async function get({ params }) {
    const { image } = params;
    const response = await fetch(`http://localhost:3000/_images/${image}`);
    return {
        status:  response.status,
        headers: Object.fromEntries(response.headers.entries()),
        body:    await response.text(), // TODO: fix binary encoding of images!
    };
}

```

[1] https://kit.svelte.dev/docs#hooks-handle

**Comment by helbling** [comment]
The problem with the encoding of the endpoint workarounds above is described in #1438.
By setting `content-type: application/octet-stream` the endpoint will serve the correct bytes, but then the correct content-type needs to be overridden again in `hooks.js`. 

The fixed endpoints look like this:
```
import { promises } from 'fs';

export async function get({ params }) {
    const { image } = params;
    return {
        headers: {
            'content-type': 'application/octet-stream', // can be replaced again by src/hooks.js
        },
        body: (await promises.readFile(`static/_images/${image}`)),
    };
}
```

```
export async function get({ params }) {
    const { image } = params;
    const response = await fetch(`http://localhost:3000/_images/${image}`);
    return {
        status:  response.status,
        headers:
        {
            ...Object.fromEntries(response.headers.entries()),
            'content-type': 'application/octet-stream', // can be replaced again by src/hooks.js
        },
        body: new Uint8Array(await response.arrayBuffer()),
    };                                                                                                      |                                      
}
```

**Comment by benmccann** [comment]
This issue thread is pretty messy and talking about a couple different things. Mostly I think it's asking for better defaults, which were provided in https://github.com/sveltejs/kit/pull/1416, so I'm going to close this. It's also somewhat asking for configurable headers perhaps (that's what the title is), but it's a bit unclear and muddled. It'd be better to file a new issue if anyone wants that
