### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by netcodedev** [sveltejs/kit#8099]
### Describe the bug

When switching to one specific route (/profile) I get the following error even if the +page.svelte is completely empty:
```
SyntaxError: Unexpected end of JSON input
    at load_data (client.js?t=1670859539762&v=f1f07156:1712:25)
    at async load_route (client.js?t=1670859539762&v=f1f07156:791:19)
    at async update (client.js?t=1670859539762&v=f1f07156:263:38)
    at async navigate (client.js?t=1670859539762&v=f1f07156:1134:3)
```

### Reproduction

[Linux] [Node 16.x]
1. clone repository `git clone https://github.com/DataManagementLab/ThesisPortal.git`
2. navigate into cloned repository `cd ThesisPortal`
3. switch branch to `minimal`: `git checkout minimal`

4. install `npm i`
5. start `npm run dev`
6. Goto `http://localhost:5173`
7. Click the `profile` link in the top right corner

### Logs

```Shell
SyntaxError: Unexpected end of JSON input
    at load_data (client.js?t=1670859539762&v=f1f07156:1712:25)
    at async load_route (client.js?t=1670859539762&v=f1f07156:791:19)
    at async update (client.js?t=1670859539762&v=f1f07156:263:38)
    at async navigate (client.js?t=1670859539762&v=f1f07156:1134:3)
```

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 25.03 GB / 31.07 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    npm: 9.1.1 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 107.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/adapter-node: next => 1.0.0-next.102 
    @sveltejs/kit: next => 1.0.0-next.571 
    svelte: ^3.53.1 => 3.53.1 
    vite: ^3.2.5 => 3.2.5
```

### Severity

blocking all usage of SvelteKit

**Comment by dominikg** [comment]
We are not going to curl pipe something. Please provide a self-contained minimal reproduction repository or stackblitz

**Comment by netcodedev** [comment]
Alright i added a branch which does not require a started database. `git checkout minimal` after cloning

**Comment by dominikg** [comment]
going to https://stackblitz.com/github/DataManagementLab/ThesisPortal/tree/minimal?file=src%2Froutes%2Fprofile%2F%2Bpage.svelte  and clicking on `profile` results in two boxes showing 

![image](https://user-images.githubusercontent.com/611613/207108520-9d43d937-3cae-4388-b84a-b11688409bea.png)

and nothing like the error message you posted above.

Sorry to be so strict about this but we need a _minimal_ reproduction. 
If you need general help why something isn't working or how to provide this, please use discord chat #questions @ https://svelte.dev/chat  or github discussions in this repo.

**Comment by netcodedev** [comment]
That is very weird... I'm going to investigate that further and come back

**Comment by netcodedev** [comment]
apparently, deleting the project and cloning it again fixed the issue for whatever reason...
