### ISSUE TITLE
Unexpected error calling unavailable route /users  

### ISSUE THREAD

**Issue by aheinzer** [sveltejs/kit#8117]
### Describe the bug

Although the route /users does not exist, you get an unexpected error when this route is called. I would expect a 404 error page.

### Reproduction

Create new SvelteKit app:                                                                                                                                       

```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```

and call http://localhost:5173/users

Now you get the following error (instead of 404):

```
[vite] Internal server error: Failed to resolve entry for package "/users". The package may have incorrect main/module/exports specified in its package.json
  2       at packageEntryFailure (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:22938:11)
  3       at resolvePackageEntry (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:22935:5)
  4       at tryResolveFile (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:22547:38)
  5       at tryFsResolve (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:22532:16)
  6       at Context.resolveId (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:22404:24)
  7       at Object.resolveId (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:42496:46)
  8       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  9       at async ModuleGraph.resolveUrl (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:61862:26)
 10       at async ModuleGraph.getModuleByUrl (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:61734:23)
 11       at async doTransform (file:///Users/john/my-app/node_modules/vite/dist/node/chunks/dep-2285ba4f.js:40292:20) (x2)
```

### System Info

```Shell
System:
  OS: macOS 13.0.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 3.57 GB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 19.0.0 - /usr/local/bin/node
  npm: 8.19.2 - /usr/local/bin/npm
Browsers:
  Chrome: 108.0.5359.98
  Firefox: 105.0.1
  Safari: 16.1
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.90
  @sveltejs/kit: next => 1.0.0-next.584
  svelte: ^3.54.0 => 3.54.0
  vite: ^4.0.0 => 4.0.1
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I can't reproduce this. I get the 404 I would expect.

**Comment by aheinzer** [comment]
I tried to reproduce it on another machine, there I get a 404 as well.

It seems that I have only this error on my MacBook. I tried the following, but all of them could not fix the error on my machine:

- test with different browsers (Safari, Firefox, Chrome)
- delete of browser cache
- delete `node_modules` and `.svelte-kit` folder and install dependencies again by `node install`
- delete global `node_modules` dir and reinstall Node.js and npm
- machine reboot

At the moment, I have no idea why I am getting this error and what else I could try.

**Comment by aheinzer** [comment]
I also get the same error when I create a standard vite project with framework vanilla using `npm create vite@latest`.

This proves that it is not a SvelteKit error, so I am closing this ticket.

I will investigate further and open a ticket on Vite if necessary. If so, I will link the ticket here.
