### ISSUE TITLE
`npm run dev --host` doesn't host app on network

### ISSUE THREAD

**Issue by vinliao** [sveltejs/kit#8119]
### Describe the bug

The `--host` args is used to host app on the network. It doesn't work on the latest SvelteKit install. `npx vite dev --host` is fine, and that suggest to me it might be a SvelteKit issue.

### Reproduction

1. `npm create svelte@latest my-app`
2. `cd my-app`
3. `npm i`
4. `npm run dev --host`
![Screenshot from 2022-12-13 20-48-50](https://user-images.githubusercontent.com/34117807/207346832-bc0fff4e-6326-4937-b0a7-8e32e1488ea5.png)
![Screenshot from 2022-12-13 20-49-12](https://user-images.githubusercontent.com/34117807/207346939-f2aa932e-bacf-48a7-94bb-cebbde6df0fc.png)

### System Info

```Shell
System:
    OS: Linux 6.0 Fedora Linux 37 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 12.78 GB / 15.37 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 3.3.0 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 107.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.90 
    @sveltejs/kit: next => 1.0.0-next.585 
    svelte: ^3.54.0 => 3.54.0 
    vite: ^4.0.0 => 4.0.1
```

### Severity

annoyance

**Comment by Conduitry** [comment]
As with all `npm run` commands, you need to insert a `--` to separate flags for npm from flags for the script it's calling. You want `npm run dev -- --host`, otherwise you're passing `--host` to `npm`.
