### ISSUE TITLE
Generate types for `src/service-worker.js`

### ISSUE THREAD

**Issue by kwangure** [sveltejs/kit#8127]
### Describe the problem

At present you need to add types for the service worker to clue TypeScript in about the `WebWorker` scope and set `self` to `ServiceWorkerGlobalScope`.

### Describe the proposed solution

SvelteKit should generate types into the types folder.

### Alternatives considered

Writing my own types. It typically involves adding triple-slash directives in my `src/service-worker.js`.

```javascript
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

self.addEventListener('install', (event) => {
	/** @type {ExtendableEvent} */ (event).SpecialServiceWorkerStuff
```
And creating `src/service-worker.d.ts`
```javascript
declare const self: ServiceWorkerGlobalScope;
```

### Importance

nice to have

### Additional Information

TS Context: https://github.com/microsoft/TypeScript/issues/14877.

**Comment by dummdidumm** [comment]
We can't generate such types into the types folder because they still need to be manually referenced inside `service-worker.js`, and at the same time it needs to be made sure that those types are not loaded anywhere else, since the `no-default-lib` instruction effectively removes theses type definitions from the rest of the project, which is undesireable. I think we should instead document this pattern and adjust our generated `tsconfig.json` to `exclude` the service worker file, so it doesn't interfere with the rest of the project.

**Comment by jdgamble555** [comment]
The problem with this is that if you import anything inside the `/src/service-worker` folder, it won't find things like `$lib` etc.

**Comment by vadimmos** [comment]
Is there any progress on this issue? Are developers still doomed to write ServiceWorker code with one eye on the documentation, without the ability to rely on autocompletion and type checking tools?

**Comment by teemingc** [comment]
The docs have an example on how to enable type checking for the service worker https://svelte.dev/docs/kit/service-workers#Inside-the-service-worker

**Comment by balthild** [comment]
I got this error when using the code in the docs:

```ts
const self = globalThis.self as unknown as ServiceWorkerGlobalScope;
```

```
Cannot redeclare block-scoped variable 'self'. ts(2451)
lib.dom.d.ts(43605, 13): 'self' was also declared here.
lib.webworker.d.ts(14918, 13): and here.
```

**Comment by teemingc** [comment]
> I got this error when using the code in the docs:
> 
> const self = globalThis.self as unknown as ServiceWorkerGlobalScope;
> ```
> Cannot redeclare block-scoped variable 'self'. ts(2451)
> lib.dom.d.ts(43605, 13): 'self' was also declared here.
> lib.webworker.d.ts(14918, 13): and here.
> ```

Can you open a new issue? I suspect the example has issues with typescript 6

EDIT: I can't reproduce this on a new kit project so you'll have to provide a minimal reproduction too
