### ISSUE TITLE
[node-adapter] Expose a way to change `sirv` options

### ISSUE THREAD

**Issue by ahhshm** [sveltejs/kit#8130]
### Describe the problem

I would like to let my nginx server handle gzip compression and etag generation but I can't because all `sirv` options are hard-coded in the node adapter:
‍‍‍‍‍‍
```ts
sirv(path, {
	etag: true,
	gzip: true,
	brotli: true,
})
```

### Describe the proposed solution

Expose a way to change `sirv` configuration. Maybe something like this:
```ts
// svelte.config.js
const config = {
  kit: {
    adapter: adapter({ sirv: { gzip: false, etag: false, brotli: false } }),
  },
};
```

### Importance

would make my life easier

**Comment by Conduitry** [comment]
I'd be against doing this. If users want more control over the server, there's already a feature where you bring your own and you just use SvelteKit as middleware or a request handler.

The `gzip` option doesn't actually perform any gzipping anyway - it just will server `.gz` versions of files if they already exist on disk. If we expose these options in SvelteKit, we're also opening ourselves up to support questions about how to use specific `sirv` options for specific results.

We also might want to completely replace `sirv` with another library at some point. Doing that would become a breaking change if we exposed these options.

**Comment by ahhshm** [comment]
Totally understandable. 

But my back-end guy says that our nginx server should handle the ETag generation and we don't want SvelteKit to add ETag header. What's the best way to disable that? 

I can build a [custom server](https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server) but according to your example I have to use the handler anyway and the handler uses `sirv` which adds Etag header to the response. 

If I don't want to use the handler, I assume I have to configure a server myself and I don't like that because **I want** all SvelteKit server functionalities expect etag generation.

Maybe it's a problem with our setup. I'm not a back-end guy.
