### ISSUE TITLE
Prevent scrolling animation on route change

### ISSUE THREAD

**Issue by DhyeyMoliya** [sveltejs/kit#814]
**Is your feature request related to a problem? Please describe.**
Scrolling animation on route change is some times beautiful and sometimes feels unreal(different then classic/regular UX).

**Describe the solution you'd like**
Can we pass some option somewhere, to disable it like `sveltekit:noscrollanimation` or something shorter. 🧐

**Describe alternatives you've considered**
I tried `sveltekit:noscroll`, but it completely disables scroll, as it is meant to. 😀

**How important is this feature to you?**
As websites developer, I should be able to control the UX patterns.

**Additional context**
None

**Comment by PatrickG** [comment]
svelte/kit does not make a "scrolling animation".
Maybe you have changed the scroll behavior somewhere in your styles?
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

**Comment by DhyeyMoliya** [comment]
Ohh, I have added bootstrap. Maybe that is causing this behaviour, I will check it. Thanks @PatrickG

**Comment by DhyeyMoliya** [comment]
I am closing this issue as this is not related to SvelteKit, smooth scrolling was added by Bootstrap. Thanks @PatrickG for pointing it out.
