### ISSUE TITLE
Experimental inspector throws `The editor process exited with an error: (code 1).`

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#8179]
### Describe the bug

After initializing a fresh skeleton project, and enabling the experimental inspector as shown in Rich's vite conference video https://www.youtube.com/watch?v=-OMPfr56kXI the logs/error below gets thrown when I click on an element after hitting cntrl+shift.

### Reproduction

not relevant, or if you really want one, simply `npm init svelte@next` -> skeleton template -> yes to all additional things like typescript etc.

### Logs

```Shell
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Could not open +page.svelte in the editor.
The editor process exited with an error: (code 1).
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 2.23 GB / 15.75 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.0 => 1.0.0
    svelte: ^3.55.0 => 3.55.0
    vite: ^4.0.1 => 4.0.1
```

### Severity

annoyance

### Additional Information

I run commands in a directory on my second partition with label `P`.

**Comment by dominikg** [comment]
upstream issue https://github.com/yyx990803/launch-editor/issues/35
