### ISSUE TITLE
Better error message for: `Unexpected option config.kit.vite`

### ISSUE THREAD

**Issue by LeoDog896** [sveltejs/kit#8207]
### Describe the problem

Older blogs use `config.kit.vite` when creating custom plugins (usually for server hooks), and the removal of this ends up having small reprecussions.

### Describe the proposed solution

A small error message that says something similar to "Hint: The Vite config has been moved over to vite.config.??"

### Importance

nice to have

**Comment by Conduitry** [comment]
A more helpful error message for this, along with many many other things, was removed in #8019. We don't want to be bogged down by these. As is mentioned in the 1.0 blog post (https://svelte.dev/blog/announcing-sveltekit-1.0) and migration guide (#5774) there is a version just before all of these helpful errors were removed that you can upgrade to to help you migrate. I don't think this particular bit of migration deserves special treatment.

**Comment by alexmorrise** [comment]
I appreciate finding this issue because I was following an older blog and couldn't figure out why the plugins were being ignored.
