### ISSUE TITLE
Support hook per glob

### ISSUE THREAD

**Issue by omar2205** [sveltejs/kit#8214]
### Describe the problem

This is a basic example for hooks from the docs

```ts
src/hooks.server.ts
import type { Handle } from '@sveltejs/kit';
 
export const handle = (async ({ event, resolve }) => {
  if (event.url.pathname.startsWith('/custom')) {
    return new Response('custom response');
  }
 
  const response = await resolve(event);
  return response;
}) satisfies Handle;
```

We have to do path parsing like `event.url.pathname.startsWith` to do certain things when a user visits a certain path.

### Describe the proposed solution

It would be helpful to have an array of path glob and a hook/handle function to execute, like:
```ts
import { checkAuth } from '$lib/server/utils'

export const handles = [
  { path: '/admin/*', handler: checkAuth }
]
```

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
This is something you can write yourself using the `sequence` helper. Rough code (haven't tested this):

```js
import { sequence } from '@sveltejs/kit';

export function globHandlers(handlers) {
  const result = handlers.map(handler => {
    return ({ event, resolve }) => {
      if (someGlobbingLibraryToCheckIfMatches(handler.path)) {
        return handler.handler({ event, resolve });
      } else {
       return resolve(event);
      }
   });
  return sequence(result);
}
```

Closing as this can be done in userland.
