### ISSUE TITLE
add routing.js to exports to create custom routing

### ISSUE THREAD

**Issue by mavthedev** [sveltejs/kit#8221]
### Describe the problem

I've always wanted to make my own custom routing files but frustrated when I cant import the [`utils/routing.js`](https://github.com/sveltejs/kit/blob/master/packages/kit/src/utils/routing.js) from sveltekit and I have to implement my own route to regex method or copy the code and add it to my own code whenever the original file updates.`

### Describe the proposed solution

Export all files in utils folder

### Alternatives considered

Just export [`utils/routing.js`](https://github.com/sveltejs/kit/blob/master/packages/kit/src/utils/routing.js) as './routing'

### Importance

would make my life easier

**Comment by david-plugge** [comment]
I think there was an issue about extracting the router into its own package. That could solve your issue.

**Comment by dummdidumm** [comment]
I don't fully understand the feature request. What do you my by "my own custom routing files"? Do you want to opt out of the file-system based routing and have the ability to configure what routes load at which point yourself manually through some configuration file?

**Comment by mavthedev** [comment]
I mean custom routing files as in my own _hooks.ts files (https://github.com/sveltejs/kit/discussions/8007)

**Comment by mavthedev** [comment]
@dummdidumm

**Comment by Rich-Harris** [comment]
I still have no idea what this feature request is. Please explain it in simple, concrete terms, ideally with specific examples.

**Comment by mavthedev** [comment]
@Rich-Harris I want to be able to use the functions exported by routing.js so that I can parse routes the same way that sveltekit does. In this case, I want to import all files in my routes folder named _hooks.ts/js, then use `parse_route_id` from routing.js and create a list of hooks, import them in hooks.server.ts and check if the URL matches the Regex using `exec`

**Comment by Rich-Harris** [comment]
closing this as there's nothing actionable
