### ISSUE TITLE
Platform is undefined in dev mode

### ISSUE THREAD

**Issue by chrskerr** [sveltejs/kit#8230]
### Describe the bug

In the docs ([here](https://kit.svelte.dev/docs/types#app)) the default type for Platform is `{}`, but in dev it is coming through as undefined.

This makes type safety harder, since TS doesn't enforce an is-object check before attempting to access properties. 

My preference would like to default Platform to an empty object, rather than updating the type to allow undefined. 

This is an issue for us since adapter-node will only apply during production builds and as such during dev the Platform object is undefined.

### Reproduction

Open repo https://github.com/chrskerr/sveltekit-platform-demo, and start in dev mode

Open the app in any browser, and you'll see 'undefined' printed into the terminal as the result of `console.log(typeof event.platform)` from hooks.server.ts

VSCode believes the type of event.platform to be Readonly<Platform> or Readonly<{}>, meaning the below fails TS because 'something' doesn't exist on event.platform (correct) but it doesn't catch that event.platform is maybe undefined 

<img width="898" alt="Screenshot 2022-12-20 at 11 50 20 am" src="https://user-images.githubusercontent.com/10432093/208562388-f9d8768f-2c97-4284-b7bf-ac10489df103.png">

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 266.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/adapter-node: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.2
```

### Severity

annoyance

**Comment by paukuman** [comment]
alternative, using a `npm run pages:preview`
