### ISSUE TITLE
Video player persists state between pages

### ISSUE THREAD

**Issue by jinyus** [sveltejs/kit#8231]
### Describe the bug

Title explains it, even when setting a different source, the html is updated but the player just keeps playing the old video when navigating to other pages.

### Reproduction

https://github.com/jinyus/sveltekit-video-bug

live demo: https://svelte-video-bug.surge.sh

### System Info

```Shell
System:
    OS: Linux 6.0 undefined
    CPU: (16) x64 AMD Ryzen 7 PRO 6850U with Radeon Graphics
    Memory: 17.69 GB / 30.13 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.3.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 108.0.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

https://user-images.githubusercontent.com/30532952/208563955-ab613843-fcf1-42bb-94b9-5b6ba2f27cee.mp4

**Comment by dirthsj** [comment]
The HTML5 specification specifically state that changing a video source element's attributes will have no effect. I'm not sure what sveltekit could do differently; you've just instructed it to do something that can't work.

**Comment by jinyus** [comment]
> The HTML5 specification specifically states that changing a video source element's attributes will have no effect. I'm not sure what sveltekit could do differently; you've just instructed it to do something that can't work.

That's not the main issue, the player state persists when navigating between pages. I start a video, navigate to a different page with a different video but the old video is still playing on the new page.
