### ISSUE TITLE
svelte.config.js base paths don't work with %20 escape

### ISSUE THREAD

**Issue by chipnetics** [sveltejs/kit#8233]
### Describe the bug

When configuring the kit base paths with %20 escapes for web addresses with spaces, the pre-rendering fails (using @sveltejs/adapter-static)

```ts
const config = {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter({
			pages: 'build',
			assets: 'build',
			fallback: '200.html',
		}),
		paths: {
			base: dev ? "" : "/sites/something%20with%20spaces/build",
		},
	},
};
```

Instead you must replace %20 with spaces... such as `/sites/something with spaces/build`

### Reproduction

Unfortunately corporate code, but easy to reproduce with any svelte kit project with a base path containing spaces.

### System Info

```Shell
System:
    OS: Linux 5.18 Debian GNU/Linux bookworm/sid
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 51.70 GB / 62.53 GB
    Container: Yes
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 18.10.0 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
I'm inclined to say this works as expected and consider it a feature that escaping is done for your so you don't have to do it yourself. Leaving this open for others to express their opinion.

**Comment by chipnetics** [comment]
Somewhat fair and probably not too common. Though personally I did sink nearly 4 hours until realizing this was what was causing the prerendering fail... Luckily the 404 message was bit of a clue.

My network path was nested under 5 directories with spaces so I naturally just copy and pasted it from the URL which was already escaped with %20 in the address. 🤷‍♂️

**Comment by benmccann** [comment]
yeah, this is working as intended
