### ISSUE TITLE
type error at +page.ts

### ISSUE THREAD

**Issue by taishi55** [sveltejs/kit#8234]
### Describe the bug

PageLoad not found

`Module '"./$types"' has no exported member 'PageLoad'`

### Reproduction

create `+page.ts`

paste the following
```
import type { PageLoad } from './$types';
export const prerender = true;
 
export const load = (async ({ fetch }) => {
  const res = await fetch('/my-server-route.json');
  return await res.json();
}) satisfies PageLoad;
```

### System Info

```Shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 92.25 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.2
```

### Severity

annoyance

### Additional Information

https://stackoverflow.com/questions/74469661/sveltekit-pageload-module-not-found

this didn't work for me

**Comment by taishi55** [comment]
it worked after `npm install` again. Not sure what caused this.

**Comment by gtm-nayan** [comment]
The types aren't gonna be there if you don't see a .svelte-kit folder, which is either:
1. Generated automatically if you're running the dev server
2. Generated manually by running the `npx svelte-kit sync` command

If you did either of those and still ran into the issue then please provide a proper reproduction and we'll reopen it.
