### ISSUE TITLE
Sapper's process.browser or something similar

### ISSUE THREAD

**Issue by MirrorBytes** [sveltejs/kit#824]
**Is your feature request related to a problem? Please describe.**
Yes and no. It would be nice to have persistence for something like forms, and wrapping writable stores is an easy and efficient solution to achieve this:

```typescript
export function local<T extends IndexableJsonValue>(key: string, initial: T): Writable<T> {
	const toString = (value: T) => JSON.stringify(value, null, 2); // helper function
	const toObj = JSON.parse; // helper function

	if (localStorage) {
		if (localStorage.getItem(key) === null) {
			localStorage.setItem(key, toString(initial));
		}

		const saved: T = toObj(localStorage.getItem(key) || '');

		const store = writable<T>(saved);

		return {
			subscribe: store.subscribe,
			set: (value: T) => {
				localStorage.setItem(key, toString(value));

				store.set(value);
			},
			update: (fn: (value: T) => T) => {
				store.update((val: T) => {
					const newVal = fn(val);

					localStorage.setItem(key, toString(newVal));

					return newVal;
				});
			}
		};
	}

	return writable(initial);
}
```

**Describe the solution you'd like**
It would be nice to have access to localStorage (and other browser only features) and SSR. Sapper's `process.browser` was a workaround that allowed this sort of functionality.

**Describe alternatives you've considered**
Not using localStorage, but that would cause UX to suffer.

**How important is this feature to you?**
Quite. I'm working on a project that's central focus is forms and data entry, and persistence is key. Storing this kind of information in a local store on the server is inefficient, overkill, and completely unnecessary for this.

**Comment by CaptainCodeman** [comment]
Try
```
import { browser } from '$app/env'
```

See docs: https://kit.svelte.dev/docs#modules-app-env

**Comment by MirrorBytes** [comment]
I somehow completely missed this when reading the docs. Thank you.
