### ISSUE TITLE
csr breaks "a" link elements contained inside an "svg" element

### ISSUE THREAD

**Issue by peufo** [sveltejs/kit#8242]
### Describe the bug

When client-side rendering is enabled, links inside an Svg component disappear.
Still, no problem if a native svg element is used.

### Reproduction

See: [https://github.com/peufo/kit-bug-report-link-svg](https://github.com/peufo/kit-bug-report-link-svg)
or 
1. Make sure csr is enabled (default)
2. Create a simple SVG component "Svg.svelte"

```svelte
<svg
  viewBox="0 0 100 100"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
>
  <slot />
</svg>
```

3. Use it with links inside
```svelte
<script>
  import Svg from './Svg.svelte'
</script>
<Svg>
  <a href="/42">
    <text x="50" y="90" text-anchor="middle"> test link </text>
  </a>
</Svg>
```

### System Info

```Shell
System:
    OS: Linux 5.10 Kali GNU/Linux Rolling 2022.3
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 5.02 GB / 7.53 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.0 => 1.0.1
    svelte: ^3.54.0 => 3.55.0
    vite: ^4.0.0 => 4.0.2
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Seems like a Svelte "bug" instead, see https://svelte.dev/repl/8c9bb576f1f348a3953f391a9e90a27f?version=3.55.0

For the `a` inside the SVG tag, the compiler identifies it as an SVG anchor and uses `svg_element` to create it, whereas for the slotted one the compiler has no way of knowing it's inside an SVG so it just creates a normal anchor element which doesn't work the same way

**Comment by peufo** [comment]
Well seen,

This opened issue already exists in the svelte project, I missed it: [/sveltejs/svelte/issues/7807](https://github.com/sveltejs/svelte/issues/7807)

Thanks for the explanation, I close this one.

**Comment by peufo** [comment]
@gtm-nayan Mea culpa! Svelte provides a "namespace" option to signal to the compiler the context of a component:

```svelte
<svelte:options namespace="svg"/>
```

see [https://svelte.dev/repl/a4a6543ca9fb405da054b87ab198f728?version=3.55.0](https://svelte.dev/repl/a4a6543ca9fb405da054b87ab198f728?version=3.55.0)
