### ISSUE TITLE
Export resolved Svelte config for use by plugins

### ISSUE THREAD

**Issue by hedgehog125** [sveltejs/kit#8243]
### Describe the problem

I'm making a service worker plugin specifically for SvelteKit with the static adapter, and I'm currently having to rely on a hacky solution to get the SvelteKit config (importing a module that's used internally by SvelteKit (src/core/config.index.js) ). I need the config in order to get the build directory, as well as check a few settings to make sure that they're compatible with the plugin.

I could import the config file myself, but the problem is that I'd then have to hard-code all the defaults in. 

### Describe the proposed solution

I think it would be best to add the resolved Svelte config (complete with defaults, like what the internal module returns from load_config) to viteConfig.define, but it could also be in viteConfig.plugins like vite-plugin-svelte's API property.

### Alternatives considered

There are a few other ways it could be exposed, but I don't think they'd be better.

### Importance

nice to have

**Comment by benmccann** [comment]
Before you build a new plugin, I wanted to make sure you have seen https://github.com/vite-pwa/sveltekit

**Comment by hedgehog125** [comment]
Yeah, I should have another look at it since it wasn't ready when I first had a look at it. But I'm finding it interesting learning how to make Vite plugins, and I also want it to do things a bit differently by having my plugin generate a list of changed files so it doesn't need to redownload as many files. The developers of that plugin might also benefit from this feature.

**Comment by hedgehog125** [comment]
Hmm, I forgot the build directory is specified in the arguments to the adapter function. It's still useful to have the other config, but I wonder what can be done about that. I suppose each adapter could expose its arguments itself, but that's not ideal since some adapters might not do that. Maybe that's a separate issue

I can still work around it, but it would be nice to not have to worry about defaults and making sure the build directory is the same for both functions.

**Comment by Rich-Harris** [comment]
The resolved config is already available to adapters:

```js
// svelte.config.js
export default {
  kit: {
    adapter: {
      name: 'my-adapter',
      adapt: (builder) => {
        console.log(builder.config);
        // ...
      }
    }
  }
};
```

Is that sufficient? To be honest I don't really understand what you're trying to do — can you explain it in concrete terms?

**Comment by hedgehog125** [comment]
@Rich-Harris good point. That's probably a better approach for this since the plugin is SvelteKit specific anyway. Presumably I can just initialise the static adapter from within my custom one and then call its adapt between my own logic method myself.

I was trying to make a Vite service worker plugin specifically for SvelteKit since the way it builds to the .svelte-kit folder complicates things a little. I needed the SvelteKit config for a couple of checks and to handle the base URL (I think the Vite one was always "./"?). But yeah, I think an adapter makes more sense.

Out of interest though, there's an "api" property on the "vite-plugin-svelte" plugin in the viteConfig.plugins. What's that intended to be used for? Since it's not documented as far as I can tell, and its only property: "options", changed a bit before 1.0 released.

**Comment by benmccann** [comment]
Yes, `./` is used to make the base always relative

I'm not familiar with the `api` property, but there's nothing we currently intend to have exposed or used externally

**Comment by hedgehog125** [comment]
Ah ok. Thanks for both of your input. I'll close as completed
