### ISSUE TITLE
split option in cloudflare-adapter

### ISSUE THREAD

**Issue by LoaiDev** [sveltejs/kit#8249]
### Describe the problem

it would be beneficial to have the option to split routes ito individual functions just like the split function in vercel-adapter. This would have the advantage that static files and pre rendered pages wouldn't be handled by a function but with cloudflare directly using less quota. I don't know if it will affect performace in any way.

### Describe the proposed solution

have a `split` option to the adapter just like the vercel adapter to create individual routes

### Importance

would make my life easier

**Comment by samuba** [comment]
Another huge benefit: You can get around the 1MB file size limit for workers.
Right now it is impossible to deploy to cloudflare if you have e.g. a route with a heavy dependency

**Comment by Rich-Harris** [comment]
Unfortunately Cloudflare Pages just doesn't work that way AFAIK. You can split your functions up, but as soon as you deploy them they will get bundled back into a single worker. 

As for static files and prerendered pages, they can in theory be included in `_routes.json` (support for which was added in https://github.com/sveltejs/kit/pull/6530), but there's a limit to the number of entries you can have in that file and there was a concern about including everything, so some things have to be served via a function. @jrf0110 would know more!
