### ISSUE TITLE
Sveltekit generated project using typescript has vite.config.js file instead of ts

### ISSUE THREAD

**Issue by thebspin** [sveltejs/kit#8257]
### Describe the bug

When generating a typescript project (skeleton) it gets me a vite.config.js file instead of .ts like it used to do in the past.
Playwright for example does has it's .ts file for it's config.

### Reproduction

Generate a new typescript skeleton project, with all the options on yes (playwright, vitest, prettier and eslint).

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.98 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/Library/Caches/fnm_multishells/7782_1671956111960/bin/node
    npm: 8.15.0 - ~/Library/Caches/fnm_multishells/7782_1671956111960/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox Developer Edition: 106.0
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
Is `vite.config.ts` even supported? I can't find reference to it in their docs.

**Comment by dominikg** [comment]
yes it is, https://vitejs.dev/config/ 

> Vite also directly supports TS config files. You can use vite.config.ts with the defineConfig helper as well.

**Comment by tcc-sejohnson** [comment]
So weird -- I even went to that page and Ctrl+F-ed for `vite.config.ts`! Thanks... 🙃

**Comment by aradalvand** [comment]
Doesn't #8258 implement this? Shouldn't it be closed?

**Comment by dummdidumm** [comment]
Thank you for noticing, closing
