### ISSUE TITLE
explain status codes for 'fail' and 'redirect' functions in documentation

### ISSUE THREAD

**Issue by bobbymannino** [sveltejs/kit#8264]
### Describe the problem

you have set typed status codes for both but I cannot figure out what they mean or why they are what they are, explaining in docs would be useful

### Describe the proposed solution

see above

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Maybe we could have a link to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status somewhere, but I don't think we ought to be doing more than that. These status codes have been around a very long time and are very well-documented online.
