### ISSUE TITLE
Production build import error

### ISSUE THREAD

**Issue by sproott** [sveltejs/kit#8267]
### Describe the bug

I'm trying to make a production build of a SvelteKit app that's using [Quirrel](https://quirrel.dev/). It works properly in a dev build, but crashes during the production build.

The .mjs file in the `quirrel` library just reexports everything from dist/cjs/src/sveltekit.js, which has regular named exports (see the file structure at https://www.npmjs.com/package/quirrel?activeTab=explore). So everything should, in theory, work.

Instead, it throws an error saying that `The requested module 'quirrel/sveltekit.mjs' does not provide an export named 'Queue'`, even though it should. This can be fixed by explicitly importing the .js or .cjs file, but I don't think this should be necessary.

For more information, see the [original issue](https://github.com/quirrel-dev/quirrel/issues/1111) I posted in quirrel's repo.

### Reproduction

https://github.com/sproott/quirrel-sveltekit-build-bug

### Logs

```Shell
import { Queue } from "quirrel/sveltekit.mjs";
         ^^^^^
SyntaxError: The requested module 'quirrel/sveltekit.mjs' does not provide an export named 'Queue'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async prerender (file:///home/username/temp/quirrel-sveltekit-build-bug/node_modules/@sveltejs/kit/src/core/prerender/prerender.js:355:16)
[vite-plugin-sveltekit-compile] Prerendering failed with code 1
error during build:
Error: Prerendering failed with code 1
    at ChildProcess.<anonymous> (file:///home/username/temp/quirrel-sveltekit-build-bug/node_modules/@sveltejs/kit/src/exports/vite/index.js:551:15)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

### System Info

```Shell
System:
    OS: Linux 6.0 Arch Linux
    CPU: (12) x64 AMD Ryzen 5 5500U with Radeon Graphics
    Memory: 9.26 GB / 14.98 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chromium: 108.0.5359.124
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.91 => 1.0.0-next.91
    @sveltejs/kit: ^1.0.0-next.589 => 1.0.0-next.589
    svelte: ^3.55.0 => 3.55.0
    vite: ^4.0.3 => 4.0.3
```

### Severity

serious, but I can work around it

**Comment by bluwy** [comment]
> The .mjs file in the `quirrel` library just reexports everything from dist/cjs/src/sveltekit.js, which has regular named exports (see the file structure at https://www.npmjs.com/package/quirrel?activeTab=explore). So everything should, in theory, work.

It looks like it re-exports `./dist/esm/src/sveltekit.js` instead. The issue though is that `./dist/esm/src/sveltekit.js` is still treated as CJS by node because it doesn't use the `.mjs` extension, and the closest package.json doesn't have `"type": "module"`. An easy fix is to do the latter [here](https://cdn.jsdelivr.net/npm/quirrel@1.13.1/dist/esm/package.json).

Closing as this is Node behaviour.
