### ISSUE TITLE
Make global declaration the default

### ISSUE THREAD

**Issue by CaptainCodeman** [sveltejs/kit#8276]
### Describe the problem

Seems like every day someone will have an issue with [trying to import types in `src/app.d.ts`](https://kit.svelte.dev/docs/types#app)

### Describe the proposed solution

Why not make the `declare global {` version the default?

### Importance

nice to have

**Comment by dummdidumm** [comment]
IIRC declare global only works if there is an import in the file

**Comment by CaptainCodeman** [comment]
Ah, I was wondering what I must be missing

Adding something to force it to be a module might be confusing, although it may still help, e.g.:

```ts
// See https://kit.svelte.dev/docs/types#app
// for information about these interfaces
// and what to do when importing types
declare global {
  namespace App {
    interface Locals {
      name: string
    }
    // interface PageData {}
    // interface Error {}
    // interface Platform {}
  }
}

// this line can be removed if you add an import to this file:
export default undefined;
```
