### ISSUE TITLE
Can't import TS File - Cannot find module X imported from Y

### ISSUE THREAD

**Issue by jdgamble555** [sveltejs/kit#8279]
### Describe the bug

# Code Snippet

**tests/tests.ts**
```javascript
import { expect, test } from '@playwright/test';
import { my_module } from './utils';

test('index page has expected h1', async ({ page }) => {
	console.log(my_module);
	await page.goto('/');
	expect(await page.textContent('h1')).toBe('Welcome to SvelteKit');
});
```

**tests/utils.ts**
```js
export const my_module = 'testing buddy!';
```

**Describe the bug**

I run `npm run test` and I get this error:

```
Error: Cannot find module 'C:\web projects\testing-import\tests\utils' 
imported from C:\web projects\testing-import\tests\test.ts
```

### Reproduction

This is a brand new SvelteKit project with Playwright with the two added TS files:

https://github.com/jdgamble555/testing-import

It seems I can work around it by incorrectly making my "ts" file import a "js" like so:

```js
import { my_module } from './utils.js';
```

However, this is not a `js` file, it is a `ts` file. Apparently I should also be able to get rid of:

```
type: module
```
in `package.json`, but that would break SvelteKit.

### System Info

```Shell
- SvelteKit 1.0
- Windows 11
- Playwright 1.28.1
```

### Severity

annoyance

### Additional Information

Is there any CORRECT way of doing this without breaking SvelteKit? I know lots of people are going to use Playwright with imports.

**Comment by bluwy** [comment]
TypeScript in Playwright is handled entirely by Playwright, so you'd have to add the extensions following [its docs](https://playwright.dev/docs/test-typescript#typescript-with-esm). There's nothing much SvelteKit can do to change it.
