### ISSUE TITLE
API endpoint, called from the server, with cache-header cannot be cleared

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#8286]
### Describe the bug

This is similar to, but different than https://github.com/sveltejs/kit/issues/7784 

I have an api endpoint that looks like this 

```js
export async function GET({ url, setHeaders, request }) {
	console.log('ENDPOINT', x++);

	const search = url.searchParams.get('search') || '';

	setHeaders({
		'cache-control': 'max-age=60',
		Vary: 'todos-cache'
	});
	const todos = await getTodos(search);
	return json(todos);
}
```

This endpoint is called from a SHARED loader. So the first time I view a page, the fetch is called from SvelteKit's internals, on the server. With the cache-control header, as above, these results are cached for 60 seconds. Even a call to invalidate to the api endpoint url does not clear that cached entry. Even adding a depends call in the shared loader, and called invalidate on that does not clear the cached entry. Even manually passing a different value of the header on each call (to test) does not clear the cached entry.

Is this by design? Note that I'm not talking about browser caching. I can already modify the header I'm Vary'ing on (todos-cache) on the client, and successfully clear the cache, which works.

The only workaround I've found is to just not add the cache-control header at all, depending on whether the loader is running client-side, or server-side (which I can surmise by snooping around the headers).

Again, mainly trying to surmise if this is by design. If it is, by all means close this. If not, I'd be happy to whip up a minimal repro. 

### Reproduction

n/a, for now (if this is not by design I'd be happy to make one).

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 151.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 8.18.0 - ~/Documents/node_modules/.bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.1 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Likely a big where the inlined response is reused, not taking into account the Vary header. To keep the implementation simply I'd say we shouldn't keep responses with a vary header cached. This might result in some false negatives but very few people will actually use that header.
