### ISSUE TITLE
Let ParamMatcher functions return a string to redirect 

### ISSUE THREAD

**Issue by darrylyeo** [sveltejs/kit#8289]
### Describe the problem

Routes with parameters don't have an easy way to redirect to a "canonical" route, and param matchers are too strict (invalid routes will just 404).

### Describe the proposed solution

I'd like for param matchers to return either a boolean (the current behavior) or a "canonical" param string which triggers a redirect. For example, if I want my blog slugs to only ever contain lowercase letters:

```ts
// params/isCanonicalSlug.ts

import type { ParamMatcher } from '@sveltejs/kit'

export const match: ParamMatcher = slug =>
    slug === slug.toLowerCase()
        ? true               // slug is valid
        : slug.toLowerCase() // slug is malformed, redirect to this slug instead
```

This way I can just define one route directory with a param matcher `routes/blog/[slug=isCanonicalSlug]` without extra files or custom `load` redirect logic.

### Alternatives considered

Right now to achieve this, I have to implement a conditional redirect like this:

```ts
// routes/blog/[slug]/+layout.ts

import { redirect } from '@sveltejs/kit'
import type { LayoutLoad } from './$types'
 
export const load = (({ params }) => {
    if (params.slug !== params.slug.toLowerCase()) {
        throw redirect(308, params.slug.toLowerCase())
    }
}) satisfies LayoutLoad
```

Or for an existing pattern-matched route, add a "catch-all" route with a blank page that always redirects:

```ts
// params/isCanonicalSlug.ts

import type { ParamMatcher } from '@sveltejs/kit'

export const match: ParamMatcher = slug =>
    slug === slug.toLowerCase()
```

```svelte
<!-- routes/blog/[slug=isCanonicalSlug]/+page.svelte -->

<script lang="ts">
    import { page } from '$app/stores'
</script>

{$page.params.slug}

The canonical blog post
```

```svelte
<!-- routes/blog/[slug]/+page.svelte -->

<!-- (Not canon) -->
```

```ts
// routes/blog/[slug]/+layout.server.ts

import { redirect } from '@sveltejs/kit'
import type { LayoutServerLoad } from './$types'
 
export const load = (({ params }) => {
    throw redirect(308, params.slug.toLowerCase())
}) satisfies LayoutServerLoad
```

### Importance

would make my life easier

**Comment by markjaquith** [comment]
This is an interesting idea. Param matchers seem fairly underpowered as-is.

You could potentially simplify this if you assumed that a Param matcher that returns its input param as-is should be considered the same as a `true` response, which would allow you to make a Param matcher that simply does `.toLowerCase()`

**Comment by Rich-Harris** [comment]
This isn't what matchers are for — they're deliberately very simple functions. Redirecting if a string is returned would be a confusing API that solves a very niche problem.

Throwing a redirect inside the `load` function is the correct way to solve this problem.
