### ISSUE TITLE
Build reproducibility inconsistent order in vite manifest

### ISSUE THREAD

**Issue by peterpeterparker** [sveltejs/kit#8290]
### Describe the bug

Validating the reproducibility of build results is innacurate because the resources listed in `vite-manifest.json` are not sorted.

i.e. each time `npm run build` is executed, the resources listed in `vite-manifest.json` are sorted differently. Per extension, validating the build results - e.g. comparing hashes of results - is not possible.

### Reproduction

```
git clone https://github.com/peterpeterparker/my-app-reproducibility-sort
cd my-app-reproducibility-sort
npm ci
npm run build
-- copy build/vite-manifest.json somewhere
npm run build
-- compare build/vite-manifest.json with previous output
-- repeat
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 78.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

### Additional Information

- I am not sure it is actually a SvelteKit, adapter static or vitejs issue. For sure let me know if I should forward the issue somewhere else

- Note that to ensure build reproducibility the [version](https://kit.svelte.dev/docs/modules#$app-environment-version) should be set to a constant value, not timestamp which is done in the sample repo by using the `package.json` version number instead

### Workaround

Sort the `vite-manifest.json` entries manually with a post script.

e.g. in `script/make-reproducible`

```
#!/usr/bin/env bash
set -euxo pipefail
cd "$(dirname "$(realpath "$0")")/.."
# shellcheck disable=SC2094 # This reads the entire file into memory and then writes it out, so is correct.
cat <<<"$(jq --sort-keys . build/vite-manifest.json)" >build/vite-manifest.json
```

**Comment by bluwy** [comment]
Yes this is a Vite issue as the manifest is generated by it. Please open an issue at https://github.com/vitejs/vite/issues

**Comment by peterpeterparker** [comment]
Sure, done.

👉 https://github.com/vitejs/vite/issues/11540
