### ISSUE TITLE
Adapter-Node gives error 403 for Action routes

### ISSUE THREAD

**Issue by HikaruHokkyokusei** [sveltejs/kit#8297]
### Describe the bug

This is an error in the resolution of routes that are associated with Actions during server-side rendering.

It works fine when with the vite dev server. So I believe that it is an issue with the `adapter-node` and the `handler.js` that it generates.

It is not able to resolve the routes that are generated as a consequence of the code of the following syntax: -

```
import type { Actions } from "./$types";
export const actions = {
    // These logics always run on the server
    enter: async () => {
        // Do something...
    },

    restart: async () => {
        // Do something...
    },

    update: async () => {
        // Do something...
    }
} satisfies Actions;
```

The three routes here, `enter`, `restart`, and `update` do not work.

### Reproduction

Create a demo svelte-kit app.
I go for a typescript syntax demo app that comes with the built-in `sverdle` game.

In the `svelte.config.js` file, use `adapter-node` instead of `adapter-auto`.

Now, build the app using the script provided in the `package.json` file.
Run the app using the command `node build/index.js`.

Go to the `sverdle` game, input a 5-letter word and try to hit enter.
It will not work. (It is trying to hit the endpoint: http://localhost:3000/sverdle?/enter)

### Logs

```Shell
main.js?attr=Jj_PVtv…6QrNZgV3dcNTil:2625 
POST http://localhost:3000/sverdle?/enter 403 (Forbidden)
fetchCallImpl	@	main.js?attr=Jj_PVtv…6QrNZgV3dcNTil:2625
window.fetch	@	main.js?attr=Jj_PVtv…6QrNZgV3dcNTil:2627
window.fetch	@	start-b3b6aa9e.js:1
l	        @	_page.svelte-6113d134.js:1
```

### System Info

```Shell
System:
  OS: Windows 10 10.0.22621
  CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Memory: 16.38 GB / 31.86 GB
Binaries:
  Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
  npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.22621.963.0), Chromium (108.0.1462.46)
  Internet Explorer: 11.0.22621.1
npmPackages:
  @sveltejs/adapter-node: ^1.0.0-next.106 => 1.0.0 
  @sveltejs/kit: ^1.0.0-next.589 => 1.0.1 
  svelte: ^3.54.0 => 3.55.0
  vite: ^4.0.0 => 4.0.3
```

### Severity

blocking an upgrade

**Comment by Lord-Leonard** [comment]
+1

**Comment by Rich-Harris** [comment]
This is happening because you haven't set an `ORIGIN`: https://github.com/sveltejs/kit/tree/master/packages/adapter-node#origin-protocol_header-and-host_header

We debated detecting this case more proactively in https://github.com/sveltejs/kit/pull/7693 but concluded it would cause more trouble than it's worth. Not sure if there's an in-between solution.

**Comment by HikaruHokkyokusei** [comment]
Ok, I tried the solution of specifying `ORIGIN` and it works fine now. I have never worked with reverse proxies or load balancers so specifying a single `ORIGIN` doesn't make sense to me, but I guess the problem is solved using `x-forwarded-proto` and `x-forwarded-host` (based on the article you linked).

Anyways, thanks for the help. I'll keep looking more into it, and hopefully will understand what those extra headers do.

**Comment by slokhorst** [comment]
For future readers: the docs for `ORIGIN` are now here: https://svelte.dev/docs/kit/adapter-node#Environment-variables-ORIGIN-PROTOCOL_HEADER-HOST_HEADER-and-PORT_HEADER
