### ISSUE TITLE
new Response from Sveltekit returning audio files does not work as expected

### ISSUE THREAD

**Issue by half-metal** [sveltejs/kit#8300]
### Describe the bug

I've been trying to figure out why audio was behaving differently with a file retrieved from Sveltekit modifying this example to do playback with an audio file: https://svelte.dev/tutorial/media-elements, and finally realized the way Sveltekit returns a file is different than Node or even other frameworks, which as a result doesn't allow seeking position to be displayed.

A file read from the file system that is returned by Sveltekit through the server.js route does not return media files in a way that can be processed by the frontend to determine duration in the same way other servers do.

In the repo provided, various url are provided in route `/audio-tag `that can be commented out to check how it works.
    1) `let url = 'https://download.pariyatti.org/free/_moIbLs95/Dana_The_Practice_of_Giving_single.mp3'`
    2) `let url = 'http://localhost:5173/fileAudio?fileName=enchanted-svelte.mp3&fileFolderPath=audio'`

url 1) loads fine and duration can be determined, which allows determining the visual seek slider graphic location since you know the audio.currentTime and the audio.duration which is 9375.564
url 2) is a file stored in the project in the assets folder, duration can be determined for small files; however, larger files will fail and show NaN. As a result you cannot determine current time.

The main difference I think is the response from 1) which is status code 206 and byte range is in the content header. This question on stackoverflow has answers that show how to can potentially fix this https://stackoverflow.com/questions/42590683/node-cant-seek-audio-stream 

Except you cannot change the response status code to 206. in Sveltekit due to recent changes. Unless that's not in the documentation. You can still give a byte range in the headers, but it still has issues with moving the seek slider, which maybe due to not being able to change the status code.

Perhaps it's something else, but from what I can tell,  this is an issue where Sveltekit server works differently than how other server systems work like Apache or Node server, which work fine, or lack of documentation to show how to do this.

### Reproduction

https://github.com/half-metal/audio-issue-svelte

### System Info

```Shell
Chrome on Macbook air
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
I don't see in the code anywhere where you're trying to return a 206. Can you update the repro to show that that's not working?

There also seems to be a bit of stuff in the repo that's unrelated to this issue. https://github.com/half-metal/audio-issue-svelte/blob/main/src/routes/fileAudio/%2Bserver.js also has hard-coded absolute paths that aren't going to work when someone else clones your repo. And the headers that are returned are also hard-coded, and not based on the range that was requested by the browser.

**Comment by half-metal** [comment]
@Conduitry I updated and pushed commit https://github.com/half-metal/audio-issue-svelte where I attempt to set status code 206 and get this error from the server
```
2:47:09 PM [vite] page reload .svelte-kit/generated/client-manifest.js
Parse failure: Unexpected token (53:42)
Contents of line 53:     return new Response(readStream, status:206, { headers: responseHeaders });
Error: Parse failure: Unexpected token (53:42)
Contents of line 53:     return new Response(readStream, status:206, { headers: responseHeaders });
    at ssrTransformScript (apps/audio-issue-svelte/node_modules/vite/dist/node/chunks/dep-0bae2027.js:51616:15)
    at ssrTransform (apps/audio-issue-svelte/node_modules/vite/dist/node/chunks/dep-0bae2027.js:51591:12)
    at Object.ssrTransform (apps/audio-issue-svelte/node_modules/vite/dist/node/chunks/dep-0bae2027.js:60915:20)
    at loadAndTransform (apps/audio-issue-svelte/node_modules/vite/dist/node/chunks/dep-0bae2027.js:39310:24)
2:47:14 PM [vite-plugin-svelte] ssr compile done.
package                 files     time     avg
audio-issue-svelte          1   11.0ms  11.0ms
```
This is how I attempted to set 206  `return new Response(readStream, status:206, { headers: responseHeaders });`

I actually didn't know how to return a 206 for a status code based on latest Sveltekit not having docs how to do since the previous way is now deprecated, I tried changing and it would error out.. I was only able to return 200. 

The route /audio-tag will GET from /fileAudio server route the file but fail since it doesn't like `status code:206` in the Response.

**Comment by half-metal** [comment]
@Conduitry  also yeah, about the hardcoded, I was trying to show example where it pulls it from your File System and not merely getting from your /static folder, if you alter this on the server.js page {id: 1, name:"imagePath", value:`${your directory}/audio-svelte/src/lib/assets/}`, to the directory you cloned the repo it should work. I guess I could put in static folder which will probably illustrate the same thing. Let me know and I'll switch to that folder.

**Comment by Conduitry** [comment]
` return new Response(readStream, status:206, { headers: responseHeaders });` isn't syntactically correct JS, as that error message indicates.

https://kit.svelte.dev/docs/web-standards links to the MDN pages for the web standards you need to be aware of to use SvelteKit. https://developer.mozilla.org/en-US/docs/Web/API/Response/Response shows how to call the constructor to represent a different status code.

**Comment by half-metal** [comment]
ahh, that's better with return `new Response(readStream, { status: 206, headers: responseHeaders});`
and also using something like this
```
                    'Content-Range': 'bytes 0-81660645/81660646',
                    'Content-Type': 'application/x-download-file',
```

I now see the duration is returned and can show the seek slider since the duration is no longer NaN

I was going all over the docs looking up the word 'response' and 'new response', and should have just looked at that web standards. Closing this issue thx @Conduitry
