### ISSUE TITLE
Allow setting build-time configuration values

### ISSUE THREAD

**Issue by trwnh** [sveltejs/kit#8305]
### Describe the problem

I want to set different configuration values during development vs. at build time.

### Describe the proposed solution

I would like to see an easy way to set build-time options/config

### Alternatives considered

[I don't yet know enough about SvelteKit to propose an alternative, sorry]

### Importance

would make my life easier

### Additional Information

More specifically, to avoid an X-Y problem:

The problem I noticed is that when you for example disable `csr` with `export const csr = false`, it causes issues in the dev environment.

The intended goal is to have features such as hot reloading during `npm run dev`, and to have adapter-static remove these features with `npm run build`.

Based on what (little) I know so far, it seems like the most natural solution would be to somehow leave `csr` enabled for dev, and only disable it for build. However, it seems you can only set the options for the root layout in `src/routes/+layout.[js,ts]` which get applied both at dev time and build time.

I would also consider the issue solved if `npm run dev` always assumed `csr` or somehow allowed for hot reloading without affecting the zero-js statically generated build.

**Comment by Conduitry** [comment]
You already have access to this via https://kit.svelte.dev/docs/modules#$app-environment-dev - you can base route configuration on this.
