### ISSUE TITLE
Provide feedback about prerender progress during build

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/kit#8309]
### Describe the problem

I have ~10000 routes that are being prerendered. When building the app, it looks like the process has stopped or got stuck. There is no feedback given.

### Describe the proposed solution

Something like a counter that tracks the progress of how many pages have been crawled or prerendered, which updates every second?

### Alternatives considered

Wait and hope for the best every time.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
You can use `logLevel: 'info'` in your Vite config and it will print pathnames as they are prerendered

**Comment by UltraCakeBakery** [comment]
Thanks for the response. I was not aware of the `logLevel: 'info'` option. It will do for now during debugging, but the console flood is not ideal. I will keep this issue open for a maintainer to label it, or close it as "not planned". 

Not sure if this issue is worth you guy's time though, since at this stage I should probably use the static adapter and use a static file host.... But on the flip side, the dev experience for people that have endpoints connecting to slow databases (lets say 10s query times) probably experience the same confusion that I had, even when they are just  generating a few pages. I'm lucky that all endpoints are < 1ms in performance making generating 10000 routes barrable.

**Comment by Rich-Harris** [comment]
There was a recent change that affected logging — it turns out that `logLevel: 'info'` is the default Vite setting, but unless you explicitly set that value, the `verbose` setting during prerendering was disabled. That logic has been fixed...

```diff
// pseudo-code
-verbose = logLevel === 'info';
+verbose = logLevel === 'info' || logLevel === undefined;
```

...which means that progress feedback is given by default, so I'll close this
