### ISSUE TITLE
redirect + set cookies

### ISSUE THREAD

**Issue by kswope** [sveltejs/kit#8316]
### Describe the problem

Redirecting and setting cookies at the same time might be a missing feature.

This is what I'm using now (in hooks.server.ts) , yuck

```
  return new Response(undefined, {
    status: 302,
    headers: {
      location: "/public/login",
      "set-cookie": `originalPath=${path}`,
    },
  })
```

### Describe the proposed solution

There's a handy redirect function [here](https://kit.svelte.dev/docs/load#redirects), 

```
throw redirect(307, '/login');
```

perhaps it could accept options with cookies

```
throw redirect(307, '/login', {cookies: {originalPath: "/settings"});
```

### Importance

nice to have

**Comment by Conduitry** [comment]
Can you do this by using the [`cookies.set` API](https://kit.svelte.dev/docs/load#cookies-and-headers) and then throwing the `redirect`? I don't think it needs to be combined into a single function.

**Comment by kswope** [comment]
> Can you do this by using the [`cookies.set` API](https://kit.svelte.dev/docs/load#cookies-and-headers) and then throwing the `redirect`? I don't think it needs to be combined into a single function.

Trying that led me to the problem.  Looks to me like throwing a redirect creates a new Response.

**Comment by markjaquith** [comment]
@kswope Hmm. @Conduitry's suggestion is working for me. Here's a StackBlitz demonstrating it: https://stackblitz.com/edit/sveltejs-kit-template-default-uqfna4?file=src/routes/set-cookie-and-redirect-to-success/+page.server.js

```js
import { redirect } from '@sveltejs/kit';

export function load({ cookies }) {
	cookies.set('success', 'true');
	throw redirect(302, '/success');
}
```

<img width="290" alt="CleanShot 2023-01-02 at 12 49 55@2x" src="https://user-images.githubusercontent.com/353790/210264878-016883d6-b14c-4323-9087-ebc53c7c18d6.png">

**Comment by kswope** [comment]
> @kswope Hmm. @Conduitry's suggestion is working for me. Here's a StackBlitz demonstrating it: https://stackblitz.com/edit/sveltejs-kit-template-default-uqfna4?file=src/routes/set-cookie-and-redirect-to-success/+page.server.js


My problem is in hooks.

To further compound the issue, the cookie setting location is in the request property

```
let auth: Handle = async ({ event, resolve }): Promise<Response> => {
    event.cookies.set("key", value)
...
```

I suppose cookies could be carried over to the response like so

```
  event.cookies.set("key", value)
  const response = await resolve(event);
  return response;
```

But I'm not sure if setting a cookie on a request makes sense or should be allowed.

Even worse, I don't think there's a way to set a 3xx status code on that response either.  But I think you could manage a location header.

**Comment by ivanhofer** [comment]
I had a similar issue a few weeks ago: #7611

**Comment by Conduitry** [comment]
Ah, yup, it sounds like dummdidumm's comment in https://github.com/sveltejs/kit/issues/7611#issuecomment-1311724908 is relevant here then. I'm not sure what sort of dev mode warnings would be practical to emit here.

**Comment by ivanhofer** [comment]
Like I already mentioned in https://github.com/sveltejs/kit/issues/7611#issuecomment-1311774821, the best option would be to support such a use-case.
I'm sure there will be some people stumbling into this issue in the future and asking why it doesn't work.

If you try to set a cookie after calling `resolve` e.g. like this:

```ts
const response = await resolve(event)
cookies.set('test', 'cookie')
return response
```
you'll get this error:
```
Cannot use `cookies.set(...)` after the response has been generated
```

If `SvelteKit` does not want to support setting `cookies` outside of the `resolve` process, then at least an error should be thrown telling that it is not supported and that someone needs to set the corresponing headers on the response object.

**Comment by 7antra** [comment]
@kswope 

It's unrelated to the issue, but in your example you use cookie just to get a "referrer" your original path. It's little bit weird and not a best pratices to do that. I think you could just use a params like 
```
headers: {
      location: `/public/login?originalPath=${path}`,
}
```

and access it in your login page with `$page.url.searchParams.get('originalPath')`

**Comment by kswope** [comment]
@7antra 

> It's little bit weird and not a best pratices to do that.

Its not weird but maybe its less common for SPAs.

First link in google search for "login redirect to requested url" is this [Spring Security – Redirect to the Previous URL After Login](https://www.baeldung.com/spring-security-redirect-login)

> The most common ways to implement redirection logic after login are:
> 
>     using HTTP Referer header
>     saving the original request in the session
>     appending original URL to the redirected login URL

The reason I don't like the URL method is because if there are multiple pages before the final redirect you have to remember to keep passing the originalPath.

**Comment by Rich-Harris** [comment]
I'm having a hard time following this conversation — if `cookies.set(...); throw redirect(...)` works then what are we missing?

**Comment by ivanhofer** [comment]
I think the issue described here was fixed by #8648.

Leaving two cookies edge cases that are mentioned in #7611 and currently not solved.

1. 
```ts
event.cookies.set('custom', 'cookie') // this call gets ignored

return new Response('<html><body><h1>Hello</h1></body></html>', {
	headers: {
		'Content-type': 'text/html'
	}
})
```
2.
```ts
const response = await resolve(event);

// this will throw an error
event.cookies.set('test', 'cookie') 

return response
```

**Comment by dummdidumm** [comment]
Both sound like "works as designed" for me, so I'd be in favor of closing

**Comment by Rich-Harris** [comment]
Yeah, I think the behaviour in both of those cases is correct — by returning a custom response you're opting out of the rendering process, and headers are as much a part of that rendering process as the body is.

Given #8648 fixes the issue at hand, I'll close this
