### ISSUE TITLE
Can't build with staging environment variables 

### ISSUE THREAD

**Issue by yuliankarapetkov** [sveltejs/kit#8323]
### Describe the bug

I am trying to build an app with staging environment variables (`.env.staging`). However, I am always getting the environment variables listed in `.env.production`.

### Reproduction

Run the following:

```
npm run build -- --mode staging
```

Or update `mode` in `vite.config`:
```
const config = {
	plugins: [sveltekit()],
	mode: "staging"
};
```
And then run `npm run build`

When building with either of these approaches, I can see a message saying `vite v4.0.3 building for staging...`. However, when I open `/build/index.html` (I'm using SPA mode), I can see that the environment variables injected are the production ones.

**Note**:
Running the project locally (`npm run dev -- --mode staging`) uses the correct files. Building the project (`npm run build -- --mode staging`) doesn't.

Here's a [demo repo](https://github.com/yuliankarapetkov/svelte-latest).

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 19.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.13.1 - ~/.../node_modules/.bin/npm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 108.0.5359.124
    Firefox: 105.0.1
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

blocking an upgrade

### Additional Information

I migrated from Routify to SvelteKit and now our testing environment is broken due to this issue.

**Comment by yuliankarapetkov** [comment]
It doesn't seem to be an issue with Vite since I just created a sample VanillaJS Vite project and the above works as expected.

**Comment by konstantinblaesi** [comment]
works fine for me

**config:**
```
// .env.development
PUBLIC_TEST=development_123
```

```
// .env.staging
PUBLIC_TEST=development_123
```

**build**:
npm run build -- --mode staging

**preview**
npm run preview -- --mode staging

or in package.json script `vite build --mode staging` and `vite preview --mode staging`

**Comment by yuliankarapetkov** [comment]
@konstantinblaesi not working for me.

I am using the [demo repo](https://github.com/yuliankarapetkov/svelte-latest) I posted above.

```
// .env.staging
PUBLIC_TEST=staging
```

```
// .env.production
PUBLIC_TEST=production
```

```
// svelte.config.js
import adapter from '@sveltejs/adapter-static';
import preprocess from "svelte-preprocess"

const config = {
	preprocess: preprocess(),

	kit: {
		adapter: adapter({
			fallback: 'index.html'
		}),
		prerender: {
			entries: []
		}
	}
};

export default config;
```

```
// +layout.ts
export const ssr = false;
```

```
// +page.svelte
<script lang="ts">
	import { PUBLIC_TEST } from '$env/static/public';
</script>

<h1>Hello from {PUBLIC_TEST}</h1>
```
When I run `npm run dev -- --mode staging` with this config, I get the following result:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/6671521/210654566-d356d4ed-fcb1-486e-a2b4-bc010184593e.png">

However, when I try to build for the staging environment with `npm run build -- --mode staging`, I can see the following after a successful build:
```
// /build/index.html
...
<script type="module" data-sveltekit-hydrate="45h">
	import { start } from "/_app/immutable/start-bc958a88.js";

	start({
		env: {"PUBLIC_TEST":"production"}, // <== <== <== <== <== <== <== <== <== <== 
		paths: {"base":"","assets":""},
		target: document.querySelector('[data-sveltekit-hydrate="45h"]').parentNode,
		version: "1672868440223"
	});
</script>

```

**Comment by konstantinblaesi** [comment]
That's really strange as I was already using your repo. I only added the two .env files and svelte adds the env value right into the page for me
![image](https://user-images.githubusercontent.com/5871169/210763958-65063752-fa2b-4dd5-9040-4920cc7d0f2d.png)

**Comment by Rich-Harris** [comment]
Works as expected for me too

**Comment by yuliankarapetkov** [comment]
I just redeployed the project and now it uses the correct `.env` file. There was something wrong I was doing before that. Not sure what. 

Sorry for the fuss! It all works as expected 🚀

**Comment by aakash14goplani** [comment]
@yuliankarapetkov - what are the steps that you took for migrating Routify to SvleteKit?

**Comment by mhDuke** [comment]
> I just redeployed the project and now it uses the correct `.env` file. There was something wrong I was doing before that. Not sure what.
> 
> Sorry for the fuss! It all works as expected 🚀

@yuliankarapetkov i am facing the same problem, the vite keeps picking up variables from .env.production when it should pick up variables from .env.staging. i run `"build:staging": "vite build --mode staging"`

do you recall how did you solve it?
