### ISSUE TITLE
new Error().stack reporting wrong line number

### ISSUE THREAD

**Issue by ejkreboot** [sveltejs/kit#8333]
### Describe the bug

I am trying to create a simple logger that reports the line numbers where the log function was called by parsing `new Error().stack`. But the resulting line numbers are off--in my case, between 2 and 7 lines. I do not know if this is a sveltekit issue, a vite issue, or a non-issue.

### Reproduction

With a freshly created app:
```
npm create svelte@latest lineno
cd lineno
npm install
```

If I create I `$src/hooks.server.js` with just a simple function:
```
export const handle = async ({ event, resolve }) => {
  console.log(new Error("My error").stack)
  return await resolve(event);
}
```

The stack trace reports line 4 instead of line 2;
```
Error: My error
    at Object.handle (/erikor/Documents/Business/lineno/src/hooks.server.js:4:15)
```

This continues to be true despite trying to enable sourcemaps in `svelte.config.js`:
```
const config = {
    compilerOptions: {
        enableSourcemap: true,
      },
    preprocess: sveltePreprocess({
        sourceMap: true,
    }),
    kit: {
        adapter: adapter()
    }
};
```
And `vite.config.js`:

```
const config = {
    plugins: [sveltekit()],
    build: {
        sourcemap: 'inline'
    },
};
```

And this is the case in both dev and prod.

If my code contains an actual error, then the reported line numbers are correct.
```
export const handle = async ({ event, resolve }) => {
  foo(bar);
  return await resolve(event);
}
```
```
foo is not defined
ReferenceError: foo is not defined
    at Object.handle (//Users/erikor/Documents/Business/lineno/src/hooks.server:2:3)
```

### Logs

```Shell
See above. There are no other logs I am aware of.
```

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 1.94 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/adapter-node: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.3
```

### Severity

annoyance

**Comment by benmccann** [comment]
> I do not know if this is a sveltekit issue, a vite issue, or a non-issue.

Because this is happening in a `.js` file without any `.svelte` file involved, it's almost certainly a Vite issue and not caused by SvelteKit or `vite-plugin-svelte`.

**Comment by benmccann** [comment]
Vite 4.0.4 has a sourcemap fix. I see you're on 4.0.3. You could try upgrading and see if it helps.

https://github.com/vitejs/vite/blob/v4.0.4/packages/vite/CHANGELOG.md#404-2023-01-03

**Comment by ejkreboot** [comment]
Upgrade to vite 4.0.4. Did not resolve issue. I will post over in vite. Thank you!
