### ISSUE TITLE
Nesting `<button>` tags causes `%sveltekit.body%` to render under the wrong target

### ISSUE THREAD

**Issue by alexiglesias93** [sveltejs/kit#8345]
### Describe the bug

I don't know if this issue is just specific to nesting `<button>` tags (which [is wrong syntax](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element)) or if it is caused whenever invalid HTML syntax is written.

When something like this is written (notice the invalid nested `<button>` tags):
```html
<button class="card" on:click={handle_card_click}>
	<div>Card Title</div>

	<div class="card-controls">
		<button class="card-control" on:click|stopPropagation={handle_edit_card_click}>Edit</button>
		<button class="card-control" on:click|stopPropagation={handle_remove_card_click}>Remove</button>
	</div>
</button>
```
SvelteKit renders `%sveltekit.body%` directly under `<body>`, ignoring the HTML structure defined in `app.html` and displays this warning:
```
Placing %sveltekit.body% directly inside <body> is not recommended, as your app may break for users who have certain browser extensions installed.

Consider wrapping it in an element:

<div style="display: contents">
  %sveltekit.body%
</div>
```

Fixing this is as simple as fixing the invalid HTML, but a more descriptive error would've helped me a lot when debugging my project when I encountered this.

### Reproduction

Stackblitz with reproduction steps:
https://stackblitz.com/edit/sveltejs-kit-template-default-ylq8rn?file=src/routes/+page.svelte

### System Info

```Shell
(Info from Stackblitz, but the issue happens in regular local projects too)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
Any ideas about what sort of error message would have helped diagnose this? Malformed HTML is rather hard to detect (even if the Svelte compiler had an exhaustive list of rules like 'a button can only include phrasing content', it only operates on a single component at a time, meaning that if a `<button>` contained a component that _also_ contained a `<button>`, so we'd need to validate the rendered HTML which is costly/tricky and the developer would have to figure out where the offending component code lived), so realistically it would probably be something like this...

```diff
Placing %sveltekit.body% directly inside <body> is not recommended, as your app may break for users who have certain browser extensions installed.

Consider wrapping it in an element:

<div style="display: contents">
  %sveltekit.body%
</div>

+If the body is already wrapped, it may indicate that you're generating malformed HTML
```

...which doesn't seem like it would be _that_ helpful. Thoughts?

**Comment by alexiglesias93** [comment]
Oh, that extra line would've given me a good head start, as initially I was clueless of why I was getting that error and it wasn't until I decided to start enabling/disabling each component in my project that I was able to narrow down the issue to that specific HTML snippet. So it would definitely be helpful!

Maybe it could be possible to identify the specific logic in SvelteKit that causes the `%sveltekit.body%` to be misplaced?
Or instead of analyzing each component separately, check `app.html` to see if effectively `%sveltekit.body%` is not a direct child of `<body>` before throwing the error.

**Comment by Rich-Harris** [comment]
i guess analysing `app.html` would be the most robust approach. the (major) downside is that to do it reliably we might need to introduce a dependency on an HTML parser, which would be unfortunate. though maybe given the scope of the problem we can hand-roll a solution

**Comment by aubergene** [comment]
Just a thought which probably isn't helpful but might inspire something. If you serve a page as xhtml (i.e. with `"Content-Type": "application/xhtml+xml"`) then Chrome will do DOM validation. So in a simple experiment where I try to add invalid content I get and error like this

`index.html:11 Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.`

**Comment by myieye** [comment]
I almost created a new issue, but I'm assuming my problem is essentially the same thing.

I've discovered that nesting `<button>` or `<a>` breaks the SSR result and then CSR fixes it up.
On SSR the first button seems to get closed when the second button starts.

Here's my repro: https://stackblitz.com/edit/sveltejs-kit-template-default-ga3fw5?file=src%2Fapp.d.ts
![image](https://github.com/sveltejs/kit/assets/12587509/7d5957f6-6a93-4acf-9274-0646da7b3df7)

**Comment by eltigerchino** [comment]
Closing this now that we get a nice Svelte 5 error for invalid HTML.
![VS Code error](https://github.com/user-attachments/assets/286611e1-c5a9-4bed-ac7f-99f1d3c1ebc3)
![vite overlay error](https://github.com/user-attachments/assets/c1cddf78-5fb1-4234-8333-6be88c3e33ab)
