### ISSUE TITLE
Delayed loading of data in load function

### ISSUE THREAD

**Issue by y0zong** [sveltejs/kit#8375]
### Describe the problem

Sometimes data api is slow, page is just seems died after click a link to route to new page. Is that possible to route to new page immediately after clicking a link even the only data from api is not ready? I know this can be done by a trick that fetch data in page programmly but it will be nicer to done by `load` function itself.

or there’s a ready way to do this just because I missed something in document?

### Describe the proposed solution

The logic is basically consistent except to return the page immediately and update after the data arrives instead of waiting for the data to return to the page.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
closing in favour of https://github.com/sveltejs/kit/issues/7213#issuecomment-1318758519
