### ISSUE TITLE
Redirect does not work in load function when calling invalidateAll

### ISSUE THREAD

**Issue by akkie** [sveltejs/kit#8382]
### Describe the bug

I have a load function in a `+page.ts` file, which logs a user out. This function logs the user out on the server, then it invalidates all data, so that the layout gets rendered with actual server data. After that the user should be redirected to the login page.

```ts
export const load: PageLoad = async ({ fetch, parent }) => {
  const { locale } = await parent();

  // Logout on server

  await invalidateAll();
  throw redirect(307, '/login');
};
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ux4hr3?file=src/routes/logout/+page.js

Click the logout button on the home page. The user gets not redirected to the about page. When `invalidateAll` will be removed, then the redirect works as expected.

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (5) arm64 unknown
    Memory: 10.45 GB / 15.61 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.0.1 => 1.0.1 
    @sveltejs/kit: 1.0.3 => 1.0.3 
    svelte: 3.55.0 => 3.55.0 
    vite: 4.0.4 => 4.0.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
`load` is intended for loading data, not side effects like invalidating. There's also danger of this resulting in an infinite loop. I think this kind of logic is better implemented inside your `+page.svelte` where the logout button is - something like
```svelte
<script>
  import {invalidateAll, goto} from '$app/navigation';

  async function logout() {
    await invalidateAll();
    goto('/home');
  }
</script>

<button on:click={logout}>logout</button>
```

Closing as `invalidate(All)` isn't meant to be used inside `load` functions. You're welcome to expand on your use case if you feel this is unjustified.
