### ISSUE TITLE
`use:enhance` resets form data between repeated submits

### ISSUE THREAD

**Issue by angrytongan** [sveltejs/kit#8404]
### Describe the bug

Submitting the same form content when using `use:enhance` results in form fields being cleared between submits.

### Reproduction

https://github.com/angrytongan/use-enhance-bug

1. Install

```
git clone https://github.com/angrytongan/use-enhance-bug
npm install
npm run dev
```

2. Browse to `http://localhost:5173`
3. Enter `hello` in first field, `world` in second field.
4. Press `Submit`.
5. `hello world` is printed underneath the form. First field contains `hello`,
   second field contains `world`. Server prints:

    ```js
    { first: 'hello', last: 'world' }
    ```

6. Press `Submit`.
7. `hello world` is printed underneath the form. Fields are now empty. Server
   prints:

    ```js
    { first: 'hello', last: 'world' }
    ```

8. Press `Submit`.
9. Nothing printed underneath form. Fields are empty. Server prints:
    ```js
    { first: '', last: '' }
    ```

## Expectation

Fields should not lose their content.

## Use case

-   Chat form with room and message field: the room may not change, but the
    message does. We want to keep the room between form submits.

### System Info

```Shell
System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 258.57 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.0 => 1.0.7
    svelte: ^3.54.0 => 3.55.0
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
This is the expected behavior, by default `form.reset()` is called after a successful submission (this is also mentioned in the docs). You can disable this by passing `reset: false` to the `update` method:
```svelte
<form method="post" use:enhance={() => {
  return ({ update }) => update({ reset: false });
}}
```

**Comment by coryvirok** [comment]
FWIW, I was confused by this as well and didn't see anything about the `reset` option to update. Thx for the fix.

**Comment by angrytongan** [comment]
@dummdidumm I think I had the expectation that adding `use:enhance` wouldn't change behaviour from the same form that didn't `use:enhance`. No problems at all, just wondering if that was a valid assumption? Thanks so much for all your work.

**Comment by dummdidumm** [comment]
It doesn't change the behavior, by resetting the form it tries to mimick it closer - if you wouldn't have `use:enhance` on the form, you would get a full page reload with the form cleared.

**Comment by angrytongan** [comment]
Hm, not sure I understand. My understanding is the form will take any values that are set by the server; if I remove `use:enhance` from [the form in this repo](https://github.com/angrytongan/use-enhance-bug), I get the same values after POST that I do before. But adding `use:enhance` changes this behaviour. What am I missing here?

**Comment by dummdidumm** [comment]
Oooh I see, yeah that's unfortunate. Moving this into a new issue.

**Comment by angrytongan** [comment]
@dummdidumm Thanks legend 👍
