### ISSUE TITLE
Headers are not set when ssr = false

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#8428]
### Describe the bug

In production build, the headers are not set if `ssr = false` in `+layout.server.ts`

### Reproduction

1. Create SvelteKit skeleton project

2. Set headers in `hooks.server.ts`
```ts
export const handle: Handle = async ({ event, resolve }) => {
  event.setHeaders({
    'x-foo': 'bar',
    'cache-control': 'no-store',
  })
  return resolve(event)
}
```
3. Disable SSR in `+layout.server.ts`:
```ts
export const ssr = false
```

4. `pnpm build`
5. `pnpm preview`
6. Get headers (`https -h http://127.0.0.1:4173/`)
7. Note the missing headers

---
See reproduction repo: https://github.com/ebeloded/kit-headers-bug

### Logs

```Shell
❯ http -h http://127.0.0.1:4173/                      
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Tue, 10 Jan 2023 01:58:08 GMT
Keep-Alive: timeout=5
Transfer-Encoding: chunked
content-type: text/html
etag: "1673315883560"
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 370.16 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/adapter-node: ^1.1.0 => 1.1.0 
    @sveltejs/kit: ^1.0.0 => 1.0.10 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.4
```

### Additional Information

1. The headers _are_ returned when in dev mode `pnpm dev`
2. In the reproduction, I use `adapter-auto`, but behavior is the same with `adapter-node`

**Comment by dummdidumm** [comment]
What do you mean by the step "get headers (`https -h http://127.0.0.1:4173/`)"? When I'm invoking the URL in the browser and look at the headers in the network tab, they are shown as expected.

**Comment by ebeloded** [comment]
@dummdidumm sorry about the confusion. The `https` comes from [HTTPie](https://httpie.io/).

I've double-checked and confirmed the issue. 

Here is the screenshot of headers when the app running in dev mode (`pnpm run dev`). The headers are present:

<img src="https://user-images.githubusercontent.com/5859177/211579918-c3cdbfe5-0230-412d-9533-fd7f8f8735a1.png" width="300" />


And here is a screenshot of the app that runs in production mode (`pnpm run preview`). The headers are absent:

<img src="https://user-images.githubusercontent.com/5859177/211580239-9cd675de-0d43-4cd0-a38e-57afdf123675.png" width="300" />

Please let me know if you get different results.

The problem I am trying to solve in my app is to set the `cache-control` header, but it proves to be impossible when `ssr = false`.

**Comment by Rich-Harris** [comment]
ohhh.... this must be because of https://github.com/sveltejs/kit/pull/8131.

Two options:

1. we treat this as a bug and revert #8131 
2. add `export const prerender = false` alongside `export const ssr = false`

#8131 is a valuable optimisation so it would be a shame to lose it, but I wonder how we can make this behaviour clearer.

**Comment by benmccann** [comment]
There's a feature request for saving the headers and serving them here: https://github.com/sveltejs/kit/issues/9408
