### ISSUE TITLE
Kit docs should absolutely talk about where components should live.

### ISSUE THREAD

**Issue by rogadev** [sveltejs/kit#8443]
### Describe the bug

At present, if you visit the kit [docs related to project structure](https://kit.svelte.dev/docs/project-structure) you'll notice there is no mention of where components should live. I can't seem to find anywhere in the docs that tells new users where they should be putting their Svelte components. Considering components are such a key concept Svelte and SvelteKit, I would have certainly expected some good explanation about where they can/should live in your project structure.

### Reproduction

Pretend you're new to SvelteKit. Follow the docs. Try to figure out where components should live. Search the site for "components" or "project structure" or "component folder structure".

### Logs

```Shell
n/a
```

### System Info

```Shell
n/a
```

### Severity

annoyance

**Comment by Conduitry** [comment]
What sort of guidance would you be looking for? They can live wherever you want in `src`. The project structure documentation says where things need to live for SvelteKit to know how to handle them. Components other than `+page` and `+layout` can live wherever you want.

The starter `create-svelte` template demonstrates how components can live alongside the pages that use them. You can also put shared code (components or .js files) in `src/lib`.

**Comment by stephane-vanraes** [comment]
There is a mention under _Routing_ here https://kit.svelte.dev/docs/routing#other-files, it could be beneficial to duplicate some of that under `lib` in _Project Structure_

**Comment by Algoinde** [comment]
Can be a simple addition, actually.

```diff
my-project/
├ src/
│ ├ lib/
│ │ ├ server/
│ │ │ └ [your server-only lib files]
-│ │ └ [your lib files]
+│ │ └ [your lib files and Svelte components]
```
