### ISSUE TITLE
'$env/static/private'; doesn't work as expected with typescript

### ISSUE THREAD

**Issue by digaofs** [sveltejs/kit#8460]
### Describe the bug

Hi,

I'm trying to use a .env file exactly as described in the docs - https://learn.svelte.dev/tutorial/env-static-private. However, I keep getting "Module '"$env/static/private"' has no exported member [KEY_NAME]" in VS code, inside any (+server, +page.server) .ts file.

### Reproduction

https://github.com/digaofs/svelteKitEnvBugReproduction

Steps to reproduce
1 - Clone repository
2- npm install
3- Open folder using VS code (I'm using v1.74.2)
4- Open +page.server.ts in an editor
5- Error occur at line 3 - (Module '"$env/static/private"' has no exported member 'PASSPHRASE'.ts(2305)) 

### System Info

```Shell
System:
    OS: macOS 11.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 134.83 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    npm: 9.1.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.2
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.0 => 1.0.11
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Where is `PASSPHRASE` coming from? I don't see it in the reproducible. Is this inside a `.env` file which wasn't committed?

**Comment by digaofs** [comment]
Sorry about that, I was tricked by .gitignore. Yes, it comes from src/.env, now present at the same repository.

**Comment by mattlehrer** [comment]
I'm not sure that SK will check for .env in src/.env instead of in the project root. I set up a new project a few hours ago and typescript and the import for env/static/private worked for me with .env in the root.

**Comment by digaofs** [comment]
@mattlehrer that seems to be the problem. I moved the file to the root, and managed to make it work with a npm check (svelt-kit sync + check).
Closing the issue, as it's my mistake (I don't have the need to put the file under src).

Thanks!!

**Comment by AmeerIT** [comment]
> @mattlehrer that seems to be the problem. I moved the file to the root, and managed to make it work with a npm check (svelt-kit sync + check). Closing the issue, as it's my mistake (I don't have the need to put the file under src).
> 
> Thanks!!

the npm check did it for me
