### ISSUE TITLE
Server actions could be available in `+layout.svelte`

### ISSUE THREAD

**Issue by z-x** [sveltejs/kit#8462]
### Describe the problem

Hello!
I am not sure that I am right, but let's say we have a login form that is available on all the subpages in the header. Is there any way of using server actions to make it work if the header is placed in `+layout.svelte`? As actions are only available in the `+page.svelte` does that mean I need to repeat the actions in every route?

### Describe the proposed solution

I think the server actions in the `+layout.svelte` make sense from the development perspective. The use case being search, login forms or - as in the case of my app - the ability to add a 'List' from every route on the page.

### Alternatives considered

Currently I just extracted the action to a separate JS file and am importing them on every route. I am considering I am missing some obvious solution here as this seems to be a very basic things. If so, a better description in the docs would be nice (I could do a PR myself if I knew the answer).

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
You do not need to repeat them on each route, you can use `<form method="post" action="/path/to/your/action">` in your layout, and need to add it only to `/path/to/your/action/+page.server.js` once.

We deliberately didn't add this to layouts because then actions wouldn't work without JS (there's no clear place where the reload should happen).
Having written this, maybe there _IS_ a way to make it work without JS. When the form is POSTed in the native case, we have access to all layouts, so theoretically we could walk up the chain and find the first matching action. Not sure if I miss some obvious technical challenges, or if it's just too weird of an API - thoughts @Rich-Harris ?

**Comment by z-x** [comment]
Right, this is quite obvious. :) Thanks for the answer! I guess I didn't thought about using it because of this (quoting the docs):

> update the form property, $page.form and $page.status on a successful or invalid response, but only if the action is on the same page you're submitting from. So for example if your form looks like <form action="/somewhere/else" ..>, form and $page will not be updated. This is because in the native form submission case you would be redirected to the page the action is on

Which is understandable but also requires me to do additional steps when validating the data. So it's either repeating those on every route or using the `action=""` with a path and resigning from that beautiful and simple validation handling.

**Comment by dummdidumm** [comment]
You could update `$page.form` yourself through `applyAction`, bypassing the default `use:enhance` logic that only does this if the action is on the page you're on.

**Comment by Rich-Harris** [comment]
I'd recommend _not_ doing that though! `$page.form` should be used on the page the action belongs to. Just inspect the value in the `enhance` callback and set local state in the layout accordingly. 

Going to close this, as we can already do everything we need to do here:

```svelte
<!-- +layout.svelte -->
<form
  action="/whatever"
  method="POST"
  use:enhance={() => {
    // if the form is submitted without javascript, it will reload `/whatever` with `$page.form` populated...

    return ({ result }) => {
      // ...otherwise we can set local state inside `+layout.svelte` based on `result`
    };
  }}
>
```

**Comment by hyunbinseo** [comment]
The generated `ActionData` type is still provided in the `+layout.svelte` file, even though the exported `form` variable is not updated. Is this intended?

> the action can respond with data that will be available through the `form` property on the corresponding page and through `$page.form` app-wide until the next update.

https://kit.svelte.dev/docs/form-actions#anatomy-of-an-action
