### ISSUE TITLE
`use:enhance` breaks HMR and routing in dev with `<input name="method" />`

### ISSUE THREAD

**Issue by awenzel5** [sveltejs/kit#8467]
### Describe the bug

Creating a form with and input with the name of "method" breaks both hot module reloading and routing in development mode. The pages build and run just fine on preview, but you get this message in the developer's console and navigating to and from this page freezes navigation (again only in development mode). It seems to stem from [these lines](https://github.com/sveltejs/kit/blob/9c01c32ef72bbed630fadcb8283f8f8533ced5e1/packages/kit/src/runtime/app/forms.js#L28-L31), where it checks form.method

 
![Image of Issue](https://user-images.githubusercontent.com/108757722/211913071-0b99e007-6122-4a2e-8a63-2dffba980b47.png)

### Reproduction

https://github.com/awenzel5/sveltekit-enhance-method

### Logs

```
forms.js?v=80aa9393:30 Uncaught (in promise) Error: use:enhance can only be used on <form> fields with method="POST"
    at enhance (forms.js?v=80aa9393:30:9)
    at mount (+page.svelte? [sm]:8:41)
    at targetCmp.$$.fragment.m (svelte-hooks.js?v=80aa9393:291:24)
    at mount_component (index.mjs:1949:26)
    at Object.update [as p] (root.svelte? [sm]:41:39)
    at update_slot_base (index.mjs:100:14)
    at Object.update [as p] (layout.svelte?v=80aa9393:40:6)
    at update (index.mjs:1209:36)
    at flush (index.mjs:1169:17)
```
### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 21.68 GB / 24.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.11 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This feels like #7593 and is I'm guessing another instance of a similar sort of thing.
