### ISSUE TITLE
Demo app does not work locally without using --host flag

### ISSUE THREAD

**Issue by diericx** [sveltejs/kit#8486]
### Describe the bug

The demo app does not work when running `npm run dev`, it only works when running `npm run dev -- --host` and accessing via local network ip address.

### Reproduction

```
$ npm create svelte@latest my-app

create-svelte version 2.1.0

Welcome to SvelteKit!

✔ Which Svelte app template? › SvelteKit demo app
✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
✔ Add ESLint for code linting? … No / **Yes**
✔ Add Prettier for code formatting? … No / **Yes**
✔ Add Playwright for browser testing? … No / **Yes**
✔ Add Vitest for unit testing? … No / **Yes**

Your project is ready!
✔ Typescript
  Inside Svelte components, use <script lang="ts">
✔ ESLint
  https://github.com/sveltejs/eslint-plugin-svelte3
✔ Prettier
  https://prettier.io/docs/en/options.html
  https://github.com/sveltejs/prettier-plugin-svelte#options
✔ Playwright
  https://playwright.dev
✔ Vitest
  https://vitest.dev

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-adders

Next steps:
  1: cd climbing-notebook
  2: npm install (or pnpm install, etc)
  3: git init && git add -A && git commit -m "Initial commit" (optional)
  4: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat

$ cd my-app
$ npm install
$ git init && git add -A && git commit -m "Initial commit"
$ npm run dev
```
Accessing home page throws 500

### Logs

```Shell
All resources are failing to load. Browser logs below.


[vite] connecting... client.ts:19:8
[vite] connected. client.ts:134:14
Loading failed for the module with source “http://localhost:5173/src/routes/Counter.svelte”. localhost:5173:198:1
TypeError: error loading dynamically imported module client-manifest.js:20:41
Loading failed for the module with source “http://localhost:5173/src/lib/images/svelte-welcome.webp?import”. localhost:5173:198:1
Loading failed for the module with source “http://localhost:5173/src/lib/images/svelte-welcome.png?import”. localhost:5173:198:1
Loading failed for the module with source “http://localhost:5173/src/routes/+page.svelte?svelte&type=style&lang.css”. localhost:5173:198:1
<Error> was created with unknown prop 'data' client.js:1733:15
<Error> was created with unknown prop 'form' client.js:1733:15
<Root> was created without expected prop 'form' client.js:1733:15
SingleFile is hooking the IntersectionObserver API to detect and load deferred images. client.js:1733:15
```

### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M2
    Memory: 382.19 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.asdf/installs/nodejs/18.13.0/bin/node
    npm: 9.2.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.2
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0
    @sveltejs/kit: ^1.0.0 => 1.0.11
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

I apologize for the lack of debugging effort on my end, but I am obviously very unfamiliar with the entire stack as this is my first attempt at using it. I have another project I've gotten working from the basic template but would like to use this template now.

It may be worth mentioning that the files in the errors (e.g. `http://localhost:5173/src/routes/Counter.svelte`) are being successfully served.

**Comment by Conduitry** [comment]
I can't reproduce this, and I really couldn't begin to say what could be causing it.

Have you tried disabling various optional features while scaffolding the demo app? Have you tried this on other systems?

**Comment by diericx** [comment]
Yes the same issue persists with all flags removed. Would you mind sending your system info output if yours doesn't match mine?

**Comment by Rich-Harris** [comment]
Whatever this is, it's a Vite issue rather than a SvelteKit issue. Do you experience the same thing with a non-SvelteKit Vite project?

**Comment by Rich-Harris** [comment]
Based on the fact that I haven't heard any similar reports from other users, I'm going to be optimistic and chalk it up to a weird glitch, and close this. Thanks!

**Comment by lloyet** [comment]
Hello guys,
I updated my nodejs version to actual LTS version `18.15.0` and it seems i face the same issue.
I need to add `-- --host` option to command line `npm run dev` to expose on `localhost:5173`

**Comment by huseeiin** [comment]
I'm getting the same `<Root> was created without expected prop 'form'` error when using `return error(404)`

**Comment by huseeiin** [comment]
> I'm getting the same `<Root> was created without expected prop 'form'` error when using `return error(404)`

it only happens with `export const ssr = false` though
