### ISSUE TITLE
Template string in `import.meta.glob` yields no results

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#8490]
### Describe the bug

There's still a problem with #6239. Escaping parens in `import.meta.glob` goes wrong for template strings.

```
Object.keys(
  import.meta.glob('./\\(demos\\)/*/+page.{svx,md,svelte}')
).length
>>> 11

Object.keys(
  import.meta.glob(`./\\(demos\\)/*/+page.{svx,md,svelte}`)
).length
>>> 0
```

### Reproduction

See the console logs in this repro:

https://stackblitz.com/edit/sveltejs-kit-template-default-skkkob?file=src/routes/+page.js

### System Info

```Shell
StackBlitz
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is a [Vite issue](https://github.com/vitejs/vite/issues/11824), not a SvelteKit issue — closing
