### ISSUE TITLE
Typescript error TS2554 ("Expected 2 arguments, but got 1.") not thrown on boilerplate repo

### ISSUE THREAD

**Issue by Arro** [sveltejs/kit#8491]
### Describe the bug

I created a svelte-kit demo app using a `npm create svelte@latest jan-11` command. 

I selected "SvelteKit demo app" to the first question, yes to typescript, yes to eslint, yes to prettier, and no to the rest.

I'm also learning typescript, so I'm stepping through the typescript handbook while I do this.   From [one of the first pages of the handbook](https://www.typescriptlang.org/docs/handbook/2/basic-types.html) they have this example:

```
// This is an industrial-grade general-purpose greeter function:
function greet(person, date) {
  console.log(`Hello ${person}, today is ${date}!`);
}
 
greet("Brendan");
```

Therefore, I changed `src/routes/+page.svelte` begin with the following:

```
<script lang="ts">
	import Counter from './Counter.svelte';
	import welcome from '$lib/images/svelte-welcome.webp';
	import welcome_fallback from '$lib/images/svelte-welcome.png';

	// This is an industrial-grade general-purpose greeter function:
	function greet(person, date) {
		console.log(`Hello ${person}, today is ${date}!`);
	}

	greet('Brendan');
</script>
```

Running `tsc` outputs nothing.  Running `eslint .` outputs nothing.  

Running `npm dev`, I get the following:

```
  VITE v4.0.4  ready in 448 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Hello Brendan, today is undefined!
Hello Brendan, today is undefined!
10:56:36 AM [vite-plugin-svelte] ssr compile done.
package files     time     avg
jan-11      5   65.2ms  13.0ms
```

**Why would a typescript error not be thrown there?**

Creating an empty directory with a single `hello.ts` file with just the greeter function and invocation, you do see the following:
```
hello.ts:6:1 - error TS2554: Expected 2 arguments, but got 1.

6 greet("Brendan");
  ~~~~~~~~~~~~~~~~

  hello.ts:2:24
    2 function greet(person, date) {
                             ~~~~
    An argument for 'date' was not provided.


Found 1 error in hello.ts:6
```

### Reproduction

See description.

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 924.47 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /opt/homebrew/opt/node@16/bin/node
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.11 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
`tsc` can't handle Svelte files, that's why we built `svelte-check` which can handle both TS and Svelte files. It should be part of your package.json , the script to invoke it is named `check`

**Comment by Arro** [comment]
aha! thanks!

**Comment by Arro** [comment]
is there a way to make eslint run `svelte-check`, though?
