### ISSUE TITLE
`esm_env.DEV` returning `false`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#8492]
### Describe the bug

`esm_env.DEV` is returning `false` when running `pnpm dev` in sites/kit.svelte.dev

### Reproduction

Put the following inside `render_response` in `render.js`
```
console.log(`DEV? ${DEV}`);
```

Run `pnpm dev` in sites/kit.svelte.dev

### System Info

```Shell
`master`
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment]
Vite seems to be resolving the imports from `vite.config.js` without any conditions. This seems like a Vite bug

**Comment by benmccann** [comment]
I think we need to add `conditions: ['development']` here:

https://github.com/vitejs/vite/blob/e58a4f00e201e9c0d43ddda51ccac7b612d58650/packages/vite/src/node/config.ts#L939

**Comment by Rich-Harris** [comment]
Vite shouldn't be setting any conditions when loading `vite.config.js`, surely? It should be treating it as a native Node module. I'm not sure what you mean. I don't think there's a bug here.

**Comment by Rich-Harris** [comment]
Regardless, the import isn't coming via `vite.config.js`. I'm confused by this issue

**Comment by Conduitry** [comment]
Is there a repro that doesn't involve editing compiled code and seeing what it does?

**Comment by Rich-Harris** [comment]
In any case, I just checked and https://github.com/vitejs/vite/pull/11679 doesn't fix this issue (would have been alarming if it did tbh, since that would have meant that SvelteKit was getting bundled during the config bundling step)

**Comment by benmccann** [comment]
Vite is executing esbuild to bundle the `vite.config.js`. esbuild by default has no conditions and so you need to provide whether it's `development` or `production`. The `vite.config.js` imports stuff from `@sveltejs/kit/vite` and it looked like it was reading `esm_env.DEV` then.

Thanks for testing. It sounds like there may be something else I need to fix as well.

**Comment by benmccann** [comment]
Ok, I think I found the bug. I believe the problem is that this line doesn't go through Vite where I'd expect it to call `vite.ssrLoadModule` instead of `import`:

https://github.com/sveltejs/kit/blob/301aec9f000a212a72dcd4936cc14c9ad6539e0c/packages/kit/src/exports/vite/dev/index.js#L46

**Comment by Rich-Harris** [comment]
Yeah, at present runtime server code runs in Node. This would change if we merge #8429

**Comment by benmccann** [comment]
This appears to be fixed since #8429 was merged.

The only question I have before we close this is whether this line should change:

https://github.com/sveltejs/kit/blob/37ed70bdb6d32ac79e73099169f4ef706d7747ab/packages/kit/src/runtime/server/page/render.js#L80

It sounded like @dummdidumm added that as a workaround for detecting `DEV` in https://github.com/sveltejs/kit/pull/8478. Now that it's working, maybe we can remove the workaround and just use `DEV`?

**Comment by dummdidumm** [comment]
There's no workaround, it's just that we should add a "if dev mode" check to the if condition (though for dead code elimination and because it's available anyway now we could also use `__SVELTEKIT_DEV__`

**Comment by benmccann** [comment]
I would expect `esm-env` should also work for dead code elimination, but I haven't tested. Either solution is fine though

I'll send a PR and close this issue. Thanks!

**Comment by Rich-Harris** [comment]
DCE works with `esm-env`, but not this...

```js
export function thing({ dev }) {
  if (dev) {
    do_some_stuff();
  }

  // ...
}
```

...which is what we'd have to do in order to make dev vs prod behaviour unit testable
