### ISSUE TITLE
a `<svelte:script>` comparable to Next.js `Script` tag?

### ISSUE THREAD

**Issue by tx0c** [sveltejs/kit#8495]
Is it worthy to have a `<svelte:script>` comparable to Next.js `Script` tag?

```svelte
<svelte:script
  // a strategy to early load to insert in head before all other script, or lazy load at end of body;
  strategy="beforeInteractive | afterInteractive | lazyOnload | worker | ..."
  async
  src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxx"
  on:load={() => {
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'G-xxxxxx');
  }}
 />
```

or extend current `<svelte:body>` to allow a content, and just leave whatever inside to the end of html body?

```svelte
<svelte:body
  on:mouseenter={handleMouseenter}
  on:mouseleave={handleMouseleave}
  use:someAction

  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxx"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());
    gtag('config', 'G-xxxxxx');
  </script>
/>
```

_Originally posted by @tx0c in https://github.com/sveltejs/kit/discussions/8306#discussioncomment-4574813_

**Comment by Rich-Harris** [comment]
You can already put scripts in your components - just make sure they're not at the top level (ie they need to be inside a wrapper element). But is there any reason you wouldn't put that in `src/app.html`?

**Comment by xmlking** [comment]
when we want to share such code as reusable  component.
I felt I needed such capability, when I was implementing following component:
 https://github.com/xmlking/svelte-starter-kit/blob/main/src/lib/components/Analytics.svelte
Otherwise I had to use some hacks `document.currentScript.getAttribut`

**Comment by Rich-Harris** [comment]
Gotcha. As I say, putting the script inside an element (like `<svelte:head>` in `Analytics.svelte`) is the intended solution, so I'll close this

**Comment by tx0c** [comment]
but there's a reason in some cases better to be at end of `body` not `head`, and Svelte should have a solution for that

Quote from https://stackoverflow.com/a/38407984

> In short and simple language:

Place script that impacts the render of the page at the end of the body

> But is there any reason you wouldn't put that in src/app.html?

Yes, because `src/app.html` is only 1 global impacting all pages, but in my project only part of pages need a special script before end of body

Please re-open

**Comment by tx0c** [comment]
just google search `why put script end of body not head?`

got many reasons, this is from https://levelup.gitconnected.com/all-about-script-87fea475b976

> The best practice is to put JavaScript <script> tags just before the closing </body> tag rather than in the <head> section of your HTML. The reason for this is that HTML loads from top to bottom. The head loads first, then the body, and then everything inside the body.

@Rich-Harris please re-open

**Comment by Rich-Harris** [comment]
I'm not going to reopen this issue. There's a variety of ways you can get the `<script>` to the bottom of the page, but in your case since you're using the `async` attribute it simply doesn't matter.

**Comment by ryanwi** [comment]
> There's a variety of ways you can get the <script> to the bottom of the page

as a newcomer to sveltekit, with a background in server side rendering of html (Rails-style rendering), what are these ways?  I'm looking to output some `<script>` tags to page and am not clear on the options.

similar goals as was mentioned above:

* only want to output those on one page, not all pages
* I'm trying to put it before the </body> tag as was mentioned here
* like this, but this fails as y'all probably know
* tried `if browser` check, but the scripts weren't rendered in the browser
* onMount seems heavy to just output something in the html, so I haven't tried that yet

```
<script>
	/** @type {import('./$types').PageData} */
	export let data;
</script>

<svelte:head>
  <script type="text/javascript" src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pako/2.1.0/pako.min.js"></script>  
</svelte:head>

<h1 class="text-4xl mb-4 mt-4 font-extrabold">Room</h1>

<div>
  <p>Data</p>
  <p>{JSON.stringify(data)}</p>  
</div>

<div>
  <p>Room</p>
  <p>{JSON.stringify(data.room)}</p>  
</div>

<!-- this should be in the rendered html,  not processed on the server -->
<script type="text/javascript">
  const _token = "{data.session?.accessToken}";
  const _host = "hostfromenv";
</script>
<script type="text/javascript" src="[external-script]"></script>
```

I'm missing something key to the SvelteKit, component world, so any further tips are appreciated.
