### ISSUE TITLE
application/xml is reported as Invalid Content-Type

### ISSUE THREAD

**Issue by ezcamlive** [sveltejs/kit#852]
I am running pnpm run start command and it frequently crashes when a request comes in with content type application.xml. Can you please include code to support other unknown content types to handle this gracefully?

Error: Invalid Content-Type application/xml
    at get_body (file:///landing/node_modules/.pnpm/@sveltejs/kit@1.0.0-next.61_svelte@3.35.0+vite@2.1.3/node_modules/@sveltejs/kit/dist/chunks/index.js:111:10)

**Comment by babichjacob** [comment]
This sounds like a worthwhile problem to solve, but we'll need you to re-do this issue with the bug report template properly filled out (including repository that reliably reproduces it) so we can investigate.
