### ISSUE TITLE
In the new `app.d.ts` I cannot `declare module` anymore now

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#8527]
### Describe the bug

Before the latest updates on file `app.d.ts` I was using:

```ts
declare namespace App {
  // interface Error {}
  // interface Locals {}
  interface PageData {
    // Some here...
  }
  // interface Platform {}
}

declare module "custom/project";
declare module "another/project";
```

Now the new `app.d.ts` is like this:

```ts
declare global {
  namespace App {
    // interface Error {}
    // interface Locals {}
    interface PageData {
      // Some here...
    }
    // interface Platform {}
  }
}

export {};

declare module "custom/project";
declare module "another/project";
```

The `declare module` lines don't work anymore: I get missing types error in my app's code.

How to fix?

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.13.0
    npm: 8.19.3
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
  npmPackages:
    @sveltejs/adapter-static: 1.0.2 => 1.0.2
    @sveltejs/kit: 1.1.0 => 1.1.0
    svelte: 3.55.1 => 3.55.1
    vite: 4.0.4 => 4.0.4
```

### Severity

blocking an upgrade

**Comment by dummdidumm** [comment]
In your case just remove `export {}` , that makes the file an ambient module again.

Giving this the documentation label because we should note that somehow.

**Comment by Rich-Harris** [comment]
You can also create a separate file, `src/ambient.d.ts` or whatever, for the `declare module` stuff. That way the behaviour of `app.d.ts` won't change if you later need to add an `import` (which would turn it back into a module).

Honestly, this aspect of TypeScript is confusing as hell. Wish the distinction was more explicit — `"use ambient";` or something.

**Comment by frederikhors** [comment]
Yes Rich. Is very confusing. Can we write a docs about this?
