### ISSUE TITLE
Static adapter build showing Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by Mrbeyond** [sveltejs/kit#8528]
### Describe the bug

Using static adapter, the build was successful and I preview works perfectly but when deployed on nginx as static files, the app keeps showing "500 internal error" with the error [ SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON ] on the console.

This started after I upgraded the app the the official version 1.0

I was working perfectly 

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-fsnfkn?file=src/routes/+layout.svelte

### Logs

```Shell
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
```

### System Info

```Shell
"devDependencies": {
		"@playwright/test": "^1.28.1",
		"@sveltejs/adapter-auto": "^1.0.0",
		"@sveltejs/adapter-static": "^1.0.2",
		"@sveltejs/kit": "^1.0.0",
		"@typescript-eslint/eslint-plugin": "^5.45.0",
		"@typescript-eslint/parser": "^5.45.0",
		"autoprefixer": "^10.4.13",
		"axios": "^1.2.2",
		"cssnano": "^5.1.14",
		"eslint": "^8.28.0",
		"eslint-config-prettier": "^8.5.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.21",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"sass": "^1.57.1",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"svelte-preprocess": "^5.0.0",
		"tailwindcss": "^3.2.4",
		"tslib": "^2.4.1",
		"typescript": "^4.9.3",
		"vite": "^4.0.0",
		"vitest": "^0.25.3"
	},
```

### Severity

annoyance

### Additional Information

I have tested this with two different projects with the same issue.

**Comment by Rich-Harris** [comment]
Please include a reproduction, not a link to a working Stackblitz project that would _presumably_ reproduce the issue with your nginx config.

When you do it, make sure it's a minimal reproduction and not a kitchen sink project like the one above.

For future reference, the 'system info' section should contain the output of running

```
npx envinfo --system --binaries --browsers --npmPackages "{svelte,@sveltejs/*,vite}"
```

as specified in the [issue template](https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml), not a copy-paste dump of part of your package.json.

**Comment by Mrbeyond** [comment]
@Rich-Harris Thanks for your intervention on this, I have cracked the issue, it because of hook.server.ts file and prerender = true clause in +layout.ts
