### ISSUE TITLE
Anchor image in docs = 404ing

### ISSUE THREAD

**Issue by acoyfellow** [sveltejs/kit#853]
**Describe the bug**
The anchor image inside of the links seems to be 404'ing:
https://kit.svelte.dev/icons/link.svg - used in docs

**Logs**
![image](https://user-images.githubusercontent.com/1666099/113479518-9a81cf80-945d-11eb-9383-cc999d4011ba.png)

**To Reproduce**
Visit https://kit.svelte.dev/docs to see no image +
click https://kit.svelte.dev/icons/link.svg to see 404

**Severity**
Minor

**Comment by Conduitry** [comment]
https://github.com/sveltejs/sites/issues/13

This would be handled in the sites repo, not here. But this should be a pretty easy fix.
