### ISSUE TITLE
Documentation incorrectly specifies all options as optional

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#854]
**Describe the bug**
Commenting out `adapter:` prop in `svelte.config.cjs` throws error:

```
> Using undefined
> adapt is not a function
TypeError: adapt is not a function
    at adapt (file:///C:/kit/node_modules/@sveltejs/kit/dist/chunks/index6.js:768:8)
    at file:///C:/kit/node_modules/@sveltejs/kit/dist/cli.js:633:11
```

**Expected behavior**
I read https://kit.svelte.dev/docs#configuration:

> All values are optional.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

System:
OS: Windows 10 10.0.19042
Binaries:
Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
npmPackages:
@sveltejs/kit: 1.0.0-next.70 => 1.0.0-next.70
svelte: 3.37.0 => 3.37.0
vite: 2.1.5 => 2.1.5

- Your adapter: Nothing
</details>

**Additional context**
I need a way to build my project as if I were using the [`sveltejs/template`](https://github.com/sveltejs/template) seed.

**Comment by ignatiusmb** [comment]
All options are indeed optional, you'll need to read more for each of the options, in this case https://kit.svelte.dev/docs#configuration-adapter and https://kit.svelte.dev/docs#adapters.
