### ISSUE TITLE
[DOCS] Supported environments can seem contradictory

### ISSUE THREAD

**Issue by netaisllc** [sveltejs/kit#8543]
### Describe the bug

To me, the docs section in the attached screen shot is pretty confusing:

![Screen Shot 2023-01-14 at 8 04 07 PM](https://user-images.githubusercontent.com/1242423/212567682-9a365f94-0e5d-4d12-b189-832b2b7fb2ba.png)

Elaboration: 
* the "not-orange" part implies you can deploy Cloudflare Pages, Netlify or Vercel _using only the default adapter._ (indeed, the Vercel adapter readme basically says this.)
* but the "orange" part makes it seem like you _should install/use_ the named adapter

Actual experience with Kit & Vercel has shown me that the vercel-adapter isn't needed (unless platform specific features are used), so maybe consider an edit to clarify things.

### Reproduction

N/a

### Logs

```Shell
N/a
```

### System Info

```Shell
N/a
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This is now covered in https://kit.svelte.dev/docs/adapter-auto
