### ISSUE TITLE
Netlify adapter https imports in api too

### ISSUE THREAD

**Issue by andrei0x309** [sveltejs/kit#8569]
### Describe the problem

So using the Netlify adapter with edge enabled I saw it's possible to import external libs like in `+page.server.ts` like: 
`import { createClient } from "https://esm.sh/@supabase/supabase-js";` 

But it is not possible to do the same in APIs file like `routes/api/test/+server.ts` because you'll get at build: `Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. Received protocol 'https:'` would be nice if it was possible to run API on deno too.

I see that network imports are coming in node too, I don't know if that later will fix the issue.

### Describe the proposed solution

Would be nice if this feature could be implemented so you can run API under deno too, not sure if is possible by changing the adapter only. 

Also maybe a potential workaround is just to use directly Netlify edge functions I didn't try that to see how it goes. 

### Importance

nice to have

**Comment by andrei0x309** [comment]
LE for other users:
The workaround works:
example `netlify.toml`:
```
[build]
  command = "npm run build"
  publish = "build"
  edge_functions = "edge-functions"

[[edge_functions]]
  path = "/edge-api/email"
  function = "email"
 ```
 
and for example in email.ts you can do HTTPS imports from `denoland` or `esm.sh` or other compatible sources and will work provided that the lib works with the Netlify Deno limitations, will not break the render function deployed by svelteKit and will be deployed as edge functions alongside the render one from svelteKit.

Probably the adapter could deploy functions from `routes/api` but since you can do it manually probably is not a very big priority.

**Comment by Rich-Harris** [comment]
I don't understand — you're saying an import from `https://esm.sh/@supabase/supabase-js` works in a `+page.server.ts` but not a `+server.ts`? There's no reason it should work in one but not the other, so this issue would benefit from a reproduction if you're able to create one

**Comment by andrei0x309** [comment]
@Rich-Harris 
So on further inspection, it just so happens that the `supabase` local node lib works in edge deno too.
That means that in reality, https module imports(network imports) work neither in `+page.server.ts` nor `+server.ts` as it will break the build - `ERR_UNSUPPORTED_ESM_URL_SCHEME` ( though as an edge function deployment should work in theory).

So yeah the only way to use external libs in svelteKit on edge is to use local node libs and hope it works on Deno too.
And for a json REST API you can deploy additional edge functions ( besides the render deployed by svelteKit adapter for SSR) where external https module imports will work.   

I made a quick repo here: https://github.com/andrei0x309/sk-deno-api-route

As a matter of fact, I don't know if this can be overcome somehow, in order to not break the build, might be very complicated, and node already offers experimental network imports in v19+, so with time this will be resolved by itself might take 2 years until the features will reach LTS status though 😢 

So I guess this can be closed.

**Comment by Rich-Harris** [comment]
This feels like the sort of thing that could probably be fixed with a Vite plugin. I'm not sure if an appropriate one already exists or if it would need to be created

**Comment by andrei0x309** [comment]
In case someone discovers this issue. 

This will also work if you don't want to deploy standalone edge functions, will be much better than trying to use Vite to transform imports:

```json
	"scripts": {
		"build": "node --experimental-network-imports ./node_modules/vite/bin/vite build",
	},
```
