### ISSUE TITLE
Cannot find package '...' imported from on netlify deployment

### ISSUE THREAD

**Issue by BetaConnector** [sveltejs/kit#858]
**Describe the bug**
I am trying to write to faunaDB on a netlify hosted application.

I added faunadb to my dependencies:
```json
"dependencies": {
     "faunadb": "^4.1.3"
}
```

I also tried different Settings within vite:
```js
vite: {
      ssr: {
          noExternal: Object.keys(pkg.dependencies || {}),
      }
}
```
But this leads me to the following error:
```
Cannot read property 'custom' of undefined
TypeError: Cannot read property 'custom' of undefined
    at file:///home/alex/dev/testApp/.svelte/output/server/app.js:2825:50
```

```js
var customInspect = nodeUtil && nodeUtil.inspect.custom;
```

So if I left the vite-objtions blank for now.

**Expected behavior**
I would that the node module can be found within the function.

**Information about your SvelteKit Installation:**
I created a repo here, as a minimal example:
https://github.com/BetaConnector/sveltekit-test/

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900KS CPU @ 4.00GHz
    Memory: 8.05 GB / 15.54 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0

Your adapter: netlify
</details>

**Comment by Aias** [comment]
I'm having similar problems with the netlify adapter. The site builds and deploys fine, but has trouble actually executing the function. Returns the following error:

```
{"errorType":"Error","errorMessage":"Cannot find package 'remarkable' imported from /var/task/src/app.mjs","trace":["Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'remarkable' imported from /var/task/src/app.mjs","    at packageResolve (internal/modules/esm/resolve.js:650:9)","    at moduleResolve (internal/modules/esm/resolve.js:691:18)","    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:784:11)","    at Loader.resolve (internal/modules/esm/loader.js:100:40)","    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)","    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)","    at link (internal/modules/esm/module_job.js:46:36)"]}
```

I'm not sure if it's something to do with remarkable specifically, or if that's just the first package the module resolution fails on.

**Comment by BetaConnector** [comment]
@Aias, the problem ist that witin a function an import won't work. As far as I understood, the package _remarkable_ needs to be bundled within your project.

You have to add it to dependencies instad of devDependencies and you have to tell vite to bundle those dependencies:
```js
vite: {
      ssr: {
        noExternal: Object.keys(pkg.dependencies || {}),
      },
    },
```

**Comment by Aias** [comment]
@BetaConnector Interesting, yeah I tried with vercel and got the same error so apparently not an issue specific to the netlify adapter. 

Remarkable is listed in my dependencies, not devDependencies (see [package.json here](https://github.com/Aias/barnsworthburning/blob/95a66040489724e5b7ec534f0673b99527b8a09b/package.json)) and still get the error. I'll try the code you've linked above and see if it works. I'm a little surprised that I have to manually specify that the package needs to be included though, I assumed the fact that it's imported within my svelte components would be enough to signal to vite that it needs to be bundled. I'll have to read up more on how vite works apparently.

**Comment by icecog** [comment]
For the next one who finds this thread and, like me, had issues figuring out where things were supposed to go here is a complete `svelte.config.cjs`

```cjs
const preprocess = require('svelte-preprocess');
const adapter = require('@sveltejs/adapter-static');
// const adapter = require('@sveltejs/adapter-node');
const pkg  = require('./package.json');

/** @type {import('@sveltejs/kit').Config} */
module.exports = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		adapter: adapter({}),
		vite: {
			ssr: {
				noExternal: Object.keys(pkg.dependencies || {}),
			},
		},
	},
};

```

**Comment by esyon** [comment]
@Aias, within vercel everything works as expected. You need to remove the ssr-attribute. In vercel it's not required that everything is bundled within your project.

**Comment by ignatiusmb** [comment]
I'm pretty sure this is fixed on the latest version, can you try with the latest template? We've ditched the `vite.ssr.noExternal` config, so dependencies shouldn't be bundled anymore.

Closing, but we can revisit and reopen this if the problem still persists.
