### ISSUE TITLE
SSR of page that imports a large file causes huge spike in memory usage

### ISSUE THREAD

**Issue by FeldrinH** [sveltejs/kit#8592]
### Describe the bug

During the initial server side render of a page that imports a large file the server memory usage spikes to approximately 100x the size of the file. On my system this causes node to run out of memory and crash when importing files larger than 30MB. 

This seems to happen for imported JSON files as well as text files imported using Vite's `?raw` parameter.

Curiously the memory usage spike only seems to occur when using the dev server (`npm run dev`). It does not occur when building the project with `npm run build` and then using the preview server (`npm run preview`).

The memory usage spike also does not seem to occur during client side rendering. If you navigate to the page that imports the large file using a client side routed link and the import happens on the client everything works fine.   

### Reproduction

https://github.com/FeldrinH/sveltekit-oom-repro

### Logs

```Shell
C:\...\sveltekit-oom-repro>npm run dev

> sveltekit-oom-repro@0.0.1 dev
> vite dev



  VITE v4.0.4  ready in 707 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

<--- Last few GCs --->

[14108:0000027B8A881300]    97882 ms: Mark-sweep 2035.1 (2081.8) -> 2035.1 (2081.8) MB, 984.5 / 0.0 ms  (average mu = 0.218, current mu = 0.010) allocation failure; scavenge might not succeed
[14108:0000027B8A881300]    99854 ms: Mark-sweep 2050.9 (2081.8) -> 2050.9 (2113.8) MB, 1964.3 / 0.0 ms  (average mu = 0.111, current mu = 0.004) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6DE509E7F node_api_throw_syntax_error+175967
 2: 00007FF6DE490C06 SSL_get_quiet_shutdown+65750
 3: 00007FF6DE491FC2 SSL_get_quiet_shutdown+70802
 4: 00007FF6DEF2A214 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF6DEF15572 v8::Isolate::Exit+674
 6: 00007FF6DED973CC v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF6DED945EB v8::internal::Heap::CollectGarbage+3963
 8: 00007FF6DEDAA823 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF6DEDAB0CD v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF6DEDBA903 v8::internal::Factory::NewFillerObject+851
11: 00007FF6DEAABEB5 v8::internal::DateCache::Weekday+1349
12: 00007FF6DEFC78B1 v8::internal::SetupIsolateDelegate::SetupHeap+558193
13: 00007FF65F2BE29A

C:\...\sveltekit-oom-repro>
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.68 GB / 7.87 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.75
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.1
    @sveltejs/kit: ^1.0.0 => 1.1.3
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by tcc-sejohnson** [comment]
I couldn't repro this, though my machine is on steiroids. The first SSR page load did take a while while Vite imported the large file, but it worked fine. Maybe a Windows issue? Would be good to get some others to try to repro this.

**Comment by FeldrinH** [comment]
> I couldn't repro this, though my machine is on steiroids. The first SSR page load did take a while while Vite imported the large file, but it worked fine.

How much was the peak memory usage during import? I can also for example import 20 MB files but the memory usage jumps from less than 100 MB to 2000 MB during the initial render, which even if no crash occurs seems like a very large amount of memory needed just to import a 20 MB file with no real processing steps.

**Comment by Rich-Harris** [comment]
Like @tcc-sejohnson I'm not getting an OOM, but I can see the spike in memory usage.

Unfortunately it's a Vite issue rather than a SvelteKit issue, so it's mostly out of our hands. You can verify this by creating a project with these two files...

```js
// package.json
{
  "dependencies": {
    "vite": "^4.0.4"
  },
  "type": "module"
}
```

```js
// index.js
import * as vite from 'vite';

const server = await vite.createServer();

const before = process.memoryUsage().heapUsed;
await server.ssrLoadModule('./largefile.txt?raw');
const after = process.memoryUsage().heapUsed;

console.log('Memory usage:', after - before);
```

...along with `largefile.txt`, and running `node index.js`. I get the following result:

> Memory usage: 3061288728

(in other words around 3Gb)

It might be worth opening an issue on the [Vite tracker](https://github.com/vitejs/vite/issues) to see if there's anything that can be done to make `ssrLoadModule` use less memory.

**Comment by FeldrinH** [comment]
I have opened an issue on the Vite tracker (https://github.com/vitejs/vite/issues/11745).

**Comment by Rich-Harris** [comment]
Excellent, thank you - will close this since there's not much we can do beyond wait for a fix in Vite
