### ISSUE TITLE
[docs] External images won't load because of `CORB`

### ISSUE THREAD

**Issue by msonnberger** [sveltejs/kit#8598]
### Describe the bug

I noticed that on the Vercel adapter docs page, `settings.png` isn't displayed in the "Node version" section. Chrome shows a warning in the console that this is due to `Cross-Origin Resource Blocking`. [This page](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#observable-corb-impact-on-images) explains that when an `<img>`'s `src` has `x-content-type-options` set to `nosniff` and a (wrong) `content-type: text/html` header (which both applies to that image), CORB will block the response

### Reproduction

- Visit https://kit.svelte.dev/docs/adapter-vercel#notes-node-version
- "Vercel project settings" alt text is displayed instead of the actual image

### Logs

```Shell
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://github.com/sveltejs/kit/blob/master/packages/adapter-vercel/settings.png with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 90.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.n/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 8.19.3 - ~/.n/bin/npm
  Browsers:
    Firefox Developer Edition: 110.0
    Safari: 16.2
```

### Severity

annoyance

### Additional Information

Can reproduce in Arc (Chromium), Firefox and Safari

**Comment by dominikg** [comment]
Introduced by https://github.com/sveltejs/kit/pull/8531

Maybe colocate assets needed for docs to avoid this. Some links are also absolute (they had to be when it was in the adapters readme) that can now be relative.
