### ISSUE TITLE
Adapter-Vercel has incorrect documentation

### ISSUE THREAD

**Issue by DrewDaPilot** [sveltejs/kit#860]
Good evening,

I just recently noticed that the vercel adapter tells you to run `npm i` after adding the adapter to your dev dependencies. This guidance should be removed in favor of a `pnpm i` or `pnpm i @sveltejs/adapter-vercel` as the `npm` version of the command does not properly install the adapter.

**Comment by Conduitry** [comment]
If npm doesn't correctly install the Vercel adapter, that sounds like a bug, not something that should be documented around. What specifically are you seeing when you use npm to install it?

**Comment by DrewDaPilot** [comment]
Sorry about that, I just assumed the issue was related to the project structure and the use of another package manager. I dont exactly recall the error message but I remember that pnpm install seemed to fix the issue. If you would like I can try to reproduce the issue in the event that someone else encounters it in the future.

**Comment by antony** [comment]
If you can reproduce the issue, I'd be happy to take a look. I don't know of any reason you'd be asked to, or need to run `npm install` after adding an adapter though.

**Comment by DrewDaPilot** [comment]
I cant seem to reproduce this, however I have encountered a few other bugs with sveltekit. I will close this issue now and open any other issues accordingly. Sorry for the inconvienience.
