### ISSUE TITLE
Type guards in templating using Typescript with strict enabled

### ISSUE THREAD

**Issue by fleimisch** [sveltejs/kit#8608]
### Describe the bug

Hi,

SvelteKit by default comes with strict Typescript enabled, which is included in templating. I'm getting type errors if I do this:
_Error: Parameter 'e' implicitly has an 'any' type._
`<div on:keyup={(e) => someFunction(e)}></div>`

If I then add a type guard or add "any" to ignore it, then I get a syntax error
`<div on:keyup={(e:any) => someFunction(e)}></div>`
_Error: Unexpected token
If you expect this syntax to work, here are some suggestions: 
If you use typescript with `svelte-preprocess`, did you add `lang="ts"` to your `script` tag? 
Did you setup a `svelte.config.js`?_

Is this a (un)known bug or I'm missing something?

Thank you,
Nate

### Reproduction

Put `<div on:keyup={(e) => someFunction(e)}></div>` or `<div on:keyup={(e:any) => someFunction(e)}></div>` anywhere with typescript strict enabled.

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 42.32 GB / 63.92 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.75
    Edge: Spartan (44.22621.1105.0), Chromium (109.0.1518.55)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.1 
    @sveltejs/adapter-static: ^1.0.4 => 1.0.4 
    @sveltejs/kit: ^1.0.0 => 1.1.3 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This is unrelated to SvelteKit, this is a tooling issue - although not one I can reproduce. Which IDE are you using and what Svelte-related extensions do you have installed.

(Closing this, but happy to answer further questions)

**Comment by fleimisch** [comment]
Hey, thank you for your reply. I'm using VSCode 1.74.3 with Svelte for VS Code extension, no other extensions.

> For the second case - using type annotations inside the template - that's not supported yet.

Right, I wasn't expecting it too, but it's forcing me to provide types for some reason:
![image](https://user-images.githubusercontent.com/6266369/213555471-43989216-8426-47bb-94ec-4efc908c1bcc.png)

This is a fresh out of the box svelte@latest instance installed two days ago.
