### ISSUE TITLE
Deprecation warning upon installing project

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#8611]
### Describe the bug

It's coming from svelte-check -> svelte-preprocess -> sorcery -> sourcemap-codec

### Reproduction

I installed the demo app with TypeScript support and then ran `npm install`

### Logs

```Shell
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

### System Info

```Shell
latest
```

### Severity

annoyance

**Comment by benmccann** [comment]
Hmm https://www.npmjs.com/package/sorcery hasn't been updated in 7 years. It sounds a bit like `magic-string`. Was it a precursor to it?

**Comment by Rich-Harris** [comment]
no, totally separate. i'll update the package to use `@jridgewell/sourcemap-codec`

**Comment by dummdidumm** [comment]
Just please don't remove commonjs at the same time 😅 svelte-preprocess which depends on it is commonjs so couldn't use it if it became esm.

**Comment by Rich-Harris** [comment]
lol i was about to do exactly that. i guess i can add a prepublish `esbuild` step since it only exports `default`

**Comment by benmccann** [comment]
CJS can use ESM code though. It shouldn't be an issue should it? I would still make it ESM-only personally. We should probably update svelte-preprocess to be ESM as well anyway

**Comment by dummdidumm** [comment]
I mean you could do minor release to swap out the package and then another major release to remove commonjs; `svelte-preprocess` and all other commonjs modules can then happily use the previous major version without getting deprecation warnings

**Comment by Rich-Harris** [comment]
it's a 7 year old package — one does not simply swap things out... it needs some fairly drastic surgery to get things back into a publishable state (you can't even run `npm install` in that repo as things stand)

**Comment by Rich-Harris** [comment]
> CJS can use ESM code though

nope, other way round

**Comment by Rich-Harris** [comment]
`import()` is synchronous, and you can't use top-level await in CJS. in certain circumstances that's okay but not in the general case. if the goal is to make a library consumable by CJS consumers you can't rely on that

**Comment by dummdidumm** [comment]
My hope would be that, since you only need to swap out the depending package (it has the same signature AFAIK), you wouldn't need to touch anything else.

**Comment by Rich-Harris** [comment]
That was my hope too!

**Comment by Rich-Harris** [comment]
ok fuck it, this was taking too long. i swapped out the packages and did the minimal changes necessary to get it to publish — the tests don't pass, and the package is a mess, but at least we can get rid of the deprecation warning now

**Comment by Conduitry** [comment]
This should be good to go now with the release of `svelte-preprocess@5.0.1`.
