### ISSUE TITLE
Dynamic Server Site Generation

### ISSUE THREAD

**Issue by oneacik** [sveltejs/kit#8638]
### Describe the problem

I want to generate static pages from md files like I can do in gatsby or Next.js

### Describe the proposed solution

Normally, I would just define pages to prerender by returning them from some server function after scanning the directory.
You can just use similar approach as in next.js.
https://nextjs.org/docs/basic-features/pages#scenario-2-your-page-paths-depend-on-external-data

### Alternatives considered

I could use just server side rendering, but I wouldn't be able then to host those pages on static providers like github pages.

### Importance

i cannot use SvelteKit without it

**Comment by Rich-Harris** [comment]
Not sure I understand - what's stopping you?

**Comment by geoffrich** [comment]
You should take a look at the [prerendering](https://kit.svelte.dev/docs/page-options#prerender) docs, if you haven't already. SvelteKit supports prerendering your entire site to deploy to a static provider like GitHub pages.

**Comment by oneacik** [comment]
I have a case where I want to create a static digital garden like I can get from gatsby.
It uses markdown files as data source and generates in generation time static routes.

From what I understand from routing documentation, citing:
`src/routes/blog/[slug] creates a route with a parameter, slug, that can be used to load data dynamically when a user requests a page like /blog/hello-world`
means that this approach will `load data dynamically` therefore it will need to query markdown document for further processing from somewhere. 
So it is not a static page.

As I read @geoffrich comment I can see that some dynamic routes may be prerendered:
https://kit.svelte.dev/docs/page-options#prerender
However I assume that `auto` is done via some nasty heurestic and some pages will still need to be dynamically rendered.
So it is not fully static page.

In Next.js it is possible to define all possible *slug*s in generation time (for example by scanning markdown folder) so they will get statically generated. Therefore it may generate *fully static page* from "external" resources like markdown files. 

Is there some other idiomatic approach that I am missing?

**Comment by oneacik** [comment]
I have a case where I want to create a static digital garden like I can get from gatsby.
It uses markdown files as data source and generates in generation time static routes.

From what I understand from routing documentation, citing:
`src/routes/blog/[slug] creates a route with a parameter, slug, that can be used to load data dynamically when a user requests a page like /blog/hello-world`
means that this approach will `load data dynamically` therefore it will need to query markdown document for further processing from somewhere. 
So it may not be a static page.

As I read @geoffrich comment I can see that some dynamic routes may be prerendered:
https://kit.svelte.dev/docs/page-options#prerender
I see that `auto` option either crawls links or uses predefined list of pages.
As I cannot supply dynamic function to this predefined list of pages, therefore I can't scan for all possible paths
and generating this list by some external script seems not idiomatic.
So it may not be fully static page.

In Next.js it is possible to define all possible *slug*s in generation time (for example by scanning markdown folder) so they will get statically generated. Therefore it may generate *fully static page* from "external" resources like markdown files. 

Is there some other idiomatic approach that I am missing?

**Comment by s3812497** [comment]
You can configure the `config.kit.prerender.entries` in `svelte.config.js`

> If you do need to specify which pages should be accessed by the prerenderer, you can do so with the entries option in the prerender configuration.

https://kit.svelte.dev/docs/configuration#prerender

I've no experience with this, but is it possible to form a list of strings paths by using `fs` to scan your markdown folder?

**Comment by Rich-Harris** [comment]
Yep, you can certainly use `prerender.entries` for this. Though surely you'd want to link to these pages from elsewhere in your site anyway?

**Comment by oneacik** [comment]
@Rich-Harris @s3812497 
So it seems, but is it possible to put a function there?
Would community welcome such feature if it is impossible to supply a function?

@Rich-Harris in fact as you mentioned the quick workaround would be to generate a sitemap.

**Comment by Rich-Harris** [comment]
What would be different if it was a function that returned an array instead of an array?

**Comment by Rich-Harris** [comment]
Closing as it's not clear that there's anything that needs to happen here

**Comment by oneacik** [comment]
Sorry, I was doing test project for this case and it seems that sitemap is a go:
https://github.com/oneacik/svelte-static-digital-garden
I think I won't be pushing the topic further as workaround is working well.
