### ISSUE TITLE
[Question] Form Action Submission

### ISSUE THREAD

**Issue by devappbox** [sveltejs/kit#8642]
### Describe the problem

Hello, i am new to SvelteKit. I am using  the use:enhance form action. My question is how to display a dialog box so that i can choose to continue or cancel a submission

``````
<form
  method="POST"
  use:enhance={({ form, data, action, cancel }) => {

    //Call or Show Dialog Box with options to continue or cancel submission   
   
    return async ({ result, update }) => {
    };
  }}
>
``````

Thank you for the any advice

**Comment by Conduitry** [comment]
Please don't open issues for support requests.
