### ISSUE TITLE
Cookies API doesn't work with redirect helper in hooks

### ISSUE THREAD

**Issue by peng-devs** [sveltejs/kit#8643]
### Describe the bug

I have an auth token stored in cookies, and use hooks to validate the token.
When the token expires, it should clear the cookie and then redirect to the login page.
But it does not, the redirect is successful but the cookies still exist.
```
if (token_is_expired(token) {
  event.cookies.delete('auth');  // doesn't work
  event.cookies.set('auth', '', { maxAge: 0 });  // doesn't work either
  throw redirect(303, '/login');
}
```

### Reproduction

https://github.com/peng-devs/sveltekit-hooks-issue
1. `npm run dev` and visit `http://localhost:5173/login`
2. Click the login button
3. You'll be automatically returned to the login page (to simulate the token expired situation).
4. If the cookie is deleted, you'll see the login button, otherwise you'll only see the text 'already logged in'.

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 6.69 GB / 7.72 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    npm: 9.2.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2
    @sveltejs/kit: ^1.0.0 => 1.2.2
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by markjaquith** [comment]
See also #8316 — "redirect + set cookies"
