### ISSUE TITLE
launch.json vscode support

### ISSUE THREAD

**Issue by cognominal** [sveltejs/kit#865]
Generate an appropriate  .vscode/launch.json to better support running/debugging in vscode.
I don't know enough about svelte-kit and vscode to do it myself.
But somehow, that's the point : integrate svelte-toolkit in standard vscode workflow for noobs like me.

**Comment by antony** [comment]
I'm not convinced this is something we'd look to build into core, since not everybody uses vscode, so this wouldn't make sense for every developer.

**Comment by rmunn** [comment]
Not everyone uses VS Code, but it's a very popular tool for JS development so it's worth having a VS Code setup somewhere easy to find. Maybe it would be good to have a documentation section showing setups for various popular tools: VS Code, Atom, Vim/NeoVim, Emacs, plus whatever other editors are popular enough that someone writes a documentation PR to add their favorite editor's setup to the documentation.

**Comment by Leftium** [comment]
I created a [svelte-adder](https://github.com/svelte-add/svelte-add) that automates the steps for basic launch.json support: https://github.com/Leftium/vscode-preset
It's really just a simple [preset](https://preset.dev/).

To use it:
1. `npx apply Leftium/vscode-preset` (Adds files to project.)
2. `npm run dev` (Start dev server.)
3. Press F5 from VS Code to launch debug browser.

**Comment by ignatiusmb** [comment]
Supporting VSCode launch preset would mean we're open to other editor presets as well, which would increase the stuff we'd need to maintain. Looking at the activity in this thread, it doesn't look like there's a demand or people having the same problem.

Closing as there's also a community alternative, already available as well.
