### ISSUE TITLE
`<input type="reset" />` clears form instead of respecting values

### ISSUE THREAD

**Issue by angrytongan** [sveltejs/kit#8654]
### Describe the bug

Using `<input type="reset" />` on a form with hardcoded `value`s clears the form when it shouldn't.

### Reproduction

https://github.com/angrytongan/use-enhance-bug

1. Install

```
git clone https://github.com/angrytongan/use-enhance-bug
npm install
npm run dev
```

2. Browse to http://localhost:5173/reset

3. Press Reset.

Form is reset, but values shouldn't <s>not</s> change. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/reset

### System Info

```Shell
System:
    OS: macOS 12.6.2
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 272.98 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.7 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

Related to #8513 via #8404.

**Comment by NormandoHall** [comment]
BTW...

![image](https://user-images.githubusercontent.com/2943127/213894022-733f0692-3061-4995-bc24-260663ddbd8f.png)

**Comment by s3812497** [comment]
Might be worth moving this to the sveltejs/svelte repository. It’s an issue related to Svelte itself rather than SvelteKit.

**Comment by angrytongan** [comment]
Moved to https://github.com/sveltejs/svelte/issues/8220
