### ISSUE TITLE
As of @sveltejs/kit version 1.0.13, `crypto` doesn't seem to be polyfilled during build-time

### ISSUE THREAD

**Issue by mglikesbikes** [sveltejs/kit#8655]
### Describe the bug

Looks like prior to 1.0.13, `crypto` (the [webcrypto global](https://developer.mozilla.org/en-US/docs/Web/API/crypto_property)) was polyfilled. Now it doesn't seem to be. (Using `adapter-cloudflare-workers` if that makes a difference.)

For example: this code will prevent `vite build` from completing:

```if (typeof crypto === 'undefined') throw new Error('this explodes `vite build`')```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-zank98?file=README.md,src%2Froutes%2F%2Bpage.js,package.json&terminal=dev

Steps to repro:

1. Run `npm run build` with SK 1.0.12. Note it builds fine.
2. Run `npm i -D @sveltejs/kit@1.0.13`
3. Run `npm run build` and observe that `src/pages.js` throws an error because `crypto` is undefined

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.05 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/adapter-cloudflare-workers: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.4```
```

### Severity

blocking an upgrade

### Additional Information

Tried to debug this as best I could and it may be related to this PR: https://github.com/sveltejs/kit/pull/8429

> (edited for clarity per findings in comments)

**Comment by benmccann** [comment]
You could confirm whether it's that PR by testing with 1.0.3 and 1.0.4 and reporting whether or not they work

I would also be curious if either `typeof Deno === 'undefined'` or `typeof Bun === 'undefined'` evaluate to `true` on Cloudflare

**Comment by mglikesbikes** [comment]
Good tip — tracked it down to a version 1.0.13 which was this PR: https://github.com/sveltejs/kit/pull/8429

Stackblitz is updated as well.

**Comment by dummdidumm** [comment]
Problem is that `should_polyfill` is checked too late, it should happen in `postbuild/index.js` already since nodes are already loaded there. Let's wait for #8636 to land since that moves stuff around quite a bit, then fix this.

**Comment by JordanShurmer** [comment]
I [brought this up](https://github.com/sveltejs/kit/pull/8013#issuecomment-1405145473) in another issue, but it seems this is the most relevant issue.

I am seeing pretty much the same error described in here, except with the `fetch` object. Moving from `1.0.12` to `1.0.13` causes our builds to fail during the Prerendering step because **fetch is not defined**.

In our case, we actually want to disable prerendering entirely, so it's a little baffling why the prerendering is even happening.

**Comment by JordanShurmer** [comment]
The solution we're going with for now came from a Discord post, and some other issues related to prerendering:

We're using the `building` environment flag to just avoiding the code that was using `fetch`. Fortunately for us it was only in one place, so not too bad.

```
import {building} from "$app/environment";

...
if (building) return;
fetch(...);
```
