### ISSUE TITLE
`@playwright/test: ^1.28.1` causes infinite delay on `npm install` with a message like `idealTree buildDeps`

### ISSUE THREAD

**Issue by Bishwas-py** [sveltejs/kit#8659]
### Describe the bug

I created a sveltekit project, and while doing `npm i` the installation gets stuck infinitely. And whenever I removed `@playwright/test: ^1.28.1` from `package.json > devDependencies`, it works well. `^1.25.0` version of `@playwright/test` works pretty well, but I believe `^1.28.1` has some issues.

### Reproduction

# Create a SvelteKit project
```
npm create svelte@latest new_sveltekit_project
✔ Which Svelte app template? › Skeleton project
✔ Add type checking with TypeScript? › Yes, using TypeScript syntax
✔ Add ESLint for code linting? … No / Yes
✔ Add Prettier for code formatting? … No / Yes
✔ Add Playwright for browser testing? … No / Yes
✔ Add Vitest for unit testing? … No / Yes
```
# Install dependencies
```
npm install # this gets stuck 
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦  idealTree:testsvelte: sill idealTree buildDeps
```

### Logs

```Shell
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦  idealTree:testsvelte: sill idealTree buildDeps
```

### System Info

```Shell
System:
    OS: Linux 6.0 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
    Memory: 3.97 GB / 9.59 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.1.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.1.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.74
    Firefox: 108.0.1
```

### Severity

blocking all usage of SvelteKit

**Comment by gtm-nayan** [comment]
I doubt it's infinite, for 1.25, you might have the browser binaries cached already whereas for 1.28 they need to be downloaded along with the playwright package.

Anyway, I don't think there's anything we can do in create-svelte for it, if there's any issue it'd be in your package manager or playwright itself.
