### ISSUE TITLE
relative base paths

### ISSUE THREAD

**Issue by albertlast** [sveltejs/kit#8663]
### Describe the problem

I want to build a web app which got no backend interaction,
but after build to be able to drop on some random webspaces in random folder.

so the idea is to build a spa with relative base path base: './'

To build a spa i follow this: https://kit.svelte.dev/docs/adapter-static#spa-mode
to set the relative base i tryed first to go by the vite.config.ts and set there the base,
but i got the build log message that this get overwrited by svelte.config.js
so i try to set in paths the base to ./

but got an error message that the base had to start with / (which mean a relative root path is wanted).
```
Error: config.kit.paths.base option must either be the empty string or a root-relative path that starts but doesn't end with '/'. See https://kit.svelte.dev/docs/configuration#paths
```

but like i said i want to drop this spa on a random webspace in a random folder without rebuild.

app got init by "npm create svelte@latest <project_name>"

code: https://github.com/albertlast/GameLiveCounterSvelte

vite.config.ts:
```ts
import { sveltekit } from '@sveltejs/kit/vite'
import type { UserConfig } from 'vite'

const config: UserConfig = {
  plugins: [sveltekit()],
  test: {
    include: ['src/**/*.{test,spec}.{js,ts}']
  }
}

export default config
```

svelte.config.js
```js
import adapter from '@sveltejs/adapter-static';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://kit.svelte.dev/docs/integrations#preprocessors
	// for more information about preprocessors
	preprocess: vitePreprocess(),

	kit: {
		adapter: adapter({
		  fallback: 'index.html',
		}),
		prerender: { entries: [] },
		paths:{
			base:'/bekeon/glcs'
		}

	  }
};

export default config;
```

### Describe the proposed solution

allow the base path to start with . beside of /

### Alternatives considered

maybe with a pure svelte approache this issue didn't happen,
but the default package depence of "npm create svelte@latest <project_name>" is with svelte-kit so expecte this to work.

### Importance

nice to have

### Additional Information

https://0exclusive.de/bekeon/glcs generated svelte version
https://0exclusive.de/bekeon/glc/ vue version with relative path 
```
<link rel="modulepreload" href="/bekeon/glcs/_app/immutable/start-5b6cd4e0.js">
```
vs
```
<script type="module" crossorigin src="./assets/index-aeb7ae09.js"></script>
```

**Comment by mydracula** [comment]
I also want to know how to set baseUrl

**Comment by albertlast** [comment]
just use svelte without svelte kit
