### ISSUE TITLE
importing environment variables does not work with turborepo

### ISSUE THREAD

**Issue by isaacfink** [sveltejs/kit#8664]
### Describe the bug

I am importing environment variables with `$env/static/public` for a supabase client and in development (when loading variables from a `.env` file) it works perfectly but in production it fails, it actually fails the build

### Reproduction

create turborepo project from the sveltekit starter
add a `.env` file and import the variables to use in a `ts` file
build the project without a `.env` file with injecting environment variables, i am using vercel and injecting the variables through the dashboard

### System Info

```Shell
deploying on vercel
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
Can you elaborate on what this means exactly?

> create turborepo project from the sveltekit starter

If you have a repro you can share (a repo, not a description) it would help greatly.

**Comment by isaacfink** [comment]
@Rich-Harris it works now and I don't know why or why it didn't work until now, I went through multiple iterations and at one point the issue wad I was importing a variable in a utility package that didn't have the variables but on some iterations that was definitely not the issue, I am having a different issue now so I can't check if it works in that app but it works in another app at the moment, I will close this issue now and add a comment if I run into it again in the future
