### ISSUE TITLE
[feature request] Client Side Rendering Adapter (with filesystem routing)

### ISSUE THREAD

**Issue by showierdata9978** [sveltejs/kit#8672]
### Describe the problem

Im frustrated that Kit uses my CF Workers Quota, when I just want a Client Side Rendering, MultiPage Svelte App without client side routing with `{#if page=="somthing"} {/if}`

### Describe the proposed solution

generate multiple HTML files that can be served with somthing like python's http.server static file server. 

Without doing any SSR, or PreRendering. Just letting the client render it.

basicly just like if you rendered 2 normal  svelte apps, then served them staticly (with one in a subdir, for /subdir/ insted of *.html)

### Alternatives considered

Not using SvelteKit, or using all of my workers quota when my app goes fully public (i get more requests then the default quota)

### Importance

i cannot use SvelteKit without it

### Additional Information

repo: [link](https://github.com/meower-media-co/Meower-SvelteKit)

**Comment by showierdata9978** [comment]
Client side rendering; fp based routing

**Comment by dummdidumm** [comment]
What is "fp based routing"?

Is this "I want an SPA"? What except `export const ssr = false` (https://kit.svelte.dev/docs/page-options#ssr) do you need?

**Comment by showierdata9978** [comment]
Basically all I'm asking for is all client side rendered, but still with
multiple pages. (That does not use cf workers quota)

Iv tried pretender & adapter-static , but fails because I use LocalStorage
and other Client Side APIS that need to be done before onMount is called

**Comment by s3812497** [comment]
Highly recommend following the steps [in this page](https://kit.svelte.dev/docs/adapter-static#spa-mode) to achieve what you want (as per dummdidumm's suggestion).

You client-side APIs should have no issue with `export const ssr = false` in the root layout (`src/routes/+layout.js`).
If you're still experiencing issues, you could provide a copy of the logs / a detailed example of it.

**Comment by showierdata9978** [comment]
I'm going to defer this til I get home, and I had already set SSR to false
