### ISSUE TITLE
Custom Output Path for Static Adapter

### ISSUE THREAD

**Issue by jacoblukewood** [sveltejs/kit#868]
**Is your feature request related to a problem? Please describe.**
The *out* option for the static adapter does not work. It functions fine on the node adapter as [described in the docs](https://kit.svelte.dev/docs#adapters).

**Describe the solution you'd like**
To be able to set a custom output directory like you can with the node adapter.

**Describe alternatives you've considered**
Manually moving the files or creating a custom build script.

**How important is this feature to you?**
It would simplify my build process.

**Comment by ignatiusmb** [comment]
You should now be able to provide a custom output path for the adapter, see https://github.com/sveltejs/kit/tree/master/packages/adapter-static#usage and its options
