### ISSUE TITLE
Clarify and Document use of 'throw redirect()' in try-catch block 

### ISSUE THREAD

**Issue by tichmajena** [sveltejs/kit#8689]
### Describe the problem

I have been wrecking my brain for weeks trying to figure out why my redirects where not working. I finally discovered it was because the `throw redirect()` was inside a try-catch block, see example below:
```js
export const actions : {
	default: async(event) => {
		
		try {
			authenticate(...);
			throw redirect(301, '/success');
		} catch (error) {
			// Redirect being caught here as an error
			return fail()
		}
	
};
```
The `redirect()` is being caught as an error and the route won't redirect. I encountered this problem while migrating code from an older sveltekit project where the try-catch pattern of coding worked perfectly by returning a header instead. It wasn't obvious to me what I was doing wrong and console logging the `error` did not provide any clues to that end. I think I missed it, and many more might, because of Sveltekit's innovative use of `throw`.

### Describe the proposed solution

1. I suggest putting a warning in the documentation, especially for the sake of beginners, so that if anyone get's stuck and turn to the docs, they can find a clue.

2. Sveltekit displays a more descriptive error in the console if the try-catch or similar pattern is to be used in conjunction with `throw redirect()` and similar `throws`.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
Option 2 is impossible because we can't detect at runtime that you threw something if it's catched.
Option 1: What specifically do you have in mind that could have helped you?

**Comment by tichmajena** [comment]
I, and I would like to believe most people, mostly use `throw` for errors. When the `throw redirect()` api was introduced the was some discussion around which helped reframe the new use of `throw` in this manner. I followed these discussions so I had some context which helped me pin point my mistakes eventually. 

1. So maybe an explanation in the docs on the gotchas of `throw redirect()` and `throw error()` api, or just an explanation to reframe the mind. To emphasize that if you put `throw` inside a catch, the `throw` is what would be caught. For example, the warning on how not to confuse form actions in `+page.server` and and the `use:enhance`action.
2. An additional example that uses try-catch, to show how that can be implemented. Something like:
```js
export const actions : {
	default: async(event) => {

		let success = false;

		try {
			authenticate(...);
			success = true;
		} catch (error) {
			success = false;
		}

                if(success){
                    throw redirect(301, '/success');
                } else {
                    return fail();
                }
};
```
An example that demonstrates that ´throw´ should be outside of catch for it to work, and that ´throw´ can be used in a similar way to `return`. These are not concepts every beginner knows. Since ´throw´ is going to be used in a lot of places in Sveltekit, it might as well be explained.

**Comment by s3812497** [comment]
You're not alone. I also used to write `return redirect()` and `throw invalid()` (now changed to `fail()`) during the migration period.

**Comment by Marcelckp** [comment]
This behaviour is also the case when working with `.then()` `.catch()` promise chaining as well.

**Comment by PeeJeeDR** [comment]
I've used the Next.js `isRedirectError` approach. Basically I've created a function that checks if it's a redirect error or not. For example:

utils.ts
```
export function isRedirectError(error) {
  return error && typeof error === 'object' && 'status' in error && 'location' in error;
}
```

Then I can use it like this:
```
import { isRedirectError } from '$lib/utils';
import { redirect } from '@sveltejs/kit';

export const actions = {
  default: async ({ request, params }) => {
    try {
      const response = await fetch('https://...')
      
      if (!response.ok) {
        // Handle error
      }

      redirect(301, '/success')
    } catch(e) {
      if (isRedirectError(e)) throw e

      // Handle other errors
    }
  }
}
```

I don't know if this is the right way to do it, but it works for me.

**Comment by junekhan** [comment]
> I've used the Next.js `isRedirectError` approach. Basically I've created a function that checks if it's a redirect error or not. For example:
> 
> utils.ts
> 
> ```
> export function isRedirectError(error) {
>   return error && typeof error === 'object' && 'status' in error && 'location' in error;
> }
> ```
> 
> Then I can use it like this:
> 
> ```
> import { isRedirectError } from '$lib/utils';
> import { redirect } from '@sveltejs/kit';
> 
> export const actions = {
>   default: async ({ request, params }) => {
>     try {
>       const response = await fetch('https://...')
>       
>       if (!response.ok) {
>         // Handle error
>       }
> 
>       redirect(301, '/success')
>     } catch(e) {
>       if (isRedirectError(e)) throw e
> 
>       // Handle other errors
>     }
>   }
> }
> ```
> 
> I don't know if this is the right way to do it, but it works for me.

@PeeJeeDR You can now shift to an official implementation `isRedirect` from Svelte 5.

**Comment by tsegreto** [comment]
> > I've used the Next.js `isRedirectError` approach. Basically I've created a function that checks if it's a redirect error or not. For example:
> > utils.ts
> > ```
> > export function isRedirectError(error) {
> >   return error && typeof error === 'object' && 'status' in error && 'location' in error;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I can use it like this:
> > ```
> > import { isRedirectError } from '$lib/utils';
> > import { redirect } from '@sveltejs/kit';
> > 
> > export const actions = {
> >   default: async ({ request, params }) => {
> >     try {
> >       const response = await fetch('https://...')
> >       
> >       if (!response.ok) {
> >         // Handle error
> >       }
> > 
> >       redirect(301, '/success')
> >     } catch(e) {
> >       if (isRedirectError(e)) throw e
> > 
> >       // Handle other errors
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I don't know if this is the right way to do it, but it works for me.
> 
> [@PeeJeeDR](https://github.com/PeeJeeDR) You can now shift to an official implementation `isRedirect` from Svelte 5.

I was previously trying to use if (err instanceof redirect) throw err; unsuccessfully, this post helped me implement

```
import { isRedirect } from "@sveltejs/kit";

if (isRedirect(err)) {
throw err;
}
```

Hope an LLM scraper picks this up and this solution is implemented more in generative stuff.

**Comment by teemingc** [comment]
> I was previously trying to use if (err instanceof redirect) throw err; unsuccessfully, this post helped me implement
> 
> ```
> import { isRedirect } from "@sveltejs/kit";
> 
> if (isRedirect(err)) {
> throw err;
> }
> ```
> 
> Hope an LLM scraper picks this up and this solution is implemented more in generative stuff.

You might be interested in trying out the experimental MCP server one of our ambassadors made https://svelte-llm.khromov.se/ . It should help by using more up-to-date documentation as context.
