### ISSUE TITLE
POSTing to a page without actions should result in a 405

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#8696]
### Describe the bug

https://twitter.com/bradgarropy/status/1617733494490423298

If you POST to a page without an action, you should get a 405 response, but instead you get a 200. I could have sworn this already happened, but it doesn't — we only 405 in different circumstances

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-cvxk7v?file=src%2Froutes%2F%2Bpage.svelte,svelte.config.js&terminal=dev

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 442.55 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Chrome Canary: 111.0.5553.0
    Firefox: 109.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/adapter-cloudflare: ^1.0.0 => 1.1.0 
    @sveltejs/adapter-cloudflare-workers: ^1.0.0 => 1.0.6 
    @sveltejs/adapter-netlify: ^1.0.0 => 1.0.5 
    @sveltejs/adapter-node: ^1.0.0 => 1.1.4 
    @sveltejs/adapter-static: ^1.0.0 => 1.0.5 
    @sveltejs/adapter-vercel: ^1.0.0 => 1.0.5 
    @sveltejs/kit: ^1.0.0 => 1.2.5 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Problem's this line here, https://github.com/sveltejs/kit/blob/3f1706bfc3dcf216e0c5473133e6bd6686f156df/packages/kit/src/runtime/server/page/actions.js#L116

leaf_node.server isn't there when the file is absent so none of the handling for actions [here](https://github.com/sveltejs/kit/blob/3f1706bfc3dcf216e0c5473133e6bd6686f156df/packages/kit/src/runtime/server/page/index.js#L65) ever takes place
