### ISSUE TITLE
CHANGELOG.md in packages have no links to commits

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#870]
**Is your feature request related to a problem? Please describe.**
CHANGELOG.md in packages have no links to commits.

https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md

**Comment by benmccann** [comment]
I think we should change the format with https://github.com/atlassian/changesets/blob/main/docs/modifying-changelog-format.md

@pngwn might have more tips

**Comment by pngwn** [comment]
Yeah we can either use the GitHub changelog formatter that is provided or we can write a custom one.

@Conduitry has some reservations about the provided formatter so we may want to look into a custom one that meets our requirements.

**Comment by ignatiusmb** [comment]
Changes in CHANGELOG now links to its original PR, which aligns with how the core Svelte repository writes its changes
