### ISSUE TITLE
Calling `invalidate` on mount in a layout triggers an infinite reload loop on a 404 error

### ISSUE THREAD

**Issue by allezxandre** [sveltejs/kit#8701]
### Describe the bug

The `server_fallback` method from here:

https://github.com/sveltejs/kit/blob/74798e94ab16db33887a2229ae03f6ec419d40f3/packages/kit/src/runtime/client/client.js#L1122-L1134

appears to check if the page has `hydrated` to prevent infinite reloads when a 404 happens.

However, it seems if `invalidate` is called (for instance in a `+layout.svelte` component that is parent to the 404-d page), it is my understanding that `invalidate` waits for the page to `hydrate` prior to `server_fallback` being called, and so an infinite redirect loop appears.

### Reproduction

Here's a modified template:

[StackBlitz Reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-tae7et?file=src/routes/+layout.svelte)

The only change is in the root `+layout.svelte` where the following has been added:

```js
onMount(() => {
    void invalidate('placeholder:identifier')
})
```

Navigating to a non-existing route like `/invalid-link` (added to the `Header` navigation for convenience) will trigger an infinite loop of reloads.

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (8) arm64 unknown
    Memory: 931.27 MB / 6.77 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.1.4 => 1.1.4 
    @sveltejs/kit: ^1.2.6 => 1.2.6 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by allezxandre** [comment]
By the way, for anyone looking for a workaround, if you need to invalidate from a layout component, you can check that `$page.error` is `null` prior to calling `invalidate`:

```diff
+if (!$page.error)
    onMount(() => {
        void invalidate('placeholder:identifier')
    })
```

**Comment by dummdidumm** [comment]
I can see how that's happening, though I'm wondering why you eagerly `invalidate` inside `onMount` - what's your real world use case? I'm not sure how we can fix this without breaking other assumptions about code flows. For example, we could check if the page status is 404 and not reload in that case, but that would break if the page exists on the server (navigated to through the `handle` hook). For this case we somehow would need to know that
- this is an eager `invalidate`
- it's on a 404 page
- we already have been on this page before

**Comment by allezxandre** [comment]
Supabase ([documentation here](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#synchronizing-the-page-store)) uses it to store the Supabase session on a Cookie through the server

**Comment by Rich-Harris** [comment]
As a workaround, perhaps you could wrap the `invalidate` call in a `if ($page.status === 200)` block or similar?

**Comment by eltigerchino** [comment]
Closing this as it's not reproducible on the latest version of Kit
