### ISSUE TITLE
Integrating sqlite with sveltekit (adaptar_node())

### ISSUE THREAD

**Issue by anilbhattaraitoronto** [sveltejs/kit#872]
I am wondering if someone has figured out how to integrate sqlite database engine with sveltekit. I love svelte in the frontend and it looks like sveltekit is even better with its integration of front and backend, but I have been trying to incorporate sqlite with no success so far.

I will really appreciate if someone more knowledgeable than I could share some way out. 

Thank you very much

**Comment by Rich-Harris** [comment]
Please don't use the issue tracker to request support, that's not what it's for, as articulated quite clearly in the issue templates you decided to ignore: https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/questions-and-help.md

Doing stuff like this just creates extra noise that maintainers have to deal with and delays the point at which we can release a stable version.
