### ISSUE TITLE
Clicking hash link twice on Firefox breaks back navigation

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#8725]
### Describe the bug

This issue only occurs when using the desktop Firefox browser.

Clicking a hash link twice then navigating to a new page causes the browser back navigation to change the URL but no navigation occurs.

### Reproduction

https://stackblitz.com/edit/github-lxdc8e?file=src%2Froutes%2F%2Blayout.svelte

1. Preview the website in a desktop Firefox browser.
3. On the same page, click the "Go to footer" hash link twice.
4. Navigate to a different page.
5. Press the browser back button.
6. The browser does not navigate back but the URL changes.

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.76 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Chrome Canary: 111.0.5559.0
    Firefox: 109.0
    Firefox Developer Edition: 105.0
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/kit: ^1.0.0 => 1.2.8 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by danielimmke** [comment]
If no one is looking at this, I can take it.

**Comment by dummdidumm** [comment]
Sure, go ahead!

**Comment by s3812497** [comment]
One potential cause of this is that Firefox does not emit a popstate event on subsequent navigations to the same hash URL. However, Chrome and Safari will always emit the popstate event when.

**Comment by danielimmke** [comment]
Spent some time on this today, I was able to confirm what @s3812497 said. Firefox's popState event also doesn't include all of the same information as Chrome's.

I think it will be a matter of finding where in the routing code SvelteKit decides to "navigate" and changing the conditional logic to account for this. I can only work on this in small increments but have some additional time planned for it this coming week.

**Comment by danielimmke** [comment]
I'm sorry, I just don't have the bandwidth to look at this further right now. Hopefully the little bit I did helped.

**Comment by s3812497** [comment]
> I'm sorry, I just don't have the bandwidth to look at this further right now. Hopefully the little bit I did helped.

No worries! Thanks for the extra info that you've put out. I'll try and have a look at it again this weekend :)

**Comment by s3812497** [comment]
@Rich-Harris what would be the effect of removing the `if (event.state?.[INDEX_KEY])` check? https://github.com/sveltejs/kit/blob/526a2ed5676905807d83ace90d3853027f17f265/packages/kit/src/runtime/client/client.js#L1620-L1626
Currently, firefox always returns a `event.state: null` while on a hash link, clicking the same hash link, navigating somewhere else, then pressing back. Hence, this check causes navigation to break. I can't find where in the codebase we're populating the `event.state` with this `sveltekit:index` key.

**Comment by s3812497** [comment]
@Rich-Harris how are we populating `event.state` with the `sveltekit:index` key on any popstate event? Firefox is always returning `null` for it in this scenario, causing navigation to break.
https://github.com/sveltejs/kit/blob/526a2ed5676905807d83ace90d3853027f17f265/packages/kit/src/runtime/client/client.js#L1620-L1624

**Comment by trueadm** [comment]
So looking more into this, and it seems when you click a link with a hash, `hashchange` fires, where we do `replaceState`. However, in Firefox, clicking a link with the same hash will not trigger `hashchange` and instead will set `history.state` to `null`. Looking at how other routing solutions handle this is interesting – they don't seem to use `hashchange`, and instead always push on hash changes. We could do something similar here, or we could detect FF and force a state change.

**Comment by Rich-Harris** [comment]
Could we somehow detect that the `hashchange` is a direct result of the `replaceState` rather than UA sniffing?

> @Rich-Harris how are we populating `event.state` with the `sveltekit:index` key on any popstate event?

I'm not sure I understand? It's populated at the time of the `pushState` or `replaceState` that created the history entry we're popping to.

**Comment by trueadm** [comment]
> Could we somehow detect that the hashchange is a direct result of the replaceState rather than UA sniffing?

Not sure this would solve the issue. If you refresh a link with a hash and click the same link with the hash, you don't get a `hashchange` and you don't get a `popstate`. You only get the `click` handling logic. Maybe we can detect if history.state is `null` at this point? I'll do some more digging.

**Comment by s3812497** [comment]
> > @Rich-Harris how are we populating `event.state` with the `sveltekit:index` key on any popstate event?
> 
> 
> 
> I'm not sure I understand? It's populated at the time of the `pushState` or `replaceState` that created the history entry we're popping to.

Sorry about that, I misunderstood how the API worked. Dominik is right about Firefox setting it to null. Truly strange behaviour
