### ISSUE TITLE
v1.3.1 brakes cloudflare 404 page

### ISSUE THREAD

**Issue by korywka** [sveltejs/kit#8750]
### Describe the bug

After upgrade from `1.3.0` to `1.3.1`, instead of 404 error code, 500 is fired.

### Reproduction

<img width="1728" alt="Screenshot 2023-01-27 at 13 35 17" src="https://user-images.githubusercontent.com/988471/215088902-5613edcb-5115-4103-9112-b4b07e2c14ff.png">

This error is fired from JS redirect. After page refresh it becomes 404 correctly.

https://94499105.binaries-web.pages.dev/bin/aaaaa - direct is `404`, but from search form is `500`.

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 61.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: 1.0.2 => 1.0.2 
    @sveltejs/kit: 1.3.0 => 1.3.0 
    svelte: 3.55.1 => 3.55.1 
    vite: 4.0.4 => 4.0.4
```

### Severity

blocking an upgrade

**Comment by korywka** [comment]
Thank you 🤝

**Comment by dummdidumm** [comment]
Thank you @s3812497 for investigating (and your general activity in general the last days/weeks, really appreciated!) - does this mean we can close this in favor of #8751?

**Comment by s3812497** [comment]
> Thank you @s3812497 for investigating (and your general activity in general the last days/weeks, really appreciated!)

Thank you to you and the svelte team for all your hard work :)
SvelteKit has helped me get through many of my university assignments.
