### ISSUE TITLE
I need to change the `build` dir name

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#876]
**Is your feature request related to a problem? Please describe.**
I need to change the `build` dir name.

**Describe the solution you'd like**
I wanna find how in docs page. I cannot now.

**Comment by benmccann** [comment]
Is this for a specific adapter? What's the motivation?

**Comment by frederikhors** [comment]
Adapter static, for now.

The motivation: to maintain compliance with other projects in the same team.

**Comment by babichjacob** [comment]
Closing as duplicate of #868. Follow that issue for updates.
