### ISSUE TITLE
[vite-plugin-sveltekit-compile] Cannot read properties of undefined (reading 'has_server_load')

### ISSUE THREAD

**Issue by Chaddeus** [sveltejs/kit#8763]
### Describe the bug

Prior to SvelteKit 1.3.1 my code would build fine.  With no other code changes in my project, after updating to SvelteKit 1.3.1 (and subsequently 1.3.2), my project will no longer build and the error doesn't point to anything in my code to resolve.

The app runs fine in development mode (npm run dev). 

```
[vite-plugin-sveltekit-compile] Cannot read properties of undefined (reading 'has_server_load')
error during build:
TypeError: Cannot read properties of undefined (reading 'has_server_load')
    at file:///***/node_modules/@sveltejs/kit/src/core/sync/write_client_manifest.js:67:43
```

More of the error log in the Logs section of this report. The reason I kept this part here is because if I click the write_client_manifest.js file I see this code:

```
let leaf_has_server_load = false;
if (route.leaf) {
	if (metadata) {
		const i = /** @type {number} */ (indices.get(route.leaf));
		leaf_has_server_load = metadata[i].has_server_load;
	} else if (route.leaf.server) {
		leaf_has_server_load = true;
	}
}
```

`leaf_has_server_load = metadata[i].has_server_load;` is where the error is triggered from. If I change it to `leaf_has_server_load = metadata[i]?.has_server_load;` then my code will build.

But I'm worried this might cause issues somehow in my app that I'm unaware of.

In case it is related to the tsconfig changes in the latest updates, here's my tsconfig:

```
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": false
	},
}
```

### Reproduction

Not sure how to reproduce this as the error isn't clear on what the issue is in my code.

### Logs

```Shell
[vite-plugin-sveltekit-compile] Cannot read properties of undefined (reading 'has_server_load')
error during build:
TypeError: Cannot read properties of undefined (reading 'has_server_load')
    at file:///***/node_modules/@sveltejs/kit/src/core/sync/write_client_manifest.js:67:43
    at Array.map (<anonymous>)
    at write_client_manifest (file:///***/node_modules/@sveltejs/kit/src/core/sync/write_client_manifest.js:55:5)
    at Object.handler (file:///***/node_modules/@sveltejs/kit/src/exports/vite/index.js:607:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginDriver.hookParallel (file:///***/node_modules/rollup/dist/es/shared/rollup.js:23688:17)
    at async file:///***/node_modules/rollup/dist/es/shared/rollup.js:25032:13
    at async catchUnfinishedHookActions (file:///***/node_modules/rollup/dist/es/shared/rollup.js:24128:20)
    at async doBuild (file:///***/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44518:22)
    at async build (file:///***/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:44347:16)
```
```


### System Info

```Shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 15.15 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /opt/homebrew/bin/node
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 109.0.5414.119
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91 
    @sveltejs/adapter-static: ^1.0.5 => 1.0.5 
    @sveltejs/kit: ^1.3.2 => 1.3.2 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

blocking an upgrade

### Additional Information

I searched for this error prior to reporting it. Some had said to check all imports. I did this in case I had missed something. But all my imports are fine.

**Comment by Chaddeus** [comment]
Also, to add -- I use adapter static and have no load functions (my app uses Firebase), configured like so:

```
kit: {
	adapter: adapter({
		pages: 'build',
		assets: 'build',
		fallback: 'app.html',
		precompress: true
	})
}
```

**Comment by Rich-Harris** [comment]
> Not sure how to reproduce this as the error isn't clear on what the issue is in my code

In this situation, use the divide and conquer strategy - progressively delete chunks of code and remove dependencies until the only thing that remains is the source of the bug. You'll often get a good idea of what's causing the bug as a result of this process.

Unfortunately there's not much we can do to investigate without a repro

**Comment by ryanylee** [comment]
Running into similar issue

**Comment by ryanylee** [comment]
Appears to happen when building and there's a folder with only a`+layout.svelte` file and no `+page.svelte` or inner routes. 

src
|_routes
   |_example
      |_+layout.svelte
      
and running `npm run build`
