### ISSUE TITLE
Change the default favicon so that it's easily distinguishable from kit.svelte.dev/docs

### ISSUE THREAD

**Issue by mcrascal** [sveltejs/kit#878]
When you have many tabs open you can't tell which tabs contain the docs and which tabs contain your project. 

It might be a good idea to change the colour of the favicon that's included with the starter project. 

This is not important. 

Thank you all for your hard work!

**Comment by dciug** [comment]
I agree. It's a small detail but it does have a nice impact on the development experience. Here's an example https://twitter.com/chriscoyier/status/1239906515219173376
Taken from here: https://css-tricks.com/different-favicon-for-development/

**Comment by dciug** [comment]
How about these colors, good enough? Blue for "development" seems to be quite common.

![svelte_favicon](https://user-images.githubusercontent.com/6199480/113572619-41fb2f80-9621-11eb-8297-34c29e521241.png)

**Comment by joe-azps** [comment]
Don't think it's necessary. The tab clearly states "Docs" in the title but besides that, if it is a development project, wouldn't we be updating the favicon with the project icon?

**Comment by dciug** [comment]
> Don't think it's necessary. The tab clearly states "Docs" in the title but besides that, if it is a development project, wouldn't we be updating the favicon with the project icon?

This is quite tricky. 
1. It depends on the way your browser handles tabs. Firefox shrinks tab dimensions, and if you're one of those people with 50+ tabs, the tab text is useless. 
2. Icon + color is a much stronger signifier, the human eye is much more susceptible to that. No thought required. The book "Don't make me think" is a good read about this.
3. Even when it comes to startups, the project logo may be created a few months into the project.

**Comment by joe-azps** [comment]
> This is quite tricky.
> 
> 1. It depends on the way your browser handles tabs. Firefox shrinks tab dimensions, and if you're one of those people with 50+ tabs, the tab text is useless.
> 2. Icon + color is a much stronger signifier, the human eye is much more susceptible to that. No thought required. The book "Don't make me think" is a good read about this.
> 3. Even when it comes to startups, the project logo may be created a few months into the project.

I see where you are coming from but here is how my mind interprets your points.

1. Two specific cases of Firefox and "one of those people" seem like an edge case and shouldn't apply for all.
2. Is it an icon color, or the logo color of Svelte, doesn't seem like changing the logo color applies when that orange is the brand.
3. Startup or not, it takes a few minutes to change your favicon, if the project logo isn't ready yet then put a placeholder in there. Once again changing the Svelte branding color doesn't see like the right path.

I think we both bring great points to the discussion, let's see what other input we get from the community.

**Comment by dciug** [comment]
A middle ground solution could be to allow us to config svelte favicons for 'dev' and 'production' builds. Maybe have a default 'dev' and 'orange' Svelte favicon.

**Comment by dummdidumm** [comment]
That would only complicate things for no real benefit. Either you change the favicon or you don't, and if you do you expect it to change for both environments

**Comment by benmccann** [comment]
You should update the favicon for your own project and not use Svelte's
