### ISSUE TITLE
Lazy loading data

### ISSUE THREAD

**Issue by dreitzner** [sveltejs/kit#8785]
### Describe the problem

One of SvelteKits core concepts is how we load data.
Using a `load` function and expecting `data` to have the data available in rendering is an established pattern.
```html
<!-- +page.svelte -->
<script>
  /** @type {import('./$types').PageData} */
  export let data;
</script>
```
```js
<!-- +page.server.js -->
/** @type {import('./$types').PageServerLoad} */
export async function load({ params }) {
  return {
    params
  };
}
```

If I need some data on the page, but I don't need it immediately, it would be nice to follow a similar pattern for loading that data, but lazily.

### Describe the proposed solution

From a technical side I would be aware of two possibilities:

1. Giving the option for flushing (chunked response)
```html
<!-- +page.svelte -->
<script>
  /** @type {import('./$types').PageData} */
  export let data;
  /** @type {import('./$types').LazyPageData} */
  export let lazy_data;
</script>
  <p>Hello {data.name}</p>
  {#if $lazy_data}
    <p>Your rank: {$lazy_data.rank}</p>
  {/if}
```
```js
<!-- +page.server.js -->
/** @type {import('./$types').PageServerLoad} */
export async function load({ flush }) {
  // some basic data get's loaded
  flush({
    name: 'me',
  })
  // some DB lookup that takes some time, but is not needed immediately
  const rank = await db.get('rank', userId);
  return {
    rank
  };
}
```
This would give a lot of control and could even make multiple flushes/stages of injecting data possible.
A problem to solve here would be how to handle multiple load functions spread through multiple layouts.
The easiest approach might be to have flush phases and if non is implemented, it will be available in `data`.
I kinda like the idea of having the ability for different load phases, but possible drawbacks of this approach might be:
1. loaded data might be in `data` or `lazy_data` depending on the context
2. that much flexibility might be hard to reason about while debugging
3. adding a flush will change where your `data` will end up

Flushing HTML early might be worth considering to speed up page performance even more, even if it will not be used for this feature.

2. Auto injecting lazy data after page is rendered
```html
<!-- +page.svelte -->
<script>
  /** @type {import('./$types').LazyPageData} */
  export let lazy_data;
</script>

{#if $lazy_data}
  <p>Hello {$lazy_data.name}</p>
{/if}
```
```js
<!-- +page.server.js -->
/** @type {import('./$types').LazyPageServerLoad} */
export async function lazy_load({ params }) {
  return {
    name: 'me'
  };
}
```

This approach is a lot more straight forward.
The separation of lazy and non lazy data is much clearer.
I would put the lazy response maybe in a store to make reactivity easier, but it might also work without it.

### Alternatives considered

Just keep as is and load data in `onMount` though server endpoint.

### Importance

nice to have

**Comment by xypine** [comment]
Isn't this basically the same root problem as in #7213?

**Comment by dreitzner** [comment]
👍 
I didn't find that issue with the keywords I was searching for.....
