### ISSUE TITLE
Svelte lib folder isn't output on build (with Vite)

### ISSUE THREAD

**Issue by KinyaDev** [sveltejs/kit#8791]
### Describe the bug

The Svelte lib folder isn't outputed on build (with Vite).
In fact, all my assets in that folder are output directly in the assets folder (output/client/_app/immutable/assets)
So the images can't be get when I need them.

### Reproduction

Get all my files in $lib folder with this function:
```
export const get = async () => {
		const allimgsf = import.meta.glob('$lib/*.png');
		const iterableImages = Object.entries(allimgsf);

		const allimgs = await Promise.all(
			iterableImages.map(async ([path, resolver]) => {
				// @ts-ignore
				const imgPath = path.slice(1, -3);

				return {
					path: imgPath,
					name: imgPath.split('/').reverse()[0]
				};
			})
		);

		return allimgs;
	};
```
Show all the images in a component:
```
{#await get() then get}
		{#each Object.values(get) as f}
			<div class="art">
				<img src={f.path + 'png'} alt={f.name} />
				<p>{f.name}</p>
			</div>
		{/each}
	{/await}
```
Then build the app.

### Logs

```Shell
Error: Not found: /src/lib/LN-Stat-Interface.png
    at resolve (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2509:18)
    at resolve (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2376:34)
    at Object.#options.hooks.handle (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2553:59)
    at respond (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2374:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /src/lib/Silika%20Demon%20Charadesign.png
    at resolve (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2509:18)
    at resolve (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2376:34)
    at Object.#options.hooks.handle (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2553:59)
    at respond (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2374:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Not found: /src/lib/Which%20kind%20of%20thing%20are%20kinya%20projects.png
    at resolve (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2376:34)
    at Object.#options.hooks.handle (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2553:59)
    at respond (file:///C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit/output/server/index.js:2374:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz
    Memory: 2.96 GB / 7.88 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE     
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.70)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2
    @sveltejs/kit: ^1.0.0 => 1.3.2
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking an upgrade

### Clonable Repo 
https://github.com/KinyaDev/kinyapp

### StackBlitz Project
https://stackblitz.com/github/KinyaDev/kinyapp

**Comment by Conduitry** [comment]
Please provide a compete but minimal reproduction as a clonable repo or StackBlitz project.

**Comment by KinyaDev** [comment]
Here is the StackBlitz Project

**Comment by s3812497** [comment]
I think you mean to place your images in `/static` instead of `/src/lib`.

Any assets included in `/static` will be copied to the root `/` of your build folder.

So, if you wanted to read and return a filepath from `/static/images/example.jpg`, ensure that your endpoint returns the path `/images/example.jpg`.

**Comment by KinyaDev** [comment]
No because I have a problem with that. When I use import.meta.glob, it reads the files in my src folder, and then when I go to my website it tries to read in the static files SO... I don't want to have two images folder that are the same in src and static.

**Comment by KinyaDev** [comment]
If I don't put my images in the `src/` folder, it will return nothing and it will not load my images in the `static/` folder.
So I use $lib folder, but I have another error...

**Comment by KinyaDev** [comment]
![image](https://user-images.githubusercontent.com/114854571/215737220-dd44dbc3-1a24-4d9c-98a8-f950368537bd.png)
I changed to `const allimgsf = import.meta.glob('../../static/images/*.png');` If you want to see what was my previous error.
```
files in the public directory are served at the root path.
Instead of /static/images/LN-Stat-Interface.png, use /images/LN-Stat-Interface.png.
Error: Not found: /static/images/LN-Stat-Interface.png
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:395:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:236:5)
    at Object.#options.hooks.handle (/@fs/C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:233:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
files in the public directory are served at the root path.
Instead of /static/images/Which kind of thing are kinya projects.png, use /images/Which kind of thing are kinya projects.png.
Error: Not found: /static/images/Which%20kind%20of%20thing%20are%20kinya%20projects.png
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:395:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:236:5)
    at Object.#options.hooks.handle (/@fs/C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:233:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
files in the public directory are served at the root path.
Instead of /static/images/Silika Demon Charadesign.png, use /images/Silika Demon Charadesign.png.
Error: Not found: /static/images/Silika%20Demon%20Charadesign.png
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:395:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:236:5)
    at Object.#options.hooks.handle (/@fs/C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:233:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
The request url "C:\Users\kinya\OneDrive\Documents\kinya-website-svelte\static\images\LN-Stat-Interface.png" is outside of Vite serving allow list.

- C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/src/lib
- C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/src/routes
- C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/.svelte-kit
- C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/src
- C:/Users/kinya/OneDrive/Documents/kinya-website-svelte/node_modules

Refer to docs https://vitejs.dev/config/server-options.html#server-fs-allow for configurations and more details.

The request url "C:\Users\kinya\OneDrive\Documents\kinya-website-svelte\static\images\Which kind of thing are kinya projects.png" is outside of Vite serving allow list.
The request url "C:\Users\kinya\OneDrive\Documents\kinya-website-svelte\static\images\Silika Demon Charadesign.png" is outside of Vite serving allow list.

```

Sorry it tells me that, but If I change `/static/images/image.png` to `/images/image.png` : Vite will load no images in that folder.

**Comment by KinyaDev** [comment]
It is really strange because `http://127.0.0.1:5174/images/LN-Stat-Interface.png` works.

**Comment by KinyaDev** [comment]
I will make another repo to illustrate clearly the problem.

**Comment by KinyaDev** [comment]
I fixed it by adding a `.slice(7)` to the string that is the path returned to be used on the component.

**Comment by Rich-Harris** [comment]
Your repro appears to be private:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/1162160/215889688-937572d1-28a7-426d-be31-3af7b7b664fa.png">

`import.meta.glob` is designed to be used with source code, not static assets. You really should be putting the images inside `src/lib` if you want to use them like this.

**Comment by s3812497** [comment]
> `import.meta.glob` is designed to be used with source code, not static assets. You really should be putting the images inside `src/lib` if you want to use them like this.

Rich is right. I had a closer look at Vite's `import.meta.glob` and you'll have to call the "resolver" (the import(...) method for each module) to get the public URL in the final build.

A solution for you would look like this.
```svelte
<script>
  export const get = async () => {
    const allimgsf = import.meta.glob("$lib/images/*.png");
    const iterableImages = Object.entries(allimgsf);

    const allimgs = await Promise.all(
      iterableImages.map(async ([path, resolver]) => {
        // gets the resolved asset path
        const imgPath = /** @type {{default: string;}} */ (
          await resolver()
        ).default.slice(0, -4);

        return {
          path: imgPath,
          name: imgPath.split("/").at(-1),
        };
      })
    );

    return allimgs;
  };
</script>

{#await get() then get}
  {#each Object.values(get) as f}
    <div class="art">
      <img src="{f.path + '.png'}" alt="{f.name}" />
      <p>{f.name}</p>
    </div>
  {/each}
{/await}
```

**Comment by KinyaDev** [comment]
https://github.com/KinyaDev/kinya

Le mar. 31 janv. 2023 à 22:41, Rich Harris ***@***.***> a
écrit :

**Comment by KinyaDev** [comment]
Thanks!

**Comment by KinyaDev** [comment]
> > `import.meta.glob` is designed to be used with source code, not static assets. You really should be putting the images inside `src/lib` if you want to use them like this.
> 
> Rich is right. I had a closer look at Vite's `import.meta.glob` and you'll have to call the "resolver" (the import(...) method for each module) to get the public URL in the final build.
> 
> As a result, the URL would be:
> 
> * dev `http://127.0.0.1:5173/src/lib/images/svelte-welcome.png`
> * after build `http://127.0.0.1:4173/_app/immutable/assets/svelte-welcome-6c300099.png`
> 
> A solution for you could look like this.
> 
> ```svelte
> <script>
>   export const get = async () => {
>     const allimgsf = import.meta.glob("$lib/images/*.png");
>     const iterableImages = Object.entries(allimgsf);
> 
>     const allimgs = await Promise.all(
>       iterableImages.map(async ([path, resolver]) => {
>         // gets the resolved asset path
>         const imgPath = /** @type {{default: string;}} */ (
>           await resolver()
>         ).default.slice(0, -4);
> 
>         return {
>           path: imgPath,
>           name: imgPath.split("/").at(-1),
>         };
>       })
>     );
> 
>     return allimgs;
>   };
> </script>
> 
> {#await get() then get}
>   {#each Object.values(get) as f}
>     <div class="art">
>       <img src="{f.path + '.png'}" alt="{f.name}" />
>       <p>{f.name}</p>
>     </div>
>   {/each}
> {/await}
> ```

Thanks, I'll try it.

**Comment by KinyaDev** [comment]
![image](https://user-images.githubusercontent.com/114854571/216003238-0a3856b7-b631-4a7d-8c88-54343f7101dc.png)

It shows the images strangely.

> > `import.meta.glob` is designed to be used with source code, not static assets. You really should be putting the images inside `src/lib` if you want to use them like this.
> 
> Rich is right. I had a closer look at Vite's `import.meta.glob` and you'll have to call the "resolver" (the import(...) method for each module) to get the public URL in the final build.
> 
> As a result, the URL would be:
> 
> * dev `http://127.0.0.1:5173/src/lib/images/svelte-welcome.png`
> * after build `http://127.0.0.1:4173/_app/immutable/assets/svelte-welcome-6c300099.png`
> 
> A solution for you could look like this.
> 
> ```svelte
> <script>
>   export const get = async () => {
>     const allimgsf = import.meta.glob("$lib/images/*.png");
>     const iterableImages = Object.entries(allimgsf);
> 
>     const allimgs = await Promise.all(
>       iterableImages.map(async ([path, resolver]) => {
>         // gets the resolved asset path
>         const imgPath = /** @type {{default: string;}} */ (
>           await resolver()
>         ).default.slice(0, -4);
> 
>         return {
>           path: imgPath,
>           name: imgPath.split("/").at(-1),
>         };
>       })
>     );
> 
>     return allimgs;
>   };
> </script>
> 
> {#await get() then get}
>   {#each Object.values(get) as f}
>     <div class="art">
>       <img src="{f.path + '.png'}" alt="{f.name}" />
>       <p>{f.name}</p>
>     </div>
>   {/each}
> {/await}
> ```

**Comment by KinyaDev** [comment]
`return {
path: imgPath,
name: decodeURI(imgPath.split('/').at(-1)).split('-')[0]
}`

I changed a bit the code and it works now.

**Comment by KinyaDev** [comment]
I published my website on Vercel and it works perfectly, thanks !

> > `import.meta.glob` is designed to be used with source code, not static assets. You really should be putting the images inside `src/lib` if you want to use them like this.
> 
> Rich is right. I had a closer look at Vite's `import.meta.glob` and you'll have to call the "resolver" (the import(...) method for each module) to get the public URL in the final build.
> 
> As a result, the URL would be:
> 
> * dev `http://127.0.0.1:5173/src/lib/images/svelte-welcome.png`
> * after build `http://127.0.0.1:4173/_app/immutable/assets/svelte-welcome-6c300099.png`
> 
> A solution for you could look like this.
> 
> ```svelte
> <script>
>   export const get = async () => {
>     const allimgsf = import.meta.glob("$lib/images/*.png");
>     const iterableImages = Object.entries(allimgsf);
> 
>     const allimgs = await Promise.all(
>       iterableImages.map(async ([path, resolver]) => {
>         // gets the resolved asset path
>         const imgPath = /** @type {{default: string;}} */ (
>           await resolver()
>         ).default.slice(0, -4);
> 
>         return {
>           path: imgPath,
>           name: imgPath.split("/").at(-1),
>         };
>       })
>     );
> 
>     return allimgs;
>   };
> </script>
> 
> {#await get() then get}
>   {#each Object.values(get) as f}
>     <div class="art">
>       <img src="{f.path + '.png'}" alt="{f.name}" />
>       <p>{f.name}</p>
>     </div>
>   {/each}
> {/await}
> ```
