### ISSUE TITLE
v1.3.5 broke the URL hash handling

### ISSUE THREAD

**Issue by heikkilamarko** [sveltejs/kit#8804]
### Describe the bug

I updated from SvelteKit v1.3.4 to v1.3.5 and started to get the following error:

<img width="1608" alt="Screenshot 2023-01-31 at 9 09 34" src="https://user-images.githubusercontent.com/3757314/215691220-031c54c2-8aa7-48c8-a69e-36e2635c77a5.png">

My auth provider (Keycloak) redirects back to my app after login with a URL hash. It seems that the following change in #8767 broke the hash handling:

<img width="1615" alt="Screenshot 2023-01-31 at 8 37 56" src="https://user-images.githubusercontent.com/3757314/215691668-52d23320-42f0-4233-b87c-3d735a4b71d5.png">

### Reproduction

See the bug description.

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 394.70 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.3
```

### Severity

blocking an upgrade

**Comment by msonnberger** [comment]
oops, that was me. apparently there is a difference between DOM IDs and CSS selectors. Should be fixed with #8806 (which uses `document.getElementById` again)
