### ISSUE TITLE
adapter-vercel - external option does not work 

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#8814]
### Describe the bug

The `external` option of the vercel adapter does not appear to work, and exclude modules from the final build.

### Reproduction

This is my config 

```js
import adapter from "@sveltejs/adapter-vercel";
import preprocess from "svelte-preprocess";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  // Consult https://github.com/sveltejs/svelte-preprocess for more information about preprocessors
  preprocess: preprocess(),

  kit: {
    adapter: adapter({
      external: ["@aws-sdk/client-lambda"]
    }),
    alias: {
      $styles: "src/styles",
      $lib: "src/lib",
      $data: "src/data",
      $lambda: "src/lambda"
    }
  }
};

export default config;
```

The deployed website does still function, including the parts that directly depend on `@aws-sdk/client-lambda` existing, and functioning.

This should fail with that library being excluded / made external. 

I'd love to provide a real repro, but to my knowledge there is literally no way to do a final, real lambda build, and produce the actual code that gets uploaded to aws. My understanding is that this process happens only on Vercel's servers :( 

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.46 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 9.3.0 - ~/Documents/git/booklist/svelte-kit/node_modules/.bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.2 => 1.0.2 
    @sveltejs/adapter-vercel: ^1.0.6 => 1.0.6 
    @sveltejs/kit: ^1.3.3 => 1.3.3 
    svelte: ^3.55.0 => 3.55.1 
    vite: ^4.0.3 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
`external` is specific to edge functions (and ideally wouldn't exist, because it's nonsensical — see https://github.com/sveltejs/kit/pull/8759). If your project has dependencies, those dependencies will be included in your lambda.

**Comment by arackaf** [comment]
@Rich-Harris it's not nonsensical for one very real use case: aws lambda has the `aws-sdk` package already available, built in. So typically (unless you need a super specific version) you'd mark that package as external, so whatever bundling tool your using doesn't ship that huge glob over the wire. 

I'm not sure if Vercel already has special handling around this.

**Comment by arackaf** [comment]
(but that's obv beyond the scope of this issue - sorry about that)

**Comment by Rich-Harris** [comment]
No idea if there's any special handling — to be honest I'd expect it to be on AWS's side, if so. Seems like an interesting design choice either way. You could always try hacking around in `.vercel/output/functions` to remove any `node_modules/@aws-sdk/client-lambda` directories and see if things still work (and if it has any impact on lambda size)

**Comment by arackaf** [comment]
@Rich-Harris aws already ships aws-sdk to lambda already - it's up to users whether they also want to bundle in a specific version, or just use what's there.

Hooking into a post-build even an manually mucking with the server output is an interesting idea - thanks for that!
