### ISSUE TITLE
Getting errors for endpoint that doesn't exist

### ISSUE THREAD

**Issue by faulander** [sveltejs/kit#8828]
### Describe the bug

i **had** a endpoint in /api/dc but renamed it to /api/dw. I changed all the references to /api/dc to /api/dw. The code works as it should. But every 5 minutes or so i get this error in the console:
```
Error: Not found: /api/dc
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:395:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:236:5)
    at Object.#options.hooks.handle (/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:233:40)
```
Sometimes just once, sometimes 5-6 times:
![image](https://user-images.githubusercontent.com/38588197/216018243-01767a96-063d-420a-bb64-aecbb3dc8ee1.png)

In Visual Studio i checked if there are any occurences of /api/dc, there aren't any. I deleted .sveltekit directory, updated sveltekit and reinstalled sveltekit completely. I restarted dev-server several times and also Visual Studio.

Somehow there must be some cache but i cannot find.

### Reproduction

i cannot reproduce this behaviour, i only have it in one project. but it might occur every time you rename a directory (endpoint)

### Logs

```Shell
see above
```

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 AMD EPYC 7282 16-Core Processor
    Memory: 4.15 GB / 7.74 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91 
    @sveltejs/adapter-node: ^1.0.0-next.88 => 1.1.4 
    @sveltejs/kit: ^1.0.0 => 1.3.6 
    svelte: ^3.50.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information
Additionally i get log outpout from serverside (in visual studio console) where i am sure that i don't have any console.log statements. i check 2, 3, 5 times and also searched for **ALL** console.logs in the whole project (including packages) but there was none. this is happening only on one route.
Is there a possibility to log where the output is coming from or is there a command to tell vite to re-compile when running dev-server?

**Comment by Conduitry** [comment]
There's nothing we can possibly do about this without some sort of reproduction. My initial guesses are that you have a copy of the application running that you don't know about and/or you have an instance in a browser somewhere still making requests to the old URL.

**Comment by faulander** [comment]
> There's nothing we can possibly do about this without some sort of reproduction. My initial guesses are that you have a copy of the application running that you don't know about and/or you have an instance in a browser somewhere still making requests to the old URL.

I am Head of Support in a IT-Company, so i am well aware of how important it is, to have a reproduceable example, but i cannot reproduce it, no matter what i do. It happens JUST in that Project. What i did:

* npm run dev --force
* deleted .sveltekit
* reinstalled sveltekit
* closed all browsers but one with an incognito window
* deployed me RC to the productive system so they are the same codebase
* restarted Windows, Server, Visual Studio Code.

I don't know what to do or where to look, thats why i asked if someone knows where i could continue investigation. I don't need a fix served on a silver platter, an idea would suffice.

**Comment by dummdidumm** [comment]
Did you wipe out your `node_modules` folder and reinstall dependencies? Maybe there's some wrong cache inside the `node_modules/.vite` folder

**Comment by faulander** [comment]
thanks for the suggestion, but it might be that someone else in the company has an old version still open forever. In the evening, when i am the only one in the office, the error doesn't occur.

So my question now is: Can i programmatically hard refresh the page  - say once every 24hr? I don't want to send out an email to 20 members of the team and putting up load on the it team because the users do not know how to refresh a page ;)

**Comment by Rich-Harris** [comment]
Could you recreate `/api/dc/+server.js` and redirect it to a page that said 'whoever sees this, please close your browser'?

**Comment by faulander** [comment]
What a great pragmatic idea, thanks alot @Rich-Harris !

**Comment by Rich-Harris** [comment]
I'll be optimistic and assume that worked, and close this as I don't think there's any action we can take on the SvelteKit side
