### ISSUE TITLE
Support for non-ESM npm package?

### ISSUE THREAD

**Issue by accron-1** [sveltejs/kit#883]
I'm want to use the NPM package [tingodb](https://www.npmjs.com/package/tingodb), but I get the following error when I start the app:
```
10:46:45 PM [vite] new dependencies found: tingodb, updating...
 > node_modules/tingodb/lib/main.js:6:75: error: Could not resolve "mongodb" (mark it as external to exclude it from the bundle)
    6 │ ...("bson").ObjectID || require("mongodb").ObjectID) : require("./Obj...
      ╵                                 ~~~~~~~~~

 > node_modules/tingodb/lib/tcoll.js:1160:4: error: With statements cannot be used with the "esm" output format due to strict mode
    1160 │         with (value.scope) {
         ╵         ~~~~
```

I've asked for advice on Discord but didn't get any solution unfortunately.

What's the correct way of including a package like `tingodb` in svelte-kit?

**Comment by secondary-school55** [comment]
@accron-1 
I have same problems too. 
Only solution i see, moving that package to esm. If you do not want to wait, fork it and modify.

Evan You said - one of main purpose Vitejs - moving web ecosystem to ESM modules.

**Comment by accron-1** [comment]
If you look in npm you'll see that the last update to the package was 3 years ago, so an update is likely not going to happen :)

Exactly what does it mean to move to ESM modules? Are there any tutorials that show a simple example?

**Comment by GrygrFlzr** [comment]
The bigger problem here is that the `with (value.scope)` is not valid ES5 strict mode syntax. ES6 implies strict mode, and ESM implies ES6+. It may be easier to find an alternative in-memory NoSQL database rather than trying to port this one?

**Comment by Conduitry** [comment]
Due to the `with`, the answer is pretty much that you can't. There are other issues about improving support for other packages, but there's not much you can do if it uses non strict mode features.

Also, please don't open issues for support requests. We appreciate that you did first ask on Discord, but not getting an answer there does not mean you should escalate here.

**Comment by accron-1** [comment]
It's not an escalation.

With no helpful replies on Discord, it's hard to know if it is a limitation in svelte-kit, or an issue with the npm package itself.
As @secondary-school55 stated above, I'm not the only one with this kind of issue, and it's unlikely we're the only ones; as such, it's worthwhile highlighting here what the official stand is in these case, and possible workarounds (if any).
