### ISSUE TITLE
(docs) toggle between js and ts is jarring

### ISSUE THREAD

**Issue by sacrosanctic** [sveltejs/kit#8845]
### Describe the problem

An extra line gets added in code snippets when toggling from JS to TS. I find it a little hard at a glance to see the difference.

js
```js
/** @type {import('./$types').PageLoad} */
export function load() {
  return {
    a: Promise.resolve('a'),
    b: Promise.resolve('b'),
    c: {
      value: Promise.resolve('c')
    }
  };
}
```

ts
```ts
import type { PageLoad } from './$types';
 // <===== extra line is here
export const load = (() => {
  return {
    a: Promise.resolve('a'),
    b: Promise.resolve('b'),
    c: {
      value: Promise.resolve('c')
    }
  };
}) satisfies PageLoad;
```

### Describe the proposed solution

Add the same extra line in JS.

[video](https://www.veed.io/view/016e7ddf-3840-4e2f-9149-698080382174?sharingWidget=true&panel=share)
Top snippet shows my solution, bottom snippet shows current.

js
```js
/** @type {import('./$types').PageLoad} */
 // <===== matching line
export function load() {
  return {
    a: Promise.resolve('a'),
    b: Promise.resolve('b'),
    c: {
      value: Promise.resolve('c')
    }
  };
}
```

ts
```ts
import type { PageLoad } from './$types';
 // <===== extra line is here
export const load = (() => {
  return {
    a: Promise.resolve('a'),
    b: Promise.resolve('b'),
    c: {
      value: Promise.resolve('c')
    }
  };
}) satisfies PageLoad;
```

### Alternatives considered

# alternative 1
js
```js
 // <===== add it before the import
/** @type {import('./$types').PageLoad} */
export function load() {
  return {
    a: Promise.resolve('a'),
    b: Promise.resolve('b'),
    c: {
      value: Promise.resolve('c')
    }
  };
}
```
# alternative 2
ts
```ts
import type { PageLoad } from './$types';
 // <===== or remove the extra line here
export const load = (() => {
  return {
    a: Promise.resolve('a'),
    b: Promise.resolve('b'),
    c: {
      value: Promise.resolve('c')
    }
  };
}) satisfies PageLoad;
```

### Importance

nice to have

**Comment by Rich-Harris** [comment]
We're not optimising for the transition, we're optimising for the code itself — the assumption is that you're going to pick the language _you_ use and stick with it. Having a blank line between a value and its type annotation would be very unusual (and frankly rather confusing — it's much less clear that they belong together). Similarly, it's very common to have a blank line after a block of `import` declarations, so the proposed alternatives would also be undesirable.
