### ISSUE TITLE
Some adapters on npmjs.com have docs that link to the adapter-cloudflare docs instead of the correct docs

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/kit#8850]
### Describe the bug

Some adapters on npmjs.com have docs that link to the adapter-cloudflare docs instead of the correct docs.
I think this is fixed on Github but the fixes weren't reflected on npmjs.com yet.

### Reproduction

https://www.npmjs.com/package/@sveltejs/adapter-static
https://www.npmjs.com/package/@sveltejs/adapter-node

### System Info

```Shell
N/A
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This was fixed in #8594 but apparently not released yet.
