### ISSUE TITLE
Data serialization is broken if you are using full URL to API on your hostname

### ISSUE THREAD

**Issue by stalkerg** [sveltejs/kit#8852]
### Describe the bug

My API is on the same hostname but in sub path "/api". My fetch do things like `fetch('https://my.site/api/get_user')` . 
The URL from this `fetch` is testing on the server side is here https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/page/load_data.js#L190 and removing the hostname from the URL because the origin is the same, but the client trying to search the full path by selector because we use `fetch` URL as is here https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/client.js#L603 .

It raises the second request to API, from CSR. 

### Reproduction

In the load function, you should make a `fetch` with the full path to the same hostname. 

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 37.92 GB / 62.81 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    npm: 8.19.2 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.1.4 => 1.1.4 
    @sveltejs/kit: 1.3.9 => 1.3.9 
    @sveltejs/svelte-virtual-list: github:sveltejs/svelte-virtual-list => 3.0.1 
    svelte: 3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by s3812497** [comment]
> My API is on the same hostname but in sub path "/api". My fetch do things like `fetch('https://my.site/api/get_user')` .

Can you confirm if your issue is similar to https://github.com/sveltejs/kit/issues/8851 where using the SvelteKit provided `fetch` is unable to find APIs outside the framework on the same host?

If it is similar, it should be fixed by https://github.com/sveltejs/kit/pull/8869

**Comment by stalkerg** [comment]
@s3812497 seems like I have no similar issue because I am using `handleFetch`, anyway I have no crash, in my case, just serialization is broken. I suppose is a different issue but on the same theme.

**Comment by s3812497** [comment]
> @s3812497 seems like I have no similar issue because I am using `handleFetch`, anyway I have no crash, in my case, just serialization is broken. I suppose is a different issue but on the same theme.

Do you mind uploading an example project that reproduces this issue and the actual / expected behaviour?

**Comment by stalkerg** [comment]
I will try. Also, it seems like #8851 it's about `server.js`, but my issue is about fetch in load function of `+page.js`. 
But again, you can look into my link and it will be clear - SSR uses only `path` for a tag with data but the client trying to find by full URL with the hostname. 

I am not sure how to fix it... basically, we can't remove the origin if it's not a part of SvelteKit routes.

**Comment by stalkerg** [comment]
@s3812497 @dummdidumm thanks!

**Comment by s3812497** [comment]
@stalkerg thanks for filing the issue :)
