### ISSUE TITLE
(Docs) Request: improve discoverability of documentation for programmatic form submissions

### ISSUE THREAD

**Issue by fnimick** [sveltejs/kit#8866]
### Describe the problem

Use case: calling form actions from client-side event functions, similar to how `enhance` works. This is possible but not well documented outside of the module documentation, where I only found it after already figuring out what functions to call / how to perform it.

I spent a couple days figuring out how to do this, everything from "why are my form submissions always returning HTTP 200" to "how do I update the page form store with the result?"

### Describe the proposed solution

I would kindly suggest that the following be added to the [form actions documentation](https://kit.svelte.dev/docs/form-actions):

- A description of the format returned when an action is called with the header `Accept=application/json` . I spent quite a while trying to figure out why my endpoint was always returning with status 200 when the `fail` utility function was used, only when being called from a client-side fetch. We should indicate that this is expected behavior and that the response must be deserialized and handled on the client.
- An example for performing deserialization and updating the `page.form` store based on the fetch result. My searching found https://github.com/sveltejs/kit/discussions/5875#discussioncomment-3540263 which indicated that an `updateForm` handler was created, but I was unable to locate it. It took reading the `enhance` code to realize that I should be using [applyAction](https://kit.svelte.dev/docs/modules#$app-forms-applyaction) instead, after calling `deserialize`.

I suspect I am not the only one having this confusion, based on others who have commented in the discord help groups.

### Importance

would make my life easier

### Additional Information

The documentation entries for `deserialize` and `applyAction` already exist - they're just not discoverable until you already know what you are looking for. Searching for combinations of "sveltekit", "client form submission", etc does not surface them.

**Comment by dummdidumm** [comment]
To clarify:
- you want the search term "client form submission" to guide you towards the `applyAction` and `enhance` and `deserialize` entries?
- you want an entry in `Form Actions` about `deserialize`
- you want to have some info about the shape returned by a form post through `fetch`

Basically you want to have some info about "build your own `enhance` function from the ground up"?
Is that correct?

**Comment by fnimick** [comment]
The search term was just an illustration of the discoverability problem - I think adding this documentation, or a link to a detailed description, to the Form Actions page is more than sufficient.

The reasoning is to be able to define a `<form>` which submits normally without JS, but performs custom client behavior when JS is enabled, analogous to `enhance` for progressive enhancement. I want to duplicate _some_ behavior of `enhance` while also adding some of my own, in a way which is not possible through the enhance hooks. (validation on blur, etc)

My actual use case was handling form submissions through the [Felte](https://felte.dev/) client-side validation library, and interpreting the result. Having documentation on how `enhance` works would have been very helpful!

So yes, I think "how to build enhance" would work in this case - though nobody should need to do that, an illustration of how it interacts with the form action handler would have been perfect.

**Comment by fnimick** [comment]
@dummdidumm if you support adding this documentation to the `Form Actions` page, I can take a stab at it later - let me know!

**Comment by dummdidumm** [comment]
There's already the [custom event listener](https://kit.svelte.dev/docs/form-actions#progressive-enhancement-custom-event-listener) section in the form action docs. What is lacking from them that you would've found useful?

**Comment by fnimick** [comment]
Oh - I just missed that when reading. My mistake.

It's not entirely explicit to me that `applyAction` in the progressive enhacement case is intended to duplicate the behavior in the non-CSR case. That's true, yeah?

Either way, we can close this issue, unless you have any suggestions for how to improve discoverability of this documentation.

**Comment by dummdidumm** [comment]
Yes, `applyAction` does that.

Thanks, I'll close this issue then. I believe we have a more general issue about search keywords, which would help with the discoverability problem (every section could have invisible keywords attached to it).
