### ISSUE TITLE
tsconfig contains duplicate include entries

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#8872]
### Describe the bug

.svelte-kit/tsconfig.json "include" entry looks like this:

```jsonc
{
  "include": [
		"ambient.d.ts",
		"./types/**/$types.d.ts",
		"../vite.config.ts",
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte",
		"../src/**/*.js", // duplicate
		"../src/**/*.ts", // duplicate
		"../src/**/*.svelte", // duplicate
		"../tests/**/*.js",
		"../tests/**/*.ts",
		"../tests/**/*.svelte"
	]
}
```

### Reproduction

Go to https://node.new/sveltekit, open .svelte-kit/tsconfig.json

### System Info

```Shell
-
```

### Severity

annoyance

**Comment by s3812497** [comment]
https://github.com/sveltejs/kit/blob/fafe7d5f033b249d554879b5ab7bc641f0ace362/packages/kit/src/core/sync/write_tsconfig.js#L89-L94

This block is causing the duplicate entries.

But following this logic, shouldn't the output for `kit.files.routes` be along the lines of `/src/routes/**/*.js` instead of `/src/**/*.js`?
```diff
- "../src/**/*.js",
- "../src/**/*.ts",
- "../src/**/*.svelte",
- "../src/**/*.js", // duplicate
- "../src/**/*.ts", // duplicate
- "../src/**/*.svelte", // duplicate
+ "../src/routes/**/*.js",
+ "../src/routes/**/*.ts",
+ "../src/routes/**/*.svelte",
+ "../src/lib/**/*.js",
+ "../src/lib/**/*.ts",
+ "../src/lib/**/*.svelte",
```

**Comment by gtm-nayan** [comment]
Was just looking at the same thing, when the tsconfig was hardcoded in the templates, [all of src was included](https://github.com/sveltejs/kit/pull/4118/files#diff-d5bf696270e52707c851b168ea61e8fcafac2792029e816dd5b13493c501e8aaL35), and if we change it to be scoped to lib and routes now,

It might _potentially_ be a breaking change?

**Comment by s3812497** [comment]
> so can't tell if this was intended or not, and if we change it to be scoped to lib and routes now,

The default `app.d.ts` would also need to be moved to the directory of either `kit.files.routes` or `kit.files.lib`.

Additionally, specifying a single folder as the path for either of those options causes the output relative path to incorrectly go up 3 levels higher:
```
"../../../../**/*.js",
"../../../../**/*.ts",
"../../../../**/*.svelte",
```

**Comment by dummdidumm** [comment]
Only including sources in lib and routes would be a breaking change, yes. Looking closer at the logic, I'm wondering why we scoped it like this in the first place. Theoretically this would break if you're setting up the routes and lib folders in a weird way - but there's also no good way around this. I somewhat regret making parts of this that configurable.

Anyway, the fix would be to just deduplicate them. You could also have a closer look at the bug @s3812497 uncovered.
