### ISSUE TITLE
Detect new build / deployment

### ISSUE THREAD

**Issue by cannahum** [sveltejs/kit#8879]
### Describe the problem

It gets concerning when we receive a ton of errors on our monitoring platforms soon after we release a new deployment. We believe what's going on is that when a user navigates to a different page, the browser requests artifacts that are no longer there because we deployed a new version before. 

Next.js has automatic updates https://nextjs.org/docs/deployment#automatic-updates

Is this something SvelteKit supports?

Thank you.

### Describe the proposed solution

Automatically detect a newly-deployed version from the client-side, then update the client's version. Updating means refreshing the page, or updating references to artifacts should the client navigate.

### Importance

nice to have

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs/configuration#version This is already supported.
