### ISSUE TITLE
Handling explicit URL filetype is missing in examples. Eg. how would you structure `~/posts/index.json.js`?

### ISSUE THREAD

**Issue by inspiredlabs** [sveltejs/kit#8885]
Eg. how would you structure `~/posts/index.json.js`, as in this [GraphQL](https://youtu.be/zH2qG9YwN3s?t=1322) example?

Handling explicit filename extensions are missing in the examples.

```
The same principle applies to parameterized routes:

| Old Description | Old | New |
| ------------ | ----------- | ------------- |
| Filename extension | index.json.js | +page.json.js |

```

_Originally posted by @dummdidumm in https://github.com/sveltejs/kit/discussions/5774#discussioncomment-3294867_

**Comment by spences10** [comment]
In the example you're referencing it's to a `GET` http method, in that case you can use a `+server.js` with the folder taking on the filename extension `post.json\+server.js`

```text
├── src
│   ├── app.html
│   ├── lib
│   │   └── graphql-client.js
│   └── routes
│       ├── +layout.svelte
│       ├── +page.svelte
│       └── posts.json
│           └── +server.js
```

Hope that helps.

**Comment by dummdidumm** [comment]
Updated the migration guide
