### ISSUE TITLE
Password in query parameter of a request redirects user to the home page.

### ISSUE THREAD

**Issue by traviszuleger** [sveltejs/kit#8889]
### Describe the bug

If you include "password" in your query parameters at all, the request is completely avoided and instead returns a redirect to your homepage. I assume this is for security purposes, but there is no documentation anywhere (that I could find), and makes for really long debugging sessions. 

In most scenarios, a developer should avoid putting a password in query parameters completely, but for people who are developing libraries and making small changes at a time to get to a working setup may run into this and get extremely confused. (I know this, because I was one of them tonight)

### Reproduction

Create any endpoint that returns something and make a call to the endpoint with any variation of your query parameters having `password=something` (by navigation or using fetch). This will forward you straight to your home page without ever calling the endpoint. Do this again but instead change your query parameter to something like "pasword=something". This will work as intended. (NOTE: You don't need to reference the parameter at all)

```js
export async function GET(event) {
  console.log("hello world");
  return json({ hello: "world" });
}
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 5.23 GB / 15.86 GB
  Binaries:
    Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0-next.90 => 1.0.2
    @sveltejs/kit: ^1.0.0-next.587 => 1.3.10
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.1
```

### Severity

annoyance

### Additional Information

This isn't the worst thing, but it would be nice to have something documenting it in the Endpoints documentation.

**Comment by traviszuleger** [comment]
Coincidentally, I am having the same issue with any url path of "/logout". I'm not sure if this is some configuration thing that is causing this issue or what, but it is like certain words cause this redirecting issue. Any light on this subject would really be helpful.

**Comment by traviszuleger** [comment]
Sorry for spamming comments but this is just a mess. Sometimes my endpoints sometimes they don't and I am at a loss at what to do. It is so unpredictable that it is becoming one of the worst headaches to deal with.

`/logout` would never log my user out, I changed it to `/log-out` and it worked consistently. I changed it to `/sign-out` and it didn't work. I changed it to `/sign-outt` and it only worked once. I changed it back to `/log-out` and it didn't work at all. I'm not necessarily sure what is going on here, I suppose it could be my code but we are talking about endpoints that aren't working at all even if the behavior is exactly like what I have above with the `json({ hello: "world" })` example. Even with my hook turned off, these endpoints just aren't getting called and I don't understand why.

**Comment by traviszuleger** [comment]
I am closing this for now. I think this is something dumb I am not understanding and has something to do with the pages getting cached.

**Comment by dummdidumm** [comment]
There is no special handling of query parameters named password, so this must be something outside of SvelteKit

**Comment by traviszuleger** [comment]
Yeah it has something to do with the page getting cached or something. Which is why I closed it. It's not just on one endpoint, it's happening multiple times but only for my login and logout endpoints. Not sure what it is but I assume I'll figure it out eventually

**Comment by traviszuleger** [comment]
@dummdidumm It definitely is weird behavior though, if you could shed some light. In certain situations, my endpoint can only get called once and then suddenly it cannot get called again unless I hard reset my cache. Why would that be?
