### ISSUE TITLE
Trying the examples/realworld.svelte.dev  

### ISSUE THREAD

**Issue by lgs** [sveltejs/kit#890]
Trying the [examples/realworld.svelte.dev](https://github.com/sveltejs/kit/tree/master/examples/realworld.svelte.dev) got this error:

```npm ERR! Unsupported URL Type "workspace:": workspace:*```

That is in package.json declaration:

```
...
	"devDependencies": {
		"@sveltejs/adapter-node": "workspace:*",
		"@sveltejs/kit": "workspace:*",
...
```

**Comment by babichjacob** [comment]
Please fill out the provided issue template exactly as it is.

By the way, you're probably getting this error because you're probably using `npm` - try `pnpm` instead (because these are `pnpm` workspaces).
