### ISSUE TITLE
Vercel deploy error, 30 min ago it was working

### ISSUE THREAD

**Issue by RomanistHere** [sveltejs/kit#8907]
### Describe the bug

![image](https://user-images.githubusercontent.com/49812531/217034704-ebaf2c13-f2cf-485e-b75b-ae13f6711b02.png)

can't deply to vercel, previous successful deployments throw error when redeployed. adapter-vercel installed directly works

### Reproduction

-

### System Info

```Shell
vercel cloud
```

### Severity

blocking an upgrade

**Comment by RomanistHere** [comment]
https://github.com/sveltejs/kit/commit/c7648f6608a413e2654625cbd30f890d2148cf13 - I see this pr had issues with deployment

**Comment by dummdidumm** [comment]
This is likely related to that, yes. My guess is that your environment didn't grab the latest version of adapter-auto (instead using the cached version), which results in installing the latest version of adapter-vercel, which is not compatible with your SvelteKit version (needs 1.5 at least). The latest 1.x version of adapter-auto has this fixed.

**Comment by RomanistHere** [comment]
> This is likely related to that, yes. My guess is that your environment didn't grab the latest version of adapter-auto (instead using the cached version), which results in installing the latest version of adapter-vercel, which is not compatible with your SvelteKit version (needs 1.5 at least). The latest 1.x version of adapter-auto has this fixed.

![image](https://user-images.githubusercontent.com/49812531/217037277-f4de89b4-2e59-4161-a5dd-d6ca5db0f93d.png)
how can I make it "latester"?

**Comment by dummdidumm** [comment]
Oh, you're still on the `next` versions? You should probably bump all these like:
```
"devDependencies": {
  "@sveltejs/adapter-auto": "^2.0.0",
  "@sveltejs/kit": "^1.5.0",
  "svelte": "^3.55.0"
  ..
}
```

**Comment by RomanistHere** [comment]
Checking.

By the way, "still on the `next` versions" - it's what you get when you create an app with commands on kit.svelte.dev - I thought it's supposed to be that way

**Comment by RomanistHere** [comment]
I confirm it works, thanks @dummdidumm

**Comment by Conduitry** [comment]
Where on kit.svelte.dev are there instructions that result in you getting an app that uses `@next` version of dependencies? The instructions on the homepage https://kit.svelte.dev/ don't - are there some elsewhere that do and that need to be updated?

**Comment by RomanistHere** [comment]
@Conduitry just checked, not anymore. Installs 1.5 version by default
