### ISSUE TITLE
Route level config not working for `+server.js`

### ISSUE THREAD

**Issue by Smirow** [sveltejs/kit#8908]
### Describe the bug

Route level config seems to be ignored for `+server.js/ts`

### Reproduction

Deploy to Vercel with a route level config in `+server.js/ts`.

### Severity

annoyance

**Comment by Rich-Harris** [comment]
'Reproduction' is not an optional field.

If this relates to ISR, there is a known issue we are currently investigating.

**Comment by Smirow** [comment]
@Rich-Harris I thought that was pretty self-explanatory, but I guess it's not: https://github.com/Smirow/kit-issue-8908

Should create two lambda as a I defined a config in `api/+server.ts` :
```javascript
export const config: Config = {
  memory: 512,
  split: true // not needed
};
```
But when deployed to Vercel it is bundled with the other route. So it seems that `config` is getting ignored in routes defined by `+server.ts` files (as opposed to `+page.server.ts`).

**Comment by Smirow** [comment]
So probably coming from here as config are retrieved only if the route is a page:

https://github.com/sveltejs/kit/blob/48bdb0271f648c11ccdda3f991935f2f56aa0137/packages/kit/src/core/postbuild/analyse.js#L94-L130

**Comment by msonnberger** [comment]
Can confirm that if I specify `runtime: nodejs18.x` in a `+server.ts` file, the route still shows up inside `.svelte-kit/vercel-tmp/fn-0/manifest.js` whereas it doesn't if I do the same inside `+page.ts`.

envinfo:
```
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 47.92 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.n/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 9.3.1 - ~/.n/bin/npm
  Browsers:
    Firefox Developer Edition: 110.0
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-vercel: 2.0.1 => 2.0.1 
    @sveltejs/kit: 1.5.0 => 1.5.0 
    svelte: 3.55.1 => 3.55.1 
    vite: 4.1.1 => 4.1.1 
```
