### ISSUE TITLE
docs: add a small not on a good PurgeCSS extractor for Svelte CSS classes (please)

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#891]
**Is your feature request related to a problem? Please describe.**
Given (from docs):

> SvelteKit does all the boring stuff for you so that you can get on with the creative part.

and given a lot of people is using Tailwind (and the amazing [Tailwind JIT](https://github.com/tailwindlabs/tailwindcss-jit)) with [PurgeCSS](https://github.com/FullHuman/purgecss) but **there is no clear indication of what the right code is to extract the CSS Svelte classes**.

**Describe the solution you'd like**
Can we please add a note on docs for how to write a good CSS classes extractor for PurgeCSS?

**Describe alternatives you've considered**
I read a lot of pages like this: https://github.com/tailwindlabs/tailwindcss/discussions/1731.

**Comment by babichjacob** [comment]
The status quo is that integrating other libraries with Svelte doesn't belong in its documentation.

By the way, my project creates [good Tailwind configs](https://github.com/svelte-add/tailwindcss/blob/main/templates/tailwind.config.cjs) such that questions like this don't need to be asked.

**Comment by frederikhors** [comment]
I'm sorry, @babichjacob, but I don't agree on this.

I have opened an issue for a recipe perhaps in the most appropriate place.

**Comment by antony** [comment]
We don't have recipes on the svelte site. Try the community site. 

But @babichjacob is correct, we don't document third party libraries our docs, because it's not the most appropriate place.
