### ISSUE TITLE
globa.d.ts declare unstandard interface not working for svelte

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#892]
**Describe the bug**
In the file `src/global.d.ts` with the default content:

```typescript
// src/global.d.ts
/// <reference types="@sveltejs/kit" />
/// <reference types="svelte" />
/// <reference types="vite/client" />
```

...I added a custom interface:
```typescript
interface HTMLInputElement {
  webkitdirectory?: boolean;
}
```

No effect - Still such code (`webkitdirectory` in the` input` element) - is marked as wrong:
```svelte
<input type="file" id="fileinput" bind:files webkitdirectory multiple />

{#each files as file}
<li>{file.webkitRelativePath}</li>
{/each}
<script>
  let files new FileList();
</script>
```

I also tried with:
```typescript
interface SvelteInputProps {
  webkitdirectory?: boolean;
}
```
...same effect.

Is there a method to make it work?
If not, please allow it somehow.

At the same time adding an interface to `global.d.ts`:
```typescript
interface File {
	webkitRelativePath: string;
}
```
...works for lines:
```svelte
<li>{file.webkitRelativePath}</li>
```

This looks like this generally works, but the svelte types block it somehow.

**Comment by dummdidumm** [comment]
You were almost right. See https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#im-using-an-attributeevent-on-a-dom-element-and-it-throws-a-type-error on how to get it into the html typings

**Comment by lukaszpolowczyk** [comment]
@dummdidumm Thanks!

This code in `global.d.ts`:
```typescript
declare namespace svelte.JSX {
  interface SvelteInputProps {
    webkitdirectory?: boolean;
  }
}
```
...makes everything work.

**Comment by DePasqualeOrg** [comment]
> @dummdidumm Thanks!
> 
> This code in `global.d.ts`:
> 
> ```ts
> declare namespace svelte.JSX {
>   interface SvelteInputProps {
>     webkitdirectory?: boolean;
>   }
> }
> ```
> 
> ...makes everything work.

Is the solution now to put this in `app.d.ts`? I have the following:

```
<input bind:this={fileInputElement} bind:files={inputFiles} type="file" multiple webkitdirectory />
```

And I'm getting this error:

```
Argument of type '{ "bind:files": FileList; type: "file"; multiple: true; webkitdirectory: boolean; }' is not assignable to parameter of type 'HTMLProps<"input", HTMLAttributes<any>>'.
  Object literal may only specify known properties, and '"webkitdirectory"' does not exist in type 'HTMLProps<"input", HTMLAttributes<any>>'.
```
