### ISSUE TITLE
Build does not respect Vite command line option `--minify false`

### ISSUE THREAD

**Issue by brunnerh** [sveltejs/kit#8926]
### Describe the bug

When trying to create a non-minified build via [command line option `--minify false`](https://vitejs.dev/guide/cli.html#build), the build is still minified.

It *is* possible to disable minification via the configuration, however:

```ts
// vite.config.ts
export default defineConfig(config =>({
	build: {
		minify: false,
	},
	// ...
}));
```

### Reproduction

- Open https://node.new/sveltekit
- Run `npm run build -- --minify false`
- Check output files, e.g. `.svelte-kit/output/client/_app/immutable/start-*.js`

### System Info

```Shell
[Stackblitz]
```

### Severity

annoyance

### Additional Information

The `--minify` option is processed in some way.
When running `npm run build -- --minify terser`, there will be an error if `terser` is not installed.

**Comment by gtm-nayan** [comment]
I believe this is because of the secondary build thing. The option goes through for the primary build but the cli args are then not passed to the client/sw build that's started by the kit plugin afterwards.

**Comment by Rich-Harris** [comment]
I guess we need to expand this list... https://github.com/sveltejs/kit/blob/c983428942f74eb9f4a35b763127bb4bd3d90f61/packages/kit/src/exports/vite/index.js#L630-L636 ...to include all relevant properties from https://vitejs.dev/guide/cli.html#build
