### ISSUE TITLE
Server still runs on SPA if there's a store

### ISSUE THREAD

**Issue by Owez** [sveltejs/kit#8931]
- Describe the bug
- Reproduction
  - Files
  - Error
  - Real-world code
- Logs
- System Info
- Severity
- Additional Information

### Describe the bug

So basically the issue is that ive turned my application into an SPA mode app and i know everything is set correctly. everything is working fine and its all clientside until all of these things happen at once:

1. A `export const load: PageLoad = async ({ params }) => {` on a page
2. This load function imports a writable store
3. The page is refreshed

Some of the code will then run in the server. Because stores are volatile, step 3 makes it so the store gets initiated again but on the server. Say you have `writable(myInit())`, this will run on clientside like a good SPA until you refresh it. Then `myInit()` will run in the server, and probably a lot of the rest of the code.

The problem i'm having is that for some reason step 1 and 2 make it so the store init runs serverside even though it shouldnt be. On first load it runs clientside properly, it only happens if you refresh the page.

#### Files

Say you have the following code in `lib/store.ts`:

```ts
// lib/store.ts
import { writable } from "svelte/store";

export interface YarkStore { x: string, y: string, z: string }

export const yarkStore = writable(yarkStoreInitial())

function yarkStoreInitial(): YarkStore {
    console.log("You should see this in inspect element, not in the server console!!!")
    let x = window.localStorage.getItem("just_an_example") // <-- this wont work if running on server
    return /** code below and then return here */
}
```

Then this is accessed in some route which has a load function that uses the store (`+page.ts`):

```ts
import { get } from "svelte/store";
import { yarkStore } from "$lib/store";

export const load: PageLoad = async ({ params }) => {
    const store = get(yarkStore)
    // more stuff
}
```

#### Error

The first time the app runs and the page it loaded (through first load or through navigating to the page), the app will work fine. However, if you refresh the page the store will run on the server even though it's an SPA app. This will give the following error in the server console:

```
You should see this in inspect element, not in the server console!!!
ReferenceError: window is not defined
    at yarkStoreInitial (/Users/owen/Projects/yark/yark-pages/src/lib/store.ts:29:24)
    at /Users/owen/Projects/yark/yark-pages/src/lib/store.ts:12:34
    at async instantiateModule (file:///Users/owen/Projects/yark/yark-pages/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52224:9)
```

Attached is a video of me navigating to a the affected page, this happens when I click the `poland` button. It works the first time because the store loaded in the clientside, but the second time doesnt work because I refreshed the page and it's now running serverside for some reason:

https://user-images.githubusercontent.com/30081702/217298492-77d4a2e7-5c23-4a77-b09d-0e55a314f61b.mov

(See console at bottom at 9 seconds in)

#### Real-world code

- The `store.ts` library file: https://github.com/Owez/yark/blob/sveltekit/yark-pages/src/lib/store.ts 
- The `+page.ts` file: https://github.com/Owez/yark/tree/sveltekit/yark-pages/src/routes/archive/%5Bkind%5D

To run this code, clone `https://github.com/Owez/yark` and then run the following commands with Python 3.11 installed:
1. `pip3 install poetry`
2. `cd yark-api`
3. `poetry install`
4. `poetry run poe dev`

Then, open a new terminal and then run the following commands to launch the actual GUI:
1. `cd yark-pages`
2. `npm install`
3. `npm run tauri dev`

Once you've done this, press the load panel and import any random folder and give it a name; once you press the button youll be on the trouble page. Sorry about the Python steps, they're needed to get the API up and running.

### Logs

```Shell
BROWSER LOGS
============
Everything up to and including the warning was before a page refresh. I think the warning is weird, but the warning here is happening when `window` is available and everything else works alright so I'm not sure.
Logs here:
https://ibb.co/6HVGWdh

SERVER LOGS
===========

owen@Owens-MacBook-Air yark-pages % npm run tauri dev

> yark-pages@0.0.1 tauri
> tauri dev

     Running BeforeDevCommand (`npm run dev`)

> yark-pages@0.0.1 dev
> vite dev



  VITE v4.0.4  ready in 505 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
        Info Watching /Users/owen/Projects/yark/yark-pages/src-tauri for changes...
   Compiling app v0.1.0 (/Users/owen/Projects/yark/yark-pages/src-tauri)
    Finished dev [unoptimized + debuginfo] target(s) in 3.53s
4:12:10 PM [vite-plugin-svelte] ssr compile done.
package         files     time     avg
yark-pages          1   25.1ms  25.1ms
You should see this in inspect element, not in the server console!!!
ReferenceError: window is not defined
    at yarkStoreInitial (/Users/owen/Projects/yark/yark-pages/src/lib/store.ts:25:24)
    at /Users/owen/Projects/yark/yark-pages/src/lib/store.ts:12:34
    at async instantiateModule (file:///Users/owen/Projects/yark/yark-pages/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:52224:9)
```

### System Info

```Shell
ABOUT
=====

Macbook Air from 2021, the same thing happens on another NixOS computer. 

SYSTEM INFO
===========

  System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 123.59 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Firefox: 109.0.1
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/adapter-static: ^1.0.0-next.50 => 1.0.0-next.50 
    @sveltejs/kit: ^1.0.0 => 1.3.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

The SPA config I used is from the docs with static files also included. Here's my relevant svelte config:

```ts
import adapter from '@sveltejs/adapter-static';
// etc..
		adapter: adapter({
			fallback: 'index.html',
			pages: 'build',
			assets: 'build',
		}),
```

And in `routes/+layout.ts` I've got a simple `export const ssr = false`. This has been working fine up to this point and everywhere with `window` has been rendering on the client until this issue.

I'm using Tauri for filesystem stuff which is why I need an SPA. I think Tauri has a very low chance of being the problem here, as it just runs the stock sveltekit dev server as if i was doing `npm run dev`.

**Comment by Conduitry** [comment]
Please provide a minimal reproduction - not just a few files - and not one that involves installing all of the dependencies of your app.

That said, top-level stores on the server side like what you're doing are a bad idea because they will be shared across all users of the app. And even if you're building your production app as an SPA, the adapter you're using is ignored in dev mode. There will always be a server-side component of your application, which will share this state across all users (and across page reloads).

**Comment by Owez** [comment]
Soved with https://github.com/Owez/yark/pull/111
