### ISSUE TITLE
Allow form data modifying before submission with `enhance`

### ISSUE THREAD

**Issue by Glench** [sveltejs/kit#8954]
### Describe the problem

Based on [this line](https://github.com/sveltejs/kit/blob/a39ba279a71b1e2011d833e26be93d5c8077aa95/packages/kit/src/runtime/app/forms.js#L76), I just found out that if I change form values in the `submit()` function to `enhance` then the old values are submitted. e.g.

```svelte
<script>
  function submit({form}) {
    form.querySelector('input').value = "bar"
  }
</script>
<form use:enhance={submit}>
  <input name="test" value="foo" />
</form>
```

I would expect "bar" to be submitted, not "foo". What do y'all think?

### Describe the proposed solution

Just construct the form data for submission after the caller's submit function runs.

### Alternatives considered

I imagine there are cases where this might cause confusion but can't think of any off the top of my head.

### Importance

nice to have

**Comment by Glench** [comment]
Oh derp, just realized `enhance` gives you a `FormData` object to do this with. Can probably close this.

**Comment by dummdidumm** [comment]
Yes, the `FormData` object is the source of truth at that point, Dom modifications don't have an effect - closing.
