### ISSUE TITLE
Node Adapter | Gzip not working

### ISSUE THREAD

**Issue by Maggi64** [sveltejs/kit#897]
**Describe the bug**
As the title says, compression doesn't seem to work with the node adapter. 

**Logs**
_content-encoding header is missing_
![image](https://user-images.githubusercontent.com/20517052/113634848-ce344380-966f-11eb-97ea-48cf24136c7b.png)

**To Reproduce**
[REPO](https://github.com/Maggi64/svelte-kit-cache-header-issue) `npm run build` + `npm run start`

**Comment by babichjacob** [comment]
`npm run start` does not use an adapted build. Use `node build` to start your Node adapted app.

**Comment by Maggi64** [comment]
I see thanks. I missed this in the documentation somehow.
