### ISSUE TITLE
Env vars not working on svelte:head scripts

### ISSUE THREAD

**Issue by dmvvilela** [sveltejs/kit#8976]
### Describe the bug

I am trying to add google and clarity analytics to my SvelteKit website. At first I tried like joyofcode shows in his website. But then, since I need dev/prod environments, I added static env vars. Thing is, it doesn't work. Svelte for some reason does not identify those variables.. Tried with Svelte Kit 1.5, 1.5.3 and below. Env vars do exists correctly since I use in another places. Code is below:

### Reproduction

```
<script lang="ts">
	import { page } from '$app/stores';
	import { PUBLIC_GA4_METRIC_ID, PUBLIC_MS_CLARITY_ID } from '$env/static/public';

	$: {
		// @ts-ignore
		if (typeof gtag !== 'undefined') {
			// @ts-ignore
			gtag('config', `${PUBLIC_GA4_METRIC_ID}`, {
				page_title: document.title,
				page_path: $page.url.href
			});
		}
	}
</script>

<svelte:head>
	<!-- Google tag (gtag.js) -->
	<script
		async
		src={`https://www.googletagmanager.com/gtag/js?id=${PUBLIC_GA4_METRIC_ID}`}
	></script>
	<script>
		window.dataLayer = window.dataLayer || [];

		function gtag() {
			dataLayer.push(arguments);
		}

		gtag('js', new Date());
		gtag('config', `${PUBLIC_GA4_METRIC_ID}`);
	</script>

	<!-- Microsoft clarity -->
	<script type="text/javascript">
		(function (c, l, a, r, i, t, y) {
			c[a] =
				c[a] ||
				function () {
					(c[a].q = c[a].q || []).push(arguments);
				};
			t = l.createElement(r);
			t.async = 1;
			t.src = 'https://www.clarity.ms/tag/' + i;
			y = l.getElementsByTagName(r)[0];
			y.parentNode.insertBefore(t, y);
		})(window, document, 'clarity', 'script', `${PUBLIC_MS_CLARITY_ID}`);
	</script>
</svelte:head>

```

### Logs

```Shell
assinar:3472 
        
       Uncaught ReferenceError: PUBLIC_GA4_METRIC_ID is not defined
    at assinar:3472:21
(anonymous) @ assinar:3472
assinar:3484 
        
       Uncaught ReferenceError: PUBLIC_MS_CLARITY_ID is not defined
    at assinar:3484:48
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 157.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox Developer Edition: 110.0
    Safari: 16.2
```

### Severity

serious, but I can work around it

### Additional Information

Tried adding this on Discord channel at first. Did not get any response. I also tried the vars getting from a const variable on script tag, still didn't work.

**Comment by Rich-Harris** [comment]
The content of `<script>` tags is not interpolated (it would be chaos otherwise). Either put the code inside those `<script>` tags inside your main component `<script>` or put them in `src/app.html` (using `%sveltekit.env.PUBLIC_MS_CLARITY_ID%` etc)

**Comment by dmvvilela** [comment]
Oh I see.. Thanks! 
Just one thing.. I read all SvelteKit documentation, didn't find nothing really about the %sveltekit...% stuff. 
Maybe we should have one chapter explaining more in details about that.
