### ISSUE TITLE
[feature] adapter-cloudflare: make build target configurable

### ISSUE THREAD

**Issue by SimonAdameit** [sveltejs/kit#8980]
### Describe the problem

I would like the build target to be configurable for the `adapter-cloudflare` package. I want to use `es2022` to get `top level await` but `es2020` is hardcoded: https://github.com/sveltejs/kit/blob/master/packages/adapter-cloudflare/index.js#L49

### Describe the proposed solution

I'd like the build target to be configurable by the user.

### Alternatives considered

I've considered:
- making my code conform to es2020 using the `vite-plugin-top-level-await` plugin
- patching adapter-cloudflare using https://www.npmjs.com/package/patch-package

Right now I'm using a patch, as I run into problems with the `vite-plugin-top-level-await` plugin and requiring `es2022` is fine for my use-case.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Is there any reason not to just always use `es2022`?

**Comment by Rich-Harris** [comment]
According to https://github.com/cloudflare/workers-sdk/pull/2720, `es2022` is okay
