### ISSUE TITLE
SSR Fetch not adhearing to the same cookie rules as normal fetch

### ISSUE THREAD

**Issue by kivox** [sveltejs/kit#8995]
### Describe the bug

I am unsure if this is intentionally but it's also stated in the docs, `Cookies will only be passed through if the target host is the same as the SvelteKit application or a more specific subdomain of it.`. 

From how I understand this and how it acts in practice, if a cookie is set from `subdomain.domain.com` to `domain.com` and you try to access it on `subdomain.domain.com` it should work, but trying to access it in `subdomaintwo.domain.com` doesn't work (the cookie doesn't get sent). Whereas with normal fetch, if the cookie has SameSite=Lax set anything under the domain can use it, so if a cookie is set on `domain.com`, it can be used on `anything.domain.com`

So I am wondering, is this intentional? if so why, and why not adhere to the same fetch standards?

### Reproduction

Set a cookie from `domain.com`, try to send a SSR Fetch request to `anything.domain.com`

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 15.63 GB / 31.93 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)    
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.3
    @sveltejs/adapter-node: ^1.1.6 => 1.1.7
    @sveltejs/kit: ^1.0.0 => 1.5.2
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
It is intentional. The server can't tell what domain or subdomain the cookies were set on. It just has the names of the cookies the browser has exposed to it. To be cautious, SvelteKit doesn't send these cookies to different subdomains. You can have more control over it by using the `handleFetch` hook.
