### ISSUE TITLE
The best 'hello world' you've ever seen

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#90]
The page you're greeted with when you first do `npm run dev -- --open` on your first `npm init svelte` project should serve several purposes:

* it should look slick and beautiful and give you confidence that this is a well-built product crafted by people who care about well-designed user and developer experiences
* it should give you very clear 'what now?' instructions, like 'edit `src/routes/index.svelte`' and 'visit https://svelte.dev to learn how to build Svelte apps'
* it should give you some idea about the project structure (e.g. it could have an additional route, because otherwise you're left asking 'why is my `App.svelte` now called `src/routes/index.svelte`?')
* it should demonstrate interactivity, rather than just being something you could have done with static HTML
* it should elicit joy and delight, the way GREAT SUCCESS did, except without a) getting people riled up or b) being something that grates after a while
* it should make other framework authors jealous

At the same time, if you're experienced with SvelteKit, it should be very quick and easy to remove the starter files to get started with your own stuff, so there shouldn't be too many routes/components/static assets.

**Comment by rafaelcamaram** [comment]
@Rich-Harris Are you still considering this issue from Dec 2020 in the current roadmap? If it's the case, I would love to help 🙂

**Comment by Rich-Harris** [comment]
Closing this now that we have https://netlify.demo.svelte.dev (the todos app is a little wonky due to a problem with the API, but there's a separate issue to look into that https://github.com/sveltejs/api.svelte.dev/issues/8)

**Comment by FractalHQ** [comment]
In case it's unintentional - [netlify.demo.svelte.dev](https://netlify.demo.svelte.dev/) doesn't load.
