### ISSUE TITLE
Handle optional route URL params

### ISSUE THREAD

**Issue by MTyson** [sveltejs/kit#900]
**Is your feature request related to a problem? Please describe.**
In Sapper, I wanted to have two index pages like so:

```
rfrndm.com/[topic_id]
rfrndm.com
```

And then point both files to a single route component: `/routes/[optional_topic_id].svelte`

Wherein I could then just say if `topic_id == null` and then handle things accordingly.

But that didn't work,  because if you go rfrndm.com you go to `/routes/index.svelte` and if you go to `rfrndm.com/1234` you go to `/routes/[topic_id].svelte`

Long story short, you have to create two route components, a non-DRY solution.

**Describe the solution you'd like**
I would like to define `/routes/[topic_id].svelte`

And have it match requests to `/domain.com/foobar` and `/domain.com` both, so long as a specific `/routes/foobar.svelte` isn't defined.

**Describe alternatives you've considered**
Creating two route components works ok, but its not DRY.

**How important is this feature to you?**
It's not to bad to work around with two landing pages, but it's annoying and might become problematic as the app grows larger.

**Additional context**
Not sure if this is still a thing in SvelteKit, but I image it might be.

**Comment by Rich-Harris** [comment]
You can achieve this with [rest parameters](https://kit.svelte.dev/docs#routing-advanced-rest-parameters)

**Comment by MTyson** [comment]
OK, sounds like with SvelteKit, unlike Sapper, if I do `routes/[topic_id].svelte`

It will match both `/domain.com/foobar` and `/domain.com`

I'll give it a whirl when we build up the gumption to migrate.

**Comment by MTyson** [comment]
BTW, don't forget to sleep.
