### ISSUE TITLE
Change `tsconfig/json` `moduleResolution` to `bundler`

### ISSUE THREAD

**Issue by ConProgramming** [sveltejs/kit#9007]
### Describe the problem

To reiterate [this issue](https://github.com/sveltejs/language-tools/issues/1522): In [TypeScript 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7), along the property "module": "node16" that enables ESM features in TypeScript, there are new values for the property "moduleResolution": "node16" and "nodenext". Both values allows importing from dependencies with [package.json exports, imports, and self-referencing](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing). 

Right now, this property in the default `.sveltekit/tsconfig.json` is "node." This doesn't support [features like defining "types" in "exports"](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing).

### Describe the proposed solution

Change `tsconfig/json` `moduleResolution` to `node16` or `nodenext`. This will mean that relative import paths need explicit file extensions - so `'./$types.js';` instead of `'./$types';`, and similar changes. It'd be a breaking change, atleast for typescript linting, but seems to be more future proof.

### Alternatives considered

Keep `moduleResolution` as `node`. It's less future proof, as we'll keep having to use `declare module` and a global `types ` property in `package.json`.

### Importance

nice to have

**Comment by david-plugge** [comment]
Agree!

But in case you really need this today make use of `typesVersions`
```json
{
	"exports": {
		".": {
			"types": "./dist/index.d.ts",
			"default": "./dist/index.js"
		},
		"./component": {
			"types": "./dist/component.d.ts",
			"default": "./dist/component.js"
		}
	},
	"types": "./dist/index.d.ts",
	"typesVersions": {
        "*": {
            "component": [
                "dist/component.d.ts"
            ]
        }
	}
}
```
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions

**Comment by ydcjeff** [comment]
With `moduleResolution` `nodenext`, what would we use instead of `declare module`?

**Comment by dummdidumm** [comment]
We won't be changing `moduleResolution` to `next/node16` because it has lots of unpleasant side effects:
- all relative imports now need the full path and file extension (and it's weird because you need to import TS files with a `.js` ending)
- not properly built packages will suffer because their types are no longer resolved

Instead we should leverage TypeScript 5.0's upcoming [`moduleResolution: "bundler"`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler).

Changing this is a breaking change though (at least for `create-svelte`)

**Comment by charlesashby** [comment]
if you don't want to use `moduleResolution: bundler`, just declare them manually in e.g. novel.d.ts

```
declare module "novel/plugins" {
  export * from "novel/dist/plugins";
}

declare module "novel/extensions" {
  export * from "novel/dist/extensions";
}

declare module "novel/utils" {
  export * from "novel/dist/utils";
}
```
