### ISSUE TITLE
Make it possible to tell SSR (and prerendering) when a page is ready

### ISSUE THREAD

**Issue by tedsteen** [sveltejs/kit#9008]
### Describe the problem

When using `{await ...}`-blocks in templates while server side rendering or pre-rendering, the resulting page will contain the intermediate "Loading..." content that gets rendered while the promise is resolving.

This makes it impossible to generate correct (finished) pre-rendered content that contains `{await ...}`-blocks and makes SSRed pages contain unresolved content.

### Describe the proposed solution

Routify solved it [like this](https://www.routify.dev/docs/helpers#ready).

I can't really see a better way of dealing with it, except perhaps a load function for components (with a default implementation that returns a resolved promise) that can inform the page about when it's ready.

### Alternatives considered

Don't use `{await ...}` in templates and instead load all your data in `+page.js`.  This becomes particularly difficult (unfeasible) when your `{await ...}`-blocks are in components.

### Importance

would make my life easier

### Additional Information

[Discussion leading up to this issue](https://discord.com/channels/457912077277855764/1073362584025190462)

**Comment by david-plugge** [comment]
`$ready` sounds pretty cool but i wonder why you can´t use `load` in `+page.js`?

**Comment by tedsteen** [comment]
> `$ready` sounds pretty cool but i wonder why you can´t use `load` in `+page.js`?

This would mostly be a problem when awaiting content on components not pages.

**Comment by dummdidumm** [comment]
This needs support inside Svelte chore. We would need to be able to have a streaming/async SSR render method, and we would need to be able to tell Svelte that it should await a promise before resolving the rendering.

**Comment by Rich-Harris** [comment]
Going to close this as it's ultimately a Svelte issue (rather than SvelteKit) that may or may not get addressed — giving components the power to delay rendering is a decision we would need to take very carefully, as it is often a footgun — coordinating async work in `load` is less convenient in the moment but will typically yield better outcomes. Remains to be seen if we rethink our stance on this for future Svelte versions.

For posterity, the workaround in the Discord conversation was to make creative use of `transformPageChunk`

**Comment by tedsteen** [comment]
Not really something I have had problems with, but what about pre-rendered pages? It is now not possible to render correct (finished) pre-rendered pages with {await...}-blocks in them.

**Comment by dummdidumm** [comment]
This is a Svelte-core issue which we plan to look at to skip the pending block and resolve directly to the then or catch block, if possible

**Comment by tedsteen** [comment]
Alright, thanks!
Is this anything I can read about somewhere? (maybe I can help push it forward or something)
