### ISSUE TITLE
Vite `ErrorOverlay` TypeError

### ISSUE THREAD

**Issue by navtoj** [sveltejs/kit#9010]
### Describe the bug

The below error shows up in the browser console when I start the vite dev server with `npm run dev`.

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/20136585/218299346-5efb26cc-0798-421d-a0a4-96ef1cb242c7.png">

### Reproduction

It only happens sometimes so I'm not sure how to replicate it.

### Logs

```Shell
overlay.ts:152 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at new ErrorOverlay (overlay.ts:152:21)
    at createErrorOverlay (client.ts:278:29)
    at handleMessage (client.ts:247:9)
    at WebSocket.<anonymous> (client.ts:91:5)
ErrorOverlay @ overlay.ts:152
createErrorOverlay @ client.ts:278
handleMessage @ client.ts:247
(anonymous) @ client.ts:91
```

### System Info

```Shell
System:
  OS: macOS 12.6.3
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 66.80 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 19.2.0 - /usr/local/bin/node
  npm: 8.19.3 - /usr/local/bin/npm
npmPackages:
  @sveltejs/adapter-cloudflare: ^1.0.0 => 1.1.0 
  @sveltejs/kit: ^1.0.0 => 1.3.9 
  svelte: ^3.54.0 => 3.55.1 
  vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

Would this error stop the vite error overlay from showing up when some error happens in sveltekit?

**Comment by gtm-nayan** [comment]
@navtoj put a breakpoint on that line the and check what the original error message was if it happens again. There aren't many that'd have a code frame but omit the message.

**Comment by Rich-Harris** [comment]
I experienced this today, but it was fleeting. Presumably somewhere a non-`Error` is being thrown

**Comment by Rich-Harris** [comment]
figured it out: https://github.com/sveltejs/kit/pull/9440
