### ISSUE TITLE
Add `data-sveltekit-replace` link option

### ISSUE THREAD

**Issue by axwalker** [sveltejs/kit#9014]
### Describe the problem

If you want create a navigation where the navigation history is replaced, you always have to use `goto` with the `replace` option instead of an `<a>` link.

This means you lose a few benefits:

- The ability to middle-click or cmd+click to open the link in a new tab
- easy preloading of code/data with their corresponding link options
  - instead you have to call `preloadData`/`preloadCode` within an `on:click` call before your `goto` call
  - if you want the preload call to happen on hover/tap instead, you need more handlers on top
- easier a11y compliance -> instead should manually describe the role/purpose of the button (or whatever component is being used)
- any automatic link scraping that you might have set up for SEO/sitemap generation/whatever else

### Describe the proposed solution

An additional `data-sveltekit-replace` option on top of the [existing options](https://kit.svelte.dev/docs/link-options#data-sveltekit-preload-data).

This would turn something like this:

```html
<button
  on:click={() => goto('/my-path/123', { replaceState: true })}
  on:touchstart={() => preloadData('/my-path/123')}
  on:mousedown={() => preloadData('/my-path/123')}
>
  Go to page
</button>
```

into this:

```html
<a href="/my-path/123" data-sveltekit-replace data-sveltekit-preload-data="tap">
  Go to page
</a>
```

### Alternatives considered

Using `goto` as described above.

### Importance

would make my life easier

### Additional Information

A related comment was made in another somewhat related issue [here](https://github.com/sveltejs/kit/issues/969#issuecomment-1156381881).

I tried looking for other discussions on this feature and couldn't find any - sorry if I missed one!

**Comment by Rich-Harris** [comment]
Yeah, this seems like a good solution to the problem. Have to admit I've never encountered a situation where I wanted a link click to result in a `replaceState` rather than a `pushState` so as an aside I'm just curious about the details of your use case?

We should probably make it `data-sveltekit-replacestate` rather than just `replace` — more explicitness for five extra characters is a good trade IMHO.

**Comment by dummdidumm** [comment]
In general I think every goto option should have an equivalent data-sveltekit option (there are issues for the other ones AFAIK)

**Comment by axwalker** [comment]
The more explicit name sounds good.

As far as my use case - roughly, I have a list of elements on a page that are sorted in ascending order by default. Then I have a button to change this to descending and vice versa after that. This updates the query string and we prefer this not to add entries to the history. We're keeping a lot of state in the query string, so we have a few cases similar to this where `replaceState` is preferred.

**Comment by geoffrich** [comment]
`data-sveltekit-keepfocus` was also requested in https://github.com/sveltejs/kit/issues/7895#issuecomment-1376758368. +1 on providing a data-sveltekit attribute for every goto option.

This wouldn't just be useful on links, but also on progressively enhanced GET forms.

**Comment by jycouet** [comment]
Looking around... And it's exactly my need too! _And activities are a few days old. Awesome_ 🎉

---

> I'm just curious about the details of your use case

This is my structure
![image](https://user-images.githubusercontent.com/5312607/219099070-012894c3-5057-426d-95b3-9fdc7a1901a3.png)

And each folder information/periods/quotes is a tab on the page.
Users will navigate through tabs, but when they press the back button they don't expect to go to the previous tab, but to the previous page.

**Comment by danielimmke** [comment]
I would like to work on this since it is tagged as a good issue for new contributors.

**Comment by dummdidumm** [comment]
Thanks, but a PR for this already exists. You can look at the "ready to implement" label if you want to find other issues you might want to work on 👍

**Comment by axwalker** [comment]
@dummdidumm is there anything else I can help with here?
