### ISSUE TITLE
[...catchall] provoques unexpected behavior in other server fetch calls and pages

### ISSUE THREAD

**Issue by rsousacode** [sveltejs/kit#9015]
### Describe the bug

We're using [...catchall] to improve permalink and SEO such as this:

- Make call to API with the slug to see if the slug is valid.
- If the slug is invalid throw 404
-  If the slug is valid the response from the server returns content data and type, the type will allow us to render component A or B.
- This should allow us to render https://mysite.com/stuff (Component 1) and https://mysite.com/other-stuff (Component 2 )

What is happening:

- As soon we add catchall functionality, we have to use full-path instead of relative path.
- With the change above, it works on development but not on production with the difference that on production we use the same url: https://mysite.com and https://mysiste.com/api (other service)

Expected:
- Adding [...catchall] functionality doesn't provoque unexpected behavior in other routes and fetch calls, and allows to keep using relative paths in other page.server fetch calls. 

### Reproduction

https://github.com/rsousacode/AspNetSPA_SvelteKit/tree/catch_all_bug

1. Download app and run dotnet run
2. The  "not-working" route has a fetch call with relative path to "/api/WeatherForecast" that doesn't work
3. The "working" route has a fetch call with full-path that works
4. If you delete the [...catchall] folder everything starts working again.

### System Info

```Shell
Svelte Kit 1.5.5
Adapter-node 1.1.8
```

### Severity
Workaround is possible, but there's cases a proper 404 page isn't shown.

**Comment by dummdidumm** [comment]
Could you provide a reproducible that doesn't involve ASP.NET? a) to make sure that it's not related to that and b) to have a proper minimum reproducible.

**Comment by rsousacode** [comment]
> Could you provide a reproducible that doesn't involve ASP.NET? a) to make sure that it's not related to that and b) to have a proper minimum reproducible.

Sure. 

Here's a example using NodeJS.
https://github.com/rsousacode/sveltekit-dynamic-routing-bug

If you visit "/api/hello" you get the "Hello World" response in the browser, but svelte-kit can't handle it.

**Comment by rsousacode** [comment]
I am not even sure if this is the proper way to do:
`/my-url-one` -> Render Component 1
`/my-url-two` -> Render Component 2 

If it's not it'd be cool if you mention a workaround, in order to go forward with this technology for some future projects.

**Comment by rsousacode** [comment]
Given the api route in both examples starts with `/api/` I found a workaround that includes using params/route.js like this

```js
/** @type {import('@sveltejs/kit').ParamMatcher} */
export function match(param) {
    return /^(?!\/api\/).*/.test(param);
}
```

and instead of using [...catchall] I use [page=route], and still be able to "catch" all other urls.

I'll close this, since this params feature fits well for this use case. Thank you.

**Comment by rsousacode** [comment]
Sorry, I am re-opening this since the workaround above doesn't work for links that has multiple slashes, such as `my-category/my-post` which [...catchall] handles. I hope the above reproduction(s) I gave is enough for this.

With the above WORKAROUND it has the following problems:

1)  Using  `[page=route]/[...rest]` ,`[...rest]`  is catching links that [page=route] should ignore (in this case routes that start with "/api/"). (This deserves its own issue)

2) If the user types "/api/a-non-existing-endpoint" instead of showing a neat 404 page, svelte-kits totally ignores the route, with [...catchall] I could present a proper 404 page.
