### ISSUE TITLE
Bug with Node adapter?

### ISSUE THREAD

**Issue by CropWatchDevelopment** [sveltejs/kit#9017]
### Describe the bug

Building my application with the mongo db package + node adapter results in:
> Using @sveltejs/adapter-node
Circular dependency: node_modules/mongodb/lib/change_stream.js -> node_modules/mongodb/lib/collection.js -> node_modules/mongodb/lib/change_stream.js
Circular dependency: node_modules/mongodb/lib/collection.js -> node_modules/mongodb/lib/operations/rename.js -> node_modules/mongodb/lib/collection.js
Circular dependency: node_modules/mongodb/lib/change_stream.js -> node_modules/mongodb/lib/cursor/change_stream_cursor.js -> node_modules/mongodb/lib/change_stream.js
Circular dependency: node_modules/mongodb/lib/change_stream.js -> node_modules/mongodb/lib/db.js -> node_modules/mongodb/lib/change_stream.js
Circular dependency: node_modules/mongodb/lib/change_stream.js -> node_modules/mongodb/lib/mongo_client.js -> node_modules/mongodb/lib/change_stream.js
Circular dependency: node_modules/mongodb-connection-string-url/lib/index.js -> node_modules/mongodb-connection-string-url/lib/redact.js -> node_modules/mongodb-connection-string-url/lib/index.js
Circular dependency: node_modules/@aws-sdk/credential-provider-ini/dist-es/resolveProfileData.js -> node_modules/@aws-sdk/credential-provider-ini/dist-es/resolveAssumeRoleCredentials.js -> node_modules/@aws-sdk/credential-provider-ini/dist-es/resolveProfileData.js
Circular dependency: node_modules/@aws-sdk/util-endpoints/dist-es/utils/callFunction.js -> node_modules/@aws-sdk/util-endpoints/dist-es/utils/evaluateExpression.js -> node_modules/@aws-sdk/util-endpoints/dist-es/utils/callFunction.js
Circular dependency: node_modules/@aws-sdk/util-endpoints/dist-es/utils/getEndpointProperties.js -> node_modules/@aws-sdk/util-endpoints/dist-es/utils/getEndpointProperty.js -> node_modules/@aws-sdk/util-endpoints/dist-es/utils/getEndpointProperties.js
Circular dependency: node_modules/@aws-sdk/util-endpoints/dist-es/utils/evaluateRules.js -> node_modules/@aws-sdk/util-endpoints/dist-es/utils/evaluateTreeRule.js -> node_modules/@aws-sdk/util-endpoints/dist-es/utils/evaluateRules.js
Circular dependency: node_modules/mongodb/lib/mongo_client.js -> node_modules/mongodb/lib/connection_string.js -> node_modules/mongodb/lib/encrypter.js -> node_modules/mongodb/lib/mongo_client.js
Circular dependency: node_modules/mongodb/lib/index.js -> node_modules/mongodb/lib/change_stream.js -> node_modules/mongodb/lib/mongo_client.js -> node_modules/mongodb/lib/connection_string.js -> node_modules/mongodb/lib/encrypter.js -> node_modules/mongodb/lib/index.js
Circular dependency: node_modules/mongodb/lib/mongo_client.js -> node_modules/mongodb/lib/connection_string.js -> node_modules/mongodb/lib/mongo_client.js
Circular dependency: node_modules/mongodb/lib/sdam/server.js -> node_modules/mongodb/lib/sdam/monitor.js -> node_modules/mongodb/lib/sdam/server.js
Generated an empty chunk: "_server.ts".
Generated an empty chunk: "_server.ts".
Generated an empty chunk: "_server.ts".
Generated an empty chunk: "_server.ts".
Generated an empty chunk: "_server.ts".

### Reproduction

Fresh project with "mongodb": "^4.13.0", and "@sveltejs/adapter-node": "^1.1.8", installed with --save-d

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21.1 (Vera)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 7.09 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.19.0 - /usr/bin/node
    npm: 8.19.3 - /usr/bin/npm
  Browsers:
    Brave Browser: 110.1.48.158
    Chrome: 110.0.5481.77
    Firefox: 109.0.1
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.2 
    @sveltejs/adapter-node: ^1.1.8 => 1.1.8 
    @sveltejs/kit: ^1.0.0 => 1.3.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.0.4
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I am pretty sure this isn't related to my code as the dependencies don't show anything from me, it is all within the node modules directory, I have tried deleting and re-pulling npm stuff, no luck. Any input is appreciated!

**Comment by Conduitry** [comment]
Does the build application not work? Those sound like the regular circular dependency _warning_ from Rollup that are often not actually a problem.

If you are having trouble bundling a given dependency with Rollup in the Node adapter, you can move it to a prod dependency so that it becomes a runtime dependency of your app rather than being bundled at build time.

**Comment by CropWatchDevelopment** [comment]
I have moved the mongodb from `DevDependencies`, to `dependencies`, That solved the issue, I should have known this. It slipped by until you mentioned it. I am sorry for raising a false alarm. And Thank you very much for helping me catch that!
