### ISSUE TITLE
Error while navigating: index.mjs:20 --> Uncaught (in promise) TypeError: fn is not a function

### ISSUE THREAD

**Issue by faulander** [sveltejs/kit#9028]
### Describe the bug

when i navigate inside the app, (most of the time, but not always) the error below is shown.
I don't know where to start looking for the problem, since the error is internal sveltekit only i presume.

**THIS ONLY HAPPENS** when navigating, **NEVER** when refreshing the page.

I would be happy if you could point me in the right direction on why and where this error can happen.

### Reproduction

i tried, but i cannot come up with a minimal example, since my codebase is already pretty huge. 

### Logs

```Shell
index.mjs:20 

       Uncaught (in promise) TypeError: fn is not a function
    at run (index.mjs:20:12)
    at Array.forEach (<anonymous>)
    at run_all (index.mjs:26:9)
    at destroy_component (index.mjs:1973:9)
    at root.svelte? [sm]:42:41
    at index.mjs:1258:17
    at run (index.mjs:20:12)
    at Array.forEach (<anonymous>)
    at run_all (index.mjs:26:9)
    at check_outros (index.mjs:1238:9)
run @ index.mjs:20
run_all @ index.mjs:26
destroy_component @ index.mjs:1973
(anonym) @ root.svelte? [sm]:42
(anonym) @ index.mjs:1258
run @ index.mjs:20
run_all @ index.mjs:26
check_outros @ index.mjs:1238
update @ root.svelte? [sm]:42
update_slot_base @ index.mjs:100
update @ +layout.svelte:296
update_await_block_branch @ index.mjs:1575
update @ +layout.svelte:106
update @ index.mjs:1209
flush @ index.mjs:1169
Promise.then (asynchron)
schedule_update @ index.mjs:1120
make_dirty @ index.mjs:1984
(anonym) @ index.mjs:2022
$$self.$$set @ root.svelte? [sm]:45
(anonym) @ proxy.js?v=618c5227:83
$set @ index.mjs:2123
dest.<computed> @ proxy.js?v=618c5227:46
update @ client.js?t=1676284422168&v=618c5227:362
await in update (asynchron)
navigate @ client.js?t=1676284422168&v=618c5227:1148
(anonym) @ client.js?t=1676284422168&v=618c5227:1520
```

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (6) x64 Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
    Memory: 4.58 GB / 7.74 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91 
    @sveltejs/adapter-node: ^1.0.0-next.88 => 1.1.8 
    @sveltejs/kit: ^1.0.0 => 1.5.3 
    svelte: ^3.50.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

Additional information:
It only happens on navigating. I have this code which shows a loading spinner while nagivating (it has no influence on the error, because it also happens when i remove it) which might give a clue:

```
	{#if Boolean($navigating)}
		<div class="fixed w-full h-full z-10" in:fade={{ duration: 150 }}>
			<div class="absolute w-full h-full bg-slate-400 dark:bg-slate-700 opacity-50 z-10" />
			<div class="absolute w-full h-full flex justify-center items-center z-20">
				<Shadow size="300" color="#15803d" unit="px" />
			</div>
		</div>
	{/if}
```
When the bug appears, this happens:
- The adress in the adress bar doesn't change, it stays on the page i clicked a link
- the loading spinner never stops (so $navigating is never updated?) 

More Info:
- it happens on almost all pages, but not all the time, maybe 90%
- it never happens on the root page
- it happens on all browsers
- it happens when running dev-server, cannot deploy this to productive ;) 

I know that that information might not suffice to resolve it, so i would be happy if you could give me a tipp, where this error is thrown and what' might cause it.

**Comment by Conduitry** [comment]
This isn't the first issue you've opened with no real reproduction. Please stop doing this.

**Comment by Rich-Harris** [comment]
I recommend learning the [Divide and Conquer](https://github.com/braydie/HowToBeAProgrammer/blob/master/en/1-Beginner/Personal-Skills/02-How-to-Debug-by-Splitting-the-Problem-Space.md) debugging strategy
