### ISSUE TITLE
Explicit SSR Imports

### ISSUE THREAD

**Issue by DrewDaPilot** [sveltejs/kit#905]
**Is your feature request related to a problem? Please describe.**
In short, the issue here is caused by how SSR is generated and bundled. When import client side libraries such as `firebase` or `js-cookie` I have found that the site does not run because the client libraries are still being imported into the server runtime resulting in SSR errors.

**Describe the solution you'd like**
Ideally there would be a vite extension that can interpret imports accordingly such that the imports can be top level like they are in sapper. From my experience I did not have this issue when using Sapper, only with sveltekit.

**Describe alternatives you've considered**
One possible alternative would be to have a config file where you can explicitly declare which imports are server and which imports are client side. Not really sure how the sapper stack handled it but I could not reproduce a similar issue with sapper.

**How important is this feature to you?**
This feature is not direly important, but it is a quality of life feature and most developers might be confused by the inability for them to easily import modules at the top level of their script blocks without causing various warnings or errors.

**Comment by DrewDaPilot** [comment]
To clarify,

```md
<details>
	import { goto } from '$app/navigation';	
	import { browser } from '$app/env';

	if (browser) {
		import firebase from '$lib/fb.js';
		import Cookies from 'js-cookie';
	}
</details>
``` 

The recommended approach which is to use a conditional with the `browser` statement does not appear to work as it gives an error about top level imports.

**Comment by benmccann** [comment]
You can do a dynamic import in `onMount`. See https://kit.svelte.dev/docs#troubleshooting-server-side-rendering

**Comment by DrewRidley** [comment]
I dont know that this issue should be closed. I spent a few hours communicating with people on the discord about the issue and its a pretty significant migration to require all users to replace top level imports with sophisticated and ugly dynamic imports.

```js
import lib from 'lib'

onMount() {
   useLib();
}
``` 
the following example worked fine with sappers bundler, but not with vite. Instead, users are expected to learn how to use dynamic imports without any documentation or clarification as to why.

```js
let lib;
onMount() {
   if (browser) {
    lib = (await import('lib')).default;
  }
}
```
perhaps these examples can shed some light into some more examples of why this issue should be investigated further.

**Comment by benmccann** [comment]
I've proposed a solution for this type of problem over in https://github.com/sveltejs/kit/issues/754

**Comment by DrewRidley** [comment]
I am not necessarily referencing a true SPA scenario. I was thinking something more along the lines of sapper. I still want SSR to be enabled, but I would like certain imports that are client-only to still feel natural. I can look into the how the vite plugin works and its possible this can be adapted to be added. I understand that vite is very different from rollup so I dont know how feasible it is.

**Comment by benmccann** [comment]
I guess you could automatically wrap every `onMount` call with `if (browser)` in a custom preprocessor. You'd still need the dynamic import in that case though. I'm not sure this is something we'd want to add to the default vite plugin at this point. It'd probably be better to keep it separate and see if there's enough demand for it before we'd want to do something like that on a more official basis

But I'd say your best bet would be to try https://modularfirebase.web.app/ and hope it might support being loaded on the server-side more easily than the standard Firebase libraries (which were a huge source of pain even in Sapper even if it's a bit worse in SvelteKit) and if not try to give feedback to the Firebase team that helps them improve those libraries (e.g. using `fetch` instead of `XMLHttpRequest`, etc.)

**Comment by benmccann** [comment]
@DrewRidley thanks for the idea. While I wasn't so excited about the prospect of doing this with a preprocessor, I think we could do this directly in the Svelte compiler. We've filed an issue for this over in https://github.com/sveltejs/svelte/issues/6372

**Comment by jthegedus** [comment]
>But I'd say your best bet would be to try modularfirebase.web.app and hope it might support being loaded on the server-side more easily than the standard Firebase libraries (which were a huge source of pain even in Sapper even if it's a bit worse in SvelteKit) and if not try to give feedback to the Firebase team that helps them improve those libraries (e.g. using fetch instead of XMLHttpRequest, etc.)

Just to reduce confusion on this topic, Firebase have distinct libraries for Browser vs Server which share *some* API surface. The modular (v9) rewrite of these SDKs is in different states:

- Browser: Firebase JS SDK - (in beta) https://firebase.google.com/docs/web/modular-upgrade
- Server: Firebase Admin Node.js SDK - (in alpha) https://modular-admin.web.app/

The differences in the APIs depends on the products being used, with calls to services from the Server (Cloud Function is the common env for this) bypassing the [Security Rules](https://firebase.google.com/docs/rules) model of Firebase. Given that, take care using Firestore from the Browser SDK in SvelteKit Endpoints or SSR components as your Sec Rules are being bypassed.

**Comment by cupcakearmy** [comment]
Has anyone got it to work in svelte kit?

I constantly get `IDBIndex is not defined` event with

```
import preprocess from 'svelte-preprocess'
import adapter from '@sveltejs/adapter-node'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: preprocess(),

  kit: {
    adapter: adapter(),
    target: '#svelte',
    ssr: false,
    prerender: {
      enabled: false,
    },
  },
}

export default config
```

Is there something I'm missing? dynamic importing the library in an onMount does not seem to work.

**Comment by jthegedus** [comment]
@cupcakearmy It depends on the Firebase modules you are using. `firebase/firestore`, which most people are using, doesn't have a dependency on IDBIndex so aren't facing this issue.

This is feedback the Firebase team would like to receive. I have observed the `IDBIndex` error you report when trying to use the `firebase/performance` module.

**Comment by cupcakearmy** [comment]
@jthegedus I got it work now. The issue that I was not realizing was that dynamic for firebase don't work in dev mode, only in the actual builds for some reason.
Thanks!

**Comment by jthegedus** [comment]
> @jthegedus I got it work now. The issue that I was not realizing was that dynamic for firebase don't work in dev mode, only in the actual builds for some reason.
> Thanks!

Curious, it works in Dev and Prod for me

**Comment by cupcakearmy** [comment]
The quirks of working with beta software I guess :)
But I love svelte kit too much to wait 😆 It's the best thing that happened to web development in a looooing time 🥰

**Comment by sheecegardezi** [comment]
i dont think this is resolved!

**Comment by lucidNTR** [comment]
the issue seems to have been accidentally closed by an unrelated PR. the dynamic imports break bundling and also slow down app startup.

**Comment by benmccann** [comment]
I'm not sure that there's anything we could change in SvelteKit, but our current design for Svelte 5 will make it easier and more natural to deal with client-side only code, so stay tuned!

**Comment by carstenjaksch** [comment]
I have a similar issue, but with a Node module (jsdom) that should only run on the server. On the client, I want to use the corresponding browser APIs.

Asked a question about that: https://github.com/sveltejs/kit/discussions/11090

**Comment by FeldrinH** [comment]
> I'm not sure that there's anything we could change in SvelteKit, but our current design for Svelte 5 will make it easier and more natural to deal with client-side only code, so stay tuned!

@benmccann What is this new design in Svelte 5 that you mentioned? I took a look at the Svelte 5 RC documentation and release notes and could not figure out what part of the changes makes dealing with client-side only code easier.

**Comment by VityaSchel** [comment]
I'm struggling with this when using `page` in pre-defined variables. Svelte tries to import an object that uses `page` before rendering which causes the error `Can only read 'page.url' on the server during rendering (not in e.g. `load` functions)`. I'd love to see ssr-level imports implemented.
