### ISSUE TITLE
Usage of process.env with $env module is unclear

### ISSUE THREAD

**Issue by seanlail** [sveltejs/kit#9060]
### Describe the problem

The documentation for the `$env` modules seems to focus on using `.env` files.
https://kit.svelte.dev/docs/modules#$env-dynamic-private

- There is a small mention that `process.env` can be used in the _static_ module [here in the tutorial](https://learn.svelte.dev/tutorial/env-static-private), but this doesn't really work with typescript.
- There's a bit in the Node Adapter docs that says `$env` [doesn't work _in production_](https://kit.svelte.dev/docs/adapter-node#environment-variables). I'm also not sure "static" is where that should be. I want to use `process.env.X` dynamically.

Additionally, If I don't have a `.env` file I _think_ the `$env` module is not even generated, so that fails in `svelte-check`.

It would be good to explain how to set the types up when using only `process.env.X` and not `.env` files.

(as an aside, I found that if I create a `.env` file, to get the types I have to fill in everything... but that means I'm filling in things I might not want to be available in local / dev mode. e.g. analytics apiKeys - I don't want to run that locally)

### Describe the proposed solution

Clarity in the documentation on how to use this feature correctly with TypeScript support.

I'm not sure if this is even working as intended - is this perhaps a bug?

### Alternatives considered

I've done this but I'm not sure this is going to be dynamic and secure.
As I have read in the docs, using `.server` in the filename will protect that data from leaking to the client.

```typescript
// src/config.client.ts
export const config = {
  notSecret: process.env.PUBLIC_NOT_A_SECRET || ''
};
```

```typescript
// src/config.server.ts
export const config = {
  secretKey: process.env.SECRET_KEY || ''
};
```

### Importance

nice to have

### Additional Information

Here's a working version I have: https://github.com/seanlail/kit-issue-9060

This works for me because I have typed a `config.client` and `config.server` because I can't set the types for the `$env` module.

For dev mode created a `.env.local` file with this contents:
```
PUBLIC_ENV_VAR=public_from_env
PRIVATE_ENV_KEY=private_from_env
```

For production I run `npm run build` and then server it with:
```
PUBLIC_ENV_VAR=node_public_key NODE_ENV=production PRIVATE_ENV_KEY=node_private_key PROD_ONLY_KEY=node_prod_only_key node build
```

Result is below

| Dev | Production | 
| --- | --- |
| <img width="303" alt="image" src="https://user-images.githubusercontent.com/142589/220158827-4d4de415-9228-4417-9161-6b3c8745590d.png"> | <img width="322" alt="image" src="https://user-images.githubusercontent.com/142589/220158725-0666eaaf-e2cf-4249-8580-3d28ca932b53.png"> |

**Comment by tcc-sejohnson** [comment]
I'm not sure what the problem is after reading this issue a couple of times -- after rereading the documentation, all of the information is there, and `$env` is working as intended. Maybe if you provide a repro or describe the actual issue you're running into I can help.

**Comment by seanlail** [comment]
@tcc-sejohnson Sorry, I'll create a repo shortly to show the issues.

**Comment by seanlail** [comment]
@tcc-sejohnson I've updated the "Additional Information" section with repo link and details.
