### ISSUE TITLE
Build an output that is usable from local disk (file:// URL)

### ISSUE THREAD

**Issue by jzillmann** [sveltejs/kit#907]
**Is your feature request related to a problem? Please describe.**
Quite often i code tools which take some input (like a JSON file) and generate a HTML report out of it. This HTML report might be served by a server (e.g. Github Pages) but often just sits somewhere on the disk and should be openable/consumable from there (e.g. `open file:///Users/x/projects/y/build/test/index.html`).

**Describe the solution you'd like**
From initial experiments (with `adapter-static`) I found 2 things I would need for the above to work which I failed to accomplish with `svelte-kit` so far:
- Links/Includes (from `index.html`) need to be relative instead of absolute
  - `paths/assets||base` were quite resistant setting up anything relative 
- The JS field need to be in `IIFE` format (since [module script imports will raise CORS issues](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts))
  - `vite.build: { lib: { name: "my-app", entry: "src/main.ts", formats: ["iife"] }}` produced `UMD and IIFE output formats are not supported for code-splitting builds`

A solution would be to make the 2 things possible.
Perfect would be a simple way to achieve that. Like an specialized adapter.

**Describe alternatives you've considered**
Maybe what I'm trying to achieve is dump and using svelte-kit for such a thing doesn't make much sense? Just stick to `Svelte Classic` ?

With `Svelte Classic` and Vite I can accomplish the above by tweaking `vite.config.js` in the following way:
- Set `base` to `''` (makes the links relative)
- Configure `IIEF` format:
```
build: {
  lib: { name: "my-app", entry: "src/main.ts", formats: ["iife"] },
}
```
- Move the `index.html` to `public/` and add appropriate script and css includes

**How important is this feature to you?**
This is the first thing I usually set up for the majority of apps I'm crafting.

**Comment by KonradHoeffner** [comment]
I understand your pain as I have the same problem. See also issues https://github.com/sveltejs/kit/issues/1553 and https://github.com/sveltejs/kit/issues/1154.

**Comment by btakita** [comment]
@jzillmann Re your current `Svelte Classic` & `Vite` solution: how are you doing your routing?

**Comment by jzillmann** [comment]
@btakita Not sure what you mean...

**Comment by btakita** [comment]
@jzillmann How are you currently routing to the different "page" components in the SPA? I wonder if it's feasible to extract only the Sveltekit router to use with Classic Svelte & Vite.

**Comment by jzillmann** [comment]
Oh, I guess i just do customized routing, nothing special there!

**Comment by maximedupre** [comment]
This issue is essential for Electron apps, which use the filesystem.

All the links and scripts in the page are absolute, so it doesn't work.

**Comment by btakita** [comment]
Just a heads-up. I'm working on a fork of Sapper to support `file://` hash-based routing. My project needs to continue supporting sapper until some SSR issues are fixed (https://github.com/vitejs/vite/issues/4306).

My current work in progress is at https://github.com/btakita/sapper/tree/hbr

**Comment by btakita** [comment]
I was able to modify the routing to switch between hash-based routing when the origin is `file://` & otherwise the default path-based-routing. https://github.com/btakita/sapper/tree/hbr

When the time comes to migrate my project over to Svelte Kit, I'll work on a PR. The conditionals are spread out in several places in https://github.com/btakita/sapper/blob/hbr/runtime/src/app/router/index.ts & https://github.com/btakita/sapper/blob/hbr/runtime/src/app/goto/index.ts.

I didn't want to do any major refactorings, lest the hbr branch diverge too much from the master branch.

**Comment by AlsDevShack** [comment]
Also hoping this can get added to sveltekit.

Is there a workaround available? 
I'd like to keep using SvelteKit for creating the full blown app with a server. But also need the SPA app to be run from file too.

**Comment by easyfrog** [comment]
any solution for now?
I want to use `sveltekit` and `adapter-static` to generate static html files use on `cordova`, but there is no luck for now.

**Comment by mattiash** [comment]
After a lot of tinkering I have managed to build a script that can take an html-file generated by adapter-static and inline all javascript in the file. It is very hacky and runs code in the browser to make the imports work, but it works for my use-case which is to build simple html-files with a bit of interactivity in them that I can send in an email without hosting them anywhere. Might be useful as inspiration for someone.

The trickiest part is that the only way I could use `import` was if the the module was added as a blob to the page. But adding it as a blob generates a new url for the module, which means that all `import` statements must be rewritten after the blob has been added.

https://github.com/mattiash/svelte-notebook/blob/master/util/inlinejs.cjs

**Comment by chadian** [comment]
I also came up with a hacky workaround for a similar issue including hash routing, not sure if it's specific to `file:///` but as an `index.html` being loaded from within an extension which I think is treated similarly.

1. Create an [`index.html/+page.svelte` route](https://github.com/chadian/vorfreude/pull/19/files#diff-c612315e6bc87036fe4bab27a173b0d5bfe5f7c34bb425e318b58b6561e231e7) that is not prerendered, which is ran when the extension loads the `index.html`. This `index.html` route then redirects to the root route via `goto('/')`; 
2. Hash routes are swapped in after route transitions ([`handleRouteChange`](https://github.com/chadian/vorfreude/pull/19/files#diff-25e5b05cf766f76e1980b783f95605006529e6788addfa397a887d26f0ce58e4) with `afterNavigate` on root `+layout.svelte`)
3. On app initialization any initial hash routes are navigated to the correct route ([`handleInitialHashRoute`](https://github.com/chadian/vorfreude/pull/19/files#diff-25e5b05cf766f76e1980b783f95605006529e6788addfa397a887d26f0ce58e4) with `onMount` on root `+layout.svelte`) and subsequently replaced with the hash route again.

**Comment by MentalGear** [comment]
This might what ya all are looking for:
https://github.com/richardtallent/vite-plugin-singlefile

**Comment by till** [comment]
I hope this is the correct issue to comment on.

My use-case is similar, even though I don't need it to work standalone with `file://`.

I am trying to make a my application work within an electron app. For that, I found that if I was not using SvelteKit, I could configure vite with `base: './'` and it would work as expected. With SvelteKit this currently seems  impossible as all paths have to empty or absolute.

When I leave `kit.paths.base` empty, it won't use what I put in vite either. Seems like the configuration for SvelteKit wins either way.

**Comment by benmccann** [comment]
@till it would seem that SvelteKit always sets base to `./` when building the client:

https://github.com/sveltejs/kit/blob/cad0389e5f5f6d407e1c48f45d84c28c744d73aa/packages/kit/src/exports/vite/index.js#L431

Is there anything you notice being different in the output between a normal Vite build with `./` and a SvelteKit build?

**Comment by till** [comment]
@benmccann Maybe I am using it wrong, or using not the latest? I just upgraded to a `1.x`.

When I set `base` in vite's config mothing happens, when I leave `paths.base` empty in SvelteKit's configuration, all paths in the build are `/` and then my app fails to run.

**Comment by till** [comment]
Hmm, looking at the code, maybe `paths.base` vs `paths.assets`?

**Comment by benmccann** [comment]
> Links/Includes (from index.html) need to be relative instead of absolute

The file references are relative now:

![Screenshot from 2023-01-23 15-36-27](https://user-images.githubusercontent.com/322311/214176455-aaf27b55-ccca-46ce-8fda-177d44e2b5bc.png)

> The JS field need to be in IIFE format (since [module script imports will raise CORS issues](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts))

Yep. It looks like this is the main blocker:

![Screenshot from 2023-01-23 15-36-43](https://user-images.githubusercontent.com/322311/214176441-c18aa43a-7853-471a-bb4f-76620407ee42.png)

**Comment by till** [comment]
@benmccann is there anything to check on my end?

This is the code that gets generated currently:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="description" content="" />
		<link rel="icon" href="/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<meta http-equiv="content-security-policy" content="">
		<link rel="modulepreload" href="/_app/immutable/start-029f2991.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/index-1e690e6a.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/singletons-89169131.js">
		<link rel="modulepreload" href="/_app/immutable/chunks/index-e3c86715.js">
	</head>
	<body class="flex flex-col items-center min-h-screen">
		
		<script type="module" data-sveltekit-hydrate="45h">
			import { start } from "/_app/immutable/start-029f2991.js";

			start({
				env: {},
				paths: {"assets":"","base":""},
				target: document.querySelector('[data-sveltekit-hydrate="45h"]').parentNode,
				version: "1674548434903"
			});
		</script>
	</body>
</html>
```

My `svelte.config.js`:

```js
// import adapter from '@sveltejs/adapter-auto';
import adapter from '@sveltejs/adapter-static'
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
export default {
	extensions: ['.svelte'],
	kit: {
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: 'index.html',
			precompress: false,
		}),
	},
	preprocess: [
		preprocess({
			postcss: true,
		}),
	],
}
```

My `vite.config.js`:

```
const config = {
	build: {
		minify: true,
	},
	resolve: {
		alias: {
			$routes: path.resolve('./src/routes'),
			$store: path.resolve('./src/store'),
		},
	},
	plugins: [sveltekit()],
}
export default config
```
