### ISSUE TITLE
`prerender` setting in empty `server.js` causes request errors despite the page working in browser

### ISSUE THREAD

**Issue by Dan1ve** [sveltejs/kit#9074]
### Describe the bug

When
```js
export const prerender = true;

// No other content in file
```
is used in a `server.ts` file that does not contain any other code, the site appears to be working fine in browsers (no errors on page or in network tab).

However, external tools (e.g. Google Search Console, sitemap generators  or simply `curl`) will report a `40x: Method not allowed` error.

This can be fixed by adding an empty `GET()`  method in the same file, like so:

```js
export const prerender = 'auto';

export async function GET() {
	return new Response();
}
```

The [docs](https://kit.svelte.dev/docs/page-options#prerender) don't mention that this is necessary, and it's very confusing that some tools claim the site doesn't work. 

This bug may be a variant or generalization of #8428 

### Reproduction

1. Create a route with a dummy `+page.svelte`, an empty `+server.js` and add `export const prerender = true;`
2. Run `build` and then `preview`
3. Call `curl http://<your-route>`

Expected: No errors.
Actual:  Curl responds with `GET method not allowed` 

### Logs

```Shell
Based on the example above:

curl http://localhost:4173
GET method not allowed

Google Search Console reports:

"Failed: Blocked due to other 4xx issue"
```

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 38.43 GB / 62.48 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 18.14.0 - /usr/bin/node
    npm: 9.3.1 - /usr/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 109.0.1
  npmPackages:
    @sveltejs/adapter-node: 1.2.0 => 1.2.0 
    @sveltejs/kit: 1.7.0 => 1.7.0 
    @sveltejs/vite-plugin-svelte: 2.0.2 => 2.0.2 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.1.1 => 4.1.1
```

### Severity

annoyance

### Additional Information

Just wanted to say thanks for this amazing framework :smile_cat:

**Comment by s3812497** [comment]
What's your use case for creating an empty endpoint route?

Currently, any http method not exported will result in a `405 method not allowed` for the endpoint route.

**Comment by Dan1ve** [comment]
I wanted to enabled prerender for that particular route, so I followed the docs. Did I misinterpret something?

**Comment by Rich-Harris** [comment]
But _what_ are you prerendering?

**Comment by tcc-sejohnson** [comment]
The only reason you would export `prerender = true` from a `+server.ts` file is if you wanted to generate a prerendered API response from that route at buildtime. My guess is the behavior you want in this instance is actually your page to be prerendered. If so, move the export to `+page.svelte`.

**Comment by Dan1ve** [comment]
There probably was a misconception on my side. In addition to the `+server.ts` file, I have a `+page.server.ts` that looks something like this

```ts
export async function load() {
   return {
      posts: await loadBlogPosts()
   }
}
```

I thought I _had_ to place the `prerender` flag to the `+server.ts` file, but that's not true. Also, I think the docs might have changed in the meantime. Issue can be closed, thanks for all the swift responses!
