### ISSUE TITLE
adapter-node custom onwarn option

### ISSUE THREAD

**Issue by vfilatov** [sveltejs/kit#9076]
### Describe the problem

Would be great to pass a custom onwarn handler to `adapter-node` from `svelte.config.js` like:

```js
import node from '@sveltejs/adapter-node';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: node({
      onwarn: (warning, handler) => {
        if (/regexp/.test(warning))
          return;
        handler(warning);
      }
    }),
  },
};

export default config;
```

### Describe the proposed solution

While using d3 package, there are annoying warnings coming from `rollup` like:
```text
> Using @sveltejs/adapter-node
Circular dependency: node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/index.js -> node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/select.js -> node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/index.js
Circular dependency: node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/index.js -> node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/selectAll.js -> node_modules/.pnpm/d3-selection@3.0.0/node_modules/d3-selection/src/selection/index.js
```

`adapter-node` calls `rollup` without ability to pass custom `onwarn` handler at https://github.com/sveltejs/kit/blob/master/packages/adapter-node/index.js#L51

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
As an alternative, you could move d3 to `dependencies` (rather than `devDependencies`) so that it doesn't get bundled by Rollup

**Comment by vfilatov** [comment]
> As an alternative, you could move d3 to `dependencies` (rather than `devDependencies`) so that it doesn't get bundled by Rollup

Yes, this works for my particular case!

PS. There still could be other cases...

**Comment by Rich-Harris** [comment]
The advice will always be the same though — move it out of `devDependencies`. We cover this in the `adapter-node` [docs](https://kit.svelte.dev/docs/adapter-node#deploying):

<img width="917" alt="image" src="https://user-images.githubusercontent.com/1162160/219815087-60ae8674-d9c6-4525-ab70-84d3819273e8.png">

Given that, I'm not sure there's much reason to pass options to Rollup rather than bypass it altogether.

**Comment by Rich-Harris** [comment]
Going to close this as I don't think there's anything we should change here

**Comment by cmjoseph07** [comment]
@Rich-Harris 

Is it possible to reconsider this issue or would you be willing to accept a PR on this? I have various deps that are not in my package.json but are causing me circular deps. Example I do not have zod-to-json-schema but have superform within my project causes these to show up.

<img width="1383" alt="Image" src="https://github.com/user-attachments/assets/51960d0d-a47b-4866-aab5-471ab7fc0874" />


I have to write a script to patch adapter-node to keep this consistent on updates and that feels kinda meh.

**Comment by ciscoheat** [comment]
The new `zod4` adapter for Superforms uses its own JSON Schema generator, so if you can upgrade, that should fix this one at least.

https://superforms.rocks/get-started/zod4

**Comment by cmjoseph07** [comment]
@ciscoheat 

I will look into updating this and checking. It seems like a chill update to v4 so just give me a day or so :)

**Comment by cmjoseph07** [comment]
@ciscoheat 

You were 100% right and a very easy update on a pretty big prod app. Still would like to be able to pass things to the adapter though as some people might use libs that aren't maintained or can't currently fix this problem.
