### ISSUE TITLE
 Cannot find package '@sveltejs/kit' Vercel

### ISSUE THREAD

**Issue by ethanfox** [sveltejs/kit#9083]
### Describe the bug

Cant deploy Sveltkit app to Vercel. It shouldn't be this hard.

### Reproduction

idk

### Logs

```Shell
[GET] /
20:40:01:43
2023-02-17T02:40:01.482Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@sveltejs/kit' imported from /var/task/Users/ethanfox/Code/material-space/.svelte-kit/vercel-tmp/index.js
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
RequestId: f6010fbd-8d56-484c-9eac-8a33a8184c04 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 39.34 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Safari: 16.2
  npmPackages:
    svelte: ^3.54.0 => 3.55.1
```

### Severity

annoyance

###       svelte.config.js
        import adapter from '@sveltejs/adapter-vercel';
        import { vitePreprocess } from '@sveltejs/kit/vite';
        
        /** @type {import('@sveltejs/kit').Config} */
        const config = {
	        // Consult https://kit.svelte.dev/docs/integrations#preprocessors
	        // for more information about preprocessors
	        preprocess: vitePreprocess(),
        
	        kit: {
		        adapter: adapter()
	        }
        };
        
        export default config;

### package.json
        
        {
	        "name": "material-space",
	        "version": "0.0.1",
	        "private": true,
	        "scripts": {
		        "dev": "vite dev",
		        "build": "vite build",
		        "preview": "vite preview",
		        "test": "playwright test",
		        "check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json",
		        "check:watch": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --watch",
		        "test:unit": "vitest",
		        "lint": "prettier --plugin-search-dir . --check . && eslint .",
		        "format": "prettier --plugin-search-dir . --write ."
	        },
	        "devDependencies": {
		        "@playwright/test": "^1.28.1",
		        "@sveltejs/adapter-auto": "^1.0.0-next.83",
		        "@sveltejs/adapter-node": "^1.2.0",
		        "@sveltejs/adapter-vercel": "^2.0.2",
		        "@sveltejs/kit": "^1.5.0",
		        "@tailwindcss/forms": "^0.5.3",
		        "@typescript-eslint/eslint-plugin": "^5.45.0",
		        "@typescript-eslint/parser": "^5.45.0",
		        "autoprefixer": "^10.4.13",
		        "eslint": "^8.28.0",
		        "eslint-config-prettier": "^8.5.0",
		        "eslint-plugin-svelte3": "^4.0.0",
		        "postcss": "^8.4.21",
		        "prettier": "^2.8.0",
		        "prettier-plugin-svelte": "^2.8.1",
		        "svelte": "^3.54.0",
		        "svelte-check": "^3.0.1",
		        "svelte-headless-table": "^0.17.2",
		        "tailwindcss": "^3.2.6",
		        "tslib": "^2.4.1",
		        "typescript": "^4.9.3",
		        "vite": "^4.0.0",
		        "vitest": "^0.25.3"
	        },
	        "type": "module",
	        "dependencies": {
		        "@supabase/auth-helpers-sveltekit": "^0.8.7",
		        "@supabase/supabase-js": "^2.7.1",
		        "node-fetch": "^2.6.9"
	        }
        }

**Comment by Conduitry** [comment]
"idk" isn't a valid reproduction either.
