### ISSUE TITLE
Environment variables special character ($) issue

### ISSUE THREAD

**Issue by shanestreator** [sveltejs/kit#9092]
### Describe the bug

Any ideas of a workaround without removing `$`?

Environment Variable: `DB_PASS`

.env file
`DB_PASS = *^$php&!Bz`

from '$env/static/private'
`DB_PASS = *^&!Bz`

Seemingly culprit character
`$`

env file
![env file](https://user-images.githubusercontent.com/35476261/219708600-aac0578d-8559-427c-b38c-0112a09c878f.png)

env console log
![env log](https://user-images.githubusercontent.com/35476261/219708602-8277724d-ccc2-435e-ad15-767e97f33aa2.png)

### Reproduction

Repo
https://github.com/shanestreator/svelte-env-issue

Files of concern
`.env`
`src/routes/+page.server.ts`

### System Info

```Shell
System:
    OS: macOS 12.6.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 373.20 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.2.0 - ~/.nvm/versions/node/v19.2.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v19.2.0/bin/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 109.0.5414.119
    Firefox: 97.0.1
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.7.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.2
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Apparently something is attempting to interpolate shell variables in `.env`. I'm not sure what the intended behavior is without quotes, but if the value is enclosed in single quotes, I would certainly expect it not to be interpolated like that. I suspect this is an upstream issue in Vite. I don't think SvelteKit does any handling of `.env` files itself. Can you see whether this is present in a minimal Vite project without SvelteKIt?

**Comment by wwwdepot** [comment]
Not an issue, it's a feature.

> Vite uses [dotenv-expand](https://github.com/motdotla/dotenv-expand) to expand variables out of the box.

> Note that if you want to use $ inside your environment value, you have to escape it with `\`.

https://vitejs.dev/guide/env-and-mode.html#env-files

**Comment by shanestreator** [comment]
Ah, very cool, that worked! Thank you both for the quick response.
