### ISSUE TITLE
asset list is not returned correctly when building

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#9093]
### Describe the bug

https://github.com/sveltejs/kit/pull/9073 causes `builder.writeClient` to return an array of characters instead of the assets paths.

### Reproduction

https://github.com/s3812497/sveltekit-write-client-bug

1. Run `pnpm i && pnpm build`.
2. Inspect the `.svelte-kit/cloudflare/_routes.json` file.
3. The `exclude` values include several different characters instead of asset files.

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 540.63 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Chrome Canary: 112.0.5600.0
    Firefox: 109.0.1
    Firefox Developer Edition: 110.0
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @sveltejs/adapter-cloudflare: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^1.7.1 => 1.7.1 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.1.2 => 4.1.2
```

### Severity

serious, but I can work around it

### Additional Information

See the workaround here https://github.com/sveltejs/kit/issues/9093#issuecomment-1435042170

**Comment by hauerm** [comment]
Hello @s3812497,

I support this request. How did you work arround this issue?

regards
