### ISSUE TITLE
External JS not loaded blocking in <svelte:head> on client-side nav

### ISSUE THREAD

**Issue by Glench** [sveltejs/kit#9096]
### Describe the bug

During SSR, putting an external script in `<svelte:head>`...

```svelte
<svelte:head>
    <script src="https://js.stripe.com/v3/"></script>
</svelte:head>
```

...then calling it in onMount...

```svelte
import {onMount} from 'svelte';

let message = '...'
    onMount(() => {
        if (Stripe) {
           message = 'Stripe() is available!' 
        }
})
```

...works great. However, when you use client-side nav and open the page, the `Stripe` object isn't available during `onMount`.

Is this intended behavior? I'd expect that blocking JS scripts in <head> should work the same in SSR and client-side nav.

### Reproduction

[Here's a minimal repo showcasing this behavior with some instructions](https://github.com/Glench/head-js-sveltekit-minimal-example).

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 73.29 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 90.1.24.82
    Chrome: 109.0.5414.119
    Edge: 110.0.1587.49
    Firefox: 108.0.2
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.7.1
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.2
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
This isn't intended, but it is expected — when you create a `<script>` element programmatically (which is what's happening during client-side navigation), it's not possible for it to block anything else. This isn't a SvelteKit thing, it's just how browsers work.

If there's no module version of the SDK, you'll need to do something like this:

```js
onMount(() => {
  const script = document.createElement('script');
  script.onload = () => {
    if (Stripe) {
      message = 'Stripe() is available!' 
    }
  };
  script.src = 'https://js.stripe.com/v3/';
  document.head.appendChild(script);
});

**Comment by Glench** [comment]
Thanks for your clarification and a potential fix! That's a very kind thing to provide.

It's still a little weird to me that SSR and client-side nav would act differently, though (even though I know this is how script tags work under the hood). It feels like this is a ripe area for unintended bugs — I wouldn't have expected this except I accidentally clicked around and found my payment page broken :/ Would have been very bad if that made it to production. Hopefully others don't run into it or have my same expectations! :)

**Comment by Glench** [comment]
Oh and thank you so much for SvelteKit! This is the web framework I've been dreaming of since 2010.

**Comment by msfninja** [comment]
> This isn't intended, but it is expected — when you create a `<script>` element programmatically (which is what's happening during client-side navigation), it's not possible for it to block anything else. This isn't a SvelteKit thing, it's just how browsers work.
> 
> If there's no module version of the SDK, you'll need to do something like this:
> 
> ```js
> onMount(() => {
>   const script = document.createElement('script');
>   script.onload = () => {
>     if (Stripe) {
>       message = 'Stripe() is available!' 
>     }
>   };
>   script.src = 'https://js.stripe.com/v3/';
>   document.head.appendChild(script);
> });
> ```

For future visitors, there is a module version of the Stripe.js SDK:

https://stripe.com/docs/libraries/stripejs-esmodule
