### ISSUE TITLE
Error running `svelte-package`

### ISSUE THREAD

**Issue by brucejo75** [sveltejs/kit#9097]
### Describe the bug

From: https://github.com/sveltejs/kit/pull/8922#issuecomment-1434927519

`svelte-package` throwing a misleading error on misconfigured `package.json`

The error advises me to add a `svelte` condition to my `exports`.  I had one.  I really needed to add a `svelte` condition at the top level.

### Reproduction

```
# Create the project and choose `Skeleton project` (which is what many of the online tutorials do)
$ pnpm create svelte error
$ cd error
$ pnpm install
$ pnpm add svelte2tsx @sveltejs/package
$ pnpm add -P svelte
$ mkdir src/lib
$ echo -e "<h1>Error</h1>\n" > lib/src/ErrComponent.svelte
```

add `"exports"` key to `package.json`
```
"exports": {
    ".": {
      "types": "./dist/ErrComponent.d.ts",
      "svelte": "./dist/ErrComponent.js"
    }
},
```

Run `svelte-package`
```
$ pnpm svelte-package
src/lib -> dist
@sveltejs/package found the following issues while packaging your library:
You are using Svelte files, but did not declare a `svelte` condition in one of your `exports` in your `package.json`. Add a `svelte` condition to your `exports` to ensure that your package is recognized as Svelte package by tooling. See https://kit.svelte.dev/docs/packaging#anatomy-of-a-package-json-exports for more info
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (1) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
    Memory: 201.78 MB / 904.09 MB
    Container: Yes
    Shell: 5.1.16 - /usr/bin/bash
  Binaries:
    Node: 18.14.0 - ~/.local/share/pnpm/node
    npm: 9.3.1 - ~/.local/share/pnpm/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.7.1
    @sveltejs/package: ^2.0.1 => 2.0.1
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.0.0 => 4.1.2
```

### Severity

annoyance

### Additional Information

- if you `pnpm create svelte` & choose library then `package.json` adds 2 keys that are important:
```
"svelte": "./dist/index.js",
"types": "./dist/index.d.ts",
```

The error is misleading, I had a `svelte` condition in my `exports`.  I really needed a `svelte` condition at the top level.

**Comment by FractalHQ** [comment]
Technically, it makes sense that this:
> Add a `svelte` condition to your `exports`

Would mean `exports.svelte`.  Though I can also see how this could be further clarified.

**Comment by dominikg** [comment]
I don't think we should force people to put svelte in the top level of exports map.

Alternative solution would be to also search subkeys and not print the message when it was found there

**Comment by seanlail** [comment]
I had the same issue and eventually figured out that it was on the root. 

My project was created with an older version that set Svelte to index.js... but to appease the packager I had to change it. 

Not sure why this is needed?

Before:
'''
"svelte": "index.js"
'''

After:

'''
"svelte": "./package/index.js"
'''

Maybe the fix should be to automatically update this in the migration script and make the warning clearer?

**Comment by seanlail** [comment]
Oh, a note on this: This error (for me at least) was because of the root "svelte", not a missing one in exports.
