### ISSUE TITLE
Snapshots are saved when tab becomes hidden, not when it is unloaded

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#9098]
### Describe the bug

The data for snapshots is currently saved when the `visibilitychange` event fires and we have `document.visibilityState === 'hidden'`. This isn't quite what we want.

This will fire prematurely if someone switches to another tab in their browser, or minimizes it. There's no need to persist the state yet in these cases.

More seriously: It will fail to fire on Firefox when the user closes the tab. We're not persisting the snapshot data in that case, and if they restore the tab, it will not get the restored data. Interestingly, it _does_ get persisted when refreshing the page in Firefox.

In Chrome, this even appears to also be fired when closing the tab, so we don't see the same issue there.

### Reproduction

None currently, apologies. This should occur with the snapshots example https://kit.svelte.dev/docs/snapshots as-is.

### Logs

```Shell
n/a
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.92 GB / 7.66 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.8.0 - ~/.bin/nodejs/current/bin/node
    Yarn: 1.22.19 - ~/.bin/nodejs/current/bin/yarn
    npm: 8.18.0 - ~/.bin/nodejs/current/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.1.7 => 1.1.7 
    @sveltejs/kit: 1.5.0 => 1.5.0 
    svelte: 3.55.1 => 3.55.1 
    vite: 4.1.1 => 4.1.1
```

### Severity

annoyance

### Additional Information

Is `beforeunload` considered bad form for this? Do we have other options? It would be nice to switch to something that doesn't have the false positives and false negatives of `document.visibilityState`.

**Comment by Rich-Harris** [comment]
IIRC we _do_ need to capture it on `visibilitychange` for the sake of browser tabs on mobile that get backgrounded and later reanimated. I'm not 100% confident on that though. It doesn't preclude us persisting to `sessionStorage` in another event as well — doing so is harmless.

I seem to recall a recommendation against using `beforeunload`, though I don't know if it applies to us here.

**Comment by geoffrich** [comment]
`beforeunload` is recommended against [for bfcache reasons](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event#usage_notes) and is not reliably fired on mobile (per MDN):

> The beforeunload event is not compatible with the [back/forward cache](https://web.dev/bfcache/) (bfcache), because many pages using this event assume that the page will not continue to exist after the event is fired. To combat this, browsers will not place pages in the bfcache if they have beforeunload listeners, and this is bad for performance.

I've seen [pagehide](https://developer.mozilla.org/en-US/docs/Web/API/Window/pagehide_event#usage_notes) recommended as [an alternative to unload](https://web.dev/bfcache/#never-use-the-unload-event) but I'm not sure if it applies in this case or not

**Comment by dummdidumm** [comment]
According to https://web.dev/bfcache/#only-add-beforeunload-listeners-conditionally this only applies to Firefox, Safari/Chrome still enable bfcache when `beforeunload` is present
