### ISSUE TITLE
"Getting Started" instructions incorrect without JS enabled

### ISSUE THREAD

**Issue by McAllaster** [sveltejs/kit#910]
**Describe the bug**

When visiting the [getting started](https://kit.svelte.dev/docs#introduction-getting-started) section in the docs, the instructions for setup are incomplete.

However, the CDN hides `svelte@next` portion of the `npm init` line, producing:

```
mkdir my-app
cd my-app
npm init [email protected]
npm install
npm run dev
```

**To Reproduce**
Visit the link above with JS disabled in a browser of your choice.

**Expected behavior**

Section output shows:

```
mkdir my-app
cd my-app
npm init svelte@next
npm install
npm run dev
```

**Severity**

Not severe at all, to be honest. I just thought this might be something worth knowing/fixing.

**Additional context**

CloudFlare (the CDN in question) has some [documentation](https://support.cloudflare.com/hc/en-us/articles/200170016-What-is-Email-Address-Obfuscation-) on the email obfuscation which is doing this.

**Comment by Rich-Harris** [comment]
closing, as we disabled email obfuscation — thanks
