### ISSUE TITLE
TypeError: Cannot redefine property: Symbol($$jest-matchers-object) during npm run test

### ISSUE THREAD

**Issue by Glench** [sveltejs/kit#9112]
### Describe the bug

During `npm run test` I'm getting the following error with a minimal vitest test:

```
$ npm run test

> sveltekit-tests-error-minimal@0.0.1 test
> playwright test


Running 1 test using 1 worker

TypeError: Cannot redefine property: Symbol($$jest-matchers-object)

    at Function.defineProperty (<anonymous>)
    at file:///Users/glen/tmp/sveltekit-tests-error-minimal/node_modules/vitest/dist/chunk-runtime-chain.f86e5250.js:1112:10


  1 skipped
```

### Reproduction

Here's a minimal reproduction: https://github.com/Glench/sveltekit-tests-error-minimal

Mostly just see test/other.test.ts. This was made with a fresh install just using skeleton project, TS, and saying yes to all the extras.

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 36.58 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 90.1.24.82
    Chrome: 109.0.5414.119
    Edge: 110.0.1587.50
    Firefox: 108.0.2
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.7.2
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.2
```

### Severity

serious, but I can work around it

**Comment by Glench** [comment]
Oh, just realized that this is because vitest unit tests are supposed to be in the `src` directory and are run with `npm run test:unit` whereas playwright end-to-end tests are run with `npm run test`.

**Comment by harapeko** [comment]
I noticed the lack of my setup in your tips.

```diff
import type { PlaywrightTestConfig } from '@playwright/test';

export default {
	webServer: {
		command: `vite dev --port 3005`,
		port: 3005
	},
+	testDir: 'tests'
} satisfies PlaywrightTestConfig;

```

**Comment by bijiasuo2006** [comment]
I just clone your code from github https://github.com/Glench/sveltekit-tests-error-minimal

When I run the test command, still has the same error you posted before, any suggestion about it?

**Comment by slhck** [comment]
More specifically, make sure that when you have both `vitest` and `playwright` in your project, `playwright` looks for tests in a directory that does not contain any `vitest` tests.

Set `testDir` in Playwright's config to a directory that houses Playwright tests exclusively.
