### ISSUE TITLE
Project builds but fails on deploy

### ISSUE THREAD

**Issue by charbelnicolas** [sveltejs/kit#9141]
### Describe the bug

Today I updated my project with an NPM Update and it no longer works correctly. This is what my package.json look like:

![20230220_151727](https://user-images.githubusercontent.com/14960414/220191687-4686f37c-e39d-4261-a3b4-574a575cc941.png)

The project builds succesfully:
![20230220_151653](https://user-images.githubusercontent.com/14960414/220191700-b80e9b07-cb13-4a17-a61c-136af5802cc6.png)

And this is what happens when it gets deployed:

![20230220_151833](https://user-images.githubusercontent.com/14960414/220191795-d30f1807-109d-4b42-93d2-d0c7e7a25056.png)

[Click here to see the issue for yourself](https://charbelnicolas.com/pockets)

### Reproduction

I could not reproduce this issue with a clean svelte-kit install. It is mostly a bug based on my project I guess... but this only happened after doing an NPM update today.

### System Info

```Shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 29.83 GB / 31.30 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.6.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 110.0.5481.100
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
Hm. @Rich-Harris @dummdidumm Do we need to rethink using `.mjs` files if they're unlikely to get the appropriate `Content-Type` headers served in various static servers? Or at least document the configuration changes that are needed? It looks like this particular site is using nginx.

**Comment by charbelnicolas** [comment]
> Hm. @Rich-Harris @dummdidumm Do we need to rethink using `.mjs` files if they're unlikely to get the appropriate `Content-Type` headers served in various static servers? Or at least document the configuration changes that are needed? It looks like this particular site is using nginx.

Yep, I'm using Nginx :)

**Comment by Conduitry** [comment]
In the meantime, you should be able to configure nginx to return the appropriate `Content-Type: application/javascript` header for `.mjs` files.

**Comment by charbelnicolas** [comment]
> In the meantime, you should be able to configure nginx to return the appropriate `Content-Type: application/javascript` header for `.mjs` files.

Thank you, I'll see what I can do.

**Comment by charbelnicolas** [comment]
I changed the mime.types file on the server and it works now, thank you!

I still get this message though:

![20230220_160301](https://user-images.githubusercontent.com/14960414/220198085-afbe04ba-7056-4749-9a03-d7ced17d5e9e.png)

Any idea of why that is?

**Comment by dummdidumm** [comment]
Any chance you're using Firefox? The preload optimazation doesn't work there and you instead get a warning like this

**Comment by Rich-Harris** [comment]
The screenshot looks like Chrome. I'm actually seeing the same thing on kit.svelte.dev, bizarrely:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/1162160/220205522-aa61550b-947a-41c0-85a9-6090585c7133.png">

There's definitely a bug here. Perhaps those modules really aren't being imported, though I don't understand why they'd be in the preload list otherwise

**Comment by charbelnicolas** [comment]
I

> Any chance you're using Firefox? The preload optimazation doesn't work there and you instead get a warning like this

I'm using latest chrome

**Comment by tony19** [comment]
I'm also seeing this problem but with `text/plain`:

> start.93eb02de.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
> app.1f02cb34.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

* Chrome Version 109.0.5414.119
* macOS Ventura
* nginx

I tried the fix in https://github.com/sveltejs/kit/pull/9142, but that seemed to have no effect. I had to revert to SvelteKit v1.5.0 for now.

**Comment by Conduitry** [comment]
#9142 is unrelated to this issue.

**Comment by Rich-Harris** [comment]
@tony19 is that an error you can reproduce or is it something in your logs? if the latter, it's probably because someone tried to load that file after a redeploy happened while they were on the site. it's generally harmless as the client will detect a new version and automatically reload

**Comment by tony19** [comment]
@Rich-Harris It's the former... reproducible just by visiting the site. I'll try to create an isolated reproduction if needed.

**Comment by Rich-Harris** [comment]
@tony19 yes please — it sounds like a separate issue though, so please open a new ticket

**Comment by rob-balfre** [comment]
This has broken our SPA builds too... we have the worst CDN on Azure and it doesn't know let us serve .mjs files. 

This a deliberate change to force us over to Vercel 😂 ??

**Comment by wickning1** [comment]
I also found that the precompress option fails after the switch to mjs, likely because of this glob https://github.com/sveltejs/kit/blob/b3c31a15eb245e58a7adf7187f39e9a21dc592ac/packages/kit/src/core/adapt/builder.js#L85

**Comment by polyzen** [comment]
Relevant: https://pagure.io/mailcap/pull-request/10

On Arch Linux (and other distros perhaps), nginx pulls in mailcap for mime.types use by default.
