### ISSUE TITLE
Using `depends` with colon and certain words throws unhandled error in Firefox

### ISSUE THREAD

**Issue by khromov** [sveltejs/kit#9159]
### Describe the bug

Admittedly an odd bug, i noticed that the below code inside a `+page.ts` file reliably breaks on Firefox:

### Reproduction

```ts
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ fetch, url, depends }) => {
    const response = await (await fetch('https://jsonplaceholder.typicode.com/todos/1')).json();

	depends('jar:messages');

	return response;
};
```

### Logs

In Chrome and Safari it works, but Firefox throws:

```
TypeError: URL constructor: jar:messages is not a valid URL.
    depends client.js:589
    load +page.ts:6
    load_node client.js:670
...
```

I believe `jar` is some sort of special protocol identifier in Firefox, perhaps relating to Java jars. I suspect that there are other "magic" words on the protocol list that might break when used in a `depends` key together with a colon.

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: -
    Memory: -
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
  Browsers:
    Firefox: 110
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.8.3 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Peculiar indeed.

My gut feeling here is that we shouldn't do anything weird to try to make this work - but rather try to figure out what all of the special protocols are (any help in where to look for that would be appreciated) and then throw a more informative error in all browsers in dev mode when you try to use one of these.

**Comment by msonnberger** [comment]
Did some digging and I found the place where the schema handling happens in Mozilla's codebase:

https://searchfox.org/mozilla-central/rev/234ae43d3793289167926ef91bfb5145da91d4aa/netwerk/base/nsNetUtil.cpp#1814

Out of the special schemas handled there, `moz-icon`, `view-source` and `jar` throw the above error (when tested with `new URL("schema:foo")`, while some others don't throw but have some other special handling, most notably adding slashes like with `http://` to the href. I don't know how SvelteKit uses the URL object for `depends`, but maybe we should warn in these cases too.

Also, while there is and [IANA list](http://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml) for URI schemas (which contains a lot more), I'm afraid it's highly browser dependent which schemas are handled with which special rules.

**Comment by dummdidumm** [comment]
A PR which at dev time checks for moz-icon, view-source and jar as protocol schemes and logs a warning would be appreciated. For v2 we could make this an error.
