### ISSUE TITLE
Add __mocks__ folder to tsconfig

### ISSUE THREAD

**Issue by seanlail** [sveltejs/kit#9181]
### Describe the problem

A `__mocks__` folder needs to be added to the root of your project in order to mock external modules with Vitest.

Quote from a vitest maintainer:
> For external libraries we use `root/__mocks__` folder. For internal, you need to have `__mocks__` folder inside the folder where the file is located.

This path needs to be added to the tsconfig that SvelteKit generates, as the "includes" is hidden away from the user.

I can obviously do this manually in my project but it could break due to unknown future changes.

### Describe the proposed solution

Add the `__mocks__` path to the includes list in the tsconfig that SvelteKit generates at `./.svelte-kit/tsconfig.json`

### Alternatives considered

A possible alternative would be to somehow expose the include / exclude setup so that we can extend it safely.

Looks like making the test folder configurable was an idea too: https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/sync/write_tsconfig.js#L106
(for example, I like to use `__tests__`)

### Importance

nice to have

**Comment by gtm-nayan** [comment]
> A possible alternative would be to somehow expose the include / exclude setup so that we can extend it safely.

Kinda like https://kit.svelte.dev/docs/configuration#typescript ?

**Comment by seanlail** [comment]
> > A possible alternative would be to somehow expose the include / exclude setup so that we can extend it safely.
> 
> Kinda like https://kit.svelte.dev/docs/configuration#typescript ?

Amazing! I can't believe I missed it. Thank you @gtm-nayan
