### ISSUE TITLE
Jagged scroll behaviour on navigation

### ISSUE THREAD

**Issue by Coretteket** [sveltejs/kit#9189]
### Describe the bug

SvelteKit's client-side navigation seems to introduce jagged scroll behaviour, where the scroll position of the previous page is kept for a very short period of time, before it correctly scrolls to the top. This is demonstrated in the video below of [kit.svelte.dev](https://kit.svelte.dev/docs), which was recorded in Firefox, although the same behaviour occurs (for me) on Chrome. The same is occurring in my own SvelteKit apps, and also in the simple reproduction linked below. Do note that is does not always occur, although I have not been able to find a pattern.

It may be related to #2733, although it is a separate problem: the page scroll position *is* always reset to top, but not quickly enough. My apologies if this has been addressed before, or if it is simply a limitation of CSR, as it's my first issue opened here. 

**Example:**

https://user-images.githubusercontent.com/33397397/221026050-d409cfd5-65ad-4a29-a19a-742055415bf1.mp4

### Reproduction

Nothing complicated here, just two scrollable pages.
https://github.com/Coretteket/jagged-scroll-repro

### System Info

```Shell
System:
    OS: Windows 11 10.0.22623
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Memory: 1000.01 MB / 7.39 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1325.0), Chromium (110.0.1587.46), ChromiumDev (111.0.1660.13)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-vercel: ^2.1.0 => 2.1.0
    @sveltejs/kit: ^1.8.3 => 1.8.3
    svelte: ^3.55.1 => 3.55.1
    vite: ^4.1.4 => 4.1.4
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
Man, once you see it you really can't unsee it 😭 Luckily the solution is fairly straightforward — #9311

**Comment by Coretteket** [comment]
Thanks a ton for this fix, lovely to be able to unsee this now! 😊
