### ISSUE TITLE
User-defined "unhandledRejection" and "uncaughtException" handler

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/kit#9194]
### Describe the problem

Errors or rejections thrown inside endpoints and load functions on the server are catched by sveltekit. Then Sveltekit does some processing but does not apply any custom handler.

Because the catch happens in the implementation of resolve, global.process.on("uncaughtException") and global.process.on("unhandledRejection") handlers are ignored.

### Describe the proposed solution

Because there can also be exceptions in the handle itself, I propose to add two functions that can be exported from server hooks which correspond to user defined exception and rejection handlers and are applied to the error catched by sveltekit after sveltekit did its own processing of these errors. 

In the most ideal situation, the global.process.on listeners that have been defined before sveltekit starts running should be inherited and applied after preprocessing of the errors by sveltekit. In this way, sveltekit's behaviour does not alter the expected behaviour of the surrounding node process, which is catching what should be catched with any pre-configured logger.

### Alternatives considered

- Do nothing and let the exceptions go without logging them with a custom logging framework. Not an option, since the data seems to be useful to take further action, like for example sending email notifications.
- Not throwing anything unexpected at all. Not possible, since there will always be unexpected exceptions and rejections.

### Importance

would make my life easier

### Additional Information

After reading through the source code, the function implementations should be added somewhere inside the following call stack 

```
Error
    at Module.coalesce_to_error (/node_modules/.pnpm/@sveltejs+kit@1.5.3_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/utils/error.js:11:5)
    at Module.handle_fatal_error (/node_modules/.pnpm/@sveltejs+kit@1.5.3_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/utils.js:73:46)
    at resolve (/node_modules/.pnpm/@sveltejs+kit@1.5.3_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/respond.js:413:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handle (/home/.../routes/hooks.server.ts:44:18)
    at async Module.respond (/node_modules/.pnpm/@sveltejs+kit@1.5.3_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/runtime/server/respond.js:234:20)
    at async file:///home/.../node_modules/.pnpm/@sveltejs+kit@1.5.3_svelte@3.55.1+vite@4.1.1/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:495:22
```
Probably in the respond or handle function.

**Comment by dummdidumm** [comment]
What do you mean by "does not process any custom handler"? There's [handleError](https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror) which applies to any unexpected errors in endpoints/load functions.
`process.on('..')` sounds node specific and isn't available on all platforms, you can [add a callback to it yourself](https://kit.svelte.dev/docs/adapter-node#custom-server) if you're using the node adapter.

**Comment by wvhulle** [comment]
Hi sorry for the spam. I hadn't seen that the handle error also works in server hooks.
