### ISSUE TITLE
Service worker have a scope fixed at build time

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#922]
**Describe the bug**
this line https://github.com/sveltejs/kit/blob/ccb8825fd97d7f23ee961b30077e1a2bf1a53b42/packages/kit/src/runtime/client/start.js#L53

will always register the service worker on a fixed url, which prevent it to be used on arbitrary sub folder, a requirement for ipfs webiste.

**Expected behavior**

svelte kit should allow us to provide a mechanism to define the registration behavior, including the service worker url at runtime

While it is possible to create the service worker separatly from svelte kit and then register it manually, this lose the benefit of the `$service-worker` modules.

One solution would be to separate the 2 : one option to generate the service worker and another option to decide whether to use the builtin service worker registration

This way I can still build my service worker with the benefit of the `$server-worker` module and register as I wish

**Comment by benmccann** [comment]
It looks like this code changed in https://github.com/sveltejs/kit/pull/1724 though still doesn't work the way you're suggesting you'd like it to

**Comment by benmccann** [comment]
@wighawag you may want to take a look at https://github.com/sveltejs/kit/pull/2281 which would add an option to disable the existing service worker registration so that you can add your own, which would fix this

**Comment by benmccann** [comment]
https://github.com/sveltejs/kit/pull/2988 has been merged which adds an option to disable the existing service worker registration, so I think you could now add your own to address this and I'll go ahead and close this. Let me know if there's something that would still be required

**Comment by wighawag** [comment]
@benmccann great! that should indeed be sufficient for my use case

But note that ideally svelte-kit should support dynamic basepath and so the default service-worker registration should support such case, see : https://github.com/sveltejs/kit/issues/595
