### ISSUE TITLE
The `version_hash` changes too often

### ISSUE THREAD

**Issue by bfanger** [sveltejs/kit#9225]
### Describe the bug

This causes errors in development and during redeployments:
```
Uncaught (in promise) ReferenceError: __sveltekit_${hash} is not defined
    at paths:2:23
```
where `${hash}` is different every time. `paths` refers to `http://localhost:5173/@id/__x00____sveltekit/paths`

Every time you run a `vite build` you'll get a different output bundle, which can result in unnecessary breakage during deployments.

### Reproduction

Start a dev server and while the dev server is running, execute a `vitest run` (or a `npx vite build`).

`[vite] page reload .svelte-kit/generated/server/internal.js`

Now the server and client are out of sync and the dev server is broken.

### Logs

```Shell
[vite] connecting...
Uncaught (in promise) ReferenceError: __sveltekit_i2dure is not defined
    at paths:2:23
[vite] connected.
```

### System Info

```Shell
System:
    OS: macOS 11.7.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 2.05 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Chrome Canary: 113.0.5620.0
    Firefox: 110.0
    Safari: 16.3.1
  npmPackages:
    @sveltejs/adapter-static: ^2.0.1 => 2.0.1 
    @sveltejs/kit: ^1.8.5 => 1.8.5 
    @sveltejs/package: ^2.0.2 => 2.0.2 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.1.4 => 4.1.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Could you clarify how this causes breakage during redeployments?

**Comment by Rich-Harris** [comment]
Ah yep, the `paths` module is being reloaded but the page isn't, so there's a mismatch. One thing we could potentially do is omit the hash in development.

I'm also not seeing how this could cause errors during redeployments?

**Comment by bfanger** [comment]
Triggering a re-deploy where the pipeline **builds and deploys** a specific commit, the output will be different for every run.
Maybe this doesn't impact site stability but it feels flacky.

My theory is that when using a CDN the end-user can have cache-hit and get outdated html file, but if the outdated javascript file can already be flushed and they get an error on the javascript import.

But this is normal behavior for a regular deployment, so:
- stable dev server: should-have
-  idempotent builds: nice-to-have

**Comment by dummdidumm** [comment]
- stable dev server -> agree
- idempotent builds -> with regards to the hash, this is controllable through the [version](https://kit.svelte.dev/docs/configuration#version) option

**Comment by Rich-Harris** [comment]
If the user gets an out-of-date HTML response because of `cache-control` headers, it will point to equally out-of-date build artifacts — since they're cached immutably, the app _should_ continue to work. (Of course it's conceivable that a CDN will somehow have cached the HTML but not the assets — generally I think it's best [not to cache HTML](https://jakearchibald.com/2016/caching-best-practices/), though sometimes it's necessary).

Perhaps we should do a better job of documenting this pattern:

```js
// svelte.config.js
import { execSync } from 'node:child_process';

export default {
  kit: {
    version: {
      name: execSync('git rev-parse HEAD').toString().trim()
    }
  }
};
```
