### ISSUE TITLE
Redirect in hooks.servers.ts throw an Error

### ISSUE THREAD

**Issue by yb-leakmited** [sveltejs/kit#9234]
### Describe the bug

Calling throw redirect(code, path) throws an Error in preview and production (on Vercel). It works fine in dev.
Seems related to : https://github.com/sveltejs/kit/issues/8617 and https://github.com/sveltejs/kit/pull/8690

App created today with npm `create svelte@latest`

### Reproduction

Reproduction repository : 
https://github.com/yb-leakmited/svelkit-redirect-error

### Logs

```Shell
Error: {"status":303,"location":"/sign-in"}
    at coalesce_to_error (file:///C:/Users/Leakmited_IT_02/workspace/my-app/.svelte-kit/output/server/index.js:125:7)
    at handle_fatal_error (file:///C:/Users/Leakmited_IT_02/workspace/my-app/.svelte-kit/output/server/index.js:160:51)
    at respond (file:///C:/Users/Leakmited_IT_02/workspace/my-app/.svelte-kit/output/server/index.js:2630:18)
    at async file:///C:/Users/Leakmited_IT_02/workspace/my-app/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:146:5
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 3.53 GB / 15.41 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.8.6
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.4
```

### Severity

blocking an upgrade

**Comment by StephenGunn** [comment]
I have the same issue but my redirect works fine in dev but breaks on Netlify.

```
ERROR  Error: {"status":302,"location":"https://angieblomdigitaldesigns.com"}
    at coalesce_to_error (file:///var/task/.netlify/server/index.js:125:7)
    at handle_fatal_error (file:///var/task/.netlify/server/index.js:160:51)
    at resolve (file:///var/task/.netlify/server/index.js:3088:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handle (file:///var/task/.netlify/server/chunks/hooks.server.js:122:23)
    at async respond (file:///var/task/.netlify/server/index.js:2952:22)
    at async Runtime.handler (file:///var/task/.netlify/serverless.js:270:20)
```

is the log from the render function on Netlify

**Comment by AlanAcDz** [comment]
Can confirm redirect also breaks in Vercel with the most recent version of SvelteKit. Although the logs I get there are not really helpful, probably cause I'm redirecting from a form action.

<img width="1215" alt="Captura de pantalla 2023-02-27 a la(s) 19 22 51" src="https://user-images.githubusercontent.com/20191823/221728192-264f218f-920e-45e5-b967-8ad201423a25.png">

This just renders my closest error boundary (+error.svelte) with a 500 internal error.
I have been testing and it works fine while running in dev mode but breaks in production even if I do a local build and preview it. Also, if I change my form action for an API route and do the redirect there, it shows the same log as the one that is getting @StephenGunn

**Comment by AlanAcDz** [comment]
Update: I just downgraded to version 1.7.2 and it is working fine on Vercel. I was still getting the error building and previewing locally though, even if I deleted the .svelte-kit folder after downgrading

**Comment by mrmcc3** [comment]
I've also run into this issue or something similar when deploying to vercel. Some more details which might help

- Works in dev
- I can reproduce by throwing a redirect from an action (not in hooks.server.ts)
- Downgrading to 1.8.5 works. Seems to indicate issue was introduced in 1.8.6
  perhaps something to do with external/noExternal stuff

**Comment by jycouet** [comment]
I confirm that the issue is still present in `1.8.7`
From my prod on `render` 👇
```
Feb 28 09:36:39 AM  Error: {"status":302,"location":"/app"}
Feb 28 09:36:39 AM      at coalesce_to_error (file:///opt/render/project/src/apps/capa/.svelte-kit/output/server/index.js:123:7)
Feb 28 09:36:39 AM      at handle_fatal_error (file:///opt/render/project/src/apps/capa/.svelte-kit/output/server/index.js:158:51)
Feb 28 09:36:39 AM      at respond (file:///opt/render/project/src/apps/capa/.svelte-kit/output/server/index.js:3180:18)
Feb 28 09:36:39 AM      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Feb 28 09:36:39 AM      at async file:///opt/render/project/src/node_modules/.pnpm/@sveltejs+kit@1.8.7_svelte@3.55.1+vite@4.1.4/node_modules/@sveltejs/kit/src/exports/vite/preview/index.js:146:5
```

Downgrading to 1.8.5 works.

**Comment by christophsturm** [comment]
I wonder if a fix for an issue like this shouldn't also contain a playwright test. I think a good rule of thumb is that everything that produced a bug in a release warrants a test case. (but maybe thats just because I'm a bit of a tdd fan).

**Comment by jycouet** [comment]
Thx @dummdidumm for the quick fix

@christophsturm, I'm pretty sure you can add a test ^_~

**Comment by christophsturm** [comment]
> @christophsturm, I'm pretty sure you can add a test ^_~

actually in my codebase i had a test that broke, but I do not know sveltekit internals well enough to find out why, and I thought its probably something stupid on my end because why would something so basic not work.

**Comment by dummdidumm** [comment]
The test suite probably didn't catch it because the condition which added `@sveltejs/kit` to `noExternal` was true in that case.

We have some plans around more general e2e tests including adapters, in which we can also test this.

**Comment by sense-then-love** [comment]
On 1.8.6 and 1.8.7 I got page errors if the page did a throw, on 1.8.8 getting page errors just navigating to pages, 1.8.5 works good
