### ISSUE TITLE
full page reload every server update, HMR, vite

### ISSUE THREAD

**Issue by vqt123** [sveltejs/kit#9241]
### Describe the problem

Vite aggressively reloads the entire app every time there's a server change. API change? Reload. +page.server change? Reload. 

Trying to test a big form for instance that constantly resets form values every time you save the action feels so bad.

Rich has this issue open https://github.com/vitejs/vite/issues/7887

but the DX right now because of this is so bad that I beg we have a workaround.

### Describe the proposed solution

Coerce someone at vite to address https://github.com/vitejs/vite/issues/7887

or gives us a workaround

### Importance

i cannot use SvelteKit without it

**Comment by vqt123** [comment]
After digging into vite docs and vite forums, i found the vite config options to do this

vite.config.ts

```
export default defineConfig({
	plugins: [sveltekit()],

	server: {
		watch: {
			ignored: ['**.ts']
		}
	}
});
```

this seems to ignore all typescript file changes

**Comment by vqt123** [comment]
Ok, found an acceptable workaround thanks to this vite post from about a year ago.

https://github.com/vitejs/vite/issues/6695

Included this in my +layout.svelte (Or any svelte file you wish to not to full page reload on server changes)

+layout.svelte, or +page.svelte
```
<script>
	if (import.meta.hot) {
		import.meta.hot.on('vite:beforeFullReload', () => {
			throw '(skipping full reload)';
		});
	}
</script>

```

All server file changes still compile however this prevents your front-end from completely reloading.

**Comment by david-plugge** [comment]
You could also call `invalidateAll` to rerun server load functions if that's not already handled by sveltekit

**Comment by amr3k** [comment]
Thanks so much, this really helped me preserving the form state while developing

**Comment by rob-3** [comment]
`// @hmr:keep-all` for whole-component and `// @hmr:keep` from [here](https://github.com/sveltejs/svelte-hmr/tree/master/packages/svelte-hmr#preservation-of-local-state) was good enough for my uses

**Comment by achamas-playco** [comment]
Just add this to your client-side code:

```
if (import.meta.hot) {
   import.meta.hot.accept(() => {
      import.meta.hot!.invalidate();
   });
}
```

It will force a full page reload for every HMR action.
