### ISSUE TITLE
start.js & app.js = Internal Server Error in production b/c Response header content-type is "text/html; charset=UTF-8"

### ISSUE THREAD

**Issue by sense-then-love** [sveltejs/kit#9248]
### Describe the bug

- Locally for app.js & start.js the response header Content-Type is application/javascript
- In production the content type for these 2 files are text/html; charset=UTF-8
- No error in cloudflare wokers terminal but browser errors say

Loading module from “https://sensethenlove.com/_app/immutable/entry/start.59d6b0b2.js” was blocked because of a disallowed MIME type (“text/html”).
Loading module from “https://sensethenlove.com/_app/immutable/entry/app.646327ce.js” was blocked because of a disallowed MIME type (“text/html”).

The browser console errors also include a link to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

Example: https://sensethenlove.com/ + https://github.com/sensethenlove/sensethenlove

### Reproduction

Deploy to cloudflare workers w/ most recent svelte packages

### Logs

```Shell
Loading module from “https://sensethenlove.com/_app/immutable/entry/start.59d6b0b2.js” was blocked because of a disallowed MIME type (“text/html”).
Loading module from “https://sensethenlove.com/_app/immutable/entry/app.646327ce.js” was blocked because of a disallowed MIME type (“text/html”).
```

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 95.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
    Safari: 15.6.1
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.0.6 => 1.0.6 
    @sveltejs/kit: ^1.8.8 => 1.8.8 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.1.4 => 4.1.4
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
Looking at that demo site, the real issue seems to be that these requests are returning 500 errors (which is rendered as an HTML page), not that the correct file is being returned with the wrong MIME type.

The error page instructs the owner of the site to log into the Cloudflare console and check its logs. Do you see anything helpful in there?

**Comment by sense-then-love** [comment]
@Conduitry Now the requests are returning as 200's! Thank you for helping me comprehend the content-type, idk what changed, glitch in the matrix, thank you to all @ Svelte!
