### ISSUE TITLE
defaults in functions in SSR work differently than on client.

### ISSUE THREAD

**Issue by blairn** [sveltejs/kit#925]
```
import * as d3 from 'd3';
export function createScale(scale= d3.scaleLinear()) {

```

it works on the client, but does not work for SSR.  it fails like this.... 
```
d3 is not defined
ReferenceError: d3 is not defined
```

but.... that ONLY happens during ssr, if you go to the page from somewhere else it is good, and it works.

this however DOES work...
```
import * as d3 from 'd3';

export function createScale(scale) {
    scale = scale ?? d3.scaleLinear()
```

and it works for client, AND SSR.

weird huh? went down quite the rabbit hole trying to work out what was going on there.

**Comment by benmccann** [comment]
It'd probably be best to file this over in the Vite repo

**Comment by benmccann** [comment]
That's probably because client is ESM and server is CJS. Libraries should avoid using default exports for this reason. If you can use named exports that will avoid this issue
