### ISSUE TITLE
Support file routing like +customPageName.svelte for better organization

### ISSUE THREAD

**Issue by Trystan-SA** [sveltejs/kit#9253]
### Describe the problem

Having to define routes by folder can sometimes be tedious. For example:

```
src/routes/
   contact/
      +page.svelte
   about-us/
      +page.svelte
   landing-page/
      +page.svelte
   newsletter/
      +page.svelte
   +page.svelte
```
It can be a bit too long to create a structure like this if you have a lot of static pages. And if you need a more complex structure (let's say a `blog`, or a `projects` route with a lot of sub-folders containing some `+page.server.ts` or `+layout.server.ts`) you might not realize what is "complex" and what is only simple pages only by looking at your `src/routes` folder hierarchy. You need to expend a lot of folders before having a sense of what is going on.

This is also the case for API endpoints :
```
src/routes/api/users
   getByID/
      +server.ts
   getByEmail/
      +server.ts
   addFileAttachement/
      +server.ts
   auth/
      login/
         +server.ts
      logout/
         +server.ts
```

Most API can be simplified by using HTTP verbs (`POST`, `GET`, `PUT` ...) But when you want to adapt to an already existing one that is not very well designed (lots of endpoints that use a single verb each) it get very messy.

### Describe the proposed solution

**Allow SvelteKit router to load files with the "+" symbol at the beginning.**

Having to declare `+page.svelte` every time is redundant. We already have the "+" symbol telling us that we are creating a page. It feels weird and not very well organized to create a folder only for that.

A structure like this would be easier to read and write:
```
src/routes/
   +index.svelte
   +contact.svelte
   +about-us.svelte
   +landing-page.svelte
   +newsletter.svelte
   projects/
      +page.svelte
   blogs/
      +page.svelte
```

This way we already know what is in the _root level_ and what has more logic added to it. (allowing `+index.svelte` to have the same effect as `+page.svelte` is more logical I believe, but that's a detail)

Endpoints also seems more manageable:
```
src/routes/api/users
   +getByID.server.ts
   +getByEmail.server.ts
   +addFileAttachement.server.ts
   auth/
      +login.server.ts
      +logout.server.ts
``` 

This way your file structure is divided by 2. You directly know that `auth` have more logic behind. You have to do fewer clicks to know how your application is organized and it takes less space in the code editor explorer.  

If a folder has the same endpoint as a named page, the folder could take over.
```
src/routes/
   about-us/
      +page.svelte
      +page.ts      <-- can also be used for +about-us.svelte
   +about-us.svelte      <-- ignored
```

Reserved keywords `+layout.` `+error` `+page` and `+server` takes priority (it does not create a route named 'layout' for example).

This is not a breaking change since we keep folder routing like before.

### Alternatives considered

- For endpoints, dropping Sveltekit and injecting fastify to the server hook `handle` function instead. 
- For public pages that doesn't need SRR, build a separate SPA by splitting the `svelte-spa-router` async routes with esbuild.

### Importance

would make my life easier

**Comment by david-plugge** [comment]
Allowing custom file names would bring back way more complexity. They decided to go with folder based routing because it gives you a very good overview about what a route is actually doing without opening a single file. And it's always better to have a single correct way of doing things.

**Comment by Rich-Harris** [comment]
The current approach was reached after being discussed at torturous length, and isn't going to change
