### ISSUE TITLE
sw.js inline import `?url` filecontent, it should be return a file url.

### ISSUE THREAD

**Issue by shynome** [sveltejs/kit#9256]
### Describe the bug

sw.js inline import `?url` filecontent, it should be return a file url.

### Reproduction

```sh
npm create svelte sw-inline-reproduction
cd sw-inline-reproduction
echo 'import l from "./service-worker.js?url";console.log(l)' > src/service-worker.js
npm run build
cat .svelte-kit/output/client/service-worker.js
```
you will see the `service-worker.js` file include to the `?url` filecontent

### Logs

```log
const a = "data:application/javascript;base64,aW1wb3J0IGwgZnJvbSAiLi9zZXJ2aWNlLXdvcmtlci5qcz91cmwiO2NvbnNvbGUubG9nKGwpCg==";
console.log(a);
```

### System Info

```Shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 18.65 GB / 30.72 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.14.2 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.0 - /usr/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 102.8.0esr
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-static: ^2.0.1 => 2.0.1 
    @sveltejs/kit: ^1.9.1 => 1.9.1 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.1.4 => 4.1.4
```

### Severity

serious, but I can work around it

### Additional Information

I have import a large wasm file (size 1.6M) in sw.js, if inline the wasm file will make sw.js load slow. (`assetsInlineLimit: 0` option is not working for sw.js)
My current solution is to copy the wasm files to the `static` directory and manually set the wasmUrl

**Comment by shynome** [comment]
I have updated the Reproduction step, now it easily reproduce

**Comment by Rich-Harris** [comment]
Started investigating in https://github.com/sveltejs/kit/pull/9285
