### ISSUE TITLE
`cookies.getAll()`

### ISSUE THREAD

**Issue by david-plugge** [sveltejs/kit#9263]
### Describe the problem

The supabase auth helpers store the session inside cookies to be able to authenticate on the server.
This session can get pretty big and therefore exceeds the cookies size limit.
To overcome this problem we are going to implement cookie chunking.

If you want to store data inside a cookie that exceeds the cookie size limit you have to either implement session id´s or cookie chunking ([next auth](https://next-auth.js.org/configuration/options#cookies) does this).

### Describe the proposed solution

add `cookies.getAll()`
the return type could be an iterator so something like this is possible:

```ts
for (const { name, value } of cookies.getAll()) {
  if (name.startsWith(cookieName)) {
     ...
   }
}
```

### Alternatives considered

Use a "workaround" like this:

```ts
export function getChunkedCookie(cookies: Cookies, name: string, opts?: CookieParseOptions) {
	const value = cookies.get(name);
	if (value) {
		return value;
	}

	const chunks: string[] = [];

	for (let i = 0; ; i++) {
		const cookieName = `${name}.${i}`;
		const chunk = cookies.get(cookieName, opts);

		if (chunk) {
			chunks.push(chunk);
		} else {
			break;
		}
	}
	return chunks.length ? chunks.join('') : undefined;
}
```

### Importance

nice to have

**Comment by Rich-Harris** [comment]
yeah, this seems like a reasonable addition. PRs welcome :)
