### ISSUE TITLE
path autocomplete not working

### ISSUE THREAD

**Issue by zhihengGet** [sveltejs/kit#9278]
### Describe the bug

src/
-----lib /
 ----------rti /

somehow `$lib/` does not show any path hints when i try to import { } from "$lib",  i was expecting 'rti' to show  

i have svelte vscode extension installed.

also included an stackblitz repo, if u go to my-app/.../ test.ts , and try to import from it, no path autocomplete

here is my tsconfig, did not touch.

```

{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true
	}
	// Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
	//
	// If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
	// from the referenced tsconfig.json - TypeScript does not merge them in
}
```

.```
svelte/tsconfig

{
	"compilerOptions": {
		"paths": {
			"src": [
				"../src"
			],
			"src/*": [
				"../src/*"
			],
			"$lib": [
				"../src/lib"
			],
			"$lib/*": [
				"../src/lib/*"
			]
		},
	
		"rootDirs": [
			"..",
			"./types"
		],
		"importsNotUsedAsValues": "error",
		"isolatedModules": true,
		"preserveValueImports": true,
		"lib": [
			"esnext",
			"DOM",
			"DOM.Iterable"
		],
		"moduleResolution": "node",
		"module": "esnext",
		"target": "esnext"
	},
	"include": [
		"ambient.d.ts",
		"./types/**/$types.d.ts",
		"../vite.config.ts",
		"../src/**/*.js",
		"../src/**/*.ts",
		"../src/**/*.svelte",
		"../tests/**/*.js",
		"../tests/**/*.ts",
		"../tests/**/*.svelte"
	],
	"exclude": [
		"../node_modules/**",
		"./[!ambient.d.ts]**",
		"../src/service-worker.js",
		"../src/service-worker.ts",
		"../src/service-worker.d.ts"
	]
}

### Reproduction

[stackblitz new project](https://stackblitz.com/edit/node-4dsqka?file=my-app/src/lib/test.ts)

### Logs

```Shell
no
```

### System Info

```Shell
windows
```
using latest sveltekit , fresh project
"svelte": "^3.54.0",
"svelte-check": "^3.0.1",

### Severity

annoyance

**Comment by zhihengGet** [comment]
ok do i need to update base tsconfig.ts with baseURL:"." ?

**Comment by jasonlyu123** [comment]
It's a known issue in TypeScript. The path completion under `$lib` doesn't work without a `baseURL`. You can set  `baseURL`. But `baseURL` also has its problem with auto import. If you manually write import more frequently, you can consider adding that until it's fixed in TypeScript.

**Comment by Rich-Harris** [comment]
Is there anything we can do on our end or should this be closed?

**Comment by zhihengGet** [comment]
feel free to close if there is nothing sveltekit can do about it !

**Comment by siaikin** [comment]
hi @Rich-Harris i have same issue. but TypeScript say "[This must be specified if "paths" is.](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping)"

Whether it is better to add baseUrl by default?
