### ISSUE TITLE
Use parens for shadowing parts of folder name in route 

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#9283]
### Describe the problem

Similar to [`(groups)`](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group) for assigning different layouts to files with equal base route, we could also give `(xyz)` special meaning for ignoring _parts_ of folder names?

### Describe the proposed solution

```txt
(2023-03-02)post-3/+page.svelte
(2023-02-12)post-2/+page.svelte
(2023-01-28)post-1/+page.svelte
```

are nicely sorted by date in the file tree but would be served as

```
/post-3
/post-2
/post-1
```

by the app.

### Alternatives considered

You could make the date string a separate folder.

```txt
(2023-03-02)/post-3/+page.svelte
(2023-02-12)/post-2/+page.svelte
(2023-01-28)/post-1/+page.svelte
```

### Importance

nice to have

**Comment by Rich-Harris** [comment]
We can't do this as it would be a breaking change — `(2023-03-02)post-3` is already a valid route. We could _potentially_ revisit for 2.0, but not before then

**Comment by david-plugge** [comment]
That's actually a nice idea. Using a folder with parens isn't too bad as VS code for example just opens up the first folder that holds a file.

**Comment by dummdidumm** [comment]
Not sure how I feel about this. I don't think this is something that warrants the additional implementation complexity, and potentially taking away a valid route.

**Comment by Conduitry** [comment]
> taking away a valid route

You'd still be able to do https://kit.svelte.dev/docs/advanced-routing#encoding so I don't think that's a concern.

As for whether this is a worthwhile feature, I don't know.

**Comment by benmccann** [comment]
I tend to think we shouldn't do this. The `()` syntax could be confused with [grouped routes](https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group). But primarily, each time we add a new piece of syntax the routing system becomes harder for users to understand and I don't think the benefit is worth it in this case.
