### ISSUE TITLE
Give a warning when the root load function failed.

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/kit#9284]
### Describe the problem

Currently, the code in https://github.com/sveltejs/kit/blob/7c8dbf36af71bc4bad603dd661efbf0c030fd808/packages/kit/src/runtime/client/client.js#L903 does not give a warning after form submission when an error is thrown in the load (using the kit version `throw error(500, error)`) but just refreshes the whole page and omits the error. It would be nice if the error was shown to be able to debug the application.

### Describe the proposed solution

Add a log statement that is visible in dev and prints error.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
By the nature of the solution (reloading the page) there isn't really a good place to print an error, since it will immediately vanish when the page reloads. I'm not sure what the right fix is — perhaps adding a `debugger` statement to prevent the reload?

**Comment by wvhulle** [comment]
Thanks a lot!
