### ISSUE TITLE
Netlify Adapter: Custom redirects not working

### ISSUE THREAD

**Issue by kvn-shn** [sveltejs/kit#930]
**Describe the bug**
Custom Netlify redirects don't work. Neither using `netlify.toml` nor `static/_redirects`.

**To Reproduce**
1. Setup a minimal SvelteKit app using the [Netlify adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify)
2. Specify a [redirection rule](https://docs.netlify.com/routing/redirects/), e.g. put `/old /new` in `static/_redirects`
3. Deploy the build output on Netlify (or test it locally using [Netlify Dev](https://cli.netlify.com/netlify-dev/))
4. Navigate to https://YOUR-TEST-PAGE.example/old
5. Now you'll get a Svelte 404 error

**Expected behavior**
* Instead of the 404, my website should actually redirect to https://YOUR-TEST-PAGE.example/new
* Document that redirections in `netlify.toml` aren't supported (for now?) because the adapter itself defines a "catch all" in `_redirects` [making all in `netlify.toml` unusable](https://cli.netlify.com/netlify-dev#redirects)

**Information about your SvelteKit Installation:**
* @sveltejs/kit: next => 1.0.0-next.64
* @sveltejs/adapter-netlify => 1.0.0-next.4
* svelte: ^3.29.0 => 3.36.0
* vite: ^2.1.0 => 2.1.4

**Severity**
For me personally? High, as I'm planning to replace an old website with SvelteKit and have to gracefully deal with old URLs. At least the `_redirects` definitions should work.

**Additional context**
* I already noticed that the adapter is simply overwriting my own `_redirects` file with its own content because [`writeFileSync()` is used](https://github.com/sveltejs/kit/blob/bb2d97d9c590b52b23c8a4de68794ab0b7fb5441/packages/adapter-netlify/index.js#L54).
* When investigating the issue locally I tried to change it to `appendFileSync()` (which makes more sense in my opinion). 
* Then however I'm getting the following:
  ```
  Must use import to load ES Module: MY-PROJECT/functions/render/index.js
  require() of ES modules is not supported.
  require() of MY-PROJECT/functions/render/index.js from /npm/node_modules/netlify-cli/node_modules/lambda-local/build/lambdalocal.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from MY-PROJECT/package.json.
  ```
* Renaming `index.js` to `index.cjs` as suggested leads to another error.

Here I had to stop because I don't know what that error above exactly means. I hope my report is helping though. Nice project btw!

**Comment by kvn-shn** [comment]
Thinking about it a little more, doing the following seems to be best:
* Append the required line to an existing `_redirects` rather than overwriting it.
* Add a flag to disable adding this redirection altogether so we can use the more powerful `netlify.toml` instead (and have to add it there ourselves).
* Document this special treatment in the readme.

What do you think?

**Comment by mikenikles** [comment]
I had a good night's sleep as well and a clearer understanding of the situation after reading more into the Netlify docs. I agree with your latest comment, using `netlify.toml` should be the preferred way to go.

One addition I suggest to requirements:
* If there is no existing `_redirects` file and the `netlify.toml` does not have the required redirect, we keep the current behaviour (i.e. we create the `_redirects` file with `/* /.netlify/functions/render 200`

**Comment by kvn-shn** [comment]
Thought about it even more. ;) We should try to make it even smarter:
1. Check if the adapter-specific redirection is in the TOML:
    * Yes: nothing to do here anymore, proceed normally.
    * No: continue.
2. Check if there are any other `[[redirects]]` in the TOML:
    * Yes: fail with an error, e.g. "Netlify adapter's redirection rule is missing. Please add [...] at the end of your netlify.toml"
    * No: continue.
3. Do the `appendFileSync(publish + '/_redirects', '\n\n/* /.netlify/functions/render 200')` thing. It should automatically create the file if it doesn't already exist. Else, `\n` ensures that it's added in a proper new line.

Additionally we should point out in the readme that no (other) custom "catch all" redirects are allowed, neither in `netlify.toml` nor in `_redirects`.

**Comment by mikenikles** [comment]
These steps sound reasonable to me. I can adjust the open PR #932 accordingly, but wonder if @benmccann had any comments before I start to work on the changes.

For anyone else ending up here, I needed a workaround to support existing redirects ([commit](https://github.com/gitpod-io/website-kumquat/pull/345/commits/8da27388a55cc1c65a0852ccb1c5866cefc9cca9)). Here's what's needed:
1. In `netlify.toml`, add the following redirect rule at the end of the file:
    ```toml
    [[redirects]]
      from = "/*"
      to = "/.netlify/functions/render"
      status = 200
    ```
1. Delete the `./build/_redirects` file once `svelte-kit build` completes

**Comment by benmccann** [comment]
I'm not that familiar with `netlify.toml`. I'd say if you both agree on what to change then go ahead and send that PR

**Comment by kvn-shn** [comment]
I just noticed that @Rich-Harris made some changes. So now a custom `_redirects` isn't even considered anymore (just the internal file is used). So how should we proceed with this?

I still like the approach described above https://github.com/sveltejs/kit/issues/930#issuecomment-817077432 as I have a rather long `_redirects` that would be less maintainable using the `netlify.toml` format. However step 3 would have to be adjusted somehow... Any suggestions?

**Comment by benmccann** [comment]
I think we should respect the existing config. See https://github.com/sveltejs/kit/issues/60 which is an open issue for that

**Comment by benmccann** [comment]
@kvn-shn @mikenikles is this something that either of you plan to work on? There's an open PR, but it's gone a bit stale with no one touching it, so I'm not quite sure whether we should keep it open

**Comment by kvn-shn** [comment]
We can close the PR as it already diverged too much (and the changes wasn't that big anyway).

To be honest I'm unsure how we should proceed here. I hoped @Rich-Harris would chime in and discuss with us how it's supposed to be done now because with the [recent changes](https://github.com/sveltejs/kit/blob/6f101932326b68dc1c858371ce1f87973a92cbe6/packages/adapter-netlify/index.js#L42) the possibility to easily fix it got *worse*: now `_redirects` is simply overridden not taking an existing `_redirects` into account at all.

**Comment by benmccann** [comment]
Is there a reason you even need to define custom redirects in `netlify.toml`? You can do it in SvelteKit itself either in `load` or `handle`. Doing it in SvelteKit would make it much easier to migrate to another host should you ever have a desire to do that

**Comment by caesar** [comment]
@benmccann but that wouldn't work for a static site – unless I've misunderstood what you're suggesting?

Surely the simple solution is for SvelteKit to append (or prepend) to `_redirects` rather than overwriting it. Would that be difficult?

**Comment by caesar** [comment]
Oh, I may have misunderstood – do the hooks you're suggesting using run onload, in the browser?
But in that case you would have the overhead of the client loading the page before the redirect, which is far from ideal, plus you can't send eg a 301 redirect which is useful for search engines.

**Comment by benmccann** [comment]
Good point. I think that it could do a client-side redirect, but that's probably different than the server-side redirect that I imagine that Netlify would do

It seems very reasonable update the file rather than overwriting it. It's probably not something the maintainers would get to, but I'd be open to a PR from the community for it

**Comment by caesar** [comment]
I will need this when I use SvelteKit in production so I'd be happy to take a look – but I probably won't have time in the near future, so if anyone else wants to get to it before me, go ahead! 😄

Regarding doing it in SvelteKit so that migrating to another host in future is easier – I wonder if a good approach would be to add the redirects to SvelteKit's config, and then the individual Adapters (Netlify, Vercel, etc) could output them in the appropriate format for each host? Of course that's more work to implement, but it would give greater portability.

**Comment by kvn-shn** [comment]
I need it too so I started a quick PR to get some progress on this: https://github.com/sveltejs/kit/pull/1484

btw, I decided against the more robust implementation described in https://github.com/sveltejs/kit/issues/930#issuecomment-817077432 as it's overengineering and the "quick fix" -- just appending the specific rule -- should do it too.

**Comment by caesar** [comment]
Thanks @kvn-shn, that PR looks reasonable – though I don't know if the fatal error is really necessary if a catch-all is found in `netlify.toml`? Maybe just a warning that it won't do anything?

Thinking more about what @benmccann said – and looking further into how the Netlify Adapter works – I realise that a site published with the Netlify Adapter is not static / pre-rendered after all, but server-rendered using Netlify Functions.
That being the case, perhaps the `handle` hook would work for this after all.

That said, I still think the adapter shouldn't break `_redirects` unnecessarily, so I'm +1 on the solution in #1484.

**Comment by kvn-shn** [comment]
Thanks for your feedback. In my opinion it's reasonable to throw an error because for the Netlify Adapter it's simply invalid to have any other catch-all redirect besides the generated one.

One benefit of using Netlify's redirects instead of something SvelteKit provides is that they are [way more powerful](https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file), e.g. redirects by country or language or role, setting headers etc.

**Comment by caesar** [comment]
Both good points, and bearing that in mind the PR looks good to me. 👍

**Comment by caesar** [comment]
One more thought: bearing in mind that `netlify.toml` supports more advanced redirect support (including all the syntax described in the page you linked), and bearing in mind that a catch-all in `_redirects` prevents any redirects in `netlify.toml` from working, is there a reason Netlify Adapter's catch-all can't go in `netlify.toml` instead of in `_redirects`?

**Comment by benmccann** [comment]
Netlify's redirects aren't and can't be more powerful than SvelteKit's. SvelteKit has access to all the same info as Netlify and potentially more and allows you to write custom code. If you write something in `handle` or `load` it will be run as a Netlify function and you can still prerender pages if you'd like

**Comment by caesar** [comment]
@benmccann true, but it will require several lines of code to do what you could do with one line in `_redirects` or with a simple `netlify.toml` config. It's probably faster too. For the same reasons, on my own server I do redirects in nginx config instead of in application code.

I guess it comes down to personal preference, but either way, I think in principle the adapter shouldn't break Netlify's built-in functionality unless it really *has* to.
