### ISSUE TITLE
Second non-optional parameter is skipped when root optional parameter is not matched

### ISSUE THREAD

**Issue by banDeveloper** [sveltejs/kit#9304]
### Describe the bug

Considering the following route path:

/[[lang=en]]/[param1=param1]/[param2]/[param3]
- lang matches "en"
- param1 matches "a"

If we print out the `params` for each route we get:
/en/a - `lang: "en", param1: "a"` - correct
/en/a/b - `lang: "en", param1: "a", param2: "b"` - correct
/en/a/b/c - `lang: "en", param1: "a", param2: "b", param3: "c"` - correct

/a - `param1: "a"` - correct
/a/b - `param1: "a", param2: "b"` - correct
/a/b/c - `param1: "a", param2: "c"` - wrong, `param2` should be `b` and `param3` should be `c`

This bug did not exist in 1.3.8, I'm assuming it was caused by [fix: successive optional route parameters can now be empty](https://github.com/sveltejs/kit/pull/9266).

### Reproduction

[https://stackblitz.com/edit/sveltejs-kit-template-default-p8azya?file=README.md](https://stackblitz.com/edit/sveltejs-kit-template-default-p8azya?file=README.md)

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.9.3 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.4
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
Ah, whoops — cc'ing @glennsayers in case we don't get a chance to look at this soon :)
