### ISSUE TITLE
Feature request: getting request info in server-side components

### ISSUE THREAD

**Issue by kahverengi001** [sveltejs/kit#931]
I have an issue while processing headers from requests per page. For example; I can access request headers via only hooks. But I need request information in components for learning what is client's request information such as headers.

It would be amazing if you can simply add a module for it or add it into one of the other modules.

This feature is really important because, for example, I need to use the client's headers in API calls to the backend server.

**Comment by Conduitry** [comment]
You can already do this with the `getContext` and `getSession` hooks, so that the required data is exposed everywhere in the session store.

**Comment by kahverengi001** [comment]
Is it possible to get request headers in a page component from a session store? Because my session store just returns empty.


 ```
 import { browser } from "$app/env";
  import { getStores, session } from "$app/stores";

  if (!browser) {
    console.log(session)
  }
```

**Comment by kahverengi001** [comment]
@Conduitry As far as I see from documentation, the hooks are for endpoints. But we also need headers in components too. If there is an option to get headers in pages such as `routes/index.svelte` then explain. I strongly recommend opening this issue back.
