### ISSUE TITLE
props for endpoints

### ISSUE THREAD

**Issue by ryoppippi** [sveltejs/kit#9315]
### Describe the problem

Sveltekit endpoints are great.
However, the endpoint call is not typesafe. This is true for input and endpoint path names.

#### for argument
Like
`export page`
we define
`export props`
for endpoint inputs

```typescript
export Props: {id: string};

export const GET = ({props})=>{
	const {id} = props;
 .....
```
When we use typescript, we can get a type information from the editors.

#### for endpoint path
Maybe we can create some object like what tRPC creates

### Importance

would make my life easier

**Comment by ryoppippi** [comment]
I used tRPC with Sveltekit, and this experience is awesome.
But I do not think it is impossible for sveltekit

**Comment by dummdidumm** [comment]
If you want that kind of type safety I think it's best to just use tRPC - it's designed for this use case. We would just be playing catch-up.
