### ISSUE TITLE
Subcomponents EG. <Form.Input /> 

### ISSUE THREAD

**Issue by bobbymannino** [sveltejs/kit#9316]
### Describe the problem

I may be missing the obvious but I cannot find a way to create sub components, is there something im missing or is it not a feature yet?

### Describe the proposed solution

Have sub components in svelte

### Importance

nice to have

**Comment by Rich-Harris** [comment]
What do you mean? Like this? https://svelte.dev/repl/0e79b23dd3b74e56912bc3a9016f78c1?version=3.55.1

**Comment by Rich-Harris** [comment]
(not sure why you'd want to do that, but... you can)

**Comment by bobbymannino** [comment]
Exactly what I was after, couldn’t find it online anywhere my bad, thank you
