### ISSUE TITLE
Unclear whether adapter-vercel has any benefits over adapter-auto

### ISSUE THREAD

**Issue by efstajas** [sveltejs/kit#9334]
### Describe the bug

This is not a *bug* really, more like a small inconsistency that is a little confusing.

When you deploy on Vercel using `adapter-auto`, something (assuming `adapter-vercel`) prints the following line during build:

> If you plan on staying on this deployment platform, consider replacing @sveltejs/adapter-auto with @sveltejs/adapter-vercel. This will give you faster and more robust installs, and more control over deployment configuration.

Prompted by this, I went to check out `adapter-vercel`, but the first and only thing written in [the readme](https://github.com/sveltejs/kit/blob/master/packages/adapter-vercel/README.md) is:

> If you're using [adapter-auto](https://kit.svelte.dev/docs/adapter-auto), you don't need to install this unless you need to specify Vercel-specific options, since it's already included.

So, the build log reads like there's some benefit to explicitly using adapter-vercel beyond extra configuration, but the adapter's README makes it sound like it won't make a difference at all. Wondering which one is true.

### Reproduction

- Publish any sveltekit app using adapter-auto on Vercel, and observe the build log including the quoted line.
- Observe [adapter-vercel's README](https://github.com/sveltejs/kit/blob/master/packages/adapter-vercel/README.md) including a seemingly contradictory statement. 

### System Info

```Shell
N/A
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
The prompt is more correct. If you plan to stay on a specific platform, install the adapter for that specific platform.

**Comment by efstajas** [comment]
Alright, thanks for the confirmation! Doing that, then :)
