### ISSUE TITLE
@sveltekit/adapter-cloudflare added redundant "+" in environment variable

### ISSUE THREAD

**Issue by ThangHuuVu** [sveltejs/kit#9335]
### Describe the bug

Hi there, it seems like when using SvelteKit with `@svelte/adapter-cloudflare`, my envs are automatically added "+" before and after the value.
I followed the instruction on this page: https://kit.svelte.dev/docs/adapter-cloudflare
Here is the code I use:
```ts
export const handle = SvelteKitAuth(async (event) => {
  const authOptions = {
    providers: [GitHub({ clientId: event.platform.env?.GITHUB_ID!, clientSecret: event.platform.env?.GITHUB_SECRET! })] as any,
    secret: event.platform.env?.AUTH_SECRET,
    trustHost: true
  }
  return authOptions satisfies SvelteKitAuthConfig
}) satisfies Handle;
```
I deployed my code at https://sveltekit-auth-cloudflare.pages.dev/

When I clicked on login, I got redirected to: https://github.com/login/oauth/authorize?scope=read%3Auser+user%3Aemail&response_type=code&client_id=+09b05339034599edca67+&redirect_uri=https%3A%2F%2Fsveltekit-auth-cloudflare.pages.dev%2Fauth%2Fcallback%2Fgithub&code_challenge=redacted&code_challenge_method=S256

Notice that my client_id is appended with the plus sign on both ends.
My env is set in Cloudflare Dashboard -> Pages -> sveltekit-auth-cloudflare -> Settings -> Environment Variables
<img width="499" alt="Screen Shot 2023-03-06 at 19 07 18" src="https://user-images.githubusercontent.com/31528554/223106111-f12da55b-ae02-4f65-b341-9ac7e792ac3d.png">

This doesn't happen if I don't use the `adapter-cloudflare` package. A working example without it: https://sveltekit-auth-example.vercel.app/

### Reproduction

https://github.com/ThangHuuVu/sveltekit-auth-cloudflare

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 111.84 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 15.6.1
    Safari Technology Preview: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.91 
    @sveltejs/adapter-cloudflare: 1.0.0-next.45 => 1.0.0-next.45 
    @sveltejs/kit: next => 1.0.0-next.589 
    svelte: 3.55.0 => 3.55.0 
    vite: 4.0.1 => 4.0.1
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
`+` is how spaces are encoded in search parameters:

```js
q = new URLSearchParams();
q.set('client_id', ' 09b05339034599edca67 ');
q.toString(); // '+09b05339034599edca67+'
```

It sounds like you have some spaces in the env vars in your dashboard?

**Comment by ThangHuuVu** [comment]
Thanks, @Rich-Harris - that's totally it! Sorry for the false alarm
