### ISSUE TITLE
Navigation "goto" updates adressbar but not the component 

### ISSUE THREAD

**Issue by muellercornelius** [sveltejs/kit#935]
**Describe the bug**
I am trying to implement route guards but when I try to intercept the routing only the adressbar is updated but the normal routing continues to work.

This is the Code I used. Propably not intended to be used like this. 

``` js
        import { navigating } from '$app/stores';
	import { goto } from '$app/navigation';

	let authorized = false;

	navigating.subscribe((route) => {
		if(!route) return;
		if(route.to.path !== "/login" && !authorized) {
			goto("/login")
		}
	});
```

**What I Expect to Happen**
The Login Page should show up.

**What Really Happens**
The Page of the clicked Link shows up but the adressbar says: `"http://localhost:3000/login"`

**To Reproduce**
https://github.com/muellercornelius/Svelte-Routing-Bug

**Stacktraces / Logs**
Nothing

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

```
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 2.98 GB / 7.92 GB
  Binaries:
    Node: 15.5.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```

- Newest Chrome

- No Adapter. Only local Testing.
</details>

**Severity**
Hmmm yes, quite a bummer. Without it I see no solution to intercept the routing. Maybe other options work or an official solution for route guards would be great.

**Comment by nitroboy720** [comment]
If you want a solution before this gets checked out/fixed, see [https://kit.svelte.dev/docs#loading](https://kit.svelte.dev/docs#loading), especially the part about redirect. This is were route guards are usually done.

**Comment by lukaszpolowczyk** [comment]
I have it too - the address changes and the component does not.

But if I modify the code and refresh the page manually and then use `goto`, ONCE `goto` works - the address changes and so does the component.
Reusing `goto` anymore, even then, doesn't work.
If I manually refresh the page again, then `goto` will run again once.

Just clicking a link, a back button, etc. works the same.


<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 8.90 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.8.0 - /usr/bin/npm
  Browsers:
    Firefox: 85.0
  npmPackages:
    @sveltejs/kit: 1.0.0-next.71 => 1.0.0-next.71 
    svelte: ^3.37.0 => 3.37.0 
    vite: ^2.1.5 => 2.1.5 
```
</details>

So a change in the code does something, but only once.

Steps A:
* `npm run dev`
* open page in the browser
* click the button with `goto`
* **result:** the address changes and the component <ins>does not</ins>.

Steps B:
* `npm run dev`
* open page in the browser
* <ins>change something in the code</ins> (something important, more than a space)
* click the button with `goto`
* **result:** the address changes and the component <ins>does not</ins>.

but with refresh page...
Steps C:
* `npm run dev`
* open page in the browser
* <ins>change something in the code</ins> (something important, more than a space)
* refresh page
* click the button with `goto`
* **result:** the address changes and **the component changes**
* click the button with `goto` again
* **result:**  the address changes and the component <ins>does not</ins>.
* click the button with `goto` again
* **result:**  the address changes and the component <ins>does not</ins>.
* (...)
* refresh page
* click the button with `goto`
* **result:** the address changes and **the component changes**
* click the button with `goto` again
* **result:**  the address changes and the component <ins>does not</ins>.
* (...)

Is it just a question of refreshing? No:
Steps D:
* `npm run dev`
* open page in the browser
* refresh page
* click the button with `goto`
* **result:**  the address changes and the component <ins>does not</ins>.

**Comment by lukaszpolowczyk** [comment]
I have it too - the address changes and the component does not.

But if I modify the code and refresh the page manually and then use `goto`, ONCE `goto` works - the address changes and so does the component.
Reusing `goto` anymore, even then, doesn't work.
If I manually refresh the page again, then `goto` will run again once.

Just clicking a link, a back button, etc. works the same.


<details>
  <summary>Diagnostics</summary>

```
  System:
    OS: Linux 5.10 Arch Linux
    CPU: (4) x64 AMD Athlon(tm) X4 950 Quad Core Processor
    Memory: 8.90 GB / 15.07 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 7.8.0 - /usr/bin/npm
  Browsers:
    Firefox: 85.0
  npmPackages:
    @sveltejs/kit: 1.0.0-next.71 => 1.0.0-next.71 
    svelte: ^3.37.0 => 3.37.0 
    vite: ^2.1.5 => 2.1.5 
```
</details>

So a change in the code does something, but only once.

Steps A:
* `npm run dev`
* open page in the browser
* click the button with `goto`
* **result:** the address changes and the component <ins>does not</ins>.

Steps B:
* `npm run dev`
* open page in the browser
* <ins>change something in the code</ins> (something important, more than a space)
* click the button with `goto`
* **result:** the address changes and the component <ins>does not</ins>.

but with refresh page...
Steps C:
* `npm run dev`
* open page in the browser
* <ins>change something in the code</ins> (something important, more than a space)
* refresh page
* click the button with `goto`
* **result:** the address changes and **the component changes**
* click the button with `goto` again
* **result:**  the address changes and the component <ins>does not</ins>.
* click the button with `goto` again
* **result:**  the address changes and the component <ins>does not</ins>.
* (...)
* refresh page
* click the button with `goto`
* **result:** the address changes and **the component changes**
* click the button with `goto` again
* **result:**  the address changes and the component <ins>does not</ins>.
* (...)

Is it just a question of refreshing? No:
Steps D:
* `npm run dev`
* open page in the browser
* refresh page
* click the button with `goto`
* **result:**  the address changes and the component <ins>does not</ins>.

**Comment by lukaszpolowczyk** [comment]
Code and GIF for Option C:

```svelte
<!-- [slug].svelte -->
<script>
	import { getStores, navigating, page, session } from '$app/stores';
	import {onMount} from "svelte";
	import { goto } from '$app/navigation';
	let slug = $page.params.slug;
	$:slug2 = $page.params.slug;
	
	onMount(()=>console.log("onMount",$page.params.slug));
</script>
{$page.params.slug} $page.params.slug<br>
{slug} let slug<br>
{slug2} $:slug2<br>
<a href={`${Number($page.params.slug)+1}`}>{Number($page.params.slug)+1}</a>
<button on:click={()=>goto(`${Number($page.params.slug)+1}`)}>{Number($page.params.slug)+1}</button>

```
![svelte-kit-bug](https://user-images.githubusercontent.com/16800535/114256608-9eac7080-99ba-11eb-976f-4ff9eece4466.gif)

**Comment by muellercornelius** [comment]
Thank you @nitroboy720 that was a great advice. It worked perfectly ;).

**Comment by Rich-Harris** [comment]
redirects are the correct solution here, so I'll close this

**Comment by wiesson** [comment]
> If you want a solution before this gets checked out/fixed, see https://kit.svelte.dev/docs#loading, especially the part about redirect. This is were route guards are usually done.

That is true, but it only works on server side (?). Our app uses firebase and I wasn't able to get both the frontend and the admin library (cookie auch / token check) up and running, so I'm using the same technique as the OP mentioned and I did run in the same errors 😅
