### ISSUE TITLE
Customize navigation scroll container [router]

### ISSUE THREAD

**Issue by lukasIO** [sveltejs/kit#937]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a website where - due to the design - it is not desired that the website scrolls on `window` when navigating but rather on a container child (in my case the `main` element).
The current implementation in the router calls the `scrollTo()` function on the window element with no ability to customize the scroll container

**Describe the solution you'd like**
It'd be great to be able to use SvelteKit navigation features like auto-scroll-to-top and scroll restoration also for a custom scroll container.

What I imagine is something like
```diff
+const scrollContainer = customScrollContainer | window;  // if a customScrollContainer is set, use it, otherwise default to the window object
const deep_linked = hash && document.getElementById(hash.slice(1));
if (scroll) {
-  scrollTo(scroll.x, scroll.y);
+  scrollContainer.scrollTo(scroll.x, scroll.y);
} else if (deep_linked) {
  // scroll is an element id (from a hash), we need to compute y
-  scrollTo(0, deep_linked.getBoundingClientRect().top + scrollY);
+  scrollContainer.scrollTo(0, deep_linked.getBoundingClientRect().top + scrollY);
} else {
-  scrollTo(0,0);
+  scrollContainer.scrollTo(0, 0);
}
```

**Describe alternatives you've considered**
I guess the alternative would be to duplicate what the router is doing after each navigation but instead on the custom scroll container.

**How important is this feature to you?**
It'd be really useful for me, but it's definitely more of a nice to have.

**Additional context**
I'd be happy to submit a PR if this is something that you'd be open to.
I'm not sure what would be the best place to set a custom scroll container (maybe an object in `$app/navigation`?), so I would be happy about suggestions.

**Comment by benmccann** [comment]
See `disableScrollHandling` in the docs: https://kit.svelte.dev/docs/modules#$app-navigation
