### ISSUE TITLE
Error during sveltkit app building

### ISSUE THREAD

**Issue by Graciasjr** [sveltejs/kit#9379]
### Describe the bug

When i try to build my svelteKit app, I have error in console
error after npm run build 👇🏿

### Reproduction

`node:internal/process/promises:288        
            triggerUncaughtException(err, 
true /* fromPromise */);`
            ^

`[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by 
rejecting a promise which was not handled 
with .catch(). The promise rejected with the reason "#<Redirect2>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}`

### System Info

```Shell
`Node.js v18.9.0
[vite-plugin-sveltekit-compile] Failed with code 1
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///C:/MAMP/htdocs/svelteKit/node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)`
```

**Comment by dummdidumm** [comment]
Please provide a reproduction

**Comment by Graciasjr** [comment]
> Merci de fournir une reproduction

`Node.js v18.9.0
[vite-plugin-sveltekit-compile] Failed with code 1
error during build:
Error: Failed with code 1
    at ChildProcess.<anonymous> (file:///C:/MAMP/htdocs/svelteKit/node_modules/@sveltejs/kit/src/utils/fork.js:68:13)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12`

**Comment by Rich-Harris** [comment]
From the [issue template](https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml):

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

Please provide a reproduction, or this issue will be closed.

**Comment by Graciasjr** [comment]
> From the [issue template](https://github.com/sveltejs/kit/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml):
> 
> > A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
> 
> Please provide a reproduction, or this issue will be closed.

Sorry, I finally fixed the bug.
The bug was caused by a redirect function that was in the wrong places in my page.js .

Sorry for the confusion I created by opening this issue. it's because my english is not very good and i have a hard time expressing myself
Sorry

**Comment by Rich-Harris** [comment]
No worries! Glad it's resolved.
