### ISSUE TITLE
Multiple +layout/+page.svelte with layout reset should be forbidden

### ISSUE THREAD

**Issue by adiguba** [sveltejs/kit#9380]
### Describe the problem

Because of the layout reset syntax, it is currently possible to create multiple +page.svelte (or +layout.svelte)

Exemple :
```
routes/path/page/
           +page.svelte
           +page@.svelte
           +page@path.svelte
```

Sveltekit seems to accept that, and choose the most complete file (`+page@my-path.svelte` in this example).

I think this should be incorrect and generate an error.

### Describe the proposed solution

Create a page with multiples +page.svelte file using layout-reset.

Example :
https://stackblitz.com/edit/sveltejs-kit-template-default-ro1dgr?file=README.md

### Importance

nice to have

**Comment by geodask** [comment]
This is my first issue ever to an open source project. It seemed relatively easy so I decided to work on it. Probably my solution is not optimal and the error messages may need improvements. I will open a PR.

**Comment by geodask** [comment]
This is my first issue for an open source project. Probably the solution is not optimal and the error messages need improvements. It seemed relatively easy so I decided to give it a try.
