### ISSUE TITLE
Expose `manifest_data` to be extended by other vite plugins

### ISSUE THREAD

**Issue by gu-stav** [sveltejs/kit#9383]
### Describe the problem

I'd like to register new routes in svelte-kit, which come as part of a installed npm dependency. My current idea is to write a vite-plugin which resolves the routes folder of that dependency (inside node_modules) and extends the "router" in vite. For this I'd like to use the `configResolved()` hook (or any other).

Right now [`manifest_data`](https://github.com/sveltejs/kit/blob/7e67738f327b34f16f7971ee544c4bfba4e2654a/packages/kit/src/exports/vite/index.js#L150) is a private variable which is not exposed to other vite plugins. I think therefore there is no way that I could e.g. use the [`sync.all() / create_manifest_data()`](https://github.com/sveltejs/kit/blob/7e67738f327b34f16f7971ee544c4bfba4e2654a/packages/kit/src/exports/vite/index.js#L291) utility to re-create the routes/nodes as part of a different plugin.

### Describe the proposed solution

I am by no means an expert in vite/ rollup, but I can see two ways:

1. Expose the manifest as part of `new_config`:

```js
new_config.define = {
        // ...
	__SVELTEKIT_EMBEDDED__: kit.embedded ? 'true' : 'false',
       __SVELTEKIT_MANIFEST: manifest_data
};
```

2. Use a rollup API

I think this would give other plugins a way to access to the manifest:

```js
function plugin() {
	return {
		name: 'test',
		buildStart() {
			// trigger loading a module. We could also pass an initial
			// "meta" object here, but it would be ignored if the module
			// was already loaded via other means
			this.load({ id: 'my-id' });
			// the module info is now available, we do not need to await
			// this.load
			const meta = this.getModuleInfo('my-id').meta;
			// we can also modify meta manually now
			meta.test = { some: 'data' };
		}
	};
}
```

All places accessing `manifest_data` would need to be updated to read from the stored option.

### Importance

i cannot use SvelteKit without it

### Additional Information

I am open to any other suggestions and hope this is concrete enough to be actionable.

Would you accept a PR for that or do you want to keep the manifest private?

**Comment by Rich-Harris** [comment]
We definitely don't want to expose the manifest data publicly. Can you describe your use case in more concrete terms?
