### ISSUE TITLE
Adapter-static not applying CSS on index page

### ISSUE THREAD

**Issue by universallyleo** [sveltejs/kit#9404]
### Describe the bug

This is what I expect:
![image](https://user-images.githubusercontent.com/110659061/224484868-b59c3c28-2e5a-41a5-b6c7-7810cef0b4ba.png)

But when I upload it to [Github pages](https://universallyleo.github.io/testapp/), the index page has no CSS applied to it:
![image](https://user-images.githubusercontent.com/110659061/224484932-93be9f18-23c2-4669-b8d9-994704141059.png)

The strange thing is that CSS get applies correctly on other pages, only the index page (i.e. from ` src/+page.svelte`) has this problem.  Even stranger is if I click a link to go to another page, and then click a link coming back to the index page, the CSS will be applied!  You can see this on my [demo pages](https://universallyleo.github.io/testapp/).  Can anyone explains why this is happening?

The build produce no error of course.  It is the final result that is the problem.

There was no such problem before on my old project (built around the time when SvelteKit1.0 comes out).  But when I update my npm packages everything breaks.  So I start afresh and checked that I really doesn't show the way I expect.  If any of my steps is wrong, perhaps some clarification in the documentation will be very helpful.  Perhaps some clarification on the correct steps to how to update the svelte packages in the documentation will be helpful too.

### Reproduction

[Link](https://github.com/universallyleo/testapp) to the repo containing the demo. 

This is how I come to it:
1. `npm create svelte@latest testapp`
2. `npm install`
3. `npm i @sveltejs/adapter-static`
4. change `svelte.config.js` as follows
```
import adapter from "@sveltejs/adapter-static";

const dev = process.argv.includes("dev");

/** @type {import('@sveltejs/kit').Config} */
const config = {
    kit: {
        // adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
        // If your environment is not supported or you settled on a specific environment, switch out the adapter.
        // See https://kit.svelte.dev/docs/adapters for more information about adapters.
        adapter: adapter({
            pages: "docs",
            assets: "docs",
        }),
        paths: {
            base: dev ? "" : "/testapp",
        },
    },
};

export default config;
```
5. Add `export const prerender=true` to `+layout.js`
6. Add `+layout.svelte` and style it (this is where the CSS are set).
7. Add another page `about/+page.svelte` to demonstrate that the CSS get applies correctly on the non-index page
8. Add a blank `.nojekyll` to static folder
9. `npm run dev` checked it is producing the result I wanted
10. `npm run build` to built to docs folder
11. Upload to repo to Github and have Github Page points to docs 
![image](https://user-images.githubusercontent.com/110659061/224485240-b16c1097-5cf8-4102-b46c-184c0d2c8ba8.png)
12. Check result on [Github pages](https://universallyleo.github.io/testapp/) 

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 2.93 GB / 15.81 GB
  Binaries:
    Node: 18.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.4.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 111.0.5563.64
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/adapter-static: ^2.0.1 => 2.0.1
    @sveltejs/kit: ^1.5.0 => 1.11.0
    svelte: ^3.54.0 => 3.56.0
    vite: ^4.0.0 => 4.1.4
```

### Severity

annoyance

**Comment by s3812497** [comment]
The missing CSS in the index page is because the linked stylesheet is being set to the wrong path during build.

```html
<!-- This results in /testapp/testapp/_app instead of /testapp/_app -->
<link href="./testapp/_app/immutable/assets/_layout.a467127a.css" rel="stylesheet">
```

One workaround in the meantime would be to set relative paths to false in `svelte.config.js`.
```diff
        paths: {
            base: dev ? "" : "/testapp",
+            relative: false
        },
```
```html
<!-- always results in /testapp/_app -->
<link href="/testapp/_app/immutable/assets/_layout.a467127a.css" rel="stylesheet">
```

**Comment by universallyleo** [comment]
Thank you very much.  This does fix the issue.
I agree this is not really a bug, but it is impossible to find out from the [documentation](https://kit.svelte.dev/docs/adapter-static).  

The comment on trailingSlash in the documentation says "does not render", but in my case it is rendering - just that without CSS - and it only happens to a single page, and so I never thought about that.  After all I follow exactly the instruction under the Github Page section.  More clarity in the documentation would be great.  Hope someone in the svelte team will notice this.

**Comment by danyelkoca** [comment]
Hi,

Im having the same issue when hosting a svelte project on gh-pages.

Im hosting the app on username.github.io/<repo_name> where repo_name is "permanent"

I have done below in order to change the base of the app so that hrefs work fine:
![image](https://user-images.githubusercontent.com/34621907/226602482-63112e42-a96e-4a55-9337-8706cea09335.png)

I have 3 pages: Index, about, form

![image](https://user-images.githubusercontent.com/34621907/226602661-e3d05b45-c3c1-44ce-8b84-dfd5a936a994.png)

After building the app, css and js links are referenced from permanent folder in index.html
![image](https://user-images.githubusercontent.com/34621907/226602914-e7c81c57-3672-4d79-8a45-c3d59cbdc41a.png)

While other pages (form, about) go directly to _app
![image](https://user-images.githubusercontent.com/34621907/226603005-8f63c0f7-134f-4100-9584-2fb01fcf7698.png)

While other pages are referring to the correct location of these files, index page is looking for permanent folder, which does not exist in the build folder:
![image](https://user-images.githubusercontent.com/34621907/226603191-1fd4c294-698c-40c4-b51f-e982ea83bb75.png)

I have tried adding  `relative: false` in the svelte.config,js but it changes all references to ./permanent/_app on all pages, which is the incorrect location. 

One workaround would be to use `relative: false` and then move the _app folder under a new folder called permanent after build. This doesnt sound right though.

Any advice on how to fix this wrong reference issue on index.html?

**Comment by s3812497** [comment]
> I have tried adding `relative: false` in the svelte.config,js but it changes all references to ./permanent/_app on all pages, which is the incorrect location.

It should be referencing `/permanent/_app` when setting `relative: false`. Can you provide a repository that reproduces this? Accessing `/permanent/_app` from the base of `https://danyelkoca.github.io/` should result in the correct filepath when navigating to `https://danyelkoca.github.io/permanent`

> Any advice on how to fix this wrong reference issue on index.html?

Alternatively, you can add the `export const trailingSlash: 'always'` option for your index page.
This would align the URL with your github pages site.
```js
// src/routes/+page.js
export const trailingSlash = 'always';
```

**Comment by danyelkoca** [comment]
Thanks for the response.

`relative: false` was not solving the issue yesterday (I guess I had forgotten to add .nojekyll in the GitHub repo) 

But now, as you mentioned, all the references are changed to `/permanent/...` so it's working fine with the addition of `relative: false`.

Thanks for the help!

**Comment by s3812497** [comment]
I can no longer reproduce this issue. Assets are correctly linked in the root `index.html` page such as `<link href="./_app/immutable/assets/0.fa9427ff.css" rel="stylesheet">` even with the base path config set.
