### ISSUE TITLE
Socket hang up Kit + node-fetch - Node v19

### ISSUE THREAD

**Issue by GeoDoX** [sveltejs/kit#9409]
### Describe the bug

Node v19 introduced a 5 second delay before closing socket connections which causes node-fetch to not process requests because the socket is still busy.

I get the following error.
`
FetchError: request to http://db:8000/sql failed, reason: socket hang up
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:512:28)
    at Socket.socketOnEnd (node:_http_client:520:9)
    at Socket.emit (node:events:524:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
`

This is resolved by passing `keepAlive: false` to the server. https://futurestud.io/tutorials/node-js-fix-socket-hang-up-errors

A work around for the moment is to use node v18.

I believe this should be resolved in kit/adapter-node as it avoids having to write a custom server which would do this for you.
https://kit.svelte.dev/docs/adapter-node#custom-server

### Reproduction

TBD

### System Info

```Shell
  System:
    OS: Linux 5.15 Alpine Linux
    CPU: (8) x64 AMD FX(tm)-9590 Eight-Core Processor
    Memory: 3.57 GB / 7.71 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 19.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.2.0 => 1.2.0 
    @sveltejs/kit: ^1.5.0 => 1.9.2 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.4 
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
Closing due to lack of response.
