### ISSUE TITLE
error: "Cannot use keyword 'await' outside an async function", why?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#941]
**Describe the bug**
In `./generated/index.ts` I'm using this code:

```ts
import type { PlayerServiceClient } from './generated/player.client';

let playerService: PlayerServiceClient;

const playerClient = await import('./generated/player.client');

export const player = (): PlayerServiceClient =>
	playerService ||
	((playerService = new playerClient.PlayerServiceClient({})), playerService);
```

**Logs**
`Cannot use keyword 'await' outside an async function`

**Expected behavior**
I would like to use this because I need lazy load of many files and I would like to use it like this in my components:

```ts
import { player } from "../generated";

let players: Player[];

(async () => {
  players = await player.queryPlayers({ playerId: "1" });
})();
```

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 7.8.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.71 => 1.0.0-next.71
    svelte: 3.37.0 => 3.37.0
    vite: 2.1.5 => 2.1.5

- Your browser: Chrome

- Your adapter: static
</details>

**Comment by dymoo** [comment]
Why not just

```
export default async function() {
let playerService: PlayerServiceClient;

const playerClient = await import('./generated/player.client');

return () = PlayerServiceClient =>
	playerService ||
	((playerService = new playerClient.PlayerServiceClient({})), playerService);
}

```

**Comment by frederikhors** [comment]
Because I think is the same. I have double `await` in components, right?

I would like to have only one `await`.

How do you call that in components?

**Comment by Conduitry** [comment]
The top-level await proposal hasn't reached stage 4 (accepted) and isn't supported by Acorn, the parser we're using.

**Comment by frederikhors** [comment]
@Conduitry I read [here](https://github.com/acornjs/acorn/tree/master/acorn) that there is an option for acorn: `allowAwaitOutsideFunction`.

How can I set this option in my svelte kit environment?

**Comment by frederikhors** [comment]
I think with this I can write this code:

```ts
import { player } from "../generated";

let players: Player[];

const playerService = await player();
const { response } = await playerService.queryPlayers({ playerId: "1" });

if (response) {
  players = response.players;
}
```

instead of:

```ts
import { player } from "../generated";

let players: Player[];

(async () => {
  const playerService = await player();
  const { response } = await playerService.queryPlayers({ playerId: "1" });

  if (response) {
    players = response.players;
  }
})();
```

Right?
