### ISSUE TITLE
adapter-static still runs ssr in npm run dev

### ISSUE THREAD

**Issue by ianengelbrecht** [sveltejs/kit#9410]
### Describe the bug

Using adapter-static to create an SPA, as per instructions at https://kit.svelte.dev/docs/single-page-apps and https://kit.svelte.dev/docs/single-page-apps#usage gives a message saying ssr compile in progress ...

I would have expected no SSR at all. In this case I'm using indexedDB (via Dexie via RXDB), which throws an error as there is no indexedDB on the server. 

Repo created from skeleton template. No server side code at all.

Seems related to issue #9161 

### Reproduction

https://github.com/ianengelbrecht/svelte-pwa-ktt

Just clone, npm install, npm run dev and you'll see the resulting error in the console. 

### System Info

```Shell
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
    Memory: 16.36 GB / 31.89 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.18362.1593.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/adapter-static: ^2.0.1 => 2.0.1
    @sveltejs/kit: ^1.5.0 => 1.11.0
    svelte: ^3.54.0 => 3.56.0
    vite: ^4.0.0 => 4.1.4
```

### Severity

annoyance

### Additional Information

Annoyance as I'm just playing around here to see how things work, but could be more serious if this was a real project.

**Comment by s3812497** [comment]
You'll need to add a `src/routes/+layout.js` file with the line `export const ssr = false;`.
> You can turn any SvelteKit app, using any adapter, into a fully client-rendered single-page app (SPA) by disabling SSR at the root layout:

https://kit.svelte.dev/docs/single-page-apps

Below is a link to a working example.

https://stackblitz.com/edit/github-csyvke?file=src/routes/+layout.js

**Comment by dummdidumm** [comment]
This is just an info that `vite-plugin-svelte` did compile something for SSR (but there's nothing that _runs_ this). I don't think there's a sensible way to disable this during dev without degrading the DX when switching between rendering modes.
