### ISSUE TITLE
Allow file-based routes (e.g. `+about.page.svelte`)

### ISSUE THREAD

**Issue by jnordberg** [sveltejs/kit#9418]
### Describe the problem

As a user coming from pre-1.0 svelte kit I must say that I very much prefer the old routing system, for the sole reason that I find it really hard to navigate a svelte kit project when every file is named `+page.svelte/js`. Maybe I'm getting old but I keep squinting at my editor file tree to figure out where I need to go and it doesn't help that the subfolders often can't be descriptive either so I end up confused about which `[id]/+page.svelte` I'm looking for.

### Describe the proposed solution

If we where allowed to declare routes using filenames as well as folders, e.g. `+about.svelte` or `post/+[id].svelte` it would make it much easier to navigate a larger project.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
This was discussed at great length, and while there are some tradeoffs, we chose the API the way it is now to make the structure more consistent, easier to enhance and refactor, and more. Introducing another way to do the same thing would contradict that.
