### ISSUE TITLE
kit router is intercepting links outside of the mount node

### ISSUE THREAD

**Issue by john-michael-murphy** [sveltejs/kit#9419]
### Describe the bug

nytimes uses sveltekit to generate static graphics that we then inline all over our main website. for instance, this piece has three separate components built by sveltekit that we've inlined into a single page: https://www.nytimes.com/interactive/2023/03/09/us/track-california-storm.html

```html
<Header />
<Ad />
<SvelteKit />
<Recirc />
<Footer />
```

One issue that we're noticing with this pattern is that SvelteKit router intercepts link clicks from the _entire_ page, and not just the node it mounts. 

In the scenario above, for instance, the SvelteKit router intercepts clicks from the `<Header />`, which is managed by Nytimes.com and not sveltekit. 

### Reproduction

Head to: https://www.nytimes.com/interactive/2023/03/09/us/track-california-storm.html

Notice the second graphic on the page:

<img width="382" alt="Screenshot 2023-03-13 at 3 13 57 PM" src="https://user-images.githubusercontent.com/23287496/224807258-f3d0bcd5-c243-4187-af6b-8ef405e14402.png">

Scroll up and click on the nytimes logo. This is a relative link, `/` that should bring you to nytimes.com:
<img width="377" alt="Screenshot 2023-03-13 at 3 13 44 PM" src="https://user-images.githubusercontent.com/23287496/224807632-b4ba17e8-ab0f-485d-9ca7-6513bf9de0af.png">

Scroll down and notice how the second graphic now errors and the page does not navigate correctly:
<img width="379" alt="Screenshot 2023-03-13 at 3 14 12 PM" src="https://user-images.githubusercontent.com/23287496/224807992-c3531ce6-525e-462a-90f1-b3f65512e7c2.png">
 

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.86 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/bin/nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/bin/nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.3
```

```
"@sveltejs/adapter-static": "2.0.1",
"@sveltejs/kit": "1.8.5",
"vite": "4.1.4"
```
```


### Severity

serious, but I can work around it

### Additional Information

_No response_

**Comment by dummdidumm** [comment]
https://kit.svelte.dev/docs/configuration#embedded was designed for use cases like this - does this solve the problem?

**Comment by john-michael-murphy** [comment]
@dummdidumm Oh, wow! I totally missed this in the documentation. Thank you so much @dummdidumm!
