### ISSUE TITLE
npm run check reports types errors on implicitly generated types

### ISSUE THREAD

**Issue by arackaf** [sveltejs/kit#9422]
### Describe the bug

Recent updates to SvelteKit have started shipping automatically generated / inferred types. That means things like 

```js
export async function load({ url, parent, fetch, depends }) {
```

type just fine in the IDE. Unfortunately, the `npm run check` task does not appear to be aware of those types, and complains about implicit anys

<img width="820" alt="image" src="https://user-images.githubusercontent.com/11261266/225209843-660c865b-3412-4d54-b6e9-328bc3d451e7.png">

### Reproduction

None yet but I can whip something up if you all need it

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1007.36 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/Cellar/nvm/0.38.0/versions/node/v18.14.0/bin/node
    Yarn: 1.22.17 - /usr/local/Cellar/nvm/0.38.0/versions/node/v16.11.1/bin/yarn
    npm: 9.3.0 - ~/Documents/git/booklist/svelte-kit/node_modules/.bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-vercel: ^2.0.2 => 2.0.2 
    @sveltejs/kit: ^1.11.0 => 1.11.0 
    svelte: ^3.55.0 => 3.55.1 
    vite: ^4.0.3 => 4.0.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
Which version of `svelte-check` are you using? You need to install the latest to take advantage of this feature.

**Comment by arackaf** [comment]
@dummdidumm deepest apologies. I did upgrade SvelteKit to latest, but I didn't realize svelte-check was itself a separate dependency. It all works perfectly! :D

**Comment by arackaf** [comment]
@dummdidumm deepest apologies. I did upgrade SvelteKit to latest, but I didn't realize svelte-check was itself a separate dependency. It all works perfectly! :D
