### ISSUE TITLE
Data returned from `load` while rendering is not serializable: Cannot stringify arbitrary non-POJOs

### ISSUE THREAD

**Issue by BhagatAO** [sveltejs/kit#9429]
### Describe the bug

I was referring this example from the svelte kit doc to show the skeleton loader. It works properly in the dev mode but when I try the build, it shows the serializable error.

```
/** @type {import('./$types').PageServerLoad} */
export function load() {
  return {
    one: Promise.resolve(1),
    two: Promise.resolve(2),
    streamed: {
      three: new Promise((fulfil) => {
        setTimeout(() => {
          fulfil(3)
        }, 1000);
      })
    }
  };
}
```

 I am using @sveltejs/adapter-node.

### Reproduction

https://kit.svelte.dev/docs/load

### System Info

```Shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 50.58 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Safari: 16.1
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-node: ^1.2.2 => 1.2.2 
    @sveltejs/kit: ^1.11.0 => 1.11.0 
    svelte: ^3.56.0 => 3.56.0 
    vite: ^4.1.4 => 4.1.4
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
I can't reproduce this given the code snippet. Please provide a proper reproduction repo with steps how to reproduce it.

**Comment by BhagatAO** [comment]
Seems the issue was with pnpm local. So closing this ticket

**Comment by polaroidkidd** [comment]
this is still an issue with running pnpm locally. Really weird.

**Comment by michaltaberski** [comment]
Did you find a workaround the issue?

**Comment by ghostdevv** [comment]
We would need a minimal reproduction to try and figure out what's going on :pray:
