### ISSUE TITLE
Throw to a svelte component from hooks

### ISSUE THREAD

**Issue by fcrozatier** [sveltejs/kit#9439]
### Describe the problem

My use case is error management for protected routes. As discussed in #6315, the best practice is to place the protection logic in `hooks.server.ts`. Let's say I want to distinguish between different protection levels (`verified`, `premium`, `admin` etc). There are currently two options:

1. `throw error(403, {code: 'verified'})` from `hooks.server`
Then the `error.html` file is served and it's hard to customize, there is no tooling available:
- I will struggle to use my Tailwind classes by finding a way to point to the processed css files
- I will have to use raw js to manipulated the DOM to distinguish between my hard-coded cases (`verified` etc.) and show relevant divs and links.

2. `throw redirect(303, "/protected?code=verified")` from `hooks.server`
This way I can use a svelte component, styling is easy, and I can access my error codes from `app.d.ts`
- But isn't is weird to return 303 instead of 403 ? (and since it's a server redirect it will just end up being a 200 to the `/protected` route)
- Also I have to manually write the error code in the redirect url which doesn't feel very idiomatic

Is there a better way?

### Describe the proposed solution

Maybe a `+protected.svelte` component (or with any other name...) on the root level where a call to `error` inside `hooks` would lead? Or maybe make `error` lead to the root `+error.svelte`?

Which would basically allow to use `throw error(403, {code: "verified"})` from `hooks` in a more manageable way and would return the correct 403 error status

### Alternatives considered

Option 2 seems better for now

### Importance

would make my life easier

**Comment by 7nik** [comment]
I'd go with 2nd solution: the status code doesn't matter much if you respond with a HTML page - the user anyway won't see the status code.

**Comment by dummdidumm** [comment]
A redirect is the correct solution here - it's what you're doing, you don't allow people to visit the original page, you want them to log in somewhere else.
