### ISSUE TITLE
https://kit.svelte.dev/docs/ returns a 404

### ISSUE THREAD

**Issue by danielzting** [sveltejs/kit#9449]
### Describe the bug

It seems like the /docs route does not normalize trailing slashes, even though trailing slashes work on the other pages I've tried.

### Reproduction

Paste [https://kit.svelte.dev/docs/](https://kit.svelte.dev/docs/) (with trailing slash) into browser

### Logs

```Shell
`Failed to load resource: the server responded with a status of 404 ()` in DevTools console
```

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 16.76 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /usr/local/bin/node
    npm: 9.2.0 - /usr/local/bin/npm
    Watchman: 2023.01.16.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/adapter-vercel: ^1.0.5 => 1.0.5 
    @sveltejs/kit: ^1.0.0 => 1.0.1 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.1
```

### Severity

annoyance

**Comment by s3812497** [comment]
SvelteKit is currently matching `/docs/` to the route `/docs/[slug]` instead of `/docs`.
However, in `dev` mode it matches `/docs/ to `/docs`.
Should we change how the built version behaves to match dev mode?

**Comment by amr3k** [comment]
It always bothers me to type `kit.svelte.dev/docs` and get a 404.
Someone please fix this
