### ISSUE TITLE
onDestroy is called during SSR?

### ISSUE THREAD

**Issue by asv1** [sveltejs/kit#945]
**Describe the bug**
Error 500 ```window is not defined``` is showed.

**Logs**
Please include browser console and server logs around the time this bug occurred.

**To Reproduce**
Repo: [https://github.com/asv1/svelte_bug_4](https://github.com/asv1/svelte_bug_4)

**Expected behavior**
No error must be show. onDestroy must not be called during SSR?

**Stacktraces**
**Information about your SvelteKit Installation:**
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 13.24 GB / 15.93 GB
  Binaries:
    Node: 14.16.0 - d:\portable\node\node.EXE
    npm: 6.14.11 - d:\portable\node\npm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.771
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```
**Severity**
Bug makes impossible to use browser related stuff in onDestroy hook.

**Additional context**

**Comment by Conduitry** [comment]
This is the intended behavior - https://svelte.dev/docs#onDestroy - The idea is that you may have some cleanup to do so as not to cause a memory leak. You'll have to wrap browser-only code in an appropriate check.

**Comment by steve-taylor** [comment]
This one's a bit of a head scratcher. Is there nothing that's called specifically before a component is unmounted? It seems like a massive oversight.

**Comment by alancwoo** [comment]
> Following code does not cause `ReferenceError: alert is not defined` in SSR.
> 
> ```
> <script lang="ts">
>   import { browser } from '$app/env';
>   import { onDestroy } from 'svelte';

Just a note that it's now `import { browser } from '$app/environment';` as per https://kit.svelte.dev/docs/modules#$app-environment
