### ISSUE TITLE
Cannot run the example app from create-svelte app or build current app

### ISSUE THREAD

**Issue by samiam376** [sveltejs/kit#9451]
### Describe the bug

I followed the steps to create a svelte example app but when I run `npm run dev -- --open`

I receive the following error

`
✘ [ERROR] Expected "," in JSON but found end of file

    ../../../package.json:15:0:
      15 │
         │ ^
         ╵ ,

failed to load config from /Users/samsheridan/Documents/Code/myapp/vite.config.js
error when starting dev server:
Error: Build failed with 1 error:
../../../package.json:15:0: ERROR: Expected "," in JSON but found end of file
    at failureErrorWithLog (/Users/samsheridan/Documents/Code/myapp/node_modules/esbuild/lib/main.js:1636:15)
`

I see the same error when trying to build/preview my existing projects as well

### Reproduction

run 
`npm create svelte@latest myapp`

then choose the example project and use the default options. Then run `npm install` and ``npm run dev -- --open`

### System Info

```Shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 77.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.2 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 111.0
    Safari: 15.4
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.12.0
    svelte: ^3.54.0 => 3.57.0
    vite: ^4.0.0 => 4.2.0
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
This isn't happening for me. What's in your `package.json`? It sounds like it was corrupted in some way.

**Comment by samiam376** [comment]
@Conduitry I got it working - a stray package.json in a parent directory was broken and causing the issue
