### ISSUE TITLE
Full layout reset (ignore the root layout)

### ISSUE THREAD

**Issue by adiguba** [sveltejs/kit#9455]
### Describe the problem

Currently we can reset to the "root" layout using `+page@.svelte` or `+layout@.svelte`.
This will use the `routes/+layout.svelte` as parent layout, ignoring all intermediate layouts.

But there is no way to completely ignore this root layout !

The current solution for this, as stated in the documentation, is to use a `(group)` :
https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-page

It's fine when we build our route tree in advance for that.
But it can be painful in an existing app that wouldn't use this structure.

For example, If my app is currently like that : 
```
    src/routes/
    ├ other-routes
    │ ├ path
    │ └ +page@.svelte      // reset to root layer (with header/footer)
    │ ├ ...
    │ └ +layout.svelte 
    ├ item/
    │ ├ [id]/
    │ │ ├ embed/
    │ │ │ └ +page@.svelte  // reset to root layer, but I want an empty layer
    │ │ └ +page.svelte
    │ └ +layout.svelte
    └ +layout.svelte       // root layer, with app header/footer...
```

Here my `/item/[i]/embed` route will use the root layer, used by all page of my applications, but I want an empty layout !
I could create a `(app)` group in order to fix that, like in the documentation's example, but it will have some breaking impacts on my app : 

```diff
src/routes/
-   ├ other-routes
-   │ ├ path
-   │ └ +page@.svelte      // reset to root layer (with header/footer)
-   │ ├ ...
-   │ └ +layout.svelte 
-   ├ item/
-   │ ├ [id]/
-   │ │ ├ embed/
-   │ │ │ └ +page@.svelte  // reset to root layer (empty)
-   │ │ └ +page.svelte
-   │ └ +layout.svelte
-   └ +layout.svelte       // root layer, with app header/footer...
+   ├  (app)               // New directory
+   │ ├ other-routes
+   │ │ ├ path
+   │ │ └ +page@(app).svelte    // reset to root layer (with header/footer) NEED TO BE RENAMMED !
+   │ │ ├ ...
+   │ │ └ +layout.svelte 
+   │ │ ├ ...
+   │ ├ item/
+   │ │ ├ [id]/
+   │ │ │ ├ embed/
+   │ │ │ │ └ +page@.svelte    // reset to root layer
+   │ │ │ └ +page.svelte
+   │ │ └ +layout.svelte
+   │ └ +layout.svelte        // (app) root layer, with app header/footer...
+   └ +layout.svelte          // root layer, empty
```

* Lots of files will be moved !
* It will broke all code based on route.id
* I need to update all my existing layout reset from `+page@.svelte` to `+page@(app).svelte`, because here I want my app layout and not an empty layout...

Why we need to revamp the whole app for something so basic ?

### Describe the proposed solution

A new special layout reset, by using a specific syntax like `+page@@.svelte` or `+layout@@.svelte` (note the double `@`).

This would consist of using an empty root layout, completely ignoring the `+layout.svelte/js/ts` files from the routes directory.

=> And now we have a single change on the current page :

```diff
    src/routes/
    ├ other-routes
    │ ├ path
    │ └ +page@.svelte
    │ ├ ...
    │ └ +layout.svelte 
    ├ item/
    │ ├ [id]/
    │ │ ├ embed/
-   │ │ │ └ +page@.svelte
+   │ │ │ └ +page@@.svelte  // reset to an EMPTY layer
    │ │ └ +page.svelte
    │ └ +layout.svelte
    └ +layout.svelte       // root layer, with app header/footer...
```

### Alternatives considered

Continue to use `(group)`

### Importance

nice to have

**Comment by Frank-D** [comment]
+1 
(I'm in the exact same situation, and was considering refactoring my entire routes tree exactly like described above, however I'm scratching my head right now wondering if that is really worth it, since I'm afraid I won't need too many pages which require to skip the root layout, so that would be a bummer to introduce a new root group - such as (app) as per the above - and move everything under, only to make room for a couple of those pages (+- static in my case) that require to skip my main/root layout...)

**Comment by NormandoHall** [comment]
+1
Same, it is crazy to change all the organization paths to use (group) only for reset the layout in some route.

**Comment by Rich-Harris** [comment]
Closing for the reasons given in https://github.com/sveltejs/kit/pull/9472#issuecomment-1490861458.

Moving lots of files isn't a problem — if you use `git mv` then you won't even lose git history, and PRs etc will remain mergable. Same goes for renaming existing `+page@.svelte` files — this doesn't feel like a dealbreaker. `route.id` code _will_ need to be changed (though I'm curious to know how you're using `route.id`? I've found it to be quite rare to use it), and this reminds me that it would be nice to add a better type than `string` to that property.

As an alternative, you can always do this sort of thing:

```svelte
{#if route.id.includes('/embed/')}
  <slot />
{:else}
  <main>
    <Header/>
    <slot />
    <Footer />
  </main>  
{/if}
```

**Comment by adiguba** [comment]
Currently I'm not using route.id with Sveltekit.

But on websites under another techs I used something similar to identify pages for stats/analytics (routes had a unique ID, but localized URIs).

Thanks for your response.

**Comment by newsve** [comment]
> if you use git mv then you won't even lose git history,

This isn't true, you lose it, just google yourself "does git mv preserve history".

> As an alternative, you can always do this sort of thing:...

which isn't type-safe and silently breaks on folder changes

> Moving lots of files isn't a problem — 

I would say, it is, and takes flow and fun out of coding and creates a lot of hassle

**Comment by dummdidumm** [comment]
> Fwiw, I am not into the feature of OP, rather would like to have a more flexible layout API, which allows to break out of parent's or a specific layouts only, and not only root's.

This is possible. If you have a route like `foo/bar/baz/+page.svelte` and each segment has a layout, you can skip the baz layout or the baz and bar layout by doing `+page@bar.svelte` or `+page@foo.svelte`. Only thing you can't do is skip the root layout or skip a layout in-between, like only skipping the bar layout.

**Comment by newsve** [comment]
> you can skip the baz layout or the baz and bar layout by doing +page@bar.svelte or +page@foo.svelte

Ok, this is very nice, thanks for letting me know! 🙂 In which part of the docs is `page@.svelte` specced?

**Comment by rogadev** [comment]
> +1 Same, it is crazy to change all the organization paths to use (group) only for reset the layout in some route.

It's really not. Think about a page you may want to print. Do you need a navbar? Footer? No. Just the page, as-is, without any layout.

Why was this closed? This is kind of a big deal that SvelteKit can't do this, IMHO. It's inflexibilities like these that make me pull my hair out when trying to use SvelteKit. It makes me want to reroll back to Nuxt every time. At some point, I'll stop reaching for SK completely and just build everything in Nuxt if these issues don't get fixed.

**Comment by laneme** [comment]
> It makes me want to reroll back to Nuxt every time. At some point, I'll stop reaching for SK completely and just build everything in Nuxt if these issues don't get fixed.

@rogadev Its understandable you (and other users) may want a feature that sveltekit decided not to work on. We should respect that and not act like they owe us a thing and nuxt is their business competitor and they should keep all their customers happy.

If you really believe a feature should be implemented, provide the sveltekit team with convincing use cases. I'm sure they will take a second look.

**Comment by rogadev** [comment]
> @rogadev Its understandable you (and other users) may want a feature that sveltekit decided not to work on. We should respect that and not act like they owe us a thing and nuxt is their business competitor and they should keep all their customers happy.

No expectations were made. I am simply offering candid and straightforward feedback. I am fortunate to be in a position where I can select the framework that best suits each individual project. My comments are intended to elucidate the rationale behind my choices in this context. At no point did I suggest an obligation on their part, but rather, I aimed to articulate the implications their decisions have on my experience as a user.

> If you really believe a feature should be implemented, provide the sveltekit team with convincing use cases. I'm sure they will take a second look.

I feel strongly that the original post was sufficiently detailed and I support the sentiments of the original poster, and I fully endorse the points raised by the original author, as evidenced by my participation in this discussion. There are multiple, readily apparent reasons why this feature is important, such as the creation of printable report views that exclude user interface elements like the navigation bar. The current layout system in SvelteKit unnecessarily complicates what should otherwise be a rather straightforward task. If they borrowed from other frameworks that have already learned this lesson it would be a significant improvement.

Lastly, I would like to emphasize the importance of maintaining a professional discourse, especially when addressing the viewpoints of others. The original contributor invested considerable time and effort into presenting a well-argued case. Attempting to discredit or diminish the validity of others concerns by way of gaslighting is poor form and undermines the very purpose of such discussion threads, which are designed to be platforms for constructive debate among developers. Telling people they don't have valid concerns is not in any way constructive.

**Comment by muthiyalu** [comment]
I agree with @rogadev here , it seems weird that such a basic requirement which is supported in almost every other framework needs such a discussion. IMHO when it comes these matters nothing can compare to the laravel community. Having built apps in many framework and languages (with some of them running in prod for large enterprises) including spring, rails, django, express, vue etc , Sveltekit is a such a breath of fresh air. But the community should listen to why someone may be asking for a feature , especially one that been taken for granted for years in most framework.

**Comment by lukecarbis** [comment]
I agree that this would be a great addition to SvelteKit. I'm also disappointed it's not easily possible.

My workaround isn't perfect, but suits me, and might suit others:

I just created the route I wanted in the `static` directory (e.g. `/static/privacy-policy/`) and put an `index.html` file there. This will just skip Svelte entirely, which is a bummer if you want to include other components. But it did the trick.

**Comment by Salman2301** [comment]
> Closing for the reasons given in [#9472 (comment)](https://github.com/sveltejs/kit/pull/9472#issuecomment-1490861458).
> 
> Moving lots of files isn't a problem — if you use `git mv` then you won't even lose git history, and PRs etc will remain mergable. Same goes for renaming existing `+page@.svelte` files — this doesn't feel like a dealbreaker. `route.id` code _will_ need to be changed (though I'm curious to know how you're using `route.id`? I've found it to be quite rare to use it), and this reminds me that it would be nice to add a better type than `string` to that property.
> 
> As an alternative, you can always do this sort of thing:
> 
> ```svelte
> {#if route.id.includes('/embed/')}
>   <slot />
> {:else}
>   <main>
>     <Header/>
>     <slot />
>     <Footer />
>   </main>  
> {/if}
> ```

Yeah... but that's what filebased routing suppose to solve?. It will be nice if svelte can support skipping the root layout too. idk why it enforce root layout but you can skip other layouts. Any alternative its feels like a ugly workaround. Please consider supporting it. 

> Will be nice, if we can read a file and see that file is skipping routes

**Comment by TheStrongest** [comment]
I just had this issue a while ago. It seemed like a basic feature to have for a frontend framework. I could. I don't understand why this was skipped, and why it hasn't been implemented in the new svelte 5.

Please guys consider this feature, it would be breathe of fresh air. Svelte's selling point is its ease/simplicity.

**Comment by hockeymikey** [comment]
I hate that this was closed. There is really no reason for this. Why should I create a group just to achieve this effect on one single page? It's silly and foolish. Rethinking my usage of sveltekit too.

**Comment by Abdk4Moura** [comment]
I agree with guys here. It's so trivial I think it's unnecessary to dismiss that as not tangible especially since it makes everything easy. The grouping thing feels too complex and overkill for this use case. 

If you can skip parent layouts, why make an exception for the root? I can't think of any good reason to make this exception.

**Comment by IqroNegoro** [comment]
why this closed as not planned lol

**Comment by mklnz** [comment]
I spent hours trying to figure this out and I wish it could be easier as well. There should be some way to completely use a different layout from the root for some routes.

**Comment by t1u1** [comment]
> Moving lots of files isn't a problem

It may not be a technical problem, but it is a DX problem. In the middle of shipping a simple feature if you need to reorganize the whole source code, tell all co-workers to update their branches (sometimes old ones) then, to the say the least, it's quite sub-optimal.

It would still be worth it if there were no easy solutions. In this case, it looks like a simple change to the naming convention could solve it. In terms of implementation, I would imagine that the framework could have a hidden empty root layout by default, one that the user specified root layout is a child of. And the full layout reset would simply reset to that meta root layout with the same logic as the usual reset does.

**Comment by derekmoeller** [comment]
> Closing for the reasons given in [#9472 (comment)](https://github.com/sveltejs/kit/pull/9472#issuecomment-1490861458).
> 
> Moving lots of files isn't a problem — if you use `git mv` then you won't even lose git history, and PRs etc will remain mergable. Same goes for renaming existing `+page@.svelte` files — this doesn't feel like a dealbreaker. `route.id` code _will_ need to be changed (though I'm curious to know how you're using `route.id`? I've found it to be quite rare to use it), and this reminds me that it would be nice to add a better type than `string` to that property.
> 

I had this problem, and Rich's solution works well. It was pretty painless to just do git mv the existing app into (app) and then create my second (group) directory. git history is retained. (The only time it's not retained is if the file's contents change too much at the same time as moving, so just commit everything, then do git mv, and commit again.)

**Comment by lukas-buergi** [comment]
The group workaround doesn't work when you want to have, let's say /A have the normal layout but /A/B should not have the root layout.

**Comment by takeseem** [comment]
why this closed as not planned lol

**Comment by gregg-cbs** [comment]
This is why programmatic composition of routes will always be king.

```ts
const router = createRouter({
  routes: [
    { 
      path: '/', 
      component: WebsiteLayout, 
      children: [
        { path: 'home', component: HomePage },
        { path: 'about', component: AboutPage }
        { path: 'contact', component: ContactPage }
      ]
    },

    {
      path: '/dashboard', 
      component: DashboardLayout,
      children: [
        { 
          path: 'orders',
          component: OrderLayout,
          children: [
            { path: ':orderid', component: OrderPage }
          ]
        }
      ]
    },

    {
      path: '/both-layouts', 
      component: WebsiteAndDashboardLayout,
      children: [
        { path: 'some-route', component: SomePage }
      ]
    }
  ]
})
```

File based routing will always have limitations and its assuming a route and folder structure onto the programmer. Programmers should be able to compose routes the way they feel. Im not sure why Svelte defend this hierarchical router when Vue has made a solid programmatic router that can be copied. Maybe its an SSR thing, but if a programmatic router ever comes into svelte it will change the game.

**Comment by nightly** [comment]
> Closing for the reasons given in [#9472 (comment)](https://github.com/sveltejs/kit/pull/9472#issuecomment-1490861458).
> 
> Moving lots of files isn't a problem — if you use `git mv` then you won't even lose git history, and PRs etc will remain mergable. Same goes for renaming existing `+page@.svelte` files — this doesn't feel like a dealbreaker. `route.id` code _will_ need to be changed (though I'm curious to know how you're using `route.id`? I've found it to be quite rare to use it), and this reminds me that it would be nice to add a better type than `string` to that property.
> 
> As an alternative, you can always do this sort of thing:
> 
> {#if route.id.includes('/embed/')}
>   <slot />
> {:else}
>   <main>
>     <Header/>
>     <slot />
>     <Footer />
>   </main>  
> {/if}

This is the approach I took. 

However, it's not the most elegant and would be nicer if the framework had this as a built-in option. Mainly due to the fact that I think the framework could handle **preloading issues** that arise as a result in a more systematic fashion.
