### ISSUE TITLE
(throw) Redirect doesn't work on full page loads

### ISSUE THREAD

**Issue by Devr-pro** [sveltejs/kit#9462]
### Describe the bug

Redirect thrown in `load` functions work precisely and expectedly when navigated to that respective page/route through clicking the link/a-tag navigation, but weirdly that isn't the case when we full load the page or reload the page, it kind of stops working or breaks the app.
My reproduction kind of demonstrates that.(try changing the logic of redirect & go to `/dashboard` through entering the url and not by clicking the button  )

### Reproduction

[demo-app-repo](https://github.com/Devr-pro/redirect-issue-repro) and the [reproduction website](https://redirect-issue-repro.netlify.app/)

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 30.63 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.3 => 1.0.3 
    @sveltejs/adapter-netlify: ^1.0.5 => 1.0.5 
    @sveltejs/kit: ^1.12.0 => 1.12.0 
    svelte: ^3.57.0 => 3.57.0 
    vite: ^4.2.0 => 4.2.0
```

### Severity

serious, but I can work around it

### Additional Information

I use github codespaces , kind of suspicious it has something to do with this but not sure.
Sorry in advance if this a poor one 😅, thanks!

**Comment by dummdidumm** [comment]
You're using redirect status code 300. This means that the user agent (aka the browser) has to somehow chose the right destination, which in practise I don't know how it works frankly. It works when navigating via button click because the redirect status code has no meaning in that situation.

Choose a more appropriate status code and it should work as expected.

**Comment by Devr-pro** [comment]
> You're using redirect status code 300. This means that the user agent (aka the browser) has to somehow chose the right destination, which in practise I don't know how it works frankly - but apparently the browser does nothing in this case. It works when navigating via button click because the redirect status code has no meaning in that situation.
> 
> Choose a more appropriate status code (302, 303 or 307) and it should work as expected.

Oh, okay I'll try the things out

**Comment by Devr-pro** [comment]
@dummdidumm  hey, thanks it worked, but I kind of explored the different status code and saw that 301 & 308 which are permanently moved redirect status codes do work but even if I change it to anything else (bcoz If I had done it unknowningly/mistakenly) then it still redirects me, no matter what condition or status code is there  it redirects everytime, to solve this I had to delete the build& .svelte-kit folder and it worked fine , is this a bug? It might need to be reviewed

**Comment by Conduitry** [comment]
If you had previously sent a 301 Moved Permanently, the browser will cache that. It will perform the redirect without even calling the server unless you clear the browser's cache.

**Comment by Devr-pro** [comment]
> If you had previously sent a 301 Moved Permanently, the browser will cache that. It will perform the redirect without even calling the server unless you clear the browser's cache.

Oh, thanks I missed that one.
