### ISSUE TITLE
Populate event.platform data during dev with Vite plugins

### ISSUE THREAD

**Issue by kgallimore** [sveltejs/kit#9464]
### Describe the problem

Using a custom node server with middleware, as of right now only running the prod build actually allows the populated data to be exposed under event.platform inside of hoosk.server.ts. This may be a vite issue but I asked both in the vite and svelte discord servers and no one gave a response. I am also assuming that this is not a bug but just not an implemented feature, and I have also tried adjusting the order the plugin is executed.

### Describe the proposed solution

Passing a middleware as a vite plugin under dev should populate the same event.platform object as it does when running a custom node server with that middleware.

### Importance

nice to have

### Additional Information

Here is a repo to demonstrate how dev does not populate event.platform, but prod does. I have an example of both express and connect  under expressServer.js and connectServer.js
https://github.com/kgallimore/Sveltekit-SSPI
Running dev will log how the req.sso object is being populated in the plugin, but is not found in event.platform. Running either server will show that it is available.
Thanks!

**Comment by Conduitry** [comment]
This would fall under #2304. We want to find a way to make this work across all adapters, not just the Node one.
