### ISSUE TITLE
SECURITY - restrict `server` folder in deployment documentation

### ISSUE THREAD

**Issue by eytanProxi** [sveltejs/kit#9477]
### Describe the problem

I tried to deploy sveltekit with Plesk+nodejs adapter and it works great !

But I discovered that event if nginx redirect all request to sveltekit, if you try `https://mywebsite.com/server/chunks/private-ade19f8d.js`, it gives you the content of the file ! This mean that all your secrets are accessible from the web !!!

### Describe the proposed solution

Since this is a big security flaw (not directly related to SvelteKit but rather to its use), I think we should add a page in the documentation that indicates that you really need to block access to /server.

For example, this is the nginx config I added for Plesk :

```nginx
location ~ /(server|client|tmp|node_modules|env\.js|handle\.js|shims.js|index\.js) {
    deny all;
    return 404;
}
```

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment]
After careful consideration we're closing this issue as non-actionable. Documenting this won't help, rather confuse most people - or rather those people who actually read this close enough. This feels like something that should be documented on the hosting side (like; here's how you secure your server files in Plesk). The fact that other don't observe this behavior hint to me this is also not a common problem.
