### ISSUE TITLE
`svelte-kit dev` does not recognize occupied ports on Windows

### ISSUE THREAD

**Issue by emme1444** [sveltejs/kit#948]
**Describe the bug**
When running `svelte-kit dev`, on Windows, SvelteKit does not throw an error for an already occupied port. Instead what happens is SvelteKit prints the "welcome" message, when trying to reach the started dev server it is of course shadowed by the process already occupying that port.

**To Reproduce**

On a Windows machine:
1. Make sure some service is running on port `3000`.
2. Make a new directory and `cd` into it.
2. `npm init svelte@next`
3. `npm i`
4. `npm run dev` ⬅ This should throw, but doesn't!

**Expected behavior**

An error should be thrown to indicate that the port the dev server is trying to launch on is already in use by another process.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz 
    Memory: 16.23 GB / 23.92 GB
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5
```
</details>

**Severity**

Mildly annoying, but for many users nonetheless.

**Additional context**
I poked around in the source for the `svelte-kit` cli. I noticed that you guys use the `port-authority` package's `blame` function. According to [the `port-authority` documentation](https://www.npmjs.com/package/port-authority#additional-functions), under _Additional functions_, this function only supports Unix-like operating systems.

Maybe a better fix is for this, would be to add support for this in `port-authority`, just thought this should be tracked.

Thanks for this awesome framework!

**Comment by Conduitry** [comment]
I think this is just how Windows networking works, at least in Node. I'm able to listen on port 3000 on 0.0.0.0 in one process and on port 3000 on 127.0.0.1 in another process, and Windows is fine with this. By default, SvelteKit will serve on 127.0.0.1:3000 - and if I already have something that specifically bound to that port on that interface, I will get an EADDRINUSE error when I try to run `npm run dev`.

Do you know of something different that SvelteKit could be doing here?

**Comment by emme1444** [comment]
Ah! I see! I wasn't aware of the fact that that was how it worked.

> Do you know of something different that SvelteKit could be doing here?

Now that I'm aware of how this works, I can't seem to figure out how one could go forward with this. Let's leave it at that then? Or was there some other information you were hoping to get?

**Comment by benmccann** [comment]
Ok, it sounds like there isn't anything you want to be fixed still then, so I'll go ahead and close this

**Comment by MvnTruong** [comment]
Please re-open. Vite is able to detect if port 3000 is already in use, if so, and incrementally checks until an open port is found; and this works on Windows 10. Since SvelteKit is using Vite under the hood, there's no reason why SvelteKit shouldn't be able to do this too

**Comment by benmccann** [comment]
Yes, I think it's confusing that the Vite server options didn't do anything while the others did. That's been fixed in https://github.com/sveltejs/kit/pull/2232, so with the next release you can now configure this setting. Thus I'm leaving this issue close as it's been solved
