### ISSUE TITLE
feat: Guard function to protect routes (+guard.server.js)

### ISSUE THREAD

**Issue by adiguba** [sveltejs/kit#9482]
### Describe the problem

Actually it's quite difficult and confusing to correctly protect routes on a Sveltekit application.
Unlike many other concepts like page, layout, form or endpoint, Sveltekit does not really offer us a clear solution for that.

Using a `+layout.server.js` seems the simplest solution, but wrong because of parallel loading which can leak data.
Or you must have a `+page.server.js` on all pages with an `await parent()` at the beginning to ensure that the layout is executed.
But it is repetitive and a source of error/omission...
And this solution does not protect form's actions neither server enpoints !
=> **NOT RECOMMENDED !!!**
  
Using `hooks.server.ts` is the current recommended solution.
It's mostly correct with a redirect to a login page *(although personally I find it not very graceful)*.
But on CSR it can miss some page without data-loading, and it's a little buggy if you want to manage that via HTTP 401 or 403 errors *(which seems the cleanest way to me)*, because the error handling is different between SSR and CSR : 
* On SSR the hook will completely prevents the page from being rendered, and it will return the `error.html` file.
* On CSR the page loading will fail, and the appropriate `+error.svelte` will be used.
What makes that we will obtain a different page according to how we load it
=> **NOT OPTIMAL**

### Describe the proposed solution

A solution would be to introduce two new route files :  `+guard.server.js` and `+guard.client.js`.

#### Server Side : 

`+guard.server.js` will be executed on server before any execution of an element of the sub-route (layouts, actions, pages or endpoints).
This will allow to check the auths and throw an error or send a redirect :
```javascript
/// +guard.server.js
import { error } from '@sveltejs/kit'

export function guard(event) {
    // We check the user (preloaded on the locals) :
    if ( event.locals.user && event.locals.user.role === 'admin' ) {
        throw error(403, "Please login");
    }
}
```

=> This would be equivalent to have a call to `guard()` at the beginning of all `load()`, actions or endpoints function.
So on SSR when guard will throw an error, the rendering will fail and use the correct `+error.svelte`.

On CSR all requests to a guarded route will require a server call to validate and process, that should produce an equivalent result.

`guard()` should also be executed before all others tasks (load(), actions, page, server endpoint) to ensute it can be executed.

---

#### Client Side :

On the client side, an optional `+guard.client.js` could allow us to avoid some useless queries.

For example, if the user is not logged-in, we can throw a 403 error on client-side without sending any request to the server :
```javascript
/// +guard.client.js
import { error } from '@sveltejs/kit'
import { user } from '$lib/client/user-store.js';

export function guard(event) {
    if ( get(user) === null ) {
        // no user auth at all - server validation is useless
        throw error(403, "Please login");
    }
}
```

### Alternatives considered

hooks.server.js with redirect

### Importance

nice to have

### Additional Information

Maybe we can also have an "universal" guard() function, but I don't see any interest or concrete use case for that.

**Comment by pilcrowOnPaper** [comment]
I still think `page.server.ts` and `layout.server.ts` are the place to add auth guards. Assume `locals` is typed as so:

```ts
type Locals = {
  user: User | null;
}
```

Checking for user is part of validation process for the load function and as such should be part of it:

```ts
export const load = async (event) => {
  if (!event.locals.user) throw redirect();
  const data = await getDataUsingUserId(event.locals.user.userId);
  return {
    user: event.locals.user
  };
};
```

Same goes for form actions. Even if you using the proposed solution, the code will still look exactly the same since you have type-check/validate `locals.user`, unless you can return data from an auth guard handler and access it.

Route specific middlewares may be more appropriate as a general solution however.

**Comment by ivanhofer** [comment]
This is the same problem as described in #6315

**Comment by adiguba** [comment]
@pilcrowOnPaper : yes `+page.server.ts` and `+layout.server.ts` is the best way, but the check must be added to all routes in order to avoid some and this can lead to omissions...
The principle of a `+guard.server.js` would be to have a single file for ALL pages/endpoints of a subtree.


@ivanhofer : I didn't see it.
I mark this as duplicate...
