### ISSUE TITLE
jsx support

### ISSUE THREAD

**Issue by qiuqfang** [sveltejs/kit#9490]
### Describe the bug

In the script tag I imported a component and saved it in a variable. Syntax error was reported

### Reproduction

```
<script>
	import { page } from '$app/stores';
	import '../app.css';

	import SettingsIcon from '~icons/material-symbols/settings';

	const routes = [
		{ id: '/', name: 'Home' },
		{ id: '/about', name: 'About' },
		{ id: '/settings', name: 'Settings', icon: <SettingsIcon /> }
	];
</script>
```

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 106.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
    Safari: 16.3
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.13.0 
    svelte: ^3.54.0 => 3.57.0 
    vite: ^4.2.0 => 4.2.1
```

### Severity

serious, but I can work around it

**Comment by ramonmalcolm10** [comment]
You can use `<svelte:component>`

`const routes = [{id: '/settings', name: 'Settings', icon: SettingsIcon}];`

`<svelte:component this={routes[0].icon}/>`

**Comment by qiuqfang** [comment]
> You can use `<svelte:component>`
> 
> `const routes = [{id: '/settings', name: 'Settings', icon: SettingsIcon}];`
> 
> `<svelte:component this={routes[0].icon}/>`

Yes, I found this syntax in the svelte documentation

**Comment by qiuqfang** [comment]
> 

right
