### ISSUE TITLE
Template index file is missing page <title>

### ISSUE THREAD

**Issue by bamadesigner** [sveltejs/kit#952]
**Describe the bug**
The included template index file (with "Hello World!" and the counter example) does not have a page <title>.

This causes an accessibility issue.

**To Reproduce**
Download the kit and run the dev environment. Open the app's index route.

**Expected behavior**
For the HTML output to include a <title></title>.

**Severity**
As this is an accessibility issue, it is blocking some users.

**Additional context**
I have a PR ready and will submit after I create this issue.

**Comment by bamadesigner** [comment]
I submitted pull request #953 to remediate this issue.

**Comment by antony** [comment]
Thanks :)

**Comment by bamadesigner** [comment]
You're most welcome!
