### ISSUE TITLE
 Confused by migration guide. Are DELETE and other actions still valid inside +page.server.js?

### ISSUE THREAD

**Issue by jsilveira** [sveltejs/kit#9523]
### Describe the problem

I'm trying to migrate an old Svelte Kit project following the "migration guide" and when I thought I was almost done, I came across this error:

`Error: Invalid export 'DELETE' in src/routes/(...)/+page.server.js ('DELETE' is a valid export in +server.js)`

And I found it very confusing, because the migration guide says:

> Update +page.server.js
> This file, previously referred to as a page endpoint, exists to provide your page with data from the server. The data retrieval function was rena med from GET to load. **The other handlers still correspond to HTTP methods — POST, PUT, PATCH and DELETE.**

So I'm really confused about this error. I have looked at the official docs of Svelte Kit and even the source code of kit, leaving me under the impression that `+page.server.js` are not allowed to export those actions, but the migration guide is not saying that. So is the guide wrong or outdated? 

### Describe the proposed solution

Fix the migration guide if it's wrong. This is my second migration of a SvelteKit site and the process for me has been painful, confusing and frustrating. The documentation is really poor and fragmented. 

### Importance

i cannot use SvelteKit without it

**Comment by jhwz** [comment]
Nah they need to be moved to +server.js, +page.server.js should only export a load function and any page options

**Comment by jsilveira** [comment]
Thanks, I appreciate the quick response. However, I think this highlights even more what a mess the migration guide currently is. I will create a separate issue to discuss this as a whole. I love Svelte and Svelte Kit, and I'm really thankful for all the great work you are doing, but I also think the svelte kit community and early adopters deserve a clear migration process and maybe those of you who are involved in Kit's day to day development are not aware of how painful it is right now to reconstruct the current state of things.
