### ISSUE TITLE
[adapter-node] Get original host from forwarded request

### ISSUE THREAD

**Issue by jaylinski** [sveltejs/kit#9529]
### Describe the problem

As a developer, I want to be able to get the original `Host` from forwarded requests in adapter-node, so I can change the logic of my application based on the original `Host`.

### Describe the proposed solution

Implement `getOriginalHost()`-method in adapter-node handler, similar to `getClientAddress()`.

The de-facto standard header `X-Forwarded-Host` can be used for this:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

### Alternatives considered

Developers could implement their own middleware via `hooks.server.js`. It can process the `X-Forwarded-Host`-header and add the host origin to the current `event`.

### Importance

would make my life easier

### Additional Information

If you think this feature is useful, I can open PR for adapter-node.

**Comment by Conduitry** [comment]
https://kit.svelte.dev/docs/adapter-node#environment-variables-origin-protocol-header-and-host-header Does the `HOST_HEADER` env var not do what you need?

**Comment by jaylinski** [comment]
Yep, I should try and read the docs more carefully.
