### ISSUE TITLE
Pass result of getContext to pages or make headers available in pages

### ISSUE THREAD

**Issue by kahverengi001** [sveltejs/kit#955]
**Describe the bug**
`Context` parameter in `load` function event in `context="module"` returns {} even you set the `getContext` method in hooks/index.js.

**To Reproduce**
To reproduce this issue apply these codes:
`hooks/index.js`
```
/** @type {import('@sveltejs/kit').GetContext} */
export async function getContext({ headers }) {
  console.log("getContext")
  return {
    headers: headers
  }
}
```

`routes/index.svelte`
  ```
import { browser } from "$app/env";
  /**
   * @type {import('@sveltejs/kit').Load}
   */
  export async function load({ page, fetch, session, context }) {
    console.log("load")
    console.log(context)

    return {}
  }
```

**Expected behavior**
Return {} in client-side and in server-side return the result from `getContext` hook.

**Severity**
Annoying and blocking development due to; not all of us uses end-points to process data. We also need context in components/pages on the server-side.

**Additional context**
There is a discussion about this in Svelte Discord server in `svelte-kit` channel: https://discord.com/channels/457912077277855764/819723698415599626/830464479258083368

It seems like this line causes it to always return {}: https://github.com/sveltejs/kit/blob/dfbe62b28baf5f846f4d23f0668691fdf4d39b66/packages/kit/src/runtime/server/page/respond.js#L61

**Comment by Conduitry** [comment]
This is part of the reason we're trying to find better names for things. The `context` in the `getContext` object is unrelated to the `context` in `load` functions.

The `getContext` hook return value is exposed on the request object that is passed to endpoint routes. This is data that is, in general, not necessarily safe to expose to the browser.

The `getSession` hook takes this context and returns the `session` that is exposed to `load` functions (and in the `$session` store).

The `context` in `load` functions comes from the `context` returned by a higher-up `load` function in a `$layout.svelte` file.

**Comment by kahverengi001** [comment]
Well, `getContext` passes into the endpoint routes but what about page routes? There is no current way of passing it to the page routes. Only sessions are available, but there is a scenario which is when you have a separated back-end server than kit server. You can't do all the route page REST API calls in hooks always. The API calls for pages must be defined in pages as you do in fetch calling in `<script context="module">`.  For example, I want to use browser headers to make API call to the back-end server. But in this current situation it's not possible.

**Comment by Conduitry** [comment]
We definitely don't want to make all the headers available to pages, as that would negate any benefits of HTTP-only cookies. I still don't see what's wrong with manually exposing select headers through the session, and then using those however you need to during `load`s.

**Comment by benmccann** [comment]
Yeah, I think `session` would probably suffice here. I didn't quite realize that you were suggesting to use it in your last comment

@kahverengi001 try `session` and let us know if it doesn't work. If it's not sufficient, please provide more detail about the exact problem you're trying to solve

**Comment by kahverengi001** [comment]
Thanks for better renaming and caring about the issue.

I have a project which has a back-end server and a front-end (kit) server. The point is getting authentication is should be done by browser but the kit server should render data for SSR.

So what I'm trying to do is passing the client browser's headers directly to the API headers in the component page's load function. In the current situation, there is no way to access any kind of request information such as headers, or which method in component pages. Only available in endpoints. But the problem is I do not want to create API for middleware. I already have an API server that is back-end. So all I need is just passing browser request information.

I mean it should already provide this kind of data to the front-end server (kit) on the server-side. Of course, this information shouldn't be accessible via a browser.

Another point is if I want to use the client's headers. Then I need to do all of them in hooks. So whether what which page is.
I am still open to ideas. But my opinion is it should already be able to access context from the server version of component pages.

**Comment by Conduitry** [comment]
Any page component could also be rendered on the client though, and we don't want entirely different experiences for pages rendered on the browser and pages rendered on the server. If something's a necessary piece of data to render a page, it needs to be something that the browser can be trusted with.

If authenticating with the external API server involves sending it cookies that won't be sent to the SSR server (because they're for a different domain), then you can't use SSR.

**Comment by kahverengi001** [comment]
I'm not quite sure about not letting people to writing special server safe code is a good idea in general. Maybe it seems easier usage for the kit.

In the current structure, I guess I need to create inner APIs for every external API. (which I believe 2x and duplicating work, and not letting the external API server control rules such as limitations and security of requests)

Do you have any suggestions for this kind of external API server scenario?

**Comment by benmccann** [comment]
Is this external API on the same domain? Regardless of being able to access the headers, I would think that you'd need to proxy the calls to make sure that it's the same domain, which could just be one thing in `hooks.js` and not a new endpoint for each API. If you tried to call the external API directly I'd think you'd end up with a bunch of CORS headaches.

**Comment by kahverengi001** [comment]
Yes, the external API is under the same domain. And sure, I'm aware of CORS.

> which could just be one thing in `hooks.js`

Could you please explain this more or better?

**Comment by benmccann** [comment]
E.g. you could have a `handle` method that proxies any `/api/` calls to another server. https://kit.svelte.dev/docs#hooks-handle

I guess without proxying you would setup an application load balancer that sends `/api/` to your backend and everything else to SvelteKit? But even so, I don't quite understand what your issue would be. You'd hit some endpoint to get a token and then put that token in your `fetch` call

**Comment by kahverengi001** [comment]
Well, imagine you have a token in your cookies and you need that token in each API on the external server. If you want to make API calls in your page components' `load, function, then you are supposed to use the `session` variable for shifting tokens from hooks to the components. This is how it works in the current structure.

When you mentioned about `handle` function in hooks, I got an idea in my mind. First I need to recognize which URL requested from the SSR server then I can make the API call for that page in the `handle` or `getSession method, then I can simply pass the required data to the page component via the session variable.

As far as I see from the real-world example or any kind of kit example, they don't have authentication. And people think to use the only Auth0 which is easy integration. In the examples, they only fetch data without any authentication from inner APIs. For example: `/posts.json`
