### ISSUE TITLE
Optimize js files sent

### ISSUE THREAD

**Issue by PlopTheReal** [sveltejs/kit#9553]
### Describe the problem

My goal is to optimize the payloads and reduce the number of requests in a prod build.
Here are the requests on a page load from the route `routes/[...catchall]`:
![image](https://user-images.githubusercontent.com/58116071/228492175-cf21aef9-e495-40e9-b283-bc9eb4490b2b.png)

My rollupOptions that reduces the number of chunks are the following: 
```
rollupOptions: {
	output:{
	 manualChunks: (id)=> {
	    const chunks = [
		  'routes/+layout.svelte',
		  'routes/+error.svelte',
		  '...catchall]/+page.svelte',
		  '/components/critical/']
	       for (const chunkName of chunks) {
		   if (id.includes(chunkName)) {
			 return "m"
		}
	}
},
```
In the previous capture `m.xxx.js` are the merged chunks.

We can see those extra js files:
`start.xxx.js`
`app.xxx.js`
`_layout.svelte.xxx.js`
`_...catchall_-page.svelte.xxx.js`
`0.xxx.js`
`1.xxx.js`
`2.xxx.js`

Also some of them are nearly empty and probably don't require an extra request.

```javascript
// _layout.svelte.xxx.js
import{O as f}from"../chunks/m.d03737c2.js";export{f as default};
```

```javascript
// _...catchall_-page.svelte.xxx.js
import{R as f}from"../chunks/m.d03737c2.js";export{f as default};
```

```javascript
// 0.xxx.js
import{O as m}from"./m.d03737c2.js";export{m as component};
```

```javascript
// 1.xxx.js
import{Q as m}from"./m.d03737c2.js";export{m as component};
```

```javascript
// 2.xxx.js
import{R as m}from"./m.d03737c2.js";export{m as component};
```

The page loaded is from [...catchall] route:
![image](https://user-images.githubusercontent.com/58116071/228495632-2a0e0255-7bcd-4513-a3a9-4e4ec9660d76.png)

### Describe the proposed solution

Remove / merge as much js files as possible.

### Importance

would make my life easier

**Comment by PlopTheReal** [comment]
I've just spotted that this one is related to #https://github.com/sveltejs/kit/issues/9520 and #https://github.com/sveltejs/kit/issues/3882

**Comment by dummdidumm** [comment]
Closing in favor of those referenced issues

**Comment by PlopTheReal** [comment]
feels sad, looks I've provided a bit more details / insights in this one.

**Comment by dummdidumm** [comment]
No worries, it's not for nothing! The referenced issues do link back to this one so we will not lose sight of the details in here.
