### ISSUE TITLE
More svelte syntax throughout kit

### ISSUE THREAD

**Issue by JonathonRP** [sveltejs/kit#9556]
### Describe the problem

Currently in server side using $ to subscribe to stores doesn't work with .[server].ts, .[server].js files it would be nice to be able to have that, how Nextjs has js or ts files in page folder act as jsx react components.

### Describe the proposed solution

More svelte syntax eligible to be used throughout the sveltekit stack.

### Importance

nice to have

**Comment by dummdidumm** [comment]
Things like `$` subscribing to stores is constrained to Svelte files. Even if we were able to change that at some point, it would need to happen for Svelte itself. A related issue exists somewhere in the Svelte repository - therefore closing.
