### ISSUE TITLE
[Question] Security Issue Disclosure Channel

### ISSUE THREAD

**Issue by v1ktor0t** [sveltejs/kit#9559]
### Describe the bug

Hello team,

we have identified a security issue regarding to the SvelteKit web server. What communication channel is appropriate for disclosing the issue?

Thanks,
Viktor

### Reproduction

n/a.

### System Info

```Shell
n/a.
```

### Severity

annoyance

**Comment by dominikg** [comment]
We enabled githubs private reporting feature, you can create a new advisory here: https://github.com/sveltejs/kit/security/advisories/new (also linked from the new issue page).

More information about it can be found in the github docs https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability
