### ISSUE TITLE
Can't dynamically import images from $lib folder

### ISSUE THREAD

**Issue by Xharos** [sveltejs/kit#9585]
### Describe the bug

I would like to import images depending on a variable, something like :
```js
<script>
    let animal = 'cat';
</script>

<img src="$lib/assets/{animal}.jpg">
```

But i get an error while :
```js
<img src="$lib/assets/cat.jpg">
```

Works like a charm.

### Reproduction

Fresh install with svelte-preprocess-import-assets to dynamically import assets from code according to [svelte-kit documentation](https://kit.svelte.dev/docs/assets)

Link to a repository :
- https://github.com/Xharos/test-svelte-issue

[is working](https://github.com/Xharos/test-svelte-issue/blob/master/src/routes/%2Bpage.svelte)
[cause an error](https://github.com/Xharos/test-svelte-issue/blob/master/src/routes/test/%2Bpage.svelte)

### Logs

```Shell
Error: Not found: /$lib/assets/cat.jpg
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:394:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:5)
    at Object.#options.hooks.handle (eval at instantiateModule (file:///E:/test/node_modules/vite/dist/node/chunks/dep-79892de8.js:53995:28), <anonymous>:46:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```Shell
System:                                                       
    OS: Windows 10 10.0.19044                                   
    CPU: (8) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics    
    Memory: 7.82 GB / 15.95 GB                                  
  Binaries:                                                     
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE            
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.15.0
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.2.0 => 4.2.1
```

### Severity

annoyance

### Additional Information

Or if there is an alternative to dynamically import assets, I can deal with it.

But using `svelte-preprocess-import-assets` is the only solution I've founded.

Thanks in advance

**Comment by gtm-nayan** [comment]
svelte-preprocess-import-assets only looks for static asset paths in your components. Please open a feature request there instead if you want to use dynamic paths with interpolated segments.

Alternatively, you may use globEager with vite to a similar effect.
