### ISSUE TITLE
postbuild fails while creating fallback page when header property based filtration applied

### ISSUE THREAD

**Issue by DaBigBlob** [sveltejs/kit#9587]
### Describe the bug

I want to be able to return "Please visit from a browser." as plaintext when the request's 'Accept' string does not contain 'text/html'.
However when I implement this in hooks.server.ts,
```ts
import type { Handle } from '@sveltejs/kit';
 
export const handle = (async ({ event, resolve }) => {
 
//this 👇 code
  if (!event.request.headers.get("Accept")?.includes("text/html")) {
    return new Response("Please visit from a browser.", {headers: {"Content-Type": "text/html"}, status: 406});
  }

  return await resolve(event);
}) satisfies Handle;
```
kit/src/core/postbuild/fallback.js fails.
<img width="1257" alt="Screenshot 2023-04-02 at 5 57 30 AM" src="https://user-images.githubusercontent.com/73036332/229348547-9c8ebcae-9bae-4705-9a64-f35eaf37685b.png">

Not it is not adapter-cloudflare's problem. This occurs without that adapter too.

### Reproduction

Svelte sample app + reproduced error: https://github.com/DaBigBlob/postbuild-err-reproduction-svelte

## reproduction steps
1. initiate a skeleton sveltekit project

2. add the following in src/hooks.server.ts
```ts
import type { Handle } from '@sveltejs/kit';
 
export const handle = (async ({ event, resolve }) => {
 
if (!event.request.headers.get("Accept")?.includes("text/html")) {
  return new Response("Please visit from a browser.", {headers: {"Content-Type": "text/html"}, status: 406});
}

  return await resolve(event);
}) satisfies Handle;
```
3 .run `npm run build`

### System Info

```Shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 126.33 MB / 16.00 GB
    Shell: 3.4.1 - /usr/local/bin/fish
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Safari: 16.4
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.15.0 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.2.0 => 4.2.1
```

### Severity

blocking all usage of SvelteKit

**Comment by Conduitry** [comment]
You should be able to use the `building` boolean from `$app/environment` (https://kit.svelte.dev/docs/modules#$app-environment-building) to determine whether this is a simulated request coming from pre-rendering, and not do any filtering in this case.
