### ISSUE TITLE
`trailingSlash` `ignore` gives wrong URL pathname

### ISSUE THREAD

**Issue by GingerAdonis** [sveltejs/kit#9595]
### Describe the bug

Viewing a page with a trailing slash when rendered clientside will give an URL pathname without the trailing slash in `+page.server.js`. This is quite problematic for custom `trailingSlash` handling in the load function.

Example:
- `/myroute/` server load gives pathname: `/myroute/` (ok)
- `/myroute/` client load gives pathname: `/myroute` (not ok)

### Reproduction

Please note that `trailingSlash` is set to `ignore`. Click both links and see the problem when viewing a page with a trailing slash.

https://stackblitz.com/edit/sveltejs-kit-template-default-y3g4ee?file=src/routes/about/+page.svelte

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600U with Radeon Graphics
    Memory: 2.41 GB / 13.86 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-node: 1.2.3 => 1.2.3
    @sveltejs/kit: 1.15.0 => 1.15.0
    svelte: 3.58.0 => 3.58.0
    vite: 4.2.1 => 4.2.1
```

### Severity

serious, but I can work around it

**Comment by amit13k** [comment]
I am facing similar issue where client side navigation with a trailing slash doesn't contain trailing slash in the pathname in load function. As a workaround, I am just adding a trailing slash if it's not already present. Hoping to see this fixed sooner.

**Comment by dreitzner** [comment]
After some debugging, here is some more info:

- `render_page()` returns correct URL
```
URL {
  href: 'http://billa.local:3000/about/',
  origin: 'http://billa.local:3000',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'billa.local:3000',
  hostname: 'billa.local',
  port: '3000',
  pathname: '/about/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

- `render_data()` returns wrong url
```
URL {
  href: 'http://billa.local:3000/about',
  origin: 'http://billa.local:3000',
  protocol: 'http:',
  username: '',
  password: '',
  host: 'billa.local:3000',
  hostname: 'billa.local',
  port: '3000',
  pathname: '/about',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

**Comment by dreitzner** [comment]
adding to that:

- `export const trailingSlash = 'always';` is present in `./src/routes/+layout.js`
- I still get trailing_slash as never in `render_data()`, which is why the `normalize_path` does not work
- I also tried adding the trailing slash option to the root server layout => same issue
- I also tried to add a layout to the route, but it is still never

**Comment by dreitzner** [comment]
@Rich-Harris the logic was introduced with PR #7719 .
Do you remember, why the trailing slash logic was excluded for data requests?
Link to original PR: https://github.com/sveltejs/kit/pull/7719/files#diff-70bbf390c5a53b49a9f23557426bbd1bee9188a247ce1ef34e5f4f217036c7f6R180
Link to current code block: https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/respond.js#L178

For every client site routing the trailing slash logic is never called and it is therefore undefined, when calling `render_data()`

**Comment by dreitzner** [comment]
@dummdidumm as reviewer of this PR, you also might be able to give more insight into the question above. 😊

**Comment by dummdidumm** [comment]
I think we did that because data requests don't need to be redirected, but the logic seems flawed because while we don't want to redirect, we still want to compute it (because right now it's always `undefined` as you say and then falls back to `never`). A PR changing that would be appreciated 👍

**Comment by GingerAdonis** [comment]
I've updated the stackblitz link to use kit v1.15.9 and this bug still occur. Do you have any idea? @dummdidumm / @dreitzner :)

**Comment by dreitzner** [comment]
@GingerAdonis that is weird....

when I create a new SvelteKit project and run it locally, I get the correct behavior.
See https://github.com/dreitzner/svelte-kit-trailing-slash

**Comment by GingerAdonis** [comment]
> when I create a new SvelteKit project and run it locally, I get the correct behavior. See https://github.com/dreitzner/svelte-kit-trailing-slash

Your repo has a `+page.js` file instead of a `+page.server.js` file to properly reproduce this bug.

**Comment by dreitzner** [comment]
ok, that makes sense, there is currently no way to communicate to the server that there should be a trailing slash in preload, when it is set to ignore. I updated my test repo with `/server` and `/server/`

Example:
`/server`  will call http://127.0.0.1:5173/server/__data.json?x-sveltekit-invalidated=_1
`/server/` will call http://127.0.0.1:5173/server/__data.json?x-sveltekit-invalidated=_1

**Comment by GingerAdonis** [comment]
@dummdidumm Can the issue be re-opened? Thank you. :)
