### ISSUE TITLE
Page goes unresponsible if exception was thrown in `<script>` tag inside of `+page.svelte`

### ISSUE THREAD

**Issue by devunt** [sveltejs/kit#9598]
### Describe the bug

I found that in CSR routing, if an error was thrown in `<script lang="ts">` tag inside of `+page.svelte` file, `hooks.client.ts`'s `handleError` hook does not called and pages are become unresponsible without any noticeable change (e.g. it does not renders `+error.svelte`). If the error was thrown in `load` inside of `+page.ts`, `handleError` called correctly and `+error.svelte` renders.

---

Given `src/hooks.client.ts` existing,

```typescript
// src/hooks.client.ts
import type { HandleClientError } from '@sveltejs/kit';

export const handleError = (({ error, event }) => {
  console.log('handleError client hook');
  return { message: 'Unexpected error' };
}) satisfies HandleClientError;
```

---

Following code calls `handleError` and renders `+error.svelte`.

```typescript
// src/routes/test/+page.ts
import type { PageLoad } from './$types';

export const load: PageLoad = async () => {
  throw new Error('hey');
};
```

Console logs:
<img width="613" alt="image" src="https://user-images.githubusercontent.com/337728/229695209-f4c49ba9-7d92-463a-b85c-fa6776ef5917.png">

---

Whereas following code makes the page unresponsible.

```svelte
<!-- src/routes/test/+page.svelte -->
<script lang="ts">
  throw new Error('hey');
</script>
```

Console logs:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/337728/229695527-3d5e3797-5a94-40fd-a61c-d9ebaad1843a.png">

---

This only happens in client-side routing when the `<a>` directs to the errorrous page, and user clicks it. In SSR, such as hard-refreshing, `handleError` in `hooks.server.ts` calls correctly and corresponding `+error.svelte` renders.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-uanet1

### Logs

```Shell
proxy.js?v=731064bf:15 [HMR][Svelte] Unrecoverable HMR error in <+page>: next update will trigger a full reload
logError @ proxy.js?v=731064bf:15
Proxy<+page> @ proxy.js?v=731064bf:380
construct_svelte_component_dev @ chunk-J2U4QHOD.js?v=731064bf:2081
update @ root.svelte:45
update_slot_base @ chunk-J2U4QHOD.js?v=731064bf:97
update @ +layout.svelte:17
update @ chunk-J2U4QHOD.js?v=731064bf:1110
flush @ chunk-J2U4QHOD.js?v=731064bf:1076
Promise.then (async)
schedule_update @ chunk-J2U4QHOD.js?v=731064bf:1050
make_dirty @ chunk-J2U4QHOD.js?v=731064bf:1830
(anonymous) @ chunk-J2U4QHOD.js?v=731064bf:1867
$$self.$$set @ root.svelte:52
(anonymous) @ proxy.js?v=731064bf:83
$set @ chunk-J2U4QHOD.js?v=731064bf:1957
dest.<computed> @ proxy.js?v=731064bf:46
update @ client.js?v=731064bf:382
await in update (async)
navigate @ client.js?v=731064bf:1157
(anonymous) @ client.js?v=731064bf:1580
+page.svelte:1 Uncaught (in promise) Error: hey
    at instance (http://localhost:3000/src/routes/(app)/test/+page.svelte?t=1680586046430:53:8)
    at init (chunk-J2U4QHOD.js?v=731064bf:1861:23)
    at new Page (http://localhost:3000/src/routes/(app)/test/+page.svelte?t=1680586046430:66:3)
    at createProxiedComponent (svelte-hooks.js?v=731064bf:341:9)
    at new ProxyComponent (proxy.js?v=731064bf:242:7)
    at new Proxy<+page> (proxy.js?v=731064bf:349:11)
    at construct_svelte_component_dev (chunk-J2U4QHOD.js?v=731064bf:2081:22)
    at Object.update [as p] (root.svelte:45:43)
    at update_slot_base (chunk-J2U4QHOD.js?v=731064bf:97:10)
    at Object.update [as p] (http://localhost:3000/src/routes/(app)/+layout.svelte?t=1680585133028:201:6)
```

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 39.28 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.8.1 - /private/var/folders/zw/9w9jjw9j66l5hdgh5gk6brbh0000gn/T/xfs-d5170514/node
    Yarn: 3.5.0 - /private/var/folders/zw/9w9jjw9j66l5hdgh5gk6brbh0000gn/T/xfs-d5170514/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  npmPackages:
    @sveltejs/adapter-vercel: ^2.4.1 => 2.4.1
    @sveltejs/kit: ^1.15.0 => 1.15.0
    svelte: ^3.58.0 => 3.58.0
    vite: ^4.2.1 => 4.2.1
```

### Severity

blocking all usage of SvelteKit

**Comment by SQLSourcerer** [comment]
I think I've noticed this happen when there is an error in the template portion of the +page.svelte too

**Comment by dummdidumm** [comment]
`handleError` is only concerned with handling errors that happen during the loading phase (load functions, handle hook), not the rendering phase. For those we need to add support into Svelte itself first, namely error boundaries. Afterwards we can revisit if there's something to add to SvelteKit. If so, we'll open a new issue for that, so I'm going to close this one.

**Comment by seanlail** [comment]
> `handleError` is only concerned with handling errors that happen during the loading phase (load functions, handle hook), not the rendering phase. For those we need to add support into Svelte itself first, namely error boundaries. Afterwards we can revisit if there's something to add to SvelteKit. If so, we'll open a new issue for that, so I'm going to close this one.

Thanks for this response. Can you point me to an open / related issue?

I've been looking at the docs here:
https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror
Specifically `src/hooks.client.js`

I read that as "client side error handling" but it's actually not?

This is super confusing in the docs.

**Comment by CaptainCodeman** [comment]
The docs specifically say "If an unexpected error is thrown during loading ***or rendering***, this function will be called"

Does that only apply to the server hook?

**Comment by ibrahimqasim-abtrace** [comment]
> `handleError` is only concerned with handling errors that happen during the loading phase (load functions, handle hook), not the rendering phase. For those we need to add support into Svelte itself first, namely error boundaries. Afterwards we can revisit if there's something to add to SvelteKit. If so, we'll open a new issue for that, so I'm going to close this one.

Why is this marked as not planned?
There is currently no way to redirect to error pages on the client side or in SPA mode?

**Comment by mroobert** [comment]
@devunt  Is there a solution for this at the current state of sveltekit or am I missing something?

**Comment by CaptainCodeman** [comment]
A new 'error boundary' feature was recently added that may be useful:

https://svelte.dev/docs/svelte/svelte-boundary
