### ISSUE TITLE
Unexpected null value in layout child load function

### ISSUE THREAD

**Issue by Glench** [sveltejs/kit#9612]
### Describe the bug

In my hooks.server.ts I have a function that sets locals.user to null or a user object:

```typescript
export const handle = (async function handle({ event, resolve }) {
    event.locals.user = await get_user(event);
    return resolve(event);
}) satisfies Handle;
```

In a layout.server.ts file I have this, which should redirect if there is no user object:

```typescript
export const load = (async ({locals}) => {
    if (!locals.user) throw redirect(307, '/login')
    return {
         // ...
    }
}) satisfies PageServerLoad;
```

Within the layout's purview I have a +page.server.ts that references `locals.user`:

```typescript
export const load = (async ({locals}) => {
    // simplified for clarity
    console.log(locals.user.id)
}) satisfies PageServerLoad;
```

With this setup I've occasionally gotten this error from +page.server.ts:

```TypeError: Cannot read properties of null (reading 'id')```

My understanding is that this error should be impossible — the layout.server.ts load function should catch the case where there is no user object and redirect to the `/login` route, so the +page.server.ts load function should never be called. Is this a mistaken idea or is there a bug?

I don't have any more information about what causes this error sometimes and not others. It only seems to have happened a few times in production and I don't know why. I haven't been able to reproduce locally.

### Reproduction

see above

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
    Memory: 232.93 MB / 981.34 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.8.1 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 9.5.1 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.3
    @sveltejs/adapter-node: ^1.2.2 => 1.2.2
    @sveltejs/kit: ^1.14.0 => 1.14.0
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.1
```

### Severity

serious, but I can work around it

**Comment by geoffrich** [comment]
This sounds like "working as expected" to me - all load functions are [run in parallel](https://kit.svelte.dev/docs/load#parallel-loading) to prevent request waterfalls, so `+layout.server.ts` and `+page.server.ts` are executed at the same time. You can't count on the layout code running first. Whether or not you get the error is non-deterministic and depends on whether the layout's redirect is thrown before the page tries to access locals.

**Comment by Glench** [comment]
Oh hrm, thanks for pointing that out but that kind of sucks actually. It means I have to have a bunch of duplicate code. Is there some idiomatic way to get the behavior I was expecting?

**Comment by dummdidumm** [comment]
It sounds like you want to return that info from your layout and then use `await parent()` : https://kit.svelte.dev/docs/load#using-parent-data

Closing as there are ways to accomplish this with existing API

**Comment by Glench** [comment]
Thanks all for your support! <3
