### ISSUE TITLE
`split` option for `adapter-cloudflare`

### ISSUE THREAD

**Issue by nCrafts** [sveltejs/kit#9617]
### Describe the problem

So it seems that sveltekit deploys the whole app (minus the static parts) as a single worker.js file. Cloudflare has a limit of 1mb for this file.

How does one structure an application that doesn't exceed 1mb in total?

Example, I am using markdown to store content in my project, which is imported using this code in +pager.server.ts:

`const modules = import.meta.glob('../../markdown/**/*.md')
`

Unless I am doing something wrong it seems that the single worker.js file now includes all of the markdown files?

Related: https://github.com/sveltejs/kit/issues/2963

### Describe the proposed solution

I don't really know. Maybe a way for the adapter to scale to something larger?

### Alternatives considered

I've looked at Vercel but I don't like the pricing, and cloudflare seems to offer more features.

### Importance

i cannot use SvelteKit without it

**Comment by benmccann** [comment]
Vercel has a `split` option: https://kit.svelte.dev/docs/adapter-vercel#deployment-configuration. This sounds like a request to have that option in `adapter-cloudflare` as well

**Comment by nCrafts** [comment]
I believe the Cloudflare allows 5mb on the paid plans, which gives some more room. Still, being able to split the app would be amazing.

I am not sure if it’s possible though. It seems that Cloudflare expects one _worker.js file:
[https://developers.cloud flare.com/pages/how-to/refactor-a-worker-to-pages-functions/](https://developers.cloudflare.com/pages/how-to/refactor-a-worker-to-pages-functions/)

**Comment by benmccann** [comment]
@jrf0110 do you know if this feature is possible to implement on Cloudflare Pages?

**Comment by markjaquith** [comment]
Note that these limits (1MB free, 5MB paid) are after gzip compression. My SvelteKit app produces a 1.75MB `_worker.js` file, but it gzips down to 405KB. If I do some JS minification before gzipping, I can get it slightly smaller... 376KB. There might be some more that SvelteKit can squeeze in with minification.

I don't think it's possible to do auto splitting yet ([see this ticket](https://github.com/cloudflare/workers-sdk/issues/637)), but you can petition them on a case-by-case basis to raise the limit for you: https://forms.gle/ukpeZVLWLnKeixDu7

**Comment by nCrafts** [comment]
Another thing to add, and maybe this is something to control within Sveltekit: the content of my pre-rendered routes is also being added to the _worker.js file.

Example, if I add a .md page to my route, while enabling pre-rendering, the content of this .md file ends up in the _worker.js file, even though the page is pre-rendered.

Beyond the file size itself having a large _worker.js file will increase the worker startup time. Having all the raw text content of the website load on every worker invocation is not very effective.

Any advice would be welcome.

**Comment by jrf0110** [comment]
> @jrf0110 do you know if this feature is possible to implement on Cloudflare Pages?

Soon :) https://github.com/cloudflare/workers-sdk/pull/2769

**Comment by bgronek** [comment]
Looks like https://github.com/cloudflare/workers-sdk/pull/2769 has been merged and deployed. So does this now need to be incorporated into the adapter?

**Comment by eltigerchino** [comment]
closing in favour of https://github.com/sveltejs/kit/issues/2963
