### ISSUE TITLE
Can CSS be inlined in the server-rendered pages ?

### ISSUE THREAD

**Issue by Litarvan** [sveltejs/kit#962]
Currently, HTML is rendered in the response by the server, but the CSS is linked through <link> attributes, thus delaying proper page rendering until the stylesheet request is done.

Is it possible to inline CSS (or at least the 'start' stylesheet) like Next.JS does? Or is it planned?

**Comment by Maggi64** [comment]
CSS loading got worse in comparison to sapper i think.
With the migration to sveltekit i saw a loss in 18 lighthouse points.

**New:**
![image](https://user-images.githubusercontent.com/20517052/114319507-2658c300-9b12-11eb-8e60-ba17cc16fd55.png)
![image](https://user-images.githubusercontent.com/20517052/114319549-3ffa0a80-9b12-11eb-858e-08574448de1b.png)

**Old:**
![image](https://user-images.githubusercontent.com/20517052/114319602-6c158b80-9b12-11eb-8946-b2d7761a743b.png)

I can provide more detailed info if needed.

**Comment by benmccann** [comment]
> This seems mostly related to more css files that need to be loaded.

Sapper used rollup-plugin-css-chunks to chunk the CSS files in the same way that the JS files were chunked. That's handled by Vite now, so you'd have to put in a feature request over in that repo if you'd like to see that behavior added to Vite

**Comment by andreiborisov** [comment]
Inlining is a huge win for perceived performance, even when loading assets through HTTP/2. I'd say this is a critical feature on the road to SvelteKit's production-ready status.

**Comment by Maggi64** [comment]
> Sapper used rollup-plugin-css-chunks to chunk the CSS files in the same way that the JS files were chunked. Vite is most compatible with Rollup plugins, so potentially you could include that in your build.

Sadly didn't work. I tried to disable vite css splitting, but it doesn't seem to respect my config settings.

**Comment by andreiborisov** [comment]
I've successfully mitigated the issue by using HTTP/2 Server Push, depending on your backend, you might wanna look into that

**Comment by mvolfik** [comment]
Interesting to note, CSS _is_ inlined when using dev server, but not during build (adapter-static in my case)

**Comment by mehdiraized** [comment]
i use postcss config in [sveltekit starter](https://github.com/navneetsharmaui/sveltekit-starter) but not work in build project

**Comment by livehtml** [comment]
Please give us opportunity to do this. It's too important and needed thing in SvelteKit. Thanks.

**Comment by Rich-Harris** [comment]
As of the most recent version, you can inline stylesheets smaller than a certain size with the `inlineStyleThreshold` option:

```js
// svelte.config.js
export default {
  kit: {
    // inline all stylesheets smaller than 1kb
    inlineStyleThreshold: 1024
  }
};
```

**Comment by julienchazal** [comment]
thx @Rich-Harris !

CSS is inlined, but is it normal that in the HTML still appears :

```html
<link disabled rel="stylesheet" href="/_app/assets/index-f3af5aa6.css">
```

Chrome is loading this CSS file, and it contains CSS that has been inlined

**Comment by gerardo-rodriguez** [comment]
> As of the most recent version, you can inline stylesheets smaller than a certain size with the `inlineStyleThreshold` option:
> 
> ```js
> // svelte.config.js
> export default {
>   kit: {
>     // inline all stylesheets smaller than 1kb
>     inlineStyleThreshold: 1024
>   }
> };
> ```

This is great, @Rich-Harris! 🎉 

Does it matter where the source CSS file exists? Does it matter how or where the CSS file is imported? Does the use of an adapter (I'm using `@sveltejs/adapter-static`) disable the `inlineStyleThreshold` setting?

I'm setting `inlineStyleThreshold` to different values (including extremely large values) and I don't see anything getting inlined. I wonder what I'm doing wrong. We are running version `1.0.0-next.254`. Is this the best place to ask these types of questions, or should I ask elsewhere? 🤔 

My endgoal is to inline both the JS and CSS, I found this CSS option first so figured I'd start there.

Thank you! I've enjoyed using SvelteKit and Svelte so much thus far! 😄

**Comment by wiesson** [comment]
> I'm setting inlineStyleThreshold to different values (including extremely large values) and I don't see anything getting inlined. 

Same here!

**Comment by pavelloz** [comment]
Im afraid i have the same issue.

With `prerender: false` it just plain doesnt work.

With `prerender true` i can find:
* html file in build directory is wrong, without any CSS inlined
* html file in .svelte-kit/output/prerendered/output is correct, CSS is inlined. `svelte-kit` preview shows correct build.

```
=> npx envinfo --npmPackages "{svelte,@sveltejs/*,vite}"           

  npmPackages:
    @sveltejs/adapter-static: next => 1.0.0-next.29 
    @sveltejs/kit: next => 1.0.0-next.302 
    svelte: ^3.46.4 => 3.46.4 
```

**Comment by johntron** [comment]
inlineStyleThreshold doesn't work for me either (using adapter-static). There may be a regression if it was working 7 months ago when @robots4life made the commit that worked for him.

**Comment by newsroomdev** [comment]
Thank you for reopening @benmccann.

I did some exploration last night and noticed that the `inlineStyleThreshold` is always set to `0` after it's returned from the [`options` function in `kit/src/core/config/index.js`](https://github.com/sveltejs/kit/blob/177a5a9f8219f3f9633d8f8dc879f8472f74d6a2/packages/kit/src/core/config/index.js#L109). I believe there may be a bug with the [`number` validator in `kit/src/core/config/options.js`](https://github.com/sveltejs/kit/blob/8e9d1a6d04ac510304d2194a3cab6ac9941746c6/packages/kit/src/core/config/options.js#L432-L439), despite its similarity to adjacent the `string_array` and `boolean` validators. I hope this helps!

**Comment by dummdidumm** [comment]
Could someone provide a minimum reproducible so we can look into it? I did set `inlineThreshold` to an arbitrary high number and ran the build of the SvelteKit site; styles were inlined as expected. Don't get confused by the `<link href="...">` still present, they are `disabled` so not actually loaded - it's a hint for Vite to not do funky stuff.

**Comment by The-Noah** [comment]
The styles inside the `link` tags are loaded though, if you open DevTools and go to the network tab you can see them being loaded.

**Comment by dummdidumm** [comment]
That's strange, I don't see this behavior (using Chrome); according to the spec a disabled link tag should be neither downloaded nor executed. A reproducible would really help.

**Comment by The-Noah** [comment]
#7130

**Comment by dummdidumm** [comment]
Thanks, closing in favor of that issue.

**Comment by dummdidumm** [comment]
The inline styles being loaded seems to have been a bug in Vite. It fails with 3.1.x, but works with 3.2.x. Updating to the latest version of Vite fixes the bug.
