### ISSUE TITLE
Intercepting Routes

### ISSUE THREAD

**Issue by bobbymannino** [sveltejs/kit#9625]
### Describe the problem

https://beta.nextjs.org/docs/routing/intercepting-routes Similar to NextJS feature. It would be awesome if we could use this in sveltekit.

### Describe the proposed solution

As above

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
My initial gut feeling is 😱 we've gone too far 😱 

Looking at the modal example, I'm _still_ not sure exactly how it works, and I'm _extra_ sure I wouldn't know how it worked at all if I stumbled upon it in a codebase and didn't have the whole explainer to go along with it. 

That being said, I think there is room for some neat features around something like this. I particularly like the parallel routes implementation. I'll personally have to think about it a bit more.

**Comment by bobbymannino** [comment]
this has been implemented now, a little while ago too so I think I can close this
