### ISSUE TITLE
`Date.toLocaleString()` not working in SSR

### ISSUE THREAD

**Issue by hyunbinseo** [sveltejs/kit#9629]
### Describe the bug

`new Date().toLocaleDateString('en-CA');` returns `M/DD/YYYY` in SSR, instead of `YYYY-MM-DD`.

### Reproduction

```svelte
<script>
  import { onMount } from 'svelte';

  let dateString = new Date().toLocaleDateString('en-CA');

  $: console.log(dateString);

  onMount(() => console.log(dateString));
</script>
```
```bash
# server
4/10/2023
```
```bash
# browser
2023-04-10
2023-04-10
```

### System Info

```Shell
System:
  OS: macOS 13.3
  CPU: (8) arm64 Apple M1
  Memory: 53.28 MB / 8.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
  npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
Browsers:
  Chrome: 112.0.5615.49
  Firefox: 110.0.1
  Safari: 16.4
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
  @sveltejs/kit: ^1.5.0 => 1.15.2 
  svelte: ^3.54.0 => 3.58.0 
  vite: ^4.2.0 => 4.2.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
This is up to Node, and is going to depend on which locales they ship by default. If you run `new Date().toLocaleDateString('en-CA')` in the Node REPL, you'll see the same results. I'm not sure how one loads new locales at runtime (as opposed to needing to recompile Node with additional locales built in), but this is unrelated to SvelteKit.

**Comment by hyunbinseo** [comment]
Node.js returns different result in `.toLocaleDateString('en-CA')`.

v16: `yyyy-MM-dd`
v18: `M/d/yyyy`

https://github.com/nodejs/node/issues/46277
https://github.com/nodejs/node/issues/45945

**Comment by srl295** [comment]
Ideally you should not be depending on the date format outputting a certain format.  If you really need a fixed format, `toLocale…` is not for you.

The locale formats can and do change. That said, this particular change was reverted.
