### ISSUE TITLE
redirect in load function to external (absolute) link

### ISSUE THREAD

**Issue by AndreasHald** [sveltejs/kit#963]
We use Auth0 hosted pages for auth, which means we have to redirect our users to an external site, for authentication. With sapper, we just did the redirect directly in express.

```javascript
 export const load: Load = async ({ page, fetch, session, context }) => {
    const { user } = session;

    if (!user) {
      const webAuth = new auth0.WebAuth({options});
      const redirect = webAuth.client.buildAuthorizeUrl();
      return {
        status: 300,
        redirect,
      };
    }
    return {};
 };
```

However the url returned here is absolute and unrelated to our site (```https://some-slug.auth0.com/authorize?some-query-params```) and i'm unable to get it to work.

I know this was previously an issue in sapper aswell (https://github.com/sveltejs/sapper/issues/490), is it simply just not implemented in svelte-kit yet?

**Comment by Conduitry** [comment]
This does appear to be implemented in SvelteKit, and external redirects are working for me, both when `load` is called on the server, and when doing client-side navigation to a page with a `load` that returns a `redirect`.

Do you have a small reproduction? My guess as to what's happening here is that the browser cached your first 300 response, and is refusing to hit the endpoint again. That's a strange response to be returning, anyway (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300) - is it part of what auth0 tells you to do? I would suggest using 302 for this, which would also not be cached.

**Comment by AndreasHald** [comment]
You are absolutely correct, i just picked the first 3xx number. and the browser did cache the response. everything is working as expected, i'm very sorry to have wasted your time.
