### ISSUE TITLE
`adapter-node` fails to build pages with dynamic CSS import 

### ISSUE THREAD

**Issue by kraftwerk28** [sveltejs/kit#9632]
### Describe the bug

Cannot `build` the project with dynamically imported css file. `dev` script works fine though. Also, same bug happens when importing css inside `+*.server.ts`'s `load` function to further pass the imported css via the `data` prop:

```ts
export const load = (async () => {
  return {
    css: await import('./styles.css').then(m => m.default),
  };
}) satisfies PageServerLoad;
```

### Reproduction

1. Open https://stackblitz.com/edit/sveltejs-kit-template-default-xgmxyj?file=src/routes/+page.svelte
2. Wait for startup script to finish
3. Check the terminal output of `npm run build` script

### Logs

```Shell
error during build:
Error: Could not resolve "../../chunks/styles.js" from ".svelte-kit/adapter-node/entries/pages/_page.svelte.js"
    at error (file:///home/projects/sveltejs-kit-template-default-xgmxyj/node_modules/rollup/dist/es/shared/node-entry.js:2153:30)
    at handleInvalidResolvedId (file:///home/projects/sveltejs-kit-template-default-xgmxyj/node_modules/rollup/dist/es/shared/node-entry.js:23807:24)
    at resolveDynamicImport (file:///home/projects/sveltejs-kit-template-default-xgmxyj/node_modules/rollup/dist/es/shared/node-entry.js:23865:58)
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-node: ^1.2.3 => 1.2.3 
    @sveltejs/kit: ^1.5.0 => 1.15.2 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.2.0 => 4.2.1
```

### Severity

blocking all usage of SvelteKit

**Comment by popapaul** [comment]
Until this is fixed, you might be able to make use of [vite`s raw import](https://vitejs.dev/guide/assets.html#importing-asset-as-string):
``await import('./styles.css?raw')``

Note: It will not help if you need to transform the css beforehand with postcss, as it will import the file content before transformation.

**Comment by benmccann** [comment]
I'm not sure this is the right repository to file the issue as it's only Rollup involved in that stack trace: https://github.com/sveltejs/kit#bug-reporting

**Comment by kraftwerk28** [comment]
> I'm not sure this is the right repository to file the issue as it's only Rollup involved in that stack trace: https://github.com/sveltejs/kit#bug-reporting

You're right - I confirm the issue happens on adapter-cloudflare as well, so it's probably not tied to sveltekit, but rather a global problem w/ dynamic import of CSS
