### ISSUE TITLE
SvelteKit flashes html content on page refresh

### ISSUE THREAD

**Issue by edgarasben** [sveltejs/kit#964]
Svelte Kit flashed html content every time I hit browser refresh on Safari. I am using the latest svelte@next install with all extras enabled.

Let me know if I should provide the source or more details needed.

https://user-images.githubusercontent.com/725324/114307153-a49b7200-9ade-11eb-8963-eb64653c1dda.mov

**Comment by dummdidumm** [comment]
Duplicate of #915
