### ISSUE TITLE
The button loses focus from the button when moving to the next subpages

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#968]
The button loses focus from the button when moving to the next subpages:
Example (with a description of the problem): https://github.com/lukaszpolowczyk/focus-button

## Problem

1. Refresh page
2. Press `Tab key` on the keyboard
3. The button are focused
4. Press `Right Arrow` on the keyboard
5. The button loses focus
 
**Question:** How do I keep focus without using `element.focus()` or anything like that?

GIF with this:
![lost-focus](https://user-images.githubusercontent.com/16800535/114312453-0534aa00-9af3-11eb-8127-fa5c146092fb.gif)

The code looks like this:

```svelte
<!-- src/routers/[slug].svelte -->
<svelte:head><title>Lost focus - Sveltekit Routers</title></svelte:head>
<script>
  import { page } from '$app/stores';
  
</script>
<br>
page {$page.params.slug}
```
　
```svelte
<!-- src/routers/$layout.svelte -->
<script>
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  
  import Keydown from "svelte-keydown";
</script>
<Keydown on:ArrowRight={() => goto(`${Number($page.params.slug)+1}`) } />

<button on:click={()=>goto(`${Number($page.params.slug)+1}`)}>goto({Number($page.params.slug)+1})</button>
or press RightArrow
<slot />
```

**Comment by dummdidumm** [comment]
GitHub issues are reserved for bug reports or feature requests. Please ask usage questions on StackOverflow or the Discord server.

By default a page change will not keep the element focused, that's an accessibility best practice default. You'll need to handle that yourself.

**Comment by ahtcx** [comment]
@dummdidumm could focusing the body not be optional? I'm having a similar issue where I have a search text field updating the URL with `goto` which will lose focus on each keystroke. I think this is a pretty common use-case and whilst it's possible to implement workarounds manually it would be a lot easier if it were an option in `goto`.

@lukaszpolowczyk as a workaround I've been using [`patch-package`](https://www.npmjs.com/package/patch-package) on [L245 of `router.js`](https://github.com/sveltejs/kit/blob/39b69677635a59b40675d375c64bbc4507ea0ea5/packages/kit/src/runtime/client/router.js#L245) but this isn't ideal and I imagine `router.js` will change a lot so you'll have to update it at every change.

**Comment by lukaszpolowczyk** [comment]
@dummdidumm @ahtcx
I want it too.
Maybe similar to `sveltekit:noscroll` and `goto(href, { replaceState, noscroll })` , e.g. `sveltekit:keepfocus` and `goto(href, { replaceState, keepfocus })` ?

**Comment by lukaszpolowczyk** [comment]
@dummdidumm Should I create a separate issue?
Can this issue be changed in feature request for `sveltekit:keepfocus`?

**Comment by dummdidumm** [comment]
Please open a new issue for the feature request.
