### ISSUE TITLE
Add a way to change the query params on a page easily.

### ISSUE THREAD

**Issue by davjhan** [sveltejs/kit#969]
**Is your feature request related to a problem? Please describe.**
I would like an easy way to change the query params in the address bar at runtime.

**Usecases:**
- I want to sync a text input on the page to a query param so that when the user copies the address from the address bar and shares it, the link automatically has the field pre-filled.
- I want to pass an error message to another page that I want to display temporarily. I set the error as a query param and use `goto`  to redirect to that page. If i let the user acknowledge the error banner and hide it, I want to remember that by stripping the query param from the URL so that when they refresh, the banner doesn't re-appear.

**Describe the solution you'd like**
An API that allows me to change the url, with convenient syntax for adding and removing query params. Ideally, this will not trigger a refresh of the page in itself.

Perhaps augment the `goto` API? https://kit.svelte.dev/docs#modules-app-navigation
**Describe alternatives you've considered**
There are workarounds for the usecases that I've mentioned, but this is a common enough usecase imo.

**How important is this feature to you?**
Not a deal-breaker but it would allow me to have a simpler architecture that stores state more obviously, in the url, instead of a store.
**Additional context**
As an aside, It would also be nice to have a slicker way to append query params to a `goto` call. Currently, judging by the signature from the documentation, theres no way to do it.

`goto(href, { replaceState, noscroll })`

Thanks!

**Comment by mohe2015** [comment]
Which workarounds are you thinking of @davjhan ?

**Comment by mohe2015** [comment]
Just realized when the router has fully loaded it seems like this already works.

**Comment by davjhan** [comment]
So you can use the `$page.query` object in  `import {page} from '$app/stores'`, but this is an
[URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) object and not a svelte store. As such, there is no reactivity that comes out of the box. The workaround is you creating a custom store that auto updates this URLSearchParams instance AND manually overwrites the url.

Here is a sample component that you can use to test how this works.

```svelte
<script>
    import {page} from '$app/stores'
</script>
<main class='p-4 flex flex-col items-center'>
    <button on:click={()=> $page.query.set("weather","sunny")}>Set query param</button>
    <h1>{$page.query.get("weather")}</h1>
    <button on:click={()=> console.log($page.query.get("weather"))}>print weather to console</button>
</main>
```
When you click the "set query param" button, it neither updates the URL nor does it automatically update the h1 label. (Cause its not a store). However, when you click the "print weather..." button afterwards, it will print "sunny" as expected.

The reason I raise this ticket is that this seems like an improvement that should be implemented at the framework level, cause its a very common use case, and therefore, we'd appreciate the improved ergonomics.

---

> Just realized when the router has fully loaded it seems like this already works.

What do you mean by this?

**Comment by mohe2015** [comment]
> So you can use the `$page.query` object in `import {page} from '$app/stores'`, but this is an
> [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) object and not a svelte store. As such, there is no reactivity that comes out of the box. The workaround is you creating a custom store that auto updates this URLSearchParams instance AND manually overwrites the url.

You probably mean something like the following - just builtin.
```ts
// DO NOT USE THIS AS IS - THIS IS NOT FINISHED YET
// SPDX-License-Identifier: CC0-1.0
import { goto } from '$app/navigation';
import type { Subscriber, Unsubscriber, Updater, Writable } from 'svelte/store';
import { page } from '$app/stores';
import type { Location } from '@sveltejs/kit/types/helper';
import { get } from 'svelte/store';

declare type Invalidator<T> = (value?: T) => void;

const location2query = (value: Location): Record<string, string> => {
	console.log(value.query.toString());
	const currentQuery: Record<string, string> = {};
	value.query.forEach((value, key) => {
		currentQuery[key] = value; // TODO FIXME append
	});
	return currentQuery;
};

export const query: Writable<Record<string, string>> = {
	/**
	 * Subscribe on value changes.
	 * @param run subscription callback
	 * @param invalidate cleanup callback
	 */
	subscribe(
		run: Subscriber<Record<string, string>>,
		invalidate?: Invalidator<Record<string, string>>
	): Unsubscriber {
		return page.subscribe(
			(value) => {
				console.log('subscribe.run');
				if (value) {
					run(location2query(value));
				}
			},
			invalidate
				? (value) => {
						console.log('subscribe.invalidate');
						if (value) {
							invalidate(location2query(value));
						}
				  }
				: undefined
		);
	},
	/**
	 * Set value and inform subscribers.
	 * @param value to set
	 */
	set(value: Record<string, string>): void {
		console.log('set');
		const urlSearchParams = new URLSearchParams(value);
		goto(`?${urlSearchParams.toString()}`, { replaceState: true });
	},
	/**
	 * Update value using callback and inform subscribers.
	 * @param updater callback
	 */
	update(updater: Updater<Record<string, string>>): void {
		console.log('set');
		updater(location2query(get(page)));
	}
};
```

> 
> > Just realized when the router has fully loaded it seems like this already works.
> 
> What do you mean by this?

Oh sorry, I probably mistaked this with something I read somewhere else. I meant that `goto` creates a full page load but I think this was never the case after the page has loaded. Anyways svelte seems to handle this quite well (as expected).

**Comment by etienneburdet** [comment]
I had the same problem (filters on the side that needs to synced with the URL) and it took me a little while to get around it, but `goto(…)`, actually is fine for that. That is because `goto` doesn't trigger any component remount (a highly debated subject in Sapper), keep the state of your `let var`,  but do trigger your `load`. 

And you do want to trigger your `load` if your URL change(i.e navigate to a new URL), else you risk not having the same page on first navigation and when already on the page. But this won't retrigger any component load if you are the same path.

Then any variable that is sync to the URL should be an `export let …` and returned by your `load function` and you derived the state of your page this way. You may have to add guards to prevent fetching large amount of data if you already did.

So I don't think `goto` needs a `syncUrl` option, navigating is fine. I do agree on a more elegant solution than `goto(`/path?`$page.query.toString()`), though!

**Comment by davjhan** [comment]
Thanks etienne for teaching me something new today!

> I had the same problem (filters on the side that needs to synced with the URL) and it took me a little while to get around it, but `goto(…)`, actually is fine for that. That is because `goto` doesn't trigger any component remount (a highly debated subject in Sapper), keep the state of your `let var`, but do trigger your `load`.

This is good to know. Is this still true for static sites? For example if you have `ssr:false` in svelte configs or have
```
<script context="module">
	export const prerender = true;
</script>
```

---

> Then any variable that is sync to the URL should be an export let … and returned as props by your load function and you derive the state of your page this way. You may have to add guards to prevent re-fetching large amount of data if you already did.

Do I have to do this manually or can I just use `$page.params` from 

```
import { page } from '$app/stores';
```

**Comment by etienneburdet** [comment]
It works on static sites too, yes. The (pre)load will be run either when you export or client-side.

Using the built-in store is a pretty good way to do indeed, here is a real life exemple with destructuring:
```
	export async function load({ page, fetch }) {
                …
		const { lnglatq, recherche: searchValue, ...filterValues } = Object.fromEntries(page.query)
		const markerLngLat = q2center(lnglatq);
               …
		return {
			props: {
				markerLngLat,
				searchValue,
				filterValues
			}
		};
	}
```

**Comment by ThisIsSammysAccount** [comment]
Running into this issue and trying to follow the responses as I'm rather new to Svelte. I'm trying to access a query string value on a static site on the initial page GET. Loading the query string from page.query in the module load event and passing as a prop works from VSCode, both on the initial load and after a goto(), but after exporting using the static adapter the page.query doesn't see the query string and is always an empty URLSearchParams object. Note I'm using the Load event from @sveltejs/kit, not directly from $app/stores. 

This code works in dev/VSCode:

```
<script context="module" lang="ts">
	import type { Load } from '@sveltejs/kit';

	let urlCode:string;
	
	// see https://kit.svelte.dev/docs#loading
	export const load: Load = async ({ page, fetch }) => {

		if (page.query.has('c'))
			urlCode = page.query.get('c');

                 return {
			//pass the data to the module to render
			props: { urlCode }
		};
         }
```

This works, urlCode is populated:  
`http://localhost:3000/?c=abc`

This does not work, page.query never sees a value.
`http://actualwebsite.com/page?c=abc`

I see the complexity in setting a new query string after the app is loaded, but I'm not sure why the initial load seems to be missing the value. Any suggestions?

Thanks.

**Comment by rmunn** [comment]
@ThisIsSammysAccount -

I'd suggest opening a new issue for your "page.query is empty" problem, as that would seem to be a bug in the static adapter, and thus unrelated to this one. But first, try putting a `console.log('Page object:', page)` inside your `load()` function, and examine the page object you get in both dev mode (in VS Code) and in compiled mode (what you get on the actual website). Logging the `page` object to the browser console should allow you to dig into the object's properties right there in the console and see exactly what difference is has between dev mode and when it's deployed. And that, in turn, will allow you to write up a better bug report. (Or you might get lucky and figure out the problem just from that console log!)

**Comment by bradphelan** [comment]
I have a version that maybe similar to what  @mohe2015 

routes/filter.svelte
```
<script>

import {createQueryStore} from "$lib/URLSearchParamsStore"

const filter0 = createQueryStore("filter0")
const filter1 = createQueryStore("filter1")

</script>

<p>Input filter</p>
<input bind:value={$filter0}/>
<input bind:value={$filter1}/>
```

![OFUG3aEx1u](https://user-images.githubusercontent.com/17650/126176849-47cf1399-07e7-4bf5-a13e-edee52c7ca82.gif)

store.js
```
import { goto } from "$app/navigation";

import {page} from "$app/stores"

function queryToObject(params){
    // parse query string
    const obj = {};
    // iterate over all keys
    for (const key of params.keys()) {
        if (params.getAll(key).length > 1) {
            obj[key] = params.getAll(key);
        } else {
            obj[key] = params.get(key);
        }
    }
    return obj;
}

export function createQueryStore(prop) {
  var query = undefined
	return {
    subscribe: h => { 
      return page.subscribe(p=>{
        query = queryToObject(p.query)
        h(query[prop])
      })
    },
    set: v => {
      query[prop] = v
      const urlSearchParams = new URLSearchParams(query)
      const g = `?${urlSearchParams.toString()}`
      goto(g, {keepfocus:true, replaceState:true, noscroll:true})
    },
	};
}
```

**Comment by bostondevin** [comment]
Yeah - this should be in the framework already - thanks! @bradphelan - saved me!!!

**Comment by mohamadHarith** [comment]
Below is a Typescript version of query params store provided by @bradphelan . 

```typescript
import { goto } from '$app/navigation';
import { page } from '$app/stores';

const URLSearchParamsToObject = (params: URLSearchParams) => {
  let obj = {};
  params.forEach((v: string, k: string) => {
    obj[k] = v;
  });
  return obj;
};

export const createQueryParamsStore = (key: string) => {
  let params;
  page.subscribe((v) => {
    params = URLSearchParamsToObject(v.query);
  });

  return {
    subscribe: (cb: Function) => {
      return page.subscribe((p) => {
        cb(p.query.get(key));
      });
    },
    set: (value: string) => {
      params[key] = value;
      const urlSearchParams = new URLSearchParams(params);
      goto(`?${urlSearchParams.toString()}`, {
        keepfocus: true,
        replaceState: true,
        noscroll: true
      });
    }
  };
};
```
Also, I have been hitting the below error while using the **goto** navigation function in a component.
![WhatsApp Image 2021-11-05 at 6 34 23 PM](https://user-images.githubusercontent.com/16622933/140507891-6d70de8c-94bf-4e0b-ad62-1ad5f0ede020.jpeg)

The mistake I made was I used the **goto** function out of the **onMount** method. This was the reason for the above error because **goto** method will be called while rendering the component server side. The **goto** method can only be called on the frontend, hence it shall be placed within the **onMount** function.

```html
<script lang="ts">
  import { onMount } from 'svelte';
  import { createQueryParamsStore } from '$lib/store';

  const testParam = createQueryParamsStore('test');
  testParam.subscribe((v) => {
    console.log('test param=> ', v);
  });

  onMount(() => {
    testParam.set('123');
  });
</script>
```

**Comment by Manuelbaun** [comment]
@bradphelan, @mohamadHarith  thanks for the custom `queryParamStore`. But I hit an issue with it. Basically, I wanted to display the current page and size on an table in the url, so you can easliy jump to it. The I hit the issue, that only on of the two params are displayed in the url.

```typescript
const pageFilter = createQueryParamsStore('page', currentPage);
const limitFilter = createQueryParamsStore('size', size);
```

it looks like the createQueryParamsStore hits some sort of race condition, while initializing it. Only size is displayed in the url.   I moved the params object outside of the create function for now, as it solved my issue.  It probably will be an store as well.

**Comment by mohamadHarith** [comment]
@Manuelbaun  Sorry that you're facing an issue with the query param store that I provided, I will look into it. However, the solutions provided by me and @bradphelan is using the *goto* method, which is used for navigation. This will cause the *load* method within the page to be called again while mutating the query params. So, if you have any API calls within the *load* method, it will be called again. This is unnecessary if you're just trying to mutate query param within the page. So, due to this, I have discard this query param store in our project. I wish SvelteKit team could provide us a better solution for this.

**Comment by mohamadHarith** [comment]
https://dev.to/mohamadharith/mutating-query-params-in-sveltekit-without-page-reloads-or-navigations-2i2b

**Comment by zummon** [comment]
More simple way or understandable in my opinion to get it going without store. Also support array
Create `$lib/query.js`
```
import { goto } from "$app/navigation";

// string to object
export const strToObj = (str = '', scope = {}) => {
	const s = new URLSearchParams(str)
	let obj = scope
	Object.keys(scope).forEach((key) => {
		const values = s.getAll(key)
		if (values.length > 0){
			if (Array.isArray(scope[key])){
				obj[key] = values
				return
			}
			obj[key] = values[0]
		}
	})
	return obj
}
// query string to object
export const qsToObj = (scope = {}) => {
	const obj = strToObj(location.search, scope)
	return obj
}

// object to string
export const objToStr = (obj = {}) => {
	let str = '?'
	Object.keys(obj).forEach((key) => {
		const values = obj[key]
		if (values){
			if (Array.isArray(values)){
				values.forEach((value) => {
					str += `${key}=${value}&`
				})
				return
			}
			str += `${key}=${values}&`
		}
	})
	return str
}
// object to query string
export const objToQs = (obj = {}) => {
	const str = objToStr(obj)
	goto(str, {
		replaceState: true,
		noscroll: true,
		keepfocus: true,
	})
}
```
So the functions above will help and below are ideas to improve

- We need to `get()`, `getAll()` to access the query string. Could it be accessible from simple object like `{}` 
- Use `goto()` to update the query string in the url bar. Could it be like when `$page.query` changes it will auto change the url bar for the `window.location.search` part

To use in `page.svelte`
```
<script>
import { onMount } from "svelte";
import { objToQs, qsToObj } from "$lib/query";

let ready = false
let q = {
	name: ''
}
onMount(() => {
	q = qsToObj(q)
	ready = true
})
$: {
	if (ready){
		objToQs(q)
	}
}
</script>

<input bind:value={q.name}>
```
Hope it will work for easily query changes. Wish SvelteKit implements it soon, will help a lot of less code and less work for web developers

**Comment by benneq** [comment]
I can't get load and goto working as desired.

I have a component that should behave like this:
1. (on initial load / SSR): parse search params, execute fetch
2. display an input with the search params, display the fetch result
3. when the input value changes, it should update the url and refetch the data

On the client side I can't use `fetch` inside `load`, because there are some inputs that can't be put into the search params. Though ideally I'd like to update the url search params and **skip** the load function. But how?

Another issue is, that the reactive statement, which is watching the input value, is getting triggered immediately after load. This will update the url search params and execute the fetch. Though I double fetch the data on page load (1. on server side, 2. on client side).

Here's a stripped down version of my code:
```svelte
<script context="module">
export const load = async ({ url, fetch }) => {
    // this fetch is needed for SSR
    const text = url.searchParams.get('text');
    const result = await fetch(`/api?text=${text}`).then(val => val.json());

    return {
        props: {
            data: result,
            text: text,
        }
    }
}
</script>

<script>
import { browser } from "$app/env";
import { goto } from "$app/navigation";

export let data;
export let text;
let paramThatIsNotPartOfUrlSearchParams;

// if browser is needed because else this would call goto while SSR.
// basically this whole reactive block should not be automatically called after initial render
$: if(browser) {
    // here I'd like to update the url search params
    goto(`?text=${text}`, { replaceState: true, keepfocus: true });

    // and execute fetch when the user changed the input value
    // this fetch can contain more search params than the SSR fetch
    // and those search params should not be visible in the browser's url
    fetch(`/api?text=${text}&foo=${paramThatIsNotPartOfUrlSearchParams}`).then(val => val.json())
        .then(result => data = result);
}
</script>

<input type="text" bind:value={text} /><br/>
Data: {JSON.stringify(data)}
```

Anyone has some idea how to solve this?

**Comment by Rich-Harris** [comment]
judging by the thumbs up, this _is_ a dupe, so i'll close it

**Comment by itswadesh** [comment]
Thanks Rich,

To handle <select> input populate with query params the following hack worked

```const url = new URL($page.url.toString())
url.searchParams.set('cityName', selectedCityName)
url.searchParams.set('countryName', selectedCountryName)
goto(url.toString(), { replaceState: true, noscroll: true })```

**Comment by homerjam** [comment]
Could we have a `sveltekit:replace` anchor option?

**Comment by ollema** [comment]
> Reading between the lines, I think what everyone wants is a way to `goto` without triggering a navigation. It's [easy enough to do this](https://stackblitz.com/edit/sveltejs-kit-template-default-68ectc?file=src%2Froutes%2Findex.svelte&terminal=dev)...
> 
> ```js
> const url = new URL(location);
> url.searchParams.set('foo', bar);
> goto(href, { replaceState: true });
> ```
> 
> ...and you create whatever helper function you like around that, but the fact that it triggers navigation (and with it, `load`) is problematic in some cases. For example it causes inputs to be blurred, which is undesirable.
> 
> As such, I think this is _effectively_ a duplicate of #2673.

the code in `index.svelte` of the attached stackblitz is not working anymore when recreated with a more recent sveltekit version :thinking: 

you lose focus on the input after each page navigation, see [this stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-edcqqw?file=src/routes/index.svelte)

**Comment by blerrgh** [comment]
It seems like modifying $page.url.seachParams and then calling goto performs the requested behavior.

This code:
```js
const url = new URLSearchParams;
url.set(param, value);
await goto(`?${url}`);
```
updates the browser url and then triggers a page `load()` but this code:
```js
const url = $page.url.searchParams;
url.set(param, value);
await goto(`?${url}`);
```
updates the browser url and doesn't re-trigger the page `load()`.

Not sure why that would be or if it's just a fluke in my specific code.

**Comment by caseywatts** [comment]
[This response](https://github.com/sveltejs/kit/issues/969#issuecomment-882597472) is just what I wanted! A store for query/search parameters :)

A couple of changes I had to do to get it working with sveltekit 1.2.2
1. `p.query` → `p.url.searchParams` (because [`page.query` has been replaced with `page.url.searchParams`](https://kit.svelte.dev/docs/web-standards#url-apis-urlsearchparams))
2. `goto(g, { keepfocus: true, replaceState: true, noscroll: true });` has been replaced with `goto(g, { keepFocus: true, replaceState: true, noScroll: true });` (the variables have to be camelCase).
3. Just tidying up a bit, I replaced `queryToObject()` with `Object.fromEntries`.
4. I annotated it a bit to help me keep oriented.


Here's my full updated code for `URLSearchParamsStore.js`

```
import { goto } from '$app/navigation';
import { page } from '$app/stores';

export function createQueryStore(prop) {
	var query = undefined;
	return {
		subscribe: (h) => {
			// any time $page gets updated, we'll update the queryStore
			return page.subscribe((p) => {
				query = Object.fromEntries(p.url.searchParams);
				h(query[prop]);
			});
		},
		set: (v) => {
			// any time the queryStore gets updated, we'll also update the url using goto()
			query[prop] = v;
			const urlSearchParams = new URLSearchParams(query);
			const g = `?${urlSearchParams.toString()}`;
			goto(g, { keepFocus: true, replaceState: true, noScroll: true });
		}
	};
}
```

I was also wondering why we'd want a separate queryStore for each entry instead of just one query object -- and then I realized (again! lol) that [svelte doesn't automatically update when an object is mutated](https://svelte.dev/tutorial/updating-arrays-and-objects). Now I'm glad to have this store be set up for a single query parameter.

**Comment by caseywatts** [comment]
I refactored [it](https://github.com/sveltejs/kit/issues/969#issuecomment-1403304685) a bit more to support strings, arrays, and booleans:

`lib/URLParamsStore.js`
```
import { goto } from '$app/navigation';
import { page } from '$app/stores';

const booleanParam = {
	deserialize(string) {
		return string == 'true';
	},
	serialize(bool) {
		if (bool == true) {
			return 'true';
		} else {
			return 'false';
		}
	}
};

const arrayParam = {
	deserialize(string) {
		if (string) return string.split(',').map((v) => v.trim());
	},
	serialize(array) {
		return array.toString();
	}
};

const stringParam = {
	serialize(string) {
		return string.toString();
	},
	deserialize(string) {
		if (string) return string.toString();
	}
};

function serialize(paramType, data) {
	if (paramType == 'array') {
		return arrayParam.serialize(data);
	} else if (paramType == 'boolean') {
		return booleanParam.serialize(data);
	} else {
		return stringParam.serialize(data);
	}
}

function deserialize(paramType, data) {
	if (paramType == 'array') {
		return arrayParam.deserialize(data);
	} else if (paramType == 'boolean') {
		return booleanParam.deserialize(data);
	} else {
		return stringParam.deserialize(data);
	}
}

function queryStore(paramType, prop) {
	return {
		subscribe: (h) => {
			// any time $page gets updated, we'll update the queryStore
			return page.subscribe((p) => {
				h(deserialize(paramType, p.url.searchParams.get(prop)));
			});
		},
		set: (value) => {
			// any time the queryStore gets updated, we'll also update the url using goto()
			page.subscribe((p) => {
				p.url.searchParams.set(prop, serialize(paramType, value));
				goto(`?${p.url.searchParams.toString()}`, {
					keepFocus: true,
					replaceState: true,
					noScroll: true
				});
			});
		}
	};
}

export function createParamsArrayStore(prop) {
	return queryStore('array', prop);
}

export function createParamsBooleanStore(prop) {
	return queryStore('boolean', prop);
}

export function createParamsStringStore(prop) {
	return queryStore('string', prop);
}
```

`+page.js`
```
<script>
  import { createParamsStringStore, createParamsBooleanStore, createParamsArrayStore } from "../../lib/URLSearchParamsStore"

  const title = createParamsStringStore("title");
  const showOrder = createParamsBooleanStore("showOrder");
  const chords = createParamsArrayStore("chords");
</script>

<label>
  Title
  <input bind:value={$title}>
</label>
<label>
  Show Chord Order
  <input type=checkbox bind:checked={$showOrder}>
</label>
<label>
  Chords
  <select multiple bind:value={$chords} style="width: 100px;">
    <option value="F">F</option>
    <option value="C">C</option>
    <option value="G">G</option>
    <option value="D">D</option>
    <option value="A">A</option>
  </select>
</label>
```

I really like having the serialize/deserialize functions parsed out and easy to edit like this -- I do fiddle with these on projects a lot.

[svelte-pathfinder](https://github.com/sveltetools/svelte-pathfinder) supports these data types in the url too, but it's a little heavier than this simple one-file approach.

**Comment by caseywatts** [comment]
This library supports multiple data types for query params too! https://github.com/paoloricciuti/sveltekit-search-params
