### ISSUE TITLE
Move to `.env` and `.env.local` and away from `.env.example`

### ISSUE THREAD

**Issue by coyotte508** [sveltejs/kit#9701]
### Describe the problem

I'm always frustrated when cloning a sveltekit project with an environment.

I need to manually create a `.env` file, so that the typescript errors from importing on `$env/static/private` go away. Eg `cp .env.example .env`.

Why can't I just `pnpm install && pnpm dev` after cloning :grimacing: 

### Describe the proposed solution

From the way SvelteKit handles environment, it would make sense to change this in the starter template's `.gitignore`:

- ignore `.env.local` and `.env.*.local`, that's where the secrets or custom configs will be
- do not ignore `.env` or `.env.{production,development,test}` : **commit** `.env` to the project by default! It should only contain non-sensitive default values.

SvelteKit [refers](https://kit.svelte.dev/docs/adapter-node#environment-variables) to [how Vite handles env](https://vitejs.dev/guide/env-and-mode.html#env-files)

The `.env.*.local` files overrides the `.env` files, and Vite recommend ignoring the local files but not the other. 

So you can have:

- The default values in `.env` (and empty strings eg `SECRET=` for secrets, so that TS is happy)
- Select env variables `.env.local`: secrets & custom overrides

### Alternatives considered

Change SvelteKit to load default env from `.env.example` to make TS happy, but it's a breaking change.

Here only the docs + starter template need to be changed.

### Importance

would make my life easier

### Additional Information

Original comment here: https://github.com/sveltejs/kit/issues/2925#issuecomment-1482656644

**Comment by dummdidumm** [comment]
The decision to ignore `.env` by default which many people also use for sensitive environment variables outweighs the minor inconvenience of having to copy over stuff from a `.env.example` file - therefore closing. You are of course free to adjust this for your own project and modify the `.gitignore` that `create-svelte` produces.
