### ISSUE TITLE
Visible "Navigated to ..." in production builds

### ISSUE THREAD

**Issue by trentjones21** [sveltejs/kit#971]
**Describe the bug**
There is a hidden element on the page with id `svelte-announcer` that is used for accessibility. When developing (running `svelte-kit dev`) the element is hidden.  However, once you run `svelte-kit build && node build` the element becomes visible as soon as you make a client side navigation. 

**Logs**
No browser or server errors occur

**To Reproduce**
1. Check out this repo: https://github.com/trentjones21/svelte-bug . It is just the default svelte kit template with a second route added for navigation.
2. `npm run dev`
3. Click the "Client side navigation" link, and notice there is no issue
4. `npm run build && node build`
5. Click the "Client side navigation" link.  Notice that the "Navigated to ..." accessibility text is visible on the screen

**Expected behavior**
"Navigated to ..." text shouldn't be visible 

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

-   System:
    OS: macOS 11.2.2
    CPU: (8) x64 Apple M1
    Memory: 217.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    npm: 7.5.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.72 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 

- Browser I used: `Safari: 14.0.3`

- Bug exists in `adapter-node` and `adapter-netlify`.  Those are the only two I tested. 
</details>

**Severity**
Serious enough that it makes it hard to deploy a site as long as this bug exists

**Screenshot of the bug**
<img width="244" alt="Screen Shot 2021-04-11 at 10 37 17 PM" src="https://user-images.githubusercontent.com/5697561/114341260-92d5c100-9b16-11eb-8039-538eb102968a.png">

**Comment by ivoberger** [comment]
Was introduced with `1.0.0-next.72`. Appeared for me after upgrading from `1.0.0-next.71`

**Comment by Conduitry** [comment]
Interesting. The styles to hide that are present in `.svelte/build/generated/root.svelte`, but they seem to be getting lost in the production build.

**Comment by dummdidumm** [comment]
Could this be related to Vite? I don't see anything that touches that code area according to the next-72 changelog

**Comment by Conduitry** [comment]
No, I think it probably is on our end. When I pin `@sveltejs/kit@1.0.0-next.71`, the issue goes away, even with the same/latest version of Vite where I could reproduce it with next.72

**Comment by rogueyoshi** [comment]
To add, I noticed that my route's CSS doesn't load when this occurs.
