### ISSUE TITLE
Inconsistent media URLs

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#9716]
### Describe the bug

When importing a media asset and trying to prefix its path with another domain name, I am running into inconsistencies in how SvelteKit works.

+page.svelte

```
<script lang="ts">
  import image from "$lib/assets/image.jpg";
  import Image from "$lib/Image.svelte";
</script>

<img src={image} alt="kitten" />

<Image src={image} alt="kitten" />
```

Image.svelte

```
<script lang="ts">
  export let src: string;
  export let alt = "";

  const mediaUrl = "https://www.example.com";

  function media(path: string) {
    console.log(path);

    if (path.startsWith("http")) {
      return path;
    } else {
      return `${mediaUrl}${path}`;
    }
  }
</script>

<img src={media(src)} {alt} />
```

What this code is trying to do, is prepend a different domain name to all local assets. In this example it's `https://www.example.com` but in the real works code it's Cloudinary, a tool to resize, optimize and cache all our assets. 

In development mode everything works perfectly fine: when you `npm run dev` my repro project, the second image won't show (as it's prepended by `https://www.example.com`). But when you create a build and preview it locally, the image does show locally. Instead of the URL being `https://www.example.com/_app/immutable/assets/image.9d75a129.jpg`, instead it's `http://127.0.0.1:4173/_app/immutable/assets/image.9d75a129.jpg` - but only in the client. In the SSR version of the response, the URL is `https://www.example.com/_app/immutable/assets/image.9d75a129.jpg`. So when you turn off JavaScript in your browser and look at the build preview, the image URL is still `https://www.example.com/_app/immutable/assets/image.9d75a129.jpg`.

### Reproduction

https://github.com/kevinrenskers/image-path-repro

npm run build
npm run preview

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.10 GB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 112.0
    Safari: 16.4
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.15.7
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.2.0 => 4.2.2
```

### Severity

serious, but I can work around it

### Additional Information

I could replace my domain name in the `media` function with the Cloudinary domain, but this is not ideal. More importantly, it seems weird that the image URLs are relative ones in SSR but become absolute ones in client mode.

**Comment by kevinrenskers** [comment]
A simpler example:

```
<script lang="ts">
  import image from "$lib/assets/image.jpg";

  function media(path: string) {
    return `https://www.example.com${path}`;
  }
</script>

<img src={image} alt="kitten" />
<img src={media(image)} alt="kitten" />
```

In the build preview the URL for the second image becomes `https://www.example.comhttp://127.0.0.1:4173/_app/immutable/assets/image.9d75a129.jpg`.

**Comment by benmccann** [comment]
you shouldn't need the `media` function. it's intended to use the `paths.assets` option for this use case: https://kit.svelte.dev/docs/configuration#paths

**Comment by kevinrenskers** [comment]
Oh, that's very nice. Can you use a value from the .env file though?

It's still weird to me why it behaves the way it does, so I think the ticket is still valid, even though I won't run into it anymore?

**Comment by benmccann** [comment]
You can use `process.env` in the `svelte.config.js` file

Since it sounds like you're probably unblocked I'm going to go ahead and close this. I don't think we'd realistically end up looking at it given all the other issues in the tracker. If it causes real problems to someone later on we can re-evaluate

**Comment by benmccann** [comment]
I think [Vite does use those](https://vitejs.dev/guide/env-and-mode.html#env-files), but it's possible that we load the Svelte config file before Vite has loaded the env files. If that's the case, you could use `dotenv` to load the `.env` files yourself at the top of the `svelte.config.js`.
