### ISSUE TITLE
Linting does not like '&' in scss

### ISSUE THREAD

**Issue by mjulstein** [sveltejs/kit#972]
**Describe the bug**
When i use ampersand in the following example the 'npm run lint' command reports an error; 'Identifier is expected ParseError':
```
<style lang="scss">
  main {
    list-style: none;
    & > p:not(:first-of-type) {
      margin-top: 10px;
    }
  }
</style>
```
The page renders correctly.

**Logs**
Not applicable only happens with ampersand ref in SCSS.

**To Reproduce**
Create a nested style and use ampersand to ref the path before
Run 'npm run lint'

**Expected behavior**
Expect no error unless the trailing refs are illegal.

**Stacktraces**
Not applicable only happens with ampersand ref in SCSS.

**Information about your SvelteKit Installation:**
I ran npm init svelte@next on April 12 2021

**Severity**
Minor

**Additional context**
This is only a linting issue but could be problematic in CI/CD or even make it harder to debug errors later.

**Comment by Conduitry** [comment]
See https://github.com/sveltejs/eslint-plugin-svelte3#svelte3ignore-styles

This should probably be the default in the template though if you've enabled both ESLint and Less/Sass.

**Comment by dummdidumm** [comment]
This is a current limitation of the Svelte ESLint plugin. You need to turn off parsing of styles: https://github.com/sveltejs/eslint-plugin-svelte3#svelte3ignore-styles 

```
// eslintrc.cjs
  // ...
  settings: {
    'svelte3/ignore-styles': true,
    // ...
  }
```

**Comment by Conduitry** [comment]
@dummdidumm I think this would make sense to include in the default template though. If someone is using ESLint and is using something other than CSS, we can add that for them.

**Comment by dummdidumm** [comment]
Beaten by a few seconds 😄 I agree that we should handle this in the setup - after the new Hello World template is done.

**Comment by Conduitry** [comment]
See #987. We're going to be moving away from built-in Less and Sass support, which means that updating `.eslintrc.js` accordingly would then fall on users, and wouldn't be something that would be handled in `create-svelte`. Closing this.
