### ISSUE TITLE
Respect HTTP status for asset caching in adapter-cloudflare

### ISSUE THREAD

**Issue by fjdumont** [sveltejs/kit#9721]
### Describe the problem

Bad responses from the server are being served with cache-control headers. This is similar to #9393, which has already been fixed in #9394.

This issue aims to streamline response status handling in adapter-cloudflare as well, so all adapters work in a similar fashion.

### Describe the proposed solution

This could be fixed by checking the response status code before saving the bad response at [worker.js](https://github.com/sveltejs/kit/blob/29ffc78560a99ce387b10a24f48b7f01205f51e7/packages/adapter-cloudflare/src/worker.js#L57).

adapter-cloudflare-workers does so [here]( https://github.com/sveltejs/kit/blob/29ffc78560a99ce387b10a24f48b7f01205f51e7/packages/adapter-cloudflare-workers/files/entry.js#L26).

adapter-node does so [here](https://github.com/cdemi/kit/blob/43f37af6e43516455c4ca6d9c20714553b409efc/packages/adapter-node/src/handler.js#LL40C37-L40C40).

### Importance

would make my life easier

**Comment by fjdumont** [comment]
Is this as straightforward as it seems?

https://github.com/sveltejs/kit/compare/master...fjdumont:kit:master

**Comment by lukeed** [comment]
206 status code is the only throwable status code ([spec](https://w3c.github.io/ServiceWorker/#dom-cache-put) and [cf docs](https://developers.cloudflare.com/workers/runtime-apis/cache/))

if 4xx and 5xx errors arent to be cached, that has to be filtered on the consumer side _because it's up to the consumer_.
The `isCacheable` method from `worktop/cache` just echos the spec logic to sidestep/prevent errors

**Comment by fjdumont** [comment]
This turns out to affect a few thousand of my users, so I'm pushing with a suggestion in PR #9768.

**Comment by fjdumont** [comment]
> 206 status code is the only throwable status code ([spec](https://w3c.github.io/ServiceWorker/#dom-cache-put) and [cf docs](https://developers.cloudflare.com/workers/runtime-apis/cache/))
> 
> if 4xx and 5xx errors arent to be cached, that has to be filtered on the consumer side _because it's up to the consumer_. The `isCacheable` method from `worktop/cache` just echos the spec logic to sidestep/prevent errors

Seems reasonable. Thanks for chiming in!

This turns out to affect a few thousand of my users on each deployment, so I'm pushing with a suggestion in PR #9768.
