### ISSUE TITLE
Unknown compiler option 'ignoreDeprecations'.ts

### ISSUE THREAD

**Issue by craigcosmo** [sveltejs/kit#9724]
### Describe the bug

this error only shows in tsconfig.ts file
```
Unknown compiler option 'ignoreDeprecations'.ts
```

`my package.js`
```json
"typescript": "^5.0.0",
"@sveltejs/adapter-auto": "^2.0.0",
"@sveltejs/kit": "^1.5.0",
"vite": "^4.2.0",
"@typescript-eslint/eslint-plugin": "^5.45.0",
"@typescript-eslint/parser": "^5.45.0",
"svelte": "^3.54.0",
```
`my tsconfig.ts`

<img width="964" alt="Screenshot 2023-04-20 at 11 11 14 AM" src="https://user-images.githubusercontent.com/538657/233256206-5f97b5c0-4299-4580-9523-59f8d3032357.png">

![Uploading Screenshot 2023-04-20 at 11.16.02 AM.png…]()

### Reproduction

start all new skeleton project with option vitest test and elsint. then run npm dev

### System Info

```Shell
mac os ventura, node v16, chrome 112.0.5615.49
```

### Severity

annoyance

**Comment by jasonlyu123** [comment]
You're probably using an old version of VSCode. Could you update to the latest version and try again?

**Comment by craigcosmo** [comment]
update vscode works
