### ISSUE TITLE
Enhanced form action error is only shown when a layout is present.

### ISSUE THREAD

**Issue by eduardolagoeiro** [sveltejs/kit#9745]
### Description
When submitting a form an error is thrown but it is only displayed when a layout is present. Without the layout, the error is not displayed unless the `use:enhance` option is removed.

### Expected Behavior

The error should be displayed regardless of whether a layout is present or `use:enhance` is used.

### Actual Behavior

The error is only displayed when a layout is present, or when `use:enhance` is removed.

### Steps to Reproduce

1. Create a form with use:enhance.
2. Create a form action that throws an error.
3. Submit the form.
4. If a layout is present, the error is displayed. If not, the error is not displayed unless `use:enhance` is removed.

I create a setup here:

repository: https://github.com/eduardolagoeiro/sk-error-form-enhance
form: http://localhost:5173/my-form

To see the bug, remove the use:enhance and/or rename the `src/my-form/_+layout.svelte` to `src/my-form/+layout.svelte`

### System Info

```Shell
System:
  OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Memory: 11.10 GB / 15.47 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
Browsers:
  Chrome: 112.0.5615.49
  Firefox: 112.0.1
npmPackages:
  @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
  @sveltejs/kit: ^1.5.0 => 1.15.7 
  svelte: ^3.54.0 => 3.58.0 
  vite: ^4.2.0 => 4.3.1
```

### Severity

annoyance

**Comment by s3812497** [comment]
Incldued a stackblitz repro. Clicking submit doesn't show the expected error page *unless* there is a `+layout.svelte` file present in the `/my-form` route.
https://stackblitz.com/edit/github-auuqqv?file=src%2Froutes%2Fmy-form%2F%2Bpage.svelte,src%2Froutes%2Fmy-form%2F%2Bpage.server.js

**Comment by gtm-nayan** [comment]
Hmm, it does work if you client side navigate to the form page.

There's an inconsistency there in that, during a client side navigation the missing +layout.svelte is marked with an empty value in `state.branch` whereas when entering the page for the first time the server doesn't include the empty nodes causing it to render the page itself even in the error case.

The SSR code seems heavily leaning towards compacting the arrays, not sure if this is the bit that got left over and should be removed or we need to do it the other way around.

https://github.com/sveltejs/kit/blob/3a8195dfe0f55c024b7b347e74c6e21480bda5bd/packages/kit/src/runtime/client/client.js#L757
