### ISSUE TITLE
invalidate() in layout not working

### ISSUE THREAD

**Issue by coyotte508** [sveltejs/kit#9746]
### Describe the bug

Inside a layout, neither `invalidate("/")` or `invalidate(url => true)` work. Only `invalidateAll()` does.

This code in `+layout.server.ts`:

```ts
export async function load() {
  return {
    exchangeRate: Math.random()
  }
}
```

This code in `+layout.svelte`:

```svelte
<script lang="ts">
  import { invalidate } from "$app/navigation";
  import { onMount } from "svelte";

  export let data;

  onMount(() => {
    // Update exchange rates every second
    const interval = setInterval(() => {
      console.log("invalidating");
      invalidate("/");
      invalidate((url) => {
        console.log("testing", url.href);
        return true;
      }).then(() => console.log("done"));
    }, 1000);

    return () => {
      clearInterval(interval);
      console.log("destroyed");
    };
  });
</script>

<slot />

{data.exchangeRate}
```

Checking the logs, we see the "invalidating" and "done" in the browser console, but no network call, and displayed content does not change.

Replacing either `invalidate` by `invalidateAll` makes the content change

### Reproduction

https://github.com/coyotte508/sveltekit-invalidate

### System Info

```Shell
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 16.48 GB / 62.65 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 110.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.15.7 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.2.0 => 4.3.1
```

### Severity

serious, but I can work around it

**Comment by kevmodrome** [comment]
I think this is a misunderstanding of how invalidate works - the URL mentioned in the documentation is not talking about th URL of the page, but the URL of any fetches in the load function.

So, for example. Here:
+page.server.js```js
export async function load({ fetch }) {
  const res = await fetch('/api/posts') // this is the URL that you should call as an argument to invalidate
  const posts = await res.json()

  return {
    posts
  }
}
```
And
+page.svelte```
<script>
   import { onMount } from 'svelte'
   export let data;
   
   onMount(() => {
      invalidate('/api/posts')
   })
</script>

...
```

What you can do is add a `depends` function in the load function like so:

+page.server.js```js
export async function load({ fetch }) {
  const res = await fetch('/api/posts') // this is the URL that you should call as an argument to invalidate
  const posts = await res.json()

  depends('app:posts') // can be anything

  return {
    posts
  }
}
```

and on the client:
```js
onMount(() => {
   invalidate('app:posts') // needs to match what is in the load function
})
```

**Comment by coyotte508** [comment]
Thanks. It's still weird, in my mind `invalidate(() => true)` and `invalidateAll()` should be the same, but they behave differently
