### ISSUE TITLE
svelte-announcer and css

### ISSUE THREAD

**Issue by raydaly** [sveltejs/kit#975]
**Describe the bug**
A $layout.svelte behaves differently on home page and /about

**Logs**
Not in logs, css or layout problem.

**To Reproduce**
I created a new svelte-kit folder and added a minimum about of new code to illustrate.
1. Created /about in /routes with corresponding index.svelte only containing ```<h1>About</h1>```
2. Added to $layout.svelte 
```
<div class="all">
	<div class="navbar">
		Nav here
	</div>
	<div class="content">
		<slot />
	</div>
</div>

<style>
	.all {height: 100%;}
	.navbar { width: 5rem; height: 100vh; position: fixed;
  	background-color:black; color:white; }
		.content {margin-left: 5rem; }
</style>
```

**Expected behavior**
The spacing (margin) above the black navbar on http://localhost:3000/ should be the same as http://localhost:3000/about. In my Chrome Browser Mac the margin about increases when going to /about. Same in Firebox for Mac.

**Stacktraces**
none

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz
    Memory: 107.42 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 7.6.1 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Browsers:
    Brave Browser: 89.1.21.73
    Chrome: 89.0.4389.114
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.71 
    svelte: ^3.29.0 => 3.37.0 
    vite: ^2.1.0 => 2.1.5 

</details>

**Severity**
High. 
There is probably a work around but I rate it high because the addition of a DIV into my code is serious. If svelte-announcer is going to remain, it needs to be disclosed in the documentation both for both reason it is added and for the impact on $layout.svelte coding.
[routes.zip](https://github.com/sveltejs/kit/files/6297272/routes.zip)

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**
I don't use github often, thus the amateur completion of this form.

**Comment by c-bandy** [comment]
The announcer is there because the navigation svelte uses doesn't actually change the page you're on. It changes the elements, and then swaps the URL. This feature is important for people who use screen readers so that they know that navigation took place. 

There is an open issue to improve customization of this element in #879. Feel free to pitch your thoughts there as well.

**Comment by c-bandy** [comment]
I would like to add as a workaround you can put your HTML in a containing element to avoid layout problems

**Comment by raydaly** [comment]
> The announcer is there because the navigation Svelte uses doesn't actually change the page you're on. It changes the relevant elements, and then swaps the URL. This feature is important for people who use screen readers so that they know that navigation took place. It is unlikely there will be an option to remove it, but improvements to documentation are always welcome.
> 
> There is an open issue to improve customization of this element in #879. Feel free to pitch your thoughts there as well.

I'll stick to the CSS issue here. The inserted div is given a position: absolute which would require a containing element to also have a position of absolute. That works. Not sure if $layout should add this or if it is the responsibility of the coder.

More in #879.

**Comment by c-bandy** [comment]
> The inserted div is given a position: absolute which would require a containing element to also have a position of absolute.

This isn't true, elements with no parent that is absolutely positioned just fallback to root. It would still be positioned correctly. And because of the other CSS properties applied to the element it should not be visible either way. There is currently a bug that makes the styles not apply correctly which is tracked in #971, maybe this is what you're seeing?

**Comment by ignatiusmb** [comment]
Thanks for opening an issue, but without a full reproducible example, we can't really know what the problem is and what's causing it. As mentioned above, `svelte-announcer` have a position of absolute which should not mess with the user's layout.
