### ISSUE TITLE
Deno adapter

### ISSUE THREAD

**Issue by buttercubz** [sveltejs/kit#976]
Is there any future interest or plan to create an adapter for `Deno` from the `svelteKit` development team, oh are you open to third party development?

**Comment by benmccann** [comment]
We should publish a list of community developed ones somewhere. Potentially https://github.com/sveltejs/integrations. If there's one or two that are particularly popular possibly we could consider graduating them to a more official status.

It's possible that there are API shortcomings that wouldn't support some new adapters. If so, please let us know when you encounter them
