### ISSUE TITLE
Node server not sending pre rendered content.

### ISSUE THREAD

**Issue by justinbiebur** [sveltejs/kit#977]
**Describe the bug**
When I build and serve the example app from https://github.com/sveltejs/kit/tree/master/examples/svelte-kit-demo using ```node build``` I get prerendering: false in the about page.

**Logs**

**To Reproduce**

1. Clone this repo.
2. Navigate to /examples/svelte-kit-demo
3. ```yarn install```
4. ```yarn build```
5. ```node build```
6. Go to ```localhost:${PORT}/about```

**Expected behavior**
Since the about page is being pre rendered, I expect it to show, ```prerendering: true```. The pre rendered HTML inside the build folder does contain ```prerendering: true```. But I expect the same to be shown in the browser.

**Stacktraces**

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz
    Memory: 171.84 MB / 3.71 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
- Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.9.0 - /usr/local/bin/npm
 - Browsers:
    Firefox: 87.0
- npmPackages:
    @sveltejs/kit: ^1.0.0-next.72 => 1.0.0-next.72 
    svelte: ^3.35.0 => 3.37.0 
    vite: ^2.1.5 => 2.1.5 

</details>

**Severity**
serious

**Additional context**
![image](https://user-images.githubusercontent.com/47483452/114414742-bb1ff700-9bcc-11eb-914e-b62802a2ca91.png)

**Comment by ignatiusmb** [comment]
I'm not sure what the bug is referring to here, also because the example app doesn't exist anymore in the provided link. Prerendering is mostly relevant for an adapter when building, not when serving the app, in which case it is rendered in the server.
