### ISSUE TITLE
$page.form isn't updated with form action

### ISSUE THREAD

**Issue by evan-thurston** [sveltejs/kit#9770]
### Describe the bug

I'm having issues accessing the 'form' data returned from server side form actions

### Reproduction

https://github.com/evan-thurston/form-action-returns

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 3.38 GB / 15.89 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.15.2
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.2.0 => 4.2.1
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
@evan-thurston the callback you return from your handleSubmit must call the applyAction function or the update function or manually update the page with the results.

Updated the docs to make that a bit clearer hopefully.

**Comment by Rich-Harris** [comment]
Going to close this as `use:enhance` is already covered in the docs and the tutorial:

- https://kit.svelte.dev/docs/form-actions#progressive-enhancement-use-enhance
- https://learn.svelte.dev/tutorial/customizing-use-enhance
