### ISSUE TITLE
Stop / shutdown hook to close database connections, etc.

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#978]
Pre-rendering will generally create connections to a database if one is being used in the project by running the code in `hooks.js`. However, there's no hook to shutdown. Users are reporting that these hanging DB connections cause the build to never exit

I've seen this come up a couple times on Discord and Github. Most recently:
* https://discord.com/channels/457912077277855764/819723698415599626/831111325425074188
* https://github.com/sveltejs/kit/issues/763#issuecomment-813370258

**Comment by Prinzhorn** [comment]
If this results in a `teardown` hook I'd love to see a `setup` hook as well https://github.com/sveltejs/kit/issues/927

**Comment by n4bb12** [comment]
Some inspiration from Next.js: They exit 0 [after build](https://github.com/vercel/next.js/blob/33255b7f4ed6dd2608d6a6590d137353b6f19f67/packages/next/bin/next.ts#L115-L121) and [after export](https://github.com/vercel/next.js/blob/33255b7f4ed6dd2608d6a6590d137353b6f19f67/packages/next/cli/next-export.ts#L65).
