### ISSUE TITLE
Tailwind CSS Integration

### ISSUE THREAD

**Issue by ramonmalcolm10** [sveltejs/kit#9806]
### Describe the problem

I use Tailwind for all my projects, every-time I create a new project I have to manually install Tailwind CSS.

### Describe the proposed solution

I would like to be able to pass a flag --tailwind when creating a new project to have Tailwind installed. 

### Alternatives considered

I have to visit the Tailwind installation page and follow the installation instruction.

### Importance

would make my life easier

**Comment by polyzen** [comment]
Previous discussion: https://github.com/sveltejs/kit/discussions/3025

IIRC React or something prompts to setup Tailwind now as well.

**Comment by Conduitry** [comment]
A number of Svelte maintainers are not the biggest fans of Tailwind, and I don't think we're going to see this as an officially blessed template variant.

If you're looking for something to programmatically add Tailwind to an app, there's the Svelte Add project, which has a Tailwind option - https://github.com/svelte-add/tailwindcss. It's an unofficial community project, but several core Svelte maintainers have also contributed to it.
