### ISSUE TITLE
@sveltejs/adapter-netlify + Supabase - throws http 500 only when edge functions are turned on.

### ISSUE THREAD

**Issue by sortofsleepy** [sveltejs/kit#9810]
### Describe the bug

It's a little bit of a weird one that I haven't found any documentation on. Basically, if edge functions are enabled, a 500 error gets thrown when running the deployed site due to, as far as I can tell, the Supabase helper trying to access the `document` variable while running the server code of the SvelteKit app.

The really weird part is that locally with the dev server, this issue never happens. 

While Edge functions are not a priority and my project is fine not using them, this seems like a bug somewhere either with the adapter or with Supabase(where I've also filed an issue already)

I've been following along with [a Supabase tutorial](https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit) so I'm not entirely certain where the issue lies. 

### Reproduction

~~- Set up a Supabase table, grab the api url and anon key , plug that into a .env file with the keynames~~
  ~~- PUBLIC_SUPA_URL - for the api url~~
  ~~- PUBLIC_SUPA_KEY - for the api key~~
  ~~- See tutorial for where those things are.~~
(url and key are now embedded in the repo)  

- Install Netlify's CLI - npm netlify-cli --save-dev
- Run build (in npm). This is important cause otherwise the behavior will end up being similar to just running the dev server.
- Run `npx netlify dev` to start the Netlify cli.
- The server mimicking a deployed Netlify setup should be running @ http://localhost:8888/
- When you visit `http://localhost:8888/` you should hit an http `500`

I've set up a test repo here https://gitlab.com/xoio/supa-netlify-testing

### Logs

```Shell
From Netlify - this appears repeatedly in the logs 

Apr 28, 09:38:13 AM: error  [render] ReferenceError: document is not defined
    at Object.getItem (file:///root/.netlify/edge-functions/render.js:8118:46)
    at file:///root/.netlify/edge-functions/render.js:4790:36
    at Generator.next (<anonymous>)
    at file:///root/.netlify/edge-functions/render.js:4736:71
    at new Promise (<anonymous>)
    at __awaiter10 (file:///root/.netlify/edge-functions/render.js:4718:14)
    at getItemAsync (file:///root/.netlify/edge-functions/render.js:4789:39)
    at SupabaseAuthClient.<anonymous> (file:///root/.netlify/edge-functions/render.js:5944:40)
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/.netlify/edge-functions/render.js:5462:28)
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 11.60 GB / 31.90 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.64)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1
    @sveltejs/adapter-netlify: ^2.0.7 => 2.0.7
    @sveltejs/kit: ^1.5.0 => 1.15.8
    svelte: ^3.54.0 => 3.58.0
    vite: ^4.3.0 => 4.3.2
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
From the looks of it the sveltekit storage adapter in supabase-auth-helpers tries to access document.cookie if (it thinks) it's in a browser.

For which it does the following check in auth-helpers/shared,

```js
function isBrowser() {
  return typeof window !== "undefined";
}
```

But, IIRC Netlify edge functions run in Deno where `window` does exist, so that's probably where it chokes. 

I can't find anything at the line numbers from the stack trace so, @sortofsleepy please confirm and file the issue in auth-helpers if that's correct otherwise update the repro to make it self contained, i.e. doesn't require someone to go and use a GUI and create a table manually.

**Comment by Devr-pro** [comment]
I had same issue after following up the auth-helper tutorial from their docs
After some code shedding I found that a helper function `const {data: { session } } = await supabase.auth.getSession();` in `+layout.ts` was causing the 500 error
Maybe it would be same for you?

**Comment by sortofsleepy** [comment]
> I had same issue after following up the auth-helper tutorial from their docs After some code shedding I found that a helper function `const {data: { session } } = await supabase.auth.getSession();` in `+layout.ts` was causing the 500 error Maybe it would be same for you?

I thought that was possibly the issue too at first but I tried it again just now to make sure and I'm still hitting a 500. 

> From the looks of it the sveltekit storage adapter in supabase-auth-helpers tries to access document.cookie if (it thinks) it's in a browser.
> 
> For which it does the following check in auth-helpers/shared,
> 
> ```js
> function isBrowser() {
>   return typeof window !== "undefined";
> }
> ```
> 
> But, IIRC Netlify edge functions run in Deno where `window` does exist, so that's probably where it chokes.
> 
> I can't find anything at the line numbers from the stack trace so, @sortofsleepy please confirm and file the issue in auth-helpers if that's correct otherwise update the repro to make it self contained, i.e. doesn't require someone to go and use a GUI and create a table manually.

That was more or less the conclusion I came to. As far as I can tell, everything centers around their `createSupabaseLoadClient` call but I haven't the faintest idea as to why if things work perfectly fine without edge functions. 

Apologies on the lack of a self-contained example, I'm on a free tier and didn't realize I could spin up another project, I've updated the repo to include the url/key so you shouldn't have to spin anything up. 

I already filed an issue under their repo but am still waiting to hear back. I guess I just wasn't sure who this should go under; I already tried the Netlify support forums but they weren't particularly helpful.

**Comment by Devr-pro** [comment]
> I thought that was possibly the issue too at first but I tried it again just now to make sure and I'm still hitting a 500. Do you remember how you got things working?
Yes,  it was the only cause for my issue and after removing it all works fine now.

**Comment by dummdidumm** [comment]
It seems a related PR in supabase was merged, so I'm assuming it's something on their side so I'm closing the issue
