### ISSUE TITLE
SvelteKit and ESModules

### ISSUE THREAD

**Issue by rhernandog** [sveltejs/kit#9824]
### Describe the bug

Hi,

Hey everyone, I'm Rodrigo from the GreenSock team. We're getting a few questions about SvelteKit complaining about import statements outside a module. Everything was fine with this setup:
```
"@sveltejs/adapter-auto": "^1.0.0",
"@sveltejs/kit": "^1.0.0",
"svelte": "^3.54.0",
"svelte-check": "^2.9.2",
"typescript": "^4.9.3",
```

But with the latest versions:
```
"@sveltejs/adapter-auto": "^2.0.0",
"@sveltejs/kit": "^1.5.0",
"svelte": "^3.54.0",
"svelte-check": "^3.0.1",
"typescript": "^5.0.0",
```

Users are getting this error:
`SyntaxError: Cannot use import statement outside a module`

Now this is not a terrible deal since we do offer UMD modules that avoid this situation, but is certainly a bit annoying for users when they have to re-install their dependencies (for any reason) as mentioned here:

https://greensock.com/forums/topic/32926-problems-importing-scrolltrigger/#comment-183735

We'd like to have some sort of official word from the Svelte/SvelteKit team in order to explain that to users as well as give them the option of using the UMD modules to solve the problem.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-27qhsl?file=src%2Froutes%2F%2Blayout.svelte&terminal=dev

### System Info

```Shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz
    Memory: 8.50 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Managers:
    Apt: 2.4.8 - /usr/bin/apt
    Composer: 2.3.10 - /usr/local/bin/composer
  Utilities:
    Make: 4.3 - /usr/bin/make
    GCC: 11.3.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
  Servers:
    Apache: 2.4.52 - /usr/sbin/apachectl
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    VSCode: 1.77.3 - /snap/bin/code
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.34.0 - /usr/bin/perl
    PHP: 8.1.2 - /usr/bin/php
    Python3: 3.10.6 - /usr/bin/python3
  Databases:
    MySQL: 5.7.38 - /usr/bin/mysql
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 112.0.2
```

### Severity

annoyance

**Comment by benmccann** [comment]
This is because the `gsap` package is broken: https://publint.dev/gsap@3.11.5
