### ISSUE TITLE
Page does not reload when navigating back via back arrow button in browser

### ISSUE THREAD

**Issue by nekphal** [sveltejs/kit#9832]
### Describe the bug

When I navigate to a new page (see example below) and then press the back button of the browser, the url changes but the page content remains unchanged. Only when I manually reload the page, the correct content appears.

How i navigate to the new page:
`<a href="/service/{singleService.id}" class="service-name">{singleService.name}</a>`

### Reproduction

1. structure like this
![image](https://user-images.githubusercontent.com/73845523/235899111-d9ad0c22-29c5-4e90-8b5c-ac363e517b04.png)
2.  Navigate to `http://localhost:5173/?stackName=testStack` (normal +page.svelte) 
3. Click on Service of Stack and get redirected to `http://localhost:5173/service/testService` 
4.  Click on back-Button in Browser

Now the url has changed back to `http://localhost:5173/?stackName=testStack`, but the page content remains the same. Only when I reload the page (F5), the correct page or content is displayed. 

### System Info

```Shell
System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 3.03 GB / 15.09 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.63
    Firefox: 112.0.2
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.15.1 => 1.15.1 
    svelte: ^3.58.0 => 3.58.0 
    vite: ^4.2.1 => 4.2.1
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
Please provide a proper reproduction for the issue as instructed by the issue template:

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.

**Comment by jstet** [comment]
We have a similar problem on the [CorrelAid website](https://github.com/CorrelAid/correlaid_website). When navigating to a slug page from a parent page e.g. https://www.correlaid.org/veranstaltungen/ -> https://www.correlaid.org/veranstaltungen/open-onboarding-call-aug-23/ you cant navigate back to the parent page using the back button.

**Comment by ollyde** [comment]
Have the same issue, but difficult to replicate. Really crappy.

**Comment by MicrexIT** [comment]
I still experience the problem with svelte ^5.0.0-next.1

**Comment by Blue-Nomad** [comment]
I'm also having this issue. Only on mobile, pressing back sometimes resets the page, restting things like IntersectionObserver, and sometimes it returns to the state it was in when I navigated, with things like IntersectionObserver already run.

I've tried using afterNavigate to reset variables when going back but it doesn't work in these cases when the page doesn't rerun.
