### ISSUE TITLE
adapter-cloudflare: how do you do logs ?

### ISSUE THREAD

**Issue by happysalada** [sveltejs/kit#9834]
### Describe the problem

while running an application one needs to be able to read the emitted logs.
Cloudflare has a logs function that can capture logs from workers, however I haven't seen documented anywhere how you enable logs for a sveltekit app deployed with the adapter-cloudflare.
Any information on how to gather logs would be greatly appreciated.

### Describe the proposed solution

I have seen the wrangler.toml file edited to `log_push = true` , but there is no wrangler.toml file for the adapter-cloudflare.
So I don't know how to actually gather logs for a sveltekit deployed app.

### Alternatives considered

I would be happy to try anything if anyone has any idea.

### Importance

would make my life easier

**Comment by alesvaupotic** [comment]
I've added scripts to `package.json`:
```
"pages": "wrangler pages dev .svelte-kit/cloudflare",  
"tail": "wrangler pages deployment tail --project-name rcf",
```


More at https://developers.cloudflare.com/workers/wrangler/commands/#deployment-tail

**Comment by happysalada** [comment]
cloudflare also has the ability to push logs from workers to somewhere outside. Do you know how to do that ?
https://developers.cloudflare.com/logs/about/
I would like to not only have logs on streaming (or tail), but somewhere to store and access them later. Do you know how to do that ?

**Comment by alesvaupotic** [comment]
Oh, I misunderstood your request. Runtime logging is available on paid workers plans I believe. I have never used it.  Sorry I can't be of more assistance. Tried their Discord at https://discord.gg/cloudflaredev ?

**Comment by ghostdevv** [comment]
I'm not sure that pages has access to [`Workers Trace Events Logpush`](https://developers.cloudflare.com/workers/platform/logpush/), but at any rate definitely best to ask in the cloudflare discord

I'll close this for now but feel free to reopen if it's something that needs to be in the adapter and not another config specific to pages :pray:
