### ISSUE TITLE
Better skeleton template for Skeleton project and Package project

### ISSUE THREAD

**Issue by thetejasmagade** [sveltejs/kit#9836]
### **SvelteKit has awesome Skeleton template 💖💖** 

Currently, the **Normal Project** and **Package Project** templates in SvelteKit are a bit basic and may not provide the optimal starting point for these projects. Therefore, I propose improving these templates to provide a better starting point for developers.

### Describe the proposed solution

So, I think these two projects should also have better interactive skeleton template. I'll contribute for same issue/suggestion.

### **My approach**

- **Normal Skeleton Project:**  I will implement clean counter template for this project similar to SvelteKit's counter page which also have some important links regarding SvelteKit documentaion and tutorials.
- **Package Skeleton Project:**  I will implement informative template for this project which have nice and clean styling with some important links and documentation regarding packaging.

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
I'm not sure this is particularly actionable without more specifics. These apps aren't _supposed_ to be pretty. They're supposed to be as minimal as possible so that I can create a project, not have to delete anything, and be able to get right to building my project.

**Comment by Rich-Harris** [comment]
What @tcc-sejohnson — this is works-as-intended :)

**Comment by thetejasmagade** [comment]
Yeah! @tcc-sejohnson, @Rich-Harris I got it 👍🤝
