### ISSUE TITLE
target="_self" triggers hard navigation

### ISSUE THREAD

**Issue by GauBen** [sveltejs/kit#9842]
### Describe the bug

`<a href="page">` and `<a href="page" target="_self">` behave differently, despite `_self` being the default target value.

Without target (and with `target=""`), the client-side router works as expected. With `target="_self"`, the client-side router ignores the link and a hard navigation is performed, reloading the whole page.

I have pinpointed the bug to an incorrect `external` detection:

https://github.com/sveltejs/kit/blob/7a924137deb130708103644425b48bdc31927f93/packages/kit/src/runtime/client/utils.js#L132-L136

Instead of `!!target`, it should be something similar to `(target && target !== '_self')`, but more complicated because it needs to take `_parent` and `_top` into account.

The `target` logic is already implemented here:

https://github.com/sveltejs/kit/blob/7a924137deb130708103644425b48bdc31927f93/packages/kit/src/runtime/client/client.js#L1488-L1493

### Reproduction

https://github.com/GauBen/sveltejs-kit-_self-issue/

https://stackblitz.com/edit/sveltejs-kit-template-default-jv5xhh?file=src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.15.10 
    svelte: ^3.54.0 => 3.58.0 
    vite: ^4.3.0 => 4.3.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior. Treating `target=_self` as a full page reload is common to a lot of SPA frameworks, and predated SvelteKit's other mechanisms for disabling client-side navigation.

**Comment by GauBen** [comment]
Thanks for the answer @Conduitry

**Comment by PeppeL-G** [comment]
This just caused me to debug my website for a few hours; I had no idea `target="_self"` would introduce a different behavior.

Personally I would prefer if another attribute would be used to indicate a full page reload for links, because it's much easier for those that are looking for that functionality to search and find that attribute than it is for us who are unaware of the special `target="_self"` treatment to debug our code. Just my 2 cents!

**Comment by pepkin88** [comment]
> This is the intended behavior. Treating `target=_self` as a full page reload is common to a lot of SPA frameworks, and predated SvelteKit's other mechanisms for disabling client-side navigation.

This is new to me too. Can this behavior be at least documented [here](https://svelte.dev/docs/kit/link-options) and in the tutorial?

**Comment by brunnerh** [comment]
Would recommend opening a separate documentation issue.
