### ISSUE TITLE
2 nested forms don't work with SSR

### ISSUE THREAD

**Issue by sweetamino** [sveltejs/kit#9876]
### Describe the bug

Weird edge case I ran into but appears to be a bug. When there are 2 nested forms, SSR does not render them properly.

If you're wondering why I was trying to do this, I have a setup like: Settings menu modal with a form > Confirm irreversible settings change popup modal with a form. I am rendering my modals with a PortalToBody component, so the forms are not actually nested, they are both prepended to body in hooks.server.js and in my component mount/destroy for js. But in the component tree before transformPageChunk in hooks.server.js they are nested and SSR does not render them right. I was testing it works without JS but I found it did not because of this apparent bug. It probably makes more sense for me to just separate the forms anyway but I figured I'd post this anyway. Not sure if it deserves a fix. I can just move my "nested" form outside of the first in my case.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-dukfxd?file=src/routes/+page.svelte

### System Info

```Shell
System:
    OS: Linux 4.4 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 5.81 GB / 15.97 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1
    @sveltejs/kit: ^1.5.0 => 1.16.2
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.5

Browser: Chrome
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This is how browsers work - you can't nest `form` elements. See this Stackoverflow answer for more info and possible workarounds: https://stackoverflow.com/questions/379610/can-you-nest-html-forms
