### ISSUE TITLE
cookies inside endpoints called from `event.fetch` are not correctly set

### ISSUE THREAD

**Issue by david-plugge** [sveltejs/kit#9901]
### Describe the bug

When calling an endpoint from `event.fetch` that sets a cookie with `httpOnly: false` the actual response sets the cookie with `httpOnly: true`

### Reproduction

https://github.com/david-plugge-reproductions/sveltekit-fetch-httponly-cookie

### System Info

```Shell
System:
  OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
  CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Memory: 11.99 GB / 15.57 GB
  Container: Yes
  Shell: 5.8.1 - /usr/bin/zsh
Binaries:
  Node: 18.16.0 - /mnt/wslg/runtime-dir/fnm_multishells/197_1683713854937/bin/node
  npm: 9.5.1 - /mnt/wslg/runtime-dir/fnm_multishells/197_1683713854937/bin/npm
```

### Severity

blocking all usage of SvelteKit

**Comment by tcc-sejohnson** [comment]
I have this fixed locally -- just having to think through the ramifications. I'll try to get a PR open tomorrow.

**Comment by tcc-sejohnson** [comment]
Here's a draft PR: #9909

I'm not sure if it'll actually get merged (I have a couple of concerns about the implementation that I'm discussing with Rich), but it at least identifies and documents the issue.
