### ISSUE TITLE
$page.error incorrectly valorized in a specific situation with ssr false

### ISSUE THREAD

**Issue by raythurnvoid** [sveltejs/kit#9906]
### Describe the bug

My goal is to always render the `+error.svelte` page even when an error occurs in `handle.server.js` and to set the response's status to 500 when that happens.

When ssr is disables, calling `resolve` in `hooks.server.js`, throw an error in `+layout.server.js` and use the response body to return a 500 cause `$page.error` to be incorretly valorized.

```js
// hooks.server.js
export const handle = async (input) => {
	try {
		throw new Error('some logic throws')
	} catch (e) {
		const response = await input.resolve(input.event); // I want to show +error.svelte when an error occours here
		// return response; uncommenting this solves the issue but cause the status in the response to be 200
	
		const body = await response.text();
	
		const errorResponse = new Response(body, {
			status: 500,
			headers: response.headers
		});
	
		return errorResponse;
	}
};
```

```js
// layout.server.js
import { error } from '@sveltejs/kit';

export const load = () => {
	throw error(500, {
		message: 'test',
		stack: 'stack',
		cause: {}
	});
};
```

```js
// about/layout.js
export const ssr = false;

export const load = async () => {
	return {};
};
```

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-ujnvdm

the issue appears only in the `/about` page that has `ssr` set to `false` 

This is the issue:

```js
// $page.error

{
  "type": "data",
  "nodes": [
    {
      "type": "skip"
    },
    {
      "type": "error",
      "error": {
        "message": "test",
        "stack": "stack",
        "cause": {}
      },
      "status": 500
    },
    {
      "type": "skip"
    },
    {
      "type": "skip"
    }
  ]
}
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.1 
    @sveltejs/kit: ^1.5.0 => 1.16.3 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.5
```

### Severity

annoyance

**Comment by eltigerchino** [comment]
When SSR is turned off, the page is sent as an empty shell with some JSON data that is used to hydrate the page. However, when your error response text is passed to a new response, only the JSON part of that text is kept in the new body. This is an issue with the response body carrying over when the new Response class is instantiated.

Closing this since SvelteKit is working as expected.
