### ISSUE TITLE
Do not send router to MPAs

### ISSUE THREAD

**Issue by Thiagolino8** [sveltejs/kit#9920]
### Describe the problem

I recently made the same simple app using two frameworks for comparison, SvelteKit and Astro + svelte with a single reactive component in each
The component consisted of a large list of products fetched during server-side rendering and a search bar that filtered the list on the fly.
The app made using Astro resulted in an html file twice the size as it needed to serialize the product list, while the app made using SvelteKit did not as the data fetching was done in a universal load
Even so, the total size of the app created with SvelteKit was three times bigger than the app created using Astro due to the javascript sent, since both had only 1 identical component, I could only assume that the culprit for the size of the app was the client router, which was not being used since the app only had one page

### Describe the proposed solution

Don't send the router if:
- The app only has one page
- No page references another page of the same app
- All links are under the tag of a data-sveltekit-reload attribute

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
> - The app only has one page
> - No page references another page of the same app
> - All links are under the tag of a data-sveltekit-reload attribute

IMO, this is wayyyy too complicated a heuristic for a feature that's not likely to be useful for most people. If we expose a way to serve the app without a client-side router, it should just be an opt-in config option.

**Comment by Thiagolino8** [comment]
I really don't understand what the complexity would be to create the functionality, but at least from a pure guess it seems to me that:
- Among all the points, checking the number of pages is really quite simple.
- The anchor tag check suggested in points 2 and 3 is already something the framework does during pre-rendering

Anyway, if it really isn't feasible, an optional configuration would be good enough for me, but it would seem like an inferior experience to what the framework usually offers

**Comment by tcc-sejohnson** [comment]
> already something the framework does during pre-rendering

Sort of, but not really -- it's totally possible for a link to be part of a dynamic route that's not hit during prerendering (this is the whole point of `config.kit.prerender.entries` and the `entries` page-level export), and it's also possible to dynamically render links in such a way that we wouldn't ever see them during build (for example, in an `each` block that's only triggered under some runtime conditions). I don't think it's realistically possible for us to determine either one of these, but maybe Rich'll chime in with some magic solution.

**Comment by Thiagolino8** [comment]
Thanks for the explanation, now I understand the complexity a bit better
Apparently an opt-in config is the best you can get then
When I created the issue I thought it was just a nice thing to have, but on second thought it's not even the first professional project I've worked on where something like that would be useful
I think it would be something interesting for any MPA or One Page App

**Comment by Rich-Harris** [comment]
Comparisons like 'three times bigger' aren't all that valuable in this context, because we're talking about some fairly modest numbers. The amount of code we're talking about won't affect user experience at all, and will be overtaken by app code for anything non-trivial. (It will also be cached immutably, so the user only downloads it once.)

Building the framework in such a way that the router was optional would add considerable complexity, once you start to factor in things like 'beforeNavigate/afterNavigate callbacks still need to be called at the right time'. You'd basically be talking about maintaining two separate SvelteKit clients.

So the question is: is it worth the maintenance overhead? I would argue that it isn't, since there's essentially no real world impact.
