### ISSUE TITLE
[vercel] no dynamic environment variables on edge

### ISSUE THREAD

**Issue by jetaggart** [sveltejs/kit#9926]
### Describe the bug

If you set up a svelte project with 

```js
// svelte.config.js
import adapter from '@sveltejs/adapter-vercel';
// ...

	kit: {
		adapter: adapter({runtime: "edge"})
	}
```

And try to use environment variables:

```
import { env } from '$env/dynamic/public';
```

It will be empty. Static env vars seem to work fine. Dynamic env vars work fine on serverless.

### Reproduction

See description

### System Info

```Shell
Vercel edge
```

### Severity

blocking all usage of SvelteKit

**Comment by tcc-sejohnson** [comment]
Not a bug; read the last paragraph in the docs here: https://kit.svelte.dev/docs/adapter-vercel#environment-variables

You can either populate the config value mentioned there with the env vars you're using (to force-populate them dynamically in edge) or you can use static environment variables.

**Comment by jetaggart** [comment]
Ah, my bad, thank you!
