### ISSUE TITLE
Feature request: add yellow and red colors for server side console.warn() and console.error() methods

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sveltejs/kit#9931]
### Describe the problem

I have written some server side code lately which was fun but I noticed I had a hard time finding my console.logs compared to console logs in the browser.

I tried to accomplish this with the Vite customLogger option but it didn't really work because it only changes the Vite messages, not normal console.logs.

### Describe the proposed solution

I would like to see `console.warn()` get a yellow color and `console.error()` get a red color in the terminal in server side code.

SvelteKit already uses `kleur` which should be able to accomplish this.

I think if the `console.log()` color is unchanged and only `console.warn()` and `console.error()` are changed everyone would be happy, but this could also be a config option to opt-in.

### Alternatives considered

Just use kleur which works fine but would be nicer to just use console.warn() and console.error().

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
I personally don't think this is something Kit should bother with -- like you said, the solution here is just to install `kleur` or some other CLI color helper.

**Comment by Conduitry** [comment]
I'm also -1 on patching the built-in `console.*` function. That doesn't sound like the framework's area of responsibility, and sounds like it's asking for trouble if some user's application is doing its own patching of them.
