### ISSUE TITLE
'typeof TableSearch__SvelteComponent_' is not assignable of type 'Constructor<SvelteComponentDev>'

### ISSUE THREAD

**Issue by cmjoseph07** [sveltejs/kit#9932]
### Describe the bug

Not sure what is going on and I can't find any similar errors in recent history on Github or Discord. When I am trying to render a Svelte component for testing following @testing-librart/svelte I am getting this crazy Typescript error but the test seem to be functioning fine. 

It seems to want to be of type SvelteConponentDev but if I try to use `as typeof SvelteConponentDev` I get an error saying it's already typed. Can anyone advise me if this is a mistake on my part or a bug that has just sprung up?

### Reproduction

```Typescript
import { render, fireEvent, cleanup } from '@testing-library/svelte';
import { describe, it, expect, afterEach, vi } from 'vitest';

import { DataHandler } from '@vincjo/datatables';
import TableSearch from './TableSearch.svelte';

// Mock DataHandler
class MockDataHandler extends DataHandler {
  search(query: string) {
    query;
  }
}

describe('TableSearch.svelte', () => {
  afterEach(() => {
    cleanup();
  });

  it('renders TableSearch component', () => {
    const { getByTestId } = render(TableSearch, { props: { handler: new MockDataHandler() } });
    expect(getByTestId('table-search-form')).toBeTruthy();
  });

  it('renders search input field with correct attributes', () => {
    const { getByTestId } = render(TableSearch, { props: { handler: new MockDataHandler() } });

    const input = getByTestId('table-search-input'); // Use getByTestId to find the input element
    expect(input).toBeTruthy();
    expect(input.className).toContain('transition-all');
  });

  it('calls handler search method when input is changed', async () => {
    const handler = new MockDataHandler();
    const searchMock = vi.spyOn(handler, 'search');
    const { getByTestId } = render(TableSearch, { props: { handler } });

    const input = getByTestId('table-search-input');
    await fireEvent.input(input, { target: { value: 'test query' } });

    expect(searchMock).toHaveBeenCalled();
    expect(searchMock).toHaveBeenCalledWith('test query');
  });
});
```

### Logs

```Shell
No overload matches this call.
  Overload 1 of 2, '(component: Constructor<SvelteComponentDev>, componentOptions?: SvelteComponentOptions<SvelteComponentDev> | undefined, renderOptions?: Omit<...> | undefined): RenderResult<...>', gave the following error.
    Argument of type 'typeof TableSearch__SvelteComponent_' is not assignable to parameter of type 'Constructor<SvelteComponentDev>'.
      Type 'TableSearch__SvelteComponent_' is missing the following properties from type 'SvelteComponentDev': $set, $on, $destroy, $$prop_def, and 5 more.
  Overload 2 of 2, '(component: Constructor<SvelteComponentDev>, componentOptions?: SvelteComponentOptions<SvelteComponentDev> | undefined, renderOptions?: RenderOptions<...> | undefined): RenderResult<...>', gave the following error.
    Argument of type 'typeof TableSearch__SvelteComponent_' is not assignable to parameter of type 'Constructor<SvelteComponentDev>'.ts(2769)
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
    Memory: 219.06 MB / 1.86 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.1 => 2.0.1
    @sveltejs/adapter-node: ^1.2.4 => 1.2.4
    @sveltejs/kit: ^1.16.3 => 1.16.3
    @sveltejs/vite-plugin-svelte: ^2.2.0 => 2.2.0
    svelte: ^3.59.1 => 3.59.1
    vite: ^4.3.5 => 4.3.5
```

### Severity

annoyance

**Comment by tcc-sejohnson** [comment]
cc @dummdidumm, the typing guru

**Comment by jasonlyu123** [comment]
This might be an issue for the typescript-plugin in language tools. It's probably because a global shim file is not being loaded correctly and has nothing to do with SvelteKit. Some of the situations are fixed, but there is a situation we can't reproduce consistently to investigate. And that will disappear when you restart the TSServer. If that doesn't work for you, we'll need a reproduction repository.

**Comment by cmjoseph07** [comment]
@jasonlyu123 When I restart the TSServer, the errors come right back. They don't disappear. Do you think it has something to do with my app.d.ts or a node module that I might have downloaded? I am not sure how I am the only person with this type of error. I feel like it has to be something with my setup at this point.

**Comment by cmjoseph07** [comment]
Okay, I just noted the error only pops up after I run vitest. If I restart the TS server is seems to be fine but running the vitest the typescript errors appear. Does this mean I should be looking into vitest more instead?

**Comment by jasonlyu123** [comment]
I'll see if I can reproduce it with vitest. I think it's triggering something instead of a direct cause. I have seen a similar problem with vanilla svelte, no kit, and no vitest. So it should be a more general problem.

**Comment by cmjoseph07** [comment]
@jasonlyu123 I am using sveltekit and vitest but yeah I think it has to be a config problem or something with vitest at this point. I will close this and move my issue over there. Thanks!
