### ISSUE TITLE
Accessibility concerns on create-svelte template

### ISSUE THREAD

**Issue by malko** [sveltejs/kit#9954]
### Describe the problem

When creating an app with ```npm create svelte@latest my-app``` the app.html file contains the following code:
```<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<link rel="icon" href="%sveltekit.assets%/favicon.png" />
		<meta name="viewport" content="width=device-width" />
		%sveltekit.head%
	</head>
	<body data-sveltekit-preload-data="hover">
		<div style="display: contents">%sveltekit.body%</div>
	</body>
</html>
```

My concerns is that the display: contents is reported as having accessibility issues in browsers as stated here: https://developer.mozilla.org/en-US/docs/Web/CSS/display-box#accessibility_concerns
So the results can lead to a full app which can't be used with screen readers which is really not a good default.

### Describe the proposed solution

either choose another display value or remove completely the declaration and use the default display value.

### Alternatives considered

use either display: block or don't set anything as div are block by default

### Importance

would make my life easier

**Comment by malko** [comment]
PR proposed #9956

**Comment by Rich-Harris** [comment]
The accessibility concerns you mention don't apply in this situation, to the best of our research — they're specific to things like tables and buttons. Is there a specific bug you've encountered, or is this more of a vague concern?

**Comment by geoffrich** [comment]
Yeah, last time I looked into this, the `display: contents` accessibility bug only affected semantic elements like `<ul>`. It shouldn't have any effect on divs: https://github.com/sveltejs/svelte/issues/6268#issuecomment-864665450

Though if you have a specific screen reader / browser combination that is unable to use a SvelteKit app due to `display: contents`, we'd want to know about it.

**Comment by malko** [comment]
> The accessibility concerns you mention don't apply in this situation, to the best of our research — they're specific to things like tables and buttons. Is there a specific bug you've encountered, or is this more of a vague concern?
This is more a vague concerns as I didn't have capacity to test all browsers versions to check that more in depth. 
If this is already known and a conscient decision, I have nothing more to say, I haven't found sveltejs/svelte#6268 so thought it was not already known. You can then safely ignore this issue and the associated PR (thanks for the quick reply)
