### ISSUE TITLE
Assets not output when imported in +page.server.ts

### ISSUE THREAD

**Issue by liegeandlief** [sveltejs/kit#9961]
### Describe the bug

I previously raised this bug - https://github.com/sveltejs/kit/issues/8224

It was closed because it was a duplicate of https://github.com/sveltejs/kit/issues/5240 which has been closed as resolved by https://github.com/sveltejs/kit/pull/9073

But this is still an issue for me. The problem doesn't occur when running the dev server only when running `vite build` and `vite preview`. I am using the 

Is there something I need to do to get this to work?

### Reproduction

See https://github.com/sveltejs/kit/issues/8224

### System Info

```Shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 3.3.0 - ~/.volta/tools/image/yarn/3.3.0/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/npm/9.5.1/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 113.0
    Safari: 16.4
  npmPackages:
    @sveltejs/adapter-vercel: ^2.0.2 => 2.4.3
    @sveltejs/kit: ^1.0.0 => 1.16.3
    svelte: ^3.44.0 => 3.59.1
    vite: ^4.0.0 => 4.3.7
```

### Severity

serious, but I can work around it

**Comment by Serator** [comment]
It doesn't work for me too. Does anyone have a solution to this issue?

**Comment by s3812497** [comment]
Can you please provide a minimal reproduction in the form of a repository?

**Comment by s3812497** [comment]
@Serator I can't confirm if this is a bug or intended behaviour. The assets are included in the build as server assets (which are not publicly exposed), but we want to publicly expose them (client assets). This should automatically occur for assets imported in client-side code (+page.js, +page.svelte, etc.), but not server code (+server.js, etc.).

The only solution I know to this is to include your files in the `static` directory and provide the absolute path to them `/icon-192.png`. This has its drawbacks and perhaps there should be way to import them through Vite but still work?

**Comment by Serator** [comment]
> ... to include your files in the `static` directory and provide the absolute path to them `/icon-192.png`.

That's exactly what I did, but in the long run I'd like to be able to add assets without this trick.

**Comment by Serator** [comment]
> A hacky workaround is to just arbitrarily include it in client-side code.

This looks like a hack and it's going to be hard to figure out what's going on here, even though that's what works.

**Comment by s3812497** [comment]
The solution might best be provided by Vite and so I've provided feedback here https://github.com/vitejs/vite/discussions/13808

**Comment by Serator** [comment]
@s3812497 What do you mean by `prod environment`? Could you please tell more about it or give a link to the documentation?

**Comment by s3812497** [comment]
> @s3812497 What do you mean by `prod environment`? Could you please tell more about it or give a link to the documentation?

`adapter-auto` automatically installs a suitable adapter by detecting the production environment based on these environment variables https://github.com/sveltejs/kit/blob/master/packages/adapter-auto/adapters.js

e.g., `VERCEL=1` is present when deploying to the Vercel platform (the production environment) so `adapter-vercel` is installed and used to build.

If you see this warning after building your app with `adapter-auto`, the bug will occur.
```bash
> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
```

**Comment by liegeandlief** [comment]
@s3812497 I explicitly set `adapter` to the Vercel adapter in my Svelte config and still have this issue

**Comment by s3812497** [comment]
> @s3812497 I explicitly set `adapter` to the Vercel adapter in my Svelte config and still have this issue

Is it still an issue when deployed to Vercel or just when previewing with `npm run preview`?
It seems the `vite preview` still uses the output from `.svelte-kit` which does not concatenate the server and client assets. However, the final build `.vercel` does have them concatenated.

**Comment by liegeandlief** [comment]
@s3812497 I've just tested this for the first time in a while and it seems to be working now when running preview and build 🎉

**Comment by Serator** [comment]
@s3812497, @liegeandlief I tried building the project and running in preview mode, but it still doesn't work for me either with `VERCEL=1` + `@sveltejs/adapter-auto` or `@sveltejs/adapter-vercel`. Maybe you have a working example? Thanks.

**Comment by s3812497** [comment]
> @s3812497, @liegeandlief I tried building the project and running in preview mode, but it still doesn't work for me either with "`VERCEL=1` + `@sveltejs/adapter-auto`" or "`@sveltejs/adapter-vercel`". Maybe you have a working example? Thanks.

Sorry, I just discovered preview mode will not work for any adapter but the build output should be fine when deploying. I have a fix in the works that should make preview mode copy over the right server assets.

**Comment by Serator** [comment]
@s3812497 Now it's working for me. Thank you!
