### ISSUE TITLE
Begin Adapter Confusion

### ISSUE THREAD

**Issue by Shaun-Regenbaum** [sveltejs/kit#998]
It seems that the current begin adapter tries to export using esmodules, but svelte config uses require. Is this intentional? Or should something be clarified in the documentation? There is also a disconnect between sveltekit documentation for adapters and the begin adapter readme.

**Comment by benmccann** [comment]
There's a new version of the Begin adapter. Please take a look at https://github.com/architect/sveltekit-adapter
