### ISSUE TITLE
`base` in `$app/paths` is empty on the root page but the type says it can't be

### ISSUE THREAD

**Issue by utkarshkukreti** [sveltejs/kit#9985]
### Describe the bug

The [type of `base` is](https://github.com/sveltejs/kit/blob/195e9ac2233776ecf1aff7dadbadd7226f68e8dd/packages/kit/types/ambient.d.ts#L295):

    export const base: `/${string}`;

but the value of `base` on the root page is the empty string (reproduction link below).

I'm not sure if the type is wrong or `base` should be `"/"` for the root page.

<img width="1231" alt="CleanShot 2023-05-19 at 15 14 14@2x" src="https://github.com/sveltejs/kit/assets/217126/f30b6b82-1acc-4acc-b130-70343345d0f7">

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-afkmfp?file=src%2Froutes%2F%2Bpage.svelte&terminal=dev

(The only file I changed from the default template is `routes/+page.svelte`.)

```
<script>
	import { base } from '$app/paths'
</script>

{JSON.stringify([base, base.length])}
```

On the root page, the output is:

```
["",0]
```

### System Info

```Shell
npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0
    @sveltejs/kit: ^1.5.0 => 1.18.0
    svelte: ^3.54.0 => 3.59.1
    vite: ^4.3.0 => 4.3.8
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
Fixed in 1.19 via https://github.com/sveltejs/kit/pull/9992. This is why friends don't let friends hand-write `.d.ts` files
