### ISSUE TITLE
500 Error when fetching the head of a Kit project

### ISSUE THREAD

**Issue by mattpilott** [sveltejs/kit#9986]
### Describe the bug

Vercel returns `x-vercel-error: INTERNAL_SERVER_ERROR` when fetching the head of a Svelte Kit site, like so:

- `curl -I https://sveltesnaps.vercel.app/` this is a Rich Harris project
- `curl -I https://surreyescapes.com` one of mine
- `curl -I https://kit-500.vercel.app` a blank kit project a made and deployed (https://github.com/mattpilott/kit-500)

### Reproduction

https://github.com/mattpilott/kit-500

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 474.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/bin/node
    npm: 9.6.5 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 112.0.2
    Safari: 16.5
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
Looks like something Vercel specific, I didn't get any errors with adapter-node. Even on adapter-vercel, I don't think there's anything that'd cause it to error specifically on head requests.

**Comment by mattpilott** [comment]
Interestingly, swapping from adapter-auto to adapter-vercel seems to fix the error

**Comment by mattpilott** [comment]
Unsure how adapter-auto works, i thought it just used adapter-vercel under the hood if it detected that was the host

**Comment by mattpilott** [comment]
It looks like this is now resolved, closing.
